### ISSUE TITLE
[flaky test]: Dynamic Provisioning should create a volume on demand with useDataPlaneAPI

### ISSUE THREAD

**Issue by krzysiekg** [kubernetes/kubernetes#100097]
#### Which jobs are flaking:
pull-kubernetes-e2e-azure-file-windows

#### Which test(s) are flaking:
Dynamic Provisioning should create a volume on demand with useDataPlaneAPI [kubernetes.io/azure-file] [file.csi.azure.com] [Windows]

#### Testgrid link:
https://testgrid.k8s.io/provider-azure-presubmit#pr-k8s-azure-file-e2e-master-windows 

#### Reason for failure:
```
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/dynamic_provisioning_test.go:646
Unexpected error:
    <*errors.errorString | 0xc000aced90>: {
        s: "PersistentVolumeClaims [pvc-mtnvw] not all in phase Bound within 5m0s",
    }
    PersistentVolumeClaims [pvc-mtnvw] not all in phase Bound within 5m0s
occurred
/home/prow/go/src/sigs.k8s.io/azurefile-csi-driver/test/e2e/testsuites/testsuites.go:219
```

#### Anything else we need to know:
Triage:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&job=kubernetes-e2e-azure-file-windows&test=Dynamic%20Provisioning%20should%20create%20a%20volume%20on%20demand%20with%20useDataPlaneAPI

Spyglass:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99970/pull-kubernetes-e2e-azure-file-windows/1369560307927617536
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99970/pull-kubernetes-e2e-azure-file-windows/1369599252451299328
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99970/pull-kubernetes-e2e-azure-file-windows/1369435530026029056

**Comment by andyzhangx** [comment]
fixed by https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/592, won't run this test for in-tree driver any more
