### ISSUE TITLE
EndpointSlice Controllers create duplicate EndpointSlices in certain cases

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#100033]
#### What happened:
The controllers can create a second EndpointSlice after an immediate sync if the first EndpointSlice they created is not in the cache yet. Here's what can happen:

1. Controller gets event that triggers sync for Service
2. Controller syncs and creates EndpointSlice
3. Controller gets event that triggers sync for same Service
4. Controller syncs and creates EndpointSlice (the slice created in 2 has not made it to the cache yet)

#### What you expected to happen:
A single EndpointSlice to be created.

#### How to reproduce it (as minimally and precisely as possible):
Run integration tests hundreds of times that involve 2 consecutive events that will trigger a sync. Example: https://github.com/kubernetes/kubernetes/pull/100025#issuecomment-794454897.

/assign
/sig network

**Comment by robscott** [comment]
When this bug is fixed, we'll need to rollback https://github.com/kubernetes/kubernetes/pull/100027.

**Comment by aojea** [comment]
> When this bug is fixed, we'll need to rollback #100027.

just amend it in the PR that fix the bug, so we merge all together
