### ISSUE TITLE
newTestResourceQuota causes clusters to fail conformance when they probably shouldn't

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#100016]
#### What happened:
I ran conformance tests on a cluster that had a controller enabled that syncs a configmap across all clusters. It failed:
```
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
Mar  5 11:07:41.670: Unexpected error:
    <*errors.StatusError | 0xc001452500>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "configmaps \"test-configmap\" is forbidden: exceeded quota: test-quota, requested: configmaps=1, used: configmaps=2, limited: configmaps=2",
            Reason: "Forbidden",
            Details: {
                Name: "test-configmap",
                Group: "",
                Kind: "configmaps",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    configmaps "test-configmap" is forbidden: exceeded quota: test-quota, requested: configmaps=1, used: configmaps=2, limited: configmaps=2
occurred
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/resource_quota.go:336
```

Appears to be due to a 2 configmap limit: https://github.com/kubernetes/kubernetes/blob/02b9dd6a6e7d2928945afa4b8aedd7650d6d4cab/test/e2e/apimachinery/resource_quota.go#L1481

#### What you expected to happen:
These clusters should pass conformance. This is a very common pattern (even Kubernetes itself does it!).

#### How to reproduce it (as minimally and precisely as possible):

I didn't run it myself, but apparently just install Istio and run the conformance suite. See https://github.com/istio/istio/issues/31312 for details

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.2

**Comment by liggitt** [comment]
my guess is the CA configmap created by default in 1.20 exacerbated this issue. I agree the conformance test should make fewer assumptions about the cluster it is running in and should accomodate default configmaps. left a comment on the PR in flight for this. I'd like to see the change picked to 1.20 as well.
