### ISSUE TITLE
SSA triggers update events on apply to resource when it is no-op

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes/kubernetes#100024]
#### What happened:

Using SSA patch to create and manage a couple of resources (specifically [those](https://github.com/openshift/cluster-cloud-controller-manager-operator/tree/fffa7104273622e6d0720c38b72735f9693646ae/pkg/cloud/openstack/assets), the list may change in the future) resulted in endless hot loop, as each apply increases `resourceVersion` of the resource even if this is a no-op.

#### What you expected to happen:

Apply resources once to establish ownership on the fields and forget. Operator should not be triggered by constant `resourceVersion` changes if does not change any object spec or metadata by a new patch.

#### How to reproduce it (as minimally and precisely as possible):

Take a sample Deployment or other resource and forcefully apply it multiple times using controller-runtime client.

![hot-loop-ssa](https://user-images.githubusercontent.com/32226600/110516907-748d3780-810a-11eb-91d8-6ef203645bfc.gif)

#### Anything else we need to know?:

This issue appeared using controller-runtime client implementation, but could be present in other clients.  `kubectl` is not affected. 

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.0+aa519d9 and before
- Cloud provider or hardware configuration: aws/openstck, does not matter
- OS (e.g: `cat /etc/os-release`): ~
- Kernel (e.g. `uname -a`): ~
- Install tools: ~
- Network plugin and version (if this is a network-related bug): ~
- Others: ~

/sig api-machinery
/wg api-expression

**Comment by apelisse** [comment]
Can you show me the exact object after it's been applied (as returned by the apiserver in the apply request) and the object that you intended to apply (as seen in the file, before it's been decoded). That would greatly help me understand what's going on, thanks!

**Comment by Danil-Grigorev** [comment]
@apelisse Sure. Here are a couple of pastebins:
- `Deployment` before and after (not the first apply): https://pastebin.com/gLGkhbLX
- `ConfigMap` before and after (again, some Nth unchanged apply): https://pastebin.com/sdj0pLfP
- `ConfigMap` over time (triggered by other resource updates): https://pastebin.com/tWFUAe9B Here you can see how the `resourceVersion` rises over time.

It was using controller-runtime client, and applying golang kapi structure.

**Comment by apelisse** [comment]
@jpbetz I'm working on an alternative understanding here, but would you believe this will be fixed in 1.21?

**Comment by apelisse** [comment]
There's a slight bug with creationTimestamp being cleared AFTER we've updated the timestamp, I'm inverting these two operations, that will help BUT that doesn't mean that using client-go to apply is the right thing to do.

**Comment by jpbetz** [comment]
> BUT that doesn't mean that using client-go to apply is the right thing to do.

Using the go structs to construct apply requests is something we know is unsound. Here's an example of what can go wrong: https://github.com/kubernetes/kubernetes/pull/99462#discussion_r589109539

The typesafe apply support we're adding in 1.21 (https://github.com/kubernetes/enhancements/issues/2155) solves the problem. I highly recommend migrating to that once its available. It avoid this particular issue as well as all the soundness issues that arise when marshaling go structs to create apply requests.

**Comment by palnabarun** [comment]
@Danil-Grigorev -- since SSA has opted out of the v1.21, can I retarget this for v1.22?

**Comment by apelisse** [comment]
there is a main new solution that was pushed as 1.21, and a smaller fix that will be merged in 1.22

**Comment by palnabarun** [comment]
@apelisse -- in light of that, can we remove the v1.21 milestone?

**Comment by voigt** [comment]
Hey there, Bug-Triage here 👋 ,
Given the fact that the code freeze for 1.22 already started and this issue has been moved from release to release, I'm clearing the milestone label for this issue.

Feel free to assign it to an appropriate milestone again, once this issue is under active development again.

/milestone clear

**Comment by liggitt** [comment]
was this resolved in 1.22?

**Comment by apelisse** [comment]
Yes, this is solved by using the "apply client" rather than the regular typed clients.

**Comment by apelisse** [comment]
We have a fix for that but it didn't make it to code-freeze, we'll back-port in many releases later.

**Comment by liggitt** [comment]
is this the same issue as #95460? should this be deduped to that one (or vice-versa)?

**Comment by apelisse** [comment]
Yeah, they may not be the exact same underlying reason, but they should have the same fix.

/close
