### ISSUE TITLE
Publish kubernetes protocol definitions as .proto files

### ISSUE THREAD

**Issue by roboslone** [kubernetes/kubernetes#100080]
_This is probably not a right place to request this, but I didn't find anything on discuss.kubernetes.io or Google._

I have a number of services around kubernetes cluster, that would greatly benefit from original protocol definitions used by kubernetes itself. For example I could have a gRPC handler returning deployments/services/pods currently running in my cluster with some additional metainfo outside of kubernetes:

```
message Response {
    my_namespace.DeploymentMeta meta = 1;
    k8s.apps.v1.Deployment deployment = 2;
}

service MyAwesomeService {
    rpc ListDeployments (google.protobuf.Empty) returns (stream Response);
}
```

To achieve this I would need original `.proto` files for stuff I'm interested in (e.g. `Deployment`, `Service`, `Pod`, `DaemonSet`, etc.), but I didn't find it anywhere (I think I read somewhere that protobuf definitions are actually generated from Go-structs).
Also it would be great to have functions for conversion from Go-struct and protobuf message and back.

Is is possible to provide these things?

**Comment by liggitt** [comment]
The generated .proto files are available in https://github.com/kubernetes/api (e.g. https://github.com/kubernetes/api/tree/master/core/v1/generated.proto)

However, the wire format Kubernetes uses for proto serialization prefixes with "k8s0" and always includes an envelope type (runtime.Unknown) which describes the apiVersion and kind of the message. See https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/serializer/protobuf/protobuf.go for implementation details. This allows messages to self-identify their type, but means adaptation is needed to work with typical proto libraries not expecting an envelope object (stripping the "k8s0" prefix and two decode steps are needed)

**Comment by roboslone** [comment]
Seems like that's what I need (it's not too convenient since I would need to also make some apimachinery proto-files available to my local build tool as well, but it's better than nothing :)).

I'm not too worried about wire format since I'll be using Go-client to communicate with k8s API anyway, I only want to expose k8s entities in my RPCs.

Thanks, @liggitt!

**Comment by liggitt** [comment]
One note, if you are intending to use these type definitions in your own API, is that I would *strongly* recommend only using GA versions (not alpha or beta), since conversion logic between versions is only known to the kube-apiserver, and pre-GA types have a bounded lifetime before removal.
