### ISSUE TITLE
A pod in a Statefulset is not restarted if its init container is failing

### ISSUE THREAD

**Issue by dannyzaken** [kubernetes/kubernetes#100094]
#### What happened:
* I got into a situation where the init container image of a pod in a statfulset contains a code that is failing to run successfully. 
* I updated the statefulset with an image that should run the init to completion
* The pod is never updated with the new init container. it keeps failing during the init stage
* only explicit deletion of the pod fixes the issue

#### What you expected to happen:
* expected the pod to restart with the correct init container image

#### How to reproduce it (as minimally and precisely as possible):
* deploy a statefulset with an init container
* after it's ready, cause the init container to fail and restart the pod (I changed the command to `exit 1`)
* the pod should restart and fail init
* update the init container image in the STS to a different image
* see that the pod is not restarting and stays in a failed state

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T03:27:49Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
running on minikube
```
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
```

**Comment by gjkim42** [comment]
Tested similar cases
- Pod: can't update fields spec.container[*].command(no issue)
- Deployment: updated properly(no issue)
- Statefulset: could reproduce issue

**Comment by cbandy** [comment]
Discussed in #67250.

**Comment by soltysh** [comment]
> Discussed in #67250.

Closing as duplicate.
/close
