### ISSUE TITLE
The logic to determine if node is known in node lifecycle controller is overly simple which can potentially lead to werid behavior

### ISSUE THREAD

**Issue by visunali** [kubernetes/kubernetes#100022]
#### What happened:
We found out race condition could potentially occur in node lifecycle controller when a worker node is terminated and another worker node **with same name** spins up before pod eviction timeout.

Node lifecycle controller keeps monitoring the health report from worker node. [If it didn't get this report, it will mark condition status as Unknown](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1092). When a worker node is taking off, we are seeing following log repeatedly showing from node lifecycle controller below then at a certain point of time it stopped warning because node lifecycle controller received heartbeat from another node with same name and "thought" it was the node that got terminated before.

```
2021-02-03 16:32:42.000 I0203 16:32:42.147242 1 node_lifecycle_controller.go:1127] node XXXXX hasn't been updated for 1m40.32969872s. Last Ready is: &NodeCondition{Type:Ready,Status:Unknown,LastHeartbeatTime:2021-02-03 16:29:23 +0000 UTC,LastTransitionTime:2021-02-03 16:31:41 +0000 UTC,Reason:NodeStatusUnknown,Message:Kubelet stopped posting node status.,}
```

[If this situation continues for a certain period of time (pod-eviction-timeout, 5min by default)](https://t.corp.amazon.com/P44607680/communication), node controller will take some actions.

However, another new node with same name appears before timeout. So NLC thought it was the same node.

NLC first [fetches all nodes](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L759), then [classify nodes](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L763) to newly-added nodes, deleted nodes based on its known node set. The [logic to classify nodes](https://github.com/kubernetes/kubernetes/blob/27c89b9aec73f66529a497910c460af2b25ab6dd/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1338) is quite simple by just comapring the node name with its known set. Given node name is identical to the node that's terminated, NLC thought it was the same node and keeps it in its known node set, however, under the hood, it's the new node that's sending heartbeat.

Due to this, by running `kubectl describe node xxxx` we are seeing information (providerID, labels, etc.) is associated with the worker node that's terminated while ago instead of new node. And node terminated long time ago is still sending heartbeat somehow.

#### What you expected to happen:
Node lifecycle controller should be able to distinguish between newly-added and deleted nodes and update node set correctly even if they have identical node name. And eventually it's expected to list correct information of the node with same name by running `kubectl describe node xxxx`.

#### How to reproduce it (as minimally and precisely as possible):
It's easy to reproduce the issue by taking down a worker node and launching a new node with same node name before pod eviction timeout.

#### Environment:
- Kubernetes version (use `kubectl version`): This issue is present in all versions
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): (This issue is related to logic in node lifecycle controller.)
- Kernel (e.g. `uname -a`): (This issue is related to logic in node lifecycle controller.)
- Install tools: (This issue is related to logic in node lifecycle controller.)
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by visunali** [comment]
We are using AWS EKS which is using private DNS name as node name. There is likelihood that EC2 can select exactly same private DNS name for new node after another node with same name gets terminated.

**Comment by anguslees** [comment]
> We are using AWS EKS which is using private DNS name as node name. There is likelihood that EC2 can select exactly same private DNS name for new node after another node with same name gets terminated.

Sounds like we should use providerID (aka EC2 instance-id) as the node name...
