### ISSUE TITLE
client-side `kubectl apply` does not use strategic merge patch info in openapi for unknown types

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#100012]
#### What happened:

Tried to use `kubectl apply` with an old release of kubectl against a new version of an existing built-in type

#### What you expected to happen:

`kubectl apply` (with client-side apply) should honor advertised strategic-merge-patch directives like `patchStrategy=replace` published in the openapi for the new type.

#### How to reproduce it (as minimally and precisely as possible):

(hoisted from https://github.com/kubernetes/kubernetes/pull/99290#discussion_r589566260 while experimenting with PodDisruptionBudget v1; these exact types won't work until that PR merges, but any type that supports strategic merge patch that is not known to an old kubectl version would work)

v1beta1.yaml:
```yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mypdb
spec:
  minAvailable: 2
```

v1.yaml:
```yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mypdb
spec:
  minAvailable: 2
```

using a new kubectl aware of the new go type works as expected:

```
$ kubectl apply -f v1beta1.yaml --v=9 2>&1 | egrep "PATCH.*Content-Type"
```

> I0308 22:19:09.677423   69774 round_trippers.go:435] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: **application/strategic-merge-patch+json**" -H "User-Agent: kubectl/v1.21.0 (darwin/amd64) kubernetes/d35ba15" 'https://localhost:6443/apis/policy/v1beta1/namespaces/default/poddisruptionbudgets/mypdb?fieldManager=kubectl-client-side-apply'

```
$ kubectl apply -f v1.yaml --v=9 2>&1 | egrep "PATCH.*Content-Type"
```

> I0308 22:20:47.751304   70024 round_trippers.go:435] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: **application/strategic-merge-patch+json**" -H "User-Agent: kubectl/v1.21.0 (darwin/amd64) kubernetes/d35ba15" 'https://localhost:6443/apis/policy/v1/namespaces/default/poddisruptionbudgets/mypdb?fieldManager=kubectl-client-side-apply'`

using an old kubectl that doesn't have the v1 go type compiled in does not send the expected patch type:

```
$ kubectl-1.19 apply -f v1beta1.yaml --v=9 2>&1 | egrep "PATCH.*Content-Type"
```

> I0308 22:21:14.547349   70073 round_trippers.go:424] curl -k -v -XPATCH  -H "Content-Type: **application/strategic-merge-patch+json**" -H "User-Agent: kubectl-1.19/v1.19.7 (darwin/amd64) kubernetes/a5dcd0c" -H "Accept: application/json" 'https://localhost:6443/apis/policy/v1beta1/namespaces/default/poddisruptionbudgets/mypdb?fieldManager=kubectl-client-side-apply'

```
$ kubectl-1.19 apply -f v1.yaml --v=9 2>&1 | egrep "PATCH.*Content-Type"
```

> I0308 22:21:52.086715   70108 round_trippers.go:424] curl -k -v -XPATCH  -H "Accept: application/json" -H "Content-Type: **application/merge-patch+json**" -H "User-Agent: kubectl-1.19/v1.19.7 (darwin/amd64) kubernetes/a5dcd0c" 'https://localhost:6443/apis/policy/v1/namespaces/default/poddisruptionbudgets/empty-v1beta1?fieldManager=kubectl-client-side-apply'

It looks like kubectl doesn't send strategic merge patches for unknown types, even if the openapi schema indicates they are supported:

https://github.com/kubernetes/kubernetes/blob/4fccba9e068f31a562f753caf4b37959b4ef829a/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L120-L166

Notably, `kubectl apply --server-side` handles this scenario like a champ :)

/sig cli

cc @apelisse @mengqiy

**Comment by ardaguclu** [comment]
The point that I don't understand about this issue; nowhere in the code(highlighted or even in whole file https://github.com/kubernetes/kubernetes/blob/4fccba9e068f31a562f753caf4b37959b4ef829a/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L120-L166) is set patchType to `JSONPatchType(application/json-patch+json)`.

**Comment by apelisse** [comment]
Apply never uses `JSONPatchType`. It uses strategic merge patch for built-in types, and json merge patch for CRs.

**Comment by ardaguclu** [comment]
I investigated this problem but it looks that there is no elegant way discriminating whether resource is CRD or it is core type but new version does not exist.

`runtime.IsNotRegisteredError(err)` check in [here](https://github.com/kubernetes/kubernetes/blob/c0562815fada455daf4826f59df895942dad8df0/staging/src/k8s.io/kubectl/pkg/cmd/apply/patcher.go#L123) is for CRDs in order to use json merge patch. In our case, v1 version of `PodDisruptionBudget` also gets this error(because it really does not exist in older version of kubectl schema) and as expected it fails during json merge patch.

We can use openAPISchema to check `PodDisruptionBudget` exists or not. But that time CRDs also exist in openAPISchema and kubectl start using strategic merge patch for CRDs.

We need to identify resource is CRD or core type via openAPISchema if resource gets `runtime.IsNotRegisteredError` but I could not find a better way to achieve this(other than checking the api version is `apiextensions.k8s.io`?).

WDYT @liggitt @apelisse ?

**Comment by apelisse** [comment]
The OpenAPI schema advertises the types of patch available on each endpoint, so basically, you could build a strategic-merge-patch if it's supported, fallback to json merge patch if it's not? That information is available in the `paths` part of the OpenAPI, for the PATCH operation, you should be able to see the valid `Content-Types`.

e.g.
```
{
...
  "paths": {
    "/apis/policy/v1/namespaces/{namespace}/poddisruptionbudgets": {
      "patch": {
        "consumes": [
          "application/json-patch+json",
          "application/merge-patch+json",
          "application/strategic-merge-patch+json",
          "application/apply-patch+yaml"
        ],
        "description": "partially update the specified PodDisruptionBudget",
        ...
```

**Comment by apelisse** [comment]
But I think what Jordan is arguing also is that we should use the OpenAPI before all (and basically never use the built-in types struct information at that point).
