### ISSUE TITLE
Kubernetes fails to allocate PV pretending storage request overflows int64

### ISSUE THREAD

**Issue by maxlaverse** [kubernetes/kubernetes#100091]
##### Short version
After upgrading our clusters to Kubernetes 1.19, the provisioning of PersistentVolumes started failing with the following Events:
> ProvisioningFailed persistentvolumeclaim/\<namespace-pvc\> Failed to provision volume with StorageClass “\<storage class\>" : quantity 3435973836800m is too great, overflows int64

The value 3435973836800 matches the actual storage request of 3.2Gi. It doesn't seem special in any way, not too big, not too small, and it always worked until 1.19. We look into the issue with @fungusakafungus and we believe the PR [When casting resource.Quantity to int64 it may overflow](https://github.com/kubernetes/kubernetes/pull/90907) introduced a change that broke the PersistentVolume provisioning even when it doesn’t overflow int64.

##### Long version
Amounts of resource in Kubernetes are represented with the `type Quantity struct`. In the PersistentVolume drivers, there are some functions that manipulate storage request `Quantity` in order to allocate a disk with the right size. 

Before the mentioned PR, those quantities were retrieved by calling `(q *Quantity) Value()` which relies on `(q *Quantity) ScaledValue(scale Scale)` to return the value as an int64. This worked probably fine in most of the cases, but it could happen that the represented value would overflow an int64, and in this case the result of `Value()` would be wrong. The function’s description states that it’s the caller’s responsibility to check this:
```go
// To detect overflow, call Value() first and verify the expected magnitude.
func (q *Quantity) ScaledValue(scale Scale) int64 {
```

This is likely what the PR wanted to handle. The change replaced all `Value()` calls with `AsInt64()` which has a different signature. From where it’s used now, you would think that the second return value signals an overflow:

[Example](https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/cloud-provider/volume/helpers/rounding.go#L60-L67):
```go
// RoundUpToMiB rounds up given quantity upto chunks of MiB
func RoundUpToMiB(size resource.Quantity) (int64, error) {
    requestBytes, ok := size.AsInt64()
    if !ok {
        return 0, fmt.Errorf("quantity %s is too great, overflows int64", size.String())
    }
    return roundUpSize(requestBytes, MiB), nil
}
```

This is probably where the error we’re seeing is generated. I believe that the signature of `AsInt64()` was misinterpreted. From my understanding of its description, returning `false` doesn’t mean we’re overflowing `int64`. It only means that internally, the quantity is represented as a decimal amount:
```go
// AsInt64 returns a representation of the current value as an int64 if a fast conversion
// is possible. If false is returned, callers must use the inf.Dec form of this quantity.
func (q *Quantity) AsInt64() (int64, bool) {
```

Internally, depending on their values, quantities are stored/represented in [two different ways](https://github.com/kubernetes/apimachinery/blob/1f1bc58a1c7983ab067dac7b23ff9fdc5081d5ba/pkg/api/resource/quantity.go#L264-L300):
* `int64Amount` for DecimalExponent (e.g. `10e6`) or DecimalSI (e.g. `2M`)
* `int64Amount` for BinarySI that don’t have a decimal part but a unit (simplified) (e.g. `3200Mi`)
* `infDecAmount` for all the rest

With the PR, Kubernetes now fails to provision volumes that have a storage request represented as `infDecAmount`. Many of the storage requests are represented this way and still perfectly valid in our opinion.

#### What you expected to happen:
I would have expected the provisioning to continue to work as those requests seemed valid and were always accepted by our underlying cloud-provider in earlier version of Kubernetes.

##### From the code
```go
package main

import (
    "fmt"

    "k8s.io/apimachinery/pkg/api/resource"
    volumehelpers "k8s.io/cloud-provider/volume/helpers"
)

func computeVolumeOptions(resourceRequest string) {
    // Simplified version of what happens in a "volume driver"
    capacity := resource.MustParse(resourceRequest)
    volSizeMiB, err := volumehelpers.RoundUpToMiBInt(capacity)
    fmt.Printf("Request of '%s' \tgives ScaledValue(0)=%d, RoundValueInMB=%d, err: %v\n", resourceRequest, capacity.Value(), volSizeMiB, err)
}

func main() {
    // This works
    computeVolumeOptions("3200Mi")
    // = 3200*1024*1024*1000 = 3355443200000 millibytes

    // This fails, but it's the same quantity as above
    computeVolumeOptions("3.125Gi")
    // = 3.125*1024*1024*1024*1000 = 3355443200000 millibytes

    // This fails and worked before
    computeVolumeOptions("3.2Gi")
    // = 3.2*1024*1024*1024*1000 = 3435973836800 millibytes

    // A true overflow ?
    computeVolumeOptions("990Pi")
    // = 990*1024*1024*1024*1024*1024*1000 = 1.1146409e+21 > 9.223372e+18

    // This fails but is supposed to work since the volume driver ultimately round up
    // to the megabyte
    computeVolumeOptions("3.2Mi")
    // = 3.2*1024*1024*1000 = 3355443200 millibytes

    // This works
    computeVolumeOptions("3.2M")
    // = 3.2*1024*1024*1000 = 3200000000 millibytes
}

```

##### With a PVC

Create a StatefulSet with a PersistentVolumeClaim that uses vSphere storage:
```yaml
volumeClaimTemplates:
...
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3.2Gi
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.7
- Cloud provider or hardware configuration: vSphere, but I think it impacts other cloud-provider that were changed in the PR:

/sig storage
/kind bug

/cc @gnufied @wongma7

Possibly related to https://github.com/kubernetes/kubernetes/issues/99846

**Comment by wongma7** [comment]
I think the only reason we do not use the quantity library for scaling and why we tried to roll our own rounding code is because when scaling stuff in AsScaledInt64(3) or ScaledValue(3), the library assumes decimal SI (M, 1000), not binary SI units (Mi, 1024): https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apimachinery/pkg/api/resource/math.go#L138

You are right, our self-rolled rounding code doesn't handle values with millibyte or higher precision like 3.2Gi. Our code uses AsInt64 and then performs its own scaling. If AsInt64 returns false, the int64 returned is not in bytes (it must be in millibytes or higher precision), so our rounding code won't work, so it returns that " is too great, overflows int64".

In 1.18, we used Value() to round to bytes but we didn't check it against ScaleValue as the signature suggested. So the PR in question fixed cases where Value() overflowed but inadvertently broke your case.

The correct way to round, which the resource library's rounding does, is to drop the useless precision and round up. https://github.com/kubernetes/kubernetes/blob/cea1d4e20b4a7886d8ff65f34c6d4f95efcb4742/staging/src/k8s.io/apimachinery/pkg/api/resource/amount.go#L97, but as I said it doesn't seem to handle binary SI quantities correctly.

For decimal SI quantities, we should rely on the resource library's AsScaledInt64 and be done with it. (We could also use Value() and ScaledValue as the signature suggests but calling AsScaledInt64 directly seems simpler). Like this:

```
func RoundUpToGB(size resource.Quantity) (int64, error) {
	value, ok := size.AsScaledInt64(resource.Giga)
	if !ok {
		return 0, fmt.Errorf("quantity %v is too great, overflows int64", size)
	}
        return value, nil
}
```

For binary SI quantities, we need to do something fancier involving CanonicalizeBytes I think, I'm not sure yet.

**Comment by wongma7** [comment]
I guess for binary SI we can go back to using Value but actually check the overflow this time.

**Comment by maxlaverse** [comment]
Hi @wongma7,
Thanks for the quick feedback on the problem's description already. Indeed, the *Scaled* functions don't handle BinarySI and that's why I quickly discarded the idea of using them, since when it's about storage, I suppose more people are using this format. I just finished wrapping up a PR that I hope address both the issue we are facing, but also what was meant to be fixed in the PR your reviewed back then. It doesn't make any difference between the 3 formats however.

**Comment by wongma7** [comment]
Yeah I commented within seconds of your PR. I glanced at it , will review more soon, but it makes sense to me to just use VAlue and check ofr overflow for both decimal SI and binary SI rather than using Scaled() for one and not the other :+1:

**Comment by gnufied** [comment]
> This is probably where the error we’re seeing is generated. I believe that the signature of AsInt64() was misinterpreted. From my understanding of its description, returning false doesn’t mean we’re overflowing int64. It only means that internally, the quantity is represented as a decimal amount:

I think it means both. i.e - when incoming value is decimal or if value is so big that `Quantity` type can't store it as `int64amount` it switches to decimal. So while my PR fixed later case, it broke the former. :/
