### ISSUE TITLE
There are no 6-digit issues or PRs in kubernetes/kubernetes

### ISSUE THREAD

**Issue by craigbox** [kubernetes/kubernetes#100000]
Up until now, all issues and PRs have had 5 digits or fewer.  We should validate nothing fails when the issue or PR number is 6 digits long.

**Comment by nikhita** [comment]
:100: :100:

**Comment by matthyx** [comment]
Nice one!

**Comment by aojea** [comment]
:1st_place_medal:

**Comment by nikhita** [comment]
Going to close this one :)

**Comment by liggitt** [comment]
<img src="https://user-images.githubusercontent.com/980082/110514751-9e783700-80d5-11eb-8bc1-bb365c28b212.jpeg" height="500" alt="o_O">

**Comment by aojea** [comment]
hahahahha
please add it to the bot 
/liggit

**Comment by csantanapr** [comment]
LOL !

**Comment by cheftako** [comment]
Your issue is your fix.

**Comment by atoato88** [comment]
Awesome!! :100: 
/woof
