### ISSUE TITLE
Job suspend and completionMode fields should be left empty when features are disabled

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#100187]
When feature gates are disabled, fields should not be rendered when storing or when returning objects from API.

For this reason, feature gate should control defaulting and the fields should be pointers.

This was missed during api-review for `.spec.suspend` and `.spec.completionMode`

/sig apps

**Comment by liggitt** [comment]
this needs to be resolved before 1.21 to ensure alpha features are completely inert in the release
