### ISSUE TITLE
[Flaky test] [sig-network] Networking Granular Checks: Services should function for client IP based session affinity: http [LinuxOnly]

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#100135]
#### Which jobs are flaking:
ci-kubernetes-e2e-gce-scale-correctness

#### Which test(s) are flaking:
[sig-network] Networking Granular Checks: Services should function for client IP based session affinity: http [LinuxOnly]

#### Testgrid link:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:416
Mar  9 12:24:27.462: Unexpected no endpoints return
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

#### Anything else we need to know:
Prow job URL with the failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1369256942261768192.

/sig scalability
/sig network

**Comment by aojea** [comment]
/close

only 1 occurrence in 1 job in 2 months
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness&include-filter-by-regex=based%20session%20affinity&width=5

we should have min 2 occurrences to declare a flaky
