### ISSUE TITLE
Pods with “hard” podAntiAffinity were scheduled to the same node

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#100140]
#### What happened:
I created a deployment with three replicas. Configured “hard” podAntiAffinity,as follows:

>         podAntiAffinity:
>           requiredDuringSchedulingIgnoredDuringExecution:
>           - labelSelector:
>               matchExpressions:
>               - key: anti-myself
>                 operator: In
>                 values:
>                 - openpalette-op-asm-operator
>             topologyKey: kubernetes.io/hostname

Then，use kubectl to get pods. It was found that the two pods op-asm-operator-75d9577679-9fvdf and op-asm-operator-75d9577679-vl9qm were scheduled to the same node.
![image](https://user-images.githubusercontent.com/25921749/110809652-10ac6f80-82c0-11eb-83ed-2bf5c394a363.png)

At that time, etcd's I/O was high. From the kube-scheduler log, I could see that the scheduling of the Pod failed due to the failure to bind the Pod. The reason for the binding failure was "etcdserver: request timed out".
```
E0306 15:19:51.677589       1 framework.go:747] plugin "DefaultBinder" failed to bind pod "admin/op-asm-operator-75d9577679-vl9qm": Operation cannot be fulfilled on pods/binding "op-asm-operator-75d9577679-vl9qm": etcdserver: request timed out
E0306 15:19:51.677752       1 factory.go:465] "Error scheduling pod; retrying" err="Binding rejected: plugin \"DefaultBinder\" failed to bind pod \"admin/op-asm-operator-75d9577679-vl9qm\": Operation cannot be fulfilled on pods/binding \"op-asm-operator-75d9577679-vl9qm\": etcdserver: request timed out" pod="admin/op-asm-operator-75d9577679-vl9qm"
I0306 15:19:51.678015       1 event_broadcaster.go:374] Event(v1.ObjectReference{Kind:"Pod", Namespace:"admin", Name:"op-asm-operator-75d9577679-vl9qm", UID:"1cdeea68-2297-4d22-810d-e50c18cdec40", APIVersion:"v1", ResourceVersion:"827", FieldPath:""}): type: 'Warning' reason: 'FailedScheduling' Binding rejected: plugin "DefaultBinder" failed to bind pod "admin/op-asm-operator-75d9577679-vl9qm": Operation cannot be fulfilled on pods/binding "op-asm-operator-75d9577679-vl9qm": etcdserver: request timed out

I0306 15:19:58.417021       1 event_broadcaster.go:374] Event(v1.ObjectReference{Kind:"Pod", Namespace:"admin", Name:"op-asm-operator-75d9577679-9fvdf", UID:"3fca4250-632e-4650-b7a3-f828505fc1c8", APIVersion:"v1", ResourceVersion:"851", FieldPath:""}): type: 'Normal' reason: 'Scheduled' Successfully assigned admin/op-asm-operator-75d9577679-9fvdf to 1111--88
E0306 15:20:09.424242       1 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"op-asm-operator-75d9577679-9fvdf.1669afc4287fd0a4", GenerateName:"", Namespace:"admin", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"admin", Name:"op-asm-operator-75d9577679-9fvdf", UID:"3fca4250-632e-4650-b7a3-f828505fc1c8", APIVersion:"v1", ResourceVersion:"851", FieldPath:""}, Reason:"Scheduled", Message:"Successfully assigned admin/op-asm-operator-75d9577679-9fvdf to 1111--88", Source:v1.EventSource{Component:"default-scheduler", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc008e92798da24a4, ext:177729781574, loc:(*time.Location)(0x2c36080)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc008e92798da24a4, ext:177729781574, loc:(*time.Location)(0x2c36080)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'etcdserver: request timed out' (will not retry!)
```

It seems that the Pod binding has actually been successfully saved to etcd, although etcdserver returns "Request timed out".

#### What you expected to happen:
Pods with “hard” podAntiAffinity should be scheduled to the different nodes.

#### How to reproduce it (as minimally and precisely as possible):
This exception may occur when etcd's I/O is high

#### Environment:
- Kubernetes version (use `kubectl version`):  v1.19.4
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by houjun41544** [comment]
I did a preliminary analysis.
The first pod op-asm-operator-75d9577679-vl9qm was scheduled to the node "1111-88" and run normally. But due to etcdserver timeout, kube-scheduler received a binding failure, and then called ForgetPod() to delete the pod from the schedulercache. The Kube-Scheduler code is as follows.
[https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/scheduler/scheduler.go](url)
```
		err := sched.bind(bindingCycleCtx, prof, assumedPod, scheduleResult.SuggestedHost, state)
		if err != nil {
			metrics.PodScheduleError(prof.Name, metrics.SinceInSeconds(start))
			// trigger un-reserve plugins to clean up state associated with the reserved Pod
			prof.RunReservePluginsUnreserve(bindingCycleCtx, state, assumedPod, scheduleResult.SuggestedHost)
			if err := sched.SchedulerCache.ForgetPod(assumedPod); err != nil {
				klog.Errorf("scheduler cache ForgetPod failed: %v", err)
			}
```
Also due to the exception of etcd, kube-scheduler did not receive the add event of the scheduled Pod, so the Pod could not be added to the schedulecache again.
When the second pod op-asm-operator-75d9577679-9fvdf was to be scheduled, no pods on the node "1111-88" in the schedulercache met the anti-affinity with this pod, so it could be scheduled to node "1111-88".

**Comment by tanjing2020** [comment]
Although the timeout is returned, has etcd successfully written the data? Can you confirm this?

**Comment by houjun41544** [comment]
@tanjing2020  The status of the Pod is running. Kubelet will run the pod only when the pod is bound to the node.

**Comment by houjun41544** [comment]
Has anyone else encountered the same problem? The scheduler binding pod receives “etcdserver: request timed out” (as follows), but the binding is actually successful and pod is running. 
`
E0306 15:19:51.677589       1 framework.go:747] plugin "DefaultBinder" failed to bind pod "admin/op-asm-operator-75d9577679-vl9qm": Operation cannot be fulfilled on pods/binding "op-asm-operator-75d9577679-vl9qm": etcdserver: request timed out
`

**Comment by kerthcet** [comment]
have you solved you problems yet? @houjun41544
