### ISSUE TITLE
Kubedm supports k8s component to customize image name or path to pull images.

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#100174]
#### What would you like to be added:
Kubedm supports k8s component to customize image name or path to pull images.

#### Why is this needed:

Sometimes users want to compile k8s components and build customized k8s component images, push them to the docker repository, and then install k8s with kubedm. At this time, they need to specify the name and tag of the customized k8s component, so Kubedm should supports k8s component to customize image name or path to pull images.
a simple implementation: #100160

**Comment by wangyysde** [comment]
@chymy As if you can use config or image-repository flag of kubeadm.

**Comment by chymy** [comment]
> @chymy As if you can use config or image-repository flag of kubeadm.

Yes,  I know the flag. I mean that the customized image's name or tag  , not repository. Thanks.

**Comment by pacoxu** [comment]
/cc kofClubs 

@kofClubs would you help with this

**Comment by chymy** [comment]
> We have done similar things as we cannot access gcr.io directly from China. Hence, we have to sync some latest images to our registry. `daocloud.io` or `registry.cn-hangzhou.aliyuncs.com` or local registry.

Thanks @pacoxu . Kubedm can set up image repository. However， if we redevelop the k/k and package it as our own mirror, `tag` might be different.

**Comment by wangyysde** [comment]
@chymy  As if you can specify the tag by --kubernetes-version.But the format of the tag  must be X.X.X. The following if the output of kubeadm config images list --kubernetes-version 5.22.1 --image-repository harbor.bzhy.com/k8s . It is for you reference.
`harbor.bzhy.com/k8s/kube-apiserver:v5.22.1
harbor.bzhy.com/k8s/kube-controller-manager:v5.22.1
harbor.bzhy.com/k8s/kube-scheduler:v5.22.1
harbor.bzhy.com/k8s/kube-proxy:v5.22.1
harbor.bzhy.com/k8s/pause:3.2
harbor.bzhy.com/k8s/etcd:3.4.13-0
harbor.bzhy.com/k8s/coredns:1.7.0`

**Comment by neolit123** [comment]
/remove-help
/remove good-first-issue

this labels should not be present on this issue.

**Comment by neolit123** [comment]
^ @wangyysde 's advice above is good.

> Kubedm supports k8s component to customize image name or path to pull images.

kubeadm already supports image repository.
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2
search for `imageRepository`

this allows you to create / download images and place them in an accessible registry.

we have no plans to allow customizing image name / tags for api-server, KCM, kube-proxy and kube-scheduler, but you can do that for etcd.

**Comment by neolit123** [comment]
we don't keep support tickets open here, so i'm going to close this.
but you can continue the conversation...

/kind support
/close

see https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by chymy** [comment]
Thanks @neolit123 @wangyysde , our components may be different tags. ^_^

**Comment by neolit123** [comment]
currently we support custom images for dns and etcd. but if `kubeadm upgrade` finds that it will skip upgrade.
you can create tag aliases using `docker tag <your custom image tag> <k8s-semver>`
this means the `<k8s-semver>` tag will point to your custom image.

if you wish to discuss this feature request for the kubeadm API more create an issue in https://github.com/kubernetes/kubeadm

note, it cannot be added in v1beta1/2 and must target v1beta3.

**Comment by chymy** [comment]
> for the control-plane, you can create tag aliases using `docker tag <your custom image tag> <k8s-semver>`
> this means the `<k8s-semver>` tag will point to your custom image.

Thanks @neolit123 , That's a solution.
