### ISSUE TITLE
[Flaky Test] [sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate [Feature:DaemonSetUpdateSurge]

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100138]
#### Which jobs are flaking:
ci-kubernetes-e2e-gci-gce-alpha-features

#### Which test(s) are flaking:
[sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate [Feature:DaemonSetUpdateSurge]

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:493
Mar 11 10:28:25.158: Expected
    <string>: 68f54748b9
to equal
    <string>: 58679bf97b
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:1086
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

7 flakes in the last 3 days:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369955771013402624
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369930103982657536
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369801249796395008
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369550582074839040
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369500246761017344
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1369158284967153664

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=surge%20pods%20onto%20nodes%20when%20spec%20was%20updated#fe6fca1e94ca4e88000b

/sig apps
/priority important-soon

**Comment by dims** [comment]
cc @soltysh

**Comment by thejoycekung** [comment]
More flakes since this weekend:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1371459664851505152
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1371411846942167040
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1371400020078628864
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1371328297023049728
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1370920369401106432
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1370823231673470976
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1370691620554412032
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1370559762902552576

**Comment by soltysh** [comment]
> cc @soltysh

Apologies, I was out last week looking at it now...

**Comment by soltysh** [comment]
I've added a bit more debug information, it's hard to say which hashes are being compared and why it is failing, see #100310

**Comment by soltysh** [comment]
/assign
There were no failures since this fix merged, I'll continue looking into this...

**Comment by thejoycekung** [comment]
@soltysh I think these ones have the new debug message you added:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1372169795985739776
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1372037424590360576
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1372013764487942144

**Comment by soltysh** [comment]
Looks like #100345 should be able to help us with this.

**Comment by thejoycekung** [comment]
More recent flakes:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373948999001706496
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373888095178461184
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373828703854792704
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373780131771846656
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373721495817162752
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1373637192525549568

**Comment by soltysh** [comment]
Hmm... looks like we might have missed some cases, I'll look into it more...

**Comment by soltysh** [comment]
@thejoycekung from what I see #100345 merged on March 23rd, and looking at https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features&width=5 last failure is happening on March 22nd. The failures from above are from before the fix landed, b/c they are pointing a pods which are deleted (`pod.DeletionTimestamp != nil`) and that exact fix was added in that PR. I'll continue monitoring, but I'm pretty confident this is solved.

**Comment by thejoycekung** [comment]
Triage is showing that nothing has flaked since the 23rd, so I'm pretty confident closing this now. https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=surge%20pods%20onto%20nodes%20when%20spec%20was%20updated

Thanks so much for your help @soltysh !

/close

**Comment by mkorbi** [comment]
@soltysh looks like there was a small hiccup

- https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-alpha-features
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1380547485486813184
