### ISSUE TITLE
[Flaky test] [sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a ClusterIP service

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#100134]
#### Which jobs are flaking:
ci-kubernetes-e2e-gce-scale-correctness

#### Which test(s) are flaking:
[sig-network] Conntrack should be able to preserve UDP traffic when server pod cycles for a ClusterIP service

#### Testgrid link:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/conntrack.go:203
Mar  9 12:23:30.486: Failed to connect to backend 1
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

#### Anything else we need to know:
Prow job URL with the failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1369256942261768192.

/sig scalability
/sig network

**Comment by aojea** [comment]
The test only failed once, is hard to know if is flake or a glitch, there is another networking testing failing in the same minute.

However, the job is not very healthy https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness , @wojtek-t is this something we should look, it failed a lot last week and seems it recovered later.

**Comment by thejoycekung** [comment]
https://github.com/kubernetes/kubernetes/issues/91236 was this same test if I recall correctly? Just linking these two issues together

**Comment by aojea** [comment]
> correctly

that was with NodePort, that was the one that was very flaky, this specific one is with ClusterIP and it was always acceptable, this happens only once, but the job show more networking failures in others runs recently.

There is no strong evidence now to declare this particular test flaky with only one failure in a non "stable" job

**Comment by tosi3k** [comment]
> However, the job is not very healthy https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness , @wojtek-t is this something we should look, it failed a lot last week and seems it recovered later.

Test job was very red because of https://github.com/kubernetes/kubernetes/issues/99599 and https://github.com/kubernetes/kubernetes/issues/99449 both of which are already fixed.

**Comment by aojea** [comment]
Folks I'm closing this, only 1 failure since jan18, more than 60 runs
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness&width=90&include-filter-by-regex=Conntrack.*ClusterIP

/close
