### ISSUE TITLE
Show storage-backend default value in kube-apiserver

### ISSUE THREAD

**Issue by yizhang-zen** [kubernetes/kubernetes#100153]
#### What happened:
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
```
--storage-backend string
--
  | The storage backend for persistence. Options: 'etcd3' (default).

```
Although it says in the doc that `etcd3` is the default value of  storage-backend flag in apiserver. But the log showed empty.

```
I0311 20:39:16.030663       1 flags.go:59] FLAG: --stderrthreshold="2"
I0311 20:39:16.030671       1 flags.go:59] FLAG: --storage-backend=""
I0311 20:39:16.030675       1 flags.go:59] FLAG: --storage-media-type="application/vnd.kubernetes.protobuf"
```

#### What you expected to happen:
It would be good to have default value showed in the flag.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5

**Comment by Jeffwan** [comment]
https://github.com/kubernetes/kubernetes/blob/019c89218119ef37bf755e3717c431f4cb9469a4/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go#L51

"" means "etcd3".  However, I think it should be printed here. empty string is not that straightforward. I can help fix it.

**Comment by fedebongio** [comment]
/assign @YoyinZyc 
@Jeffwan are you planning to work on this one to fix it?
/triage accepted

**Comment by Jeffwan** [comment]
@fedebongio Yes. I will file a PR to address this
