### ISSUE TITLE
[Flaky test] [sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#100132]
#### Which jobs are flaking:
ci-kubernetes-e2e-gce-scale-correctness

#### Which test(s) are flaking:
[sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols

#### Testgrid link:
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1211
Mar 10 12:54:33.113: Unexpected error:
    <*errors.errorString | 0xc024168020>: {
        s: "service is not reachable within 2m0s timeout on endpoint 10.40.11.169:31530 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 10.40.11.169:31530 over TCP protocol
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1245
```

#### Anything else we need to know:
Prow job URL with the failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1369619536927526912.

/sig scalability
/sig network

**Comment by aojea** [comment]
@swetharepakula weren't you working in this test in another issue? or am I mixing things?

**Comment by swetharepakula** [comment]
The one I was looking into is https://github.com/kubernetes/kubernetes/issues/93932. I don't think they are having the same problem. That test was failing because time it took for loadbalancer recreations for larger clusters.

**Comment by swetharepakula** [comment]
Looking at the test logs:

The service reachability fails at `Mar 10 12:54:33.113` :
```
error:
exit status 1
Retrying...
Mar 10 12:54:33.113: FAIL: Unexpected error:
    <*errors.errorString | 0xc024168020>: {
        s: "service is not reachable within 2m0s timeout on endpoint 10.40.11.169:31530 over TCP protocol",
    }
    service is not reachable within 2m0s timeout on endpoint 10.40.11.169:31530 over TCP protocol
occurred
```
but the pod creations, according the events, happened after the timeout (`Mar 10 12:54:33.287`)
```
Mar 10 12:54:33.287: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for execpodx9cc8: { } Scheduled: Successfully assigned services-1571/execpodx9cc8 to gce-scale-cluster-minion-heapster
Mar 10 12:54:33.287: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for nodeport-update-service-4drn2: { } Scheduled: Successfully assigned services-1571/nodeport-update-service-4drn2 to gce-scale-cluster-minion-group-1-3jtw
Mar 10 12:54:33.287: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for nodeport-update-service-765c7: { } Scheduled: Successfully assigned services-1571/nodeport-update-service-765c7 to gce-scale-cluster-minion-group-3-vsf0
Mar 10 12:54:33.287: INFO: At 2021-03-10 12:52:13 +0000 UTC - event for nodeport-update-service: {replication-controller } SuccessfulCreate: Created pod: nodeport-update-service-4drn2
Mar 10 12:54:33.287: INFO: At 2021-03-10 12:52:13 +0000 UTC - event for nodeport-update-service: {replication-controller } SuccessfulCreate: Created pod: nodeport-update-service-765c7
```

I am not sure how to investigate this further.

**Comment by aojea** [comment]
/close
Thanks @swetharepakula for investigating it, it also only failed once in the last 2 months
https://testgrid.k8s.io/sig-scalability-gce#gce-master-scale-correctness&include-filter-by-regex=NodePort%20listening&width=5
We are going to close until we have more failures, there was an issue fixed recently causing pods to time out, I can't find the reference right  now
