### ISSUE TITLE
StaticPod: Missing default serviceaccount mount on Ubuntu 20.0.4

### ISSUE THREAD

**Issue by camrossi** [kubernetes/kubernetes#100105]
I am deploying a new cluster based of K8S 1.20.4 and Ubuntu 20.0.4 
None of my static pods are getting the default service account mount.

This is for coreDNS but a static pods will not have the mount. 
```
{
                "Type": "bind",
                "Source": "/var/lib/kubelet/pods/3d735801-a925-46f5-81d6-30f5ed220341/volumes/kubernetes.io~secret/coredns-token-22ffs",
                "Destination": "/var/run/secrets/kubernetes.io/serviceaccount",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
},
```
I also do not see the mount in "/var/lib/kubelet/pods/ID" folder 

I have another cluster on Ubuntu 18 and K8S 1.20.2 and there the static pods are getting the mount. 
I am not sure what could be the reason, I tried also completely removing appArmour just in case but that was not the reason. 
Debug level logs on Kubelet shed no light either. 
I also tried K8S 1.20.2 and have the same behaviour.

**Comment by liggitt** [comment]
static pods are not allowed to make use of any API service resources, including mounting configmaps, secrets, or service account tokens. They must be able to be started by the kubelet without contact with the API server.

/close

**Comment by MikeSpreitzer** [comment]
This fact is missing from the documentation.  For example, as noted at https://github.com/kubernetes/website/issues/28611#issuecomment-876537379
