### ISSUE TITLE
How to use Scheduling Framework in v1.15.3？

### ISSUE THREAD

**Issue by zhangrongguo** [kubernetes/kubernetes#100170]
Because the function `NewSchedulerCommand ` in the path `cmd/kube-scheduler/app/server.go` has no input argument, I can't pass the customized scheduling plugin to it.

**Comment by neolit123** [comment]
try asking on the support channels or #sig-scheduling on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/sig scheduling
/close
