### ISSUE TITLE
Nodes are frequently NotReady

### ISSUE THREAD

**Issue by clh-cod** [kubernetes/kubernetes#100166]
#### What happened:
Nodes are frequently NotReady

#### Environment:
- Kubernetes version (use `kubectl version`): v1.18.1
- OS (e.g: `cat /etc/os-release`): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`):Linux njscsjfwzx2 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Network plugin and version (if this is a network-related bug): calico V3.17.0
- docker: v20.10.0

I created a Kubernetes using Kubeadm. When the node is added to Kubernetes, occurs frequently NotReady.

##Kubelet logs:
`3 Mar 12 10:49:32 njscsjfwzx2 kubelet[23221]: E0312 10:49:32.719846   23221 controller.go:178] failed to update node lease, error: Put https://10.43.0.49:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/njscsjfwzx2?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

3 Mar 12 10:49:32 njscsjfwzx2 kubelet[23221]: E0312 10:49:32.778252   23221 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "njscsjfwzx2": Get https://10.43.0.49:6443/api/v1/nodes/njscsjfwzx2?resourceVersion=0&timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
`

##Describe this node
`Name:               njscsjfwzx2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    iothub=emqx-broker
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=njscsjfwzx2
                    kubernetes.io/os=linux
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.43.0.51/8
                    projectcalico.org/IPv4IPIPTunnelAddr: 10.244.109.193
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 12 Mar 2021 09:56:36 +0800
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  njscsjfwzx2
  AcquireTime:     <unset>
  RenewTime:       Fri, 12 Mar 2021 10:16:44 +0800
Conditions:
  Type                 Status    LastHeartbeatTime                 LastTransitionTime                Reason              Message
  ----                 ------    -----------------                 ------------------                ------              -------
  NetworkUnavailable   False     Fri, 12 Mar 2021 09:56:40 +0800   Fri, 12 Mar 2021 09:56:40 +0800   CalicoIsUp          Calico is running on this node
  MemoryPressure       Unknown   Fri, 12 Mar 2021 10:16:49 +0800   Fri, 12 Mar 2021 10:17:34 +0800   NodeStatusUnknown   Kubelet stopped posting node status.
  DiskPressure         Unknown   Fri, 12 Mar 2021 10:16:49 +0800   Fri, 12 Mar 2021 10:17:34 +0800   NodeStatusUnknown   Kubelet stopped posting node status.
  PIDPressure          Unknown   Fri, 12 Mar 2021 10:16:49 +0800   Fri, 12 Mar 2021 10:17:34 +0800   NodeStatusUnknown   Kubelet stopped posting node status.
  Ready                Unknown   Fri, 12 Mar 2021 10:16:49 +0800   Fri, 12 Mar 2021 10:17:34 +0800   NodeStatusUnknown   Kubelet stopped posting node status.
Addresses:
  InternalIP:  10.43.0.51
  Hostname:    njscsjfwzx2
Capacity:
  cpu:                8
  ephemeral-storage:  200176132Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16265916Ki
  pods:               110
Allocatable:
  cpu:                8
  ephemeral-storage:  184482322946
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             16163516Ki
  pods:               110
System Info:
  Machine ID:                   81cb8bbdf11c46519f29a21725501298
  System UUID:                  DD8B1A42-3159-3635-E53E-7533A7EEF976
  Boot ID:                      445cfa22-75be-4d6d-ad5e-487670e62c18
  Kernel Version:               3.10.0-1127.19.1.el7.x86_64
  OS Image:                     CentOS Linux 7 (Core)
  Operating System:             linux
  Architecture:                 amd64
  Container Runtime Version:    docker://20.10.0
  Kubelet Version:              v1.18.1
  Kube-Proxy Version:           v1.18.1
PodCIDR:                        10.244.2.0/24
PodCIDRs:                       10.244.2.0/24
Non-terminated Pods:            (5 in total)
  Namespace                     Name                   CPU Requests  CPU Limits   Memory Requests  Memory Limits  AGE
  ---------                     ----                   ------------  ----------   ---------------  -------------  ---
  kube-system                   calico-node-fkvmg      250m (3%)     0 (0%)       0 (0%)           0 (0%)         21m
  kube-system                   kube-proxy-z979f       0 (0%)        0 (0%)       0 (0%)           0 (0%)         21m
  kubesphere-logging-system     fluent-bit-tdxn7       0 (0%)        0 (0%)       0 (0%)           0 (0%)         21m
  kubesphere-monitoring-system  node-exporter-pfj4r    112m (1%)     1300m (16%)  200Mi (1%)       500Mi (3%)     21m
  service-center                iothub-2lk4od-0        0 (0%)        0 (0%)       0 (0%)           0 (0%)         11m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                362m (4%)   1300m (16%)
  memory             200Mi (1%)  500Mi (3%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type     Reason                   Age                 From                     Message
  ----     ------                   ----                ----                     -------
  Normal   Starting                 21m                 kubelet, njscsjfwzx2     Starting kubelet.
  Warning  ImageGCFailed            21m                 kubelet, njscsjfwzx2     failed to get imageFs info: unable to find data in memory cache
  Normal   NodeAllocatableEnforced  21m                 kubelet, njscsjfwzx2     Updated Node Allocatable limit across pods
  Normal   Starting                 21m                 kube-proxy, njscsjfwzx2  Starting kube-proxy.
  Normal   NodeHasNoDiskPressure    15m (x6 over 21m)   kubelet, njscsjfwzx2     Node njscsjfwzx2 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     15m (x6 over 21m)   kubelet, njscsjfwzx2     Node njscsjfwzx2 status is now: NodeHasSufficientPID
  Normal   NodeReady                15m (x4 over 20m)   kubelet, njscsjfwzx2     Node njscsjfwzx2 status is now: NodeReady
  Normal   NodeHasSufficientMemory  62s (x14 over 21m)  kubelet, njscsjfwzx2     Node njscsjfwzx2 status is now: NodeHasSufficientMemory
`

**Comment by neolit123** [comment]
are you sure you have enough resources on these nodes?

/sig node

**Comment by clh-cod** [comment]
@neolit123 Of course, this node has enough memoury and disk. 
![image](https://user-images.githubusercontent.com/69289383/111095575-b427a980-8578-11eb-9a65-0997949fbbfc.png)

**Comment by logici** [comment]
I get the same problem as well. In my case, I have three nodes in my cluster. two nodes in the cluster are NotReady frequently except the leader. 
kubernetes version: 1.19
os: ubuntu20.04
Network plugin and version: 3.13.2
runtime: containerd
I created a Kubernetes using with microk8s.

There are prometheus alerts.
![alert](https://user-images.githubusercontent.com/34180157/113821726-1017d380-97af-11eb-99ba-a35429f58628.png)

`journalctl -u kubelet.service -f `:
```
Apr 07 06:51:55 xxxxx microk8s.daemon-kubelet[2128037]: W0407 06:51:55.568780 container_manager_linux.go:942] CPUAccounting not enabled for pid:
Apr 07 06:51:55 xxxxx microk8s.daemon-kubelet[2128037]: W0407 06:51:55.568814 container_manager_linux.go:945] MemoryAccounting not enabled for pid:
Apr 07 06:51:56 xxxxx microk8s.daemon-kubelet[2128037]: E0407 06:51:56.211398 manager.go:1123] Failed to create existing container: /kubepods/burstable/pod6d3ca221-d0a1-46cb-92af-53b0623c7a81/43dae5a10db8060cc10648a8b57b6b2e177d470ff7ca8e637ddf3c66bf490c1c: task 43dae5a10db8060cc10648a8b57b6b2e177d470ff7ca8e637ddf3c66bf490c1c not found: not found
Apr 07 06:51:57 xxxxx microk8s.daemon-kubelet[2128037]: E0407 06:51:57.716385 manager.go:1123] Failed to create existing container: /kubepods/burstable/pod6d3ca221-d0a1-46cb-92af-53b0623c7a81/078fac279099ee28e9342fd3abdd9f9ab49d5e0b5a836c19f2b9a0a224736a1a: task 078fac279099ee28e9342fd3abdd9f9ab49d5e0b5a836c19f2b9a0a224736a1a not found: not found
Apr 07 06:51:59 xxxxx microk8s.daemon-kubelet[2128037]: E0407 06:51:59.221443 manager.go:1123] Failed to create existing container: /kubepods/burstable/podd1e963f0-5f4c-4b45-90e5-827c72e80a3e/5037f6b9d6febb382d446e4c7a62ce62181277c244ff1a534550ec64a2e168de: task 5037f6b9d6febb382d446e4c7a62ce62181277c244ff1a534550ec64a2e168de not found: not found
Apr 07 06:52:00 xxxxx microk8s.daemon-kubelet[2128037]: E0407 06:52:00.727154 manager.go:1123] Failed to create existing container: /kubepods/burstable/podd1e963f0-5f4c-4b45-90e5-827c72e80a3e/992d959c0dfd2d9d300da5a77ac25ecdb75fbd792c4fadbba8ee4f624ef24ef7: task 992d959c0dfd2d9d300da5a77ac25ecdb75fbd792c4fadbba8ee4f624ef24ef7 not found: not found
Apr 07 06:52:02 xxxxx microk8s.daemon-kubelet[2128037]: E0407 06:52:02.437211 controller.go:178] failed to update node lease, error: Put "https://127.0.0.1:xxxxx/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/ausrine?timeout=10s": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```
`/kubepods/burstable/podd1e963f0-5f4c-4b45-90e5-827c72e80a3e/5037f6b9d6febb382d446e4c7a62ce62181277c244ff1a534550ec64a2e168de` is the id of the calico-node pod.

**Comment by clh-cod** [comment]
This problem I have in a production environment.
Finally, the reason is that another machine has the same IP.

**Comment by logici** [comment]
thanks, @clh-cod. I have checked the ip of nodes just now. But it does not fit my case.

**Comment by kaykhan** [comment]
> thanks, @clh-cod. I have checked the ip of nodes just now. But it does not fit my case.

Did you find your solution?
