### ISSUE TITLE
NodeStage is not called after NodeUnstage error

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#100182]
#### How to reproduce it (as minimally and precisely as possible):

1. Run a pod that uses a CSI volume that supports NodeStage (such as Ceph RBD)
2. Delete the pod
3. The CSI driver times out when processing NodeUnstage call. It is un-staging the volume in the background and eventually succeeds. (Ceph RBD talks to the storage backed in NodeUnstage and there was some network disruption)
4. Create new pod that uses the same volume on the same node

#### What happened:
kubelet calls only NodePublish. Since the previous NodeUnstage did not succeed, it wrongly assumes that the volume is still NodeStaged.

#### What you expected to happen:
kubelet calls NodeStage + NodePublish, because it can't be sure if the volume is staged or not.
After NodeUnstage error, we should mark volumes as uncertain to make sure NodeStage is called after NodeUnstage returns error.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21

**Comment by adabuleanu** [comment]
Is there a workaround in kubernetes 1.20 for this issue? I see that the fix is addressed for kubernetes 1.21.

Thanks,
Adrian

**Comment by adabuleanu** [comment]
I managed to reproduce this very often why upgrading from k8s 1.19.6 to 1.20.4 . I posted my findings on the original ticket https://bugzilla.redhat.com/show_bug.cgi?id=1936408 . I can give more details if needed.

**Comment by msau42** [comment]
/assign @jsafrane
@kubernetes/sig-storage-bugs

**Comment by vpnachev** [comment]
Hello, 

I see this issue is fixed in 1.22 but are there any plans to fix it also in 1.20 and 1.21?
