### ISSUE TITLE
Kubernetes blocking UDP requests

### ISSUE THREAD

**Issue by canuysal** [kubernetes/kubernetes#100212]
### issue:
RTSP protocol uses random udp ports to push data every frame.

If I use single port TCP connection it works, but TCP has its own delay. Whenever I try to stream data using UDP in a pod, k8s does not allow udp access.

RTSP-UDP initially connects to 554 TCP port, and gets assigned to an UDP port between ~18000-25000. This port changes every frame.  However I cannot get any data using udp.

### reproduce: (edited for clarity)
The camera should be in the host network, ie 10.5.5.2
Pod is in the CNI, ie 10.244.10.16, The node running the pod has host IP ie 10.5.5.12

If you dont have access to an rtsp stream, (if you have cctv you probably have one)
you can create one using this link -> rtsp with ffmpeg
make sure you change the fields tcp to udp.

Rtsp stream you created must be on another computer on host network. Confirm you can get the stream with ffplay command on the node you will run the pod. For example, run
```
ffplay rtsp://10.5.5.2:8554/stream1
```
from the node 10.5.5.12

After you confirm it, try to start a basic ubuntu:18.04 or 20.04 pod with sleep, log in the pod shell, install ffmpeg and try the ffplay command again. You can background it and probe with tcddump or any other tool you like.

### notes:
Stream will hang unless you use hostNetwork, which is undesirable in my case.

You can use tcpdump to see tcp communications with rtsp server is successful but udp packet size is zero.

**Comment by aojea** [comment]
@canuysal kubernetes does not filter anything by default, however, from your description is not easy to understand your scenario, is this pod to pod communication, pod to service?
You need to describe better the scenario, and if possible describe how to reproduce it

**Comment by canuysal** [comment]
hi @aojea , I will try to make it more clear.
The camera is in the host network, ie 10.5.5.2
Pod is in the CNI, ie 10.244.10.16

Im trying to connect rtsp stream within the pod. To reproduce:

If you dont have access to an rtsp stream, (if you have cctv you probably have one)
you can create one using this link ->  [https://superuser.com/questions/1420328/streaming-rtsp-with-ffmpeg](rtsp with ffmpeg)

**Comment by aojea** [comment]
I see, I think that this is a NAT problem not a Kubernetes problem, usually the PodIP is being masquerade to the NodeIP, so the traffic from the camera needs to be DNATed, but since it has different ports it never matches the conntrack entry and is not DNATed to send back to the Pod.

If my assumption is correct, you can verify it checking the conntrack table of your node or with tcpdump, and see if the destination IP of the packets coming from the camera are the NodeIP or the PodIP.

Some ideas to solve this particular problem:
1. No masquerade traffic from the pods to the camera IP, is something that the ip-masq-agent does https://kubernetes.io/docs/tasks/administer-cluster/ip-masq-agent/ , but then you have to install a route to the pod IP in your camera
2. Use a RSTP NAT kernel helper like https://packages.debian.org/stretch/nat-rtsp-dkms, so it handles the returning traffic

**Comment by uablrek** [comment]
So the udp communication is initiated from within a POD? If so, as @aojea pointed out, K8s is not involved. It is a CNI-plugin thing, so;

What CNI-plugin are you using? How is it configured? Some overlay such as vxlan?

Please use the issue template next time. It has important fields to be filled, e.g CNI-plugin.

I can't think of anything in the path that can mangle UDP packets to have lenght=0 so I think the sender sends those packets. A possible reason would be MTU problems. When you run on the node or in a POD with hostNetwork:true you almost certainly have the default MTU=1500. But within a POD, depending on CNI-plugin, you may have a smalles MTU, say 1460 (cause of the network overlay). If the sender uses DF (don't fragment) there may be a problem. Nothing obvious I can think of though.

A way to check the MTU-problem theory may be to disable network overlays in the CNI-plugin. The MTU inside the pod should become 1500 for eth0.

**Comment by uablrek** [comment]
If you are using Calico the ports are scrambeled by default by `--random-fully` for outgoing NAT. I know this causes problems for SCTP and perhaps also for rtsp (which I am not familiar with)? The `--random-fully` can be turned off in Calico, I don't know if other CNI-plugins uses `--random-fully`.

**Comment by canuysal** [comment]
Hey, I've been trying the solutions you suggested for the last two days, and It became clear it's a NAT problem. 
Today I tried to forward the udp port at the node with netcat, and stream was successful. Is there any way that I can forward all udp packages coming from a specific source to the pod in kubernetes?

I know It's not an issue and may be out of context, but can you help me out? I can't find any solutions to this.

@aojea, first solutions you suggested is not feasible to me, I can't access cameras.
I tried second one, however It doesn't seem to be doing anything. It adds itself as rtsp helper to iptables, but doesnt do anything to the actual udp packages. I tried activating it with modprobe, added in /etc/modules and can see it loaded with ``` lsmod | grep nf_rtsp ```.

@uablrek tcpdump shows packages reach node, it wasnt 0 bytes after all. It just doesnt get forwarded to the node.
MTU is not the issue since packet sizes are less than MTU.

**Comment by canuysal** [comment]
@uablrek I'm using flannel at the time being, but tried this on calico as well. Thanks for the heads up, I will properly format my issue next time.

**Comment by dcbw** [comment]
@canuysal Kubernetes does not support port ranges for containers. Which is probably what you're running into; after the initial control connection on 554 the randomly assigned port is not being forwarded between camera + container. The port cannot be added after the container is started becuase (depending on the network plugin) they may not be able to dynamically update the ports on-the-fly. And you can't just say "forward all ports X-Y to container A" becuase Kubernetes doesn't support that yet.

**Comment by thockin** [comment]
>  And you can't just say "forward all ports X-Y to container A" becuase Kubernetes doesn't support that yet.

And practically I don't see how it could.  There are two ways to look at this: static and dynamic.

Static: If we allowed pod port ranges, you could ask kubelet to map N incoming ports on the node to N  target ports on the pod.  The node only has 64K UDP ports available, so scheduling multiple pods that want this would be difficult and wasteful

Dynamic: We would need to detect a new connection and install/expand rules to forward additional ports on the fly.   I'm not saying it's impossible but I don't know how to do it off the top of my head.

https://speakerdeck.com/thockin/kubernetes-and-networks-why-is-this-so-dang-hard

If you are using a network mode which requires outgoing NAT to reach the larger network ("island mode"), you are "borrowing" shared resources (ports), and those resources are managed.

This is a case where "flat mode" works much better.  If your pod could talk to your camera with no NAT you would literally get sall of the traffic.  It might cause other problems to use random UDP ports (conntrack) but we can cross that bridge when we get there.

As such - I don't think this is a "bug" in kubernetes.  I'm happy to keep the discussion going, but we should probably close this issue?  The sig-net mailing list might be a better venue.

Disagree?

**Comment by caseydavenport** [comment]
I agree Tim - this sounds like a limitation in the networking mode that's being used (i.e., outside of Kubernetes and not a bug). 

Mailing list sounds like a good place to continue discussion, but I'd expect that using a network mode that gives pods real routable IP addresses (there are a bunch of options depending on your environment) would work here. 

> I'm using flannel at the time being, but tried this on calico as well. 

I would guess you can probably make this scenario work with either, but the default configurations for both flannel and Calico will NAT traffic from pods to things that aren't pods, because that "just works" for a bunch of environments. You'll want to turn that NAT off. Once you do though, you need to ensure that pods can talk to things outside of k8s via some other means.

/close

**Comment by canuysal** [comment]
I tried same thing with a docker container, without kubernetes and it works(no host network). Shouldn't it work on kubernetes as well? I know I said It's not a k8s issue but this led me to think otherwise.

There is also this [issue](https://github.com/kubernetes/kubernetes/issues/94561) which is closed by a workaround,
This unanswered and deleted [stackoverflow question](https://webcache.googleusercontent.com/search?q=cache:8Eg-PoqCVuwJ:https://stackoverflow.com/questions/60118428/client-inside-k8s-pod-consuming-rtsp-video-via-udp-from-a-camera+&cd=1&hl=en&ct=clnk&gl=tr)

Shouldn't we investigate a little further? Why can it run on docker easily but not in kubernetes?

Closing an issue should be the op's choice in my opinion, at least within a few days after the most recent answer.

**Comment by caseydavenport** [comment]
@canuysal sorry - I thought we had determined that this was not a problem with Kubernetes, nor a new enhancement request, and so generally we close issues once that's determined to be the outcome.

> I tried same thing with a docker container, without kubernetes and it works(no host network)

How did you configure networking for this container? If the above analysis is correct, the issue has nothing to do with how you launched the container (Docker vs Kubernetes vs something else), rather it has to do with how you're getting packets from one place to another (routing / NAT).

**Comment by canuysal** [comment]
@caseydavenport thank you. I launched docker container with a regular docker run command, no additional network settings. Is there something different between docker and k8s container network policy that would cause this behaviour?

**Comment by dougsland** [comment]
Hi @canuysal ,

> @caseydavenport thank you. I launched docker container with a regular docker run command, no additional network settings. Is
> there something different between docker and k8s container network policy that would cause this behaviour?

I believe the question returns to you, in this case, are you defining any network policy in your env? Are you using docker as runtime as well in k8s or other runtime like containerd/cri-o ? Any thing in the logs? Anything different in the tcpdump ? Are you using the same components and versions? 

> There is also this [issue](https://github.com/kubernetes/kubernetes/issues/94561) which is closed by a workaround,
Looks like switching the component made the work (not really kubernetes).  Have you tried the workaround as well?

As others mentioned, you would get more people involved in this thread via mailing list. Please let me know if would like to continue via mail list.

/cc @rmazzine in case he wants to provided some data.

**Comment by canuysal** [comment]
@dougsland Hi,
I tried some network policies, like allowing all udp network traffic but they didn't work. In this case however, I'm not using any network policies. 

I'm using docker runtime, didn't check the logs on that. 

With tcpdump, conntrack, I figured out packets reach the node but doesnt get forwarded to udp, if I use use netcat to forward it, it works. With using docker, however, It works without using any additional network configurations. I tried this with multiple kubernetes versions in different clusters I created. Tested it calico and flannel, both results the same. I will try the script you mentioned and report back, thank you.

I would like to continue with mailing list if thats the right place to talk about it, sorry for all the trouble. How should I go with this?

**Comment by dougsland** [comment]
> @dougsland Hi,
> I tried some network policies, like allowing all udp network traffic but they didn't work. In this case however, I'm not using any
> network policies.
> 
> I'm using docker runtime, didn't check the logs on that.
> 
> With tcpdump, conntrack, I figured out packets reach the node but doesnt get forwarded to udp, if I use use netcat to forward it, it
> works. With using docker, however, It works without using any additional network configurations. I tried this with multiple
> kubernetes versions in different clusters I created. Tested it with calico and flannel, both results the same. I will try the script you
> mentioned and report back, thank you.

Do you mind to share the step by step here so I can give a try following your steps as well?
@canuysal 
> 
> I would like to continue with mailing list if thats the right place to talk about it, sorry for all the trouble. How should I go with this?

No problem at all, here the list info: https://groups.google.com/g/kubernetes-sig-network
Additional info about sig-network/meetings etc: https://github.com/kubernetes/community/tree/master/sig-network
https://groups.google.com/g/kubernetes-sig-network

**Comment by canuysal** [comment]
> hi @aojea , I will try to make it more clear.
> The camera is in the host network, ie 10.5.5.2
> Pod is in the CNI, ie 10.244.10.16, The node running the pod has host IP ie 10.5.5.12
> 
> Im trying to connect rtsp stream within the pod. To reproduce:
> 
> If you dont have access to an rtsp stream, (if you have cctv you probably have one)
> you can create one using this link -> [rtsp with ffmpeg](https://superuser.com/questions/1420328/streaming-rtsp-with-ffmpeg)
> make sure you change the fields tcp to udp.
> 
> Rtsp stream you created must be on another computer on host network. Confirm you can get the stream with ffplay command on the node you will run the pod. For example, run
> 
> ```
> ffmpeg -i <rtsp link> -f null -
> ```
> 
> from the node 10.5.5.12, and you should get frames rolling. if it hangs it is not working.
> 
> After you confirm it, try to start a basic ubuntu:18.04 or 20.04 pod with sleep, log in the pod shell, install ffmpeg and try the ffplay command again. You can background it and probe with tcddump or any other tool you like.

@dougsland this comment has the steps to reproduce kubernetes part. for docker,  you can do
```
#ubuntu version doesnt matter
docker run -it ubuntu:20.04 /bin/bash
apt update
apt install ffmpeg
ffmpeg -i <rtsp link> -f null -
```
And you should frames are rolling, if it hangs, it doesnt work.

**Comment by canuysal** [comment]
I'm closing the issue and will try my chances on the mailing list. Thanks for all the help.

**Comment by dcdennis** [comment]
@canuysal Did you find a resolution to this issue?

**Comment by shunwatai** [comment]
> I tried same thing with a docker container, without kubernetes and it works(no host network). Shouldn't it work on kubernetes as well? I know I said It's not a k8s issue but this led me to think otherwise.
> 
> There is also this [issue](https://github.com/kubernetes/kubernetes/issues/94561) which is closed by a workaround, This unanswered and deleted [stackoverflow question](https://webcache.googleusercontent.com/search?q=cache:8Eg-PoqCVuwJ:https://stackoverflow.com/questions/60118428/client-inside-k8s-pod-consuming-rtsp-video-via-udp-from-a-camera+&cd=1&hl=en&ct=clnk&gl=tr)
> 
> Shouldn't we investigate a little further? Why can it run on docker easily but not in kubernetes?
> 
> Closing an issue should be the op's choice in my opinion, at least within a few days after the most recent answer.

I have the same issue when trying to stream a RTSP source by FFMPEG, it runs ok inside a docker container but fails when running in K8S... I have no idea.

The following command run ok inside a pure docker container but failed in K8S
```
ffmpeg -i <rtsp link> -f null -
```

@dcdennis I have a workaround by streaming the RTSP source through TCP by adding the options `-rtsp_transport tcp` which can run successfully in K8S
```
ffmpeg -rtsp_transport tcp -i <rtsp link> -f null -
```
