### ISSUE TITLE
The document of ReadinessGates mentioned in the note cannot find

### ISSUE THREAD

**Issue by yangyuliufeng** [kubernetes/kubernetes#100238]
[The document of ReadinessGates mentioned in the note](https://github.com/kubernetes/kubernetes/blob/9657dd77a3563ffc7dbd061d51f34f714b1f8d5c/pkg/apis/core/types.go#L2835) cannot find.

**Comment by zxh326** [comment]
/assign

You are right. The correct link should be https://git.k8s.io/enhancements/keps/sig-network/580-pod-readiness-gates/README.md

**Comment by zxh326** [comment]
may be fixed
/close
