### ISSUE TITLE
default network resolves to multiple instances, please specify

### ISSUE THREAD

**Issue by svennela** [kubernetes/kubernetes#10029]
Hi,

Trying to deploy kubernetes on vsphere, Running into below error? Any help? Where to specify network details?? 

Starting cluster using provider: vsphere
... calling verify-prereqs
... calling kube-up
Starting master VM (this can take a minute)...
Error: default network resolves to multiple instances, please specify

Also it created VM, next time when i run it has to be deleted..

**Comment by skuzye** [comment]
You have to export GOVC_NETWORK environment variable, e.g. export GOVC_NETWORK='my_switch'
