### ISSUE TITLE
kubelet uses 120GB memory after 20,000 job created and retains 80GB memory after jobs completed and deleted

### ISSUE THREAD

**Issue by mzyfree** [kubernetes/kubernetes#100241]
#### What happened:
1.create 20K job and each job is a java application running data monitor and analysis 
2.delete all jobs after they have been completed
3.kubelet memory usage 120GB memory:
```
Name:   kubelet
Umask:  0022
State:  S (sleeping)
Tgid:   9278
Ngid:   9278
Pid:    9278
PPid:   9274
TracerPid:      0
Uid:    0       0       0       0
Gid:    0       0       0       0
FDSize: 1024
Groups:
VmPeak: 126307060 kB
VmSize: 126307056 kB
VmLck:         0 kB
VmPin:         0 kB
VmHWM:  106238456 kB
VmRSS:  85699368 kB
RssAnon:        85675408 kB
RssFile:           23960 kB
RssShmem:              0 kB
VmData: 126179776 kB
VmStk:       132 kB
VmExe:     48260 kB
VmLib:      2072 kB
VmPTE:    210628 kB
VmSwap:    72604 kB
Threads:        362
```

#### What you expected to happen:
kubelet should use and retain less memory 

#### Anything else we need to know?:
Through pprof,we find the inuse_space size is 360MB.And 67% of 120GB is Anonymous(through mmap?).

#### Environment:
- Kubernetes version (use `kubectl version`):
- Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.12", GitCommit:"e2a822d9f3c2fdb5c9bfbe64313cf9f657f0a725", GitTreeState:"archive", BuildDate:"2020-09-22T06:47:35Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Centos 7.5
- Kernel (e.g. `uname -a`):
- 3.10.0-957.21.3.el7.x86_64 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
pprof png:
![profile002](https://user-images.githubusercontent.com/7983349/111131222-fe2d8100-85b2-11eb-8826-7a583d0ed339.png)

**Comment by wzshiming** [comment]
This should have been fixed https://github.com/kubernetes/kubernetes/pull/27916

**Comment by wzshiming** [comment]
This issue is duplicated https://github.com/kubernetes/kubernetes/issues/94583

**Comment by Dingshujie** [comment]
@wzshiming #100326 not fixs this issue.

**Comment by Dingshujie** [comment]
- cadvisor has memory leak: cadvisor watch all cgroup director.  when file or directory delete, inotify will recevie IN_DELETE event, when cadvisor recevie IN_DELETE, cadvisor will call inotify RemoveWatch to remove watch descriptor. When watch descriptor delete before function called, function will return EINVAL, may lead this path remain in watches and paths map, and also not delete path in containersWatched, finally lead to memory leak
- before kubernetes 1.19, kubelet use ref manager  to manage the reference, this reference used for reporting events such as creation,failure, etc.  In job completed scenes, container exit with exit code 0, kubelet not to remove reference in ref manager, so lead to memory leak

**Comment by ehashman** [comment]
not actually fixed in k8s, the PR above should not have closed this bug

**Comment by gjkim42** [comment]
cc

**Comment by jonyhy96** [comment]
Can u provide `proc/[pid]/statm` info of kubelet?

**Comment by gjkim42** [comment]
/reopen

Waiting for https://github.com/google/cadvisor/pull/3014 to be merged and cadvisor to be updated.

**Comment by gjkim42** [comment]
> Waiting for [google/cadvisor#3014](https://github.com/google/cadvisor/pull/3014) to be merged and cadvisor to be updated.

cc @bobbypage

**Comment by bobbypage** [comment]
google/cadvisor#3014 has merged. It will be included in next cAdvisor release and next k8s version (1.24). 

If this problem is more widespread we can consider to backport it... is it common to get into case of inotify handles being leaked?

**Comment by rphillips** [comment]
We have a number of issues that might be the symptom of this issue. Namely, a few customers are reporting memory is full on the node, but all the RSS doesn't add up to the in-use space. With the anonymous mmapped data being retained, this issue seems like the culprit.

Can we get a backport to 1.23 and 1.22?

**Comment by gjkim42** [comment]
https://kubernetes.slack.com/archives/C0BP8PW9G/p1641412256497400

I think we can expect quite a big performance boost from this issue.
I'll backport #106473 to 1.23 and 1.22.

**Comment by bobbypage** [comment]
> We have a number of issues that might be the symptom of this issue. Namely, a few customers are reporting memory is full on the node, but all the RSS doesn't add up to the in-use space. With the anonymous mmapped data being retained, this issue seems like the culprit.
> 
> Can we get a backport to 1.23 and 1.22?

Agree, sounds like we should backport it. I don't think we need to bump cAdvisor, we just need to bump k/utils to pick up the fix [kubernetes/utils#228](https://github.com/kubernetes/utils/pull/228)

**Comment by rphillips** [comment]
I created a 1.21 backport linked to this issue: https://github.com/kubernetes/kubernetes/pull/108335

**Comment by rphillips** [comment]
The 1.20 backport https://github.com/kubernetes/kubernetes/pull/108337

**Comment by gjkim42** [comment]
> /reopen
> 
> 
> 
> Waiting for https://github.com/google/cadvisor/pull/3014 to be merged and cadvisor to be updated.

I think we can close this, as all relevant prs have been merged.

/close
