### ISSUE TITLE
To podresource API,  GetPodResources function return the cpu list in share pool for the Burstable QoS pod and so on

### ISSUE THREAD

**Issue by huone1** [kubernetes/kubernetes#100211]
To CPU Management function  in kubelet:

I hope to get all pod’s resource info by “/var/lib/kubelet/pod-resources/kubelet.sock”
in my test：
numa info: one numa node  has 0-7 cpus
![image](https://user-images.githubusercontent.com/71266853/111026591-eaa0df80-8425-11eb-9ca2-a82ea733226e.png)

![image](https://user-images.githubusercontent.com/71266853/111026094-76653c80-8423-11eb-8fe3-2abb8c41814a.png)

![image](https://user-images.githubusercontent.com/71266853/111026451-4a4abb00-8425-11eb-98f5-7480e332216f.png)

the cpu list which the container can uses is nothing for me, because they are in  the shared pool and any container can use them.
#### What happened:
 To the containers in Guaranteed pods with integer CPU requests, return the exclusive CPUs;
 but to others, return all cpus in the shared pool
#### What you expected to happen:
To the containers in Guaranteed pods with integer CPU requests, return the exclusive CPUs;
 To others, return empty array     

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
 
![image](https://user-images.githubusercontent.com/71266853/111026397-f213b900-8424-11eb-8195-ebbf9530d12c.png)

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by matthyx** [comment]
I am not sure you can "hard assign" cpus with resource quotas... they are still shared somehow afaik.

Can you also provide more information (pod spec, ...) to reproduce?

Please re-open this bug once you have provided more information.

/triage needs-information
/close
