### ISSUE TITLE
BTRFS: Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/snap/microk8s/common/var/lib/kubelet": could not find device with major: 0, minor: 29 in cached partitions map

### ISSUE THREAD

**Issue by jcdutton** [kubernetes/kubernetes#100224]
#### What happened:
kubelet keeps restarting every 15 seconds.
The error message that I think is causing it is:
microk8s.daemon-kubelet[70940]: F0313 18:01:19.700016   70940 kubelet.go:1350] Failed to start ContainerManager failed to get rootfs info: failed to get device for dir "/var/snap/microk8s/common/var/lib/kubelet": could not find device with major: 0, minor: 29 in cached partitions map

/var/snap/...  is a BTRFS filesystem.
btrfs does not report file mount information the same as other filesystems.

/proc/1/mountinfo for this system:
24 31 0:22 / /sys rw,nosuid,nodev,noexec,relatime shared:7 - sysfs sysfs rw
25 31 0:23 / /proc rw,nosuid,nodev,noexec,relatime shared:14 - proc proc rw
26 31 0:5 / /dev rw,nosuid,noexec,relatime shared:2 - devtmpfs udev rw,size=16352228k,nr_inodes=4088057,mode=755
27 26 0:24 / /dev/pts rw,nosuid,noexec,relatime shared:3 - devpts devpts rw,gid=5,mode=620,ptmxmode=000
28 31 0:25 / /run rw,nosuid,nodev,noexec,relatime shared:5 - tmpfs tmpfs rw,size=3286564k,mode=755
31 1 0:27 /@ / rw,relatime shared:1 - btrfs /dev/mapper/nvme_crypt rw,ssd,space_cache,subvolid=257,subvol=/@
30 24 0:6 / /sys/kernel/security rw,nosuid,nodev,noexec,relatime shared:8 - securityfs securityfs rw
32 26 0:30 / /dev/shm rw,nosuid,nodev shared:4 - tmpfs tmpfs rw
33 28 0:31 / /run/lock rw,nosuid,nodev,noexec,relatime shared:6 - tmpfs tmpfs rw,size=5120k
34 24 0:32 / /sys/fs/cgroup ro,nosuid,nodev,noexec shared:9 - tmpfs tmpfs ro,mode=755
35 34 0:33 / /sys/fs/cgroup/unified rw,nosuid,nodev,noexec,relatime shared:10 - cgroup2 cgroup2 rw,nsdelegate
36 34 0:34 / /sys/fs/cgroup/systemd rw,nosuid,nodev,noexec,relatime shared:11 - cgroup cgroup rw,xattr,name=systemd
37 24 0:35 / /sys/fs/pstore rw,nosuid,nodev,noexec,relatime shared:12 - pstore pstore rw
38 24 0:36 / /sys/fs/bpf rw,nosuid,nodev,noexec,relatime shared:13 - bpf none rw,mode=700
39 34 0:37 / /sys/fs/cgroup/net_cls,net_prio rw,nosuid,nodev,noexec,relatime shared:15 - cgroup cgroup rw,net_cls,net_prio
40 34 0:38 / /sys/fs/cgroup/cpuset rw,nosuid,nodev,noexec,relatime shared:16 - cgroup cgroup rw,cpuset
41 34 0:39 / /sys/fs/cgroup/blkio rw,nosuid,nodev,noexec,relatime shared:17 - cgroup cgroup rw,blkio
42 34 0:40 / /sys/fs/cgroup/pids rw,nosuid,nodev,noexec,relatime shared:18 - cgroup cgroup rw,pids
43 34 0:41 / /sys/fs/cgroup/devices rw,nosuid,nodev,noexec,relatime shared:19 - cgroup cgroup rw,devices
44 34 0:42 / /sys/fs/cgroup/memory rw,nosuid,nodev,noexec,relatime shared:20 - cgroup cgroup rw,memory
45 34 0:43 / /sys/fs/cgroup/perf_event rw,nosuid,nodev,noexec,relatime shared:21 - cgroup cgroup rw,perf_event
46 34 0:44 / /sys/fs/cgroup/cpu,cpuacct rw,nosuid,nodev,noexec,relatime shared:22 - cgroup cgroup rw,cpu,cpuacct
47 34 0:45 / /sys/fs/cgroup/hugetlb rw,nosuid,nodev,noexec,relatime shared:23 - cgroup cgroup rw,hugetlb
48 34 0:46 / /sys/fs/cgroup/freezer rw,nosuid,nodev,noexec,relatime shared:24 - cgroup cgroup rw,freezer
49 34 0:47 / /sys/fs/cgroup/rdma rw,nosuid,nodev,noexec,relatime shared:25 - cgroup cgroup rw,rdma
50 25 0:48 / /proc/sys/fs/binfmt_misc rw,relatime shared:26 - autofs systemd-1 rw,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=33407
51 26 0:49 / /dev/hugepages rw,relatime shared:27 - hugetlbfs hugetlbfs rw,pagesize=2M
52 26 0:20 / /dev/mqueue rw,nosuid,nodev,noexec,relatime shared:28 - mqueue mqueue rw
53 28 0:50 / /run/rpc_pipefs rw,relatime shared:29 - rpc_pipefs sunrpc rw
54 24 0:7 / /sys/kernel/debug rw,nosuid,nodev,noexec,relatime shared:30 - debugfs debugfs rw
55 24 0:11 / /sys/kernel/tracing rw,nosuid,nodev,noexec,relatime shared:31 - tracefs tracefs rw
128 54 0:11 / /sys/kernel/debug/tracing rw,nosuid,nodev,noexec,relatime shared:72 - tracefs tracefs rw
56 24 0:51 / /sys/fs/fuse/connections rw,nosuid,nodev,noexec,relatime shared:32 - fusectl fusectl rw
57 24 0:21 / /sys/kernel/config rw,nosuid,nodev,noexec,relatime shared:33 - configfs configfs rw
130 31 7:1 / /snap/snapd/11107 ro,nodev,relatime shared:70 - squashfs /dev/loop1 ro
133 31 7:0 / /snap/core/10859 ro,nodev,relatime shared:73 - squashfs /dev/loop0 ro
529 31 0:27 /@home /home rw,relatime shared:120 - btrfs /dev/mapper/nvme_crypt rw,ssd,space_cache,subvolid=258,subvol=/@home
299 31 259:2 / /boot rw,relatime shared:123 - ext2 /dev/nvme0n1p2 rw
511 50 0:58 / /proc/sys/fs/binfmt_misc rw,nosuid,nodev,noexec,relatime shared:292 - binfmt_misc binfmt_misc rw
641 28 0:62 / /run/user/122 rw,nosuid,nodev,relatime shared:648 - tmpfs tmpfs rw,size=3286560k,mode=700,uid=122,gid=126
667 641 0:63 / /run/user/122/gvfs rw,nosuid,nodev,relatime shared:662 - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=122,group_id=126
619 28 0:59 / /run/user/1000 rw,nosuid,nodev,relatime shared:347 - tmpfs tmpfs rw,size=3286560k,mode=700,uid=1000,gid=1000
1156 619 0:60 / /run/user/1000/gvfs rw,nosuid,nodev,relatime shared:361 - fuse.gvfsd-fuse gvfsd-fuse rw,user_id=1000,group_id=1000

#### What you expected to happen:
kubelet should not error and not restart and just carry on running.
#### How to reproduce it (as minimally and precisely as possible):
Just try starting kubelet on a btrfs filesystem
#### Anything else we need to know?:
Filesystem is btrfs
#### Environment:
- Kubernetes version (use `kubectl version`):
microk8s.kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+350770ed07a558", GitCommit:"350770ed07a558ba1ce8202a6f9ea849f9a75f06", GitTreeState:"clean", BuildDate:"2021-02-11T20:09:31Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.2-34+350770ed07a558", GitCommit:"350770ed07a558ba1ce8202a6f9ea849f9a75f06", GitTreeState:"clean", BuildDate:"2021-02-11T20:10:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Single Physical Host. 32 CPU, 32GB RAM, 1TB NVME SSD.
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Kernel (e.g. `uname -a`):
generic upstream:
inux thread 5.11.6 #65 SMP Fri Mar 12 23:42:30 GMT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
snap install microk8s --classic
- Network plugin and version (if this is a network-related bug):
flanneld
- Others:
Required before flanneld will run:
microk8s disable ha-cluster
I have attached the full syslog output during a single run of 15 seconds, before it repeats.

[syslog.kubelet.txt](https://github.com/kubernetes/kubernetes/files/6136586/syslog.kubelet.txt)

**Comment by pacoxu** [comment]
I think it is fixed in next release 1.21 as https://github.com/kubernetes/kubernetes/issues/98009#issuecomment-794520115

/cc gjkim42 
/sig node

**Comment by pacoxu** [comment]
/area cadvisor 

https://github.com/kubernetes/kubernetes/blob/release-1.20/vendor/github.com/google/cadvisor/fs/fs.go#L575

**Comment by gjkim42** [comment]
Thanks @pacoxu 
This looks similar to https://github.com/kubernetes/kubernetes/issues/94335, and should have been resolved by https://github.com/kubernetes/kubernetes/pull/98042.

@jcdutton 
I think updating kubernetes to 1.20.3 or higher can address the issue. Could you try this?

/assign

**Comment by jcdutton** [comment]
I tried 1.20.4.
But, there is a new problem. containerd fails to start. Just "timeout was exceeded"
<28>1 2021-03-14T13:44:30.207681+00:00 thread systemd 1 - -  snap.microk8s.daemon-containerd.service: State 'stop-sigterm' timed out. Killing.
<29>1 2021-03-14T13:44:30.208168+00:00 thread systemd 1 - -  snap.microk8s.daemon-containerd.service: Killing process 18584 (containerd) with signal SIGKILL.
<28>1 2021-03-14T13:44:30.210345+00:00 thread systemd 1 - -  snap.microk8s.daemon-containerd.service: Main process exited, code=killed, status=9/KILL
<28>1 2021-03-14T13:44:30.210447+00:00 thread systemd 1 - -  snap.microk8s.daemon-containerd.service: Failed with result 'timeout'.
<30>1 2021-03-14T13:44:30.210944+00:00 thread systemd 1 - -  Stopped Service for snap application microk8s.daemon-containerd.

**Comment by jcdutton** [comment]
I don't know if it helps but..
My system has a LUKS encrypted partition, with btrfs running on top of it.  No LVM used.

**Comment by gjkim42** [comment]
I think BTRFS issue is no longer reproduced.

Regarding the containerd issue, I have no idea what LUKS is.
It could be helpful to comment the output of `journalctl -u containerd`....

**Comment by jcdutton** [comment]
As a question. Why is kubenetes looking for device major:minor numbers?
Can someone explain to me what kubenetes need this for? I might be able to suggest a more reliable approach that covers all file system types.
I think it is a flawed approach, because on btrfs major:minor numbers are not globally unique.
31 1 0:27 /@ / rw,relatime shared:1 - btrfs /dev/mapper/nvme_crypt rw,ssd,space_cache,subvolid=257,subvol=/@
529 31 0:27 /@home /home rw,relatime shared:120 - btrfs /dev/mapper/nvme_crypt rw,ssd,space_cache,subvolid=258,subvol=/@home

See, both those have the same major:minor of 0:27
I believe the only way to make it globally unique is to include the next column. i.e. the /@  or the /@home

**Comment by gjkim42** [comment]
I think cadvisor already has collected the mount point.
https://github.com/kubernetes/kubernetes/blob/5b0a2c3a29f6b5392e0f8f94ba5669bdc9eb73f6/vendor/github.com/google/cadvisor/fs/fs.go#L73-L79

**Comment by jcdutton** [comment]
for the containerd problem with 1.20.4:
output of journalctl -u containerd attached
[containerd.journal.txt](https://github.com/kubernetes/kubernetes/files/6136852/containerd.journal.txt)

LUKS is Linux full disk encryption.

**Comment by jcdutton** [comment]
The kubernetes appear to be up now.
Should I be worried about this message in the logs that might be related:
<30>1 2021-03-14T15:08:34.076990+00:00 thread microk8s.daemon-kubelite 64250 - -  E0314 15:08:34.076630   64250 cri_stats_provider.go:376] Failed to get the info of the filesystem with mountpoint "/var/snap/microk8s/common/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs": cannot find filesystem info for device "/dev/mapper/nvme_crypt".

/dev/mapper/nvme_crypt is ambiguous, because with btrfs, two different btrfs filesystems are mounted from it.
root and home.

**Comment by gjkim42** [comment]
I think the same mount source `/dev/mapper/nvme_crypt` can cause the error. 

> Should I be worried about this message in the logs that might be related:

I think that error was recovered.
If there is a problem, please report it.
