### ISSUE TITLE
Unable to write to windows container on Kubernetes 1.19.6

### ISSUE THREAD

**Issue by lelix** [kubernetes/kubernetes#100284]
Hello,

there is an application, runs with the IIS and .net framework (using docker image - mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-2004)
the application works well in Kubernetes and there are no questions (using AWS EKS with windows nodes group (node-ami-family WindowsServer2004CoreContainer))

But there is one caveat
an application is written in .net framework 4.8 and tries to write all sorts of temp files to the directory, and this is the problem
unfortunately, he cannot, something with permissions (I guess issue with Kubernetes)
**Notes**: Locally I do not have an issue with permissions(I mean run my container in Docker), only in Kubernetes

Gave different rights, Write, FullControl - nothing comes out (but works locally)
Thus, it gave rights to folders in the application:
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")
$acl = Get-Acl "C:\inetpub\wwwroot\"
$acl.SetAccessRule($rule)
Set-Acl "C:\inetpub\wwwroot\" $acl

**Tell me what I'm doing wrong, who can help?**

**Comment by jsturtevant** [comment]
Are these commands 

```
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")
$acl = Get-Acl "C:\inetpub\wwwroot"
$acl.SetAccessRule($rule)
Set-Acl "C:\inetpub\wwwroot" $acl
``` 
run in a dockerfile?  What does the `whoami` in the container output?

**Comment by lelix** [comment]
> Are these commands
> 
> ```
> $rule = New-Object System.Security.AccessControl.FileSystemAccessRule("IIS_IUSRS", "Modify", "ContainerInherit,ObjectInherit", "None", "Allow")
> $acl = Get-Acl "C:\inetpub\wwwroot"
> $acl.SetAccessRule($rule)
> Set-Acl "C:\inetpub\wwwroot" $acl
> ```
> 
> run in a dockerfile? What does the `whoami` in the container output?

user manager\containeradministrator

**Comment by jsturtevant** [comment]
@lelix   Are those commands in a docker file or are they commands that the container executes when it is running?

**Comment by lelix** [comment]
> @lelix Are those commands in a docker file or are they commands that the container executes when it is running?

in dockerfile
