### ISSUE TITLE
[Failing Test] [sig-node] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance] (ci-kubernetes-e2e-windows-gce-20h2)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100252]
#### Which jobs are failing:
ci-kubernetes-e2e-windows-gce-20h2

#### Which test(s) are failing:
[sig-node] Container Runtime blackbox test when running a container with a new image should be able to pull from private registry with secret [NodeConformance]

#### Since when has it been failing:
Since March 2

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-windows-20h2-master&include-filter-by-regex=Container%20Runtime%20blackbox

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/node/runtime.go:393
Mar 15 11:12:47.191: All 3 attempts failed: expected container state: Running, got: "Waiting"
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/node/runtime.go:400
```

#### Anything else we need to know:

Some example Spyglass links:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1371397503974379520
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1371336864115462144
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1371276206955040768
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1371215557856071680

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Container%20Runtime%20blackbox%20test%20when%20running%20a%20container%20with%20a%20new%20image%20should%20be%20able%20to%20pull%20from%20private%20registry%20with%20secret#0924ab7b625017b4c31a

/sig node windows
/priority important-soon

**Comment by jeremyje** [comment]
I'm well aware of this issue. It's due to the fact that the private repo image does not support 20h2. It's actually able to access the image fine though.

**Comment by thejoycekung** [comment]
@jeremyje Would it be possible to disable this test on this job then, since it's a known issue?

**Comment by claudiubelu** [comment]
> 
> 
> I'm well aware of this issue. It's due to the fact that the private repo image does not support 20h2. It's actually able to access the image fine though.

Hmm, it's a 20h2 run, and it's trying to the image ``gcr.io/authenticated-image-pulling/windows-nanoserver:v1`` which does not have a Windows image for 20h2 in its manifest list. According to this [1], the 2004 and 20h2 jobs should use the ``image-repo-list-2004`` file. That fill will contain the ``gcAuthenticatedRegistry: e2eprivate``, a registry which will contain the image ``e2eprivate/windows-nanoserver:v1``, which contains images for 1809, 1903, 1909, 2004, 20h2 in its manifest list. Ofc, the job will need a things:

Test arg ``--docker-config-file`` will have to contain the docker credentials that are going to be used by that test. That job, if you look at its labels, has the label ``preset-windows-private-registry-cred`` https://github.com/kubernetes/test-infra/blob/8ca99adc33381a959787ad285056e240f5707713/config/jobs/kubernetes-sigs/sig-windows/sig-windows-sac.yaml#L124,  which is the preset that sets that ``DOCKER_CONFIG_FILE`` env variable and add that docker config file as a volume. You can see the preset definition here: https://github.com/kubernetes/test-infra/blob/ee34df90fc037e92586b431dc4881b8a68fdf245/config/prow/config.yaml#L651

[1] https://github.com/kubernetes-sigs/windows-testing/tree/master/images#image-repository-list

**Comment by jeremyje** [comment]
QQ: Won't `image-repo-list-2004` for 20H2 break other tests? Should we just update the e2eprivate reference in master?

**Comment by jsturtevant** [comment]
/triage accepted 
@chewong do you know if `image-repo-list-2004` is the right one for 20H2 tests?

**Comment by chewong** [comment]
Yes, it should be the right one since it's using the default test image registry (`k8s.gcr.io/e2e-test-images`), which should have 20H2 support.

**Comment by thejoycekung** [comment]
Started passing after March 25 -- from https://github.com/kubernetes-sigs/windows-testing/pull/259 looks like.

/close
