### ISSUE TITLE
Suggest adding `local time` for the output of `kubectl get nodes -owide`

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kubernetes#100232]
The clock synchronization error between different nodes often cause some issues which difficult to debug, it would be great if the `kubectl get nodes -owide` can also have the field like `local time` which can print out the realtime on the node, and this will help debugging when there are issues for clock synchronization error.

**Comment by pacoxu** [comment]
I think you should config ntp/chronyd on your nodes. 

https://github.com/kubernetes/node-problem-detector/blob/f42281ee2658900bdb0571e1159a43f6ab712a19/config/custom-plugin-monitor.json
Then, configure npd with a ntp checking.

**Comment by pacoxu** [comment]
Get the lastHeartbeatTime as a workaround:
`kubectl get node -o=custom-columns=NAME:.metadata.name,IP:.status.addresses[0].address,VERSION:.status.nodeInfo.kubeletVersion,LAST_HEARTBEAT:status.conditions[-1].lastHeartbeatTime
`

```
[root@dce-master-10-10-121-11 dce]# kubectl get node -o=custom-columns=NAME:.metadata.name,IP:.status.addresses[0].address,VERSION:.status.nodeInfo.kubeletVersion,LAST_HEARTBEAT:status.conditions[-1].lastHeartbeatTime
NAME                      IP             VERSION   LAST_HEARTBEAT
dce-master-10-10-121-11   10.10.121.11   v1.18.0   2021-03-15T06:39:03Z
dce-node-10-10-121-12     10.10.121.12   v1.18.0   2021-03-15T06:39:01Z
dce-node-10-10-121-13     10.10.121.13   v1.18.0   2021-03-15T06:39:08Z
```

**Comment by gyliu513** [comment]
@pacoxu `lastHeartbeatTime` may not able to help much, as what I want is the real time / local time on each worker node.

Also I can config NTP, but this will involve some extra config, here I want to enable k8s can print out the local time so that I can have a global view of the time for each worker node ;-)
