### ISSUE TITLE
Do not  delete pod if pod is in waiting pods  but not scheduled.

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#100235]
#### What happened:

https://github.com/kubernetes/kubernetes/blob/9657dd77a3563ffc7dbd061d51f34f714b1f8d5c/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L697:L704

We may delete podS though they  may be waiting in `WaitingPods`

#### What you expected to happen:

Do not delete waiting pods if they are not scheduled.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cwdsuzhou** [comment]
/cc @Huang-Wei

WDYT ?

**Comment by Huang-Wei** [comment]
It sounds to me that you prefer to prioritize waiting Pod over other assigned Pods. In that case, you may want to exclude waiting Pods in the earlier Filtering/Sorting Victims step, instead of simply disregard the deletion in PrepareCandidate(). 

In general, when Permit plugins work along with PostFilter (preemption), the logic could be complicated. There may not be a general preemption implementation (probably in the future we can exercise pluginArgs to provide different options). So for now the best bet is to implement your own PostFilter plugin.

**Comment by cwdsuzhou** [comment]
> It sounds to me that you prefer to prioritize waiting Pod over other assigned Pods. In that case, you may want to exclude waiting Pods in the earlier Filtering/Sorting Victims step, instead of simply disregard the deletion in PrepareCandidate().
> 
> In general, when Permit plugins work along with PostFilter (preemption), the logic could be complicated. There may not be a general preemption implementation (probably in the future we can exercise pluginArgs to provide different options). So for now the best bet is to implement your own PostFilter plugin.

Got it!

But for the default preemption plugin, we delete the victims to free resources. 

If pod has assigned, we should delete it.
If pod has not assigned, we just need reject it in WaitingPod because the pod just exists in the `NodeInfo` cache.

**Comment by Huang-Wei** [comment]
> If pod has not assigned, we just need reject it in WaitingPod because the pod just exists in the `NodeInfo` cache.

Oh, your point was to verify if it's a waiting pod first, and then delete it? If so, then it makes sense to me.

```go
if waitingPod := fh.GetWaitingPod(victim.UID); waitingPod != nil {
    // reject it
} else {
    // delete the victim
}
```

Feel free to raise a PR.

/assign @cwdsuzhou

**Comment by cwdsuzhou** [comment]
> > If pod has not assigned, we just need reject it in WaitingPod because the pod just exists in the `NodeInfo` cache.
> 
> Oh, your point was to verify if it's a waiting pod first, and then delete it? If so, then it makes sense to me.
> 
> ```go
> if waitingPod := fh.GetWaitingPod(victim.UID); waitingPod != nil {
>     // reject it
> } else {
>     // delete the victim
> }
> ```
> 
> Feel free to raise a PR.
> 
> /assign @cwdsuzhou

Yes, I will open a PR to do this
