### ISSUE TITLE
Detach kubeadm from k8s.io/kubernetes to k8s.io/kubeadm

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/kubernetes#100239]
#### What would you like to be added:
All implementations of kubeadm are in [cmd/kubeadm](https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm).
My idea is to extract it to k8s.io/kubeadm so that other gomod projects can easily reference it.
#### Why is this needed:
As far as I know, [ projectcalico/node repeatedly defines ](https://github.com/projectcalico/node/blob/master/pkg/startup/startup.go#L69)the configuration item [KubeadmConfigConfigMap  of kubeadm](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L247), so I remembered the suggestion of [ k8s.io/kubectl](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl). 
But I don’t know if other projects use kubeadm's implementation or configuration items. Does this pr have enough meaning?

**Comment by neolit123** [comment]
already tracked here:
https://github.com/kubernetes/kubernetes/issues/78534

add comments to that issue if you want.

/close
/sig cluster-lifecycle
/area kubeadm
