### ISSUE TITLE
Move images in gcr.io/gke-release to community owned repositories?

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100274]
Looks like we have 2 images:
- gcr.io/gke-release/nvidia-gpu-device-plugin
- gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver

Here:
https://cs.k8s.io/?q=gcr.io%2Fgke-release&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

Should these be moved to community owned repositories? Are there already there and we just need to fix up the locations?

**Comment by cpanato** [comment]
@dims 
for `gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver` there are some PRs in progress to move the registry:
 - https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/724
 - https://github.com/kubernetes/test-infra/pull/21374
 
 and requested to @spiffxp to copy the exiting image to the new community registry.

for `gcr.io/gke-release/nvidia-gpu-device-plugin` I will work on that next. :)

**Comment by dims** [comment]
thanks @cpanato !

**Comment by cpanato** [comment]
discovered that the `gcp-compute-persistent-disk-csi-driver` is available here: `k8s.gcr.io/nvidia-gpu-device-plugin@sha256:0842734032018be107fa2490c98156992911e3e1f2a21e059ff0105b07dd8e9e` will open a PR to update to use this image

**Comment by BenTheElder** [comment]
Where are the sources for these images? Will we be able to continue to publish new images? cc @ruiwen-zhao xref: https://github.com/kubernetes/kubernetes/pull/96276

None of these images seem to have version tags?

If we're not actually publishing these, then we should probably either:
- consume them from somewhere that is publishing them and maintaining them
- set up mirroring them

**Comment by BenTheElder** [comment]
copying from https://github.com/kubernetes/kubernetes/pull/100294#issuecomment-800532513

Also as much as I would like to see this sorted out I don't think https://github.com/kubernetes/k8s.io/issues/1525 or https://github.com/kubernetes/kubernetes/issues/100274 counts as a test-only issue to be resolving in this part of the release cycle. This seems like something we should do early in 1.22 and focus on actual test coverage improvements and functionality fixes right now.

**Comment by BenTheElder** [comment]
Was CSI moved?

**Comment by cpanato** [comment]
> Was CSI moved?

yes Ben (gcr.io/gke-release/gcp-compute-persistent-disk-csi-driver was moved)

**Comment by cpanato** [comment]
gcp-compute-persistent-disk-csi-driver is moved

and nvidia-gpu-device-plugin have a good slack 🧵  https://kubernetes.slack.com/archives/C0BP8PW9G/p1623920550355600 and the image was move in k/k with this PR https://github.com/kubernetes/kubernetes/pull/100294

I think we can close this issue. 
will close, if I did wrong we can reopen

/close
