### ISSUE TITLE
WaitForAttachAndMount might delay pod terminating.

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#100219]
From comment https://github.com/kubernetes/kubernetes/issues/100047#issuecomment-796980046

syncPod is waiting for volumes to finish mounting. before calling WaitForAttachAndMount, it checks if the pod is terminated before entering. However, if the pod is terminated after that check, then we are stuck in in WaitForAttachAndMount until it times out, a little over 2 minutes.

The call probably needs to be enhanced to return early if the pod is deleted. It doesn't seem like pod deletion is captured as a pod error. In fact, we seem to pop all errors if the pod is deleted.

**Comment by jingxu97** [comment]
cc @Random-Liu

**Comment by jingxu97** [comment]
found similar issue and PR to address it https://github.com/kubernetes/kubernetes/issues/49663

**Comment by jingxu97** [comment]
In syncPod workflow, there are three places checking whether pod is terminated 

1. if pod is not runnable, or deletionTimeStamp is set, or pod is failed, trigger killPod() and return
 [code link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1590)

2. if pod is not termniated (!kl.podIsTerminated(pod) ), do not create cgroup etc.
 [code link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1617) 

3. if pod is not termniated (!kl.podIsTerminated(pod) ), do not wait for volume mounts
[code link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1698)

So in case during one particular syncPod, two cases

- pod deletion timestamp is not set yet, then pod is considered not terminated, syncPod will waitForAttachMount(). If at this point, volume is actually unmounted (or will not mount at all because volume is already removed from desired state)
- pod deletion timestamp is set already, syncPod will return immediately at first check shown above. 

So my thought is #49724 is actually does not help on problem #49663. Two possible proposals here to help this
1. reduce waitForAttachandMount timeout (e.g., 2mins-1min). Concern is not sure how it will affect performance for normal pod startup
2. waitForAttachandMount only checks actual state, it is possible to also check desired state. If the volume is no longer in desired state, should stop and return immediately. 

@msau42 @Random-Liu, any thoughts?

**Comment by msau42** [comment]
I prefer option 2 so that it exits the wait faster in error conditions and doesn't impact the normal case.

**Comment by jingxu97** [comment]
cc @mauriciopoppe

**Comment by jingxu97** [comment]
now I tried to implement this logic and realized for option 2, we cannot differentiate whether pod volume is removed from desired state or it is not yet added to the state. In many cases, it might not yet added to desired state, then we return error immediately, which might affect the performance..

**Comment by msau42** [comment]
if it's not added yet to desired state, then we will return error from the call. Are you considered that syncPod will take too long to retry?

**Comment by jingxu97** [comment]
> if it's not added yet to desired state, then we will return error from the call. Are you concerned that syncPod will take too long to retry?

right. I remember if there is no pod update event happened, pod worker sync up pod after a period of time.

**Comment by msau42** [comment]
Is there some other state we can check? To make it this far in `syncPod`, are there any assumptions we can make?

**Comment by smarterclayton** [comment]
In syncPod you can't assume anything, but you can call the pod worker to check Should*() methods (introduced in 1.21).  Calls to that method are cheap (lock per pod)

**Comment by smarterclayton** [comment]
Context cancellation of sync should address most of the issues here, especially by adding tests that ensure that every wait loop is connected to the overall sync context, which is cancelled when a pod is deleted.  I will create a tracking issue.

**Comment by smarterclayton** [comment]
#113606 is the tracking issue

**Comment by smarterclayton** [comment]
I *think* this is fixed now with #117412 in 1.28.
