### ISSUE TITLE
Prevent addition of new flags to kubelet

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#100336]
#### What would you like to be added:
- Add a test to prevent adding of new flags to kubelet. It can verify the current number of flags and fail when a new flag has been added. Test can be modified if there is a valid reason to add flag instead of config.
- Update the SIG-Node developer doc to give preference to addition of config than flag.

#### Why is this needed:
There has been an ongoing effort to migrate kubelet flags to config. We do not want to add any new flags to kubelet until it is very necessary. It is easy to be missed during PR reviews a test case here would help to prevent future regressions.

/sig node
see issue https://github.com/kubernetes/kubernetes/issues/86843

**Comment by neolit123** [comment]
like i commented on https://github.com/kubernetes/kubernetes/issues/86843 it's not clear whether SIG Node has agreed to the concept of migrating to config and to stop adding flags entirely.

if the SIG has agreed to that, adding such a blocking "flag-check" seems reasonable, but i wouldn't say necessary due to the relatively small number of approvers for the kubelet who can be aware of this problem and gating on changes adding new flags.

**Comment by adisky** [comment]
@neolit123 It is just about adding simple unit test. We are not completely enforcing here to add new flags that is the SIG decision, Its just to notice author/reviewer that if it is possible add it to config.

**Comment by neolit123** [comment]
might be a good idea to open a mailing list discussion to give a heads up on this change in advance:
https://github.com/kubernetes/community/tree/master/sig-node#contact

**Comment by BenTheElder** [comment]
This seems like the sort of thing that human approval covers. Whoever can approve the kubelet binary sources can approve adding flags.

A comment / docs seems sufficient for providing "just a notice" and takes zero maintenance / zero runtime cost.

**Comment by matthyx** [comment]
It's been agreed to stop adding new flags in SIG Node meeting:
https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#heading=h.qmsvtr8128ga

/triage accepted
/assign @adisky
