### ISSUE TITLE
Fixes for Deprecation of io/ioutil (in Go 1.16)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100367]
Please see https://golang.org/doc/go1.16#ioutil

We have a lot of references to `ioutil` which we need to migrate to newer package(s) mentioned in the url above:
https://cs.k8s.io/?q=io%2Fioutil&i=nope&files=.*%5C.go&excludeFiles=&repos=kubernetes/kubernetes

We also need some verify scripts to ensure we don't add back this package

/area code-organization

**Comment by dims** [comment]
/sig architecture

(seems like this cuts across everything!)

**Comment by harshanarayana** [comment]
@dims  mind if I take a look at this ?

/assign @harshanarayana

**Comment by dims** [comment]
Ack @liggitt !

**Comment by harshanarayana** [comment]
@dims  For the script to verify the and ensure we don't add this back again, can I modify the existing `importverifier` toolchain to add a new `disallowedImports` field  with similar behavior support as that of `allowedImports` ?

**Comment by liggitt** [comment]
ioutil is extremely widely used, and is not actually a problem to continue using... make sure the importverifier doesn't complain if we depend on it transitively via a vendored dependency

**Comment by harshanarayana** [comment]
@liggitt Sure. I will keep that in mind.  I will enable this as a soft warning behavior if that is all right with everyone so that we can warn them but not fail the check right-away. Once we decide to enforce it, we can switch the config to fail the checks.

**Comment by dims** [comment]
@liggitt ack on the warn/verify we can deal with that later (i'll check on possibilities). let's focus this issue to just the bulk replace

**Comment by harshanarayana** [comment]
Ack.  Thanks @dims  @liggitt

**Comment by BenTheElder** [comment]
Most of the methods in ioutil have relatively simple implementations that seem stable, doubly so if it's deprecated 🙃
If go isn't planning to remove this package any time soon I'm also not sure it's worth the cost of forcing library consumers to use go1.16+?

**Comment by palnabarun** [comment]
/remove-lifecycle stale
/priority important-longterm
(based on https://github.com/kubernetes/kubernetes/issues/100367#issuecomment-801837105. Please feel to correct, if otherwise)

**Comment by mythi** [comment]
@dims looks like people are still submitting PRs on this topic and they are not getting reviewed. From Go perspective there's no update since the 1.16 announcement (AFAIK). Should we revisit this goal?
