### ISSUE TITLE
Deprecate/replace apt.kubernetes.io and yum.k8s.io (or) move them to community owned repository

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100348]
- both `apt.kubernetes.io` and `yum.k8s.io` are redirects to google owned/operated package repository:
https://cs.k8s.io/?q=(yum%7Capt).kubernetes.io&i=nope&files=&excludeFiles=&repos=kubernetes/k8s.io
- deb/rpm packages are signed by folks in GOOG and uploaded to the repository (thanks @BenTheElder and others who take care of this!!!)

Choices are:
- Get a community owned key and setup our own repository
- Deprecate these repos in favor of something else

/sig release

**Comment by justaugustus** [comment]
This is a duplicate of https://github.com/kubernetes/release/issues/281, which is part of the over-arching Artifact Management epic here: https://github.com/kubernetes/sig-release/issues/1372.

Further, there is a project board capturing some of these asks here: https://github.com/orgs/kubernetes/projects/48
Work will begin in v1.22.

/close

**Comment by dims** [comment]
@justaugustus thanks! i wanted to be sure that we consider this and work through stuff way before we think of brand new use cases / scenarios.

**Comment by justaugustus** [comment]
@dims -- Thanks. Please comment on the original issue! :)
