### ISSUE TITLE
kubelet: provide feature to config CNI through config vs picking it up on lexicographic orde

### ISSUE THREAD

**Issue by medyagh** [kubernetes/kubernetes#100309]
in minikube we noticed that during kubeadm init, kuberentes picks up the first alphabetical CNI that could cause some unexpected issues with choosing CNIs. (such as choosing the wrong CNI when there are other CNI files availbe in the `/etc/cni/net.d`

based on this comment from @afbjorklund https://github.com/kubernetes/minikube/issues/10788#issuecomment-797289498

```
If there are multiple CNI configuration files in the directory, the kubelet
uses the configuration file that comes first by name in lexicographic order.
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni
```

would it be possible to have a way to configure the CNI in the config file explicitly ?

as @neolit123 noted originally https://github.com/kubernetes/kubeadm/issues/2408
> kubeadm allows the users to configure the kubelet via KubeletConfiguration.
> AFAIK the field to control this CNI related behavior is missing there, so that is a kubelet issue.

Moved this issue from  https://github.com/kubernetes/kubelet/issues/25 for better triage visibility.

**Comment by BenTheElder** [comment]
These are picked up by the container runtime when not dockershim and dockershim is generally deprecated / not taking new features.

A CRI implementation could choose to support this, but, it would break the expectations of pretty much everything in the space.

CNI is generally under the purview of SIG network
/sig network

**Comment by BenTheElder** [comment]
Lexicographic config files is also how systemd and other system level configuration works when there is not only a single file. I don't think it is expected that config files would be in this directory unless they are intended to be used.

**Comment by neolit123** [comment]
> such as choosing the wrong CNI when there are other CNI files availbe in the /etc/cni/net.d

i also remembered that the there could be issues if there are conflicting CNI configs in that folder.
maybe the recommendation is to just have a single CNI config there at all times.

**Comment by BenTheElder** [comment]
> some distro packages can install to that folder (AFAIK podman does that)

This is arguably a bug in podman's packaging. It's not expected to have multiple CNI installed. I would not install this on a Kubernetes node.

> the folder must be spec-ed to be either install time or run time config.

It's runtime. The config has live reloading in containerd at least.


In either case such a feature would be at the container runtime level. containerd already supports configuring an alternative directory for both CNI configuration and binaries.

**Comment by dcbw** [comment]
Giving kubelet a specific CNI config to pick up prevents the (perhaps uncommon) practice of changing network plugins in clusters from a default to another plugin, which I know people do.

And if/until Kube grows some kind of multi-network awareness, this is the job of the runtime itself (crio, containerd, docker) these days, not kubelet.

**Comment by medyagh** [comment]
how about allow it is an optional config for kubelet and if user doesn't specify it, then it fall back to lexicographic order ? that way if users really wants to config it with a specific CNI why not allow them to set it explicitly

**Comment by thockin** [comment]
It's not clear to me why this is important enough to carry yet another config option for.  Aside from that, this is actually the purvey of each CRI impl (CNI is an implementation detail), so I don't think there's anything we want to do here.  Please feel free to reopen if there's new information.
