### ISSUE TITLE
Metrics discrepancy for Memory in metric-server and top command.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#100327]
#### What happened:
We are monitoring pods running in Kubernetes using metric server and analyzing the same in grafana.
As could see, using kubectl top command, seeing mem and cpu info in Mebibyte and Millicore respectively. show in below.
kubectl top pods test-0
NAME CPU(cores) MEMORY(bytes)
test-0 3m 335Mi

Prometheus reading the metrics, and updating the cpu and memory in nanocore and kebibytes respectively. show in below.
kube_metrics_server_pods_mem{pod_name="test-0",pod_namespace="default"} 343748

in kubernetes machine

kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/test-0"
{"kind":"PodMetrics","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"name":"test-0","namespace":"default","selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/test-0","creationTimestamp":"2021-03-17T12:02:21Z"},"timestamp":"2021-03-17T12:01:51Z","window":"30s","containers":[{"name":"test","usage":{"cpu":"2731514n","memory":"343748Ki"}}]}

But if we convert mebibytes to kebibytes i.e. 335mi to Ki, value will be 343040, then how the value "memory":"343748Ki" is calculated?

#### What you expected to happen:
Values should be in proper units.
#### How to reproduce it (as minimally and precisely as possible):
install metric-server and compare the output of top and get --raw command.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.16.9
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):  
`PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`
- Kernel (e.g. `uname -a`):  Linux localhost 4.14.151-OpenNetworkLinux #1 SMP Fri Mar 5 08:52:32 UTC 2021 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
please open this issue in the the metrics-server repository.
if the maintainers explain that this is a core k8s bug - re-open this ticket.

thanks
/close
/sig insrumentation
