### ISSUE TITLE
How to monitor CPU and MEM usage of pods running in K8S and push to monitor application

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#100390]
I want to monitor CPU and MEM usage of pods and fed the metrics to monitor application, specially prometheus.
does there any application for it or apis?

**Comment by neolit123** [comment]
hi, prometheus can be used for that:
https://itnext.io/k8s-monitor-pod-cpu-and-memory-usage-with-prometheus-28eec6d84729

please use the support forums for more questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
other user can help you there.

/kind support
/close
