### ISSUE TITLE
Kubernetes Pods create/Status unsure (kubelet) - dbus: connection closed by user

### ISSUE THREAD

**Issue by srinathmatti** [kubernetes/kubernetes#100328]
#### What happened:
We have a random pod having issues where its status is not available to K8s (Api server) and when we login to assigned node we can see it via ```docker ps ``` in some cases. As of now the solution is we restart kubelet on the node where the pod is assigned 

```
15m         Normal    Scheduled                  pod/catalog-server-5f5cfdffd9-7b8pw    Successfully assigned apps/catalog-server-5f5cfdffd9-7b8pw to node5
4s          Warning   FailedCreatePodContainer   pod/catalog-server-5f5cfdffd9-7b8pw    unable to ensure pod container exists: failed to create container for [kubepods burstable pod3b7a3b5d-7685-43cb-a0ab-5b0646ba07d7] : dbus: connection closed by user
```

```  
Warning  FailedCreatePodContainer  4m40s (x4642 over 16h)  kubelet  unable to ensure pod container exists: failed to create container for [kubepods besteffort poda3e18933-f1c9-4c86-a752-e355e632ef1c] : dbus: connection closed by user
```

#### What you expected to happen: 
This is not happening in our other cluster which have the same containers but older version of kubernetes ranging from 1.14 to 1.17 which were created using kubeadm.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`): 5.4.91-1.el7.elrepo.x86_64
- Install tools: kubespray ( 2.15.0)
- Network plugin and version (if this is a network-related bug): cilium 
- Others:

**Comment by srinathmatti** [comment]
let me know what logs is needed ? I can provide it .

**Comment by wzshiming** [comment]
https://github.com/kubernetes/kubernetes/blob/a6a3bf2eb4a0b7e9f86f991ffc24b72beafce2f4/vendor/github.com/coreos/go-systemd/v22/dbus/dbus.go#L158-L173
I probably positioned it to happen on L171, but I don’t understand why it happened. do you have a way to reproduce it? or provide the log of kubelet, let me locate the specific reason.

**Comment by vsxen** [comment]
dbus service had exited or restart?


you can restart kubelet to resolve it.


https://bugzilla.redhat.com/show_bug.cgi?id=1634092

**Comment by wzshiming** [comment]
I restarted dbus and this happened.

**Comment by vsxen** [comment]
by the way, I konw it because had seen a issue about `systemd & docker` in my cluster

when I run `docker run -it --rm ubuntu bash` it will  hang,
when I run `docker run -itd nginx`, then docker ps  will show `Created`

systemd-logind  
```
Jun  4 10:42:01 k8s-node145 systemd-logind: Failed to start session scope session-413369.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:43:01 k8s-node145 systemd-logind: Failed to start session scope session-413370.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:44:01 k8s-node145 systemd-logind: Failed to start session scope session-413371.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:45:01 k8s-node145 systemd-logind: Failed to start session scope session-413372.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:45:01 k8s-node145 systemd-logind: Failed to start session scope session-413373.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:46:01 k8s-node145 systemd-logind: Failed to start session scope session-413374.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:47:01 k8s-node145 systemd-logind: Failed to start session scope session-413375.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:48:01 k8s-node145 systemd-logind: Failed to start session scope session-413376.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:49:01 k8s-node145 systemd-logind: Failed to start session scope session-413377.scope: The maximum number of pending replies per connection has been reached
Jun  4 10:50:01 k8s-node145 systemd-logind: Failed to start session scope session-413378.scope: The maximum number of pending replies per connection has been reached
```

I search with google and change `max_replies_per_connection ` in `/etc/dbus-1/session.conf` file. (see mail list)

Also  I find  polkit & dbus has some error,even I can't restart it.
(Authorization not available. Check if polkit service is running or see debug message for more information.)

Ref
mail list 
https://lists.freedesktop.org/archives/dbus/2016-June/016948.html
a chinese blog
https://my.oschina.net/u/4362933/blog/3512512

**Comment by wzshiming** [comment]
This seems to be a issue with too many dbus connections, which is different from this issue

**Comment by srinathmatti** [comment]
> you can restart kubelet to resolve it.

I know we can restart kubelet which will fix the issue but for time being, the environment where we are running this cluster will go in lockdown and we would not will be able to access / fix things

**Comment by wzshiming** [comment]
The part affected by dbus
- [ ] runc https://github.com/opencontainers/runc/pull/2862
- [ ] graceful node shutdown feature

**Comment by mmerrill3** [comment]
Hi, is there a version of kubernetes that we should be using where the dbus singleton was not getting the close method called on it?  We see this issue with k8s 1.20.5 and 1.20.2.

We previously didn't see this error on k8s 1.19.6.

**Comment by wzshiming** [comment]
@mmerrill3 
Currently waiting for the upstream dependency to release a new version. all versions should have the same error. Maybe you can upgrade godbus to v5.0.4 separately

**Comment by vsxen** [comment]
https://github.com/opencontainers/runc/issues/1959
https://bugs.centos.org/view.php?id=15695

**Comment by arianvp** [comment]
Did this get fixed in any released kubernetes version? I notice restarting dbus on 1.23 leaves kubelet in a broken state like described here

**Comment by wzshiming** [comment]
``` console
# systemd-inhibit --list
     Who: kubelet (UID 0/root, PID 27974/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
# systemctl restart dbus
# systemd-inhibit --list
Failed to list inhibitors: Failed to activate service 'org.freedesktop.login1': timed out
# systemctl restart systemd-logind
# systemd-inhibit --list
     Who: kubelet (UID 0/root, PID 27974/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```

I have tested the graceful shutdown part of the Dbus reconnection is fixed.

However, this bug still seems to exist when creating Pod. It seems that the runc or go-systemd parts are not fixed with godbus/dbus#files

/reopen

**Comment by wzshiming** [comment]
https://github.com/opencontainers/runc/blob/c83abc503de7e8b3017276e92e7510064eee02a8/libcontainer/cgroups/systemd/dbus.go#L39

It looks like this needs to be checked to see if it's still connected

**Comment by wzshiming** [comment]
https://github.com/coreos/go-systemd/pull/393

**Comment by kolyshkin** [comment]
I _think_ this should be fixed by https://github.com/kubernetes/kubernetes/pull/110496
