### ISSUE TITLE
Container resource limit does not work

### ISSUE THREAD

**Issue by sunnoy** [kubernetes/kubernetes#100365]
The set memory limit is 4g ，But using more than 6g

![image](https://user-images.githubusercontent.com/19342276/111603147-04b83480-880f-11eb-95ff-b824df02f80b.png)

![image](https://user-images.githubusercontent.com/19342276/111603217-17cb0480-880f-11eb-9654-65ff016a9c75.png)

**Comment by wzshiming** [comment]
Do you have a way to reproduce it?

**Comment by sunnoy** [comment]
cup is easy to reproduce, memory is not easy to reproduce

env
centos 7.6
k8s 1.18

**Comment by wgahnagl** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/kind support
/close
