### ISSUE TITLE
[1.22] Revert Revert "Promote SizeMemoryBackedVolumeSizing to beta"

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100371]
When master opens up for `v1.22`, we need to add this back in:
https://github.com/kubernetes/kubernetes/pull/100346

/sig node

**Comment by wilsonehusin** [comment]
note to self / 1.21 and 1.22 release notes team -- let's make sure the PR body on the original PR is copied over to the new PR. `krel` will think that the old release note and documentation has been covered in 1.21, but we will (I will update this comment with link) manually override it to not show up in 1.21 release notes.
