### ISSUE TITLE
Add an e2e test for UNC paths windows when using gMSA

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#100388]
#### What happened:
There was a regression in containerd that required a fix for gmsa working with UNC paths. See the fix at https://github.com/kubernetes-sigs/windows-gmsa/issues/30#event-4479102851

#### What you expected to happen:
We should have a test that validates this functionality.  

#### Anything else we need to know?:

See https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/gmsa_full.go for set up and place to add this test.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig windows
/triage accepted
/priority important-long-term
/help

**Comment by jsturtevant** [comment]
@Kappie37 if you have questions feel free to reachout on slack in sig-windows

**Comment by Kappie37** [comment]
@jsturtevant Will do, thanks!

**Comment by marosset** [comment]
I have thought about this a bit and think it might be easiest to just expose a share on the domain controller.
This does push more requirements into the configuration that needs to happen outside of the tests but it will make the tests a lot cleaner IMO.
