### ISSUE TITLE
Removing --root-ca-file from kube-controller-manager args does not update ServiceAccount token Secrets

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#100343]
#### What happened:

I removed the `--root-ca-file` from my kube-controller-manager command line arguments, but the ServiceAccount token (`type: kubernetes.io/service-account-token`) Secrets did not receive any updates to their `ca.crt` keys.

#### What you expected to happen:

I expected that the `ca.crt` key would be removed, since it is implied by the ["accessing the API from a Pod"](https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod) docs that that file will not be there if it's not "available" and the [kube-controller-manager command line reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) docs imply that if the setting is not set, it will not include the CA in the ServiceAccount token's secret.

#### How to reproduce it (as minimally and precisely as possible):

1. Start up a cluster where kube-controller-manager has a `--root-ca-file` flag set to a correct bundle for the apiserver's server cert.
2. Create a ServiceAccount token Secret (e.g. by creating a ServiceAccount)
3. Observe that the Secret has a key called `ca.crt`
4. Restart kube-controller-manager without the `--root-ca-file` flag
5. Observe that the Secret still has a key called `ca.crt` and its value is unchanged

#### Anything else we need to know?:

I was able to confirm that if I keep the `--root-ca-file` flag but change it to some other file that's still valid for the apiserver's server cert, just contains other stuff in it, the Secrets _do_ update with a new value for `ca.crt`.

I looked in logs for something that would help me figure out what was wrong, and I saw this, but it appeared both when I removed the `--root-ca-file` flag and when I kept it but changed the value for it, so I guess it's not related?

```
controllermanager.go:518] Starting "root-ca-cert-publisher"
controllermanager.go:525] Skipping "root-ca-cert-publisher"
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18.15
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 9 (stretch)
- Kernel (e.g. `uname -a`): `Linux ip-10-47-23-237 5.4.38 #1~bt9+1 SMP Tue May 12 21:16:19 UTC 2020 x86_64 GNU/Linux` (I think my company patched this kernel but I don't think it's relevant to this issue)
- Install tools: the hard way :)
- Network plugin and version (if this is a network-related bug): n/a
- Others:

**Comment by SataQiu** [comment]
It looks like `rootCA` is always not empty. If `--root-ca-file` was not set, the controller will use the CA embedded in kubeconfig.

https://github.com/kubernetes/kubernetes/blob/30a261d97c65f3e1e46a93eb368376f68935a057/cmd/kube-controller-manager/app/controllermanager.go#L602-L623

https://github.com/kubernetes/kubernetes/blob/30a261d97c65f3e1e46a93eb368376f68935a057/cmd/kube-controller-manager/app/controllermanager.go#L649-L651

**Comment by SataQiu** [comment]
@2rs2ts Is the CA in kubeconfig used by the `kube-controller-manager` the same as the CA specified by the `root-ca-file` flag?

**Comment by 2rs2ts** [comment]
@SataQiu we weren't setting it in the kubeconfig explicitly, but I was originally using `--root-ca-file=/etc/ssl/certs/ca-certificates.crt`, so if the default behavior for the kubeconfig is to use `/etc/ssl/certs/ca-certificates.crt` if the CA isn't specified, then that makes a certain amount of sense. If that's true then I think the docs are just worded confusingly–what do you think?

**Comment by enj** [comment]
Seems like the docs could be updated to state that when a `--root-ca-file` is not given, the CA bundle for the current context in `--kubeconfig` will be used instead if specified.
