### ISSUE TITLE
Traffic Policy and Topology Aware Routing should not be exclusive

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#100313]
#### What happened:
I believe the [code is currently written](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L30) in a way so that only one of the following will be implemented (in order):
- ExternalTrafficPolicy
- InternalTrafficPolicy
- Topology Hints

#### What you expected to happen:
Configurations like `externalTrafficPolicy=Local` + `internalTrafficPolicy=Local` should be valid. Similarly, it should be able to enable topology if only one of `externalTrafficPolicy` or `internalTrafficPolicy` are set to local.

(This originated from https://github.com/kubernetes/website/pull/27032#discussion_r595399116).

/sig network
/cc @maplain @andrewsykim @thockin

**Comment by thockin** [comment]
Do we need to get this into 1.21 ?

**Comment by robscott** [comment]
I'm not sure. It would be nice, but I don't think it's necessarily a release blocker. I'm happy to make a PR if we think it could make it in as a bug fix, but I think the diff could get relatively large.

**Comment by andrewsykim** [comment]
@robscott this makes a lot of sense to do, is this just waiting for someone to implement?

**Comment by robscott** [comment]
@andrewsykim thanks for following up on this! This just needs someone to take it on.

**Comment by andrewsykim** [comment]
Thanks Rob! Happy to take a look (or find someone who can)

**Comment by nicolehanjing** [comment]
I can take a look at this :)

**Comment by andrewsykim** [comment]
Thanks @nicolehanjing 

/assign @nicolehanjing

**Comment by nicolehanjing** [comment]
I think my current blocker is on how to determine whether the traffic is internal or external
Please let me know if you have any pointers/suggestions. Thanks!
cc @robscott @andrewsykim

**Comment by robscott** [comment]
@nicolehanjing If I'm remembering this correctly, it's more complicated than it seems on the surface. The fundamental problem here is that topology endpoints may not always include node-local endpoints. To illustrate that, consider the following example:

- 3 equal zones - A, B, and C. 
- 2 pods deployed in zone A, 1 pod deployed in zone B
- Hints will allocate one of the "extra" pods in zone A to cover zone C

That means that "extra" zone A Pod that has been allocated to zone C will not be part of the filtered endpoints for the Node it's running on. 

To further complicate things, External Traffic Policy and Internal Traffic Policy are actually somewhat different if I understand correctly. It appears that Internal Traffic Policy affects all requests that reach a Node for the specified Service. At least that's my interpretation of the [implementation here](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L34-L36) - @maplain can correct me if I got this wrong. If my interpretation is correct, that means that there will never be any overlap between Internal Traffic Policy and Topology Hints - Internal Traffic Policy should always get priority. One could argue that we could fall back to Topology if no local endpoints were available, but I don't think we have that behavior specified anywhere.

On the other hand External Traffic Policy is [implemented in each proxier](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1397-L1403) where we can have separate config for internal and external requests. Topology based filtering was [implemented in the code shared by each proxier](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L26-L43) - the same place as the Internal Traffic Policy implementation. 

The problem we have is that if we filter endpoints based on topology before they even reach the proxier implementations, there's a chance that we'll have filtered out some local endpoints. It seems like our least bad option is to make topology filtering include endpoints if a hint matches or if it is node local, and then filter them further by topology hints within each proxier. Does that sound reasonable?

/cc @andrewsykim @thockin

**Comment by andrewsykim** [comment]
/milestone v1.23 

We probably want to address this before we GA the interna ltraffic policy feature

**Comment by thockin** [comment]
+1

**Comment by danwinship** [comment]
> To further complicate things, External Traffic Policy and Internal Traffic Policy are actually somewhat different if I understand correctly. It appears that Internal Traffic Policy affects all requests that reach a Node for the specified Service. At least that's my interpretation of the [implementation here](https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/topology.go#L34-L36)

That implementation is wrong according to [the KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy):

> This field will be independent from externalTrafficPolicy. In other words, internalTrafficPolicy only applies to traffic originating from internal sources.

**Comment by andrewsykim** [comment]
FYI @danwinship I don't think myself or @nicolehanjing is going to be able to work on this any time soon, please feel free to take it if you can :)

**Comment by ritpanjw** [comment]
Hi @andrewsykim , this is bug triage shadow here 👋
I'd like to check what's the status. The code freeze is starting tomorrow and since PR is not merged
As the PR is tagged for 1.23, is it still planned for this release?

**Comment by liggitt** [comment]
@thockin commented +1 about fixing this before 1.23 in https://github.com/kubernetes/kubernetes/issues/100313#issuecomment-915651654, but https://github.com/kubernetes/kubernetes/pull/106497 does not appear to be making progress.

1.23.0 rc 1 was just released... what are the implications if this issue is not fixed in 1.23.0?

**Comment by robscott** [comment]
Sorry, didn't do a great job of updating this. @danwinship has a PR that will fix this issue, but after some [discussion in Slack](https://kubernetes.slack.com/archives/C09QYUH5W/p1636995039151500), we determined that this should not be blocking for topology beta. Sorry, that thread falls off before a clear conclusion, but I know there was at least one more follow up chat thread continuing that discussion.

**Comment by liggitt** [comment]
Thanks for updating, moved to 1.24

**Comment by ritpanjw** [comment]
Hi 👋 . Checking in from bug triage for 1.24. Should we continue to track progress on this issue for 1.24 release? If yes, would you please update the priority field for us to track it better?

**Comment by andrewsykim** [comment]
I believe this will be fixed in https://github.com/kubernetes/kubernetes/pull/106497

**Comment by ritpanjw** [comment]
@andrewsykim should we close this PR then ?

**Comment by ritpanjw** [comment]
@andrewsykim if it is being fixed in https://github.com/kubernetes/kubernetes/pull/106497, can we close this PR ?

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/pull/106497 is still open
