### ISSUE TITLE
audit on configmap changes

### ISSUE THREAD

**Issue by arek-jamanskiy** [kubernetes/kubernetes#100372]
#### What would you like to be added:
configmap needs to have not only creationTimestamp, but also the last patching timestamp.
Better to have the ability to get all the history of the changes together with the historical values.

#### Why is this needed:
Such feature will help to investigate possible incidents, it also may allow rollbacks.

Now there is no possibility to investigate any incidents connected to the changes on the configmaps.
You never know which particular configmap value certain pod was started with, 
when configmap was changed last time and what particularly was changed.

**Comment by deads2k** [comment]
the audit log allows tracking RequestResponse bodies.  See https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ for details.

The kube-api does not allow getting historical revisions of particular resources.  Such a change would need to go through a KEP process in https://github.com/kubernetes/enhancements

/close
