### ISSUE TITLE
debian10 containerd1.4.4 Unable to adapt k8s 1.20.4

### ISSUE THREAD

**Issue by ganlei333** [kubernetes/kubernetes#100389]
operating system: debian10
k8s:1.20.4
containerd:1.4.4
Binary deployment

Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: failed to write "1" to "/sys/fs/cgroup/memory/system.slice/containerd.service/kubepods-burstable-pod7a875b5c_4d3c_4345_ac0f_5c847d8d7129.slice:cri-containerd:webapp/memory.limit_in_bytes": write /sys/fs/cgroup/memory/system.slice/containerd.service/kubepods-burstable-pod7a875b5c_4d3c_4345_ac0f_5c847d8d7129.slice:cri-containerd:webapp/memory.limit_in_bytes: device or resource busy: unknown

root@k8s-node-02:# ll /sys/fs/cgroup/memory/system.slice/containerd.service/kubepods-burstable-pod7a875b5c_4d3c_4345_ac0f_5c847d8d7129.slice:cri-containerd:ee05f876e981d258209f91f25f139f7abc13a0246a5f343298572602fea8c7bb/
总用量 0
-rw-r--r-- 1 root root 0 3月 18 17:51 cgroup.clone_children
--w--w--w- 1 root root 0 3月 18 16:56 cgroup.event_control
-rw-r--r-- 1 root root 0 3月 18 16:56 cgroup.procs
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.failcnt
--w------- 1 root root 0 3月 18 17:51 memory.force_empty
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.failcnt
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.limit_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.max_usage_in_bytes
-r--r--r-- 1 root root 0 3月 18 17:51 memory.kmem.slabinfo
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.tcp.failcnt
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.tcp.limit_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.kmem.tcp.max_usage_in_bytes
-r--r--r-- 1 root root 0 3月 18 17:51 memory.kmem.tcp.usage_in_bytes
-r--r--r-- 1 root root 0 3月 18 17:51 memory.kmem.usage_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.limit_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.max_usage_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.move_charge_at_immigrate
-r--r--r-- 1 root root 0 3月 18 17:51 memory.numa_stat
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.oom_control
---------- 1 root root 0 3月 18 17:51 memory.pressure_level
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.soft_limit_in_bytes
-r--r--r-- 1 root root 0 3月 18 17:51 memory.stat
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.swappiness
-r--r--r-- 1 root root 0 3月 18 17:51 memory.usage_in_bytes
-rw-r--r-- 1 root root 0 3月 18 17:51 memory.use_hierarchy
-rw-r--r-- 1 root root 0 3月 18 17:51 notify_on_release
-rw-r--r-- 1 root root 0 3月 18 17:51 tasks
root@k8s-node-02:#

Demand path：cri-containerd:webapp
Actual path :cri-containerd:ee05f876e981d258209f91f25f139f7abc13a0246a5f343298572602fea8c7bb

**Comment by Iceber** [comment]
https://github.com/opencontainers/runc/pull/2812 improves runc error reporting in cases where memory limit is set too low.

**Comment by haircommander** [comment]
I agree, I believe this is fixed as of runc-1.0.0-rc94. Please reopen if you disagree
/close
