### ISSUE TITLE
node(s) didn't match pod affinity/anti-affinity description

### ISSUE THREAD

**Issue by kfirfer** [kubernetes/kubernetes#100400]
From time to time, pods couldn't scheduled on nodes because of affinity/anti-affinity

The event from kubelet example:
```
11s   Warning FailedScheduling pod/nmap     0/20 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 19 node(s) didn't match node selector.
```

Would be better for traceability and troubleshooting if the event will post also the conflicted pods

**Comment by MadhavJivrajani** [comment]
Hi! I'd like to try working on this issue if possible 😄 
/assign
