### ISSUE TITLE
[Failing Test] subPath should unmount if pod is force deleted while kubelet is down (ci-kubernetes-gci-gce-serial)

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100419]
#### Which jobs are failing:
ci-kubernetes-gci-gce-serial

#### Which test(s) are failing:

- [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: blockfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link-bindmounted] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir-link] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: dir] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: gce-localssd-scsi-fs] [Serial] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]
- [sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: tmpfs] [Testpattern: Pre-provisioned PV (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]

There are also variations of this test that are flaking (e.g. `[sig-storage] In-tree Volumes [Driver: gluster] [Testpattern: Inline-volume (default fs)] subPath should unmount if pod is force deleted while kubelet is down [Disruptive][Slow][LinuxOnly]`) but not failing -- please consult TestGrid.

#### Since when has it been failing:
TestGrid says sometime between these commits: https://github.com/kubernetes/kubernetes/compare/2f8a2258f...3d179220a
First failing run at March 17 18:29 PDT

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

#### Reason for failure:
Most of them have an error that looks like this:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/subpath.go:352
Mar 18 04:24:29.705: Expected grep stdout to be empty (i.e. no mount found).
Expected
    <string>: tmpfs on /var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~projected/kube-api-access-fglwr type tmpfs (rw,relatime,size=7384568k)
    tmpfs on /var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~projected/kube-api-access-fglwr type tmpfs (rw,relatime,size=7384568k)
    tmpfs on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~projected/kube-api-access-fglwr type tmpfs (rw,relatime,size=7384568k)
    tmpfs on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~projected/kube-api-access-fglwr type tmpfs (rw,relatime,size=7384568k)
    10.64.1.67:test_vol on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~glusterfs/test-volume type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
    10.64.1.67:test_vol on /var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~glusterfs/test-volume type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
    10.64.1.67:test_vol on /var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~glusterfs/test-volume type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
    10.64.1.67:test_vol on /home/kubernetes/containerized_mounter/rootfs/var/lib/kubelet/pods/c7fc55f1-b3ba-43e1-a7ce-95531e901d9a/volumes/kubernetes.io~glusterfs/test-volume type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)
    
to be empty
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/utils.go:193
```
An example Spyglass link for more details: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1372359492334784512

#### Anything else we need to know:
Triage shows a huge spike for these failures: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=subPath%20should%20unmount%20if%20pod%20is%20force%20deleted%20while%20kubelet%20is%20down

/sig storage cloud-provider
/area provider/gcp
/priority critical-urgent

**Comment by thejoycekung** [comment]
/cc @cpanato 
cc'ing as a followup from Slack

**Comment by msau42** [comment]
/assign  @chrishenzie 
to help investigate

**Comment by thejoycekung** [comment]
https://github.com/kubernetes/test-infra/compare/1acac7628...432c6e7dc
these were the test-infra changes between the passing/failing

**Comment by chrishenzie** [comment]
This is in [the kubelet logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1372706391768174592/artifacts/bootstrap-e2e-minion-group-n2h8/kubelet.log) for one of the failed tests:

```
E0319 03:27:56.378155  123117 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 933 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x41d3380, 0x7381320)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x41d3380, 0x7381320)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).syncStates(0xc0013820c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:411 +0x8ab
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).sync(0xc0013820c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:348 +0x4e
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconciliationLoopFunc.func1()
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:158 +0x118
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0014d3700)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0014d3700, 0x518dc60, 0xc0014fdfb0, 0x4364a01, 0xc0001040c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0014d3700, 0x5f5e100, 0x0, 0x1, 0xc0001040c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0xc0013820c0, 0xc0001040c0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler/reconciler.go:146 +0x5f
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/volumemanager/volume_manager.go:272 +0x1df
```

This nil pointer deference happens on line 411. Looking at that line we have:
https://github.com/kubernetes/kubernetes/blob/1a983bb958ba663e5d86983c55a187fb8c429c51/pkg/kubelet/volumemanager/reconciler/reconciler.go#L410-L412
