### ISSUE TITLE
CSI migration doesn't count inline volumes for attach limit

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#100474]
#### What happened:
From code inspection:
- Non-csi volume predicate [defers to the csi predicate](https://github.com/kubernetes/kubernetes/blob/65bdc9efe6a78e35189e727393c108cbe028c4b5/pkg/scheduler/framework/plugins/nodevolumelimits/non_csi.go#L232) if the plugin is migrated
- csi volume predicate [does not count inline volumes](https://github.com/kubernetes/kubernetes/blob/65bdc9efe6a78e35189e727393c108cbe028c4b5/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L140)

#### What you expected to happen:
csi volume predicate should count inline volumes for migrated plugins. The non-csi volume predicate is going to be removed once all the cloud provider migrations is GA.

#### How to reproduce it (as minimally and precisely as possible):
I haven't tried it, but here's a possible test case:
1. Turn on csi migration
2. Create X inline volumes and assign all Pods to the same node using node selector (not Pod.Spec.NodeName). X is the node limit for the plugin
3. Try to create one more volume and use node selector to the same node. Instead of the scheduler failing, it will get scheduled and fail during attach.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
/assign @Jiawei0227 
cc @jsafrane

**Comment by msau42** [comment]
Also not quite related, but did we implement support for counting the equivalent in-tree and CSI volumes even if migration is off? The KEP [states that as a goal](https://github.com/kubernetes/enhancements/blame/master/keps/sig-storage/554-maximum-volume-count/README.md#L63), but then in the [implementation section](https://github.com/kubernetes/enhancements/blame/master/keps/sig-storage/554-maximum-volume-count/README.md#L188), it doesn't mention how the predicate should behave in that scenario. And in the predicate code, I've only been able to find logic that [doesn't count the volume if migration is off](https://github.com/kubernetes/kubernetes/blob/65bdc9efe6a78e35189e727393c108cbe028c4b5/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L204)

cc  @bertinatto

**Comment by gnufied** [comment]
@dobsonj is going to take a stab at it.

**Comment by Jiawei0227** [comment]
Hey @dobsonj @gnufied  any updates on this?

**Comment by dobsonj** [comment]
@Jiawei0227 I ended up taking some other bugs to start with, so this is on the back burner for the moment. Feel free to take it if you have some free cycles in the mean time.

**Comment by kassarl** [comment]
I'm be interested in taking a look at this issue

**Comment by Jiawei0227** [comment]
Sounds good! Thanks Laila

**Comment by msau42** [comment]
/remove lifecycle/rotten

@kassarl @Jiawei0227 any updates on this?
