### ISSUE TITLE
K8S-1.16.3: Secure port for KCM and Kubescheduler health checks.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#100459]
#### What happened:
Deployed K8S using kubespray, and could see all k8s system pods comes with hostIP.
KCM :-  ports health check (http 10252) as well as secure port(10257).
KUBE-Scheduler: health check(http 10251) as well as secure port(10259).
we could see these are exposed from outside k8s node. After exploring, we found that by default --bind-address is bind with 0.0.0.0(all interface), and they suggest to change to localhost(127.0.0.1) to secure the port or attack to cluster.

After doing require changes, we could see secure ports are unexposed but health check port are still accessible.
0322 06:27:19.071697       1 serving.go:319] Generated self-signed cert in-memory
I0322 06:27:19.795192       1 controllermanager.go:161] Version: v1.16.3
I0322 06:27:19.796265       1 secure_serving.go:123] Serving securely on 127.0.0.1:10257
I0322 06:27:19.797435       1 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252

How can we avoid exposing health check port outside of k8s node. 

#### What you expected to happen:
Port shouldn't be expose.

#### How to reproduce it (as minimally and precisely as possible):
Deploy k8s using kubespray and access the ports from outside the node.
#### Environment:
- Kubernetes version (use `kubectl version`):  Kubernetes v1.16.3
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): 
 
`PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

- Kernel (e.g. `uname -a`):  `Linux localhost 4.14.151-OpenNetworkLinux #1 SMP Fri Mar 5 08:52:32 UTC 2021 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi,

> Kubernetes version (use kubectl version): Kubernetes v1.16.3

this version is no longer in support. support is provided only for 1.18+ at this point..

> we could see these are exposed from outside k8s node. After exploring, we found that by default --bind-address is bind with 0.0.0.0(all interface)

kubespray uses kubeadm. by default newer kubeadm versions use --bind-adress=127.0.0.1 and --port=0:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/controlplane/manifests.go#L282-L283

please consult with the kubespray maintainers, they know about this.

/close
/sig cluster-lifecycle
