### ISSUE TITLE
Kubeadm uses deprecated etcd default snapshot count

### ISSUE THREAD

**Issue by zorro786** [kubernetes/kubernetes#100471]
#### What would you like to be added:
Kubeadm v1.20 has snapshot-count as 10000 in etcd [configuration](https://github.com/kubernetes/kubernetes/blob/release-1.20/cmd/kubeadm/app/phases/etcd/local.go) as default:

This has been changed in etcd 3.1 and since then (current latest version being 3.4) [default](https://github.com/etcd-io/etcd/pull/7160) is 100,000 

#### Why is this needed:
Unless Kubernetes has any performance specific considerations to keep older etcd default value for snapshot count, we should use the one recommended by etcd community.

**Comment by BenTheElder** [comment]
this is also what we have configured in kube-up.sh
https://github.com/kubernetes/kubernetes/blob/d25986b8a67314bce5667f45739a0e093184b926/cluster/gce/manifests/etcd.manifest#L56-L57

cc @aojea @neolit123

**Comment by aojea** [comment]
we should ask sig-scalability here , @wojtek-t has good insights always in all the etcd parameters

**Comment by neolit123** [comment]
> Kubeadm uses deprecated etcd default snapshot count

i would argue that this is not a "deprecated" count; does etcd think of it that way?
to my the value boils down to user preference that may even involve some trial and error and perf benchmarks.

i was asked on slack about this and i don't have the historic context of why 10000 was pinned.

if @wojtek-t is and SIG Scale are OK with the change we can merge it for 1.22.

**Comment by BenTheElder** [comment]
> i would argue that this is not a "deprecated" count. 

agree, I think this is just imprecise phrasing around ~"outdated" though, and the point stands for that.

https://kubernetes.io/blog/2018/12/11/etcd-current-status-and-future-roadmap/#etcd-v3-2-summer-2017 actually talks about increasing the snapshot count, but upstream tooling did not because we set the flag explicitly. It also talks about the tradeoffs

> etcd v3.2 also introduces changes such as “snapshot-count” default value from 10,000 to 100,000. With higher snapshot count, etcd server holds Raft entries in-memory for longer periods before compacting the old ones. etcd v3.2 default configuration shows higher memory usage, while giving more time for slow followers to catch up. It is a trade-off between less frequent snapshot sends and higher memory usage. Users can employ lower etcd --snapshot-count value to reduce the memory usage or higher “snapshot-count” value to increase the availability of slow followers.

**Comment by neolit123** [comment]
on the PR @ptabor is recommending that we lower it.

given this is very user setup specific and we have been running with this value for a while, i'm leaning towards a vote to not change it, but if others think otherwise lets pick a new value.

**Comment by pacoxu** [comment]
@ptabor 's comment on https://github.com/kubernetes/kubernetes/pull/100475#issuecomment-805592572

> I would keep this (10k) for now.
> FYI: https://docs.google.com/document/d/1O2o1IApHWmSioXG3fez4eVlUHOrXICYGNVIzaqNS0IQ/edit?resourcekey=0-e6Iywgdkol0uiVBAaV1oww#heading=h.8bdriypllkgh documents what the v2-store snapshot contains.

**Comment by neolit123** [comment]
closing and the PR based on the feedback from sig-scalability.

@zorro786 @lojies 
thank you for bringing this topic up.

/close

**Comment by neolit123** [comment]
@zorro786 if you pass a --config file to kubeadm it will respect your custom value:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  local:
    extraArgs:
      snapshot-count: 100000
```
