### ISSUE TITLE
Kubectl .lock file is ambiguous

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#100453]
#### What happened:

``` bash
KUBECONFIG=/dir1/config kubectl config use-context ctx --kubeconfig=/dir2/config
```
Use `/dir1/config.lock` and `/dir2/config`

#### What you expected to happen:

Use `/dir2/config.lock` and `/dir2/config`

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/sig api-machinery
PR is for client-go

**Comment by BenTheElder** [comment]
kubectl locks all files being read or written. I'm pretty sure but not positive that even if you pass `--kubeconfig` other files may be read.

**Comment by wzshiming** [comment]
I found it has been fixed in 1.20, https://github.com/kubernetes/kubernetes/pull/93293
Close this

**Comment by BenTheElder** [comment]
do we need to backport this? what version were you on?

**Comment by wzshiming** [comment]
1.19, Of course it would be better if it could be backport. although i think upgrading Kubectl is not a problem.

Due to the patch of #93293, I think it is necessary to clean up some of the code here that will no longer be used https://github.com/kubernetes/kubernetes/pull/100455#discussion_r599216408
