### ISSUE TITLE
Failing jobs gci-gce-serial-*

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#100481]
#### Which jobs are failing:

https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns-nodecache
https://testgrid.k8s.io/sig-network-gce#gci-gce-serial
https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns-nodecache
https://testgrid.k8s.io/sig-storage-kubernetes#gce-serial
https://testgrid.k8s.io/google-gce#gce-cos-master-serial&width=5

#### Which test(s) are failing:

[sig-storage] tests

It seems something related to gce-serial and storage, maybe something has changed recently?

Most of the tests fail with 
```
I0322 14:54:12.550] Mar 22 14:54:12.548: FAIL: Expected grep stdout to be empty (i.e. no mount found).
````

**Comment by aojea** [comment]
/sig testing
/sig storage
ping @spiffxp @BenTheElder @msau42

**Comment by msau42** [comment]
Is this the same as https://github.com/kubernetes/kubernetes/issues/100419?

**Comment by aojea** [comment]
it seems so, sorry for the noise, I didn't check the test name failinf
As always, @thejoycekung is doing an excellent job catching these failures


/close
duplicate of https://github.com/kubernetes/kubernetes/issues/100419
