### ISSUE TITLE
kube-proxy: persistent connection kept alive although readiness checks fails (and POD not ready)

### ISSUE THREAD

**Issue by rpasche** [kubernetes/kubernetes#100492]
#### What happened:

We are running some logstash pods within our environment to receive data from external customers. We use the persistent queue feature within logstash to buffer events on disks. In case the buffer disks fills up, we want all connections *to* that POD to be terminated. While *new* connections do NOT make it to that POD, persistent connections can still transfer data to that POD although it is reporting as *unhealthy*

#### What you expected to happen:

I expected to have kube-proxy to stop forwarding data to that POD once it is reported as *unhealthy*. At least, this is how I understood this paragraph at https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes

```
If you want your container to be able to take itself down for maintenance, you can specify a readiness probe that checks an endpoint specific to readiness that is different from the liveness probe.
```

#### Anything else we need to know?:

For me, the basic question is...is the readiness check supposed to work like I think? So if a readiness check fails, no packets should get forwarded to the POD (that service) anymore? In best case, kube-proxy also sends a RST packet Or is the readiness state only taken into account for *new* connections?

Thanks

**Comment by aojea** [comment]
/sig network
/remove-lifecycle rotten
I have to double check, but established connections should work to allow graceful termination
probes combinations are complex, there are some sections on the docs that explain the topic in more detail, but I don't know if this should be explicitely mentioned , @sftim  what do you think?

**Comment by caseydavenport** [comment]
/remove-kind bug
/kind support

I agree with @aojea - established connections shouldn't be reset by the kube-proxy, but new connections should stop being forwarded to the unready endpoint. So, I think that's working as intended.

**Comment by caseydavenport** [comment]
/triage accepted
/close 

The docs do also say this:

> If you want to be able to drain requests when the Pod is deleted, you do not necessarily need a readiness probe; on deletion, the Pod automatically puts itself into an unready state regardless of whether the readiness probe exists. The Pod remains in the unready state while it waits for the containers in the Pod to stop

Which is not explicit, but does imply that going unready provides a chance for the pod to gracefully terminate existing connections.

**Comment by rpasche** [comment]
The thing is, I do not want the pod to get restarted in certain cases. That is our issue. I want the pod and the process to continue running (so being able to still process "queued" events) whole *no new events* should get - still? - routed to that pod.

**Comment by caseydavenport** [comment]
Sorry, I didn't mean to imply you needed to restart your pod. 

> So if a readiness check fails, no packets should get forwarded to the POD (that service) anymore?

I think the crux of the issue is that we're dealing with connections, not packets. The connection will stay live until it is terminated, and packets for that connection will still be allowed. If you want to stop receiving packets, then the pod needs to terminate existing connections in order to tear down conntrack state.

New connections will not be routed to that pod while it's unready, though.
