### ISSUE TITLE
AuditLog for update operation without change the object

### ISSUE THREAD

**Issue by yunhjiang** [kubernetes/kubernetes#100473]
#### What happened:
At k8s, some controller will update the object even when there is no change to the object itself. One example is the cronjob, which will update the object blindly.

Currently such update will be recorded by the audit log event and passed to the backend. It's not easy for the backend to distinguish the update is success or not, especially if the auditlog is set to Request level, thus the audit log event has to keep all the information. 

#### What you expected to happen:

The audit log logic can provide a method so that such non-change update will be ignored, or it's easy to filter our such information without comparing the resource version in the request/response field in the audit log event.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by deads2k** [comment]
The audit log is an log of requests.  It is not a log for resource impact.  I don't think this will move forward as an issue.  Instead, you can try a KEP in https://github.com/kubernetes/enhancements . The sig you're looking for review in the enhancements repo is sig-auth.

/close

**Comment by yunhjiang** [comment]
@deads2k  Is the auditlog part of sig-auth, instead of api machinery?

**Comment by deads2k** [comment]
> @deads2k Is the auditlog part of sig-auth, instead of api machinery?

sig-auth owns the audit feature: https://github.com/kubernetes/community/tree/master/sig-auth .
