### ISSUE TITLE
Delete legacy proxy path

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#10045]
We right now have two different URL paths in the v1 API for proxying to a pod:

```
/api/v1/proxy/namespaces/{namespaces}/pods/{name}/{path:*}
/api/v1/namespaces/{namespaces}/pods/{name}/proxy/{path:*}
```

This is because, we're in the process of moving towards using subresources (the second URL), but haven't deleted the legacy path yet (the first one).

This is to keep track of deleting the legacy proxy path.

**Comment by nikhiljindal** [comment]
cc @smarterclayton @bgrant0607

**Comment by smarterclayton** [comment]
The service proxy needs to be moved, @csrwng either knows which issue it is or should be able to create the issue if it doesn't exist

**Comment by bgrant0607** [comment]
#10038

**Comment by lavalamp** [comment]
We need:

* Make sure the "new" way works for all resources (services, pods, nodes) (I don't think this is true for 1.1)
* Add to release notes that people need to transition while running 1.2 because it's going away for 1.3
* Actually remove it after 1.2 branch is cut.

**Comment by liggitt** [comment]
subresource proxying is still in progress for nodes and services:
https://github.com/kubernetes/kubernetes/pull/18010
https://github.com/kubernetes/kubernetes/pull/17493

those PRs are pending API approval, but are ready otherwise

**Comment by lavalamp** [comment]
And we won't ever be able to remove the old way from the current API. Only from the new APIs.

**Comment by smarterclayton** [comment]
Depends.  We could certainly age out API patterns with sufficient lead
time.  It just may not be worth it.

**Comment by lavalamp** [comment]
I will kick this to the next release once #17493 merges.

**Comment by mbohlool** [comment]
I think this had sufficient lead. It creates confusion for generated clients to have both connect and proxy in API. I am going to remove proxy as it is deprecated in 1.2

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/59884
