### ISSUE TITLE
Return the ObjectReference.Name on the AuditLog event for object created through GenerateName 

### ISSUE THREAD

**Issue by yunhjiang** [kubernetes/kubernetes#100466]
#### What happened:
When an object is created through the GenerateName and there is metadata.Name is not specified, the AuditLog event for it does not have the ObjectReference.Name populated.

#### What you expected to happen:
The ObjectReference.Name should specify the object name on the ResponseCompleted.

#### How to reproduce it (as minimally and precisely as possible):
1. Enable the Auditlog for pod create event
2. Create a job, which will create pod
3. Check the ObjectReference.Name on the auditlog event for the pod

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzshiming** [comment]
Maybe you should watch the Update event,  Pod creation and metadata.Name filling are done by two different components.

**Comment by yunhjiang** [comment]
Thanks for checking, @wzshiming . However, I don't get your suggestion of  'watch the Update event'. Why it helps here? Currently our issue is,  we can't figure out from the audit log who and when it's created for such case.

Watch the Update event does not provide us such information, right? Although we can watch the 'create' event, but that will miss the information of who/when/sourceip etc, i.e. the benefit of auditlog.

Do you think that it's possible to change LogResponseObject() at  https://github.com/kubernetes/kubernetes/blob/34cab8f80a9104be7fe5d8a5a22c3207dab46268/staging/src/k8s.io/apiserver/pkg/audit/request.go#L175, so that if the ObjectReference.Name is not set, we decode the object and populate the information? I'm not sure if encodeObject() can provide the name information?

**Comment by enj** [comment]
/remove-lifecycle rotten
/triage accepted

I have not confirmed that this bug exists, but I suspect that it does.  It may be tricky to fix based on when the storage layer fills out the generated name vs when the audit layer runs.

**Comment by yunhjiang** [comment]
> /remove-lifecycle rotten
> /triage accepted
> 
> I have not confirmed that this bug exists, but I suspect that it does. It may be tricky to fix based on when the storage layer fills out the generated name vs when the audit layer runs.

I think possibly we can't do it easily for the RequestReceived stage event, but it will be easy to do it at the ResponseCompleted stage?
