### ISSUE TITLE
start-apiserver (needs to run as root) gives misleading failure in gce/gci/configure_helper_test.go bc of chown

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#100421]
#### What happened:

When poking around on a PR reproducer, i found that on my machine w/ zshell as the default, where id migrated some code over from an NFS share, had these failures...  turns out it was related to `chown` failures....  but we dont report that .  easy fix is to just improve the clogging in the clsuter helper stuff. (PR attached)

```
-> % make test
+++ [0320 14:04:32] Running tests without code coverage
--- FAIL: TestServerOverride (0.12s)
    --- FAIL: TestServerOverride/ETCD-SERVERS_is_not_set_-_default_override (0.07s)
        configure_helper_test.go:120: "Start kubernetes api-server\nchown: changing ownership of '/tmp/configure-helper-test892907696/kube-apiserver.log': Operation not permitted\n"
        configure_helper_test.go:121: Failed to run ["bash" "-c" "source \"/tmp/configure-helper-test892907696/kube-env\" ;source \"configure-helper.sh\" ;source \"configure-kubeapiserver.sh\" ;start-kube-apiserver"]: exit status 1
    --- FAIL: TestServerOverride/ETCD-SERVERS_and_ETCD_SERVERS_OVERRIDES_are_set (0.05s)
        configure_helper_test.go:120: "Start kubernetes api-server\nchown: changing ownership of '/tmp/configure-helper-test727776335/kube-apiserver.log': Operation not permitted\n"
        configure_helper_test.go:121: Failed to run ["bash" "-c" "source \"/tmp/configure-helper-test727776335/kube-env\" ;source \"configure-helper.sh\" ;source \"configure-kubeapiserver.sh\" ;start-kube-apiserver"]: exit status 1
```

#### What you expected to happen:

Bash commands to change directories wouldnt fail or be heavily relied on 

#### How to reproduce it (as minimally and precisely as possible):

not sure, but some machines maybe w different bash versions etc might not work for these tests

Happy to close if this is a non issue, will try to see if i can isolate the root cause..  in my box bash works fine and i can use it to source files etc... so im kinda confused about why the api

**Comment by jayunit100** [comment]
yeah digging around that `chown` is the culprit... i guess `make test` fails unless your root?

**Comment by BenTheElder** [comment]
/triage duplicate

https://github.com/kubernetes/kubernetes/issues/99881

This was? fixed already before this issue was filed (https://github.com/kubernetes/kubernetes/pull/100368 merged 4 days ago), please update your clone.

I do not see this error at 1a983bb958b
