### ISSUE TITLE
Delete the log of the component, it will still not rebuild the file to save it.

### ISSUE THREAD

**Issue by lunhuijie** [kubernetes/kubernetes#100478]
#### What happened:
1.when I delete the log's file of kubelet and find the status of kubelet is ok.
but i can't find where these logs go.
2.when I mv the log's file of kubelet to other path, it still write to this file.
then i rebuild the same file at the old path, it wouldn't write to this new file but still the one which moved to other path just now.
3.when I delete the logs of kubelet and restart kubelet, it will rebuild. 
#### What you expected to happen:
whatever I do to these log's files, it will rebuild when cluster found it lost.
#### How to reproduce it (as minimally and precisely as possible):
see What happened
#### Anything else we need to know?:
This situation is right? I think it is unreasonable not to rebuild
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mengjiao-liu** [comment]
I can repeat the question 
```sh
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

I've looked at the code and this is probably a problem with the Klog library.

I will try to fix this.

/assign

**Comment by lunhuijie** [comment]
I am also looking at this piece of code to solve this problem. If you have any nice idea, we can discuss it together. @mengjiao-liu

**Comment by mengjiao-liu** [comment]
Now you can be sure that the problem is with the Klog library, because I test with Klog alone and repeat the problem as well @lunhuijie

**Comment by lunhuijie** [comment]
klog.go->output->switch s {    , I find v19 is differ to v20. 
Every time I make a mistake when writing a file, an error value will be returned. In this code, the processing of the error return value is discarded. If you need to fix this problem, you may need to increase the judgment of the error return. @mengjiao-liu

**Comment by mengjiao-liu** [comment]
When deleting or moving log files,` L.File [infoLog] != nil` 
https://github.com/kubernetes/klog/blob/master/klog.go#L928-L933

so log file is not rebuilt @lunhuijie

**Comment by mengjiao-liu** [comment]
Need to update the klog version to solve the issue after [it is fixed ](https://github.com/kubernetes/klog/pull/232)

**Comment by mengjiao-liu** [comment]
Haven't had time to do it recently, or can you continue with it? @lunhuijie

/unassign

**Comment by mengjiao-liu** [comment]
The previous PR is here https://github.com/kubernetes/klog/pull/232 for your reference.

Anyone is welcome to do it.😀

**Comment by RPing** [comment]
I can try this one.
So currently, the only reason kubernetes/klog#232 can't be merged is that we need to use file watch instead of original `os.IsExist` approach, right? @mengjiao-liu

**Comment by mengjiao-liu** [comment]
Thanks for your effort. @RPing
Yes, I think it takes too much I/O to check every time.

**Comment by RPing** [comment]
I try the file watch way like watcher in [kubernetes](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/filesystem/watcher.go), but encountered an issue in fsnotify: fsnotify/fsnotify#194, it waits fsnotify/fsnotify#260 to be fixed.

**Comment by RPing** [comment]
@mengjiao-liu I've implemented a simple fix using a inotify goroutine.
But I want to clarify that what's the timing for rebuilding the log?
If we want to rebuild it as soon as the log is deleted, we should put the inotify goroutine into kubelet, not klog.

**Comment by mengjiao-liu** [comment]
If rebuilt, the time point is after the file is deleted.On second thought, the immediate reconstruction should have been done in Kubelet. File handle release and file reconstruction should be a feature rather than a bug.

Let's refer to more comments. @serathius @derekwaynecarr @mrunalp
