### ISSUE TITLE
Extremely slow detach/attach via controller-manager(in-tree volume plugin)

### ISSUE THREAD

**Issue by ivan-cai** [kubernetes/kubernetes#100555]
#### What happened:
A in-tree volume plugin. kubernetes version is 1.12.4. 3253 nodes and 11000+ pvs in cluster.
If I recreate a pod (with pvc of this in-tree volume plugin), sometimes I found the volume would not be detach in   6min(maxWaitForUnmountDuration) . Because `attachedVolume.MountedByNode` always `true`,  `DetachVolume` only be called after timeout(maxWaitForUnmountDuration).
The recreating pod will be `running` after 10min.

1. 14:00:51 pod start attchvolume to 10.0.91.178(new node)
2. 14:00:52 unmount succeeded volume from 10.0.79.215(old node)
3. 14:06:27 pod start detachvolume from 10.0.79.215, and is called by force detaching(6min timeout)
4. 14:06:35 volume detach succeeded from 10.0.79.215
5. 14:06:44 volume attach succeeded to 10.0.91.178
6. 14:08:20 start mountvolume to 10.0.91.178
7. 14:08:21 mountvolume succeeded to 10.0.91.178

 logs in kube-controller-manager：
```
I0324 14:00:51.005553       1 reconciler.go:296] attacherDetacher.AttachVolume started for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") from node "10.0.91.178"
W0324 14:06:27.405252        1 reconciler.go:234] attacherDetacher.DetachVolume started for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") on node "10.0.79.215" This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching
I0324 14:06:35.634703       1 operation_generator.go:420] DetachVolume.Detach succeeded for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") on node "10.0.79.215"
I0324 14:06:44.166122       1 operation_generator.go:336] AttachVolume.Attach succeeded for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") from node "10.0.91.178"
```

logs in old node(10.0.79.215)：
```
Mar 24 14:00:52 qsh4-k8s-rmt-202011-placement-06 kubelet[4879]: I0324 14:00:52.203475    4879 operation_generator.go:706] UnmountVolume.TearDown succeeded for volume "kubernetes.io/qcloud-cbs/disk-gqk6de0b" (OuterVolumeSpecName: "p-rmt-sns-comment-page-cache") pod "af64310e-5c9c-11eb-80b9-dac834c1f5b0" (UID: "af64310e-5c9c-11eb-80b9-dac834c1f5b0"). InnerVolumeSpecName "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41". PluginName "kubernetes.io/qcloud-cbs", VolumeGidValue ""
```

logs in new node(10.0.91.178)：
```
Mar 24 14:08:20 qsh4-k8s-rmt-202011-placement-12 kubelet[21564]: I0324 14:08:20.623875   21564 reconciler.go:252] operationExecutor.MountVolume started for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") pod "rmt-sns-comment-page-cache-0" (UID: "c00b6e4a-8c66-11eb-bc71-7eca219a0cbd")
Mar 24 14:08:20 qsh4-k8s-rmt-202011-placement-12 kubelet[21564]: I0324 14:08:20.623912   21564 operation_generator.go:499] MountVolume.WaitForAttach entering for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") pod "rmt-sns-comment-page-cache-0" (UID: "c00b6e4a-8c66-11eb-bc71-7eca219a0cbd") DevicePath "/dev/disk/by-id/virtio-disk-gqk6de0b"
Mar 24 14:08:21 qsh4-k8s-rmt-202011-placement-12 kubelet[21564]: I0324 14:08:21.704737   21564 operation_generator.go:529] MountVolume.MountDevice succeeded for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") pod "rmt-sns-comment-page-cache-0" (UID: "c00b6e4a-8c66-11eb-bc71-7eca219a0cbd") device mount path "/var/lib/kubelet/plugins/kubernetes.io/qcloud-cbs/mounts/disk-gqk6de0b"
Mar 24 14:08:21 qsh4-k8s-rmt-202011-placement-12 kubelet[21564]: I0324 14:08:21.714256   21564 operation_generator.go:569] MountVolume.SetUp succeeded for volume "pvc-cc04208e-346e-11eb-9d40-5e96bcb88e41" (UniqueName: "kubernetes.io/qcloud-cbs/disk-gqk6de0b") pod "rmt-sns-comment-page-cache-0" (UID: "c00b6e4a-8c66-11eb-bc71-7eca219a0cbd")
```

#### What you expected to happen:
- controller-manager detaches volume from the old node immideately after the pod is removed and attaches it to new one immediately after detaching.

#### How to reproduce it (as minimally and precisely as possible):
- an occasional bug
- recreate pod, and pod is schduled to another node

#### Anything else we need to know?:
- detach too slow(>6min),`attachedVolume.MountedByNode` always `true` in 6min
- apiserver is normal （cpu,memory and so on）

#### Environment:
- Kubernetes version (use `kubectl version`): 1.12.4
- Cloud provider or hardware configuration: tencentcloud
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ivan-cai** [comment]
@kubernetes/sig-storage-bugs

**Comment by ivan-cai** [comment]
cc @gnufied @yuga711 @jingxu97 @jsafrane

**Comment by jingxu97** [comment]
The reason detach takes 6 mins to tigger is because on node side, kubelet did not successfully umount the volume and update node status volumeInUse. Detach can only be safely triggered after volume is unmounted at node side. There is 6 mins timeout, and detach will be triggered forcefully.

**Comment by ivan-cai** [comment]
@jingxu97 Reason is not on node side. Umount volume succeeded quickly，and node.status.volumeInUse also be updated(`kubectl get node xxx -oymal` can see the change).
I think the problem is caused by apiserver or kcm. But I use cmd `curl` to watch the Node object, its' status.volumeInUse is updated. But I do not ensure if caused by nodeinformer in kcm.

**Comment by jingxu97** [comment]
I see. btw: you k8s version is too old. Better to upgrade the version and then test it again?
You mentioned 11000+ pvs in cluster. How many nodes in your cluster?

**Comment by ivan-cai** [comment]
@jingxu97 There are 3253 nodes in cluster.

**Comment by ivan-cai** [comment]
I know the reason for this issue. K8s 1.12, the Node objects are updated frequently. Because of the heartbeat from kubelet to APIServer.
