### ISSUE TITLE
kubernetes should support cross namespace ownerrefrence

### ISSUE THREAD

**Issue by zhaojizhuang** [kubernetes/kubernetes#100577]
#### What happened:

kubernetes don't allow cross namespace ownerrefrence

```yaml
ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Revision
      name: websocket-chat-00001
      uid: 187fddec-771b-4708-bcc0-741436cd248c
    resourceVersion: "38260697"
    uid: 983ccda9-9123-4edf-b65e-f01cd4433a55
```

#### What you expected to happen:
allow cross namespace ownerrefrence,as follows

```yaml
ownerReferences:
    - apiVersion: serving.knative.dev/v1
      blockOwnerDeletion: true
      controller: true
      kind: Revision
      name: websocket-chat-00001
      uid: 187fddec-771b-4708-bcc0-741436cd248c
      namespace: xxxxx
    resourceVersion: "38260697"
    uid: 983ccda9-9123-4edf-b65e-f01cd4433a55
```

#### Environment:
- Kubernetes version (use `kubectl version`):
```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by CaoDonghui123** [comment]
I think this is a feature, not a bug
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by zhaojizhuang** [comment]
> I think this is a feature, not a bug
> https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

@CaoDonghui123 yeah... it is just a feature suggestion. For in my project, I want to build a `ownerReferences` which points to resource in another namespace

**Comment by liggitt** [comment]
Cross namespace references are disallowed by design as described in https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/


See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#object-references for details about the considerations behind namespace scoping references

**Comment by liggitt** [comment]
> To make things worse, this used to work but suddenly stopped.

In the past, it could sometimes work, but not consistently/safely... cross-namespace owner references were always vulnerable to random deletion on controller-manager restart. xref https://github.com/kubernetes/kubernetes/issues/65200
