### ISSUE TITLE
Improve coverage of authorization metrics in apiserver (authorization_attempts)

### ISSUE THREAD

**Issue by melnikalex** [kubernetes/kubernetes#100588]
#### What would you like to be added:
Some metrics on authorization:
* overall approved
* overall denied
* overall latency

#### Why is this needed:
Many users run multiple authorizers in the authorization chain. When cluster administrators are making changes anywhere in the chain or updating the authorization components they'd like to have metrics around authorization to help detect anomalies sooner.

/sig auth
/kind feature

**Comment by melnikalex** [comment]
I'm thinking about submitting something similar to these CRs but for authorization:
https://github.com/kubernetes/kubernetes/pull/81509?_pjax=%2523js-repo-pjax-container

**Comment by enj** [comment]
/triage accepted
/remove-lifecycle rotten

Metrics related to authorization seem like a reasonable addition.

**Comment by enj** [comment]
@logicalhan @liggitt do we require a KEP for new metrics?

**Comment by logicalhan** [comment]
No, I don't think that's necessary, but please tag instrumentation for reviews, we've had some problematic metrics recently.
