### ISSUE TITLE
Document how to upgrade a CoreOS-based Cluster

### ISSUE THREAD

**Issue by jcderr** [kubernetes/kubernetes#10058]
I have a CoreOS-based cluster based on 0.17 and would love to upgrade to more recent versions.

**Comment by erimatnor** [comment]
I just made some CoreOS cluster configs available here that might interest you. They are based on Fleet so it makes it easier to upgrade Kubernetes. Current version used is v0.18.2.

https://github.com/iobeam/coreos-kubernetes
