### ISSUE TITLE
Pick up l7-lb-controller version that uses v1 APIs

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#100560]
found this in https://github.com/kubernetes/kubernetes/pull/99840 while finding beta API dependencies for 1.22.  This will block `pull-kubernetes-e2e-gce-ubuntu-containerd` from running at all in 1.22

I *think* this is for this deployment: https://github.com/kubernetes/ingress-gce/blob/426c8588246e40b5d24a6230d5d3751766c94cd4/docs/deploy/resources/glbc.yaml  , and in ingress-gce I found https://github.com/kubernetes/ingress-gce/pull/1384

**Comment by aojea** [comment]
/sig network
/triage accepted
I pinged some GCE sig-network folks in the PR 
https://github.com/kubernetes/ingress-gce/pull/1384#issuecomment-807010731

**Comment by liggitt** [comment]
> I _think_ this is for this deployment: https://github.com/kubernetes/ingress-gce/blob/426c8588246e40b5d24a6230d5d3751766c94cd4/docs/deploy/resources/glbc.yaml

given that uses extensions/v1beta1 Deployments, that particular manifest seems unused

**Comment by deads2k** [comment]
once we land the fix in https://github.com/kubernetes/ingress-gce/pull/1384 , anyone know how to update the image we use in e2e tests?

**Comment by liggitt** [comment]
/assign @freehan 

The update to use v1 APIs is merged to `master` in https://github.com/kubernetes/ingress-gce/pull/1384

What version should be tagged we can pick up in https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/manifests/glbc.manifest#L20? Does https://github.com/kubernetes/ingress-gce/pull/1384 need to be picked back to one or more release branches?

**Comment by liggitt** [comment]
It would be helpful to get a `k8s.gcr.io/ingress-gce-glbc-amd64` version containing the fix tagged, so the manifest can be updated in https://github.com/kubernetes/kubernetes/pull/99840 to get e2e signal even before `master` opens for 1.22.

**Comment by freehan** [comment]
Ack. We are planning to cut a release soon. Once the release is cut, I will update the k/k to use that

**Comment by jprzychodzen** [comment]
@freehan what's the ETA for cutting ingress-gce release? I think it might be related to failing pull-kubernetes-e2e-gce-100-performance run in #99840
