### ISSUE TITLE
Add flags to kubeadm for customizing  the image version of etcd and coreDNS

### ISSUE THREAD

**Issue by wangyysde** [kubernetes/kubernetes#100512]
#### What would you like to be added:
Ref: #100174
Ref: #2411
Add flags to kubeadm for customizing  the image version of etcd and coreDNS
#### Why is this needed:
Sometimes users want to compile k8s components and build customized k8s component images, push them to the docker repository, and then install k8s with kubedm. At this time, they need to specify the tag of the customized k8s component. Now,    using --image-repository and  --kubernetes-version flags can customizes the respository and the version of Kubernetes components. But there isn't flags to customize the versions of etcd and coreDNS.

**Comment by fabriziopandini** [comment]
@wangyysde FYI, we are collecting kubeadm issues

As per comment on the related PR 
> @wangyysde I'm sorry but I'm -1 for this change for two reasons:
> - We are avoiding changes to existing API version in kubeadm, even if non breaking/additions; in order to add new fields it is required to include this change in the next API version (you can refer the kubeadm repo for changes planned/under evaluation for the next release)
> - We are carefully restricting the usage of flags in kubeadm for the most common use cases only

> Currently, many Kubeadm users are addressing your use case by using the existing image meta field, but if this does not fit your use case we are happy to discuss it in the kubeadm office hours

**Comment by SataQiu** [comment]
@wangyysde 

You can list the images needed by kubeadm, and push them into your own repo, then run `kubeadm init --image-repository <your-own-repo-address>`.

```bash
[root@iZj6c21mhndh5fnby05mhcZ ~]# kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.20.5
k8s.gcr.io/kube-controller-manager:v1.20.5
k8s.gcr.io/kube-scheduler:v1.20.5
k8s.gcr.io/kube-proxy:v1.20.5
k8s.gcr.io/pause:3.2
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
```

**Comment by wangyysde** [comment]
@SataQiu Thanks. I know that we can specify the repository and version of k8s components by using --image-repository or --kubernetes-version flag . But I don't know how to specify the versions of  coreDNS and etcd.

**Comment by wangyysde** [comment]
@fabriziopandini Thank you for your comments. 

-  I know that we can specify the repository and version of k8s components by using --image-repository or --kubernetes-version flag. But I don't know how to specify the versions of coreDNS and etcd by using the existing image meta field.
-  Currently,as if the version of  the k8s components can be specified,but  the version of  the two external component image (coreDNS and Etcd) can not be specified. I don't know why  the k8s components' version can be specified while the two external component can not ?
- I think that the two flags can be added in the next milestone. But I am a beginner in the kubernetes community. Anyone can tell me what I must to do if I want to commit this issues with the PR to the next milestone? Thanks.

**Comment by neolit123** [comment]
@wangyysde kubernetes components are moving away from flags in favor of configuration files.
we don't want to add more flags in kubeadm that duplicate options that are already in the config.

you should be using the --config and nothing else...unless something is only available as a flag (likely experimental at that point).

your PR cannot be accepted for other reasons too @fabriziopandini covered them.

**Comment by fabriziopandini** [comment]
/close
We can move the discussion on a new issue in the kubeadm repo if required.
