### ISSUE TITLE
document _output directory

### ISSUE THREAD

**Issue by oz123** [kubernetes/kubernetes#100596]
#### What happened:
I spent quite a while figuring out how to build the docker images for k8s, when I finally succeeded, the build process told me the images are deleted. I was quite puzzled:
```
$ sudo make quick-release-images WHAT=kube-apiserver 
+++ [0327 01:42:50] Verifying Prerequisites....
+++ [0327 01:42:51] Building Docker image kube-build:build-e1b7576657-5-v1.15.8-legacy-1
+++ [0327 01:42:53] Creating data container kube-build-data-e1b7576657-5-v1.15.8-legacy-1
+++ [0327 01:43:07] Syncing sources to container
+++ [0327 01:43:17] Running build command...
+++ [0327 01:43:30] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
+++ [0327 01:43:36] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
+++ [0327 01:43:46] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
+++ [0327 01:43:59] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
+++ [0327 01:44:19] Building go targets for linux/amd64:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
+++ [0327 01:44:36] Building go targets for linux/amd64:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
+++ [0327 01:44:38] Building go targets for linux/amd64:
    cmd/kube-apiserver
    cmd/kube-controller-manager
    cmd/kube-scheduler
    cmd/kube-proxy
    vendor/github.com/onsi/ginkgo/ginkgo
    test/e2e/e2e.test
    cluster/images/conformance/go-runner
    cmd/kubectl
+++ [0327 01:55:16] Syncing out of container
+++ [0327 01:55:22] Building images: linux-amd64
+++ [0327 01:55:22] Starting docker build for image: kube-apiserver-amd64
+++ [0327 01:55:22] Starting docker build for image: kube-controller-manager-amd64
+++ [0327 01:55:22] Starting docker build for image: kube-scheduler-amd64
+++ [0327 01:55:22] Starting docker build for image: kube-proxy-amd64
+++ [0327 01:55:22] Building conformance image for arch: amd64
+++ [0327 01:55:33] Deleting docker image k8s.gcr.io/kube-scheduler-amd64:v1.19.10-dirty
+++ [0327 01:55:34] Deleting docker image k8s.gcr.io/kube-controller-manager-amd64:v1.19.10-dirty
+++ [0327 01:55:34] Deleting docker image k8s.gcr.io/kube-apiserver-amd64:v1.19.10-dirty
+++ [0327 01:55:35] Deleting docker image k8s.gcr.io/kube-proxy-amd64:v1.19.10-dirty
+++ [0327 01:55:41] Deleting conformance image k8s.gcr.io/conformance-amd64:v1.19.10-dirty
+++ [0327 01:55:41] Docker builds done
```
After I built the images again. only to receive the same message, I started digging, and I found out that the
images are exported with `docker save`.

#### What you expected to happen:
I think a notification where the images are found would be useful. If you do it a couple of times you remember this, 
but for newcomers or the occasional contributor this can be very frustrating.

A log message [ here can be useful:](https://github.com/kubernetes/kubernetes/blob/7146eb593126d77d2dfdc1444dad068881b7c391/build/lib/release.sh#L397)
```
        "${DOCKER[@]}" build ${docker_build_opts:+"${docker_build_opts}"} -q -t "${docker_image_tag}" "${docker_build_path}" >/dev/null
        # If we are building an official/alpha/beta release we want to keep
        # docker images and tag them appropriately.
        local -r release_docker_image_tag="${KUBE_DOCKER_REGISTRY-$docker_registry}/${binary_name}-${arch}:${KUBE_DOCKER_IMAGE_TAG-$docker_tag}"
        if [[ "${release_docker_image_tag}" != "${docker_image_tag}" ]]; then
          kube::log::status "Tagging docker image ${docker_image_tag} as ${release_docker_image_tag}"
          "${DOCKER[@]}" rmi "${release_docker_image_tag}" 2>/dev/null || true
          "${DOCKER[@]}" tag "${docker_image_tag}" "${release_docker_image_tag}" 2>/dev/null
        fi
        +++kube::log::status "Saving docker image ${docker_image_tag} in "${images_dir}/"
        "${DOCKER[@]}" save -o "${binary_file_path}.tar" "${docker_image_tag}" "${release_docker_image_tag}"
        echo "${docker_tag}" > "${binary_file_path}.docker_tag"
        rm -rf "${docker_build_path}"
        ---ln "${binary_file_path}.tar" "${images_dir}/"
        +++ln -v "${binary_file_path}.tar" "${images_dir}/"

        kube::log::status "Deleting docker image ${docker_image_tag}"
        "${DOCKER[@]}" rmi "${docker_image_tag}" &>/dev/null || true
```

I'm happy to submit a PR, if you think this is useful.

**Comment by BenTheElder** [comment]
FWIW _all_ output goes under `_output`, I think we should ensure this is sufficiently documented at least.
https://github.com/kubernetes/kubernetes/blob/master/build/README.md

**Comment by oz123** [comment]
It took me a while to find this. Also, I tried using the scripts directly without much success. The makefile is much more helpful. It might be worth mentioning that in the linked document.

**Comment by Ghosgt** [comment]
i had the same problem

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
/help
/triage accepted
/kind documentation
/retitle document _output directory
though also a log message might be good? thing is where to stick it, we have a lot of variations on building that won't pass through the same codepaths ...
IMO this absolutely ought to be documented at the very least

**Comment by oz123** [comment]
@BenTheElder to begin with, I only added a note about the location of the build artifacts.
The  `Makefile` is referenced already in many places in the developer guide. Maybe it is better to
completely remove the mentioning of manual invocation of the individual scripts and instead
recommend the specific make target?
IMHO, this is more consistent with the rest of the documentation. However, it is definitely out of
scope here. If you or other dev's think it is a good idea, I can submit another PR for that.

**Comment by BenTheElder** [comment]
> The Makefile is referenced already in many places in the developer guide. Maybe it is better to
completely remove the mentioning of manual invocation of the individual scripts and instead
recommend the specific make target?

Generally I think this is true, but there are some specific scripts in the repo where it can make sense to just invoke them directly and a few that are not in the makefile at all (like build/run.sh) so it doesn't necessarily apply to everything, but I'd agree it generally applies to building at least. And I think that it would be good to make this more consistent 😅

**Comment by oz123** [comment]
@BenTheElder Ping. Can this be merged?
