### ISSUE TITLE
kubectl cp does not show any error for copying non existing file

### ISSUE THREAD

**Issue by kumarvijendar** [kubernetes/kubernetes#100539]
#### What happened: 
I was copying a file using kubectl to one of my pod, accidentally I was giving a wrong path for my file
#### What you expected to happen:
kubernetes should've shown an error with an exit status
#### How to reproduce it (as minimally and precisely as possible):
 kubectl -n my-namespace cp not-existing-random-file-name pod-name:/tmp/potato.txt
 
The command completes silently and does not show any error. 
#### Anything else we need to know?:
Even the exist status of the command comes as 0
#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2-0-g52c56ce", GitCommit:"d7f3ccf9a5bdc96ba92e31526cf014b3de4c46aa", GitTreeState:"clean", BuildDate:"2020-09-11T23:48:53Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0+d59ce34", GitCommit:"d59ce3486ae3ca3a0c36e5498e56f51594076596", GitTreeState:"clean", BuildDate:"2020-10-08T15:58:07Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): NAME="CentOS Linux"
- Kernel (e.g. `uname -a`): GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by CaoDonghui123** [comment]
It was fixed by #90333
