### ISSUE TITLE
Add kubernetes-specific labels to the google cloud logging fluentd plugin

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#10061]
Effectively a cross-post of https://github.com/GoogleCloudPlatform/fluent-plugin-google-cloud/issues/15, but this also tracks updating our fluentd images once the plugin has been changed.

@mr-salty @satnam6502

**Comment by satnam6502** [comment]
How do we decide a milestone for this PR?

**Comment by a-robinson** [comment]
@erickhan

**Comment by justinsb** [comment]
Love this feature.  Any plans to do something similar for ES?  And did we consider just replacing fluentd with our own collector (in Go)?

**Comment by a-robinson** [comment]
@justinsb, I can't remember if you've been pointed there before, but I think #8632 is along the lines of what you would want for ES.

And we haven't really considered replacing it, no. Fluentd hasn't been a source of problems as far as I've seen. I expect the main benefits that would motivate a replacement would be lower resource usage and making it easier to integrate k8s concepts?

**Comment by a-robinson** [comment]
Closing in favor of #8001, which is effectively the same.
