### ISSUE TITLE
There is no way to pass arguments to the test subject in integration testing

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#100611]
#### What happened:
I wanted to run an integration test and use the `-args` option of `go test` to pass parameters to the program being tested.  I could not find a way to do so.  I tried `KUBE_TEST_ARGS="-args $the_args_I_wanted"` but this failed because those args were followed by `-short=true` in the actual program invocation (see https://github.com/kubernetes/kubernetes/blob/770d3f181c5d7ed100d1ba43760a74093fc9d9ef/hack/make-rules/test-integration.sh#L76 for the reason).

#### What you expected to happen:
I expected there to be a way.  I expected it to be documented.

#### Environment:
- Kubernetes version (use `kubectl version`): current and many recent releases
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-testing

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
https://github.com/kubernetes/kubernetes/pull/100657 just needs a rebase and another poke at assigned reviewers
