### ISSUE TITLE
Master continues to use deleted node's etcd

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#100677]
#### What happened:
**Kuberntes version:** 1.18.6
### Summary: 
Created a master via init, added another one via "join", after sometime, drained & deleted the joined-node. Still etcd spews messages like, `etcdserver: leader changed`. Later when I intentionally removed /etc/kubernetes from deleted node & rebooted it, it made the first master "inoperative". Any kubectl command says "connection to server refused"

### Details:
1) In master -1 call init as below
```
kubeadm init \
        --control-plane-endpoint "${SLB_VIP}:6443" \
        --apiserver-advertise-address "${SELF_IP}" \
        --kubernetes-version "1.18.6" \
        --upload-certs \
        --skip-phases=addon/kube-proxy \
        --skip-phases=addon/coredns \
        --ignore-preflight-errors=FileContent--proc-sys-net-bridge-bridge-nf-call-iptables \
        -v=5) || ret=$?

```
2) In Master-2, called join as below

```
curl -m 10 -o ${tfile} http://${SLB_VIP}/admin.conf
kubeadm join --discovery-file ${tfile} --control-plane

```
3) Sleep for many minutes; Check to see both masters are running fine and reported in `kubectl get nodes`.

4) Drain & delete master -2
```
kubectl drain ${hname} --ignore-daemonsets --delete-local-data
kubectl delete node ${hname}

```
5) Run "`kubectl get nodes`" multiple times to see spew as below. Note, when the command succeeded, it listed **only one node.** The error message "_leader changed_" keeps appearing
```
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: leader changed
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: leader changed
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: request timed out
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: request timed out
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: request timed out
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
NAME              STATUS   ROLES    AGE   VERSION
co4aeap000105c2   Ready    master   36m   v1.18.6
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: leader changed
remanava@CO4AEAP000105C2:/var/log/containers$ k.sh get nodes
Error from server: etcdserver: leader changed
```
6) In master 2, I removed /etc/kubernetes dir and rebooted the box
```
remanava@CO4AEAP000105BD:/usr/share/sonic/deploy/install_scripts$ sudo rm -rf /etc/kubernetes/
remanava@CO4AEAP000105BD:/usr/share/sonic/deploy/install_scripts$ date; sudo reboot
```
7) Now **master-1** has become *inoperative*. The kubectl command fails as below
```
The connection to the server 20.72.201.152:6443 was refused - did you specify the right host or port?
The connection to the server 20.72.201.152:6443 was refused - did you specify the right host or port?

```
#### What you expected to happen:
Expect master-1 to run healthy as single master control plane (just as before master-2 joined).

#### How to reproduce it (as minimally and precisely as possible):
Steps in details above

#### Environment:
- Kubernetes version (use `kubectl version`):
```
- Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
remanava@CO4AEAP000105C2:~$ sudo cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel (e.g. `uname -a`):
`Linux CO4AEAP000105C2 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
/area kubeadm
/sig cluster-lifecycle
kubeadm runs a single etcd instance on the first control plane node (`kubeadm init`) unless you provision etcd yourself.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/

**Comment by renukamanavalan** [comment]
Yes, Init brought in the first instance of etcd, in master**-1**
When master**-2** joined, the second instance started.

I could see messages like "leader changed"

When I remove master**-2** (the node that joined) using `delete node`, in master**-1**, I could still see "leader changed" messages spewing periodically, though `kubectl get nodes` lists only one node.

Later when I intentionally remove /etc/kubernetes dir and rebooted the master-**2**, master-**1** become inoperative.

**Comment by pacoxu** [comment]
I think you can refer to #74112 or https://stackoverflow.com/a/60297375/1926952.

The correct way to delete a master node with kubeadm would be `kubeadm reset`. It will call etcd member remove as #74112.

If you use `kubectl delete node`, the etcd member is still in the etcd cluster. The StackOverflow link may help.

> - Remove the control-plane IP from the kubeadm-config CM ClusterStatus
> - Remove the etcd member using etcdctl
> - Delete the Node object using kubectl (if you don't want the Node around anymore)
> from  https://stackoverflow.com/a/60297375/1926952

**Comment by renukamanavalan** [comment]
Thanks a lot Paco. I will try your suggestion.

Just one more consultation request. 

I am running my master node VM in managed environment. 

1. Say I have 5 VMs running as **master nodes** in control-plane cluster.
    The etcd cluster will have all 5 node names as master nodes

2. A VM could get deleted & re-created anytime, but using same node name. 
    The VM got re-imaged, so it lost all its context, **but the etcd cluster will still have this node name** (from step1) as "not ready"

4. Attempt to re-join will fail as a node by same name exists. The `kubeadm reset` will not help either, as there is no local data or context.

Question:
Before join, do I try to delete the node by same name ?

**Comment by pacoxu** [comment]
For me, I use `kubectl exec` or `docker exec` to the etcd pod/container
```
# docker exec -it adfa3f4db6d5 sh
sh-5.0# export ETCDCTL_CACERT=/etc/kubernetes/pki/etcd/ca.crt
sh-5.0# export ETCDCTL_CERT=/etc/kubernetes/pki/etcd/peer.crt
sh-5.0# export ETCDCTL_KEY=/etc/kubernetes/pki/etcd/peer.key
sh-5.0# etcdctl member list
dc543c4d307fadb9, started, daocloud, https://10.6.177.40:2380, https://10.6.177.40:2379, false
sh-5.0#
```

- `etcdctl member list` to show the member id
- `etcdctl member remove <memberID>` like dc543c4d307fadb9 (remove unused members)
- If you have 5 master nodes, etcd cluster would be healthy with  3  healthy nodes.

**Comment by neolit123** [comment]
thanks @pacoxu for providing help in this support ticket.
@renukamanavalan yes, you have to use kubeadm reset that removes a member or you have to remove it manually using etcdctl.

closing this, but feel free to ask more questions.
/close

**Comment by renukamanavalan** [comment]
One more question.

First my THANKS to Paco & Lubomir!

In my second scenario, where a re-imaged VM attempting to join (_as master_) using same node name as it had before re-imaging, could I simply delete the node (`kubectl delete node`) and  then join (`kubeadm join ...`)

**Comment by neolit123** [comment]
the etcd members have storage on a VM, but even if you delete this storage and whole VM, the etcd member has to be deleted using etcdctl from the etcd cluster.

**Comment by renukamanavalan** [comment]
Thanks Lubomir!

Will "kubeadm reset" work from a re-imaged VM that has no locally available data ?

**Comment by neolit123** [comment]
i would not work, since the VM would not have the admin.conf or certificates on disk required to connect to the k8s / etcd clusters.
you should try the etcdctl commands that @pacoxu gave.

**Comment by renukamanavalan** [comment]
FYI: For automated scenarios, I prefer not to have the need to get into other VMs. So I am trying to look for other possibility,

Question: (_hopefully last_)
I could manually copy in /etc/kubernetes/admin.conf and /etckubernetes/pki/* files into this re-imaged VM.

With those **files in place,** will running `kubeadm reset" from this re-imaged VM could work ?

**Comment by neolit123** [comment]
it should in theory, but i haven't tried something like that.

you should make sure to call `kubeadm reset` before deleting control-plane VMs...

**Comment by renukamanavalan** [comment]
THANK YOU Lubomir!!

I will make sure to add my findings & resolve to this thread

**Comment by renukamanavalan** [comment]
Agree with solution provided above.

kubeadm reset -f, followed by a sleep for a minute, before join helps. The sleep/pause give time for the cluster to mark the node as "not ready". Attempt to join, after that state is reached, is clean.

THANK YOU all!
