### ISSUE TITLE
github.com/BurntSushi/toml is unmaintained

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100602]
we have a transitive dependency that is unmaintained - https://github.com/BurntSushi/toml we don't use it directly but definitely a longer term concern. Alternative seems to be https://github.com/pelletier/go-toml

![image](https://user-images.githubusercontent.com/23304/112739106-6c712c80-8f3f-11eb-9d37-54b31b0e60cb.png)

**Comment by BenTheElder** [comment]
regarding alternatives: 
https://github.com/kubernetes-sigs/kind/blob/83b25fd2085e06f9deffbf70010733f3b2fb45d7/pkg/cluster/internal/patch/toml.go#L91-L94

also worth noting: https://github.com/containerd/containerd/blob/1b05b605c860e3052dc2fb298fcf98987f9a811d/go.mod#L6
(we should probably file an issue there too?)

**Comment by BenTheElder** [comment]
https://pkg.go.dev/github.com/pelletier/go-toml#Marshal may make it difficult for projects to switch.

caddy seems to be using https://github.com/naoina/toml but that has a single release in 2017

https://github.com/caddyserver/caddy/blob/b54fa4123975195c721ff5a5c0b43c4622009676/go.mod#L18

**Comment by adisky** [comment]
containerd is moving to `https://github.com/pelletier/go-toml` 
ref: https://github.com/containerd/containerd/pull/5278

**Comment by BenTheElder** [comment]
is it unmaintained? https://github.com/BurntSushi/toml/issues/272 => things are merging
