### ISSUE TITLE
DualStack Node only appears to receive IPv4 InternalIP

### ISSUE THREAD

**Issue by jjschwarz** [kubernetes/kubernetes#100675]
#### What happened:

I used kubeadm to deploy Kubernetes v1.20.5 to a dual stack CentOS v7.9 host with the command:

kubeadm init --upload-certs --feature-gates IPv6DualStack=true

During the initialization I noticed that it issued certificates for the IPv4 address, the IPv4 loopback and the IPv6 loopback address.  After initialization
the command:

kubectl get nodes k8s-1.devtest.bugs.net -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'

from https://kubernetes.io/docs/tasks/network/validate-dual-stack/ only returns back an IPv4 InternalIP.  I have validated that the DNS server and host both see IPv6 fine.

I went ahead and deployed Calico with IPv6 enabled and the pods are able to actually get outbound on IPv4 and IPv6, however if I attempt to deploy any service with IPv6 enabled via the spec.ipFamilies
I receive back the error:

spec.ipFamilies[0]: Invalid value: []string(nil): ipfamily IPv6 is not configured on cluster

I created another single node test cluster using the same setup just to test this out, but right now I am seeing the exact same issue.  

I can confirm that Calico is working with IPv6 just fine.  I have IPv6 BGP traffic, and pods can talk on IPv6 with each other.

It appears this issue is affecting the NodePort bindings and the node itself.

#### What you expected to happen:
I expect the command:
kubectl get nodes k8s-1.devtest.bugs.net -o go-template --template='{{range .status.addresses}}{{printf "%s: %s \n" .type .address}}{{end}}'

to return both an IPv4 and IPv6 address per the information at 
https://kubernetes.io/docs/tasks/network/validate-dual-stack/

#### Environment:
- Kubernetes version (use `kubectl version`):
-  kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Virtual machine running on VMware 7.0U2

- OS (e.g: `cat /etc/os-release`):
 cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux k8s-test.bugs.net 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:08:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Network plugin and version (if this is a network-related bug):
Calico 3.14

**Comment by pacoxu** [comment]
Refer to https://github.com/pacoxu/website/blob/5a6c4244c44b3d3e474f62731919ec0d2637518c/content/en/docs/setup/production-environment/tools/kubeadm/dual-stack-support.md

The document is targeting 1.21 and it can be used for 1.20 with DualStack feature gate on. 

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "10.100.0.1"
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: 10.100.0.2,fd00:1:2:3::2
```

Node IP dual-stack can be configured in nodeRegistration.kubeletExtraArgs. It will configure `kubelet --node-ip` with both ipv4 and ipv6 IPs.

**Comment by jjschwarz** [comment]
OK, trying to make sure I don't miss anything here...but we seem to have two examples (command line and YAML) which have slightly different information in your example.  So my questions are:
1. The command line version doesn't specify any of the node information (just the pod and service networks).  Is the node information for kubelet and the API ncessary, or is that optional?
2. I assume based on your example that we must provide a pod and service network in the init and not let kubeadm just use the defaults?
3.

**Comment by jjschwarz** [comment]
Testing on the full cluster shows that it works just fine with the manually declared pod network and service cidr blocks.  
Thank you!
