### ISSUE TITLE
Misleading events show warnings but no positive affirmation when the warning is corrected

### ISSUE THREAD

**Issue by zenbones** [kubernetes/kubernetes#100682]
When getting a description of relevant events, for example this from 'kubectl describe pdb <name>'...

```
Events:
  Type    Reason  Age                From               Message
  ----    ------  ----               ----               -------
  Normal  NoPods  50m (x5 over 52m)  controllermanager  No matching pods found
```

This information is good to know. The fact is that it has been corrected. In the same report, just above it...

```
Name:           absolute-epicenter-arch
Namespace:      default
Min available:  1
Selector:       app.kubernetes.io/instance=absolute,app.kubernetes.io/name=epicenter-arch,app.kubernetes.io/part-of=epicenter
Status:
    Allowed disruptions:  0
    Current:              1
    Desired:              1
    Total:                1
```

And an attempt to drain the node yields...

```
evicting pod default/absolute-epicenter-arch-dwms6
error when evicting pod "absolute-epicenter-arch-dwms6" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
```

So, all is well, and the pod has been found by the PDB and appropriately protected. It would be great of there were and event in the event list saying that the pod had been found.

I've found the same issue with probes (startup, liveness) where the failure of the http endpoint shows up in the events when describing a pod, but the later working http call (even though the pods status and http logs conform a successful event) is not in the events when describing the pod.

It would be nice to have positive confirmations when non-working events are recovered from rather than having to check and search and wonder if you're missing something.

#### Environment:
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by liggitt** [comment]
I don't think this is specific to PDBs

**Comment by zenbones** [comment]
It's not specific to PDBs, I see the same issue in probes (startup and licenses anyway).

David Berkman

________________________________
