### ISSUE TITLE
CNI: loopback adapter gets state set to down due to PID recycling

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#100648]
#### What happened:
I have been chasing a bug where the `lo` interface on our kube nodes periodically gets its state set to down and causes all sorts of havoc on the node and I have finally come to the conclusion that it is due to PID recycling. Today I finally diagnosed this after I compiled many different logs on the system and noticed the PIDs wrap around 

#### What you expected to happen:
Kubernetes and CNI should never mix up network namespaces due to PID recycling. This failed for us on the `lo` interface in the host's namespace, but could have also happened for non-loopback plugins had other namespaces been mixed up.

#### How to reproduce it (as minimally and precisely as possible):
I don't have a great reproducer, however, the CNI DEL command for the loopback plugin is very happy to delete a loopback interface in the host namespace with a command like:
```
echo '{"cniVersion":"0.2.0","name":"cni-loopback","type":"loopback"}' | CNI_COMMAND=DEL CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin CNI_NETNS=/proc/1/ns/net /opt/cni/bin/loopback
```
On our servers, `kernel.pid_max = 100000` but most modern distributions default to something like 4,194,304 so we're just behind the times on that setting on our internal distro. That makes this problem reproduce far more quickly, especially since our build system also heavily employs this cluster and build systems very rapidly create processes.

If we were to increase that setting, this case would become much less probable, however, it would not be impossible.

#### Anything else we need to know?:
I found a similar bug on OpenShift's bug tracker here: https://bugzilla.redhat.com/show_bug.cgi?id=1754154
It links to a related issue here: https://bugzilla.redhat.com/show_bug.cgi?id=1754638
And it appears that they solved this with a quick hack which just deletes the body of the loopback interface's DEL operation: https://github.com/openshift/containernetworking-plugins/pull/15/files

#### Environment:
- Kubernetes version (use `kubectl version`): 1.17.17
- Cloud provider or hardware configuration: EC2
- OS (e.g: `cat /etc/os-release`): N/A (internal)
- Kernel (e.g. `uname -a`): 5.4.20-hs779 (internal kernel)
- Install tools: internal
- Network plugin and version (if this is a network-related bug): CNI 0.7.1 for the loopback plugin. We have an internal CNI plugin on our hosts that handles everything end-to-end other than the stuff that is built-in to kubelet like loopback.

---
To fully solve this problem, I wonder if kubelet should be making use of pinned network namespace bind mounts rather than using the PID-based path to the container's network namespace. This would resolve the issue because the netns bind mounts outlive all pids in them exiting, and the bind mount is mounting a specific netns's inode rather than something like a symlink to a PID's netns path. This seems like a fairly easy fix that would not require any changes in any CNI plugins (unless they currently try to parse the PID out of the netns path or something).

Actually, after typing all of that, I followed up on all the links to that openshift PR and it looks like that's how this was solved for cri-o too: https://github.com/cri-o/cri-o/pull/3048

**Comment by BenTheElder** [comment]
Are you using dockershim? You mention a cri-o fix but not how Kubernetes comes into play here.

**Comment by PaulFurtado** [comment]
Ah yeah, I thought I mentioned docker in the issue but I see that I missed that. Yes, this is with dockershim, so kubernetes is referencing namespaces by PID.

So a simple fix with dockershim could be for kubelet to reference the netns via the `NetworkSettings.SandboxKey` of the infra container, excerpt from `docker inspect`:
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "34c5f70f81b377545c91069f5b2eaeaedff422ea6b20c4e27f3ae621f9b7de3c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/34c5f70f81b3",
            ...
```

However, might this also be a problem for runtimes other than docker, like containerd?

**Comment by squeed** [comment]
I actually discovered the same bug in CRI-O a few years ago and wrote a blog post about it: https://www.caseyc.net/home/localhost-special-1/

CNI itself can do nothing; it takes the namespace path as passed. If we were maintaining Dockershim, I'd say we should properly bind-mount the netns. But since this is all going away (both dockershim and, more immediately, the container), we can just stop tearing down loopback.

**Comment by BenTheElder** [comment]
cc @dims @mikebrow

**Comment by PaulFurtado** [comment]
@squeed I actually linked your PR above and read that blog a bit after posting this! :smile:

I made the same tweak to the loopback plugin in our infrastructure, but this can just as easily happen with any other type of network plugin. Here's a random example in a plugin we used to use: https://github.com/lyft/cni-ipvlan-vpc-k8s/blob/1afdba72a7f5dca9f51666792a7769f0cfca2a51/plugin/unnumbered-ptp/unnumbered-ptp.go#L535-L608
I'm sure many plugins are similarly stateless. In that case, the plugin's teardown will look for interfaces in the namespace by specific name, like eth0 or veth0 and then will tear down the interfaces and return their IPs into IPAM, etc purely based on what is present in the namespace. The issue you and I both faced here affected the host namespace the most, however, if some other pod on the node is cycling through PIDs quickly then the PID collision can just as easily be another pod, likely configured by the same CNI plugin, and then the CNI plugin will tear down the interfaces in the wrong namespace.

I realize that dockershim is no longer maintained, but given that any runtime is able to make this mistake (especially if they followed dockershim as being the first example), any CNI plugin can be very negatively impacted by this, and users would have a really hard time tracking it down, it may really be useful to have kubelet just pin the namespace. It'd even be a useful kubernetes feature for other integrations if it pinned pod network namespaces at a well-known path. Short of that, maybe the the CRI validation tests could catch runtimes that return the netns via the PID-based paths to prevent other runtimes from making this mistake.

We run a few thousand kube nodes and have used various network plugins as the ecosystem has evolved and I feel like I've debugged network namespace confusion issues many times over the years where pod's network interfaces would randomly go missing. So much so that at some point, I rewrote an ipvlan-based CNI plugin in-house with tons of sanity checks and audit logging of every netlink call so that I could track down issues like this if our own plugin ever made such a mistake.

I feel like issues like this may be occurring for a lot of people out there, but redundancy among their pods causes it to go overlooked as a "random node network problem in the cloud", or worked around by health checks.

**Comment by thockin** [comment]
@squeed @dcbw It's not clear to me if this is a bug in kubernetes or a potential-bug in containerd or a documentation issue?

**Comment by squeed** [comment]
@thockin this is a dockershim bug - it needs to stop passing pid/ephemeral namespace paths to CNI.

**Comment by dims** [comment]
@squeed is there proposed patch somewhere?

**Comment by dcbw** [comment]
@thockin it's a bug in dockershim technically; but given this has existed since the beginning of time, and dockershim is going away. Also making sure kubelet upgrades do the right thing with already running could be error-prone. I'm not sure it's worth solving?

**Comment by fawadkhaliq** [comment]
> I feel like issues like this may be occurring for a lot of people out there

We saw this under similar conditions described above. The summary captured here [1] pretty much sums up what we discovered

[1] https://www.caseyc.net/home/localhost-special-1/

**Comment by thockin** [comment]
Next steps here?

**Comment by BenTheElder** [comment]
Followed up previously in #sig-node and we have https://github.com/containerd/containerd/issues/5630 for containerd, given https://github.com/kubernetes/kubernetes/issues/100648#issuecomment-820740450 I don't think we're fixing dockershim, so probably we can close this one.

**Comment by dcbw** [comment]
Yeah, not dockershim. CRIO and containerd are covered and that should be good.
/close
