### ISSUE TITLE
Shouldnt be returning etcd errors

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#10064]
As discussed with @bgrant0607, we return etcd error as is if update fails: https://github.com/GoogleCloudPlatform/kubernetes/blob/5520386b180d3ddc4fa7b7dfe6f52642cc0c25f3/pkg/api/errors/etcd/etcd.go#L48. All other functions except InterpretUpdateError() are fine.

Also, we shouldnt be checking resourceVersion while updating in the apiServer: https://github.com/GoogleCloudPlatform/kubernetes/blob/4fdcbc3096432692ee27c8d3f7e85580b29f780c/pkg/registry/generic/etcd/etcd.go#L302. We should let etcd do the conflict check.

**Comment by bgrant0607** [comment]
See also #10031

**Comment by bgrant0607** [comment]
And #1990

**Comment by bgrant0607** [comment]
We should log unexpected etcd errors (at a suitably high verbosity level).

**Comment by bgrant0607** [comment]
Also the case from #10031 reported by @smarterclayton :
The events REST storage object is not using generic.Etcd, and it's not wrapping the returned errors from etcd with the appropriate `pkg/api/errors/etcd` handles.  As a result, we return raw etcd errors to clients which leaks server information (security) and is also ugly.

Spawned from https://github.com/openshift/origin/issues/3196

**Comment by bgrant0607** [comment]
The general issue is #1990

**Comment by bgrant0607** [comment]
The etcd errors were previously noted there: https://github.com/GoogleCloudPlatform/kubernetes/issues/1990#issuecomment-93606822

**Comment by bgrant0607** [comment]
Can this be closed?

**Comment by smarterclayton** [comment]
I had a comment about the linked change - I would have preferred not to change etcd/error like this because it changes error filtering cases.

**Comment by nikhiljindal** [comment]
Fixed by https://github.com/GoogleCloudPlatform/kubernetes/pull/10246

**Comment by nikhiljindal** [comment]
Verified that all rest handlers call writeNegotiated() which calls errToAPIStatus: https://github.com/kubernetes/kubernetes/blob/21455ab776faf3a257927e6fb3771e97fd4206cf/pkg/apiserver/apiserver.go#L423, so we never return raw etcd errors outside the apiserver.
