### ISSUE TITLE
Consider: remove node-port conflict prevention in kube-proxy and kubelet

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#100643]
Background:  Kube-proxy (https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1099-L1128 https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/iptables/proxier.go#L1259-L1292  bernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1440-L1478 https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/proxier.go#L1253-L1281) and kubelet (https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockershim/network/hostport/hostport.go#L79-L119) try to be clever when installing iptables port-forward rules.  They open() the same port and leave it open, the idea being to prevent any subsequent app from trying to use that port (which won't work because iptables resolves first).

This is not-insignificant amount of code, which has had bugs in the past.  More importantly it has bugs NOW.  For one, we still go ahead and install a port-forward even if we could not bind.  Also dockershim doesn't resume this after a restart (https://github.com/kubernetes/kubernetes/issues/42960) and as dockershim dies, the CNI equivalent of this doesn't even try.  Lastly, if kube-proxy or kubelet dies, the "other" process can steal the port.

To solve this properly we would really need either an out-of-process agent which manages blocked ports or a kernel API to do it without a living process.

The ROI of this seems relatively limited.

So I propose that we consider just removing all of this logic.  It's of dubious value and inconsistent and unreliable anyway.

@aojea 

xref #100599

**Comment by uablrek** [comment]
Would it be possible to use eBPF and create a filter that blocks bind on the node-port range?

I have not worked with eBPF myself and may be over estimating it's magic powers. Perhaps some Cilium guy can advice? They have written the best eBPF description I have read; https://docs.cilium.io/en/v1.9/bpf/

**Comment by fristonio** [comment]
Hey @uablrek 
Yeah, we have something similar for Cilium already where we block `bind{4,6}` for NodePorts(https://github.com/cilium/cilium/pull/9880/).
I believe at this point we don't have any eBPF infrastructure in the proxy though? It will be interesting to see how we can bring eBPF to the proxy.

**Comment by uablrek** [comment]
> To solve this properly we would really need either an out-of-process agent which manages blocked ports or a kernel API to do it without a living process.

Perhaps an out-of-process agent may be the best first approach.

**Comment by aojea** [comment]
> So I propose that we consider just removing all of this logic. It's of dubious value and inconsistent and unreliable anyway.

I agree with you about that the port-holding logic, but after discussing it with @danwinship , I couldn't stand against the argument that is a real threat, more or less likely, but that the port-forwarding can steal a process port is real.

> To solve this properly we would really need either an out-of-process agent which manages blocked ports or a kernel API to do it without a living process.

That seems like a nice and easy project and covers both kubelet and kube-proxy, can we adopt it in sig-network? I'm bad with names, something like port-conflict-agent ....
I volunteer for that project, it will be similiar to the https://github.com/kubernetes-sigs/ip-masq-agent

**Comment by uablrek** [comment]
> a kernel API to do it without a living process.

I like the "without a living process" approach. As I understand a eBPF filter can stay in the kernel after the program that loaded it has terminated. Right?

It would be good to have a run-once command executed as a part of K8s startup like;
```
block-bind --range=30000-32767
```

**Comment by danwinship** [comment]
Should this be a KEP?

We need a list of criteria. eg

1. It's not possible for two Services to claim the same NodePort? (I think this is already guaranteed by the apiserver independently of the port opening.)
2. It's not possible for two Pods on the same node to claim the same HostPort? (I think this is already guaranteed by the scheduler independently of the port opening.)
3. It's not possible for an "untrusted" Pod to use HostPort to steal a port from a system service or hostNetwork pod? (For some definition of "untrusted". You can do this with PodSecurityPolicies.)
4. It's not possible for _any_ Pod to use HostPort to steal a port from a system service or hostNetwork pod?

like, I think if we get rid of the port opener then that means we can't have 4, but if we don't have 4, then why should we have 2?

**Comment by thockin** [comment]
IIRC The dockershim implementation of hostPorts will NOT install the port-forward if it can't also open the port and will fail to start the pod.  I do not know if the CNI equivalent will do that?  This is the real risk vector - someone claims hostPorts that attack the node daemons.

Kube-proxy merely complains about it but proceeds anyway.  I don't think it's OK to do otherwise - we don't really have a notion of a Service failing to start, especially just on some nodes.  This seems OK to me, since the nodePort range is supposed to be explicitly set aside for k8s to allocate from.

 I'm not against doing something smarter here, but let's think of the attack vector and see if that really closes it.  Suppose I write a pod that claims hostPort 22.  It gets scheduled but it can't open that port, so the pod fails to start.  Now I attack the real sshd and cause it to crash (OOM or something).  My pod can win the race and claim 22 before sshd restarts.  Is that acceptable?  Thenceforth, sshd can't start.

The only way to defend that is to have every system agent "earmark" their port somewhere so it can not be allocated.  If we had THAT, would we still need the port opener?

Are there better answers (other than "don't use hostPorts" and "don't collide with nodePorts")?

**Comment by danwinship** [comment]
> IIRC The dockershim implementation of hostPorts will NOT install the port-forward if it can't also open the port and will fail to start the pod. I do not know if the CNI equivalent will do that? This is the real risk vector - someone claims hostPorts that attack the node daemons.

The CNI equivalent does not do port opening at all, because it just exits after setting up the iptables rules, so even if it opened the port it would just close it immediately afterward...

> Kube-proxy merely complains about it but proceeds anyway. I don't think it's OK to do otherwise - we don't really have a notion of a Service failing to start, especially just on some nodes. This seems OK to me, since the nodePort range is supposed to be explicitly set aside for k8s to allocate from.

Yeah, NodePorts without port opening seem mostly unproblematic as long as
  1. the administrator doesn't do something "ill-advised" like set the nodeport range to `0-65535` so that they can create a service with `nodePort: 80`
  2. the nodeport range doesn't overlap the kernel ephemeral port range, so you don't have to worry about accidental conflicts with `net.Listen("tcp", ":0")`. (Of course, no one can reliably validate this since you'd have to validate it on each node, but only the apiserver actually knows what the nodeport range is.)
  3. you aren't concerned about nodeport-vs-hostport conflicts, either because you've restricted hostport usage to users you trust or because you've restricted hostport usage to a non-overlapping port range

> I'm not against doing something smarter here, but let's think of the attack vector and see if that really closes it. Suppose I write a pod that claims hostPort 22. It gets scheduled but it can't open that port, so the pod fails to start. Now I attack the real sshd and cause it to crash (OOM or something). My pod can win the race and claim 22 before sshd restarts. Is that acceptable?

If you have a threat model where there are users who are permitted to create a Pod that says `hostPort: 22` but who should not actually be allowed to steal that port from sshd, then presumably you wouldn't consider this outcome acceptable. But in that case it seems like it would be better to use pod security policy (-ish) to prevent people from creating the pod in the first place. (I don't think there's a strong argument for "I need to be able to prevent people from claiming hostPort 22 even if they're not bound by pod security policy" because an unrestricted attacker can just create a privileged hostNetwork pod rather than sneaking around with hostPorts.)

> Are there better answers (other than "don't use hostPorts" and "don't collide with nodePorts")?

"Don't use hostPorts" seems like a good answer in general, though I'm not sure how many real-world clusters could use that. "Heavily restrict hostPorts if you can't just disable them" seems like it needs to be part of the final answer.

**Comment by danwinship** [comment]
> More importantly it has bugs NOW. For one, we still go ahead and install a port-forward even if we could not bind. Also dockershim doesn't resume this after a restart (#42960)

Hm... kubelet/dockershim also doesn't recreate the hostport iptables rules if they get deleted (either while kubelet is running, or after a restart).

**Comment by thockin** [comment]
There are good comments here, which I think I agree with overall.

If you don't trust your users to use arbitrary hostPorts, you should be controlling that via policy.  But we don't have a good way to do policy "in the box".

The current checks we have for nodePorts are pretty pointless, since we capture the ports anyway, and we know ~nobody looks at logs unless something goes wrong.

The current checks we have for hostPorts are not pointless, but are pretty broken (and will be less utilized as dockershim dies).

If we had an out-of-band way to lock down the nodePorts range (so apps can't bind() them) that would be good.

We still lack a simple way to govern hostPort usage.

If we do nothing, the hostPorts logic for this will "go away on its own" as dockershim is EOL'ed.

The question then is whether the nodePorts logic is a) useful enough to keep; b) compelling enough to try to do something better; c) something we should require all implementations of kube-proxy-equivalents to implement?

**Comment by aojea** [comment]
> We still lack a simple way to govern hostPort usage.

Seems we are going to have one :)
https://github.com/kubernetes/enhancements/pull/2582/files#r611099615

> The question then is whether the nodePorts logic is a) useful enough to keep; b) compelling enough to try to do something better; c) something we should require all implementations of kube-proxy-equivalents to implement?

> Yeah, NodePorts without port opening seem mostly unproblematic as long as

I did a quick search about modifying nodeport ranges and it shows a lot of hits that may indicate that people is not going to use safely 

> If we had an out-of-band way to lock down the nodePorts range (so apps can't bind() them) that would be good.

This is the same that with clusterIP ranges, we don't expose these configuration parameters, if thise will be exposed we can left it to the services implementation to lock down that range and improve our current kube-proxy one ...

**Comment by danwinship** [comment]
> If we do nothing, the hostPorts logic for this will "go away on its own" as dockershim is EOL'ed.

Oh, hm, I don't think I answered quite what you meant when you asked about "the CNI equivalent" before.

There are three possibilities, not two:

1. dockershim
2. CRI with an implementation that implements HostPorts natively (eg, cri-o)
3. CRI with an implementation that does not implement HostPorts natively, but converts the CRI HostPort data to the form used by [the CNI portmap plugin](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) so you can chain that (eg, containerd)

when I said that "The CNI equivalent does not do port opening at all", I meant the CNI portmap plugin. But if you're using cri-o, it implements hostports just like dockershim does (and will keep doing so when dockershim goes away).
