### ISSUE TITLE
[Flaking-test] Kubernetes e2e suite.[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] listing validating webhooks should work [Conformance]

### ISSUE THREAD

**Issue by sladyn98** [kubernetes/kubernetes#100760]
#### Which jobs are flaking:

kubeadm-kinder-latest

#### Which test(s) are flaking:

AdmissionWebhook [Privileged:ClusterAdmin] should mutate pod and apply defaults after mutation [Conformance] 

#### Testgrid link:

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest&width=20

#### Reason for failure:

```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
Apr  1 07:33:00.835: waiting for webhook configuration to be ready
Unexpected error:
    <*errors.errorString | 0xc0002b8240>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1055
```

#### Anything else we need to know:

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%20listing%20validating%20webhooks%20should%20work%20

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1377337478465196032
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1377398378459041792
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1377520176924200960

/sig api-machinery

**Comment by thejoycekung** [comment]
/sig api-machinery

Thanks for logging this @sladyn98 ! I've added it to the CI Signal board as well.

**Comment by jpbetz** [comment]
The vast majority of failures (212 of 223) are from kops tests:

```
136 e2e-kops-gce-stable ►
 76 e2e-kops-gce-latest ►
 9 ci-kubernetes-e2e-kubeadm-kinder-latest ►
 1 ci-kubernetes-e2e-kubeadm-kinder-kubelet-1-19-on-latest ►
 1 ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-20 ►
```

The failing kops test runs have a wide range of timeout related failures, e.g.: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-stable/1377594167231778816

/sig-remove api-machinery
/sig cluster-lifecycle

**Comment by neolit123** [comment]
cc @kubernetes/kops-maintainers 
pinged #kops-devs on slack as well.

maybe this is the temporal non-QoS Prow cluster problem?

**Comment by neolit123** [comment]
...but i'm not seeing the same flakes on the 1.20 branch in this job:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-1-20

both kubeadm-kinder-1-20 and kubeadm-kinder-latest run in the same Prow cluster.
so this might be an actual problem.

**Comment by thejoycekung** [comment]
at @neolit123's advice I went and checked some of the jobs that also run in the `k8s-infra-prow-build` cluster and run this test, and they seem to be green:
- [Conformance - GCE - master - kubetest2](https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2&include-filter-by-regex=AdmissionWebhook)
- [conformance-ga-only](https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only&include-filter-by-regex=AdmissionWebhook)
- [gce-cos-master-default](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=AdmissionWebhook)
- [gce-ubuntu-master-containerd](https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd&include-filter-by-regex=AdmissionWebhook)

I saw a couple flakes for other AdmissionWebhook tests on the kind jobs, but nothing major.
... so hopefully *not* an actual problem in k8s / tests?

**Comment by neolit123** [comment]
> ... so hopefully not an actual problem in k8s / tests?

this seems like sufficient evidence to me.
we can leave these issues open and if the tests suddenly stop flaking it further confirms it.

**Comment by neolit123** [comment]
@mkorbi hi, i do not see this API machinery test flaking consistently in the kubeadm job:
> [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] listing validating webhooks should work [Conformance]

last flake was a single time on 6-22:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest&width=20

the flake tracked in https://github.com/kubernetes/kubernetes/issues/100787
is no longer present either.

**Comment by lambdanis** [comment]
There was a flake of `Kubernetes e2e suite.[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with pruning [Conformance]` yesterday: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1413083890691608576

The error was different than the originally reported one, but maybe it's the same issue:
```
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:87
Jul  8 11:01:22.445: waiting for the deployment status valid%!(EXTRA string=k8s.gcr.io/e2e-test-images/agnhost:2.32, string=sample-webhook-deployment, string=webhook-5244)
Unexpected error:
    <*errors.errorString | 0xc0026baee0>: {
        s: "error waiting for deployment \"sample-webhook-deployment\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"sample-webhook-deployment-78988fc6cd\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
    }
    error waiting for deployment "sample-webhook-deployment" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, Reason:"MinimumReplicasUnavailable", Message:"Deployment does not have minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, LastTransitionTime:v1.Time{Time:time.Time{wall:0x0, ext:63761338580, loc:(*time.Location)(0xa083940)}}, Reason:"ReplicaSetUpdated", Message:"ReplicaSet \"sample-webhook-deployment-78988fc6cd\" is progressing."}}, CollisionCount:(*int32)(nil)}
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:846
```

The same build had a flake of `task-07-e2e` with just:
```
exit status 1
```
I guess it's somehow related.

This issue looks like an exact duplicate of https://github.com/kubernetes/kubernetes/issues/100787 though, I think one of them should be closed.

**Comment by neolit123** [comment]
/sig api-machinery

if sig-apimachinery doesn't want to take action and loosening the test requirements, i don't think we should consider these problematic for 1.22. maybe this should be investigated in the future...

closing the duplicate:
https://github.com/kubernetes/kubernetes/issues/100787

**Comment by neolit123** [comment]
this is not flaking in other jobs, so arguably not a blocker.
/milestone clear

will ping #sig-apimachinery to check if they object to this milestone clear.
