### ISSUE TITLE
Can I use IP:PORT as external-ip of LoadBalancer Service?

### ISSUE THREAD

**Issue by Jiajing-Hu** [kubernetes/kubernetes#100744]
**Cluster information:**
Kubernetes version: 1.16.8
Cloud being used: bare-metal
Installation method: ansible
Host OS: centos7
CNI and version: calico 3.15
CRI and version: docker 18.09

**my question**
I create a new LoadBalancer with my own Loadbalancer server, which needs both ip and ports. So I wonder if I can save the port in 「external-ip」. is it illegal or not ?

_for example:_
```bash
kubectl get svc 
🌀   ~  kubectl get svc test-backend
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
test-backend   LoadBalancer   192.180.72.174   10.5.63.132:8080   8080:31235/TCP   3d1h
```

in other word, is it ok to save **IP:PORT** in `v1.Service.Status.LoadBalancer.Ingress.IP` ?

**Comment by neolit123** [comment]
hi, please use the support channels for questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/sig network
/kind support
