### ISSUE TITLE
Kubernetes bypasses external firewall ports on Hetzner and AWS

### ISSUE THREAD

**Issue by yashpanchalecosmob** [kubernetes/kubernetes#100781]
#### What happened:

We have been using freeswitch on kubernetes setup by dialing on port 5060 using a third party application for SIP calls.
Our config for kubernetes was at network mode host and default config was listening to udp 5060. 
Now after blocking all other ports except ssh on aws security groups we were still able to make calls to the server.
This same issue was repeated for Hetzner as well. We set up hetzner firewall allowing only ssh and blocking all other ports.

**Note:** We checked for firewall configuration multiple times to confirm it's validity using netcat and it was confirmed that the port was blocked. However whenever we used this third party application to make calls to the server using server's ip and port 5060 it bypassed the external firewall setup.

When we disabled the  kubelet on both servers and switched to docker-compose host network mode this issue was not produced.

#### What you expected to happen:

We expected the external firewalls to block the port but it was still open while we had kubernetes setup.

#### How to reproduce it (as minimally and precisely as possible):

1) Setup kubernetes cluster on two nodes.
2) Use the freeswitch image and create a sample deployment make sure it is on network mode host.
3) Make calls to the public ip of the node where the pod is deployed with port 5060 using microsip application.

#### Environment:
- Kubernetes version (use `kubectl version`): Kubernetes v1.20.5
- Cloud provider or hardware configuration: AWS Security Group and Hetzner
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`): 4.15.0-136-generic

**Comment by neolit123** [comment]
/remove-kind bug
/kind support
/sig network

i don't think external firewall is something that kubernetes can just bypass.
you might get more feedback on:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by yashpanchalecosmob** [comment]
> /remove-kind bug
> /kind support
> /sig network
> 
> i don't think external firewall is something that kubernetes can just bypass.
> you might get more feedback on:
> https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

Yes that is exactly what we thought but it seems that is does in this case.

**Comment by vincentmli** [comment]
@yashpanchalecosmob, if you could draw a simple network path diagram of the sip call path, and provide more kubernetes deployment details like pod, it could be useful, if you suspect there is networking issue in Kubernetes, I recommend iptables trace https://youtu.be/9HNKRP7x57M, it is very handy once you have clear picture what the packet path look like.

**Comment by jayunit100** [comment]
hmmm..  Since the definition of K8s is a cluster that passes the Conformance suite, id assume that this isnt a bug ~ i.e. your cluster is working, but your firewall isnt doing the right thing to *prevent* your cluster from doing certain things... ?

**Comment by thockin** [comment]
Can you be more precise about the firewall rule you installed?\
