### ISSUE TITLE
Regression: Multi-AZ Clusters test timing out in big clusters

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#100705]
From https://github.com/kubernetes/kubernetes/pull/98699#issuecomment-810916947

After #98699, Multi-AZ Clusters tests in 1.19 and 1.20 started timing out as createBalancedPodForNodes is extremely inefficient in scale: for each node (out of 5k), it lists all pods in a cluster serially (each list takes ~5s), which translates to ~7 hours.

Optimizing this function by listing pods once and then in memory by Spec.NodeName

/kind bug
/priority critical-urgent
/sig scheduling

**Comment by jkaniuk** [comment]
/reopen

```
May 17 08:53:40.150: INFO: Waiting for running...
May 17 08:53:45.217: INFO: Waiting for running...
May 17 08:53:50.340: INFO: Waiting for running...
May 17 08:53:55.400: INFO: Waiting for running...
...
May 17 11:30:08.220: INFO: Waiting for running...
May 17 11:30:13.285: INFO: Waiting for running...
May 17 11:30:18.348: INFO: Waiting for running...
May 17 11:30:23.409: INFO: Waiting for running...

---------------------------------------------------------
Received interrupt.  Running AfterSuite...
```

Looks that ComputeCPUMemFraction took only 12 minutes, but it stuck later, on `Waiting for running...`

It is scheduling one pod per each node: https://github.com/kubernetes/kubernetes/blob/release-1.21/test/e2e/scheduling/priorities.go#L567

Which is waiting 5s to be ready: https://github.com/kubernetes/kubernetes/blob/release-1.21/test/utils/runners.go#L905

5k nodes * 5s = ~7h

**Comment by alculquicondor** [comment]
/assign @damemi

Can you do the pod creations in parallel?

**Comment by damemi** [comment]
Yes, good idea. I'll update to do that
