### ISSUE TITLE
Dockershim deprecation side-effect : "kubenet" will be gone!

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100707]
Tracking issue for this ask from sig-network. When [dockershim will be removed](https://github.com/kubernetes/enhancements/issues/2221) from kubernetes/kubernetes, `kubenet` will be removed as well 

![image](https://user-images.githubusercontent.com/23304/113157689-20590d00-9209-11eb-8383-95c857b8128e.png)

[ ] - cleanup references in Kops and Kops jobs ( [here](https://cs.k8s.io/?q=kubenet&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra) and [here](https://github.com/kubernetes/kops/search?q=kubenet))
[ ] - cleanup k/k and k/test-infra (other than kops)
[ ] - Remove kubenet references from docs

/kind cleanup
/sig network
/sig node

**Comment by dims** [comment]
cc @thockin @aojea

**Comment by aojea** [comment]
Also, announced  on the sig-network mailing list Feb 1st
https://groups.google.com/g/kubernetes-sig-network/c/nW_1gYTqW_0/m/fKkl2oNGBQAJ 

@aramase I think that you also have some dependency in kubenet in some jobs IIRC

**Comment by dims** [comment]
thanks @aojea

**Comment by aramase** [comment]
@aojea that's right! We do have quite a few jobs running with kubenet. Thanks for the heads up.

**Comment by khenidak** [comment]
I know this sounds like a big deal but it is not. kubenet is using CNI components that live out side the tree in addition to route controller/node-ipam (both will remain). A simple wrapper for these CNI component can act as a replacement. I am not sure we need to have this as part of a kubernetes sig or not.

**Comment by dims** [comment]
@khenidak let's not add yet-another-CNI :) hoping this will nudge folks to switch to an existing one.

**Comment by BenTheElder** [comment]
@dims I think the point was moreso that if you want something that looks like kubenet you can have it very easily with standard CNI plugins and a straightforward CNI config .json

both kubenet and this configuration would be lacking all of the additional functionality in overlay networks but if you were fine with kubenet you will be fine with this instead of needing to migrate to calico/cillium/...

It's probably worth documenting this somewhere for users looking to migrate, I don't think it needs to be a "project" though. 

For now we have e.g. https://github.com/kubernetes/kubernetes/blob/a651804427dd9a15bb91e1c4fb7a79994e4817a2/cluster/gce/gci/configure-helper.sh#L2973-L2997

**Comment by aojea** [comment]
> For now we have e.g.

that is containerd kubenet replacement https://github.com/containerd/containerd/blob/master/docs/cri/config.md#cni-config-template

**Comment by aojea** [comment]
that is not what ip-masq-agent does? 
https://github.com/kubernetes-sigs/ip-masq-agent

**Comment by dims** [comment]
@BenTheElder Got it. thanks! it's enlightening to read this stuff, as i have no clue about networking :)

**Comment by justinsb** [comment]
I'd ask that we be very clear in our communication that we are removing the kubenet *flags*, but that the networking mode commonly known as kubenet remains fully functional.

The configuration steps have been moved from flags to a more manual configuration.  Specifically: cni template with the configuration @BenTheElder listed, and ip-masq-agent (or other ways of setting the `MASQUERADE` rules).

**Comment by thockin** [comment]
Who is "we" here and where do we need to be clear? :)

**Comment by justinsb** [comment]
I guess anyone writing something that might appear on twitter as attributed to the project - release notes, PR titles .. even issue titles  :smile:

**Comment by caseydavenport** [comment]
> removing the kubenet flags, but that the networking mode commonly known as kubenet remains fully functional.

I feel like that's not a fair characterization though. I think what's happening is we're removing kubenet, and that's OK. Users can easily build something themselves that mimics the way kubenet behaved if that's what they are into, but it's not really "kubenet" any more than Calico is kubenet.

I'm not really sure what the true definition of kubenet is and isn't, to be honest. Is it just bridge+host-local? What about ptp+host-local? Is kubenet actually just allocation of IP addresses based on Node.Spec.PodCIDR? If so then a lot of things could be considered kubenet (Calico included, for example).

Maybe I am missing the point, though.

**Comment by justinsb** [comment]
My concern is that we don't want users to think that the functionality commonly known as kubenet is in any way going to stop working.

kubenet is the MVP of networking plugins: use PodCIDRs instead of separate IP allocation; use infrastructure or host level routes such that pods can route to pods.

I believe most CNI providers have adopted this approach now - but we tried a number of other approaches along the way.

If you actually want to remove kubenet, let's have that discussion, but let's not conflate this with a dockershim discussion.

**Comment by neolit123** [comment]
we discussed this deprecation in the SIG CL meeting and agreed that we should be clear in release notes that this about removing flags and kubenet would continue to work after that.

**Comment by caseydavenport** [comment]
I would guess that for most users, "kubenet == the dockershim implementation", and I suspect users who see a release note stating the kubenet will continue to work will not expect that they now need to implement their own CNI network configuration and distribute it to all of their nodes.

**Comment by neolit123** [comment]
it seems appropriate to have docs explaining what actions the users need to take.
or as @justinsb mentioned, we could link to https://github.com/kubernetes/kubernetes/issues/100707#issuecomment-811518514

**Comment by caseydavenport** [comment]
> kubenet is the MVP of networking plugins: use PodCIDRs instead of separate IP allocation; use infrastructure or host level routes such that pods can route to pods.

@justinsb My point was that, by this definition, both Calico and Flannel (and probably others) are kubenet :) 

I think to users, kubenet is something more specific than that. Namely, it's the "built-in" networking option.

**Comment by justinsb** [comment]
How about we err on the side of caution, and be very explicit that we're removing the flags, and that users that want the equivalent behaviour can set it up using a CNI configuration - it likely suffices to link to https://github.com/kubernetes/kubernetes/issues/100707#issuecomment-811518514

**Comment by Random-Liu** [comment]
> kubenet is the MVP of networking plugins: use PodCIDRs instead of separate IP allocation; use infrastructure or host level routes such that pods can route to pods.

IIRC, one big difference between dockershim kubenet/containerd CNI template vs. Calico/Flannel is that:
1) dockershim kubenet / containerd CNI relies on kubelet to [pass it the pod CIDRs through CRI](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/kubelet_network.go#L59). 
2) Calico / Flannel retrieves that from the apiserver directly.

And the kubelet's behavior to pass pod CIDR [always runs no matter what kubelet network plugin is used](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/kubelet_node_status.go#L507).

As long as that behavior is kept, it should be fine to either deprecate/remove the kubenet implementation or flag.

However, I do agree with https://github.com/kubernetes/kubernetes/issues/100707#issuecomment-814291942 that we should clearly tell people who are using kubenet about the alternative in containerd and cri-o. In containerd, the CNI template was added specifically for this purpose https://github.com/containerd/containerd/blob/master/contrib/gce/cni.template

**Comment by dchen1107** [comment]
GKE still has some dependencies on kubenet today even we planned to get off it for a while. Just confirmed it with the engineering team internally.

**Comment by squeed** [comment]
@Random-Liu Why do you need to template in the PodCIDR? It should be valid to pass IP ranges as a CNI capablity arg - see https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#well-known-capabilities

**Comment by aojea** [comment]
> @Random-Liu Why do you need to template in the PodCIDR? It should be valid to pass IP ranges as a CNI capablity arg - see https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#well-known-capabilities

https://github.com/kubernetes/kubernetes/issues/77682

**Comment by BenTheElder** [comment]
@aojea do you maybe want to run https://github.com/kubernetes/kubernetes/issues/77682 by SIG node again? I think we should reconsider it perhaps

**Comment by aojea** [comment]
> @aojea do you maybe want to run #77682 by SIG node again? I think we should reconsider it perhaps

I don't know, that will depend on Node.Status.PodCIDR,  and that field is "controversial" at minimum :)

https://github.com/kubernetes/kubernetes/issues/57130

I never thought I would say this :smile: , but is not clear to me after these years that we should create this slippery slope between CNI and Kubernetes/Kubelet, right now CNI is CRI runtime business

**Comment by dims** [comment]
/sig network

Can someone from sig-network please help with documenting something since dockershim has been ripped off now?

**Comment by dims** [comment]
Re-opening as we haven't cleaned up docs  ( cc @sftim )

**Comment by sftim** [comment]
Thanks @dims

**Comment by hakman** [comment]
@dims I think https://github.com/kubernetes/kubernetes/pull/107096 is the last leftover of kubenet removal.

**Comment by jyotimahapatra** [comment]
@dims 👋 Im from the bug triage team. Wanted to check if there are other PRs needed to close this issue.

**Comment by dims** [comment]
all set. thanks @jyotimahapatra
