### ISSUE TITLE
kube-porxy.1.18.17  start BUG

### ISSUE THREAD

**Issue by qingsong-cn** [kubernetes/kubernetes#100773]
F0402 13:51:09.710069  126711 server.go:497] error loading config file "/opt/k8s/cfg/kube-proxy-config.yml": no kind "KubeProxyConfiguration" is registered for version "kubeproxy.config.k8s.io/v1alpha1" in scheme "k8s.io/client-go/tools/clientcmd/api/latest/latest.go:50"

cat kube-proxy-config.yml 
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
metricsBindAddress: 0.0.0.0:10249
clientConnection:
   kubeconfig: /opt/k8s/cfg/kube-porxy.kubeconfig
hostnameOverride: node-2
clusterCIDR: 10.2.0.0/16

**Comment by pacoxu** [comment]
The same error can be found only in https://github.com/kubernetes/kubernetes/pull/52198#issuecomment-353374993

Would you check the kube-proxy image version?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.9.md#network-1
> The API group/version for the kube-proxy configuration has changed from componentconfig/v1alpha1 to kubeproxy.config.k8s.io/v1alpha1. If you are using a config file for kube-proxy instead of the command line flags, you must change its apiVersion to kubeproxy.config.k8s.io/v1alpha1. (#53645, @xiangpengzhao)

**Comment by qingsong-cn** [comment]
> The same error can be found only in [#52198 (comment)](https://github.com/kubernetes/kubernetes/pull/52198#issuecomment-353374993)
> 
> Would you check the kube-proxy image version?
> 
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.9.md#network-1
> 
> > The API group/version for the kube-proxy configuration has changed from componentconfig/v1alpha1 to kubeproxy.config.k8s.io/v1alpha1. If you are using a config file for kube-proxy instead of the command line flags, you must change its apiVersion to kubeproxy.config.k8s.io/v1alpha1. (#53645, @xiangpengzhao)

 kube-proxy v1.18.17
I use  v1.18.17 Server binaries
Download it here
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md

**Comment by qingsong-cn** [comment]
> The same error can be found only in [#52198 (comment)](https://github.com/kubernetes/kubernetes/pull/52198#issuecomment-353374993)
> 
> Would you check the kube-proxy image version?
> 
> https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.9.md#network-1
> 
> > The API group/version for the kube-proxy configuration has changed from componentconfig/v1alpha1 to kubeproxy.config.k8s.io/v1alpha1. If you are using a config file for kube-proxy instead of the command line flags, you must change its apiVersion to kubeproxy.config.k8s.io/v1alpha1. (#53645, @xiangpengzhao)

thank you
I get 
systemd file   kube-proxy.service
I use --kubeconfig parameter，this is error
need --config

**Comment by neolit123** [comment]
> I use --kubeconfig parameter，this is error
> need --config

/close
/kind support
/sig network
