### ISSUE TITLE
Kubeproxy healthz port exposed to outside kubernetes cluster.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#100740]
#### What happened:
We've deployed k8s(1.16.3) using kubespray, and could see 10256(kube-proxy healthz port) is exposed to outside the cluster/k8s node and by default bind address is 0.0.0.0 which is all interface.

we tried changing 0.0.0.0 to localhost(127.0.0.1), and now port is closed from outside the cluster or k8s node.

1) Is this the right way?
2) Where we are using kube-proxy health check API? Is it by some other kube system service?

#### What you expected to happen:
Port shouldn't be expose to outside the cluster.

#### How to reproduce it (as minimally and precisely as possible):
Deploy k8s (1.16.3) and curl to the kube-proxy health check api from outside the k8s node.

#### Anything else we need to know?:
I think in higher version of k8s also, we have the same.

#### Environment:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`):
Linux localhost 4.14.151-OpenNetworkLinux #1 SMP Fri Mar 5 08:52:32 UTC 2021 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by SataQiu** [comment]
FYI: #44968

**Comment by neolit123** [comment]
> we tried changing 0.0.0.0 to localhost(127.0.0.1), and now port is closed from outside the cluster or k8s node.

https://pkg.go.dev/k8s.io/kube-proxy/config/v1alpha1#KubeProxyConfiguration

```
	// bindAddress is the IP address for the proxy server to serve on (set to 0.0.0.0
	// for all interfaces)
	BindAddress string `json:"bindAddress"`
	// healthzBindAddress is the IP address and port for the health check server to serve on,
	// defaulting to 0.0.0.0:10256
	HealthzBindAddress string `json:"healthzBindAddress"`
	// metricsBindAddress is the IP address and port for the metrics server to serve on,
	// defaulting to 127.0.0.1:10249 (set to 0.0.0.0 for all interfaces)
	MetricsBindAddress string `json:"metricsBindAddress"`
```

kubeadm uses the defaults for these, but you can override them by passing this configuration to kubeadm init:

```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
# config here
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
# config here
```

note that there is a separate HealthzBindAddress and BindAddress.
i recommend to only change HealthzBindAddress to localhost, but if you change BindAddress to localhost this means that, for example, you would bind NodePorts only to localhost of that node.

> Is this the right way?
> Where we are using kube-proxy health check API? Is it by some other kube system service?

external insecure health checks are mostly harmless, but you can bind healthz to localhost if you want.
for other components we have secured /healthz either on localhost by default or behind HTTPs.

maybe we should configure `HealthzBindAddress: 127.0.0.1` by default from kubeadm, but that might break users of these health check.

cc @MrHohn do you have feedback on this?

/sig network cluster-lifecycle

**Comment by jayunit100** [comment]
i think to follow up its worth a quick check to see if we can still pass conformance when nodeports only bind to 127 -- i assume not.  in that case, really the workaround here is a workaround only for special cases where theres a very high level of security required etc.

**Comment by MrHohn** [comment]
@neolit123 Thanks for the clarification. A quick comment is that we've been using kube-proxy's healthz endpoint as the health check target of the GCP network load balancer (service with `type=LoadBalancer`). I suspect a few other cloud provides may have a similar dependency. Defauling `HealthzBindAddress` to localhost might break the LB functionality in this case.

**Comment by neolit123** [comment]
understood @MrHohn ,

it might be too late change the kube-proxy default of HealthzBindAddress at this point.
i was wondering whether  we should change the value kubeadm passes to kube-proxy for HealthzBindAddress to localhost, but this will likely break users too.

@jayunit100 
>  thanks for differentiating those fields lubomir - so i think to follow up its worth a quick check to see if we can still pass conformance when nodeports only bind to 127 -- i assume not. in that case, really the workaround here is a workaround only for special cases where theres a very high level of security required etc.

yes, i agree. you can still check conformance if you'd like.

i will close this ticket, because the change on the sides of kube-proxy or kubeadm (when kubeadm manages kube-proxy) is breaking, and i don't see the security benefits.

/close
