### ISSUE TITLE
Not able to run podman in kubernetes pod if privilege field in security context is false even though user is root  

### ISSUE THREAD

**Issue by SahilChaudhary25** [kubernetes/kubernetes#100752]
#### What happened:
Not able to run podman in kubernetes pod if privilege field in security context is false even though user is root while setting privilege to true it is working fine in both root & non root

#### What you expected to happen:
Podman should be worked when privilege field in security context is false

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"5de7fd1f9555368a86eb0f8f664dc58055c17269", GitTreeState:"clean", BuildDate:"2021-01-18T09:31:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
   Azure
   
- OS 
- Linux

**Comment by neolit123** [comment]
i think this is a podman problem not a k8s problem, try the support channels first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if you confirm a bug open the issue again.

> Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0",

side note: your kubectl is much older than the server.

/sig node
/kind support
/close
