### ISSUE TITLE
"repomd.xml signature could not be verified for kubernetes" error when installing Kubernetes from yum repo on CentOS7

### ISSUE THREAD

**Issue by dkleissa** [kubernetes/kubernetes#100757]
#### What happened:
When attempting to install k8s from a yum repo on CentOS7, yum encounters the following error:

```https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes```

This discussion started in an existing closed issue that appears to be related: https://github.com/kubernetes/kubernetes/issues/60134#issuecomment-812013641

#### What you expected to happen:
Installation complete without error.

#### How to reproduce it (as minimally and precisely as possible):
This can be reliably reproduced in a Docker container:
```
docker run -it centos:centos7 /bin/bash
```

then 

```
cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF
```
```
yum list -y kubectl
```

Repeating this with `docker run -it centos:centos8 /bin/bash` works. 

Note in CentOS8 `gnupg2-2.2.20-2.el8` is installed instead of `gnupg2-2.0.22-5.el7_5`. In https://github.com/kubernetes/kubernetes/issues/60134 the solution seemed to be installing `gnupg2-2.0.22-5.el7_5`, so it is unclear what has changed.

#### Anything else we need to know?:

- This was working fine as of 6pm EDT on 2021-03-31
- We noticed first failures around 8am EDT on 2021-04-01
- If we compare a fresh install and an existing, recently installed node that is still up, the keys look different. Yum now seems to be failing on the "old" node as well.

Current output when installing:

```
kubernetes/x86_64/signature                                                                                                                                                        |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0xA7317B0F:
 Userid     : "Google Cloud Packages Automatic Signing Key <gc-team@google.com>"
 Fingerprint: d0bc 747f d8ca f711 7500 d6fa 3746 c208 a731 7b0f
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes/x86_64/signature                                                                                                                                                        | 1.4 kB  00:00:11 !!!
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.
```

output when trying yum commands on older, previously functioning node:

 ```
kubernetes/signature                                                                                                                                                               |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x307EA071:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2021-03-01-08_01_09.pub)"
 Fingerprint: 7f92 e05b 3109 3bef 5a3c 2d38 feea 9169 307e a071
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Is this ok [y/N]: y
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes/signature                                                                                                                                                               | 1.4 kB  00:00:17 !!!
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.
updates
```

#### Environment:
- Kubernetes version (use `kubectl version`): na
- Cloud provider or hardware configuration: Inside a docker container running in EC2 and on a laptop
- OS (e.g: `cat /etc/os-release`): CentOS7
- Kernel (e.g. `uname -a`): Linux node0 3.10.0-1160.15.2.el7.x86_64 #1 SMP Thu Jan 21 16:15:07 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dkleissa** [comment]
Also, when trying to manually verify `repomd.xml` it looks like 1) a new push happened at 8:13pm EDT, which is consistent with when we saw the failures begin, and 2) maybe the key has expired?

Running this:
```
curl -fsSL https://packages.cloud.google.com/yum/doc/yum-key.gpg | gpg2 --import
curl -fsSL -O https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml
curl -fsSL -O https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml.asc
gpg2  --verify repomd.xml.asc
```

Results in:

```
[root@71611ec163ec /]# gpg2  --verify repomd.xml.asc
gpg: Signature made Wed Mar 31 00:13:31 2021 UTC using RSA key ID BA07F4FB
gpg: Good signature from "Google Cloud Packages Automatic Signing Key <gc-team@google.com>"
gpg: Note: This key has expired!
Primary key fingerprint: 54A6 47F9 048D 5688 D7DA  2ABE 6A03 0B21 BA07 F4FB
gpg: Signature made Wed Mar 31 00:13:31 2021 UTC using RSA key ID 836F4BEB
gpg: Good signature from "gLinux Rapture Automatic Signing Key (//depot/google3/production/borg/cloud-rapture/keys/cloud-rapture-pubkeys/cloud-rapture-signing-key-2020-12-03-16_08_05.pub) <glinux-team@google.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 59FE 0256 8272 69DC 8157  8F92 8B57 C5C2 836F **4BEB**
```

**Comment by BenTheElder** [comment]
this is tracked in https://github.com/kubernetes/release/issues/1982

**Comment by dkleissa** [comment]
Per @BenTheElder's comment in the related ticket, it seems like key is fixed but the error will remain on CentOS7 and it is safe to disable the repo_check: https://github.com/kubernetes/release/issues/1982#issuecomment-812449935
