### ISSUE TITLE
e2e tests should be adapted for Kata Containers

### ISSUE THREAD

**Issue by wainersm** [kubernetes/kubernetes#100710]
One way (maybe the easiest today) of running the e2e tests for testing Kata Containers [1] with Kubernetes is to deploy an admission controller webhook to mutate pods so that they will have set the `runtimeClassName` properly. The caveat of such as approach is the webhook mutating not just test pods but also admin ones, which could drive to false-positives.

Regardless, I've been using the project's webhook [2] to daily run a CI job [3] to test Kata Containers with OpenShift. The results that I get seems very satisfactory with only a few e2e tests failing.

However I could identify some k8s e2e which will fail because actually the test code should handle Kata Containers as a corner case. For example, the tests below will fail on the fsType checking because Kata won't mount the filesystem as ext4 (instead it mounts as virtiofs).

```
[sig-storage] In-tree Volumes [Driver: local][LocalVolumeType: block] [Testpattern: Pre-provisioned PV (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Dynamic PV (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Pre-provisioned PV (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
[sig-storage] In-tree Volumes [Driver: azure-disk] [Testpattern: Inline-volume (ext4)] volumes should store data [Suite:openshift/conformance/parallel] [Suite:k8s]
```    
Therefore, I am opening this issue for the purpose of:
 1. Track the e2e tests which I suspect fail because they need to be adapted for Kata Containers 
 2. Discuss solutions, e.g., for the above tests perhaps does not check fsType would be acceptable solution? 
 3. Track eventual PRs to address this enhancement

#### References

[1] https://katacontainers.io/
[2] https://github.com/kata-containers/tests/tree/main/kata-webhook
[3] https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-kata-containers-kata-containers-main-e2e-tests

**Comment by BenTheElder** [comment]
Alternatively you could just make kata the default runtime in the test cluster..?

Kata seems to actually be failing the expectations of the test here. Why not fix that or simply not run these test cases?

Ultimately storage tests are sig storage's call, but wherever possible we expect to make tests portable so we can potentially include them in conformance, and the cluster is expected to pass the tests.

**Comment by wainersm** [comment]
Hi @BenTheElder , first of all, thanks for the prompt reply.

> Alternatively you could just make kata the default runtime in the test cluster..?

I don't know how it would change the fact that some tests break if kata containers is used. Could you please expand on that topic?

> 
> Kata seems to actually be failing the expectations of the test here. Why not fix that or simply not run these test cases?
>

Taking the problem described on https://github.com/kubernetes/kubernetes/pull/100712 as an example. Kata Containers is failing the expectation of the test, yes, but such as expectation cannot be met given the constraints imposed by the technologies of virtualization used (i.e. the filesystem type will be exposed as virtiofs necessarily; it is a detail of implementation).

Nowadays with the possibility of using different runtimes with k8s (by leveraging the Runtime Class extension) and the advent of various projects which proposes virtualization-based sandboxed containers, I am afraid that more and more the e2e tests will need to take in consideration those "exceptional uses".  

I confess that I don't like the idea of putting "if-given-runtime-then-do-this-else-do-that" across the e2e tests code. On the other hand, I am very new to k8s world and its testing culture so I cannot propose a better solution at this point. Now, if there isn't any way around for the problems I'm describing here, ok, I can manage to skip those tests in my test cluster. My ultimate goal with this issue is to debate whether or not some action should be taken and how.

> Ultimately storage tests are sig storage's call, but wherever possible we expect to make tests portable so we can potentially include them in conformance, and the cluster is expected to pass the tests.

Got it.

**Comment by BenTheElder** [comment]
> > Alternatively you could just make kata the default runtime in the test cluster..?
>
> I don't know how it would change the fact that some tests break if kata containers is used. Could you please expand on that topic?

This is in response to this comment from the original post:

> One way (maybe the easiest today) of running the e2e tests for testing Kata Containers [1] with Kubernetes is to deploy an admission controller webhook to mutate pods so that they will have set the runtimeClassName properly


> Taking the problem described on #100712 as an example. Kata Containers is failing the expectation of the test, yes, but such as expectation cannot be met given the constraints imposed by the technologies of virtualization used (i.e. the filesystem type will be exposed as virtiofs necessarily; it is a detail of implementation).

The "fix" here is to not essentially not run the test in certain circumstances. This kind of "skip" is banned from comformance tests and therefore discouraged in our tests because then we will not be able to conformance test in the future. 

You could also accomplish this by not running the test.

I don't think the conformance wg has necessarily agreed that tests should cater to anything other than runc-like environment (for example `crun` is perfectly compatible).

> I confess that I don't like the idea of putting "if-given-runtime-then-do-this-else-do-that" across the e2e tests code

Right, I don't think the tests should be aware of specific runtimes. The cleaner option is to configure your test invocation to skip certain tests?

As a general rule we don't actually run _Every_ test case on any given run. We have too many to be reasonable, instead we often focus on `[Conformance]` or exclude `[Flaky]|[Slow]|[Disruptive]`, etc.

For odd cluster configurations we configure excluding _specific_ test cases. I think that pretty much matches to this issue.

This puts the power over what tests run into the hands of the caller.

**Comment by BenTheElder** [comment]
I think this is primarily at the discretion of sig storage, however.
