### ISSUE TITLE
[sig-api-machinery] AdmissionWebhook - should mutate custom resource with pruning [Conformance]

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#100787]
#### Which test(s) are flaking: 
- `Kubernetes e2e suite: [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with pruning [Conformance]`
- `kinder.test.workflow: task-07-e2e`

#### Reason for failure:

```
• Failure [40.144 seconds]
[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin]
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/framework.go:23
  should mutate custom resource with pruning [Conformance] [It]
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
  Mar 30 01:12:43.485: waiting for webhook configuration to be ready
      
  Unexpected error:
      <*errors.errorString | 0xc000246250>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred
  /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1826
------------------------------
{"msg":"FAILED [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with pruning [Conformance]","total":-1,"completed":15,"skipped":321,"failed":1,"failures":["[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should mutate custom resource with pruning [Conformance]"]}

```

#### Anything else we need to know:

Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=%5C%5Bsig%5C-api%5C-machinery%5C%5D%5C%20AdmissionWebhook%5C%20%5C%5BPrivileged%3AClusterAdmin%5C%5D%5C%20should%5C%20mutate%5C%20custom%5C%20resource%5C%20with%5C%20different%5C%20stored%5C%20version%5C%20%5C%5BConformance%5C%5D

> Notes: 4 clusters of 316 failures (21 in last day) out of 125086 builds from 3/18/2021, 8:00:07 PM to 4/2/2021, 11:57:06 AM.

/sig api-machinery

**Comment by liggitt** [comment]
This looks the same as https://github.com/kubernetes/kubernetes/issues/100760

**Comment by neolit123** [comment]
i do not see this flake in the recent runs of the test job:
https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest&width=20

**Comment by lambdanis** [comment]
There was a flake yesterday: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1413083890691608576

But this issue looks like an exact duplicate of https://github.com/kubernetes/kubernetes/issues/100760, I think one of them should be closed.

**Comment by neolit123** [comment]
/close
duplicate
