### ISSUE TITLE
[Failing test] Kubernetes e2e suite.[sig-autoscaling] DNS horizontal autoscaling kube-dns-autoscaler should scale kube-dns pods in both nonfaulty and faulty scenarios

### ISSUE THREAD

**Issue by sladyn98** [kubernetes/kubernetes#100795]
#### Which jobs are failing:
 e2e-kops-gce-stable 
 e2e-kops-gce-latest 

#### Which test(s) are failing:
DNS horizontal autoscaling kube-dns-autoscaler should scale kube-dns pods in both nonfaulty and faulty scenarios

#### Since when has it been failing:
I cannot quite see the testgrid date since its been failing for a long time

#### Testgrid link:
https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-gce-stable

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:57
Mar 24 08:28:41.571: Unexpected error:
    <*errors.StatusError | 0xc001621720>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "configmaps \"kube-dns-autoscaler\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kube-dns-autoscaler",
                Group: "",
                Kind: "configmaps",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    configmaps "kube-dns-autoscaler" not found
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/autoscaling/dns_autoscaling.go:70
```

#### Anything else we need to know:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=autoscaling&test=DNS%20horizontal%20autoscaling%20kube-dns-autoscaler%20should%20scale%20kube-dns%20pods%20in%20both%20nonfaulty%20and%20faulty%20scenarios

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-stable/1378287426245496832
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/e2e-kops-gce-stable/1378272072488194048

**Comment by pacoxu** [comment]
It seems to be related with ENABLE_DNS_HORIZONTAL_AUTOSCALER setting in kops gce cluster.

As we are moving from `kube-dns and autoscaler` to `coredns with node-local-dns`, does this still needed? I think this need a cleanup. Let me check the background.

/assign
/area dns

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/kops/commit/2844abd2255fbc91df4ad17a8a5922084cc4a7f8#diff-2983fab4084c9924c5b2b08ee707eb513c749db933e7b3481b8a746ddf033875, kops gke will migrate to coredns after 1.20.

So we should skip it.

**Comment by pacoxu** [comment]
Should we remove # Should keep target in cluster/addons/dns-horizontal-autoscaler/dns-horizontal-autoscaler.yaml and ENABLE_DNS_HORIZONTAL_AUTOSCALER related scripts ?

**Comment by pacoxu** [comment]
> It seems to be related with ENABLE_DNS_HORIZONTAL_AUTOSCALER setting in kops gce cluster.
> 
> As we are moving from `kube-dns and autoscaler` to `coredns with node-local-dns`, does this still needed? I think this need a cleanup. Let me check the background.

@BenTheElder  I made a mistake here. I thought that the dns-autoscaler only supports old kube-dns, however, it supports both kube-dns and coredns. https://kubernetes.io/docs/tasks/administer-cluster/dns-horizontal-autoscaling/

So this should not be removed. I will check if it still fails or the failure reason.

**Comment by aojea** [comment]
If this is a kops only issue https://storage.googleapis.com/k8s-gubernator/triage/index.html?sig=autoscaling&test=DNS%20horizontal%20autoscaling%20kube-dns-autoscaler%20should%20scale%20kube-dns%20pods%20in%20both%20nonfaulty%20and%20faulty%20scenarios

should this not be open in the kops project?

**Comment by pacoxu** [comment]
The link is broken now: https://testgrid.k8s.io/sig-cluster-lifecycle-kops#kops-gce-stable
> Internal Error: Refresh, and file an issue if problem persists. (Your table may be too big; consider lower `days_of_results` or `enable_test_methods = false`).

@aojea  https://prow.k8s.io/?job=e2e-kops-gce-stable is green now.

@sladyn98 can we close this?

**Comment by sladyn98** [comment]
Yeah if the job is green we can close it.
