### ISSUE TITLE
Make more effective use of golangci-lint

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#100783]
Hi team.
Currently, this repository runs golangci-lint using `./hack/verify-golangci-lint.sh` added in #99120

I personally think that lint should be used a little more effectively.
Currently we have the script, but golangci-lint is giving us errors for the master brunch's code. This means that this script is not working.

FYI: https://github.com/kubernetes/kubernetes/issues/99243

So I think we need to somehow make developers more aware of the existence of lint.
I think it would be more likely that developers would still be aware of lint if it existed in the Makefile rather than just in a huge number of scripts in the hack directory.

(Ideally, it should be checked by CI, but I thought it could reduce productivity as it would take longer for the CI run to finish.)

---

And, golangci-lint can be configured with a file. I think that we should create a configuration file because managing settings in a file makes it easier to manage more detailed settings. For example, it is possible to perform a detailed lint check only on the code in the pkg directory

https://golangci-lint.run/usage/configuration/#config-file

#### What would you like to be added:

- modify Makefile to add `make lint`(run ./hack/verify-golangci-lint.sh)
- manage golangci-lint with `.golangci.yaml`

#### Why is this needed:

- we should use golangci-lint more effectively

**Comment by BenTheElder** [comment]
`make verify` is how these linter scripts are run, we don't need another makerule. you can run a specific verify with `make verify WHAT=golangci-lint`

If it is not running in CI then it must have been explicitly excluded.

**Comment by sanposhiho** [comment]
> make verify is how these linter scripts are run, we don't need another makerule. you can run a specific verify with make verify WHAT=golangci-lint

👀 👀 
I'm new to the development of this repository, so I didn't know about this, thanks. ❤️ 

> If it is not running in CI then it must have been explicitly excluded.

It seems to be explicitly excluded, as you say.

https://github.com/kubernetes/kubernetes/pull/99120/files#diff-7d0aff81f66f2fa4e129a3e8d4e0a19b95fa7ad922aff6a3bc6c7430d11157cfR38

**Comment by BenTheElder** [comment]
there's a _lot_ to take in in this repo 🙃 

we can un-exclude it when we have confidence in it, I think we're not there yet.

the tricky problem with these usually is that we have such a large volume of code, so the benefit of fixing the lints has to be very high for people to focus on this, otherwise it's just too much work to get the whole repo updated and all of the changes reviewed.

I agree that if we pursue golangci-lint further we should look at adding a configuration file.
We should not add it to the repor root as it will be difficult to approve changes to (very few people are granted permission to approve at the root directory), we should place it under `hack/` alongside the script.

**Comment by sanposhiho** [comment]
> the tricky problem with these usually is that we have such a large volume of code, 

Yeah, This repository is quite large, so if we just enable a lot of linter without thinking about it, it will take a long time to run...

For example, I think the following strategies can be used to optimize the use of linter

- Use only minor checks on the code for testing with `exclude-rules` on config file
- Enable more linters, especially for packages that need to be readable.

What do you think?

>  so the benefit of fixing the lints has to be very high for people to focus on this, otherwise it's just too much work to get the whole repo updated and all of the changes reviewed.

Developers may find this a bit of a hassle, but I think it's a good idea because it's something that needs to be done for reviewers and people who will later read the code.
Of course, we need to set only the linter you need for your project. Enabling too many linter will not contribute to productivity...

**Comment by BenTheElder** [comment]
> Use only minor checks on the code for testing with exclude-rules on config file

I'm not familiar with exclude-rules. But perhaps.

> Enable more linters, especially for packages that need to be readable.

Who decides which packages? I'm not sure this is a good idea, it should probably just be linters suitable to run repo-wide.


> Developers may feel a bit of a hassle, but I think it's good because it's something that needs to be done for reviewers and people who will later read the code.

Er yes, but we can't force people to fix things. There has to be pretty high value (e.g. preventing runtime bugs), it's just too expensive at this point to fix nitpick stuff across the entire repo unless it's mechanical (like gofmt) and even then ...

Not only do people have to enact the fixes, but it's time consuming to review them. So any linters enabled need a good argument why they're worth turning on.

For any new project I'd recommend running with most of them on from the start, but it's different trying to roll them out to such a large existing project.


cc @dims (previously expressed interest in this area)

**Comment by aojea** [comment]
/cc
There is some stuff in script that can be moved to golangci-lint: govet, gofmt, importas, ...
We reduce code to maintain and offload all these work to golangci-lint ...

**Comment by aojea** [comment]
important, it seems that we have to figure out how to lint staging folders too
https://github.com/kubernetes/kubernetes/pull/104368#discussion_r691257310
