### ISSUE TITLE
 [sig-node][NodeConformance]  when querying /stats/summary should report resource usage through the stats api

### ISSUE THREAD

**Issue by PriyankaH21** [kubernetes/kubernetes#100788]
#### Which test(s) are flaking:
- `E2eNode Suite: [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api `
-  `e2e.go: Node Tests`

#### Testgrid link: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1376358064403255296

#### Reason for failure:
```
Expected
    <string>: Summary
to match fields: {
.Node.SystemContainers[pods].CPU:
	Expected
	    <string>: CPUStats
	to match fields: {
	.UsageNanoCores:
		Expected
		    <*uint64 | 0xc0014639e8>: 0
		To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc0008180f0 Expected
		    <uint64>: 0
		to be >=
		    <int>: 10000})]
	}
	
}

_output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:344
```

#### Anything else we need to know:
go.k8s.io/triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=when%20querying%20%2Fstats%2Fsummary%20should%20report%20resource%20usage%20through%20the%20stats%20api

links to specific failures in spyglass:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-alpha/1377832918797258752
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-containerd-node-e2e-1-4/1377771771104595968

/sig node

**Comment by ehashman** [comment]
@cynepco3hahue any updates on this?

**Comment by cynepco3hahue** [comment]
> @cynepco3hahue any updates on this?

Will take a look at this week.

**Comment by cynepco3hahue** [comment]
It looks has the same symptoms as - https://github.com/kubernetes/kubernetes/pull/95345
@harche @alejandrox1 @dashpole FYI

Looks as cadvisor stats provider(e2e node still runs with docker) does not provide relevant stats. It looks like some cadvisor bug, because we only fethc the data from the cadvisor.

**Comment by bobbypage** [comment]
Are there examples of recent flakes for this? 

Looking at https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-master&width=20&include-filter-by-regex=stats%20api it seems pretty green for this test.

**Comment by cynepco3hahue** [comment]
@bobbypage It does not happen often, but still happen, see - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1414270480633827328

**Comment by cynepco3hahue** [comment]
Also, take into account that we mitigated one of the similar errors via https://github.com/kubernetes/kubernetes/pull/95345

**Comment by ehashman** [comment]
> Are there examples of recent flakes for this?
> 
> Looking at https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-master&width=20&include-filter-by-regex=stats%20api it seems pretty green for this test over the past 2 weeks.

That's failing often enough to be considered flaky; I have seen this test fail frequently on presubmit jobs.

**Comment by ehashman** [comment]
Flaking very frequently on the swap ubuntu periodic: https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu&exclude-non-failed-tests=

**Comment by SergeyKanzhelev** [comment]
this is not a regression, our suggestion is not block release on it. @kubernetes/release-managers feel free to remove the milestone

**Comment by bobbypage** [comment]
Taking a closer look.

Some failures from https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-master&width=20&include-filter-by-regex=stats%20api

Failure 1: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1417417911915515904



```
2 W0720 10:15:27.281] STEP: Destroying namespace "summary-test-1228" for this suite.
3 W0720 10:15:27.281]
4 W0720 10:15:27.281]
5 W0720 10:15:27.281] • Failure [49.590 seconds]
6 W0720 10:15:27.281] [sig-node] Summary API [NodeConformance]
7 W0720 10:15:27.282] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
8 W0720 10:15:27.282]   when querying /stats/summary
9 W0720 10:15:27.282]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
0 W0720 10:15:27.282]     should report resource usage through the stats api [It]
1 W0720 10:15:27.282]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
2 W0720 10:15:27.282]
3 W0720 10:15:27.283]     Failed after 15.052s.
4 W0720 10:15:27.283]     Expected
5 W0720 10:15:27.283]         <string>: Summary
6 W0720 10:15:27.283]     to match fields: {
7 W0720 10:15:27.283]     .Node.SystemContainers[pods].CPU:
8 W0720 10:15:27.283]         Expected
9 W0720 10:15:27.283]             <string>: CPUStats
0 W0720 10:15:27.283]         to match fields: {
1 W0720 10:15:27.284]         .UsageNanoCores:
2 W0720 10:15:27.284]             Expected
3 W0720 10:15:27.284]                 <*uint64 | 0xc000bc3e58>: 0
4 W0720 10:15:27.284]             To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc00084aba0 Expected
5 W0720 10:15:27.284]                 <uint64>: 0
6 W0720 10:15:27.284]             to be >=
7 W0720 10:15:27.284]                 <int>: 10000})]
8 W0720 10:15:27.284]         }
9 W0720 10:15:27.285]
0 W0720 10:15:27.285]     }
1 W0720 10:15:27.285]
2 W0720 10:15:27.285]
3 W0720 10:15:27.285]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:349
```

Failure 2: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1416232826109431808

```
W0717 03:48:57.418] • Failure [49.312 seconds]
W0717 03:48:57.418] [sig-node] Summary API [NodeConformance]
W0717 03:48:57.418] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
W0717 03:48:57.418]   when querying /stats/summary
W0717 03:48:57.419]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
W0717 03:48:57.419]     should report resource usage through the stats api [It]
W0717 03:48:57.419]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
W0717 03:48:57.419]
W0717 03:48:57.419]     Failed after 15.034s.
W0717 03:48:57.419]     Expected
W0717 03:48:57.419]         <string>: Summary
W0717 03:48:57.419]     to match fields: {
W0717 03:48:57.419]     .Node.SystemContainers[pods].CPU:
W0717 03:48:57.420]         Expected
W0717 03:48:57.420]             <string>: CPUStats
W0717 03:48:57.420]         to match fields: {
W0717 03:48:57.420]         .UsageNanoCores:
W0717 03:48:57.420]             Expected
W0717 03:48:57.420]                 <*uint64 | 0xc0010cd208>: 0
W0717 03:48:57.420]             To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc000e21ce0 Expected
W0717 03:48:57.420]                 <uint64>: 0
W0717 03:48:57.420]             to be >=
W0717 03:48:57.421]                 <int>: 10000})]
W0717 03:48:57.421]         }
W0717 03:48:57.421]
W0717 03:48:57.421]     }
W0717 03:48:57.421]
W0717 03:48:57.421]
W0717 03:48:57.421]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:349
```


Failure 3: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet/1414270480633827328
 
```
W0711 17:49:05.048] • Failure [64.739 seconds]
W0711 17:49:05.048] [sig-node] Summary API [NodeConformance]
W0711 17:49:05.048] _output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
W0711 17:49:05.048]   when querying /stats/summary
W0711 17:49:05.048]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
W0711 17:49:05.048]     should report resource usage through the stats api [It]
W0711 17:49:05.049]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
W0711 17:49:05.049]
W0711 17:49:05.049]     Failed after 15.060s.
W0711 17:49:05.049]     Expected
W0711 17:49:05.049]         <string>: Summary
W0711 17:49:05.049]     to match fields: {
W0711 17:49:05.049]     .Node.SystemContainers[pods].CPU:
W0711 17:49:05.050]         Expected
W0711 17:49:05.050]             <string>: CPUStats
W0711 17:49:05.050]         to match fields: {
W0711 17:49:05.050]         .UsageNanoCores:
W0711 17:49:05.050]             Expected
W0711 17:49:05.050]                 <*uint64 | 0xc000f53030>: 0
W0711 17:49:05.050]             To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc0007a4000 Expected
W0711 17:49:05.051]                 <uint64>: 0
W0711 17:49:05.051]             to be >=
W0711 17:49:05.051]                 <int>: 10000})]
W0711 17:49:05.051]         }
W0711 17:49:05.051]
W0711 17:49:05.051]     }
W0711 17:49:05.051]
W0711 17:49:05.051]
W0711 17:49:05.052]     _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:349
```

**Comment by bobbypage** [comment]
hmm, I'm not sure if I understand the failure correctly. 

It looks like the test gets back `0` for `Node.SystemContainers[pods].CPU.UsageNanoCores` and expects that it will match either zero or be >= 10000.

The test code expects either 0 or between 10000 and 2e9. 

https://github.com/kubernetes/kubernetes/blob/85a29212e03d8385a2b8cdee7758067e2ea0aac8/test/e2e_node/summary_test.go#L98

Based on error message, it in fact look like it's getting back 0: 

```
W0711 17:49:05.050]             Expected
W0711 17:49:05.050]                 <*uint64 | 0xc000f53030>: 0
```

so I'm a bit confused why this check is failing. Am I misunderstand the failure or does the `gomega.SatisfyAny` line not do what we are expecting? 

/cc @harche 
who looked who spent some time looking at this as part of https://github.com/kubernetes/kubernetes/pull/95345

**Comment by bobbypage** [comment]
Also by the way, the failures in ubuntu swap job https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu&exclude-non-failed-tests= seem to be caused by reason. Those failures seem to be due to MemoryStats:

e.g.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu/1417908948832358400

```
W0721 18:26:07.489]     .Pods[summary-test-3534::stats-busybox-0].Memory:
W0721 18:26:07.489]     	Expected
W0721 18:26:07.489]     	    <string>: MemoryStats
W0721 18:26:07.489]     	to match fields: {
W0721 18:26:07.489]     	.RSSBytes:
W0721 18:26:07.489]     		Expected
W0721 18:26:07.489]     		    <uint64>: 0
W0721 18:26:07.489]     		to be >=
W0721 18:26:07.489]     		    <int64>: 1000
W0721 18:26:07.489]     	}
W0721 18:26:07.489]     	
W0721 18:26:07.489]     }
W0721 18:26:07.490]     [0m
```

Perhaps memory stats may be impacted by swap being enabled?

**Comment by bobbypage** [comment]
I tried to repro the failures in https://github.com/kubernetes/kubernetes/issues/100788#issuecomment-884525348 by making the below patch (to force `UsageNanoCores` to always be zero).

```
--- a/pkg/kubelet/server/stats/summary_sys_containers.go
+++ b/pkg/kubelet/server/stats/summary_sys_containers.go
@@ -55,6 +55,13 @@ func (sp *summaryProviderImpl) GetSystemContainersStats(nodeConfig cm.NodeConfig
                if !cont.startTime.IsZero() {
                        s.StartTime = cont.startTime
                }
+               if cont.name == sp.provider.GetPodCgroupRoot() {
+                       var zero uint64
+                       s.CPU.UsageNanoCores = &zero
+               }
+
                stats = append(stats, *s)
        }
``` 

The test fails consistently with this change:

```
• Failure [109.617 seconds]
[sig-node] Summary API [NodeConformance]
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
  when querying /stats/summary
  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
    should report resource usage through the stats api [It]
    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54

    Timed out after 90.000s.
    Expected
        <string>: Summary
    to match fields: {
    .Node.SystemContainers[pods].CPU:
        Expected
            <string>: CPUStats
        to match fields: {
        .UsageNanoCores:
                Expected
                    <*uint64 | 0xc000d13640>: 0
                To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc000bbc660 Expected
                    <uint64>: 0
                to be >=
                    <int>: 10000})]
        }

    }
```

despite the fact that zero should be valid and passing for the test

https://github.com/kubernetes/kubernetes/blob/85a29212e03d8385a2b8cdee7758067e2ea0aac8/test/e2e_node/summary_test.go#L94-L98

So this makes me think that the problem is that the `gomega.SatisfyAny` is not actually doing what we expect.

**Comment by bobbypage** [comment]
I think the problem `gomega.SatisfyAny` is it's doing a uint64 pointer comparison to uint64. 

expected is `*uint64`
```
Expected
                    <*uint64 | 0xc000d13640>: 0
```
matcher expects `uint64`
```
                To satisfy at least one of these matchers: [%!s(*matchers.BeZeroMatcher=&{}) %!s(*gstruct.PointerMatcher=&{0xc000bbc660 Expected
                    <uint64>: 0
```

The following patch to test results in test passing when zero is returned:

```
-                                               "UsageNanoCores":       gomega.SatisfyAny(gomega.BeZero(), bounded(10000, 2e9)),
+                                               "UsageNanoCores":       gomega.SatisfyAny(gstruct.PointTo(gomega.BeZero()), bounded(10000, 2e9)),
```

**Comment by ehashman** [comment]
/reopen

This appears to be flaking a lot per triage, I'm also seeing it on PRs

**Comment by ehashman** [comment]
Since this is against milestone v1.22, let me close this and potentially open a new issue as the current failures don't match.

/close
