### ISSUE TITLE
[Flaky Test] [sig-node] Pods should cap back-off at MaxContainerBackOff [Slow][NodeConformance]

### ISSUE THREAD

**Issue by thejoycekung** [kubernetes/kubernetes#100758]
#### Which jobs are flaking:
ci-kubernetes-e2e-windows-gce-2004
ci-kubernetes-e2e-windows-gce-2019
ci-kubernetes-e2e-windows-gce-20h2

Happening on master-informing and 1.21-informing.

#### Which test(s) are flaking:
[sig-node] Pods should cap back-off at MaxContainerBackOff [Slow][NodeConformance]

#### Testgrid link:

- https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master&show-stale-tests=&include-filter-by-regex=Pods%20should%20cap%20back-off%20at%20MaxContainerBackOff
- https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2019-master&show-stale-tests=&include-filter-by-regex=Pods%20should%20cap%20back-off%20at%20MaxContainerBackOff
- https://testgrid.k8s.io/sig-release-master-informing#gce-windows-20h2-master&show-stale-tests=&include-filter-by-regex=Pods%20should%20cap%20back-off%20at%20MaxContainerBackOff

#### Reason for failure:
Taken from this Spyglass example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1377540067605614592#1:build-log.txt:17645
```
Apr  1 10:15:02.305: FAIL: expected 5m0s back-off got=9m13s in delay1
Full Stack Trace
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc002e94180)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc002e94180)
Apr  1 10:15:02.305: FAIL: expected 5m0s back-off got=9m13s in delay1
Full Stack Trace
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc002e94180)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc002e94180)
	_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:144 +0x2b
testing.tRunner(0xc002e94180, 0x6dcacf8)
	/usr/local/go/src/testing/testing.go:1194 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1239 +0x2b3
[AfterEach] [sig-node] Pods
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
STEP: Collecting events from namespace "pods-90".
STEP: Found 6 events.
Apr  1 10:15:02.343: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for back-off-cap: { } Scheduled: Successfully assigned pods-90/back-off-cap to e2e-72498dd1e8-c48e0-windows-node-group-nmf3
Apr  1 10:15:02.343: INFO: At 2021-04-01 09:46:27 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} Pulled: Container image "k8s.gcr.io/e2e-test-images/busybox:1.29-1" already present on machine
Apr  1 10:15:02.343: INFO: At 2021-04-01 09:46:28 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} Created: Created container back-off-cap
Apr  1 10:15:02.343: INFO: At 2021-04-01 09:46:35 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} Started: Started container back-off-cap
Apr  1 10:15:02.343: INFO: At 2021-04-01 09:48:10 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} BackOff: Back-off restarting failed container
Apr  1 10:15:02.343: INFO: At 2021-04-01 10:12:38 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} Failed: Error: context deadline exceeded
Apr  1 10:15:02.380: INFO: POD           NODE                                          PHASE    GRACE  CONDITIONS
Apr  1 10:15:02.380: INFO: back-off-cap  e2e-72498dd1e8-c48e0-windows-node-group-nmf3  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2021-04-01 09:46:02 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2021-04-01 09:59:58 +0000 UTC ContainersNotReady containers with unready status: [back-off-cap]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2021-04-01 09:59:58 +0000 UTC ContainersNotReady containers with unready status: [back-off-cap]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2021-04-01 09:46:02 +0000 UTC  }]
```

#### Anything else we need to know:
Triage: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=Pods%20should%20cap%20back-off%20at%20MaxContainerBackOff#f101a59cb13dc89c3050

Example Spyglass links:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1377582841705009152
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1377522190294978560
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1377479407165247488
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004-1-21/1377250816255070208
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2019-1-21/1377371956420022272

/sig node windows

**Comment by jsturtevant** [comment]
looked into the errors for a few recent failures.  And it looks like there might be something happening with the connection to the runtime and timeout of the start up for the pods or some resource contention. They all have `rpc error: code = DeadlineExceeded desc = context deadline exceeded`

We don't see this in aks-engine runs.  We run all serial/slow tests in a separate job.  Maybe that is an option?

Not as familiar with the gke set up, @pjh or @jeremyje might be able to help?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-20h2/1377582841705009152
```
pr  1 12:52:43.583: INFO: At 2021-04-01 12:52:01 +0000 UTC - event for back-off-cap: {kubelet e2e-64a6b4549a-9f143-windows-node-group-c83j} InspectFailed: Failed to inspect image "k8s.gcr.io/e2e-test-images/busybox:1.29-1": rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1377540067605614592
```
Apr  1 10:15:02.343: INFO: At 2021-04-01 10:12:38 +0000 UTC - event for back-off-cap: {kubelet e2e-72498dd1e8-c48e0-windows-node-group-nmf3} Failed: Error: context deadline exceeded
Apr  1 10:15:02.380: INFO: POD           NODE                                          PHASE    GRACE  CONDITIONS
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-containerd-gce/1377474374533124096
```
Apr  1 05:42:00.756: INFO: At 2021-04-01 05:15:53 +0000 UTC - event for back-off-cap: {kubelet e2e-669d8e4687-dc24d-windows-node-group-vgxh} Started: Started container back-off-cap
Apr  1 05:42:00.756: INFO: At 2021-04-01 05:17:46 +0000 UTC - event for back-off-cap: {kubelet e2e-669d8e4687-dc24d-windows-node-group-vgxh} BackOff: Back-off restarting failed container
Apr  1 05:42:00.756: INFO: At 2021-04-01 05:41:33 +0000 UTC - event for back-off-cap: {kubelet e2e-669d8e4687-dc24d-windows-node-group-vgxh} Failed: Error: context deadline exceeded
```

**Comment by pjh** [comment]
Thanks James for taking the first look, I'm checking on this now.

/assign

**Comment by pjh** [comment]
I've sent https://github.com/kubernetes/test-infra/pull/21640 and https://github.com/kubernetes/test-infra/pull/21640 to stop running the `[Slow]` tests except specifically in the Serial test job for GCE Windows.

**Comment by thejoycekung** [comment]
/close

Now that both kubernetes/test-infra#21640 and kubernetes/test-infra#21642 have merged, this test won't run anymore.
