### ISSUE TITLE
Kubeadm join randomly fails with etcd store not starting

### ISSUE THREAD

**Issue by jfgauron** [kubernetes/kubernetes#100797]
#### What happened:

I have an issue where joining a node to the control plane fails. What I find weird is the issue appears to be completely random. If I just reset the node using `kubeadm reset -f` and try `kubeadm join` again, there is about a 50% chance that it will succeeds.

#### What you expected to happen:

`kubeadm join` to act consistently.

#### How to reproduce it (as minimally and precisely as possible):

I made a repo to reproduce the issue. You'll need packer, terraform and jq. Follow the instructions on the README: https://github.com/jfgauron/debug-kubernetes-etcd.

#### Anything else we need to know?:

I followed the instructions there: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/. The load balancer is an internal `networking load balancer` in AWS and all the instances served are in private subnets. The instances are registered by ip address. For my testing, I gave all the instances permissions to send/receive data on every ports/protocols, so it isn't a security group issue.

#### Environment:
- Kubernetes version (use `kubectl version`):
````
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
````

- Cloud provider or hardware configuration: `AWS`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.2 LTS (Focal Fossa)`
- Kernel (e.g. `uname -a`): `Linux ip-10-17-24-243 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: I installed kubernetes manually in a `packer` script.
 Provision script: https://pastebin.com/raw/bi4bLSN3
 calico.yaml: https://pastebin.com/raw/yhEWdHk5
 containerd/config.toml: https://pastebin.com/raw/BYPADA28
 kubeadm.yaml: https://pastebin.com/raw/M6qYDdMd
 
 The provision script install kubernetes, containerd, pull images, etc... calico.yaml is the network plugin, containerd config is to use systemd cgroup. kubeadm.yaml is the config passed to `kubeadm init`.
- Network plugin and version (if this is a network-related bug): `calico (0.3.1)`
- Others:

Here are logs from the cluster (10.17.73.85 is the unhealthy node):

[kubectl describe pod -n kube-system kube-apiserver-ip-10-17-83-85](https://pastebin.com/raw/Zkg9pKx1)
[kubectl get --raw='https://10.17.83.85:6443/livez?verbose'](https://pastebin.com/raw/kZvyV7Lg) - from 10-17-80-97
[kubectl get --raw='https://10.17.83.85:6443/livez?verbose'](https://pastebin.com/raw/TCMXFKQa) - from 10-17-83-85
`curl -k https://10.17.83.85:6443/livez?verbose` - from both nodes -> connection refused???
[journalctl -xeu kubelet](https://pastebin.com/raw/SpxxFsZd) - from 10-17-83-85
[kubectl get pods -n kube-system](https://pastebin.com/raw/5mpbwupQ)

You will notice in the `describe pod` command than the node is in a crash loop with these events:

```
Warning  Unhealthy  24m                   kubelet  Startup probe failed: Get "https://10.17.83.85:6443/livez": read tcp 10.17.83.85:41100->10.17.83.85:6443: read: connection reset by peer
```

**Comment by jfgauron** [comment]
I made a repo to reproduce the issue: https://github.com/jfgauron/debug-kubernetes-etcd.

I also noticed that `kubeadm join` fails at the `control-plane-join/etcd` phase:

```
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: timeout waiting for etcd cluster to be available
To see the stack trace of this error execute with --v=5 or higher
```

etcd store not being started is what causes `kube-apiserver` crash loop: 

```
W0404 14:16:30.786996       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Error: context deadline exceeded
```

`kubeadm join --v=10` output: 

```
79 with maintenance client: context deadline exceeded
I0404 23:50:57.215710    1516 etcd.go:468] Failed to get etcd status for https://10.17.17.29:2379: failed to dial endpoint https://10.17.17.29:2379 with maintenance client: context deadline exceeded
I0404 23:51:05.007515    1516 etcd.go:468] Failed to get etcd status for https://10.17.17.29:2379: failed to dial endpoint https://10.17.17.29:2379 with maintenance client: context deadline exceeded
I0404 23:51:15.809967    1516 etcd.go:468] Failed to get etcd status for https://10.17.17.29:2379: failed to dial endpoint https://10.17.17.29:2379 with maintenance client: context deadline exceeded
I0404 23:51:31.580466    1516 etcd.go:468] Failed to get etcd status for https://10.17.17.29:2379: failed to dial endpoint https://10.17.17.29:2379 with maintenance client: context deadline exceeded     
```

**Comment by jfgauron** [comment]
I wasn't able to reproduce the issue on 1.19.0. Seems to be specific to 1.20.x.

**Comment by jfgauron** [comment]
I have updated the previously mentioned repository with logs from a test that failed: https://github.com/jfgauron/debug-kubernetes-etcd/tree/main/logs.

**Comment by neolit123** [comment]
> error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: timeout waiting for etcd cluster to be available
To see the stack trace of this error execute with --v=5 or higher

we are not seeing such problems in the kubeadm e2e tests for 1.20:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-1-20

this is a 3 control-plane node cluster with stacked etcd (colocated etcd members on the CP nodes).

we also have kubeadm usage in a few companies in their products.

reading:
https://github.com/jfgauron/debug-kubernetes-etcd/blob/main/logs/join_output.txt

> I0406 01:48:01.243224 1126 etcd.go:488] [etcd] attempting to see if all cluster endpoints ([https://10.17.23.83:2379 https://10.17.16.128:2379]) are available 1/8
I0406 01:48:03.272059 1126 etcd.go:468] Failed to get etcd status for https://10.17.16.128:2379: failed to dial endpoint https://10.17.16.128:2379 with maintenance client: context deadline exceeded

this could be host machine / infrastructure or network connectivity related.
you can debug it with curl / etcdctl locally.

kubeadm just constructs and etcd client in go, and tries to list members / check if they are ready.

/kind support
/area kubeadm

**Comment by jfgauron** [comment]
There is no "etcd pod container". It just never starts. Kubeadm announces the new etcd member:
>[etcd] Announced new etcd member joining to the existing etcd cluster

Then it creates the static pod manifest:

>Creating static Pod manifest for "etcd"

I can see that the manifest was correctly created in `/etc/kubernetes/manifests`. But then for some reasons kubelet fails at starting the pod, so the etcd members are stuck in this state:

```
e18359e28da17e0, started, ip-10-17-30-59, https://10.17.30.59:2380, https://10.17.30.59:2379
168bb4e9e85df5db, started, ip-10-17-152-153, https://10.17.152.153:2380, https://10.17.152.153:2379
994dd0e5adc088a0, started, ip-10-17-88-66, https://10.17.88.66:2380, https://10.17.88.66:2379
daee76e09e5f58f4, unstarted, , https://10.17.22.239:2380,
```

And listing pods with `kubectl get pods -n kube-system` show that the etcd pod is missing for the unhealthy node:

```
calico-kube-controllers-69496d8b75-6nwl2   1/1     Running            0          11m
calico-node-5hrhp                          1/1     Running            0          3m55s
calico-node-jmdtg                          1/1     Running            0          9m47s
calico-node-rfnwd                          1/1     Running            0          11m
calico-node-w98sz                          1/1     Running            0          10m
coredns-74ff55c5b-s2btw                    1/1     Running            0          11m
coredns-74ff55c5b-zj5n5                    1/1     Running            0          11m
etcd-ip-10-17-152-153                      1/1     Running            0          9m44s
etcd-ip-10-17-30-59                        1/1     Running            0          12m
etcd-ip-10-17-88-66                        1/1     Running            0          10m
kube-apiserver-ip-10-17-152-153            1/1     Running            0          9m46s
kube-apiserver-ip-10-17-22-239             0/1     CrashLoopBackOff   4          3m54s
kube-apiserver-ip-10-17-30-59              1/1     Running            0          12m
kube-apiserver-ip-10-17-88-66              1/1     Running            0          10m
kube-controller-manager-ip-10-17-152-153   1/1     Running            0          9m46s
kube-controller-manager-ip-10-17-22-239    1/1     Running            0          3m54s
kube-controller-manager-ip-10-17-30-59     1/1     Running            2          12m
kube-controller-manager-ip-10-17-88-66     1/1     Running            0          10m
kube-proxy-79bhk                           1/1     Running            0          3m55s
kube-proxy-9ncbc                           1/1     Running            0          10m
kube-proxy-bn6xr                           1/1     Running            0          11m
kube-proxy-fmh2w                           1/1     Running            0          9m47s
kube-scheduler-ip-10-17-152-153            1/1     Running            0          9m46s
kube-scheduler-ip-10-17-22-239             1/1     Running            0          3m54s
kube-scheduler-ip-10-17-30-59              1/1     Running            1          12m
```

When looking [at kubelet logs](https://pastebin.com/raw/evRi67e3) with `journalctl --no-pager -xu kubelet`, you can clearly see something went wrong:

```
Apr 08 22:19:32 ip-10-17-22-239 kubelet[1890]: W0408 22:19:32.956706    1890 predicate.go:113] Failed to admit pod etcd-ip-10-17-22-239_kube-system(8103f6cb1f46b8065a06864c5b04369e) - Unexpected error while attempting to recover from admission failure: preemption: error finding a set of pods to preempt: no set of running pods found to reclaim resources: [(res: ephemeral-storage, q: 104857600), ]
```

This error led me to [this issue](https://github.com/kubernetes/kubernetes/issues/99305). Sadly [the fix suggested here](https://github.com/kubernetes/kubernetes/issues/99305#issuecomment-802805653) didn't seem to work.

Running `systemctl restart kubelet` fix the issue and makes the node healthy again.

>this could be host machine / infrastructure or network connectivity related.

I literally built a test repository with `terraform` and `packer` so that the host machines / infrastructure and network connectivity would all be accounted for. I can reproduce the issue 100% of the time, starting from scratch every time. The issue also get fixed by restarting kubelet, despite not changing anything to the host machine, infrastructure, or network. I fail to see how it could be anything but a bug in kubernetes.

**Comment by neolit123** [comment]
> EDIT: I was in fact able to apply the fix in the issue I linked and it fixed my problem. We can close this issue then since there is already one open. 

i does look the same as https://github.com/kubernetes/kubernetes/issues/99305

> Would have been nice if my issue was taken seriously from the start, just saying.

looking at your failure logs and finding a related kubernetes/kubernetes ticket was the right action. this is not a kubeadm bug per se. you can also comment on https://github.com/kubernetes/kubernetes/issues/99305 that you experienced the same bug.
