### ISSUE TITLE
when apiservers have different RV for infrequently updated resources, client-go will get too large resource version error and relist the source again and again

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#100745]
#### What happened:
In a large cluster, even if the configmap has not changed, kube-apiserver will receive many list configmap requests
In the problem scenario, we have two kube-apiservers A and B. A pod managed by kubelet references configmap A as a volume. If configmap A is changed and kubelet's http2 connection is switched by the GOAWAY #88567, then kubelet will relist configmap A from the apiserver. In a large cluster, this problem will cause the kube-apiserver cpu usage to be too high.
The scene is as shown below
![image](https://user-images.githubusercontent.com/1468240/113268661-31d60e00-930a-11eb-9e88-1f1bfd6f1418.png)

@wojtek-t 

#### What you expected to happen:

kubelet's client-go donot relist configmap A again and again.

#### How to reproduce it (as minimally and precisely as possible):

In large clusters, kube-apiserver will have a lot of trace logs which is about cacher list xxx(total time: 3000ms)

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.4
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): euleros 2.9
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wojtek-t** [comment]
https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1904-efficient-watch-resumption will address it (it's going beta in 1.21 release)

**Comment by chenyw1990** [comment]
@wojtek-t thank you so much, i think this enhancement can fix this issue.
@jpbetz I think that the PR #94364 can fix this issue, I will merge it to our branch, and test again, wait my new report.

**Comment by chenyw1990** [comment]
PR #94364 cannot be cherry pick to v1.19.4,  but I think it can fix it.
close this issue.
