### ISSUE TITLE
Deprecate and remove DynamicKubeletConfig (?)

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100799]
Stuck in beta since `v1.11`:
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go#L37-L40

/sig node

**Comment by dims** [comment]
cc @SergeyKanzhelev @ehashman

**Comment by pacoxu** [comment]
#61673 as well. 

> If this could be considered an instance-specific flag, or a descriptor of local topology
> managed by the Kubelet, see: #61647.
> 
> If this flag is only registered in os-specific builds, see: #61649.

**Comment by neolit123** [comment]
the feature was enabled in kubeadm as optional, but we removed it recently.

prior feedback from users was that they could not get it work with the kubeadm wrapped option or by following the official docs:
https://kubernetes.io/blog/2018/07/11/dynamic-kubelet-configuration/

dynamic reconfiguration of services is a interesting discussion, yet from what i've seen SIG Arch are mostly not in favor.
but arguably dynamic reload of certs from disk falls in the same bucket and we are already doing that for some component flags.

**Comment by liggitt** [comment]
> but arguably dynamic reload of certs from disk falls in the same bucket and we are already doing that for some component flags.

I don't think that's in the same bucket... dynamic refresh of a time-bound portion of a configuration (like a CA bundle or an authentication token) seems very different from changing the configuration.

**Comment by neolit123** [comment]
i still consider it dynamic reconfiguration of a service, that may or may not have behavior changes.
changing the CA bundle that a server accepts can have behavior changes for clients trusting the same server.

**Comment by derekwaynecarr** [comment]
we discussed this in sig-node and @SergeyKanzhelev said he would explore this in more depth during 1.22.

**Comment by mtaufen** [comment]
I agree with @liggitt that auto reload of the CA bundle is not in the same category of DynamicKubeletConfig.

It's the difference between changing the filepath (dynamic config) and just reloading the file at a fixed location (CA reload). 

Sure it's technically a change but if config is specifying intent, and the intent is "reload this file periodically," then changing the target file is not changing intent.

**Comment by SergeyKanzhelev** [comment]
Let's track this work as a KEP so there are less bugs in k/k repository. Also helps with linking to the KEP - instead of linking PRs to this issue.

/close

**Comment by BenTheElder** [comment]
Note: the KEP is https://github.com/kubernetes/enhancements/issues/281#issuecomment-841001850
