### ISSUE TITLE
coredns in containercreating state : invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

### ISSUE THREAD

**Issue by amarjothi** [kubernetes/kubernetes#100719]
#### What happened:

`NAME                                                         READY   STATUS              RESTARTS   AGE

calico-kube-controllers-568b9cfb7-lrzh7   1/1     Running             0          26h
calico-node-49zr8                                         1/1     Running             0          2d1h

**coredns-5d6ccf5984-ct9px                       0/1     ContainerCreating   0          45m
coredns-5d6ccf5984-szs2s                          0/1     ContainerCreating   0          45m
coredns-6c6f7bf499-24mkg                         0/1     ContainerCreating   0          45m**

kube-apiserver-kube-master-1                     1/1     Running             0          27h
kube-controller-manager-kube-master-1     1/1     Running             0          2d2h
kube-proxy-qps8j                                           1/1     Running             0          2d1h
kube-scheduler-kube-master-1                    1/1     Running             0          22h`

#### What you expected to happen:

Coredns to create pods in running state.  Currently failing with error,

 Warning  FailedCreatePodSandBox  70s (x131 over 29m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f049cd07dd737cc430ea2186c035d168ac7087bf1700599c79ed2c9dcfa94545": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable

#### How to reproduce it (as minimally and precisely as possible):

kubeadm init --config /etc/kubernetes/kubeadmcfg.yaml  --v=5 --ignore-preflight-errors=all 

kubectl apply -f calico_clusterrole.yaml --kubeconfig=/etc/kubernetes/admin.conf
kubectl create clusterrolebinding calico-cni --clusterrole=calico-cni --user=calico-cni --kubeconfig=/etc/kubernetes/admin.conf

After cluster initialisation- After all nodes are up :-
kubectl apply -f calico_etcd.yaml --kubeconfig=/etc/kubernetes/admin.conf

KUBEADM CONFIG 
`#!/bin/bash -x

cat > /etc/kubernetes/kubeadmcfg.yaml <<EOF
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
  - token: "xxxxxxxxxxx"
    description: "another bootstrap token"
    usages:
      - authentication
      - signing
    groups:
      - system:bootstrappers:kubeadm:default-node-token
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: xx.xx.xx.xx
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    resolv-conf: "/etc/resolv.conf"
    node-ip: xx.xx.xx.xx
    kubelet-cgroups: "/system.slice/kubelet.service"
    container-runtime: remote  
    container-runtime-endpoint: unix:///run/containerd/containerd.sock
    runtime-cgroups: "/system.slice/containerd.service"
    network-plugin: cni
    cni-bin-dir: /opt/cni/bin
    cni-conf-dir: /etc/cni/net.d
    cgroup-driver: systemd
  taints:
  - effect: PreferNoSchedule
    key: node-role.kubernetes.io/master
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
certificatesDir: "/etc/kubernetes/pki"
clusterName: "kubernetes"
controllerManager:
  extraArgs:
    kubeconfig: "/etc/kubernetes/controller-manager.conf"
    cluster-name: "kubernetes"
    cluster-signing-cert-file: "/etc/kubernetes/pki/ca.crt"
    cluster-signing-key-file: "/etc/kubernetes/pki/ca.key"
    node-monitor-grace-period: "60s"
    node-monitor-period: "10s"
    node-startup-grace-period: "1m30s"
    bind-address: "0.0.0.0"
    secure-port: "10257"
    deployment-controller-sync-period: "60s"
    leader-elect: "true"
    leader-elect-lease-duration: "30s"
    leader-elect-renew-deadline: "20s"
    service-account-private-key-file: "/etc/kubernetes/pki/sa.key"
    service-cluster-ip-range: "10.96.0.0/24"
    controllers: "*,bootstrapsigner,tokencleaner"
    controller-start-interval: "60s"
    feature-gates: "TTLAfterFinished=true"
    root-ca-file: "/etc/kubernetes/pki/ca.crt"
    authorization-kubeconfig: "/etc/kubernetes/controller-manager.conf"
    authentication-kubeconfig : "/etc/kubernetes/controller-manager.conf"
    v: "4"
etcd:
  external:
    endpoints:
    - "https://kube-etcd-1:2379"
    - "https://kube-etcd-2:2379"
    - "https://kube-etcd-3:2379"
    caFile: "/etc/kubernetes/pki/etcd/ca.crt"
    certFile:  "/etc/kubernetes/pki/etcd/server.crt"
    keyFile: "/etc/kubernetes/pki/etcd/server.key"
imageRepository: XXXX
kubernetesVersion: v1.20.0
controlPlaneEndpoint: "kube-master-1:6443"
networking:
  dnsDomain: "cluster.local"
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "192.168.0.0/16"
scheduler:
  extraArgs:
    secure-port: "10259"
    bind-address: "0.0.0.0"
    leader-elect: "true"
    feature-gates: "TTLAfterFinished=true"
apiServer:
  certSANs:
    - "kubernetes"
    - "kubernetes.default"
    - "kubernetes.default.svc"
    - "kubernetes.default.svc.cluster"
    - "kubernetes.default.svc.cluster.local"
  timeoutForControlPlane: "12m0s"
  extraArgs:
      v: "4" 
      external-hostname: "kube-master-1"
      allow-privileged: "true"
      anonymous-auth: "true"
      bind-address: "0.0.0.0"
      apiserver-count: "3"
      etcd-servers: "https://kube-etcd-1:2379,https://kube-etcd-2:2379,https://kube-etcd-3:2379"
      etcd-cafile: "/etc/kubernetes/pki/etcd/ca.crt"
      etcd-certfile: "/etc/kubernetes/pki/etcd/server.crt"
      etcd-keyfile: "/etc/kubernetes/pki/etcd/server.key"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
evictionHard:
    memory.available:  "200Mi"
clusterDomain: cluster.local
FeatureGates:
  TTLAfterFinished: true
cgroupDriver: systemd
staticPodPath: /etc/kubernetes/manifests
failSwapOn: false
EOF
`

#### Environment:
- Kubernetes version (use `kubectl version`): 
 
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: AWS
 
- OS (e.g: `cat /etc/os-release`):    

NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

- Kernel (e.g. `uname -a`): 
Linux kube-master-1 3.10.0-1160.15.2.el7.x86_64 #1 SMP Thu Jan 21 16:15:07 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: 
 kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:57:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Network plugin and version (if this is a network-related bug):   calico cni v1.8.3, coredns v1.7.0, kubernetes v.1.20
- Others:

**Comment by pacoxu** [comment]
I cannot reproduce it with part of your kubeadm configurations. (feature-gates: "TTLAfterFinished=true")
As the error message shows, I suspect the kubelet kubeconfig is not configured correctly. 

- check `/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf` --kubeconfig configuration on the problem node.
- check /etc/kubernetes/kubelet.conf if kubelet is using this file

Simple way to test it:
- kubectl get pod --kubeconfig=/etc/kubernetes/kubelet.conf
- kubectl get pod --kubeconfig=/etc/kubernetes/admin.conf

**Comment by amarjothi** [comment]
[root@kube-master-1 ec2-user]# kubectl get pod --kubeconfig=/etc/kubernetes/kubelet.conf -n=kube-system
NAME                                      READY   STATUS              RESTARTS   AGE
calico-kube-controllers-568b9cfb7-l2bb2   1/1     Running             0          8m56s
calico-node-6g5jm                         1/1     Running             0          79m
coredns-6c6f7bf499-lmkhk                  0/1     ContainerCreating   0          79m
coredns-6c6f7bf499-rwqcd                  0/1     ContainerCreating   0          79m
kube-apiserver-kube-master-1              1/1     Running             0          134m
kube-controller-manager-kube-master-1     1/1     Running             0          134m
kube-proxy-zdwsq                          1/1     Running             0          79m
kube-scheduler-kube-master-1              1/1     Running             0          134m
[root@kube-master-1 ec2-user]# kubectl get pod --kubeconfig=/etc/kubernetes/admin.conf
No resources found in default namespace.
[root@kube-master-1 ec2-user]# kubectl get pod --kubeconfig=/etc/kubernetes/admin.conf -n=kube-system
NAME                                      READY   STATUS              RESTARTS   AGE
calico-kube-controllers-568b9cfb7-l2bb2   1/1     Running             0          9m23s
calico-node-6g5jm                         1/1     Running             0          79m
coredns-6c6f7bf499-lmkhk                  0/1     ContainerCreating   0          79m
coredns-6c6f7bf499-rwqcd                  0/1     ContainerCreating   0          79m
kube-apiserver-kube-master-1              1/1     Running             0          135m
kube-controller-manager-kube-master-1     1/1     Running             0          135m
kube-proxy-zdwsq                          1/1     Running             0          79m
kube-scheduler-kube-master-1              1/1     Running             0          135m

**Comment by amarjothi** [comment]
[root@kube-master-1 ec2-user]# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably
# the user should use the .NodeRegistration.KubeletExtraArgs object in the configuration files instead.
# KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
ExecStart=
ExecStart=/usr/local/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS

**Comment by SataQiu** [comment]
@amarjothi Did you check if Calico is working properly?
I guess this error(`invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable`)  is reported by Calico CNI. 
You can check Calico logs firstly:
```sh
kubectl --kubeconfig=/etc/kubernetes/kubelet.conf logs -f  calico-kube-controllers-568b9cfb7-l2bb2 -n=kube-system 
kubectl --kubeconfig=/etc/kubernetes/kubelet.conf logs -f  calico-node-6g5jm -n=kube-system 
```

**Comment by amarjothi** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-04-01T06:18:33Z"
  generation: 1
  labels:
    k8s-app: kube-dns
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:k8s-app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:k8s-app: {}
          f:spec:
            f:containers:
              k:{"name":"coredns"}:
                .: {}
                f:args: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:livenessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:initialDelaySeconds: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":53,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":53,"protocol":"UDP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":9153,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:readinessProbe:
                  .: {}
                  f:failureThreshold: {}
                  f:httpGet:
                    .: {}
                    f:path: {}
                    f:port: {}
                    f:scheme: {}
                  f:periodSeconds: {}
                  f:successThreshold: {}
                  f:timeoutSeconds: {}
                f:resources:
                  .: {}
                  f:limits:
                    .: {}
                    f:memory: {}
                  f:requests:
                    .: {}
                    f:cpu: {}
                    f:memory: {}
                f:securityContext:
                  .: {}
                  f:allowPrivilegeEscalation: {}
                  f:capabilities:
                    .: {}
                    f:add: {}
                    f:drop: {}
                  f:readOnlyRootFilesystem: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/etc/coredns"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:readOnly: {}
            f:dnsPolicy: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/os: {}
            f:priorityClassName: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:serviceAccount: {}
            f:serviceAccountName: {}
            f:terminationGracePeriodSeconds: {}
            f:tolerations: {}
            f:volumes:
              .: {}
              k:{"name":"config-volume"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:items: {}
                  f:name: {}
                f:name: {}
    manager: kubeadm
    operation: Update
    time: "2021-04-01T06:18:33Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-04-01T07:14:00Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "860521"
  uid: 42108987-741a-435c-be1f-d6d50d32f3bf
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: nexus:5555/coredns:1.7.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: coredns
      serviceAccountName: coredns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          name: coredns
        name: config-volume
status:
  conditions:
  - lastTransitionTime: "2021-04-01T07:14:00Z"
    lastUpdateTime: "2021-04-01T07:14:00Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2021-04-06T16:42:07Z"
    lastUpdateTime: "2021-04-06T16:42:24Z"
    message: ReplicaSet "coredns-6c6f7bf499" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
`

**Comment by amarjothi** [comment]
`[root@kube-master-3 nodeagent]# k describe pod coredns-6c6f7bf499-hxbc2 -n=kube-system
Name:                 coredns-6c6f7bf499-hxbc2
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 kube-worker-2/10.179.16.35
Start Time:           Tue, 06 Apr 2021 17:42:24 +0100
Labels:               k8s-app=kube-dns
                      pod-template-hash=6c6f7bf499
Annotations:          <none>
Status:               Pending
IP:
IPs:                  <none>
Controlled By:        ReplicaSet/coredns-6c6f7bf499
Containers:
  coredns:
    Container ID:
    Image:         nexus:5555/coredns:1.7.0
    Image ID:
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-qh4nn (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-qh4nn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-qh4nn
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly op=Exists
                 node-role.kubernetes.io/control-plane:NoSchedule
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                   From               Message
  ----     ------                  ----                  ----               -------
  Normal   Scheduled               12m                   default-scheduler  Successfully assigned kube-system/coredns-6c6f7bf499-hxbc2 to kube-worker-2
  Warning  FailedCreatePodSandBox  12m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4958172d98b7ebde669a02a66223d770b19629e0e72103ef13975a1aa8712fd4": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  12m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "aa15b405f197403f7940184568947eb185a985a3bdf2cb31fdfe25761939390d": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  12m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "660d7bf1eb2103f36c55ff05f7d1194a876d095877711dfc198bd169473c1dcb": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  11m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "3a157aa1ddb5127b5f68f9e22e0a880e9b3fa28a5f50cce4ef3ae25e328197e0": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  11m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "21a316e3a7dc9aa891a8b6f0e1be2637d144b372874e90910a53825f2da6c9f4": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  11m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ae70a1ccb211efc07947870a2fd62f24e5906ece34ce0785f365ab26e201216b": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  11m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "37449efb96eae2457e17f5d519ba2f9bba81af4134f43f26790ce993fb8d9a6a": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  10m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "169fb97e5d3840ed9ea34ea242b8adc47950db40bcbf84617d2248c7af6110d6": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  10m                   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "074c37354f193e2285a1d25e43bb1fdd7336b810e52ef6dbb045e875a833faa1": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
  Warning  FailedCreatePodSandBox  2m28s (x37 over 10m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "e7dec96b02f2b98853611f9691eb03be55f4034bb52667ec0c3fa45db92367ac": invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
[root@kube-master-3 nodeagent]#
`

calico-node is running on all nodes 1/1 active, still get this error. Am I missing some configuration on the worker node?

**Comment by neolit123** [comment]
did you install the kubelet / kubeadm / ... from the official RPM packages?

the kubelet package installs a package called `kubernetes-cni` that is required by some CNI plugins.

**Comment by amarjothi** [comment]
Not rpm but downloaded binaries

**Comment by neolit123** [comment]
did you install `cni-plugins-linux-amd64-...` ?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
^ you can follow the guide "without a package manager".

but i would suggest you start over and use RPM.

this might solve the problem. but i have not context as mentioned here:
https://github.com/kubernetes/kubernetes/issues/100719#issuecomment-811357011

**Comment by amarjothi** [comment]
# Install the cni plugins
write_to_log 'Install cni plugins'
cd /tmp
cat cni-plugins-linux-amd64-v0.8.2.tgz | tar -C /opt/cni/bin/ -zxvf -

yes I have.

**Comment by neolit123** [comment]
i'd try from scratch with the RPM packages.

**Comment by amarjothi** [comment]
it should work with kubelet binary too right?

**Comment by amarjothi** [comment]
There is no problem with cni, what i meant was - it should work irrespective of using rpm or kubelet binary. I have found the problem, the kubelet config - on all the other nodes other than node 1, are incorrect. I used kubeadm for bootstrapping, on the first node passed in config file.

**Comment by amarjothi** [comment]
there is no problem with the cni - calico nodes are running. What i meant was it should work irrespective of whether it is rpm install or binary install of kubelet. I am checking the kubelet config on the worker nodes.

**Comment by amarjothi** [comment]
there is no problem with the cni - calico nodes are running. What i meant was it should work irrespective of whether it is rpm install or binary install of kubelet. I am checking the kubelet config on the worker nodes. i had used kubeadm for bootstrapping passing in an initial config file, and then kubeadm join.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl
^ you can follow the guide "without a package manager". -> this is exactly what i have followed

**Comment by SataQiu** [comment]
Does calico have `kubeconfig` configured correctly?

```sh
cat /etc/cni/net.d/10-calico.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "kubernetes",
      "nodename": "node",
      "mtu": 1440,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    }
  ]
}
```

**Comment by amarjothi** [comment]
hi, I am using etcd as datastore backend for calico cni, so my conflist as below, also have tried installing kubelet using yum repo instead of binary. And still get the error with coredns.

`[root@kube-master-1 net.d]# cat 10-calico.conflist
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "log_level": "info",
      "datastore_type": "etcdv3",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "etcd_endpoints": "https://kube-etcd-1:2379,https://kube-etcd-2:2379,https://kube-etcd-3:2379",
      "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key",
      "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert",
      "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca",
      "mtu": 0,
      "ipam": {
          "type": "calico-ipam"
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "portmap",
      "snat": true,
      "capabilities": {"portMappings": true}
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    }
  ]
}
`

**Comment by amarjothi** [comment]
[root@kube-master-1 net.d]# k get pods -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   calico-kube-controllers-568b9cfb7-n5q9p   1/1     Running             0          36m
kube-system   calico-node-6m26x                         1/1     Running             0          5d17h
kube-system   calico-node-7pfxg                         1/1     Running             0          5d17h
kube-system   calico-node-8jr95                         1/1     Running             0          5d17h
kube-system   calico-node-brpjz                         1/1     Running             0          44m
kube-system   calico-node-zqn8m                         1/1     Running             0          5d17h
kube-system   coredns-6c6f7bf499-tnq2r                  0/1     ContainerCreating   0          29m
kube-system   coredns-799454bb75-49trd                  0/1     ContainerCreating   0          29m
kube-system   coredns-799454bb75-ms9w2                  0/1     ContainerCreating   0          29m
kube-system   kube-apiserver-kube-master-1              1/1     Running             0          5d21h
kube-system   kube-apiserver-kube-master-2              1/1     Running             0          5d18h
kube-system   kube-apiserver-kube-master-3              1/1     Running             0          5d18h
kube-system   kube-controller-manager-kube-master-1     1/1     Running             0          5d21h
kube-system   kube-controller-manager-kube-master-2     1/1     Running             0          5d18h
kube-system   kube-controller-manager-kube-master-3     1/1     Running             0          5d18h
kube-system   kube-proxy-48wm6                          1/1     Running             0          5d18h
kube-system   kube-proxy-8z5c2                          1/1     Running             0          5d18h
kube-system   kube-proxy-md5nn                          1/1     Running             0          5d20h
kube-system   kube-proxy-mv9f5                          1/1     Running             0          5d18h
kube-system   kube-proxy-vg6w4                          1/1     Running             0          44m
kube-system   kube-scheduler-kube-master-1              1/1     Running             0          5d21h
kube-system   kube-scheduler-kube-master-2              1/1     Running             0          5d18h
kube-system   kube-scheduler-kube-master-3              1/1     Running             0          5d18h

**Comment by amarjothi** [comment]
hi, An update got to the bottom of this, we are using containerd runtime, and cni calico plugin. So to get containerd runtime started, had to create config file in /etc/cni/net.d as 10-calico.conf - once this config was created, crictl info -> showed OK. there was something wrong with containerd, that it didnt recognise 10-calico.conflist as filename.

The .conflist extension is supported for use with configuration lists (rather that .conf, for single plugin config) in the CNI code: https://github.com/containernetworking/cni/blob/6fc72a49e9ad357698b64634d60e0a83300284bf/libcni/conf.go#L186
GitHubGitHub
containernetworking/cni
Container Network Interface - networking for Linux containers - containernetworking/cni

Once containerd was started, used kubeadm for setup and calico for networking. Once calico was installed, it created 10-calico.conflist. So essentially there were **two** **config** files in the /etc/cni/net.d directory. This was reason for coredns throwing the kubelet error - invalid configuration, no configuratin provided, try setting KUBERNETES_MASTER environment variable.

Once I removed the initial conf file(10-calico.conf) i had created for containerd runtime setup. coredns started running.

I am happy to close the issue - just documenting this incase someone else comes across this issue.

**Comment by amarjothi** [comment]
Happy to close.

**Comment by neolit123** [comment]
> Once containerd was started, used kubeadm for setup and calico for networking. Once calico was installed, it created 10-calico.conflist. So essentially there were two config files in the /etc/cni/net.d directory. This was reason for coredns throwing the kubelet error - invalid configuration, no configuratin provided, try setting KUBERNETES_MASTER environment variable.

there was not so long ago an open issue in kubernetes/kubernetes for letting users pick *what* config file the kubelet should use from `/etc/cni/net.d` the issue was closed. https://github.com/kubernetes/kubernetes/issues/100309

as a rule of thumb, try keeping only the configuration that you need in there, or even better - just delete the contents of the folder before cluster creation. calico will write its config there each time the user installs it.
