### ISSUE TITLE
kubelet syncloop failed

### ISSUE THREAD

**Issue by gosoon** [kubernetes/kubernetes#100803]
#### What happened:
The new pod successfully scheduled is always in the pending state,and kubelet did not generate SyncLoop logs,kubelet seems to be stuck somewhere in Syncloop.

After log “SyncLoop (housekeeping)”, no new SyncLoop logs are generated.
```
$ grep "SyncLoop" kubelet.INFO

I0330 15:58:27.145341 4130850 kubelet.go:1966] SyncLoop (PLEG): "reporter-dhrkc_default(2c69ba04-c0de-46a6-adc7-6b050ee97e07)", event: &pleg.PodLifecycleEvent{ID:"2c69ba04-c0de-46a6-adc7-6b050ee97e07", Type:"ContainerStarted", Data:"18b1e68dd2bc5d5ca876651a0457f358586ed6ac90d26b5f0f6e5b1692a65920"}
I0330 15:58:27.146778 4130850 kubelet.go:1966] SyncLoop (PLEG): "reporter-dhrkc_default(2c69ba04-c0de-46a6-adc7-6b050ee97e07)", event: &pleg.PodLifecycleEvent{ID:"2c69ba04-c0de-46a6-adc7-6b050ee97e07", Type:"ContainerStarted", Data:"e4d8c047ef7b330ae61f2258dc9b8359ac422b86212b6a1c9d7e86f0d0ae8c02"}
I0330 15:58:27.936114 4130850 kubelet.go:2012] SyncLoop (housekeeping)
```
There is no useful error log.

```
$ curl http://127.0.0.1:10255/healthz
[+]ping ok
[+]log ok
[-]syncloop failed: reason withheld
healthz check failed
```
Is there a better way to troubleshoot such problems？

#### Environment:
- Kubernetes version (use `kubectl version`):   v1.17.4
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS-7
- Kernel (e.g. `uname -a`):3.10.0-862.el7.x86_64
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): v1.17.4

if this is the kubelet version too, it is out of support.
please try with 1.18+.

/sig node

**Comment by zouyee** [comment]
Please checkout your runtime status

**Comment by gosoon** [comment]
I finally found the problem,kubelet's housekeeping goroutine got stuck when cleaning up the cephfs volume, causing the kubelet syncLoop goroutine to get stuck. The cephfs volume has an error,unable to access it.

**Comment by gosoon** [comment]
I still have some questions. Since kubelet syncloop failed, why is kubelet still ready and did not report an error event?

**Comment by ydp** [comment]
This looks like similar with #101622, which is cause by nfs volume is not accessible.

**Comment by wzshiming** [comment]
SIG Node is reviewing and triaging issues that are relevant to supported versions of Kubernetes as part of a bug scrub.

This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by wzshiming** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Please re-open this bug once you have provided more information.

/triage needs-information
/close
