### ISSUE TITLE
Expose ordinal index as environment variable on statefulset pod

### ISSUE THREAD

**Issue by steeling** [kubernetes/kubernetes#100898]
#### What would you like to be added:

Expose ordinal index as environment variable on statefulset pod. Is there a reason this hasn't already been done? It seems like a simple thing.

#### Why is this needed:

So stateful applications have a consistent identifier. Can be used for sharding workloads.

**Comment by neolit123** [comment]
please fill the issue template correctly and reopen.
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/enhancement.md

/close
/sig apps

**Comment by neolit123** [comment]
to discuss with other users you can try:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by cbandy** [comment]
There is a label with the pod name that can be put into an environment variable using the downward API.

- https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#pod-name-label
- https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api
