### ISSUE TITLE
Density should cleanup better

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#10080]
In cases where one wants to run multiple iterations of density back to back, we really need to make sure a pervious iteration's load doesn't leak into this one. 2 main culprits are:

1. Deleting the namespace will return in a moment, when really it takes like ~15m to delete all events (~20,000 events for 3000 pods). These deletes actually have a bad effect on the next run.
2. We should make sure the pods are actually gone on the kubelet before staring a new run by using the proxy to poll /pods or something. Otherwise we're effectively putting > 30 pods on a node and the kubelet is known to be slow during pod deletes.

This is obviously not a problem if we tear down the entire cluser between iterations.
@gmarek

**Comment by gmarek** [comment]
IMO it's not a problem. In Jenkins we do turn down clusters between runs, and when running manually it's all in hands of the person running.

In my case, when running tests I was always waiting for proper namespace deletion. Delete indeed returns straight away, but `get namespace` still returns namespace in question as "terminating". It's slightly faster than turning down the cluster.

In addition if you want to save the time you don't want to delete pods used to saturate the cluster (those first 30/node), as bringing them up again takes 7-8 minutes. Instead you just play with the test commenting out pieces you don't want to use, rebuild the test, which takes seconds and run it again.
Deleting additional 100 pods together with associated events is pretty quick.

**Comment by gmarek** [comment]
I believe we can close this issue.

**Comment by bprashanth** [comment]
> Instead you just play with the test commenting out pieces you don't want to use, rebuild the test, which takes seconds and run it again.
Deleting additional 100 pods together with associated events is pretty quick.

Sure, there's doing something like that, and theres leaving a clean environment for the next test by default so your tests can run in any order. We have iterations there as a feature, and I think we still run density as part of e2e, so anything that runs after it feels the after effects. It's just too easy to shoot yourself in the foot if you don't do proper cleanup in a test, assuming it's always giong to run alone in a fresh cluster doesn't sound like a good idea even if it happens to work today.

**Comment by gmarek** [comment]
IIUC this (i.e. test isolation) is deeper issue, not only for the Density, but also Load test, and any other e2e that creates non-trivial number of resources.

**Comment by wojtek-t** [comment]
We no longer run those tests as part of regular gce e2e test - see #9858

**Comment by bprashanth** [comment]
See https://github.com/GoogleCloudPlatform/kubernetes/issues/3954#issuecomment-113509698

**Comment by bprashanth** [comment]
The events deletion at least is handled by https://github.com/GoogleCloudPlatform/kubernetes/pull/10175.

**Comment by gmarek** [comment]
Yup. I believe we can close this bug.

**Comment by bprashanth** [comment]
Hmm, there's still the problem of cleaning up containers on the kubelet (delete just removes keys from etcd currently)

**Comment by timothysc** [comment]
@bprashanth details?

**Comment by bprashanth** [comment]
kubectl delete pods doesn't wait till the kubelet has deleted containers on the node

**Comment by timothysc** [comment]
Ohh yeah, that's been that way forever it's non-blocking.

**Comment by gmarek** [comment]
@quinton-hoole @wojtek-t is this still a thing?

**Comment by wojtek-t** [comment]
Currently it's hacked - to provide a clear and fast solution we need to be able to quickly remove the whole namespace and to do it we need to be able to remove a collection of objects in a single step.
But I think we can close it now as a duplicate of https://github.com/kubernetes/kubernetes/issues/10380
