### ISSUE TITLE
Add support for full URL semantics (query params, etc) in webhook URL

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#100888]
#### What would you like to be added:

Support all/more valid URL is webhook URLs. Currently, query params are rejected.

#### Why is this needed:

This is needed to pass information to the webhook server. Because of this limitation, we are required to do gross hacks. We (Istio) originally allowed `webhook.example.com/k1/v1/k2/v2/k3/v3` to pass arbitrary kv pairs. We then found users wanted to pass slashes in they keys, leading to more issues.

URLs have already solved this problem with query params. Rejecting these seems to push major complexity to users.

/sig api-machinery

**Comment by liggitt** [comment]
I think the client used to make the request adds query parameters representing timeouts; would this cause ambiguity merging parameters?

**Comment by howardjohn** [comment]
I think it would cause a small ambiguity perhaps. We could make timeout query param as an input invalid, and allow everything else or overwrite/append (would need to see how repeated query params are handled - maybe it's too messy).
Any of those options would help the cases trying to set anything other than `timeout`

**Comment by luigi-riefolo** [comment]
@liggitt @howardjohn I can start working on it, if that's fine with you

**Comment by liggitt** [comment]
> Any of those options would help the cases trying to set anything other than `timeout`

There's no guarantee that will always be the only query parameter client-go uses in requests (propagating audit IDs comes to mind as a possible future addition). I would tend to avoid introducing situations that lead to ambiguity or confusing between user data and system data.

I'm not completely opposed to the idea, but I haven't seen much demand for it either. A proposal to add this would need to consider the compatibility implications of loosening validation, and the fragmentation implications of webhook configurations not working on API servers between 1.16 and whenever this began to be allowed.
