### ISSUE TITLE
cloud-provider service controller race with node sync and service updates

### ISSUE THREAD

**Issue by kishorj** [kubernetes/kubernetes#100846]
#### What happened:
The cloud-provider service controller handles node sync and service reconcile events independently. The node sync eventually invokes the `UpdateLoadBalancer` for each of the affected service resources. The service reconciler invokes `EnsureLoadBalancer`, `UpdateLoadBalancer`, `EnsureLoadBalancerDeleted` etc. APIs from the cloud provider implementation. Since both of these events are handled concurrently, there can be two concurrent operations on a single service resource in some cases. For example,
- Service "foo" gets deleted, service reconciler invokes `EnsureLoadBalancerDeleted`
- Concurrently, node sync loop picks up worker node update events, it invokes `UpdateLoadBalancer` for service "foo"
Since delete and update are happening concurrently, there is a potential to leak external cloudprovider resources. In extreme cases, concurrent update can re-create the external LB resource which has been deleted as part of the delete operation.

#### What you expected to happen:
From the API interface perspective, it looks unusual for the `Update` method to get invoked after the`Delete` method on the same resource. If the contract enforces this consistency, the underlying vendor implementation gets simplified. Ideally, the cloud-provider controller should put the events from the node sync loop and the service updates into the same reconcile queue. That way the cloudprovider APIs will not get invoked concurrently for the same resources. 

#### How to reproduce it (as minimally and precisely as possible):
Service delete and node sync happens at the same time.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bowei** [comment]
Given the fragility of the API contracts and N provider implementations, it's probably better for the implementations to implement handling for the looser contract rather than try to give stricter guarantees at this level.

**Comment by khenidak** [comment]
Hi @kishorj, Thanks for this  -- Exactly which node reconciler that calls into cloud provider's `*LoadBalancer*()` funcs?

**Comment by andrewsykim** [comment]
> Ideally, the cloud-provider controller should put the events from the node sync loop and the service updates into the same reconcile queue.

This makes a lot of sense and should be fairly easy change to make in service controller

**Comment by bowei** [comment]
Putting it on the queue does not mean operations are linearized -- it's possible to have multiple queue threads that are operating in concurrently.

**Comment by andrewsykim** [comment]
I feel like `UpdateLoadBalancer` should just call `EnsureLoadBalancerDeleted` whenever the deletion timestamp is set? Would that simplify things here?

**Comment by andrewsykim** [comment]
Alternatively, [nodeSyncService](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L741-L759) should check `needsCleanup` [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cloud-provider/controllers/service/controller.go#L743-L745)
