### ISSUE TITLE
Admission webhook metrics improvement

### ISSUE THREAD

**Issue by voutcn** [kubernetes/kubernetes#100871]
#### What would you like to be added:

- Add a `namespace` label to admission webhook related [metrics](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L125-L157)
- Extend the max value of the webhook latency histogram buckets metrics to 10s

#### Why is this needed:
Bad admission webhooks can reject/timeout/fail critical requests like kube-controller-manager (KCM) and kube-scheduler (KS) lease renewal. Such failures are not very visible because the admission webhook metrics do not record the resource or the namespace of a request. Adding a `namespace` label will make such failures easier to detect without increasing the cardinality of the metrics significantly.

The range of the webhook latency histogram 0-2.5s. Some critical requests like leader elections have a 10s default timeout, so the extending the buckets to 10s will allow us to observe the 10s timeout.

/sig instrumentation
/sig api-machinery

**Comment by dashpole** [comment]
/triage accepted

This was discussed at the last sig meeting

**Comment by MadhavJivrajani** [comment]
Hi! I'd like to work on this if possible 😄 
/assign

**Comment by voutcn** [comment]
Thank you @MadhavJivrajani! Have you started? Otherwise I will create a PR.

**Comment by voutcn** [comment]
Hey @MadhavJivrajani. I created a PR (the code was ready a few days ago but I did not commit), and assigned you as a reviewer since you are interested.

**Comment by MadhavJivrajani** [comment]
Hey @voutcn, I was unable to work on this. Thanks for letting me know! 😄
