### ISSUE TITLE
Create a logging style guide

### ISSUE THREAD

**Issue by scottilee** [kubernetes/kubernetes#100843]
#### What happened:
While working on adding structured logs to the codebase I noticed there's inconsistencies in how logs are written. For instance, the word "csr" would be [lowercase in some log statements](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/certificate_controller.go#L177) and [uppercase in other log statements](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/certificate_controller.go#L100).

#### What you expected to happen:
There should be a style guide covering:
* capitalization: should resources like "pod" be capitalized? What about things like "uid" or "id"?
* structured log keys: should structured logs keys be capitalized or lowercased? how should spaces be handled?
```
# capitalized?
klog.V(4).InfoS("Updating Certificate request", "CSR", oldCSR.Name)

# lowercased?
klog.V(4).InfoS("Updating Certificate request", "csr", oldCSR.Name)

# spacing handled with camelcase?
klog.V(4).InfoS("Updating Certificate request", "oldCSR", oldCSR.Name)

# spacing handled with underscores?
klog.V(4).InfoS("Updating Certificate request", "old_csr", oldCSR.Name)

# spacing handled with @?
klog.V(4).InfoS("Updating Certificate request", "old@csr", oldCSR.Name) # probably not, but you get the idea
```
* probably lots of other stuff too

#### How to reproduce it (as minimally and precisely as possible):
Browse the code and see the madness.

#### Anything else we need to know?:
No.

#### Environment:
N/A

/sig instrumentation
/cc @logicalhan

**Comment by serathius** [comment]
Please check out our migration guide https://groups.google.com/forum/#!forum/kubernetes-wg-structured-logging
Let me know if there is anything missing or unclear

**Comment by scottilee** [comment]
> Please check out our migration guide https://groups.google.com/forum/#!forum/kubernetes-wg-structured-logging
> Let me know if there is anything missing or unclear

@serathius When I go to that link it's a Google Group with no conversations. Where exactly can I find the migration guide?
<img width="1189" alt="Screen Shot 2021-04-06 at 6 41 26 AM" src="https://user-images.githubusercontent.com/7443383/113720102-26d10400-96a3-11eb-9cb5-b31bb77ed25f.png">

**Comment by serathius** [comment]
Oh sorry, error when copy-pasting
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md

**Comment by scottilee** [comment]
Okay, that works!
