### ISSUE TITLE
Experimental patches ignores etcd on join phase control-plane-prepare

### ISSUE THREAD

**Issue by perezjasonr** [kubernetes/kubernetes#100869]
#### What happened:

Using kubeadm join phase control-plane-prepare all <join string> --experimental-patches /path/to/dir
adds the patch for everything except etcd

#### What you expected to happen:

I expect the patch to include etcd

#### How to reproduce it (as minimally and precisely as possible):

create a patch file for all 4 manifests that kubeadm generates

do an init with experimental patches

note the manifests include the patch for all components including etcd

get the join info for another master node

put the exact same patch file(s) on the joining node

do the join phases, when you get to `kubeadm join phase control-plane-prepare all <join string> --experimental-patches /path/to/dir` the kube-* manifests have the patch, etcd will not be patched.

#### Anything else we need to know?:

this only seems to be an issue on join. for init-ing a master etcd is fine and it gets its patch.

also i noticed `kubeadm join phase control-plane-join` only has the experimental patches option if you do etcd and not all, I'm not sure what thats for but in the order of phases kubelet is already started and it spins up etcd so obviously that patch must be for something else? and also I'm of the impression if I picked etcd there and not all, id lose functionality of the other components and this is not an etcd only node.

is there some logic missing where the patches dir is not acknowledged if you do it by phases?

#### Environment:
- Kubernetes version (use `kubectl version`): 
1.20.4
- Cloud provider or hardware configuration:
cloud/aws
- OS (e.g: `cat /etc/os-release`):

NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

- Kernel (e.g. `uname -a`):

Linux ip-10-42-21-222.us-east-2.compute.internal 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Wed Feb 3 03:12:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

kubeadm

- Network plugin and version (if this is a network-related bug): n/a
- Others: n/a

**Comment by neolit123** [comment]
hi,

kubeadm join creates a manifest file as part of the phase `control-plane-join`, not the `control-plane-prepare` phase:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L150
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/

something else to note is that kubeadm init/join process can be broken down into phases completely this is not something that the kubeadm team recommends, since it makes it very difficult to adapt to phase order changes or phase additions / removals.

instead we recommend to do only skip certain phases using --skip-phases.

/kind support
/area kubeadm
/close

i will close this but LMK if you have more questions.

**Comment by neolit123** [comment]
> also i noticed kubeadm join phase control-plane-join only has the experimental patches option if you do etcd and not all, I'm not sure what thats for but in the order of phases kubelet is already started and it spins up etcd so obviously that patch must be for something else? and also I'm of the impression if I picked etcd there and not all, id lose functionality of the other components and this is not an etcd only node.

this seems accurate to me:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L46-L47

the patches only matter for the etcd sub-command/phase that generates the etcd manfiest.

**Comment by perezjasonr** [comment]
> hi,
> 
> kubeadm join creates an etcd manifest file as part of the phase `control-plane-join`, not the `control-plane-prepare` phase:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L150
> https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
> 
> for the other components you should be able to apply patches at the `control-plane-prepare` phase.
> 
> something else to note is that while the kubeadm init/join process can be broken down into phases completely this is not something that the kubeadm team recommends, since it makes it very difficult to adapt to phase order changes or phase additions / removals.
> 
> instead we recommend to only skip certain phases using --skip-phases and execute them out of band.
> 

thank you for the explanation. I would have rather not done phases manually but due to project requirements (namely, not being able to assign folder permissions for dirs that kubeadm manages) we had to do it atomically. Although I haven't tried skip phases.


> > also i noticed kubeadm join phase control-plane-join only has the experimental patches option if you do etcd and not all, I'm not sure what thats for but in the order of phases kubelet is already started and it spins up etcd so obviously that patch must be for something else? and also I'm of the impression if I picked etcd there and not all, id lose functionality of the other components and this is not an etcd only node.
> 
> this seems accurate to me:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L46-L47
> 
> the patches only matter for the etcd sub-command/phase that generates the etcd manifest.
> i guess we could have added it for `all`, but this feels less accurate and `-prepare` is doing that (less accurate option):
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplaneprepare.go#L81
> 
> the kubelet being already started is by design, due to a complication:
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/cmd/phases/join/controlplanejoin.go#L140-L152
> 
> if you have objections to this design or other requests please log a kubernetes/kubeadm ticket.

I guess it makes more sense now that you've explained it but I still don't understand which join command is supposed to do in the end if the node is not only an etcd node. 

Unless were suggesting that I can do etcd, then "all" after that? so same command twice? I dont want to lose the functionality of preparing the full master node. but it could also be my misunderstanding that it must be one or the other. In either case I think others will find it misleading that "all" doesn't include the etcd call.

but of course, thank you for your explanations

**Comment by neolit123** [comment]
> thank you for the explanation. I would have rather not done phases manually but due to project requirements (namely, not being able to assign folder permissions for dirs that kubeadm manages) we had to do it atomically. Although I haven't tried skip phases.


this is an interesting use case. can you explain the folder permissions problem in more detail with examples?

> I guess it makes more sense now that you've explained it but I still don't understand which join command is supposed to do in the end if the node is not only an etcd node.

you can try to pass patches to the whole `control-plane-prepare all`, but break down the `control-plane-join` into its sub-phases and pass the patches only to the `etcd` sub-phase.

```bash
kubeadm join phase preflight --config ...
kubeadm join phase control-plane-prepare all --experimental-patches ... --config ...
kubeadm join phase kubelet-start --config ...
kubeadm join phase control-plane-join etcd --experimental-patches ... --config ...
kubeadm join phase control-plane-join update-status --config ...
kubeadm join phase control-plane-join mark-control-plane --config ...
```

> Unless were suggesting that I can do etcd, then "all" after that? so same command twice? I dont want to lose the functionality of preparing the full master node. but it could also be my misunderstanding that it must be one or the other. In either case I think others will find it misleading that "all" doesn't include the etcd call, or at the very least strange that it does include the etcd call but just not the patches option you'd get if you did just etcd.

i agree that the lack of consistency is misleading here.
i've logged an issue for that and we can discuss it.

https://github.com/kubernetes/kubeadm/issues/2435

**Comment by perezjasonr** [comment]
> this is an interesting use case. can you explain the folder permissions problem in more detail with examples?
> 

absolutely!
if youre familiar with platform One, the control plane components do not run as root. they run as 1000 or 1001 etc...

so obviously as you said its a strange use case and certainly out of the norm, but kubeadm doesn't accommodate this, naturally the components crash since they cannot read the certs and such owned by root per kubeadm. What I ended up doing is atomically breaking down the phases and in between certain steps I change the permissions for various dirs and files so that control plane components can read them. It seems to work so far!

the latest and greatest issue as you are now aware is that with enabling selinux and with latest containerd versions properly respecting selinux contexts I now use the patch feature which led me here on the phase join.

and now youve gone down the path with me haha.

> you can try to pass patches to the whole `control-plane-prepare all`, but break down the `control-plane-join` into its sub-phases and pass the patches only to the `etcd` sub-phase.
> 
> ```shell
> kubeadm join phase preflight --config ...
> kubeadm join phase control-plane-prepare all --experimental-patches ... --config ...
> kubeadm join phase kubelet-start --config ...
> kubeadm join phase control-plane-join etcd --experimental-patches ... --config ...
> kubeadm join phase control-plane-join update-status --config ...
> kubeadm join phase control-plane-join mark-control-plane --config ...
> ```
> 

thank you I actually started experimenting immediately and patches w/ prepare all then etcd join w/ patches, then join all obviously did not work as that seems to have overwritten the manifest (was worth a try)

then doing exactly what you mentioned, patches w/ prepare all then breaking down the join phase etcd w/ patches, update-status, mark control plane seems to have done the trick.

> i agree that the lack of consistency is misleading here.
> i've logged an issue for that and we can discuss it.
> 
> [kubernetes/kubeadm#2435](https://github.com/kubernetes/kubeadm/issues/2435)

excellent! ill check it out.

**Comment by neolit123** [comment]
> so obviously as you said its a strange use case and certainly out of the norm, but kubeadm doesn't accommodate this, naturally the components crash since they cannot read the certs and such owned by root per kubeadm. What I ended up doing is atomically breaking down the phases and in between certain steps I change the permissions for various dirs and files so that control plane components can read them. It seems to work so far!

i don't see how we can make the kubeadm process to stop requiring root, since it has to execute `systemctl ...` to start the kubelet.
but for the overall folder permissions problem this might be interesting to you:
https://github.com/kubernetes/enhancements/labels/sig%2Fcluster-lifecycle

please give your comments if you have any.

> the latest and greatest issue as you are now aware is that with enabling selinux and with latest containerd versions properly respecting selinux contexts I now use the patch feature which led me here on the phase join.

there might other complexities that we are completely unaware of.
the kubeadm maintainers have mostly deferred the host and container security solution / setup (e.,g. selinux) to the user.
we don't have e2e tests for it either.

> then doing exactly what you mentioned, patches w/ prepare all then breaking down the join phase etcd w/ patches, update-status, mark control plane seems to have done the trick.

ok, good to hear.

**Comment by perezjasonr** [comment]
> i don't see how we can make the kubeadm process to stop requiring root, since it has to execute `systemctl ...` to start the kubelet.
> users / distros might be able to workaround that with a placeholder non-root `sysctl`, somehow.

sorry to clarify, kubeadm itself is run as root, its the control plane components that do not so we go in (again as root) and manually modify perms of the folders kubeadm creates/managers etc...youre right theres no way to not run kubeadm as root because of systemctl and such this was just for containers kubelet spins up.

> but for the overall folder permissions problem this might be interesting to you:
> https://github.com/kubernetes/enhancements/labels/sig%2Fcluster-lifecycle
> 
> please give your comments if you have any.

ok lemme check it out.

> there might other complexities that we are completely unaware of.
> the kubeadm maintainers have mostly deferred the host and container security solution / setup (e.g. selinux) to the user.
> we don't have e2e tests for it either.

yes and indeed i do expect to deal with the selinux stuff and don't hold kubeadm accountable for that one, one of which was patching in the selinux context to the control plane components (thank goodness for the patch feature).

**Comment by perezjasonr** [comment]
@neolit123 sorry i know this issue is closed and we should keep it closed but I realized theres no experimental patches for addons like kube-proxy, or coredns, as such I cannot customize these manifests, is this deliberate? I'm guessing theres some reason I'm not aware of why these do not have the patch option. TY.

**Comment by neolit123** [comment]
We do not have plans to allow addon patches, because we are in the process
of creating a better addon story. The current addons might no longer be
hardcoded in kubeadm in the future.

For now you can skip them and deploy your own custom ones.

**Comment by perezjasonr** [comment]
fair enough thanks for the insight.
