### ISSUE TITLE
sig-node-arm64 test grid is stale

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#100800]
@lubinsz @vielmetti https://testgrid.k8s.io/sig-node-arm64#Summary seems out of date. Could we get things green before we release 1.21 this week? if we can't get a reliable signal, then we should probably reconsider this set of CI jobs showing up in test grid.

/sig node

**Comment by vielmetti** [comment]
@dims Happy to help - any suggestions welcomed. In particular I'm not sure what exact hardware these tests are running on, and I could potentially provide something.

**Comment by dims** [comment]
@vielmetti we need the original developers of the arm64 jobs to respond and revive what they were running earlier (and reporting to test grid) :( 

Looks pretty bad 

![image](https://user-images.githubusercontent.com/23304/113773064-7fc88880-96f3-11eb-8c31-3c8a829c39d4.png)

**Comment by zhlhahaha** [comment]
Hi @dims @vielmetti, I will take a look at this issue.
