### ISSUE TITLE
glusterfs CSI migration support or deprecation needed

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#100897]
CSI migration is an effort to enable smooth transition from intree volume plugin usage to CSI driver usage. 
Context: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/

Currently we are trying to evaluate for non-cloud provider plugins if they are in the interest of CSI migration support. If not, we will plan to mark them as deprecated and remove the source code from core kubernetes in the later releases.

For glusterfs, please let us know if CSI migration support is still in their roadmap or we should mark it as deprecated. 

/sig storage
/cc @msau42 @saad-ali 
/cc @humblec @jsafrane @gnufied

**Comment by amarts** [comment]
For the users who wants to use glusterfs with CSI, there is an option available - https://github.com/kadalu/kadalu/

Hence for a large project like kubernetes, if glusterfs is the only volume plugin delaying the CSI migration, users can be pointed to kadalu project and glusterfs can be marked deprecated. @humblec is that fine?

meantime, from kadalu project we will see what we can do to help users migrate to CSI based deployment smoothly! (and would update this thread).

**Comment by humblec** [comment]
> For the users who wants to use glusterfs with CSI, there is an option available - https://github.com/kadalu/kadalu/

Yes, at the same time we got our initial Gluster CSI driver working a way back here https://github.com/gluster/gluster-csi-driver.
Just wondering or trying to find an opinion on whether we should revamp gluster CSI driver project itself. The advantage we get here is the smooth migration from in tree driver to CSI.  From the kube community and outside, we know many production deployments are running with in tree gluster drivers , so we have to really make a poll and take the call.

> 
> Hence for a large project like kubernetes, if glusterfs is the only volume plugin delaying the CSI migration, users can be pointed to kadalu project and glusterfs can be marked deprecated. @humblec is that fine?

Its not the case atm, but half of them migrated ( mainly cloud providers) and rest are getting planned on doing migration to CSI or marking `deprecated` . So we are left with some time but we have to make a decision too.

> 
> meantime, from kadalu project we will see what we can do to help users migrate to CSI based deployment smoothly! (and would update this thread).

Thats one option as well, however considering both  models are bit different , we have to check is there a  possibility of smooth migration.

**Comment by humblec** [comment]
@Jiawei0227 I have kickstarted some discussions in the backend about our take on GlusterFS plugin forward. However I would like to officially take a survey/poll from couple of communities ( kubernetes and glusterfs) before we move on.  To take a feedback from kubernetes community, is there an official way of launching a Poll/Survey on deprecation of a plugin..etc? @saad-ali @jsafrane @msau42 @xing-yang  . I believe its important to take a decision based on community feedback  considering the plugin existed for long time ( since v1..4 or since 2016 https://github.com/kubernetes/kubernetes/pull/30888)  . Meanwhile we will also do the same from gluster community. 

@amarts can we trigger a poll from glusterfs community as well?  I can help on this as well.

**Comment by amarts** [comment]
> @amarts can we trigger a poll from glusterfs community as well? I can help on this as well.

Sure @humblec! Lets get a poll running in gluster mailing lists. We surely need to include heketi community (considering I see many users who only watches changes there, and not glusterfs) too. @phlogistonjohn @raghavendra-talur

**Comment by sftim** [comment]
There is also https://blog.k8s.io/ and / or https://k8s.dev/blog/ to publicize the CSI driver migration generally and to highlight specific calls for participation like this.

**Comment by mattcary** [comment]
@dannylee- some of the mechanisms that glusterfs needs are starting to be deprecated, eg the --experimental-mounter-path flag is deprecated upstream and will be removed, for example, in GKE in the ~1.24 time frame.

It sounds like https://github.com/kadalu/kadalu/ is the migration story---is that still true?

**Comment by amarts** [comment]
> It sounds like https://github.com/kadalu/kadalu/ is the migration story---is that still true?

from kadalu project, we don't have 'online' migration completed yet. But sure, for anyone wanting to have glusterfs as an option in k8s, they can use kadalu :+1:

**Comment by dannylee-** [comment]
Isn't Kadalu still in beta?  It's currently at 0.8.10.

**Comment by dims** [comment]
cc @phlogistonjohn

**Comment by humblec** [comment]
@amarts as per our discussions some time back, the technical feasibility of a migration path to kadalu project via translation lib were being explored, do we have some conclusion on the same?  If we see a technical difficulty to achieve or plug kadalu on the translation path,  I would like to propose glusterfs driver deprecation in upcoming Kubernetes release.  The main reason being its becoming hard to maintain without the support from heketi  ( https://github.com/heketi/heketi) which is in maintenance mode, Please revert, so that I can take this forward.

**Comment by amarts** [comment]
@humblec here is my take.

The online migration path is not possible right now for applications (ie, there will have to be re-mount of the client mount). The option to use the kadalu/kadalu project to consume data is possible even if the [previous volumes are created using heketi](https://kadalu.github.io/blog/importing-a-gluster-volume-to-kadalu-storage/). With that, I feel its good to reference this as a documentation of how to migrate 'data' off-line into another PV, and take this issue to logical conclusion by removing gluster reference from k8s. 

We are happy to assists the users on case-by-case if they want support for migration, but getting this feature to support online migration is bit out of scope for kadalu development team too at this time.

Vote for driver deprecation for future k8s releases.

**Comment by dims** [comment]
`deprecation in 1.25 and removal in 1.26` per note to the mailing list - https://groups.google.com/g/kubernetes-sig-storage/c/EnjJYaka_i8/m/0bnz1IuyBAAJ

**Comment by xing-yang** [comment]
GlusterFS code is already removed.  This issue can be closed now.

**Comment by liggitt** [comment]
It looks like there are a couple CSI options referenced, but I don't see a documented migration path. @humblec @msau42 - can we get a documented migration procedure on the website to point folks to who are upgrading to 1.26?
