### ISSUE TITLE
Enable dual-stack tests on windows

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#100870]
Currently the dual-stack tests are marked `LinuxOnly`: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dual_stack.go

We should be able to enable some of these tests for windows too as a first step for setting up windows dual-stack periodic jobs.

/assign
/cc @aojea 

/sig network
/sig testing

**Comment by jsturtevant** [comment]
This will require Windows Server 2004+ (10.0.19041+)

**Comment by aramase** [comment]
Thanks, James! Adding the doc here for reference: https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack

**Comment by aojea** [comment]
wow, impressive, didn't know that this was possible :clap:
