### ISSUE TITLE
k8s cluster failure recovery

### ISSUE THREAD

**Issue by bidianqing** [kubernetes/kubernetes#100967]
#### What happened:
I success build high-availability k8s cluster include three master instance, When I  destroy one master, the k8s cluster normal worker. When I  destroy two master, the k8s cluster  all the paralysis.  Of this time, "LOAD_BALANCER_DNS:LOAD_BALANCER_PORT" is not connection. I not way recover the k8s cluster.
![image](https://user-images.githubusercontent.com/12196280/114208708-5c6e3980-9990-11eb-9fd9-0c6eb4064ff2.png)

#### What you expected to happen:
I want the k8s normal working

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: Alibaba Cloud
- OS (e.g: `cat /etc/os-release`): CentOS 7
- Kernel (e.g. `uname -a`):
- Install tools:Kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/remove-kind bug
/kind support 

this seems like a question for the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
