### ISSUE TITLE
increase ssh timeout

### ISSUE THREAD

**Issue by bilalcaliskan** [kubernetes/kubernetes#100918]
Hello, 

I have opened a [PR](https://github.com/kubernetes/node-problem-detector/pull/533) to [node-problem-detector](https://github.com/kubernetes/node-problem-detector) but node-problem-detector uses [k8s.io/kubernetes/pkg/ssh](https://github.com/kubernetes/kubernetes/tree/master/pkg/ssh) as ssh library and `sshDialTimeout` set in [right here](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L166). [In that failing merge check](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/node-problem-detector/533/pull-npd-e2e-test/1379563125270908928#1:build-log.txt%3A222) there is ssh connectivity errors, so to be able to debug the problem we need to increase `sshDialTimeout` constant in [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/ssh/ssh.go#L166)

**Comment by BenTheElder** [comment]
hmm @dims should we be filing a bug about https://github.com/kubernetes/node-problem-detector/blob/fc0edbd222e16b775ec58a253366a41822ecb3d5/go.mod#L37-L38

**Comment by ehashman** [comment]
@BenTheElder there are a lot of external things importing it: https://cs.k8s.io/?q=%22k8s.io%2Fkubernetes%2Fpkg%2Fssh%22&i=nope&files=&excludeFiles=&repos=

**Comment by bilalcaliskan** [comment]
@BenTheElder do you mean the version of the **k8s.io/kubernetes** and **k8s.io/test-infra** ?  What should be the imported version on https://github.com/kubernetes/node-problem-detector/blob/fc0edbd222e16b775ec58a253366a41822ecb3d5/go.mod#L37-L38?

**Comment by BenTheElder** [comment]
@ehashman we should probably stage that package then or move it to https://github.com/kubernetes/utils.

k8s.io/kubernetes imports are unsupported.

Importing test-infra is not a great idea either, it's another monorepo with heavy dependencies and it isn't versioned.

**Comment by dims** [comment]
@ehashman other than NPD, all others are either tests or vendor, So i'd recommend NPD pick up a copy and maintain it.
