### ISSUE TITLE
removal of the BlockVolume feature gate was not announced under "action required"

### ISSUE THREAD

**Issue by aholler** [kubernetes/kubernetes#100988]
#### What happened:

kubeadm upgrade apply 1.21.0 failed on a cluster with 1.20.5. The new apiserver did not start.

#### What you expected to happen:

A successful upgrade.

#### How to reproduce it (as minimally and precisely as possible):

Enable the feature gate BlockVolume on a cluster with 1.20.5 and try kubeadm upgrade.

#### Anything else we need to know?:

I had to edit the manifests in /etc/kubernetes/manifests and the configmap kubeadm-config in order to remove the feature flag BlockVolume. (I edited both, the manifests and the configmap but I'm not sure which change was required)

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: AMD64 and ARM64
- OS (e.g: `cat /etc/os-release`): Ubuntu
- Kernel (e.g. `uname -a`): 5.4.0
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): kilo
- Others:

At least I would expect to find such "blockers" in the changelog in the section "Urgent Upgrade Notes" and not just under "Other (Cleanup or Flake)". It would also be great if kubeadm would find such problems before trying to upgrade.

Finding the problem isn't really obvious, you have to use e.g. docker to look at the log of the failed container for the apiserver (while kubeadm tries to upgrade).

Best regards,

Alexander

**Comment by aholler** [comment]
To describe my installation a bit more, I've used the following yaml to install the cluster(s) with kubeadm:

---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
featureGates:
  IPv6DualStack: true
apiServer:
  extraArgs:
    feature-gates: TTLAfterFinished=true,BlockVolume=true,ImmutableEphemeralVolumes=true
scheduler:
  extraArgs:
    feature-gates: TTLAfterFinished=true,BlockVolume=true,ImmutableEphemeralVolumes=true
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true,BlockVolume=true,ImmutableEphemeralVolumes=true
...
---

**Comment by pacoxu** [comment]
#98021 related

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/pull/98021
has a release note for the removal of deprecated flags:

>> The deprecated feature gates `CSIDriverRegistry`, `BlockVolume` and `CSIBlockVolume` are now unconditionally enabled and can no longer be specified in component invocations.

so this is already in the changelog, but it's not under the action required section as you pointed out:

> At least I would expect to find such "blockers" in the changelog in the section "Urgent Upgrade Notes" and not just under "Other (Cleanup or Flake)". It would also be great if kubeadm would find such problems before trying to upgrade.

**Comment by neolit123** [comment]
>  It would also be great if kubeadm would find such problems before trying to upgrade.

that is completely out of scope for kubeadm and not so easy to execute.

**Comment by neolit123** [comment]
/retitle removal of the BlockVolume feature gate was not announced under "action required"

leaving this open of SIG Storage wish to comment, but there is not much we can at this point.

**Comment by aholler** [comment]
What would help too is if kubeadm would output the log of the failed container (the apiserver in this case) if it fails to come up.

Maybe that's easier to implement than a check for valid feature flags. It also might be in the scope of kubeadm.

E.g. in the above case the message in the log of the failed apiserver was pretty clear, it just was not obvious to see it because kubeadm does not show it.

**Comment by neolit123** [comment]
This diverges from the original kubeadm design too. Kubeadm just starts the
kubelet that manages the static pods and does not block for them to start.

Even if it blocks, they might fail 1 minute later in resource constrained
cases.

**Comment by msau42** [comment]
I agree it was an oversight to not put the release note under ACTION_REQUIRED. Thank you for the feedback and we'll be sure to correct this in the future.

The remaining discussion sounds more related to kubeadm improvements.

/remove-sig storage
/sig cluster-lifecycle

**Comment by neolit123** [comment]
i guess at this point we can close this.
kubeadm has no logic (or a way) to detect missing feature gates in core components.

/close
