### ISSUE TITLE
[Failing Test] gce-ubuntu-containerd jobs failing

### ISSUE THREAD

**Issue by swetharepakula** [kubernetes/kubernetes#100978]
#### Which jobs are failing:
Both jobs are failing with the same error message.
pull-kubernetes-e2e-gce-ubuntu-containerd
gce-ubuntu-master-containerd

#### Which test(s) are failing:
Tests are not run as clusters fail to come up.

#### Since when has it been failing:
gce-ubuntu-master-containerd:  Cluster creations failures started 2021/04/09 05:09 AM PST.
pull-kubernetes-e2e-gce-ubuntu-containerd: Cluster creation failures started around 2021/04/08 3:15 AM PST
#### Testgrid link:
https://testgrid.k8s.io/google-gce#gce-ubuntu-master-containerd
https://testgrid.k8s.io/google-gce#pull-kubernetes-e2e-gce-ubuntu-containerd

#### Reason for failure:
Cluster creation script fails
```
error during ./hack/e2e-internal/e2e-up.sh: exit status 2
```

**Comment by neolit123** [comment]
> 0410 20:45:23.570748   10893 config.go:383] "Receiving a new pod" pod="kube-system/etcd-server-events-e2e-196dc19dab-a7d53-master"
I0410 20:45:23.570839   10893 config.go:383] "Receiving a new pod" pod="kube-system/etcd-server-e2e-196dc19dab-a7d53-master"
I0410 20:45:23.570952   10893 config.go:383] "Receiving a new pod" pod="kube-system/kube-apiserver-e2e-196dc19dab-a7d53-master"
I0410 20:45:23.571048   10893 config.go:383] "Receiving a new pod" pod="kube-system/kube-controller-manager-e2e-196dc19dab-a7d53-master"
E0410 20:45:23.572726   10893 remote_runtime.go:86] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
E0410 20:45:23.573108   10893 kuberuntime_manager.go:208] "Get runtime version failed" err="get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
E0410 20:45:23.573226   10893 server.go:292] "Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
kubelet.service: Main process exited, code=exited, status=1/FAILURE
kubelet.service: Failed with result 'exit-code'.

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/100942/pull-kubernetes-e2e-gce-ubuntu-containerd/1380977958105124864/artifacts/e2e-196dc19dab-a7d53-master/kubelet.log

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100942/pull-kubernetes-e2e-gce-ubuntu-containerd/1380977958105124864/

**Comment by thejoycekung** [comment]
Looks like infra-commit is https://github.com/kubernetes/test-infra/commit/eca83d2ac
related PR: https://github.com/kubernetes/test-infra/pull/21735
/cc @dims

**Comment by dims** [comment]
fix is going in here https://github.com/kubernetes/kubernetes/pull/100992
