### ISSUE TITLE
quobyte CSI migration support or deprecation needed

### ISSUE THREAD

**Issue by Jiawei0227** [kubernetes/kubernetes#100900]
CSI migration is an effort to enable smooth transition from intree volume plugin usage to CSI driver usage.
Context: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/

Currently we are trying to evaluate for non-cloud provider plugins if they are in the interest of CSI migration support. If not, we will plan to mark them as deprecated and remove the source code from core kubernetes in the later releases.

For quobyte, please let us know if CSI migration support is still on the roadmap or we should mark it as deprecated in the 1.22 release.

/sig storage
/triage accepted
/cc @msau42 @saad-ali @jsafrane 
/cc  @venkatsc @tksm

**Comment by Jiawei0227** [comment]
Gentle ping.

**Comment by venkatsc** [comment]
@Jiawei0227 Please deprecate the in-tree plugin and updated any old references to our [Quobyte CSI](https://github.com/quobyte/quobyte-csi#quobyte-csi) repo.

Thank you.

**Comment by Jiawei0227** [comment]
This is deprecated here: https://github.com/kubernetes/kubernetes/pull/101773

**Comment by Jiawei0227** [comment]
/remove-lifecycle stale
The plugin support is already deprecated. Will be removed in a later release.
