### ISSUE TITLE
Provide a "roadmap" for what users can do post install (+ example).

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#10098]
"Next Steps" Roadmap (post-installation-&-examples info):
Need to provide a high-level, general path that applies to all users for moving forward with k8s (ie. install and example done, Now what?).

Examples:
- You created a cluster on a single node, see how to scale to meet your production needs:
  - point to creating more nodes, clusters
  - sharing cluster access
  - security, etc.
- Now you can set up:
  - configuration management tools?
  - networking, security, performance related configuration?
  - Migrate to production? -> mention and point to the "Planning and Design Considerations"

**Comment by roberthbailey** [comment]
This looks obsolete and we've done one (or maybe two) large documentation refactorings since it was filed so I'm going to close it.
