### ISSUE TITLE
PowerShell install cannot find kubectl.exe at default link

### ISSUE THREAD

**Issue by nextMJ** [kubernetes/kubernetes#100946]
#### What happened:
While installation on Windows with PowerShell tool, the script tries to find the link to `kubectl.exe` at address `https://kubernetes.io/docs/tasks/tools/install-kubectl/` but the link is not there.

#### What you expected to happen:
Find the link to a file and install kubernetes :-)

#### How to reproduce it (as minimally and precisely as possible):
I did everything written at [this](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-with-powershell-from-psgallery) link, so:
- `Install-Script -Name 'install-kubectl' -Scope CurrentUser -Force`
- `install-kubectl.ps1 -DownloadLocation "C:\kubectl"`

,and I get this error:
```
==>Getting download link from  https://kubernetes.io/docs/tasks/tools/install-kubectl/
==>analyzing Downloadlink
==>starting Download from  using Bitstransfer
ERROR: Start-BitsTransfer : Cannot validate argument on parameter 'Source'. The argument is null or empty. Provide an argument
 that is not null or empty and then try the command again.
```

#### Environment:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: localhost
- OS (e.g: `cat /etc/os-release`): Windows 10
- Install tools: PowerShell

**Comment by jsturtevant** [comment]
looks like the script is trying to parse a link that is no longer valid: https://www.powershellgallery.com/packages/install-kubectl/1.7/Content/install-kubectl.ps1

I used powershell gallery's contact the owner to figure out where the source for this lives to get it updated.

**Comment by jsturtevant** [comment]
fixed by: https://github.com/kubernetes/website/pull/27467
/close
