### ISSUE TITLE
Service account permission testing with --as return yes, even wrong sa name provided

### ISSUE THREAD

**Issue by RAJMITTAL** [kubernetes/kubernetes#100994]
####  i have following command to verify the permissions of a service account "sa-name".
 `kubectl auth can-i create deployment  -n myns --as=system:serviceaccount:myns:sa-name`

#### What you expected to happen:
when i put wrong service account name, e.g instead of **sa-name** i put *any-name*. it should return false. but it is always returning true.

#### How to reproduce it (as minimally and precisely as possible):

- create a ns myns
- create a sa **sa-name** in myns
- create a clusterrole with deployment create permission
- create a rolebinding with above clusterrole and sa in namespace myns
` kubectl create rolebinding my-binding --clusterrole=my-role --serviceaccount=myns:sa-name -n myns`
- now  `kubectl auth can-i create deployment  -n myns --as=system:serviceaccount:myns:sa1`

#### Environment:
- Kubernetes version (use `kubectl version`):1.19.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): Linux controlplane 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:03:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by RAJMITTAL** [comment]
i just found following role created in system. as soon as i removed it. it started working as expected

```
Name:         per-binding
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  cluster-admin
Subjects:
  Kind   Name                    Namespace
  ----   ----                    ---------
  User   admin                   
  User   kubelet                 
  Group  system:serviceaccounts  
```

**Comment by liggitt** [comment]
> i just found following role created in system. as soon as i removed it. it started working as expected

that's correct... by granting access to all service accounts, that binding made authorization checks against any service account username return yes

/close
