### ISSUE TITLE
IPVS error log occupation with externalTrafficPolicy: Local option in Service

### ISSUE THREAD

**Issue by ssup2** [kubernetes/kubernetes#100925]
#### What happened: 
IPVS error log occupation with externalTrafficPolicy: Local
~~~
$ dmesg
...
[23709.680898] IPVS: rr: TCP 192.168.0.52:80 - no destination available
[23710.709824] IPVS: rr: TCP 192.168.0.52:80 - no destination available
[23832.428700] IPVS: rr: TCP 127.0.0.1:30209 - no destination available
[23833.461818] IPVS: rr: TCP 127.0.0.1:30209 - no destination available
...
~~~

#### What you expected to happen:
Do not print the error log.

#### How to reproduce it (as minimally and precisely as possible):

~~~
$  kubectl get nodes -o wide
NAME     STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
node01   Ready    control-plane,master   13d   v1.20.5   192.168.0.61   <none>        Ubuntu 18.04.4 LTS   5.4.0-64-generic   docker://19.3.12
node02   Ready    <none>                 13d   v1.20.5   192.168.0.62   <none>        Ubuntu 18.04.4 LTS   5.4.0-64-generic   docker://19.3.12
~~~

~~~
$ kubectl get service
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)        AGE
kubernetes        ClusterIP      10.96.0.1        <none>           443/TCP        13d
nginx-ipv4        LoadBalancer   10.96.82.45      192.168.0.52     80:30209/TCP   54m

$ kubectl get service nginx-ipv4 -o yaml
...
spec:
  clusterIP: 10.96.82.45
  clusterIPs:
  - 10.96.82.45
  externalTrafficPolicy: Local
  healthCheckNodePort: 31583
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30209
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.52
~~~

~~~
$ kubectl get pod -o wide
NAME                                  READY   STATUS    RESTARTS   AGE   IP                NODE     NOMINATED NODE   READINESS GATES
nginx-658f4cf99f-654bc                1/1     Running   0          55m   192.167.140.91    node02   <none>           <none>
nginx-658f4cf99f-jp27p                1/1     Running   0          55m   192.167.140.92    node02   <none>           <none>
nginx-658f4cf99f-ld9th                1/1     Running   0          55m   192.167.140.82    node02   <none>           <none>
~~~

~~~
(node01) $ ipvsadm -L
...
TCP  192.168.0.52:80 rr
TCP  192.168.0.61:30209 rr
...

(node01) $ curl 192.168.0.52:80
(node01) $ curl localhost:30209

[23709.680898] IPVS: rr: TCP 192.168.0.52:80 - no destination available
[23710.709824] IPVS: rr: TCP 192.168.0.52:80 - no destination available
[23832.428700] IPVS: rr: TCP 127.0.0.1:30209 - no destination available
[23833.461818] IPVS: rr: TCP 127.0.0.1:30209 - no destination available
~~~

As you can see, "nginx-ipv4" service endpoint are nginx pods in "node02". Because "nginx-ipv4" service has "externalTrafficPolicy: Local" and node01 doesn't have nginx pod, node01 doesn't have IPVS destination for 192.168.0.52:80 and 192.168.0.61:30209. And this makes IPVS occupy the kernel log.

I know this is intended. But I think  kube-proxy must set the filter ruless to iptables for 192.168.0.52:80 and 192.168.0.61:30209 to prevent IPVS error log occupation. Is there any plan for this issue??

#### Environment:
- Kubernetes version (use `kubectl version`): 
  - v1.20.5
- Cloud provider or hardware configuration: 
  - my local cluster
- OS (e.g: `cat /etc/os-release`): 
~~~
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
~~~
- Kernel (e.g. `uname -a`):
  - Linux node01 5.4.0-64-generic #72~18.04.1-Ubuntu SMP Fri Jan 15 14:06:34 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu
- Install tools:
  - kubeadm
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by uablrek** [comment]
The kernel log printouts should be transient. They should stop when a real server becomes available. If the kernel log printouts keep coming it is a misconfiguration, you have exposed a service without endpoints and clients keep trying to use it.

To insert/remove temporary iptables rules (which is non-trivial) to prevent kernel log printouts that are either transient or caused by misconfiguration is not a prioritized issue.

I let sig/network decide if this is worth doing and wait with triage.

**Comment by ssup2** [comment]
My NLN(Network Load Balancer) doesn't support L7, so my NLB can't use healthCheckNodePort. Therefore, my NLB checks the existence of pods by sending health check packets to NodePort of all LB services. These health check packets are cause of IPVS kernel log. So In my situation, the kernel logs is not transient. Are there any other options I can choose in my situation?

I remember that with kube-proxy iptables mode there are no kernel log issues. So I hope this problem will be solved.

**Comment by uablrek** [comment]
Problem is that these are kernel messages, not K8s. I will check if there is some configuration in ipvs to suspress them or set the syslog level for them.

**Comment by uablrek** [comment]
Semms to be printed with this macro;
https://github.com/torvalds/linux/blob/95c7b07551879c8ad4d6dca10c02de46ddbf55a8/include/net/ip_vs.h#L259-L263

I can't see any way to suspress or change the syslog level. It is rate limited but probably not enough to stop flooding your logs.

**Comment by uablrek** [comment]
Is your use-case limited to `externalTrafficPolicy:Local`?

That is, do your Network Load Balancer send packets to all nodes and only the nodes where pods are allocated are supposed to answer?

Or is it not limited to `externalTrafficPolicy:Local`? That is, you send packets to a service without any endpoints, but endpoints may pop up at some time in the future.

**Comment by ssup2** [comment]
Is your use-case limited to externalTrafficPolicy:Local? -> Yes :)
That is, do your Network Load Balancer send packets to all nodes and only the nodes where pods are allocated are supposed to answer? -> Yes :)

**Comment by rikatz** [comment]
@uablrek this is something 'funny' I've hit while doing the kpng research. We always assign the ServiceIP on machines, even if they don't have Endpoints. This turns out to return to user a connection refused instead of simply drop/try to route which IMO I don't know if was the idea of this design.

Anyway, some check I would do in kpng is: if service have endpoint then configure, otherwise not. I'm bringing this idea here, because I wanna to discuss if this should be changed in kube-proxy, like if the service does not have endpoints should we still keep the Service being configured?

**Comment by rikatz** [comment]
@ssup2 You can disable kernel logging with [kernel.printk](https://www.kernel.org/doc/Documentation/sysctl/kernel.txt).

Don't know if this helps (didn't had time to test) but you might take a look

**Comment by ssup2** [comment]
@rikatz I tested with a load balancer service that doesn't have any endpoint. But it's the same.

~~~
# kubectl get service
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP                          PORT(S)        AGE
kubernetes        ClusterIP      10.96.0.1        <none>                               443/TCP        18d
my-nginx-ipv4     LoadBalancer   10.102.96.66     192.168.0.53                         80:31380/TCP   2m45s

# curl localhost:31380
curl: (7) Failed to connect to localhost port 31380: Connection refused
# dmesg
[110880.619837] IPVS: rr: TCP 127.0.0.1:31380 - no destination available
[110881.649816] IPVS: rr: TCP 127.0.0.1:31380 - no destination available
~~~

~~~
# sysctl -a |grep printk
kernel.printk = 4       4       1       7
kernel.printk_delay = 0
kernel.printk_devkmsg = ratelimit
kernel.printk_ratelimit = 5
kernel.printk_ratelimit_burst = 10
kernel.tracepoint_printk = 0
sysctl: reading key "net.ipv6.conf.all.stable_secret"
sysctl: reading key "net.ipv6.conf.default.stable_secret"
sysctl: reading key "net.ipv6.conf.docker0.stable_secret"
sysctl: reading key "net.ipv6.conf.eth0.stable_secret"
sysctl: reading key "net.ipv6.conf.kube-ipvs0.stable_secret"
sysctl: reading key "net.ipv6.conf.lo.stable_secret"
sysctl: reading key "net.ipv6.conf.tunl0.stable_secret"
~~~

**Comment by uablrek** [comment]
> if the service does not have endpoints should we still keep the Service being configured?

@rikatz This update https://github.com/kubernetes/kubernetes/issues/93456 will require a service configured even if there are no _local_ endpoints.

**Comment by uablrek** [comment]
@ssup2 Can you apply https://github.com/kubernetes/kubernetes/pull/97081 and re-build K8s?

I think this might solve your problem. At least the printouts will stop. But packets (synack) will be returned but with incorrect source (a pod address). I think this will not cause problems for you though.

**Comment by thockin** [comment]
> My NLN(Network Load Balancer) doesn't support L7, so my NLB can't use healthCheckNodePort

This might be worth a bug of its own.  Maybe we need a way to handle that at L4?

Maybe IPVS proxier needs to install iptables rules to REJECT packets in this case?

**Comment by ssup2** [comment]
@uablrek Sorry for the late reply. https://github.com/kubernetes/kubernetes/pull/97081 
If I apply this PR, How are the rules of iptables/IPVS changed? And I think this PR could be applied by only changing kube-proxy. If my opinion is correct, could you offer kube-proxy container image to apply to my cluster?

@thockin I think that the REJECT rule is required. Now I'm developing my project(https://github.com/kakao/network-node-manager) to apply the REJECT rule.

**Comment by uablrek** [comment]
> If I apply this PR, How are the rules of iptables/IPVS changed?

The iptables rules are not changed, but you _do_ have real servers defined on all nodes, not just the ones where server pods are running. That will prevent the loggings.

**Comment by ssup2** [comment]
what're real servers?? And could you provide kube-proxy image?? Thanks :)

**Comment by uablrek** [comment]
"no destination available" means no servers or "real servers".

I will check how to build a kube-proxy image, but I have never done it so it may take some time.

**Comment by uablrek** [comment]
I have built a `kube-proxy` image from the "release-1.20" branch and applied PR #97081 at
```
docker.io/nordixorg/kube-proxy:v1.20-97081
```
I have tested the `kube-proxy` binary but not the full image. I hope it works.

**Comment by uablrek** [comment]
And BTW `loopback:node-port` have never worked with ipvs, will never work, and will be removed; https://github.com/kubernetes/kubernetes/issues/96879

**Comment by ssup2** [comment]
@uablrek I tested and it works well. The logs disappear. Thanks :)

But this method generates unnecessary packet transmission.
I think the ideal way is to use the drop rule in iptables.
Is there a plan to support the drop rule??

**Comment by uablrek** [comment]
Great! Thanks for testing :+1:  (and verify that I got the build right :smile: )

To add/remove iptables rules should _not_ be taken lightly. There is plenty of room for mistakes in cases that are hard to test like interferrence with other actors that uses iptables like CNI-plugins, rapid updates, and restarts (upgrade).

I have not got https://github.com/kubernetes/kubernetes/pull/97081 accepted yet, but if that PR is accepted I will close this issue also. I feel pretty confident that #97081 will not introduce any bugs.

I think the extra packets can be ignored (unless you probe like crazy).

**Comment by ssup2** [comment]
@uablrek Thanks :)

**Comment by uablrek** [comment]
/remove-lifecycle stale

Waiting on comments on PR https://github.com/kubernetes/kubernetes/pull/97081
