### ISSUE TITLE
winkernel kube-proxy problems when IPv6DualStack is enabled (ie, in 1.21)

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#100966]
#### What happened:
Ran winkernel kube-proxy in 1.21 (where `IPv6DualStack` is now enabled by default). It fails:

`F0408 17:17:11.043472    1316 server.go:489] unable to create proxier: unable to create ipv4 proxier: Could not find host mac address for 0.0.0.0, hostname: e2e-wmcow-bpfpl, clusterCIDR : 10.132.0.0/24, nodeIP:0.0.0.0`

Manually specifying `--bind-address` gets it past that problem but then fails with:

`F0408 21:22:41.744719    1804 server.go:489] unable to create proxier: unable to create ipv6 proxier: Could not find host mac address for ::, hostname: winworker-pbvb6, clusterCIDR : 10.132.0.0/24, nodeIP:::`

(Note that this is a single-stack IPv4 cluster.)

#### What you expected to happen:
Enabling the feature gate should not change the end-user-visible behavior for people who are not using the gated feature.

There are (at least) two problems:

1. When `IPv6DualStack` is disabled, the startup code calls `utilnode.GetNodeIP(client, hostname)` to get the node IP and passes that to `winkernel.NewProxier`, but when `IPv6DualStack` is enabled, it passes `nodeIPTuple(config.BindAddress)` instead, which will always pass at least one unspecified (`0.0.0.0`/`::`) IP to `NewDualStackProxier`. But the winkernel proxier code doesn't deal with unspecified IPs, at least when using an "overlay" network; it requires that the passed-in IP be an actual IP address on some interface. (It's possible that it should be using something like `utilnet.ResolveBindAddress()` from apimachinery to convert the possibly-unspecified bind address to a local IP.)
2. The winkernel kube-proxy startup code always creates a metaproxier with IPv4 and IPv6 sub-proxiers if `IPv6DualStack` is enabled, but then fails if it can't create either of those proxiers. This is wrong; it should fall back to single-stack operation if it can't run dual-stack, because the presence of the feature gate doesn't mean that the cluster is _actually_ dual-stack, it just means that it _is allowed to be_ dual-stack.

#### How to reproduce it (as minimally and precisely as possible):
Run kube-proxy 1.21 in winkernel mode with an overlay network on a single-stack IPv4 node

**Comment by jsturtevant** [comment]
What version of Windows server are you running?  Must be 2004+ https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack

/cc @aramase

**Comment by aravindhp** [comment]
We are seeing this issue with 1809, 1909 and 20H2. Not sure if https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#ipv4-ipv6-dual-stack matters here. This is a single stack cluster and kube-proxy is assuming it is actually dual stack just because the IPv6 dual stack feature is now enabled by default in 1.21. Cluster network setup is [hybrid networking with OVN-Kubernetes](https://docs.openshift.com/container-platform/4.7/networking/ovn_kubernetes_network_provider/configuring-hybrid-networking.html#configuring-hybrid-ovnkubernetes_configuring-hybrid-networking).

**Comment by jsturtevant** [comment]
It looks like this is specific to the overlay setting,  It seems reasonable to me that it should fallback to single stack.  @aramase is that the expected behavior?

As discussed in slack the work around is to add `--feature-gates=IPv6DualStack=false`

**Comment by aramase** [comment]
> It looks like this is specific to the overlay setting, It seems reasonable to me that it should fallback to single stack. @aramase is that the expected behavior?

@jsturtevant Falling back to using single stack if creating dual-stack proxier might ignore actual errors when the cluster is dual-stack. Instead could we check if the hosts are dual-stack/cluster CIDR are dual-stack? If there is only 1 cluster CIDR then we can just rely on that in addition to the feature gate.

**Comment by jsturtevant** [comment]
>Instead could we check if the hosts are dual-stack/cluster CIDR are dual-stack?  

Is that how it is handled on the linux side?

There seems to be an additional check needed as well, If overlay is enabled then it should fall back to single stack.  From the docs: ` Note: Overlay (VXLAN) networks on Windows do not support dual-stack networking today.`

**Comment by aojea** [comment]
> Is that how it is handled on the linux side?


kube-proxy in linux tries to create a dual-stack proxy, but if the host doesn't have ipv6 iptables, it fallsback to single-stack.
If is dual-stack and it only has configured one of the ipfamilies, the proxy of the other family is not going to get any service or endpoint

**Comment by neolit123** [comment]
these seem like problems that we should fix in a 1.21 PATCH release and 1.22 at master, correct?

our kubeadm e2e test job run only against the "stable-1" label, so they caught the problem only after 1.21.0 was out.
ideally we should have these tests for the k8s master branch too.

**Comment by jsturtevant** [comment]
this doesn't look like it requires any changes to the OS layer so I will give it a go
/assign

**Comment by neolit123** [comment]
>  jsturtevant moved this from InProgress (v1.22) to In Review (v1.22) in SIG-Windows on May 6

given this is in the in-review board:

/remove-lifecycle stale
