### ISSUE TITLE
kubectl logs failed with "net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by zhucan** [kubernetes/kubernetes#100904]
#### What happened:
kubectl logs failed with "net/http: TLS handshake timeout"

#### What you expected to happen:
kubectl logs successfully

#### Environment:
- Kubernetes version (use `kubectl version`): 
![image](https://user-images.githubusercontent.com/13997135/113965633-5a0cc200-9860-11eb-84c5-e2c7ac7b5c72.png)

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
CentOS Linux release 7.8.2003 (Core)

- Kernel (e.g. `uname -a`):
3.10.0-1127.19.1.el7.x86_64
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
quay.io/coreos/flannel:v0.13.1-rc2  
- Others:

**Comment by neolit123** [comment]
please try the support channels for this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
