### ISSUE TITLE
cAdvisor to extract the container metrics directly in a file format rather than than local host/UI display

### ISSUE THREAD

**Issue by Guru-arnav** [kubernetes/kubernetes#100987]
could you please let me know how to extract the cadvisor monitored metrics into a file. I need to perform analysis on the metrics

**Comment by pacoxu** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/). 

Feel free to reopen if this is a feature request or have some ideas/ write proposal/KEPs for it.

@Guru-arnav  Does the link [Metrics For Kubernetes System Components](https://kubernetes.io/docs/concepts/cluster-administration/system-metrics/) solve your problem? 

/sig instrumentation 
/triage accepted
/close
