### ISSUE TITLE
v1.21.0 changelog says "Default Container Labels" instead of "Default Container Annotations" 

### ISSUE THREAD

**Issue by invidian** [kubernetes/kubernetes#100961]
#### What happened:

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#default-container-labels is wrong as it says default label can be specified, but KEP and other lines of changelog mentions annotation.

#### What you expected to happen:

Changelog is correct and consistent about  default container feature for kubectl.

#### Anything else we need to know?:

I'm still not able to get this feature to work actually for `kubectl logs`.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.0

**Comment by wilsonehusin** [comment]
/triage accepted

thanks for reporting early!
