### ISSUE TITLE
Can kubelet provide http-proxy to dockerd ?

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#101041]
#### What happened:
In my scenario, the kubernetes master node also acts as http-proxy (_by running Squid_). Whenever a node connects/configured with master VIP/URL, the dockerd daemon of that node had to be configured with this IP as [dockerd's http-proxy](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy). But configuring as per this [link](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy) requires restart of dockerd, which is expensive in my case, as there are already many containers running off of local images, which would restart if dockerd restarts.

I am not sure how this ***magic*** happens, but the imagePullSecret is configured in kubernetes/etcd and **kubelet should be the one providing the same to dockerd** .

**Question:** Could **kubelet also provide http-proxy to dockerd**, w/o requiring a service-restart of docker?

#### What you expected to happen:
Configure http-proxy for image-pull by node in kubernetes and dockerd in the node gets it upon "node join" transparently w/o requiring "service restart docker"

#### How to reproduce it (as minimally and precisely as possible):
Have a registry behind http-proxy
Make your master act as http-proxy (_you may install squid_)
Deploy a pod to this node and note that image pull fails.
Now configure the master IP as http-proxy for dockerd as explained [here](https://docs.docker.com/config/daemon/systemd/#httphttps-proxy)
Note: image pull succeeds

#### Environment:
- Kubernetes version (use `kubectl version`): "v1.18.6"
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
admin@CO4AEAP000105BD:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

```
- Kernel (e.g. `uname -a`): `Linux CO4AEAP000105BD 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adlerliu** [comment]
1
