### ISSUE TITLE
Any way to run different command in different securityContext? 

### ISSUE THREAD

**Issue by V0idk** [kubernetes/kubernetes#101052]
#### What would you like to be added:

I have a deployment, steps like: 
1.  run install.sh with root, will create some user  test1
2.  and then run start.sh with test1

But containers only supports single securityContext.

if i use initContainer,  any change of install.sh(such as create user) would not save after initContainer finish.

#### Why is this needed:

run different command in different securityContext

**Comment by liggitt** [comment]
/remove-sig auth
/close

you can either separate the distinct security settings into separate containers/invocations and run them serially in initContainers, or run a single container with sufficient privileges/capabilities to make calls like setuid to run subcommands as different users
