### ISSUE TITLE
Creating a CRD with broken converter webhook prevents GC controller from initialization

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#101078]
#### What happened:

Creating a CRD with broken converter webhook prevents GC controller from initialization, which breaks on informer sync. Additionally, this issue is not visible until gc controller restarts - dynamically added crd resources with non-working converter webhook do not break running GC.

#### What you expected to happen:

GC controller should initialize with available informers. CRDs with broken converter webhook should not prevent GC controller from working on other resources.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a cluster
1. Create a CRD (1_crd.yaml)
1. Create a CR (2_crd.yaml)
1. Change CRD to add another version and webhook converter (3_crd.yaml)
1. Restart kube-controll-manager
1. Add deployment
1. Delete deployment
1. Check that pod from deployment is not GC'ed

[gc-bug.zip](https://github.com/kubernetes/kubernetes/files/6305426/gc-bug.zip)

**Comment by neolit123** [comment]
please follow the issue template correctly:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

including k8s version is important.

**Comment by jprzychodzen** [comment]
Sure, it happens on current K8s master branch - exact commit is `b0abe89ae259d5e891887414cb0e5f81c969c697`

* Kubernetes version (use kubectl version):
  ```
  kubectl version
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", 
  GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-alpha.0.30+b0abe89ae259d5-dirty", GitCommit:"b0abe89ae259d5e891887414cb0e5f81c969c697", GitTreeState:"dirty", 
  BuildDate:"2021-04-13T16:11:56Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
  ```
* Cloud provider or hardware configuration:
  K8s cluster running on GCE started with kubetest. 10 nodes with `--gcp-node-size=n1-standard-1` and with [preset-e2e-scalability-common](https://github.com/kubernetes/test- infra/blob/master/config/jobs/kubernetes/sig-scalability/sig-scalability-presets.yaml#L119) env variables
* OS (e.g: cat /etc/os-release):
  ```
  cat /etc/os-release
  NAME="Container-Optimized OS"
  ID=cos
  PRETTY_NAME="Container-Optimized OS from Google"
  HOME_URL="https://cloud.google.com/container-optimized-os/docs"
  BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
  GOOGLE_METRICS_PRODUCT_ID=26
  GOOGLE_CRASH_ID=Lakitu
  KERNEL_COMMIT_ID=9ca830b4d7ae9ff76f64f4f9f78a0a0b88dfcda4
  VERSION=85
  VERSION_ID=85
  BUILD_ID=13310.1041.9
  ```
* Kernel (e.g. uname -a):
  ```
  Linux e2e-test-jprzychodzen-master 5.4.49+ #1 SMP Wed Sep 23 19:45:38 PDT 2020 x86_64 Intel(R) Xeon(R) CPU @ 2.00GHz GenuineIntel GNU/Linux
  ```
* Install tools:

**Comment by yliaog** [comment]
i think this is the same issue as reported in https://github.com/kubernetes/kubernetes/issues/90597

**Comment by jprzychodzen** [comment]
It might share root cause - informer sync in case of GC should non-block on CRDs (and possibly on other resources?)

I guess we would need some metrics about unsynced informers to handle this properly.

**Comment by aojea** [comment]
This seems to be this way by design, see this duplicate https://github.com/kubernetes/kubernetes/issues/96066#issuecomment-721836316

**Comment by willdeuschle** [comment]
This is problematic for our environments as well. Unstable user-defined conversion webhooks break GC for unrelated resources, those unrelated resources eventually hit quota limits and render the environment unusable.

Is there a recommended approach to this from the community? One naive solution that comes to mind is a config option for marking a CRD as non-blocking for GC. Then GC would only respect `blockOwnerDeletion` in a best effort fashion, for example. Admission webhooks could then block CRD creation that specified a conversion webhook _without_ making the resource non-blocking.

Without this, it's hard to allow users to specify conversion webhooks because k8s then takes a dependency on those services (which in our case, already take a dependency on k8s).

**Comment by liggitt** [comment]
I think I'd push to make gc stop blocking on discovery or informer sync at all, and make blockOwnerDeletion even more best effort.

**Comment by deads2k** [comment]
> I think I'd push to make gc stop blocking on discovery or informer sync at all, and make blockOwnerDeletion even more best effort.

I'd like to stop honoring blockOwnerDeletion. :)

**Comment by tkashem** [comment]
cc @tkashem

**Comment by haorenfsa** [comment]
Is there any ongoing work for this?

**Comment by liggitt** [comment]
> Is there any ongoing work for this?

None that I know of. At first glance, removing the requirement that all informers be fully synced before GC starts/resumes seems reasonable to me, and would resolve this issue.

**Comment by haorenfsa** [comment]
OK, I'll try to work out a patch

**Comment by rauferna** [comment]
Hi @tossmilestone,

What is the status of this? One year has passed. Is there any short term plan to fix this?

Thanks!

**Comment by haorenfsa** [comment]
@rauferna not likely in a short term. A quick solution is that you delete the converter webhook when you find your CRD controller is not working. and add it back when it recovers. Or you deploy multiple replicas to avoid the downtime as possible.
