### ISSUE TITLE
kubelet in v1.21.0 cann't run in alpine system, tips: sh: kubelet: not found, maybe it's a build bug

### ISSUE THREAD

**Issue by tristan-tsl** [kubernetes/kubernetes#101069]
#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.0
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): alpine:3.13
- Kernel (e.g. `uname -a`): Linux localhost.localdomain 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tristan-tsl** [comment]
run `mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2` to fix it temp

**Comment by neolit123** [comment]
> run mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2 to fix it temp

this is not a core k8s problem.
please try the support forums or discuss it with the Alpine maintainers.

for a k8s discussion use:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
