### ISSUE TITLE
cluster.local domain could not be resolved in POD.

### ISSUE THREAD

**Issue by jc-lab** [kubernetes/kubernetes#101017]
### What happened:
Cannot query the cluster.local domain (e.g. kubernetes.default.svc.cluster.local) from within the POD.
But querying with kubernetes.default works.

### What you expected to happen:
Should be able to resolve by querying the cluster.local domain.

### How to reproduce it (as minimally and precisely as possible):
I just init the k8s cluster.

#### Core DNS Log:

```
"A IN kubernetes.default.svc.cluster.local.default.svc.cluster.local. udp 83 false 512" NXDOMAIN qr,aa,rd 173
"A IN kubernetes.default.svc.cluster.local.svc.cluster.local. udp 72 false 512"NXDOMAIN qr,aa,rd 165
"A IN kubernetes.default.svc.cluster.local.cluster.local. udp 54 false 512" REFUSED qr,rd,ra 68
"A IN kubernetes.default.svc.cluster.local.cluster.local. udp 54 false 512" REFUSED qr,rd,ra 68
```

The .local domain is not queried as it is, and the fields in search in resolv.conf are appended.

Pod Yaml contains:
```
dnsPolicy: ClusterFirst
```

### Environment:
- Kubernetes version (use `kubectl version`): v1.20.5
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): "20.04 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): 5.4.0-64-generic
- Install tools: apt-get
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
It is related with “search” and “ndots” in /etc/resolv.conf

The default ndots is 5. If you set it to 2， no more domain search would be triggered for xxx.xxx.svc.cluster.local

/area dns
/sig network

**Comment by jc-lab** [comment]
@pacoxu Thanks for reply.
I saw a related issue somewhere.
However, already it defaults to 5, and it is the same if I change it to 7 or another number.

**Comment by pacoxu** [comment]
If 'ndots' is larger, it will trigger search domains. Use smaller number to prevent those searches.

**Comment by jc-lab** [comment]
Let's test it tomorrow.
But how can I change the default value of Pod's resolve.conf?

**Comment by BenTheElder** [comment]
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-dns-config

**Comment by jc-lab** [comment]
This method is difficult to apply to all Pods, including third parties.
The cluster.local domain is basically supported by k8s, but it is strange that it does not work.
Is there a better solution or a way to change it globally?

**Comment by pacoxu** [comment]
Another option would be using `coredns autopath`: https://coredns.io/plugins/autopath/.

Suggestions from https://github.com/kubernetes/kubernetes/issues/59031#issuecomment-400724357

**Comment by uablrek** [comment]
I can't reproduce this problem. Be aware that some programs does not use the resolver lib. For instance `go` programs make dns queries in their own way (normally) to prevent that a kernel thread gets blocked. So please check how your program does dns queries and try some others like `ping`. Lookup programs like `nslookup` and `dig` probably also bypass the resolver (at least is looks that way).

**Comment by jc-lab** [comment]
@uablrek 
Interestingly, in an Internet-enabled environment, it works as well as I want.
However, this situation occurs in an environment where the Internet is not available (connected only to OpenWRT's dnsmasq server and not connected to external DNS).

**Comment by thockin** [comment]
It depends on the DNS resolver in the client.  What conatiner image are you using to do these queries?  I can't repro it with `ubuntu`, for example.
