### ISSUE TITLE
Add a Kubelet configuration option to disable certain cAdvisor metrics

### ISSUE THREAD

**Issue by ncapps** [kubernetes/kubernetes#101079]
#### What happened:
We have both Kubernetes and Docker running in the same environment. cAdvisor is running as part of the kubelet binary. Kubernetes is using CRI-O as our CRI. Both `/var/lib/docker` and `/var/lib/containers` are backed by a ZFS file system.

cAdvisor is gathering metrics for the Docker CRI and executes `zfs list` on an interval. This operation is resource intensive. We do not need cAdvisor to gather metrics for the Docker CRI.

I would like to be able to expose the `--disable_metrics` cAdvisor flag as a flag to kubelet so that I can stop gathering filesystem metrics for the Docker CRI.

#### What you expected to happen:
Docker CRI metrics are not gathered by cAdvisor/kubelet

#### How to reproduce it (as minimally and precisely as possible):
See "What Happened" description above.

#### Environment:
- Kubernetes version: 1.20.0+k3s2
- Cloud provider or hardware configuration: bare metal
- OS: CentOS 7

**Comment by Nick-Triller** [comment]
Hi, I would like to start contributing to Kubernetes. Can I take a stab at this issue if you decide it's something that should be implemented?

**Comment by n4j** [comment]
@Nick-Triller if you are still interested in working on this issue you can assign it to yourself

**Comment by adisky** [comment]
> cAdvisor is gathering metrics for the Docker CRI and executes zfs list on an interval. This operation is resource intensive. We do not need cAdvisor to gather metrics for the Docker CRI.

You want to say that, if you are using container runtime other than docker, still it collects metrics from docker?
can you attach Kubelet logs?

> I would like to be able to expose the --disable_metrics cAdvisor flag as a flag to Kubelet so that I can stop gathering filesystem metrics for the Docker CRI.

I think we should detect without using a flag what container runtime is used and fetch metrics accordingly.

/triage needs-information

**Comment by wb14123** [comment]
Hi @adisky , I'm having the same problem. In my case, and I think that's also what @ncapps meant is, I'm actually using docker as container run time. But since `/var/lib/docker` is backed with ZFS, list the disk usage is very expensive: the `zfs list` drives CPU usage to 100%. Is there anyway to configure the frequent of the behavior?

**Comment by wb14123** [comment]
Actually I'm not sure if `--disabled-metrics` in kube-apiserver can do the work or not, since the `zfs list` command is invoked by kubelet. If it doesn't work, it would make since to also add the `--disabled-metrics` flag to kubelet since this flag is also in many other Kubenetes components.

**Comment by endocrimes** [comment]
/retitle Add a Kubelet configuration option to disable certain cAdvisor metrics
