### ISSUE TITLE
Create a duration metric for probes

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#101035]
/kind feature
/sig node

As exec probe timeout [bug was fixed](https://github.com/kubernetes/enhancements/issues/1972), upgrade of k8s may lead to unexpected workload disruptions if the exec probe timeout is not corrected properly. Unfortunately there is no easy way today to guess which timeout should be set for the probe. The suggestion is to introduce a duration metric to allow customers to measure this time.

Likely here where other metrics are defined: /pkg/kubelet/prober/prober_manager.go

KEP: https://github.com/kubernetes/enhancements/issues/1972

/assign @jackfrancis
/cc @matthyx

**Comment by jackfrancis** [comment]
See here for a prototype reference of a metric:

- https://github.com/kubernetes/kubernetes/pull/95429/files#diff-c3e7f724d1b0dcee40df80716ed57d90d2649710150fa92bf9822bdad35e0429

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

as @jackfrancis is working on it

**Comment by jackfrancis** [comment]
/remove-lifecycle stale

https://github.com/kubernetes/kubernetes/pull/104484 is still in-progress
