### ISSUE TITLE
container runtime status check may not have completed yet, PLEG is not healthy

### ISSUE THREAD

**Issue by pixiake** [kubernetes/kubernetes#101056]
#### What happened:
When I upgraded kubelet from v1.18.8 to v1.19.0 (v1.19.9 is the same) ,  the node is notready, and kubelet reported the following error
```
Apr 13 13:22:22 i-ie33j8hy kubelet[19792]: E0413 13:22:22.676030   19792 kubelet.go:1765] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg was last seen active 16m6.559177445s ago; threshold is 3m0s]
```
I've tried restarting the node and it doesn't solve the problem.

I checked docker, and both `docker ps` and `docker inspect` are working fine.

#### Anything else we need to know?:
The kubelet configuration:
```
$ cat /var/lib/kubelet/config.yaml
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
clusterDNS:
- 169.254.25.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionHard:
  memory.available: 5%
evictionMaxPodGracePeriod: 120
evictionPressureTransitionPeriod: 30s
evictionSoft:
  memory.available: 10%
evictionSoftGracePeriod:
  memory.available: 2m
featureGates:
  CSINodeInfo: true
  ExpandCSIVolumes: true
  RotateKubeletClientCertificate: true
  RotateKubeletServerCertificate: true
  VolumeSnapshotDataSource: true
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
kubeReserved:
  cpu: 200m
  memory: 250Mi
maxPods: 110
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
rotateCertificates: true
runtimeRequestTimeout: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
systemReserved:
  cpu: 200m
  memory: 250Mi
volumeStatsAggPeriod: 0s
```
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
- Docker version
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:33:55 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:25:42 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
- OS (e.g: `cat /etc/os-release`):

```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```
Linux i-ie33j8hy 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
kubeadm
```

**Comment by pixiake** [comment]
Is there any way to check which container is blocking the kubelet?

**Comment by rdxmb** [comment]
same problem here: 

`drei   NotReady                   <none>                 197d   v1.20.5   10.139.0.93   <none>        Ubuntu 20.04.2 LTS   5.4.0-70-generic   docker://19.3.14`

```
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:09:38Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by sgblv** [comment]
I've faced with exactly same issue. 
Upgraded from 1.18 to 1.19 , similar configs ,same errors.

**Comment by rdxmb** [comment]
Could this be handled with a higher priority, please? When existing nodes suddenly stop and are not Ready anymore, people have some problems to deal with existing workload.

**Comment by rdxmb** [comment]
Is this caused by https://github.com/moby/moby/issues/40817 ?

**Comment by rdxmb** [comment]
I've changed my `drei`s container runtime to containerd 1.4.4 with cgroup-driver `systemd`. Actually, I could drain another node and run about 124 pods on `drei` - without flapping the node status.

I wonder if this issue has something to do with running cgroup-driver `cgroupfs` and docker on a systemd-managed OS (Ubuntu) - when there is high workload.

My actual cluster looks like that:

```
drei   Ready,SchedulingDisabled   <none>                 19h    v1.20.6   10.139.0.93   <none>        Ubuntu 20.04.2 LTS   5.4.0-70-generic   containerd://1.4.4
eins   Ready                      control-plane,master   545d   v1.20.4   10.139.0.91   <none>        Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://19.3.14
vier   Ready                      <none>                 20d    v1.20.5   10.139.0.94   <none>        Ubuntu 20.04.2 LTS   5.4.0-67-generic   containerd://1.4.4
zwei   Ready                      <none>                 98d    v1.19.7   10.139.0.92   <none>        Ubuntu 20.04.1 LTS   5.4.0-62-generic   docker://19.3.14
```
As I am migrating to containerd and cgroup-driver systemd, my cgroup-drivers actually look like this:

| node | cgroup-driver |
|--------|--------------------|
| eins  | systemd         |
| zwei  | systemd |
| drei   | cgroupfs |
| vier   | systemd |

If I can help to debug this, please tell me the steps to do that.

**Comment by qeternity** [comment]
@rdxmb are you say that upgrading containerd from 1.3.x to 1.4.x resolves this?

**Comment by rdxmb** [comment]
@qeternity I am not sure. The problem is that this is one of my production cluster and I cannot try to reproduce/verify this at any time.

That's why I ask for steps to debug, so I can do that in a goal-oriented way instead of just trying different things ...

**Comment by Belly-Buster** [comment]
Downgrading containerd from 1.4.4 to 1.4.3-1 resolved this issue for me.

**Comment by Velociraptor85** [comment]
Update to 1.4.6 fix the issue for me too

**Comment by matthyx** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close

**Comment by kvaps** [comment]
I also faced this issue with docker 20.10.5 and containerd 1.4.4
Installing docker 20.10.7, and containerd 1.4.6 solves this issue.

We've also upgraded without downtime for a running containers by enabling live-restore option in `/etc/docker/daemon.json`:
```yaml
  "live-restore": true
```

**Comment by mingregister** [comment]
I also face the same problem:

`[2021-07-11 19:39:07] [company-server-121] [kubelet:] [E0711 19:39:07.668471   28566 fsHandler.go:118] failed to collect filesystem stats - rootDiskErr: could not stat "/home/docker/overlay2/f87f0f28e6ac885c1bddb11dcb53b324320c4735beb39ebeb7924639b6e82664/diff" to get inode usage: stat /home/docker/overlay2/f87f0f28e6ac885c1bddb11dcb53b324320c4735beb39ebeb7924639b6e82664/diff: no such file or directory, extraDiskErr: could not stat"/home/docker/containers/c1a66eb7987e22119550c386b9ba28d877d83d9d9b61d04687b6c6c97cf213b4" to get inode usage: stat /home/docker/containers/c1a66eb7987e22119550c386b9ba28d877d83d9d9b61d 04687b6c6c97cf213b4: no such file or directory]
[2021-07-11 19:39:41] [company-server-121] [kubelet:] [E0711 19:39:41.048159   28566 kubelet.go:1848] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 16m1.563334863s ago; threshold is 3m0s]

`

kubectl version 
`
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
`

uname -a
`
Linux company-server-122 4.14.15-1.el7.elrepo.x86_64 #1 SMP Tue Jan 23 20:28:26 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
`

docker version 
`
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

`
