### ISSUE TITLE
Log out warnings if user specify unused weight to scheduler framework plugins

### ISSUE THREAD

**Issue by Jerry-Ge** [kubernetes/kubernetes#101087]
#### What would you like to be added:
Log out some warnings if a user accidentally specifies a weight parameter to a framework plugin that doesn't use weight at all. 

#### Why is this needed:
The current Plugin struct looks like this:
```
type Plugin struct {
	// Name defines the name of plugin
	Name string
	// Weight defines the weight of plugin, only used for Score plugins.
	Weight int32
}
```
However, not all framework plugins will need this `Weight` variable. (Only the plugins during the Score extension point will actually need it) 
In case a user accidentally specifies a `Weight` to a non-score plugin, I don't think we should prevent the user from doing this way but it's very necessary to log out some kind of warnings to let the user know this weight will not be used.

**Comment by chendave** [comment]
+1,  weight on the non-score plugin should not effective, but it's not always ignored and might lead  to potential negative impact to the weight of score plugin, e.g.  the issue mentioned here: https://github.com/kubernetes/kubernetes/issues/100613.

**Comment by Jerry-Ge** [comment]
@Huang-Wei @ahg-g @alculquicondor What do you guys think? Any comments? 😬

**Comment by alculquicondor** [comment]
I prefer we just fix #100613.

**Comment by Huang-Wei** [comment]
I'm fine with warning the non-Score plugins specifying a weight. Also, which is a must-have, is to fix the issue reported in #100613 which incorrectly overwrites the Score plugin's weight.

**Comment by Jerry-Ge** [comment]
Cool! That's reasonable and will put the investigation on #100613 on the top priority.

**Comment by chendave** [comment]
I think you can just close this one?
