### ISSUE TITLE
How to achieve failover within 3 seconds when accessing via service name (kube-proxy) When the node fails

### ISSUE THREAD

**Issue by guanxingfeng** [kubernetes/kubernetes#101101]
I  encountered the problem of service access high availability when the node fails. The customer requires service failover within 3s after the node fails. I think it is not a good practice to adjust the --node-monitor-grace-period and -–node-status-update-frequency parameters because it will bring more risks and cannot reach 3s. See related issue：
https://github.com/kubernetes/kubernetes/issues/7433
https://github.com/kubernetes-sigs/kubespray/blob/master/docs/kubernetes-reliability.md
Is there a better way to impove High-Availability? My current thoughts are:
1. Does kube-proxy have an active or passive health check for endpoints With ipvs or iptables? It can check and remove unavailable endpoints within 3 seconds.
2. Can it be solved with the help of a service mesh such as istio？

**Comment by guanxingfeng** [comment]
This is a discussion topic, not a bug

**Comment by neolit123** [comment]
please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
