### ISSUE TITLE
Clarify our support/compatibility with other configuration management software

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#10116]
Today we say [Salt](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/salt.md) can be used but its not clear if only Salt is supported or if Kubernetes can be configured with other software?

Are there any factors to consider (that users should be aware of) when choosing the config. software other than Salt?

**Comment by roberthbailey** [comment]
Kubernetes can be configured with other software (see the matrix [here](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides)). As discussed during the community meeting today, being a supported platform doesn't depend on using salt. It depends on ensuring that you can create a cluster and run the e2e test suite against the cluster (and make sure it keeps working over time). In particular, CoreOS doesn't use salt, but there's no reason that CoreOS can't be a supported platform. 

In general, users shouldn't need to consider what configuration software a provider is using (this should be an implementation detail of the provider). They should mainly be interested in picking where they want to run (GCP, AWS, bare metal, local), and then they should primarily be interacting with the kubernetes API to run containers on their platform of choice. 

For advanced users, there may be some interest in tweaking their deployment (e.g. enabling privileged containers) which will depend on how the underlying platform is configured.

**Comment by RichieEscarez** [comment]
Thanks @roberthbailey,

I think this is the type of info that we should make clear to our "users".

Question: 
Do we want to ask "users" to run e2e tests too (thats for contributors only right)? 

So for example, do you think we should make these types of statements (to clarify this area of the product)?
 - "View the list of getting started guides and the corresponding configuration software that has been tested."
 - "[More information about Salt is available here.](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/salt.md)"
 - "If you are interested in contributing to Kubernetes and want to test other configuration software, see the Kubernetes "contributor" documentation for information about [end-2-end tests](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#end-to-end-tests)."

**Comment by roberthbailey** [comment]
Users shouldn't need to run e2e tests. They will be using the same functions as the e2e tests exercise (hence the need for the tests to verify that things continue to work) but the tests themselves are only for contributors. 

That salt page is quite out of date (it's been a long time since we stopped connecting the nodes to the master in a salt minion/master relationship). 

I think we should just have a link to the github repo for folks that are interested in contributing. Github should be organized well enough that it is clear that you will be required to have passing e2e tests on pull requests.

**Comment by RichieEscarez** [comment]
Do you agree that in order to cover this area, we need to update/provide the following (and that we should use this Issue to deliver these changes)?

 - Update the [Saltstack topic](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/salt.md) so that its accurate -> *"we stopped connecting the nodes to the master in a salt minion/master relationship"*
 - Revise the Saltstack topic so that to speaks to only what user's should know:
     1. Clarify that its not necessary, but advanced users who are interested can use our Saltstack documentation to modify the default configuration.  
Question: Do we need to mention how to recover the default configuration if their attempt at modifications fail?
     2. Mention that the use of other configuration software is possible and that users are not limited to whats listed in the getting started guides. Also point them to our list:  
*"View the list of [getting started guides](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides) and the corresponding configuration software that has been tested."*
     3. Include a statement similar to the following in case users are interested in becoming "contributors" and want to list and maintain their tested environments:  
*"If you are interested in contributing to Kubernetes and want to test other configuration software, see the [Kubernetes "contributor" documentation](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/devel/development.md#end-to-end-tests) for more information."*

**Comment by roberthbailey** [comment]
@zmerlynn offered to make the required changes to salt.md. Feel free to assign back to me (or create separate issues) if we need to cover anything other than salt here.

**Comment by justinsb** [comment]
I propose closing; I feel like the tasks described here are no longer particularly relevant to where we are now as a project?

**Comment by roberthbailey** [comment]
I agree with @justinsb's conclusion from last November, and as there haven't been any dissenting options I'm going to close as obsolete.
