### ISSUE TITLE
Deleting a pod does not trigger the container preStop hooks

### ISSUE THREAD

**Issue by Tolsto** [kubernetes/kubernetes#101146]
#### What happened:

Deleting a pod via `kubectl delete pod [pod_name]` does not trigger the container preStop hooks.

#### What you expected to happen:

Execute preStop hooks when deleting a pod via kubectl.

#### How to reproduce it (as minimally and precisely as possible):

Delete a pod  via `kubectl delete pod [pod_name]`

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.6-eks-49a6c0
- Cloud provider or hardware configuration: AWS EKS

**Comment by CaoDonghui123** [comment]
it is right in v1.21.0
