### ISSUE TITLE
Unexpected Pods (system-node-critical) Evicted During Ephemeral-Storage Pressure

### ISSUE THREAD

**Issue by erismaster** [kubernetes/kubernetes#101167]
#### Anything else we need to know?:
```
W0411 04:19:22.000250   22453 eviction_manager.go:335] eviction manager: attempting to reclaim ephemeral-storage
W0411 05:09:22.078141   22453 eviction_manager.go:422] eviction manager: unexpected error when attempting to reduce ephemeral-storage pressure: wanted to free 9223372036854775807 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "protokube:1.16.4" (must force) - container 68ebe099df35 is using its referenced image 46ca4d15fc48
I0411 05:09:22.097740   22453 eviction_manager.go:364] eviction manager: pods ranked for eviction: k8s-jumpbox-586f64b4c7-6dr47-prd-internal(9ea687f2-74a9-459e-83b4-2c21e64a45f7), calico-node-zsb6k_kube-system(a13f46f6-9b7d-4c1e-87a6-783e69986a2c), kube-proxy-ip-10-1-1-72.us-west-2.compute.internal_kube-system(547051e7ebf9c0803a04e7ef36f64b53), rabbitmq-8c9868c89-ddcg7-prd-internal(27fbbcb6-54b5-4f93-9355-0942f3621081), incident-manager-6f4b48dc66-w2bvw-prd-internal(1ffe9b46-3860-4902-80c9-c07e6784fdd0), inventory-7d9cc6cd74-4zbjv-prd-interface(8af7d4e4-435d-441f-8bd4-842f5865885d), sre-ssh-794cb4dc8c-6jtmp-prd-internal(83596430-b96e-4937-9990-7b86a9497415), fractal-ui-6788765ff4-csws5-prd-public(b2440d7c-17a4-4d87-a9d9-bcbf7ba6b58e), fm-mon-ui-755bff6fd9-svfrn-prd-internal(09f9db9f-3867-4a48-841e-5b9a8d8a24a4), -st2actionrunner-5ffb8bc4f4-7xp7m-prd-internal(7f41bf93-4a70-470e-9e02-e04b530e12bb), network-orchestrator-7c8d94d96b-jdfql-prd-orchestration(2bf16f2d-66aa-484b-949a-88ea07c608f2), workload-platform-controller-7bc74748f6-5bll6-prd-orchestration(d0ae5057-6d2b-4327-b82b-2623f5514128), controller-service-56f8744b6f-khvr8-prd-orchestration(d1ae9fff-4318-45e0-aa52-314d6ba9b528), certificate-worker-c454b5757-vpllk-prd-worker(c88e779b-41d4-4abc-8a01-cdce0c64acd7), config-provider-868949d56c-2tp99-prd-interface(6ca3447a-4c85-4663-b173-94241f23b414), zookeeper-0-prd-public(b0efb401-67ce-41e2-8a2c-3088f1ea78fe), cadvisor-9c2zh_monitoring(5bfab22d-27e5-4d89-9094-63fa9b19c166), log-router-log-router-l89zn_infra-system(c2871609-789c-4dfd-ae40-ce2f3001571a), witness-v2-node-ftbnm_monitoring(33807f39-e390-49d1-a37c-b2ec254e8294), prom-prometheus-node-exporter-dlz2m_monitoring(a7a62781-c109-4f47-808b-de2a9e96d3ba), kube2iam-hfxrf_infra-system(17b7b270-52b6-4f50-93f5-e4eb02a7c9b8)
I0411 05:09:22.097363   22453 eviction_manager.go:346] eviction manager: must evict pod(s) to reclaim ephemeral-storage
I0411 05:09:23.059423   22453 eviction_manager.go:581] eviction manager: pod k8s-jumpbox-586f64b4c7-6dr47-prd-internal(9ea687f2-74a9-459e-83b4-2c21e64a45f7) is evicted successfully
I0411 05:09:23.059444   22453 eviction_manager.go:195] eviction manager: pods k8s-jumpbox-586f64b4c7-6dr47-prd-internal(9ea687f2-74a9-459e-83b4-2c21e64a45f7) evicted, waiting for pod to be cleaned up
I0411 05:09:26.059753   22453 eviction_manager.go:408] eviction manager: pods k8s-jumpbox-586f64b4c7-6dr47-prd-internal(9ea687f2-74a9-459e-83b4-2c21e64a45f7) successfully cleaned up
W0411 05:50:33.796776   22453 eviction_manager.go:335] eviction manager: attempting to reclaim ephemeral-storage
W0411 05:50:33.882065   22453 eviction_manager.go:422] eviction manager: unexpected error when attempting to reduce ephemeral-storage pressure: wanted to free 9223372036854775807 bytes, but freed 0 bytes space with errors in image deletion: rpc error: code = Unknown desc = Error response from daemon: conflict: unable to remove repository reference "protokube:1.16.4" (must force) - container 68ebe099df35 is using its referenced image 46ca4d15fc48
I0411 05:50:33.900833   22453 eviction_manager.go:346] eviction manager: must evict pod(s) to reclaim ephemeral-storage
I0411 05:50:33.901163   22453 eviction_manager.go:364] eviction manager: pods ranked for eviction: calico-node-zsb6k_kube-system(a13f46f6-9b7d-4c1e-87a6-783e69986a2c), kube-proxy-ip-10-1-1-72.us-west-2.compute.internal_kube-system(547051e7ebf9c0803a04e7ef36f64b53), rabbitmq-8c9868c89-ddcg7-prd-internal(27fbbcb6-54b5-4f93-9355-0942f3621081), incident-manager-6f4b48dc66-w2bvw-prd-internal(1ffe9b46-3860-4902-80c9-c07e6784fdd0), inventory-7d9cc6cd74-4zbjv-prd-interface(8af7d4e4-435d-441f-8bd4-842f5865885d), sre-ssh-794cb4dc8c-6jtmp-prd-internal(83596430-b96e-4937-9990-7b86a9497415), fractal-ui-6788765ff4-csws5-prd-public(b2440d7c-17a4-4d87-a9d9-bcbf7ba6b58e), fm-mon-ui-755bff6fd9-svfrn-prd-internal(09f9db9f-3867-4a48-841e-5b9a8d8a24a4), -st2actionrunner-5ffb8bc4f4-7xp7m-prd-internal(7f41bf93-4a70-470e-9e02-e04b530e12bb), network-orchestrator-7c8d94d96b-jdfql-prd-orchestration(2bf16f2d-66aa-484b-949a-88ea07c608f2), workload-platform-controller-7bc74748f6-5bll6-prd-orchestration(d0ae5057-6d2b-4327-b82b-2623f5514128), controller-service-56f8744b6f-khvr8-prd-orchestration(d1ae9fff-4318-45e0-aa52-314d6ba9b528), certificate-worker-c454b5757-vpllk-prd-worker(c88e779b-41d4-4abc-8a01-cdce0c64acd7), config-provider-868949d56c-2tp99-prd-interface(6ca3447a-4c85-4663-b173-94241f23b414), zookeeper-0-prd-public(b0efb401-67ce-41e2-8a2c-3088f1ea78fe), cadvisor-9c2zh_monitoring(5bfab22d-27e5-4d89-9094-63fa9b19c166), log-router-log-router-l89zn_infra-system(c2871609-789c-4dfd-ae40-ce2f3001571a), witness-v2-node-ftbnm_monitoring(33807f39-e390-49d1-a37c-b2ec254e8294), prom-prometheus-node-exporter-dlz2m_monitoring(a7a62781-c109-4f47-808b-de2a9e96d3ba), kube2iam-hfxrf_infra-system(17b7b270-52b6-4f50-93f5-e4eb02a7c9b8)
I0411 05:50:34.443727   22453 eviction_manager.go:195] eviction manager: pods calico-node-zsb6k_kube-system(a13f46f6-9b7d-4c1e-87a6-783e69986a2c) evicted, waiting for pod to be cleaned up
I0411 05:50:34.443712   22453 eviction_manager.go:581] eviction manager: pod calico-node-zsb6k_kube-system(a13f46f6-9b7d-4c1e-87a6-783e69986a2c) is evicted successfully

```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.16.15
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`):  AL2
- Kernel (e.g. `uname -a`): 4.14.219-164.354.amzn2.x86_64
- Install tools: kOps
- Network plugin and version (if this is a network-related bug): Calico
- Others:

What we don't fully understand is the criteria here for the ranked eviction list. Since this pressure event was ephemeral-storage, it seems that QoS is not used (potentially not used for any evictions). We expected that since Calico was running with system-node-critical priorityclass that it would be spared from eviction, but that does not appear to be the case. kube-proxy was also ranked 3rd in the list, but that fails to evict since its a static pod. The pods in namespaces outside of kube-system have a limit-range set so there is a default cpu/mem request and limit, as well as ephemeral-storage request and limit set. These do not match so majority of pods get `Burstable` QoS. Calico had cpu request set but nothing else (I am aware this should be changed). We were suspecting it was related to the missing ephemeral-storage (thinking that any amount of usage > 0, would put it ranked at top of eviction priority) but the very first pod to be evicted had ephemeral-storage set. 

There is some additional conversation here: https://kubernetes.slack.com/archives/C0BP8PW9G/p1618521184209800.

**Comment by sftim** [comment]
I'm not sure that this is a _bug_. My understanding is that eviction and scheduling have been implemented separately: the node (usually the `kubelet`) makes eviction decisions, whilst a scheduler (usually `kube-scheduler`) makes scheduling decisions. If a Pod is evicted, PodPriority helps the scheduler choose where to put its **replacement**.

Eviction is different from preemption. If the scheduler needs to preempt Pods (for example, to schedule a `system-node-critical` Pod that is not yet assigned to a node), then the scheduler does have regard to PodPriority when deciding which Pods to _preempt_.

So that's how Kubernetes works now, at least as I understand it. However, it's surprising enough behavior that @erismaster has filed this as a bug report. In my view there is a case for having the kubelet pay attention to relative Pod priorities when making eviction decisions. Potentially the kubelet could even ask the scheduler for an eviction _recommendation_ and fall back to a local decision if no control plane hint arrives promptly.

I might be wrong, and the node already does take these details into account. If the situation is as I've described and we want to discuss those kind of improvements I've sketched out, I recommend shifting that discussion into a new feature request and probably a [KEP](https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement).

I'll stay subscribed to this issue to find out how it gets triaged. The outcome will influence my take on how SIG Docs should document these concepts (scheduling, eviction, preemption).

**Comment by dashpole** [comment]
The kubelet [takes priority into account](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/helpers.go#L640) when evicting pods today, so this is likely a bug

**Comment by dashpole** [comment]
Confirmed that this was the behavior in 1.16.15 as well: https://github.com/kubernetes/kubernetes/blob/v1.16.15/pkg/kubelet/eviction/helpers.go#L656

**Comment by dashpole** [comment]
> The pods in namespaces outside of kube-system have a limit-range set so there is a default cpu/mem request and limit, as well as ephemeral-storage request and limit set

I suspect this is the reason why it was evicted, although I wouldn't necessarily change that.

The ranking algorithm is:

1. Prioritize evicting pods where (Usage > requests)
2. Prioritize evicting the lowest priority pods
3. Prioritize evicting pods with the largest Usage - Requests (absolute).

Since kubernetes doesn't overcommit resources, we know that `sum(requests) over all pods < total disk space available`.  This allows us to ensure (with a caveat below ****) that no pod which uses less than it requests is evicted.  Then, we can give priority to remaining "unrequested" resources to high-priority pods, and lastly evict the pods which are using the most "extra" resources above what they requested.

So my best guess as to why the ranking was the way it was is...

* The "other" de-prioritized pods all had ephemeral storage requests set, and kept usage < requests.
 * jumpbox, calico and kube-proxy were exceeding their requests (assume req == 0 for no requests).
 * among jumpbox, calico, and KP, calico and KP were de-prioritized because of their high priority.

**** caveat:  disk space used by container images is variable, and not accounted for today.  This means that even if all pods use less than their requests, eviction is still possible for disk.  Accounting for them is a hard problem, since container image layers can be shared by multiple containers.

What you can do to prevent this in the future:

1. Set Ephemeral storage requests on calico.  Ideally set them so they are higher than your expected usage.
2. Set `--kube-reserved` for ephemeral storage to account for image disk space usage.  This will decrease your node's Allocatable by the amount reserved, and help mitigate the caveat above.

**Comment by desponda** [comment]
@dashpole I think that doesn't match with what the kubernetes documentation states here: https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#evicting-end-user-pods, specifically the part on:

` If the kubelet is responding to lack of available disk, it ranks Pods within a quality of service that consumes the largest amount of disk and kills those first.`

After reading through the code and understanding it, quality of service is not factored into the decision of evicting a pod so it seems this is an error in documentation or confusing at best. 

The paragraph above that in the same section also references QoS classes which, again, do not factor into diskpressure evictions, and also do not take into consideration the `limit` of the ephemeral storage.

**Comment by sftim** [comment]
BTW if this is specifically a documentation issue, the best place to flag it is at https://github.com/kubernetes/website

**Comment by sftim** [comment]
Thanks @dashpole

**Comment by erismaster** [comment]
@dashpole I think its worth mentioning that k8s-jumpbox _does_ has ephemeral-storage limit and request set, while calico does not. So we had 1 pod that had ephemeral-storage get evicted before the ones we know do not.

**Comment by erismaster** [comment]
> BTW if this is specifically a documentation issue, the best place to flag it is at https://github.com/kubernetes/website

I suspect that ultimately thats what we may have here. I'd be happy to take a stab at clarifying the docs.

**Comment by dashpole** [comment]
> I think its worth mentioning that k8s-jumpbox does has ephemeral-storage limit and request set, while calico does not. So we had 1 pod that had ephemeral-storage get evicted before the ones we know do not.

Yeah, my theory was that k8s-jumpbox's usage was more than its request.  Are request and limit the same, or is limit higher?

**Comment by erismaster** [comment]
The are different - Request is 256Mi (defaulted from limit-range), limit is 32Gi (again, defaulted from limit-range). That was my theory as well, so seems we independently agree on why this was evicted first. 

> among jumpbox, calico, and KP, calico and KP were de-prioritized because of their high priority.
Am I reading this correctly that pods with a higher priority (derived from priorityClass) would be evicted _before_ pods with a lower priority? That feels backwards to me, as a cluster operator.

**Comment by dashpole** [comment]
> Am I reading this correctly that pods with a higher priority (derived from priorityClass) would be evicted before pods with a lower priority? That feels backwards to me, as a cluster operator.

No, I meant calico and KP were less likely to be evicted than jumpbox

**Comment by erismaster** [comment]
Okay so to summarize, we are thinking that there is no bug, maybe documentation could clarify that QoS is _not_ used and that the following decision tree is what is used:
```
Prioritize evicting pods where (Usage > requests)
Prioritize evicting the lowest priority pods
Prioritize evicting pods with the largest Usage - Requests (absolute).
```
for eviction decisions. 

I think what's really confusing in the docs is that it's using the terminology from QoS (`BestEffort`, `Burstable`, and `Guaranteed`) while thats not really the case. 

> The kubelet ranks Pods for eviction first by whether or not their usage of the starved resource exceeds requests, then by Priority, and then by the consumption of the starved compute resource relative to the Pods' scheduling requests.

> As a result, kubelet ranks and evicts Pods in the following order:

> BestEffort or Burstable Pods whose usage of a starved resource exceeds its request. Such pods are ranked by Priority, and then usage above request.
Guaranteed pods and Burstable pods whose usage is beneath requests are evicted last. 
Guaranteed Pods are guaranteed only when requests and limits are specified for all the containers and they are equal. Such pods are guaranteed to never be evicted because of another Pod's resource consumption. If a system daemon (such as kubelet, docker, and journald) is consuming more resources than were reserved via system-reserved or kube-reserved allocations, and the node only has Guaranteed or Burstable Pods using less than requests remaining, then the node must choose to evict such a Pod in order to preserve node stability and to limit the impact of the unexpected consumption to other Pods. In this case, it will choose to evict pods of Lowest Priority first.

Is it safe to assume that any pod running without ephemeral-storage set will always be violating the requests?

**Comment by dashpole** [comment]
> I think what's really confusing in the docs is that it's using the terminology from QoS (BestEffort, Burstable, and Guaranteed) while thats not really the case.

> Is it safe to assume that any pod running without ephemeral-storage set will always be violating the requests?

Yes.  In theory, you could _never_ write a log line or touch any file, and you'd be able to not violate, but that's probably not worth mentioning.

**Comment by erismaster** [comment]
Okay I'll work on a docs update, hopefully be able to get a PR up today - do you want to be cc'd on that one @dashpole?

Regarding this issue, I think we're safe to close it (Or I can leave this open until the docs PR is up?) 

Appreciate the helpful and quick triaging @dashpole and @sftim!

**Comment by erismaster** [comment]
This is fine to leave closed. The docs around this issue have since been updated and clarified the behavior around this situation.
