### ISSUE TITLE
Add sync to the windows node for storage E2E tests

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes/kubernetes#101172]
#### What would you like to be added:

We'd like to add https://docs.microsoft.com/en-us/sysinternals/downloads/sync to the windows nodes

#### Why is this needed:

Discussed in https://github.com/kubernetes/kubernetes/pull/100377#discussion_r614367327, some storage e2e tests need the `sync` call to flush data to disk, this utility is not available in windows nodes or agnhost

/sig storage
/sig testing

**Comment by jsturtevant** [comment]
Does sync only need to be in Agnhost or also on the Windows node?  I don't think there is any issue with adding to the agnhost for this tests.  Has it been tested that it works?

/cc @claudiubelu in case you have thoughts

**Comment by mauriciopoppe** [comment]
In the README of sync it says: 

> Unfortunately, Sync requires administrative privileges to run.

Initially I thought it could be added to agnhost however @jingxu97 told me that Windows containers cannot run in privileged mode as of today.

cc @msau42 @jingxu97

**Comment by jsturtevant** [comment]
Since we run the Windows Test containers as `ContainerAdministrator` they should have full access to modify the host files if the host path is mapped in.

**Comment by mauriciopoppe** [comment]
I downloaded the zip file and I checked that it has an EULA, @jsturtevant do you know which sig would help with the license?

**Comment by claudiubelu** [comment]
Hm, if the sysinternal sync.exe is problematic, what about the GNU one?

```
PS C:\Users\Administrator\Downloads> sync --help
Usage: /usr/bin/sync [OPTION] [FILE]...
Synchronize cached writes to persistent storage

If one or more files are specified, sync only them,
or their containing file systems.

  -d, --data             sync only file data, no unneeded metadata
  -f, --file-system      sync the file systems that contain the files
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <http://www.gnu.org/software/coreutils/>
Report sync translation bugs to <http://translationproject.org/team/>
Full documentation at: <http://www.gnu.org/software/coreutils/sync>
or available locally via: info '(coreutils) sync invocation'
PS C:\Users\Administrator\Downloads> get-command sync | Select-Object Path

Path
----
C:\Program Files\Git\usr\bin\sync.exe
```

It seems to come from coreutils, which can easily be downloaded and extracted from. Hopefully, they are 64-bit binaries.

Anyways, I think adding ``sync.exe`` is a good idea, there are a few other non-conformance tests that are calling sync.

**Comment by jsturtevant** [comment]
@mauriciopoppe I believe that would be sig-contributor-experience.  I thought we were using other sys-internal tools as well but it is a good idea to double check.

**Comment by BenTheElder** [comment]
/remove-sig testing
we don't own the nodes (?)

**Comment by claudiubelu** [comment]
I've sent https://github.com/kubernetes/kubernetes/pull/103976 , which would add ``sync.exe`` to agnhost, as you required. I've also built ``claudiubelu/agnhost:2.33`` using that PR. Let us know if that satisfies your requirements, we could merge afterwards.

```
docker run --rm --entrypoint sync.exe claudiubelu/agnhost:2.33 --help
Unable to find image 'claudiubelu/agnhost:2.33' locally
2.33: Pulling from claudiubelu/agnhost
ba17af31b927: Pull complete
...
7f46c3c5afe7: Pull complete
Digest: sha256:0e5869ae59ad8609b96d1e750205be6cb190fc59ee4ee648635f27d8dbd808fd
Status: Downloaded newer image for claudiubelu/agnhost:2.33
Usage: sync.exe [OPTION] [FILE]...
Synchronize cached writes to persistent storage

If one or more files are specified, sync only them,
or their containing file systems.

  -d, --data             sync only file data, no unneeded metadata
  -f, --file-system      sync the file systems that contain the files
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/sync>
or available locally via: info '(coreutils) sync invocation'

This is an UNSUPPORTED, UNTESTED, EXPERIMENTAL build of GNU coreutils.
USE AT YOUR OWN RISK.
```

**Comment by mauriciopoppe** [comment]
Thanks @claudiubelu, I guess we can merge the PR and I can run the storage e2e tests that need `sync`.
