### ISSUE TITLE
Error Stacked control plane and etcd nodes

### ISSUE THREAD

**Issue by leosantosazevedo** [kubernetes/kubernetes#101117]
Failed add master in cluster multi master.
I following this document
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/#set-up-the-etcd-cluster

#### Which jobs are failing:

These first node started my cluster

[kubelet-finalize] Updating "/etc/kubernetes/kubelet.conf" to point to a rotatable kubelet client certificate and key
[addons] Applied essential addon: CoreDNS
[addons] Applied essential addon: kube-proxy

Your Kubernetes control-plane has initialized successfully!

To start using your cluster, you need to run the following as a regular user:

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

Alternatively, if you are the root user, you can run:

  export KUBECONFIG=/etc/kubernetes/admin.conf

You should now deploy a pod network to the cluster.
Run "kubectl apply -f [podnetwork].yaml" with one of the options listed at:
  https://kubernetes.io/docs/concepts/cluster-administration/addons/

You can now join any number of the control-plane node running the following command on each as root:

  kubeadm join k8s-haproxy:6443 --token cxlxmr.b04aeu8n91z7tb75 \
        --discovery-token-ca-cert-hash sha256:031847d16e958d99ac6116a952a9dcb567609d2c21196c0da37be57c0ee189e7 \
        --control-plane --certificate-key 88afb2baf092e556f25c53527391671311f6cdd713ddb8ba0cd21886859d2793

Please note that the certificate-key gives access to cluster sensitive data, keep it secret!
As a safeguard, uploaded-certs will be deleted in two hours; If necessary, you can use
"kubeadm init phase upload-certs --upload-certs" to reload certs afterward.

Then you can join any number of worker nodes by running the following on each as root:

kubeadm join k8s-haproxy:6443 --token cxlxmr.b04aeu8n91z7tb75 \
        --discovery-token-ca-cert-hash sha256:031847d16e958d99ac6116a952a9dcb567609d2c21196c0da37be57c0ee189e7

root@k8s-master-0:~# kubectl get nodes
NAME           STATUS   ROLES                  AGE     VERSION
k8s-master-0   Ready    control-plane,master   7m22s   v1.21.0
root@k8s-master-0:~# kubectl get nodes
Error from server: etcdserver: request timed out
root@k8s-master-0:~# kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
root@k8s-master-0:~#
root@k8s-master-0:~# kubectl get nodes
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
root@k8s-master-0:~#  kubectl get pods
Error from server (InternalError): an error on the server ("") has prevented the request from succeeding
root@k8s-master-0:~#

#### Which test(s) are failing:

These second node started my cluster

root@k8s-master-1:~#
root@k8s-master-1:~# kubeadm join k8s-haproxy:6443 --token cxlxmr.b04aeu8n91z7tb75 \
>         --discovery-token-ca-cert-hash sha256:031847d16e958d99ac6116a952a9dcb567609d2c21196c0da37be57c0ee189e7 \
>         --control-plane --certificate-key 88afb2baf092e556f25c53527391671311f6cdd713ddb8ba0cd21886859d2793
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks before initializing the new control plane instance
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[download-certs] Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [k8s-master-1 localhost] and IPs [192.168.0.251 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [k8s-master-1 localhost] and IPs [192.168.0.251 127.0.0.1 ::1]
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [k8s-haproxy k8s-master-1 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.0.251]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Valid certificates and keys now exist in "/etc/kubernetes/pki"
[certs] Using the existing "sa" key
[kubeconfig] Generating kubeconfig files
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[check-etcd] Checking that the etcd cluster is healthy
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[etcd] Announced new etcd member joining to the existing etcd cluster
[etcd] Creating static Pod manifest for "etcd"
[etcd] Waiting for the new etcd member to join the cluster. This can take up to 40s
[kubelet-check] Initial timeout of 40s passed.
error execution phase control-plane-join/etcd: error creating local etcd static pod manifest file: timeout waiting for etcd cluster to be available
To see the stack trace of this error execute with --v=5 or higher
root@k8s-master-1:~#
root@k8s-master-1:~#

**Comment by neolit123** [comment]
hi, i don't see a bug in kubeadm here.
please try the support forums or #kubeadm on k8s slack first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
