### ISSUE TITLE
[Failing Test] AzureDisk CSI Driver End-to-End Tests: Pre-Provisioned [single-az] should create an inline volume by in-tree driver

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#101196]
#### Which jobs are failing:

pull-kubernetes-e2e-aks-engine-azure-disk-windows-dockershim

#### Which test(s) are failing:

AzureDisk CSI Driver End-to-End Tests: Pre-Provisioned [single-az] should create an inline volume by in-tree driver [kubernetes.io/azure-disk] 

> 

> /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:262 Test Panicked /usr/local/go/src/runtime/panic.go:212  Panic: runtime error: invalid memory address or nil pointer dereference  Full stack: sigs.k8s.io/azuredisk-csi-driver/test/e2e.glob..func2.3.7() 	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning_test.go:269 +0x1f4 sigs.k8s.io/azuredisk-csi-driver/test/e2e.TestE2E(0xc0002dbc80) 	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/suite_test.go:201 +0x1b6 testing.tRunner(0xc0002dbc80, 0x1f6b4f0) 	/usr/local/go/src/testing/testing.go:1194 +0xef created by testing.(*T).Run 	/usr/local/go/src/testing/testing.go:1239 +0x2b3

#### Since when has it been failing:

It seems the test start to run on that job on 14/4

#### Testgrid link:

https://testgrid.k8s.io/sig-windows-presubmit#pull-kubernetes-e2e-aks-engine-azure-disk-windows-dockershim&width=5

This is running in presubmit jobs with a very low rate of success :/

**Comment by andyzhangx** [comment]
this issue is fixed

**Comment by aojea** [comment]
Thanks for the prompt response
