### ISSUE TITLE
Scheduler Code Deep Cleanup: Scheduler, genericScheduler, and SchedulerAlgorithm

### ISSUE THREAD

**Issue by Jerry-Ge** [kubernetes/kubernetes#101135]
#### What would you like to be added:
Refactor the names of `Scheduler`, `SchedulerAlgorithm`, and `genericScheduler` to something like: 
`Scheduler`, `SchedulerAlgorithm`, and`SchedulerAlgorithmImpl`

#### Why is this needed:
I was reading the scheduler framework code and found out very confusing when reading the `type Scheduler struct` and `type genericScheduler struct` ([link](https://github.com/kubernetes/kubernetes/blob/8edda782f30a377afd031d5d7f4d62551785c441/pkg/scheduler/core/generic_scheduler.go#L79)). The name `genericXXXX` sounds very generic at least to myself... and no comments were there. 

In reality, the `genericScheduler` is just an implementation of the `SchedulerAlgorithm` interface above which will act as the algorithm component in the scheduler object. 

Another note is there was a TODO to rename the `SchedulerAlgorithm struct` before. ([Link](https://github.com/kubernetes/kubernetes/blob/8edda782f30a377afd031d5d7f4d62551785c441/pkg/scheduler/core/generic_scheduler.go#L60))

So, I suggest for the better organization of the scheduler code, some code refactorings of names of `Scheduler`, `SchedulerAlgorithm`, and `genericScheduler` is quite necessary.

**Comment by Jerry-Ge** [comment]
@alculquicondor @Huang-Wei @chendave Appreciate any of your opinions :D

**Comment by alculquicondor** [comment]
what @ahg-g and I have discussed before is entire getting rid of `SchedulerAlgorithm` and `genericScheduler`. IIRC, autoscaler used to use the `genericScheduler` to reuse scheduler code, but now it uses a `schedulerFramework`. So, with the existence of the scheduler framework, there is no need of 3 layers. Then, we should be merging whatever is in `genericScheduler` into the framework or `Scheduler`.

If you can find a way to do this in incremental PR, I'm all in favor of that.

Renaming might help understanding the codebase, but it doesn't moving away from this structure.

**Comment by ahg-g** [comment]
Correct, we want to get rid of ScheduleAlgorithm and also refactor the code such that core/generic_scheduler.go and scheduler.go are merged and move whatever make sense to framework. Lots of code already moved out such as binding and preemption.

Looking at both those files, I don't think there is much we can move to the framework, so I think the next step is to work on merging them.

**Comment by Huang-Wei** [comment]
It makes sense to eliminate `ScheduleAlgorithm`. Additionally, we can use this chance to do a deep cleanup of `Scheduler`. For example, function `NextPod()` is basically equivalent to the embedded SchedulingQueue's Pop(), and hence not quite needed to be part of `Scheduler`.

**Comment by Jerry-Ge** [comment]
Great! thanks, guys and I will start this mission with some incremental PRs.

**Comment by ahg-g** [comment]
Please send a plan before start sending PRs; it could be as simple as a checkbox task list in this issue of what you are planing to change/move.

**Comment by Jerry-Ge** [comment]
### I am planning to do this job architecturally in the following three phases (PRs). 

| ID      | Status      | Description | Comments     |  Related PR
| :---:  | :---:           |    :---            |          :---        | :---              |
| 1        |     :x:             | Remove all the unreferenced functions in generic_scheduler.go             | Shouldn't have any sideffects     | 
| 2        |     :x:   | Move the core Schedule function to scheduler.go  and related tests      |  The HEAVY part since most of the functions have dependencies     |
| 3        |     :x:   | More cleanups in scheduler.go        |  e.g. NextPod() function     |

However, it seems that the 2nd part will be extremely heavy. Any comments or suggestions to break that will be very appreciated. 

I also prepared a WIP mini-design doc for tracking this job. [[Link to Google Doc](https://docs.google.com/document/d/16auD8S8p6rApOlucS6Lc6u6zacfqzFmvHUOfmhNSYB0/edit?usp=sharing)]

**Comment by alculquicondor** [comment]
Perhaps you can split 2 in more than one PR

**Comment by Huang-Wei** [comment]
I'd suggest tweaking the plan a bit:

1. Unroll ScheduleAlgorithm#Extenders() to Scheduler.go ([1.diff](https://gist.github.com/Huang-Wei/53fafb11d2da1a65eb606e44061f6816) for your reference)
    - in scheduer.go, just specify an `Extenders` slice (instead of function `Extenders()`)
    - [temporary] add `[]framework.Extender` to ScheduleAlgorithm#Schedule()
    - so we can make some functions (e.g., g.findNodesThatPassExtenders, g.prioritizeNodes) stateless by adding extenders slice into the function signature, and you can keep stateful function as-is and refactor later
2. Unroll ScheduleAlgorithm#Schedule() to Scheduler.go (you may split this into a couple of PRs if needed)

**Comment by Jerry-Ge** [comment]
> I'd suggest tweaking the plan a bit:
> 
> 1. Unroll ScheduleAlgorithm#Extenders() to Scheduler.go ([1.diff](https://gist.github.com/Huang-Wei/53fafb11d2da1a65eb606e44061f6816) for your reference)
>    
>    * in scheduer.go, just specify an `Extenders` slice (instead of function `Extenders()`)
>    * [temporary] add `[]framework.Extender` to ScheduleAlgorithm#Schedule()
>    * so we can make some functions (e.g., g.findNodesThatPassExtenders, g.prioritizeNodes) stateless by adding extenders slice into the function signature, and you can keep stateful function as-is and refactor later
> 2. Unroll ScheduleAlgorithm#Schedule() to Scheduler.go (you may split this into a couple of PRs if needed)

Just back from holiday. Thanks @Huang-Wei  for the detailed review and guidance! I will prepare another PR beginning with the Extenders() unrolling.

**Comment by Jerry-Ge** [comment]
Note: Going on a long vacation, will return back to this in August :)

**Comment by chendave** [comment]
@alculquicondor Jerry is out of duty at the moment, as far as I know he won't be able to work on this anymore.

maybe I or @ruquanzhao could take over it.

/cc @ruquanzhao

/remove-lifecycle stale
