### ISSUE TITLE
[sig-autoscaling] update client-go to 1.14+ in images

### ISSUE THREAD

**Issue by zshihang** [kubernetes/kubernetes#101286]
#### What happened:

the following images are using old client-go that would not work correctly starting 1.22+ if those images use in-cluster config(mounted service account token) to talk to kube-apiserver:
- k8s.gcr.io/addon-resizer

#### What you expected to happen:

if the above images use in-cluster config, they should use client-go 1.14+.

xref: https://github.com/kubernetes/kubernetes/issues/75551

/assign @mwielgus 
/cc @liggitt
/sig autoscaling
/priority important-soon

**Comment by zshihang** [comment]
any updates here?

/cc @kubernetes/sig-autoscaling-bugs

**Comment by liggitt** [comment]
cc @bskiba
