### ISSUE TITLE
Not able to create kube-proxy pod

### ISSUE THREAD

**Issue by jayanta5050** [kubernetes/kubernetes#101258]
I had create 3 node kubernetes cluster
1 Master
2 Worker Nodes
By mistake kube-proxy dockers and pod got deleted in one worker node, How to create kube-proxy docker and pod in one node again.

In first worker node below dockers are running...
![image](https://user-images.githubusercontent.com/79866150/115300779-60d3e880-a12e-11eb-8f67-f1236187f6d1.png)

In second worker node below dockers are running..
![image](https://user-images.githubusercontent.com/79866150/115300817-6b8e7d80-a12e-11eb-875f-f3775f3faf53.png)

In master node, below pods i can see
![image](https://user-images.githubusercontent.com/79866150/115300839-7517e580-a12e-11eb-8430-33be5205e966.png)

How are re create the kube-proxy in the first worker node ?

**Comment by neolit123** [comment]
please use the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/remove-kind bug
/kind support
