### ISSUE TITLE
allowing kernel.shmmax & kernel.shmall for TimesTen db pod's in Kubernetes

### ISSUE THREAD

**Issue by Cheers-am** [kubernetes/kubernetes#101227]
#### What happened:
Unable to allow kernel.shmmax & kernel.shmall  in security context
#### What you expected to happen:
deinfe kernel.shmmax & kernel.shmall  value for TimesTen POD.

#### Environment:

- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T11:45:27Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
  DL360
- OS (e.g: `cat /etc/os-release`):
  SLES 15 SP2

- Kernel (e.g. `uname -a`):
  4.12.14-23-default #1 SMP Tue May 29 21:04:44 UTC 2018 (cd0437b) x86_64 x86_64 x86_64 GNU/Linux
 
- Network plugin and version (if this is a network-related bug):
 calico

**Comment by Cheers-am** [comment]
/sig/kubernetes

**Comment by matthyx** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close
