### ISSUE TITLE
no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30"

### ISSUE THREAD

**Issue by zhuyouzhufu** [kubernetes/kubernetes#101222]
#### Environment:
- Kubernetes version (1.2.1):

kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1
bindTimeoutSeconds: 600
clientConnection:
  burst: 200
  kubeconfig: /opt/kubernetes/server/conf/kube-scheduler.kubeconfig
  qps: 100
enableContentionProfiling: false
enableProfiling: true
hardPodAffinitySymmetricWeight: 1
healthzBindAddress: 192.168.100.33:10251
leaderElection:
  leaderElect: true
metricsBindAddress: 192.168.100.33:10251
EOF

The following error message appears when starting the service of
4月 19 00:22:10 k8s_master_hangzhou kube-scheduler[3504]: no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30"

![image](https://user-images.githubusercontent.com/34908518/115152869-97b1ec00-a0a5-11eb-962e-632bae6ecaaf.png)

**Comment by zhuyouzhufu** [comment]
KUBE_SCHEDULER_OPTS="--logtostderr=false \\
--v=2 \\
--config=/opt/kubernetes/server/conf/kube-scheduler.yml \\
--log-dir=/opt/kubernetes/server/logs \\
--cert-dir=/opt/kubernetes/server/ssl \\
--leader-elect=true \\
--alsologtostderr=true \\
--bind-address=192.168.100.33 \\
--master=https://192.168.100.33:6443

**Comment by neolit123** [comment]
try:
```
kind: KubeSchedulerConfiguration
apiVersion: kubescheduler.config.k8s.io/v1beta1
```

/kind support
/remove-kind bug
/sig scheduling

**Comment by neolit123** [comment]
use the support forums and #sig-scheduling on k8s slack for more questions about this:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
