### ISSUE TITLE
Provide "Updating Clusters" example

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#10126]
We have a [Live update example](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide/update-demo) for updating pods. We should have a corresponding example for updating clusters.

**Comment by thockin** [comment]
load-balancing some docs @alex-mohr and WAW folks @wojtek-t

**Comment by wojtek-t** [comment]
@piosz - can you please take a look?

**Comment by brendandburns** [comment]
Taking this as it appears to be unloved right now...

**Comment by bgrant0607** [comment]
#11402 was merged. Can this be closed?

**Comment by RichieEscarez** [comment]
This issue is to provide a corresponding "example" for updating a cluster (to live along side [Updating Live Pods](http://kubernetes.io/v1.0/docs/user-guide/update-demo/README.html) in the Examples section). 

I think this can move into the back log until we have a formal, non-experimental process for updating nodes in the other supported platforms (not only GKE/GCE-OSS nodes).

**Comment by mikedanese** [comment]
cc @vishh
