### ISSUE TITLE
where to fix command line references?

### ISSUE THREAD

**Issue by ssbostan** [kubernetes/kubernetes#101201]
Hi, I want to fix some issues on command line tools references but i don't found the source of that.

How to solve command line tools references and trigger document auto-generation tool?

**Comment by neolit123** [comment]
if the is a problem with the tools that generate the docs its here:
https://github.com/kubernetes-sigs/reference-docs

the docs are organized and hosted at https://github.com/kubernetes/website

if there is a problem with specific content like a CLI flag it must be changed in kubernetes/kubernetes as that is where the command line ref. docs are generated from:
https://github.com/kubernetes/kubernetes/tree/master/cmd

/kind support
/close

**Comment by neolit123** [comment]
you can long an issue in https://github.com/kubernetes/website too.
