### ISSUE TITLE
Express "schedule my deployment pods on at least two nodes"

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kubernetes#101270]
How to express "schedule my deployment pods on at least two nodes" with current schedule primitives.

If my deployment can have 10 pods, i want all of them to be scheduled on at least two nodes instead of only one node. I know this may result in Pending pods when there are no additional node is available. We need to distributed pods on at least two nodes to keep a high availability incase on node is down and all pods are on that.

**Comment by pacoxu** [comment]
podAntiAffinity with preferredDuringSchedulingIgnoredDuringExecution may help
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity-beta-feature

**Comment by andyxning** [comment]
@pacoxu `SelectorSpreadPriority` is trying to minimize the number of pods on the same node not try to enforce it which is what i desire

**Comment by alculquicondor** [comment]
There is no such primitive.

You can use required topology spreading to force the scheduler to keep a balanced number of pods in between all nodes that qualify to host the pod  https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/ (see the usage of `whenUnsatisfiable: DoNotSchedule`).

However, I would recommend to stick with `whenUnsatisfiable: ScheduleAnyway` and let kube-scheduler take a best-effort approach.

**Comment by alculquicondor** [comment]
/close

Github is not the appropriate venue to ask for support. You can consider asking in stackoverflow or the slack channel for https://kubernetes.slack.com/messages/kubernetes-users
