### ISSUE TITLE
Connection with Kubectl does not work over LoadBalancer

### ISSUE THREAD

**Issue by Craftoncu** [kubernetes/kubernetes#101289]
#### What happened:
Connection with Kubectl does not work over LoadBalancer

#### How to reproduce it (as minimally and precisely as possible):
Setup clean cluster, add all server to a vnet, create loadbalancer service out of k8s, connect to public load balancer ip:6443

#### Anything else we need to know?:
HetznerCloud & If I target a single server, its working.

#### Environment:
- Kubernetes version (use `kubectl version`): 20
- Cloud provider or hardware configuration: Hetzner Cloud
- OS (e.g: `cat /etc/os-release`): Deb 10 Buster

Error: 2021/04/20 20:02:06 http: proxy error: x509: certificate is valid for 10.233.0.1, 10.0.0.9, 10.0.0.6, 127.0.0.1, 10.0.0.8, (censored public ip), (censored public ip), (censored public ip), not (censored public ip of loadbalancer which points to all 3 master nodes)

**Comment by neolit123** [comment]
please try the support forums for this first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
/sig cli
