### ISSUE TITLE
400 bad request http to https ingress not working

### ISSUE THREAD

**Issue by Chauhan619** [kubernetes/kubernetes#101216]
Current situation:
Container having apache2 shibboleth running on ports 
Http: 8090
Https: 8443 self signed certificate 

Image is running fine at local but when deployed to kubernetes I am getting error while accessing https service running on container.

Ingress is sending http plain request to https port

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingresss
spec:
 tls:
 - host: *foo.com
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 8090
      - path: /ssd
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number:8443
Here http _>http is working fine but http -> https is redirecting to http<>:8443 and ending in 400 bad request

**Comment by wangyysde** [comment]
@Chauhan619 Because the certification is base on website(specified by host item) not path. For the same website,maybe you can not setup HTTP for one path and HTTPS for another.

**Comment by sftim** [comment]
/kind support
I think

**Comment by thockin** [comment]
@robscott is this a case where AppProtocol helps?

**Comment by robscott** [comment]
Hey @Chauhan619 do you know which Ingress controller/implementation you're using for this? It's possible that setting AppProtocol on the backend Service ports could help here, but would likely depend on the Ingress implementation you were using.

**Comment by thockin** [comment]
Who is doing the redirect?  Your app or the LB impl?

**Comment by thockin** [comment]
Is there more followup needed here?
