### ISSUE TITLE
[sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it [Conformance]

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#101231]
#### Which jobs are failing:
Test Kubernetes e2e suite.[sig-apps] DisruptionController should block an eviction until the PDB is updated to allow it [Conformance] has failed 8 times (no passing result found). Earliest failure found at commit/cbe41b4e7 (Sat Mar 05 07:20 PST).

#### Which test(s) are failing:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-19-on-1-21

#### Since when has it been failing:
since #100724 promote PDB e2e to conformance testing
kubeadm-kinder-kubelet-1-20-on-1-21
&
kubeadm-kinder-kubelet-1-19-on-1-21

success on 
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-21-on-latest

#### Testgrid link:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-kubelet-1-19-on-1-21

#### Anything else we need to know:
The last code change that I can find is https://github.com/kubernetes/kubernetes/pull/92991.

/cc hasheddan
As the PodDisruptionBudget API has been promoted to policy/v1 with no schema changes in 1.21, not sure if this is related.

**Comment by pacoxu** [comment]
After looking at the kubelet logs,
```
-- Logs begin at Mon 2021-04-19 05:22:05 UTC, end at Mon 2021-04-19 05:49:17 UTC. --
Apr 19 05:22:05 kinder-xony-worker-2 systemd[1]: Started kubelet: The Kubernetes Node Installer.
Apr 19 05:22:06 kinder-xony-worker-2 kubelet[86]: F0419 05:22:06.114158      86 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Apr 19 05:22:06 kinder-xony-worker-2 kubelet[86]: goroutine 1 [running]:
Apr 19 05:22:06 kinder-xony-worker-2 kubelet[86]: k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc000010001, 0xc0000c8840, 0xfb, 0x14d)
```
It seems to be related with kind kubelet initialing.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/test-infra/pull/21643
kubeadm-kinder-kubelet-1-19-on-1-21 was added 13 days ago.

**Comment by liggitt** [comment]
This test is added to conformance in 1.22 and is only expected to be run and to pass against a 1.22 API server.

**Comment by liggitt** [comment]
I thought the skew job for "on 1.x" were running the 1.x conformance tests.

**Comment by neolit123** [comment]
the problem is in the test-infra spec.
planned to send PR fix for it during the weekend, but didn't get to it.

the errors are the result of a manual update to the same spec that should be mitigated by the new tooling here:
https://github.com/kubernetes/kubeadm/issues/2430

**Comment by neolit123** [comment]
fix: https://github.com/kubernetes/test-infra/pull/21853
