### ISSUE TITLE
network name is empty under network-status annotation

### ISSUE THREAD

**Issue by amshankaran** [kubernetes/kubernetes#101214]
#### What happened:
Calico is configured as primary CNI. Created a pod (via deployment). while describing the pod, under "networks-status:" annotation,  network name is empty string "name": "" 
master-0-ejlcluster> kubectl describe pod nginx-shr-6584fcbb55-lpndj
Name:         nginx-shr-6584fcbb55-lpndj
Namespace:    default
Priority:     0
Node:         worker-pool1-w7m9sczq-ejlcluster/10.0.10.97
Start Time:   Sat, 17 Apr 2021 09:30:08 +0000
Labels:       app=nginx-shr
              pod-template-hash=6584fcbb55
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "",
                    "ips": [
                        "192.168.185.80"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "",
                    "ips": [
                        "192.168.185.80"
                    ],
                    "default": true,
                    "dns": {}
                }]

#### What you expected to happen:
under "networks-status:" annotation  "name": "k8s-pod-network" is expected.

director-0> kubectl describe pod nginx-shr-6584fcbb55-5gqnf
Name:         nginx-shr-6584fcbb55-5gqnf
Namespace:    default
Priority:     0
Node:         worker-p1-ywj6c6j5/10.0.10.17
Start Time:   Fri, 16 Apr 2021 11:01:42 +0000
Labels:       app=nginx-shr
              pod-template-hash=6584fcbb55
Annotations:  k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "192.168.248.74"
                    ],
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "k8s-pod-network",
                    "ips": [
                        "192.168.248.74"
                    ],
                    "default": true,
                    "dns": {}
                }]

#### How to reproduce it (as minimally and precisely as possible): 
just deploy a nginx pod in latest kubernets cluster
kubectl create deployment nginx-shr --image=nginx

#### Anything else we need to know?:
master-0-ejlcluster> sudo vim 00-multus.conf

{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name": "k8s-pod-network", "cniVersion": "0.3.0", "plugins": [ { "type": "calico", "log_level": "info", "etcd_endpoints": "https://10.0.10.163:2379", "etcd_key_file": "/etc/cni/net.d/calico-tls/etcd-key", "etcd_cert_file": "/etc/cni/net.d/calico-tls/etcd-cert", "etcd_ca_cert_file": "/etc/cni/net.d/calico-tls/etcd-ca", "mtu": 2070, "ipam": { "type": "calico-ipam", "assign_ipv4": "true", "assign_ipv6": "false" }, "container_settings": { "allow_ip_forwarding": true }, "policy": { "type": "k8s", "k8s_api_root": "https://[10.96.0.1]:443", "k8s_auth_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6ImhSRzZ..." }, "kubernetes": { "kubeconfig": "/etc/cni/net.d/calico-kubeconfig" } }, { "type": "portmap", "snat": true, "capabilities": {"portMappings": true} } ] } ] }

---------
master-0-ejlcluster> kubectl edit configmap calico-config -n  kube-system

apiVersion: v1
data:
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.0",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "etcd_endpoints": "__ETCD_ENDPOINTS__",
          "etcd_key_file": "__ETCD_KEY_FILE__",
          "etcd_cert_file": "__ETCD_CERT_FILE__",
          "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
          "mtu": 2070,
          "ipam": {
            "type": "calico-ipam",
            "assign_ipv4": "true",
            "assign_ipv6": "false"
          },
          "container_settings": {
            "allow_ip_forwarding": true
          },
          "policy": {
            "type": "k8s",
            "k8s_api_root": "https://[__KUBERNETES_SERVICE_HOST__]:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
  etcd_ca: /calico-secrets/etcd-ca
  etcd_cert: /calico-secrets/etcd-cert
  etcd_endpoints: https://10.0.10.163:2379
  etcd_key: /calico-secrets/etcd-key
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"calico_backend":"bird","cni_network_config":"{\n  \"name\": \"k8s-pod-network\",\n  \"cniVersion\": \"0.3.0\",\n  \"plugins\": [\n    {\n      \"type\": \"calico\",\n      \"log_level\": \"info\",\n      \"etcd_endpoints\": \"__ETCD_ENDPOINTS__\",\n      \"etcd_key_file\": \"__ETCD_KEY_FILE__\",\n      \"etcd_cert_file\": \"__ETCD_CERT_FILE__\",\n      \"etcd_ca_cert_file\": \"__ETCD_CA_CERT_FILE__\",\n      \"mtu\": 2070,\n      \"ipam\": {\n        \"type\": \"calico-ipam\",\n        \"assign_ipv4\": \"true\",\n        \"assign_ipv6\": \"false\"\n      },\n      \"container_settings\": {\n        \"allow_ip_forwarding\": true\n      },\n        \"policy\": {\n        \"type\": \"k8s\",\n        \"k8s_api_root\": \"https://[__KUBERNETES_SERVICE_HOST__]:__KUBERNETES_SERVICE_PORT__\",\n        \"k8s_auth_token\": \"__SERVICEACCOUNT_TOKEN__\"\n      },\n      \"kubernetes\": {\n          \"kubeconfig\": \"__KUBECONFIG_FILEPATH__\"\n      }\n    },\n    {\n      \"type\": \"portmap\",\n      \"snat\": true,\n      \"capabilities\": {\"portMappings\": true}\n    }\n  ]\n}","etcd_ca":"/calico-secrets/etcd-ca","etcd_cert":"/calico-secrets/etcd-cert","etcd_endpoints":"https://10.0.10.163:2379","etcd_key":"/calico-secrets/etcd-key"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"calico-config","namespace":"kube-system"}}
  creationTimestamp: "2021-04-17T05:51:09Z"
  name: calico-config
  namespace: kube-system
  resourceVersion: "19908"

**Comment by JornShen** [comment]
@amshankaran  Do you report it in the multus-cni community? 
This annotation ` k8s.v1.cni.cncf.io/network-status` is set by multus-cni.

https://github.com/k8snetworkplumbingwg/network-attachment-definition-client/blob/9d213757d22d5d06f1b8ff289ce16d0cf9aabc6c/pkg/utils/net-attach-def.go#L75

**Comment by amshankaran** [comment]
@jornShen No I haven't reported this in multus-cni. Do I need to create a new issue in multus-cni to report this or adding any flag here would do?

**Comment by JornShen** [comment]
I think it is the problem of multus-cni. So it is better to create issue in multus-cni.

**Comment by amshankaran** [comment]
> 
> Thanks @JornShen I'll create a issue in multus-cni.
> I think it is the problem of multus-cni. So it is better to create issue in multus-cni.

**Comment by aojea** [comment]
> Thanks @JornShen I'll create a issue in multus-cni.

/close

Thanks for reporting, it is better to track it only in one place
