### ISSUE TITLE
Linter for keeping configs & code in sync?

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#10124]
I had a bug in my own Go code where I forgot to update a label selector in response to a YAML config file changing (to rename a label key). I predict that I will not be the last person to make such a mistake and that others too will be driven to madness.

It would be wonderful to have some kind of system / framework where things like labels in configs are somehow kept in sync with their use in code. We can imagine all kinds of wonderful and horrible ways of doing this. I think we should do something. Personally, if it were up to me, I would write a program that parsed Go programs and analyzed their use of labels etc. but perhaps we can get away with a lighter linting solution.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (153/150 (102%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:27064)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU4y-000OhT-81
	for dev@imwiz.com; Thu, 01 Jun 2017 11:40:12 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=JXOU5JkQRaUt8bWOqUJyw8YxWWY=; b=GIpP3wspQbXJmnKP
	eiKFbx+fridh8fJ8wVkaTLUIP88mwfj3MPrbZp7we4e/fgciKMRR0vxBrvoDCth4
	e9pIRKvFbA9vV1sbIRCJfPwyD8RUBrtl4E6+vSPhrU2fFL1rPQcZrKVtwyc8WSw9
	KqgEq/iydzoRnN487GuSpixE2vI=
Received: by filter1082p1mdw1.sendgrid.net with SMTP id filter1082p1mdw1-20966-59305170-7B
        2017-06-01 17:40:00.98100184 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id i52PrOMLQGGlGLj1f97yOQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:40:00.933 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:40:00 -0700
