### ISSUE TITLE
[sig-network] update client-go to 1.14+ in images

### ISSUE THREAD

**Issue by zshihang** [kubernetes/kubernetes#101283]
#### What happened:

the following images are using old client-go that would not work correctly starting 1.22+ if those images use in-cluster config(mounted service account token) to talk to kube-apiserver:
- ~k8s.gcr.io/k8s-dns-dnsmasq-nanny~
- ~k8s.gcr.io/k8s-dns-kube-dns~
- ~k8s.gcr.io/k8s-dns-sidecar~
- k8s.gcr.io/networking/ip-masq-agent-amd64

#### What you expected to happen:

if the above images use in-cluster config, they should use client-go 1.14+.

xref: https://github.com/kubernetes/kubernetes/issues/75551

/assign @thockin @bowei 
/cc @liggitt

**Comment by liggitt** [comment]
I'd suggest leaving off the triage label so it shows up in the sig's issue workflow

**Comment by bowei** [comment]
/assign @prameshj 

Seems like all that's needed is to update and rebuild.

**Comment by prameshj** [comment]
Will update the dns images.

/assign @varunmar for ipmasq-agent image.

**Comment by prameshj** [comment]
@zshihang can you clarify which versions are ok to use?
From https://github.com/kubernetes/client-go/releases, I see new releases 0.19, 0.20, 1.5.7 -- but no versions above 1.14. Are these versions ok to use?

DNS repo currently overrides to [v0.0.0-20190620085101-78d2af792bab](https://github.com/kubernetes/dns/blob/05a4cd0f5d3b0e7a2925ff10995eb821a683103d/go.mod#L57)

**Comment by liggitt** [comment]
client-go v0.x.y versions >= v0.14.0+

**Comment by liggitt** [comment]
v0.0.0-20190620085101-78d2af792bab corresponds to kubernetes-1.15: https://github.com/kubernetes/client-go/commit/78d2af792bab

**Comment by prameshj** [comment]
Thanks Jordan! Looks like no action needed for DNS images then.

/unassign

**Comment by liggitt** [comment]
> DNS repo currently overrides to v0.0.0-20190620085101-78d2af792bab

Yes, but the current revisions of the DNS images are not being used in https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns/kube-dns. The 1.15.10 images are built on client-go v3.0.0, which corresponds to Kubernetes versions prior to 1.14 (https://github.com/kubernetes/dns/blob/1.15.10/Gopkg.toml#L70)

/assign @prameshj

**Comment by prameshj** [comment]
ip-masq-agent does not use client-go.

It uses a bunch of [k8s 1.13 libraries](https://github.com/kubernetes-sigs/ip-masq-agent/blob/5ef3c8cb0103d1564abdc4cfb16acfef82ed77a6/Godeps/Godeps.json#L67), but no client-go. 

Closing this since the DNS references have been fixed.

/close

**Comment by zshihang** [comment]
that's fast fix. thank you!
