### ISSUE TITLE
kubectl commands don't respect timeout values on non-existent cluster

### ISSUE THREAD

**Issue by idealtech-i3dlabs** [kubernetes/kubernetes#101288]
#### What happened:
kubectl --request-timeout=4 get nodes or cluster-info doesn't wait for 4 seconds before timing out. (Tried many values, same thing)
It waits for at least 20 seconds. Not sure why 20, or where it's configured. 

#### What you expected to happen:
kubectl exiting with an error after 4 seconds.

#### How to reproduce it (as minimally and precisely as possible):
time kubectl cluster-info --request-timeout=4
(must be done on a NON-EXISTENT cluster)

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
error: context deadline exceeded

real	0m20.110s
user	0m0.062s
sys	0m0.033s

As you can see, it waited 20 seconds, not 4.

#### Anything else we need to know?:
I am trying to make it work so that we can cut automation/deployment time when there is no cluster configured yet. Automation needs to use this command to check if an API replies.

#### Environment:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Does not apply, see description.
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): 5.8.0-48-generic
- Install tools: basic kubectl install from official packages.
- Network plugin and version (if this is a network-related bug): Not applicable

**Comment by lojies** [comment]
@idealtech-i3dlabs, this param should have a time unit.
You can try `kubectl get nodes --request-timeout=4s`, i tried and it work.

`--request-timeout='0': The length of time to wait before giving up on a single server request. Non-zero values
should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests.`

**Comment by pacoxu** [comment]
@justinsb tried to add a timeout for `cluster-info dump`  in  https://github.com/kubernetes/kubernetes/pull/99107/files.
The PR was reverted in #99450. A command timeout would be added like the PR. I'm not sure if we need add a `--timeout` for `cluster dump`.

**Comment by idealtech-i3dlabs** [comment]
Hmmm. Still doesn't work for me... weird
Just tried on another test environment with 1.20.4 pointing to a non-existing cluster.

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

$ time kubectl get nodes --request-timeout=4s
Unable to connect to the server: dial tcp 172.16.2.34:6443: connect: no route to host

real	0m15.450s
user	0m0.081s
sys	0m0.035s
