### ISSUE TITLE
[sig-node] update client-go to 1.14+ in images

### ISSUE THREAD

**Issue by zshihang** [kubernetes/kubernetes#101285]
#### What happened:

the following images are using old client-go that would not work correctly starting 1.22+ if those images use in-cluster config(mounted service account token) to talk to kube-apiserver:
- k8s.gcr.io/gke-node-termination-handler

#### What you expected to happen:

if the above images use in-cluster config, they should use client-go 1.14+.

xref: https://github.com/kubernetes/kubernetes/issues/75551

/assign @bobbypage 
/cc @liggitt
/sig node
/priority important-soon

**Comment by SergeyKanzhelev** [comment]
notes:

image defined here: https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/blob/master/Dockerfile.build
and referenced here: https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/cluster/gce/addons/node-termination-handler/daemonset.yaml#L49

**Comment by SergeyKanzhelev** [comment]
I think the right fix will be to remove this addon in 1.22 in favor of graceful termination feature: https://github.com/kubernetes/enhancements/issues/2000

**Comment by liggitt** [comment]
> I think the right fix will be to remove this addon in 1.22 in favor of graceful termination feature: [kubernetes/enhancements#2000](https://github.com/kubernetes/enhancements/issues/2000)

Sounds good to me. Who has the ball to do that?

**Comment by ehashman** [comment]
@liggitt: @bobbypage owns graceful termination (and is currently assigned, I will ping).

**Comment by bobbypage** [comment]
> > I think the right fix will be to remove this addon in 1.22 in favor of graceful termination feature: [kubernetes/enhancements#2000](https://github.com/kubernetes/enhancements/issues/2000)
> 
> Sounds good to me. Who has the ball to do that?

@liggitt `k8s.gcr.io/gke-node-termination-handler` is hosted on https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/ 

As mentioned [Graceful Node Shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) (beta in 1.21) replaces the need for that handler so it can be deprecated and removed moving forward. 

I will followup and update the README on the [repo](https://github.com/GoogleCloudPlatform/k8s-node-termination-handler/) remove this [addon](https://github.com/kubernetes/kubernetes/blob/204ff6caeb8229e6d12b54809108e7f32c19502f/cluster/gce/addons/node-termination-handler/daemonset.yaml#L49) from k/k.

**Comment by zshihang** [comment]
k8s.gcr.io/gke-node-termination-handler is removed from the tree.

/close
