### ISSUE TITLE
Change constants CoreDNSImageName

### ISSUE THREAD

**Issue by thdrnsdk** [kubernetes/kubernetes#101300]
#### What happened:

When installing using kubeadm, only the image of coredns has a different depth.
This is very inconvenient when installing using a private registry.

#### What you expected to happen:

$ kubeadm config images list
`
k8s.gcr.io/coredns/coredns:v1.8.0
`

change to

`
k8s.gcr.io/coredns:v1.8.0
`

#### How to reproduce it (as minimally and precisely as possible):

replace constants in

https://github.com/kubernetes/kubernetes/blob/6a7572e4adaa209e09744092a9ac052f31fbeb9f/cmd/kubeadm/app/constants/constants.go#L331

#### Anything else we need to know?:

need to push again to the gcr repository .

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/99321#issuecomment-783649010

> 
> From v1.7.1, [the image promotion is no longer done in the legacy way](https://github.com/kubernetes/k8s.io/pull/1405#issuecomment-725631498)
> 
> v1.8.0 should be available under k8s.gcr.io/coredns/coredns:v1.8.0

**Comment by thdrnsdk** [comment]
The image depth only changes when using coredns images.
In case of building and using private Image Registry, it is strange to have subpath repository level for only coredns.

k8s.gcr.io/kube-apiserver:v1.21.0
k8s.gcr.io/kube-controller-manager:v1.21.0
k8s.gcr.io/kube-scheduler:v1.21.0
k8s.gcr.io/kube-proxy:v1.21.0
k8s.gcr.io/pause:3.4.1
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns/coredns:v1.8.0

**Comment by wangyysde** [comment]
@thdrnsdk  
Yes, I am agree with you. It is very strange that only the path of coredns is /coredns/xxxx ,the others is /xxx. @fabriziopandini @SataQiu  Can we change the  path of coredns to /xxx too?

**Comment by fabriziopandini** [comment]
This is not really up to Kubeadm. 
kubeadm simply adapts to change that happens somewhere else, so changing the constant in kubeadm won't fix the image name; instead, it will make v1.21 clusters to fail.

Please refert to https://github.com/kubernetes-sigs/cluster-api/issues/4463#issuecomment-819208692 for a detailed analysis of available images for CoreDNS; Also, please note that changes to the image name have side effects in other systems as well, so, if possible, I suggest to avoid changing this again...

**Comment by dims** [comment]
+1 to what @fabriziopandini said.

In all honesty, more things will go to the format that coredns is following over time. So we better get used to it.

**Comment by neolit123** [comment]
the depth cannot be changed and you must adapt your local registry.

cc @chrisohaver @rajansandeep 
since the change of path for the image and introduction of `v` created similar complains from users.

/close
