### ISSUE TITLE
client-go: Binary size regression in 1.21+

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#101384]
#### What happened:

I upgraded to client-go 1.21 and our binaries increased:

```
32M -> 35M istio-cni
34M -> 37M istio-cni-repair
32M -> 35M istio-cni-taint
82M -> 91M istioctl
78M -> 88M operator
80M -> 87M pilot-discovery
```

#### What you expected to happen:

Binary sizes do not get bloated, especially when just importing Kubernetes libraries already adds ~30mb prior to this version.

#### How to reproduce it (as minimally and precisely as possible):
Upgrade to 1.21. Example PR where I pulled the numbers https://github.com/istio/istio/pull/32131

#### Anything else we need to know?:

The majority of this seems from `k8s.io/client-go/applyconfigurations`. This is derived from https://github.com/jondot/goweight and https://github.com/loov/goda.

**Comment by howardjohn** [comment]
For reference on the potential impact of this, at our current rate of image pulls of our project this would cost hundreds of thousands of dollars in GCR network traffic costs, and we are of course far from the only importer of Kubernetes libraries. So I think it's fairly important that a library that is central to a large ecosystem is as lean as possible, as it has a major impact on all consumers.

**Comment by dims** [comment]
Looking at what changed between the versions of client-go that @howardjohn mentions:
https://github.com/kubernetes/client-go/compare/v0.20.5...v0.21.0

everything under is brand new:
https://github.com/kubernetes/client-go/tree/master/applyconfigurations

Starting with the commit here:
https://github.com/kubernetes/kubernetes/pull/99759

@howardjohn this is part of the work under this KEP:
https://github.com/kubernetes/enhancements/issues/2155

This is part of the cost of this new feature and not a side effect of some unnecessary dependencies getting dragged in. Will leave this upto @kubernetes/sig-api-machinery-bugs folks to chime in here if i missed or misread something.

**Comment by lavalamp** [comment]
client-go doesn't make any binary size promises.

FWIW, I don't foresee adding another feature of this magnitude probably ever again.

If we're incredibly lucky, go2 will let us phrase the client without (as much) code generation. (although that may not help the binary size.)

@jpbetz can speak to whether these packages should be included if they aren't directly used.

**Comment by jpbetz** [comment]
> client-go doesn't make any binary size promises.
> 
> FWIW, I don't foresee adding another feature of this magnitude probably ever again.
> 
> If we're incredibly lucky, go2 will let us phrase the client without (as much) code generation. (although that may not help the binary size.)
> 
> Joe Betz can speak to whether these packages should be included if they aren't directly used.

`k8s.io/client-go/applyconfigurations` really is needed now that we're supporting server side apply in the client. I don't forsee any other additions like this in the future. See the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2155-clientgo-apply) for more details on what exactly this does.

**Comment by lavalamp** [comment]
Oh, it's absolutely needed and we won't be removing it. But the question is if a binary links some part of client-go, but doesn't happen to use that package, should it really be showing up in binary size?

**Comment by jpbetz** [comment]
> Oh, it's absolutely needed and we won't be removing it. But the question is if a binary links some part of client-go, but doesn't happen to use that package, should it really be showing up in binary size?

Oh right. I'd have to defer to golang experts in this but the newly generated code doesn't do anything tricky, so I wouldn't expect the linker to have any trouble with it.
