### ISSUE TITLE
Allow Node Only expansion of Local Volumes

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#101340]
There are use cases where users want to expand the local volume (may be managed by LVM or something similar), but even though they can edit underlying PV (and expand the underlying device) -  the reported size in pvc.Status keeps reporting older value because in-tree local volumes are non-expandable.

We could make this easier for users by - implementing `NodeExpandableVolumePlugin` interface for local volumes. 

This would allow following steps for local volume expansion:

1. User/admin edits the pvc - requesting new size.
2. Admin expands the underlying device.
2. Admin edits the PV and sets new size.
3. Kubelet will expand the filesystem and update `pvc.Status`

This would at least get the user from impossible territory  to possible.

cc @msau42 @cofyc 

/sig storage

**Comment by trotro** [comment]
Hi @gnufied & @zhanghe9702 any news on this issue ? The related PR seems stalled.

**Comment by gnufied** [comment]
@trotro https://github.com/kubernetes/kubernetes/pull/102886 merged. So this is fixed now.

**Comment by trotro** [comment]
> @trotro https://github.com/kubernetes/kubernetes/pull/102886 merged. So this is fixed now.

Oh right ! I didn't look close enough and thought it was only for directory based volumes.
Thank you.
