### ISSUE TITLE
The traffic is not routed correctly after the network interface on worker node is restarted

### ISSUE THREAD

**Issue by zhanshen8D** [kubernetes/kubernetes#101323]
#### What happened:
We have a statefulset with 2 replicas, on each pod there is Postgres instance. One acts as master while the other acts as replica.
There are 2 services exposed, one is PG master service and the other is PG replica service. Both services are without selector, and there are 2 endpoints sharing the name of it related service.
The IP of the Postgres pod will be patched into endpoints so that the traffic can be routed to the correct pod when accessing the service.
For example, PG master service is corresponding to the endpoint of the same name, and in that endpoint there is ip of the pod running master Postgres instance.

There is another traffic pod which will set up the DB connection to the master Postgres service.
The problem is:
1. The traffic pod(issue DB connections with JDBC) and PG master pod are in the same worker node(let’s call it worker1).
2. The PG replica pod is in another worker(worker2).
3. Run a testing case which is: “Shutdown network interface on worker1, sleep 60s, take up network interface on worker1”
4. Then the previous PG replica pod is promoted to master, and the previous PG master pod is demoted to replica.
5. The traffic pod’s target address is the PG master service name but at that time it connects to the replica pod. Thus the traffic could try to write to a PG in ‘read-only’ mode and test case fails.

The kube-proxy mode is iptables.
We suspect the iptables in kube-proxy doesn’t update the routing information in time. It means the iptables could update the routing information a bit later than the traffic pod establishing the DB connection.

#### What you expected to happen:
The kube-proxy should route the traffic to correct pod.

#### How to reproduce it (as minimally and precisely as possible):
Has been mentioned in "What happened".

#### Anything else we need to know?:
We made a restart of the kube-proxy and the problem hasn't been reproduced since then. That's strange.
So we hope to know the root cause of that.

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"91fb1371fc570cfd3b3052012ce68fdd78b41c07", GitTreeState:"clean", BuildDate:"2020-10-28T08:47:48Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux node-150-132-197-150 4.15.0-118-generic #119~16.04.1-Ubuntu SMP Tue Sep 8 14:54:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
this seems like a request of support, please try:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if you have proof that this is an actual bug in core k8s you can reopen the issue or a new one.

/remove-kind bug
/kind support
/sig network
/close
