### ISSUE TITLE
Why apiserver does not return remainingItemCount when labelSelector or filedSelector is not nil

### ISSUE THREAD

**Issue by Garrybest** [kubernetes/kubernetes#101463]
What happened:
I found remainingItemCount would not return when we use labelSelector or filedSelector to list objects. I can’t understand. Now I need remainingItemCount attribute to know how many objects remained.

Here is the source code.
https://github.com/kubernetes/kubernetes/blob/7e9fe39cd7c3ee67fcc29e6ca0836917c5a4e9e1/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L770-L776

**Comment by liggitt** [comment]
Because the filtering is applied in the kube-apiserver, and knowing the remaining count would require the API server to fully list all items and filter them, which is potentially very expensive.
