### ISSUE TITLE
kubelet won't start after reboot with swap off already

### ISSUE THREAD

**Issue by uxth** [kubernetes/kubernetes#101406]
#### What happened:
server rebooted, kubelet is not started
#### What you expected to happen:
it should started
#### How to reproduce it (as minimally and precisely as possible):
just reboot the server
#### Anything else we need to know?:
The connection to the server 192.168.0.190:6443 was refused - did you specify the right host or port?

[log.txt](https://github.com/kubernetes/kubernetes/files/6363100/log.txt)

#### Environment:
- Kubernetes version (use `kubectl version`):
- Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- it is set up on a local vm.
- OS (e.g: `cat /etc/os-release`):
- NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Kernel (e.g. `uname -a`):
- Linux k8s-master01 4.15.0-142-generic #146-Ubuntu SMP Tue Apr 13 01:11:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by uxth** [comment]
free -m

              total        used        free      shared  buff/cache   available
Mem:           1992         303         920          10         769        1537
Swap:             0           0           0


I think the most common case is that swap is on, so kubelet won't be able to start.
but in my case the swap is already turned off from /etc/fstab.
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/ubuntu-vg/ubuntu-lv during curtin installation
/dev/disk/by-id/dm-uuid-LVM-HwPB2qdBSmBSrzb3Dc47VHJe7k4T4JCAtIfTQYtZhZvTQIm5M3Ll523aAydwDsCp / ext4 defaults 0 0
# /boot was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/a0a091c4-da9b-4fc1-b172-d5ae74642b0f /boot ext4 defaults 0 0
# /swap.img	none	swap	sw	0	0


what could be the reason? how can I solve this?
thanks

**Comment by lunhuijie** [comment]
It looks like there is a problem with the apiserver，mybe the logs of apiserver is useable.

**Comment by uxth** [comment]
What do I need to do to collect the api server log?
