### ISSUE TITLE
Expose `defaults` in k8s.io/api 

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#101468]
#### What would you like to be added:
Defaulting logic (`zz_generated.defaults.go`) to be exported to k8s.io/api.

#### Why is this needed:

Any logic that depends on defaults needs to import kubernetes/kubernetes, which is hard to do/not recommended.

This also leads to confusion where `scheme.Default()` on k8s.io/api types seems like it would work, but it ends up doing nothing.

Example of a project that would benefit from this change: https://github.com/itaysk/kubectl-neat

**Comment by liggitt** [comment]
I'm strongly opposed to exposing this. Conversion and defaulting should generally only be done by the kube-apiserver, and occasionally depend on configuration or feature enablement known only to the API server. 

Taking a dependency on a specific version of a library exporting this capability encourages components outside the kube-apiserver to do this, grow stale in the default logic they embed, and try to apply defaults without knowing the API server features/config.

**Comment by howardjohn** [comment]
That seems reasonable. Feel free to close this

**Comment by liggitt** [comment]
One alternative for https://github.com/itaysk/kubectl-neat in k8s 1.18+ would be to trim fields not owned by the original applier
