### ISSUE TITLE
Pod not scheduling in different az with failure-domain.beta.kubernetes.io/zone  as topologyKey

### ISSUE THREAD

**Issue by uptownaravi** [kubernetes/kubernetes#101459]
#### What happened:
We have noticed an issue using the failure-domain.beta.kubernetes.io/zone as topology key in the 
podAntiAffinity ( requiredDuringSchedulingIgnoredDuringExecution ) 

expected the pods to be scheduled in different availability zones, but they got created in the same az.
although there is a new GA label topology.kubernetes.io/zone the deprecated one should also be supported in v1.17

#### What you expected to happen:
Statefulset pods having the podAntiAffinity ( requiredDuringSchedulingIgnoredDuringExecution )  and topology key as 
failure-domain.beta.kubernetes.io/zone should be scheduled in different availabilty zones.

#### How to reproduce it (as minimally and precisely as possible):
This is a EKS environment using statefulset with ebs volume template.

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: 
Major:"1", Minor:"20", GitVersion:"v1.20.2
Server Version
Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af

- Cloud provider or hardware configuration:
 AWS EKS v1.17
- OS (e.g: `cat /etc/os-release`):
ami:  amazon-eks-node-1.17
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by damemi** [comment]
Hi @uptownaravi, could you please provide the full yaml of the pod definition in question? With any sensitive information removed, of course

**Comment by uptownaravi** [comment]
Hi @damemi 

adding the definition as requested

-------
"kind": "Pod",
    "apiVersion": "v1",
    "metadata": {​
      "name": "stsname-0",
      "generateName": "stsname-",
      "namespace": "namespace-name",
      "selfLink": "/api/v1/namespaces/namespace-name/pods/stsname-0",
      "labels": {​
        "app": "stsname",
        "statefulset.kubernetes.io/pod-name": "stsname-0"
      }​,
      "annotations": {​
       ...      }​,
      "ownerReferences": [
        {​
          "apiVersion": "apps/v1",
          "kind": "StatefulSet",
          "name": "stsname",
          "controller": true,
          "blockOwnerDeletion": true
        }​
      ]
    }​,
    "spec": {​
      "volumes": [
        ...
      ],
      "initContainers": [
        ...
      ],
      "containers": [
        ...
      ],
      "restartPolicy": "Always",
      "terminationGracePeriodSeconds": 10,
      "dnsPolicy": "ClusterFirst",
      "serviceAccountName": "service-account-name",
      "serviceAccount": "service-account-name",
      "shareProcessNamespace": true,
      "securityContext": {​
        "sysctls": [
          {​
            ...
          }​
        ]
      }​,
      "imagePullSecrets": [
        ...
      ],
      "hostname": "stsname-0",
      "subdomain": "stsname",
      "affinity": {​
        "nodeAffinity": {​
          "requiredDuringSchedulingIgnoredDuringExecution": {​
            "nodeSelectorTerms": [
              {​
                "matchExpressions": [
                  {​
                    "key": "key-name",
                    "operator": "In",
                    "values": [
                      "value-of-key"
                    ]
                  }​,
                  {​
                    "key": "failure-domain.beta.kubernetes.io/zone",
                    "operator": "In",
                    "values": [
                      "us-east-1a",
                      "us-east-1b",
                      ...
                    ]
                  }​
                ]
              }​
            ]
          }​
        }​,
        "podAntiAffinity": {​
          "requiredDuringSchedulingIgnoredDuringExecution": [
            {​
              "labelSelector": {​
                "matchExpressions": [
                  {​
                    "key": "app",
                    "operator": "In",
                    "values": [
                      "stsname"
                    ]
                  }​
                ]
              }​,
              "topologyKey": "failure-domain.beta.kubernetes.io/zone"
            }​
          ]
        }​
      }​,
      "schedulerName": "default-scheduler",
      "tolerations": [
        ...
      ],
      "priority": 0,
      "enableServiceLinks": true
    }​,
    "status": {​
      ...
    }​
  }

**Comment by ahg-g** [comment]
can you verify that the nodes actually have the `failure-domain.beta.kubernetes.io/zone` label?
