### ISSUE TITLE
If i limits the CPU cores but Memory for the Pod, the Topomanager will not use the static policy, why? Benefit?

### ISSUE THREAD

**Issue by qingshanyinyin** [kubernetes/kubernetes#101481]
**_First i set the kubelet as bellow:_**
–cpu-manager-policy=static –topology-manager-policy=best-effort

**_Second i create the pod as bellow:_**
![image](https://user-images.githubusercontent.com/35218255/116066852-1963d400-a6bb-11eb-8917-2a16799cbff8.png)
Then i check the cgroup of this container, and find that the  CPU core is bindded to the container. That means that the static-manager works. ( cpu_manager_state as bellow: ) 
![image](https://user-images.githubusercontent.com/35218255/116068152-7f9d2680-a6bc-11eb-9eaa-1036dc34b2bc.png)

_**Third i delete the memory request of the pod as bellow:**_
![image](https://user-images.githubusercontent.com/35218255/116068425-d1de4780-a6bc-11eb-98d3-86a8776bab68.png)
Then i find that this pod use the shared CUP cores.

Fourth i read the code of kubelet, the key code of this is bellow:
![image](https://user-images.githubusercontent.com/35218255/116068664-110c9880-a6bd-11eb-9573-3b49bbf2ac48.png)
If i do not set the memory, the k8s think the pod is burstable. so the cpu-manager-policy=static will not work and use shared CPU cores.

**Is the Fourth  analysis correct？
Why? 
If the k8s is designed like this（as third Scenes）, what is the benefit of it?**

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
