### ISSUE TITLE
--log-file only works if --logtostderr=false 

### ISSUE THREAD

**Issue by brsolomon-deloitte** [kubernetes/kubernetes#101425]
As originally filed at https://github.com/kubernetes/kubeadm/issues/2455.

## Is this a BUG REPORT or FEATURE REQUEST?

BUG REPORT

## Description

Passing `--log-file` to both `kubeadm init` and `kubeadm join` never actually creates or writes a log file whatever the level of `--v` and regardless of whether the enclosing directory exists. **`--log-file` _only_ works if the undocumented `--logtostderr=false` is passed as well.**

## Versions

**kubeadm version** : `kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:30:03Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}`

**Environment**:
- **Kubernetes version**: `Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}`
- **Cloud provider or hardware configuration**: AWS
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5
- **Kernel** (e.g. `uname -a`): 5.4.0

## What happened?

```bash
$ ls -la /var/log/kubeadm/
total 8
drwxr-xr-x  2 root root   4096 Apr 21 22:48 .
drwxrwxr-x 12 root syslog 4096 Apr 21 22:51 ..
```

## What you expected to happen?

A log file to be produced at `/var/log/kubeadm/join-*.log`

## How to reproduce it (as minimally and precisely as possible)?

In this example `--log-file` fails to do anything when used with `kubeadm join` to join a node to the control plane. However, this issue persists across different subcommands.

```bash
kubeadm join xxxx.elb.us-xx-xx.amazonaws.com:6443 --token xxx.xxx \
        --discovery-token-ca-cert-hash sha256:xxxx \
        --control-plane --certificate-key xxxx \
        --log-file /var/log/kubeadm/join-$(date +%s).log --one-output --v 9
```

**Comment by CaoDonghui123** [comment]
/assign
I will try to reproduce it first
