### ISSUE TITLE
Inconsistent behavior while trying to access service by External IP from within a cluster

### ISSUE THREAD

**Issue by sknaumov** [kubernetes/kubernetes#101491]
#### What happened:
I have 2 services, and the first one (let's call it client) internally uses the other to operate, and issues HTTP request to External-IP of the second service. Sometimes response content is expected, but sometimes, say, after client's pod restart, I receive just empty response as if request is filtered by iptables. The same is if I manually use curl - from some pods it consistently works, from some - doesn't and nmap from these pods to desired external IP shows that 80/tcp is filtered. But everything could change again after client pod restart.

#### What you expected to happen:
Consistency - either it works or not.

#### How to reproduce it (as minimally and precisely as possible):
I'm new to kubernetes and work with pre-existing cluster(

#### Anything else we need to know?:
Don't know if it is significant, but both services (client and server) use LoadBalancer and have External-IP.

#### Environment:
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

So the question is, is it OK to use External-IP from within a cluster?

**Comment by uablrek** [comment]
> So the question is, is it OK to use External-IP from within a cluster?

Short answer; sometimes.

The beavior is not consistent between environments. Please complete the "Environment" section of the issue template. E.g. the used cloud-provider.

Also what kind of "external-ip"? LoadBalancer? Include the service manifest would help.

**Comment by uablrek** [comment]
Is the service `externalTrafficPolicy:local`? Please check https://github.com/kubernetes/kubernetes/issues/93456

**Comment by thockin** [comment]
Ping on this  -  is it still a problem @sknaumov ?  If not, we'll close this.

**Comment by caseydavenport** [comment]
Looks like we're still missing important environmental information which makes it impossible to triage this one. In general, I'd recommend against using ExternalIP as a means to access services from within the cluster unless there's a reason to do so.

Going to close this for now but we can re-open if we get more information! 

/close
