### ISSUE TITLE
kube-scheduler crashes and restarts with panics in DefaultPreemption plugin

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#101548]
#### What happened:

Kubernetes 1.19 (confirmed with 1.19.7 and 1.19.10)

kube-scheduler crashes and restarts with the following errors in `default_preemption.go`. 

1. **panic: runtime error: index out of range [0] with length 0** 

The problem code is line 389.  When `victims` is nil or `victims.Pods` is empty, the error happens.  If we skip `GetPodPriority ` when it's nil or empty, the error is gone. 
```
387         victims := nodesToVictims[node]
388         // highestPodPriority is the highest priority among the victims on this node.
389         highestPodPriority := podutil.GetPodPriority(victims.Pods[0])
```

```
panic: runtime error: index out of range [0] with length 0 [recovered]
panic: runtime error: index out of range [0] with length 0
goroutine 1406 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1c9fde0, 0xc00748cf48)
 /usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.pickOneNodeForPreemption(0xc007e3dbc0, 0x4, 0x4)
/Users/yuanchen/projects/aci/go/kubescheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:389 +0xd2c
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.SelectCandidate(0xc0086e0840, 0x4, 0x4, 0xc008235800, 0x2068138)
/Users/yuanchen/projects/aci/go/kubescheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:331 +0x85
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).preempt(0xc000ac4b80, 0x20677d0, 0xc005849540, 0xc0085616e0, 0xc008235800, 0xc008561710, 0x2d80750, 0xc00820a8c0, 0x7f0937ef47d8, 0x30)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:135 +0x4bd
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).PostFilter(0xc000ac4b80, 0x20677d0, 0xc005849540, 0xc0085616e0, 0xc0071543a8, 0xc008561710, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:83 +0xf1
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runPostFilterPlugin(0xc0002fd380, 0x20677d0, 0xc005849540, 0x7f0937a84040, 0xc000ac4b80, 0xc0085616e0, 0xc0071543a8, 0xc008561710, 0xc0084f3ab0, 0x5f5e100)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/runtime/framework.go:557 +0x87
```

2. **panic: runtime error: invalid memory address or nil poster dereference**

` 452   latestStartTime := util.GetEarliestPodStartTime(nodesToVictims[minNodes2[0]])`

The problem is `nodesToVictims[minNodes2[0]]` does not exist and returns nil sometimes. Simply skipping it won't solve the problem.  The scheduler will reach either line 456 or 341. 

```
456        klog.Errorf("earliestStartTime is nil for node %s. Should not reach here.", minNodes2[0])
```

`341     klog.Errorf("None candidate can be picked from %v.", candidates)`

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15706d7]
goroutine 1385 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x1b448c0, 0x2d281b0)
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/scheduler/util.GetEarliestPodStartTime(0x0, 0xc004d4d9e0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/util/utils.go:56 +0x37
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.pickOneNodeForPreemption(0xc004d4d9e0, 0x4, 0x4)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:452+0x7a9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.SelectCandidate(0xc0066e5180, 0x4, 0x4, 0xc0062f5000, 0x2068138)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:331 +0x85
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).preempt(0xc000f9e880, 0x20677d0, 0xc004fa3340, 0xc0061b5290, 0xc0062f5000, 0xc0061b52c0, 0x2d80750, 0xc00603fc40, 0x7f6bcbc363f8, 0x30)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:135 +0x4bd
: k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).PostFilter(0xc000f9e880, 0x20677d0, 0xc004fa3340, 0xc0061b5290, 0xc002523ac8, 0xc0061b52c0, 0x0, 0x0)
```

#### What you expected to happen:

The scheduler works without failures.

#### How to reproduce it (as minimally and precisely as possible):

When there are preemptions in a cluster. 

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.10 or v1.19.7
- Cloud provider or hardware configuration: bare metal 
- OS (e.g: `cat /etc/os-release`): centos 7 
- Kernel (e.g. `uname -a`):   Linux 5.4.77-7.el7pie #1 SMP Sat Nov 21 01:16:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Huang-Wei** [comment]
@yuanchen8911 Are you running the vanilla scheduler? or a customized one that leverages the utilities in default_preemption.go?

**Comment by yuanchen8911** [comment]
It's a custom scheduler with some internal out-of-tree plugins, but it doesn't have any custom postFilter plugins. 

Which utility functions are you referring to?  Thanks.

**Comment by ahg-g** [comment]
are those custom plugins filter plugins? do they maintain state? 

If yes, then one hypothesis is that those custom filters filter the node in the filter phase, but not when executed in the preemption phase, and so this will result in a candidate node with no victims?

**Comment by yuanchen8911** [comment]
Yes, it includes filter plugins and uses cycle state.

**Comment by ahg-g** [comment]
you need to make sure that those filter plugins play nicely when executed again in the preemption phase.

**Comment by yuanchen8911** [comment]
@ahg-g Thanks  What do you mean by performing filter in the preemption phase? would you mind elaborating it a little?

**Comment by yuanchen8911** [comment]
What additional logic is needed to handle the preemption case?

**Comment by ahg-g** [comment]
in the preemption phase we run the filters again to check if removing lower priority pods make the node schedulable: https://github.com/kubernetes/kubernetes/blob/d9839a30c78c55f4cda8edb8effa249e9bb42884/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L543

we later add them one by one to reduce the set of victim pods to the absolute minimum: https://github.com/kubernetes/kubernetes/blob/d9839a30c78c55f4cda8edb8effa249e9bb42884/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L558

My hypothesis is that some how your filter is returns success when adding all the pods back, and so you end up with zero victims and a candidate node. This shouldn't happen because if the pod fits the node without removing any victims, then we shouldn't be running preemption in the first place. So my theory is that the custom filter is returning false when run in the filter phase, but returns true when executed in the preemption phase.

**Comment by yuanchen8911** [comment]
Disabled the filter plugin, but still see the same issues.

**Comment by ahg-g** [comment]
are you able to change the scheduler code and run the test again? I can send a patch tomorrow to add some debugging messages to help us root cause the issue.

**Comment by yuanchen8911** [comment]
yes, thanks a lot!  really appreciate it!

**Comment by yuanchen8911** [comment]
@ahg-g  You are right.  We still use a deprecated Predicate extender, which causes the problem. After disabling it, it's working fine.  It used to work with 1.18 though. We are retiring it.  Thank you so much!!!

**Comment by yuanchen8911** [comment]
If the test cases can help debug scheduler extender Webhook (Predicate) too, I'd like to try it. Thanks again!

**Comment by yuanchen8911** [comment]
How can we improve the preemption logic to prevent such thing happening?

**Comment by ahg-g** [comment]
for starter, we should check the list len, the scheduler should not panic in all cases.

Other than that, I think we need to clearly document what the preemption logic does (that it executes the prefilter extensions points and the filter plugins multiple times) and the expectations from filter plugins (that they may get executed more than once in the same cycle)

**Comment by yuanchen8911** [comment]
I can file a PR for additional checks.

**Comment by Huang-Wei** [comment]
> We still use a deprecated Predicate extender, which causes the problem.

Is it a **predicate** extender or **preemption** extender? If it's a predicate extender, I don't quite think we found the root cause - b/c predicate extenders are not invoked during preemption (https://github.com/kubernetes/kubernetes/issues/86942#issuecomment-650436328).

It makes more sense if it's a preemption extender - if the preemption extender mutates the `candidates` to make it invalid. If it's the case, could you verify it by adding debug info before and after L157 to check the validness of `candidates`?

https://github.com/kubernetes/kubernetes/blob/c6e65079c70100edc647e3ccfdfa9ead1fe71818/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L157

**Comment by Huang-Wei** [comment]
> the scheduler should not panic in all cases.

That's always true :)

**Comment by yuanchen8911** [comment]
filed a PR to mitigate it. https://github.com/kubernetes/kubernetes/pull/101560

**Comment by yuanchen8911** [comment]
It's a predicate extender. I'll debug it more. 

> > We still use a deprecated Predicate extender, which causes the problem.
> 
> 
> 
> Is it a **predicate** extender or **preemption** extender? If it's a predicate extender, I don't quite think we found the root cause - b/c predicate extenders are not invoked during preemption (https://github.com/kubernetes/kubernetes/issues/86942#issuecomment-650436328).
> 
> 
> 
> It makes more sense if it's a preemption extender - if the preemption extender mutates the `candidates` to make it invalid. If it's the case, could you verify it by adding debug info before and after L157 to check the validness of `candidates`?
> 
> 
> 
> https://github.com/kubernetes/kubernetes/blob/c6e65079c70100edc647e3ccfdfa9ead1fe71818/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L157

**Comment by yuanchen8911** [comment]
Added some debug info.  after `FindCandidates` and `CallExtenders`.  Here's the result.

`FindCandidates` returned 4 candidates, but one of candidates (`candidates[3]`) has zero pod. The candidate happened to be the best candidate and hence caused the "`index out of range`" error. It should have nothing to do with `CallExtenders` as our extender doesn't support Preemption. Disabling it may change pod placements/candidates selection and bypassed the error. It's like a coincidence.  

A simple fix is to check if `candidate.Victims.Pods` is empty. if it is, do not add the node to candidates.

```
func candidatesToVictimsMap(candidates []Candidate) map[string]*extenderv1.Victims {
329     m := make(map[string]*extenderv1.Victims)
330     for _, c := range candidates {
332         // if len(c.Victims().Pods) != 0 {
333         m[c.Name()] = c.Victims()
334         // }
335     }
336     return m
337 }
```

Alternatively, a change to `dryRunPreemption` may work too. 

```
258         pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
259         if fits && len(pods) != 0 {
```

Here is the log with debug info.
```
12360 default_preemption.go:124] After FindCandidates
default_preemption.go:125] candidates length is  4
default_preemption.go:127] candidates[0].Name = knode0019  victims Pods  = 1
default_preemption.go:127] candidates[1].Name = knode0016   victims Pods  = 1
default_preemption.go:127] candidates[2].Name = knode0024  victims Pods  = 1
default_preemption.go:127] candidates[3].Name = knode0046  victims Pods = 0
default_preemption.go:137] After CallExtenders
default_preemption.go:138] candidates length is  4
default_preemption.go:140] candidates[0].Name = knode0019  victims Pods  = 1
default_preemption.go:140] candidates[1].Name = knode0016   victims Pods  = 1
default_preemption.go:140] candidates[2].Name = knode0024  victims Pods  = 1
default_preemption.go:140] candidates[3].Name = knode0046  victims Pods = 0
runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1ca0de0, 0xc009afa5a0)
 /Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x1ca0de0, 0xc009afa5a0)
/usr/local/Cellar/go/1.16.2/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.pickOneNodeForPreemption(0xc005450f30, 0x4, 0x4)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:407 +0xcac
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.SelectCandidate(0xc007276100, 0x4, 0x4, 0x0, 0x0)
 /Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:349 +0x85
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).preempt(0xc000ddbfa0, 0x2068990, 0xc006654d80, 0xc008f9e600, 0xc008312800, 0xc008f9eb70, 0x2d82750, 0xc000fda340, 0x7f6faeb12760, 0x30)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:150 +0xbd9
k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption.(*DefaultPreemption).PostFilter(0xc000ddbfa0, 0x2068990, 0xc006654d80, 0xc008f9e600, 0xc006aa4000, 0xc008f9eb70, 0x0, 0x0)
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/kubernetes/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go:83 +0xf1
k8s.io/kubernetes/pkg/scheduler/framework/runtime.(*frameworkImpl).runPostFilterPlugin(0xc0001b1040, 0x2068990, 0xc006654d80, 0x7f6faf522238, 0xc000ddbfa0, 0xc008f9e600, 0xc006aa4000, 0xc008f9eb70, 0xc00198fab0, 0x5f5e100)
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
/Users/yuanchen/projects/aci/go/kube-scheduler/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x11b
kube-scheduler.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Unit kube-scheduler.service entered failed state.
kube-scheduler.service failed.
kube-scheduler.service holdoff time over, scheduling restart.
```

**Comment by Huang-Wei** [comment]
> Alternatively, a change to `dryRunPreemption` may work too.
> 
> ```
> 258         pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
> 259         if fits && len(pods) != 0 {
> ```

This looks more promising.

---

Back to digging into the root cause, it seems `selectVictimsOnNode` returns an empty `pods` but with `fits=true`. So that implies firstly we have a non-nil [potentialVictims](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L533-L535), and then in [filterPodsWithPDBViolation](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L556), the `potentialVictims` is separated into two list: violatingVictims and nonViolatingVictims. Finally the two victims list are tried one by one to run [reprievePod](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L557). It looks like `reprievePod` returns {fits=true, nil error} **for every victim**, which is quite abnormal. I think it's problematic that every pod is retrievable and in which we can debug into.

**Comment by yuanchen8911** [comment]
> > Alternatively, a change to `dryRunPreemption` may work too.
> > ```
> > 258         pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
> > 259         if fits && len(pods) != 0 {
> > ```
> 
> This looks more promising.
> 
> Back to digging into the root cause, it seems `selectVictimsOnNode` returns an empty `pods` but with `fits=true`. So that implies firstly we have a non-nil [potentialVictims](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L533-L535), and then in [filterPodsWithPDBViolation](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L556), the `potentialVictims` is separated into two list: violatingVictims and nonViolatingVictims. Finally the two victims list are tried one by one to run [reprievePod](https://github.com/kubernetes/kubernetes/blob/98d5dc5d36d34a7ee13368a7893dcb400ec4e566/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L557). It looks like `reprievePod` returns {fits=true, nil error} **for every victim**, which is quite abnormal. I think it's problematic that every pod is retrievable and in which we can debug into.

Yes, `selectVictimOnNode` should not return empty pod and fit==true in the first place, but it's hard to locate the problematic code.

**Comment by yuanchen8911** [comment]
The following code in `CallExtenters` looks questionable to me. if `victimsMap` is empty, should the function return nil, nil? 
 ```
 victimsMap := candidatesToVictimsMap(candidates)
    if len(victimsMap) == 0 {
        return candidates, nil
    }
```

Also,  if `!extender.SupportsPreemption() || !extender.IsInterested(pod)` is true for all extenders, the loop won't do anything and  candidates will remain the same. Why do we bother creating a new candidates in this case?

**Comment by yuanchen8911** [comment]
> > Alternatively, a change to `dryRunPreemption` may work too.
> > ```
> > 258         pods, numPDBViolations, fits := selectVictimsOnNode(ctx, fh, stateCopy, pod, nodeInfoCopy, pdbs)
> > 259         if fits && len(pods) != 0 {
> > ```
> 
> This looks more promising.

It can prevent `FindCandidates` from returning candidates with empty pods, but what about `CalleExtenders`?  It's possible to add nodes without victim pods to candidates if `nodeNameToVictims` returned by `ProcessPreemption` has such nodes.
`nodeNameToVictims, err := extender.ProcessPreemption(pod, victimsMap, nodeLister)`

**Comment by yuanchen8911** [comment]
Updated the PR based on the finding and discussions.  https://github.com/kubernetes/kubernetes/pull/101560

**Comment by Huang-Wei** [comment]
> Why do we bother creating a new candidates later? Can it just return candidates?

Yes, we can use a flag to mark if all extenders don't support preemption. If yes, simply return the candidates.

**Comment by Huang-Wei** [comment]
> It's possible to add nodes without victim pods to candidates if `nodeNameToVictims` returned by `ProcessPreemption` has such nodes.

Technically this can exist due to faulty extender implementation. If we really want to guard it, instead of logging the error and continue, I'm more inclined to return the error immediately as this is a fatal error - the victimsMap cannot be used either for latter extender or further preemptor nominating.

**Comment by yuanchen8911** [comment]
@Huang-Wei  Is my understanding correct? 

In `CallExtenters`, if victimsMap is empty, should it return `nil, nil` instead of `candidates, nil`?

```
victimsMap := candidatesToVictimsMap(candidates)
   if len(victimsMap) == 0 {
       return candidates, nil
   }
```

**Comment by Huang-Wei** [comment]
The only case victimsMap can be empty is empty candidates, and so return either doesn't quite matter, right?

**Comment by yuanchen8911** [comment]
> The only case victimsMap can be empty is empty candidates, and so return either doesn't quite matter, right?
You are right.

**Comment by yuanchen8911** [comment]
> > It's possible to add nodes without victim pods to candidates if `nodeNameToVictims` returned by `ProcessPreemption` has such nodes.
> 
> Technically this can exist due to faulty extender implementation. If we really want to guard it, instead of logging the error and continue, I'm more inclined to return the error immediately as this is a fatal error - the victimsMap cannot be used either for latter extender or further preemptor nominating.

As long as one extender returns an invalid victimsMap (with empty pods), `CallExtender`s returns an error immediately? 

What about `selectVictimsOnNode`? Should it return an error immediately if it returns` status.IsSuccess() `with empty pods?

**Comment by Huang-Wei** [comment]
> As long as one extender returns an invalid victimsMap (with empty pods), `CallExtender`s returns an error immediately?

I think so. Because the result it returned is faulty, and we don't want to continue based on it

> What about `selectVictimsOnNode`? Should it return an error immediately if it returns`status.IsSuccess()`with empty pods?

The same. We may don't want to continue the scheduling cycle based on faulty result.
