### ISSUE TITLE
Deprecate and Remove apiserver.k8s.io/v1[alpha|beta]1 Versions 

### ISSUE THREAD

**Issue by carlory** [kubernetes/kubernetes#101564]
#### Why is this needed:

All the supported resources with `apiserver.config.k8s.io/v1`,`apiserver.k8s.io/v1alpha1` and `apiserver.k8s.io/v1beta1`:

- `version=v1alpha1, kind=AdmissionConfiguration`  was added in v1.6 and promoted to GA in v1.17.  ref #85098
- `version=v1alpha1, kind=EgressSelectorConfiguration` was added in 1.16 and promoted to Beta in v1.18. ref #88502

The `v1.21` was released, however, the v1alpha1 versions of the API are still not deprecated.

- https://github.com/kubernetes/apiserver/tree/master/pkg/apis/apiserver/v1alpha1

This requires:

- [ ] deprecate `apiserver.config.k8s.io/v1alpha1` 
- [ ] update [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1281-network-proxy#graduation-criteria) and promoted `EgressSelectorConfiguration ` to GA
- [ ] deprecate `apiserver.config.k8s.io/v1beta1` 
- [ ] update website docs
- [ ] remove apiserver.config.k8s.io/v1[alpha|beta]1 Versions 

/kind deprecation
/kind cleanup
/kind api-change
/assign

**Comment by Git-Jiro** [comment]
Hi!
I would like to work on this issue, but I have not yet found the correct documentation how to deprecate an API by myself.
Can you point me to the correct docs or an example PR where another API got deprecated?

**Comment by Git-Jiro** [comment]
I found this document: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md
But it only seems to describe how to upgrade an API and does not mention deprecation.
