### ISSUE TITLE
Userspace kube-proxy 1.21.0 does not work on Windows

### ISSUE THREAD

**Issue by antoninbas** [kubernetes/kubernetes#101500]
#### What happened:

When using the latest version of the userspace kube-proxy (v1.21.0) on Windows, ClusterIP load-balancing will not work.

Trying to curl a Service (in this case the Kubernetes Service) directly from a Windows Node running userspace kube-proxy will give you this:
```powershell
PS C:\k\antrea> curl.exe -k -vvI https://30.0.0.1:443
* Rebuilt URL to: https://30.0.0.1:443/
*   Trying 30.0.0.1...
* TCP_NODELAY set
* Connected to 30.0.0.1 (30.0.0.1) port 443 (#0)
* schannel: SSL/TLS connection with 30.0.0.1 port 443 (step 1/3)
* schannel: disabled server certificate revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
* schannel: using IP address, SNI is not supported by OS.
* schannel: sending initial handshake data: sending 147 bytes...
* schannel: sent initial handshake data: sent 147 bytes
* schannel: SSL/TLS connection with 30.0.0.1 port 443 (step 2/3)
* schannel: failed to receive handshake, SSL/TLS connection failed
* Closing connection 0
* schannel: shutting down SSL/TLS connection with 30.0.0.1 port 443
* Send failure: Connection was aborted
* schannel: failed to send close msg: Failed sending data to the peer (bytes written: -1)
* schannel: clear security context handle
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
```

If you look at the kube-proxy logs, you may see logs such as this one:
```
I0422 04:14:20.097896   10132 proxier.go:245] "Proxying for service" servicePortPortalName="kube-system/antrea::30.0.101.108" addr="30.0.101.108:443" protocol=TCP
I0422 04:14:21.095778   10132 proxysocket.go:179] Accepted TCP connection from 30.0.0.1:52046 to 30.0.0.1:443
E0422 04:14:21.095778   10132 proxysocket.go:136] Couldn't find an endpoint for default/kubernetes:https:30.0.0.1: missing endpoints
E0422 04:14:21.095778   10132 proxysocket.go:182] Failed to connect to balancer: missing endpoints
```

#### What you expected to happen:

Since there is an Endpoint, kube-proxy should load-balance the connection to it.

#### How to reproduce it (as minimally and precisely as possible):

1) You need a K8s v1.21 cluster with at least one Windows Node. If you want to follow these instructions, the container runtime on the Windows Node should be Docker, not containerd.

2) You need to meet the conditions to run userspace kube-proxy: you should create a network adapter called "vEthernet (HNS Internal NIC)" to which kube-proxy will assign ClusterIP addresses. You may want to use this script: https://github.com/vmware-tanzu/antrea/blob/v1.0.0/hack/windows/Prepare-ServiceInterface.ps1.

3) Deploy userspace kube-proxy on Windows Nodes using a DaemonSet and rancher wins; you can apply this yaml: https://gist.githubusercontent.com/antoninbas/74ee2f2c6153ec94b078fb0001d8ddbb/raw/251e07fc0f90c1a4cd51c635f10c35a79ee56fdf/kube-proxy-windows.yml. This is a modified version of the manifest published by https://github.com/kubernetes-sigs/sig-windows-tools. Note that we use hostNetwork Pods, hence the requirement for the Docker container runtime. As an alternative, you can also run kube-proxy.exe manually.

#### Anything else we need to know?:

I believe that the root cause for this is because the `WindowsEndpointSliceProxying` feature gate was graduated to Beta in v1.21, and it seems that it breaks the userspace kube-proxy backend.

* reverting to an older version of kube-proxy (v1.20) works just fine
* updating the `run-script.ps1` script to perform the following config change also solves the issue:
   ```
   yq w -i /host/var/lib/kube-proxy/config.conf featureGates.WindowsEndpointSliceProxying false
   ```

This issue was first reported in the Antrea project (https://github.com/vmware-tanzu/antrea/issues/2120), which currently uses userspace kube-proxy on Windows.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.0
- Cloud provider or hardware configuration: AWS EC2, using kubeadm v1.21 to deploy the cluster
- OS: Windows Server 2019

**Comment by danwinship** [comment]
> I believe that the root cause for this is because the `WindowsEndpointSliceProxying` feature gate was graduated to Beta in v1.21, and it seems that it breaks the userspace kube-proxy backend.

This was fixed in master by https://github.com/kubernetes/kubernetes/pull/100913 which is being cherry-picked to 1.21 in https://github.com/kubernetes/kubernetes/pull/101504

**Comment by antoninbas** [comment]
Thanks @danwinship. I think we can mark this issue as a duplicate of https://github.com/kubernetes/kubernetes/issues/100880 and close it.
