### ISSUE TITLE
Pod resources reports no ID for the NUMA node 0

### ISSUE THREAD

**Issue by cynepco3hahue** [kubernetes/kubernetes#101522]
#### What happened:

During access to pod resources API, it reports devices from NUMA node 0 without NUMA ID. 
For example

The device from NUMA node 0
```
..., "topology":{"nodes":[{}]}
```
The device from NUMA node 1
```
..., "topology":{"nodes":[{"ID":1}]}
```

#### What you expected to happen:

Topology for the device on the NUMA node 0 should be reported correctly
```
..., "topology":{"nodes":[{"ID":0}]}
```

#### How to reproduce it (as minimally and precisely as possible):

1. Be sure that you have configured some device plugin((GPU, SR-IOV)) and the node has some device on the NUMA node 0(GPU, SR-IOV)
2. Create the pod with the above node selector and that requests the device.
3. Under the node, run a simple go binary that will get container resources via pod resources API
```
package main

import (
	"context"
	"encoding/json"
	"os"
	"time"

	kubeletpodresourcesv1 "k8s.io/kubelet/pkg/apis/podresources/v1"
	"k8s.io/kubernetes/pkg/kubelet/apis/podresources"
)

const (
	defaultSocketPath          = "unix:///var/lib/kubelet/pod-resources/kubelet.sock"
	defaultPodResourcesTimeout = 10 * time.Second
	defaultPodResourcesMaxSize = 1024 * 1024 * 16 // 16 Mb
)

func main() {
	cli, conn, err := podresources.GetV1Client(defaultSocketPath, defaultPodResourcesTimeout, defaultPodResourcesMaxSize)
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	resp, err := cli.List(context.TODO(), &kubeletpodresourcesv1.ListPodResourcesRequest{})
	if err != nil {
		panic(err)
	}

	json.NewEncoder(os.Stdout).Encode(resp)
}
```
4. Check the above pod resources.

#### Anything else we need to know?:

The problem happens because of the topology presentation,
```
// Topology describes hardware topology of the resource
message TopologyInfo {
    repeated NUMANode nodes = 1;
}
// NUMA representation of NUMA node
message NUMANode {
    int64 ID = 1;
}
```
Because ID represented by int64 and the default value for int64 is 0, it ignored during serialization.
From proto3 documentation:
```
Note that for scalar message fields, once a message is parsed there's no way of telling whether a field was explicitly set to the default value (for example whether a boolean was set to false) or just not set at all: you should bear this in mind when defining your message types. For example, don't have a boolean that switches on some behavior when set to false if you don't want that behavior to also happen by default. Also note that if a scalar message field is set to its default, the value will not be serialized on the wire.
```

Possible solutions will be:
- represent ID as a string
- do not use nested struct and just have
```
// Topology describes hardware topology of the resource
message TopologyInfo {
    repeated int64 nodes  = 1;
}
```

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by fromanirh** [comment]
I wonder if device plugins have the same issue; additionally: does the go de-serialization do the right thing? IOW, is the value of the go structs initialized to the right value?

The podresources API - most notably the relevant types - are already stable now, so change them is hard.

**Comment by cynepco3hahue** [comment]
In the end, it was a problem with the JSON serialization, the pod resource API returns all relevant data, but some data missed during the encoding.
