### ISSUE TITLE
remove a possible panic from a deferred function in test/e2e/resize_nodes.go

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#10157]
Failf in a deferred function may cause a double-panic when the deferred function was run after panicking.

The problem exists for reverting iptables filter and may be in other places.

This should be cleaned up. It would also be good to review other e2e tests where this may occur.

cc @lavalamp, @quinton-hoole

**Comment by kargakis** [comment]
Shouldnt be an issue anymore
