### ISSUE TITLE
conversion-gen is broken in 1.20 and 1.21 release

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#101567]
#### What happened:
conversion-gen tool is broken in 1.20 and 1.21 release. This is blocking us and projects like [cert-manager](https://github.com/jetstack/cert-manager/pull/3926) from migrating to the latest k8s tool chain.  

As for context, everything was ok in k8s 1.18. In k8s 1.18.9, the auto generated code will look like the following:

![resource-metadata-zz_generated-conversion-go-at-master-·-kmodules-resource-metadata](https://user-images.githubusercontent.com/94814/116364174-c4a68300-a7b8-11eb-895b-ad4e73f7076a.png)

In k8s 1.20 and 1.21, the auto generated code look like the following:

![Use-k8s-1-21-0-tool-chain-by-tamalsaha-·-Pull-Request-104-·-kmodules-resource-metadata](https://user-images.githubusercontent.com/94814/116364307-ec95e680-a7b8-11eb-9463-7a91ec6df840.png)

This is obviously incorrect, since the k8s.io/apiextensions-apiserver package does have an auto generated conversion for these types:

![Screenshot from 2021-04-28 00-31-57](https://user-images.githubusercontent.com/94814/116364644-4696ac00-a7b9-11eb-821b-0dd26c706c0e.png)

Now, digging into the code of `conversion-gen` I see that the only way `conversion-gen` tool can know about the existence of this method will be that it can be found in the `manual_conversions` map.

ref: https://github.com/kubernetes/code-generator/blob/v0.21.0/cmd/conversion-gen/generators/conversion.go#L1053-L1078

![Screenshot-from-2021-04-28-00-35-06](https://user-images.githubusercontent.com/94814/116365129-cd4b8900-a7b9-11eb-961d-ca5956d94aa7.png)

First I thought that I needed to pass the `--extra-dirs k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1` flag to `conversion-gen` tool so that those files are parsed for conversion methods. But that did not fix it.

Now, further digging I found that the reason the auto-generated `https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1/zz_generated.conversion.go` file is not parsed by the Go `Builder` in `conversion-gen` tool because the auto generated file has the build tag `// +build !ignore_autogenerated` and the Go source parser is configured with `ignore_autogenerated` build tag.

ref: https://github.com/kubernetes/gengo/blob/master/args/args.go#L132-L138

As a result, the auto generated (files with zz_ prefix) are never parsed and we get that `compileErrorOnMissingConversion()` error.

**Proposed Solution:**

In my view, the main problem here is that the same variable `g.GeneratedBuildTag` variable is used to add the build tag to the generated zz_conversion.go file and to parse existing auto generated conversion files. So, I was able to get this fixed using the following approach:

(1) Use separate flags for adding build tag to the generated conversion file and for importing/parsing existing generated conversion files. Here is my pr: https://github.com/kubernetes/gengo/pull/200

I initialize them to the same default value so that the behavior of the code generators other than `conversion-gen` remains unchanged. But I also added a new `--import-tag` flag for the new `ImportBuildTag` .

(2) Now, in the `conversion-gen` code, I set the `ImportBuildTag` to empty string so that by default it parses all the generated conversion functions from the `--extra-dirs` and `--peer-dirs`. 

pr: https://github.com/kubernetes/kubernetes/pull/101568

If users need old behavior for some reason, they can set the `--import-tag=ignore_autogenerated` to avoid parsing the existing generated conversion files.

**Testing Fix**

If you want to test the fix, you need to use my forked `conversion-gen` binary.

```
replace k8s.io/code-generator => github.com/kmodules/code-generator v0.21.1-rc.0.0.20210428003838-7eafae069eb0

replace k8s.io/gengo => github.com/kmodules/gengo v0.0.0-20210428002657-a8850da697c2
```

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by dims** [comment]
cc @palnabarun @nikhita

**Comment by liggitt** [comment]
cc @wojtek-t

likely related to https://github.com/kubernetes/kubernetes/pull/90018 in 1.19, which intentionally removed the fallback to  reflect-based conversion, because it is not known to be correct and masks conversion bugs

based on what was generated previously, is it possible you weren't actually picking up the generated conversions before and were using the reflective conversion path?

**Comment by tamalsaha** [comment]
>  is it possible you weren't actually picking up the generated conversions before and were using the reflective conversion path?

Yes. It was using reflective conversions. As you can see here with k8s 1.18.9

https://github.com/kmodules/resource-metadata/blob/78a10662e33585c6b06d7e0c07c8c70e111ab4d3/apis/meta/v1alpha1/zz_generated.conversion.go#L1140-L1149
