### ISSUE TITLE
BackoffLimit does not work for pods in Jobs (Kubernetes 1.19)

### ISSUE THREAD

**Issue by kolomenkin** [kubernetes/kubernetes#101584]
#### What happened:

1. I deployed CronJob with non-existing docker image,
2. Job was created in time, Pod was created and got pull problems
3. Pod stay in the state "ImagePullBackOff" for 10 and more hours
4. If I deploy new version of CronJob with correct docker image tag it will never start.

#### What you expected to happen:

I expect Pod to use default BackoffLimit like in documentation:
Default value = 6
Delays = 10sec, 20sec, 40sec, 80 sec, 160 sec and 320 sec
Total delay is less than 12 minutes.

I expect Pod will fail to start in about 12 minutes after it was created.
With "restartPolicy: Never" I expect Job will finish after Pod will fail (in 12 minutes).
And I expect scheduler will create a new job from updated template when it is necessary by the schedule
 (currently it never happens).

#### How to reproduce it (as minimally and precisely as possible):

See "What happened"

#### Anything else we need to know?:

It seems the counter of Back-off pulling retries is not incremented. Here is a part of POD log:
```
  Warning  Failed   13m (x439 over 113m)    kubelet  Error: ImagePullBackOff
  Normal   BackOff  3m25s (x484 over 113m)  kubelet  Back-off pulling image "my.private.artifactory/myimage:mytag"
```
It seems it makes a docker pull try every 12 seconds on average. It seems it waits only initial 10 seconds between retries.

Here is an earlier version of the same POD event log:
```
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  24m                   default-scheduler  Successfully assigned mynamespace/mynamespace-mycronjob-1619601000-h5cmr to ip-10-0-45-27.eu-west-1.compute.internal
  Normal   Pulling    23m (x4 over 24m)     kubelet            Pulling image "my.private.artifactory/myimage:mytag"
  Warning  Failed     23m (x4 over 24m)     kubelet            Failed to pull image "my.private.artifactory/myimage:mytag": rpc error: code = Unknown desc = Error response from daemon: Get https://my.private.artifactory/v2/myimage/manifests/mytag: unknown: Authentication is required
  Warning  Failed     23m (x4 over 24m)     kubelet            Error: ErrImagePull
  Normal   BackOff    9m44s (x65 over 24m)  kubelet            Back-off pulling image "my.private.artifactory/myimage:mytag"
  Warning  Failed     4m45s (x87 over 24m)  kubelet            Error: ImagePullBackOff
```

#### Related (similar) issues:
- https://github.com/kubernetes/kubernetes/issues/54870
- https://github.com/kubernetes/kubernetes/issues/62382

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19

Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: Amazon EKS (their SaaS Kubernetes)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by 249043822** [comment]
If ErrImagePull happened, the containers of pod would not be created, the backoff only does ImagePull again, so the job's BackoffLimit could not perceive the ImagePullBackoff

**Comment by SergeyKanzhelev** [comment]
Glanced over. Is this dup of #87278?

**Comment by kolomenkin** [comment]
I would say it is not a full dulicate of #87278.

I can imagine someone can decide to keep those issue without a fix for Deployments. I'm not sure if Deployment yaml editing if affected,

But I point similar behavior in the context of CronJob. I.e. we need to success/fail by some schedule. 

And it is extremely important when CronJob is updated (redeployed) with a different valid image reference. And those changes are ignored infinitely.

**Comment by kouk** [comment]
Does anyone have a workaround for this?

**Comment by kolomenkin** [comment]
> Does anyone have a workaround for this?

Unfortunately the best way is not to use Kubernetes outside of pet projects.
From my experience in 2021 Kubernetes is still not a production-ready solution.
It is full of obvious bugs in design and implementation. No one should use it for production ever.

Examples:
- the current issue. We can treat cronjobs as production not-ready for many years because this problem can affect any project at any point of time. Just some temporary outage of your dockerhub and your cronjobs are got broken and will not run even after re-deploy.
- there is no support for running exactly 1 simultaneous DB migration as a part of deploy of a new service version. This is a base functionality expected from K8S. The only workaround is to lock service update speed to 1 pod at a time which is a dirty hack. What if I have hundreds of pods and each of them needs 1 minute to start. It will take hours to deploy new service version. Really?
- Kustomize is a mess from design point of view. CommonLabels are broken by design (problems when you change/add a label and you have some service). Name prefixes are broken by design (some references are not renamed and you need to patch them manually).
- K8S logs is a face-palm feature. There is a very tricky way to sort them in a chronological order. Really??? Logs are usually deleted after 1 hour, similar messages get lost by design, messages are not informative.
