### ISSUE TITLE
All healthcheck failed when using NLB and externalTrafficPolicy Local

### ISSUE THREAD

**Issue by axelczk** [kubernetes/kubernetes#101529]
I'm trying to use an AWS NLB for UDP traffic on a EKS cluster with kubernetes 1.19.8 with an externalTrafficPolicy sets to local in order to keep the client sourceIP. 
With this configuration, all the node's healthcheck in the target group are failed. 

If I'm correct, the node that have one pod of the application should be considered as healthy and the healthcheck on the path /healthz is handled by the kube-proxy. 

Believing that was my application the problem, I tried this solution:
https://aws.amazon.com/fr/blogs/opensource/network-load-balancer-support-in-kubernetes-1-9/

But the result was still the same: instead of having one pod healty and the others not healthy, both pod where unhealty. 

Best regards

**Comment by VigneshSP94** [comment]
the /healthz endpoint of kube-proxy is actually to check the health of your worker node, not your application. I am not understanding how `--healthz-bind-address ipport` will ensure the health of your application.

Can you curl your worker on port 10256 and see if it gives a 200? if your node is not listening on 10256, please run this `kubectl get daemonset kube-proxy -n kube-system -o json | jq '.spec.template.spec.containers[].command` command to see on what port the healthz server is listening.

If it doesn't give 200, then your lb will not mark them as healthy.

**Comment by axelczk** [comment]
Here is the result of your command:

```
[
  "kube-proxy",
  "--v=2",
  "--config=/var/lib/kube-proxy-config/config"
]
```

After further test, I think the problem is on EKS side and not on kubernetes.

**Comment by aojea** [comment]
I'm not familiar but the docs here say you should open some network rules too
https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support

> After further test, I think the problem is on EKS side and not on kubernetes.

Anyway, this doesn't seem sig-network or kubernetes

/kind support
Please close it if you discard is kubernetes related or retag it as /sig cloud-provider if you feel is cloud-provider specific

**Comment by thockin** [comment]
For "Local" services, the healtcheck needs to target the per-service `healthCheckNodePort` which is an HTTP endpoint that returns true ONLY IF there is at least 1 pod for that specific service on that node.  See staging/src/k8s.io/cloud-provider/service/helpers/helper.go func `GetServiceHealthCheckPathPort()` which is called in staging/src/k8s.io/legacy-cloud-providers/aws/aws.go but maybe that's not what is being run?
