### ISSUE TITLE
Init container is running but not ready

### ISSUE THREAD

**Issue by chaodaiG** [kubernetes/kubernetes#101585]
Reference https://github.com/kubernetes/test-infra/issues/21985

#### What happened:

Saw multiple pods with states:

```
"initContainerStatuses": [
{
	"name": "clonerefs",
	"state": {
		"running": {
			"startedAt": "2021-04-27T20:52:18Z"
		}
	},
	"lastState": {},
	"ready": false,
	"restartCount": 0,
	"image": "gcr.io/k8s-prow/clonerefs:v20210426-19829768bb",
	"imageID": "gcr.io/k8s-prow/clonerefs@sha256:15420f0867aecde2574b00d8b2099ba4a18952287106e50b0e945c34f7e88b39",
	"containerID": "containerd://2ed0e5f8c4b4e5c99d578876c3882ca45e9953b88caa456c962a05193b8c5801"
},
```

Notice that the init pod is running but not ready. 

#### What you expected to happen:

Should this happen at all?

#### How to reproduce it (as minimally and precisely as possible):

See https://github.com/kubernetes/test-infra/issues/21985

**Comment by matthyx** [comment]
@chaodaiG do you have an example of a pod spec for that?

**Comment by matthyx** [comment]
Normally init containers should be `ready` only after they have successfully ran, or if they have succeeded their readinessProbe:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/prober/prober_manager.go#L262-L270

**Comment by matthyx** [comment]
I think in your case the initContainer was stuck running and therefore never returned its status...

**Comment by chaodaiG** [comment]
> @chaodaiG do you have an example of a pod spec for that?

See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101434/pull-kubernetes-e2e-capz-ha-control-plane/1387147612502626304, click on `YAML` at the bottom of the page

**Comment by matthyx** [comment]
Awesome!
So I think it really happened as I have described... initContainer was stuck forever, didn't exit with success and thus never updated its status to `ready`.
Maybe you could follow this advice: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#detailed-behavior

> Use activeDeadlineSeconds on the Pod and livenessProbe on the container to prevent init containers from failing forever. The active deadline includes init containers.

**Comment by fromanirh** [comment]
per https://github.com/kubernetes/kubernetes/issues/101585#issuecomment-842403611 doesn't seem a bug. Please reopen if there is new evidence
/close
