### ISSUE TITLE
Move off gce-device-plugin-gpu job from deprecated OS image

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#101558]
xref: https://github.com/kubernetes/kubernetes/issues/101471#issuecomment-826499568

`ci-kubernetes-e2e-gce-device-plugin-gpu` job is currently using image [`gke-1134-gke-rc5-cos-69-10895-138-0-v190320-pre-nvda-gpu`](https://github.com/kubernetes/test-infra/blob/518ab2b454a502af06d74f7e54a712be7a7abf8b/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gpu-gce.yaml#L5-L6). 

This image is super old (cos-69; 4.14 kernel) which is not supported anymore https://cloud.google.com/container-optimized-os/docs/release-notes#current_active_releases

This image is also "special" since it is using preloaded nvidia drivers unlike the rest of the e2e tests which use [default GCI version](https://github.com/kubernetes/kubernetes/blob/50e319767cc4aad5c6ff56a8d002c406cdcc3e0e/cluster/gce/config-default.sh#L89) 

We should see if we can instead use the default COS image so that this job won't depend on any special images.

/sig node
/sig testing

/cc @pacoxu @ruiwen-zhao

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/test-infra/pull/21994 to use a general node image. I cannot find a special image with gpu preloaded.

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/test-infra/pull/21994 to use a general node image. I cannot find a special image with gpu preloaded.

**Comment by bobbypage** [comment]
Looks like image update went fine, GPU plugin jobs is still green :) 

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master
