### ISSUE TITLE
Proposal: Network Labels for pods (e.g. for security-groups), libnetwork remote driver

### ISSUE THREAD

**Issue by MalteJ** [kubernetes/kubernetes#10166]
# libnetwork
Docker has got a new network stack: [libnetwork](https://github.com/docker/libnetwork)
libnetwork supports external logic to manage container networking via a remote driver API.
When starting up a container libnetwork asks the remote driver to create one or more network endpoints, set them up and attach them to the container. It is possible to provide user defined options in form of key-value pairs to the driver. After the driver has created and attached the endpoints Docker will execute the container.

# Proposal
The idea is to add network-labels to the Kubernetes pod manifest. These labels will be propagated through Docker into the libnetwork remote driver. The remote driver will configure the container's network according to the given labels.
This allows to realize some interesting things: For example you can attach a container to multiple separated networks. Or you can realize security groups.

## Multiple Networks
You could separate pods via different networks. E.g. tenantA would have an other network than tenantB.

## Security Groups
Security groups may work like this:
You have an application-server pod and add a network-label `security-groups=http-server,db-client`. Further you have a database pod with the network-label `security-groups=db-server`.
When starting the pods Docker will provide these labels to the libnetwork remote driver. The driver creates the network endpoints and configures iptables with rules defined by the security groups.
E.g. the security group `db-server` may look like this:

    allow incoming traffic from sec-group 'db-client' to TCP port 3306.
    allow outgoing traffic to sec-group 'db-client' from TCP port 3306.

and `db-client` could look like this:

    allow outgoing traffic to sec-group 'db-server' to TCP port 3306.
    allow incoming traffic from sec-group 'db-client' status ESTABLISHED,RELATED.

whereas the group `http-server` would allow incoming http traffic:

    allow incoming traffic from 0.0.0.0/0 to TCP port 80.
    allow outgoing traffic to 0.0.0.0/0 from TCP port 80.

# Difficulties
## Service IPs
The DNAT used by kube-proxy could be a problem to identify the container the traffic is coming from. The source IP should not be altered by the NAT.

# Tasks
## Docker
Docker still has to add support for remote libnetwork drivers. At the moment it can only use the internal libnetwork drivers.
### Pod Manifests
The pod manifest would need to support network-labels
### Security-Groups
There would have to be a place where you define the security group rules.
### Remote Driver
We would need to create a libnetwork remote driver that supports the described features.

**Comment by thockin** [comment]
This overlaps with #17551 #15465 #13622 #16958
