### ISSUE TITLE
kubectl api returns Throttling request took message 

### ISSUE THREAD

**Issue by summerisc** [kubernetes/kubernetes#101631]
#### What happened:
On one of the control-plane node, any kubectl commands take longer time with a log like:
```
$ kubectl get pod

97555 request.go:655] Throttling request took 1.184984731s, request: GET:https://10.0.1.1:6443/apis/coordination.k8s.io/v1?timeout=32s
NAME                      READY   STATUS    RESTARTS   AGE
mongo-mongodb-0           1/1     Running   0          3m10s

```
It took long time to respond a kubectl call with this Throttling request took thing. 

#### What you expected to happen:
kubectl API call returns response without error

#### How to reproduce it (as minimally and precisely as possible):
run any kubectl command

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by SataQiu** [comment]
@summerisc FYI: https://github.com/kubernetes/kubernetes/pull/87740

**Comment by SataQiu** [comment]
Try to change the log level with this PR #101634

**Comment by neolit123** [comment]
> Try to change the log level with this PR #101634

/sig instrumentation api-machinery

**Comment by vebbeb** [comment]
I see this behavior if the `.kube` folder does not belong to the same user and group who executes the `kubectl` command. Therefore, the following did the trick for me:

```
chown -R myusername:mygroup .kube/
````
