### ISSUE TITLE
Missing taint: node.kubernetes.io/unreachable:NoExecute when nodes enter NotReady state

### ISSUE THREAD

**Issue by bsctl** [kubernetes/kubernetes#101674]
#### What happened:
When the worker nodes enter in a NotReady state, the taint `node.kubernetes.io/unreachable:NoExecute` is not added to the node. Only the `node.kubernetes.io/unreachable: NoSchedule` taint is added. The effect is that pods running on such workers remain in `Running` state and never rescheduled.

This is similar to #97100 but in different conditions.
Actually we discovered it during test of patch #98168.
#98168 works only if you shutdown worker nodes, it doesn't work if you shutdown masters too.

```
NAME                STATUS     ROLES                  AGE   VERSION
k8s-caas-infra01    NotReady   infra                  72d   v1.20.6
k8s-caas-infra02    NotReady   infra                  72d   v1.20.6
k8s-caas-infra03    NotReady   infra                  72d   v1.20.6
k8s-caas-master01   Ready      control-plane,master   72d   v1.20.6
k8s-caas-master02   Ready      control-plane,master   72d   v1.20.6
k8s-caas-master03   Ready      control-plane,master   72d   v1.20.6
k8s-caas-worker01   NotReady   worker                 72d   v1.20.6
k8s-caas-worker02   NotReady   worker                 72d   v1.20.6
```

```
$ kubectl -n auth-system get pods -o wide | grep infra
keycloak-0                                    1/1     Running   0          98m    10.38.70.92     k8s-caas-infra01   <none>           <none>
keycloak-keycloak-operator-654ff77bf5-hv6c9   1/1     Running   0          107m   10.38.136.220   k8s-caas-infra03   <none>           <none>
keycloak-postgresql-7654cccbb7-8s6fr          1/1     Running   0          107m   10.38.136.232   k8s-caas-infra03   <none>           <none>
```

```
$ kubectl describe node k8s-caas-infra03
Name:               k8s-caas-infra03
Roles:              infra
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k8s-caas-infra03
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/infra=
Annotations:        csi.volume.kubernetes.io/nodeid: {"rbd.csi.ceph.com":"k8s-caas-infra03"}
                    kubeadm.alpha.kubernetes.io/cri-socket: /run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.9.5.68/24
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 17 Feb 2021 12:26:12 +0100
Taints:             node.kubernetes.io/unreachable:NoSchedule
```

#### What you expected to happen:
We expect the taints:

```
node.kubernetes.io/unreachable:NoExecute
node.kubernetes.io/unreachable:NoSchedule
node.kubernetes.io/not-ready:NoExecute
```

as per [documentation](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions)

#### How to reproduce it (as minimally and precisely as possible):
This issue has been observed during an operational test on an on-prem Kubernetes v1.20.6 cluster.
We have an high availability control plane with 3 masters and few workers distributed on two stretched data-center.
In order to exercise the DR capability, we switched off all the VMs, both masters and workers.

1. shut down all the masters and workers
2. restart only the masters
3. after masters become `Ready`, restart a couple of workers.
4. at this point we expect the system (after the eviction time of 300s) to "_move_" pods from the workers that are in `NotReady` to the workers that are in `Ready` state  
4. check taints on the remaining workers that are still `NotReady`
 
#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.6`
- Cloud provider or hardware configuration: `on-premises running on RHEV`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.2 LTS (Focal Fossa)`
- Kernel (e.g. `uname -a`): `5.4.0-72-generic`
- Install tools: `kubeadm`
- Network plugin and version (if this is a network-related bug): `calico`
- Others:

**Comment by akshitgrover** [comment]
Hi,
I have been working with Kubernetes for quiet some time. Now, I feel like contributing as well.
Once this is triaged and is still valid. I'd like to take it up.
Being a first time contributor, I might get lost on the way and need some help.
Thank you

**Comment by ahg-g** [comment]
> We expect the taints:

> node.kubernetes.io/unreachable:NoExecute
> node.kubernetes.io/unreachable:NoSchedule
> node.kubernetes.io/not-ready:NoExecute

unreachable and not-ready aren't supposed to exist on the node at the same time. The not-ready taint is added when the node status is NotReady, while unreachable is added when the ready status is unknown.

**Comment by bsctl** [comment]
> unreachable and not-ready aren't supposed to exist on the node at the same time. The not-ready taint is added when the node status is NotReady, while unreachable is added when the ready status is unknown.

@ahg-g 
well, what we see doesn't match with statement above

```
NAME                STATUS     ROLES                  AGE   VERSION
k8s-caas-infra01    NotReady   infra                  72d   v1.20.6
k8s-caas-infra02    NotReady   infra                  72d   v1.20.6
k8s-caas-infra03    NotReady   infra                  72d   v1.20.6.             <----- node NotReady
k8s-caas-master01   Ready      control-plane,master   72d   v1.20.6
k8s-caas-master02   Ready      control-plane,master   72d   v1.20.6
k8s-caas-master03   Ready      control-plane,master   72d   v1.20.6
```

and

```
$ kubectl describe node k8s-caas-infra03
Name:               k8s-caas-infra03
Roles:              infra
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=k8s-caas-infra03
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/infra=
Annotations:        csi.volume.kubernetes.io/nodeid: {"rbd.csi.ceph.com":"k8s-caas-infra03"}
                    kubeadm.alpha.kubernetes.io/cri-socket: /run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 10.9.5.68/24
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 17 Feb 2021 12:26:12 +0100
Taints:             node.kubernetes.io/unreachable:NoSchedule   <--- taint unreachable

```

**Comment by ahg-g** [comment]
> well, what we see doesn't match with statement above

ok, but expecting that both to exist is not valid.

Are you able to lookup the node name in the kube-controller-manager logs? Perhaps updating the taint failed, in which case we could see the following error log: https://github.com/kubernetes/kubernetes/blob/6c658a86f9e75943024b0b4f792a37938a96a31f/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L598

**Comment by elChipardo** [comment]
Hi guys, I got the same issue on a Kubernetes cluster v1.19.7.
However, this has been fixed recently in:
- v1.21.0: [PR]: https://github.com/kubernetes/kubernetes/pull/96876) // [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#changelog-since-v1200)
- v1.19.9: [PR](https://github.com/kubernetes/kubernetes/pull/98140) // [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#changelog-since-v1198)
- v1.120. [PR](https://github.com/kubernetes/kubernetes/pull/98168) // [CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1204)

Hope it's helpful!

**Comment by adampl** [comment]
@elChipardo the OP says it occurs on v1.20.6, so it must be a different issue, or it hasn't been completely fixed.

**Comment by ehashman** [comment]
Can someone confirm if they can reproduce this?

/triage needs-information

**Comment by gjkim42** [comment]
I couldn't reproduce this issue at v1.21.2 and v1.20.6.

```
gjkim@node0:~$ kubectl get nodes
NAME    STATUS     ROLES                  AGE   VERSION
node0   Ready      control-plane,master   26m   v1.20.6
node1   Ready      control-plane,master   24m   v1.20.6
node2   Ready      control-plane,master   22m   v1.20.6
node3   Ready      <none>                 21m   v1.20.6
node4   NotReady   <none>                 21m   v1.20.6
gjkim@node0:~$ kubectl get pods -o wide
NAME                                 READY   STATUS        RESTARTS   AGE     IP           NODE    NOMINATED NODE   READINESS GATES
deploy-managed-pod-bfc4b9d79-4cngj   1/1     Terminating   0          20m     10.42.0.6    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-5x926   1/1     Terminating   0          20m     10.42.0.5    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-7lx9f   1/1     Terminating   0          20m     10.42.0.2    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-8p7vv   1/1     Terminating   0          20m     10.42.0.3    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-d67fd   1/1     Running       1          20m     10.47.0.7    node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-dkpng   1/1     Running       1          20m     10.47.0.2    node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-dt97q   1/1     Running       0          9m41s   10.47.0.15   node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-g88gg   1/1     Running       0          9m41s   10.47.0.11   node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-kpgdk   1/1     Running       0          9m41s   10.47.0.16   node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-lz9kv   1/1     Running       1          20m     10.47.0.4    node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-nb9zc   1/1     Terminating   0          20m     10.42.0.4    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-pr5nq   1/1     Terminating   0          20m     10.42.0.1    node4   <none>           <none>
deploy-managed-pod-bfc4b9d79-sjcmj   1/1     Running       1          20m     10.47.0.8    node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-x5q7v   1/1     Running       0          9m41s   10.47.0.13   node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-z7726   1/1     Running       0          9m41s   10.47.0.14   node3   <none>           <none>
deploy-managed-pod-bfc4b9d79-z7zct   1/1     Running       0          9m41s   10.47.0.12   node3   <none>           <none>
sts-managed-pod-0                    1/1     Running       1          20m     10.47.0.3    node3   <none>           <none>
sts-managed-pod-1                    1/1     Running       1          20m     10.47.0.6    node3   <none>           <none>
sts-managed-pod-2                    1/1     Terminating   0          20m     10.42.0.7    node4   <none>           <none>
sts-managed-pod-3                    1/1     Running       1          20m     10.47.0.5    node3   <none>           <none>
sts-managed-pod-4                    1/1     Terminating   0          20m     10.42.0.8    node4   <none>           <none>
sts-managed-pod-5                    1/1     Running       1          20m     10.47.0.1    node3   <none>           <none>
sts-managed-pod-6                    1/1     Terminating   0          19m     10.42.0.9    node4   <none>           <none>
sts-managed-pod-7                    1/1     Running       1          19m     10.47.0.10   node3   <none>           <none>
sts-managed-pod-8                    1/1     Terminating   0          19m     10.42.0.10   node4   <none>           <none>
sts-managed-pod-9                    1/1     Running       1          19m     10.47.0.9    node3   <none>           <none>
```

```
kubectl get node node4 -ojsonpath="{.spec.taints[*]}"
{"effect":"NoSchedule","key":"node.kubernetes.io/unreachable","timeAdded":"2021-06-27T05:10:22Z"} {"effect":"NoExecute","key":"node.kubernetes.io/unreachable","timeAdded":"2021-06-27T05:10:38Z"}
```

node4 was successfully tainted with the `NoExecute` effect and the kubernetes successfully tried to terminate the pods of `node4`.

I think you should wait more time for the kubernetes to evict the pods of the `NotReady` node. I didn't test a lot, but it seemed that v1.20.6 evicted pods more slowly.

**Comment by bsctl** [comment]
@gjkim42 hello thanks for working on it. Please do all the steps reported in the description. Just shutting down a worker is not enough. Thanks 

> shut down all the masters and workers

> restart only the masters

> after masters become Ready, restart a couple of workers.

> at this point we expect the system (after the eviction time of 300s) to "move" pods from the workers that are in NotReady to the workers that are in Ready state

> check taints on the remaining workers that are still NotReady

**Comment by gjkim42** [comment]
@bsctl 

Actually, I did.
I made a cluster with 3 master nodes and 2 worker nodes.

Deployed a deployment (10 replicas) and a statefulset (10 replicas).

And then,

1. Stopped all 5 VM nodes
2. Started 3 master nodes
3. Executed `watch kubectl get nodes`
    All 5 nodes were `Ready` status at first. (Kubernetes couldn't state actual states of the nodes at that time)
    Waited for 2 worker nodes's status to become `NotReady` (Waited for kubenetes to be able to state their actual status)
4. Started a worker node and waited for pod eviction
    One worker node was become `Ready` status after a few seconds.
5. After more than 5 minutes, pod-eviction occurred.

Can you reproduce this issue always? or sometimes?
I think you have to elaborate on this scenario more for us to reproduce it.

**Comment by bsctl** [comment]
@gjkim42 on cluster v1.20.6 the issue is still there. Which logs can be useful to understand the issue?

> I think you should wait more time for the kubernetes to evict the pods of the NotReady node. I didn't test a lot, but it seemed that v1.20.6 evicted pods more slowly.

the eviction time is 300s, why need to wait more? However, we waited up to one hour :)

Currently do not have a cluster in more recent versions to test.

**Comment by bsctl** [comment]
> I think you have to elaborate on this scenario more for us to reproduce it.

I simply switched off (brutally switched off the VM) all the nodes in step 1, not a graceful shutdown. This because the initial intent of the test was a DR simulation.

**Comment by gjkim42** [comment]
Could you give us the logs of all of kube-controller-managers?

**Comment by adampl** [comment]
I suggest you write a bash script that's using a local multi-node cluster provisioned by [Kind](https://kind.sigs.k8s.io/), so that everyone can have a fully reproducible environment. Something along the lines of https://github.com/kubernetes/kubernetes/issues/97100

**Comment by chuangxinyuan** [comment]
@bsctl I have encountered the same situation as you, according to below NOTE, k8s cannot add taint very quickly, i guess, partially because the noexcute taint will evict pod, and the process will consume lots of resources and be error prone, to avoid chaos, k8s add  an hidden limit rate. if you shutdown the node one by one, and only shutdown next node until the privious pod eviction finished （ if you have lots of pod on this node, meaning you mingt need lots of time waiting).

please try, i have tested in my 22 node ENV, my approach works, you might be able to see what you expect.

[https://v1-18.docs.kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/](url)
Note: The control plane limits the rate of adding node new taints to nodes. This rate limiting manages the number of evictions that are triggered when many nodes become unreachable at once (for example: if there is a network disruption).

**Comment by stingshen** [comment]
In a cluster that has less than `large-cluster-size-threshold` nodes, the node eviction rate would be set to 0 if more than `unhealthy-zone-threshold` nodes are NotReady.

`large-cluster-size-threshold` and `unhealthy-zone-threshold` are controller manager parameters.
