### ISSUE TITLE
ephemeralContainers: don't add new debug container if one already exists

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes/kubernetes#101609]
#### What happened:
With featureGate: ephemeralContainer enabled, I ran:
kubectl debug -q -n graylog -i graylog-0 --image=nicolaka/netshoot --image-pull-policy=Always --target=graylog-server -- tcpdump -i eth0 -U -nn

#### What you expected to happen:
to add a debug container.. and if one already existed.. re-use it.. OR atleast when above command exits.. remove the patched in container.

#### How to reproduce it (as minimally and precisely as possible):
Run kubectl debug .. multiple times on kubernetes 1.19.

**Comment by RolandMa1986** [comment]
I found there's a discussion #84764 about ephemeralContainers lifecycle. The proposal can be found here  [#KEP-277: Ephemeral Containers](https://github.com/verb/kubernetes-enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md#killing-ephemeral-containers)

**Comment by KlavsKlavsen** [comment]
@RolandMa1986 Perhaps I'm just not finding it - but it does not seem to specify anything on how to handle this, where when I run debug on the same pod - multiple times, I get an extra container inside the pod with named debug-$randomstring  - ending up with a LOT of new containers instead of it either "removing it after I'm done" - or re-attaching to the existing one instead of creating a new one.

**Comment by verb** [comment]
#84764 is about modifying the API to allow removing or replacing ephemeral containers (currently this is disallowed). Let's make this issue about deciding how `kubectl debug` should handle this situation when it occurs.

/remove-sig node
/sig cli
/triage accepted
/assign

@KlavsKlavsen What behavior do you expect when you run `kubectl debug` with the name of an ephemeral container that's still running? Should it remove and re-add the container? simply reattach to it?

FYI @pacoxu

**Comment by KlavsKlavsen** [comment]
@verb I would expect it to reattach to a running debug container.. so I could f.ex. start a tcpdump - and get back to it later.. and I would be happy for having a "default timeout - for auto cleanup" setting.. so it would automaticly remove debug containers if I forgot.. and then I'd like settings for creating an extra debug container (ie. by giving it a different name than default 'debug')  and an override for the timeout setting.. 
Then it would be a fantastic tool for adhoc debug'ing in k8s.

**Comment by verb** [comment]
@KlavsKlavsen Reattaching to ephemeral containers by name is already possible via `kubectl attach`. We could perhaps automatically reattach when `--interactive` or `--attach` is specified and the command hasn't changed, but this implicit action might surprise some users. At the same time, I'd like `kubectl debug` to be as convenient as possible.

As a thought experiment, what should happen if 2 different users attempt to create an identically named debugging container at the same time, as might happen when responding to an outage?

We'll support expiring ephemeral containers by allowing third-party controllers to detect and remove them. That's #84353.

**Comment by KlavsKlavsen** [comment]
> @KlavsKlavsen Reattaching to ephemeral containers by name is already possible via `kubectl attach`. We could perhaps automatically reattach when `--interactive` or `--attach` is specified and the command hasn't changed, but this implicit action might surprise some users. At the same time, I'd like `kubectl debug` to be as convenient as possible.
>

Its what I intuitively had expected (and thought it did - until I realized I had 30+ new containers in the pod :)
 
> As a thought experiment, what should happen if 2 different users attempt to create an identically named debugging container at the same time, as might happen when responding to an outage?
> 
you could "complain about a missing --attach" - as a debug container by that name is already running (and then when I had just run it the second time - it would also complain and tell me to add --attach to reattach to default named container 'debug' - or ask to set name specificly to something else by giving: --name debugklavsen

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
@verb 
according to #84764 and #103482, this worked as expected and we will not change the behavior.
