### ISSUE TITLE
pods are scheduled to nodes which cannot run them - missing cause of "hanging" pods in `kubectl describe pod`

### ISSUE THREAD

**Issue by rdxmb** [kubernetes/kubernetes#101653]
#### What happened:

I have 3 worker nodes. When draining one of them, there actually is too much workload for the other two: One is full with required memory for all of the pods. The other one has much memory free (it has 128 GB RAM overall), but the pod number has reached a total of 130. (I did not change the max pod number in kubelet and I am wondering why the total pod number increases the default max number of 100, but that does'nt matter here...)

The new pods scheduled to the node with too much pods hang:

```tick-portal                                   chronograf-0                                                  0/1     ContainerCreating   0          2m3s    <none>         drei   <none>           <none>```

```
# kubectl -n tick-portal describe po chronograf-0 
Name:                 chronograf-0
Namespace:            tick-portal
Priority:             99999
Priority Class Name:  tick-portal
Node:                 drei/10.139.0.93
Start Time:           Fri, 30 Apr 2021 10:32:28 +0200
Labels:               app.kubernetes.io/instance=tick-portal
                      app.kubernetes.io/name=tick-chronograf
                      controller-revision-hash=chronograf-77896c7496
                      reddoxx/storageclass=iscsi-pv-provisioner
                      statefulset.kubernetes.io/pod-name=chronograf-0
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        StatefulSet/chronograf
Containers:
  tick-chronograf:
    Container ID:   
    Image:          chronograf:1.8.8
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  100Mi
    Requests:
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /var/lib/chronograf from chronograf-var-lib-chronograf (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-c6cbw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  chronograf-var-lib-chronograf:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  chronograf-var-lib-chronograf-chronograf-0
    ReadOnly:   false
  default-token-c6cbw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-c6cbw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  2m24s  default-scheduler  Successfully assigned tick-portal/chronograf-0 to drei
```

The syslog of the node includes:

```
Apr 30 10:36:29 drei systemd[2813765]: Failed to create control group inotify object: Too many open files
Apr 30 10:36:29 drei systemd[2813765]: Failed to allocate manager object: Too many open files
```

10 minutes later, the `kubectl describe pod` include, 

`   Warning  FailedCreatePodSandBox  12m                kubelet            Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded`

Some minutes later I see
`
  Warning  FailedCreatePodSandBox  11m                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1a768b865b0b0f545f7ff4060d38fe43e2d1fa50a16df0ca284796a3e5d74120": failed to allocate for range 0: no IP addresses available in range set: 10.244.3.1-10.244.3.254`

What I wonder is that

1. pods are scheduled to a node with has not enough ressources (in this case IP addresses or the max pod number has reached)
2. pods with lower `priorityClass` than the hanging pods still run and are not evicted.
3. `kubectl describe pod` first does not include the problem, after about 10 minutes it includes the note about not enought IP addresses
4. `kubectl describe node` does not include any information about the problem

#### What you expected to happen:

1. When there are not enough ressources (max pod number increased, not IP addresses available etc), the pods are not scheduled to those nodes
2. Pods with lower `priorityClass` are evicted, so that the hanging pods can be started. 
3. `kubectl describe pod` includes the cause, why those pods are hanging, e.g. `max number of pods has reached` or something like that. If there are not enough IP addresses on that node, it would be good to get this information in 1 minute and not in 10. And there should be a suggestion how to increase them, if this is possible.
4. `kubectl describe node` should include the problem on the node here.

#### How to reproduce it (as minimally and precisely as possible):

Try to start about 130 very small pods on one node. Be sure CPU and memory limit is not reached. First start the one with low priorityClass and then those with high priorityClass.

#### Environment:
- Kubernetes version (use `kubectl version`): `GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c"`
- Cloud provider or hardware configuration: Hardware with 128 GB RAM and 40 virtual cpu cores
- OS (e.g: `cat /etc/os-release`):  `Ubuntu 20.04.2 LTS`
- Kernel (e.g. `uname -a`): `Linux drei 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Others (only the node which has reached the max number of pods)

```
# free -h
              total        used        free      shared  buff/cache   available
Mem:          125Gi        30Gi        22Gi       281Mi        72Gi        95Gi
Swap:            0B          0B          0B
```

```
root@eins.k1.reddoxx.com:~# k describe node drei
Name:               drei
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=drei
                    kubernetes.io/os=linux
                    reddoxx.com/containerruntime=containerd
Annotations:        flannel.alpha.coreos.com/backend-data: null
                    flannel.alpha.coreos.com/backend-type: host-gw
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.139.0.93
                    kubeadm.alpha.kubernetes.io/cri-socket: /run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Tue, 27 Apr 2021 22:21:58 +0200
Taints:             <none>
Unschedulable:      false
Lease:
  HolderIdentity:  drei
  AcquireTime:     <unset>
  RenewTime:       Fri, 30 Apr 2021 10:43:40 +0200
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Wed, 28 Apr 2021 18:13:15 +0200   Wed, 28 Apr 2021 18:13:15 +0200   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Fri, 30 Apr 2021 10:39:38 +0200   Wed, 28 Apr 2021 18:12:38 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Fri, 30 Apr 2021 10:39:38 +0200   Wed, 28 Apr 2021 18:12:38 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Fri, 30 Apr 2021 10:39:38 +0200   Wed, 28 Apr 2021 18:12:38 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                True    Fri, 30 Apr 2021 10:39:38 +0200   Wed, 28 Apr 2021 18:12:38 +0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled
Addresses:
  InternalIP:  10.139.0.93
  Hostname:    drei
Capacity:
  cpu:                40
  ephemeral-storage:  286772552Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131673152Ki
  pods:               110
Allocatable:
  cpu:                40
  ephemeral-storage:  264289583486
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             131570752Ki
  pods:               110
System Info:
  Machine ID:                                  7fb7f96066e1408c9f672502ba54e27d
  System UUID:                                 38353738-3933-5a43-4a37-34313039394a
  Boot ID:                                     d350ec71-8a4d-4a72-b23e-bed8b82fa744
  Kernel Version:                              5.4.0-70-generic
  OS Image:                                    Ubuntu 20.04.2 LTS
  Operating System:                            linux
  Architecture:                                amd64
  Container Runtime Version:                   containerd://1.4.4
  Kubelet Version:                             v1.20.6
  Kube-Proxy Version:                          v1.20.6
PodCIDR:                                       10.244.3.0/24
PodCIDRs:                                      10.244.3.0/24
Non-terminated Pods:                           (99 in total)
  Namespace                                    Name                                                  CPU Requests  CPU Limits  Memory Requests  Memory Limits    AGE
  ---------                                    ----                                                  ------------  ----------  ---------------  -------------    ---
  
#  [... - snip ]

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests           Limits
  --------           --------           ------
  cpu                500m (1%)          400m (1%)
  memory             70221915392 (52%)  72208966912 (53%)
  ephemeral-storage  0 (0%)             0 (0%)
  hugepages-1Gi      0 (0%)             0 (0%)
  hugepages-2Mi      0 (0%)             0 (0%)
Events:
  Type    Reason           Age                From     Message
  ----    ------           ----               ----     -------
  Normal  NodeSchedulable  12m (x2 over 40h)  kubelet  Node drei status is now: NodeSchedulable
```

actually:

```
# kubectl get po -A -o wide | grep -c <NODE>
112
```
edited: Changed the order of "How to reproduce it"

**Comment by ahg-g** [comment]
> pods are scheduled to a node with has not enough ressources (in this case IP addresses or the max pod number has reached)
> kubectl get po -A -o wide | grep -c <NODE>
> 112

Can you check if any of those pods completed (i.e., in status Fail or Success). Note that completed pods are ignored by the scheduler.

> pods with lower priorityClass than the hanging pods still run and are not evicted.

By default, I think eviction happen when the node is under resource pressure form running pods (e.g., memory pressure). Eviction doesn't happen on admission: If a higher priority pod can't be admitted, kubelet doesn't evict a running lower priority pod to fit the higher priority one.

**Comment by pacoxu** [comment]
/remove-sig node
I suggest you can run `drain --v=9` to see what happened in the process. 
It should not be related to kubelet eviction.

**Comment by rdxmb** [comment]
@pacoxu 

sorry, I have not seen your answer yet.

> Can you check if any of those pods completed (i.e., in status Fail or Success). Note that completed pods are ignored by the scheduler.

No, not Failed or Success. I talk about pods belonging to deployments or statefulSets.

Unfortunately, I am not able to reproduce that anymore, because we've just changed the environment to use smaller nodes - so we cannot reach the maximum number of pods. For me it seems that there is a problem when reaching the max number of pods, where there is no problem with cpu- and memory-limit (pod number per node seems to be a soft limit in kubernetes. See number 1., 3. and 4. in this issue)

> If a higher priority pod can't be admitted, kubelet doesn't evict a running lower priority pod to fit the higher priority one.

Oh, I really expected that kubelet will do that. So for number 2. above I will create a feature request :)
