### ISSUE TITLE
Dual-stack: should we have dual-stack DNS?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#101682]
In a dual-stack cluster, the cluster DNS service can be upgraded to dual-stack.  Kubelet has a `--cluster-dns` config which is a list of IPs -- this is very hard to update as an end user.

I think we should consider if and how to make this easier.

1) Should we have `--cluster-dns-service` as an alternative, which pulls all cluster IPs?
2) Should all pods get resolv.conf `nameserver` lines for dual-stack?  Or only pods with dual-stack podIPs?

**Comment by uablrek** [comment]
Why would an end user care which protocol their DNS queries uses as long as the lookup works? What is the use-case?

You might well have dual-stack at home and an ipv4 address as nameserver and you do not care.

In an ipv6-only cluster upgraded to dual-stack the `--cluster-dns` would already be an ipv6 address.

**Comment by aojea** [comment]
definitively in favor of using only one IP family for DNS resolv.conf  , as Lars says, DNS resolves  A and/or AAAA independently of the IP layer ... DNS is already complicated and dualstacking the resolv.conf will make it more complicated

**Comment by chrisohaver** [comment]
CoreDNS used in a sentence ... chris wakes up...

> 1. DNS server may get clever and respond according to the FamilyOf(request.SrcIP), but CoreDNS does not do that.

I suppose this could be done to filter the additional records of an SRV request? Or maybe in forwarding cases, only forward to upstream servers in the same family?  I don't think any of those things really matter.

Do you have an example of why/how a DNS server would respond differently based on the source ip family?

**Comment by khenidak** [comment]
I am saying it should not :-)

**Comment by khenidak** [comment]
/help

if you - the reader - want to help please reach out. I will provide the needed support to drive that one forward.

**Comment by EricWvi** [comment]
Should we add another DNS Service and enter both IPFamilies addresses in Pod's `resolv.conf` file?

**Comment by uablrek** [comment]
> update: When I curl a Service, it will make two requests, one for type A, another for type AAAA. Will this increase the DNS server's pressure?

That is a different thing. The A,AAAA it the dual-stack query. It is already supported and works. This issue is about the protocol used for the query.

**Comment by uablrek** [comment]
I have still not seen a use-case. Why?

I am not against dual-stack, it was my main task when I started working with K8s, but this will add complexity for no good reason.

At the very least, *require a full set of e2e tests* that must work on different environments in a PR implementing this. To add this function might seem easy and fun, but to create e2e tests, and maintain them, will put things in perspective.

**Comment by EricWvi** [comment]
> That is a different thing. The A,AAAA is the dual-stack query. It is already supported and works. This issue is about the protocol used for the query itself.

I know it works now. I just wonder whether it affects the server's performance? It seems unnecessary to me, as far as normal cases are concerned.

Am I drifting off the point?

**Comment by uablrek** [comment]
> Am I drifting off the point?

Yes, a bit. Let's keep to discussions about the issue. The A,AAAA queries are probably due to https://en.wikipedia.org/wiki/Happy_Eyeballs. And it's the "resolver" in the application that controls this, and nothing K8s can do anything about. And BTW `go` uses it's own resolver (normally) that handles go threads better, other likely uses the resolver in libc. Ns-query tools often uses their own way to do nslookup (for better control) so a test using, say `dig`, is probably not a good test for the function requested in this issue.

**Comment by uablrek** [comment]
> But since we are trying to move api-server to dual-stack because an external client might be running exclusively one of either families we should also consider moving DNS server to dual-stack. I wouldn't say it is urgent but it is important.

An external client will have it's own "resolv.conf" (or something similar) and since CoreDNS listens to "::" (https://github.com/kubernetes/kubernetes/issues/101682#issuecomment-943703963), this will already work.
