### ISSUE TITLE
Kubernetes scheduler unit test registry_test Failures with master go

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#101657]
#### What happened:
Below are the failures while running unit test **pkg/scheduler/framework/runtime/registry_test.go** with golang in master branch.
```
--- FAIL: TestMerge (0.00s)
    --- FAIL: TestMerge/valid_Merge (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607ea0 pluginFactory2:0x11607ed0]. Got map[pluginFactory1:0x11607e40 pluginFactory2:0x11607e70] instead.
    --- FAIL: TestMerge/Merge_duplicate_factories (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11607f60]. Got map[pluginFactory1:0x11607f00] instead.
--- FAIL: TestRegister (0.00s)
    --- FAIL: TestRegister/valid_Register (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11607fc0]. Got map[pluginFactory1:0x11607f90] instead.
    --- FAIL: TestRegister/Register_duplicate_factories (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11608050]. Got map[pluginFactory1:0x11607ff0] instead.
--- FAIL: TestUnregister (0.00s)
    --- FAIL: TestUnregister/valid_Unregister (0.00s)
        registry_test.go:252: Unregister(). Expected map[pluginFactory2:0x116080e0]. Got map[pluginFactory2:0x116080b0] instead.
```
**Reference : https://github.com/golang/go/issues/45697#issuecomment-826007480**

**$ go version
go version devel go1.17-5daefc5363 Thu Apr 22 01:40:02 2021 +0000 linux/ppc64le**
Note: Occurs in x86 architecture as well.

#### What you expected to happen:
The tests should Pass as with stable go
```
[root@rajalakshmi1-workspace kubernetes]# go version
go version go1.16 linux/ppc64le
[root@rajalakshmi1-workspace kubernetes]# make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/ 2>&1 | tee pss.log
+++ [0422 09:55:38] Running tests without code coverage
ok      k8s.io/kubernetes/pkg/scheduler/framework/runtime       0.190s
[root@rajalakshmi1-workspace kubernetes]#
```

#### How to reproduce it (as minimally and precisely as possible):
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/

#### Environment:
Master branch of kubernetes repo.
https://github.com/kubernetes/kubernetes
OS: Linux
Observed failure on ppc64le and x86 architectures

**Below is the attached log:**
[fail.log](https://github.com/kubernetes/kubernetes/files/6404969/fail.log)

**Comment by Rajalakshmi-Girish** [comment]
@laboger request help on getting this triaged.

**Comment by laboger** [comment]
The Go compiler developer has identified the bugs in the test that is causing it to fail. They are listed in the last comment in the Go issue before closing it. https://github.com/golang/go/issues/45697#issuecomment-826007480

**Comment by pacoxu** [comment]
So the correct way to compare function would be something like
```
			if reflect.ValueOf(pluginFactory).Pointer()  != reflect.ValueOf(val).Pointer() {
				// pluginFactory functions are not the same.
				return false
			}
```

**Comment by Rajalakshmi-Girish** [comment]
@pacoxu The issue still exists.
Can you please reopen?
```
[root@rajalakshmi-workspace ~]# go version
go version devel go1.17-326a792517 Tue May 11 02:46:21 2021 +0000 linux/ppc64le
[root@rajalakshmi-workspace ~]# rm -rf kubernetes
[root@rajalakshmi-workspace ~]# git clone https://github.com/kubernetes/kubernetes.git
Cloning into 'kubernetes'...
remote: Enumerating objects: 1227971, done.
remote: Counting objects: 100% (315/315), done.
remote: Compressing objects: 100% (224/224), done.
remote: Total 1227971 (delta 130), reused 139 (delta 83), pack-reused 1227656
Receiving objects: 100% (1227971/1227971), 744.02 MiB | 12.30 MiB/s, done.
Resolving deltas: 100% (884050/884050), done.
Updating files: 100% (20733/20733), done.
[root@rajalakshmi-workspace ~]# cd kubernetes
[root@rajalakshmi-workspace kubernetes]# make test KUBE_RACE=-race WHAT=./pkg/scheduler/framework/runtime/ 2>&1 | tee test.log
+++ [0518 01:02:37] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
Generating prerelease lifecycle code for 27 targets
+++ [0518 01:02:43] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/deepcopy-gen
Generating deepcopy code for 227 targets
+++ [0518 01:02:54] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/defaulter-gen
Generating defaulter code for 89 targets
+++ [0518 01:03:08] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/code-generator/cmd/conversion-gen
Generating conversion code for 124 targets
+++ [0518 01:03:37] Building go targets for linux/ppc64le:
    ./vendor/k8s.io/kube-openapi/cmd/openapi-gen
Generating openapi code for KUBE
Generating openapi code for AGGREGATOR
Generating openapi code for APIEXTENSIONS
Generating openapi code for CODEGEN
Generating openapi code for SAMPLEAPISERVER
+++ [0518 01:03:56] Building go targets for linux/ppc64le:
    ./vendor/github.com/go-bindata/go-bindata/go-bindata
+++ [0518 01:03:58] Running tests without code coverage
I0518 01:05:58.514729  901615 framework.go:394] "Plugin's EventsToRegister() returned nil" plugin="fakeNoopRuntime"
E0518 01:05:58.534396  901615 framework.go:522] "Failed running AddPod on PreFilter plugin" err="injected status" plugin="TestPlugin1" pod=""
E0518 01:05:58.537375  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.539516  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.540210  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.541527  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin 1" pod=""
E0518 01:05:58.542358  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.543517  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.544150  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.545923  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.546821  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.547541  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.549109  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.549927  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin 1" pod=""
E0518 01:05:58.550729  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.551520  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.553730  901615 framework.go:1033] "Failed running Permit plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.555885  901615 framework.go:1033] "Failed running Permit plugin" err="injected status" plugin="TestPlugin" pod=""
E0518 01:05:58.570058  901615 framework.go:961] "Failed running Reserve plugin" err="injected status" plugin="test-plugin" pod=""
E0518 01:05:58.571188  901615 framework.go:875] "Failed running PreBind plugin" err="injected status" plugin="test-plugin" pod=""
E0518 01:05:58.572213  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="test-plugin" pod=""
E0518 01:05:58.573085  901615 framework.go:1033] "Failed running Permit plugin" err="injected status" plugin="test-plugin" pod=""
E0518 01:05:58.577639  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="bind-1" pod=""
E0518 01:05:58.580805  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="bind-0" pod=""
E0518 01:05:58.581558  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="bind-0" pod=""
E0518 01:05:58.583112  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="bind-1" pod=""
E0518 01:05:58.585448  901615 framework.go:908] "Failed running Bind plugin" err="injected status" plugin="bind-0" pod=""
--- FAIL: TestMerge (0.00s)
    --- FAIL: TestMerge/valid_Merge (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11611cd0 pluginFactory2:0x11611d00]. Got map[pluginFactory1:0x11611c70 pluginFactory2:0x11611ca0] instead.
    --- FAIL: TestMerge/Merge_duplicate_factories (0.00s)
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11611d90]. Got map[pluginFactory1:0x11611d30] instead.
--- FAIL: TestRegister (0.00s)
    --- FAIL: TestRegister/valid_Register (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11611df0]. Got map[pluginFactory1:0x11611dc0] instead.
    --- FAIL: TestRegister/Register_duplicate_factories (0.00s)
        registry_test.go:207: Register(). Expected map[pluginFactory1:0x11611e80]. Got map[pluginFactory1:0x11611e20] instead.
--- FAIL: TestUnregister (0.00s)
    --- FAIL: TestUnregister/valid_Unregister (0.00s)
        registry_test.go:252: Unregister(). Expected map[pluginFactory2:0x11611f10]. Got map[pluginFactory2:0x11611ee0] instead.
FAIL
FAIL    k8s.io/kubernetes/pkg/scheduler/framework/runtime       0.199s
FAIL
make: *** [Makefile:184: test] Error 1
[root@rajalakshmi-workspace kubernetes]#
```

**Comment by Rajalakshmi-Girish** [comment]
@pacoxu I am not sure if you can access this link for our CI job. Can you please check?
https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le/1394427387789185024
The above tests have been failing every day in our jobs!

**Comment by pacoxu** [comment]
- [periodic-kubernetes-unit-test-ppc64le](https://prow.ppc64le-cloud.org/prowjob?prowjob=4df7f7b4-b763-11eb-b926-3eb8c12c8462) downloads go from url="https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-ppc64le.tar.gz"
- [postsubmit-master-golang-kubernetes-unit-test-ppc64le](https://prow.ppc64le-cloud.org/prowjob?prowjob=a4620ab5-b785-11eb-837c-0234662505dc) downloads go from `curl -X GET http://build-bot.prow:8090/build\?project\=$build_project\&commit\=$build_commit -o /tmp/golang.tar.gz`

I suspect the postsubmit-master-golang-kubernetes-unit-test-ppc64le failed for wrong golang version.

periodic-kubernetes-unit-test-ppc64le failed for other problems. The TestMerge is not failed.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
>     * [periodic-kubernetes-unit-test-ppc64le](https://prow.ppc64le-cloud.org/prowjob?prowjob=4df7f7b4-b763-11eb-b926-3eb8c12c8462) downloads go from url="[https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-ppc64le.tar.gz](https://storage.googleapis.com/golang/go$%7BGOLANG_VERSION%7D.linux-ppc64le.tar.gz)"
> 
>     * [postsubmit-master-golang-kubernetes-unit-test-ppc64le](https://prow.ppc64le-cloud.org/prowjob?prowjob=a4620ab5-b785-11eb-837c-0234662505dc) downloads go from "curl -X GET [http://build-bot.prow:8090/build\?project\=$build_project\&commit\=$build_commit](http://build-bot.prow:8090/build%5C?project%5C=$build_project%5C&commit%5C=$build_commit) -o /tmp/golang.tar.gz"
> 
> 
> I suspect the postsubmit-master-golang-kubernetes-unit-test-ppc64le failed for wrong golang version.
> 
> `periodic-kubernetes-unit-test-ppc64le` failed for other problems. The TestMerge is not failed.
> 
> For ppc64le failures, there are several issues in golang: [golang/go#43228](https://github.com/golang/go/issues/43228) (fixed yesterday) \[golang/go#45685](https://github.com/golang/go/issues/45685) \ [golang/go#37331 (comment)](https://github.com/golang/go/issues/37331#issuecomment-825711057)

Yes the go versions for both the jobs are different and it is **intentional:**

`periodic-kubernetes-unit-test-ppc64le`: It is meant to run Kubernetes unit tests with the stable version of golang
`postsubmit-master-golang-kubernetes-unit-test-ppc64le`: It is meant to run Kubernetes unit tests with golang built from the master branch of https://github.com/golang/go

As I mentioned in the description of this issue, these unit test cases are **failing only on golang that is built from master branch** and passing with stable versions of golang.
And as Lynn mentioned in https://github.com/kubernetes/kubernetes/issues/101657#issuecomment-832225880, the golang team has concluded that these failures are due to the bugs in the test case.

**Comment by pacoxu** [comment]
With #101757,  `reflect.ValueOf(pluginFactory).Pointer()  != reflect.ValueOf(val).Pointer()` is false

```
        registry_test.go:158: Merge(). Expected map[pluginFactory1:0x11611cd0 pluginFactory2:0x11611d00]. Got map[pluginFactory1:0x11611c70 pluginFactory2:0x11611ca0] instead.
```
@cherrymui Per #101657 (comment), do you mean that we should change to `reflect.ValueOf(pluginFactory).Interface()  != reflect.ValueOf(val).Interface()`?

**Comment by cherrymui** [comment]
> @cherrymui @laboger Per #101657 (comment), do you mean that we should change to reflect.ValueOf(pluginFactory).Interface() != reflect.ValueOf(val).Interface()?

No. In general comparing `Value.Interface()` is the right thing to do. But if the Value is actually a `func`, which is not comparable, comparing `Interface()` will panic.

**Comment by dims** [comment]
Note from golang team about this bug is here:
https://github.com/golang/go/issues/45697#issuecomment-826007480
