### ISSUE TITLE
Should we remove GAed feature gate ServiceNodeExclusion 

### ISSUE THREAD

**Issue by wangyysde** [kubernetes/kubernetes#101614]
In the pkg/features/kube_features.go file, comment says that feature gate ServiceNodeExclusion  remove in 1.22. Should we remove this GAed feature gate in 1.22?
Additional, I saw a few of feature gates marked remove in 1.22. Can I remove them too?

**Comment by pacoxu** [comment]
#100776 will fix it

**Comment by wangyysde** [comment]
OK, then I will close this issue. Thanks. 
/close
