### ISSUE TITLE
Sometimes many Pods are signaled SIGTERM.

### ISSUE THREAD

**Issue by jc-lab** [kubernetes/kubernetes#101650]
#### What happened:

Many Pods, including kube-schedule-controller, coredns, etc. are restarted from time to time.
At this time, Pods are signaled SIGTERM.

One sample:
```
I0430 06:41:36.233750       1 request.go:645] Throttling request took 1.118210563s, request: GET:https://10.96.0.1:443/api/v1/namespaces/default/configmaps/my-ingress-controller-leader-user
I0430 06:42:26.101312       1 main.go:184] "Received SIGTERM, shutting down"
I0430 06:42:26.104148       1 nginx.go:365] "Shutting down controller queues"
I0430 06:42:33.490162       1 status.go:123] "leaving status update for next leader"
I0430 06:42:33.490245       1 nginx.go:381] "Stopping NGINX process"
2021/04/30 06:42:35 [notice] 575#575: signal process started
I0430 06:42:49.038985       1 nginx.go:394] "NGINX process has stopped"
I0430 06:42:49.039029       1 main.go:192] "Handled quit, awaiting Pod deletion"
I0430 06:42:59.046659       1 main.go:195] "Exiting" code=0
```

* Scaling never happen.
* There is no log of kernel bugs etc in dmesg.

#### What you expected to happen:

Don't send SIGTERM.

#### How to reproduce it (as minimally and precisely as possible):

- 1 control plane node.
- 1 worker node.
- 1 storage node (rook-ceph).

#### Anything else we need to know?:

This is the log output by `log -p` after killed:
[kube-controller-manager-cp-node.txt](https://github.com/kubernetes/kubernetes/files/6403740/kube-controller-manager-cp-node.txt)
[kubelet-2.txt](https://github.com/kubernetes/kubernetes/files/6403742/kubelet-2.txt)
[containerd-2.txt](https://github.com/kubernetes/kubernetes/files/6403743/containerd-2.txt)
[cp-node-kubelet.txt](https://github.com/kubernetes/kubernetes/files/6403744/cp-node-kubelet.txt)
[etcd.txt](https://github.com/kubernetes/kubernetes/files/6403745/etcd.txt)
[ingress-2.txt](https://github.com/kubernetes/kubernetes/files/6403746/ingress-2.txt)

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.2`
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: `Baremetal`
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04 LTS`
- Kernel (e.g. `uname -a`): `5.4.0-64-generic`
- Install tools: `kubeadm`

**Comment by VigneshSP94** [comment]
Can you add more information like /resources/app-details.

I see the below message in kubelet log -

```
Error while processing event ("/sys/fs/cgroup/memory/user.slice/user-1000.slice/session-48.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/user.slice/user-1000.slice/session-48.scope: no such file or directory
```
Can you provide what is the cgroup driver being used? systemd?

**Comment by jc-lab** [comment]
Hello @VigneshSP94
Could you please tell me a bit how to check `/resources/app-details`?
I am not sure what this is.
Thank you.

**Comment by jc-lab** [comment]
Anyone can give me a hint? :'-(

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/). Sorry that this has been sitting with no response :(

/remove-kind bug
/kind support
/close
