### ISSUE TITLE
apf: use a lister to avoid making periodic LIST calls

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#101667]
#### What happened:
The Priority & Fairness bootstrap configuration reconciler uses `LIST` to get all the `FlowSchema` and `PriorityLevelConfiguration` objects on the cluster at `1m` interval.

We can use a `lister` that is backed by a cache to avoid making these periodic `LIST` calls. 

In a production cluster we expect to have tens of APF configuration objects, not hundreds or thousands, but it is a nice optimization to have.

**Comment by wojtek-t** [comment]
@tkashem - will you be able to help with this (once the main PR merges)? It should be fairly small thing.

**Comment by tkashem** [comment]
@wojtek-t yes, I will take care of it.

/assign

**Comment by tkashem** [comment]
Ben Luddy will take care of this issue.  

/assign @benluddy

**Comment by benluddy** [comment]
> /assign @benluddy

Looking into it.

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

I missed the PR has been opened for it: #105800 - I will take a look.
