### ISSUE TITLE
switch dnsutils container to a smaller base

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10163]
It's WAY smaller, but it requires either tests use +ndots=3 or a docker fix for ndots.

**Comment by pmorie** [comment]
Out of curiousity, does this busyboc have selinux support compiled in?

**Comment by thockin** [comment]
How would I tell?

progrium/busybox

FWIW, if there was an ultra-min RH distro for use inside containers, I'd be
even happier.  Is someone working on that?

**Comment by pmorie** [comment]
@thockin I'm doing my own test now, was in airports earlier

**Comment by pmorie** [comment]
Doesn't look like it supports it :-/

> FWIW, if there was an ultra-min RH distro for use inside containers, I'd
be even happier. Is someone working on that?

Very interesting question.  I don't know about _inside_ containers -- I'm
at RH Summit this week and will ask around.

**Comment by thockin** [comment]
Someone build me ufedora, which is 5 MB big and has a shell and just enough
to run `yum install`

**Comment by thockin** [comment]
Once we do this we can simplify the DNS e2e test - we don't need a jessie variety and a wheezy variety

**Comment by thockin** [comment]
Progrium was just EOL'ed in favor of Alpine which has totally broken DNS.  YaY!

@vmarmol

**Comment by thockin** [comment]
for this issue we can use dig which should not use the host's resolver lib anyway, but in general this is pretty useless

**Comment by JeanMertz** [comment]
> Someone build me ufedora, which is 5 MB big and has a shell and just enough
> to run `yum install`

Interested in hearing more about this. Where did you get this? Given Alpine's DNS search woes, I'm in search for a replacement, but everything above 20mb seems overkill to run a single binary.

**Comment by thockin** [comment]
It was a plea for someone to do it, not that someone has done it.

**Comment by JeanMertz** [comment]
Do'h, now I see the d instead of a t, excuse me.

**Comment by janeczku** [comment]
I ended up creating `Alpine-kubernetes`: A base image that gives you Alpine Linux + DNS SEARCH domain support. See here: https://github.com/janeczku/docker-alpine-kubernetes.

**Comment by thockin** [comment]
That's neat.  I'm not sure I'm comfortable with how intrusive it is into
the lifecycle of a container, but it sure seems useful to get started with
and maybe figure out some more solutions.

Thanks!

**Comment by janeczku** [comment]
@thockin For a non intrusive way you may have a look at https://github.com/janeczku/alpine2skydns - bridging Alpine Linux containers to SkyDNS.

**Comment by luebken** [comment]
@thockin wrote:
> FWIW, if there was an ultra-min RH distro for use inside containers, I'd be
even happier.  Is someone working on that?

With the [recent uprise](https://www.brianchristner.io/docker-is-moving-to-alpine-linux/) in interest in minimal containers I was also searching for alternatives for alpine. @thockin: Any luck?

**Comment by thockin** [comment]
Hopefully Alpine (musl) is on the way to sanity.  They supposedly have a
working DNS resolver now.  we just have to wait for it to propagate.

**Comment by thockin** [comment]
alpine:3.4 is available and viable.

**Comment by bowei** [comment]
probably can close this -- the e2e tests now use alpine-based dnsutils (~5 MB)

**Comment by christhomas** [comment]
Musl's DNS is still broken

**Comment by thockin** [comment]
Details?
