### ISSUE TITLE
Table driven tests for kube-proxy / service proxies

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#101765]
After hacking around on some new kube proxy stuff, i found that my brain had trouble reasoning about why failures were happening.   As a holistic solution to this problem i want to use the same solution that we have for network policy testing ~ which is outputting comprehensive test data with positive and negative controls.  

@dougsland is hacking on a prototype of a few service, i think ill probably take it over after friday (if he lets me :)) and make it table driven. 

Roughly here is what ill do for the first iteration.... any suggestions on wether other data should be added?

# Table tests for service proxies

Its not easy to know exactly what service configurations are and are not supported on a cluster.  For example.

```
node 1:                   ---> (node 1) fails
node 2: user ---> service ---> (node 2) works 
node 3:                   ---> (node 3) fails
```

In the above scenario.... a user (or pod) on node 2, is able to access
a service with an endpoint on node 2, however not able to access services
on node 1 or node 3.

To debug such a scenario, a user might run all the conformance tests, and discover, for example, that polling during tests fails from inside of a pod that is scheduled to a *random* node in a cluster, however, the topology of WHERE a pod is polling from is one of the most important aspects of testing the service proxy. 

Additionally, the *details* of the service type (nodeport, loadbalancer, clusterip, and so on) being used as the ingress point is important.

# Solution

We should have tabular test outputs for kube-proxy that give us topological pattern
information for exactly what pods, on what nodes can access what what *other* pods on other nodes.  This will allow people to easily diagnose:

- hairpin service errors
- errors related to local -> external routes
- errors related to nodes that are performing poorly for non-k8s reasons (infra problems)

```
          node1(cip,np)       node2(cip,np)    node3 (cip,np)    node4(cip,np)  
node 1         ok,ok            ok,ok            ok,ok               ok,ok    
node 2         ok,ok            ok,ok            ok,ok               ok,ok
node 3         ok,ok            ok,ok            ok,ok               ok,ok
node 4         ok,fail          ok,fail          ok,fail             ok,ok
```

# Initial prototype

For an initial prototype of this, a set of golang tests which probe pods through
service endpoints can be built that output these tables.

**Comment by jayunit100** [comment]
@dougsland has done some initial prototypes for this , doug will demo it today at the kube-proxy workin group

**Comment by mattfenwick** [comment]
👍 I'm interested in helping out with this !

**Comment by knabben** [comment]
prototyping a version here: https://github.com/K8sbykeshed/k8s-service-lb-validator

**Comment by jayunit100** [comment]
niceeee

**Comment by aojea** [comment]
+100

can we take the same approach that we did with network policy?
separate folder and running parallel to current ones?
That turned out to work out very well IMHO and zero disruption

**Comment by jayunit100** [comment]
We're still working on this , @knabben had a prototype that is working

**Comment by jayunit100** [comment]
@rajaskakodkar
