### ISSUE TITLE
kubelet memory leak v1.18.1

### ISSUE THREAD

**Issue by danisafta** [kubernetes/kubernetes#101724]
#### What happened:
kubelet increased more than 100MB in memory in 4 days.

#### What you expected to happen:
kubelet to not used that amount of RAM

#### How to reproduce it (as minimally and precisely as possible):
I have reproduced it using 3 cronjobs which create hello world pods each minute
and another cronjob that writes a line to a file each minute.

#### Environment:
- Kubernetes version (use `kubectl version`):
v1.18.1

- Cloud provider or hardware configuration
 happens on both virtualbox and baremetal

- OS (e.g: `cat /etc/os-release`):
centos 7

- Kernel (e.g. `uname -a`):
4.18.0-147.3.1

I have seen some existing issues like #64137 but I do not have any dangling resources associated with the cgroup.

**Comment by wzshiming** [comment]
/assign

This is a duplicate issue, there has been a fixed PR but it has not been merged. #100326
