### ISSUE TITLE
Kubernetes check docker config.json

### ISSUE THREAD

**Issue by Arsen-Uulu** [kubernetes/kubernetes#101733]
Hi, I was looking into injecting proxy variables from config.json to my pods running in K8s.  config.json for proxies works only from docker cli = https://github.com/docker/cli/blob/master/cli/command/container/create.go#L77-L103, 
is it possible to do something similar within in Kubernetes?  Since Kubernetes is just another API client for docker. 

I know work around is to use ConfigMap and patch deployments/nodes.

**Comment by BenTheElder** [comment]
> is it possible to do something similar within in Kubernetes? 

Podpreset is the closest thing I can think of. It was removed but you can use a mutating webhook to add it. https://github.com/kubernetes/kubernetes/issues/93900#issuecomment-774460034

This is really a container runtime concern though.
/sig node

> Since Kubernetes is just another API client for docker.

kubernetes does have a docker API client when using dockershim, which is deprecated, but not when using other container runtimes, and will not be implementing docker specific features.

**Comment by wgahnagl** [comment]
This feature doesn't seem to have enough details to further investigate. What is the end result you want to achieve?

Please re-open once you have provided more information.

/triage needs-information
/close
