### ISSUE TITLE
broken command to update api testdata

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#101700]
#### What happened:
I tried rebasing an old open PR, and got merge conflicts on api testdata.  I read https://github.com/kubernetes/api/blob/648b77825832f4e96433407e4b406a3bdbb988bd/testdata/README.md#current-version and tried the command listed there for regenerating the test data.  It failed as follows.

```sh
(base) mspreitz@mjs12 kubernetes % UPDATE_COMPATIBILITY_FIXTURE_DATA=true go test ./vendor/k8s.io/api -run //HEAD

directory /Users/mspreitz/go/src/k8s.io/kubernetes/vendor/k8s.io/api is not a package listed in vendor/modules.txt
```

#### What you expected to happen:
I expected successful regeneration of the api test data.

#### How to reproduce it (as minimally and precisely as possible):
Checkout `master` and issue the command exhibited above.

#### Environment:
- Kubernetes version (use `kubectl version`): `master` is at commit dfc91819b78e7dbf56194f50eff4c19c9fecd01b right now
- 
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @liggitt

**Comment by liggitt** [comment]
ah, latest go versions changed the invocation to `… go test k8s.io/api ...`

**Comment by liggitt** [comment]
fixed in https://github.com/kubernetes/kubernetes/pull/101704
