### ISSUE TITLE
Call scheduler extension based on labels/annotations

### ISSUE THREAD

**Issue by hasethuraman2** [kubernetes/kubernetes#101776]
#### What would you like to be added:

Today, an external application can register its extender to kube-scheduler (through the manifest) and kube-scheduler calls the extender unconditionally. I am looking where if extender can be invoked only when a pod has a certain labels/annotations.

#### Why is this needed:
In a large cluster where regularly 100s of pods (in a large system where x1000s of pods running) every min reaches extender.
Rather, let extender register itself with the label-selector/annotation-selector.

Please let me know what I can do further if this makes sense - should I create a KEP and/or code changes and send PR or any other procedure?

**Comment by Huang-Wei** [comment]
This requirement makes sense to me. We have a couple of options supporting this:

- introduce a new API field (e.g., pod label selector) to extender
- flag the pods (e.g., set a particular annotation and possibly) so that scheduler won't call extenders upon them - this can be enabled by a feature gate

Feel free to raise a KEP discussing potential options.

**Comment by ahg-g** [comment]
The feature looks reasonable. +1 to writing a KEP to discuss API options, but a label selector seems like the most natural approach.

**Comment by Huang-Wei** [comment]
> +1 to writing a KEP to discuss API options, but a label selector seems like the most natural approach.

Basically, we can implement it with or without API changes.

The 2nd option I mentioned above can work without API changes. It lets the users define their custom rules to identify "which kind of pods should be ignored by extenders", and use an annotation to communicate with scheduler. That annotation can be imposed in the yamls in the CI/CD phase, or guarding by custom logic in admission webhook.

**Comment by ahg-g** [comment]
The second option means we need to pre-define an annotation that the scheduler understands, correct? I think it is better to give users the flexibility via labelSelector; besides, we should avoid using annotations as an API wherever possible.

**Comment by Huang-Wei** [comment]
Yes, let's just brainstorm to list all the options first, and then analyze their pros/cons in the KEPs.

BTW: another option is to make `extenders` profile-leveled. We used to discuss this in other contexts, but seems it also fit this requirement.

**Comment by mailhari** [comment]
What is profile-leveled? It is completely new to me. Is it for having multiple extenders?

**Comment by mailhari** [comment]
Meanwhile, I am still drafting the KEP here .. https://github.com/mailhari/enhancements/commit/d10d3faa9eda9288b113373628e5801c619fd5fc

One I hear the confirmation, will create a PR for KEP for pros and cons.

**Comment by Huang-Wei** [comment]
@mailhari for now, the extenders is defined as a [global argument](https://github.com/kubernetes/kubernetes/blob/b9ddee497a2fed32f70ccdd03a145f497564b348/pkg/scheduler/apis/config/types.go#L105) of scheduler configuration, which means every pod's scheduling to subjected to calling those extenders. But if move `extenders` into the [profile](https://github.com/kubernetes/kubernetes/blob/b9ddee497a2fed32f70ccdd03a145f497564b348/pkg/scheduler/apis/config/types.go#L109) struct, you can choose particular pods to call specific extenders - through pod's .spec.schedulerName which is mapped to scheduler profile.

**Comment by mailhari** [comment]
@Huang-Wei So an extender cannot register in multiple kube-schedulers - hope that is not a valid scenario in the first place?

**Comment by mailhari** [comment]
Got it. Deleted my previous comment.

**Comment by mailhari** [comment]
I hope the spec.schedulerName can be modified by mutatingwebhook during pod creation.

**Comment by mailhari** [comment]
@Huang-Wei @wojtek-t Created
https://github.com/kubernetes/enhancements/pull/2750

FYI This is my first PR and first KEP to kubernetes repo. Please let me know if anything else is missing.

**Comment by Congrool** [comment]
Hi, does this feature have any further work?

**Comment by sanposhiho** [comment]
I think it's still a good-to-have feature.

**Comment by kerthcet** [comment]
/remove-lifecycle stale
/assign
I'm working on this.
