### ISSUE TITLE
Use docker 1.7 network command to setup bridge

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#10178]
As of Docker 1.7 network plugins have been marked experimental and will soon allow the following workflow:

Kubelet ensure proper Kubernetes network bridge is in place

```
$ kubelet --configure-network=true --network-cidr=10.200.10.0/24 --network-name=kubernetes ...
```

```
$ docker network ls
NETWORK ID      NAME           TYPE
d367e613ff7f    none           null
bd61375b6993    host           host
cc455abccfeb    kubernetes     bridge
```

```
$ docker run --net=kubernetes
```

More details regarding network plugins can be found here: https://github.com/docker/docker/blob/master/experimental/networking.md

**Comment by dchen1107** [comment]
We should do this once we cut 1.0.

**Comment by thockin** [comment]
Docker's networking does not allow you to specify a CIDR for the bridge, so
we can not use it yet.

**Comment by justinsb** [comment]
Propose closing: I believe this is obsolete with kubenet & CNI work?
