### ISSUE TITLE
aks-engine-azure-disk (vmas and vmss) tests are failing

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#101720]
#### Which jobs are failing:

https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-disk-vmss
https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-disk-vmas

#### Which test(s) are failing:
all of them

#### Since when has it been failing:
4/28

#### Testgrid link:
https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-disk-vmss
https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-disk-vmas

#### Reason for failure:

```
2021/05/02 21:33:29 main.go:327: Something went wrong: starting e2e cluster: error creating cluster: cannot deploy: cannot get the create deployment future response: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```

#### Anything else we need to know:

/cc @chewong @andyzhangx

**Comment by chewong** [comment]
Opened https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/823 to fix it

**Comment by jsturtevant** [comment]
These tests are removed: https://github.com/kubernetes/test-infra/pull/22067
