### ISSUE TITLE
Setting up KubernetesUI and Grafana UI in single node kubernetes cluster

### ISSUE THREAD

**Issue by maulik887** [kubernetes/kubernetes#10177]
I have simple kubernetes running on ubuntu like it mentioned [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker.md). Here I wanted to configure kubernetes UI along with Grafana UI so that I can do/monitor stuff using UI. 

I have followed [KubernetesUI](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/ui.md) project and [this](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md) link for help, but not able to setup in mentioned environment. Anybody tried setting up Kubernetes UI or Grafana UI in kubernetes cluster ?

Update1- It seems like kubernetes UI lives in kubernetes [code base](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/www). Is there any pre-cooked docker image available like 'hyperkube' ? Or do I need to pick that code out from kubernetes code base and need to manually run in docker container ?
I also tried to run all the pods and services mentioned [here](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md) in above environment. But that Heapster pod is not starting somehow after so long, Anybody tried that ?

**Comment by bcbroussard** [comment]
@maulik887 The Kubernetes web ui is built into the apiserver and runs by default  at `http://<kubernetes master api>/static/app/` or the shortcut url `/ui`. So you don't need to do anything special to access it.

If you want to build your own custom tabs and pages in the web ui, you can look at [/www/master/components/README.md](/www/master/components/README.md)

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (157/150 (104%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:13343)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU5c-000P5O-EJ
	for dev@imwiz.com; Thu, 01 Jun 2017 11:40:53 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=O1gCxSy01mxuWLUJ2sq/fGhJ+8M=; b=TsjN2xYdbdI594Q0
	a5IQHtKWvWZYE1uujB5suySNYkH4oBNb+7qrvbrTqXK/2tglyy0Yhu9JzPka1+cA
	de29hkixxTCQ9XqRSwH/M7W8Esij5VSad4sVrn0+5bfCqyA4/TBiQ5xZkH21RA8v
	RjwCcVeA+/JNf+KHf3nomy1029E=
Received: by filter0660p1mdw1.sendgrid.net with SMTP id filter0660p1mdw1-11665-5930517F-27
        2017-06-01 17:40:15.391642012 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id x6gZ-3K9RsiRsvMkgEbpnQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:40:15.329 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:40:15 -0700
