### ISSUE TITLE
1.22 Release Notes: Known Issues

### ISSUE THREAD

**Issue by pmmalinov01** [kubernetes/kubernetes#101728]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.22 Release Notes([example from 1.21 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#known-issues)). If you know of issues or API changes that are going out in 1.22, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @cici37 @Damans227 @sladyn98 @simcard0000
/sig release
/milestone v1.22

**Comment by Damans227** [comment]
> If you know of issues or API changes that are going out in 1.19, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

1.19 ?

**Comment by jgavinray** [comment]
Hi @cici37, @Damans227, and @sladyn98 
Bug Triage team here for the 1.22 release. Is this issue still intended for milestone 1.22?

**Comment by xing-yang** [comment]
Please add the following to the Known Issues section of the 1.22 Release Notes:
```
vSphere CSI Driver does not support Kubernetes v1.22 because it uses v1beta1 CRD APIs.  Do not upgrade to v1.22 if you are using vSphere CSI Driver.
```
CC @divyenpatel @SandeepPissay @msau42 @jsafrane @gnufied

**Comment by msau42** [comment]
@xing-yang Can you also mention the CSIMigrationVSphere feature gate in the note as well?

**Comment by xing-yang** [comment]
@msau42 what should I mention about the CSIMigrationVSphere feature gate?

**Comment by msau42** [comment]
If the feature gate is enabled, they should also hold off on upgrading to 1.22

**Comment by gnufied** [comment]
The main concern as far as k8s release is - it is intree to CSI migration of vSphere volumes that is broken in 1.22. So I think our release note should say something like:

> vSphere migration of intree volumes is broken with 1.22. If you are using migrated vsphere volumes, you should not upgrade to 1.22 until vSphere CSI driver can properly support 1.22.
