### ISSUE TITLE
[Flaky Test] [sig-instrumentation] MetricsGrabber should grab all metrics from a Scheduler

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#101894]
### Failure cluster [94211b5f97dae0d51701](https://go.k8s.io/triage#94211b5f97dae0d51701)
![image](https://user-images.githubusercontent.com/2010320/117766965-ed238800-b262-11eb-92e6-48ac98874f9c.png)

##### Error text:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:81
Apr 29 19:10:43.698: Unexpected error:
    <*errors.StatusError | 0xc002d9a280>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server rejected our request for an unknown reason (get pods kube-scheduler-bootstrap-e2e-master:10251)",
            Reason: "BadRequest",
            Details: {
                Name: "kube-scheduler-bootstrap-e2e-master:10251",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "unknown",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 400,
        },
    }
    the server rejected our request for an unknown reason (get pods kube-scheduler-bootstrap-e2e-master:10251)
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/instrumentation/monitoring/metrics_grabber.go:88
```
#### Recent failures:
[2021/5/11 上午6:59:59 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391890754812514304)
[2021/5/11 上午6:58:56 ci-kubernetes-e2e-gci-gce-network-proxy-http-connect](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-http-connect/1391890503502401536)
[2021/5/11 上午4:59:55 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391860556041818112)
[2021/5/11 上午4:58:58 ci-kubernetes-e2e-gci-gce-network-proxy-http-connect](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-http-connect/1391860303720878080)
[2021/5/11 上午3:00:01 ci-kubernetes-e2e-gci-gce-network-proxy-grpc](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc/1391830356272877568)

/kind failing-test

/sig instrumentation
/assign

**Comment by pacoxu** [comment]
The flake happened in #95366 before.

**Comment by pacoxu** [comment]
This is fixed.
![image](https://user-images.githubusercontent.com/2010320/118429179-abcc2600-b703-11eb-9114-7e95f0c112da.png)

**Comment by dashpole** [comment]
The error message in https://github.com/kubernetes/kubernetes/issues/101894#issuecomment-844405409 makes me think the apiserver is not available during that test run: `error waiting for scheduler pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods metrics-proxy:10259)`.  Can someone link to the frequency graphs to see if the problem is widespread?

**Comment by ehashman** [comment]
@dashpole got it: https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=MetricsGrabber%20should%20grab%20all%20metrics%20from%20a%20Scheduler

**Comment by dashpole** [comment]
I don't think I was right above.  I think the "the server is currently unable to handle the request" is an error coming from the proxy.  The proxy was added around the time this issue was filed (https://github.com/kubernetes/kubernetes/pull/96216), so it seems likely to be related to it.

@knight42 can you take a look?

**Comment by knight42** [comment]
@dashpole This is a known issue, and @pohly is working on it #102050. 

Now that #102050 is being blocked by the debugging handler problem, could we merge #101960 to mitigate this problem first? cc @pohly @aojea

**Comment by pohly** [comment]
I would prefer to reach a decision about enabling the debug handlers, but if that's not possible, then merging PR #101960  as mitigation might make sense.

**Comment by dashpole** [comment]
It appears to still be failing based on https://github.com/kubernetes/kubernetes/issues/101894#issuecomment-849065294.  If you are coming here after seeing a flake, rebase your PR to pick up #101960, and see if that fixes it.

**Comment by pohly** [comment]
Why rebase? Any new test run will be based on merge with current k/k master and thus contain https://github.com/kubernetes/kubernetes/pull/101960.

**Comment by knight42** [comment]
<img width="1111" alt="Screen Shot 2021-05-28 at 13 04 52" src="https://user-images.githubusercontent.com/4237254/119932195-62a68c80-bfb5-11eb-9971-488a6dad23af.png">

@dashpole looks like it has become more stable now.
