### ISSUE TITLE
ContainerLabels not contains pod labels, but SandboxLabels contains pod labels

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#101829]
#### What happened:

When we read the container's config.v2.json or `docker inspect` some containers, I cannot get the enough labels on container's config.v2.json.

But all pod labels can be found on sandbox container.

this is the code about create sandbox container.
![image](https://user-images.githubusercontent.com/28707161/117536346-1a86f080-b02d-11eb-96df-24fe0af53ff0.png)

this is the code about create normal container.
![image](https://user-images.githubusercontent.com/28707161/117536348-207cd180-b02d-11eb-9606-d782b088e3a5.png)

#### What you expected to happen:

What is the difference between sandbox container and normal containers?  I think all pod labels can be added to every container.

#### How to reproduce it (as minimally and precisely as possible):
None

#### Environment:
- Kubernetes branch: master

**Comment by Nebulazhang** [comment]
Our log agent may need to inspect container in order to get pod labels information, and upload logs with labels or depends on some labels. So we need to  get the enough labels on container's spec

**Comment by SergeyKanzhelev** [comment]
Can you please expand on the use case - why all labels are needed

**Comment by haircommander** [comment]
@Nebulazhang is this still needed? if so, can you add tests as requested by @SergeyKanzhelev

**Comment by pacoxu** [comment]
As I know, some node agent uses `docker inspect` to get container information and sometimes want to retrieve pod labels.

I would suggest to use `crictl inspect`  instead to get pod info directly.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind support

workaround is to use `crictl`. Closing, please re-open if needed
