### ISSUE TITLE
Load balancing does not work correctly when scale pod

### ISSUE THREAD

**Issue by TinyWhite1997** [kubernetes/kubernetes#101887]
#### What happened:
When I performed a stress test on nginx, the nginx deployment scaled, but the newly created nginx pod did not have any load. If I stop the stress test for two minutes, all pods will start working normally. As shown in the picture below:
![image](https://user-images.githubusercontent.com/49556810/117745037-4d530380-b23c-11eb-8a59-8aa17e50411c.png)

#### What you expected to happen:
Once the pod is created and running through hpa, it can participate in load balancing normally.
#### How to reproduce it (as minimally and precisely as possible):
Create bitnami/nginx use helm:
`# helm get values nginx -ntest-p1
USER-SUPPLIED VALUES:
autoscaling:
  enabled: false
  maxReplicas: 40
  minReplicas: 1
  targetCPU: 30
  targetMemory: 30
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi`
#### Anything else we need to know?:
My test tool: [http_load](https://acme.com/software/http_load/)
If I start a stress test during scaledown, it told me no route to host err
#### Environment:
- Kubernetes version (use `kubectl version`): v1.18.8-aliyun.1
- Cloud provider or hardware configuration: aliyun
- OS (e.g: `cat /etc/os-release`): Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)
- Kernel (e.g. `uname -a`): Linux  4.19.91-23.al7.x86_64 #1 SMP Tue Mar 23 18:02:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel:v0.11.0.2-g6e46593e-aliyun
- Others:
kube-proxy mode is ipvs, and other config is default.

/sig network
/sig autoscaling

**Comment by TinyWhite1997** [comment]
i find the same issue here [#81775](https://github.com/kubernetes/kubernetes/issues/81775) . it's still open.

**Comment by andrewsykim** [comment]
@TinyWhite1997 is your scale test using TCP or UDP traffic?

**Comment by TinyWhite1997** [comment]
It's TCP. I just use the http_load tool to test nginx service. whether it is ClusterIp or NodePort or LoadBalancer will get the same result. For reference [#81775](https://github.com/kubernetes/kubernetes/issues/81775), it may be an ipvs problem, so I switched to iptables and got the result I wanted.

**Comment by aojea** [comment]
> It's TCP. I just use the http_load tool to test nginx service. whether it is ClusterIp or NodePort or LoadBalancer will get the same result. For reference [#81775](https://github.com/kubernetes/kubernetes/issues/81775), it may be an ipvs problem, so I switched to iptables and got the result I wanted.

so, can we close it @TinyWhite1997 ?

**Comment by TinyWhite1997** [comment]
> > It's TCP. I just use the http_load tool to test nginx service. whether it is ClusterIp or NodePort or LoadBalancer will get the same result. For reference [#81775](https://github.com/kubernetes/kubernetes/issues/81775), it may be an ipvs problem, so I switched to iptables and got the result I wanted.
> 
> so, can we close it @TinyWhite1997 ?

yes

**Comment by aojea** [comment]
awesome, thanks
/close
