### ISSUE TITLE
Docker in AKS 1.19.9

### ISSUE THREAD

**Issue by VictorDC92** [kubernetes/kubernetes#101868]
#### What happened:

I have upgraded my cluster from version 1.18.17 to version 1.19.9. The problem comes from the fact that I have some pods that need the docker.sock and now my container runtime has changed from docker to containerd.

![Captura de pantalla 2021-05-10 145942](https://user-images.githubusercontent.com/80468926/117662919-627a5480-b1a0-11eb-9470-03357cf642d6.png)

#### What you expected to happen:

I need to use docker in version 1.19.9. Is there any way to continue using it? Can I change my container runtime to docker in this version of kubernetes? Or change the node image version?

If so, how can I do it?

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.9
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Linux / Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-1046-azure
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by VictorDC92** [comment]
@pacoxu I have updated my cluster using Azure and Terraform. The problem comes that I change the runtime container to containerd and I need it to be docker.

**Comment by neolit123** [comment]
> I have some pods that need the docker.sock

this is a relevant note:

>> One thing to note: If you are relying on the underlying docker socket (/var/run/docker.sock) as part of a workflow within your cluster today, moving to a different runtime will break your ability to use it. This pattern is often called Docker in Docker. There are lots of options out there for this specific use case including things like kaniko, img, and buildah.

https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

this doesn't seem like an issue in k8s core.
you can try getting support from AKS or the k8s support channels:

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
