### ISSUE TITLE
scheduler_perf: add detailed description about op data type in benchmark test's configration

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#101849]
Hi team!

#### What would you like to be added:

Now, README currently asks the users to browse scheduler_perf_test.go to see `op` data type implementation for benchmark test's configration.

https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler_perf/README.md#how-to-configure-benchmark-tests

I would like to add documentation on this, what types of `op` exist, and how to use each `op` data types for configration.

#### Why is this needed:

This is not user-friendly, I think.

**Comment by Huang-Wei** [comment]
> I would like to add documentation on this, what types of `op` exist, and how to use each `op` data types for configration.

Sure, feel free to raise a PR updating the doc.

**Comment by sanposhiho** [comment]
Okey thanks 😊 
/assign

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

I'll do it after some new op created 
- https://github.com/kubernetes/kubernetes/pull/101854
- https://github.com/kubernetes/kubernetes/pull/101835
