### ISSUE TITLE
Optimize NodeVolumeLimits scheduler plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#101803]
The NodeVolumeLimits filter currently recomputes the volume count on the node for each incoming pod, we should cache that in the scheduler's nodeInfo like we do for other resources (memory, cpu etc.).

Also, it seems some of the checks in the filter are agnostic to the node (like checking the incoming pod PVC and computing its volume count); those can be factored out into a PreFilter instead of redundantly doing them for each node.

/sig scheduling

/cc @msau42 @cofyc wdyt?

**Comment by msau42** [comment]
I think those are good improvements.

I remember we actually did try prototyping caching of the volume count, but didn't actually find improvement in benchmarks. I'm not able to find the issue though where we posted the results. @jsafrane @bertinatto do you remember?

For now, I think we could target some of the Prefilter enhancements

**Comment by msau42** [comment]
@kubernetes/sig-storage-feature-requests

**Comment by sanposhiho** [comment]
Hello, I want to take this one.
/assign

**Comment by sanposhiho** [comment]
> I remember we actually did try prototyping caching of the volume count, but didn't actually find improvement in benchmarks. I'm not able to find the issue though where we posted the results.

This issue shows two optimizations, (1)volume count caching and (2)pre-calculating with PreFilter, does this discussion conclude that the former(1) does not need to be done?

I've created a PR for the latter(2) for now. #102235

**Comment by jyz0309** [comment]
@msau42 @sanposhiho Hello! I want to know that the former(1) need to be done or not? Actually I am interested in this issue, and want to try the volume count cache :)

**Comment by msau42** [comment]
I remember we thought about caching the volume count previously and the benchmark analysis did not show the volume counting as the bottleneck. However I'm not able to find the issue/PR with the links to the tests and results anymore. If you would like to help with adding a new benchmark test and performance analysis, that would be greatly appreciated!

**Comment by jyz0309** [comment]
Hello! Actually I am new to the community...So if you can give me some advice about how to add it, or where to start. It will be very helpful to me and greatly appreciated!

**Comment by haosdent** [comment]
@sanposhiho can ping me if your pull request is ready, would like to help to review.

**Comment by sanposhiho** [comment]
@haosdent 
Thanks. I rebased the PR.

**Comment by sanposhiho** [comment]
https://github.com/kubernetes/kubernetes/pull/102235#issuecomment-1008068308

/close
