### ISSUE TITLE
Scheduler scheduled pods to a deleted node

### ISSUE THREAD

**Issue by saurap** [kubernetes/kubernetes#101872]
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14", 
1. A node that was active in the cluster was removed as part of our scaling thresholds. 
2. The node was removed from Azure VMSS and removed from cluster inventory as well. 
The log: node_tree.go:113] Removed node "worker2-scus-prod-a7-vmss0000m0" in group "southcentralus:\x00:2" from NodeTree
3. However almost after 20hours, an application hpa triggered a scaleup event. The new pods were somehow assigned to the non-existing (the deleted node from above). 
Few pods had the deleted node under the "NOMINATED NODE" and empty "NODE" section for "kubectl get pods -o wide. While describing the pod we saw event: "Warning  FailedScheduling  11m   default-scheduler  0/66 nodes are available: 10 node(s) had taints that the pod didn't tolerate, 56 Insufficient cpu." 
4. I had to restart kube-scheduler which fixed the issue on its own after that by assigning pods to existing nodes. The logs on the scheduler around that time are only "factory.go:494] pod is already present in the activeQ" which I could not relate to anything. 

I was going over https://github.com/kubernetes/kubernetes/issues/94437 which sound familiar. And at the bottom of it, it reads "We just retried with 1.18.8 and the issue is still there (same symptom)." Since I am on 1.17.14, I thought I will open this here.

**Comment by neolit123** [comment]
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.14",

< 1.19 is out of support.

> The node was removed from Azure VMSS and removed from cluster inventory as well.

try asking Azure for support.
if this is confirmed as a 1.19+ bug, you can open a new issue here.

/close
/kind support

**Comment by neolit123** [comment]
alternatively you can ask other users in the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
