### ISSUE TITLE
Scheduler fails to schedule due to cyclic errors on pod forget and assume

### ISSUE THREAD

**Issue by zorro786** [kubernetes/kubernetes#101877]
#### What happened:
Found several pending pods in scheduler queue and they failed due to:

```
E0510 11:08:36.825986       1 framework.go:777] "Failed running Bind plugin" err="Operation cannot be fulfilled on pods/binding \"test-pod-6b9b7db86c-rjr4m\": rpc error: code = Unavailable desc = transport is closing" plugin="DefaultBinder" pod="test-namespace/test-pod-6b9b7db86c-rjr4m"
E0510 11:08:36.826066       1 scheduler.go:586] scheduler cache ForgetPod failed: pod c79ffa51-1b35-4eb6-8e09-783fad5fb5bf wasn't assumed so cannot be forgotten
...
...
E0510 11:08:38.107538       1 scheduler.go:367] scheduler cache AssumePod failed: pod c79ffa51-1b35-4eb6-8e09-783fad5fb5bf is in the cache, so can't be assumed
```

#### What you expected to happen:
Expected the pod to be scheduled/assumed on retry as it was not added in cache per message "wasn't assumed so cannot be forgotten" previously.
In other words, expected `schedulerCache.assumedPods` & `schedulerCache.podStates` to be always in sync.

#### How to reproduce it (as minimally and precisely as possible):
Not sure

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.2
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): Ubuntu 16.04.7 LTS

**Comment by zorro786** [comment]
CC: @Huang-Wei @ahg-g

**Comment by zorro786** [comment]
@ahg-g It is native scheduler without any mods. I think you have wrong commit for release 1.20.

https://github.com/kubernetes/kubernetes/blob/v1.20.2/pkg/scheduler/scheduler.go#L586
Commit ID for 1.20.2 tag: https://github.com/kubernetes/kubernetes/commit/faecb196815e248d3ecfb03c680a4507229c2a56

What I am using:
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Yes it is for the same pod, `uid` is being used as key in cache.
I have several such errors in logs captured across different pods
Another info that might help is that several pods were force deleted before the above ones were deployed.

**Comment by zorro786** [comment]
No

**Comment by Huang-Wei** [comment]
> Another info that might help is that several pods were force deleted before the above ones were deployed.

Did you force deleting scheduled Pods or unscheduled Pods? do they have the same Pod names as the new deploy ones?

**Comment by zorro786** [comment]
> Did you force deleting scheduled Pods or unscheduled Pods? do they have the same Pod names as the new deploy ones?

Both scheduled and unscheduled; about 90% of them scheduled; they all belong to deployments. Names are deterministic but different pod ids would be assigned to them by K8s so highly improbable to have same names for several pods I saw errors with in logs (400+).

**Comment by baxiaoshi** [comment]
This problem is because the pod of the same uid is deleted?

**Comment by zorro786** [comment]
> This problem is because the pod of the same uid is deleted?

It is very unlikelyfor collisions in uid. Also it's not a single uid but several so this can be ruled out.

**Comment by ltagliamonte-dd** [comment]
seeing the same problem on:
```
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
