### ISSUE TITLE
konnectivity network proxy tests e2e tests failing

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#101879]
#### Which jobs are failing:

https://k8s-testgrid.appspot.com/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-http-connect
https://k8s-testgrid.appspot.com/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-grpc

#### Anything else we need to know:

Konnectivity network proxy tests have been failing since 5/7/2021.

Looking at the diff of changes it seems like it's related to running the control plane as non root. (https://github.com/kubernetes/kubernetes/compare/1f3fd1cb8...ca0c04e4d?)

cc @vinayakankugoyal, is there anything that needs to be changed on the konnectivity network proxy to support this? The proxy component communicates with the apiserver with a UDS socket.

This is the error we're seeing in the tests:

```
 error dialing backend: dial unix /etc/srv/kubernetes/konnectivity-server/konnectivity-server.socket: connect: permission denied
```

/sig api-machinery
/sig cloud-provider

**Comment by aojea** [comment]
/reopen

The status of these jobs is still completely red https://testgrid.k8s.io/sig-api-machinery-network-proxy#Summary

:thinking: the fix merged with the job `pull-kubernetes-e2e-gce-network-proxy-grpc`  failing, maybe is unrelated but we should have the jobs green.

**Comment by aojea** [comment]
the http job was been fixed but the grpc job still fails, most errors have the following message

```
Command stdout:

stderr:
Error from server: error dialing backend: dial timeout

error:
```
https://testgrid.k8s.io/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-grpc&width=5

**Comment by aojea** [comment]
@Jefftree can you please take a look to the grpc one to see if is the same issue or a new one?
