### ISSUE TITLE
Expose container start time in kubelet /metrics/resource endpoint

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#101851]
KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/727-resource-metrics-endpoint introduced a new Kubelet /metrics/resource endpoint  as a replacement for Summary API. When working on design to switch Metrics Server to `/metrics/resource` endpoint I found some problems with CPU metric.

This endpoint exposes cumulative CPU usage metrics for each container. To calculate usage of CPU users need to scrape this endpoint twice and calculate the differential. In current state this API has two major problems:
* Detection of container restarts
* Delay in metrics for fresh containers

#### Detection of container restarts

Container restarts cause reset of cumulative metric, but they cannot be reliably detected by api users. If container restarted between metric collection, agent will either calculate negative usage or much lower then real usage. Addressing this issue requires API to be extended to allow users to detect that there was a container restart since previous API call, allowing it to discard recorded value.

Issue in Metrics Server repo: https://github.com/kubernetes-sigs/metrics-server/issues/745

#### Delay in metrics for fresh containers

Metrics Server collects metrics once a minute (as for v0.4.X), for long running containers Metrics Server can use previous samples to calculate usage. For fresh containers previous sample is not available, so it can up to 2 full metric collection periods to be able to return metric. For Metrics Server default period being 1 minute it can take up to 2 minutes since container started to get information about it's CPU usage. This has really negative impact on process of scaling up replicas using HPA, as it adds additional minute to each cycle. As targeted CPU usage is usually around 70%, it means that on one scale up number of replicas can grow only by 40%. To growing replicas 2x requires multiple scaling decisions, each of them needing to wait for metrics from new containers. 

Issue in Metrics Server repo: https://github.com/kubernetes-sigs/metrics-server/issues/747

### Proposal

Add new metrics Kubelet to /metrics/resource endpoint to provide information about the start time of container. Node metrics are not required due to differences in node lifecycle.
```
# Start time of container in UNIX time
Name: container_start_time
Labels: container, pod, namespace
```

With this metric it is possible to remove both aforementioned problems. First it allows to detect container restart as a container start time change. Second it allows to speed up metrics for fresh containers, as we can assume that CPU cumulative usage using start time was equal 0.

/sig node
/cc @dashpole
/sig instrumentation

**Comment by yangjunmyfm192085** [comment]
need help?@serathius
We can do it.@sanwishe

**Comment by yangjunmyfm192085** [comment]
> /assign

I have assigned, thank you very much
/unassign lengrongfu

**Comment by serathius** [comment]
Currently this is a proposal. We need to discuss it with SIG Node to get agreement on design.

**Comment by yangjunmyfm192085** [comment]
> Currently this is a proposal. We need to discuss it with SIG Node to get agreement on design.

yes, we will wait for the result of  proposal.

**Comment by lengrongfu** [comment]
> /assign

Okay, can we do it together?

**Comment by yangjunmyfm192085** [comment]
> > /assign
> 
> Ok, can we do it together? @yangjunmyfm192085
I think the work is not heavy, If have heavy tasks,  Welcome to join us do it together!

**Comment by dashpole** [comment]
I think this proposal is the right way forward.  The only other solution I can think of would be to have the MS watch pods and nodes, but that seems heavy-weight for this problem, and will have race conditions.

**Comment by serathius** [comment]
/help 
Will not have time to work on this. Feel free to grab it.

**Comment by yangjunmyfm192085** [comment]
@serathius Can we start this work?

**Comment by serathius** [comment]
I have already discussed it on SIG Instrumentation meeting, Would be good to present this issue on SIG Node meeting and get their opinion, before starting coding. Would you be interested in leading the discussion?

**Comment by yangjunmyfm192085** [comment]
ok, Let me prepare it.

**Comment by ehashman** [comment]
We discussed this during SIG Node today. There was consensus that we should definitely add the container start time metrics and that this would be useful.

There were questions about the node start time. It's unclear how it would be defined (node boot time? first time kubelet is marked NodeReady? something else?) and how it would be used. From my reading of the original comment, the node start time is currently optional and it's not clear what it would be used for.

My recommendation would be to leave node start time off for now. Let's discuss further at SIG Instrumentation this week (note: I can't attend) or here on the issue if we want to make a case to SIG Node for its inclusion? @serathius

**Comment by serathius** [comment]
Skipping start time for nodes make sense. Will remove it from original proposal.

**Comment by MadhavJivrajani** [comment]
/remove-kind design
/kind feature

`kind/design` will soon be removed from `k/k` in favor of `kind/feature`. Relevant discussion can be found here: https://github.com/kubernetes/community/issues/5641

**Comment by serathius** [comment]
PR with implementation was merged.
