### ISSUE TITLE
Survey on GDSE

### ISSUE THREAD

**Issue by WybeKoper** [kubernetes/kubernetes#101850]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by neolit123** [comment]
/close

this is better communicated on the user channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
