### ISSUE TITLE
Suppressing the warning "tar: removing leading '/' from member names" with cp command. 

### ISSUE THREAD

**Issue by joshi95** [kubernetes/kubernetes#101891]
#### What you expected to happen:  

It should have run silently without the message. 

#### How to reproduce it (as minimally and precisely as possible):

Step 1. Create a file inside a pod (eg. my-pod)

> kubectl exec -it my-pod -- touch /test.csv

Step 2. Copy the file to local from the pod.

> kubectl cp my-pod:/test.csv /test.csv (source has a forward slash) 

Raises: 

> tar: removing leading '/' from member names

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration: local machine
- OS (e.g: `cat /etc/os-release`): MacOS
- Kernel (e.g. `uname -a`): Darwin
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by joshi95** [comment]
I can pick this up. If it is approved.

**Comment by eddiezane** [comment]
There's CVE history for `kubectl cp`. I don't think we want to suppress any warning messages.

Efforts to improve it should be put towards https://github.com/kubernetes/kubernetes/issues/58512

**Comment by eddiezane** [comment]
@soltysh @tallclair if y'all disagree feel free to reopen.

/triage unresolved
/close
