### ISSUE TITLE
link file _output/bin is broken

### ISSUE THREAD

**Issue by wangyysde** [kubernetes/kubernetes#101821]
#### What happened:
When we run scripts in hack subpath, they are create a link file named bin in _output subpath which pointing to _output/local/bin/${platform}. But all the binaries have been output into _output/dockerized/bin/ and the subpath _output/local/bin is not exist normally.And there are many scripts in hack are using _output/bin subpath. 

#### What you expected to happen:
Correct the pointing of the _output/bin to _output/dockerized/bin

#### How to reproduce it (as minimally and precisely as possible):
1. unlink _output/bin if it is existing.
2. run hack/verify-description.sh.
3. ls -l  _output/bin

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.6.1810 (Core) 
- Kernel (e.g. `uname -a`):  3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by SataQiu** [comment]
IMO, you should run `make all` instead of `hack/verify-description.sh`.

**Comment by wangyysde** [comment]
@SataQiu .Thanks. I run  hack/verify-description.sh following #99675.  The link file _output/bin be created in kube::golang::place_bins function in hack/lib/golang.sh script. Then the hack/lib/golang.sh be called by verify-e2e-test-ownership.sh.  I think that the script verify-e2e-test-ownership.sh is for e2e test,and there are many scripts in hack are using _output/bin subpath. I think that we should correct this subpath.

**Comment by BenTheElder** [comment]
"dockerized" is only in the path when things are built inside docker. binaries can also be built on the host.

**Comment by BenTheElder** [comment]
There's no guarantee that all files are built with a single method. Sometimes an invocation will build both (images currently always used dockerized binaries, so builds with image can have both).

The script should not be relying on adding this to PATH or whatever, we have kube::until::find-binary and other ways to avoid depending on fixed paths.

**Comment by wangyysde** [comment]
Thanks.
