### ISSUE TITLE
[arm64] several e2e storage testcases are failed due to the ceph is not ready

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#101967]
#### What happened:
When I run some e2e storage testcases locally, below testcases as an example, 

```
[sig-storage] In-tree Volumes [Driver: ceph][Feature:Volumes][Serial] [Testpattern: Pre-provisioned PV (default fs)] subPath should fail if subpath with backstepping is outside the volume [Slow][LinuxOnly]
```

I consistently saw the below error message, 

```FAIL: Failed to find "Ceph is ready" in pod logs: Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
    Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
      May 11 16:55:33.525: Failed to find "Ceph is ready" in pod logs: Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
          Failed to find "Ceph is ready", last result: "monmaptool: monmap file /etc/ceph/monmap
```

#### What you expected to happen:
ceph should be deployed successfully and testcase should pass.

#### How to reproduce it (as minimally and precisely as possible):
Run the testcases mentioned above.

e.g.
```
/usr/bin/e2e.test -ginkgo.focus="In-tree Volumes \[Driver: ceph\]\[Feature:Volumes\]\[Serial\] \[Testpattern: Pre-provisioned PV \(default fs\)\] subPath should fail if subpath with backstepping is outside the volume \[Slow\]\[LinuxOnly\]"  -provider=local
```

#### Environment:
- Kubernetes version (use `kubectl version`): ALL
- Cloud provider or hardware configuration: ARM64
- OS (e.g: `cat /etc/os-release`): ubuntu18
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
is this happening in CI? please provide links to occurences?

**Comment by chendave** [comment]
> is this happening in CI? please provide links to occurences?

Hey, Ben, 

I update the issue description a little bit, this won't be an issue on X86 which is currently the default arch CI is running, but tons of testcases will fail on ARM64 due to this issue.

Eventually, we hope the k8s will have a ARM CI along with the more adoption of arch beside the X86, and thus, those e2e testcases should workable on ARM64 firstly.

I will explain why it failed on ARM64 in the PR desc, pls help to review, thanks!
