### ISSUE TITLE
controllerManager cluster-signing-duration  configuration does not take effect

### ISSUE THREAD

**Issue by ztgoto** [kubernetes/kubernetes#101965]
#### What happened:
sudo kubeadm init --config=./config-init.yaml
```
controllerManager:
  extraArgs:
    "cluster-signing-duration": "87600h0m0s"
    "feature-gates": "RotateKubeletServerCertificate=true"
    "cluster-signing-cert-file": "/etc/kubernetes/pki/ca.crt"
    "cluster-signing-key-file": "/etc/kubernetes/pki/ca.key"
```
The cluster-signing-duration is configured for 10 years

/var/lib/kubelet/config.yaml
```
rotateCertificates: true
```

But the actual situation certificate is only one year
```
sudo kubeadm  certs check-expiration

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 May 13, 2022 06:35 UTC   364d                                    no      
apiserver                  May 13, 2022 06:35 UTC   364d            ca                      no      
apiserver-kubelet-client   May 13, 2022 06:35 UTC   364d            ca                      no      
controller-manager.conf    May 13, 2022 06:35 UTC   364d                                    no      
front-proxy-client         May 13, 2022 06:35 UTC   364d            front-proxy-ca          no      
scheduler.conf             May 13, 2022 06:35 UTC   364d                                    no      

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      May 03, 2041 10:39 UTC   19y             no      
front-proxy-ca          May 03, 2041 10:39 UTC   19y             no
```

#### What you expected to happen:
I hope the time configured by cluster-signing-duration will take effect

#### Environment:
- Kubernetes version (use `kubectl version`):  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by neolit123** [comment]
there is a duplicate issue from the past about this.

--cluster-signing-duration does not control the signing duration of certificate that the kubeadm CA key signs directly without controllers. the flag only controls the duration for certificates signed by the kube-controller-manager. such a certficate would be the kubelet client certficate when a node joins a cluster.

> But the actual situation certificate is only one year

kubeadm does not allow you to modify the certificate duration of 1 year. you have two options:
- fork kubeadm and modify https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/constants/constants.go#L49
- see `kubeadm certs generate-csr`:
  - you can use kubeadm to generate CSRs
  - sign the CSRs to create certificates with the duration you want

/close
/kind support
