### ISSUE TITLE
[Flaking Test] [sig-node] ConfigMap should be consumable via the environment

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/kubernetes#101906]
#### Which jobs are flaking:
[gce-windows-2004-master](https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master)

#### Which test(s) are flaking:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1391881191962972160

#### Testgrid link:

- [[sig-node] ConfigMap should be consumable via the environment [NodeConformance] [Conformance]](https://testgrid.k8s.io/sig-release-master-informing#gce-windows-2004-master)
-  [sig-node] Pods should support remote command execution over websockets [NodeConformance] [Conformance] 
-  [sig-node] Downward API should provide host IP as an env var [NodeConformance] [Conformance] 
- [sig-node] Downward API should provide pod UID as env vars [NodeConformance] [Conformance] 
- [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop http hook properly [NodeConformance] [Conformance] 

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
May 10 23:11:52.534: Unexpected error:
    <*errors.errorString | 0xc002da4860>: {
        s: "failed to get logs from pod-configmaps-2bca97c5-e660-4d04-8df3-819e5d5209b6 for env-test: an error on the server (\"unknown\") has prevented the request from succeeding (get pods pod-configmaps-2bca97c5-e660-4d04-8df3-819e5d5209b6)",
    }
    failed to get logs from pod-configmaps-2bca97c5-e660-4d04-8df3-819e5d5209b6 for env-test: an error on the server ("unknown") has prevented the request from succeeding (get pods pod-configmaps-2bca97c5-e660-4d04-8df3-819e5d5209b6)
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:742
```

#### Anything else we need to know:
- [spyglass](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-windows-gce-2004/1391881191962972160)

**Comment by SergeyKanzhelev** [comment]
/assign @ehashman 

to validate whether it is flaking or not

**Comment by ehashman** [comment]
/triage accepted

https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=failed%20to%20get%20logs&test=ConfigMap%20should%20be%20consumable%20via%20the%20environment

Doesn't really appear to be flaking today but there are a few flakes.

**Comment by ehashman** [comment]
/unassign
/sig windows

It appears this is primarily failing on Windows. (thanks @cynepco3hahue for noticing!)

**Comment by dims** [comment]
all the configmap ones seem to be green now
https://testgrid.k8s.io/sig-windows-gce#gce-windows-2004-master&include-filter-by-regex=ConfigMap

leaving this open if sig-windows wants to chase others.

/milestone clear
