### ISSUE TITLE
Services should be able to create a functioning NodePort service for Windows failing

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#101907]
#### Which jobs are flaking:
https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master
#### Which test(s) are flaking:
[sig-windows] Services should be able to create a functioning NodePort service for Windows
#### Testgrid link:
https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master
#### Reason for failure:
  `s: "command terminated with exit code 7",`
#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by jsturtevant** [comment]
run that failed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1391546999131607040

**Comment by ravisantoshgudimetla** [comment]
Another run that failed but with a different exit code:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-21-windows-containerd/1399281231979352064

**Comment by ravisantoshgudimetla** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-19-windows/1395958415271923712

**Comment by marosset** [comment]
/close
This is a dupe of #98499
