### ISSUE TITLE
[Failing test] k8s.io/legacy-cloud-providers/vsphere TestSecretUpdated

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#101927]
##### Error text:
```
=== RUN   TestSecretUpdated
/tmp/go-build2183127444/b5733/vsphere.test flag redefined: log_dir
--- FAIL: TestSecretUpdated (0.05s)
panic: /tmp/go-build2183127444/b5733/vsphere.test flag redefined: log_dir [recovered]
	panic: /tmp/go-build2183127444/b5733/vsphere.test flag redefined: log_dir

goroutine 1848 [running]:
testing.tRunner.func1.2(0x2a1d100, 0xc000a30250)
	/usr/local/go/src/testing/testing.go:1143 +0x49f
testing.tRunner.func1(0xc000560300)
	/usr/local/go/src/testing/testing.go:1146 +0x695
panic(0x2a1d100, 0xc000a30250)
	/usr/local/go/src/runtime/panic.go:971 +0x499
flag.(*FlagSet).Var(0xc00012a180, 0x32a2d28, 0x449fcb0, 0x2eb0fd6, 0x7, 0x2f2c182, 0x2f)
	/usr/local/go/src/flag/flag.go:871 +0x637
flag.(*FlagSet).StringVar(...)
	/usr/local/go/src/flag/flag.go:760
k8s.io/kubernetes/vendor/k8s.io/klog/v2.InitFlags(0x0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:427 +0xfb
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere.TestSecretUpdated(0xc000560300)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere_test.go:1209 +0x58a
testing.tRunner(0xc000560300, 0x2fca618)
	/usr/local/go/src/testing/testing.go:1193 +0x203
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x5d8

```
#### Recent failures:
[5/11/2021, 9:25:38 AM ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1392153616399208448)
[5/11/2021, 3:25:18 AM ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1392062891410067456)
[5/10/2021, 9:25:56 PM ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1391972293101490176)
[5/10/2021, 3:25:43 PM ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1391881696697126912)
[5/10/2021, 9:25:30 AM ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1391791097046372352)

/kind failing-test
/kind flake
/sig cloud-provider
/area provider/vmware

Flaked on https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/101919/pull-kubernetes-unit/1392207748908716032

Is this the same issue as https://github.com/kubernetes/kubernetes/issues/98941 ?

**Comment by pacoxu** [comment]
/assign @mengjiao-liu 
There seems to be a data-race here.
```
=== RUN   TestSecretUpdated
W0511 20:30:10.965504   98005 vsphere.go:339] Global.User and Secret info provided. VCP will use secret to get credentials
W0511 20:30:10.965607   98005 vsphere.go:343] Global.Password and Secret info provided. VCP will use secret to get credentials
==================
WARNING: DATA RACE
Read at 0x0000044a1cda by goroutine 6:
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).header()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:605 +0x16c
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:737 +0x69
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.Errorf()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1463 +0x4bc
  k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vclib.(*VSphereConnection).Logout()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vclib/connection.go:169 +0x413
  k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere.logout()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere.go:561 +0x139

Previous write at 0x0000044a1cda by goroutine 85:
  flag.newBoolValue()
      /usr/local/go/src/flag/flag.go:112 +0x3c5
  flag.(*FlagSet).BoolVar()
      /usr/local/go/src/flag/flag.go:630 +0x3d1
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.InitFlags()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:435 +0x39b
  k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere.TestSecretUpdated()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vsphere_test.go:1209 +0x589
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Goroutine 6 (running) created at:
  runtime.createfing()
      /usr/local/go/src/runtime/mfinal.go:156 +0x64
  os.NewFile()
      /usr/local/go/src/os/file_unix.go:106 +0x72
  os.init()
      /usr/local/go/src/os/file.go:64 +0x41e

Goroutine 85 (running) created at:
=== CONT  TestSecretUpdated
    testing.go:1092: race detected during execution of test
--- FAIL: TestSecretUpdated (0.14s)
```

**Comment by mengjiao-liu** [comment]
https://github.com/kubernetes/kubernetes/issues/101927

There's a finalizer [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L512) that trips up the test case. 

vsphere_test.go TestSecretUpdated `klog.InitFlags(nil)` set flag `logging.addDirHeader` and  `k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/vsphere/vclib.(*VSphereConnection).Logout() ` read from `loggingT.addDirHeader`
https://github.com/kubernetes/kubernetes/blob/e8cf412e5ec70081477ad6f126c7f7ef7449109c/vendor/k8s.io/klog/v2/klog.go#L605

so when the logout read  and the test is write the ` addDirHeader`,they lead to `data race`



I came up with a mutex where the klog library reads `logging.addDirHeader`
```
			l.mu.Lock()
			if l.addDirHeader {
				if dirsep := strings.LastIndex(path[:slash], "/"); dirsep >= 0 {
					file = path[dirsep+1:]
				}
			}
			l.mu.Unlock()
```

Or a lock on the kubernetes vsphere logout function.

Any better suggestions?

/cc@dims @liggitt @pacoxu

**Comment by liggitt** [comment]
> There's a finalizer [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L512) that trips up the test case.

the use of a runtime finalizer is suspect... that's the only use in our codebase and makes unit testing really hard.

also, the use of the global logger in TestSecretUpdated is suspect... the code under test should be structured to allow testing the results without plumbing through the global logger

**Comment by jonyhy96** [comment]
Since the test is still failed, pick up at #106584 /cc @andrewsykim
