### ISSUE TITLE
E2E Node flags organization

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#101986]
#### What would you like to be added:

Remove specific node configuration flags from the main `framework.TestContext` struct, they do share a lot of code but have different bootstrap approaches, and flags are oddly distributed across the test framework.  (some examples in the xref file).

#### Why is this needed:
To fix the lack of standardization in the addition of new flags and ensure proper separation of concern between both test suites.

Document and enumerate the available flags, organizing them to be consumable in a consistent interface, facilitating the usage, and providing a standardized development experience.

WIP xref:

https://docs.google.com/document/d/1_lvtCz-Qdl1zVEe5cBfTyt4fZXXhximh0wRR5TajJRg

**Comment by wesleyw72** [comment]
@knabben I'm interested in picking this up but I don't fully understand the task. From what I understand, the main piece of work is moving the Node flags out of `TestContext` and put them into a node e2e test specific location as suggested here: https://github.com/kubernetes/kubernetes/pull/97028/files#r617106781 . 

Is that correct or have I misunderstood?

**Comment by knabben** [comment]
@wesleyw72 Correct, this is mostly the main idea but needs more discussion around the new structure.

It Can be a good idea to spec out a proposal and bring to the SIG node CI meeting.

/cc @SergeyKanzhelev @ehashman
