### ISSUE TITLE
When referencing a package named "github.com/mrunalp/fileutils", ci found that there are two variables undefined

### ISSUE THREAD

**Issue by lunhuijie** [kubernetes/kubernetes#101970]
#### What happened:
I wrote a test case and referenced this package（github.com/mrunalp/fileutils） to copy the folder，the function is fileutils.CopyDirectory. CI reported an error.
![image](https://user-images.githubusercontent.com/45219809/118100646-45948a00-b409-11eb-9348-425e0ff43b10.png)

#### What you expected to happen:
CI pass without "pull-kubernetes-typecheck — Job failed."
#### Anything else we need to know?:
More details:
https://github.com/kubernetes/kubernetes/pull/101959
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lunhuijie** [comment]
@mrunalp I read the relevant source code and found that there is a definition. So why is CI but could you help me take a look? 
I would be very grateful for your help!

**Comment by HongjiangHuang** [comment]
[Here](https://github.com/kubernetes/kubernetes/tree/master/test/typecheck) detect [fileutils](https://github.com/mrunalp/fileutils/blob/master/fileutils.go) package not support windows-386 and windows-arm

**Comment by BenTheElder** [comment]
this is not a bug, it's as mentioned above: typecheck ensures that the kubernetes will compile for all supported platforms by typechecking it.

you must either use cross platform code, or have platform specific versions gated by build tags / platform specific files.

/remove-sig testing
/remove-kind bug
/close
