### ISSUE TITLE
Probing container should *not* be restarted with a tcp:8080

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#101912]
#### Which jobs are flaking:
https://testgrid.k8s.io/sig-windows-signal#gce-windows-2019-1.21
#### Which test(s) are flaking:
Probing container should *not* be restarted with a tcp:8080
#### Testgrid link:
https://testgrid.k8s.io/sig-windows-signal#gce-windows-2019-1.21
#### Reason for failure:
   ```Warning  FailedMount  18m                     kubelet            MountVolume.SetUp failed for volume "kube-api-access-n2tj2" : failed to sync configmap cache: timed out waiting for the condition ```
#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

/sig windows

**Comment by marosset** [comment]
I can't find any recent instances of this failure.
We can reopen if needed.

/close
