### ISSUE TITLE
Question - customizing Service (ClusterIP) load balancer logic

### ISSUE THREAD

**Issue by IAXES** [kubernetes/kubernetes#101994]
Is it possible to override the load balancing logic that Service (i.e. ClusterIP) objects use? For example, I'd like to be able to customize a service that is associated with a deployment that scales up to 2000 pods. Due to the non-uniform setup (i.e. heterogeneous workloads across different types of nodes with different compute capabilities), I'd like to have more control over how requests are routed to different pods running in the cluster.

Is this possible, without resorting to recompiling K8S and modifying the load balancer logic? (i.e. create an operator that implements the appropriate interfaces, extend existing logic rather than re-writing it, etc.). If this isn't the case, are there other approaches that could achieve a similar result?

Thank you.

**Comment by aojea** [comment]
I think that your request is related to the Service Topology topic, the load balancer logic for Service is left to the component that implement the Services logic, that by default is kube-proxy in kubernetes.

Kubernetes exposes fields in the Service and EndpointSlices objects that can be consumed by the implementations to define their own loadbalancing, see [related discussion in the mailing list](https://groups.google.com/g/kubernetes-sig-network/c/IxtD8KYsMeA/m/sbUsY04IAgAJ)

Per example, kube-proxy has a new feature called TopologyHints that allows clients to "prefer endpoints in the same zone", that sounds related to your request, you can see more about this feature in the KEP
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2433-topology-aware-hints

Also, [I've demoed  it during last kubecon,](https://kccnceu2021.sched.com/event/d2243112bdefef102311f38ff7e5c930), check [slides 19-22](https://static.sched.com/hosted_files/kccnceu2021/df/Kubernetes%20_Advanced_Networking_Testing%20_with_KIND_Antonio_Ojea_Kubecon_2021.pdf)

**Comment by IAXES** [comment]
@aojea This is awesome, and exactly what I was looking for. Thanks!

I'm going to close the issue/ticket, as this gives me the "springboard" I need. Hopefully if other people encounter this topic in the future they add their 2 cents to it as well.
