### ISSUE TITLE
Re-enable csi hostpath tests in kind job

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#101913]
#### What happened:
CSI hostpath tests were disabled due to #101275, suspicion is that updating the hostpath sidecars may have increased flakiness of the job.

#### What you expected to happen:
To add the tests back, we need to do further investigation to see if the updates are causing issues. Some current suspicions:
- We added health monitor sidecars, however the version of the hostpath driver does not support health monitoring, so those containers are constantly crashlooping

**Comment by msau42** [comment]
> So while adding pods that need to be restarted increases load unnecessarily, this cannot be the only reason.

It might not be the only reason, but I think it's worth knocking down every issue we find one by one to help us triage further.

**Comment by pohly** [comment]
Testing in https://github.com/kubernetes-csi/csi-driver-host-path/pull/289 also shows a higher rate of test flakes on Kubernetes 1.21 than on 1.20. The driver deployment is exactly the same for both. What is different are the Kubernetes version and the test suite (the job always uses the test suite that matches the Kubernetes version).

There are 7 additional tests that run in 1.21 (120 instead of 113). I've not checked which those additional tests are.

**Comment by mauriciopoppe** [comment]
I run the suite a few times before #100637 with a160d1d and I see lots of flakes!

```
Summarizing 1 Failure:

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] provisioning [It] should provision storage with pvc data source in parallel [Slow]
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:602

Ran 51 of 5769 Specs in 1408.253 seconds
FAIL! -- 50 Passed | 1 Failed | 0 Pending | 5718 Skipped
```

```
Summarizing 6 Failures:

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] provisioning [It] should provision storage with pvc data source
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:602

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] multiVolume [Slow] [It] should access to two volumes with different volume mode and retain data across pod recreation on the same node [LinuxOnly]
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go:679

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] provisioning [It] should provision storage with pvc data source in parallel [Slow]
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:602

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (filesystem volmode)] multiVolume [Slow] [It] should access to two volumes with the same volume mode and retain data across pod recreation on the same node [LinuxOnly]
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go:660

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (immediate-binding)] ephemeral [It] should create read/write inline ephemeral volume
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go:660

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (late-binding)] ephemeral [It] should support two pods which share the same volume
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go:660

Ran 51 of 5769 Specs in 1732.782 seconds
FAIL! -- 45 Passed | 6 Failed | 0 Pending | 5718 Skipped
```

```
Summarizing 2 Failures:

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] provisioning [It] should provision storage with pvc data source
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:602

[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] provisioning [It] should provision storage with pvc data source in parallel [Slow]
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/volume/fixtures.go:684

Ran 51 of 5769 Specs in 1676.008 seconds
FAIL! -- 49 Passed | 2 Failed | 0 Pending | 5718 Skipped

```

**Comment by pohly** [comment]
> I run the suite a few times before #100637 with a160d1d and I see lots of flakes!

So it's not the sidecar update that caused these flakes.

You are running against an old Kubernetes (1.18.17), so it's not a recent regression either.

Can you rule out that driver pods get evicted during a test run (https://github.com/kubernetes-csi/csi-driver-host-path/issues/47)?

**Comment by msau42** [comment]
Flakes have always existed, the claim we're trying to investigate is if things got more flaky after updating the sidecar. I'm not sure individually testing is going to help much here. And from the resource graphs that were collected, I don't see significant resource consumption increases. 

I think at this point our best course of action would be to knock down the latest flakes one by one.

**Comment by mauriciopoppe** [comment]
Sounds good, I'll start with this one as it seems a common flake across all of the tests:

```
[Fail] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] provisioning [It] should provision storage with pvc data source
/usr/local/google/home/mauriciopoppe/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:602
```

**Comment by pohly** [comment]
> I think at this point our best course of action would be to knock down the latest flakes one by one.

Agreed. https://github.com/kubernetes/kubernetes/issues/101911 would be a good start.

**Comment by msau42** [comment]
What do folks think about adding an optional kind CI job with the hostpath tests added back in? We can investigate the flakes there as they come up and make incremental improvements. When the flake rate of that job drops, then we can add the tests back to the blocking job. cc @BenTheElder

**Comment by BenTheElder** [comment]
The hostpath tests were never disabled in CI, unless you're referring to presubmit specifically? In which case +1
The periodic equivilants blocking the release are untouched.

**Comment by msau42** [comment]
Oh, I was referring to https://k8s-testgrid.appspot.com/sig-release-master-blocking#kind-master-parallel specifically thanks! I think we can use this job as a starting point to triage flakes.

**Comment by pohly** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-network-proxy-grpc?buildId=1385142123086483456 started failing close to (at?) merging of #100637 according to
https://github.com/kubernetes/kubernetes/pull/100637#issuecomment-841890515

Could be a coincidence.

/cc @caesarxuchao

**Comment by BenTheElder** [comment]
thank you all for looking into this 🙏 

see discussion here https://github.com/kubernetes/test-infra/pull/22193#issuecomment-848259202 for context on bringing it back, and possible causes
