### ISSUE TITLE
[Flaky test] [sig-network] LoadBalancers should be able to change the type and ports of a TCP service [Slow]

### ISSUE THREAD

**Issue by tosi3k** [kubernetes/kubernetes#101904]
#### Which jobs are flaking:
gce-master-scale-correctness

#### Which test(s) are flaking:
[sig-network] LoadBalancers should be able to change the type and ports of a TCP service [Slow]

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

#### Reason for failure:
Relevant test case is not reported in Prow and is missing in Testgrid:
![image](https://user-images.githubusercontent.com/22770898/117806573-cd886180-b25a-11eb-9a72-8099e17116ec.png)

It seems as if that particular test doesn't manage to finish before the timeout from kubetest kicks in.

#### Anything else we need to know:
Three most recent test job runs that have failed because of that:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1390275642393628672
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1387014109668577280
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1385202017940541440

/kind flake
/sig scalability
/sig network
/cc @kubernetes/sig-network-bugs

**Comment by aojea** [comment]
this is one of the challenges with the Loadbalancer flakes, we have some unknowns that probably will never be able to control ...
the error message is misleading though, is not that ESIPP is not working, is that the connection times out ...

```
May  7 12:51:24.954: INFO: Poke("http://34.73.54.52:80/clientip"): Get "http://34.73.54.52:80/clientip": dial tcp 34.73.54.52:80: i/o timeout
May  7 12:51:24.954: INFO: Poking "http://34.73.54.52:80/clientip"
May  7 12:51:54.955: INFO: Poke("http://34.73.54.52:80/clientip"): Get "http://34.73.54.52:80/clientip": dial tcp 34.73.54.52:80: i/o timeout
May  7 12:51:54.956: INFO: Could not reach HTTP service through 34.73.54.52:80/clientip after 5m0s: timed out waiting for the condition
May  7 12:51:54.956: FAIL: Source IP () is not the client IP even after ESIPP turned on, expected a public IP.
```

we need to be able to know where is the connection drop, where is the client running @BenTheElder in this setup? it is a pod in one of the prow clusters, right?

I think that is something like this 
prow pod -> [???] -> GCP LB -> Cluster under test -> Pod

cc @swetharepakula

**Comment by jkaniuk** [comment]
Still missing occasionally: 
![image](https://user-images.githubusercontent.com/5487158/120193525-d5fe0780-c21c-11eb-9012-c81aaefed9e1.png)

**Comment by jkaniuk** [comment]
@aojea  - any progress on this?

> it is a pod in one of the prow clusters, right?

yes those connections come from test pod in scalability prow cluster

> prow pod -> [???] -> GCP LB -> Cluster under test -> Pod

not sure what [???] would be, is there anything before GCP LB?

**Comment by aojea** [comment]
> @aojea - any progress on this?
> 
> >

I couldn't start yet, hopefully this week I will have some time to work on this

> not sure what [???] would be, is there anything before GCP LB?

yeah, there has to be all the things needed to go from the pod to the LB: internal infrastructure + vpcs + cluster networking ...

**Comment by aojea** [comment]
not failures for 3 weeks, since https://github.com/kubernetes/kubernetes/pull/102533 this merged, I'm going to close it, we can reopen if it fails again
/close
