### ISSUE TITLE
Optimize kube-root-ca.crt watches

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#101969]
#### What would you like to be added:

With BoundServiceAccountTokenVolumes feature, all kubelets started watching 'kube-root-ca.crt' configmap, in each namespace that has a pod running on the given kubelet.

All such configmap has exactly the same data:, usually specified in --root-ca-file flag:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/rootcacertpublisher/publisher.go#L191-L200

It also looks like the data rarely changes (only on kube-controller-manager restart with a different --root-ca-file content)

Improvement request: reduce the number of watches:
* Given all the configmap has exactly the same data, we can simply watch a single configmap, e.g. in kube-system namespace or other, dedicated one?
* Given that we rarely change the content, do we need watches at all? How about GETting the object and refreshing it only when it's close to expiry date?

#### Why is this needed:
'kube-root-ca.crt' watches are responsible for approx. 150k watches in our 5k scalability tests. Maintaining such a number of watches is problematic:
* each such watch must be reinitialized every ~10 minutes
* on master recreation all watches must be recreated on the new master replica etc.
* watches are responsible for most of goroutines active in kube-apiserver

Before BoundServiceAccountTokenVolumes feature, we had the same number of secret watches, but now we see opportunity to improve this and reduce the total number of watches open in the system.

@kubernetes/sig-auth-feature-requests 
@zshihang
@wojtek-t 
@jkaniuk

**Comment by liggitt** [comment]
> * Given all the configmap has exactly the same data, we can simply watch a single configmap, e.g. in kube-system namespace or other, dedicated one?

The injection uses a generic configmap projected volume, this would require special-casing this config map in the kubelet, which I would not expect to do.

> * Given that we rarely change the content, do we need watches at all? How about GETting the object and refreshing it only when it's close to expiry date?

Clients don't know when a new CA will be added as part of a rotation, well ahead of the expiry of any of the certs in the bundle.
