### ISSUE TITLE
unscheduled pods due to mismatched node field has no useful status

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#101957]
#### What happened:

- labelling a pod, with a nonexistent node leads to it being pending forever
- this is ok but... we should  yield any status/events info  so we can know why its not scheduling

#### What you expected to happen:

I'd expect that `kubectl describe` would have explicit misscheduling information when the `node` field was missing.  I think the scheduler probably 'sees' this node, doesnt match it, and thus never assigns the pod to it.  

#### How to reproduce it (as minimally and precisely as possible):

Make a pod such as 
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  nodeName: no-way-this-will-schedule
```

and then run kubectl describe on it

#### Anything else we need to know?:

Heres the 'describe' output...  seems like the scheduler should be firing off an event here... 
```
kubo@jumper:~/path$ kubectl describe pod nginx-deployment-bc6986bd5-s7nzn
Name:           nginx-deployment-bc6986bd5-s7nzn
Namespace:      default
Priority:       0
Node:           kube-01/
Labels:         app=nginx
                pod-template-hash=bc6986bd5
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/nginx-deployment-bc6986bd5
Containers:
  tkg-vc-antrea-control-plane-jkql7:
    Image:        k8s.gcr.io/nginx-slim:0.7
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lnwm9 (ro)
Volumes:
  default-token-lnwm9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lnwm9
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20, but i think also in head

**Comment by Huang-Wei** [comment]
Who sets the .spec.nodeName for the Pod? I suppose it's by a 3rd-party application? If so, it won't go through the regular scheduling process, and hence no events will be generated.

**Comment by jayunit100** [comment]
oh, so , its automatically just 'set' ... ok... 
hmm... whose job is it to report on the fact that this doesnt match a node.
this seems like someone (maybe once of the controller managers?) should
be posting this status somehow

**Comment by Huang-Wei** [comment]
> whose job is it to report on the fact that this doesnt match a node.

Given that any component can set `.spec.nodeName`, IMO the one that sets it should be responsible for reporting this kind of mismatch status.
