### ISSUE TITLE
SSH tunnel controller keeps thinking it's out of sync with the nodes on cluster with no nodes

### ISSUE THREAD

**Issue by a-robinson** [kubernetes/kubernetes#10194]
On a cluster with no nodes, the SSH tunnel code keeps trying to replace tunnels to stay in sync with the "different" nodes, even though it's in a steady state of not having any nodes. The logs below are being logged every second:

```
I0622 20:54:40.731896       6 master.go:837] found different nodes. Need to replace tunnels
I0622 20:54:40.731926       6 master.go:810] replacing tunnels. New addrs: []
E0622 20:54:40.731969       6 master.go:856] Failed to load SSH Tunnels: Failed to open any tunnels.
```

@cjcullen @lavalamp

**Comment by lavalamp** [comment]
Lol-- I'm already making some changes there so I'll fix this. Clusters with no nodes should be rare now and impossible in the future (once we fully self-host).

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
@cjcullen @lavalamp - do either of you know if this issue still exists?

**Comment by cjcullen** [comment]
This is fixed now. I think by https://github.com/kubernetes/kubernetes/pull/19314...
