### ISSUE TITLE
reset deleted_kinds strictRemovedHandlingInAlpha to false after beta

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#101951]
once the we hit a beta release, we can reset the default value for strict handling to false to prep for 1.23.

/assign @deads2k 
/kind bug
/priority important-soon
/milestone v1.22
@kubernetes/sig-api-machinery-bugs

**Comment by notchairmk** [comment]
Hi @deads2k, Bug Triage from SIG Release here 👋.. Checking to see if this issue is going to make it to v1.22 milestone bearing in mind code freeze is 07/08/2021. Feel free to reach out if there are any questions/concerns.

**Comment by voigt** [comment]
Hi, Bug Triage here,
removing this issue from 1.22, as there hasn't been activity on that issue for 16 days.

/milestone clear
