### ISSUE TITLE
FR: Safer rollout of admission webhook updates

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#102019]
#### What would you like to be added:

A mechanism to gradually roll out (and roll back) admission webhook configuration (`ValidatingWebhookConfiguration1 and `MutatingWebhookConfiguration`) updates (or additions). This should apply to the whole admission configuration, including the `clientConfig`, `rules`, `matchPolicy`, etc. 

Some ideas for features that would be nice to have:

- Control the percent of traffic going to the new/old configuration: this could be a random selection per-request, or keyed off a more stable value such as target object UID (although this wouldn't be guaranteed to be representative of the overall request ratio).
- Identify `canary` and `critical` namespaces and/or resources: canary resources would hit the updated configuration first, and critical resources would hit the updated configuration last.
- Set rejection and/or error thresholds: if the rejection or error rates hit the threshold, then the rollout would be automatically rolled back.

#### Why is this needed:

Webhook admission controllers are cluster-scoped resources that (without a namespace selector) apply to the whole cluster. This means that a misconfiguration can easily bring down an entire cluster, especially when failing closed (`failurePolicy=Fail`).

Note that this is about updates to the `admissionregistration.k8s.io/v1 {Validating,Mutating}WebhookConfiguration` resources, not updates to the underlying webhook servers.

We should also consider whether there are other cluster-scoped resources that could benefit from a similar mechanism, and whether this could be implemented in a generic way to cover those usecases.

**Comment by lavalamp** [comment]
#92157 is a different request, but it contains some related discussion.

**Comment by fedebongio** [comment]
@tallclair is this something you are planning to prepare a KEP for? Thanks

**Comment by deads2k** [comment]
This looks too significant to make progress as an issue.  To pursue this, I think a design will be needed.  @tallclair do you already have a design in mind that you would like to describe at a sig-apimachinery meeting?

**Comment by tallclair** [comment]
I don't have a specific design in mind, but I'd be happy to discuss some ideas at sig-apimachinery. This was actually forked out of https://github.com/kubernetes/enhancements/issues/1872, which was my initial idea.

**Comment by fedebongio** [comment]
Hi Tim, this one has been open and a bit stalled for some weeks now. Would you like to come to the SIG meeting to chat about it?

**Comment by lavalamp** [comment]
We would probably tackle this as a follow-up to the inconclusive "webhook webhooks" conversation in yesterday's. I may put that on the agenda anyway. They are extremely related issues, perhaps even the same, or if not, a solution to safer rollouts would at least clarify what part of the problem is remaining for platform admins.

**Comment by tallclair** [comment]
I put it on the agenda for next week (June 16th)

**Comment by deads2k** [comment]
We spoke about this at the sig-apimachinery call this week.  The outcome is that we're interested in reviewing a KEP if someone can commit effort to delivering and maintaining such a feature, but no one on the sig call was in a position to commit to pushing it through.

Just a reminder that a commitment to review a KEP isn't the same as a commitment to merge it or shepherd it through implementation.

The next step is creating a KEP (if desired), so we'll close this issue.
