### ISSUE TITLE
Hardcoded test images prevent passing in airgap environment

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#102075]
#### What happened:
Numerous sig-storage tests hardcode the registry/image for tests, meaning they can't be overridden by custom values and therefore can't pass in an airgap setting.

#### What you expected to happen:
It should make use of templates and checking the registry/image location at runtime.

#### Anything else we need to know?:
xref: https://github.com/vmware-tanzu/sonobuoy/issues/1264

/area e2e-test-framework
/sig testing

**Comment by BenTheElder** [comment]
/sig storage
/remove-sig testing
sig storage owns their manifests for their test cases. SIG testing owns the framework to lookup images but not doing it in all the test cases.

**Comment by pacoxu** [comment]
/cc @pohly 

`gcr.io/k8s-staging-cs` -> `gcr.io/gke-release` ->  `k8s.gcr.io/sig-storage`
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml#L24

https://github.com/kubernetes/k8s.io/pull/952

**Comment by pohly** [comment]
There is support for patching the registry in those manifest files:
https://github.com/kubernetes/kubernetes/blob/5c586201186b1f31d16257511baef7793112ae76/test/e2e/storage/utils/create.go#L625-L637

For which test or job is that not working?

I have never tried that feature, but presumably it's to be used by copying the required images into a local registry and then overriding k8s.gcr.io/sig-storage via `KUBE_TEST_REPO_LIST`:
https://github.com/kubernetes/kubernetes/blob/5c586201186b1f31d16257511baef7793112ae76/test/utils/image/manifest.go#L40

**Comment by johnSchnake** [comment]
So I also had seen that patch logic; I think that is getting phased in in certain places and I'll have to double check the list of impacted tests to see if it is still lagging behind.

**Comment by johnSchnake** [comment]
I'll try and walk through the code a bit more; the best example I have is from a storage tests and it is difficult to follow the setup/teardown logic if you're not familiar. The file `test/e2e/testing-manifests/storage-csi/mock/csi-mock-driver-attacher.yaml` has the hard coded value in this example and I'm not sure that it ever gets swapped out.

That being said, from the time of the sonobuoy ticket to now, something has changed because the registry in question is different too.

**Comment by pohly** [comment]
That issue was about gcr.io/k8s-staging-csi - that's not a registry that ever should be used in a proper Kubernetes release. We may have used it temporarily when images hadn't been promoted yet.

I'll comment in that issue.
