### ISSUE TITLE
ApiServer `--kubelet-timeout` does nothing 

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#102052]
#### What happened:
Configured `--kubelet-timeout` but no effect.

#### Anything else we need to know?:
Check the code and found the `--kubelet-timeout` does nothing.

https://github.com/kubernetes/kubernetes/blob/1d38084930b56be9b5830c20bd5b464b1f955047/cmd/kube-apiserver/app/options/options.go#L252-L253
https://github.com/kubernetes/kubernetes/blob/1d38084930b56be9b5830c20bd5b464b1f955047/pkg/kubelet/client/kubelet_client.go#L87-L123

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by yliaog** [comment]
the flag is passed to the following code, does it not work?

https://github.com/kubernetes/kubernetes/blob/22ec3b0eddf2bea9d7137516c15d85d17f059357/pkg/kubelet/client/kubelet_client.go#L54

	// HTTPTimeout is used by the client to timeout http requests to Kubelet.
        HTTPTimeout time.Duration
