### ISSUE TITLE
[1.19, 1.20] make release fails due to k8s.gcr.io/build-image/debian-iptables for wrong platform

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#102087]
#### What happened: 

`make release` failed like so on 1.20.7:

```
c2834cd528bb: Pull complete
Digest: sha256:4c9410a4ee555dcb0e8b7bd6fc77c65ac400f7c5bd4555df8187630efaea6ea4
Status: Downloaded newer image for k8s.gcr.io/build-image/debian-iptables:buster-v1.3.0
image with reference k8s.gcr.io/build-image/debian-iptables:buster-v1.3.0 was found but does not match the specified platform: wanted linux/arm, actual: linux/amd64
!!! [0518 01:38:34] Call tree:
!!! [0518 01:38:34]  1: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:240 kube::release::create_docker_images_for_server(...)
!!! [0518 01:38:34]  2: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:246 kube::release::build_server_images(...)
!!! [0518 01:38:34]  3: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:98 kube::release::package_server_tarballs(...)
!!! [0518 01:38:34]  4: build/release.sh:45 kube::release::package_tarballs(...)
+++ [0518 01:38:34] Deleting docker image k8s.gcr.io/kube-scheduler-arm:v1.20.7
+++ [0518 01:38:35] Deleting docker image k8s.gcr.io/kube-controller-manager-arm:v1.20.7
+++ [0518 01:38:35] Deleting docker image k8s.gcr.io/kube-apiserver-arm:v1.20.7
+++ [0518 01:38:38] Building tarball: node linux-s390x
+++ [0518 01:38:38] Deleting conformance image k8s.gcr.io/conformance-arm:v1.20.7
!!! [0518 01:38:38] previous Docker build failed
!!! [0518 01:38:38] Call tree:
!!! [0518 01:38:38]  1: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:240 kube::release::create_docker_images_for_server(...)
!!! [0518 01:38:38]  2: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:246 kube::release::build_server_images(...)
!!! [0518 01:38:38]  3: /usr/local/google/home/bentheelder/go/src/k8s.io/kubernetes/build/lib/release.sh:98 kube::release::package_server_tarballs(...)
!!! [0518 01:38:38]  4: build/release.sh:45 kube::release::package_tarballs(...)
+++ [0518 01:38:50] Building tarball: node linux-ppc64le
+++ [0518 01:38:59] Building tarball: node windows-amd64
!!! [0518 01:39:09] previous tarball phase failed
make: *** [Makefile:407: release] Error 1
```

Similar failure happens cross compiling in 1.19

#### What you expected to happen:

`make release` should not fail. I have all the pre-reqs installed, I am able to cross compile Kubernetes on 1.21, 1.18, 1.17, 1.16, 1.15, 1.14 ...

#### How to reproduce it (as minimally and precisely as possible):

I think you just need docker 20.10 on linux + try to `make release` on Kubernetes 1.19 or 1.20 branches.

#### Anything else we need to know?:

I suspect this is related to `FROM --platform` in the dockerfile, vs building with say buildx --platform (which we changed in 1.21 https://github.com/kubernetes/kubernetes/pull/98529)

#### Environment:
- ~debian testing
- docker 20.10.2 CE
- kubernetes 1.19 or 1.20 latest patch releases

/sig release

**Comment by BenTheElder** [comment]
seems to succeed on 20.10.5 / macOS 🤔

**Comment by saschagrunert** [comment]
I'll give this a look tomorrow.

**Comment by saschagrunert** [comment]
The issue is that the architecture specific images had the wrong architecture in their manifest. This has been already fixed a while ago. I think a mitigation would be to backport #98529 or update the base images for the release branches.
```
> podman inspect k8s.gcr.io/build-image/debian-iptables-arm:buster-v1.3.0 | jq -r .[].Architecture
amd64
> podman inspect k8s.gcr.io/build-image/debian-iptables-arm:buster-v1.6.0 | jq -r .[].Architecture
arm
```

Backporting the #98529 seems better to me, I'll propose that change.

**Comment by BenTheElder** [comment]
My only concern with backporting https://github.com/kubernetes/kubernetes/pull/98529 would be potenetially introducing the requirement of buildx (I think prior to this building a release didn't require it?) which might increase the minimum docker version?

I'm not sure why the cross builds are working on the mac, but I wonder if perhaps docker began tolerating this again in one of the patch releases in the 20.10 series.

**Comment by spiffxp** [comment]
I have no idea if it's relevant here, but I'll just point out that right now the latest release of `buildx` has a bug that prevents it from properly pushing to GCR under certain conditions (see https://github.com/kubernetes/test-infra/issues/20884#issuecomment-783840975 for a description of the problem)

I am hopeful the fix is making its way back up the dependency chain into the next release of `buildx` (see: https://github.com/kubernetes/test-infra/issues/20884#issuecomment-834792037 for what we're waiting on), but I just looked and we're still waiting.

**Comment by BenTheElder** [comment]
we're using buildx for the same patterns as before only replacing building one platform at a time as a drop in docker build replacement. since we use `--load` when building and then push/manifest push.

we're not affected. it's being pushed by old school docker tooling from the standard docker storage.

sascha mentioned that the newer base images should work properly with `FROM --platform` as they are properly multi-arch, so I want to test that option.

the remaining buildx concern is the possibility that some older docker was working at least for non-cross builds perhaps in someone else's downstream pipeline and will now not work because it lacks this (it's not clear, we've not tightly monitored / documented required versions).

**Comment by saschagrunert** [comment]
I think we're already fine since we bumped the debian-base images in https://github.com/kubernetes/kubernetes/pull/102342, https://github.com/kubernetes/kubernetes/pull/102341 and https://github.com/kubernetes/kubernetes/pull/102340.

This means that we now use proper multi architecture images for `debian-{base,iptables}`.

/close
