### ISSUE TITLE
e2e failures: all pdcsi tests

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#102077]
#### Which jobs are failing:
ci-kubernetes-e2e-gci-gce-serial

#### Which test(s) are failing:
All gce pd csi tests

#### Since when has it been failing:
5/14

#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-storage-kubernetes#gce-serial

#### Reason for failure:
Likely related to the removal of v1beta1 storage objects in https://github.com/kubernetes/kubernetes/pull/99840. The provisioner and attacher sidecars need to be updated.

**Comment by thejoycekung** [comment]
is #102101 also related to this? if so we can close it

**Comment by msau42** [comment]
No I don't think it's related at first glance.

**Comment by aojea** [comment]
@prameshj these are failing in sig-network testgrid too, https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns-nodecache

 I've found them when you mentioned it in the dns autoscale issue, kudos to her

**Comment by mattcary** [comment]
As Michelle predicted, eg from the provisionner.

```
E0521 05:23:22.045197       1 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSINode: the server could not find the requested resource
```

Created https://github.com/kubernetes/kubernetes/pull/102212.

**Comment by mkorbi** [comment]
hey, have you seen the CSI test failing in gce-master-scale? https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness


@mattcary @msau42

**Comment by mattcary** [comment]
The provisionner isn't deleting the volume in time. I wonder if this is the
same issue that we've seen with the pd csi driver where at load the
provisionner's watches are getting dropped.

```
          Persistent Volume pvc-59ebe0e1-2bd8-4a50-867c-e1c615379741 not
deleted by dynamic provisioner: PersistentVolume
pvc-59ebe0e1-2bd8-4a50-867c-e1c615379741 still exists within 5m0s
      occurred [0m

      /go/src/
k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:152
[90m------------------------------ [0m
{"msg":"FAILED [sig-storage] CSI Volumes [Driver: csi-hostpath]
[Testpattern: Dynamic PV (default fs)] volume-expand should not allow
expansion of pvcs without AllowVolumeExpansion
property","total":-1,"completed":7,"skipped":20,"failed":1,"failures":["[sig-storage]
CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)]
volume-expand should not allow expansion of pvcs without
AllowVolumeExpansion property"]}
```

**Comment by msau42** [comment]
Hostpath CSI failures are being investigated in: https://github.com/kubernetes/kubernetes/issues/102452
