### ISSUE TITLE
Pods is running when Node in NotReady state

### ISSUE THREAD

**Issue by MainPoser** [kubernetes/kubernetes#102026]
#### What happened:
1.when a node is down, the POD state is running(I waited more than five minutes)

#### What you expected to happen:
1.The status of the three pods will be updated to terminating. When all worker nodes are restarted, the pod will be re deployed
#### How to reproduce it (as minimally and precisely as possible):
1.I have a cluster of one master node and three worker nodes. 
2.Then I deploy a statefulset, which three replicas(one pod one node).
3.When I forcibly shut down three worker nodes, all workers are in NotReady state. However, there may be one or two pods whose status is always running.
4.As a result, my Mongo replica set cannot be restored
5.When I restart all worker nodes instead of shutting down, the status of the three pods will be updated to terminating. When all worker nodes restart, the pod will be re deployed and my Mongo cluster will be restored
#### Anything else we need to know?:
1.I'm trying to deploy a Mongo replica set. Pods that are still running when the node is shut down cannot join the cluster after the node is restarted, but each pod can communicate with each other
#### Environment:
- Kubernetes version (use `kubectl version`):
```
1.18.3
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):

```
RHEL7.5
```

- Kernel (e.g. `uname -a`):

```
3.10.0-862.el7x86_64
```

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig cluster-lifecycle

**Comment by gjkim42** [comment]
I think this has been fixed. You can update the k8s cluster to v1.18.17 or the latest version
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#changelog-since-v11816
https://github.com/kubernetes/kubernetes/pull/98943

/close
