### ISSUE TITLE
add https-proxy's certification setting to kubeconfig

### ISSUE THREAD

**Issue by liufen90** [kubernetes/kubernetes#102079]
Now kubeconfig has supported to set http-proxy. There could be potential scenarios where certain clusters require the usage of an HTTPs proxy to be accessible for safety. It would be useful to have https-proxy's certification as a per cluster setting on the kube config so that it is easy to talk to clusters that require and don't require the usage of a https proxy.

**Comment by pacoxu** [comment]
a feature request ？`/kind feature`
