### ISSUE TITLE
L7 GCE Ingress failing tests

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#102006]
#### Which jobs are failing:

GCE Ingress tests

#### Which test(s) are failing:

Loadbalancing: L7 GCE [Slow] [Feature:Ingress]

#### Since when has it been failing:

05-14 

#### Testgrid link:

https://testgrid.k8s.io/sig-network-gce#gci-gce-ingress-manual-network
https://testgrid.k8s.io/sig-network-gce#gci-gce-kube-dns-nodecache
https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress

#### Reason for failure:

```
May 14 07:06:54.439: FAIL: Unexpected error:
    <*errors.StatusError | 0xc000972960>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server could not find the requested resource",
            Reason: "NotFound",
            Details: {Name: "", Group: "", Kind: "", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 404,
        },
    }
```

#### Anything else we need to know:

update to handle beta removals in 1.22 #99840

ingress should move to v1 https://github.com/kubernetes/kubernetes/issues/95309

**Comment by aojea** [comment]
I think that the solution is to solve #95309 and move all the e2e code in tree from to ingress v1beta1 to v1, 
@deads2k @liggitt  can you confirm?

```
I0514 07:07:00.398439       8 httplog.go:99] "HTTP" verb="GET" URI="/apis/extensions/v1beta1/ingresses?resourceVersion=0" latency="916.942µs" userAgent="nginx-ingress-controller/v1.5.1+$Format:%h$ (linux/amd64) kubernetes/$Format" audit-ID="88b801de-10ec-47b2-905b-6fda245401b6" srcIP="35.203.161.117:44086" resp=404
```

cc: @bowei @swetharepakula @robscott

**Comment by liggitt** [comment]
Anything using v1beta1 ingress must move to v1 ingress to work against the master branch or 1.22+ API servers. That user-agent looks like `nginx-ingress-controller`, not a manifest

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-gubernator/triage/index.html#5a9d456b310fc98c6425
![image](https://user-images.githubusercontent.com/2010320/118428645-82f76100-b702-11eb-8cc6-2675eb227cd1.png)

/priority critical-urgent

**Comment by aojea** [comment]
/assign

https://github.com/kubernetes/kubernetes/pull/102030

**Comment by mkorbi** [comment]
- https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress
- https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

**Comment by jkaniuk** [comment]
Looks fixed, thanks!

![image](https://user-images.githubusercontent.com/5487158/119120199-5017da80-ba2c-11eb-95f2-de050e0ba434.png)
