### ISSUE TITLE
kubectl top pod doesn't account for the whole pod resource usage

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/kubernetes#102051]
#### What happened:

The kubectl top command doesn't take into account the resource usage of the whole pod as stated in the command documentation. It only accounts for the resource usage of the containers. This is because [PodMetrics](https://github.com/kubernetes/metrics/blob/v0.21.0/pkg/apis/metrics/types.go#L63-L74) only account for containers resource usage and not the resource usage of the whole Pod. This is meaningful for autoscaling as we only want to account for the container resource usage, but in the case of `kubectl top pod` it seems to be different.

#### What you expected to happen:
According to the description of the command:
```
 The 'top pod' command allows you to see the resource consumption of pods.
```
I would have expected `kubectl top pod` to return the resource usage of the whole pod and not only the resource usage of its containers.

#### How to reproduce it (as minimally and precisely as possible):

If you have Prometheus running and scraping cadvisor metrics, it's pretty easy to notice:
![image](https://user-images.githubusercontent.com/22327577/118465064-d0bf9980-b701-11eb-98e0-5c6f1ced1dc8.png)
We have 3 different containers CPU usage reported by cadvisor for the kube-apiserver pod:
- `POD` container (pause container)
- `kube-apiserver` container
- empty which refers to the usage of the whole pod

Even if we were to add the cpu usage of both the pause and the kube-apiserver containers, it wouldn't be equal to the usage of the whole pod reported by cadvisor. This is because, there are not only containers that are running in a pod. Depending on the aggregated API, kubectl top pod will either return the sum of all the containers resource usage or the one of all containers except the pause container. In any case, it would only account for containers.

If you aren't monitoring cadvisor metrics, this is also noticeable by querying the `/stats/summary?only_cpu_and_memory=true` endpoint of your control-plane, in the same fashion as the current implementation of metrics-server. In the resource usage reported for the kube-apiserver pod we can see the resource usage of the `kube-apiserver` container and another section for the resource usage of the whole pod. Both information already exist, but [PodMetrics](https://github.com/kubernetes/metrics/blob/v0.21.0/pkg/apis/metrics/types.go#L63-L74) only account for containers resource usage.

<details open>
<summary>Summary API resource usage of kube-apiserver</summary>

```json
  {
   "podRef": {
    "name": "kube-apiserver-minikube",
    "namespace": "kube-system",
    "uid": "ee69b8ee6d1f13282c619a8f501bcec0"
   },
   "startTime": "2021-05-17T09:05:13Z",
   "containers": [
    {
     "name": "kube-apiserver",
     "startTime": "2021-05-17T09:05:13Z",
     "cpu": {
      "time": "2021-05-17T09:28:37Z",
      "usageNanoCores": 58036902,
      "usageCoreNanoSeconds": 96719276856
     },
     "memory": {
      "time": "2021-05-17T09:28:37Z",
      "usageBytes": 417988608,
      "workingSetBytes": 417988608,
      "rssBytes": 415109120,
      "pageFaults": 145926,
      "majorPageFaults": 0
     }
    }
   ],
   "cpu": {
    "time": "2021-05-17T09:28:37Z",
    "usageNanoCores": 64109788,
    "usageCoreNanoSeconds": 96887530866
   },
   "memory": {
    "time": "2021-05-17T09:28:37Z",
    "usageBytes": 418611200,
    "workingSetBytes": 418611200,
    "rssBytes": 415109120,
    "pageFaults": 0,
    "majorPageFaults": 0
   }
  },
```
</details>  

#### Anything else we need to know?:

There are two potential solutions that I can see depending on which direction the `kubectl top` command go. Either, the command description should be updated to mention that it is used to introspect autoscaling pipelines and thus doesn't account for the whole pod resource usage. Or, the description could be kept as is and the PodMetrics resource could be updated to also include the resource usage of the whole pod. If so, `kubectl top pod` should be updated to take that change into account. 

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-04-09T16:47:30Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

/sig instrumentation
cc @serathius @brancz 
/sig cli

**Comment by odinuge** [comment]
Hi @dgrisonnet ,

> [...] This is because, there are not only containers that are running in a pod.[...]

Can you elaborate more on what you mean with this? What else is running inside a container other than the containers and the pod sandbox?

**Comment by serathius** [comment]
Even though both tools share a similar name kubectl top was not designed to give a as detailed view as it's linux counterpart. It was a side effect of designing an autoscaling pipeline as so it doesn't care about container runtime overhead nor being supper accurate. 

Same as Core Metrics Pipeline, kubectl top was designed for scalable, easy to setup resource autoscaling, leaving problems mentioned before to monitoring systems like Prometheus. Non container pod resource usage you mentioned would be useful when trying calculate and monitor overhead, but I don't expect that cli tool will be robust enough for this task.

Still it can be confusing for `kubectl top` users why it's results differ so much from what they get in their monitoring solution. However this is more a documentation problem, we should definitely do a better job there.

Overall I'm not saying that we shouldn't improve kubectl top in any means, but let's make sure we know what problem we are solving, and what use cases we are trying targetting.

**Comment by dgrisonnet** [comment]
Hey @odinuge, I was referring to all the processes that are not charged into the containers cgroups, but in the pod cgroups. Basically, the goal would be to either extend kubectl top pods to account for the changes made in #95839 or update the documentation to clarify that it only accounts for container resource usages.

I understand that `kubectl top` wasn't designed to be the equivalent of Linux top for Kubernetes, but considering the documentation and the naming similarity, I would expect most of the users to believe that it has the same purpose.

That said I'm fine with keeping `kubectl top` purpose to autoscaling, but we should make it clear in the documentation.

**Comment by dgrisonnet** [comment]
Closing as a duplicate of https://github.com/kubernetes/kubectl/issues/830.
