### ISSUE TITLE
crio cgroup v1 node conformance test failing after runc update

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#102092]
#### Which jobs are failing:
All crio node conformance jobs which use cgroup v1 such as, 
[Node Conformance Periodics](https://prow.k8s.io/?job=*ci-crio-cgroupv1-node-e2e-conformance*)
[Node Conformance Presubmit](https://prow.k8s.io/?job=*pull-kubernetes-node-crio-e2e*)

#### Which test(s) are failing:
[sig-node] Summary API [NodeConformance]

#### Since when has it been failing:
From this [commit](https://github.com/kubernetes/kubernetes/commit/b1b06fe0a4d80ac0fd67fae56f29a3710934a256) onwards which bumped up runc 

#### Testgrid link:
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance

#### Reason for failure:
Update to runc rc94 is causing this failure.

**Comment by harche** [comment]
Output of the failed tests,

```bash
• Failure [111.380 seconds]
[sig-node] Summary API [NodeConformance]
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/framework.go:23
  when querying /stats/summary
  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:43
    should report resource usage through the stats api [It]
    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54

    Timed out after 90.000s.
    Expected
        <string>: Summary
    to match fields: {
    [.Pods[summary-test-8171::stats-busybox-0].Memory:
    	Expected
    	    <string>: MemoryStats
    	to match fields: {
    	.AvailableBytes:
    		Expected
    		    <*uint64 | 0x0>: nil
    		not to be <nil>
    	}
    	, .Pods[summary-test-8171::stats-busybox-1].Memory:
    	Expected
    	    <string>: MemoryStats
    	to match fields: {
    	.AvailableBytes:
    		Expected
    		    <*uint64 | 0x0>: nil
    		not to be <nil>
    	}
    	]
    }
    

    _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:342
```

**Comment by odinuge** [comment]
Thanks for pinging @harche!

Yeah, the new runc release still need a fair bit of work before properly working with k8s. There might be other edge cases as well... :/

This might be related to what I mentioned here (although not 100% sure about this one): https://github.com/kubernetes/kubernetes/pull/101888#pullrequestreview-661762880

I have an somewhat old PR here: https://github.com/kubernetes/kubernetes/pull/98374

And it looks like the pre-submit passed on that commit now: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98374/pull-kubernetes-node-crio-e2e/1394592396901093376/

**Comment by harche** [comment]
Tests passing now after https://github.com/kubernetes/kubernetes/pull/102094 is merged
