### ISSUE TITLE
kubectl debug compatibility with pre-1.22 ephemeral containers API

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#102008]
#### What would you like to be added:
#101034 changed the Kind used with the `/ephemeralcontainers` subresource from `EphemeralContainers` to `Pod`. This change will break old clients. (The ephemeral containers API is still in alpha, so this is acceptable.)

Currently, compatibility is broken in both directions:
1. kubectl versions prior to 1.22 are incompatible with server version 1.22
2. kubectl version 1.22 is incompatible with server versions prior to 1.22

Remediating the first requires complex server-side backwards compatibility logic which is not worth implementing for an alpha API.

Remediating the second for `kubectl debug` should be much easier. The `EphemeralContainer` struct hasn't changed, only the path in the object. We could detect the kind returned by the server and change the path used in the JSON patch (or even just naively try the previous path if the server returns an error).

This behavior would be removed after the old server version falls out of the support window.

#### Why is this needed:

This isn't strictly needed, but it would improve UX for what I expect is a common scenario: using the latest kubectl with older servers.

/sig cli
/priority important-soon

**Comment by verb** [comment]
@soltysh @eddiezane what do you think about adding this backwards compatibility behavior to kubectl?

**Comment by eddiezane** [comment]
> kubectl versions prior to 1.22 are incompatible with server version 1.22
> Remediating the first requires complex server-side backwards compatibility logic which is not worth implementing for an alpha API.

Are we able to detect this and fail gracefully client side with a warning to users to upgrade their client?

> kubectl version 1.22 is incompatible with server versions prior to 1.22
> Remediating the second for kubectl debug should be much easier. The EphemeralContainer struct hasn't changed, only the path in the object. We could detect the kind returned by the server and change the path used in the JSON patch (or even just naively try the previous path if the server returns an error).

Agree that this fix is the important one.

I wonder if a commit for backwards compatibility is something we can cherry pick to other release branches? Seeing as earlier branches will have both structs it might even be cleaner to do version conditional in kubectl there?

@puerco is that something we've done before?

**Comment by puerco** [comment]
Just to make in my head a matrix of effects/noneffects, please confirm for me if these are right:

1. Kubectl 1.22 will have the compatibility logic baked in. So it will be able to talk to older servers.
2. Cherry-picking that logic to older branches would not alter in any way how pre-1.22 kubectls interact with old (pre 1.22) servers. 
3. The cherry-pick would only add the needed logic to allow old kubectls to talk to 1.22 and later servers

Are these assumptions correct?

**Comment by verb** [comment]
> Just to make in my head a matrix of effects/noneffects, please confirm for me if these are right:
> 
> 1. Kubectl 1.22 will have the compatibility logic baked in. So it will be able to talk to older servers.

Correct.

> 2. Cherry-picking that logic to older branches would not alter in any way how pre-1.22 kubectls interact with old (pre 1.22) servers.
> 3. The cherry-pick would only add the needed logic to allow old kubectls to talk to 1.22 and later servers

I haven't prototyped it, but this should be possible. We could trigger the logic on a server error that indicates it received an unexpected Kind.

That being said, I don't think it's worth cherry-picking forward compatibility into older versions of kubectl. This is for an alpha feature that must be explicitly enabled with the `EphemeralContainers` feature flag. It's not unreasonable to require people experimenting with an alpha feature to use a kubectl version >= server version. There's far more risk than benefit.

It would be more of a burden to keep around old versions of kubectl for older clusters, so I thought adding backwards compatibility in 1.22 would be nice, even if it's not strictly required.

I agree it would be nice if we could give users of pre-1.22 kubectl a better error message, but I at least have kubernetes/website#27988 out to indicate a minimum kubectl version requirement of 1.22.

**Comment by yashikabadaya** [comment]
I'd like to take up this task.

**Comment by verb** [comment]
@yashikabadaya How's it going? I'd like to make sure this makes it into 1.22.

**Comment by yashikabadaya** [comment]
Hi @verb , I am able to reproduce this issue. I am looking for some guidance on how to go about fixing this issue?

**Comment by verb** [comment]
Hi @yashikabadaya, given that time zones are difficult and the code freeze is near, I think it'll be most efficient to communicate with examples. I'll prepare a PR with what I have in mind.
