### ISSUE TITLE
E2E kube-dns-autoscaler tests should belong to sig-networking, not sig-autoscaling

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#102096]
I believe that tests in test/e2e/autoscaling/dns_autoscaling.go should belong to sig-networking, e.g.:

`[sig-autoscaling] DNS horizontal autoscaling kube-dns-autoscaler should scale kube-dns pods in both nonfaulty and faulty scenarios`

/assign @prameshj 
/cc @wojtek-t 
/sig networking
/sig autoscaling

**Comment by prameshj** [comment]
These tests are run on sig-network testgrid as well in https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-serial and https://k8s-testgrid.appspot.com/sig-network-gce#gci-gce-serial-kube-dns and those failures do come to sig-network. Right, @aojea ?

**Comment by aojea** [comment]
I don't see any network check on these tests, they are asserting only that the scaling work, so I think that autoscsaling should own them.
However, there are no written rules AFAIK and if someone sees a possible network problem they should tag sig-network, as prameshj says in previous comment we already monitor that job

**Comment by prameshj** [comment]
Thanks @aojea . Can we close this, @jkaniuk ?

**Comment by jkaniuk** [comment]
Thanks. Yes, we can.
