### ISSUE TITLE
Deprecate AlgorithmProvider flag and algorithmProvider scheduler pkg 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102151]
#### What would you like to be added:

1. Remove [AlgorithmProvider](https://github.com/kubernetes/kubernetes/blob/8c0d06aad87047235beafd14546ff8418499b17e/cmd/kube-scheduler/app/options/deprecated.go#L50) flag. This flag was marked as deprecated since v1.17, we can remove it now.
2. Remove the [algorithmprovider](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/algorithmprovider) pkg. The default set of plugins would move to be set in the component config defaulting logic.

#### Why is this needed:
1. To enable versioning the default set of scheduler plugins 
2. Cleanup: unify defaulting for scheduler configuration 

/sig scheduling

**Comment by yuzhiquan** [comment]
@Haleygo you need make pr in k/k, not self-repo.

**Comment by Haleygo** [comment]
> @Haleygo you need make pr in k/k, not self-repo.

@yuzhiquan Thanks for reminder! I was meant to pull a draft, get it right now.

**Comment by Haleygo** [comment]
@ahg-g I am not sure about the second request :

> Remove the algorithmprovider pkg. The default set of plugins would move to be set in the component config defaulting logic.

 and I just moved the default set of plugins under createFromProvider, Is that the right place to go?

**Comment by yuzhiquan** [comment]
> > @Haleygo you need make pr in k/k, not self-repo.
> 
> @yuzhiquan Thanks for reminder! I was meant to pull a draft, get it right now.

Ok, you can make WIP pr.
