### ISSUE TITLE
"scheduler: non-compatible change in default topology spread constraints"

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#102136]
#### What happened:

From v1.19, the scheduler use `PodTopologySpread` plugin to do default spreading, with the following constraints, and the original `SelectorSpread` is disabled by default.

```yaml
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: kubernetes.io/hostname
  maxSkew: 3
- whenUnsatisfiable: ScheduleAnyway
  topologyKey: topology.kubernetes.io/zone
  maxSkew: 5
```
These default constraints suppose nodes have a `topology.kubernetes.io/zone` label. The algorithm will ignore nodes that don't have all the required topology keys presented when scoring.  

https://github.com/kubernetes/kubernetes/blob/ee9f365c519423d8693c6a9891ef8c5c47ebe475/pkg/scheduler/framework/plugins/podtopologyspread/scoring.go#L77-L82

However, in many on-premise clusters,  those labels are not added by default and no guaranteed to exist, which leads to the `PodTopologySpread` will not take effect at all.   

In a worse case, If we assign a `NodeResourcesMostAllocated` plugin and the `PodTopologySpread` do not take effect as described above,  the `NodeResourcesMostAllocated` will dominate the scheduling and be likely to bind all pods belonging to ReplicaSets to the same node, which will lead to low availability and is not accepted by our user.

In the `SelectorSpread` plugin, we have already taken care of this case: 

https://github.com/kubernetes/kubernetes/blob/ee9f365c519423d8693c6a9891ef8c5c47ebe475/pkg/scheduler/framework/plugins/selectorspread/selector_spread.go#L153-L154

When changed to `PodTopologySpread`, we do not care zome, so are not compatible with the original behavior.

#### What you expected to happen:

the default `PodTopologySpread` plugin should take care of the case in which nodes do not have zone labels and work properly.

#### How to reproduce it (as minimally and precisely as possible):

create a deployment in a cluster whose nodes do not have zone labels and observe the default spreading.

#### Environment:
- Kubernetes version (use `kubectl version`):
master branch

/assign 
/sig scheduling

**Comment by gaorong** [comment]
A potential fix would like  [this](https://github.com/gaorong/kubernetes/commit/0d50540312832a822d03141f699e1982f7ee4065): In the default constraints case, we do not ignore nodes in prescore phase, so nodes with no topology-labels will be grouped to an empty-value topology and count pod per topology normally. At the later score phase, those empty-value topology's scores will not be added to the final score as we have a label check as below, so the last result will favour nodes with all required topology keys presented and penalize without.

	for i, c := range s.Constraints {
		if tpVal, ok := node.Labels[c.TopologyKey]; ok {
			var cnt int64
			if c.TopologyKey == v1.LabelHostname {
				cnt = int64(countPodsMatchSelector(nodeInfo.Pods, c.Selector, pod.Namespace))
			} else {
				pair := topologyPair{key: c.TopologyKey, value: tpVal}
				cnt = *s.TopologyPairToPodCounts[pair]
			}
			score += scoreForCount(cnt, c.MaxSkew, s.TopologyNormalizingWeight[i])
		}
	} 



can this fix make sense? feel free to leave comments.

**Comment by ahg-g** [comment]
There are two options: 
1) Add `topology.kubernetes.io/zone` label to the nodes. This is reasonable since this label (along with topology.kubernetes.io/region) is now standard: https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/1659-standard-topology-labels

2) Update the default pod spreading constraints in the scheduler CC to only use the hostname constraint.

@alculquicondor we faced/discussed this issue before, what was the conclusion?

**Comment by alculquicondor** [comment]
My suggestion was to special case the system defaulting to still provide some spreading if the zone label doesn't exist https://github.com/kubernetes/kubernetes/issues/98480#issuecomment-768365650

Feel free to implement that suggestion. This should apply for backporting.

**Comment by alculquicondor** [comment]
cc @Huang-Wei who was in the previous thread.

**Comment by alculquicondor** [comment]
Btw, in the meantime, you can disable the feature gate `DefaultPodTopologySpread`

**Comment by Huang-Wei** [comment]
@alculquicondor 's suggestion looks good, but where should can we achieve that? Not during init time as `defaultConstraints` is instantiated without knowing the underlying node labels:

https://github.com/kubernetes/kubernetes/blob/bc637a7a07cf917140daa3bd434eac9bbd8fe92c/pkg/scheduler/framework/plugins/podtopologyspread/plugin.go#L97-L99

If in runtime, that implies we have to do it in every scoring cycle, and iterate the filtered nodes to know if the zone label is present or not.

**Comment by Huang-Wei** [comment]
> can this fix make sense? feel free to leave comments.

This may work except for the unnecessary calculation on the "artificial" empty-value topology.

**Comment by alculquicondor** [comment]
Yes, it should be in runtime. We already iterate over all the nodes in `PreScore`, so I don't see why it wouldn't work.

> can this fix make sense?

Something like that, but it should be done just for the `System` defaulting mode. If the cluster administrator set another default, we assume they know what they are doing.

**Comment by ahg-g** [comment]
This isn't pretty, but I guess we have to do it because it was a breaking change.

**Comment by ahg-g** [comment]
/retitle "scheduler: non-compatible change in default topology spread constraints"

**Comment by alculquicondor** [comment]
We probably need to solve this before graduating to GA kubernetes/enhancements#1258

@gaorong I noticed you still have a PR open. Are you still working on it?

**Comment by alculquicondor** [comment]
/unassign @gaorong 
as they seem inactive

I can take it over
/assign

**Comment by alculquicondor** [comment]
I'm not going to backport this, but I will support a cherry pick if anybody needs it. 1.20 would be the oldest that can be fixed.

**Comment by alculquicondor** [comment]
cc @damemi

**Comment by ahg-g** [comment]
/open

for backporting

**Comment by ahg-g** [comment]
we need to backport this

**Comment by alculquicondor** [comment]
Opened: #106604, #106605, #106607
