### ISSUE TITLE
Move volume as a default resource for node resource plugins.

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#102166]
#### What happened:
See the discussion here, 
https://github.com/kubernetes/kubernetes/pull/101946#discussion_r631829448

We can move volume as a default resource, and refactor the function like  `balancedResourceScorer` and `resourceAllocationScorer.score` to make the code more concise.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig scheduling

**Comment by chendave** [comment]
/remove-kind bug

cc @alculquicondor @Huang-Wei

**Comment by alculquicondor** [comment]
Note that I would rather remove the entire logic, as it never graduated to beta and it's been a while. But @ravisantoshgudimetla has to confirm if we can do that.

**Comment by chendave** [comment]
kindly ping @ravisantoshgudimetla for any thoughts? https://github.com/kubernetes/kubernetes/pull/101946 is blocking due to this feature, so far we have three choices, 
- Define the volume as a default resource just like the cpu and memory,  so that it will be considered if user don't specify any resource explicitly.
- Treat it as an extended resource, this will be something like "gpu" or "hugepage" etc. then it will not be included unless the volume is added into resource list by user.
- Remove the entire logic as @alculquicondor 's suggestion? if there is no plan to graduate this feature?

**Comment by chendave** [comment]
The feature has been removed.
