### ISSUE TITLE
Can't see the logs of pod

### ISSUE THREAD

**Issue by Hamza-Lachi** [kubernetes/kubernetes#102141]
#### What happened:

whenever i check logs of any pod from my master server `kubectl logs -f crm-dev-rapi-894c8fb99-9fdks`  i get this issue.

`Error from server: Get "https://192.168.1.109:10250/containerLogs/default/crm-dev-rapi-894c8fb99-9fdks/crm-dev-rapi?follow=true": dial tcp 192.168.1.109:10250: i/o timeout`

#### What you expected to happen:

it should show me the logs of my pod

#### kubectl version

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

#### Cloud provider or hardware configuration

master --- aws
worker --- pawnhost

#### OS

Ubuntu 20.04.2 LTS (Focal Fossa)

#### Kernel

Linux k8s-mstr-01 5.4.0-1048-aws #50-Ubuntu SMP Mon May 3 21:44:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pacoxu** [comment]
#102139 is dupped. You may close one.
