### ISSUE TITLE
[Test Failing] "Loadbalancing: L7 [Slow] Nginx should conform to Ingress spec" in gce-master-scale-correctness

### ISSUE THREAD

**Issue by jkaniuk** [kubernetes/kubernetes#102102]
#### Which jobs are failing:
gce-master-scale-correctness

#### Which test(s) are failing:
Loadbalancing: L7 [Slow] Nginx should conform to Ingress spec

#### Since when has it been failing:
5-14

#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-correctness

#### Reason for failure:
```
the server could not find the requested resource
occurred k8s.io/kubernetes/test/e2e/framework/ingress/ingress_utils.go:492
```

#### Anything else we need to know:
update to handle beta removals in 1.22 #99840

ingress should move to v1 #95309

/sig scalability
/sig networking
/assign aojea

**Comment by wangyysde** [comment]
xref: #102030
