### ISSUE TITLE
Optimize calculating the DefaultSelector in the scheduler

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102179]
For default pod spreading, for each pod we compute a selector that defines the set of pods that the incoming pod should be spread against. This is done by listing all Services, ReplicaSets, Deployments in the namespace and testing which ones with a selector that matches the pod labels.

This is very expensive at scale (e.g., thousands of replicasets in the same namespace). 

To address this issue, I think we can use the `ownerReference` in the pod to directly lookup the owning resource instead of doing linear search.

/sig scheduling

**Comment by alculquicondor** [comment]
I'm experiment about how far I can get improving `LabelSelectorAsSelector`.

Otherwise, the matching code is coming from the lister, which is under apimachinery, so the way we are matching might have a reason. Perhaps @liggitt can shed some light?

/sig api-machinery

**Comment by alculquicondor** [comment]
I'm referring to this function https://github.com/kubernetes/kubernetes/blob/29e4fdab4d644af51c1fa2623bf0e78f3dd6383b/staging/src/k8s.io/client-go/listers/apps/v1/replicaset_expansion.go

**Comment by ahg-g** [comment]
I think using ownerReference is very a reasonable approach, we should do that regardless.

**Comment by alculquicondor** [comment]
I shaved about 10% from the entire scheduling cycle time by managing slices better. More than that, it would require some refactoring to add a parsing option to skip validation. ReplicaSet and StatefulSet correctly validate selectors at creation, so it should be safe to do that. Skipping validation would shave other 50%, according to the profiles we have.

**Comment by ahg-g** [comment]
Again, why do we have to do a brute force search if we can simply look it up.

**Comment by alculquicondor** [comment]
I'm guessing because of adoption. But I'll let Jordan confirm.

**Comment by ahg-g** [comment]
Adoption will lead to ownerReference being updated by the adopting controller.

**Comment by fedebongio** [comment]
/cc @liggitt @jiahuif 
also cc @apelisse because of ownerreference
/triage accepted

**Comment by liggitt** [comment]
> ReplicaSet and StatefulSet correctly validate selectors at creation

they aren't affected by https://github.com/kubernetes/kubernetes/issues/99139 ?

> This is done by listing all Services, ReplicaSets, Deployments in the namespace and testing which ones with a selector that matches the pod labels.
> ...
> To address this issue, I think we can use the ownerReference in the pod to directly lookup the owning resource instead of doing linear search.

Using ownerReference would miss spreading for a selecting service ... is that important?

**Comment by alculquicondor** [comment]
> they aren't affected by #99139 ?

Ah, they would. I was assuming the existing validation was complete.

> Using ownerReference would miss spreading for a selecting service ... is that important?

Services are and would be handled separately, still by listing all of them.

Maybe the `GetPodReplicaSets` was meant to only be used by kcm? Then scheduler can just rely on the owner references wrt ReplicaSet and StatefulSet. Just trying to get the history right before we proceed.

**Comment by alculquicondor** [comment]
btw, we already skip validation for Services' selectors :)
