### ISSUE TITLE
Source for Namespace API reference omits details of .status.phase

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#102180]
#### What happened:
Spotted during triage for https://github.com/kubernetes/website/issues/28062 - @Ivo-Peterka visited https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/
The source of https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ suggests that readers look elsewhere for a list of Namespace phases:
https://github.com/kubernetes/kubernetes/blob/29e4fdab4d644af51c1fa2623bf0e78f3dd6383b/staging/src/k8s.io/api/core/v1/types.go#L5039-L5051

~but following that link doesn't take you to a page listing valid namespace phases.~

#### What you expected to happen:
- https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ lists valid namespace phases.
- https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/ also lists valid namespace phases.

#### How to reproduce it (as minimally and precisely as possible):
Visit https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/ or https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/ and try to work out what the valid values for `.status.phase` are.

#### Anything else we need to know?:
Not a high priority but definitely nice to fix.
/kind documentation

If retaining the hyperlink with the comment for  `NamespaceStatus` struct, it should link to the concept page not the task. In other words, the link should be to https://k8s.io/docs/concepts/overview/working-with-objects/namespaces/

#### Environment:
- Kubernetes version (use `kubectl version`): v1.21
- Cloud provider or hardware configuration: *n/a*
- OS (e.g: `cat /etc/os-release`): *n/a*
- Kernel (e.g. `uname -a`): *n/a*
- Install tools: *n/a* 
- Network plugin and version (if this is a network-related bug): *n/a*
- Others:
/sig docs
/sig architecture

**Comment by pacoxu** [comment]
Only found in  https://kubernetes.io/docs/tasks/administer-cluster/namespaces/.

> A namespace can be in one of two phases:
> 
> - Active the namespace is in use
> - Terminating the namespace is being deleted, and can not be used for new objects
> 
> See the [design doc](https://git.k8s.io/community/contributors/design-proposals/architecture/namespaces.md#phases) for more details.

[NamespaceStatus docs](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/namespace-v1/#NamespaceStatus) seems to be a better place.
