### ISSUE TITLE
NetworkPolicy: Support deny action

### ISSUE THREAD

**Issue by unmarshall** [kubernetes/kubernetes#102127]
Hello,

We have a use case where we have a limited set of pods/namespaces for which egress should be blocked and there is an unknown number of pods/namespaces/external endpoints to which it should be allowed.

This feature is provided by calico and is pretty useful (https://docs.projectcalico.org/archive/v3.19/security/calico-network-policy#features). Is there a pull to bring this into native K8S NetworkPolicy?

Best Regards,
Madhav

**Comment by thockin** [comment]
The short answer is that it is NOT currently being discussed.  To open this discussion we would need someone to lay out the use cases, why existing solutions do not work, and propose API changes.

**Comment by thockin** [comment]
We are looking at DENY as part of cluster network policy.  That may help what you need?

**Comment by srampal** [comment]
KEP for CNP referred to in Tim's comment is here ->. https://github.com/kubernetes/enhancements/issues/2091

**Comment by abhiraut** [comment]
A couple of questions for @unmarshall 

1. Are you looking to explicitly deny this traffic as a cluster administrator persona? If yes, you might be interested in ClusterNetworkPolicy KEP as pointed out by Tim above which includes `deny` actions, the link to the KEP can be found here -> https://github.com/kubernetes/enhancements/pull/2522
2. Are you looking to deny this as a developer persona? If yes, we, as part of [sig-network-policy-api](https://github.com/kubernetes-sigs/network-policy-api) subgroup, are thinking about a v2 NetworkPolicy API, which may/or may not include `deny` actions, perhaps you may be interested in joining us for a discussion during our weekly meetings or leave a note on [slack](https://kubernetes.slack.com/archives/C01CWSHQWQJ)
