### ISSUE TITLE
The second unsolicited packet sent by POD is not forwarded in accordance with Conntrack

### ISSUE THREAD

**Issue by kyrieSun-wow** [kubernetes/kubernetes#102128]
The second unsolicited packet sent by POD is not forwarded in accordance with Conntrack

#### What happened:
k8s env:
- service type: loadbalancer (coodinate with metalLB in layer 3:BGP)
- service attribute: externalTrafficPolicy : local   (To get the real source ip of client)
- pod num: only one for this service

scenario:
1. A client sent SCTP init and HEARTBEAT to loadbalancerIP of service (pod will not answer here);
2. Pod sent HEARTBEAT to client and client answer HEARTBEAT _ACK;
3. pod sent SCTP init to client,but no SNAT here(??) , client didn't answer back
4. pod retransmits SCTP INIT,still no  SNAT here(??)  ,client didn't answer back
5. pod retransmits SCTP INIT again,still no  SNAT here(??)  ,client didn't answer back
6. pod retransmits SCTP INIT again, SNAT is done,but the source ip is nodeIP not loadbalancerIP

check the conntrack:
root@xxx:~# conntrack -L | grep 10.96.134.34 | grep sctp
sctp     132 431987 ESTABLISHED src=172.1.0.2 dst=172.15.15.66 sport=36412 dport=36412 src=10.96.134.34 dst=172.1.0.2 sport=36412 dport=36412 [ASSURED] mark=0 use=1

It seems that conntrack is correct, 
So why the SCTP init sent by pod can not be SNAT correctly?
Or Why the HEARTBEAT sent by pod can be SNAT correctly?  

#### What you expected to happen:
The  SCTP init sent by pod should be SNAT correctly

#### attachment:
![conntrack_does_not_work](https://user-images.githubusercontent.com/59361291/118791894-b801e000-b8c9-11eb-8abb-aa1f97763f60.png)
172.1.0.2:        client
172.15.15.66:  loadbalancerIP
10.96.134.34:  podIP
172.1.113.92:  nodeIP

#### Environment:
root@xxx:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:11:25Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.14", GitCommit:"89182bdd065fbcaffefec691908a739d161efc03", GitTreeState:"clean", BuildDate:"2020-12-18T12:02:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kyrieSun-wow** [comment]
NOTE: SCTP multihomed issue

**Comment by uablrek** [comment]
Kube-proxy mode? ipvs or iptables?
What CNI-plugin? And in case of `Calico`, what backend?

**Comment by uablrek** [comment]
Actually I don't think there are any sctp multihoming tests in the K8s CI (right @aojea ?).

So unless some sctp developer steps up to take this issue, can you provide some test application, or point to any test application to use?

A minute of google'ing got me this; https://stackoverflow.com/questions/6342617/sctp-multihoming
Do you think it's sufficient?

**Comment by kyrieSun-wow** [comment]
> Kube-proxy mode? ipvs or iptables?
> What CNI-plugin? With which network overlay? And in case of `Calico`, what backend?

root@casammek8s:~# curl localhost:10249/proxyMode
iptables

CNI-plugin: 
calico    BGP overlay

backend: A private software deployed as deployment, two worker nodes and only one pod per worker node.

####More info
![Uploading k8s_sctp_restart_issue.png…]()

**Comment by kyrieSun-wow** [comment]
> Actually I don't think there are any sctp multihoming tests in the K8s CI (right @aojea ?).
> 
> So unless some sctp developer steps up to take this issue, can you provide some test application, or point to any test application to use?
> 
> A minute of google'ing got me this; https://stackoverflow.com/questions/6342617/sctp-multihoming
> Do you think it's sufficient?

This is not very similar to the issue I met

**Comment by uablrek** [comment]
@janosi Can you please take a look at this?

**Comment by aojea** [comment]
> Actually I don't think there are any sctp multihoming tests in the K8s CI (right @aojea ?).

nope, AFAIK we have "hello-world" sctp tests XD

**Comment by kyrieSun-wow** [comment]
Finally,problem solved.  The following two commands need to be set on the worker node:
**sysctl -w net.netfilter.nf_conntrack_sctp_timeout_closed=60
sysctl -w net.netfilter.nf_conntrack_sctp_timeout_heartbeat_sent=60**

**Comment by uablrek** [comment]
@kyrieSun-wow Can we close this issue?

But, if you can find any reasonable simple SCTP test program, please send a pointer. AFAIK nobody maintain sctp in K8s for now and it would be nice to have something better than "hello-world" for sctp in the e2e tests.

**Comment by bridgetkromhout** [comment]
Closing now, but yes, we would be happy to get "any reasonable simple SCTP test program". Thanks.

/close
