### ISSUE TITLE
Wrong scheduler behaviour when setting high memory_request like 50E

### ISSUE THREAD

**Issue by Sin4wd** [kubernetes/kubernetes#102134]
#### What happened:
A pod with memory request of 50E scheduled on a 8GB node!
- I believe this number caused some overflow or something in `kube-scheduler`. The scheduler passes the pod and this problem spreads afterwards. 
- I'm not aware of the severity of issue but I can imagine scenarios that this could cause damage to cluster's workload.(Fortunately in our case bunch of Alerts and Metric infections was the case.)

#### What you expected to happen:
Simply this pod must stay in Pending and not being scheduled because

#### How to reproduce it (as minimally and precisely as possible):
- get some up and running k8s cluster
- `kubectl apply -f somebug.yaml`
```somebug.yaml
apiVersion: v1
kind: Pod
metadata:
  name: somecrash
spec:
  containers:
  - name: somecrash
    image: alpine  
    resources:
      limits:
        cpu: 200m
        memory: 50E
      requests:
        cpu: 200m
        memory: 50E
```
- `kubectl get po -w` wait for it to be scheduled!!!

#### Anything else we need to know?:
- Events from Output of `kubectl describe po somecrash`:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  14s                default-scheduler  Successfully assigned myNS/somecrash to myNode
  Normal   Pulled     11s                kubelet            Successfully pulled image "alpine" in 2.718539746s
  Normal   Pulling    10s (x2 over 13s)  kubelet            Pulling image "alpine"
  Normal   Created    8s (x2 over 10s)   kubelet            Created container somecrash
  Normal   Started    8s (x2 over 10s)   kubelet            Started container somecrash
  Normal   Pulled     8s                 kubelet            Successfully pulled image "alpine" in 2.200344301s
  Warning  BackOff    6s (x2 over 7s)    kubelet            Back-off restarting failed container
```
- Some side effect for example in 'kubectl describe no myNode':
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests                              Limits
  --------           --------                              ------
  cpu                4245m (70%)                           10735m (178%)
  memory             50000000010377244416 (-32032083726%)  50000000010615271168 (-32032083724%)
  ephemeral-storage  0 (0%)                                0 (0%)
  hugepages-2Mi      0 (0%)                                0 (0%)

```
- I didn't find any useful log in kube-scheduler

#### Environment:
- Kubernetes version (use `kubectl version`): `k8s-1.21 GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479"`
- Cloud provider or hardware configuration: general purpose VM
- OS (e.g: `cat /etc/os-release`):  `Ubuntu20.04`
- Kernel (e.g. `uname -a`): `5.4.0-67-generic`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
/sig scheduling

**Comment by pacoxu** [comment]
/assign 
I will try to reproduce it today.

**Comment by pacoxu** [comment]
`Ei` works. 
> For memory, the unit should be M or Mi, not m, m is the unit for CPU.

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/apis/core/resource.go#L27-L35

```
// <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei
//   (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)
// <decimalSI>       ::= m | "" | k | M | G | T | P | E
//   (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)
// <decimalExponent> ::= "e" <signedNumber> | "E" <signedNumber>
```

You can check https://github.com/kubernetes/kubernetes/issues/49442#issuecomment-320879475 as well.

**Comment by Sin4wd** [comment]
> `Ei` works.
> 
> > For memory, the unit should be M or Mi, not m, m is the unit for CPU.
> 
> https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/apis/core/resource.go#L27-L35
> 
> ```
> // <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei
> //   (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)
> // <decimalSI>       ::= m | "" | k | M | G | T | P | E
> //   (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)
> // <decimalExponent> ::= "e" <signedNumber> | "E" <signedNumber>
> ```
> 
> You can check [#49442 (comment)](https://github.com/kubernetes/kubernetes/issues/49442#issuecomment-320879475) as well.

Actually I didn't use the "E" myself. I tried 5000... testing adding one zero at a time to reproduce the problem. Kubernetes itself translated my number to this. Thus maybe there is a bug somewhere in the manifest sanitizer code.
