### ISSUE TITLE
Guestbook: Error while creating pod.

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10213]
I'm trying to create a pod from the the guestbook for redis on ubuntu machine.

I ran the command:
$ kubectl create -f examples/guestbook/redis-master-controller.json
Error: the server could not find the requested resource

**Comment by adyanthaya17** [comment]
# kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.0", GitCommit:"754d3ce99ee50f392369868bf6ba1e866801b086", GitTreeState:"clean"}

**Comment by nikhiljindal** [comment]
Seems similar to https://github.com/GoogleCloudPlatform/kubernetes/issues/9945. Updating kubectl and cluster to 0.19 might fix this.

**Comment by jlowdermilk** [comment]
```
Error: the server could not find the requested resource
```
That error is seen when a old client talks to the apiserver using an unknown/unsupported version. Updating to 0.19 should fix.

**Comment by mbforbes** [comment]
@adyanthaya17 can you please confirm whether updating solves this? And close this issue if so?

**Comment by adyanthaya17** [comment]
I have a release-0.19.0 directory in my kubernetes. I ran the command in the release-0.19.0 path and the command worked.
