### ISSUE TITLE
sched: revisit preference algorithm of extended resources in heterogeneous env

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#102154]
In https://github.com/kubernetes/kubernetes/pull/101946#discussion_r634645359, we found that if extended resources are specified in scheduler plugin args, it's actually not properly scored on a heterogeneous cluster - i.e., machines may have or not have that extended resource. This problem exists in plugins `LeastAllocated`, `MostAllocated` and `RequestedToCapacityRatio`, and will also impact `BalancedAllocation` if we add support for extended resource in it.

Here is an example to illustrate the problem. Suppose we have 3 nodes, and {cpu, mem, gpu} are registered through pluginArgs and all weighted 1. And suppose below is the current requested/capacity usage:

|       | cpu | mem | gpu |
|-------|-----|-----|-----|
| node1 | 4/8 | 4/8 | 2/8 |
| node2 | 4/8 | 4/8 | 4/8 |
| node3 | 4/8 | 4/8 | 0/0 (no gpus) |

Then there comes a best-efforts Pod, it will be scored like this:

|       | cpu | mem | gpu                                         |
|-------|-----|-----|---------------------------------------------|
| node1 | 50  | 50  | 75 (least requested)<br>25 (most requested) |
| node2 | 50  | 50  | 50                                          |
| node3 | 50  | 50  | 0                                           |

As you can see, node3 is not selected in either least or most requested plugin, but shouldn't it be favored in both cases? As putting it to node3 would leave the cpu/mem room in node1/node2 unoccupied, so later Pods that request gpu can get more chances to be successfully scheduled to node1/node2 - instead of being pending due to shortage of cpu/mem which may have been occupied by pods not requesting gpu.

/sig scheduling

**Comment by alculquicondor** [comment]
So to clarify: the desired final score for node3 should be `(50+50)/2`, rather than `(50+50+0)/3`.

**Comment by Huang-Wei** [comment]
> So to clarify: the desired final score for node3 should be `(50+50)/2`, rather than `(50+50+0)/3`.

Yes, it shouldn't be `(50+50+0)/3`. Probably we will change to `(50+50)/2`, or `(50+50+100)/3`. We can discuss the implementation details later.

**Comment by chendave** [comment]
+1 to `(50+50+100)/3` so that node3 will be preferred compared with node2

**Comment by alculquicondor** [comment]
why should be preferred? Should it be for both Least and Most?

I'm thinking that the preference should be on the user. In this case, they could set up a node label and do preferred node affinity.

**Comment by Huang-Wei** [comment]
> why should be preferred? Should it be for both Least and Most?

The extended resource can be thought of as "scarce" resources, so favoring node3 over node1/node2 literally means "don't interrupt node1/node2". But the preference algorithm needs to be designed sophisticatedly - here the score on cpu/mem gets a tie, so it's easy to say node3 is favorable, but what if scoring on cpu/mem on node3 is lower? should we still consider node3? or, to what extent it's lower than other nodes, then we favor it? These are the algorithm details we should discuss in the next step. For now, let's get a consensus on whether we need to optimize the algorithm.

BTW: we may leverage the [DRF](https://cs.stanford.edu/~matei/papers/2011/nsdi_drf.pdf) algorithm to ensure the resource fairness.

**Comment by alculquicondor** [comment]
I think we have consensus that we need to improve the algorithm :)

**Comment by alculquicondor** [comment]
can we proceed? we don't have much time left until the code freeze.

**Comment by chendave** [comment]
@Huang-Wei are you still working on this?

**Comment by alculquicondor** [comment]
From the SIG meeting:
If you have nodes with scarce resources (like GPUs), those nodes should have a taint so that pods that don't request the resource don't get scheduled there. Then, the remaining of the nodes should be scored as if the resource didn't exist.
In conclusion, we should go for `(50+50)/2` instead of `(50+50+100)/2`.

FTR, @Huang-Wei is out this week.

**Comment by chendave** [comment]
> If you have nodes with scarce resources (like GPUs), the best practice is that these nodes should have a taint so that pods that don't request the resource don't get scheduled there. Then, the remaining of the nodes should be scored as if the resource didn't exist.
In conclusion, we should go for (50+50)/2 instead of (50+50+100)/3.

Good idea, that makes the things easier.

**Comment by Huang-Wei** [comment]
>  the best practice is that these nodes should have a taint so that pods that don't request the resource don't get scheduled there

With this as an assumption, yes, (50+50)/2 is a neat algorithm.
