### ISSUE TITLE
Short running pods take very long to teardown

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#102149]
In master we continue to see instances of short running pods failing to terminate quickly, due to races between sources of truth.

https://github.com/kubernetes/kubernetes/pull/102025#issuecomment-843622820 stops e2e tests from "cheating" and bypassing kubelet shutdown, and as a result some tests fail predictably (garbage collection lots of short running pods for testing various behaviors).  The linked comment shows a pod that is racing between container start and pod delete.  The problem is that dispatchWork invokes `podAndContainersAreTerminal()` on the containerstart event, but the cache that `podAndContainersAreTerminal` checks is not yet up to date (that's handled inside UpdatePod / syncPod).

In general, the pod worker is the one who should be managing shutdown.  We added optimizations to dispatchWork to skip the pod worker, and we historically had a race condition where the pod worker was shut down too early and thus termination never happened, but the right thing to do is to stop trying to optimize the pod worker knowing the state of the pod (it's job is to sync the pod) and instead make sure that a) the pod worker is running until a pod is deleted from api (which should be true today) and b) if we need to reduce latency of shutdown, we should do so by ensuring the pod worker gets that update.

The failures here are a significant violation of our performance goals around pods, and our e2e tests are demonstrating the failures pretty cleanly, so we need to put this race condition to bed.

https://github.com/kubernetes/kubernetes/pull/102025 can trigger the issue trivially, so for now using that to debug failure reasons.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/issues/88766 is related to this, as is https://github.com/kubernetes/kubernetes/pull/98507

After some discussion, the core race is that only syncPod (and the pod worker) knows whether container starts are in progress, and therefore is the only component that can also safely answer "are all containers for a pod stopped" within the kubelet.  Other components would then check with pod workers.  That implies pod worker must be running until such a time as all containers are stopped, which again makes the pod worker the best to manage "is this UID still alive".  We may also have to fix controllers like the volume attach controller that check pod status from the api by more rigorously indicating a terminal condition on the pod (all containers are stopped and no new containers can be started), but that will require input from the storage team.

We will be testing this change out shortly and #98507 should be layered on top of it, because we want to make changes to pod worker that capture some of the same info.

**Comment by ehashman** [comment]
@smarterclayton can this be closed? Was this fixed as part of the 1.22 refactor?

**Comment by ehashman** [comment]
/remove-lifecycle rotten
/close

I believe this was addressed by the 1.22 pod lifecycle refactor; we haven't seen short-lived pods getting stuck in a while, and it is particularly easy to trigger this in CI.
