### ISSUE TITLE
[sig-windows] [Feature:Windows] GMSA Full [Serial] [Slow] GMSA support works end to endChanges

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#102113]
#### Which jobs are failing:
https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-containerd-serial-slow-master
https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-dockershim-serial-slow-master

#### Which test(s) are failing:
[sig-windows] [Feature:Windows] GMSA Full [Serial] [Slow] GMSA support works end to endChanges

#### Since when has it been failing:
5/12/2021

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows-serial-slow/1394453762159939584

#### Reason for failure:
gmsa CRD is using v1beta1 apis

#### Anything else we need to know:
started fix: https://github.com/kubernetes-sigs/windows-gmsa/pull/31

/sig windows
/triage accepted

**Comment by chewong** [comment]
Still failing in 1.18 - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-1-18-windows-serial-slow/1396942953200488448. Is this expected?
