### ISSUE TITLE
Track unwanted dependencies, add ratcheting presubmit

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#102145]
#### What would you like to be added:

Add a file to track dependencies we want to remove or avoid picking back up. Examples:
* github.com/go-kit/kit
* k8s.io/klog (as opposed to k8s.io/klog/v2)
* github.com/go-openapi/{analysis,spec,strfmt,validate}
* http://github.com/influxdata/influxdb1-client
* go.mongodb.org/mongo-driver
* github.com/hashicorp/hcl
* github.com/hashicorp/golang-lru
* github.com/spf13/viper (https://github.com/kubernetes/kubernetes/pull/102598)
* rsc.io/quote and rsc.io/sampler (https://github.com/kubernetes/kubernetes/pull/102833)
* github.com/go-bindata/go-bindata (https://github.com/kubernetes/kubernetes/pull/99829)

Add a presubmit that uses `go mod graph` to do the following:
1. Checks if any items in the "unwanted but still present" list are no longer present and prompts to move them to the "absent and not allowed" list
2. Checks if any items in the "absent and not allowed" list are present and fails.

#### Why is this needed:

Dependency updates often reintroduce problematic dependencies that were previously dropped.

/area code-organization
/cc @dims

**Comment by pacoxu** [comment]
I may help with it.
/assign

**Comment by liggitt** [comment]
> I checked the code, there is already a logic to check forbidden dependencies.

yeah, that was added sort of ad-hoc, and doesn't do the ratcheting bit we want (record a dependency we have but don't want, once we no longer use it, require moving it to the forbidden list)
