### ISSUE TITLE
Inconsistencies in `queueset.go`

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102299]
#### What happened:
I reviewed the current code to see what had been done to generalize request width.  I found a few inconsistencies in `apiserver/pkg/util/flowcontrol/fairqueuing/queueset/`.

A really simple one is at line https://github.com/kubernetes/apiserver/blob/78f15cef9253969d90e08519943b02c3433c6016/pkg/util/flowcontrol/fairqueuing/queueset/queueset.go#L746 , where `S` is subtracted from the product `G * seats` but should have been subtracted from just `G` (and their difference multiplied by `seats`).

With that fixed, a queue's `virtualStart` tracks the expected "virtual time" (`R(t)` in the original paper) when the oldest waiting request will start.  However, https://github.com/kubernetes/apiserver/blob/78f15cef9253969d90e08519943b02c3433c6016/pkg/util/flowcontrol/fairqueuing/queueset/types.go#L106-L112 computes the expected finish "virtual time" of the J'th request by multiplying by `G` but not `seats`.

#### What you expected to happen:

There should be a consistent notion of "virtual time" (AKA `R(t)`), either always including seats or excluding them.

#### Environment:
- Kubernetes version (use `kubectl version`): latest k8s/apiserver sources
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@tkashem 
@wojtek-t 
@deads2k 
@lavalamp

**Comment by MikeSpreitzer** [comment]
BTW, I suspect it would be better if "virtualTime" is not multiplied by request width.  I am working on writing.

**Comment by MikeSpreitzer** [comment]
I am running into a dilemma.  The whole point of "virtual time" --- R(t) in the original paper --- is that it is shared among all the queues.  They all get work done at the same rate, dR/dt.  But when we generalize so that requests have different widths (and thus work is the sum over requests of `width*duration`), even restricting the virtual world so that a queue runs only one request at a time does not save us from the fact that different queues get work done at different rates.  Even discarding fairness, and executing one request per queue at a time in the virtual world, it looks like what can be shared among queues is not a matter of work done.

**Comment by MikeSpreitzer** [comment]
But the current implementation approach makes the assumption that all the non-empty queues get work done at the same rate.  As long as we are willing to tolerate the lossages due to that fiction, the queues can share one R(t) meter.

**Comment by lavalamp** [comment]
I see both sides of this; I still think it is double counting to use W*D to advance virtual time AND to occupy W seats. OTOH, I also think it is right that we should be fair over the work (W*D) -- not just duration.

One crazy idea is to add the request to multiple queues, and not execute it until it gets to the head of all the queues it is in. The number of queues it needs to be added to would be (# queues) * W / seats, rounded up I guess.

**Comment by MikeSpreitzer** [comment]
I think "virtual time" is a fuzzy and not easy to think about precisely.  That's why I did a careful write-up with quantitative reasoning, and using a well motivated function `R(t)` like in the original paper.  In the KEP revision I am preparing, I think

- the problem statement (https://github.com/MikeSpreitzer/kube-enhancements/tree/max-min-list/keps/sig-api-machinery/1040-priority-and-fairness#fair-queuing-for-server-requests-problem-statement)

- the equations defining intended behavior (https://github.com/MikeSpreitzer/kube-enhancements/tree/max-min-list/keps/sig-api-machinery/1040-priority-and-fairness#fair-queuing-for-server-requests-with-equal-allocations-intended-behavior)

- the implementation discussion (https://github.com/MikeSpreitzer/kube-enhancements/tree/max-min-list/keps/sig-api-machinery/1040-priority-and-fairness#implementation-of-fair-queuing-for-server-requests-with-equal-allocations-technique-and-problems)

make sense.  It is in the last of those that `R(t)` is introduced, and I think it is clear that this should be a measure that includes request width.

**Comment by wojtek-t** [comment]
> I see both sides of this; I still think it is double counting to use W*D to advance virtual time AND to occupy W seats. OTOH, I also think it is right that we should be fair over the work (W*D) -- not just duration.

I don't think it's double counting, because those are different things.

And yes - we should be fair over W*D - this is exactly why I wanted to push virtual time by W*D.

@MikeSpreitzer - I've seen your KEP PR, just I'm under water. My Fridays are real working time, so I will take a look tomorrow.
