### ISSUE TITLE
NetPol tests arbitrarily enforce the requirement "cluster DNS must be on pod port 53"

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#102286]
#### What happened:
The NetPol tests assume that creating a policy that blocks all egress except to UDP port 53 will still allow DNS. This does not work on OCP because while the DNS _Service_ is on `port: 53`, it redirects to `targetPort: 5353` on the DNS _Pods_ (so that the pods don't need to be pointlessly granted the `NET_BIND_SERVICE` capability), so a policy that only allows to port 53 will block DNS in this case.

#### What you expected to happen:
If Conformance does not require CoreDNS to run on port 53, then the NetPol tests should likewise not require it.

#### How to reproduce it (as minimally and precisely as possible):
Run e2e suite on OCP with ovn-kubernetes. Or else run on plain kube with DNS pods using a different port, with the DNS service mapping from 53 to that port.

#### Anything else we need to know?:
This was fixed for the old NetworkPolicy tests in https://github.com/kubernetes/kubernetes/pull/95453 by making them not use DNS. I still argue that there is absolutely no need to use DNS in the NetworkPolicy tests, because NetworkPolicy only operates on IPs, not on DNS names, so using DNS is just adding a gratuitous extra step that can fail spuriously (as it does here).

/cc @jayunit100

**Comment by jayunit100** [comment]
hey ! thanks for noticing this dan !  ok yeah lets fix this !

**Comment by jayunit100** [comment]
yo @mattfenwick im gonna make a `Prober` interface on the kubemanager to decouple it as an arg, just fyi

**Comment by mattfenwick** [comment]
💯 okay let me know if I can help @jayunit100 , sounds like that'll work fine ! 👍
