### ISSUE TITLE
Move scheduler plugin defaulting to ComponentConfig defaulting logic

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102211]
Currently if the user sets a plugin configuration, parsing and defaulting for unset parameters for a plugin config is properly handled during [conversion](https://github.com/kubernetes/kubernetes/blob/fed3a4520d99a2d99fd4ed0f7edf1ac79e7253e7/pkg/scheduler/apis/config/v1beta1/conversion.go#L162).

However, in the case were the user doesn't specify a plugin config at all, then generating a default plugin config happens when we [instantiate the framework](https://github.com/kubernetes/kubernetes/blob/fed3a4520d99a2d99fd4ed0f7edf1ac79e7253e7/pkg/scheduler/framework/runtime/framework.go#L421)

This is not proper, and I propose we move the latter to happen during conversion. This will ensure that the plugin configuration are properly defaulted from the beginning, and any "hacks" we needed to do down stream to handle legacy configurations (like the [extenders ignoredExtendedResources](https://github.com/kubernetes/kubernetes/blob/fed3a4520d99a2d99fd4ed0f7edf1ac79e7253e7/pkg/scheduler/factory.go#L126)) is applied to a properly defaulted configuration.

/sig scheduling

**Comment by yuzhiquan** [comment]
/triage accepted
/assign
This is refs https://github.com/kubernetes/kubernetes/pull/101822#discussion_r636946012, and i would like to resolve this.
@ahg-g does this issue should wiat for https://github.com/kubernetes/kubernetes/pull/99597 merged first?

**Comment by ahg-g** [comment]
> /triage accepted
> /assign
> This is refs [#101822 (comment)](https://github.com/kubernetes/kubernetes/pull/101822#discussion_r636946012), and i would like to resolve this.
> @ahg-g does this issue should wait for #99597 merged first?

I think you can start, once #99597 is merged, we add the defaulting to v1beta2.

**Comment by yuzhiquan** [comment]
@ahg-g 
I have some questions:
1. if just fix ci failed in #101822 , may be add `registerPriorityConfigProducer` in https://github.com/kubernetes/kubernetes/blob/2d79ebbe588ffcf82c2a4e7667b9ee7c478378a9/pkg/scheduler/framework/plugins/legacy_registry.go#L223 for nodefit score plugin, in producer function can handle `NodeResourcesFitArgs == nil`, add default config for args, then in https://github.com/kubernetes/kubernetes/blob/fed3a4520d99a2d99fd4ed0f7edf1ac79e7253e7/pkg/scheduler/factory.go#L126 here only update the IgnoredResources field.
2. Confused on 
> I propose we move the latter to happen during conversion. This will ensure that the plugin configuration are properly defaulted from the beginning, and any "hacks" we needed to do down stream to handle legacy configurations (like the extenders ignoredExtendedResources) is applied to a properly defaulted configuration.

it's likely to add new method to every plugin, such as defaultconfig?
Did i miss something?

**Comment by ahg-g** [comment]
If you don't mind, let me take this one. We need to move the group of default plugins to be set during CC defaulting logic. It is not quite straightforward to do.

**Comment by yuzhiquan** [comment]
> If you don't mind, let me take this one. We need to move the group of default plugins to be set during CC defaulting logic. It is not quite straightforward to do.

Sure,it's my pleasesure to learn something from your code.
/unassign
/assign @ahg-g
