### ISSUE TITLE
Pod stuck in pulling image 

### ISSUE THREAD

**Issue by ahmeddrawy** [kubernetes/kubernetes#102263]
#### What happened:
Pod stuck in pulling image state
#### What you expected to happen:
pull image correctly
#### Anything else we need to know?:
Running using Minikube v1.18.1

#### Environment:
- Kubernetes version (use `kubectl version`):
 ```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
`Linux tw3-pc 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by n4j** [comment]
@ahmeddrawy Could you provide more details like which image you were trying to pull and are you experiencing this issue consistently?

**Comment by SergeyKanzhelev** [comment]
1.20 is not known for issues with image pulling. Likely something very specific to the pod and image. I will close the issue as we need more specifics on repro steps, and ideally, the kubelet logs for the repro. Please reopen when you have more details

/close

**Comment by pacoxu** [comment]
link to https://github.com/kubernetes/kubernetes/issues/59376#issuecomment-867507042 which has some discussions on image pull issue
