### ISSUE TITLE
Renewing certs including CA after expiration causes Unauthorized

### ISSUE THREAD

**Issue by DrissiReda** [kubernetes/kubernetes#102283]
I'm running kubernetes 1.16.9 with a single master and multiple workers.

Certificates expired and now I attempted to renew certs.
Simply running on master: 
```
kubeadm alpha certs renew all
reboot
```
didn't do anything, ca was already expired (my bad, non default 10 years validity).

So I deleted all pki and conf files inside /etc/kubernetes/pki.

Then I ran:
```
kubeadm init phase certs all
kubeadm init phase kubeconfig all
reboot
```

This worked and I can do use kubectl, but all nodes show "Unauthorized" on all requests on `systemctl status kubelet`

I thought this was related to tokens, so I deleted all "default" serviceaccounts in all namespaces so the tokens would be created again.

Current state of the cluster: all nodes on "NotReady" and all queries to the kube api return Unauthorized.

How can I get rid of this? Any fast workarounds? wasn't kubeadm init supposed to take care of updating new configs?

I can't afford to run kubeadm reset, I want to fix my cluster without having to resort to that.

**Comment by neolit123** [comment]
> I'm running kubernetes 1.16.9 with a single master and multiple workers.

this version is out of support. bug fixes can be backported back to 1.19+.

> didn't do anything, ca was already expired (my bad, non default 10 years validity).

CA rotation is a complicated topic and is documented here:
https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/

the kubernetes/kubernetes issue tracker is not the right place to ask for support.
you can try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/remove-kind bug
/kind support
/close
