### ISSUE TITLE
additional gate when deleteing namespace

### ISSUE THREAD

**Issue by sureshpalemoni** [kubernetes/kubernetes#102274]
#### What would you like to be added:
Sometime, a namespace gets deleted accidentally, as a result all of the resources in it gets deleted. As a precaution, we should have additional gate before it gets deleted. Confirm the namespace after deletion.

#### Why is this needed:
Additional security when accidental deletion of namespace.

**Comment by rburruss022** [comment]
This would be super helpful for new users

**Comment by eddiezane** [comment]
Hi @sureshpalemoni,

I'm currently working on a KEP for additional protection with kubectl delete.

https://groups.google.com/g/kubernetes-dev/c/y4Q20V3dyOk

Would you be interested in providing a user story for the KEP?

**Comment by eddiezane** [comment]
Let's consolidate discussion of this in the KEP.

/close
