### ISSUE TITLE
Support pod selection with custom rules

### ISSUE THREAD

**Issue by suigh** [kubernetes/kubernetes#102271]
#### What would you like to be added:
Provide an interface so that the user can return a preferred pod to scheduler from the un-scheduled pods.

#### Why is this needed:
Current scheduler plugin provides `Less` function to sort the pods, `heapsort` is used as the algorithm. `heapsort` is fast, while it will not work if the values that used for sorting can be changed dynamically, this is the limitation of `heapsort`.

One use case:
There are many pods from 2 users (userA and userB) , and the target is to ensure the `resource usage` (E.g. userA gets x CPUs) between userA and userB is 1:1. Here, we should use the `resource usage`  to sort pods in `Less` function, because the `resource usage` for userA/userB will be updated dynamically once a pod is selected and bond, we will not always get the next expected pod because of the limitation of `heapsort`. 

One workaround is to let the scheduler to re-sort all the left pods after one pod is selected, while re-sorting all the pods is expensive; even we update the `heapsort` with another algorithm, the re-sorting is still necessary. We should leave the sorting logic to the end user, and end user can provide optimized algorithm.

#### Details:
Like the scheduler plugin, provide a pod queue that can be implemented by end user, such a queue can:
1. Accept unscheduled pods.
2. Popup unscheduled pod with custom rules to scheduler

With this enhancement, we can also get some benefits:
1. FCFS for the pods.
2. Re-schedule all pods when there is something change (E.g. some resources are released)

/sig scheduling

**Comment by Huang-Wei** [comment]
There are 2 requirements here: dynamic sorting in internal queue and associate scheduler with user's tenancy model.

For now, there is one global internal queue (activeQ) to pop and schedule pods, and hence we adopt the (static) heapsort to order the pending pods. I'm not quite a fan of dynamically sorting ALL pods inside one global queue, as it inevitably applies performance overhead, and it's unacceptable for users who don't want this feature at all.

Dynamic may make sense when we introduce multiple sub-queue support. Say, we can have multiple sub-queues, and given the number of that is not large, it might be ok to do dynamic sorting in the scope of sub-queues, and (static) pod soring happens inside each sub-queue. In this way, the performance overhead may be acceptable. Also, we can associate sub-queue to user's tenancy model, and hence make it possible to pop Pods from different tenants (via sub-queues) dynamically.

Above is my 2 cents. But feel free to draft a google doc if you already have a feasible solution.

**Comment by suigh** [comment]
@Huang-Wei 

Here is the google doc, let's discuss the details on it.
https://docs.google.com/document/d/1HT9VLFcVccTCs7ucTkD2iyYSgR23cBiAP84l0nTQYH4/edit?usp=sharing

**Comment by Huang-Wei** [comment]
/close

We can continue the discussion in  #93591.
