### ISSUE TITLE
--all-namespaces does not work with kubectl describe pods

### ISSUE THREAD

**Issue by RouR** [kubernetes/kubernetes#102214]
--all-namespaces does not work with `kubectl describe pods --all-namespaces  some-pod-name`

```error: a resource cannot be retrieved by name across all namespaces```

#### Expected
Flag --all-namespaces is works

#### Known workaround
`kubectl describe pods --namespace=pod-namespace some-pod-name`

Similar issue https://github.com/kubernetes/kubernetes/issues/26303

#### Environment:
v1.20.6

`kubectl version`
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by gautierdelorme** [comment]
@RouR `kubectl describe pods --all-namespaces` should work. As for passing the name it seems to be by design: https://github.com/kubernetes/kubernetes/issues/15834#issuecomment-249568245.

**Comment by palnabarun** [comment]
I think the design choice made in https://github.com/kubernetes/kubernetes/issues/15834#issuecomment-249568245 is correct.

You achieve what you are asking by composing the functionality of command-line constructs like the following:

```
$ kubectl describe po -n $(kubectl get pods --all-namespaces -o json | jq -r '.items[] | select(.metadata.name | test("pod-you-want")).metadata.namespace') pod-you-want
...
```

**Comment by eddiezane** [comment]
The above comments are correct. This was the designed implementation.

/close
