### ISSUE TITLE
Create integration tests of k8s.io/component-base/logs library

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#102237]
To test json logging in core Kubernetes components, we are rolling out a set of e2e Kind test https://github.com/kubernetes/kubernetes/issues/100748. Running Kind cluster with json tests the components in exact configuration as it will be deployed on cluster, but it has couple of downsides:
* Hard to test configuration matrix - requires recreating cluster 
* There is no portable way to get logs for testing - https://github.com/kubernetes/kubernetes/issues/100748#issuecomment-841699949

As all core components use same library, instead of testing specific component we should be able to create a new component for testing component-base, pass flags and verify stdout/stderr.
 TODO:
* Find a code location and implement a minimal component that uses `k8s.io/component-base/logs`
* Add tests that verify log output

/wg structured-logging
/wg component-standard
/cc @BenTheElder @mtaufen @stealthybox 

CCing WG structured logging meeting attendees that were interested in testing
/cc @ravitri @krzysiekg @pchan @sladyn98

**Comment by BenTheElder** [comment]
Is there a reason to go to the extent of building and pushing an image and running a pod versus just having a "unit" / "integration" test that forks/execs something using it?

**Comment by serathius** [comment]
Fork/exec should work as long we have can pass flags to process and read it's stdout. Any idea if there are similar tests in k/k that we could take a look at and copy?

**Comment by serathius** [comment]
/priority important-soon
This issue is based on feedback from Kubelet migration retrospection, it is required before organizing migration of next component.
CC @kubernetes/wg-structured-logging-members

**Comment by sladyn98** [comment]
Yeah, if there are examples that we can go off we can get started on this, i will probe around the codebase.

**Comment by serathius** [comment]
/milestone v1.22
Part of work go graduate JSON log format.

**Comment by voigt** [comment]
Due to v1.22 code freeze, I'm moving this issue to the next release.

/milestone v1.23

**Comment by serathius** [comment]
Idea, we could utilize existing example to verify do test logging library and confirm that documentation works is correct https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base/logs/example

**Comment by serathius** [comment]
@sladyn98 you haven't made any updates for over 5 months, please let me know if you are still planning to work on it.

/unassign

**Comment by pchan** [comment]
@serathius Can you assign this to me. I have started working on this.
