### ISSUE TITLE
Update etcd to v3.5.0

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#102294]
/sig scalability

This issue is tracking process of upgrading etcd to 3.5.0 planned for 1.22 K8s release.

Etcd has recently released Beta versions https://github.com/etcd-io/etcd/issues/12970 and is starting the process of correctness and performance testing. To reduce change of finding performance regression late, we will start qualifying Beta Etcd releases on GKE master branch and will upgrade to 3.5.0 as soon as it is available. 

Steps:
* [x] Do preliminary scale testing of etcd v3.5.0-beta.3 release 
* [x] Release etcd v3.5.0-beta.3 image (https://github.com/kubernetes/kubernetes/pull/102277, https://github.com/kubernetes/k8s.io/pull/2101)
* [x] Release etcd v3.5.0-rc.0 image (https://github.com/kubernetes/kubernetes/pull/102585)
* [x] Upgrade etcd server to v3.5.0-rc.0 (https://github.com/kubernetes/kubernetes/pull/102062)
* [x] Wait for 3.5.0 release and upgrade etcd client (https://github.com/kubernetes/kubernetes/pull/100488)
* [x] Release etcd v3.5.0 image (https://github.com/kubernetes/kubernetes/pull/102909, https://github.com/kubernetes/k8s.io/pull/2236)
* [ ] Upgrade etcd server to v3.5.0

/milestone v1.22

**Comment by pacoxu** [comment]
> - [ ] Release etcd v3.5.0 image

Does this meant that the 3.5.0 should be promoted like https://github.com/kubernetes/k8s.io/pull/1183.

**Comment by serathius** [comment]
Yes, created https://github.com/kubernetes/k8s.io/pull/2101

**Comment by justaugustus** [comment]
/area release-eng release-team
/sig release

For tracking:
cc: @kubernetes/release-engineering @kubernetes/release-team

**Comment by pmmalinov01** [comment]
I do think this can be pointed in the Major Themes for the 1.22 release. I would like your opinions @justaugustus @serathius  on this. If you do think it has a place in it, I will add it to the [Github Discussion](https://github.com/kubernetes/sig-release/discussions/1575).

**Comment by samuelarogbonlo** [comment]
How can I be a contributor to this issue? what are the technical checklist that needs to be achieved to close out on the issue?

**Comment by serathius** [comment]
PR https://github.com/kubernetes/kubernetes/pull/102062 to update Etcd is ready, but we found a blocker for merging . There is one test failing https://github.com/etcd-io/etcd/issues/13056
I will take a look into it on Monday, still more eyes on the problem could speed up resolution.

**Comment by justaugustus** [comment]
We'll also need a new kube-cross image w/ etcd v3.5.0.
I'm working on that here: https://github.com/kubernetes/release/pull/2123

**Comment by serathius** [comment]
@pacoxu We just need to upgrade the server to use new image like in https://github.com/kubernetes/kubernetes/pull/102062

**Comment by serathius** [comment]
ok, looks like @pacoxu is busy. Let me take a look
/assign

**Comment by pacoxu** [comment]
Thanks. @serathius
