### ISSUE TITLE
all components of k8s are repeatedly deleted and created

### ISSUE THREAD

**Issue by aduncmj** [kubernetes/kubernetes#102208]
Hi all, 

As shown below, the status of all components of k8s is between pending and running

![image](https://user-images.githubusercontent.com/30764902/119131069-96405e80-ba6b-11eb-8e52-d0c7edf26fff.png)

![image](https://user-images.githubusercontent.com/30764902/119131102-a0faf380-ba6b-11eb-847f-5d6a2b40a196.png)

And logs from `journalctl -f -u kubelet` indicates pods are outdated. Some of detail logs are listed below.

> 5月 21 17:42:14 k8s-master kubelet[1615]: E0521 17:42:14.168690    1615 kubelet.go:2167] Container runtime network not ready: NetworkReady=false reason:Ne
tworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
5月 21 17:42:15 k8s-master kubelet[1615]: W0521 17:42:15.733511    1615 kubelet.go:1622] Deleting mirror pod "etcd-k8s-master_kube-system(d10c0f7f-ba18-11
eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:15 k8s-master kubelet[1615]: W0521 17:42:15.740525    1615 kubelet.go:1622] Deleting mirror pod "kube-apiserver-k8s-master_kube-system(d10c3d
2e-ba18-11eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:15 k8s-master kubelet[1615]: W0521 17:42:15.749751    1615 kubelet.go:1622] Deleting mirror pod "kube-controller-manager-k8s-master_kube-syst
em(d0af2526-ba18-11eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:15 k8s-master kubelet[1615]: W0521 17:42:15.756567    1615 kubelet.go:1622] Deleting mirror pod "kube-scheduler-k8s-master_kube-system(d0b161
f7-ba18-11eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:16 k8s-master kubelet[1615]: W0521 17:42:16.437473    1615 kubelet.go:1622] Deleting mirror pod "etcd-k8s-master_kube-system(d10c0f7f-ba18-11
eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:17 k8s-master kubelet[1615]: W0521 17:42:17.444155    1615 kubelet.go:1622] Deleting mirror pod "etcd-k8s-master_kube-system(d3a06510-ba18-11
eb-84aa-0cc47adadbe0)" because it is outdated
5月 21 17:42:19 k8s-master kubelet[1615]: W0521 17:42:19.169992    1615 cni.go:188] Unable to update cni config: No networks found in /etc/cni/net.d

Has anyone encountered this problem?  What can I do for solving it?

**Comment by navist2020** [comment]
It seems that the cni plugin is not started in your cluster.

**Comment by navist2020** [comment]
You can use the following command after the cluster starts:
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

**Comment by aduncmj** [comment]
> You can use the following command after the cluster starts:
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
> ```

As far as I know, all components except dns can run normally without cni plugin, so I think it's not related with the cni plugin. By the way, the cni plugin I plan to use is contrail-k8s-cni.

**Comment by aduncmj** [comment]
> what is your container runtime version and kubelet version?
> could be a problem with your container runtime.
> 
> do you have enough resources on the node?
> 
> also try asking in https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md for more comments.

There are enough resources on the node. The docker version is 18.06 and the kubelet version is 1.12.9. In addition, the contents of the link you provided are what I am looking for. I will also ask for help in those discussion platforms. Thanks a lot!

**Comment by neolit123** [comment]
1.12 is no longer in support. Please try 1.19 or newer and confirm if the
problem is reproducible with this newer version.

**Comment by matthyx** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
