### ISSUE TITLE
startupProbe  being ignored after restarting the pod 

### ISSUE THREAD

**Issue by judab5ericom** [kubernetes/kubernetes#102230]
/sig architecture
/wg K8s Infra
#### What happened:
Kubernetes bring up Container successfully perform StartupProbe properly,
a few minutes later I make the POD restart by fail the Liveness Prob.
The  container goes down and in the next creation of the POD the startupProbe does not run at all, 
the container starts directly with Liveness and Readiness while startupProbe skipped

#### What you expected to happen:
I expect that  startup probe will run every POD creation

#### How to reproduce it (as minimally and precisely as possible):
Configure POD with all three probes:  Startup/Liveness/Readiness Probe  (Probe should configure to run as EXEC shell script)
Verify that StartupProbe pass sucessfully, Verify that Liveness and Readiness pass sucessfully
Wait few minutes  
Make Liveness to fail 
Verify that POD restart due to Liveness Check,
Verify that POD go up again
Check Logs you should see Liveness probe without startup probe

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"6f6ce59dc8fefde25a3ba0ef0047f4ec6662ef24", GitTreeState:"clean", BuildDate:"2021-04-15T03:23:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

YAML Code Snip:

- Cloud provider or hardware configuration:
Instance run with Ubuntu
$ cat /etc/issue
Ubuntu 18.04.5 LTS \n \l

Using Rancher Docker Kubernetes

- OS (e.g: `cat /etc/os-release`):

- Kernel (e.g. `uname -a`):
Linux xxx 5.4.0-1044-oracle #47~18.04.1-Ubuntu SMP Thu Apr 22 03:29:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
   Rancher
- Network plugin and version (if this is a network-related bug):
- Others:
YAML
startupProbe:
          exec:
            command:
            - /startup_probe.sh
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
		  
 livenessProbe:
          exec:
            command:
            - /liveness.sh
          failureThreshold: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
		  
       readinessProbe:
          exec:
            command:
            - /readiness.sh
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5

**Comment by matthyx** [comment]
/assign
Will take a look on Tuesday... I think this was fixed on master but not sure about cherry picks.
I'll search once back in front of a real computer...

**Comment by wzshiming** [comment]
This is a duplicate Issue #101093
The affected versions are  1.18.18, 1.19.10, 1.20.6, 1.21.0, please try another version.

**Comment by pacoxu** [comment]
@wzshiming it shoud be fixed in 1.18.19 and 1.18.20 by #101226.
/close 

Feel free to reopen if it still exists. @judab5ericom
