### ISSUE TITLE
ping6 service-name and ping6 node-ip do not work for dual-stack IPv6 address

### ISSUE THREAD

**Issue by timscm** [kubernetes/kubernetes#102210]
#### What happened:
1. I used `kubeadm init --config kubeadm.yaml` to install k8s cluster.
2. then I run `kubectl apply -f calico_etcd.yaml` to provide k8s cni.
3. then next, I run `kubectl apply -f my.yaml` to create deployment, 2 replicas.
4. then next, I run `kubectl apply -f mysvc.yaml` to create service, configurated ipFamilyPolicy: PreferDualStack
5. now I run `kubectl describe pod my-76dc8c4557-bx6p8 my-76dc8c4557-fh9j6`, there are IPv4 and IPv6 address, my-76dc8c4557-bx6p8: 100.110.3.196, 100::d572:dd0:e9cf:e2c3, my-76dc8c4557-fh9j6: 100.110.3.197, 100::d572:dd0:e9cf:e2c4
6. now I run `kubectl describe svc my`, there is IPv4 and IPv6 address: 10.102.104.15, 10::b769 
7. then I enter my pod `kubectl exec -it my-76dc8c4557-bx6p8 -- bash`, and in this pod, I do these checks:

check1 IPV4 pod to pod: `ping  100.110.3.197`, result: PASS
check2 IPv6 pod to pod: `ping6 -n 100::d572:dd0:e9cf:e2c4`, result: PASS
check3 IPv6 pod to pod(no -n option): `ping6 100::d572:dd0:e9cf:e2c4`, result: PASS, but get warning info: "ping: getnameinfo: Temporary failure in name resolution".
check4 IPv4 pod to svc: `ping mysvc`, result: PASS
check5 IPv6 pod to svc: `ping6 mysvc`, result: FAIL, show me message: "ping6: unknown host mysvc"
check7 mysvc type change to NodePort, there is NOT IPv6 ipvs rules, result: FAIL, my steps as follow:

After that, I setup my node an IPv6 address, 130::4/64, gateway: 130::254, both node IPv4 and IPv6 at the same interface eth0, IPv4 address is: 130.255.0.4, and the IPv6 address is: 130::4/64, the env:
1. Node1: installed k8s, IPv4: 130.255.0.4, IPv6: 130::4/64
2. Node2: no any k8s, IPv4: 130.255.0.5, IPv6: 130::5/64

Then I run `kubectl edit svc mysvc` and setup the type from "ClusterIp" to "NodePort", after this I check `ipvsadm -ln` does not show me any NodeIP IPv6 rules:

TCP  10.102.104.15:10086 rr
  -> 100.110.3.196:10086		 Masq	1	0	0
  -> 100.110.3.197:10086		 Masq   1   0   0
TCP  130.255.0.4:31283 rr
  -> 100.110.3.196:10086		 Masq	1	0	0
  -> 100.110.3.197:10086		 Masq   1   0   0
TCP  [10::b769]:10086 rr
  -> [100::d572:dd0:e9cf:e2c3]:10086		 Masq	1	0	0
  -> [100::d572:dd0:e9cf:e2c4]:10086		 Masq	1	0	0

I found I need to change the kube-proxy configmap, `kubectl -n kube-system edit configmap kube-proxy`, and change the "nodePortAddress: null" to the "nodePortAddress: ["130::4/64", "130.255.0.4/24"]", after this, I run `kubectl -n kube-system delete pod kube-proxy` to restart kube-proxy, and then the `ipvsadm -ln` show me the NodePort IPv6 rules:

TCP  [130::4]:31283 rr
  -> [100::d572:dd0:e9cf:e2c3]:10086		 Masq	1	0	0
  -> [100::d572:dd0:e9cf:e2c4]:10086		 Masq	1	0	0

check8# IPv4 to direct ping Node1 IPv4 address, `ping 130.255.0.4`, result: PASS
check9# IPv6 to direct ping Node1 IPv6 address, `ping6 -n 130::4`, result: PASS
check10# IPv4 to direct ping Node2 IPv4 address, `ping 130.255.0.5`, result: PASS
check11# IPv6 to direct ping Node2 IPv6 address, `ping6 -n 130::5`, result: FAIL, so I added ip6table for NAT, the rule: `ip6tables -t nat -I POSTROUTING -d 130::5 -j SNAT --to-source 130::4`, then the `ping6 -n 130::5` result pass.

config file: kubeadm.yaml 
```yaml
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
featureGates:
  IPv6DualStack: true
networking:
  podSubnet: 100.64.0.0/10,100::/64
  serviceSubnet: 10.96.0.0/12,10::/108
kubernetesVersion: v1.20.7
----
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
```

config file: calico-etcd.yaml, which is download from: 
https://docs.projectcalico.org/manifests/calico-etcd.yaml, and update the related configuration items.

#### What you expected to happen:

I want these things happen:
1. At dual stak env, the container in pod can use its IPv6 to ping6 service name.
2. At dual stak env, the container in pod can use its IPv6 to ping6 Node2 IPv6 address.
3. At dual stak env, I don't need to update kube-proxy configmap, then can get NodePort ipvs rule for IPv6.

#### How to reproduce it (as minimally and precisely as possible):

Login to Node1, assign IPv4, IPv6 address, then:
1. run `kubeadm init --config kubeadm.yaml` to create k8s cluster
2. run `kubectl apply -f calico_etcd.yaml` to create CNI
3. run `kubectl apply -f my.yaml` to create deployment
4. run `kubectl apply -f mysvc.yaml` to create service

That is, can reproduce these issues.

#### Anything else we need to know?:

Nothing more I can provide.

#### Environment:
- Kubernetes version (use `kubectl version`): can reproduce the issue at: v1.20.5, v1.20.7, v1.21.1
- Cloud provider or hardware configuration: virtual host enviroment.
- OS (e.g: `cat /etc/os-release`): CentOS 7.4
- Kernel (e.g. `uname -a`): Linux xxx 3.10.0-1062.el7.x86_64 ... 2019 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico v3.19.0
- Others: no.

**Comment by uablrek** [comment]
ICMP-echo is not load-balanced by K8s (kube-proxy) so `ping` (or `ping6`) to a service address (clusterIP, nodePort or loadBalancerIP) is not intended to work.

That makes this issue a feature request, not a bug.

/kind feature
/remove kind-bug

**Comment by timscm** [comment]
> ICMP-echo is not load-balanced by K8s (kube-proxy) so `ping` (or `ping6`) to a service address (clusterIP, nodePort or loadBalancerIP) is not intended to work.
> 
> That makes this issue a feature request, not a bug.
> 
> /kind feature
> /remove kind-bug

No, as mentioned in the description, the ping service-name CAN work. But ping6 to service name does NOT work. And the ICMP-echo is just my testing method to check the network connection, it's not the purpose. Could you please double check this?

**Comment by uablrek** [comment]
Ping to let's say a `clusterIP`, which is what the service-name resolves to on the cluster, works _only_ with `proxy-mode=ipvs` and _only_ because the clusterIP is actually locally assigned to the `kube-ipvs0` device.

So what you ping is a local address, not any pods. So you can remove all pods and ping to the clusterIP _will still work_!

Also try `proxy-mode=iptables` and `ping` will not work for any service ip.

**Comment by timscm** [comment]
> Ping to let's say a `clusterIP`, which is what the service-name resolves to on the cluster, works _only_ with `proxy-mode=ipvs` and _only_ because the clusterIP is actually locally assigned to the `kube-ipvs0` device.
> 
> So what you ping is a local address, not any pods. So you can remove all pods and ping to the clusterIP _will still work_!
> 
> Also try `proxy-mode=iptables` and `ping` will not work for any service ip.

According your information, so eventhough the ICMP-echo does not work, the network is still can be connected? I tested this because I want the pod IPv6 address can connect to the other service by service name, but I check this by using ping6, it shows me doesn't work, any another testing method can I use? 

And the second question is the pod ipv6 address can not access the node physical address outside of the cluster, I configured my k8s by using dual-stack, both works for IPv4, but when using ipv6 it doesn't.

**Comment by uablrek** [comment]
> so eventhough the ICMP-echo does not work, the network is still can be connected? 

Yes, with TCP (or UDP or SCTP if you use those)

> another testing method can I use?

For TCP you must try to connect. You can disconnect immediately if succesful.

> pod ipv6 address can not access the node physical address outside of the cluster

A bit unclear. I guess your pods can't connect to an ipv6 address outside the cluster?

If so, it is a CNI-plugin problem. Not K8s. For `Calico` you must proably specify;
```
            - name: CALICO_IPV6POOL_NAT_OUTGOING
              value: "true"
```

**Comment by timscm** [comment]
> > so eventhough the ICMP-echo does not work, the network is still can be connected?
> 
> Yes, with TCP (or UDP or SCTP if you use those)
> 
> > another testing method can I use?
> 
> For TCP you must try to connect. You can disconnect immediately if succesful.

But when I try run ping6 service name, the command result show me: unknown host mysvc, may this be the issue of coredns? May coredns do not resolve the dns name to IPv6?

> 
> > pod ipv6 address can not access the node physical address outside of the cluster
> 
> A bit unclear. I guess your pods can't connect to an ipv6 address outside the cluster?
> 
> If so, it is a CNI-plugin problem. Not K8s. For `Calico` you must proably specify;
> 
> ```
>             - name: CALICO_IPV6POOL_NAT_OUTGOING
>               value: "true"
> ```
Oh, I see. I will try this configure item later.

**Comment by aojea** [comment]
> But when I try run ping6 service name, the command result show me: unknown host mysvc, may this be the issue of coredns? May coredns do not resolve the dns name to IPv6?

for resolving dual-stack services you need a newer coredns version that is still not shipped with kubeadm 
https://github.com/kubernetes/kubernetes/issues/99751

**Comment by timscm** [comment]
> > But when I try run ping6 service name, the command result show me: unknown host mysvc, may this be the issue of coredns? May coredns do not resolve the dns name to IPv6?
> 
> for resolving dual-stack services you need a newer coredns version that is still not shipped with kubeadm
> #99751

So I need to wait new version of kubeadm, right? 
And there is another issue: the kubenet need to assign nide ipv6 address to key: nodePortAddresses, and then it will create ipvs rule for the ipv6 address on service nodePort, is this a bug? I thought it is, because IPv4 can keep nodePortAddresses=nill, and can create the ipvs rule for the service nodePort.

**Comment by uablrek** [comment]
> So I need to wait new version of kubeadm, right?

You must upgrade K8s eventually. How it's done, with `kubeadm` or not, doesn't matter.

I don't understand the second question. "kubenet"? You are using Calico, right. I normally don't set `nodePortAddresses` and nodeports are assigned fine.

Anyway, there questions are not related to this issue and is better asked in some forum, e.g. the #sig-network slack channel https://app.slack.com/client/T09NY5SBT/C09QYUH5W. See you there :smiley: 

I close this issue for now. If you want icmp support in kube-proxy the right way is to write a KEP (Kubernetes Enhancement Proposal). Be aware that icmp support is not easy to support, for example `ipvs` have no support.

/close

**Comment by timscm** [comment]
> > So I need to wait new version of kubeadm, right?
> 
> You must upgrade K8s eventually. How it's done, with `kubeadm` or not, doesn't matter.
> 
> I don't understand the second question. "kubenet"? You are using Calico, right. I normally don't set `nodePortAddresses` and nodeports are assigned fine.
> 
> Anyway, there questions are not related to this issue and is better asked in some forum, e.g. the #sig-network slack channel https://app.slack.com/client/T09NY5SBT/C09QYUH5W. See you there 😃
> 
> I close this issue for now. If you want icmp support in kube-proxy the right way is to write a KEP (Kubernetes Enhancement Proposal). Be aware that icmp support is not easy to support, for example `ipvs` have no support.
> 
> /close

Sorry, it's a mistake for kubenet, I mean the kube-proxy, it doesn't create the ipvs rule based on IPv6 node ip, but the kube-proxy will create this when I explicitly update the kube-proxy configmap item "nodePortAddresses: null" to "nodePortAddresses: ["130::4/64", "130.255.0.4/32"]", should be this a bug? Because the kube-proxy doesn't get the interfaces automatically which assigned IPv6 address.

**Comment by uablrek** [comment]
Ah, I see. Yes I think that is a bug related to you extremely old kernel (please upgrade if you can);
https://github.com/kubernetes/kubernetes/issues/93858

But you found a work-around which is great :+1: I'll make a note in the other issue.
