### ISSUE TITLE
 pods scheduled on different node cannot communicate with each other on kubernetes cluster using calico network

### ISSUE THREAD

**Issue by irfansheikh777** [kubernetes/kubernetes#102335]
I am facing  this issue troubleshooting long time issue is  I have create Kubernetes cluster with calico network in my on premises server the **pods scheduled  on  different node on this Kubernetes cluster not able to communicate to each other **  . please chcek below scenarios. 
There are two worker node **server9** and **server10**
Two PODS are created on server 9 and  one pod created on server 10 as u can see below.
**pods within  same node are ale to communicate with each other but pod on another node is not able to communicate with each other.**
Can you please   help me to resolve this as there is no communication between this pods which is issue for application level cluster
![image](https://user-images.githubusercontent.com/29003677/119655874-1c2d2280-be3b-11eb-9af1-4dda4bd7aa93.png)
![image](https://user-images.githubusercontent.com/29003677/119655776-ff90ea80-be3a-11eb-99c8-622308588213.png)

**Comment by pacoxu** [comment]
/sig network
But I think this is a calico issue which should be tracked/discussed in https://github.com/projectcalico/calico.

**Comment by thockin** [comment]
Agree this is for Calico.

/assign @caseydavenport to confirm and close

**Comment by caseydavenport** [comment]
@irfansheikh777 looks like you've already raised an issue on the Calico GitHub so let's continue discussion there (https://github.com/projectcalico/calico/issues/4638) - I don't think we need a kubernetes issue tracing this. Thanks!

/close
