### ISSUE TITLE
[Failing Test][sig-cluster-lifecycle] ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-21

### ISSUE THREAD

**Issue by mkorbi** [kubernetes/kubernetes#102345]
#### Which jobs are failing:
[kubeadm-kinder-latest-on-1-21](https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest-on-1-21&width=20)
#### Which test(s) are failing:
- ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-21
- task-06-e2e-kubeadm

#### Since when has it been failing:
18.05.2021
Failing started with commit e338438b7 after some successful test iterations

#### Testgrid link:

- [Testgrid](https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest-on-1-21&width=20)
- [Spyglass on ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-21 ](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-21/1397575241361788928)
- [Spyglass on task-06-e2e-kubeadm](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-21/1395245098811265024)

#### Reason for failure:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/kubeadm_config_test.go:59
Expected
    <map[string]string | len:1>: {
        "ClusterConfiguration": "apiServer:\n  certSANs:\n  - localhost\n  - 172.17.0.3\n  extraArgs:\n    authorization-mode: Node,RBAC\n  timeoutForControlPlane: 4m0s\napiVersion: kubeadm.k8s.io/v1beta3\ncertificatesDir: /etc/kubernetes/pki\nclusterName: kinder-xony\ncontrolPlaneEndpoint: 172.17.0.7:6443\ncontrollerManager:\n  extraArgs:\n    enable-hostpath-provisioner: \"true\"\ndns: {}\netcd:\n  local:\n    dataDir: /var/lib/etcd\nimageRepository: k8s.gcr.io\nkind: ClusterConfiguration\nkubernetesVersion: v1.21.2-rc.0.5+e338438b72e4af\nnetworking:\n  dnsDomain: cluster.local\n  podSubnet: 192.168.0.0/16\n  serviceSubnet: 10.96.0.0/12\nscheduler: {}\n",
    }
to have key
    <string>: ClusterStatus
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/kubeadm_config_test.go:63
```

**Comment by pacoxu** [comment]
/assign
ClusterStatus is removed from kubeadm recently. I think it would be related.

**Comment by pacoxu** [comment]
E2E in https://github.com/kubernetes/kubernetes/blob/release-1.21/test/e2e_kubeadm/kubeadm_config_test.go#L63 will check ClusterStatus.

I opened #102358 which is cherry-pickof  #102157 to 1.21. It would fix this problem.

**Comment by neolit123** [comment]
@mkorbi after https://github.com/kubernetes/kubernetes/pull/102358 merged https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest-on-1-21&width=20 seems to have turned green with respect to to the failing test in the issue description.

i'm going to close this, but please revise and re-open if needed.

/close
