### ISSUE TITLE
kubectl get command not consistent with overlapping resources kind not in the same group

### ISSUE THREAD

**Issue by secat** [kubernetes/kubernetes#102378]
#### What happened:

The [Kubernetes Gateway API](https://gateway-api.sigs.k8s.io/) and the Istio API both have a resource named Gateway:
```
$ kubectl api-resources
NAME       SHORTNAMES   APIGROUP                       NAMESPACED   KIND
gateways   gw           networking.istio.io/v1beta1            true         Gateway
gateways   gtw          networking.x-k8s.io/v1alpha1           true         Gateway
```

When we are using Istio and the Gateway API in the same Kubernetes cluster, these names will overlap when using `kubectl` on the command line. `kubectl get gateway` might return the Kubernetes Gateway resources and not the Istio Gateway resources or vice versa.

#### What you expected to happen:

I would expect `kubectl get <overlapping resource name>` to return an error and offer me choices like when we use `kubectl logs` over a pod that has multiple containers.

Example:
```
$ kubectl logs prometheus-k8s-0
error: a container name must be specified for pod prometheus-k8s-0, choose one of: [prometheus config-reloader]
```

So I would expect something like:
```
kubectl get gateway
error: a fully qualified domain name must be specified for resource gateways, choose one of: [gateways.networking.istio.io, gateways.networking.x-k8s.io]
```

#### How to reproduce it (as minimally and precisely as possible):

- Install Istio CRDs and new Kubernetes gateway API CRDs.
- Create an Istio gateway resource 
- Create a Kubernetes gateway resource
- Run the command `kubectl get gateway`

#### Environment:
- Kubernetes version: client: v1.21.1, server: v1.18.17-gke.700
- Cloud provider or hardware configuration: GKE

**Comment by navist2020** [comment]
> So I would expect something like:
> 
> ```
> kubectl get gateway
> error: a fully qualified domain name must be specified for resource gateways, choose one of: [gateways.networking.istio.io, gateways.networking.x-k8s.io]
> ```
You can get the correct result to use in the form `<plural>.<group>`, like
```
kubectl get gateway.networking.istio.io
```
or
```
kubectl get gateway.networking.x-k8s.io
```
Their ShortName is also different.

**Comment by secat** [comment]
@navist2020 Thanks for the answer. 

My point is that is not normal that `kubectl get <resource kind>` is not consistent based on which CRDs are installed.

**Comment by lauchokyip** [comment]
/cc @soltysh 
We discussed about similar cases, `kubectl explain` was having the same [issue](https://github.com/kubernetes/kubernetes/pull/91295).

**Comment by lauchokyip** [comment]
We discussed about similar cases, `kubectl explain` was having the same [issue](https://github.com/kubernetes/kubernetes/pull/91295).

**Comment by lauchokyip** [comment]
We discussed about similar cases, `kubectl explain` was having the similiar [issue](https://github.com/kubernetes/kubernetes/pull/91295).

**Comment by eddiezane** [comment]
@ingvagabund any interest in looking at this like you did for explain?

We won't be able to error but we can possibly warn.

**Comment by eddiezane** [comment]
We might want to expose priorities in `kubectl api-resources`. Possibly part of the discovery API.

**Comment by KnVerey** [comment]
When considering this we should keep in mind that we've had cases in the past where a core resource migrated from one group to another and priority-base selection applying automatically across both was desirable (i.e. Deployment and friends moving from extensions to apps).

**Comment by lauchokyip** [comment]
can take a look at this one and put it some of my thoughts

**Comment by ingvagabund** [comment]
@eddiezane if there's someone else who has free time .... Otherwise, I will have some free slots in 2 weeks to take a look.

**Comment by lauchokyip** [comment]
@eddiezane @KnVerey , I looked at the source code and here is what I have found. Also need some inputs on how to solve it.

I will use the resource `pods` as an example. `pods` will match the version Kind, `v1 Pod` and  `metrics.k8s.io/v1beta1 PodMetrics`. The later one is because of metrics server.

In `Builder`, when we want to [find the mapping](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L723) we would first check if the `gvr` is provided, if not then we would parse in the resource without any group or kind and call [`KindFor`](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/cli-runtime/pkg/resource/builder.go#L735) with just the resource name. In this case, it will be `pods`

The problem lies in [`KindFor`](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/api/meta/priority.go#L92). It will first find the `originalGVKs` which will output 
```
[/v1, Kind=Pod metrics.k8s.io/v1beta1, Kind=PodMetrics]

```
and it will loop through the `KindPriority` which look similiar to this
```
[/v1, Kind=* /v1, Kind=* apiregistration.k8s.io/v1, Kind=* apiregistration.k8s.io/v1beta1, Kind=* apps/v1, Kind=* events.k8s.io/v1, Kind=* events.k8s.io/v1beta1, Kind=* authentication.k8s.io/v1, Kind=* authentication.k8s.io/v1beta1, Kind=* authorization.k8s.io/v1, Kind=* authorization.k8s.io/v1beta1, Kind=* autoscaling/v1, Kind=* autoscaling/v2beta1, Kind=* autoscaling/v2beta2, Kind=* batch/v1, Kind=* batch/v1beta1, Kind=* certificates.k8s.io/v1, Kind=* certificates.k8s.io/v1beta1, Kind=* networking.k8s.io/v1, Kind=* networking.k8s.io/v1beta1, Kind=* extensions/v1beta1, Kind=* policy/v1, Kind=* policy/v1beta1, Kind=* rbac.authorization.k8s.io/v1, Kind=* rbac.authorization.k8s.io/v1beta1, Kind=* storage.k8s.io/v1, Kind=* storage.k8s.io/v1beta1, Kind=* admissionregistration.k8s.io/v1, Kind=* admissionregistration.k8s.io/v1beta1, Kind=* apiextensions.k8s.io/v1, Kind=* apiextensions.k8s.io/v1beta1, Kind=* scheduling.k8s.io/v1, Kind=* scheduling.k8s.io/v1beta1, Kind=* coordination.k8s.io/v1, Kind=* coordination.k8s.io/v1beta1, Kind=* node.k8s.io/v1, Kind=* node.k8s.io/v1beta1, Kind=* discovery.k8s.io/v1, Kind=* discovery.k8s.io/v1beta1, Kind=* flowcontrol.apiserver.k8s.io/v1beta1, Kind=* acme.cert-manager.io/v1, Kind=* acme.cert-manager.io/v1beta1, Kind=* acme.cert-manager.io/v1alpha3, Kind=* acme.cert-manager.io/v1alpha2, Kind=* cert-manager.io/v1, Kind=* cert-manager.io/v1beta1, Kind=* cert-manager.io/v1alpha3, Kind=* cert-manager.io/v1alpha2, Kind=* helm.cattle.io/v1, Kind=* k3s.cattle.io/v1, Kind=* metrics.k8s.io/v1beta1, Kind=* /*, Kind=* apiregistration.k8s.io/*, Kind=* apps/*, Kind=* events.k8s.io/*, Kind=* authentication.k8s.io/*, Kind=* authorization.k8s.io/*, Kind=* autoscaling/*, Kind=* batch/*, Kind=* certificates.k8s.io/*, Kind=* networking.k8s.io/*, Kind=* extensions/*, Kind=* policy/*, Kind=* rbac.authorization.k8s.io/*, Kind=* storage.k8s.io/*, Kind=* admissionregistration.k8s.io/*, Kind=* apiextensions.k8s.io/*, Kind=* scheduling.k8s.io/*, Kind=* coordination.k8s.io/*, Kind=* node.k8s.io/*, Kind=* discovery.k8s.io/*, Kind=* flowcontrol.apiserver.k8s.io/*, Kind=* acme.cert-manager.io/*, Kind=* cert-manager.io/*, Kind=* helm.cattle.io/*, Kind=* k3s.cattle.io/*, Kind=* metrics.k8s.io/*, Kind=*]

```

and when [`kindMatching`](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/api/meta/priority.go#L105) it checks if `Kind=Pod /v1` matches `Kind=* /v1` , and because it matches, it will just return after it matches and it won't go through `Kind=* metrics.k8s.io/*`
