### ISSUE TITLE
JSONSchemaProps should also support YAML encoding/decoding

### ISSUE THREAD

**Issue by campoy** [kubernetes/kubernetes#102380]
#### What would you like to be added:

This issue is about the `JSONSchemaProps` type defined in:
- [k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1](https://github.com/kubernetes/apiextensions-apiserver/blob/41c32f2661cc03c04d3c7e48ccf8107e0f8922b4/pkg/apis/apiextensions/v1/types_jsonschema.go)
- [k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1](https://github.com/kubernetes/apiextensions-apiserver/blob/41c32f2661cc03c04d3c7e48ccf8107e0f8922b4/pkg/apis/apiextensions/v1beta1/types_jsonschema.go)

Currently, these types do not support `yaml` encoding, as they come only with `json` field tags and implement only `MarshalJSON` and `UnmarshalJSON` for the types with custom encoding such as [`JSONSchemaPropsOrArray`](https://pkg.go.dev/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1#JSONSchemaPropsOrArray).

This has lead to subtle bugs where certain fields might not be decoded correctly, while others fields (because of most YAML decoders' behavior) are still matched correctly even if the casing differs.

I would like to solve this by adding the necessary field tags and methods necessary for custom YAML encoding.

I'm assuming this should be done in `k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1` only, or should we also retrofit the change into `[k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1`?

#### Why is this needed:

Right now, the only way to use JSONSchemaProps with YAML is to first parse the YAML, convert it into JSON, and finally parse the JSON. This makes it impossible to report accurate line numbers for any parsing error.

**If this issue is accepted, I would like to provide a PR I have already been working on.**

/sig api-machinery

**Comment by roycaihw** [comment]
[JSONSchemaProps](https://github.com/kubernetes/kubernetes/blob/59fd0a5c95a428660701dac7fe230dd6ddc4410a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go#L20) is not different from other built-in types-- we only declare json tags in the Go type.

In Kubernetes, we implemented [a wrapper of go-yaml](https://github.com/kubernetes-sigs/yaml#introduction) to handle yaml encoding/decoding using the json tags. The steps you mentioned about converting yaml to json is made there, and is hidden from the user. Users and API authors don't need to implement additional yaml support.

Please try using https://github.com/kubernetes-sigs/yaml. Please let us know if you still experience any inaccurate line numbers in parsing error. Please see https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apiextensions-apiserver/test/integration/yaml_test.go#L26 for examples of using this package. 

/close
