### ISSUE TITLE
Some typo at informationt staging/src/k8s.io/apimachinery/pkg/labels/selector.go

### ISSUE THREAD

**Issue by horizonzy** [kubernetes/kubernetes#102312]
### place one:
https://github.com/kubernetes/kubernetes/blob/b496238dd65d86c65183ac7ffa128c5de46705b4/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L580

meaningfull -> meaningful.

### place two:
https://github.com/kubernetes/kubernetes/blob/ebd61572c579476a6537b9002d90c978f24dda4e/staging/src/k8s.io/apimachinery/pkg/labels/selector.go#L493

informationt -> information.

**Comment by pacoxu** [comment]
/kind cleanup
/remove-kind feature

BTW, typo in comments  appears to fall under [trivial-edits](https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/contributors/guide/pull-requests.md#trivial-edits) which we do not encourage.

**Comment by horizonzy** [comment]
pr to [kubernetes/enhancements](https://github.com/kubernetes/enhancements) will be better?
