### ISSUE TITLE
Support setting depth to structured logging 

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#102353]
Logr and Klog extended the api to provide a method to provide a depth information https://github.com/kubernetes/klog/releases/tag/v2.5.0

To support new changes we should update:
* [x] [User guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md) should suggest using depth (@yangjunmyfm192085)
* [x] Restore depth to log calls that removed it when migrating to structured logging (@AbdulBasitAlvi)
  * [x] [httplog.go](https://github.com/kubernetes/kubernetes/blob/31f6cca256a21b9bbd561965dd321f518c88c944/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L100)
* [x] Add information about source code location in JSON format (add caller encoder to [EncoderConfig](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/json/json.go#L148)) (@MadhavJivrajani, https://github.com/kubernetes/kubernetes/pull/102437)

/wg structured-logging

**Comment by serathius** [comment]
/priority important-soon
This issue is based on feedback from Kubelet migration retrospection, it is required before organizing migration of next component.
CC @kubernetes/wg-structured-logging-members

**Comment by yangjunmyfm192085** [comment]
@MadhavJivrajani  @AbdulBasitAlvi, need any help? If need help,  can give me some tasks to do

**Comment by serathius** [comment]
There are 3 tasks proposed, please pick one so we make sure we don't duplicate work.

**Comment by AbdulBasitAlvi** [comment]
I am doing the following task @MadhavJivrajani @yangjunmyfm192085

Restore depth to log calls that removed it when migrating to structured logging
- httplog.go

**Comment by serathius** [comment]
Thanks for confirmation, added your GitHub handle to this task at the top.

**Comment by yangjunmyfm192085** [comment]
and @MadhavJivrajani?
which one can I do?

**Comment by MadhavJivrajani** [comment]
Hey @yangjunmyfm192085, I can do the third point :)

**Comment by MadhavJivrajani** [comment]
PR for point 3: #102437

**Comment by yangjunmyfm192085** [comment]
/assign
Ok, let me take a look the first part

**Comment by serathius** [comment]
All tasks been done, thanks for the help!
