### ISSUE TITLE
K8s node add new label, Prometheus pull data not inconsistent

### ISSUE THREAD

**Issue by zhangjie2012** [kubernetes/kubernetes#102385]
Yesterday, I created a issue about K8s Prometheus monitor: https://github.com/google/cadvisor/issues/2880.

After two days of tracking, I found it's not Prometheus's problem (config or monitor exp).

Same prometheus version, and same config files. When add new label to K8s node, In Kubernetes v1.13 `container_memory_usage_bytes` only has one data, But in Kubernetes v1.19 `container_memory_usage_bytes` has two data.

Is k8s apiserver change metrics behavior in diff versions ?

**Comment by zhangjie2012** [comment]
`/sig api-machinery`

**Comment by fedebongio** [comment]
Hopefully David can help with the answer.

/triage accepted

**Comment by dashpole** [comment]
This isn't related to the apiserver.  Something added a label to your metric, which makes the new stream distinct from the old one.  The kubelet [only adds name, image, pod name, namespace, container name](https://github.com/kubernetes/kubernetes/blob/043b3fc1e4b80939c24cf000d821ea64e8ad75d1/pkg/kubelet/server/server.go#L958) to its container metrics, so i'm guessing you are running cAdvisor as a daemonset.

Are you getting these metrics from the kubelet, or running cAdvisor yourself?

If the latter, i'd recommend setting `--store_container_labels=false`, to not add additional labels from your pods, as this can happen.  See https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#container-labels for the options.

**Comment by zhangjie2012** [comment]
@dashpole We getting metrics from kubelet, not cAdvisor.

this problem finally we removed Prometheus `relabel_configs` temporary repair ( this will remove container node label info).

![image](https://user-images.githubusercontent.com/2450412/120575287-5efe8400-c453-11eb-80f7-9fdc8ecc320e.png)

I still understand. We have four K8s cluster, all metrics fetch from kubelet, two old  k8s cluster is ` v1.13`, two new k8s cluster is `v1.19`.  

the old cluster container also has node label, but only metric record, same config new cluster have two metric record.

**Comment by zhangjie2012** [comment]
btw, the old cluster(v1.13)'s prometheus config also have `__meta_kubernetes_node_label_(.+)`, we not remove, but work well.

![image](https://user-images.githubusercontent.com/2450412/120575736-2e6b1a00-c454-11eb-81ee-2776d47d23c3.png)

**Comment by dashpole** [comment]
Did you add the `k2_app_hostpath` node label in both clusters?  It looks like that is what caused the overlap between the two streams

**Comment by zhangjie2012** [comment]
> Did you add the `k2_app_hostpath` node label in both clusters? It looks like that is what caused the overlap between the two streams

No, but every cluster both have different node label. When  add new label to node on old cluster, the metrics alse changed, but no overlap, only one record. 

The same situation, new cluster have two record.
