### ISSUE TITLE
Create HPA v2 Stable API

### ISSUE THREAD

**Issue by josephburnett** [kubernetes/kubernetes#102362]
#### What would you like to be added:

We need to create a new version v2 (no suffix) along with conversion routines, etc..

#### Why is this needed:

HPA v2beta2 is graduating to stable!  

- KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-autoscaling/2702-graduate-hpa-api-to-GA
- Tracking issue: https://github.com/kubernetes/enhancements/issues/2702
- Working doc: https://docs.google.com/document/d/1QGT9Waxc500ICGX_TGIoxfOWKmWbXYC6TWxfdUC2Njg/edit#
- Slack channel: #sig-autoscaling-api

#### What to do:

1. Read [Changing the API](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#changing-the-api), in particular [Making a New API Version](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#making-a-new-api-version).
2. Tell @josephburnett on #sig-autoscaling-api "_Hey, I want to do this._" (just so two people don't start the same work)
3. Create the new API and conversion routines.

#### Details:

The HPA controller [uses v2beta2](https://github.com/kubernetes/kubernetes/blob/d541872f9a036ed4f792232e43fde6dacf0e1084/pkg/controller/podautoscaler/horizontal.go#L576-L583) as the internal structure.  So your conversion routines will be from v2 -> v2beta2 and back.  We will migrate the controller and associated code to v2 stable as a separate change.

Create the new API by copying v2beta2.  We are graduating the API as-is without adding any new fields.  However there are a few fields and enum values we would like to rename because they are confusing.

* Rename `MaxPolicySelect` to `MaxChangePolicySelect` and the [value](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#ScalingPolicySelect) from `"Max"` to `"MaxChange"`.  The enum `MaxPolicySelect` will choose the smallest absolute value when scaling down (largest change) which has been confusing to customers.
* Rename `MinPolicySelect` to `MinChangePolicySelect` and the value from `"Min"` to `"MinChange"`.
* Rename `ResourceMetricSourceType` to `PodResourceMetricSourceType` and the [value](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#MetricSourceType) from `"Resource"` to `"PodResource"`.  The new `"ContainerResource"` type makes `"Resource"` ambiguous.
* Rename the associated `ResourceMetricSource` [struct](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#ResourceMetricSource).

Generate new code (see [Generating Code](https://pkg.go.dev/k8s.io/api/autoscaling/v2beta2#ScalingPolicySelect)).

Send a pull request (one squashed commit please) and notify #sig-autoscaling-api so we can take a look too.  It will probably need API review.

Feel free to reach out for help on #sig-autoscaling-api if you have any questions!

**Comment by danishprakash** [comment]
@wangyysde just a bump, are you working on this? couldn't find a message on slack for the same. Thanks

**Comment by josephburnett** [comment]
Hey @wangyysde thanks for volunteering!  Can you touch base with me in #sig-autoscaling-api in the Kubernetes Slack channel?  If you don't want to use slack, just email directly at josephburnett@google.com.

**Comment by AbdulBasitAlvi** [comment]
I would also like to start working on creating the new HPA v2 API. If someone is not working on it I can pick it up @josedonizetti @wangyysde

**Comment by josephburnett** [comment]
@AbdulBasitAlvi great!  Let's coordinate the work on #sig-autoscaling-api.  Ping me there or stop by the [sig-autoscaling working group meeting](https://github.com/kubernetes/community/tree/master/sig-autoscaling).

**Comment by wangyysde** [comment]
@AbdulBasitAlvi Are you start working on this? If not ,I will try to it .

**Comment by wangyysde** [comment]
@josephburnett Sorry. I have not Slack account.

**Comment by josephburnett** [comment]
Just to follow up, @wangyysde you have this issue.  Thanks for the PR.  @AbdulBasitAlvi I will follow up with you on Slack to find other, interesting work.  :)

**Comment by josephburnett** [comment]
I'm unable to get a v2 HPA object when I set this up with `kubetest --build --up`.

```
josephburnett@josephburnett:~/go/src/k8s.io/kubernetes$ kubectl get hpa.v2beta2.autoscaling
Warning: autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+
NAME         REFERENCE               TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
php-apache   Deployment/php-apache   <unknown>/50%   1         10        1          35s
```
```
josephburnett@josephburnett:~/go/src/k8s.io/kubernetes$ kubectl get hpa.v2.autoscaling
error: the server doesn't have a resource type "hpa"
```
