### ISSUE TITLE
Regex for validating Sysctl values in deployments might not be correct.

### ISSUE THREAD

**Issue by mrbetta** [kubernetes/kubernetes#102373]
#### What happened:
The Regex that validates sysctl values in objects doesn't allow names that contain forward slashes. Sysctl values on network subinterfaces contain these forward slashes.

#### What you expected to happen:
Running:
kubectl create -f ./deployment.yaml

Creates the deployment.

#### How to reproduce it (as minimally and precisely as possible):

Create a deployment that brings an additional network interface with subinterface into a pod (using something like Multus). 

Interface will appear as eth2.100

sysctl values for this interface will follow the convention "net.ipv4.conf.eno2/100..."

Attempt to set one of these values in the deployment such as:

spec:
  securityContext:
    sysctls:
    - name: net.ipv4.conf.eno2/100.rp_filter
      value: "0"

It will fail validation, even though it seems like that's the valid name. I wasn't able to escape it.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.5
- Cloud provider or hardware configuration: On-premise
- OS (e.g: `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): 5.5.2-1
- Install tools: kubeadm init
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by mrbetta** [comment]
Maybe this line:

https://github.com/kubernetes/kubernetes/blob/c224ca7674445ec98a2e8876daf53b9846cd3ae1/pkg/apis/policy/validation/validation.go#L368

Should be updated with: 
"([a-z0-9][/-_a-z0-9]*)?[a-z0-9*]"

**Comment by mrbetta** [comment]
Wrong place:

"([a-z0-9][-_/a-z0-9])?[a-z0-9]"

**Comment by mrbetta** [comment]
Also here?
https://github.com/kubernetes/kubernetes/blob/e8760b95bb0a0dfb5c184fd4e5ab95da3650a040/pkg/apis/core/validation/validation.go#L3777

**Comment by mengjiao-liu** [comment]
/reopen
Relaxing validation of API fields has to be done over two releases.We have only completed the first part now.
see https://github.com/kubernetes/kubernetes/pull/102393#discussion_r645018213 for more details.
