### ISSUE TITLE
Black/night-themed documentation for kubernetes

### ISSUE THREAD

**Issue by satyamsareen** [kubernetes/kubernetes#102352]
Hello Team,

I had a rather simple request.

Can we get black/night-themed documentation for k8s?
The way we have for Docker.

Any thoughts on this.

Cheers and Thanks

**Comment by pacoxu** [comment]
/sig docs
https://github.com/kubernetes/website/ is the repo for Kubernetes website and documentation.

/cc @sftim @tengqm

**Comment by sftim** [comment]
Duplicates https://github.com/kubernetes/website/issues/18798 and https://github.com/kubernetes/website/issues/25061
/triage duplicate

@satyamsareen let's track this in [k/website](https://github.com/kubernetes/website)
/close
