### ISSUE TITLE
POST pods/eviction calls can easily violate 1s API call latency SLO

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#102361]
#### What happened:

If many pods using the same pod disruption budget are deleted at ~the same time, significant part DELETE API calls will finish in more >1s, violating latency SLO.

#### What you expected to happen:
All API calls meet 1s latency SLO.

#### How to reproduce it (as minimally and precisely as possible):

* Create a pod disruption budget object
* Create multiple pods in the same namespace
* Evict all of them at the same time

#### Anything else we need to know?:

I think the Retry strategy used for resolving conflicts is using too large base delay:

https://github.com/kubernetes/kubernetes/blob/d541872f9a036ed4f792232e43fde6dacf0e1084/pkg/registry/core/pod/storage/eviction.go#L55-L60

This way, if we see any conflict those requests will see at least 500ms latency, in case of two conflicts,  we exceed SLO.

I think we should use smaller base (like 100ms) and larger jitter (like 50%) to spread conflicting requests for larger period of time.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by nikhita** [comment]
cc @soltysh 
since this is sig apps related
