### ISSUE TITLE
demo ignore it

### ISSUE THREAD

**Issue by sivanamu** [kubernetes/kubernetes#102368]
kubectl get pods --all-namespaces -o json  | jq -r '.items[] | select(.status.phase != "Running" or ([ .status.conditions[] | select(.type == "Ready" and .state == false) ] | length ) == 1 ) | .metadata.namespace + "/" + .metadata.name'

**Comment by neolit123** [comment]
we should use the issue tracker for bug reports / feature requests.

/close
