### ISSUE TITLE
Update CNI plugins

### ISSUE THREAD

**Issue by lentzi90** [kubernetes/kubernetes#102311]
The latest release of CNI plugins is [v0.9.1](https://github.com/containernetworking/plugins/releases/tag/v0.9.1), but we still have [v0.8.7 in the dependencies](https://github.com/kubernetes/kubernetes/blob/master/build/dependencies.yaml#L37).

I'll attempt to create a PR for this based on the [last update](https://github.com/kubernetes/kubernetes/pull/94367).

**Comment by thockin** [comment]
@dcbw - assigning to you :)
