### ISSUE TITLE
Proxy healthz start failure after node CRI maintenance

### ISSUE THREAD

**Issue by martinstraesser** [kubernetes/kubernetes#102392]
#### What happened:

On some nodes in my cluster I had to restart the CRI (in my case `containerd`) for maintenance reasons via:

```
systemctl stop containerd
# maintenance 
systemctl daemon-reload
systemctl start containerd
```

As expected the following events where given by `kubectl describe node $NODE_NAME` : 
````
 Normal   NodeNotReady                     20m                   kubelet     Node c34 status is now: NodeNotReady
 Warning  ContainerGCFailed                18m (x2 over 19m)     kubelet     rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory"
````

After `containerd` is ready again the node gets ready again, however there seams to be a persisting issue with the proxy health check:

```
  Normal   NodeReady                        36m (x2 over 18h)    kubelet     Node c35 status is now: NodeReady
  Normal   Starting                         36m                  kube-proxy  Starting kube-proxy.
  Warning  FailedToStartProxierHealthcheck  60s (x421 over 36m)  kube-proxy  failed to start proxier healthz on 0.0.0.0:10256: listen tcp 0.0.0.0:10256: bind: address already in use
```

#### What you expected to happen:

Processes should be canceled or restarted properly to avoid port collision.

#### How to reproduce it (as minimally and precisely as possible):

As stated above, stop CRI on any node and restart it.

#### Anything else we need to know?:

I was able to solve the issue myself by brute-force killing the process which blocks the port. For this, I execute `lsof -i:10256` on the node and kill the outcoming PID. 

Possibly related: #49263

#### Environment:
- Kubernetes version (`kubectl version`): v1.21.1
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.5 LTS
- Container Runtime: containerd://1.3.3

**Comment by wzshiming** [comment]
it works well will recover in a minute

```
  Warning  ContainerGCFailed  2m15s  kubelet  rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory"
  Normal   NodeNotReady       119s   kubelet  Node zsm-test-2 status is now: NodeNotReady
  Normal   NodeReady          98s    kubelet  Node zsm-test-2 status is now: NodeReady
```

https://github.com/kubernetes/kubernetes/blob/e6136c0303028d68cac67290d94a60cec167ccdf/pkg/kubelet/kubelet.go#L1282-L1296

**Comment by martinstraesser** [comment]
To reproduce:
On any non-master node execute:
```
systemctl stop containerd
sleep 60
systemctl daemon-reload
systemctl start containerd
```

Thats it. Then observe events e.g. with `kubectl describe node $YOUR_NODE`

**Comment by wzshiming** [comment]
> To reproduce:
> On any non-master node execute:
> 
> ```
> systemctl stop containerd
> sleep 60
> systemctl daemon-reload
> systemctl start containerd
> ```
> 
> Thats it. Then observe events e.g. with `kubectl describe node $YOUR_NODE`

Can't follow the steps you said to reproduce

**Comment by wzshiming** [comment]
``` bash
systemctl stop containerd
pkill kube-proxy; nc -l 0.0.0.0 10256& # your maintenance?
systemctl start containerd
```

I'm not sure what you did, I guess it might be something like this

**Comment by wzshiming** [comment]
``` bash
systemctl stop containerd
pkill kube-proxy; nc -l 0.0.0.0 10256& # your maintenance?
systemctl start containerd
```

I'm not sure what you did, I guess it might be something like this

**Comment by martinstraesser** [comment]
I isolated the root-cause maintenance step to a movement of the local `containerd` image repository. I did not explicitly touch the kube-proxy or any port. Can you reproduce issue with this: 

```
OLD_LIB_DIRECTORY=/var/lib/containerd
NEW_LIB_DIRECTORY=/home/username/containerd
systemctl stop containerd
mv $OLD_LIB_DIRECTORY $NEW_LIB_DIRECTORY
# replace root entry in /etc/containerd/config.toml accordingly
systemctl daemon-reload
systemctl start containerd
```

**Comment by martinstraesser** [comment]
I isolated the root-cause maintenance step to a movement of the local containerd image repository. I did not explicitly touch the kube-proxy or any port. Can you reproduce issue with this: 

```
OLD_LIB_DIRECTORY=/var/lib/containerd
NEW_LIB_DIRECTORY=/home/username/containerd
systemctl stop containerd
mv $OLD_LIB_DIRECTORY $NEW_LIB_DIRECTORY
# replace root entry in /etc/containerd/config.toml accordingly
systemctl daemon-reload
systemctl start containerd
```

**Comment by bridgetkromhout** [comment]
This seems like a sig-node issue - removing sig-network for now.

/remove-sig network

**Comment by ehashman** [comment]
/triage not-reproducible

If someone can repro this, then we can look at fixing it but thus far we have been unable. Will close if we cannot reproduce.
