### ISSUE TITLE
CRD definition is changing the property name 'y' in openAPIV3Schema spec to True

### ISSUE THREAD

**Issue by chintha-govardhan** [kubernetes/kubernetes#102308]
The below CRD is created using kubectl. The CRD contains the openAPIV3Schema spec which has property name as 'y'.

<pre>
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tests.calci.io
spec:
  group: calci.io
  versions:
    - name: v1 # it's possible to provide multiple versions of a CRD
      served: true # it's possible to disable a CRD
      storage: true # there can be multiple versions but only one can be used to store the objects
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                operation:
                  type: string
                  enum: ["ADD", "SUB", "DIV", "MUL"]
                x:
                  type: number
                <b>y:
                  type: number</b>
  scope: Namespaced # resources can be namespaced or available for the whole cluster
  names:
    plural: tests
    singular: test
    kind: Test # this name is being used in manifests
    shortNames: # these short names can be used in the CLI, e.g. kubectl get er
    - tt
</pre>

After the crd is created, the y property is showing as True in CRD description

<pre>
Name:         tests.calci.io
Namespace:
Labels:       <none>
Annotations:  API Version:  apiextensions.k8s.io/v1
Kind:         CustomResourceDefinition
Metadata:
  Creation Timestamp:  2021-05-26T05:54:57Z
  Generation:          1
  Managed Fields:
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:conditions:
    Manager:      kube-apiserver
    Operation:    Update
    Time:         2021-05-26T05:54:57Z
    API Version:  apiextensions.k8s.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        f:conversion:
          .:
          f:strategy:
        f:group:
        f:names:
          f:kind:
          f:listKind:
          f:plural:
          f:shortNames:
          f:singular:
        f:scope:
        f:versions:
      f:status:
        f:storedVersions:
    Manager:         kubectl
    Operation:       Update
    Time:            2021-05-26T05:54:57Z
  Resource Version:  1373282
  UID:               725f0994-7fa1-49b4-a01e-07498b623d2d
Spec:
  Conversion:
    Strategy:  None
  Group:       calci.io
  Names:
    Kind:       Test
    List Kind:  TestList
    Plural:     tests
    Short Names:
      tt
    Singular:  test
  Scope:       Namespaced
  Versions:
    Name:  v1
    Schema:
      openAPIV3Schema:
        Properties:
          Spec:
            Properties:
              Operation:
                Enum:
                  ADD
                  SUB
                  DIV
                  MUL
                Type:  string
              <b>True:
                Type:  number</b>
              X:
                Type:  number
            Type:      object
        Type:          object
    Served:            true
    Storage:           true
Status:
  Accepted Names:
    Kind:       Test
    List Kind:  TestList
    Plural:     tests
    Short Names:
      tt
    Singular:  test
  Conditions:
    Last Transition Time:  2021-05-26T05:54:57Z
    Message:               no conflicts found
    Reason:                NoConflicts
    Status:                True
    Type:                  NamesAccepted
    Last Transition Time:  2021-05-26T05:54:57Z
    Message:               the initial names have been accepted
    Reason:                InitialNamesAccepted
    Status:                True
    Type:                  Established
  Stored Versions:
    v1
Events:  <none>
</pre>

**Comment by CaoDonghui123** [comment]
/assign
I will try to reproduce it first

**Comment by CaoDonghui123** [comment]
https://github.com/go-yaml/yaml/issues/740#issuecomment-843446726
need update version to gopkg.in/yaml.v3

**Comment by wzshiming** [comment]
Maybe you can wrap y in quotes, like 

``` yaml
'y':
  type: number
```

**Comment by CaoDonghui123** [comment]
> Maybe you can wrap y in quotes

It also decodes to true

**Comment by fedebongio** [comment]
/cc @roycaihw 
thank you Haowei! 
/triage accepted

**Comment by roycaihw** [comment]
it's unclear how to fix it, but there has been a duplicate issue: https://github.com/kubernetes/kubernetes/issues/34146

**Comment by liggitt** [comment]
a quoted `"y"` should never convert to `true`. 

> > Maybe you can wrap y in quotes
> 
> It also decodes to true

wrapping it in quotes works correctly for me:

```yaml
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                operation:
                  enum:
                  - ADD
                  - SUB
                  - DIV
                  - MUL
                  type: string
                x:
                  type: number
                "y":
                  type: number
```

**Comment by liggitt** [comment]
also reported in https://github.com/go-yaml/yaml/issues/283

**Comment by liggitt** [comment]
for yaml values like "y", "n", "no", it seems like quoting is required for them to be unambiguous
