### ISSUE TITLE
Watch of Service resource with WebSocket does not timeout appropriately

### ISSUE THREAD

**Issue by shawkins** [kubernetes/kubernetes#102464]
#### What happened:

Using the Fabric8 client, which defaults to using WebSockets for Watches, I established a Watch on Service resources.  After the timeout (implicit or explicit) rather than the WebSocket seeing a close control frame or even an EOF it continued to be open and fulfill ping/pong requests - but no Service events are sent.

#### What you expected to happen:

The WebSocket would close.

#### How to reproduce it (as minimally and precisely as possible):

Create a WebSocket based Watch with the ListOptions timeoutSeconds set on the Service resource along with a steady production of Service events, such as create/delete of a dummy Service.

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"ffd6836", GitTreeState:"clean", BuildDate:"2020-10-27T05:15:27Z", GoVersion:"go1.15.0", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

The behavior has been seen in both local minikube and OpenShift distributions based upon Kubernetes 1.20.

- OS (e.g: `cat /etc/os-release`):

Fedora 33

**Comment by liggitt** [comment]
Is this the same issue as https://github.com/kubernetes/kubernetes/issues/85548 ?

**Comment by shawkins** [comment]
> Is this the same issue as #85548 ?

It could be related, but in that case the client is calling close.  In this case we expect the server to initiate the close.

**Comment by fedebongio** [comment]
A couple of things were discussed when we triaged this issue:
a) we need to involve the Fabric8 team (~java client?)
b) We don't always default to Websocket, in fact we discussed discontinuing it
c) But the code is still there, so it's allowed for now and we should support it.

Not sure what to do next @lavalamp @deads2k

**Comment by lavalamp** [comment]
a) no, it sounds like an apiserver problem, it should be reproducible with a go client in a test.
b) If anything, we should standardize on websockets. Brower based clients depend on them. And when/if we get rid of SPDY, websockets are the replacement.

This may be relevant to @caesarxuchao's interests.

**Comment by shawkins** [comment]
> a) no, it sounds like an apiserver problem, it should be reproducible with a go client in a test.

I didn't see an option to use websockets with the go client https://github.com/fabric8io/kubernetes-client/issues/3177#issuecomment-850464286 the impl is at https://github.com/kubernetes/client-go/blob/56494c9682c414b74bb83639bd6890feed82d307/rest/request.go#L671

Is there another code path or go client that will use a websocket for Watches?

**Comment by lavalamp** [comment]
Technically I didn't say *our* go client, just *a* go client. 😅 I just had in mind using the raw websockets library.

...we must be testing the websocket watches *somehow*?

**Comment by shawkins** [comment]
I adapted https://gist.github.com/jezell/ca4b08b17df3fb7b9dc8783d9a68cc2e to 
```
package main

import (
	"bytes"
	"io"
	"log"
	"net/http"
	"path/filepath"

	"golang.org/x/net/websocket"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
)

func main() {
	var home = homedir.HomeDir()
	var kubeconfig = filepath.Join(home, ".kube", "config")
	config, err := clientcmd.BuildConfigFromFlags("", kubeconfig)
	if err != nil {
		panic(err.Error())
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

	var url = clientset.RESTClient().Get().URL()

	url.Hostname()
	url.Port()

	apiURL := "wss://" + url.Hostname() + ":" + url.Port() + "/api/v1/services?watch=true&timeoutSeconds=10"
	wsc, err := websocket.NewConfig(apiURL, apiURL)
	if err != nil {
		log.Fatal(err)
	}
	wsc.TlsConfig, err = rest.TLSConfigFor(config)
	if err != nil {
		log.Fatal(err)
	}
	wsc.Header, err = headersForConfig(config)
	if err != nil {
		log.Fatal(err)
	}

	wsConn, err := websocket.DialConfig(wsc)
	if err != nil {
		log.Fatal(err)
	}
	defer wsConn.Close()

	buf := &bytes.Buffer{}
	for {
		var msg []byte
		if err := websocket.Message.Receive(wsConn, &msg); err != nil {
			if err == io.EOF {
				break
			}
			log.Fatalf("Failed to read completely from websocket %v", err)
		}
		if len(msg) == 0 {
			continue
		}
		log.Printf("Read %v %v", len(msg), string(msg))
		buf.Write(msg)
	}

	if buf.String() != "container is alive\n" {
		log.Fatalf("Unexpected websocket logs:\n%s", buf.String())
	}
}

type extractRT struct {
	http.Header
}

func (rt *extractRT) RoundTrip(req *http.Request) (*http.Response, error) {
	rt.Header = req.Header
	return nil, nil
}

func headersForConfig(c *rest.Config) (http.Header, error) {
	extract := &extractRT{}
	rt, err := rest.HTTPWrappersForConfig(c, extract)
	if err != nil {
		return nil, err
	}
	if _, err := rt.RoundTrip(&http.Request{}); err != nil {
		return nil, err
	}
	return extract.Header, nil
}
```
It will simply keep running - with no events after the timeout.  If you switch to configmap, it will terminate.

**Comment by liggitt** [comment]
that's a terrific reproducer, thanks!

**Comment by lavalamp** [comment]
Yeah, we should absolutely be able to stick that in a unit / integration test somewhere, thanks!

**Comment by liggitt** [comment]
opened in https://github.com/kubernetes/kubernetes/pull/102539

configmap watch works correctly, service watch hits timeout without the server closing the connection

**Comment by liggitt** [comment]
I suspect the issue is in newDecoratedWatcher. Services implement a decorator and configmaps don't.

**Comment by liggitt** [comment]
yup, the request context wasn't propagated to the decorated watcher

**Comment by liggitt** [comment]
Service decorator was added in 1.20 in 6675eba3eff1c8e565c4060a9c1396f75da7cc3e

Fix with unit and integration test in https://github.com/kubernetes/kubernetes/pull/102539

Will pick to 1.21 and 1.20 once merged
