### ISSUE TITLE
Docker credentials passed via CRI (on image pull) match URL paths by prefix

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#102472]
#### What happened:

https://github.com/kubernetes/kubernetes/pull/8438 introduced a glob mechanism for [Docker authentication configuration files](https://kubernetes.io/docs/concepts/containers/images/#configuring-nodes-to-authenticate-to-a-private-registry). URL paths are being matched via `strings.HasPrefix`:

https://github.com/kubernetes/kubernetes/blob/4556873abf8aa88ce2ab40476267b0e9d4253366/pkg/credentialprovider/keyring.go#L215-L218

This means that credentials provided for a container image `quay.io/saschagrunert/foo` in `config.json` will also be passed to the container runtime if we choose an image like `quay.io/saschagrunert/foo-my-suffix`.

I don't think that this is intentional because I cannot think of a valid use-case around it.

#### What you expected to happen:

That the credentials only for full path matches get passed down to the container runtime (via the CRI).

#### How to reproduce it (as minimally and precisely as possible):

Run kubernetes as described above with a set of pre-configured auth secrets and pull an image with a path suffix.

#### Anything else we need to know?:

None

#### Environment:
- Kubernetes version (use `kubectl version`): v1.22.0-alpha.2.260+14e4ed07cf81a8
- Cloud provider or hardware configuration: None
- OS (e.g: `cat /etc/os-release`): NixOS
- Kernel (e.g. `uname -a`): 5.11.21
- Install tools: None
- Network plugin and version (if this is a network-related bug): None
- Others: None

cc @brendanburns @tcnghia

**Comment by matthyx** [comment]
This will require unit test coverage at least...

/triage accepted
/help

**Comment by endocrimes** [comment]
it seems like this was at least partially intentional, as the question was raised in the initial PR - I wonder if @tcnghia could elaborate on the initial purpose there?

**Comment by saschagrunert** [comment]
Yes, I think it was intentional too and added it to the docs in this PR: https://github.com/kubernetes/website/pull/28226

**Comment by mtrmac** [comment]
I don’t see that the original URL says anything about the prefix-of-name-component matching (if anything, “Note that we don't support wildcards in ports and paths yet.” suggests that wildcard support would be same as wildcards in host name, i.e. `filepath.Match` is not a prefix match).

Similarly https://github.com/kubernetes/website/pull/28226 documents the glob behavior but (other than saying the “prefix” word) AFAICS says nothing _explicit_ about the prefix-of-name-component matching.

**Comment by tcnghia** [comment]
Hello! Apologies that this was buried in my email.

The HasPrefix check predated my PR. I only pulled the logic into its own function when  I added glob.

https://github.com/kubernetes/kubernetes/pull/8438/files#diff-13fbddb28f17a15bee09157d3f10ccaeffe900f97c7463957fc1d5f394968100L130

**Comment by mtrmac** [comment]
This looks to have been there since the very start of the code: https://github.com/tcnghia/kubernetes/commit/2f87857b0fc0e00e72bd8ece5bb96d9c95296d21

Sigh.

I guess now that this is a documented behavior, this bug can remain closed. But I’m going to strongly object to spreading this semantics (e.g. to the CRI, where we have tentatively discussed passing more credentials to allow authenticated mirrors).
