### ISSUE TITLE
Secret ended with: too old resource version

### ISSUE THREAD

**Issue by ercindemir** [kubernetes/kubernetes#102440]
I've read a lot about this issue on google and noticed people saying these logs are expected nothing to worry about, but I often see the same logs in the pods and I am curious about how I can get rid of them. Why are we seeing these logs exactly? Please shed some light on that.

Secret ended with: too old resource version

```
W0528 08:24:35.191059       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136329240 (136330521)
W0528 08:39:29.197834       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136335511 (136336795)
W0528 08:55:35.204496       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136341573 (136343365)
W0528 09:09:04.216732       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136348121 (136349202)
W0528 09:24:00.224786       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136353600 (136355423)
W0528 09:41:36.231222       1 reflector.go:289] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: watch of *v1.Secret ended with: too old resource version: 136359660 (136362039)
```

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: AWS

/sig api-machinery

**Comment by ercindemir** [comment]
@lavalamp

**Comment by 249043822** [comment]
#85723

**Comment by lavalamp** [comment]
It just means the current watch connection ended (watches disconnect after 5-10 minutes), and the the client will re-watch, relisting first if necessary. Another issue is open somewhere about removing the log message, which has a poor signal-to-noise ratio.

**Comment by ercindemir** [comment]
@lavalamp Thank you for your time to comment. I consistently receive these logs in my pods. Is there any way to resolve this?

**Comment by lavalamp** [comment]
> I consistently receive these logs in my pods. Is there any way to resolve this?

The system is not misbehaving, so I'm not sure what about it you want resolved. You are welcome to send a PR changing the log line if that would help.
