### ISSUE TITLE
Umbrella issue: Reduce release image sizes 

### ISSUE THREAD

**Issue by rikatz** [kubernetes/kubernetes#102493]
Per last k8s-infra WG, some images are more used than others, most notably kube-proxy. This can be easily explained by the fact that while control plane is restricted to a small set of hosts, all regular clusters needs kube-proxy (unless your CNI does implement it, which is not the case).

kube-proxy image is 118Mb, and diving into it we can see:

```
  "layer": [
    {
      "sizeBytes": 52345249,
      "command": "#(nop) ADD file:958919051423e2871000d6b40bcfa96d0443bea2a627b1f342c833ae7c9b2771 in / "
    },
    {
      "sizeBytes": 21766531,
      "command": "|1 IPTABLES_VERSION=1.8.5 /bin/sh -c echo deb http://deb.debian.org/debian buster-backports main \u003e\u003e /etc/apt/sources.list     \u0026\u0026 apt-get update     \u0026\u0026 apt-get -t buster-backports -y --no-install-recommends install         iptables=${IPTABLES_VERSION}*         ebtables"
    },
    {
      "sizeBytes": 4796291,
      "command": "|1 IPTABLES_VERSION=1.8.5 /bin/sh -c clean-install     conntrack     ipset     kmod     netbase"
    },
    {
      "sizeBytes": 1684,
      "command": "#(nop) COPY file:753d2b895bae0725b470e608b4745c5a21d9ebb4ce1e9a13ad3d26721e1e6dd8 in /usr/sbin/iptables-wrapper "
    },
    {
      "command": "|1 IPTABLES_VERSION=1.8.5 /bin/sh -c update-alternatives \t--install /usr/sbin/iptables iptables /usr/sbin/iptables-wrapper 100 \t--slave /usr/sbin/iptables-restore iptables-restore /usr/sbin/iptables-wrapper \t--slave /usr/sbin/iptables-save iptables-save /usr/sbin/iptables-wrapper"
    },
    {
      "sizeBytes": 1148,
      "command": "|1 IPTABLES_VERSION=1.8.5 /bin/sh -c update-alternatives \t--install /usr/sbin/ip6tables ip6tables /usr/sbin/iptables-wrapper 100 \t--slave /usr/sbin/ip6tables-restore ip6tables-restore /usr/sbin/iptables-wrapper \t--slave /usr/sbin/ip6tables-save ip6tables-save /usr/sbin/iptables-wrapper"
    },
    {
      "sizeBytes": 39485440,
      "command": "#(nop) COPY file:a468018b126749cbaeeee16d14fc68d8e9f589dc9a5ec090d79fffe2b89b5ff2 in /usr/local/bin/kube-proxy "
    }]
```

In an effort to optimize it, we can:
* join multiple RUN commands into a single layer (and clean everything into that same RUN command)
* Remove probably unnecessary files from base image (/usr/bin/qemu-x86_64-static)

As this is mostly a tracking issue, PRs related to image cleanup will make reference into this.

/sig release

**Comment by rikatz** [comment]
/wg k8s-infra
@dims @spiffxp @hh fyi

I'm gonna open a PR to consolidate kube-proxy image, and later we need to discuss with sig-release if `/usr/bin/qemu-x86_64-static` is really necessary in base image

**Comment by justaugustus** [comment]
xref: https://github.com/kubernetes/release/pull/1622
FYI @kubernetes/release-engineering 
/area release-eng

**Comment by dims** [comment]
@rikatz when i run the container using `docker run -it k8s.gcr.io/kube-proxy:v1.21.0 sh` and peek inside i don't see the `/usr/bin/qemu-x86_64-static` there. is it there in one of the layers and then gets removed?

**Comment by rikatz** [comment]
@dims it seems so. But on the upper image:

docker run -it --rm k8s.gcr.io/build-image/debian-base-amd64:buster-v1.7.0 ls -l /usr/bin |grep qemu
-rwxr-xr-x 1 root root   8423624 Jan  3 16:47  qemu-x86_64-static

So this is already part of the layers :(

**Comment by dims** [comment]
@rikatz looks like this was introduced in between 1.4.0 and 1.5.0

```
$ docker run -it --rm k8s.gcr.io/build-image/debian-base-amd64:buster-v1.4.0 ls -l /usr/bin |grep qemu
Unable to find image 'k8s.gcr.io/build-image/debian-base-amd64:buster-v1.4.0' locally
buster-v1.4.0: Pulling from build-image/debian-base-amd64
1813d21adc01: Already exists
Digest: sha256:afff10fcd513483e492807f8d934bdf0be4a237997f55e0f1f8e34c04a6cb213
Status: Downloaded newer image for k8s.gcr.io/build-image/debian-base-amd64:buster-v1.4.0
1
[2785342:2785341 - 0:1985] 02:08:22 [dims@bigbox:/dev/pts/0 +1] ~
$ docker run -it --rm k8s.gcr.io/build-image/debian-base-amd64:buster-v1.5.0 ls -l /usr/bin |grep qemu
Unable to find image 'k8s.gcr.io/build-image/debian-base-amd64:buster-v1.5.0' locally
buster-v1.5.0: Pulling from build-image/debian-base-amd64
96459fd64d20: Pulling fs layer
96459fd64d20: Verifying Checksum
96459fd64d20: Download complete
96459fd64d20: Pull complete
Digest: sha256:216c4c2de4ba39a5e70c4b2ae6bd91d475b3e6673c5e02a061f1152c9a7cdccd
Status: Downloaded newer image for k8s.gcr.io/build-image/debian-base-amd64:buster-v1.5.0
-rwxr-xr-x 1 root root   8423624 Jan  3 16:47  qemu-x86_64-static
```

**Comment by BenTheElder** [comment]
If we ported the iptables wrapper script to a binary (go?) we could do distroless + iptables binaries (build from source or copy from a distro image) + the selection wrapper for the kube-proxy image. A full debian image is overkill anyhow.

**Comment by rikatz** [comment]
hum, sounds like something we can do.

@danwinship as the official creator of iptables-wrapper, wdyt?

**Comment by justaugustus** [comment]
+1 to Ben's idea!
@rikatz -- Pending Dan's confirmation, are you planning on working on this or do you want RelEng to?

**Comment by rikatz** [comment]
I can work on this without any problem :) Hope I just don't break anything ;)

About the kube-proxy image anyway, I think we can have a good gain consolidating the RUN commands in kproxy Dockerfile, at least reducing the final image in ~20mb. If this is OK I'll work in two fronts

**Comment by puerco** [comment]
Awesome, if I can help let @rikatz  me know. I take it the script that ben is talking about is this one right?
https://github.com/kubernetes/release/blob/master/images/build/debian-iptables/buster/iptables-wrapper

**Comment by rikatz** [comment]
@puerco yup, exactly, based on https://github.com/kubernetes-sigs/iptables-wrappers :)

If you have bandwidth then go for it! Otherwise no worries!

**Comment by puerco** [comment]
Start and I'll try to follow you Ricardo. We are pushing for some enhancements for the next couple of releases and won't be able to give it my full attention for two weeks or so.

**Comment by danwinship** [comment]
There was some discussion in #82966 about trying to optimize the image but I think everyone was like "eh, maybe later". Guess it's later?

> If we ported the iptables wrapper script to a binary (go?) we could do distroless + iptables binaries (build from source or copy from a distro image) + the selection wrapper for the kube-proxy image. A full debian image is overkill anyhow.

kube-proxy has several external binary dependencies including at least conntrack, ipset, iptables, ipvs, and modprobe. I'm not sure distroless is the way to go. Maybe just switch to a Linux distro with smaller base images? (Alpine?)

> @danwinship as the official creator of iptables-wrapper, wdyt?

Porting the wrapper to golang seems like overkill to me :man_shrugging: 
If you do it though, please submit a PR to the repo.

**Comment by BenTheElder** [comment]
> kube-proxy has several external binary dependencies including at least conntrack, ipset, iptables, ipvs, and modprobe. I'm not sure distroless is the way to go. Maybe just switch to a Linux distro with smaller base images? (Alpine?)

Ah yes, this. Is ipvs kube-proxy still developed? Is this a complete listing

This is still not many binaries, it's just 4 packages (if we ignore the wrapper script), which is not really worth having a bunch of ancillary distro stuff in the image IMHO. We could copy them over from a distro onto e.g. distroless perhaps.

> Maybe just switch to a Linux distro with smaller base images? (Alpine?)

I think alpine / busybox is probably not acceptable as an end-user image due to licensing? (not really my area but ...)

We also don't want / need any of the additional packaged stuff (e.g. manpages) even for these deps, we just need the binaries.

> Porting the wrapper to golang seems like overkill to me 🤷‍♂️

The intent there would only be to drop all the userspace binary dependencies for the script. (less potential vulnerabilities, easier to have a distroless-like image). Otherwise I'd agree, we should not port it just to port it.

FWIW istio has done something like this. cc @howardjohn

**Comment by howardjohn** [comment]
For Istio we did build a custom distroless image with just iptables added: https://github.com/istio/distroless/commit/df31f67841c72486cc0a3c6e72ac6a6d5b6e81e9. The problem is a bit simpler for us those since we are running iptables in the pod network namespace not the host so we don't need the wrapper stuff (I think, anyhow, it at least seems to work..).

**Comment by rikatz** [comment]
@dims about the qemu-x86_64-static I've removed it from base image and re-created everything and it has just build fine. I've tracked the addition to https://github.com/kubernetes/release/pull/1909

@saschagrunert can you help us clarifying the need of this file inside the image? :D

Here are some results so far (I'm showing just the amd64 now, but the gain is similar for other images as well)

Before images optimizations 
```
rpkatz/debian-base-amd64                             buster-v1.7.1                      16db22087cca   29 minutes ago      60.8MB
rpkatz/debian-iptables-amd64                             buster-v1.6.2                      e29c36372f6a   9 minutes ago       87.7MB
```


After images optimizations
```
rpkatz/debian-base-amd64                                 buster-v1.7.2                      3ec71045d1b4   9 minutes ago       52.4MB
rpkatz/debian-iptables-amd64                             buster-v1.6.3                      85814e9ca503   4 minutes ago       60.5MB
```

With the simple changes we might have a reduction of 30% of the image size, which is pretty acceptable to me.

About moving to distroless I agree this might be a good win, but we need to take care as we are not going to run only iptables* commands but conntrack, ipset and other things that may rely not only in glibc but also other libraries, so managing those dependencies might turn into something painful. Maybe this can be a next step? Same applies for iptables-wrapper (as Dan stated), maybe we will end up with a bigger image (go binary, etc) instead of a simple shell script for now (and well, the problem we are trying to solve here specifically is the image size) :)

**Comment by dims** [comment]
thanks a ton @rikatz I'll take the 30% savings anyday!

![image](https://user-images.githubusercontent.com/23304/121397968-dc7a3680-c922-11eb-96f8-abd3db1182ac.png)

**Comment by BenTheElder** [comment]
> @saschagrunert can you help us clarifying the need of this file inside the image? :D

Tracked it back to the original addition here https://github.com/kubernetes/release/pull/2113#discussion_r648546476

I don't think we need this, and haven't for ... years.

**Comment by thockin** [comment]
A pattern I have picked up for multiple RUN commands is to use multi-stage builds:

```
FROM whatever as prep

RUN x
RUN y
RUN z

COPY foo bar

RUN rm -rf /useless/stuff


#############################################################################
FROM scratch
COPY --from=prep / /
```

The result just has 1 layer (well, 2, but one is "scratch").

**Comment by rikatz** [comment]
The Debian-base image is created actually in a similar way, but instead of doing the multistage, it exports the layers and re-import as a single image -> https://github.com/kubernetes/release/blob/master/images/build/debian-base/Makefile#L95-L102

For debian-iptables image, I did something "similar" just to test but the gain is not that huge. OTOH, what I did (and will wait for the new Debian-base image to gets merged) is to join the [RUN](https://github.com/kubernetes/release/blob/master/images/build/debian-iptables/buster/Dockerfile#L21-L33) statements as the last one is the clean_install script that cleans the cache, and this way the final layer is just Debian Base + the necessary things for Kube-proxy :)

**Comment by thockin** [comment]
My point is that the multi-stage build means you don't have to join all the
RUN commands together.  You can write them more "naturally"

**Comment by rikatz** [comment]
OK, got it :) 

So maybe when I open the PR for debian-iptables, instead of joining the RUN commands we can use the multi-stage if this is better viewable :)

**Comment by thockin** [comment]
It's a minor point - it should produce the same result for RUN
commands.  It's strictly better in the case of COPY (you can't merge
COPY commands or COPY+RUN commands)

**Comment by danwinship** [comment]
Hm... I thought I had responded to this...

> Ah yes, this. Is ipvs kube-proxy still developed?

yes

> Is this a complete listing

"conntrack, ipset, iptables, ipvs, and modprobe" is the complete list of things that kube-proxy _directly_ invokes on Linux. There _might_ be other binaries that get indirectly invoked via some imported module, although I don't think so.

And actually, strike ipvs from that list; `utilipvs.New()` takes a `utilexec.Interface`, but it doesn't actually use it...
