### ISSUE TITLE
Propose plural version for klog.KObj

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#102434]
Original discussion https://github.com/kubernetes/kubernetes/pull/99799#discussion_r588252534

Problem is that in golang slice of struct cannot be passed into slice of interfaces they implement. This is due to difference in memory representation of two slices (cant wait for Generics) . For example
[]corev1.Pods{}  cannot be passed to func KObjs(objs []klog.ObjectRef).

/wg structured-logging
@kubernetes/wg-structured-logging-members 
/kind cleanup
/cc @Priyankasaggu11929

**Comment by pacoxu** [comment]
Good point. I will work on #101820 which may should `node score` list, and it would be a case of this.

**Comment by serathius** [comment]
Hey @Priyankasaggu11929, I haven't seen any updates. Are you still planning to work on this issue? 
@yuzhiquan has send a PR with implementation https://github.com/kubernetes/klog/pull/249. 

There is still some work aside of just implementing `klog.KObjs`:
* Update user guide
* Fix temporary workarounds introduced in original PRs
  *  https://github.com/kubernetes/kubernetes/pull/99799#discussion_r588252534
  * https://github.com/kubernetes/kubernetes/pull/99029#discussion_r586816580
  
@Priyankasaggu11929 when https://github.com/kubernetes/klog/pull/249 gets merged, would you be still interested in finishing the work?

**Comment by Priyankasaggu11929** [comment]
@serathius, firstly apologies on not updating on this (I just got terribly stuck in work stuff previous weeks).

Thank you for listing other points. I'll be implementing them this weekend itself, & will update here.

**Comment by serathius** [comment]
Please make sure to collaborate with @yuzhiquan and give feedback on the PR.

**Comment by yuzhiquan** [comment]
> @serathius, firstly apologies on not updating on this (I just got terribly stuck in work stuff previous weeks).
> 
> Thank you for listing other points. I'll be implementing them this weekend itself, & will update here.

Huge apologies for not noticed this issue, and with pleasure  work with @Priyankasaggu11929.
Thanks @serathius

**Comment by Priyankasaggu11929** [comment]
Thank you @serathius. I’ll connect on the PR.

**Comment by yuzhiquan** [comment]
> * Update user guide
> * Fix temporary workarounds introduced in original PRs
>   
>   * [Refactor pods format to return ObjRef slice #99799 (comment)](https://github.com/kubernetes/kubernetes/pull/99799#discussion_r588252534)
>   * [kubelet: migrate pkg/kubelet/eviction to structured logging #99029 (comment)](https://github.com/kubernetes/kubernetes/pull/99029#discussion_r586816580)

TODO list as @serathius suggest:

- [ ] Update user guide
- [ ] Tag Klog new version 2.10.0 
- [ ] Bump k/k klog version to 2.10.0


Fix temporary workarounds introduced in original PRs:
   * [ ] [Refactor pods format to return ObjRef slice #99799 (comment)](https://github.com/kubernetes/kubernetes/pull/99799#discussion_r588252534)
   * [ ] [kubelet: migrate pkg/kubelet/eviction to structured logging #99029 (comment)](https://github.com/kubernetes/kubernetes/pull/99029#discussion_r586816580)

**Comment by Priyankasaggu11929** [comment]
Thanks @yuzhiquan. I’ll do the changes tomorrow.

**Comment by Priyankasaggu11929** [comment]
Hi @yuzhiquan, @serathius, want to confirm. The above listed todo items, the PR for them will go after the https://github.com/kubernetes/klog/pull/249 is merged, right?

**Comment by yuzhiquan** [comment]
> Hi @yuzhiquan, @serathius, want to confirm. The above listed todo items, the PR for them will go after the [kubernetes/klog#249](https://github.com/kubernetes/klog/pull/249) is merged, right?

Yes, klog#249 should merged first before we move on other TODO.

**Comment by Priyankasaggu11929** [comment]
update on this issue ~ still awaiting for a new `klog` release version. I'll follow up on the same.

**Comment by yuzhiquan** [comment]
Hi,  @Priyankasaggu11929 we can cotinue now.

**Comment by yuzhiquan** [comment]
Our implement will be pacth to k/k in this https://github.com/kubernetes/kubernetes/pull/104103

**Comment by Priyankasaggu11929** [comment]
Thanks @yuzhiquan. I’ll pick up the items.

**Comment by serathius** [comment]
Any progress on this?

**Comment by yuzhiquan** [comment]
@Priyankasaggu11929 We can mobe on this now, https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/klog/v2/klog.go#L1626 is merged

**Comment by serathius** [comment]
I think with removal of format.pods this issue is done.
/close

**Comment by yuzhiquan** [comment]
> I think with removal of format.pods this issue is done. /close

We need update docs for user guide?

**Comment by serathius** [comment]
Let me add it to https://github.com/kubernetes/community/pull/6283 then.
