### ISSUE TITLE
kubectl config view --minify should also report basic auth info

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#10247]
```
$ kubectl config view --minify
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://173.255.113.219
  name: kubernetes-satnam_e2e-test-satnam
contexts:
- context:
    cluster: kubernetes-satnam_e2e-test-satnam
    user: kubernetes-satnam_e2e-test-satnam
  name: kubernetes-satnam_e2e-test-satnam
current-context: kubernetes-satnam_e2e-test-satnam
kind: Config
preferences: {}
users:
- name: kubernetes-satnam_e2e-test-satnam
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: LsUe2Z4cXqa61UQqQ2qWGGf7nOSLw9np
```

**Comment by satnam6502** [comment]
@jlowdermilk

**Comment by jlowdermilk** [comment]
The basic auth info is actually in a different user, which is why it doesn't show up with minify. It's not valid for a kubeconfig user entry to contain redundant authentication schemes (i.e. both `token` and `username/password`). It's generated as a separate user for convenience [here](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/common.sh#L87). For the above example, it would be in user kubernetes-satnam_e2e-test-satnam-basic-auth.

That being said, I don't think we even need the token any more, the certs should be sufficient. cc @roberthbailey

**Comment by satnam6502** [comment]
We don't need the token? Then how would I sensibly curl to the Elasticsearch logging service? Would I be forced to use basic auth for that?

**Comment by jlowdermilk** [comment]
Sorry, I meant to make that a question not a statement. I don't have enough context to know what pieces are currently using the token. Perhaps a better question is what do we still use basic auth for? Is it just for hitting the api with a browser?

**Comment by satnam6502** [comment]
Yes, basic auth is what we tell people to use when accessing cluster level services from the browser, and token for when using curl. See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging-elasticsearch.md

**Comment by jlowdermilk** [comment]
Seems like we should be telling users to run `kubectl proxy` to access cluster level services from the browser. Do you know if cluster level services are accessible via `kubectl proxy`? I recall there being some trouble with it, but I thought we fixed it.

**Comment by satnam6502** [comment]
`kubectl proxy` works now because we have switched to a newer version of Kibana that can access Elasticsearch via a DNS name for its service. However, I feel we also ought to support direct access via the proxy at the master.

**Comment by roberthbailey** [comment]
We should no longer need the token in the kubeconfig file that is used client-side by kubectl (you can verify this by deleting the `token: LsUe2Z4cXqa61UQqQ2qWGGf7nOSLw9np` line from your file -- everything will continue to work). 

That doesn't mean we should remove bearer token or basic auth support from the apiserver though. We also use bearer token auth for kube-proxy on GCE btw.
