### ISSUE TITLE
Failing snapshot tests due to resource version mismatch

### ISSUE THREAD

**Issue by venkatsc** [kubernetes/kubernetes#102482]
#### Which test(s) are failing:
Snapshots tests

#### Since when has it been failing:
From k8s v20.2

#### Reason for failure:
Some clusters need `v1beta1` resources for [Snapshot resources.](https://github.com/rook/rook/issues/6819#issuecomment-852059116)
Required `v1beta1` snapshot class is provided through file as following
```yaml
SnapshotClass:
   FromFile: <v1beta1 Storage class>
```
However, the testing frame work is [not using the supplied version](https://github.com/kubernetes/kubernetes/blob/17f3990ea1cdc1bd20c0d6e742c247b5b72beae0/test/e2e/storage/utils/snapshot.go#L137) but adding `v1` resulting in test failures.

/sig storage

**Comment by Kartik494** [comment]
Hi @venkatsc  are you applying corresponding crd's for snapshots?Could you describe here in more details

**Comment by Kartik494** [comment]
You can find the crd [here](https://github.com/kubernetes-csi/external-snapshotter/tree/master/client/config/crd) and apply correspondingly

**Comment by venkatsc** [comment]
Thank you @Kartik494  for the hint. I don't remember exactly which CRD the cluster has and it was long time ago.
