### ISSUE TITLE
Kubernetes fails to start after host reboot

### ISSUE THREAD

**Issue by davig019** [kubernetes/kubernetes#102460]
#### What happened:
After server reboot the master does not start
#### What you expected to happen:
The master to start
#### How to reproduce it (as minimally and precisely as possible):
Install k8s using getting started guide and reboot server
#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration: proxmox vm
- OS (e.g: `cat /etc/os-release`):Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): 5.4.0-73-generic
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): calico

Other:

Docker info:

    root@k8s-master-sun:/var/lib/kubelet# docker version
    Client: Docker Engine - Community
     Version:           20.10.6
     API version:       1.41
     Go version:        go1.13.15
     Git commit:        370c289
     Built:             Fri Apr  9 22:47:17 2021
     OS/Arch:           linux/amd64
     Context:           default
     Experimental:      true
    
    Server: Docker Engine - Community
     Engine:
      Version:          20.10.6
      API version:      1.41 (minimum version 1.12)
      Go version:       go1.13.15
      Git commit:       8728dd2
      Built:            Fri Apr  9 22:45:28 2021
      OS/Arch:          linux/amd64
      Experimental:     false
     containerd:
      Version:          1.4.6
      GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
     runc:
      Version:          1.0.0-rc95
      GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
     docker-init:
      Version:          0.19.0
      GitCommit:        de40ad0

Kube info:

    root@k8s-master-sun:/var/lib/kubelet# kubectl version
    Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
    The connection to the server localhost:8080 was refused - did you specify the right host or port?
    root@k8s-master-sun:/var/lib/kubelet# kubeadm version
    kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

Swap is off:

    root@k8s-master-sun:/var/lib/kubelet# cat /proc/swaps
    Filename                                Type            Size    Used    Priority
    root@k8s-master-sun:/var/lib/kubelet#

Node is routable (via /etc/hosts) :

    root@k8s-master-sun:/var/lib/kubelet# ping control.k8s
    PING control.k8s (192.168.11.3) 56(84) bytes of data.
    64 bytes from k8s-master-sun (192.168.11.3): icmp_seq=1 ttl=64 time=0.023 ms
    64 bytes from k8s-master-sun (192.168.11.3): icmp_seq=2 ttl=64 time=0.017 ms

Docker both restarted and runable:

    sudo systemctl restart docker
    root@k8s-master-sun:/var/lib/kubelet# docker ps
    CONTAINER ID   IMAGE                    COMMAND                  CREATED             STATUS             
    PORTS     NAMES
    8aebf12fc5df   a4183b88f6e6             "kube-scheduler --au…"   About an hour ago   Up About an hour             k8s_kube-scheduler_kube-scheduler-k8s-master-sun_kube-system_f0df6f397c24d3b110cf48ad64e0d7d9_4
    263f604d5693   e16544fd47b0             "kube-controller-man…"   About an hour ago   Up About an hour             k8s_kube-controller-manager_kube-controller-manager-k8s-master-sun_kube-system_e62ca8baa5393cdf116f38061ef8fc62_5
    f8f460186396   k8s.gcr.io/pause:3.4.1   "/pause"                 About an hour ago   Up About an hour             k8s_POD_kube-scheduler-k8s-master-sun_kube-system_f0df6f397c24d3b110cf48ad64e0d7d9_4
    dcc3a30f46a9   k8s.gcr.io/pause:3.4.1   "/pause"                 About an hour ago   Up About an hour             k8s_POD_kube-controller-manager-k8s-master-sun_kube-system_e62ca8baa5393cdf116f38061ef8fc62_4
    6d8aa6f68f4c   k8s.gcr.io/pause:3.4.1   "/pause"                 About an hour ago   Up About an hour             k8s_POD_kube-apiserver-k8s-master-sun_kube-system_14a666fcea486a2c883aa3cb67958817_4
    root@k8s-master-sun:/var/lib/kubelet#

Kubelet logs(> char limit on post)
https://pastebin.com/fHbwegsP

**Comment by cndoit18** [comment]
I think it depends on your deployment, can you elaborate on that?

**Comment by neolit123** [comment]
/kind support
/remove-kind bug
until confirmed

reading trough the kubelet logs it seems the apiserver pod is failing to start.
can you try obtaining logs from the apiserver container?

**Comment by neolit123** [comment]
closing due to no response.
/close

**Comment by neolit123** [comment]
you can use the support channels in the future:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
