### ISSUE TITLE
when the node restarts, the numa information of the device cannot be obtained from the checkpoint

### ISSUE THREAD

**Issue by silenceper** [kubernetes/kubernetes#102552]
#### What happened:
When the node restarts, the numa information of the device cannot be obtained from the checkpoint(maybe device plugin start slow), resulting in an error in the cpuset setting.

Through the tracking code, it is found that when the kubelet is restarted, the Topology information is not retained in the checkpoint.
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/cm/devicemanager/topology_hints.go#L131-L139

`m.allDevices` is nil.

#### What you expected to happen:
`m.allDevices` can restore from checkpoint.Can get the numa information correctly 

#### How to reproduce it (as minimally and precisely as possible):
- The device plugin reports the device information and the associated numa, and normally schedules a pod to the node
- Restart node, the device plugin may not be started yet, or it may be slow to start. At this time, the original container is being started gradually
- kubelet print message "[topologymanager] Hint Provider has no preference for NUMA affinity with any resource"
- the origin container can not get numa from device plugin

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzshiming** [comment]
https://github.com/kubernetes/kubernetes/blob/e52b7be7d719673a1a5ae28ad3bb0d6db58d35ec/pkg/kubelet/cm/devicemanager/endpoint.go#L96-L121

It seems that your Kubelet is not ready, or the ApiServer response is too slow, I think it is unnecessary to store AllDevices.

**Comment by silenceper** [comment]
But the startup sequence is uncontrollable, or when the abnormal situation of node restart occurs, or the device itself starts slowly?

**Comment by wzshiming** [comment]
If the Device is not actually ready, and the Kubelet assumes it is ready, will it introduce new bug?

**Comment by silenceper** [comment]
This will only affect pods that have been scheduled to node. If the device is not ready, then kubelet cannot obtain device related information, and the information obtained by kubelet from checkpoint does not record numa related information. Resulting in failure to obtain topology information, and ultimately affect the setting of cpuset.

**Comment by swatisehgal** [comment]
> If the device is not ready(In other words, even if it is ready, all device information is not reported)
The above statement is not clear to me.
I tried reproducing this issue but noticed that after kubelet restart the topology information is getting repopulated in the checkpoint file. Can you please add more description on the how to exactly reproduce this issue? Are we saying that this issue occurs when the device plugin is not ready and kubelet restart occurs? I would like to gain a better understanding of exactly the circumstances under which we encounter this bug.

**Comment by silenceper** [comment]
Meet several conditions:
1. The kubelet restarts
2. The device plugin has not reported device information in time
3. Only containers that have been running on the original node (without rescheduling) will get the error numa information

**Comment by fromanirh** [comment]
In the restart flow, the kubelet should reset the allocatable device count to zero until the device plugin register itself again (https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/cm/devicemanager/manager.go#L517).
Which can be slow indeed, but pods should not reach the node until devices are reported allocatable.
When the device plugin registers itself again, it will report topology information, so we're good.

It seems to me that you possibly just hit https://github.com/kubernetes/kubernetes/issues/102880 maybe?

**Comment by pacoxu** [comment]
@silenceper  would you confirm if it is dupped to #102880?

**Comment by silenceper** [comment]
I looked at the issue  #102880, and from my point of view, it does not seem to be the problem I encountered here.

**Comment by fromanirh** [comment]
thanks for updating the reproduction steps.
Unfortunately is still not very clear how to reproduce the issue. The steps you added document what happens when the condition triggers. What we miss is the steps to reproduce the state which makes it possible for the condition to trigger, so we can properly assess the bug severity.
For example:
- do we need a special device plugin or does it happen with any device plugin?
- do we need a particulat combination of pods or just one pod requesting devices is enough?
- do the pod need to be static or any combination of pods is sufficient?
- does the issue happen with a simple kubelet restart or do after a node drain?
- what triggered the kubelet restart? perhaps a crash? was the restart triggered by a kubelet update?

Ideally, the reproduction steps should allow us to write a end to end (e2e) test which reproduces the bug and validates the fix, preventing regressions: https://github.com/kubernetes/kubernetes/pull/102882/commits/ca593e562f7913ef14eff0647d3c97da125c3cf7
