### ISSUE TITLE
Scheduler: add plugin name to the filter message

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102573]
When the scheduler fails to find a node to schedule a pod, a message is logged summarizing the reason. It would be helpful if we include the plugin name in the summary message so that it is easier to parse this message by diagnostic tools. 

I also wonder if we can utilize structured logging to report an even easier to parse log message.

/sig scheduling

**Comment by alannatodd** [comment]
@ahg-g I'm interested in working on this as my first issue - is that ok? (Can remove my assignment if not)

/assign

**Comment by alannatodd** [comment]
@ahg-g Could you point me to the log message(s) this is for? I searched through a lot of the scheduler code but I couldn't figure out which one(s) you are referring to.

**Comment by ahg-g** [comment]
I think we need to do it here: https://github.com/kubernetes/kubernetes/blob/5a21b978820ff266fcbd81e72f1dabc515172eca/pkg/scheduler/framework/interface.go#L246

how about we do 

```
for _, s := range p {	
 .....

  for p, r := range s.reasons {  
    finalStatus.AppendReason(fmt.Sprintf("%s/%s", p, r))
  }
}
```

@alculquicondor @Huang-Wei wdyt?

but it would be cool if we can do something more structured.

**Comment by alculquicondor** [comment]
The reasons are used in the event message. I'm not in favor of increasing the size of the message. We already hit some limitations in the past. It would be better if somehow the list of failed plugins can make it to the log line without affecting the event.

**Comment by alannatodd** [comment]
Also, not really related but should this:
https://github.com/kubernetes/kubernetes/blob/53873fbf23aa357aeae6e1b6f8cd8459fd459407/pkg/scheduler/scheduler.go#L525

be this:
`klog.ErrorS(nil, "Status after running PostFilter plugins for pod", "pod", klog.KObj(pod), "status", status)` 
(missing the "pod" key from the key-value name argument)

**Comment by Huang-Wei** [comment]
> but it would be cool if we can do something more structured.

Yes, my rough idea is to make the current stringified "status" message more structured, something like:

```
klog.XYZf("generic message...", "pod", klog.KObj(pod), "reasons", "simplified reasons (unlike current reasons that mix everything together)", "phase", "<PreFilter, Filter, etc.>", "failedBy", "failed plugin(s)", "anything else for log analysis")
```

We can have different logging templates and helpers to ease the log dumping, as well as eventing.

**Comment by Huang-Wei** [comment]
@alannatodd Thanks for the interest. We can brainstorm here and get to an initial consensus first.

**Comment by jyz0309** [comment]
@alannatodd Hello! Are you still working this issue? Can I try it? Or join the brainstorm :)

**Comment by mikechengwei** [comment]
Hi guys,From the above discussion, I designed a plan.
First of all, we have to consider two points:
1. We should not change the existing `merge` method, we need to build a new method for structured output to avoid increasing the size of event messages.
2. Since the current reason is mixed together, we need to simplify it.

For the first point, I searched the code and did not find that the event send uses reasons.I think event message just use error msg. @alculquicondor wdyt？

For the second point, i will build a new method called `newMerge` method, it will return reasons format with `pluginName/reasons` string.  @Huang-Wei huang wdyt？

**Comment by alculquicondor** [comment]
> For the first point, I searched the code and did not find that the event send uses reasons.I think event message just use error msg.

The error message is built from the reasons. See the implementation of `FitError.String`

**Comment by mikechengwei** [comment]
> > For the first point, I searched the code and did not find that the event send uses reasons.I think event message just use error msg.
> 
> The error message is built from the reasons. See the implementation of `FitError.String`
Thanks,i see in . 
https://github.com/kubernetes/kubernetes/blob/dadecb2c8932fd28de9dfb94edbc7bdac7d0d28f/pkg/scheduler/framework/types.go#L233 .

**Comment by mikechengwei** [comment]
I find that event msg use  `FitError` Error method build , It assembles `reasons` by itself and output a `reasonMsg`.

Ref:
https://github.com/kubernetes/kubernetes/blob/dadecb2c8932fd28de9dfb94edbc7bdac7d0d28f/pkg/scheduler/framework/types.go#L233 

Eevent msg build method is independent of the status `merge` method.

Ref:
https://github.com/kubernetes/kubernetes/blob/dadecb2c8932fd28de9dfb94edbc7bdac7d0d28f/pkg/scheduler/framework/interface.go#L254

I find the scheduler's entire life cycle process, only `RunPostFilterPlugins` lacks the plugin name, and the other phase have contained it.For example :
https://github.com/kubernetes/kubernetes/blob/dadecb2c8932fd28de9dfb94edbc7bdac7d0d28f/pkg/scheduler/framework/runtime/framework.go#L940

So，I think it is ok for optimizing Status `merge` method to add plugin name.Wdyt? @ahg-g

**Comment by fulviodenza** [comment]
Is this issue still open? If nobody work on it I'd like to work on this issue as my first issue
