### ISSUE TITLE
Restart crucial components in an e2e test

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#10254]
Write an e2e test that restarts various components and confirms expectations. Things to consider restarting (we already have an e2e that restarts etcd, and reboots the node iirc):
1. controller manager during replica/service/node creation
2. scheduler with unassigned pods
3. kubelet with pending/deleted pods 
4. apiserver
5. kubeproxy 
6. docker

If some of these restarts fail it could leave the cluster in a bad state, so we might not want to run this as part of the regular e2es.

**Comment by mbforbes** [comment]
More reboot tests!

**Comment by mbforbes** [comment]
It'd be great to get our current "blow stuff away" tests out of their own sandbox and into the real world as well. If these things take a while to run I fear they'll also be relegated.

But overall, this seems like a great idea!

**Comment by ixdy** [comment]
Much of this has been done in the "disruptive tests", no?

Should we close this issue?
@kubernetes/goog-testing

**Comment by bprashanth** [comment]
Yeah closing
