### ISSUE TITLE
Not able to connect to mongoDb when pod is in terminating state implementing prestop hook 

### ISSUE THREAD

**Issue by nature-18** [kubernetes/kubernetes#102501]
#### What happened:
We have our microservices are deployed in azure kubernetes service. In one of the pod, we wanted to implement prestop hook, so that before termination, it should gather all inprogress items and update the mongodb collection and deliver the message back to service bus queue to process from where it left. But as soon as the prestop is called, the mongo connection is lost with error "no reachable server" 
#### What you expected to happen:
It should not lose connection to mongodb and service bus during the terminationGracePeriod
#### Environment:
- Kubernetes version (use `kubectl version`): 1.20.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
hi, please also please try the support forums for feedback from more users:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support

**Comment by neolit123** [comment]
/sig node
for feedback on this around terminationGracePeriod

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

You may also want to reach out to AKS support for assistance, but this appears to be an application-specific issue.

/remove-kind bug
/close
