### ISSUE TITLE
Container restart policy - Problem settings Spec in Pod

### ISSUE THREAD

**Issue by MrPallaBall** [kubernetes/kubernetes#102562]
I'm following this page og official documentation https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy

I would like to set the `spec.restartPolicy`  of a Pod with the Never value, but Kubernetes in GCP give me this message:

> spec.template.spec.restartpolicy unsupported value Never supported values always

The same appends when I set OnFailure value.

How I can set `spec.restartPolicy` with Never value?

**Comment by pacoxu** [comment]
dup with #24725
/kind support
/remove-kind bug

**Comment by ehashman** [comment]
/close

Please submit a support ticket to GCP support. This is the Kubernetes development repo.
