### ISSUE TITLE
Konnectivity Service doesn't tolerate wildcard taints and gets evicted when node gets tainted with NoExecute.

### ISSUE THREAD

**Issue by scubakiz** [kubernetes/kubernetes#102582]
#### What happened:
Konnectivity Service gets evicted when node gets tainted with NoExecute.

#### What you expected to happen:
Just like CoreDNS and KubeProxy, Konnectivity-agent should not get evicted when Node gets a taint.

#### How to reproduce it (as minimally and precisely as possible):
Have a port-forward running from a service and taint a node with a NoExecute option.  Konnectivity-agent is deleted and can't get scheduled on the Node again until taint is removed.

#### Anything else we need to know?:
All other system pods use a wildcard toleration and are not effected by node taints.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.11
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
As I know, only kube-proxy tolerates NoExecute.

https://github.com/kubernetes/kubernetes/blob/646acf096e61dcda9cc20c9acbbe2969741e07c3/cluster/gce/manifests/kube-proxy.manifest#L12-L19

coredns does not.

https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/cluster/addons/dns/coredns/coredns.yaml.sed

konnectivity agent's setting is same as coredns.
https://github.com/kubernetes/kubernetes/blob/646acf096e61dcda9cc20c9acbbe2969741e07c3/cluster/gce/addons/konnectivity-agent/konnectivity-agent-ds.yaml#L21-L24

**Comment by pacoxu** [comment]
/cc @Jefftree  @cheftako 

Like dns-node-cache and kube-proxy, daemonset seems to have the toleration. 
/assign

kubeadm kube-proxy is using below.
https://github.com/SataQiu/kubernetes/blob/c66a7bc42c528bcf95eb910a7f28f9efccbbaafe/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L111-L112

**Comment by jkh52** [comment]
As long as this stays DaemonSet, these broader tolerations seem acceptable.

With GKE we have switched to Deployment, and intentionally do not have these broad tolerations (to avoid poor interaction with cluster-autoscaler). @MaciekPytel

**Comment by scubakiz** [comment]
In its current state (as a DaemonSet), NoExecute taint can never be used in AKS.  When such a taint is applied, Konnectivity Service gets evicted and the cluster loses connectivity to the client (the port-forward drop the connection and will not restart it).  Have to move my testing Pod to a different node before I can use it again, while the original node remains without the Konnectivity Service until the taint is removed.

I can get around the issue in the short-term:

**Old process:**
kubectl taint node $selectedNode process=gpu:NoExecute

**New process:**
kubectl taint node $selectedNode process=gpu:NoSchedule
kubectl delete pods --field-selector=spec.nodeName=$selectedNode

Since the second command only runs in the current namespace, Konnectivity Service is not affected.   

While the workaround accomplishes the same results, it seems like a hack.
