### ISSUE TITLE
[AutoScaling] Kubernetes Ingress Object Metrics with Community NGINX Ingress Controller

### ISSUE THREAD

**Issue by chirangaalwis** [kubernetes/kubernetes#102575]
#### What would you like to be added:
A [custom metrics API implementation](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-custom-metrics) for capturing the request count per unit time of a Kubernetes Ingress resource object, when using the community NGINX Ingress Controller in order to be used as a metric for Horizontal Pod Autoscaling (HPA).

The ultimate goal is to be able to add a request per unit time metric to Horizontal Pod Autoscaler as described in the [walk through](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics), when using the community NGINX Ingress Controller implementation.

```
type: Object
object:
  metric:
    name: requests-per-second
  describedObject:
    apiVersion: networking.k8s.io/v1beta1
    kind: Ingress
    name: main-route
  target:
    type: Value
    value: 2k
```

An example similar to the suggested solution can be found at [Skipper collector](https://github.com/zalando-incubator/kube-metrics-adapter#skipper-collector) with the [kube-metrics-adapter](https://github.com/zalando-incubator/kube-metrics-adapter#kube-metrics-adapter). This particular solution works when using the [skipper](https://github.com/zalando/skipper) Ingress Controller implementation.

#### Why is this needed:

- The accuracy of request per unit time, as a metric for HPA is considered to be very high. Especially, when working with container based deployments of language runtimes involving garbage collection. Please see this [#sig-autoscaling Slack channel discussion](https://kubernetes.slack.com/archives/C09R1LV8S/p1622375253069800?thread_ts=1622094642.065900&cid=C09R1LV8S) for a details about this topic.

- Community NGINX Ingress Controller being one of the most widely used implementations.

#### Notes:

- Original requests made at [#sig-autoscaling](https://kubernetes.slack.com/archives/C09R1LV8S/p1622610189078100) and [#ingress-nginx-users](https://kubernetes.slack.com/archives/CANQGM8BA/p1622550824303000) Slack channels.

- [Discussion on accuracy of metrics for HPA](https://kubernetes.slack.com/archives/C09R1LV8S/p1622094642065900)

**Comment by gjtempleton** [comment]
Hey, thanks for raising this issue!

SIG Autoscaling and the core kubernetes codebase doesn't actually build or own any implementations of the custom metrics API, we just own the core functionality, allowing others to build tools for different metrics backends to serve the APIs.

Could you clarify why using Prometheus to scrape the nginx metrics and then using the [prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter) to expose these metrics as object metrics for the purposes of scaling wouldn't allow you to do what you're needing?

/remove-kind feature
/kind support

**Comment by chirangaalwis** [comment]
@gjtempleton appreciate your feedback on this matter.

A concern I encountered with regards to using NGINX Ingress Controller metrics, was as to how this solution could be integrated to a scenario which involves multiple Ingresses being managed by a single NGINX Ingress Controller installation (e.g. a multi application deployment in which each application service is exposed via its own Ingress resource and each application needs to be individually auto scaled based on the request count specific to it).

In such a scenario, the request count for a unit time, scraped from the NGINX Ingress Controller obviously is for all the Ingresses and not for each Ingress (please correct me if I am wrong).

@gjtempleton this is the reason for me to create this issue. Please refer https://github.com/kedacore/keda/issues/538#issuecomment-854495169 to an issue comment I have added regarding this in [KEDA](https://github.com/kedacore/keda) implementation.

**Comment by chirangaalwis** [comment]
Updating the issue thread with the sig-autoscaling Slack channel discussion (https://kubernetes.slack.com/archives/C09R1LV8S/p1622610189078100) with @gjtempleton.

**Comment by rikatz** [comment]
Hi,

Thanks for the issue and the idea. Although ingress-nginx is indeed a SIG Network subproject, we have our repo in https://github.com/kubernetes/ingress-nginx

Can you open this issue on our specific repo, and closing this one. This way we can have some more eyes (ingress nginx implementators) into that.

Thanks! You can mark me and @strongjz into that issue :)

**Comment by chirangaalwis** [comment]
Created issue https://github.com/kubernetes/ingress-nginx/issues/7283 as suggested and closing this.
