### ISSUE TITLE
Kubelet does not compress container logs

### ISSUE THREAD

**Issue by peng09** [kubernetes/kubernetes#102553]
#### What happened:
Kubelet does not compress container logs and the total disk usage for container logs exceeded ContainerLogMaxSize.

#### What you expected to happen:
Kubelet compress old container logs even if the file size of latest container log file is less than threshold (ContainerLogMaxSize).

#### How to reproduce it (as minimally and precisely as possible):

Supposing the ContainerLogMaxFiles is 5 and ContainerLogMaxSize is 10M.
1. Kubelet have already renamed the current log file to a tmp file and reopen container log file, so there will be two files under pod logs directory: 0.log and 0.log.20200603-150405. The size of tmp file (0.log.20200603-150405) depends on the output of containers and it is greater than 10M.
2. Kubelet tries to compress the tmp file, but failed for some reason.
3. The container does not output new lines to newly created file 0.log and its size never grows larger than 10M.

Kubelet will not compress the tmp file anymore. If there are multiple cases on one host, it may cause disk usage leak.

#### Environment:
- Kubernetes version (use `kubectl version`):
1.14.8

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by lunhuijie** [comment]
I test this similar。
Mybe the reason is about "Kubelet tries to compress the tmp file, but failed for some reason."
After the log file is renamed, the soft link is not deleted, so the log will still be written to the previous file. That is what you said--0.log.20200603-150405. If you restart kubelet, you will find that the file is normal.

**Comment by lunhuijie** [comment]
This scenes is like to https://github.com/kubernetes/kubernetes/issues/100478s

**Comment by peng09** [comment]
I have tried to restart Kubelet, however tmp file is still uncompressed.

In Kubelet container_log_manager, it will only check the disk usage of latest container log. So before the size of latest log file exceeded threshold, it will not try to rotate/compress previous files in the meantime.

**Comment by lunhuijie** [comment]
tmp file is still uncompressed
How about 0.log, the container still does not output new lines to newly created file 0.log?

**Comment by peng09** [comment]
The container has the ability to output new logs, it just does not output new lines because process in container has finished its work.

The main concern in the issue above is that tmp file is uncompressed because of unexpected error, and Kubelet will not retry to compress it anymore and thus consume excessive disk spaces.

**Comment by lunhuijie** [comment]
/unassign 
I think the compression inside the container should be the responsibility of docker

**Comment by peng09** [comment]
Hi @lunhuijie , the uncompressed (tmp) files is under /var/log/pods directory on hosts, besides we are using Containerd as our runtime, so it is not related to Docker.

**Comment by pacoxu** [comment]
I have investigated issue #101656.  @saschagrunert 's comments: https://github.com/kubernetes/kubernetes/issues/101656#issuecomment-836373487

I think it would be a kubelet issue. But 1.14.8 is really old. You'd better reproduce it with a newer kubelet version.
The question here is how to reproduce it. I don't know how to simulate the compress failure.
>`Kubelet tries to compress the tmp file, but failed for some reasons`

I dug into the code, do you get logs like below? `failed to compress log`
https://github.com/kubernetes/kubernetes/blob/f545438bd347d2ac853b03983576bf0a6f1cc98b/pkg/kubelet/logs/container_log_manager.go#L284-L292

And I think the compress error should be provided. We should retry if the compress failure is a general error, not special one.
