### ISSUE TITLE
Get rid of duplicate set of metrics for watch counts

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#102545]
Just noticed that we have redundant metrics for watch counts like:

```
# HELP apiserver_longrunning_gauge [ALPHA] Gauge of all active long-running apiserver requests broken out by verb, group, version, resource, scope and component. Not all requests are tracked this way.
# TYPE apiserver_longrunning_gauge gauge
apiserver_longrunning_gauge{component="apiserver",group="",resource="configmaps",scope="cluster",subresource="",verb="WATCH",version="v1"}
 1
apiserver_longrunning_gauge{component="apiserver",group="",resource="configmaps",scope="namespace",subresource="",verb="WATCH",version="v1"} 25
```
^ This was added in v1.9 as part of https://github.com/kubernetes/kubernetes/pull/52302

```
# HELP apiserver_registered_watchers [ALPHA] Number of currently registered watchers for a given resources
# TYPE apiserver_registered_watchers gauge
apiserver_registered_watchers{group="",kind="ConfigMap",version="v1"} 26
```
^ This was added in v1.11 as part of https://github.com/kubernetes/kubernetes/pull/63779

We probably should get rid of the latter since the former is more granular and also includes other long-running calls (like proxy). Both seem to be in alpha status FWIW.

/cc @wojtek-t @smarterclayton (authors for those changes)
/sig instrumentation
/good-first-issue

**Comment by sanwishe** [comment]
@vineelyalamarthy Thank you very much for assigning. but I’ve already working on this issue. It is a pleasure to working with you next time?
/unassign vineelyalamarthy

**Comment by pratikyadav33** [comment]
Hello Devs,
Is this Up for Grab I Would Like To contribute.

**Comment by wojtek-t** [comment]
Being addressed in https://github.com/kubernetes/kubernetes/pull/102595

**Comment by sorkinl** [comment]
There is a PR for this issue already and it seems it was decided what to do with the duplicate metric and I am not sure if this issue is relevant anymore?https://github.com/kubernetes/kubernetes/pull/102595#issuecomment-858833484
