### ISSUE TITLE
kubelet doesn't observe/get call for remounts.

### ISSUE THREAD

**Issue by Horopter** [kubernetes/kubernetes#102567]
#### What happened: 
When the block volume is detached ungracefully or by a reboot to compute instance, kubelet re-attaches the volume, but it doesn't mount it. Thus, it is inaccessible to the user.

#### What you expected to happen:
The volume should be mounted after attach automatically.

#### How to reproduce it (as minimally and precisely as possible):
1. Create a pod with one PVC to provision a block volume to it.
2. Detach the provisioned volume from the node forcefully.
3. Let kubernetes re-attach the volume. However, kubernetes doesn't trigger mount of the volume.
4. The volume is thus not available to the user. We suspect this is the case because we don't have mount reconciler like attach reconciler.

#### Anything else we need to know?:
Observed in both flex-volume and CSI volumes.
Current workaround we are using is that customer has to restart pod to ensure a reattach/remount, which is not conducive always.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.7
- Cloud provider or hardware configuration: OCI
- OS (e.g: `cat /etc/os-release`): Oracle-Linux-7.9

#### Logs:
The following lines in logs appear when volume is mounted for the first time but they don't appear post re-attachment.
```bash
Jun  3 12:03:09 compute-instance@host kubelet: I0603 12:03:09.075299    3023 reconciler.go:269] operationExecutor.MountVolume started for volume "default-token-ljdd7" (UniqueName: "kubernetes.io/secret/<UUID>-default-token-ljdd7") pod "pod-0" (UID: "<UUID>")
Jun  3 12:03:09 compute-instance@host systemd: Started Kubernetes transient mount for /var/lib/kubelet/pods/<UUID>/volumes/kubernetes.io~secret/default-token-ljdd7.
Jun  3 12:03:09 compute-instance@host kubelet: I0603 12:03:09.089833    3023 operation_generator.go:657] MountVolume.SetUp succeeded for volume "default-token-ljdd7" (UniqueName: "kubernetes.io/secret/<UUID>-default-token-ljdd7") pod "pod-0" (UID: "<UUID>")
Jun  3 12:03:09 compute-instance@host kubelet: I0603 12:03:09.576625    3023 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "volumeID" (UniqueName: "volumeGUID") pod "pod-0" (UID: "<UUID>")
Jun  3 12:03:09 compute-instance@host kubelet: E0603 12:03:09.576791    3023 nestedpendingoperations.go:301] Operation for "{volumeName:volumeGUID podName: nodeName:}" failed. No retries permitted until 2021-06-03 12:03:10.576747875 +0000 UTC m=+1295.690261304 (durationBeforeRetry 1s). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"volumeID\" (UniqueName: \"volumeGUID\") pod \"pod-0\" (UID: \"<UUID>\") "
Jun  3 12:03:10 compute-instance@host kubelet: I0603 12:03:10.579270    3023 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "volumeID" (UniqueName: "volumeGUID") pod "pod-0" (UID: "<UUID>")
Jun  3 12:03:10 compute-instance@host kubelet: E0603 12:03:10.579468    3023 nestedpendingoperations.go:301] Operation for "{volumeName:volumeGUID podName: nodeName:}" failed. No retries permitted until 2021-06-03 12:03:12.579407147 +0000 UTC m=+1297.692920583 (durationBeforeRetry 2s). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"volumeID\" (UniqueName: \"volumeGUID\") pod \"pod-0\" (UID: \"<UUID>\") "
```
They don't appear later when the volume is detached forcefully (and k8 attaches automatically) implying that mount is not being reconciled.

**Comment by msau42** [comment]
A reboot should be handled properly. When kubelet starts up, it performs "reconstruction" from any leftover directories on the host to clean them up. However some plugins may not implement reconstruction correctly, which may cause problems. But at least for CSI drivers, it should be working.

For the force detach while a workload is still running case, what is the cause of that? That scenario does not seem expected.
