### ISSUE TITLE
kubelet fails to download image via squid proxy server

### ISSUE THREAD

**Issue by vasusheoran** [kubernetes/kubernetes#102505]
#### What happened:
I have a private GKE cluster and I have set up docker to use squid proxy for worker nodes. **I can successfully pull images** from the private repo by sshing into the worker node and using `docker pull <REPO/IMAGE:TAG>`.

However, when creating a pod, kubelet fails to download image with following error:
`Failed to pull image "<IMAGE>": rpc error: code = Unknown desc = failed to pull and unpack image "<IMAGE>": failed to resolve reference "<IMAGE>": failed to do request: Head https://<REPO>/v2/<IMAGE>/manifests/<TAG>: dial tcp <IP>: i/o timeout`

When I checked the access logs for squid proxy, there were no entries present. Thus, I think k8s (kubelet) is not honouring the docker proxy settings.

Below is my http-proxy.conf file for docker in the worker node:
[Service]
Environment="HTTP_PROXY=http://192.168.1.17:3128"
Environment="HTTPS_PROXY=http://192.168.1.17:3128"
Environment="NO_PROXY=localhost,127.0.0.1,*.*.0.1"

#### Environment:
- Kubernetes version (use `kubectl version`):
  Client Version: v1.17.0
  Server Version: v1.19.9-gke.1400
- Cloud provider or hardware configuration:  
  GKE 

#### I have following questions:
1. Is this the correct approach to set up a cluster behind a corporate proxy?
2. Is there an alternative way to set up proxy settings for k8s?

**Comment by dims** [comment]
@vasusheoran please take this up with your GKE support folks.

thanks,
