### ISSUE TITLE
hack/test-integration.sh is extremely flaky

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#10257]
It's been failing with more frequency on CI (shippable/travis). Seeing "failed to find pid of Docker container" in the startup logs

```
I0623 19:30:07.776206 1790 endpoints_controller.go:258] Finished syncing service "default/kubernetes" endpoints. (1.237us)
I0623 19:30:07.782345 1790 server.go:592] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"localhost", UID:"localhost", APIVersion:"", ResourceVersion:"", FieldPath:""}): reason: 'starting' Starting kubelet.
I0623 19:30:07.784223 1790 server.go:592] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"localhost", UID:"localhost", APIVersion:"", ResourceVersion:"", FieldPath:""}): reason: 'invalidDiskCapacity' invalid capacity 0 on device "" at mount point ""
W0623 19:30:07.783134 1790 kubelet.go:684] Failed to move Kubelet to container "/kubelet": mountpoint for cgroup not found
I0623 19:30:07.786219 1790 kubelet.go:686] Running in container "/kubelet"
I0623 19:30:07.786420 1790 status_manager.go:56] Starting to sync pod status with apiserver
I0623 19:30:07.786540 1790 kubelet.go:1695] Starting kubelet main sync loop.
I0623 19:30:07.786644 1790 pod_manager.go:112] SET: Containers changed
E0623 19:30:07.783191 1790 kubelet.go:666] Image garbage collection failed: invalid capacity 0 on device "" at mount point ""
E0623 19:30:07.794661 1790 kubelet.go:1611] error getting node: node localhost not found
I0623 19:30:07.795247 1790 kubelet.go:1393] Desired: []*api.Pod{(*api.Pod)(0xc208c84000)}
I0623 19:30:07.783219 1790 server.go:63] Starting to listen on 127.0.0.1:10250
I0623 19:30:07.786100 1790 config.go:251] Setting pods for source http : {[0xc208da0400] 0 http}
W0623 19:30:07.800207 1790 container_manager_linux.go:173] [ContainerManager] Failed to ensure state of "/docker-daemon": failed to find pid of Docker container: exit status 1
```

@bprashanth, @lavalamp do you have cycles to look into this?

**Comment by lavalamp** [comment]
That looks like it's just a warning, no?

**Comment by jlowdermilk** [comment]
Hmm, I lost the original run. The failure I saw was failure to connect to node 127.0.0.1. It seems there are multiple causes of flakiness. The one I am still seeing that should be reproducible is endpoint creation timeout:
```
F0623 17:35:44.283956 31457 integration.go:802] FAILED: unexpected endpoints: timed out waiting for the condition
```
https://app.shippable.com/builds/55899561ce9ab80b00d0ac8a

**Comment by jlowdermilk** [comment]
Example run with "erro getting node" problems:
https://app.shippable.com/builds/5589861627cb5b0c00c5a00b
Run log has multiple

```
E0623 16:31:31.084895 31484 kubelet.go:1611] error getting node: node 127.0.0.1 not found
```

**Comment by bprashanth** [comment]
Any idea how one figures out the resource usage on the shippable machine?

I don't mean how many cores I'm supposed to get, I mean how much cpu etc the tests are actually using. If i was on a linux box I would use top/ps/sar etc to profile it during a run. I have seen some cases with what looks like high n/w latency (but could well be disk or something else).

The kubelet won't find the node if the watch goroutine never ran.

**Comment by lavalamp** [comment]
I think we run very close to timeouts on shippable. We need to print out how much time it took when it works, so that we can see if we just need to increase the time limit. In the cases I've seen, it looks like shippable takes about 10x as long to do something as my desktop.

**Comment by bprashanth** [comment]
Yes, I print it out in the rcs and bumped up log level to v(4) on shippable for exactly this reason. We have (/should have where we don't) perf tests that stress perf-y things. However the timeout on the endpoints controller is 60s with a comment that pretty much says 'reevaluate this timeout' or something along these lines. And without logging proof I'm a little hesitant about masking something that only shows up on flaky networks.

**Comment by caesarxuchao** [comment]
I'm timing the pod creation time in the intergration tests [here](https://github.com/GoogleCloudPlatform/kubernetes/pull/9899). It seems flakes are related to the workload on Shippable, because when I ran the tests in the night, it passed 23/24 runs. It has a much higher failure rate when running in the daytime.

**Comment by bprashanth** [comment]
https://github.com/Shippable/support/issues/1601

**Comment by dalanlan** [comment]
What about the warnings? 
```
W0723 05:48:10.602110       1 container_manager_linux.go:173] [ContainerManager] Failed to ensure state of "/docker-daemon": failed to find pid of Docker container: exit status 1
```
I have the same warning for kubelet #11733

**Comment by soltysh** [comment]
I'm getting constant failures from integration, see https://app.shippable.com/builds/560159cea94e1a0c0080e42b the last failure is:
```
F0922 13:58:46.044137   16123 integration.go:457] FAILED: pods never created timed out waiting for the condition
!!! Error in ./hack/test-integration.sh:55
  'KUBE_API_VERSIONS="v1,experimental/v1" KUBE_TEST_API_VERSIONS="$1" "${KUBE_OUTPUT_HOSTBIN}/integration" --v=${LOG_LEVEL} --max-concurrency="${KUBE_INTEGRATION_TEST_MAX_CONCURRENCY}"' exited with status 255
Call stack:
  1: ./hack/test-integration.sh:55 runTests(...)
  2: ./hack/test-integration.sh:69 main(...)
Exiting with status 1
+++ [0922 13:58:46] Integration test cleanup complete
```
