### ISSUE TITLE
kubelet panic with fatal error: concurrent map writes

### ISSUE THREAD

**Issue by tongchao199** [kubernetes/kubernetes#102517]
/sig node
/area kubelet

#### What happened:
kubelet panic with fatal error concurrent map writes when allocate container device

* panic log
```shell
Jun  1 19:47:24 gpu-node-330 kubelet: fatal error: concurrent map writes
Jun  1 19:47:24 gpu-node-330 kubelet: goroutine 2684 [running]:
Jun  1 19:47:24 gpu-node-330 kubelet: runtime.throw(0x434c2b8, 0x15)
Jun  1 19:47:24 gpu-node-330 kubelet: /usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc00223f6c8 sp=0xc00223f698 pc=0x432eb2
Jun  1 19:47:24 gpu-node-330 kubelet: runtime.mapassign_faststr(0x3a96760, 0xc000c3b4a0, 0xc000e62fc0, 0x24, 0x7029de0)
Jun  1 19:47:24 gpu-node-330 kubelet: /usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc00223f730 sp=0xc00223f6c8 pc=0x416d27
Jun  1 19:47:24 gpu-node-330 kubelet: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc000c944e0, 0xc000903c00, 0xc002687760, 0x42, 0xc00223fb78)
Jun  1 19:47:24 gpu-node-330 kubelet: /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/kubelet/cm/devicemanager/manager.go:365 +0x592 fp=0xc00223faa8 sp=0xc00223f730 pc=0x1b5b692
```

#### What you expected to happen:
kubelet no panic when allocate container device

#### How to reproduce it (as minimally and precisely as possible):
* Create pod, container has extended resource (like nvidia.com/gpu)
* Kubelet panic occasionally on nodes

#### Anything else we need to know?:
* system message logs
[messages.log](https://github.com/kubernetes/kubernetes/files/6581782/messages.log)

#### Environment:
- Kubernetes version (use `kubectl version`):
```shell
root@gpu-node-330:~$ kubelet --version
Kubernetes v1.18.9
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```shell
root@gpu-node-330:~$ clear
root@gpu-node-330:~$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
- Kernel (e.g. `uname -a`):
```shell
root@gpu-node-330:~$ uname -a
Linux gpu-node-330 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
* nvidia device plugin
```shell
 $ kubectl -n kube-system get ds nvidia-device-plugin-daemonset -o wide
NAME                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE    CONTAINERS                 IMAGES                                                          SELECTOR
nvidia-device-plugin-daemonset   2         2         2       2            2           accelerate-type=nvidia   432d   nvidia-device-plugin-ctr   k8s-device-plugin:1.0.0-beta   name=nvidia-device-plugin-ds
```
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/assign
seems to be a problem here https://github.com/kubernetes/kubernetes/blob/v1.18.9/pkg/kubelet/cm/devicemanager/manager.go#L363-L368

However, 1.18 is EoL, you may upgrade kubernetes to a newer version after it is fixed.

**Comment by pacoxu** [comment]
@tongchao199 https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-852865453
> Have you seen this actually cause an issue? This variable is only used in Allocate() and all calls to Allocate() are serialized.

At first glance, I think it would be a problem of no locking so I send a PR #102525 to fix it. However, as @klueska pointed out that this method are called serially. 

I checked the log and cannot find multi goroutine run into this function. Would you double check if the log you provided is complete?

**Comment by pacoxu** [comment]
@tongchao199  would you provide the complete panic logs? Thanks.

**Comment by tongchao199** [comment]
> @tongchao199 [#102525 (comment)](https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-852865453)
> 
> > Have you seen this actually cause an issue? This variable is only used in Allocate() and all calls to Allocate() are serialized.
> 
> At first glance, I think it would be a problem of no locking so I send a PR #102525 to fix it. However, as @klueska pointed out that this method are called serially.
> 
> I checked the log and cannot find multi goroutine run into this function. Would you double check if the log you provided is complete?

**Comment by tongchao199** [comment]
> @tongchao199 [#102525 (comment)](https://github.com/kubernetes/kubernetes/pull/102525#issuecomment-852865453)
> 
> > Have you seen this actually cause an issue? This variable is only used in Allocate() and all calls to Allocate() are serialized.
> 
> At first glance, I think it would be a problem of no locking so I send a PR #102525 to fix it. However, as @klueska pointed out that this method are called serially.
> 
> I checked the log and cannot find multi goroutine run into this function. Would you double check if the log you provided is complete?

@pacoxu 

What I exported is the complete message log. 
I review the v1.18.9 code, and the Allocate method is indeed called serially. 
This problem has occurred once in our test environment, but it has not been reproduced for the time being. 
We can track this problem and see if other people have encountered similar problems.

**Comment by pacoxu** [comment]
Thanks for the information.
