### ISSUE TITLE
start kube-apiserver failed with parameter "--port=8080 --secure-port=6443" on version 1.22.0-alpha.2

### ISSUE THREAD

**Issue by libaoan** [kubernetes/kubernetes#102619]
#### What happened:
when I start kube-apiserver on version v1.22.0-alpha.2 ,  I got an error blow...
```
[root@node1 ~]# journalctl -xe
Jun 05 19:07:41 node1 systemd[1]: --audit-log-path=/var/lib/audit.log
Jun 05 19:07:41 node1 systemd[1]: --event-ttl=1h
Jun 05 19:07:41 node1 systemd[1]: --allow-privileged=true': /etc/kubernetes/apiserver
Jun 05 19:07:41 node1 systemd[1]: Starting Kubernetes API Service...
-- Subject: Unit kube-apiserver.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kube-apiserver.service has begun starting up.
Jun 05 19:07:41 node1 kube-apiserver[4806]: Flag --insecure-bind-address has been deprecated, This flag has no effect now and will be rem
Jun 05 19:07:41 node1 kube-apiserver[4806]: Flag --port has been deprecated, This flag has no effect now and will be removed in v1.24.
Jun 05 19:07:41 **node1 kube-apiserver[4806]: Error: invalid port value 8080: only zero is allowed**
Jun 05 19:07:41 node1 systemd[1]: kube-apiserver.service: main process exited, code=exited, status=1/FAILURE
Jun 05 19:07:41 node1 systemd[1]: Failed to start Kubernetes API Service.
-- Subject: Unit kube-apiserver.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit kube-apiserver.service has failed.
```

#### How to reproduce it (as minimally and precisely as possible):
start kube-apiserver with parameters "--port=8080 --secure-port=6443"

#### Environment:
- Kubernetes version (use `kubectl version`):
i
[root@node1 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-alpha.2", GitCommit:"7705b300e2085c3864bb1e49a7302bf17f080219", GitTreeState:"clean", BuildDate:"2021-05-21T00:12:47Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
start up with vagrant and virtualbox

- OS (e.g: `cat /etc/os-release`):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by liggitt** [comment]
Support for insecure serving is removed in 1.22

The only permitted value for the --port flag is now 0:
``` 
Flag --port has been deprecated, This flag has no effect now and will be removed in v1.24.
Jun 05 19:07:41 **node1 kube-apiserver[4806]: Error: invalid port value 8080: only zero is allowed**
```
