### ISSUE TITLE
TestExecPluginRotationViaInformer flake and slow > 2min

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#102650]
### Failure cluster [670e16aa8066230be73b](https://go.k8s.io/triage#670e16aa8066230be73b)

    exec_test.go:627: wanted sync true, got sync false
    exec_test.go:740: wanted sync true, got sync false
    exec_test.go:750: wanted sync true, got sync false

    exec_test.go:771: informer never changed resource versions from "42606": timed out waiting for the condition

##### Error text:
```
=== RUN   TestExecPluginRotationViaInformer
=== PAUSE TestExecPluginRotationViaInformer
=== CONT  TestExecPluginRotationViaInformer
E0527 06:04:00.043307  121243 controller.go:184] Get "https://127.0.0.1:40847/api/v1/namespaces/default/endpoints/kubernetes": dial tcp 127.0.0.1:40847: connect: connection refused
    testserver.go:380: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/cmd/kube-apiserver/app/testing"
I0527 06:04:02.747118  121243 serving.go:341] Generated self-signed cert (/tmp/kubernetes-kube-apiserver650002284/apiserver.crt, /tmp/kubernetes-kube-apiserver650002284/apiserver.key)
I0527 06:04:02.747132  121243 server.go:614] external host was not specified, using 127.0.0.1
W0527 06:04:02.747142  121243 authentication.go:524] AnonymousAuth is not allowed with the AlwaysAllow authorizer. Resetting AnonymousAuth to false. You should use a different authorizer
    testserver.go:215: runtime-config=map[api/all:true]
    testserver.go:216: Starting kube-apiserver on port 45509...
W0527 06:04:04.040009  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040050  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040068  121243 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0527 06:04:04.040611  121243 mutation_detector.go:53] Mutation detecto
```
#### Recent failures:
[2021/5/31 上午4:10:22 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1399095506172383232)
[2021/5/27 下午9:41:15 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1397910435235106816)
[2021/5/27 下午1:39:15 ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1397789133039996928)

/kind failing-test
/kind flake

@ankeesler  @enj as it is added in #101726
/sig auth

Open it as it is the top flake of pull-kubernetes-integration: http://storage.googleapis.com/k8s-metrics/flakes-latest.json

**Comment by ankeesler** [comment]
Commented on PR.

**Comment by ankeesler** [comment]
I've seen this test fail 2 times today on my PR https://github.com/kubernetes/kubernetes/pull/99310:
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99310/pull-kubernetes-integration/1402718119469780992
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/99310/pull-kubernetes-integration/1402696213777616896

Going to hope that I close my eyes and `/retest` and never see it again...but if it happens again I'll reopen this...

**Comment by pacoxu** [comment]
@ankeesler 
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=TestExecPluginRotationViaInformer
![image](https://user-images.githubusercontent.com/2010320/121462322-04c96a00-c9e3-11eb-9295-aaddf33c3310.png)

**Comment by ankeesler** [comment]
Opened https://github.com/kubernetes/kubernetes/issues/102842 to track flakes once again
