### ISSUE TITLE
[Failing test] [sig-network] Services [Slow] should be able to create and tear down a standard-tier load balancer 

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#102649]
#### Which jobs are failing:

ci-kubernetes-e2e-gci-gce-coredns
ci-kubernetes-e2e-gci-gce-slow
ci-kubernetes-e2e-gci-gce-ipvs

Basically, all jobs that run the test :)

#### Which test(s) are failing:

[sig-network] Services [Slow] should be able to create and tear down a standard-tier load balancer 

#### Since when has it been failing:

06-05

#### Testgrid link:

https://testgrid.k8s.io/sig-network-gce#gci-gce-ipvs&width=5
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=should%20be%20able%20to%20create%20and%20tear%20down%20a%20standard-tier%20load%20balancer

#### Reason for failure:

> 
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/network_tiers.go:64
> Jun  7 04:30:04.200: Unexpected error:
>     <*errors.errorString | 0xc003298bd0>: {
>         s: "timed out waiting for service \"net-tiers-svc\" to have a new ingress IP",
>     }
>     timed out waiting for service "net-tiers-svc" to have a new ingress IP
> occurred
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/network_tiers.go:147
>

**Comment by aojea** [comment]
/sig network

@MrHohn it seems you reported failures in this test previously and seems a GCE feature dependent on the GCE controller, can you PTAL?
cc @bowei @swetharepakula

**Comment by MrHohn** [comment]
> @MrHohn it seems you reported failures in this test previously and seems a GCE feature dependent on the GCE controller, can you PTAL?

It has been so long that I entirely forgot what was the previous cause. From a quick look, the gce loadbalancer controller stuck on an address not found error (logs from [a recent run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ipvs/1401934216412794880)):
```
E0607 16:34:25.784833      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:34:31.859107      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:34:42.934246      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:35:04.021560      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:35:45.118759      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:37:06.467103      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
E0607 16:39:47.664044      10 gce_loadbalancer.go:174] Failed to EnsureLoadBalancer(bootstrap-e2e, services-6097, net-tiers-svc, a8d573ae414fd4ec099dff43893319d3, us-west1), err: failed to ensure a static IP for load balancer (a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): error getting static IP address: googleapi: Error 404: Address with IP "35.212.229.111" was not found in region "us-west1"
```

**Comment by MrHohn** [comment]
Full logs related to the problematic service `services-6097/net-tiers-svc`: https://gist.github.com/MrHohn/447a74e7fa96cca6481fde8d35696b9b

It reads like the controller thought the service desired `Premium` tier network, where it actually wanted `Standard`?
```
I0607 16:34:25.183750      10 gce_loadbalancer_external.go:83] ensureExternalLoadBalancer(a8d573ae414fd4ec099dff43893319d3(services-6097/net-tiers-svc)): Desired network tier "Premium".
```

Would it be https://github.com/kubernetes/kubernetes/pull/102513? (purely based on the timing - don't see how that is related yet) @freehan

**Comment by freehan** [comment]
/assign

Thanks @MrHohn  

It is indeed caused by #102513. Pushed a PR to fix the e2e test.
