### ISSUE TITLE
ResourceVersion="0" causes no chunking, makes starting Informers expensive

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/kubernetes#102672]
I'm seeing issues where API servers experience high load when Informers start up.  I think I've traced it to this issue https://github.com/kubernetes/client-go/issues/366 where it was intentionally decided that chunking would not be peformed when ResourceVersion="0".  That decision dates from 2018 and was made because it was not possible to provide the correcct consistency guarantee (compatible with ResourceVersion="0") in a paged situation. 

Is any better solution possible now? 

For instance, is it possible to leverage the fact that, in recent versions "The metadata.resourceVersion of a resource collection (i.e. a list response) [identifies the resource version at which the list response was constructed](https://kubernetes.io/docs/reference/using-api/api-concepts/#resourceversion-in-metadata)."  So would it be possible to leverage that to allow real paging?  e.g. 

(a) client requests ResourceVersion="0"
(b) server computes resourceVersion of the list it is about to serve (i.e. "resource version at which the list was constructed").  This is the bit that I'm not sure about.  Can it compute that RV before it starts writing the response headers? 
(c) server does real chunking, and returns a continue token based on (b).  (Since as noted in the 2018 GitHub issue, it's not possible to base a continue token on (a).)

#### How to reproduce it (as minimally and precisely as possible):

Use the Go SDK to create and Run an Informer for some kind object that you have many thousands of.

#### Anything else we need to know?:

Just a few quick notes on the impact of this:

Firstly, there can be real impact on server resource consumption - especially if many different clients start Informers on large lists at the same time.  

Secondly, the current behaviour is confusing.  It doesn't seem to be documented anywhere outside a few GitHub comments.

Thirdly, it doesn't seem to be consistent with the intention of the [original KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/365-paginated-lists). For instance, the KEP says this

> A snapshot of all resources at a particular moment in time that has a single resourceVersion that clients can **begin watching** from to receive updates.

And yet, in realiting, when I client wants to "**begin watching**" that's currently the **one** time that chunking is NOT supported (due to this issue with ResourceVersion="0").

So it seems that a fundamental goal of the KEP is not being met by the current behaviour.

See also https://github.com/kubernetes/kubernetes/issues/96497 , which is about making the current beta behaviour GA.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.7
- Cloud provider or hardware configuration: AKS

**Comment by wojtek-t** [comment]
The solution for it is proper overload protection in kube-apiserver. This is already being worked on as part of https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness

**Comment by JohnRusk** [comment]
Thanks @wojtek-t .  

My understanding, from the chunking KEP and from my own testing, is that it's much more resource-efficient to do chunked listing than unchunked, and therefore in an ideal world, all list queries would be chunked.  There are also a number of other advantages of chunking, as outlined in the opening bullet points of the chunking KEP.

If I understand your reply correctly, you're saying that it's equally (or at least sufficiently) effective to leave the lists unchunked and asssign them wider width in the priority and fairness mechanism.  I don't yet understand how that can be the case.   Can you elaborate?

**Comment by wojtek-t** [comment]
Let me be more specific:

1) I agree that in most cases chunking is better then no-chunking (the problem is when there are too many chunks and before we process the last one you already went out of history window and need to start from the beginning)

2) The problem is that currently watchcache doesn't support chunking - so the current choice is: chunk from etcd or not chunk from watchcache.
And here it's no apples-to-apples comparison, because we can be waaay more efficient when listing from watchcache:
- it doesn't require deserialization (the objects are already in cache)
- we support indexes (e.g. kubelet listing pods from its node - from watchcache is proportional to the number of those pods, from etcd we list all pods in the whole system)
- we don't put any load on etcd (so it's also protecting etcd from overload)

So what I'm saying is that - if we add chunking support to watchcache - that will work. If you're suggesting to switch listing back to etcd, this will blow up large clusters.


Now - why I'm saying that P&F is the solution. You're saying that the problem is:

> Firstly, there can be real impact on server resource consumption - especially if many different clients start Informers on large lists at the same time.

This is because of lack of overload protection in kube-apiserver. P&F will address exactly this.


> Secondly, the current behaviour is confusing. It doesn't seem to be documented anywhere outside a few GitHub comments.

Behavior of what? How listing is done in the informer is an implementation detail and noone should rely on it. The public interface of the informer is pretty much about handlers, which don't depend on how listing is done.

> A snapshot of all resources at a particular moment in time that has a single resourceVersion that clients can begin watching from to receive updates.

This is true - list with RV=0 is a consistent read. It's a list form a given point in time (though potentially in the past).

**Comment by JohnRusk** [comment]
>Behavior of what? 

The behaviour that `limit` is ignored by the server if ResourceVersion=0. If that's the long-term plan, I think it has to be documented in the docomentation that describes `limit`\`continue` otherwise folks will keep wasting time trying to figure out what's happening.

Thanks for your detailed comments on all the other points.  I'll digest them and reply later.

**Comment by JohnRusk** [comment]
Out of curiousity, how will the `width` of a non-chunked list query be calculated?  I can see how to calculate it for a chunked one (since the upper bound on object counts is right there in the `limit` parameter).  But for an unchunked one, how is the `width` to be determined?

**Comment by wojtek-t** [comment]
> I think it has to be documented in the docomentation that describes

Agree. I though we did that, but apparently I'm wrong.

> Out of curiousity, how will the width of a non-chunked list query be calculated?

Based on total number of all objects of a given type. [We have that information already - we even export it as a metric]

**Comment by JohnRusk** [comment]
>Based on total number of all objects of a given type

Nice.  Is that functionality included in the beta of API Priority and Fairness that's in K8s 1.20?

**Comment by JohnRusk** [comment]
>So what I'm saying is that - if we add chunking support to watchcache - that will work. If you're suggesting to switch listing back to etcd, this will blow up large clusters.

I see.  Yes, your logic makes sense.  I had (naively) assumed that chunking was something equally achievable in all cases, but from your reply it sounds like it would be additional work (not able to leverage the current chunking code) if you were to from the watch cache.

One question, does `RV=1, ResourceVersionMatch=NotOlderThan`, also result in hitting etcd? (I know it gives the chance of a 410 Gone error on later pages in the list).

**Comment by wojtek-t** [comment]
> Nice. Is that functionality included in the beta of API Priority and Fairness that's in K8s 1.20?

No - the support for LIST was designed couple weeks ago and we're working on having it done in 1.22.

> I see. Yes, your logic makes sense. I had (naively) assumed that chunking was something equally achievable in all cases, but from your reply it sounds like it would be additional work (not able to leverage the current chunking code) if you were to from the watch cache.

Not necessary naively - it's an understandable intuition.
But yes - we don't support chunking from watchcache and adding it will be a very large piece of work (though it's periodically being discussed).

> One question, does RV=1, ResourceVersionMatch=NotOlderThan, limit=nnn, also result in hitting etcd? (I know it gives the chance of a 410 Gone error on later pages in the list).

Yes - it hits etcd.
The logic is basically here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L677

So we hit etcd if at least one of the following is true:
- resourceVersion is unset
- Continue is set
- limit >0 && resourceVersion != '0'
- ResourceVersionMath == ExactMatch
In your example the 3rd case is true, so it will hit etcd.

**Comment by JohnRusk** [comment]
Thanks for your detailed answers. Much appreciated.  I'll keep an eye on upcoming releases, and repeat some of my tests, with Priority and Fairness, once the List support is out.

Am I right in assuming that that it's intended to work even for lists as large as 10's of thousands of objects - e.g. 50,000 items?

If so, you're welcome to close this issue now.   (Unless you need it for tracking documentation updates, as discussed above).

**Comment by wojtek-t** [comment]
> Am I right in assuming that that it's intended to work even for lists as large as 10's of thousands of objects - e.g. 50,000 items?

yes

> If so, you're welcome to close this issue now. (Unless you need it for tracking documentation updates, as discussed above).

yes - we can leave it open for the documentation update

**Comment by JohnRusk** [comment]
@wojtek-t  I'm looking at that code you mentioned above.  And I noticed this:

```
 TODO: Make check() function more sophisticated, in particular
// allow it to behave as "waitWithTimeout".
func (r *ready) check() bool ...
```
Which is called from [here](https://github.com/kubernetes/kubernetes/blob/8ac5d4d6a92d59bba70844fbd6e5de2383a08c96/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L695)

**Will that TODO be addressed as part of the 1.22 work you mentioned?**  If not.... could there be a problem as follows: when multilpe list requests all arrive at the same time, and the cache is empty, it looks like they'll all end up going to etcd.  That looks like it could create load issues on freshly-started API servers (which is the problem that I'm currently looking at on some clusters).

Naturally, one solution in 1.22 could be to set very low limits of concurrent List operations - so then it would be OK if all the requests hit etcd, because there won't be very many of them in flight at the same time.  The problem with that is that the same low limits will apply later, after the cache is full, and applying low limits with a full cache would presumably be bad for scalability.

**Comment by wojtek-t** [comment]
We're not planning to touch this code at least in 1.22.

That said - it's actually not that bad as you wrote. Note that whole rate-limitting is based on in-flight limits. So if the requests takes less time (as it should when served from watchcache) it kind-of automatically gives us ability to be able to process more requests in a unit of time. We may want to address that TODO eventually, but that's not a current priority.

**Comment by JohnRusk** [comment]
Ah, yes, thanks for explaining.  Yes, it's not as bad as I initially thought.  It still worries me, but slightly less now :-)

**Comment by fedebongio** [comment]
Thank you Wojciech for all your comments and knowledge!
/cc @yliaog 
/triage accepted

**Comment by JohnRusk** [comment]
@wojtek-t   You mentioned rate-limiting based being based on in-flight limits, above.  I've been testing on large list sizes (e.g. 40,000 items) and I'm seeing it take almost a minute to serve the list (from cache).  Is that what you'd expect?  (Wondering if that's normal, or maybe something unexpected is interfereing with my test).

**Comment by JohnRusk** [comment]
Just for completeness @wojtek-t: I'm also seeing non-trivial RAM spikes (e.g. around 10GB) when doing unchunked listing from cache at fairly low concurrency levels. E.g. only 6 concurrent list operations, with 40,000 secrets in the list. Presumably the spikes would be even bigger if the lists were bigger.  I'd love it if enhanced priority and fairness could smooth out such spikes - but (based on my intuition) I'm not sure it will, given that the behaviour appears with only a small number of concurrent list operations.

**Comment by JohnRusk** [comment]
@wojtek-t you wrote:

>we don't support chunking from watchcache and adding it will be a very large piece of work (though it's periodically being discussed)

I'm finding that the lack of watch cache chunking is coming up more and more in discussions that I have with colleagues about load management.  

So I have a question/suggestion - what makes the chunking from watch cache hard?  Is the difficulty in _incrementally querying the watch cache_ (one page at a time)?  If so, why not _identify_ all the objects to be returned in the first call.  I.e. same logic as right now, but instead of returning them all on the first call, save a list of pointers to them.  Then return just the first `limit` number of them, and a continue token that identifies the list and the current index in it.   Subsequent calls just look up the right spot in the list and return another `limit` number of objects.  

I have no idea if that suggestion is useful, or if (as is likely) its already been considered.  But I figured I'd share it anyway because issues with the current behaviour keep coming up a _lot_ in conversations with colleagues about load management.

**Comment by JohnRusk** [comment]
Related issue https://github.com/kubernetes/kubernetes/issues/82655

**Comment by wojtek-t** [comment]
> If so, why not identify all the objects to be returned in the first call. I.e. same logic as right now, but instead of returning them all on the first call, save a list of pointers to them.

We were discussing that in the past too. And at the high-level it seems to work but:
- that saved list is kept in-memory only - so what if a client for continuation reaches a different kube-apiserver?
- the cache storing those "precomputed" lists would obviously have to be TTL-based (or somewhat like that). Configuring it correctly so that it won't cause significant RAM increase is definitely not obvious
- if I have gazillions of LISTs to serve on high-churn resource (e.g. pods) then storing a lot of them in memory will not fully solve our problem - it will to significant extent move the problem around

As a result, what we're exploring now (which I'm personally pretty supportvie for) is something more like kubernetes/enhancements#3142

This isn't a generic solution but this would allow us to
1) migrate our internal clients (informers in particular) to something that we know we can support
2) by the above, open a door for significantly throttling the non-paginated list requests via P&F

**Comment by JohnRusk** [comment]
Thanks for the detailed reply @wojtek-t . The issues you point out make sense.

I'm left with a couple of concerns about the current direction, which I'd like to share with you.  I'm not saying they're show-stoppers, but they do seem like the might be relevant.

My first concern is about the advice that would then be given to developers (e.g. of 3rd-party things that will run in K8s). If I understand correctly, the advice to devs would become:
1. If you need a "list", your first preference should be to use an Informer because it will do streaming for you.
2. If you can't or don't use an informer
    a. Lists that hit the API server cache may be strongly throttled.
    b. Paginated lists that force querying from etcd will be less throttled _but you shouldn't use these because they put too much load on etcd_.
    
I'm a little concerned about the conflict between 2a and 2b.  Devs don't want to be throttled, but we don't want them to hit etcd.  

My second concern is that even a very small number of unpaginated list queries can cause a non-trivial RAM spike if the lists have 10s of thousands of elements.  How sure are we that we can get decent control of RAM spikes by throttling non-paginated requests with P&F?
