### ISSUE TITLE
JSON logging format should not be registered by default

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#102632]
Follow up from https://github.com/kubernetes/klog/issues/211

Currently importing `k8s.io/component-base/logs` results both `text` and `json` logging format available by default. As Json format is not yet GAed, it is undesired to force it on component authors that use the library. Instead it should be optional. This can be achieved by having it's registration moved to submodule.

TODO:
* Create a new module `./staging/src/k8s.io/component-base/logs/json/register`
* Add import `_ "k8s.io/component-base/logs/json/register"` to system components
  * [kubelet](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/kubelet.go)
  * [kube-scheduler](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/scheduler.go)
  * [kube-apiserver](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/apiserver.go)
  * [kube-controller-manager](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/controller-manager.go)
* Remove JSON register call https://github.com/kubernetes/kubernetes/blob/9d27400fe20867c5f811f21a2571974887cf3d1e/staging/src/k8s.io/component-base/logs/config.go#L42 
  
As this change requires high level approvals in cmd directories it's recommended to do the change in multiple PRs, create module first should allow split changes to system components to separate PRs and merge them independently. 

/wg structured-logging
/cc @kubernetes/wg-structured-logging-members

**Comment by mengjiao-liu** [comment]
I want to try to work here. 
/assign

**Comment by lavalamp** [comment]
Why can you not remove the registration line prior to importing the new packages?

**Comment by serathius** [comment]
We have e2e periodic tests that would start failing if JSON is not available.

**Comment by serathius** [comment]
Looks like work here is done.
Thanks for the help!
