### ISSUE TITLE
Controller-manager fails to successfully start when converting a cluster from dual-stack to single-stack

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [kubernetes/kubernetes#102698]
#### What happened:
Tried to downgrade a running dual stack cluster to single stack by modifying service-cluster-ip-range and cluster-cidr parameters to have only one CIDR (both parameters had ipv4,ipv6 CIDR ,changed it to have only ipv4 CIDR).
After making this change controller-manager fails to start successfully. The below error is seen in the controller manager logs:

`controllermanager.go:226] error starting controllers: node:ccd-focal-clus2-1 has an allocated cidr: 2001:db8:1234:5678:8:3::/120 at index:1 that does not exist in cluster cidrs configuration`

node.Spec.PodCIDRs :

```
spec:
    podCIDR: 10.244.2.0/28
    podCIDRs:
    - 10.244.2.0/28
    - 2001:db8:1234:5678:8:3::/120
```

#### What you expected to happen:
Successful downgrade from dual to single stack cluster

#### How to reproduce it (as minimally and precisely as possible):
In a running dual stack cluster edit the parameters "service-cluster-ip-range" and "cluster-cidr" in kube-controller-manager.yaml and kube-apiserver.yaml to have only one CIDR(keep the primary cidr, delete the secondary).
Also, delete parameters "node-cidr-mask-size-ipv4" and "node-cidr-mask-size-ipv6" if present.

#### Anything else we need to know?:
kube-controller-manager logs:
[4_downgrade_dualstack.txt](https://github.com/kubernetes/kubernetes/files/6618336/4_downgrade_dualstack.txt)

#### Environment:
- Kubernetes version (use `kubectl version`): v1.22.0-alpha.2
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`):  "Ubuntu 20.04.2 LTS"
- Kernel (e.g. `uname -a`): Linux ccd-focal-clus2-1 5.4.0-66-generic
- Install tools:
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by VivekThrivikraman-est** [comment]
@aojea

**Comment by aojea** [comment]
Great catch, 
/sig network
/triage accepted
@thockin @khenidak @danwinship  another one  for converting from dual to single.
https://github.com/kubernetes/kubernetes/pull/101914#issuecomment-850727366

This hopefully will be addressed by https://github.com/kubernetes/enhancements/issues/2593

**Comment by khenidak** [comment]
@aojea  I don't think kubernetes/enhancements#2593 should fix this, specially when should? limit the scope to `additive` only.

This behavior is very similar to changing service cidrs. The cluster can not resolve such as a change specially for an immutable field `node.spec.cidrs`

For the sake of discussion the same behavior will exist if you have a single stack cluster with `pod-cidrs=["10.0.0.0/16"] ` and you change it to `pod-cidrs=["172.16.0.0/16"]` - The controller will fail to start (and it should fail to start).

The only way out of this is to coordinate deletion all node objects that has cidrs carved from old-cidrs and restart their corresponding nodes. New node objects will be created with correct cidrs and whatever pods lived there will start with podIPs allocated from the correct cidr.

**Comment by aojea** [comment]
is it better to break an entire cluster or have a cluster running with a misconfigured node?

**Comment by khenidak** [comment]
Yes, this is how it was and i think this is the correct way.

The behavior of one node misconfigured is indeterministic from user pov (some traffic will work, some won't etc). Halting CM and asking user to manually fix the misconfiguration IMO is the best the approach.

**Comment by aojea** [comment]
> Yes, this is how it was and i think this is the correct way.

I disagree this is the correct way just because nodeipam is a functional feature, not required, and this breaks all the other controller that are required.

**Comment by aojea** [comment]
> maybe we can reach a better agreement (anything is better than stoping CM all together. But i am unable to find a better solution to avoid indeterministic behavior).

I'm not saying to modify current behavior, it is what it is :shrug: , but  the new KEP will replace and hopefully deprecate current nodeipam and we can revisit in more detail this problem during the reviews of the new implementation
/cc @rahulkjoshi

**Comment by rahulkjoshi** [comment]
/remove-lifecycle rotten

The PR referenced above will make this story better: kubernetes/enhancements#2593
Target is 1.24 for code merge
