### ISSUE TITLE
Configuring the kube-apiserver advertise address in kubeadm init has incomplete consequences

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102693]
#### What happened:
I want to create a kube cluster in a set of VirtualBox VMs.  Unless otherwise directed, `kubeadm init` picks the same IP address for each VM, `10.0.2.15` (this is the IP address of the network interface that appears in the default route, because the first network interface is what VB calls a "NAT" type of adapter, which I chose because that is the easiest way to get access to the outside world).  The kubeadm instructions say that I can tell `kubeadm init` to use a different IP address for the kube-apiserver to advertise.  However, when I do that, I find that:

1. the generated certificate for the kube-apiserver does not include the configured address in the Subject Alternative Name list, and
2. the `kubeadm join` command printed at the end of `kubeadm init` uses the deault address.

#### What you expected to happen:
I expected `kubeadm init` to understand the relevant implications of setting the kube-apiserver's advertise address.

#### How to reproduce it (as minimally and precisely as possible):
I think the above is pretty direct.

#### Anything else we need to know?:
```
mspreitz@init1:~$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:17:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

mspreitz@init1:~$ ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:58:21:5f brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic enp0s3
       valid_lft 83615sec preferred_lft 83615sec
    inet6 fe80::a00:27ff:fe58:215f/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 08:00:27:fa:cf:4d brd ff:ff:ff:ff:ff:ff
    inet 192.168.56.110/24 brd 192.168.56.255 scope global dynamic enp0s8
       valid_lft 304sec preferred_lft 304sec
    inet6 fe80::a00:27ff:fefa:cf4d/64 scope link 
       valid_lft forever preferred_lft forever
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:8d:4c:99:39 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
```

#### Environment:
- Kubernetes version (use `kubectl version`): `GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192"`
- Cloud provider or hardware configuration: VirtualBox VM
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux init1 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): did not get that far
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-cluster-lifecycle

**Comment by neolit123** [comment]
> I want to create a kube cluster in a set of VirtualBox VMs. Unless otherwise directed, kubeadm init picks the same IP address for each VM, 10.0.2.15 (this is the IP address of the network interface that appears in the default route, because the first network interface is what VB calls a "NAT" type of adapter, which I chose because that is the easiest way to get access to the outside world).

by choosing this setup you complicate your k8s deployment as all the k8s components, including kubelet, kubeadm, kube-apiserver, etc IIRC would pick the IP 10.0.2.15. so now you must be explicit about the IPs you want for all components.
none of the components allow you to pick an interface.

kubeadm and apiserver use [this](https://github.com/kubernetes/kubernetes/blob/89db31aadefb5207dbf84e2403495d0da31c7c35/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go#L467). kubelet uses something similar and also undocumented, so you might have to pass --node-ip.

> the generated certificate for the kube-apiserver does not include the configured address in the Subject Alternative Name list, 

i cannot confirm that:

```
# that is not a valid address but just for testing
kubeadm init ... --advertise-address 192.168.0.1

# ctrl+c ...

# the address is in the cert SAN
openssl x509 -in /etc/kubernetes/pki/apiserver.crt -text -noout
...
X509v3 Subject Alternative Name: 
                DNS:controlplane, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, IP Address:10.96.0.1, IP Address:192.168.0.1

```

> the kubeadm join command printed at the end of kubeadm init uses the deault address.

join prints the control-plane-endpoint, not the advertise-address.

https://stackoverflow.com/questions/65995056/kubernetes-api-server-bind-address-vs-advertise-address

we want joining node clients to connect to the secure port, which the bind addresses of IP server instances expose., not the advertise addresses. we consider the control plane endpoint to be the endpoint where all worker nodes should connect to.
if no control-plane-endpoint is specified it would default to the bind-adress:port.

/remove-kind bug
/kind support

**Comment by neolit123** [comment]
how are you passing your advertise address to kubeadm init - is it via InitConfiguration or flag?

according to the code, the control plane endpoint (if not specified) should get defaulted to the the init configuration advertise address, and that get's defaulted to the default public IP.

i'm trying to check if there is a bug between flags / config and drift between bind/advertise addresses...

**Comment by MikeSpreitzer** [comment]
If I recall correctly, I used the following config file for `kubeadm init`.
```
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  extraArgs:
    advertise-address: 192.168.56.101
```

**Comment by neolit123** [comment]
Kubeadm does not parse "extra args" as a something to add to SANs or join
command. --advertise-address or the init/join configuration advertise
address should be used instead.

I think our example for advertise address here should be removed.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#apiserver-flags

Lets move the discussion to your k/website ticket about improvements.

Also PRs are welcome.

/close
