### ISSUE TITLE
kubelet error launching pods, state error on running containers

### ISSUE THREAD

**Issue by j4m3s-s** [kubernetes/kubernetes#102659]
#### What happened:
Launching a pod failed with 
```
RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "it-sync-cron-1623075300-hhzbh": operation timeout: context deadline exceeded
Jun 07 14:21:29 ip-10-241-29-119 kubelet[23154]: E0607 14:21:29.850146   23154 kuberuntime_sandbox.go:68] CreatePodSandbox for pod "it-sync-cron-1623075300-hhzbh_itnt-world(1be277c9-5e3e-4641-b77b-cc7c370c6bf1)" failed: rpc error: code = Unknown desc = failed to create a sandbox for pod "it-sync-cron-1623075300-hhzbh": operation timeout: context deadline exceeded
```
#### What you expected to happen:
To create a container successfully.
#### How to reproduce it (as minimally and precisely as possible):
unfortunately it's not very deterministic, I haven't been able to reproduce it. But we experience pretty frequently (multiple times a day).
#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-rc.0", GitCommit:"e338cf2c6d297aa603b50ad3a301f761b4173aa6", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-eks-ad4801", GitCommit:"ad4801fd44fe0f125c8d13f1b1d4827e8884476d", GitTreeState:"clean", BuildDate:"2020-10-20T23:27:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
AWS m5.xlarge 
According to documentation : 

Instance Size | vCPU | Memory (GiB) | Instance Storage (GiB) | Network Bandwidth (Gbps) | EBS Bandwidth (Mbps)
m5.xlarge       | 4        | 16                    | EBS-Only                      | Up to 10                              | Up to 4,750

- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel (e.g. `uname -a`):
Linux ip-10-241-29-119 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

When this bug happens, a lot of weird things also happen 
- running `docker run -it busybox sh` hangs
- running `timedatectl` also hangs
The volumes attached to the node : 
```
NAME          MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
nvme0n1       259:0    0  20G  0 disk
├─nvme0n1p1   259:1    0  20G  0 part /
└─nvme0n1p128 259:2    0   1M  0 part
nvme1n1       259:3    0  50G  0 disk /var/lib/kubelet/pods/199bcf4c-b71a-4d30-98a9-aada8d6e9111/volumes/kubernetes.io~aws-ebs/pvc-7b88b2a8-ab21-11ea-b238-06be
```

Additionnal logs : 
```
Jun 07 14:28:51 ip-10-241-29-119 kubelet[23154]: E0607 14:28:51.778384   23154 remote_runtime.go:351] ExecSync 787941d2753f6a4cda30ba2200fc7f0087cc3515c2acba2c0e1be202c4d2e77d '/app/grpc-health-probe -addr=:50051' from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Jun 07 14:28:51 ip-10-241-29-119 kubelet[23154]: W0607 14:28:51.778442   23154 prober.go:108] No ref for container "docker://787941d2753f6a4cda30ba2200fc7f0087cc3515c2acba2c0e1be202c4d2e77d" (aws-node-hbc5s_kube-system(fcfff8b4-13a5-4a33-8f73-19c6122b88e1):aws-node)
Jun 07 14:28:52 ip-10-241-29-119 kubelet[23154]: E0607 14:28:52.242336   23154 remote_runtime.go:351] ExecSync 787941d2753f6a4cda30ba2200fc7f0087cc3515c2acba2c0e1be202c4d2e77d '/app/grpc-health-probe -addr=:50051' from runtime service failed: rpc error: code = Unknown desc = operation timeout: context deadline exceeded
Jun 07 14:28:52 ip-10-241-29-119 kubelet[23154]: W0607 14:28:52.242386   23154 prober.go:108] No ref for container "docker://787941d2753f6a4cda30ba2200fc7f0087cc3515c2acba2c0e1be202c4d2e77d" (aws-node-hbc5s_kube-system(fcfff8b4-13a5-4a33-8f73-19c6122b88e1):aws-node)
```

CNI : 
```
{"level":"info","ts":"2021-06-07T14:30:18.495Z","caller":"/usr/local/go/src/runtime/proc.go:203","msg":"CNI Plugin version: v1.6.3 ..."}
AWS CNI v1.6.3
```

containerd : 
```
containerd github.com/containerd/containerd 1.4.1 c623d1b36f09f8ef6536a057bd658b3aa8632828
```

Docker : 
```
Docker version 19.03.6-ce, build 369ce74
```

Runc : 
```
runc version 1.0.0-rc92
commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
spec: 1.0.2-dev
```

if you need any more information I'll be happy to help.
If I need to report this to some other projects please tell me, I'm not sure where the bug lies, so ...

**Comment by HongjiangHuang** [comment]
Hi ~ bro @j4m3s-s
This seems to be caused by [docker](https://github.com/moby/moby/issues/40817). 

Reference: 
https://github.com/kubernetes/kubernetes/blob/v1.16.15/pkg/kubelet/dockershim/libdocker/kube_docker_client.go#L146

**Comment by ehashman** [comment]
/remove-kind support

A timeout on pod sandbox creation could possibly be a bug, but there isn't enough information here to be certain.

Can you provide full kubelet/container runtime logs and the pod specification? This is not possible to reproduce or debug in its current state.

/triage more-information

**Comment by j4m3s-s** [comment]
I currently don't have logs related to that, so I'll follow up with more information soon (probably beginning of next week). Thanks for the help !

**Comment by stayhungry001** [comment]
I have the same issue, too. As I can see, there are several containers with exit status. This issue resolved when I delete the exited containers.

**Comment by j4m3s-s** [comment]
IIRC, when I deleted the containers it hanged and didn't really work. (Although you should take that with a grain of salt, since I can't reproduce the issue at the moment).

We have updated our cluster to 1.17, and the behavior doesn't seem to appear or it appears less often. So unfortunately I'm unable to provide any logs to help debug it further :/.

**Comment by j4m3s-s** [comment]
I haven't encountered the bug since I updated, closing.
