### ISSUE TITLE
More concurrency bugs in priority-and-fairness_test.go

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102648]
#### What happened:
In reviewing a fix to #102016, I noticed other violations of the restriction in https://golang.org/pkg/testing/#T that
> A test ends when its Test function returns or calls any of the methods FailNow, Fatal, Fatalf, SkipNow, Skip, or Skipf. Those methods, as well as the Parallel method, must be called only from the goroutine running the Test function.

Obvious examples include:
- https://github.com/kubernetes/apiserver/blob/71dfa70b215bfa7c1d57083d251d5a49ec4fc9e8/pkg/server/filters/priority-and-fairness_test.go#L332
- https://github.com/kubernetes/apiserver/blob/71dfa70b215bfa7c1d57083d251d5a49ec4fc9e8/pkg/server/filters/priority-and-fairness_test.go#L456
- https://github.com/kubernetes/apiserver/blob/71dfa70b215bfa7c1d57083d251d5a49ec4fc9e8/pkg/server/filters/priority-and-fairness_test.go#L469
- https://github.com/kubernetes/apiserver/blob/71dfa70b215bfa7c1d57083d251d5a49ec4fc9e8/pkg/server/filters/priority-and-fairness_test.go#L907

A less obvious case is the test servers created.  If I understand correctly, they execute their handler in a forked goroutine, not the client's goroutine.  The given handlers call `expectMatchingAPFHeaders(t, ...)`, which can call `t.Fatal`.

#### What you expected to happen:
I expected to find no other violations.

#### Environment:
- Kubernetes version (use `kubectl version`): latest published to k8s.io/apiserver
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
/assign @tkashem 
@wojtek-t 
@lavalamp 
@deads2k

**Comment by cici37** [comment]
@tkashem Hi, Wondering if you are still working on this one? Thank you

**Comment by tkashem** [comment]
@cici37  yes, I just put out a fix for it, thanks!
