### ISSUE TITLE
unit tests of the ./pkg/volume are failing 

### ISSUE THREAD

**Issue by gerassimos** [kubernetes/kubernetes#102600]
On a clean Ubuntu dev environment I get the following error when I executed the `make test WHAT=./pkg/volume`

```
+++ [0604 10:05:38] Running tests without code coverage
--- FAIL: TestGetMetricsBlock (0.11s)
  metrics_block_test.go:96: Unexpected error when calling GetMetrics: unable to open device "/dev/cdrom": open /dev/cdrom: no medium found
```
  
I think that the tests should not fail and should handle the case where there is a cdrom device but there is not an actual CD media inserted.

I got feedback from @serathius and this is also happing on his environment with the following error:

```
--- FAIL: TestGetMetricsBlock (0.00s)
    metrics_block_test.go:92: Unexpected error when calling GetMetrics: unable to open device "/dev/dm-0": open /dev/dm-0: permission denied
```
    
I am coping also his comment from the slack that may help: 
_Looks like it's not a problem with cdrom, but some dependence on device. I don't think it should try try to access at all._
    
This is my very first issue, I am new to this, any help is welcome.
I am really looking forward to starting coding but I am overwhelmed with the amount of information that I need to digest.

/cc serathius
/sig instrumentation

**Comment by serathius** [comment]
@gerassimos Fact that this tests fails only locally and not on CI means that there will not be a lot of interest in fixing it. Feel free to prepare a fix for it. Please let me know if you need help with setting up development workflow.

**Comment by BenTheElder** [comment]
@serathius this is probably related to https://github.com/kubernetes/kubernetes/issues/99881.
Because other tests have this same issue, CI is still running unit tests as UID=0. I have work to remove that but I wasn't sure about another storage test.

**Comment by gnufied** [comment]
The block metrics tests were introduced in - https://github.com/kubernetes/kubernetes/pull/101587 

I am fine with deleting the test in question. We have e2e that captures this more accurately and unit test seems kinda less useful anyways.

**Comment by gnufied** [comment]
opened https://github.com/kubernetes/kubernetes/pull/102608 to remove the test. I think we should be fine without it.

**Comment by BenTheElder** [comment]
Thank you!

Also just for the record noting that I can of course locally reproduce this (with `/dev/dm-0` in my case).

**Comment by BenTheElder** [comment]
thanks all.

similar issues are tracked in #102607, #99881
