### ISSUE TITLE
Config file equivalents for --log-file --one-output

### ISSUE THREAD

**Issue by brsolomon-deloitte** [kubernetes/kubernetes#102699]
```
kubeadm init --config /path/to/custom.yaml --log-file out.log --one-output <other-args>
```

will error with

```
can not mix '--config' with arguments [log-file one-output]
```

however it is not apparent in the documentation what the equivalent key entries for these two flags are or if there are equivalents at all.

- Do corresponding key/value pairs exist in a custom config file?
- If so, what are they?

#### Environment:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by neolit123** [comment]
duplicate
https://github.com/kubernetes/kubeadm/issues/2455

the logger (klog) flags are confusing for component consumers.
we could allow it, but apparently it would introduce a breaking change.

in the meantime you can just do `kubeadm ... | tee`

https://github.com/kubernetes/kubeadm/issues/2455#issuecomment-824498797

/close
