### ISSUE TITLE
misleading failures info when e2e storage testcase is running locally

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#102680]
#### What happened:

If the provide is `local`, run the below storage testcase, 

```
/usr/bin/e2e.test -ginkgo.focus="\[sig-storage\] Dynamic Provisioning DynamicProvisioner \[Slow\] should provision storage with different parameters"  -provider=local
```

Hit below exception, 
```
[It] should provision storage with different parameters
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:152
Jun  4 15:12:39.715: FAIL: Expected
    <int>: 0
not to equal
    <int>: 0

Full Stack Trace
k8s.io/kubernetes/test/e2e/storage.getRandomClusterZone(0x6f5edf8, 0x4002292f20, 0x664dec2, 0x4)
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:1065 +0x9c
k8s.io/kubernetes/test/e2e/storage.glob..func30.2.1()
        /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_provisioning.go:165 +0xb0
k8s.io/kubernetes/test/e2e.RunE2ETests(0x4000303380)
        _output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:131 +0x370
k8s.io/kubernetes/test/e2e.TestE2E(0x4000303380)
        _output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:144 +0x28
testing.tRunner(0x4000303380, 0x686c228)
        /usr/local/go/src/testing/testing.go:1193 +0xdc
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1238 +0x244
[AfterEach] [sig-storage] Dynamic Provisioning
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
```

At first glance, it looks like the return value is not correct, but looking into how the testcases was wrote, the root case should be that the testcase below doesn't support the `local` provide, 

- SSD PD on GCE/GKE
- gp2 EBS on AWS

We should provide the correct error message which will be useful for trouble shooting instead.

#### Environment:
- Kubernetes version (use `kubectl version`):   All
- Cloud provider or hardware configuration: local
- OS (e.g: `cat /etc/os-release`):  All
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
NOTE: the "local" provider is specifically hack/local-up-cluster.sh. any other cluster that is not one of "gce" etc. should use the default provider / "skeleton" provider (I know the naming is bad, but it's sort of an API now)
