### ISSUE TITLE
kube-controller-manager 1.21.1 crashes with nil pointer (azure_standard.go)

### ISSUE THREAD

**Issue by Michael-Sinz** [kubernetes/kubernetes#102660]
#### What happened:
Trying to run kubernetes 1.21.1 clusters and the kube-controller-manager crashes quite often with a panic due to a nil pointer.  (Consistently crashing, actually)

```
goroutine 2630 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x40c4940, 0x72b9590)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x40c4940, 0x72b9590)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).serviceOwnsFrontendIP(0xc00072b800, 0x0, 0xc003f1a8c0, 0xc003f28c30, 0xc003f28a40, 0xc003f28a50, 0x0, 0xc003f28c40, 0xc002255860, 0xa9, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_standard.go:370 +0x2a2
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancerStatus(0xc00072b800, 0xc002255860, 0xc003e97130, 0x0, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:511 +0x3a5
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).getServiceLoadBalancer(0xc00072b800, 0xc002255860, 0x7fff9602d3d8, 0x6, 0x0, 0x0, 0x0, 0xc001ae1c00, 0x6a8411, 0x72f58c0, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:383 +0x3e5
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).shouldUpdateLoadBalancer(...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:1959
k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure.(*Cloud).UpdateLoadBalancer(0xc00072b800, 0x506b0c8, 0xc0001a2008, 0x7fff9602d3d8, 0x6, 0xc002255860, 0xc002f92680, 0x3, 0x4, 0x3, ...)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/azure_loadbalancer.go:229 +0x7d
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).lockedUpdateLoadBalancerHosts(0xc0010b94a0, 0xc002255860, 0xc002f92680, 0x3, 0x4, 0x0, 0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:795 +0x2a2
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).nodeSyncService(0xc0010b94a0, 0xc002255860, 0xc00236a138)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:753 +0x2b6
k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service.(*Controller).updateLoadBalancerHosts.func1(0x0)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/cloud-provider/controllers/service/controller.go:770 +0x74
k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil.func1(0xc00262b6c0, 0xc00236a0e0, 0xc00262b6b0, 0x1, 0xc000a7d258, 0xc0029b2880)
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:90 +0x90
created by k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue.ParallelizeUntil
	/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/util/workqueue/parallelizer.go:76 +0x253
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x32bb0c2]
```

#### What you expected to happen:
Don't Panic  (👍)

I am not yet sure where this traces back to but the line in question is:
[`if strings.EqualFold(*pip.ID, *fip.PublicIPAddress.ID) {`](https://github.com/kubernetes/kubernetes/blob/v1.21.1/staging/src/k8s.io/legacy-cloud-providers/azure/azure_standard.go#L370)
and my guess is that the problem is with the fip side since the pip.ID was checked for nil just in the line above but nothing validated fip.PublicIPAddress.ID is valid - but I have not traced back all of the code to validate if could have an invalid pointer. 

#### How to reproduce it (as minimally and precisely as possible):
Create a kubernetes cluster with 1.21.1 of kubernetes using aks-engine and our skyman infrastructure.  This starts happening shortly after starting the cluster and starting to load services.  I have not (yet) narrowed it down to the smallest reproducing case as it takes some time to get to that point.

We do have a service the a pre-defined public IP address that we deploy.  (Basically a static IP address)

My further guess is that this is related to the fact that I have a static IP address allocated to the service but somehow it is not showing up as a valid IP address (kubectl get services shows that is it <pending> but getting the spec shows that it has the public IP address)

This is the log of the kube-controller-manager (well, one of the crashes - they happen over and over again)
[crash.txt](https://github.com/kubernetes/kubernetes/files/6609992/crash.txt)

#### Anything else we need to know?:
The cluster is limping around but not at all usable.

The same set of charts we deployed to this minimal test cluster work in prior kubernetes (for sure, 1.18 as it is in production)

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration: azure
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): Linux k8s-master-58735726-0 5.4.0-1048-azure #50~18.04.1-Ubuntu SMP Fri May 14 15:30:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Others: aks-engine 0.63.0

**Comment by Michael-Sinz** [comment]
Note that this is also now shown in 1.20.7

**Comment by Michael-Sinz** [comment]
There is this PR that may be related:  https://github.com/kubernetes-sigs/cloud-provider-azure/pull/615/files

**Comment by BenTheElder** [comment]
that PR recently had the same thing go into this repo https://github.com/kubernetes/kubernetes/pull/101739

it's being cherry-picked to 1.21 here https://github.com/kubernetes/kubernetes/pull/101885

/assign @nilo19 @feiskyer

**Comment by feiskyer** [comment]
yes, the fix is being cherry-picked to 1.20 and 1.21 by https://github.com/kubernetes/kubernetes/pull/101886 and https://github.com/kubernetes/kubernetes/pull/101885, and they would be part of 1.20.8 and 1.21.2.

**Comment by Michael-Sinz** [comment]
> yes, the fix is being cherry-picked to 1.20 and 1.21 by #101886 and #101885, and they would be part of 1.20.8 and 1.21.2.

We are completely blocked on moving to k8s 1.20 or 1.21 until this is addressed.  How long before this PR gets pulled it.  I see it has been sitting there for almost a month.  Is there a way we can make sure this gets done soon?

**Comment by feiskyer** [comment]
The next Kubernetes release would happen on 06-16 (refer the scheduler here: https://github.com/kubernetes/website/blob/master/content/en/releases/patch-releases.md#upcoming-monthly-releases).

**Comment by ialidzhikov** [comment]
@Michael-Sinz , can this issue be closed now?

**Comment by Michael-Sinz** [comment]
I have not yet had a chance to test a k8s with the fix yet.  (Various reasons, including being rather busy)

**Comment by ialidzhikov** [comment]
> I have not yet had a chance to test a k8s with the fix yet. (Various reasons, including being rather busy)

Okay. v1.21.2 was released yesterday - https://github.com/kubernetes/kubernetes/releases/tag/v1.21.2. Let us know if it is fixing the issue for you.

**Comment by feiskyer** [comment]
v1.21.2 released. Let me know if you still have issues.
