### ISSUE TITLE
client-go memory leak

### ISSUE THREAD

**Issue by xiaoanyunfei** [kubernetes/kubernetes#102718]
#### What happened:

We use `client-go informerFactory` to handle some pod information,

>informerFactory.Core().V1().Pods().Informer().AddEventHandler(    
cache.ResourceEventHandlerFuncs{
      AddFunc:    addPodToCache,
      UpdateFunc: updatePodInCache,
      DeleteFunc: deletePodFromCache,
    })

> cache := make(map[string]*v1.Pod)
addPodToCache -> AddPod(pod *v1.Pod)  {
key, _ := framework.GetPodKey(pod)
cache[key]=pod
}

> deletePodFromCache->RemovePod(pod *v1.Pod) error{
key, _ := framework.GetPodKey(pod)
delete(cache, key)
}

But we came across memory leak problem recently.

I add some log, and finally find the reason.

Our k8s version is 1.17 with more than 5500 node, but the  default-watch-cache-size of `kube-apiserver` is 100 which is too small for our cluster. 
(The last k8s already use `dynamic size watch-cache` #https://github.com/kubernetes/kubernetes/issues/90058)

[Reflector.ListAndWatch](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L254)

`Reflector List `function costs more than 35 second, and then `Reflector` use the last resourceVersion of `List` to call `Watch` function. `Reflector Watch `  get an  error `too old resource version: 6214379869 (6214383056)` because the last resourceVersion of `List` has been expired in default-watch-cache-size of `kube-apiserver`

`Reflect.Run` will keep the cycle `List` -> `Watch` - `get too old resource version error`

Then a memory leak occurred.  We use `cache` map to store pod information, and the `cache` will contain pods in different `PodList`. This will prevent golang from gc the whole `PodList`

The code causing memory leak is `meta.EachListItem`
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/meta/help.go#L115

Replacing `found = append(found, item)` with `found = append(found, item.DeepCopyObject())` can fix the problem.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L453

 

#### What you expected to happen:
Calling `DeepCopyObject` has some memory overhead,
I wonder if there is a better solution for this.

#### How to reproduce it (as minimally and precisely as possible):

```
import (
        "fmt"
        goruntime "runtime"
        "time"

        v1 "k8s.io/api/core/v1"
        "k8s.io/apimachinery/pkg/api/meta"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
        "k8s.io/apimachinery/pkg/runtime"
)

func main() {
        leak()
}

func unleak() {
        store := make(map[string]*v1.Pod)
        var index int
        for {
                plist := generatePod(index)
                for _, pod := range plist.Items {
                        pod := pod
                        store[pod.Name] = &pod
                }
                time.Sleep(time.Second * 2)
                index++
                goruntime.GC()
                fmt.Println("==unleak==", index, len(store))
        }
}

func leak() {
        store := make(map[string]*v1.Pod)
        var index int
        var items []runtime.Object
        for {
                items = items[:0]
                plist := generatePod(index)
                meta.EachListItem(plist, func(obj runtime.Object) error {
                        items = append(items, obj)
                        return nil
                })
                for _, item := range items {
                        pod := item.(*v1.Pod)
                        store[pod.Name] = pod
                }
                time.Sleep(time.Second * 2)
                index++
                goruntime.GC()
                fmt.Println("==leak==", index, len(store))
        }
}

func generatePod(num int) *v1.PodList {
        var plist v1.PodList
        for i := 0; i < 100000-num; i++ {
                pod := v1.Pod{
                        ObjectMeta: metav1.ObjectMeta{
                                Name: fmt.Sprintf("pod-%d", i),
                        },
                }
                plist.Items = append(plist.Items, pod)
        }
        return &plist
}
```

![leak](https://user-images.githubusercontent.com/6782068/121289931-5f49c400-c918-11eb-9634-995eae66e275.png)

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sxllwx** [comment]
In fact, Unleak's code itself has a bug

**Comment by novahe** [comment]
I think this is the same problem issue: #102564 pr: #102565

**Comment by novahe** [comment]
I format code used for reproduction
```go
package main

import (
	"fmt"
	goruntime "runtime"
	"time"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/meta"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func main() {
	leak()
}

func unleak() {
	store := make(map[string]*v1.Pod)
	var index int
	for {
		plist := generatePod(index)
		for _, pod := range plist.Items {
			store[pod.Name] = &pod
		}
		time.Sleep(time.Second * 2)
		index++
		goruntime.GC()
		fmt.Println("==unleak==", index, len(store))
	}
}

func leak() {
	store := make(map[string]*v1.Pod)
	var index int
	var items []runtime.Object
	for {
		items = items[:0]
		plist := generatePod(index)
		meta.EachListItem(plist, func(obj runtime.Object) error {
			items = append(items, obj)
			return nil
		})
		for _, item := range items {
			pod := item.(*v1.Pod)
			store[pod.Name] = pod
		}
		time.Sleep(time.Second * 2)
		index++
		goruntime.GC()
		fmt.Println("==leak==", index, len(store))
	}
}

func generatePod(num int) *v1.PodList {
	var plist v1.PodList
	for i := 0; i < 100000-num; i++ {
		pod := v1.Pod{
			ObjectMeta: metav1.ObjectMeta{
				Name: fmt.Sprintf("pod-%d", i),
			},
		}
		plist.Items = append(plist.Items, pod)
	}
	return &plist
}

```

**Comment by 249043822** [comment]
Cc @jpbetz @wojtek-t

**Comment by sxllwx** [comment]
FYI, I think this is caused by Golang's GC, not `meta.EachListItem`. If the num parameter of the `generatePod` function is removed, 100,000 simulated Pods are generated each time, and the RES value is very stable.

**Comment by sxllwx** [comment]
> FYI, I think this is caused by Golang's GC, not `meta.EachListItem`. If the num parameter of the `generatePod` function is removed, 100,000 simulated Pods are generated each time, and the RES value is very stable.
> 
> ![image](https://user-images.githubusercontent.com/11829907/121872366-c2cc5b00-cd37-11eb-9139-b82e7638b0c6.png)
> 
> full-code:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	goruntime "runtime"
> 	"time"
> 
> 	v1 "k8s.io/api/core/v1"
> 	"k8s.io/apimachinery/pkg/api/meta"
> 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
> 	"k8s.io/apimachinery/pkg/runtime"
> )
> 
> func main() {
> 	leak()
> }
> 
> func leak() {
> 	store := make(map[string]*v1.Pod)
> 	var index int
> 	var items []runtime.Object
> 	for {
> 		items = items[:0]
> 		plist := generatePod()
> 		meta.EachListItem(plist, func(obj runtime.Object) error {
> 			items = append(items, obj)
> 			return nil
> 		})
> 		for _, item := range items {
> 			pod := item.(*v1.Pod)
> 			store[pod.Name] = pod
> 		}
> 		time.Sleep(time.Second * 2)
> 		index++
> 		goruntime.GC()
> 		fmt.Println("==leak==", index, len(store))
> 	}
> }
> 
> func generatePod() *v1.PodList {
> 	var plist v1.PodList
> 	for i := 0; i < 100000; i++ {
> 		pod := v1.Pod{
> 			ObjectMeta: metav1.ObjectMeta{
> 				Name: fmt.Sprintf("pod-%d", i),
> 			},
> 		}
> 		plist.Items = append(plist.Items, pod)
> 	}
> 	return &plist
> }
> ```

a

**Comment by sxllwx** [comment]
If I modify the unleak function to the following code, there will also be a monotonic rise in RES. I suspect that the value (plist) of plist v := reflect.ValueOf(plist).Elem() makes the plist object escape to the heap, which affects the work of golang gc.
```golang
func unleak() {
	store := make(map[string]*v1.Pod)
	var (
		index int
		raw   reflect.Value
	)
	for {
		plist := generatePod(index)
		v := reflect.ValueOf(plist).Elem()
		v = v.FieldByName("Items")
		for i := 0; i < v.Len(); i++ {
			raw = v.Index(i)
			if true {
				raw = raw.Addr()
			}

			o := raw.Interface().(runtime.Object).(*v1.Pod)
			store[o.Name] = o
		}
		time.Sleep(time.Second * 2)
		index++
		goruntime.GC()
		fmt.Println("==unleak==", index, len(store))
	}
}
```

**Comment by wojtek-t** [comment]
Re code above - the leak is not coming from the ForEach, but the fact that you're not really releasing all the references here:
```
items = items[:0]
```


Going back to the original comment, I don't think we have a problem with ForEach function:

> 100 which is too small for our cluster.

you should adjust watchcache size - 100 items in 5k-node cluster is certainly enough. There was a function that adjusts it on number of nodes, but it was based on some flag (apiserver-ram-mb or sth like that), which I bet you don't set.

> Then a memory leak occurred. We use cache map to store pod information, and the cache will contain pods in different PodList. This will prevent golang from gc the whole PodList

I don't understand this comment. If you're storing the data in cache, then it's expected that those will not be GC-ed. That's the whole point in storing them in cache, right?

**Comment by sxllwx** [comment]
The leak here is caused by the golang slice gc mechanism, and there is no memory leak in the `for...range` mode because of the copy mechanism of `v` in `for_, v := range slice`. If the unleak function is changed to the following code (equivalent to the mode of using reflect in meta.EachListItem), there will be an incorrect situation where the res value monotonously increases. I suggest adding deepcopy to meta.EachListItem to alleviate this situation.

```golang
func unleak() {
	store := make(map[string]*v1.Pod)
	var index int
	for {
		plist := generatePod(index)
		for _, pod := range plist.Items {
			store[pod.Name] = &pod
		}
		time.Sleep(time.Second * 2)
		index++
		goruntime.GC()
		fmt.Println("==unleak==", index, len(store))
	}
}
```

**Comment by xiaoanyunfei** [comment]
@sxllwx  is right, `The leak here is caused by the golang slice gc mechanism`.
Once we get address of element in golang slice,  the whole golang slice can not be gc.

I add a new test case, and the `store` caches different `Generation` pod list.
```
import (
        "fmt"
        goruntime "runtime"
        "time"

        v1 "k8s.io/api/core/v1"
        metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func main() {
        leak()
}

func leak() {
        store := make(map[string]*v1.Pod)
        var index int
        for {
                plist := generatePod(index)
                for index, pod := range plist {
                        store[pod.Name] = &plist[index]
                }
                time.Sleep(time.Second * 2)
                index++
                goruntime.GC()
                fmt.Println("==leak==", index, len(store))
        }
}

func generatePod(num int) []v1.Pod {
        var items []v1.Pod
        for i := 0; i < 100000-num; i++ {
                pod := v1.Pod{
                        ObjectMeta: metav1.ObjectMeta{
                                Name:       fmt.Sprintf("pod-%d", i),
                                Generation: int64(num),
                        },
                }
                items = append(items, pod)
        }
        return items
}
```

**Comment by sxllwx** [comment]
> @sxllwx is right, `The leak here is caused by the golang slice gc mechanism`.
> Once we get address of slice element the whole slice can not be gc.
> `meta.EachListItem` has the logic of getting address of slice element.
> 
> I add a new test case, and the `store` caches different `Generation` pod list.
> 
> ```
> import (
>         "fmt"
>         goruntime "runtime"
>         "time"
> 
>         v1 "k8s.io/api/core/v1"
>         metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
> )
> 
> func main() {
>         leak()
> }
> 
> func leak() {
>         store := make(map[string]*v1.Pod)
>         var index int
>         for {
>                 plist := generatePod(index)
>                 for index, pod := range plist {
>                         store[pod.Name] = &plist[index]
>                 }
>                 time.Sleep(time.Second * 2)
>                 index++
>                 goruntime.GC()
>                 fmt.Println("==leak==", index, len(store))
>         }
> }
> 
> func generatePod(num int) []v1.Pod {
>         var items []v1.Pod
>         for i := 0; i < 100000-num; i++ {
>                 pod := v1.Pod{
>                         ObjectMeta: metav1.ObjectMeta{
>                                 Name:       fmt.Sprintf("pod-%d", i),
>                                 Generation: int64(num),
>                         },
>                 }
>                 items = append(items, pod)
>         }
>         return items
> }
> ```

There is already a PR that is working on a similar issue. The link for this PR discussion 
 https://github.com/kubernetes/kubernetes/pull/102565#discussion_r645105418

**Comment by wojtek-t** [comment]
OK - that makes sense to me. Sorry for confusion, I was looking to much at https://github.com/kubernetes/kubernetes/pull/102565#discussion_r645105418 and I still think there is no bug in that PR, because we're not taking an address of slice item there, right? The runtime.Object are already pointers, right?

That said, the extractList that is happening before has this problem:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/api/meta/help.go#L169

@liggitt @deads2k - FYI

**Comment by sxllwx** [comment]
After testing, only in two cases will affect the work of GC

- store[plist.Items[i].GetName()] = &plist.Items[i]
- items.Index(i).Addr().Interface()

The two functions with this kind of operation are

-meta.EachListItem https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/api/meta/help.go#L143
-meta.EachListItem
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/apimachinery/pkg/api/meta/help.go#L196

**Comment by sxllwx** [comment]
@liggitt @deads2k  Is there anything I can do to help this move forward?

**Comment by xigang** [comment]
@deads2k @wojtek-t  we also had a `kube-controller-manager` memory leak, suspected to be related to client-go.
Our cluster has 5600 nodes and `kube-controller-manager` memory usage:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/3377677/189121176-f3459380-1ff6-470c-8387-fad0fbb8add1.png">

**Comment by sxllwx** [comment]
I don't think this issue is related to issue #102565 issue #102718.

issue #102565 #102718 reflects the use of a lot of memory when doing `ListObject`.

And from the kube-controller-manager you provided, the memory-related pprof consumes a lot of memory in the Unmarshal of a separate Object (*corev1.Node).

FYI: My guess here is because a large number of Nodes in the kube cluster briefly jittered.
