### ISSUE TITLE
DynamicKubeletConfig logs nothing when dynamic-config-dir is missing

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102743]
#### What happened:
I tried to use DynamicKubeletConfig, but the kubelet did not react.  I followed the instructions up through https://kubernetes.io/docs/tasks/administer-cluster/reconfigure-kubelet/#observe-that-the-node-begins-using-the-new-configuration but the node's status got no config section.  No events reported an error.  I ran the kubelet with `-v=5`, and it logged no relevant complaint.  I was mystified.  Later I realized I had overlooked one step: supplying `--dynamic-config-dir` on the kubelet's command line.

#### What you expected to happen:
I expected to get a clue about what I did wrong.

#### How to reproduce it (as minimally and precisely as possible):
I think the outline above is pretty direct.

#### Environment:
- Kubernetes version (use `kubectl version`): `GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192"`
- Cloud provider or hardware configuration: VirtualBox VMs
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux init2 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm v1.21.1
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-node-bugs

**Comment by pacoxu** [comment]
https://github.com/kubernetes/enhancements/blob/e324e84516eff5119750a717851e934f6a197fdf/keps/sig-node/281-dynamic-kubelet-configuration/kep.yaml#L35-L37

According to #100799 and the kep above, DynamicKubeletConfig will be deprecated in 1.22 and removed in 1.24.
/cc @SergeyKanzhelev

**Comment by MikeSpreitzer** [comment]
Yes, I thought we might want it to not be such a sharp edge while it is still present.

**Comment by SergeyKanzhelev** [comment]
Since the feature is scheduled for deprecation, closing the issue.

KEP: https://github.com/kubernetes/enhancements/issues/281

/close

**Comment by SergeyKanzhelev** [comment]
> Yes, I thought we might want it to not be such a sharp edge while it is still present.

feel free to send a patch PR. But it will be low priority since it was this way for a while already
