### ISSUE TITLE
Kubelet does not update its node's leaseDurationSeconds

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102744]
#### What happened:
After creating my cluster, I tweaked one kubelet's config to change its NodeLeaseDuration to 100 seconds.  The kubelet echoed the new config to the journal and changed its behavior to renew its lease every 25 seconds --- but it did _not_ update the `spec.leaseDurationSeconds` field of its Lease, that still says "40".

#### What you expected to happen:
I expected the Lease to reflect the newly configured duration.

#### How to reproduce it (as minimally and precisely as possible):
I think the above is pretty direct.

#### Environment:
- Kubernetes version (use `kubectl version`): `GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192"`
- Cloud provider or hardware configuration: VirtualBox VMs
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux init2 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm v1.21.1
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-node-bugs

**Comment by adisky** [comment]
I think Kubelet needs to be restarted when kubelet config is changed, I think the issue here is it is changing the behaviour but not updating the `spec.leaseDurationSeconds` field. Either we should not change the behaviour or we should do both (change the behaviour+update to API)
/triage accepted
/priority backlog

**Comment by MikeSpreitzer** [comment]
I may have restarted the kubelet when I tried that.

**Comment by MadhavJivrajani** [comment]
I was able to reproduce this and I had a few questions, I've started a discussion in sig-node: https://kubernetes.slack.com/archives/C0BP8PW9G/p1628061313065700
