### ISSUE TITLE
`kubectl set env` does not support use of -f and --from flags simultaneously

### ISSUE THREAD

**Issue by ankeesler** [kubernetes/kubernetes#102741]
#### What happened:

* I wanted to write a unit test to validate what happens when someone runs `kubectl set env --from secret/s` and tries to use stdin for both the file and environment variable inputs (e.g., `kubectl set env --from secret/s -f - -`).
* I could not write a valid unit test because `kubectl set env` does not support use of `--from` and `-f` at the same time.
* Actual behavior shown here on the CLI:
```
akeesler@akeesler-a02:kubernetes$ echo '{"apiVersion":"apps/v1","metadata":{"name":"d"},"kind":"Deployment"}' | kubectl set env -f - --from secret/s KEY=VALUE
error: resource/name arguments cannot be provided when a path is specified
```

#### What you expected to happen:

* I expected to be able to use `--from` and `-f` at the same time in a `kubectl set env` command.
* Specifically, I expected `kubectl` to get the `--from` resource separately from the `-f` resource.
* Expected behavior shown here on the CLI:
```
akeesler@akeesler-a02:kubernetes$ echo '{"apiVersion":"apps/v1","metadata":{"name":"d"},"kind":"Deployment"}' | kubectl set env -f - --from secret/s KEY=VALUE
deployment.apps/d env updated
```

#### How to reproduce it (as minimally and precisely as possible):

```
$ kubectl create deploy d --image nginx
$ echo '{"apiVersion":"apps/v1","metadata":{"name":"d"},"kind":"Deployment"}' | kubectl set env -f - --from secret/s KEY=VALUE
```

#### Anything else we need to know?:

* I came upon this while trying to write a unit test in relation to this PR comment: https://github.com/kubernetes/kubernetes/pull/99310#discussion_r629475961.
* I think this issue is coming about here, since we apply both the `-f` and `--from` flags to the resource builder: https://github.com/kubernetes/kubernetes/blob/3d6e0694bbb2eec588982a16d225a00d248a387c/staging/src/k8s.io/kubectl/pkg/cmd/set/set_env.go#L284-L290.

#### Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: `kind`
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others:

/sig cli

**Comment by soltysh** [comment]
I don't consider that a bug, but a conscious decision not to support both 
/close
