### ISSUE TITLE
 Pod fails to start after restarting rapidly

### ISSUE THREAD

**Issue by mowangdk** [kubernetes/kubernetes#102779]
#### What happened:

the following error is reported when the pod is created.
> Warning FailedMount 9m53s (x23 over 40m) kubelet     MountVolume.SetUp failed for volume “xxxxx” : rpc error: code = Internal desc = stat /var/lib/kubelet/plugins/kubernetes.io/csi/pv/xxxxx/globalmount: no such file or directory

#### What you expected to happen:

the pod start normally

#### How to reproduce it (as minimally and precisely as possible):

1. Create multiple pods with cloud disks on a limited number of nodes， e.g  sts(Parallel) replicas 20 in 2 nodes
2. Shrink the replicas of sts to 0
3. When all pods enter terminating state，expand the sts to 20
4. there will be several pods with the above problems.

#### Anything else we need to know?:

1. ```NodeUnstageVolume``` mainly did there things 
    - umount globalmount path
    - remove globalmount path
    - detach disk
2. Due to batch detach disk, some disk detach request will failed
3. The pod restarted without waiting for the kubelet to retry the ```NodeUnstageVolume``` request
4. The pod eventually end up in ContainerCreating State

5. For time being, we solve this problem by move detach disk operation from ```NodeUnStageVolume``` to ```ControllerUnpublishVolume```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4
- OS (e.g: `cat /etc/os-release`):
> NAME="Alibaba Cloud Linux (Aliyun Linux)"
VERSION="2.1903 LTS (Hunting Beagle)"
ID="alinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.1903"
PRETTY_NAME="Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
- Cloud provider or hardware configuration: Alibaba Cloud Container Service for Kubernetes 
- Kernel (e.g. `uname -a`) : Linux 4.19.91-23.al7.x86_64
- Install tools: None
- Network plugin and version (if this is a network-related bug):
- Others: None

**Comment by mowangdk** [comment]
This problem is only reproduced in version 1.20, 1.18 & 1.16 are normal

**Comment by mowangdk** [comment]
the 6060c57ba3a944bd133968fd669980c97af846c6 commit affects the function

```
commit 6060c57ba3a944bd133968fd669980c97af846c6
Author: Jan Safranek <jsafrane@redhat.com>
Date:   Fri Nov 6 17:33:07 2020 +0100

    Call MountDevice only once
    
    Cann MountDevice only when the volume was not device-mounted before.

diff --git a/pkg/volume/util/operationexecutor/operation_generator.go b/pkg/volume/util/operationexecutor/operation_generator.go
index 142cd5acfde..50ee980b5e6 100644
--- a/pkg/volume/util/operationexecutor/operation_generator.go
+++ b/pkg/volume/util/operationexecutor/operation_generator.go
@@ -568,7 +568,7 @@ func (og *operationGenerator) GenerateMountVolumeFunc(
 			DevicePath: devicePath,
 		}
 
-		if volumeDeviceMounter != nil {
+		if volumeDeviceMounter != nil && actualStateOfWorld.GetDeviceMountState(volumeToMount.VolumeName) != DeviceGloballyMounted {
 			deviceMountPath, err :=
 				volumeDeviceMounter.GetDeviceMountPath(volumeToMount.VolumeSpec)
 			if err != nil {
```

**Comment by mowangdk** [comment]
Can this judgment be removed？

**Comment by mowangdk** [comment]
related: https://github.com/kubernetes/kubernetes/pull/88759

**Comment by gnufied** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
> 5. For time being, we solve this problem by move detach disk operation from NodeUnStageVolume to ControllerUnpublishVolume

That's how detach should be done (if your cloud has API for that) - ControllerPublish attaches volumes, ControllerUnpublish detaches them. Ideally, NodeStage finds the attached device and mounts it, and NodeUnstage unmounts it.

**Comment by jsafrane** [comment]
Can you please check https://github.com/kubernetes/kubernetes/pull/100183? I changed the way how errors from NodeUnstage / NodeUnpublish are used, it could fix this issue too.

[ Still, using ControllerPublish / ControllerUnpublish is much better if your cloud allows one CSI driver pod (with the external-attacher) to attach/detach volumes to/from *any* node in the cloud ]

**Comment by mowangdk** [comment]
> > 1. For time being, we solve this problem by move detach disk operation from NodeUnStageVolume to ControllerUnpublishVolume
> 
> That's how detach should be done (if your cloud has API for that) - ControllerPublish attaches volumes, ControllerUnpublish detaches them. Ideally, NodeStage finds the attached device and mounts it, and NodeUnstage unmounts it.

Yes, but due to historical reasons, we cannot migrate all detach operations to ControllerPublish/ControllerUnpublish.  and we believe that spreading the mount operation to each node can increase concurrency

**Comment by mowangdk** [comment]
> Can you please check #100183? I changed the way how errors from NodeUnstage / NodeUnpublish are used, it could fix this issue too.
> 
> [ Still, using ControllerPublish / ControllerUnpublish is much better if your cloud allows one CSI driver pod (with the external-attacher) to attach/detach volumes to/from _any_ node in the cloud ]

ok， we will look into this pr
