### ISSUE TITLE
`k8s.io/kubectl/pkg/cmd/version` `TestNewCmdVersionWithoutConfigFile` always fails locally

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#102754]
/sig cli

run `make test` (or just `make test WHAT=k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/versionn`).

observe failure:

```
--- FAIL: TestNewCmdVersionWithoutConfigFile (0.06s)
    version_test.go:43: Cannot execute version command: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
FAIL
FAIL	k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/version	0.307s
```

xref: https://github.com/kubernetes/kubernetes/issues/102607#issuecomment-854985308

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/issues/102607#issuecomment-858300307 following up here in the original issue for now.

**Comment by knight42** [comment]
@BenTheElder Hi, I have filed #102824 to address this issue.

**Comment by BenTheElder** [comment]
Thank you!
