### ISSUE TITLE
Example kubeadm config has host addresses in the pod subnet

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102767]
#### What happened:
I am trying to learn how to use kubeadm well and it looks like there may be a problem in the example configuration in https://github.com/kubernetes/kubernetes/blob/v1.21.1/cmd/kubeadm/app/apis/kubeadm/v1beta2/doc.go#L155-L253 .  It says `podSubnet: "10.100.0.1/24"`, but also uses address 10.100.0.1 for various host things like the kube-apiserver and the etcd server and the scheduler.  Also, interestingly, it puts a different address --- 10.100.1.1 --- in the apiserver's cert SANs.

#### What you expected to happen:
I expected to not be confused.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-multicluster-misc

**Comment by BenTheElder** [comment]
seems more like sig/cluster-lifecycle?

**Comment by MikeSpreitzer** [comment]
Sorry, typo, corrected.

**Comment by MikeSpreitzer** [comment]
But the 'bot does not seem to have noticed the edit.

@kubernetes/sig-cluster-lifecycle

**Comment by BenTheElder** [comment]
> But the 'bot does not seem to have noticed the edit.

yeah, FWIW commands are never evaluated on comment edit versus a new comment so that trivial edits do not e.g. restart tests etc.

also no need to apologize! just trying to make sure things get the attention of the right folks. @neolit123 in particular seems to stay pretty on top of SCL/kubeadm issues 🙃

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/bc8acbc43eea13effc6c2034a82e7d56ba2d9eb6/cmd/kubeadm/app/apis/kubeadm/v1beta3/types.go#L150-L152
> CertSANs sets extra Subject Alternative Names for the API Server signing cert.

It seems to be intended as the comments above.

**Comment by pacoxu** [comment]
The podSubnet part in the dual stack example is suggested by @aojea in https://github.com/kubernetes/website/pull/26675#discussion_r584168282

**Comment by aojea** [comment]
he is right, the docs are wrong

> podSubnet: "10.100.0.1/24", 

should be 10.100.0.0/24, but I think that is more an aesthetic issue, and the code will take the right subnet, but for docs is better to be pedantic

> but also uses address 10.100.0.1 for various host things like the kube-apiserver and the etcd server and the scheduler. Also, interestingly, it puts a different address --- 10.100.1.1 

yeah, that is why I always suggest to use subnets with more clear differentiation, 10.100.0.0/24 and 10.100.1.0/24 are easy to get wrong, however , 10.96.0.0/16 and 10.244.0.0/16 are not
