### ISSUE TITLE
`pkg/proxy/config` `TestInitialSync` flake

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#102792]
#### Which jobs are flaking:

`pull-kubernetes-unit`

#### Which test(s) are flaking:

`pkg/proxy/config` `TestInitialSync`

#### Testgrid link:

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestInitialSync

( couldn't find a functional testgrid link, but triage should do)

#### Reason for failure:

```
=== RUN   TestInitialSync
W0610 18:48:46.084993   66239 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0610 18:48:46.085207   66239 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0610 18:48:46.086020   66239 config.go:315] Starting service config controller
I0610 18:48:46.086130   66239 shared_informer.go:240] Waiting for caches to sync for service config
I0610 18:48:46.086553   66239 config.go:133] Starting endpoints config controller
I0610 18:48:46.086640   66239 shared_informer.go:240] Waiting for caches to sync for endpoints config
I0610 18:48:46.091967   66239 shared_informer.go:247] Caches are synced for service config 
    api_test.go:159: Unexpected services: []*v1.Service{}, expected: []*v1.Service{(*v1.Service)(0xc000195400), (*v1.Service)(0xc000194c80)}
    api_test.go:159: Unexpected services: []*v1.Service{(*v1.Service)(0xc0001e8500)}, expected: []*v1.Service{(*v1.Service)(0xc000195400), (*v1.Service)(0xc000194c80)}
I0610 18:48:46.187825   66239 shared_informer.go:247] Caches are synced for endpoints config 
--- FAIL: TestInitialSync (0.10s)
```

#### Anything else we need to know:

sample:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102760/pull-kubernetes-unit/1403056738990559232

/sig api-machinery

**Comment by knight42** [comment]
Actually I have filed a PR https://github.com/kubernetes/kubernetes/pull/94564 to deflake this test, but got no response.

**Comment by aojea** [comment]
/assign @knight42 
/unassign @aojea 

Thanks @knight42

**Comment by aojea** [comment]
@knight42 do you mind reopening the PR and assigning me as reviewer?

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/94564 merged 🤞

**Comment by fedebongio** [comment]
/remove-sig api-machinery
looks like the SIG Network PR got merged, maybe we can close this one if flake is solved? 
Thanks!

**Comment by aojea** [comment]
> looks like the SIG Network PR got merged, maybe we can close this one if flake is solved?

/close
Indeed, not failure during the last 3 days

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&test=TestInitialSync
