### ISSUE TITLE
Add pre-condition check for bind operation

### ISSUE THREAD

**Issue by mlmhl** [kubernetes/kubernetes#102761]
#### What would you like to be added:

Currently kube-scheduler binds pod asynchronously, this may lead to a race condition, consider the following scenario:

1.  User submits a StatefulSet with one replica(Pod)
2. Kube-scheduler schedules the pod, and tries to bind the pod in an asynchronous goroutine
3. User updates the StatefulSet, may be that the version of the image has been modified, or the resource requirements have been increased
4. The old pod is deleted and a new one created
5. As the bind operation is executed in an asynchronous goroutine, it may be executed after the pod recreated. So the new pod will be bind as both the old pod and the new one has same name.

However, as the new pod's spec has been modified, so this bind operation may assign the pod to an unsuitable node.

So maybe we need to check the pod's UID or ResourceVersion inside bind operation to avoid above problem.

#### Why is this needed:

The StatefulSet pod maybe assigned to unsuitable node when pod re-created.

**Comment by kerthcet** [comment]
is there any plan? or maybe I can think about it and try to produce a kep.

**Comment by kerthcet** [comment]
hey, @mlmhl  can you explain which resource would be running into a race condition. I can't get your point. Maybe, you can describe at that moment, what status podA and podB stays in.
What's more, IMO, if race condition exists, `Reverse Plugin` would be a better choice.

**Comment by Huang-Wei** [comment]
#105913 has been merged, which will block the binding if the bound pod holds a different UID from the live (recreated) pod.

/close
