### ISSUE TITLE
Refactor preparePVCDataSourceForProvisioning to support BlockVolume tests in multivolume.go

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes/kubernetes#102787]
#### What would you like to be added:

In https://github.com/kubernetes/kubernetes/pull/102775 block volume tests were skipped because `preparePVCDataSourceForProvisioning` is not using `utils.CheckWriteToPath / utils.CheckReadFromPath`, there are more details about how these functions are used in `TestConcurrentAccessToSingleVolume`

This is a test that uses the [XFS](https://cloud.google.com/container-optimized-os/docs/concepts/supported-filesystems#xfs), if tested using the [GCE PD storage class](https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd) it should have `fstype: xfs`, in addition the test cluster should have the [VolumeSnapshot CRDs and the controllers installed](https://kubernetes.io/docs/concepts/storage/volume-snapshots/)

*Things that are needed for a first time contributor*

- a development kubernetes cluster, preferably on a public cloud instance although I'm not sure if kind can be used
- a CSI driver like PD CSI Driver, the storage class should be setup to use the xfs fstype
- the volume snapshot CRDs and controllers installed in the cluster (kubernetes-csi/external-snapshotter#usage)

/sig storage
/area testing
/good-first-issue

**Comment by dbgoytia** [comment]
Hey team! I'd like to further investigate on this issue if possible?

**Comment by mauriciopoppe** [comment]
/area test

hey @dbgoytia, sure, I've added more info about how to test it, it requires these components:

- a development kubernetes cluster, preferably on a public cloud instance although I'm not sure if `kind` can be used
- a CSI driver like [PD CSI Driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/), the storage class should be setup to use the `xfs` fstype
- the volume snapshot CRDs and controllers installed in the cluster (https://github.com/kubernetes-csi/external-snapshotter#usage)

**Comment by dbgoytia** [comment]
thanks a lot @mauriciopoppe !! I might be a bit slow though, I'm pretty new to the community. I appreciate the documentation you shared, the assignation and how to replicate it, I'll test it out and if I have some doubts, I'll get back with you :D

**Comment by sanya301** [comment]
Hey @dbgoytia are you still working on this issue? I am interested in this

**Comment by dbgoytia** [comment]
Yes, I'm still working on this, but would totally be open to doing pair-programming if you're open to it? I would benefit from you for solving the problem since I'm still pretty new to the codebase and I'm still understanding the environment.

**Comment by Shubham2900** [comment]
Hey @dbgoytia, Are you still working on this, I would like to do pair-programming if possible.
