### ISSUE TITLE
Docker image exiting with 0 in response to cron termination leaves active pod

### ISSUE THREAD

**Issue by Christopher-Hurst-rft** [kubernetes/kubernetes#102733]
#### What happened:
A corn docker python job with the replace policy leaves an active pod if it catches  (for clean up) the SIGTERM SIGKILL signals sent by k8s then exits with 0. So if the corn job has a job history we see an active historical pod  that should have been replaced.

If the job does not catch the signal or reponds with the appropriate Docker exit code for the given signal (not 0 eg 137) this problem does not happen.

#### What you expected to happen:
I would not have expected exiting with 0 (no error) in response to cause a difference. If this is a feature it doesn't seem well documented.  

Is the docker return code looked for when the corn job is replaced and how does this affect behaviour.

#### How to reproduce it (as minimally and precisely as possible):
When Kubernetes corn job is "replaced" it sends signals python in docker image catches and returns 0 , job history lists active pod.

Sample simple pything (normally signal catch is for clean up)

import time, signal
quit = False

def shutdown_all(signum, frame):
  global quit
  quit = True
  print ("quit>>>>>>>>>>exit 0")
  exit(0)

if __name__=="__main__":
  print ("start>>>>>>>>>>")
  signal.signal(signal.SIGTERM, shutdown_all)  

  while not quit:
    time.sleep(1)

#### Environment:
Kubernetes 1.17
AWS

Amazon Linux 2

**Comment by neolit123** [comment]
> Kubernetes 1.17

this version is not in support. try 1.19+

> I would not have expected exiting with 0 (no error) in response to cause a difference. If this is a feature it doesn't seem well documented.

/remove-kind bug
/kind documentation
/sig apps
