### ISSUE TITLE
kubernetes1.21.1 : Join from second master makes apiserver in first master, fails & exits

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes/kubernetes#102797]
#### What happened:
**Steps:**
1) Install kubelet, kubectl & kubeadm which by default installs 1.21.1
2) Run kubeadm init with control-end-point with VIP, advertise address as this-host-ip
```
    kubeadm init \
        --control-plane-endpoint "${SLB_VIP}:6443" \
        --apiserver-advertise-address "${SELF_IP}" \
        --upload-certs \
        --skip-phases=addon/kube-proxy \
        --skip-phases=addon/coredns \
        -v=5 || ret=$?

```
3) Watch kubectl get nodes to see first master running fine.
```
NAME              STATUS   ROLES                  AGE     VERSION
co4aeap000110fb   Ready    control-plane,master   2m45s   v1.21.1

```
4) Install same in second master, copy admin.conf & /etc/kubernetes/pki/* files from first master and run join as below
`kubeadm join --discovery-file ${temp_admin_conf} --control-plane -v=5 || ret=$?
`

5) Note, the second master appear as "not ready" in nodes list, briefly
```
NAME              STATUS     ROLES                  AGE     VERSION
co4aeap000110fb   Ready      control-plane,master   3m10s   v1.21.1
co4aeap000110fc   NotReady   <none>                 0s      v1.21.1
Thu Jun 10 21:53:27 UTC 2021
NAME              STATUS     ROLES                  AGE     VERSION
co4aeap000110fb   Ready      control-plane,master   3m15s   v1.21.1
co4aeap000110fc   NotReady   <none>                 5s      v1.21.1
Thu Jun 10 21:53:32 UTC 2021
Thu Jun 10 21:53:47 UTC 2021

```

6) After few seconds, the API server become unreachable in first master and eventually exits
tail end of logs from apiserver pod is as below. BTW I have attached entire log.
```
W0610 21:55:06.267520       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:06.267544       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:06.267625       1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://127.0.0.1:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
W0610 21:55:10.750627       1 controller.go:193] RemoveEndpoints() timed out
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

**NOTE**: The second master is not added as member to VIP, until join succeeds. So any access to control-plane-endpoint would reach the first master, until join completes.
[api_server_log_from_first_master.log](https://github.com/kubernetes/kubernetes/files/6634929/api_server_log_from_first_master.log)
[join_spew_from_second_master.log](https://github.com/kubernetes/kubernetes/files/6634930/join_spew_from_second_master.log)
[script_used.sh.txt](https://github.com/kubernetes/kubernetes/files/6634931/script_used.sh.txt)
[Additional info.txt](https://github.com/kubernetes/kubernetes/files/6634932/Additional.info.txt)

#### What you expected to happen:
Join succeeds consistently

#### How to reproduce it (as minimally and precisely as possible):
Explained above with additional info as attached

#### Anything else we need to know?:
Any tips would be very much appreciated. Thanks in advance!

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.1
- Cloud provider or hardware configuration: Azure VM
- OS (e.g: `cat /etc/os-release`):
```
- NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):  'Linux CO4AEAP000110FB 5.0.0-1032-azure #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux'
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
@renukamanavalan 
you have opened a number of issues in multiple repositories asking for help on the same problem about setting up an high-availability cluster with kubeadm, which i have closed....i understand your position that you might be stuck and you might be making mistakes following the documentation, or even stumbling on gaps in the documentation, but like i said multiple times - the kubernetes issue trackers are not the right place to get support. these are developer forums that track bugs and features.

we leave occasional support tickets open with the idea to gather more information and improve documentation, thus if you discover the source of this problem you can contribute an entry in the kubeadm troubleshooting guide:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

but for general cluster creation support we have #kubeadm, #kubernetes-users on k8s slack and other channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
so please try to avoid logging the same ticket multiple times "until somebody helps", or i will kindly ask github moderation to take action.

/remove-kind bug
/kind support 
/sig cluster-lifecycle

cc @kubernetes/code-of-conduct-committee

**Comment by renukamanavalan** [comment]
Thank you! Sorry about the noise.

**Comment by renukamanavalan** [comment]
Duplicate of [#99305](https://github.com/kubernetes/kubernetes/issues/99305)
