### ISSUE TITLE
Document what happens when using envFrom with invalid values in secret/configmap

### ISSUE THREAD

**Issue by mortenlj** [kubernetes/kubernetes#102732]
#### What happened:

Trying to use `envFrom` to set environment variables from a secret with binary data. Got error message:
`Error: failed to start container "mortenlj-test": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"setenv: invalid argument\"": unknown`

#### What you expected to happen:

I was hoping that invalid values would be skipped with an event, the same as invalid keys.

#### How to reproduce it (as minimally and precisely as possible):

Create a secret with binary data, specifically NULL-bytes, in the *value*. Try to use this in a pod using `envFrom`.

#### Anything else we need to know?:

The specific problem is mentioned in https://github.com/kubernetes/kubernetes/issues/89906, but a mention in the docs for the `envFrom` field on [Container](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#container-v1-core) would be very useful. The current documentation mentions what happens if the keys are invalid, but makes no mention of what happens if a value is invalid (contains a NULL-byte).

This is mostly a request for clearer documentation, but even better if keys with invalid values was just skipped, the same as if the key itself was invalid.

#### Environment:
- Kubernetes version (use `kubectl version`): 
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6",  
  GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.17-gke.1900", GitCommit:"c97b098770a3dcd2e36fdccd8ec5642a5cddbd7f", 
  GitTreeState:"clean", BuildDate:"2021-04-14T09:22:16Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by fedebongio** [comment]
Hi! Thank you for raising! 

Is anybody in cc planning to send a PR to docs? Thanks!
