### ISSUE TITLE
hollow-node cannot work well,  unknown service: runtime.v1alpha2.ImageService

### ISSUE THREAD

**Issue by softputer** [kubernetes/kubernetes#102727]
#### What happened:
when i deploy hollow-node pod to one k8s cluster, it just cannot work well.some error occurs to stop listing images.
![截屏2021-06-09 下午5 42 59](https://user-images.githubusercontent.com/10970097/121354520-88db0d80-c961-11eb-8c9b-10282f70d639.png)

#### What you expected to happen:
hollow-node kubelet runs well with no errors . and when i run e2e tests ,it works well 
#### How to reproduce it (as minimally and precisely as possible):
build kubemark upon  v1.21.1 
#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration: vagrant /vritualbox /ubuntu
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
The error log seems to be kubelet log which pointed to the cri error pulling image.
/sig node

I only find similar issues in https://github.com/kubernetes-sigs/cri-tools/issues/436#issuecomment-464290289 and https://github.com/kubernetes-sigs/cri-tools/issues/710. Would you try?

**Comment by softputer** [comment]
i found the problem ald.
it is because  the containerd 1.4.6 has upgrade pkg/apis/runtime/v1alpha2 to pkg/apis/runtime/v1
but kubemark 1.21.1 still invoke pkg/apis/runtime/v1alpha2, that caused the problem

**Comment by softputer** [comment]
i changed this to make it work
	//f.RemoteImageEndpoint = "/run/containerd/containerd.sock"
	f.RemoteImageEndpoint = "/var/run/dockershim.sock"
