### ISSUE TITLE
I can't reach service IPs on the network. Unable to access application from web.

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10278]
Hi, I have my kubernetes environment up and running on an ubuntu machine with a master and two minion nodes. I'm able to fetch the nodes and list then.

I'm using https://github.com/GoogleCloudPlatform/kubernetes/tree/master/release-0.19.0/examples/update-demo i.e. to scale nautilus image. I'm unaware of which IP to use to view the images on the web page.

```bash
$ kubectl get pods
POD                          IP            CONTAINER(S)   IMAGE(S)                                        HOST                          LABELS                              STATUS    CREATED      MESSAGE
update-demo-nautilus-agkk9   172.16.50.2                                                                  10.x.x.x/10.x.x.x  name=update-demo,version=nautilus   Running   18 minutes
                                           update-demo    gcr.io/google_containers/update-demo:nautilus                                                                     Running   18 minutes
update-demo-nautilus-anjzp   172.16.50.3                                                                  10.x.x.x/10.x.x.x   name=update-demo,version=nautilus   Running   18 minutes
                                           update-demo    gcr.io/google_containers/update-demo:nautilus                                                                     Running   18 minutes
```

```bash
$ kubectl get rc
CONTROLLER             CONTAINER(S)   IMAGE(S)                                        SELECTOR                            REPLICAS
update-demo-nautilus   update-demo    gcr.io/google_containers/update-demo:nautilus   name=update-demo,version=nautilus   2
```

**Comment by nikhiljindal** [comment]
Did you try http://localhost:8001/static as specified in the example?

**Comment by adyanthaya17** [comment]
I did try that that but the page gives me -Webpage unavailable.

**Comment by nikhiljindal** [comment]
Did ```./kubectl proxy --www=examples/update-demo/local/``` work fine?
It should output
```Starting to serve on localhost:8001``` as mentioned at https://github.com/GoogleCloudPlatform/kubernetes/tree/master/release-0.19.0/examples/update-demo#step-one-turn-up-the-ux-for-the-demo

**Comment by adyanthaya17** [comment]
This is what I've got:
$ kubectl proxy --www=examples/update-demo/local/
Starting to serve on localhost:8001

**Comment by adyanthaya17** [comment]
I think the command didn't execute completely as I've to press ctrl d or ctrl c to come out of the command.

**Comment by nikhiljindal** [comment]
```kubectl proxy``` starts a local server on port 8001 for showing the UI. Killing that command kills the server.

Can you try going to localhost:8001 while kubectly proxy is still running.

**Comment by adyanthaya17** [comment]
I went to http://localhost:8001/static while the kubectl proxy is still in 'Starting to serve on localhost:8001'. 

I get:
This webpage is not available

ERR_CONNECTION_REFUSED

**Comment by adyanthaya17** [comment]
Is there a workaround for this one where I can access the web?

**Comment by thockin** [comment]
Can you please provide more details on what you tried to do, what happened,
what you expected to happen?

**Comment by nikhiljindal** [comment]
Dont know of a workaround.
Maybe @brendandburns does?

Can you send the output of ```kubectl cluster-info```
Also, please make sure that examples/update-demo/local/ is accessible from the directory where you are running ```kubectl proxy```

**Comment by nikhiljindal** [comment]
Syncing past https://github.com/GoogleCloudPlatform/kubernetes/pull/10230 might help as well.

**Comment by adyanthaya17** [comment]
$ kubectl cluster-info
Kubernetes master is running at http://10.x.x.x:8080

where 10.x.x.x is my master node. I ran thr comman 'kubetcl proxy'

$ kubernetes/examples/update-demo/local# kubectl proxy
Starting to serve on localhost:8001

@thockin My set up is like this: where I have two nodes-one behaving as both master and minion while the other node as a minion. I have my kubernetes environment up and running, able to fetch node state and they read 'Ready'. I'm following the guestbook from 'kubernetes/release-0.19.0/examples/update-demo'.

$ kubectl proxy --www=examples/update-demo/local/
Starting to serve on localhost:8001

but here it doesn't go to another line. If I need to execute another command I have to make use of ctrl+d and if I run the command again it tells the bind address is already in use. Thinking that it has worked I created two replicas:

$ kubectl create -f examples/update-demo/nautilus-rc.yaml

and resized it:

$ kubectl scale rc update-demo-nautilus --replicas=4

and if I check the 'kubectl get pods' I can see them as an when I resize the pods.

The document said the images that were the four pods could be viewed from the web and I'm not sure how it's done as I'm getting 'web page unavailable' when I go here- http://localhost:8001/static/index.html

**Comment by adyanthaya17** [comment]
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"17", GitVersion:"v0.17.0", GitCommit:"82f8bdac06ddfacf493a9ed0fedc85f5ea62ebd5", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"18", GitVersion:"v0.18.0", GitCommit:"754d3ce99ee50f392369868bf6ba1e866801b086", GitTreeState:"clean"}

**Comment by adyanthaya17** [comment]
@nikhiljindal I tried with the update of #10230 but it didn't seem to work.

**Comment by adyanthaya17** [comment]
Is it necessary to install gcloud SDK for the update-demo?

**Comment by nikhiljindal** [comment]
FWIW, I just tried it on HEAD and it works fine for me.

I ran
```
$./hack/local-cluster-up.sh
```
Then in another tab:
```
$./cluster/kubectl.sh proxy --www=examples/update-demo/local/
```
which gave me
```
Starting to serve on localhost:8001
```
Now, when I go to ```http://localhost:8001/static/``` I get 200 response with a blank page as expected.
Note that going to ```http://localhost:8001/``` gives me ```404 page not found```

My kubectl version is 
```
Client Version: version.Info{Major:"0", Minor:"19+", GitVersion:"v0.19.3-916-g5bd928fed002a3", GitCommit:"5bd928fed002a31ce1c61b15210c296e6ee4c357", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"19+", GitVersion:"v0.19.3-916-g5bd928fed002a3", GitCommit:"5bd928fed002a31ce1c61b15210c296e6ee4c357", GitTreeState:"clean"}
```

**Comment by adyanthaya17** [comment]
When I tried running the first command as you mentioned, this is what I got:
$ ./local-cluster-up.sh
./local-up-cluster.sh: line 35: ./../hack/lib/init.sh: No such file or directory

**Comment by adyanthaya17** [comment]
Okay, so I created a new kubernetes cluster and I'm able to fetch my node details when I run-
$ kubectl get nodes.

When I ran the below command:
./kubectl proxy --www=examples/update-demo/local/ &

It prompts me as: ' bash: ./kubectl: No such file or directory'.

**Comment by adyanthaya17** [comment]
From this document kubernetes/release-0.19.0/examples/update-demo/

I have followed the step 1, step 2, step 3 and step 4. I haven't worked on the step 0. Probably is that the reason why I'm unable to see the pods running on the web?

This is the site I got to, to access the pods:
http://localhost:8001/static/index.html

**Comment by thockin** [comment]
https://github.com/thockin/kubernetes/blob/docs-debug-svcs/docs/debugging-services.md

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by vhosakot** [comment]
I installed k8s using `kubeadm` in https://kubernetes.io/docs/getting-started-guides/kubeadm/.  I wanted to run `kubectl proxy` on the master, and access the k8s API from a different host (not the master) using the IP address (not `localhost`) of the master.

`172.18.7.245` is the IP address of my master, and after doing `kubectl proxy --port=8181 --address=172.18.7.245 --accept-hosts='^*$' &` on the master, I was able to successfully access the k8s API from a different host (with IP address `172.18.7.246 ` and that pings the master `172.18.7.245`) using

```
curl http://172.18.7.245:8181/api/v1
curl http://172.18.7.245:8181/api/v1/services
curl http://172.18.7.245:8181/api/v1/pods
curl http://172.18.7.245:8181/api/v1/secrets
curl http://172.18.7.245:8181/api/v1/static
```

I was also able to access the k8s API from another machine that can SSH into `172.18.7.246` after setting up SSH port-forwaring `ssh -L 8080:172.18.7.245:8181 172.18.7.245` on the machine and using the following commands.

```
curl http://localhost:8080/api/v1
curl http://localhost:8080/api/v1/services
curl http://localhost:8080/api/v1/pods
curl http://localhost:8080/api/v1/secrets
curl http://localhost:8080/static
```
