### ISSUE TITLE
Azure Disk:  Don't automatically reformat disks with NTFS if the disk has an existing filesystem

### ISSUE THREAD

**Issue by mikenri** [kubernetes/kubernetes#102737]
#### What happened:

If A pod that uses Azure Disk for persistent storage mistakenly had no node selector added for a Linux application.

When Kubernetes scheduled the pod to a Windows node, the Azure Disk was reformatted with NTFS and the Linux filesystem data was destroyed.

I have seen this is common with 3rd party software vendors that provide a utility that generates K8S deployment YAML. 
It seems some vendors assume that Kubernetes clusters are Linux only and they don't add a node selector to force their Linux application to run on a Linux node. 

#### What you expected to happen:

There should be a safety check in place where if an Azure Disk has an existing filesystem, do not reformat the disk with NTFS if it is scheduled to a Windows node. 

#### How to reproduce it (as minimally and precisely as possible):

Run a Linux application pod that uses Azure Disk for persistent storage, formatted with a Linux filesystem on a Windows node by mistake. 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18.19
- Cloud provider or hardware configuration: Azure Kubernetes Service
- OS (e.g: `cat /etc/os-release`):  Windows Server 2019 
- Kernel (e.g. `uname -a`):  10.0.17763.1971
- Install tools:  
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Do you use https://github.com/kubernetes-sigs/azuredisk-csi-driver?
/cc @andyzhangx

**Comment by andyzhangx** [comment]
thanks for the info, https://github.com/kubernetes-csi/csi-proxy/pull/123 should fix this issue, while I think we also need to port that fix to in-tree driver? cc @jingxu97

**Comment by mikenri** [comment]
> Do you use https://github.com/kubernetes-sigs/azuredisk-csi-driver?
> /cc @andyzhangx

I am using the following YAML for example:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-nodelete
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-disk
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  kind: managed
  cachingMode: ReadWrite
  storageaccounttype: Premium_LRS
  resourceGroup: my-resource-group

**Comment by andyzhangx** [comment]
this issue is fixed in Azure Disk CSI driver

**Comment by marosset** [comment]
> this issue is fixed in Azure Disk CSI driver

@andyzhangx is there an issue / PR we can link to here for the fix?

**Comment by andyzhangx** [comment]
> > this issue is fixed in Azure Disk CSI driver
> 
> @andyzhangx is there an issue / PR we can link to here for the fix?

@marosset this issue was fixed in csi-proxy v1.0.0, related PR: https://github.com/kubernetes-csi/csi-proxy/pull/123

**Comment by bridgetkromhout** [comment]
Thanks, @andyzhangx. Until the above-linked fix is available on AKS, Andy mentioned to me that a possible workaround is using a windows label (to prevent linux-only workloads from being scheduled on windows nodes): https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/#ensuring-os-specific-workloads-land-on-the-appropriate-container-host

**Comment by andyzhangx** [comment]
since this issue was already fixed in csi-proxy v1.0.0, we won't fix it in in-tree driver because from k8s 1.23, csi migration for azure disk is already turned on by default, all azure disk requests would be handled by azure disk csi driver already.
