### ISSUE TITLE
AWS GP3 Storage Support Missing

### ISSUE THREAD

**Issue by williamblevins** [kubernetes/kubernetes#102707]
#### What would you like to be added:

GP3 Storage Class Support for AWS EBS. Currently, `persistentvolume-controller  Failed to provision volume with StorageClass "prometheus-gp3": invalid AWS VolumeType "gp3"` via Kubernetes 1.19 on EKS.

May require no more than adding the new type here: https://github.com/kubernetes/kubernetes/blob/10ed4502f46d763a809ccdcc6c30be1c03e19147/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L449-L458

For more information on AWS EBS types: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volume-types.html

#### Why is this needed:

Missing a newer, better performance, cost saving volume type for AWS EBS.

**Comment by ialidzhikov** [comment]
/area storage

See https://github.com/kubernetes/kubernetes/pull/102713#issuecomment-857378728. The aws-ebs-csi-driver is already supporting these nee volume types. You should use CSI as the in-tree volume plugins are deprecated.

/cc @msau42

**Comment by pacoxu** [comment]
aws-ebs-csi-driver already supports gp3.

https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/2b612304eb1997cb8da1e6cc79f14a4a09b0ec14/pkg/cloud/cloud.go#L40-L53

**Comment by cheftako** [comment]
Nick?

**Comment by nckturner** [comment]
For new features, CSI should be used, as referenced above by @ialidzhikov.

/close
