### ISSUE TITLE
e2e test failed for kubernetes v1.20.1

### ISSUE THREAD

**Issue by jwz-ecust** [kubernetes/kubernetes#102712]
**What happened:**
kubernetes v1.20.1 sonobuoy e2e test failed for AdmissionWebhook

Plugin: e2e
Status: failed
Passed: 265
Failed: 44
Skipped: 5358

**Failed tests:**
1. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should mutate custom resource with different stored version [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1825
2. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] listing mutating webhooks should work [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:679
3. [Fail] [sig-network] Services [It] should have session affinity timeout work for NodePort service [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3365
4. [Fail] [sig-cli] Kubectl client Update Demo [It] should scale a replication controller  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:330
5. [Fail] [sig-cli] Kubectl client Update Demo [It] should create and stop a replication controller  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:317
6. [Fail] [sig-api-machinery] CustomResourceConversionWebhook [Privileged:ClusterAdmin] [It] should be able to convert from CR v1 to CR v2 [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/crd_conversion_webhook.go:499
7. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should mutate configmap [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:987
8. [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
9. [Fail] [k8s.io] [sig-node] PreStop [It] should call prestop when killing a pod  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/pre_stop.go:151
10. [Fail] [sig-network] DNS [It] should provide DNS for pods for Subdomain [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211
11. [Fail] [sig-cli] Kubectl client Guestbook application [It] should create and stop a working application  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/kubectl/kubectl.go:378
12. [Fail] [sig-network] Services [It] should be able to create a functioning NodePort service [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1179
13. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should mutate custom resource with pruning [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1825
14. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should honor timeout [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:2187
15. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should mutate custom resource [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1825
16. [Fail] [sig-api-machinery] Aggregator [It] Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:404
17. [Fail] [sig-network] Services [It] should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3444
18. [Fail] [sig-network] Services [It] should be able to change the type from ExternalName to ClusterIP [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1662
19. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should deny crd creation [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:2058
20. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should be able to deny attaching pod [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:960
21. [Fail] [sig-network] DNS [It] should provide DNS for services  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211
22. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should be able to deny pod and configmap creation [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:908
23. [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
24. [Fail] [sig-network] Services [It] should have session affinity work for NodePort service [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3444
25. [Fail] [sig-network] Services [It] should be able to change the type from ClusterIP to ExternalName [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1743
26. [Fail] [sig-apps] ReplicationController [It] should serve a basic image on each replica with a public image  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/rc.go:65
27. [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: udp [NodeConformance] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:93
28. [Fail] [sig-network] Services [It] should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3444
29. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should mutate pod and apply defaults after mutation [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1054
30. [Fail] [sig-network] DNS [It] should provide DNS for ExternalName services [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:464
31. [Fail] [sig-network] DNS [It] should provide DNS for pods for Hostname [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:464
32. [Fail] [sig-network] Services [It] should be able to change the type from ExternalName to NodePort [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1701
33. [Fail] [sig-network] Services [It] should have session affinity timeout work for service with type clusterIP [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3365
E0608 17:05:56.091548      23 progress.go:123] Unexpected response when posting progress update to http://localhost:8299/progress: 500
E0608 17:05:56.091581      23 progress.go:131] Response body from posting progress update: []
34. [Fail] [sig-network] DNS [It] should provide DNS for the cluster  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:464
35. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] listing validating webhooks should work [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:605
36. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] should unconditionally reject operations on fail closed webhook [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:1274
37. [Fail] [sig-network] Networking Granular Checks: Pods [It] should function for intra-pod communication: http [NodeConformance] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/networking.go:82
38. [Fail] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] [It] patching/updating a validating webhook should work [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apimachinery/webhook.go:431
39. [Fail] [sig-apps] ReplicaSet [It] should serve a basic image on each replica with a public image  [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/apps/replica_set.go:95
40. [Fail] [sig-network] DNS [It] should resolve DNS of partial qualified names for services [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:464
41. [Fail] [k8s.io] Container Lifecycle Hook when create a pod with lifecycle hook [It] should execute prestop http hook properly [NodeConformance] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/common/lifecycle_hook.go:79
42. [Fail] [sig-network] Services [It] should be able to change the type from NodePort to ExternalName [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:1787
43. [Fail] [sig-network] DNS [It] should provide /etc/hosts entries for the cluster [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/dns_common.go:464
44. [Fail] [sig-network] Services [It] should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance] 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/service.go:3444

**What you expected to happen:**
test pass

**How to reproduce it (as minimally and precisely as possible):**
install kubernetes v1.20.1 with kubeadm and sonobuoy v0.50.0,then run:
sonobuoy run --mode certified-conformance

**Environment:**

[root@master01 ~]# kubectl version --short
Client Version: v1.20.1
Server Version: v1.20.1

root@master1:~/conformance/tests/7# uname -a
Linux master1 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment]
are these failing consistently or only sometimes?
what nodes do you have in the cluster.

we are not seeing consistent failures for the same tests in the k8s CI.

/remove-kind bug
/kind failing-test

**Comment by BenTheElder** [comment]
> install kubernetes v1.20.1 with kubeadm and sonobuoy v0.50.0,then run:

The PR description sort of makes this sound like it's a single node, is that the case? you will not be able to pass conformance without N >= 2 workload-schedulable nodes for one.

There's also a bit more to having a functioning cluster than just installing kubeadm (e.g. need to setup CRI, CNI, ...), we definitely have kubeadm passing all of the conformance tests in CI.

**Comment by jwz-ecust** [comment]
@BenTheElder The test was performed on the platform with 3 master nodes and 1 slave node.
@neolit123 Failing consistently. For each test, it would consume 5 hours. Compared with other tests on cncf, I think it's abnormal.

**Comment by neolit123** [comment]
> The test was performed on the platform with 3 master nodes and 1 slave node.

you need at least two nodes that accept workloads.
add another worker node and retry. if you see the failures again you can reopen the ticket.

/close

**Comment by BenTheElder** [comment]
> The test was performed on the platform with 3 master nodes and 1 slave node.

As @neolit123 mentioned that will not be sufficient, at least two nodes must be workload-schedulable for conformance testing, in order to validate behavior around e.g. rolling updates. That's an explicit decision by the conformance working group that has been discussed quite a bit already so I don't think it's likely to change.

If you add another node I'd guess at least some of these would pass.

> For each test, it would consume 5 hours. Compared with other tests on cncf, I think it's abnormal.

Conformance testing with sonobuoy should not take 5 hours but it should actually take about 2 hours. 

It's not a casual suite, it's an increasingly comprehensive battery to ensure the platform fully behaves in a standard way to provide portable APIs for distributed clustering ... I'm not sure what you're comparing to in CNCF but I don't think there really is anything that needs to test such a broad set of complex APIs.

Perhaps the cluster is a bit under-provisioned? We run these on even fairly low spec hosts (I've run them with maybe 2 cores and a few gb ram) with https://sigs.k8s.io/kind and they pass fine without taking so long but they do take some resources.
