### ISSUE TITLE
Scheduler: deprecate Policy config

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102793]
Policy config is the legacy scheduler configuration API that is being replaced with the standard ComponentConfig one.

This is a tracking issue for deprecating policy config once CC is GA.

- [ ] Remove the flag
- [ ] Remove legacy registry and related factory code

/sig scheduling

**Comment by knight42** [comment]
@ahg-g Hi! I would like to help. By saying `Remove legacy registry and related factory code`, did you mean we should keep the deprecated flags but make them have no effect?

**Comment by ahg-g** [comment]
> @ahg-g Hi! I would like to help. By saying `Remove legacy registry and related factory code`, did you mean we should keep the deprecated flags but make them have no effect?

 We will likely remove them in the same cycle or even same PR.

Thanks for your interest, most likely we will do that in a later release once the community agree that CC is mature enough to replace policy. I created this issue for tracking purposes and raise awareness that this deprecation is coming.

**Comment by ahg-g** [comment]
@damemi @Huang-Wei @alculquicondor should we propose and announce a specific release to remove policy support so that we give the community enough buffer to switch to CC?

**Comment by damemi** [comment]
@ahg-g announcing a specific release would be very helpful, at least for us so we can propagate that timeline downstream to customers. +1

**Comment by ahg-g** [comment]
@damemi what is a reasonable target for your customers?

**Comment by damemi** [comment]
@ahg-g we have been planning for a 1.23 removal (btw, I think this is a duplicate of the original issue for deprecating policy config: https://github.com/kubernetes/kubernetes/issues/92143, we should close one of them)

So, we are fine moving forward with that for a timeline

**Comment by ahg-g** [comment]
oh, I didn't see that one, closing this. Lets move the discussion on setting a target release for the removal to the other issue.
