### ISSUE TITLE
Fake client should support mimic graceful pod deletion

### ISSUE THREAD

**Issue by chenchun** [kubernetes/kubernetes#102798]
#### What would you like to be added:
Fake client should support mimic graceful pod deletion. Although fake client supports `AddReactor/PrependReactor` to add  a customize `Reactor` to different requests, it doesn't pass DeleteOptions down to the `Reactor`.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/fake/fake_pod.go#L121-L126

#### Why is this needed:
To mimic testing graceful pod deletion in my project.

**Comment by fedebongio** [comment]
/cc @caesarxuchao who volunteered to reply / explain / ask
Thanks!
/triage accepted

**Comment by caesarxuchao** [comment]
I think it makes sense to pass down the deleteOptions to the reactors. @chenchun do you want to make a patch?

I don't think the fake client should mimic other graceful deletion logics like handling finalizers. That's too complicated. If tests need to test our those behaviors, they can use the real apiserver.

**Comment by chenchun** [comment]
Yes, I'll send a patch later.

> I don't think the fake client should mimic other graceful deletion logics like handling finalizers. That's too complicated.

I agree.
