### ISSUE TITLE
syntax of KubeletExtraArgs is not clear

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102827]
#### What happened:
I was reading the doc about NodeRegistration, with an interest in specifying some `kubeletExtraArgs`.  I noticed that the doc (e.g., https://github.com/kubernetes/kubernetes/blob/52eea971c57580c6b1b74f0a12bf9cc6083a4d6b/cmd/kubeadm/app/apis/kubeadm/v1beta2/types.go#L207-L210) does not tell me exactly how to identify each arg: exactly as on the command line (including leading dash(es)), as on the command line but without leading dash(es), or camelCase.

#### What you expected to happen:
I expected the doc to enable me to write some `kubeletExtraArgs` with confidence.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
FWIW the answer is flag names as on the command name but without any leading dashes.

This also applies to controllerManager.extraArgs, scheduler.extraArgs, etc. which hopefully should all cover this similarly (if not now, after fixing ...)
