### ISSUE TITLE
APIPriorityAndFairness feature gate with max-requests-inflight: 0 and max-mutating-requests-inflight: 0 causes kubeadm init failure

### ISSUE THREAD

**Issue by davidtseng** [kubernetes/kubernetes#102885]
#### What happened:
Using Kubespray to build a new cluster with v1.20.7, kubeadm init fails at phase upload-config with these specific settings due to apiserver startup issues and the beta feature gate "API Priority and Fairness" enabled (which is by default).

max-requests-inflight: 0
max-mutating-requests-inflight: 0

note: tested setting the vars individually does not trigger bug, only when both are set to 0 does it occur

Error:
error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition

#### What you expected to happen:
kubeadm init completes and cluster builds normally

#### How to reproduce it (as minimally and precisely as possible):

Build new cluster with these apiserver params:
max-requests-inflight: 0
max-mutating-requests-inflight: 0

#### Anything else we need to know?:
If I set the feature gate APIPriorityAndFairness=false then the problem does not occur.

Hinted at solution from:
https://github.com/kubernetes/kubernetes/issues/97525

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.7
- Cloud provider or hardware configuration: aws
- OS (e.g: `cat /etc/os-release`): Flatcar Container Linux by Kinvolk 2765.2.5 (Oklo)
- Kernel (e.g. `uname -a`): Linux 5.10.38-flatcar #1 SMP Thu May 20 20:51:33 -00 2021 x86_64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz GenuineIntel GNU/Linux
- Install tools: kubespray
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
Take a quick look and find below which may be related.
https://github.com/kubernetes/kubernetes/blob/d5685397e18b78133afde778077652ee55e4c5f7/cmd/kube-apiserver/app/server.go#L493-L502

**Comment by SataQiu** [comment]
If the `APIPriorityAndFairness` feature gate is enabled, `FlowControl` will be created.
https://github.com/kubernetes/kubernetes/blob/f880187573d118ec624332e7d62e77074302c7f9/staging/src/k8s.io/apiserver/pkg/server/options/recommended.go#L127-L138

https://github.com/kubernetes/kubernetes/blob/f880187573d118ec624332e7d62e77074302c7f9/staging/src/k8s.io/apiserver/pkg/server/config.go#L735-L741

If the `APIPriorityAndFairness` feature gate is disabled, and `nonMutatingLimit == 0 && mutatingLimit == 0`, it looks like we're just not limiting it.
https://github.com/kubernetes/kubernetes/blob/f880187573d118ec624332e7d62e77074302c7f9/staging/src/k8s.io/apiserver/pkg/server/filters/maxinflight.go#L122-L130

**Comment by MikeSpreitzer** [comment]
D'oh!  I don't remember considering this case, and it is not mentioned in https://kubernetes.io/docs/concepts/cluster-administration/flow-control/#enabling-disabling-api-priority-and-fairness .  I suppose the proper thing to do is to behave analogously to the max-in-flight filter.  That would make the `--enable-priority-and-fairness` command line flag unnecessary, but I do not think that's a show-stopper.  The other plausible alternative would be to apply the default values.

**Comment by MikeSpreitzer** [comment]
I do not understand how you got `--max-requests-inflight=0` and `--max-mutating-requests-inflight=0` on the command line.  When I search for the in kubespray, I find nothing:

```
(base) mspreitz@mjs12 kubespray % git checkout release-2.16
Branch 'release-2.16' set up to track remote branch 'release-2.16' from 'origin'.
Switched to a new branch 'release-2.16'
(base) mspreitz@mjs12 kubespray % 
(base) mspreitz@mjs12 kubespray % find  * -type f -exec grep inflight \{\} \; -print -exec echo \;
(base) mspreitz@mjs12 kubespray % 
```

We discussed the case of `--max-requests-inflight=0` and `--max-mutating-requests-inflight=0` on the command line in the APF meeting today.  The consensues was that since APF can be disabled using the `--enable-priority-and-fairness` command line flag, we should consider `--max-requests-inflight=0` and `--max-mutating-requests-inflight=0` on the command line to be an invalid configuation that will cause the kube-apiserver to log an error and exit at startup.

@lavalamp 
@tkashem 

@deads2k 
@wojtek-t

**Comment by davidtseng** [comment]
@MikeSpreitzer 

We had some custom arguments sent in to kubespray with these vars:

`kube_kubeadm_apiserver_extra_args:
  max-requests-inflight: 0
  max-mutating-requests-inflight: 0`

In the past we ran into apiserver requests hitting the limits due to some large clusters so we had these vars set. They may be outdated / incorrect with recent changes. We are going through upgrading from v1.17.17. It took me a while to track down the issue but I realize it is likely an odd configuration. We'll continue to test but ay advised configuration for large clusters (4000+ pods) welcome.

**Comment by MikeSpreitzer** [comment]
You can try setting large inflight limits, or disabling APF using the `--enable-priority-and-fairness` flag.

**Comment by MikeSpreitzer** [comment]
#103066 , just merged, causes the configuration mentioned here to be rejected.
