### ISSUE TITLE
If a container dies in a pod, we should throw an event

### ISSUE THREAD

**Issue by derekwaynecarr** [kubernetes/kubernetes#10288]
For a related discussion see:
https://github.com/openshift/origin/issues/3390

`docker events` tracks a `die` event separate from a `create` and `start` event.

Monitoring applications will want this event to watch the cluster to know that a container died.

FYI @ejemba @sdminonne @dchen1107

**Comment by mbforbes** [comment]
This seems very useful

**Comment by pmorie** [comment]
Spoke with @sdminonne about this one.  Probable call site: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/dockertools/manager.go#L1601

I think @sdminonne or @ejmemba is going to take this one.

E2E plan we've discussed:  create an imagine that core does (by making `abort` syscall), test that there is an event for it.

**Comment by ejemba** [comment]
@pmorie   I'm going to take care of this one.

**Comment by ejemba** [comment]
Here the related PR 
https://github.com/kubernetes/kubernetes/pull/14115
Not a big fix, but was my first dive in the kube source.

**Comment by yujuhong** [comment]
> Here the related PR 
> #14115

Discussed with @ejemba on #14115, and we decided to wait until the pod lifecycle event generator (#12802) is completed, so that we could extend that to throw an event.

Lowering the priority since the change will not be done anytime soon.
