### ISSUE TITLE
Container Lifecycle Hooks exit on non-0 exit code

### ISSUE THREAD

**Issue by Manu10744** [kubernetes/kubernetes#102841]
Hi,

i don't understand why Container Lifecycle Hooks are instantly killed by Kubernetes (Exit Code 137) when some command is used that returns a non-0 exit code. Sometimes this is expected behavior and i don't understand why this is not possible with Kubernetes.

For example, in a `postStart` lifecycle hook, if i am trying to wait for a webservice inside the container to be running like so:

```bash
ATTEMPT_COUNTER=0
        MAX_ATTEMPTS=12
        until curl --connect-timeout 2 --silent --output /dev/null --fail https:/mypage. de/tasks/definitions; do
            if [ \${ATTEMPT_COUNTER} -eq \${MAX_ATTEMPTS} ]; then
                echo "Container didnt answer in time. "
                exit 1
            fi 

            ATTEMPT_COUNTER=\$((\$ATTEMPT_COUNTER+1))
            sleep 10
        done
```

then this will fail instantly as soon as the first curl command fails on `Connection refused`.

**Comment by HongjiangHuang** [comment]
https://kubernetes.io/docs/tasks/configure-pod-container/attach-handler-lifecycle-event/#discussion. 

The Container's state will only change to Running when the postStart hook is successfully executed, 

so I don't understand what your question is?

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

It looks like we have some documentation for this already as linked by @HongjiangHuang but I will also mark this with a docs tag.

/kind documentation
/close
