### ISSUE TITLE
Docker container runs correctly when running standalone, but crashes when running in kubernetes (out of memory).

### ISSUE THREAD

**Issue by JasonShenk** [kubernetes/kubernetes#102881]
My program is an unmanaged c++ core wrapped with a managed .NET interface. I am running this in a linux docker container in kubernetes. I noticed that garbage collection with the typical using statements doesn't seem to work correctly in the kubernetes environment i.e. the pod will run out of memory if repeatedly allocating. This same behavior is not seen when running just the docker container outside of kubernetes. I have built a test program that mimics our memory allocation scheme which uses arrays of unique pointers. The test program exhibits the same characteristics i.e. it runs out of memory when running in minikube locally but runs indefinitely in just the docker container.
When I run a test .NET wrapped c++ program in a docker linux container that allocates 5 gb of memory within a using statement in a loop, this program executes infinitely as would be expected i.e. memory is allocated, then released and it doesn’t cause out of memory crashes. But when I put this linux image in a k8 container created with a 12 gb maximum memory usage, it repeatedly fails with out of memory errors. These are not on the first allocation of the memory i.e. it allocates and de allocates a few times before it fails with out of memory. Therefore, I conclude that it is not deallocating the memory correctly in the k8 enviornment.

The following is the kernel of the memory allocation in the very simple test program:

      while(n < max)
      {
        using (var memtest = new MemoryTestEngine(megabytes))
        {
          ++n;
          memtest.ClearData();
        }
      }
The memory should be cleared by garbage collection outside of the using scope. In Docker only, it apparently is cleared correctly because I can see the memory utilized quickly converge to a stable value and it does not run out of memory. In Kubernetes running the docker container, It quickly runs out of memory. Further, it seems that it is somehow related to the .NET garbage collection. The default garbage collection appears to work in Docker, but not in Docker inside Kubernetes.

Kubernetes v1.20.2 on Docker 20.10.5

**Comment by JasonShenk** [comment]
How do I triage?  I went to the bot link https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md and there is nothing about triage.

**Comment by fromanirh** [comment]
SIG Node is reviewing and triaging issues that are relevant to supported versions of Kubernetes as part of a bug scrub.

This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by JasonShenk** [comment]
I can  give you containers which can be run in docker, and in kubernetes within docker.  These behave differently (the kubernetes run out of memory while the docker does not).   I'm running docker 20.10.7 and minikube version 1.21.0

**Comment by JasonShenk** [comment]
(from above) Kubernetes v1.20.2 on Docker 20.10.5

**Comment by JasonShenk** [comment]
The following .tar (i had to wrap it in a .zip) is a docker container that repeatedly allocates and deallocates the c++ unmanaged vectors with 2GB of memory.  In docker, with 10GB max memory, this program will run indefinitely.  If I run this in minikube with 10GB (9961 MB) max allocated, it repeatedly crashes due to out of memory.  I am creating the minikube with the following:  minikube start --memory=9900  The .tar file can be loaded into its container with the following command:  docker load -i gc2gb.tar

I would appreciate if someone could give this archive a run and confirm the behavior I am seeing.  

Thanks.

**Comment by JasonShenk** [comment]
Is there a file size limit?  My zip will not upload.

**Comment by JasonShenk** [comment]
zip

**Comment by EricWvi** [comment]
Would you make a image and push it to a registry, say, Docker?

**Comment by JasonShenk** [comment]
I will give it a shot.  I am assuming I need to follow the steps here:

https://docs.docker.com/docker-hub/repos/

**Comment by JasonShenk** [comment]
https://hub.docker.com/repository/docker/jasonshenk/shenktesting/general

**Comment by JasonShenk** [comment]
Anyone else have an idea?
