### ISSUE TITLE
[Failing Test] [sig-storage] ci-kubernetes-e2e-gci-gce-serial 

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/kubernetes#102865]
#### Which jobs are failing:
ci-kubernetes-e2e-gci-gce-serial (gce-cos-master-serial)

#### Which test(s) are failing:
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pvc count metrics for pvc controller after creating pvc only 
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pv count metrics for pvc controller after creating pv only
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create total pv count metrics for with plugin and volume mode labels after creating pv
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning errors [Slow]
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create none metrics for pvc controller before creating any PV or PVC
- Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc
- e2e.go: Test

#### Since when has it been failing:
2021-05-11 19:20:26 +0000 UTC

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

#### Reason for failure:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:526
Jun 14 15:15:06.169: Error getting c-m metricValues: error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)
Unexpected error:
    <*errors.errorString | 0xc00322d500>: {
        s: "error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)",
    }
    error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)
occurred
```

#### Anything else we need to know:

/sig storage

**Comment by aojea** [comment]
I think that this will be fixed by https://github.com/kubernetes/kubernetes/pull/102050
cc @pohly

**Comment by pohly** [comment]
Now we just need to convince someone to merge that PR...

**Comment by lambdanis** [comment]
The PR mentioned above was merged 10 days ago, but it didn't fix the failing tests.

I checked the recent failures, and I didn't see anything failing exactly with the error @ramrodo reported (`Error getting c-m metricValues: error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)`). However, the failures look very similar, there are many timeouts when getting the metrics, like:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:577
Jul 12 11:27:18.810: Unable to get pv controller metrics
Unexpected error:
    <*errors.errorString | 0xc000242240>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:790
```
Most of Volume metrics PVController tests are failing with this error:
* `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create bound pv/pvc count metrics for pvc controller after creating both pv and pvc`
* `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pv count metrics for pvc controller after creating pv only`
* `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pvc count metrics for pvc controller after creating pvc only`
* `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create total pv count metrics for with plugin and volume mode labels after creating pv`
* `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning and attach/detach`

`Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create none metrics for pvc controller before creating any PV or PVC` has some random passes, but usually fails with:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:555
Jul 12 05:20:29.501: Wrong pv controller metric pv_collector_unbound_pv_count(storage_class): wanted map[], got map[provisioning-42154h44z:-1 provisioning-9578p2kfn:-1]
Expected
    <map[string]int64 | len:2>: {
        "provisioning-42154h44z": -1,
        "provisioning-9578p2kfn": -1,
    }
to equal
    <map[string]int64 | len:0>: {}
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:521
```

`Kubernetes e2e suite: [sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation` also has random passes, but usually fails:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:265
Jul 12 09:00:18.985: Expected
    <string>: bootstrap-e2e-minion-group-dt9s
not to equal
    <string>: bootstrap-e2e-minion-group-dt9s
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:325
```

 `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning errors [Slow] expand_more` fails fetching c-m metrics:
 ```
 /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:156
Jul 12 13:45:25.254: Error fetching c-m updated storage metrics
Expected
    <int>: 0
not to equal
    <int>: 0
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:209
```

`Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create metrics for total number of volumes in A/D Controller` also fails to find one metric:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:396
Jul 12 13:29:34.065: Key "attachdetach_controller_forced_detaches" not found in A/D Controller metrics
Expected
    <bool>: false
to equal
    <bool>: true
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:428`
```

These all look related :)

There are also some cleanup failures in the same build, but I don't think they're related, they started more recently.

**Comment by pohly** [comment]
> The PR mentioned above was merged 10 days ago, but it didn't fix the failing tests.
> 
> I checked the recent failures, and I didn't see anything failing exactly with the error @ramrodo reported (`Error getting c-m metricValues: error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server could not find the requested resource (get pods metrics-proxy:10257)`). However, the failures look very similar, there are many timeouts when getting the metrics, like:
> 
> ```
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:577
> Jul 12 11:27:18.810: Unable to get pv controller metrics
> Unexpected error:
>     <*errors.errorString | 0xc000242240>: {
>         s: "timed out waiting for the condition",
>     }
>     timed out waiting for the condition
> occurred
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:790
> ```

If I read https://github.com/kubernetes/kubernetes/blob/584658a17d958f0b663cb39dec1907cbba641300/test/e2e/storage/volume_metrics.go#L781-L790 correctly, this means that the test doesn't get the metrics that it expects. I'm not entirely sure, but I think if it ran into an actual error, it would fail differently. Can you check whether there's any mention of "Error fetching controller-manager metrics"?

> `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create none metrics for pvc controller before creating any PV or PVC` has some random passes, but usually fails with:
> 
> ```
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:555
> Jul 12 05:20:29.501: Wrong pv controller metric pv_collector_unbound_pv_count(storage_class): wanted map[], got map[provisioning-42154h44z:-1 provisioning-9578p2kfn:-1]
> Expected
>     <map[string]int64 | len:2>: {
>         "provisioning-42154h44z": -1,
>         "provisioning-9578p2kfn": -1,
>     }
> to equal
>     <map[string]int64 | len:0>: {}
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:521
> ```

This shows that metrics grabbing worked. It found some metrics data, it's just not the expected data.

> `Kubernetes e2e suite: [sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation` also has random passes, but usually fails:
> 
> ```
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:265
> Jul 12 09:00:18.985: Expected
>     <string>: bootstrap-e2e-minion-group-dt9s
> not to equal
>     <string>: bootstrap-e2e-minion-group-dt9s
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:325
> ```

Not related to metrics?

> `Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics should create prometheus metrics for volume provisioning errors [Slow] expand_more` fails fetching c-m metrics:
> 
> ```
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:156
> Jul 12 13:45:25.254: Error fetching c-m updated storage metrics
> Expected
>    <int>: 0
> not to equal
>    <int>: 0
> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:209
> ```

Another variant of "didn't get expected metrics".

**Comment by lambdanis** [comment]
> If I read
> 
> https://github.com/kubernetes/kubernetes/blob/584658a17d958f0b663cb39dec1907cbba641300/test/e2e/storage/volume_metrics.go#L781-L790
> correctly, this means that the test doesn't get the metrics that it expects. I'm not entirely sure, but I think if it ran into an actual error, it would fail differently. Can you check whether there's any mention of "Error fetching controller-manager metrics"?

Nope, there is nothing like that in [raw build logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1414593366405943296/build-log.txt).

> > `Kubernetes e2e suite: [sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation` also has random passes, but usually fails:
> > ```
> > /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:265
> > Jul 12 09:00:18.985: Expected
> >     <string>: bootstrap-e2e-minion-group-dt9s
> > not to equal
> >     <string>: bootstrap-e2e-minion-group-dt9s
> > /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:325
> > ```
> 
> Not related to metrics?

Ah, yes, this one doesn't look directly related. We should track it in a separate issue probably, I'll check it.

I opened another issue for tracking unmounting failures in the same job: https://github.com/kubernetes/kubernetes/issues/103651

**Comment by ramrodo** [comment]
> Can you check whether there's any mention of "Error fetching controller-manager metrics"?

Yes. There was that error message 29 days ago (06/14/2021) when I created this issue. Here is the [ProwJob link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1404439462015930368)

But now, the error message is not exactly the same but this new one fails at the same step (_Getting plugin name_).

**Comment by pohly** [comment]
I think there's enough evidence to claim (until proven otherwise, of course :sweat_smile: ) that metrics grabbing now works. Why the metrics data is not what the tests expect I don't know - someone familiar with these tests and how they apply to Windows would have to check that.

**Comment by ramrodo** [comment]
Thanks for the suggestion @pohly. I'll look for someone in the community who can help us to test this and update the tests if It is necessary.

**Comment by lambdanis** [comment]
@ramrodo @kubernetes/sig-storage has a meeting in ~30 minutes and I ~~passively aggressively added it to their agenda~~ politely asked to review failures :)

**Comment by wojtek-t** [comment]
FTR - those tests aren't related to Windows (the windows tests might have their own issues).

**Comment by wojtek-t** [comment]
BTW - shouldn't we add this to 1.22 milestone?

**Comment by mauriciopoppe** [comment]
might be related https://github.com/kubernetes/kubernetes/pull/103713

**Comment by mauriciopoppe** [comment]
`Kubernetes e2e suite: [sig-storage] [Serial] Volume metrics PVController should create unbound pvc count metrics for pvc controller after creating pvc only` timed out with:

```
• Failure [79.688 seconds]
[sig-storage] [Serial] Volume metrics
_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
  PVController
  _output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:457
    should create unbound pvc count metrics for pvc controller after creating pvc only [It]
    _output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:568

    Jul 20 21:34:47.206: Unable to get pv controller metrics
    Unexpected error:
        <*errors.errorString | 0xc0002c6bf0>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred

    _output/local/go/src/k8s.io/kubernetes/test/e2e/storage/volume_metrics.go:792
```

I saw that the failure is in the call to `metrics.GrabFromControllerManager()`, in the test there's a beforeEach hook where metrics are fetched with a function wrapped inside a `sync.Once` successfully, 

```
> k8s.io/kubernetes/test/e2e/framework/metrics.(*Grabber).GrabFromControllerManager() _output/local/go/src/k8s.io/kubernetes/test/e2e/framework/metrics/metrics_grabber.go:271 (PC: 0x42acc1d)
   266:                 }
   267:         })
   268:         if err != nil {
   269:                 return ControllerManagerMetrics{}, err
   270:         }
=> 271:         return parseControllerManagerMetrics(output)
   272: }
   273:
   274: // GrabFromSnapshotController returns metrics from controller manager
   275: func (g *Grabber) GrabFromSnapshotController(podName string, port int) (SnapshotControllerMetrics, error) {
   276:         if !g.grabFromSnapshotController {
(dlv) p output
"# HELP apiserver_audit_event_total [ALPHA] Counter of audit even...+1009762 more"
```

However the test attempts to get metrics again later using the same function but because it's wrapped with `sync.Once` the output is an empty string next time.

```
k8s.io/kubernetes/test/e2e/framework/metrics.(*Grabber).GrabFromControllerManager() _output/local/go/src/k8s.io/kubernetes/test/e2e/framework/metrics/metrics_grabber.go:271 (PC: 0x42acc1d)
   266:                 }
   267:         })
   268:         if err != nil {
   269:                 return ControllerManagerMetrics{}, err
   270:         }
=> 271:         return parseControllerManagerMetrics(output)
   272: }
   273:
   274: // GrabFromSnapshotController returns metrics from controller manager
   275: func (g *Grabber) GrabFromSnapshotController(podName string, port int) (SnapshotControllerMetrics, error) {
   276:         if !g.grabFromSnapshotController {
(dlv) p output
""
```

@pohly Do you know why the function that fetches metrics is wrapped with `sync.Once`?

cc @jingxu97

**Comment by aojea** [comment]
The sync.Once function are used for waiting for the corresponding pods once, I think it is a mistake, and the logic to obtain metrics should be out of the sync.Once function
```
			output, lastMetricsFetchErr = g.getSecureMetricsFromPod(g.kubeControllerManager, metav1.NamespaceSystem, kubeControllerManagerPort)
```
https://github.com/kubernetes/kubernetes/pull/101895#commitcomment-50902953

**Comment by mauriciopoppe** [comment]
Thanks for chiming in @aojea, indeed once I removed the wrapping `sync.Once` all of the tests passed in #103806

**Comment by mauriciopoppe** [comment]
/reopen

I'll check the results in CI and also cherrypick to 1.22, then we should be able to close this issue.

**Comment by mauriciopoppe** [comment]
All of the storage metric related failures are green now, the remaining tests that are failing are tracked in https://github.com/kubernetes/kubernetes/issues/103651

**Comment by dims** [comment]
thanks @mauriciopoppe let's close this then!

/close
