### ISSUE TITLE
regression in vsphere attach disk call with invalid canonical path

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#102891]
When we introduced https://github.com/kubernetes/kubernetes/pull/95447 we added an additional check during attach disk call to check for canonical path - https://github.com/kubernetes/kubernetes/pull/95447/files#diff-5000d45019379218cc35bc5f967f2731b4dbff230399361c8f6b9a8af3e7e1f0R928

Now this is creating a regression in many deployments because when volume is created, canonical path gets replaced - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L1467
and hence when attach is attempted k8s can't find canonical path of the volume anymore.

It throws following error:

```
E0615 19:43:13.184859  155096 attacher.go:93] Error attaching volume "[/Datacenter/datastore/foobar/team-ssd-intel] kubevols/kubernetes-dynamic-pvc-9ca3e73f-841f-49ab-95ad-7de96881f06a.vmdk" to node "attach.home.lan": failed to get path from dummy request: ServerFaultCode: Invalid datastore path '[/Datacenter/datastore/foobar/team-ssd-intel] kubevols/kube-dummyDisk.vmdk'. is not a FileNotFound error                      
```

There are two ways of fixing this. We could decide to use old `vmDiskPath` in attach code, if we can't fetch canonical path or we could decide not to replace canonical path during provisioning. 

cc @divyenpatel 

/sig storage

**Comment by divyenpatel** [comment]
cc: @chethanv28

**Comment by gnufied** [comment]
The code that replaces canonical Path during provisioning is pretty old and hence I don't remember/know why we are doing that. But since there could be many existing PVs that now have different canonical path - I think it might be safest to merge - https://github.com/kubernetes/kubernetes/pull/102892 to prevent any regressions.
