### ISSUE TITLE
Failure cluster [6837517a...]

### ISSUE THREAD

**Issue by ankeesler** [kubernetes/kubernetes#102842]
##### Error text:
```
=== RUN   TestExecPluginRotationViaInformer
=== PAUSE TestExecPluginRotationViaInformer
=== CONT  TestExecPluginRotationViaInformer
I0531 11:39:46.948512  125677 controller.go:181] Shutting down kubernetes service endpoint reconciler
I0531 11:39:46.948694  125677 dynamic_cafile_content.go:170] "Shutting down controller" name="request-header::/tmp/kubernetes-kube-apiserver689092220/proxy-ca.crt"
E0531 11:39:46.948812  125677 storage_flowcontrol.go:142] "APF bootstrap ensurer is exiting" err="timed out waiting for the condition"
I0531 11:39:46.948838  125677 controller.go:122] Shutting down OpenAPI controller
I0531 11:39:46.948859  125677 crd_finalizer.go:278] Shutting down CRDFinalizer
I0531 11:39:46.948876  125677 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
I0531 11:39:46.948899  125677 crdregistration_controller.go:142] Shutting down crd-autoregister controller
I0531 11:39:46.948921  125677 nonstructuralschema_controller.go:204] Shutting down NonStructuralSchemaConditionController
I0531 11:39:46.948936  125677 naming_controller.go:302] Shutting down NamingConditionController
I0531 11:39:46.948955  125677 establishing_controller.go:87] Shutting down EstablishingController
I0531 11:39:46.948976  125677 cluster_authentication_trust_controller.go:463] Shutting down cluster_authentication_trust_controller controller
I0531 11:39:46.948996  125677 apiservice_controller.go:131] Shutting down APIServiceRegistrationController
I
```
#### Recent failures:
[6/2/2021, 10:37:11 AM ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1400098826638856192)
[5/31/2021, 7:14:34 AM ci-kubernetes-integration-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1399323072154046464)

/kind failing-test
/kind flake
/sig auth
/cc @enj 

Thought we squashed this here https://github.com/kubernetes/kubernetes/issues/102650, but no such luck.

**Comment by pacoxu** [comment]
The link seems to be not correct.

 Non TestExecPluginRotationViaInformer flake after June 7th(#102652 merged on June 7th)
https://storage.googleapis.com/k8s-gubernator/triage/index.html?test=TestExecPluginRotationViaInformer
![image](https://user-images.githubusercontent.com/2010320/122007302-60806280-cdea-11eb-8b08-9190f622458d.png)

**Comment by ankeesler** [comment]
@pacoxu you are correct, this was my mistake. The failures I was seeing were actual failures in my PR, and were fixed here: https://github.com/kubernetes/kubernetes/pull/99310#issuecomment-861525441.

Closing this issue as it is not the flake that I thought it was.
