### ISSUE TITLE
Node NotReady: kubelet suddenly giving error Failed to list ****: an error on the server ("") has prevented the request from succeeding

### ISSUE THREAD

**Issue by mootezbessifi** [kubernetes/kubernetes#102876]
#### What happened:
Worker nodes on a cluster suddenly stop sending heart bits giving the below error 
> **From Kubelet:** 
`Jun 15 11:06:25 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:25.205094    8693 reflector.go:153] object-"sop-qa"/"stag-registry": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:06:25 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:25.404929    8693 reflector.go:153] object-"sop-qa"/"sop-qa-postgres-user": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:06:25 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:25.605089    8693 reflector.go:153] object-"sop-qa"/"sop-qa-vendor": Failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps)
Jun 15 11:06:25 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:25.696838    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
Jun 15 11:06:25 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:25.805193    8693 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: an error on the server ("") has prevented the request from succeeding (get runtimeclasses.node.k8s.io)
Jun 15 11:06:26 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:26.005139    8693 reflector.go:153] object-"sop-dev"/"sop-dev-ignite-token-ms7tp": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:06:26 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:26.205067    8693 reflector.go:153] object-"kube-system"/"stag-registry": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:06:34 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:34.702010    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
Jun 15 11:06:35 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:35.606024    8693 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io fms-k8s-node-dev-14)
Jun 15 11:06:43 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:43.707303    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
Jun 15 11:06:51 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:51.610528    8693 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io fms-k8s-node-dev-14)
Jun 15 11:06:52 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:52.712496    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
Jun 15 11:06:58 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:58.805357    8693 reflector.go:153] object-"kube-system"/"custom-fluentd-fluentd-elasticsearch": Failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps)
Jun 15 11:06:59 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:59.005021    8693 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:458: Failed to list *v1.Node: an error on the server ("") has prevented the request from succeeding (get nodes)
Jun 15 11:06:59 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:59.205134    8693 reflector.go:153] object-"sop-dev"/"sop-dev-portal": Failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps)
Jun 15 11:06:59 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:59.405197    8693 reflector.go:153] object-"sop-qa"/"default-token-wsvzb": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:06:59 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:59.605085    8693 reflector.go:153] object-"sop-dev"/"sop-dev-ignite": Failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps)
Jun 15 11:06:59 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:06:59.805104    8693 reflector.go:153] object-"mon-v1"/"prometheus-node-exporter-token-x7pkr": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:00 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:00.005205    8693 reflector.go:153] object-"sop-dev"/"default-token-jvzmd": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:00 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:00.205177    8693 reflector.go:153] object-"sop-dev"/"dev-registry": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:00 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:00.405156    8693 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: an error on the server ("") has prevented the request from succeeding (get pods)
Jun 15 11:07:00 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:00.605086    8693 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.CSIDriver: an error on the server ("") has prevented the request from succeeding (get csidrivers.storage.k8s.io)
Jun 15 11:07:00 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:00.805155    8693 reflector.go:153] k8s.io/kubernetes/pkg/kubelet/kubelet.go:449: Failed to list *v1.Service: an error on the server ("") has prevented the request from succeeding (get services)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.005142    8693 reflector.go:153] object-"kube-system"/"custom-fluentd-fluentd-elasticsearch-token-6tccd": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.205041    8693 reflector.go:153] object-"sop-qa"/"stag-registry": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.404977    8693 reflector.go:153] object-"sop-qa"/"sop-qa-postgres-user": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.605085    8693 reflector.go:153] object-"sop-qa"/"sop-qa-vendor": Failed to list *v1.ConfigMap: an error on the server ("") has prevented the request from succeeding (get configmaps)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.717354    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.717409    8693 kubelet_node_status.go:389] Unable to update node status: update node status exceeds retry count
Jun 15 11:07:01 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:01.805055    8693 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.RuntimeClass: an error on the server ("") has prevented the request from succeeding (get runtimeclasses.node.k8s.io)
Jun 15 11:07:02 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:02.005085    8693 reflector.go:153] object-"sop-dev"/"sop-dev-ignite-token-ms7tp": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:02 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:02.205134    8693 reflector.go:153] object-"kube-system"/"stag-registry": Failed to list *v1.Secret: an error on the server ("") has prevented the request from succeeding (get secrets)
Jun 15 11:07:07 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:07.615555    8693 controller.go:135] failed to ensure node lease exists, will retry in 7s, error: an error on the server ("") has prevented the request from succeeding (get leases.coordination.k8s.io fms-k8s-node-dev-14)
Jun 15 11:07:20 fms-k8s-node-dev-14 kubelet[8693]: E0615 11:07:20.722795    8693 kubelet_node_status.go:402] Error updating node status, will retry: error getting node "fms-k8s-node-dev-14": an error on the server ("") has prevented the request from succeeding (get nodes fms-k8s-node-dev-14)
`

> **From kube-apiserver getting:**
`Jun 14 14:41:03 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 14:41:03.547627   31268 writers.go:105] apiserver was unable to write a JSON response: client disconnected
Jun 14 14:41:03 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 14:41:03.547795   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"client disconnected"}
Jun 14 14:41:03 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 14:41:03.548976   31268 writers.go:118] apiserver was unable to write a fallback JSON response: client disconnected
Jun 14 15:03:52 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:03:52.397138   31268 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.967319   31268 writers.go:105] apiserver was unable to write a JSON response: client disconnected
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.967441   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"client disconnected"}
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.968630   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.968714   31268 writers.go:118] apiserver was unable to write a fallback JSON response: client disconnected
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.969285   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.969796   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Jun 14 15:06:28 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 15:06:28.970501   31268 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
Jun 14 16:07:15 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 16:07:15.682865   31268 watcher.go:214] watch chan error: etcdserver: mvcc: required revision has been compacted
Jun 14 16:14:44 fms-k8s-master-dev-1 kube-apiserver[31268]: E0614 16:14:44.178597   31268 upgradeaware.go:357] Error proxying data from client to backend: read tcp 127.0.0.1:8080->127.0.0.1:53834: read: connection reset by peer`

This issue start happening 5 days ago while the cluster was initiated 3 years ago and the last upgrade was performed 6 months back for etcd from v3.0.13 to 3.4.13 and kubernetes one year back from 1.14.2 to 1.17.4.

I have tested all kind of communication between worker and master + handle and execute commands on master nothing giving error and everything looks working like a charm. 
Also checked the ETCD cluster health and status, everything looks fine

**Additional info**
`$ kubectl cluster-info
Kubernetes master is running at http://127.0.0.1:8080`
 
#### What you expected to happen:
Node keep the state healthy and continue pushing heart bits 
#### Anything else we need to know?:
This issue is happening randomly and to fix it temporary i need to restart kubelet 

**kubelet config**
`[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=containerd.service
Requires=containerd.service

[Service]
ExecStart=/usr/local/bin/kubelet \
  --config=/var/lib/kubelet/config.yaml \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock \
  --image-pull-progress-deadline=2m \
  --kubeconfig=/var/lib/kubelet/fms-k8s-node-dev-14.kubeconfig \
  --network-plugin=cni \
  --register-node=true \
  --hostname-override=fms-k8s-node-dev-14 \
  --v=10 \
  --cloud-provider=openstack \
  --cloud-config=/opt/kubernetes/cloud.config \
  --log-dir=/var/log/kubernetes \
  --logtostderr=false
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`

**var/lib/kubelet/config.yaml **
`apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: 0.0.0.0
tlsCertFile: "/var/lib/kubelet/fms-k8s-node-dev-14.pem"
tlsPrivateKeyFile: "/var/lib/kubelet/fms-k8s-node-dev-14-key.pem"
authentication:
  x509:
    clientCAFile: "/opt/kubernetes/certs/ca.pem"
  webhook:
    enabled: false
    cacheTTL: 2m0s
  anonymous:
    enabled: false
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
clusterDomain: cluster.local
clusterDNS:
- 10.240.0.254
runtimeRequestTimeout: 15m0s
podCIDR: 10.200.0.0/16
evictionHard:
  memory.available: 500Mi
  nodefs.available: '10'
systemReserved:
  cpu: 500m
  ephemeral-storage: 1Gi
  memory: 2Gi
kubeReserved:
  cpu: '1'
  ephemeral-storage: 1Gi
  memory: 1Gi
`

**kube-api config**
`[Unit]
Description=Kubernetes API Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes

[Service]
ExecStart=/opt/kubernetes/bin/kube-apiserver \
  --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority \
  --advertise-address=11.11.11.11 \
  --allow-privileged=true \
  --apiserver-count=3 \
  --audit-log-maxage=30 \
  --audit-log-maxbackup=3 \
  --audit-log-maxsize=100 \
  --audit-log-path=/var/log/audit.log \
  --authorization-mode=Node,RBAC \
  --bind-address=0.0.0.0 \
  --client-ca-file=/opt/kubernetes/certs/ca.pem \
  --etcd-cafile=/opt/kubernetes/certs/ca.pem \
  --etcd-certfile=/opt/kubernetes/certs/client.pem \
  --etcd-keyfile=/opt/kubernetes/certs/client-key.pem \
  --etcd-servers=https://172.16.1.19:2379,https://172.16.1.18:2379,https://172.16.1.17:2379 \
  --event-ttl=1h \
  --encryption-provider-config=/var/lib/kubernetes/encryption-config.yaml \
  --kubelet-certificate-authority=/opt/kubernetes/certs/ca.pem \
  --kubelet-client-certificate=/opt/kubernetes/certs/admin.pem \
  --kubelet-client-key=/opt/kubernetes/certs/admin-key.pem \
  --kubelet-https=true \
  --runtime-config=api/all=true \
  --service-account-key-file=/opt/kubernetes/certs/ca-key.pem \
  --service-cluster-ip-range=10.240.0.0/16 \
  --service-node-port-range=30000-32767 \
  --tls-cert-file=/opt/kubernetes/certs/client.pem \
  --tls-private-key-file=/opt/kubernetes/certs/client-key.pem  \
  --audit-log-path=/var/log/kubernetes/kube-apiserver.log \
  --logtostderr=false \
  --log-dir=/var/log/kubernetes \
  --cloud-provider=openstack \
  --cloud-config=/opt/kubernetes/cloud.config \
  --http2-max-streams-per-connection=1000 \
  --v=8
Restart=on-failure
RestartSec=5
`
#### Environment:
- Kubernetes version (use `kubectl version`): 1.17.4
- Cloud provider or hardware configuration: openstack public cloud
- OS (e.g: `cat /etc/os-release`): ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux fms-k8s-node-dev-14 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: self developed ansible scripts (following kubernetes  the hard way)
- Network plugin and version (if this is a network-related bug): Flannel v0.12.0
- Container Runtime: containerd github.com/containerd/containerd v1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429

**Comment by n4j** [comment]
@mootezbessifi Could you describe on what environment your cluster is deployed? If it's on cloud then do let us know the cloud vendor.

**Comment by mootezbessifi** [comment]
@n4j my enviroment is deployed on Ubuntu VMs 16.04 provisioned on Mirantis Openstack cloud

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/issues/73742#issuecomment-460659872 and https://github.com/kubernetes/kubernetes/issues/83938#issuecomment-543370966 which may help.

**Comment by mootezbessifi** [comment]
Hi @pacoxu  I used to share all logs which i have. 
The main issue is with kubelet and not with kube-api as per the above logs 
I was interacting with master using many kubectl commands without facing any considerable issue. everything was pretty fine.

why kubelet gets working for a while then go down suddenly after hours generating the previously reported logs !

**Comment by ehashman** [comment]
@mootezbessifi This sounds to me like a network interruption occurred between the kubelet and API server. I don't see anything that suggests there is a bug, and we would require more verbose logs to assist. Furthermore, 1.17 is not a supported version.

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/)! Thanks.

/remove-kind bug
/kind support
/close

**Comment by liuyanzhen34** [comment]
Thank you

**Comment by pacoxu** [comment]
We recently meet the problem in an old Kuberentes cluster which is v1.18. We have a lot of `prevented` error message like this.
Finally, we found it is related to `use of closed connection` https://github.com/kubernetes/kubernetes/issues/87615.  
- For instance, v1.18.19 fixed it in https://github.com/kubernetes/kubernetes/pull/100376. But the feature is disabled if HTTP2_READ_IDLE_TIMEOUT_SECONDS is set to 0. (You should enable it with this env)

**Comment by prometheus-tao** [comment]
The same issue occur on uat k8s cluster, I fixed this problem by restart kubelet, but i feel the same case will be occur again, Have other method or setting can be avoid this situation? @ehashman
