### ISSUE TITLE
kubectl: get configmap in env-file format

### ISSUE THREAD

**Issue by ha-douken** [kubernetes/kubernetes#102815]
# My intend
I want to update a configmap holding environment variables in these steps:
1. kubectl get configmap … > my-file
2. Modify my-file
3. kubectl create configmap --from-env-file my-file …

# The issues I have
* This will not work because yaml is not an accepted format for --from-env-file
* Using --from-file which accepts yaml does not work because it adds the filename as a key on root level instead of the content

# My Questions
* Can I somehow get the configmap in an env-file format?
* Or can I somehow submit the yaml format without the the extra key?

@kubernetes/sig-cli-misc

**Comment by ha-douken** [comment]
@kubernetes/sig-cli-misc
/sig cli

**Comment by HongjiangHuang** [comment]
You can try: 

1. `kubectl get configmap … -o yaml > my-file.yaml`
2. Modify my-file.yaml
3. `kubectl apply -f my-file.yaml`

@ha-douken 

/close
/kind support
