### ISSUE TITLE
informer watch memory leak after create and delete resources thousands times

### ISSUE THREAD

**Issue by fangpb** [kubernetes/kubernetes#102874]
#### What happened:
I use informer to watch a kind of resources. Then, I try to create and delete the resources ten thousands times, after that, I find that the memory used by the process increased 35MB。 I try to analays the memory use with pprof, the result as follow.
the pprof graph show the momory used by the **StreamWatcher**.

11270.19kB 37.05% 37.05% 11270.19kB 37.05%  reflect.New
 6145.50kB 20.20% 57.26%  6145.50kB 20.20%  k8s.io/apimachinery/pkg/apis/meta/v1.(*FieldsV1).UnmarshalJSON
 3072.23kB 10.10% 67.36%  3072.23kB 10.10%  reflect.unsafe_NewArray
 2560.05kB  8.42% 75.78%  2560.05kB  8.42%  github.com/modern-go/reflect2.(*unsafeType).UnsafeNew
 2560.04kB  8.42% 84.19%  2560.04kB  8.42%  github.com/json-iterator/go.(*Iterator).ReadString
 1536.14kB  5.05% 89.24%  2727.10kB  8.97%  ***.enqueueTask
  678.95kB  2.23% 91.47%   678.95kB  2.23%  k8s.io/client-go/util/workqueue.(*Type).Add
  544.67kB  1.79% 93.27%   544.67kB  1.79%  google.golang.org/grpc/internal/transport.newBufWriter
  512.28kB  1.68% 94.95%   512.28kB  1.68%  reflect.mapassign
  512.06kB  1.68% 96.63%   512.06kB  1.68%  google.golang.org/protobuf/internal/impl.(*MessageInfo).makeKnownFieldsFunc
#### What you expected to happen:
-
#### How to reproduce it (as minimally and precisely as possible):
watch a kind of resources with informer, and try to create and delete the resources ten thousands times
#### Anything else we need to know?:
-
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by evanlixin** [comment]
me too, Waiting for reply
