### ISSUE TITLE
Fail to grab controller manager metrics fro Windows test cluster on prow job  

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#102893]
One of Windows prow tests (gce pd CSI migration tests) started to fail from May 10 (between 17~21pm UTC). Checking PRs merged, we identified PR https://github.com/kubernetes/kubernetes/pull/96216

This PR disable insecure serving in controller-manager, created metrics-proxy to get metrics. Some investigation so far

1. From build log of prow jobs, the metrics-proxy is running fine. 
```
I0615 02:47:54.936210   85970 metrics_proxy.go:83] Found components: [{kube-controller-manager-e2e-7451bd99eb-b549a-master 10257 10.40.0.2} {kube-scheduler-e2e-7451bd99eb-b549a-master 10259 10.40.0.2}]
I0615 02:48:27.309443   85970 metrics_proxy.go:212] Successfully setup metrics-proxy
```
2. All test failed at the line with errors [link](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-gce-pd-csi-driver-latest-k8s-master-windows-2019-migration/1404616952315383808/build-log.txt)
https://github.com/kubernetes/kubernetes/pull/96216/files#diff-28a3131f96324063dd53e17270d435a3b0b3bd8f806ee0e33295929570eab209R289
```
Jun 15 02:50:32.126: FAIL: Error getting c-m metrics : error waiting for controller manager pod to expose metrics: timed out waiting for the condition; the server is currently unable to handle the request (get pods metrics-proxy:10257)
```

3. We tried to create e2e cluster with kubetest locally with similar set up and run CSI windows tests, and they can pass. Metrics can be correctly retrieved from metrics-proxy.

**Comment by jingxu97** [comment]
cc @pohly @knight42 @mauriciopoppe

**Comment by jingxu97** [comment]
cc @mattcary @jeremyeder @pjh

**Comment by pacoxu** [comment]
Since #96216, the 10252 HTTP port for kube-controller-manager was not supported anymore.
Does windows setup or csi depend on that port?

**Comment by pohly** [comment]
My theory, as mentioned in https://github.com/kubernetes/kubernetes/pull/102050#issuecomment-855386927, is that in the CI's Windows cluster, the kube-controller-manager only listens on localhost. The current metrics-grabber does not support this. My PR would address that.
