### ISSUE TITLE
Device manager silently fails to restore checkpoint after upgrading to 1.20+

### ISSUE THREAD

**Issue by fromanirh** [kubernetes/kubernetes#102880]
#### What happened:
After upgrading kubelet from version <= 1.19 to version >= 1.20, the device manager will fail to restore its state from the checkpoint. The change was introduced in https://github.com/kubernetes/kubernetes/commit/a8b8995ef241e93e9486d475126450f33f24ef4e .

The restore fails silently (it actually writes a warning in the logs, but keeps going). Because of this the device manager state is inconsistent up until the device plugins register themselves again, which can take minutes, depending on the specific device plugin. We seen up to 5 minutes on real clusters the for SRIOV device plugin.

Because of the inconsistent state, the kubelet will **NOT** update the device availability to zero, so the scheduler will send pods towards the inconsistent kubelet.
At admission time, the device manager allocation will not trigger, again because of the incosistent state, so pods will be admitted without device plugins actually being allocated to them.

#### What you expected to happen:
Any of the following wouls be acceptable
1. the kubelet recovers the checkpoint state correctly
2. the kubelet sets its own state as inconsistent, so pods aren't scheduled until the node heals
3. the kubelet sets its own state as inconsistent, so pods aret scheduled, but aren't admitted until the node heals

#### How to reproduce it (as minimally and precisely as possible):
1. run pods requesting devices on <= 1.19 kubelet
2. drain the node
3. upgrade the kubelet to a version >= 1.20
4. run pods on the upgraded node typically as soon as the node gets Ready

#### Anything else we need to know?:

The issue was discovered first in openshift, but turns out is not openshift specific.

The bug triggers only after a upgrade, so kubelet is stopped, updated (<= 1.19 to >= 1.20) and started again.
There are no more know ways to trigger this bug.

The updated kubelet fails to restore the checkpoint data. See this excerpt from the logs
```
Jun 15 07:31:49.743990 openshift-worker-1 hyperkube[4852]: I0615 07:31:49.743846    4852 manager.go:236] Starting Device Plugin manager

[...]

Jun 15 07:31:49.744795 openshift-worker-1 hyperkube[4852]: W0615 07:31:49.744770    4852 manager.go:244] Continue after failing to read checkpoint file. Device allocation info may NOT be up-to-date. Err: json: cannot unmarshal array into Go struct field PodDevicesEntry.Data.PodDeviceEntries.DeviceIDs of type checkpoint.DevicesPerNUMA
```
The kubelet keep going, but this means the internal devicemanager maps will be **completely** empty. The expected state after recovery is that the *key* of the relevant devices will be present.
This is a critical point to understand the impact of this bug.
After the failed recovery, the kubelet will happily run, but the node update callback (https://github.com/kubernetes/kubernetes/blob/v1.20.7/pkg/kubelet/cm/devicemanager/manager.go#L516) will **not** update the node objects.

This is another critical point to understand the impact of this bug.
The expected behaviour is to reset the allocatable device counters to 0 (zero) up until the device plugins register themselves again.
So the scheduler will send pods on this node, while it should not (devices not ready).

In the pod admission flow, and we call `DeviceManager.Allocate()`, which ultimately calls `allocateContainerResources` https://github.com/kubernetes/kubernetes/blob/v1.20.7/pkg/kubelet/cm/devicemanager/manager.go#L830

Each loop, we have a call to `isDevicePluginResources` (https://github.com/kubernetes/kubernetes/blob/v1.20.7/pkg/kubelet/cm/devicemanager/manager.go#L843). Problem is: exactly because the **empty healthyDevices** maps, it always return false.
Worth stressing that the bug is that the maps are completely empty. The expected flows is to have the **keys** in the map, but with zero values (until the device plugin registers itself again). Should that have been the case, an device allocation request should have been performed.

#### Environment:
- Kubernetes version (use `kubectl version`): any kubernetes >= 1.20
- Cloud provider or hardware configuration: any
- OS (e.g: `cat /etc/os-release`): any
- Kernel (e.g. `uname -a`): any
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by fromanirh** [comment]
I have a PR in the working to make sure the kubelet can read pre-1.20 checkpoint files, which is IMO the cleanest and most robust way to solve this issue. I will post it shortly.

**Comment by fromanirh** [comment]
Update:
After further investigation: I'm quite confident the issue here happens on the upgrade flow when node is recovering, so all the pods -including the device plugin one(s)- need to be recreated, and this take some time.
This means there is no concern about device plugins slow to re-register or other issues: it really seems a plain old race, which is possible because the device manager state is corrupted.

In the environments on which we observed this bug, the time window on which the device manager state is corrupted is in the order of 2-3 (two or three) minutes.

**Comment by fromanirh** [comment]
https://github.com/kubernetes/kubernetes/pull/102882 merged so k8s 1.23 and onwards should be safe now. question is if we need to do backports on 1.20, 1.21, 1.22 (or a subset thereof). @klueska @endocrimes @ehashman any thoughts?

**Comment by endocrimes** [comment]
Now we have all three backports LGTM'd and Approved from a node pov, we need to go through the cherry pick approval process which I'm not super familiar with

For reference inline:
- 1.20: https://github.com/kubernetes/kubernetes/pull/106295
- 1.21: https://github.com/kubernetes/kubernetes/pull/106254
- 1.22: https://github.com/kubernetes/kubernetes/pull/106253

**Comment by fromanirh** [comment]
Neither am I, but I'll have a deep look ASAP. Thanks!

**Comment by endocrimes** [comment]
@ehashman has been through the process before and might be able to give you some pointers

**Comment by fromanirh** [comment]
all the backports got merged, I think we can now close this issue
