### ISSUE TITLE
Scheduler: remove deprecated scheduler CLI flags

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#102804]
The command line flags `hard-pod-affinity-symmetric-weight` and `scheduler-name` have been marked as deprecated for multiple releases.

We can now remove them, deprecation policy for admin-facing CLI flags is "GA, admin-facing flag, longer of 6 months or 1 release"

Verify deprecated since 1.18: https://github.com/kubernetes/kubernetes/blob/release-1.18/cmd/kube-scheduler/app/options/deprecated.go

/sig scheduling
/assign

**Comment by Huang-Wei** [comment]
@ahg-g a kind reminder: ensure it's reflected in k/website.

**Comment by ahg-g** [comment]
@sftim do we manually update the flags in the [reference](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/) or do they get automatically updated?

**Comment by sftim** [comment]
The reference for kube-scheduler is autogenerated; https://kubernetes.io/docs/contribute/generate-ref-docs/kubernetes-components/ explains how.
