### ISSUE TITLE
When create a cluster by kubeadm, the parameter'--log-file' does not take effect

### ISSUE THREAD

**Issue by AbelTaylor** [kubernetes/kubernetes#102982]
#### What happened:
i use command 'kubeadm init --kubernetes-version {{ k8s_version }} --token={{ token }} --token-ttl 0 --log-file /var/log/kube_master.log' to initialize the cluster

#### What you expected to happen:
the file '/var/log/kube_master.log' becomes the log file of the master node, but it doesn't work, same time, the worker node use 'kubeadm join XXX --log-file ' does not work , neither.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.11
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0.72
- Install tools:
- Network plugin and version (if this is a network-related bug): flannel
- Others:

**Comment by wangyysde** [comment]
dupplicated: #101425

**Comment by neolit123** [comment]
see https://github.com/kubernetes/kubeadm/issues/2455

use `| tee ...` instead.

/close
