### ISSUE TITLE
`verify-generated-docs.sh` log spam: `WARNING: go-md2man does not handle node type HTMLSpan`

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#102976]
expand the logs for:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102960/pull-kubernetes-verify/1405766623234625536

see this long line included _many_ times repeatedly

probably we should fix this?

/sig docs
? maybe ?

**Comment by BenTheElder** [comment]
this is still true and still unneeded log noise
/remove-lifecycle stale

maybe architecture instead since these are generated API docs AFAICT
/sig architecture

**Comment by BenTheElder** [comment]
/remove-lifecycle rotten
this still absolutely spams the logs https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107616/pull-kubernetes-verify/1483478985085030400

/lifecycle frozen

**Comment by liggitt** [comment]
no md2man / HTMLSpan warning messages in latest logs for that job or in a manual run, marking is resolved

/close
