### ISSUE TITLE
Windows kubelet volume-stats-agg high cpu usage.

### ISSUE THREAD

**Issue by franznemeth** [kubernetes/kubernetes#102954]
#### What happened:
In our windows  kubernetes environment we run workloads with an emptyDir which is about 80GiB in size and contains lots of small files. Since the --volume-stats-agg-period features defaults to 1m kubelet never seems to finish this run and uses more and more CPU over time and eventually crashing. 

Setting the --volume-stats-agg-period=-1s  (#96674) fixes this behavior.

#### What you expected to happen:
kubelet not steadily increasing CPU usage over time because of volume-stats-agg feature.

#### How to reproduce it (as minimally and precisely as possible):
Create a number of pods with large emptyDir volumes on a windows worker node.

#### Anything else we need to know?:
We are running the rancher kubernetes distribution but this seems like a kubelet issue to me. 
#### Environment:
- Kubernetes version (use `kubectl version`): 
`Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Master nodes running in vSphere and workers on bare-metal
- OS (e.g: `cat /etc/os-release`): 
Windows Server 2019 Standard 1809
- Kernel (e.g. `uname -a`):
OS Build 17763.1999
- Install tools:
rancher rke

If there is any additional information I can provide I am happy to do so.

**Comment by immuzz** [comment]
cc : @jsturtevant

**Comment by sanchayanghosh** [comment]
I will be taking a look at this issue. WIll try to reproduce first, and update on the status.

**Comment by franznemeth** [comment]
Thanks for having a look. We were able to reproduce it somewhat reliably by having about 100Gi of small files (for example source code) in an emptyDir.
