### ISSUE TITLE
use cluster size instead of zone size when decide eviction rate in node life cycle controller

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/kubernetes#102908]
#### What happened:

both the [doc](https://kubernetes.io/docs/concepts/architecture/nodes/#reliability) and [notes](https://github.com/kubernetes/kubernetes/blob/f5cf74ddff818236b8435370afa41a51f23dd532/cmd/kube-controller-manager/app/options/nodelifecyclecontroller.go#L45) implies that the `large-cluster-size-threshold` of node lifecycle controller is the whole cluster size, but the [reduce qps logic](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1374) is passed with the zone size in  [`enterPartialDisruption`](https://github.com/kubernetes/kubernetes/blob/6298e1fe6add48f2705c19a120d041570c7eba9a/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1316) logic

#### What you expected to happen:
use cluster size instead of zone size

**Comment by pacoxu** [comment]
I prefer to think it would be a doc problem which may be not that clear.

https://kubernetes.io/docs/concepts/architecture/nodes/#reliability
> The reason these policies are implemented per availability zone is because one availability zone might become partitioned from the master while the others remain connected. If your cluster does not span multiple cloud provider availability zones, then there is only one availability zone (i.e. the whole cluster).

**Comment by xrmzju** [comment]
> I prefer to think it would be a doc problem which may be a little unclear to use `--large-cluster-size-threshold`(maybe `large-zone-size-threshold` is better. If there's no zone defined, cluster size is the same as the zone size.).
> 
> https://kubernetes.io/docs/concepts/architecture/nodes/#reliability
> 
> > The node eviction behavior changes when a node **in a given availability zone** becomes unhealthy.
> > The reason **these policies are implemented** **per availability zone** is because one availability zone might become partitioned from the master while the others remain connected. If your cluster does not span multiple cloud provider availability zones, then there is only one availability zone (i.e. the whole cluster).

From the implement now you are right. but on the other side, i think use zone size does not make any sense. PartialDisruption state  accours when the percentage of  notReadyNodes  in this zone greater than [unhealthyZoneThreshold](https://github.com/kubernetes/kubernetes/blob/7b9c335826d0d76a8a49c45588f5a30bd85b7ed9/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1496)（default 0.55）, image this situation,  a cluster spreads in zone1(100 nodes) and zone2(20 nodes), if 15 nodes fail in zone2, than zone2 is in PartialDisruption state, as a cluster administor, i would like my apps deployed in this zone2 could be migrated to zone1 cause zone1 has enough resources. but if i have a small cluster, eviction may not help because the other zone may not have enough resource.

**Comment by xrmzju** [comment]
> > I prefer to think it would be a doc problem which may be a little unclear to use `--large-cluster-size-threshold`(maybe `large-zone-size-threshold` is better. If there's no zone defined, cluster size is the same as the zone size.).
> > https://kubernetes.io/docs/concepts/architecture/nodes/#reliability
> > > The node eviction behavior changes when a node **in a given availability zone** becomes unhealthy.
> > > The reason **these policies are implemented** **per availability zone** is because one availability zone might become partitioned from the master while the others remain connected. If your cluster does not span multiple cloud provider availability zones, then there is only one availability zone (i.e. the whole cluster).
> 
> From the implement now you are right. but on the other side, i think use zone size does not make any sense. PartialDisruption state accours when the percentage of notReadyNodes in this zone greater than [unhealthyZoneThreshold](https://github.com/kubernetes/kubernetes/blob/7b9c335826d0d76a8a49c45588f5a30bd85b7ed9/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1496)（default 0.55）, image this situation, a cluster spreads in zone1(100 nodes) and zone2(20 nodes), if 15 nodes fail in zone2, than zone2 is in PartialDisruption state, as a cluster administor, i would like my apps deployed in this zone2 could be migrated to zone1 cause zone1 has enough resources. but if i have a small cluster, eviction may not help because the other zone may not have enough resource.

**Comment by pacoxu** [comment]
My point is only from a quick reading of the code and docs. The code owner may have a better understanding and clarificaiton.

**Comment by ehashman** [comment]
Docs say (emphasis mine)

> The node controller checks what **percentage of nodes in the zone** are unhealthy (NodeReady condition is ConditionUnknown or ConditionFalse) at the same time:
>
> - If the cluster is small (i.e. has less than or equal to `--large-cluster-size-threshold nodes` - default 50), then evictions are stopped.

I don't think this is a bug, but rather a clarity issue with the docs.

/remove-kind bug
/kind documentation
/help
/good-first-issue

**Comment by meganeshkadam** [comment]
Hi @ehashman , 
I would like to contribute to this issue. Doc bugs is a good place to start! 

I am currently going through below reference: 
~~~
https://kubernetes.io/docs/contribute/
~~~
I have already signed the individual CNCF contributor license Agreement, kindly let me know what should be my next steps. :)

**Comment by meganeshkadam** [comment]
> Docs say (emphasis mine)
> 
> > The node controller checks what **percentage of nodes in the zone** are unhealthy (NodeReady condition is ConditionUnknown or ConditionFalse) at the same time:
> > 
> > * If the cluster is small (i.e. has less than or equal to `--large-cluster-size-threshold nodes` - default 50), then evictions are stopped.
> 
> I don't think this is a bug, but rather a clarity issue with the docs.
> 
> /remove-kind bug
> /kind documentation
> /help
> /good-first-issue

So, Do I need to replace `--large-cluster-size-threshold`  with  `--large-zone-size-threshold` ?
OR we need to phrase this pointer in the documentation completely for better clarity? 

Can you help with what needs to be updated in the documentation? 

BR,
Ganesh Kadam

**Comment by sftim** [comment]
I'm not sure this issue is well-defined enough to count as a good first issue for this website.
/remove-good-first-issue

@xrmzju if you're happy to revise the issue description to make things clear even to a new contributor, we'd be happy to look at reinstating that label.

@meganeshkadam you might like to pick a different issue from https://github.com/kubernetes/website/issues?q=is%3Aissue+label%3A%22good+first+issue%22+is%3Aopen+label%3Alanguage%2Fen
