### ISSUE TITLE
Kubernetes services unable to communicate with inter subnets

### ISSUE THREAD

**Issue by indrajithgihan** [kubernetes/kubernetes#102906]
#### What happened: We have worker nodes with 2 different subnets (172.26.180 & 172.26.224). Kubernetes IP range communication is working within the subnet as expected and unable to communicate with inter subnets. 

Please refer the below scenario for more information. 

 Working  -  Traffic initiating from 172.26.224.34 (Master Server)  to pod (10.244.27.2) which is scheduled in worker node (172.26.224.11) 
Not working - Traffic initiating from  172.26.180.14 (Master Server) to pod (10.244.27.2) which is scheduled in worker node (172.26.224.11) 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.17.12
- Cloud provider or hardware configuration: On prem cluster
- OS (e.g: `cat /etc/os-release`): Red Hat Enterprise Linux Server 7.8 (Maipo)
- Kernel (e.g. `uname -a`): 3.10.0-1160.el7.x86_64
- Install tools: firewalld is turned off. Kubectl,kubelet and kubeadm,Docker version 18.06.3-ce are installed
- Network plugin and version (if this is a network-related bug): flannel 
- Others:

**Comment by pacoxu** [comment]
/sig network
but it seems to be a support case and should be flannel issue in my opinion.

**Comment by uablrek** [comment]
K8s v1.17 is no longer maintained. That said, this does not look like a K8s problem, rather a configuration problem. Likely in flannel as @pacoxu pointed out.

Which network overlay are you using? Vxlan? Please add this info and version of flannel to the network plugin info.

**Comment by uablrek** [comment]
Can you from within a POD on a worker in subnet "A"  `ping` a POD on a worker in subnet "B"? With it's pod ip that is, **not** through any service ip. If not this is a CNI-plugin overlay problem. And btw, in a multi subnet cluster you _must_ use a network overlay.

**Comment by uablrek** [comment]
@indrajithgihan Can you please provide the requested information and try the "ping" test above?

**Comment by indrajithgihan** [comment]
@uablrek Found the issue was with network firewall blocking 8472 udp port. Hence we managed to open the port in firewall and now thus is working. Hence ok to close this issue as it is a firewall blockage.

**Comment by uablrek** [comment]
Ok, thanks.

/close
