### ISSUE TITLE
"dial timeout" flakes in e2e tests with konnectivity proxy enabled

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#102904]
#### What happened:

various e2e tests are flaking with "dial timeout" errors since June 7th, when the konnectivity network proxy was enabled by default in 

https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=dial%20timeout

![image](https://user-images.githubusercontent.com/980082/122152112-c2fb5200-ce2e-11eb-904d-17446da52172.png)

All the failures I saw in https://testgrid.k8s.io/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-grpc&width=20&sort-by-failures= were "dial timeout" errors

cc @cheftako @jkh52 

/kind bug
/kind flake

**Comment by liggitt** [comment]
I'm not seeing how the request context is plumbed to egress dialers, specifically here:

https://github.com/kubernetes/kubernetes/blob/6298e1fe6add48f2705c19a120d041570c7eba9a/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go#L224-L243

I expected to see the context plumbed so that connect/proxy calls don't outlive the driving request... maybe something like this (though I'm not positive the connect and proxy calls are 1:1):
```diff
diff --git a/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go b/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
index 701540d64ad..d9eb5dfafdc 100644
--- a/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
+++ b/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector.go
@@ -134,7 +134,7 @@ func tunnelHTTPConnect(proxyConn net.Conn, proxyAddress, addr string) (net.Conn,
 
 type proxier interface {
 	// proxy returns a connection to addr.
-	proxy(addr string) (net.Conn, error)
+	proxy(ctx context.Context, addr string) (net.Conn, error)
 }
 
 var _ proxier = &httpConnectProxier{}
@@ -144,7 +144,7 @@ type httpConnectProxier struct {
 	proxyAddress string
 }
 
-func (t *httpConnectProxier) proxy(addr string) (net.Conn, error) {
+func (t *httpConnectProxier) proxy(ctx context.Context, addr string) (net.Conn, error) {
 	return tunnelHTTPConnect(t.conn, t.proxyAddress, addr)
 }
 
@@ -154,14 +154,14 @@ type grpcProxier struct {
 	tunnel client.Tunnel
 }
 
-func (g *grpcProxier) proxy(addr string) (net.Conn, error) {
-	return g.tunnel.Dial("tcp", addr)
+func (g *grpcProxier) proxy(ctx context.Context, addr string) (net.Conn, error) {
+	return g.tunnel.DialContext(ctx, "tcp", addr)
 }
 
 type proxyServerConnector interface {
 	// connect establishes connection to the proxy server, and returns a
 	// proxier based on the connection.
-	connect() (proxier, error)
+	connect(context.Context) (proxier, error)
 }
 
 type tcpHTTPConnectConnector struct {
@@ -169,11 +169,12 @@ type tcpHTTPConnectConnector struct {
 	tlsConfig    *tls.Config
 }
 
-func (t *tcpHTTPConnectConnector) connect() (proxier, error) {
-	conn, err := tls.Dial("tcp", t.proxyAddress, t.tlsConfig)
+func (t *tcpHTTPConnectConnector) connect(ctx context.Context) (proxier, error) {
+	conn, err := (&tls.Dialer{NetDialer: &net.Dialer{}, Config: t.tlsConfig}).DialContext(ctx, "tcp", t.proxyAddress)
 	if err != nil {
 		return nil, err
 	}
+	// TODO: tie conn lifetime to ctx lifetime
 	return &httpConnectProxier{conn: conn, proxyAddress: t.proxyAddress}, nil
 }
 
@@ -181,11 +182,12 @@ type udsHTTPConnectConnector struct {
 	udsName string
 }
 
-func (u *udsHTTPConnectConnector) connect() (proxier, error) {
-	conn, err := net.Dial("unix", u.udsName)
+func (u *udsHTTPConnectConnector) connect(ctx context.Context) (proxier, error) {
+	conn, err := (&net.Dialer{}).DialContext(ctx, "unix", u.udsName)
 	if err != nil {
 		return nil, err
 	}
+	// TODO: tie conn lifetime to ctx lifetime
 	return &httpConnectProxier{conn: conn, proxyAddress: u.udsName}, nil
 }
 
@@ -193,17 +195,17 @@ type udsGRPCConnector struct {
 	udsName string
 }
 
-func (u *udsGRPCConnector) connect() (proxier, error) {
+func (u *udsGRPCConnector) connect(ctx context.Context) (proxier, error) {
 	udsName := u.udsName
 	dialOption := grpc.WithContextDialer(func(context.Context, string) (net.Conn, error) {
-		c, err := net.Dial("unix", udsName)
+		c, err := (&net.Dialer{}).DialContext(ctx, "unix", udsName)
 		if err != nil {
 			klog.Errorf("failed to create connection to uds name %s, error: %v", udsName, err)
 		}
-		return c, err
+		return c, fmt.Errorf("uds: %w", err)
 	})
 
-	tunnel, err := client.CreateSingleUseGrpcTunnel(udsName, dialOption, grpc.WithInsecure())
+	tunnel, err := client.CreateSingleUseGrpcTunnel(ctx, udsName, dialOption, grpc.WithInsecure())
 	if err != nil {
 		return nil, err
 	}
@@ -229,15 +231,15 @@ func (d *dialerCreator) createDialer() utilnet.DialFunc {
 		trace := utiltrace.New(fmt.Sprintf("Proxy via %s protocol over %s", d.options.protocol, d.options.transport), utiltrace.Field{Key: "address", Value: addr})
 		defer trace.LogIfLong(500 * time.Millisecond)
 		start := egressmetrics.Metrics.Clock().Now()
-		proxier, err := d.connector.connect()
+		proxier, err := d.connector.connect(ctx)
 		if err != nil {
 			egressmetrics.Metrics.ObserveDialFailure(d.options.protocol, d.options.transport, egressmetrics.StageConnect)
-			return nil, err
+			return nil, fmt.Errorf("connect: %w", err)
 		}
-		conn, err := proxier.proxy(addr)
+		conn, err := proxier.proxy(ctx, addr)
 		if err != nil {
 			egressmetrics.Metrics.ObserveDialFailure(d.options.protocol, d.options.transport, egressmetrics.StageProxy)
-			return nil, err
+			return nil, fmt.Errorf("proxy: %w", err)
 		}
 		egressmetrics.Metrics.ObserveDialLatency(egressmetrics.Metrics.Clock().Now().Sub(start), d.options.protocol, d.options.transport)
 		return conn, nil
diff --git a/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector_test.go b/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector_test.go
index 2b31ccc41b6..b1ac1351d12 100644
--- a/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector_test.go
+++ b/staging/src/k8s.io/apiserver/pkg/server/egressselector/egress_selector_test.go
@@ -176,7 +176,7 @@ type fakeProxyServerConnector struct {
 	proxierErr   bool
 }
 
-func (f *fakeProxyServerConnector) connect() (proxier, error) {
+func (f *fakeProxyServerConnector) connect(ctx context.Context) (proxier, error) {
 	if f.connectorErr {
 		return nil, fmt.Errorf("fake error")
 	}
@@ -187,7 +187,7 @@ type fakeProxier struct {
 	err bool
 }
 
-func (f *fakeProxier) proxy(_ string) (net.Conn, error) {
+func (f *fakeProxier) proxy(_ context.Context, _ string) (net.Conn, error) {
 	if f.err {
 		return nil, fmt.Errorf("fake error")
 	}
diff --git a/vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go b/vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
index 9d1f6f911e0..3158e415771 100644
--- a/vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
+++ b/vendor/sigs.k8s.io/apiserver-network-proxy/konnectivity-client/pkg/client/client.go
@@ -35,7 +35,7 @@ import (
 type Tunnel interface {
 	// Dial connects to the address on the named network, similar to
 	// what net.Dial does. The only supported protocol is tcp.
-	Dial(protocol, address string) (net.Conn, error)
+	DialContext(ctx context.Context, protocol, address string) (net.Conn, error)
 }
 
 type dialResult struct {
@@ -66,15 +66,15 @@ var _ clientConn = &grpc.ClientConn{}
 // gRPC based proxy service.
 // Currently, a single tunnel supports a single connection, and the tunnel is closed when the connection is terminated
 // The Dial() method of the returned tunnel should only be called once
-func CreateSingleUseGrpcTunnel(address string, opts ...grpc.DialOption) (Tunnel, error) {
-	c, err := grpc.Dial(address, opts...)
+func CreateSingleUseGrpcTunnel(ctx context.Context, address string, opts ...grpc.DialOption) (Tunnel, error) {
+	c, err := grpc.DialContext(ctx, address, opts...)
 	if err != nil {
 		return nil, err
 	}
 
 	grpcClient := client.NewProxyServiceClient(c)
 
-	stream, err := grpcClient.Proxy(context.Background())
+	stream, err := grpcClient.Proxy(ctx)
 	if err != nil {
 		return nil, err
 	}
@@ -86,12 +86,12 @@ func CreateSingleUseGrpcTunnel(address string, opts ...grpc.DialOption) (Tunnel,
 		readTimeoutSeconds: 10,
 	}
 
-	go tunnel.serve(c)
+	go tunnel.serve(ctx, c)
 
 	return tunnel, nil
 }
 
-func (t *grpcTunnel) serve(c clientConn) {
+func (t *grpcTunnel) serve(ctx context.Context, c clientConn) {
 	defer c.Close()
 
 	for {
@@ -175,7 +175,7 @@ func (t *grpcTunnel) serve(c clientConn) {
 
 // Dial connects to the address on the named network, similar to
 // what net.Dial does. The only supported protocol is tcp.
-func (t *grpcTunnel) Dial(protocol, address string) (net.Conn, error) {
+func (t *grpcTunnel) DialContext(ctx context.Context, protocol, address string) (net.Conn, error) {
 	if protocol != "tcp" {
 		return nil, errors.New("protocol not supported")
 	}
@@ -224,7 +224,9 @@ func (t *grpcTunnel) Dial(protocol, address string) (net.Conn, error) {
 		t.conns[res.connid] = c
 		t.connsLock.Unlock()
 	case <-time.After(30 * time.Second):
-		return nil, errors.New("dial timeout")
+		return nil, errors.New("dial timeout, backstop")
+	case <-ctx.Done():
+		return nil, errors.New("dial timeout, context")
 	}
 
 	return c, nil
```

also, wrapping errors so that we can tell at what layer timeouts or errors are occurring at would make this easier to figure out

**Comment by jkh52** [comment]
Thanks will take a look.

**Comment by BenTheElder** [comment]
Pass rate for the GCE e2e presubmit in Kubernetes has _tanked_

https://prow.k8s.io/?job=pull-kubernetes-e2e-kind
> Success rate over time: 3h: 100%, 12h: 96%, 48h: 90%

https://prow.k8s.io/?job=pull-kubernetes-e2e-gce-ubuntu-containerd
> Success rate over time: 3h: 64%, 12h: 66%, 48h: 73%

~60% versus a real pass of 100% of PRs is not very acceptable. If this can't be fixed immediately we should probably be reverting konnectivity in this repo, I've already seen a number of SIGs wind up opting out their CI jobs because of issues.

**Comment by BenTheElder** [comment]
kubemark: https://github.com/kubernetes/test-infra/pull/22495, https://github.com/kubernetes/perf-tests/issues/1828
netpol: https://github.com/kubernetes/test-infra/pull/22503

**Comment by liggitt** [comment]
> Pass rate for the GCE e2e presubmit in Kubernetes has _tanked_

I don't think that's related to this... this was enabled since June 7th, and there are only ~4 total flakes today with the "dial timeout" signature in the PR presubmit

**Comment by cheftako** [comment]
Looking to land the context fix with https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/238 soon. Once that lands I will generate the change in K/K to pick it up and try to get it landed ASAP.

**Comment by BenTheElder** [comment]
ACK @liggitt, somewhere we have a problem, and the timeline lines up anecdotally with noticing issues.

Even if we only have 4 flakes from that timeout, the overall job runtime is getting high enough -- could still be related. failures are > 1h

**Comment by lambdanis** [comment]
Some jobs on master-blocking and master-informing dashboards are flaking with "dial timeout", e.g.:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1415461202011623424
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1413130449760292864
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1413341846817476608
so I'm adding this issue to CI Signal board.

**Comment by BenTheElder** [comment]
GCE has resumed having a pretty abysmal pass rate, I presume it was a blip when I last looked at this.

https://prow.k8s.io/?job=pull-kubernetes-e2e-kind

> Success rate over time: 3h0s: 100%, 12h0s: 100%, 48h0s: 85%

https://prow.k8s.io/?job=pull-kubernetes-e2e-gce-ubuntu-containerd

> Success rate over time: 3h0s: 63%, 12h0s: 76%, 48h0s: 60%

**Comment by liggitt** [comment]
while I think there's still a significant issue to solve, I don't think this issue is responsible for that pass rate

occurrences of the dial timeout on pull-kubernetes-e2e-gce-ubuntu-containerd:

* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=dial%20timeout&job=pull-kubernetes-e2e-gce-ubuntu-containerd
* ![image](https://user-images.githubusercontent.com/980082/125830431-18cdfaf0-a6a9-4099-a924-ecf18d6606ac.png)

occurrences of the dial timeout across all CI and PR jobs:

* https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=dial%20timeout
* ![image](https://user-images.githubusercontent.com/980082/125830252-15b4033d-2566-42d2-a85c-ab7e44b567ab.png)

**Comment by liggitt** [comment]
fwiw, all the errors seem to be hitting the "dial timeout, backstop" case

**Comment by lambdanis** [comment]
Hey, just checking in, how close are we to fixing this issue? Can I do anything to help?

We have jobs on master-blocking dashboard flaking with this error recently:
[ci-kubernetes-gce-conformance-latest-kubetest2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1416934204754628608) (Testgrid: [Conformance - GCE - master - kubetest2](https://k8s-testgrid.appspot.com/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2&width=20))
[ci-kubernetes-e2e-gci-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1416440446703374336) (Testgrid: [gce-cos-master-default](
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-default&width=20))
And 1.22 RC0 cut is planned for tomorrow, so we hope for a greener board :)

**Comment by SergeyKanzhelev** [comment]
this PR may help: #103777, can somebody apply the milestone?

**Comment by aojea** [comment]
> this PR may help: #103777, can somebody apply the milestone?

I'm afraid that those kernel panics are there since 2020 (at minimum)  :sweat: https://github.com/kubernetes/kubernetes/issues/91236#issuecomment-713619858

**Comment by dims** [comment]
https://testgrid.k8s.io/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-grpc&width=20&sort-by-failures= has been green for 3 days straight.

**Comment by jkh52** [comment]
Despite newer COS M85 image, some dial timeouts (https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=dial%20timeout) are still present.

Based on logs and timestamps, we're hopeful that after https://github.com/kubernetes-sigs/apiserver-network-proxy/pull/251 (and pick up in k/k) we will see a noticeable improvement.

**Comment by dims** [comment]
please file follow ups still all green ( https://testgrid.k8s.io/sig-api-machinery-network-proxy#ci-kubernetes-e2e-gci-gce-network-proxy-grpc&width=20&sort-by-failures= )
