### ISSUE TITLE
scheduler: `frameworkImpl.extenders` is not set

### ISSUE THREAD

**Issue by ordovicia** [kubernetes/kubernetes#102971]
#### What happened:

`frameworkImpl.extenders` here

https://github.com/kubernetes/kubernetes/blob/9d3e4eb86254a436f4bb8f2677b46704e086e3dd/pkg/scheduler/framework/runtime/framework.go#L278

is supposed to be set through `WithExtenders()`,

https://github.com/kubernetes/kubernetes/blob/9d3e4eb86254a436f4bb8f2677b46704e086e3dd/pkg/scheduler/framework/runtime/framework.go#L219

but `WithExtenders()` is not called from anywhere except tests, so `frameworkImpl.Extenders()` always returns `nil`.

https://github.com/kubernetes/kubernetes/blob/9d3e4eb86254a436f4bb8f2677b46704e086e3dd/pkg/scheduler/framework/runtime/framework.go#L136

#### What you expected to happen:

`frameworkImpl.extenders` should be set through `WithExtenders()` here.

https://github.com/kubernetes/kubernetes/blob/9d3e4eb86254a436f4bb8f2677b46704e086e3dd/pkg/scheduler/factory.go#L152

Am I missing something?

#### How to reproduce it (as minimally and precisely as possible):

N/A

#### Anything else we need to know?:

None

#### Environment:
- Kubernetes version (use `kubectl version`): master (9d3e4eb86254a436f4bb8f2677b46704e086e3dd)
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: None

**Comment by ahg-g** [comment]
Thanks for pointing that out. The plumbing of extenders to the framework impact calling extenders on preemption. That seems to be a path not covered by tests end to end.

Can you submit a PR to fix this? as you mentioned we need to pass the extenders on profile creation.

We need to patch the fix back to v1.21 and v1.20 (the release where this was refactored).

/cc @Huang-Wei

**Comment by ordovicia** [comment]
I have submitted a PR for a fix. #103019
