### ISSUE TITLE
Why not add metrics about image pulling in Kubelet 

### ISSUE THREAD

**Issue by Nebulazhang** [kubernetes/kubernetes#102947]

**Comment by n4j** [comment]
@Nebulazhang could you please fill in the below details in the template and give some more insights?
```
What would you like to be added:

Why is this needed:
```

**Comment by n4j** [comment]
> @Nebulazhang could you please fill in the below details in the template and give some more insights?
> 
> ```
> What would you like to be added:
> 
> Why is this needed:
> ```

@Nebulazhang  Could you please provide the above information?

**Comment by n4j** [comment]
@Nebulazhang For now I am closing this issue. Feel free to re-open when you are ready to provide additional information 

/close

**Comment by pacoxu** [comment]
/close

Some thoughts on the monitoring about kubelet image pulling:
- if you are using a private registry, it's easier to get image-pull status from registry metrics
- the image pull process heavily depends on the network and registry server
- another way to get some status of image pulling is by monitoring events like `Pulling`, `Pulled`.
- some container runtime have metrics that is related to image: take contained as an example: see https://containerd.io/docs/getting-started/ 
```
grpc_server_msg_received_total{grpc_method="Create",grpc_service="containerd.services.images.v1.Images",grpc_type="unary"} 1
grpc_server_handled_total{grpc_code="OK",grpc_method="Create",grpc_service="containerd.services.images.v1.Images",grpc_type="unary"} 1
```

If you met image pull hanging problem, https://github.com/kubernetes/kubernetes/issues/59376#issuecomment-867507042 may help.

**Comment by MPV** [comment]
For reference, this is discussed here now:
- https://github.com/kubernetes/kubernetes/issues/111259
