### ISSUE TITLE
 Building go targets for darwin/arm64:     ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen touch: _output/bin/prerelease-lifecycle-gen: No such file or directory make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1 make: *** [generated_files] Error 2

### ISSUE THREAD

**Issue by yaya56** [kubernetes/kubernetes#102912]
go env
GO111MODULE=""
GOARCH="arm64"
GOBIN=""
GOCACHE="/Users/sifan/Library/Caches/go-build"
GOENV="/Users/sifan/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/sifan/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/sifan/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/opt/homebrew/Cellar/go/1.16.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/homebrew/Cellar/go/1.16.4/libexec/pkg/tool/darwin_arm64"
GOVCS=""
GOVERSION="go1.16.4"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/lb/vpn9d21x1pb4536tpxcdpnpm0000gn/T/go-build3170408779=/tmp/go-build -gno-record-gcc-switches -fno-common"

I cloned the code to my /Users/me/...  and cd into kubernetes dir ,then i run "make" ,but failed with " Building go targets for darwin/arm64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
touch: _output/bin/prerelease-lifecycle-gen: No such file or directory
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
"

the branch is master  0d1dcca73bbecf5b3ef2e41e325a7bbe2012ce3e
i was working on m1 macbook

**Comment by BenTheElder** [comment]
This repo must be in a GOPATH still. I believe the developer guide covers this.

**Comment by yaya56** [comment]
> This repo must be in a GOPATH still. I believe the developer guide covers this.

echo $GOPATH
/Users/sifan/go
i moved kubernetes dir into $GOPATH/src/k8s.io/ ,still got same problem

**Comment by microyahoo** [comment]
I have come across same issue
```
+++ [0923 17:02:35] Building go targets for linux/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
> non-static build: k8s.io/kubernetes/./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
cannot find package "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen" in any of:
	/usr/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOROOT)
	/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOPATH)
!!! [0923 17:02:35] Call tree:
!!! [0923 17:02:35]  1: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:733 kube::golang::build_some_binaries(...)
!!! [0923 17:02:35]  2: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:877 kube::golang::build_binaries_for_platform(...)
!!! [0923 17:02:35]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0923 17:02:35] Call tree:
!!! [0923 17:02:35]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0923 17:02:35] Call tree:
!!! [0923 17:02:35]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
```

**Comment by microyahoo** [comment]
> I have come across same issue
> 
> ```
> +++ [0923 17:02:35] Building go targets for linux/amd64:
>     ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
> > non-static build: k8s.io/kubernetes/./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
> cannot find package "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen" in any of:
> 	/usr/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOROOT)
> 	/root/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOPATH)
> !!! [0923 17:02:35] Call tree:
> !!! [0923 17:02:35]  1: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:733 kube::golang::build_some_binaries(...)
> !!! [0923 17:02:35]  2: /root/go/src/k8s.io/kubernetes/hack/lib/golang.sh:877 kube::golang::build_binaries_for_platform(...)
> !!! [0923 17:02:35]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
> !!! [0923 17:02:35] Call tree:
> !!! [0923 17:02:35]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
> !!! [0923 17:02:35] Call tree:
> !!! [0923 17:02:35]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
> make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
> make: *** [generated_files] Error 2
> ```

The cause is that some `vendor/k8s.io/*` will be deleted after running `go mod tidy`, the build will come to normal after restore it.

**Comment by ZackHollander** [comment]
I have the same issue. `GO111MODULE=""
GOARCH="amd64"
GOBIN="/zacharyhollander/go/bin"
GOCACHE="/Users/zacharyhollander/Library/Caches/go-build"
GOENV="/Users/zacharyhollander/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/zacharyhollander/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/zacharyhollander/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.17.2/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.17.2/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/zacharyhollander/Documents/Development/FOSS/kubernetes/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5f/_1s35bvn0xqg329_n9mqj5340000gn/T/go-build112273426=/tmp/go-build -gno-record-gcc-switches -fno-common"
zacharyhollander@Zacharys-MacBook-Pro kubernetes % sudo make WHAT=cmd/kubectl`

`zacharyhollander@Zacharys-MacBook-Pro kubernetes % sudo make WHAT=cmd/kubectl
Password:
go install k8s.io/kubernetes/hack/make-rules/helpers/go2make: mkdir /zacharyhollander: read-only file system
+++ [1101 23:26:43] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
> non-static build: k8s.io/kubernetes/./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
go install k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen: mkdir /zacharyhollander: read-only file system
!!! [1101 23:26:44] Call tree:
!!! [1101 23:26:44]  1: /Users/zacharyhollander/Documents/Development/FOSS/kubernetes/hack/lib/golang.sh:730 kube::golang::build_some_binaries(...)
!!! [1101 23:26:44]  2: /Users/zacharyhollander/Documents/Development/FOSS/kubernetes/hack/lib/golang.sh:874 kube::golang::build_binaries_for_platform(...)
!!! [1101 23:26:44]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1101 23:26:44] Call tree:
!!! [1101 23:26:44]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1101 23:26:44] Call tree:
!!! [1101 23:26:44]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
`

**Comment by hicker-kin** [comment]
I have come across the same issue，where or how can i resolve it
