### ISSUE TITLE
Change default secure port to 443

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10298]
Now that nginx proxy is not the preferred configuration, there is no reason to use non-standard port 6443.
Change the default value from 6443 to 443?  This will require changes in some getting started guides.

**Comment by erictune** [comment]
this is for apiserver.

**Comment by lavalamp** [comment]
No objection to doing this, but it's not making 1.2.

**Comment by liggitt** [comment]
Low port binding requires root access or CAP_NET_BIND_SERVICE. Probably not an issue, but would be a change.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.  Probably not worth the effort, and people want to run apiserver as non root.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (161/150 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:55240 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGU6E-000PQ7-JD
	for dev@imwiz.com; Thu, 01 Jun 2017 11:41:33 -0600
Date: Thu, 01 Jun 2017 10:41:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496338879;
	bh=INRYi/xeLHGe86QCsJ434Y13stRUi2OChYwD17eQAIk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=cdtnWU9qLE83tQ8zyNrrUAQ9M56qsAOLKyU0+soG8/LfTuspTHFD6fsiw5BX3ThCn
	 gfsusMDV+JutYQK71BzvlWZXlXbt4PZmgqpO0i+vYXPJVGScfOdvXJ2YYhZ/AZSKP1
	 wOIpVmPguexpBk9FLAuin+sXBCefIhEH9sqVmYFM=

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (160/150 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:5984)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU6E-000PQ2-Rv
	for dev@imwiz.com; Thu, 01 Jun 2017 11:41:32 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=cDsw6tT2UFnM5MtoU4qP+3NVs3w=; b=eHiUh7fh5zPHulCz
	CmGJR+po9DGAwJzibFkjJOAymZ1DThsuWDPJ/WoKylDj3IDAzg9aKm91suMaj0zk
	3ked5QNJD8asD78VpGP3A0FQc4RocmsTQtYuj3cdeQY+hY2PcetPJec4avtcWE8/
	MR3EfE4UkcVD/b/WAMz8KFuhB6Y=
Received: by filter0948p1mdw1.sendgrid.net with SMTP id filter0948p1mdw1-32089-593051BF-28
        2017-06-01 17:41:19.324554442 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id M8bcYn6QRECNcSxVVVEsrA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:41:19.251 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:41:19 -0700
