### ISSUE TITLE
Umbrella Issue: Prioritization on volume capacity [beta]

### ISSUE THREAD

**Issue by cofyc** [kubernetes/kubernetes#102902]
This is an umbrella issue to track the development of the [KEP 1845: Prioritization on volume capacity](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1845-prioritization-on-volume-capacity). The goal in this issue is beta (see [criteria](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1845-prioritization-on-volume-capacity#beta)).

- [x] API changes: https://github.com/kubernetes/kubernetes/pull/99594
- [ ] Add benchmarking tests
- Turn algorithm based on feedback from developers and users
- (discuss first) Decide to support storage class weighting or not (if we should, implement it)?

cc @msau42 @jsafrane

**Comment by fengzixu** [comment]
I will check the left work in this issue
