### ISSUE TITLE
Need a `kubectl expose` flag to make a headless service

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10294]
Either --cluster-ip=None or --type=Headless or something.  Type is where we want to go, but --cluster-ip matches reality.

**Comment by bgrant0607** [comment]
In general, we should probably revisit expose flags now that the API has changed significantly.

**Comment by thockin** [comment]
We added a --type flag.  In general do we want operations that that map 1:1
to REST objects to expose flags for every field?

**Comment by bgrant0607** [comment]
Not necessarily, no. Expose is for simple use cases.

**Comment by ApsOps** [comment]
Hi guys. What's the status of this issue? I see that PR #25034 was closed but not merged.

**Comment by thockin** [comment]
That was closed for lack of owner-time.  If you have time to work on it, I think this change is relatively easy.  Adding a `--cluster-ip` should not be very hard.

**Comment by ApsOps** [comment]
@thockin Okay, thanks for the info. I've been thinking of contributing for quite some time, so I'd love to try here (I'm a golang beginner). I just setup the development environment right now.

I wanted to clear a few things here.

1. Do we try to assign any value given to `--cluster-ip`, or do we only support `--cluster-ip=None`?
2. Should we only support `--cluster-ip=None`, or `--type=Headless` as well? Personally, I think `--type=Headless` makes more sense.

**Comment by thockin** [comment]
On Mon, Jun 27, 2016 at 7:14 AM, Amanpreet Singh
<notifications@github.com> wrote:
>
> @thockin Okay, thanks for the info. I've been thinking of contributing for quite some time, so I'd love to try here (I'm a golang beginner). I just setup the development environment right now.

Go's pretty easy, you'll get the swing of it pretty quickly.  The tour
on golang.org is really quite good.

> I wanted to clear a few things here.
>
> Do we try to assign any value given to --cluster-ip, or do we only support --cluster-ip=None?
> Should we only support --cluster-ip=None, or --type=Headless as well? Personally, I think --type=Headless makes more sense.

"None" means headless.  "Headless" itself is just the silly name that
happened to stick, describing the behavior.  We should support
--cluster-ip=<IP address> too, and plumb the value straight into the
`service.spec.clusterIP` field.

**Comment by ApsOps** [comment]
@thockin Thanks. I actually sent a PR #28239 if you could take a look. It seems there's some confusion around the use of this flag.
Right now, I've added support for just `--cluster-ip=None`. I can extend it to support any IP address if we're on the right track.
