### ISSUE TITLE
jav groovy libraries are not executed in kubernetes slave pod

### ISSUE THREAD

**Issue by KamatR** [kubernetes/kubernetes#102992]
#### What happened:
we are executing our pipeline script on slave pod, which has some groovy libraries.
def     process =  ['bash', '-c', cmd].execute()
def file= new File( "test.txt" )

even though the scripts are executed from slave pod, the groovy libraries seems to be working only in our master pod.

#### What you expected to happen:
We want groovy libraries to be executed in kuberbetes slave pod too when using a pipeline script.

#### How to reproduce it (as minimally and precisely as possible):
Launch  a kubernets slave pod and try to execute pipeline script from slave pod which has some groovy libarries.

#### Environment:
- Kubernetes version (use `kubectl version`):
-Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
PRETTY_NAME="CentOS Linux 7 (Core)"

- Kernel (e.g. `uname -a`):

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
There's nothing in this issue to suggest it's a kubernetes bug and not some issue in this groovy system you're using.

kubernetes does not have any concept of "master" or "slave" pods (also we no longer use either of those terms in this project in general), and does nothing special for groovy, these are just containers.

I suggest reaching out to support channels for whatever system has this concept (it's not clear from your post where this abstraction is coming from).
