### ISSUE TITLE
TestGetServicePrincipalTokenFromMSI unit tests fails on ppc64le

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#102987]
#### Which jobs are failing:

https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

#### Which test(s) are failing:
Below two test cases started failing on ppc64le:
vendor/k8s.io/legacy-cloud-providers/azure/auth:
1. TestGetServicePrincipalTokenFromMSIWithUserAssignedID
2. TestGetServicePrincipalTokenFromMSI

#### Since when has it been failing:
6th June 2021

#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

#### Reason for failure:
```
azure_auth_test.go:73: 
        	Error Trace:	azure_auth_test.go:73
        	Error:      	Received unexpected error:
        	            	MSI not available
        	Test:       	TestGetServicePrincipalTokenFromMSIWithUserAssignedID
```

#### Anything else we need to know:
503d048...a68644b was the delta between the passing and failing tests
Started failing after https://github.com/kubernetes/kubernetes/pull/102441

**Comment by feiskyer** [comment]
Thanks for reporting the issue. This was caused by vendor changes in https://github.com/Azure/go-autorest/pull/613, which introduced external dependency on IMDS. If IMDS endpoint is not reachable, then the new logic would report error.

**Comment by feiskyer** [comment]
Filed #103018 to clean up the failed tests.
