### ISSUE TITLE
Patching a created APIService may make it unavailable

### ISSUE THREAD

**Issue by heyste** [kubernetes/kubernetes#102907]
#### What happened:
Running a new e2e test fails around 50% of the time. Test code in #100508

- Using the [TestSampleAPIServer](https://github.com/kubernetes/kubernetes/blob/6298e1fe6add48f2705c19a120d041570c7eba9a/test/e2e/apimachinery/aggregator.go#L122) conformance test to create an API Service object,
- Patch it with a label
- Test the status sub-resource (read,patch,replace)
- Finally delete the API Service object.

#### What you expected to happen:
Expect the above test code to always pass.

#### How to reproduce it (as minimally and precisely as possible):
- git clone `https://github.com/ii/kubernetes/tree/apiservice-status-endpoints`
- run the below e2e test from the kubernetes folder
```
TEST_NAME="Should be able to support the 1.17 Sample API Server using the current Aggregator"
go test ./test/e2e/ -v -timeout=0  --report-dir=/tmp/ARTIFACTS -ginkgo.focus="$TEST_NAME"
```

#### Anything else we need to know?:

```
Mar 24 11:46:26.860: FAIL: deleting flunders([{map[apiVersion:wardle.example.com/v1alpha1 kind:Flunder metadata:map[creationTimestamp:2021-03-23T22:46:26Z name:dynamic-flunde
r-782802333 namespace:aggregator-2521 resourceVersion:4 selfLink:/apis/wardle.example.com/v1alpha1/namespaces/aggregator-2521/flunders/dynamic-flunder-782802333 uid:566de910-
f6dd-4254-942c-43fadf284431] spec:map[] status:map[]]}]) using dynamic client but received unexpected error:                                                                  
the server is currently unable to handle the request 
```
Discussed in [Conformance meeting 23 March](https://www.youtube.com/watch?v=tKNDCx-DrnA&t=705s)

#### Environment:
- Kubernetes version (use `kubectl version`):
`Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: Bare metal
- OS (e.g: `cat /etc/os-release`): ubuntu 20.04
- Kernel (e.g. `uname -a`): `5.4.0-71-generic #79-Ubuntu SMP`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by heyste** [comment]
/sig api-machinery
cc @smarterclayton

**Comment by sftim** [comment]
For clarity:
/retitle Patching a created APIService may make it unavailable
