### ISSUE TITLE
One more oversight in generalization for width

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#102973]
#### What happened:
I noticed that the the code in queueset.go for calculating the dR/dt, the derivative of R(t) with respect to t, called in the code `getVirtualTimeRatioLocked`, was not updated when the generalization for width was introduced.  The `min` should be between C and the sum of seats not the number of requests.  See https://github.com/MikeSpreitzer/kube-enhancements/tree/max-min-list/keps/sig-api-machinery/1040-priority-and-fairness#fair-queuing-for-server-requests-with-equal-allocations-and-serial-virtual-execution-intended-behavior , where it says

```
mu_equal(t) = min(C, Sum[over i] rho(i,t)) / NEQ(t)
```

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
@tkashem

**Comment by tkashem** [comment]
yes, i noticed it, I am going to open a PR.

/assign
