### ISSUE TITLE
kubernetes.tar.gz not found for some versions

### ISSUE THREAD

**Issue by dgomezleon** [kubernetes/kubernetes#102942]
The kubernetes.tar.gz tarball is not present for the latest versions 1.21.2, 1.20, and 1.19.12. However, it is available for version 1.18.20, and even for 1.22.0-alpha.3

Do you plan to make it available for these or future versions or do you stop its release? Is there any other way to obtain it?

I could see this [open issue](https://github.com/kubernetes/kubernetes/issues/100460), but it does not seem to show a final decision.

**Comment by ialidzhikov** [comment]
> SIG Release and the Release Engineering team have decided to delay the upcoming 1.19.12, 1.20.8, and 1.21.2 patch releases for tomorrow, June 17.

See https://groups.google.com/g/kubernetes-dev/c/Q3gCBTGleK8/m/-KRD52uCBAAJ

**Comment by ialidzhikov** [comment]
@dgomezleon, can we now close this issue?

**Comment by dgomezleon** [comment]
Yes. Thank you for the info.
