### ISSUE TITLE
Retries for Context cancelled errors in kube-apiserver for webhook authorizer requests

### ISSUE THREAD

**Issue by Anumita** [kubernetes/kubernetes#102911]
Currently kube-apiserver only retries for the following errors when trying to send a webhook authorizer request.
https://github.com/kubernetes/kubernetes/blob/29e5e4df4b150169ed27f2c22e026800da9761cf/staging/src/k8s.io/apiserver/pkg/util/webhook/webhook.go#L65

We notice a lot of other errors as well for "Failed to make webhook authorizer request" like "context cancelled" / "context deadline exceeded" , "stream error: stream ID 11; INTERNAL_ERROR"

Just wondering if adding retries for such errors would be useful as well.

**Comment by fedebongio** [comment]
It is a utility function that is in API Server, but the definition of the behaviour should be in SIG Auth. 
/remove-sig api-machinery
/sig auth

**Comment by enj** [comment]
The context is shared for all webhook authorization SAR calls (it is the context of the incoming client request).  Once that context is canceled, retrying the SAR call will never work as they will always immediately return with "context cancelled" / "context deadline exceeded."

Closing as I believe the current code is correct.

/close
