### ISSUE TITLE
Add Pod Schedule Score into ScheduleResult and put the scheduleResult into CycleState 

### ISSUE THREAD

**Issue by lmxia** [kubernetes/kubernetes#103084]
#### What would you like to be added:
1. Add Score of the suggested host  into ScheduleResult 
2. Add the scheduleResult into cycleState, so the latter plugins can get the score.

#### Why is this needed:

The scheduler did't put the score of suggested host into scheduleResult and no plugin can get the score, however if i want to  schedule a pod across clusters, i have no way to compare with nodes in different kubernetes clusters.

/sig/scheduling
/sig/multicluster

**Comment by damemi** [comment]
This could also be relevant to improving the scheduler's logging (ie, easier access to node scores) ref: https://github.com/kubernetes/kubernetes/issues/101820

**Comment by jyz0309** [comment]
Hello! I am new to the community. And I want to try this issue. Can you or someone give me some advice? @damemi @wzshiming

**Comment by Huang-Wei** [comment]
@jyz0309 this issue needs further discussion.

> The scheduler did't put the score of suggested host into scheduleResult and no plugin can get the score, however if i want to schedule a pod across clusters, i have no way to compare with nodes in different kubernetes clusters.

[Admiralty](https://github.com/admiraltyio/admiralty) got the same challenge but figured out a way to solve this.

**Comment by lmxia** [comment]
> @jyz0309 this issue needs further discussion.
> 
> > The scheduler did't put the score of suggested host into scheduleResult and no plugin can get the score, however if i want to schedule a pod across clusters, i have no way to compare with nodes in different kubernetes clusters.
> 
> [Admiralty](https://github.com/admiraltyio/admiralty) got the same challenge but figured out a way to solve this.

That is exactly because admiralty! I am using admiralty as a multi-cluster scheduler model, and thus that maybe a way to do better schedule job.
