### ISSUE TITLE
Retain LGTM through squashes

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#103096]
#### What would you like to be added:

Configure this repo ([k/kubernetes](https://github.com/kubernetes/kubernetes)) to retain LGTM labels when people squash commits. PR https://github.com/kubernetes/test-infra/pull/9138 made this possible.

#### Why is this needed:
This feature will make it easier for people to squash commits, and should give reviewers confidence to ask other contributors to squash when appropriate.

To implement this change, make a PR against ([k/test-infra](https://github.com/kubernetes/test-infra)) that is similar to https://github.com/kubernetes/test-infra/pull/19304.

**Comment by sftim** [comment]
/sig contributor-experience
Any other SIGs?

**Comment by BenTheElder** [comment]
/sig testing
I guess? We own the tooling / repo but not the workflow expectations (contribex).

I am a big +1 for this if it's working as expected now (and it's benign if not, it just used to not detect it correctly => still need re-lgtm)

**Comment by sftim** [comment]
We (SIG Docs) already use Prow plugin / mechanism for [k/website](https://github.com/kubernetes/website), and in my experience it has worked the way I expected it to.

**Comment by MadhavJivrajani** [comment]
/triage accepted

@sftim good first issue?

**Comment by sftim** [comment]
> good first issue

I don't triage enough in _this_ repo to make that call confidently. No objection though!

**Comment by MadhavJivrajani** [comment]
Lemme mark it as help wanted since there's enough context provided 😄 
Thanks @sftim!

**Comment by gdsoumya** [comment]
Would like to take this up.

**Comment by MadhavJivrajani** [comment]
Feel free to assign it to yourself (by commenting `/assign`)

**Comment by gdsoumya** [comment]
Is there anything else required apart from adding `kubernetes/kubernetes` to `lgtm` block in `test-infra/config/prow/plugins.yaml` to enable this? @sftim @MadhavJivrajani

**Comment by BenTheElder** [comment]
Good first issue requires both documenting pointers to where to make the change and what to do and the issue should already be agreed upon a path to move forward. https://git.k8s.io/community/contributors/guide/help-wanted.md

SIG contribex needs to approve workflow changes. I think maybe this is Ok though since it doesn't change the overall workflow.

**Comment by cblecker** [comment]
Has this been brought up to contibex somewhere and I missed it?

**Comment by jberkus** [comment]
@cblecker nope.  I'm a big +1 on it.

**Comment by Atharva-Shinde** [comment]
I would love to work on this, can I go ahead?
