### ISSUE TITLE
Lack of visibility/attention to shippable/travis flakes may be hiding real bugs

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#10300]
As we've all no doubt noticed, Shippable is really flaky. What's disturbing is that it's not just `hack/test-integration.sh` (#10257), there have been unit test failures that are timeouts/panics/data races. Because Shippable is so flaky, people tend to just kick it until it goes green, but this is probably hiding real bugs. We should be tracking every Shippable flake somewhere, a docs spreadsheet would do. We're not even noticing now, and that's frightening. @ixdy or @quinton-hoole do you want to own this? A simple form/spreadsheet with build link, failed test name, and tailed output would be a good start. If it's something that takes 30s to do before hitting build again, then it's not an undue burden on reviewers.

**Comment by quinton-hoole** [comment]
Agreed.  Worthy of some investigation and data gathering.  But neither of us have bandwidth for this right now.

**Comment by wojtek-t** [comment]
We are no longer using Shippable and Travis is pretty stable now.
Closing.
