### ISSUE TITLE
Can I get the throughput with kubectl cp?

### ISSUE THREAD

**Issue by mind-mind** [kubernetes/kubernetes#103020]
#### Why is this needed:

Hello,

I would like to get the throughput from `kubectl cp `, I tried to find the command to use it, but I just found the command to get thoughput when using it with .tar file. I would like to know if I use another file, how can I get the throughput?

Thank you so much.

**Comment by n4j** [comment]
@mind-mind Do you intended to do something like this `tar cf - /tmp/foo | kubectl exec -i -n <some-namespace> <some-pod> -- tar xf - -C /tmp/bar` with other utilities perhaps `zip` or `jar`?

`kubectl cp` isn't file type specific and you can pipe `I/O` from any utility as long as they are installed on your container.

Please refer to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp

If this is not what you are looking for then can you elaborate your use case?

**Comment by mind-mind** [comment]
> @mind-mind Do you intended to do something like this `tar cf - /tmp/foo | kubectl exec -i -n <some-namespace> <some-pod> -- tar xf - -C /tmp/bar` with other utilities perhaps `zip` or `jar`?
> I tried once, but it seem doesn't work

**Comment by n4j** [comment]
@mind-mind Could you paste the exact command which you tried? 

Also, can you check if external dependencies are met in your container?

**Comment by mind-mind** [comment]
<img width="685" alt="image" src="https://user-images.githubusercontent.com/68138683/122719600-9d3fd400-d298-11eb-9c69-10ddbca75b4c.png">


I tried this one `kubectl exec <podname> -- tar cf - <file.gz> | pv | tar xf - -C <path destination>`

<img width="722" alt="image" src="https://user-images.githubusercontent.com/68138683/122720510-c44ad580-d299-11eb-8c11-4c4678fe64e0.png">

`tar cf - train-idx3.gz | kubectl -i -n /home/ubuntu test1 -- tar xf - -C /tmp/bar 
`

**Comment by n4j** [comment]
@mind-mind For your first command it looks like `train-idx3.gz` is missing in the container (the message is pretty clear)

For your second command the syntax is incorrect, it's format is `tar cf - /tmp/foo | kubectl exec -i -n <some-namespace> <some-pod> -- tar xf - -C /tmp/bar`, looking at your command you don't need to pass `-n` flag and remove `/home/ubuntu` as it's being interpreted as command.

All the issues which you have mentioned can be effectively solved if you go through the documentation [here](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cp).

Also, it would really help if you can paste the error as text within code block as it helps us in copy pasting the commands and execute it in our environment  :)

**Comment by mind-mind** [comment]
Okay. Sorry about that.

I use this command instead` pv | tar cf - train-idx3.gz | kubectl exec -i  test1 -- tar xf - -C /home/ubuntu `

This is output

`0.00 B 0:02:27 [0.00 B/s] [<=>                                                                                   ]
`

I see the data in the worker node, but I didn't get throughput to send data from the master node to the worker node.

The thing that I need is a throughput value to calculate something.

**Comment by mind-mind** [comment]
Well, seems like I found the solution. Thank you so much for your help.
