### ISSUE TITLE
nodelifecycle: not compatible with virtual-kubelet node

### ISSUE THREAD

**Issue by ZYecho** [kubernetes/kubernetes#103086]
#### What happened:
when node in not ready state, node controller will set pods which on this node to not ready state, but with virtual-kubelet node(https://github.com/virtual-kubelet/virtual-kubelet),  this logic brings side effects. The pod which run in vk node，its lifecycle is not managed by vk node，so, when vk not ready, that not means the pod is not ready. 

and when the pod not ready, it cause the endpoint changes, which will hurt the user's service.

#### What you expected to happen:
need a label, such as 【node.kubernetes.io/exclude-disruption】
when node contains this label, node controller will totally ignore the node.

#### How to reproduce it (as minimally and precisely as possible):

deploy a virtual kubelet node,  run some pods/service on it, and then let vk pod panic.

#### Environment:
- Kubernetes version (use `kubectl version`):
latest
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
virtual-kubelet is not part of the Kubernetes project, and is not supported by the Kubernetes project.

it seems like vk is responsible for emulating kubelet, not Kubernetes responsible for supporting a fake kubelet ...

**Comment by ZYecho** [comment]
> virtual-kubelet is not part of the Kubernetes project, and is not supported by the Kubernetes project.
> 
> it seems like vk is responsible for emulating kubelet, not Kubernetes responsible for supporting a fake kubelet ...

yep，but in a cloud provider environment, vk is widely used with k8s. So I hope k8s can provide a extensible mechanisms such as a label to make it more suitable.

**Comment by BenTheElder** [comment]
It's not clear to me from your post why it is that VK cannot emulate a kubelet accurately without changing Kubernetes, it might be worth elaborating a bit.

But I'm also pretty sure a label meaningful to this controller would require a https://github.com/kubernetes/enhancements, and I don't think SIG Node / Cloud Provider (I don't speak for them, but I'm somewhat familiar with these groups) likely have the free time to build such a thing without someone sort of sponsoring this effort.

**Comment by ZYecho** [comment]
> It's not clear to me from your post why it is that VK cannot emulate a kubelet accurately without changing Kubernetes, it might be worth elaborating a bit.
> 
> But I'm also pretty sure a label meaningful to this controller would require a https://github.com/kubernetes/enhancements, and I don't think SIG Node / Cloud Provider (I don't speak for them, but I'm somewhat familiar with these groups) likely have the free time to build such a thing without someone sort of sponsoring this effort.

thanks, will do it.
