### ISSUE TITLE
Start test clusters with v3 logging

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#10308]
We should modify the salt configs to setup test clusters with at least v3 logging. It is otherwise impossible to separate the realness from the rethoric. I _think_ we can achieve this with a new salt grain.

/ref https://github.com/GoogleCloudPlatform/kubernetes/issues/10282

**Comment by gmarek** [comment]
Let's discuss this tomorrow. I also think we can achieve this with a new grain, that will correspond to my idea in #8802.

**Comment by gmarek** [comment]
By tomorrow I, obviously, mean Monday:)

**Comment by bprashanth** [comment]
We already have v(4) on gce. 
GKE clusters are still at v(2), not sure why.

**Comment by fejta** [comment]
Thanks for reopening!

Multiple quarters elapsed without anyone making progress. I closed this class of bug because I want to bring attention to any that are still interesting to fix.

GKE will need to expose a way for e2e tests to configure the log level when deploying a GKE cluster

**Comment by gmarek** [comment]
Sorry - it just went off my radar, after I've done this for salt-based deployments. @bprashanth - IIUC GKE doesn't use salt. @alex-mohr

**Comment by bprashanth** [comment]
I though creating a cluster just ran kube-up with a combination of these settings + GCE scripts: https://github.com/kubernetes/kubernetes/tree/master/cluster/gke. 

But clearly there is more trickery, since we need to do things like: https://github.com/kubernetes/kubernetes/blob/master/cluster/gke/config-common.sh#L33

**Comment by kargakis** [comment]
hack/local-up-cluster is using 4 now and I think the same stands for our test jobs
