### ISSUE TITLE
Azure Exclude node from LoadBalancer lead to failed reconciliation of services 

### ISSUE THREAD

**Issue by dkistner** [kubernetes/kubernetes#103085]
#### What happened:

Exclude node from LoadBalancer (via `kubectl label node node1 node.kubernetes.io/exclude-from-external-load-balancers=true
`) leads to failing reconciliation of the existing load balancer services in the cluster with following error:

```
E0621 19:29:45.637822       1 controller.go:732] failed to update load balancer hosts for service default/
test-1: EnsureBackendPoolDeleted: failed to parse the VMAS ID : getAvailabilitySetNameByID: failed to pars
e the VMAS ID
```

The legacy provider azure is not using an AvailablilitySet as it it running with those cloudprovider config:

```
aadClientId: "my-spn-id"
aadClientSecret: "my-spn-secret"
tenantId: "my-tenant"
subscriptionId: "my-subscription"
cloud: AZUREPUBLICCLOUD
location: "westeurope"
resourceGroup: "my-rg"
routeTableName: "cluster-rt"
securityGroupName: "cluster-sg"
subnetName: "nodes"
vnetName: "cluster-vnet"
loadBalancerSku: "standard"
```

Creating new load balancer services have the effect that they are stuck in `Pending` due to same issue.

#### What you expected to happen:
Service reconciliation should succeed.

#### How to reproduce it (as minimally and precisely as possible):
- Create an Azure k8s cluster with `v1.20.6` with an Azure cloud controller manager based on legacy-cloud-provider azure in the corresponding k8s version
- Configure the cloud controller manager to use the feature gate `ServiceNodeExclusion=true`
- Create a service of type LoadBalancer in the cluster and wait until it was created
- Label a node with `node.kubernetes.io/exclude-from-external-load-balancers=true`
- Check the cloud-controller-manager logs
- New load balancer services will now stuck in Pending state

#### Anything else we need to know?:
Maybe related to https://github.com/kubernetes-sigs/cloud-provider-azure/issues/401 but should be fixed with https://github.com/kubernetes/kubernetes/pull/95542

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.6`
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug
/sig cloud-provider
/area provider/azure

cc @feiskyer, @nilo19, @andyzhangx

**Comment by ialidzhikov** [comment]
@nilo19 , thanks for the fix. Can you also create a cherry-pick to kubernetes/kubernetes@master?

**Comment by ydp** [comment]
@nilo19  we hit a similar issue in in-tree provider as well, could you please help cherry-pick the fix? Thanks.

**Comment by feiskyer** [comment]
Here are the cherry-picks to k/k:
https://github.com/kubernetes/kubernetes/pull/103600
https://github.com/kubernetes/kubernetes/pull/103599
