### ISSUE TITLE
`kubectl describe <kind>` should work with no arguments

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#10305]
Currently it complains:
```
error: you must provide one or more resources by argument or filename
```
But it's not that it can't describe multiple objects (added in #5905), because label selection works, e.g.:
```
kubectl describe pods -l kubernetes.io/cluster-service
```

Forked from #9356.

cc @bprashanth

**Comment by feihujiang** [comment]
Does it get approved? If it does, Is there anybody to work on this? If not, I'd like to work on this

**Comment by feihujiang** [comment]
@bgrant060 Maybe someone forgets resource name when using describe command, and if `kubectl describe <kind>` works, lot's of information output is a little boring. I think `kubectl describe <kind> --all` is better.  What's your opinion?

**Comment by bgrant0607** [comment]
I think it should be consistent with get.

This won't go in until after 1.0 is done.

**Comment by feihujiang** [comment]
OK, I see.  But I stick to my opinion.

**Comment by bprashanth** [comment]
This is just a nice to have because one can always do: kubectl describe nodes `kubectl get nodes | tail -n +2 | awk '{print $1}'`

**Comment by feihujiang** [comment]
@bgrant0607  The conclusion is that working with no arguments, not working with --all?

**Comment by bgrant0607** [comment]
Yes.

**Comment by feihujiang** [comment]
Sorry, I made a mistake, "get command" PR ref a wrong issue.

**Comment by kargakis** [comment]
This is fixed now
