### ISSUE TITLE
Upgrading from 1.18 to 1.19 may prevent csrapprover controller from starting

### ISSUE THREAD

**Issue by bcho** [kubernetes/kubernetes#103017]
#### What happened:

We have a couple of clusters were upgrading from 1.18 to 1.19 and saw `csrapprover` controller skipped starting due to certificates.k8s.io resource api change.

We use similar setup for these clusters:

- HA apiserver
- multiple instances of kube-controller-manager with leader election

We upgrade the cluster with rolling update each control plane components to switch from 1.18 to 1.19. We update kube-apiserver and kube-controller-manager **simultaneously**. In our repro, there are chances that we see below logs from the upgraded kube-controller-manager leader instance:

```
I0619 08:09:56.370784       1 controllermanager.go:534] Starting "csrapproving"
W0619 08:09:56.370792       1 controllermanager.go:541] Skipping "csrapproving"
``` 

These logs mean the `csrapproving` controller start up is skipped due to KCM failed to discover the CSR resource with v1 api version from kube-apiserver: https://github.com/kubernetes/kubernetes/blob/b23a96cef9b59b1559c9e9a5645017a10977216c/cmd/kube-controller-manager/app/certificates.go#L171-L175

The outcome of this behavior is that: all new CSR will not be approved:

```
NAMESPACE   NAME        AGE   SIGNERNAME                                    REQUESTOR                 CONDITION
            csr-xxxx   0s    kubernetes.io/kube-apiserver-client-kubelet   system:bootstrap:xxxx   Pending
```

From the kube-controller-manager's implementation, I think it's because during the upgrade process, the kube-controller-manager with 1.19 version discovered v1beta1 API of CSR resource from the old replica of kube-apiserver (which runs 1.18):

https://github.com/kubernetes/kubernetes/blob/b23a96cef9b59b1559c9e9a5645017a10977216c/cmd/kube-controller-manager/app/controllermanager.go#L432-L438

We can mitigate this issue by restarting the kube-controller-manager to let it rediscover the expected version of CSR resource.

#### What you expected to happen:

`csrapprover` controller should always start when upgrading Kubernetes from 1.18 to 1.19.

#### How to reproduce it (as minimally and precisely as possible):

1. running 2 or more kube-apiservers with 1.18; running kube-controller-manager with 1.18
2. upgrade these components
      - upgrade kube-controller-manager to 1.19
      - upgrade kube-apiserver to 1.19 with rolling update
3. observe kube-controller-manger's log to see if there logs telling csrapprover controller start up were skipped
      - we can do consistent reproduce by upgrading the KCM first, then upgrading the kube-apiserver. But in our real world usage, we upgrade these two components in parallel

#### Anything else we need to know?:

From our testing, we saw that the csr clean up controller were started (because it didn't check the api version). For this controller, the informer cache would fail at the first few attempts of syncing requests. But after the kube-apiserver instances are fully upgraded to 1.19, the csr clean up controller's informer cache can recover and remove approved CSR properly.

-------

IMO, since we are checking the resource api version for these controllers, is it better to change the checking logic to either:

- return error if the desired resource is not found, so we can crash the kube-controller-manager and retry start up
- retry the discovery inside each controller?

With these approaches, I think we could unblock the start up dependencies for these control plane components during the cluster upgrade scenario.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by bcho** [comment]
I think this issue is similar with #101740 #98548 . And the root cause is: https://github.com/kubernetes/kubernetes/issues/101740#issuecomment-835401680

**Comment by neolit123** [comment]
> We upgrade the cluster with rolling update each control plane components to switch from 1.18 to 1.19. We update kube-apiserver and kube-controller-manager simultaneously. In our repro, there are chances that we see below logs from the upgraded kube-controller-manager leader instance:

is thus happening because the upgrade process is not following this upgrade order strictly?
https://kubernetes.io/releases/version-skew-policy/#supported-component-upgrade-order

ideally, you must first upgrade all kube-apiservers and only then the kube-controller-managers.

**Comment by neolit123** [comment]
> These logs mean the csrapproving controller start up is skipped due to KCM failed to discover the CSR resource with v1 api version from kube-apiserver:

is the controller not started after a period of time?

looking at logs of the kubeadm upgrade test for 18->19, which also upgrade apiserver and KCM at the same time (not following the policy) i do see the controller being started:

> {"log":"I0621 12:44:26.479940       1 controllermanager.go:549] Started \"csrapproving\"\n","stream":"stderr","time":"2021-06-21T12:44:26.480316484Z"}

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-upgrade-1-18-1-19/1406952354686701568/artifacts/kinder-upgrade-control-plane-1/containers/kube-controller-manager-kinder-upgrade-control-plane-1_kube-system_kube-controller-manager-df97015c49b9a642ae66f71fcd8a444dbd28d588dd00f61d59a7fb09c1ca9da9.log

/sig cluster-lifecycle

**Comment by bcho** [comment]
> is the controller not started after a period of time?

Hi, yes, the csrapproving controller never starts, since it failed to discover the v1 CSR resource.

For your examples, I think if the kube-controller-manager starts bit earlier, it may be able to discover the v1beta1 CSR resource from the old kube-apiserver. But this depends on the timing.

**Comment by enj** [comment]
/triage accepted
/remove-sig auth

This appears to be a valid bug in the upgrade process.  I do not think any changes need to be made to the controller manager itself.

**Comment by liggitt** [comment]
> upgrade these components
> * upgrade kube-controller-manager to 1.19
> * upgrade kube-apiserver to 1.19 with rolling update

It sounds like k-c-m is hitting a 1.18 API server. If so, that is not a supported component skew. See https://kubernetes.io/releases/version-skew-policy/#kube-controller-manager-kube-scheduler-and-cloud-controller-manager for details:

> kube-controller-manager, kube-scheduler, and cloud-controller-manager must not be newer than the kube-apiserver instances they communicate with. They are expected to match the kube-apiserver minor version, but may be up to one minor version older (to allow live upgrades).

In that doc, there's a specific example of k-c-m communicating with kube-apiserver through a load balancer that calls out the requirement for all backing API server instances to be at the new version before upgrading k-c-m.

**Comment by liggitt** [comment]
While it might be more resilient to make the csrapprover controller fail to start if the certificates/v1 API cannot be found, rather than skipping, I think that's a mitigation for running an unsupported configuration.

/close
