### ISSUE TITLE
client-go: fixture data race

### ISSUE THREAD

**Issue by glazychev-art** [kubernetes/kubernetes#103148]
#### What happened:
Hello,
Found a potential data race in `client-go` testing.
There is a test `TestWatchCallNonNamespace`
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture_test.go#L56
If we update it like this (we actually can do it [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L97)):
```
...
go func() {
	err := o.Create(testResource, testObj, ns)
	if err != nil {
		t.Errorf("test resource creation failed: %v", err)
	}
	// Potential data race
	_, err = o.Get(testResource, ns, testObj.GetName())
	if err != nil {
		t.Errorf("test resource getting failed: %v", err)
	}
}()
out := <-watch.ResultChan()
// Modify received object
// Potential data race
outCasted := out.Object.(*unstructured.Unstructured)
outCasted.Object["data"] = strconv.Itoa(rand.Int())
...
```
If watcher updates received object we get a data race.

#### What you expected to happen:
No data race

#### Anything else we need to know?:
My suggestion: send copy of object here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L403
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/testing/fixture.go#L419

**Comment by caesarxuchao** [comment]
/cc @roycaihw 
/triage accepted

@roycaihw Do you remember if we fixed similar issues before?

**Comment by novahe** [comment]
Hi @glazychev-art ,The code avoiding data race seems to already exist：
https://github.com/kubernetes/kubernetes/blob/5fe522c2376e9a732a50c89f38986ce4300fd4a0/staging/src/k8s.io/client-go/testing/fixture.go#L374-L377

**Comment by glazychev-art** [comment]
Hi @novahe,
Did you run my test with `-race` flag?

Of course if I comment 
`// obj = obj.DeepCopyObject()` 
there will be data race.

But let's take a look at:
1. https://github.com/kubernetes/kubernetes/blob/5fe522c2376e9a732a50c89f38986ce4300fd4a0/staging/src/k8s.io/client-go/testing/fixture.go#L416-L420
We _store_ `obj` in `t.objects` and do `w.Add(..)` with the _same_ `obj`. So, watcher receives `obj` that is stored in `t.objects` map.

2. If we call `o.Get(...)` we take the same `obj` from `t.objects`:
https://github.com/kubernetes/kubernetes/blob/5fe522c2376e9a732a50c89f38986ce4300fd4a0/staging/src/k8s.io/client-go/testing/fixture.go#L287-L295
Therefore, if watcher modifies received `obj` in another goroutine we have data race. 

Output:
```
==================
WARNING: DATA RACE
Write at 0x00c0002ea660 by goroutine 8:
  runtime.mapassign_faststr()
      /usr/local/go/src/runtime/map_faststr.go:202 +0x0
  k8s.io/client-go/testing.TestWatchCallAndModifyNonNamespace()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/testing/fixture_test.go:112 +0x6c4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202

Previous read at 0x00c0002ea660 by goroutine 9:
  k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go:451 +0xa7
  k8s.io/apimachinery/pkg/runtime.DeepCopyJSON()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go:438 +0xc9
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:146 +0x9f
  k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopyObject()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/zz_generated.deepcopy.go:36 +0x38
  k8s.io/client-go/testing.(*tracker).Get()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/testing/fixture.go:295 +0x2bb
  k8s.io/client-go/testing.TestWatchCallAndModifyNonNamespace.func1()
      /home/art/go/src/github.com/kubernetes/kubernetes/staging/src/k8s.io/client-go/testing/fixture_test.go:102 +0x2c8

```

**Comment by novahe** [comment]
@glazychev-art  You're right ,thank you for solving my confusion.  One solution could be to copy of object
