### ISSUE TITLE
mirror pause image to local repository(AWS ECR)

### ISSUE THREAD

**Issue by vickeyrihal1** [kubernetes/kubernetes#103120]
#### What happened:
We have a k8s setup where we mirror all the public docker images to local and our cloud repository. We do this to avoid public repositories rate limiting and any other public outage cases.

As pause is a multi-arch image and we require this for both windows and linux workers, is there a way we could mirror these images to local repository servers? FYI, we don't have google cloud account.

We tried most of the options, including native buildx commands and the make commands given in your readme, but neither of them are helping. Could you help us with an easy and reliable way to mirror the multi-arch pause image?

PS - we tried related slack channel, but that didn't help as well.

#### What you expected to happen:
multi-arch image mirror to local repo and aws ecr repository.

#### How to reproduce it (as minimally and precisely as possible):
Try to mirror it at your end.

#### Environment:

NA

- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): MAC
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
> As pause is a multi-arch image and we require this for both windows and linux workers, is there a way we could mirror these images to local repository servers? FYI, we don't have google cloud account.

Yes, you don't need a google account. k8s.gcr.io is not rate limited and does not require authentication. Google hosts it for the project but there's no requirements to pull from it.

Try [`crane`](https://github.com/google/go-containerregistry/tree/main/cmd/crane) specifically [`crane copy`](https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_copy.md).

> We tried most of the options, including native buildx commands and the make commands given in your readme, but neither of them are helping.

In the pause directory (build/pause) you can build it yourself with: `make all-push REGISTRY=your-registry-host`

Could you help us with an easy and reliable way to mirror the multi-arch pause image?

> PS - we tried related slack channel, but that didn't help as well.

Which channel? If you mean cluster-lifecycle, it's the wrong SIG, pause is needed by node and build and managed by release (with some help from testing), not cluster-lifecycle

/sig node release
/remove-sig cluster-lifecycle
/assign

**Comment by vickeyrihal1** [comment]
Awesome! crane copy command helped mirroring to local repository. Thanks a lot, @BenTheElder.

**Comment by BenTheElder** [comment]
Great! You're welcome 😄
