### ISSUE TITLE
Only allow specified users to access k8s cluster

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/kubernetes#103113]
#### What would you like to be added:
X509 authenticator verifies CN
#### Why is this needed:
1. When the root CA is abused, many users can be issued. At this time, the client certificate can pass X509 authentication. Even if these users cannot operate the cluster through authorization, they can access the non-resource URL of the system:authentication group.
2. After we define a correct X509 authenticator, the front proxy authenticator cannot play its interception role (for example, only certain CNs are allowed).
3. When the X509 authenticator is turned on, there seems to be a way to only allow certain CNs to login to the k8s cluster.
https://github.com/kubernetes/kubernetes/blob/7b24c7e4a7a644bd9c4aa173d59fd5bdcddc8652/staging/src/k8s.io/apiserver/pkg/authentication/request/x509/x509.go#L198

Why not use `Verifier`, I want to do this, please convince me why not.  :- )

/sig auth 
/assign

**Comment by enj** [comment]
> When the root CA is abused

I feel like it would be best to not let this happen?  Even if you limit the usernames and/or groups that can be asserted, the allowed identities would still pose a risk.  This would also weirdly break the CSR issued client certs that are meant to be valid against the Kube API.

**Comment by njuptlzf** [comment]
> > When the root CA is abused
> 
> I feel like it would be best to not let this happen? Even if you limit the usernames and/or groups that can be asserted, the allowed identities would still pose a risk. This would also weirdly break the CSR issued client certs that are meant to be valid against the Kube API.

Yes, but from the customer's point of view, no one can determine the use of root CA. (But I met) :-(

It seems uncommon at the moment, so it is closed.

**Comment by enj** [comment]
Another issue is that limiting `CN` is not enough - that just limits usernames.  `O` is used for group membership assertion, and someone in `system:masters` can always do anything.  The `CN` restriction enforced by `verifySubject` is meant to say "a client cert with this CN from this CA can assert any identity" which is different from "only allow client certs from this CA to assert the following identities."

**Comment by njuptlzf** [comment]
> ###  a client cert with this CN from this CA can assert any identity

Yes, the purpose of this issue is to **narrow the range of users of the cluster**. 
But because it happens during `authentication`, I prefer to use `allow login` instead of calling it `assert any identity`,
and the prerequisite scenario is indeed `root CA abuse`. (uncommon)

In addition, groups may not be involved, it happens in `authorization`.

Thank you for your explanation.
