### ISSUE TITLE
Dynamically set ttlSecondsAfterFinished via mutating webhook after job completion

### ISSUE THREAD

**Issue by visit1985** [kubernetes/kubernetes#103182]
#### What happened:

In the docs for [TTL Controller](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/#ttl-controller), there is a hint about using a mutating admission webhook to set `.spec.ttlSecondsAfterFinished` dynamically after a Job has finished to choose different TTL values based on the Jobs status.

In order to modify the Job on completion, a webhook needs to be registered on `UPDATE` of the `jobs/status` subresource.

In this case the `AdmissionReview` request contains the whole Job object, but patches for `.spec.ttlSecondsAfterFinished` do not mutate the Job resource - presumably because of the subresource context.

The api server does not log any error.

An audit record is created with annotations:

```
"mutation.webhook.admission.k8s.io/round_0_index_13":"{\"configuration\":\"ttl-admission-webhook\",\"webhook\":\"ttl-admission-webhook.kube-system.svc\",\"mutated\":true}",
"patch.webhook.admission.k8s.io/round_0_index_13":"{\"configuration\":\"ttl-admission-webhook\",\"webhook\":\"ttl-admission-webhook.kube-system.svc\",\"patch\":[{\"op\":\"add\",\"path\":\"/spec/ttlSecondsAfterFinished\",\"value\":300}],\"patchType\":\"JSONPatch\"}"
```

#### What you expected to happen:

Patching of `.spec.ttlSecondsAfterFinished` should mutate the Job resource.

#### How to reproduce it (as minimally and precisely as possible):

Create a webhook which responds with:

```
{
    "apiVersion":"<apiVersion of the request>",
    "kind":"AdmissionReview",
    "response":{
        "allowed":true,
        "uid":"<uid of the request>",
        "patchType":"JSONPatch",
        "patch":"W3sib3AiOiAiYWRkIiwgInBhdGgiOiAiL3NwZWMvdHRsU2Vjb25kc0FmdGVyRmluaXNoZWQiLCAidmFsdWUiOiAzMDB9XQ=="
    }
}
```

Where patch decodes to:

```
[{"op": "add", "path": "/spec/ttlSecondsAfterFinished", "value": 300}]
```

Create a MutatingWebhookConfiguration with rule:

```
      - operations: ["UPDATE"]
        apiGroups: ["batch"]
        resources: ["jobs/status"]
        apiVersions: ["*"]
```

#### Environment:
- Kubernetes version (use `kubectl version`): v1.20.4-eks-6b7464
- Cloud provider or hardware configuration: AWS

/sig api-machinery

**Comment by fedebongio** [comment]
/assign @caesarxuchao 
(to find the right owner)
/triage accepted

**Comment by caesarxuchao** [comment]
This seems to be an issue with the TTL controller. @janetkuo can you take a look? Thanks.

**Comment by visit1985** [comment]
@janetkuo do you have a suggestion? Thanks!

**Comment by emmawang2023** [comment]
Hi @visit1985 , may I know have you got a way to fix this issue already, I face a similar issue recently. 
seems even the webhook registered on UPDATE of the jobs/status subresource, it can get the whole manifest of the job,
and I tried to add a job's metadata.lables.<sometestlabel> using webhook which is in job resource,  it could work, but for spec.xxx didn't work.  Seems if register webhook in status subresource, then the spec.xxx couldn't be modified

**Comment by visit1985** [comment]
@emmawang2023 , we ended up using a controller instead of a webhook, that watches `/apis/batch/v1/jobs` and patches the jobs based on their `.status.conditions`.

```python
from kubernetes import client, config

DEFAULT_TTL = 900
FAILED_TTL = 86400


class JobTTLReconciler:
    def reconcile(self, namespace, job):
        api = client.BatchV1Api()
        try:
            job_obj = api.read_namespaced_job(job, namespace)

            if job_obj.spec.ttl_seconds_after_finished:
                return

            if job_obj.status.conditions:
                if any(c.type == "Complete" and c.status == "True" for c in job_obj.status.conditions):
                    patch = {"spec": {"ttlSecondsAfterFinished": DEFAULT_TTL}}
                    api.patch_namespaced_job(job, namespace, patch)
                    return

                if any(c.type == "Failed" and c.status == "True" for c in job_obj.status.conditions):
                    patch = {"spec": {"ttlSecondsAfterFinished": FAILED_TTL}}
                    api.patch_namespaced_job(job, namespace, patch)
                    return

        except client.ApiException as err:
            if err.status != 404:
                raise err
```

**Comment by emmawang2023** [comment]
Hi @visit1985 , I see, thanks for your kindly reply!
