### ISSUE TITLE
Statefulset pods are not evicted when we shutdown the node manually 

### ISSUE THREAD

**Issue by skokkira** [kubernetes/kubernetes#103175]
#### What happened:

Upon manual shutdown of the node in k8s cluster, the deployment pods running in shutdown node are evicted successfully to the other node in the cluster except statefulset pods.

#### What you expected to happen:

Statefulset pods also should be evicted like other normal pods. 

#### How to reproduce it (as minimally and precisely as possible):

It can be reproudced by shutdown the any of the worker node in the cluster. 

#### Anything else we need to know?:

if we do drain on the node, The statefulset pods are evicting from worker node but if we shutdown the node then statefulset pods are going to terminated state.
Tested by removing the node from the cluster in that case pods are moved to other node or by terminating the pods gracefully pods are moved to other worker node. 
with out manual intervention we are expecting statefulset pods need to evict from one node to other node. 

#### Environment:
- Kubernetes version (use `kubectl version`):

v1.14.0

- Cloud provider or hardware configuration:
huawei cloud

- OS (e.g: `cat /etc/os-release`):
Red Hat Enterprise Linux Server release 7.9 (Maipo)
- Kernel (e.g. `uname -a`):
Linux <hostname> 3.10.0-1160.el7.x86_64 #1 SMP Tue Aug 18 14:50:17 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:

Monitoring tools(Grafana,Prometheus)

- Network plugin and version (if this is a network-related bug):
calico/cni:v3.7.4
calico/node:v3.7.4

- Others:

No issue in the cluster.

**Comment by gjkim42** [comment]
This is a known issue. I think that we have not yet found (or not needed) any graceful solution for this at the core level.

One workaround for this is to make operator that force deletes terminating pod from the non-ready node.

Related:
https://github.com/kubernetes/kubernetes/issues/74947
https://github.com/kubernetes/enhancements/pull/719

/sig apps

**Comment by michaelgugino** [comment]
This is working as designed.  The reason you see your StatefulSets go terminating but not appear elsewhere is that k8s guarantees you will not exceed the number of pods you have requested.  Since the node is no longer able to contact the cluster (since it's powered off), it never confirms that the StatefulSet pod was actually stopped.

Always wait for drain to succeed before powering off a node.
