### ISSUE TITLE
The problem of edge node replacement

### ISSUE THREAD

**Issue by beyondyinjl2** [kubernetes/kubernetes#103135]
#### What happened:
After testing, the edge gateway is broken. Change to the same node name and ip to install node. Add to the k8s cluster. The docker container deployed on the original bad gateway will not be automatically deployed to the new gateway. Re-kubectl apply deployment .yaml(Specifies the deployment of node deployment) will not be deployed either. You must first kubectl delete node to delete the node, and then add it before it can be deployed normally

#### What you expected to happen:
How to automatically replace the gateway, only need to install 节点, without other additional operations?

#### How to reproduce it (as minimally and precisely as possible):
Reinstall the node system and join the k8s cluster

#### Anything else we need to know?:
Specify the container deployed by the node, how to deploy it on the replaced gateway by yourself, do not need to delete the node first, add the node

#### Environment:
- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux rabbitmq3 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment]
hi, support questions are better suited for the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

thanks
/close
/kind support
