### ISSUE TITLE
Missing doc that static pod's spec can not reference any API objects

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#103167]
#### What happened:
I discovered by way too indirect means that a static pod can not have a ConfigMap or Secret volume.

#### What you expected to happen:
I expected such a restriction to be clearly documented in the API documentation.  Probably either in the documentation for PodSpec.Volumes or ConfigMapVolumeSource and SecretVolumeSource.

#### How to reproduce it (as minimally and precisely as possible):
Look at those places in the documentation.

#### Anything else we need to know?:
I eventually found half of this restriction mentioned at the end of https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#restrictions but that is too obscure (https://github.com/kubernetes/website/issues/28611).  There are several other doc pages on the subject that a reader encounters first, and possibly only.  In any case, the API should be self-sufficient in this matter.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-apps-bugs

**Comment by yuswift** [comment]
see kubernetes/website/pull/28623

**Comment by MikeSpreitzer** [comment]
1. The complaint here is about the comments on the API object types.  Those need to be accurate too.
2. The issue is more pervasive than I realized when I first opened this issue.  What is prohibited for static pod's spec is any reference to any other API object.
