### ISSUE TITLE
e2e framework: monitoring and metrics report

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#103145]
#### What would you like to be added:

I'd like the e2e framework to report some basic metrics for the kubernetes components during the tests.

> A summary of CPU and RAM consumption of the entire Prow test job (i.e. including all processes running inside KinD) amortized over time for the entire duration of the job would be a good start. Is that possible

xref: https://github.com/kubernetes/kubernetes/issues/101275#issuecomment-830577539

#### Why is this needed:

On hindsight, we could observe that CI jobs are very sensitive to CPU/RAM/IOPS resources, specially sig-network and sig-storage tests, that under resource constraints usage they start to flake.

This was specially evident with the latest runc regression on performance. Sig-scalability has metrics and analyse the performance of the project, however, these performance issues can be so subtle that are not easy to spot on their tests, but are enough to introduce flakiness in the CI.
 
An important number of times people spend a lot of time debugging tests without finding an explanation, we need to provide better tools and instrumentation to developers to be able to debug these flakes.

xref https://github.com/kubernetes/kubernetes/issues/101275

#### Additional Information:

This is unrelated to the metrics/instrumentation tests https://github.com/kubernetes/kubernetes/pull/102050

This is about introducing a new component (we should discuss which technology we want to use) that gathers the metrics during the job run and dumps then once the e2e tests finish.

I've did a quick example in kind with prometheus https://github.com/kubernetes-sigs/kind/pull/2190, however, sig-scalability uses another approach, the important is that the approach we choose is clean, with minimum impact on the cluster performance and the output can be easy to process.

**Comment by aojea** [comment]
/sig testing
common stakeholders, feel free to add more to the discussion
@BenTheElder @liggitt @pohly @wojtek-t @spiffxp

**Comment by wojtek-t** [comment]
@kubernetes/sig-scalability @jkaniuk @mborsz @marseel

**Comment by aojea** [comment]
@BenTheElder I have the necessary tooling to enable prometheus on kind to gather metrics and dump them at the end of the test 

https://github.com/aojea/kind-networking-plugins/tree/main/monitoring

What do you think to add it to the kind jobs? and if affirmative, what will be the best way?

I guess it should be called from https://github.com/kubernetes-sigs/kind/blob/main/hack/ci/e2e-k8s.sh

**Comment by BenTheElder** [comment]
I would really really like to stop making e2e-k8s.sh more complex before we migrate to a binary command, and I'd like to stop straying further from default configuration. Why are these metrics disabled by default?

I also think kind is probably not a very appropriate way to perform performance tests, at least specifically not when running on noisy-neighbor host environments.

**Comment by aojea** [comment]
> I also think kind is probably not a very appropriate way to perform performance tests, at least specifically not when running on noisy-neighbor host environments (as we generally do in Kubernetes CI)

is not about performance tests, is about having metrics of the system after the test , that will help to debug the tests.
The trade off is that Heisenberg principle applies "act of measurement always disturbs the object measured" 

@wojtek-t @BenTheElder the alternative is adding them as an addon :grimacing: 
 https://github.com/kubernetes/kubernetes/tree/master/cluster/addons

**Comment by smarterclayton** [comment]
I think not gathering the metrics creates some negative incentives:

1. we don’t have a way to observe the value metrics create for users during tests, so we can’t assess that value ourselves
2. we don’t have an easy way to see the metrics we generate, so it’s a problem for downstream users or test authors
3. we don’t create a culture of “metrics matter”

Since I think we’ve repeatedly said the metrics do matter, I agree with antonio that we should be taking deliberate small steps to capture, assess, and leverage those metrics ourselves.  We definitely want to be considerate of impact and cost, but we run lots of tests whose marginal utility is lower than observing some metrics over an e2e run
