### ISSUE TITLE
Enforce ReadWriteOncePod PVC access mode during scheduling

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes/kubernetes#103132]
See [KEP-2485](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2485-read-write-once-pod-pv-access-mode) for more context.

#### What would you like to be added:

The `ReadWriteOncePod` PVC access mode guarantees only a single pod can access the provided PVC as a volume. This is enforced during volume mount (in kubelet), and should be additionally enforced during scheduling.

#### Why is this needed:

Because without it the scheduler will assign pods to nodes and they will fail to start (due to failed volume attachment / mount).

#### Implementation details:

- The `NodeInfo` type will be extended to store a mapping of PVC names to the number of pods on the node consuming that PVC
- The `VolumeRestrictions` scheduler plugin is extended to have a lister for PVC and for `NodeInfo`
- During PreFilter, the plugin enumerates each `NodeInfo` checking the reference count for each PVC in the pod to be scheduled
- If the pod to be scheduled's PVC is using the `ReadWriteOncePod` access mode and that PVC is found with a reference count > 0, mark the pod `UnschedulableAndUnresolvable` (alpha)
  - For beta, we will mark the pod `Unschedulable` and implement preemption logic

**Comment by ahg-g** [comment]
thanks, please update the beta graduation criteria in the KEP

**Comment by kerthcet** [comment]
hey @chrishenzie , where are we now? I found you have a draft pr created.

**Comment by chrishenzie** [comment]
I haven't had time yet to complete this yet but it's my goal to wrap this up.

Implementing this should be doable, but there are a few other [beta graduation tasks](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2485-read-write-once-pod-pv-access-mode#beta) that need taking care of that all need completion in the same release. The last thing I was focused on was implementing a test for `NodePublishVolume()` in the [csi-sanity](https://github.com/kubernetes-csi/csi-test/tree/master/cmd/csi-sanity) utility.

**Comment by Abirdcfly** [comment]
Is there something else to be done here? 

I noticed that https://github.com/kubernetes/kubernetes/pull/103082 has been merged

**Comment by chrishenzie** [comment]
The last point in the issue description above is what remains to be done, implementing preemption logic. This is a beta graduation task; before we get to this we need to wrap up these tasks outlined here (https://github.com/kubernetes/kubernetes/issues/103132#issuecomment-999242180).

**Comment by chrishenzie** [comment]
Status update -- I'm tackling this in 1.26

**Comment by chrishenzie** [comment]
Status update -- this is deferred until 1.27, see this comment for details:
https://github.com/kubernetes/enhancements/pull/3537#discussion_r978120310

An E2E test was added here:
https://github.com/kubernetes/kubernetes/pull/112987

And I'm currently looking into scheduler integration testing.

**Comment by chrishenzie** [comment]
/remove-lifecycle stale

This is ready for 1.27, just need KEP PRR approval:
https://github.com/kubernetes/enhancements/pull/3537 (KEP)
https://github.com/kubernetes/kubernetes/pull/114051 (Scheduler preemption logic)
https://github.com/kubernetes/kubernetes/pull/114494 (E2E test update and feature gate bump to beta)
