### ISSUE TITLE
[PodSecurity] Implement remaining pod security standards checks

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103194]
Tracking issues:
  - [x] #103195
  - [x] #103197
  - [x] #103198
  - [x] #103199
  - [x] #103202
  - [x] #103196
  - [x] #103201
  - [x] #103200
  - [x] #103381
  - [x] #103388
  - [x] #103204
  - [x] #103203
  - [x] #103205
  - [x] #103271

Once all the checks have been implemented, we should do a final pass to ensure consistency of across all checks. In particular, we should look at:

- Consistency of FailureReasons in responses
- Consistency (and user experience) of FailureDetails in responses
- Comment blocks capturing the current policy (take it or leave it, but should be consistent)
- Checking of init containers (balance number of fixtures with coverage)
- Usage of sets over slices (sets shuffle the order, and are less efficient when de-duplication isn't needed)
- Consistency of check IDs

/sig auth

**Comment by tallclair** [comment]
/assign @liggitt 
(for final cleanup pass)

**Comment by liggitt** [comment]
tracking consistency/cleanup work in https://github.com/kubernetes/kubernetes/issues/103373

/close
