### ISSUE TITLE
Support Oversubscription in kubernetes

### ISSUE THREAD

**Issue by k82cn** [kubernetes/kubernetes#103141]
#### What would you like to be added:

In our scenario, the resource usage is very low comparing to resource request; so we'd like to re-use those "idle" by other low priority task, e.g. batch. In this conext, we'd like to add a new interface/api on those oversubscription resources, and some improvement to kubelet on cgroup management.

#### Why is this needed:

Oversubscription will help to improve the resource utilication of cluster which is important to our environment :)

/sig architect
/sig node
/sig scheduling

**Comment by k82cn** [comment]
We're going to draft an design on this for more comments; if anyone interests in this feature, please also share your comments and suggestion :)

**Comment by ahg-g** [comment]
wouldn't setting the pod requests to something lower and rely on a higher pod limit practically achieve overcommit semantics?

**Comment by k82cn** [comment]
> wouldn't setting the pod requests to something lower and rely on a higher pod limit practically achieve overcommit semantics?

for some online services, e.g. nginx, the resource usage are based on user's request, so it's hard for them set a "reasonable" request; to improve the QoS of service, it's usually to give enough resource to services to avoid interaction.

**Comment by adisky** [comment]
We track feature requests for Kubernetes in https://github.com/kubernetes/enhancements
KEP guide https://github.com/kubernetes/enhancements/blob/master/keps/README.md

**Comment by damemi** [comment]
It might not perfectly solve your use case, but I've discussed the [out-of-tree real load aware plugins](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/61-Trimaran-real-load-aware-scheduling) as an alternative to overcommitment, since in theory if you are scheduling based on actual load you may not need to rely on request overcommitment

**Comment by k82cn** [comment]
> It might not perfectly solve your use case, but I've discussed the [out-of-tree real load aware plugins](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/61-Trimaran-real-load-aware-scheduling) as an alternative to overcommitment, since in theory if you are scheduling based on actual load you may not need to rely on request overcommitment

Thanks very much for your input! It's not only scheduling, but also node/cgroup/kernel, as we need to reclaim the resouce back for online service and make sure not impact to QoS of online service.

**Comment by k82cn** [comment]
> We track feature requests for Kubernetes in https://github.com/kubernetes/enhancements
> KEP process https://github.com/kubernetes/enhancements/blob/master/keps/README.md

Sure, I'm going to move this request to enhancements.
