### ISSUE TITLE
ValidatingWebhook API sometimes throws connection refused and works after retry

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubernetes#103108]
#### What happened:
Created a deployment and saw that validating webhook endpoint started serving. However, when trying to apply some resources to trigger validating webhook, it throws an error, as shown below, sometimes and after retrying a couple of times, it works. 

Sometimes it throws an error `Internal error occurred: failed calling webhook "vbaremetalhost.kb.io": Post "https://capm3-baremetal-operator-webhook-service.capm3-system.svc:443/validate-metal3-io-v1alpha1-baremetalhost?timeout=10s": dial tcp 10.103.185.239:443: connect: connection refused`

I would understand that the problem is infrastructure related, if it always fails. But I don't understand what causes this intermittent failures and how it works after retrying.

Is it common problem?, is there anyone faced before?, what are the ways to debug it?

#### What you expected to happen:
Validating webhook endpoint always validates without throwing `connection refused` error.

#### Anything else we need to know?:
There are a couple of webhooks under different namespace(capi-webhook-system) and they are working. The webhook I created in different namespace (capm3-system) faces this `connection refused` problem.

#### Environment:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: minikube version: v1.20.0
- OS (e.g: `cat /etc/os-release`): Red Hat 8.3

**Comment by yuswift** [comment]
please make sure the pods behind `https://capm3-baremetal-operator-webhook-service.capm3-system.svc:443/validate-metal3-io-v1alpha1-baremetalhost?timeout=10s` are running before you create deployments

**Comment by ardaguclu** [comment]
Thanks, I'm sure because before applying it, I run;
`kubectl rollout status deployment capm3-baremetal-operator-controller-manager -n capm3-system`
