### ISSUE TITLE
Sort yaml/json fields more helpfully when printing objects

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10311]
When I do `kubectl get foo/bar -o yaml`, I see things like this:

```
apiVersion: v1beta3
foo: blah     <------------- why is this before kind and metadata?
kind: bar
metadata:
  creationTimestamp: 2015-06-24T21:09:17Z  
  name: myregistrykey  <----- why isn't this first because it is the most important metadata.
  namespace: default
  resourceVersion: "1497"
  selfLink: /api/v1beta3/namespaces/default/secrets/myregistrykey
  uid: 46703fde-1ab5-11e5-b558-42010af0cf71
zlist:
  - property: foo   
    name: bar   <---------- why isn't name always first?
```

It appears that tags are sorted alphabetically.
I'd rather always see fields that are in all objects at the top, so `apiVersion`, `kind`, and `metadata` should come before any kind-specific fields. (In the above example, field `foo` comes before `metadata`).

And I'd rather see `name` as the first property in a list for which name is the merge key.

Maybe this is just my opinion.

**Comment by bgrant0607** [comment]
Agree. We should use the same order as in types.go, which would enable us to curate the order. go-restful does that when constructing the swagger now.

This is pretty important for the cross-version conversion tool, and for generating config files more generally.

**Comment by bgrant0607** [comment]
cc @krousey

**Comment by krousey** [comment]
FWIW the json encoder does respect field order: https://github.com/golang/go/blob/master/src/encoding/json/encode.go#L603
I think the go-yaml package also respects field order: https://github.com/go-yaml/yaml/blob/v2/encode.go#L154

The problem probably happens in ghodss/yaml. https://github.com/ghodss/yaml/blob/master/yaml.go#L54 https://github.com/ghodss/yaml/blob/master/yaml.go#L80

**Comment by bgrant0607** [comment]
cc @ghodss

**Comment by caesarxuchao** [comment]
FWIW, the reflect.TypeOf() randomly changes the order of fields, so when the marshal fucntion in go-yaml package is called, the passed in reflect.Value's fields are randomly ordered:
https://github.com/go-yaml/yaml/blob/v2/encode.go#L62.
Fields are then sorted here: https://github.com/go-yaml/yaml/blob/v2/encode.go#L130

**Comment by bgrant0607** [comment]
I don't think we have time to do this for 1.0. We'll get back to it later.
