### ISSUE TITLE
[PodSecurity] baseline - apparmor

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103200]
Implement the "AppArmor" check from https://kubernetes.io/docs/concepts/security/pod-security-standards/#baseline

- [ ] implement check_apparmor.go for the baseline policy
  - fail if any apparmor annotations are present that are set `unconfined`, include the relevant container names and invalid values in the forbidden details
  - see staging/src/k8s.io/pod-security-admission/policy/check_addCapabilities.go as an example
- [ ] implement fixtures_apparmor.go
  - see staging/src/k8s.io/pod-security-admission/test/fixtures_addCapabilities.go as an example
  - generatePass should return pods with containers containing no apparmor annotations, `runtime/default` annotations for containers, for init containers, and for non-existent containers, and the same with a `localhost/foo` profile.
  - generateFail should generate test cases
    - apparmor annotation set to `unconfined` for container
    - apparmor annotation set to `unconfined` for initContainer
  - run `UPDATE_POD_SECURITY_FIXTURE_DATA=true go test k8s.io/pod-security-admission/test` to update test fixtures
  - run `go test ./test/integration/auth -v -run PodSecurity` to ensure integration tests pass

**Comment by liggitt** [comment]
/assign @tallclair 
can you verify the description of what we'll be checking here, then unassign so someone can pick this up?

**Comment by tallclair** [comment]
Updated. We decided to allow all profiles except unconfined, since the cluster admin would need to configure the profiles for them to work.

**Comment by liggitt** [comment]
thanks, should the docs be updated as well to clarify that
