### ISSUE TITLE
[PodSecurity] restricted - non-root groups?

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103204]

**Comment by liggitt** [comment]
this has a question mark in the title, and the pod security standard is marked as optional... not sure what we're doing with this one

/assign @tallclair 
to resolve

**Comment by tallclair** [comment]
From the Key (https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement#pod-security-standards):
> This optional constraint will be omitted from the initial implementation.

So I think we should close this for now.

**Comment by liggitt** [comment]
can we open a doc update to clarify what this means on the website... as an implementer, I'd have a hard time applying that guideline
