### ISSUE TITLE
pod can not delete

### ISSUE THREAD

**Issue by Imy123** [kubernetes/kubernetes#103285]
#### What happened: In my kubernetes cluster, a pod can not delete 
![image](https://user-images.githubusercontent.com/17736269/123732420-77d04d00-d8cc-11eb-8b45-1c0937c2da8e.png)
![image](https://user-images.githubusercontent.com/17736269/123732484-8f0f3a80-d8cc-11eb-8f77-094d259203e4.png)

pod is running, but when I exec delete command get `Error from server (NotFound): pods "ks-apiserver-d67e884842de45b1a492783f5920008e" not found`

#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.8
- Cloud provider or hardware configuration: Alibaba Cloud Elastic Compute
- OS (e.g: `cat /etc/os-release`): CentOS7
- Kernel (e.g. `uname -a`):  3.10.0-957.21.3.el7.x86_64
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): 
- Others:

**Comment by yuswift** [comment]
@Imy123 you missed the `-` in the pod name. Please open issues in https://github.com/kubesphere/kubesphere if you have problems on KubeSphere.

**Comment by Imy123** [comment]
> @Imy123 you missed the `-` in the pod name. Please open issues in https://github.com/kubesphere/kubesphere if you have problems on KubeSphere.

pod name is right, this pod can describe but can not delete

**Comment by yuswift** [comment]
> > @Imy123 you missed the `-` in the pod name. Please open issues in https://github.com/kubesphere/kubesphere if you have problems on KubeSphere.
> 
> pod name is right, this pod can describe but can not delete

take a look at the first picture and check the pod name and namespace
