### ISSUE TITLE
[Flaky unit test] PersistentVolume TestControllerSync

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#103221]
#### Which jobs are flaking:
pull-kubernetes-unit

#### Which test(s) are flaking:
k8s.io/kubernetes/pkg/controller/volume/persistentvolume: TestControllerSync

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103190/pull-kubernetes-unit/1408560971697360896

#### Reason for failure:
```
    framework_test.go:202: Event "Warning ClaimLost" not emitted
    framework_test.go:640: Test "5-7 - delete volume event makes claim lost, delete claim event will not report metric": events do not match
```

#### Anything else we need to know:
- https://storage.googleapis.com/k8s-gubernator/triage/index.html?pr=1&text=Event%20%22Warning%20ClaimLost%22%20not%20emitted

/sig storage

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
/reopen

I still see the flake in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106820/pull-kubernetes-unit/1467315993326915584 recently.

**Comment by jsafrane** [comment]
Fix: https://github.com/kubernetes/kubernetes/pull/107166
