### ISSUE TITLE
kubernetes fails to start with a flannel crash when using a ppp0 modem interface

### ISSUE THREAD

**Issue by jswantek** [kubernetes/kubernetes#103280]
#### What happened:
`flannel` panic on kubernetes start when using a LTE modem that enumerates as a `ppp0` device.

```
I0624 23:06:59.293981   24938 flannel.go:92] Determining IP address of default interface
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a31f90]

goroutine 20887 [running]:
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.parseAddr(0x400648bdec, 0x40, 0x40, 0x0, 0x400867a0a8, 0x4, 0x280, 0x0, 0x0, 0x400648be00, ...)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:274 +0x170
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.(*Handle).AddrList(0x6721590, 0x43eff40, 0x400f0859e0, 0x2, 0x0, 0x4, 0x2bc, 0xfe, 0x1)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:199 +0x180
github.com/rancher/k3s/vendor/github.com/vishvananda/netlink.AddrList(...)
        /go/src/github.com/rancher/k3s/vendor/github.com/vishvananda/netlink/addr_linux.go:174
github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip.getIfaceAddrs(0x400e1e22c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip/iface.go:36 +0x68
github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip.GetIfaceIP4Addr(0x400e1e22c0, 0x0, 0x0, 0x400775ee08, 0x1, 0x1)
        /go/src/github.com/rancher/k3s/vendor/github.com/coreos/flannel/pkg/ip/iface.go:40 +0x30
github.com/rancher/k3s/pkg/agent/flannel.LookupExtIface(0x400e1e22c0, 0x75ff34, 0x400cd82f08, 0x75f90c)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/flannel.go:100 +0xa8
github.com/rancher/k3s/pkg/agent/flannel.flannel(0x444d740, 0x4000e58c00, 0x0, 0x4006a5dd40, 0x34, 0x400b2e43f0, 0x2d, 0x1, 0x0)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/flannel.go:43 +0x28
github.com/rancher/k3s/pkg/agent/flannel.Run.func1(0x444d740, 0x4000e58c00, 0x4005df4380)
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/setup.go:98 +0x5c
created by github.com/rancher/k3s/pkg/agent/flannel.Run
        /go/src/github.com/rancher/k3s/pkg/agent/flannel/setup.go:97 +0x290
```

#### What you expected to happen:
Expected kubernetes to start without panic.

#### How to reproduce it (as minimally and precisely as possible):
1. Attach modem to USB port and wait for it to enumerate (have no other internet uplink interfaces) (**Note: must enumerates as a `ppp0` device.**)
2. start kubernetes

#### Anything else we need to know?:
- This issue will **not** occur with modems that enumerate as`wwan0` devices using the `qmi_wwan` driver (or equivalent)
- Issue originally discovered when using `k3s` (see: https://github.com/k3s-io/k3s/issues/3512) and noticed that Kubernetes source is based on the same https://github.com/vishvananda/netlink code so am also reporting the defect here

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
- Kernel (e.g. `uname -a`): `Linux ws-nxcore-000048B02D07627C 4.9.140-tegra #1 SMP PREEMPT Thu Jun 17 21:46:37 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others: see k3s reported defect (https://github.com/k3s-io/k3s/issues/3512) and netlink reported defect (https://github.com/vishvananda/netlink/issues/664) and netlink proposed PR (https://github.com/vishvananda/netlink/pull/665)

**Comment by neolit123** [comment]
try logging the issue in the flannel issue tracker:
https://github.com/flannel-io/flannel

flannel issues are not tracked here.

/close
