### ISSUE TITLE
[PodSecurity] Implement and test metrics

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103207]
Tasks:
  - [ ] for both pod/pod-controller admission
  - [ ] record allow/deny/exempt/error cases correctly
  - [ ] record enforce/warn/audit cases correctly

**Comment by jyz0309** [comment]
I am new to the community, and I am interested in this issue. Can you let me try it? If you can, can you give me some advice about where to add the metric? Thanks a lot! @liggitt

**Comment by tallclair** [comment]
@jyz0309 The details of the metric we'd like to record are laid out in the KEP here: https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2579-psp-replacement/README.md#monitoring

Most of the implementation should go in the `pod-security-admission.k8s.io/metrics` package (currently a placeholder: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/metrics/metrics.go).

The `RecordEvaluation` interface should probably be called from the main admission.Validate method: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/admission/admission.go#L204

I think it probably makes sense to update the interface method to take the admission attributes, and the AdmissionResponse, and then put all the logic about whether & how to record a given request behind the admission interface. In other words, something like this:

```go
type EvaluationRecorder interface {
	RecordEvaluation(attrs admission.Attributes, response *admissionv1.AdmissionResponse)
}

type PrometheusRecorder struct {
  // ...
}

func NewPrometheusRecorder(/* ... */) {
  // ...
}
```

One caveat: using `admission.Attributes` will result in a circular dependency. You can either move the existing attributes interface to the API package, or create a `metrics.Attributes` interface with the relevant subset of the admission attributes. I could be convinced by either approach.

**Comment by tallclair** [comment]
One problem with this approach: exemptions & ignored requests are not surfaced to the interface I proposed above. We don't want to duplicate that logic in the metrics recorder, so we'll need another way of piping that data through. We might need to define our own response type wrapper, something like this:

```
type Response struct {
  *admissionv1.AdmissionResponse
  Decision
}

type Decision string

const (
  DecisionAllow = "allow" // Policy evaluated, request allowed
  DecisionDeny = "deny" // Policy evaluated, request denied
  DecisionIgnore = "ignore" // Request not relevant, policy not evaluated
  DecisionExempt = "exempt" // Request exempt, policy not evaluated
  DecisionError = "error" // Error preventing evaluation, policy not evaluated
)
```

Then `Validate{Namespace,Pod,PodController}` will need to be updated to return the new response type.

**Comment by jyz0309** [comment]
@tallclair Hello! I have worked for this issue a few days. Actually, Now I can get the Operator and Resource labels in RecordEvaluation() by attrs.GetOperation() and attrs.GetResource(). But I don't know how to get other labels😭 Can you teach me how to get other labels?
