### ISSUE TITLE
ipvs: Concurrent map read and map write exist in kube-proxy

### ISSUE THREAD

**Issue by coderwangke** [kubernetes/kubernetes#103260]
#### What happened:
![image](https://user-images.githubusercontent.com/42019725/123636449-744ab080-d84f-11eb-8293-21a41889a14e.png)

#### What you expected to happen:
no panic

#### Anything else we need to know?:
https://github.com/kubernetes/kubernetes/blob/release-1.16/pkg/proxy/ipvs/graceful_termination.go#L86

#### Environment:
- Kubernetes version (use `kubectl version`): k8s 1.16

**Comment by gjkim42** [comment]
@coderwangke 
Could you fix this? I think the function needs a lock while being executed.

**Comment by MadhavJivrajani** [comment]
/triage accepted
/good-first-issue

todo: add a lock around the body of this function:
https://github.com/kubernetes/kubernetes/blob/18936c8b181de5701fba4f0b958317f9dbdab0a1/pkg/proxy/ipvs/graceful_termination.go#L84

Similar to
https://github.com/kubernetes/kubernetes/blob/18936c8b181de5701fba4f0b958317f9dbdab0a1/pkg/proxy/ipvs/graceful_termination.go#L101-L104

**Comment by aojea** [comment]
> /triage accepted
> /good-first-issue
> 
> todo: add a lock around the body of this function:
> https://github.com/kubernetes/kubernetes/blob/18936c8b181de5701fba4f0b958317f9dbdab0a1/pkg/proxy/ipvs/graceful_termination.go#L84
> 
> Similar to
> https://github.com/kubernetes/kubernetes/blob/18936c8b181de5701fba4f0b958317f9dbdab0a1/pkg/proxy/ipvs/graceful_termination.go#L101-L104

@MadhavJivrajani sig-network uses the /triage labels for tracking issues, if you accept it , it can go unnoticed and the PR may not have reviewers, so please let the SIG members handle the triage labels ... anwyay, thanks for helping out and pointing out the code problem

**Comment by MadhavJivrajani** [comment]
Oh I see, thank you for letting me know, I'll keep that in mind going forward. :)

**Comment by thockin** [comment]
Anyone actually on this?  It seems like a good fix to have for 23 and maybe backport

**Comment by EricWvi** [comment]
I'll have a try.

**Comment by aojea** [comment]
> I'll have a try.

There is a reproducer here https://github.com/kubernetes/kubernetes/pull/103287

**Comment by EricWvi** [comment]
> There is a reproducer here #103287
Oops, I just peeked at the time of the pull request and not realized that you've got such deep conversation.

**Comment by cyclinder** [comment]
hi !
someone work on this now? I would like to try it.

**Comment by PPadi** [comment]
Yes, working on it currently.

**Comment by MadhavJivrajani** [comment]
@cyclinder are you still planning to give this a shot?

**Comment by cyclinder** [comment]
@MadhavJivrajani  Is there no one working on this? If so, I'd submit a PR for it this week. :)
