### ISSUE TITLE
0.19.3 delete-pod returns a Pod representation and not a Status representation

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#10325]
Hi.  I installed k8s 0.19.3 via kube-up.sh with an AWS provider.

I must be missing something obvious, but I thought this was worth posting just in case.

I find a pod-delete via curl to the v1 REST API returns 200 OK with the Pod representation, instead of the Status representation.  

Here are the vital details:  https://gist.github.com/ae6rt/3ce32740d9595fc616e9

The way I read the API docs https://52.5.163.97/swagger-ui/#!/v1/deletePod the response should be a v1.Status object, not a Pod.

Mark

**Comment by lavalamp** [comment]
Our delete handler may send back either a status or the last known state of the object: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/apiserver/resthandler.go#L566

We should fix our docs or fix our code, it's not immediately obvious to me which is wrong, but one of them is.

**Comment by tanmaykm** [comment]
I got bitten by this just now.
It will be good to have a single clear return type.

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is re-creatable.
