### ISSUE TITLE
[PodSecurity] restricted - seccomp

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103205]
Implement the "seccomp" check from https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

- [ ] implement check_seccomp.go for the baseline policy
  - fail if any seccomp profiles are set in the pod security context or container security contexts to type=Unconfined. Include the relevant container names and invalid values in the forbidden details
  - see staging/src/k8s.io/pod-security-admission/policy/check_runAsNonRoot.go as an example
- [ ] implement fixtures_apparmor.go
  - see staging/src/k8s.io/pod-security-admission/test/fixtures_runAsNonRoot.go as an example
  - generatePass should return
    - pod that sets RuntimeDefault at pod level
    - pod that sets Localhost at pod level
    - pod that sets RuntimeDefault in container
    - pod that sets Localhost in container
    - pod that sets RuntimeDefault in initContainer
    - pod that sets Localhost in initContainer
  - generateFail should generate test cases
    - pod that sets Unconfined profile at pod level
    - pod that sets Unconfined profile in container
    - pod that sets Unconfined profile in initContainer
    - pod that doesn't set any seccomp profile (default is unconfined)
  - run `UPDATE_POD_SECURITY_FIXTURE_DATA=true go test k8s.io/pod-security-admission/test` to update test fixtures
  - run `go test ./test/integration/auth -v -run PodSecurity` to ensure integration tests pass

**Comment by liggitt** [comment]
/assign @tallclair 
can you verify the description of what we'll be checking here, then unassign so someone can pick this up?
