### ISSUE TITLE
Timeout errors in e2e tests are fantastically unhelpful

### ISSUE THREAD

**Issue by mbforbes** [kubernetes/kubernetes#10322]
We've got a failing e2e test right now. Here's what the error says:

```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/service.go:284
Expected error:
    <*errors.errorString | 0xc20802bef0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
not to have occurred
```

"Timed out waiting for the condition," huh? How helpful.

This requires you to go look a the code. And if you have skew in the code you're testing versus what you have checked out—well, have fun hunting.

This is a combination of our `WaitFor(...)` code:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/util/wait/wait.go#L78

... and our writing of test statements that look like `Expect(err).NotTo(HaveOccurred())` and `expectNoError(err)`.

+cc @quinton-hoole @ixdy to start throwing chairs around the room

**Comment by quinton-hoole** [comment]
Agreed.  This wastes a lot of peoples time.  Upped the priority for post 1.0.

**Comment by kargakis** [comment]
@kubernetes/sig-testing-misc

**Comment by ixdy** [comment]
related: #34059

**Comment by spiffxp** [comment]
/remove-priority important-soon
/priority important-longterm
/remove-lifecycle stale
/lifecycle frozen
I know this one has sat untouched forever, but it's still a real problem, and would be someplace a new contributor could definitely help us with.  You don't have to fix the tests, just help us make them  fail with more meaningful error messages.

**Comment by dhirajnair** [comment]
Hi, I would like to pick this up as my first item. This one being an old item, please confirm if this is still an issue.
I have taken fork of k8 and run the unit tests successfully.
Any pointers on how to get started with this item will be appreciated.

Thanks
D

**Comment by spiffxp** [comment]
[Yes it's still a problem](https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=timed%20out%20waiting%20for%20the%20condition)

I'm not sure that you'll run into this during unit tests.  Mostly commonly shows up in e2e tests.

Some ideas:
- allow the wait function to take a description of the condition that's being waited on
- chip away at #34059 to replace the `Expect(err).NotTo(HaveOccurred())` anti-pattern with something that describes what is being done while we expected no error

Personally I wouldn't expect a big pr solving this all at once, tinier PR's that fix spot instances of the problem are just as appreciated.

**Comment by dhirajnair** [comment]
Thanks Aaron. Will take a look at e2e and get started on this.

**Comment by dhirajnair** [comment]
I am on osx. Looks like only apiserver and controllers can be tested e2e on osx(darwin). Please correct me if I am wrong.

**Comment by louislepper** [comment]
I've raised a PR to improve the error messages in the DNS related e2e tests:

https://github.com/kubernetes/kubernetes/pull/67619

Just started learning Go/Kubernetes - all feedback welcome :-)

**Comment by nikhita** [comment]
Closing this as a dupe of https://github.com/kubernetes/kubernetes/issues/34059

/close
