### ISSUE TITLE
Custom Transport can't be used with client-go if client cert is used

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#103225]
#### What happened:
https://github.com/kubernetes/client-go/blob/v0.21.1/transport/transport.go#L36-L39

`transport.New(config *Config) ) (http.RoundTripper, error)` does not allow setting custom Transport if client cert auth is used. I would like to be able to set custom transport even when client cert auth is used.

I am using a custom transport that is used to connect to airgapped clusters (imagine my hosted web app wants to connect to a KIND cluster running on a user desktop). Using `HTTPWrappersForConfig` is not enough in this case. I need to be able to catch the final `request` object and pass it via my tunnel to talk to such air gapped clusters. I hit this issue when I call `RESTClientFor(config *Config)`.

As a side note, I tried to use the `kubernetes.New(rest.Interface)` api. That is also not possible due to #103224 . 

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by tamalsaha** [comment]
I have opened a pr https://github.com/kubernetes/kubernetes/pull/103230 to fix this.

**Comment by enj** [comment]
@tamalsaha I am going to close this out because we believe the current behavior to be correct.  Please feel free to reopen and respond to Jordan's comment in https://github.com/kubernetes/kubernetes/pull/103230#issuecomment-870680595 if you are still encountering the issue.

/close
