### ISSUE TITLE
How to make fluentd-sidecar-gcp recognize/parse logging severity

### ISSUE THREAD

**Issue by fabito** [kubernetes/kubernetes#10327]
Hi  @a-robinson ,

I'm using a **fluentd-sidecar-gcp** based container to send my application logs to GCP.
Everything is working fine.
I wanted to know what should I change in order to have the log's severities/levels properly categorized in the web GUI.
My logs look like this:

```shell
[INFO] log 1...
[DEBUG] log2...
```
Is it a fluentd configuration ?
Any help is appreciated.

regards
Fábio

**Comment by a-robinson** [comment]
Hey Fábio, I'm really sorry for letting this slip past me. Severity isn't something that we currently have support for in the default fluentd images. We'd like to do so in the future, but it's something that has to be parsed out of the log message, and supporting parsing of the incredibly diverse array of different log formats is something that's tough to do generally.

You could add it yourself for your own log types if you'd like, though. You'd have to add a `format` regex to the input configuration of fluentd. For example, if we want to collect minecraft logs (which look like `[02:31:46] [Server thread/INFO]: mootcycle left the game`), you'd add this to the input stanza:
```
format /^(?<message>\[(?<time>.*)\]\s\[.*\/(?<severity>\w+)\]:\s.*)$/
```

You can then rebuild the Docker image that includes the configuration and use it in your cluster as described in [this recent thread](https://groups.google.com/forum/#!topic/google-containers/Sqm7-V7mW7s).
