### ISSUE TITLE
`kubernetes.New(c rest.Interface) *Clientset` api is not usable

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#103224]
#### What happened:
https://github.com/kubernetes/client-go/blob/v0.21.2/kubernetes/clientset.go#L637

I am trying to use the `kubernetes.New(c rest.Interface) *Clientset` api to create a client. But it turns out that this facade api is not usable. The key issue is that I can only set one `APIPath` to the `rest.Interface` and it fails for any other api group versions with an error `the server could not find the requested resource`.

#### Anything else we need to know?:

The issue seems to be that `rest.Interface` is a "getter" type interface. To fix this, the generated code should be able to set the correct group_version (hence api path) in their respective `.New(rest.Interface)` api. So, a method like

`ForGroupVersion(gv schema.GroupVersion) rest.Interface` could be added to rest.Interface and then update the generated code to use this method to properly set the GroupVersion in their respective `.New(rest.Interface)` methods.

#### Environment:
- Kubernetes version (use `kubectl version`): any version of k8s.io.client-go
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/kind bug

**Comment by yliaog** [comment]
it is working as intended, it is not a bug. 

GroupVersion must be set when initializing RESTClient
 https://github.com/kubernetes/client-go/blob/843bb800b12ac5b3f0d273bd39f889e248b43fed/rest/config.go#L290

**Comment by liggitt** [comment]
> it is working as intended, it is not a bug.
> 
> GroupVersion must be set when initializing RESTClient
> https://github.com/kubernetes/client-go/blob/843bb800b12ac5b3f0d273bd39f889e248b43fed/rest/config.go#L290

But that means a RESTClient can only be used for a single group/version, and kubernetes.New(rest.Interface) uses the provided RESTClient for lots of group/versions, which doesn't work.

I experimented with fixing this in https://github.com/kubernetes/kubernetes/pull/97821 but didn't make a lot of progress

**Comment by aojea** [comment]
/unassign
I don't know if is worth the effort to fix the New(c rest.Interface) , hopefully with https://github.com/kubernetes/kubernetes/pull/105490 most of the issues can be solved
