### ISSUE TITLE
[PodSecurity] restricted capabilities

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103271]
Tasks:
- [x] Decide on restricted capabilities policy - discussion in https://docs.google.com/document/d/1Z26yS26z5saILHzj9nSvlbGOBJP_6c182Fl-vAi8AQY/edit
    - Proposal has buy-in
- [ ] Update Pod Security Standards documentation - https://github.com/kubernetes/website/pull/27882
- [ ] Implement `check_dropCapabilities.go`
  - in restricted v1.22+, must drop ALL, may only add back CAP_NET_BIND_SERVICE
  - sketch of this check in https://github.com/liggitt/kubernetes/commits/podsecurity-dropcap

**Comment by tallclair** [comment]
See https://docs.google.com/document/d/1Z26yS26z5saILHzj9nSvlbGOBJP_6c182Fl-vAi8AQY/edit# for proposal & discussion.

**Comment by liggitt** [comment]
/assign @tallclair 
to drive resolution of the approach

**Comment by mgutierrez98** [comment]
Hi @tallclair  I'm interested in working on this. Is this already being worked on or can I get started on it?

**Comment by tallclair** [comment]
We still need to come to a conclusion (see the doc, it's on the agenda for sig-security tomorrow). Once we have agreement on what the policy should be, I'd be happy for you (@mgutierrez98) to pick up the implementation.

**Comment by tallclair** [comment]
@mgutierrez98 we're good to move forward with the proposal in the doc (require drop `All`, allow only `NET_BIND_SERVICE` to be added back), if you still want to pick this up.

**Comment by mgutierrez98** [comment]
Will do! thank you @tallclair. It may take me a bit to get this done.
