### ISSUE TITLE
Windows container are not killed properly by liveness probe

### ISSUE THREAD

**Issue by Tarjei400** [kubernetes/kubernetes#103250]
#### What happened:
Liveness probe seems to be restarting container, however old container is still running somehow on a cluster.

#### What you expected to happen:
Old containers are stopped.

#### How to reproduce it (as minimally and precisely as possible):
Reproducing it might be a little tricky, as you cannot see old containers running using kubectl, from that perspective it seems like its all okay. Application needs to register in external system f.e consul

Used tools:
Windows nano server:2004
Consul

Application:
On startup application registers itself in consul along with health checks to be done on some port. A service can be seen in Consul, and health checks are passing.

When liveness probe fails, container is eventually marked as unhealthy, and scheduled for restart. 
Now whats funny, I see container restarted, however in consul I see old services, moreover with health checks passing, thats how I know old containers keep running. I also see metrics from old containers in grafana which are scraped by prometheus. None of this can be observed through kubectl.

#### Anything else we need to know?:
I made sure application reacts to termination signals properly and closes itself gracefully (f.e ctrl + c). It doesn't seem to make a difference for k8s

Used liveness probes: 

```
livenessProbe:
  exec:
    command:
      - cmd
      - /c
      -  dir nonexistingfileblahblha.txt
```

or

```
livenessProbe:
  exec:
    command:
      - cmd
      - /c
      -  exit 1
```

Result is still the same, probe seems to do its job, except killing old container properly (its still running)

I used 
#### Environment:
- Kubernetes version (use `1.20`):
- Cloud provider or hardware configuration: aws eks
- OS Windows_Server-2004-English-Core-EKS_Optimized-1.20-2021.05.18
- Kernel (e.g. `uname -a`):
- Install tools:
  terraform
  consul

**Comment by Tarjei400** [comment]
Update: 
 I copied shutdown.exe from windows-servercore image. I go inside container using kubectl exec -it <name> -- cmd and execute shutdown. It looks like old container gets restarted, and new one is being created :O

**Comment by Tarjei400** [comment]
Update, my bad last turns out I have duplicates registered in consul, really sorry for spamming

**Comment by wzshiming** [comment]
please reopen if you think there is a bug.

support requests should normally go here:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/remove-kind bug
/king bug
/close
