### ISSUE TITLE
ImageGC removing all unused images

### ISSUE THREAD

**Issue by snowboy932** [kubernetes/kubernetes#103255]
i have the latest  (1.21.2) version of k8s. GarbageCollector is trying to remove all docker images even if they wasnt pulled by k8s. how to disable it? i tried to configure DiskPressure and MemoryPressure to the highest threshold (including deprecated flags) but it didnt help

**Comment by neolit123** [comment]
IIRC, the image garbage collector in the kubelet is supposed to clean only images referenced in k8s objects (e.g. Pod)?
are you sure it's removing other images from the host? how to reproduce that?

/triage needs-information
/sig node

**Comment by snowboy932** [comment]
@neolit123 diskpressure removed, for example, docker private registry image.
steps to reproduce:
1. create private registry
2. add docker private registry creds as kubectl secrets 
3. call diskpressure
result: all images that not using will be removed

**Comment by SergeyKanzhelev** [comment]
I think this is by design. Kubelet doesn't keep track of the list of images that was previously used by one of containers. So there is no way to differenciate manually pulled and kubelet-pulled images.

Why do you need to pull extra images without scheduling pods? What is the scenarios?
