### ISSUE TITLE
Scheduler: add tests to verify backward compatibility of component config

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#103309]
Add a test to capture the working default config from current and previous releases to make sure that continues to load/validate successfully.

See example configurations that can be used in https://github.com/kubernetes/kubernetes/pull/101822#issuecomment-870768062

/sig scheduling
/help
/good-first-issue

**Comment by niulechuan** [comment]
Hi, my PR will little bit late, since I realized the test-infra is a quite big scope. I'm doing my best to work it out. thank for this great opportunity to learn this area.
