### ISSUE TITLE
Convert Service REST ResourceLocation() to use EndpointSlice?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#103328]
Currently uses Endpoints.  Maybe that is OK?  A comment at least...

**Comment by khenidak** [comment]
xref https://github.com/kubernetes/kubernetes/issues/105092 (watch out for in cluster endpoints)

**Comment by aojea** [comment]
hmm, let me see if I get right how this works, IIUIC the ResourceLocation returns an URL for the apiserver proxy

https://github.com/kubernetes/kubernetes/blob/b15f788d29df34337fedc4d75efe5580c191cbf3/pkg/registry/core/service/proxy.go#L59-L65

The way it is now, it always assumes the primary IP family for the service, that matches the Endpoint ... 

Checking how the proxy URLs are build I can't see how someone can use the secondary IP family or specify an IP family
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls
