### ISSUE TITLE
Windows nodes have high latency / network drops when pod is terminated on windows node

### ISSUE THREAD

**Issue by tcope0094** [kubernetes/kubernetes#103312]
#### What happened:
Terminating a pod on a windows node causes the network latency to spike and sometimes timeout completely on all windows nodes in the cluster.
The linux nodes running on the same hosts / subnet / VLAN as the windows nodes experience no network issues at all.

#### What you expected to happen:
Deleting a pod has no adverse impact on networking of the node the pod was terminated on or any other windows node.

#### How to reproduce it (as minimally and precisely as possible):
Single master node, multiple windows worker nodes all running flannel, startup pods on the windows nodes, start pinging any of the windows nodes, terminate one of the pods on a windows node and observe the response time of the ping replies.

#### Anything else we need to know?:
All nodes are Hyper-V VMs in our local datacenter.
85 Node cluster, about half ubuntu, half windows server 1909, single master node.
Running flannel as the network plugin.

#### Environment:
- Kubernetes version (use `kubectl version`): 
   1.18.2

- Cloud provider or hardware configuration: 
   All nodes are Hyper-V VMs.

- OS (e.g: `cat /etc/os-release`): 
   Master node and linux worker nodes: Ubuntu 18.04.4
   Windows worker nodes: Windows Server 1909

- Kernel (e.g. `uname -a`):
   Master node and linux worker nodes: 4.15.0-123-generic
   Windows worker nodes: 10.0.18363.778

- Network plugin and version (if this is a network-related bug):
   Linux: flannel: v0.12.0
   Windows: flannel: v0.13.0   

- Others:
   Flannel is running in l2bridge mode

**Comment by immuzz** [comment]
@sbangari can you please take a look or assign someone else from your team?

**Comment by tcope0094** [comment]
More details:
We've observed that when a pod is terminated, the CPU utilization of the HNS process on all windows nodes will spike sharply for a few seconds which is the same time when the response times increase sharply. 
We have plans to build out a new cluster using the newest windows SAC 20H2, which may fix the issues.
