### ISSUE TITLE
Allow pods to enter host's cgroup namespace

### ISSUE THREAD

**Issue by aditighag** [kubernetes/kubernetes#103363]
#### What would you like to be added:

Kubernetes currently exposes `hostPID` and `hostNetwork` configurations for pods to enter host's PID and network namespaces respectively. Allow pods to enter host's cgroup namespace as well. 

#### Why is this needed:

CNIs like Cilium attach BPF programs to cgroups to enable [socket-based load-balancing](https://docs.cilium.io/en/v1.10/gettingstarted/kubeproxy-free/) using eBPF. BPF cgroup programs can also be used to collect [statistics](https://kubernetes.io/blog/2017/12/using-ebpf-in-kubernetes/#pod-and-container-level-network-statistics). In order to do that, CNI agents mount cgroup2 filesystem on the underlying kubernetes node. With cgroup v2 adoption, container runtimes have switched the default cgroup namespace mode to [private](https://docs.docker.com/config/containers/runmetrics/#running-docker-on-cgroup-v2). In this mode, every pod has its own cgroup namespace. As a result, CNI agents end up attaching eBPF programs at their virtualized cgroup root, and the attached eBPF programs aren't effective for other pods. 
In Cilium, we've worked around this problem by mounting cgroup2 fs on the underlying host in an init container using `nsenter` command, with cgroup and mount namespaces as enterable. However, this requires host's `/proc` to be mounted in an init container, and thus, may have security implications. Alternatively, we also allow users to specify mount point on the host where cgroup2 fs is already mounted, and we volume mount this inside the Cilium pod. However, this is a manual step since cgroup2 filesystem may not always be mounted. Mount points can also be distribution dependent. 

If Kubernetes allowed pods to enter host's cgroup namespace, we could deploy an CNI agent init container that'll be able to mount cgroup2 filesystem on the host without having to mount `/proc` on the host.

**Comment by neolit123** [comment]
/sig network
for the CNI part of the topic.

**Comment by fasaxc** [comment]
Calico also uses the cgroupv2 hooks so we'd also like to have a solution for this.

**Comment by thockin** [comment]
This is interesting.  It "feels different" than host net or host IPC or host PID.  Those are meaningful independent of isolation - we know what PIDs and IPC and Networks are.  Cgroups, being part of isolation stack feels like more significant abstraction leak.  I am not sure it IS different, but it feels that way.

Curious to hear node folks' thoughts.

**Comment by sftim** [comment]
This feels like the kind of area where a DaemonSet might not be the right fit. Some things (eg the kubelet) you just have to deploy using mechanisms other than Pods.

**Comment by thockin** [comment]
Not using pods *significantly* raises the difficulty of doing
"interesting" things automatically.  Suddenly it's not something a 3rd
party can provide, it has to be integrated into the node bootstrap.
I'm reluctant to shut that door unless it's really the least-worst
option.

**Comment by BenTheElder** [comment]
Why shouldn't the host be responsible for mounting the cgroups filesystem though ...?

Can CNI not just bind-mount the common mount points by default and locate which one has it or require the user to mount it to a sane somewhat common location?

How is being able to make mounts on the host not a huge security hole comparable to a priv pod?

CNI daemonsets are also already quite privileged typically including e.g. writing executables to the host (to be invoked by the container runtime) and controlling in-cluster networking ...

**Comment by aditighag** [comment]
I would like to give some more context to address the potential concerns expressed around security. Cgroup namespaces virtualize the view of a process's cgroups [1] which means they only limit the cgroup hierarchy as seen by a process. When container runtimes like Docker run in the private cgroup namespace mode, pods are created in nested cgroup hierarchies. However, please note that kubelet still sees the parent cgroup hierarchy for these pods, and will continue to enforce cgroup resource (e.g., cpu, memory) limits.

>Why shouldn't the host be responsible for mounting the cgroups filesystem though ...?

The description has more details. Also, see this comment by @thockin - https://github.com/kubernetes/kubernetes/issues/103363#issuecomment-876815919.

[1] https://man7.org/linux/man-pages/man7/cgroup_namespaces.7.html

**Comment by BenTheElder** [comment]
> > Why shouldn't the host be responsible for mounting the cgroups filesystem though ...?
> 
> The description has more details.

I don't see any other than:

> However, this is a manual step since cgroup2 filesystem may not always be mounted. Mount points can also be distribution dependent.

Which doesn't seem to be a strong argument for why Kubernetes should not push back and expect:
1) it should be mounted
2) mounts should be in one of at most a few locations, not arbitrary.

2\) at least seems very reasonable to expect or else require the user to configure in the CNI.
1\) is unclear, why are we supporting hosts running with cgroupsv2 that do not mount cgroupsv2 at all?

**Comment by khenidak** [comment]
I believe this should be up to the user to mount the cgroup fs into the pod which will have to be running as a privileged pod anyway. I understand the use case but it is really - so far at least - a slim use case very specific certain BPF scenarios. 

I think we should close this issue. Re-open as more information/use-cases arrise.

/close
