### ISSUE TITLE
Kubelet is not reporting all metrics

### ISSUE THREAD

**Issue by rdrgporto** [kubernetes/kubernetes#103347]
#### Environment:
- **Kubernetes version**: 1.21.2
- **Cloud provider or hardware configuration**: Bare metal (VMware)
- **OS**: Ubuntu 18.04.5 LTS
- **Kernel**: 4.15.0-147-generic
- **Install tools**: Kubeadm
- **Network plugin and version (if this is a network-related bug)**: Weave 2.8.1
- **CRI**: Containerd 1.4.6

Hi, everyone

I have installed **Kubernetes 1.21.2 with Containerd 1.4.6** in order to test the new version. I found out that **Kubelet** does not provide metrics about containers's memory. Here you are an example:

```
   "containers": [
    {
     "name": "kube-controller-manager",
     "startTime": "2021-06-29T08:30:24Z",
     "cpu": {
      "time": "2021-06-29T08:52:04Z",
      "usageNanoCores": 14491661,
      "usageCoreNanoSeconds": 21133058342
     },
     "memory": {
      "time": "2021-06-29T08:52:04Z",
      "workingSetBytes": 44150784
     },
     "rootfs": {
      "time": "2021-06-29T08:51:59Z",
      "availableBytes": 40293728256,
      "capacityBytes": 47015370752,
      "usedBytes": 69632,
      "inodesFree": 2675867,
      "inodes": 2816016,
      "inodesUsed": 20
     },
     "logs": {
      "time": "2021-06-29T08:52:04Z",
      "availableBytes": 40293728256,
      "capacityBytes": 47015370752,
      "usedBytes": 98304,
      "inodesFree": 2675867,
      "inodes": 2816016,
      "inodesUsed": 2
     }
    }
  ]
```

I attach to the issue **a markdown regarding my Kubernetes installation** and **Kubelet's output**: [kubernetes-installation.zip](https://github.com/kubernetes/kubernetes/files/6740184/kubernetes-installation.zip).

I have tested with **Docker 19.03.15** and **Kubernetes 1.21.2** and it works. 

I am not able to figure out the issue which I have. Any help ?

Thanks in advance

**Comment by ehashman** [comment]
It's unclear from the first comment or attachment where you are pulling these stats from.

Kubernetes does not use issues on this repo for support requests. If you have further questions on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close

**Comment by ehashman** [comment]
This might be a duplicate of #103366?

**Comment by rdrgporto** [comment]
Hi, @ehashman 

It has the same behaviour.
