### ISSUE TITLE
When set gcc.terminatedPodThreshold = 0, we should delete all terminated pods, not disable pod garbage collector

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#103330]
#### What happened:
In production environment, users do not want to leave any terminated pods.

#### What you expected to happen:
when set gcc.terminatedPodThreshold = 0, we should delete all terminated pods.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
note: this is a breaking change https://github.com/kubernetes/kubernetes/pull/103329#issuecomment-871613173

**Comment by BenTheElder** [comment]
per https://github.com/kubernetes/kubernetes/pull/103329#issuecomment-872562866
/close
