### ISSUE TITLE
[PodSecurity] baseline - seccomp: forbid explicit unconfined

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103388]
Runtimes (cri-o & containerd) let you override the default seccomp profile, and there is a new proposal to change the default profile (https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2413-seccomp-by-default). To respect these changes to the default in the baseline profile, we should forbid _explicitly_ setting the seccomp profile to unconfined.

Note: this is different from the restricted check, which _requires_ the profile to be **set** to something other than unconfined.

**Comment by liggitt** [comment]
it should be its own check
