### ISSUE TITLE
[PodSecurity] prioritize checking unique or controllerless pods when checking inside a namespace

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#103304]
When updating policy labels on a namespace, existing pods are evaluated to see if they are compatible with the new policy.

If there are too many pods, or if evaluation takes too long, we short circuit and warn that not all pods were checked.

For that reason, we want to prioritize checking a variety of pods before checking essentially identical pods, so that unique warnings can be surfaced before reaching the pod count cutoff or evaluation timeout.

Pods created by the same controller are most likely to be identical (e.g. replicas from a replicaset or job, copies of pods from a statefulset or daemonset, etc)

```
evaluatedControllers := map[metav1.OwnerReference]bool{}
evaluatedPods := 0
skippedPods := sets.NewInt()
pods := ... get pods in the namespace
for i, pod := range pods {
  if controller, hasController := (... find metadata.ownerReference with controller=true); hasController {
    if evaluatedControllers[controller] {
      // we've already evaluated a pod for this controller... come back to it if we have time
      skippedPods.Insert(i)
      continue
    }
    evaluatedControllers[controller] = true
  }
  // evaluate, short-circuiting and warning on timeout or exceeding max pod count
  ... := evaluatePod(ctx, pod, ...)
}

// if we made it through all unique or controllerless pods, go back over the ones we skipped
for i := range skippedPods {
  // evaluate, short-circuiting and warning on timeout or exceeding max pod count
  ... := evaluatePod(ctx, pods[i], ...)
}
```

cc @tallclair

**Comment by akshitgrover** [comment]
@liggitt 
This is an interesting fix
I'd like to take this up
Can I take this up?
I am fairly new to Kubernetes source code so might need some help

**Comment by akshitgrover** [comment]
I am guessing this where the logic you mentioned should be implemented right?
https://github.com/kubernetes/pod-security-admission/blob/c669f400f4694fcd34422dba42f8c375f2e746b2/admission/admission.go#L381

**Comment by liggitt** [comment]
thanks for the interest; this is targeted at the beta version... right now, effort is going toward the alpha-blocking work for 1.22

**Comment by akshitgrover** [comment]
Should I wait for the code freeze before working on this?
Sorry for lame questions

**Comment by liggitt** [comment]
> Should I wait for the code freeze before working on this?

If you want to start looking at it, that's fine, but it's possible the code in the ValidateNamespace function will change before we're ready to start merging 1.23 work, and there isn't really reviewer bandwidth to take a look at work-in-progress stuff for next release yet.

**Comment by akshitgrover** [comment]
Sure, I'll just for code freeze before I start with implementation
By the time I'll just assign this to myself
/assign

**Comment by akshitgrover** [comment]
@liggitt 
Does it make sense to take it up now?
I think we already have a couple of RC builds after the code freeze

**Comment by liggitt** [comment]
sure, it's fine to start work in a branch in your fork and have a WIP PR open, even before master reopens for 1.23 work

**Comment by akshitgrover** [comment]
Awesome, I'll start working on it
Thank you

**Comment by jyz0309** [comment]
Hello! @akshitgrover Are you still working on this? If you don't have time, I can take this issue. If not, maybe I can give some help😊

**Comment by akshitgrover** [comment]
@jyz0309 
Since this was not an urgent issue
I was working on some other issues last week
I have started on this, Will be raising a PR maybe today or tomorrow
I Will ask you if I get stuck
Thank you
