### ISSUE TITLE
kubectl top pod shows wrong memory usage

### ISSUE THREAD

**Issue by sechunOH** [kubernetes/kubernetes#103352]
#### What happened:
"kubectl top pod" shows different memory usage from its in pod.
I think that it shows with adding cache memory.

Is this usage metric used to HPA?
If so, how can I find right value of memory request for my applications?

```
# kubectl top pod
{my_pod_name}        9m           1394Mi

# ps -eo user,pid,rss,pmem,pcpu,cmd --sort -rss
USER       PID   RSS %MEM %CPU CMD
root         6 712188  2.1 0.8 java -jar .... <-- my java application
root      5518  3544  0.0  0.0 /bin/bash
root      5523  3104  0.0  0.0 ps -eo user,pid,rss,pmem,pcpu,cmd --sort -rss
root         1   700  0.0  0.0 /bin/sh -c java -jar ....
```
#### What you expected to happen:
HPA uses memory usage without cache.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by serathius** [comment]
Assuming that you are using Metrics Server, https://github.com/kubernetes-sigs/metrics-server/blob/master/FAQ.md#how-memory-usage-is-calculated

**Comment by ehashman** [comment]
/kind support
/close

Thanks @serathius for answering.

Kubernetes does not use issues on this repo for support requests. If you have further questions @sechunOH,  please visit our [forums](https://discuss.kubernetes.io/).
