### ISSUE TITLE
Add force-eviction-seconds option to kube-controller-manager

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#103356]
I am saying [taint-based eviction](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions), the other one(no-taint-based eviction) is out of this feature request.

Currently, all the pods are scheduled for deletion by the node lifecycle controller if their nodes are tainted by the `NoExecute` effect for longer than `tolerationSeconds`.

I understand that pod eviction of node lifecycle controller helps in the case that the pods managed by deployments(replicaset) should be respawned on the other nodes. However, that is just an extra effect of the pod eviction.

I think pod eviction itself is incomplete: it tries to terminate pods but it may not succeed because it can be triggered when the kubelet which is responsible for pod termination is not online. I understand that scheduling pod termination works if the node(kubelet) came back, but we have to consider the case that the node never came back.

I think that kubernetes should be able to force evict pods.

#### What would you like to be added:

Add force-eviction-seconds option to kube-controller-manager(nodelifecycle controller)

#### Why is this needed:

- To supplement the incompleteness of the current `taint based eviction` mechanism of the node lifecycle controller
- To respawn pods managed by statefulset
    - https://github.com/kubernetes/kubernetes/issues/103175
    - https://github.com/kubernetes/kubernetes/issues/74947
    - https://github.com/kubernetes/kubernetes/issues/74689
    - https://github.com/kubernetes/enhancements/pull/719
    - I’ve seen many questions about this in the sig-node slack channel

**Comment by gjkim42** [comment]
/cc @ehashman @SergeyKanzhelev @liggitt
Could you PTAL?

**Comment by gjkim42** [comment]
Hi @jingxu97 (the original author of ForceEviction)
Are you working on this?

**Comment by gjkim42** [comment]
Closed in favor of the [pod safety design](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/pod-safety.md).

**Comment by jhoblitt** [comment]
The design proposals have been removed.  Is there any current motion on similar functionality to reschedule a statefulset when a node is offline?
