### ISSUE TITLE
Kubelet should not report metrics from init containers

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#103368]
#### What would you like to be added:
as discussed in issue [#792](https://github.com/kubernetes-sigs/metrics-server/issues/792) and[#796](https://github.com/kubernetes-sigs/metrics-server/issues/796) , we get the metrics of terminated container. metric information about terminated pods is expected? If so,  that has changed recently?
#### Why is this needed:
 Kubelet endpoints and CRI metrics protos should report metrics for terminated container should be standardized

**Comment by dashpole** [comment]
We only provide metrics for non-terminal pods: https://github.com/kubernetes/kubernetes/pull/79409

We only provide metrics for running containers: https://github.com/kubernetes/kubernetes/pull/83504

**Comment by serathius** [comment]
ok, looks like this is a bug in container runtime CRI metrics implementation.

**Comment by haircommander** [comment]
also cc @bobbypage as both of those examples are from cadvisor (as cri-o uses the cadvisor stats provider)

**Comment by serathius** [comment]
/retitle Kubelet should not report metrics from init containers

**Comment by haircommander** [comment]
I believe this is only a bug in the cadvisor stats provider, as there is [code](https://github.com/kubernetes/kubernetes/blob/c75d254beb662ea73736d2f123d0382b7f91dfbd/pkg/kubelet/stats/cri_stats_provider.go#L810) in the cri stats provider code to handle this. Between the dockershim deprecation and the (hopeful) promotion of PodAndContainerStatsFromCRI to beta in 1.24, I am wondering if it is worth the time to fix this in the kubelet. dockershim and CRI-O are the last users of the cadvisor stats provider, and CRI-O will use CRI stats when PodAndContainerStatsFromCRI is true by default.

If one were to fix this, I think the spot would be in [this code](https://github.com/kubernetes/kubernetes/blob/c75d254beb662ea73736d2f123d0382b7f91dfbd/pkg/kubelet/stats/cadvisor_stats_provider.go#L390) which according to [this comment](https://github.com/kubernetes/kubernetes/blob/659c7e709f3b7f5f2a25e456525cd8747f2e68cc/pkg/kubelet/stats/cadvisor_stats_provider.go#L327) (which was lost in [this refactor](https://github.com/kubernetes/kubernetes/issues/103423) but the code seems to be the same) should filter out terminated containers, but doesn't seem to be doing so.

**Comment by lbogdan** [comment]
This seems to be fixed for me in 1.23 (using `cri-o`, so as per https://github.com/kubernetes/kubernetes/blob/v1.23.5/pkg/kubelet/cadvisor/util.go#L76-L79 , `kubelet` is still using legacy `cadvisor` stats), and the only "recent" PR touching `cadvisor_stats_provider.go` related to pod stats is #103423, so I guess that refactor actually fixed filtering out terminated containers, @haircommander ? Either this, or it was fixed in `cadvisor` in the meanwhile. 🙂

**Comment by lbogdan** [comment]
Doing a bit more digging (I just can't help it!), here https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/pkg/kubelet/stats/cadvisor_stats_provider.go#L90 (which in turn calls `cadvisor` directly here https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/pkg/kubelet/stats/cadvisor_stats_provider.go#L405-L409
), `infos` doesn't contain any exited init containers data, so the filtering is done by `cadvisor`.

`cadvisor` was bumped in https://github.com/kubernetes/kubernetes/pull/106282 from v0.39.2 to v0.43.0, so I'm guessing the fix should be somewhere in there.
