### ISSUE TITLE
network plugin is not ready & cni config uninitialized

### ISSUE THREAD

**Issue by ZW007** [kubernetes/kubernetes#103324]
#### What happened:
When I do `kubectl get nodes` The Worker node is not ready though the master node is ready. 
#### What you expected to happen:
The worker node should be ready. 
#### How to reproduce it (as minimally and precisely as possible):
I have added flannel by `sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml` on the master node after `sudo kubeadm init --pod-network-cidr=10.244.0.0/16 ` 
#### Anything else we need to know?:
There is no `KUBELET_NETWORK_ARGS` in my `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` so I cannot remove it as suggested by #48798

Information I got from the master node when do get pods and get nodes. 
[![enter image description here][1]][1]

[![enter image description here][2]][2]

From the worker node, I got this when do `journalctl -r -u kubelet`
[![enter image description here][3]][3]

As they told me, `container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized` Also, worker node says `Unable to update cni config" err="no networks found in /etc/cni/net.d` Should them be the reasons? My `/etc/cni/net.d` folder does not have a `net.d` file
#### Environment:
- Kubernetes version (use `kubectl version`): v1.21.1
- Cloud provider or hardware configuration: X86_64
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 master, Ubuntu 16.04 worker node
- Install tools: Kubeadm 
- Network plugin and version: flannel sudo kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- Others: bare metal 

  [1]: https://i.stack.imgur.com/9X290.png
  [2]: https://i.stack.imgur.com/EpenA.png
  [3]: https://i.stack.imgur.com/QhJtO.png

**Comment by pacoxu** [comment]
/sig network
/kind support

Please check why the flannel pod not started on that node.

**Comment by BenTheElder** [comment]
/remove-kind bug
This is not a bug in Kubernetes. Flannel needs to install the CNI config so containerd can start, neither of these are part of Kubernetes.

The Kubernetes project does not use issues for support and does not support third party projects like flannel.

Please file an issue with flannel, or see:
- the forums https://discuss.kubernetes.io/
- stackoverflow https://stackoverflow.com/search?q=kubernetes
