### ISSUE TITLE
When use the remote container runtime, image gc manager might delete the sandbox image

### ISSUE THREAD

**Issue by Hanaasagi** [kubernetes/kubernetes#103494]
#### What happened:

When run kubelet with `--container-runtime="remote"`, the `ImageGCManager` does not use the correct sandbox image from container runtime. In `ImageGCManager`, the sandbox image should be kept on the node. If we don't get the configuration from container runtime, it will cause the sandbox image to be deleted in some cases.

https://github.com/kubernetes/kubernetes/blob/26bdfbc0abd4bc9024397ff7b566b7c41d4467ee/pkg/kubelet/images/image_gc_manager.go#L209-L217

In kubernetes v1.21.1, the default sandbox image value is "gcr.io/pause:3.4.1", but Containerd use the `k8s.gcr.io/pause:3.5` in recent version.

#### What you expected to happen:

kubelet should know the real sandbox image that container runtime using.

#### How to reproduce it (as minimally and precisely as possible):

Use the containerd as the Container Runtime. Change the GC threashold value in `/var/lib/kubelet/config.yaml` and run kubelet with `--container-runtime="remote"`.

```
imageGCHighThresholdPercent: 2  
imageGCLowThresholdPercent: 1  
```

Deploy a nginx pod and then delete it. The sandbox image will be deleted.

#### Anything else we need to know?:

In CRI v1alpha2 proto, there is a `info` field in `Status` response. Containerd returns a `sandboxImage` field. But it's a arbitrary map, depends on the implementation of Container Runtime.

https://github.com/kubernetes/kubernetes/blob/26bdfbc0abd4bc9024397ff7b566b7c41d4467ee/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto#L1249-L1257
```
message StatusResponse {
    // Status of the Runtime.
    RuntimeStatus status = 1;
    // Info is extra information of the Runtime. The key could be arbitrary string, and
    // value should be in json format. The information could include anything useful for
    // debug, e.g. plugins used by the container runtime.
    // It should only be returned non-empty when Verbose is true.
    map<string, string> info = 2;
}
```

#### Environment:
- Kubernetes version (use `kubectl version`): Kubernetes v1.21.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): Debian GNU/Linux 11 (bullseye)"
- Kernel (e.g. `uname -a`): Linux 5.10.0-7-amd64 SMP Debian 5.10.40-1 (2021-05-28) x86_64 GNU/Linux
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others: containerd version v1.5.2 36cc874494a56a253cd181a1a685b44b58a2e34a

**Comment by neolit123** [comment]
related to:
https://github.com/kubernetes/kubernetes/issues/81756

**Comment by pacoxu** [comment]
We can config kubelet with flag `--pod-infra-container-image`. GCmanager will use it or default one.
https://github.com/kubernetes/kubernetes/blob/75d571a10be4db7a4b932b4131e8f1095f6c46bf/pkg/kubelet/config/flags.go#L95

```
      --pod-infra-container-image string                         Specified image will not be pruned by the image garbage collector. When container-runtime is set to 'docker', all containers in each pod will use the network/ipc namespaces from this image. Other CRI implementations have their own configuration to set this image. (default "k8s.gcr.io/pause:3.4.1")
```
https://github.com/kubernetes/kubernetes/blob/7229ea343dd649f9a6c20fa1fd6b13e602f3f082/cmd/kubelet/app/options/container_runtime.go#L29-L36

Containerd configuration in `/etc/containerd/config.toml`
```
[plugins."io.containerd.grpc.v1.cri"]
sandbox_image = "k8s.gcr.io/pause:3.2"
```

**Comment by adisky** [comment]
There is already a proposal on adding a pinned images to CRI specs, Image marked as pinned image will not be garbage collected.
https://github.com/kubernetes/enhancements/pull/2694/files

**Comment by pacoxu** [comment]
It targets 1.22 but the k/k PR is not merged yet. See https://github.com/kubernetes/enhancements/issues/2040#issuecomment-875217537.

**Comment by Hanaasagi** [comment]
Thanks for the reply. I close this issue and track that KEP.
