### ISSUE TITLE
kubeadm init tasks fails when executing in private servers running behind a proxy

### ISSUE THREAD

**Issue by blesson-james** [kubernetes/kubernetes#103489]
#### What happened:
I'm working on Open source project on High Performance Computing, Omnia(https://github.com/dellhpc/omnia). I deploy single node and multi node k8s cluster on HPC servers with CRI-O as K8s CRI. Our playbooks are working fine when executed on normal servers without any proxy.
Recently we moved to completely private network with internet accessible behind the corporate proxy. And kubeadm init task is failing in this setup with below error:
........
..."[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"", "[kubelet-start] Starting the kubelet", "[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"", "[control-plane] Creating static Pod manifest for \"kube-apiserver\"", "[control-plane] Creating static Pod manifest for \"kube-controller-manager\"", "[control-plane] Creating static Pod manifest for \"kube-scheduler\"", "[etcd] Creating static Pod manifest for local etcd in \"/etc/kubernetes/manifests\"", "[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory \"/etc/kubernetes/manifests\". This can take up to 4m0s", "[kubelet-check] Initial timeout of 40s passed.", "", "\tUnfortunately, an error has occurred:", "\t\ttimed out waiting for the condition", "", "\tThis error is likely caused by:", "\t\t- The kubelet is not running", "\t\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)", "", "\tIf you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:", "\t\t- 'systemctl status kubelet'", "\t\t- 'journalctl -xeu kubelet'", "", "\tAdditionally, a control plane component may have crashed or exited when started by the container runtime.", "\tTo troubleshoot, list all containers using your preferred container runtimes CLI.", "", "\tHere is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:", "\t\t- 'crictl --runtime-endpoint /var/run/crio/crio.sock ps -a | grep kube | grep -v pause'", "\t\tOnce you have found the failing container, you can inspect its logs with:", "\t\t- 'crictl --runtime-endpoint /var/run/crio/crio.sock logs CONTAINERID'"]}

I'm doing below configuration before executing kubeadm init command:

cat /etc/systemd/system/crio.service.d/http-proxy.conf
[Service]
Environment=”HTTP_PROXY=http://IP:port"
Environment=”HTTPS_PROXY=http://IP:port"

systemctl daemon-reload
systemctl restart crio

Updated ~/.bashrc with following
export http_proxy=http://IP:port
export https_proxy=http://IP:port
export no_proxy=localhost,127.0.0.1,master-node-ip,10.96.0.0/12,10.244.0.0/16

here, 10.96.0.0/12 is the service CIDR for kubernetes services & 10.244.0.0/16 is the pod network cidr (Provided during kubeadm init)

My kubeadm init command:
/bin/kubeadm init --pod-network-cidr='10.244.0.0/16' --apiserver-advertise-address='my-head-node-ip'

#### What you expected to happen:
Kubernetes cluster should be deployed successfully

#### How to reproduce it (as minimally and precisely as possible):
Provide proxy configuration as given in steps above.
Proceed with kubernetes installation. (Execute control_plane.yml present on control_plane folder in https://github.com/dellhpc/omnia)

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: on-premises private HPC cluster
- OS (e.g: `cat /etc/os-release`): Centos 8.3
- Kernel (e.g. `uname -a`):
- Install tools: 
- Network plugin and version (if this is a network-related bug): calico (tried with flannel too)
- Others:

**Comment by blesson-james** [comment]
kubeadm init should either provide option to pass these proxy variables or should internally handle proxy configurations and all the pods should automatically be able to perform internal and external communications.

Please let me know if above options are available or let me know if doing anything wrong in the proxy configurations

**Comment by neolit123** [comment]
if your host has the *proxy environment variables kubeadm will pick them up and propagate them to the control plane components. there are a lot of users who have the same setup and it works for them.

but looking at your logs i see:

> This can take up to 4m0s", "[kubelet-check] Initial timeout of 40s passed.", "", "\tUnfortunately, an error has occurred:", "\t\ttimed out waiting for the condition", "", "\tThis error is likely caused by:", "\t\t- The kubelet is not running",

proxy may not be reason for this failure.
you need to look at the kubelet logs, see what containers are failing on the host and their logs.
if you cannot find a solution in:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

try asking on k8s slack's #kubeadm channel or the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/remove-sig network
/kind support
/sig cluster-lifecycle
/close
