### ISSUE TITLE
Deployment Condition not getting updated with correct timestamp

### ISSUE THREAD

**Issue by dhilipkumars** [kubernetes/kubernetes#103450]
#### What happened:
it appears that a deployment recovering from a Quota Error (previous rollout) does not update the condition's timestamp after the current rollout succeeds. 

Here is the condition along with deployments status

```
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2021-07-02T21:53:59Z"
      lastUpdateTime: "2021-07-02T21:53:59Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2021-07-02T19:20:32Z"
      lastUpdateTime: "2021-07-02T22:03:41Z"
      message: ReplicaSet "nginx-deploy-6fdb978b98" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    - lastTransitionTime: "2021-07-02T22:03:41Z"
      lastUpdateTime: "2021-07-02T22:03:41Z"
      message: 'pods "nginx-deploy-6fdb978b98-gcqzs" is forbidden: exceeded quota:
        onboard-quota, requested: memory=500Mi, used: memory=300Mi, limited: memory=500Mi'
      reason: FailedCreate
      status: "True"
      type: ReplicaFailure
    observedGeneration: 40
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
But actually the rollout is successful from simple get command 
```
$ ks get deploy
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
nginx-deploy   1/1     0            1           168m
```
and the Pod is running fine
```
$ ks get pods
NAME                            READY   STATUS    RESTARTS   AGE
nginx-deploy-58478dfb69-gxscf   1/1     Running   0          15m
```

#### What you expected to happen:
The deployments condition is updated with the latest timestamp so that its easier and more reliable for a program to process it.
#### How to reproduce it (as minimally and precisely as possible):
1. Create a namespace
2. create a resource quota with as low as 500Mi memory
3. Create a simple deployment with 1 replica and resource request as 100Mi
4. scale the simple deployment to 10 replicas to simulate a quota failure
5. scale it back to 3 replicas. 
#### Environment:
- Kubernetes version (use `kubectl version`):
`
k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:50:54Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"ca992926ba9f76abd853859a64b5b04a1b562362", GitTreeState:"clean", BuildDate:"2021-05-19T22:29:12Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: aks
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:
cc:

**Comment by dhilipkumars** [comment]
cc: @kow3ns

**Comment by yuswift** [comment]
@dhilipkumars hi, I tried to reproduce the bug with the steps you provided, here is the staus I got:
```
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-07-06T06:37:53Z"
    lastUpdateTime: "2021-07-06T06:37:57Z"
    message: ReplicaSet "nginx-5b675cd9c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-07-06T06:54:39Z"
    lastUpdateTime: "2021-07-06T06:54:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
k get deploy -n quota-test nginx
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   3/3     3            3           18m
```

**Comment by dhilipkumars** [comment]
/remove-lifecycle rotten
as several people have reported, this looks like a hard to recreate problem

**Comment by atiratree** [comment]
@dhilipkumars I have tried to reproduce this as described but came to a same conclussion as @yuswift and am not seeing an issue here.

> But actually the rollout is successful from simple get command
> $ ks get deploy
> NAME           READY   UP-TO-DATE   AVAILABLE   AGE
> nginx-deploy   1/1     0            1           168m

also seeing from your output and yaml: your rollout was not successful (did not complete) yet


My test run:

```
    availableReplicas: 3
    conditions:
    - lastTransitionTime: "2022-01-06T18:27:31Z"
      lastUpdateTime: "2022-01-06T18:27:31Z"
      message: ReplicaSet "nginx-78df9ccbdd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-01-06T18:29:17Z"
      lastUpdateTime: "2022-01-06T18:29:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 5
    readyReplicas: 3
    replicas: 3
    updatedReplicas: 3
```

**Comment by dhilipkumars** [comment]
@atiratree are you trying in a kind cluster? yeah its not an easy recreate, it doesn't happen all the time.

**Comment by atiratree** [comment]
@dhilipkumars I have just tried on kind with multiple attempts but could not reproduce it. 

Can you please try if it can be reproduced on your env again? If yes, please post full YAMLs, events and kube-controller-logs if possible.
