### ISSUE TITLE
Out of memory pods from deployment spawn endlessly

### ISSUE THREAD

**Issue by NikolaNemes** [kubernetes/kubernetes#103421]
#### What happened:
When a applying a deployment using the _nodeName_ attribute to target a specific worker node with a certain number of replicas, kube-scheduler will start spawning endless OOM pods if the node does not currently have enough memory to accommodate all of them.
#### What you expected to happen:
In case there is no memory for the additional replicas, they should stay pending until there is available memory on the node.
#### How to reproduce it (as minimally and precisely as possible):

1. Check the amount of allocatable memory on a certain worker node: **kubectl describe node node_name**
      - In my case, the selected worker node has **2 951 440Ki** allocatable memory.
2. Write a deployment that uses any container image (in my case nginx) with memory request and memory limit set to arbitrary values (but high enough to fill memory of node with a smaller number of pods), and set the _nodeName_ attribute to the name the worker node. Select a smaller number of replicas and deploy. In my case, I was able to go up to 9 replicas with the following deployment.

```script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deplyoment
spec:
  replicas: 9
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeName: poolalpha-worker-0
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "951440Ki"
          requests:
            memory: "214400Ki"
```
If I apply this deployment, 9 pods will be scheduled on the node with no issues.

```script
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deplyoment-54bd7757b8-56nqb   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-7bgqs   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-bqdwg   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-db9nd   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-f8xv9   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-gm6h7   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-mb6lh   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-v2jbz   1/1     Running   0          24s
nginx-deplyoment-54bd7757b8-x7f9p   1/1     Running   0          24s
```

However if I change it to 10 pods (enough for the node to run out of memory) and redeploy, I get the following state:

```script
NAME                                READY   STATUS        RESTARTS   AGE
nginx-deplyoment-54bd7757b8-2q8zm   0/1     OutOfmemory   0          3s
nginx-deplyoment-54bd7757b8-4bq9t   0/1     OutOfmemory   0          2s
nginx-deplyoment-54bd7757b8-5sz89   0/1     OutOfmemory   0          6s
nginx-deplyoment-54bd7757b8-6gchm   0/1     Pending       0          0s
nginx-deplyoment-54bd7757b8-82lwg   0/1     OutOfmemory   0          4s
nginx-deplyoment-54bd7757b8-8nkb8   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-98j7b   0/1     OutOfmemory   0          5s
nginx-deplyoment-54bd7757b8-9dbgd   0/1     OutOfmemory   0          2s
nginx-deplyoment-54bd7757b8-btcx9   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-fctrv   0/1     OutOfmemory   0          5s
nginx-deplyoment-54bd7757b8-g9tlh   0/1     OutOfmemory   0          8s
nginx-deplyoment-54bd7757b8-gszpg   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-hflsx   0/1     OutOfmemory   0          3s
nginx-deplyoment-54bd7757b8-hpbcm   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-k9mkc   0/1     OutOfmemory   0          1s
nginx-deplyoment-54bd7757b8-n88tl   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-nc97x   0/1     OutOfmemory   0          1s
nginx-deplyoment-54bd7757b8-nwlss   0/1     OutOfmemory   0          3s
nginx-deplyoment-54bd7757b8-pcm8z   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-phgjw   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-pnqjj   0/1     OutOfmemory   0          10s
nginx-deplyoment-54bd7757b8-qscnj   0/1     OutOfmemory   0          13s
nginx-deplyoment-54bd7757b8-s4j9l   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-szdlq   1/1     Running       0          13s
nginx-deplyoment-54bd7757b8-wp27n   0/1     OutOfmemory   0          1s
nginx-deplyoment-54bd7757b8-xn5tc   0/1     OutOfmemory   0          5s
```

Unless the deployment is deleted, the number of OOM pods seems to grow endlessly.
Is this due to the way the deployment is configured, or is it a kube-scheduler issue?

#### Environment:
- Kubernetes version:
```script
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"9e5f344f6cdbf2eaa7e450d5acd8fd0b7f669bf9", GitTreeState:"clean", BuildDate:"2021-05-19T04:40:57Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"9e5f344f6cdbf2eaa7e450d5acd8fd0b7f669bf9", GitTreeState:"clean", BuildDate:"2021-05-19T04:34:27Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Install tools: kubeadm

**Comment by NikolaNemes** [comment]
Ah, sorry, I tried searching for similar issues and was not able to find anything.

Is there any way to avoid this sort of behavior? (by changing deployment config or a certain k8s config)

if not, I suppose we should just monitor memory/resource consumption and avoid these situations altogether?

**Comment by wzshiming** [comment]
Because you use nodeName to bypass the scheduler and forcefully schedule to nodes with insufficient memory, You should lower Requests.

**Comment by wzshiming** [comment]
please reopen if you think there is a bug.

support requests should normally go here:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
