### ISSUE TITLE
Deprecate apiserver_longrunning_guage and apiserver_registered_watchers in favor of a new metric

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#103441]
apiserver_longrunning_gauge and apiserver_register_watchers are kinda redundant [as pointed out here](https://github.com/kubernetes/kubernetes/issues/102545). We discussed this in our SIG instrumentation meeting and while it's clear that apiserver_longrunning_gauge, the name does not conform to instrumentation guidelines (it was created before those guidelines existed). 

What we want to do is deprecate both metrics and create a new one which actually does conform to our naming conventions probably something like `apiserver_longrunning_requests`. 

@yanisawesome has volunteered to undertake this. 

/cc @brancz @ehashman @dashpole 
/sig instrumentation

**Comment by jyz0309** [comment]
@yan-lgtm Have you still working on this issue? I am new to the community, and can I try it?

**Comment by yan-lgtm** [comment]
Hey Alkaid, I added the deprecate in https://github.com/kubernetes/kubernetes/pull/103793. If you want to add the new metric, feel free to do so.

**Comment by jyz0309** [comment]
@logicalhan Can I add the new metric? If I can, can you give me some advice about the new metric? Thank you~
