### ISSUE TITLE
 ResourceMetricsAPI failing on containerd and cri-o

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#103428]
#### Which jobs are failing:
https://testgrid.k8s.io/sig-node-containerd#containerd-node-features (containerd)
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features (crio)

#### Which test(s) are failing:
[sig-node] ResourceMetricsAPI [NodeFeature:ResourceMetrics] when querying /resource/metrics should report resource usage through the resource metrics api

#### Since when has it been failing:
Ever since this commit was merged https://github.com/kubernetes/kubernetes/pull/102444

#### Testgrid link:
https://testgrid.k8s.io/sig-node-containerd#containerd-node-features (containerd)
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features (crio)

#### Reason for failure:
We need to see what the commit is breaking this particular NodeFeatures test on both crio and containerd.

**Comment by ehashman** [comment]
ah, let's use the RT's issue

/close
