### ISSUE TITLE
Kubernetes v1.20 endpoints resource cannot view controller manger or scheduler

### ISSUE THREAD

**Issue by XzBuleSky** [kubernetes/kubernetes#103446]
#### What happened:
  Hello ！
  I want to check the election of basic components, but the information displayed is different in different versions of kubernetes binary installation methods.
  Is the corresponding information cancelled in kubernetes v1.20 +? Or is there any other way to view the election of basic components?
The following kubernetes configuration parameters are consistent, except that the binary executable file is replaced
> Kubernetes v1.20.8 or Kubernetes v1.20.2
```
$ kubectl get endpoints -n kube-system
No resources found in kube-system namespace.
```
> Kubernetes v1.19.12
```
$ kubectl get endpoints -n kube-system
NAME                      ENDPOINTS   AGE
kube-controller-manager   <none>      9m12s
kube-scheduler            <none>      9m13s
```

**Comment by yuswift** [comment]
`kubectl get leases.coordination.k8s.io -A`

**Comment by neolit123** [comment]
for more questions please try https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close

**Comment by neolit123** [comment]
/sig network

if you think there is a bug, reopen this issue.
