### ISSUE TITLE
prow.k8s.io: show skip reason

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#103430]
#### What would you like to be added:

When an e2e test gets skipped with `e2eskipper.Skipf`, the reason passed to that function should be visible in junit file and prow.io.

~~Currently the reason is not recorded in the junit file. Whether it would be shown by prow.io is unknown.~~

Recent JUnit files contain an explanation why a test case was skipped. It would be nice to show that on prow.io.

#### Why is this needed:

Makes it easier to understand why a test didn't run in a certain job.

**Comment by spiffxp** [comment]
I _think_ this is fixed in v1.22 due to the latest ginkgo.  We need to give backporting to release-branch branches a go

**Comment by spiffxp** [comment]
I noticed you filed this issue after https://github.com/kubernetes/kubernetes/pull/102111 landed, so maybe it didn't actually fix things?  I was under the impression that pulled in https://github.com/onsi/ginkgo/pull/571 which fixed the bug you're experiencing

**Comment by pohly** [comment]
> I noticed you filed this issue after #102111 landed, so maybe it didn't actually fix things?

Let me double-check...

/assign

**Comment by pohly** [comment]
There are indeed `<skipped>` entries when testing with Kubernetes master. I must have looked at a run with Kubernetes 1.21 or older when filing this issue.

Example from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-csi-1-21-on-kubernetes-master/1422109884308000768/artifacts/junit_parallel.xml

```
<testcase name="External Storage [Driver: hostpath.csi.k8s.io] [Testpattern: Dynamic PV (default fs)] fsgroupchangepolicy (OnRootMismatch)[LinuxOnly], pod created with an initial fsgroup, new pod fsgroup applied to volume contents" time="0.001067444">
<skipped>
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/framework/testsuite.go:51 Driver "hostpath.csi.k8s.io" does not support FsGroup - skipping /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/fsgroupchangepolicy.go:79
</skipped>
</testcase>
```

However, prow.k8s.io does not show the skip reasons: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-csi-1-21-on-kubernetes-master/1422109884308000768

**Comment by BenTheElder** [comment]
This would have better visibility in kubernetes/test-infra, where the source code for prow.k8s.io exists.

**Comment by pohly** [comment]
> This would have better visibility in kubernetes/test-infra, where the source code for prow.k8s.io exists.

I wasn't sure whether it's e2e.test or the web UI which needs to be enhanced. Let's move it... -> https://github.com/kubernetes/test-infra/issues/24209
