### ISSUE TITLE
Does k8s support assigning unique identification to each pod? #58962

### ISSUE THREAD

**Issue by zgcbj** [kubernetes/kubernetes#103506]
I create a Deployment with 5 pods, the requirement is that each application in each pod needs an unique identification(such as pod-1, pod-2, pod-3, pod-4, pod-5). StatefulSet is not suitable，because pods couldn't be rescheduled when the node is NotReady. Is there any ways to achieve this ?
The requirement is that, when a pod is rescheduled to another node, the pod’s iidentification wouldn’t be changed.

**Comment by zgcbj** [comment]
@kubernetes/sig-apps-feature-requests

**Comment by thockin** [comment]
Not as part of something like Deployment.  I think you want multiple ServiceAccounts and multiple Deployments (or other controllers).
