### ISSUE TITLE
Failed to renew certificate by following official documents

### ISSUE THREAD

**Issue by rayw000** [kubernetes/kubernetes#103575]
#### What happened:

I'm trying to renew certificates of my cluster due to it has already been expired after being set up for 1 year.

I tried steps here https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubelet-client-cert
and here https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

Everything seems fine. Now I run `sudo kubeadm alpha certs check-expiration` and gets
```
[check-expiration] Reading configuration from the cluster...
[check-expiration] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Jul 08, 2022 04:11 UTC   364d                                    no
apiserver                  Jul 08, 2022 04:11 UTC   364d            ca                      no
apiserver-etcd-client      Jul 08, 2022 04:11 UTC   364d            etcd-ca                 no
apiserver-kubelet-client   Jul 08, 2022 04:11 UTC   364d            ca                      no
controller-manager.conf    Jul 08, 2022 04:11 UTC   364d                                    no
etcd-healthcheck-client    Jul 08, 2022 04:11 UTC   364d            etcd-ca                 no
etcd-peer                  Jul 08, 2022 04:11 UTC   364d            etcd-ca                 no
etcd-server                Jul 08, 2022 04:11 UTC   364d            etcd-ca                 no
front-proxy-client         Jul 08, 2022 04:11 UTC   364d            front-proxy-ca          no
scheduler.conf             Jul 08, 2022 04:11 UTC   364d                                    no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      May 06, 2030 09:31 UTC   8y              no
etcd-ca                 May 06, 2030 09:31 UTC   8y              no
front-proxy-ca          May 06, 2030 09:31 UTC   8y              no
```

And command `ls -l /var/lib/kubelet/pki` gives me
```
total 12K
-rw------- 1 root root 2.8K Jul  8 11:10 kubelet-client-2021-07-08-11-10-47.pem
lrwxrwxrwx 1 root root   59 Jul  8 11:10 kubelet-client-current.pem -> /var/lib/kubelet/pki/kubelet-client-2021-07-08-11-10-47.pem
-rw-r--r-- 1 root root 2.2K May  8  2020 kubelet.crt
-rw------- 1 root root 1.7K May  8  2020 kubelet.key
```

But pod `kube-apiserver-master-node` still complains
```
E0708 06:17:56.925938       1 authentication.go:53] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid
```

pod `kube-controller-manager-master-node` complains
```
E0708 06:18:43.864140       1 leaderelection.go:320] error retrieving resource lock kube-system/kube-controller-manager: Unauthorized
```

pod `kube-schedular-master-node` complains something like
```
E0708 06:18:13.501920       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.PodDisruptionBudget: Unauthorized
E0708 06:18:28.307350       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.PersistentVolume: Unauthorized
E0708 06:18:30.694503       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Node: Unauthorized
E0708 06:18:31.360053       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.StorageClass: Unauthorized
E0708 06:18:32.420864       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.PersistentVolumeClaim: Unauthorized
E0708 06:18:33.846130       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSINode: Unauthorized
E0708 06:18:37.965334       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Service: Unauthorized
E0708 06:18:48.295401       1 reflector.go:178] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Failed to list *v1.ConfigMap: Unauthorized
E0708 06:18:56.318539       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1beta1.PodDisruptionBudget: Unauthorized
```

I've tried to delete these three pods. They are recreated automatically, problem is still there.

And deployments still don't create new replicasets when they are changed by running `kubectl apply -f`, existing replicasets still don't create new pods when I manually delete an existing pod.

#### What you expected to happen:

Successfully renew certificates and make cluster work as normal.

#### How to reproduce it (as minimally and precisely as possible):

I've no idea.

#### Environment:
- Kubernetes version (use `kubectl version`): from 1.18.5 to 1.19.2
- Cloud provider or hardware configuration: bare-metal
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04 LTS
- Kernel (e.g. `uname -a`): `Linux master-node 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: apt-get
- Network plugin and version (if this is a network-related bug): calico-3.14
- Others:

**Comment by wangyysde** [comment]
As if you have renewed the certificates. Are you "copy this resulted kubelet.conf to /etc/kubernetes/kubelet.conf on ALL nodes?
Have you restarted kubelet?

**Comment by rayw000** [comment]
@wangyysde

> Are you "copy this resulted kubelet.conf to /etc/kubernetes/kubelet.conf on ALL nodes?

No, just the control plane node. Let me have a try to do this.

> Have you restarted kubelet?

Yes, but only the control plane node.

**Comment by rayw000** [comment]
@wangyysde 

I've tried to copy `kubelet.conf` to a working node with low workloads and restart its kubelet. Everything seemed fine until I tried to delete a pod on it. There is no new pod recreated. Problem still.

**Comment by rayw000** [comment]
Solved!

All I need to do is running these commands on my control plane.
```
docker kill k8s_POD_kube-apiserver-{control plane hostname}_kube-system_xxxxxxxx
docker kill k8s_POD_kube-controller-manager-{control plane hostname}_kube-system_xxxxxxxx
docker kill k8s_POD_kube-scheduler-{control plane hostname}_kube-system_xxxxxxxx
```

According to my test, `kubectl -n kube-system delete pod kube-xxx-<hostname>` **DOESN'T WORK**.
**ONLY** manually killing `k8s_POD_*` containers solved my problem.

**Comment by neolit123** [comment]
hi, 

there are a couple of things to note here:
- kubeadm manages the control-plane certificates those that you can use "kubeadm certs renew" with.
- kubeadm does not manage the the kubelet certificates, those are renewed automatically, so this guide is normally not needed:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/#kubelet-client-cert
but if you had the problem with the kubelet you should follow the guide. it works.

> I'd like to leave this issue opened since killing k8s_POD_* is not mentioned in this document. So it may not be a normal situation I ran into.

if you run `kubeadm certs renew` you will see that it actually tells you at the end that you must now restart the components.
it is not mentioned here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-certs/#manual-certificate-renewal

but you can log an issue about it in the kubernetes/website repository and tag it with `/sig cluster-lifecycle`. you can also help us by sending a PR. using `docker kill` is not portable because there are also containerd / cri-o users. a general note in the lines "you must now restart the containers of the control plane components" is better.

/area kubeadm
/sig cluster-lifecycle
/kind support
/close

**Comment by rayw000** [comment]
@neolit123 Thank you for your reply. That's a great help to me! I'd like to submit a PR to website repo.
