### ISSUE TITLE
kubectl get -o yaml: is it posible to hide metadata.managedFields

### ISSUE THREAD

**Issue by gaorong** [kubernetes/kubernetes#103571]
#### What would you like to be added:
kubectl's output hides the pod `managedFields` field by default,  IMO, most people don't care about this field, but it will take a lot of screen space to show, and mess the truly valuable information.  Maybe we can add a flag to `kubectl get pod` command if we want to observe this field apparently.
 
also see https://stackoverflow.com/questions/62077977/kubectl-get-o-yaml-is-it-posible-to-hide-metadata-managedfields

**Comment by pacoxu** [comment]
The second answer in your stackoverflow link has mentioned the flag https://stackoverflow.com/a/67056145.
```
      --show-managed-fields=false: If true, keep the managedFields when printing objects in JSON or YAML format.
```
This was added since 1.21(#96878).
