### ISSUE TITLE
Private docker images in examples and contrib

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/kubernetes#10352]
There is a bunch of of places where we use docker images hosted on private accounts. I think we should switch there to some more official sources or host the images on gcr.io/google_containers. 

```
./contrib/prometheus/prometheus-all.json: "jayunit100/kube-prometheus"
./examples/cluster-dns/dns-backend-rc.yaml: ddysher/dns-backend
./examples/cluster-dns/dns-frontend-pod.yaml: ddysher/dns-frontend
./examples/guestbook-go/redis-master-controller.json: "image":"gurpartap/redis"
./examples/guestbook-go/redis-slave-controller.json: "image":"gurpartap/redis"
./examples/hazelcast/hazelcast-controller.yaml: quay.io/pires/hazelcast-kubernetes:0.3.1
./examples/meteor/meteor-controller.json: "chees/meteor-gke-example:latest"
./examples/nfs/nfs-server-pod.yaml: jsafrane/nfs-data
./examples/phabricator/phabricator-controller.json: "fgrzadkowski/example-php-phabricator"
./examples/rethinkdb/admin-pod.yaml: - antmanler/rethinkdb:1.16.0
./examples/rethinkdb/rc.yaml: - antmanler/rethinkdb:1.16.0
./examples/spark/spark-master.json: "mattf/spark-master"
./examples/spark/spark-worker-controller.json: "mattf/spark-worker"
./examples/storm/storm-nimbus.json: "mattf/storm-nimbus"
./examples/storm/storm-worker-controller.json: "mattf/storm-worker"
./examples/storm/zookeeper.json: "mattf/zookeeper"
```

**Comment by mwielgus** [comment]
@marekbiskup @piosz

**Comment by resouer** [comment]
I try to fix example I proposed, but it seems I can not push to `gcr.io`

```
Error: Status 403 trying to push repository google_containers/appsample: "Access denied."
```

**Comment by mwielgus** [comment]
@resouer Which example are you talking about?

**Comment by bgrant0607** [comment]
cc @kubernetes/examples

**Comment by amygdala** [comment]
For examples, we (dev rel) have created a canonical place to put public container images: the `google-samples` project. It probably makes sense to port most of the images over, for those examples we wish to maintain.

**Comment by fejta** [comment]
@amygdala how do we add images to google-samples? #13288 shows that there are some kubernetes/redis etc images that exist on dockerhub that I'd like to migrate over to gcr.io to address that bug.

I'd be happy to get instructions from you on how I can do this if you don't have time.

**Comment by amygdala** [comment]
Just closing the loop here -- it looks like Jeff has replied on email. @fejta

**Comment by fejta** [comment]
@amygdala Thanks for letting me know about the email!

**Comment by spiffxp** [comment]
/remove-sig testing
/sig release
/sig apps
I'm adding release because of "building things" and apps because I think they're the sig that owns kubernetes/examples

**Comment by ahmetb** [comment]
We moved the examples to their own repo (https://github.com/kubernetes/examples) for further maintenance. All maintained examples (guestbook, mysql-wordpress-pd and cassandra) use either Docker Hub images, or gcr.io/google-samples which are publicly acessible. Other examples in that repository are staged for deletion in the long term if nobody steps up to take over maintenance.

I've a longer term plan to make gcr.io/google-samples process more transparent and accessible to wider community: kubernetes/examples#11 (comment)

If you think this issue is still relevant, please create a new issue in the new repo.
