### ISSUE TITLE
Make our testing environment more sane

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#10353]
From @ixdy in #10078:

> And I don't really have a great plan for expanding this yet. One issue is that this script isn't bundled with any of the release artifacts, so our Jenkins runners download it from GitHub each time. Having to download multiple scripts (if we factor it out) will get a bit more complicated, though it's a possibility. Also open to other suggestions on how to organize this. (Maybe using some sort of lightweight config format rather than a shell script?)

I recommend we have a conversation about how to move the testing environment/framework, (e2e and maybe others,) into first-class code rather than all shell scripts.  Maybe this conversation has already happened or is somewhere else, but I haven't really been a part of it.

cc @ixdy @mbforbes @quinton-hoole

**Comment by quinton-hoole** [comment]
Agreed, that conversation is overdue.  We're probably not going to have bandwidth for this for the next few weeks.

**Comment by quinton-hoole** [comment]
To be clear, I'd welcome the conversation to get this started, but I don't think that we'll be merging any large changes to the code in the next few weeks.

**Comment by ihmccreery** [comment]
As I'm poking around our testing infrastructure this week, I'll think about this and maybe write something up.

**Comment by cjcullen** [comment]
It'd be nice to have the critical builds fail fast, and maybe also prioritize running known flaky tests first.

**Comment by ihmccreery** [comment]
From @alex-mohr:

We should reduce the number of project our testing infrastructure uses, so there are fewer to manage.

We should also make sure we can track down leaked resources easily, and make sure we're not leaking, or at least clean up leaked resources.

**Comment by ihmccreery** [comment]
Closing this as obsolete.
