### ISSUE TITLE
TestQuotaLimitService is very flaky

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#103510]
It failed 3 times on my unrelated PR, e.g.:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102998/pull-kubernetes-integration/1412300553769193472

/kind flake

Added in https://github.com/kubernetes/kubernetes/pull/100412

/sig network
/priority important-soon

/cc @hanlins @aojea @thockin

**Comment by aojea** [comment]
discussed here , https://github.com/kubernetes/kubernetes/pull/103472
but I think we should move from hardcoded delay to wait.PollImmediate loops ...

**Comment by aojea** [comment]
/close

no failures on this test on the last 10 failed jobs since
https://github.com/kubernetes/kubernetes/pull/103472
