### ISSUE TITLE
Pod fail to start as /sys/fs/cgroup/devices/kubepods.slice/kubepods-burstable.slice doesn't exist

### ISSUE THREAD

**Issue by Congelli501** [kubernetes/kubernetes#103542]
#### What happened:
Pod failed to start on a node that is already running a lot of pod sucessfuly, with the following events:
```
unable to ensure pod container exists: failed to create container for [kubepods burstable pod247ca13b-bc17-4709-ab2c-4d98b5ad4fb2] : mkdir /sys/fs/cgroup/devices/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod247ca13b_bc17_4709_ab2c_4d98b5ad4fb2.slice: no such file or directory
unable to ensure pod container exists: failed to create container for [kubepods burstable pod247ca13b-bc17-4709-ab2c-4d98b5ad4fb2] : Unit kubepods-burstable-pod247ca13b_bc17_4709_ab2c_4d98b5ad4fb2.slice already exists.
Successfully assigned api/file-manager-0 to node2
```

The pod was is a `ContainerCreating` state during that time, after 10 minutes, I deleted the pod, and it finally came up in less than a minute.
The pod was created from a statefulset

#### What you expected to happen:
Pod should have started normally.

#### How to reproduce it (as minimally and precisely as possible):
I don't know :(

#### Anything else we need to know?:
When the pod was failing to start, the directory `/sys/fs/cgroup/devices/kubepods.slice/` didn't exist on that node.
When the pod was able to start, the directory `/sys/fs/cgroup/devices/kubepods.slice/` existed (I didn't create it myself)
This is the first time I saw this error for a 2000+ pod cluster, so it seems pretty rare. I upgraded runc recently from version 
`1.0.0~rc10-0ubuntu1` to `1.0.0~rc95-0ubuntu1~20.04.1`.
Seems to be the follow up of https://github.com/kubernetes/kubernetes/issues/97497

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Baremetal amd64 (AMD EPYC 7371 / 256GB of RAM)
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`): `Linux node2 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): weave 2.8.1
- Others: containerd `1.4.4-0ubuntu1~20.04.2` and runc version `1.0.0~rc95-0ubuntu1~20.04.1`

**Comment by neolit123** [comment]
> How to reproduce it (as minimally and precisely as possible):
> I don't know :(

are you able to provide more details of why it happens?

> AMD EPYC 7371 / 256GB of RAM

i'm going to assume that's node RAM and not the CPU cache of the 7371 (google says it has 64MB L3).
is 256 sufficient for you pod?

/sig node

**Comment by Congelli501** [comment]
> > How to reproduce it (as minimally and precisely as possible):
> > I don't know :(
> 
> are you able to provide more details of why it happens?
Unfortunately not, I opened the issue as the other issue with the same errors (https://github.com/kubernetes/kubernetes/issues/97497) states it may not be solved.
It was during the creation of a pod created by a new statefull set, but the cluster runs more than 200 statefull sets with that same image and just a different mount.
So there is nothing special about what I did, so the issue seems extremely rare.

> 
> > AMD EPYC 7371 / 256GB of RAM
> 
> i'm going to assume that's node RAM and not the CPU cache of the 7371 (google says it has 64MB L3).
> is 256 sufficient for you pod?
It's 256 GB of RAM (not MB), yes, it's enough for that pod and the other hundreds of other pods that runs alongside it. Half the RAM was available at the time of the issue. There was no high cpu usage or load.
> 
> /sig node

Anyway, feel free to close the issue as non reproducible, I'll open it again if the problem happens a second time

**Comment by odinuge** [comment]
This is probably the same issue as https://github.com/kubernetes/kubernetes/issues/102676. Can you verify if you see the same issue with `v1.21.1`?

We sadly don't have a fix ready for next release (if that is the issue), and the regression will be there in `v1.22` as well. https://github.com/kubernetes/kubernetes/issues/102676 should fix this, but it lack review/approval... :/

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

need to have better repro steps if possible and whether it's the same issue as @odinuge suggested.
