### ISSUE TITLE
TestValidateCertificateSigningRequestCreate/valid_duration is flaking

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#103549]
#### Which jobs are flaking:

pull-kubernetes-unit

#### Which test(s) are flaking:

pkg/apis/certificates/validation TestValidateCertificateSigningRequestCreate/valid_duration

#### Testgrid link:

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/98817/pull-kubernetes-unit/1412827544935206912

#### Reason for failure:

```
    validation_test.go:378: returned and expected errors did not match - expected
        <nil>
        but got
        <nil>
```

cc @enj for #99494

**Comment by liggitt** [comment]
/close

this is only seen in presubmit runs on a single PR which introduced the issue
