### ISSUE TITLE
[PodSecurity] Improve error UX

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103561]
Ideas to consider:
- [x] ~~Group errors by container. Ex:
    `pod: check1, check2 (value); container1: check1 (value, value); init container2: check1, check5~~
- [x] ~~Consider making reasons more machine-readable~~
- [x] https://github.com/kubernetes/kubernetes/issues/103213
- [x] Add context to failure message, like `Pod violates baseline PodSecurity level:` - https://github.com/kubernetes/kubernetes/pull/105314
- [x] Fix invalid namespace label error message - https://github.com/kubernetes/kubernetes/pull/105959

Hoisted to followup in #106129

**Comment by pacoxu** [comment]
/assign @calvin0327
Would you help to implement this?

**Comment by calvin0327** [comment]
@pacoxu Yes, I want to have a try.

/assign

**Comment by tallclair** [comment]
Another one to add: provide more context for the failure message. For example, this is the current error (v1.22.1) on an `enforce=baseline` namespace:

```sh
$ kubectl run privilege-pod --rm -it --privileged --image=alpine --overrides='{"spec":{"hostPID": true}}'
Error from server (Failure): host namespaces (hostPID=true), privileged (container "privilege-pod" must not set securityContext.privileged=true)
```

I would prefer to see an error message like:
```
Error from server (Failure): Pod violates baseline PodSecurity level: host namespaces (hostPID=true), privileged (container "privilege-pod" must not set securityContext.privileged=true)
```
Adding `Pod violates baseline PodSecurity level:`, or something like that.

**Comment by tallclair** [comment]
Another error message that could stand to be improved:

```sh
$ kubectl label namespace default pod-security.kubernetes.io/enforce-version=foobar
The namespaces "default" is invalid
```

**Comment by calvin0327** [comment]
@tallclair  I worked on it for a few days and tried to solve the first and fifth issue. I don't know that is reasonable, correct me if not.
