### ISSUE TITLE
Automate code generated by mockgen/mockery

### ISSUE THREAD

**Issue by nikhita** [kubernetes/kubernetes#103540]
There are a few mock files [1] [2] in the codebase today that are generated by [mockgen](https://github.com/golang/mock) and [mockery](https://github.com/vektra/mockery). However, these files are not autogenerated by any scripts today. This should be fixed and they should be probably be automated using `go:generate` tags [3].  They should probably also be made consistent to use either mockgen _or_ mockery too.

Example (mockgen):

https://github.com/kubernetes/kubernetes/blob/17f6f286212a631a6f73749b3f8b1fcebd9f90bb/pkg/kubelet/dockershim/libdocker/testing/mock_client.go#L19-L21

Example (mockery):

https://github.com/kubernetes/kubernetes/blob/17f6f286212a631a6f73749b3f8b1fcebd9f90bb/pkg/kubelet/pod/testing/mock_manager.go#L17

[1] https://cs.k8s.io/?q=mockgen&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes
[2] https://cs.k8s.io/?q=mockery&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes
[3] https://blog.codecentric.de/en/2017/08/gomock-tutorial/

---
Thanks to @ihgann for pointing this!

/kind cleanup

cc @dims @oomichi  since you were involved in https://github.com/kubernetes/kubernetes/pull/95534#discussion_r505818224

Maybe code organization since this is spread across the codebase
/sig architecture
/area code-organization

**Comment by ihgann** [comment]
If it matters, at all, I would vote for [mockgen](https://github.com/golang/mock) to be the standard.

**Comment by vikramcse** [comment]
@nikhita @dims 
1. for automating mock generation we can add `go:generate` tag in the file where the interface exists
- so whenever we can to generate a mock for a interface we can trigger `go generate <file_name>` command
- we can also add `go generate <filename>` command in makefile

2. there are only 4 files which are using `mokito/testify` so converting them to `gomock/mockgen` will be easier

let me know your thoughts on this

**Comment by dims** [comment]
@vikramcse the typical pattern we have is ...
- have a `hack/update-xyz.sh` which one can use to update the files.
- have a `hack/verify-xyz.sh` that runs in CI and can compare what exists in the repo and complains to folks to run the `update-xyz.sh` script

So let's start with a update script ... please scan the existing ones in the hack/ directory to get some inspiration.

**Comment by vikramcse** [comment]
@dims I have started working on the `update script`, which generates the mock files by reading the `go:generate` command mentioned in the comments.
I went through existing update scripts and have done some rough bash script
Am I on right track?

**Comment by dims** [comment]
yep, please open up a draft PR

**Comment by vikramcse** [comment]
@dims 
Thank You for your guidance :)
converted to Draft PR

I have a question
- by this approach this script will scan each `go:generate` command every time and regenerate the mock file, so is there any need to avoid that regeneration? if yes then how can I check that

**Comment by dims** [comment]
@vikramcse look at how verify-gofmt.sh works

**Comment by vikramcse** [comment]
@dims I noticed there are some `interfaces` which does not exists in file

for e.g below mock is generated from `NetworkPlugin` interface from `k8s.io/kubernetes/pkg/kubelet/network` package
that interface does not exists in that package.

https://github.com/kubernetes/kubernetes/blob/388c2d901d185d34a340fcae566bd38b73bdb704/pkg/kubelet/dockershim/network/testing/mock_network_plugin.go#L19-L21 

Now the `NetworkPlugin` exists in `pkg/kubelet/dockershim/network/plugins.go`

so when we re:generate the mock from the NEW `NetworkPlugin` interface by using below command the prev and current mocks are not matching
```
//go:generate mockgen -source=plugins.go  -destination=testing/mock_network_plugin.go -package=testing NetworkPlugin
```

https://github.com/kubernetes/kubernetes/blob/388c2d901d185d34a340fcae566bd38b73bdb704/pkg/kubelet/dockershim/network/plugins.go#L54-L83

what should we do in this case?

**Comment by dims** [comment]
we should try to fix the existing test to use the NEW NetworkPlugin @vikramcse
