### ISSUE TITLE
Cannot create certificate signing request: Post "https://kube.company.com x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by lambotchi** [kubernetes/kubernetes#103680]
#### What happened:
Error during kubeadm init. I am trying to setup HA Cluster with kubeadm following this [guide](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/high-availability/). 

```
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in cri-o/containerd using crictl:
		- crictl --runtime-endpoint /run/containerd/containerd.sock ps -a | grep kube | grep -v pause
		Once you have found the failing container, you can inspect its logs with:
		- 'crictl --runtime-endpoint /run/containerd/containerd.sock logs CONTAINERID'
```

**kubelet logs**
```
Jul 13 02:35:22 qakube-master.company.com kubelet[23845]: E0713 02:35:22.584281   23845 kubelet.go:2291] "Error getting node" err="node \"qakube-master.company.com\" not found"
Jul 13 02:35:22 qakube.company.com kubelet[23845]: E0713 02:35:22.648311   23845 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://k...unknown authority
```

#### What you expected to happen:
kubeadm init will be successful

#### How to reproduce it (as minimally and precisely as possible):
1. **Load balancer is set** (nginx + keepalived). Listening port is at 443. Master nodes are added as backed with port 443 (not 6443). Able to test the connectivity between the LB and the VMs

**Standard k8s component installation on official docs**

2. Disable swap
sudo swapoff -a
edit /etc/fstab and comment any swap entries if present

3. Letting iptables see bridged traffic
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

4. Whitelist required ports
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#check-required-ports
https://istio.io/latest/docs/ops/deployment/requirements/

5. Install containerd as container-runtime (instead of docker)
Make sure that docker or other supported container runtime is installed
Prerequisite
cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

6. Setup required sysctl params, these persist across reboots.
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

7.Apply sysctl params without reboot
sudo sysctl --system

8. Install containerd
sudo yum install -y yum-utils device-mapper-persistent-data lvm2
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo

sudo yum update -y && sudo yum install -y containerd.io

sudo mkdir -p /etc/containerd
containerd config default | sudo tee /etc/containerd/config.toml

9. Containerd additional configurations /etc/containerd/config.toml
Use systemd as cgroupdriver
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  ...
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true

Use /data as containerd data directory
Change to the desired root directory (e.g. /data)
root = "/var/lib/containerd"

10. Installing kubeadm, kubelet and kubectl on ALL your nodes
Execute this on all of your cluster nodes/VMS.
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

11. Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
sudo yum install -y kubelet-1.21.2 kubeadm-1.21.2 kubectl-1.21.2 --disableexcludes=kubernetes
sudo systemctl enable --now kubelet
sudo systemctl daemon-reload
sudo systemctl restart kubelet

12. sudo kubeadm init --control-plane-endpoint kube.company.com --kubernetes-version v1.21.2 --pod-network-cidr 10.244.0.0/16 --cri-socket /run/containerd/containerd.sock  --upload-certs --apiserver-cert-extra-sans=kube.company.com,localhost,$kubemaster1IP,$kubemaster2IP,$kubemaster3IP --apiserver-bind-port=443 

#### Anything else we need to know?:
1. When the LB is handed over to me and backend (3 IPs of the master nodes) are configured, I tried to replace my kubeconfig with kube.company.com:443 in my server field value. It produces the same error x509: certificate signed by unknown authority. **I guess this is also a question of what should be done if you are going to place an LB in front of a a master node (regardless if 1 or many master)**

2. When I `kubeadm init` without `--control-plane-endpoint`. It works as expected. 
3. It fails even if I use the IP of the load balancer in `--control-plane-endpoint`

#### Environment:
- Kubernetes version: 1.21.2
- Cloud provider or hardware configuration: Bare Metal
- OS (e.g: `cat /etc/os-release`): RHEL 7.9
- Kernel (e.g. `uname -a`):3.10.0-1160.25.1.el7.x86_64 #1 SMP Tue Apr 13 18:55:45 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): N/A
- Others: containerd

**Comment by lambotchi** [comment]
This happens when my front-end load balancer is listening at 443. When i tried to changed it to 6443, everything just works out fine. I haven't tested using other ports other than the two. Can someone explain to me why? 

I tried to use a simply haproxy setup like 

```
# /etc/haproxy/haproxy.cfg
#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon


#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option http-server-close
    option forwardfor       except 127.0.0.0/8
    option                  redispatch
    retries                 1
    timeout http-request    10s
    timeout queue           20s
    timeout connect         5s
    timeout client          20s
    timeout server          20s
    timeout http-keep-alive 10s
    timeout check           10s


#---------------------------------------------------------------------
# apiserver frontend which proxys to the control plane nodes
#---------------------------------------------------------------------
frontend apiserver
    bind *:6443
    mode tcp
    option tcplog
    default_backend apiserver


#---------------------------------------------------------------------
# round robin balancing for apiserver
#---------------------------------------------------------------------
backend apiserver
    option httpchk GET /healthz
    http-check expect status 200
    mode tcp
    option ssl-hello-chk
    balance     roundrobin
        server  k8s-master-0 10.218.8.301:6443 check
        server  k8s-master-1 10.218.8.302:6443 check
        server  k8s-master-2 10.218.8.303:6443 check
```
and execute

`sudo kubeadm init --control-plane-endpoint loadbalancerdns.company.com:6443 --kubernetes-version v1.21.2 --pod-network-cidr 10.244.0.0/16 --cri-socket /run/containerd/containerd.sock`

**Comment by neolit123** [comment]
hello,

> This happens when my front-end load balancer is listening at 443. When i tried to changed it to 6443, everything just works out fine. I haven't tested using other ports other than the two. Can someone explain to me why?

haproxy is taking over a port the kube-apiserver cannot listen on it?
see:
https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#bootstrap-the-cluster

if you think something is missing in the documentation PRs, welcome for k/kubeadm and k/webiste.

> Jul 13 02:35:22 qakube.company.com kubelet[23845]: E0713 02:35:22.648311   23845 certificate_manager.go:437] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post "https://k...unknown authority

this may be unrelated or temporal.

we do not provide support in the kubernetes issue trackers.
try the support channels or #kubeadm on k8s slack:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close

**Comment by lambotchi** [comment]
I am well aware of https://github.com/kubernetes/kubeadm/blob/master/docs/ha-considerations.md#bootstrap-the-cluster and tried with --apiserver-bind-port as well.
