### ISSUE TITLE
Azure In-tree CSI Driver: Unable to Access Azure File PVC After Rotating Storage Account Credentials

### ISSUE THREAD

**Issue by poojas1607** [kubernetes/kubernetes#103683]
I'm using in-tree driver to dynamically provision azure file share PVC. However the secret which is deployed during PVC provision is not getting updated when the storage account credential gets rotated . Is this expected behavior? If yes then is there any way to update the secret for PVCs? The credentials are created as a secret in pod namespace by in-tree CSI driver.
The kubernetes version I'm using - 1.19.10.

When I tried to access the PVC director by executing into the pod. It was not accesible after rotating the Azure storage account credentials. 

For example, in below example, Azure PVC is mounted using CIFS in az-mounts directory.

```
user@computer> kubectl exec -it sample-pod -n test1 -- /bin/bash
bash-4.3# ls
bin  dev   home  lib64  az-mounts  proc  root   sbin  srv      tmp  var
bash-4.3# cd az-mounts
bash-4.3# ls
tmp1  tmp2
# rotate Azure storage account credentials externally
bash-4.3# cd tmp1
bash-4.3# ls
ls: reading directory '.': Host is down
bash-4.3# exit
```

**Comment by poojas1607** [comment]
> @poojas1607: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

/sig storage

**Comment by poojas1607** [comment]
> @poojas1607: This issue is currently awaiting triage.
> 
> If a SIG or subproject determines this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.
> 
> The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.

/triage accepted

**Comment by poojas1607** [comment]
Any update?

**Comment by andyzhangx** [comment]
### update azure file secret if azure storage account key changed

**Issue details**: 
There would be azure file mount failure if azure storage account key changed

**Workaround**:
User needs to update `azurestorageaccountkey` field manually in azure file secret(secret name format: `azure-storage-account-{storage-account-name}-secret` in `default` namespace):
```
kubectl delete secret azure-storage-account-{storage-account-name}-secret
kubectl create secret generic azure-storage-account-{storage-account-name}-secret --from-literal azurestorageaccountname=... --from-literal azurestorageaccountkey="..." --type=Opaque
```
 > make sure there is no `\r` in the account name and key, here is a [failed case](https://github.com/MicrosoftDocs/azure-docs/issues/61650#issuecomment-683274588)
 - delete original pod(may use `--force --grace-period=0`) and wait a few minutes for new pod retry azure file mount
