### ISSUE TITLE
How to generate yaml in cluster to let work node to join

### ISSUE THREAD

**Issue by huchen2021** [kubernetes/kubernetes#103652]
#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

I have a cluster, and a node wants to join by running “kubeadm join --config kubeadm-join-config.yaml  --ignore-preflight-errors=all”

I don't know how to generate kubeadm-join-config.yaml of this cluster. Any hints will be appreciated.

**Comment by CaoDonghui123** [comment]
> kubeadm config print join-defaults > kubeadm-join-config.yaml

doc:https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

**Comment by neolit123** [comment]
you can look at JoinConfiguration here:
https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

or check the output of `kubeadm config print join-defaults`.

/close
