### ISSUE TITLE
Failing SIG Scalability performance tests

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#103682]
Since last Friday scalability test become red/very flaky

Affected jobs:
* [gce-master-scale-performance](https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance)
* [kubemark-master-500](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-master-500)
* [kubemark-5000](https://k8s-testgrid.appspot.com/sig-scalability-kubemark#kubemark-5000)

Those failure are related to failed jobs. Sample test output:

```
ClusterLoaderV2: load: [step: 24] Waiting for 'scale and update objects' to be completed
:0 [measurement call WaitForControlledPodsRunning -  error: [measurement call WaitForControlledPodsRunning - WaitForRunningJobs error: 17 objects timed out: Jobs: test-ls2r5p-31/big-job-0, test-ls2r5p-13/big-job-0, test-ls2r5p-25/big-job-0, test-ls2r5p-10/medium-job-0, test-ls2r5p-6/big-job-0, test-ls2r5p-32/big-job-0, test-ls2r5p-17/big-job-0, test-ls2r5p-2/big-job-0, test-ls2r5p-5/big-job-0, test-ls2r5p-14/big-job-0, test-ls2r5p-7/medium-job-0, test-ls2r5p-33/big-job-0, test-ls2r5p-3/big-job-0, test-ls2r5p-34/big-job-0, test-ls2r5p-18/big-job-0, test-ls2r5p-7/big-job-0, test-ls2r5p-28/big-job-0]] :0
```

Working hypothesis is that code change from #98238, but this requires confirmation.

**Comment by wojtek-t** [comment]
This particular regression is purely Job-related (we only see problems with batchv1.Job objects).

/sig apps
/priority critical-urgent

@kubernetes/sig-apps-bugs @alculquicondor

@soltysh - FYI

/milestone v1.22

**Comment by jprzychodzen** [comment]
After internal testing it seems that #103644 can be a fix.

Added big scale presubmits to #103644
