### ISSUE TITLE
Installing network-manager-l2tp breaks the microk8s cluster

### ISSUE THREAD

**Issue by turowicz** [kubernetes/kubernetes#103661]
Details here: https://github.com/ubuntu/microk8s/issues/2410

**Comment by ehashman** [comment]
From the upstream issue, this appears to be a networking issue specific to your Ubuntu setup and distro packages. This is not something we can provide support with in upstream Kubernetes.

/close

**Comment by turowicz** [comment]
@ehashman cool, just making sure.
