### ISSUE TITLE
[Failing test] [sig-node] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod] when we need to admit a critical pod should be able to create and delete a critical pod [cos-stable1]

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103690]
/kind failing-test
/sig node

This test is failing on the serial job: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

/cc @fromanirh

**Comment by ehashman** [comment]
https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

**Comment by fromanirh** [comment]
Should be fixed by https://github.com/kubernetes/kubernetes/pull/103408
