### ISSUE TITLE
 [Failing Test][sig-node] ci-kubernetes-e2e-gce-scale-correctness

### ISSUE THREAD

**Issue by encodeflush** [kubernetes/kubernetes#103688]
#### Which jobs are failing:

ci-kubernetes-e2e-gce-scale-correctness

#### Which test(s) are failing:

* Kubernetes e2e suite: [sig-node] SSH should SSH to all nodes and run commands
* kubetest.Test

#### Since when has it been failing:

Jul 10 14:01:51 UTC+0200

#### Testgrid link:

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

#### Reason for failure:

Kubernetes e2e suite: [sig-node] SSH should SSH to all nodes and run commands:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/node/ssh.go:45 Jul 14 12:25:05.165: Ran echo "foo" \| grep "bar" on , got error error dialing  from bastion: missing port in address, expected <nil> /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
more [logs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1415280350170451968).

e2e.go: Test
```
error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Serial\]\|\[Disruptive\]\|\[Flaky\]\|\[Feature:.+\]\|\[DisabledForLargeClusters\] --minStartupPods=8 --node-schedulable-timeout=90m --logexporter-gcs-path=gs://sig-scalability-logs/ci-kubernetes-e2e-gce-scale-correctness/1415280350170451968 --report-dir=/logs/artifacts --disable-log-dump=true --cluster-ip-range=10.64.0.0/11: exit status 1
```
#### Anything else we need to know:
/sig node

**Comment by saschagrunert** [comment]
Uhhh, this may help here https://github.com/kubernetes/kubernetes/pull/103640

**Comment by ehashman** [comment]
/sig scalability
FYI

**Comment by spiffxp** [comment]
I got annoyed that I couldn't click through to see the logs, so now you can, ref: https://github.com/kubernetes/test-infra/issues/22923

**Comment by spiffxp** [comment]
/assign @wojtek-t @mm4tt 
SIG Scalability chairs, please find someone to address or call this a non-release-blocking failure

**Comment by mm4tt** [comment]
Assigning to current scalability oncall (https://go.k8s.io/oncall):

/assign @marseel

**Comment by wojtek-t** [comment]
This is sig-node issue - should be addres by SIG-node folks.

/sig node

**Comment by spiffxp** [comment]
https://github.com/kubernetes/kubernetes/pull/103640 is being discussed as a fix for this and I'm not sure it's correct

**Comment by spiffxp** [comment]
@wojtek-t is it sig scalability's intent that 5k node clusters should support SSH?

**Comment by spiffxp** [comment]
The SSH test in question passes in the "default" job: https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=SSH

So the fact that this failure is unique to a scalability job means to me that scalability needs to own at least some part of this

**Comment by marseel** [comment]
I did a little bit of digging and ci-kubernetes-e2e-gce-scale-correctness uses `- --gcp-ssh-proxy-instance-name=gce-scale-cluster-master` option in kubetest, which according to https://github.com/kubernetes/test-infra/blob/2b77449e7fcaa977b84e979f5544ad1eb6f1c7f8/kubetest/main.go#L90 seems to be setting KUBE_SSH_BASTION env. So I believe this is main difference between our scalability job and "default".

**Comment by saschagrunert** [comment]
Debugging the test in https://github.com/kubernetes/kubernetes/pull/103815 and providing a fix there. The crictl host PR (#103640) is doing something different.
