### ISSUE TITLE
cluster/gce/util.sh assumes that kubernetes-server-linux is staged if it exists locally, but may have been staged in a different project

### ISSUE THREAD

**Issue by ihmccreery** [kubernetes/kubernetes#10367]
As discussed in #9743, I'm seeing something very similar to @quinton-hoole:

    Jun 12 21:46:07 e2e-test-quinton-master startupscript: Running startup script /var/run/google.startup.script
    ...
    Jun 12 21:46:08 e2e-test-quinton-master startupscript: Mounting master-pd
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: Downloading binary release tar (https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-server-linux-amd64.tar.gz)
    Jun 12 21:46:14 e2e-test-quinton-master startupscript:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Jun 12 21:46:14 e2e-test-quinton-master startupscript:                                  Dload  Upload   Total   Spent    Left  Speed
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100   127  100   127    0     0   1316      0 --:--:-- --:--:-- --:--:--  1511
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: Downloading Salt tar (https://storage.googleapis.com/kubernetes-staging-8e55f027a8/devel/kubernetes-salt.tar.gz)
    Jun 12 21:46:14 e2e-test-quinton-master startupscript:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Jun 12 21:46:14 e2e-test-quinton-master startupscript:                                  Dload  Upload   Total   Spent    Left  Speed
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015100 35105  100 35105    0     0   815k      0 --:--:-- --:--:-- --:--:-- 1038k
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: Unpacking Salt tree and checking integrity of binary release tar
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: 
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: gzip: stdin: not in gzip format
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: tar: Child returned status 1
    Jun 12 21:46:14 e2e-test-quinton-master startupscript: tar: Error is not recoverable: exiting now
    Jun 12 21:46:29 e2e-test-quinton-master startupscript: Couldn't unpack Salt tree. Retrying...

During kube-up.sh I see:

    Creating gs://kubernetes-staging-4c2ab8624f
    Creating gs://kubernetes-staging-4c2ab8624f/...
    +++ Staging server tars to Google Storage: gs://kubernetes-staging-4c2ab8624f/devel
    +++ kubernetes-server-linux-amd64.tar.gz already staged ('rm ./cluster/../cluster/gce/../../cluster/../_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1' to force)

Looking in my developers console, I `kubernetes-salt.tar.gz`, but no `kubernetes-server-linux-amd64.tar.gz`.

I think this is a bug where we assume that because `_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1` exists, we've already staged to the correct project, which seems like the wrong assumption.

If I'm correct, the component would be `cluster/gce/util.sh:function copy-if-not-staged()`.

**Comment by ihmccreery** [comment]
To clarify, there are two problems here:

1. We're not correctly catching the problem that the master can't find the `kubernetes-server-linux-amd64.tar.gz` file;
2. We're assuming in `cluster/gce/util.sh` that has been staged if it exists locally, which it may not have been, (or at least not in the same project).

To reproduce, create a cluster with `kube-up.sh` in one project, then switch to a different project and run `kube-up.sh` again.

**Comment by zmerlynn** [comment]
I think the `"${tar}.sha1"` in that function just needs to become something like `"${tar}.${PROJECT}.sha1"`. My bad. :( This entire function has been more trouble than its worth - feel free to just gut the optimization, too.

**Comment by alex-mohr** [comment]
@zmerlynn  fwiw, seems like if we do want a test for has-it-been-staged, the most-robust approach would be to "gsutil ls" the object in question?

removing from v1.

**Comment by amygdala** [comment]
This should probably be its own issue, but just a note that the emitted info:
+++ kubernetes-server-linux-amd64.tar.gz already staged ('rm ./cluster/../cluster/gce/../../cluster/../_output/release-tars/kubernetes-server-linux-amd64.tar.gz.sha1' to force)

is incorrect.  The files are named *.uploaded.sha1, apparently.

**Comment by zmerlynn** [comment]
This bug is obsolete. I removed this code in 5a031bf52c988686db49815bf2ce09b21c27239b.
