### ISSUE TITLE
[Failing Test] [sig-scheduling] Pod should avoid nodes that have avoidPod annotation (ci-kubernetes-e2e-gci-gce-serial)

### ISSUE THREAD

**Issue by lambdanis** [kubernetes/kubernetes#103655]
#### Which jobs are failing:

ci-kubernetes-e2e-gci-gce-serial (gce-cos-master-serial)

#### Which test(s) are failing:

Kubernetes e2e suite.[sig-scheduling] SchedulerPriorities [Serial] Pod should avoid nodes that have avoidPod annotation

#### Since when has it been failing:

June 19th 2021 ([build](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial-kube-dns-nodecache/1406181768893042688))

#### Testgrid link:

Testgrid: https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-cos-master-serial&width=20
Prow history: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial

#### Reason for failure:
Looks like pods are scheduled where they shouldn't be? `bootstrap-e2e-minion-group`:
```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:265
Jul 12 16:12:11.309: Expected
    <string>: bootstrap-e2e-minion-group-7l0c
not to equal
    <string>: bootstrap-e2e-minion-group-7l0c
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/scheduling/priorities.go:325
```

#### Anything else we need to know:
The tests passes in maybe 20% of the builds, but it looks random, so I don't treat it as a flake.

At the moment there are also sig-storage tests consistently failing in this job: https://github.com/kubernetes/kubernetes/issues/102865, https://github.com/kubernetes/kubernetes/issues/103651. They don't look related though.

/sig scheduling
/kind failing-test

**Comment by kerthcet** [comment]
try to have a look.

**Comment by kerthcet** [comment]
try to have a look.

**Comment by alculquicondor** [comment]
This is expected. The feature (which was alpha) is now removed by default. Users can still enable it by switching to a v1beta1 scheduler component config.

Let's remove the test.
