### ISSUE TITLE
scheduler: Make it clear that EnqueueExtensions has the role of dynamic event handlers registration

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#103633]
Hello team 👋  (I'm sorry this Issue is not on the issue template.)

It is related to #100347 #101394
With #101394, we use EnqueueExtensions.EventsToRegister() for dynamic event handlers registration. 

So, now EnqueueExtensions has two roles.

1. move unschedulable Pods in internal scheduling queues efficiently
2. dynamic event handlers registration 

Currently, there is no description of role2 in EnqueueExtensions or EventsToRegister. So I think we should add some documents about this behavior.
And I also propose to rename `EnqueueExtensions` to `EventRegistrationExtensions` or something. What do you think?

/cc @Huang-Wei 
/sig scheduling

**Comment by Huang-Wei** [comment]
> So I think we should add some documents about this behavior.

I agree we can improve the documents (or in-line comments) to make the behavior clearly understandable.

>  And I also propose to rename `EnqueueExtensions` to `EventRegistrationExtensions` or something. What do you think?

Not quite a fan of the renaming. The interface `EnqueueExtensions` describes the semantics accurately - users can implement this interface to impact scheduler to enqueue pods efficiently. Although `EventsToRegister()` is the unique method of this interface, we may add more methods in the future. Rename the interface to `EventRegistrationExtensions` would restrict its semantics to "events registrations management" only, which doesn't look promising to me.

**Comment by kerthcet** [comment]
help to improve the document /assign

**Comment by kerthcet** [comment]
/assign
help to improve the document or maybe refactor the function name.

**Comment by sanposhiho** [comment]
> I agree we can improve the documents (or in-line comments) to make the behavior clearly understandable.

:)

> The interface EnqueueExtensions describes the semantics accurately 

On second thought, the event handler is used for enqueue pods, so its name is appropriate. 👍 
OK, so let's do improve documents only.

**Comment by Huang-Wei** [comment]
It's fixed by #103686.

/close
