### ISSUE TITLE
[Failing Test][sig-scalability] gce-cos-master-scalability-100

### ISSUE THREAD

**Issue by jupblb** [kubernetes/kubernetes#103606]
#### Which jobs are failing:
sig-release-master-blocking/gce-cos-master-scalability-100
#### Which test(s) are failing:
`e2e.go: diffResources`

#### Since when has it been failing:
July 9th, 20:13 PDT
#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-scalability-100
#### Reason for failure:
Most likely something is wrong with ssh auth.

The errors started with [the first failed run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413335052305043456) giving output:
```
measurement call TestMetrics - TestMetrics error: [action gather failed for EtcdMetrics measurement: unexpected error (code: 0) in ssh connection to master: &errors.errorString{s:"error getting SSH client to prow@34.138.181.78:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'"}]
```
and later [each](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413432949348503552) [run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413425150098935808) [gives](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1413417346365657088) an error similar to this one:
```
Error: 2 leaked resources
+NAME                                                      LOCATION    LOCATION_SCOPE  SIZE_GB  TYPE    STATUS
+e2e-big-dynamic-pvc-d9445c69-d845-4abf-b452-90838a0e4da0  us-east1-b  zone            10       pd-ssd  READY]
```

When debugging through the build log we can see the following errors occur:
```
Failed to execute 'sudo /bin/bash /home/kubernetes/bin/kube-master-internal-route.sh' on e2e-big-master despite 5 attempts
Last attempt failed with: load pubkey "/workspace/.ssh/google_compute_engine": invalid format
...
Failed to execute 'curl -s --cacert /etc/srv/kubernetes/pki/etcd-apiserver-ca.crt --cert /etc/srv/kubernetes/pki/etcd-apiserver-client.crt --key /etc/srv/kubernetes/pki/etcd-apiserver-client.key https://127.0.0.1:2379/v2/members/$(curl -s --cacert /etc/srv/kubernetes/pki/etcd-apiserver-ca.crt --cert /etc/srv/kubernetes/pki/etcd-apiserver-client.crt --key /etc/srv/kubernetes/pki/etcd-apiserver-client.key https://127.0.0.1:2379/v2/members -XGET | sed 's/{\"id/\n/g' | grep e2e-big-master\" | cut -f 3 -d \") -XDELETE -L 2>/dev/null' on e2e-big-master despite 5 attempts
Last attempt failed with: load pubkey "/workspace/.ssh/google_compute_engine": invalid format
...
Failed to execute 'curl -s  http://127.0.0.1:4002/v2/members/$(curl -s  http://127.0.0.1:4002/v2/members -XGET | sed 's/{\"id/\n/g' | grep e2e-big-master\" | cut -f 3 -d \") -XDELETE -L 2>/dev/null' on e2e-big-master despite 5 attempts
Last attempt failed with: load pubkey "/workspace/.ssh/google_compute_engine": invalid format
...
I0709 07:18:13.065470   14617 ssh.go:50] ssh to "e2e-big-master" finished with "load pubkey \"/workspace/.ssh/google_compute_engine\": invalid format\r\nsa_107361654189119518833@35.185.123.43: Permission denied (publickey).\r\nERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].\n": exit status 255
F0709 07:18:13.065566   14617 clusterloader.go:293] Error while setting up prometheus stack: exit status 255
```
while in a healthy run we would get e.g.:
```
Successfully executed 'sudo /bin/bash /home/kubernetes/bin/kube-master-internal-route.sh' on e2e-big-master
```

The node to which the volume `e2e-big-dynamic-pvc-d9445c69-d845-4abf-b452-90838a0e4da0` was attached shows no significant error in its logs.

**Comment by marseel** [comment]
/cc @ameukam 
I've talked with Arnaud and he pointed that this PR might be related to this issue: 
https://github.com/kubernetes/k8s.io/pull/2296

**Comment by ameukam** [comment]
Revert of kubernetes/k8s.io#2296 have been applied: https://github.com/kubernetes/k8s.io/pull/2312.

**Comment by marseel** [comment]
I've triggered presubmit, looks like it helped: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103610/pull-kubernetes-e2e-gce-100-performance/1413475339442589696

**Comment by ehashman** [comment]
I'm not sure if https://github.com/kubernetes/kubernetes/issues/103624 is a dupe or related.

**Comment by ameukam** [comment]
> I'm not sure if #103624 is a dupe or related.

@ehashman It's related to the change we introduced. Looking at https://prow.k8s.io/?job=ci-kubernetes-e2e-gci-gce-scalability and https://testgrid.k8s.io/sig-scalability-gce#gce-cos-master-scalability-100, I don't think the job is still impacted.

**Comment by marseel** [comment]
/close
I think we can close this issue now. Revert fixed issue.
