### ISSUE TITLE
Pods in CreateContainerConfigError keep pulling image / exceed docker hub rate limit

### ISSUE THREAD

**Issue by TheKangaroo** [kubernetes/kubernetes#103643]
#### What happened:
A pod stuck in CreateContainerConfigError (in my case because svcat wasn't ready and the pod depends on an s3 bucket) keeps pulling the image without any crash loop backoff.
We have a payed dockerhub subscription to pull images, but it turned out this failing daemonset (9 pods in total) exceeds the "fair use" policy of docker (in our case the average was 289,400 pulls/day).
The node does not really pull the image that many times per day, but even the "pull check" counts as a pull for docker hub.

#### What you expected to happen:
I would expect the pod to crash loop backoff on CreateContainerConfigError and therefore does not exceed docker hub rate limit.

#### How to reproduce it (as minimally and precisely as possible):
Deploy a pod with CreateContainerConfigError e.g. use a non-ready (cluster)servicebroker.
`kubectl describe <pod>` to see a huge amount of image pulls in the last x minutes.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.17.6 and 1.21.0
- Cloud provider or hardware configuration: onPrem,
- OS (e.g: `cat /etc/os-release`): Flatcar Container Linux by Kinvolk 2605.7.0 (Oklo)
- Kernel (e.g. `uname -a`): Linux k8s-master-01.lxsbx.ka.de.dm-drogeriemarkt.com 5.4.72-flatcar #1 SMP Fri Oct 23 16:42:52 -00 2020 x86_64 Intel(R) Xeon(R) CPU E5-2699 v4 @ 2.20GHz GenuineIntel GNU/Linux
- Install tools: deployed via cloud-config/ignition as systemd units

**Comment by novahe** [comment]
Hi, @TheKangaroo I reproduced it by the following yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: create-container-config-error-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:latest 
      imagePullPolicy: Always  # note！
      command: ["sleep", "1000000"]
      env:
        - name: ENV_VAR_USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-configmap # not exist
              key: user.name
```

if `imagePullPolicy: Always`, I watched event whith command `kubectl get event -w`：

```bash
43s         Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
116s        Normal    Pulled      pod/create-container-config-error-pod   Successfully pulled image "busybox:latest" in 7.7143107s
97s         Normal    Pulled      pod/create-container-config-error-pod   Successfully pulled image "busybox:latest" in 5.234163641s
79s         Normal    Pulled      pod/create-container-config-error-pod   Successfully pulled image "busybox:latest" in 6.423541367s
62s         Normal    Pulled      pod/create-container-config-error-pod   Successfully pulled image "busybox:latest" in 5.33199454s
43s         Normal    Pulled      pod/create-container-config-error-pod   Successfully pulled image "busybox:latest" in 5.917402327s
```

I modified  `imagePullPolicy: IfNotPresent`,  and watched event：

```bash
LAST SEEN   TYPE      REASON      OBJECT                                  MESSAGE
74s         Normal    Scheduled   pod/create-container-config-error-pod   Successfully assigned default/create-container-config-error-pod to master
8s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
8s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
1s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
0s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
1s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
0s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
0s          Warning   Failed      pod/create-container-config-error-pod   Error: couldn't find key user.name in ConfigMap default/user-configmap
0s          Normal    Pulled      pod/create-container-config-error-pod   Container image "busybox:latest" already present on machine
```

It seems to look good. From the code, it will not always pull the image, when the `imagePullPolicy: IfNotPresent`  configuration is set.

https://github.com/kubernetes/kubernetes/blob/68922e3deb4696f4c0268ee68e03c816acd4feec/pkg/kubelet/images/image_manager.go#L116-L128

So, your configuration is `imagePullPolicy: Always`?

If yes, you can modify it to `imagePullPolicy: IfNotPresent`  and try.



> I would expect the pod to crash loop backoff on CreateContainerConfigError and therefore does not exceed docker hub rate limit.

In my opinion, `crash loop backoff` is only applicable to scenarios where the pod changes from the `running` to the `crashing`.  All running pods on kubernetes have crashed, It is to protect the kubernetes cluster and prevent the kubernetes cluster from shutdown due to excessive pressure.

`CreateContainerConfigError`is only triggered at the first start. No `crash loop backoff` would start the pod more quickly.

**Comment by TheKangaroo** [comment]
Thank you for investigating this :)
Yes we use imagePullPolicy always almost everywhere in our clusters.
This is a bit unfortunate for our setup, since a single broken deployment with imagePullPolicy always can exceed the rate limit. We don't enforce any imagePullPolicy for our users so there will always be the possibility for our users to break this. 
At least it's a point to start to know, that imagePullPolicy can prevent this.
