### ISSUE TITLE
Volume unmount failures saying "could not get consistent content of /proc/mounts"

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#103754]
We saw these kinds of errors in Kubelet when [trying to cleanup]((https://github.com/kubernetes/kubernetes/blob/2da4d48e6d519fe52914b90a91cd5a64793d2bc4/pkg/volume/util/operationexecutor/operation_generator.go#L835-L840)) bind-mounts for the pod’s mounted subPaths:

`Jun 25 06:57:48 ip-172-18-228-96.ec2.internal kubelet[4955]: E0625 06:57:48.750465    4955 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/configmap/d4e712ef-fc5b-476c-aae4-3b37eff4a947-php-config podName:d4e712ef-fc5b-476c-aae4-3b37eff4a947 nodeName:}" failed. No retries permitted until 2021-06-25 06:57:49.25043195 +0000 UTC m=+138568.074599660 (durationBeforeRetry 500ms). *Error*: "error cleaning subPath mounts for volume \"php-config\" (UniqueName: \"kubernetes.io/configmap/d4e712ef-fc5b-476c-aae4-3b37eff4a947-php-config\") pod \"d4e712ef-fc5b-476c-aae4-3b37eff4a947\" (UID: \"d4e712ef-fc5b-476c-aae4-3b37eff4a947\") : error processing /var/lib/kubelet/pods/d4e712ef-fc5b-476c-aae4-3b37eff4a947/volume-subpaths/php-config/main: error cleaning subpath mount /var/lib/kubelet/pods/d4e712ef-fc5b-476c-aae4-3b37eff4a947/volume-subpaths/php-config/main/15: could not get consistent content of /proc/mounts after 3 attempts"`

They happen when the Kubelet attempts to get a consistent content of the `/proc/mounts` file across consecutive reads, but fails [despite 3 attempts](https://github.com/kubernetes/utils/blob/0e1f9d6934776f537ca6a2a95ceb93d800c0628f/mount/mount_helper_unix.go#L34-L35). Given heavy churn of volumes/mounts on that node, the `/proc/mounts` file is changing very frequently, increasing the likelihood of the above issue. The exact call trace seems to be the following:
- Kubelet calling [UnmountVolume](https://github.com/kubernetes/kubernetes/blob/2da4d48e6d519fe52914b90a91cd5a64793d2bc4/pkg/kubelet/volumemanager/reconciler/reconciler.go#L454)
- which calls [GenerateUnmountVolumeFunc](https://github.com/kubernetes/kubernetes/blob/2da4d48e6d519fe52914b90a91cd5a64793d2bc4/pkg/volume/util/operationexecutor/operation_executor.go#L859) which calls [subpather.CleanSubPaths](https://github.com/kubernetes/kubernetes/blob/2da4d48e6d519fe52914b90a91cd5a64793d2bc4/pkg/volume/util/operationexecutor/operation_generator.go#L837-L838)
- which calls [doCleanSubPaths](https://github.com/kubernetes/kubernetes/blob/2da4d48e6d519fe52914b90a91cd5a64793d2bc4/pkg/volume/util/subpath/subpath_linux.go#L58) which calls [doCleanSubPath](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/util/subpath/subpath_linux.go#L252)
- which calls [mount.CleanupMountPoint](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/util/subpath/subpath_linux.go#L295) (with extensiveMountPointCheck set to `true`) which calls [doCleanupMountPoint](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount_helper_common.go#L41)
- which calls [removePathIfNotMountPoint](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount_helper_common.go#L90) which calls [IsNotMountPoint](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount_helper_common.go#L119) (since extensiveMountPointCheck == true)
- which calls [mounter.List](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount.go#L254) that calls [ListProcMounts](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount_linux.go#L291)
- where we try to do the [ConsistentRead](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/mount-utils/mount_linux.go#L503) of the `/proc/mounts` file

The reason for doing this consistency check is unclear to me. After some tracking, it seems to date back to this old pull request https://github.com/kubernetes/kubernetes/pull/3180 by @thockin. Tim - could you explain the reason you had on your mind for it? :)

The effect of this issue is it seems to slow down the pod cleanup latency by up to 1s (due to the retries) on busy nodes. We saw this in the unmount codepath, but could potentially be happening at other places too where we try listing the mounts.

W.r.t the fix, do any of these make sense?
- increase the no. of attempts for the consistent read
- get rid of the consistent read check if unneeded
- ignore these errors

/sig storage
/sig scalability

**Comment by shyamjvs** [comment]
@thockin @msau42 @jsafrane - any thoughts on the above?

**Comment by msau42** [comment]
The number of read attempts was increased recently for only fc and iscsi volume types: https://github.com/kubernetes/kubernetes/pull/102059

I believe the concern about more broadly increasing the count was load.

@kubernetes/sig-storage-bugs 
cc @gnufied @jingxu97

**Comment by gnufied** [comment]
Did the volume stay in that state or unmount eventually succeeded? One of the reasoning of not increasing the number of attempts everywhere was - unmount operation is always retried and hence if we can't get consistent read after 3 attempts during this umount operation then we will retry next time.

**Comment by jsafrane** [comment]
> The reason for doing this consistency check is unclear to me. After some tracking, it seems to date back to this old pull request #3180 by @thockin. Tim - could you explain the reason you had on your mind for it? :)

Kernel does not guarantee that reading a single /proc/ file with two (or more) `read` calls is consistent. The first `read()` can return one version and second the `read()`, continuing where the first left, can return content of another version of the mount table. Hence the check.

**Comment by shyamjvs** [comment]
Thanks for clarifying @jsafrane. On digging a bit I found the following:

> /proc/mounts is atomic within a single read system call. So if you read the whole file all at once, you get a single consistent snapshot of the mount points on the system. However, if you use several read system calls -- and if the file is big, this is exactly what will happen if you use normal I/O libraries and don't pay special attention to this issue -- you will be subject to a race condition. Not only will you not get a consistent snapshot, but mount points which were present before you started and never stopped being present might go missing in what you see. To see that it's atomic for one read(), look at [m_start() in fs/namespace.c](http://lxr.linux.no/linux+v2.6.38/fs/namespace.c#L889) and see it grab a semaphore that guards the list of mountpoints, which it keeps until m_stop(), which is called when the read() is done. To see what can go wrong, see [this bug from last year](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593516) (same one I linked above) in otherwise high-quality software that blithely read /proc/mounts.

(source: https://stackoverflow.com/questions/5713451/is-it-safe-to-parse-a-proc-file)

Based on above, do you think it's possible to optimize just the mount/unmount cases by only checking consistency of the entries corresponding to volume that is being mounted/unmounted? Or can that still result in incorrect behavior?

**Comment by shyamjvs** [comment]
> Did the volume stay in that state or unmount eventually succeeded?

@gnufied It does seem to succeed eventually, although taking up to a few extra seconds for the worst-case volumes.

> One of the reasoning of not increasing the number of attempts everywhere was - unmount operation is always retried and hence if we can't get consistent read after 3 attempts during this umount operation then we will retry next time.

But it seems like a retry for reading `/proc/mounts` file is much faster compared to retry of the volume unmount operation itself, the latter being [exponentially backed off](https://github.com/kubernetes/kubernetes/blob/47e1df8f4e86af1904ec9b3ecf427e1f1178be6e/pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go#L154) starting at 0.5s. So cost of unmount retries seems higher. Wdyt?

**Comment by jsafrane** [comment]
> Based on above, do you think it's possible to optimize just the mount/unmount cases by only checking consistency of the entries corresponding to volume that is being mounted/unmounted? Or can that still result in incorrect behavior?

`read()` can return a half of a line, with the rest of it in a subsequent `read()`. But the second `read()` can be with a different mount table. Hence the line with the mount that the code is interested in may be inconsistent too.

Nr. of /proc/mount read attempts has been increased recently. How often do you see `could not get consistent content of /proc/mounts` in your logs? Kubelet already retries after such failure and there is no user visible bug. I'd like to avoid premature optimization if it happens once in a while.

**Comment by manugupt1** [comment]
Hi @jsafrane 

QQ: Why do need we need an `extensiveMountPointCheck` for subPath volumess?
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/subpath/subpath_linux.go#L297

FYI: I am investigating this at https://github.com/kubernetes/kubernetes/issues/104976

**Comment by wongma7** [comment]
re: why extensive check must be done for subpaths, it must be because for bind mounts the stat method used by IsLikelyNotMountPoint does not work so for subpath volumes it makes sense we are forced to do the extensive check else we may remove data on host instead of the mount point...ref: https://github.com/kubernetes/kubernetes/issues/72347

@manugupt1 and I found moby's implementation which tries to use openat2 https://github.com/moby/sys/blob/76a42cd566e5f05c3155179ea779e418df4ff4f9/mountinfo/mounted_linux.go#L10-L11 before falling back to reading /proc/mounts but it depends on newer 5.6+ kernels.

@jsafrane in #104976 this error surfaces to users as unmount failure attempts, it seems like mount/unmount attempts deadlock if there are too many in flight and a consistent read is effectively impossible, when there are x # of pods * y # of subpaths per pod. It is possible the root cause of #104976 is this issue, any ideas for how to confirm? Like let's say we run the same # of pods * subpaths but with a patched kubelet where extensiveMountPointCheck is set to false https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/subpath/subpath_linux.go#L297, if the pods mounts/unmounts eventually converge instead of hanging then that should confirm this is the cause?

**Comment by BenTheElder** [comment]
/remove-lifecycle stale
Fairly recent activity on linked PR.

**Comment by jsafrane** [comment]
This should be fixed by https://github.com/kubernetes/kubernetes/pull/109217
