### ISSUE TITLE
the server doesn't have a resource type "coredns"

### ISSUE THREAD

**Issue by 916264367** [kubernetes/kubernetes#103798]
Hello everyone, I tried to deploy kubernetes for the first time. I found that my pod couldn't start normally. I checked the log and reported an error. What's wrong with it？
![image](https://user-images.githubusercontent.com/51771785/126317515-46c37a1e-c40d-4262-9a10-a15c03659a66.png)

**Comment by 916264367** [comment]
> @916264367：这个问题没有签名标签。请使用以下命令之一添加适当的标签：
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> 有关可用的 SIG、工作组和委员会的[列表](https://git.k8s.io/community/sig-list.md)，请参阅[组列表](https://git.k8s.io/community/sig-list.md)。
Sorry, there is an error in my command input. But I still can't solve the problem
![image](https://user-images.githubusercontent.com/51771785/126318294-00bbd39a-bae6-4d19-a495-7aa252aa4411.png)

**Comment by neolit123** [comment]
it should be `kubectl describe po <some-pod> ...`
please use the support channels for questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
