### ISSUE TITLE
Managing Resources Memory for Containers

### ISSUE THREAD

**Issue by linl12138** [kubernetes/kubernetes#103761]
When I managing resources memory for containers, if  spec.containers[].resources.requests.memory equal 100m,pod can run sucessfully,but if I add limits setting, the memoy unit is also 'm',the pod will start failed.
According document,the valid memoty unit includes 'E, P, T, G, M, K',or 'Ei, Pi, Ti, Gi, Mi, Ki',but why using  'm' cannot Return syntax error.

The first case(running sucessfully):
resources:
    requests:
        cpu: 0.3
        memory: 100m
The second case(start failed):
resources:
    requests:
        cpu: 0.3
        memory: 100m
    limits:
        cpu: 0.4
        memory: 200m

**Comment by neolit123** [comment]
please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by neolit123** [comment]
if you think you found a problem in the documentation log an issue in kubernetes/website.
