### ISSUE TITLE
[Failing Test] [sig-cluster-lifecycle] conformance tests conformance (periodic-cluster-api-provider-aws-e2e-conformance-release-0-6-with-k8s-ci-artifacts)

### ISSUE THREAD

**Issue by lambdanis** [kubernetes/kubernetes#103706]
#### Which jobs are failing:

periodic-cluster-api-provider-aws-e2e-conformance-release-0-6-with-k8s-ci-artifacts (periodic-conformance-release-0-6-k8s-main)
Note: this job was renamed from periodic-cluster-api-provider-aws-e2e-conformance-v1alpha3-with-k8s-ci-artifacts (capa-conformance-v1alpha3-k8s-master) on July 2nd in https://github.com/kubernetes/test-infra/pull/22771/

#### Which test(s) are failing:

* capa-e2e-conformance: conformance tests conformance
* capa-e2e-conformance: AfterSuite

#### Since when has it been failing:

July 1st 2021 ([build](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-v1alpha3-with-k8s-ci-artifacts/1410637617170485248))

#### Testgrid link:

Testgrid: https://testgrid.k8s.io/sig-release-master-informing#periodic-conformance-release-0-6-k8s-main
Prow history: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-release-0-6-with-k8s-ci-artifacts

#### Reason for failure:

Timeouts:
```
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/conformance/conformance_test.go:104
Timed out after 1200.000s.
Expected
    <bool>: false
to be true
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.19/test/framework/cluster_helpers.go:173

/home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/conformance/conformance_suite_test.go:52
Timed out after 1200.000s.
Expected
    <bool>: false
to be true
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api@v0.3.19/test/framework/cluster_helpers.go:173
```

Logs have many "connection refused" errors:
```
E0713 19:57:08.479659   22687 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.17/tools/cache/reflector.go:105: Failed to list *v1.Event: Get "https://127.0.0.1:38509/api/v1/namespaces/conformance-rx4hdv/events?limit=500&resourceVersion=0": dial tcp 127.0.0.1:38509: connect: connection refused
```

#### Anything else we need to know:

The same job has also some flakes, e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-release-0-6-with-k8s-ci-artifacts/1415347543612592128. I saw "error waiting for daemon pod to start" and "pod ran to completion" errors. But these flakes are rare.

/sig cluster-lifecycle

**Comment by randomvariable** [comment]
Should be fixed with two things:
https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2581
and then switching our reporting to the main branch of that repo. filing now.

**Comment by randomvariable** [comment]
We've switched to main branch in test-infra, so once the above PR is in, we should be good to go

**Comment by randomvariable** [comment]
We should be back in business at the next periodic.

**Comment by randomvariable** [comment]
still saw the `should provide DNS for ExternalName services [Conformance] [It]` flake

**Comment by lambdanis** [comment]
We have a green build :tada:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-aws-e2e-conformance-with-k8s-ci-artifacts/1415845983945756672
https://k8s-testgrid.appspot.com/sig-release-master-informing#periodic-conformance-main-k8s-main

I'm calling it closed.
