### ISSUE TITLE
use of closed network connection;Cause the node status to become not ready

### ISSUE THREAD

**Issue by imkos** [kubernetes/kubernetes#103765]
k8s version: 1.20.8
1):
e59e-4b2c-b7cc-0fe7a2394fc0-golib") pod "msgapiserver-094b322a-b744-4a0f-bbb6-2dc87dfd44a3-b6d3v-m4n4x" (UID: "336c3203-e59e-4b2c-b7cc-0fe7a2394fc0")
Jul 19 18:02:42 node1 kubelet[2129392]: E0719 18:02:42.287195 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:9946: use of closed network connection
Jul 19 18:02:43 node1 kubelet[2129392]: I0719 18:02:43.052476 2129392 log.go:181] http: superfluous response.WriteHeader call from k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader (httplog.go:217)
Jul 19 18:02:51 node1 kubelet[2129392]: E0719 18:02:51.421566 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:10340: use of closed network connection
Jul 19 18:02:56 node1 kubelet[2129392]: E0719 18:02:56.735537 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:10584: use of closed network connection
Jul 19 18:02:57 node1 kubelet[2129392]: E0719 18:02:57.678009 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:10644: use of closed network connection
Jul 19 18:03:14 node1 kubelet[2129392]: E0719 18:03:14.800017 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:11338: use of closed network connection
Jul 19 18:03:19 node1 kubelet[2129392]: E0719 18:03:19.541723 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:11596: use of closed network connection
Jul 19 18:03:21 node1 kubelet[2129392]: I0719 18:03:21.138080 2129392 topology_manager.go:187] [topologymanager] Topology Admit Handler
Jul 19 18:03:21 node1 kubelet[2129392]: I0719 18:03:21.225059 2129392 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/88e228ba-d7eb-41b6-9426-703ede94a69b-config-volume") pod "msgapiserver-78cdf8bf9d-k6lvx" (UID: "88e228ba-d7eb-41b6-9426-703ede94a69b")
Jul 19 18:03:21 node1 kubelet[2129392]: I0719 18:03:21.225141 2129392 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-5kbgl" (UniqueName: "kubernetes.io/secret/88e228ba-d7eb-41b6-9426-703ede94a69b-default-token-5kbgl") pod "msgapiserver-78cdf8bf9d-k6lvx" (UID: "88e228ba-d7eb-41b6-9426-703ede94a69b")
Jul 19 18:03:21 node1 kubelet[2129392]: I0719 18:03:21.225195 2129392 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "host-time" (UniqueName: "kubernetes.io/host-path/88e228ba-d7eb-41b6-9426-703ede94a69b-host-time") pod "msgapiserver-78cdf8bf9d-k6lvx" (UID: "88e228ba-d7eb-41b6-9426-703ede94a69b")
Jul 19 18:03:21 node1 kubelet[2129392]: W0719 18:03:21.964063 2129392 pod_container_deletor.go:79] Container "6fbf7787066fc7f444eec94441168cb1fa4e52f370b93f4366f8a2462b912c7e" not found in pod's containers
Jul 19 18:03:24 node1 kubelet[2129392]: I0719 18:03:24.036050 2129392 scope.go:111] [topologymanager] RemoveContainer - Container ID: ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242
Jul 19 18:03:24 node1 kubelet[2129392]: I0719 18:03:24.046779 2129392 scope.go:111] [topologymanager] RemoveContainer - Container ID: ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242
Jul 19 18:03:24 node1 kubelet[2129392]: E0719 18:03:24.047266 2129392 remote_runtime.go:332] ContainerStatus "ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242
Jul 19 18:03:24 node1 kubelet[2129392]: W0719 18:03:24.047292 2129392 pod_container_deletor.go:52] [pod_container_deletor] DeleteContainer returned error for (id={docker ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242}): failed to get container status "ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242": rpc error: code = Unknown desc = Error: No such container: ee31cb5f057972f969159d4cd27d97123dfa9d099e052c6f858efeaa87668242

2):
ul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.104956 2129392 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626689400-fd6rt": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.105017 2129392 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626689400-fd6rt": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.105030 2129392 kuberuntime_manager.go:755] createPodSandbox for pod "stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626689400-fd6rt": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.105073 2129392 pod_workers.go:191] Error syncing pod 65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb ("stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)"), skipping: failed to "CreatePodSandbox" for "stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)" with CreatePodSandboxError: "CreatePodSandbox for pod \"stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"stat-cron-1626689400-fd6rt\": operation timeout: context deadline exceeded"
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.106128 2129392 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626689400-8m5zr": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.106161 2129392 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "userserver-cron-1626689400-8m5zr_default(319f534b-b005-4e60-a031-33e975298192)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626689400-8m5zr": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.106177 2129392 kuberuntime_manager.go:755] createPodSandbox for pod "userserver-cron-1626689400-8m5zr_default(319f534b-b005-4e60-a031-33e975298192)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626689400-8m5zr": operation timeout: context deadline exceeded
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.106220 2129392 pod_workers.go:191] Error syncing pod 319f534b-b005-4e60-a031-33e975298192 ("userserver-cron-1626689400-8m5zr_default(319f534b-b005-4e60-a031-33e975298192)"), skipping: failed to "CreatePodSandbox" for "userserver-cron-1626689400-8m5zr_default(319f534b-b005-4e60-a031-33e975298192)" with CreatePodSandboxError: "CreatePodSandbox for pod \"userserver-cron-1626689400-8m5zr_default(319f534b-b005-4e60-a031-33e975298192)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"userserver-cron-1626689400-8m5zr\": operation timeout: context deadline exceeded"
Jul 19 18:12:10 node1 kubelet[2129392]: E0719 18:12:10.448412 2129392 kuberuntime_manager.go:965] PodSandboxStatus of sandbox "4bd303e5d6fe642592e07947cc33904a961d83e7d77302fd727164aa2c91d5b8" for pod "stat-cron-1626689400-fd6rt_default(65e7c63a-9bf3-4b6d-bb9a-b12ce8d868bb)" error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Jul 19 18:13:10 node1 kubelet[2129392]: I0719 18:13:10.545244 2129392 setters.go:577] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2021-07-19 18:13:10.54520597 +0800 CST m=+31877.406385046 LastTransitionTime:2021-07-19 18:13:10.54520597 +0800 CST m=+31877.406385046 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active 3m0.113659495s ago; threshold is 3m0s}
Jul 19 18:13:10 node1 kubelet[2129392]: E0719 18:13:10.668119 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.236558019s ago; threshold is 3m0s
Jul 19 18:13:10 node1 kubelet[2129392]: E0719 18:13:10.768243 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.336681377s ago; threshold is 3m0s
Jul 19 18:13:10 node1 kubelet[2129392]: E0719 18:13:10.968365 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.53679794s ago; threshold is 3m0s
Jul 19 18:13:11 node1 kubelet[2129392]: E0719 18:13:11.368499 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.936927463s ago; threshold is 3m0s
Jul 19 18:13:12 node1 kubelet[2129392]: E0719 18:13:12.168619 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m1.737054581s ago; threshold is 3m0s
Jul 19 18:13:13 node1 kubelet[2129392]: E0719 18:13:13.768781 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m3.33719758s ago; threshold is 3m0s
Jul 19 18:13:16 node1 kubelet[2129392]: E0719 18:13:16.968918 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m6.537352582s ago; threshold is 3m0s
Jul 19 18:13:21 node1 kubelet[2129392]: E0719 18:13:21.969044 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m11.537475661s ago; threshold is 3m0s
Jul 19 18:13:26 node1 kubelet[2129392]: E0719 18:13:26.969181 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m16.537604119s ago; threshold is 3m0s
Jul 19 18:13:31 node1 kubelet[2129392]: E0719 18:13:31.969331 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m21.537752205s ago; threshold is 3m0s
Jul 19 18:13:36 node1 kubelet[2129392]: E0719 18:13:36.969455 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m26.537890131s ago; threshold is 3m0s
Jul 19 18:13:41 node1 kubelet[2129392]: E0719 18:13:41.969592 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m31.53802405s ago; threshold is 3m0s
Jul 19 18:13:46 node1 kubelet[2129392]: E0719 18:13:46.969696 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m36.538123538s ago; threshold is 3m0s
Jul 19 18:13:51 node1 kubelet[2129392]: E0719 18:13:51.969834 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m41.538261871s ago; threshold is 3m0s
Jul 19 18:13:56 node1 kubelet[2129392]: E0719 18:13:56.969957 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m46.538393044s ago; threshold is 3m0s
Jul 19 18:14:01 node1 kubelet[2129392]: E0719 18:14:01.970079 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m51.538514534s ago; threshold is 3m0s
Jul 19 18:14:06 node1 kubelet[2129392]: E0719 18:14:06.970197 2129392 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m56.538633671s ago; threshold is 3m0s

**Comment by neolit123** [comment]
do you have sufficient ports available on your host?
https://serverfault.com/questions/261663/on-linux-how-can-i-tell-how-many-ephemeral-ports-are-left-available

/sig node network
/kind support
unclear if bug / support ticket.

**Comment by imkos** [comment]
@neolit123 
[root@node1 ~]# ss -s
Total: 599
TCP:   503 (estab 71, closed 385, orphaned 0, timewait 47)

Transport Total     IP        IPv6
RAW	  0         0         0
UDP	  8         5         3
TCP	  118       98        20
INET	  126       103       23
FRAG	  0         0         0

**Comment by imkos** [comment]
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.015431    1082 topology_manager.go:187] [topologymanager] Topology Admit Handler
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.043337    1082 topology_manager.go:187] [topologymanager] Topology Admit Handler
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155716    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "host-time" (UniqueName: "kubernetes.io/host-path/0d2f30f8-b16f-44f4-a588-d4a15befa39f-host-time") pod "userserver-cron-1626833400-7rjp6" (UID: "0d2f30f8-b16f-44f4-a588-d4a15befa39f")
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155754    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/bb11f2f0-0786-4524-82ee-e0abedd7f403-config-volume") pod "stat-cron-1626833400-zh4xf" (UID: "bb11f2f0-0786-4524-82ee-e0abedd7f403")
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155772    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/0d2f30f8-b16f-44f4-a588-d4a15befa39f-config-volume") pod "userserver-cron-1626833400-7rjp6" (UID: "0d2f30f8-b16f-44f4-a588-d4a15befa39f")
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155790    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-5kbgl" (UniqueName: "kubernetes.io/secret/bb11f2f0-0786-4524-82ee-e0abedd7f403-default-token-5kbgl") pod "stat-cron-1626833400-zh4xf" (UID: "bb11f2f0-0786-4524-82ee-e0abedd7f403")
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155813    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "host-time" (UniqueName: "kubernetes.io/host-path/bb11f2f0-0786-4524-82ee-e0abedd7f403-host-time") pod "stat-cron-1626833400-zh4xf" (UID: "bb11f2f0-0786-4524-82ee-e0abedd7f403")
Jul 21 10:10:09 node1 kubelet[1082]: I0721 10:10:09.155934    1082 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-5kbgl" (UniqueName: "kubernetes.io/secret/0d2f30f8-b16f-44f4-a588-d4a15befa39f-default-token-5kbgl") pod "userserver-cron-1626833400-7rjp6" (UID: "0d2f30f8-b16f-44f4-a588-d4a15befa39f")
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.403065    1082 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626833400-zh4xf": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.403124    1082 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626833400-zh4xf": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.403139    1082 kuberuntime_manager.go:755] createPodSandbox for pod "stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "stat-cron-1626833400-zh4xf": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.403182    1082 pod_workers.go:191] Error syncing pod bb11f2f0-0786-4524-82ee-e0abedd7f403 ("stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)"), skipping: failed to "CreatePodSandbox" for "stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)" with CreatePodSandboxError: "CreatePodSandbox for pod \"stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"stat-cron-1626833400-zh4xf\": operation timeout: context deadline exceeded"
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.408891    1082 remote_runtime.go:116] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626833400-7rjp6": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.408915    1082 kuberuntime_sandbox.go:70] CreatePodSandbox for pod "userserver-cron-1626833400-7rjp6_default(0d2f30f8-b16f-44f4-a588-d4a15befa39f)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626833400-7rjp6": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.408927    1082 kuberuntime_manager.go:755] createPodSandbox for pod "userserver-cron-1626833400-7rjp6_default(0d2f30f8-b16f-44f4-a588-d4a15befa39f)" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod "userserver-cron-1626833400-7rjp6": operation timeout: context deadline exceeded
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.408962    1082 pod_workers.go:191] Error syncing pod 0d2f30f8-b16f-44f4-a588-d4a15befa39f ("userserver-cron-1626833400-7rjp6_default(0d2f30f8-b16f-44f4-a588-d4a15befa39f)"), skipping: failed to "CreatePodSandbox" for "userserver-cron-1626833400-7rjp6_default(0d2f30f8-b16f-44f4-a588-d4a15befa39f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"userserver-cron-1626833400-7rjp6_default(0d2f30f8-b16f-44f4-a588-d4a15befa39f)\" failed: rpc error: code = Unknown desc = failed to start sandbox container for pod \"userserver-cron-1626833400-7rjp6\": operation timeout: context deadline exceeded"
Jul 21 10:12:09 node1 kubelet[1082]: E0721 10:12:09.551588    1082 kuberuntime_manager.go:965] PodSandboxStatus of sandbox "274b5062fc5bb9af75d4c8c66cefe93183a7aee1f6cec5e73e70075696ee0b9d" for pod "stat-cron-1626833400-zh4xf_default(bb11f2f0-0786-4524-82ee-e0abedd7f403)" error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Jul 21 10:13:09 node1 kubelet[1082]: I0721 10:13:09.879728    1082 setters.go:577] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2021-07-21 10:13:09.879700705 +0800 CST m=+142206.106938509 LastTransitionTime:2021-07-21 10:13:09.879700705 +0800 CST m=+142206.106938509 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active 3m0.352359086s ago; threshold is 3m0s}
Jul 21 10:13:10 node1 kubelet[1082]: E0721 10:13:10.334669    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.80730835s ago; threshold is 3m0s
Jul 21 10:13:10 node1 kubelet[1082]: E0721 10:13:10.434785    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.907427765s ago; threshold is 3m0s
Jul 21 10:13:10 node1 kubelet[1082]: E0721 10:13:10.634903    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m1.107541081s ago; threshold is 3m0s
Jul 21 10:13:11 node1 kubelet[1082]: E0721 10:13:11.035020    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m1.507662094s ago; threshold is 3m0s
Jul 21 10:13:11 node1 kubelet[1082]: E0721 10:13:11.835080    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m2.307719235s ago; threshold is 3m0s
Jul 21 10:13:13 node1 kubelet[1082]: E0721 10:13:13.435218    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m3.907859334s ago; threshold is 3m0s
Jul 21 10:13:16 node1 kubelet[1082]: E0721 10:13:16.635314    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m7.107954868s ago; threshold is 3m0s
Jul 21 10:13:21 node1 kubelet[1082]: E0721 10:13:21.635455    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m12.108092502s ago; threshold is 3m0s
Jul 21 10:13:26 node1 kubelet[1082]: E0721 10:13:26.635589    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m17.108220387s ago; threshold is 3m0s
Jul 21 10:13:31 node1 kubelet[1082]: E0721 10:13:31.635725    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m22.108356897s ago; threshold is 3m0s
Jul 21 10:13:36 node1 kubelet[1082]: E0721 10:13:36.635869    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m27.108497578s ago; threshold is 3m0s
Jul 21 10:13:41 node1 kubelet[1082]: E0721 10:13:41.636003    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m32.108637475s ago; threshold is 3m0s
Jul 21 10:13:46 node1 kubelet[1082]: E0721 10:13:46.636133    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m37.108770199s ago; threshold is 3m0s
Jul 21 10:13:51 node1 kubelet[1082]: E0721 10:13:51.636717    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m42.109342918s ago; threshold is 3m0s
Jul 21 10:13:56 node1 kubelet[1082]: E0721 10:13:56.636837    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m47.109477766s ago; threshold is 3m0s
Jul 21 10:14:01 node1 kubelet[1082]: E0721 10:14:01.636996    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m52.109623866s ago; threshold is 3m0s
Jul 21 10:14:06 node1 kubelet[1082]: E0721 10:14:06.637138    1082 kubelet.go:1852] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m57.1097673s ago; threshold is 3m0s

**Comment by dcbw** [comment]
@imkos what network/CNI plugin are you using in this cluster?

**Comment by imkos** [comment]
@dcbw flannel, use  quay.io/coreos/flannel:v0.13.0

**Comment by caseydavenport** [comment]
I'm not sure I see any indication in those logs that the network plugin is to blame, but it could be.

I suspect this is a general node health problem with host network access. 

> Jul 19 18:02:42 node1 kubelet[2129392]: E0719 18:02:42.287195 2129392 conn.go:254] Error on socket receive: read tcp 127.0.0.1:14905->127.0.0.1:9946: use of closed network connection

@imkos what is running at 127.0.0.1:9946?
