### ISSUE TITLE
scheduler: panic in AppendReason, when status is nil (= success)

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#103737]
#### What happened:

AppendReason panic when status is nil. 
https://github.com/kubernetes/kubernetes/blob/818ed1afff306f8b310c56083e0c6be4fa93ce8a/pkg/scheduler/framework/interface.go#L185

Some plugins return nil to mean success. 

(Or, shouldn't Status.reason be used on success status? I use Status.reason field as a reason for why it is success.)

#### What you expected to happen:

not panic or describe this behaviour on the document

#### How to reproduce it (as minimally and precisely as possible):

https://play.golang.org/p/WWohPs5qYS5

#### Anything else we need to know?:

**Comment by sanposhiho** [comment]
/sig scheduling
/assign

I think there are some solutions we can take. 
1.  just add this behaviour to AppendReason document. (most easy solution)
2. initialize Status when status is nil like below.

```
func (s *Status) AppendReason(reason string) {
	if s == nil {
		s = NewStatus(Success)
	}
	s.reasons = append(s.reasons, reason)
}
```

3. make plugins not to return nil as Status

I support the second idea.

**Comment by Huang-Wei** [comment]
@sanposhiho I'd expect (and in fact it is) the caller to be responsible to ensure the status is not nil:

```
⇒  ag AppendReason pkg/scheduler -B3
pkg/scheduler/generic_scheduler.go
381-			if _, found := statuses[failedNodeName]; !found {
382-				statuses[failedNodeName] = framework.NewStatus(framework.Unschedulable, failedMsg)
383-			} else {
384:				statuses[failedNodeName].AppendReason(failedMsg)

pkg/scheduler/framework/plugins/volumebinding/volume_binding.go
176-		// not bound. Pod will be moved to active/backoff queues once these
177-		// claims are bound by PV controller.
178-		status := framework.NewStatus(framework.UnschedulableAndUnresolvable)
179:		status.AppendReason("pod has unbound immediate PersistentVolumeClaims")
--
239-	if len(reasons) > 0 {
240-		status := framework.NewStatus(framework.UnschedulableAndUnresolvable)
241-		for _, reason := range reasons {
242:			status.AppendReason(string(reason))

pkg/scheduler/framework/interface.go
181-	return s.reasons
182-}
183-
184:// AppendReason appends given reason to the Status.
185:func (s *Status) AppendReason(reason string) {
--
268-		}
269-
270-		for _, r := range s.reasons {
271:			finalStatus.AppendReason(r)
```

The 2nd option may work, but semantically `AppendReason` should be called by a non-success status.

**Comment by sanposhiho** [comment]
Hi @Huang-Wei 

> AppendReason should be called by a non-success status.

OK, I see :)

I created the small PR to describe that reason field is for non-success status. 
Please take a look 🙏
