### ISSUE TITLE
Expose BindPodsQps and BindPodsBurst as cmd line flags

### ISSUE THREAD

**Issue by HaiyangDING** [kubernetes/kubernetes#10377]
There is a TODO in the scheduler/factory stating that BindPodsQps and BindPodsBurst should be exposed as cmd line flags.

I would like to implement this, if no one is currently working on it.

**Comment by mbforbes** [comment]
@HaiyangDING can you please find authors who have touched the code recently (check out GitHub's history) and then @ mention them here directly? They'll be able to tell you whether we'll likely accept PRs for these fixes in the next couple weeks (we're pushing to 1.0 so are generally only accepting work on 1.0 features, tests, documentation, or bug fixes). Thank you--please ping if you need help!

**Comment by HaiyangDING** [comment]
@mbforbes , I will look up the history to see if I can find the author.

Besides, I am going to see if I can do anything for 1.0. Many thanks to your suggestion!

**Comment by HaiyangDING** [comment]
@bprashanth ,

Hi, I saw in the Git history that you have added limitation to pod burst qps and pod binding rate at https://github.com/GoogleCloudPlatform/kubernetes/commit/4004a68ae983fec2e24741e10833d6f9f78f741b. In the patch, it is mentioned that BindPodsQps and BindPodsBurst should be exposed to cmd line flags. If you do not mind, may I send a PR to implement this? I just want to make some contribution to Kubernetes and have total respect of the work you have done:)

Regards

**Comment by bprashanth** [comment]
@HaiyangDING out of curiosity, do you have a use case in mind? (Would you like to push the limit higher/lower?). I'm totally fine exposing it as a command line flag if you need it, note however that we're currently in a code freeze working toward our 1.0 release (https://groups.google.com/forum/#!topic/kubernetes-announce/1voyC1d-T_o), so we might not be able to merge your pr right away.

**Comment by HaiyangDING** [comment]
@bprashanth ,

Hi, I do not have a specific use case right away. I wanted to implement this simply because I saw a TODO when reading the code. Luckily enough, it happens that I have had some contribution to the scheduler cmd line(https://github.com/GoogleCloudPlatform/kubernetes/pull/6967), so I felt that I could make more contribution for the community:) That is all my motivation.

Besides, it is OK for me if the PR not be merged for some moment.

**Comment by kargakis** [comment]
@kubernetes/sig-node-feature-requests
