### ISSUE TITLE
StreamWatcher memory leak ?

### ISSUE THREAD

**Issue by evanlixin** [kubernetes/kubernetes#103789]
I am using client-go/tools/cache package NewInformer, find the StreamWatcher and seeing extremely high memory allocations. Attached is a memory profile:

[pprof.bcs-k8s-watch.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz](https://github.com/kubernetes/kubernetes/files/6845441/pprof.bcs-k8s-watch.alloc_objects.alloc_space.inuse_objects.inuse_space.003.pb.gz)

From this we have 2.3 GB of memory allocated by the StreamWatcher.

To get to this state I had a script to create pod and delete pod over and over again, and every 10 seconds I run it again. I left this running 30 minutes and saw this memory usage.

watch code as follows,  cache.NewInformer return controller and store。writer is chan queue, receiving event and distribute to queue。 

https://github.com/Tencent/bk-bcs/blob/master/bcs-k8s/bcs-k8s-watch/app/k8s/watcher.go

#91686

**Comment by evanlixin** [comment]
I am sorry,  paste the code snippet again
`
type Watcher struct {
resourceType string
resourceNamespaced bool
controller cache.Controller
store cache.Store
writer *output.Writer
stopChan chan struct{}
}

// NewWatcher creates a new watcher of target type resource.
func NewWatcher(client *rest.Interface, resourceType string, resourceName string, objType runtime.Object,
writer *output.Writer, sharedWatchers map[string]WatcherInterface, resourceNamespaced bool) *Watcher {

watcher := &Watcher{
	resourceType:       resourceType,
	writer:             writer,
	sharedWatchers:     sharedWatchers,
	resourceNamespaced: resourceNamespaced,
}

// build list watch.
listWatch := cache.NewListWatchFromClient(*client, resourceName, metav1.NamespaceAll, fields.Everything())

// register event handler.
eventHandler := cache.ResourceEventHandlerFuncs{
	AddFunc:    watcher.AddEvent,
	UpdateFunc: watcher.UpdateEvent,
	DeleteFunc: watcher.DeleteEvent,
}

// build informer.
store, controller := cache.NewInformer(listWatch, objType, defaultSyncInterval, eventHandler)
watcher.store = store
watcher.controller = controller

return watcher
}

// GetByKey returns object data by target key.
func (w *Watcher) GetByKey(key string) (interface{}, bool, error) {
return w.store.GetByKey(key)
}

// ListKeys returns all keys in local store.
func (w *Watcher) ListKeys() []string {
return w.store.ListKeys()
}

// Run starts the watcher.
func (w *Watcher) Run(stopCh <-chan struct{}) {
// run controller.
w.controller.Run(stopCh)
}

// AddEvent is event handler for add resource event.
func (w *Watcher) AddEvent(obj interface{}) {
data := w.genSyncData(obj, action.SyncDataActionAdd)
if data == nil {
return
}
w.writer.Sync(data)
}

// DeleteEvent is event handler for delete resource event.
func (w *Watcher) DeleteEvent(obj interface{}) {
data := w.genSyncData(obj, action.SyncDataActionDelete)
if data == nil {
return
}
w.writer.Sync(data)
}

// UpdateEvent is event handler for update resource event.
func (w *Watcher) UpdateEvent(oldObj, newObj interface{}) {
// compare the object changes for update.
if reflect.DeepEqual(oldObj, newObj) {
newObjMetadata := newObj.(metav1.Object)

	// there is no changes, no need to update.
	glog.V(2).Infof("watcher got the same ResourceType[%s]: %s/%s",
		w.resourceType, newObjMetadata.GetNamespace(), newObjMetadata.GetName())
	return
}

// it's need to update finally, sync metadata now.
data := w.genSyncData(newObj, action.SyncDataActionUpdate)
if data == nil {
	return
}
w.writer.Sync(data)
}
`

**Comment by evanlixin** [comment]
@liggitt @howardjohn  Thanks  for taking a look

**Comment by evanlixin** [comment]
i find that infomer handler be stuck will lead to streamWatcher memory high allocations。don't  hang informer handler and you will resolve that question. @fedebongio

**Comment by aojea** [comment]
can you check with a cpu profile if some handler is blocking?
https://github.com/kubernetes/kubernetes/issues/91686#issuecomment-652167754

**Comment by evanlixin** [comment]
cpu  profile is normal。as follows，code  [https://github.com/Tencent/bk-bcs/blob/master/bcs-k8s/bcs-k8s-watch/app/k8s/watcher.go](url)，callback  handler 

func (w *Watcher) AddEvent(obj interface{}) {
	data := w.genSyncData(obj, action.SyncDataActionAdd)
	if data == nil {
		return
	}
	w.writer.Sync(data)
}

writer is a buffer chan with 102400 length and  write chan timeout for one second。probably is will be stuck when produce lots of events。finally，I store events to fifo queue when  it produce lots of events，and  consume fifo queue event to writer chan。the issue is solved。

**Comment by aojea** [comment]
So, the problem is that your handlers are slower processing the objects from the delta fifo queue, than the rate at which the events are obtained from the apiserver,  this is because of this

https://github.com/kubernetes/kubernetes/blob/a8035dbc3b1a523932f8e2384b5f49ace4194870/staging/src/k8s.io/client-go/tools/cache/delta_fifo.go#L504-L513

objects are processed by the handlers locking the deltaFifo queue, hence the streamwatcher accumulates the object in memory until the handlers process the object and Pop() release the lock.

The code comments inform about this problem
> // process should avoid expensive I/O operation so that other queue operations, i.e.
// Add() and Get(), won't be blocked for too long.

@wojtek-t @deads2k the only solution I see is logging some errors warning about this (processing withouth locking doesn't seem an option, right?)
I've tried to use queue depth, but that is not an option, since the contention happens before events get into the queue and it nevers goes high.
I've tried adding trace for slow handlers operations, however, those maybe harmless if the incoming rate is still lower than the draining rate, unless we decide that we want to trace process handlers that take more than X seconds

**Comment by deads2k** [comment]
> @wojtek-t @deads2k the only solution I see is logging some errors warning about this (processing withouth locking doesn't seem an option, right?)

Yeah.  I don't see it as a high priority, but that could be helpful.  Following the standard hander to workqueue pattern, it isn't a practical problem.

/priority backlog

**Comment by evanlixin** [comment]
thanks @aojea and @deads2k for yours help. I think the question has been resolved and will close the issue

**Comment by evanlixin** [comment]
@aojea @deads2k  i don't hang informer hander by fifo queue,  i find that  memory will come down when lots of create and delete pods。but i running code online，the streamwatcher still exist high memory usage 。 as follows pprof
[0801heap.pdf](https://github.com/kubernetes/kubernetes/files/6912102/0801heap.pdf)，Please take a look at it。

**Comment by kuldeepsolanki04** [comment]
@evanlixin i am also facing same issue any guidance for the watcher memory increase in high pod churn
