### ISSUE TITLE
How can I remove ImageLocalityPriority?

### ISSUE THREAD

**Issue by hyserver** [kubernetes/kubernetes#103766]
#### What happened:
The ImageLocalityPriority parameter causes uneven use of cluster resources. 

Can we remove it?

#### Environment:
- Kubernetes version: 1.21.1
- OS: NAME="CentOS Linux", VERSION="7 (Core)"
- Kernel: 4.4.248-1.el7.elrepo.x86_64
- Network plugin and version : macvlan 0.9.1

**Comment by neolit123** [comment]
please use the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
