### ISSUE TITLE
Create k8s pod and always wrong

### ISSUE THREAD

**Issue by Gzylzy** [kubernetes/kubernetes#103770]
My project is a SpringBoot jar, and when i want to create a pod , it talks to me "io.kubernetes Unknown apiVersionKind v1/Pod is it registered?" then i debug it and found some question, 
--- Set<ClassInfo> allClasses = cp.getTopLevelClasses("io.kubernetes.client.openapi.models");
This code in ModelMapper.class to read the package, when it works in jar ,It always found nothing ,that cause my pod don't create.
so how can i due it.

**Comment by neolit123** [comment]
please try the support forums first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
