### ISSUE TITLE
Add test case in pkg/cm/cpuset to verify no elements are added after result is called

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#103764]
This is caught by static check PR
https://github.com/kubernetes/kubernetes/pull/103723/files/7e980a3330b648bcc8952356b16fc7500a8c530f#r670801768

Test case needs to be added for the following code path

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpuset/cpuset.go#L49-#L52

A simple verification of adding element `b.Add()` after result `b.Result()`  is called needs to be added [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpuset/cpuset_test.go#L38
) 
The test should fail until  PR #103723 is merged.

**Comment by adisky** [comment]
oh!! there is already a PR https://github.com/kubernetes/kubernetes/pull/103415 Adding the test

**Comment by Sadiquedeveloper** [comment]
@KuberDriver  are you still activately working on this.

**Comment by KuberDriver** [comment]
> oh!! there is already a PR https://github.com/kubernetes/kubernetes/pull/103415 Adding the test
> 

@Sadiquedeveloper actually no due to this PR☝️

**Comment by alimoosavi** [comment]
I am new to kubernetes project and this issue seems attractive to me , please assign this issue to me.

**Comment by adisky** [comment]
closing the issue fixed by https://github.com/kubernetes/kubernetes/pull/103415
/close
