### ISSUE TITLE
Integrate conversion tool into kubectl

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#10382]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cluster_management.md#switching-your-config-files-to-a-new-api-version

See also #7576, #4471

**Comment by hurf** [comment]
Following the discussion in #7576, I'm planning to add a verb `convert` to kubectl, with `i,o,r,v` flags. Is this the right way to fix this issue?

**Comment by hurf** [comment]
Related doc has been moved to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/cluster-management.md#switching-your-config-files-to-a-new-api-version
