### ISSUE TITLE
v1.22.0 (beta, rc) broke --audit-log-path=- support

### ISSUE THREAD

**Issue by AlekSi** [kubernetes/kubernetes#103845]
#### What happened:

I run an API server with `--audit-log-path=-` as documented and supported. I tried to update to v1.22.0-beta.2. It failed.

I tracked down the issue to #95387. That PR tries to create a file with the name "-" in the current directory. If that directory is not writable, the API server exits with an error.

#### What you expected to happen:

Everything should work as before. Specifically, the API server should not try to create a file named "-" if stdout logging is requested.

#### How to reproduce it (as minimally and precisely as possible):

Run an API server with `--audit-log-path=-`. Observe either server exit or file "-" being created.

#### Anything else we need to know?:

Will send PR shortly.

#### Environment:
- Kubernetes version (use `kubectl version`):

v1.22.0-beta.2

- OS (e.g: `cat /etc/os-release`):

https://github.com/talos-systems/talos

**Comment by neolit123** [comment]
the PR has an ACTION REQUIRED:
https://github.com/kubernetes/kubernetes/pull/95387

are you seeing a problem with file permissions or something else?

/sig api-machinery auth
/triage needs-information

**Comment by AlekSi** [comment]
> are you seeing a problem with file permissions or something else?

Sorry, I forgot to mention the most important part. :) Updated description.

https://github.com/AlekSi/kubernetes/commit/c854cd2412498a76d5cc13f5ac37a88561c86ee5 will be submitted shortly.

**Comment by AlekSi** [comment]
See #103875

**Comment by AlekSi** [comment]
Both #103878 and #103875 are merged, closing.
