### ISSUE TITLE
Kubernetes memory stats don't support virtio balloon

### ISSUE THREAD

**Issue by DanWard** [kubernetes/kubernetes#103887]
#### What happened:
On reboot of my kubernetes host VMs, the memory reported at the time of start was as below:
```
$ kubectl top node
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
kube01   273m         5%     1888Mi          110%
kube02   279m         5%     2208Mi          182%
kube03   349m         6%     2344Mi          194%
```

This stopped scheduling from occurring when the memory was reported as overcommitted. 
Setting a static 4GB minimum, 6GB maximum then restarting k3s (`service k3s restart`) on each node then reported the memory percentage as correct, but still did not yield the correct overall memory assigned to the host.
```
~/kubectl top nodes
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
kube01   249m         4%     1854Mi          45%
kube02   303m         6%     2186Mi          49%
kube03   1426m        28%    3474Mi          87%
```

I've left it running for a while, and it has stabilised around here:
```
~/kubectl top nodes
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
kube01   242m         4%     2339Mi          57%
kube02   288m         5%     2555Mi          58%
kube03   354m         7%     4078Mi          102%
```
The hosts are aware of their memory limits, but kubernetes seems to only look at the allocation at the time of service start.
```
core@kube01:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:          5.8Gi       1.8Gi       1.4Gi       7.0Mi       2.5Gi       3.8Gi
Swap:            0B          0B          0B
```
#### What you expected to happen:
I expected kubernetes to report and allow usage on all of the memory available to the host, allowing the kernel balloon device to manage the memory allocations from KVM.

#### How to reproduce it (as minimally and precisely as possible):
1. Use Proxmox, or KVM hypervisor with virtio balloon enabled.
2. Set this memory count to low for the VM to start, and high for the pods to use. I.e. 512Mi minimum, 6Gi maximum.
3. Start the VM.
4. Let kube servcies start, check the `top` stats and `free` stats from the host.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2+k3s1", GitCommit:"5a67e8dc473f8945e8e181f6f0b0dbbc387f6fca", GitTreeState:"clean", BuildDate:"2021-06-21T20:52:44Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Proxmox bare-metal host, Ubuntu 20.04 VMs.
- OS (e.g: `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
`Linux kube01 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
K3S. Ubuntu 20.04 ISO.
- Network plugin and version (if this is a network-related bug):
Calico, 3.19
- Others:

**Comment by brancz** [comment]
This is Kubernetes, not k3s, even though there might be similarities we have no idea about k3s. Please report this over at k3s.

**Comment by ehashman** [comment]
Given that we haven't heard anything in a couple months, I will close this issue. Feel free to reopen when you are able to provide further info to assist with debugging.

/close
