### ISSUE TITLE
Logs from inside apiserver handler.ServeHTTP disappear into ether

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#10385]
Hit a brick wall trying to debug a separate issue because the apiserver is not recording logs past the request authenticator http.Handler. Specifically, calls to `glog.Infof()`, `httplog.LogOf(w).Addf()`, and even `fmt.Printf` do not make it into `kube-apiserver.log`. So, e.g. `pkg/apiserver/proxy.go` generates no logs regardless of log level.

The event horizon is in [NewRequestAuthenticator](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/auth/handlers/handlers.go#L33). Callers up the stack from there can call `httplog.LogOf(w, req).Addf` or `glog.Infof` and the output appears in `kube-apiserver.log`. Log lines in functions further down the call stack are never output.

If anyone has ideas, I'd be grateful for help. Even a repro would at least be sanity affirming.

cc @lavalamp, @nikhiljindal,

**Comment by lavalamp** [comment]
I was able to repro this yesterday, btw. You're not crazy. Perhaps search back through our jenkins apiserver logs to see when it broke?

**Comment by jlowdermilk** [comment]
Late updating. I did eventually work around the blindspot. It seems the reason I couldn't get logs from `pkg/apiserver/proxy.go` to show up is that the actual call to the proxy handler is made thru [UpgradeAwareProxyHandler](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/registry/generic/rest/proxy.go#L40). Still not sure why that causes logs to blackhole but not worth digging into further right now.

**Comment by smarterclayton** [comment]
I think this was fixed recently in better refactors of the code.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (176/150 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o10.sgmail.github.com ([167.89.101.201]:42092)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU8G-000QRU-Sm
	for dev@imwiz.com; Thu, 01 Jun 2017 11:43:37 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=rkBGe2Pwn2Fa3FrL3UZmuHKCo4k=; b=RYWJgpqicueDKWUu
	UnzfPwuFky3SAAYAdzBpEtDNkjb8JqSPyUn7ir9gz8gt81kxMdYL8MjRtTGvKn36
	xf8LS4vGi1iTG8Vosba9Pl3TT1OIfsvMpP9DZTFvgH9AnKLWOqNXA1eCrAyXI16h
	hEdcJz3YU2hzt9N5MCjlLgiiQBA=
Received: by filter0841p1mdw1.sendgrid.net with SMTP id filter0841p1mdw1-19546-59305237-68
        2017-06-01 17:43:19.914948161 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id Ir-U0w47QUmp6yyrjKMlyA
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:43:19.868 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:43:19 -0700
