### ISSUE TITLE
UDP Pod behind a LoadBalancer Service (External IP) replacing another Pod in the same node not receiving traffic

### ISSUE THREAD

**Issue by dkulchinsky** [kubernetes/kubernetes#103857]
#### What happened:

UDP traffic to a Pod behind a LoadBalancer Service exposing a UDP listener service is blackholed when the replacement Pod is scheduled on the same node as the "old" Pod.

#### What you expected to happen:

A new Pod that gets provisioned (replacing the previous one) will receive traffic once it's ready.

#### How to reproduce it (as minimally and precisely as possible):

1. Run a UDP Listener Pod (single pod) and using nodeSelector ensure it runs on a specific node
2. Expose the Pod behind a LoadBalancer Service
3. Send continuous stream of UDP packets from outside the cluster to the External IP of the Service
4. Observe that traffic is correctly received
5. Delete the Pod and observe as a new one is created, traffic should now be blackholed and not reaching the "new" Pod

#### Anything else we need to know?:

After the new Pod is recreated, we noticed the following `conntrack` entries on the node:
```
udp 17 29 src=<SRC IP A> dst=<SVC EXT IP> sport=51287 dport=6343 packets=111046 bytes=144979158 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP A> sport=6343 dport=51287 packets=0 bytes=0 mark=0 use=1
udp 17 29 src=<src ip B> dst=<SVC EXT IP> sport=53156 dport=6343 packets=132186 bytes=174564682 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP B> sport=6343 dport=53156 packets=0 bytes=0 mark=0 use=1
udp 17 29 src=<src ip C> dst=<SVC EXT IP> sport=54882 dport=6343 packets=97917 bytes=129246821 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP C> sport=6343 dport=54882 packets=0 bytes=0 mark=0 use=2
udp 17 29 src=<src ip D> dst=<SVC EXT IP> sport=50427 dport=6343 packets=220813 bytes=290159533 [UNREPLIED] src=<SVC EXT IP> dst=<SRC IP D> sport=6343 dport=50427 packets=0 bytes=0 mark=0 use=1
```

notice that the <SVC EXT IP> appears here both in the original `dst` and the NATed `src`, this is wrong and I suspect happens because the conntrack for the old Pod were flushed before the iptables rules for the new Pod were created (?) and in the interim new packets have reached the node and resulted in these incorrect conntrack entries.

To "fix" this, we manually deleted the above conntrack entries, and this allowed new correct one to be established based on the now existing iptables nat rule:

```
 udp 17 29 src=<SRC IP A> dst=<SVC EXT IP> sport=51287 dport=6343 packets=7716 bytes=10071760 [UNREPLIED] src=172.30.3.219 dst=<SRC IP A> sport=6343 dport=51287 packets=0 bytes=0 mark=0 use=2
 udp 17 29 src=<SRC IP B> dst=<SVC EXT IP> sport=53156 dport=6343 packets=8100 bytes=10710888 [UNREPLIED] src=172.30.3.219 dst=<SRC IP B> sport=6343 dport=53156 packets=0 bytes=0 mark=0 use=1
 udp 17 29 src=<SRC IP C> dst=<SVC EXT IP> sport=54882 dport=6343 packets=5129 bytes=6759873 [UNREPLIED] src=172.30.3.219 dst=<SRC IP C> sport=6343 dport=54882 packets=0 bytes=0 mark=0 use=1
 udp 17 29 src=<SRC IP D> dst=<SVC EXT IP> sport=50427 dport=6343 packets=9988 bytes=13124292 [UNREPLIED] src=172.30.3.219 dst=<SRC IP D> sport=6343 dport=50427 packets=0 bytes=0 mark=0 use=2
```

with this new conntrack entries, the traffic started flowing as expected to the new Pod and notice that the NATed `src` now correctly shows the Pod IP (172.30.3.219) instead of the Service External IP.

While spelunking through the GitHub issues and PRs, I found this issue https://github.com/kubernetes/kubernetes/issues/91236 which was addressed in https://github.com/kubernetes/kubernetes/pull/98305, it does mention that:
> The conntrack entries have to be cleared after the iptables rules are programmed and when
the service has endpoints available.

Since the fix in this PR refers to NodePort, perhaps the same also applies to External IP (i.e. LoadBalancer Service?) or there's something else at play here? AFAICT, this fix is included in v1.20.7 that we are running.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-gke.1800", GitCommit:"cd6f9121893d6cdb30e3c48d57830ed44411e4ba", GitTreeState:"clean", BuildDate:"2021-06-07T09:17:22Z", GoVersion:"go1.15.12b5", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: GCP/GKE
- OS (e.g: `cat /etc/os-release`):
```
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=c19d150c6bd658510ec786390aec80ad476c7578
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
VERSION=89
VERSION_ID=89
BUILD_ID=16108.403.15
```
- Kernel (e.g. `uname -a`): `Linux gke-stg-usc1-workloads-b5d2c472-xbzb 5.4.104+ #1 SMP Tue Apr 6 09:49:56 PDT 2021 x86_64 Intel(R) Xeon(R) CPU GenuineIntel GNU/Linux`
- Install tools: Terraform (with google provider)
- Network plugin and version (if this is a network-related bug): `Calico v3.16.10-gke.0`
- Others:

**Comment by dkulchinsky** [comment]
According to GCP support (since we hit this on a GKE cluster) there's already a fix for this bug and it in v1.21, however I'm unable to find to link it here (hope they can provide the link shortly).

**Comment by dkulchinsky** [comment]
GCP support referenced https://github.com/kubernetes/kubernetes/pull/98305 as the fix for this issue, however this was already merged and released in v1.20.4 but we are running v1.20.7, so should have the fix already, so the status is unclear at this point.

**Comment by aojea** [comment]
thanks for the detailed report, 

at first sight we do clean the external ips
https://github.com/kubernetes/kubernetes/blob/fffaadc01331cca57cafa0fc066a2a3eec23acb8/pkg/proxy/iptables/proxier.go#L829-L832
is it possible to set kube-proxy in a log level of 2 and capture the logs from the node to correlate with the time it happends, and understand why those entries are not being deleted?

**Comment by dkulchinsky** [comment]
Hey @aojea, we can try that, however since this is a GKE environment I'd have to check how/if we can change kube-proxy log level.

My understanding of the issue is that it's not that the conntrack entries are flushed, is that they are flushed **_before_** the nat iptables rules are created, causing faulty conntrack entries to be created in the interim (since the udp packets are incoming all the time).

**Comment by dkulchinsky** [comment]
@aojea, I'm having some miscommunication about the availability of fix in https://github.com/kubernetes/kubernetes/pull/98305 with GCP/GKE support 😞 and was hoping you could confirm that https://github.com/kubernetes/kubernetes/pull/98305 is included in v1.20.5 (as per the release notes there? https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md#changelog-since-v1204)

GCP Support claim that this change is incorporated in v1.21 and we should wait for v1.21 to be available in GKE.

**Comment by aojea** [comment]
> @aojea, I'm having some miscommunication about the availability of fix in #98305 with GCP/GKE support  and was hoping you could confirm that #98305 is included in v1.20.5 (as per the release notes there?

I see the commit in 1.20.5 , this is the cherry-pick https://github.com/kubernetes/kubernetes/pull/99017/
```
git describe --contains d059a916c37f9b265967c5503810cc5306644c9e
v1.20.5~20^2
```

> My understanding of the issue is that it's not that the conntrack entries are flushed, is that they are flushed before the nat iptables rules are created, causing faulty conntrack entries to be created in the interim (since the udp packets are incoming all the time).

The conntrack entries are always deleted after the conntrack entries are created, there is some code that detects that a service goes stale and based on that it deletes the entries. 
I think that current code detects this case, at least I know it works when the service goes from 0 to 1 endpoint, that is why the logs will be useful, we can see exactly what happens ...

**Comment by dkulchinsky** [comment]
Thanks for confirming @aojea!

I just checked and `kube-proxy` seem to be already running in log level 2:
```
         - kube-proxy --cluster-cidr=172.22.0.0/16 --oom-score-adj=-998 --v=2 --feature-gates=DynamicKubeletConfig=false,EfficientWatchResumption=true
           --iptables-sync-period=1m --iptables-min-sync-period=10s --ipvs-sync-period=1m
           --ipvs-min-sync-period=10s --detect-local-mode=NodeCIDR 1>>/var/log/kube-proxy.log
           2>&1
```

I looked back at the logs when this issue was identified and I see the following entries:

```
message: Stale udp service NodePort <namespace>/<service>:sflow -> 32741
message: Stale udp service <namespace>/<service>:sflow -> 172.31.14.114
```

This two messages and only these two repeat every time we tried to rollout the deployment.

`32741` is indeed the `nodePort` and `172.31.14.114` is the ClusterIP of the service:
```
❯ k describe svc <service>
Name:                        <service>
Namespace:                   <namespace>
Type:                        LoadBalancer
IP Families:                 <none>
IP:                          172.31.14.114
IPs:                         172.31.14.114
LoadBalancer Ingress:        <External IP>
Port:                        sflow  6343/UDP
TargetPort:                  6343/UDP
NodePort:                    sflow  32741/UDP
Endpoints:                   172.30.3.220:6343
Session Affinity:            None
External Traffic Policy:     Local
HealthCheck NodePort:        30304
LoadBalancer Source Ranges:  <Some CIDRs here>
Events:                      <none>
```

**Comment by aojea** [comment]
oh wait, by external IP you mean `LoadBalancer Ingress:        <External IP>`?

**Comment by aojea** [comment]
here you go, 
https://github.com/kubernetes/kubernetes/pull/104009

having good reports on bugs make them easy to spot ;)

**Comment by dkulchinsky** [comment]
@aojea indeed! I apologize if I wasn't clear 😓 indeed I was referring to the LoadBalancer Service External IP.

Thanks for fix!!! 🥳 

But now I'm a bit confused, since I understood that LoadBalancer Service External IP == LoadBalancer Ingress IP, but I see these are two separate attributes?

so for example:
```
❯ k get svc -n platform ext-ic-ingress-nginx-controller
NAME                              TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)                      AGE
ext-ic-ingress-nginx-controller   LoadBalancer   172.27.13.98   <External IP>   80:30218/TCP,443:30731/TCP   222d
```

```
❯ k describe -n platform svc ext-ic-ingress-nginx-controller
Name:                     ext-ic-ingress-nginx-controller
Namespace:                platform
Type:                     LoadBalancer
IP Families:              <none>
IP:                       172.27.13.98
IPs:                      172.27.13.98
LoadBalancer Ingress:     <External IP>
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30218/TCP
Endpoints:                172.26.3.73:80,172.26.9.52:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  30731/TCP
Endpoints:                172.26.3.73:443,172.26.9.52:443
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     31766
Events:                   <none>
```

These `<External IP>` are the same IP, but internally they are separate attributes?

**Comment by aojea** [comment]
hmm I don't know how kubectl prints the information, but you can check the fields with 
`kubectl get service -o yaml` and you could see that ExternalIPs and LoadBalancer.IngressIP are different fields, actually one is in the Status and other in the Spec

**Comment by dkulchinsky** [comment]
> hmm I don't know how kubectl prints the information, but you can check the fields with
> `kubectl get service -o yaml` and you could see that ExternalIPs and LoadBalancer.IngressIP are different fields, actually one is in the Status and other in the Spec

interesting, so in the `-o yaml` output, I can only see the `status.loadBalancer.ingress.ip`, there's actually no mention of `External IP` here:
```
❯ kubectl get -n platform svc ext-ic-ingress-nginx-controller -o yaml
apiVersion: v1
kind: Service
metadata:
  name: ext-ic-ingress-nginx-controller
  namespace: platform
spec:
  clusterIP: 172.27.13.98
  clusterIPs:
  - 172.27.13.98
  externalTrafficPolicy: Local
  healthCheckNodePort: 31766
  ports:
  - name: http
    nodePort: 30218
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30731
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ext-ic
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: <Public/External IP>
```

That's why I always assumed that this is referring to the same thing/attribute.
