### ISSUE TITLE
New kubelet-serial failures, test timeouts

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103879]
Began late on 07/20: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

Many tests labeled [Disruptive][Feature:DynamicKubeletConfig] are now failing due to timeouts.

Example run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1417796402028744704

/kind failing-test
/sig node

**Comment by ehashman** [comment]
Most likely possibility here is https://github.com/kubernetes/kubernetes/pull/103785... @smarterclayton can you PTAL?

**Comment by ehashman** [comment]
Ah you know what, they are all DynamicKubeletConfig tests that are newly timing out/failing, strange. Was there a test-infra change...?

/cc @SergeyKanzhelev

**Comment by ehashman** [comment]
Same error basically on all failures:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/dynamic_kubelet_config_test.go:82
Timed out after 60.001s.
Expected
    <*errors.errorString | 0xc000fa3770>: {
        s: "checkConfigMetrics: case: reset via nil config source: expect metrics (metrics.KubeletMetrics)map[kubelet_node_config_assigned:[<*>kubelet_node_config_assigned{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_active:[<*>kubelet_node_config_active{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_last_known_good:[<*>kubelet_node_config_last_known_good{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]] but got (metrics.KubeletMetrics)map[]",
    }
to be nil
```

**Comment by ehashman** [comment]
Was able to repro the node e2e failures locally, will try against https://github.com/kubernetes/kubernetes/pull/103880

**Comment by ehashman** [comment]
Still seeing failures with the revert applied, will git bisect.

**Comment by ehashman** [comment]
```
ehashman@fedora:~/src/k8s$ git bisect good d7ee024cc5d0bf09bb8b78941f5d4c6e3c56c676
9f47110aa29094ed2878cf1d85874cb59214664a is the first bad commit
commit 9f47110aa29094ed2878cf1d85874cb59214664a
Merge: 7303b2ce4e0 d7ee024cc5d
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Tue Jul 20 15:21:26 2021 -0700

    Merge pull request #103785 from smarterclayton/preserve_reason
    
    Ensure that Reason and Message are preserved on pod status

 pkg/kubelet/kubelet_pods.go      |  77 ++++++----
 pkg/kubelet/kubelet_pods_test.go | 321 ++++++++++++++++++++++++++++++++++++++-
 2 files changed, 365 insertions(+), 33 deletions(-)
```

/assign @smarterclayton 


The weird thing is that the revert doesn't make the failures go away, but it looks like this was occasionally flaking previously, so maybe I'm just getting unlucky: https://storage.googleapis.com/k8s-gubernator/triage/index.html?text=checkConfigMetrics%3A%20case%3A%20reset%20via%20nil%20config%20source%3A%20expect%20metrics

**Comment by ehashman** [comment]
I've definitely confirmed that

- https://github.com/kubernetes/kubernetes/pull/103785 is where the failures started
- reverting the PR doesn't fix the failures :grimacing: 

Really stumped as to why.

**Comment by pacoxu** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1417796402028744704/artifacts/n1-standard-2-cos-81-12871-1290-12-2b3adefc-system.log
```
Jul 21 10:42:48 localhost df[297]: Filesystem      Size  Used Avail Use% Mounted on
Jul 21 10:42:48 localhost df[297]: /dev/root       2.0G  955M 1005M  49% /
Jul 21 10:42:48 localhost df[297]: devtmpfs        3.7G     0  3.7G   0% /dev
Jul 21 10:42:48 localhost df[297]: tmpfs           3.7G     0  3.7G   0% /dev/shm
Jul 21 10:42:48 localhost df[297]: tmpfs           3.7G  288K  3.7G   1% /run
Jul 21 10:42:48 localhost df[297]: tmpfs           3.7G     0  3.7G   0% /sys/fs/cgroup
Jul 21 10:42:48 localhost df[297]: tmpfs           3.7G   36K  3.7G   1% /etc/machine-id
Jul 21 10:42:48 localhost df[297]: tmpfs           256K     0  256K   0% /mnt/disks
Jul 21 10:42:48 localhost df[297]: tmpfs           3.7G     0  3.7G   0% /tmp
Jul 21 10:42:48 localhost df[297]: overlayfs       3.7G   36K  3.7G   1% /etc
Jul 21 10:42:48 localhost df[297]: /dev/sda8        12M   28K   12M   1% /usr/share/oem
Jul 21 10:42:48 localhost df[297]: /dev/sda1        16G   81M   16G   1% /mnt/stateful_partition
Jul 21 10:42:48 localhost df[297]: tmpfs           1.0M     0  1.0M   0% /var/lib/cloud

...

Jul 21 11:43:26 n1-standard-2-cos-81-12871-1290-12-2b3adefc google-accounts[362]: ERROR Exception calling the response handler. [Errno 28] No space left on device.
                                                                                  Traceback (most recent call last):
                                                                                    File "/usr/lib64/python2.7/site-packages/google_compute_engine/metadata_watcher.py", line 200, in WatchMetadata
                                                                                      handler(response)
                                                                                    File "/usr/lib64/python2.7/site-packages/google_compute_engine/accounts/accounts_daemon.py", line 285, in HandleAccounts
                                                                                      self.utils.SetConfiguredUsers(desired_users.keys())
                                                                                    File "/usr/lib64/python2.7/site-packages/google_compute_engine/accounts/accounts_utils.py", line 363, in SetConfiguredUsers
                                                                                      shutil.copy(updated_users_file, self.google_users_file)
                                                                                    File "/usr/lib64/python2.7/shutil.py", line 133, in copy
                                                                                      copyfile(src, dst)
                                                                                    File "/usr/lib64/python2.7/shutil.py", line 98, in copyfile
                                                                                      copyfileobj(fsrc, fdst)
                                                                                  IOError: [Errno 28] No space left on device

```

**Comment by ehashman** [comment]
That smells like an inode leak, we'd need the output of `df -i`

**Comment by ehashman** [comment]
Debugging in https://github.com/kubernetes/kubernetes/pull/103921

**Comment by ehashman** [comment]
Looking through the logs I notice the out of disk space errors almost always follow

```
Jul 26 19:06:11 n1-standard-2-cos-81-12871-1290-12-80df8ac6 kubelet[42102]: I0726 19:06:11.799533   42102 kubelet.go:2149] "SyncLoop (housekeeping) end"
```

This corresponds to this snippet of code:

https://github.com/kubernetes/kubernetes/blob/ee5df7cbcfffaddece66944a528fccb07430d29a/pkg/kubelet/kubelet.go#L2141-L2149

So I thought I'd look at HandlePodCleanups and the first thing I noticed is that every time this runs, it appears we're creating a new pod container manager:

https://github.com/kubernetes/kubernetes/blob/ee5df7cbcfffaddece66944a528fccb07430d29a/pkg/kubelet/kubelet_pods.go#L1016-L1026

However, we're already doing that in the outer syncLoop:

https://github.com/kubernetes/kubernetes/blob/ee5df7cbcfffaddece66944a528fccb07430d29a/pkg/kubelet/kubelet.go#L1626-L1628

That seems duplicated but git blame suggests that this isn't a new change, so I'll continue to dig into the recent `HandlePodCleanups` changes.

**Comment by ehashman** [comment]
Note that at each kubelet start, we're seeing okay utilization of both inodes and disk space, so something inside the kubelet is spiking and then cleaning itself up I guess:

```
Jul 26 19:07:02 n1-standard-2-cos-81-12871-1290-12-80df8ac6 kubelet[47850]: I0726 19:07:02.219671 47850 server.go:446] "Disk info" space="Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root        2006736   977876   1028860  49% /
devtmpfs         3823296        0   3823296   0% /dev
tmpfs            3827028        0   3827028   0% /dev/shm
tmpfs            3827028      436   3826592   1% /run
tmpfs            3827028        0   3827028   0% /sys/fs/cgroup
tmpfs            3827028       72   3826956   1% /etc/machine-id
tmpfs                256        0       256   0% /mnt/disks
tmpfs            3827028   581836   3245192  16% /tmp
overlayfs        3827028       72   3826956   1% /etc
/dev/sda8          11760       28     11408   1% /usr/share/oem
/dev/sda1       16293736 16277344         8 100% /mnt/stateful_partition
tmpfs               1024      120       904  12% /var/lib/cloud
overlay         16293736 16277344         8 100% /var/lib/docker/overlay2/29018d7bc778ff1cb113c3eb8bfac0a060b0a9b94e6b3eda00c42419d1d62c74/merged
shm                65536        0     65536   0% /var/lib/docker/containers/80a6db28cc849d733bedd48587a5119bfd967cd2a255a863ab01a234e7250a3d/mounts/shm
overlay         16293736 16277344         8 100% /var/lib/docker/overlay2/070c72b267f25e0d42c7f7891acdd21547a33637229db95d6b96d0d534149d9b/merged"
 inodes="Filesystem      Inodes  IUsed  IFree IUse% Mounted on
/dev/root       127488  21884 105604   18% /
devtmpfs        955824    220 955604    1% /dev
tmpfs           956757      1 956756    1% /dev/shm
tmpfs           956757    513 956244    1% /run
tmpfs           956757     18 956739    1% /sys/fs/cgroup
tmpfs           956757     30 956727    1% /etc/machine-id
tmpfs           956757      1 956756    1% /mnt/disks
tmpfs           956757    134 956623    1% /tmp
overlayfs       956757     30 956727    1% /etc
/dev/sda8         4096     11   4085    1% /usr/share/oem
/dev/sda1      1036320 125943 910377   13% /mnt/stateful_partition
tmpfs           956757     45 956712    1% /var/lib/cloud
overlay        1036320 125943 910377   13% /var/lib/docker/overlay2/29018d7bc778ff1cb113c3eb8bfac0a060b0a9b94e6b3eda00c42419d1d62c74/merged
shm             956757      1 956756    1% /var/lib/docker/containers/80a6db28cc849d733bedd48587a5119bfd967cd2a255a863ab01a234e7250a3d/mounts/shm
overlay        1036320 125943 910377   13% /var/lib/docker/overlay2/070c72b267f25e0d42c7f7891acdd21547a33637229db95d6b96d0d534149d9b/merged"
```

from https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103921/pull-kubernetes-node-kubelet-serial/1419717156169322496/artifacts/n1-standard-2-cos-81-12871-1290-12-80df8ac6-system.log

**Comment by ehashman** [comment]
Ah wait! I see it!

```
/dev/sda1       16293736 16277344         8 100% /mnt/stateful_partition
```

That started out with 81M used. What's filling it up? :eyes:

**Comment by ehashman** [comment]
https://github.com/kubernetes/kubernetes/blob/9b84e473b28f0e63fd27df420791e2089fc09b30/cluster/gce/gci/configure-helper.sh#L483-L496

This is where it's configured.

Great catch @rphillips who noticed that this started around a test that set up the static pod `kube-system/static-disk-hog`. It seems it's failing.

We see that once this test fails, the disk is full and so everything else fails: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103880/pull-kubernetes-node-kubelet-serial/1418634958255165440/#1:build-log.txt%3A45508

Is this possibly a manifestation of #103651 ? Or something else storage-related?

**Comment by smarterclayton** [comment]
Seems likely it is related to 103651, at least on the surface.

**Comment by dims** [comment]
@smarterclayton https://github.com/kubernetes/kubernetes/issues/103651 has a fix https://github.com/kubernetes/kubernetes/pull/103937, i ran `pull-kubernetes-node-kubelet-serial` on the 103937 PR and still seeing issues mentioned here ( looking at https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103937/pull-kubernetes-node-kubelet-serial/1419989415182209024/ )

**Comment by dims** [comment]
@smarterclayton @ehashman we need to revert https://github.com/kubernetes/kubernetes/pull/103668 see the WIP PR https://github.com/kubernetes/kubernetes/pull/103950 and the CI job output in https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103921/pull-kubernetes-node-kubelet-serial/1419717156169322496/build-log.txt

How did i find it? I looked at the PRs from Clayton and checked if i was seeing any of the new log messages and saw this in the failed jobs: which pointed to https://github.com/kubernetes/kubernetes/pull/103668 where the log message was added.
```
[dims@dims-a02 10:45] ~/Downloads ⟩ rg "Pod is waiting for termination"
1418634958255165440/artifacts/n1-standard-2-cos-89-16108-470-1-13ed3d62-system.log
90141:Jul 23 18:50:35 n1-standard-2-cos-89-16108-470-1-13ed3d62 kubelet[43215]: I0723 18:50:35.177354   43215 pod_workers.go:544] "Pod is waiting for termination, ignoring runtime-only kill until after pod worker is fully terminated" pod="cpu-manager-test-7541/non-gu-pod" podUID=9ce913f6-d32d-4180-a0c6-767b13921073

1418634958255165440/artifacts/n1-standard-2-ubuntu-gke-2004-1-20-v20210401-399317d9/kubelet.log
138414:Jul 23 19:53:56 n1-standard-2-ubuntu-gke-2004-1-20-v20210401-399317d9 kubelet[78518]: I0723 19:53:56.318457   78518 pod_workers.go:544] "Pod is waiting for termination, ignoring runtime-only kill until after pod worker is fully terminated" pod="cpu-manager-test-730/gu-pod" podUID=3f6ec04e-9f75-4421-907c-848a2668dee0

1418634958255165440/artifacts/n1-standard-2-cos-81-12871-1290-12-a8890dc5-system.log
193907:Jul 23 19:44:42 n1-standard-2-cos-81-12871-1290-12-a8890dc5 kubelet[63339]: I0723 19:44:42.436825   63339 pod_workers.go:544] "Pod is waiting for termination, ignoring runtime-only kill until after pod worker is fully terminated" pod="kube-system/static-disk-hog-5658dc75-ac43-4334-b3d7-ba903b26eed0-n1-standard-2-cos-81-12871-1290-12-a8890dc5" podUID=80727fe5f1b8237a54aacb2e10817c78

1418634958255165440/artifacts/n1-standard-2-ubuntu-gke-2004-1-20-v20210401-399317d9-system.log
149244:Jul 23 19:53:56 n1-standard-2-ubuntu-gke-2004-1-20-v20210401-399317d9 kubelet[78518]: I0723 19:53:56.318457   78518 pod_workers.go:544] "Pod is waiting for termination, ignoring runtime-only kill until after pod worker is fully terminated" pod="cpu-manager-test-730/gu-pod" podUID=3f6ec04e-9f75-4421-907c-848a2668dee0
```

**Comment by dims** [comment]
@ehashman please request @kubernetes/release-managers to mark this as `release-blocker` if it is...

**Comment by smarterclayton** [comment]
Looking at the linked job, I see:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/dynamic_kubelet_config_test.go:82
Timed out after 60.001s.
Expected
    <*errors.errorString | 0xc001428a30>: {
        s: "checkConfigMetrics: case: reset via nil config source: expect metrics (metrics.KubeletMetrics)map[kubelet_node_config_assigned:[<*>kubelet_node_config_assigned{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_active:[<*>kubelet_node_config_active{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_last_known_good:[<*>kubelet_node_config_last_known_good{node_config_kubelet_key=\"\", node_config_resource_version=\"\", node_config_source=\"local\", node_config_uid=\"\"} => 1 @[0]] kubelet_node_config_error:[<*>kubelet_node_config_error => 0 @[0]]] but got (metrics.KubeletMetrics)map[]",
    }
to be nil
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/dynamic_kubelet_config_test.go:1192
```

You are saying that means the static-disk-hog never completed?  The log message you see is intentional and the sign of correct behavior, so just seeing that log message alone doesn't mean anything is wrong.

**Comment by dims** [comment]
@smarterclayton - so far what i had was that master/HEAD fails when you run the optional pull-kubernetes-node-kubelet-serial, with a revert of #103668 the pull-kubernetes-node-kubelet-serial does not run out of disk space :) i have not yet looked at the detailed logs yet.

Also per @ehashman a simple revert is not enough as we will have to somehow ensure that the NPE that #103668 was supposed to fix will have to be taken care of as well. (so i closed the revert PR)

**Comment by dims** [comment]
marking this as release-blocker. right @ehashman @SergeyKanzhelev

**Comment by smarterclayton** [comment]
These errors are wierd.  The metrics the kubelet is supposed to expose don't even show up `kubelet_node_config_active` isn't even present in https://github.com/kubernetes/kubernetes/pull/103961 - did we break the node_config metrics somehow?  I don't think that's related to my changes at all.

**Comment by ehashman** [comment]
@smarterclayton looks like we deprecated the metrics as of 1.22: https://github.com/kubernetes/kubernetes/pull/102966/files#diff-7a99719139dd480a780b106a988e3175c2a5e72d48cc8399666843a8e631221d

However, deprecated metrics should still be emitted, they shouldn't be hidden until 4 releases ahead... https://kubernetes.io/blog/2021/04/23/kubernetes-release-1.21-metrics-stability-ga/#how-are-metrics-deprecated

/cc @logicalhan

**Comment by SergeyKanzhelev** [comment]
I think they are not registered when the feature flag is disabled.

**Comment by ehashman** [comment]
We explicitly enable the feature flag in these tests though, so that shouldn't be it...

**Comment by logicalhan** [comment]
> However, deprecated metrics should still be emitted, they shouldn't be hidden until 4 releases ahead... https://kubernetes.io/blog/2021/04/23/kubernetes-release-1.21-metrics-stability-ga/#how-are-metrics-deprecated

Only for stable metrics. 

However, I'm a bit confused because these should not be hidden until 1.23.

**Comment by ehashman** [comment]
Okay so some components support a `--show-hidden-metrics-for-version` flag, however the kubelet does not: https://github.com/kubernetes/kubernetes/pull/85282

This means the only way one can specify unhiding metrics is with a KubeletConfiguration. However, the node e2e tests don't support specifying one. Thus, we may want to consider adding this as a flag in a future release, or updating the node e2e tests to not need command line flags.

Hence, I suggest we just bump the metric deprecation to unhide the alpha metrics.

**Comment by smarterclayton** [comment]
Looking through the remaining node-serial tests, I think most of them are unrelated to my changes to pod lifecyle except possibly `E2eNode Suite: [sig-node] GarbageCollect [Serial][NodeFeature:GarbageCollect] Garbage Collection Test: One Non-restarting Container Should eventually garbage collect containers when we exceed the number of dead containers per container`, which I am investigating now.

**Comment by rphillips** [comment]
@smarterclayton I do not see a failed sandbox creation there. However, the Kubelet is racing at the same spot with a configmap update, and then restarting Kubelet within the same second of the garbage-collect test pod.

```
Jul 29 03:12:13 n1-standard-2-cos-89-16108-470-11-e2672b75 kubelet[7719]: I0729 03:12:13.152167    7719 configsync.go:204] "Kubelet config controller event" message="Kubelet restarting to use /api/v1/namespaces/kube-system/configmaps/testcfg-lp6lp, UID: 110e3693-7bf6-40c2-8f29-94915e5c5002, ResourceVersion: 517, KubeletConfigKey: kubelet"
Jul 29 03:12:13 n1-standard-2-cos-89-16108-470-11-e2672b75 kubelet[7719]: I0729 03:12:13.152167    7719 configsync.go:204] "Kubelet config controller event" message="Kubelet restarting to use /api/v1/namespaces/kube-system/configmaps/testcfg-lp6lp, UID: 110e3693-7bf6-40c2-8f29-94915e5c5002, ResourceVersion: 517, KubeletConfigKey: kubelet"
```

**Comment by ehashman** [comment]
Question: if we take https://github.com/kubernetes/kubernetes/pull/103992 can we fix the rest of these issues in backports? I'd like to unblock the release if at all possible.

**Comment by SergeyKanzhelev** [comment]
> Question: if we take #103992 can we fix the rest of these issues in backports? I'd like to unblock the release if at all possible.

Serial was not a blocking for previous releases and this is outstanding progress that for 1.22 we investigated so many of the failures. Since we are not running serial on 1.22 branch, unless we will find critical product issues, test fixes may not need to be backported. Perhaps we can discuss to start running serial on release branches once they are stabilized in master. So unless there are known problems (which I believe there is none), I'd suggest to not block the release

**Comment by smarterclayton** [comment]
In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1420578748725465088 `E2eNode Suite: [sig-node] Restart [Serial] [Slow] [Disruptive] [NodeFeature:ContainerRuntimeRestart] Container Runtime Network should recover from ip leak expand_more` is failing because it takes 1h30m to terminate the pod `test-e7842f3f-c74c-4285-9b78-3d26c9d53bac`.  Looking through logs we attempt to call syncTerminatingPod 86 times and each time it failed.  Grepping for the error returned 

```
 E0729 03:54:43.316147   48428 pod_workers.go:747] "Error syncing pod, skipping" err="detected running containers after a successful KillPod, CRI violation: [docker://57b03a8780ccc5c862e96d16c5ebc39fecffb110b10d00f72d390d3931659c32]" pod="restart-test-3493/test-e7842f3f-c74c-4285-9b78-3d26c9d53bac" podUID=512e8f6d-1557-44f5-b3b1-9ff6745c4992
...
 E0729 05:19:52.464196  117608 pod_workers.go:747] "Error syncing pod, skipping" err="detected running containers after a successful KillPod, CRI violation: [docker://57b03a8780ccc5c862e96d16c5ebc39fecffb110b10d00f72d390d3931659c32]" pod="restart-test-3493/test-e7842f3f-c74c-4285-9b78-3d26c9d53bac" podUID=512e8f6d-1557-44f5-b3b1-9ff6745c4992
 E0729 05:20:14.770915  117608 pod_workers.go:747] "Error syncing pod, skipping" err="[failed to \"KillContainer\" for \"test-e7842f3f-c74c-4285-9b78-3d26c9d53bac\" with KillContainerError: \"rpc error: code = Unknown desc = error during connect: Post \\\"http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/57b03a8780ccc5c862e96d16c5ebc39fecffb110b10d00f72d390d3931659c32/stop?t=30\\\": EOF\", failed to \"KillPodSandbox\" for \"512e8f6d-1557-44f5-b3b1-9ff6745c4992\" with KillPodSandboxError: \"rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\"]" pod="restart-test-3493/test-e7842f3f-c74c-4285-9b78-3d26c9d53bac" podUID=512e8f6d-1557-44f5-b3b1-9ff6745c4992
```

which is because of 

```
 I0729 05:19:52.464131  117608 kubelet.go:1813] "Post-termination container state" pod="restart-test-3493/test-e7842f3f-c74c-4285-9b78-3d26c9d53bac" podUID=512e8f6d-1557-44f5-b3b1-9ff6745c4992 containers="(test-e7842f3f-c74c-4285-9b78-3d26c9d53bac state=running exitCode=0 finishedAt=0001-01-01T00:00:00Z)"
 I0729 05:20:15.958943  117608 kubelet.go:1813] "Post-termination container state" pod="restart-test-3493/test-e7842f3f-c74c-4285-9b78-3d26c9d53bac" podUID=512e8f6d-1557-44f5-b3b1-9ff6745c4992 containers="(test-e7842f3f-c74c-4285-9b78-3d26c9d53bac state=exited exitCode=0 finishedAt=2021-07-29T03:10:02.668575184Z)"
```

which means that kill pod in dockershim was unable to kill a container.

This would probably be a release blocker, but I don't know that it's a regression.

**Comment by smarterclayton** [comment]
Spawned https://github.com/kubernetes/kubernetes/issues/104017

**Comment by ehashman** [comment]
Original issue as reported, failures that started 07/20 on https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial are now resolved due to https://github.com/kubernetes/kubernetes/pull/103980 landing on 07/28.

I have filed #104041 to revert the workaround with a proper fix in 1.23.

We still have work to do on ensuring the kubelet serial tests complete a full run, but they are looking much better. Getting log output in #104047 will help with debugging.

/close

**Comment by yuzhiquan** [comment]
@ehashman we meet same failing test in `pull-kubernetes-node-kubelet-serial` and `pull-kubernetes-node-kubelet-serial-containerd`, and seems like other pr also failing https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial, any suggestion on this?

**Comment by kerthcet** [comment]
> @ehashman we meet same failing test in `pull-kubernetes-node-kubelet-serial` and `pull-kubernetes-node-kubelet-serial-containerd`, and seems like other pr also failing https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial, any suggestion on this?

#104247 is tracing the `dynamic_kubelet_config_test` error.
