### ISSUE TITLE
client-go: cannot create/update resource with server-side apply on client-go fake clientset

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#103816]
Hello team.

#### What happened:

https://github.com/kubernetes/client-go/blob/ac207faedfb64acd5b99a2fb309b7044918b4dda/kubernetes/typed/core/v1/fake/fake_node.go#L138-L157

FakeNodes has Apply method, but we cannot create/update resource with server-side apply with this method.
And creating new resource and updating exist resource have different error message.

```
# create new resource
 nodes "nodename" not found

# update exist resource
PatchType is not supported 
```

#### What you expected to happen:

(1) support ApplyPatchType or (2) creating new resource makes the same error as updating (= `PatchType is not supported`)

#### How to reproduce it (as minimally and precisely as possible):

apply resource with fake clientset

#### Environment:
- client-go version: latest

**Comment by sanposhiho** [comment]
I'd like to take this issue
/assign

**Comment by sanposhiho** [comment]
I have no good idea to implement server-side apply logic on PatchActionImpl to support ApplyPatchType 😢
For now, I changed the error message on creating new resource with serverside apply. #103821

**Comment by apelisse** [comment]
We've discussed that with @jpbetz before. Not sure that's something we want to do.

**Comment by jpbetz** [comment]
> We've discussed that with Joe Betz before. Not sure that's something we want to do.

See our [earlier discussion about this](https://github.com/kubernetes/kubernetes/pull/99462#discussion_r590548928) and [the doc we wrote on the topic](https://docs.google.com/document/d/1ipi1sZd5rvPvplX_TV74gGOtFWJTf9N0qKnH2-rcI4s/edit#heading=h.io39zc1z1m28) for more detail.

**Comment by sanposhiho** [comment]
Hello.
OK, So this issue is duplicated with #99953. I'll close it with #103821, thanks

**Comment by sanposhiho** [comment]
Hi @howardjohn 
We can see two problems in this issue.

- fake clientset doesn't support server-side apply
- for the current situation, error message is not appropriate because user cannot know fake clientset doesn't support server-side apply from error message.

And the first one is duplicated with #99953. So I think it is ok to close this issue with #103821, because the PR will fix the second one.

**Comment by sanposhiho** [comment]
Aha, #99953 was closed because of non-update..
