### ISSUE TITLE
nodelocaldns - please add support for coredns 1.8.3 and 1.8.4

### ISSUE THREAD

**Issue by Shahard2** [kubernetes/kubernetes#103803]
#### What happened:

Having issues with nodelocal dns and coredns ...(when trying to upgrade to eks 1.20)

#### What you expected to happen:

It should work

#### How to reproduce it (as minimally and precisely as possible):
1. have a cluster with local dns
2. Try to upgrade to eks 1.20

**Comment by neolit123** [comment]
> Try to upgrade to eks 1.20

please contact the EKS support on what is required here.
the issue does not have sufficient context and whether that is a problem with nodelocaldns:
https://github.com/kubernetes/dns
where nodelocaldns lives.

this repository is for core k8s problems.

/close
/kind support
