### ISSUE TITLE
Endpoints not deleted when Service selector set to null

### ISSUE THREAD

**Issue by c2nes** [kubernetes/kubernetes#103804]
#### What happened:

I converted a `ClusterIP` service to an `ExternalName` service and then back to a `ClusterIP` service. After doing so I began receiving sporadic connection errors when trying to reach the service. During this process a corresponding Deployment was updated.

Upon investigating I found the service had two EndpointSlices, one owned by the Service and the other owned by the Services' Endpoints resource. The latter EndpointSlice contained stale IP addresses for pods which had since been deleted, which explained the sporadic connection errors.

When the Service type was set to `ExternalName` I (naturally) also removed the Service's selector. It seems this left the Endpoints resource orphaned, at which point it become eligible for EndpointSlice mirroring. Mirroring resulted in two EndpointSlices for the service, and after the service was set back to `ClusterIP` only the EndpointSlice owned by the Service was updated, presumably because the other Endpoints resource was no longer eligible for mirroring.

#### What you expected to happen:

I would expect the Endpoints resource to be deleted when the Services' selector is set to null.

#### How to reproduce it (as minimally and precisely as possible):

```bash
# Install nginx so we have some pods to point the service at
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install --set replicaCount=3 nginx bitnami/nginx

cat > service.yaml <<EOF
apiVersion: v1
kind: Service
metadata:
 name: my-svc
 namespace: default
spec:
 selector:
  app.kubernetes.io/name: nginx
 ports:
  - port: 80
    targetPort: http
EOF

kubectl apply -f service.yaml
kubectl patch --type=json service/my-svc --patch '[{"op":"replace","path":"/spec/selector","value":null}]'

# Note that the Endpoints resource still exists, and that a new EndpointSlice has been created
kubectl get endpoints
kubectl get endpointslice

# Roll the pods and reset the service
kubectl rollout restart deploy nginx
kubectl apply -f service.yaml

# Note that the Endpoints resource is updated and the original EndpointSlice is updated.
# The second EndpointSlice still exists, but is pointing at the original pod IPs.
kubectl get endpoints
kubectl get endpointslice
```

#### Anything else we need to know?:

n/a

#### Environment:

I originally hit this issue on an EKS cluster, but the reproduction steps above were performed on a kind cluster,

```shellsession
$ kind version
kind v0.11.1 go1.16.6 linux/amd64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yuswift** [comment]
duplicate
https://github.com/kubernetes/kubernetes/issues/103576

**Comment by dcbw** [comment]
Closing in favor of the earlier issue then. Let's follow up there. Thanks!
/close
