### ISSUE TITLE
reduce resource requirements of networkpolicy tests by 1/3

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#103802]
#### Which jobs are flaking:

The `NetPol` tests can take a long time to start since they require 9 pods.    This can result in failures like: 

```fail [k8s.io/kubernetes@v1.21.1/test/e2e/network/netpol/network_policy.go:1208]: unable to initialize resources```

Now, these tests were designed to fail fast - i.e. if you cant make x pods, dont bother testing.  however... We can reduce the odds that such a scenario happens i think by 

- reducing the cost of making x pods  (1) below
- reducing the number X (2 or 3)

Fix ideas below:

0) Potential super-easiest fix: request 50 millicored per `agnhost` pod.  Since the pods literally do nothing other then respond to one or two web requests... maybe thats enough to make the scheduler 50% more likely to create the pods quickly enough.

1) Potential easiest fix: reduce pod footprint by making 
```
func (p *Pod) KubePod() *v1.Pod {
```
configurable to take a protocol 
```
func (p *Pod) KubePod(protocols []v1.Protocol)
```
This would potentially reduce resource requirements by 66%

2)  have each test specify positive / negative control set and make model smart enough to only create required pods - and poller smart enough to poll required pods.  This makes the tests arbitrarily resource efficient - but then re-adds the original problem of now, any failures we get are going to require fine grained understanding of the test plan and lots of manual curation of exact testing requirements.  This is imo unsustainable. 

3) Have each test specify a "region" of the matrix.  i.e. "requiredNamespaces=x" would only poll this matrix and thus only require 3 pods instead of 9.... 

``` x/a x/b x/c
x/a
x/b
x/c
```

note that (3) and (1) could be combined.

...  given that the flake rate is 1/10 right now, i think reducing the resources by 66% (which you get for free w/ (1)) would be good enough as a first pass.

#### Testgrid link:

https://k8s-testgrid.appspot.com/sig-network-gce#network-policies,%20google-gce

**Comment by danwinship** [comment]
> 1. Potential easiest fix: reduce pod footprint by making
> 
> 
> ```
> func (p *Pod) KubePod() *v1.Pod {
> ```
> 
> configurable to take a protocol
> 
> ```
> func (p *Pod) KubePod(protocols []v1.Protocol)
> ```
> 
> This would potentially reduce resource requirements by 66%

I don't understand this. What exactly will `KubePod` do with the `protocols`, and how will this reduce "resource requirements", and how will reducing those resource requirements result in pods starting up faster?

**Comment by squeed** [comment]
Additional suggestion: Rather than issuing lots and lots of `Exec()`s, issue one Exec per pod, and execute multiple commands in them.

**Comment by rajaskakodkar** [comment]
> > 1. Potential easiest fix: reduce pod footprint by making
> > 
> > ```
> > func (p *Pod) KubePod() *v1.Pod {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > configurable to take a protocol
> > ```
> > func (p *Pod) KubePod(protocols []v1.Protocol)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This would potentially reduce resource requirements by 66%
> 
> I don't understand this. What exactly will `KubePod` do with the `protocols`, and how will this reduce "resource requirements", and how will reducing those resource requirements result in pods starting up faster?

By default every Pod is creating 6 containers (2 for each of the protocols), we can limit this by making it create containers for the protocols used in any particular test.

**Comment by jayunit100** [comment]
Ok, we've got this done now , rajas has ccd the mailing list w the results, so I think we will merge the PR in the next few days .

Overall results are as we predicted, implementing most of the ideas in this thread , empirically seeing 2/3->1/3 reduction in test times as expected ! :)

**Comment by jayunit100** [comment]
https://github.com/kubernetes/kubernetes/pull/104086
