### ISSUE TITLE
Move mounter source files out of cluster/gce/gci/mounter

### ISSUE THREAD

**Issue by benhxy** [kubernetes/kubernetes#103866]
cluster/ directory is deprecated (https://github.com/kubernetes/kubernetes/blob/master/cluster/README.md), and its source code should be moved to separate repos.

/kind cleanup
/sig cloud-provider

**Comment by liggitt** [comment]
/sig storage
/assign @msau42 
for triage/routing

**Comment by BenTheElder** [comment]
This one seems like maybe https://github.com/kubernetes/cloud-provider-gcp

**Comment by mattcary** [comment]
/remove-lifecycle rotten

@jpbetz do you know how this is interacting with cloud-provider-gcp?
