### ISSUE TITLE
Dedup the code in scheduler.go#scheduleOne()

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#103853]
In scheduler.go#scheduleOne(), some logic was written duplicately to recover failures in different phases. This looks a bit ugly. We should tease out the logic in scheduleOne() and eventually de-duplicated those logic.

The duplicated code includes:

- fwk.RunReservePluginsUnreserve()
- sched.SchedulerCache.ForgetPod()
- sched.recordSchedulingFailure()
- ...

/kind cleanup
/sig scheduling

**Comment by kerthcet** [comment]
hey @RyanBouchard, if you are out of bandwith, I'm glad to provide some help.🥷

**Comment by alculquicondor** [comment]
I almost opened a new issue, but better expand this thread:

The error handling is currently split in 2 places with no clear reason for the separation:
- `MakeDefaultErrorFunc` in `pkg/scheduler/factory.go`
- `recordSchedulingFailure` in `pkg/scheduler/scheduler.go`.

Moreover, `recordSchedulingFailure` is called from several places and #103805 is adding more calls.

My proposal:
- Merge the 2 functions in a single place, maybe even a put them in their own file `pkg/scheduler/error_handling.go`
- Defer the call in 2 places: once in the scheduling routine and once in the binding routine.
- Maybe recordSchedulingFailure could accept phase and status. Then, in a map we define the actions that should be taken for each combination, for example:
  - put in unschedulable queue
  - put in backoff queue
  - trigger MoveAllToActive (with/without the pod being scheduled)
- Add unit tests :)

**Comment by RyanBouchard** [comment]
Hi @kerthcet, really sorry for missing your comment. Any help is welcome. I actually have to back off for now. Just have too much on my plate at the moment.

**Comment by ritpanjw** [comment]
Hi @yuchen-sun  , this is bug triage here 👋
There hasn't been any activity on this issue for a couple of months now, Just want to make sure this issue is still on track for the 1.23?

**Comment by Huang-Wei** [comment]
@ritpanjw thanks for checking. It's still valid but more a cleanup issue, so feel free to take it out from the 1.23 tracking board.

**Comment by ritpanjw** [comment]
/milestone clear

clearing the milestone based on Huang's comment

**Comment by sanposhiho** [comment]
Hi @yuchen-sun 
Are you still working on this? I can take it over if you want.

**Comment by kidddddddddddddddddddddd** [comment]
I can't see why these codes are duplicated😢. Maybe someone can explain this a little bit more when they have time?

**Comment by alculquicondor** [comment]
See https://github.com/kubernetes/kubernetes/issues/103853#issuecomment-889370324

**Comment by Huang-Wei** [comment]
This issue is gonna reach its "anniversary" and no progress yet... I will spend some time on it. By combining the requirements from #110871, I have a rough working plan like this:

- [ ] Eliminate [MakeDefaultErrorFunc()](https://github.com/kubernetes/kubernetes/blob/9dc13f4f57e77258fcde4cb8e3d1566ed2b728c1/pkg/scheduler/scheduler.go#L352) by move its logic into [handleSchedulingFailure()](https://github.com/kubernetes/kubernetes/blob/9dc13f4f57e77258fcde4cb8e3d1566ed2b728c1/pkg/scheduler/schedule_one.go#L812). Also, refactor the [Error](https://github.com/kubernetes/kubernetes/blob/9dc13f4f57e77258fcde4cb8e3d1566ed2b728c1/pkg/scheduler/scheduler.go#L79) signature to sth. like `FailureHandlerFn` (abstraction for composing UT easily).
- [ ] In the new `handleSchedulingFailure()` function. Reuse err string so that we don't evaluate FitError multiple times.
- [ ] Refactor `handleSchedulingFailure()` to unify the calls in `scheduleOne()`. (more details in Aldo's https://github.com/kubernetes/kubernetes/issues/103853#issuecomment-889370324 starting at the 2nd bullet)

**Comment by sanposhiho** [comment]
We splitted `scheduleOne` into two functions; `schedulingCycle()` `bindingCycle()` in https://github.com/kubernetes/kubernetes/pull/111775

>  Refactor handleSchedulingFailure() to unify the calls in scheduleOne(). 

In the PR, we discussed some ideas for this.

One is calling `handleSchedulingFailure()` in `schedulingCycle()` `bindingCycle()` as `defer` like: https://github.com/kubernetes/kubernetes/commit/87d7e076540f30ab9e0cd28aaeb0d2baae7ef8c2
Another is returning needed information and call `handleSchedulingFailure()` in `scheduleOne()` (from @kerthcet ) https://github.com/kubernetes/kubernetes/pull/111775#discussion_r948976565

**Comment by kerthcet** [comment]
Diff looks like https://github.com/kubernetes/kubernetes/commit/6554946c5277cd7651d1186f343f89d9641c7abe

**Comment by Huang-Wei** [comment]
> Another is returning needed information and call handleSchedulingFailure() in scheduleOne()

+1 to this so we don't need to pass in `podsToActivate` and `start` to `schedulingCycle()`. Apart from that, if we embed nominatingInfo and reason to ScheduleResult, the number of return parameters is not concerning either - just need an additional err to be returned.

**Comment by kerthcet** [comment]
Then I'm going to address the advices based on the https://github.com/kubernetes/kubernetes/commit/6554946c5277cd7651d1186f343f89d9641c7abe, would you mind that? @sanposhiho

**Comment by sanposhiho** [comment]
@kerthcet 
No. I don’t mind. Feel free to go ahead. 👍

**Comment by kerthcet** [comment]
Updates:
After https://github.com/kubernetes/kubernetes/pull/112025, https://github.com/kubernetes/kubernetes/pull/112103 merged, I think we unified the calls in `scheduleOne()`. But we may have some other refactor works, e.g. currently, we pass error and reason to `handleSchedulingFailure`, this is a little ugly. Maybe we can directly pass-in status, for reason is always deduced by the status.

**Comment by kerthcet** [comment]
@kidddddddddddddddddddddd would you like to take a look?

**Comment by kidddddddddddddddddddddd** [comment]
> @kidddddddddddddddddddddd would you like to take a look?

Sure, and BTW is this status `scheduler.framework.Status` ?
>Maybe we can directly pass-in status, for reason is always deduced by the status.

**Comment by kerthcet** [comment]
Yes

**Comment by kerthcet** [comment]
After https://github.com/kubernetes/kubernetes/pull/114082 got merged, I think we can close this @Huang-Wei
