### ISSUE TITLE
Removing UserSpace Proxying from Kubernetes core/

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#103860]
#### What would you like to be added:

Today in sig-network we all totally decided  to remove the userspace linux and windows proxies from kubernetes core, consensus was reached amongst the few remaining users of the kube proxy in userspace (project antrea @antoninbas , as well as openshift engineers @danwinship).

Im not sure this requires a KEP since, after all, the userspace proxy is essentially basically an untested easter egg that resides in K8s for legacy purposes, but we can write one if folks really want one. 

My proposal would be:

1) Heavily comment the code that the proxy is being removed in 1.23, including deprecation on the flag options for the kube-proxy mode.

2) In 1.24, stop accepting any feature updates related to Kube proxy in userspace other then CVEs or compilation errors.

3) In 1.25, delete the existing Kubernetes code for userspace proxy.  During this time, we can integrate the code into https://github.com/kubernetes-sigs/kpng as a optional backend, which will give users the ability to play with a userspace proxy in a sandbox if they want to, while also allowing a 'non production' version of the userspace proxy to live on in an experimental state.  

Does anyone want to help or take this issue over? I have no strong opinions on the implementation :), but i think this is the fastest and easiest.  

#### Why is this needed:

At this point we are heavily lacking test coverage for the userspace proxy.
- It hasnt been updated to support endpoint slices
- topology features are also not supported
- we have other efforts in place to modularize kube-proxy some day anyways, and so removing what is in-tree is synergistic with those efforts
- on kind we know there will not be support for the userspace linux proxy  https://github.com/kubernetes-sigs/kind/pull/2264

**Comment by thockin** [comment]
Yeah, in particular I want to print/log a warning and maybe add a metric when we fall back on userspace.

**Comment by aojea** [comment]
I've just realized we have to remove it form the website docs too:
https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/services-networking/service.md#user-space-proxy-mode-proxy-mode-userspace

**Comment by khenidak** [comment]
/honk

yes. please.

**Comment by thockin** [comment]
All told,  the iptables mode has been pretty stable - hopefully we don't
depend on too many overly-modern things.  route_localnet still needs to be
resolved properly (IMO) as a bug.

**Comment by jayunit100** [comment]
we've now deprecated the windows userspace proxy in the command line.  With the new proxy pretty close at hand in KPNG, we should be able to cleanly delete the rest in the next release if folks are ok with that.

**Comment by jayunit100** [comment]
https://github.com/kubernetes-sigs/kpng/pull/83 <-- finished porting it over for the windows userspace side ! ok, if anyone wants, they can delete that portion of the codebase :) if not we'll issue a PR in a few weeks once *linux userspace* porting is done w the entire removal....

**Comment by BenTheElder** [comment]
> on kind we know there will not be support for the userspace linux proxy https://github.com/kubernetes-sigs/kind/pull/2264

Actually, that is circular ... 🙃 

https://github.com/kubernetes-sigs/kind/pull/2264#issuecomment-885814334

Devil's advocate: 
How much tech debt is this code carrying?
How much effort would it be to add a CI coverage?

It looks like there's some easily identified niche usage still:
https://grep.app/search?q=--proxy-mode%3Duserspace

**Comment by thockin** [comment]
The tech debt here is that we almost never add "modern" support to
userspace - traffic policy, endpoint slices, etc.  It's effectively
abandoned.

**Comment by aojea** [comment]
/reopen

I still see it :smile: https://github.com/kubernetes/kubernetes/tree/master/pkg/proxy/userspace

kindly ping @jayunit100

**Comment by jayunit100** [comment]
i guess we can close this pretty soon
