### ISSUE TITLE
[release-1.19] [release-1.20] e2e tests can fail because of dockerhub rate limits

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#103871]
/kind bug
/area test

#### What happened:

Last year Docker Hub restricted the amount of image pulls for anonymous and free users. From https://www.docker.com/increase-rate-limits:

> On November 20, 2020, rate limits anonymous and free authenticated use of Docker Hub went into effect. Anonymous and Free Docker Hub users are limited to 100 and 200 container image pull requests per six hours.

100 container image pull requests per six hours are way too low. Running K8s e2e tests can fail because of dockerhub rate limits.

The issue seems to be mitigated by https://github.com/kubernetes/kubernetes/pull/98964 in v1.21. I think we need to backport this to release-1.19 and release-1.20.

#### What you expected to happen:
No dockerhub rate limits on e2e tests execution.

#### How to reproduce it (as minimally and precisely as possible):

1. Run e2e test with kubetest against cluster with exhausted docker hub pull rate limits

```
$ kubetest --provider=skeleton --deployment=local --test --check-version-skew=false  --test_args=--ginkgo.flakeAttempts=1 --ginkgo.dryRun=false --minStartupPods=1 --ginkgo.focus=\[sig-cli\]\sKubectl\sclient\sKubectl\scopy\sshould\scopy\sa\sfile\sfrom\sa\srunning\sPod
```

2. Make sure that the e2e test execution can fail because of dockerhub rate limits:

See example events:

```
time="2021-07-20T02:56:15Z" level=info msg="At 0001-01-01 00:00:00 +0000 UTC - event for busybox1: {default-scheduler } Scheduled: Successfully assigned kubectl-9536/busybox1 to worker-1-z1-6b445-gpx5s"
time="2021-07-20T02:56:15Z" level=info msg="At 2021-07-20 02:51:14 +0000 UTC - event for busybox1: {kubelet worker-1-z1-6b445-gpx5s} Pulling: Pulling image \"busybox\""
time="2021-07-20T02:56:15Z" level=info msg="At 2021-07-20 02:51:15 +0000 UTC - event for busybox1: {kubelet worker-1-z1-6b445-gpx5s} Failed: Failed to pull image \"busybox\": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
time="2021-07-20T02:56:15Z" level=info msg="At 2021-07-20 02:51:15 +0000 UTC - event for busybox1: {kubelet worker-1-z1-6b445-gpx5s} Failed: Error: ErrImagePull"
time="2021-07-20T02:56:15Z" level=info msg="At 2021-07-20 02:51:16 +0000 UTC - event for busybox1: {kubelet worker-1-z1-6b445-gpx5s} BackOff: Back-off pulling image \"busybox\""
time="2021-07-20T02:56:15Z" level=info msg="At 2021-07-20 02:51:16 +0000 UTC - event for busybox1: {kubelet worker-1-z1-6b445-gpx5s} Failed: Error: ImagePullBackOff"
```

#### Environment:
- Kubernetes version (use `kubectl version`): release-1.19, release-1.20
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by BenTheElder** [comment]
This is a breaking change and may not be cherry pick approvable. People have already set up their airgapped testing expecting to mirror these from dockerhub.

**Comment by BenTheElder** [comment]
I'm also not sure that all of the images are identical other than hosting location, I think in the process some of them were upgraded.

**Comment by spiffxp** [comment]
This might not be a straight cherry-pick.  As @BenTheElder says It could be a breaking change and depends on a few things:
- whether any test images changed functionality since their release
- when the change to list images used in e2e tests landed (which can facilitate air gapping)
- when the change to use `KUBE_TEST_REPO` landed

I don't have the time to do this legwork right now, if someone does, that could help move the discussion forward.

/sig release
I'm tagging in SIG Release since they would need to be involved in deciding what's acceptable to backport or not.

**Comment by aojea** [comment]
the impact on kubernetes CI, the effort and the risk to break something can be considerable, it is also an external (and unfortunate problem), is this really worth the effort?

**Comment by BenTheElder** [comment]
With our own CI doing fine, and the risk from breaking backported changes, I don't think this is going to change.

In 1.21+ this is resolved, and it won't be all that long before those are the supported versions of Kubernetes anyhow.
