### ISSUE TITLE
Ingress Nginx custom backend for errors

### ISSUE THREAD

**Issue by itisguptak** [kubernetes/kubernetes#103817]
Hi,

I have implemented custom default backend for our Ingress nginx controller using https://kubernetes.github.io/ingress-nginx/examples/customization/custom-errors/#customized-default-backend

It's working all fine except that it also overrides the app error responses. E.g. If a backend app is responding with a 401 or a 503, the UI client looks at the app error response to render the response. But now since I have implemented custom backend, it's not seeing the error response from the app but the response from ingress. 

Is there any way we can allow original error response from app to go the client with custom backend enabled at ingress level? 

Thank you. 

/sig network

**Comment by rikatz** [comment]
@itisguptak thanks for your issue.

For ingress-nginx, I kindly ask you to open the issue in github.com/kubernetes/ingress-nginx

I'm going to close this issue, please feel free to reach on ingress-nginx repo and also on #ingress-nginx-users in Kubernetes Slack

Thanks!

/close
