### ISSUE TITLE
Build and use a new skyDNS container

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10386]
After 1.0 for risk reasons.  SkyDNS now builds their own container from Alpine, so much smaller than before.

**Comment by thockin** [comment]
When we do this we can switch the healthcheck to use 'dig' instead of 'nslookup'

**Comment by thockin** [comment]
Maybe obsoletes #9290

**Comment by so0k** [comment]
Is there any reason not to change `cluster/addons/dns/skydns-rc.yaml.in` to use the `skynetservices/skydns:2.5.3a` image from [docker hub](https://hub.docker.com/r/skynetservices/skydns/tags/) instead of the gcr.io image?

**Comment by thockin** [comment]
Their image used to be huge but now it's from busybox, so very reasonable.

I am still worried about us officially releasing a product that pulls
images that we don't control.  It's not that I don't trust people, it's
just that we've seen git hashes get obliterated by well-intentioned changes
(hence we vendor deps), and we've seen docker hub tags get re-written or
disappear.

It is my opinion that part of our release process should be ensuring that
EVERY container we use ANYWHERE in kubernetes is pulled and re-pushed to
our own registry, or maybe even rebuilt from source.  It's the moral
equivalent of vendoring our dependencies.

**Comment by so0k** [comment]
Understood, but Current gcr image tags aren't very clear which version of SkyDNS is actually used:

```
gcr.io/google_containers/skydns   2015-10-13-8c72f8c   11 weeks ago   40.55 MB
skynetservices/skydns             2.5.3a               11 weeks ago   18.86 MB
gcr.io/google_containers/skydns   2015-03-11-001       9 months ago   8.811 MB
```

**Comment by thockin** [comment]
@
