### ISSUE TITLE
ci-crio-cgroupv1-node-e2e-conformance job is flaking due to test timeouts

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#103856]
#### Which jobs are flaking:

- ci-crio-cgroupv1-node-e2e-conformance

#### Which test(s) are flaking:

- many

#### Testgrid link:

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance&width=20

#### Reason for failure:

Many tests failing, they seem to be timing out.

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1418052152126869504

#### Anything else we need to know:

Flakiness began late on 07/21 with this failure run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1418021944074178560

Note that cri-o jobs do not pin version of cri-o or Fedora CoreOS so it is possible the underlying components got bumped.

/sig node

**Comment by haircommander** [comment]
I will take this

/assign

**Comment by ehashman** [comment]
/remove-kind flake
/kind failing-test

as stats/summary test is now continuously failing

**Comment by haircommander** [comment]
it is hard to tell because the tests were very flaky before, but I am suspicious of https://github.com/kubernetes/kubernetes/pull/103713 for causing the perma-failures. I have opened https://github.com/kubernetes/kubernetes/pull/103959 to test, where we can compare the difference in failures. It's possible this is just due to some crio configuration not being happy with the metrics server bump

**Comment by ehashman** [comment]
/remove-lifecycle stale
/remove-kind failing-test
/kind flake

back to flaking: https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance&width=20&exclude-non-failed-tests=

```
E2eNode Suite.[sig-network] Networking Granular Checks: Pods should function for node-pod communication: http [LinuxOnly] [NodeConformance] [Conformance]
E2eNode Suite.[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
E2eNode Suite.[sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart exec hook properly [NodeConformance] [Conformance]
E2eNode Suite.[sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute prestop exec hook properly [NodeConformance] [Conformance]
E2eNode Suite.[sig-network] Networking Granular Checks: Pods should function for intra-pod communication: http [NodeConformance] [Conformance]
E2eNode Suite.[sig-network] Networking Granular Checks: Pods should function for node-pod communication: udp [LinuxOnly] [NodeConformance] [Conformance]
```

**Comment by haircommander** [comment]
it looks like the major page fault value is a bit off. I've opened https://github.com/kubernetes/kubernetes/pull/106533 to fix
