### ISSUE TITLE
Move conformance source out of cluster/images/conformance

### ISSUE THREAD

**Issue by benhxy** [kubernetes/kubernetes#103867]
cluster/ directory is deprecated (https://github.com/kubernetes/kubernetes/blob/master/cluster/README.md), and its source code should be moved to separate repos.

/kind cleanup
/sig cloud-provider
/sig testing

**Comment by liggitt** [comment]
> its source code should be moved to separate repos

or at least to a separate dir... at first glance, `test/images` seems like a good destination for this
