### ISSUE TITLE
Delete old use-specific tokens

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10387]
Now that service accounts work properly, we can delete things like the DNS token and the code needed to build it.

**Comment by thockin** [comment]
@erictune I forget where this live(d) are we still generating the old-style tokens?  Or can we close this?

**Comment by mikedanese** [comment]
This isn't done yet.

**Comment by liggitt** [comment]
dupe of https://github.com/kubernetes/kubernetes/issues/13110
