### ISSUE TITLE
Optimize heapster memory usage

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#10396]
After #10256, we allocate 2.5GB to heapster.  We need that for max utilization, but we effectively permanently allocate that memory even for relatively small clusters.  We also assign 2GB to influx.

It would be good not to have such a high fixed overhead.

The low-hanging fruit here is probably optimizing heapster, because it is under our control.

**Comment by vishh** [comment]
Heapster's memory usage is currently proportional to the number of
containers. 2.5 GB is the ceiling. Smaller clusters can set a lower limit.

**Comment by justinsb** [comment]
@vishh - right, and I totally understand how we got here.  I don't even think 2.5GB is that unreasonable if you're running 10k containers.  It just rules out smaller instance types (f1-micro & g1-small on GCE), and it is mostly going to be wasted memory for smaller clusters.  We don't have any resource strategies other than "allocate max" right now, so I don't think we have a choice.

Not a big deal, but maybe post v1 we can look at a heapster memory profile!  I'd love to help with that - I'd like to get a better understanding of Go GC/memory usage.

**Comment by devlina** [comment]
Hi @vishh , eventer container is not able to start due to this: 
```
6m    5s    31    {kubelet 10.240.74.6}        Warning    FailedSync    Error syncing pod, skipping: failed to "StartContainer" for "eventer" with RunContainerError: "runContainer: API error (500): Minimum memory limit allowed is 4MB\n"
```
top command says : KiB Mem:   4047456 total,  3884808 used,   162648 free
Do I need more memory in the system to run the heapster pod? or, something else is broken.

**Comment by vishh** [comment]
The error seems to indicate that the memory limit for `eventer` is set to a
value that is lesser than `4MB`.

**Comment by devlina** [comment]
Oh I mixed up `m` and `Mi`. Will fix it. Thank you.
