### ISSUE TITLE
Unable to connect to the server: EOF

### ISSUE THREAD

**Issue by WangYunT** [kubernetes/kubernetes#103969]
[root@k8s-master01 pki]# kubectl get cs
**Unable to connect to the server: EOF**

[root@k8s-master01 pki]# systemctl status kubelet.service -l
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2021-07-28 11:08:45 HKT; 1min 56s ago
     Docs: https://kubernetes.io/docs/
 Main PID: 10987 (kubelet)
    Tasks: 26
   Memory: 34.7M
   CGroup: /system.slice/kubelet.service
           └─10987 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=k8s.gcr.io/pause:3.1

Jul 28 11:10:41 k8s-master01 kubelet[10987]: E0728 11:10:41.779786   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:41 k8s-master01 kubelet[10987]: E0728 11:10:41.880439   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:41 k8s-master01 kubelet[10987]: E0728 11:10:41.980829   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.081187   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.181598   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.282061   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.382757   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.483208   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.583628   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:10:42 k8s-master01 kubelet[10987]: E0728 11:10:42.684072   10987 kubelet.go:2252] node "k8s-master01" not found

Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.420646   10987 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:454: Failed to list *v1.Node: Get https://192.168.131.199:26443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-master01&limit=500&resourceVersion=0: EOF
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.502145   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.602727   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.703400   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.752275   10987 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.168.131.199:26443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: EOF
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.803854   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.904123   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:30 k8s-master01 kubelet[10987]: E0728 11:11:30.947233   10987 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:445: Failed to list *v1.Service: Get https://192.168.131.199:26443/api/v1/services?limit=500&resourceVersion=0: EOF
Jul 28 11:11:31 k8s-master01 kubelet[10987]: E0728 11:11:31.004538   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:31 k8s-master01 kubelet[10987]: E0728 11:11:31.104981   10987 kubelet.go:2252] node "k8s-master01" not found
Jul 28 11:11:31 k8s-master01 kubelet[10987]: E0728 11:11:31.187806   10987 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192.168.131.199:26443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: EOF

[root@k8s-master01 csboci]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:08:59Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: EOF

**Comment by dimakow** [comment]
Hi @WangYunT 

could you please elaborate your problem instead of just pasting logs? Like **What happened?**, **What you expected to happen?** and **How to reproduce it ?**

At the moment it seems you had some connectivity problems to API-Server or API-Server had in general a problem.

**Comment by ehashman** [comment]
/remove-sig node

This is an API server connectivity issue; neither your kubelet nor your kubectl client are able to talk to an api-server.

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/kind support
/close
