### ISSUE TITLE
GetNodeResources is no longer used

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#10399]
After #8164, nodecontroller no longer calls GetNodeResources.

I don't see a comment on this being deliberate.  @cjcullen ?

Nodes are still reporting memory correctly (I presume the kubelet is reporting it).  I don't know if cores are being reported correctly, but e.g. on AWS cores have very different sizes, so we can't rely on a simple core-count.

**Comment by erictune** [comment]
@justinsb what do you mean by "core have very different sizes"?

**Comment by roberthbailey** [comment]
I think nodes have reported resources for a while. Before nodes self registered, the nodecontroller would get an initial resource estimate for the node but that should no longer be necessary since as soon as the node is registered it will have an accurate resource representation.

**Comment by justinsb** [comment]
On AWS, the core count is only a proxy for power.  AWS defines a different unit (called ECU) which they use to provide a way to normalize this.  These instance types all have two cores, but they have varying numbers of ECUs:

m3.large: 6.5
c4.large: 8
c3.large: 7

'legacy' instance types have more variation:

m1.large: 4
c1.medium: 5
m2.large: 6.5


It's not the end of the world if we simply use core-count; I was mostly surprised to see that GetNodeResources was no longer used.

Thinking about this more, I guess the point is that the CPU limits (at the cgroups level) will be in terms of cores, so nodes should report actual cores in these units.

I guess for v-next we should consider normalizing a container's CPU request by the power of a core.  And I shouldn't be reporting fictitious units in the aws implementation of GetNodeResources, although I'm saved because it is not currently used (correctly or incorrectly) :-)

**Comment by erictune** [comment]
Actually, justinsb, it appears you are the _only_ one doing it right.  In `docs/resources.md` we state that cpu is actually in units of `KCU`, which is sort of like an `ECU` except that we haven't defined it yet :frowning:

**Comment by erictune** [comment]
Filed #10438 for the ECU/normalized-cpu issue, so that this Issue can just be about deleting dead code.
