### ISSUE TITLE
kubelet cpu-manager not exclude reserved cpus from DefaultCPUSet

### ISSUE THREAD

**Issue by huzhengchuan** [kubernetes/kubernetes#103910]
#### What happened:
setting "--reserved-cpus=0-4 --enforce-node-allocatable=pods  --cpu-manager-policy=static" bootstrap kubelet.  Want to let 0-4 cpu not used by container.  and create burstable and besteffort  pod  and check cpu_manager_state file

[root@node02 ~]# cat /var/lib/kubelet/cpu_manager_state 
{"policyName":"static","defaultCpuSet":"0-31","checksum":3540042759}

#### What you expected to happen:
kubelet cpu-manager exclude reserved cpus from DefaultCPUSet, , DefaultCPUSet need to set "defaultCpuSet":"5-31"

#### Environment:
- Kubernetes version (use `kubectl version`): 
- [root@master1 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"77cb7af1b7d6b830a51528961c5fe390533afc69", GitTreeState:"clean", BuildDate:"2021-03-25T01:50:01Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"c0e55a819230dcce19f1ad1645c40c1ed9d06ad1", GitTreeState:"clean", BuildDate:"2021-03-24T02:32:42Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
x86

- OS (e.g: `cat /etc/os-release`):
[root@master1 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- Kernel (e.g. `uname -a`):
[root@master1 ~]# uname -a
Linux master1 3.10.0-957.el7.x86_64 

- Install tools:
minkube
- Network plugin and version (if this is a network-related bug):
calico

- Others:
machine cpu is 32c

**Comment by dimakow** [comment]
Do you see any wrong cpu allocations for spawned containers?

By looking at the code i see that DefaultCPUSet should always be all CPU's and only during allocation in `GetAllocatableCPUs` the CPU's are being reduced by reserved CPU's:

https://github.com/kubernetes/kubernetes/blob/73dd5c840662bb066a146d0871216333181f4b64/pkg/kubelet/cm/cpumanager/policy_static.go#L191

PS: 18.15 is out of maintenance

**Comment by huzhengchuan** [comment]
`GetAllocatableCPUs` is only use to Guaranteed pod. allocate cpu to guaranteed pod is  reduced reserved cpus. But for burstable and besteffort pod always use DefaultCPUSet, it will let burstable and besteffort pod use the reserved cpu. 

I create burstable pod, and check the cgroup of container

> [root@node02 1f02f559d9b9886179b7941a00bfb67be7a0701f785def1cf5a0e11cb38b329f]# pwd
/sys/fs/cgroup/cpuset/kubepods/burstable/pod4816d23f-4190-4594-a6a0-c0dd520068e5/1f02f559d9b9886179b7941a00bfb67be7a0701f785def1cf5a0e11cb38b329f
[root@node02 1f02f559d9b9886179b7941a00bfb67be7a0701f785def1cf5a0e11cb38b329f]# cat cpuset.cpus 
0-31

I think it need to set 5-31, because 0-4 is reserved, not let container running on the reserved cpus.

**Comment by gjkim42** [comment]
/assign
/kind bug

Reproduced at v1.20.9

**Comment by gjkim42** [comment]
```sh
# guaranteed pod
$ cat podc7e0a603-b288-40d9-82dc-d6d2eb87c557/aa78d51576dbaae8ee00490bd33cfd6c6031e7c6194a801f162dff17b108522d/cpuset.cpus 
6
# burstable pod
$ cat burstable/pod24763d37-b4cb-4b9e-af96-2e218d9e0e97/91791e68142e6b10499577dfbf148b68b8dec68f5144389d6dc234ca7ed9417a/cpuset.cpus 
0-5,7-11
# besteffort pod
$ cat besteffort/pod7f720073-caeb-4a9f-a359-5085d892776c/dfc7efa50318d890eacbcdf84529806d1bd6910935882374a94bd768dd0c81c4/cpuset.cpus 
0-5,7-11
```

**Comment by cynepco3hahue** [comment]
The CPU manager does not exclude the reserved-cpus from the default CPU set, because you can end with the situation when all non-reserved CPUs are used by guaranteed pods. It is the intentional behavior, probably we should update the doc to make it more clear.

**Comment by huzhengchuan** [comment]
--reserved-cpus is only fix the guaranteed pod not use the reserved CPUs when the cpu policy is static.  perhaps we need a strict isolated cpu manager let all container not running the reserved CPUs

**Comment by gjkim42** [comment]
KEP: https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/375-cpu-manager/README.md
Docs: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

**Comment by gjkim42** [comment]
/unassign

I agree with @cynepco3hahue

> This is because zero CPU reservation would allow the shared pool to become empty.


> The static policy maintains the following sets of logical CPUs:
>
> - **SHARED:** Burstable, BestEffort, and non-integral Guaranteed containers
  run here. Initially this contains all CPU IDs on the system. As
  exclusive allocations are created and destroyed, this CPU set shrinks
  and grows, accordingly. This is stored in the state as the default
  CPU set.
>
> - **RESERVED:** A subset of the shared pool which is not exclusively
  allocatable. The membership of this pool is static for the lifetime of
  the Kubelet. The size of the reserved pool is the ceiling of the total
  CPU reservation from `--kube-reserved` and `--system-reserved`.
  Reserved CPUs are taken topologically starting with lowest-indexed
  physical core, as reported by cAdvisor.
>
> - **ASSIGNABLE:** Equal to `SHARED - RESERVED`. Exclusive CPUs are allocated
  from this pool.
>
> - **EXCLUSIVE ALLOCATIONS:** CPU sets assigned exclusively to one container.
  These are stored as explicit assignments in the state.

which means that the reserved CPU is a part of the shared pool.



> perhaps we need a strict isolated cpu manager let all container not running the reserved CPUs

I think that will need a feature request to make a new cpu-manager or change the semantics of the static cpu-manager policy.

**Comment by huzhengchuan** [comment]
thanks!  close this issue first, the feature about the strict isolated cpu manager need more discuss
