### ISSUE TITLE
CSI E2E: Support StorageClass Secrets E2E test in CSI

### ISSUE THREAD

**Issue by gxglls** [kubernetes/kubernetes#103936]
#### What would you like to be added:
My csi driver implements the authentication function in accordance with https://kubernetes-csi.github.io/docs/secrets-and-credentials.html#secrets-and-credentials. The underlying implementation is to use iSCSI's CHAP. But I did not find any e2e test related to CSI authentication/credentials, I will try to implement it and submit a PR

#### Why is this needed:
e2e testing needs to cover CSI certification related functions

**Comment by BenTheElder** [comment]
SIG testing owns test frameworks, CI tools, and other things that facilitate testing, however the ask here appears to be for more tests of SIG storage code, which would be owned by SIG storage then.

FWIW this sounds like a good idea.

**Comment by gxglls** [comment]
@BenTheElder ，Thank you for your answer


> which would be owned by SIG storage then

Should it remove the testing tag instead of the storage tag?
