### ISSUE TITLE
Enable pod creation in case of AZ failover with EBS as persistent volumes

### ISSUE THREAD

**Issue by leela-maheshwar** [kubernetes/kubernetes#103909]
#### What would you like to be added:
My current application uses a single pod instance and stores application data on EBS volume (dynamically provisioned) attached to the application container inside the pod. By default, K8S creates the Pod and Volume on one of AZ in the given cloud environment. With this, if there is AZ failure, K8S is not spawning a new pod on a different AZ with new fresh EBS volume on the new AZ. My application is fine to start with the fresh new volume on the new AZ and it's fine for data loss here. Would love k8s to provide this feature by default or some config basis.

#### Why is this needed:

This will make our application much more resilient in case of AZ failure.

**Comment by fulviodenza** [comment]
I would love working on this feature, if approved, I ask to implement this condition. I find it very useful

**Comment by Huang-Wei** [comment]
> With this, if there is AZ failure, K8S is not spawning a new pod on a different AZ with new fresh EBS volume on the new AZ.

Are your nodes located in one AZ? or across multiple AZs? or you want an external component (like cluster autoscaler) to provision a new node for the unschedulable pod to land on?

**Comment by leela-maheshwar** [comment]
We have nodes present in all 3 AZ's.

**Comment by Huang-Wei** [comment]
If there is a node failure, the controller manager is able to detect the missing node heartbeat, and then wait for a grace period to spin up new pods to replace the old ones on the old node. So I don't quite understand "K8S is not spawning a new pod". Can you elaborate?

**Comment by leela-maheshwar** [comment]
@Huang-Wei Let's assume we have 3 AZ's and 3 nodes per AZ. My application is deployed as a single pod with PVC backed by EBS. Initially, when we deploy the pod k8s picks one AZ, let's assume this is AZ1 and k8s issues cloud provider to create EBS on AZ1. Here the pod reference points to the PVC object which is referring to EBS on AZ1. Let's say if AZ1 goes down, k8s will try to create the pod on a new node in AZ2. But the new pod still refers to the same PVC object which is pointing to EBS on AZ1. As AZ1 is not available now, the newly created pod on AZ2 is not coming up.  The ask here is, can we allow k8s to create a new pod along with new PVC/EBS on AZ2 by de-referencing the old PVC/EBS on AZ1? We are ok to lose the data that is accumulated on EBS on AZ1 and start with a fresh new EBS on AZ2.

**Comment by Huang-Wei** [comment]
This sounds like a request for @kubernetes/sig-storage-feature-requests 
/sig storage
