### ISSUE TITLE
Operationexecutor log format problem

### ISSUE THREAD

**Issue by njuptlzf** [kubernetes/kubernetes#103907]
#### What happened:
`I0726 15:05:12.072600   39595 operation_generator.go:974] UnmountDevice succeeded for volume "volume-name" %!(EXTRA string=UnmountDevice succeeded for volume "volume-name" (UniqueName: "fake-plugin/fake-device1") on node "mynodename" )
`

Here at the same time, simple, detail information is returned and formatting problems are caused.
#### What you expected to happen:
No format error. For example, only datail is returned.
#### How to reproduce it (as minimally and precisely as possible):
```shell
cd pkg/kubelet/volumemanager/reconciler
go test . -v
```
#### Anything else we need to know?:
Found from running pkg/kubelet/volumemanager/reconciler/reconciler_test.go

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/good-first-issue

**Comment by yuzhiquan** [comment]
Seems like caused by https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L974, this line still not in structured logging, we need to handle these messages.

**Comment by njuptlzf** [comment]
I don’t know if this package will be accepted for structured log migration. 
It seems that only kubelet is required now.

**Comment by ping035627** [comment]
I think it‘s only kubelet required too.

**Comment by yuswift** [comment]
@mcbenjemaa Hi, sorry about that I didn't realize that you assign yourself to this issue. Hope #103911 is helpful for this issue.

**Comment by sochoaAtMulesoft** [comment]
Interesting.  I'm running the same test locally: 

```
~/src/k8s/pkg/kubelet/volumemanager/reconciler on master! 16:11:09
$ uname -a
Darwin <machine-name> 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64

~/src/k8s/pkg/kubelet/volumemanager/reconciler on master! 16:13:12
$ go test . -v | tee test-$(date +"%Y-%m-%d").log
...

~/src/k8s/pkg/kubelet/volumemanager/reconciler on master! 16:13:25
$ grep -iq 'operation_generator.go:974' test-2021-12-17.log || echo "NOT FOUND"
NOT FOUND
```

And I'm not finding the same log output issue there.  Can anyone else see it on `a1e8a5bf39d` (master)?

**Comment by pohly** [comment]
@sochoaAtMulesoft: it's quite likely that the source code line changed. Search for "EXTRA string" instead.
