### ISSUE TITLE
AKS provider, cannot use public ip address located in another subscription

### ISSUE THREAD

**Issue by sanderdam** [kubernetes/kubernetes#103994]
#### What happened:

The legacy-cloud-provider azure cannot get a loadbalancer IP address from another resource group in another subscription.
The azure_loadbalancer.go file has support for the annotation: service.beta.kubernetes.io/azure-load-balancer-resource-group, but it than assumes the same subscription as where the AKS is hosted in.

#### What you expected to happen:

I expect that I can specify what subscription-id the public ip address is in by using another annotation. Probably named: service.beta.kubernetes.io/azure-load-balancer-subscription-id

#### How to reproduce it (as minimally and precisely as possible):

Create an AKS cluster in resource-group: A, located in subscription A. Create a public ip resource in resource-group B, located in subscription B. All in the same Azure tenant. Create a role assignment in resource group B which gives the AKS cluster identity Network Contributor rights. In my case I want to deploy the Nginx Ingress Controller. I specify the "azure-load-balancer-resource-group" annotation in the Helm release but it fails given the following error:

```
Warning  ListPublicIPs           8s (x3 over 23s)  azure-cloud-provider  Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client 'c512c820-94a7-4b3a-933b-xxxxxxxxxxxx' with object id 'c512c820-94a7-4b3a-933b-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Network/publicIPAddresses/read' over scope '/subscriptions/480f0bde-1a1c-4b3d-a7a6-xxxxxxxxxxxx/resourceGroups/rg-test/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
  Warning  SyncLoadBalancerFailed  8s (x3 over 23s)  service-controller    Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: {"error":{"code":"AuthorizationFailed","message":"The client 'c512c820-94a7-4b3a-933b-xxxxxxxxxxxx' with object id 'c512c820-94a7-4b3a-933b-xxxxxxxxxxxx' does not have authorization to perform action 'Microsoft.Network/publicIPAddresses/read' over scope '/subscriptions/480f0bde-1a1c-4b3d-a7a6-xxxxxxxxxxxx/resourceGroups/rg-test/providers/Microsoft.Network' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```
In the above example, the given scope is invalid since the resource-group rg-test is located in another subscription id.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.11
- Cloud provider or hardware configuration: Azure
- OS (e.g: `cat /etc/os-release`): Linux machines

**Comment by feiskyer** [comment]
This is not a supported feature in AKS.

Cloud provider supports network resources in a different subscription by config `networkResourceSubscriptionID` (docs https://kubernetes-sigs.github.io/cloud-provider-azure/install/configs/#host-network-resources-in-different-aad-tenant-and-subscription). However, that is only supported when all network resources are put in the networkResourceSubscriptionID, which is not true for AKS because AKS LoadBalancer would be in the same subscription as AKS cluster itself.
