### ISSUE TITLE
 secrets "kubeadm-certs" is forbidden: User "system:bootstrap:mput08" cannot get resource "secrets" in API group "

### ISSUE THREAD

**Issue by csdnkrue1** [kubernetes/kubernetes#103978]
Hello all,

I'm new in this group and in the kubernets topic.
May be you can help me with the first steps. I got a error if I try to add a additional master to the cluster
For me it looks like a security-problem

It would be nice if you could help me

Let me know If I did any wrong with open of question 

----------------------------------------------------------------
"kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", 

GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", 

GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", 

GitCommit:"7a576bc3935a6b555e33346fd73ad77c925e9e4a", GitTreeState:"clean", BuildDate:"2021-07-15T20:56:38Z", 

GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

"
----------------------------------------------------------------

Command Join a second master

[node5 ~]$ kubeadm join 192.168.0.33:6443 --token mput08.a67ftptgrmv80t7l     --discovery-token-ca-cert-hash sha256:79f87231358600410ed5f16764bd6256d58b1b833aa0e0d5cf57f4606266cc70 --control-plane --certificate-key 86fa3895828decbdbe6445c901641d8e051c3b8dccf02080bacb2fb28c51f8f1

----------------------------------------------------------------
Error
Downloading the certificates in Secret "kubeadm-certs" in the "kube-system" Namespace
error execution phase control-plane-prepare/download-certs: error downloading certs: error downloading the secret: secrets "kubeadm-certs" is forbidden: User "system:bootstrap:mput08" cannot get resource "secrets" in API group "" in the namespace "kube-system"
To see the stack trace of this error execute with --v=5 or higher

----------------------------------------------------------------

Many thanks
Norman

**Comment by neolit123** [comment]
hello, this can happen if for some reason your cluster ended up without the permissions the error message explains.
these permissions are added when you call `kubeadm init --upload-certs ...` or on demand with the `kubeadm init phase upload-certs --upload-certs` phase.

you could then have called `kubeadm join --certificate-key ...` and requested to download the certificates, but the joining node does not have access.

for more support questions please use #kubeadm on k8s slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/remove-kind failing-test
/kind support
/area kubeadm
