### ISSUE TITLE
[PodSecurity] Extra audit annotations

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#103923]
The current alpha implementation doesn't record all the audit annotations that are defined in the KEP
(https://github.com/kubernetes/enhancements/blob/master/keps/sig-auth/2579-psp-replacement/README.md#audit-annotations):

1. [ ] `pod-security.kubernetes.io/enforce-policy = <policy_level>:<resolved_version>` Record which policy was evaluated
   for enforcing mode.
    - ~~Resolved version is the actual version of the policy that was evaluated, so in the case of
      `latest` or future versions, it will be `latest@<version>` where `<version>` is the tagged
      version of the apiserver or webhook (e.g. `latest@v1.22.5-build.8`).~~
    - This annotation is only recorded when a policy is enforced. Specifically, it will not be
      recorded for irrelevant updates or exempt requests.
2. [x] ~~`pod-security.kubernetes.io/audit-policy = <policy_level>:<resolved_version>` Same as `enforce-policy`, but for
   audit mode policies (only included when an audit policy is set).~~
3. [x] ~~`pod-security.kubernetes.io/enforce-violations = <policy violations>` When an enforcing policy is violated, record
   the violations here.~~ _Already captured in response status message._
4. [x] `pod-security.kubernetes.io/audit-violations = <policy violations>` When an audit mode policy is violated, record
   the violations here.
    - [ ] Actual implementation sets `pod-security.kubernetes.io/audit = <policy violations>`. I think we should switch to `audit-violations` to distinguish from the `audit` policy level label.
5. [ ] `pod-security.kubernetes.io/exempt = [user, namespace, runtimeClass]` For exempt requests, record the parameters
   that triggered the exemption here.
6. [x] _(not defined in the KEP)_ `pod-security.kubernetes.io/error = <policy parse error>` When the policy label isn't parsed correctly
    - If we want to keep this, we should probably set it for all errors.

We need to clean up the annotations, decide which of these we want, and update the KEP to match the intent.

**Comment by sftim** [comment]
Aside: is there a list of the defined / well-known audit annotations? I'm imagining something similar to https://kubernetes.io/docs/reference/labels-annotations-taints/.

**Comment by tallclair** [comment]
@sftim good idea. Filed https://github.com/kubernetes/website/issues/29479

**Comment by slaskawi** [comment]
Hey @tallclair

I'd be more than happy to work on this issue!

I can see the following annotations being used ([link](https://github.com/kubernetes/kubernetes/blob/9ce17c87738937c9ea0aae980e48493c678fcd4f/staging/src/k8s.io/pod-security-admission/api/constants.go#L40-L45)):

```
EnforceLevelLabel   = labelPrefix + "enforce"
EnforceVersionLabel = labelPrefix + "enforce-version"
AuditLevelLabel     = labelPrefix + "audit"
AuditVersionLabel   = labelPrefix + "audit-version"
WarnLevelLabel      = labelPrefix + "warn"
WarnVersionLabel    = labelPrefix + "warn-version"
```

Comparing to the KEP, the missing ones are:

- `pod-security.kubernetes.io/enforce-policy` - The code seems to use a combination of `enforce` and `enforce-version` as a replacement of this one.
- `pod-security.kubernetes.io/audit-violations` - Seems to use a combination of `audit` and `audit-version` similarly to the one the above.
- `pod-security.kubernetes.io/exempt` - This one is not present at all. We configure exemptions in `PodSecurityConfiguration` ([link](https://github.com/kubernetes/kubernetes/blob/a3ba921b16805fad3ee5a42ce076661dd7aaa627/staging/src/k8s.io/pod-security-admission/admission/api/types.go#L40)).
- `pod-security.kubernetes.io/error` - Not preset at all.

Please forgive me if my interpretation of the above is not accurate. I'm still a newbie in core Kubernetes world. 

I think we could adjust the KEP on both `enforce-policy` and `audit-violations` to reflect the implementation. Then, we could clarify that the exemptions are handles differently (via `PodSecurityConfiguration`). Finally, I'd suggest removing the `error` annotation.

What do you think, @tallclair

/assign

/cc stlaz s-urbaniak

**Comment by slaskawi** [comment]
My previous comment was totally wrong. Please disregard it. I looked at a wrong piece and messed up labels with audit annotations.

Here's a more accurate version:

* `pod-security.kubernetes.io/enforce-policy` - seems to be missing.
* `pod-security.kubernetes.io/audit-violations` - replaced by `pod-security.kubernetes.io/audit` ([link](https://github.com/kubernetes/kubernetes/blob/32783f75684e0e514b15f79023ba31485be07d9e/staging/src/k8s.io/pod-security-admission/admission/admission.go#L392)).
* `pod-security.kubernetes.io/exempt` - Indeed missing.
* `pod-security.kubernetes.io/error` - This one is present in the code and invoked when a policy can not be parsed ([link](https://github.com/kubernetes/kubernetes/blob/32783f75684e0e514b15f79023ba31485be07d9e/staging/src/k8s.io/pod-security-admission/admission/admission.go#L379)).

I raised a PR with a fix here: https://github.com/kubernetes/enhancements/pull/2978

The only suggestion I'd have is to put a policy version somewhere in the audit annotations. I think this could be helpful for debugging in the future.
