### ISSUE TITLE
Call firewalld instead of using iptables when possible

### ISSUE THREAD

**Issue by eparis** [kubernetes/kubernetes#10398]
Using iptables commands directly on a system managed by firewalld can result in problems. Currently all documentation recommends turning off firewalld before using kubernetes. Instead, like docker, we should send commands to firewalld instead of directly via exec of iptables. This removes the race issues where they both try to operate at the same time and removes problems where our rules are removed for no apparent reason.

**Comment by cgwalters** [comment]
Docker PR: https://github.com/docker/docker/pull/9397

**Comment by thockin** [comment]
This is a fair point for post-1.0

**Comment by dchen1107** [comment]
Subscribe to the issue

**Comment by rhatdan** [comment]
Here is the patch to make this happen in docker.

https://github.com/docker/docker/pull/9397/files

**Comment by danwinship** [comment]
Oops, this should have been closed by #12396

> This removes the race issues where they both try to operate at the same time and removes problems where our rules are removed for no apparent reason.

Neither of these are a problem any more; we use `iptables -w`, so the race condition is solved, and we listen for firewalld restarts, so our rules get re-added if firewalld removes them.
