### ISSUE TITLE
Building Kubernetes using Docker doc does not mention the requirement of buildx cli plugin for Docker

### ISSUE THREAD

**Issue by m-Bilal** [kubernetes/kubernetes#104067]
[Building Kubernetes using Docker Doc](https://github.com/kubernetes/kubernetes/blob/5be21c50c269fc1d28e0bd31ab9dcb572ae7fac5/build/README.md) does not explicitly mention that buildx cli plugin is required for this operation.
If buildx is not present, running `./build/run.sh` gives the following error (which is not very helpful.)
```
+++ Docker build command failed for kube-build:build-06a78ba7ce-5-v1.16.6-1
unknown flag: --load
```
Running the manual command also results in the same error.

I think that the doc should mention that buildx cli plugin should be present for the Docker Image to successfully build, how users can check if buildx is installed, and [how buildx can be installed](https://github.com/docker/buildx/issues/226#issuecomment-765885813) if not already present. (I'm very new to kubernetes community, and I spent 2-3 days trying to figure this out, so this could really help beginners who get  stuck here).

**Comment by neolit123** [comment]
> I think that the doc should mention that buildx cli plugin should be present for the Docker Image to successfully build, how users can check if buildx is installed, and how buildx can be installed if not already present. (I'm very new to kubernetes community, and I spent 2-3 days trying to figure this out, so this could really help beginners who get stuck here).

that seems like a valid improvement.
if someone wants to take this, PRs are welcome.

**Comment by m-Bilal** [comment]
Happy to help here

Docker Buildx installation can be verified by checking if `docker-buildx` file is present in `~/.docker/cli-plugins`.
Buildx can be installed by the following sequence of commands ([source](https://github.com/docker/buildx/issues/226#issuecomment-765885813)):
```
curl --silent -L https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 -o buildx-v0.5.1.linux-amd64
chmod a+x buildx-v0.5.1.linux-amd64
mkdir -p ~/.docker/cli-plugins
mv buildx-v0.5.1.linux-amd64 ~/.docker/cli-plugins/docker-buildx
docker buildx
```
Also, @neolit123 should this issue be left open for community (such as first time contributors) or should I make the changes and raise a PR (if we need it quickly)?

**Comment by neolit123** [comment]
> Also, @neolit123 should this issue be left open for community (such as first time contributors) or should I make the changes and raise a PR (if we need it quickly)?

if you think you can make the change, please go ahead.
thanks
