### ISSUE TITLE
unable to access outside ip address in worker nodes

### ISSUE THREAD

**Issue by Kumar6295** [kubernetes/kubernetes#104036]
Hi,
We are using kubernetes cluster with 1 master and 2 workers.
Create network policy for engress and ingress for all the pods.
We are able to ping and nslookup in master node pods it is working but we are try sample in worker nodes pods it is not working.
Need to add any separate policy for worker nodes?

**Comment by neolit123** [comment]
hi, please try the support channels first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

we try to keep the issue trackers for bugs/features only.

/kind support
/close
