### ISSUE TITLE
Unable to access outside ip with domain name , when it is not in /etc/hosts file of pods

### ISSUE THREAD

**Issue by Kumar6295** [kubernetes/kubernetes#104035]
Hi,
We are using kubernetes cluster with 1 master node and 2 worker nodes.
We deployed pods in master node and enabled engress and ingress for pods and able ping particular domain name like below

ping  identity.ns.ai 
PING identity.ns.ai (46.xx.xx.188): 56 data bytes
64 bytes from 46.xx.xx.188: seq=0 ttl=50 time=30.160 ms
64 bytes from 46.xx.xx.188: seq=1 ttl=50 time=28.350 ms
64 bytes from 46.xx.xx.188: seq=2 ttl=50 time=31.248 ms
Ping is working fine but while using in program , it is not working.

After that added  46.xx.xx.188 identity.ns.ai in /etc/hosts then it is working. may we know what is the issue.

**Comment by getpawarful** [comment]
triage/accepted

**Comment by getpawarful** [comment]
Looks like a DNS issue to me, please find this for reference https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

**Comment by Kumar6295** [comment]
Thanks , we will look into

**Comment by neolit123** [comment]
please try the support channels for help / questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
