### ISSUE TITLE
Best approach to write data to /sys/block/mdX/md/sync_action as its failing

### ISSUE THREAD

**Issue by mukul-seagate11** [kubernetes/kubernetes#104026]
<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!

#### What happened:
Best approach to write data to /sys/block/mdX/md/sync_action as its failing

#### What you expected to happen:
To define a spec where data can be written in /sys/block/mdX/md/sync_action to scrub the drives

#### Environment:
- Cloud provider or hardware configuration: hardware

**Comment by ehashman** [comment]
/sig storage

Please add more information to this bug report. How is your action failing? What version of Kubernetes are you using?

**Comment by mukul-seagate11** [comment]
I want to write some data from container to host file having below permission without running container in privileged mode,
 
[root@k8s]# ls -l /sys/class/block/md0/md/sync_action
-rw-r--r-- 1 root root 4096 Jul 18 01:00 /sys/class/block/md0/md/sync_action

**Comment by mukul-seagate11** [comment]
[root@hpe04-m09 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", 18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", 15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by mukul-seagate11** [comment]
[root@hpe04-m09 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", 18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.9", 15T20:56:38Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Kartik494** [comment]
@mukul-seagate11 Could You provide some steps on How you implement these steps for write data to host file from container, That would provide more clarification on this.

Thanks
