### ISSUE TITLE
Revert bump of DynamicKubeletConfig metrics deprecation to 1.23

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#104041]
This shipped in 1.22 as deprecated in 1.22. As a hacky fix to unbreak tests on 1.23 dev, I bumped the deprecation policy one release: https://github.com/kubernetes/kubernetes/pull/103980#issuecomment-888510879

We will need to revert that before 1.23 ships and figure out a better solution.

/kind cleanup
/milestone v1.23
/sig node

**Comment by jyz0309** [comment]
I want to try it. Can I take this issue? @ehashman

**Comment by ehashman** [comment]
I have explained how to fix this on @kerthcet's PR: https://github.com/kubernetes/kubernetes/pull/104075#issuecomment-891208939

**Comment by ehashman** [comment]
/reopen

reverted in https://github.com/kubernetes/kubernetes/pull/104202 as fix did not work

**Comment by jyotimahapatra** [comment]
Hi, 👋 Im the bug triage shadow. Since we're in 1.23 milestone code freeze, could we move this issue to milestone 1.24?

**Comment by ehashman** [comment]
> Hi, wave Im the bug triage shadow. Since we're in 1.23 milestone code freeze, could we move this issue to milestone 1.24?

@jyotimahapatra this is critical for 1.23 and I think it just got forgotten... we need to get this fixed before test freeze
