### ISSUE TITLE
Is there any way to convert my k8s CRD into OpenApi json ?

### ISSUE THREAD

**Issue by ravipwaghmare** [kubernetes/kubernetes#104001]
This is my Sample CRD and I want to generate OpenAPI JSON from it.
Is there any way to do it automatically?
---
            apiVersion: apiextensions.k8s.io/v1beta1
            kind: CustomResourceDefinition
            metadata:
              annotations:
                controller-gen.kubebuilder.io/version: v0.2.4
              creationTimestamp: null
              name: sampleapps.app.mydomain
            spec:
              group: app.mydomain
              names:
                kind: SampleApp
                listKind: SampleAppList
                plural: sampleapps
                singular: sampleapp
              scope: Namespaced
              validation:
                openAPIV3Schema:
                  description: SampleApp is the Schema for the sampleapps API
                  properties:
                    apiVersion:
                      description: 'APIVersion defines the versioned schema of this representation
                        of an object. Servers should convert recognized schemas to the latest
                        internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
                      type: string
                    kind:
                      description: 'Kind is a string value representing the REST resource this
                        object represents. Servers may infer this from the endpoint the client
                        submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
                      type: string
                    metadata:
                      type: object
                    spec:
                      description: SampleAppSpec defines the desired state of SampleApp
                      properties:
                        foo:
                          description: Foo is an example field of SampleApp. Edit SampleApp_types.go
                            to remove/update
                          type: string
                      type: object
                    status:
                      description: SampleAppStatus defines the observed state of SampleApp
                      type: object
                  type: object
              version: v1
              versions:
              - name: v1
                served: true
                storage: true
            status:
              acceptedNames:
                kind: ""
                plural: ""
              conditions: []
              storedVersions: []

**Comment by neolit123** [comment]
if supported might be good to document this at the k8s.io website.

/kind documentation
/sig api-machinery

**Comment by Jefftree** [comment]
if the CRD is already applied to the cluster, kubectl supports retrieving the CRD in either yaml or json format. (Eg: `kubectl get crd <crd-name> -o json`). CRDs are also aggregated and their schema published at the `/openapi/v2` endpoint. For purposes of documentation I think there are a couple of third party tools for generating the JSON, but I don't recall anything built in for CRDs.
