### ISSUE TITLE
Migrate Json logging format to use zapr

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#104097]
#### What would you like to be added:

/cleanup
[Structured Logging KEP](https://github.com/kubernetes/enhancements/issues/1602) proposed to introduce alternative JSON logging format, that is injected into klog by providing a [logr.Logger](https://github.com/go-logr/logr) interface implementation. 

When Json format was originally implemented we decided to write our own logr.Logger implementation to speed up work and skip taking a dependency on implementation that might not be matching specification given in KEP. 

Our implementation: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/json/json.go

As we added more testing and logr.Logger released 1.0.0, it doesn't make sense to maintain this code as it's very similar to existing logr.Logger implementation called zapr. https://github.com/go-logr/zapr

Not to person that will work on it:
We can either wait for klog and k/k to switch to logr 1.0.0 or migrate now when we are still on 0.4.0. I prefer to do it earier as it will reduce work needed to migrate to 1.0.0.

#### Why is this needed:
Reduce maintanance cost of library and consolidate work on JSON logr implementation.
It should also help when transitioning to logr 1.0.0

/cc @kubernetes/wg-structured-logging-members 
/wg structured-logging
/sig instrumentation
/priority important-soon
/cc @timhockin @pohly

**Comment by pohly** [comment]
I can have a look at this soonish if no-one else volunteers.

**Comment by yangjunmyfm192085** [comment]
My opinion: migrate now, I prefer to migrate as soon as possible to verify the implementation of zapr.
I'll take a look it, what about @yuzhiquan's suggestion?

**Comment by pohly** [comment]
We definitely should start now.

I would do this together with updating klog to the (currently unreleased) code which uses logr 1.0, otherwise we just end up with another dependency on an obsolete external package (zapr v0.4.0) with known bugs (V handling apparently was broken and was fixed as part of the API change in https://github.com/go-logr/zapr/commit/7bc31c25c5f9c6dec785dd1f96b1ad49139d622a#diff-72a6c66d907dff1098b855ad97d9caabebf8e240b84ea98e8740213594297d29).

**Comment by pohly** [comment]
@yangjunmyfm192085 are you working on this?

I had a quick look and updating klog, logr and using zapr is straight-forward, except for one issue: the json.go fork of of zapr logs verbosity of a message with a "v" field. go-logr/zapr doesn't do that.

I now wonder whether this should be treated as a Kubernetes specific extension or get added to go-logr/zapr. Thoughts?

**Comment by pohly** [comment]
Let me share what I have right now: https://github.com/kubernetes/kubernetes/pull/104103

**Comment by yuzhiquan** [comment]
> My opinion: migrate now, I prefer to migrate as soon as possible to verify the implementation of zapr.
> I'll take a look it, what about @yuzhiquan's suggestion? Should we start this now?

IMO, it's right time to do this, and plz ping me, if need any help.

**Comment by yangjunmyfm192085** [comment]
> @yangjunmyfm192085 are you working on this?
> 
> I had a quick look and updating klog, logr and using zapr is straight-forward, except for one issue: the json.go fork of of zapr logs verbosity of a message with a "v" field. go-logr/zapr doesn't do that.
> 
> I now wonder whether this should be treated as a Kubernetes specific extension or get added to go-logr/zapr. Thoughts?

I am not working on this now, I think you can continue worke on it, any help or need can ping me too.

**Comment by yangjunmyfm192085** [comment]
> I now wonder whether this should be treated as a Kubernetes specific extension or get added to go-logr/zapr. Thoughts?

/cc @yuzhiquan

**Comment by yuzhiquan** [comment]
> @yangjunmyfm192085 are you working on this?
> 
> I had a quick look and updating klog, logr and using zapr is straight-forward, except for one issue: the json.go fork of of zapr logs verbosity of a message with a "v" field. go-logr/zapr doesn't do that.
> 
> I now wonder whether this should be treated as a Kubernetes specific extension or get added to go-logr/zapr. Thoughts?

This "v" field is follow design in https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1602-structured-logging,  specific for kubernetes, But if zapr set this "v " as default field, may be more available.
/cc @serathius @thockin

**Comment by thockin** [comment]
zapr takes a `zap.Logger` which can be set up in a lot of different configurations.  In the zapr example it logs `"level":"info"`, for example.

If we want to add an optional `v` to zapr itself, I don't particularly object, but we'd need a new `NewWithOptions()` function, carrying an optional "LogNumericV" flag (or something like that).  PRs welcome - glogr has an Options variant, so you can sort of clone that.

Or you can configure the zap.Logger `EncoderConfig.LevelKey` but that gives you "info" and "debug" not "1" or "2".

**Comment by pohly** [comment]
While looking at the current json.go, I noticed that errors also have a "v" field. In the test it is zero:
https://github.com/kubernetes/kubernetes/blob/8c64743d73f206bf633828a7fa1dd014ce153209/staging/src/k8s.io/component-base/logs/json/json_test.go#L150

However, it's implemented the same way as Info, so `logger.V(5).Error` records "v=5". That doesn't make sense to me.

My suggestion is to always log errors with "v=-1", to distinguish them from info messages with "v=0".

**Comment by pohly** [comment]
And perhaps "v=-2" for panics?

**Comment by pohly** [comment]
Another question about json.go: should the log level of a component influence which messages get logged?

The constructor doesn't take a parameter to specify the component's log level: https://github.com/kubernetes/kubernetes/blob/5dd4d3c7f7f5e83a2a62190332eaa6a3c916f955/staging/src/k8s.io/component-base/logs/json/json.go#L42-L48

And the test just checks that messages at all levels are enabled:

https://github.com/kubernetes/kubernetes/blob/5dd4d3c7f7f5e83a2a62190332eaa6a3c916f955/staging/src/k8s.io/component-base/logs/json/json_test.go#L97-L105

That's different from zapr where the level of the message is checked against the threshold configured in the zap logger.


The zap logger

**Comment by pohly** [comment]
PR for zapr is here: https://github.com/go-logr/zapr/pull/37

With that change, https://github.com/kubernetes/kubernetes/pull/104103 passes the JSON unit tests with some (minor) modifications.

**Comment by pohly** [comment]
> Another question about json.go: should the log level of a component influence which messages get logged?

Kubernetes handles that in klog: klog checks the component log level, then calls the logger only if the message is to be printed.
