### ISSUE TITLE
All CRIO node e2e jobs failing

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#104096]
#### Which jobs are failing:
ci-crio-cgroupv1-node-e2e-conformance
ci-crio-cgroupv1-node-e2e-features
ci-crio-cgroupv2-node-e2e-conformance
pull-kubernetes-node-crio-e2e 

etc. 

#### Which test(s) are failing:
All tests 

#### Since when has it been failing:
After https://github.com/kubernetes/kubernetes/pull/104047 is merged. 

#### Testgrid link:
[prow dash for crio](https://prow.k8s.io/?job=*crio*)

#### Reason for failure:
Unknown

**Comment by harche** [comment]
cc @ehashman

**Comment by saschagrunert** [comment]
Fix is incoming in https://github.com/kubernetes/test-infra/pull/23110
