### ISSUE TITLE
Container probes support hooks?

### ISSUE THREAD

**Issue by jacky68147527** [kubernetes/kubernetes#104023]
I hope to take more actions based on the probes results, such as synchronize permissions, notify services outside the kubernetes cluster, and so on......

**Comment by kerthcet** [comment]
`exec command` can not meet your needs?

**Comment by kerthcet** [comment]
I do think probes should not process with heavy logic, which may lead to unexpected phenomenon.

**Comment by ehashman** [comment]
Kubernetes SIG Node does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/) or Slack.

/kind support
/close
