### ISSUE TITLE
[Discussion] should Pods be placed in backoff when internal errors happen?

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#104013]
Today, when a Pod fails to schedule, we put it in the unschedulable queue regardless of the reason why it failed.

Pods only exit the unschedulable queue for 2 reasons:
- An external event happens (pod deleted, node created, etc)
- The flush (1 min by default)

In some cases, the errors could be transient, and the Pod should not be penalized by landing in the unschedulable queue.
The most obvious reasons are failures in the API server, for example, when querying PVCs (and the error is not NotFound) or when binding.

Where do we produce errors that are not Unschedulable(AndUnresolved) status? A quick survey:
- API errors:
  - volume binding
  - pod binding
- Calling listers (PVC, PodDisruptionBudget, Namespace)
- Calling Snapshot methods, but they always return nil.
- Checking for nodeInfo.Node() != nil, which shouldn't happen today.
- Parse errors (should be unreacheable, as they are verified in PreFilter, returning UnschedulableAndUnresolvable)
- Missing plugin state (should be unreacheable, unless failed to enable PreFilter/PreScore for the plugin)

I think we can remove the errors from Snapshot methods and any other methods we see never return errors. The API and lister errors should be transient. The missing plugin state shouldn't be a problem.
Then, we can implement the simple logic of putting the pod in unschedulable queue if the status is Unschedulabe(AndUnresolvable), backoff otherwise.

/sig scheduling

**Comment by alculquicondor** [comment]
Might we wise to solve this along with the refactorings in #103853

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei

**Comment by Huang-Wei** [comment]
SGTM. Prior to the implementation, need to pre-refactor the plugins to ensure (1) transient failures are returned as Error status and (2) non-transient failures are categorized as Unschedulable(AndUnresolvable) properly.

**Comment by ahg-g** [comment]
I don't think we should do this for "not found" errors, those should continue to return unschedulable (events will move the pod out of unschedulable when the missing resource becomes available).

While in theory it sounds plausible to put the pod directly in backoff upon transient errors, do we have evidence that this is actually a problem? My concern is that as we continue to fine tune error classification, it will become easier to misclassify errors, which may lead to other problems.

**Comment by alculquicondor** [comment]
My proposal is that any error (that is **not** NotFound) is treated as transient, thus puts the pod back in backoff. But that should be done after a more detailed survey than the one I already did.

I do not have evidence of the current error handling (put in unschedulable) being a problem. Perhaps it would show in the metric `pod_scheduling_duration_seconds` for the existing performance and scalability tests.

**Comment by alculquicondor** [comment]
@Jerry-Ge maybe you would be interested in taking a stab at this
