### ISSUE TITLE
apiserver_admission_controller_admission_duration_seconds_bucket is very large in 1.22

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#104008]
#### What happened:
Running a 1.22 beta and the standard e2e test suite, we found that apiserver_admission_controller_admission_duration_seconds_bucket grew very large, very quickly.  Large enough to lead to instability as our monitoring stack repeatedly read them.

https://github.com/kubernetes/kubernetes/pull/101208#discussion_r679200100 looks like a prime candidate.  We are attempting a revert locally to see if it improves the situation.

#### What you expected to happen:
While we could technically work around this by passing non-default flags to the kube-apiserver, the defaults should be safe for use by non-experts.

#### Environment:
- Kubernetes version -- 1.22 beta-something pretty close to now-ish
- an openshift branch we're trying to integrate

**Comment by ehashman** [comment]
@deads2k do we have a k/k revert open yet for testing?

**Comment by s-urbaniak** [comment]
@ehashman I submitted https://github.com/kubernetes/kubernetes/pull/104033: let me know if this looks good to you.
