### ISSUE TITLE
Add metrics to apiserver tracking the service IP allocator

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#104093]
#### What would you like to be added:
Add metrics to apiserver tracking the service IP allocator - around how many IP addresses are used(allocated) vs available, and/or if there were any errors allocating service IPs to a service.

#### Why is this needed:
We want to track if we are approaching the limit of the ServiceClusterIPRange, which is a fixed CIDR and difficult to change. Currently while we can approximate the usage looking at services in the cluster, it is not coming from the source allocator which is within the apiserver.

Similar metrics are currently available for the node's ipam allocatior: https://github.com/kubernetes/kubernetes/pull/90288

/area apiserver
/sig instrumentation
/sig network

**Comment by aojea** [comment]
/triage accepted
/assign

> around how many IP addresses are used(allocated) vs available, 

I see something like this, gauges for `usage_cluster_ip` and `available_cluster_ip`

> and/or if there were any errors allocating service IPs to a service.

can you expand on this? a counter incremented each time an IP allocation fails?

**Comment by adammw** [comment]
> can you expand on this? a counter incremented each time an IP allocation fails?

that is one option. for contrast the nodeipam metric has an 'allocation_tries_per_request' metric - i was imagining something similar to an 'attempts', but with a success:true/false tag/facet so we could compare how often allocations are attempted/how often they fail. I will defer to the experts here as I'm not sure what the status quo for reporting attempts/failures are. 

I'm not sure if there's any code paths that would cause allocation failures other than usage > total (or available <= 0) - but having them separated out like that would be handy in that scenario. (maybe etcd internal allocation is corrupt? or context deadline exceeded)
