### ISSUE TITLE
CronJob controller V2: breaks "@every [interval]" jobs

### ISSUE THREAD

**Issue by bootc** [kubernetes/kubernetes#104012]
#### What happened:

In K8s 1.21, CronJobs with a `.spec.schedule` with a value containing something like `@every 6h` are inconsistently scheduled, and the CronJob's `.status.lastScheduleTime` field does not match reality.

For example, I have a CronJob configured as above. It runs every 6 hours as long as the kube-controller-manager pod isn't restarted, but the `.status.lastScheduleTime` is currently some 45 minutes _before_ the Job's `.spec.metadata.creationTimestamp`. The kube-controller-manager's logs correctly show the job is created corresponding with the Job's creationTimestamp, and the CronJob's lastScheduleTime appears to be updated at the same time, but with a time stamp in the past.

In K8s 1.20 the behaviour was as expected, and the lastScheduleTime closely (possibly even exactly) matched the Job's creationTimestamp.

#### What you expected to happen:

Jobs created from CronJobs should be consistently created every 6 hours (for `@every 6h`), and the `.status.lastScheduleTime` should closely follow the last Job's `.spec.metadata.creationTimestamp` field.

#### How to reproduce it (as minimally and precisely as possible):

I see consistent behaviour on multiple clusters running 1.21 (in AWS EKS and built using Rancher RKE2), but I haven't tried with timestamps shorter than 6 hours. This is easily reproducible with `@every 6h` timestamps, however.

#### Anything else we need to know?:

The `@every` syntax is not documented in the Kubernetes [CronJob documentation](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/), though that mostly points at [Wikipedia](https://en.wikipedia.org/wiki/Cron) for the schedule format. However, the `@every` syntax works and is documented in [`vendor/github.com/robfig/cron/v3/doc.go`](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/robfig/cron/v3/doc.go) and at https://pkg.go.dev/github.com/robfig/cron.

The implementation for `@every` is at: https://github.com/kubernetes/kubernetes/blob/fffaadc01331cca57cafa0fc066a2a3eec23acb8/vendor/github.com/robfig/cron/v3/parser.go#L424-L431

#### Environment:
- Kubernetes version (use `kubectl version`):
  - ```version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+rke2r1", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-21T16:49:24Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}```
  - ```version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T00:59:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}```

- Cloud provider or hardware configuration: Rancher RKE2 _and_ AWS EKS
- OS (e.g: `cat /etc/os-release`): Debian Bullseye / Amazon Linux 2
- Kernel (e.g. `uname -a`): 5.10.0-8-amd64 / 5.4.129-63.229.amzn2.x86_64
- Install tools: Rancher RKE2 / n/a
- Network plugin and version (if this is a network-related bug): n/a

**Comment by cndoit18** [comment]
Hello, I tend to be influenced by the timezone of the control plane. can you provide more information?

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by bootc** [comment]
My `kube-controller-manager` pods run with TZ=UTC. My local time zone is Europe/London which is currently 1h different, but this shouldn't be relevant as all my control-plane components run on UTC time.

**Comment by RyanAoh** [comment]
I have reproduced this by the following case:
1. Create a cronjob with schedule "@every 3m"
2. After 2 mininutes, update the schedule to "@every 5m"
3. Wait to the job created by cronjob crontroller.

Then, you can see that the `.status.lastScheduleTime` will be always 3 minutes before the Job's `.spec.metadata.creationTimestamp`.

**Comment by sftim** [comment]
> The `@every` syntax is not documented in the Kubernetes CronJob documentation, though that mostly points at Wikipedia for the schedule format. However, the @every syntax works and is documented in vendor/github.com/robfig/cron/v3/doc.go and at https://pkg.go.dev/github.com/robfig/cron.

Since this was filed, the documentation now refers readers to the robfig cron package format documentation.

**Comment by d-honeybadger** [comment]
Was able to reproduce incorrect scheduling by restarting kube-controller-manager:
- spun up a minikube `minikube start --kubernetes-version=v1.22.3`
- created a cronjob with `@every 3m` schedule, which initally was scheduled as expected
- ~1min after the last job ran, restarted kube-controller-manager (by removing the static pod manifest from /etc/kubernetes/manifests and then putting it back)
- the next job was scheduled ~3min _after the kube-controller-manager restart_, instead of _after the last job scheduled time_; which resulted in a gap of ~4min between the jobs
Note that `.status.lastScheduleTime` also got messed up after the restart - if got offset relative to the actual time the last run was scheduled.

I then tested the same scenario with kube-controller-manager restart in k8s v1.20.3, and it followed `@every 3m` schedule correctly even after kube-controller-manager restart, so, this appears to be a regression.
