### ISSUE TITLE
CRD validation does not immediately reject unknown fields

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#104090]
#### What happened:
For gateway-api we have a [simple verification test](https://github.com/kubernetes-sigs/gateway-api/blob/master/hack/verify-examples-kind.sh) that essentially installs our CRDs and then installs all our examples. It's become somewhat flaky recently, and it appears this could be related. Recently a PR added a field that was unknown/undefined in the API Version of the example. This was not caught by the test described above.

Digging further, it appears that unknown fields are let through for the first few seconds after a CRD is created. After that CRD validation appears to kick in as expected. For now, adding a 3 second delay between installing the CRDs and examples is sufficient to get our test to catch this again, but of course a better upstream fix would be ideal.

#### What you expected to happen:
Applying a custom resource with fields that aren't defined by the CRD to fail.

#### How to reproduce it (as minimally and precisely as possible):
```
kind create cluster --image kindest/node:v1.21.1 
git clone git@github.com:kubernetes-sigs/gateway-api.git
cd gateway-api
git checkout c4a3a3e52e0781aac3d6b8b8f90c3cffa3552ba1
kubectl apply -f config/crd/bases
kubectl apply --recursive -f examples
```

To recreate this, the final two commands need to be run without a pause. There is an invalid field (method) in `examples/basic-http.yaml` that should cause the final command to fail with a message like this:

```
error: error validating "examples/basic-http.yaml": error validating data: ValidationError(HTTPRoute.spec.rules[1].matches[0]): unknown field "method" in io.x-k8s.networking.v1alpha1.HTTPRoute.spec.rules.matches; if you choose to ignore these errors, turn validation off with --validate=false
```

If we uninstall the CRDs (`kubectl delete -f config/crd/bases`) and then run the two kubectl commands above again with a ~3s pause between them, it will consistently catch this and the apply will fail. On the other hand, when these commands are run immediately after each other, the `kubectl apply` consistently passes, allowing the invalid field through.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-06-22T04:47:11Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Kind
- Install tools: Kind

/sig api-machinery
/cc @apelisse @sttts

**Comment by apelisse** [comment]
Actually, @Jefftree and @jpbetz might know something about that too

**Comment by liggitt** [comment]
I suspect the rejection you are seeing is happening client side. The server does not reject unknown fields (it either drops them, or preserves them if x-kubernetes-preserve-unknown-fields is set). 

If kubectl creates the object when the endpoint is registered and the endpoint is accepting create requests, but before the server openapi schema is updated (or there is a race with kubectl checking for the updated openapi schema), kubectl can submit the object anyway. 

Once you start getting error messages about the unknown fields, does it offer passing "--validate=false" as an option? If so, that is a client-side error, not something enforced server side.

**Comment by robscott** [comment]
Woops, sorry I missed adding the actual error message I was seeing. You're completely right @liggitt, I was seeing/expecting the client-side validation here. Somehow I'd thought that there was more to it than that. Is there any server side validation that prevents unknown CRD fields from being persisted?

**Comment by liggitt** [comment]
setting `preserveUnknownFields: false` will drop the unknown fields instead of persisting them, but there is not a "reject request with unknown fields" option

**Comment by kevindelgado** [comment]
FWIW, I am working on a KEP to tackle server side unknown field validation. These are some [initial notes](https://docs.google.com/document/d/1MmEkA2xEr_vOJ9SrpWu92rAzvaxEY47PHeRKcfO86mc/edit?usp=sharing) that were presented at the last sig/api-machinery meeting. I received the go ahead to formalize this into a full KEP and can link to this discussion once that kep is submitted.

**Comment by luxas** [comment]
cc @luxas
