### ISSUE TITLE
[Failing Test] pull-kubernetes-e2e-gce-100-performance jobs failing

### ISSUE THREAD

**Issue by boenn** [kubernetes/kubernetes#104094]
#### Which jobs are failing:

The two job failure scenarios are similar
pull-kubernetes-e2e-gce-ubuntu-containerd
pull-kubernetes-e2e-gce-100-performance

#### Which test(s) are failing:

[pull-kubernetes-e2e-gce-ubuntu-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103934/pull-kubernetes-e2e-gce-ubuntu-containerd/1422402493962260480/)
[pull-kubernetes-e2e-gce-100-performance](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/103934/pull-kubernetes-e2e-gce-100-performance/1422402494792732672)

#### Since when has it been failing:

pull-kubernetes-e2e-gce-ubuntu-containerd failures started 2021-08-03 03:42:41 +0000 UTC
pull-kubernetes-e2e-gce-100-performance failures started 2021-08-03 03:44:29 +0000 UTC

#### Reason for failure:

Cluster creation script fails

```
error during ./hack/e2e-internal/e2e-up.sh: exit status 2
```

#### Anything else we need to know:
Somewhat similar to this: https://github.com/kubernetes/kubernetes/issues/100978

**Comment by neolit123** [comment]
> pull-kubernetes-e2e-gce-100-performance

/sig scalability

**Comment by neolit123** [comment]
pull* jobs are persubmits that run before a PR merges.
i think this qualifies more as `/kind flake` i.e. it could be temporary or due to the contents of specific PRs:

test-grid link:
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-gce-100-performance

**Comment by boenn** [comment]
/kind flake

Here are some logs, The two jobs are almost the same error.

```
WARNING: You have selected a disk size of under [200GB]. This may result in poor I/O performance. For more information, see: https://developers.google.com/compute/docs/disks#performance.

I0803 06:40:52.918] Group is stable
W0803 06:40:57.792] INSTANCE_GROUPS=e2e-ec8f18d460-a7d53-minion-group
W0803 06:40:57.792] NODE_NAMES=e2e-ec8f18d460-a7d53-minion-group-46qq e2e-ec8f18d460-a7d53-minion-group-8t5b e2e-ec8f18d460-a7d53-minion-group-g9l0
W0803 06:40:57.792] Trying to find master named 'e2e-ec8f18d460-a7d53-master'
W0803 06:40:57.792] Looking for address 'e2e-ec8f18d460-a7d53-master-ip'
W0803 06:40:58.891] Using master: e2e-ec8f18d460-a7d53-master (external IP: 34.127.55.162; internal IP: (not set))
I0803 06:40:58.991] Waiting up to 300 seconds for cluster initialization.
I0803 06:40:58.992] 
I0803 06:40:58.992]   This will continually check to see if the API for kubernetes is reachable.
I0803 06:40:58.992]   This may time out if there was some uncaught error during start up.
I0803 06:40:58.992] 
I0803 06:46:00.021] ...................................................................................................................................................Checking for custom logdump instances, if any
I0803 06:46:00.026] ----------------------------------------------------------------------------------------------------
I0803 06:46:00.026] k/k version of the log-dump.sh script is deprecated!
I0803 06:46:00.026] Please migrate your test job to use test-infra's repo version of log-dump.sh!
I0803 06:46:00.026] Migration steps can be found in the readme file.
I0803 06:46:00.026] ----------------------------------------------------------------------------------------------------
I0803 06:46:00.027] Sourcing kube-util.sh
I0803 06:46:00.076] Detecting project
I0803 06:46:00.077] Project: k8s-infra-e2e-boskos-002
I0803 06:46:00.077] Network Project: k8s-infra-e2e-boskos-002
I0803 06:46:00.077] Zone: us-west1-b
I0803 06:46:00.085] Dumping logs from master locally to '/workspace/_artifacts'
W0803 06:46:00.186] Cluster failed to initialize within 300 seconds.
W0803 06:46:00.186] Last output from querying API server follows:
W0803 06:46:00.186] -----------------------------------------------------
W0803 06:46:00.186] * Expire in 0 ms for 6 (transfer 0x55b3fa6aafb0)
W0803 06:46:00.186] * Expire in 5000 ms for 8 (transfer 0x55b3fa6aafb0)
W0803 06:46:00.186] *   Trying 34.127.55.162...
W0803 06:46:00.186] * TCP_NODELAY set
W0803 06:46:00.187] * Expire in 200 ms for 4 (transfer 0x55b3fa6aafb0)
W0803 06:46:00.187] * connect to 34.127.55.162 port 443 failed: Connection refused
W0803 06:46:00.187] * Failed to connect to 34.127.55.162 port 443: Connection refused
W0803 06:46:00.187] * Closing connection 0
W0803 06:46:00.187] curl: (7) Failed to connect to 34.127.55.162 port 443: Connection refused
W0803 06:46:00.187] -----------------------------------------------------
W0803 06:46:00.187] 2021/08/03 06:46:00 process.go:155: Step './hack/e2e-internal/e2e-up.sh' finished in 7m56.582961135s
W0803 06:46:00.188] 2021/08/03 06:46:00 e2e.go:544: Dumping logs locally to: /workspace/_artifacts
```

**Comment by boenn** [comment]
I checked some component logs at https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103934/pull-kubernetes-e2e-gce-ubuntu-containerd/1422402493962260480/artifacts/e2e-15f8fe8240-a7d53-minion-group-cc4n/kubelet.log shows **Failed to connect to apiserver**. But the log of apiserver is empty.

I also checked https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/103934/pull-kubernetes-e2e-gce-ubuntu-containerd/1422402493962260480/artifacts/e2e-15f8fe8240-a7d53-master/kube-master-configuration.log shows:
```
The connection to the server localhost:443 was refused - did you specify the right host or port
```

**Comment by dims** [comment]
we've had a few green runs in both now ... So let's call them flaky :)

![image](https://user-images.githubusercontent.com/23304/128093296-e1cc5af1-b88e-4ecf-bc63-8bcfdcd89e26.png)
![image](https://user-images.githubusercontent.com/23304/128093328-61d7092c-56fb-4cc4-a461-14075de6756d.png)

**Comment by boenn** [comment]
fine.. I will conduct further inspections :)
