### ISSUE TITLE
Default Scheduler Improvement: take node's allocatable pod ip into consideration

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/kubernetes#104091]
#### What would you like to be added:

Adding a scheduling condition in default scheduler to take allocatable IP from node's `.spec.PodCIDR` into consideration.

related KEP PR in sig-scheduling: [PR#219](https://github.com/kubernetes-sigs/scheduler-plugins/pull/219)

#### Why is this needed:
For now, the default scheduler only takes .status.Allocatable["pods"] into consideration when scheduling. If the density of pods in a node is relatively high, the node might not have sufficient allocatable Pod IPs to allocate.

@Huang-Wei

**Comment by jyz0309** [comment]
Can I try this issue if it's accepted? I am interested in this one~
/assign
If I can't, just cancel my assign😝

**Comment by lianghao208** [comment]
For now, it's just an idea to bring up the discussion. You can learn more details in [PR#219](https://github.com/kubernetes-sigs/scheduler-plugins/pull/219)
I have already worked on fixing this this issue though. If you have any suggestions, we can discuss on this issue. Thanks for the reply!
@jyz0309

**Comment by Huang-Wei** [comment]
A couple of questions, which may need input from sig-node / sig-network:

1. Is a node's `.spec.PodCIDR` always be honored when allocating an IP on CNI side?
2. When IPv4/IPv6 dual-stack is enabled, can the pod **_always_** get an (IPv6) IP regardless of the IPv4 CIDR's exhaustion?
3. If we put IPv6 aside, is `min(ip # of .spec.PodCIDR, .status.Allocatable["pods"])` an accurate formula to calculate the maximum pods we can allocate to a node?
