### ISSUE TITLE
Pod restarting depends on one of containers status

### ISSUE THREAD

**Issue by Lovnx** [kubernetes/kubernetes#104156]
There is a pod which contains 2 containers, We hope restart pod when one of containers shutdown, how to achieve this?

**Comment by mcbenjemaa** [comment]
/kind support
/sig node

Define LivenessProbe for each container, the kubelet should restart the pod if one of your containers has failed.
[configure-liveness-readiness-probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes)

- Please use slack for those kind of support request! [k8s-slack](https://github.com/kubernetes/community/tree/master/communication#slack)

**Comment by mcbenjemaa** [comment]
/kind support
/sig node

Define LivenessProbe for each container, the kubelet should restart the pod if one of your containers has failed.
[configure-liveness-readiness-probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes)

- Please use slack for those kind of support request! [k8s-slack](https://github.com/kubernetes/community/tree/master/communication#slack)

**Comment by Lovnx** [comment]
could you show me an example? by using tcp probe.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
