### ISSUE TITLE
kubectl - Error from server (Forbidden): users “xxx@xxx.it” is forbidden: User “system:serviceaccount:gke-connect:connect-agent-sa”

### ISSUE THREAD

**Issue by ciuffoly** [kubernetes/kubernetes#104127]
I have this strange situation, how I can solve this problem ?

`ubuntu@anth-mgt-wksadmin:~$ kubectl get nodes
error: the server doesn't have a resource type "nodes"

ubuntu@anth-mgt-wksadmin:~$ kubectl cluster-info
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
error: the server doesn't have a resource type "services"

ubuntu@anth-mgt-wksadmin:~$ kubectl cluster-info dump
Error from server (Forbidden): users "xxx@xxx.it" is forbidden: User system:serviceaccount:gke-connect:connect-agent-sa" cannot impersonate resource "users" in API group "" at the cluster scope`

I think that the problem has been generated by this following apply searching a way to connect the admin cluster to Cloud Console but how to rollback ?

`USER_ACCOUNT=xxx@xxx.it
cat <<EOF > /tmp/impersonate.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - ${USER_ACCOUNT}
  resources:
  - users
  verbs:
 - impersonate
 - --
 - apiVersion: rbac.authorization.k8s.io/v1
 - kind: ClusterRoleBinding
metadata:
  name: gateway-impersonate
roleRef:
  kind: ClusterRole
  name: gateway-impersonate
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: connect-agent-sa
  namespace: gke-connect
EOF
# Apply impersonation policy to the cluster.
kubectl apply -f `/tmp/impersonate.yaml`

It is possible we have add gke-connect API after this operation or before I don't remember.

**Comment by enj** [comment]
Please reach out to GKE support for configuration issues related to their gateway agent.

You likely have a type somewhere in your RBAC configuration.

/close

**Comment by enj** [comment]
Support info: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
