### ISSUE TITLE
[Flaking test] DATA RACE in TestVolumeUnmountAndDetachControllerEnabled

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#104173]
#### Which jobs are failing:
pull-kubernetes-unit

#### Which test(s) are failing:
k8s.io/kubernetes/pkg/kubelet: TestVolumeUnmountAndDetachControllerEnabled

#### Since when has it been failing:
I just noticed it today, 5 Aug 2021.

#### Testgrid link:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104002/pull-kubernetes-unit/1423295539780259840

#### Reason for failure:
data race between two goroutines

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-node-bugs

**Comment by knight42** [comment]
I have filed #104193 to address this issue.

**Comment by SergeyKanzhelev** [comment]
/assign @knight42

since you are already working on it. Thank you!

**Comment by MikeSpreitzer** [comment]
This may be a duplicate of #104057
