### ISSUE TITLE
externalTrafficPolicy: Local does not work for NodePort Services

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#104105]
#### What happened:

NodePort Services with `externalTrafficPolicy: Local` do not actually direct traffic exclusively to local pods. Instead, load balancer rules are created in iptables that will route traffic to other nodes' pods.

#### What you expected to happen:

The behavior documented [here](https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip) and [here](https://kubernetes.io/docs/tutorials/services/source-ip/#source-ip-for-services-with-type-nodeport) should happen.

#### How to reproduce it (as minimally and precisely as possible):

This repro case from 1.16 still works, in fact the output for the iptables rules is basically identical, except for new nodes being in existence: https://github.com/kubernetes/kubernetes/issues/85397#issuecomment-600324032

1. Create a NodePort Service with `externalTrafficPolicy: Local`
2. Look at iptables rules, see that they are load balancing traffic between pods

You can really highlight the problem by using this strategy for a DaemonSet, like we do for the datadog-agent. We wanted a Service that would let any pod send statsd metrics to its own Node IP address (via downward API) at the configured Service port, to hit the NodePort and get redirected to the colocated datadog-agent pod. What we found was that the traffic would get sent to different nodes, and this would mess up the `host` tag, making metrics submitted from a pod on host A be tagged as if the pod was running on host B.

#### Anything else we need to know?:

This was previously opened in #85397 but erroneously closed. I could not reopen it, so I am forced to create a new issue.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.12
- Cloud provider or hardware configuration: AWS EC2 (the hard way)
- OS (e.g: `cat /etc/os-release`): `Debian GNU/Linux 9 (stretch)`
- Kernel (e.g. `uname -a`): `Linux ip-10-42-17-156 5.4.38 #1~bt9+1 SMP Tue May 12 21:16:19 UTC 2020 x86_64 GNU/Linux`
- Install tools: none, we do it the hard way
- Network plugin and version (if this is a network-related bug): calico 3.18.4
- Others:

**Comment by aojea** [comment]
> We wanted a Service that would let any pod send statsd metrics to its own Node IP address (via downward API) at the configured Service port, to hit the NodePort and get redirected to the colocated datadog-agent pod. What we found was that the traffic would get sent to different nodes, and this would mess up the `host` tag, making metrics submitted from a pod on host A be tagged as if the pod was running on host B.

the traffic is coming from inside the cluster, hence `externalTrafficPolicy` doesn't apply.
There is a new feature `internalTrafficPolicy` that was added in 1.21 and is going to be beta in 1.22 that does what you want
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy

/remove kind-bug

**Comment by 2rs2ts** [comment]
Why was a new feature needed instead of a bug fix? Who could possibly want to contact the NodePort instead of the ClusterIP–something that takes extra configuration to do–if not to circumvent the ClusterIP load balancing?

**Comment by uablrek** [comment]
Please see also https://github.com/kubernetes/kubernetes/issues/93456. In ipvs mode traffic is blackholed if no local pod exists.

**Comment by thockin** [comment]
Discussed at sig-net today.  I have a distinct memory (rare for me!) of discussion this design point and it came down to a lesser-evil choice.  We could either treat ALL traffic to a NodePort as external (in which case hitting the NodePort on your pod's node could blackhole) or treat internal traffic to a NodePort as internal.  We know that some users *do* hit their local nodeport and breaking them (blackhole) was perceived as worse.

Now it seems that IPVS and iptables disagree on this.  That's unpleasant.  I'm open to re-adjudicating this point if we think it is incorrect, but changing it now (in either direction) is a break.

> Why was a new feature needed instead of a bug fix?

Internal traffic policy and external traffic policy serve different goals and have some different meanings.  for ETP=local it almost always means "preserve the source IP".  For ITP=local it means "use my node agent" (we already preserve source IP).  We decided it was valid to set ETP=local and ITP=cluster, so they needed to be 2 different policy statements.

I also find it odd that we set up a healthCheckNodePort for type=LB and not for type=nodePort, but that's a different issue.

So for what you want, ITP should be the better answer, I think.

But we should answer (and document) what we think is supposed to happen for NodePorts x internal sources.

**Comment by 2rs2ts** [comment]
>In ipvs mode traffic is blackholed if no local pod exists.

I think that's also what happens in iptables mode, though–at least, for traffic coming from outside the cluster. My brief reading of that issue leads me to believe that ipvs mode's problem is that it is not load balancing traffic sent to the ClusterIP, which I agree is definitely a bug–but I was just talking about the NodePort.

I do not know as much about ipvs as I do about iptables; if ipvs is unable to differentiate between internal and external traffic in this context, then that would explain why the design is how it is... though that raises the question of why a new feature for internal traffic would help. 😅 

>We know that some users do hit their local nodeport and breaking them (blackhole) was perceived as worse.

I agree that sending traffic to a blackhole is worse than (what I perceive to be) ignoring the traffic policy. Though, I am unable to come up with a reason why a user would hit a NodePort service instead of a ClusterIP when the latter doesn't require any use of the downward API and is just way simpler and easier, *unless* they were specifically trying to get treated as external clients. Whether or not kube-proxy can allow the user the functional choice in ipvs mode notwithstanding...

>So for what you want, ITP should be the better answer, I think.

Yes, it seems so, but waiting until that's stable enough to use in production is not my idea of a fun time, and there will forever be users like me who expect that traffic sent to the "external" interface (NodePort) would be subject to the external traffic policy, only to find out the hard way that it's not so.

**Comment by uablrek** [comment]
> is not load balancing traffic sent to the ClusterIP

Of course that works, that is basic functionality. The issue is about traffic to a loadBalancerIP or nodePort. Also please note that a PR that fixes the problem (or makes the behaivor the same as for iptables) for ipvs exists.

> I agree that sending traffic to a blackhole is worse than (what I perceive to be) ignoring the traffic policy.

Um, that is the third option when no local pod exists?

The use-case that sending traffic from an internal pod directed to a loadBalancerIP/nodePort to another node even with etp:local is when an application makes an external dns query for a service that _may_ be in the local cluster _or_ hosted remotely. To configure the app to make a local query (and get the clusterIP) is the service is hosted locally and an external query otherwise is possible but clumsy and non-intuitive. IMHO this is a more "main-stream" use-case than the problem in this issue.

**Comment by 2rs2ts** [comment]
I'm not really following your example–it sounds as though something like coredns would be able to solve it–but I will chalk this up to my inexperience. I can at least take away that you can't know what the client intended by the time the request goes through kube-proxy's rules, and that sometimes clients hit the NodePort without specifically trying to circumvent load balancing, even if I can't conceive of why they would do that.

Thank you both for your time.

**Comment by aojea** [comment]
> I also find it odd that we set up a healthCheckNodePort for type=LB and not for type=nodePort, but that's a different issue.

@thockin  the healtcheck is only used by the external loadbalancers to know if they should forward traffic to that node, no?
