### ISSUE TITLE
Record node authorizer update graph latency

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/kubernetes#104108]
#### What would you like to be added:

Log statements and metrics indicating when the node authorizer graph has be updated for a pod.

There is already a log statement for when the graph starts an update, but this is before the graph lock is obtained and doesn't tell when the graph update is completed.

#### Why is this needed:

We are seeing node authorizer failures which prevent pods from starting for extended periods of time.  It is believed that this is caused by a race between:

- the node authorizer graph being updated
- the node requesting the secret

It is important to have logging that indicates when the graph finished updating in order to reflect lock contention on the graph.

**Comment by Shubham82** [comment]
Hi, folks
I would like to work on this.
/assign

**Comment by Shubham82** [comment]
Hi
Fixed this issue here #107744
