### ISSUE TITLE
etcd "expire" action not handled

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#10412]
Seen in logs: `etcd_helper_watch.go:411] unknown action: expire`

https://github.com/GoogleCloudPlatform/kubernetes/blob/11f9fd1dcd9a0b45e2b1fdeced95b61aed153599/pkg/tools/etcd_helper_watch.go#L411

Presumably this should send a delete instead of dropping it on the floor.

**Comment by bprashanth** [comment]
I think I ran into similar confusion about a month ago, I also vaguely remember that kube-dns (or something equally unrelated) was the only thing creating keys with a ttl. Think it's a red herring.

**Comment by lavalamp** [comment]
It's not the thing I'm trying to find but it is definitely worth fixing. I think the graceful pod deletion stuff sets TTLs?

**Comment by bprashanth** [comment]
yes, IIRC it's hidden behind a flag though

**Comment by lavalamp** [comment]
Maybe it's events? I think the test I found this in watches events. At any rate, the fix should be trivial.

**Comment by wojtek-t** [comment]
I agree those are probably events - all the events have ttl set.

**Comment by bprashanth** [comment]
>I agree those are probably events - all the events have ttl set.

It would be weird if that was messing with density, since density takes < 1hour (ttl of events) and we synchronously cleanup events after load test. I totally agree we should handle the expired event from etcd.

**Comment by wojtek-t** [comment]
>
It would be weird if that was messing with density, since density takes < 1hour (ttl of events) and we synchronously cleanup events after load test. I totally agree we should handle the expired event from etcd.

That's not exactly true - we synchronously cleanup events before the next step. So if you run a test and the leave the cluster, events will be deleted asynchronously then.

**Comment by bprashanth** [comment]
True, I meant this can only mess with a local cluster if it's events ttls

**Comment by wojtek-t** [comment]
I agree.

**Comment by timothysc** [comment]
issue expired.. ;-)
