### ISSUE TITLE
[sig-network] Ingress API should support creating Ingress API operations [Conformance]

### ISSUE THREAD

**Issue by oeotvos** [kubernetes/kubernetes#104162]
#### Which jobs are failing:
sonobuoy run --e2e-focus="Ingress API should support creating Ingress API operations" --kube-conformance-image-version v1.19.8

#### Which test(s) are failing:
`[sig-network] Ingress API
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/framework.go:23
should support creating Ingress API operations [Conformance] [It]
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:597

Aug 5 07:39:59.312: Unexpected error:
<*errors.StatusError | 0xc0039e08c0>: {
ErrStatus: {
TypeMeta: {Kind: "", APIVersion: ""},
ListMeta: {
SelfLink: "",
ResourceVersion: "",
Continue: "",
RemainingItemCount: nil,
},
Status: "Failure",
Message: "ingresses.networking.k8s.io "e2e-example-ing" is forbidden: service "test-backend" not found",
Reason: "Forbidden",
Details: {
Name: "e2e-example-ing",
Group: "networking.k8s.io",
Kind: "ingresses",
UID: "",
Causes: nil,
RetryAfterSeconds: 0,
},
Code: 403,
},
}
ingresses.networking.k8s.io "e2e-example-ing" is forbidden: service "test-backend" not found
occurred
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:1060

{"msg":"FAILED [sig-network] Ingress API should support creating Ingress API operations [Conformance]","total":1,"completed":0,"skipped":4770,"failed":1,"failures":["[sig-network] Ingress API should support creating Ingress API operations [Conformance]"]}`

#### Testgrid link:
[202108050739_sonobuoy_8a2aed03-254c-4338-bc99-7d4492498a90.tar.gz](https://github.com/kubernetes/kubernetes/files/6939289/202108050739_sonobuoy_8a2aed03-254c-4338-bc99-7d4492498a90.tar.gz)

#### Reason for failure:
As far as I understand, ingress is trying to be created without existing "test-backend" service

#### Anything else we need to know:
Looks like our cluster has enhanced verification whether the service exists before ingress creation, i.e let's create an simple ingress without service created in upfront:

- k apply -f ingress.yaml
    Error from server (Forbidden): error when creating "ingress.yaml": ingresses.networking.k8s.io "minimal-ingress" is forbidden: service "test321" not found
- cat ingress.yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
    name: minimal-ingress
    annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    spec:
    rules:
        http:
        paths:
            path: /testpath
            pathType: Prefix
            backend:
            service:
            name: test321
            port:
            number: 80

Thank you in advance.

/sig network
/sig testing
/wg k8s Infra

**Comment by thockin** [comment]
This is not a standard thing.  The kubernetes semantic is that the service DOES NOT need to pre-exist.  I can't see where this validation is being done in k/k.  I don't believe it *is* being done in k/k

> Looks like our cluster has enhanced verification whether the service exists before ingress creation

I don't know what exactly this means (in terms of "how") but your cluster seems to be intentionally non-conformant.  This is not a bug in Kubernetes as far as I can see?  What resolution are you hoping for?

**Comment by oeotvos** [comment]
Thank you for the explanation and confirmation!
