### ISSUE TITLE
Log attempts to output resp.Body 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#104184]
#### What happened:

Log messages like `body of failing http response: &{0x531900 0xc0010d2780 0x775180}` are not very informative.

/sig cloud-provider

#### What you expected to happen:

Either actual response body or none of it if this is a security concern.

/sig security

sig security to confirm it is ok to change this to log an actual response body.

#### How to reproduce it (as minimally and precisely as possible):

two places it is being logged:

- https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/legacy-cloud-providers/gce/gcpcredential/credentialutil.go#L63
- https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/credentialprovider/config.go#L206

#### Environment:
- Kubernetes version (use `kubectl version`):1.20, but doesn't matter
- Cloud provider or hardware configuration:GKE
- OS (e.g: `cat /etc/os-release`):COS

**Comment by yuzhiquan** [comment]
FYI, `InfoS` already handle []byte display in https://github.com/kubernetes/klog/pull/237, may be we can move this to structured-logging.

**Comment by feeltimeQ** [comment]
l can fix this

**Comment by skywe-tang** [comment]
Hi, @feeltimeQ I just found a place to test my first submit. If you are still working on this, please let me know. I'll close my PR

**Comment by feeltimeQ** [comment]
> Hi, @feeltimeQ I just found a place to test my first submit. If you are still working on this, please let me know. I'll close my PR

   Hi, @skywe-tang, l still working on this issues, thanks .

**Comment by skywe-tang** [comment]
> > Hi, @feeltimeQ I just found a place to test my first submit. If you are still working on this, please let me know. I'll close my PR
> 
> Hi, @skywe-tang, l still working on this issues, thanks .

OK, go ahead. This PR #104225 can be used as a reference, I‘ll close it
