### ISSUE TITLE
What to do ? "cloud-console-reader" is forbidden: User  "system:node:anth-admin-host1" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" 

### ISSUE THREAD

**Issue by ciuffoly** [kubernetes/kubernetes#104176]
ubuntu@anth-mgt-wksadmin:~$ cat cloud-console-reader.yaml 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-console-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

ubuntu@anth-mgt-wksadmin:~$ kubectl apply -f cloud-console-reader.yaml --kubeconfig kubeconfig
Error from server (Forbidden): error when retrieving current configuration of:
Resource: "rbac.authorization.k8s.io/v1, Resource=clusterroles", GroupVersionKind: "rbac.authorization.k8s.io/v1, Kind=ClusterRole"
Name: "cloud-console-reader", Namespace: ""
from server for: "cloud-console-reader.yaml": clusterroles.rbac.authorization.k8s.io "**cloud-console-reader" is forbidden: User 
"system:node:anth-admin-host1" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope**

ubuntu@anth-mgt-wksadmin:~$ cat cloud-console-reader.yaml 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-console-reader
rules:
- apiGroups: [""]
  resources: ["nodes", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]

ubuntu@anth-mgt-wksadmin:~$ kubectl  get nodes  --kubeconfig kubeconfig
NAME               STATUS   ROLES                  AGE     VERSION
anth-admin-host1   Ready    control-plane,master   7d4h    v1.20.5-gke.1301
anth-admin-host3   Ready    <none>                 3h50m   v1.20.5-gke.1301
anth-admin-host4   Ready    <none>                 6d7h    v1.20.5-gke.1301
anth-admin-host5   Ready    <none>                 3h48m   v1.20.5-gke.1301

ubuntu@anth-mgt-wksadmin:~$ kubectl cluster-info dump  --kubeconfig test_config |tail -5
Error from server (Forbidden): users "sa000580@gcloud.telecomitalia.it" is forbidden: User "system:serviceaccount:gke-connect:connect-agent-sa" cannot impersonate resource "users" in API group "" at the cluster scope

**Comment by neolit123** [comment]
hi, this doesn't seem like a bug in k8s, but rather a request for support.
please try getting help at the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
