### ISSUE TITLE
Node image reporting can return indeterminate results to the API server

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#104136]
#### What happened:
The Kubelet defaults nodeStatusMaxImages to 50 images to report to the API server. The [Images](https://github.com/kubernetes/kubernetes/blob/026fb3bf35915c9b4e2029ce162724648854a291/pkg/kubelet/nodestatus/setters.go#L459) function does a truncate before the sort. This could cause the kubelet to report images in an indeterminate way depending on how the remote container runtime returns the images to the kubelet. 

#### What you expected to happen:
I expect the sort to happen before the truncation so a consistent set of images are always returned to the API server.

#### Environment:
- Kubernetes version (use `kubectl version`): master - 5be21c50c269fc1d28e0bd31ab9dcb572ae7fac5
- Cloud provider or hardware configuration: all
- OS (e.g: `cat /etc/os-release`): Linux
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

/sig node

**Comment by rphillips** [comment]
Sorry, this is working correctly.

**Comment by fabiand** [comment]
Could you elaborate on why this is working as expected?

**Comment by fabiand** [comment]
This got also discussed in #93488
