### ISSUE TITLE
Kubernetes cache data error that block helm install command

### ISSUE THREAD

**Issue by antzjm** [kubernetes/kubernetes#104115]
#### What happened:
When I install a helm chart, but return some error.
Sometimes the error info like that:
**Error: unable to build kubernetes objects from release manifest: string field contains invalid UTF-8**
And sometimes the error info like that:
**[2021-07-28T03:00:35.441Z] Error: unable to build kubernetes objects from release manifest: proto: invalid field number**
#### What you expected to happen:
I hope I can install helm chart smoothly.
#### How to reproduce it (as minimally and precisely as possible):
This issue happened in my infra frequently.
#### Anything else we need to know?:
I just take a action that remove ~/.kube/cache file as work around to solve this problem temporarily. 
#### Environment:
- Kubernetes version (use `kubectl version`): v1.19.5
- Cloud provider or hardware configuration: 
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009 (Core)
- Kernel (e.g. `uname -a`): 4.18.0-1.2007201736.el7_7.emrs.altmvl.x86_64 
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kerthcet** [comment]
i think it's not a bug of kubernetes. have you tried other helms for test

**Comment by neolit123** [comment]
> i think it's not a bug of kubernetes. have you tried other helms for test

agreed.

> Error: unable to build kubernetes objects from release manifest: string field contains invalid UTF-8

you should report this to the authors of the helm chart or to helm.

/kind support
/close

**Comment by neolit123** [comment]
to ask other users if they have seen this you can also try the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by antzjm** [comment]
@neolit123 I remove k8s cache to solve this issue, So I guess the root cause is related with k8s.
