### ISSUE TITLE
vsphere debian vmdk (master/minion) proxy

### ISSUE THREAD

**Issue by lcowdrey** [kubernetes/kubernetes#10417]
Using both the pre-built kubernetes tar ball (v0.19.3) and the base Debian VMDK, (https://storage.googleapis.com/govmomi/vmdk/2014-11-11/kube.vmdk.gz) during kube-up.sh all services for the master and minions do not appear to start and kube-up.sh goes in to endless loop.

This appears to be down to such running commands as:

curl -v -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com

Which when running in a proxy-environment, fails. This is simply down to the proxy environment variables not making it in when commands like curl are running towards external addresses.

Defining http_proxy/https_proxy and running the curl command again on master, successfully pulls back the salt bootstrap.

Is this related to issue #9623 or something else?

I have attempted to build kubernetes from git source, specifying the proxy details in build/build-image/Dockerfile but its appearing to generate similar results as in kube-up.sh staying in endless loop.

**Comment by lcowdrey** [comment]
root      1973     1  0 12:30 ?        00:00:00 /usr/sbin/rpc.idmapd
root      2255     1  0 12:30 ?        00:00:00 /usr/sbin/rsyslogd -c5
root      2344     1  0 12:30 ?        00:00:00 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
root      2365     1  0 12:30 ?        00:00:00 /usr/sbin/acpid
daemon    2390     1  0 12:30 ?        00:00:00 /usr/sbin/atd
root      2432     1  0 12:30 ?        00:00:00 /usr/sbin/cron
ntp       2714     1  0 12:30 ?        00:00:00 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -c /var/lib/ntp/ntp.conf.dhcp -u 103:106
101       2738     1  0 12:30 ?        00:00:00 /usr/sbin/exim4 -bd -q30m
root      2767     1  0 12:30 ?        00:00:00 /usr/sbin/sshd
root      2791     1  0 12:30 tty1     00:00:00 /sbin/getty 38400 tty1
root      2792     1  0 12:30 tty2     00:00:00 /sbin/getty 38400 tty2
root      2793     1  0 12:30 tty3     00:00:00 /sbin/getty 38400 tty3
root      2794     1  0 12:30 tty4     00:00:00 /sbin/getty 38400 tty4
root      2795     1  0 12:30 tty5     00:00:00 /sbin/getty 38400 tty5
root      2796     1  0 12:30 tty6     00:00:00 /sbin/getty 38400 tty6
root      2813     1  0 12:31 ?        00:00:00 sudo /tmp/master-start.sh
root      2814  2813  0 12:31 ?        00:00:00 /bin/bash /tmp/master-start.sh
root      2857  2814  0 12:31 ?        00:00:00 curl -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com
root      2858  2814  0 12:31 ?        00:00:00 sh -s -- -M -X
root      2859  2767  0 12:31 ?        00:00:00 sshd: kube [priv]
kube      2861  2859  0 12:31 ?        00:00:00 sshd: kube@pts/0
kube      2862  2861  3 12:31 pts/0    00:00:00 -bash
kube      2943  2862  0 12:31 pts/0    00:00:00 ps -ef
kube@kubernetes-master:~$ cat /tmp/master-start.sh
#! /bin/bash
readonly MY_NAME=kubernetes-master


sed -i -e 's/\b\w\+.vm\b//' /etc/hosts

sed -i -e "s/\\bkube\\b/${MY_NAME}/g" /etc/host{s,name}
hostname ${MY_NAME}
cd /home/kube/cache/kubernetes-install
readonly MASTER_NAME='kubernetes-master'
readonly INSTANCE_PREFIX='kubernetes'
readonly NODE_INSTANCE_PREFIX='kubernetes-minion'
readonly SERVICE_CLUSTER_IP_RANGE='10.244.240.0/20'
readonly ENABLE_NODE_MONITORING='true'
readonly ENABLE_NODE_LOGGING='false'
readonly LOGGING_DESTINATION='elasticsearch'
readonly ENABLE_CLUSTER_DNS='true'
readonly DNS_SERVER_IP='10.244.240.240'
readonly DNS_DOMAIN='cluster.local'
readonly SERVER_BINARY_TAR='kubernetes-server-linux-amd64.tar.gz'
readonly SALT_TAR='kubernetes-salt.tar.gz'
readonly MASTER_HTPASSWD='admin:KcKN/I0TbVSGo'



mkdir -p /srv/salt-overlay/pillar
cat <<EOF >/srv/salt-overlay/pillar/cluster-params.sls
instance_prefix: '$(echo "$INSTANCE_PREFIX" | sed -e "s/'/''/g")'
node_instance_prefix: $NODE_INSTANCE_PREFIX
service_cluster_ip_range: $SERVICE_CLUSTER_IP_RANGE
enable_cluster_monitoring: $ENABLE_CLUSTER_MONITORING
enable_node_monitoring: $ENABLE_NODE_MONITORING
enable_cluster_logging: $ENABLE_CLUSTER_LOGGING
enable_node_logging: $ENABLE_NODE_LOGGING
logging_destination: $LOGGING_DESTINATION
elasticsearch_replicas: $ELASTICSEARCH_LOGGING_REPLICAS
enable_cluster_dns: $ENABLE_CLUSTER_DNS
dns_replicas: $DNS_REPLICAS
dns_server: $DNS_SERVER_IP
dns_domain: $DNS_DOMAIN
EOF

mkdir -p /srv/salt-overlay/salt/nginx
echo $MASTER_HTPASSWD > /srv/salt-overlay/salt/nginx/htpasswd



echo "Unpacking Salt tree"
rm -rf kubernetes
tar xzf "${SALT_TAR}"

echo "Running release install script"
sudo kubernetes/saltbase/install.sh "${SERVER_BINARY_TAR}"


sed -i -e "s/http.us.debian.org/mirrors.kernel.org/" /etc/apt/sources.list

mkdir -p /etc/salt/minion.d
echo "master: $MASTER_NAME" > /etc/salt/minion.d/master.conf

cat <<EOF >/etc/salt/minion.d/grains.conf
grains:
  roles:
    - kubernetes-master
  cloud: vsphere
EOF

mkdir -p /etc/salt/master.d
cat <<EOF >/etc/salt/master.d/auto-accept.conf
auto_accept: True
EOF

cat <<EOF >/etc/salt/master.d/reactor.conf
reactor:
  - 'salt/minion/*/start':
    - /srv/reactor/highstate-new.sls
    - /srv/reactor/highstate-masters.sls
    - /srv/reactor/highstate-minions.sls
EOF

set +x
curl -L --connect-timeout 20 --retry 6 --retry-delay 10 https://bootstrap.saltstack.com | sh -s -- -M -X
set -x

**Comment by lcowdrey** [comment]
kube@kubernetes-master:/tmp$ cat master-start.sh.err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 6 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 3 retries left.

**Comment by lcowdrey** [comment]
kube@kubernetes-master:/tmp$ cat master-start.sh.err
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 6 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 5 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 4 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0Warning: Transient problem: timeout Will retry in 10 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0curl: (28) connect() timed out!

**Comment by lcowdrey** [comment]
kube@kubernetes-master:/tmp$ cat master-start.sh.out
Unpacking Salt tree
Running release install script
+++ Installing salt files into new trees
`kubernetes/saltbase/salt' -> `/srv/salt-new/salt'
`kubernetes/saltbase/salt/kubelet' -> `/srv/salt-new/salt/kubelet'
`kubernetes/saltbase/salt/kubelet/kubelet.service' -> `/srv/salt-new/salt/kubelet/kubelet.service'
`kubernetes/saltbase/salt/kubelet/kubernetes_auth' -> `/srv/salt-new/salt/kubelet/kubernetes_auth'
`kubernetes/saltbase/salt/kubelet/default' -> `/srv/salt-new/salt/kubelet/default'
`kubernetes/saltbase/salt/kubelet/initd' -> `/srv/salt-new/salt/kubelet/initd'
`kubernetes/saltbase/salt/kubelet/init.sls' -> `/srv/salt-new/salt/kubelet/init.sls'
`kubernetes/saltbase/salt/docker' -> `/srv/salt-new/salt/docker'
`kubernetes/saltbase/salt/docker/docker-defaults' -> `/srv/salt-new/salt/docker/docker-defaults'
`kubernetes/saltbase/salt/docker/default' -> `/srv/salt-new/salt/docker/default'
`kubernetes/saltbase/salt/docker/init.sls' -> `/srv/salt-new/salt/docker/init.sls'
`kubernetes/saltbase/salt/README.md' -> `/srv/salt-new/salt/README.md'
`kubernetes/saltbase/salt/kube-scheduler' -> `/srv/salt-new/salt/kube-scheduler'
`kubernetes/saltbase/salt/kube-scheduler/kube-scheduler.manifest' -> `/srv/salt-new/salt/kube-scheduler/kube-scheduler.manifest'
`kubernetes/saltbase/salt/kube-scheduler/init.sls' -> `/srv/salt-new/salt/kube-scheduler/init.sls'
`kubernetes/saltbase/salt/kube-master-addons' -> `/srv/salt-new/salt/kube-master-addons'
`kubernetes/saltbase/salt/kube-master-addons/kube-master-addons.sh' -> `/srv/salt-new/salt/kube-master-addons/kube-master-addons.sh'
`kubernetes/saltbase/salt/kube-master-addons/kube-master-addons.service' -> `/srv/salt-new/salt/kube-master-addons/kube-master-addons.service'
`kubernetes/saltbase/salt/kube-master-addons/initd' -> `/srv/salt-new/salt/kube-master-addons/initd'
`kubernetes/saltbase/salt/kube-master-addons/init.sls' -> `/srv/salt-new/salt/kube-master-addons/init.sls'
`kubernetes/saltbase/salt/debian-auto-upgrades' -> `/srv/salt-new/salt/debian-auto-upgrades'
`kubernetes/saltbase/salt/debian-auto-upgrades/20auto-upgrades' -> `/srv/salt-new/salt/debian-auto-upgrades/20auto-upgrades'
`kubernetes/saltbase/salt/debian-auto-upgrades/init.sls' -> `/srv/salt-new/salt/debian-auto-upgrades/init.sls'
`kubernetes/saltbase/salt/kube-client-tools.sls' -> `/srv/salt-new/salt/kube-client-tools.sls'
`kubernetes/saltbase/salt/logrotate' -> `/srv/salt-new/salt/logrotate'
`kubernetes/saltbase/salt/logrotate/init.sls' -> `/srv/salt-new/salt/logrotate/init.sls'
`kubernetes/saltbase/salt/logrotate/cron' -> `/srv/salt-new/salt/logrotate/cron'
`kubernetes/saltbase/salt/logrotate/conf' -> `/srv/salt-new/salt/logrotate/conf'
`kubernetes/saltbase/salt/logrotate/docker-containers' -> `/srv/salt-new/salt/logrotate/docker-containers'
`kubernetes/saltbase/salt/kube-addons' -> `/srv/salt-new/salt/kube-addons'
`kubernetes/saltbase/salt/kube-addons/kube-addons.sh' -> `/srv/salt-new/salt/kube-addons/kube-addons.sh'
`kubernetes/saltbase/salt/kube-addons/dns' -> `/srv/salt-new/salt/kube-addons/dns'
`kubernetes/saltbase/salt/kube-addons/dns/skydns-svc.yaml.in' -> `/srv/salt-new/salt/kube-addons/dns/skydns-svc.yaml.in'
`kubernetes/saltbase/salt/kube-addons/dns/skydns-rc.yaml.in' -> `/srv/salt-new/salt/kube-addons/dns/skydns-rc.yaml.in'
`kubernetes/saltbase/salt/kube-addons/kube-addon-update.sh' -> `/srv/salt-new/salt/kube-addons/kube-addon-update.sh'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/heapster-service.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/heapster-service.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/influxdb-service.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/influxdb-service.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/heapster-controller.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/heapster-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/grafana-service.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/grafana-service.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/google'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google/heapster-service.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/google/heapster-service.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/google/heapster-controller.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/google/heapster-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/googleinfluxdb' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/googleinfluxdb'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/googleinfluxdb/heapster-controller-combined.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/googleinfluxdb/heapster-controller-combined.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone/heapster-service.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone/heapster-service.yaml'
`kubernetes/saltbase/salt/kube-addons/cluster-monitoring/standalone/heapster-controller.yaml' -> `/srv/salt-new/salt/kube-addons/cluster-monitoring/standalone/heapster-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/kube-addons.service' -> `/srv/salt-new/salt/kube-addons/kube-addons.service'
`kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch' -> `/srv/salt-new/salt/kube-addons/fluentd-elasticsearch'
`kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/es-service.yaml' -> `/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/es-service.yaml'
`kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/kibana-controller.yaml' -> `/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/kibana-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/kibana-service.yaml' -> `/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/kibana-service.yaml'
`kubernetes/saltbase/salt/kube-addons/fluentd-elasticsearch/es-controller.yaml' -> `/srv/salt-new/salt/kube-addons/fluentd-elasticsearch/es-controller.yaml'
`kubernetes/saltbase/salt/kube-addons/initd' -> `/srv/salt-new/salt/kube-addons/initd'
`kubernetes/saltbase/salt/kube-addons/init.sls' -> `/srv/salt-new/salt/kube-addons/init.sls'
`kubernetes/saltbase/salt/helpers' -> `/srv/salt-new/salt/helpers'
`kubernetes/saltbase/salt/helpers/init.sls' -> `/srv/salt-new/salt/helpers/init.sls'
`kubernetes/saltbase/salt/helpers/safe_format_and_mount' -> `/srv/salt-new/salt/helpers/safe_format_and_mount'
`kubernetes/saltbase/salt/base.sls' -> `/srv/salt-new/salt/base.sls'
`kubernetes/saltbase/salt/kube-admission-controls' -> `/srv/salt-new/salt/kube-admission-controls'
`kubernetes/saltbase/salt/kube-admission-controls/limit-range' -> `/srv/salt-new/salt/kube-admission-controls/limit-range'
`kubernetes/saltbase/salt/kube-admission-controls/limit-range/limit-range.yaml' -> `/srv/salt-new/salt/kube-admission-controls/limit-range/limit-range.yaml'
`kubernetes/saltbase/salt/kube-admission-controls/init.sls' -> `/srv/salt-new/salt/kube-admission-controls/init.sls'
`kubernetes/saltbase/salt/fluentd-gcp' -> `/srv/salt-new/salt/fluentd-gcp'
`kubernetes/saltbase/salt/fluentd-gcp/fluentd-gcp.yaml' -> `/srv/salt-new/salt/fluentd-gcp/fluentd-gcp.yaml'
`kubernetes/saltbase/salt/fluentd-gcp/init.sls' -> `/srv/salt-new/salt/fluentd-gcp/init.sls'
`kubernetes/saltbase/salt/cadvisor' -> `/srv/salt-new/salt/cadvisor'
`kubernetes/saltbase/salt/cadvisor/init.sls' -> `/srv/salt-new/salt/cadvisor/init.sls'
`kubernetes/saltbase/salt/openvpn-client' -> `/srv/salt-new/salt/openvpn-client'
`kubernetes/saltbase/salt/openvpn-client/client.conf' -> `/srv/salt-new/salt/openvpn-client/client.conf'
`kubernetes/saltbase/salt/openvpn-client/init.sls' -> `/srv/salt-new/salt/openvpn-client/init.sls'
`kubernetes/saltbase/salt/openvpn' -> `/srv/salt-new/salt/openvpn'
`kubernetes/saltbase/salt/openvpn/server.conf' -> `/srv/salt-new/salt/openvpn/server.conf'
`kubernetes/saltbase/salt/openvpn/init.sls' -> `/srv/salt-new/salt/openvpn/init.sls'
`kubernetes/saltbase/salt/etcd' -> `/srv/salt-new/salt/etcd'
`kubernetes/saltbase/salt/etcd/etcd.manifest' -> `/srv/salt-new/salt/etcd/etcd.manifest'
`kubernetes/saltbase/salt/etcd/init.sls' -> `/srv/salt-new/salt/etcd/init.sls'
`kubernetes/saltbase/salt/kube-proxy' -> `/srv/salt-new/salt/kube-proxy'
`kubernetes/saltbase/salt/kube-proxy/kube-proxy.service' -> `/srv/salt-new/salt/kube-proxy/kube-proxy.service'
`kubernetes/saltbase/salt/kube-proxy/kubeconfig' -> `/srv/salt-new/salt/kube-proxy/kubeconfig'
`kubernetes/saltbase/salt/kube-proxy/default' -> `/srv/salt-new/salt/kube-proxy/default'
`kubernetes/saltbase/salt/kube-proxy/initd' -> `/srv/salt-new/salt/kube-proxy/initd'
`kubernetes/saltbase/salt/kube-proxy/init.sls' -> `/srv/salt-new/salt/kube-proxy/init.sls'
`kubernetes/saltbase/salt/top.sls' -> `/srv/salt-new/salt/top.sls'
`kubernetes/saltbase/salt/generate-cert' -> `/srv/salt-new/salt/generate-cert'
`kubernetes/saltbase/salt/generate-cert/make-cert.sh' -> `/srv/salt-new/salt/generate-cert/make-cert.sh'
`kubernetes/saltbase/salt/generate-cert/make-ca-cert.sh' -> `/srv/salt-new/salt/generate-cert/make-ca-cert.sh'
`kubernetes/saltbase/salt/generate-cert/init.sls' -> `/srv/salt-new/salt/generate-cert/init.sls'
`kubernetes/saltbase/salt/_states' -> `/srv/salt-new/salt/_states'
`kubernetes/saltbase/salt/_states/container_bridge.py' -> `/srv/salt-new/salt/_states/container_bridge.py'
`kubernetes/saltbase/salt/static-routes' -> `/srv/salt-new/salt/static-routes'
`kubernetes/saltbase/salt/static-routes/refresh' -> `/srv/salt-new/salt/static-routes/refresh'
`kubernetes/saltbase/salt/static-routes/if-down' -> `/srv/salt-new/salt/static-routes/if-down'
`kubernetes/saltbase/salt/static-routes/if-up' -> `/srv/salt-new/salt/static-routes/if-up'
`kubernetes/saltbase/salt/static-routes/init.sls' -> `/srv/salt-new/salt/static-routes/init.sls'
`kubernetes/saltbase/salt/kube-apiserver' -> `/srv/salt-new/salt/kube-apiserver'
`kubernetes/saltbase/salt/kube-apiserver/kube-apiserver.manifest' -> `/srv/salt-new/salt/kube-apiserver/kube-apiserver.manifest'
`kubernetes/saltbase/salt/kube-apiserver/init.sls' -> `/srv/salt-new/salt/kube-apiserver/init.sls'
`kubernetes/saltbase/salt/nginx' -> `/srv/salt-new/salt/nginx'
`kubernetes/saltbase/salt/nginx/kubernetes-site' -> `/srv/salt-new/salt/nginx/kubernetes-site'
`kubernetes/saltbase/salt/nginx/nginx.conf' -> `/srv/salt-new/salt/nginx/nginx.conf'
`kubernetes/saltbase/salt/nginx/nginx.json' -> `/srv/salt-new/salt/nginx/nginx.json'
`kubernetes/saltbase/salt/nginx/init.sls' -> `/srv/salt-new/salt/nginx/init.sls'
`kubernetes/saltbase/salt/kube-controller-manager' -> `/srv/salt-new/salt/kube-controller-manager'
`kubernetes/saltbase/salt/kube-controller-manager/init.sls' -> `/srv/salt-new/salt/kube-controller-manager/init.sls'
`kubernetes/saltbase/salt/kube-controller-manager/kube-controller-manager.manifest' -> `/srv/salt-new/salt/kube-controller-manager/kube-controller-manager.manifest'
`kubernetes/saltbase/salt/monit' -> `/srv/salt-new/salt/monit'
`kubernetes/saltbase/salt/monit/kubelet' -> `/srv/salt-new/salt/monit/kubelet'
`kubernetes/saltbase/salt/monit/docker' -> `/srv/salt-new/salt/monit/docker'
`kubernetes/saltbase/salt/monit/kube-addons' -> `/srv/salt-new/salt/monit/kube-addons'
`kubernetes/saltbase/salt/monit/kube-proxy' -> `/srv/salt-new/salt/monit/kube-proxy'
`kubernetes/saltbase/salt/monit/init.sls' -> `/srv/salt-new/salt/monit/init.sls'
`kubernetes/saltbase/salt/monit/monit_watcher.sh' -> `/srv/salt-new/salt/monit/monit_watcher.sh'
`kubernetes/saltbase/salt/fluentd-es' -> `/srv/salt-new/salt/fluentd-es'
`kubernetes/saltbase/salt/fluentd-es/fluentd-es.yaml' -> `/srv/salt-new/salt/fluentd-es/fluentd-es.yaml'
`kubernetes/saltbase/salt/fluentd-es/init.sls' -> `/srv/salt-new/salt/fluentd-es/init.sls'
`kubernetes/saltbase/pillar' -> `/srv/salt-new/pillar'
`kubernetes/saltbase/pillar/README.md' -> `/srv/salt-new/pillar/README.md'
`kubernetes/saltbase/pillar/logging.sls' -> `/srv/salt-new/pillar/logging.sls'
`kubernetes/saltbase/pillar/mine.sls' -> `/srv/salt-new/pillar/mine.sls'
`kubernetes/saltbase/pillar/docker-images.sls' -> `/srv/salt-new/pillar/docker-images.sls'
`kubernetes/saltbase/pillar/privilege.sls' -> `/srv/salt-new/pillar/privilege.sls'
`kubernetes/saltbase/pillar/top.sls' -> `/srv/salt-new/pillar/top.sls'
`kubernetes/saltbase/pillar/cluster-params.sls' -> `/srv/salt-new/pillar/cluster-params.sls'
`kubernetes/saltbase/reactor' -> `/srv/salt-new/reactor'
`kubernetes/saltbase/reactor/README.md' -> `/srv/salt-new/reactor/README.md'
`kubernetes/saltbase/reactor/highstate-new.sls' -> `/srv/salt-new/reactor/highstate-new.sls'
`kubernetes/saltbase/reactor/highstate-minions.sls' -> `/srv/salt-new/reactor/highstate-minions.sls'
`kubernetes/saltbase/reactor/highstate-masters.sls' -> `/srv/salt-new/reactor/highstate-masters.sls'
+++ Installing salt overlay files
`/srv/salt-overlay/salt/nginx/htpasswd' -> `/srv/salt-new/salt/nginx/htpasswd'
`/srv/salt-overlay/pillar/cluster-params.sls' -> `/srv/salt-new/pillar/cluster-params.sls'
+++ Install binaries from tar: kubernetes-server-linux-amd64.tar.gz
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/hyperkube' -> `/srv/salt-new/salt/kube-bins/hyperkube'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-apiserver.docker_tag' -> `/srv/salt-new/salt/kube-bins/kube-apiserver.docker_tag'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-apiserver.tar' -> `/srv/salt-new/salt/kube-bins/kube-apiserver.tar'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-controller-manager.docker_tag' -> `/srv/salt-new/salt/kube-bins/kube-controller-manager.docker_tag'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-controller-manager.tar' -> `/srv/salt-new/salt/kube-bins/kube-controller-manager.tar'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kubectl' -> `/srv/salt-new/salt/kube-bins/kubectl'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kubelet' -> `/srv/salt-new/salt/kube-bins/kubelet'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-proxy' -> `/srv/salt-new/salt/kube-bins/kube-proxy'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kubernetes' -> `/srv/salt-new/salt/kube-bins/kubernetes'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-scheduler.docker_tag' -> `/srv/salt-new/salt/kube-bins/kube-scheduler.docker_tag'
`/tmp/kubernetes.OvsWUE/kubernetes/server/bin/kube-scheduler.tar' -> `/srv/salt-new/salt/kube-bins/kube-scheduler.tar'
+++ Swapping in new configs
`/srv/salt-new/salt' -> `/srv/salt'
`/srv/salt-new/pillar' -> `/srv/pillar'
`/srv/salt-new/reactor' -> `/srv/reactor'

**Comment by roberthbailey** [comment]
/cc @pietern (listed on the [getting started guides](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides) as the vsphere maintainer). 

@lcowdrey FYI the vsphere guide doesn't look like it's been updated since last November, so it's unclear to me how well we should expect them to work with the current release. Contributions would be greatly appreciated!

**Comment by imkin** [comment]
The debian image has been update in january 2016. We also have anew guide. Lets please close this issue.

@mikedanese can you please close this one?
