### ISSUE TITLE
kube get pods --watch doesn't always report terminal status with exitCode during Deployment update

### ISSUE THREAD

**Issue by bydga** [kubernetes/kubernetes#104155]
#### What happened:
When updating an existing Deployment (`kubectl replace -f deployment.yaml`), new pods are being created and old pods are killed. We are constantly doing `kubectl get pods --watch` to do some internal monitoring, however sometimes (cca 30-50% of the cases) we don't receive the final update (for the old pod that is being stopped). Expecting somthing like:
```
"state": {
  "terminated": {
    "containerID": "docker://86714d667e1468048d982f2776020e4dc572985031eee75246f3c7f5a0280734",
    "exitCode": 0,
    "finishedAt": "2021-08-05T07:48:13Z",
    "reason": "Completed",
    "startedAt": "2021-08-05T07:45:56Z"
  }
}
```
Instead the last status update for such pod is weird:

```
"state": {
  "waiting": {
    "reason": "ContainerCreating"
  }
}
```
(complete logs below)
We really need to know the exitCode of all terminated containers/pods during upgrade.

#### What you expected to happen:
Receive the exitCode (included in the final pod status update notification) for all pods during Deployment upgrade.

#### How to reproduce it (as minimally and precisely as possible):
It is hard to consistently reproduce, but it happens to us with almost every Deployment update for at least one pod.

Deployment spec: [deployment.yml](https://github.com/kubernetes/kubernetes/files/6937404/deployment.yml.txt)
I am attaching 3 logs ( all done via `kubectl get pods --output json --watch-only --output-watch-events | jq 'del(.object.metadata.managedFields)'`):

- [Initial creation of the Deployment](https://github.com/kubernetes/kubernetes/files/6937390/deployment-initial-create.txt)(not really interesting)

- [Logs from deployment upgrade that is OK](https://github.com/kubernetes/kubernetes/files/6937391/deployment-replace-ok.txt) (changed resources.limits.memory to trigger the upgrade), using `kubectl replace` that is without problems. All pods correctly reported the final terminated status with exitCode. This log is mainly for complete picture, nothing much interesting there. All pods starts terminating (MODIFIED event with deletionTimestamp appears, then they shift from `state.running` to `state.terminated` with attached exit code.

- [Logs from second (faulty) upgrade](https://github.com/kubernetes/kubernetes/files/6937393/deployment-replace-missing.txt). <--- THIS is the important one. Again just changed memory using `kubectl replace` And one pod doesn't report the exitcode at all.
This one is interesting:
  - 3 pods are running before the upgrade: `example-deployment-5f846c8bc5-kzht5 example-deployment-5f846c8bc5-n49g2  example-deployment-5f846c8bc5-k8ppq`
  - First two of them start terminating (deletionTimestamp appears, then their containerStatuses change to `state.terminated`)
  - the last one (k8ppq) starts terminating as well (deletionTimestamp), however it fails to report how it ended - and the last status is the weird `ContainerCreating` (line 3375) - and no state.terminated with the attached exit code.

- I am also attaching one additional log of [events](https://github.com/kubernetes/kubernetes/files/6937398/events.txt) (done by `kube get events --watch-only --output-watch-events --output json | jq 'del(.object.metadata.managedFields)'`). But nothing useful there (at least nothing I am aware of)

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
```
AWS EKS, self managed worker nodes on EC2 isntances with https://cloud-images.ubuntu.com/docs/aws/eks/
```
- OS (e.g: `cat /etc/os-release`):
```
Ubuntu 20.04.2 LTS
```
- Kernel (e.g. `uname -a`):
```
5.4.0-1037-aws
```
- Install tools:
```
AWS CloudFormation templates - mostly from official AWS docs
```
- Network plugin and version (if this is a network-related bug):
```
Calico CNI
calico-node - docker.io/calico/cni:v3.19.1
tigera-operator - quay.io/tigera/operator:v1.17.4
```
- Others:

**Comment by codearky** [comment]
I was able to reproduce, but feels like these false containers status reports originate in kubelet (?)
Will keep investigating and update
/assign

**Comment by caesarxuchao** [comment]
/triage accepted

Thanks @codearky

**Comment by codearky** [comment]
My reproduction yielded a bit different output (kind v0.11.0 go1.16.4 linux/amd64, Kubernetes v1.21, Ubuntu 16.04) :
```
        {
          "image": "nginxdemos/hello:latest",
          "imageID": "",
          "lastState": {
            "terminated": {
              "exitCode": 137,
              "finishedAt": null,
              "message": "The container could not be located when the pod was deleted.  The container used to be Running",
              "reason": "ContainerStatusUnknown",
              "startedAt": null
            }
          },
          "name": "api",
          "ready": false,
          "restartCount": 0,
          "started": false,
          "state": {
            "waiting": {
              "reason": "ContainerCreating"
            }
          }
        }
```
in contrast to @bydga 's
```
  {
          "image": "nginxdemos/hello:latest",
          "imageID": "",
          "lastState": {},
          "name": "api",
          "ready": false,
          "restartCount": 0,
          "started": false,
          "state": {
            "waiting": {
              "reason": "ContainerCreating"
            }
          }
  }
```

Worth to mention that trying to reproduce it again after the first time, failed all my attempts.

I had some looks and found this change was merged https://github.com/kubernetes/kubernetes/pull/95561 to v1.20 which explains the difference.

The reason this happens at all is because we were not able to catch the container termination when it happened, we just know it used to exist and now is gone - so we know it has been terminated but don't really know why.

We can expect this kind of situation for example when our container has been killed by something other than kubelet and kubelet missed it, so generally saying @bydga I think it's a bit risky to assume you could always get the container's exit code because these things can happen from time to time.

Having say that, it's strange that we see this happen when the termination is "planned", i.e when it is being triggered from a deployment controller. Need further investiagtion on that, but as I was able to reproduce it only once, it's a bit hard to see where it falls. @bydga It would be very helpful if you could provide some detailed kubelet logs (verbosity  level 5) and maybe some logs from your container runtime - around when this issue occurs so I could keep looking into it. My best guess here is the container termination cycle happens before the kubelet's PLEG's is able to report the termination event (it is by default configured to 1s - see https://github.com/kubernetes/kubernetes/blob/355bc3df228d9529a15e53d4bb59757e191c0225/pkg/kubelet/kubelet.go#L158-L166)
Also, I would try to upgrade to v1.20 to see if it still happens frequently as described

**Comment by bydga** [comment]
Hmm interesting. I will try to upgrade the cluster and rerun our tests to see how this changed/improved. Also i will add the logs you propose 🙂 

But i'm not sure how valid is the point with "not being able to catch the termination".. I'm pretty new to Kube (I've been using Mesos for years), but in the end, there must be a place somewhere in the kubelet, where Kube is waiting for the given pod's process to terminate (`wait $pid`) - and receive the exitcode there.

Btw, I haven't seen this issue with pod terminations/crashes during its normal lifetime (like when I force the process to end with 0 or when the process crashes on internal error/memory/whatever). We always see the terminal status update. This problem occurs only during the described deployment upgrade.

**Comment by bydga** [comment]
@codearky here is the syslog from the "faulty" upgrade

quick summary:
- 3 pods were running:
    - `hera-example-api-kube-bydga-daemon-695b4c6f9-4hlss`
    - `hera-example-api-kube-bydga-daemon-695b4c6f9-6vt29`
    - `hera-example-api-kube-bydga-daemon-695b4c6f9-t594g`
- they were replaced during the uprade to 3 new ones:
    - `hera-example-api-kube-bydga-daemon-85949bbbc4-v5955`
    - `hera-example-api-kube-bydga-daemon-85949bbbc4-rzwfl`
    - `hera-example-api-kube-bydga-daemon-85949bbbc4-l9b5k`
    
- the one which failed to report the exitcode is the `hera-example-api-kube-bydga-daemon-695b4c6f9-6vt29`


I'm attaching 2 syslogs, because we had two servers for this test. The faulty pod is in the first one:
[syslog1.txt](https://github.com/kubernetes/kubernetes/files/6998030/syslog1.txt)
[syslog2.txt](https://github.com/kubernetes/kubernetes/files/6998055/syslog2.txt)

also the output of this current `kubectl get pods -w`:
[watchpods.txt](https://github.com/kubernetes/kubernetes/files/6998063/watchpods.txt)

**Comment by codearky** [comment]
@bydga Thanks for the cooperation.
 I've looked into the logs and I see kubelet did catch the transition of state of the faulty container  -

>  Aug 16 13:29:14 ip-10-64-69-89 kubelet-eks.daemon[6311]: I0816 13:29:14.306020    6311 generic.go:155] GenericPLEG: 140ee325-67d6-4731-ac23-8024abb6abc3/134f6035af42b783213eb020a962d8436e9ef43a0b11e12c33ff7a28c6692145: running -> exited

But we never actually updated `status_manager` with this tranistion. Why? It's hard to tell.
I see on line 608 we queue a pod sync loop which suppose to catch this event, and update the status manager as part of the iteration. We see another loop is queued in line 646, and again it does not seem to begin its run and update the  `status_manager` (although a new status is being written to the cache, and should trigger an iteration which should catch the exited container status - line 642). Just right after we update the cache again with a new status (line 739) we see all these qeued iteration begin running (i.e. we only now generate the api status and update `status_manager` with it)
, but this time the container already in a non-existent status (line 731) and it seems to take this latest status. So we actually never caught the termination.


As mentioned, it's hard for me to tell where the problem relies as I cannot reproduce this issue (using local cluster v1.19.3) and instrument the code with additional logs. But since multiple changes were introduced to this code, including those from #95561 (which seems to provide some defense mechanism agianst these kind of problems), I suggest to upgrade your cluster and report here the results so we can keep from there

Thanks!

**Comment by bydga** [comment]
Hi, long time no see 🙂  We managed to upgrade the cluster to `v1.21.2-eks-0389ca3`. And since this is the last kube release supporting docker as a container runtime, we also switched to containerd runtime (we were kinda hoping that the this error happens somewhere in the docker-shim and it will vanish with this shift 🙂 ). However no, it is still there. :/ 

Anyways, after upgrading, we still see the problem. I'm attaching the logs again:
[kubelet.log](https://github.com/kubernetes/kubernetes/files/7128860/kubelet.log)
[watch.log](https://github.com/kubernetes/kubernetes/files/7128862/watch.log)

3 (old) pods were running:
- hera-example-api-kube-bydga-api-5d96786949-brzmh
- hera-example-api-kube-bydga-api-5d96786949-9jvzq
- hera-example-api-kube-bydga-api-5d96786949-h2c94

and 3 new ones started:
- hera-example-api-kube-bydga-api-f6c5455fb-7kksk
- hera-example-api-kube-bydga-api-f6c5455fb-965s5
- hera-example-api-kube-bydga-api-f6c5455fb-2pg8m

the faulty one that reported the error like:
```
"containerStatuses": [
        {
          "image": "696577169457.dkr.ecr.us-west-2.amazonaws.com/hera/example-api/kube-bydga:3a690712",
          "imageID": "",
          "lastState": {
            "terminated": {
              "exitCode": 137,
              "finishedAt": null,
              "message": "The container could not be located when the pod was deleted.  The container used to be Running",
              "reason": "ContainerStatusUnknown",
              "startedAt": null
            }
          },
          "name": "api",
          "ready": false,
          "restartCount": 0,
          "started": false,
          "state": {
            "waiting": {
              "reason": "ContainerCreating"
            }
          }
        }
      ],
```

was the `hera-example-api-kube-bydga-api-5d96786949-brzmh`

I have to admit, that after upgrading the issue started to happen less often. But since we are just testing it, we don't have significant amount of deploys to make any conclusions. But let's say from 10 Deployment updates the issue happened twice.

**Comment by bydga** [comment]
Hi, I'm sad that despite the fact you guys confirmed and reproduced the bug, it got rotten and closed :/ I now encountered it it even on Job entity - we ran a job and were unable to process/read the exitcode how the job finished. This is a bit pain for our developers as they submit a job to the cluster, wait several hours for the job to finish, and then they receive an error (even though the task itself almost surely succeeded). 
I'm attaching output of `kubectl get pod custom-job-789zw-gfhff -o json --output-watch-events -w`

The job starts (ADDED event, then it gets MODIFIED to scheduled, ContainerCreating, running). And then, when the job finishes, we receive again this weird watch event:
```js
containerStatuses: [
{
	name: 'job',
	state: {
		waiting: {
			reason: 'ContainerCreating',
		},
	},
			

	lastState: {
		terminated: {
			exitCode: 137,
			reason: 'ContainerStatusUnknown',
			message:
				'The container could not be located when the pod was deleted.  The container used to be Running',
			startedAt: null,
			finishedAt: null,
		},
	},
	ready: false,
	restartCount: 0,
	image: 'xxx.dkr.ecr.eu-central-1.amazonaws.com/internal-image:1234',
	imageID: '',
	started: false,
},
]
```


It doesn't make any sense for the pod to be in the ContainerCreating state again (after termination). We have `restartPolicy=Never` and `backoffLimit=0`. It has to fail or succeed in the end.


[log.txt](https://github.com/kubernetes/kubernetes/files/9643519/log.txt)

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten
/triage accepted
/priority important-longterm

this may create a challenge for this KEP: https://github.com/kubernetes/enhancements/issues/3329 

@bydga is it 1.21 or some later version? Any chance you can try it on one of the supported versions?

**Comment by bydga** [comment]
Hi, thanks for the quick reply 🙂 This is currently 1.21 (aws eks), but we will be upgrading in a week. Once we have the newer version, i will retest and share the results 👍

**Comment by mimowo** [comment]
@SergeyKanzhelev @bydga I have scripted reproducing of the issue and confirmed it on 1.21 and 1.22. 
However, it appears fixed on 1.23 and 1.25. 

To reproduce I run 10 retries of create / replace / delete a deployment and check if the output (`out.txt`, see below) contains "The container could not be located when the pod was deleted" or "ContainerStatusUnknown".

On one terminal I run:
```sh
kubectl get pods --output json --watch-only --output-watch-events | jq 'del(.object.metadata.managedFields)' | tee out.txt
```

on the other terminal run `python repro.py` against a cluster with 3 nodes:
```python
import os, time

TMP_KUBE_BUILD = "/tmp/cmd-0123"

def exec_cmd(cmd):
    print("----")
    print(cmd)
    exitCode = os.system(cmd)
    print("exit code: ", exitCode)
    print("----")
    return exitCode

def is_clean(exp_running = 3):
    exec_cmd("kubectl get pods | tee %s" % TMP_KUBE_BUILD)
    with open(TMP_KUBE_BUILD) as file:
        lines = file.readlines()
        running_count = 0
        for line in lines:
            if "Running" in line:
                running_count += 1
        return running_count == exp_running and len(lines) == exp_running + 1

def await_clean(exp_running = 3):
    is_clean_tmp = False
    while not is_clean_tmp:
        is_clean_tmp = is_clean(exp_running)
        time.sleep(1.0)

if __name__ == "__main__":
    for i in range(0, 10):
        print("=============================== START: " + str(i))
        if exec_cmd("kubectl create -f deployment.yaml") != 0:
            continue
        await_clean()
        if exec_cmd("kubectl replace -f deployment-up.yaml") != 0:
            continue
        await_clean()
        if exec_cmd("kubectl delete -f deployment.yaml") != 0:
            continue
        print("=============================== END: " + str(i))
```

**Comment by SergeyKanzhelev** [comment]
> Hi, thanks for the quick reply 🙂 This is currently 1.21 (aws eks), but we will be upgrading in a week. Once we have the newer version, i will retest and share the results 👍

Looking forward for update. Based on @mimowo I will change it to needs information as it seems to be fixed

/triage needs-information

**Comment by haircommander** [comment]
Is this still an issue? Last we heard it was happening on 1.21, a very old version at the time of writing this comment

**Comment by bydga** [comment]
We currently run AWS EKS `v1.28.8` and I can't see this issue in our logs anymore. So hopefully this issue is gone 🍀
