### ISSUE TITLE
Pod sandbox creation fails when Namespace name + Pod name is more than 217 characters 

### ISSUE THREAD

**Issue by triii10** [kubernetes/kubernetes#104288]
#### What happened:

DNS Subdomain name standard allows the maximum length of the Pod name to be 253 characters.
However, Pod sandbox creation fails when Namespace name + Pod name is greater than 217 characters. 

```
Events:
  Type     Reason                  Age                         From               Message
  ----     ------                  ----                        ----               -------
  
  Warning  FailedCreatePodSandBox  <invalid> (x22 over 4m31s)  kubelet            Failed to create pod sandbox: mkdir /var/log/pods/long-name_thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpodthisisalong-verylong_19d86838-b886-467b-9579-3d31710d3607: file name too long
```

#### What you expected to happen:

Pod creation should succeed if name length satisfies the DNS subdomain name standard.

#### How to reproduce it (as minimally and precisely as possible):

```
$ kubectl create -f long-pod-stateless.yaml -n long-name
pod/thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpodthisisalong-lon created
```

#### Anything else we need to know?:

```
$ cat long-pod-stateless.yaml
apiVersion: v1
kind: Pod
metadata:
  name: thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpodthisisalong-lon
  labels:
    app: long-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
```

Pod name - thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpodthisisalong-lon
Namespace name - long-name

Sum of name length = 209 + 9 = 218

Creating Pod with length 208 + namespace 9 characters (total 217) succeeds :

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  22s   default-scheduler  Successfully assigned long-name/thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpod-thisisalongpodthisisalong-lo to <hostname>
  Normal  Pulling    3s    kubelet            Pulling image "nginx:latest"
  Normal  Pulled     0s    kubelet            Successfully pulled image "nginx:latest" in 3.7048188s
  Normal  Created    0s    kubelet            Created container nginx
  Normal  Started    0s    kubelet            Started container nginx
```

#### Environment:
- Kubernetes version (use `kubectl version`):

> Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c6a2f08fc4378c5381dd948d9ad9d1080e3e6b33", GitTreeState:"clean", BuildDate:"2021-05-12T12:19:22Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
> 

- OS (e.g: `cat /etc/os-release`): 

> 
> NAME="CentOS Linux"
> VERSION="8 (Core)"
> ID="centos"
> ID_LIKE="rhel fedora"
> VERSION_ID="8"
> PLATFORM_ID="platform:el8"
> PRETTY_NAME="CentOS Linux 8 (Core)"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:centos:centos:8"
> HOME_URL="https://www.centos.org/"
> BUG_REPORT_URL="https://bugs.centos.org/"
> 
> CENTOS_MANTISBT_PROJECT="CentOS-8"
> CENTOS_MANTISBT_PROJECT_VERSION="8"
> REDHAT_SUPPORT_PRODUCT="centos"
> REDHAT_SUPPORT_PRODUCT_VERSION="8"
> 

- Kernel (e.g. `uname -a`):

> Linux hostname 4.18.0-147.5.1.el8_1.x86_64 #1 SMP Wed Feb 5 02:00:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

/sig apps

**Comment by nicolai92** [comment]
If you check the warning message in your first code block, you can see that Kubernetes tries to create a path and a file on the host machine for the pod, that you want to deploy. The name of the pod is used as a filename. My guess is, that you reached the limit of the file name's length on the host OS - which is for ext4 file systems 255 bytes.

**Comment by kow3ns** [comment]
This feature is managed by sig-node. I'm not actually sure if this is a known constraint or a bug.
