### ISSUE TITLE
kube-proxy should log the payload when iptables-restore fails 

### ISSUE THREAD

**Issue by cchxn258886** [kubernetes/kubernetes#104234]
my k8s cluster version is 1.17.x 。this cluster has 10 nodes.one master 。
only  2 nodes get problem.
```go
E0809 05:37:21.484590       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 05:37:21.484752       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:14:37.485082       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 53 failed
)
I0809 06:14:37.485205       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:45:24.676775       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 53 failed
)
I0809 06:45:24.676868       1 proxier.go:779] Sync failed; retrying in 30s
E0809 06:45:38.141258       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 52 failed
)
I0809 06:45:38.141408       1 proxier.go:779] Sync failed; retrying in 30s
E0809 07:32:42.616867       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 52 failed
)
I0809 07:32:42.617009       1 proxier.go:779] Sync failed; retrying in 30s
E0809 07:42:13.864568       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 07:42:13.864698       1 proxier.go:779] Sync failed; retrying in 30s
E0809 08:00:20.842378       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 08:00:20.842502       1 proxier.go:779] Sync failed; retrying in 30s
E0809 08:06:32.562513       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 51 failed
)
I0809 08:06:32.562665       1 proxier.go:779] Sync failed; retrying in 30s
```
it make my svc sometime can use。sometime can timeout。
what can i do can resolve this problem ? 
this 2 node's svc is nodeportType 。

**Comment by cchxn258886** [comment]
@Network

**Comment by aojea** [comment]
you can increase kube-proxy verbosity adding `-v7` flag and you should get more information about the cause of the error

Kubernetes 1.17 is EOL, so you should upgrade to 1.19 at least https://kubernetes.io/releases/

**Comment by cchxn258886** [comment]
> you can increase kube-proxy verbosity adding `-v7` flag and you should get more information about the cause of the error
> 
> Kubernetes 1.17 is EOL, so you should upgrade to 1.19 at least https://kubernetes.io/releases/

hello bro。my cluster is use kubeadm init .so what should i do .i know this is use configmap 。but in this i can not found how edit this configmap is available？about upgrade this cluster .this time is impossible。

**Comment by cchxn258886** [comment]
> you can increase kube-proxy verbosity adding `-v7` flag and you should get more information about the cause of the error
> 
> Kubernetes 1.17 is EOL, so you should upgrade to 1.19 at least https://kubernetes.io/releases/

about stack. i only get this log.
```go
 11:25:38.390292       1 proxier.go:779] Sync failed; retrying in 30s
E0805 11:36:18.240849       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 46 failed
)
I0805 11:36:18.240985       1 proxier.go:779] Sync failed; retrying in 30s
W0805 11:45:14.938674       1 server_others.go:323] Unknown proxy mode "", assuming iptables proxy
I0805 11:45:14.951384       1 node.go:135] Successfully retrieved node IP: 10.60.44.71
I0805 11:45:14.951437       1 server_others.go:145] Using iptables Proxier.
I0805 11:45:14.951948       1 server.go:571] Version: v1.17.2
I0805 11:45:14.952618       1 conntrack.go:52] Setting nf_conntrack_max to 655360
I0805 11:45:14.953070       1 config.go:131] Starting endpoints config controller
I0805 11:45:14.953105       1 config.go:313] Starting service config controller
I0805 11:45:14.953143       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
I0805 11:45:14.953144       1 shared_informer.go:197] Waiting for caches to sync for service config
I0805 11:45:15.053346       1 shared_informer.go:204] Caches are synced for endpoints config 
I0805 11:45:15.053355       1 shared_informer.go:204] Caches are synced for service config 
E0805 11:46:53.104982       1 proxier.go:1507] Failed to execute iptables-restore: exit status 1 (iptables-restore: line 47 failed
)
```

**Comment by aojea** [comment]
To increase the verbosity on kube-proxy on a kubeadm deployment you can do
```
 kubectl patch -n kube-system daemonset/kube-proxy \
    --type='json' -p='[{"op": "add", "path": "/spec/template/spec/containers/0/command/-", "value": "--v=7" }]'
```
and wait until pods are restarted.

Despite that, if there is a bug, it will not be backported to 1.17, so you have to go to a supported version first

**Comment by thockin** [comment]
I *swear* we added code to dump the ruleset when this happens, but I don't see it any more.

**Comment by thockin** [comment]
I'm going to re-purpose this as a feature :)

**Comment by bhumijgupta** [comment]
Hi, I would like to pick this up. Can someone give me some code pointers on where to start?

**Comment by rajibmitra** [comment]
Let me know if I can help in anyway. @thockin

**Comment by thockin** [comment]
I'd start with pkg/util/iptables/iptables.go - `restoreInternal()`

It's worth thinking about the cleanest solution here, but maybe something like:

```
type ParseError interface {
    Line() Int
}

type parseError struct {
    cmd string
    line int
}

func (e parseError) Line() int {
    return line
}

func (e parseError) Error() string {
    return fmt.Sprintf("%s: parse error on line %d", e.cmd, e.line)
} 
```

When you get an error from exec, parse the error for `line %d failed` and if it matches, return a `parseError`.  Then let the callers check for a `ParseError` by interface assertion, extract the Line(), extract their input's data at -3 and +3 from that line and log it.  E.g.

```
 Failed to execute iptables-restore: input error on line 1234:
    1231: ...
    1232: ...
    1233: ...
    1234: ...
    1235: ...
    1236: ...
    1237: ...
```

You'll proably want a helper func to do that, which could live in that same iptables package.  And a test.

**Comment by cyclinder** [comment]
hi everyone!

Is anyone doing this? I am willing to do this！

**Comment by aojea** [comment]
at least I didn't see any PR from @amustaque97 , in case of collision please sync between both to avoid duplicate efforts

**Comment by amustaque97** [comment]
Hi @cyclinder, apologies I was busy with some other work. You must please continue.

**Comment by cyclinder** [comment]
thanks @amustaque97

**Comment by cyclinder** [comment]
> extract the Line(), extract their input's data at -3 and +3 from that line and log it. E.g.

I'm working on this now, but  I'm stuck in here,  I got the line, and then how I extract `proxier.iptablesData.Bytes()` at -3 and +3 from that line?

**Comment by arun1587** [comment]
> You'll proably want a helper func to do that, which could live in that same iptables package. And a test. 


you may need to write a helper function to extract them from the logs.
my 2 cents..
here is my version for reference.
you could add some tests, to cover the boundary conditions.
```
const delimiter = 0x0a

func extratLines(limit, lineNumber int, lines []byte) string {
	lineBytes := bytes.Split(lines, []byte{delimiter})

	count := len(lineBytes)
	var extractedLines bytes.Buffer

	// validate boundary limits
	start := max(lineNumber-limit, 0)
	end := min(lineNumber+limit, count-1)

	for i := start; i <= end; i++ {
		extractedLines.WriteString(string(lineBytes[i]) + "\n")
	}

	return extractedLines.String()
}

func max(a, b int) int {
	if a > b {
		return a
	}

	return b
}

func min(a, b int) int {
	if a < b {
		return a
	}

	return b
}
