### ISSUE TITLE
`k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts` `TestDownloadCerts` fails

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#104265]
#### Which jobs are failing:

Running `make test` locally.

#### Which test(s) are failing:

`k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts` `TestDownloadCerts`

#### Since when has it been failing:

Today?

#### Testgrid link:

There is none, but I'm not filing this as a flaking test because it's a dependable failure, not a flake.

#### Reason for failure:

I suspect this depends on the user's umask given the error:
```
--- FAIL: TestDownloadCerts (0.15s)
    copycerts_test.go:255: cert "ca.crt" should have mode 0644, has 0640
    copycerts_test.go:255: cert "front-proxy-ca.crt" should have mode 0644, has 0640
    copycerts_test.go:255: cert "sa.pub" should have mode 0644, has 0640
    copycerts_test.go:255: cert "etcd/ca.crt" should have mode 0644, has 0640
FAIL
FAIL	k8s.io/kubernetes/cmd/kubeadm/app/phases/copycerts	0.612s
ok  	k8s.io/kubernetes/cmd/kubeadm/app/phases/etcd	(cached)
```

#### Anything else we need to know:
originally https://github.com/kubernetes/kubernetes/issues/102607#issuecomment-895753987

/area kubeadm
/sig cluster-lifecycle

**Comment by neolit123** [comment]
there were related changes to TestDownloadCerts last month:
https://github.com/kubernetes/kubernetes/commit/5c00024c70bee36d12a1a5293a1940f2bb7de95b

we could pin the mode for these newly created files in kubeadm.
/triage accepted

**Comment by neolit123** [comment]
but the problem seems odd.

kubeadm uses client-go utils for writing a cert file with mode 644:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/staging/src/k8s.io/client-go/util/cert/io.go#L61-L70

i don't understand why something would override this mode to 0640.

**Comment by BenTheElder** [comment]
>i don't understand why something would override this mode to 0640.

From the initial issue filing:
> I suspect this depends on the user's umask given the error:

https://en.wikipedia.org/wiki/Umask -- users may be running in an environment with a less permissive umask, but the test depends on a full permissive umask. https://stackoverflow.com/questions/10220531/how-to-set-system-wide-umask

**Comment by neolit123** [comment]
ok, right.

https://man7.org/linux/man-pages/man2/open.2.html


```
              The effective mode is modified by the process's umask in
              the usual way: in the absence of a default ACL, the mode
              of the created file is (mode & ~umask).
```

a quick fix would be to get the current process umask and expect it to be applied to the file permissions:

```
// in TestDownloadCerts
current := syscall.Umask(0) // get the current process mask, while setting it to 0
syscall.Umask(current) // restore it
....

const certFileMode = 0644 & current

but note:
https://man7.org/linux/man-pages/man2/umask.2.html

```
       It is impossible to use umask() to fetch a process's umask
       without at the same time changing it.  A second call to umask()
       would then be needed to restore the umask.  The nonatomicity of
       these two steps provides the potential for races in multithreaded
       programs.
```

**Comment by BenTheElder** [comment]
I think it would be reasonable to just set umask without getting it in the TestMain for the package.

IIRC go runs tests as a binary / process per package, so it would only affect that package.

We could make setting the umask only happen on unix without making the tests unix only as well, by using a conditionally compiled wrapper.

I can send a PR for this, I suspect the system umask is google's workstation customization (~~debian testing), and probably relatively unusual elsewhere. I recall now we've run into this in the past during builds where e.g. `COPY` does not result in the permissions on other systems so we've added chmod to e.g. https://github.com/kubernetes-sigs/kind/issues/2138

**Comment by neolit123** [comment]
the test would fail on Windows because `os.Stat()` -> `stat.Mode()` would always return `-rw-rw-rw-` there.
so we should os-branch the `stat.Mode()` checks.

**Comment by BenTheElder** [comment]
I'm not sure I understand the windows part tbh, I think this particular failure can be addressed without affecting windows though.

After meetings I got around to confirming on my personal debian stable instance `umask` reports `0022` while on my "gLinux" (~debian testing) workstation it reports `0027`. AFAICT `0022` should be more or less the standard across distros but debian and ubuntu at least provide a mechanism out of the box to configure it for the system.

**Comment by neolit123** [comment]
yeah, the test is already broken on non-Unix, so we could just set the umask to make the test happy.
the non-Unix fix seems like something that can be done separately.

**Comment by BenTheElder** [comment]
filed https://github.com/kubernetes/kubernetes/pull/104284 to set it to 0 in test main so it would be technically not umask sensitive anymore on linux and macOS at least.
