### ISSUE TITLE
kubectl describe node have a error value. When looking at HugePage data, the data "hugepage-1Gi" and "hugepage-2Mi" are incorrect

### ISSUE THREAD

**Issue by zhougw001** [kubernetes/kubernetes#104295]
#### What happened:
I use "kubectl describe node node1" to check the value of HugePage, the data in Allocatable is incorrect. The hugepages-1Gi is not equal to the data in Allocated resources. I test some times, the data in Allocated resources is correct, the data in Capacity and Allocatable is error.
#### What you expected to happen:
The data "hugepages-1Gi" and "hugepages-2Mi" in Capacity/Allocatable is calculation error. 

#### How to reproduce it (as minimally and precisely as possible):
1.In a k8s cluster, select one node and set hugepage-1Gi
2.create a application and use hugepage
3.use "kubectl describe node node3" to check the hugepage use.
4. the data hugepage-1Gi in Allocatable is error,  no matter how much the hugepage is used , the value is not change.
#### Anything else we need to know?:
It's a time-honored bug
#### Environment:
- Kubernetes version (use `kubectl version`):  all version， I use 1.20.1
- Cloud provider or hardware configuration:
-cpu : 16core
memory: 32G
storega: 1T
- OS (e.g: `cat /etc/os-release`):CentOS 7 
- Kernel (e.g. `uname -a`):root
- Install tools:
- ansiable
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

At minimum, please paste the full output of `kubectl describe node` with the expected and actual behaviour.

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by zhougw001** [comment]
![pic1](https://user-images.githubusercontent.com/49544454/129502135-a77dbfc1-4fb8-4446-8591-4c0a9b6023c9.jpg)
![pic2](https://user-images.githubusercontent.com/49544454/129502143-a3123dac-852f-41f4-9738-32567429685e.jpg)

**Comment by ehashman** [comment]
Allocatable does not refer to how much resources are in use by your node. It refers to how many resources are available for the kubelet to allocate, given the limits for system reserved specified. In this case, all hugepages on the system are allocatable, none were reserved.

Consider this trivial example of a local-up-cluster with no system reserved specified that has a single 1 CPU pod scheduled; allocatable is equal to capacity:

```
Capacity:
  cpu:                16
  ephemeral-storage:  177630116Ki
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             65562276Ki
  pods:               110
Allocatable:
  cpu:                16
  ephemeral-storage:  163703914635
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             65459876Ki
  pods:               110
...
Non-terminated Pods:          (2 in total)
  Namespace                   Name                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                        ------------  ----------  ---------------  -------------  ---
  default                     restart-0                   1 (6%)        1 (6%)      40Mi (0%)        40Mi (0%)      10s
```

/close

Not a bug.
