### ISSUE TITLE
ci-kubernetes-node-swap-fedora: timeout when querying /stats/summary should report resource usage through the stats api  

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#104292]
#### Which jobs are failing:

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora

#### Which test(s) are failing:
 when querying /stats/summary should report resource usage through the stats API 

#### Since when has it been failing:
always failed

#### Reason for failure:
```
E2eNode Suite: [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api expand_less | 2m3s
-- | --
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54 Timed out after 90.001s. Expected     <string>: Summary to match fields: { [.Pods[summary-test-873::stats-busybox-0].Network: 	Expected 	    <*v1alpha1.NetworkStats \| 0x0>: nil 	not to be <nil>, .Pods[summary-test-873::stats-busybox-1].Network: 	Expected 	    <*v1alpha1.NetworkStats \| 0x0>: nil 	not to be <nil>] }  _output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:347
```

#### Anything else we need to know:
#103842  fixed similar issue #100788 in 1.23 which was also cherry-picked to 1.22
 
/cc  @bobbypage @ehashman

**Comment by pacoxu** [comment]
/sig node

Some failure of cadvisor in kubelet log: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-fedora/1425288171079340032
```
  219  W0811 03:03:43.166504    4067 sysinfo.go:394] Cannot read core id for /sys/devices/system/node/node0/cpu1, core_id file does not exist, err: open /sys/devices/system/node/node0/cpu1/topology/core_id: no such file or directory
>   221: I0811 03:03:43.172187    4067 manager_no_libpfm.go:28] cAdvisor is build without cgo and/or libpfm support. Perf event counters are not available.
>   222: I0811 03:03:43.182227    4067 manager.go:229] Version: {KernelVersion:5.13.4-200.fc34.x86_64 ContainerOsVersion:Fedora CoreOS 34.20210725.3.0 DockerVersion:20.10.7 
> 
> E0811 03:04:03.781355    4067 cadvisor_stats_provider.go:415] "Partial failure issuing cadvisor.ContainerInfoV2" err="partial failures: [\"/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-podd392b244_3573_4580_b4d7_0115251a92d6.slice/crio-ae54da2e426d366df9baabeab3de98d1aa451e327112123d4cf05a9f7b5f1549.scope\": RecentStats: unable to find data in memory cache]"
> 
> E0811 03:04:54.238504    4067 cadvisor_stats_provider.go:147] "Unable to fetch pod log stats" err="open /var/log/pods/projected-2404_pod-projected-configmaps-777ff801-b2d2-4e2b-a267-861229cf0491_6f4cd5b3-2a3a-4219-85bf-b6bb7c9fd4b5: no such file or directory" pod="projected-2404/pod-projected-configmaps-777ff801-b2d2-4e2b-a267-861229cf0491"

**Comment by ehashman** [comment]
/triage accepted

might be an issue with the fedora image?

**Comment by ehashman** [comment]
/kind flake
/remove-kind failing-test

I see looking more closely at the Fedora and Ubuntu jobs that this is flaking and not failing every time, it's just flaking the majority of the time.

**Comment by liggitt** [comment]
this is flaking frequently... seeing it multiple times on PRs

**Comment by liggitt** [comment]
oh.. well... I'm seeing this test flake, but on the presubmit containerd job

**Comment by liggitt** [comment]
https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=when%20querying%20%2Fstats%2Fsummary

**Comment by liggitt** [comment]
failing batch merges as well - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-node-e2e-containerd/1455925147750895616/

**Comment by pacoxu** [comment]
/cc @rphillips

Just find something that may be related:

> W1103 16:01:12.372689    1178 container.go:586] Failed to update stats for container "/kubepods/besteffort/pod2eda2178-023e-4bfb-82e0-caaff9bad1a5": /sys/fs/cgroup/cpuset/kubepods/besteffort/pod2eda2178-023e-4bfb-82e0-caaff9bad1a5/cpuset.cpus found to be empty, continuing to push stats

https://bugzilla.redhat.com/show_bug.cgi?id=1733571

/area cadvisor

**Comment by SergeyKanzhelev** [comment]
@bobbypage are you looking into it? Or should we try to find a new owner?

**Comment by ehashman** [comment]
/unassign @bobbypage 

Clearing assignees for this release, please reassign if you have the bandwidth to complete this.

**Comment by pacoxu** [comment]
[pull-kubernetes-node-swap-fedora](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-swap-fedora) always failed
and so does [pull-kubernetes-node-swap-ubuntu](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-swap-ubuntu).

**Comment by ehashman** [comment]
Appears to be fixed on Fedora, but not on Ubuntu. Progress!

/assign @mmiranda96

**Comment by pacoxu** [comment]
Any update on this?

**Comment by mmiranda96** [comment]
Testgrid has been green for more than a week now. I think this is fixed.
/close
