### ISSUE TITLE
Kubernetes apply command produces 'wrong encoding error'

### ISSUE THREAD

**Issue by virtyos** [kubernetes/kubernetes#104249]
I'm trying to execute `microk8s kubectl apply -f  deployment.yaml` and always getting

`error: string field contains invalid UTF-8`
No matter what file I'm trying to use. Even if I execute

`microk8s kubectl apply -f  blablabla`
Result is the same

**Comment by neolit123** [comment]
hi, please report this to microk8s first:
https://github.com/ubuntu/microk8s
make sure you include the version too.

to discuss with other users, use the k8s support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
