### ISSUE TITLE
revisit `PodEligibleToPreemptOthers` func from default preemption

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#104266]
#### What happened:
As the comment here explained, the logic of `PodEligibleToPreemptOthers` func from default preemption is not accurate enough, the deleting pod should be a preemption victim instead of normal deleted pod.
https://github.com/kubernetes/kubernetes/pull/104030#discussion_r680138858

Quote from @Huang-Wei 

> PodEligibleToPreemptOthers currently checks if a nominated node has low-priority terminating pods, then it assumes those terminating pods are preempted by the preemptor. It's actually not that accurate - we should verify the terminating pods are exactly preemption victims; otherwise a possible case is: the victims have been physically deleted, and the terminating pods are due to regular deletion.

#### What you expected to happen:
Refine the logic to make sure the deleting pod is actually a preemption victim.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

cc @alculquicondor 

/sig scheduling

**Comment by alculquicondor** [comment]
Do we have a way to tell? Add a Pod condition perhaps? Is it worth the extra API call?

**Comment by Huang-Wei** [comment]
It doesn't worth an extra API call.

A possible way is to handle it in [nominator](https://github.com/kubernetes/kubernetes/blob/95ff56c201ae7ccdcd1f01bc36646d1d6496483a/pkg/scheduler/internal/queue/scheduling_queue.go#L828), by introducing a `nominatedPodToVictims` map.

**Comment by alculquicondor** [comment]
But then it has to be best effort (in case kube-scheduler restarts). What would happen if the information is not present?

**Comment by Huang-Wei** [comment]
> But then it has to be best effort (in case kube-scheduler restarts).

Yes.

> What would happen if the information is not present?

It would fall back to the current logic - once a nominated pod finds terminating and low-priority pods on a node, it doesn't proceed preemption attempt on that node.

**Comment by chendave** [comment]
/close 

As already said, this will introduce extra state and complexity to handle, close for now, maybe the issue will gone alone the way ahead. :)

**Comment by Huang-Wei** [comment]
/reopen

Given `PodDisruptionConditions` is in place, we have a clear API field to tell whether a terminating Pod is caused by scheduler preemption.

```console
# running in k8s 1.26
# pause2 tries to preempt pause1
⇒  k get po
NAME     READY   STATUS        RESTARTS   AGE
pause1   1/1     Terminating   0          8m47s
pause2   0/1     Pending       0          2m46s
```

```console
# pause1's condition
⇒  k get po pause1 -o json | jq '.status.conditions[] | select(.type=="DisruptionTarget")'
{
  "lastProbeTime": null,
  "lastTransitionTime": "2022-12-20T22:45:55Z",
  "message": "Kube-scheduler: preempting to accommodate a higher priority pod: default/pause2",
  "reason": "PreemptionByKubeScheduler",
  "status": "True",
  "type": "DisruptionTarget"
}
```
