### ISSUE TITLE
Documentation snapshots for version prior to `1.17` are served with an invalid certificate

### ISSUE THREAD

**Issue by Horgix** [kubernetes/kubernetes#104241]
#### What happened:

When trying to view Kubernetes documentation snapshots for versions prior to `1.17`, it is served using a generic Netlify TLS certificate, therefore not matching the doc domain, and thus ending up in a browser warning:

![screenshot_2021-08-09-151254_915x660_selection](https://user-images.githubusercontent.com/4584397/128712867-3611e1c7-415a-4eab-a19d-cd0a82d42d90.png)

#### What you expected to happen:

Have the doc served over HTTPS with a valid certificate :slightly_smiling_face: 

#### How to reproduce it (as minimally and precisely as possible):

Visit one of the following doc pages :

- https://v1-16.docs.kubernetes.io/
- https://v1-15.docs.kubernetes.io/
- https://v1-15.docs.kubernetes.io/

etc.

Note that doc with the same pattern starting at 1.17 are fine: https://v1-17.docs.kubernetes.io/

These domain were also once valid, since I just figured it out by re-opening old tabs in my browser.

**Comment by neolit123** [comment]
please log this in the kubernetes/website repository where the website source is.

/kind documentation
/close

**Comment by Horgix** [comment]
> please log this in the kubernetes/website repository where the website source is.

My bad, will do. Thanks!
