### ISSUE TITLE
Master logs not uploaded on successful e2e runs or failed test -up

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#10423]
We [dump master logs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/core.go#L32) for uploading to GCS on [failed e2e runs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/e2e_test.go#L150), but not on successful e2e runs or failed test -up.

We should definitely be dumping those logs for failed cluster-ups, and it would also be nice to throw in the successes too (good to have recent green for comparison).

**Comment by cjcullen** [comment]
@ixdy @quinton-hoole

**Comment by roberthbailey** [comment]
Getting logs uploaded on a failed test -up seems really important for debugging.

**Comment by wojtek-t** [comment]
+1
There were just a bunch of failures in scalability test suite (run 1623-1628) that failed because not all system pods were running. Since there are no logs, there is no easy way to debug it.

It would be super useful to have all the logs for failed cluster-ups.

cc @davidopp

**Comment by quinton-hoole** [comment]
Unless I'm confused, it looks as if these logs are still not being uploaded.  @dchen1107 @ixdy FYI.

**Comment by quinton-hoole** [comment]
For example:

gs://kubernetes-jenkins/logs/kubernetes-e2e-gce/7500

**Comment by ixdy** [comment]
That particular build was a timeout. When Jenkins kills the job, the log-collecting code never runs.

**Comment by ixdy** [comment]
Another case we won't collect logs is if the cluster fails to initialize. (Which is a really important place to collect logs, but it's not a trivial fix.)

**Comment by brendandburns** [comment]
Moving this into post, since it seems unlikely to get fixed in the near term.  @ixdy feel free to correct me if I'm wrong.

**Comment by ixdy** [comment]
We also don't collect logs on test job timeouts, which is frustrating.

**Comment by wojtek-t** [comment]
>
We also don't collect logs on test job timeouts, which is frustrating.

+1

**Comment by mml** [comment]
#21183 will collect the logs when the cluster fails to initialize.  That's not all the cases listed here, but it's a good one.

**Comment by gmarek** [comment]
I'd like to bump the priority for this further - we don't have any logs to help with debugging #18969, which started to happen more often recently - it seems that #21183 didn't help. cc @davidopp @mml @ixdy @fejta @wojtek-t

**Comment by ixdy** [comment]
I have too many P0s assigned to me already. This is at least 3rd in line right now.

**Comment by gmarek** [comment]
This one is half year old and is P0 for a month...

**Comment by ixdy** [comment]
From discussion with @spxtr on hangouts, a vague plan:
* move log-dumping logic from `test/e2e/core.go` into a standalone command in something like `cmd/dumplogs` (feel free to bikeshed the name)
* update Jenkins to call this command as a post-build step
* probably remove `test/e2e/core.go` and the debug stuff recently added to `cluster/gce/util.sh`.

Right now the `test/e2e/core.go` stuff is pretty GCE/GKE specific and uses ssh. We should probably change to a more provider-agnostic method, but this would be a good start.

**Comment by ixdy** [comment]
Hm, actually, post-build step actually won't work, since we tear down the cluster first. But making it a separate command can still let us call it in more places.

**Comment by wojtek-t** [comment]
FYI - we also need logs from timed-out runs (not only the failed ones).

**Comment by ixdy** [comment]
@wojtek-t moving `test/e2e/core.go` out into its own binary should help accomplish this.

**Comment by spxtr** [comment]
I'm worried that the best way to do this is to write a bash script that grabs IPs from `cluster/{provider}/util.sh`'s `detect-master` and `detect-nodes` functions and just does an ssh and cats the logs. Then we could point `test/e2e/core.go` at that.

It's sorta difficult to make `test/e2e/core.go` work on its own.

**Comment by gmarek** [comment]
I think at this point we're happy with anything that usually works. We can work on making in nice and shiny later.

**Comment by spxtr** [comment]
We now get logs when kube-up fails, which recently happened [here](https://cloud.google.com/console/storage/kubernetes-jenkins/logs/kubernetes-e2e-gce/12631/) :)

Still some work to do here, I'll leave this issue open until timeouts are handled properly and `test/e2e/core.go` points here.

**Comment by gmarek** [comment]
@spxtr - I can't thank you enough!

**Comment by spxtr** [comment]
Ok, #22374 is in so we should get logs for kubernetes-e2e-* jobs and PR Jenkins jobs on timeout.

**Comment by spxtr** [comment]
I'm gonna call this done.
