### ISSUE TITLE
cgroup refresh after daemon-reload

### ISSUE THREAD

**Issue by AmazingPangWei** [kubernetes/kubernetes#104289]
#### What happened:
When I run kubelet on my CentOS7.7, I add some arguments as follows:
``` shell

"--system-reserved=cpu=3,memory=6Gi",
"--system-reserved-cgroup=/system.slice",
"--enforce-node-allocatable=pods,system-reserved"

```
then, I check memory limit like this:
``` shell

[root@vm ~]# cat /sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes 
6442450944

```
Everything is OK. But after that, I happen to execute `systemctl daemon-reload` and `systemctl restart my-service`。Next, I check memory limit again, but it has changed:
``` shell

[root@vm ~]# cat /sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes 
9223372036854771712

```

#### What you expected to happen:

So, is there a way to keep system.slice/ stable?

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Furthermore, you should include the full systemd service manifests. It's possible that the way you defined your restart command is incorrect. Can you show the full command line of the running kubelet process (e.g. using `ps`) before and after the service restart?

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by AmazingPangWei** [comment]
Thanks for your reply. Here is my cluster detail:
 
* OS：CentOS 7.7
* cluster version: v1.19.10
* container runtime: docker
* kubelet：run as container in docker
* kubelet comand line: 
``` shell
kubelet --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --pod-infra-container-image=xxx/mirrored-pause:3.2 --authentication-token-webhook=true --make-iptables-util-chains=true --volume-plugin-dir=/var/lib/kubelet/volumeplugins --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --cloud-provider= --fail-swap-on=false --anonymous-auth=false --streaming-connection-idle-timeout=30m --read-only-port=0 --cluster-domain=cluster.local --network-plugin=cni --resolv-conf=/etc/resolv.conf --cgroups-per-qos=True --authorization-mode=Webhook --cni-bin-dir=/opt/cni/bin --v=2 --cluster-dns=10.43.0.10 --hostname-override=vm-pw-k8s --address=0.0.0.0 --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --root-dir=/var/lib/kubelet --cni-conf-dir=/etc/cni/net.d --event-qps=0 --system-reserved=cpu=3,memory=6Gi --system-reserved-cgroup=/system.slice --enforce-node-allocatable=pods,system-reserved --cgroup-driver=cgroupfs
```

How to reproduce：

1. run kubelet as above
2. check `/sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes`, and its result is `6442450944`
3. run `systemctl daemon-reload`
4. run `systemctl restart` any serive, such as httpd, `systemctl restart httpd`
5. check `/sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes` again, and its result is `9223372036854771712`
6. after restarting kubelet, `/sys/fs/cgroup/memory/system.slice/memory.limit_in_bytes` is back to `6442450944`

**Comment by ehashman** [comment]
Ah, this seems like a race between the kubelet and the system daemon. We would not expect a system daemon restart as part of normal operations. Kubelet only sets this at startup. I'm not sure whether we would consider this a bug or not. Let me ask some folks...

/remove-triage needs-information

**Comment by SergeyKanzhelev** [comment]
/assign @swatisehgal 

/triage accepted

We still need to investigate whether this is a bug or expected behavior

**Comment by swatisehgal** [comment]
IIUC, this looks like a systemd issue to me as it should not touch cgroups that it didn't create and that is exactly what seems to be happening when `systemctl daemon-reload` is run.

**Comment by likakuli** [comment]
we met same problem. is there any update about why and how systemd do it?
