### ISSUE TITLE
Kompose generated  network YAML cannot  be applied because  there are o matches for kind "NetworkPolicy" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by ricjhill** [kubernetes/kubernetes#104221]
#### What happened:

In a powershell terminal from a dir containing  the  docker  compose file   [docker-compose.prod.yml](https://raw.githubusercontent.com/doccano/doccano/master/docker-compose.prod.ymll).  I ran the command 

`kompose convert -f .\docker-compose.prod.yml
`

I then applied  the manifests created to my local minkube cluster  

 
```
kubectl apply -f  .
deployment.apps/backend configured
deployment.apps/nginx configured
service/nginx configured
persistentvolumeclaim/postgres-data configured
deployment.apps/postgres configured
persistentvolumeclaim/static-volume configured
unable to recognize "network-backend-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"
unable to recognize "network-frontend-networkpolicy.yaml": no matches for kind "NetworkPolicy" in version "extensions/v1beta1"
```
 

The error messages were corrected by  updating the  API  version in the  yaml files "network-backend-networkpolicy.yaml" and  "network-frontend-networkpolicy.yaml"

From
`
apiVersion: extensions/v1beta1
`
to
`
apiVersion: networking.k8s.io/v1
`
#### What you expected to happen:

I expected kompose to create network YAMLs using apiVersion: networking.k8s.io/v1.

#### How to reproduce it (as minimally and precisely as possible):

See above

#### Environment:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
 
```
minikube version
minikube version: v1.22.0
commit: a03fbcf166e6f74ef224d4a63be4277d017bb62e
```

```
Device name	XXXX
Full device name	XXXXXX.aas.local
Processor	Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   2.00 GHz
Installed RAM	8.00 GB (7.82 GB usable)
Device ID	XXXXXXX
Product ID	XXXXXX
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

- OS (e.g: `cat /etc/os-release`):

> Edition	Windows 10 Pro
> Version	20H2
> Installed on	‎12/‎20/‎2020
> OS build	19042.1110
> Experience	Windows Feature Experience Pack 120.2212.3530.0

- Kernel (e.g. `uname -a`):
- Install tools:
chocolatey package manager

- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by aojea** [comment]
/close
this is not a kubernetes bug, yaml files should have the right version,  AFAIK kustomize only parses and modifies files .and kubernetes 1.22 doesn't support ingress v1beta1, it was announced in the release notes
