### ISSUE TITLE
"Kubelet fails to start if the SeccompDefault feature gate is enabled via the KubeletConfiguration file"

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#104298]
#### What happened:

Since Kubernetes 1.22.0, it's required to enable the `DynamicKubeletConfig` feature gate on Kubelet to use the `--dynamic-config-dir` flag. Enabling the feature gate via the KubeletConfiguration file causes Kubelet to fail to start. I've used a configuration file such as the following one:

```
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
featureGates:
  DynamicKubeletConfig: true
  RotateKubeletServerCertificate: true
...
```

I've got the following error when trying to start Kubelet:

```
Flag --dynamic-config-dir has been deprecated, Feature DynamicKubeletConfig is deprecated in 1.22 and will not move to GA. It is planned to be removed from Kubernetes in the version 1.23. Please use alternative ways to update kubelet configuration.
E0811 09:30:52.737166    7094 server.go:194] "Failed to validate kubelet flags" err="the DynamicKubeletConfig feature gate must be enabled in order to use the --dynamic-config-dir flag"
```

However, if I use the `--feature-gates` command-line flag instead of the KubeletConfiguration file, the Kubelet starts up properly. I've also found out that the same happens with the `SeccompDefault` feature gate and the `--seccomp-default` flag.

#### What you expected to happen:

Kubelet starts up properly if the `DynamicKubeletConfig` or `SeccompDefault` feature gate is enabled via the configuration file.

#### How to reproduce it (as minimally and precisely as possible):

1. Enable the `--dynamic-config-dir` flag on Kubelet
2. Enable the DynamicKubeletConfig feature flag via the configuration file
3. Try to start Kubelet

The same can be reproduced by using the `--seccomp-default` flag and the `SeccompDefault` feature gate.

#### Environment:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: AWS
- OS (e.g: `cat /etc/os-release`): 
     ```
     NAME="Ubuntu"
     VERSION="20.04.2 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.2 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     ```
- Kernel (e.g. `uname -a`): `Linux ip-172-31-187-253 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

/sig node
/area kubelet

**Comment by xmudrii** [comment]
I've created #104299 to try to solve this issue.

**Comment by SergeyKanzhelev** [comment]
/retitle "Kubelet fails to start if the SeccompDefault feature gate is enabled via the KubeletConfiguration file"

since we are removing DynamicKubeletConfig, renaming the issue to indicate that problem still exists

**Comment by SergeyKanzhelev** [comment]
/unassign @xmudrii

(based on PR comment, feel free to re-assign to yourself)

**Comment by vaibhav2107** [comment]
Hi @xmudrii, @SergeyKanzhelev 
Is this issue active to work on?

**Comment by xmudrii** [comment]
@vaibhav2107 From my side, I'm not working on it, so feel free to take it over.
