### ISSUE TITLE
[Failing test] [sig-node] Lock contention [Slow] [Disruptive] [NodeFeature:LockContention] Kubelet should stop when the test acquires the lock on lock file and restart once the lock is released

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#104307]
#### Which jobs are failing:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

#### Which test(s) are failing:

`[sig-node] Lock contention [Slow] [Disruptive] [NodeFeature:LockContention]` tests

#### Since when has it been failing:

08/11 ~2:30PDT
First fail run https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-features/1425389087623221248

#### Testgrid link:

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

#### Reason for failure:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/lock_contention_test.go:35
Timed out after 10.001s.
Expected
    <bool>: true
to be false
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/lock_contention_test.go:67
```

#### Anything else we need to know:

These tests appear to be newly added in https://github.com/kubernetes/kubernetes/pull/103608

They have never passed as far as I can tell. Not sure why this was merged/not caught in CI.

/cc @ipochi 
/sig node

**Comment by ipochi** [comment]
@ehashman 

Hi thanks for pointing out. 

I was looking at this https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-lock-contention

I thought I saw green runs in the latest tests.
Please.correct me if I am wrong.

**Comment by ehashman** [comment]
They're fine on that tab but they're broken in https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-features-master

**Comment by ehashman** [comment]
I'm puzzled why they're even getting pulled into that job since they're marked `Disruptive`...

**Comment by ehashman** [comment]
@ipochi why does this feature need its own separate job for a single test?

**Comment by ipochi** [comment]
> @ipochi why does this feature need its own separate job for a single test?

Apologies, I'm not sure of the conventions for the tests.

I wasn't given info/notified regarding this. Where else could I have put a test for this ?

**Comment by ehashman** [comment]
@ipochi since it's just the one test there are a number of jobs we could add this to. Let's discuss at the CI subproject tomorrow? I'll add this to the agenda.

**Comment by ipochi** [comment]
> @ipochi since it's just the one test there are a number of jobs we could add this to. Let's discuss at the CI subproject tomorrow? I'll add this to the agenda.

When does the CI subproject happen ? 
If it fits the timezone, if like to atttend.

I'd very much like to re-revert the changes and out this test in proper place with green runs

**Comment by ehashman** [comment]
> When does the CI subproject happen ?
> If it fits the timezone, if like to atttend.
> 
> I'd very much like to re-revert the changes and put this test in proper place with green runs

Agreed! It's tomorrow at 8am Pacific Time: https://www.google.com/calendar/event?eid=MDV0Y3ZoNWd1OGtpNWtmc2lncTd2NW9tb21fMjAyMTA4MTJUMTUwMDAwWiBjYWxlbmRhckBrdWJlcm5ldGVzLmlv
