### ISSUE TITLE
Intermittent loss of iptables rules causing loss of access to services on a NodePort

### ISSUE THREAD

**Issue by davidtnorth** [kubernetes/kubernetes#104388]
We are using K8s 1.15. I'm aware this is many versions back, but I've been unable to locate a bug report like this one suggesting the problem may still exist in newer versions (we should find that out over the coming weeks).

We have experienced this problem on two different installations:

 - One on RHEL 7, installed using kubeadm
 - One on Debian 10, also installed using kubeadm
 
In both cases, the symptoms are as follows:

 - There is a service which is exposed via a NodePort
 - This service is backed by a single pod

In one case, the service is Traefik acting as the ingress controller for the cluster; in another, it's PostgreSQL.

Initially, everything works.

Then, after a seemingly random period of time which could be days or weeks, connections to the service from outside the cluster fail with "connection refused".

Examining the output of `iptables -L nat` shows that the rules for directing traffic to that service seem to have been removed, despite the pod being in a healthy state.

Re-starting the pod fixes the problem.

**Comment by aojea** [comment]
nodePort or hostPort?

**Comment by khenidak** [comment]
I don't even remember how kube-proxy used to work back then. We have iterated to improve it so much since then. And since we can not really patch such an old version the only solution around that is to check what clears iptables/kube-proxy logs or better move to newer kubernetes versions. 

I will not mark this as `accepted` but i will leave it open for a while maybe somebody can provide a solution.

**Comment by thockin** [comment]
I don't think kube-proxy is fundamentally different, but lots of bugs have been fixed.  Nothing that stands out as THIS bug, though.

Are you using iptables or IPVS mode?

I agree that the logs are the best starting point - do you have logs around that time?

**Comment by thockin** [comment]
Anything more we can do here?
