### ISSUE TITLE
Feat: Set Pod Level Resource Limits and Requests

### ISSUE THREAD

**Issue by BLasan** [kubernetes/kubernetes#104375]
#### What would you like to be added:

Option to add resource limits and requests to the Pods rather than getting the sum of the resource limit values of the containers inside it.

#### Why is this needed:

Suppose two microservices (A & B) which will execute one at a time on a request receive. It means that when calling to microservice-B from microservice-A where A expects the response from the service B. So this implies that A is in a IO bound state without proceeding any further step until it gets back the response from service B. At such kind of situation getting total value of resource limits of the containers would lead to a resource wastage.

#### Is this a BUG REPORT or FEATURE REQUEST?:

/kind feature

#### Related Issue:

https://github.com/kubernetes/kubernetes/issues/60834

**Comment by dims** [comment]
@BLasan please see the process we follow here in kubernetes for enhancements like these - https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement

you will need to advocate with sig-auth / sig-apimachinery and sig-node to get something like this going.

**Comment by BLasan** [comment]
> @BLasan please see the process we follow here in kubernetes for enhancements like these - https://github.com/kubernetes/enhancements#is-my-thing-an-enhancement
> 
> you will need to advocate with sig-auth / sig-apimachinery and sig-node to get something like this going.

Thanks. Will follow the process
