### ISSUE TITLE
kube-proxy failed to sent event to kube-apiserver in v1.22

### ISSUE THREAD

**Issue by chenyw1990** [kubernetes/kubernetes#104394]
#### What happened:
In v1.22, kube-proxy failed to sent event to kube-apiserver.
```
E0816 17:17:48.021402 1275820 event_broadcaster.go:253] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"paas-192-168-10-117.169bd8f7e06ca3ce", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, EventTime:v1.MicroTime{Time:time.Time{wall:0xc03ec54a555b43fd, ext:64899824, loc:(*time.Location)(0x2d96720)}}, Series:(*v1.EventSeries)(nil), ReportingController:"kube-proxy", ReportingInstance:"kube-proxy-PaaSCore-1", Action:"StartKubeProxy", Reason:"Starting", Regarding:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"paas-192-168-10-117", UID:"paas-192-168-10-117", APIVersion:"", ResourceVersion:"", FieldPath:""}, Related:(*v1.ObjectReference)(nil), Note:"", Type:"Normal", DeprecatedSource:v1.EventSource{Component:"", Host:""}, DeprecatedFirstTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedLastTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeprecatedCount:0}': 'Event "paas-192-168-10-117.169bd8f7e06ca3ce" is invalid: involvedObject.namespace: Invalid value: "": does not match event.namespace' (will not retry!)
```
this issue relate to PR: https://github.com/kubernetes/kubernetes/pull/102832

![image](https://user-images.githubusercontent.com/1468240/129565118-05ff3991-ef78-42a3-919d-e41c9b56e8f5.png)

after this change, kube-proxy cannot send event to kube-apisever.

kube-apiserver failed in:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/validation/events.go#L143~L145

![image](https://user-images.githubusercontent.com/1468240/129565993-4705851f-0a3e-4df8-a47f-34cbdd93f948.png)

#### What you expected to happen:
kube-proxy can send event to kube-apiserver successed.

#### How to reproduce it (as minimally and precisely as possible):
start kube-proxy normally

#### Environment:
- Kubernetes version (use `kubectl version`):v1.22
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by chenyw1990** [comment]
@thockin @Yuan-Junliang

**Comment by h4ghhh** [comment]
Relate PR：https://github.com/kubernetes/kubernetes/pull/100125

**Comment by bridgetkromhout** [comment]
Related: https://github.com/kubernetes/kubernetes/pull/104395

**Comment by khenidak** [comment]
This https://github.com/kubernetes/kubernetes/pull/100125 should close this issue. I will close please feel free to reopen if the issue is still there. 

/close

**Comment by liggitt** [comment]
note that until https://github.com/kubernetes/kubernetes/pull/105089 is merged and the next 1.22 patch release is cut, this is unresolved for 1.22

**Comment by liggitt** [comment]
reopening just to track the backport

**Comment by liggitt** [comment]
https://kubernetes.io/releases/patch-releases/#1-22 is the timeline for 1.22 patch releases... one was just cut, which means the next isn't planned for ~1 month
