### ISSUE TITLE
Resource not found error when api server is started but OpenAPI specs are not imported

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubernetes#104324]
#### What happened:
When api server starts, it does not wait all OpenAPI specs are imported as shown below;

- It starts OpenAPI aggregator in different goroutine https://github.com/kubernetes/kubernetes/blob/e7efe219f8a5fcdff9647d45639696048c1f6147/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L337
- It starts readyz endpoint for getting requests https://github.com/kubernetes/kubernetes/blob/e7efe219f8a5fcdff9647d45639696048c1f6147/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L326

However, since the OpenAPI specs are not guaranteed that they are all imported at least once, commands like `kubectl explain somecrd` throws `resource not found` error in here https://github.com/openshift/kubernetes-kubectl/blob/0c5d119ce86414ebbd725f56967987c9cf72e496/pkg/cmd/explain/explain.go#L154

#### What you expected to happen:
Api server's readiness probe endpoint should ensure that all OpenAPI specs are imported and commands like `kubectl explain` returns correct results.

#### How to reproduce it (as minimally and precisely as possible):
Restart API server and immediately run `kubectl explain examplecrd` command.

#### Environment:
- Kubernetes version (use `kubectl version`):
v1.21.2
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by caesarxuchao** [comment]
cc @Jefftree
/triage accepted

**Comment by Jefftree** [comment]
afaik there is some work being done around this area to improve the behavior when the apiserver is initializing https://github.com/kubernetes/enhancements/pull/3029

**Comment by ardaguclu** [comment]
@Jefftree you are right, problem looks to be solved. 

I'm closing this issue.
