### ISSUE TITLE
Can k8s use mysql to replace etcd? How to replace?

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#104370]
Can k8s use mysql to replace etcd? How to replace?

**Comment by yxxhero** [comment]
I think no.

**Comment by pacoxu** [comment]
kube-apiserver doesn't support it.
```
      --storage-backend string                   The storage backend for persistence. Options: 'etcd3' (default).
```
https://github.com/rancher/k8s-sql uses a DB such as MySQL, RDS, or Cloud SQL for your Kubernetes cluster state. But the repo was archived.

**Comment by neolit123** [comment]
you can use rancher's kine project. it emulates the etcd API layer but uses something else as the storage backend.

see examples here:
https://github.com/k3s-io/kine/blob/master/examples/minimal.md

/kind support
/close
