### ISSUE TITLE
Adding Kubernetes Middleware by Casbin to official List

### ISSUE THREAD

**Issue by ashish493** [kubernetes/kubernetes#104354]
I'm a member from Casbin. Our community has been building a Kubernetes Middleware, which would authorize the requests based on Casbin Policies. This middleware uses K8s validation admission webhook to check the policies defined by casbin, for every request to any k8s resource/sub-resource.
 
#### What would you like to be added:
I would like to add our middleware in the official list of K8s. Is there any such list of 3rd party applications of K8s, where I can create a PR for it?

You can check the middleware here:- https://github.com/casbin/k8s-authz
You can check this repo to know more about Casbin:- https://github.com/casbin/casbin

**Comment by neolit123** [comment]
> I would like to add our middleware in the official list of K8s. Is there any such list of 3rd party applications of K8s, where I can create a PR for it?

hi, not sure what you mean by official list, but if you'd like your project to be hosted in a repository under the k8s github organizations, then you'd have to ask for a sponsoring special interest group (SIG).

your projects would fall under the expertise of SIG Auth. try emailing the group mailing list for feedback:
https://github.com/kubernetes/community/tree/master/sig-auth#contact

this issue tracker is for bug/feature tracking.
thanks

/close
/sig auth
/kind support
