### ISSUE TITLE
run k8s source code on IDE (such as :goland)

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#104319]
How to run k8s source code on IDE? What environment need to be configured?

**Comment by jyz0309** [comment]
Hello! I think you can try to read this [blog](https://dzone.com/articles/easy-step-by-step-local-kubernetes-source-code-cha), I think it will help you a lot~

**Comment by pipijiev12** [comment]
> Hello! I think you can try to read this [blog](https://dzone.com/articles/easy-step-by-step-local-kubernetes-source-code-cha), I think it will help you a lot~
I read the official k8s blog, it only teaches you how to install k8s, but it doesn't teach you how to run k8s source code. The official blog only provides to compile k8s on linux source code, but does not run the source code on ide.

**Comment by neolit123** [comment]
for support discussions:
http://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
