### ISSUE TITLE
 Warning  ImageGCFailed    failed to get imageFs info: unable to find data in memory cache

### ISSUE THREAD

**Issue by NOWYOU** [kubernetes/kubernetes#104341]
kubernetes version：v1.18.0
System architecture: arm64 ubuntu 20.04
I installed a three-node k8s cluster on Raspberry Pi 4 model B in binary mode.
But the container image cannot be downloaded normally, and the following error will be reported

Use the command 【kubectl describe nodes k8s-02 】
`  Normal   Starting                 15s    kubelet, k8s-02     Starting kubelet.
  Warning  ImageGCFailed            15s    kubelet, k8s-02     failed to get imageFs info: unable to find data in memory cache
  Normal   NodeHasSufficientMemory  15s    kubelet, k8s-02     Node k8s-02 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    15s    kubelet, k8s-02     Node k8s-02 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     15s    kubelet, k8s-02     Node k8s-02 status is now: NodeHasSufficientPID`

Use the command 【journalctl -u kubelet | grep -i garbage】
`Aug 13 02:58:43 k8s-01 kubelet[92038]: E0813 02:58:43.110169   92038 kubelet.go:1301] Image garbage collection failed multiple times in a row: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:58:51 k8s-01 kubelet[92271]: E0813 02:58:51.937790   92271 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:58:59 k8s-01 kubelet[92506]: E0813 02:58:59.440425   92506 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:59:05 k8s-01 kubelet[92739]: E0813 02:59:05.960611   92739 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:59:12 k8s-01 kubelet[92978]: E0813 02:59:12.649678   92978 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:59:19 k8s-01 kubelet[93267]: E0813 02:59:19.431350   93267 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 02:59:26 k8s-01 kubelet[93493]: E0813 02:59:26.178111   93493 kubelet.go:1305] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache`

Raspberry Pi capacity situation.

```bash
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           782M  4.0M  778M   1% /run
/dev/mmcblk0p2  117G   16G   97G  15% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0       49M   49M     0 100% /snap/core18/1949
/dev/loop1       49M   49M     0 100% /snap/core18/2127
/dev/loop2       62M   62M     0 100% /snap/lxd/19040
/dev/loop3       27M   27M     0 100% /snap/snapd/10709
/dev/loop4       29M   29M     0 100% /snap/snapd/12707
/dev/loop5       62M   62M     0 100% /snap/lxd/21032
/dev/mmcblk0p1  253M  119M  134M  48% /boot/firmware
tmpfs           782M     0  782M   0% /run/user/0
```

I found the same problem on various forums and github, but there seems to be no universal solution. The known solutions cannot solve this problem.
If you encounter a similar problem and successfully solved it, can you share your ideas?

**Comment by NOWYOU** [comment]
This is my personal opinion. Although the SD card on the Raspberry Pi has enough capacity, it seems that docker cannot write to it.

**Comment by neolit123** [comment]
hi, please fill the issue template properly:
https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/bug-report.md

once that is complete, you can reopen the issue.
thanks

/sig node
/close

**Comment by NOWYOU** [comment]
> hi, please fill the issue template properly:
> https://raw.githubusercontent.com/kubernetes/kubernetes/master/.github/ISSUE_TEMPLATE/bug-report.md
> 
> once that is complete, you can reopen the issue.
> thanks
> 
> /sig node
> /close

Thank you for your advice, I already fix it. And then how can I open the question again?

**Comment by wangxf1987** [comment]
steps:
1. systemctl daemon-reexec
2. systemctl restart docker
3. systemctl restart kubelet

**Comment by wangxf1987** [comment]
steps:
1. systemctl daemon-reexec
2. systemctl restart docker
3. systemctl restart kubelet
