### ISSUE TITLE
Kubelet is not unmounting bind mount when RWO volumes is attached in multiple pods on the same node 

### ISSUE THREAD

**Issue by amitbhatia1987** [kubernetes/kubernetes#104357]
We have 2 node kubernetes setup with one master & one worker node
K8s version: v1.20.4

Failure Scenario:
To test a failure scenario following steps are performed:
1) Create multiple pods using single RWO PVC (FC) using CSI mounted in all pods. Use POD Affinity to schedule them on single worker node.
2) Stop kubelet on the worker node
3) Pod goes into terminating state
4) From Master node force delete terminating pods to clear all terminating pod objects
5) Delete volumeattachment
6) Start kubelet on the worker node
7) Kubelet is unable to clear all bind mounts hence resulting in mount failure with below error
 **With ext4 FS:**
 Warning  FailedMount             10m   kubelet                  MountVolume.SetUp failed for volume "csivol-648c9fe30c" : rpc error: code = Internal desc =  runid=140 error publish volume to target path: mount failed: exit status 32
mounting arguments: -o remount /var/lib/kubelet/plugins/kubernetes.io/csi/pv/csivol-648c9fe30c/globalmount /var/lib/kubelet/pods/c4b98b33-b904-48f5-983b-a3b9516dc9c5/volumes/kubernetes.io~csi/csivol-648c9fe30c/mount
output: mount: /var/lib/kubelet/pods/c4b98b33-b904-48f5-983b-a3b9516dc9c5/volumes/kubernetes.io~csi/csivol-648c9fe30c/mount: cannot remount /var/lib/kubelet/plugins/kubernetes.io/csi/pv/csivol-648c9fe30c/globalmount read-write, is write-protected.

**With XFS FS:**
Warning  FailedMount             22s (x8 over 89s)  kubelet                  MountVolume.MountDevice failed for volume "csivol-a6a7ff3a9c" : kubernetes.io/csi: attacher.MountDevice failed to create dir "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/csivol-a6a7ff3a9c/globalmount":  mkdir /var/lib/kubelet/plugins/kubernetes.io/csi/pv/csivol-a6a7ff3a9c/globalmount: file exists

 It seems Kubelet only unmount the first attached bind mount while ignores other bind mounts and is unable to remount the global mount  with below error

Aug 13 08:32:42 bl460cx2355 kubelet[1140]: E0813 08:32:42.935662 1140 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/csi-unity.dellemc.com^csivol-027480504e-FC-ckm00172100089-sv_1256 podName: nodeName:}
" failed. No retries permitted until 2021-08-13 08:32:50.935616809 +0200 CEST m=+21.200611763 (durationBeforeRetry 8s). Error: "GetDeviceMountRefs check failed for volume \"csivol-027480504e\" (UniqueName: \"kubernetes.io/csi/csi-unity
.dellemc.com^csivol-027480504e-FC-ckm00172100089-sv_1256\") on node \"bl460cx2355\" : the device mount path \"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/csivol-027480504e/globalmount\" is still mounted by other references [/var/lib/
kubelet/pods/13f0cd8f-adf8-49fe-8d76-9f32ae7c446b/volumes/kubernetes.io~csi/csivol-027480504e/mount /var/lib/kubelet/pods/132015c3-2e1d-46c7-b29c-f702bb0f6319/volumes/kubernetes.io~csi/csivol-027480504e/mount /var/lib/kubelet/pods/bee8
b16b-5d1d-4c19-ad82-86e954f22af8/volumes/kubernetes.io~csi/csivol-027480504e/mount /var/lib/kubelet/pods/24bd60b5-b770-4707-b8fd-9856b73a19e9/volumes/kubernetes.io~csi/csivol-027480504e/mount /var/lib/kubelet/pods/af0c810a-693e-463a-a0
76-dd58e62b8820/volumes/kubernetes.io~csi/csivol-027480504e/mount /var/lib/kubelet/pods/68097e4b-0cc0-4978-8de4-ef0465e0d1a3/volumes/kubernetes.io~csi/csivol-027480504e/mount]"

**Comment by Kartik494** [comment]
Hi @amitbhatia1987 Could you provide some information on number of volume mounts are bound when kubelet is in running state? and which volume mount is not been cleared by kubelet

**Comment by Kartik494** [comment]
I am trying to reproduce this in my environment, could you share or reference pod yaml  for the same.

**Comment by ikogan** [comment]
I believe I'm seeing this using the CephFS CSI, I have an open issue with them here: https://github.com/ceph/ceph-csi/issues/2238. That issue includes a test manifest but it requires a Ceph cluster :-/.

**Comment by ikogan** [comment]
I'm wondering if this is related to https://github.com/ceph/ceph-csi/issues/2238
