### ISSUE TITLE
all tests in kubelet-serial-gce-e2e-graceful-node-shutdown are failing

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#104344]
#### What happened:

All tests in https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-graceful-node-shutdown are red.

/sig node
/assign @bobbypage

**Comment by bobbypage** [comment]
Test will be updated in https://github.com/kubernetes/kubernetes/pull/102915/

**Comment by SergeyKanzhelev** [comment]
this is fixed thru https://github.com/kubernetes/kubernetes/pull/106108
