### ISSUE TITLE
Errors connecting to AKS-HCI service host

### ISSUE THREAD

**Issue by EkeleAsonye** [kubernetes/kubernetes#104397]
#### What happened
Issue was reported by a partner, Dell Corp.

When I RDP to one of the nodes in my Azure Stack HCI cluster, I ran the Get-AksHciCluster command and got the error that the established connection failed because host failed to respond.

Probing further, an operator can not access the mgmt cluster using the kubeconfig-mgmt.  The commands will fail with an error like:
Unable to connect to the server: dial tcp 172.168.10.0:6443.
where 172.168.10.0 is the IP of the control plane.
 
Certain powershell commands that use the kubeconfig-mgmt will fail with an error similar to :
Unable to connect to the server: dial tcp 172.168.10.0:6443.
where 172.168.10.0 is the IP of the control plane.

![image](https://user-images.githubusercontent.com/70991596/129594777-090831aa-ea22-43d4-924f-9045eb4b80be.png)

**Comment by neolit123** [comment]
hi, you should try contacting Azure support.
this repository is for core k8s bugs/features.

/sig cloud-provider
/area-provider azure
/close
