### ISSUE TITLE
Coalesce exec calls in networkpolicy tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#104305]
#### What happened:

we can still make things faster :) 

#### What to do

Coalesce of `exec` calls in netpol tests would result in alot snappier probing.

Right now, we do:
- pod a -> pod a (1 sec)
- pod a -> pod b (1 sec)
- pod a -> pod c (1 sec)

It would be faster if we do 

- pod a -> pod x/a, x/b, x/c, y/a, y/b, y/c , and pod a returns a `[fail, pass, pass, pass, fail,... ]` array.  
- pod b -> pod x/a, x/b, x/c, ... 

this would involve maybe adding functionality to agnhost to return more info i think ?

have to investigate more.

**Comment by jayunit100** [comment]
cc @mattfenwick

**Comment by mattfenwick** [comment]
I tried this out before, and it didn't help as much as I hoped.  Wish I still had the code lying around b/c I don't want you to have to take my word for it 😱 anyway I still think this is a good idea and we should try it again.
