### ISSUE TITLE
Decide what we are doing with normalized cpu

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10438]
In docs/resources.md we state that cpu is actually in units of KCU, which is normalized CPU.
But, on GCE/GKE we don't do that.  Nor on Vagrant, or anything else.
As @justinsb points out, the AWS cloud provider is reporting cores in ECUs (amazon's normalized core).
GCE is reporting actual cores.
GCE used to have GCEUs but it seems the documentation for that is gone.

So, we need to do something.  Some options:
1.  kubernetes.io/cpu resource is implementation defined.  
- Can continue to use ECU on amazon
- Can continue to use absolute on GCE
- Remove mention of KCU from docs.
- Config is portable, but performance varies.
  1. kubernetes.io/cpu resource is cores on all cloud-providers.
- Change Amazon
- Fixup docs  
- Config is portable, but performance varies
  1. kubernetes.io/cpu resource is normalized for all platforms, and ostensibly comparable across cloud-providers
- put actual core count as a new field on nodes, in case anyone cares
- define values for GCE, other platforms
- Let the battle begin over who's cores are better 
- Constantly update a table of (processor type, core) to KCU mappings, as there are vastly more types of cpus in the wide world than there are just on amazon and GCE.
- Config is portable, and performance varies less
  1. Each platform can define its own normalized unit, with cores as a fallback
- kubernetes.io/ecu means AWS ECUs
- cloud.google.com/kcu means some normalized unit for GCE processors
-  Config is not portable, and you are forced to think about performance when porting.

**Comment by erictune** [comment]
@justinsb pointed out this issue on #10399

**Comment by dchen1107** [comment]
subscribe to this issue.

**Comment by thockin** [comment]
I assumed it would be something like each cluster can optionally define a
mapping of platform-CPU to KCUs and that would be used at scheduling/run
time.  I can think of no better person than you to consider the merits of
these options, though :)
