### ISSUE TITLE
Race detected in pkg/kubelet

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#104463]
#### Which jobs are flaking:

`pull-kubernetes-unit`

#### Which test(s) are flaking:

`pkg/kubelet`

/sig node

#### Testgrid link:

The overall TestMain is failing:

Sample failure:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/100720/pull-kubernetes-unit/1428427896606691328

#### Reason for failure:

race detected.

**Comment by pacoxu** [comment]
```
=== SKIP: vendor/k8s.io/legacy-cloud-providers/vsphere TestVolumes (0.00s)
    vsphere_test.go:876: No config found in environment

=== Failed
=== FAIL: pkg/kubelet  (0.00s)
=== CONT  
    testing.go:1092: race detected during execution of test
FAIL
FAIL	k8s.io/kubernetes/pkg/kubelet	18.260s

DONE 30011 tests, 22 skipped, 1 failure in 1.895s
+++ [0819 19:25:32] Saved JUnit XML test report to /logs/artifacts/junit_20210819-185024.xml
make: *** [Makefile:184: test] Error 1
```

No race details found in the CI logs.

**Comment by adisky** [comment]
/triage accepted. 
It has failed on multiple PR's with same error
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit?buildId=1428494756425502720

**Comment by adisky** [comment]
Not able to reproduce locally, but seeing the data race in  CI `TestVolumeUnmountAndDetachControllerDisabled()`
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104368/pull-kubernetes-unit/1428640022386446336#1:build-log.txt%3A2364

**Comment by adisky** [comment]
but this seems duplicate of https://github.com/kubernetes/kubernetes/issues/104057
