### ISSUE TITLE
apiserver/pkg/storage/interfaces.go contains unintended HTML tags

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#104457]
#### What happened:
My IDE rendered the comments in `interfaces.go` and they were incomprehensible.  I looked at the corresponding source, and found stuff like
```
// IndexerFuncs is a mapping from <index name> to function that
// for a given object computes <value for that index>.
type IndexerFuncs map[string]IndexerFunc
```

Those things set off in angle brackets are taken to be HTML tags.  They should be backquoted.

#### What you expected to happen:
I expected the comments to render comprehensibly.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.22.0
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
Here is an example of what I saw in my IDE.   The HTML tags in the comment source just disappeared, because they are not actually meaningful HTML tags.

<img width="627" alt="Screen Shot 2021-08-19 at 12 16 00 PM" src="https://user-images.githubusercontent.com/14296719/130104953-dfa5732f-8966-4f69-88d3-521e7cfaae7e.png">

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
Better source would look like this:
```
// IndexerFuncs is a mapping from `<index name>` to function that
// for a given object computes `<value for that index>`.
type IndexerFuncs map[string]IndexerFunc
```

**Comment by MikeSpreitzer** [comment]
That would make it look like this:
<img width="577" alt="Screen Shot 2021-08-19 at 3 17 12 PM" src="https://user-images.githubusercontent.com/14296719/130130749-d28e09e6-8da6-4bea-a7d6-2a014c250c52.png">

**Comment by MikeSpreitzer** [comment]
That would make it look like this:
<img width="748" alt="Screen Shot 2021-08-19 at 3 18 23 PM" src="https://user-images.githubusercontent.com/14296719/130130856-651ea964-e269-4b25-9775-bea2c9017c59.png">

**Comment by Pravenn18** [comment]
Can anyone tell me who is the mentor in Kubernetes,please

**Comment by MikeSpreitzer** [comment]
I don't know about a single designated mentor.  I will be happy to help anyone working on this issue.

**Comment by cheftako** [comment]
> Can anyone tell me who is the mentor in Kubernetes please

I would suggest either attending a SIG (Eg. APIMachinery or Storage) meeting which interests you and seeing what that SIG has as far as getting new contributors up to speed or reach out to ContribEx.
