### ISSUE TITLE
Ability to use image references with literal IPv6 address as domain

### ISSUE THREAD

**Issue by mcwumbly** [kubernetes/kubernetes#104491]
#### What happened:

1. setup a private IPv6 registry (e.g. Docker or Harbor) which has both FQDN and IPv6 address.
2. prepare an example app yaml file which image will be pulled from the registry. 
3. app can be created successfully when image URL starting with FQDN:
    ```
    - image: my.registry.com/hello-app:1.0
    ```
4. app can not be created when image URL starting with IPv6 address.
    ```
    - image: [fc00:f853:ccd:e793::3]:5000/hello-app:1.0
    ```

pod status is `InvalidImageName` and events show `Warning  InspectFailed  48s (x142 over 30m)  kubelet            Failed to apply default image tag " [fc00:f853:ccd:e793::3]:5000/hello-app:1.0": couldn't parse image reference "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0": invalid reference format`

#### What you expected to happen:

1. app can be created when image URL starting with IPv6 address of registry

#### How to reproduce it (as minimally and precisely as possible):

The following reproduction uses KinD with a local docker registry for simplicity. It leaves something to be desired, in that the containerd config patch is overriding the registry endpoint, but it does illustrate the issue. Note that the container endpoint is overridden to be the IPv6 address of the registry, so connectivity is using IPv6.

Note: A more satisfying reproduction would be to use a publicly available registry that serves IPv4 and IPv6 where images can be pulled using their IP addresses in addition to their domain names -- but I haven't found one yet that meets those criteria. 

Also Note: One can reproduce this by installing a registry like Harbor that serves IPv6, but it's more involved.

Steps:

1. Run the script below to create a docker registry and IPv6 KinD cluster
   ```
   #!/bin/sh
   set -o errexit
   
   # create registry container unless it already exists
   reg_name='kind-registry'
   reg_ip='[fc00:f853:ccd:e793::3]'
   reg_port='5000'
   reg_image='registry:2'
   running="$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)"
   if [ "${running}" != 'true' ]; then
     docker run \
       -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
       "${reg_image}"
   fi
   
   # create a cluster with the local registry enabled in containerd
   cat <<EOF | kind create cluster --config=-
   kind: Cluster
   apiVersion: kind.x-k8s.io/v1alpha4
   networking:
     ipFamily: ipv6
   containerdConfigPatches:
   - |-
     [plugins."io.containerd.grpc.v1.cri".registry.mirrors."*"]
       endpoint = ["http://${reg_ip}:${reg_port}"]
   EOF

   # connect the registry to the cluster network
   # (the network may already be connected)
   docker network connect "kind" "${reg_name}" || true
   ```
2. Pull, tag, and push a sample image to the registry
   ```
   docker pull gcr.io/google-samples/hello-app:1.0
   docker tag gcr.io/google-samples/hello-app:1.0 localhost:5000/hello-app:1.0
   docker push localhost:5000/hello-app:1.0
   ```
3. Create a deployment that references that image via some domain name
   ```
   kubectl create deployment hello-server --image=foo:5000/hello-app:1.0
   ```
   NOTE: Using `foo` as the domain to illustrate it doesn't really matter because we wildcard-match the registry mirror in the containerd config patch in this example.
4. Check the pods and see that it's running OK
   ```
   $ kubectl get po
   NAME                                 READY   STATUS             RESTARTS   AGE
   hello-server-589fdfbf87-rvvch        1/1     Running            0          29m
   ```
5. Create a deployment that references that image via an IPv4 address
   ```
   kubectl create deployment hello-server-ipv4 --image="127.0.0.1:5000/hello-app:1.0"
   ```
6. Check the pods and see that it's running OK
   ```
   $ kubectl get po
   NAME                                 READY   STATUS             RESTARTS   AGE
   hello-server-589fdfbf87-rvvch        1/1     Running            0          34m
   hello-server-ipv4-56789c7584-9bj85   1/1     Running            0          33m
   ```
5. Create a deployment that references the image via an IPv6 address (happens to be the address of the registry container)
   ```
   kubectl create deployment hello-server-ipv6 --image="[fc00:f853:ccd:e793::3]:5000/hello-app:1.0"
   ```
6. Check the pod and see the following:
   ```
   $ kubectl get po
   NAME                                 READY   STATUS             RESTARTS   AGE
   hello-server-589fdfbf87-rvvch        1/1     Running            0          34m
   hello-server-ipv4-56789c7584-9bj85   1/1     Running            0          33m
   hello-server-ipv6-6dc8fc44f7-v88rp   0/1     InvalidImageName   0          29m
   ```
7. Describe the pod and see these events:
   ```
   $ kubectl describe pod hello-server-ipv6-6dc8fc44f7-v88rp
   ...
   Events:
     Type     Reason         Age                  From               Message
     ----     ------         ----                 ----               -------
     Normal   Scheduled      31m                  default-scheduler  Successfully assigned default/hello-server-ipv6-6dc8fc44f7-v88rp to kind-control-plane
     Warning  Failed         28m (x12 over 30m)   kubelet            Error: InvalidImageName
     Warning  InspectFailed  48s (x142 over 30m)  kubelet            Failed to apply default image tag " [fc00:f853:ccd:e793::3]:5000/hello-app:1.0": couldn't parse image reference "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0": invalid reference format
   ```

#### Anything else we need to know?:

This looks like a limitation in [distribution/distribution](https://github.com/distribution/distribution), where a regular expression supports domains and IPv4 addresses, but not IPv6 addresses:

1. kubelet returns this error [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/dockershim/libdocker/helpers.go#L45-L48) or [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/images/image_manager.go#L164-L167).
2. ParseNormalizedName returns the underlying error [here](https://github.com/distribution/distribution/blob/ecdf4b7e436ac39ff5e09a67e84b79aa2b74ad80/reference/normalize.go#L47-L50) from Parse
3. Parse returns the error [here](https://github.com/distribution/distribution/blob/ecdf4b7e436ac39ff5e09a67e84b79aa2b74ad80/reference/reference.go#L198)
4. The [DomainRegexp](https://github.com/distribution/distribution/blob/main/reference/regexp.go#L26-L38) does not allow IPv6 addrs
5. Found these two open PRs for this issue:
    1. https://github.com/distribution/distribution/pull/2899
    2. https://github.com/distribution/distribution/pull/2575

Here's a couple other quick tests that show the same underlying issue:

```
$ docker pull "[::1]:5000/hello-app:1.0"
invalid reference format
```

```
root@kind-control-plane:/# crictl pull "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0"
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to parse image reference "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0": invalid reference format
```

This is arguably a feature request rather than a bug. I'm happy to discuss this elsewhere if someone can point me in the right direction, but felt it'd be valuable to document this limitation here in the meantime as I was not able to find any other mentions of this issue.

The workaround of just using a hostname for the domain seems pretty straightforward, the person who originally reported this to me says that the users they support often currently use private registries serving on IPv4 without FQDNs and may run into this as they start using IPv6 clusters. 

#### Environment:
- Kubernetes version (use `kubectl version`): 
   ``` 
   Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
   ```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): `Ubuntu 20.04.2 LTS`
- Kernel (e.g. `uname -a`): `5.4.0-65-generic`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by andrewsykim** [comment]
@aojea @khenidak does this issue ring any bells?

**Comment by aojea** [comment]
Great description by the way, it's interesting, it looks to me that the right fix is in the docker library so the whole container ecosystem is consistent about that ... 
Let me try to move forward with one of those PRs
/assign
/triage accepted

**Comment by mcwumbly** [comment]
> it looks to me that the right fix is in the docker library so the whole container ecosystem is consistent about that

good point. here's a couple other quick tests that show the same underlying issue:

```
$ docker pull "[::1]:5000/hello-app:1.0"
invalid reference format
```

```
root@kind-control-plane:/# crictl pull "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0"
FATA[0000] pulling image: rpc error: code = Unknown desc = failed to parse image reference "[fc00:f853:ccd:e793::3]:5000/hello-app:1.0": invalid reference format
```

(updating original post to include this context as well)

**Comment by aojea** [comment]
Let's see if we can fix it upstream and revendor it https://github.com/distribution/distribution/pull/3489

**Comment by khenidak** [comment]
/assign @khenidak 

I honestly never seen anybody uses IP (IPv4 or IPv6) instead of host name. I also wonder if container runtime will treat `<IP>/<name>` different from `<host-name>/<name>` and try to re-pull it. IOW maybe we shouldn't fix this.

**Comment by mcwumbly** [comment]
> I honestly never seen anybody uses IP (IPv4 or IPv6) instead of host name.

Since IPv6 doesn't work, I suspect _no one_ has seen that :)

But I was told it was common in some scenarios to use IPv4 instead of hostname. I haven't personally seen this either, but let me see if I can find someone who has to comment with a bit more color.

**Comment by khenidak** [comment]
The concern i have with this is image identity re GC and what not. Imagine this scenario, two images that look like this:

https://kal-registry.io/my-fantastic-app-image
https://<kal-registry.IP>/my-fantastic-app-image

The are the same image but to GC and anything that operates on images (including pull secrets) they are two different images.

@cpuguy83  -- do you have thoughts on this?

**Comment by cpuguy83** [comment]
For GC these are just references the runtime is able to understand when it should clean up the blobs and snapshots related to it.

Note that containerd just uses `url.Parse` to parse an image reference and should work just fine this way unless there's something in the cri code path that's messing with it.

**Comment by honghaiw** [comment]
Hi,
Some of our telco customers are using the IPv4 addresses of their internal private Harbor services, in these cases, customers export Harbor services using literal IPv4 address directly instead of a FQDN, perhaps they don't want to configure new FQDNs on their DNS server.
They will meet this issue if they want to use IPv6 address for private Harbor services in future.
If this issue will not be fixed, we have to document it and let customer to use FQDN on IPv6 environments.
Thanks.

**Comment by aojea** [comment]
> Let's see if we can fix it upstream and revendor it [distribution/distribution#3489](https://github.com/distribution/distribution/pull/3489)

now that this has merged, it needs to be revendored on the corresponding components
