### ISSUE TITLE
imagePullSecrets should log warning if secret does not exist

### ISSUE THREAD

**Issue by neilharris123** [kubernetes/kubernetes#104432]
#### What happened:

imagePullSecrets can added to a pod manifest to reference a secret containing registry credentials. Currently, if you add the name of a secret that does not exist, there is no warning or error. 

#### What you expected to happen:

I would expect there to be an error and a failed deployment if the secret does not exist/cannot be found in the namespace. 
If people are pulling public images, they may still wish to authenticate to a registry, for example dockerhub, before pulling the image, in order to utilise their subscription account rate limits. Currently if they use imagePullSecrets and the referenced secret does not exist, they may assume they are authenticating to their account when they are not, and will still be able to pull public images without any warning that authentication is not taking place. 

#### How to reproduce it (as minimally and precisely as possible):

Add `imagePullSecrets: myfakesecret` to a pod spec, and pull images from docker.io.

**Comment by neolit123** [comment]
> Add imagePullSecrets: myfakesecret to a pod spec, and pull images from docker.io.

/sig node
(based on the field location)

**Comment by neolit123** [comment]
(and/or)
/sig auth

**Comment by kerthcet** [comment]
correct me if not. Pulling private images with nonexists secret, pod will turn to `ErrImagePull`.  However, pulling public image with nonexists secret, no error will display yet.

**Comment by pacoxu** [comment]
Similar issue with #88142. 
> Perhaps a warning event should be created?

**Comment by neilharris123** [comment]
> correct me if not. Pulling private images with nonexists secret, pod will turn to `ErrImagePull`. However, pulling public image with nonexists secret, no error will display yet.

Yes that's correct.

**Comment by kerthcet** [comment]
> Similar issue with #88142.
> 
> > Perhaps a warning event should be created?

I think so. Working on this later. Will also live up to your  expectations, right? @neilharris123

**Comment by JaneLiuL** [comment]
But I check it already have a warnging events if secret not exist and pullImageFail:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_manager.go line:147

**Comment by Pingan2017** [comment]
Now, only info message when image not exist
https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/pkg/kubelet/kubelet_pods.go#L891-L895

**Comment by Pingan2017** [comment]
maybe direct return and not enter `syncPod` is better.
`return` if pullSecret is not existed 
https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/pkg/kubelet/kubelet.go#L1725-L1729

@kubernetes/sig-node-bugs

**Comment by kerthcet** [comment]
> maybe direct return and not enter `syncPod` is better.
> `return` if pullSecret is not existed
> https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/pkg/kubelet/kubelet.go#L1725-L1729
> 
> @kubernetes/sig-node-bugs

if you pull image from  a public repo, the process should not be impacted even no secrets exists. And it's what it is right now.

**Comment by adisky** [comment]
I think a warning event `FailedToRetrieveImagePullSecret` could be added here
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L655
/good-first-issue
/triage accepted

**Comment by calvin0327** [comment]
I would like work on this.
/assign @EricWvi

**Comment by calvin0327** [comment]
I would like to work in this.
/assign

**Comment by liggitt** [comment]
Thanks for wanting to jump in on this, but it's not clear this is a good first issue… making the proposed change would break deployments/pods that are currently working/running, so it's unlikely this would be acceptable from a compatibility perspective.

**Comment by liggitt** [comment]
Requiring image pull secrets to exist would have to be opt-in, which means an API change. I don't think this is worth the addition, but would like to hear sig-node's perspective. 

An alternative could be to explore ways to make it more obvious to the user when this situation was occurring without automatically failing the pod

**Comment by kerthcet** [comment]
> Requiring image pull secrets to exist would have to be opt-in, which means an API change. I don't think this is worth the addition, but would like to hear sig-node's perspective.
> 
> An alternative could be to explore ways to make it more obvious to the user when this situation was occurring without automatically failing the pod

hi @liggitt , we will not fail the pod, we just want to add some warning to make it obviously, maybe it's the same as you advised. correct me if not. 🧐

**Comment by adisky** [comment]
> I think a warning event `FailedToRetrieveImagePullSecret` like
> https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/pkg/kubelet/kubelet_pods.go#L655
> 
> 
> could be added here
> https://github.com/kubernetes/kubernetes/blob/175776d25a5cf007c1fe1294097a8bf8e8b90e28/pkg/kubelet/kubelet_pods.go#L891-L895
> 
> 
> /good-first-issue
> /triage accepted

To be clear here, only adding a warning is marked as good first issue here, not changing any pod behaviour.

**Comment by liggitt** [comment]
gotcha, that seems more reasonable, thanks for clarifying

as a note, make sure the warning events are generated at most once in that function, rather than once per missing secret object (if there are multiple missing secrets)

**Comment by neilharris123** [comment]
> > Similar issue with #88142.
> > > Perhaps a warning event should be created?
> 
> I think so. Working on this later. Will also live up to your expectations, right? @neilharris123

Yes, a warning would be good. I feel an error would have be better, but as has already been mentioned we are too far along now for this change as it would break many existing deployments, so a warning makes the most sense now.

**Comment by ossparvinder** [comment]
@adisky based on what you have stated above, I see an INFO log already exists! If I'm understanding this correctly, now we need to raise a warning event to fulfill this request. Is that right? @liggitt @neilharris123

**Comment by kerthcet** [comment]
I think @calvin0327 has created a [pr](https://github.com/kubernetes/kubernetes/pull/104535) above and labeled /lgtm already.

**Comment by B-AYUSHMAN-PRUSTY** [comment]
Hey I don't know anything about how to code but i am interested to contribute on kubernetes
So help me to contribute

**Comment by adisky** [comment]
@SergeyKanzhelev there is PR already here https://github.com/kubernetes/kubernetes/pull/104535, just needs approval

**Comment by SergeyKanzhelev** [comment]
@adisky it was just FYI =) Reviewed the PR, thank you

**Comment by adisky** [comment]
@SergeyKanzhelev Thanks for the review :)

**Comment by PriyanshuAhlawat** [comment]
will like to work on it.
/assign

**Comment by SriPrarabdha** [comment]
Hey , would love to work on this issue

**Comment by SergeyKanzhelev** [comment]
> Hey , would love to work on this issue

there is already a PR: https://github.com/kubernetes/kubernetes/pull/104535/files @calvin0327  do you plan to push the PR forward?

**Comment by calvin0327** [comment]
@SergeyKanzhelev I have been busy with other things recently, if anyone is willing to continue this problem. I will close the PR.

**Comment by charan1998** [comment]
if noone else is working on this task, I would like to take this up. 🙂

**Comment by kerthcet** [comment]
Feel free to work on this @charan1998 , you can refer to https://github.com/kubernetes/kubernetes/pull/104535 for some advices.

**Comment by charan1998** [comment]
Thanks! Will refer it 👍

**Comment by Hecim1984** [comment]
Pomoc mi treba koliko imam ETH, BTC i ostali coinna? I gdje mogu  ⛰🏔⛏ rudarit?

**Comment by i-am-yuvi** [comment]
Is this issue still open/active?

**Comment by charan1998** [comment]
Hello @i-am-yuvi. I was working on it but not able to continue it due to some personal reasons. You can take over if you would like to. You can refer this PR #107814 if you want to.

**Comment by i-am-yuvi** [comment]
Yes sure!

**Comment by mrjoema** [comment]
Can I try this if no one is available to work on it ?

**Comment by i-am-yuvi** [comment]
> Can I try this if no one is available to work on it ?

Yes go on!!!

**Comment by mrjoema** [comment]
Sorry for keep opening the PR. something went wrong on my fork branch. I eventually needed to re-fork the repo so it caused the PR closed automatically

**Comment by ShehabMMohamed** [comment]
Can I give it a try if no one is working on it?

**Comment by liggitt** [comment]
Thanks for the offer, but it looks like https://github.com/kubernetes/kubernetes/pull/109492 was open and had an update that was waiting for review (which I didn't realize)

**Comment by valkyr13** [comment]
is this issue still available to pick up?

**Comment by emiljanogj** [comment]
Hi, this issue still available?

**Comment by kaisoz** [comment]
Hi!

It feels that this issue is stalled (although it lacks the label) and the related PRs have been abandoned. I'll work on it if that's ok 😊 

/assign

**Comment by sftim** [comment]
As well as an event, we might like to directly report a warning to end users (suggested in https://github.com/kubernetes/kubernetes/pull/117927#issuecomment-1548157787).
More complexity though.

**Comment by kaisoz** [comment]
> As well as an event, we might like to directly report a warning to end users (suggested in [#117927 (comment)](https://github.com/kubernetes/kubernetes/pull/117927#issuecomment-1548157787)). More complexity though.

@sftim should it be part of this issue? it only mentions `log` but as you guys (the contributors) decide
