### ISSUE TITLE
UpdateWithEventNamespace appears to be missing namespace check

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#104495]
#### What happened:

Reading through the code, I noticed that the [`UpdateWithEventNamespace`](https://github.com/kubernetes/client-go/blob/590eaed90a85421cb0c4815c5a9647a09f1ce5a2/kubernetes/typed/core/v1/event_expansion.go#L63-L78) method in the `EventExpansion` is missing a check that's in the `Create` and `Patch` variants (and is inconsistent with the comment):

```go
// UpdateWithEventNamespace modifies an existing event. It returns the copy of the event that the server returns,
// or an error. The namespace and key to update the event within is deduced from the event. The
// namespace must either match this event client's namespace, or this event client must have been
// created with the "" namespace. Update also requires the ResourceVersion to be set in the event
// object.
func (e *events) UpdateWithEventNamespace(event *v1.Event) (*v1.Event, error) {
	result := &v1.Event{}
	err := e.client.Put().
		NamespaceIfScoped(event.Namespace, len(event.Namespace) > 0).
		Resource("events").
		Name(event.Name).
		Body(event).
		Do(context.TODO()).
		Into(result)
	return result, err
}
```

The relevant bit from the doc comment is:
```
// ... The
// namespace must either match this event client's namespace, or this event client must have been
// created with the "" namespace. ...
```

#### What you expected to happen:

The Create/Patch variants have checks like:
```go
	if e.ns != "" && event.Namespace != e.ns {
		return nil, fmt.Errorf("can't create an event with namespace '%v' in namespace '%v'", event.Namespace, e.ns)
	}
```

#### How to reproduce it (as minimally and precisely as possible):

N/A just reviewing code

#### Environment:
- Kubernetes version (use `kubectl version`): observed at HEAD of k8s.io/client-go

**Comment by wzshiming** [comment]
Good catch, this like #78482

**Comment by caesarxuchao** [comment]
cc @wojtek-t 
/triage accepted
