### ISSUE TITLE
I am not able to launch nodegroup with custom eks 1.21.2 AMI 

### ISSUE THREAD

**Issue by alpana17** [kubernetes/kubernetes#104479]
I launched a cluster with eks 1.21
When I try to launch a nodegroup with custom AMI with cmd: eksctl create nodegroup --config-file C:\Users\alsingha\Desktop\ImageFactory\eks\cluster.yaml
here is cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: alp-cluster-121-north-virginia
  region: us-east-1

vpc:
  sharedNodeSecurityGroup: sg-0d37341a371473e33
  manageSharedNodeSecurityGroupRules: false

managedNodeGroups:
  - name: alp-cluster-121-custom
    ami: ami-07af0e585ffd35bff
    ssh:
      publicKeyName: alsingha-north-virginia
    disableIMDSv1: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh managed-cluster --alp-cluster-121-north-virginia
      
It gives me error
![image](https://user-images.githubusercontent.com/8611615/130229044-a339ec0f-06b0-4e2d-94f4-a1b6caa5d684.png)

**Comment by imoisharma** [comment]
Hi @alpana17, there are some common troubleshooting solutions for you. 

### Nodes fail to join the cluster:
There are a few common reasons that prevent nodes from joining the cluster:

- The [aws-auth-cm.yaml](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) file does not have the correct IAM role ARN for your nodes. Ensure that the node IAM role ARN (not the instance profile ARN) is specified in your aws-auth-cm.yaml file. For more information, see Launching [self-managed Amazon Linux nodes](https://docs.aws.amazon.com/eks/latest/userguide/launch-workers.html).
- The ClusterName in your node AWS CloudFormation template does not exactly match the name of the cluster you want your nodes to join. Passing an incorrect value to this field results in an incorrect configuration of the node's /var/lib/kubelet/kubeconfig file, and the nodes will not join the cluster.
- The node is not tagged as being owned by the cluster. Your nodes must have the following tag applied to them, where <cluster-name> is replaced with the name of your cluster. 
![image](https://user-images.githubusercontent.com/30807347/130374079-7d677c42-60f4-4ebc-aa41-519873348008.png)
- The nodes may not be able to access the cluster using a public IP address. Ensure that nodes deployed in public subnets are assigned a public IP address. If not, you can associate an Elastic IP address to a node after it's launched. For more information, see [Associating an Elastic IP address](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html#using-instance-addressing-eips-associating) with a running instance or network interface. If the public subnet is not set to automatically assign public IP addresses to instances deployed to it, then we recommend enabling that setting. For more information, see Modifying the public IPv4 addressing attribute for your subnet. If the node is deployed to a private subnet, then the subnet must have a route to a NAT gateway that has a public IP address assigned to it.
- The STS endpoint for the Region that you're deploying the nodes to is not enabled for your account. To enable the region, see [Activating and deactivating AWS STS in an AWS Region](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-activate-deactivate).
-The worker node does not have a private DNS entry, resulting in the kubelet log containing a node "" not found error. Ensure that the VPC where the worker node is created has values set for domain-name and domain-name-servers as Options in a DHCP options set. The default values are domain-name:<region>.compute.internal and domain-name-servers:AmazonProvidedDNS. For more information, see [DHCP options](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html#AmazonDNS) sets in the Amazon VPC User Guide.

For further investigation, if you can share some more details, that would be great, 

Best Regards
Mohit Sharma

**Comment by neolit123** [comment]
please report this to EKS support first.
if they find an actual upstream k8s bug reopen this ticket with their feedback.

thanks
/kind support
/close
