### ISSUE TITLE
hostNetwork tests can't use the same port or they will collide

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#104406]
Failed here
```
Kubernetes e2e suite: [sig-network] Services should respect internalTrafficPolicy=Local Pod to Pod (hostNetwork: true) [Feature:ServiceInternalTrafficPolicy] expand_more
```
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104401/pull-kubernetes-e2e-ubuntu-gce-network-policies/1427400844852072448
/retest

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/issues/104401#issuecomment-900063266_

This fails because the pod tries to bind port 80, that is a very demanded port, but there are two tests doing that, that increase the chance to collide

**Comment by khenidak** [comment]
Close when #104407 104407 merges
