### ISSUE TITLE
Found a typo on kubectl describe -h

### ISSUE THREAD

**Issue by arsley** [kubernetes/kubernetes#104473]
#### What happened:

I tried to see `kubectl describe -h`, found a typo on Examples section:

```
$ kubectl describe -h
...
Examples:
...
  # Describe pods by label name=myLabel
  kubectl describe po -l name=myLabel
...
```

#### What you expected to happen:

It has to be `pods` not `po`.

```diff
$ kubectl describe -h
...
Examples:
...
  # Describe pods by label name=myLabel
-  kubectl describe po -l name=myLabel
+  kubectl describe pods -l name=myLabel
...
```

#### How to reproduce it (as minimally and precisely as possible):

Just run `kubectl describe -h` .

#### Anything else we need to know?:

There may be similar typos in other commands.

#### Environment:

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:56:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-gke.501", GitCommit:"de876a981b936ce528482c45794fb1dfc5005042", GitTreeState:"clean", BuildDate:"2021-06-25T02:54:31Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): macOS Big Sur 11.5.2
- Kernel (e.g. `uname -a`):
```
Darwin *** 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
```

- Install tools: homebrew (`brew install kubernetes-cli`)
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by kerthcet** [comment]
`po` is short for `pods`  as `svc` responsing to `service`.

**Comment by arsley** [comment]
I didn't notice that `po` is the shorthand, sorry :bow:
I think this issue can close, but only this example showing on `kubectl describe -h` uses shorthand.
It's strange for newbie (like me).
