### ISSUE TITLE
apiserver admission: serviceaccount mutates pod.spec w/o notifying reinvocation-context

### ISSUE THREAD

**Issue by jdef** [kubernetes/kubernetes#104464]
#### What happened:
* my mutating webhook calculates a hash of the pod.spec, allows reinvocation; no side effects
* my validating webhook validates the hash of the pod.spec and fails because the pod.spec has changed
* webhook auditing indicates that my webhooks are the only ones processing the pod.spec
* upon serializing the spec to JSON for both the mutator and validator, the only change is related to the "kube-api-access-xyz" projected volume, managed by a built-in k8s admission plugin
* the aforementioned plugin does not appear to mutate the reinvocation context, even through it may mutate a pod (robbing other mutators of the chance to observe the change): https://github.com/kubernetes/kubernetes/blob/548f16dbbbdcff3eac822236353d613800ecb6e4/plugin/pkg/admission/serviceaccount/admission.go#L161
* it appears that *both* my hooks see the injected volume, but the validation hook sees the injected SA volume with a "defaultMode" field set, and my mutation hook does NOT see this field set

#### What you expected to happen:
* my validation hook should calculate the same hash

#### Anything else we need to know?:
* mutating, validating webhooks are implemented atop controller-runtime v0.8.3, pod objects are being decoded into `unstructured.Unstructured` targets

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21.3
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jdef** [comment]
cc @liggitt @sttts

**Comment by liggitt** [comment]
interesting... defaults are applied when going from versioned → internal

1. API server decodes v1 Pod request → applies defaults → converts to internal Pod
2. Built-in admission control operates on the internal Pod
  * service account admission injects the kube-api-access volume
3. Mutating admission is called
  * internal Pod → converts to v1 Pod → serializes → sends to mutating webhook
  * mutating webhook returns patch
  * patch is applied to v1 Pod JSON
  * resulting v1 Pod JSON is decoded → defaults applied (defaultMode is set on the api-token volume here) → converted to internal Pod
4. Validating webhook admission is called
  * internal Pod → converts to v1 Pod → serializes → sends to validating webhook

That means if any built-in admission plugin sets up data that would be modified by applying defaulting to the pod, the data sent to mutating webhooks will be missing those applied defaults until the first mutating webhook that returns a patch that changes the object

**Comment by liggitt** [comment]
Possible solutions:
1. ensure defaults are applied to the internal → versioned object before invoking webhooks
2. ensure built-in admission always populates data matching default values for unset fields

**Comment by liggitt** [comment]
As an aside, I'm not sure what you're using the hashing for, but be aware that hashing is fragile in the presence of defaults and new fields added over time. A hash you add to a pod spec in one release might not match a hash computed in a different release, or with different admission in place.
