### ISSUE TITLE
Is there a way to disable GPU for CPU pods?

### ISSUE THREAD

**Issue by kwon14** [kubernetes/kubernetes#104474]
Hello.
I am running a GPU server by referring to the document https://kubernetes.io/docs/tasks/manage-gpus/scheduling-gpus/.
I have found that GPU is used in DL work with Jupyternotebook by creating a virtual environment of CPU pod on the GPU node as shown below.
Obviously there is no nvidia.com/GPU entry in Limits, Requests, so I don't understand that GPU is used.
     Limits:
       cpu: 2
       memory: 2000Mi
     Requests:
       cpu: 2
       memory: 2000Mi
Is there a way to disable GPU for CPU pods?
please answer about my question.
thank you.

**Comment by neolit123** [comment]
please try asking on the support channels first:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

if this is a missing feature reopen this issue and add the `/kind support` command.

thanks.

/sig node
/kind support
