### ISSUE TITLE
Memory use of go-restful high?

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#10446]
Saw https://github.com/labstack/echo and the benchmark numbers for go restful seemed really high.  700k bytes allocated to serve a simple request?  This hasn't shown up on my profiles yet, but not sure why the two would be out of sync.

**Comment by bgrant0607** [comment]
cc @nikhiljindal @caesarxuchao

**Comment by brendandburns** [comment]
Closing this, one year old, no investigation, not an issue (or if it is we'll discover it elsewhere...)

**Comment by smarterclayton** [comment]
Data shows all our memory use is in our frameworks still.  We have a
process for this now so no need for the issue.
