### ISSUE TITLE
Add running field to Job status

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#104422]
#### What would you like to be added:

A `Running int32` field to `JobStatus` to keep track of the number of Running Pods. This differs from the existing `Active` field in that it doesn't include Pods in `Pending` phase.

#### Why is this needed:

Some workloads (example: kubeflow/mpi-operator#315) require watching the number of running replicas to take some decisions.

Note that other workload APIs (Deployment, StatefulSet) already provide this information.

/sig apps

**Comment by kerthcet** [comment]
if `kep` document required for this feature?

**Comment by alculquicondor** [comment]
That's open for discussion. Because it's a new field, it requires a feature gate or a best effort strategy for updating the field in the first release. Maybe a short KEP is worth.

**Comment by alculquicondor** [comment]
cc @soltysh @smarterclayton
