### ISSUE TITLE
daemonset: When node is shutdown, headless service exposing the daemonset pod is returning the corresponding pod ip address 

### ISSUE THREAD

**Issue by amitkatyal** [kubernetes/kubernetes#104424]
#### What happened:
When the node is shutdown, the headless k8s service exposing the daemonset is returning the IP address of the pod which is running on the shutdown node. This is resulting in an issue as the k8s application is trying to connect to the pod which doesn't exist.

#### What you expected to happen:
I understand that even though the node is shutdown daemonset pod in the running state is expected behavior but at least DNS resolution for the headless service should not return the IP address of the pod which doesn't exist.

#### How to reproduce it (as minimally and precisely as possible):
1. Deploy daemonset to the k8s cluster
2. Expose daemonset via the k8s headless service
3. Shutdown one of the node
4. Check the pod status, daemonset pod should be in the running state
5. Check the endpoints returned by the headless service, it returns the IP address of the pod which doesn't exist. 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: Esxi
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by thockin** [comment]
How are you shutting down the node?  All pods should be terminated and removed from endpoints.

**Comment by amitkatyal** [comment]
@thockin, I'm shutting down the node with the shutdown command. The issue is the daemonset POD running on that node. Since that POD remains in the running state, the headless service for the daemonset returns the IP address of the unreachable POD as well.

**Comment by ehashman** [comment]
As is, this is expected behaviour. Daemonset pods aren't evicted on normal node drain. Eventually the daemonset controller will update that pod's status given that the kubelet is no longer checking in.

Graceful shutdowns might help with this; that feature is currently in beta: https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

The feature is on by default but you will need to configure it in order to use it.

**Comment by ehashman** [comment]
/close

Feel free to reopen if the above does not help.

**Comment by amitkatyal** [comment]
> https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

@ehashman I understand that daemon sets pods will not be removed but is it expected for headless service exposing the daemonset pods to return the IP address of POD which is not reachable? BTW, if the daemon set is exposed via the normal service, then it doesn't return the IP of the daemon set POD which is not reachable so was wondering if the same needs to be addressed for the headless service as well. Thanks.
