### ISSUE TITLE
allow imagePullSecrets to reference secrets in other namespaces

### ISSUE THREAD

**Issue by neilharris123** [kubernetes/kubernetes#104415]
#### What would you like to be added:

Currently imagePullSecrets can only reference secrets in the same namespace. 

```  
imagePullSecrets:
  - name: dockerhub-credentials
 ```

I am proposing that, if a user has added the correct rbac rules to make a secret available to serviceAccounts in other namespaces, they should be able to reference that secret under imagePullSecrets, for example:

```  
imagePullSecrets:
  - name: kube-system.dockerhub-credentials
 ```
 
In the above example/proposal, the dockerhub-credentials secret exists in the kube-system namespace, but is accessible by a serviceAccount/pod in another namespace by prepending the namespace before the secret. 

#### Why is this needed:

Sometimes a single secret may be needed cluster-wide. For example, a single docker registry secret may be needed by applications in multiple namespaces. Currently, we need to create the same secret in every namespace. It would make more sense to be able to reference the secret and the namespace it is deployed in under imagePullSecrets (assuming the user has added the correct rbac resource to make it available to service accounts in other namespaces).

**Comment by liggitt** [comment]
/sig auth

Cross namespace secret references are intentionally not permitted in the API. The actor fetching the secrets (the kubelet) is authorized based on the secret reference in the pod alone. Pods are created by a variety of actors, including controllers that act across namespaces. The permissions of the user originating the pod spec are not usable for performing cross-namespace authz checks at pod runtime.

See previous discussions about cross namespace secret references/use:
* https://github.com/kubernetes/kubernetes/issues/57325
* https://github.com/kubernetes/kubernetes/issues/4954
