### ISSUE TITLE
Add tests for Windows Node Reboots

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#104428]
# Problem
As of now, when we reboot windows nodes, OVS goes down which breaks Antrea CNI.
I suspect reboots may have other effects on other services/CNIs in windows clusters.

Thus, we need a Reboot test case (azure has its own tests for node reboots, but theyre not upstreamed yet).

# Solution

So, lets add a `Distruptive` , `Slow` , `Serial` reboot test for `sig-windows` nodes. 

This is a good way for us to begin exersizing Priveliged containers.
However, if theres *another* way to get a windows node to reboot (from inside a container) we should explore it.

**Comment by jayunit100** [comment]
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/kubelet_stats.go <-- we can borrow from this as a template to get started

**Comment by weiwenli97** [comment]
There are two cases. One enables MHC while the other should disable MHC.

**Comment by mritunjaysharma394** [comment]
Hi @jayunit100, I think we can use cron-job or as mentioned above the MHC way( https://v2cloud.com/tutorials/how-to-configure-windows-to-reboot-automatically-on-schedule)

I also had a few more doubts, like here are some of the ways to reboot windows:

1. The shutdown command. This is a command line tool available on most any windows computer which will allow you to remotely reboot any computer joined to an active directory domain. All that’s required are the right credentials.

```
shutdown -r — reboots the system.
shutdown -m — specifies a remote computer to be shutdown/restarted/logged off (\computername)
shutdown -s — shuts the system down (and powers it off).
shutdown -l — logs the current logged on user off the system.
shutdown -t xx — where xx is number of seconds to wait untill shutdown/restart/logoff
```

2. Rundll32. This method invokes Windows’ native ability to run system DLL’s which can perform system functions.

```
rundll32.exe user.exe,ExitWindows – shuts down windows completely.
rundll32.exe user.exe,ExitWindowsExec – restarts windows.
rundll32.exe shell32.dll,SHExitWindowsEx x where x stands for:
0 – logoff
1 – shutdown
2 – reboot
4 – force
8 – power off
3. Powershell restart-computer command.
```
And yes, thank you so much for this https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/kubelet_stats.go as it gives a good template to understand what we can do. Please do suggest what method we can use if we have to consider any of the above methods to be executed programmatically. 

In fact, I would love to pick this issue and contribute, however, I have few initial doubts on how much complexity we can face while doing this inside container, would love to know more on this, thanks a lot!

**Comment by jayunit100** [comment]
thanks everyone ! ok i assigned wenli.... 

...  By the way this is wenlis first upstream issue, so will be a good leanring experience for her , lets try to give her some support along the way :)

**Comment by mritunjaysharma394** [comment]
All the best @weiwenli97 🥳 

Looking forward for all the amazing contributions you make 🚀

**Comment by weiwenli97** [comment]
Enable or disable MHC, the expected behavior for windows nodes reboot should be only reboot not re-created and rejoined.
I am trying host process pod to reboot windows node.

**Comment by jayunit100** [comment]
These tests should not be "aware" really of MHC... they need to be generic kubernetes tests, so they won'y have any references to Cluster API.

**Comment by weiwenli97** [comment]
Design on workload nodes Reboot tests:
1. Using host process pod to reboot the windows node(s)
2. After 5 minutes, checking whether the node(s) is ready or re-created. The workers should only reboot not re-create.

**Comment by ravisantoshgudimetla** [comment]
+1 on testing reboots. They may resurface underlying OS specific problems too.

**Comment by jayunit100** [comment]
@weiwenli97 can you post the code you have in a PR ? would like to start discussing this even if its not ready yet :)

**Comment by weiwenli97** [comment]
I have made a draft PR for it https://github.com/kubernetes/kubernetes/pull/104698/files. Could you please help review it? Thank you!
