### ISSUE TITLE
Disable Anonymous Requests by Default

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/kubernetes#104548]
This issue is meant to start a conversation around changing a default in Kubernetes. The NSA/CISA recently published a [Kubernetes hardening guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF). It covers a wide range of items, but one of the recurring themes is changing defaults to activate more secure settings in Kubernetes. As I read through these, I wondered why some of these settings were not already the default in Kubernetes. I’m sure there’s more to the story around these items than I know, but I thought it would be worthwhile to have a public discussion around each. I’ve set up a series of issues here. Linking between them for ease of reference:

- [Not mounting service tokens within pods](https://github.com/kubernetes/kubernetes/issues/104545) 
- [Close insecure port access to API server](https://github.com/kubernetes/kubernetes/issues/104546)
- [Encrypt secrets by default](https://github.com/kubernetes/kubernetes/issues/104547)
- Disable anonymous requests by default (this issue)
- [Turn on logging by default](https://github.com/kubernetes/kubernetes/issues/104549)
- [Provide a default seccomp profile](https://github.com/kubernetes/kubernetes/issues/104550)

## The Issue:
From the NSA/CISA Guide:
> “In Kubernetes 1.6 and newer, anonymous requests are enabled by default.” - 20

## NSA/CISA Proposed Fix:
> “Anonymous requests should be disabled by passing the `--anonymous-auth=false` option to the API server.” - 20

## Question for Discussion:
This was the default prior to 1.6, then was changed. Why was this changed? Do those reasons still make sense? Should it be changed back to disable anonymous requests by default?

**Comment by liggitt** [comment]
previous discussion in https://github.com/kubernetes/kubernetes/issues/43784

**Comment by apmarshall** [comment]
> previous discussion in https://github.com/kubernetes/kubernetes/issues/43784

@liggitt From just a quick skim of this: is the headline here that one of the principle functions of anonymous requests is liveness checking for the API?

**Comment by liggitt** [comment]
health/liveness is the primary request authorized to anonymous requests by default, yes
