### ISSUE TITLE
kube-controller-manager source code run error on ide

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#104539]
![)$E _BBG)E3_ Z}$B0) $N](https://user-images.githubusercontent.com/75164118/130569617-e9f9e7c3-94bc-4abd-a34d-55bf1987431b.png)
I wonder why this error occurs when I run the kube-controller-manager source code.

Is this a mistake because I didn't configure my cloud provider properly?

If I don't have a cloud provider, is there another solution?

**Comment by kerthcet** [comment]
how you start `kube-controller-manager`, maybe you should provide some details.

**Comment by pipijiev12** [comment]
> how you start `kube-controller-manager`, maybe you should provide some details.

I first binary deployed the K8S cluster and then successfully ran K8S. Next, I put the corresponding Kube-controller-Manager configuration parameters into the IDE program parameters and run the kube-controller-Manager source code. Finally, the IDE reports the error shown above. At this point, I don't know what the request resource is or who the request resource is from.

**Comment by neolit123** [comment]
IIRC, this error is common and temporary and should not be a concern.
this issue tracker is not for questions / support tickets.

please try asking on slack or the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
