### ISSUE TITLE
kubernetes should not count active_file as used memory, I have been waiting for 4 years!

### ISSUE THREAD

**Issue by zhxjdwh** [kubernetes/kubernetes#104533]
#### What happened:
kubernetes should not count active_file as used memory！
https://github.com/kubernetes/kubernetes/issues/43916

#### Environment:
- version: v1.15.3
- Cloud provider or hardware configuration: none
- OS : centos7.4
- Kernel: Linux master1 4.4.124-1.el7.elrepo.x86_64 #1 SMP Sun Mar 25 05:21:59 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MadhavJivrajani** [comment]
/remove-sig architecture
/sig node

@zhxjdwh thank you for bumping this up! You might be able to get the needed attention if you brought this up in a sig-node meeting. sig-node meets every Tuesday at 10am PT (there is a meeting today!). Should you decide to attend, the joining details and agenda doc (please add your agenda item to this) can be found [here](https://github.com/kubernetes/community/tree/master/sig-node#meetings).

**Comment by zhxjdwh** [comment]
Any news for this?

**Comment by ehashman** [comment]
This is a duplicate of the linked issue https://github.com/kubernetes/kubernetes/issues/43916

Closing.

/close
