### ISSUE TITLE
kube-controller-manager

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#104565]
How to solve the cloud node Lifecycle Controller service？？
![3UH`GO(F}Z6E5%9P4$GOICQ](https://user-images.githubusercontent.com/75164118/130716596-aab642a0-8b3c-43dc-bdd9-3656abf8f51b.png)

**Comment by pacoxu** [comment]
/kind support
/sig cloud-provider
Would you check if #87224 answered your question?

**Comment by neolit123** [comment]
closing as this tracker is not for questions:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

but feel free to continue the discusion.

/close
