### ISSUE TITLE
ci-crio-cgroupv1-node-e2e-conformance is flaking 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#104568]
#### Which jobs are flaking:
ci-crio-cgroupv1-node-e2e-conformance 

#### Which test(s) are flaking:
`[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api`

#### Testgrid link:
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance

#### Reason for failure:
Not yet known. 

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by adisky** [comment]
Most of the node periodic jobs are failing because of GO 1.17 update
https://github.com/kubernetes/test-infra/pull/23364

**Comment by SergeyKanzhelev** [comment]
it looks like it is green now. Let's re-open if this will start flaking again

/close
