### ISSUE TITLE
What do we want to do with the test "should have ipv4 and ipv6 node podCIDRs" 

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#104544]
The test ""should have ipv4 and ipv6 node podCIDRs" 

https://github.com/kubernetes/kubernetes/blob/c2a633e07ec6129398dfef95c9e011ea5535ded2/test/e2e/network/dual_stack.go#L71-L85

depends on a feature that is optional (one of the ipam controllers in the controller manager) 

https://github.com/kubernetes/kubernetes/blob/c2a633e07ec6129398dfef95c9e011ea5535ded2/pkg/controller/nodeipam/ipam/range_allocator.go#L373

We have discussed this previously, but since this is actually affecting downstream CIs I propose to remove it form the e2e framework.

For cloud providers, it can be moved to the own external cloud provider code, since the policy is to not host more tests with dependencies.

For the feature itself, it can easily be replaced by a unit or an integration test.

ref: https://bugzilla.redhat.com/show_bug.cgi?id=1996128

**Comment by aojea** [comment]
@aramase we have discussed it before, but now is affecting downstream CIs and is really a controller-manager test.
/cc @danwinship  @ricky-rav
/cc @BenTheElder for sig-testing visibility
/sig network

**Comment by aramase** [comment]
@aojea Removing the test sounds reasonable as it's specific to cloud providers. I'll review if we have enough unit tests for this and open a PR to remove it from e2e.

**Comment by aojea** [comment]
> I'll review if we have enough unit tests for this and open a PR to remove it from e2e.

We can add more if they don't exist, as a condition to remove the e2e

**Comment by aojea** [comment]
> > Removing the test sounds reasonable as it's specific to cloud providers
> 
> It's not specific to cloud providers. It's specific to different network plugins; some require it and some don't.

I think that the comment is related to the e2e framework skipper, that only skips by cloud provider,  but yeah, it is about CNIs
