### ISSUE TITLE
Simple services with external IPs on bare-metal

### ISSUE THREAD

**Issue by devurandom** [kubernetes/kubernetes#10456]
This is a follow up from #1161.

I use a bare-metal installation of CoreOS and Kubernetes, and would like to define an external (i.e. arbitrary) IP and port for which Kubernetes receives traffic and directs it to the associated pods. I can arrange for all nodes in the Kubernetes cluster to be physically connect to the right switches and thus have the possibility to receive traffic for that external IP. This seems like a very simple form of load balancing to me. How can I do it with Kubernetes?

Alternatively: Is it possible to make pods listen on a certain external (i.e. arbitrary) IP, in addition to the internal cluster IP? That way I could setup my own load balancer or "public" service.

**Comment by roberthbailey** [comment]
@thockin @ghodss @brendandburns

**Comment by devurandom** [comment]
In case this is not clear: I am missing clear hints on how to do this in the docs. An example would be great, too.

**Comment by fcantournet** [comment]
We use the following setup, I hardly suggest you do the same in prod but this gives you an idea:

We declare external services (services that need to be reachable from the outside of the kubernetes cluster) with `type: LoadBalancer`
This way they get a nodePort attributed in the nodePort range, at service creation on all nodes.

We then use vulcand (but you could use whatever) to load-balance incoming http(s) traffic over all nodes in the cluster. Routing is just pointing to the right Port, to any node.
After that kube-proxy does its magic, as if the traffic came from the inside of the cluster.
Vulcand is configured by a simple kube2sky-like go app : kube2vulcand that watch kubernetes apiserver.

A better way to do this would be to implement a proper cloudprovider in kubernetes, based on CoreOS & flannel. IIRC this is in the works right now, although I don't know who is actually working on it or how far along they are. Would be extremely very awesome though.

**Comment by thockin** [comment]
> We declare external services (services that need to be reachable from the outside of the kubernetes cluster)
> with type: LoadBalancer This way they get a nodePort attributed in the nodePort range, at service creation on
> all nodes.

@fcantournet  You can define it with type = NodePort, FYI :)

@devurandom We can't QUITE do what you want natively yet - you can expose a Service on every node, but you don't get to pick the port (well, you do, but you don't get the full port range to choose from).  You can do as @fcantournet suggests and run a load-balancer (but that balancer isn't HA either) to the NodePort.  As an alternative, see #10405 - you can actually get a host port, it's just a bit clumsy.  We'll do better after 1.0.

**Comment by devurandom** [comment]
Thanks for your answer.

What I don't understand is, why not, when it sounds so simple: Since the IP is static, k8s does not have to manage its allocation. So it could just schedule adding that IP to some kube-proxy's network interface, and to my experience it would start to work immediately.

I'll use fleet to setup a proxy container, for the time being. Then I can manage the actual worker with k8s, and can just remove the proxy when the rest of my service chain is also integrated with k8s.

**Comment by thockin** [comment]
"why not" is simply a matter of "hasn't been done yet".  What you describe is actually a pretty reasonable way to approach it, but we just don't have that level of expressiveness in the API yet,

**Comment by stephenwithav** [comment]
@thockin do you know if anyone's working on this yet?

**Comment by thockin** [comment]
AFAIK, not yet

**Comment by stephenwithav** [comment]
I'd like to take a look at it this weekend.  Other than reading the code and looking at the callgraph, can you offer any advice/words of wisdom?

**Comment by bprashanth** [comment]
> I use a bare-metal installation of CoreOS and Kubernetes, and would like to define an external (i.e. arbitrary) IP and port for which Kubernetes receives traffic and directs it to the associated pods. I can arrange for all nodes in the Kubernetes cluster to be physically connect to the right switches and thus have the possibility to receive traffic for that external IP. This seems like a very simple form of load balancing to me. How can I do it with Kubernetes?

@stephenwithav see https://github.com/kubernetes/contrib/tree/master/keepalived-vip, will not work on a cloud provider (yet) but should be realtively easy to hook it up, if you'd like to (it has a unicast mode, so all you need is a notify script to re-assign a static ip).

**Comment by stephenwithav** [comment]
thanks, @bprashanth.  @alebdf suggested looking at that repo, too--I'll take a longer look at it this weekend.

I do technically run on a cloud, a bunch of vpses, but they static ips.  Will that present a problem?

**Comment by bprashanth** [comment]
Does your vps allow you to float ips? i.e can you assign a the static ip to an instance, then reassign it to another via some (probably rest like) api?

**Comment by stephenwithav** [comment]
No, but I can delete an instance via a REST api and create a new instance with a new ip via the same ip.

**Comment by bprashanth** [comment]
Hmm, that's tricky. you essentially need to associate an external ip with an internal 10 dot. This internal 10 dot will get re-assigned from endpoint to endpoint through vrrp. Any creative ideas about how you can achieve that on your vps?

**Comment by bprashanth** [comment]
"that" meaning
> you essentially need to associate an external ip with an internal 10 dot.

**Comment by stephenwithav** [comment]
> Any creative ideas about how you can achieve that on your vps?

Possibly.  I need to read up on keepalived and vrrp. :)

**Comment by bprashanth** [comment]
Keepalived will give you really fast failover if you're using a baremetal setup and a gateway you control, because only the master will respond to arp. On a cloud provider where you're going to re-assign IPs via REST interface, you're stuck with the latency of that operation anyway. In such a scenario you may just want to do a more naive leader election for the sake of simplicity: http://blog.kubernetes.io/2016/01/simple-leader-election-with-Kubernetes.html

**Comment by smarterclayton** [comment]
There is work ongoing by @marun for OpenShift to implement a combination VRRP gateway for a subnet range that would offer simple LoadBalancer behavior on services with stable external IPs.  It would be a new type of controller, and we anticipate moving this into a community project sometime in the next few months.

**Comment by Nesh108** [comment]
I jump in and I would like to extend the question: my cloud provider (not AWS/GCP) doesn't support floating IPs out of the box, although I can contact them and they can assign it to the servers I need.

Would that be enough for my services to be able to pick up an external IP (they are currently stuck in <pending>)? If not, what steps do I need to take to be able to do so?
Also, would I need 1 floating IP for each service I intend to deploy?

**Comment by thockin** [comment]
If they can assign a floating IP to one or more cluster nodes, then the
existing iptables logic should kick in and handle the rest.

The only questions are which nodes and how many?  Because we can easily
program the LB in GCE (which is a true VIP unlike AWS) we assign it to
*all* nodes.  This gives us best resilience against a mode going down or
becoming overloaded.  But it has a cost.

The cost is that the traffic may arrive at a node that doesn't actually
have a backend for that service.  In that case we re-balance to a node that
does.  To make that second balance work we have to SNAT, which means we
lose the original client IP! This is bad, and we are working on a fix.

The fix, however, requires that the VIP only arrive at machines that
actually have a backend for the service.  Simple enough if I can
dynamically program the LB.  Much more complex if the VIP requires a human
to change.

So this request is well timed because we need to consider your case.  Is
the VIP routing ECMP or just one primary?  Does your provider offer VIP
healthcheck to remove bad machines?  Or some other way to know which VMs to
use or not use for a VIP?  @girishkalele

As to having an IP per Service, currently the answer is yes.  We have
considered trying to optimize that to share VIPs when ports don't overlap,
but it's pretty seriously complex, so we have not pursued it.

**Comment by eviloop** [comment]
Hello,
Sorry for reviving an old topic but I am a bit lost and i believe my use case is quite similar. I am unable to find much info on this

We are also running a bare-metal/non-integrated-LB cloud clusters. We do have a Loadbalancer, but simply not Kubernetes manipulated.

Our setup:
We have IPs that are dynamically allocated but not by Kubernetes. Therefore they are "static" for Kubernetes.

1) We dynamically create some nodes as labeled "edge" and dynamically connect it to the LB.
     It is possible to label all nodes as "edge", thus having them all connected to the LB

2) We run an NGINX Ingress Controller DaemonSet with nodeSelector set to "edge"

Having these IPs as ExternalIPs of a Service works locally for things like dashboard links but not at federation level. It also requires infrastructure knowledge.

Is there a way to configure at cluster level which IPs should be advertised as external IPs for a cluster ?

I found out that there is a service-loadbalancer in contrib, however it looks like ti suffers from the same fault.
https://github.com/kubernetes/contrib/tree/master/service-loadbalancer

**Comment by aledbf** [comment]
@eviloop please check https://github.com/kubernetes/contrib/tree/master/keepalived-vip
It allows you to expose one or more kubernetes services using IPs from your LAN.

**Comment by eviloop** [comment]
Thanks for the quick feedback ! 
I am a bit lost, 

1) I have a Openstack FIP - external network
2) a LB- external (FIP) and internal (VIP) network
3) node IPs with Ingress controllers connected to the LB - internal network

If the nodes were exposed on the external network direcly, keepalived-vip would solve my issue as i could assign a VIP to a service. Or did i misunderstood ?

My use case would be that all Loadbalancer type services from this cluster show the OS FIP as external endpoint (two networks above ) and this to be recognised at Federation level as a service endpoint.

**Comment by marun** [comment]
@eviloop I think the 'federation plane' updates dns with the external addresses assigned to a federated service.  The examples in the federation docs use services of type LoadBalancer with load balancer ip's but the docs indicate that ExternalIPs could work, too:

http://kubernetes.io/docs/user-guide/federation/federated-services/#creating-a-federated-service

Have you tried manually assigning the FIP address as an external ip on the service?  I suspect the federation plane could then use that to update dns.

**Comment by eviloop** [comment]
@marun This is a good idea, thanks ! I will try with both Loadbalancer Type AND ExternalIPs

In hindsight I realise now that my business case would be to force all cross-cluster traffic via Federation Ingress, while currently it is designed via Federation Services with direct communication between services

**Comment by psyhomb** [comment]
You can maybe try this concept with consul and traefik
https://github.com/psyhomb/k8s-deployer

More in depth explanation
https://github.com/psyhomb/k8s-deployer/tree/master/traefik#more-in-depth-explanation

**Comment by jpds** [comment]
This issue is also fixed by https://metallb.universe.tf/
