### ISSUE TITLE
Provide a Default seccomp Profile

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/kubernetes#104550]
This issue is meant to start a conversation around changing a default in Kubernetes. The NSA/CISA recently published a [Kubernetes hardening guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF). It covers a wide range of items, but one of the recurring themes is changing defaults to activate more secure settings in Kubernetes. As I read through these, I wondered why some of these settings were not already the default in Kubernetes. I’m sure there’s more to the story around these items than I know, but I thought it would be worthwhile to have a public discussion around each. I’ve set up a series of issues here. Linking between them for ease of reference:

- [Not mounting service tokens within pods](https://github.com/kubernetes/kubernetes/issues/104545)
- [Close insecure port access to API server](https://github.com/kubernetes/kubernetes/issues/104546)
- [Encrypt secrets by default](https://github.com/kubernetes/kubernetes/issues/104547)
- [Disable anonymous requests by default](https://github.com/kubernetes/kubernetes/issues/104548)
- [Turn on logging by default](https://github.com/kubernetes/kubernetes/issues/104549)
- Provide a default seccomp profile (this issue)

## The Issue:
From the NSA/CISA Guide:
> “One method for auditing container system calls in Kubernetes is to use the Secure Compute Mode (seccomp) tool. This tool is disabled by default but can be used to limit a container’s system call abilities, thereby lowering the kernel’s attack surface. Seccomp can also log what calls are being made by using an audit profile.” - 26

## NSA/CISA Proposed Fix:
> “A custom seccomp profile is used to define which system calls are allowed and default actions for calls not specified. To enable a custom seccomp profile within a Pod, Kubernetes admins can write their seccomp profile JSON file to the `/var/lib/kubelet/seccomp/` directory and add a `seccompProfile` to the Pod’s securityContext . A custom seccompProfile should also include two fields: `Type: Localhost` and `localhostProfile: myseccomppolicy.json`. Logging all system calls can help administrators know what system calls are needed for standard operations allowing them to restrict the seccomp profile further without losing system functionality.” - 26

## Question for Discussion:
Should Kubernetes provide a default seccomp profile? If so, what should this include? If not, is there a different method to limit system calls that could be included by default to improve Kubernetes security?

**Comment by MMerzinger** [comment]
I believe that this topic is already being addressed. Seccomp default profiles are an alpha feature of Kubernetes 1.22 (see #101943 and #81115). This setting was also a result of a third party security review (see #81146), and reference is made to #101943 to address this issue. As far as I understood #101943, the runtime standard is used as a fallback.

I'm not sure if this feature will be enabled by default when it leaves the alpha/beta phase, so I'm curious to see what the discussion yields.

**Comment by liggitt** [comment]
agree, I'd suggest closing this in favor of https://github.com/kubernetes/enhancements/issues/2413
