### ISSUE TITLE
race condition causing pods that require device plugin to be stuck at container creating

### ISSUE THREAD

**Issue by kubetester** [kubernetes/kubernetes#104581]
#### What happened:
This happens during node reboots.  Pods that was deployed prior to reboot would be redeploy. All pods are successful except for pods that require device plugin. The pod fails with multus error : AddNetwork: SRIOV-CNI failed to load netconf: LoadConf(), it keeps deleting the pod and restarting with the same error. If you look at the device plugin logs, those required devices have not been allocated.  Delete the pods and redeploying it fixes the issue.

#### What you expected to happen:
Expect all pods to recover

#### How to reproduce it (as minimally and precisely as possible):
Create a pod that use multus with sriov cni.  This should create a pod with 2 inferfaces ( one outbound and another to the vf ) . Reboot the node that has this pod. Issue doesn't always happen.  

#### Anything else we need to know?:
According to issue 64632, upon node restart, the allocatable field will be zero but it's not in this case.  On the fail case, we will see in the kubelet log that "manager.go:577] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found" happens before "6008 kubelet_node_status.go:70] Attempting to register node cn-515-20080500300007". This doesn't zero out the devices and deploys the pods that requires device plugins. 
Looking at the kubelet.go ( fastStatusUpdateOnce() ), it seems like it does updateRuntimeUp() before syncNodeStatus() but not in the func (kl *Kubelet) Run(updates <-chan kubetypes.PodUpdate). I'm not sure if it's intended.

#### Environment:
- Kubernetes version (use `kubectl version`): version 1.17.4
- Cloud provider or hardware configuration: Local hardware
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-66-generic
- Install tools:
- Network plugin and version (if this is a network-related bug):
Multus 3.1, sriov-cni:v2.2, sriov-device-plugin:v3.3.2
- Others:

**Comment by SergeyKanzhelev** [comment]
> > 1.17.4
> 
> < 1.20 is out of support. is this reproducible with newer versions?
> 
> /sig node

/triage needs-information

If no repro on latest versions available, we will close the bug.
