### ISSUE TITLE
Close Insure Port Access to API Server by Default

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/kubernetes#104546]
This issue is meant to start a conversation around changing a default in Kubernetes. The NSA/CISA recently published a [Kubernetes hardening guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF). It covers a wide range of items, but one of the recurring themes is changing defaults to activate more secure settings in Kubernetes. As I read through these, I wondered why some of these settings were not already the default in Kubernetes. I’m sure there’s more to the story around these items than I know, but I thought it would be worthwhile to have a public discussion around each. I’ve set up a series of issues here. Linking between them for ease of reference:

- [Not mounting service tokens within pods](https://github.com/kubernetes/kubernetes/issues/104545)
- Close insecure port access to API server (this issue)
- [Encrypt secrets by default](https://github.com/kubernetes/kubernetes/issues/104547)
- [Disable anonymous requests by default](https://github.com/kubernetes/kubernetes/issues/104548)
- [Turn on logging by default](https://github.com/kubernetes/kubernetes/issues/104549)
- [Provide a default seccomp profile](https://github.com/kubernetes/kubernetes/issues/104550)

## The Issue:
From the CISA/NSA Guide:
> “The Kubernetes API server runs on ports 6443 and 8080, which should be protected by a firewall to accept only expected traffic. Port 8080, by default, is accessible without TLS encryption from the local machine, and the request bypasses authentication and authorization modules.” - 15

## NSA/CISA Recommended Fix:
> “The insecure port can be disabled using the API server flag `--insecure-port=0`.” - 15

## Question for Discussion:
Is there a compelling reason to allow default unprotected (both unauthenticated and unencrypted) communication with the API on the localhost? If not, should this be disabled by default?

**Comment by liggitt** [comment]
This was done in 1.20. See #95856

> The kube-apiserver ability to serve on an insecure port, deprecated since v1.10, has been removed.
