### ISSUE TITLE
Change Defaults to Not Mount Service Tokens Within Pods Automatically

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/kubernetes#104545]
This issue is meant to start a conversation around changing a default in Kubernetes. The NSA/CISA recently published a [Kubernetes hardening guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF). It covers a wide range of items, but one of the recurring themes is changing defaults to activate more secure settings in Kubernetes. As I read through these, I wondered why some of these settings were not already the default in Kubernetes. I’m sure there’s more to the story around these items than I know, but I thought it would be worthwhile to have a public discussion around each. I’ve set up a series of issues here. Linking between them for ease of reference:

- Not mounting service tokens within pods (this issue)
- [Close insecure port access to API server](https://github.com/kubernetes/kubernetes/issues/104546)
- [Encrypt secrets by default](https://github.com/kubernetes/kubernetes/issues/104547)
- [Disable anonymous requests by default](https://github.com/kubernetes/kubernetes/issues/104548)
- [Turn on logging by default](https://github.com/kubernetes/kubernetes/issues/104549)
- [Provide a default seccomp profile](https://github.com/kubernetes/kubernetes/issues/104550)

## The Issue:
From the NSA/CISA Write-up:
> “By default, Kubernetes automatically provisions a service account when creating a Pod and mounts the account’s secret token within the Pod at runtime. Many containerized applications do not require direct access to the service account as Kubernetes orchestration occurs transparently in the background. If an application is compromised, account tokens in Pods can be gleaned by cyber actors and used to further compromise the cluster.“ - 11-12

## NSA/CISA Recommended Fix:
>“When an application does not need to access the service account directly, Kubernetes administrators should ensure that Pod specifications disable the secret token being mounted. This can be accomplished using the `automountServiceAccountToken: false` directive in the Pod’s YAML specification.” - 12

## Question for Discussion
If it is true that “many containerized applications do not require access to the service account,” should Kubernetes change its default behavior to not mount these tokens, thereby eliminating a potential attack vector, and let users who do need them turn this on?

**Comment by liggitt** [comment]
this seems like a duplicate of https://github.com/kubernetes/kubernetes/issues/57601
