### ISSUE TITLE
controller-manager stuck applying old over-quota LB config

### ISSUE THREAD

**Issue by wcurry** [kubernetes/kubernetes#104524]
#### What happened:

Customer with a Service type LB added more than 50 CIDRs to their `loadBalancerSourceRanges`. Our account quota is 100 rules per Security Group. The over-quota error didn't appear in the service's events as expected. I found controller-manager logs of the failed calls.

When the user brought their CIDR count back down below 50 and applied the manifest, the LB was not updated and the errors persist in the logs. AWS cloud trail logs show k8s still attempting to apply the over-quota configuration.

#### What you expected to happen:

Error appears in service's events and application of fixed manifest is reconciled.

#### How to reproduce it (as minimally and precisely as possible):

I attempted to reproduce in a dev cluster and saw expected behavior.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.19.10
- Cloud provider or hardware configuration: Self-managed AWS
- OS (e.g: `cat /etc/os-release`): FCOS 32.20201018.3.0
- Kernel (e.g. `uname -a`): 5.8.15-201.fc32.x86_64

#### Notes:

The LB currently has 46 CIDRs in its `loadBalancerSourceRanges` and the `kubectl describe svc` shows:

```
Events:
  Type    Reason                Age                       From                Message
  ----    ------                ----                      ----                -------
  Normal  EnsuringLoadBalancer  2m51s (x1723 over 5d23h)  service-controller  Ensuring load balancer
```

controller-manager is logging the following every 5 minutes:

```
I0823 16:47:44.059549       1 event.go:291] "Event occurred" object="namespace/loadbalancer" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: error authorizing security group ingress: \"RulesPerSecurityGroupLimitExceeded: The maximum number of rules per security group has been reached.\\n\\tstatus code: 400, request id: 0f6fd2d1-c63c-48a1-a31e-1009a124e5b1\""
```

AWS cloud trail confirms that the API calls are attempting to apply over 100 rules.

**Comment by wcurry** [comment]
Opened an issue in cloud-provider-aws as well. I can close this if it it doesn't belong here.

https://github.com/kubernetes/cloud-provider-aws/issues/252

**Comment by pacoxu** [comment]
/sig cloud-provider
/area provider/aws

And find some similar issues like #74828 #68684 #98097 and some discussions in
https://github.com/kubernetes/kubernetes/issues/68684#issuecomment-438316741

**Comment by kishorj** [comment]
@wcurry, if you update the `loadBalancerSourceRanges` attribute to contain fewer entries, does the controller recovers, or it is forever stuck with the error? This issue is similar to #98097.

**Comment by wcurry** [comment]
@kishorj It does not recover. We had to replace two LBs with new ones to get around this.
