### ISSUE TITLE
client-go: DefaultControllerRateLimiter should not use BucketRateLimiter

### ISSUE THREAD

**Issue by dramich** [kubernetes/kubernetes#104554]
#### What happened:

Currently when using `DefaultControllerRateLimiter` it adds `BucketRateLimiter` as one of the `MaxOfRateLimiter` limiters. 
This does not work as intended because there is no immediate sleep following the call to the limiter as seen in
https://github.com/kubernetes/client-go/blob/master/util/flowcontrol/throttle.go#L95 which does work correctly. 

The issue with the `BucketRateLimiter` in its current usage is there is no forget nor a sleep immediately following the `r.Limiter.Reserve().Delay()` call so if `MaxOfRateLimiter` is called thousands of times in a row, the timeout grows very quickly with no max. For example, if a clusters has 10k secrets and those are all enqueued using the `DefaultControllerRateLimiter` the `BucketRateLimiter` will end up with a 16 min wait before the tail end of objects can be enqueued and processed. 

#### What you expected to happen:

I would expect some max backoff to take affect. 

#### How to reproduce it (as minimally and precisely as possible):

This can be seen at https://play.golang.org/p/O9gdIylRB03

**Comment by luyou86** [comment]
@caesarxuchao @dramich @deads2k @liggitt 

1. is it possible to set maxWaitingTime for BucketRateLimiter?  when r.Limiter.Reserve().Delay() > maxWaitingTime, the return of BucketRateLimiter When()  is maxWaitingTime.

2. maxWaitingTime defined is 1000ms / r.limit * MAXQPS(5000) 

3. in this issue example (r.tokens = 100, r.limit = 10), if call When() 10000 times,  the tail end of the object is enqueued  waiting for 8.33 min. i'm not sure  how to set the value of MAXQPS

please help review it

**Comment by dramich** [comment]
@deads2k @luyou86 The fix merged to close this issue does not fix the underlying issue with the DefaultControllerRateLimiter. The bucket is not being used correctly so this does not work as intended, please read my issue description again as to what is actually happening.

**Comment by luyou86** [comment]
@deads2k is another fix  needed to solve this issue?

**Comment by deads2k** [comment]
A token bucket rate limiter will only refill at the defined rate.  If enough requeues are added, it will take a long time for the refill rate to clear the queue.

If a max wait is introduced, then requeues will be inserted into the queue faster than the refill rate of the token bucket rate limiter.  A max wait will violate the token bucket rate limiter and we want token bucket rate limiting behavior.
