### ISSUE TITLE
Encrypt Secrets By Default

### ISSUE THREAD

**Issue by apmarshall** [kubernetes/kubernetes#104547]
This issue is meant to start a conversation around changing a default in Kubernetes. The NSA/CISA recently published a [Kubernetes hardening guide](https://media.defense.gov/2021/Aug/03/2002820425/-1/-1/1/CTR_KUBERNETES%20HARDENING%20GUIDANCE.PDF). It covers a wide range of items, but one of the recurring themes is changing defaults to activate more secure settings in Kubernetes. As I read through these, I wondered why some of these settings were not already the default in Kubernetes. I’m sure there’s more to the story around these items than I know, but I thought it would be worthwhile to have a public discussion around each. I’ve set up a series of issues here. Linking between them for ease of reference:

- [Not mounting service tokens within pods](https://github.com/kubernetes/kubernetes/issues/104545)
- [Close insecure port access to API server](https://github.com/kubernetes/kubernetes/issues/104546)
- Encrypt secrets by default (this issue)
- [Disable anonymous requests by default](https://github.com/kubernetes/kubernetes/issues/104548)
- [Turn on logging by default](https://github.com/kubernetes/kubernetes/issues/104549)
- [Provide a default seccomp profile](https://github.com/kubernetes/kubernetes/issues/104550)

## The Issue:
From the NSA/CISA Guide:
> “By default, Kubernetes stores Secrets as unencrypted base64-encoded strings that can be retrieved by anyone with API access.” - 17

## NSA/CISA Proposed Fix:
> “Access can be restricted by applying RBAC policies to the secrets resource. Secrets can be encrypted by configuring data-at-rest encryption on the API server or by using an external Key Management Service (KMS), which may be available through a cloud provider. To enable Secret data-at-rest encryption using the API server, administrators should change the kube-apiserver manifest file to execute using the `--encryption-provider-config` argument.” - 17

## Question for Discussion:
If Kubernetes is providing a built-in mechanism for storing secrets, why shouldn’t it also store them encrypted by default? Does making this the default in any way preclude other options for secret protection, like RBAC or an external KMS? Does making this the default significantly change the use of secrets by Kubernetes or by services running on Kubernetes? Or are mechanisms for decrypting secrets on use already built into Kubernetes for when that flag is set on the API server?

**Comment by deads2k** [comment]
I don't see this issue as actionable without a KEP that describes what encryption should be used, how it should be generated, how it should be managed, how migration would happens, and how backup procedures would change.

If you're interested in such a feature, writing an enhancement in https://github.com/kubernetes/enhancements that addresses such concerns is a good next step.


/close
