### ISSUE TITLE
`[sig-network] EndpointSlice should have Endpoints and EndpointSlices pointing to API Server [Conformance]` E2E test fails when it shouldn't

### ISSUE THREAD

**Issue by jnummelin** [kubernetes/kubernetes#104612]
#### What happened:

`[sig-network] EndpointSlice should have Endpoints and EndpointSlices pointing to API Server [Conformance]` E2E test fails.
The test is implemented at: https://github.com/kubernetes/kubernetes/blob/9c1f9c3962717c6078fa166eeb76242a4cc1d751/test/e2e/network/endpointslice.go#L62

#### What you expected to happen:

I would expect the test pass with these objects in place:
```
$ kubectl get ep,endpointslice 
NAME                   ENDPOINTS           AGE
endpoints/kubernetes   1.2.3.4:6443   5h

NAME                                              ADDRESSTYPE   PORTS   ENDPOINTS      AGE
endpointslice.discovery.k8s.io/kubernetes-nw6h9   IPv4          6443    1.2.3.4   5h
```

AFAIK this fulfills the general requirement of the test that there's a corresponding endpointslice object with same addressing information as is on the endpoint object.

IMO the test should rather look for epslice which is owned by the `kubernetes` endpoint rather than relying on a hardcoded name.

#### How to reproduce it (as minimally and precisely as possible):

- Add `--endpoint-reconciler-type=none` flag to kube-apiserver
- Manually create the `kubernetes` endpoint with proper addressing for the api-server
- epslice "mirroring" create new endpointslice with name like `kubernetes-xyzxyz`

--> The test fails as it's hardcoded to look for endpointslice named `kubernetes`

#### Anything else we need to know?:

I'm working on a PR to provide a fix proposal

#### Environment:
- Kubernetes version (use `kubectl version`): 1.22.1
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: k0s
- Network plugin and version (if this is a network-related bug): kube-router 1.3.1
- Others:

**Comment by aojea** [comment]
/remove kind-bug
/remove kind-failing-test

The test is correct, apiserver must generates both endpoint and enpointslices with the special name "kubernetes" , that are the backends for the "kubernetes.default" service with the IP addresses of the apiservers. This special service "kubernetes.default" and its endpoints are used by clients with In-Cluster auto discovery.

I think that whatever cluster that is not generating the endpoint and endpointslices for the "kubernetes.default" service should not meet Conformance, at least I can't see how automatic in-cluster configuration will work without that ...

> Add --endpoint-reconciler-type=none flag to kube-apiserver

@thockin @lavalamp @liggitt  I only see `--endpoint-reconciler-type=none` option used for webhook tests, the other 2 reconcilers always create the endpoints and slices for "kubernetes.default"

https://github.com/kubernetes/kubernetes/blob/48da959dbff18bfef6e801bd8c8ab3c88b7a7650/pkg/controlplane/instance.go#L234-L249

should we clarify the goal of this "none" option?

**Comment by jnummelin** [comment]
> This special service "kubernetes.default" and its endpoints are used by clients with In-Cluster auto discovery.

Yes, I do understand this. And in our case this is true, there is a svc called `kubernetes` as there is also endpoints object called `kubernetes`. This makes the in-cluster discovery work. Otherwise we'd get much more errors in the conformance instead of this only one... :)

> I think that whatever cluster that is not generating the endpoint and endpointslices for the "kubernetes.default" service

In our case we're relying on the endpointslice mirroring to take care of creating the endpointslice object, which makes this test fail as it uses generated "suffix" on the object name.

I have not dived too deep (yet) into the internals of endpointslices but I fail to see how the endpointslice object name really matters when both svc and endpoint object does have proper name.

**Comment by aojea** [comment]
> Yes, I do understand this. And in our case this is true, there is a svc called `kubernetes` as there is also endpoints object called `kubernetes`

oh, this seems interesting then ... who is creating the corresponding endpoint? can you paste a kubectl get endpoints -o yaml?

**Comment by aojea** [comment]
this is how it looks like in my cluster
```sh
$kubectl get endpointslices kubernetes -o yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 172.18.0.2
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  creationTimestamp: "2021-08-26T10:07:23Z"
  generation: 1
  labels:
    kubernetes.io/service-name: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "219"
  uid: 22f6a6b6-1c07-424d-8023-f681f653519c
ports:
- name: https
  port: 6443
  protocol: TCP

$ kubectl get endpoints kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2021-08-26T10:07:23Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
  resourceVersion: "217"
  uid: 4dfb5b74-1f3a-4bff-b295-94ba2121474f
subsets:
- addresses:
  - ip: 172.18.0.2
  ports:
  - name: https
    port: 6443
    protocol: TCP
```

**Comment by jnummelin** [comment]
> who is creating the corresponding endpoint?

In our case (k0s distro) it's our custom controller that is triggered when the controlplane is configured in HA mode. So this basically sets the api to mode `--endpoint-reconciler-type=none`. When our controller runs it has a configured LB address which it resolves to IP address(es) and created the corresponding EP object. We do NOT create the endpointslice as we rely on the mirroring functionality to let it create and sync it.

Here's the object details:
```
$ kubectl get endpoints kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2021-08-26T13:59:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:subsets: {}
    manager: k0s
    operation: Update
    time: "2021-08-26T13:59:08Z"
  name: kubernetes
  namespace: default
  resourceVersion: "306"
  uid: 3d08ba2d-f17d-4037-8a49-20e5bfa99371
subsets:
- addresses:
  - ip: 1.2.3.4
  ports:
  - name: https
    port: 6443
    protocol: TCP
```

```
$ kubectl get endpointslices
NAME               ADDRESSTYPE   PORTS   ENDPOINTS      AGE
kubernetes-nw6h9   IPv4          6443    1.2.3.4   3d18h

$ kubectl get endpointslices kubernetes-nw6h9 -o yaml
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 1.2.3.4
  conditions:
    ready: true
kind: EndpointSlice
metadata:
  creationTimestamp: "2021-08-26T13:59:13Z"
  generateName: kubernetes-
  generation: 1
  labels:
    endpointslice.kubernetes.io/managed-by: endpointslicemirroring-controller.k8s.io
    kubernetes.io/service-name: kubernetes
  name: kubernetes-nw6h9
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Endpoints
    name: kubernetes
    uid: 3d08ba2d-f17d-4037-8a49-20e5bfa99371
  resourceVersion: "383"
  uid: bd298b8f-4165-4f16-8b06-ae142c7778e7
ports:
- name: https
  port: 6443
  protocol: TCP
```

Reading the code for API built-in endpoint reconcilers I see they set `endpointslice.kubernetes.io/skip-mirror: "true"` and create the endpointslice object by themselves. Yes, we could do that too in k0s but I fail to see why the name of the endpointslice object really matters at all.

**Comment by liggitt** [comment]
I agree the conformance test should not be looking up endpointslice by name. It should be using a label selector of `kubernetes.io/service-name=kubernetes` to locate the endpointslices.

**Comment by aojea** [comment]
> I agree the conformance test should not be looking up endpointslice by name. It should be using a label selector of `kubernetes.io/service-name=kubernetes` to locate one or more endpointslices and verifying the ports and endpoints across them.

Fair enough, on the good side this also will simplify the KEP from @danwinship https://github.com/kubernetes/enhancements/pull/2622/ to dual-stack the apiserver

@robscott you are the expert in this area, can you PTAL at this discussion?

/kind failing-test

**Comment by aojea** [comment]
hmm @liggitt 
https://github.com/kubernetes/kubernetes/blob/9c1f9c3962717c6078fa166eeb76242a4cc1d751/test/e2e/network/endpointslice.go#L55-L60

the test description explicitly says the name of the object has to be "kubernetes", if the name is mandatory the test is correct, otherwise we need to rewrite the test description and talk with conformance people
/area conformance

**Comment by liggitt** [comment]
the description should be rewritten... the test is enforcing stricter requirements on endpointslices than required/expected
