### ISSUE TITLE
E2E test output should provide more useful stack traces

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#104685]
*Disclaimer:* This is something that seems highly useful for users and simple to implement. I intend to complete this myself.

#### What would you like to be added:
When looking at the e2e test results you see stack traces like:
```
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/...
```
That's useful, but not directly so since that is not a file or URL you can jump to since it is relative to the dockerized binary in the image.

Instead, we should just replace those paths with useful ones that can jump to a file or URL for faster debugging. I suggest a URL to the github code since locally a user may have a different path to their k8s code.

For example, it would look like:
```
https://github.com/kubernetes/kubernetes/blob/v1.22.1/test/e2e/kubectl/kubectl.go#L258
```

### Notes

Two possible places this could be implemented would be in the junit reporter and the other would be in the standard log output.  I propose just changing the junit since this is reported as the "results". The raw logs could remain unchanged which would prevent any bugs from interfering in the raw output. In addition, the junit is already something we make choices about and form ourselves, so it seems intuitive to make quality of life changes there and it is also extremely easy to do since all the junit processing is one in 1-2 files.

/sig testing
/area test
/area e2e-test-framework

**Comment by johnSchnake** [comment]
I would also consider changing the raw output too since, tbh, that is more readable. Now that I think of it, the junit output isnt normally what you scroll through since it just encodes things like new lines as `\n` so its hard to read.

**Comment by BenTheElder** [comment]
> I would also consider changing the raw output too since, tbh, that is more readable. Now that I think of it, the junit output isnt normally what you scroll through since it just encodes things like new lines as \n so its hard to read.

The Junit is expandable / rendered by prow.k8s.io, any other junit tool can also decode the strings?

>  Instead, we should just replace those paths with useful ones that can jump to a file or URL for faster debugging. I suggest a URL to the github code since locally a user may have a different path to their k8s code.

We can't assume that the sources came from GitHub (many vendors are building forks, people develop firewalled, etc.)

We should probably be building kubernetes binaries with -trimpath at some point ... cc @dims.

I don't think the stack trace paths are in-scope for SIG-testing, they're just go stack information, this should be handled at the binary level (SIG release)

/sig release

**Comment by dims** [comment]
@BenTheElder we do use `trimpath` see https://cs.k8s.io/?q=trimpath&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes (specifically hack/lib/golang.sh)
