### ISSUE TITLE
Default Scheduler Enhancement: add pods scheduling tracker metrics as a feature gate to track a pod scheduling lifecycle

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/kubernetes#104684]
#### What would you like to be added:
In the latest version of default scheduler, it's difficult to track a pod scheduling process unless setting up a high log level.
Can we record pods scheduling process in metrics(e.g. whether a node pass the filter plugins and the score for this node)? 
The metrics could be like:
```
node_scheduling_pass_filter{node="10.0.0.1", pod_name="test-xxxx", pass_node_ports="true", pass_node_resources_fit="true"} 

node_scheduling_score{node="10.0.0.1", pod_name="test-xxxx", score_node_resources_least_allocated="10",score_node_resources_most_allocated="50"} 

```

#### Why is this needed:
To make the pods scheduling process easier to track.

P.S. It's an idea to bring up the discussion.

**Comment by ahg-g** [comment]
We can't do that using metrics, this will generate high cardinality.

**Comment by lianghao208** [comment]
> We can't do that using metrics, this will generate high cardinality.
@ahg-g 
I agree, using metrics to record every pod's scheduling process could generate high cardinality. I'm wondering if there is a better way to track a pod's  scheduling process without analyzing scheduler's log?

**Comment by Huang-Wei** [comment]
> I'm wondering if there is a better way to track a pod's scheduling process without analyzing scheduler's log?

That sounds like a conflicting requirement :) Metrics are aimed to show a scheduler's overall scheduling health, in an aggregated and high level. While for an individual pod, I think analyzing the log is the right way - the work will be easier once we finish the structured logging migration.

**Comment by lianghao208** [comment]
> That sounds like a conflicting requirement :) Metrics are aimed to show a scheduler's overall scheduling health, in an aggregated and high level.
Thank you for the reply, I agree.

> While for an individual pod, I think analyzing the log is the right way - the work will be easier once we finish the structured logging migration.

 I noticed the structured logging migration is in progress. Do you think it needs a dynamic mechanism( could be a signal or a http request send to the scheduler without modifying the args or restarting the process) to level up the log level? 
Because the default log level for scheduler is not high enough to cover the details, and modifying the log level args is inconvenient when it comes to multiple scheduler pods.

**Comment by lianghao208** [comment]
@Huang-Wei @ahg-g 
Thank you for the reply!
