### ISSUE TITLE
Nodes become NotReady after adding ExternalIPs in ClusterIP or NodePort service

### ISSUE THREAD

**Issue by mjkota** [kubernetes/kubernetes#104679]
> 

#### What happened: 
Nodes went in NotReady state after creating a service type ClusterIP or NodePort with ExternalIPs set to worker nodes. The issue is observed with Kube-Proxy is running in IPVS mode. Even the nodes added as ExternalIPs become non-routable from other nodes in the cluster.
```kubectl get svc
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP                     PORT(S)        AGE
kubernetes   ClusterIP   10.96.0.1        <none>                          443/TCP        23d
nginx        NodePort    10.104.206.115   10.128.149.177,10.128.149.199   80:31811/TCP   44s
```
```
kubectl get nodes -w
NAME                STATUS   ROLES                  AGE   VERSION
mudit-cks-master    Ready    control-plane,master   23d   v1.21.3
mudit-cks-worker1   Ready    <none>                 23d   v1.21.3
mudit-cks-worker2   Ready    <none>                 23d   v1.21.3
mudit-cks-worker1   NotReady   <none>                 23d   v1.21.3
mudit-cks-worker1   NotReady   <none>                 23d   v1.21.3
```
The same work fines if the Kube-Proxy is running in iptable mode.

#### What you expected to happen:
The Nodes should not go in the NotReady state.

#### How to reproduce it (as minimally and precisely as possible):
Add ExternalIPs in ClusterIP or NodePort service with Kube-Proxy running in IPVS mode.

#### Anything else we need to know?:
Created the cluster with kubeadm.

#### Environment:
- Kubernetes version (use `kubectl version`): 
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: OnPremise VM.
- OS (e.g: `cat /etc/os-release`): 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):  ``` Linux mudit-cks-master 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux ```

- Install tools:
- Network plugin and version (if this is a network-related bug): Calico
- Others:

**Comment by uablrek** [comment]
So, the ExternalIPs `10.128.149.177,10.128.149.199` are actual node addresses?

If so, that is an invalid configuration, and further for a `NodePort` service it is unnecessary. Traffic to any `node-ip:nodePort` will be handled anyway.

What are you trying to accomplish?

**Comment by thockin** [comment]
Likely this causes iptables rules which block anything except the service port on that IP.  I don't think this is what you want. I echo Lars - What are you trying to accomplish?

**Comment by mjkota** [comment]
@uablrek and @thockin Actually this is my customer set up and they are using NFS CSI. In order to do so there are 3 storage nodes that act as NFS storage providers but at the same time, they are attached as worker nodes in the cluster.
Now customer has their application which creates a NodePort and ClusterIP type service with NFS node IP set as externalIPs.
I know this is not the correct usage for clusterIP or NodePort, better to rely on configMap. But since this works in Kube-proxy running in iptable mode it's worth looking at this in IPVS mode as well.

**Comment by uablrek** [comment]
So, the externalIP setting is for convenient read from some other application? It has not anything to do with traffic?

That it happens to work for iptables out of luck. If any app uses a port that is also used in main netns it will likely fail.

For ipvs the addresses are actually assigned to another interface (ipvs-kube0) creating a conflict.

And no, I will not make extensive work and test to allow an invalid configuration (which may be impossible for ipvs) if the purpose is just convenient read for another app.

I will close this issue. Please re-open if there some traffic related use-case.

/close
