### ISSUE TITLE
gce-master-scale-performance is failing

### ISSUE THREAD

**Issue by jupblb** [kubernetes/kubernetes#104657]
#### Which jobs are flaking:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance
#### Which test(s) are flaking:
`gce-master-scale-performance` 08/29
#### Testgrid link:
https://k8s-testgrid.appspot.com/sig-scalability-gce#gce-master-scale-performance
#### Reason for failure:
There has been a single (third, considering SlowCount) slow request.
#### Anything else we need to know:
[Perf dash](http://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=APIServer&metricname=LoadResponsiveness_PrometheusSimple&Resource=jobs&Scope=resource&Subresource=&Verb=POST) shows no long lasting issue with the latency.

/assign
/sig scalability

**Comment by jupblb** [comment]
The next run is passing.

**Comment by leonardpahlke** [comment]
this flaky test seems to be resolved /close
