### ISSUE TITLE
Preserving unknown fields in CRD version v1

### ISSUE THREAD

**Issue by Shreya027** [kubernetes/kubernetes#104628]
I am trying to preserve unknown fields dropped in CRD version v1 by default. I tried adding   `preserveUnknownFields=true` in the CRD_OPTIONS as shown below:

`CRD_OPTIONS?="crd:trivialVersions=true,crdVersions=v1beta1,preserveUnknownFields=true" `However, once I added this and applied the changes, I get the following error in the terminal:

                    __you may only set PreserveUnknownFields to true with v1beta1 CRDs
                    Error: not all generators ran successfully__
                    
I figured out that another option can be using` // +kubebuilder:pruning:PreserveUnknownFields` on top of type structs to preserve fields. But I wanted to know if there was a more general way to do this, instead of adding it for all types. Also, I want  to confirm if ` // +kubebuilder:pruning:PreserveUnknownFields` annotation preserves unknown fields for nested struct fields  inside the outer struct for which the annotation is applied.

**Comment by liggitt** [comment]
in a v1 CRD, you can add the following to the top-level of the schema to preserve unknown fields for that level:

```
x-kubernetes-preserve-unknown-fields: true
```

See https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning for details.

Questions about the kube-builder annotations would be better to ask in the [kube-builder repo](https://github.com/kubernetes-sigs/kubebuilder) or [slack channel](https://slack.k8s.io/#kubebuilder)

/close

**Comment by liggitt** [comment]
> I want to confirm if ` // +kubebuilder:pruning:PreserveUnknownFields` annotation preserves unknown fields for nested struct fields inside the outer struct for which the annotation is applied.

It only preserves unknown fields (and subtrees of those unknown fields) for that level
