### ISSUE TITLE
RunAsUsername Windows test fails with containerD master

### ISSUE THREAD

**Issue by adelina-t** [kubernetes/kubernetes#104683]
#### Which jobs are failing:

https://testgrid.k8s.io/sig-windows-networking#ltsc2019-containerd-flannel-sdnoverlay-master

#### Which test(s) are failing:

[Feature:Windows] SecurityContext should not be able to create pods with unknown usernames"

#### Reason for failure:

This job uses containerd built from master. Recently, containerd introduced this commit ( https://github.com/containerd/containerd/commit/25644b4614d607199befa3c83c86540496a6e4f9 ) that enables a user to be set for running the sandbox. This causes the test to fail because the checks in the tests all look at the container status, but in this case, the work container doesn't get created since the failure is at the sandbox level.

**Comment by jsturtevant** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/104635

**Comment by jsturtevant** [comment]
closing this as duplicate. see https://github.com/kubernetes/kubernetes/issues/104635#issuecomment-910415666 for discussion at sig-node
