### ISSUE TITLE
sessionAffinity based on ClientIP, is not maintained for a new UDP request followed by TCP request from same client

### ISSUE THREAD

**Issue by Nish0808** [kubernetes/kubernetes#104659]
#### What happened:

sessionAffinity based on ClientIP, is not maintained for a new UDP request followed by TCP request coming from same client.

Lets take two independent Kubernetes clusters **Cluster 1 & Cluster 2** , Each of them has two replicas of same application Pod. Like 
**Cluster 1 : Pod A & Pod B** 
**Cluster 2 : Pod C & Pod D**. 
Application code in Pod A(client) wants to connect to any Pod running in cluster 2 via NodePort/Loadbalancer service over TCP protocol where the response would contain a UDP Port stating the client(Pod A) to initiate a new UDP socket on supplied UDP port for further communications.

To summarize the need:
**Pod A -> Pod C   over TCP and response carries a UDP port**
**Pod A -> Pod C   over UDP port captured in response**

#### What you expected to happen:
When I use **sessionAffinity: ClientIP** in service spec at Server side cluster, it does not redirect the TCP and UDP calls coming from same client to one single pod. Example: First **TCP** call goes to **Pod C** and the next **UDP** call goes to **Pod D**.
I am looking for both TCP and UDP calls to fall on same pod.

Could someone please let me know, if above mentioned behavior is working as expected given ClientIP  based session-affinity does not work with mix of protocols.
or, does this seem to be a valid bug?

Thanks!

**Comment by uablrek** [comment]
Related https://github.com/kubernetes/kubernetes/issues/103000

**Comment by uablrek** [comment]
You may experiment with `proxy-mode=ipvs` and `--ipvs-scheduler=sh` (source hashing). While that will solve this problem it may well cause a whole bunch of new ones since `ipvs-scheduler` is global (default round-robin, "rr").

**Comment by Nish0808** [comment]
Use-case:
There is a proprietary transfer protocol where a client performs TCP handshake with server and server sends a UDP port in the response. Client receives the response, fetch the port and initiate a new UDP socket on that port for data transfer.
Here, both TCP and UDP calls needs to go on same server which is not happening if there are multiple replicas of server running behind a Kubernetes service.

**Comment by Nish0808** [comment]
@uablrek I am not sure if I am allowed to do such change on a managed K8s cluster or on RedHat OpenShift platform.

**Comment by uablrek** [comment]
If this is cluster internal traffic, use a headless service. I little bit of extra work for load-balancing but it will work for sure since it is pod-pod without any service-ip.

**Comment by Nish0808** [comment]
@uablrek , it's actually inter k8s cluster communication. Client and Server resides on different Kubernetes clusters.

**Comment by aojea** [comment]
From my reading, I think that this is a problem of using stateless deployments for workloads that are not stateless.
It this not a stateful application, that everything that goes to PodA has to go to PodA always?

I wonder if statefulset can help here https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/ :thinking:

**Comment by Nish0808** [comment]
Even if I use statefulset, this problem still persists as to perform a data transfer, somehow I need to route the request to same pod which served the TCP request. On service spec, setting sessionAffinity to ClientIP is not helping as the client is same but the protocol (endpoints) are different, isn't it?

**Comment by aojea** [comment]
> Even if I use statefulset, this problem still persists as to perform a data transfer, somehow I need to route the request to same pod which served the TCP request. On service spec, setting sessionAffinity to ClientIP is not helping as the client is same but the protocol (endpoints) are different, isn't it?

yeah, agree with the problem, I'm trying to understand if there is a pattern that current APIs are not covering and that we should generalize, there was several issues of people asking to change Services behavior for active/passive deployments, those workloads are stateful too ... maybe current API is not handling well this scenarios? or is just an implementation problem? if we change the implementation do we break something?

**Comment by thockin** [comment]
Can we merge this with https://github.com/kubernetes/kubernetes/issues/103000 ?

**Comment by thockin** [comment]
Closing as dup - see #103000
