### ISSUE TITLE
Pods getting scheduled irrespective of insufficient resources

### ISSUE THREAD

**Issue by krahil** [kubernetes/kubernetes#104626]
**What happened:**
cluster info: 1 master, 1 worker node, kubernetes version: v1.22.1

Pods are failing with status "OutOfpods" after sometime.
I am submitting few jobs targeted on a single node. At max, I am able to see 17 pods running based on requested resources. But not all pods successfully completes. Few of them goes into "OutOfpods" status after sometime. I have tried limiting maximum pods on this node to 10, but still the error persists. After limiting the number of pods to 10, I am seeing only 8 pods in running. At the end of entire job, I am left with many such "OutofPods" status pods.
Ideally, pods should wait in scheduling by default and not fail because of insufficient resource.

kubectl describe pod:
<img width="789" alt="pod_scheduling_issue" src="https://user-images.githubusercontent.com/89634117/131108654-c52fbbf7-65db-4891-a0ea-95e840ab029d.PNG">

kubectl describe node:
![image](https://user-images.githubusercontent.com/89634117/131108583-d948134a-eb0a-4597-afd8-9b9d693f150a.png)

**Environment:**
OS: CentOS 7.9
Kubernetes version: 1.22.1

**Anything else we need to know?**
I have a cluster with old kubernetes version 1.13 of which this worker node was earlier a part of. That cluster works absolutely fine and this worker node used to generate 17 pods there also.

My new cluster v1.22.1 configuration is default with NO additional parameters set in kubelet, which we expect after installation of kubernetes. All other system pods are working fine.

**What is expected to happen:**
Pod should only be scheduled if resource quota matches with the request, otherwise remain in scheduling queue (Pending state).

**Comment by krahil** [comment]
Thank you so much @ahg-g for such a quick response and relating this to valid accepted issue in v1.22 release version. I have gone through the related issue #104560 and it matches the scenario I have been observing. Seems the fix is still in progress.

Thanks again!

**Comment by dimakow** [comment]
@krahil can this issue be closed then?

**Comment by krahil** [comment]
Sure, this issue can be closed now.
