### ISSUE TITLE
Secrets bug

### ISSUE THREAD

**Issue by LIL-Raps** [kubernetes/kubernetes#104678]
#### What happened:

When I created a secret with data values as "true" without encoding and apply to the cluster, it doesn't send an error.  

#### What you expected to happen:

I expected that my apply doesn't work.

#### How to reproduce it (as minimally and precisely as possible):

For reproducing you should deploy secrets with value as "true".

#### Anything else we need to know?:

There is a screenshot with the bug. 

![Screenshot from 2021-08-31 13-18-30](https://user-images.githubusercontent.com/34604269/131485764-a01e081a-fb4c-4f93-b707-bbb717c04c55.png)

#### Environment:
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: AWS isn't eks. 
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`):  5.8.0-1041-aws 
- Install tools: kubespray
- Network plugin and version (if this is a network-related bug): calico
- Others:

**Comment by kerthcet** [comment]
it works as expected, if you want to encode the secret, you may work like this:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
stringData:
  default: 'true'
```

**Comment by LIL-Raps** [comment]
> it works as expected, if you want to encode the secret, you may work like this:
> 
> ```
> apiVersion: v1
> kind: Secret
> metadata:
>   name: secret-sa-sample
> stringData:
>   default: 'true'
> ```

I do not understand why this opportunity exists. For what purposes can it be used?

**Comment by balan2010** [comment]
I was expecting below code will throw an error because data value of the secret default is not base64 encoded.  According to secrets documentation secret has to be base64 encoded.  here is the type definition for secret https://github.com/kubernetes/kubernetes/blob/67fa7b278249f12dd29d5b749fe7f973e8f3e0e1/staging/src/k8s.io/api/core/v1/types.go#L5856

`apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
data:                                        
   default: true`

**Comment by kerthcet** [comment]
I'll add some validation before successfully create secrets. I'll keep up with my progress.

**Comment by kerthcet** [comment]
after some investigating, i found it's not possible to verify whether the value if `base64` decoded, only we can do is to confirm whether the value is an candidate of base64 encoded, for `true` is actually `base64` format. But I can add some verifications, e.g. the length of the value should be `a multiple of 4 characters` and the characters is a set of `A-Z, a-z, 0-9, +, /` as well as padding `=`, but I was doubt about the  effect and importance(actually, server side will also check).  In summary, `true` will not be detected as an invalid base64 value.

WDYT @LIL-Raps @balan2010

**Comment by LIL-Raps** [comment]
@kerthcet Hi sounds like it might be possible to implement verifications as you provided, but I don't understand why you said that "true" will not be detected as an invalid base64 value if you will verify value within the verifications rules, "true" will be detected as an invalid base64 value.

**Comment by kerthcet** [comment]
because 'true' met all the needs `base64` encoded code required, a set of `A-Z, a-z, 0-9, +, /`, and containing 4 characters.  I can't find the way to  distinguish between them.

**Comment by LIL-Raps** [comment]
Oh yeah sorry. Well if make 'true' as an exception?

**Comment by kerthcet** [comment]
this is a special case, as `true` has a special meaning however this is not a general solution, let's hear from someone else. I'm fine to add `true verification`.

**Comment by liggitt** [comment]
/remove-sig security
/sig api-machinery

The values in the data map of a Secret object must be base-64 encoded, as noted in the [API documentation](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/secret-v1/) and [examples](https://kubernetes.io/docs/concepts/configuration/secret/). Special-casing and forbidding the base-64 value `true` is not backwards-compatible.
