### ISSUE TITLE
after restart network  nodeport cannot access,or telnet ip:nodeport failure

### ISSUE THREAD

**Issue by kql250520** [kubernetes/kubernetes#104643]
#### Which jobs are failing:
after restart network  nodeport cannot access,or telnet ip:nodeport failure

CentOS Linux release 7.5.1804 (Core),GitVersion:"v1.13.3 
claas/kube-proxy:v1.13.3

![image](https://user-images.githubusercontent.com/30395964/131206305-380ebfbb-3659-43d5-9337-359432c7ada1.png)

Three-Way Handshake， the latest ack failure

**Comment by pacoxu** [comment]
You may provide more details about how to reproduce it if this indicates to be a kube-proxy bug. 

```
[root@10-7-101-4 ~]# curl 10.7.101.4:32212 | head -n 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4091  100  4091    0     0   901k      0 --:--:-- --:--:-- --:--:--  998k
<!DOCTYPE html>
<html>
[root@10-7-101-4 ~]# kubectl get svc -n dce-system
NAME                              TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
dao1-2048-2048                    NodePort    10.96.2.124   <none>        80:32212/TCP   3h32m
[root@10-7-101-4 ~]# systemctl restart network
[root@10-7-101-4 ~]# curl 10.7.101.4:32212 | head -n 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4091  100  4091    0     0  3602k      0 --:--:-- --:--:-- --:--:-- 3995k
<!DOCTYPE html>
<HTML>
```

I tried your steps but it can work in my cluster.

BTW, the official troubleshooting guide is in https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/

**Comment by thockin** [comment]
What does "restart network" mean here?  This is clearly not a systemic issue - we'd be drowning in bug reports.

**Comment by thockin** [comment]
I'm going to close this - if you feel there's more information to provide, please reopen
