### ISSUE TITLE
kubernetes auth error: impersonation request has been denied, group header value is not allowed in roles

### ISSUE THREAD

**Issue by dmitry-mightydevops** [kubernetes/kubernetes#104637]
#### What happened:

```bash
➜ k auth can-i --as=dmitry --as-group=system:master get pods -n argo-cd
Error from server: impersonation request has been denied, group header "system:master" value is not allowed in roles

➜ k get clusterrolebinding system:master -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-03-02T00:48:21Z"
  name: system:master
  resourceVersion: "866"
  uid: 62205f1f-7aa7-43e2-903d-4c6ebd3d21a5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:master
  namespace: default
```

so group `system:master` exists.

#### What you expected to happen:

```
➜ k auth can-i --as=dmitry --as-group=system:master get pods -n argo-cd
```

to return **yes** or **no** per query
 
#### How to reproduce it (as minimally and precisely as possible):

I'm using AWS EKS 1.21 cluster 

#### Environment:
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: AWS EKS 1.21

**Comment by liggitt** [comment]
that message does not appear in the kubernetes codebase... are you using teleport? I see that error message at https://github.com/gravitational/teleport/blob/master/lib/kube/proxy/forwarder.go#L1146

**Comment by dmitry-mightydevops** [comment]
Yes correct using teleport.

**Comment by liggitt** [comment]
Thanks for confirming, sounds like an issue on the teleport side
