### ISSUE TITLE
Kubernetes 'Indexed-Job' does not works

### ISSUE THREAD

**Issue by seyoongit** [kubernetes/kubernetes#104644]
my problem is summarized [here](https://stackoverflow.com/questions/68958322/how-to-use-kubernetes-indexed-job).

I have no idea why this doesn't works.

**Comment by yxxhero** [comment]
Note that completion mode is an alpha feature in the 1.21 release. To be able to use it in your cluster, make sure to enable the IndexedJob feature gate on the API server and the controller manager. @seyoongit

**Comment by seyoongit** [comment]
```
minikube --feature-gates=IndexedJob=true 
```
works well. thanks!
