### ISSUE TITLE
Credentialprovider infinite loop on k3s over GCE vm

### ISSUE THREAD

**Issue by SimoneLazzaris** [kubernetes/kubernetes#104625]
#### What happened:

Library `credentialprovider` initialization is stuck in infinite loop:  we found a problem when running on a k3s instance on a gce VM: the library never stop initialization, triggering an infinite loop on the runWithBackoff function in gcp/metadata.go

#### What you expected to happen:

I expected it to not be stuck in an infinite loop. Infinite loop are bad.

#### How to reproduce it (as minimally and precisely as possible):

Install k3s on a gce VM. Launch on it a pod with a container that is using the credentialprovider library. Wait forever.

#### Anything else we need to know?:

After some extensive debugging, we found that the library realizes to be on a GCE virtual machine, since onGCEVM function returns true. This is because `cat /sys/class/dmi/id/product_name` returns `Google Compute Engine`:
```sh
$ kubectl exec -it kube-notary-f7598887f-5v6d6 -- cat /sys/class/dmi/id/product_name
Google Compute Engine
$
```

All fine so far. But then, the gcp plugin tries to fetch the metadata from `http://metadata.google.internal`, which is not resolved, since this line on file `/etc/hosts`
```
169.254.169.254 metadata.google.internal  # Added by Google
```
is **not** present in the kubernetes pod, but just on the host.

The workaround we found is to add this hostAlias to the pod configuration
```yaml
      hostAliases:
        - ip: "169.254.169.254"
          hostnames: ["metadata.google.internal"]
```
which is effective, but also ugly.

The ideal solution to this problem would be:
 - to detect if we are running on kubernetes inside gce, either testing the line metadata.google.internal on /etc/hosts or by other means and/or
 - avoid infinite loop in runWithBackoff function

#### Environment:
- Kubernetes version (use `kubectl version`):
 ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
Google Cloud Project
- OS (e.g: `cat /etc/os-release`):
 ```
NAME="AlmaLinux"
VERSION="8.4 (Electric Cheetah)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.4 (Electric Cheetah)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8.4:GA"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.4"
```
- Kernel (e.g. `uname -a`):
 ```
 Linux k3scnildemo 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Tue Aug 10 15:40:55 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
 ```
- Install tools:
k3sup
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by adisky** [comment]
cc @DangerOnTheRanger

**Comment by DangerOnTheRanger** [comment]
This looks like a case of #86245 to me, though this is with k3s, not OpenShift. Going off the comments on that issue, I think adding a timeout or retry limit to `runWithBackoff` might be risky/have unintended consequences. Changing the way `onGCEVM` works is also a potential solution, though I think similar logic applies there.

With the other issue, OpenShift was blocking the `metadata.google.internal` link - why did the `/etc/hosts` line not end up on the pod here? Someone more familiar with k3s than I am might be able to shed more light on that matter. If possible, allowing that link to go through would be my preferred solution, but if that's not possible/practical I think we could look at some other ways for `onGCEVM` to work.

**Comment by brandond** [comment]
> why did the /etc/hosts line not end up on the pod here?

Are you saying that any code using using go-containerregistry in a container is expected to mount the host's /etc/hosts into the container? That seems like an odd thing to expect users to know, especially since it's not documented anywhere.

**Comment by DangerOnTheRanger** [comment]
> > why did the /etc/hosts line not end up on the pod here?
> 
> Are you saying that any code using using go-containerregistry in a container is expected to mount the host's /etc/hosts into the container? That seems like an odd thing to expect users to know, especially since it's not documented anywhere.

Sorry, I think I misunderstood the issue - I thought the issue was during fetching a container image for k3s for some reason, as opposed to the issue in reality coming from trying to use `pkg/credentialprovider` from inside a container on a k3s-hosted pod. 

I think the problem here if I'm understanding it correctly now stems from using/depending on `pkg/credentialprovider` for Docker image-related things. That code makes some k8s-specific assumptions; things in pkg/ aren't expected/intended to be consumed outside of k8s itself, and so this issue falls outside the intended use case of `pkg/credentialprovider`, unfortunately.

The issue as described will happen if `pkg/credentialprovider` is used from within a container on GCE for any reason while not having access to `metadata.google.internal`, so you're completely right - go-containerregistry (which uses a mostly-unmodified fork of `pkg/credentialprovider`, I believe) will likely have this issue as well. I recommend opening an issue on go-containerregistry for that, since from a k8s perspective `pkg/credentialprovider` is providing the correct behavior.

**Comment by SimoneLazzaris** [comment]
Maybe I can explain what is our use case.

Our application is monitoring other pods, to monitor if untrusted containers are running on the k8s installation. In order to do that, it fetches container checksums from their original repository. So it uses package `go-containerregistry` to manage authentication. It retrieves auth informations from the pod metadata and use them to download container checksums, which are compared against a trust database.

The application is of course running as a container in a pod, so it has no direct access to the underlying node files.

**Comment by brandond** [comment]
Have you tried building your application with the build tags to disable the various credential providers? https://github.com/google/go-containerregistry/pull/630

**Comment by SimoneLazzaris** [comment]
@brandond disabling the credentials seems to also be a viable workaround/solution.
Our container is not stuck in init phase anymore.

**Comment by DangerOnTheRanger** [comment]
> Brad Davidson disabling the credential providers seems to also be a viable workaround/solution. Our container is not stuck in init phase anymore.

This sounds like the best approach to me - does doing so impact any other part of your workflow? I think there's a case to be made that we could close the issue now that we know this.
