### ISSUE TITLE
Add `runtime/pprof` support to binaries like the kubelet

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#104681]
#### What would you like to be added:

The idea is to support CPU and memory profile creation via `runtime/pprof` for binaries like the kubelet. This allows to collect profiles over the complete lifetime of a binary, for example when running them in test suites or for debugging purposes.

#### Why is this needed:

Right now, we only support the `debug/pprof/*` HTTP endpoints, which accept a duration (default `?seconds=30`, cannot be `-1` or unlimited). When running a test suite, then this is not very helpful because we can only guess when to stop the recording.

The enhancement would add two additional flags, where the example implementation from [`runtime/pprof`](https://pkg.go.dev/runtime/pprof) can be used as starting point.

```golang
var cpuprofile = flag.String("cpuprofile", "", "write cpu profile to `file`")
var memprofile = flag.String("memprofile", "", "write memory profile to `file`")

func main() {
    flag.Parse()
    if *cpuprofile != "" {
        f, err := os.Create(*cpuprofile)
        if err != nil {
            log.Fatal("could not create CPU profile: ", err)
        }
        defer f.Close() // error handling omitted for example
        if err := pprof.StartCPUProfile(f); err != nil {
            log.Fatal("could not start CPU profile: ", err)
        }
        defer pprof.StopCPUProfile()
    }

    // ... rest of the program ...

    if *memprofile != "" {
        f, err := os.Create(*memprofile)
        if err != nil {
            log.Fatal("could not create memory profile: ", err)
        }
        defer f.Close() // error handling omitted for example
        runtime.GC() // get up-to-date statistics
        if err := pprof.WriteHeapProfile(f); err != nil {
            log.Fatal("could not write memory profile: ", err)
        }
    }
}
```

As a follow-up, we can enhance e2e.test to evaluate the produced profiles. For example, we can run `go tool pprof -png cpu.prof` to produce an adequate build artifact.

Some references I found during my investigation:
- The existing profile gatherer got removed in https://github.com/kubernetes/kubernetes/pull/85304
- We have this grab-profiles script: https://github.com/kubernetes/kubernetes/blob/master/hack/grab-profiles.sh, which seems to rely on gcp and ssh

**Comment by aojea** [comment]
I have doubts if this feature can scale well, seems overkill to debug e2e tests, those are randomly executed and you'll end with min 3 kubelets full profiles, that you have to correlate gainst the timing on the tests

**Comment by BenTheElder** [comment]
I don't think sig-testing can unilaterally alter binaries like this on our own, this seems like maybe sig-architecture or each of the binaries's sigs.

IF they were ok adding these endpoints and paying the cost of profiling during testing, we could collect them in CI, but I'm not sure it's appropriate for e2e.test to collect them, and logistically it will be difficult to collect them portably in a central tool like this.
