### ISSUE TITLE
pod updates:how to change the fields of spec.containers[].resources.request.cpu(memory)

### ISSUE THREAD

**Issue by thyn** [kubernetes/kubernetes#104737]
Is it possible to change request only without pod restart? I know about #24913. But  requests  seems to me to be safe to change

Example of usage:
We have blue green deployment. When new pods are starting they need few resources. When they switched to production poods need more resources (request only). After deployment all old pods would be active for some time with lower requests. To be sure everything is ok.

**Comment by pacoxu** [comment]
/sig apps node
for traige
/kind feature

The current updateable fields:
https://github.com/kubernetes/kubernetes/blob/b0bc8adbc2178e15872f9ef040355c51c45d04bb/pkg/apis/core/validation/validation.go#L4057-L4061

And there is #102884 to fix this, the primary goal is `allow to change container resource requests & limits without necessarily restarting the container.` Would you check if kubernetes/enhancements#2273 can solve your problem?

**Comment by thyn** [comment]
Thank you. It's what I need. Is any information about next version which will contain that changes?

**Comment by thockin** [comment]
https://github.com/kubernetes/enhancements/issues/1287
