### ISSUE TITLE
rbd: unmap failed: (16) Device or resource busy

### ISSUE THREAD

**Issue by fcddk** [kubernetes/kubernetes#104785]
#### What happened
     kubelet log:
`nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/rbd/k8s-data:kubernetes-dynamic-pvc-b3e3f5a1-6a72-4c1b-b491-21879df40d07 podName: nodeName:}" failed. No retries permitted until 2021-09-06 06:24:03.085198835 +0800 CST m=+4045740.475184549 (durationBeforeRetry 2m2s). Error: "UnmountDevice failed for volume \"pvc-7597f603-8ccd-4c42-b54a-b8a79035d29c\" (UniqueName: \"kubernetes.io/rbd/k8s-data:kubernetes-dynamic-pvc-b3e3f5a1-6a72-4c1b-b491-21879df40d07\") on node \"slave12\" : rbd: failed to unmap device /dev/rbd12, error exit status 16, rbd output: rbd: sysfs write failed\nrbd: unmap failed: (16) Device or resource busy\n"`

### cadvisor volumeMounts
`        volumeMounts:
        - mountPath: /rootfs
          mountPropagation: HostToContainer
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: varrun
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /dev/disk
          name: dev
          readOnly: true`

#### Environment:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"archive", BuildDate:"2021-01-28T13:13:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"archive", BuildDate:"2021-01-28T13:13:05Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
VERSION_ID="18.04"

- Kernel (e.g. `uname -a`):

Linux mgt01 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Kartik494** [comment]
Hi @fcddk Could you explain  this issue in some details, that would be easier to understand
