### ISSUE TITLE
PV and PVC exists for POD but Scheduler still complains volume/node affinity

### ISSUE THREAD

**Issue by mohammaddawoodshaik** [kubernetes/kubernetes#104709]
#### What happened:
In a three-node cluster, we have Statefulset with replica-3. Each node in the cluster has a PV/PVC created in order to make sure one statefulset-pod to schedule on each node. 

Initially all things are working good. But as part of our testing, we have hard-rebooted all three boxes with a ~60sec gap. After the nodes comes back up, we saw that one pod in statefulset is stuck in pending state(more then 6hrs), with the below error.

**Events:
  Type     Reason            Age                 From               Message
  Warning  FailedScheduling  97s (x33 over 42m)  default-scheduler  0/3 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 2 node(s) had volume node affinity conflict.**

Workaround worked for us:
In order to recover from this, we have restarted the kube-scheduler(leader) container.

PV:
server-system-pv-0   198G       RWO            Retain           Bound    server-system/data-data-0   local-storage            2d2h

PVC:
data-data-0   Bound    server-system-pv-0   198G       RWO            local-storage   2d2h

POD Volumes:
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-data-0
    ReadOnly:   false

#### What you expected to happen:
After some time eventually, all service-pods should have come back to Running state.

#### How to reproduce it (as minimally and precisely as possible):
As this is not a consistent behaviour we are seeing. Only way to reproduce right now is, hard-reboot all the nodes in the cluster.

#### Environment:
- Kubernetes version (use `kubectl version`):
**Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-cisco", GitCommit:"9bd6278a0e70c390455f515d696d1b41cbef8e10", GitTreeState:"clean", BuildDate:"2021-03-16T10:17:33Z", GoVersion:"go1.14.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.15-cisco", GitCommit:"9bd6278a0e70c390455f515d696d1b41cbef8e10", GitTreeState:"clean", BuildDate:"2021-03-16T10:17:33Z", GoVersion:"go1.14.13", Compiler:"gc", Platform:"linux/amd64"}**
- Cloud provider or hardware configuration:
    VMs
- OS (e.g: `cat /etc/os-release`):
**NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic**
- Kernel (e.g. `uname -a`):
**Linux hstanme-generic #82~18.04.1 SMP Tue Apr 20 06:24:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux**
- Install tools:
kubeadm
- Network plugin and version (if this is a network-related bug):
**Caclico
root@maglev-master-10-20-172-41:~# calicoctl version
Client Version:    v3.12.0.cisco
Git commit:        dca8136d
Cluster Version:   v3.12.0.cisco
Cluster Type:      k8s,bgp**
- Others:

**Comment by neolit123** [comment]
> GitVersion:"v1.18.15-cisco",

versions < 1.20 are out of support in upstream k8s, so you might have to contact the support of your provider first.
please confirm, if you or them can reproduce this with version 1.20 or newer.

thanks

/sig storage
/triage needs-information

**Comment by harshanarayana** [comment]
@neolit123 This is a little customised version of kubernetes we build and manage internally in our own team. We have had a few changes done to the way `kubeadm` works + allow the link local range of IPs to be consumed for creating the cluster. 

We are working on getting a custom patched v1.21.2 to run the test to see if we can reproduce the same.
