### ISSUE TITLE
close pod's FQDN

### ISSUE THREAD

**Issue by Royal0302** [kubernetes/kubernetes#104724]
how can i closed pod's FQDN when i was created pod  by statefulset

**Comment by pacoxu** [comment]
Please try https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md for questions and support.

/kind support
/sig network

You may refer to https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#hostname-and-name-resolution and https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields.

> **setHostnameAsFQDN (boolean)**
> 
> If true the pod's hostname will be configured as the pod's FQDN, rather than the leaf name (the default). In Linux containers, this means setting the FQDN in the hostname field of the kernel (the nodename field of struct utsname). In Windows containers, this means setting the registry value of hostname for the registry key HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters to FQDN. If a pod does not have FQDN, this has no effect. Default to false.
> 
> **subdomain (string)**
> 
> If specified, the fully qualified Pod hostname will be "<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>". If not specified, the pod will not have a domainname at all.

**Comment by thockin** [comment]
What does it mean to close the FQDN?

**Comment by thockin** [comment]
I'm going to close this - if you feel there's more information to provide, please reopen
