### ISSUE TITLE
Servcie cluster ip leaks

### ISSUE THREAD

**Issue by yuchengwu** [kubernetes/kubernetes#104769]
#### What happened:
Service cluster ip leaks(no more than 9 minutes) if the service under deleting(e.g. lb svc waiting on cloud provider controller to finish a clean up job) when the ip repair worker works.

#### What you expected to happen:
Servcie cluster ip should be released once service has been deleted.

#### How to reproduce it (as minimally and precisely as possible):
```shell
# cat svc.yml
apiVersion: v1
kind: Service
metadata:
  finalizers:
  - f/f
  name: test1
spec:
  clusterIP: 192.168.4.133
  ports:
  - port: 4389
  type: ClusterIP
# cat svc2.yml
apiVersion: v1
kind: Service
metadata:
  name: test2
spec:
  clusterIP: 192.168.4.133
  ports:
  - port: 2389
  type: ClusterIP
```
step 1: kubectl create -f svc.yml
step 2: kubectl delete -f svc.yml 
step 3: sleep 3m(ip repair worker loop interval is 3m) to wait ip repair worker to realloced
step 4: remove svc test1's finalizer
step 5: kubectl get svc -A | grep 192.168.4.133 # ensure 192.168.4.133 not assigned to any existing service
step 6: kubectl create -f svc2.yml # we got
The Service "test2" is invalid: spec.clusterIP: Invalid value: "192.168.4.133": provided IP is already allocated

#### Anything else we need to know?:
I encountered this when I try to migrate services from one namespace to another while preserve IP unchanged during our product upgrading. If we are lucky, the period between [service delete action](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/storage/rest.go#L297) and its fully disappeared from cluster is not intervened by [ip repair woker](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/ipallocator/controller/repair.go) then we won't stuck on the previous step 6, otherwise we have to wait another 6 - 9 minutes(repair work pretend it is still in use until count expires, current count value `numRepairsBeforeLeakCleanup` is 3) to let the ip repair worker clean it up.

Note that nodePort GC logic looks like the same, so it may have same issue.

#### Environment:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.18", GitCommit:"3b72d58d4b44c0e2545b6c7d6ee73a11e5b6980a", GitTreeState:"clean", BuildDate:"2021-06-09T13:10:46Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-49+3b72d58d4b44c0", GitCommit:"3b72d58d4b44c0e2545b6c7d6ee73a11e5b6980a", GitTreeState:"clean", BuildDate:"2021-06-09T13:10:18Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
#87603 is a similar one.  Some logic details in https://github.com/kubernetes/kubernetes/issues/87603#issuecomment-579443444.

**Comment by thockin** [comment]
Dup of 87603 - fix is pending, but is not easily separable from the rest of the PR, so not likely to backport.  Closign as dup.
