### ISSUE TITLE
Rename volume_fsgroup_recursive_apply labe for volume operations to volume_fsgroup_apply

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#104717]
This came from discussions in - https://github.com/kubernetes/enhancements/pull/2914

And we should consider renaming the label to something more meaningful and a current proposed alternative is `volume_fsgroup_apply`.

/sig storage

**Comment by Kartik494** [comment]
Hi , is there anyone working on it? if not i would like to work on this.

**Comment by gnufied** [comment]
The metrics was renamed in - https://github.com/kubernetes/kubernetes/pull/105885/files .

/close
