### ISSUE TITLE
[E2E] Add a --scale= option OR introspect nodes on startup for scale/load/soak tests.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#10479]
**problem** 

Right now we embed soak testing semantics into some of the E2E's  on a case-by-case ad hoc basis.   This makes each test require a certain amount of interpretation to run.   

**examples**
- networking.go which has a pending service layer of parallelism.
- load.go which aims to add n pods per node (similar to density)
- density.go which has parallel job submissions and lots of manual "disable/enable" switching, also does the "n pods per node" stuff.
- explicit soak tests like k8petstore which also have scalability heuristics.

**solution 1: yet another parameter** 

maybe we should provide a `--scale` option to the E2E tests which dictates the level of capacity a cluster expects to have ?  
- It could be a true/false switch.  If its **on** then a test will run at "cluster scale" i.e. it will test things assuming that each node is production quality, and capable of running 100s of containers and so on.  
- If its off, then the e2e tests will run at "normal" scale, just testing basic functionality.  

**solution 2 : make educated guesses, no user interaction needed**

Another possibly less fragile approach is that we can introsepct the cluster on startup.  Bascially, we can (1) have a task which, on each node of the cluster, attempts to launch N containers or something OR
(2) simply read the metadata about free `cat /proc/cpuinfo` and `cat /proc/meminfo`, and make reasonable guesses at startup time based on this information.

The advantage here is that, for i guess 90% of the cases, we can have generalized concept of what a cluster can/should be able to support.   

I'm not married to these ideas, but just wanted to start the conversation.  

Any other/different/better ideas on *how to define scale semantics to E2E testing expectations in a less ad-hoc fashion* ?

**Comment by jayunit100** [comment]
cc @timothysc @rrati @satnam6502 @quinton-hoole @dchen1107 @eparis

**Comment by a-robinson** [comment]
cc @ixdy

**Comment by jayunit100** [comment]
This is subsumed by the implementation of a global config
