### ISSUE TITLE
Unauthorized kube-proxy causing stack traces on the API server

### ISSUE THREAD

**Issue by kelseyhightower** [kubernetes/kubernetes#10470]
I'm still digging into why I can get the proxy service to auth with the API using TLS certs, but stack traces on the API server side are unexpected here.
### Environment

```
$ kubectl version
Client Version: version.Info{Major:"0", Minor:"20", GitVersion:"v0.20.0", GitCommit:"c17a15a0cbcac20230c6d63a584958422c5fd9ec", GitTreeState:"clean"}
Server Version: version.Info{Major:"0", Minor:"20", GitVersion:"v0.20.0", GitCommit:"c17a15a0cbcac20230c6d63a584958422c5fd9ec", GitTreeState:"clean"}
```

```
$ kubectl get cs
NAME                 STATUS    MESSAGE              ERROR
controller-manager   Healthy   ok                   nil
scheduler            Healthy   ok                   nil
etcd-0               Healthy   {"health": "true"}   nil
```

```
$ docker info
Containers: 11
Images: 50
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.5
Operating System: CoreOS 723.0.0
CPUs: 1
Total Memory: 3.619 GiB
Name: node1.c.kubestack.internal
ID: EMLC:7H7M:2EYM:NY6K:MBXC:56KU:DJ7T:AJL5:D5AQ:DQ52:XXNJ:CBPY
Username: kelseyhightower
Registry: https://index.docker.io/v1/
```
### Logs

From the Kube proxy logs:

```
E0629 00:40:15.930163       1 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
E0629 00:41:07.215017       1 api.go:108] Unable to load services: the server has asked for the client to provide credentials (get services)
E0629 00:41:35.783223       1 api.go:180] Unable to load endpoints: the server has asked for the client to provide credentials (get endpoints)
```

From the API server logs:

```
goroutine 327 [running]:
github.com/GoogleCloudPlatform/kubernetes/pkg/httplog.(*respLogger).WriteHeader(0xc2095f92c0, 0x191)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/httplog/log.go:188 +0x9a
net/http.Error(0x7fcb95ba62c8, 0xc2095f92c0, 0x13ad950, 0xc, 0x191)
    /usr/src/go/src/net/http/server.go:1274 +0x9a
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.unauthorized(0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers/handlers.go:67 +0x4e
net/http.HandlerFunc.ServeHTTP(0x16fdfb8, 0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers.func·001(0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/auth/handlers/handlers.go:39 +0x2f7
net/http.HandlerFunc.ServeHTTP(0xc208607bc0, 0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·013(0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc2085e71c0, 0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/api.func·013(0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/api/requestcontext.go:101 +0xe1
net/http.HandlerFunc.ServeHTTP(0xc208917820, 0x7fcb95ba62c8, 0xc2095f92c0, 0xc208b7a680)
    /usr/src/go/src/net/http/server.go:1265 +0x41
github.com/GoogleCloudPlatform/kubernetes/pkg/apiser [[kube-proxy/v0.20.0 (linux/amd64) kubernetes/c17a15a] 10.240.138.142:40890]
```

**Comment by kelseyhightower** [comment]
Finally got the proxy to authenticate by using a valid kubeconfig. So the action item here is to clean up the error handling around auth.

**Comment by mikedanese** [comment]
We like stack traces: 

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/httplog/log.go#L75-L78

**Comment by smarterclayton** [comment]
We muted many of these.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (179/150 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:60243 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGU8r-000QrO-98
	for dev@imwiz.com; Thu, 01 Jun 2017 11:44:13 -0600
Date: Thu, 01 Jun 2017 10:44:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496339042;
	bh=SJ7YqT7eoFhel5x7YFq/xy99nLNZyh1y//ZKIPL+DK0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=YuIT+5AJ3M9d3Bl279udsJcTCoWuQ2DOyHJ5jp6031gWClpaYoyaWodspXgr/4PB6
	 Tjt2/nL+y7uzn8HhbzuHQ03KVAk16vfhEvzTC0+7A6Uv//kgYEKZrb+MOK/b9mS/1S
	 G+Ek7O94f9DjVrW4Z5YqcJBH4NZ0mszXf3BqP+Wc=

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (180/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:56995 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1dGU8t-000QnN-2w
	for dev@imwiz.com; Thu, 01 Jun 2017 11:44:15 -0600
Date: Thu, 01 Jun 2017 10:44:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1496339040;
	bh=BkmaAu/dCXUlqYh2Knp0r1LyIeV0kOBavTWU3HU25WM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1xSM3KcIx7Cfw+GmELcfOjnia/6K02XplL1H0j050pGS2xplNBpF9igtiPJpJ7PJv
	 yV9awPbUVEoEy6jRo7izBbmtP6gnR+N4bbcHjNPVc6jBEBsUwbfcj9MnJtRwLOEzVF
	 lJQV4eeOUpeQlTdhM4wGkeOyUrSO7NrSeklvYI8c=
