### ISSUE TITLE
issue while installing Kubernetes cluster:

### ISSUE THREAD

**Issue by anoopnm182** [kubernetes/kubernetes#104710]
<img width="350" alt="1" src="https://user-images.githubusercontent.com/89909933/131661632-4660f2fc-7d34-42a2-a144-a3ec03f46c27.PNG">
<img width="525" alt="2" src="https://user-images.githubusercontent.com/89909933/131661638-7c9bc799-6f66-4d53-bfc5-8aeeab3f301e.PNG">
<img width="550" alt="3" src="https://user-images.githubusercontent.com/89909933/131661641-d4bd7402-0132-401b-987f-07fd86f5e2f4.PNG">

But in the step: apt-get install -y kubelet kubeadm kubectl 

error appears:
apt-get install -y kubelet kubeadm kubectl
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package kubelet
E: Unable to locate package kubeadm
E: Unable to locate package kubectl

attached the screenshots.

**Comment by neolit123** [comment]
try the updated steps here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl


/remove-sig architecture
/sig release

**Comment by neolit123** [comment]
closing. if this still doesn't work for you please re-open the issue and provide more details where does it fail in:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

/close

**Comment by anoopnm182** [comment]
i tried run "kubeadm init", but stuck below error. Swap is off. would you please help me.

root@Kube-Master:~# kubeadm init --pod-network-cidr=192.168.0.0/16 --ignore-preflight-errors=
[init] Using Kubernetes version: v1.22.1
[preflight] Running pre-flight checks......
...................................................

[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.

Unfortunately, an error has occurred:
timed out waiting for the condition
This error is likely caused by:
- The kubelet is not running
- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

    If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:  
'systemctl status kubelet'
- 'journalctl -xeu kubelet'
Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all Kubernetes containers running in docker:
'docker ps -a | grep kube | grep -v pause'
Once you have found the failing container, you can inspect its logs with:
- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

root@Kube-Master:# sudo systemctl restart kubelet.service
root@Kube-Master:# sudo systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-09-06 08:17:22 UTC; 9s ago
     Docs: https://kubernetes.io/docs/home/
  Process: 11268 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FA
 Main PID: 11268 (code=exited, status=1/FAILURE)
...skipping...
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-09-06 08:17:22 UTC; 9s ago
     Docs: https://kubernetes.io/docs/home/
  Process: 11268 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FA
 Main PID: 11268 (code=exited, status=1/FAILURE)
