### ISSUE TITLE
helm uninstall chart , but ReplicaSet and Pod is exists on k8s  

### ISSUE THREAD

**Issue by fangsean** [kubernetes/kubernetes#104745]
#### What happened:

    (1) helm uninstall chart at namespace
    (2) not found deployment and service
    (3) but ReplicaSet is exists，on time pod is exists.

#### What you expected to happen:
     (1) ReplicaSet and pod is not exists.
#### How to reproduce it (as minimally and precisely as possible):
     (1) Restart k8s, But unable to reproduce the problem 
#### Environment:
- Kubernetes version (use `kubectl version`): 
         
         Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
        
        NAME="CentOS Linux"
        VERSION="7 (Core)"
        ID="centos"
        ID_LIKE="rhel fedora"
        VERSION_ID="7"
        PRETTY_NAME="CentOS Linux 7 (Core)"
        ANSI_COLOR="0;31"
        CPE_NAME="cpe:/o:centos:centos:7"
        HOME_URL="https://www.centos.org/"
        BUG_REPORT_URL="https://bugs.centos.org/"
        CENTOS_MANTISBT_PROJECT="CentOS-7"
        CENTOS_MANTISBT_PROJECT_VERSION="7"
        REDHAT_SUPPORT_PRODUCT="centos"
        REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
          
        Linux paas-test-region1-slave4 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
As you cannot reproduce it consistently, it's hard to figure out what happened.

You should check the `ownerReferences` of your orphaned replicaset next time. 
https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/
```
- apiVersion: apps/v1
  kind: ReplicaSet
  metadata:
    annotations:
      deployment.kubernetes.io/desired-replicas: "1"
      deployment.kubernetes.io/max-replicas: "2"
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2021-09-02T08:22:47Z"
    generation: 1
    labels:
      k8s-app: tigera-operator
      name: tigera-operator
      pod-template-hash: 6fbb48778f
    name: tigera-operator-6fbb48778f
    namespace: tigera-operator
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: Deployment
      name: tigera-operator
      uid: 94851f01-a2b2-4028-88b8-ebca254db438
    resourceVersion: "614"
    uid: 3db9e5bf-841c-4b2c-adf2-7334ac2d9760
  spec:
    replicas: 1
    selector:
```


If you delete something with  `--cascade='orphan'`, the pod/rs may still exists.
```
kubectl delete --help
      --cascade='background': Must be "background", "orphan", or "foreground". Selects the deletion cascading strategy
for the dependents (e.g. Pods created by a ReplicationController). Defaults to background.

[root@daocloud ~]# kubectl create -f deploy.yaml
deployment.apps/web created
[root@daocloud ~]# kubectl get pod
NAME                   READY   STATUS    RESTARTS   AGE
web-5cc8694fc7-5kpmd   0/1     Pending   0          3s
[root@daocloud ~]# kubectl ge^Cpod
[root@daocloud ~]# kubectl delete -f deploy.yaml --cascade='orphan'
deployment.apps "web" deleted
[root@daocloud ~]# kubectl get pod
NAME                   READY   STATUS    RESTARTS   AGE
web-5cc8694fc7-5kpmd   0/1     Pending   0          22s
[root@daocloud ~]# kubectl get rs
NAME             DESIRED   CURRENT   READY   AGE
web-5cc8694fc7   1         1         0       25s
[root@daocloud ~]#
```

Some docs that you may refer to 
https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-foreground-cascading-deletion

**Comment by thockin** [comment]
This sounds like a helm bug more than a k8s bug

**Comment by kow3ns** [comment]
agree. This sounds like a HELM UX issue. Please file against that project.
