### ISSUE TITLE
Update-demo-nautilus: This webpage is not available

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#10472]
I'm following this document kubernetes/release-0.19.0/examples/update-demo/ to get an application running.

I have followed the step 1, step 2, step 3 and step 4. I haven't worked on the step 0. Is that the reason why I'm unable to see the pods running on the web?

This is the site I got to, to access the pods:
http://localhost:8001/static/index.html

which gives me 'This webpage is not available'.

**Comment by roberthbailey** [comment]
Step 0 is to launch a kubernetes cluster. Do you have a cluster running? In step 1 you launched kubectl in proxy mode, which should connect to the apiserver in your cluster and proxy requests to localhost:8001 to the apiserver. Did you see any errors when running `./kubectl proxy --www=examples/update-demo/local/`?

**Comment by adyanthaya17** [comment]
Yes, I have a kubernetes cluster running. 
Step 0: $ ./cluster/kube-up.sh

The above step I haven't worked on my machine. 

When I run the command : 
$ kubectl proxy --www=examples/update-demo/local/ &

It prompts me: Starting to serve on localhost:8001

**Comment by roberthbailey** [comment]
Does `kubectl get pods` return successfully?

**Comment by adyanthaya17** [comment]
Yes it does.
$ kubectl get nodes
$kubectl get pods
$ kubectl get services

All these return successfully.

**Comment by roberthbailey** [comment]
Are you running the kubectl proxy command from a directory that contains the `examples/update-demo/local/` directory as a relative path? If, from that same directory, you run `ls examples/update-demo/local/` does it show `index.html` as one of the files?

**Comment by adyanthaya17** [comment]
$  ls examples/update-demo/local/
angular.min.js  angular.min.js.map  index.html  LICENSE.angular  script.js  style.css

**Comment by roberthbailey** [comment]
Hmmm. @ihmccreery worked through this demo last week and made some [minor fixes](https://github.com/GoogleCloudPlatform/kubernetes/pull/10230) but I don't think before those fixes there was a webpage not found error hitting the localhost url.

**Comment by adyanthaya17** [comment]
I did edit the files previously as mentioned in #10230 but I'm still facing the same issue.

**Comment by roberthbailey** [comment]
The other thing I can think of to check is to make sure that kubectl proxy is actually binding to the port on your machine. After running kubectl proxy, can you run `netstat -an | grep 8001` and verify that it prints out a line (my mac shows `tcp46      0      0  *.8001                 *.*                    LISTEN`).

**Comment by adyanthaya17** [comment]
tcp6       0      0 :::8001                 :::*                    LISTEN

This is what is getting printed

**Comment by roberthbailey** [comment]
I'm now at a loss as to what isn't working.

**Comment by adyanthaya17** [comment]
Could you tell me as to what the below command does?

$ ./cluster/kube-up.sh

**Comment by roberthbailey** [comment]
From your netstat output it looks like kubectl may only be binding to an ipv6 interface on your machine (whereas on my machine it's binding to both ipv4 and ipv6). Can you try pointing your browser at http://[::1]:8001/static/ and see if that connects?

**Comment by roberthbailey** [comment]
(by the way, that works for me in chrome but not safari, so your milage may vary depending on your browser)

**Comment by adyanthaya17** [comment]
I tried it on chrome but I still am unable to see the web page :(

**Comment by adyanthaya17** [comment]
I have manually installed kubectl in the master node by:

$ wget https://storage.googleapis.com/kubernetes-release/release/v0.17.0/bin/linux/amd64/kubectl
$ chmod +x kubectl
$ mv kubectl /usr/local/bin/

and have executed the commands 
$ kubectl proxy --www=examples/update-demo/local/ &
$ kubectl create -f examples/update-demo/nautilus-rc.yaml

in the directory:
$ kubernetes/release-0.19.0/

**Comment by roberthbailey** [comment]
You are running kubectl proxy on the master node? That would explain why you can't connect. 

The instructions are for running kubectl on your local machine; if you are running the command on the master then nothing will be listening on localhost for your web browser's connection. 

Please try running kubectl proxy locally on your machine and see if that helps.

**Comment by adyanthaya17** [comment]
When you say 'local machine' does it mean the minion node? I have my kube-proxy service running on minion node.

**Comment by roberthbailey** [comment]
The local machine is the machine that you are running the web browser on. You should run kubectl proxy on the same machine as your web browser.

**Comment by suyogbarve** [comment]
I am actually able to run kubectl proxy on a different machine (browser : 10.101.109.73) and able to access it from another machine (kube_master: 10.101.100.8)
However I am facing a different issue, my kubernetes master node is unable to talk to any of the pods.
If I hit >>
curl http://kube_master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-z7x57/data.json
Error: 'dial tcp 172.17.0.4:80: no route to host'

I running 2 kubernetes node (node1: 10.101.109.84) and (node2: 10.101.109.69)
and update-demo-nautilus-z7x57 is the name of the pod which is created on node2

**Comment by ihmccreery** [comment]
Hi @suyogbarve.  Would you mind [opening a separate issue](https://github.com/GoogleCloudPlatform/kubernetes/issues/new)?  It sounds like the issue you're facing is a different one, and it will be hard to address two different issues on the same thread.

**Comment by suyogbarve** [comment]
Sure @ihmccreery I opened a new issue https://github.com/GoogleCloudPlatform/kubernetes/issues/11058

**Comment by roberthbailey** [comment]
Can this issue be closed then?

**Comment by ihmccreery** [comment]
@adyanthaya17, has running the kubectl proxy on your local machine helped?

**Comment by adyanthaya17** [comment]
My kubectl proxy is running on the minion nodes but it still isn't working.

**Comment by adyanthaya17** [comment]
I ran the below command and the output is sa seen
 
$ curl http://master:8080/api/v1/proxy/namespaces/default/pods/update-demo-nautilus-6lyv4/data.json
{
  "image": "nautilus.jpg"
}

**Comment by roberthbailey** [comment]
@adyanthaya17 that output looks correct. Are you still having trouble connecting to the kubectl proxy? If you are running the proxy on a GCE instance, one option would be to poke a hole in your GCE firewall for the proxy port (by default 8001) on that instance and then point your web browser at `http://<external-ip>:8001/static` to see the demo UI.

**Comment by roberthbailey** [comment]
I'm going to close this in favor of continuing the discussion on your more recent issue (https://github.com/kubernetes/kubernetes/issues/12465).
