### ISSUE TITLE
Random "interrupted system call" issues

### ISSUE THREAD

**Issue by tavolodobela** [kubernetes/kubernetes#104815]
We have the following environment:

kubernetes 1.22.0
containerd: 1.5.2-0ubuntu1~20.04.2
calico: v3.19.1
OS: ubuntu 20.04

The problem is that when pods are running, we experience random "interrupted system call" issues. What could be the problem? What additional data is needed to figure out what's wrong?

One example is when the app in the pod tried to create a 16 MB shared memory, and during the process we got this interrupted system call error.

**Comment by neolit123** [comment]
hi, can you show relevant logs from the kubelet and containerd.

/triage needs-information
/sig node

**Comment by tavolodobela** [comment]
hello, @neolit123 please find them linked. I've searched for both the container name and the container id in syslog. Let me know if you need more data.

https://pastebin.com/ycxDhRxw
https://pastebin.com/FrQcA806


Note that when the 'accident' happens (20:50:38) there's nothing in the logs for that time. The only thing I found is that the gpu operator provided these entries (we use nvidia gpu's inside the pods):


/var/log/containers/gpu-operator-node-feature-discovery-worker-bthsh_default_worker-c170341bc32e6ce6b7ee636869a3aff15679eeadcbf5e6e52c871dfc7f12efa6.log:

`
2021-09-03T22:50:38.419511449+02:00 stderr F I0903 20:50:38.419299       1 nfd-worker.go:468] starting feature discovery...
`

`
2021-09-03T22:50:38.440049033+02:00 stderr F W0903 20:50:38.439885       1 kernel.go:99] failed to detect the status of selinux, please check if the system supports selinux and make sure /sys on the host is mounted into the container: open /host-sys/fs/selinux/enforce: no such file or directory
`

`
2021-09-03T22:50:38.503029951+02:00 stderr F I0903 20:50:38.502751       1 nfd-worker.go:480] feature discovery completed
`

`
2021-09-03T22:50:38.50306926+02:00 stderr F I0903 20:50:38.502793       1 nfd-worker.go:550] sending labeling request to nfd-master
`

**Comment by neolit123** [comment]
Thanks for the additional info.
Hoping that the issue triage folks will find these useful.

/remove-triage needs-information
/kind bug
Until confirmed otherwise.

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include logs from the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Once more details are provided, the bug will be accepted.

/triage needs-information
/cc @fromanirh

**Comment by ehashman** [comment]
(note: none of the attached logs say anything about an interrupted system call)

**Comment by tavolodobela** [comment]
Unfortunately I don't have any more logs other than the linked kubelet and containerd logs from pastebin. What else could I give you?

**Comment by SergeyKanzhelev** [comment]
/close

if you can get kubelet logs when the issue repro, it probably be enough if this is a k8s problem. Please re-open if you have more information
