### ISSUE TITLE
local-up-cluster.sh: core-dns fails with "loop detected"

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#104862]
#### What happened:

https://github.com/kubernetes/kubernetes/pull/100706 changed from "kube-dns" to "core-dns". "core-dns" is failing for me on Debian Buster:
```
$ kubectl logs -n kube-system coredns-755cd654d4-v56h2
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.0
linux/amd64, go1.15.3, 054c9ae
[FATAL] plugin/loop: Loop (127.0.0.1:45909 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8324999591064329788.1141440117556384278."
```

`local-up-cluster.sh` works when I use `DNS_ADDON=kube-dns`.

#### What you expected to happen:

"core-dns" should work.

#### Anything else we need to know?:

Perhaps related to this? https://github.com/coredns/coredns/issues/2087

#### Environment:
- Kubernetes version (use `kubectl version`): current master (e99b945b17823137a49176cb3561a756e9fd9a70)
- OS (e.g: `cat /etc/os-release`): Debian Buster
- Kernel (e.g. `uname -a`): 5.5.0-0.bpo.2-amd64

/cc @dims

**Comment by chrisohaver** [comment]
https://coredns.io/plugins/loop#troubleshooting provides a description of the error, causes, and workarounds.  Typically this is due to a local dns resolver installed on the host. Solution is to configure kubelet to use a different `resolv.conf` (more detail in link).

**Comment by pohly** [comment]
That mirrors what I found through the issue. Needs to be fixed in `local-up-cluster.sh` then.

**Comment by aojea** [comment]
I think we have to parameterize this
https://github.com/kubernetes/kubernetes/blob/a73f45dd96d01bbb2e8b2071a3aafdcdaeed0582/cluster/addons/dns/coredns/coredns.yaml.in#L76

**Comment by chrisohaver** [comment]
> I think we have to parameterize this
> 
> https://github.com/kubernetes/kubernetes/blob/a73f45dd96d01bbb2e8b2071a3aafdcdaeed0582/cluster/addons/dns/coredns/coredns.yaml.in#L76

I think the safer way is to configure kublet to send the correct resolv.conf to all “default” dns policy pods, not just fix in coredns.

**Comment by aojea** [comment]
Doh, right :)
