### ISSUE TITLE
ci-kubernetes-e2e-gce-scale-performance flakes with slow POST/PATCH jobs requests

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#104811]
#### Which jobs are flaking:
Two flakes recently:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1434924831014391808
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1432025635122843648

They fail with error like:
```
:0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:jobs Subresource: Verb:POST Scope:resource Latency:perc50: 26.798561ms, perc90: 48.23741ms, perc99: 1.063749999s Count:149 SlowCount:2}; expected perc99 <= 1s]]
:0
```

or

```
:0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:jobs Subresource: Verb:PATCH Scope:resource Latency:perc50: 29.365079ms, perc90: 130ms, perc99: 1.064999999s Count:148 SlowCount:2}; expected perc99 <= 1s]]
:0
```

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

/assign

**Comment by mborsz** [comment]
In https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1434924831014391808 logs I have found the following slow calls:

```
I0906 19:05:57.328637      12 httplog.go:105] "HTTP" verb="PATCH" URI="/apis/batch/v1/namespaces/test-3cnpmr-40/jobs/small-job-0" latency="1.034064788s" userAgent="clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="7ab0bccb-46b4-426c-8fea-ba5a6d63b18c" srcIP="34.134.33.17:39658" apf_pl="exempt" apf_fs="exempt" apf_d="" fl_priorityandfairness="975.523326ms" resp=200
I0906 19:05:57.351657      12 httplog.go:105] "HTTP" verb="PATCH" URI="/apis/batch/v1/namespaces/test-3cnpmr-6/jobs/medium-job-0" latency="1.030253352s" userAgent="clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="730817fb-a10c-4e61-92d6-5d85ffd99e6d" srcIP="34.134.33.17:39660" apf_pl="exempt" apf_fs="exempt" apf_d="" fl_priorityandfairness="1.020300711s" resp=200

```
* It's a bug that we use exempt priority level for clusterloader: I created https://github.com/kubernetes/kubernetes/issues/104809
* It's quite worrisome that APF handler takes 1s for exempt request.

**Comment by mborsz** [comment]
I checked a APF code and I think the flow for exempt requests is:
* genericfilters.WithPriorityAndFairness()
   * workEstimate := workEstimator.EstimateWork(r)
   *  fcIfc.Handle()
       * cfgCtlr.startRequest()
          * cfgCtlr.lock.Lock()
          * looks for matching flowschemas in cfgCtrl.flowSchemas
          * returns for exempt
       * req.Finish
          * updates metrics
          * calls execFn
             * updates headers
             * handler.ServeHTTP which stops the timer for priorityandfairness

For me, the most likely reason for slowness is lock contention on cfgCCtrl.lock. We know that the test is super cpu-intensive in that part and other requests are e.g. calculating sha256 keeping that lock.

A potential improvement would be to change this lock to RWLock or return the lock before starting calculating sha256 (if we believe that this is the most expensive operation there).

/cc @MikeSpreitzer @lavalamp @wojtek-t @tkashem

**Comment by wojtek-t** [comment]
I think the lock-contention is even worse than what you wrote, as e.g.:
https://github.com/kubernetes/kubernetes/blob/ef754331c453d3b5fdc31edf62da3d90771d5acd/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/apf_controller.go#L823
is happening under this lock (which is also dispatching requests).

I will take a deeper look later this week, but I think that switching to RWLock might do the job without any invasive changes.

**Comment by MikeSpreitzer** [comment]
`plState.queues.StartRequest` may trigger the execution of some requests that were waiting, but they are not executed in the same goroutine.

Yes, I think changing that Mutex to a RWMutex would be an easy way to greatly reduce contention.

**Comment by lavalamp** [comment]
I agree switching to RWMutex is likely to help a lot, if that's not enough I think with a little work we could e.g. switch to `atomic.Value`s.

**Comment by MikeSpreitzer** [comment]
/triage accepted
/priority important-soon
I will work on the fix.

**Comment by mborsz** [comment]
Wow! Thanks a lot for rapid help here! Let's wait for the next test run to see if it helped.
/reopen

**Comment by MikeSpreitzer** [comment]
Yes, can you please report the filter latency regardless of whether it is bad or good?  I would like to know _how much_ of a difference that PR made.

**Comment by mborsz** [comment]
Sure, will report the latency change in both cases.

**Comment by mborsz** [comment]
I compared 
* (the one where we saw issue) https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1434924831014391808
* (first with the lock improvements) https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1435649583614005248

I tried to find requests that:
* use exempt PL (so shouldn't be throttled)
* has fl_priorityandfairness, key which means that priority and fairness filter took more than 100ms

Sample matching request:
```
I0906 20:43:56.160509      12 httplog.go:105] "HTTP" verb="DELETE" URI="/api/v1/namespaces/test-3cnpmr-16/services/small-service-12" latency="466.642329ms" userAgent="clusterloader/v0.0.0 (linux/amd64) kubernetes/$Format" audit-ID="83b8fcd2-988e-4353-8645-e61d049091b4" srcIP="34.134.33.17:39630" apf_pl="exempt" apf_fs="exempt" apf_d="" fl_priorityandfairness="140.356839ms" resp=200
```

In the old run, I see ~6k such requests, with the locking improvements there are no such requests.
```
$ grep -c -e 'exempt.*fl_priorityandfairness' 1434924831014391808/kube-apiserver.log
5830
$ grep -c -e 'exempt.*fl_priorityandfairness' 1435649583614005248/kube-apiserver.log
0
```

The latency of PATCH jobs seems to improve significantly:
![image](https://user-images.githubusercontent.com/2559168/132639234-3afb76f5-e09f-4a5d-9f65-9f9fbfa6d8f9.png)

So overall it looks great. The only worrisome metric I see is that actual P&F throttling for other requests has grown:

With locking improvements:
![image](https://user-images.githubusercontent.com/2559168/132639639-ff710cbe-5217-4dda-8274-97045ee1d7e4.png)

Old: 
![image](https://user-images.githubusercontent.com/2559168/132639650-27daccfc-0a9d-4094-9d75-8c20b6b342fa.png)

E.g. 'node-high' has now throttling latency of ~1.5s in spikes where in the previous test run it was more like ~800ms.

I don't think the lock improvements touched this directly.
I expect that this is either:
* per-test variance (if we rerun the old run again we would see different throttling latencies as well)
* we throttle exempt requests less (as expected) giving less resources to other requests.

Anyway, I don't think this change is meaningful as per-test latency aggregates for PATCH nodes/status and PUT leases (the most common requests in node-high) look ~same as previously:
![image](https://user-images.githubusercontent.com/2559168/132640335-d22b97b9-2bf4-4fc1-be0e-dd69773388eb.png)
![image](https://user-images.githubusercontent.com/2559168/132640417-f954fa05-72ac-4752-bf1e-5187701edb1b.png)

I think we can close this for now as the issue seems to be resolved.

Thanks a lot @MikeSpreitzer for your help here!
/close

**Comment by MikeSpreitzer** [comment]
@mborsz : thanks for reporting!
