### ISSUE TITLE
Mixed content  issue , http content loaded over https 

### ISSUE THREAD

**Issue by manjeetsinghcodz** [kubernetes/kubernetes#104834]
Hello all, 

I'm have a website running on k8s below is architecture with issue of mixed content  http loaded on https :

```
kubernetes version : 1.21 
traefik : v2.5
Nginx : v1.17
```

`Client -----> Cloudflare SSL -----> Traefik SSL (letsencrypt) ---> Nginx Pods (No SSL) `

it will be impossible to install SSL certs on the Nginx pods and convert the http url to https . 

I heard about the **x-forwarded-proto** header. 

i configured my httpsingressroute as below : 

`apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: https
  namespace: mg
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`www.xxx.com`)
    services:
    - name: web
      port: 80
    middlewares:
    - name: x-forwarded-proto
      namespace: mg
    - name: basic-auth
      namespace: mg
  tls:
    secretName: www.xxx.com-cert` 

My middleware : 

`apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: x-forwarded-proto
  namespace: mg
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"`

I turned off the cloudflare proxy SSL but still the same issue. Any help will be really appreciated

**Comment by uablrek** [comment]
Um, what is the problem exactly? Must the backends (nginx) know the original protocol? Or does traffic not work at all?

Anyway, this does not seem like a bug in K8s.

/kind support
/remove-kind bug

**Comment by manjeetsinghcodz** [comment]
@uablrek when i load my website in wordpress , it is displaying a lot of mixed contents issues thus break the site. The thing is the nginx pods are in http listening on port 80 and the website has urls hardcoded in http. SSL decryption is at Traefik ingress. 

Solution would be maybe  If i convert the hardcoded urls http to https, i'll have to install SSL certs at pod level nginx. 

How can i solve the issue of mixed content without converting the hardcoded urls and installing SSL certs in nginx in the pods ?

**Comment by manjeetsinghcodz** [comment]
solved damn it : 

Had to add this on nginx 

`add_header 'Content-Security-Policy' 'upgrade-insecure-requests';`
