### ISSUE TITLE
Implement the logic for `RequiredDuringSchedulingRequiredDuringExecution`

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#104895]
#### What would you like to be added:
The rule of Node Affinity `RequiredDuringSchedulingRequiredDuringExecution` has been marked as a TODO item longer than 5 years, while the semantic of the rule is clearly defined and pretty straightforward, 

> 	// If the affinity requirements specified by this field are not met at
	// scheduling time, the pod will not be scheduled onto the node.
	// If the affinity requirements specified by this field cease to be met
	// at some point during pod execution (e.g. due to an update), the system
	// will try to eventually evict the pod from its node.

The code in scheduler has been commented out since: https://github.com/kubernetes/kubernetes/pull/21057,  is there anything prevent us from implementing this feature? is it a good chance to implement this feature in the coming release, might be 1.24?

#### Why is this needed:

For some cases, Pod no longer qualified to run a specific node should be evicted so that the rules of node affinity will still be valid.

@ahg-g @Huang-Wei @alculquicondor @damemi  WDYT?

/sig scheduling
/sig node

**Comment by alculquicondor** [comment]
There is already an open issue for it: https://github.com/kubernetes/enhancements/issues/2358

There is nothing stopping us from implementing it, but it's mostly a sig-node feature.

I'm closing this issue so we can keep one discussion only

/close
