### ISSUE TITLE
Support CNI v1.0.0

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#104861]
#### What happened:

I trier to use cni v1.0.0 and cni-plugins v1.0.1 (bridge), but `kubelet` rejects with;
```
E0909 06:21:39.503175     376 kuberuntime_manager.go:819] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to create pod network sandbox k8s_mserver-deployment-654bbdc6dc-5zgtx_default_108fb616-8600-4539-87ec-800b9b83f92d_0(7f371758918223613e2ebbbbfa7557f949bc6035e99f6175aa564e8dab713eb5): unsupported CNI result version \"1.0.0\"" pod="default/mserver-deployment-654bbdc6dc-5zgtx"
```

#### What you expected to happen:

The first official cni release shall be supported.

#### How to reproduce it (as minimally and precisely as possible):

Use cni v1.0.0. I am using the `bridge` cni-plugin with this config;
```json
{
  "cniVersion": "1.0.0",
  "name": "cni-x",
  "type": "bridge",
  "bridge": "cbr0",
  "isDefaultGateway": true,
  "hairpinMode": true,
  "ipam": {
    "type": "host-local",
    "ranges": [
      [ { "subnet": "11.0.2.0/24" } ],
      [ { "subnet": "1100::200/120" } ]
    ]
  }
}
```

#### Anything else we need to know?:

Same config with cniVersion": "0.4.0" works fine.

Here is the printout;
```
./vendor/github.com/containernetworking/cni/pkg/version/version.go:     return nil, fmt.Errorf("unsupported CNI result version %q", version)
```

#### Environment:
- Kubernetes version (use `kubectl version`): master
- Cloud provider or hardware configuration: kvm vm's
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`): linux-5.13.1
- Install tools: none
- Network plugin and version (if this is a network-related bug): 
```
# /opt/cni/bin/bridge -v
CNI bridge plugin v1.0.1
```
- Others:

/sig network
/sig node

**Comment by uablrek** [comment]
I tried this;
```
git clean -dxf
hack/pin-dependency.sh github.com/containernetworking/cni v1.0.0
hack/update-vendor.sh
hack/verify-vendor.sh
hack/lint-dependencies.sh
hack/update-internal-modules.sh
# (build...)
```
Everything builds without problem but for some reason `kubelet` gives the same error as before.

**Comment by aojea** [comment]
/assign @squeed 
maybe is related to this https://www.cni.dev/docs/spec-upgrades/#libcni-changes-in-cni-v10 ?

**Comment by uablrek** [comment]
`github.com/containernetworking/cni` seems to be in "dockershim" only which makes sense since the CRI-plugin will handle this (I use `crio`);
```
kubernetes > grep -rF 'github.com/containernetworking/cni' pkg cmd
pkg/kubelet/dockershim/network/kubenet/kubenet_linux_test.go:   "github.com/containernetworking/cni/libcni"
pkg/kubelet/dockershim/network/kubenet/kubenet_linux_test.go:   "github.com/containernetworking/cni/pkg/types"
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:        "github.com/containernetworking/cni/libcni"
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:        cnitypes "github.com/containernetworking/cni/pkg/types"
pkg/kubelet/dockershim/network/kubenet/kubenet_linux.go:        cnitypes020 "github.com/containernetworking/cni/pkg/types/020"
pkg/kubelet/dockershim/network/cni/cni_windows.go:      cniTypes020 "github.com/containernetworking/cni/pkg/types/020"
pkg/kubelet/dockershim/network/cni/cni.go:      "github.com/containernetworking/cni/libcni"
pkg/kubelet/dockershim/network/cni/cni.go:      cnitypes "github.com/containernetworking/cni/pkg/types"
pkg/kubelet/dockershim/network/cni/cni.go:      // https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md
pkg/kubelet/dockershim/network/cni/cni.go:// see: https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md
pkg/kubelet/dockershim/network/cni/cni.go:// see: https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md and
pkg/kubelet/dockershim/network/cni/cni.go:// see: https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md
pkg/kubelet/dockershim/network/cni/cni.go:                      // see: https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md and
pkg/kubelet/dockershim/network/cni/cni_test.go: types020 "github.com/containernetworking/cni/pkg/types/020"
pkg/kubelet/dockershim/network/cni/testing/mock_cni.go: "github.com/containernetworking/cni/libcni"
pkg/kubelet/dockershim/network/cni/testing/mock_cni.go: "github.com/containernetworking/cni/pkg/types"
pkg/kubelet/dockershim/network/cni/cni_others.go:       "github.com/containernetworking/cni/libcni"
```

**Comment by uablrek** [comment]
Perhaps this is a check that "dockershim" that is unnecessary when a CRI-plugin+CNI-plugin is used?

**Comment by uablrek** [comment]
But I must of course check "crio"! Prehaps that's what you meant all along @aojea :smile:

**Comment by aojea** [comment]
> But I must of course check "crio"! Prehaps that's what you meant all along @aojea

I did the previous bump for cni dependencies on crio and containerd, I think containerd changed the structure of the repo, but this may serve as guide if someone want to help 

https://github.com/cri-o/ocicni/pull/79
https://github.com/containerd/cri/pull/1556

**Comment by uablrek** [comment]
This is a cri-plugin problem. I filed an issue on `cri-o` https://github.com/cri-o/cri-o/issues/5287.

I am unsure of the status of `dockershim`, if it should be updated or removed. I leave this issue open, please close it if it is not relevant.

**Comment by SergeyKanzhelev** [comment]
/triage accepted
/remove-sig node

This issue seems to be worked on. Looks like sig network issue

**Comment by khenidak** [comment]
thanks for this. I think we should keep the issue open. The fix should have zero code change (assuming we don't change the deprecated dockershim and kubenet). But we need to track it.

/assign @khenidak

**Comment by aojea** [comment]
/close
Thanks to @saschagrunert 
https://github.com/cri-o/cri-o/pull/5380
and @zouyee 
https://github.com/containerd/containerd/pull/6136
