### ISSUE TITLE
k8s Container runtimes

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [kubernetes/kubernetes#104871]
Hi.
What environment do the images run in?
Docker? If so, how can you run images in Podman?

**Comment by uablrek** [comment]
Read about https://kubernetes.io/docs/setup/production-environment/container-runtimes/

[cri-o](https://cri-o.io/) is _very_ close related to podman, I think they use the same libs.

At kubernetes.slack.com there is a #crio channel that handles so many `podman` questions that I left it (i use cri-o only). I think that is the place you should go for more information.

I close this issue if you don't mind.
/close

**Comment by EvgenyPrikhodko** [comment]
Thanks for the answer, how to run k8s with podman?

**Comment by uablrek** [comment]
`podman` is a tool and as such not directly called by cri-o, but cri-o creates pods and containers with the same libs as podman does, but verify that in the #crio slack channel. But I suggest you present your problem in a more generic way, like "I can do this with podman, how can I do the same in K8s" (with cri-o most likely).

**Comment by EvgenyPrikhodko** [comment]
but cri-o creates pods and containers with the same libs as podman does

Can you share a link to the documentation?

**Comment by uablrek** [comment]
No, sorry I am not a cri-o maintainer myself, just a cri-o user. But ask in the slack channel. I took a peek just now and there seem to be more podman questions than cri-o. Same as before :smiley:

**Comment by EvgenyPrikhodko** [comment]
)))
