### ISSUE TITLE
how to set elasticsearch JVM

### ISSUE THREAD

**Issue by cdzhangyong** [kubernetes/kubernetes#104896]
How to set elasticsearch JVM
I want set elasticsearch jvm Xms and  Xmx。
I edit es-statefulset.yaml as:
          resources:
            # need more cpu upon initialization, therefore burstable class
            limits:
              cpu: 1
              memory: 3.5Gi
            requests:
              cpu: 100m
              memory: 3.5Gi
          env:
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "MINIMUM_MASTER_NODES"
              value: "1"
            - name: ES_JAVA_OPTS
              value: "-Xms3g -Xmx3g "

I  deploy the statefulset but elasticsearch ues jvm Xms1g Xmx1g.
container info:
![image](https://user-images.githubusercontent.com/13670030/132827511-f4d63961-6bfe-4df9-a318-be96e7ff5dae.png)

**Comment by neolit123** [comment]
please try the support channels instead:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
