### ISSUE TITLE
TestDifferentWidths flakes 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#104860]
#### Which jobs are flaking:
pull-kubernetes-unit

#### Which test(s) are flaking:
TestDifferentWidths

#### Testgrid link:
 https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/104801/pull-kubernetes-unit/1435825901991366656

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit

#### Reason for failure:
```
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset: TestDifferentWidths expand_less | 0s
-- | --
=== RUN   TestDifferentWidths     queueset_test.go:211: 2021-09-09 05:03:38.347675904: Start TestDifferentWidths, doSplit=false, clk=0xc00024ec80, grc=0xc0000416d4     queueset_test.go:270: 2021-09-09 05:03:38.347675904: 0, 0, 0 got req=0xc000411c70, idle=false     queueset_test.go:286: 2021-09-09 05:03:38.347675904: 0, 0, 0 executing; seats=1     queueset_test.go:270: 2021-09-09 05:03:38.347675906: 1, 0, 0 got req=0xc000120d00, idle=false

<br class="Apple-interchange-newline">
```

#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

**Comment by MikeSpreitzer** [comment]
Yes, a couple of the unit tests have too stringent evaluations.
See https://github.com/kubernetes/kubernetes/pull/104856#issuecomment-916430271
