### ISSUE TITLE
ci-cgroup-systemd-containerd-node-e2e failed for golang version

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#104813]
#### Which jobs are failing:
ci-cgroup-systemd-containerd-node-e2e

#### Which test(s) are failing:

- e2e.go: Node Tests expand_more

#### Since when has it been failing:
since  #103692

#### Testgrid link:

https://testgrid.k8s.io/sig-node-containerd#cgroup-systemd-containerd-node-e2e

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroup-systemd-containerd-node-e2e/1435077560919658496

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cgroup-systemd-containerd-node-e2e/1434729541649043456/build-log.txt

#### Reason for failure:
```
W0906 04:08:11.598] I0906 04:08:11.598033    6440 run_remote.go:579] Creating instance {image:cos-89-16108-470-16 imageDesc:cos-89-16108-470-16 kernelArguments:[] project:cos-cloud resources:{Accelerators:[]} metadata:0xc0004ca1c0 machine: tests:[]} with service account "93366850354-compute@developer.gserviceaccount.com"
I0906 04:08:11.699] Initializing e2e tests using image cos-stable/cos-cloud/cos-89-16108-470-16.
I0906 04:08:11.699] make: Entering directory '/go/src/k8s.io/kubernetes'
I0906 04:08:11.699] make[1]: Entering directory '/go/src/k8s.io/kubernetes'
W0906 04:08:12.687] 
W0906 04:08:12.688] Detected go version: go version go1.16.7 linux/amd64.
W0906 04:08:12.688] Kubernetes requires go1.17.0 or greater.
W0906 04:08:12.688] Please install go1.17.0 or later.
W0906 04:08:12.688] 
W0906 04:08:12.693] !!! [0906 04:08:12] Call tree:
W0906 04:08:12.696] !!! [0906 04:08:12]  1: hack/run-in-gopath.sh:31 kube::golang::setup_env(...)
W0906 04:08:12.746] 
W0906 04:08:12.747] Detected go version: go version go1.16.7 linux/amd64.
W0906 04:08:12.747] Kubernetes requires go1.17.0 or greater.
W0906 04:08:12.747] Please install go1.17.0 or later.
```

**Comment by adisky** [comment]
@pacoxu passing now https://testgrid.k8s.io/sig-node-containerd#cgroup-systemd-containerd-node-e2e, I didn't update go version as there was already a PR by boat k8s-ci-robot
shall we close this?

**Comment by pacoxu** [comment]
Thanks for the info @adisky 
/close
since the CI is green now.
