### ISSUE TITLE
1.23 Release Notes: Known Issues

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#104885]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.23 Release Notes([example from 1.22 release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.22.md#known-issues)). If you know of issues or API changes that are going out in 1.23, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @Damans227 @AuraSinis @parul5sahoo @sam-cogan 
/sig release
/milestone v1.23

**Comment by csantanapr** [comment]
v1.23 is already released and release notes are located here
/close

cc @AuraSinis
