### ISSUE TITLE
Bump github.com/json-iterator/go to v1.1.12

### ISSUE THREAD

**Issue by mkumatag** [kubernetes/kubernetes#104947]
#### Which jobs are failing:

Kubernetes tests and some of the components using `github.com/json-iterator/go` are failing with golang tip because the [issue](https://github.com/golang/go/issues/48238#issuecomment-917321536) reported and got fixed in the [json-iterator v1.1.12 release](https://github.com/json-iterator/go/releases/tag/v1.1.12)

#### Which test(s) are failing:
Sample test report can be found here - https://prow.ppc64le-cloud.org/view/s3/prow-logs/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le/1437101281280790528

#### Reason for failure:
https://github.com/modern-go/reflect2/issues/24
https://github.com/golang/go/issues/48238

#### Anything else we need to know:

Bumping github.com/json-iterator/go to v1.1.12 in the following repositories will help to fix the issue mentioned here

https://cs.k8s.io/?q=json-iterator%2Fgo&i=nope&files=go.mod&excludeFiles=vendor&repos=kubernetes/kubernetes

- [ ] kubernetes/kubernetes
- [ ] k8s.io/apimachinery
- [ ] k8s.io/code-generator
- [ ] k8s.io/kube-aggregator

**Comment by mkumatag** [comment]
cc @Karthik-K-N

**Comment by Karthik-K-N** [comment]
Working on required changes
