### ISSUE TITLE
Improve docs on running host_processs.go e2e tests....

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#104987]
@weiwenli97  has some details on issues encountered w/ host-process tests... using this as an issue to track them.

**Comment by weiwenli97** [comment]
I want to run host_process.go e2e tests.

First, I installed Windows dev environment in my local machine using kubernetes 1.22+.

Then, I followed the guidance to enable --feature-gates=WindowsHostProcessContainers=true for both kubelet and api-server. Also, I updated hcsshim and config.toml.

After that, I created a host-process pod and it worked well.

At last, I wanted to run host-process e2e test in sig-windows. And it was skipped for **feature 'WindowsHostProcessContainers' is not enabled**. Then I rebuilt the e2e binary using the args **make TEST_ARGS=‘--feature-gates=WindowsHostProcessContainers=true’**. And run e2e case using the new built binary.
And the same as before, the case was skipped with the same reason.

**Comment by san-coding** [comment]
Hey, is this issue still open? I would like to work on this, I am new to open source

**Comment by marosset** [comment]
@weiwenli97 you need to pass in --feature-gates=WindowsHostProcessContainers=true to the e2e.test binary too like we do here https://github.com/kubernetes/test-infra/blob/2b1842bf54cad06e7733bf7e82aba9b74daf2e89/config/jobs/kubernetes-sigs/sig-windows/release-master-windows.yaml#L733

@ mention me for faster responses in the future :)

**Comment by jayunit100** [comment]
oh ! `--node-os-distro=windows` @weiwenli97  :) should fix it !

**Comment by marosset** [comment]
Yup, we check to make sure node-os-distro is windows and the feature is enabled.

https://github.com/kubernetes/kubernetes/blob/86c64375305d5f18a1372e36f5a50041bf3ccd48/test/e2e/windows/host_process.go#L37-L40

**Comment by weiwenli97** [comment]
Thank all of you very much! @marosset @jayunit100 
I pass --feature-gates=WindowsHostProcessContainers=true when running e2e.test. And the test could be triggered.
I just build the e2e.test using --feature-gates=WindowsHostProcessContainers=true and it doesn't work.

**Comment by marosset** [comment]
@weiwenli97 @jayunit100 this got addressed in a sig-windows community meeting correct?

**Comment by weiwenli97** [comment]
@marosset I thought it hadn't been addressed in a sig-windows community meeting. And it only focused on docs. And I have found how to run host_process e2e test. Thanks!
