### ISSUE TITLE
Cleanup admission/eventratelimit to use clock.RealClock

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#104994]
#### What happened:
While working on https://github.com/kubernetes/kubernetes/pull/104578, I realized that https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/admission/eventratelimit/clock.go implements another `realClock` rather than using the one already implemented in https://github.com/kubernetes/apimachinery/tree/master/pkg/util/clock. 

I'm not sure why this was re-implemented, but if we can migrate to using `clock.RealClock` itself, then the code in the `flowcontrol` package can be cleaned up significantly (as part of https://github.com/kubernetes/kubernetes/pull/104578).

#### What you expected to happen:
I expect areas of the codebase that make use of a real clock to consistently use `clock.RealClock` instead of re-implementing it

#### How to reproduce it (as minimally and precisely as possible):
NA

#### Anything else we need to know?:
Another (slightly) related issue: https://github.com/kubernetes/kubernetes/issues/94738

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by MikeSpreitzer** [comment]
Better yet, use the one in https://github.com/kubernetes/utils/blob/master/clock/clock.go
