### ISSUE TITLE
[Flaky test] Kubernetes e2e suite.[sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should conform to Ingress spec

### ISSUE THREAD

**Issue by simrangupta234** [kubernetes/kubernetes#104941]
#### Which jobs are failing:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-ingress/1432573009574498304

#### Which test(s) are failing:
```html
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should conform to Ingress spec 
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:118
Aug 31 05:37:28.291: error in waiting for ingress to get an address: Failed to execute a successful GET within 10m0s, Last response body for https://34.120.38.178/foo, host foo.bar.com:

timed out waiting for the condition
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:124
```
```html
e2e.go: Test 
error during ./hack/ginkgo-e2e.sh --ginkgo.focus=\[Feature:Ingress\]|\[Feature:NEG\] --report-dir=/workspace/_artifacts --disable-log-dump=true: exit status 1
```
#### Since when has it been failing:
08/31/2021

#### Testgrid link:
https://testgrid.k8s.io/sig-release-master-blocking#gci-gce-ingress&exclude-non-failed-tests=

**Comment by dims** [comment]
cc @aojea

**Comment by aojea** [comment]
only 1 failure in last 15 runs and no failure in last 12 is not enough to know if is a infra hiccup, an environment issue, a flake, ...
As a rule of thumb we should open issues if one test fails at least 2 times in 10 executions
