### ISSUE TITLE
Question: Why to vendor runc in k8s

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes/kubernetes#104974]
It is more of a question since I was trying to find out the reason why runc is vendored in k8s. 
Can someone share some thoughts about why runc is vendored in k8s in a bit more detail, since I was not able to find any mention of it in the repo(why to vendor, where it is used, what it is used for?). However, as I went through the repo  a bit,  I got to know that Kubelet is trying to use it  from the vendor directory (maybe, cgroup related code inside runc?). Thanks in advance!

**Comment by furkatgofurov7** [comment]
@odinuge @saschagrunert @dims @kolyshkin

**Comment by pacoxu** [comment]
There are already some discussions in #104325. 
Would you discuss this in that thread?

**Comment by neolit123** [comment]
> There are already some discussions in #104325.

+1 discussions should happen in a single place.

also #code-organization on k8s slack is the channel to discuss vendor topics.

/close
/kind support
