### ISSUE TITLE
Namespace not found, even when created at the earliest

### ISSUE THREAD

**Issue by kamikazechaser** [kubernetes/kubernetes#104930]
#### What happened:

```bash
$ kubectl apply -R -f build
clusterissuer.cert-manager.io/dev-letsencrypt-production created
clusterrole.rbac.authorization.k8s.io/dev-keel created
clusterrolebinding.rbac.authorization.k8s.io/dev-keel created
namespace/helloworld created
namespace/keel created
ingress.networking.k8s.io/dev-keel-ingress created
deployment.apps/dev-keel created
poddisruptionbudget.policy/dev-keel created
service/dev-keel created
serviceaccount/dev-keel created
Error from server (NotFound): error when creating "build/helloworld/dev-helloworld.Deployment.yaml": namespaces "helloworld" not found
Error from server (NotFound): error when creating "build/helloworld/dev-helloworld.Ingress.yaml": namespaces "helloworld" not found
Error from server (NotFound): error when creating "build/helloworld/dev-helloworld.Service.yaml": namespaces "helloworld" not found
```

An error was thrown in spite of namespace being created earlier. Running apply a second time fixes the issue.

#### What you expected to happen:

`No error as namespace was created earlier.`

#### How to reproduce it (as minimally and precisely as possible):

kubectl apply -R -f build

#### Anything else we need to know?:

I have seen similar issues on here and skaffold, the solutions are to create the namespace earlier than the other resources.

- https://github.com/GoogleContainerTools/skaffold/issues/6259

#### Environment:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}```
```
- Cloud provider or hardware configuration: DOKS

**Comment by liggitt** [comment]
What order were the failed resources created in? Can you add --v=6 to see what order the create requests were made in?

**Comment by kamikazechaser** [comment]
> Can you add --v=6 to see what order the create requests were made in?

https://gist.github.com/kamikazechaser/8b3feaa3660b4775bb93fc920069ccb0

**Comment by liggitt** [comment]
> Does the recursive option strictly follow alphabetical order?

I think so

**Comment by liggitt** [comment]
> From what I can see it does try to create the helloworld resources (deployment, ingress, service) much earlier in that order.

yeah, the namespace has to be created first
