### ISSUE TITLE
[KEP-2400] Add e2e tests that exercise all available swap configurations

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105025]
#### What would you like to be added:

We need e2e coverage and validation of behaviour for the following scenarios:

- cgroupsv1 + LimitedSwap
- cgroupsv1 + UnlimitedSwap
- cgroupsv2 + LimitedSwap
- cgroupsv2 + UnlimitedSwap

We also need to ensure that the container runtimes in test-infra are bumped to the right versions so that the swap memory parameters are correctly passed through.

#### Why is this needed:

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta

**Comment by shuheiktgw** [comment]
I'd like to work on this issue if I may!
/assign

**Comment by shuheiktgw** [comment]
I've been trying to work on this PR but could not figure out where to start... This issue might be a bit too complicated for beginners like me so let me unassign myself... 🙇 

/unassign

**Comment by ehashman** [comment]
/milestone clear
per https://github.com/kubernetes/enhancements/issues/2400#issuecomment-1068228077

**Comment by iholder101** [comment]
This issue is inactive and outdated. Please refer to this one instead: https://github.com/kubernetes/kubernetes/issues/119430

**Comment by iholder101** [comment]
Please refer also to https://github.com/kubernetes/kubernetes/issues/120798.
Closing this issue as it's inactive.

/close
