### ISSUE TITLE
Telnet on nodeip and nodeport is failing 

### ISSUE THREAD

**Issue by sharathbabupulumati** [kubernetes/kubernetes#105024]
Hi Team, 

I have a scenario where I need to expose my application outside to the cluster which is a top based service. So fir that I choose nodeport as my option.

Where,  I have deployed 3 nodeport services with different port numbers  consecutively for exposing multiple endpoints.

But, I see that only few of the exposed ports are succeeded using telnet.
For ex. I have deployed a 3 node port services with 32226, 32227 and 32228. Where my pod and it's replicas  lies on the same node.

In the above example setup, only one or 2 ports are succeeded in telnet check, where as others are not working as expected. I have cross verified that endpoints is successfully created and mapped with the service.

Could you please help me on this?

**Comment by pacoxu** [comment]
https://kubernetes.io/docs/tasks/debug-application-cluster/debug-service/ is a nice doc for debugging services.

**Comment by thockin** [comment]
+1 to @pacoxu - @sharathbabupulumati please take a look at that and let us know if something seems like it's a bug.
