### ISSUE TITLE
informer factory start caused error: stream error when reading response body, may be caused by closed connection

### ISSUE THREAD

**Issue by illusion202** [kubernetes/kubernetes#105096]
#### What happened:
When I start numbers of informer factories to list and watch serval k8s clusters pods（about 100+ clusters）**at the same time**，I probability got the following error log：

> `E0818 15:20:40.181837  277770 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Pod: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 57; INTERNAL_ERROR
I0818 15:21:45.785777  277770 trace.go:205] Trace[316394150]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (18-Aug-2021 15:20:41.181) (total time: 64603ms):
Trace[316394150]: [1m4.603865861s] [1m4.603865861s] END
E0818 15:21:45.785795  277770 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Pod: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 61; INTERNAL_ERROR
I0818 15:22:55.875784  277770 trace.go:205] Trace[447267791]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (18-Aug-2021 15:21:46.785) (total time: 69089ms):
Trace[447267791]: [1m9.089869849s] [1m9.089869849s] END
E0818 15:22:55.875799  277770 reflector.go:153] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.Pod: stream error when reading response body, may be caused by closed connection. Please retry. Original error: stream error: stream ID 63; INTERNAL_ERROR
I0818 15:24:01.885872  277770 trace.go:205] Trace[435704625]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:135 (18-Aug-2021 15:22:56.875) (total time: 65009ms):
Trace[435704625]: [1m5.009982746s] [1m5.009982746s] END`

PS：
1. Total pod data size about 40~50Gi
2. After serval minutes or hours，informer factory retrys to list pods many of time and starts successfully

#### Environment:
- Kubernetes version (use `kubectl version`):  v1.17.4
- Client OS (e.g: `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Client Kernel (e.g. `uname -r`): 3.10.0-1.0.1.el7.x86_64

**Comment by illusion202** [comment]
sig/api-machinery

**Comment by pacoxu** [comment]
Same error message in https://github.com/helm/helm/issues/7997.

According to  @lavalamp 's [comments](https://github.com/helm/helm/issues/7997#issuecomment-683886838), it may be caused by operations that take more than 60 seconds hit the global timeout.
