### ISSUE TITLE
AWS: Kube Up Issues (possibly salt related)

### ISSUE THREAD

**Issue by iterion** [kubernetes/kubernetes#10508]
I'm having issues bringing a cluster up on latest master. I initially had issues bringing up the master, but was able to get it running by running `sudo salt '*' state.highstate` again. This showed me the following output:
```
ip-172-20-0-118.ec2.internal:
Data failed to compile:
----------
The function "state.highstate" is running as PID 16712 and was started at 2015, Jun 29 22:20:00.029092 with jid 20150629222000029092
ip-172-20-0-119.ec2.internal:
Data failed to compile:
----------
The function "state.highstate" is running as PID 16530 and was started at 2015, Jun 29 22:19:56.083956 with jid 20150629221956083956
```

By killing the pid it references on each node and running highstate again I'm able to get that node to start up correctly. @justinsb perhaps there is some new race condition created by the auto-scaling group? I'm not sure why the salt process is getting stuck, not much in the salt minion logs:

```
2015-06-29 22:20:09,570 [salt.loaded.int.module.cmdmod][ERROR   ] Command 'service docker start' failed with return code: 1
2015-06-29 22:20:09,570 [salt.loaded.int.module.cmdmod][ERROR   ] output: start: Job failed to start
2015-06-29 22:20:09,574 [salt.state       ][ERROR   ] Service docker is already enabled, and is dead
```

I think the master failing to start up completely could be related to nodes not starting up, but it could be a separate issue.

This was in us-east with c3.xlarge for master and r3.2xlarge for nodes and ubuntu as the distro, everything else was default.

**Comment by iterion** [comment]
I also tried scaling up the auto-scaling group and saw that those nodes experienced the same issue. So, it seems most likely that there is something in the behavior of the cloud-init script. However, I've looked through those logs and nothing seems out of the ordinary.

**Comment by iterion** [comment]
More progress, I can get the node to come online just by running `sudo service docker stop`.  The salt run that was stuck then continues and registers the node correctly with the master. The upstart logs for docker contain a bunch of references to not being able to connect to `/var/run/docker.sock`.

**Comment by dchen1107** [comment]
Which kubernetes version are you running here?

**Comment by iterion** [comment]
I built from master as of yesterday afternoon. I believe the same issue was
happening on 0.20.0.

**Comment by iterion** [comment]
Closing this as it seems to be resolved now. I haven't seen it happen again on newer builds.
