### ISSUE TITLE
kubeadm join failed when kubelet configured with --register-node=false

### ISSUE THREAD

**Issue by geotransformer** [kubernetes/kubernetes#105059]
#### What happened:
kubeadm join failed when kubelet configured with --register-node

#### What you expected to happen:
it should join the node to the cluster

#### How to reproduce it (as minimally and precisely as possible):
1. have a cluster running
2. boot up another node and install kubeadm, kubelet and kubectl
3. Prepare the kubeadm-config.yaml. Config the kubelet with --register-node=false
4. kubeadm join with the kubeadm-config.yaml
#### Anything else we need to know?:
If kubeadm join creates a node object to the cluster when kubelet is configured with  --register-node=false, it probably can resolve this issue. 

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Wed 2021-09-15 22:43:19 UTC; 12s ago
     Docs: https://kubernetes.io/docs/home/
 Main PID: 9847 (kubelet)
    Tasks: 14 (limit: 4680)
   CGroup: /system.slice/kubelet.service
           └─9847 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --register-node=false --cert-dir=/data/k

Sep 15 22:43:30-mm-master2 kubelet[9847]: E0915 22:43:30.594610    9847 kubelet.go:2298] "Error getting node" err="node \"-mm-master2\" not found"
Sep 15 22:43:30-mm-master2 kubelet[9847]: E0915 22:43:30.695253    9847 kubelet.go:2298] "Error getting node" err="node \"-mm-master2\" not found"

https://kubernetes.io/docs/concepts/architecture/nodes/
Management
There are two main ways to have Nodes added to the API server:

The kubelet on a node self-registers to the control plane
You (or another human user) manually add a Node object
After you create a Node object, or the kubelet on a node self-registers, the control plane checks whether the new Node object is valid. For example, if you try to create a Node from the following JSON manifest:

{
  "kind": "Node",
  "apiVersion": "v1",
  "metadata": {
    "name": "10.240.79.157",
    "labels": {
      "name": "my-first-k8s-node"
    }
  }
}
#### Environment:
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: not matter
- OS (e.g: `cat /etc/os-release`):Ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools: kubeadm
- Network plugin and version (if this is a network-related bug): Calico
- Others:

**Comment by pacoxu** [comment]
I think this is expected. If `--register-node=false`, the node will not register to the cluster(However, kubeadm join/init will check the node status.)

```
cat <<EOF | sudo tee kubeadm-register-node-false.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    register-node: "false"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
EOF
kubeadm init -v 4  --config kubeadm-register-node-false.yaml
```

**Comment by neolit123** [comment]
--register-node=false is unsupported by kubeadm. kubeadm relies on the kubelet to create and manage the node object and i don't think we want to support manual creation of node objects.

Also from my experiments in the past, feeding a custom node object gets accepted and updated by the kubelet but the node never becomes ready.

You can play with workarounds but i do not think there is much we can do here.

**Comment by neolit123** [comment]
/close
Please let us know if you have more comments.
