### ISSUE TITLE
 the "^M" appears in the output.

### ISSUE THREAD

**Issue by verycici** [kubernetes/kubernetes#105061]
What happened:

When Use kubectl -n namespace exec -it pod -- bash -c "command" > test.txt . the "^M" appears in the output.

For example:

$ kubectl -nkube-system exec -it kube-proxy-4pkq9 -- sh -c "ls -al /" > 1.txt 
$ cat -t 1.txt 
total 68^M
drwxr-xr-x   1 root root 4096 Sep  7 11:18 .^M
drwxr-xr-x   1 root root 4096 Sep  7 11:18 ..^M
-rwxr-xr-x   1 root root    0 Sep  7 11:18 .dockerenv^M
lrwxrwxrwx   1 root root    7 Oct  8  2020 bin -> usr/bin^M
drwxr-xr-x   2 root root 4096 Apr 15  2020 boot^M
drwxr-xr-x  13 root root 3560 Sep  7 11:18 dev^M
drwxr-xr-x   1 root root 4096 Sep  7 11:18 etc^M
drwxr-xr-x   2 root root 4096 Apr 15  2020 home^M
-rwxr-xr-x   1 root root 1646 Aug 18 19:14 hyperkube^M
lrwxrwxrwx   1 root root    7 Oct  8  2020 lib -> usr/lib^M
lrwxrwxrwx   1 root root    9 Oct  8  2020 lib32 -> usr/lib32^M
lrwxrwxrwx   1 root root    9 Oct  8  2020 lib64 -> usr/lib64^M
lrwxrwxrwx   1 root root   10 Oct  8  2020 libx32 -> usr/libx32^M
drwxr-xr-x   2 root root 4096 Oct  8  2020 media^M
drwxr-xr-x   2 root root 4096 Oct  8  2020 mnt^M
drwxr-xr-x   2 root root 4096 Oct  8  2020 opt^M
dr-xr-xr-x 214 root root    0 Sep  7 11:18 proc^M
drwx------   2 root root 4096 Oct  8  2020 root^M
drwxr-xr-x   1 root root 4096 Sep  7 11:18 run^M
lrwxrwxrwx   1 root root    8 Oct  8  2020 sbin -> usr/sbin^M
drwxr-xr-x   2 root root 4096 Oct  8  2020 srv^M
dr-xr-xr-x  13 root root    0 Sep 10 16:47 sys^M
drwxrwxrwt   2 root root 4096 Oct  8  2020 tmp^M
drwxr-xr-x   1 root root 4096 Oct  8  2020 usr^M
drwxr-xr-x   1 root root 4096 Oct  8  2020 var^M

What you expected to happen:

it should not use the "^M".

Environment:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:41:22Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.14", GitCommit:"c93cd0e4cfd27c8216a9ee2b6f1969a9d1294c5c", GitTreeState:"clean", BuildDate:"2021-08-18T11:09:02Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by RyanAoh** [comment]
Is the file `1.txt` created by a windows-based text editor？
It seems that this is because the windows-based text editors will have a special carriage return character (CR+LF) at the end of lines to denote a line return or newline, which will be displayed incorrectly in Linux (^M).

**Comment by crossphoton** [comment]
Hi,
Can you tell how to reproduce this?
Here's what I tried on minikube.

- started minikube
- created a namespace `test`
- create a nginx pod
- ran `kubectl --namespace=test exec -it nginx -- sh -c "ls -al /" > cat.txt`

There's no `^M` in the output.

Kubernetes: 1.22.1
GoVersion: 1.16.7

**Comment by lauchokyip** [comment]
@crossphoton , I was able to reproduce using [Kubernetes Playground](https://www.katacoda.com/courses/kubernetes/playground), they key is the command `cat -t 1.txt`
```
controlplane $ cat -t 1.txt
total 76^M
drwxr-xr-x   1 root root 4096 Sep 20 13:35 .^M
drwxr-xr-x   1 root root 4096 Sep 20 13:35 ..^M
-rwxr-xr-x   1 root root    0 Sep 20 13:35 .dockerenv^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 bin^M
drwxr-xr-x   2 root root 4096 Feb  3  2019 boot^M
drwxr-xr-x   5 root root  360 Sep 20 13:35 dev^M
drwxr-xr-x   1 root root 4096 Sep 20 13:35 etc^M
drwxr-xr-x   2 root root 4096 Feb  3  2019 home^M
drwxr-xr-x   8 root root 4096 Mar 26  2019 lib^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 lib64^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 media^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 mnt^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 opt^M
dr-xr-xr-x 147 root root    0 Sep 20 13:35 proc^M
drwx------   2 root root 4096 Mar 26  2019 root^M
drwxr-xr-x   1 root root 4096 Sep 20 13:35 run^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 sbin^M
drwxr-xr-x   2 root root 4096 Mar 26  2019 srv^M
dr-xr-xr-x  13 root root    0 Sep 20 13:35 sys^M
drwxrwxrwt   2 root root 4096 Mar 26  2019 tmp^M
drwxr-xr-x  10 root root 4096 Mar 26  2019 usr^M
drwxr-xr-x   1 root root 4096 Mar 26  2019 var^M
```

**Comment by lauchokyip** [comment]
I don't think this is a bug, when you run `kubectl` with the flag `-t ` , [docker will convert \n to \r\n](https://github.com/moby/moby/issues/37366#issuecomment-401157643)

**Comment by crossphoton** [comment]
@lauchokyip Ah yes,

I used `cat cat.txt` for the output. Didn't even notice that.

**Comment by verycici** [comment]
you can try it .


$&nbsp;a=`kubectl -nkube-system exec -it kube-proxy-nrxwb -- sh -c "ls -al /|wc -l"`
$ echo $a
22


$ echo $a &gt; 111.txt
$ cat -t 111.txt&nbsp;
22^M


the $a is not a&nbsp;integer，it's 22^M.&nbsp;If I put the&nbsp; "$a" in the script,&nbsp; I can't compare it with other numbers




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/kubernetes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月20日(星期一) 晚上9:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes]  the "^M" appears in the output. (#105061)





 
@lauchokyip Ah yes,
 
I used cat cat.txt for the output. Didn't even notice that.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lauchokyip** [comment]
> you can try it . $&nbsp;a=`kubectl -nkube-system exec -it kube-proxy-nrxwb -- sh -c "ls -al /|wc -l"` $ echo $a 22 $ echo $a &gt; 111.txt $ cat -t 111.txt&nbsp; 22^M the $a is not a&nbsp;integer，it's 22^M.&nbsp;If I put the&nbsp; "$a" in the script,&nbsp; I can't compare it with other numbers
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kubernetes/kubernetes" ***@***.***&gt;; 发送时间:&nbsp;2021年9月20日(星期一) 晚上9:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [kubernetes/kubernetes] the "^M" appears in the output. (#105061) @lauchokyip Ah yes, I used cat cat.txt for the output. Didn't even notice that. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Can you try
```
kubectl -nkube-system exec -it kube-proxy-4pkq9 -- sh -c "stty -onlcr && ls -al /" > 1.txt
```

**Comment by verycici** [comment]
I tried. It's no problem


$ kubectl -nkube-system exec -it kube-proxy-nrxwb&nbsp; -- sh -c "stty -onlcr &amp;&amp; ls -al /" &gt; 1.txt
$ cat -t 1.txt&nbsp;
total 76
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 Sep 20 13:59 .
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 Sep 20 13:59 ..
-rwxr-xr-x&nbsp; &nbsp;1 root root&nbsp; &nbsp; 0 Sep 20 13:59 .dockerenv
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 Jun 23 04:13 bin
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 Mar 19&nbsp; 2021 boot
drwxr-xr-x&nbsp; &nbsp;8 root root 2700 Sep 20 13:59 dev
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 Sep 20 13:59 etc
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 Mar 19&nbsp; 2021 home
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 Sep 20 13:59 lib
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 May 11 00:00 media
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 May 11 00:00 mnt
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 May 11 00:00 opt
dr-xr-xr-x 222 root root&nbsp; &nbsp; 0 Sep 20 13:59 proc
drwx------&nbsp; &nbsp;2 root root 4096 Jun 22 09:43 root
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 Sep 20 13:59 run
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 Jun 23 04:13 sbin
drwxr-xr-x&nbsp; &nbsp;2 root root 4096 May 11 00:00 srv
dr-xr-xr-x&nbsp; 13 root root&nbsp; &nbsp; 0 Sep 20 13:58 sys
drwxrwxrwt&nbsp; &nbsp;2 root root 4096 Jun 23 04:13 tmp
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 May 11 00:00 usr
drwxr-xr-x&nbsp; &nbsp;1 root root 4096 May 11 00:00 var



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/kubernetes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月20日(星期一) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes]  the "^M" appears in the output. (#105061)





  
you can try it . $&nbsp;a=kubectl -nkube-system exec -it kube-proxy-nrxwb -- sh -c "ls -al /|wc -l" $ echo $a 22 $ echo $a &gt; 111.txt $ cat -t 111.txt&nbsp; 22^M the $a is not a&nbsp;integer，it's 22^M.&nbsp;If I put the&nbsp; "$a" in the script,&nbsp; I can't compare it with other numbers
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "kubernetes/kubernetes" @.&gt;; 发送时间:&nbsp;2021年9月20日(星期一) 晚上9:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [kubernetes/kubernetes] the "^M" appears in the output. (#105061) @lauchokyip Ah yes, I used cat cat.txt for the output. Didn't even notice that. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
Can you try
 kubectl -nkube-system exec -it kube-proxy-4pkq9 -- sh -c "stty -onlcr &amp;&amp; ls -al /" &gt; 1.txt  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brianpursley** [comment]
> I don't think this is a bug, when you run `kubectl` with the flag `-t ` , [TTY will convert \n to \r\n](https://github.com/moby/moby/issues/37366#issuecomment-401157643)

@lauchokyip I think you might be on to something.

I'm not able to reproduce the problem on a 1.23 cluster that is using containerd.

I wonder if being able to reproduce this has to do with which container runtime your cluster uses.

**Comment by lauchokyip** [comment]
@brianpursley I am using containerd but k3s server version 1.21.4
