### ISSUE TITLE
Improve unit tests for Kubelet configuration APIs

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105029]
There are two main issues right now with the test coverage for the Kubelet configuration APIs (internal type defined by [pkg/kubelet/apis/config/types.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/pkg/kubelet/apis/config/types.go) and serializable type at [staging/src/k8s.io/kubelet/config/v1beta1/types.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/staging/src/k8s.io/kubelet/config/v1beta1/types.go))

1. There are no unit tests for [pkg/kubelet/apis/config/v1beta1/defaults.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/pkg/kubelet/apis/config/v1beta1/defaults.go)

We should at minimum have unit tests that populate defaults for the most minimal config, e.g. [pkg/apis/core/v1/defaults_test.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/pkg/apis/core/v1/defaults_test.go)

2. The validation tests in [pkg/kubelet/apis/config/validation/validation_test.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/pkg/kubelet/apis/config/validation/validation_test.go) are not targeted

These just throw together a bunch of different validation issues and then count the errors. In theory, if one thing breaks but another is fixed, the tests won't fail. These should be completely refactored in order to test *specific* validation behaviours, e.g. as in [pkg/apis/core/v1/validation/validation_test.go](https://github.com/kubernetes/kubernetes/blob/fa2657b8b2f839b88834579917abda1a816a1970/pkg/apis/core/v1/validation/validation_test.go)

/sig node
/kind cleanup
/priority important-longterm
/area test
/help

If you are a relatively new contributor, please give the [API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md) and [API change](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md) docs a read as they will help provide context for you to dive in.

/cc @liggitt

**Comment by shuheiktgw** [comment]
Hi @ehashman, I'm new to kubernetes/kubernetes repository but I'd like to work on this issue as my first one if I may!
/assign @shuheiktgw

**Comment by pacoxu** [comment]
#96675 is a problem with the default value of a flag/configuration. If we have the default_test.go, it should not happen then.

**Comment by shuheiktgw** [comment]
@ehashman @pacoxu I've added tests for pkg/kubelet/apis/config/v1beta1/defaults.go so would you review the PR?
https://github.com/kubernetes/kubernetes/pull/105116

I start working on pkg/kubelet/apis/config/validation/validation_test.go next!

**Comment by shuheiktgw** [comment]
@ehashman @pacoxu I've refactored tests in the validation so would you review the PR?
https://github.com/kubernetes/kubernetes/pull/105360
