### ISSUE TITLE
'kubectl diff'  ability to  show what is going to be removed 

### ISSUE THREAD

**Issue by rubber-ant** [kubernetes/kubernetes#105043]
#### What would you like to be added:

when I run this command:
`kubectl diff -f  template.yaml`

I can see the difference between the file _template.yaml_ and the current online configuration  ONLY of what is going to add or change but not remove.

Is it possible to also show in the difference what is going to be removed from the current configuration?

#### Why is this needed:

It will give a full and complete overview of the actual difference between filename and the current online configuration

/sig cli

**Comment by apelisse** [comment]
`kubectl diff` shows you what apply would do. Apply usually doesn't remove resources, unless you use prune, is that what you're referring too? While I think that makes sense, I think `kubectl apply --prune` is mostly non-recommended so I don't know if we would invest time in this.

**Comment by rubber-ant** [comment]
@apelisse

yes something like `prune`  

For example, when using `kubectl diff` with a new flag  `--overwrite=true`

`kubectl diff -f  file.yaml --overwrite=true` will act as it will overwrite the full configuration from the file to the current config  
so I can see if the actual file configuration is really the same as the current config or if something is missing.

**Comment by rubber-ant** [comment]
the improvement I'm talking about is also mentioned at end of this page   https://kubernetes.io/blog/2019/01/14/apiserver-dry-run-and-kubectl-diff/   

![image](https://user-images.githubusercontent.com/2983049/133514614-d7d92413-5478-4061-a1f5-aec1f77e74f3.png)

**Comment by apelisse** [comment]
Yeah, I don't know if I disagree. I'd be happy to guide you if you want to work on this.

cc @seans

**Comment by ardaguclu** [comment]
@rubber-ant Are you planning to work on this?

**Comment by rubber-ant** [comment]
@ardaguclu nop, just reported.

**Comment by cmssczy** [comment]
I try to run command `kubectl diff -f file` and found that It could display what is going to be removed. Did I misunderstand?

```bash
kubectl diff -f busybox.yaml
```
```yaml

diff -u -N /tmp/LIVE-144669027/v1.Pod.default.client /tmp/MERGED-294686566/v1.Pod.default.client
--- /tmp/LIVE-144669027/v1.Pod.default.client	2021-09-17 16:58:34.124620295 +0800
+++ /tmp/MERGED-294686566/v1.Pod.default.client	2021-09-17 16:58:34.130620625 +0800
@@ -4,9 +4,9 @@
   annotations:
-    key: value            # Deleted
     kubectl.kubernetes.io/last-applied-configuration: |
       {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{"key":"value"},"name":"client","namespace":"default"},"spec":{"containers":[{"command":["tail","-f","/dev/null"],"image":"busybox:latest","name":"busybox"}],"nodeSelector":null}}
+    test: aaa              # Added
   creationTimestamp: "2021-09-17T07:42:11Z"
   managedFields:
   - apiVersion: v1
@@ -61,8 +61,8 @@
       f:metadata:
         f:annotations:
           .: {}
-          f:key: {}
           f:kubectl.kubernetes.io/last-applied-configuration: {}
+          f:test: {}
       f:spec:
         f:containers:
           k:{"name":"busybox"}:
@@ -82,7 +82,7 @@
         f:terminationGracePeriodSeconds: {}
     manager: kubectl
     operation: Update
-    time: "2021-09-17T08:57:22Z"       # Changed
+    time: "2021-09-17T08:58:34Z"
   name: client
   namespace: default
   resourceVersion: "1969120"
```

**Comment by rubber-ant** [comment]
@cmssczy, 
get your full configuration YAML and delete a deployment or sts and then try it. 
or 
extreme but easy way  to test
try to pass an empty YAML file, it should show up all to delete with the `-` symbol but it doesn't.

**Comment by cmssczy** [comment]
> try to pass an empty YAML file, it should show up all to delete with the - symbol but it doesn't.
@rubber-ant got what you said.
But why `kubectl diff -f busybox.yaml` could get what we expected?
