### ISSUE TITLE
[Feature Request] Rollout-Restart permission

### ISSUE THREAD

**Issue by jmprovencher** [kubernetes/kubernetes#105074]
#### What would you like to be added:

I know this might not be the perfect place for feature request, but I'm not sure I would have been able to submit that in the enhancement repository. 

Currently, the `kubectl rollout restart deployment` command requires `edit deployment` using the RBAC Authorization model defined [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/). This approach is causing a little bit of a security problem internally at our company, since in some environment, like HIPAA, giving developers access to 'edit/create deployment' is a big security liability. However, we would like to give them the ability to perform a rollout-restart on a deployment.

#### Why is this needed:

1. Least privilege access
2. One example of a use-case of needing a rollout-restart without having the right to edit a deployment would be for example when a service has dynamic configuraitons at boot time and that this given configuration has change, it would be interesting for developers to be able to perform a rollout restart so that all the rotated pods have the new configuration available.

**Comment by liggitt** [comment]
/remove-sig auth
/sig apps

The operation for restarting a deployment is not distinguished from any other edit currently. Routing to sig-apps for the feature request.

**Comment by liggitt** [comment]
Traditionally, the way sub-object policy is enforced is via admission, which has both the old and new object information, and the user information, in order to make decisions about whether the particular write request should be allowed.

**Comment by jmprovencher** [comment]
> The operation for restarting a deployment is not distinguished from any other edit currently. Routing to sig-apps for the feature request.

Perfect thanks! I know that currently it's not distinguished from any other edit operation, however I really feel like it would make sense to separate both. We tend to try to forbid developers to be able to manually edit a deployment in a production environment (for obvious security reasons) but we would like them to be able to restart the deployment if necessary.
