### ISSUE TITLE
[KEP-2400] Verify MemoryPressure behaviour with swap enabled

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105023]
#### What would you like to be added:

Verify MemoryPressure behaviour with swap enabled and document any changes for configuring eviction.

- New e2e tests (start with manual verification and then develop this into automated e2es)
- Documentation updates, as needed

#### Why is this needed:

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta

**Comment by mmiranda96** [comment]
I'm interested in this, taking a look...
/cc

**Comment by SergeyKanzhelev** [comment]
/assign @mmiranda96

feel free to unassign yourself if decided to

**Comment by helayoty** [comment]
Hi @ehashman, this is a bug triage shadow for release v1.24, are we still targeting the current release for this issue?

**Comment by ehashman** [comment]
/milestone clear
per https://github.com/kubernetes/enhancements/issues/2400#issuecomment-1068228077

**Comment by SergeyKanzhelev** [comment]
See the report: https://github.com/kubernetes/enhancements/issues/2400#issuecomment-1693451128

**Comment by iholder101** [comment]
This issue is old, outdated and inactive. Also, I don't have the rights to update the description and @ehashman is no longer working on this.

Closing in favor of this replacement issue: https://github.com/kubernetes/kubernetes/issues/120800.
/close
