### ISSUE TITLE
[KEP-2400] Add swap memory to the Kubelet stats API

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105021]
#### What would you like to be added:

Add swap memory to the Kubelet stats API so that we have metrics on swap utilization.

- Code changes
- Add e2e coverage

#### Why is this needed:

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta

**Comment by mengjiao-liu** [comment]
I want to work on it.
/assign

I see that the names and types of metrics have not been determined in the [KEP documentation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap). Should we determine them before implementation? @ehashman

**Comment by yxxhero** [comment]
@mengjiao-liu May I  be a backup? Thansk very much. wo can work together for this KEP.
/assign

**Comment by mengjiao-liu** [comment]
> @mengjiao-liu May I be a backup? Thansk very much. wo can work together for this KEP.
> /assign

Of course, very happy to work with you.

**Comment by ehashman** [comment]
/unassign @yxxhero @mengjiao-liu 
/milestone v1.24

Clearing assignees for this release as there are no attached PRs, please reassign if you have the bandwidth to complete this.

**Comment by mmiranda96** [comment]
I'm interested in working on this for 1.24
/assign

**Comment by mengjiao-liu** [comment]
Still working on this.
/assign @yxxhero @mengjiao-liu
/unassign @assign

**Comment by ehashman** [comment]
ack, thank you!

**Comment by helayoty** [comment]
@ehashman @mengjiao-liu  👋  the release 1.24 bug triage shadow. Does this issue still target release 1.24?

**Comment by iholder101** [comment]
Issue is inactive and outdated. Please use this one instead: https://github.com/kubernetes/kubernetes/issues/119425
