### ISSUE TITLE
[e2e-test] fail for ingress-nginx-controller validating webhook

### ISSUE THREAD

**Issue by fusida** [kubernetes/kubernetes#105039]
#### What happened:
k8s version: 1.20
ingress-nginx: installed

when we run e2e-test and k8s-conformance, something wrong was happened, because it create ingress three times in the same "host + path":
test/e2e/network/ingress.go  line: 1020
```
// Ingress resource create/read/update/watch verbs
ginkgo.By("creating")
_, err := ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
framework.ExpectNoError(err)
_, err = ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
framework.ExpectNoError(err)
createdIngress, err := ingClient.Create(context.TODO(), ingTemplate, metav1.CreateOptions{})
framework.ExpectNoError(err)
```
it cause:
```
admission webhook \"validate.nginx.ingress.kubernetes.io\" denied the request: host \"foo.bar.com\" and path \"/\" is already defined in ingress ingress-6591/e2e-example-ingfh6zq
```
log info :
```
[sig-network] Ingress API
  should support creating Ingress API operations [Conformance]
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
[BeforeEach] [sig-network] Ingress API
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:174
STEP: Creating a kubernetes client
Sep 15 09:30:08.451: INFO: >>> kubeConfig: /tmp/kubeconfig-861644554
STEP: Building a namespace api object, basename ingress
STEP: Waiting for a default service account to be provisioned in namespace
[It] should support creating Ingress API operations [Conformance]
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:629
STEP: getting /apis
STEP: getting /apis/networking.k8s.io
STEP: getting /apis/networking.k8s.iov1
STEP: creating
Sep 15 09:30:08.595: FAIL: Unexpected error:
    <*errors.StatusError | 0xc002051a40>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "admission webhook \"validate.nginx.ingress.kubernetes.io\" denied the request: host \"foo.bar.com\" and path \"/\" is already defined in ingress ingress-6591/e2e-example-ingfh6zq",
            Reason: "BadRequest",
            Details: nil,
            Code: 400,
        },
    }
    admission webhook "validate.nginx.ingress.kubernetes.io" denied the request: host "foo.bar.com" and path "/" is already defined in ingress ingress-6591/e2e-example-ingfh6zq
occurred

Full Stack Trace
k8s.io/kubernetes/test/e2e/network.glob..func11.1()
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/ingress.go:1020 +0xe13
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000e41800)
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc000e41800)
        _output/dockerized/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:144 +0x2b
testing.tRunner(0xc000e41800, 0x4fc1e88)
        /usr/local/go/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1168 +0x2b3
[AfterEach] [sig-network] Ingress API
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:175
STEP: Collecting events from namespace "ingress-6591".
STEP: Found 1 events.
```

#### What you expected to happen:
run e2e-test without error
#### How to reproduce it (as minimally and precisely as possible):
just run e2e-test with ingress-nginx installed
it should not run three times in the same "host + path", even metadata.name unique.
#### Anything else we need to know?:
our k8s may have webhook to validate ingress "host + path" right, so do not run thress times same path again.
#### Environment:
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug): ingress-nginx-controller
- Others:

**Comment by pacoxu** [comment]
/sig network
link to a PR discussion in #100449

**Comment by fusida** [comment]
it think it should run by unique "host + path", not just unique name

**Comment by fusida** [comment]
> /sig network
> link to a PR discussion in #100449
I think it's not a good idea to remove ingree-nginx validating webhook or remove e2e-test/ingress.go code in line 1020.
just run test repeat by unique "host + path", not just unique name.

**Comment by rikatz** [comment]
So per previous comment on the PR, it seems that the test is trying to run with Validation Webhook enabled. 

As this is up to each ingress implementation to implement or not a validation webhook, we can not surely say "Validation Webhook" should be part of the k8s e2e test, as for what e2e test does is create 3 entries on the API and check if the 3 were created.

IMO running that e2e tests on an existing cluster with validation webhook from specific Ingress Controllers is a bad idea, I would recommend you running kubernetes e2e tests on a cluster different from ingress-nginx.
