### ISSUE TITLE
[KEP-2400] Add support for controlling swap consumption at the pod level via cgroups

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105020]
#### What would you like to be added:

Add support for controlling swap consumption at the pod level via cgroups.

- Code changes (currently this is only supported per-container)
  - Ensure we handle usage of swap during container restart boundaries for writes to tmpfs (which may require pod cgroup change beyond what container runtime will do at container cgroup boundary).
- e2e tests that exercise and verify functionality
  - Ensure we have coverage for the tmpfs case

#### Why is this needed:

See https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2400-node-swap#beta

**Comment by dimakow** [comment]
Sorry, i think i will not have enough free-time to make it till deadline

/unassign

**Comment by helayoty** [comment]
@ehashman 👋  the release 1.24 bug triage shadow. Does this issue still target release 1.24?

**Comment by ehashman** [comment]
/milestone clear
per https://github.com/kubernetes/enhancements/issues/2400#issuecomment-1068228077

**Comment by iholder101** [comment]
This issue is inactive and outdated. Please refer to this one instead: https://github.com/kubernetes/kubernetes/issues/120801

/close
