### ISSUE TITLE
topologySpreadConstraint doesn't work fine when only one worker node is eligible for workload

### ISSUE THREAD

**Issue by sunchill06** [kubernetes/kubernetes#105072]
#### What happened:
Created a deployment with topologySpreadConstraint with topology key kubernetes.io/hostname, with the following config
topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar

Created deployment with 2 replicas and both the pods landed on the same worker node. 
#### What you expected to happen:
I expected that second pod would have gone in Pending state.

#### How to reproduce it (as minimally and precisely as possible):

Create following deployment:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deploy
  labels:
    foo: bar
spec:
  replicas: 2
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-name
                operator: In
                values:
                - node1
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            foo: bar
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
Make sure that only one worker node is eligible for workload using nodeSelectors or nodeAffinity.

foo-deploy-7d7bd695b8-xcdw2   1/1     Running   0          12s    192.168.107.140   node1 <none>           <none>
foo-deploy-7d7bd695b8-xsk2k   1/1     Running   0          12s    192.168.107.141   node 1<none>           <none>

#### Environment:
- Kubernetes version (use `kubectl version`): 
**kubectl version**
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:**"v1.20.4"**, GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:24:15Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"ec2760d6d916781de466541a6babb4309766c995", GitTreeState:"clean", BuildDate:"2021-02-27T17:18:03Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
NAME="SLES"
VERSION="15-SP1"
VERSION_ID="15.1"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP1"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp1"

- Kernel (e.g. `uname -a`):
Linux XXXXX 4.12.14-195-default #1 SMP Tue May 7 10:55:11 UTC 2019 (8fba516) x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sunchill06** [comment]
Can someone please look into this?

**Comment by ahg-g** [comment]
/assign @Huang-Wei 

I think there is a bug here: 
https://github.com/kubernetes/kubernetes/blob/b15f788d29df34337fedc4d75efe5580c191cbf3/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L317

We should do the following:
```
minMatchNum := paths[0].MatchNum
if paths.TopologyValue == node.Labels[c.TopologyKey] {
 minMatchNum := paths[1].MatchNum
}
```

**Comment by ahg-g** [comment]
we need to back port the fix as well.

**Comment by Huang-Wei** [comment]
It's not a bug. The problem lies in the nodeAffinity spec:

```yaml
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-name
          operator: In
          values:
          - node1
```

As documented [here](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#interaction-with-node-affinity-and-node-selectors), when you use node selector or node affinity, the spreading calculation will be performed against the nodes that fit the node selector and node affinity, instead of the entire cluster. So in your case, the pod is required to be scheduled to "node1" **only**, and based on that, apply the topology spread constraints, so it's legal to stack unlimited pods on this single node.

**Comment by sunchill06** [comment]
so what about respecting maxSkew? I expected the pods to be in the pending state if maxSkew is not met.

**Comment by Huang-Wei** [comment]
> so what about respecting maxSkew

When there is only one node, there is actually no concept of "skew". What's your intention of restricting node affinity to one single node, while also applying topology spread constraints? I cannot even think of a use case.

**Comment by sunchill06** [comment]
I just wanted to understand whether skew is considered when there is only one node eligible for the workload. Also, it's not intended to restrict node affinity to one single node, rather it was observed unintentionally, and just wanted to make sure that we are not missing anything.

Thanks for clarifying that this is the intended behavior.

**Comment by ahg-g** [comment]
Ok, I think what I am proposing will only allow brining at most another failure domain (force a second node or zone), which doesn't really solve the problem and it may actually not be desirable in all cases.

Note that this behavior is not limited to using node affinity/selector, imagine a cluster that started with a single node or zone.

I think the topology spread API can use another parameter, call it `MinDomains` which we currently assume to be 1. Imagine that I have service that I want to spread over at least two zones or three nodes, `MinDomains` will force the filter to reject scheduling the pod until we have the desired number of zones/nodes.

**Comment by ahg-g** [comment]
@MaciekPytel @x13n for thoughts, although I know that using "Required" spreading is not something we usually recommend because of stockouts.

**Comment by Huang-Wei** [comment]
> I think the topology spread API can use another parameter, call it `MinDomains` which we currently assume to be 1.

That doesn't quite work as the user can specify more than one constraint.

**Comment by ahg-g** [comment]
> That doesn't quite work as the user can specify more than one constraint.

We add it for each constraint, like skew.

**Comment by Huang-Wei** [comment]
> We add it for each constraint, like skew.

That should work. If we get adequate real-world requirements, I'm fine with getting it implemented.

**Comment by alculquicondor** [comment]
Let's get clear on something first:
OP's question is answered. This is working-as-intended. The skew is respected. Since there is only one candidate node, the skew is zero (there are 2 pods in the candidate node and the node with the least amount of pods has 2 pods `2-2=0`).

@ahg-g if you believe there is the potential for a new feature, can we open a new issue?

**Comment by ahg-g** [comment]
opened https://github.com/kubernetes/kubernetes/issues/105291 to discuss the potential for adding another parameter.
