### ISSUE TITLE
 A bug that mutates a not-used copy of a struct

### ISSUE THREAD

**Issue by guodongli-google** [kubernetes/kubernetes#105155]
Report a bug that mutates a not-used copy of a struct.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L49-L50

Here "PatchMeta" is struct which will be copied by value. The mutation on the copy receiver "pm" doesn't do anything to the original struct in the caller. As a consequence, this mutation has no meaningful effect. 

```
type PatchMeta struct {
	patchStrategies []string
	patchMergeKey   string
}

func (pm PatchMeta) SetPatchStrategies(ps []string) {
	pm.patchStrategies = ps
}
```

The fix is to use pointer receiver.
```
func (pm *PatchMeta) SetPatchStrategies(ps []string) {
	pm.patchStrategies = ps
}
```

A similar issue:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L41-L42

Found by #deepgo.

**Comment by gjkim42** [comment]
/cc

Just curious... is this ever meaningfully used?

**Comment by NikhilSharmaWe** [comment]
I would like to change the value reciever to reference reciever.

**Comment by neolit123** [comment]
isn't that a problem here as well?
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L166

**Comment by guodongli-google** [comment]
> https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go#L166

This one seems fine since `s.Schema` is of an interface type (similar to pointer type) so `s.Schema` will be reused/shared by the caller and the side effect takes place.
```
type PatchMetaFromOpenAPI struct {
	Schema openapi.Schema
}

type Schema interface {
	// Giving a visitor here will let you visit the actual type.
	Accept(SchemaVisitor)
	...
}
```

**Comment by guodongli-google** [comment]
Just filed a similar one: https://github.com/kubernetes/kubernetes/issues/105423
which contains a mini bug reproducer: https://play.golang.org/p/cibNCyIarZS
