### ISSUE TITLE
Introduce JSON logging format for kube-proxy

### ISSUE THREAD

**Issue by pchan** [kubernetes/kubernetes#105165]
#### What would you like to be added:

Structured logging support in k8s allows specifying logging in JSON. Many k8s components like apiServer, scheduler have support for json. This issue tracks adding JSON logging support for kube-proxy.  

#### Breakdown of the task

To get json logging support, changes have to be made in kube-proxy and Kind e2e script (for Prow/CI runs) which uses KubeProxyConfiguration 

1. Introduce logging-format (--logging-format string  ) option in kube-proxy. Currently there is none. ([link](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/))
2. Introduce an option in [KubeProxyConfiguration](https://github.com/kubernetes/kube-proxy/blob/v0.22.1/config/v1alpha1/types.go#L104) so that kubeadm/kind can specify logging-format. Whether this "configuration option" is something generic or specific to logging needs input from a kube-proxy domain expert.
3. Update Kind to make use of the above 2 and specify the logging format similar to how we do for control-plane components. 
4. Prow/test-infra CI runs will have json logging enabled for kube-proxy.

#### Why is this needed:
To get the benefits of structured logging.

/sig network
/cc @serathius 
/cc @BenTheElder

**Comment by NikhilSharmaWe** [comment]
I would like to contribute towards this feature.

**Comment by NikhilSharmaWe** [comment]
@pchan can you explain the 3rd point, I am unable to understand.

**Comment by pchan** [comment]
> @pchan can you explain the 3rd point, I am unable to understand.

Kind is used to run e2e testing and recently it was updated for enabling json logging for control plane components. Issue https://github.com/kubernetes/kubernetes/issues/100748

**Comment by thockin** [comment]
Sounds reasonable.

/triage accepted

**Comment by NikhilSharmaWe** [comment]
I have added the Logs type for kubeadm/kind to specify logging-format for kube-proxy and saw #100748 issue and how they added JSON formatting for other k8s components, but getting difficulty to underestand how to proceed for adding this feature. Guidance needed.

**Comment by cyclinder** [comment]
Any one working on this? I would try on this. I think the demand for this issue is similar to https://github.com/kubernetes/kubernetes/pull/91532.

**Comment by danwinship** [comment]
@cyclinder afaik no one is working on this

**Comment by cyclinder** [comment]
Thanks!

/assign
