### ISSUE TITLE
CSI e2e test subpath parameters are incorrect

### ISSUE THREAD

**Issue by pzheng1025** [kubernetes/kubernetes#105129]
#### What happened:
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/testsuites/subpath.go#L162-L164
In subpath.go, `filePathInSubpath` and `filePathInVolume` are defined as follows

```
l.subPathDir = filepath.Join(volumePath, subPath)
l.filePathInSubpath = filepath.Join(volumePath, fileName)
l.filePathInVolume = filepath.Join(l.subPathDir, fileName)
```

#### What you expected to happen:
From the variable name, should `filePathInSubpath` and `filePathInVolume` be swapped? Like:
```
l.filePathInVolume = filepath.Join(volumePath, fileName)
l.filePathInSubpath = filepath.Join(l.subPathDir, fileName)
```

**Comment by BenTheElder** [comment]
/remove-sig testing
[SIG storage owns their test code, this is specific to the subpath tests, not general testing infra/framework.]

**Comment by Kartik494** [comment]
I am working on this

**Comment by Kartik494** [comment]
@pzheng1025 i have raised PR #106489 for this .PTAL

**Comment by Kartik494** [comment]
closing the issue in reference of [conversation](https://github.com/kubernetes/kubernetes/pull/106489#discussion_r780079899).
/close

**Comment by Kartik494** [comment]
Hi @pzheng1025 We should close this issue now as per [discussion](https://github.com/kubernetes/kubernetes/pull/106489#discussion_r780079899) this a legit behaviour , not a bug

**Comment by Kartik494** [comment]
Hi @pzheng1025 could you please close this issue , as per [discussion](https://github.com/kubernetes/kubernetes/pull/106489#discussion_r780079899) ?
Thanks!

**Comment by pzheng1025** [comment]
Sounds good.
