### ISSUE TITLE
Query string is not forwarded in case of WebSocket connections in `UpgradeAwareHandler`

### ISSUE THREAD

**Issue by mertyildiran** [kubernetes/kubernetes#105105]
#### What happened:

For an `UpgradeAwareHandler` handler created by this line:

https://github.com/kubernetes/kubectl/blob/d11f42ab701cb66eec24aa24b3f19939d6409e32/pkg/proxy/proxy_server.go#L214

query string is not forwarded to the upstream if it's a WebSocket connection.

It's disappearing somewhere in this function:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L275-L426

#### What you expected to happen:

Query string should be forwarded.

#### How to reproduce it (as minimally and precisely as possible):

Deploy an image that has an HTTP server, define an endpoint for WebSocket. 

Put a proxy in front of that with `proxy.NewProxyHandler`.

Send a request with scheme `ws://` and add some query string like `?q=blabla`. Try to get the query string from the HTTP server.

#### Anything else we need to know?:

It might be an issue related to https://github.com/kubernetes/kubectl instead of directly Kubernetes.

#### Environment:

I'm sure this is an issue in these versions:

```go
k8s.io/apimachinery v0.21.2
k8s.io/kubectl v0.21.2
```

Also reproduced it in these releases:
- `v0.22.3-rc.0`
- `v0.22.2`

**Comment by pacoxu** [comment]
/sig cli
(not sure if it is caused by network or apimachinery)

**Comment by mertyildiran** [comment]
@pacoxu I've actually tried to disable the call to `tryUpgrade` function and the issue persisted.

One of the WebSocket upgrade related headers producing this issue `-H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: x3JJHMbDL1EzLkh9GBhXDw=="`

So I looked at the calls to `IsUpgradeRequest` in the codebase:
- https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go#L277
- https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_proxy.go#L217

Could it be related to `kube-aggregator` instead of `apimachinery`?

Could you please point me to the related network code that you've mentioned so I can look at it?

**Comment by mertyildiran** [comment]
@pacoxu I actually couldn't reproduce it in isolation. I guess the issue is invalid/nonexistent. I'm sorry for filing this issue.

**Comment by mertyildiran** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/77142
