### ISSUE TITLE
no matches for kind "IAMPolicy" in version "iam.cnrm.cloud.google.com/v1beta1"

### ISSUE THREAD

**Issue by gauravrao08** [kubernetes/kubernetes#105149]
#### Which jobs are failing:
iam.cnrm.cloud.google.com/v1beta1

#### Which test(s) are failing:
IAMPolicy
#### Since when has it been failing:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/531fa4f6b0211f5fb92131c33f3c7d0d5eed8fc5/samples/tutorials/workload-identity/policy-binding.yaml
#### Anything else we need to know:

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: iampolicy-workload-identity-sample
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    #name: [sm-scl-eng-owner@PROJECT_ID.iam.gserviceaccount.com]
    name: sm-scl-eng-owner@PROJECT_ID.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:PROJECT_ID.svc.id.goog[scl-cloudlm-wi/rao-sa]
        
 error: unable to recognize "policy.yaml": no matches for kind "IAMPolicy" in version "iam.cnrm.cloud.google.com/v1beta1"

**Comment by neolit123** [comment]
hi, this doesn't seem like a upstream Kubernetes issue.
IAMPolicy is part of the Google Cloud API, thus please report the problem to the Google Cloud support instead.

/kind support
/close
