### ISSUE TITLE
upgrade coredns to 1.8.6 to fix a regression bug

### ISSUE THREAD

**Issue by calvin0327** [kubernetes/kubernetes#105189]
FYI: @neolit123

Last week a regression was [reported](https://github.com/coredns/coredns/issues/4834) for 1.8.4 for the _rewrite_ plugin. There is a workaround. FYI AFAIK, AKS has [decided to defer rolling out 1.8.4](https://github.com/Azure/AKS/issues/2521#issuecomment-911901518), skipping over the version, since a fix will be in 1.8.5 (already merged).
Describing the regression as succinctly as I can:

> If using the _rewrite_ plugin, a rewrite rule that does not also rewrite the response (using the `answer` option) will cause clients to reject any response rewritten by the rule (due to question section mismatch). A work around is to append `answer auto` to affected rules. All `exact` name rewrites are not affected since they automatically perform a response rewrite.

FWIW, this has always been the case for _some_ clients (some clients are extra picky about question mismatch), but the regression caused it to affect _most_ clients (if not all).  My attempt to explain in more detail [here](https://github.com/coredns/coredns/issues/4834#issuecomment-908544954).

Also, regarding the workaround, `answer auto` is only valid in 1.8.4, so a user cannot use that option to adjust their corefile before upgrading to avoid potential downtime.  If that is desired, any affected rule should be expressed as a `regex` rule with a response rewrite, which would be valid in 1.84 and prior versions.

_Originally posted by @chrisohaver in https://github.com/kubernetes/kubernetes/issues/102466#issuecomment-915682855_

**Comment by neolit123** [comment]
thanks for the summary @calvin0327 
updating coredns to 1.8.5 in kubeadm 1.22 (current release) makes sense.

i'm also +1 to backport the 1.8.5 patch update to kubeadm 1.21.x
@pacoxu WDYT?

/triage accepted

**Comment by pacoxu** [comment]
Agree.

We should cherry-pick the fix to 1.22 for the regression.

**Comment by chrisohaver** [comment]
FYI, There's a reload plugin bug reported in coredns 1.8.5, where coredns crashes when its configuration is changed.   https://github.com/coredns/coredns/issues/4880.

**Comment by neolit123** [comment]
Thanks for the notice @chrisohaver
I guess we should wait for the next patch.

**Comment by pacoxu** [comment]
/retitle upgrade coredns to 1.8.6 to fix a regression bug 

We need to wait for coredns 1.8.6.
- https://github.com/coredns/coredns/pull/4881
- https://github.com/coredns/coredns/pull/4884

**Comment by calvin0327** [comment]
okay.

**Comment by pacoxu** [comment]
We should publish coredns image to `k8s.gcr.io` like https://github.com/kubernetes/k8s.io/pull/2118.

```
[root@daocloud ~]# docker pull k8s.gcr.io/coredns/coredns:v1.8.5
Error response from daemon: manifest for k8s.gcr.io/coredns/coredns:v1.8.5 not found: manifest unknown: Failed to fetch "v1.8.5" from request "/v2/coredns/coredns/manifests/v1.8.5".
```

After coredns released, you need open a PR to promote `coredns/coredns:1.8.5` or `coredns/coredns:1.8.6` to `k8s.gcr.io/coredns/coredns`

**Comment by NilimaC04** [comment]
Hello there, Bug-Triage Shadow here 👋 #2897 has been merged. If the issue has been resolved completely. Please close the issue.
