### ISSUE TITLE
`$deleteFromPrimitiveList` is not idempotent

### ISSUE THREAD

**Issue by timebertt** [kubernetes/kubernetes#105146]
#### What happened:

Patching an object without finalizers using `$deleteFromPrimitiveList/finalizers` results in the given finalizers being added.

#### What you expected to happen:

`deleteFromPrimitiveList` is idempotent in case there are other list elements than the removed one.
I expected `deleteFromPrimitiveList` to also be idempotent in case the list is already empty.

#### How to reproduce it (as minimally and precisely as possible):

1. Create an arbitrary object:

```
$ k create cm foo -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-20T07:44:27Z"
  name: foo
  namespace: default
  resourceVersion: "3688787"
  uid: 0bd6fc58-97c4-4e22-b0fa-6248dccdddb2
```

2. Add an arbitrary finalizer to the object via strategic merge patch:

```
$ k patch cm foo --type=strategic -p '{"metadata":{"finalizers":["fancy.io/foo"]}}' -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-20T07:44:27Z"
  finalizers:
  - fancy.io/foo
  name: foo
  namespace: default
  resourceVersion: "3688814"
  uid: 0bd6fc58-97c4-4e22-b0fa-6248dccdddb2
```

3. Remove the finalizer again by using the `deleteFromPrimitiveList` directive:

```
$ k patch cm foo --type=strategic -p '{"metadata":{"$deleteFromPrimitiveList/finalizers":["fancy.io/foo"]}}' -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-20T07:44:27Z"
  name: foo
  namespace: default
  resourceVersion: "3688881"
  uid: 0bd6fc58-97c4-4e22-b0fa-6248dccdddb2
```

4. Send the same patch again:

```
$ k patch cm foo --type=strategic -p '{"metadata":{"$deleteFromPrimitiveList/finalizers":["fancy.io/foo"]}}' -oyaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-20T07:44:27Z"
  finalizers:
  - fancy.io/foo
  name: foo
  namespace: default
  resourceVersion: "3688909"
  uid: 0bd6fc58-97c4-4e22-b0fa-6248dccdddb2
```

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.20.4`

**Comment by brianpursley** [comment]
Strange.  It looks like attempting to delete a nonexistent primitive actually adds it.

Below is a slightly different take on your example, client-side only and without any finalizers to start with.  It tries to delete `fancy.io/foo` which is nonexistent and it ends up being added:

```
$ kubectl patch --local -f <(kubectl create cm foo --dry-run=client -o yaml) --dry-run=client --type=strategic -p '{"metadata":{"$deleteFromPrimitiveList/finalizers":["fancy.io/foo"]}}' -o yaml
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  finalizers:
  - fancy.io/foo
  name: foo
```

I also tested with some previous versions of kubectl (back to 1.10.2 even) and saw the same thing, so it appears to have always been this way.

**Comment by timebertt** [comment]
I just checked: the same thing happens when directly talking to the API server (so it's not a kubectl-only bug):

```
$ k proxy &
Starting to serve on 127.0.0.1:8001

$ curl -H "Accept: application/json" 'http://localhost:8001/api/v1/namespaces/default/configmaps/foo'
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "default",
    "uid": "0bd6fc58-97c4-4e22-b0fa-6248dccdddb2",
    "resourceVersion": "3702292",
    "creationTimestamp": "2021-09-20T07:44:27Z",
    "finalizers": [
      "fancy.io/foo"
    ]
  }
}

$ curl -XPATCH  -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" 'http://localhost:8001/api/v1/namespaces/default/configmaps/foo' -d '{"metadata":{"$deleteFromPrimitiveList/finalizers":["fancy.io/foo"]}}'
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "default",
    "uid": "0bd6fc58-97c4-4e22-b0fa-6248dccdddb2",
    "resourceVersion": "3702314",
    "creationTimestamp": "2021-09-20T07:44:27Z"
  }
}

$ curl -XPATCH  -H "Accept: application/json" -H "Content-Type: application/strategic-merge-patch+json" 'http://localhost:8001/api/v1/namespaces/default/configmaps/foo' -d '{"metadata":{"$deleteFromPrimitiveList/finalizers":["fancy.io/foo"]}}'
{
  "kind": "ConfigMap",
  "apiVersion": "v1",
  "metadata": {
    "name": "foo",
    "namespace": "default",
    "uid": "0bd6fc58-97c4-4e22-b0fa-6248dccdddb2",
    "resourceVersion": "3702316",
    "creationTimestamp": "2021-09-20T07:44:27Z",
    "finalizers": [
      "fancy.io/foo"
    ]
  }
}
```

**Comment by timebertt** [comment]
> I also tested with some previous versions of kubectl (back to 1.10.2 even) and saw the same thing, so it appears to have always been this way.

@brianpursley that's good to know. But I guess, this is not expected behavior, right?

**Comment by brianpursley** [comment]
> > I also tested with some previous versions of kubectl (back to 1.10.2 even) and saw the same thing, so it appears to have always been this way.
> 
> @brianpursley that's good to know. But I guess, this is not expected behavior, right?

I don't think it is expected behavior.  It is surprising to me at least.  I am curious to know what someone who has more experience with Strategic Merge Patch has to say though.

**Comment by liggitt** [comment]
looks like this was reported in https://github.com/kubernetes/kubernetes/pull/82320 as well

**Comment by apelisse** [comment]
The best workaround for now is probably to json merge patch the whole list with the resourceVersion set.

I don't know much about the code nor the bug, but it really looks like a bug rather than a feature, so we should be able to fix it without causing too much surprise to other users. We generally have limited interest fixing smp but that seems worthy.

Is somone interested in looking at it?
