### ISSUE TITLE
kubernetes endpointslices object not working with "AddressType: FQDN"

### ISSUE THREAD

**Issue by vasim38** [kubernetes/kubernetes#105172]
As the kubernetes provides feature called "endpointslices" specifically to be useful for larger clusters, endpointslices are not working with "addressType: FQDN"
 
As mentioned below (case A & case B), case A) works fine and Iptables rules are modified accordingly. For Case B) with "addressType: FQDN" It didn't work at all. There was no change in Iptables rule. Also it is not clear how the dns get resolved. 

A) For addressType: IPv4

----------------------------
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: po-ep-svc-eps
  labels:
    kubernetes.io/service-name: po-ep-svc
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "34.221.30.175"           # any IPv4 for external (apps not running in k8s pods) service.

Observations on Iptables rule showed the routes were added for 34.221.30.175 & 8.8.8.8 example IPs. 

[ec2-user@ip-192-168-16-180 ~]$ sudo iptables-save | grep  -i po-ep-svc 
-A KUBE-SEP-BHLBJAVIWHVWXVNI -s 34.221.30.175/32 -m comment --comment "default/po-ep-svc:http" -j KUBE-MARK-MASQ
-A KUBE-SEP-BHLBJAVIWHVWXVNI -p tcp -m comment --comment "default/po-ep-sv:http" -m tcp -j DNAT --to-destination 34.221.30.175:80
-A KUBE-SEP-H7SOG7SGKDKPNQHI -s 8.8.8.8/32 -m comment --comment "default/po-ep-svc:http" -j KUBE-MARK-MASQ
-A KUBE-SEP-H7SOG7SGKDKPNQHI -p tcp -m comment --comment "default/po-ep-sv:http" -m tcp -j DNAT --to-destination 8.8.8.8:80
-A KUBE-SEP-HRXYNMJP74SXYNLG -s 192.168.46.155/32 -m comment --comment "default/po-ep-svc:http" -j KUBE-MARK-MASQ
-A KUBE-SEP-HRXYNMJP74SXYNLG -p tcp -m comment --comment "default/po-ep-sv:http" -m tcp -j DNAT --to-destination 192.168.46.155:80
-A KUBE-SERVICES -d 10.100.0.175/32 -p tcp -m comment --comment "default/po-ep-svc:http cluster IP" -m tcp --dport 80 -j KUBE-SVC-EBKN2CM4M5HJSU6Y
-A KUBE-SVC-EBKN2CM4M5HJSU6Y -m comment --comment "default/po-ep-svc:http" -m statistic --mode random --probability 0.33333333349 -j KUBE-SEP-HRXYNMJP74SXYNLG
-A KUBE-SVC-EBKN2CM4M5HJSU6Y -m comment --comment "default/po-ep-svc:http" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-BHLBJAVIWHVWXVNI
-A KUBE-SVC-EBKN2CM4M5HJSU6Y -m comment --comment "default/po-ep-svc:http" -j KUBE-SEP-H7SOG7SGKDKPNQHI

Validation :

Terminal$ kubectl exec nginx -it bash 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@nginx:/# 
root@nginx:/# curl my-service 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>Test Page for the Apache HTTP Server</title>

Result: Passed

B) For addressType: FQDN 
----------------------------
apiVersion: discovery.k8s.io/v1beta1
kind: EndpointSlice
metadata:
  name: po-ep-svc-abc
  labels:
    kubernetes.io/service-name: po-ep-svc
addressType: FQDN
ports:
  - name: http
    protocol: TCP
    port: 80
endpoints:
  - addresses:
      - "myservice.somedomain.com" #  DNS for external (apps not running in k8s pods) service 

==================

Validation : 

Terminal$ kubectl exec nginx -it bash 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
root@nginx:/# 
root@nginx:/# curl my-service
curl: (7) Failed to connect to my-service port 80: Connection refused

Result: Failed

Any guidance/clarification on above would be helpful. 

Ref :
[1] https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/ 
[2] https://static.sched.com/hosted_files/kccnceu19/f0/Scale%20Kubernetes%20Service%20Endpoints%20100x.pdf

**Comment by vasim38** [comment]
Can someone please take a look ?

**Comment by aojea** [comment]
/sig network
/kind documentation

FQDN addresses are not used by kube-proxy so they won't work, @robscott can you expand on this?

**Comment by robscott** [comment]
Thanks for raising this issue! As @aojea said, we need to update the docs here to clarify that FQDN EndpointSlices are not useful to kube-proxy and are therefore ignored. The use for FQDN was really for different potential consumers of the API, but it was not intended to be something that proxy implementations would consume.

/triage accepted

**Comment by aojea** [comment]
> /remove-lifecycle stale

what is your expectation @vasim38 ?
AddressType FQDN will now work for kube-proxy as explained in previous comments

**Comment by harsh4870** [comment]
> > /remove-lifecycle stale
> 
> what is your expectation @vasim38 ? AddressType FQDN will now work for kube-proxy as explained in previous comments

You mean FQDN will not work for kube-proxy right ? Or now work for kube-proxy ? 

i am trying same so if you could please help.

**Comment by vasim38** [comment]
@harsh4870 Yes I raised it for the same issue. I did not see any live example or use of it and raised this. I was replied [this](https://github.com/kubernetes/kubernetes/issues/105172#issuecomment-1001798532) by @aojea

**Comment by harsh4870** [comment]
Yes @vasim38  thanks for a prompt response however i have not with it **Now** work with FQDN or **Not** work with FQDN ? Coz i read somewhere it not work with Kube-proxy or service name with FQDN
