### ISSUE TITLE
cespare should update to v2.1.2

### ISSUE THREAD

**Issue by zishen** [kubernetes/kubernetes#105133]
**What happened:**

When imported and build with -buildmode=plugin or anything use dynamic link, go will throw

when dynamic linking, R15 is clobbered by a global variable access and is used here:
[cespare:54](https://github.com/cespare/xxhash/issues/54)

and this happened in go 1.17 and 1.17.1
![截图](https://user-images.githubusercontent.com/7522079/133923522-20686d19-3f04-424e-ba2d-cebacaca0338.PNG)

so, the sctive dependency component "cespare" should be update v2.1.2 or later.

**Environment:**
Kubernetes version (use kubectl version): 1.22 and 1.22.1 fail,
Cloud provider or hardware configuration:
OS (e.g: cat /etc/os-release): ubuntu 20.04.2
go：1.17, 1.17.1

**Anything else we need to know?:**

/sig Release

**Comment by pacoxu** [comment]
/remove-lifecycle rotten
#105142 is ready to review.
