### ISSUE TITLE
Investigate if DefaultMemoryThrottlingFactor should be set differently for Windows

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#105102]
https://github.com/kubernetes/kubernetes/blob/6a84310f8bc99aadb8019976c34a704d8d1f9b73/pkg/kubelet/apis/config/v1beta1/defaults.go#L41 sets DefaultMemoryThrottlingFactor to 0.8. 
We should investigate if this value should be set different for windows.

/sig windows
/area kubelet

**Comment by SergeyKanzhelev** [comment]
Sorry for confusion, I meant the default for cert directory
