### ISSUE TITLE
openapi schema indicates incorrect return types for delete and deletecollection operations

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#105104]
1. Many (most?) types do not specify ReturnDeletedObject in their storage configuration
2. For those types, the generated schema specifies `v1.Status` as the return type for deleting a single item and collection of items
3. The actual behavior of deleting a single item :
   * Deleting a job with `propagationPolicy=Orphan`, `propagationPolicy=Foreground`, or  no `propagationPolicy` (which defaults to orphan) returns `Job`
   * Deleting a job with `propagationPolicy=Background` returns `Status`
   * Deleting a validationwebhook with `propagationPolicy=Orphan` or `propagationPolicy=Foreground` return `ValidatingWebhookConfiguration`
   * Deleting a validationwebhook with `propagationPolicy=Background` or no `propagationPolicy` (which defaults to background) returns `Status`
4. The actual behavior of deleting a collection of items:
   * Deleting a collection of jobs returns `JobList` in all cases
   * Deleting a collection of validating webhooks returns `ValidatingWebhookConfigurationList` in all cases

So, for objects which do not set `ReturnDeletedObject: true`, the generated schema is incorrect in some cases for the single-item delete, and incorrect in all cases for the collection delete.

However, if we change to set `ReturnDeletedObject: true` for all objects, we will start returning objects in some cases where we previous returned Status, and will break clients successfully using those deletion paths that could not handle an object return.

Since all clients have to be able to handle Status in all cases (since it can be returned for forbidden errors, not found errors, etc), I think the safest thing to do is to make schema generation stop paying attention to `ReturnDeletedObject` and have it indicate the object can be a potential return value for single-item and collection deletion.

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/93477#issuecomment-921949090_

**Comment by luyou86** [comment]
@liggitt 
is only to modify api/openapi-spec/swagger.json doc?

**Comment by luyou86** [comment]
```
"200": {
            "description": "OK",
            "schema": {
              "oneOf": [
                {"$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Status"},
                {"$ref": "#/definitions/io.k8s.api.batch.v1.Job"}
              ]
            }
          }
```

modify like this, is ok? but swagger 2.0 not support "oneOf"

**Comment by liggitt** [comment]
I don't see a way to make the schema correct, since a 200 can return either a Status or Job, depending on delete options specified... if we had to pick just one, I *think* I'd pick the specific object type, not status, since clients have to be generally prepared to receive a status object from any operation on any endpoint
