### ISSUE TITLE
Large label value for the metric `kubelet_started_pods_errors_total` with label `message` when there is a error

### ISSUE THREAD

**Issue by slashpai** [kubernetes/kubernetes#105163]
#### What happened:

While reviewing labels in prometheus noticed this metric `kubelet_started_pods_errors_total` whose label value is large (700+ characters) since it was a error log message.

Example:

```
kubelet_started_pods_errors_total{endpoint="https-metrics", instance="10.0.0.3:10250", job="kubelet", message="rpc error: code = Unknown desc = failed to create pod network sandbox k8s_cluster-image-registry-operator-6c786c84-svlhd_openshift-image-registry_eeb66cce-0b91-4c7d-870c-bf02234342cd_0(8381f96f82dd16971b009a09a3470a19766e316236e7337f194d5dcd5dc5e540): error adding pod openshift-image-registry_cluster-image-registry-operator-6c786c84-svlhd to CNI network "multus-cni-network": Multus: [openshift-image-registry/cluster-image-registry-operator-6c786c84-svlhd]: error getting pod: Get "https://[api-int.ci-ln-121bc45-f76d1.origin-ci-int-gce.dev.openshift.com]:6443/api/v1/namespaces/openshift-image-registry/pods/cluster-image-registry-operator-6c786c84-svlhd?timeout=1m0s": dial tcp 10.0.0.2:6443: connect: connection refused", metrics_path="/metrics", namespace="kube-system", node="ci-ln-121bc45-f76d1-qg7xx-master-2", service="kubelet"}
```

The metric is from [kubelet code block](https://github.com/kubernetes/kubernetes/blob/v1.22.0-rc.0/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L813)

#### What you expected to happen:

 It doesn't look like we should have error/ log message as a metric

#### How to reproduce it (as minimally and precisely as possible):

Query the metric `kubelet_started_pods_errors_total` in prometheus UI or through api where kubelet is one of the target in prometheus

#### Environment:
- Kubernetes version (use `kubectl version`): v1.22.0-rc.0
- Cloud provider or hardware configuration: NA
- OS (e.g: `cat /etc/os-release`): NA
- Kernel (e.g. `uname -a`): NA
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

cc: @dgrisonnet

**Comment by dgrisonnet** [comment]
I agree that error logs should never be part of metrics, it is not the correct vector to convey this kind of information. Logging would be more appropriated here.

/sig instrumentation
/sig node

/cc @ehashman

**Comment by yxxhero** [comment]
@ehashman @dgrisonnet 
I want to work on this.
/assign
