### ISSUE TITLE
Parameterize CronJob by scheduled time

### ISSUE THREAD

**Issue by ashwin153** [kubernetes/kubernetes#105183]
#### What would you like to be added:

A way to parameterize a CronJob by the time that the instance was scheduled to start.

#### Why is this needed:

I have a data pipeline that I would like to schedule on Kubernetes; however, the pipeline is parameterized by the scheduled time. It uses this timestamp to read from data sources, so it is important that this timestamp exactly matches the schedule (e.g., if it is scheduled at `CRON_TZ=UTC 0 8 * * *`, then the job must be run with `--now=2021-01-01T08-00-00` when it runs for `2021-01-01`). This is also useful for ensuring that the job is run with a consistent timestamp across executions (e.g., if the job fails and needs to be rerun). Other scheduling systems that I've used in the past expose this as a `FOR_TIME` environment variable which can then be used to parameterize the scheduled command.

**Comment by pacoxu** [comment]
Create a run-once cronjob to run on a specific date to create a new cronjob.
😄 
/sig apps

**Comment by sftim** [comment]
This sounds like a case for a new controller, beyond what CronJob is capable of. The new controller could manage Jobs that set all the environment variables and / or command line options that you want it to.
