### ISSUE TITLE
CPUManager releases CPUs of init containers while they are being reused in app containers

### ISSUE THREAD

**Issue by eggiter** [kubernetes/kubernetes#105114]
#### What happened:
+ CPUManager releases CPUs of init containers while they are being reused in app containers.

#### What you expected to happen:
+ Certainly kubelet should not release any of CPUs which are being used in containers.

#### How to reproduce it (as minimally and precisely as possible):
+ Start kubelet using static policy.
+ Create a pod with 1 init container(request 4cpu) and 1 app container(request 2cpu).
+ After pod started(Running), we can see 2 CPUs used by app container are inherited from init container which is fine.
+ Then manually remove init container, you will see the CPUs once used by init container  are all released even though some of them are being reused in app container. 

#### Anything else we need to know?:
- It seems this was introduced in PR #90419.

#### Environment:
- Kubernetes version (use `kubectl version`):
  + v1.17.4

#### Others:
- This issue is fixed by #104837.

**Comment by eggiter** [comment]
/sig node
cc @fromanirh

**Comment by fromanirh** [comment]
thanks for filing this bug. The scenario lacks a key information: which kind of flows trigger the removal of the init container?
AFAIU, the kubernetes GC can trigger the removal, then this bug. There is any other flow? For example, which other flow do trigger an explicit container removal?

In other words, we would like to have sufficient information to write a e2e test to cover this case (now or in the near future).

**Comment by eggiter** [comment]
> There is any other flow?

No, there is not other flow that can tigger this removal AFAIK.

**Comment by eggiter** [comment]
- Since there is no other flow can tigger the removal of completed init containers, will this be a waste of CPUs for those who were assigned to these completed init containers? These CPUs can not be assigned to other Pods as long as the Pods which the completed init containers belong to are not completed.
- Well, this is another story which is little relevant with the current issue.

**Comment by fromanirh** [comment]
So, I think we have indeed a bug here, question is how easy is to trigger. I think it's worthy to explore if kubelet's GC can trigger this flow. I can think either of any other flow that could possibly trigger this bug (reason: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images). I'm exploring GC settings to asses the impacts.

**Comment by eggiter** [comment]
> I can think either of any other flow that could possibly trigger this bug

Yes, i concur.

> I'm exploring GC settings to asses the impacts.

Great. 👍

**Comment by eggiter** [comment]
@fromanirh Hi, what's the current status?
