### ISSUE TITLE
Facilitate generation of configs for common scenarios

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#10527]
Item 17 in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cli-roadmap.md.

Would go well with "edit" functionality #8263.

We could tag (as in Go field tags) commonly used fields with example values or somesuch.

**Comment by bgrant0607** [comment]
See also #10495

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by bgrant0607** [comment]
I don't think more of this type of functionality will land in kubectl
