### ISSUE TITLE
Kubectl flag normalization setup looks like a merge error

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#105244]
staging/src/k8s.io/kubectl/pkg/cmd/cmd.go:

```
    flags := cmds.PersistentFlags()    
    flags.SetNormalizeFunc(cliflag.WarnWordSepNormalizeFunc) // Warn for "_" flags     
    
    // Normalize all flags that are coming from other packages or pre-configurations     
    // a var flags *pflag.FlagSet ". e.g. glog package     
    flags.SetNormalizeFunc(cliflag.WordSepNormalizeFunc)  
```

Am I missing something?  The second call to `SetNormalizeFunc` obliterates the first one.

cc @pohly

**Comment by olivercodes** [comment]
@thockin - Looks like yes, and the WordSepNormalizeFunc and WarnWordSepNormalizeFunc do the same thing (just one also generates the warning).

https://pkg.go.dev/k8s.io/Kubernetes@v1.4.2/pkg/util/flag#WarnWordSepNormalizeFunc
![image](https://user-images.githubusercontent.com/6577282/134790770-b5e0f005-8748-4e24-896b-a28c595e3449.png)

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/4d78db54a58e250b049c4fe17ac484e5c3ec662d/staging/src/k8s.io/kubectl/pkg/cmd/cmd.go#L259-L289

L289 set `WarnWordSepNormalizeFunc` as GlobalNormalizationFunc just below. 
L260 should be duplicated and overwritten. I think this line can be removed.

**Comment by olivercodes** [comment]
Seems like a good first issue, mind if I?

**Comment by pohly** [comment]
Please don't submit a PR for this.

I have a fix for it already in https://github.com/kubernetes/kubernetes/pull/105076. Merging some other PR will just lead to conflicts.

/assign
