### ISSUE TITLE
fix: use scale.Status.Replicas to get the target's current scale

### ISSUE THREAD

**Issue by aburlutskiy** [kubernetes/kubernetes#105231]
https://github.com/kubernetes/kubernetes/blob/7bff8adaf683dc7e25b5548e2c16e7393ff8a036/pkg/controller/podautoscaler/horizontal.go#L617

Is it possible to use `scale.Status.Replicas` instead of `scale.Spec.Replicas`? Right now HPA doesn't wait till the target spins up enough pods for that.

**Comment by aburlutskiy** [comment]
sig/autoscaling

**Comment by cyclinder** [comment]
why use scale.Spec.Replicas instead of scale.Status.Replicas get currentReplicas?

**Comment by AlpherJang** [comment]
> why use scale.Spec.Replicas instead of scale.Status.Replicas get currentReplicas?

scale.Spec.Replicas means how many Replicas need, Status.Replicas means how many Replicas now
