### ISSUE TITLE
Bind api will bind unexpected pod to node in some situation

### ISSUE THREAD

**Issue by aholic** [kubernetes/kubernetes#105261]
#### What happened:
The api `CoreV1().Pods(...).Bind(ctx context.Context, binding *v1.Binding, opts metav1.CreateOptions)` bind a pod to a node. But the pod is specified by name (not uid), which is not a unique identifier for pod. So the caller of `Bind` can't make sure the pod is exactly what he want.

#### What you expected to happen:
`Bind` api can bind a pod with specified uid to a node. If the uid not match, return an error

#### How to reproduce it (as minimally and precisely as possible):
1. Create a pending pod by statefulset named busybox, make sure it's pending, the scheduler will not bind it(use non-existed node selector or other method). So we will get a pending pod busybox-0.
2. run following code
```
client, err := kubernetes.NewForConfig(cfg)
if err != nil {
	klog.Fatalf("NewForConfig err: %s", err)
	return
}

pod, err := client.CoreV1().Pods("default").Get(context.TODO(), "busybox-0", v1.GetOptions{})
if err != nil {
	klog.Fatalf("get pod: %s", err)
}

time.Sleep(30 * time.Second)     // !!!! notice here

err = client.CoreV1().Pods(pod.Namespace).Bind(context.TODO(), &corev1.Binding{
	ObjectMeta: v1.ObjectMeta {
		Namespace: pod.Namespace,
		Name: pod.Name,
		UID: pod.UID,
	},
	Target: corev1.ObjectReference{
		Kind:       "Node",
		Name:       "some-node",
	},
}, v1.CreateOptions{})  //
```
3. Notice the `time.Sleep` in the code, delete the pod busybox-0 manually during the sleep（`kubectl delete pod busybox-0` or other method）. The statefulset busybox will create another pod busybox-0 with different uid
4. Finally, the `Bind` api in the code above will bind an unexpected pod to node

#### Anything else we need to know?:
The logic in scheduler is the same. If the pod is recreate with the same name and different resource require or selector between scheduler's `Get` and `Bind`, scheduler will do a wrong bind for the pod. I think the root cause is the `Bind` api does not check the uid.

#### Environment:
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.0-alpha.3", GitCommit:"6d3ccd8e6c409a8524145b38517637218cf4b228", GitTreeState:"clean", BuildDate:"2020-10-20T09:01:41Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyunedge.1", GitCommit:"687f4f4", GitTreeState:"", BuildDate:"2021-03-08T09:56:01Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by pacoxu** [comment]
/sig scheduling
for triage (the binding feature of (pod to node) is for scheduling).

**Comment by ahg-g** [comment]
For the sake of precedence, are there other APIs that are based on object UID?

**Comment by liggitt** [comment]
uids are used as a precondition is used in many places. if the server started checking that a uid on the binding object (if specified) matched the uid of the pod being modified, that seems sufficient

**Comment by aholic** [comment]
> uids are used as a precondition is used in many places. if the server started checking that a uid on the binding object (if specified) matched the uid of the pod being modified, that seems sufficient

is there any way to confirm the caller of Bind is binding the right pod? or not uid, use resource version?

**Comment by liggitt** [comment]
> is there any way for the caller of Bind to confirm that he is binding the right pod? or not uid, use resource version?

that would require:
* the server to check that bind UID (if specified) matches the pod UID (passing the binding uid from BindingREST#Create → assignPod → setPodHostAndAnnotations and verifying the uid match in setPodHostAndAnnotations)
* the binding API caller to set metadata.uid in the posted binding object (as illustrated in the description of this issue)

**Comment by aholic** [comment]
> > is there any way for the caller of Bind to confirm that he is binding the right pod? or not uid, use resource version?
> 
> that would require:
> 
> * the server to check that bind UID (if specified) matches the pod UID (passing the binding uid from BindingREST#Create → assignPod → setPodHostAndAnnotations and verifying the uid match in setPodHostAndAnnotations)
> * the binding API caller to set metadata.uid in the posted binding object (as illustrated in the description of this issue)

+ actually, kube-scheduler(the most common binding API caller) has set the metadata.uid in the posted binding object. https://github.com/kubernetes/kubernetes/blob/b290671b1b28ab4af8164e2b69b334fab584558e/pkg/scheduler/scheduler.go#L471
+ but the server doesn't check the uid.

in my program, i do those to work around(not elegant, but it works...):
+ call the binding API with an uid in annotation(i found that BindingREST#Create → assignPod → setPodHostAndAnnotations will carry annotation).
+ check the metadata.uid matchs annotation.uid, if not match, delete the pod and wait for an new pod ... 

from your point of view, is it necessary to ensure the pod is the caller want when someone call bind API?  what's your advice for this issue？

**Comment by liggitt** [comment]
> from your point of view, is it necessary to ensure the pod is the caller want when someone call bind API?

given the scheduler made decisions based on the current shape of the pod spec, I think it makes sense for it to work to make sure it is binding that instance of the pod

> what's your advice for this issue？

I would advocate for supporting uid as a precondition in the binding API and starting to use it from the scheduler

**Comment by aholic** [comment]
> advocate

agree with you

**Comment by aholic** [comment]
> > from your point of view, is it necessary to ensure the pod is the caller want when someone call bind API?
> 
> given the scheduler made decisions based on the current shape of the pod spec, I think it makes sense for it to work to make sure it is binding that instance of the pod
> 
> > what's your advice for this issue？
> 
> I would advocate for supporting uid as a precondition in the binding API and starting to use it from the scheduler

i agree with you
