### ISSUE TITLE
failed to get calico-node daemonsets.apps in kube-system namespace

### ISSUE THREAD

**Issue by king-jingxiang** [kubernetes/kubernetes#105260]
#### Which test(s) are failing:

![image](https://user-images.githubusercontent.com/32818529/134834592-08cbca13-5612-449a-97e3-a244a59e7138.png)

#### Reason for failure:

[Install Calico ](https://docs.projectcalico.org/getting-started/kubernetes/quickstart) can't set namespace
```
# kubectl logs ks-controller-manager-586f44fb5b-mt2vv -nkubesphere-system
F0926 21:45:52.982421       1 provider.go:667] failed to get calico-node deployment in kube-system, err=daemonsets.apps "calico-node" not found
#  kubectl get ns
NAME                              STATUS   AGE
calico-apiserver                  Active   4d16h
calico-system                     Active   4d16h
default                           Active   4d16h
......
kubesphere-system                 Active   4d16h
tigera-operator                   Active   4d16h
[root@vmi-08 ~]# kubectl get ds -ncalico-system
NAME          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
calico-node   1         1         0       1            0           kubernetes.io/os=linux   4d16h
```
```
pkg/simple/client/network/ippool/calico/provider.go:77
CalicoNodeNamespace          = "kube-system"
```
#### Anything else we need to know:

Looking forward to adding this `CalicoNodeNamespace` parameter to clusterconfigurations.installer.kubesphere.io network.

#### Relevant SIG

/sig

**Comment by pacoxu** [comment]
This seems to be `kubesphere` bug in its controller-manager.  You may open issue in https://github.com/kubesphere/kubesphere/issues.
/remove-kind failing-test
/close

**Comment by king-jingxiang** [comment]
Sorry, I found the wrong project.
