### ISSUE TITLE
dockershim tear down network after stop sandbox container when StopPodSandbox 

### ISSUE THREAD

**Issue by gojoy** [kubernetes/kubernetes#105225]
Now dockershim tear down network firstly when StopPodSandbox, if the pod ip has been released in ipam successful but the sandbox container stopped failed, in this situation the sandbox container was still using the ip which has released in ipam, this will cause pod ip conflict when ipam allocating the ip to a new pod.
should dockershim  tear down network after stop sandbox container when StopPodSandbox?

**Comment by SergeyKanzhelev** [comment]
What k8s version? What is the reason for `StopPodSandbox`  to fail in your situation?

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue, as @SergeyKanzhelev has requested above: https://github.com/kubernetes/kubernetes/issues/105225#issuecomment-928316916

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by gojoy** [comment]
the k8s vision is 1.16.4. I have do more investigate after open this issue, and It was caused by cni plugin [#666](https://github.com/containernetworking/plugins/issues/666)
because releasing ip and cleaning network device is in the scope of cni.
Thanks for attention
