### ISSUE TITLE
where is  ErrCodeUnreachable error generated?

### ISSUE THREAD

**Issue by rootdeep** [kubernetes/kubernetes#105259]
I follow the process code  aboud  creating operation in k8s apiserver. When a create operation fails,  the code will process error, the releated code is 

![image](https://user-images.githubusercontent.com/28667591/134808349-bc5772fd-5ae0-456c-ae80-9e85c9c49428.png)

https://github.com/kubernetes/kubernetes/blob/v1.18.4/staging/src/k8s.io/apiserver/pkg/storage/errors/storage.go#L57 

I also read the code where the error is thrown 
https://github.com/kubernetes/kubernetes/blob/v1.18.4/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L172

But I don't find a place where an Unreachable error is build. The error type is StorageError and 
code is  ErrCodeUnreachable. (Refer https://github.com/kubernetes/kubernetes/blob/v1.18.4/staging/src/k8s.io/apiserver/pkg/storage/errors.go#L124 )

Could someone explain where the unreachable storage error throws. Thanks very much.

**Comment by MadhavJivrajani** [comment]
Hi @rootdeep, could you please bring this up on our [slack](https://slack.k8s.io) channel (specifically the `#sig-storage` channel)?
/kind support
/close
