### ISSUE TITLE
Tuning the number of domains in PodTopologySpread

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#105291]
#### What would you like to be added:

A parameter to pod topology spread constraints to tune the min and max number of domains over which the spread will occur.

PodTopologySpread includes a `skew` parameter which controls the difference between domains, but there is no knob to control the number of domains over which we should spread, I feel this should be part of a spreading API.

In practice, currently PodTopologySpread assumes a value of 1, see https://github.com/kubernetes/kubernetes/issues/105072. For example, if the cluster contains a single node, even if one uses `whenUnsatisfiable: DoNotSchedule`, then all pods will be scheduled on that single node because there is no other node to compute a skew against. 

In the scenario above, if we have a `minDomain` parameter and we set it to 4, then the first pod will be scheduled on the available node, but the next three will be marked pending, which will force CA to bring up three more nodes if configured. 

#### Why is this needed:

Use case 1: I am using cluster autoscaler and I want to use `whenUnsatisfiable: DoNotSchedule` to force spreading a deployment over a minimum number of nodes or zones.
Use case 2: I am using preferred topology spread, I have a large cluster, but I don't want to spread the service over many nodes, I prefer to spread it over at most 4 before spreading to other nodes.

/sig scheduling

**Comment by alculquicondor** [comment]
I like that this would allow scale ups without having to declare all the topologies.

What are the detailed semantics? Both `minDomains` and `maxDomains` are usable with preferred and required semantics, right?

For use case 1: While number of pods is less than `minDomains`, pods behave as if they would have antiaffinity.

For use case 2: When number of pods is greater than `maxDomains`, nodes without matching pods get filtered out (or 0 score).

Did I get that right?

**Comment by ahg-g** [comment]
> For use case 1: While number of pods is less than minDomains, pods behave as if they would have antiaffinity.
> For use case 2: When number of pods is greater than maxDomains, nodes without matching pods get filtered out (or 0 score).

Exactly for both cases. We may want to caution against using `maxDomain` with  `DoNotSchedule` and node topology since a node can't be "scaled up".

**Comment by sanposhiho** [comment]
created:
- Issue: https://github.com/kubernetes/enhancements/issues/3022
- KEP PR: https://github.com/kubernetes/enhancements/pull/3030

**Comment by Huang-Wei** [comment]
`minDomains` sounds like a reasonable requirement. But the motivation and semantics of `maxDomains` looks confusing, is there a concrete example?

In terms of DoNotSchedule mode, it's proposed to abstract `maxDomains` as an extra (dynamic) filter on top of nodeSelector/nodeAffinity for the "search space". This concerns me because once the pods are spread onto the number of so-called `maxDomains`, we can only schedule further pods onto the existing domains - this sounds pretty restricted. In terms of resource shortage, we have to do preemption by evicting ALL pods scheduled on one domain. Spinning up a new node doesn't quite help either.

**Comment by sanposhiho** [comment]
In terms of `maxDomains` and `ScheduleAnyway`, we can address use cases like `Use case 2` on the issue description.

Users need to be careful when they use `maxDomains` with `DoNotSchedule`. (and especially with topology of node, as @ahg-g said.) It will be kind to add a note for it on documentations.

**Comment by alculquicondor** [comment]
I think the API is clear in what it's behavior would be with `DoNotSchedule`. But maybe the use case is not strong enough. People can use node affinity to limit the spread instead.

Should we focus on `minDomains` for 1.24?

**Comment by ahg-g** [comment]
Node affinity will be tricky to setup because for the most part it is a static configuration, but I think starting with `minDomains` is probably good enough.

**Comment by Huang-Wei** [comment]
+1 to start with `minDomains` and consider `maxDomains` when there is a practical requirement (in particular combined with DoNotSchedule).

**Comment by krmayankk** [comment]
Has this been released ?

**Comment by alculquicondor** [comment]
This is currently in beta kubernetes/enhancements#3022

/close
