### ISSUE TITLE
Kubelet should support --register-with-taints within KubeletConfiguration

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#105298]
#### What happened:
Many config options were migrated to the KubeletConfiguration, but --register-with-taints was missed. A user might want to register their node with taints based on the yaml config file instead of passing on the command line.

This issue is to track supporting RegisterWithTaints within the KubeletConfiguration structure and preserving the behavior of --register-with-taints.

#### What you expected to happen:
I would expect the --register-with-taints option to be present in the KubeletConfiguration resource.

#### Environment:
- Kubernetes version (use `kubectl version`): 1.22+
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by cmssczy** [comment]
I want to work on it.
/assign

**Comment by cmssczy** [comment]
hi, I'm trying to add `RegisterWithTaints` in this struct.
```go
type KubeletConfiguration struct {
  // ...
  RegisterWithTaints []string
  // ...
}
```
But When I build a release (`make quick-release-images`),  it always failed with the logs as follow. 
```shell
E0929 15:12:25.614113    2234 conversion.go:755] Warning: could not find nor generate a final Conversion function for k8s.io/kubernetes/pkg/kubelet/apis/config.KubeletConfiguration -> k8s.io/kubelet/config/v1beta1.KubeletConfiguration
E0929 15:12:25.616113    2234 conversion.go:756]   the following fields need manual conversion:
E0929 15:12:25.616142    2234 conversion.go:758]       - RegisterWithTaints
Generating openapi code for KUBE
388d387
< API rule violation: list_type_missing,k8s.io/kubelet/config/v1beta1,KubeletConfiguration,RegisterWithTaints
ERROR:
	 KUBE API rule check failed. Reported violations differ from known violations. Please read api/api-rules/README.md to resolve the failure in api/api-rules/violation_exceptions.list.

make[1]: *** [Makefile.generated_files:625: pkg/generated/openapi/zz_generated.openapi.go] Error 1
make: *** [Makefile:552: generated_files] Error 2
!!! [0929 15:12:36] Call tree:
!!! [0929 15:12:36]  1: build/../build/common.sh:476 kube::build::run_build_command_ex(...)
!!! [0929 15:12:36]  2: build/release-images.sh:40 kube::build::run_build_command(...)
```
This is my first time to modify the code related to api change. I tried to search how to fix this problem but did not find sth useful. So could someone give me some hint? Thanks a lot.

@rphillips @ehashman

**Comment by cmssczy** [comment]
I think this issue could be closed because the related pr has been merged.
/close
