### ISSUE TITLE
Pod Service IP not able to ping from outside the cluster

### ISSUE THREAD

**Issue by bobymark** [kubernetes/kubernetes#105210]
Hi everyone,
I have a K8s setup, when I ping the pod service IP, there is response like below.

_Request timeout for icmp_seq 1
92 bytes from 10.20.60.15: Redirect Host(New addr: 10.20.60.103)
Vr HL TOS Len ID Flg off TTL Pro cks Src Dst
4 5 00 0054 5d0d 0 0000 3f 01 ba9e 10.20.19.111 10.20.60.103

But at the same time, I am able to ssh and also take it remote access via XRDP. I am using MetalLB for load balancing. This config is running for a year with K8s v1.19*. Can some one help me fix that ping issue.

Thanks in advance.
Mark.

**Comment by neolit123** [comment]
for similar questions it is better to ask on the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
