### ISSUE TITLE
Server code that glog.Errorfs or eats errors should use util.HandleError

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#10521]
util.HandleError is the default "eat this error, log it, or report it to some other system as an unexpected error" handler.  We should use it in server code (and rarely, user interface code) when we would otherwise eat an error.  There is a forthcoming integration to report these errors to Sentry or other error systems (or as events).

**Comment by smarterclayton** [comment]
I need to add a linter for this.

**Comment by falenn** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  curtis.l.bates@gmail.com
    Domain imwiz.com has exceeded the max emails per hour (181/150 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o11.sgmail.github.com ([167.89.101.202]:50661)
	by box969.bluehost.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-5c7e-dev=imwiz.com@sgmail.github.com>)
	id 1dGU90-000Qwp-Hu
	for dev@imwiz.com; Thu, 01 Jun 2017 11:44:22 -0600
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=dppQLyKrivlcndPlJqp2D86qa+s=; b=O3mAGrHglUKR4XXi
	G4qoaOh2R4VVjvWAhg07ra5Nf5zv2ylxprtWBQnANQz5rzPeP8ydJXoPTzgAF2PG
	0dccdLLqAOKBgBEETpH0Y12ZY4tsoUt3KuFka3+D2DTmMFvXbYaD08gtzt5bJJ4g
	uUSFMTDN1xBhavKr7AL+vTtMlMM=
Received: by filter0934p1mdw1.sendgrid.net with SMTP id filter0934p1mdw1-19977-5930526B-25
        2017-06-01 17:44:11.696087003 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id CudCusSIQReeVAeREobfhQ
	for <dev@imwiz.com>; Thu, 01 Jun 2017 17:44:11.680 +0000 (UTC)
Date: Thu, 01 Jun 2017 10:44:11 -0700
