### ISSUE TITLE
Downward API doesn't support status.podIPs to be used

### ISSUE THREAD

**Issue by hanamantagoudvk** [kubernetes/kubernetes#105203]
Hi ,

I am trying to use downward API in daemonset spec to set `IP ` and `IP6` environment variables using the pod's status.podIPs array.

>       env:
>         - name: IP
>   	  valueFrom:
>             fieldRef:
>               fieldPath: status.podIPs[0].ip
>         - name: IP6
>   	  valueFrom:
>             fieldRef:
>               fieldPath: status.podIPs[1].ip	

But it throws error as shown below. 

>  spec.template.spec.containers[0].env[7].valueFrom.fieldRef.fieldPath: Invalid value: "status.podIPs[0]": error converting fieldPath: field label not supported: status.podIPs[0]
>  spec.template.spec.containers[0].env[12].valueFrom.fieldRef.fieldPath: Invalid value: "status.podIPs[1]": error converting fieldPath: field label not supported: status.podIPs[1]
>  spec.template.spec.containers[0].env[7].valueFrom.fieldRef.fieldPath: Invalid value: "status.podIPs[0]": error converting fieldPath: field label not supported: status.podIPs[0]
> spec.template.spec.containers[0].env[12].valueFrom.fieldRef.fieldPath: Invalid value: "status.podIPs[1]": error converting fieldPath: field label not supported: status.podIPs[1]

Whether downward API could be enhanced to support accessing status.podIPs[0] or status.podIPs[1] ?
With dual-stack feature implemented , this makes a case for accessing both values.

**Comment by pacoxu** [comment]
```
      - name: POD_IPS
        valueFrom:
          fieldRef: 
            fieldPath: status.podIPs
```
This is supported since https://github.com/kubernetes/kubernetes/pull/83123 v1.17+.

**Comment by hanamantagoudvk** [comment]
@pacoxu , with dual-stack feature coming into picture , we should have flexibility to choose a particular IP family address from `status.podIPs`

**Comment by pacoxu** [comment]
> @pacoxu , with dual-stack feature coming into picture , we should have flexibility to choose a particular IP family address from `status.podIPs`

But Pod is not always dual-stack. And `status.podIPs[0]` is not always IPv4. Even when we enable Dual-Stack, there can be Pod with IPv6 IP only.

**Comment by aojea** [comment]
> But Pod is not always dual-stack. And `status.podIPs[0]` is not always IPv4. Even when we enable Dual-Stack, there can be Pod with IPv6 IP only.

Agree, I can't see how this can be generalized, IPs are exposed, can't the client parse them directly?
It will have to do it somehow to support all clusters as @pacoxu commented, in single stack clusters podIPs[1] will nto exist

**Comment by hanamantagoudvk** [comment]
> But Pod is not always dual-stack. And `status.podIPs[0]` is not always IPv4. Even when we enable Dual-Stack, there can be Pod with IPv6 IP only.

Yes i understand pod need not have dual-stack IPs always. I also understand , order within `status.podIPs` array also varies.
But we can leave it to user to appropriately use the` status.podIPs` array values.

Let me explain my usecase in detail.

In calico-node daemonset manifest , i want to set the calico node addresses using downward api values. Checking the appropriate IP family and order of IPs in `status.podIPs` is done outside using a script. Then we appropriately set the values from `status.podIPs` to `IP `or `IP6`.

More background about calico issue can be found here https://github.com/projectcalico/calico/issues/4870

**Comment by hanamantagoudvk** [comment]
> Agree, I can't see how this can be generalized, IPs are exposed, can't the client parse them directly?
> It will have to do it somehow to support all clusters as @pacoxu commented, in single stack clusters podIPs[1] will not exist

@aojea , as i explained above i am trying to use the `status.podIPs` in daemonset manifest. So i can't extract exact values and set it. The very reason to use downward api is to have generic way of setting the IPs.

**Comment by aojea** [comment]
> @aojea , as i explained above i am trying to use the `status.podIPs` in daemonset manifest. So i can't extract exact values and set it. The very reason to use downward api is to have generic way of setting the IPs.

yeah, but the request is very specific for your use case , we should try to generalize ... 
and if calico pluralizes the autodetection environment variable cc: @caseydavenport to match Kubernetes API?
```
IPS_AUTODETECT_METHOD
```

**Comment by dcbw** [comment]
What's the problem with having all the IPs in a single environment variable and extracting them into individual values as needed in the container's startup script?

**Comment by hanamantagoudvk** [comment]
> What's the problem with having all the IPs in a single environment variable and extracting them into individual values as needed in the container's startup script?

There is no problem. As explained above, i was just trying to set the calico `IP `and `IP6 `env variable with appropriate addresses from status.podIPs array using downward API.

**Comment by khenidak** [comment]
/close
if you believe that we need to talk more about this, then please re-open.

**Comment by xaque208** [comment]
Is there a workaround or fix for this?  It seems like we should be able to reference the array index of `status.podIPs` to use in environment variables.

**Comment by sixletters** [comment]
Is there any update on this, seems like it does not make sense that we are able to reference annotations and labels by key but cant do the same for the status.podIPs array.
