### ISSUE TITLE
Reduce watchcache contention caused by expensive watches

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#105274]
This is follow up from https://github.com/kubernetes/kubernetes/issues/73958

The main goal is to reduce the lock contention cause by GetAllEventsSinceThreadUnsafe [which may potentially allocate and copy a lot of data]

The idea of how we can solve it is the following:
1) We introduce a concept of watchCacheInterval, sth like:
```
type watchCacheInterval struct {
  startIndex int
  endIndex int
  lock sync.Mutex
  valid bool
}
```

2) GetAllEventsSinceThreadUnsafe instead of copying all data actually returns just appropriately filled in interval

3) in watchcache, we're tracking all returned intervals in some tree-like structure [this means that at the end callers to GetAllEventsSinceThreadUnsafe has to explicitly release it]

4) The interval exposes Next() method giving the next item and this is the only way to get the actual items

5) Next() internally:
  - takes a lock, checks if interval is still valid and if so returns the next item from the interval [it pushes startIndex at the same time]
  - lock effectively protects only `valid` field
  - we may optimize further by having a small buffer (say 8 or 16 items in it) and read the whole portion to the buffer [if we do so, we may consider having sync.Pool of intervals, given we need to control their lifetime anyway]

6) When we push "startIndex" in the watchCache itself - we simply look if there are any intervals that use it [we know if efficiently from the tree mentioned above sorted by startInex] and if so invalidate all of these

The implementation of the above should be fairly straightforwards (though good unit tests will be needed)

@kubernetes/sig-scalability 

/kind priority-backlog
/sig scalability
/kind feature

/help wanted

**Comment by wojtek-t** [comment]
Actually - I forgot to write one more important thing.
The reason why I propose the solution above (as opposed to others - there was a different approach proposed in https://github.com/kubernetes/kubernetes/pull/76904 ) is that it addresses also a long-standing reliability issue.

Namely - the problem is that "initEvents" are currently unbounded. So if many watches are starting at the same time, and kube-apiserver is heavily throttled, we may end-up with a large number of watches, each of them consuming theoretically unbounded memory (well - bounded by the size of watchcache, but that can be huge).
With this PR, we're explicitly bounding the memory used by "initEvents" - which is a huge gain.


@MadhavJivrajani - I'm glad to see you self-assigned. Let me know if you have any questions and I'm looking forward to see a first version of the PR (feel free to send some draft first so that we can discuss that before figuring out all tests etc.)

**Comment by MadhavJivrajani** [comment]
@wojtek-t i had a few initial questions to better understand what needs to be done:

- The intent here is to reduce the time spent for the case where `resourceVersion == 0`, since that is the place we effectively list all events currently existing in the underlying store and allocate a buffer for those and copy them over?
    - The lock contention is an issue because of this excessive time spent in allocation and copying over data
    - Should the case for `resourceVersion != 0` should remain as is or should this PR optimize that as well?

> in watchcache, we're tracking all returned intervals in some tree-like structure [this means that at the end callers to GetAllEventsSinceThreadUnsafe has to explicitly release it]

Could you elaborate on the tree-like aspect of this?
Follow up: Are there existing utils present in api-machinery that provide for this that you know of or will we have to write our own?

> When we push "startIndex" in the watchCache itself

I'm not sure I understand what pushing `startIndex` in watchCache here would mean?

**Comment by wojtek-t** [comment]
> The intent here is to reduce the time spent for the case where resourceVersion == 0, since that is the place we effectively list all events currently existing in the underlying store and allocate a buffer for those and copy them over?

No. watch with RV=0 isn't widely used. The intent is to address any RV!=0 really. This is what matters.

> Could you elaborate on the tree-like aspect of this?

When I'm writing an event to a cyclic buffer I want to check if noone would like to read the current "startIndex":
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L339

So here I would like to find all intervals which include "startIndex" and invalidate that.

The way to do that is to have a structure that will have all intervals sorted by "startIndex". So some kind of tree.
We can probably do that easier - i.e. just with a heap, because we always just want to get the one with "smallest" startIndex.

> I'm not sure I understand what pushing startIndex in watchCache here would mean?

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L162
