### ISSUE TITLE
Plan for backporting Kube-proxy error logs fix to older K8s versions

### ISSUE THREAD

**Issue by kishoreakshat** [kubernetes/kubernetes#105262]
Thanks for taking a look on #105182 guys, really appreciate your help with this 😄 

I could see that the fix has been planned as part of v1.23 milestone.

Can you please clarify if this fix can/would be backported to previous Kubernetes versions and if there is a timeline for the same. This will help plan if we will continue to see such errors for some time now.

Thanks again, good day !

_Originally posted by @akshatki in https://github.com/kubernetes/kubernetes/issues/105182#issuecomment-926304444_

**Comment by dcbw** [comment]
Seems reasonable, just needs somebody to do the cherry-pick
/triage accepted
/assign khenidak
