### ISSUE TITLE
[Failing Job] post-kubernetes-push-image-etcd

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#105284]
#### Which jobs are failing:
- post-kubernetes-push-image-etcd

#### Which test(s) are failing:
n/a

#### Since when has it been failing:
2020-08-11

#### Testgrid link:
https://testgrid.k8s.io/sig-k8s-infra-gcb#post-kubernetes-push-image-etcd

#### Reason for failure:
```
docker buildx version
docker: 'buildx' is not a docker command.
See 'docker --help'
```

#### Anything else we need to know:
Started failing when https://github.com/kubernetes/kubernetes/pull/104116 merged

No new versions of etcd are getting pushed until this gets fixed, when means the following PRs haven't fully taken effect:
- https://github.com/kubernetes/kubernetes/pull/104116
- https://github.com/kubernetes/kubernetes/pull/104301
- https://github.com/kubernetes/kubernetes/pull/104368
- https://github.com/kubernetes/kubernetes/pull/103692
- https://github.com/kubernetes/kubernetes/pull/104904

#### Relevant SIG
/sig api-machinery

/priority critical-urgent
/milestone v1.23
/assign @saschagrunert @jpbetz 
FYI @kubernetes/release-engineering

**Comment by spiffxp** [comment]
I've opened https://github.com/kubernetes/kubernetes/pull/105285 to rollback the offending commit, would like to keep this open until we can figure out the correct fix-forward

**Comment by spiffxp** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1442594901840629760 was triggered by the merge of https://github.com/kubernetes/kubernetes/pull/105285, which pushed `gcr.io/k8s-staging-etcd/etcd:3.5.0-3`

So that's now current / includes whatever PRs linked in the description may have tried to change (excluding #104116)

**Comment by spiffxp** [comment]
@pacoxu does this need promotion at all or are we good with the existing `k8s.gcr.io/etcd:3.5.0-0` image?

**Comment by spiffxp** [comment]
/remove-priority critical-urgent
/priority important-soon
The job is back to passing

**Comment by pacoxu** [comment]
> @pacoxu does this need promotion at all or are we good with the existing `k8s.gcr.io/etcd:3.5.0-0` image?

Recent updates are related to Debian base image update and golang upgrade. 
Nice to get a promotion. Good enough to use  `k8s.gcr.io/etcd:3.5.0-0`.

**Comment by saschagrunert** [comment]
Yeah, looks like that the env in the build job does not include the `/root/.docker/cli-plugins/docker-buildx` path, which makes it unavailable during the run.

**Comment by saschagrunert** [comment]
I think we have to set the `$HOME` environment variable like we already do in other build jobs, proposing the fix in https://github.com/kubernetes/kubernetes/pull/105484

**Comment by saschagrunert** [comment]
Latest test run is green: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1445454283720888320
