### ISSUE TITLE
Kubelet memory regression 1.21 -> 1.22 (~30%)

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105294]
#### What happened:

Kubelet began consuming more memory in perf scale tests.

#### What you expected to happen:

Kubelet should use approx same amount of memory between releases.

#### How to reproduce it (as minimally and precisely as possible):

Observe the perf dashboards:

- 1.21 (~100MB): http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-1.21&metriccategoryname=E2E&metricname=LoadResources&PodName=e2e-big-minion-group%2Fkubelet&Resource=memory
- 1.22 (~125MB): http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-1.22&metriccategoryname=E2E&metricname=LoadResources&PodName=e2e-big-minion-group%2Fkubelet&Resource=memory

#### Anything else we need to know?:

It appears that CPU utilization went *down* from 1.21 to 1.22 on the same test runs, so perhaps this is related?

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

Masters, 1.21
![Screenshot at 2021-09-27 14-01-36](https://user-images.githubusercontent.com/4706131/134984859-d7742147-4538-4c9c-9850-3b9f08b4f316.png)

Masters, 1.22
![Screenshot at 2021-09-27 14-01-26](https://user-images.githubusercontent.com/4706131/134984863-9486ce18-7f53-4db6-aa27-58fca9245c08.png)

Workers, 1.21
![Screenshot at 2021-09-27 14-01-10](https://user-images.githubusercontent.com/4706131/134984866-64c60973-346a-405f-958b-412d85bc0a54.png)

Workers, 1.22
![Screenshot at 2021-09-27 14-01-17](https://user-images.githubusercontent.com/4706131/134984864-68a290fd-ccb9-4147-9c58-7ce4358e8e45.png)

/kind regression
/sig node

**Comment by pacoxu** [comment]
There seems to be no kubelet prof in [artifacts of the performance test](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-21/1426695355218530304/artifacts/). Or where can I get them?

**Comment by rphillips** [comment]
I bisected it down to https://github.com/kubernetes/kubernetes/pull/102323

**Comment by ehashman** [comment]
> There seems to be no kubelet memory prof file in [artifacts of the performance test](https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-1-21/1426695355218530304/artifacts/). Or where can I get them?

Might have been an oversight when the kubelet was added to the scale tests in ~1.20, you could add this to the k/perf-tests repo

**Comment by ehashman** [comment]
Post-merge:

![Screenshot at 2021-10-04 11-29-30](https://user-images.githubusercontent.com/4706131/135905015-6b4f4cf8-d9ea-42aa-8fee-97d14941c0f7.png)

No change yet on 1.22 branch, looks like we need to backport first.

**Comment by ehashman** [comment]
Backport has landed and memory consumption has returned to baseline :tada: 

/close
