### ISSUE TITLE
Flaky test case failure: RateLimiters test cases are failing due to time mismatch

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes/kubernetes#105311]
#### Which jobs are failing:

The unit test [TestWithMaxWaitRateLimiter](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/workqueue/default_rate_limiters_test.go#L202) which was recently added is flaking

#### Which test(s) are failing:

Sample failure error trace

```
=== FAIL: vendor/k8s.io/client-go/util/workqueue TestWithMaxWaitRateLimiter (0.10s)
    default_rate_limiters_test.go:202: expected 8m20s, got 8m19.997445973s

```
Full test report can be found [here](https://prow.ppc64le-cloud.org/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le/1442376696501112832)

#### Reason for failure:

The test is flaking because of the time mismatch in a condition and its observed that the while the control arrives [here](https://github.com/kubernetes/kubernetes/blob/f84ec6c0ebabfdf261ce84844bb884eab78d79cf/staging/src/k8s.io/client-go/util/workqueue/default_rate_limiters_test.go#L201) some times its few milliseconds(8m19.997445973s) lesser than the expected time(8m20s)

**Comment by pacoxu** [comment]
/sig api-machinery 
/kind flake
A flake according to the job history: https://prow.ppc64le-cloud.org/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le
