### ISSUE TITLE
client-go Client timeout configuration is ignored 

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#105324]
#### What happened:

When Timeout is 0 or nil, the behavior is the same and no timeout 

#### What you expected to happen:

```
if opts.TimeoutSeconds == nil 
   Use Client timeout configuration
else
   Use opts.TimeoutSeconds
```

#### Anything else we need to know?:

https://github.com/kubernetes/kubernetes/blob/950f655bdd19c5af275846cf1940d767a5ec0115/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod.go#L87-L102

https://github.com/kubernetes/kubernetes/blob/950f655bdd19c5af275846cf1940d767a5ec0115/staging/src/k8s.io/client-go/rest/request.go#L134-L147

https://github.com/kubernetes/kubernetes/blob/950f655bdd19c5af275846cf1940d767a5ec0115/staging/src/k8s.io/client-go/rest/request.go#L956-L960

https://github.com/kubernetes/kubernetes/blob/950f655bdd19c5af275846cf1940d767a5ec0115/staging/src/k8s.io/client-go/rest/request.go#L396-L404

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by wzshiming** [comment]
/cc @wojtek-t
Could you have time to take a look

**Comment by aojea** [comment]
Sorry for the question, but I can't understand what problem are you trying to solve :sweat_smile: 
Why do you need to places to set a timeout?
I think that you can pass a context with timeout per request

**Comment by wzshiming** [comment]
> Sorry for the question, but I can't understand what problem are you trying to solve 😅 Why do you need to places to set a timeout? I think that you can pass a context with timeout per request

I want to set the timeout time of par request uniformly, Passing the context of per request timeout can also be achieved, but in scenarios where there are many calls, it is more convenient to have a place to set a global timeout

Today I suddenly feel that adding more content is not big workload, and it is clearer, thank for your reminder
