### ISSUE TITLE
There are two very confusing package of code client-go's tools/events and tools/record

### ISSUE THREAD

**Issue by daniel-hutao** [kubernetes/kubernetes#105391]
#### What happened:

There are two very confusing package of code client-go's tools/events and tools/record.

"Package record has all client logic for recording and reporting" // record package's doc.go
"Package events has all client logic for recording and reporting" // events package's doc.go

All of them have `EventBroadcaster`/`EventSink`/`EventRecorder` …… implement, I analyzed the code logic, and found package record is used for k8s events logic currently, and tools/events packages is expired？

If tools/events package is expired, I think the code in this package should be removed, otherwise it will confuse many source code readers and they may use it incorrectly.

#### Environment:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by daniel-hutao** [comment]
@fedebongio I don't know how this issue is going, you can let me do it if no one is work on it.

**Comment by Abirdcfly** [comment]
Just a short research:
Once event migration is completed, tools/events packages shuold be remove.
But not yet, at least it is still in use here:
https://github.com/kubernetes/kubernetes/blob/5b92e46b2238b4d84358451013e634361084ff7d/cmd/kube-scheduler/app/config/config.go#L49-L50
