### ISSUE TITLE
remove deprecated klog flags

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#105310]
#### What would you like to be added:

At some point we can remove the legacy klog flags. This change includes:
- removing the command line check in component-base/logs/validation.go
- removing the "unsupported flags" warning from the `--logging-format` help text
- adding a remark for `-vmodule` that it only works for text output

#### Why is this needed:

 https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components

**Comment by shivanshu1333** [comment]
@pohly please feel free to assign me, I've bandwidth to pick this

**Comment by pohly** [comment]
It's much too early to work on this. :grin: 

We first must mark the flags as deprecated (https://github.com/kubernetes/kubernetes/pull/105042) then in Kubernetes 1.26 (?) we can remove them.

**Comment by shivanshu1333** [comment]
Okay got it

**Comment by serathius** [comment]
Don't have capacity to work on this.

**Comment by pohly** [comment]
/triage accepted
/assign @shivanshu1333 

@shivanshu1333: you said that you wanted to work on this - are you still available?

We might be able to do this for 1.27, but I haven't checked.

**Comment by shivanshu1333** [comment]
Okay, I'll pick it up...

**Comment by pohly** [comment]
This issue was resolved via https://github.com/kubernetes/kubernetes/pull/112120 which was already merged for 1.26! I think we forgot about that when re-triaging this issue...

/close
