### ISSUE TITLE
reference to loop variables in component helper and plugin of scheduler

### ISSUE THREAD

**Issue by ishangupta-ds** [kubernetes/kubernetes#105305]
#### What happened:

Found reference to loop variables in the following files:

* `pkg/scheduler/framework/plugins/interpodaffinity/scoring.go`
* `staging/src/k8s.io/component-helpers/scheduling/corev1/nodeaffinity/nodeaffinity.go`

#### What you expected to happen:

Loop variables should not be referenced 

#### How to reproduce it (as minimally and precisely as possible):

Codebase inspection 

#### Anything else we need to know?:

Issue for best practices

#### Environment:
- Kubernetes version (use `kubectl version`): N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g: `cat /etc/os-release`): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Network plugin and version (if this is a network-related bug): N/A
- Others: N/A

**Comment by ishangupta-ds** [comment]
cc: @alculquicondor @chendave

**Comment by alculquicondor** [comment]
I don't think this is a problem

/close
