### ISSUE TITLE
supported CNIs should have stable networking for Linux and Windows pods 

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#105336]
#### Which jobs are flaking:
aks-engine-windows-containerd-master

#### Which test(s) are flaking:
Kubernetes e2e suite: [sig-windows] Hybrid cluster network for all supported CNIs should have stable networking for Linux and Windows pods
#### Testgrid link:
https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master
#### Reason for failure:
https://curl.se/libcurl/c/libcurl-errors.html shows that exit code of 22 is because of error greater than 400. So there seems to be networking problem.
#### Anything else we need to know:
- links to go.k8s.io/triage appreciated
- links to specific failures in spyglass appreciated

#### Relevant SIG

/sig windows

cc @marosset @jsturtevant @jayunit100 @claudiubelu

**Comment by marosset** [comment]
Here are some logs from the failure
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1442856310264565760

We likely need to update the test to print out the results of the exec command used in this test.
There is enough enough information in the existing logs to debug.

**Comment by jsturtevant** [comment]
This issue hasn't reproduced in the Azure test suite. 

I used https://storage.googleapis.com/k8s-triage/index.html?sig=windows&test=Hybrid%20cluster%20network%20for%20all%20supported and see a few flakes due to some stability in gce tests but not related to the test it's self.

**Comment by marosset** [comment]
/assign @claudiubelu 
We haven't seen this in a while - can you check if this is still and issue and/or close if necessary?

**Comment by marosset** [comment]
sig-windows backlog refinement:
We haven't seen this in a while so we will close for now.
/close
