### ISSUE TITLE
Capture the status message from status-type responses in audit logs

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#105353]
#### What happened:

If the response to a request is a `metav1.Status`, we currently copy a subset of the response to the `ResponseStatus` field of the audit logs: https://github.com/kubernetes/kubernetes/blob/1ad3e14f1fc4a5f6e6cd6f9ffc7d030cb3d6540d/staging/src/k8s.io/apiserver/pkg/audit/request.go#L183-L188

Note that the message is not included. In order to capture the response message, the full `RequestResponse` audit level must be used. This is not always desireable - as a contrived example, consider the case of secret resource failing validation. For a more common case, dropping the full response object may be desireable to cut down on storage costs, but the relatively small status response still holds valuable data (e.g. admission denials) in the error case.

#### What you expected to happen:

We should always capture the full `metav1.Status` response, including the message field. I'm open to dropping the details field, but I'm not sure that's necessary.

/sig auth api-machinery
/area audit
/milestone v1.23

**Comment by uhari03** [comment]
Would love to work on this
/assign

**Comment by varshaprasad96** [comment]
Hi (@uhari03 @jpbetz),
k8s 1.23 bug triage here 👋,
Just wanted to follow up and check if it would be possible to get this into k8s 1.23. If not, any objections if we move this to the next milestone?

**Comment by uhari03** [comment]
@varshaprasad96 Trying to get someone to review and merge: https://github.com/kubernetes/kubernetes/pull/105415

**Comment by varshaprasad96** [comment]
@uhari03 can this be moved to the 1.24 milestone? Looks like 1.23 milestone has been cleared from #105415

**Comment by uhari03** [comment]
@varshaprasad96 I'm guessing it has to be moved to 1.24 now, I'm still waiting for someone to approve so the test runs.
We were blocked by the CLA due to issues with the latest linux foundation migration, but that has been resolved.

**Comment by liggitt** [comment]
yes, this is not a regression in 1.23, so it's not release blocking

/milestone v1.24

**Comment by DiptoChakrabarty** [comment]
Hi @uhari03 I am part of the bug triage team for v1.24 , there hasn't been any activity for this issue for a long time , wanted to check up if there is any work planned for this. Thank You.

**Comment by uhari03** [comment]
@DiptoChakrabarty waiting for a review/merge on the following right now: https://github.com/kubernetes/kubernetes/pull/105415
