### ISSUE TITLE
There is some difference between the memory shown by kubectl top and the memory shown by contaier internal top

### ISSUE THREAD

**Issue by algebra2k** [kubernetes/kubernetes#105340]
#### What happened:

In our environment, we run a lot of php containers with kubernetes, but we found that our php containers were often `OOM`.  we found that the memory value by `kubectl top pods --containers` and `cAdvisor` is somewhat different from the `top` in container.

Here is some information in our environment: 

First, we run `kubectl to` and see that the *service* container memory is `244Mi`.
```shell
> kubectl top pod  -n ns-cd92f840eb1849c799bd686c89a2f457 dp-5e16c59b16d5e-55886dfd69-drm4p --containers

W0929 16:06:15.148541   32818 top_pod.go:140] Using json format to get metrics. Next release will switch to protocol-buffers, switch early by passing --use-protocol-buffers flag
POD                                 NAME      CPU(cores)   MEMORY(bytes)
dp-5e16c59b16d5e-55886dfd69-drm4p   service   2m           244Mi
dp-5e16c59b16d5e-55886dfd69-drm4p   sidecar   5m           22Mi
```
Then I enter the *service* contaienr exec `top` command

```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# top
top - 16:08:28 up 187 days,  4:04,  0 users,  load average: 5.79, 4.60, 3.39
Tasks:  17 total,   1 running,  16 sleeping,   0 stopped,   0 zombie
%Cpu(s): 27.8 us,  7.1 sy,  0.0 ni, 64.5 id,  0.1 wa,  0.0 hi,  0.6 si,  0.0 st
KiB Mem : 32353912 total,   488796 free, 13307404 used, 18557712 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 19509460 avail Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
  248 root      20   0  510588  24692  19024 S   0.0  0.1   0:28.22 php-fpm
 1135 root      20   0  513196  20704  13916 S   0.5  0.1   0:00.15 php-fpm
 1134 root      20   0  513196  20668  13844 S   0.5  0.1   0:00.51 php-fpm
 1125 root      20   0  513196  20664  13844 S   0.0  0.1   0:01.55 php-fpm
    1 root      20   0   34020   9820   3956 S   0.0  0.0   0:00.56 my_init
  249 root      20   0 1527072   7420   4008 S   0.0  0.0   4:05.82 file-exporter
   13 root      20   0  294456   5176   3868 S   0.0  0.0   0:00.32 syslog-ng
 1150 root      20   0   22228   4368   3436 S   0.0  0.0   0:00.02 bash
  256 root      20   0   33788   3816   2392 S   0.0  0.0   4:36.03 nginx
 1165 root      20   0   39920   3532   2984 R   0.0  0.0   0:00.00 top
  250 root      20   0   33240   3292   2316 S   0.0  0.0   0:00.00 nginx
  245 root      20   0    4456    124      0 S   0.0  0.0   0:00.03 runsv
  246 root      20   0    4456    124      0 S   0.0  0.0   0:00.03 runsv
  242 root      20   0    4608    120      0 S   0.0  0.0   0:06.86 runsvdir
  243 root      20   0    4456    120      0 S   0.0  0.0   0:00.03 runsv
  244 root      20   0    4456    120      0 S   0.0  0.0   0:00.03 runsv
  247 root      20   0    4456    120      0 S   0.0  0.0   0:00.03 runsv
```
and `free -m` shown:

```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# free -m
              total        used        free      shared  buff/cache   available
Mem:          31595       12969         522         560       18103       19080
Swap:             0           0           0
```
Then I counted the actual memory usage
```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# kb=$(ps aux | grep -v grep | grep -v 'ps aux' | grep -v bash | grep -v awk | grep -v RSS | awk '{print $6}' | awk '{s+=$1} END {printf "%.0f", s}');

root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# echo $kb
117732

root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# mb=$(expr $kb / 1024);

root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# echo $mb
114
```

So, I have some doubts about this. 

memory.usage_in_bytes and `memory.limit_in_bytes` seen by crgoup
```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# cat /sys/fs/cgroup/memory/memory.usage_in_bytes
257769472

root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# cat /sys/fs/cgroup/memory/memory.limit_in_bytes
268435456
```
and `memory.stat`
```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# cat /sys/fs/cgroup/memory/memory.stat
cache 4403200
rss 27103232
rss_huge 0
shmem 3649536
mapped_file 2973696
dirty 135168
writeback 0
pgpgin 18459672
pgpgout 18452014
pgfault 19004436
pgmajfault 33
inactive_anon 135168
active_anon 29736960
inactive_file 962560
active_file 356352
unevictable 0
hierarchical_memory_limit 268435456
total_cache 4403200
total_rss 27103232
total_rss_huge 0
total_shmem 3649536
total_mapped_file 2973696
total_dirty 135168
total_writeback 0
total_pgpgin 18459672
total_pgpgout 18452014
total_pgfault 19004436
total_pgmajfault 33
total_inactive_anon 135168
total_active_anon 29736960
total_inactive_file 962560
total_active_file 356352
total_unevictable 0
```
and `memory.kmem.usage_in_bytes`:
```shell
root@dp-5e16c59b16d5e-55886dfd69-drm4p:~# cat /sys/fs/cgroup/memory/memory.kmem.usage_in_bytes
226652160
```
I know from these issues [moby/issues/40727](https://github.com/moby/moby/issues/40727) [cadvisor/pull/1380](https://github.com/google/cadvisor/pull/1380) that `kubectl top` see the value `memory.usgae_in_bytes - total_inactive_file`, but the value we see inside the container is actually much smallers, so when the php containers cotinues to use memory, it will reach `limits: memory: 256M` limit, but there is actually a lot of memory available inside the container by `free -m`.

#### Environment:
- Kubernetes version (use `kubectl version`): v1.17.12
- Cloud provider or hardware configuration:  8C + 32 G
- OS (e.g: `cat /etc/os-release`):  Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`):  5.4.0-73-generic
- Install tools: 
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by neolit123** [comment]
/sig node cli
for triage

**Comment by neolit123** [comment]
> Kubernetes version (use kubectl version): v1.17.12

versions < 1.20 are out of support. is this reproducible with a newer apiserver + kubelet + kubectl?

**Comment by ehashman** [comment]
257769472 bytes from "memory.usage_in_bytes and memory.limit_in_bytes seen by crgoup" is 245Mi which matches `kubectl top` output. This is what cadvisor reports.

Note that your PHP processes according to the `top` output are using large amounts of virtual memory, and your system is using large amounts (18557712 -> ~18GB) of kernel buffer/cache memory. It is possible that they are I/O intensive and that the kernel is using memory to buffer disk I/O, so while the programs themselves do not require a lot of memory, they ultimately will require more memory available on the system to be performant when deployed.

This is an application tuning issue, not a bug in Kubernetes.

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close
