### ISSUE TITLE
Create skipper tool for FeatureGates

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#105351]
#### What would you like to be added:
A new skipper function which skips tests if a FeatureGate is enabled.

#### Why is this needed:
A couple of tests get skipped if a particular FeatureGate is enabled/disabled, checking ` utilfeature.DefaultFeatureGate.Enabled(feature)` and if true/false, calling `skipInternal()`. Having a wrapper around this would simplify the logic on these tests and follow the pattern of skippers.

**Comment by ehashman** [comment]
We have like 4 feature-specific skippers that could be a single generic helper: https://github.com/kubernetes/kubernetes/blob/6f47878926f1aa51e0864821d882bf695558709a/test/e2e/framework/skipper/skipper.go#L139-L162

As well as a bunch of 1-off skippers: https://github.com/kubernetes/kubernetes/blob/6f47878926f1aa51e0864821d882bf695558709a/test/e2e_node/podresources_test.go#L629-L631

/triage accepted

**Comment by Git-Jiro** [comment]
Hi!
I would like to work on this issue

**Comment by aojea** [comment]
> We have like 4 feature-specific skippers that could be a single generic helper:

![image](https://user-images.githubusercontent.com/6450081/136293945-b73d8467-8ce6-41cf-9c74-a3b77182f6a8.png)
