### ISSUE TITLE
`k8s.io/client-go/dynamic/fake` does not implement `DeleteCollection`

### ISSUE THREAD

**Issue by mattmoor** [kubernetes/kubernetes#105357]
#### What happened:

`DeleteCollection` calls on the fake dynamic client do not delete matching objects.

#### What you expected to happen:

I expected a `DeleteCollection` call on the fake dynamic client to delete objects matching the supplied selector.

#### How to reproduce it (as minimally and precisely as possible):

Here is a little test that shows a successful `List` and failing `DeleteCollection` with the same selector (on the same initial object list):

```go
package dynamic

import (
	"context"
	"errors"
	"fmt"
	"testing"

	appsv1 "k8s.io/api/apps/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	fakedynamic "k8s.io/client-go/dynamic/fake"
)

func TestFakeBug(t *testing.T) {
	scheme := runtime.NewScheme()
	appsv1.AddToScheme(scheme)

	wantObj := &unstructured.Unstructured{}
	wantObj.SetAPIVersion("apps/v1")
	wantObj.SetKind("Deployment")
	wantObj.SetNamespace("default")
	wantObj.SetName("what-i-want")
	wantObj.SetLabels(map[string]string{
		"matching-label": "true",
	})

	tests := []struct {
		name     string
		callback func(dynamic.Interface) error
		objects  []runtime.Object
	}{{
		name: "delete collection (this does not work!)",
		callback: func(client dynamic.Interface) error {
			rc := client.Resource(schema.GroupVersionResource{
				Group:    "apps",
				Version:  "v1",
				Resource: "deployments",
			})

			err := rc.Namespace(wantObj.GetNamespace()).DeleteCollection(context.Background(), metav1.DeleteOptions{}, metav1.ListOptions{
				LabelSelector: "matching-label=true",
			})
			if err != nil {
				return err
			}

			// Trigger a 404 api status error.
			_, err = rc.Namespace(wantObj.GetNamespace()).Get(context.Background(), wantObj.GetName(), metav1.GetOptions{})
			if !apierrors.IsNotFound(err) {
				return fmt.Errorf("wanted not found, but got %T (%v)", err, err)
			}
			return nil
		},
		objects: []runtime.Object{wantObj},
	}, {
		name: "list (this works!)",
		callback: func(client dynamic.Interface) error {
			rc := client.Resource(schema.GroupVersionResource{
				Group:    "apps",
				Version:  "v1",
				Resource: "deployments",
			})

			objs, err := rc.Namespace(wantObj.GetNamespace()).List(context.Background(), metav1.ListOptions{
				LabelSelector: "matching-label=true",
			})
			if err != nil {
				return err
			}

			if len(objs.Items) == 0 {
				return errors.New("expected match, but for none")
			}

			return nil
		},
		objects: []runtime.Object{wantObj},
	}}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			fkc := fakedynamic.NewSimpleDynamicClient(scheme, test.objects...)
			err := test.callback(fkc)
			if err != nil {
				t.Fatalf("callback() = %v", err)
			}
		})
	}
}
```

#### Anything else we need to know?:

I am fairly certain that the problem here is that while `DeleteCollectionActionImpl` is defined, the `ObjectTracker` does not define a `DeleteCollection` method and the fixture (`testing/fixture.go`) does not handle `DeleteCollectionActionImpl` (which *is* defined in `testing/actions.go`)

#### Environment:
- Kubernetes version (use `kubectl version`):

I am pinned to `k8s.io/client-go` at `v0.21.4` in `go.mod`

**Comment by mattmoor** [comment]
FWIW, while I didn't try the test against the latest release or HEAD, I did look at whether the fixture had been changed to reference the action (as it does `DeleteActionImpl`, for example).

**Comment by jpbetz** [comment]
@mattmoor are you willing to open a PR to fix?
/cc @caesarxuchao 
/triage accepted

**Comment by mattmoor** [comment]
I'll see if I can find cycles for it, but if someone else wants to please feel free.

Part of my hesitation is uncertainty about expanding the `ObjectTracker` interface to include `DeleteCollection`, which might be a breaking change (if other folks are implementing this out of tree), but if that's cool (and I find some time), then I will try to take a stab at it.

**Comment by jpbetz** [comment]
Adding `DeleteCollection` to [`ObjectTracker`](https://github.com/kubernetes/kubernetes/blob/ca0c04e4d3342d064a5c8fd1c88221a479780cb5/staging/src/k8s.io/client-go/testing/fixture.go#L42) feels like a sufficiently contained and easy to resolve breaking change that we can probably go ahead with it.  I can't think of any way of making this change that is both backward compatible and leaves the code in a good long term state. Any concerns @lavalamp, @deads2k ?

**Comment by tiarly** [comment]
I can take it
/assign
