### ISSUE TITLE
automated testing of command line interfaces

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#105392]
#### What would you like to be added:

We should have pre-merge tests that verify that code changes do not affect the command line interface of the Kubernetes tools. This could cover:
- which flags are supported (removing flags is a breaking change)
- formatting of help texts (hyphen versus underscore for legacy flags)
- error handling when the command line is invalid (ideally the usage text should get printed, followed by the error)

The script from https://github.com/kubernetes/kubernetes/pull/105076#issuecomment-931319645 might serve as starting point.

#### Why is this needed:

The command line API is part of the Kubernetes API and must be kept stable. Removing flags must be done with proper deprecation. Adding flags should not be done lightly.

**Comment by pohly** [comment]
@pchan started working on such a tool in the context of issue #102237.

/assign @pchan

**Comment by pchan** [comment]
@pohly  Can you try again please. I am not a member yet, so I need to comment on the issue.
