### ISSUE TITLE
kubectl convert plugin can't handle cloud.google.com/v1 BackendConfig

### ISSUE THREAD

**Issue by arvid-m** [kubernetes/kubernetes#105369]
#### What happened:

I'm trying to run `kubectl convert -f myservice.yaml` on a YAML file that contains:

```yaml
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
  name: my-service
spec:
  iap:
    enabled: true
```

#### What you expected to happen:

I would expect the output to be successful, but instead I got: `error: unable to decode "myservice.yaml": no kind "BackendConfig" is registered for version "cloud.google.com/v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"`

#### How to reproduce it (as minimally and precisely as possible):

Run the command above on the sample file.

#### Anything else we need to know?:

Is this because cloud.google.com/v1 is an extension to GCP? Does that mean that `kubectl convert` won't work with any CRDs?

#### Environment:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: GCP
- OS (e.g: `cat /etc/os-release`): 
```bash
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.5
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```
- Others: Using same version of kubectl-convert as kubectl

**Comment by neolit123** [comment]
> Is this because cloud.google.com/v1 is an extension to GCP? Does that mean that kubectl convert won't work with any CRDs?

yes, you should contact it's owners (GCP) for support on how to convert it.

this page might need some clarification:
https://kubernetes.io/docs/tasks/tools/included/kubectl-convert-overview/

/remove-kind bug
/kind support documentation
