### ISSUE TITLE
Add information about securing the Kubelet to security.md

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#1053]
The kubelet API surface (creating pods, publishing info, and running commands in containers #836) gives a high level of access to individual containers and resource consumption on minions.  We should document how we plan on securing it in [security.md](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/security.md).

**Comment by smarterclayton** [comment]
@liggitt this should be added to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/security.md once you make your proposal on securing the kubelet.

**Comment by erictune** [comment]
Hoping someone from node team will pick this up.

**Comment by smarterclayton** [comment]
I think this can be closed, in practice this is documented and secured sufficiently now.
