### ISSUE TITLE
kube-proxy: iptables is the best-available proxy, while ipvs has advantages over iptables.

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubernetes#105439]
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#ipvs-vs-iptables stipulates, that IPVS is better than IPTABLES. This is reiterated at https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies.

>$ kube-proxy --help
>…
>      --proxy-mode ProxyMode                         Which proxy mode to use: 'userspace' (older) or 'iptables' (faster) or 'ipvs' or 'kernelspace' (windows). If blank, use the best-available proxy (currently iptables). If the iptables proxy is selected, regardless of how, but the system's kernel or iptables versions are insufficient, this always falls back to the userspace proxy.

There is a contradiction: the best-available proxy currently is iptables, while IPVS has advantages over iptables.

**Comment by khenidak** [comment]
@dilyanpalauzov I am not sure what is needed by this issue. Are you looking for clarification?
/triage needs-information

**Comment by dilyanpalauzov** [comment]
Is iptables the best available proxy, or is ipvs better than iptables?

**Comment by dilyanpalauzov** [comment]
Since `the best available proxy` is something subjective, the output of `kube-proxy-help` shall not print `If blank, use the best-available proxy (currently iptables).`  It shall print instead `use SUBJECTIVELY the best availabe proxy (iptables)`.

> but since the changes in IPVS has to be implemented in the kernel has a slower evolution

What does the above mean? Does IPVS rely on user-space, since its kernel implementation is incomplete.  Do the “changes” exist somewhere?

**Comment by aojea** [comment]
> Since the best available proxy is something subjective

The best available proxy for general use is `iptables`, what is subjective is the use anybody want to give to the cluster :sweat_smile: 

> but since the changes in IPVS has to be implemented in the kernel has a slower evolution

> What does the above mean? Does IPVS rely on user-space, since its kernel implementation is incomplete. Do the “changes” exist somewhere?

I didn't say anything about incomplete, IPVS is implemented in the kernel https://github.com/torvalds/linux/tree/master/net/netfilter/ipvs , the kernel doesn't backport features, if you want feature X that is implemented in 5.6 kernel and you are in kernel 3.11, you have to upgrade your kernel and reboot the node, also the kernel is a huge project, development is slower than if you have your own userspace project

**Comment by jonyhy96** [comment]
> I want the docs to be more accurate. I want to choose between iptables and ipvs .
> 
> E.g. the documentation states, that iptables is the best, but it does not say how is it better than ipvs. In fact, it mentions how ipvs is better than iptables. If the comparison is subjective, then no general comparison between the the modes shall be made.

Agree, this realy makes misleading. i will try to fix it.

/assign
