### ISSUE TITLE
A bug that mutates a not-used copy of a struct

### ISSUE THREAD

**Issue by guodongli-google** [kubernetes/kubernetes#105423]
#### What happened:

A static analyzer DeepGo reports a finding that reveals a coding issue.

#### What you expected to happen:

At https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/emicklei/go-restful/route.go#L168-L169

Here [`Route`](https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/vendor/github.com/emicklei/go-restful/route.go#L21) is struct which will be copied by value. The mutation on the value receiver `r` doesn't do anything to the original struct in the caller. As a consequence, this mutation has no meaningful effect.
```
type Route struct {
	Method   string
	...
	contentEncodingEnabled *bool
}

func (r Route) EnableContentEncoding(enabled bool) {
	r.contentEncodingEnabled = &enabled
}

```
One fix is to use pointer receiver.
```
func (r *Route) EnableContentEncoding(enabled bool) {
	r.contentEncodingEnabled = &enabled
}
```
Another possible fix is to write back `enabled` into the caller's`contentEncodingEnabled `:
```
func (r Route) EnableContentEncoding(enabled bool) {
	*r.contentEncodingEnabled = enabled
}
```

#### How to reproduce it (as minimally and precisely as possible):
A simplified bug reproducer is available at: https://play.golang.org/p/cibNCyIarZS

#### Anything else we need to know?:
Related issue: https://github.com/kubernetes/kubernetes/issues/105155

Found by #deepgo.

**Comment by shivanshu1333** [comment]
Filled the bug in the vendor's repository, we can close this now @guodongli-google

**Comment by neolit123** [comment]
looks like EnableContentEncoding() is not used by k/k code too.

/close
