### ISSUE TITLE
Kubelet service is not coming up because inode consumption is increasing.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#105440]
#### What happened:
Kubelet services is not able to come up, as could see inode consumption  increased to 100% of total capacity in /var/lib/kubelet. 

#### What you expected to happen:
Inode consumtion should not be increased.

#### How to reproduce it (as minimally and precisely as possible):
Deploy k8s with date as (x.x.2021) and change the date to some old (x.x.2016) in order to failed certificate validation. After keep setup for two three days. 
once after this , pls try df -i .. you might see inode used is 100%

#### Anything else we need to know?:
After debugging above issue, I could see there lot of small files created in /var/lib/kubelet/pods/pod uid/container/<pod-name/container-name>

for ex: 
205750 /var/lib/kubelet/pods/fc4d4d705ce54bf5dab7867e7424b630/containers/kube-controller-manager
205766 /var/lib/kubelet/pods/e5846583a2bc8e7f6f2a82add93c95b3/containers/kube-scheduler

After deleting all these files, could see inode freed to some good extent. 
Note: these files are empty. 

ex:
-rw-rw-rw- 1 root root 0 Oct  4 08:43 6e80011f
-rw-rw-rw- 1 root root 0 Oct  4 08:43 b5495760
-rw-rw-rw- 1 root root 0 Sep 22  2021 090380ff
-rw-rw-rw- 1 root root 0 Sep 29  2021 0db0a904

What all these files? why they are not deleting ? any configuration setup we need to do here?

#### Environment:
- Kubernetes version (use `kubectl version`): `Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`): `NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
- Kernel (e.g. `uname -a`): `Linux ubuntu 4.15.0-144-generic #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by rphillips** [comment]
Are there any errors in the Kubelet log?

**Comment by akshaysharama** [comment]
@rphillips ,
    ` 9175 event.go:265] Unable to write event: 'Post https://[xx.xx.xx.xx]:6443/api/v1/namespaces/default/events: dial tcp xx.xx.xx.xx:6443: connect: connection refused' (may retry after sleeping)
          2021-09-17 10:37:16.6059 localhost kubelet[9175]: F0917 10:37:16.604801 9175 server.go:182] Failed to create listener for podResources endpoint: failed to create temporary file: open /var/lib/kubelet/pod-resources/959020798: no space left on device`

after debugging, when we did `df -i`, could see 100% inode was consumed for this path

**Comment by yxxhero** [comment]
@akshaysharama any message like `Orphaned pod found - but volume paths are still present on disk` in the kubelet log?
https://github.com/kubernetes/kubernetes/issues/60987
