### ISSUE TITLE
MountVolume.SetUp failed for volume: is not a file

### ISSUE THREAD

**Issue by chandra279mohan** [kubernetes/kubernetes#105429]
when i do deployment of redis, pod is not in ready state getting below error:

`Name:           redis-78688f7dd8-2j8kz
Namespace:      crm-stg
Priority:       0
Node:           ip-172-31-19-192.us-west-2.compute.internal/172.31.19.192
Start Time:     Sun, 03 Oct 2021 05:33:33 +0000
Labels:         pod-template-hash=78688f7dd8
                service=redis
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  ReplicaSet/redis-78688f7dd8
Containers:
  main:
    Container ID:  
    Image:         sloopstash/redis:v1
    Image ID:      
    Port:          6379/TCP
    Host Port:     0/TCP
    Command:
      /usr/bin/supervisord
      -c
      /etc/supervisord.conf
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/usr/local/bin/redis-cli PING] delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:      tcp-socket :6379 delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/supervisord.conf from supervisor-server (rw)
      /etc/supervisord.d/redis.ini from redis-supervisor (rw)
      /opt/redis/conf/redis.conf from redis-server (rw)
      /opt/redis/data from redis-data (rw)
      /opt/redis/log from redis-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fgzl6 (ro)
  log:
    Container ID:  
    Image:         sloopstash/redis:v1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/supervisord
      -c
      /etc/supervisord.conf
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/supervisord.conf from supervisor-server (rw)
      /opt/redis/log from redis-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-fgzl6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  supervisor-server:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kickstart-kubernetes/supervisor/conf/main.conf
    HostPathType:  File
  redis-supervisor:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kickstart-kubernetes/supervisor/conf/redis.ini
    HostPathType:  File
  redis-server:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kickstart-kubernetes/redis/conf/main.conf
    HostPathType:  File
  redis-data:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kickstart-kubernetes/redis/data
    HostPathType:  DirectoryOrCreate
  redis-log:
    Type:          HostPath (bare host directory volume)
    Path:          /opt/kickstart-kubernetes/redis/log
    HostPathType:  DirectoryOrCreate
  default-token-fgzl6:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-fgzl6
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                From               Message
  ----     ------       ----               ----               -------
  Normal   Scheduled    51s                default-scheduler  Successfully assigned crm-stg/redis-78688f7dd8-2j8kz to ip-172-31-19-192.us-west-2.compute.internal
  Warning  FailedMount  20s (x7 over 51s)  kubelet            MountVolume.SetUp failed for volume "redis-server" : hostPath type check failed: /opt/kickstart-kubernetes/redis/conf/main.conf is not a file
  Warning  FailedMount  20s (x7 over 51s)  kubelet            MountVolume.SetUp failed for volume "supervisor-server" : hostPath type check failed: /opt/kickstart-kubernetes/supervisor/conf/main.conf is not a file
  Warning  FailedMount  20s (x7 over 51s)  kubelet            MountVolume.SetUp failed for volume "redis-supervisor" : hostPath type check failed: /opt/kickstart-kubernetes/supervisor/conf/redis.ini is not a file`

### Here is the Deployment template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      service: redis
  replicas: 1
  template:
    metadata:
      labels:
        service: redis
    spec:
      containers:
        - name: main
          image: sloopstash/redis:v1
          imagePullPolicy: Always
          volumeMounts:
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
            - name: redis-supervisor
              mountPath: /etc/supervisord.d/redis.ini
            - name: redis-server
              mountPath: /opt/redis/conf/redis.conf
            - name: redis-data
              mountPath: /opt/redis/data
            - name: redis-log
              mountPath: /opt/redis/log
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
          ports:
            - containerPort: 6379
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - "/usr/local/bin/redis-cli"
                - "PING"
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: log
          image: sloopstash/redis:v1
          volumeMounts:
            - name: supervisor-server
              mountPath: /etc/supervisord.conf
            - name: redis-log
              mountPath: /opt/redis/log
          command:
            - "/usr/bin/supervisord"
            - "-c"
            - "/etc/supervisord.conf"
      volumes:
        - name: supervisor-server
          hostPath:
            path: /opt/kickstart-kubernetes/supervisor/conf/main.conf
            type: File
        - name: redis-supervisor
          hostPath:
            path: /opt/kickstart-kubernetes/supervisor/conf/redis.ini
            type: File
        - name: redis-server
          hostPath:
            path: /opt/kickstart-kubernetes/redis/conf/main.conf
            type: File
        - name: redis-data
            path: /opt/kickstart-kubernetes/redis/data
            type: Directory
        - name: redis-log
            path: /opt/kickstart-kubernetes/redis/log
            type: Directory

### Get pods
ec2-user@ip-172-31-46-5 kickstart-kubernetes]$ kubectl get pods -n crm-stg
NAME                     READY   STATUS              RESTARTS   AGE
redis-78688f7dd8-2j8kz   0/2     ContainerCreating   0          20s

@saad-ali  @xing-yang

**Comment by Kartik494** [comment]
Hi @chandra279mohan  is this deployment manually written for specific task or is there any link which you could provided for testing this deployment

**Comment by Kartik494** [comment]
It seems like it's an error on `mountPath` you provided in the deployment file
