### ISSUE TITLE
kube-apiserver

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#105447]
Kube-apiserver source code, which part is to achieve kubelet and Kube-Apiserver network connection? What kind of messages do they send to each other? What exactly is that information?

**Comment by MadhavJivrajani** [comment]
@pipijiev12 you'll most likely get a response if you ask this in our slack (https://slack.k8s.io)
The channels that you could ask in are `sig-node`, `sig-api-machinery`, `kubernetes-novice`.
Closing 
/close
