### ISSUE TITLE
kubectl: discovery is throttled when there are lots of resources (CRDs)

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#105489]
The default client side rate limit is 50qps with a burst of 100.

Kubectl does a discovery pass before doing the operation requested. Discovery involves (some combination of) reading the OpenAPI spec and the "homegrown" discovery information for the purpose of e.g. mapping kinds to resources. Sometimes these can be cached, but even if it is cached, an API call can be required to verify it hasn't changed.

This means that if there are more than 100 group versions, we will hit the client side rate limit in the process of discovery, possibly significantly slowing down the process.

AFAIK there is no way to adjust this limit when using kubectl.

A user report can be found here: https://github.com/kubernetes/kubernetes/pull/101634#issuecomment-933851060

An easy way to fix this is to disable the client side limit in kubectl. Possibly caching parameters could be adjusted, too. A difficult fix would be to load the minimum amount of discovery documents necessary to perform the task at hand (but some tasks require everything).

/sig cli

**Comment by justinsb** [comment]
Two contributory things:

* I think there's a bug where `kubectl get clusterrolebindings.rbac.authorization.k8s.io` forces a cache invalidation and full rediscovery, but ``kubectl get clusterrolebindings` does not.  The gotcha is that tab completion uses the full name, and of course you're more likely to use tab completion when you have lots of CRDs, making discovery more expensive.

* In general, we shouldn't have to do a full discovery to map GVK -> GVR.  In the vast majority of cases I think we should be able to just do type discovery in the group and then find the K -> R.  (@lavalamp shared something about Openshift clusters having the G in GVK not equal to the G in GVR, but I would hope we could address that with a fallback).  This would be great for controllers, but I don't think it helps for kubectl where we often need shortnames from the apiserver (and in general, kubectl is going to use more of the surface than a controller which only needs GVK -> GVR mapping, so a full discovery is more justified ... ideally we wouldn't invalidate it every time the user typed <tab> though!)

**Comment by seans3** [comment]
Moving to kubectl repo: https://github.com/kubernetes/kubectl/issues/1126

/close

**Comment by cannonpalms** [comment]
> In general, we shouldn't have to do a full discovery to map GVK -> GVR. In the vast majority of cases I think we should be able to just do type discovery in the group and then find the K -> R. (@lavalamp shared something about Openshift clusters having the G in GVK not equal to the G in GVR, but I would hope we could address that with a fallback). This would be great for controllers, but I don't think it helps for kubectl where we often need shortnames from the apiserver (and in general, kubectl is going to use more of the surface than a controller which only needs GVK -> GVR mapping, so a full discovery is more justified ... ideally we wouldn't invalidate it every time the user typed <tab> though!)

@justinsb Is there another issue describing this work for controllers?
