### ISSUE TITLE
apf: watches served by aggregated apiservers occupy seat for entire duration of request

### ISSUE THREAD

**Issue by benluddy** [kubernetes/kubernetes#105409]
#### What happened:

On a cluster with many APIs provided by aggregated apiservers, with controllers managing those APIs, the number of occupied seats effectively has a floor of 1 per watch. If the combined max-inflight limit is reduced low enough, priority levels tend to become saturated by these long-running watch requests and other requests are starved.

#### What you expected to happen:

Watch requests consume a seat only during initialization.

#### How to reproduce it (as minimally and precisely as possible):

1. Create a PriorityLevelConfiguration and a corresponding FlowSchema to match watches against a resource served by an aggregated apiserver.
2. Start some watch requests.
3. See the metric `apiserver_flowcontrol_request_concurrency_in_use` climb on the priority level per watch until all seats are exhausted.

#### Environment:
- Kubernetes version (use `kubectl version`): `v1.22.1-1676+5c24c729c7b468-dirty` (OpenShift 4.9)

/sig api-machinery

**Comment by tkashem** [comment]
cc @MikeSpreitzer @wojtek-t

**Comment by MikeSpreitzer** [comment]
D'oh!

I can see two obvious possible ways to cope:
1. make one apiserver not manage watch requests the are delegated to another apiserver; or
2. add a marker into the notification stream so that the non-origin apiservers can detect when initialization is done.

**Comment by wojtek-t** [comment]
I would even say that for regular (non-long-running) requests, it's not obvious that they should be managed by P&F even.
[I agree that for watch initialization it's particularly bad though.]

@deads2k - do we have a simple way to detect if the request will be served from our kube-apiserver or from some other aggregated apiserver?

**Comment by deads2k** [comment]
> @deads2k - do we have a simple way to detect if the request will be served from our kube-apiserver or from some other aggregated apiserver?

There is not currently a way to know that ahead of time in the filters today.  It require a list/watch, but it ought not be excessively expensive to make a 99% correct prediction, but the actual decision is made by the aggregated apiserver later in the request.

**Comment by MikeSpreitzer** [comment]
@deads2k : is there a way that we can plumb that knowledge forward to the filters?
