### ISSUE TITLE
Getting node status as "Attempting to reclaim ephemeral-storage".

### ISSUE THREAD

**Issue by gangadharsingh056** [kubernetes/kubernetes#105418]
![awadh_error2_diskpressure](https://user-images.githubusercontent.com/43050545/135712906-9e44f797-c937-4c88-8b94-e45ba9f27e9f.PNG)
![awadh_error](https://user-images.githubusercontent.com/43050545/135712907-52dd1918-2411-47f6-8f3f-852c32bc3508.PNG)

In some site, it's suggested to prune using this "docker system prune -a --volumes". But currently user data is stored on the server and docker images too.

Please help me to resolve this issue?

**Comment by Kartik494** [comment]
Could you describe here what log error's are when you run the command `docker system prune -a --volumes` , unused volume should be deleted.

**Comment by gangadharsingh056** [comment]
Dear sir,

I will follow your instructions for future errors due to unused volume.

**Comment by Kartik494** [comment]
@gangadharsingh056 if you don't have any further queries then could you close this issue.Thanks!

**Comment by gangadharsingh056** [comment]
Dear Kubernetes/Kubernetes,

You can close the issue.
Just finally, what should I do to avoid this or what's the best practices?
