### ISSUE TITLE
"internalTrafficPolicy: Local" affects external traffic too

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#105470]
[The internalTrafficPolicy KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy) says:

> This field will be independent from externalTrafficPolicy. In other words, internalTrafficPolicy only applies to traffic originating from internal sources.

However, the actual implementation entangles the two features:

- if a Service is `externalTrafficPolicy: Local`, then `proxy.FilterEndpoints` doesn't even check if it's also `internalTrafficPolicy: Local`, so making a Service external-local means you can't also make it internal-local. (It also skips the topology checks in that case.)
- if a Service is `internalTrafficPolicy: Local`, then both internal and external connections are restricted to local endpoints only (because `proxy.FilterEndpoints` will have discarded the non-local endpoints at the top of the sync loop, so they're not available when programming the remote-originated flows).

/cc @andrewsykim @robscott 
/sig network

**Comment by robscott** [comment]
This overlaps with https://github.com/kubernetes/kubernetes/issues/100313#issuecomment-912824745. As much as it would be ideal to do the endpoint filtering before endpoints are provided to a proxier, I don't think we can continue with that approach. Instead we'll likely need more logic in each proxier implementation. Hopefully this can still mostly just involve calls to shared code.

**Comment by danwinship** [comment]
ah, indeed, this is basically a duplicate
