### ISSUE TITLE
pkg/proxy/ipvs/README.md says `kube init` but means `kubeadm init`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubernetes#105438]
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#cluster-created-by-kubeadm says:

> before running
> `kube init --config <path_to_configuration_file>`
> to specify the ipvs mode before deploying the cluster.

It likely means not `kube init`, but `kubeadm init`

**Comment by MadhavJivrajani** [comment]
/sig network
/good-first-issue
Thanks!
