### ISSUE TITLE
Expand QPS abbreviation in kubelet CLI options help

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubernetes#105420]
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/ says:

> --event-qps int32     Default: 5
> QPS to  limit event creations. The number must be >= 0. If 0 will use default  QPS (5). (DEPRECATED: This parameter should be set via the config file  specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.)

Please explain what the abbreviation QPS stands for.

**Comment by sftim** [comment]
/retitle Expand QPS abbreviation in kubelet CLI options help
