### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable

### ISSUE THREAD

**Issue by guodongli-google** [kubernetes/kubernetes#105426]
#### What happened:

At https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/volume_provisioning.go#L969-L971,
within the loop `for _, pv := range allPVs.Items`, variable `pv` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of &pv within the loop may refer to the last tem updated by the loop. As a consequence, `remainingPVs` may hold multiple instances of the same item.
```
		for _, pv := range allPVs.Items {
			if pv.Spec.StorageClassName == scName {
				remainingPVs = append(remainingPVs, &pv)
			}
		}
```
Later on these remaining PVs are deleted, so it is possible that the same `pv` is deleted multiple times:
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/storage/volume_provisioning.go#L462-L464
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/storage/volume_provisioning.go#L999-L1001

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

#### What you expected to happen:

A fix is to avoid reusing the shared variable node:
```
		for i, pv := range allPVs.Items {
			if pv.Spec.StorageClassName == scName {
				remainingPVs = append(remainingPVs, &allPVs.Items[i])
			}
		}
```

**Found by #deepgo.**

**Comment by shivanshu1333** [comment]
Thanks for pointing out, makes complete sense.
I'm happy to fix it.
/assign
