### ISSUE TITLE
API Priority and Fairness doc does not explain expected client behavior

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#105494]
#### What happened:

I read the [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) doc and it didn't explain how the client should behave when interacting with the API server.

#### What you expected to happen:

I would like the docs to explain:
- How should the client handle throttling/slowness?
- How should the client handle cancellation due to queue fullness?
- What will throttling look like to the client?
- Do the standard client libraries handle throttling?
- What library functions are available to handle or avoid throttling?
- Should clients spam calls as fast as possible, sleep a constant amount, or use a backoff strategy?
- Do reads need to be handled differently than writes?
- If I use multiple clients on different threads/containers/machines/zones/regions will they all throttle together?
- Got any example client code I can copy/paste?

#### How to reproduce it (as minimally and precisely as possible):

Read the doc. Try to write a client, or use existing clients.

#### Anything else we need to know?:

Yay! No more arbitrary client-side throttling!

#### Environment:

N/A

**Comment by lavalamp** [comment]
/sig api-machinery

cc @MikeSpreitzer @wojtek-t @tkashem

**Comment by lavalamp** [comment]
Ah, we should state that also. I think the ordinary go client automatically retries if we set that header, I'll try to double check if it's exponential or if it does exactly what the header requests.

**Comment by tkashem** [comment]
I think by default it uses `NoBackoff` - so no exponential backoff, it just sleeps for `1s` as the header suggests. if the client sets the env variables only then it creates `URLBackoff` which has exponential back off.

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/client.go#L148

**Comment by tkashem** [comment]
https://github.com/kubernetes/kubernetes/issues/105521
