### ISSUE TITLE
Feature Request: Consider pods node when API server opens an exec session to a pod

### ISSUE THREAD

**Issue by nicelkaim** [kubernetes/kubernetes#105464]
A proposal that works through the design along with the implications of the change can be opened as a KEP: 
https://git.k8s.io/enhancements/keps#kubernetes-enhancement-proposals-keps

#### What would you like to be added:
API Server to consider using the node of the requested pod/container when opening connections via exec sessions.

#### Why is this needed:
This will allow exec sessions to have more stability and usability during node pool operations such as scale down or the autorepair of unhealthy nodes unrelated to the pod/container being exec'd into.

**Comment by ball-hayden** [comment]
Would definitely be up for assisting with implementation, but wouldn't know where to start.

**Comment by ball-hayden** [comment]
/remove-lifecycle rotten

^ as above, still interested in helping out. @nicelkaim would you be able to give any hints?
