### ISSUE TITLE
Report a coding issue that uses reference to loop iterator variable.

### ISSUE THREAD

**Issue by guodongli-google** [kubernetes/kubernetes#105425]
#### What happened:

At https://github.com/kubernetes/kubernetes/blob/master/test/e2e/autoscaling/cluster_size_autoscaling.go#L1251-L1253,
within the loop `for _, node := range nodeList.Items`, variable `node` is shared by all the loop iterations, as described in the Go specification (https://golang.org/ref/spec).
All instances of &node within the loop may refer to the last node item updated by the loop. As a consequence, `nodes` may hold multiple instances of the same node.
```
	for _, node := range nodeList.Items {
		if node.Labels[gkeNodepoolNameKey] == poolName {
			nodes = append(nodes, &node)
		}
	}
```

Note that the following unit test checks only the number of nodes rather than the nodes themselves (otherwise the bug may be revealed):
https://github.com/kubernetes/kubernetes/blob/0ac956ff2bef9c84b17d4b9cae2cffe71d5c6386/test/e2e/autoscaling/cluster_size_autoscaling.go#L262

More information on the bug can be found at https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable.

#### What you expected to happen:

A fixe is to avoid reusing the shared variable `node`:

```
	for i, node := range nodeList.Items {
		if node.Labels[gkeNodepoolNameKey] == poolName {
			nodes = append(nodes, &nodeList.Items[i])
		}
	}
```

Found by #deepgo.

**Comment by shivanshu1333** [comment]
Thanks for pointing out, makes complete sense.
I'm happy to fix it.
/assign
