### ISSUE TITLE
proxy/ipvs/README.md: passing mode:ipvs to `kubeadm init --config=file`

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubernetes#105534]
https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/ipvs/README.md#cluster-created-by-kubeadm says:

> Cluster Created by Kubeadm
> If you are using kubeadm with a configuration file, you have to add mode: ipvs below the kubeProxy field as part of the kubeadm configuration.
> 
> ...
> kubeProxy:
>  config:
>    mode: ipvs
>...
> before running
>
> `$ kubeadm init --config <path_to_configuration_file>`
> to specify the ipvs mode before deploying the cluster.

My understanding is, that `kubeProxy:` is not anymore correct.  The correct snippet would be:
```
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
```

**Comment by MadhavJivrajani** [comment]
/remove-kind bug
(typo in previous comment)
