### ISSUE TITLE
TestUpdatePodWithTerminatedPod flaking

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#105589]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestUpdatePodWithTerminatedPod

### Since when has it been flaking?

10/8 (when it was introduced in https://github.com/kubernetes/kubernetes/pull/105527)

### Anything else we need to know?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestUpdatePodWithTerminatedPod

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&exclude-non-failed-tests=50&width=20

Running with [stress](https://pkg.go.dev/golang.org/x/tools/cmd/stress) shows immediate failures:

```
go test -race -c ./pkg/kubelet
stress ./kubelet.test -test.v -test.run TestUpdatePodWithTerminatedPod
```

### Relevant SIG(s)

/sig node

**Comment by alculquicondor** [comment]
It's still flaking https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/105687/pull-kubernetes-unit/1448766205312634880

**Comment by liggitt** [comment]
this started flaking more on 3/21 - https://storage.googleapis.com/k8s-triage/index.html?date=2022-03-25&pr=1&text=podWorker%20state%20should%20not%20be%20marked%20terminated%20for%20a%20running%20pod

adding to the milestone for investigation

**Comment by liggitt** [comment]
cc @kubernetes/sig-node-test-failures
