### ISSUE TITLE
Publish apiserver ID

### ISSUE THREAD

**Issue by roycaihw** [kubernetes/kubernetes#105558]
### What would you like to be added?

A client can know the [ID](https://kubernetes.io/docs/tasks/administer-cluster/highly-available-control-plane/#api-server-identity) (and potentially other information like the public IP address) of the apiserver it connects to by visiting some page on the server. It could be a new metric, a new endpoint, etc. The design should be added to the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1965-kube-apiserver-identity/README.md).

### Why is this needed?

See conversation https://github.com/kubernetes/kubernetes/pull/95533#discussion_r517687292 and [beta graduation criteria](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1965-kube-apiserver-identity/README.md#alpha---beta-graduation)

**Comment by roycaihw** [comment]
/sig api-machinery
/assign
cc @aojea

**Comment by aojea** [comment]
is there any security problem with publishing an IP?
Endpoints are under RBAC control, is that enough?

**Comment by roycaihw** [comment]
/unassign
/assign @aojea 
Thanks for sending the PR!

**Comment by sftim** [comment]
```bash
curl -X GET https://localhost:443/api --header "Authorization: Bearer opensesame" --insecure
```
```
{
  "kind": "APIVersions",
  "versions": [
    "v1"
  ],
  "serverAddressByClientCIDRs": [
    {
      "clientCIDR": "0.0.0.0/0",
      "serverAddress": "192.0.2.42:443"
    }
  ]
}
```
It's already available, ish. I presume this is the structure where we could also publish a hostname if we wanted to.

**Comment by aojea** [comment]
/close

the id is present on the Lease object https://github.com/kubernetes/enhancements/commit/68afb6f8fc2f896ebf442170e3ae84e1f4e47188
