### ISSUE TITLE
Exposing multiple TCP/UDP services using a single LoadBalancer on K8s

### ISSUE THREAD

**Issue by matetiprashanth** [kubernetes/kubernetes#105501]
Trying to figure out how to expose multiple TCP/UDP services using a single LoadBalancer on Kubernetes. Let's say the services are ftpsrv1.com and ftpsrv2.com each serving at port 21.

Here are the options that I can think of and their limitations :

One LB per svc: too expensive.
Nodeport : Want to use a port outside the 30000-32767 range.
K8s Ingress : does not support TCP or UDP services as of now.
Using Nginx Ingress controller : which again will be one on one mapping:

**Comment by n4j** [comment]
@matetiprashanth Please put this question in Kubernetes Slack channel @ https://kubernetes.slack.com/.
Appropriate channels for this would be `kubernetes-users`, `sig-network`, `ingress-nginx-users`
