### ISSUE TITLE
How do Apiserver and Kubelet send commands to listen for pods messages

### ISSUE THREAD

**Issue by pipijiev12** [kubernetes/kubernetes#105597]
How do Apiserver and Kubelet send commands to listen for pods messages?
Where is this function implemented in the source code?

**Comment by MadhavJivrajani** [comment]
/sig node
/kind support
@pipijiev12 could you elaborate on what you mean by "commands" and "pod messages"?

**Comment by pipijiev12** [comment]
> /sig node /kind support @pipijiev12您能否详细说明“命令”和“pod消息”的含义？
![微信图片_20211011125507](https://user-images.githubusercontent.com/75164118/136735428-1e5deac6-246f-4227-abd9-5e5b724029a2.png)

As shown in the figure, Apiserver sends instructions to listen for POD information in Kubelet and then returns the POD status
