### ISSUE TITLE
Granularly skip storage test cases in upgrade testsuite

### ISSUE THREAD

**Issue by leiyiz** [kubernetes/kubernetes#105595]
right now due to the inability of only skipping storage test cases, the upgrade testsuite is kept untouched while we [skipped](https://github.com/kubernetes/kubernetes/pull/105052) other tests that will fail upon turning on the `CSIMigrationGCE` feature tag and will fail as a result.

We need to skip only the storage test cases with per-testcase granularity.

/sig storage
/kind cleanup

**Comment by NikhilSharmaWe** [comment]
@leiyiz I would like to collaborate. Could you please give me some direction on how can I proceed in solving this issue.
