### ISSUE TITLE
Make --validate default on for kubectl

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10555]
the --validate flag improves error messages for kubectl, for example by pointing out invalid fields.
Why is it off by default?

**Comment by erictune** [comment]
@bgrant0607

**Comment by bgrant0607** [comment]
See #7600 and #5889.

**Comment by JanetKuo** [comment]
We'll make `--validate` default on with a message telling the users how to turn it off.

**Comment by bgrant0607** [comment]
Concerns previously voiced here: https://github.com/kubernetes/kubernetes/pull/2517#issuecomment-64144899

We have to have a solution to this ~now. I don't care much about what the chosen solution is. I say we start with something trivial that mostly works and replace it with something better when we can.

Do any of the json parser-generators we've been investigating solve the schema validation problem?

cc @smarterclayton @wojtek-t

**Comment by wojtek-t** [comment]
I'm not aware of any.

**Comment by smarterclayton** [comment]
I'm not aware of any either.

On Tue, Aug 18, 2015 at 1:33 AM, Wojciech Tyczynski <
notifications@github.com> wrote:

> I'm not aware of any.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/10555#issuecomment-132076175>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
Yet another example of a support question due to lack of validation: #12862

**Comment by bgrant0607** [comment]
And another: #12835
