### ISSUE TITLE
Immutable Secrets are not renewed on recreation of pods

### ISSUE THREAD

**Issue by grassdionera** [kubernetes/kubernetes#105658]
### What happened?

I delete an immutable secret and applied it with new values.
Then i deleted the deployment/pods that are using this secret.
After applying the Deployments again, the Pod/Container is having the old secret values
When i use kubectl to get the secret values, i see the new values. 

### What did you expect to happen?

On Pod recreation the values for immutable secrets should be the newest that have been applied

### How can we reproduce it (as minimally and precisely as possible)?

Create an immutable Secret 
Create a Deployment with an ENV using this secret 
delete and reapply the immutable secret with new values
Delete and reapply the Deployment.
Exec into the Container and check the value of the ENV

### Anything else we need to know?

I have seen that sometimes the secrets are renewed on pod deletion, but i could not figure out on which conditions

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"archive", BuildDate:"2021-09-16T09:21:16Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
barebone ha setup
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux node1.bunny.dionera.dev 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
etcd (external)
etcdctl version: 3.5.0
API version: 3.5
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:33 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.10
  GitCommit:        8848fdb7c4ae3815afcc990a8a99d663dda1b590
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kubernetes-cni: 0.8.7-00
flannel network plugin 
</details>

**Comment by gjkim42** [comment]
This bug might be reproducible to the (secret, configmap) to env and (secret, configmap) to volume.

**Comment by gjkim42** [comment]
> What happens though is that kubelet is caching those "per-node" not "per-pod" (or deployment or whatever).
> So if you have any other pods that are actually referencing the old immutable secrets on the same node - then it's somewhat "working-as-intended".

Thank you @wojtek-t

OK, then this is not a bug.

Anyway, I think it is hard for many users to expect the fact that secrets are cached by name per node.
Maybe we need doc updates...? (If there aren't)

/unassign

**Comment by jlsong01** [comment]
@ehashman hello, I would like to contribute if docs update is need. Thanks.

**Comment by ehashman** [comment]
@jlsong01 feel free to submit a PR to the website!

**Comment by redbaron** [comment]
I have single pod using immutable configmap and restarting that pod with recreated configmap doesn't reflect new values
