### ISSUE TITLE
HPA Custom metrics tests are failing

### ISSUE THREAD

**Issue by krzysied** [kubernetes/kubernetes#105677]
### Which jobs are failing?

ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm
ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa

### Which tests are failing?

All Kubernetes e2e suite.[sig-autoscaling] [HPA] Horizontal pod autoscaling (scale resource: Custom Metrics from Stackdriver) 

### Since when has it been failing?

Last entry in prow show that Jul 16 13:55:27 was already failing, so longer than that.

### Testgrid link

https://k8s-testgrid.appspot.com/sig-autoscaling-hpa#gci-gce-autoscaling-hpa-cm

### Relevant SIG(s)

/sig

**Comment by leonardpahlke** [comment]
does not seem like the test is failing anymore 
/close
