### ISSUE TITLE
Add unit test for volume operation metrics

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#105616]
### What would you like to be added?

An attempt was made in https://github.com/kubernetes/kubernetes/pull/98089, but conflicted with a lot of deprecation activity at the same time. It looks like in the middle of that, we lost track of the effort to add a unit test.

@kubernetes/sig-storage-bugs 
cc @JornShen is this something you still have time to work on?

### Why is this needed?

Good to have UT coverage as e2es are more expensive to run.

**Comment by shuheiktgw** [comment]
@msau42 I'm trying to write unit tests for `OperationCompleteHook` but then I realized it is really hard since the value `timeTaken` is indeterministic. Are there any good ways to test it in this case?

**Comment by msau42** [comment]
> the value `timeTaken` is indeterministic. Are there any good ways to test it in this case?

Maybe the unit test can just check for a positive value. I think what's most important from the unit tests is that we make sure all the proper labels are set.

cc @gnufied for thoughts

**Comment by shuheiktgw** [comment]
@msau42 Thank you for your advice! I added unit tests so would you review the PR when you have time? 🙏 

https://github.com/kubernetes/kubernetes/pull/106138
