### ISSUE TITLE
Rethink P&F metrics

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#105683]
Forked from post-merge discussion on https://github.com/kubernetes/kubernetes/pull/103539

Copying the main comments here:

@MikeSpreitzer :
```
I checked the apiserver_flowcontrol_priority_level_request_count_watermarks histogram and it accumulates observations of the fraction (number of executing requests) / (concurrency limit) --- which we know is now not so meaningful, dividing a number of requests by a number of seats.

If we replace that histogram with one that accumulates observations of (number of seats occupied) / (concurrency limit) then we remove the reason I agreed to sink extra latency into QueueSet rather than just do it in the filter --- namely, the ability to have metrics that distinguish the two phases of execution. But it's more complicated, now that the extra latency can occupy more seats. BTW, I wonder if we goofed up something basic by making the virtual world track a different amount of work than what happens in the real world --- (total duration) times (seats occupied).
```

@wojtek-t 
```
@MikeSpreitzer - do we believe this metric was useful even before? I'm not entirely sure how I would suppose to use this metric.

Thinking about that - I'm wondering what metrics would be useful. Things that I might be interested about:

in the last N minutes 
- how much time (per priority-level) was consumed by which phase
- percentage of time (per priority-level) when some requests are waiting even though we're not (at least theoretically) occupying all seats with that PL.
```

@MikeSpreitzer 
```
Before generalizing width apiserver_flowcontrol_priority_level_request_count_watermarks histogram showed the extrema of occupancy. Observations of 1 showed that all seats were occupied. The apiserver_flowcontrol_priority_level_request_count_samples histogram showed not necessarily the extrema but a survey (even weighted over time). The watermarks histogram adds extrema that were missed in the sampling. I think they are meaningful even today, we just have to understand the denominator in the quotients. What we learned in this case is that the number of executing requests got as high as half of the concurrency limit.


I favor adding metrics like the apiserver_flowcontrol_priority_level_request_count samples and watermarks histograms but for seats instead of requests. At least for the executing phase. We do not have a configured limit on seats in a queue, so there is no denominator to use for that.

I favor also adding metrics about the two-phase structure. One direct metric of interest would be a histogram of observations of the dead space fraction of each request --- that is, (maxSeats - initialSeats) * initialDuration / (maxSeats * totalDuration).

We have the apiserver_flowcontrol_request_execution_seconds histogram already. That means there is a counter metric apiserver_flowcontrol_request_execution_seconds_sum that accumulates the sum of these times. I do not recall exactly which time is being observed right now, but we probably should split it by a label with values "initial" and "final". In PromQL, we can take the difference over the last N minutes and compare those differences to see the relative magnitude of the two phases.

We already have the apiserver_flowcontrol_request_wait_duration_seconds histogram showing the distribution of waiting times. Waiting only happens because of seat occupancy. Adding the dead space fraction histogram would describe that seat occupancy. Independently. With what I found in the testgrid infrastructure, namely just one metrics scrape at the end, that leaves correlation questions unanswered. But in real life there is no "end", operators have to monitor on-line using windowed queries. That can show correlation, coarsely.

If we wanted the fine-grained correlation you mention above, we would have to add tracking in queueSet of how many seats are occupied at the moment only in anticipation of the larger later width. And I am not sure that what we want to measure is simply the boolean condition of whether there is at least one request waiting due to anticipatory seat occupancy. I think it matters how many there are. And what we are really trying to get at is latency, so we may want to think harder.

But more fundamentally, I think we may have made a wrong turn by accounting work differently in the real and virtual worlds. In the virtual world, the code currently says that the work in a request is initialSeats * initialDuration + finalSeats * finalDuration. But in the real world, max(initialSeats, finalSeats) are occupied for all of initialDuration + finalDuration. In the original fair queuing technique, and in our work until we added the second phase of execution, the real and virtual worlds accounted the same amount of work to each request. The difference was just that in the virtual world the executions are interleaved in a hyper-fine way.
```

@MikeSpreitzer @tkashem 

/sig api-machinery
/priority important-longterm
/kind bug

**Comment by wojtek-t** [comment]
> I favor adding metrics like the apiserver_flowcontrol_priority_level_request_count samples and watermarks histograms but for seats instead of requests. At least for the executing phase. We do not have a configured limit on seats in a queue, so there is no denominator to use for that.

@MikeSpreitzer - given our metrics are still alpha - I wouldn't add new ones - we should probably update the existing ones

> I favor also adding metrics about the two-phase structure. One direct metric of interest would be a histogram of observations of the dead space fraction of each request --- that is, (maxSeats - initialSeats) * initialDuration / (maxSeats * totalDuration).

That SGTM

> We already have the apiserver_flowcontrol_request_wait_duration_seconds histogram showing the distribution of waiting times.

OK - I forgot about that. Yeah - that sounds fine to me.


> But more fundamentally, I think we may have made a wrong turn by accounting work differently in the real and virtual worlds. In the virtual world, the code currently says that the work in a request is initialSeats * initialDuration + finalSeats * finalDuration. But in the real world, max(initialSeats, finalSeats) are occupied for all of initialDuration + finalDuration. In the original fair queuing technique, and in our work until we added the second phase of execution, the real and virtual worlds accounted the same amount of work to each request. The difference was just that in the virtual world the executions are interleaved in a hyper-fine way.

max(initialSeats, finalSeats) are indeed occupied. But the work isn't happening there.
Even before that was some approximation, for two different requests taking the same latency, the amount of work happening underneath doesn't have to be the same (e.g. one object may be considerably smaller than the other, but latency might be dominated by etcd - but there are a bunch of other reasons too).

I understand your concerns - but for me they are somewhat theoretical (because of the reason above).

**Comment by MikeSpreitzer** [comment]
I think you meant "rethink".

**Comment by MikeSpreitzer** [comment]
Specifically regarding the existing request_count and potential seat_count metrics, here are some thoughts.
- The apiserver_flowcontrol_priority_level_request_count_samples and apiserver_flowcontrol_priority_level_request_count_watermarks histograms have a label distinguishing waiting from executing.  The values observed in these histograms are fractions, between 0 and 1, of the number of requests as a fraction of the maximum allowed by the current configuration.
- We could leave those alone and introduce an analogous pair of apiserver_flowcontrol_priority_level_seat_count_samples and apiserver_flowcontrol_priority_level_seat_count_watermarks histograms.  As noted before, we have no configuration that limits the number of seats waiting, so we would have to eschew that and just observe the seats occupied by executing requests.  We could either elide the label that distinguishes waiting from executing or always provide it with the executing value.  I tend to favor the latter for the sake of regularity and of preparation for that configuration that we have said we might add in the future.  
- for the request_count histograms of executing requests, the denominator is meaningful --- the limit on the number of seats occupied is also the limit on the number of requests executing --- but maybe this fraction is just not very interesting.  I would argue it is still interesting, because it together with the metrics of seats occupied gives information on the relation between the two.  But perhaps that would be better addressed directly, with something like a histogram of widths.  We could stop making the request_count observations for the executing phase.  That would leave us with the analogous question of whether to continue applying the label that will now have only one value (indicating waiting).

**Comment by wojtek-t** [comment]
> Making inconsistency between the work in the real and virtual worlds means that the dispatching in the real world --- which is based on the scheduling in the virtual world --- does not correspond to fairness in the real world.

I think we're mixing "dispatching" and "fairness" aspects here.

- For "fairness" - I don't think there is any discrepancy here. In virtual world, we're computing r(t) based on "initial-seats*duration+final-seats*addition-duration" which is supposed to be exactly the work that is done in the real world.
So (unless we're doing poor job in computing final-seats/additional-latency) - this actually is what we need.

- For "dispatching" - we're indeed blocking some seats during request processing if initial-seats<final-seats. But this is the part where we don't have full correspondence with real world anyway.

So I believe that we're fine with respect to fairness. And I wouldn't try to address the dispatching issue until we see that it's causing a real non-theoretical problem.


Regarding metrics per-se, I'm fine with introducing additional metrics per-seats (and using the executing label makes sense to me).

**Comment by MikeSpreitzer** [comment]
I am not sure what you mean by "But this is the part where we don't have full correspondence with real world anyway".  If you mean that the dead space (finalSeats-initialSeats during the first phase of execution) in the real world is where the notification work happens, I do not see that.  The notification work for a given request happens during the second phase of execution.  The dead space is seats held by the request in question and _not_ given to other flows.  It is unfair to not charge this against the flow that is holding those seats.
