### ISSUE TITLE
Run gosec static scan and address findings

### ISSUE THREAD

**Issue by timwaizenegger** [kubernetes/kubernetes#105662]
### Background
When I run the `gosec` static scan against kubernetes master there a lot of findings for a number of rules the scanner provides; e.g.
- `G101 (CWE-798): Potential hardcoded credentials`
- `G601 (CWE-118): Implicit memory aliasing in for loop.`
- `G103 (CWE-242): Use of unsafe calls should be audited`
- `G104 (CWE-703): Errors unhandled.`

A lot of those look like false positives but others could use a review. 

### How to reproduce
```
git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
gosec ./...

...

Summary:
  Gosec  : dev
  Files  : 7392
  Lines  : 1611992
  Nosec  : 0
  Issues : 4649
```

### What needs to be done?
- address findings by refactoring code or using "nosec" annotations on false positives

I'm mostly looking for feedback on those findings at this point:
- it looks like there is no CI integration for gosec; is that correct?
- is the kubernetes project using gosec at all?
- is there an effort ongoing/planned to address these findings?

### Why is this needed?

These findings can be an issue for enterprise adoption if static scans are mandatory in the organization.

Some of the findings are likely correct as well; actual vulnerabilities or bugs.

**Comment by dims** [comment]
cc @nehaLohia27 @PushkarJ

**Comment by BenTheElder** [comment]
It is not running in CI (SIG Testing here)

some related issues:
https://github.com/kubernetes/kubernetes/issues/99673
https://github.com/kubernetes/kubernetes/issues/100783
https://github.com/kubernetes/kubernetes/issues/103721

more generally kubernetes is not on state of the art linters, and it's a bit challenging to roll them out to a repo this large (it's not practical to patch them all at once, noisy to add `//ignore lint` comments everywhere, and our "known failing packages" pattern is clunky / a bit of effort to setup for each lint) + it's not something vendors seem keen to fund work on so far.

**Comment by PushkarJ** [comment]
Thinking about whether [CodeQL scanning](https://github.com/github/codeql-go) that is available as part of Github Repos be good alternative. I will ask the github admins, if we have it available for K8s org in general and if it can be enabled on repo level. 

/remove-lifecycle rotten

**Comment by BenTheElder** [comment]
FWIW https://github.com/kubernetes/kubernetes/issues/103721 and related issues in https://github.com/kubernetes/kubernetes/issues/105662#issuecomment-942806370 have since closed, you can now configure additional linters with https://github.com/kubernetes/kubernetes/blob/master/.golangci.yaml, the issue of existing failures remains but has options
