### ISSUE TITLE
[Flaky test] [sig-node] Kubelet should correctly account for terminated pods after restart

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#105686]
### Which jobs are flaking?

node-kubelet-serial

### Which tests are flaking?

Kubelet should correctly account for terminated pods after restart

### Since when has it been flaking?

Since test was created, flakes 10-20% of the time. Not entirely clear why, I haven't looked.

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&include-filter-by-regex=Kubelet%20should%20correctly%20account%20for%20terminated%20pods%20after%20restart

### Anything else we need to know?

/assign

### Relevant SIG(s)

/sig node

**Comment by ehashman** [comment]
> Introduced by #105527, maybe we should use `startTimeout` to replace `time.Minute`
> 
> https://github.com/kubernetes/kubernetes/blob/9804a83d8fd9eec4c20e75e73e11ffd4b370c6f0/test/e2e_node/restart_test.go#L176
> 
> See the log below, a pod becomes Succeed may exhaust tens of seconds

Yeah I only tested this locally and not in CI, it seems that in CI the pods take much longer. Timings just need to be tweaked.

**Comment by ehashman** [comment]
/reopen

still a number of flakes since the attached PR merged, I don't think that fixed it.

**Comment by 249043822** [comment]
@ehashman https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&include-filter-by-regex=Kubelet%20should%20correctly%20account%20for%20terminated%20pods%20after%20restart
from this link, I see all suites passed, which flakes do you mean?

**Comment by pacoxu** [comment]
I see this failure in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106408/pull-kubernetes-node-kubelet-serial/1459822195130765312/.

**Comment by 249043822** [comment]
so this problem should have been fixed by https://github.com/kubernetes/kubernetes/pull/106371

**Comment by ehashman** [comment]
From gubernator:

### Failure cluster [f3393094bdefc50e4d1f](https://go.k8s.io/triage#f3393094bdefc50e4d1f)

##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/restart_test.go:152
Nov  1 10:28:15.543: Failed to run sufficient restartNever pods, got 1 but expected 2
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```
#### Recent failures:
[11/14/2021, 6:36:14 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1459892921477107712)
[11/13/2021, 6:35:14 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1459530277628940288)
[11/12/2021, 10:35:13 PM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1459409480411254784)
[11/12/2021, 6:34:13 PM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1459348830074966016)
[11/12/2021, 10:33:58 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1459227970106298368)


In all cases, it's timing out. I'll try upping the startTimeout.

**Comment by ehashman** [comment]
/reopen

still flaking

**Comment by ehashman** [comment]
Luckily the kubelet log is clear as to what's going on. From https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1461404704922669056/artifacts/n1-standard-2-cos-93-16623-39-21-991516df/kubelet.log (flake https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1461404704922669056) 

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/restart_test.go:146
Nov 18 19:38:37.481: Failed to run sufficient restartNever pods, got 1 but expected 2
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113
```

```
I1118 19:37:05.003842   43953 config.go:383] "Receiving a new pod" pod="restart-test-4322/test-a693eea8-a137-471f-bc38-0768abf47fa5"
I1118 19:37:05.003899   43953 kubelet.go:2063] "SyncLoop ADD" source="api" pods=[restart-test-4322/test-a693eea8-a137-471f-bc38-0768abf47fa5]
I1118 19:37:05.003930   43953 topology_manager.go:200] "Topology Admit Handler"
I1118 19:37:05.003948   43953 manager.go:914] "Looking for needed resources" needed=1 resourceName="cpu"
I1118 19:37:05.004036   43953 predicate.go:145] "Predicate failed on Pod" pod="restart-test-4322/test-a693eea8-a137-471f-bc38-0768abf47fa5" err="Node didn't have enough resource: cpu, requested: 1000, used: 1100, capacity: 2000"
```

The test should work fine if we drop the CPU request a bit, let me tweak it to make up for the possible extra 100m scheduled. I'm not sure what's causing that (aren't these tests serial? what the heck is getting scheduled) but we should be resilient to it.

Also, https://github.com/kubernetes/kubernetes/pull/105926/files#r752688249 needs to be fixed. This test will no longer detect the regression it was designed to show after that change. I will revert it and also fix the resource requirements and that should fix this test.

**Comment by ehashman** [comment]
/milestone v1.23

need to fix this before test freeze
