### ISSUE TITLE
Abbreviations

### ISSUE THREAD

**Issue by mhash17** [kubernetes/kubernetes#105638]
### What would you like to be added?

Wouldn't it be useful to provide a consistent abbreviation 'policy'?

Examples:
- for deployments it is deploy instead of intuitively 'dep' or 'depl' (that 'loy' is a long way on the keyboard)
- limitranges > limit instead of lr
- networkpolicies > netpol instead of np
- resourcequotas > quota, instead of rq

That's just an idea while working with kubectl ... 

### Why is this needed?

Efficiency.

/sig usability

**Comment by eddiezane** [comment]
These are declared in the storage registries. https://cs.k8s.io/?q=ShortNames&i=nope&files=%5Epkg%2Fregistry%2F.*%2Fstorage.go%24&excludeFiles=&repos=kubernetes/kubernetes

Tab completion is pretty complete now and will be getting better now that we've switch to Go powered completion.

Looks like closest thing to a policy is this https://github.com/kubernetes/kubernetes/issues/86138#issuecomment-564321469. I agree with Jordan that we'd need to see more demand for a one way door decision like this.
