### ISSUE TITLE
hack/{update,verify}-vendor are broken due to coreos/bbolt rename

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#105618]
### What happened?

The `hack/{update,verify}-vendor.sh` scripts seem to broken. On a fresh checkout of k/k

```
$ go version
go version go1.17.1 linux/amd64
```

```
$ hack/verify-vendor.sh
+++ [1011 16:37:56] logfile at /tmp/update-vendor.bM31/update-vendor.log
+++ [1011 16:37:56] go.mod: update staging references
An error has occurred. Please see more details in /tmp/update-vendor.bM31/update-vendor.log
Removing /usr/local/google/home/porterdavid/go/src/k8s.io/kubernetes/_tmp/kube-vendor.Bn64kk
```

* `update-vendor.log` - https://gist.github.com/cf9fde5bd9ecd2dbfc90a0af49b71acc

The issue seems to be 

```
go: k8s.io/kubernetes/kubernetes/cluster/images/etcd/migrate imports
	go.etcd.io/etcd/clientv3 tested by
	go.etcd.io/etcd/clientv3.test imports
	github.com/coreos/etcd/auth imports
	github.com/coreos/etcd/mvcc/backend imports
	github.com/coreos/bbolt: github.com/coreos/bbolt@v1.3.6: parsing go.mod:
	module declares its path as: go.etcd.io/bbolt
	        but was required as: github.com/coreos/bbolt
```

### What did you expect to happen?

For `hack/verify-vendor.sh` to succeed. 

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Kubernetes version

n/a

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
I can't reproduce this in my normal dev env or a clean checkout, and CI seems to be passing at HEAD of master on new PRs...
