### ISSUE TITLE
Wrong udp conntrack entries are populated after a pod is killed using --force

### ISSUE THREAD

**Issue by pmarag** [kubernetes/kubernetes#105657]
### What happened?

On a single node kubernetes cluster, deployed using minikube: 

[root@control-plane ~]# kubectl get nodes -o wide
NAME                              STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                               KERNEL-VERSION          CONTAINER-RUNTIME
control-plane.minikube.internal   Ready    control-plane,master   46h   v1.22.2   10.45.253.76   <none>        Red Hat Enterprise Linux 8.4 (Ootpa)   4.18.0-305.el8.x86_64   docker://20.10.6

We have two pods handling SIP traffic. One pod is sending an OPTIONS to the other on port 5060 using a service.

ea1-tasftapp   ClusterIP   10.97.122.198    <none>        5060/UDP            46h

tas-sip-b2bua-tasftapp-69c574b88c-7nvsm   1/1     Running   0          13m   10.244.0.35   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

Connection on conntrack looks like this: 

udp      17 119 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 src=10.244.0.35 dst=10.244.0.24 sport=5060 dport=5060 [ASSURED] mark=0 use=1

If we delete the pod behind the ea1-tasftapp service by using kubectl delete pod, a new one is created:

tas-sip-b2bua-tasftapp-69c574b88c-7rdgm   1/1     Running   0          47s   10.244.0.36   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

and conntrack is updated correctly: 

udp      17 119 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 src=10.244.0.36 dst=10.244.0.24 sport=5060 dport=5060 [ASSURED] mark=0 use=1

If we delete the pod using force, a new pod is created:

tas-sip-b2bua-tasftapp-69c574b88c-gvx9g   1/1     Running   0          22s   10.244.0.37   control-plane.minikube.internal   <none>           <none>
tas-sip-b2bua-tassnf-78fd487c7d-t9b2j     1/1     Running   0          45h   10.244.0.24   control-plane.minikube.internal   <none>           <none>

but the conntrack is updated using the node ip instead of the new pods. Due to this, connectivity between the two pods doesn't work.

udp      17 29 src=10.244.0.24 dst=10.97.122.198 sport=5060 dport=5060 [UNREPLIED] src=10.97.122.198 dst=10.45.253.76 sport=5060 dport=9817 mark=0 use=1

Problem is solved only by restarting the pod initiated the connection (tas-sip-b2bua-tassnf-78fd487c7d-t9b2j) or by restarting kube-proxy. 

Issue appears only on 1.22 kubernetes version. On version 1.21 everything is working properly. 

### What did you expect to happen?

After pod is killed, a new conntrack entry should be created towards the IP of the new pod. 

### How can we reproduce it (as minimally and precisely as possible)?

Having udp connectivity between a pod and a service and force delete the pod where the traffic is routed through the service. 

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

On premises deployment. 

### OS version

NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"

Linux control-plane.minikube.internal 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed

### Related plugins (CNI, CSI, ...) and versions (if applicable)

[root@control-plane ~]# calicoctl version
Client Version:    v3.20.2
Git commit:        dcb4b76a
Cluster Version:   v3.20.2
Cluster Type:      k8s,kdd,bgp,kubeadm

**Comment by aojea** [comment]
most of the conntrack issues with UDP were fixed, I'm surprised this worked before and not now, can you run kube-proxy with verbosity 7 and attach the logs after reproduce the issue (please share more or less the time  when you delete the pod and the name of the pods so I can find them easily in the logs)

**Comment by pmarag** [comment]
@aojea I have the logs exactly from when I start our test scenario and we deleted the pod. The verbosity is 9 hope this is not a problem. Please find them attached!  I attach also the same exactly test on kubernetes 1.21 (where everything works as expected). I can see some differences but to be honest, wasn't able to find what exactly is creating the issue.
[kube-proxy-kubernetes-1.21.txt](https://github.com/kubernetes/kubernetes/files/7346276/kube-proxy-kubernetes-1.21.txt)
[kube-proxy-kubernetes-1.22.log](https://github.com/kubernetes/kubernetes/files/7346280/kube-proxy-kubernetes-1.22.log)

Since we can always replicate the issue, I can provide whatever else is needed/may help on the troubleshooting.

**Comment by aojea** [comment]
on 1.22 

> I1012 10:43:50.515733       1 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 1h0m0s
> I1012 10:43:56.533279       1 config.go:260] Calling handler.OnEndpointSliceUpdate
> I1012 10:43:56.533356       1 endpointslicecache.go:358] Setting endpoints for "tas/ea1-tasftapp:sip" to [10.244.0.29:5060]
> I1012 10:43:56.533376       1 endpointslicecache.go:358] Setting endpoints for "tas/ea1-tasftapp:sip" to [10.244.0.29:5060]
> I1012 10:43:56.533429       1 proxier.go:845] "Syncing iptables rules"

on 1.21

> I1012 12:54:20.458590       1 config.go:260] Calling handler.OnEndpointSliceUpdate
> I1012 12:54:20.906930       1 config.go:260] Calling handler.OnEndpointSliceUpdate
> I1012 12:54:20.906992       1 endpointslicecache.go:354] Setting endpoints for "tas/ea1-tasftapp:sip" to [10.244.0.15:5060]
> I1012 12:54:20.907097       1 proxier.go:841] "Stale service" protocol="udp" svcPortName="tas/ea1-tasftapp:sip" clusterIP="10.110.43.106"
> I1012 12:54:20.907114       1 proxier.go:857] "Syncing iptables rules"


on 1.21 it deletes the conntrack entry for service

> I1012 12:54:20.989553       1 proxier.go:1658] "Deleting conntrack stale entries for Services" ips=[10.110.43.106]
> I1012 12:54:20.989584       1 conntrack.go:66] Clearing conntrack entries [-D --orig-dst 10.110.43.106 -p udp]

on 1.22 doesn't detect the service stale :thinking:  and call the slicecache twice but the handler once

@danwinship does this ring a bell?

**Comment by aojea** [comment]
> If we delete the pod behind the ea1-tasftapp service by using kubectl delete pod, a new one is created:
> If we delete the pod using force, a new pod is created:

@pmarag do I read it correctly and the problem only happens when using --force to delete the pod, without force it works well?

**Comment by aojea** [comment]
I can't reproduce it :/

Install an UDP service with a service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: MyApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyApp
  template:
    metadata:
      labels:
        app: MyApp
    spec:
      containers:
      - name: agnhost
        image: k8s.gcr.io/e2e-test-images/agnhost:2.21
        args:
          - netexec
          - --http-port=80
          - --udp-port=80
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - protocol: UDP
      port: 80
      targetPort: 80
```

Get the new service IP
```
kubectl get service
NAME               TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
kubernetes         ClusterIP   10.96.0.1      <none>        443/TCP        3d21h
nodeport-service   NodePort    10.96.73.155   <none>        80:31409/UDP   13m
```
Run another pod polling the udp service constantly
```
kubectl run test -it --image k8s.gcr.io/e2e-test-images/agnhost:2.21 --command -- ash
while true; do echo "hostname" | nc -u -w 1 10.96.73.155 80 ; sleep 1;  done
```

In another terminal watch the conntrack entries inside the node
```
watch -c "conntrack -L | grep 10.96.73.155"
```

After doing `kubectl delete --force` to the service pod, the conntrack entries are correct and the app keeps working

**Comment by aojea** [comment]
/triage accepted
I can reproduce it, there is definitively something odd here

**Comment by aojea** [comment]
great catch, this is something worse than the udp conntrack problem

**Comment by aojea** [comment]
and cherry=pick to 1.22 branch https://github.com/kubernetes/kubernetes/pull/106239
