### ISSUE TITLE
Modify Access Modes aliases

### ISSUE THREAD

**Issue by Kartik494** [kubernetes/kubernetes#105602]
`ReadWriteOnce` alias `RWO` is an ambiguous [mention](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)  in access modes, as mention in  documentation that the volume can be mounted as read-write by a single node . But `ReadWriteOnce`  PV can be accessed from multiple pods when those pods are running on the same node . So here i am proposing an idea to modify the access modes aliases So that it would be more specific . 

**Current Aliases**
RWO - ReadWriteOnce
ROX - ReadOnlyMany
RWX - ReadWriteMany
RWOP - ReadWriteOncePod

**Proposed Aliases**
RWON - ReadWriteOnceNode
ROXN - ReadOnlyManyNode
RWXN- ReadWriteManyNode
RWOP - ReadWriteOncePod

**Comment by Kartik494** [comment]
cc @YuikoTakada

**Comment by YuikoTakada** [comment]
Thank you for posting issue.
Is `ReadWriteOnceNone` right? I think you wanted to write `ReadWriteOnceNode` .
Thanks!

**Comment by Kartik494** [comment]
@YuikoTakada Yes, Aliases for `ReadWriteOnce` ,  `ReadOnlyMany`  ,`ReadWriteMany` Needs to be changed in docs and code.

**Comment by Kartik494** [comment]
cc @xing-yang

**Comment by xing-yang** [comment]
@Kartik494 I think the reason to keep the RWO naming is to support backward compatibility.

CC @chrishenzie @msau42

**Comment by Kartik494** [comment]
@xing-yang @chrishenzie Thanks for your input on this.

**Comment by YuikoTakada** [comment]
@Kartik494 Could do you please close this issue?

**Comment by Kartik494** [comment]
> @Kartik494 Could do you please close this issue?

/close
