### ISSUE TITLE
Topology spreading can become imbalanced during deployment rollout

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#105661]
### What happened?

When restarting a rolling deployment, the new pods can end up in imbalanced topologies that violate their specified `MaxSkew`. This is due to interference from the old, `Terminating` pods in the scheduler's topology size calculation. At scheduling time, the constraints are technically satisfied. However, once the old pods are removed, the topology size difference can be greater than `MaxSkew`

/sig scheduling

### What did you expect to happen?

Topology spread constraints should be valid during and after a deployment rollout

### How can we reproduce it (as minimally and precisely as possible)?

Create a Kind cluster with the following config for 2 worker nodes:
```yaml
# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "topology.kubernetes.io/zone=A"
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: JoinConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "topology.kubernetes.io/zone=B"
```

Next, create a sample deployment to take up some cluster utilization (this may not be necessary)
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fat
  name: fat
  namespace: default
spec:
  replicas: 20
  selector:
    matchLabels:
      app: fat
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fat
    spec:
      nodeSelector:
        kubernetes.io/hostname: "kind-worker2"
      containers:
        - command:
            - sh
            - -c
            - "trap : TERM INT; sleep 9999999999d & wait"
          image: alpine
          imagePullPolicy: Always
          name: alpine
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

Finally, create the required deployment with topology spread constraints:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: required
  name: required
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: required
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: required
    spec:
      containers:
        - command:
            - sh
            - -c
            - "trap : TERM INT; sleep 9999999999d & wait"
          image: alpine
          imagePullPolicy: Always
          name: alpine
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: required
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
```

Once all pods are running, the required pods should initially be spread on different nodes:
```
$ kubectl get po -o wide
required-7d47b8d88b-kxqnv   1/1     Running   0          3s      10.244.1.25   kind-worker2   <none>           <none>
required-7d47b8d88b-wd5k5   1/1     Running   0          3s      10.244.2.5    kind-worker    <none>           <none>
```

However, restarting the deployment causes them to end up unbalanced:
```
$ kubectl rollout restart deployment.apps/required
deployment.apps/required restarted

$ kubectl get po -o wide
required-784d4c6d48-p8jnj   1/1     Running   0          43s   10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running   0          45s   10.244.2.3    kind-worker    <none>           <none>
```

By checking the pods during the rollout, you can see they are scheduled in accordance with the topology constraints to include Terminating nodes into the calculation. For example:
```
$ kubectl get po -o wide
required-595b4ddfc-8hpmz    1/1     Running             0          46s   10.244.1.22   kind-worker2   <none>           <none>
required-595b4ddfc-bh2tf    1/1     Terminating         0          46s   10.244.2.2    kind-worker    <none>           <none>
required-784d4c6d48-p8jnj   0/1     ContainerCreating   0          1s    <none>        kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running             0          3s    10.244.2.3    kind-worker    <none>           <none>

$ kubectl get po -o wide
required-595b4ddfc-8hpmz    0/1     Terminating   0          50s   10.244.1.22   kind-worker2   <none>           <none>
required-784d4c6d48-p8jnj   1/1     Running       0          5s    10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running       0          7s    10.244.2.3    kind-worker    <none>           <none>

$ kubectl get po -o wide
required-784d4c6d48-p8jnj   1/1     Running   0          43s   10.244.2.4    kind-worker    <none>           <none>
required-784d4c6d48-pdvjt   1/1     Running   0          45s   10.244.2.3    kind-worker    <none>           <none>
```

This leads to the imbalanced cluster state.

### Anything else we need to know?

This may be intentional, and there are existing solutions for this issue. For example, the [Descheduler](https://github.com/kubernetes-sigs/descheduler#removepodsviolatingtopologyspreadconstraint) can be run to re-balance the domains.

Alternatively, a soft pod anti-affinity can be added to help steer pods away from each other. This is not a guarantee though.

### Kubernetes version

<details>

Reproduced as far back as 1.19

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by damemi** [comment]
/cc @alculquicondor @Huang-Wei @ahg-g 
this could actually be more difficult than just excluding terminating pods. When I did a rolling deployment with a *hard* antiaffinity (just to test), the old pods did not go to terminating until the new pods were scheduled.

So, from the scheduler's point of view, there is no difference between an "old" pod and a "new" pod in a deployment since the old pods are still running at the time of scheduling. Technically, the spreading is working perfectly in this way. But functionally this is an issue

**Comment by ahg-g** [comment]
So there are two cases:

case 1) default spreading: we should be handling that correctly already since we look at the owner, which in this case is the ReplicaSet, so spreading should be limited to the pods of the ReplicaSet.

case 2) explicitly setting the topology spread constraints: I don't think we should do anything implicit here, we had the same case for one of GKE customers, and the advise was for them to set a version label and update it each time they do a rolling update. But I can see that some set of users will be surprised either way.

**Comment by damemi** [comment]
I don't have the details, but the support team that reported this to us says their users tried the label trick and it wasn't successful. They also said that was actually already documented. I can try to get more details

**Comment by alculquicondor** [comment]
Opt-out wouldn't be backwards compatible, but I don't expect it to break users, so it might be fine. Of course this requires a KEP.

**Comment by denkensk** [comment]
I draft a proposal to solve this. It would be grateful if you could review and give comments. @Huang-Wei @ahg-g @alculquicondor @damemi
https://docs.google.com/document/d/12F1YXsvy4SmumPiL3LHMLnuMHvyMqSzDqF-L9J37ZfA/edit?usp=sharing

**Comment by ahg-g** [comment]
Thanks, left few comments on the doc.
