### ISSUE TITLE
Kubelet's memory capacity and dynamic RAM in Hyper-V

### ISSUE THREAD

**Issue by ABaboshin** [kubernetes/kubernetes#105613]
### What happened?

I'm creating a kubernetes cluster on VMs in Hyper-V with dynamic RAM. The kubelet is taking not all available RAM (max ram of the VM) but only the allocated amount at the time of starting. Moreover the available RAM will be not recalculated during the running

### What did you expect to happen?

I'd like to have an ability either to force kubelet to calculated all the available dynamic RAM or to recalculate the available RAM from time to time.

### How can we reproduce it (as minimally and precisely as possible)?

Intall Ubuntu 20.04 on Hyper-V (Windows Server 2016), set dynamic RAM 8192-32768MB. Deploy kubelet there => the capacity is around 8 GB and will be never go up to 32 GB.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Custom Hyper-V VM
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux vmserversuse6.complevo.berlin 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Zetanova** [comment]
could u resolve it, beside setting the startup memory to max?

**Comment by Amith211** [comment]
/reopen

I am running into this issue and supporting dynamic memory would be a really useful feature.
