### ISSUE TITLE
Pod looses network connection (connection refused errors) during graceful shutdown period

### ISSUE THREAD

**Issue by nilesh-telang** [kubernetes/kubernetes#105703]
### What happened?

Hi,

Our backend infrastructure uses Kubernetes pods to perform analysis of data. As the flow of data increases and decreases through the day, the Kubernetes auto scaler scales up and scales down the pods.

The analysis operation on a single workload can take up to six minutes. To enable successful completion of in flight scan operation, the pods
1. have a terminationGracePeriodSeconds set to 360 seconds
2. capture the SIGTERM event and prevent the pod from accepting new requests
    ```            
            SpringApplication springApplication = new SpringApplication(ProductApplication.class);
            springApplication.addListeners(new GracefulShutdownListener());
            
            GracefulShutdownListener -> onApplicationEvent(ContextClosedEvent event) 
            1. Prevent new requests from being sent
            2. Sleep for 6 minutes
    ```

The issue is that thought the pods are waiting for 6 minutes to complete in flight operation, these operation fail in outward network communication. Thus the pod gets a `Connection Refused` error when communicating with SNS in the graceful shutdown phase.

Investigation reveal that pods are failing in external network communication with multiple applications during the 'graceful shutdown' phase.

I have gone through multiple tickets  /documents in a similar area
1. https://github.com/kubernetes/kubernetes/issues/44956
2. https://github.com/ardanlabs/service/issues/189
3. https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/

One comment on the same area seems to be https://github.com/kubernetes/kubernetes/issues/86280#issuecomment-583173036

I am raising this ticket as we require the ability to create new external connections (SNS) during graceful shutdown.

Primarily I see in the document  https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/, that a B flow is started on pod deletion, which removed pods from ip tables. It seems to me that this may result in the pod not being able to create new network connections. If this is the case we would need a mechanism to delay the B flow until the grace period is done.

I am not sure if sleeping in the pre-stop hook is the recommended mechanism to prevent pods from loosing network connection during the graceful shutdown phase.

### What did you expect to happen?

Any Kubernetes pod during it's graceful shutdown period should have unrestricted access to required resources (network) and the ability to create new connections. This ability need not be by default and could also be by setting a configuration.

### How can we reproduce it (as minimally and precisely as possible)?

1. Start a pod which perpetually creates a new connection with and updates an external entity
2. Terminate the pod manually

Connection refused should be seen in attempts to create new connection
Connection refused error may be seen for readiness probe.

We have not found this to always be reproducible in our test clusters, however can be seen very frequently in our clusters server continuous data. 

### Anything else we need to know?

The evidences that we can see indicating that pod is loosing ability to communicate with external components
1. Connection refused error to multiple components, during graceful shut down phase.
2. pod events display connectino refused event for readiness proble a minute after shutdown

```LAST SEEN   TYPE      REASON              OBJECT                      MESSAGE
38m         Normal    Killing             pod/scan-434f242-fr23e   Stopping container xyz
38m         Normal    Killing             pod/scan-434f242-fr23e   Stopping container pqr
38m         Normal    Killing             pod/scan-434f242-fr23e   Stopping container abc
38m         Warning   FailedPreStopHook   pod/s434f242-fr23e   Exec lifecycle hook ([]) for Container "abc" in Pod "scan-434f242-fr23e_dss(19451a4f-2w32-4221-we32-4a3b0b169a7c)" failed - error: command '' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: \"\": executable file not found in $PATH: unknown\r\n"
37m         Warning   Unhealthy           pod/scan-434f242-fr23e   Readiness probe failed: Get http://10.111.2.71:8080/actuator/health/readiness: dial tcp 10.203.9.71:8080: connect: connection refused
33m         Warning   Unhealthy           pod/scan-434f242-fr23e   Readiness probe failed: Get http://10.111.2.71:4191/ready: dial tcp 10.203.9.71:4191: connect: connection refused
38m         Warning   Unhealthy           pod/scan-434f242-fr23e   Liveness probe failed: Get http://10.112.2.71:4191/live: dial tcp 10.111.2.71:4191: connect: connection refused
38m         Warning   Unhealthy           pod/scan-434f242-fr23e   Liveness probe failed: Get http://10.111.2.71:8080/actuator/health/liveness: dial tcp 10.203.9.71:8080: connect: connection refused```

This does not always reproduce.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.17-eks-087e67", GitCommit:"087e67e479962798594218dc6d99923f410c145e", GitTreeState:"clean", BuildDate:"2021-07-31T01:39:55Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker container
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> Any Kubernetes pod during it's graceful shutdown period should have unrestricted access to required resources (network) and the ability to create new connections. This ability need not be by default and could also be by setting a configuration.

pods can create connections during shutdown period

a different topic is that if you are trying to connect to a service, the endpoints that are termination are removed from the service, so all the connections to that service will go to the endpoints that are ready, if there are no endpoints those connections will be refused


/kind support

**Comment by nilesh-telang** [comment]
Hi,

Sorry for the delay in updating the status. I have run multiple tests to verify the behavior. I have specified below the results of the tests and what I plan to attempt next. 

To summarize, unfortunately in all the tests that I ran, connection to external components (SNS, Kafka, Redis) failed during the graceful shutdown period. I will be running further tests to verify if there is a work around to this issue.

TEST RESULTS
---

### 1. Use "keep alive" TCP connection for SNS
> **TEST**
> Convert the connection to SNS to be a "keep alive" connection and verify if SNS updates can be made during grace period.
>
> **RESULT**
>  SNS updates failed with ConnectionRefused despite connection being set as "keep alive" connection
>
### 2. Perform a sleep in the pre-stop phase
> **TEST**
> Pre-stop invokes an end point on the container being terminated is invoked. This end point sleeps for 5 minutes (graceful shutdown period) before returning.
>
> **RESULT**
>  The end point was successfully invoked and it also return successfully after 5 minutes indicating this active connection was successfully completed. However all SNS updates in these 5 minutes failed with ConnectionRefused suggesting that new connections cannot be created.
### 3. Test connectivity with other other components during grace period
> **TEST**
> Test connectivity with Redis and Kafka during grace period
>
> **RESULT**
> Test invocation on Redis and Kafka also failed during the graceful shutdown period suggesting, new network connections are not being made and the issue is not specific to SNS.

NEXT TESTS
---
1.  Make periodic Redis invocations (every ten seconds) during shutdown to see at what point connection is lost.
2. Attempt to invoke Kafka / Redis in the pre-stop script, to confirm if connection can be made from this location.
3. Attempt to invoke Kafka / Redis in side car container, to confirm if connection can be made from this location.

**Comment by khenidak** [comment]
do you fail/stop endpoint responding to probe when you get sigterm (along with stopping the main app endoint)?

**Comment by nilesh-telang** [comment]
Hi @khenidak,

Thank you for bringing up this point. 

To summarize, the code uses `Spring Boot Actuator` probes (/actuator/health/liveness and /actuator/health/readiness) and we currently do not have code to influence the results of the probes during shutdown. However in production we can see that the probes are failing with `connection refused` immediately after the shutdown is initiated. The probes are not passing for the duration of the graceful shutdown period, which theoretically may be expected. 

Could you please let me know if you believe the failure of these probes could be influencing actions that cause the pod to loose network connectivity before the graceful shutdown period?

More details have been shared below if required.


## Pod Shut Down Logic
When a pod shut down is initiated we do the following
1. Identify the initiation of the shutdown, either by
> * capturing the event in `onApplicationEvent(ContextClosedEvent event)`
>    This is the default code behaviour
> * capturing the event in a pre-stop-hook
>    This option was introduced to test if sleeping in pre-stop helps address the issue
2. Update an internal state of the pod to "NotReady" so that no new requests are received by the pod
> When the internal state of a pod is set to "NotReady" our routing logic no longer directs request to the pod.
3. Sleep for 5 minutes
> * The 5 minutes is intended to enable the the pod to complete all pending tasks
> * The terminationGracePeriodSeconds has been set to 6 minutes, which ensures sig-kill is not received within 5 

## Probe Logic - During Shut Down

The probes that are used by the pod are
* /actuator/health/liveness
* /actuator/health/readiness

The code does not add logic to influence the result of these probes during the graceful shutdown phase.

When I investigated the pod events for scenarios where we saw network failures, we found that both Readiness probe and Liveness probe were failing with connection refused.
```
57m         Warning   Unhealthy           pod/<podname>   Readiness probe failed: Get http://<pod ip>:4191/ready: dial tcp <pod ip>:4191: connect: connection refused
57m         Warning   Unhealthy           pod/<podname>   Liveness probe failed: Get http://<pod ip>:8080/actuator/health/liveness: dial tcp <pod ip>:8080: connect: connection refused
```

**Comment by matthewbyrne** [comment]
@nilesh-telang , we're seeing this same issue, on AWS only. I've successfully communicated externally (dig www.google.com) during a graceful termination period of my deployment on GKE and self hosted kubernetes clusters.

**Comment by caseydavenport** [comment]
> I believe that this explains what we are observing. During the pod shutdown, I believe the pod is removed from the endpoint object. At this point the pod does not have an active TCP connection with SNS, and thus the connection with SNS is not retained. The fact that pod is removed from the end point may be the reason, that pod is unable to make further communications with SNS.

I missed this earlier, but this analysis isn't quite right - the iptables that get removed during shutdown are for the Service which allows inbound traffic to the terminating endpoint. Those will be removed because during termination, new connections are not directed to the terminating endpoint. However, the iptables that are removed shouldn't impact _outgoing_ connections from the pod to other network entities, which is what I believe you're describing in this issue.

> Also, kubelet and docker logs showing the time sequence of when the container sandbox stop request begins and when it finally ends might help. There are also CRI operation timeouts that could be in play here, but kubelet and docker logs will help figure that out.

I think we still need kubelet and container runtime logs, any perhaps AWS VPC CNI plugin logs in order to go deeper on this one. From the sounds of it, liveness probes start failing directly from the local kubelet -> pod IP, which suggests fairly strongly that CNI is tearing down the pod's networking before the termination grace period is over. Services aren't relevant in that path, so seems unlikely to be a services issue.

**Comment by caseydavenport** [comment]
> Could you please let me know if you believe the failure of these probes could be influencing actions that cause the pod to loose network connectivity before the graceful shutdown period?

Yes - I think it could be. If the liveness probes fail consistently, I believe the kubelet will terminate the pod before reaching the full termination grace period.

In addition to the CNI theory above, you should double-check that your liveness probes are being served throughout termination even after the SIGTERM. That seems to be another likely culprit here. Maybe try terminating a pod and see if the probe is still accessible from within the pod's own netns.

**Comment by nilesh-telang** [comment]
Hi @caseydavenport thank you for the detailed explanation and I agree with the points that you have specified. 

> From the sounds of it, liveness probes start failing directly from the local kubelet -> pod IP, which suggests fairly strongly that CNI is tearing down the pod's networking before the termination grace period is over. Services aren't relevant in that path, so seems unlikely to be a services issue.

Considering that we have not been able to reproduce this issue on any of our staging clusters, I too suspect that the issue may not be at the service level or in the kubernetes algorithm during shutdown.  At this point I am suspecting that the root cause could be that AWS is reclaiming the spot instance assigned to the pod. Based on AWS documentation, spot instances are reclaimed 2 minutes after sending an interruption notice (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/spot-instance-termination-notices.html) and service logs also indicate that network connectivity is lost two to three minutes after the pod shutdown is initiated. 

I will look into AWS VPC CNI plugin logs and communicate with Amazon support to identify if indeed pods that are facing the issue have received interruption notice for the spot instance. 
 
> In addition to the CNI theory above, you should double-check that your liveness probes are being served throughout termination even after the SIGTERM. That seems to be another likely culprit here. Maybe try terminating a pod and see if the probe is still accessible from within the pod's own netns.

I attempted to reproduce this issue in staging and here post manually terminating a pod, on staging, we see the pod alive and with network connectivity for its graceful shutdown time (five minutes). From my knowledge liveliness probes are being served through this period, however I will re-confirm this.

Thank you again for the for the pointers. I will try to retrieve the
 1. kubelet logs
 2. container runtime logs 
 3. AWS VPC CNI plugin logs
for a pod on which the issue is being faced.

Thank you @matthewbyrne for the update. I do not know if the system on which you are noticing this behavior, also uses AWS spot instances, however I will be investigating this are next and will update the ticket with my findings.

**Comment by matthewbyrne** [comment]
Hi @nilesh-telang , we've resolved the issue on our cluster. We're using Calico CNI, which had a [bug](https://github.com/projectcalico/calico/issues/4518) in it. After upgrading our Calico version our terminating pods retained their network connectivity, though I see you've already ruled this out earlier.

**Comment by thockin** [comment]
any updates here?

**Comment by nilesh-telang** [comment]
Hi @matthewbyrne ,

Thanks for sharing these details. 

Hi @thockin, at our end I think we may have found out the root cause of our issue. Our production systems use linkerd and we found that the graceful shutdown of linkerd may be causing the pod to loose connectivity to external components

The linkerd shutdown documentation mentions the following - https://linkerd.io/2.10/tasks/graceful-shutdown/

> When Kubernetes begins to terminate a pod, it starts by sending all containers in that pod a TERM signal. When the Linkerd proxy sidecar receives this signal, it will immediately begin a graceful shutdown where it refuses all new requests and allows existing requests to complete before shutting down.
> 
> This means that if the pod’s main container attempts to make any new network calls after the proxy has received the TERM signal, those network calls will fail. This also has implications for clients of the terminating pod and for job resources.

We have made changes in production to delay the shutdown of the linkerd such that the linkerd container is alive for the duration of the main container's graceful shutdown period. Based on the documentation, I believe this should address the issue.

>To mitigate this, use the --wait-before-exit-seconds flag with linkerd inject to delay the linkerd proxy’s handling of the TERM signal for a given number of seconds using a preStop hook. This delay gives slow clients additional time to receive the endpoints update before beginning graceful shutdown. To achieve max benefit from the option, the main container should have its own preStop hook with the sleep command inside which has a smaller period than is set for the proxy sidecar. And none of them must be bigger than terminationGracePeriodSeconds configured for the entire pod.

I will update and mark this ticket resolved once the verification of the fix is done.

Thank you all for you help and inputs on this issue.

**Comment by nilesh-telang** [comment]
Hi @caseydavenport ,

I apologize for the delay in responding. I missed the above question. 

We have confirmed that this was a linkerd Issue.

Thank again for all the help an inputs on this issue.
