### ISSUE TITLE
containerd pod and mirror pods sometimes remain after deleting the manifest

### ISSUE THREAD

**Issue by jmcmeek** [kubernetes/kubernetes#105790]
### What happened?

We have a test that creates a static pod on every node and a daemonset that later deletes the manifests for those files.  Sometimes the mirror pod and the containerd pod remain.  We've seen this when transient failures communicating with the apiserver caused a failure in calico like:
```
Oct 19 07:20:46 test-c5n6fr7206hepim5325g-kubee2epvgl-compute-000005fe kubelet.service[6774]: I1019 07:20:46.701627    6774 kubelet.go:2063] "SyncLoop REMOVE" source="file" pods=[pvg-k8s-psp-ns/static-nginx-10.184.98.11]
Oct 19 07:20:46 test-c5n6fr7206hepim5325g-kubee2epvgl-compute-000005fe kubelet.service[6774]: I1019 07:20:46.701995    6774 kuberuntime_container.go:714] "Killing container with a grace period" pod="pvg-k8s-psp-ns/static-nginx-10.184.98.11" podUID=5d6d2cc2c526ec6310afc8c64fac7052 containerName="static-nginx" containerID="containerd://7d0f1944976c8b4d75f44226e5f1ae59d08da416e4d776f47a2a265a2015548a" gracePeriod=30
Oct 19 07:21:27 test-c5n6fr7206hepim5325g-kubee2epvgl-compute-000005fe kubelet.service[6774]: E1019 07:21:27.130112    6774 pod_workers.go:765] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"5d6d2cc2c526ec6310afc8c64fac7052\" with KillPodSandboxError: \"rpc error: code = Unknown desc = failed to destroy network for sandbox \\\"852677484c01d58e4b124d984e7064edb6c969c27549ca9575de99d2b9bdb35e\\\": error getting ClusterInformation: Get \\\"https://[172.21.0.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default\\\": net/http: TLS handshake timeout\"" pod="pvg-k8s-psp-ns/static-nginx-10.184.98.11" podUID=5d6d2cc2c526ec6310afc8c64fac7052
```
There were no further references to the pod in the kubelet logs after that.

Restarting kubelet seems to clean up the pods.  It looks like kubelet takes one shot at deleting the pod and doesn't try again until kubelet is restarted.

### What did you expect to happen?

Kubelet should successfully delete the containerd resources and mirror pod once connectivity is restored.  We don't see the node go NotReady, so a retry might have succeeded right away.

### How can we reproduce it (as minimally and precisely as possible)?

* Create pod manifest in /etc/kubernetes/manifests
* Wait to see mirror pod in `kubectl get pods`
* Delete manifest file - and somehow cause a failure like seen above
* `kubectl get pod` and `crictl pods` still list the pod

### Kubernetes version

<details>

```console
$ kubectl version
Kubernetes 1.22.2
```

</details>

### Cloud provider

<details>
Running in IBM Cloud Kubernetes Service
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Containerd 1.5.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico CNI v3.20.1
</details>

**Comment by smarterclayton** [comment]
I'm almost positive this is #113145 

/assign
