### ISSUE TITLE
Reduce code duplication in test/e2e/storage/testsuites/snapshottable.go

### ISSUE THREAD

**Issue by mauriciopoppe** [kubernetes/kubernetes#105798]
### What would you like to be added?

The changes to support snapshot tests for Generic Ephemeral Volumes https://github.com/kubernetes/kubernetes/pull/105659 generated some duplicated code in the file `test/e2e/storage/testsuites/snapshottable.go` as commented here: https://github.com/kubernetes/kubernetes/pull/105659#discussion_r732587703, it'd be great to create functions that are reused in both `(ephemeral)` and `(persistent)` tests.

Things that are needed:

- A kubernetes dev cluster (I follow [this guide](https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/README-GCE-Windows-kube-up.md) to create a GCE cluster)
- Knowledge about how to [run e2e tests](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md)

/sig storage
/area testing
/good-first-issue

### Why is this needed?

Improve readability of the storage VolumeSnapshot tests

**Comment by yuvaldolev** [comment]
Hi @mauriciopoppe
Could you please give me some more details about what needs to be done in this issue?

**Comment by yuvaldolev** [comment]
Hi @mauriciopoppe
When I try to run the snapshottable tests using `kubetest2` and `kide` I get the following failures:
```
• Failure [43.147 seconds]
[sig-storage] CSI Volumes
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/utils/framework.go:23
  [Driver: csi-hostpath]
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/csi_volumes.go:40
    [Testpattern: Dynamic Snapshot (delete policy)] snapshottable[Feature:VolumeSnapshotDataSource]
    /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/framework/testsuite.go:50
      volume snapshot controller
      /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go:110

        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go:174
          should check snapshot fields, check restore correctly works after modifying source data, check deletion (persistent) [It]
          /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/snapshottable.go:305

          Nov  5 19:09:18.542: Unexpected error:
              <*errors.StatusError | 0xc00510e5a0>: {
                  ErrStatus: {
                      TypeMeta: {Kind: "", APIVersion: ""},
                      ListMeta: {
                          SelfLink: "",
                          ResourceVersion: "",
                          Continue: "",
                          RemainingItemCount: nil,
                      },
                      Status: "Failure",
                      Message: "the server could not find the requested resource",
                      Reason: "NotFound",
                      Details: {
                          Name: "",
                          Group: "",
                          Kind: "",
                          UID: "",
                          Causes: [
                              {
                                  Type: "UnexpectedServerResponse",
                                  Message: "404 page not found",
                                  Field: "",
                              },
                          ],
                          RetryAfterSeconds: 0,
                      },
                      Code: 404,
                  },
              }
              the server could not find the requested resource
          occurred
```

I have setup `kubetest2` and `kide` as their documentation suggested, but seem to not be-able to run the tests.
Do you have an idea why this happens?

Thanks!

**Comment by mauriciopoppe** [comment]
what was the command that you used? The csi-hostpath driver is embedded into the kubernetes codebase so you don't need to add anything else to your kind? cluster.

**Comment by yuvaldolev** [comment]
@mauriciopoppe The command I used to run the snapshottable tests is: `kubetest2 kind --test ginkgo -- --focus-regex "snapshottable"`

**Comment by yuvaldolev** [comment]
@mauriciopoppe do you have an idea about why this happens?

**Comment by mauriciopoppe** [comment]
hey @yuvaldolev, sorry for the late response and thanks for the reminder, I always run my tests with `hack/ginkgo.sh` and with a GCE cluster (not a kind cluster) for example following [this guide](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/e2e-tests.md#debugging-an-e2e-test-with-a-debugger-delve).

The VolumeSnapshot feature requires a CSI Driver, in our e2e tests we use a CSI Driver that's embedded in the kubernetes codebase called csi-hostpath, from the logs I saw that it used csi-hostpath which I think it's ok, ideally we should test it with a real CSI Driver like PD CSI Driver but that's going to provision storage in GCP.

Have you tried with `kubetest`? I think that there's more info in that page about kubetest than kubetest2

**Comment by yuvaldolev** [comment]
@mauriciopoppe Yes, I tried `kubetest`, but got the same errors as well

**Comment by MdSahil-oss** [comment]
hey @yuvaldolev  and @impact-maker, you guys have solved this issues or still working on it, because i'm considering to solve this issue if you haven't solved it

**Comment by mauriciopoppe** [comment]
thank you for signing up for this task, I believe #107066 should work, we're waiting for additional review
