### ISSUE TITLE
kube-proxy health check doesn't fail when kube-proxy can't acquire iptables lock

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#105742]
### What happened?

We upgraded iptables on one of our hosts, and kube-proxy began logging errors about being unable to acquire the `xtables.lock`. However, we didn't notice this, because kube-proxy's health check (`/healthz`) was still passing (and that's generally what we look at as our sign that something is amiss.) As a result, kube-proxy ran for days without being able to update iptables rules, eventually causing an outage for one of our services.

### What did you expect to happen?

We expected that kube-proxy's health check would fail if it was not able to interface with iptables.

### How can we reproduce it (as minimally and precisely as possible)?

Our system was running Debian stretch, running kube-proxy in iptables mode with systemd, with iptables version 1.6.0. Given that starting configuration, the repro case is:

1. Upgrade iptables to 1.6.2.
2. Observe that kube-proxy begins emitting logs saying that it cannot update iptables because another process has the `xtables.lock`.
3. Observe that kube-proxy's health check endpoint (`/healthz`) does not return an error.

### Anything else we need to know?

Example health check output:

<details>

```
$ curl -vvv localhost:10256/healthz
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10256 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:10256
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Tue, 19 Oct 2021 22:21:06 GMT
< Content-Length: 149
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"lastUpdated": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255","currentTime": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255"}
```

</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux myhost 5.4.38 #1~bt9+1 SMP Tue May 12 21:16:19 UTC 2020 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
The hard way
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker version 19.03.8, build afacb8b7f0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.18.4
</details>

**Comment by 2rs2ts** [comment]
@cyclinder Yeah we upgraded on just one node at first. Like my original bug report says, we started at 1.6.0, so all the other nodes had 1.6.0.

@aojea it never gets the lock. You have to restart kube-proxy so it can go through the iptables version detection routine again and change its behavior to the 1.6.2 logic branch. That's fine, it's whatever, but the health check doesn't fail even though kube-proxy can't do its job, which is a bug in my opinion.

**Comment by 2rs2ts** [comment]
I added this to the description as well, but here is an example `/healthz` response during this failure mode:

```
$ curl -vvv localhost:10256/healthz
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 10256 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:10256
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Tue, 19 Oct 2021 22:21:06 GMT
< Content-Length: 149
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"lastUpdated": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255","currentTime": "2021-10-19 22:21:06.566660851 +0000 UTC m=+219.246054255"}
```

And here are what the logs look like:

```
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.126027     384 proxier.go:874] Syncing iptables rules
Oct 19 22:20:40 myhost kube-proxy[384]: E1019 22:20:40.168050     384 proxier.go:1598] Failed to execute iptables-restore: exit status 4 (Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Oct 19 22:20:40 myhost kube-proxy[384]: )
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.168158     384 proxier.go:1601] Closing local ports after iptables-restore failure
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.168188     384 proxier.go:879] Sync failed; retrying in 30s
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.168215     384 proxier.go:826] syncProxyRules took 42.459134ms
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.168239     384 bounded_frequency_runner.go:296] sync-runner: ran, next possible in 1s, periodic in 1h0m0s
Oct 19 22:20:40 myhost kube-proxy[384]: I1019 22:20:40.168262     384 bounded_frequency_runner.go:279] sync-runner: retrying in 29.999949645s
```

Running `sudo lslocks | grep xtables` gives no output.

**Comment by cyclinder** [comment]
A situation: 

when there is a service or endpoint is constantly updated (which will update the `lastQueued`):
https://github.com/kubernetes/kubernetes/blob/f2e5c16545027fbe04cc33d4ef59cd01de6b9967/pkg/proxy/iptables/proxier.go#L509

so there is a high probability that the difference between the `current time` and the `lastQueued` is less than the `healthTimeout`, so this will be considered healthy

If you reduce `healthTimeout`( iptables-sync-period * 2, the defaults value of flag `iptables-sync-period` is 30s), you may see response code is 503, but in fact, it is not easy to estimate how much it should be reduced.

so As for case 3, I think there are something that can be optimized.

**Comment by cyclinder** [comment]
Thanks @danwinship,  I see, I'd fix it, can I take this one?

**Comment by danwinship** [comment]
@cyclinder sure
/assign @cyclinder
