### ISSUE TITLE
Oldest-by-date repilca set overwrite instead of oldest-by-revision during deployment leads to rollback to inproper version.

### ISSUE THREAD

**Issue by maciekdka** [kubernetes/kubernetes#105732]
Problem is that during deployment the oldest-by-date replica set is overwritten instead of oldest-by-revision. Rollback failure will occur according to revisionHistoryLimit value - in our case it was set to 2, so 2 historical revisions plus current one is kept - issue occured during 3rd deployment. Please see details in below image:

![deployment-overwritte-oldest-by-date-replica-set-instead-of-oldest-by-revision](https://user-images.githubusercontent.com/92722719/137711907-5f0ecfef-38dc-4fd2-97bd-492a51440fa9.jpg)

**Comment by eddiezane** [comment]
This might be https://github.com/kubernetes/kubectl/issues/598.

Please take a look and if not open a new issue and follow the bug issue template. Please make sure to include a simple way to reproduce.

/close
