### ISSUE TITLE
CRD Validation Expression Language in Alpha

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#105745]
### What would you like to be added?

Adding Expression Language validation for CRD.

KEP: <https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2876-crd-validation-expression-language>

Expression Language validation for CRD is available as alpha feature in 1.23:
- [x] https://github.com/kubernetes/kubernetes/pull/105107
- [x] https://github.com/kubernetes/kubernetes/pull/105477
~- [x] ~https://github.com/kubernetes/kube-openapi/pull/253~
~- [x] ~https://github.com/kubernetes/kube-openapi/pull/256~
~- [x] ~https://github.com/kubernetes/kube-openapi/pull/257~
~- [x] ~Add x-kubernetes-validator into kube-openapi schema extension [PR](https://github.com/kubernetes/kube-openapi/pull/257)~
~- [ ] Bump k8s.io/kube-openapi version with above changes #105477~
~- [ ] ~https://github.com/kubernetes/kube-openapi/pull/258~
~- [ ] ~Optimize SchemaValidator to avoid repeated recompilation of CEL programs~
~- [ ] ~Integrate expression validator of CR in k8s(Bump kube-openapi)~
- [x] Add Integration tests
~- [ ] ~Cherrypick #105477 to last few releases~ Not needed

After several round of dissuasion, we decide to move expression validation in k/k:
- [x]  https://github.com/kubernetes/kubernetes/pull/106234
- [x] https://github.com/kubernetes/kubernetes/pull/106051
- [ ] https://github.com/kubernetes/kubernetes/pull/106462

TODO tasks before graduating to beta:
- [ ] Resolve topic of what support we should provide for access to the previous versions of object (ie. 'oldSelf' feature)
- [ ] x-kubernetes-int-or-string is upgraded to use a union type of just int or string, not a dynamic type (CEL go support is planned in lates 2021)
- [ ] Understanding of upper bounds of CPU/memory usage and appropriate limits set to prevent abuse.
- [ ] Build-in macro/function library is comprehensive and stable (any changes to this will be a breaking change)
- [ ] CEL numeric comparison issue is resolved (e.g. ability to compare ints to doubles)
- [ ] [Reduce noise of invalid data messages reported from cel.UnstructuredToVal](https://github.com/kubernetes/kubernetes/issues/106440)
- [ ] [Benchmark cel.UnstructuredToVal and optimize away repeated wrapper object construction](https://github.com/kubernetes/kubernetes/issues/106438)

### Why is this needed?

Validating CRD with webhooks is painful, it could be greatly improved by adding expression language validation.

/sig api-machinery
/wg api-expression

**Comment by cici37** [comment]
Update the issue to address the changes in 1.23 and added criteria for graduating to beta.

**Comment by jpbetz** [comment]
I think we can close this one and open a new issue for beta.

**Comment by cici37** [comment]
/close
Close this one since the feature made to alpha.
Open https://github.com/kubernetes/kubernetes/issues/106465 to track for beta release.
