### ISSUE TITLE
Race condition in apiserver when request times out

### ISSUE THREAD

**Issue by marseel** [kubernetes/kubernetes#105759]
### What happened?

Apiserver crashed with stacktrace:
```
goroutine 943732 [running]:
runtime.throw
        /usr/local/go/src/runtime/panic.go:1117
runtime.mapaccess1_faststr
        /usr/local/go/src/runtime/map_faststr.go:21
net/textproto.MIMEHeader.Get
        /usr/local/go/src/net/textproto/header.go:34
net/http.Header.Get(...)
        /usr/local/go/src/net/http/header.go:46
net/http.(*Request).UserAgent(...)
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).LogArgs(...)
        k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:185 
```

### What did you expect to happen?

Not to crash

### How can we reproduce it (as minimally and precisely as possible)?

I was able to reproduce it by "slowing down" deleting headers in Authentication filter (staging/src/k8s.io/apiserver/pkg/endpoints/filters/authentication.go):

```
		req.Header.Del("Authorization")
		if strings.Contains(req.URL.Path, "itsnotworkingisit") {
			for i := 1; i < 100000000; i++ {
				req.Header.Add("Authorization", "test")
				req.Header.Del("Authorization")
			}
		} 
```
And making requests (around 5-10 requests to trigger this race condition):
```
 kubectl get --raw='/api/v1/namespaces/kube-system/configmaps/itsnotworkingisit?timeout=1s'
```

### Anything else we need to know?

Crash was caused by race condition - one goroutine was modifying headers of requests (for example authentication filter). The other goroutine was trying to get UserAgent from request, which is also taken from request's headers map. This causes unrecoverable panic.

### Kubernetes version

<details>
All versions, tested on 1.21
```console
$ kubectl version
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wojtek-t** [comment]
@marseel - friendly ping on opening cherrypicks

**Comment by marseel** [comment]
One more for 1.20: https://github.com/kubernetes/kubernetes/pull/106124

**Comment by wojtek-t** [comment]
All merged - thanks!
