### ISSUE TITLE
Meta: bug report form may suggest other repositories than kubernetes/kubernetes

### ISSUE THREAD

**Issue by jpetazzo** [kubernetes/kubernetes#105740]
In some cases, issues get more visibility if they are open on other repositories. For instance, after #105518, I learned that issues with `kubectl` should be open in kubernetes/kubectl instead of kubernetes/kubernetes.

According to https://github.com/orgs/kubernetes/repositories?q=issue there is also kubernetes/kubeadm (and perhaps others that don't have "issue" in the description 😅).

Would it make sense to add a small note in the default bug template in kubernetes/kubernetes to tell folks to have a look there? Or is that unnecessary?

**Comment by pacoxu** [comment]
Currently, we support `/transfer-issue kubectl` to move the issue to the correct project.  See example: https://github.com/kubernetes/kubectl/issues/1122#issuecomment-927339103.
