### ISSUE TITLE
ReservedMemory Configuration for NUMA

### ISSUE THREAD

**Issue by nmathew** [kubernetes/kubernetes#105783]
I am trying out  [Topology Aware Scheduler](https://github.com/killianmuldoon/documentation/tree/installguide/install-guides) For that I enabled kubelet memory manager, cpu manager and topology manager.
This is tried on a dual socket NUMA server

`KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/run/containerd/containerd.sock --cpu-manager-policy=static 
--feature-gates=RotateKubeletServerCertificate=true,AllAlpha=false,RemoveSelfLink=false,EphemeralContainers=true,BoundServiceAccountTokenVolume=false,KubeletPodResourcesGetAllocatable=true,TopologyManager=true,MemoryManager=true --kube-api-burst=40 --kube-api-qps=20 --kube-reserved=cpu=4,memory=4Gi --memory-manager-policy=static  --reserved-cpus=0,1,2,3 --reserved-memory 0:memory=4Gi,1:memory=4196Mi  --system-reserved=cpu=4,memory=4Gi --topology-manager-policy=single-numa-node"`

`topologyManagerPolicy: single-numa-node
` is set on /var/lib/kubelet/config.yaml

This throws an error 
`2021-10-20T11:28:49.523899+00:00 localhost kubelet[43342]: E1020 11:28:49.521957   43342 server.go:156] "Failed to parse kubelet flag" err="invalid argument \"0:memory=4Gi,1:memory=4196Mi\" for \"--reserved-memory\" flag: the reserved memory has incorrect format, expected numaNodeID:type=quantity[,type=quantity...], got 0:memory=4Gi,1:memory=4196Mi"
`

This is on kubernetes 1.21.1
`Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"e48500f7a04e3eaea2a2bd52ba58f25aa8ae7a23", GitTreeState:"clean", BuildDate:"2021-09-29T11:36:35Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
`

Any hints on specifying "reserved-memory" for multi-socket NUMA system ????

One way is specifying multiple "reserved-memory" like 
`--reserved-memory 0:memory=4Gi --reserved-memory 1:memory=4196Mi`

But problem with this is `KubeletExtraArgs map[string]string` is map, so it will get over-written.

### What did you expect to happen?

we should be able to specify reserved memory in a multi socket system.

### How can we reproduce it (as minimally and precisely as possible)?

Enable above flags and run kubelet

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"e48500f7a04e3eaea2a2bd52ba58f25aa8ae7a23", GitTreeState:"clean", BuildDate:"2021-09-29T11:36:35Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

none

### OS version

SLES 15 sp2

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

containerd

**Comment by nmathew** [comment]
Are we planning to add support for multiple numa nodes in single "--reserved-memory" flag, or just displaying a better error msg?

**Comment by nmathew** [comment]
@cynepco3hahue @SergeyKanzhelev by looking at the struct

`type ReservedMemoryVar struct {
	Value       *[]kubeletconfig.MemoryReservation
	initialized bool // set to true after the first Set call
}`

it seems we need to support multiple numa nodes in single "--reserved-memory" .

**Comment by cynepco3hahue** [comment]
@nmathew We should support multiple NUMA nodes under the same --reserved-memory flag.

**Comment by nmathew** [comment]
@cynepco3hahue Can you provide a sample configuration for 2 numa nodes?
"." comma seperator is already there for single numa configuration.

**Comment by cynepco3hahue** [comment]
@nmathew Yes, it is the problem, initially we needed to split it by comma, but probably it will not work as expected, so maybe we can split it by `;` and update documentation. Something like:
`<numa_id1>:<resource_name1>=<resource_size1>,...,<resource_nameN>=<resource_sizeN>;...;<numa_idN>:<resource_name1>=<resource_size1>,...,<resource_nameN>=<resource_sizeN>`

**Comment by rthakur-est** [comment]
@nmathew @cynepco3hahue can you please review the PR and provide your comments
https://github.com/kubernetes/kubernetes/pull/106840
