### ISSUE TITLE
Preventing the kube-node-lease namespace removal 

### ISSUE THREAD

**Issue by amrHassanAbdallah** [kubernetes/kubernetes#105743]
### What would you like to be added?

Right now the deletion of the below namespaces is prevented by the server 
`default`, `kube-public`, `kube-system`

But when trying to delete the 
`kube-node-lease` namespace, the server deletes it, and sometimes the namespace removal is stuck at the deleted stage which prevents the regeneration for this namespace and ends up impacting the communication between the nodes.

### Why is this needed?

Prevent `kube-node-lease` namespace removal

**Comment by linxiulei** [comment]
#85807

**Comment by ehashman** [comment]
/unassign

Please raise this in a SIG Node meeting. I'm not sure how high priority this is, but per https://github.com/kubernetes/kubernetes/pull/85807#issuecomment-560466440 I'm not sure if this is desirable.
