### ISSUE TITLE
kubectl options incorrect --> --skip-headers should be replaced with --no-headers

### ISSUE THREAD

**Issue by ronaldpetty** [kubernetes/kubernetes#105710]
### What happened?

Tried to strip headers, failed with --skip-headers (found in kubectl options):

```
~$ kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -l release=istio -A --skip-headers
NAMESPACE      NAME                               DATA   AGE
istio-system   configmap/istio                    2      67m
istio-system   configmap/istio-sidecar-injector   2      67m
NAMESPACE      NAME               ENDPOINTS                                                     AGE
istio-system   endpoints/istiod   10.32.0.4:15012,10.32.0.4:15010,10.32.0.4:15017 + 1 more...   67m
```

### What did you expect to happen?

```
~$ kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -l release=istio -A --skip-headers
istio-system   configmap/istio                    2     67m
istio-system   configmap/istio-sidecar-injector   2     67m
istio-system   endpoints/istiod   10.32.0.4:15012,10.32.0.4:15010,10.32.0.4:15017 + 1 more...   67m
istio-system   serviceaccount/istio-reader-service-account   1     67m
istio-system   serviceaccount/istiod                         1     67m
istio-system   serviceaccount/istiod-service-account         1     67m
```

### How can we reproduce it (as minimally and precisely as possible)?

Just install via kubeadm 1.22.2 k8s, here is the exact script I use.

`K8S_VERSION=1.22.2 sh <(wget -O - https://raw.githubusercontent.com/RX-M/classfiles/master/k8s.sh)`

```
~$ kubectl options | grep headers
      --skip-headers=false: If true, avoid header prefixes in the log messages
      --skip-log-headers=false: If true, avoid headers when opening log files
```

Just change from --skip-headers to --no-headers and it worked.

### Anything else we need to know?

The docs use no-header, found here:

https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get

### Kubernetes version

<details>

```console
 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

none

### OS version

cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Install tools

kubeadm 1.22.2

### Container runtime (CRI) and and version (if applicable)

sudo docker version
Client: Docker Engine - Community
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.8
 Git commit:        c2ea9bc
 Built:             Mon Oct  4 16:08:29 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.8
  Git commit:       79ea9d3
  Built:            Mon Oct  4 16:06:37 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Related plugins (CNI, CSI, ...) and versions (if applicable)

weave

**Comment by neolit123** [comment]
> --skip-headers=false: If true, avoid header prefixes in the log messages

these flags come from the logger - klog.

/sig instrumentation
/kind documentation

**Comment by cyclinder** [comment]
--skip--headers flag come from klog
--no-headers flag come from  "kubectl get"

https://github.com/kubernetes/kubernetes/blob/9804a83d8fd9eec4c20e75e73e11ffd4b370c6f0/staging/src/k8s.io/kubectl/pkg/cmd/get/get_flags.go#L167

**Comment by serathius** [comment]
cc @pohly

**Comment by pohly** [comment]
There isn't anything to fix here, right?

`kubectl options` shows the logging options as part of the global flags. `--no-headers` is shown as additional flag for the `get` command:

```
$ go run ./cmd/kubectl options 2>&1 | grep headers
      --skip-headers=false: If true, avoid header prefixes in the log messages
      --skip-log-headers=false: If true, avoid headers when opening log files
$ go run ./cmd/kubectl get --help 2>&1 | grep headers
      --no-headers=false: When using the default or custom-column output format, don't print headers (default print headers).
```

**Comment by ronaldpetty** [comment]
@pohly I agree, it didn't click with me earlier.

I suppose I was hoping (incorrectly) there was a way to remove headers in general. The --skip-headers mentions logs (unlike --no-headers) so maybe its for log "files" only (haven't figured out how to confirm that). I was assuming stdout was a 'log'. I guess this gets closed and I can go read the source on what --skip-headers does and if it doesn't work with stdout basic commands maybe submit a feature request.

Thanks again for the clarification.

**Comment by pohly** [comment]
> The --skip-headers mentions logs (unlike --no-headers) so maybe its for log "files" only (haven't figured out how to confirm that)

Correct. You get log messages when running kubectl with something like `-v=5` and those can be written into files in addition or instead of stderr.

/close
