### ISSUE TITLE
[PodSecurity] Automated webhook image builds

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#105746]
We should automate the webhook image build using cloud build (see https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#enabling-automatic-builds).

This depends on the initial webhook implementation: https://github.com/kubernetes/kubernetes/pull/105362

/sig auth

**Comment by uhari03** [comment]
@tallclair I'm interested in working on this, but it'll be my first time working with publishing k8s images.

Do we have a GCR present already for this? If yes, how do I get access or reference it for the cloudbuild.yaml files.

If no, should I be the one creating the google groups + GCRs?

**Comment by tallclair** [comment]
Yeah, if you look at the PR you linked the registry `gcr.io/k8s-staging-sig-auth` is already set up for this (https://github.com/kubernetes/k8s.io/pull/2921)
