### ISSUE TITLE
PodTopologySpread performance degrades as more pods are created

### ISSUE THREAD

**Issue by onerandomdude** [kubernetes/kubernetes#105750]
### What happened?

In a benchmark cluster with the following setup:

* 3x control plane instances
* 3x etcd instances
* 5000x [kubemark](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubemark) nodes

Use [clusterloader](https://github.com/kubernetes/perf-tests/tree/master/clusterloader2) to launch Pods with the following configuration:

* Create 5000 deployments under 1 namespace, each deployment has 30 pods
* Create deployments with the rate of 50 deployments per second

The control plane has the following configuration:

* scheduler to apiserver rate limit: kube-api-qps=150, kube-api-burst=200
* controller-manager to apiserver rate limit: kube-api-qps=150, kube-api-burst=200

During the test, it's observed that Pod binding rate drops as more Pods are created:

![image1](https://user-images.githubusercontent.com/48631960/137820341-eccb8223-9cc7-4e54-b2c2-f7d4b4147f11.png)

### What did you expect to happen?

Pod binding rate should not degrade in relates to the number of Pods in the cluster/namespace.

### How can we reproduce it (as minimally and precisely as possible)?

Add the following into scheduler config:

```
clientConnection:
  qps: 150
  burst: 200
```

Add the following flags to controller-manager:

```
--kube-api-qps=150 --kube-api-burst=200
```

Spin up a benchmark cluster with 5000 kubemark nodes and 3 control plane instances. And run the test:

```
./clusterloader --testconfig=config_minimal.tmpl <args-specific-to-the-cluster...>
```

config_minimal.tmpl: https://gist.github.com/onerandomdude/4c337c8d54971d829e7d8f2300e0fb24
deployment_minimal:tmpl: https://gist.github.com/onerandomdude/faa44adc1fb0ce52ce7006713e8bfd59

### Anything else we need to know?

Disabling PodTopologySpread plugin fixes the degradation:

```
diff --git a/pkg/scheduler/framework/plugins/registry.go b/pkg/scheduler/framework/plugins/registry.go
index 5083f55eeb7..358dff9dea7 100644
--- a/pkg/scheduler/framework/plugins/registry.go
+++ b/pkg/scheduler/framework/plugins/registry.go
@@ -29,7 +29,6 @@ import (
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/noderesources"
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodeunschedulable"
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/nodevolumelimits"
-       "k8s.io/kubernetes/pkg/scheduler/framework/plugins/podtopologyspread"
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/queuesort"
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/selectorspread"
        "k8s.io/kubernetes/pkg/scheduler/framework/plugins/serviceaffinity"
@@ -52,7 +51,7 @@ func NewInTreeRegistry() runtime.Registry {
                nodeports.Name:                             nodeports.New,
                nodepreferavoidpods.Name:                   nodepreferavoidpods.New,
                nodeaffinity.Name:                          nodeaffinity.New,
-               podtopologyspread.Name:                     podtopologyspread.New,
+               // podtopologyspread.Name:                     podtopologyspread.New,
                nodeunschedulable.Name:                     nodeunschedulable.New,
                noderesources.FitName:                      noderesources.NewFit,
                noderesources.BalancedAllocationName:       noderesources.NewBalancedAllocation,
```

![image7](https://user-images.githubusercontent.com/48631960/137824412-8cbc20a1-8804-4132-a5cf-3b263ee382c2.png)

I did some debugging, it seems like the hotspot is this section of code, which calculates `TpPairToMatchNum` map:

https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L247-L261

I tried to mock out this section, and it also mostly restores the scheduling performance:

![image2](https://user-images.githubusercontent.com/48631960/137822994-19e4a517-f41a-4fb6-992b-26e6d2eba447.png)

Some observations in terms of why the code is slow:

* It enumerates all Pods (from the same namespace) on all Nodes on every scheduling cycle
* `TpPairToMatchNum` result is thrown away on every cycle, while it could be reused to some extent to speed up the scheduling performance

### Kubernetes version

<details>

v1.20.4

</details>

### Cloud provider

<details>
On-Prem
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux <hostname> 4.14.171 #3 SMP Thu Apr 1 20:53:09 UTC 2021 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by onerandomdude** [comment]
Hi @abg-g, apologize for the radio silence, some quick updates on my side:

1. applying the same optimization (without populating `TpKeyToCriticalPaths` map) which defers `TpPairToMatchNum` calculation to "Filter" stage for "Hostname" topology key does yield very good performance (pod creation rate == pod binding rate)
2. however, the tricky bit is to calculate the "global min" in the `TpKeyToCriticalPaths` map, which requires us to enumerate through all Nodes, and it defects the purpose of the optimization

I am currently looking at if we could defer the "global min" calculation until absolutely needed, i.e. when `matchNum + selfMatchNum` (https://github.com/kubernetes/kubernetes/blob/v1.20.4/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L320) is greater than `MaxSkew`, then at that point, we run a subroutine to calculate `minMatchNum`.

But I would like to get your inputs on this potential solution and see if there is a better way to resolve this.

**Comment by Huang-Wei** [comment]
Want to point out that the fact "Special optimization on node-level constraint works on Score" may not lead to the effect it also works on Filter.

> Yes, when setting whenUnsatisfiable: ScheduleAnyway the performance improves:
> And it looks similar to the performance graph where the PodTopologySpread plugin has been disabled.

- PreFiler() runs against all nodes, while Score() runs against a fair low number of nodes - due to `percentageOfNodesToScore` and filtering result of other Filter plugins.
- Score() only needs to come up with a relative score/weight among the filtered nodes. It doesn't need to include all nodes for scoring calculation, also which is more critical, it doesn't need to calculate the global minimum matching pods (which is a must for Filter()).
