### ISSUE TITLE
Move `coscheduling` plugin from scheduler-plugins to kubernetes/kubernetes

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes/kubernetes#105802]
### What would you like to be added?

Add `coscheduling` plugin from https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling to the default `kube-scheduler`.

### Why is this needed?

1. `coscheduling` plugin is one the [motivations for the scheduling framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md#coscheduling). Number of features in the `kube-scheduler` (e.g. pods waiting in the Permit extension point or https://github.com/kubernetes/kubernetes/pull/103383) were added to support `coscheduling`. It would be easier to develop `kube-scheduler` and its scheduling framework if this plugin was part of kubernetes.

2. `coscheduling` is highly anticipated feature and supporting it by default would be great for adoption.

3. Working with `scheduler-plugins` repository is painful:
  - `scheduler-plugins` does not get patches when default `kube-scheduler` does
  - `scheduler-plugins` is sometimes few releases behind main Kubernetes
  - It is harder to build, deploy (e.g. additional controller has to be deployed) and maintain custom `kube-scheduler`.

---

I know it is not trivial to do it, but I think it is worth discussing it.

---

/sig scheduling

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei

**Comment by k82cn** [comment]
> In terms of co-scheduling, it's a fundamental requirement for batch workloads. Default scheduler have been long criticized for poor support on that, and we all agreed to add support for batch workloads natively.

co-scheduling is just one feature of batch system, e.g. [Slurm](https://slurm.schedmd.com/documentation.html); and there're also several feature interactions between those features, e.g. co-scheduling + preemption, which make a batch system more complex. So are we going to do all of those features into k/k for batch workload? 

> I think complexity and maintainability is another important criteria that should take a high priority in my opinion. Again the framework went a long way to unblock implementing such complex features outside k/k

Yes; based on complexity of batch scheduler, we proposed to have a new repo for batch to make k/k more focus.

> My concern is that if more users turn to other orchestrators, on one side, the resource conflicts of running multi-schedulers would hurt the user's business; on the other side, we may don't have enough users and thus real production reqs to validate/improve the scheduler framework. This'd sacrifice the efforts we put together to build scheduler framework, multi-profile, etc.

re 'other orchestrators/put together to build scheduler framework': IMO, we should open to the other orchestrators or organization to build their own scheduler whether based on scheduling framework or not. Scheduling framework helps user to build customized scheduling easily, it is up to the user to decide whether to use it or not :)

re 'conflicts of running multi-schedulers': currently, we use default scheduler to launch system daemons in management nodes, and use customized scheduler for business workloads in worker nodes. 

> Sure. The spec of PodGroup needs to be polished first, to adapt the needs to the whole k8s ecosystem, so each component can respond properly on API fields.

Will `PodGroup` bind to scheduling framework? One example is `.scheduleTimeoutSeconds` which is required by scheduling framework for 'Permit/Wait', but not necessary in Volcano which already do scheduling by PodGroup.

**Comment by k82cn** [comment]
In addition, prefer to have neutral repo for batch interface, similar to CSI, CNI, CRI and so on. And let's the orchestrators/organization to build their own implementations :)

I used to create [openBSI](https://github.com/openbsi) for that purpose, but the progress is slow because of effort :(

**Comment by Huang-Wei** [comment]
@k82cn some clarifications below:

> co-scheduling is just one feature of batch system, e.g. [Slurm](https://slurm.schedmd.com/documentation.html); and there're also several feature interactions between those features, e.g. co-scheduling + preemption, which make a batch system more complex. So are we going to do all of those features into k/k for batch workload?

Co-scheduling is definitely not all about batching. This issue is actually proposing making a long-requested batching directive (PodGroup) natively supported in k/k. It doesn't block external schedulers to implement or not implement this directive.

> Yes; based on complexity of batch scheduler, we proposed to have a new repo for batch to make k/k more focus.

I agree that developing in a new repo gives the best flexibility. However, like this issue mentioned, managing another scheduler is not trivial work, no matter it's a scheduler plugin-based or not.

> IMO, we should open to the other orchestrators or organization to build their own scheduler whether based on scheduling framework or not. Scheduling framework helps user to build customized scheduling easily, it is up to the user to decide whether to use it or not :)

The k8s ecosystem is still and always open. I don't see a difference w/ or w/o some batching directives in k/k. If an orchestrator like volcano provides the features the user exactly wants, they may go with it; if some user just wants the basic batch feature like co-scheduling and also keep their k8s binaries up-to-date, they may go with default scheduler, without worrying about managing multiple schedulers.

> currently, we use default scheduler to launch system daemons in management nodes, and use customized scheduler for business workloads in worker nodes.

Can you elaborate? Are you suggesting in this case, the user just run customized batch workloads?

> Will PodGroup bind to scheduling framework?

Nope. I'd pursue a generic and minimized API first, which would benefit the whole ecosystem, not just scheduling framework. Implementation-specific bits like `.scheduleTimeoutSeconds` should be plumbed into the specific implementation mechanics, for example, plugin arguments.

> In addition, prefer to have neutral repo for batch interface, similar to CSI, CNI, CRI and so on. And let's the orchestrators/organization to build their own implementations :)

Compared to directly pushing the API to k/k, this sounds like a more practical approach IMO. I hope it's possible to come up with a generic API that meets the needs of all major scheduler orchestrators - default scheduler, volcano, yunikorn, etc.

(In the long run, when the API gets mature, we may move it to k/k as a `BatchSchedulingClass`, and associate it with a PodSpec.)

> I used to create openBSI for that purpose, but the progress is slow because of effort :(

Is there an official batch WG that we can discuss and roll it forward?

**Comment by k82cn** [comment]
Proposed to start a new working group for that in CNCF/TAG-runtime: https://github.com/cncf/tag-runtime/issues/38

> Are you suggesting in this case, the user just run customized batch workloads?

No, our customized scheduler already imports all algorithms from upstream, it's not necessary to use multi-scheduler in one cluster; this solution is used for the hosted k8s service, e.g. CCE, EKS, AKS.

**Comment by ahg-g** [comment]
We indeed need a forum to discuss batch related efforts. 

As you may all know, we have been investing in improving batch support in core k8s, we started with the the Job API (indexed job, suspend, reliable tracking, 1:1 pod to node assignment, automatic job cleanup).

We also proposed an approach for job management: bit.ly/k8s-job-management, focused on job-level placement and provisioning. We will be sharing a more concrete implementation of this proposal in the next couple of months.

We also discussed initiating a k8s batch SIG or WG as an incubator for all those efforts and others like PodGroup, NUMA support. 

Why do we need a cncf-hosted group if the focus is k8s? containerd/CNI/CSI for example are trying to support more than k8s, but if the things we are planning are k8s-specific, wouldn't a k8s sig/wg be more appropriate? I opened an issue under community to discuss: https://github.com/kubernetes/community/issues/6263

**Comment by k82cn** [comment]
> Why do we need a cncf-hosted group if the focus is k8s? containerd/CNI/CSI for example are trying to support more than k8s, but if the things we are planning are k8s-specific, wouldn't a k8s sig/wg be more appropriate?

We may have different implementation based on the specifications; it may not an extender of k8s scheduler :)

**Comment by ahg-g** [comment]
> We may have different implementation based on the specifications; it may not an extender of k8s scheduler :)

but it still can be hosted in k/k or a subproject of k/k because the target orchestrator is k8s. CNI/CRI for example is not k8s specific api, and that is why it is hosted outside k/k.

**Comment by k82cn** [comment]
> but it still can be hosted in k/k or a subproject of k/k because the target orchestrator is k8s. 

How to handle Volcano (CNCF) & YuniKorn (Apache), maybe others ?

**Comment by alculquicondor** [comment]
They still run on kubernetes, so they can still depend on kubernetes repos, right?

**Comment by MaciekPytel** [comment]
Sorry, I missed this discussion earlier and I can see it moved on to other topics. Circling back for a second to integration with CA: the problem with coscheduling plugin and Cluster Autoscaler is much broader than looking at PodGroup resource. CA algorithm at its core is greedy binpacking that can be summed up with this pseudocode:

```
nodesToAdd = []
for p in pendingPods:
    scheduled = false
    for n in nodesToAdd:
        if canSchedule(n, p):
            n.AddPod(p)
            scheduled = true
            break
    if not scheduled:
        nodesToAdd.append(newNodeInfo())
        nodesToAdd[-1].AddPod(p)
requestVms(len(nodesToAdd))
```
Notably this algorithm runs only PreFilters/Filters() and completely ignores other functions in scheduling framework (ex. Scores), but that's not the main problem here.

I think core of the issue of CA integration with coscheduling plugin is that IIRC the plugin delays a decision on whether a pod can be scheduled or not. This is fundamentally incompatible with the greedy nature of CA algorithm.
I don't think we can just brush this off saying that all that's needed is for CA to look at PodGroup. I think we need a specific design that covers how the integration with CA will work that is either done together with, or approved by sig-autoscaling. I wouldn't be very surprised if the solution would require serious refactors in both CA and the coscheduling plugin.

**Comment by k82cn** [comment]
> They still run on kubernetes, so they can still depend on kubernetes repos, right?

If so, are we going to re-implement or re-define "hot" CRDs in k/k? All those CRDs run on k8s and dependent on k8s repos :)

Currently, both Kuberentes (Graduated) and Volcano (Proposing to Incubating) are CNCF projects, YuniKorn is an Apache Incubating project; so it's better to have a neutral place/repo to align the interface, e.g. WG in CNCF.

Even more (hm... mybe not necessary), such a repo/WG is helpful to involve traditional batch system communitys who may give more inputs in HPC area.

**Comment by haosdent** [comment]
> Currently, both Kuberentes (Graduated) and Volcano (Proposing to Incubating) are CNCF projects, YuniKorn is an Apache Incubating project; so it's better to have a neutral place/repo to align the interface, e.g. WG in CNCF.

Personally, I think the discussions are stand from different perspectives. If the purpose of WG-Batch is just to focus on adding batch support on the default k8s-scheduler, it is nature that put the WG under kubernetes. But if the purpose of WG-Batch is looking forward to improving batch support for other Cloud Native softwares, such as Volcano, it looks better if we could put the WG under CNCF.

**Comment by dims** [comment]
@k82cn @haosdent we can't be having the same exact conversation all the time, there are folks who want to do stuff in k8s. So the WG in k8s will concentrate on that. Who ever does not want to help there can do something similar in CNCF with a broader vision. So let's please stop talking about the same thing again and again.

It will be upto the TLs and SIG-chairs of the proposed k8s WG + SIG-Apps + SIG-Scheduling to figure out if this issue a valid one and things need to be done here.

**Comment by haosdent** [comment]
@dims Sure, sounds good to me.
