### ISSUE TITLE
kubelet resets its OOM score to -999 despite oomScoreAdj configuration value when running in a container

### ISSUE THREAD

**Issue by smira** [kubernetes/kubernetes#105820]
### What happened?

[Talos Linux](https://github.com/talos-systems/talos) runs `kubelet` in a container. Talos sets OOM score to -450 for the kubelet container and passes `oomScoreAdj: -450` in the kubelet config. 

End result is that `kubelet` OOM score adj is -999 though.

```
172.20.0.2: I1020 20:49:51.619550       1 container_manager_linux.go:929] "Attempting to apply oom_score_adj to process" oomScoreAdj=-999 pid=1
172.20.0.2: I1020 20:49:51.619561       1 oom_linux.go:65] attempting to set "/proc/1/oom_score_adj" to "-999"
```

### What did you expect to happen?

`kubelet` should have configured OOM score `-450`.

### How can we reproduce it (as minimally and precisely as possible)?

Source code analysis.

First, OOM score is set correctly from the config (flags):

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/cmd/kubelet/app/server.go#L794-L797

But then, in container manager, OOM score is reset to -999 via the following:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L538-L540

This function should skip action if the PID is not running on the host:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L895-L903

But the function `isProcessRunningInHost` looks to be confusing:

https://github.com/kubernetes/kubernetes/blob/ae9ca48f01ddb03731e7903cfe91ef3db9ce8990/pkg/kubelet/cm/container_manager_linux.go#L808-L821

When kubelet runs in a container with PID namespace shared with the host, kubelet's PID namespace will be equal to PID 1 namespace. If kubelet runs in a container with unshared PID namespace, kubelet's PID is 1 and its PID namespace is identical to PID 1 namespace. So how this function can return `false` ever?

Moreover, function `ensureProcessInContainerWithOOMScore` is always setting OOM score to a hardcoded constant -999 ignoring configuation (`qos.KubeletOOMScoreAdj`).

### Kubernetes version

<details>

`master`, reproduced with 1.22.
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by matthyx** [comment]
> When kubelet runs in a container with PID namespace shared with the host, kubelet's PID namespace will be equal to PID 1 namespace. If kubelet runs in a container with unshared PID namespace, kubelet's PID is 1 and its PID namespace is identical to PID 1 namespace. So how this function can return `false` ever?

I don't think this method needs to change... I have make a draft PR for the default value to use the flag if present, but I would like more time to add some testing.
Maybe you can have a look: https://github.com/kubernetes/kubernetes/pull/106082 ?

**Comment by smira** [comment]
> I don't think this method needs to change... I have make a draft PR for the default value to use the flag if present, but I would like more time to add some testing. Maybe you can have a look: #106082 ?

Thanks, this PR looks good to me, as it's going to set the OOM score to the configured value. 

And in our case kubelet runs in a container (not on the host, with proper OOM score via OCI spec), so this code should be even skipped, not sure how this can be addressed.

**Comment by matthyx** [comment]
> And in our case kubelet runs in a container (not on the host, with proper OOM score via OCI spec), so this code should be even skipped, not sure how this can be addressed.

neither do I...
