### ISSUE TITLE
Request for extending vSphere v6.5 support

### ISSUE THREAD

**Issue by oomichi** [kubernetes/kubernetes#105837]
### What would you like to be added?

According to the pull request https://github.com/kubernetes/kubernetes/pull/98546 in-tree vSphere v6.5 is deprecated and it will be able to be deleted on Kubernetes v1.24.
On the other hand, VMware announced vSphere v6.5 support period is extended from the original November 15, 2021 to October 15, 2022 as https://blogs.vmware.com/vsphere/2021/03/announcing-limited-extension-of-vmware-vsphere-6-5-general-support-period.html

It is useful to see vSphere v6.5 support extension till Kubernetes v1.25 for covering the above vSphere support extension.

### Why is this needed?

We and our customers are using vSphere v6.5 for deploying Kubernetes clusters on top of the vSphere.
Then it is nice to see vSphere v6.5 support extension on Kubernetes also.

**Comment by oomichi** [comment]
@divyenpatel helped me to understand current situation about this issue. Thank you @divyenpatel  !

The summary is
- The `in-tree vSphere volume plugin` is implemented under pkg/volume/vsphere_volume/ in k8s/kubernetes repo and it supports vSphere v6.5.
- The `external vsphere CSI driver` is implemented as https://github.com/kubernetes-sigs/vsphere-csi-driver and it doesn't support vSphere v6.5.
- We (the community) is trying to migrate from the `in-tree vSphere volume plugin` to the `external vShere CSI driver` as https://github.com/kubernetes/kubernetes/pull/103523 which enables the `external vsphere CSI driver` by default.

**Comment by oomichi** [comment]
According to https://github.com/kubernetes/cloud-provider-vsphere/blob/master/docs/book/tutorials/enabling-vsphere-csi-on-an-existing-cluster.md#vsphere-requirements the `external vsphere cloud provider` also seems to require vSphere v6.7 U3 for CSI and CPI. Then `in-tree vSphere cloud provider` is just an option to operate vSphere v6.5.

Is it possible to extend keeping `in-tree vSphere cloud provider` till Kubernetes v1.27 for covering the vSphere support extension of VMware?

**Comment by neolit123** [comment]
I think all internal providers are scheduled for removal earlier but perhaps @divyenpatel and @kubernetes/sig-cloud-provider can establish if an exception is possible.

/unassign

**Comment by oomichi** [comment]
The corresponding code is still there on Kubernetes v1.25.
So I think it is fine to close this issue at this time because that matches vSphere v6.5 support.

/close
