### ISSUE TITLE
multi PV with same unique volume name mount failed

### ISSUE THREAD

**Issue by zhubuntu** [kubernetes/kubernetes#105868]
### What happened?

I have two PVs with same UniqueVolumeName. Two different pods use those PVs assigned to the same node.
The first assigned pod can run well, but the second assigned pod can't be set up correctly.

### What did you expect to happen?

My two pods both can be set up correctly.

### How can we reproduce it (as minimally and precisely as possible)?

1.  create two CSI PVs with same UniqueVolumeName
2. Create two pods using these PVs
3. Assigned two pods to the same nodes.
4. The CSI plugin must support global mount.

### Anything else we need to know?

I think this is caused because the globalmount.

As code shown below, the DeviceGloballyMounted state is checked by the UniqueVolumeName. However, when we do bind mount in csi plugin, the global mount path is  ` /var/lib/kubelet/plugins/kubernetes.io/csi/pv/{pvname}/globalmount`.
https://github.com/kubernetes/kubernetes/blob/89dd275dde0d19112f826699944f40c625c33e8e/pkg/volume/util/operationexecutor/operation_generator.go#L607

So if two pv has same UniqueVolumeName, the second pv assigned to the node will assume globalmount is set correctly, but in the real publish mount stage,  csi will found the second pv's gloabalmount path not exists. The error will be like `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/test-pv1/globalmount does not exist`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Zheaoli** [comment]
Maybe we need add a validation in APISever to forbid people create multi pvs with same UniqueVolumeName

**Comment by zhubuntu** [comment]
@Zheaoli if people need to use same UniqueVolume in multi namespace, i think multi pvs are needed.  As pvc is a resource with namespace, and one pv can only bind to one pvc.

**Comment by jsafrane** [comment]
This looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/105899. Let's continue there.
/close
