### ISSUE TITLE
Proposed graduation of scheduler metrics from alpha to stable

### ISSUE THREAD

**Issue by vantuvt** [kubernetes/kubernetes#105861]
### What would you like to be added?

I would like to propose the graduation of the following scheduler metrics from alpha to stable:

- [pending_pods](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/pkg/scheduler/metrics/metrics.go#L88)
- [preemption_attempts_total](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/pkg/scheduler/metrics/metrics.go#L81)
- [preemption_victims](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/pkg/scheduler/metrics/metrics.go#L74)
- [e2e_scheduling_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/pkg/scheduler/metrics/metrics.go#L56)
- [schedule_attempts_total](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/pkg/scheduler/metrics/metrics.go#L47)

### Why is this needed?

These metrics have been stable for at least 15 months.

**Comment by rezakrimi** [comment]
The PR for this is ready to be reviewed: #105941
