### ISSUE TITLE
Proposed graduation of apiserver metrics from alpha to stable

### ISSUE THREAD

**Issue by vantuvt** [kubernetes/kubernetes#105862]
### What would you like to be added?

I would like to propose the graduation of the following apiserver metrics from alpha to stable:

- [apiserver_response_sizes](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L118)
- [aggregator_unavailable_apiservice](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/metrics.go#L39)
- [admission_controller_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [admission_step_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [admission_webhook_admission_duration_seconds](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L236)
- [apiserver_current_inflight_requests](https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L172)

### Why is this needed?

With the exception of the `aggregator_unavailable_apiservice` metric these metrics have been stable for 2 years. The `aggregator_unavailable_apiservice` metric has been stable for 12 months.

**Comment by rezakrimi** [comment]
> A couple of renaming suggestions, since it is important to get it right before graduation:
> 
> * apiserver_response_sizes => apiserver_response_size_bytes
> * aggregator_unavailable_apiservice => aggregator_unavailable_apiservices
> 
> One concern regarding `admission_webhook_admission_duration_seconds`. It was very recently changed but the change was later reverted by #104033. In the end, the metric wasn't really changed, but it might raise the concern that some users may still need additional information from this metric so I am on the fence with this one.
> 
> Side implementation note that we will need to keep in mind if we graduate `admission_webhook_admission_duration_seconds` is that the graduation should only affect the webhook admission metric and not the other, so we will need to pass the stability level to
> 
> https://github.com/kubernetes/kubernetes/blob/0d50c969c587c8a6c16e0962118305ac652c5a6b/staging/src/k8s.io/apiserver/pkg/admission/metrics/metrics.go#L212

@dgrisonnet since all the three metrics that are created with this function are graduating to stable, do you think I should still pass the `StabilityLevel` to the method or should I just set the metrics created by this functions as stable by default?

**Comment by rezakrimi** [comment]
The PR is ready to be reviewed: #106122
