### ISSUE TITLE
SecurityContext GoDoc error in v1 types.go

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#10587]
This line of GoDoc appears to be a vestige from an earlier version of the API:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L1943

The line says SecurityContext.Privileged must match Container.Privileged.  Container.Privileged no longer exists in the v1 API.

I believe the line should be removed.  Or, replaced, in which case with what?

**Comment by erictune** [comment]
That line should be removed, as well the comment a few lines above about Container.Capabilities, which has the same problem.

**Comment by pmorie** [comment]
Fixing this one this morning.
