### ISSUE TITLE
Using Graceful Node Shutdown, but containers are evicted prematurely.

### ISSUE THREAD

**Issue by kishoreakshat** [kubernetes/kubernetes#105881]
### What happened?

Our use case is to stream fluentbit logs to an [S3 bucket](https://docs.fluentbit.io/manual/pipeline/outputs/s3) whenever an EKS managed node is terminated due to a scale-in/health failure, etc.

By its design, fluentbit containers stream buffered logs to S3 when they receive a SIGTERM/SIGKILL. With EKS node eviction, they do receive a SIGTERM with default grace period (or an overriden value if specified within pod spec's 'terminationGracePeriodSeconds' attribute) for streaming logs:

`"Killing container with a grace period override" pod="fluentbit/fluent-bit-hsrgx" podUID=2531eed0-ee65-4ef0-9135-05c3ab9b1a66 containerName="fluent-bit" containerID="docker://847367534d4755160f649e451afa6e09a2dd4c2fc3e8b7156fdb890909a6c89a" gracePeriod=30`

However ~1s later, another kill container command is sent for the fluentbit containers:

`"Killing container with a grace period override" pod="fluentbit/fluent-bit-hsrgx" podUID=2531eed0-ee65-4ef0-9135-05c3ab9b1a66 containerName="fluent-bit" containerID="docker://847367534d4755160f649e451afa6e09a2dd4c2fc3e8b7156fdb890909a6c89a" gracePeriod=2`

This causes the fluentbit container to be terminated within ~3-4s which is not an ample amount of time, which we would like to give for fluentbit to stream buffered logs (logs that have not yet being sent since last upload time) to the S3 bucket, especially when we have specified 'terminationGracePeriodSeconds' and 'shutdownGracePeriod' parameters in pod specification and kubelet config, respectively.

Please help us use this feature without premature container termination so that we can achieve reliable transmission of large log files to S3.

### What did you expect to happen?

Since we were using [Graceful Node Shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/), we had specified 300s as  'shutdownGracePeriod'. 

With inhibitor locking, Kubelet would keep running for 'shutdownGracePeriod' seconds post worker node termination workflow starts, which made us realize this could help ensure reliable delivery of logs as we had enough time for buffered logs rotation and re-transmission by FluentBit. We had also specified 150s as fluent-bit daemonset's 'terminationGracePeriodSeconds' attribute.

So, theoretically, upon node termination, pod should have being given 150s for cleanup and node should have received 300s of time for shutting down gracefully.

In practice, the kubelet did remain active for 300s post node termination, but the pods and underlying containers were prematurely terminated, ~4s after node termination workflow was triggered.

As 3-4s is not enough time for reliable log uploading, especially in case for large application log files, we expected the containers to live for all of the 'terminationGracePeriodSeconds'.

### How can we reproduce it (as minimally and precisely as possible)?

1. I created an EC2 launch template with the following UserData (substituting cluster_name for name of my cluster) and a [K8s-optimized AMI](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) specified in the Launch Template Advanced Details section to be able to use Graceful Node shutdown:

```
#!/bin/bash
set -o xtrace
/etc/eks/bootstrap.sh <cluster_name>
# Inject shutdownGracePeriod value unless it has already been set.
if ! grep -q shutdownGracePeriod /etc/kubernetes/kubelet/kubelet-config.json; 
then 
    sed -i '/"apiVersion*/a \ \ "shutdownGracePeriod": "6m",' /etc/kubernetes/kubelet/kubelet-config.json
fi

# Inject shutdownGracePeriodCriticalPods value unless it has already been set.
if ! grep -q shutdownGracePeriodCriticalPods /etc/kubernetes/kubelet/kubelet-config.json; 
then 
    sed -i '/"shutdownGracePeriod*/a \ \ "shutdownGracePeriodCriticalPods": "2m",' /etc/kubernetes/kubelet/kubelet-config.json
fi

mkdir -p /etc/systemd/logind.conf.d
cat << EOF > /etc/systemd/logind.conf.d/50-max-delay.conf
[Login]
InhibitDelayMaxSec=360
EOF

sudo systemctl restart systemd-logind

```
2. I then launched a managed nodegroup using this launch template (with Desired Size 1).

3. I then launched fluentbit daemonset pods to [stream logs to S3](http://raaviblog.com/set-up-fluent-bit-as-a-daemonset-to-send-logs-to-s3-bucket/).

4. I had the following S3 output filter configuration within fluent-bit configmap:

```
output-s3.conf: |
    [OUTPUT]
        Name s3
        Match *
        bucket /<bucket_name>/
        region <region_name>
        s3_key_format /$TAG[1]/$TAG[3]/%Y/%m/%d/
        s3_key_format_tag_delimiters .
        total_file_size 50M
        use_put_object On
        upload_timeout 10m
```

5. Once the daemonset was up and running, after around 6-7 minutes when I felt enough logs would have been generated locally, I changed the Desired Size of my managed nodegroup to 0.

6. I saw that the fluentbit daemonset did receive a SIGTERM and the log output for fluentbit pods was as follows:

```
", "stream"=>"stdout", "time"=>"2021-09-09T12:22:58.546897715Z"}]
[9546] kube.fluentbit.fluent-bit-n7q4k.fluent-bit: [1631190204.536139169, {"log"=>"", "stream"=>"stdout", "time"=>"2021-09-09T12:22:43.898295117Z"}]
", "stream"=>"stdout", "time"=>"2021-09-09T12:22:58.546900315Z"}]
[2021/09/09 12:24:26] [engine] caught signal (SIGTERM)
[2021/09/09 12:24:26] [ info] [input] pausing tail.0

```
However, Fluentbit gets only ~2-3s post this termination workflow starts and is not able to push all buffered logs properly even after receiving SIGTERM.

So, I tested with [grace value](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file#config_section) kept at 0, which theoretically means no wait time post SIGTERM/SIGKILL for fluentbit containers, however even that was not enough to push logs to S3 after receiving SIGTERM.

I also tested running 'kubectl delete pod <fluent-bit-xxx>' and I could see that fluentbit was able to rotate buffered logs to S3 before shutting down, which verified that given sufficient time, buffered logs will be rotated to the destination S3 bucket.

So, I dove deeper:

1. I launched a Managed Nodegroup using the same launch template mentioned above for Graceful Shutdown of Kubelet (with Desired Size: 1). 

2. I turned 'DeleteOnTermination' to false for the root volume attached to worker node launched as part of this Managed Nodegroup. I followed this [documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/terminating-instances.html#delete-on-termination-running-instance) for the purpose, but I mentioned "DeviceName": "/dev/xvda" inside mapping.json as that was the name of the root block device attached to my worker node EC2 instance, which I checked from the Storage tab on the instance details section on EC2 console.

3. I entered into the worker node using Connect => SSM option on the EC2 console.

4. I downloaded [eks-logs collector](https://github.com/awslabs/amazon-eks-ami/tree/master/log-collector-script/linux) script bundle on the node. 

5. I reduced Desired Size of the nodegroup to 0.

6. I waited for 2-3 minutes and executed log collection shell command (sudo bash eks-log-collector.sh). I had time leverage as kubelet was delaying node termination by shutdownGracePeriod seconds.

7. Output of eks-logs collector was saved to /var/log on the root volume of the worker node.

8. Once the worker node was terminated, I verified that the root volume attached to it was preserved and in 'Available' state.

9. I launched a plain EC2 instance directly from the EC2 console in the same AZ as the one in which this root volume was present with Amazon Linux 2 AMI and [mounted this volume device](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html#ebs-format-mount-volume) as a secondary volume to this newly launched instance.

10. I mounted the device to /data directory and hence was able to access logs from after termination of pods at /data/var/log on this new instance.

This log bundle contains kubelet logs where I observed the sequence of container termination I observed and which I have referred throughout this report.

### Anything else we need to know?

While troubleshooting this issue internally, we first came across the following log entry which was causing the fluent-bit container to be killed within 2s rather than being given the 150s I had specified as the 'terminationGracePeriodSeconds' for the fluent-bit daemonset:

`Sep 17 16:15:39 ip-172-31-35-200 kubelet: I0917 16:15:39.304701 3214 kuberuntime_container.go:661] "Killing container with a grace period override" pod="fluentbit/fluent-bit-hsrgx" podUID=2531eed0-ee65-4ef0-9135-05c3ab9b1a66 containerName="fluent-bit" containerID="docker://847367534d4755160f649e451afa6e09a2dd4c2fc3e8b7156fdb890909a6c89a" gracePeriod=2`

Upon diving deeper to find the root cause behind this issue, I came across this log entry in the Kubelet logs:

`Sep 17 18:53:25 ip-172-31-32-20.us-west-2.compute.internal kubelet[3214]: I0917 18:53:25.340338 3214 kubelet.go:2039] "Pod has completed execution and should be deleted from the API server" pod="fluentbit/fluent-bit-dvhn2" syncType="update"`

This was in response to a 'DELETE syncloop' being started by Kubelet which in turn was in response to APIserver demanding fluent-bit pods be deleted. My understanding is that it is fine and completely normal for APIserver to push for pods being terminated, once node termination begins:

`Sep 17 18:53:25 ip-172-31-32-20.us-west-2.compute.internal kubelet[3214]: I0917 18:53:25.340306    3214 kubelet.go:1951] "SyncLoop DELETE" source="api" pods=[fluentbit/fluent-bit-dvhn2]
`

My concern is that there is a function which gets called by the [DELETE handlers](https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/kubelet.go#L1947), post the DELETE syncloop being triggered: [dispatchWork](https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/kubelet.go#L2032). This function has a check to see if there is a deletion timestamp assigned to the pod and if the containers are 'terminal'. I have concluded that a 'podAndContainersAreTerminal' function (called by dispatchWork) returns true (meaning containers are terminal), due to the following line in the logs:

`Sep 17 18:53:25 ip-172-31-32-20.us-west-2.compute.internal kubelet[3214]: I0917 18:53:25.340338 3214 kubelet.go:2039] "Pod has completed execution and should be deleted from the API server" pod="fluentbit/fluent-bit-dvhn2" syncType="update"`

This should only be logged only if Deletion Timestamp has been set AND if container is 'terminal'. 

Since, fluentbit container was still running (as the containers were killed later in the kubelet logs and also as seen in 'kubectl delete pods' check where the container did not exit until it had streamed logs to S3; credential errors can also be ignored as this same setup was used for 'kubectl delete pods' as well), it is dubious as to how this container was flagged 'terminal'. 

My hypothesis is that it is due to this fault, the REMOVE syncloop was later started and a few log lines (and ~1s) later, the 2s grace period override kill container workflow was triggered:

`Sep 17 18:53:25 ip-172-31-32-20.us-west-2.compute.internal kubelet[3214]: I0917 18:53:25.347852 3214 kuberuntime_container.go:661] "Killing container with a grace period override" pod="fluentbit/fluent-bit-dvhn2" podUID=bddfbd1d-0440-43f0-8579-71638ecca86d containerName="fluent-bit" containerID="docker://12e19d2aa391c43b9ca2bd9b9b4b498097cd8b1f894ac07a16814bba1ea9432c" gracePeriod=2`

Please help us understand if judging a running container is terminal is expected and if yes, graceful shutdown is not useful in this context at all.

Also, we have tested this with both [Self-managed](https://docs.aws.amazon.com/eks/latest/userguide/worker.html) and [EKS-managed](https://docs.aws.amazon.com/eks/latest/userguide/managed-node-groups.html) nodegroups and we were able to replicate this issue in both scenarios, so we have ruled out that any Amazon EKS-specific code is causing this issue.

### Kubernetes version

<details>

```console
$ kubectl version
# v1.21
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by akshatki** [comment]
Hi @wzshiming,

Thanks for writing back. I see that you have tested Graceful Node Shutdown with Kubernetes v1.22 and there seem to be no issues. I would like to highlight a couple of points:

1. As I have specified in my original comment on the issue, I am working with Kubernetes v1.21 which is the latest version available with Amazon EKS.
2. If you go through my comments above, I have mentioned that the issue is not with Graceful Shutdown and populating 'shutdownGracePeriod' values inside the kubelet config works without issues, however it is pods on these nodes that are deleted ahead of time and their containers are not given sufficient time to stream buffered logs and shut down cleanly.

Since the DELETE Handler and its [dispatchWork](https://github.com/kubernetes/kubernetes/blob/33b5f0f1eaf5e2073e4d588095366f626ad10e68/pkg/kubelet/kubelet.go#L2169) function have changed with v1.22, I tested using Kubernetes v1.22 on Amazon EC2 instances. I replicated the setup of fluent-bit daemonset pods and I triggered termination of a worker node EC2 from the console.

I then tried to capture verbose Kubelet logs and I noticed that since pod/container terminality is no more checked and since only the pod status is patched with DELETE syncloop, there were no premature 'Killing Container' calls. However, I noticed that the containers for fluentbit daemonset were destroyed 5s after the 'Killing Containers' log entry by [cadvisor container manager](https://github.com/google/cadvisor/blob/34bbefaefe6a0168a9ef4862646987adcf6fe38f/manager/manager.go#L1044) due to node shutdown and cleanup triggered by Kubelet. 

`Nov 01 17:27:42 ip-172-31-10-69 kubelet[11747]: I1101 17:27:42.352493   11747 kuberuntime_container.go:710] "Killing container with a grace period override" pod="default/fluent-bit-kzgfz" podUID=aca2f7d7-df02-424d-aea1-3dbb9778814c containerName="fluent-bit" containerID="docker://04ad2c9082b74cd110cf8bd7b6eed2578d607771fa579794a0ded88bb4783d87" gracePeriod=30`

`Nov 01 17:27:47 ip-172-31-10-69 kubelet[11747]: I1101 17:27:47.368134   11747 manager.go:1044] Destroyed container: "/kubepods/besteffort/podaca2f7d7-df02-424d-aea1-3dbb9778814c/04ad2c9082b74cd110cf8bd7b6eed2578d607771fa579794a0ded88bb4783d87" (aliases: [k8s_fluent-bit_fluent-bit-kzgfz_default_aca2f7d7-df02-424d-aea1-3dbb9778814c_0 04ad2c9082b74cd110cf8bd7b6eed2578d607771fa579794a0ded88bb4783d87], namespace: "docker")
`

However, please do understand that the workflow of v1.22 is not my primary concern as we are using Amazon EKS where the maximum available version is v1.21, which I have explained in detail in my previous comments.

However, I will try summarizing the issue again: 

I have FluentBit pods running in my EKS v1.21 cluster and although we have set Graceful Shutdown for nodes and the setting is respected during the shutdown process, pods do not get grace period seconds to clean up and their containers are cleaned with a grace period override of 2s, right after Kubelet tries to kill them with a 30s grace period.
