### ISSUE TITLE
Exec liveness probe does not honor timeoutSeconds on 1.20.7

### ISSUE THREAD

**Issue by pawelpabich** [kubernetes/kubernetes#105962]
### What happened?

We have a liveness probe with `timeoutSeconds` set to 5 but the probe doesn't seem to be failing after 5s when the monitored endpoint takes minutes to respond.

### What did you expect to happen?

We expect the probe to fail after 5seconds if the monitored endpoint takes longer than 5 seconds to respond.

### How can we reproduce it (as minimally and precisely as possible)?

I can't share my application but hopefully, the data included here will be enough to get you started.  The only important thing about `/api/serverstatus/hosted/internal/XXX` is that this endpoint will block for XXX seconds before returning 200 code. We added it to our app to prove our theory.

This problem seems to be similar to [Exec-type liveness or readiness probes ignore timeout](https://github.com/kubernetes/kubernetes/issues/94080);

**Timeout not enforced**

![image](https://user-images.githubusercontent.com/347637/139200651-542dd39b-4ead-42f2-b369-8fdfef97a422.png)

**Timeout enforced at the curl level**

![image](https://user-images.githubusercontent.com/347637/139200783-a0c42bcc-ec96-4897-a169-d378dc6278fd.png)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"4966fd0dded6419fd23233a38c8905c67a3ea78e", GitTreeState:"clean", BuildDate:"2021-08-17T02:06:07Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Azure - AKS 1.20.7
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux aks-primary-34443167-vmss000000 5.4.0-1047-azure #49~18.04.1-Ubuntu SMP Thu Apr 22 21:28:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pawelpabich** [comment]
I will try to do it in the next few days.  Definitely need to change the logging level. Do I need to do anything once  `kublet.service`  file is updated?

```root@aks-primary-34443167-vmss000000:/etc/systemd/system# nl      
^C
    12  ExecStartPre=/bin/mount --make-shared /var/lib/kubelet

    13  ExecStartPre=-/sbin/ebtables -t nat --list
    14  ExecStartPre=-/sbin/iptables -t nat --numeric --list

    15  ExecStart=/usr/local/bin/kubelet \
    16          --enable-server \
    17          --node-labels="${KUBELET_NODE_LABELS}" \
    18          --v=2 --container-runtime=remote --runtime-request-timeout=15m --container-runtime-endpoint=unix:///run/containerd/containerd.sock \
    19          --volume-plugin-dir=/etc/kubernetes/volumeplugins \
    20          $KUBELET_FLAGS \
    21          $KUBELET_REGISTER_NODE $KUBELET_REGISTER_WITH_TAINTS

    22  [Install]
    23  WantedBy=multi-user.target
root@aks-primary-34443167-vmss000000:/etc/systemd/system#```

**Comment by Shuanglu** [comment]
just run `systemctl daemon-reload&&systemctl restart kubelet`.
i was using a nginx image with module 'echo_sleep' to reproduce but couldn't repro https://github.com/nginxinc/docker-nginx/tree/master/modules. You may try something similar in your cluster to isolate.

**Comment by SergeyKanzhelev** [comment]
Please take a look at [ExecProbeTimeout feature flag](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#:~:text=Topology%20Spread%20Constraints.-,execprobetimeout,-%3A%20Ensure%20kubelet%20respects) This is likely not turned on

**Comment by pawelpabich** [comment]
I'm using AKS and I don't see any API that would return a list of enabled/disabled feature gates. Any idea how to get that?

**Comment by SergeyKanzhelev** [comment]
if you have access to kubelet logs, you will see a message about that. Search for " ExecProbeTimeout".

**Comment by SergeyKanzhelev** [comment]
Unfortunately turning this flag on to have the bug fixed, may introduce unexpected failures as the default timeout is 1 second if not specified. And it can make many probes fail unexpectedly.

**Comment by pawelpabich** [comment]
Found this line in the logs:
`I1105 07:17:47.953041    5222 flags.go:59] FLAG: --feature-gates="DynamicKubeletConfig=false,RotateKubeletServerCertificate=true"`

Looking at the gates doco again, it says that the flag is on by default.  
> <html>
<body>


ExecProbeTimeout | true | GA | 1.20 | -
-- | -- | -- | -- | --



</body>
</html>

This means that the timeout should be respected unless the flag is turned off? Am I missing something here?

**Comment by pawelpabich** [comment]
Confirmed with Azure Support. These are the only gates that are explicitly set.

> --feature-gates=DynamicKubeletConfig=false,RotateKubeletServerCertificate=true

**Comment by pawelpabich** [comment]
@SergeyKanzhelev should we reopen this issue?

**Comment by SergeyKanzhelev** [comment]
CC: @jackfrancis  can you take a look?

**Comment by jackfrancis** [comment]
ACK

**Comment by jackfrancis** [comment]
Hi @pawelpabich, I'm a bit confused by the "Timeout not enforced" screenshot. In fact that screenshot shows that the liveness probe is restarting the container in the pod events logs.

We are definitely testing timeout failures in Azure scenarios:

https://github.com/Azure/aks-engine/blob/master/test/e2e/kubernetes/workloads/exec-liveness-assume-1-second-default-timeout.yaml

In addition, we have regular upstream Kubernetes E2E coverage for this scenario:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/node/container_probe.go#L259

I'm not sure there is a regression here.

**Comment by pawelpabich** [comment]
Hi @jackfrancis,

In the first case, **without** curl timeout,  it took K8s 18 minutes to fail the liveness probe. In the second case, **with** curl timeout, it took K8s just under 5 minutes to do the same. 

The health endpoint is configured to sleep for 120 seconds before it responds. (note 120 and the end of the url).

The timeout is set to 5 seconds and the period is set to 30 seconds.  K8s should fail the probe in ~ 5 minutes (10 x 5s + 9 * 30s )

**Comment by jackfrancis** [comment]
Note that the startup probe is also failing. @SergeyKanzhelev can you confirm that the liveness probe isn't engaged until startup probe is all clear?

The 10 failures over 18 mins roughly matches the 5 second timeout + 30 second periodicity + 10 failures probe criteria. By definition, such a liveness probe will take a long time to fail, certainly not 5 seconds. What are you expecting from your liveness probe behaviors given such a configuration?

**Comment by SergeyKanzhelev** [comment]
> Note that the startup probe is also failing. @SergeyKanzhelev can you confirm that the liveness probe isn't engaged until startup probe is all clear?

this is true, as [documented](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#:~:text=the%20kubelet%20uses%20startup%20probes%20to%20know%20when%20a%20container%20application%20has%20started.%20if%20such%20a%20probe%20is%20configured%2C%20it%20disables%20liveness%20and%20readiness%20checks%20until%20it%20succeeds).

**Comment by SergeyKanzhelev** [comment]
/label needs-information

(likely not a bug, but needs a bit more information I think)

**Comment by pawelpabich** [comment]
Sorry for the delay.

> The 10 failures over 18 mins roughly matches the 5 second timeout + 30 second periodicity + 10 failures probe criteria. 

I might be missing something here but 10 x ( 5 + 30)  ~ 6 minutes.   How did you arrive at 18minutes?

> By definition, such a liveness probe will take a long time to fail, certainly not 5 seconds. What are you expecting from your liveness probe behaviors given such a configuration?

Based on my configuration I expect the probe to fail after  (10 * 5 + 9 * 30) ~6 minutes.  This roughly but not exactly aligns with the second screenshot where the timeout is enforced by `curl`. 

My assumption here, possibly incorrect, is that `Linvess Probe Failed ` event represents all 10 retries. 
Is there a way for me to find this information somewhere else?
