### ISSUE TITLE
short-circuit tests if the only thing that changed was a squash or commit message

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#105988]
I feel bad wasting CI time just to fix commit messages.  Asking people to squash commits forces CI to run and the `lgtm` to be lost.

Idea!

Could we run something to prove that the code has not changed since "before" and save time?

For example:  `find . -not \( -type d -name .git -prune \) -type f | xargs cat | md5sum` takes < 3 seconds to run and can elide a whole CI run.  We just need to squirrel that state away somewhere.

Am I just procrastinating?   Maybe.  Still....

**Comment by thockin** [comment]
running CI at merge time seems appropriate and correct, but if I pass all CI, then fix a commit message, and we can prove that code didn't change, I don't see why we would need to run tests again until it gets to the merge queue?

**Comment by thockin** [comment]
LOL at me filing a new bug that is the same as a bug I filed almost 4 years ago.

**Comment by BenTheElder** [comment]
> then fix a commit message, and we can prove that code didn't change, I don't see why we would need to run tests again until it gets to the merge queue?

Agreed, I think the `store_tree_hash` LGTM functionality could be extended to cover this case, but I'm not sure how much refactoring it would take. cc @alvaroaleman @cjwagner @chaodaiG @matthyx, thoughts? Or perhaps we shoudl follow up on https://github.com/kubernetes/test-infra/issues/19147

**Comment by cjwagner** [comment]
> Agreed, I think the `store_tree_hash` LGTM functionality could be extended to cover this case, but I'm not sure how much refactoring it would take.

It's unclear to me what additional functionality is required. Isn't the existing behavior sufficient, it just needs to be enabled?

**Comment by matthyx** [comment]
I think it was never enabled on k/k...

**Comment by alvaroaleman** [comment]
The current behavior would retain lgtm but not testresults. Uhm, I suppose we would need to somehow maintain a mapping and make (at minimum) `trigger` not create new jobs if the same tree hash was already tested and tide consider a test for a different sha with the same treehash as valid results? It is likely a solveable problem but not a trivial one and will need a design.

**Comment by alvaroaleman** [comment]
Also I might be wrong but I seem to remember there was _some_ technical reason why the store_tree_hash was not enabled globally. I can't remember what that reason was though,

**Comment by matthyx** [comment]
On the other end we need to separate the ci run on the current branch from the other one on the resulting merge, which cannot be cached.

**Comment by matthyx** [comment]
> Also I might be wrong but I seem to remember there was _some_ technical reason why the store_tree_hash was not enabled globally. I can't remember what that reason was though,

Fear?

**Comment by matthyx** [comment]
Who's taking the point? I'll go on PTO from next Wednesday until the 17th of November, but if it can wait I'll have a look.

**Comment by matthyx** [comment]
/assign
Let me look at this in the next few days.

**Comment by BenTheElder** [comment]
we should probably start by even rolling out the retain-lgtm feature more widely, I think we still haven't enabled it in this repo. xref: https://github.com/kubernetes/test-infra/pull/24134#issuecomment-992717402

**Comment by matthyx** [comment]
> we should probably start by even rolling out the retain-lgtm feature more widely, I think we still haven't enabled it in this repo. xref: [kubernetes/test-infra#24134 (comment)](https://github.com/kubernetes/test-infra/pull/24134#issuecomment-992717402)

Good idea... in the meantime I should come back to this issue :-/

**Comment by BenTheElder** [comment]
no worries! I think this will be tough to roll out, but something we should accept as a valid improvement that would ideally happen someday 😅 

in kubernetes/test-infra#24134 you can see that you are not alone in getting too busy for this 🙃

**Comment by matthyx** [comment]
/reopen
Ok, let's not forget this...
