### ISSUE TITLE
ServiceAccountIssuerDiscovery conformance test failing in upgrade tests

### ISSUE THREAD

**Issue by mtaufen** [kubernetes/kubernetes#105942]
### Which jobs are failing?

https://storage.googleapis.com/k8s-triage/index.html?sig=auth

Time | Job | Test
-- | -- | --
10/27/2021, 3:46:58 AM | ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel | [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
10/27/2021, 3:08:57 AM | ci-kubernetes-e2e-gce-stable1-latest-upgrade-master-parallel | [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
10/27/2021, 2:56:57 AM | ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-parallel | [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]
10/27/2021, 1:46:57 AM | ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel | [sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

For example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-new-parallel/1453312239984447488

### Which tests are failing?

[sig-auth] ServiceAccounts ServiceAccountIssuerDiscovery should support OIDC discovery of service account issuer [Conformance]

### Since when has it been failing?

At least October 12, e.g. https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-master-parallel&include-filter-by-regex=ServiceAccountIssuerDiscovery

### Reason for failure (if possible)

API server's cert doesn't seem to be signed for either the internal IP the test Pod tries to access it at or the cluster-local service at `https://kubernetes.default.svc.cluster.local`. For example:

```
I1027 11:33:52.650] 2021/10/27 11:33:10 Full, not-validated claims: 
I1027 11:33:52.650] openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-1723:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1635334989, NotBefore:1635334389, IssuedAt:1635334389, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-1723", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"1f291458-f06f-4eb8-aea5-2447c8788bf6"}}}
I1027 11:33:52.651] 2021/10/27 11:33:10 OK: Constructed OIDC provider for issuer https://kubernetes.default.svc.cluster.local
I1027 11:33:52.651] 2021/10/27 11:33:10 failed to validate with in-cluster discovery: failed to verify signature: fetching keys oidc: get keys failed Get "https://10.138.0.6:443/openid/v1/jwks": x509: certificate is valid for 35.199.164.122, 10.0.0.1, not 10.138.0.6
I1027 11:33:52.651] 2021/10/27 11:33:10 falling back to validating with external discovery
I1027 11:33:52.651] 2021/10/27 11:33:10 OK: got issuer https://kubernetes.default.svc.cluster.local
I1027 11:33:52.651] 2021/10/27 11:33:10 Full, not-validated claims: 
I1027 11:33:52.652] openidmetadata.claims{Claims:jwt.Claims{Issuer:"https://kubernetes.default.svc.cluster.local", Subject:"system:serviceaccount:svcaccounts-1723:default", Audience:jwt.Audience{"oidc-discovery-test"}, Expiry:1635334989, NotBefore:1635334389, IssuedAt:1635334389, ID:""}, Kubernetes:openidmetadata.kubeClaims{Namespace:"svcaccounts-1723", ServiceAccount:openidmetadata.kubeName{Name:"default", UID:"1f291458-f06f-4eb8-aea5-2447c8788bf6"}}}
I1027 11:33:52.652] 2021/10/27 11:33:10 Get "https://kubernetes.default.svc.cluster.local/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

### Relevant SIG(s)

/sig auth

**Comment by mtaufen** [comment]
To summarize, the overall issue here is that we can get the discovery doc, but the JWKS URI in the discovery doc reports an IP that doesn't actually work. We think it's because `--advertise-address` isn't set to the external IP of the control plane VM.

**Comment by mtaufen** [comment]
@justinsb recommended @cheftako since this seems to be a problem with the test setup

/assign @cheftako

**Comment by justinsb** [comment]
Also cc @jiahuif

**Comment by liggitt** [comment]
/assign @bowei 

talked with Walter, who didn't have pointers on the networking differences.

@bowei, can you route to someone who can help dig into the network differences between the envs to figure out why auto-network-discovery isn't working as expected?

**Comment by mtaufen** [comment]
@liggitt @bowei I assume this was fixed or I'd have probably gotten reminded about it before the triage bot marked the issue rotten. Can we confirm and close?

**Comment by mtaufen** [comment]
😢

**Comment by mtaufen** [comment]
I'll poke @bowei about it and see if anyone ever looked into it

**Comment by mtaufen** [comment]
@liggitt it looks like testgrid dashboards have moved since this was filed, do you have up to date links?
