### ISSUE TITLE
High CPU Utilization in kube-apiserver when a large number of CRDs are created

### ISSUE THREAD

**Issue by ulucinar** [kubernetes/kubernetes#105932]
### What happened?

In [Crossplane](https://crossplane.io/), we would like to register thousands of CRDs in a single cluster representing the many Cloud services possibly from multiple Cloud Providers. In our early trials with kind clusters, we have observed that simultaneously posting just over 700 CRDs results in a CPU-utilization spike in kube-apiserver, due to the background OpenAPI spec publishing job. We were also made aware of the memory consumption [issue](https://github.com/kubernetes/kubernetes/issues/101755) during CRD creation. 

We made similar observations in a GKE cluster on which we installed  over 650 CRDs, making the total 685. Unfortunately, we could not identify the root cause but we have observed the cluster flipping between the "repairing" state and the "available" state for an extended period of time. Our observation is that the cluster could come out of the repairing state but for a couple of times, it was in repairing state again, with no new CRD registrations or object creations from our side. The only probes we utilized during this period were `kubectl get` commands. 

In [our tests](https://github.com/crossplane-contrib/terrajet/issues/47#issuecomment-920316141), we have observed that on an arm64 machine with 8 CPU cores, API server enters a high CPU utilization period of about 20 min after 750+ CRDs are created. If the API server saturates the CPU resources allocated to it, this may also disrupt its services. So we have a couple of questions:
1. Can we expect the fix for the memory issue referenced above improve the situation with the CPU?
2. Are there any plans for introducing the number of CRDs in a cluster as a scalability dimension in the [thresholds document](https://github.com/kubernetes/community/blob/master/sig-scalability/configs-and-limits/thresholds.md)? If so, is it reasonable to expect our use cases covered?
3. Is it possible/reasonable to turn off the `/openapi/v2` endpoint to prevent aggregation of the OpenAPI schemas of the CRDs? Who are the clients of this endpoint?
4. In the GKE case, is there a way to monitor kube-apiserver CPU/memory consumption, crashes, etc.? So that we can reason about our empirical observations described above.

### What did you expect to happen?

We were not expecting to observe CPU usage spikes for extended periods in our tests. For the GKE cluster experiment, we were not expecting service disruptions. 

### How can we reproduce it (as minimally and precisely as possible)?

Simultaneously create a large number (>650) of CRDs with OpenAPI schemas.

### Anything else we need to know?

It looks like the average schema size in bytes per CRD could be a relevant parameter. If needed, we can supply those numbers assuming schemas are serialized in JSON. If you'd like to see some example CRDs we used in the above observations, please take a look at this [branch](https://github.com/ulucinar/provider-tf-azure/tree/fix-ps-670/package/crds) of one of the Crossplane providers.

### Kubernetes version

<details>
v1.21.0 in local tests where we observed high CPU utilization. <br>
v1.20.10-gke.301 for GKE: <br>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:11:29Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.301", GitCommit:"17ad7bd6afa01033d7bd3f02ce5de56f940a915d", GitTreeState:"clean", BuildDate:"2021-08-24T05:18:54Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by negz** [comment]
Our initial tests show that https://github.com/kubernetes/kube-openapi/pull/251 is likely to fix this issue. See https://github.com/crossplane/crossplane/issues/2649#issuecomment-956914007 for details.

**Comment by Jefftree** [comment]
Just to recap, I think we've all pinpointed serialization to be the main culprit of the high resource usage. This issue is magnified when applying 100s of CRDs in a short time period since we'll be repeating the serialization process [per CRD create](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/controller/openapi/controller.go#L194). https://github.com/kubernetes/kube-openapi/pull/251 reduces the frequency of serialization by doing it "lazily" only when a get request is received on the OpenAPI spec. 

The underlying issue is that serialization of a giant aggregated OpenAPI spec takes a lot of resources. [OpenAPI v3](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2896-openapi-v3/README.md) aims to solve this issue by not publishing the aggregated spec and only publishing specs per group/version but it'll be a while before that becomes GA. In the short term, reducing the frequency of the serializations via https://github.com/kubernetes/kube-openapi/pull/251 looks to provide good results (seen in https://github.com/crossplane/crossplane/issues/2649#issuecomment-956914007) and is something we should look to merge/cherrypick

**Comment by roycaihw** [comment]
Also @Jefftree pointed out that we [build proto from json](https://github.com/kubernetes/kube-openapi/blob/ec1f4c89925aaed16de489e6daa816bed3bd2811/pkg/handler/handler.go#L105-L112) today. We probably should look into building proto from Go structure directly. With lazy marshaling, that would help us eliminate the json serialization completely (assuming everyone uses proto)

**Comment by liggitt** [comment]
> We probably should look into building proto from Go structure directly. With lazy marshaling, that would help us eliminate the json serialization completely (assuming everyone uses proto)

be careful about type mismatches that got covered up by serialization round tripping (int vs int64, empty list vs nil, etc) that would make deepequal checks fail
