### ISSUE TITLE
ClusterTrafficPolicy on Kernelspace windows proxy doesn't properly respond to NodePortHealthChecks

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#105918]
### What happened?

See #62046  for details.  

Passthrough loadbalancing fails bc healthchecks fail.  

In GKE this is noticeable BUT very hard to see bc GKE ALWAYS will be able to 
find a HEALTHY linux node... so it results in a subtle degradation of performance, (due to a second hop)
but not a functional problem that is noticebale to the casual end user. 

### What did you expect to happen?

We would like the windows kernelspace proxy to be fancy enough to support native GKE loadbalancing by supporting HealthChecks properly

### How can we reproduce it (as minimally and precisely as possible)?

Run any app with clusterTrafficPolicy=local and observe (using some kind of measurment apparatus) the fact that two hops occur.

-  just run `local` as your clusterTrafficPolicy and watch traffic to the pod fail..
- just run `cluster` and turn off all your linux nodes, and then watch traffic to the pod fail <-- 

### Anything else we need to know?

thanks to @anfernee for walking us through this in sig-windows today ! 

![image](https://user-images.githubusercontent.com/826111/138935257-b8635516-2c95-4288-857f-772f4f046cc3.png)

### Kubernetes version

<details>

```console
$ kubectl main
```

</details>

### Cloud provider

<details>
GKE or any other cloud that loadbalances to the kernelspace proxy, presumeably
</details>

### OS version

<details>

```console
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by marosset** [comment]
/lifecycle stale
@phillipsj as FYI

**Comment by marosset** [comment]
https://github.com/kubernetes/kubernetes/issues/106636 might be related

**Comment by anfernee** [comment]
Correct. This has been resolved by #99287. We created this bug in one of the sig-windows meetings when we dig deep for code review. I think this could be closed.

**Comment by jsturtevant** [comment]
Thanks for the confirmation! If there are other issues we can follow up with a new issue.
/close

**Comment by marosset** [comment]
/close
(see above comment)
