### ISSUE TITLE
Do we still need {verify,update}-bazel.sh ?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#105925]

**Comment by BenTheElder** [comment]
This is intended to be removed once there are no active branches with bazel. 1.19 was still supported last I checked.

https://github.com/kubernetes/enhancements/issues/2420

We have some other cleanup pending the final turndown of bazel branches.

**Comment by BenTheElder** [comment]
1.19 just had it's last patch release a week ago 🙃, these are removed now.
