### ISSUE TITLE
Resource temporarily unavailable: Due to logs filling up /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io

### ISSUE THREAD

**Issue by prashilgupta** [kubernetes/kubernetes#105928]
### What happened?

/run partition is becoming full, making containerd and kubernetes unusable

df -ah /run
Filesystem Size Used Avail Use% Mounted on
tmpfs 395M 395M 0 100% /run

kubectl get pods -A
bash: fork: retry: Resource temporarily unavailable
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x404fcf7 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x404fcf7
stack: frame={sp:0x7fff8dd7b3e8, fp:0x0} stack=[0x7fff8dd5c950,0x7fff8dd7b990)
00007fff8dd7b2e8: 0000000000000037 0000000000000000
00007fff8dd7b2f8: 0000000000000000 0000000000000000
00007fff8dd7b308: 0000000000000001 0000000007906d60
00007fff8dd7b318: 0000000000000037 0000000007c42e20
00007fff8dd7b328: 00007fff8dd7b360 00007fff8dd7b3f0
00007fff8dd7b338: 000000000405281f 0000000000000000
00007fff8dd7b348: 000000000550fc96 00007fff00000000
00007fff8dd7b358: 00007fff8dd7b378 0000003000000010
00007fff8dd7b368: 00007fff8dd7b5c0 00007fff8dd7b4f0
00007fff8dd7b378: 0000000000000000 0000000000000000
00007fff8dd7b388: 0000000000000000 0000000000000000
00007fff8dd7b398: 0000000000000000 5f64616572687470
00007fff8dd7b3a8: 6620657461657263 52203a64656c6961
00007fff8dd7b3b8: 20656372756f7365 7261726f706d6574
00007fff8dd7b3c8: 76616e7520796c69 00656c62616c6961
00007fff8dd7b3d8: 000000000042c825 <runtime.(*pageAlloc).update+1285> 000000000550fc96
00007fff8dd7b3e8: <000000000404fd38 0000000000000000
00007fff8dd7b3f8: 000000000404d1b0 0000000000000000
00007fff8dd7b408: 00007f6bbb506000 00007f6bbb506000
00007fff8dd7b418: 000000000405488d 0000000000000001
00007fff8dd7b428: 000000000405069e 0000000007c42e20
00007fff8dd7b438: 0000000000000000 00007fff8dd7b49f
00007fff8dd7b448: 0000000000000001 0000000000000001
00007fff8dd7b458: 0000000007906d60 000000000000000a
00007fff8dd7b468: 0000000007906dec 00007fff8dd7b690
00007fff8dd7b478: 00007fff8dd7b7a8 0000000007906d60
00007fff8dd7b488: 000000000404b79f 0000000000000000
00007fff8dd7b498: 0a007fff8dd7b7a8 0000000007906d60
00007fff8dd7b4a8: 0000000004050b41 00007fff8dd7b7a8
00007fff8dd7b4b8: 0000000007906d60 000000000550fc96
00007fff8dd7b4c8: 0000000003fa2f8a 0000003000000008
00007fff8dd7b4d8: 00007fff8dd7b5c0 00007fff8dd7b4f0
runtime: unknown pc 0x404fcf7
stack: frame={sp:0x7fff8dd7b3e8, fp:0x0} stack=[0x7fff8dd5c950,0x7fff8dd7b990)
00007fff8dd7b2e8: 0000000000000037 0000000000000000
00007fff8dd7b2f8: 0000000000000000 0000000000000000
00007fff8dd7b308: 0000000000000001 0000000007906d60
00007fff8dd7b318: 0000000000000037 0000000007c42e20
00007fff8dd7b328: 00007fff8dd7b360 00007fff8dd7b3f0
00007fff8dd7b338: 000000000405281f 0000000000000000
00007fff8dd7b348: 000000000550fc96 00007fff00000000
00007fff8dd7b358: 00007fff8dd7b378 0000003000000010
00007fff8dd7b368: 00007fff8dd7b5c0 00007fff8dd7b4f0
00007fff8dd7b378: 0000000000000000 0000000000000000
00007fff8dd7b388: 0000000000000000 0000000000000000
00007fff8dd7b398: 0000000000000000 5f64616572687470
00007fff8dd7b3a8: 6620657461657263 52203a64656c6961
00007fff8dd7b3b8: 20656372756f7365 7261726f706d6574
00007fff8dd7b3c8: 76616e7520796c69 00656c62616c6961
00007fff8dd7b3d8: 000000000042c825 <runtime.(*pageAlloc).update+1285> 000000000550fc96
00007fff8dd7b3e8: <000000000404fd38 0000000000000000
00007fff8dd7b3f8: 000000000404d1b0 0000000000000000
00007fff8dd7b408: 00007f6bbb506000 00007f6bbb506000
00007fff8dd7b418: 000000000405488d 0000000000000001
00007fff8dd7b428: 000000000405069e 0000000007c42e20
00007fff8dd7b438: 0000000000000000 00007fff8dd7b49f
00007fff8dd7b448: 0000000000000001 0000000000000001
00007fff8dd7b458: 0000000007906d60 000000000000000a
00007fff8dd7b468: 0000000007906dec 00007fff8dd7b690
00007fff8dd7b478: 00007fff8dd7b7a8 0000000007906d60
00007fff8dd7b488: 000000000404b79f 0000000000000000
00007fff8dd7b498: 0a007fff8dd7b7a8 0000000007906d60
00007fff8dd7b4a8: 0000000004050b41 00007fff8dd7b7a8
00007fff8dd7b4b8: 0000000007906d60 000000000550fc96
00007fff8dd7b4c8: 0000000003fa2f8a 0000003000000008
00007fff8dd7b4d8: 00007fff8dd7b5c0 00007fff8dd7b4f0

goroutine 1 [runnable, locked to thread]:
text/template/parse.(*lexer).nextItem(...)
/usr/local/go/src/text/template/parse/lex.go:195
text/template/parse.(*Tree).next(...)
/usr/local/go/src/text/template/parse/parse.go:74
text/template/parse.(*Tree).nextNonSpace(...)
/usr/local/go/src/text/template/parse/parse.go:112
text/template/parse.(*Tree).action(0xc0002c59e0, 0xc0002e62a0, 0xa)
/usr/local/go/src/text/template/parse/parse.go:385 +0x672
text/template/parse.(*Tree).textOrAction(0xc0002c59e0, 0x0, 0x0)
/usr/local/go/src/text/template/parse/parse.go:366 +0x319
text/template/parse.(*Tree).itemList(0xc0002c59e0, 0x4bc49d1, 0x5, 0x10)
/usr/local/go/src/text/template/parse/parse.go:346 +0x2cf
text/template/parse.(*Tree).parseControl(0xc0002c59e0, 0xc0006e6c00, 0x4bc49d1, 0x5, 0x0, 0x0, 0xc00076cd80, 0x0, 0x0)
/usr/local/go/src/text/template/parse/parse.go:483 +0xf8
text/template/parse.(*Tree).rangeControl(0xc0002c59e0, 0x54456e8, 0xc0006e6c80)
/usr/local/go/src/text/template/parse/parse.go:525 +0x4c
text/template/parse.(*Tree).action(0xc0002c59e0, 0xc00060c5a0, 0x8)
/usr/local/go/src/text/template/parse/parse.go:395 +0x565
text/template/parse.(*Tree).textOrAction(0xc0002c59e0, 0x0, 0x0)
/usr/local/go/src/text/template/parse/parse.go:366 +0x319
text/template/parse.(*Tree).parse(0xc0002c59e0)
/usr/local/go/src/text/template/parse/parse.go:310 +0x247
text/template/parse.(*Tree).Parse(0xc0002c59e0, 0x4d8938f, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc00060c2d0, 0xc00074dfd0, 0x2, ...)
/usr/local/go/src/text/template/parse/parse.go:246 +0x23b
text/template/parse.Parse(0x4bc433c, 0x5, 0x4d8938f, 0xf0, 0x0, 0x0, 0x0, 0x0, 0xc00074dfd0, 0x2, ...)
/usr/local/go/src/text/template/parse/parse.go:65 +0x11d
text/template.(*Template).Parse(0xc0006e6bc0, 0x4d8938f, 0xf0, 0x8, 0x416e2c, 0x203000)
/usr/local/go/src/text/template/template.go:201 +0x825
github.com/rancher/k3s/vendor/github.com/opencontainers/runc/libcontainer.init()
/go/src/github.com/rancher/k3s/vendor/github.com/opencontainers/runc/libcontainer/generic_error.go:12 +0xa6

goroutine 6 [chan receive]:
github.com/rancher/k3s/vendor/k8s.io/klog/v2.(*loggingT).flushDaemon(0x7c0d000)
/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:1164 +0x8b
created by github.com/rancher/k3s/vendor/k8s.io/klog/v2.init.0
/go/src/github.com/rancher/k3s/vendor/k8s.io/klog/v2/klog.go:418 +0xdf

goroutine 84 [chan send]:
text/template/parse.(*lexer).emit(...)
/usr/local/go/src/text/template/parse/lex.go:157
text/template/parse.lexFieldOrVariable(0xc0007d0d00, 0x9, 0x9)
/usr/local/go/src/text/template/parse/lex.go:516 +0x147
text/template/parse.lexField(0xc0007d0d00, 0x4e03c30)
/usr/local/go/src/text/template/parse/lex.go:481 +0x34
text/template/parse.(*lexer).run(0xc0007d0d00)
/usr/local/go/src/text/template/parse/lex.go:230 +0x37
created by text/template/parse.lex
/usr/local/go/src/text/template/parse/lex.go:223 +0x14b

rax 0x0
rbx 0x0
rcx 0x404fcf7
rdx 0x0
rdi 0x2
rsi 0x7fff8dd7b3f0
rbp 0x7fff8dd7b3f0
rsp 0x7fff8dd7b3e8
r8 0xa
r9 0x55241cf
r10 0x8
r11 0x246
r12 0x550fc96
r13 0x7fff8dd7b690
r14 0x52f3864
r15 0x0
rip 0x404fcf7
rflags 0x246
cs 0x33
fs 0x0
gs 0x0

### What did you expect to happen?

Have a way to limit log file of containerd in /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io

:/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io# ls -lah 7d99079fde994c2c54c695ccc47eead5336305e083afdaf585120686d5b498d5/log.json
-rw-r--r-- 1 root root 35M Oct 26 08:00 7d99079fde994c2c54c695ccc47eead5336305e083afdaf585120686d5b498d5/log.json

### How can we reproduce it (as minimally and precisely as possible)?

Have Installed K3s and running since 65 days
one of the pods has liveliness probe configured on alpine based keepalived pod
livenessProbe:
exec:
command:
- pidof
- keepalived
failureThreshold: 3
periodSeconds: 10
successThreshold: 1
timeoutSeconds: 1
This probe is causing some issue we are suspecting
:/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io# ls -lah 7d99079fde994c2c54c695ccc47eead5336305e083afdaf585120686d5b498d5/log.json
-rw-r--r-- 1 root root 35M Oct 26 08:00 7d99079fde994c2c54c695ccc47eead5336305e083afdaf585120686d5b498d5/log.json

### Anything else we need to know?

Posted in k3s forum also https://github.com/k3s-io/k3s/issues/4327

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}```

</details>


### Cloud provider

<details>
N/A
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux ztna-gateway 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux



</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/close

since it's likely not a k8s bug
