### ISSUE TITLE
Logs from kubemark master are not exported

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#105927]
It seems that our logexporter for kubemark stopped exporting metrics from kubemark masters, e.g. this run:
https://gcsweb.k8s.io/gcs/sig-scalability-logs/pull-kubernetes-kubemark-e2e-gce-big/1452741046508195840

@kubernetes/sig-scalability @marseel

**Comment by NikhilSharmaWe** [comment]
@wojtek-t Just want to ask that am I thinking reasonable here to solve this issue.
1. logexporterGCSPath argument should be added to kubermarkDown function.
2. logexporterGCSPath should also be added in exec.command
3. log.Printf("Dumping logs for kubemark master: %s", logexporterGCSPath) should be added at place of log.Printf statement in the function.
Don't know what to do with cmd.Env.

**Comment by jkaniuk** [comment]
@tosi3k, @marseel for visibility

**Comment by mborsz** [comment]
@NikhilSharmaWe I think this is reasonable. I added one comment to that PR. We can move the review there.

**Comment by NikhilSharmaWe** [comment]
@mborz @wojtek-t  could you please confirm the changes made and get [this PR](https://github.com/kubernetes/test-infra/pull/24201) merged.
