### ISSUE TITLE
Add the alias of .dockerconfigjson

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/kubernetes#106035]
### What would you like to be added?

https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#inspecting-the-secret-regcred
The Secret specified by pod.spec.imagePullSecrets is .dockerconfigjson, can we add a new field to define it.

### Why is this needed?

We are already using Containerd, here it is still Docker that doesn’t feel suitable.
As a step to remove dockershim, I think it is still very necessary, but I am not sure which name is better.

**Comment by wzshiming** [comment]
Although this involves API changes, it is very small. Is it necessary to write KEP?

**Comment by liggitt** [comment]
/remove-sig auth

I'll defer to sig-node on whether the feature is desired. Since it involves user-facing API changes, yes, a KEP is needed.

**Comment by dims** [comment]
+1 to do this with a KEP. thanks @wzshiming

**Comment by pacoxu** [comment]
It involves new alias but is compatible with the old one. It sounds acceptable.

**Comment by adisky** [comment]
@wzshiming is it really needed? IMO `.dockerconfigjson` is not related with dockershim, dockerconfig.json is just docker standard to provide authentication credentials for registry, It is used by kubelet to fetch image credentials for container. 
We already have a replacement in the form of external credential provider. May be we can remove/disable this docker credential provider as out of tree credential providers goes beta and add an alternative out of tree plugin to https://github.com/kubernetes-sigs. I have created one [sample plugin already]( https://github.com/adisky/sample-credential-provider) need to move to k8s-sigs if gets approval.

cc @dims @liggitt thoughts?

**Comment by liggitt** [comment]
I wouldn't drop support for this format... the motivation behind out-of-tree credential providers was to avoid carrying large/complex cloud-provider-specific libraries in-tree. The secret-based credential provider is very lightweight and non-cloud-provider specific.

**Comment by liggitt** [comment]
I don't particularly think it's worth the effort to define new API constants and propagate out API changes just to support a new name

**Comment by adisky** [comment]
> I wouldn't drop support for this format... the motivation behind out-of-tree credential providers was to avoid carrying large/complex cloud-provider-specific libraries in-tree. The secret-based credential provider is very lightweight and non-cloud-provider specific.
> 
> I don't particularly think it's worth the effort to define new API constants and propagate out API changes just to support a new name

Agreed on both the points, Thanks for the inputs

**Comment by chris-short** [comment]
To be clear, this isn't a blocker for 1.24 release?

@liggitt @dims @chrisnegus @nate-double-u

**Comment by chris-short** [comment]
I don't think this needs to be worked on as part of the dockershim docs cleanup.
