### ISSUE TITLE
measure the relative cost (cpu/memory) for deep copies

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#106094]
### What happened?

the apiserver makes a deep copy of an object in several code sites while serving a request by using `DeepCopyObject()` function. We want to measure the relative cost (cpu/memory) for deep copies by using benchmark testing to better understand the impact.

Recently we have added a deep copy for this PR - https://github.com/kubernetes/kubernetes/pull/94986, knowing the relative cost would help us understand how much impact a new deep copy can incur.

**Comment by tkashem** [comment]
/sig api-machinery

cc @liggitt

**Comment by fedebongio** [comment]
/cc @apelisse 
not an urgent priority
/triage accepted

**Comment by MadhavJivrajani** [comment]
@tkashem are you working on this? If not, would you mind if I tried taking it up?

**Comment by tkashem** [comment]
sure, give it a try.

/assign @MadhavJivrajani

**Comment by NikhilSharmaWe** [comment]
@tkashem I have not worked on testing before, could you please guide me a little on how can I benchmark test the cluster or code for getting info about the relative cost (cpu/memory) for deep copies. By this I will gain some experience in testing space.

**Comment by MadhavJivrajani** [comment]
@NikhilSharmaWe 👋🏼 
I'm currently working on this and will document everything on this issue if you'd like to follow along and pitch in with questions/feedback! :)

**Comment by NikhilSharmaWe** [comment]
@MadhavJivrajani that will be great.
Thank you.
