### ISSUE TITLE
Some volumes mix "what" and "how" in API

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10603]
The GCE PD volume (and several others) have a `ReadOnly` flag alongside all of the fields that identify a PD.  This works fine in plain old "mount a volume" mode - the user specifies in their pod just what they want (a specific PD) and how they want it (read-only vs read-write).

The problem arises with PersistentVolumes - they also hold the same VolumeSource struct with the PD name and the ReadOnly flag.  This is wrong because the ReadOnly flag is not an attribute of the Pers.Vol., it is an attribute of the Claim (which indeed has a ReadOnly flag).
#10424 plumbs that down, but I find it to be a bit clumsy still.  This is an area the API can get better.  Maybe something like moving ReadOnly out of each volume and into the `Volume` struct (making it `{Name, ReadOnly, VolumeSource}`)

@markturansky

**Comment by markturansky** [comment]
Original issue/bug for persistent-claim ReadOnly flag:  https://github.com/GoogleCloudPlatform/kubernetes/issues/10244

**Comment by markturansky** [comment]
Not all Volumes have ReadOnly.  All PersistentVolumes have ReadOnly.

All storage volumes have ReadOnly.  If the intention is to migrate them to PV only, then no remaining volumes would have ReadOnly (but I think it might make sense for HostPath).

**Comment by markturansky** [comment]
If you found #10424 clumsy, please re-review and see the IsReadOnly flag I had to add to Builder to get at all the private implementations and their private readOnly fields.

**Comment by thockin** [comment]
Note I did not mean to imply clumsy was your fault here - the API conflates
concepts.

As for not all V having RO, sure they do - they can all be RO bind
mounted.  How different plugins interpret read-only is up to them.  Some
(PD) will do a different attach call.  Others will just ignore mount RO.

**Comment by kargakis** [comment]
@kubernetes/sig-storage-misc

**Comment by jsafrane** [comment]
IMO, the volume API is now set in stone with all its little quirks and oddities. We could reconsider this in any 2.0 API version, however I am closing it for now.

/close
