### ISSUE TITLE
Possibility to run minikube dashboard in background

### ISSUE THREAD

**Issue by d3vpasha** [kubernetes/kubernetes#106084]
### What would you like to be added?

Actually, when you use the command `minikube dashboard`, this will launch a new process & open the dashboard in your browser. You have to let the terminal open so you can still access the dashboard. I would like it to do this in background and not to have a terminal opened.

### Why is this needed?

This is needed because we cannot actually automate the installation & setup of minikube and we have to keep a terminal open while accessing the dashboard.

**Comment by neolit123** [comment]
please discuss this in the kubernetes/minikube repository.

/close
