### ISSUE TITLE
NodePort service fails to function for ingress when targeted by a neto

### ISSUE THREAD

**Issue by QWERTY92009** [kubernetes/kubernetes#106011]
### What happened?
/sig network

- Bitnami rabbitmq pod deployed, exposed externally as a NodePort service 'ramq'. 

- Set of network policies controlling flows between pods within namespace using podSelectors, forbidding all flows to / from other namespaces except kube-system, and controlling all flows external to the cluster using ipBlocks.

- The network policy targeting the rabbitmq pod allows ingress flows from authorized external interfaces using ipBlock.
```
-   ingress:
  - from:
    - ipBlock:
        cidr: 10.0.0.0/8

```

- All internal flows validated (those allowed by network policy are allowed, those not allowed by network policy are not allowed) by scanning IPs / ports from each pod. 

- Observed rabbitmq pod crashing repeatedly.

> Unfortunately the rabbitmq logs are not helpful in isolating the issue.

- Removed the network policy targeting the rabbitmq pod.

- Observed the rabbitmq pod operating normally.

### What did you expect to happen?

The rabbitmq pod exposed externally as a NodePort service should allow ingress from IP addresses matching the networkpolicy ingress ipBlock configuration. 

When this service is exposed externally as a LoadBalancer service, the behavior is as expected: the ingress flow matching the ipBlock of the network policy targeting this pod is allowed.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately the various deployments involve a significant amount of automation. However, this same or a similar behavior has been documented elsewhere:
https://oteemo.com/think-nodeport-kubernetes/

Namely: "NetworkPolicy resources can currently only control [pods exposed as] NodePorts by allowing or disallowing all traffic on them."

### Anything else we need to know?

Regarding the environment version information below, I have a ticket in with a team that has direct access to the hardware/OS, and will update the versions when those are available. However, since this seems to be a widely seen phenomenon I suspect it is not dependent on specific versions.

### Kubernetes version

kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-17T11:33:59Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1

### Cloud provider

<details>

N/A, this is an on-premise cluster.

</details>

### OS version

Ubuntu 18.04.5 LTS   4.15.0-136-generic

### Install tools

<details>
kubespray v2.13.2
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
docker://18.6.1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico
v3.13.2
</details>

**Comment by astoycos** [comment]
Hi @QWERTY92009 This is most likely a question for/ issue for the Calico CNI since they are the ones responsible for the datapath implementation of Network Policy.

**Comment by QWERTY92009** [comment]
Thanks @astoycos. Do you agree that targeting a pod with a network policy should not affect NodePort service? Thanks!

**Comment by astoycos** [comment]
So there is no defined dependency between services and network policy.  That being said if you were to apply a policy allowing nothing (denying everything) to a specific pod, and it was the only backend to a nodeport service, then yes the traffic _should_ be dropped.  Does that help at all or can I elaborate more :)

**Comment by QWERTY92009** [comment]
Thanks @astoycos. The affected rabbimq pod does have network policies allowing ingress / egress to all other pods within the cluster (this was done to troubleshoot this problem, previously limited to only pods within its namespace to which it should be communicating), and also ingress from the external IPs accessing the rabbitmq pod from outside the cluster. But when these networkpolicies are applied, no ingress from the external interfaces is observed.

Calico suggests getting tcpdumps to further definitize which flows are affected, so am looking into that.

**Comment by astoycos** [comment]
Yeah sounds good I would continue the debugging process with the CNI (Calcio) since they are the entity handling that traffic flow.
