### ISSUE TITLE
Metrics-server CrashLoopBackOff: unable to load configmap based request-header-client-ca-file

### ISSUE THREAD

**Issue by shuaich** [kubernetes/kubernetes#106060]
#### Bug Description
Metrics-server get **timed out** when querying request-header-client-ca-file from API server during start up.

Metrics-server error log:
```
Error: unable to load configmap based request-header-client-ca-file: Get "https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 10.0.0.1:443: i/o timeout
```

API server error log: (**unrelevant**)

~~I1101 06:21:35.267882       9 authorization.go:73] "Forbidden" URI="/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication" Reason=""
...
I1101 06:21:35.298065       9 httplog.go:129] "HTTP" verb="GET" URI="/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication" latency="30.338638ms" userAgent="Go-http-client/2.0" audit-ID="7f0c2bf5-94d9-49b1-8f21-4aeef6e2cf86" srcIP="[::1]:44620" apf_pl="catch-all" apf_fs="catch-all" apf_fd="" resp=403~~

### What did you expect to happen?

Metrics-server is able to query https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication.

### How can we reproduce it (as minimally and precisely as possible)?

1) Check out head of master branch and create a cluster
```
kubetest2 gce -v 2 \
  --repo-root ${HOME}/shuaich/kubernetes \
  --gcp-project shuaichen-gke-dev \
  --gcp-zone us-central1-c \
  --legacy-mode \
  --build \
  --up
  ```
  2) Look up metrics-server logs
```
kubectl logs -nkube-system ${metrics-server pod} -c metrics-server | less
```

### Anything else we need to know?

Metrics-server works fine for this PR: https://github.com/kubernetes/kubernetes/pull/105957

It seems latest commits after the above PR changed the behaviour of how metrics-server authenticates with api server.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.3.679+08bf54678e2bef", GitCommit:"08bf54678e2bef8b4c72c8c6d104b0bdf19a6f75", GitTreeState:"clean", BuildDate:"2021-10-30T07:01:17Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.3.679+08bf54678e2bef", GitCommit:"08bf54678e2bef8b4c72c8c6d104b0bdf19a6f75", GitTreeState:"clean", BuildDate:"2021-10-30T07:01:17Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
I built an unrelease cluster version on top of master head using `kubetest2 gce`.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
GOOGLE_CRASH_ID=Lakitu
GOOGLE_METRICS_PRODUCT_ID=26
KERNEL_COMMIT_ID=68596ba4a64caef7b8f6dbc52de04031a004c9b8
VERSION=85
VERSION_ID=85
BUILD_ID=13310.1308.1
$ uname -a
Linux kt2-6370fa93-83d1-master 5.4.129+ #1 SMP Thu Jul 8 19:57:33 PDT 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.30GHz GenuineIntel GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubetest2 gce
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by serathius** [comment]
/cc 
Can you specify what MS version you are using?

**Comment by shuaich** [comment]
metrics-server-v0.5.1

**Comment by serathius** [comment]
MS v0.5.1 should be configured get/list/watch on configmaps
https://github.com/kubernetes-sigs/metrics-server/blob/v0.5.1/manifests/base/rbac.yaml#L60

**Comment by shuaich** [comment]
The role `extension-apiserver-authentication-reader` is bound to metrics-server and should be able to query configmaps from apiserver. 
I ran `kubectl get roles -n kube-system extension-apiserver-authentication-reader -o yaml` and was able to see
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-11-01T06:21:38Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: extension-apiserver-authentication-reader
  namespace: kube-system
  resourceVersion: "187"
  uid: 35aa1cd4-4075-4b63-97fc-515a1f360274
rules:
- apiGroups:
  - ""
  resourceNames:
  - extension-apiserver-authentication
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
```

**Comment by serathius** [comment]
ok, this looks correct. I don't know why there is an error ¯\_(ツ)_/¯
 
 Maybe there is a race between MS start and RBAC propagation (maybe permissions are cached?)

**Comment by serathius** [comment]
Aside of emitting log, is there any impact on MS?

**Comment by shuaich** [comment]
Metrics-server fails to start, the Pod status is `CrashLoopBackOff`.

**Comment by serathius** [comment]
Are you sure that MS fails to authorize to configmap?
Looking into MS error it gets `dial tcp 10.0.0.1:443: i/o timeout`, `403 Forbidden` looks unrelated as I don't think MS uses `Go-http-client/2.0` user agent. Would need to be confirmed?

If if so, the problem is with MS connectivity to apiserver.

**Comment by serathius** [comment]
Would recommend to add presubmit tests as MS doesn't have any.

**Comment by shuaich** [comment]
> Log in apiserver 403 Forbidden looks unrelated as I don't think MS uses Go-http-client/2.0 user agent (would need to be confirmed).
Thanks for clarification. Will update the issue description.

**Comment by shuaich** [comment]
/cc dcbw
Could you please take a look?

**Comment by shuaich** [comment]
Somehow there are two pods deployed for metrics-server, one pod works correctly, the other one crashloops due to timeout when querying `https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication`

**Comment by Prateeknandle** [comment]
@shuaich do you know how you solved this issue?

**Comment by shuaich** [comment]
Sorry, I was not able to solve this issue.

**Comment by franceschongg** [comment]
Follow up - were y'all able to solve this? I've been running into this issue just recently on testing a cluster upgrade on EKS.
