### ISSUE TITLE
Better availability of deployments with replicas equal 1

### ISSUE THREAD

**Issue by jabdoa2** [kubernetes/kubernetes#106024]
#### Idea ####

I would like to keep pods inside the list of endpoints of my service while they terminate and are still ready. This can be used  with a `preStop` hook on the pod to keep a service available with `replicas: 1` on deployments during planned disruptions. As a result services will not be unavailable during planned disruptions (such as actions by the cluster autoscaler) and behave similar (but not the same) as an update of a deployment using `RollingUpdate`.

#### Implementation ####

Similar to `service.Spec.PublishNotReadyAddresses` I would like to add `service.Spec.PublishDuringTermination` and implement it in endpoint controller (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L447). The change is rather small and will not change existing behavior when not used.

#### Alternatives ####

Ideally, this would behave exactly like a rolling update on a deployment: 1. New pod scheduled 2. When new pod became ready the old pod gets terminated. However, this seems much more complex to implement (feel free to correct me on this). The above change looks rather simple, low risk and solves our issue optimistically in most of the cases.

### Why is this needed?

For developer test system we try to minimize the amount of resources we allocate. Most deployments run with `replicas: 1`. Unfortunately, when the cluster autoscaler (or operators) drain nodes those systems will experience unavailability. We would like to (optimistically) improve the availability of those systems. Ideally we would like to see a similar behavior as during an upgrade of a deployment with strategy `RollingUpdate`.

**Comment by aojea** [comment]
I think that this is similar  https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints

**Comment by jabdoa2** [comment]
> I think that this is similar https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1672-tracking-terminating-endpoints

That enhancement would definitely make this feature possible as well. It basically add a layer of abstraction inbetween and would allow implementing this in kube-proxy (or similar) instead.

Any chance that I could create PR for this simple feature for the meantime?

**Comment by aojea** [comment]
> Any chance that I could get a PR for this simple feature merged for the meantime?

this was already implemented https://github.com/kubernetes/kubernetes/pull/96371

**Comment by jabdoa2** [comment]
> > Any chance that I could get a PR for this simple feature merged for the meantime?
> 
> this was already implemented #96371

Not sure how that helps with my issue. As far as I can see I currently either set `PublishNotReadyAddresses` on my service but that will cause issues (i.e. connection reset) during start-up of pods or when they are unready. It will already include terminating pods in an endpoint which is what I want. Kind of unexpected from the name but that is what is also does. However, I only want terminating pods to be included in endpoints but not unready pods. Or am I missing something here?

**Comment by aojea** [comment]
>   I only want terminating pods to be included in endpoints but not unready pods.

 I'm rereading it now and I may did not understand it well, 
can you be more descriptive on the exactly states of the pods?

**Comment by jabdoa2** [comment]
> > I only want terminating pods to be included in endpoints but not unready pods.
> 
> I'm rereading it now and I may did not understand it well, can you be more descriptive on the exactly states of the pods?

My pods are in state "terminating" but the containers are still running due to `preStop` hooks. So the app is still functioning (on purpose). I want it to keep serving traffic until the new pod is up and service traffic. Similar to the behavior during a `kubectl rollout restart deployment xxx`.

Scenario: 
1. Deployment "my_service" with `replicas 1`
2. Pod X is scheduled on `node A`
3. Autoscaler decides to remove `node A` and starts to drain it
4. Pod X is terminated but keeps running (due to preStop hooks) -> The change is here. At the moment it would not receive any traffic anymore
5. New pod Y is scheduled on `node B`
6. New pod Y becomes ready
7. Pod X terminates and node A is removed

Normally your service would be unavailable between step 4 and 6. Depending on how fast scheduling works and how fast your pod starts this might take 5s to 300s. This small change would remove that in cases where nodes are drained (which happens frequently in most kubernetes clusters). It would obviously not work when node fail or during other disruptions but that is not the goal here.

**Comment by caseydavenport** [comment]
@jabdoa2 wouldn't this easily be resolved by running a second replica? 

I understand you're trying to conserve resources, but this is exactly the problem that replication is designed to solve, no?

**Comment by jabdoa2** [comment]
> @jabdoa2 wouldn't this easily be resolved by running a second replica?
> 
> I understand you're trying to conserve resources, but this is exactly the problem that replication is designed to solve, no?

Sure that would be a way for services which can be replicated. However, a very expensive one for low util ressources. Furthermore, some services do not support replication (or would need six times the resources for additional consensus nodes). A lot of deployments around here run additional nodes which are excempt from autoscaling to reduce those kinds of downtimes.

The issue here are not unplanned disturbances but planned ones. I do not see why we choose to force downtimes on services which do need to experience downtimes. With your argument we would also have to remove strategy rolling update from deployments and the kubectrl rollout restart deployment command. Both cases implement this properly. The issue is that we do not do the same during autoscaling or rolling node restarts.

**Comment by thockin** [comment]
This is the logical conclusion of  https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-graceful-termination-local-external-traffic-policy - right @andrewsykim  ?

**Comment by andrewsykim** [comment]
Yes, except in the current state we're only proposing that change for external traffic from a load balancer. I think we can adapt it for internal traffic like we discussed previously, but I think the KEP needs revisting for that soon.

**Comment by jabdoa2** [comment]
> Yes, except in the current state we're only proposing that change for external traffic from a load balancer. I think we can adapt it for internal traffic like we discussed previously, but I think the KEP needs revisting for that soon.

That would be awesome! Can we help in any way? Implementing the change is actually super simple. One additional option and two lines of code change.

**Comment by thockin** [comment]
Can we re-title this or dup it to one of the  existing issues?

**Comment by jabdoa2** [comment]
> Can we re-title this or dup it to one of the existing issues?

How would you like to title it? I did not find any duplicates when creating this.

**Comment by thockin** [comment]
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints

Once that applies to internal and external, I think it does what you need.  If all endpoints are Terminating but also Serving, we will use those.  If any endpoints are Serving and not Terminating, we will prefer those.

So dup of  https://github.com/kubernetes/enhancements/issues/1669 ?

**Comment by jabdoa2** [comment]
@thockin https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints solves part of the issue. If I understand it right it would still include terminating but ready pods in a service. That enables the `preStop` workaround (https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/1669-proxy-terminating-endpoints#motivation) for this usecase. I guess we could go further an improve scheduling here but that probably would be a (significant) change to cluster autoscaler. So yeah looks like it might be enough for now. Thanks :-).
