### ISSUE TITLE
Kubernetes worker not ready without rebooting  and another worker his not ready 

### ISSUE THREAD

**Issue by AbdElRhman2111** [kubernetes/kubernetes#106028]
### What happened?

master@master:~$ kubectl get node
NAME      STATUS     ROLES                  AGE    VERSION
master    Ready      control-plane,master   143m   v1.22.3
worker    NotReady   <none>                 142m   v1.22.3
worker2   NotReady   <none>                 142m   v1.22.3

i will run command on notready worker 
journalctl -u kubelet

أoctober 31 15:48:10 worker kubelet[86732]: E1031 15:48:10.064591   86732 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get 
"https://k8s-cluster.let.com:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/worker?timeout=10s"
: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

أoctober 31 15:48:38 worker kubelet[86732]: E1031 15:48:38.633456   86732 eviction_manager.go:255] "Eviction manager: 
 failed to get summary stats" err="failed to get node info: node \"worker\" not found"

أoctober 31 15:48:44 worker kubelet[86732]: E1031 15:48:44.068965   86732 controller.go:144] failed to ensure lease exists, will retry in 7s, error: 
Get "https://k8s-cluster.let.com:6443/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/worker?timeout=10s":
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

أoctober 31 15:48:44 worker kubelet[86732]: E1031 15:48:44.002526   86732 kubelet.go:2412] "Error getting node" err="node \"worker\" not found"

أoctober 31 15:48:44 worker kubelet[86732]: I1031 15:48:44.831080   86732 trace.go:205] Trace[385226746]: "Reflector ListAndWatch" 
name:k8s.io/client-go/informers/factory.go:134 (31-Oct-2021 15:48:14.830) (total time: 30000ms):

أoctober 31 15:48:44 worker kubelet[86732]: E1031 15:48:44.831179   86732 reflector.go:138] k8s.io/client-go/informers/factory.go:134: 
Failed to watch *v1.Service: failed to list *v1.Service: Get "https://k8s-cluster.let.com:6443/api/v1/services?limit=500&resourceVersion=0": 
dial tcp 192.168.1.122:6443: i/o timeout

### What did you expect to happen?

No think happen to change status i go to break and return find this issue

### How can we reproduce it (as minimally and precisely as possible)?

..

### Kubernetes version

<details>

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

</details>

### Cloud provider

<details>
Local Machine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux worker 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
sudo apt install -y containerd.io docker-ce docker-ce-cli     "latest version"
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

</details>

**Comment by aojea** [comment]
> dial tcp 192.168.1.122:6443: i/o timeout

there is a connectivity problem

**Comment by neolit123** [comment]
please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
