### ISSUE TITLE
release-1.19 make error

### ISSUE THREAD

**Issue by MrSsunlight** [kubernetes/kubernetes#106023]
### What happened?

```
find: vendor/k8s.io/apiextensions-apiserver/examples/client-go/hack: No such file or directory
find: vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/apis/cr: No such file or directory
...
+++ [1030 22:23:57] Building go targets for darwin/amd64:
    ./vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
cannot find package "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen" in any of:
        /usr/local/Cellar/go/1.16.3/libexec/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOROOT)
        $GOPATH//src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (from $GOPATH)
!!! [1030 22:23:57] Call tree:
!!! [1030 22:23:57]  1: $GOPATH/src/k8s.io/kubernetes/hack/lib/golang.sh:719 kube::golang::build_some_binaries(...)
!!! [1030 22:23:57]  2: $GOPATH/src/k8s.io/kubernetes/hack/lib/golang.sh:863 kube::golang::build_binaries_for_platform(...)
!!! [1030 22:23:57]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1030 22:23:58] Call tree:
!!! [1030 22:23:58]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1030 22:23:58] Call tree:
!!! [1030 22:23:58]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [_output/bin/prerelease-lifecycle-gen] Error 1
make: *** [generated_files] Error 2
```

### What did you expect to happen?

build is ok

### How can we reproduce it (as minimally and precisely as possible)?

```
cd $GOPATH/src/k8s.io
git clone https://github.com/kubernetes/kubernetes
cd kubernetes
git checkout -b release-1.19 origin/release-1.19
git pull origin release-1.19
make
```

### Anything else we need to know?

`go version go1.16.3 darwin/amd64`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

# On Linux:
$ uname -a
`Darwin bogon 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64
`
</details>

### Install tools

<details>

gcc:
`Apple clang version 12.0.5 (clang-1205.0.22.9)`

make:
`GNU Make 3.81`

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

Docker version 20.10.8, build 3967b7d

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig release
/kind support

important to note that 1.19 is going out of support soon.

**Comment by MrSsunlight** [comment]
But 1.19 is also a relatively new version, and now I don’t know what caused it to be unable to compile? I want to find a fixed version for learning. Is there a more suitable historical version recommended? @neolit123

**Comment by MrSsunlight** [comment]
I use `go get -u k8s.io/code-generator/...` , `go mod tidy` and `go mod vendor` to get the corresponding package, but the result of make remains unchanged.

```
[root@localhost kubernetes]# find -name code-generator
./staging/src/k8s.io/code-generator
./vendor/k8s.io/code-generator

root@localhost kubernetes]# tree -L 3 ./vendor/k8s.io/code-generator
./vendor/k8s.io/code-generator
├── cmd
│   └── go-to-protobuf
│       ├── BUILD
│       ├── main.go
│       ├── OWNERS
│       ├── protobuf
│       └── protoc-gen-gogo
├── LICENSE
├── pkg
│   └── util
│       ├── BUILD
│       ├── build.go
│       └── plural_exceptions.go
└── third_party
    └── forked
        └── golang

```

**Comment by neolit123** [comment]
Building older versions should be fine so not sure what the problem is.

**Comment by nitinpatil1992** [comment]
@MrSsunlight you might be missing the symlink for `vendor/k8s.io/apiextensions-apiserver`. Hope it helps.

**Comment by MrSsunlight** [comment]
> Building older versions should be fine so not sure what the problem is.

Thanks, I know the reason, it is caused by the loss of soft connection

**Comment by MrSsunlight** [comment]
> @MrSsunlight you might be missing the symlink for `vendor/k8s.io/apiextensions-apiserver`. Hope it helps.

Thanks, I know the reason, it is caused by the loss of soft connection
