### ISSUE TITLE
Pods stuck in ContainerCreating due to configmaps not being returned from apiserver

### ISSUE THREAD

**Issue by rkress3** [kubernetes/kubernetes#106088]
### What happened?

We have a kubernetes 1.16.15 cluster running with etcd. The cluster is running with 3 masters nodes. The system has 25110+ configmaps. When new configmaps are created and mounted to new pods, the pods are stuck in containerCreating because the configmap is not available from the watcher cache on the master nodes.

It seems that the watcher cache on the master nodes are not being updated by etcd. 

The new configmaps can be retrieved from etcd (using the kubectl get command). But the query to the cache does not return anything. 

kubectl get --raw   '/api/v1/namespaces/test/configmaps?fieldSelector=metadata.name%3Dtest&limit=500&resourceVersion=0'
 
{"kind":"ConfigMapList","apiVersion":"v1","metadata":{"selfLink":"/api/v1/namespaces/test/configmaps","resourceVersion":"10748356"},"items":[]}
 
The only way I have found to clear the situation is to restart the master nodes. After the restart, new configmaps will be accessible from the cache. But, after a few days the issue will arise again. 

### What did you expect to happen?

The configmaps should be retrieved from the apiserver and mounted to the pods. 

### How can we reproduce it (as minimally and precisely as possible)?

It continues to happen on one of our production sites. But I have not found a way to reproduce it on a development cluster.

### Anything else we need to know?

The cluster is running etcd version 3.3.10

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"af348cc45981e51ffd9156c04a8589b0a9a48c55", GitTreeState:"clean", BuildDate:"2021-07-22T16:59:15Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"af348cc45981e51ffd9156c04a8589b0a9a48c55", GitTreeState:"clean", BuildDate:"2021-07-22T16:59:15Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Oracle

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

$ uname -a

Linux ost-cndevcorp-masterfjki 5.4.17-2102.205.7.3.el7uek.x86_64 #2 SMP Fri Sep 17 16:52:13 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux



### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MadhavJivrajani** [comment]
Hi @rkress3, thanks for creating this issue!
The version of Kubernetes used by you (1.16.5) is no longer supported for patches. Please re-open this issue (you can do so by commenting `/reopen` on this issue) if it still persists with a Kubernetes version that is still actively supported - you can find more information [here](https://kubernetes.io/releases/version-skew-policy/). Thanks again!
/close

**Comment by MadhavJivrajani** [comment]
Also - please feel free to bring this up in the K8s slack (https://slack.k8s.io) `#sig-api-machinery` and/or `kubernetes-users`channel, maybe someone faced a similar issue :)

**Comment by rkress3** [comment]
Got it, thanks for the information about the slack channel.
