### ISSUE TITLE
kubernetes PersistentVolumeClaim status pending 

### ISSUE THREAD

**Issue by AbdElRhman2111** [kubernetes/kubernetes#106040]
### What happened?

kubernetes PersistentVolumeClaim status pending i do config yaml for storageclass frist 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
  resources:
    requests:
      storage: 30Gi

------------------------
and create  PersistentVolumeClaim yaml after storageclass 

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd

------------------------------------------

but status Pending 
i don't for this issue

### What did you expect to happen?

i need make  PersistentVolumeClaim status a Bound 

### How can we reproduce it (as minimally and precisely as possible)?

..

### Kubernetes version

<details>

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Local
</details>

### OS version

<details>

```

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


Linux master 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>
Docker
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel
</details>

**Comment by Kartik494** [comment]
Hi @AbdElRhman2111 Do you have `persistentVolume` up with you for bound this to `Persistent volume  claim`?

**Comment by Kartik494** [comment]
Can you apply this `persistent volume` and let me know if this is still in pending state.

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
spec:
  storageClassName: fast
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

**Comment by AbdElRhman2111** [comment]
> Can you apply this `persistent volume` and let me know if this is still in pending state.
> 
> apiVersion: v1 kind: PersistentVolume metadata: name: pv spec: storageClassName: fast capacity: storage: 30Gi accessModes: - ReadWriteOnce hostPath: path: "/mnt/data"

Thanks Kartik494 it's working
