### ISSUE TITLE
Under what circumstances will scheduler delete pods 

### ISSUE THREAD

**Issue by yanxingponyai** [kubernetes/kubernetes#106046]
### What happened?

The pod of a deployment suddenly deleted and restarted.

### What did you expect to happen?

The pods keeps running

### How can we reproduce it (as minimally and precisely as possible)?

I can not reproduce it
I see the audit log from apiserver, I think the pods was deleted by kube-scheduler
```
{"kind":"Event","apiVersion":"audit.k8s.io/v1","level":"Request","auditID":"f8d7a565-a9de-49ba-96c8-a6bf07a6e976","stage":"ResponseComplete","requestURI":"/api/v1/namespaces/infra-super-prod/pods/make8-server-1804-7bb8cddd6-r52xj","verb":"delete","user":{"username":"system:kube-scheduler","groups":["system:authenticated"]},"sourceIPs":["10.26.171.17"],"userAgent":"kube-scheduler/v1.20.11 (linux/amd64) kubernetes/27522a2/scheduler","objectRef":{"resource":"pods","namespace":"infra-super-prod","name":"make8-server-1804-7bb8cddd6-r52xj","apiVersion":"v1"},"responseStatus":{"metadata":{},"code":200},"requestObject":{"kind":"DeleteOptions","apiVersion":"v1"},"requestReceivedTimestamp":"2021-11-01T10:57:16.942607Z","stageTimestamp":"2021-11-01T10:57:16.950874Z","annotations":{"authorization.k8s.io/decision":"allow","authorization.k8s.io/reason":"RBAC: allowed by ClusterRoleBinding \"system:kube-scheduler\" of ClusterRole \"system:kube-scheduler\" to User \"system:kube-scheduler\""}}

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
pod restart may caused by many reasons,  e.g. OOM, liveness failed and so on, you should provide more details for investigating. What's more, it seems more like a support rather than a bug, and [slack](https://kubernetes.slack.com/archives/C09TP78DV) maybe a better place to discuss with. 

/remove kind-bug
/kind support

**Comment by ahg-g** [comment]
The scheduler issues delete when preempting pods to fit higher priority ones.
