### ISSUE TITLE
Images still in use are GCed

### ISSUE THREAD

**Issue by zerkms** [kubernetes/kubernetes#106037]
### What happened?

As you may see - for whatever reason kubelet decided to cleanup `pause:3.5` even though it's a sandbox image

```
Nov  1 02:49:16 node-guiding-basilisk kubelet[4039]: I1101 02:49:16.455933    4039 image_gc_manager.go:321] attempting to delete unused images
Nov  1 02:49:16 node-guiding-basilisk kubelet[4039]: I1101 02:49:16.473682    4039 image_gc_manager.go:375] [imageGCManager]: Removing image "sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459" to free 301416 bytes
Nov  1 02:49:16 node-guiding-basilisk containerd[3564]: time="2021-11-01T02:49:16.474462739Z" level=info msg="RemoveImage \"sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459\""
Nov  1 02:49:16 node-guiding-basilisk containerd[3564]: time="2021-11-01T02:49:16.485649003Z" level=info msg="ImageDelete event &ImageDelete{Name:k8s.gcr.io/pause:3.5,XXX_unrecognized:[],}"
Nov  1 02:49:16 node-guiding-basilisk containerd[3564]: time="2021-11-01T02:49:16.494040111Z" level=info msg="ImageDelete event &ImageDelete{Name:k8s.gcr.io/pause@sha256:1ff6c18fbef2045af6b9c16bf034cc421a29027b800e4f9b68ae9b1cb3e9ae07,XXX_unrecognized:[],}"
Nov  1 02:49:16 node-guiding-basilisk containerd[3564]: time="2021-11-01T02:49:16.504826030Z" level=info msg="ImageDelete event &ImageDelete{Name:sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459,XXX_unrecognized:[],}"
Nov  1 02:49:16 node-guiding-basilisk containerd[3564]: time="2021-11-01T02:49:16.613154111Z" level=info msg="RemoveImage \"sha256:ed210e3e4a5bae1237f1bb44d72a05a2f1e5c6bfe7a7e73da179e2534269c459\" returns successfully"
```

### What did you expect to happen?

It should be kept

### How can we reproduce it (as minimally and precisely as possible)?

Fill the disk to reach threshold and read the GC logs

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux node-guiding-basilisk 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd 1.5.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yxxhero** [comment]
@zerkms any pods use the `pause:3.5` image? Thanks very much.

**Comment by zerkms** [comment]
@yxxhero all of them, it's a sandbox image.

**Comment by yxxhero** [comment]
@zerkms Garbage collection will delete unused image. When some image used by container. It can't delete unless forced deletion.

**Comment by zerkms** [comment]
@yxxhero that's the very reason I reported it: kubelet does not detect the sandbox image correctly, so thinks it's not used anywhere.

**Comment by yxxhero** [comment]
@zerkms yes. I think because I use dockershim. I test in containerd without docker. It can delete image in use.

**Comment by yxxhero** [comment]
@zerkms https://github.com/containerd/containerd/issues/6160

**Comment by zerkms** [comment]
@yxxhero not sure how it's relevant: it's kubelet's logic that is flawed. `kubelet` must not delete the sandbox image, it's already implemented at

https://github.com/kubernetes/kubernetes/blob/6ebd6f38b9804aa9eb58c5f742a56fa1f9e6ab85/pkg/kubelet/images/image_gc_manager.go#L212-L216

the problem is that it incorrectly detects the sandbox image name.

**Comment by yxxhero** [comment]
@zerkms I think is a bug.

**Comment by neolit123** [comment]
related https://github.com/kubernetes/kubernetes/pull/103299
issue for pinned images:
https://github.com/kubernetes/kubernetes/pull/101808

**Comment by 249043822** [comment]
> @yxxhero not sure how it's relevant: it's kubelet's logic that is flawed. `kubelet` must not delete the sandbox image, it's already implemented at
> 
> https://github.com/kubernetes/kubernetes/blob/6ebd6f38b9804aa9eb58c5f742a56fa1f9e6ab85/pkg/kubelet/images/image_gc_manager.go#L212-L216
> 
> the problem is that it incorrectly detects the sandbox image name.

I could not reproduce this in v1.22.1, I think maybe the line 213 encountered error while disk full time, then sandboxImage escaped from in-use list

**Comment by 249043822** [comment]
triage/accepted

**Comment by zerkms** [comment]
@249043822 apparently you could not reproduce it in 1.22 because in kubelet 1.22 

    --pod-infra-container-image string     Default: k8s.gcr.io/pause:3.5

but in 1.20 it's `pause:3.2`.

So instead of using CRI kubelet simply relies on the cli arguments only.

**Comment by 249043822** [comment]
> @249043822 apparently you could not reproduce it in 1.22 because in kubelet 1.22
> 
> ```
> --pod-infra-container-image string     Default: k8s.gcr.io/pause:3.5
> ```
> 
> but in 1.20 it's `pause:3.2`.
> 
> So instead of using CRI (to obtain the current and actual sandbox image name) kubelet simply relies on the cli arguments only (which are not set to anything).

pause version should not the essential reason, no difference

**Comment by zerkms** [comment]
> pause version should not the essential reason

`im.sandboxImage` is set to the `--pod-infra-container-image` isn't it?

**Comment by 249043822** [comment]
> > pause version should not the essential reason
> 
> `im.sandboxImage` is set to the `--pod-infra-container-image` isn't it?

Yea

**Comment by zerkms** [comment]
> Yea

so, it causes a problem then: containerd uses pause:3.5, and kubelet thinks it's 3.2 (in kubelet v1.20 and 1.21).

So, I think kubelet should use CRI to obtain the currently used sandbox image in runtime, instead of relying on a statically set cli argument.

**Comment by 249043822** [comment]
> > Yea
> 
> so, it causes a problem then: containerd uses pause:3.5, and kubelet thinks it's 3.2 (in kubelet v1.20 and 1.21).
> 
> So, I think kubelet should use CRI to obtain the currently used sandbox image in runtime, instead of relying on a statically set cli argument.

Okay, I see

**Comment by ehashman** [comment]
> So, I think kubelet should use CRI to obtain the currently used sandbox image in runtime, instead of relying on a statically set cli argument.

This is more of a feature request than a bug. You can set the command line flag to match the version of the sandbox image you want to pin as a workaround.

/remove-kind bug
/kind feature
/retitle Dynamically detect sandbox image from container runtime

**Comment by zerkms** [comment]
Okay, it's not a feature: at this very moment I'm witnessing how a container image that is still in run was GCed:

```
Nov  7 20:35:01 node-guiding-basilisk kubelet[4039]: I1107 20:35:01.175656    4039 image_gc_manager.go:375] [imageGCManager]: Removing image "sha256:dbf9deeb946991c412f1dd7c73cd4154e14f469a8993df92bd4aae0d524d7858" to free 44689115 bytes
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.176155001Z" level=info msg="RemoveImage \"sha256:dbf9deeb946991c412f1dd7c73cd4154e14f469a8993df92bd4aae0d524d7858\""
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.196487600Z" level=info msg="ImageDelete event &ImageDelete{Name:docker.io/library/python:3.6-slim,XXX_unrecognized:[],}"
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.210875552Z" level=info msg="ImageDelete event &ImageDelete{Name:docker.io/library/python@sha256:4b4fb6869a3b93de1dc821a7cdbb167835768034a2a66d52eebc1efeae75469f,XXX_unrecognized:[],}"
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.222604931Z" level=info msg="ImageDelete event &ImageDelete{Name:docker.io/library/python@sha256:78c9446103ad8508fabafddb233249cac4883e44bf84b6d550f251eb834750f5,XXX_unrecognized:[],}"
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.230919757Z" level=info msg="ImageDelete event &ImageDelete{Name:docker.io/library/python@sha256:a7989f57b5078eae628f484fc39e249c88fd3404427e100aabcc5c6bc07cc1e7,XXX_unrecognized:[],}"
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.240637137Z" level=info msg="ImageDelete event &ImageDelete{Name:sha256:dbf9deeb946991c412f1dd7c73cd4154e14f469a8993df92bd4aae0d524d7858,XXX_unrecognized:[],}"
Nov  7 20:35:01 node-guiding-basilisk containerd[3564]: time="2021-11-07T20:35:01.510414652Z" level=info msg="RemoveImage \"sha256:dbf9deeb946991c412f1dd7c73cd4154e14f469a8993df92bd4aae0d524d7858\" returns successfully"
```

`python:3.6-slim` is running in at least one pod that have been non-stop running for the last 12 days.
