### ISSUE TITLE
RingGrowing readable will be negative, which leads `index out of range`

### ISSUE THREAD

**Issue by zen-xu** [kubernetes/kubernetes#106003]
### What happened?

When I restart my pod while the cluster in high load, the restarted pod will panic. 

The stack trace told me the panic was caused by **index out of range** in `k8s.io/utils/buffer/ring_growing.go`

![未命名](https://user-images.githubusercontent.com/38552291/139398609-1fc3fc20-39f4-4776-9ada-ca8b1061ebfe.png)

Then I read the source code of `k8s.io/utils/buffer/ring_growing.go`, and I found the reason.

https://github.com/kubernetes/kubernetes/blob/bb24c265ce725c90f0e82b01e7c1ccbffb695d14/vendor/k8s.io/utils/buffer/ring_growing.go#L19-L43

The comment has pointed out the `RingGrowing` is **not thread safe**.

After I add the lock to `RingGrowing` when read/write, no panic occurs again.

### What did you expect to happen?

The panic should never occur.

### How can we reproduce it (as minimally and precisely as possible)?

We have over 100k(running and completed) pods in our cluster, and it's in high load.
And we use volcano as our default scheduler.
When I restart the volcano-controller, the controller will panic.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
v1.18.2

### Cloud provider

<details>

</details>
self-host

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by zen-xu** [comment]
> if add the lack to `RingGrowing `, Will it cause fierce lock competition in high load ?

No

**Comment by Zheaoli** [comment]
Maybe we need a lock-free thread-safe ringbuffer

**Comment by neolit123** [comment]
tagging with api-machinery since this is used in client-go:
https://github.com/kubernetes/kubernetes/search?q=RingGrowing

/sig api-machinery

**Comment by fedebongio** [comment]
Thank you @neolit123 for the tag

**Comment by deads2k** [comment]
@zen-xu I'm not finding matching line numbers for your stack.

ring_growing.go doesn't seem to have 73 lines: https://github.com/kubernetes/utils/blob/master/buffer/ring_growing.go and line 728 from shared_informer appears to be a block end: https://github.com/kubernetes/kubernetes/blob/v1.18.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L728 

I bring it up because the access to `p.pendingNotifications` (RingGrowing instance) appears to be single-threaded to me.  We create multiple instances, but I think we start them only once.  I'd like to pull a set of code matching what your stack came from to understand how we ended up running on two threads before making the change to k8s.io/utils.

**Comment by zen-xu** [comment]
> @zen-xu I'm not finding matching line numbers for your stack.
> 
> 
> 
> ring_growing.go doesn't seem to have 73 lines: https://github.com/kubernetes/utils/blob/master/buffer/ring_growing.go and line 728 from shared_informer appears to be a block end: https://github.com/kubernetes/kubernetes/blob/v1.18.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L728 
> 

I am sorry，I write some log in `func (r *RingGrowing) WriteOne`

**Comment by zen-xu** [comment]
> @zen-xu I'm not finding matching line numbers for your stack.
> 
> 
> 
> ring_growing.go doesn't seem to have 73 lines: https://github.com/kubernetes/utils/blob/master/buffer/ring_growing.go and line 728 from shared_informer appears to be a block end: https://github.com/kubernetes/kubernetes/blob/v1.18.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L728 
> 

I am sorry，I write some logs in `func (r *RingGrowing) WriteOne` before 70 line（where I found readable will be negative）. The stack should be at 70 line

**Comment by zen-xu** [comment]
> @zen-xu I'm not finding matching line numbers for your stack.
> 
> 
> 
> ring_growing.go doesn't seem to have 73 lines: https://github.com/kubernetes/utils/blob/master/buffer/ring_growing.go and line 728 from shared_informer appears to be a block end: https://github.com/kubernetes/kubernetes/blob/v1.18.2/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L728 
> 

I am sorry，I write some logs in `func (r *RingGrowing) WriteOne` before 70 line（where I found readable will be negative）. The stack should be at 70 line

**Comment by deads2k** [comment]
> And I also add some logs in shared_informer at `func (p *processorListener) run`， and the log will print `next` is **nil** when panic occurs

Can you push those branches?  Also, any luck determining where we are launching two threads calling `.pop` on the same `processorListener`?

**Comment by zen-xu** [comment]
> Can you push those branches? Also, any luck determining where we are launching two threads calling `.pop` on the same `processorListener`?

I didn't change original logic for these codes, only added some logs to print some information which might help me to  locate the bug.

**Comment by Zheaoli** [comment]
> Can you push those branches? Also, any luck determining where we are launching two threads calling .pop on the same processorListener?

In my opinion, is there any possibility to run `AddEventHandlerWithResyncPeriod` before `Run`?

**Comment by deads2k** [comment]
`AddEventHandlerWithResyncPeriod` creates a new Listeners, so the particular instance of RingGrowing would not be re-used, right?

**Comment by Zheaoli** [comment]
@deads2k 

If people run `Run` method before `AddEventHandlerWithResyncPeriod`, the particular instance of RingGrowing would not be re-used. 

But once the people run `AddEventHandlerWithResyncPeriod` before `Run` or and run almost the same time in different  goroutines, I think it is possible to reuse the RingGrowing Buffer

**Comment by deads2k** [comment]
> But once the people run `AddEventHandlerWithResyncPeriod` before `Run` or and run almost the same time in different goroutines, I think it is possible to reuse the RingGrowing Buffer

Ah ha!  Perhaps it is that the `.run` method uses a read lock, but writes to `listenersStarted`.  the `AddEventHandlerWithResyncPeriod` acquires a full lock and reads the `listenersStarted`, but it may not observe the written value of `listenersStarted`.

Do you have  reliable reproducer you can try making the `.run` method `p.listenersLock.Lock()` and `defer p.listenersLock.Unlock()`?

**Comment by tkashem** [comment]
cc @tkashem

**Comment by Zheaoli** [comment]
@deads2k Yes, makes sense. I'll update my PR

**Comment by jschwinger233** [comment]
Shall we have a look at the whole panic logs? If it's caused by race condition, the whole goroutine stack record is helpful to determine where the concurrent access of critical section happened.

**Comment by liggitt** [comment]
> Ah ha! Perhaps it is that the `.run` method uses a read lock, but writes to `listenersStarted`. the `AddEventHandlerWithResyncPeriod` acquires a full lock and reads the `listenersStarted`, but it may not observe the written value of `listenersStarted`.

I don't understand this... the full lock would mean the RLock section would have to complete first
