### ISSUE TITLE
kubernetes cluster failed to start after reboot the computer

### ISSUE THREAD

**Issue by john1337** [kubernetes/kubernetes#106033]
### What happened?

kubernetes cluster failed to start after reboot the computer

### What did you expect to happen?

in my opinion,it's very common to restart docker or reboot the computer,such as power down,but in my circumstance,the whole k8s cluster failed to start

### How can we reproduce it (as minimally and precisely as possible)?

run systemctl restart docker or reboot in ubuntu

### Kubernetes version

1.20.4

### Cloud provider

no cloud 

### OS version

ubuntu20.04

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
please try the support channels first until a bug is confirmed:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

also this issue is missing sufficient details like component logs.

/kind support
/close
