### ISSUE TITLE
[Flake] PreStop graceful pod terminated should wait until preStop hook completes the process

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#106125]
### Which jobs are flaking?

ci-kubernetes-e2e-gci-gce
pull-kubernetes-e2e-gce-ubuntu-containerd

### Which tests are flaking?

`[sig-node] PreStop graceful pod terminated should wait until preStop hook completes the process`

This is the flakiest test both in the CI (ci-kubernetes-e2e-gci-gce) and PR (pr:pull-kubernetes-e2e-gce-ubuntu-containerd) e2e according to http://storage.googleapis.com/k8s-metrics/flakes-latest.json:

```
  "pr:pull-kubernetes-e2e-gce-ubuntu-containerd": {
    "consistency": 0.937,
    "flakes": 29,
    "test_flakes": {
      "[sig-node] PreStop graceful pod terminated should wait until preStop hook completes the process": 10,
      "[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should honor timeout [Conformance]": 4,
      "[sig-storage] Downward API volume should update annotations on modification [NodeConformance] [Conformance]": 3,
...
  "ci-kubernetes-e2e-gci-gce": {
    "consistency": 0.661,
    "flakes": 20,
    "test_flakes": {
      "[sig-node] PreStop graceful pod terminated should wait until preStop hook completes the process": 17,
      "[sig-network] Proxy version v1 should proxy logs on node using proxy subresource ": 5,
      "[sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should honor timeout [Conformance]": 3,
...
```

### Since when has it been flaking?

Several weeks

### Reason for failure (if possible)

https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=PreStop%20graceful%20pod%20terminated%20should%20wait%20until%20preStop%20hook%20completes%20the%20process

### Relevant SIG(s)

/sig node
/priority important-soon

**Comment by SaiHarshaK** [comment]
The `gracefulTerminationPeriodSeconds` is set to 30 seconds [here](https://github.com/kubernetes/kubernetes/blob/ea78226bf395cbf8c43a27a714b487d302bdf392/test/e2e/node/pre_stop.go#L171), while we wait for 15 seconds [here](https://github.com/kubernetes/kubernetes/blob/ea78226bf395cbf8c43a27a714b487d302bdf392/test/e2e/node/pre_stop.go#L192) after executing graceful termination.
Then, why are we trying to Poll for 1 minute ?([Ref](https://github.com/kubernetes/kubernetes/blob/ea78226bf395cbf8c43a27a714b487d302bdf392/test/e2e/node/pre_stop.go#L196)) Won't the pod be terminated forcefully when the 30s specified in `gracefulTerminationPeriodSeconds` is over?

**Comment by brianpursley** [comment]
@SaiHarshaK Do you think `wait.Poll` is even needed?  It seems like if the status is not Running at this time, that is an error.

I find it strange that this would time out.  Does that imply the status of the pod is not running?

I wonder if liveness probes continue to run while prestop is in progress.  :thinking:

**Comment by SaiHarshaK** [comment]
@brianpursley I also think that it isn't necessary. The pre-stop hook will make sure the pod is still running so there shouldn't be any error returned. If for some reason it failed, then it just might be an issue with the code changes.

**Comment by ehashman** [comment]
@SaiHarshaK is there an associated PR to fix this flake?

**Comment by SaiHarshaK** [comment]
> @SaiHarshaK is there an associated PR to fix this flake?

I can make the PR for removing the polling, but i wasn't sure what is expected here - Do I remove the wait.Poll entirely as discussed above?

**Comment by SaiHarshaK** [comment]
We might still the wait.Poll method because it is the condition timeout causing the error, so it might be better to retry. Ideally it is supposed to see that the pod is running and complete which isn't happening.

Current PR reduces the interval time to do more tries, alternatively what we can do is to increase the gracefulTermination period to 75seconds and let the original [wait.Poll](https://github.com/kubernetes/kubernetes/blob/0153febd9f0098d4b8d0d484927710eaf899ef40/test/e2e/node/pre_stop.go#L196) remain.

I also have a doubt, if the delete operation is taking time which is causing the wait.Poll to run after gracefulTermination period, but i don't know how to verify that locally. To help with that, i have added additional [log](https://github.com/kubernetes/kubernetes/blob/d49d8f39ea969b4dd01b1c3a251efe26cea0b4b3/test/e2e/node/pre_stop.go#L219) of pod state on each retry.

**Comment by SergeyKanzhelev** [comment]
/close

this does not seem to be flaking any longer
