### ISSUE TITLE
Whether the node status should be checked when creating volumeattachent  resources

### ISSUE THREAD

**Issue by dsy3502** [kubernetes/kubernetes#106151]
### What happened?

 After deleting volumeattachment, sometimes the new volumeattachment is still on the old node  and  the pod is still be containerCreating.  sometimes  the pod statue changes running.

### What did you expect to happen?

 after the node down or Stop kubelet inside the node , the pod  will be evicted and recreated on another available node
but the pod with a volume can't be running because the old node not detach  the volume.
Forced delete  pod or delete volumeattachment should trigger the detach process and let the pod be running

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod with a volume using any of the attachable plugins (I used GCE PD to test).
2. Stop kubelet inside the node where the pod is scheduled.
3. Wait for 6min+
4. delete the volumeattachent
5. Check to see if pod change running

### Anything else we need to know?

Whether the node status should be checked when creating volumeattachent  resources

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
why kubelet is stopped? Is it stopped without the node controller removing the node?

**Comment by ehashman** [comment]
> after the node down or Stop kubelet inside the node , the pod will be evicted and recreated on another available node
> but the pod with a volume can't be running because the old node not detach the volume.

If the kubelet is stopped, it isn't possible for the volume to be unmounted, because the kubelet is responsible for unmounting the volume.

Deleting the volumeattachment or other objects in etcd only changes what the API server will report; if the kubelet on the node is down, it won't affect the state of the node.

Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
