### ISSUE TITLE
can't use NET_ADMIN capability beside Privileged PSS

### ISSUE THREAD

**Issue by ryanlyy** [kubernetes/kubernetes#106107]
### What happened?

Dear,

Now I am experimenting PodSecurity Standard and PodSecurity Admission in Kubernetes 1.22. 

And I found I can't add NET_ADMIN capability when using baseline or restricted PSS level. The only way I can add NET_ADMIN is using Privileged PSS Level. It is really not convenient because believe no customer allow workload using privileged but wordload may need using NET_ADMIN for some reason. So after PSP removed in 1.25, how can we achieve this target?

Another issue is currently we can only apply PodSecurity Admission into namespace level(label namespace) or cluster level (AdmissionConfiguration). But if we want to use different capability on different pod type in one namespace, i.e: podA in namespace NS1 needs NET_ADMIN capability and podB in namespace NS1 only needs "restricted" PSS Level, how can we achieve it?

Thanks a lot for your support.

### What did you expect to happen?

different pod with different capability and have NET_ADMIN capability w/o using privileged PSS Level

### How can we reproduce it (as minimally and precisely as possible)?

creating pod using 1.22 with --feature-gate=PodSecurity=true

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Native kubernetes

### OS version

Linux lubuntu 5.4.0-84-generic #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

dockerd/containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

multus/calico/ipvlan

**Comment by liggitt** [comment]
This is working as designed. cap_net_admin is not expected to be granted to non-privileged workloads, and mixing privileged and non-privileged workloads in a given namespace should only be done if the pod authors in that namespace are trusted to write privileged workloads.

You can grant privileged access to a namespace, and still create lower-privilege workloads in that namespace.

/close

**Comment by ryanlyy** [comment]
Thank a lot @liggitt 

I understood in privileged labeled namespace, I can create lower-privileged workload in that namespace. but can I create privileged workloads in non-privilged labeled namespace (i.e: baseline and restricted)?

Thanks a lot for your support

**Comment by liggitt** [comment]
> I understood in privileged labeled namespace, I can create lower-privileged workload in that namespace. but can I create privileged workloads in non-privilged labeled namespace (i.e: baseline and restricted)?

No, the level on the namespace represents the upper-bound of permitted workloads in the namespace.

**Comment by ryanlyy** [comment]
thanks a lot @liggitt so if using NET_ADMIN permission, the only way is labeling namespace with "privileged" pss level? or is there anyway we can use NET_ADMIN w/o "privileged" pss level labeled?

Thanks a lot for your support

**Comment by liggitt** [comment]
the default level for unlabeled namespaces is privileged, but specific cluster admins can change that default, so if you intend to make use of privileged permissions like net_admin, explicitly labeling the namespace as privileged is recommended. 

GA / 1.24 isn't yet in progress, but there are no plans to move net_admin out of the privileged level at this point
