### ISSUE TITLE
Remove deprecate klog flag usage from kubemark

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#106103]
/kind feature

Hey, in K8s 1.23 we are planning to deprecate multiple klog flags. [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)

Deprecated flags: `--log-dir`, `--log-file`, `--log-flush-frequency`, `--logtostderr`, `--alsologtostderr`, `--one-output`, `--stderrthreshold`, `--log-file-max-size`, `--skip-log-headers`, `--add-dir-header`, `--skip-headers`, `--log-backtrace-at`

One of the alpha milestones is requires us to remove usage of deprecated flags within K8s repo. Examples found for kubemark 
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/test/kubemark/resources/hollow-node_template.yaml#L56
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/test/kubemark/resources/hollow-node_template.yaml#L87
* [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/blob/99678f0fff5b49fdc1fdcaadb50b116777d43d78/tests/kubemark/templates/hollow-node.yaml#L52
* [ ] https://github.com/kubernetes-sigs/cloud-provider-azure/blob/99678f0fff5b49fdc1fdcaadb50b116777d43d78/tests/kubemark/templates/hollow-node.yaml#L91

Recommendation, either:
* Stop depending on writing to files and remove flags `--log-file`, `--logtostderr` or
* Add go-runner to kubemark image and migrate `/kubemark --log-file=/var/log/kubelet-$(NODE_NAME).log <other flags>` to `/go-runner --log-file=/var/log/kubelet-$(NODE_NAME).log /kubemark  <other flags>`

/sig scalability
/wg structured-logging

**Comment by pohly** [comment]
Resolved in both k/k and kubernetes-sigs/cloud-provider-azure.

/close
