### ISSUE TITLE
kubeadm init fails to download coredns when using --image-repository.

### ISSUE THREAD

**Issue by Raptus1** [kubernetes/kubernetes#106128]
### What happened?

When I test to pull the image without custom image-directory it respects the coredns url structure:

pulling: k8s.gcr.io/coredns/coredns:v1.8.4

But it leaves the subfolder out completely skipping using *coredns/* when using --image-repository :
pulling: myregistry.local/coredns:v1.8.4

### What did you expect to happen?

I expected kubernetes to keep the full path to coredns when using private registry.

### How can we reproduce it (as minimally and precisely as possible)?

Test with private registry..? :)

### Kubernetes version

<details>

```console
$ kubectl version
 Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
please see:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

> Image paths between the default k8s.gcr.io and a custom repository specified using imageRepository may differ for backwards compatibility reasons. For example, one image might have a subpath at k8s.gcr.io/subpath/image, but be defaulted to my.customrepository.io/image when using a custom repository.

/kind support
/close

**Comment by Raptus1** [comment]
It seems like both areas did a change one coredns location to accommodate the other and then you ended up with the same problem again. 

k8s.gcr.io put coredns in a coredns subpath after people had been complaining about customrepos had coredns/coredns.
At the same time the code here got changed to remove the subpath when using custom imageregistry, also to accomodate the people having problem with the subpath.

So if we now can let custom image-registry use coredns/coredns: again, it will be sorted out properly.
