### ISSUE TITLE
Take taints/tolerations into consideration when calculating PodTopologySpread skew

### ISSUE THREAD

**Issue by nyarly** [kubernetes/kubernetes#106127]
### What would you like to be added?

When a pod has a topologySpreadConstraints set, nodes marks with an un-tolerated taint should be excluded from consideration when computing skew.

If considering all taints is infeasible (as implied by #80921), at least consider the Unschedulable taint.

### Why is this needed?

The existing behavior, which ignores taints because they _might_ be tolerated, leads to instability in the common use case of replacing or upgrading nodes in a cluster.

The behavior is this: the old node is cordoned, which puts an Unschedulable taint on the machine. Pods are evicted, and rescheduled. A pod with a topologySpreadConstraints considers the skew in the cluster - where the cordoned machine has 0 instances that match its labelSelector. Given the case where there are more pods in the topology set than there nodes, this means that only that one node is an acceptable scheduling target by topology, but its taint prevents scheduling there. As a result, the pod remains in Pending state until the cordoned node it removed from the cluster.

**Briefly**: the result of applying a topologySpreadConstraints in the face of upgrading a cluster's worker nodes is increased instability.

This is especially impactful in cloud hosted Kubernetes scenarios, where cluster upgrades are automated, and as a result happen under unattended (and poorly controlled) circumstances. In these circumstances, pods that are especially critical to operations can be left in a Pending state until the cordoned pod is force killed - in GKE that's about an hour.

**Comment by ahg-g** [comment]
hmm, I think this is a good case for excluding tainted nodes. @Huang-Wei  what was the reason we excluded node affinity but not taints?

**Comment by ahg-g** [comment]
@nyarly I think using `DoNotSchedule` has more problems than just this (see https://github.com/kubernetes/kubernetes/issues/105977 and https://github.com/kubernetes/kubernetes/issues/105291), so in the meantime I would suggest to use `ScheduleAnyway`.

**Comment by Huang-Wei** [comment]
@ahg-g This was brought up (#80921) to the table when PodTopologySpread was initially implemented. Back then, there were not enough data points showing which direction we wanted to head to. Another reason is TaintNodesByCondition and TaintBasedEvictions were not GA and thus extra logic was needed - both taints and conditions.

Node affinity is a hard requirement and explicitly related to topology domains, so it's intrusive to take it into consideration in the very beginning.

Overall I think it's a valid requirement, and I'm fine with excluding unscheduled taints (generated by k/k) in the PodTopologySpread feature.

**Comment by ahg-g** [comment]
/retitle Take taints/tolerations into consideration when calculating PodTopologySpread skew

**Comment by ahg-g** [comment]
@liggitt I think this is a change of default behavior, how can we proceed with this?

**Comment by liggitt** [comment]
> @liggitt I think this is a change of default behavior, how can we proceed with this?

if I'm understanding correctly, the scheduler is still considering tainted nodes which the pod does not tolerate as valid nodes for purposes of computing topology spread skew, preventing those pods from being scheduled to nodes that are actually available? That seems like a bug to me (and I'm not sure why it would the fix would only be applied to the `unschedulable` taint)

**Comment by Huang-Wei** [comment]
@liggitt you're understanding it right. The reason is that taints can be user-defined, or system-generated (like `unschedulable`). In terms of user-defined taints, they can be arbitrary and it's possible that the workloads can apply tolerations to tolerate them; while for system-generated ones, it's more due to system events so semantically we want to exclude upcoming pods from scheduling, unless the incoming pod has the corresponding toleration. So this PR introduced the change to only consider system-generated taint.

**Comment by liggitt** [comment]
> In terms of user-defined taints, they can be arbitrary and it's possible that the workloads can apply tolerations to tolerate them

but if the workloads *don't* tolerate them, we still want to leave pods that *could* be scheduled to available nodes unscheduled because of podTopologySpread skew settings that consider untolerated tainted nodes?

**Comment by Huang-Wei** [comment]
> but if the workloads _don't_ tolerate them, we still want to leave pods that _could_ be scheduled to available nodes unscheduled because of podTopologySpread skew settings that consider untolerated tainted nodes?

Yes. User-defined taints are treated as separate scheduling constraints, and thus handled separately. The same case applies to other scheduling directives as well. Like, if a node is tainted, a pod with podAffinity cannot be scheduled to that node even if there are pods matching its podAffinity constraints.

**Comment by liggitt** [comment]
I'm still confused why special-casing an `unschedulable` taint is correct... it looks like the logic of this plugin would be incorrect for all untolerated taints, not just `unschedulable`

**Comment by Huang-Wei** [comment]
> it looks like the logic of this plugin would be incorrect for all untolerated taints, not just unschedulable

In the implementation, we need to check if unschedulable taint is the only unsatisfied one. In other words, if any regular taint is unsatisfied, that node cannot be bypassed (same behavior as now)

**Comment by kerthcet** [comment]
I think @liggitt suggestions also make sense for user-defined taints will also lead to the unexpected pending pods. But system-generated taints are more common especially in large-scale cluster automation.

**Comment by liggitt** [comment]
Consistent treatment of system-defined and user-defined taints is essential, in my opinion

**Comment by Huang-Wei** [comment]
> Consistent treatment of system-defined and user-defined taints is essential, in my opinion

Thanks for the input. We're going to discuss in this week's sig meeting.

Another solution is to offer the option (i.e., honor all untolerated taints (default value), bypass all taints, honor unschedulable taint only) in the plugin's argument. WDYT?

https://github.com/kubernetes/kubernetes/blob/be5b9b4f8d8876090697e777e63d6a4c25738e71/staging/src/k8s.io/kube-scheduler/config/v1beta3/types_pluginargs.go#L93

**Comment by alculquicondor** [comment]
For backwards compatibility, we need this to be an option, but it should probably be in the constraint (pod spec).

**Comment by kerthcet** [comment]
sounds good to me. I'll work on it later.

**Comment by alculquicondor** [comment]
You need to do a KEP first

**Comment by Huang-Wei** [comment]
Rethink this a bit: given we have some implication (taking nodeSelector/nodeAffinity into consideration) plumbed into PodTopologySpread, and _may_ introduce more implications like conditional taints, probably we can use this chance to define explicit API fields over implication, to express its semantics clearly.

Here is a proposal: adding a field called `nodesExclusion` (temporary name) to [TopologySpreadConstraint](https://github.com/kubernetes/kubernetes/blob/73b68f5233297eeb60c832e1087edf2427a24e91/pkg/apis/core/types.go#L5605):

```go
type TopologySpreadConstraint struct {
    ......
    nodesExclusion:
        # boolean, defaults to true
        deriveNodeAffinity: true
        # []Taints, defaults to nil
        taints:
        - <unschedulable taint>
        - <customized taint>
        - ...
```

WDYT?

**Comment by kerthcet** [comment]
It's a good timing I supposed so. Back to the field `taints`, since we can't list all taints especially customized ones, wildcard should be supported right.

**Comment by alculquicondor** [comment]
probably better to express in a "positive" way, like "nodesInclusion". And to use enums instead of booleans. Also we need to only consider "NoSchedule" taints? Or should we include it in the API.

Can you think of a use case where the particular taint is important? Why not just use the tolerations?

Finer details of the API can be reviewed in the KEP and code reviews.

**Comment by Huang-Wei** [comment]
> Back to the field taints, since we can't list all taints especially customized ones, wildcard should be supported right.

Not sure it's a good idea to "introduce" another parser layer for wildcard. We'd better simply derive the semantics to `v1.Taint`.

> probably better to express in a "positive" way, like "nodesInclusion". 

I'm fine with either as long as the overall semantics is intrusive.

> Also we need to only consider "NoSchedule" taints?

Yes, `Effect` to be only `NoSchedule`.

> Can you think of a use case where the particular taint is important?

It's not about a particular taint. Typically users may specify the system-generated taints out there. They key point is based on Jordan's https://github.com/kubernetes/kubernetes/issues/106127#issuecomment-994240150, which states the preference of treating all taints equally. With the taints slice specified **explicitly**, there is no ambiguity.

> Why not just use the tolerations?

Not sure I got it right, you meant whether the tolerations of the pod spec should be verified? If so, that will be verified, and renaming `taints` to `taintsWhenUntolerated` may sound better.

> Finer details of the API can be reviewed in the KEP and code reviews.

Sure. Just a heads-up on whether this direction (explicitly define advanced nodes selection/bypassing rules within PodTopologySpread) sounds promising to everyone.

**Comment by alculquicondor** [comment]
`taintsWhenUntolerated` or `untoleratedTaints` sgtm. But I think there should be a mechanism to consider all taints.

**Comment by Huang-Wei** [comment]
> But I think there should be a mechanism to consider all taints.

If we name it `nodesInclusion`, yes; but for `nodesExclusion`, default case (nil slice) means to consider all taints :)

**Comment by alculquicondor** [comment]
is that assuming that, if you want the existing behavior, you leave `nodesExclusion` as `nil`?

**Comment by Huang-Wei** [comment]
Yes, I'm afraid that should be the default behavior, in terms of API compatibility.

**Comment by alculquicondor** [comment]
I think we should have a `TaintStrategy` field AND a list instead.

Similar to how we have `DefaultingType` and `DefaultConstraints` in `PodTopologySpreadArgs` (when type is `System`, `DefaultConstraints` is validated to be empty).

The strategies could be: `IgnoreTaints` (default), `RespectAllUntoleratedTaints`, `RespectExplicitUntoleratedTaints` (names could be improved. The list can only be empty if strategy is `RespectedExplicitUntoleratedTaints`.

**Comment by Huang-Wei** [comment]
> I think we should have a `TaintStrategy` field AND a list instead.

SG. Just a qq: `TaintStrategy` as the top-level field, or under nodesInclusion/nodesExclusion? I'm inclined to make **all** implicit nodes selection logic explicit, i.e., putting `TaintStrategy` under the so-called "advanced nodes selection/exclusion" field so we don't have any hidden/surprising implication.

**Comment by alculquicondor** [comment]
Agree that everything should be explicit. And better to place everything inside the new struct.

**Comment by kerthcet** [comment]
```
type topologySpreadConstraint struct {
	MaxSkew        int32
	TopologyKey    string
	Selector       labels.Selector
	NodeExclustion nodeExclusion
}

type nodeExclusion struct {
	// default to true, same behavior as now
	respectNodeAffinity bool
	// default to true, same behavior as now
	respectNodeSelector bool
	taintStrategy       taintStrategy
}

type taintStrategyName string

const (
	// Default value, will ignore taints and taints of taintStrategy is nil. Same behavior as now for backward API compatibility.
	ignoreTaints taintStrategyName = "ignoreTaints"
	// Verify all taints in node and taints of taintStrategy is nil.
	respectAllTaints taintStrategyName = "respectAllTaints"
	// Only verify the taints included in the taints of taintStrategy, mull not be empty.
	respectExplicitTaints taintStrategyName = "respectExplicitTaints"
)

type taintStrategy struct {
	name   taintStrategyName
	taints []v1.Taint
}
```
what about this?

**Comment by alculquicondor** [comment]
We can continue this discussion in the KEP PR, but:
- I prefer positive wording (inclusion, rather than exclusion)
- Avoid bools, use enums instead (ex: nodeAffinityPolicy: Ignore/Respect)
- NodeAffinity and NodeSelectors are the same thing. One API is just more expressive than the other, but there shouldn't be separate controls for them.

Separate discussion (also for the KEP): do we really need to add the taints array today? If we just have an enum today with Ignore/Respect values, we can (in the future) add the extra enum if there's demand for it.

I don't think we have the demand today. The original request in this issue said:

> If considering all taints is infeasible (as implied by #80921), at least consider the Unschedulable taint.

It is feasible to consider all taints with the added feature, so we don't have to add special treatments. @nyarly, do you agree?

**Comment by Huang-Wei** [comment]
> do we really need to add the taints array today?

This is based on the support of system-level Unschedulable taints, while also keeping semantics explicit. If supporting Unschedulable taints is optional, or even unnecessary, we can simply the design with enums (respect/ignore), and evaluate the "custom" option (accompanied with a taints slice) in the future.

@nyarly, based on your usecase, it seems the option of system-level Unschedulable taints is not mandatory, can you confirm?

**Comment by kerthcet** [comment]
also cc @fip-post-cz  for more use cases.

**Comment by sanposhiho** [comment]
Wouldn't it be better to add a note about this issue to the documentation?
Even after `NodeInclusionPolicies` is implemented and released, taints/tolerations are not taken into consideration by default for backward compatibility, and users may still face this problem.
The current behavior is written as follows, but it is just a single line at the bottom of the document, and users may not anticipate such a problem.
> Pods matched on tainted nodes are respected. See [Issue 80921](https://github.com/kubernetes/kubernetes/issues/80921)
https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#known-limitations

**Comment by kerthcet** [comment]
We can close this now since it's resolved by https://github.com/kubernetes/enhancements/issues/3094, reopen if needed.
/close
