### ISSUE TITLE
Network policy not listed

### ISSUE THREAD

**Issue by fOO223Fr** [kubernetes/kubernetes#106176]
### What happened?

`kubectl get all` outputs all resources except network policy resource

### What did you expect to happen?

i expect it to return all resources including network policy resource

### How can we reproduce it (as minimally and precisely as possible)?

Note: below yaml is taken from: https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-allow-all-ingress-traffic

Step 1:
```yaml
cat <<EOF | kubectl apply -f -
 ---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-ingress
spec:
  podSelector: {}
  ingress:
  - {}
  policyTypes:
  - Ingress
EOF
```

Step 2. `kubectl get all`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux controlplane 5.4.0-1056-gcp #60~18.04.1-Ubuntu SMP Tue Oct 19 15:05:21 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
@soltysh can you guide us here?

where is the `all` command checking the subresources?  `/k8s.io/kubectl/pkg/cmd/get/get.go`
is ok to list network policies too?

**Comment by soltysh** [comment]
`all` is an alias defined on the server and not in the client. Any resource can be added themselves to these aliases, or rather categories, see here for CRDs:
https://github.com/kubernetes/kubernetes/blob/582c4ebe267020ed59c1553b95c8ecc3e8b88c1a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go#L247-L249

Although, before you open a PR to add anything to all, I can already warn you not to do it. See https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#rules-for-extending-special-resource-alias---all and probably a couple of places where this was tried and rejected. `all` is wrong, b/c it can differ from cluster to cluster, I'd encourage for you to define something like `networks` or something similar which will allow you to group all network releated resources. See https://github.com/kubernetes/kubernetes/pull/95603 for how we defined `api-extensions` to encompass all of API extensions bits. That's the overall recommendation.

**Comment by NikhilSharmaWe** [comment]
@soltysh So, the process of defining something like networks to group all network related resources will be similar to how you introduced api-extensions category in k8s apiserver. In that case you added k8s.io/apiserver/pkg/registry/rest but what will be in case for adding network policies.
Am I thinking reasonable or not.

**Comment by soltysh** [comment]
> @soltysh So, the process of defining something like networks to group all network related resources will be similar to how you introduced api-extensions category in k8s apiserver. In that case you added k8s.io/apiserver/pkg/registry/rest but what will be in case for adding network policies.

correct

**Comment by NikhilSharmaWe** [comment]
@soltysh In that case you added k8s.io/apiserver/pkg/registry/rest but what will be in case for adding network policies.

**Comment by soltysh** [comment]
@NikhilSharmaWe you'd need to implement `rest.CategoriesProvider` for https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/networking/networkpolicy/storage/storage.go and other places which you want to include in that category similarly to that PR of mine.
