### ISSUE TITLE
ServiceAccount update is creating a new token secret

### ISSUE THREAD

**Issue by leonz** [kubernetes/kubernetes#106131]
### What happened?

If you run `kubectl replace` on a ServiceAccount, the following happens:

- The serviceAccount receives an `update`
- A new token is generated, mapped to the serviceAccount's name and uid
- The previous token is not removed, as it is also mapped to the serviceAccount name and uid

Thus, we end up in a situation where every `replace` call results in a leaked secret resource.

To be even more specific, I think what's happening is:

- the `update` removes the "secret" field because it's not in the original spec for the resource
- however, `update` does _not_ remove the metadata that sets the uid
- so our controller fights the kubernetes token controller

### What did you expect to happen?

Either a new token secret is not created, or the old one is allowed to be cleaned up.

### How can we reproduce it (as minimally and precisely as possible)?

Resource: sa.yaml
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example
```

```
[~] $ kubectl create -f sa.yaml
serviceaccount/example created
[~] $ kubectl get sa
NAME      SECRETS   AGE
example   1         56s
[~] $ kubectl get secret
NAME                  TYPE                                  DATA   AGE
example-token-wj85v   kubernetes.io/service-account-token   3      92s
[~] $

[~] $ kubectl replace -f sa.yaml
serviceaccount/example replaced
[~] $ kubectl get sa
NAME      SECRETS   AGE
example   1         116s
[~] $ kubectl get secret
NAME                  TYPE                                  DATA   AGE
example-token-ghjf4   kubernetes.io/service-account-token   3      11s
example-token-wj85v   kubernetes.io/service-account-token   3      2m1s
```

### Kubernetes version

<details>
[~] $ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
Minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
This is working as expected. The secrets list in the serviceaccount tracks the secret that should be auto-mounted into pods. The update is removing that record. That prompts the controller to generate a new auto-mounted secret.

The old secret still contains a valid token, which can still be used to authenticate. When the service account object is deleted, that secret will be deleted as well.

https://github.com/kubernetes/enhancements/pull/2800 proposes stopping the autogeneration of service account tokens entirely, and would resolve this issue as well.

/close
