### ISSUE TITLE
Controllers report unique events for generated pod names when rejected by validating admission

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#106160]
### What happened?

I used the PodSecurity webhook on 1.23.0-alpha.4 and got a pod rejected. The events were pretty spammy:

```
Events:
  Type     Reason        Age                  From                   Message
  ----     ------        ----                 ----                   -------
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-9lg7p" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-9htgx" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-lcr8l" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-l7gg8" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-xcfzl" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-7bx5p" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-tmzjx" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-gblwm" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
  Warning  FailedCreate  10m                  replicaset-controller  Error creating: admission webhook "pod-security-webhook.kubernetes.io" denied the request: pods "echo-54c9c5d4cb-5zfmm" is forbidden: violates PodSecurity "restricted:latest": seccompProfile (pod or containers "istio-validation", "istio-proxy" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

I think this is because the pod name is included in the event so it cannot deduplicate them. In other webhook failures, I have seen these collapsed - possibly due to not including the name in the error?

This is pretty minor cosmetic issue and may not be applicable in the Beta version - I didn't test it.

### What did you expect to happen?

A single event collapsed

### How can we reproduce it (as minimally and precisely as possible)?

Just get a pod rejected

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.4", GitCommit:"359b722c19ff163fb267f2747d794bd667d4f91d", GitTreeState:"clean", BuildDate:"2021-11-04T17:26:07Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
related dedupe issue:
https://github.com/kubernetes/kubernetes/issues/106160

**Comment by liggitt** [comment]
hmm... I get the same pod-name-prefixed error when using the built-in admission plugin:

> `kubectl create -f pod.json `
> `Error from server (Forbidden): error when creating "pod.json": pods "pause" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "busybox" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "busybox" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "busybox" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "busybox" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")`

That said, I think all forbidden errors from admission prefix with the resource type and name by default, so I don't think this is unique to PodSecurity...

**Comment by liggitt** [comment]
it looks like it also logs events in the success case that include the pod name, which seem like they would be spammy:

> r.Recorder.Eventf(object, v1.EventTypeNormal, SuccessfulCreatePodReason, "Created pod: %v", newPod.Name)

**Comment by liggitt** [comment]
also, curious if the replicaset controller backed off when it got repeatedly rejected

**Comment by howardjohn** [comment]
I also have a mutating webhook on pods (Istio) which maybe contributes? 

Also your pod being named `pause` may suggest its not created by a Deployment/Replicaset as I was doing - sorry if I wasn't more clear in the description.

From failures I have seen in the past they look like:
```
  Warning  FailedCreate      80s (x15 over 2m42s)  replicaset-controller  Error creating: Internal error occurred: failed calling webhook "namespace.sidecar-injector.istio.io": failed to call webhook: the server could not find the requested resource
```

^ from a non 200 failure

`Warning  FailedCreate      2s (x11 over 7s)  replicaset-controller  Error creating: admission webhook "namespace.sidecar-injector.istio.io" denied the request without explanation`

^ from a Allowed=false failure

Those are both from mutating webhook failures though... perhaps validation is different.

> also, curious if the replicaset controller backed off when it got repeatedly rejected

Ill have to get another cluster setup to be sure but I do believe it did.

**Comment by liggitt** [comment]
> Those are both from mutating webhook failures though... perhaps validation is different.
> 
> >

ah, that's the key... replicasets create using generateName, which assigns a particular name post-mutating-webhooks, pre-validation-webhooks

**Comment by liggitt** [comment]
also, based on https://github.com/istio/istio/blob/71289b584b85c149ca0709d12f46317f1bbb7de0/pkg/kube/inject/webhook.go#L272, it looks like the istio sidecar mutating webhook is not returning a [standard forbidden error](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L207-L216), like the [PodSecurity webhook is](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/admission/response.go#L55) (and most built-in admission plugins do)

**Comment by liggitt** [comment]
/remove-sig auth
/sig apps

This is a general issue for controllers using generateName and writing events in response to a pod rejection or pod creation.

It looks like there is some deduplication of events by reason (see NewEventCorrelator -> EventAggregatorByReasonFunc), so eventually the events would start getting collapsed (after ~10 instances), but that is sort of spammy.

When a controller is creating a pod with a generated name, it could use the GenerateName of the input, rather than the randomized name of the output when reporting events... an example of what that could look like is https://github.com/liggitt/kubernetes/commit/db61eb20d9d9eaafd35e13689b9b57dc0f57e7a1
