### ISSUE TITLE
Remove deprecate klog flag usage from windows cluster setup

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#106101]
/kind feature

Hey, in K8s 1.23 we are planning to deprecate multiple klog flags. [KEP-2845](https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components/README.md)

Deprecated flags: `--log-dir`, `--log-file`, `--log-flush-frequency`, `--logtostderr`, `--alsologtostderr`, `--one-output`, `--stderrthreshold`, `--log-file-max-size`, `--skip-log-headers`, `--add-dir-header`, `--skip-headers`, `--log-backtrace-at`

One of the alpha milestones is requires us to remove usage of deprecated flags within K8s repo. Examples found for windows 
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/cluster/gce/util.sh#L892
* [ ] https://github.com/kubernetes/kubernetes/blob/ec8e6e877899442da9eb0c87a9612cb4dc20373a/cluster/gce/util.sh#L938

/sig windows
/wg structured-logging

**Comment by pohly** [comment]
/assign

I've started looking into this. Part of the problem is that go-runner is not part of kubernetes-node-windows-amd64.tar.gz. I suspect that is where the scripts get kubelet.exe and kube-proxy.exe from.
