### ISSUE TITLE
`make WHAT=cmd/kubectl` not parallelizable?

### ISSUE THREAD

**Issue by branchvincent** [kubernetes/kubernetes#106165]
### What happened?

First, thanks for all your hardwork on this amazing project!

Homebrew's build of `kubectl` has been unreliable (e.g. see the [most recent failure](https://github.com/Homebrew/homebrew-core/runs/4033957174?check_suite_focus=true#step:7:122) from https://github.com/Homebrew/homebrew-core/pull/88177 and previously https://github.com/Homebrew/homebrew-core/pull/82694#issuecomment-893151472). Normally, we see an error like:

```
failed to create symbolic link '/private/tmp/kubernetes-cli-20211028-9874-jxab49/_output/bin': File exists
```

coming from https://github.com/kubernetes/kubernetes/blob/ed42bbd722a14640f8b5315a521745e7526ff31b/hack/lib/golang.sh#L559

It appears this is due to race conditions when using `make --jobs`. I just wanted to confirm that the build is not parallelizable by design, or see if it could be made so with minor modifications (in which case, I'd be happy to contribute!)

### What did you expect to happen?

For `make --jobs` to work reliably

### How can we reproduce it (as minimally and precisely as possible)?

```
$ git clone https://github.com/kubernetes/kubernetes.git
$ cd kubernetes && make WHAT=cmd/kubectl -j8
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-dirty", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"dirty", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.17.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
AFAIK, the symbolic links are a GOPATH hack that should go away once k8s switches entirely to gomod:
https://github.com/kubernetes/kubernetes/issues/82531

SIG Release can provide additional feedback here.

**Comment by BenTheElder** [comment]
Where the build scripts are parallelizable they do so internally (e.g. cross compiling, building all the code generators, building multiple WHAT binaries like `make WHAT=cmd/kubectl cmd/kubelet`), the make targets are mostly a convenience / portable alias, the substantial build logic including dependency ordering etc. is primarily in a big pile of bash that does some things in parallel 🙃

**Comment by BenTheElder** [comment]
If we trace `make WHAT=cmd/kubectl` we can see that it's `all: generated_files` with `all` being `hack/make-rules/build.sh $(WHAT)` and `generated_files` being recursive make (`$(MAKE) -f Makefile.generated_files $@ CALLED_FROM_MAIN_MAKEFILE=1`). 

The only substantial make logic is contained in the rather hairy https://github.com/kubernetes/kubernetes/blob/master/build/root/Makefile.generated_files called by that recursive generated_files target (hi @thockin 🙃 ), otherwise for the main makefile there's not really much in the way of targets to make parallel at the make level.

I would not be surprised to find that the generated_files makefile is not concurrent-make-safe and editing/reading/debugging it is ... fun :+)

**Comment by BenTheElder** [comment]
Thank you for maintaining this on the homebrew side :-)
