### ISSUE TITLE
master node becomes worker nodes after network partition

### ISSUE THREAD

**Issue by nicolehanjing** [kubernetes/kubernetes#106187]
### What happened?

When the master node is deleted from k8s cluster due to some network failures, Cloud Provider Controller Manager notices that this node VM is no longer present on the cloud provider due to network partition, so Cloud Provider Controller Manager will remove this node from the cluster. 
Later when this node is added back to k8s cluster, it is added back without the required master node taints/labels.
The master node become worker node and some pods are scheduled to that node by mistake and can not be running.

Tho the current behavior of deleting node VM from Cloud Provider when VM failover is on-going is expected, but when the node is re-registered, it should get the same role and behavior as before. And this master role label is added by kubelet.

I'm wondering if this is the expected behavior of kubelet or is that something to be fixed?

### What did you expect to happen?

The master role label should be added to the node when it's re-registered.

### How can we reproduce it (as minimally and precisely as possible)?

1. delete the master node
2. re-register the node via kubelet
3. see the master role label is deleted from the node

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.21
```

</details>

### Cloud provider

<details>
1.21
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by test-test-max** [comment]
### Install tools
kubeadm
### OS version
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
### Container runtime (CRI) and and version
Docker Engine - Community
docker Version:           20.10.10
### CSI version
 k8s.gcr.io/sig-storage/csi-provisioner:v3.0.0
 k8s.gcr.io/sig-storage/csi-attacher:v3.3.0
 k8s.gcr.io/sig-storage/csi-resizer:v1.3.0
 k8s.gcr.io/sig-storage/livenessprobe:v2.4.0

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

this looks like an orchestration issue. Kubelet just register the node as it was told

**Comment by divyenpatel** [comment]
Refer to the following steps performed on the multi-master setup.

We have 3 master nodes.

```
# kubectl get nodes -o wide
NAME                         STATUS   ROLES                  AGE     VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-control-12-1635788875    Ready    control-plane,master   8m28s   v1.21.1   10.187.103.6     10.187.103.6     Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-230-1635788862   Ready    control-plane,master   9m47s   v1.21.1   10.187.102.230   10.187.102.230   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-975-1635788850   Ready    control-plane,master   11m     v1.21.1   10.187.107.160   10.187.107.160   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-106-1635788889      Ready    <none>                 7m53s   v1.21.1   10.187.108.52    10.187.108.52    Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-38-1635788914       Ready    <none>                 7m2s    v1.21.1   10.187.107.120   10.187.107.120   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-670-1635788901      Ready    <none>                 7m28s   v1.21.1   10.187.110.155   10.187.110.155   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
```

Deleted one of the master node.

```
# kubectl delete node k8s-control-975-1635788850
node "k8s-control-975-1635788850" deleted
```

Restarted kubelet on the master to initiate self-registration.

```
# root@k8s-control-975-1635788850:~# systemctl restart kubelet
root@k8s-control-975-1635788850:~# 
```

node added without following labels and taints, so it appears as a worker node.

Labels:

- node-role.kubernetes.io/control-plane=
- node-role.kubernetes.io/master=

Taints:

- node-role.kubernetes.io/master:NoSchedule


```
# kubectl get nodes -o wide
NAME                         STATUS   ROLES                  AGE     VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-control-12-1635788875    Ready    control-plane,master   9m43s   v1.21.1   10.187.103.6     10.187.103.6     Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-230-1635788862   Ready    control-plane,master   11m     v1.21.1   10.187.102.230   10.187.102.230   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-975-1635788850   Ready    <none>                 4s      v1.21.1   10.187.107.160   10.187.107.160   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-106-1635788889      Ready    <none>                 9m8s    v1.21.1   10.187.108.52    10.187.108.52    Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-38-1635788914       Ready    <none>                 8m17s   v1.21.1   10.187.107.120   10.187.107.120   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-670-1635788901      Ready    <none>                 8m43s   v1.21.1   10.187.110.155   10.187.110.155   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
```

Added back required taints and labels to make node as control-plane, master node.

```
# kubectl taint node k8s-control-975-1635788850 node-role.kubernetes.io/master:NoSchedule
node/k8s-control-975-1635788850 tainted
```

```
# kubectl label node k8s-control-975-1635788850 node-role.kubernetes.io/control-plane=
node/k8s-control-975-1635788850 labeled
```

```
# kubectl label node k8s-control-975-1635788850 node-role.kubernetes.io/master=
node/k8s-control-975-1635788850 labeled
```


```
# kubectl get nodes -o wide
NAME                         STATUS   ROLES                  AGE   VERSION   INTERNAL-IP      EXTERNAL-IP      OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8s-control-12-1635788875    Ready    control-plane,master   24m   v1.21.1   10.187.103.6     10.187.103.6     Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-230-1635788862   Ready    control-plane,master   25m   v1.21.1   10.187.102.230   10.187.102.230   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-control-975-1635788850   Ready    control-plane,master   14m   v1.21.1   10.187.107.160   10.187.107.160   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-106-1635788889      Ready    <none>                 23m   v1.21.1   10.187.108.52    10.187.108.52    Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-38-1635788914       Ready    <none>                 22m   v1.21.1   10.187.107.120   10.187.107.120   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
k8s-node-670-1635788901      Ready    <none>                 23m   v1.21.1   10.187.110.155   10.187.110.155   Ubuntu 20.04.2 LTS   5.4.0-66-generic   docker://20.10.5
```

After configuring kubelet with the following parameters

Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf `--register-with-taints=node-role.kubernetes.io/master:NoSchedule"`

I see node re-registration happening with correct taint.

but how do we register nodes with required control plane labels using kubelet config?

I have tried out  kubelet argument `--node-labels` but it is not helping to set "node-role.kubernetes.io/control-plane=" and "node-role.kubernetes.io/master=" labels on the node.
 

```
# kubelet --help | grep node-labels
      --node-labels mapStringString                              <Warning: Alpha feature> Labels to add when registering the node in the cluster.  Labels must be key=value pairs separated by ','. Labels in the 'kubernetes.io' namespace must begin with an allowed prefix (kubelet.kubernetes.io, node.kubernetes.io) or be in the specifically allowed set (beta.kubernetes.io/arch, beta.kubernetes.io/instance-type, beta.kubernetes.io/os, failure-domain.beta.kubernetes.io/region, failure-domain.beta.kubernetes.io/zone, kubernetes.io/arch, kubernetes.io/hostname, kubernetes.io/os, node.kubernetes.io/instance-type, topology.kubernetes.io/region, topology.kubernetes.io/zone)
```

`node-role.kubernetes.io/control-plane` and `node-role.kubernetes.io/master` is not permitted keys for `--node-labels` argument.

@SergeyKanzhelev do you know how to solve this problem?

cc: @SandeepPissay

**Comment by pacoxu** [comment]
This seems to be an expected behavior in my mind. 
https://github.com/kubernetes/kubernetes/blob/cde45fb161c5a4bfa7cfe45dfd814f6cc95433f7/cmd/kubeadm/app/phases/markcontrolplane/markcontrolplane.go#L38-L59

`kubeadm join control-plane ` needs to add labels and taints in the `mark-control-plane` phase.

**Comment by pacoxu** [comment]
There are some explanation about why we should not add node role labels by node itself in https://github.com/kubernetes/kubernetes/issues/91664#issuecomment-637491037.

> Nodes may not self-assign role labels for security reasons. To add a master role to a node, the label must be applied externally. See https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction for permitted labels/label-patterns

**Comment by sftim** [comment]
Maybe we should document that restriction more clearly? This is potentially going to come up in connection to switching the taint used for control plane nodes (planned, I think, for v1.24).

**Comment by neolit123** [comment]
> This seems to be an expected behavior in my mind.

yes, exactly. the explanation https://github.com/kubernetes/kubernetes/issues/106187#issuecomment-994325709 is valid.

> Maybe we should document that restriction more clearly? This is potentially going to come up in connection to switching the taint used for control plane nodes (planned, I think, for v1.24).

we can document that in the kubeadm "create a cluster" guide.
i've logged https://github.com/kubernetes/website/issues/31972

**Comment by neolit123** [comment]
> Deleted one of the master node.

deleting the CP node object is a disruptive operation and you should only do it if you want the node to go away.
the node that you are getting post restart is no longer managed by kubeadm. it is a new node with the same name. with that, it also missing at least one important annotation and other kubeadm managed specifics that may land in the future.

there isn't much we can do about this scenario on the kubelet / kubeadm sides.

/kind support
/close

**Comment by neolit123** [comment]
> but how do we register nodes with required control plane labels using kubelet config?

if you'd like to continue deleting the node like that, you have to manually restore the node metadata with a privileged kubeconfig / kubectl call.

so it can look like this:
- fetch metadata from node object
- delete node object
- restart kubelet
- re-apply metadata

but as noted this is unsupported by kubeadm in general.
