### ISSUE TITLE
Essentially all kubectl commands should accept a filename param

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#10628]
Forked from #10493

I'd like essentially all commands operating on sets of resources to accept `-f`. The general idea is that if I have a directory full of config files, I want to use that to construct a list of objects on which to perform arbitrary operations.

Concretely, the following commands would need to accept FilenameParam:
* describe
* get
* expose
* label (and annotate, if/when we add that command)
* patch
* scale

cc @krousey @smarterclayton @deads2k @jlowdermilk @ghodss @andronat

**Comment by feihujiang** [comment]
Does it  get "approved" ? If it does, Is there anyone to work on this? If not, I'd like to work on this.

**Comment by andronat** [comment]
@feihujiang as far as I know this is free. I had it my plans to do it but I am going to be busy this week with some other issues. So you can take it over.

**Comment by feihujiang** [comment]
@andronat Thanks for your reply. I start to work on this.

**Comment by feihujiang** [comment]
@bgrant0607 I think small PRs could be reviewed easily, so I new pull request for each of these commands. Is this OK?

**Comment by bgrant0607** [comment]
@feihujiang Separate PR for each is a good approach. Note, however, we won't be able to review and merge them until after 1.0 is cut.

**Comment by feihujiang** [comment]
@bgrant0607  Thanks, I see.

**Comment by kargakis** [comment]
@bgrant0607 this is fixed now

**Comment by bgrant0607** [comment]
Thanks
