### ISSUE TITLE
[kubectl-convert] running `kubectl-convert` on MutatingWebhookConfiguration causes apply fail

### ISSUE THREAD

**Issue by georgettica** [kubernetes/kubernetes#106249]
the error stems from:

```
$ kubectl create -f webhook.yaml
The MutatingWebhookConfiguration "webhook" is invalid: webhooks[0].sideEffects: Unsupported value: "Unknown": supported values: "None", "NoneOnDryRun"
```

after some digging I saw this is the default value it it's supposed to fail, not sure if this is waned behaviour, but it's for sure not expected
https://github.com/kubernetes/kubernetes/blob/48da959dbff18bfef6e801bd8c8ab3c88b7a7650/pkg/apis/admissionregistration/types.go#L105

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by georgettica** [comment]
/sig cli
I guess?

**Comment by liggitt** [comment]
The default value for the field in v1beta1 ("Unknown") is not permitted in new objects created via the v1 API

See https://kubernetes.io/docs/reference/using-api/deprecation-guide/#webhook-resources-v122 for details:

> webhooks[*].sideEffects default value is removed, and the field made required, and only None and NoneOnDryRun are permitted for v1

**Comment by liggitt** [comment]
`kubectl-convert` does a mechanical transformation from the v1beta1 to the v1 versions, applying all v1beta1 defaults to preserve a semantically identical definition. In some cases, like this one, the GA API tightens the permitted values.

**Comment by georgettica** [comment]
Then how can we make the user experience better without compromising by adding an edge case for these stuff?

**Comment by liggitt** [comment]
Some of the changes to v1 have to be explicitly  decided/acknowledged by the user since they change the semantics of the object. I don't think we should work to silently/automatically change the meaning of beta objects so they can be created via v1.

**Comment by georgettica** [comment]
I guess I'll leave it at that though my opinion differs.

Thanks for taking the time and answering this!
