### ISSUE TITLE
How to query resource utilization metrics from the pod

### ISSUE THREAD

**Issue by shankeriyer** [kubernetes/kubernetes#10624]
Hi 
I am trying to query the actual resource utilization of containers running with a pod. Is there a mechanism with the API that provides for that?
Thanks
Shanker

**Comment by yujuhong** [comment]
You can query kubelet directly for the information.
```
    // /stats/<pod name>/<container name>                   : Stats for Kubernetes pod/container
    // /stats/<namespace>/<pod name>/<uid>/<container name> : Stats for Kubernetes namespace/pod/uid/container
```
For example. "curl --insecure https://localhost:10250/stats/foo/bar"
