### ISSUE TITLE
Graceful node shutdown not detaching persistent volumes when pods are evicted

### ISSUE THREAD

**Issue by fhke** [kubernetes/kubernetes#106227]
### What happened?

When a node with graceful node shutdown is shut down, persistent volumes attached to the node are not detached when the pod using the corresponding persistent volume claim is evicted from the node. After the node shutdown completes the associated VolumeAttachment objects are eventually removed but this tends to take 6+ minutes, which presents issues for replacement pods using ReadWriteOnce volumes as they cannot be scheduled until the volume is free again.

### What did you expect to happen?

Persistent volume(s) to be detached from the node as soon as the pod using them is evicted, so that the replacement for this pod can be scheduled again. This is the behaviour experienced when a node is drained using `kubectl drain`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable [graceful node shutdown](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/) on a kubernetes worker node in AWS
2. Create a StatefulSet that uses persistent volumes in EBS, and ensure that at least one of its pods is scheduled on the worker node with graceful shutdown enabled
3. Shut down the worker node from step 1
4. When the pod(s) of the statefulset created in step 2 running on the node are evicted, the volume(s) will remain attached to the node and the corresponding VolumeAttachment object(s) will not be deleted. This causes the replacement pods to stay in an unschedulable pending state until the volumes are detached.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS & kube-controller-manager v1.21.5
</details>

### OS version

<details>
Fedora CoreOS 33 & 34
</details>

### Install tools

<details>
Bootkube
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker & ContainerD
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@fhke can you please collect kubelet logs on shutdown so it will be easier to troubleshoot?

/assign @bobbypage 
/triage needs-information

**Comment by fhke** [comment]
Hi @SergeyKanzhelev, sorry for the delay in response. I figured out the issue - the ebs csi node daemonset was running with a non-critical priorityclass, so was unregistering before the `TearDown` occurred:

```
Jan 20 17:21:28 ip-10-252-24-234.eu-west-1.compute.internal kubelet[3038376]: {"ts":1642699288732.7266,"msg":"Node became not ready","v":0,"node":"ip-10-252-24-234.eu-west-1.compute.internal","condition":{"type":"Ready","status":"False","lastHeartbeatTime":"2022-01-20T17:21:28Z","lastTransitionTime":"2022-01-20T17:21:28Z","reason":"KubeletNotReady","message":"node is shutting down"}}
Jan 20 17:21:29 ip-10-252-24-234.eu-west-1.compute.internal kubelet[3038376]: {"ts":1642699289243.836,"msg":"kubernetes.io/csi: registrationHandler.DeRegisterPlugin request for plugin ebs.csi.aws.com\n","v":0}
Jan 20 17:21:30 ip-10-252-24-234.eu-west-1.compute.internal kubelet[3038376]: {"ts":1642699290807.2246,"msg":"operationExecutor.UnmountVolume started for volume \"www\" (UniqueName: \"kubernetes.io/csi/ebs.csi.aws.com^vol-024f4e9534724df85\") pod \"84835e99-f6a8-4118-89fe-43ffb79caf30\" (UID: \"84835e99-f6a8-4118-89fe-43ffb79caf30\") ","v":0}
Jan 20 17:21:30 ip-10-252-24-234.eu-west-1.compute.internal kubelet[3038376]: {"ts":1642699290808.9722,"msg":"Operation for \"{volumeName:kubernetes.io/csi/ebs.csi.aws.com^vol-024f4e9534724df85 podName:84835e99-f6a8-4118-89fe-43ffb79caf30 nodeName:}\" failed. No retries permitted until 2022-01-20 17:21:31.308785718 +0000 UTC m=+31.678927274 (durationBeforeRetry 500ms). Error: \"UnmountVolume.TearDown failed for volume \\\"www\\\" (UniqueName: \\\"kubernetes.io/csi/ebs.csi.aws.com^vol-024f4e9534724df85\\\") pod \\\"84835e99-f6a8-4118-89fe-43ffb79caf30\\\" (UID: \\\"84835e99-f6a8-4118-89fe-43ffb79caf30\\\") : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name ebs.csi.aws.com not found in the list of registered CSI drivers\"\n","v":0
```
