### ISSUE TITLE
Add custom formatter for podData and nodeInfo for `pkg/scheduler/internal/cache/debugger/dumper.go`

### ISSUE THREAD

**Issue by shivanshu1333** [kubernetes/kubernetes#106276]
### What would you like to be added?

We need to add a custom formatter like [this](https://gist.github.com/shivanshu1333/10a801d10c8f790b2e12e50cfb451dc7), test case to see [result](https://gist.github.com/shivanshu1333/3e7b7cda9fad55c2065900cd30f75781) as part of structured logging

### Why is this needed?

Part of structured logging https://github.com/kubernetes/enhancements/issues/1602

**Comment by pohly** [comment]
Is this still relevant?

If I remember correctly, we came to the conclusion that formatting as multi-line strings is what developers expect also for JSON output.

**Comment by pohly** [comment]
https://github.com/kubernetes/kubernetes/pull/108159 contains the conversion of `dumper.go` to `klog.InfoS` without a custom formatter and GitHub will close this issue here once it gets merged. We can reopen if that isn't the right solution.

**Comment by liggitt** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/108159
