### ISSUE TITLE
Group Namespace and Cluster in UX

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10626]
I'm proposing a best practice for Kubernetes UX:  **Group namespace with cluster, not name**
### Rationale

Teams will frequently be exposed to the existence of multiple clusters:
- vagrant on laptop for development on airplane
- testing new version of Kubernetes software
- multiple divisions in company who refuse to share nodes
- multi-cloud/multi-region 

The tuple of (ClusterName, Namespace) uniquely identifies a group of resources, globally.
A bare Namespace string alone does not because teams may sometimes want to use the same namespace name in multiple clusters.  

The tuple of (ClusterName, Namespace) will be a "thing" in user's minds.  Some UI operations:
- show me all the (ClusterName, Namespace) to which I have access to
- show me the ones I have accessed recently
- give (ClusterNameA, NamespaceA) a cute nickname for use in the UI.
- in a global list of resources, click on (ClusterNameA, NamespaceA) and show me more resources in that namespace.
- take all the resources in (ClusterNameA, NamespaceA) and make copies in (ClusterNameB, NamespaceB)  
  I'm not saying to actually render this as something like `(a.clusters.k8s.example.com, mynamespace)` in a UI.  But, we should pick a few format that make sense and use them.  And nicknames for these will help the UI.
- allocate me a new namespace in the appropriate cluster, based on company policy, lowest price, type of work being done, etc.

The tuple of (ClusterName, Namespace) is maps to/from an URL string prefix, e.g. `(a.clusters.example.com, foo)` :left_right_arrow: `https://a.clusters.example.com/api/v1/namespace/foo`.  This opens up some possibilities:
- vanity names for hosted namespaces: proxy from `https://mycluster.com/k8s/api/v1/` to `https://a.clusters.example.com/api/v1/namespace/foo/`.    Everything after that prefix stays the same.
- virtual (cluster, namespace), behind which there is machinery to map to some physical (cluster, namespace).  machinery can point to different (cluster, namespace) in event of maintenance or DR.

You can build a fully-qualified URL for a resource given (ClusterName, Namespace) plus api version plus tuple of (Kind, Name).  We already show `kind/name` in the CLI.  For example, `kubectl create -f file` outputs all the `kind/name` of what it created.  If you already have an URL string prefix for the clustername and namespace, then you can just paste these together.
### Current State

Things that follow this principle:
- In kubectl, the "context" concept encompasses both cluster and namespace (but also some other stuff).

Things that do not:
- `kubectl get --all-namespaces pods` shows `NAME` as `namespace/name`.  We should just add another column in this case which shows the namespace.
-  kubectl should accept slash-based specification of namespace and resource (#10591)
- in cockpit, name is shown right next to namespace: https://github.com/cockpit-project/cockpit/pull/2362, but "cluster" is on the tab.  what will it do when there are multiple clusters?
- probably more stuff.

**Comment by erictune** [comment]
@stefwalter who I think is working on UIs for openshift, for this thoughts on this proposal

@smarterclayton to redirect to other openshift UI people for their feedback.

@bgrant0607 for obvious reasons.

**Comment by erictune** [comment]
Related:
#3731 #8225

**Comment by bgrant0607** [comment]
I agree we should nuke the namespace/name syntax. 

There are at least 2 perspectives to consider:
1. Ordinary users, who will just live within a single namespace.
2. Cluster admins, who will have access to all namespaces.

Will think about the rest when I have time.

**Comment by erictune** [comment]
Yes, we should not join two things with a slash if that thing is not a substring of a resource URL.

**Comment by erictune** [comment]
Brian also mentioned how api groups will affect URL structure.  Consider that.

**Comment by bgrant0607** [comment]
See also:
https://github.com/GoogleCloudPlatform/kubernetes/issues/3731#issuecomment-82602492
https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-117764944

**Comment by smarterclayton** [comment]
@liggitt

On Wed, Jul 1, 2015 at 1:53 PM, Brian Grant <notifications@github.com>
wrote:

> See also:
> #3731 (comment)
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/3731#issuecomment-82602492>
> #10009 (comment)
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/10009#issuecomment-117764944>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/10626#issuecomment-117765526>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by stefwalter** [comment]
In general I like this. In Cockpit there would be a global selector with "cluster, Namespace" in a list, and that would filter what objects the various views show. 

There are two wrinkles:

 1. We want to have some dashboard views that show limited information about services in all namespaces on a cluster. This needs some more thought on how navigation between a filtered view (one cluster and namespace) and an unfiltered view (one cluster).
 2. When there is only one cluster, it becomes repetitive and confusing to include the cluster name in front of the namespaces in a list. We'd probably just not show the cluster info in that case.

Important to remember that people deploying canned applications (non-developers) will typically be deploying each one to a new namespace (eg: every app wants to have a 'database' service). So it will be common to have people interacting with many namespaces. It'll also be common for these same people to just have one cluster they care about.

> in cockpit, name is shown right next to namespace: cockpit-project/cockpit#2362, but "cluster" is on the tab.

 * We need to come up with a better name for the tab. I guess "Kubernetes" isn't bad, although I was hoping for something less scary to the uninitated.
