### ISSUE TITLE
[KEP:2133] E2E tests for external Kubelet Credential Provider

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#106248]
### What would you like to be added?

Kubelet credential provider is in alpha since 1.20 release, we need to add e2e tests to move it to beta.

**Current e2e tests for intree credential providers:**
[1]  https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/runtime_conformance_test.go#L61 (uses intree docker config credential provider) 
[2] https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/rc.go#L68 (uses intree gcp credential provider)
[3] https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/replica_set.go#L113 (uses intree gcp credential provider)

The job pull-kubernetes-e2e-gce-ubuntu-containerd fails with replica sets private image tests if external credential provider is enabled by default

**Problems in adding e2e tests for external credential providers**
-  The credential provider binary and config file needs to be installed on node VM before Kubelet starts, external cloud providers credential providers like GCP only supported to install with external cloud providers
- Tests using intree docker config provider are part of node conformance tests

**Work needs to be done**
1.  Provide a way to run existing node conformance tests[1] with external credential provider
A sample-credential-provider repo needs to be created under k8s-sigs which can be build and installed via node e2e tests to run existing node conformance tests

2. Migrate the replica set tests [2] & [3] to out of tree gcp credential provider 
Need help from gcp cloud provider team to work on this.

/sig cloud-provider node
/ cc @cheftako @dims @endocrimes @DangerOnTheRanger @andrewsykim @SergeyKanzhelev 

### Why is this needed?

KEP: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2133-kubelet-credential-providers
KEP issue: https://github.com/kubernetes/enhancements/issues/2133

**Comment by adisky** [comment]
@SergeyKanzhelev @DangerOnTheRanger @cheftako Is there any image available with gcp cloud provider+ credential provider that i can use directly to run e2e tests?

cc @spiffxp Also for any inputs on how this tests should move forward

**Comment by SergeyKanzhelev** [comment]
@cheftako do you know if there is already an image available?

**Comment by adisky** [comment]
cc @andrewsykim

**Comment by ndixita** [comment]
Assigning it to myself as I will be looking into the logistics to add the e2e tests here

**Comment by ruiwen-zhao** [comment]
@ndixita is actively working on this.

/reopen

**Comment by ruiwen-zhao** [comment]
@ndixita is actively working on this in https://github.com/kubernetes/kubernetes/pull/111495

/reopen

**Comment by spiffxp** [comment]
/remove-lifecycle rotten
per https://github.com/kubernetes/kubernetes/issues/106248#issuecomment-1222588953

**Comment by andrewsykim** [comment]
I think we can just close this, we now have both node e2e and standard e2e for this feature, thanks to @ndixita! 

/close
