### ISSUE TITLE
Test Failure: Conformance test to validate there is no conflict between pods with same hostPort but different hostIP and protocol

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#106264]
### What happened?

The below test is failing in our daily conformance runs that test the suite against the latest k8s cluster:
`Test that validates that there is no conflict between pods with same hostPort but different hostIP and protocol`
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/hostport.go#L61

Please look at https://k8s-testgrid.appspot.com/sig-node-ppc64le#conformance
Sample failure run https://prow.k8s.io/view/gs/ppc64le-kubernetes/logs/periodic-kubernetes-conformance-test-ppc64le/1457992350935552000

### What did you expect to happen?

The test should pass as in earlier builds.

### How can we reproduce it (as minimally and precisely as possible)?

Based on your deployer, you may focus and run the conformance test as mentioned in https://github.com/kubernetes-sigs/kubetest2#usage

### Kubernetes version
Started failing from K8s Build version : `v1.23.0-alpha.4.185+97125e76f3a7a3`

### Cloud provider
We observed this on k8s cluster that is on PowerVS (IBM)

### OS version
CentOS 8.4
Architecture: ppc64le

**Comment by Rajalakshmi-Girish** [comment]
@mkumatag ^^

**Comment by aojea** [comment]
/remove triage-accepted

The failure seems related to the environment, the same test is working perfectly in other jobs
https://k8s-testgrid.appspot.com/sig-release-master-blocking#conformance-ga-only&include-filter-by-regex=HostPort

The failure is because one of the pods on the test fail to run

```
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
ï¿½[1mSTEPï¿½[0m: Trying to create a pod(pod1) with hostport 54323 and hostIP 127.0.0.1 and expect scheduled
Nov  9 09:29:08.417: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
Nov  9 09:29:10.501: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
Nov  9 09:29:12.500: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
Nov  9 09:29:14.500: INFO: The status of Pod pod1 is Failed which is unexpected
Nov  9 09:29:14.501: FAIL: wait for pod pod1 timeout, err:pod ran to completion
```

I couldn't find the config of the job, but I suggest to check the difference in the configuration job before it started to fail

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> /remove triage-accepted
> 
> The failure seems related to the environment, the same test is working perfectly in other jobs https://k8s-testgrid.appspot.com/sig-release-master-blocking#conformance-ga-only&include-filter-by-regex=HostPort
> 
> The failure is because one of the pods on the test fail to run
> 
> ```
>   /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
> ï¿½[1mSTEPï¿½[0m: Trying to create a pod(pod1) with hostport 54323 and hostIP 127.0.0.1 and expect scheduled
> Nov  9 09:29:08.417: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
> Nov  9 09:29:10.501: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
> Nov  9 09:29:12.500: INFO: The status of Pod pod1 is Pending, waiting for it to be Running (with Ready = true)
> Nov  9 09:29:14.500: INFO: The status of Pod pod1 is Failed which is unexpected
> Nov  9 09:29:14.501: FAIL: wait for pod pod1 timeout, err:pod ran to completion
> ```
> 
> I couldn't find the config of the job, but I suggest to check the difference in the configuration job before it started to fail

Here is the config of the job that failed. https://prow.ppc64le-cloud.org/prowjob?prowjob=fd3eba42-41b6-11ec-bceb-ce3d5cc4486c
There was no change made to the job's configuration before it started to fail.
`kubetest2-tester-ginkgo` is used to run these tests. I am yet to reproduce this manually apart from the consistent failure in the prow jobs!

**Comment by aojea** [comment]
the test fails because the pod readiness fail, it will be nice to have logs from the kubernetes daemons to understand the root cause
```
[AfterEach] [sig-network] HostPort
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:186
[1mSTEP[0m: Collecting events from namespace "hostport-834".
[1mSTEP[0m: Found 6 events.
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:07 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Pulled: Container image "k8s.gcr.io/e2e-test-images/agnhost:2.33" already present on machine
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:07 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Created: Created container agnhost
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:07 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Started: Started container agnhost
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:08 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Unhealthy: Readiness probe failed: Get "http://172.20.26.124:8080/hostname": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:10 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Unhealthy: Readiness probe failed: Get "http://172.20.26.124:8080/hostname": dial tcp 172.20.26.124:8080: i/o timeout (Client.Timeout exceeded while awaiting headers)
Nov  9 09:29:06.160: INFO: At 2021-11-09 09:24:25 +0000 UTC - event for pod1: {kubelet config1-1636447526-master} Unhealthy: Readiness probe failed: Get "http://172.20.26.124:8080/hostname": dial tcp 172.20.26.124:8080: connect: invalid argument
Nov  9 09:29:06.243: INFO: POD   NODE                       PHASE    GRACE  CONDITIONS
Nov  9 09:29:06.243: INFO: pod1  config1-1636447526-master  Running         [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2021-11-09 09:24:05 +0000 UTC  } {Ready False 0001-01-01 00:00:00 +0000 UTC 2021-11-09 09:24:05 +0000 UTC ContainersNotReady containers with unready status: [agnhost]} {ContainersReady False 0001-01-01 00:00:00 +0000 UTC 2021-11-09 09:24:05 +0000 UTC ContainersNotReady containers with unready status: [agnhost]} {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2021-11-09 09:24:05 +0000 UTC  }]
Nov  9 09:29:06.243: INFO: 
Nov  9 09:29:06.326: INFO: 
```

however, this setup seems to have only one node, AFAIK conformance clusters require at least 1 control-plane and 2 workers

/cc @amwat @BenTheElder

**Comment by aojea** [comment]
@Rajalakshmi-Girish is this possible to get more logs from the job? kubelet, apiserver and containerd/or the CRI used

**Comment by BenTheElder** [comment]
This test cluster appears to have a single node. It is not a valid candidate for conformance testing.

https://github.com/kubernetes/kubernetes/issues/106303#issuecomment-965608855

https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ

> '--focus-regex=\[Conformance\]' '--skip-regex=\[Disruptive\]|\[Serial\]'

This is not conformance, conformance must have no skips. Please rename the job or remove the skip.

---

FYI you are uploading the kubectl binary in ARTIFACTS which is probably unintentional and wasting a lot of storage? 🙃

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> @Rajalakshmi-Girish is this possible to get more logs from the job? kubelet, apiserver and containerd/or the CRI used

Those clusters usually tear down after the tests run. I am afraid I don't have those logs at the moment.
I would like to reiterate that this test has been passing all this while in spite of the cluster being a single node! Not sure what change is causing a failure now.

**Comment by Rajalakshmi-Girish** [comment]
> 
> 
> This test cluster appears to have a single node. It is not a valid candidate for conformance testing.
> 
> [#106303 (comment)](https://github.com/kubernetes/kubernetes/issues/106303#issuecomment-965608855)
> 
> https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ
> 
> From the job logs:
> 
> > '--focus-regex=[Conformance]' '--skip-regex=[Disruptive]|[Serial]'
> 
> This is not conformance, conformance must have no skips. Please rename the job or remove the skip.
> 
> FYI you are uploading the kubectl binary in ARTIFACTS which is probably unintentional and wasting a lot of storage? 🙃

@mkumatag^^ 🙂

**Comment by BenTheElder** [comment]
The metadata reported by the job is a bit wrong (it has version tags instead of commits) but thankfully the runs tend to have a commit within that data so I can tell you it is in https://github.com/kubernetes/kubernetes/compare/582c4ebe267020...731dc8cf741e2f according to the results (you can drag between results in testgrid and get this link normally, but the link generated by this job requires manually fixing due to the metadata issue).

but I'm still not sure members of the project are likely to spend time debugging conformance failures on a non-conformant cluster in external CI that is passing on all our upstream CI. 

e.g. see:
https://testgrid.k8s.io/conformance-gce#Conformance%20-%20GCE%20-%20master%20-%20kubetest2&width=5
https://testgrid.k8s.io/conformance-kind#conformance,%20master%20(dev)&width=5

**Comment by mkumatag** [comment]
> This test cluster appears to have a single node. It is not a valid candidate for conformance testing.
> 
> https://github.com/kubernetes/kubernetes/issues/106303#issuecomment-965608855
> 
> https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ
> 
> From the job logs:
> 
> > '--focus-regex=\[Conformance\]' '--skip-regex=\[Disruptive\]|\[Serial\]'
> 
> This is not conformance, conformance must have no skips. Please rename the job or remove the skip.
> 
> ---
> 
> FYI you are uploading the kubectl binary in ARTIFACTS which is probably unintentional and wasting a lot of storage? 🙃 

Thanks for the feedback, will fix these comments...

**Comment by Rajalakshmi-Girish** [comment]
This might be a regression:
Reference: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#failing-test-3
https://github.com/kubernetes/kubernetes/issues/98648

**Comment by aojea** [comment]
it is not a regression https://github.com/kubernetes/kubernetes/issues/106264#issuecomment-964207939

**Comment by Rajalakshmi-Girish** [comment]
Yes seems to be an issue with Calico v3.21.0.
Have raised https://github.com/projectcalico/calico/issues/5089
@mkumatag ^^

**Comment by Rajalakshmi-Girish** [comment]
> This test cluster appears to have a single node. It is not a valid candidate for conformance testing.
> 
> [#106303 (comment)](https://github.com/kubernetes/kubernetes/issues/106303#issuecomment-965608855)
> 
> https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ
> 
> From the job logs:
> 
> > '--focus-regex=[Conformance]' '--skip-regex=[Disruptive]|[Serial]'
> 
> This is not conformance, conformance must have no skips. Please rename the job or remove the skip.
> 
> FYI you are uploading the kubectl binary in ARTIFACTS which is probably unintentional and wasting a lot of storage? 🙃

@BenTheElder The job listed in dashboard https://k8s-testgrid.appspot.com/conformance-hack-local-up-cluster seems to skip Serial tests. Just letting you know :)
