### ISSUE TITLE
structured logging: helper struct for formatting an object

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#106258]
### What would you like to be added?

Something like this could be made available in klog, logr or a Kubernetes helper package (TBD):
```
// LogAs implements both the string.Stringer and logr.Marshal interface with
// some custom functions. It can be used to implement a custom formatter for
// some kind of object entirely with inline functions.
type LogAs struct {
	Text: func() string
	Object: func() interface{}
}

func (l LogAs) String() string { return l.Text() }
func (l LogAs) MarshalLog() interface() { return l.Object() }

var _ string.Stringer = LogAs{}
var _ logr.Marshaler = LogAs{}
```

### Why is this needed?

We had some cases now where we needed a custom formatter. Always writing the same boilerplate code is annoying and distracts from the actual change.

**Comment by NikhilSharmaWe** [comment]
Looking forward to how you will proceed in this issue, please inform if I can collaborate in any way.

**Comment by shivanshu1333** [comment]
Linking similar issue solving formatting specific to `pod/s` and `node/s` https://github.com/kubernetes/kubernetes/issues/106276
Solving this one will provide a solution for the mentioned issue also, in that case we may need to close it

**Comment by pohly** [comment]
First draft implementation is available: https://github.com/kubernetes/klog/pull/269

**Comment by pohly** [comment]
/close

The conclusion of the code review of https://github.com/kubernetes/klog/pull/269 was that such helper functions would not be useful enough to justify the extra complexity.

We also concluded that different formatting depending on the output format (text and struct) may often not be necessary. Unless it is known that the developer or users expect a struct in JSON, let's just stick with dumping a (potentially multi-line) text.

Such text can be prepared locally with:
```
if klogV := klog.V(<level>); klogV.Enabled() {
    <prepare text>
    klogV.InfoS("here's some text", "text", text)
}
```

/close
