### ISSUE TITLE
is it possible to let kubelet build symlinks for Pods which use log file from persistent volume? 

### ISSUE THREAD

**Issue by zhanghe9702** [kubernetes/kubernetes#106222]
### What happened?

in our k8s clusters,  some pods direct logs to files in mounted pv, not stdout/stderr, we have deploy an DaemonSet(fluentbit) as log collector, but can't collect log info from these pods( others works normal), because fluentbit collect log files from stand container runtime log path like "/var/log/containers/...", now kubelet has build the symlink for stdout/stderr, so i want to know, is it possible for kubelet to build symlinks for these special pods( maybe need add fields in VolumeMount go type)

(we have tried sidecar solution, but use sidecar we need restart Deployment/DaemonSet , interrupt the application workload,  in our environment, not acceptable.)

### What did you expect to happen?

kubelet build an symlink for file in PV `varlog` like that
`
counter_default_count-1fd94bec8e4959b39ffd12737e4b353c81065ba0d33fccfa43573665e063b1ebfile_in_volume_valog.log
`

### How can we reproduce it (as minimally and precisely as possible)?

use the sidecar example in 

1. https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/admin/logging/two-files-counter-pod.yaml

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.3.249+80056f73a614b2", GitCommit:"80056f73a614b21c7d2165d65f3b74a2fbf2264e", GitTreeState:"clean", BuildDate:"2021-10-09T03:53:29Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>
bear metal machine.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux node2 5.8.0-63-generic #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
kubelet maybe not know which log files your app would write in pod volume path, actually all the app log files exists on /var/lib/kubelet/pods/{podUID}/volumes, you can access these paths to get app logs written in mounted volumes, or create a symlink to the paths in "/var/log/containers/..."

**Comment by zhanghe9702** [comment]
so is it possible to let kubelet know which file in a volume should build symlink?

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/remove-kind bug
/kind support
/close
