### ISSUE TITLE
I cannot access to pods' ip adress scheduled to a new minion added to cluster ubuntu

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/kubernetes#10621]
@WIZARD-CXY 
When adding new node to kubernetes cluster on ubuntu, I cannot access to new pods in this new minion with their ip adress.

**Comment by WIZARD-CXY** [comment]
Did you configure the flannel network?

May the force be with you

**Comment by medhedifour** [comment]
Initially I configured flannel in the new node
but after adding this new minion to cluster, flannel is falling down

**Comment by medhedifour** [comment]
@WIZARD-CXY 
Initially I configured flannel in the new node
but after adding this new minion to cluster, flannel is falling down

**Comment by WIZARD-CXY** [comment]
how do you configured?It is a bit tricky

May the force be with you

**Comment by medhedifour** [comment]
I executed : etcdctl mk /coreos.com/network/config ' {"Network":"10.0.0.0/16"}'
and I started service flanneld

**Comment by WIZARD-CXY** [comment]
Your configurations are wrong.
First, you need to add to the existing etcd cluster, the /coreos.com/network/config key exists, no need to set it again.
Second, docker bridge ip is getting from a file from flannel daemon , it is not the 10.0.0.0/16 in your case.
I understand It is a little hard for you to add a new node to the cluster.Now is 11:30 pm in China. I will figure it out tomorrow and tell you.Don't worry.

**Comment by medhedifour** [comment]
@WIZARD-CXY 
Ok 
Thanks

**Comment by WIZARD-CXY** [comment]
Have you get it done?
1 First solution is simple, if you do not have some important thing running, just tear down the old cluster and add the new node in configure-defaul.sh and run kube-up.sh. 
2 make the new node's etcd join into the old etcd cluster.It is very tricky though
I recommend you use the first approach.

**Comment by zmerlynn** [comment]
Thanks for your help, @WIZARD-CXY!

**Comment by medhedifour** [comment]
I didn't get it done yet.
For the first solution, it's easy to do, but I will lose many things ( pods, rc, services ...)
I will try the second solution.
Can you give some principal points to make the new node's etcd join the old etcd cluster ?

**Comment by WIZARD-CXY** [comment]
OK, follow this guide to add the new node to the existing etcd cluster.Be careful
https://github.com/coreos/etcd/blob/master/Documentation/runtime-configuration.md#add-a-new-member
then start flanneld and reconf docker bridge.

May the force be with you.

**Comment by medhedifour** [comment]
@WIZARD-CXY 
Thanks a lot.
