### ISSUE TITLE
[kubectl] copy non existent source in container returns zero return code

### ISSUE THREAD

**Issue by nictownsend** [kubernetes/kubernetes#106312]
### What happened?

`kubectl cp <container>:file.tgz file.tgz` results in:

```
tar: file.tgz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```
`rc=0`

### What did you expect to happen?

`rc>0`

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl` copy non existent file from container to local

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bafe72f", GitCommit:"bafe72fb05eddc8246040b9945ec242b9f805935", GitTreeState:"clean", BuildDate:"2021-03-14T16:01:39Z", GoVersion:"go1.15.7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Redhat Openshift

**Comment by jlsong01** [comment]
I signed it

**Comment by eddiezane** [comment]
There is an effort in progress to normalize the exit codes across the board.

It might need a new champion to take over from @rikatz.

https://github.com/kubernetes/enhancements/pull/2574

**Comment by rikatz** [comment]
yes please!
I really want to work on this, but I'm almost out of time :/

Anybody wants to jump into it? I can help on the KEP thing + implementation ideas, just cannot shepherd too much :/

**Comment by nictownsend** [comment]
Closing as captured in the enhancement issue above
