### ISSUE TITLE
Scheduler will run into race conditions on large scale clusters

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#106361]
### What happened?

The scheduler has a [30s timeout](https://github.com/kubernetes/kubernetes/blob/0fefe4e605ba05793e919598c09390769c127b3c/pkg/scheduler/scheduler.go#L231) for the bind operation to succeed; if we don't get a response within 30s, the in-memory assignment of pod to node in the [scheduler cache expires](https://github.com/kubernetes/kubernetes/blob/0fefe4e605ba05793e919598c09390769c127b3c/pkg/scheduler/internal/cache/cache.go#L720).

A race condition will happen in the follow case:

1. pod1 is assigned to a node, scheduler cache is updated with the assignment, bind operation issued to apiserver.

1. if the apiserver is under huge pressure, bind takes more than 30s, scheduler expires the cached pod-to-node assignment.

1. bind eventually succeeds, but because the apiserver is under huge pressure, the pod update with the node name takes a long time to propagate to the scheduler.

1. because the pod update took a long time to propagate and the cache entry expired, the scheduler is not aware that the assignment actually happened, and so it had no problem assigning a second pod to the same node that would otherwise not fit if the scheduler was aware that the first pod was eventually assigned to the node.

On the scheduler side, what we need to do is make the 30s longer for large clusters, and ideally adaptable to cluster state.

/sig scheduling

### What did you expect to happen?

No race conditions.

### How can we reproduce it (as minimally and precisely as possible)?

Create a large scale cluster.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
IIRC, the 30s timeout only starts running after we receive a 200 response for the binding. But yes, if it takes longer than 30s to receive the update, we would invalidate the cache.

I don't know if there is particular reason to invalidate the cache at all. I suppose it was meant to guard against missing Pod deletion events. We need to improve that regardless.

I would be in favor of dropping the timeout altogether.

**Comment by ahg-g** [comment]
ok, so the deadline is effectively for receiving the update.

Perhaps making it longer, like 15min, is good first step before completely removing it just so we can easily revert in case something else goes wrong.

**Comment by ahg-g** [comment]
I sent #106412 to increase the timeout to 15min. We should backport this.

**Comment by wojtek-t** [comment]
> I don't know if there is particular reason to invalidate the cache at all. I suppose it was meant to guard against missing Pod deletion events. We need to improve that regardless.

We should double check the history, but I think that in the past we were:
- asynchronously sending bind request
- updating the cache before sending the request
and then the timeout was actually protecting us from the binding request actually not succeeding.

So I agree with Aldo - that we should double check if this timeout is at all needed currently.

**Comment by alculquicondor** [comment]
We are probably good to remove this timeout altogether at this point.

/remove-lifecycle stale

**Comment by fabianberisha** [comment]
> Plz assign to yourself to notify that you"re working on this.

done. thanks!

**Comment by kapiljain1989** [comment]
@alculquicondor Could you please guide for this Issue
are you suggesting we should not check cache before assigning the pod and need other way around?

**Comment by alculquicondor** [comment]
FTR, I'm considering @kapiljain1989 assigned to this issue, as they were the first to get assigned.

You can see that in #106412 we increased the timeout. We want to get rid of the timeout. Then, we can just get rid of the logic that uses the timeout to remove some pods from the cache.

**Comment by alculquicondor** [comment]
/reopen

We still need to remove the code in 1.27

**Comment by alculquicondor** [comment]
one more release before we can remove this code.

**Comment by anson627** [comment]
do you have plan to cherry pick for previous versions, e.g 2.13, 2.14?

**Comment by alculquicondor** [comment]
did you mean 1.13 and 1.14?

**Comment by anson627** [comment]
oh, sorry my bad, I meant for 1.23 and 1.24

**Comment by alculquicondor** [comment]
It is fixed in 1.23 https://github.com/kubernetes/kubernetes/pull/106412, so it would be fixed in 1.24 too.

**Comment by anson627** [comment]
my understanding is the previous fix to increase the duration only reduce the chance of issue, but not completely avoid it, right?

that's why the other 2 fixes https://github.com/kubernetes/kubernetes/pull/110925 and https://github.com/kubernetes/kubernetes/pull/110954 are needed, right?

**Comment by emiljanogj** [comment]
Hi, this issue still available?

**Comment by alculquicondor** [comment]
@anson627 yes, but since the likelihood that an issue happens is very low, I don't think it's worth the risk of cherry-picking at this point.

**Comment by alculquicondor** [comment]
According to https://github.com/kubernetes/kubernetes/pull/110925#issuecomment-1174053205, we can remove the TTL code entirely in 1.27

I'll give the chance to @kapiljain1989 to confirm if they can still do this.

In the meantime:
/unassign @fabianberisha
/unassign @zabrox 
/remove-help

**Comment by alculquicondor** [comment]
/remove-lifecycle stale
/unassign @kapiljain1989 
as we haven't heard from them.

**Comment by wackxu** [comment]
I want to help fix this
/assign

**Comment by alculquicondor** [comment]
Thanks. What is left is to remove the timeout logic altogether.

**Comment by chengjoey** [comment]
/reopen 
remove the expire logic

**Comment by alculquicondor** [comment]
I think we can leave this closed.
Entirely removing the timeouts has proven to be close to impossible without introducing regressions.

We might need a few more iterations. Maybe we can reconsider when scheduling hints graduates to Stable.

**Comment by dom4ha** [comment]
@kerthcet @sanposhiho @macsko 

I could not find any discussion why removing the code might introduce regression. Obviously we need to make sure that sending the API call cannot eventually be skipped (in case of a failure or timeout), but the ttl is currently 0 anyway.

One thing we need to remember is the fact that the scheduler failover after the bind API call was sent may trigger the same issue like cache expiration, but it's rather an independent issue that we will solve separately.
