### ISSUE TITLE
Node e2e tests panics trying to set KubeletConfig

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#106377]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Which tests are flaking?

Seen in this job failing on multiple tests, this is just one of the stack traces

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106371/pull-kubernetes-node-kubelet-serial/1459076579521990656/

```
E2eNode Suite: [sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring] when we run containers that should cause use quotas for LSCI monitoring (quotas enabled: false) should eventually evict all of the correct pods expand_less | 11s
-- | --
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:165 Test Panicked /usr/local/go/src/runtime/map_faststr.go:204  Panic: assignment to entry in nil map  Full stack: k8s.io/kubernetes/test/e2e_node.runOneQuotaTest.func1.1(0xc00003d400) 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/quota_lsci_test.go:69 +0x133 k8s.io/kubernetes/test/e2e_node.tempSetCurrentKubeletConfig.func1() 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:171 +0xc3 k8s.io/kubernetes/test/e2e_node.TestE2eNode(0x409659) 	_output/local/go/src/k8s.io/kubernetes/test/e2e_node/e2e_node_suite_test.go:187 +0x765 testing.tRunner(0xc00012f6c0, 0x55f10c0) 	/usr/local/go/src/testing/testing.go:1259 +0x102 created by testing.(*T).Run 	/usr/local/go/src/testing/testing.go:1306 +0x35a

```

### Since when has it been flaking?

it seems that for a long time :smile: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial&width=5

### Reason for failure (if possible)

it panics here https://github.com/kubernetes/kubernetes/blob/c98b388a847f84019609f6422b4ab00b89c4603c/test/e2e_node/util.go#L171

I don't have a good understanding of those tests mechanics, but it seems a complex setup embedding functions and goroutines before the test setup, I suggest to move to something more simple 

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
ping @pacoxu @ehashman 

I don't have time for working on this unfortunately but happy to help on reviews, this can also be a good task for new contributors, also I don't consider a bad idea to rework the tests a bit to make them easier to read and simpler, I did that for sig-network and we have a pretty low flake rate since then

**Comment by ehashman** [comment]
/assign @cynepco3hahue 
/cc @endocrimes 

This probably came out of https://github.com/kubernetes/kubernetes/pull/106210

/triage accepted

**Comment by endocrimes** [comment]
Ooops - I'm assuming it's going through one of the paths where Features or whatever isn't initialized.
