### ISSUE TITLE
kubelet por-forward bugs for IPv6 support when using Istio's command line tool in Kubernetes cluster

### ISSUE THREAD

**Issue by zhlsunshine** [kubernetes/kubernetes#106345]
### What happened?

This issue relates to the [issue](https://github.com/istio/istio/issues/35177) , I check the log of kubelet and get the error output as below:
```
Nov 11 17:12:55 zhlsunshine kubelet[9844]: E1111 17:12:55.269450    9844 httpstream.go:255] error forwarding port 15000 to pod 00ae38b9f99f54d7718eef988f6ed49c50be96e41dbed7c2483ef9beb3849e40, uid : exit status 1: 2021/11/11 17:12:55 socat[11208] E connect(5, AF=2 127.0.0.1:15000, 16): Connection refused
```
Then I go on my investigation, and I find that [here](https://github.com/kubernetes/kubernetes/blob/d9f06f9e1807c804678fe201640ccc2a820d1efb/pkg/kubelet/dockershim/docker_streaming_others.go#L48) may be the right place which raises this error message. `kubelet` should support IPv6, and it's not a good idea to use `socat` to do such port-forward either, similar like containerd's  two PRs ([don't use socat for port forwarding](https://github.com/containerd/containerd/commit/11a78d9d0f1664466fa3fffebd8ff234f3ef2677) and [use happy-eyeballs for port-forwarding](https://github.com/containerd/containerd/commit/305b42583073aa1435d15ff5773c049827fa8d51)) which fixed a number of issues in IPv6 port-forwarding.

NOTE:  **My cluster is IPv6 only k8s cluster.**

### What did you expect to happen?

I think kubele should support IPv6 only k8s cluster if it can do port-forward

### How can we reproduce it (as minimally and precisely as possible)?

Just reproduce it according to the issue and make sure your k8s cluster is IPv6 only

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
This is not a kubelet issue, is a CRI issue, is the problem that you are using dockershim?

Both containerd and crio doesn't use socat, only dockershim, and dockershim was deprecated in Kubernetes, the code is still there but I think that will be removed soon IIRC

**Comment by zhlsunshine** [comment]
okay, thanks @aojea , I will try it and hope it can be removed quickly

**Comment by aojea** [comment]
> okay, thanks @aojea , I will try it and hope it can be removed quickly

just to clarify, is not a kubernetes problem, is an user choice to use dockershim, if you want to solve this problem just modify your cluster (kubelet) to use containterd or crio as CRI

**Comment by zhlsunshine** [comment]
okay, got it, I will change another container runtime. Thanks.

**Comment by aojea** [comment]
/close

let me close it, you can always reopen if necessary
