### ISSUE TITLE
Add an e2e test validating pod statuses on container state wipe

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#106390]
I changed some behaviour to be more resilient to this failure mode in https://github.com/kubernetes/kubernetes/pull/102821 but we don't have an e2e to validate it.

We should write an e2e to verify that, when the container runtime statuses are wiped (e.g. with crio-wipe on a node running CRI-O), we preserve the following behaviours:

1. Any deleted pod will never go Running -> Pending.
2. A non-daemonset API pod will never go Running -> Pending.
3. Static pods (with the same UID) are allowed to go Running -> Pending if the node rebooted.
4. If a daemonset pod doesn't have init containers, it will never go Running -> Pending.
5. Daemonset pods with init containers are allowed to go Running -> Pending if the node rebooted.

See also https://bugzilla.redhat.com/show_bug.cgi?id=1933760

/kind cleanup
/sig node
/priority important-longterm
/assign

**Comment by NikhilSharmaWe** [comment]
@ehashman I would like to work on adding this new e2e test. I have not worked on adding an e2e test before, so could you please guide me a little and inform me about how can I collaborate.

**Comment by ehashman** [comment]
Hi @NikhilSharmaWe, it is very important that this test suite is accurate and doesn't flake and I don't have time to onboard a new contributor to help with it right now, sorry.
