### ISSUE TITLE
Hugepages test fails

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#106310]
### Which jobs are failing?

kubelet-serial-gce-e2e-hugepages

### Which tests are failing?

all

### Since when has it been failing?

November 09th 2021

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-serial-gce-e2e-hugepages

### Reason for failure (if possible)

Tests fail with the same error: 'Found more than one kubelet service running'

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
it's green now. If it will re-occur we will investigate

/close
