### ISSUE TITLE
repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by sfeng1996** [kubernetes/kubernetes#106335]
### What happened?

when i deploy a application, the kubelet report an error about "repository does not exist or may require 'docker login'"，but docker pull image  succeeded on host，"imageSecret" is not configured in deployment.yaml. 

kubelet can pull image when i configure "imageSecret" in deployment.yaml.

### What did you expect to happen?

I think kubelet can pull the image as long as the docker login on the host is successful,

This document also indicates that you can select either docker login or configure "imagesecret"
https://kubernetes.io/zh/docs/concepts/containers/images/#%E9%85%8D%E7%BD%AE-node-%E5%AF%B9%E7%A7%81%E6%9C%89%E4%BB%93%E5%BA%93%E8%AE%A4%E8%AF%81

I read the kubelet code and also indicated that if deployment.yaml is not configured with "imagesecret", kubelet will read ~ /. docker/config.json of the host machine

### How can we reproduce it (as minimally and precisely as possible)?

none

### Anything else we need to know?

none

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Self built IDC
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux master-172-31-97-215 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275
 Built:             Tue Dec  1 19:14:24 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.14-sealer
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       711cc111cf
  Built:            Wed Jun  2 09:07:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
none
</details>

**Comment by sfeng1996** [comment]
> @sfeng1996: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

/sig/node

**Comment by SergeyKanzhelev** [comment]
can it be this: https://github.com/kubernetes/kubernetes/issues/69637?

does kubelet log give any clues?

**Comment by sfeng1996** [comment]
> can it be this: #69637?
> 
> does kubelet log give any clues?

this is kubelet log about " Pulling image "xxxxxxx" without credentials"

Does it mean that kubelet did not get  ~ /. Docker / config.json of the host, but the file exists in the host

**Comment by SergeyKanzhelev** [comment]
#69637 says that kubelet needs to be restarted after the `docker login` to take effect. Can you try it?

**Comment by sfeng1996** [comment]
> docker
I tried. It doesn't seem to work

root@master-172-31-97-215:~# docker logout hub.xxxxx.com
Removing login credentials for hub.iflytek.com
root@master-172-31-97-215:~# docker login hub.iflytek.com
Username: fengsun5
Password: 
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
root@master-172-31-97-215:~# 
root@master-172-31-97-215:~# systemctl restart kubelet
root@master-172-31-97-215:~# 
root@master-172-31-97-215:~# 
root@master-172-31-97-215:~# kubectl apply -f gateway.yaml 
deployment.apps/gateway created
root@master-172-31-97-215:~# kubectl get pods 
NAME                       READY   STATUS    RESTARTS   AGE
gateway-545b7fd44f-2hq48   0/1     Pending   0          6s
root@master-172-31-97-215:~# kubectl get pods 
NAME                       READY   STATUS         RESTARTS   AGE
gateway-545b7fd44f-2hq48   0/1     ErrImagePull   0          9s
root@master-172-31-97-215:~# journalctl -u kubelet -f |grep "without credentials"
11月 11 17:18:42 master-172-31-97-215 kubelet[51635]: I1111 17:18:42.601428   51635 kuberuntime_image.go:47] Pulling image "xxxxxxxxxx" without credentials
^C
root@master-172-31-97-215:~# ll ~/.docker/config.json 
-rw------- 1 root root 158 11月 11 17:17 /root/.docker/config.json

**Comment by SergeyKanzhelev** [comment]
Can you try to reproduce this on 1.21? 1.19 is out of support an 1.20 is about to get out of support. Also dockershim was deprecated as a runtime and ideally try on other runtime.

Please report back if issue persists with exact steps to repro

**Comment by sfeng1996** [comment]
> 

ok，i will try it
