### ISSUE TITLE
Are single-node clusters conformant?

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#106303]
### What happened?

I can create a cluster with one node and pass conformance, 

~there are some tests that require at least 2 nodes to run~
~`https://github.com/kubernetes/kubernetes/blob/0c6110e4120165b4485e658de6eca5d6d2d72b1a/test/e2e/common/network/networking.go#L80-L82`~

~This is because the tests Skip if they are not able to run~

~`https://github.com/kubernetes/kubernetes/blob/0c6110e4120165b4485e658de6eca5d6d2d72b1a/test/e2e/framework/network/utils.go#L774-L782`~

~As consequence, the list of tests for conformance depends on the number of nodes, a single cluster node (that is not a cluster by definition of cluster :)) will run less tests than a multi cluster node and still be Conformant~

EDIT

I have to correct myself, it seems that the conformance tests doesn't skip, the problem is: there are no conformance tests that exercise anything that requires more than one node, hence, single node cluster can pass conformance.

### What did you expect to happen?

I expect a cluster (_a group of similar things or people positioned or occurring closely together_) and a "distributed system" to not be able to be single-node.

In addition, lots of most important Kubernetes features can not be exercised on one node, lowering the quality bar.

### How can we reproduce it (as minimally and precisely as possible)?

local-up.sh pass conformance https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-local-e2e/1458332314344886272

### Anything else we need to know?

Related discussion

https://groups.google.com/g/kubernetes-sig-architecture/c/s-SCpQQDOEo/m/FUGmTFKKAQAJ

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/assign @smarterclayton @thockin @johnbelamaric  @BenTheElder  @spiffxp 

Maybe this has changed, but last time I've checked the minimum for conformance was 1 control-plane and 2 workers, if that didn't change I will submit a PR to enforce it in the suite

Regarding sig-network, with one node you can not verify the networking model, where pod to pod in different nodes should be able to communicate without NAT, that is a strong requirement ... I have to review closely what tests do we have in Conformance

**Comment by liggitt** [comment]
> it seems that the conformance tests doesn't skip, the problem is: there are no conformance tests that exercise anything that requires more than one node, hence, single node cluster can pass conformance.

that seems pretty intentional... changing the definition of conformance to require multiple nodes probably deserves more feedback than an issue/PR

**Comment by aojea** [comment]
I'm not changing the definition, just asserting it https://github.com/kubernetes/kubernetes/pull/106313

**Comment by aojea** [comment]
> that seems pretty intentional... changing the definition of conformance to require multiple nodes probably deserves more feedback than an issue/PR

if we are testing features like replicaset, daemonset, services, ..., in one node only we are missing a lot of testing on those features ... a podman/docker single node can be a kubernetes cluster ...  do I need a scheduler or network for anything, I'm just deploying always in the same node?

**Comment by BenTheElder** [comment]
> I can create a cluster with one node and pass conformance,

No I don't think so. Where are your results and configuration?

You need two schedulable nodes to pass the conformance suite.

> I have to correct myself, it seems that the conformance tests doesn't skip, the problem is: there are no conformance tests that exercise anything that requires more than one node, hence, single node cluster can pass conformance.

That's not correct, we test rolling pod behavior with replicasets. This test requires multiple nodes. There is at least one.

> How can we reproduce it (as minimally and precisely as possible)?
>
>local-up.sh pass conformance https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-local-e2e/1458332314344886272

That job is not passing conformance, from the configuration:
>       - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Serial

(see: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-local-e2e/1458332314344886272/prowjob.json)

Conformance requires not setting --ginkgo.skip, you must run all `[Conformance]` tests without skipping.

> if we are testing features like replicaset, daemonset, services, ..., in one node only we are missing a lot of testing on those features

We don't, at the very least replicaset is being tested multi-node, just not in this job that *is not* running the full conformance suite.

When conformance results are submitted they are now validated to ensure that all tests were run.
