### ISSUE TITLE
[Failing test][sig-cluster-lifecycle] kubeadm-kinder-latest-on-1-22

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#106311]
### Which jobs are failing?

kubeadm-kinder-latest-on-1-22

### Which tests are failing?

* E2EKubeadm suite.[sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role
* ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-22.Overall
* task-06-e2e-kubeadm

### Since when has it been failing?

2021-11-09 23:31 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-latest-on-1-22

### Reason for failure (if possible)

[Run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest-on-1-22/1458443045455269888): E2EKubeadm suite: [sig-cluster-lifecycle] [area-kubeadm] proxy addon kube-proxy ServiceAccount should be bound to the system:node-proxier cluster role 
```bash
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/proxy_addon_test.go:65
error getting ClusterRoleBindings "kubeadm:node-proxier"
Unexpected error:
    <*errors.StatusError | 0xc000416960>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "clusterrolebindings.rbac.authorization.k8s.io \"kubeadm:node-proxier\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kubeadm:node-proxier",
                Group: "rbac.authorization.k8s.io",
                Kind: "clusterrolebindings",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    clusterrolebindings.rbac.authorization.k8s.io "kubeadm:node-proxier" not found
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_kubeadm/util.go:136
```

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by neolit123** [comment]
/triage accepted
will have a look and send a fix if it's kubeadm related.

**Comment by neolit123** [comment]
fix PR is here, needs LGTM:
https://github.com/kubernetes/kubernetes/pull/106321
