### ISSUE TITLE
Goldengate running on kubernetes fails due to swap space issue 

### ISSUE THREAD

**Issue by 9lion** [kubernetes/kubernetes#106343]
### What happened?

we are running oracle goldengate microservices in kubernetes 1.20 and it is failing with below error. Is there a WA. OKE latest version available is 1.20.11 only 

                                        anon alloc: mmap(MAP_ANON)  anon free: munmap
                                        file alloc: mmap(MAP_SHARED)  file free: munmap
                                        target directories:
                                        /u02/Deployment/var/temp/. (main)
2021-11-11T06:39:36.905+0000 ERROR| ERROR   OGG-25715  Oracle GoldenGate Distribution Service for Oracle:  CACHEMGR: No Swap environment and parameter CONTAINER MEM_LIMIT not set. (main)

### What did you expect to happen?

goldengate should start 

### How can we reproduce it (as minimally and precisely as possible)?

yes it will not start 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"50317190d44dbdb51ae7ff430917b32ba96188b5", GitTreeState:"clean", BuildDate:"2021-06-30T14:20:31Z", GoVersion:"go1.15.13 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>

</details>
oracle OCI

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MadhavJivrajani** [comment]
/sig node
/triage needs-information
/cc @ehashman 
Since you might have more context wrt swap space usage pre-1.22

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. Please reach out to Oracle support directly for assistance with Oracle Kubernetes products.

/close
