### ISSUE TITLE
Missing metrics after switching to Cgroups v2 (need bump Cadvisor version)

### ISSUE THREAD

**Issue by judexzhu** [kubernetes/kubernetes#106393]
### What happened?

After upgrade Flatcar-Linux and switch to the cgroups v2, `kubectl top node ` shows <<unknow>>

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/17834225/141581604-49120d09-06f1-4871-9ffc-552e7db05bff.png">

### What did you expect to happen?

`kubectl top node ` shows metrics correctly

### How can we reproduce it (as minimally and precisely as possible)?

switch cgroups to v2 and check https://<<node-ip>>:10250/stats/summary\?only_cpu_and_memory\=true

```
    "cpu": {
      "time": "2021-11-12T00:33:29Z",
      "usageNanoCores": 0,
      "usageCoreNanoSeconds": 0
    },
    "memory": {
      "time": "2021-11-12T00:33:29Z",
      "availableBytes": 16785580032,
      "usageBytes": 0,
      "workingSetBytes": 0,
      "rssBytes": 0,
      "pageFaults": 0,
      "majorPageFaults": 0
```

### Anything else we need to know?

I run multiple  standalone cadvisor  with various versions and can confirmed 

That 0.39.0+ fixed the cpu metrics and the 0.41.0+ fixed the memory issue 

<img width="495" alt="image" src="https://user-images.githubusercontent.com/17834225/141593605-a34df895-2b8a-417d-9c1a-cb2849028ea0.png">

<img width="742" alt="image" src="https://user-images.githubusercontent.com/17834225/141593643-c63f379e-e253-4e24-9094-87d5bd27114d.png">

<img width="566" alt="image" src="https://user-images.githubusercontent.com/17834225/141593688-e15fab3e-eb74-4243-ba36-9e85f0dee3fa.png">

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
  Baremetal 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2983.2.0
VERSION_ID=2983.2.0
BUILD_ID=2021-11-05-1835
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2983.2.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
$ uname -a
Linux e11qk8sma03.neqdc.com 5.10.77-flatcar #1 SMP Fri Nov 5 17:49:48 -00 2021 x86_64 Common KVM processor GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
docker 20.10.10
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

#106282

**Comment by judexzhu** [comment]
https://github.com/kubernetes/kubernetes/pull/106282

**Comment by judexzhu** [comment]
#106282

**Comment by judexzhu** [comment]
May I know if the cAdvisor 0.43 will be backported to the 1.19+ kubernetes? For v1.19 is the first version to support cgroup v2

**Comment by SergeyKanzhelev** [comment]
> May I know if the cAdvisor 0.43 will be backported to the 1.19+ kubernetes? For v1.19 is the first version to support cgroup v2

We typically only cherry critical issues, see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks Also 1.19 is out of support in upstream. Also updating dependencies may not be possible on earlier versions, so unlikely 0.43 can be backported to 1.20, for example, as is. So if cAdvisor fix is needed, it will likely need to be implemented on cAdvisor earlier version tag.

How critical those metrics are? Would adopting of 1.23 be possible?

**Comment by ymmt2005** [comment]
As a workaround for older releases, we can deploy cAdvisor as a DaemonSet.
https://github.com/google/cadvisor/tree/master/deploy/kubernetes

**Comment by judexzhu** [comment]
> We typically only cherry critical issues, see: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md#what-kind-of-prs-are-good-for-cherry-picks Also 1.19 is out of support in upstream. Also updating dependencies may not be possible on earlier versions, so unlikely 0.43 can be backported to 1.20, for example, as is. So if cAdvisor fix is needed, it will likely need to be implemented on cAdvisor earlier version tag.
> 
> How critical those metrics are? Would adopting of 1.23 be possible?

It just makes `kubectl top node` output with <unknown> instead of real values, the others, Prometheus and `kubectl top pod` work fine. Our current in-production version is 1.19.xx, it might take us over 1 year to upgrade to 1.23. so if these can be backport to ealier version, it would just be perfect.

Thanks for the help

**Comment by judexzhu** [comment]
> As a workaround for older releases, we can deploy cAdvisor as a DaemonSet.
> https://github.com/google/cadvisor/tree/master/deploy/kubernetes

@ymmt2005 thank you, will this fix `kubectl top node` issue?

**Comment by timmc9104** [comment]
I’m experiencing this same issue with Kubernetes v1.20.14 after migrating to cgroup v2 in anticipation for v1.21.0+.

Will this issue be resolved after I upgrade to v1.21.0+?

**Comment by timmc9104** [comment]
> As a workaround for older releases, we can deploy cAdvisor as a DaemonSet.
> https://github.com/google/cadvisor/tree/master/deploy/kubernetes

How does this work with cAdvisor being built into the kubelet?

**Comment by bobbypage** [comment]
> I’m experiencing this same issue with Kubernetes v1.20.14 after migrating to cgroup v2 in anticipation for v1.21.0+.
> 
> Will this issue be resolved after I upgrade to v1.21.0+?

Please upgrade to v1.23.0+ which includes cAdvisor v0.43 which has cgroupv2 fixes. We don't plan to backport cAdvisor v0.43 to older k8s versions as mentioned in  https://github.com/kubernetes/kubernetes/issues/106393#issuecomment-974549417

**Comment by ymmt2005** [comment]
@judexzhu 
> thank you, will this fix kubectl top node issue?

At least on my side, `kubectl top node` is working.

@timmc9104 
> How does this work with cAdvisor being built into the kubelet?

cAdvisor w/ DamonSet is independent of cAdvisor embedded in kubelet.
So, you have to collect metrics from the DaemonSet Pods rather than kubelet to Prometheus,
and use [prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter) to
provide the metrics as [resource metrics](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/resource-metrics-api.md).

**Comment by ymmt2005** [comment]
@bobbypage 
FYI, cAdvisor v0.43 still has [a bug regarding cgroup v2](https://github.com/google/cadvisor/issues/3026).
We have sent a pull request to fix that (not merged yet) and are running a patched cAdvisor with a DaemonSet.

**Comment by timmc9104** [comment]
> 

@ymmt2005 My main concern is the metrics server as it is required for hpa, scheduler, and kubectl top.

My understanding is that the kubelet feeds the metrics server with the data it pulls using the kubelet’s embedded cAdvisor package. Which means the data must be available to the Kubelet in order for it to be available to the metrics server.

How does the cAdvisor w/DaemonSet fit in this architecture to push its metrics to the metrics server?

**Comment by ymmt2005** [comment]
@timmc9104 
I don't know if metrics-server can collect metrics directly from cAdvisor.
Please ask it elsewhere, sorry.

**Comment by bobbypage** [comment]
Please use the latest version of cAdvisor (https://github.com/google/cadvisor/releases/tag/v0.44.0) which also includes fix for process metrics - https://github.com/google/cadvisor/pull/3030

**Comment by judexzhu** [comment]
@bobbypage Thank you, we're still working on our Kubernetes cluster upgrade progress, now it has been upgrade to 1.21, we decided to delay cgroup V2 adoption for it will causing old java problem performance issue(fixed on OpenJDK 15+).

Anyway, it's fine to me to close this issue right now

Thanks so much again for everthing!

**Comment by SaxyPandaBear** [comment]
@bobbypage v0.44.0 is still in "pre-release". Any idea when it would be classified as a stable release to upgrade to, or do you already deem it safe enough for people to bump up to now?

**Comment by mariida** [comment]
> performance issue

Can you provide a detailed description of the impact, as we are also in the process of migration? @judexzhu
