### ISSUE TITLE
[sig-node] Summary API [NodeConformance]  test flakes for systemd + crio node e2e jobs 

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#106367]
### Which jobs are flaking?

ci-crio-cgroupv2-node-e2e-conformance
ci-crio-cgroupv1-node-e2e-conformance

### Which tests are flaking?

[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api

### Since when has it been flaking?

From about a month (or more)

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv2-node-e2e-conformance
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-conformance

### Reason for failure (if possible)

Although both cgroups v1 and cgroups v2 jobs are flaking, cgroupvs 2 job flakes way more. Not sure if the reason for flaking for both the jobs is same or not. 

### Relevant SIG(s)

/sig node

**Comment by ehashman** [comment]
potentially related: https://github.com/kubernetes/kubernetes/issues/104292

**Comment by ehashman** [comment]
/triage accepted
flake confirmed, although I feel like this is a dupe... trying to find the previous bugs

**Comment by ehashman** [comment]
Previous flake issue: https://github.com/kubernetes/kubernetes/issues/100788

**Comment by SergeyKanzhelev** [comment]
/assign @ehashman 

to update the status

**Comment by ehashman** [comment]
This test no longer appears to be flaking on either job. I think this issue can be closed.

/close
