### ISSUE TITLE
kubernetes v1.23.0-alpha.4 deployment fail 

### ISSUE THREAD

**Issue by 1998729** [kubernetes/kubernetes#106378]
### What happened?

Hi brothers, I currently use the latest beat version to deploy a kubernetes cluster, but there are some unexpected situations。

 - /usr/local/bin/kube-apiserver
        - --enable-admission-plugins=Priority,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
        - --bind-address=172.29.36.28
        - --advertise-address=172.29.36.28
        - --authorization-mode=Node,RBAC
        - --kubelet-client-certificate=/data/kubernetes/ssl/admin.pem
        - --kubelet-client-key=/data/kubernetes/ssl/admin-key.pem
        - --anonymous-auth=false
        - --service-cluster-ip-range=10.68.0.0/16
        - --tls-cert-file=/data/kubernetes/ssl/kubernetes.pem
        - --tls-private-key-file=/data/kubernetes/ssl/kubernetes-key.pem
        - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
        - --client-ca-file=/data/kubernetes/ssl/ca.pem
        - --service-account-key-file=/data/kubernetes/ssl/ca-key.pem
        - --etcd-cafile=/data/kubernetes/ssl/ca.pem
        - --etcd-certfile=/data/kubernetes/ssl/kubernetes.pem
        - --etcd-keyfile=/data/kubernetes/ssl/kubernetes-key.pem
        - --etcd-servers=https://172.29.36.28:2379,https://172.29.36.73:2379,https://172.29.37.157:2379
        - --endpoint-reconciler-type=lease
        - --allow-privileged=true
        - --audit-log-maxage=30
        - --audit-log-maxbackup=3
        - --audit-log-maxsize=100
        - --audit-log-path=/data/kubernetes/audit.log
        - --event-ttl=1h
        - --requestheader-client-ca-file=/data/kubernetes/ssl/ca.pem
        - --requestheader-allowed-names=
        - --requestheader-extra-headers-prefix=X-Remote-Extra-
        - --requestheader-group-headers=X-Remote-Group
        - --requestheader-username-headers=X-Remote-User
        - --proxy-client-cert-file=/data/kubernetes/ssl/aggregator-proxy.pem
        - --proxy-client-key-file=/data/kubernetes/ssl/aggregator-proxy-key.pem
        - --enable-aggregator-routing=true
        - --runtime-config=api/all=true
        - --service-account-key-file=/data/kubernetes/ssl/service-account.pem
        - --service-account-signing-key-file=/data/kubernetes/ssl/service-account-key.pem
        - --service-account-issuer=https://172.29.36.28:6443/auth/realms/master/.well-known/openid-configuration
        - --v=4

# response log
kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2167 +0x78\ncreated by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1897 +0x510\n" addedInfo="\nlogging error output: \"{\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Timeout: request did not complete within the allotted timeout\\\",\\\"reason\\\":\\\"Timeout\\\",\\\"details\\\":{},\\\"code\\\":504}\\n\"\n"
{"level":"warn","ts":"2021-11-12T10:05:05.573Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0021f9880/#initially=[https://172.29.36.28:2379;https://172.29.36.73:2379;https://172.29.37.157:2379]","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1112 10:05:05.573552       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E1112 10:05:05.573626       1 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
E1112 10:05:05.574747       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1112 10:05:05.575827       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1112 10:05:05.576958       1 timeout.go:137] post-timeout activity - time-elapsed: 4.374676ms, GET "/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/172.29.36.73" result: <nil>

### What did you expect to happen?

normal api-server, controller-manager, api-server should be running normally

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2167 +0x78\ncreated by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders\n\t/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1897 +0x510\n" addedInfo="\nlogging error output: \"{\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Timeout: request did not complete within the allotted timeout\\\",\\\"reason\\\":\\\"Timeout\\\",\\\"details\\\":{},\\\"code\\\":504}\\n\"\n"
{"level":"warn","ts":"2021-11-12T10:05:05.573Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc0021f9880/#initially=[https://172.29.36.28:2379;https://172.29.36.73:2379;https://172.29.37.157:2379]","attempt":0,"error":"rpc error: code = Canceled desc = context canceled"}
E1112 10:05:05.573552       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}: context canceled
E1112 10:05:05.573626       1 writers.go:117] apiserver was unable to write a JSON response: http: Handler timeout
E1112 10:05:05.574747       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"http: Handler timeout"}: http: Handler timeout
E1112 10:05:05.575827       1 writers.go:130] apiserver was unable to write a fallback JSON response: http: Handler timeout
E1112 10:05:05.576958       1 timeout.go:137] post-timeout activity - time-elapsed: 4.374676ms, GET "/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/172.29.36.73" result: <nil>

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/88186802/141449428-3c1e0588-4b2b-42c0-991c-31b43212aa22.png)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.0-alpha.4.254+0c6110e4120165", GitCommit:"0c6110e4120165b4485e658de6eca5d6d2d72b1a", GitTreeState:"clean", BuildDate:"2021-11-10T11:06:02Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: read tcp 127.0.0.1:33424->127.0.0.1:8443: read: connection reset by peer
```

</details>

### Cloud provider

<details>

</details>

### OS version

CentOS Linux release 7.9.2009 (Core)

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

docker version
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:44:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:43:13 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 1998729** [comment]
sorry kube-api config etcd cert write error, todo close issue

**Comment by ehashman** [comment]
/triage needs-information

Can you please provide the missing required information on your cloud provider and installation tools?
