### ISSUE TITLE
Kubectl calls a Kind a "Resource"

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10630]
kubectl help strings say "RESOURCE", but resource means the thing itself, not its type.
According to docs/api-conventions.md, we call the type of the thing the "kind".  So the help strings should change to "KIND".

example:

```
$ kubectl help get
...
Usage: 
  kubectl get [(-o|--output=)json|yaml|template|...] (RESOURCE [NAME] | RESOURCE/NAME ...) [flags]
```

should read:

```
$ kubectl help get
...
Usage: 
  kubectl get [(-o|--output=)json|yaml|template|...] (KIND [NAME] | KIND/NAME ...) [flags]
```

**Comment by bgrant0607** [comment]
The code is confused about whether it's a kind or resource, as well. Since kubectl accepts lowercase plurals, they do look more like resources (partially qualified).
```
func expandResourceShortcut(resource string) string {
	shortForms := map[string]string{
		// Please keep this alphabetized
		"cs":     "componentstatuses",
		"ev":     "events",
		"limits": "limitRanges",
		"no":     "nodes",
		"po":     "pods",
		"pv":     "persistentVolumes",
		"pvc":    "persistentVolumeClaims",
		"quota":  "resourceQuotas",
		"rc":     "replicationcontrollers",
		// DEPRECATED: will be removed before 1.0
		"se":  "services",
		"svc": "services",
	}
```

cc @smarterclayton

**Comment by bgrant0607** [comment]
Mostly they're considered resources in kubectl -- RESTMapper, RESTMapping, etc.

**Comment by derekwaynecarr** [comment]
It uses resource to know how to construct the query.  I think resource is
the proper terminology here.

**Comment by bgrant0607** [comment]
cc @deads2k

**Comment by deads2k** [comment]
> It uses resource to know how to construct the query.  I think resource is
> the proper terminology here.

In the code its definitely a resource and I think it should stay that way.  I can envision scenarios where we'd like to have two different resources make use of a single kind.  In fact, many subresources already do that today.

**Comment by smarterclayton** [comment]
Yeah, this was intentionally focused on "resource names" vs "kinds".  We've defined "resource names" so far as the subset of names that transforms into at least one valid resource.  The client can be totally agnostic of resource name if you provide the exact value the server supports (i.e. a new type "foo" would be valid if the user typed "foos").  Unknown kinds though aren't our primary goal.

**Comment by smarterclayton** [comment]
I think you're right that we should use KIND in the cli, but not if people get confused thinking they have to use uppercase or can't use plurals (for usability).  It's better to establish "KIND" early.  Internally in code we have clear distinction between "resource" and "kind" because we transform a weak string (resource name) into a strong name (kind) and then back (to a value we place in a URL to retrieve restful resource)

**Comment by hurf** [comment]
IIUC we can use 'KIND' in the cli for help string, but keep others unchanged internally. I'll submit a small patch for this.

**Comment by bgrant0607** [comment]
I think the main confusing thing about RESOURCE is that it just refers to the collection, not the fully qualified resource.

**Comment by liggitt** [comment]
kubectl does operate on resources, both partial and fully qualified, and singular and plural

All of these work:

kubectl get role
kubectl get roles
kubectl get roles.rbac.authorization.k8s.io

The unqualified resources use the singular and plural resource names published in discovery to resolve a fully qualified plural resource
