### ISSUE TITLE
Add support for proxy-url for kubectl config

### ISSUE THREAD

**Issue by mengmann** [kubernetes/kubernetes#106374]
### What happened?

Since [this PR](https://github.com/kubernetes/kubernetes/pull/81443) we can now set and use a `proxy-url` within the cluster settings from $KUBECONFIG.
Currently there is [no support to add this option](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-set-cluster-em-) with command `kubectl config set-cluster`. So currently the only way is to add this parameter manually with a good old text editor in your kubeconfig. I would like to have this feature for convenience and automation purposes.

### What did you expect to happen?

Parameter `proxy-url` should be configurable with command `kubectl config set-cluster` 

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl config set-cluster "mycluster" --proxy-url=http://foo.bar:8080
Error: unknown flag: --proxy-url
```

### Kubernetes version

<details>
Does affect kubectl client only

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
```

</details>

### Cloud provider

<details>
none, as it affects kubectl client only
</details>

### OS version

<details>

```console
uname -a
Darwin *******.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Oct 12 18:34:05 PDT 2021; root:xnu-6153.141.43~1/RELEASE_X86_64 x86_64
```

</details>

**Comment by sftim** [comment]
I'm not sure how SIG Docs might help here. What's needed?

**Comment by mengmann** [comment]
Hi @sftim 

> I'm not sure how SIG Docs might help here. What's needed?

not yet. i just wanted to make sure this new feature gets documented when available.

**Comment by ardaguclu** [comment]
I think this issue is fixed with https://github.com/kubernetes/kubernetes/pull/105566
