### ISSUE TITLE
Curl: (7) Failed connect to Connection refused

### ISSUE THREAD

**Issue by pardeepbeniwal** [kubernetes/kubernetes#106304]
### What happened?

I have created Deployment, service and ingress with below yaml file:
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx  
    spec:
      containers:
      - name: nginx
        image: nginx:1.9
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "5m"
          requests:
            cpu: 1m

---

apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: nginx
  labels:
    name: nginx
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx
    id: "0"

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: default
  name: example-nginx-ingress-1
  labels:
    app: nginx
spec:
  rules:
  - host: example1x.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80

### What did you expect to happen?

1. External IP should show in service
![image](https://user-images.githubusercontent.com/12539456/141084314-5ea20fe6-689b-4c6d-a7a0-2ca1fd4bb1eb.png)

2. Using curl example1x.com host should be accessible outside cluster
![image](https://user-images.githubusercontent.com/12539456/141084911-32ed1332-5f4c-4385-9a3a-3b49420eabbf.png)

### How can we reproduce it (as minimally and precisely as possible)?

I have created deployment service and ingress with below command:
kubectl create -f deployment.yaml

### Anything else we need to know?

iptables-save output showing "default/nginx has no endpoints"
![image](https://user-images.githubusercontent.com/12539456/141085293-4f381814-0d8e-4171-ab44-6f23d7964281.png)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS ec2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

$ uname -a
Linux ip-172-31-24-205 4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubectl kubelet kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
unclear if a bug or support issue.

/kind support
/sig network

for triage.

**Comment by aojea** [comment]
/close
you need to install an ingress controller in order to use ingresses
https://kubernetes.github.io/ingress-nginx/deploy/#bare-metal-clusters

The web has docs and troubleshooting guides, also I think that there are examples there
