### ISSUE TITLE
Missing pod host in UI

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#10645]
I brought up a local cluster and created a simple pod.
Now when I go to ```http://localhost:8080/static/app/#/dashboard/pods```, I see that the host field is empty.

![pod_ui](https://cloud.githubusercontent.com/assets/10199099/8465279/9eb530ae-1ffd-11e5-84c0-b56a9e6e2e0b.png)

I assume that I should be seeing localhost/127.0.0.1 there.

**Comment by nikhiljindal** [comment]
```grep -r "spec.host" www/``` returns a few hits which could be the cause?
Note that we changed spec.host to spec.nodeName in v1

**Comment by nikhiljindal** [comment]
cc @bcbroussard  @jackgr @preillyme @lavalamp

**Comment by bcbroussard** [comment]
@nikhiljindal this is fixed in #10625

**Comment by nikhiljindal** [comment]
Great, thanks!

**Comment by zmerlynn** [comment]
@lavalamp, can you shepherd this with #10625?

**Comment by lavalamp** [comment]
Should we grab this new container by default? It should be a one-line change now.

**Comment by bcbroussard** [comment]
@lavalamp yes we should. I'll make a PR with the update

**Comment by lavalamp** [comment]
Hm, we need an e2e test that verifies that the UI returns 200's...
