### ISSUE TITLE
Make quoting of constants consistent in comments

### ISSUE THREAD

**Issue by jiahuif** [kubernetes/kubernetes#106437]
### What would you like to be added?

Currently, referencing constants in our go docs is inconsistent around our code base.
For example, somethings we use double-quotes 
```go
type DeploymentStrategy struct {
	// Type of deployment. Can be "Recreate" or "RollingUpdate". Default is RollingUpdate.
	// +optional
	Type DeploymentStrategyType
```

Sometimes no quotes
```go
type StatefulSetCondition struct {
	// Status of the condition, one of True, False, Unknown.
	Status api.ConditionStatus
```

Sometimes back-qoutes
```go
type StatefulSetSpec struct {
	// podManagementPolicy controls how pods are created during initial scale up,
	// when replacing pods on nodes, or when scaling down. The default policy is
	// `OrderedReady`, where pods are created in increasing order (pod-0, then
	// pod-1, etc) and the controller will wait until each pod is ready before
	// continuing. When scaling down, the pods are removed in the opposite order.
	// The alternative policy is `Parallel` which will create pods in parallel
	// to match the desired scale without waiting, and on scale down will delete
	// all pods at once.
	// +optional
	PodManagementPolicy PodManagementPolicyType
```

... and sometimes a mixture of double- and single- qoutes.
```go
type PodSpec struct {

	// Set DNS policy for the pod.
	// Defaults to "ClusterFirst".
	// Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
	// DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
	// To have DNS options set along with hostNetwork, you have to specify DNS policy
	// explicitly to 'ClusterFirstWithHostNet'.
	// +optional
	DNSPolicy DNSPolicy 
``` 

We should have a community guidance on how to refer to constants in the comments.

### Why is this needed?

to improve readability for documentations generated from godoc. For example, OpenAPI specs.

**Comment by sftim** [comment]
(this idea might need a KEP)

I wonder if we could have the generated code look like:
```
type StatefulSetSpec struct {
	// "podManagementPolicy" controls how pods are created during initial scale up,
	// when replacing pods on nodes, or when scaling down. The default policy is
	// "OrderedReady", where pods are created in increasing order (pod-0, then
	// pod-1, etc) and the controller will wait until each pod is ready before
	// continuing. When scaling down, the pods are removed in the opposite order.
	// The alternative policy is "Parallel" which will create pods in parallel
	// to match the desired scale without waiting, and on scale down will delete
	// all pods at once.
	// +optional
	PodManagementPolicy PodManagementPolicyType
```

and the primary code look like Markdown:
```
type StatefulSetSpec struct {
	///markdown
	/// `podManagementPolicy` controls how pods are created during initial scale up,
	/// when replacing pods on nodes, or when scaling down. The default policy is
	/// `OrderedReady`, where pods are created in increasing order (_pod-0_, then
	/// _pod-1_, etc) and the controller will wait until each pod is ready before
	/// continuing. When scaling down, the pods are removed in the opposite order.
	/// The alternative policy is `Parallel` which will create pods in parallel
	/// to match the desired scale without waiting, and on scale down will delete
	/// all pods at once.
	// +optional
	PodManagementPolicy PodManagementPolicyType
```

**Comment by apelisse** [comment]
> type StatefulSetSpec struct {
> 	// "podManagementPolicy" controls how pods are created during initial scale up,
> 	// when replacing pods on nodes, or when scaling down. The default policy is
> 	// "OrderedReady", where pods are created in increasing order (pod-0, then
> 	// pod-1, etc) and the controller will wait until each pod is ready before
> 	// continuing. When scaling down, the pods are removed in the opposite order.
> 	// The alternative policy is "Parallel" which will create pods in parallel
> 	// to match the desired scale without waiting, and on scale down will delete
> 	// all pods at once.
> 	// +optional
> 	PodManagementPolicy PodManagementPolicyType

I'm not sure what "generated code" you're referring to?

**Comment by sftim** [comment]
Here's one example of where that kind of code ends up (and it looks a bit messy):
https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#alpha-level

What I meant though was code like https://github.com/kubernetes/kubernetes/blob/aff056d8a197f6a404ad5e02210ca662d16c3dbe/staging/src/k8s.io/api/apps/v1beta1/types_swagger_doc_generated.go

As far as I know, this code counts as “generated”: you don't write it, you run a tool before / as you commit to make sure it gets updated automatically. Imagine if this had already been through a Markdown-to-something-else conversion (as I sketched out above). We could lint the Markdown bit to make sure it looked reasonable and also convert it so that the OpenAPI, online HTML etc docs are easier to read.

**Comment by jpbetz** [comment]
cc @liggitt @alculquicondor Is there a preferred quoting pattern to use in APIs going forward? We've got some APIs that we'd like to get right.

**Comment by alculquicondor** [comment]
If SIG docs has the intention of adding a markdown parser to the go docs, I'm all down for it. In that case, you should probably use backticks.

**Comment by sftim** [comment]
> SIG Docs

Folks who contribute to that SIG are more likely to be tech writers than Go coders, I'm afraid! (If I were making something, I'd borrow the way Rust does it: https://doc.rust-lang.org/rust-by-example/meta/doc.html)

**Comment by apelisse** [comment]
Yeah, as we discussed with Tim, it'd be actually useful to have tech writers review API comments, or any comment that end-up in user-facing documentation. We'd probably need a process for that, like a "requires-doc-review" that requires a specific lgtm maybe.

**Comment by jpbetz** [comment]
/remove-lifecycle rotten

I'm in favor of having clear, well defined formatting rules for APIs. Markdown (or some subset) seems sane to me. 

+ @kubernetes/api-approvers for any thoughts or prior work on this.
