### ISSUE TITLE
GCE Ingress tests failures

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#106402]
### Which jobs are failing?

https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e
https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e-scale

### Which tests are failing?

Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should sync endpoints to NEG expand_more	3s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should conform to Ingress spec expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] rolling update backend pods should not cause service disruption expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should sync endpoints for both Ingress-referenced NEG and standalone NEG expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should create NEGs for all ports with the Ingress annotation, and NEGs for the standalone annotation otherwise expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should be able to create a ClusterIP service expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:NEG] [Flaky] should be able to switch between IG and NEG modes expand_more	2s
Kubernetes e2e suite: [sig-network] Loadbalancing: L7 GCE [Slow] [Feature:Ingress] should conform to Ingress spec expand_more

### Since when has it been failing?

11-13

### Testgrid link

https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e

### Relevant SIG(s)

/sig network

**Comment by swetharepakula** [comment]
All tests are failing with the same message: ` configmaps "ingress-uid" not found which usually is the error if the glbc/ingress-gce controller is not running.

The ingress-gce/glbc logs are also empty.

**Comment by swetharepakula** [comment]
Kubelet log shows failures to pull the glbc image: 
```
E1115 12:50:41.037402    2032 remote_image.go:114] "PullImage from image service failed" err="rpc error: code = NotFound desc = failed to pull and unpack image \"k8s.gcr.io/ingress-gce-glbc-amd64:master\": failed to resolve reference \"k8s.gcr.io/ingress-gce-glbc-amd64:master\": k8s.gcr.io/ingress-gce-glbc-amd64:master: not found" image="k8s.gcr.io/ingress-gce-glbc-amd64:master"
```

**Comment by swetharepakula** [comment]
This job still uses the old image registry. The ingress-gce repo already pushes to a different registry (gcr.io/k8s-ingress-image-push) and most of the jobs have already been converted to use those images. I will send a PR to update the remaining two ingress-gce jobs to use images from the newer registry.

**Comment by swetharepakula** [comment]
I will close this bug out, once ci is green.

**Comment by swetharepakula** [comment]
Closing since both testgrids are now green.

/close
