### ISSUE TITLE
Move scheduler Score plugin weight defaulting to API

### ISSUE THREAD

**Issue by damemi** [kubernetes/kubernetes#106426]
The scheduler framework instantiation currently handles defaulting the weights of Score plugins, as well as checking that the total weight is not more than the maximum:

https://github.com/kubernetes/kubernetes/blob/9dc0489/pkg/scheduler/framework/runtime/framework.go#L292-L306

this should be moved to the API defaulting itself to catch this earlier and be more secure
/sig scheduling
/kind feature

**Comment by kerthcet** [comment]
I can give some help. 
/assign

**Comment by NikhilSharmaWe** [comment]
@damemi I would like to collaborate. Could you please elaborate and tell in **what files** the changes should be made for handling the weight of Score Plugins in API Defaulting.

**Comment by damemi** [comment]
@NikhilSharmaWe it looks like @kerthcet has already offered to work on this, but if you would like to collaborate on it feel free. The code in question is located in https://github.com/kubernetes/kubernetes/blob/9dc0489/pkg/scheduler/framework/runtime/framework.go#L292-L306, and we are interested in moving it to the actual API defaulting sections, probably https://github.com/kubernetes/kubernetes/blob/9dc0489c1ae3540453d94348efcc536585c31805/pkg/scheduler/apis/config/v1beta2/defaults.go

**Comment by kerthcet** [comment]
Yes, I'm working on this issue also, but I haven't push commits yet for I still have some questions, let's discuss about it 
 here. Correct me if any mis-understandings.

Since we'll merge out-of-tree plugins [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L236-L239), I think move the codes to `default.go` will miss some plugins. 

And I prefer to move the code [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/profile/profile.go#L88-L118), as we have already validate the `QueueSort` Plugins here. WDYT @damemi

**Comment by damemi** [comment]
@kerthcet I don't think out-of-tree plugins will miss the validation if we move it to API. This is going to be agnostic of the specific plugin types, validating that there is just a weight set for each score plugin and that those weights aren't more than the max score. Another possible location could be here: https://github.com/kubernetes/kubernetes/blob/9dc0489c1ae3540453d94348efcc536585c31805/pkg/scheduler/apis/config/validation/validation.go

I also don't think moving the code to `profile.go` is what we want either. We're validating `QueueSort` plugins in that spot because we need to check across each individual profile("framework") to make sure there are no conflicts. The reason that check is in that spot is because that's after each framework/profile has been initialized. But, we could check the score weights on individual profiles as they're created. Does that make sense?

**Comment by kerthcet** [comment]
> @kerthcet I don't think out-of-tree plugins will miss the validation if we move it to API. This is going to be agnostic of the specific plugin types, validating that there is just a weight set for each score plugin and that those weights aren't more than the max score. Another possible location could be here: https://github.com/kubernetes/kubernetes/blob/9dc0489c1ae3540453d94348efcc536585c31805/pkg/scheduler/apis/config/validation/validation.go
> 
> I also don't think moving the code to `profile.go` is what we want either. We're validating `QueueSort` plugins in that spot because we need to check across each individual profile("framework") to make sure there are no conflicts. The reason that check is in that spot is because that's after each framework/profile has been initialized. But, we could check the score weights on individual profiles as they're created. Does that make sense?
> 
yes, I double-checked the code and I found I misunderstood the intention of function `merge()`. Thanks for your explanations, I'll push a commit tomorrow and some tests are needed too.

**Comment by kerthcet** [comment]
hi @damemi , I found it's easy to handle plugins in `KubeSchedulerProfile.Plugins.Score.Enabled` since all the plugins are implements of `ScoreExtensionPoint` , however , we can not make sure what extension point these plugins implemented in `KubeSchedulerProfile.Plugins.MultiPoint.Enabled`, for only score plugins using these weights. do you have any idea?

**Comment by damemi** [comment]
@kerthcet that is the challenge with this, and I'm open to suggestions on how we could implement it. You might have to look into doing a similar loop to try to cast all of the MultiPoint plugins to a ScorePlugin, and if that succeeds then check for the weights.

**Comment by kerthcet** [comment]
thanks, I'll have a try then.

**Comment by damemi** [comment]
@kerthcet any updates or progress on this?

**Comment by kerthcet** [comment]
Sorry, I just return from holidays and I talked with @NikhilSharmaWe , he is free to continue his work and I can provide some help if needed.

**Comment by kerthcet** [comment]
/remove-lifecycle rotten
Still helpful

**Comment by sanposhiho** [comment]
/remove-lifecycle rotten

I guess @kerthcet is working on it.
