### ISSUE TITLE
kube-proxy: move "proxier.deleteEndpointConnections" to util

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#106484]
### What happened?

https://github.com/kubernetes/kubernetes/blob/6c357f9996070fd015e08eec24f07c82b4b8b4a6/pkg/proxy/iptables/proxier.go#L727-L731
we should move `deleteEndpointConnections` to util?  This function is almost the same as:  https://github.com/kubernetes/kubernetes/blob/6c357f9996070fd015e08eec24f07c82b4b8b4a6/pkg/proxy/ipvs/proxier.go#L1942

### What did you expect to happen?

Should we integrate these two functions into /util/DeleteEndpointConnections ?

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dcbw** [comment]
@cyclinder would you be able to submit a PR that consolidates the two functions in util?

**Comment by jayunit100** [comment]
hiya @cyclinder , there are quite a few areas where code might be deduped in kube-proxy - if your interested in a holistic approach to helping us solve this, were refactoring alot of various functions in kube-proxy in the https://github.com/kubernetes-sigs/kpng/ project, if you'd like to join us, we have meetings in india and US friendly times... https://github.com/kubernetes/community/tree/master/sig-network

**Comment by cyclinder** [comment]
@dcbw yeah, I would like to try it！

**Comment by cyclinder** [comment]
@jayunit100 of course, this meeting have a friendly times

**Comment by rikatz** [comment]
@cyclinder we have an umbrella issue for kproxy cleanup related stuff as well (need to remember where is it), but go for it. Please take a look if it makes more sense to move this to staging/ or to pkg/proxy/util and please let me know how I can help you ok?

Thanks

**Comment by cyclinder** [comment]
hi @rikatz Can we discuss it on slack?

**Comment by rikatz** [comment]
Hey @cyclinder sure we can!

Sorry for the long delay, taking some time to check my late notifications.

We've been doing some pkg/proxy cleanup (see https://github.com/kubernetes/kubernetes/issues/92369) and IMO this can be part of it.

The issue is dragging a bit as all of us are pretty "busy" but all help on this is welcome.

As proxier is an interface (it is an interface...right? :D ) probably there is going to be some more effort in moving this function to the external utils package but still, from a quick look into the code it seems something that we want to do :)

Makes sense?

**Comment by cyclinder** [comment]
yeah！This is very meaningful, so first we sholud move this function to util?  and later, we will move the pkg/proxy to staging?

**Comment by cyclinder** [comment]
oh sorry..  I forgot this item... I will finish it recently
