### ISSUE TITLE
[WARNING] InvalidDiskCapacity warning thrown in node events by Kubelet

### ISSUE THREAD

**Issue by furkatgofurov7** [kubernetes/kubernetes#106420]
### What happened?

Kubelet keeps throwing `InvalidDiskCapacity` kubelet invalid capacity 0 on image filesystem in the nodes status

```
  Normal   NodeHasNoDiskPressure    29m (x5 over 29m)  kubelet  Node cp-host-1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     29m (x5 over 29m)  kubelet  Node cp-host-1 status is now: NodeHasSufficientPID
  Normal   NodeHasSufficientMemory  29m (x6 over 29m)  kubelet  Node host-1 status is now: NodeHasSufficientMemory
  Normal   NodeAllocatableEnforced  29m                kubelet  Updated Node Allocatable limit across pods
  Normal   Starting                 29m                kubelet  Starting kubelet.
  Warning  InvalidDiskCapacity      29m                kubelet  invalid capacity 0 on image filesystem
  Normal   NodeHasSufficientMemory  29m                kubelet  Node cp-host-1 status is now: NodeHasSufficientMemory
  Normal   NodeHasNoDiskPressure    29m                kubelet  Node cp-host-1 status is now: NodeHasNoDiskPressure
  Normal   NodeHasSufficientPID     29m                kubelet  Node cp-host-1 status is now: NodeHasSufficientPID
  Normal   Starting                 29m                kubelet  Starting kubelet.

```

### What did you expect to happen?

No warnings thrown in output of node events

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

I have checked couple of reported issues open/closed ones in the repo and most of them have this in logs when node logs were provided, can this be considered benign or disregarded?
Also, the same has been [reported](https://github.com/kubernetes/kubernetes/issues/59742) some time ago (2018) but that was seen in windows nodes and was fixed [here](https://github.com/kubernetes/kubernetes/pull/59743). Maybe, this should be OS agnostic and fix should be extended?  

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-11-04T09:36:56Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

```console
SLES 15 SP2
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

```console
containerd version:  containerd github.com/containerd/containerd v1.5.6 1a1b383ad5b520349f13f9715e0cd1e2f132c087
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI is not deployed at that point
</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/kubelet/stats/cadvisor_stats_provider.go#L246-L271

It is most likely a cadvisor related issue on `SLES 15 SP2`.
/area cadvisor

**Comment by jackfrancis** [comment]
@pacoxu do you think that https://github.com/kubernetes/kubernetes/pull/101882 will help?

Upon first glance, I don't think this is related

**Comment by pacoxu** [comment]
> @pacoxu do you think that #101882 will help?

Maybe.
I need to do some deep digging.

**Comment by ehashman** [comment]
/remove-triage accepted
/triage needs-information

Reading over this more closely, this may be an install environment specific issue.

Can you please attach a copy of the kubelet logs (preferably at v=4 or higher) for the affected node?
