### ISSUE TITLE
Service Externel IP does not become pending after uninstall metallb

### ISSUE THREAD

**Issue by hellobiek** [kubernetes/kubernetes#106474]
### What happened?

I had deployed a istio-ingressgateway service using metallb, which allocated a EXTERNAL-IP for istio-ingressgateway. Now I decided to using NodePort for service. So I uninstalled metallb and using NodePort.

However, When I change the service type from NodePort back to LoadBalancer, the EXTERNAL-IP is still using the old hostname but not becoming Pending.

The service is now as belows:

| NAME                        | TYPE                | CLUSTER-IP    | EXTERNAL-IP  | PORT(S)                                                               | AGE |
|  ----                           | ----                  |----                  | ---                   | ---                                                                        | ---   |
| istio-ingressgateway | LoadBalancer   |10.100.30.112 | 192.168.0.0     | 15021:32177/TCP,80:31918/TCP,443:32185/TCP | 92d |

Even if I change from service type from LoadBalancer to NodePort, then change from NodePort back to LoadBalanacer.

The EXTERNAL-IP still the old one.

### What did you expect to happen?

When I change the sevice type from NodePort to LoadBalancer, the EXTERNAL-IP  become to Pending.Just as belows:

| NAME                        | TYPE                | CLUSTER-IP    | EXTERNAL-IP  | PORT(S)                                                               | AGE |
|  ----                           | ----                  |----                  | ---                   | ---                                                                        | ---   |
| istio-ingressgateway | LoadBalancer   |10.100.30.112 | Pending          | 15021:32177/TCP,80:31918/TCP,443:32185/TCP | 92d |

### How can we reproduce it (as minimally and precisely as possible)?

- STEP1: Install a Metallb, 
- STEP2: and deploy a service using LoadBalancer type, then the service will has a EXTERNAL-IP
- STEP3: Uninstall Metallb
- STEP4: change service type to NodePort, then EXTERNAL-IP will become None
- STEP5: change serivce type back to LoadBalancer, then the EXTERNAL-IP can not be Pending

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
self deployed using kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


$ uname -a
Linux ip-10-20-0-213 5.4.0-1059-aws #62~18.04.1-Ubuntu SMP Fri Oct 22 21:51:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by uablrek** [comment]
This is not a K8s bug. Metallb has updated the `status.loadBalancer.ingress[0]` field in the service object, a field K8s does not set (or unsets). It is Metallb that has to unset it when it is uninstalled.

/remove-kind bug
/kind support

**Comment by uablrek** [comment]
If you change the type of the service, LoadBalancer -> NodePort, the external ip will become "<none>". This is the appropriate action in this case IMO.

**Comment by uablrek** [comment]
I have updated https://github.com/Nordix/assign-lb-ip/ with a `-clear` option. You can use it to clear status.loadBalancer.ingress.
Bus as mentioned, since you don't use the loadBalancer type you should switch to NodePort.

I close this issue. You may open another on metallb and refer to this one.

/close
