### ISSUE TITLE
NVIDIA GPU Device Plugin sig-node serial tests failing

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#106466]
### Which jobs are failing?

ci-kubernetes-node-kubelet-serial 

### Which tests are failing?

```
E2eNode Suite.[sig-node] NVIDIA GPU Device Plugin [Feature:GPUDevicePlugin][NodeFeature:GPUDevicePlugin][Serial] [Disruptive] DevicePlugin keeps GPU assignment to pods across pod and kubelet restarts. [cos-stable2]Changes
```

### Since when has it been failing?

Last passing run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1460315712001150976
First failing run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1460376110792445952

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

### Relevant SIG(s)

/sig node
/sig testing

**Comment by bobbypage** [comment]
The tests are failing because there was an image bump.

Last passing run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1460315712001150976
Used image `cos-93-16623-39-16-1d5a92df`

First failing run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1460376110792445952
Used image: `cos-93-16623-39-21-1c63d218`

From the new image `cos-93-16623-39-21-1c63d218`, in the [cloud-init logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1460678424329719808/artifacts/n1-standard-2-cos-93-16623-39-21-932cb27d/cloud-init.log) from the gpu installer:
```
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: I1116 18:42:05.807575     737 install.go:113] Installing GPU driver version 450.119.04
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: I1116 18:42:05.807795     737 cache.go:69] error: failed to read file /root/var/lib/nvidia/.cache: open /root/var/lib/nvidia/.cache: no such file or directory
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: I1116 18:42:05.807822     737 installer.go:92] Configuring driver installation directories
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: I1116 18:42:05.856736     737 signature.go:30] Downloading driver signature for version 450.119.04
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: I1116 18:42:05.856769     737 utils.go:88] Downloading 450.119.04.signature.tar.gz from https://storage.googleapis.com/cos-tools/16623.39.21/extensions/gpu/450.119.04.signature.tar.gz
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: E1116 18:42:05.919770     737 install.go:240] The GPU driver is not available for the COS version. Please wait for half a day and retry.
```

It looks like the GPU drivers are not published yet for this COS image, as per the error message:
```
Nov 16 18:42:05 n1-standard-2-cos-93-16623-39-21-932cb27d cloud-init[651]: E1116 18:42:05.919770     737 install.go:240] The GPU driver is not available for the COS version. Please wait for half a day and retry.
```

**Comment by SergeyKanzhelev** [comment]
/triage accepted

@kewu1992 tests rely on latest image of COS and corresponding GPU plugin. Is there any way to guarantee that both will be available at the same time always?

Alternative is to fix the test to skip if driver is not available. @bobbypage since you looked into it, any idea how to do it easily?

**Comment by bsdnet** [comment]
One way is to fix GPU device plug-in testing using not latest LTS; 
The other way is to bypass the test when GPU driver is not available.

We are also actively fixing the gap between COS image and GPU driver

**Comment by bobbypage** [comment]
test is passing now

/close
