### ISSUE TITLE
 [Failing test][sig-scalability] gce-master-scale-correctness

### ISSUE THREAD

**Issue by rajula96reddy** [kubernetes/kubernetes#106459]
### Which jobs are failing?

gce-master-scale-correctness

### Which tests are failing?

- Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Inline-volume (xfs)][Slow] volumes should allow exec of files on the volume
- Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (xfs)][Slow] volumes should store data

### Since when has it been failing?

2021-11-11 (13:01 CET)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Reason for failure (if possible)

- Kubernetes  e2e suite: [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern:  Inline-volume (xfs)][Slow] volumes should allow exec of files on the  volume
  ```
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:196 Nov 15 12:30:00.907: Unexpected error:     <*errors.errorString \| 0xc00086bda0>: {         s: "expected pod \"exec-volume-test-inlinevolume-nkgm\" success: Gave up after waiting 5m0s for pod \"exec-volume-test-inlinevolume-nkgm\" to be \"Succeeded or Failed\"",     }     expected pod "exec-volume-test-inlinevolume-nkgm" success: Gave up after waiting 5m0s for pod "exec-volume-test-inlinevolume-nkgm" to be "Succeeded or Failed" occurred /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/util.go:743
  ```
- Kubernetes e2e suite: [sig-storage] In-tree Volumes [Driver: gcepd] [Testpattern: Dynamic PV (xfs)][Slow] volumes should store data
  ```
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:159
  Nov 15 12:38:47.338: Failed to create injector pod: timed out waiting for the condition
  /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumes.go:186
  ```

### Relevant SIG(s)

/sig scalability

**Comment by leiyiz** [comment]
all `In-tree Volumes [Driver: gcepd]` are failing, likely due to https://github.com/kubernetes/kubernetes/pull/104722, will add a skip to test-config
