### ISSUE TITLE
Moving recovery from expansion failure feature from alpha to beta

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#106429]
### What would you like to be added?

Moving Recovery from expansion failure from alpha to beta requires careful consideration of version skews between kubelet, resizer and api-server.

- [ ] Handle the case where external-resizer is older but kubelet is newer. In this case, if `ResizeStatus` is not set, kubelet will refuse to expand the volume on the node by default.
- [ ] Handle the case where kubelet is older. In this case - kubelet could bypass safety mechanism we have built in to not expand the PVCs which are failing node expansion. 
- [ ] Handle the case of nil vs empty string for `pvc.Status.ResizeStatus`. 
- [ ] Allow PVC size to go back to original size.
- [ ] Verify PV size after expansion in unit tests.

xref https://github.com/kubernetes/enhancements/issues/1790

### Why is this needed?

To track issues related to recovery from expansion feature going beta.

**Comment by msau42** [comment]
One more item is to evaluate if we can shrink all the way back to original size.

**Comment by gnufied** [comment]
@msau42 thanks updated.
