### ISSUE TITLE
Use "Deprecated:" instead of "Deprecated." in types.go (once generated files are excluded from static check)

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#106405]
See https://github.com/kubernetes/kubernetes/pull/106285#discussion_r746885942

Deprecated with semicolon marks the field as deprecated. Other forms are just comments. If replaced today - static check will complain like this below. So once generated files are excluded from the static check, need to replace dot (`Deprecated.`) after "Deprecated" to colon (`Deprecated:`).

/kind cleanup
/sig api-machinery
/priority important-longterm

`./hack/verify-staticcheck.sh`:

```
Errors from staticcheck:
pkg/apis/core/v1/zz_generated.conversion.go:4127:2: out.TCPSocket is deprecated: TCPSocket is NOT supported as a LifecycleHandler and kept for the backward compatibility. There are no validation of this field and lifecycle hooks will fail in runtime when tcp handler is specified. +optional  (SA1019)
pkg/apis/core/v1/zz_generated.conversion.go:4139:55: in.TCPSocket is deprecated: TCPSocket is NOT supported as a LifecycleHandler and kept for the backward compatibility. There are no validation of this field and lifecycle hooks will fail in runtime when tcp handler is specified. +optional  (SA1019)
pkg/apis/core/validation/validation.go:2697:14: lh.TCPSocket is deprecated: TCPSocket is NOT supported as a LifecycleHandler and kept for the backward compatibility. There are no validation of this field and lifecycle hooks will fail in runtime when tcp handler is specified. +optional  (SA1019)
```

**Comment by NikhilSharmaWe** [comment]
@SergeyKanzhelev I am looking forward to contribute for this cleanup, could you please give me some direction about in which files and how can I proceed to work on this.

**Comment by NikhilSharmaWe** [comment]
@SergeyKanzhelev Are you talking about changing Derprecated. descrpition in types.go file to Deprecated:.
If you confirm I can continue to add this.

**Comment by NikhilSharmaWe** [comment]
@0904-mansi Actually I am already working on this.

**Comment by SergeyKanzhelev** [comment]
@NikhilSharmaWe @0904-mansi important thing here is to either fix or wait to be fixed the problem that generated files are being static checked. WIth the change to real deprecated field, they start failing the static check.

**Comment by SergeyKanzhelev** [comment]
this is now can be worked on.

Ideally all deprecations (`grep -R --include="types.go" deprecated`) needs to be unified to use `Deprecated:` syntax

**Comment by NikhilSharmaWe** [comment]
@SergeyKanzhelev what we want here is to change `deprecated` to `deprecated:`. But do we want to change every time we see  `deprecated` in a types.go file comments like for example do `staging/src/k8s.io/api/apps/v1/types.go:        DeprecatedTemplateGeneration   = "deprecated.daemonset.template.generation"
`  and if don't want to add `:` in this case, how can I add `:` at reasonable place in the comments because no. of cases I get by `grep -R --include="types.go" deprecated` are approximately 500. Do we need to change them manually or there is any other way.

**Comment by SergeyKanzhelev** [comment]
> for example in `staging/src/k8s.io/api/apps/v1/types.go: DeprecatedTemplateGeneration = "deprecated.daemonset.template.generation" ` and if don't want to add `:` in this case,

Yes, don't add it here.

> the comments because no. of cases I get by grep -R --include="types.go" deprecated are approximately 500

Yes, there are a lot of matches, but those are easily filtereable. I think it is reasonable to rephrase things like "// This field is deprecated in favor of setting" into "//Deprecated: This field is deprecated..." (add Deprecated:) and "// Deprecated in v1.21: It isn't being" to "Deprecated: It isn't being..." (remove version)
