### ISSUE TITLE
Go Client: RESTClient.Get returns error: "etcdserver: leader changed"

### ISSUE THREAD

**Issue by lbernick** [kubernetes/kubernetes#106491]
### What happened?

Tekton, the project I work on, uses knative/pkg's generated reconcilers that rely on the go RESTClient. A user reported to us in #tektoncd/pipeline/issues/4116 an error: "etcdserver: leader changed" which appears to have bubbled up from a call to RESTClient.Get. We also see in our webhook logs "leaderelection.go:325] error retrieving resource lock tekton-pipelines/tekton-pipelines-webhook.conversionwebhook.00-of-01: etcdserver: leader changed", a log which appears to come from [here](https://github.com/kubernetes/client-go/blob/3f38fd30fc59a8cb233980bf42728650fdfd06be/tools/leaderelection/leaderelection.go#L330).

### What did you expect to happen?

I would expect an error to be returned from the RESTClient that gives more context related to kubernetes, especially whether this error is retryable (I suspect for us it is). I would expect that the error returned would be one exported by the Go client, so our code can import that error and handle it. Currently, we don't have a way to handle the error without either using string comparison of error messages, or adding etcd as a dependency (this error is defined [here](https://github.com/etcd-io/etcd/blob/5b226e0abf4100253c94bb71f47d6815877ed5a2/server/etcdserver/errors.go#L30)). I considered opening this issue downstream in knative, but based on [this retry function](https://github.com/knative/pkg/blob/517ef0292b5362ec316d227a866821bc31ec99a8/reconciler/retry.go#L50-L66) and #knative/networking/issues/147 it looks like they also do not have a better way to handle this error.

### How can we reproduce it (as minimally and precisely as possible)?

unknown :(

The user appears to have had a workload running for about 23 hours when this occurred.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"c18ff7bd5227b42c617cf371cf315d0423e91d5e", GitTreeState:"clean", BuildDate:"2021-05-25T17:38:04Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.19) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Tekton is running on Azure aks 1.19.11 with cluster autoscaler, currently with 2 linux nodes and one windows node.

```console
$ kubectl get node
NAME                                STATUS   ROLES   AGE   VERSION
aks-nodepool1-21727696-vmss000000   Ready    agent   16d   v1.19.11
aks-nodepool1-21727696-vmss000004   Ready    agent   14d   v1.19.11
aksnpwin000000                      Ready    agent   16d   v1.19.11
```
</details>

**Comment by lbernick** [comment]
/sig api-machinery

Please feel free to reassign if this is better handled by another group.

**Comment by leilajal** [comment]
@ibabou  can you confirm their set-up is right? we would suggest you to
-check you own environment
-update etcd version
It is most likely that there is some problem with your network setup.

**Comment by lbernick** [comment]
Hi @leilajal, thanks for your response! Looping in @tibcoplord who originally reported the issue. I think there are two problems here:
1. there may be something wrong with their network setup
2. we can't handle the error returned without string comparison (and don't have a good sense of what to do about it). I would expect a REST client to return one of the typical REST error codes rather than an error bubbled up from etcd.

**Comment by tibcoplord** [comment]
FYI, I think this can happen when the cluster auto scales ( add or remove new node ), rather than a generic network issue.

I expect tekton needs to re-try ... or at least not completely stop the pipeline.
