### ISSUE TITLE
we should reject HostPort use in daemonset when maxSurge is non-zero

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#106417]
### What happened?

when  use hostport and set maxSurge =2，k8s create daemonset successfullly.
but DaemonSet rolling update is stuck， due to the failure of pod scheduling.
Events：
Warning  FailedScheduling  34s   default-scheduler  0/2 nodes are available: 1 node(s) didn't have free ports for the requested pod ports, 1 node(s) didn't match Pod's node affinity/selector.

### What did you expect to happen?

when  we use hostport and set maxSurge =2，k8s should refuse to create daemonset.

### How can we reproduce it (as minimally and precisely as possible)?

使用下面yaml文件，创建daemonset：
daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-nginx-3
  namespace: opcs
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: ds-nginx-3
  template:
    metadata:
      labels:
        name: ds-nginx-3
    spec:
      containers:
      - image: swr:2512/opcs/nginx:v1
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 8080
          hostPort: 54323
  updateStrategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate

执行命令进行滚动升级：
kubectl set image ds ds-nginx-3 nginx=swr:2512/opcs/nginx:v2 -n opcs

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
[root@paas-controller-paas-boe-master-ca-gcjfh7nagy37-0:/home/ubuntu]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>

</details>
NONE

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
hostPort is only one type of resource that could prevent a surge rollout. I'm not sure special-casing it makes sense.
