### ISSUE TITLE
Custom resource status validation doesn't do embedded resource and x-kubernetes-list-type validation

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#106401]
`statusStrategy#ValidateUpdate` doesn't do the same embedded resource and x-kubernetes-list-type "map" and "set" invariant validation that happens in custom resource create/update validation.

Does that mean embedded objects and list-type fields under custom resource status can contain invalid data? 

if so, that needs to be fixed in a way that tolerates existing invalid data (ratcheting validation)

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/106051#discussion_r748634676_

/sig api-machinery
/kind bug
/priority important-longterm

**Comment by NikhilSharmaWe** [comment]
@liggitt I would like to collaborate for fix the validation issue for custom resources. Could you please guide me with some code pointers, files and elaborate on how can I proceed to fix this bug

**Comment by liggitt** [comment]
I haven't tested this, but something along the lines of this:

```diff
diff --git a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go b/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
index 5582633f00c..4ba63ac53ee 100644
--- a/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
+++ b/staging/src/k8s.io/apiextensions-apiserver/pkg/registry/customresource/status_strategy.go
@@ -23,6 +23,7 @@ import (
 	"k8s.io/apimachinery/pkg/runtime"
 	"k8s.io/apimachinery/pkg/util/validation/field"
 	"sigs.k8s.io/structured-merge-diff/v4/fieldpath"
+	structurallisttype "k8s.io/apiextensions-apiserver/pkg/apiserver/schema/listtype"
 )
 
 type statusStrategy struct {
@@ -88,6 +89,13 @@ func (a statusStrategy) ValidateUpdate(ctx context.Context, obj, old runtime.Obj
 	if u, ok := obj.(*unstructured.Unstructured); ok {
 		v := obj.GetObjectKind().GroupVersionKind().Version
 
+		// ratcheting validation of x-kubernetes-list-type value map and set
+		if uOld, oldUnstructured := old.(*unstructured.Unstructured); oldUnstructured {
+			if oldErrs := structurallisttype.ValidateListSetsAndMaps(nil, a.structuralSchemas[v], uOld.Object); len(oldErrs) == 0 {
+				errs = append(errs, structurallisttype.ValidateListSetsAndMaps(nil, a.structuralSchemas[v], u.Object)...)
+			}
+		}
+
 		// validate x-kubernetes-validations rules
 		if celValidator, ok := a.customResourceStrategy.celValidators[v]; ok {
 			errs = append(errs, celValidator.Validate(nil, a.customResourceStrategy.structuralSchemas[v], u.Object)...)
```

we'd need tests to exercise the following scenarios on a CRD that specifies a status subresource with a list property with x-kubernetes-list-type=map and x-kubernetes-list-type=set

1. ensure a custom resource instance that already has duplicate items in the status property list can be updated successfully while still having duplicate items in the list (validation doesn't block an invalid → invalid status update)
2. ensure a custom resource instance that already has duplicate items in the status property list can be updated successfully to set unique items in the list (validation doesn't block an invalid → valid status update) 
3. ensure a custom resource instance that does not have duplicate items in the status property list cannot be updated to set duplicate items in the list (validation blocks a valid → invalid status update)

**Comment by uhari03** [comment]
since it's been a couple of months, i'm going to try and take a stab at this
/assign

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/107860 has stalled needing tests and a rebase

**Comment by harshitasao** [comment]
Thanks for the update.

**Comment by harshitasao** [comment]
Hello @liggitt, with the code freeze approaching, is this still on track for v1.25?
Thanks!

**Comment by liggitt** [comment]
not really, the status on https://github.com/kubernetes/kubernetes/pull/107860 is the same (needs tests)
