### ISSUE TITLE
add option to delete the iptables, created by kubelet

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/kubernetes#106480]
### What happened?

`kubeadm reset` does not delete the iptables/ipvs/ipset entries, created by `kubeadm init`. Part of the entries are created by kube-proxy and can be cleaned by kube-proxy --cleanup. Others are created by kubelet. See also kubernetes/kubeadm#2587 .

 * add a method to kubelet to delete all iptables/ipvs/ipset entries created by it, so that `kubeadm reset` can revert the effect of `kubeadm init`.

Copy of https://github.com/kubernetes/kubelet/issues/32.  

### What did you expect to happen?

`kubelet` shall have means to delete the iptables, it has created.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Kubernetes version

1.22

### Cloud provider

Me

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/sig network

Long history here https://github.com/kubernetes/kubernetes/issues/82125

**Comment by danwinship** [comment]
When dockershim goes away, we'll be in the odd position that kubelet creates some iptables rules itself, but it never _uses_ any iptables rules. So we should move all of kubelet's rules into kube-proxy. At that point, there would be nothing for kubelet to clean up.

This probably needs to be done over several releases, as there may be people expecting KUBE-MARK-MASQ to exist who aren't running kube-proxy.

If you think it's important for kubeadm to handle this before then, then I would say to just add a hack to kubeadm.

**Comment by danwinship** [comment]
/close
(Closing this as #82125 covers the larger issue.)

**Comment by neolit123** [comment]
we have some kubeadm docs here for clearing rules so this is not a high priority:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#remove-the-node

even if the rules are only in kube-proxy, kube-proxy is also optional in kubeadm and is run as a DS by default, which makes it tricky to execute the kube-proxy cleanup on demand from some container that may or may not run on the host.

https://github.com/kubernetes/kubeadm/issues/2587
this pretty much needs a KEP or a google doc design of sorts.
