### ISSUE TITLE
Certificates shown as expired even after refresh

### ISSUE THREAD

**Issue by ratheeshtv** [kubernetes/kubernetes#106499]
### What happened?

Docker  Version:           18.06.1-ce
OS NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
PRETTY_NAME="Ubuntu 18.04.3 LTS"

Issue:

    kubernetes nodes becomes Notready with message - Kubelet stopped posting node status.
kube-apiserver logs shows :

{"log":"E1103 18:28:07.208359       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid\n","stream":"stderr","time":"2021-11-03T18:28:07.208526256Z"}
{"log":"E1103 18:28:07.209217       1 authentication.go:65] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid\n","stream":"stderr","time":"2021-11-03T18:28:07.209328899Z"}

Followed by continuous TLS handshake error:

{"log":"I1103 18:28:07.223687       1 log.go:172] http: TLS handshake error from 10.158.81.131:52376: EOF\n","stream":"stderr","time":"2021-11-03T18:28:07.224933646Z"}
{"log":"I1103 18:28:07.223871       1 log.go:172] http: TLS handshake error from 10.158.81.131:52398: 

Finally shows shutting down:

{"log":"I1109 07:53:49.002444       1 customresource_discovery_controller.go:219] Shutting down DiscoveryController\n","stream":"stderr","time":"2021-11-09T07:53:49.00289885Z"}
{"log":"I1109 07:53:49.002455       1 establishing_controller.go:84] Shutting down EstablishingController\n","stream":"stderr","time":"2021-11-09T07:53:49.002902275Z"}
{"log":"I1109 07:53:49.002466       1 naming_controller.go:295] Shutting down NamingConditionController\n","stream":"stderr","time":"2021-11-09T07:53:49.00290554Z"}
{"log":"I1109 07:53:49.002476       1 autoregister_controller.go:163] Shutting down autoregister controller\n","stream":"stderr","time":"2021-11-09T07:53:49.002908894Z"}
{"log":"I1109 07:53:49.003433       1 secure_serving.go:160] Stopped listening on [::]:6443\n","stream":"stderr","time":"2021-11-09T07:53:49.003492221Z"}
{"log":"E1109 07:53:49.008239       1 controller.go:179] Get https://localhost:6443/api/v1/namespaces/default/endpoints/kubernetes: dial tcp 127.0.0.1:6443: connect: connection refused\n","stream":"stderr","time":"2021-11-09T07:53:49.008481878Z"}

Tried refreshing the certificates but no luck.
But kubectl get pod --all-namespaces  shows all PODS as running.

### What did you expect to happen?

After certificate renewal Nodes should go to Ready state.

### How can we reproduce it (as minimally and precisely as possible)?

Need setup

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

NA

### OS version

NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

please try on supported version, 1.18 is out of support. Also please provide more informaiton on how k8s was installed/configured.

**Comment by ratheeshtv** [comment]
Issue is resolved after manually generating the kubelet.conf and restarting kubelet.

RCA is in the auto refreshed client certificate (kubelet-client-current.pem)   CN was updated as hostname instead of ip address

**Comment by ehashman** [comment]
Thanks for the update!

/close
