### ISSUE TITLE
Fixing CVE in supported version patch releases

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/kubernetes#106423]
### What happened?

The jwt-go (a dependency) handling had a CVE that was fixed on master (see #100401 and #102755). This fixed the issue on master but not on the supported version release branches.

### What did you expect to happen?

I expected the issue to be fixed on master and on other supported versions of Kubernetes (1.22, 1.21, and 1.20)

### How can we reproduce it (as minimally and precisely as possible)?

Check out the release branch for 1.21 and search the dependency tree for `github.com/dgrijalva/jwt-go`. All versions of this dependency have the unpatched CVE.

### Kubernetes version

<details>
N/A
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by liggitt** [comment]
As noted in https://github.com/kubernetes/kubernetes/pull/102755, the vulnerable function is not in use. Is this an issue that affects this code base?
