### ISSUE TITLE
Move from archived jwt-go dependency to supported one

### ISSUE THREAD

**Issue by mattfarina** [kubernetes/kubernetes#106422]
### What would you like to be added?

The jwt-go dependency used at github.com/form3tech-oss/jwt-go/ is archived and no longer maintained. This was set to be used Kubernetes wide in #100401. That location is archived an no longer supported. It directs people to use https://github.com/golang-jwt/jwt instead.

The request is to move to the v3 branch of the new location which should be a drop in replacement.

### Why is this needed?

jwt-go recently had a security issue which is why k8s moved to the new location. The previous location was unmaintained and the security issue wasn't being addressed.  JWTs have had security issues in the past and can be difficult to do well. It would be useful to track a maintained upstream dependency that deals with security issues so k8s can more easily pull in fixes in the future.

**Comment by SataQiu** [comment]
Related Issue: #104007

**Comment by NikhilSharmaWe** [comment]
@mattfarina Can you confirm, what our focus here is to reverse the changes made in PR's ([1](https://github.com/etcd-io/etcd/pull/13256), [2](https://github.com/heketi/heketi/issues/1871), [3](https://github.com/heketi/heketi/pull/1872)) which were merged to 
use golang-jwt/jwt instead of form3tech-oss/jwt-go.

**Comment by dims** [comment]
now there's a https://github.com/golang-jwt/jwt/ too?

**Comment by dims** [comment]
```
[dims@dims-m1-7728 11:17] ~/go/src/k8s.io/kubernetes ⟩ go mod graph | grep form3tech-oss/jwt-go
k8s.io/kubernetes github.com/form3tech-oss/jwt-go@v3.2.3+incompatible
go.etcd.io/etcd/server/v3@v3.5.4 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible
k8s.io/apiextensions-apiserver@v0.0.0 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible
k8s.io/apiserver@v0.0.0 github.com/form3tech-oss/jwt-go@v3.2.3+incompatible
```
