### ISSUE TITLE
Whether pod deletion should enqueue the deployment again when there is only evicted pod left

### ISSUE THREAD

**Issue by Shuanglu** [kubernetes/kubernetes#106410]
### What happened?

For example, there is one deployment with below configuration. 
```
progressDeadlineSeconds: 600
replicas: 1
strategy:
   type: Recreate
```
Due to resource exhaustion on the node, the node evicted pods of this deployment. The running pod is owned by the rs 'nginx-deployment-dfbd8fcd5'
Around 13:46, the deployment is patched and due to the "recreate" strategy, the old pod started to be deleted. The deployment status is updated but nothing new which triggers the deployment is "stuck".
https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/progress.go#L111 
Because the "lastUpdateTime" + "progressDeadlineSeconds" > current time, the deployemnet is added to the "delayQueue"  
https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/progress.go#L186

the deployment "status.conditions" is below
```
   - lastTransitionTime: "2021-11-14T13:26:08Z"
      lastUpdateTime: "2021-11-14T13:44:57Z"
      message: Created new replica set "nginx-deployment-dfbd8fcd5"
      reason: NewReplicaSetCreated
      status: "True"
      type: Progressing
```
After the old pod is deleted, the deployment is still not enqueue immediately because there is still evicted pods left
https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/deployment_controller.go#L372

Whether this is expected behavior or we should continue to create new RS once old active old pod is deleted? Because in "rolloutRecreate" function, when the controller checks if there is pod pod running it doesn't count the evict pod
https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/recreate.go#L109

### What did you expect to happen?

deployment controller continues to create new rs if there is only evicted pod left 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a deployment with "recreate" strategy and trigger pod eviction
2. Patch the deployment
2. When  the "lastUpdateTime" + "progressDeadlineSeconds" > current time, even the old pod is deleted, the new rs is not created until it reaches the result of  "lastUpdateTime" + "progressDeadlineSeconds"

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
# Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux master 5.4.0-1062-azure #65~18.04.1-Ubuntu SMP Tue Oct 12 11:26:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
kubeadm
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by bg-chun** [comment]
it seems we should take effective running pod count here
https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/deployment_controller.go#L372

**Comment by Shuanglu** [comment]
> it seems we should take effective running pod count here https://github.com/kubernetes/kubernetes/blob/v1.22.3/pkg/controller/deployment/deployment_controller.go#L372

thanks! I found in 5 years ago the commit removed the filter of 'inactive pods' because it said 'Recreate Deployments need to verify that no Pods from older versions are running before spinning up new Pods'
https://github.com/kubernetes/kubernetes/commit/97fed0aff48637381edcef3b95f8d55ec4bf78d6#diff-c553184997fa4c9f63e697af2f39eb2e6fb43eeff64a0ef66c9e955f61347b02L540 
in another commit 3 years ago it added the filter for 'inactive pods' in 'recreate.go' 
https://github.com/kubernetes/kubernetes/commit/952e6c64b68b0c3bdcfb46376bd340d923dc065f#diff-c53d1f0a34c6462dc15af42d09038ed470c80ff7121fca5914ed2ccf60a8355aR109 
shall we revert the change in 1st commit?

**Comment by bg-chun** [comment]
@Shuanglu 
This https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-367786176 says that the DaemonSet controller deletes failed pod due to the issue(https://github.com/kubernetes/kubernetes/issues/36482), PR is here https://github.com/kubernetes/kubernetes/pull/40330
Not sure, ds controller sill  show the same behavior or not tho.

What i am trying to say is that `if the only matter is old rs which only have failed pod without no active pod`, I think we can make recreate deploy controller deletes it.
The only side effect will be that no evicted pod will exist.

Don't hesitate clarify my comment, I don't have full understanding of deploy controller at this moment, I will make some time to dig it's implementation weekends. :)

**Comment by Shuanglu** [comment]
> 



> @Shuanglu This [#54525 (comment)](https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-367786176) says that the DaemonSet controller deletes failed pod due to the issue(#36482), PR is here #40330 Not sure, ds controller sill show the same behavior or not tho.
> 
> What i am trying to say is that `if the only matter is old rs which only have failed pod without no active pod`, I think we can make recreate deploy controller deletes it. The only side effect will be that no evicted pod will exist.
> 
> Don't hesitate clarify my comment, I don't have full understanding of deploy controller at this moment, I will make some time to dig it's implementation weekends. :)

following the https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-367786176 you mentioned, there is a PR https://github.com/kubernetes/kubernetes/pull/60301 mentioned the design was to wait for RS controller to clean up the evicted one. Also another comment https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-367845264 discussed about 'which controller should delete'. Not sure what might be the best option here.

**Comment by avbhandaru** [comment]
Was this ever fixed?
