### ISSUE TITLE
[Flaky test] [sig-node] containerd-NodeConformance

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#106469]
### Which jobs are flaking?

containerd-NodeConformance

### Which tests are flaking?

[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api [cos-stable]

### Since when has it been flaking?

11/16/2021 13:23 PST ([first failed run link](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-containerd-node-e2e/1460720200839073792))

### Testgrid link

https://testgrid.k8s.io/sig-node-critical#containerd-NodeConformance

### Reason for failure (if possible)

The test creates two pods. After they're created, it retrieves the node stats summary via the stats API and validates such stats. However, the request times out after 90s ([source](https://github.com/kubernetes/kubernetes/blob/6805e6ee41bb31f374300c9b22b68ae64072f0ec/test/e2e_node/summary_test.go#L351)).

### Anything else we need to know?

Failures have been occurring only in commit d32be903b, which points out to https://github.com/kubernetes/kubernetes/pull/106325. However, the change seems unrelated.

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/area test
/triage accepted

We may need to spend some time looking into it

/assign @bobbypage

**Comment by mmiranda96** [comment]
It appears that this is a duplicate of https://github.com/kubernetes/kubernetes/issues/104292. Closing.
/close
