### ISSUE TITLE
make max retries of serviceaccount token controller configurable through command line options

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#106587]
### What would you like to be added?

max retries is supported in service account token controller, but it is not configurable in controller manager.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/tokens_controller.go#L70
```go
// TokensControllerOptions contains options for the TokensController
type TokensControllerOptions struct {
....
	// This CA will be added in the secrets of service accounts
	RootCA []byte

	// MaxRetries controls the maximum number of times a particular key is retried before giving up
	// If zero, a default max is used
	MaxRetries int
}
```

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/serviceaccount/config/types.go
```go
package config

// SAControllerConfiguration contains elements describing ServiceAccountController.
type SAControllerConfiguration struct {
	// serviceAccountKeyFile is the filename containing a PEM-encoded private RSA key
	// used to sign service account tokens.
	ServiceAccountKeyFile string
	// concurrentSATokenSyncs is the number of service account token syncing operations
	// that will be done concurrently.
	ConcurrentSATokenSyncs int32
	// rootCAFile is the root certificate authority will be included in service
	// account's token secret. This must be a valid PEM-encoded CA bundle.
	RootCAFile string
}
```

### Why is this needed?

there are failures on creating secrets because of issues. e.g. network, quota, etc. the max times is 10 by default and not configurable. it makes the controller only does reconciles at most around 1.5 seconds and gives up the service account. 

then the pods using that service account cannot be created because of secrets not ready.

**Comment by enj** [comment]
Cross linking my comment here: https://github.com/kubernetes/kubernetes/pull/106905#issuecomment-1054481407

**Comment by liggitt** [comment]
since secret creation by the token controller is no longer enabled by default in 1.24+, and is expected to no longer be an option in 1.27+ when the LegacyServiceAccountTokenNoAutoGeneration feature gate locks to `true`, I don't think exposing configuration knobs for this controller is necessary any more

/close
