### ISSUE TITLE
kube-apiserver crashes after updating from v1.19.12 to v1.20.12

### ISSUE THREAD

**Issue by iamejboy** [kubernetes/kubernetes#106548]
### What happened?

After updating from this version v1.19.12 to this v1.20.12 version, we noticed that kube-apiserver started to crash continuously with seeing it having high CPU. 

CPU Stats
`acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     0.00%               94.45MiB / 16GiB      0.58%               0B / 0B             0B / 0B             13
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     142.76%             318.5MiB / 16GiB      1.94%               0B / 0B             0B / 0B             13
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     142.76%             318.5MiB / 16GiB      1.94%               0B / 0B             0B / 0B             13
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     120.48%             398.4MiB / 16GiB      2.43%               0B / 0B             0B / 0B             13
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     120.48%             398.4MiB / 16GiB      2.43%               0B / 0B             0B / 0B             13
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     226.37%             553.2MiB / 16GiB      3.38%               0B / 0B             0B / 0B             14
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     226.37%             553.2MiB / 16GiB      3.38%               0B / 0B             0B / 0B             14
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     284.11%             660MiB / 16GiB        4.03%               0B / 0B             0B / 0B             14
acae24d2a0cb        k8s_kube-apiserver_kube-apiserver-jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar_kube-system_0753542ea02b4690137d79ceed9983a7_2                     284.11%             660MiB / 16GiB        4.03%               0B / 0B             0B / 0B             14`

kube-apiserver log

`I1119 04:03:44.677173       1 naming_controller.go:291] Starting NamingConditionController
I1119 04:03:44.677534       1 establishing_controller.go:76] Starting EstablishingController
I1119 04:03:44.677587       1 crdregistration_controller.go:111] Starting crd-autoregister controller
I1119 04:03:44.677597       1 shared_informer.go:240] Waiting for caches to sync for crd-autoregister
I1119 04:03:44.677699       1 nonstructuralschema_controller.go:192] Starting NonStructuralSchemaConditionController
I1119 04:03:44.677951       1 apiapproval_controller.go:186] Starting KubernetesAPIApprovalPolicyConformantConditionController
I1119 04:03:44.678161       1 crd_finalizer.go:266] Starting CRDFinalizer
I1119 04:03:44.684695       1 cluster_authentication_trust_controller.go:440] Starting cluster_authentication_trust_controller controller
I1119 04:03:44.684713       1 shared_informer.go:240] Waiting for caches to sync for cluster_authentication_trust_controller
I1119 04:03:44.685809       1 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1119 04:03:44.685930       1 dynamic_cafile_content.go:167] Starting request-header::/etc/kubernetes/ssl/ca.pem
E1119 04:03:44.697453       1 controller.go:152] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/100.94.133.12, ResourceVersion: 0, AdditionalErrorMsg: 
I1119 04:03:44.775782       1 apf_controller.go:279] Running API Priority and Fairness config worker
I1119 04:03:44.775796       1 cache.go:39] Caches are synced for AvailableConditionController controller
I1119 04:03:44.775823       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1119 04:03:44.777561       1 cache.go:39] Caches are synced for autoregister controller
I1119 04:03:44.789435       1 shared_informer.go:247] Caches are synced for cluster_authentication_trust_controller 
I1119 04:03:44.819558       1 shared_informer.go:247] Caches are synced for node_authorizer 
I1119 04:03:44.877775       1 shared_informer.go:247] Caches are synced for crd-autoregister 
I1119 04:03:45.680714       1 storage_scheduling.go:148] all system priority classes are created successfully or already exist.
I1119 04:03:46.214054       1 controller.go:132] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I1119 04:03:46.214080       1 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
W1119 04:03:46.284916       1 lease.go:233] Resetting endpoints for master service "kubernetes" to [100.94.133.12 100.94.133.4 100.94.135.129]
I1119 04:03:46.286505       1 controller.go:609] quota admission added evaluator for: endpoints
I1119 04:03:46.290641       1 controller.go:609] quota admission added evaluator for: endpointslices.discovery.k8s.io
E1119 04:03:46.588357       1 controller.go:116] loading OpenAPI spec for "v1beta1.webhook.cert-manager.io" failed with: OpenAPI spec does not exist
I1119 04:03:46.588372       1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.webhook.cert-manager.io: Rate Limited Requeue.
I1119 04:04:06.709738       1 controller.go:89] Shutting down OpenAPI AggregationController
I1119 04:04:06.709767       1 controller.go:123] Shutting down OpenAPI controller
I1119 04:04:06.709773       1 naming_controller.go:302] Shutting down NamingConditionController
I1119 04:04:06.709780       1 crdregistration_controller.go:142] Shutting down crd-autoregister controller
I1119 04:04:06.709785       1 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1119 04:04:06.709788       1 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
I1119 04:04:06.709795       1 apiservice_controller.go:131] Shutting down APIServiceRegistrationController
I1119 04:04:06.709800       1 crd_finalizer.go:278] Shutting down CRDFinalizer
I1119 04:04:06.709809       1 customresource_discovery_controller.go:245] Shutting down DiscoveryController
I1119 04:04:06.709812       1 cluster_authentication_trust_controller.go:463] Shutting down cluster_authentication_trust_controller controller
I1119 04:04:06.709779       1 dynamic_cafile_content.go:182] Shutting down request-header::/etc/kubernetes/ssl/ca.pem
I1119 04:04:06.709809       1 nonstructuralschema_controller.go:204] Shutting down NonStructuralSchemaConditionController
I1119 04:04:06.709830       1 autoregister_controller.go:165] Shutting down autoregister controller
I1119 04:04:06.709814       1 establishing_controller.go:87] Shutting down EstablishingController
I1119 04:04:06.709856       1 available_controller.go:487] Shutting down AvailableConditionController
I1119 04:04:06.709868       1 apf_controller.go:283] Shutting down API Priority and Fairness config worker
I1119 04:04:06.709873       1 dynamic_serving_content.go:145] Shutting down aggregator-proxy-cert::/etc/kubernetes/ssl/apiaggregator.pem::/etc/kubernetes/ssl/apiaggregator-key.pem
I1119 04:04:06.709884       1 dynamic_cafile_content.go:182] Shutting down request-header::/etc/kubernetes/ssl/ca.pem
I1119 04:04:06.709746       1 controller.go:181] Shutting down kubernetes service endpoint reconciler
I1119 04:04:06.709900       1 tlsconfig.go:255] Shutting down DynamicServingCertificateController
I1119 04:04:06.709960       1 dynamic_serving_content.go:145] Shutting down serving-cert::/etc/kubernetes/ssl/apiserver.pem::/etc/kubernetes/ssl/apiserver-key.pem
I1119 04:04:06.709972       1 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1119 04:04:06.710278       1 secure_serving.go:246] Stopped listening on [::]:443
E1119 04:04:06.714884       1 controller.go:184] Get "https://[::1]:443/api/v1/namespaces/default/endpoints/kubernetes": dial tcp [::1]:443: connect: connection refused`

### What did you expect to happen?

kube-apiserver should start normally

### How can we reproduce it (as minimally and precisely as possible)?

- updating from v1.19.12 to v1.20.12

### Anything else we need to know?

**Current Work Around:**
Adding this lines to kube-apiserver manifest
- --feature-gates=APIPriorityAndFairness=false
- --runtime-config=flowcontrol.apiserver.k8s.io/v1beta1=false

or

- --enable-priority-and-fairness=false

https://kubernetes.io/docs/concepts/cluster-administration/flow-control/

### Kubernetes version

<details>
v1.20.12
</details>

### Cloud provider

<details>
Baremetal
</details>

### OS version

<details>

$ cat /etc/os-release
NAME="Container Linux by CoreOS"
ID=coreos
VERSION=2135.6.0
VERSION_ID=2135.6.0
BUILD_ID=2019-07-30-0722
PRETTY_NAME="Container Linux by CoreOS 2135.6.0 (Rhyolite)"
ANSI_COLOR="38;5;75"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://issues.coreos.com"
COREOS_BOARD="amd64-usr"

$ uname -a

Linux jpe1-caas1-alpha1-master-000001.caas.jpe1z.dcnw.foobar 4.19.56-coreos-r1 #1 SMP Tue Jul 30 06:40:10 -00 2019 x86_64 Intel(R) Xeon(R) CPU E3-1240 v3 @ 3.40GHz GenuineIntel GNU/Linux
</details>

### Install tools

<details>
In-house tool similar to kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
# docker version

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d7080c1
  Built:            Tue Feb 19 23:07:53 2019
  OS/Arch:          linux/amd64
  Experimental:     true
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
# calicoctl version

Client Version:    v3.12.0
Git commit:        84a21b3b
Cluster Version:   v3.12.3
Cluster Type:      typha,kdd,k8s,bgp
</details>

**Comment by fedebongio** [comment]
/assign @MikeSpreitzer @tkashem 
Seems to be related to P&F
/triage accepted

**Comment by aojea** [comment]
> loading OpenAPI spec for "v1beta1.webhook.cert-manager.io" failed with: OpenAPI spec does not exist I1119 04:03:46.588372 1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.webhook.cert-manager.io: Rate Limited Requeue. I1119 04:04:06.709738 1 controller.go:89] Shutting down OpenAPI AggregationController I1119 04:04:06.709767 1 controller.go:123] Shutting down OpenAPI controller I1119 04:04:06.709773 1 naming_controller.go:302] 

this webhook error message looks suspicious

**Comment by iamejboy** [comment]
> > loading OpenAPI spec for "v1beta1.webhook.cert-manager.io" failed with: OpenAPI spec does not exist I1119 04:03:46.588372 1 controller.go:129] OpenAPI AggregationController: action for item v1beta1.webhook.cert-manager.io: Rate Limited Requeue. I1119 04:04:06.709738 1 controller.go:89] Shutting down OpenAPI AggregationController I1119 04:04:06.709767 1 controller.go:123] Shutting down OpenAPI controller I1119 04:04:06.709773 1 naming_controller.go:302]
> 
> this webhook error message looks suspicious

We have managed to fixed that but it didn't resolved the issue. here is new log before api dies.
`I1203 07:16:49.056279       1 shared_informer.go:240] Waiting for caches to sync for cluster_authentication_trust_controller
I1203 07:16:49.056305       1 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1203 07:16:49.056328       1 dynamic_cafile_content.go:167] Starting request-header::/etc/kubernetes/ssl/ca.pem
I1203 07:16:49.056338       1 autoregister_controller.go:141] Starting autoregister controller
I1203 07:16:49.056345       1 cache.go:32] Waiting for caches to sync for autoregister controller
I1203 07:16:49.055866       1 apiservice_controller.go:97] Starting APIServiceRegistrationController
I1203 07:16:49.056391       1 cache.go:32] Waiting for caches to sync for APIServiceRegistrationController controller
I1203 07:16:49.056763       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I1203 07:16:49.070727       1 crdregistration_controller.go:111] Starting crd-autoregister controller
I1203 07:16:49.070743       1 shared_informer.go:240] Waiting for caches to sync for crd-autoregister
E1203 07:16:49.070776       1 controller.go:152] Unable to remove old endpoints from kubernetes service: StorageError: key not found, Code: 1, Key: /registry/masterleases/100.94.135.129, ResourceVersion: 0, AdditionalErrorMsg: 
I1203 07:16:49.155905       1 apf_controller.go:279] Running API Priority and Fairness config worker
I1203 07:16:49.156077       1 cache.go:39] Caches are synced for AvailableConditionController controller
I1203 07:16:49.156664       1 shared_informer.go:247] Caches are synced for cluster_authentication_trust_controller 
I1203 07:16:49.157035       1 cache.go:39] Caches are synced for autoregister controller
I1203 07:16:49.157037       1 cache.go:39] Caches are synced for APIServiceRegistrationController controller
I1203 07:16:49.181228       1 shared_informer.go:247] Caches are synced for node_authorizer 
I1203 07:16:49.272838       1 shared_informer.go:247] Caches are synced for crd-autoregister 
I1203 07:16:50.055917       1 controller.go:132] OpenAPI AggregationController: action for item : Nothing (removed from the queue).
I1203 07:16:50.055945       1 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
I1203 07:16:50.059584       1 storage_scheduling.go:148] all system priority classes are created successfully or already exist.
W1203 07:16:50.270516       1 lease.go:233] Resetting endpoints for master service "kubernetes" to [100.94.133.12 100.94.133.4 100.94.135.129]
I1203 07:16:50.272490       1 controller.go:609] quota admission added evaluator for: endpoints
I1203 07:16:50.276291       1 controller.go:609] quota admission added evaluator for: endpointslices.discovery.k8s.io
I1203 07:17:20.327471       1 client.go:360] parsed scheme: "passthrough"
I1203 07:17:20.327512       1 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}
I1203 07:17:20.327522       1 clientconn.go:948] ClientConn switching balancer to "pick_first"
I1203 07:17:23.683595       1 controller.go:89] Shutting down OpenAPI AggregationController
I1203 07:17:23.683631       1 controller.go:181] Shutting down kubernetes service endpoint reconciler
I1203 07:17:23.683654       1 apf_controller.go:283] Shutting down API Priority and Fairness config worker
I1203 07:17:23.683685       1 dynamic_cafile_content.go:182] Shutting down request-header::/etc/kubernetes/ssl/ca.pem
I1203 07:17:23.683714       1 dynamic_cafile_content.go:182] Shutting down request-header::/etc/kubernetes/ssl/ca.pem
I1203 07:17:23.683718       1 controller.go:123] Shutting down OpenAPI controller
I1203 07:17:23.683722       1 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1203 07:17:23.683731       1 dynamic_serving_content.go:145] Shutting down aggregator-proxy-cert::/etc/kubernetes/ssl/apiaggregator.pem::/etc/kubernetes/ssl/apiaggregator-key.pem
I1203 07:17:23.683739       1 crdregistration_controller.go:142] Shutting down crd-autoregister controller
I1203 07:17:23.683750       1 customresource_discovery_controller.go:245] Shutting down DiscoveryController
I1203 07:17:23.683759       1 establishing_controller.go:87] Shutting down EstablishingController
I1203 07:17:23.683768       1 apiapproval_controller.go:198] Shutting down KubernetesAPIApprovalPolicyConformantConditionController
I1203 07:17:23.683779       1 nonstructuralschema_controller.go:204] Shutting down NonStructuralSchemaConditionController
I1203 07:17:23.683789       1 crd_finalizer.go:278] Shutting down CRDFinalizer
I1203 07:17:23.683798       1 naming_controller.go:302] Shutting down NamingConditionController
I1203 07:17:23.683838       1 autoregister_controller.go:165] Shutting down autoregister controller
I1203 07:17:23.683846       1 cluster_authentication_trust_controller.go:463] Shutting down cluster_authentication_trust_controller controller
I1203 07:17:23.683858       1 available_controller.go:487] Shutting down AvailableConditionController
I1203 07:17:23.683924       1 tlsconfig.go:255] Shutting down DynamicServingCertificateController
I1203 07:17:23.683731       1 apiservice_controller.go:131] Shutting down APIServiceRegistrationController
I1203 07:17:23.683941       1 dynamic_cafile_content.go:182] Shutting down client-ca-bundle::/etc/kubernetes/ssl/ca.pem
I1203 07:17:23.683945       1 dynamic_serving_content.go:145] Shutting down serving-cert::/etc/kubernetes/ssl/apiserver.pem::/etc/kubernetes/ssl/apiserver-key.pem
I1203 07:17:23.684087       1 secure_serving.go:246] Stopped listening on [::]:443
E1203 07:17:23.687139       1 controller.go:184] Get "https://[::1]:443/api/v1/namespaces/default/endpoints/kubernetes": dial tcp [::1]:443: connect: connection refused`

**Comment by iamejboy** [comment]
Fixed. Need to add "scheme: https" to liveliness probe on kube-apiserver yaml, since from v1.20, insecure port is no longer supported.
