### ISSUE TITLE
in '/usr/local/lib/libxar.1.dylib', file was built for unsupported file format

### ISSUE THREAD

**Issue by cglong** [kubernetes/kubernetes#106572]
### What happened?

I'm trying to build kubectl on macOS 10.13 [using Homebrew](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/kubernetes-cli.rb). I'm getting this error:

```console
+++ [1120 06:25:26] Building go targets for darwin/amd64:
    cmd/kubectl
# k8s.io/kubernetes/cmd/kubectl
/usr/local/Cellar/go@1.16/1.16.10/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: in '/usr/local/lib/libxar.1.dylib', file was built for unsupported file format ( 0xFE 0xED 0xFA 0xCE 0x00 0x00 0x00 0x12 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x06 ) which is not the architecture being linked (x86_64): /usr/local/lib/libxar.1.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

!!! [1120 06:26:15] Call tree:
!!! [1120 06:26:15]  1: /private/tmp/kubernetes-cli-20211120-88618-1vgba8c/hack/lib/golang.sh:726 kube::golang::build_some_binaries(...)
!!! [1120 06:26:15]  2: /private/tmp/kubernetes-cli-20211120-88618-1vgba8c/hack/lib/golang.sh:870 kube::golang::build_binaries_for_platform(...)
!!! [1120 06:26:15]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1120 06:26:15] Call tree:
!!! [1120 06:26:15]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [1120 06:26:15] Call tree:
!!! [1120 06:26:15]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [all] Error 1
```

The whole log is available here: [01.log](https://github.com/kubernetes/kubernetes/files/7575150/01.log). I apologize for the lack of detail (I'm very new to Kubernetes), but will do whatever I can to help get this resolved! 🙂

### What did you expect to happen?

kubectl to build successfully

### How can we reproduce it (as minimally and precisely as possible)?

Run `brew install --build-from-source kubernetes-cli`, likely on an older system

### Anything else we need to know?

I thought this was interesting, especially since I bought this Mac in 2011:

```console
$ ls -l /usr/local/lib/libxar.1.dylib
-r--r--r--  1 root  staff  313892 Dec 28  2007 /usr/local/lib/libxar.1.dylib
```

### Kubernetes version

N/A

### Cloud provider

N/A, local machine

### OS version

<details>

```console
$ uname -a
Darwin gMac.local 17.7.0 Darwin Kernel Version 17.7.0: Mon Aug 31 22:11:23 PDT 2020; root:xnu-4570.71.82.6~1/RELEASE_X86_64 x86_64
```

</details>

### Install tools

<details>
Homebrew
</details>

### Container runtime (CRI) and and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by eddiezane** [comment]
Cheers @cglong,

> macOS: 10.13.6-x86_64

I think your version of macOS is [EOL as of Dec 2020](https://endoflife.date/macos). Your system libraries are probably not compatible with new build toolchains.

Is there something specific you're trying to do by building from source?

**Comment by eddiezane** [comment]
I'm going to close this because I think that's the issue but feel free to respond here or reach out to me on the Kubernetes Slack and we can dig in more.

/triage support
/close

**Comment by cglong** [comment]
> I think your version of macOS is [EOL as of Dec 2020](https://endoflife.date/macos). Your system libraries are probably not compatible with new build toolchains.

Yeah that's what I was afraid of 😕 BTW that's a really cool site; I'm definitely going to use it going forward!

> Is there something specific you're trying to do by building from source?

No, nothing specific. Homebrew only provides binaries for OSes supported by Apple, so building from source is usually my only option.

> feel free to respond here or reach out to me on the Kubernetes Slack and we can dig in more.

Thank you, I appreciate that! I think probably the first step would be to try successively older versions until I find one that builds; let me know if you have any other suggestions as well 🙂

**Comment by cglong** [comment]
Hi @eddiezane, after trying to build old versions, it looks like the LKG for me is v1.20.4 and that the issue started occurring between then and v1.21.0.

I see now that v1.20 is still receiving bug fixes for three more months. Would you recommend I try to switch to a more recent patch release there, or do you think we can try to get a fix into v1.22?

**Comment by cglong** [comment]
I was just able to successfully build v1.20.13, so yeah there's definitely been a change in the v1.21 branch causing this.

**Comment by eddiezane** [comment]
The jump from 1.20 to 1.21 added support for macOS ARM64 so I imagine there were changes to Go's toolchain. Probably something to do with the linker.

That version should be fine for most clusters. If you run into compatibility issues I'd recommend using a container/vm/cloudshell.

You can also try to build it manually without the makefile. Looks like 10.13 is still support in [go1.17](https://go.dev/dl/). Try with and without CGO.

```
CGO_ENABLED=0 go build ./cmd/kubectl
```

Also have you tried downloading the latest binary itself? They should be statically built https://www.downloadkubernetes.com/ https://dl.k8s.io/v1.22.4/bin/darwin/amd64/kubectl

**Comment by cglong** [comment]
> The jump from 1.20 to 1.21 added support for macOS ARM64 so I imagine there were changes to Go's toolchain.

Thank you @eddiezane; yeah that makes total sense that this would happen as part of that work 🙁

> That version should be fine for most clusters.

That's great to hear honestly! I'm mostly using `kubectl` on this machine for just learning Kubernetes, so it should be fine for my needs 😄

> You can also try to build it manually without the makefile. Looks like 10.13 is still support in go1.17. Try with and without CGO.

Just verified that it builds and runs successfully both with and without cgo!

> Also have you tried downloading the latest binary itself?

Yeah, just tried and verified the binary itself works too 🎉

**Comment by cglong** [comment]
Out of curiosity, I just tried running `make WHAT=cmd/kubectl` from outside Homebrew and that built successfully too. So I guess this is actually being caused by something in the shims that Homebrew adds 😕
