### ISSUE TITLE
pull-kubernetes-kubemark-e2e-gce-scale fails

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#106517]
### Which jobs are failing?

pull-kubernetes-kubemark-e2e-gce-scale

### Which tests are failing?

ClusterLoaderV2: load

### Since when has it been failing?

Not sure, we just got past failures to gather enough information.

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kubemark-e2e-gce-scale

### Reason for failure (if possible)

First case:
There may be other reasons for the failure, but one I tracked down is that the PVs associated with statefulsets have node affinity constraints that are not met by any non-master node.  See https://github.com/kubernetes/kubernetes/pull/105768#issuecomment-972465085 and subsequent comments.

Second case:
I investigated one pod that failed to run and found that the PVC never got bound and the kube-controller-manager logged a complaint about the PVC having no storage class.  See https://github.com/kubernetes/kubernetes/pull/106413#issuecomment-974754511 and subsequent comments.

### Relevant SIG(s)

/sig scalability

**Comment by MikeSpreitzer** [comment]
It looks like #106413 also showed the same symptom.  See https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106413/pull-kubernetes-kubemark-e2e-gce-scale/1461164903535480832

**Comment by wojtek-t** [comment]
Will be fixed by https://github.com/kubernetes/test-infra/pull/24432
