### ISSUE TITLE
[Pod Security] Document Pod Security code structure & extension points

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#106561]
The Pod Security admission controller was designed to be extensible. We should add a markdown file to the k8s.io/pod-security-admission repo that documents the recommended extension points and gives an overview of the code structure.

/sig auth
/kind documentation

**Comment by sftim** [comment]
If anyone's tackling this, https://github.com/kubernetes/pod-security-admission could also use a nicer README (consider linking to the docs for Pod Security admission, too)
