### ISSUE TITLE
[Failing test] integration-master

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#106573]
### Which jobs are failing?

integration-master

### Which tests are failing?

- ci-kubernetes-integration-master.OverallChanges
- k8s.io/kubernetes/test/integration/apiserver.TestMaxResourceSizeChanges
- k8s.io/kubernetes/test/integration/apiserver.TestMaxResourceSize/MergePatchType_should_handle_a_patch_just_under_the_max_limitChanges
- k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration.TestLimitsChanges
- k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration.TestLimits/MergePatchType_nested_patch_under_limit

### Since when has it been failing?

11/19/2021 23:54 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

see this [run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1462209802313666560) as example to get information about the failure

**Comment by aojea** [comment]
great catch @leonardpahlke 
/sig api-machinery
/priority critical-urgent

@liggitt it seems all tests fail with

> E1120 06:26:23.531632  118423 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"Invalid JSON Patch"}: Invalid JSON Patch

how can this fail consistently only in periodics and not in presubmits? is an external dependency?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestMaxResourceSize

**Comment by aojea** [comment]
I would say this is the origin https://github.com/kubernetes/kubernetes/pull/105916

**Comment by liggitt** [comment]
presubmits only run short tests, periodics run all long ones... looking if there's a long test that needs fixup

**Comment by liggitt** [comment]
fix in https://github.com/kubernetes/kubernetes/pull/106576
