### ISSUE TITLE
failed calling webhook - connection reset by peer 

### ISSUE THREAD

**Issue by IlyaBiryukov** [kubernetes/kubernetes#106509]
### What happened?

Our Azure AKS cluster had ingress object admission validating web hook configured for nginx. Nginx webhook was exposed as a K8S service in `default` namespace, with a self-signed cert. The  `ValidatingWebhookConfiguration` had appropriate `caBundle` and the webhook worked fine.
```
default namespace:

   ValidatingWebhookConfiguration
     webhooks.clientConfig.service
       name: nginx-ingress-controller-admission
       namespace: default
    
  nginx-ingress-controller-admission service -> webhook ports on nginx pods
```

Recently we changed the  namespace of the K8S service that webhook configuration uses and it is now in `vsclk` namespace. The new service proxies to `default` namespace. We needed to do this because the TLS cert for the webhook has changed and the new one cannot have `default.svc` domain name, but is OK with `vsclk.svc`.
```
default namespace:

   ValidatingWebhookConfiguration
     webhooks.clientConfig.service
       name: nginx-ingress-controller-admission
       namespace: vsclk

   nginx-ingress-controller-admission service -> webhook ports on nginx pods

vsclk namespace:

   nginx-ingress-controller-admission service
      spec:
        type: ExternalName
        externalName: nginx-ingress-controller-admission.default.svc.cluster.local
        ports:
          - name: https-webhook
            port: 443
```

Now K8S fails to call the webhook with the following error. The nginx admission conroller is not invoked, I don't see any handling of admission requests in nginx controller pod logs:
```
kubectl apply --dry-run=server -f ingress.yaml --v=7
...
I1117 14:10:27.270256    5148 round_trippers.go:448] Response Status: 500 Internal Server Error in 80 milliseconds
I1117 14:10:27.271263    5148 helpers.go:216] server response object: [{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error when creating \".\\\\ingress.yaml\": Internal error occurred: failed calling webhook \"validate.nginx.ingress.kubernetes.io\": Post \"https://nginx-ingress-controller-admission.vsclk.svc:443/networking/v1/ingresses?timeout=10s\": read unix @-\u003e/tunnel-uds/socket: read: connection reset by peer",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "failed calling webhook \"validate.nginx.ingress.kubernetes.io\": Post \"https://nginx-ingress-controller-admission.vsclk.svc:443/networking/v1/ingresses?timeout=10s\": read unix @-\u003e/tunnel-uds/socket: read: connection reset by peer"
      }
    ]
  },
  "code": 500
}]
...
```

Running `curl -X POST https://nginx-ingress-controller-admission.vsclk.svc:443/networking/v1/ingresses --insecure --verbose` in pods in `kube-system` namespace is fine - it returns expected HTTP response, and there are entries in the nginx controller pod logs for handling admission requests from `curl` requests.

So I suspect the issue is in K8S admission controller.

### What did you expect to happen?

1. The admission web hook should be called, and let in correct ingress objects or reject incorrect one.
2. The client can get better diagnostics from the admission controller: what IP address did it try to use when it called the webhook, and what raw response, if any, it got from the webhook.
3. Have more docs on how to troubleshoot this kind of issues. E.g. is there a way to get the logs of the admission controller? Change the logs verbosity? Can the admission-controller be restarted?
4. Is there any workaround? E.g. restarting admission-controller.

### How can we reproduce it (as minimally and precisely as possible)?

Use admission web hook configuration with client config that points to a K8S service in one namespace, which in time references another K8S service in a different namespace with `spec.type: ExternalName` and `externalName: {service}.{namespace}.svc.cluster.local`

### Anything else we need to know?

There is only one network policy in the cluster. `kubectl get NetworkPolicy --all-namespaces`
```
NAMESPACE     NAME                 POD-SELECTOR             AGE
kube-system   konnectivity-agent   app=konnectivity-agent   48d
```

The policy details `kubectl describe NetworkPolicy konnectivity-agen -n kube-system`
```
Name:         konnectivity-agent
Namespace:    kube-system
Created on:   2021-09-29 20:47:18 -0700 PDT
Labels:       addonmanager.kubernetes.io/mode=Reconcile
Annotations:  <none>
Spec:
  PodSelector:     app=konnectivity-agent
  Not affecting ingress traffic
  Allowing egress traffic:
    To Port: <any> (traffic allowed to all ports)
    To: <any> (traffic not restricted by destination)
  Policy Types: Egress
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"c612f9dcf9cf5f6fda3ba3cd1c53b118c897f6c7", GitTreeState:"clean", BuildDate:"2021-10-21T03:30:46Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AKS cluster
</details>

### OS version

<details>

```
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
22000        Microsoft Windows 11 Enterprise  64-bit          10.0.22000
```

</details>

### Install tools

<details>
The nginx controller, services, and webhook configuration are installed with Helm 3.5.4
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

All Azure Kuberenetes addons are disabled.

```
az aks addon list ...
[
  {
    "api_key": "httpApplicationRouting",
    "enabled": false,
    "name": "http_application_routing"
  },
  {
    "api_key": "omsagent",
    "enabled": false,
    "name": "monitoring"
  },
  {
    "api_key": "aciConnector",
    "enabled": false,
    "name": "virtual-node"
  },
  {
    "api_key": "azurepolicy",
    "enabled": false,
    "name": "azure-policy"
  },
  {
    "api_key": "kubeDashboard",
    "enabled": false,
    "name": "kube-dashboard"
  },
  {
    "api_key": "ingressApplicationGateway",
    "enabled": false,
    "name": "ingress-appgw"
  },
  {
    "api_key": "openServiceMesh",
    "enabled": false,
    "name": "open-service-mesh"
  },
  {
    "api_key": "ACCSGXDevicePlugin",
    "enabled": false,
    "name": "confcom"
  },
  {
    "api_key": "gitops",
    "enabled": false,
    "name": "gitops"
  },
  {
    "api_key": "azureKeyvaultSecretsProvider",
    "enabled": false,
    "name": "azure-keyvault-secrets-provider"
  }
]
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

```
Type (plugin):              Azure CNI
Service CIDR:               10.0.0.0/16
DNS service IP:            10.0.0.10
Docker bridge CIDR :  172.17.0.1/16
Network policy:           None

Traffic routing
Load balancer:             Standard
```

</details>

**Comment by aojea** [comment]
This is a complicated setup, so you are using an ExternalName service to redirect the traffic and keep the SNI authentication working. Just as a note, ExternalName service only generates a CNAME dns record, doesn't perform any traffic load balancing, so is the client resolver that has to do the recursive resolving to find the IP of the service.

So far so good, the error seems to be related to the [konnectivity agent ](https://kubernetes.io/docs/tasks/extend-kubernetes/setup-konnectivity/) ,

> "message": "failed calling webhook \"validate.nginx.ingress.kubernetes.io\": Post \"https://nginx-ingress-controller-admission.vsclk.svc:443/networking/v1/ingresses?timeout=10s\": read unix @-\u003e/tunnel-uds/socket: read: connection reset by peer"

maybe the konnectivity agent is not able to resolve correctly the service?

/sig api-machinery
/cc @caesarxuchao

**Comment by leilajal** [comment]
/assign @aojea thanks for your comment. please let us know if you need further help.
//triage accepted

**Comment by ejderdal** [comment]
We have this issue also in one of our AKS clusters. But our Ingress controller was already running in a separate namespace from `kube-system`. The issue seem to have started when they replaced the `tunnelfront` proxy with the `konnectivity` agent.

Besides Nginx, other admission controller webhooks fail with the same error.

2 days ago, they upgraded konnectivity agent from
`mcr.microsoft.com/oss/kubernetes/apiserver-network-proxy/agent:v0.0.24`
to
`mcr.microsoft.com/oss/kubernetes/apiserver-network-proxy/agent:v0.0.24-hotfix.20211027`

but the issue remains. The only difference I can see is additional logging in the konnectivity agent.
```
I1119 08:48:55.960413       1 client.go:512] "Exiting proxyToRemote" connectionID=2467
E1119 08:48:55.960471       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:52250->10.181.40.126:10091: use of closed network connection" connectionID=2467
I1119 08:48:55.960489       1 client.go:474] "Exiting remoteToProxy" connectionID=2467
E1119 08:49:46.385307       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:48610->10.181.40.4:10256: use of closed network connection" connectionID=272
I1119 08:49:46.385368       1 client.go:474] "Exiting remoteToProxy" connectionID=272
I1119 08:49:46.385737       1 client.go:512] "Exiting proxyToRemote" connectionID=272
E1119 08:49:47.186167       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:49264->10.181.40.126:10256: use of closed network connection" connectionID=273
I1119 08:49:47.186218       1 client.go:474] "Exiting remoteToProxy" connectionID=273
I1119 08:49:47.186243       1 client.go:512] "Exiting proxyToRemote" connectionID=273
E1119 08:49:49.217821       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:46484->10.181.40.4:10257: use of closed network connection" connectionID=2469
I1119 08:49:49.218056       1 client.go:474] "Exiting remoteToProxy" connectionID=2469
I1119 08:49:49.217896       1 client.go:512] "Exiting proxyToRemote" connectionID=2469
E1119 08:50:35.190273       1 client.go:529] "conn write failure" err="write tcp 10.181.40.4:47760->10.250.168.211:443: use of closed network connection" connectionID=271
I1119 08:50:35.190575       1 client.go:512] "Exiting proxyToRemote" connectionID=271
E1119 08:50:35.190314       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:47760->10.250.168.211:443: use of closed network connection" connectionID=271
I1119 08:50:35.190688       1 client.go:474] "Exiting remoteToProxy" connectionID=271
E1119 08:50:47.228870       1 client.go:529] "conn write failure" err="write tcp 10.181.40.4:52080->10.250.193.243:443: use of closed network connection" connectionID=2470
I1119 08:50:47.229021       1 client.go:512] "Exiting proxyToRemote" connectionID=2470
E1119 08:50:47.228903       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:52080->10.250.193.243:443: use of closed network connection" connectionID=2470
I1119 08:50:47.229101       1 client.go:474] "Exiting remoteToProxy" connectionID=2470
E1119 08:51:07.327761       1 client.go:529] "conn write failure" err="write tcp 10.181.40.4:52120->10.250.193.243:443: use of closed network connection" connectionID=274
E1119 08:51:07.327782       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:52120->10.250.193.243:443: use of closed network connection" connectionID=274
I1119 08:51:07.327834       1 client.go:512] "Exiting proxyToRemote" connectionID=274
I1119 08:51:07.327844       1 client.go:474] "Exiting remoteToProxy" connectionID=274
E1119 08:53:26.728983       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:33320->10.181.40.31:9153: use of closed network connection" connectionID=2471
I1119 08:53:26.729039       1 client.go:474] "Exiting remoteToProxy" connectionID=2471
I1119 08:53:26.729065       1 client.go:512] "Exiting proxyToRemote" connectionID=2471
E1119 08:53:33.942107       1 client.go:493] "connection read failure" err="read tcp 10.181.40.4:36720->10.181.40.65:10249: use of closed network connection" connectionID=2472
I1119 08:53:33.942500       1 client.go:474] "Exiting remoteToProxy" connectionID=2472
I1119 08:53:33.942196       1 client.go:512] "Exiting proxyToRemote" connectionID=2472
```

**Comment by aojea** [comment]
>  The issue seem to have started when they replaced the tunnelfront proxy with the konnectivity agent.

That is an important detail, I'm not very familiar with that component, let me ping @cheftako maybe he can redirect us to the right person
/unassign

**Comment by uablrek** [comment]
I have had a similar problem when deploying a cluster where the K8s api-server is running outside the cluster (there are no "master" nodes). IMHO that is a very convenient setup since you isolate the K8s processes (with HA and what-not) from the workers. I think AWS has that type of setup, you define a cluster and can configure it and check it and _then_ you add some workers.

Anyway, back to the problem; when I deploy Cilium in this way webhooks doesn't work, please see [issue](https://github.com/cilium/cilium/issues/13406).
