### ISSUE TITLE
Debugging high controller-manager workqueue_retries_total

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#106513]
We are seeing 1-1 workqueue_adds_total to workqueue_retries_total in our clusters, that seems bad (why would everything need to be retried) so I tried looking into debugging this but could not get anything useful even with `-v 4`.

Found https://www.jaegertracing.io/docs/1.27/operator/ which suggests 10% being bad.

- How would I start debugging this ?
- What is an unhealthy amount of retries compared to adds ?

**Comment by NikhilSharmaWe** [comment]
I would like to collaborate. Could Please someone elaborate what we are trying to achieve here because there is not much information about that.

**Comment by grosser** [comment]
`adds` afaik is how many items get queues
`retries` afaik is how often an item is retried
the goal would be to have some instructions to say "if you see >10% retries then follow these steps to find out what is going on"
