### ISSUE TITLE
[Flaky] TestDifferentWidths

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#106579]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestDifferentWidths

### Since when has it been flaking?

As far back as triage board history shows

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Anything else we need to know?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106568/pull-kubernetes-unit/1462441951197401088

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestDifferentWidths

### Relevant SIG(s)

/sig api-machinery

**Comment by lavalamp** [comment]
/reopen

I got this in https://github.com/kubernetes/kubernetes/pull/113985 -- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113985/pull-kubernetes-unit/1603098592694767616

```
    queueset_test.go:348: TestDifferentWidths client 0 last=true expectFair=true margin=0.15 got an Average of 2.549999999 but the expected average was 3
    queueset_test.go:350: TestDifferentWidths client 1 last=true expectFair=true margin=0.15 got an Average of 3.099999996 and the expected average was 3
    queueset_test.go:357: TestDifferentWidths last=true got duration of 20 and expected 20
    queueset_test.go:362: TestDifferentWidths last=true got SeatDemand average of 21.599999457100008 and expected 21.599999457100008
    queueset_test.go:367: TestDifferentWidths last=true got SeatDemand standard deviation of 1.3190917286449542 and expected 1.3190917286449542
```

**Comment by MadhavJivrajani** [comment]
/reopen
Got this in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115096/pull-kubernetes-unit/1614904422679187456
