### ISSUE TITLE
Unable to create PVC in ARO using NFS CSI - error parameter=client.SubscriptionID constraint=MinLength value=""

### ISSUE THREAD

**Issue by svoruga** [kubernetes/kubernetes#106543]
### What happened?

We are trying to use the new NFS/Azurefiles preview:
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-how-to-create-nfs-shares?tabs=azure-cli
Use Container Storage Interface (CSI) drivers for Azure Files on Azure Kubernetes Service (AKS) - Azure Kubernetes Service

We are using the following to create the storage class:
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-nfs
provisioner: file.csi.azure.com
parameters:
  resourceGroup: xxx
  storageAccount: yyy
  shareName: zzz
  server: yyy.privatelink.file.core.windows.net
  protocol: nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload

--------------------
Wehn we run the example statefulset:
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azurefile
  labels:
    app: nginx
spec:
  serviceName: statefulset-azurefile
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: statefulset-azurefile
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(date) >> /mnt/azurefile/outfile; sleep 1; done
          volumeMounts:
            - name: persistent-storage
              mountPath: /mount/aroazurefilessa3/data-nfs
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: example
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: azurefile-csi-nfs
      spec:
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 100Gi
-----------------------
We get the following error - the PVC get this error
PersistentVolumeClaimPVCpersistent-storage-statefulset-azurefile-0NamespaceNScpd-instance
Just now
Generated from file.csi.azure.com_cp4d-nfs-96kk2-worker-westus22-7r5pw_314dba70-8444-49b1-bba4-f533b8977217
10 times in the last 6 minutes
failed to provision volume with StorageClass "azurefile-csi-nfs": rpc error: code = Internal desc = storage.FileSharesClient#Get: Invalid input: autorest/validation: validation failed: parameter=client.SubscriptionID constraint=MinLength value="" details: value length must be greater than or equal to 1
------------------
We updated the azure-cloud-provider secret with the tenantid, subscriptionId etc,..
----------------
When we create a PV and PVC using the UI, it works fine. 

### What did you expect to happen?

The PV and PVC s are created without issues

### How can we reproduce it (as minimally and precisely as possible)?

yamls are provided

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Openshift 4.8

### Cloud provider

<details>

</details>
Azure - ARO

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> Use Container Storage Interface (CSI) drivers for Azure Files on Azure Kubernetes Service (AKS) - Azure Kubernetes Service

you might have to first contact azure support or the CSI driver maintainers for feedback of the problem.
i don't immediately see why this is a core k8s problem.

/sig storage cloud-provider
/area provider/azure

**Comment by svoruga** [comment]
We are trying this on ARO

**Comment by bridgetkromhout** [comment]
Hi, @svoruga!

1) Azure Red Hat Openshift does not support the Azure Files CSI driver currently; this is the documentation on what they currently support: https://docs.microsoft.com/en-us/azure/openshift/howto-create-a-storageclass
2) It is possible that opening a support issue at https://azure.microsoft.com/en-us/support/options/ will get you some ideas but that will be best-effort as this scenario is not yet supported.
3) You can also ask in https://github.com/kubernetes-sigs/azurefile-csi-driver/issues to reach the open source project.

Because this is not a k/k topic, we may want to close this issue after you open one that works better for you. Thanks!

**Comment by KyWa** [comment]
I would like to chime in here as this is essentially what we are trying to do as well. The [Azure Files provisioner](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/azure_file/azure_provision.go#L234) is hard coded to use SMB protocol for provisioning when Azure Files does support NFS volumes. I was going to open a feature request for this or possibly even a PR if I had an Azure account to test with. The logic seems simple enough to have the provisioner have a "protocol" field in its spec, but it seems as if Azure doesn't want that to try and force everyone to use AKS.

**Comment by andyzhangx** [comment]
Azure File CSI driver supports nfs protocol: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/nfs, and this doc may be helpful: https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/718

**Comment by elmiko** [comment]
hi @svoruga , this feature is still in tech preview for openshift container platform. once it has landed into a general availability realse of ocp, it will be added to the aro platform. i am not sure which specific release of ocp that will be, but it should be coming within the next 2-3.

**Comment by bridgetkromhout** [comment]
> hi @svoruga , this feature is still in tech preview for openshift container platform. once it has landed into a general availability realse of ocp, it will be added to the aro platform. i am not sure which specific release of ocp that will be, but it should be coming within the next 2-3.

Thanks, @elmiko! Hi, @svoruga - please see https://docs.microsoft.com/en-us/azure/openshift/howto-create-a-storageclass#change-the-default-storageclass-optional for where updates will occur when OCP/ARO support is updated. I'm going to close this issue in k/k now. 

/close
