### ISSUE TITLE
kube-scheduler has race conditions during cache refresh

### ISSUE THREAD

**Issue by tanjing2020** [kubernetes/kubernetes#106545]
### What happened?
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/eventhandlers.go#L212
if oldPod.UID != newPod.UID {
		sched.deletePodFromCache(oldObj)
		sched.addPodToCache(newObj)
		return
	}
Both deletePodFromCache and addPodToCache operate on the internal cache of the scheduler, and will grab and release the lock respectively.
Here should be the scenario where the POD is deleted and created in a very short time, the scheduler will be merged into a POD update event to trigger the cache update. However, because it is not an atomic operation, another POD scheduling may be triggered between delete and add, resulting in an error in the calculation of the node resource plug-in, and no resources are actually available after the POD is scheduled to the node.

### What did you expect to happen?

Keep atomic operations and eliminate competition. 

### How can we reproduce it (as minimally and precisely as possible)?

Code analysis

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.22.1
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jonyhy96** [comment]
IMO, pod is insert into `SchedulingQueue` before it really been scheduled(running the node resource plug-in), it is a sequence behavior so it won't cause mis calculation of node resource allocable. IIRC

**Comment by tanjing2020** [comment]
![image](https://user-images.githubusercontent.com/73930840/142798343-d4422633-0073-4852-a597-07f544bdcd59.png)

**Comment by Goend** [comment]
pod should be in SchedulingQueue when parpare its node,in fact ,It get one pod from activeQ and decides which node to  scheduled

**Comment by ahg-g** [comment]
We should have a pod "replace" function that removes then adds back the pod while holding the lock.

**Comment by alculquicondor** [comment]
Does this only happens when there is a 2nd scheduler? Otherwise I don't see how the recreated node would be assigned to a node without passing through the queues first.

**Comment by Huang-Wei** [comment]
> Does this only happens when there is a 2nd scheduler? Otherwise I don't see how the recreated node would be assigned to a node without passing through the queues first.

The corner case was described in #85726.

**Comment by BinacsLee** [comment]
> The corner case was described in #85726. Or simplified repro steps here: https://github.com/kubernetes/kubernetes/pull/91126/files#r425542977

+1
