### ISSUE TITLE
Test should be demoted from Conformance: [sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#106512]
Related:
- Noticed this as part of https://github.com/kubernetes/kubernetes/issues/106506
- Opened in response to: https://github.com/kubernetes/kubernetes/issues/106506#issuecomment-972164628

According to our [rules for Conformance tests](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md), the `[sig-node] Events should be sent by kubelets and the scheduler about pods scheduling and running` e2e test is ineligible for Conformance.  Specifically, the test in question is looking for guaranteed delivery of Events from specific sources (kubelet and default scheduler).  This cannot be reasonably expected of all Kubernetes clusters, and thus the test should be demoted from Conformance.

For historical context:
- It looks like this has been part of Conformance sometime since sometime prior to 2015-10-17 (we introduced the [Conformance] tag in 1.2, ref: https://github.com/kubernetes/kubernetes/pull/15228
- We overhauled Conformance testing policy (including exclusion of Events) on 2018-10-08 (ref: https://github.com/kubernetes/community/pull/2459 )

If I wanted to be a language lawyer about this, I could say the policy covers ineligibility for _promotion_ but said nothing about the existing corpus of tests.  But I think this was just an honest oversight when we reviewed the existing Conformance tests.

Due to the very nature of what this test is verifying, I don't think it's possible to rewrite to avoid Events.  Thus, I think it should be demoted from Conformance.  SIG Node is free to continue to treat this as release-blocking, but it's not something we can reasonably expect of any Kubernetes cluster

/kind cleanup
/priority important-soon
/milestone v1.23

/sig architecture
/area conformance
because conformance

/sig node
because it's a sig-node test

**Comment by spiffxp** [comment]
/assign @johnbelamaric @smarterclayton 
Opened https://github.com/kubernetes/kubernetes/pull/106511 to address

FYI @ehashman @aojea @BenTheElder 
Since y'all were commenting on https://github.com/kubernetes/kubernetes/issues/106506

**Comment by aojea** [comment]
+1
