### ISSUE TITLE
[Flaky Test][sig-node] kubernetes-unit-test TestHTTP1DoNotReuseRequestAfterTimeout is being Flaky

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#106569]
### Which jobs are flaking?

periodic-kubernetes-unit-test-ppc64le

### Which tests are flaking?

1. vendor/k8s.io/client-go/rest.TestHTTP1DoNotReuseRequestAfterTimeout
2. vendor/k8s.io/client-go/rest.TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1
3. vendor/k8s.io/client-go/rest.TestHTTP1DoNotReuseRequestAfterTimeout/HTTP2

### Since when has it been flaking?

16th November 2021

### Testgrid link

https://k8s-testgrid.appspot.com/sig-node-ppc64le#unit-tests

### Reason for failure (if possible)

This test is added by change https://github.com/kubernetes/kubernetes/pull/104844

Seems like it started being flaky from the time added.

### Anything else we need to know?

Below is the trace from job:
```
 === FAIL: vendor/k8s.io/client-go/rest TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.13s)
    request_test.go:3016: Unexpected error: Get "https://127.0.0.1:34701/foo?timeout=100ms": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2021/11/20 12:06:03 http: TLS handshake error from 127.0.0.1:37890: read tcp 127.0.0.1:34701->127.0.0.1:37890: use of closed network connection
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.13s)
=== FAIL: vendor/k8s.io/client-go/rest TestHTTP1DoNotReuseRequestAfterTimeout (0.30s) 
```

### Relevant SIG(s)

/sig node

**Comment by Rajalakshmi-Girish** [comment]
Proof of Flakiness:
![image](https://user-images.githubusercontent.com/63038004/142738477-ef2d5dda-ee60-4532-9260-31357ed1fc9e.png)

**Comment by Rajalakshmi-Girish** [comment]
@aojea ^^

**Comment by aojea** [comment]
interesting, it doesn't have any failure in all the other jobs it seems it's only flake in ppc64le

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestHTTP

maybe a golang issue?

https://github.com/golang/go/issues/49680
https://github.com/golang/go/issues/44304

**Comment by aojea** [comment]
I don't have access to a ppc64le system, but it would be good to run the test with the `stress` tool 
```sh
# compile test test as binary
$ go test -run ^TestReconnectBroken k8s.io/client-go/rest -c
# run the test using https://pkg.go.dev/golang.org/x/tools/cmd/stress
$ stress ./rest.test -test.run ^TestReconnectBroken
5s: 24 runs so far, 0 failures
10s: 72 runs so far, 0 failures
15s: 96 runs so far, 0 failures
20s: 144 runs so far, 0 failures
25s: 192 runs so far, 0 failures
30s: 216 runs so far, 0 failures
35s: 264 runs so far, 0 failures
40s: 312 runs so far, 0 failures
45s: 336 runs so far, 0 failures
50s: 384 runs so far, 0 failures
```

**Comment by ehashman** [comment]
This testgrid tab is slated for removal as the job is not maintained: https://github.com/kubernetes/test-infra/pull/23249

Conformance tests are required to pass on ppc64le which are tracked here: https://testgrid.k8s.io/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster

But I don't think we necessarily have support for unit tests.

**Comment by Rajalakshmi-Girish** [comment]
> This testgrid tab is slated for removal as the job is not maintained: [kubernetes/test-infra#23249](https://github.com/kubernetes/test-infra/pull/23249)
> 
> Conformance tests are required to pass on ppc64le which are tracked here: https://testgrid.k8s.io/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster
> 
> But I don't think we necessarily have support for unit tests.

Yes the dashboard [`conformance`](https://testgrid.k8s.io/sig-node-ppc64le#conformance) under test-grid tab `sig-node-ppc64le` can be removed as there is a duplication of this at tab [`conformance-ppc64le`](https://k8s-testgrid.appspot.com/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster).

But we need to find a better place for dashboard [`unittests`](https://testgrid.k8s.io/sig-node-ppc64le#unit-tests). Removal of this altogether as part of testgrid `sig-node` cleanup is not right!

k8s unit tests would need a run on ppc64le architecture.

**Comment by aojea** [comment]
> k8s unit tests would need a run on ppc64le architecture

Is not only being able to have a job, there has to be resources, this case is a good example, the test works perfectly in x86 :/ https://github.com/kubernetes/kubernetes/issues/106569#issuecomment-974705089

**Comment by mkumatag** [comment]
> This testgrid tab is slated for removal as the job is not maintained: [kubernetes/test-infra#23249](https://github.com/kubernetes/test-infra/pull/23249)
> 

Well, these tests we are running for years and helping them to fix(found a few generic flaky tests as well), just that existing in the wrong group but will find a new home soon :)
> Conformance tests are required to pass on ppc64le which are tracked here: https://testgrid.k8s.io/conformance-ppc64le#Periodic%20ppc64le%20conformance%20test%20on%20local%20cluster
> 
> But I don't think we necessarily have support for unit tests.

I feel unit tests do give us a lot of confidence in the code, it's worth identifying the issues.

**Comment by mkumatag** [comment]
> > k8s unit tests would need a run on ppc64le architecture
> 
> Is not only being able to have a job, there has to be resources, this case is a good example, the test works perfectly in x86 :/ [#106569 (comment)](https://github.com/kubernetes/kubernetes/issues/106569#issuecomment-974705089)
> 
> What is the next step? Who will investigate the golang chain and the specifics of ppc64le environment?

Completely agree, need resources to debug/identify the issues.

**Comment by Rajalakshmi-Girish** [comment]
@aojea When I run using the stress tool the test is flaking in both ppc64le and x86_64.
- on ppc64le:
```
[root@rajalakshmi-workspace1 kubernetes]# stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout

/tmp/go-stress-20211123T070635-1678334821
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.45s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.28s)
        request_test.go:2974: TEST Connected from 127.0.0.1:47712 on /foo
        request_test.go:2974: TEST Connected from 127.0.0.1:47712 on /hang
        request_test.go:2976: TEST hanging 127.0.0.1:47712
        request_test.go:2974: TEST Connected from 127.0.0.1:47730 on /foo
        request_test.go:3030: Unexpected error: Get "https://127.0.0.1:35107/foo?timeout=100ms": net/http: request canceled (Client.Timeout exceeded while awaiting headers)
FAIL


ERROR: exit status 1


/tmp/go-stress-20211123T070635-1511241200
2021/11/23 07:06:38 http: TLS handshake error from 127.0.0.1:52740: read tcp 127.0.0.1:36005->127.0.0.1:52740: read: connection reset by peer
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.29s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.11s)
        request_test.go:3016: Unexpected error: Get "https://127.0.0.1:36005/foo?timeout=100ms": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
FAIL


ERROR: exit status 1

5s: 72 runs so far, 2 failures (2.78%)
```
- on x86_64:
```
[root@toad1 kubernetes]# stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout
5s: 50 runs so far, 0 failures

/tmp/go-stress-20211123T025122-1432112823
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.27s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP2 (0.14s)
        request_test.go:3016: Unexpected error: Get "https://127.0.0.1:44741/foo?timeout=100ms": context deadline exceeded
        request_test.go:2974: TEST Connected from 127.0.0.1:38406 on /foo
FAIL


ERROR: exit status 1

10s: 101 runs so far, 1 failures (0.99%)
15s: 156 runs so far, 1 failures (0.64%)
20s: 204 runs so far, 1 failures (0.49%)
25s: 250 runs so far, 1 failures (0.40%)
30s: 298 runs so far, 1 failures (0.34%)
35s: 351 runs so far, 1 failures (0.28%)
40s: 402 runs so far, 1 failures (0.25%)
45s: 454 runs so far, 1 failures (0.22%)
50s: 501 runs so far, 1 failures (0.20%)
55s: 553 runs so far, 1 failures (0.18%)
1m0s: 605 runs so far, 1 failures (0.17%)
1m5s: 655 runs so far, 1 failures (0.15%)

/tmp/go-stress-20211123T025122-2483598037
2021/11/23 02:52:32 http: TLS handshake error from 127.0.0.1:51906: read tcp 127.0.0.1:39957->127.0.0.1:51906: use of closed network connection
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.37s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.24s)
        request_test.go:2974: TEST Connected from 127.0.0.1:51894 on /foo
        request_test.go:2974: TEST Connected from 127.0.0.1:51894 on /hang
        request_test.go:2976: TEST hanging 127.0.0.1:51894
        request_test.go:3030: Unexpected error: Get "https://127.0.0.1:39957/foo?timeout=100ms": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
FAIL


ERROR: exit status 1

1m10s: 706 runs so far, 2 failures (0.28%)
```
@aojea the golang version was
```
[root@toad1 kubernetes]# go version
go version go1.17.3 linux/amd64
[root@toad1 kubernetes]#
```

**Comment by aojea** [comment]
> @aojea When I run using the stress tool the test is flaking in both ppc64le and x86_64.

yeah, that is the thing, we have this situation:

 same test , same golang version and it only flakes in ppc64le.

It is legit to think that the architecture can be the problem here, now, who can discard that the architecture is the problem?

BTW, seems golang has some reported that may be related https://github.com/kubernetes/kubernetes/issues/106569#issuecomment-974704197

**Comment by aojea** [comment]
there were some http changes in golang https://github.com/golang/go/commit/f9cb33c7c9d48fd0c38d17a659d5e968de648d40

however, I can't reproduce it in my host :/

```
stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout -test.v
5s: 538 runs so far, 0 failures
10s: 1096 runs so far, 0 failures
15s: 1656 runs so far, 0 failures
20s: 2208 runs so far, 0 failures
25s: 2760 runs so far, 0 failures
30s: 3312 runs so far, 0 failures
35s: 3867 runs so far, 0 failures
40s: 4419 runs so far, 0 failures
45s: 4977 runs so far, 0 failures
```

```
go version
go version go1.17.3 linux/amd64
```

**Comment by Rajalakshmi-Girish** [comment]
@aojea Is this somehow related https://github.com/golang/go/issues/49741?

**Comment by Rajalakshmi-Girish** [comment]
> there were some http changes in golang [golang/go@f9cb33c](https://github.com/golang/go/commit/f9cb33c7c9d48fd0c38d17a659d5e968de648d40)
> 
> however, I can't reproduce it in my host :/
> 
> ```
> stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout -test.v
> 5s: 538 runs so far, 0 failures
> 10s: 1096 runs so far, 0 failures
> 15s: 1656 runs so far, 0 failures
> 20s: 2208 runs so far, 0 failures
> 25s: 2760 runs so far, 0 failures
> 30s: 3312 runs so far, 0 failures
> 35s: 3867 runs so far, 0 failures
> 40s: 4419 runs so far, 0 failures
> 45s: 4977 runs so far, 0 failures
> ```
> 
> ```
> go version
> go version go1.17.3 linux/amd64
> ```
I compiled the test binary using the `-race` flag enabled.
We see this flaky only when the race is enabled. @aojea Can you please try passing -race while compiling the binary for the stress tool.

I followed https://github.com/kubernetes/community/blob/master/contributors/devel/sig-testing/flaky-tests.md#deflaking-unit-tests

**Comment by aojea** [comment]
:/ not a single failure in 20 mins

```
$ go test -run ^TestReconnectBroken k8s.io/client-go/rest -c -race                                    
$ stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout -test.v
5s: 392 runs so far, 0 failures
10s: 816 runs so far, 0 failures

...
18m55s: 95126 runs so far, 0 failures
19m0s: 95545 runs so far, 0 failures
19m5s: 95966 runs so far, 0 failures
```

**Comment by Rajalakshmi-Girish** [comment]
> 

@aojea Can you please try:
```
go test ./vendor/k8s.io/client-go/rest -c -race
stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout -test.v
```

**Comment by Rajalakshmi-Girish** [comment]
Why was the binary for `^TestReconnectBroken` being generated when we are running stress tool for `TestHTTP1DoNotReuseRequestAfterTimeout`?
Please help me understand if I am missing something.

**Comment by aojea** [comment]
> Why was the binary for `^TestReconnectBroken` being generated when we are running stress tool for `TestHTTP1DoNotReuseRequestAfterTimeout`? Please help me understand if I am missing something.

I was lazy and carried over the cli flags, but it doesn't matter, the generated binary is the same

```sh
$ go test -run ^TestReconnectBroken k8s.io/client-go/rest -c -race -o test_withflag
$ go test k8s.io/client-go/rest -c -race -o test_withoutflag
$ md5sum test_*
cda6ddc9d31f4c760c93b34ad78981dc  test_withflag
cda6ddc9d31f4c760c93b34ad78981dc  test_withoutflag
```

**Comment by Karthik-K-N** [comment]
@aojea I have seen that, there are no failures after increasing the timeout to 200 Millisecond from 100 Millisecond [here](https://github.com/kubernetes/kubernetes/blob/bf9ce7fd76068903e909358d2b25b05da7e4a431/staging/src/k8s.io/client-go/rest/request_test.go#L2998) 

Before increasing the timeout:
```
[root@rajalakshmi-workspace1 kubernetes]# stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout

/tmp/go-stress-20211129T115302-2252016254
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.29s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.10s)
        request_test.go:2974: TEST Connected from 127.0.0.1:57294 on /foo
        request_test.go:3016: Unexpected error: Get "https://127.0.0.1:36767/foo?timeout=100ms": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
FAIL


ERROR: exit status 1

5s: 74 runs so far, 1 failures (1.35%)
10s: 158 runs so far, 1 failures (0.63%)

/tmp/go-stress-20211129T115302-927173386
--- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.30s)
    --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.10s)
        request_test.go:2974: TEST Connected from 127.0.0.1:56260 on /foo
        request_test.go:3016: Unexpected error: Get "https://127.0.0.1:33675/foo?timeout=100ms": context deadline exceeded
FAIL
```

After increasing the timeout
```[root@rajalakshmi-workspace1 kubernetes]# stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout
5s: 54 runs so far, 0 failures
10s: 112 runs so far, 0 failures
15s: 169 runs so far, 0 failures
20s: 228 runs so far, 0 failures
25s: 291 runs so far, 0 failures
30s: 353 runs so far, 0 failures
35s: 413 runs so far, 0 failures
40s: 475 runs so far, 0 failures
45s: 537 runs so far, 0 failures
50s: 598 runs so far, 0 failures
55s: 659 runs so far, 0 failures
1m0s: 721 runs so far, 0 failures
1m5s: 784 runs so far, 0 failures
1m10s: 842 runs so far, 0 failures

```

Machine information
```
[root@rajalakshmi-workspace1 kubernetes]# lscpu
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  8
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Model:               2.2 (pvr 004e 0202)
Model name:          POWER9 (architected), altivec supported
Hypervisor vendor:   pHyp
Virtualization type: para
L1d cache:           32K
L1i cache:           32K
NUMA node0 CPU(s):   0-7
Physical sockets:    2
Physical chips:      1
Physical cores/chip: 10
```

Is there any way i can find, where its been taking longer time or why its expecting some extra time.

**Comment by aojea** [comment]
> @aojea I have seen that, there are no failures after increasing the timeout to 200 Millisecond from 100 Millisecond [here](https://github.com/kubernetes/kubernetes/blob/bf9ce7fd76068903e909358d2b25b05da7e4a431/staging/src/k8s.io/client-go/rest/request_test.go#L2998)
> 
> Before increasing the timeout:
> 
> ```
> [root@rajalakshmi-workspace1 kubernetes]# stress ./rest.test -test.run TestHTTP1DoNotReuseRequestAfterTimeout
> 
> /tmp/go-stress-20211129T115302-2252016254
> --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.29s)
>     --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.10s)
>         request_test.go:2974: TEST Connected from 127.0.0.1:57294 on /foo
>         request_test.go:3016: Unexpected error: Get "https://127.0.0.1:36767/foo?timeout=100ms": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> FAIL
> 
> 
> ERROR: exit status 1
> 
> 5s: 74 runs so far, 1 failures (1.35%)
> 10s: 158 runs so far, 1 failures (0.63%)
> 
> /tmp/go-stress-20211129T115302-927173386
> --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout (0.30s)
>     --- FAIL: TestHTTP1DoNotReuseRequestAfterTimeout/HTTP1 (0.10s)
>         request_test.go:2974: TEST Connected from 127.0.0.1:56260 on /foo
>         request_test.go:3016: Unexpected error: Get "https://127.0.0.1:33675/foo?timeout=100ms": context deadline exceeded
> FAIL
> ```
> 
> After increasing the timeout
> 
> ```
> 5s: 54 runs so far, 0 failures
> 10s: 112 runs so far, 0 failures
> 15s: 169 runs so far, 0 failures
> 20s: 228 runs so far, 0 failures
> 25s: 291 runs so far, 0 failures
> 30s: 353 runs so far, 0 failures
> 35s: 413 runs so far, 0 failures
> 40s: 475 runs so far, 0 failures
> 45s: 537 runs so far, 0 failures
> 50s: 598 runs so far, 0 failures
> 55s: 659 runs so far, 0 failures
> 1m0s: 721 runs so far, 0 failures
> 1m5s: 784 runs so far, 0 failures
> 1m10s: 842 runs so far, 0 failures
> ```
> 
> Machine information
> 
> ```
> [root@rajalakshmi-workspace1 kubernetes]# lscpu
> Architecture:        ppc64le
> Byte Order:          Little Endian
> CPU(s):              8
> On-line CPU(s) list: 0-7
> Thread(s) per core:  8
> Core(s) per socket:  1
> Socket(s):           1
> NUMA node(s):        1
> Model:               2.2 (pvr 004e 0202)
> Model name:          POWER9 (architected), altivec supported
> Hypervisor vendor:   pHyp
> Virtualization type: para
> L1d cache:           32K
> L1i cache:           32K
> NUMA node0 CPU(s):   0-7
> Physical sockets:    2
> Physical chips:      1
> Physical cores/chip: 10
> ```
> 
> Is there any way i can find, where its been taking longer time or why its expecting some extra time.

Maybe we can just bump the timeout in the test, is not like we need such granularity and we are taking of milliseconds only .,.. , maybe something in the standard library is racing?

**Comment by aojea** [comment]
submitted https://github.com/kubernetes/kubernetes/pull/106716 for bumping the timeout on this test, thanks for keep pushing
