### ISSUE TITLE
[Failing test][sig-api-machinery] aks-engine-windows-containerd-master

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#106574]
### Which jobs are failing?

aks-engine-windows-containerd-master

### Which tests are failing?

- ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd.OverallChanges
- Kubernetes e2e suite.[sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]Changes
- kubetest.TestChanges

### Since when has it been failing?

11/20/2021 03:27 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#aks-engine-windows-containerd-master

### Reason for failure (if possible)

[see run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1462200742394728448)
Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]

```
error waiting for deployment "sample-apiserver-deployment"
```

```bash
Failure [303.376 seconds]
[sig-api-machinery] Aggregator
  Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance] [It]

[Fail] [sig-api-machinery] Aggregator [It] Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance] 

Ran 305 of 7040 Specs in 2001.704 seconds
FAIL! -- 304 Passed | 1 Failed | 0 Pending | 6735 Skipped

```

### Anything else we need to know?

/cc @jsturtevant

### Relevant SIG(s)

/sig api-machinery

**Comment by aojea** [comment]
I think we should verify that the test doesn't fail in the supported jobs, blocking is a good candidate for correlation
https://testgrid.k8s.io/sig-release-master-blocking

If the test only fail in this job it should be assigned to the job owner,

**Comment by jsturtevant** [comment]
This is failing due to a change in ETCD image https://github.com/kubernetes/kubernetes/commit/c82a0f8ddcae7b53b72adca8e492feca20396e44 , I was looking at https://github.com/kubernetes/kubernetes/commit/c4fc9bba6c292970f7f8e82b8033afbe31f07c9a which should have added windows support but I think it is missing parts. It should have made this automatic. I don't see where the base windows images are loaded so I think it is not working as expected but maybe I am missing something.  

I going to try and rebuild an image and push it to our Windows k8sprow.azurecr.io registry we use for this image currently so our tests start passing again.

/cc @claudiubelu

**Comment by claudiubelu** [comment]
@jsturtevant is right. Somehow, the Windows image building bits were lost on rebase in the PR. I have sent a PR with the missing bits: https://github.com/kubernetes/kubernetes/pull/106593

**Comment by jsturtevant** [comment]
I used #106593 to build the images for sig-windows k8sprow.azurecr.io.  The next set of tests should pass now that the `k8sprow.azurecr.io/kubernetes-e2e-test-images/etcd:3.5.1-0` image is available.  

Longer term solution is to merge #106593 and image promotion will have the windows images.

**Comment by jsturtevant** [comment]
latest tests are passing with the new image, closing this with #106593 for the long term fix.

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1463158371048755200

/close
