### ISSUE TITLE
Extract containerID from system.slice/containerd.service style cgroupPath

### ISSUE THREAD

**Issue by zhhuabj** [kubernetes/kubernetes#106514]
### What happened?

kubeadm + containerd based cluster only "workingSetBytes" is reported for containers in a pod.

"memory": {
"time": "2021-10-04T12:06:58Z",
"workingSetBytes": 63426560
}

### What did you expect to happen?

but we would expect more memory metrics to be reported.

"memory": {
"time": "2021-10-04T12:16:27Z",
"availableBytes": 16431185920,
"usageBytes": 20508672,
"workingSetBytes": 20508672,
"rssBytes": 19746816,
"pageFaults": 14228,
"majorPageFaults": 0
}

### How can we reproduce it (as minimally and precisely as possible)?

We can easily reproduce the problem with these steps -
step1: https://pastebin.ubuntu.com/p/s5VMxGtwTw/
step2: https://pastebin.ubuntu.com/p/ZWHzSznjG4/

### Anything else we need to know?

The root cause is that the commit 545d8985844 [0] handles this style cgroupPath,

/sys/fs/cgroup/systemd/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice/cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope

but not the following style cgroupPath.

/sys/fs/cgroup/systemd/system.slice/containerd.service/kubepods-burstable-pod36b6d6be73b1065af369b3985edafa09.slice\:cri-containerd\:79fedb3bd23ca77c9d9ccb41909038316f713df22b54b7d942b71d3812e7c74e

[0] https://github.com/kubernetes/kubernetes/commit/545d8985844f6b054319db8545cb9892148e2955

### Kubernetes version

the suffix dirty of 'v1.22.0-dirty' means we are using kubelet v.122.0 + commit 545d8985844, see above reproducer for more details.

<details>

```console
root@juju-10ee00-case320434-0:~# kubelet --version
Kubernetes v1.22.0-dirty
root@juju-10ee00-case320434-0:~# containerd --version
containerd containerd.io 1.4.11 5b46e404f6b9f661a205e28d59c982d3634148f8
```

</details>

### Cloud provider

<details>

</details>

### OS version

This issue is only happened on ubuntu 20.04 + containerd, not ubuntu 18.04 + containerd, because cgroup path on ubuntu 18.04 is similar the following patch so it has no problem.

/sys/fs/cgroup/systemd/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod2fc932ce_fdcc_454b_97bd_aadfdeb4c340.slice/cri-containerd-aaefb9d8feed2d453b543f6d928cede7a4dbefa6a0ae7c9b990dd234c56e93b9.scope

<details>

```console
# On Linux:
$ cat /etc/os-release |grep -i version_id
VERSION_ID="20.04"
$ uname -a
Linux juju-10ee00-case320434-0 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by odinuge** [comment]
Hi,

From your reproduction steps, it looks like you are running using different cgroup drivers for containerd and for kubelet. This is not supported, and things will not work. It looks like you explicitly configure systemd cgroup driver for kubelet, while the default value for containerd is cgroupfs/not use systemd.

Can you please try using the same value on both kubelet and containerd, and see if you still see this behavor?

**Comment by zhhuabj** [comment]
Hi odinuge,

Thanks for your review, I found an issue 4900 [1] on google, so I added 'SystemdCgroup = true' into /etc/containerd/config.toml and created a new test env, it works.

root@juju-67651a-case320434-2-0:/home/ubuntu# ls /sys/fs/cgroup/systemd/kubepods.slice/
cgroup.clone_children  cgroup.procs  kubepods-besteffort.slice  kubepods-burstable.slice  notify_on_release  tasks
root@juju-67651a-case320434-2-0:/home/ubuntu# ls /sys/fs/cgroup/systemd/system.slice/containerd.service/
cgroup.clone_children  cgroup.procs  notify_on_release  tasks

I will close this issue, odinuge, thanks again.

[1] https://github.com/containerd/containerd/issues/4900
