### ISSUE TITLE
[sig-storage] Projected downwardAPI should update annotations on modification - flaking

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#106613]
### Which jobs are flaking?

Random failure on `ci-kubernetes-e2e-aks-engine-azure-master-staging-windows`

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows/1462891652401074176

### Which tests are flaking?

```
Kubernetes e2e suite: [sig-storage] Projected downwardAPI should update annotations on modification [NodeConformance] [Conformance] expand_less
```

### Since when has it been flaking?

2021-11-22 21:14:06 +0000 UTC

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows/1462891652401074176

### Reason for failure (if possible)

Suspecting the malfunction of the downwardAPI, invalidating the copy of annotations to the mounted file. Could be due a load in some component?

Kubelet logs:

```
7718:I1122 22:00:20.924010    4424 kubelet.go:2063] "SyncLoop ADD" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
8006:I1122 22:00:37.759585    4424 kubelet.go:2070] "SyncLoop UPDATE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
8359:I1122 22:02:44.602333    4424 kubelet.go:2079] "SyncLoop DELETE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
```

### Anything else we need to know?

The downward API never writes the annotations in the file, so tests timeout waiting for this to happen.

![image](https://user-images.githubusercontent.com/1223213/142958804-6aaecefc-3c57-4958-8c5e-d7490043a814.png)

--

multiple failures in different jobs

https://storage.googleapis.com/k8s-triage/index.html?test=Projected%20downwardAPI%20should%20update%20annotations%20on%20modification#e110086f520d1e180ef0

### Relevant SIG(s)

/sig storage
/sig windows

**Comment by knabben** [comment]
Logs for a failing pod - the container has died:
```
7728:I1122 22:00:22.262126    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerDied Data:f29ad0cd616e2cb3e75c31b5afc428ba596811ee7b75550443708c6057d0559c}
7730:I1122 22:00:23.281707    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerStarted Data:f29ad0cd616e2cb3e75c31b5afc428ba596811ee7b75550443708c6057d0559c}
7731:I1122 22:00:25.060776    4424 fake_cpu_manager.go:51] "AddContainer" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
7732:I1122 22:00:25.060776    4424 fake_memory_manager.go:50] "Add container" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
7733:I1122 22:00:25.060900    4424 fake_topology_manager.go:58] "AddContainer" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
7876:I1122 22:00:32.009010    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerStarted Data:2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c}
8006:I1122 22:00:37.759585    4424 kubelet.go:2070] "SyncLoop UPDATE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
8359:I1122 22:02:44.602333    4424 kubelet.go:2079] "SyncLoop DELETE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
```

Logs for another pod working:
```
5082:I1122 13:55:03.557138    4432 kuberuntime_manager.go:486] "No sandbox for pod can be found. Need to start a new one" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961"
5101:I1122 13:55:09.055683    4432 fake_cpu_manager.go:51] "AddContainer" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961" containerName="client-container" containerID="6227f1d3f9385c690c3dcd2e609fd3b0428fe9d83866e58818aa1e3d751ed1c8"
5102:I1122 13:55:09.056681    4432 fake_memory_manager.go:50] "Add container" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961" containerName="client-container" containerID="6227f1d3f9385c690c3dcd2e609fd3b0428fe9d83866e58818aa1e3d751ed1c8"
5103:I1122 13:55:09.056681    4432 fake_topology_manager.go:58] "AddContainer" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961" containerName="client-container" containerID="6227f1d3f9385c690c3dcd2e609fd3b0428fe9d83866e58818aa1e3d751ed1c8"
5108:I1122 13:55:10.947578    4432 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961" event=&{ID:02ff90de-bd83-4391-8ae2-9e07e7751f9f Type:ContainerStarted Data:2808205b14910cd719ca58d3d9bae7f248404ea810ae60d5aadbd67bfed83267}
5113:I1122 13:55:19.370387    4432 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961" event=&{ID:02ff90de-bd83-4391-8ae2-9e07e7751f9f Type:ContainerStarted Data:6227f1d3f9385c690c3dcd2e609fd3b0428fe9d83866e58818aa1e3d751ed1c8}
5124:I1122 13:55:22.191911    4432 kubelet.go:2070] "SyncLoop UPDATE" source="api" pods=[projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961]
5265:I1122 13:55:32.215553    4432 kubelet.go:2079] "SyncLoop DELETE" source="api" pods=[projected-953/annotationupdate4f0dd0ce-685d-4bde-a852-a9c2dfe99961]
```

**Comment by jsturtevant** [comment]
Looking at https://storage.googleapis.com/k8s-triage/index.html?test=Projected%20downwardAPI%20should%20update%20annotations%20on%20modification#e110086f520d1e180ef0 this happens in more than just windows jobs though it happens more often there.  Some of the other jobs are:
 
- ci-cri-containerd-e2e-ubuntu-gce
- ci-kubernetes-e2e-ubuntu-gce 
- ci-kubernetes-kind-ipv6-e2e-parallel

**Comment by claudiubelu** [comment]
> Logs for a failing pod - the container has died:
> 
> ```
> 7728:I1122 22:00:22.262126    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerDied Data:f29ad0cd616e2cb3e75c31b5afc428ba596811ee7b75550443708c6057d0559c}
> 7730:I1122 22:00:23.281707    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerStarted Data:f29ad0cd616e2cb3e75c31b5afc428ba596811ee7b75550443708c6057d0559c}
> 7731:I1122 22:00:25.060776    4424 fake_cpu_manager.go:51] "AddContainer" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
> 7732:I1122 22:00:25.060776    4424 fake_memory_manager.go:50] "Add container" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
> 7733:I1122 22:00:25.060900    4424 fake_topology_manager.go:58] "AddContainer" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" containerName="client-container" containerID="2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c"
> 7876:I1122 22:00:32.009010    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerStarted Data:2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c}
> 8006:I1122 22:00:37.759585    4424 kubelet.go:2070] "SyncLoop UPDATE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
> 8359:I1122 22:02:44.602333    4424 kubelet.go:2079] "SyncLoop DELETE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
> ```

Indeed, that container died, but another one was created and started later:

```
I1122 22:00:32.009010    4424 kubelet.go:2101] "SyncLoop (PLEG): event for pod" pod="projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48" event=&{ID:f23702c0-573e-4d1b-b087-0908d6a0ba19 Type:ContainerStarted Data:2c9937de8e9af7e2062c1f29a9888ed1f663f0b3b9c44f7fe6d5806abe28d39c}
```

In addition to that, we can see the pod logs in the test failure. The ``/etc/podinfo/annotations`` file is printed 65 times, with a 2 sec sleep in between them, which translates to about 2 minutes, which is how long the test waits for the Pod updates to propagate. Technically, the Update is seen by the Kubelet, but nothing seems to be done with it:

```
I1122 22:00:37.759585    4424 kubelet.go:2070] "SyncLoop UPDATE" source="api" pods=[projected-2768/annotationupdatee1328ba9-4563-426e-a639-e0ec0c0d6b48]
```

But what I find more curious about these logs you've extracted as well, how did we get a ContainerDied Event before a ContainerStarted event?
