### ISSUE TITLE
The kubectl cmd doesn't work after update the k8s Certificate

### ISSUE THREAD

**Issue by siwang2011** [kubernetes/kubernetes#106642]
### What happened?

today i find my k8s cluster cert is expired. 
i use the kubectl cmd  and it return Unable to connect to the server: x509: certificate has expired or is not yet valid
i check the cert and find it is expired in yesterday
so i just update the cert in master node with cmd  kubeadm alpha certs renew all
and happily i find the kubectl cmd is available.
after a moment i use the kubectl scale to scale my deployment and the cmd doesn't work
Please tell me how to fix it.

### What did you expect to happen?

i expect the cluster is available after use the cmd to update the cert.

### How can we reproduce it (as minimally and precisely as possible)?

just use the cmd kubeadm alpha certs renew all in which cert is expired cluster

### Anything else we need to know?

my cluster has 3 master, and first i just use cmd to update cert in one master.
and i use the cmd in other master nodes, but the problem is still alive 

### Kubernetes version

kubectl version 1.17.3

### Cloud provider

No, i install the k8s in my local machine

### OS version

# On Linux: centos7/8
$ cat /etc/os-release 
# paste output here
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"
$ uname -a
Linux k8s-master2 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Thu Oct 22 00:20:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>
i install k8s with kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

CRI is docker

**Comment by MadhavJivrajani** [comment]
/kind support
/sig cli
@siwang2011 thanks for opening this issue!
Unfortunately, `1.17.3` is no longer supported. You can find more info on that [here](https://kubernetes.io/releases/).

I'll be closing this issue but if you are able to reproduce this in a version that is currently supported, please feel free to reopen this issue and ping me. You can reopen this issue by commenting `/reopen`.

In the meantime, feel free to ask this query on our [slack](https://slack.k8s.io) and you might get the help that you're looking for there. A few channels that this particular query might fit in with would be `#sig-cli`, `#kubernetes-users` and `#sig-auth`.

Thanks again!
/close
