### ISSUE TITLE
remove infinite loop from test/e2e/service.go:validateEndpointsOrFail()

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#10669]
test should fail after some time, and should not block other tests.

**Comment by kargakis** [comment]
@kubernetes/sig-network-misc @kubernetes/sig-testing-misc

**Comment by MrHohn** [comment]
We already removed the infinite loop and added a timeout: https://github.com/kubernetes/kubernetes/blob/310ea94b6e0694ab08e3aa6185919be92419e932/test/e2e/framework/service_util.go#L1023-L1059.

Closing this issue.

/assign
