### ISSUE TITLE
ephemeral-storage based pod eviction should include more volume types

### ISSUE THREAD

**Issue by zhan849** [kubernetes/kubernetes#106606]
### What happened?

Currently kubelet's default eviction manager uses only image fs disk size and log (default place for console log) size to decide eviction threshold: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager.go#L527

however a common use case of ephemeral disk is to leverage EmptyDir for scratch space, where pod can write a lot of data, without including empty dir (and maybe some other out-of-box volume type), kubelet might make sub-ideal eviction decision such that a pod writes some log gets evicted while it's sibling using EmptyDir with data sizes magnitudes larger stays.

### What did you expect to happen?

commonly supported out-of-box volumes are considered when making ephemeral-storage shortage based eviction decision

### How can we reproduce it (as minimally and precisely as possible)?

1. create 2 pods and have them scheduled on the same node
2. have pod A to print logs to console, and pod B to print logs magnitudes larger in size but to an empty dir volume
3. wait till node level ephemeral storage shortage happens

Pod A gets evicted but pod B stays

### Anything else we need to know?

this may be a feature request instead of bug but we can convert later if needed

/sig node 
/sig storage

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
 1.18.x

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

(please re-add if SIG Node help is needed here)
