### ISSUE TITLE
Pod Initialization Error upon removing the PVC

### ISSUE THREAD

**Issue by BUHPS2261R** [kubernetes/kubernetes#106672]
### What happened?

Our Pega Platform Application is hosted in Kubernetes environment and Stream is a service node which is part of it. As part of Application Maintenance, We had to perform clean restart which included PVC's Unmount from Stream POD. Upon doing that, Pod is not getting initialized when we re-install the application.

Tried remove the Stateful-set and it's pods too to fix the issue, but it wasn't helpful.

![PVC Issue](https://user-images.githubusercontent.com/88714885/143393429-aa88d698-ec45-431f-bc9b-25b8bce3ed85.png)
![PVC issue after deletion for Stream](https://user-images.githubusercontent.com/88714885/143393446-0cef1f64-f1c4-4de5-881a-e35181dc4a4b.png)

### What did you expect to happen?

POD should not be in a state of Initializing State although PVC's are there in the cluster. POD should start with Stream Service when re-install the application.

### How can we reproduce it (as minimally and precisely as possible)?

Remove / Un-mount the PVC Volume from Stream Service POD

### Anything else we need to know?

Nothing

![image](https://user-images.githubusercontent.com/88714885/143393933-87b469cf-d065-429c-a097-d1861a04443a.png)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
![image](https://user-images.githubusercontent.com/88714885/143393963-e063193d-4372-444b-b974-f58f04a59aae.png)

### Cloud provider

AWS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
![image](https://user-images.githubusercontent.com/88714885/143394007-9d9b5fed-1374-4444-82ff-d24e20d3edd2.png)

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
please include all the details that are missing in the issue description, k8s version, CSI, CNI...etc.

/sig storage
