### ISSUE TITLE
[Failing tests] cos-cgroupv2-containerd-e2e

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#106626]
### Which jobs are failing?

ci-cos-cgroupv2-containerd-e2e-gce

### Which tests are failing?

Most tests of Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: gcepd] 

### Since when has it been failing?

17 Nov 2021

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-e2e

### Reason for failure (if possible)

```
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:174
Nov 19 12:38:43.577: While creating pods for resizing
Unexpected error:
    <*errors.errorString | 0xc003eb8d20>: {
        s: "pod \"pod-f4898948-a88a-4197-ab67-cb229e2d38b1\" is not Running: timed out waiting for the condition",
    }
    pod "pod-f4898948-a88a-4197-ab67-cb229e2d38b1" is not Running: timed out waiting for the condition
occurred
/go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volume_expand.go:192
```

### Relevant SIG(s)

/sig node storage

**Comment by SergeyKanzhelev** [comment]
Seems related to https://github.com/kubernetes/test-infra/pull/24438

@leiyiz can you take a look?

**Comment by leiyiz** [comment]
looks like gce-pd need to be skipped here as well. Will open a PR

**Comment by leiyiz** [comment]
Searching for `[Driver: gcepd]` in the linked testgrid did not show anything
