### ISSUE TITLE
[Failing tests] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#106635]
### Jobs failing

- ci-kubernetes-node-kubelet-serial-containerd: https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd
- ci-kubernetes-node-kubelet-serial: https://testgrid.k8s.io/sig-node-kubelet#node-kubelet-serial

##### Error text:
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/device_plugin_test.go:149
Unexpected error:
    <*errors.errorString | 0xc001245a40>: {
        s: "there are currently no ready, schedulable nodes in the cluster",
    }
    there are currently no ready, schedulable nodes in the cluster
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:303
```

(This is just an example, most of the tests appear to be failing)

#### Recent failures:

[11/23/2021, 2:51:59 AM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1463097972521701376)
[11/23/2021, 12:56:58 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1463069031668912128)
[11/22/2021, 10:50:58 PM ci-kubernetes-node-kubelet-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial/1463037322118303744)
[11/22/2021, 9:39:58 PM ci-cos-cgroupv2-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1463019454345515008)
[11/22/2021, 8:55:59 PM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1463008381341011968)

/sig node
/kind failing-test

/milestone v1.23
since test is failing in a release-blocking job
/priority critical-urgent

/assign @endocrimes 
/cc @SergeyKanzhelev 

I believe this stems from https://github.com/kubernetes/kubernetes/pull/106348

**Comment by endocrimes** [comment]
/triage accepted

These failures look weird - I don't understand why dockershim is sometimes failing after restarting the kubelet. I guess we should double check that timings match the old GPU test (I think I might've tightened them a bit, bc they were passing when I ran the device suite on the same nodes).

What's weirder is that they passed on my PR and all of a sudden broke after merging

**Comment by ehashman** [comment]
Discussed at [SIG Node CI](https://docs.google.com/document/d/1fb-ugvgdSVIkkuJ388_nhp2pBTy_4HEVg5848Xy7n5U/edit#bookmark=id.enugitdwq2u1) today - the easiest solution now that 1.23 has been branched is to punt these tests out of the serial lane so we can get it green again for 1.23, since any changes at this point must be backported and we would prefer that this is not release-blocking.

**Comment by ehashman** [comment]
/milestone clear

https://github.com/kubernetes/test-infra/pull/24464 should address this; we won't get a fresh serial run for another ~6 hours so let's confirm next business day that this is temporarily fixed.

**Comment by liggitt** [comment]
can we keep it in the milestone until we get a verified green run?

**Comment by pacoxu** [comment]
CI is green today after skipping DevicePluginProbe tests .
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial

**Comment by SergeyKanzhelev** [comment]
/assign @fromanirh 

Maybe related to https://github.com/kubernetes/kubernetes/issues/103691

**Comment by endocrimes** [comment]
Looks like serial has been stable for a while, closing: https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

/close

**Comment by SergeyKanzhelev** [comment]
/reopen

it is referred to here: https://github.com/kubernetes/test-infra/blob/71cf119c846b21f8fc37ab7bac00899a80ce9bea/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L401

Tests are skipped today

**Comment by SergeyKanzhelev** [comment]
@fromanirh did you have a chance to look at this? I remember you were close to understanding on what is going wrong here

**Comment by endocrimes** [comment]
oh welp, missed that 😓

**Comment by fromanirh** [comment]
> @fromanirh did you have a chance to look at this? I remember you were close to understanding on what is going wrong here

I was (past tense) but now I need to go back and look at my notes. If someone else wants to take over, be my guest, I've been quite busy with other tasks lately. Otherwise I'll get back to this!

**Comment by SergeyKanzhelev** [comment]
I agree, this plan sounds good. Thank you!

**Comment by fromanirh** [comment]
xref: https://github.com/kubernetes/test-infra/pull/26212

**Comment by fromanirh** [comment]
[podresources tests](https://github.com/kubernetes/kubernetes/blob/master/test/e2e_node/podresources_test.go) started to fail also locally - we have baremetal lanes in RH - in the project CI they skip the relevant test. Investigating a possible common root cause

**Comment by fromanirh** [comment]
after a very long troubleshooting and quite few attempts, https://github.com/kubernetes/kubernetes/pull/109820 is ready for review
