### ISSUE TITLE
why coredns oom score is -997?

### ISSUE THREAD

**Issue by vsxen** [kubernetes/kubernetes#106649]
### What happened?

why  burstable pod oom score is -997?
```
root@ubuntu-focal:/home/vagrant# kubectl -n kube-system describe  po coredns-57d4cbf879-l277z |grep -i qos
QoS Class:                   Burstable
root@ubuntu-focal:/home/vagrant# ps aux |grep core
root        8181  0.4  1.8 746256 37092 ?        Ssl  02:05   0:00 /coredns -conf /etc/coredns/Corefile
root        8417  0.3  1.8 746512 37024 ?        Ssl  02:05   0:00 /coredns -conf /etc/coredns/Corefile
root        9217  0.0  0.1   8160  2532 pts/0    S+   02:06   0:00 grep --color=auto core
root@ubuntu-focal:/home/vagrant# cat /proc/8181/oom_score_adj
-997
```

### What did you expect to happen?

oom socre is 998 ?

### How can we reproduce it (as minimally and precisely as possible)?

```
root@ubuntu-focal:/home/vagrant# kubectl -n kube-system describe  po coredns-57d4cbf879-l277z |grep -i qos
QoS Class:                   Burstable
root@ubuntu-focal:/home/vagrant# ps aux |grep core
root        8181  0.4  1.8 746256 37092 ?        Ssl  02:05   0:00 /coredns -conf /etc/coredns/Corefile
root        8417  0.3  1.8 746512 37024 ?        Ssl  02:05   0:00 /coredns -conf /etc/coredns/Corefile
root        9217  0.0  0.1   8160  2532 pts/0    S+   02:06   0:00 grep --color=auto core
root@ubuntu-focal:/home/vagrant# cat /proc/8181/oom_score_adj
-997
# why  Burstable pod oom score is -997?
```

### Kubernetes version

<details>

```console
kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.1
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
hi, how are you creating the cluster? kubeadm or something else?

> oom socre is 998 ?

what is the concern if the oom score is -977?
why do you think the oom score should be 988.

value close to 1000 means = more likely for the process to be killed.

/sig network

**Comment by vsxen** [comment]
Yes , use kubeadm

I think burstable pod oom score is 998 and I find the burstable pod in default ns oom score is 998,
so who set coredns oom score?

https://github.com/kubernetes/kubernetes/blob/release-1.21/pkg/kubelet/qos/policy.goo#L25-L31

**Comment by neolit123** [comment]
> Yes , use kubeadm

ok

> so who set coredns oom score?

the kubelet container manager is managing the scores of containers.

this is how kubeadm setups the coredns pods:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/addons/dns/manifests.go#L74

they have `priorityClassName: system-cluster-critical` which results in the score that you are seeing.

> Note: The kubelet also sets an oom_score_adj value of -997 for containers in Pods that have system-node-critical Priority

https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/

this is the desired default, so if you don't want to have it you can remove the `priorityClassName: system-cluster-critical` value or apply the QoS that you want.

/remove-sig network
/kind support
/area kubeadm
/close

**Comment by vsxen** [comment]
`The kubelet also sets an oom_score_adj value of -997 for containers in Pods that have system-node-critical Priority`

Can you let me know which Func do it?

**Comment by neolit123** [comment]
this is in the 1.22 changelog:

> As of now both `system-node-critical` and `system-cluster-critical` pods have -997 OOM score, making them one of the last processes to be OOMKilled

qos polocy is managed here:
https://github.com/kubernetes/kubernetes/blob/0691157ec4d2386f98cff6dc4e2a02433710218c/pkg/kubelet/qos/policy.go

for dev questions you can ask in #sig-node on k8s slack.
