### ISSUE TITLE
APIResponseCompression would increase P99 In apiserver

### ISSUE THREAD

**Issue by kkkkun** [kubernetes/kubernetes#106679]
We make a performance test to verify feature gain  which would take to us ?
Environment:  64C128G
We create a new crd which size is 3kb. 
| crd | compress(size/cpu/bandwidth/P99)    | discompress(size/cpu/bandwidth/P99) |
| :-----| ----: | :----: |
|crd:1000 qps:2 | 3.1M/3C/48M/168ms         |  100k/3C/1.7M/181ms               |
|crd:2000 qps:2 | 6.1M/3.3C/48M/310ms      |  202k/3.1C/1.7M/334ms             |
|crd:5000 qps:2 | 16M/4.2C/48M/781ms       |  506k/4C/2.4M/840ms                |
|crd:10000 qps:2 | 31M/4.6C/48M/1596ms   |  1.1M/4.6C/2.6M/1726ms          |

The above shows:
1.  Can reduce bandwidth effectively;
2.  P99 would increase;

The first conclusion absoutly corrects which why we add this. But  increated P99 is not what we expected. 
If P99 increases,  it would be not usefully in some solution. 

Can you give me some explanation ?

**Comment by kkkkun** [comment]
cc @liggitt  @smarterclayton @wojtek-t

**Comment by MadhavJivrajani** [comment]
Not sure how this is a flake
/remove-kind flake
/sig scalability

**Comment by kkkkun** [comment]
KEP: https://github.com/kubernetes/enhancements/blob/0e4d5df19d396511fe41ed0860b0ab9b96f46a2d/keps/sig-api-machinery/2338-graduate-API-gzip-compression-support-to-GA/README.md
beta PR: https://github.com/kubernetes/kubernetes/pull/77449
