### ISSUE TITLE
kubectl get CRD list with dirty data, but can not edit/delete

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#106625]
### What happened?

In our K8s cluster, we used the `extension-apiserver` manner to self-define CRD, to set the name `my-crd`.
1. We set the `NamespaceScoped = true`, then created some resources, like this:
```
kubectl get my-crd -A
NAME     CREATED AT
my-crd-1   2021-11-22T03:03:20Z
my-crd-2   2021-11-22T08:07:28Z
```
2. Then set the `NamespaceScoped = false`, then created some resources again, like this:
```
kubectl get my-crd -A
NAME     CREATED AT
my-crd-1   2021-11-20T03:03:20Z
my-crd-2   2021-11-20T08:07:28Z
my-crd-3   2021-11-21T04:03:20Z
my-crd-4   2021-11-21T09:03:20Z
```
Problem is: we can only edit/delete the later 2 resources (i.e. my-crd-3, my-crd-4), but can not edit/delete the first 2 `dirty` resources (i.e. my-crd-1, my-crd-2). It just hint `no resources found`.

At this point, there are 2 methods to edit/delete the first 2 `dirty` data:
1). Rollback code to `NamespaceScoped = true`, this is clumsy;
2). Exec into the etcd pod to edit/delete the dirty data keys directly, but this violates the rule to not operate etcd;

So this is the issue: we can kubectl list data, but can not edit/delete them, that is confusing :(

### What did you expect to happen?

1. `kubectl` list all data, but can also edit/delete them, maybe with some flags;
2. Add a new outcome column to display the 'dirty info', to let the user know it is dirty;

### How can we reproduce it (as minimally and precisely as possible)?

Use the `extension-apiserver` manner to self-define CRD:
1. set the `NamespaceScoped = true`, then created some resources;
2. set the `NamespaceScoped = false`, then created some resources again;
Then can list out all data, but can only edit/delete the later resources with `NamespaceScoped = false`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.3", GitCommit:"f8797eb035aca9c928af02ea9a74d232cfd41bc6", GitTreeState:"clean", BuildDate:"2020-10-12T03:32:01Z", GoVersion:"go1.14.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

</details>

**Comment by liggitt** [comment]
changing a CRD from NamespaceScoped=true to NamespaceScoped=false is not supported, and should be prevented by update validation:

https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L113

https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L450-L458

if this field is able to be changed, _that's_ the bug

**Comment by MadhavJivrajani** [comment]
@astraw99 if possible, please try to reproduce this on a a K8s version that is currently supported. More info [here](https://kubernetes.io/releases/version-skew-policy/#supported-versions).
(1.18.x does not have patch support anymore)

**Comment by astraw99** [comment]
@liggitt Got what you said, but we used the `extension-apiserver` manner, implemented this method `NamespaceScoped() bool`:
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/staging/src/k8s.io/apiserver/pkg/registry/rest/create.go#L41-L48

It is not about field change validation(`CustomResourceDefinitionSpec.Scope`), but is about dirty data issue.

**Comment by liggitt** [comment]
I see. It is invalid to change the scope of a resource type without first deleting all existing data that is stored as the opposite scope type. The built in types and CRD-based types do not permit this, and you would need to prevent this in your implementation as well.

**Comment by astraw99** [comment]
Got it, thanks :)
