### ISSUE TITLE
JSON: *v1.Container not logged as struct

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#106652]
### What happened?

kubelet logs a "container" key/value pair:
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L902

That value is a `*v1.Container`:
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/pkg/kubelet/kuberuntime/kuberuntime_container.go#L100

The resulting JSON log output contains:
```
Nov 19 02:13:48 kind-worker2 kubelet[250]: {"ts":1637288028968.0125,"caller":"kuberuntime/kuberuntime_manager.go:902","msg":"Creating container in pod","v":4,"containerType":"container","container":"&Container{Name:terminate-cmd-rpn,Image:k8s.gcr.io/e2e-test-images/busybox:1.29-2,Command:[sh -c \nf=/restart-count/restartCount\ncount=$(echo 'hello' >> $f ; wc -l $f | awk {'print $1'})\nif [ $count -eq 1 ]; then\n\texit 1\nfi\nif [ $count -eq 2 ]; then\n\texit 0\nfi\nwhile true; do sleep 1; done\n],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:restart-count,ReadOnly:false,MountPath:/restart-count,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kube-api-access-87lbt,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,}","pod":{"name":"terminate-cmd-rpn277263df-6dd5-4124-86bf-09475f6bdd96","namespace":"container-runtime-2805"}}
```

Note the `"container":"&Container{...nil,}"` part: this is a string, not an object.

### What did you expect to happen?

The struct should have been logged as JSON object (`{...}`).

### How can we reproduce it (as minimally and precisely as possible)?

Run kubelet at -v4.

### Anything else we need to know?

Found when analyzing the WG structured logging Prow job artifacts.

### Kubernetes version

master

### Cloud provider

kind

**Comment by pohly** [comment]
This happens when passing `*v1.Container` (pointer) as value in the key/value pair. It works when passing `v1.Container` (value).

**Comment by pohly** [comment]
This seems to be how `zap.Reflect` handles pointers. Options for solving this:
- in Kubernetes: find values that are pointers via static analysis and treat that as error, then replace with value
- in zapr: when checking values, add reflection while iterating over key/value pairs and replace pointer with value on-the-fly (must be optional)
- in zap: make behavior or `zap.Reflect` configurable

**Comment by pohly** [comment]
Another, better option:
- in Kubernetes: wrap the `zapcore.Encoder` for JSON so that `AddReflected` first replaces a pointer with its value

This has the advantage that neither zap nor zapr must be changed and that the additional reflection step + copying only happens directly before it is needed.

**Comment by pohly** [comment]
I can only reproduce that for `*v1.Container`, but not for some custom struct?!

**Comment by NikhilSharmaWe** [comment]
@pohly can I work on this issue.

**Comment by pohly** [comment]
I should have looked closer. `*v1.Container` implements `String`, and that is what zap calls. It's a pointer receiver, which explains why it doesn't happen when passing by value (pointer receivers get called only for pointers).

The `String` implementation is in `generated.pb.go`, i.e. all API structs have this problem.

The best solution would be to auto-generate a `MarshalLog` function for all of these types. That means any log call will automatically do the right thing.

The second-best solution is to handle this at the call locations. Perhaps the static code analysis tool can handle this to detect it.

**Comment by pohly** [comment]
@NikhilSharmaWe: thanks for the offer, but this is not an easy problem. It's not at all clear how to solve it.

/assign

**Comment by pohly** [comment]
I tried stripping the `String` method by wrapping a `*v1.Container` like this:
```
func LogPointer(ptr fmt.Stringer) interface{} {
	return ptrWrapper{ptr: ptr}
}

type ptrWrapper struct {
	ptr fmt.Stringer
}

func (p ptrWrapper) String() string {
	return p.ptr.String()
}

func (p ptrWrapper) MarshalLog() interface{} {
	type noMethods interface{}
	return noMethods(p.ptr)
}

klog.InfoS(... "container", LogPointer(&v1.Container{})
```

Doesn't work. Normally a `type newType oldType` strips methods for `oldType`, but not here: `String` is still found by `zap.Any`.

**Comment by pohly** [comment]
The alternative is to generate this function for all types:
```
func (this *Container) MarshalLog() interface{} {
	type noStringer *Container
	return noStringer(this)
}
```

I think that needs to go into https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf, directly or indirectly. The String method itself seems to come from protoc.

**Comment by pohly** [comment]
Benchmarking shows now significant difference between JSON output with string vs. struct:
```
name                       old time/op  new time/op  delta
Logging/container/JSON-36  1.86ns ± 1%  1.86ns ± 2%   ~     (p=1.000 n=5+5)
```

**Comment by thockin** [comment]
Oddly the implementation of `String()` seems to be auto-generated (generated.pb.go).  I can't help but feel like we should NOT be doing that.

**Comment by thockin** [comment]
@smarterclayton or @wojtek-t  I didn't know PB code generated .String() methods for every type (and pretty useless definitions, too).  Curious if you have more color to add.

**Comment by pohly** [comment]
FWIW, given that logging of these structs so far has been done with the String() output and developers might expect that also in JSON output, I'm now leaning towards simply leaving everything as-is.

**Comment by ehashman** [comment]
> The struct should have been logged as JSON object ({...}).

I don't know that we actually have a guideline for this. It's not clear from the structured logging spec.

I don't think this is limited to node/v1.Container; I'm pretty sure any struct with a String() function will get logged like this, even with JSON logging turned on.


> The best solution would be to auto-generate a `MarshalLog` function for all of these types. That means any log call will automatically do the right thing.

I'd be worried about the performance implications of serializing these objects, possibly repeatedly, at runtime into JSON. This would make the kubelet's high CPU utilization issues worse.

**Comment by ehashman** [comment]
I think this needs further discussion before we can triage this, can we discuss at the Instrumentation and/or Architecture?

**Comment by thockin** [comment]
If you are concerned about serialization cost, there's not much the log
layer can do - you have to take control of that.

IMO, these String() methods are kind of awful.

**Comment by pohly** [comment]
> I don't know that we actually have a guideline for this. It's not clear from the structured logging spec.

That's the same conclusion that I arrived at later. It becomes a question of what the consumers of those particular log messages want to have, which isn't clear in this case. I asked for opinions on #sig-node, but got no response.

> I don't think this is limited to node/v1.Container; I'm pretty sure any struct with a String() function will get logged like this, even with JSON logging turned on.

We have a mechanism (`logr.Marshaler`) now to override that for specific types, if desired. The "if desired" part is what we need to figure out.

I'm fine with just closing this issue as I can see arguments for and against logging as string and don't have a preference myself.

**Comment by pohly** [comment]
/close

Let's assume that string output also in JSON is what developers want until we hear otherwise.

**Comment by liggitt** [comment]
> [@smarterclayton](https://github.com/smarterclayton) or [@wojtek-t](https://github.com/wojtek-t) I didn't know PB code generated .String() methods for every type (and pretty useless definitions, too). Curious if you have more color to add.

It gets even worse ... got here via https://github.com/kubernetes/kubernetes/pull/128653#discussion_r2183041963

our gogo protobuf hackery at least generated deterministic (though uglyish) String() implementations

standard protoc-gen-go generates String() implementations that delegate to `protoimpl.X.MessageStringOf(x)`, which is [intentionally non-deterministic](https://github.com/kubernetes/kubernetes/pull/128653/files#r2183073611)
