### ISSUE TITLE
Missing Azure File e2e tests

### ISSUE THREAD

**Issue by bertinatto** [kubernetes/kubernetes#106677]
### What happened?

Azure File is one of the intree storage plugins available in k8s, however, we currently don't have a e2e tests for it.

Having such tests would be helpful to test CSI migration for Azure File.

### What did you expect to happen?

Azure File e2e tests should run on Azure.

### How can we reproduce it (as minimally and precisely as possible)?

Just run the storage e2e test suite on an Azure cluster.

### Kubernetes version

1.23

### Cloud provider

Azure

**Comment by bertinatto** [comment]
CC @msau42

**Comment by Jiawei0227** [comment]
We are migrating all the cloud provider related tests to cloud-provider specific CI. So I think azurefile e2e test should be running on cloud-provider-azure or azurefile-csi-driver.

**Comment by andyzhangx** [comment]
actually you could run azure file e2e tests by, it's not in k/k repo:
```console
/test pull-kubernetes-e2e-aks-engine-azure-file-windows-conainerd
/test pull-kubernetes-e2e-aks-engine-azure-file-windows-dockershim
/test pull-kubernetes-e2e-capz-azure-file
/test pull-kubernetes-e2e-capz-azure-file-vmss
```

**Comment by bertinatto** [comment]
@Jiawei0227 I agree these jobs should be running on Azure-specific CI. However, the intree plugin code lives in kubernetes/kubernetes, so IMO the code for the tests should be hosted in the same code base.

@andyzhangx I believe those tests jobs you listed don't run the k/k test suite, they seem to run a different testsuite specific to Azure. As far as I know, one of the requirements for CSI migration is to run the k/k test suite.

**Comment by andyzhangx** [comment]
> @Jiawei0227 I agree these jobs should be running on Azure-specific CI. However, the intree plugin code lives in kubernetes/kubernetes, so IMO the code for the tests should be hosted in the same code base.
> 
> @andyzhangx I believe those tests jobs you listed don't run the k/k test suite, they seem to run a different testsuite specific to Azure. As far as I know, one of the requirements for CSI migration is to run the k/k test suite.

@bertinatto those azure file e2e tests could run against k/k PR, and could test against csi migration, see example PR here: https://github.com/kubernetes/kubernetes/pull/105070, we don't have resources to add those tests to k/k.

**Comment by jsafrane** [comment]
@andyzhangx running k/k tests is really a prerequisite for CSI migration GA, it covers Kubernetes features pretty well and we already caught couple of issues there.

**Comment by jsafrane** [comment]
Last example: https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1600
(vSphere does not have a public CI, but at least I can run the tests manually)

**Comment by andyzhangx** [comment]
@jsafrane actually there are already k/k e2e tests testing against azure file csi driver: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/test/external-e2e/run.sh#L27-L38, so it could be we change the provisioner to in-tree driver, those tests should test against csi migration also.

**Comment by jsafrane** [comment]
Check how Azure Disk in-tree volume tests are set up in https://github.com/kubernetes/kubernetes/blob/5b1e5387591dd3ad0b3ddacc9e44a6ac7260078e/test/e2e/storage/drivers/in_tree.go#L1541. The hardest part is `CreateVolume()`, that allows for testing in-line and pre-provisioned volumes and at the same time it needs to talk to the cloud outside of Kubernetes.

**Comment by andyzhangx** [comment]
> Check how Azure Disk in-tree volume tests are set up in
> 
> https://github.com/kubernetes/kubernetes/blob/5b1e5387591dd3ad0b3ddacc9e44a6ac7260078e/test/e2e/storage/drivers/in_tree.go#L1541
> 
> . The hardest part is `CreateVolume()`, that allows for testing in-line and pre-provisioned volumes and at the same time it needs to talk to the cloud outside of Kubernetes.

@jsafrane thanks, I see there are not a lot of tests, let me try to add azure file tests directly in that folder.
And how can I only run azuredisk tests?
follow command does not work.
```
go test -v -timeout=0 ./test/e2e -ginkgo.v -ginkgo.focus="In-tree Volumes.*azure-disk.*"
```

**Comment by andyzhangx** [comment]
just comment following code, and then `go test` it works, thanks!
```
diff --git a/test/e2e/storage/drivers/in_tree.go b/test/e2e/storage/drivers/in_tree.go
index d97c4f4b2b0..de805d54311 100644
--- a/test/e2e/storage/drivers/in_tree.go
+++ b/test/e2e/storage/drivers/in_tree.go
@@ -1573,7 +1573,7 @@ func (a *azureDiskDriver) GetDriverInfo() *storageframework.DriverInfo {
 }

 func (a *azureDiskDriver) SkipUnsupportedTest(pattern storageframework.TestPattern) {
-       e2eskipper.SkipUnlessProviderIs("azure")
+       //e2eskipper.SkipUnlessProviderIs("azure")
 }
```
