### ISSUE TITLE
It’s easy to overflow when casting resource.Quantity to int64 with BinarySI formate

### ISSUE THREAD

**Issue by leileiwan** [kubernetes/kubernetes#106681]
### What happened?

// test code
```
func TestBinary(t *testing.T) {

	bValue := resource.MustParse("100000Gi")
	_, ok := bValue.AsInt64()
	if !ok {
		t.Errorf("binarySI data %+v is overflow", bValue)
	}

	dValue := resource.MustParse("1000000000G")
	_, ok = dValue.AsInt64()
	if !ok {
		t.Errorf("decimalSI data %+v is overflow", dValue)
	}
}
```
// result
=== RUN   TestBinary
    util_test.go:42: binarySI data {i:{value:0 scale:0} d:{Dec:0xc00060fc20} s: Format:BinarySI} is overflow
--- FAIL: TestBinary (0.00s)

FAIL

// notice
100000Gi cast to int64 overflow but 1000000000G not

### What did you expect to happen?

The calculation concluded that the error is too large with BinarySI formate.

// https://github.com/kubernetes/apimachinery/blob/master/pkg/api/resource/quantity.go
I do not understand why use 15 to sub, 64*3/10=19 seems more reasonable
precision = 15 - int32(len(num)) - int32(float32(exponent)*3/10) - 1
```
switch format {
	case DecimalExponent, DecimalSI:
		scale = exponent
		precision = maxInt64Factors - int32(len(num)+len(denom))
	case BinarySI:
		scale = 0
		switch {
		case exponent >= 0 && len(denom) == 0:
			// only handle positive binary numbers with the fast path
			mantissa = int64(int64(mantissa) << uint64(exponent))
			// 1Mi (2^20) has ~6 digits of decimal precision, so exponent*3/10 -1 is roughly the precision
			precision = 15 - int32(len(num)) - int32(float32(exponent)*3/10) - 1
		default:
			precision = -1
		}
	}
```

### How can we reproduce it (as minimally and precisely as possible)?

none

### Anything else we need to know?

none

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/issues/102134#issuecomment-844696891

**Comment by leileiwan** [comment]
> See [#102134 (comment)](https://github.com/kubernetes/kubernetes/issues/102134#issuecomment-844696891)
> 
> ```
> // <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei
> //   (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)
> // <decimalSI>       ::= m | "" | k | M | G | T | P | E
> //   (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)
> // <decimalExponent> ::= "e" <signedNumber> | "E" <signedNumber>
> ```
> 
> #102134 and #49442 is similar.




It doesn't seem to solve my problem. The above test case proves that binarySI data(100000Gi) is easier to overflow than decimalSI(1000000000G) conversion to int64.
```
9223372036854775807（MaxInt64）
```

**Comment by yliaog** [comment]
@leileiwan i think you're right, 15 is too conservative. do you mind to send a PR to fix it?

**Comment by leileiwan** [comment]
> 15 was chosen as "deliberately below the limit" for safety in the fast path (at the time enough other stuff was changing that I didn't want to risk hitting the limit), if we are confident we can prove 18 is closer and have the tests to back it up i have no objection.

yeah, test cases in pr have proved 18 is safety, the 1000000000Gi which is less than MaxInt64 was overflowed after parse2Int64
