### ISSUE TITLE
After pod restart sctp traffic does not reach other pod behind Loadbalancer service

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [kubernetes/kubernetes#106651]
### What happened?

There were 2 pods serving sctp traffic behind Loadbalancer service(externaltrafficpolicy cluster). The  sctp client accessing the LB service reuses source port. After the pod to which the sctp client was connected is restarted(or stopped) the traffic is not routed to the other available endpoint because of stale conntrack entry, since the client continuously retries to establish connection(hence conntrack entry does not expire).

Proxy mode used is iptables.  

### What did you expect to happen?

When one sctp server pod behind the LB service is down the traffic should reach the other sctp server pod behind the same LB service.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Loadbalancer service with externaltrafficpolicy Cluster
2. Create 2 pods serving sctp traffic acting as endpoints for the Loadbalancer service.
3. Create a sctp client which accesses the Loadbalancer service and reuses source port and continuously(in few seconds) retries to establish connection if session is broken.
4. Delete the pod to which the sctp client is connected.
5. The traffic is not switched to the other pod.

### Anything else we need to know?

Looks like stale sctp conntrack entries are supposed to be deleted as below:
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/pkg/proxy/iptables/proxier.go#L731

But the place where such endpoints are collated skips sctp and only looks for UDP because of which sctp endpoints are not cleaned:
https://github.com/kubernetes/kubernetes/blob/c8c81cbfbb381129c904ed1ab387744946cf807a/pkg/proxy/endpoints.go#L544

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.21.1
```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
VERSION="20.04.3 LTS (Focal Fossa)"
$ uname -a
Linux ccd-focal-clus2-1 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# paste output here
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
yeah,
/triage accepted
/assign

**Comment by aojea** [comment]
it seems we should not clean the SCTP conntrack entries as in TCP, conntrack track the sessions so it should be able to close it

https://github.com/torvalds/linux/blob/dbe69e43372212527abf48609aba7fc39a6daa27/net/netfilter/nf_conntrack_proto_sctp.c#L79-L112

it may be possible this is a bug in the kernel conntrack implementation, there is a TODO in the source code that looks related
https://github.com/kubernetes/kubernetes/pull/106662#issuecomment-991103260

**Comment by aojea** [comment]
@VivekThrivikraman-est as next step I suggest to check if is a kernel problem, as we had with TCP.

If you can create a reproducer like I did for the TCP case
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/netfilter/conntrack_tcp_unreplied.sh

we can reach out to the netfilter community.

**Comment by VivekThrivikraman-est** [comment]
> @VivekThrivikraman-est as next step I suggest to check if is a kernel problem, as we had with TCP.
> 
> If you can create a reproducer like I did for the TCP case https://github.com/torvalds/linux/blob/master/tools/testing/selftests/netfilter/conntrack_tcp_unreplied.sh
> 
> we can reach out to the netfilter community.

Sure @aojea, will do it.

**Comment by VivekThrivikraman-est** [comment]
Have created an issue and script to reproduce in netfilter bugzilla:
https://bugzilla.netfilter.org/show_bug.cgi?id=1579

**Comment by aojea** [comment]
> Have created an issue and script to reproduce in netfilter bugzilla: https://bugzilla.netfilter.org/show_bug.cgi?id=1579

This kernel issue was fixed, thanks Florian Westphal and @VivekThrivikraman-est 

/close
