### ISSUE TITLE
[sample-controller] Wrong go version in go.mod file of the sample-controller

### ISSUE THREAD

**Issue by huikang** [kubernetes/kubernetes#106666]
### What happened?

go build -o sample-controller .
# sigs.k8s.io/json/internal/golang/encoding/json
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
vendor/sigs.k8s.io/json/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)

### What did you expect to happen?

The sample controller can be complied

### How can we reproduce it (as minimally and precisely as possible)?

Go version 1.16

go build -o sample-controller .

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Thanks for the issue. Since the method is in the sigs.k8s.io/json library, the correct place to update this would be in the sigs.k8s.io/json repo, not here. A PR in that repo would be fine if you wanted to open one.

**Comment by able8** [comment]
Thanks. Upgrading go version to 1.17 fixes this errro.
