### ISSUE TITLE
Update Sig-windows Memory Limits tests to not assume all nodes are the same

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#106608]
### What happened?

The test `[sig-windows] [Feature:Windows] Memory Limits [Serial] [Slow] attempt to deploy past allocatable memory limits should fail deployments of pods once there isn't enough memory`: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-staging-windows-serial-slow/1461874338100678656 is failing because it assumes the memory is the same across all nodes.

A change in the configuration https://github.com/kubernetes-sigs/windows-testing/pull/293 changed that assumption and the test started to fail.

### What did you expect to happen?

the test to assign the correct amount of memory to each of the nodes to fill them up.

### How can we reproduce it (as minimally and precisely as possible)?

create a Windows cluster with 3 nodes.  Two have 6gb of allocatable memory, 1 has 14gb of allocatable memory.  Run the test above and it will fail because it tries to create 3 pods with 9 gb of memory.  The first pod will land on the node with 14gb of memory but the other two pods won't be able to find a node with enough memory (9gb pod > 6 gb nodes).

### Anything else we need to know?

https://github.com/kubernetes-sigs/windows-testing/pull/297 fixes this in the configuration

/sig windows

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by NikhilSharmaWe** [comment]
@jsturtevant Please inform that Am I reasonable here or not.
We need to update the `vmsize` in all the cases inside the (`kubernetes_release_staging_serial.json`, `kubernetes_release_staging.json` and `kubernetes_containerd_nightly.json`) similar to what was done in this [this](https://github.com/kubernetes-sigs/windows-testing/pull/293) but in all cases.

**Comment by jsturtevant** [comment]
@NikhilSharmaWe sorry I could have been clearer in the issue.  The test it's self needs to be updated to handle nodes that do not have consistent memory.  

The logic in the test is wrong if the nodes  don't all have the same memory values: https://github.com/kubernetes/kubernetes/blob/aff056d8a197f6a404ad5e02210ca662d16c3dbe/test/e2e/windows/memory_limits.go#L111

This results in pods that won't fit on some of the nodes and leaves the pods pending.  The test should handle this situation by making sure pods filled up memory but can be scheduled across the nodes.  

Let me know of need more clarification.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant So, here we have to fix the logic because the logic is wrong for the case when the nodes don't have the same memory values, which is I think is `totalAllocatable.Value()`, Is it ? 
So, do we need to change `memValue := totalAllocatable.Value()` because it is the total memory and when it is fixed then the pods present will get appropriate memory limit by `memPerPod := memValue / int64(allocatablePods)`.
So, am I thinking reasonable here?
But, still I am not able to grasp that what actually we need to change in the logic. Could you please elaborate.

**Comment by jsturtevant** [comment]
> * So, if updating the logic for the value of `totalAllocatable.Value()` is our focus, such that the it (**memory limit**) is changed according to the nodes, **how can we achieve that** ?
 
Yes, I think think the simplest thing to so would be get a list of windows nodes iterate though each one, looking up the allocatable memory for the node, creating a pod to fill that memory and assign it to that node for scheduling via `nodeselector`, ensuring the scheduling was successful.  Then once the nodes are all full deploy the pod that should go into pending (code should stay the same).  

pseudo code:

```
nodes := getWindowsNodes()
for n:= range nodes
  nodeAllocatable=getNodeAllocatable(n)
  p := createPodForNode(nodeallocatable, n.nodename) 
  deployPod(p) == success
endfor

deployAnotherPodThatShouldBePending
```

**Comment by NikhilSharmaWe** [comment]
Do we have some examples in the repo where we do something similar for other nodes ?

First we need to make `getWindowsNodes()` function or is it already present ?

Also Do we need to run the whole code(After Modifying) inside `overrideAllocatableMemoryTest` in loop for every windows node and if even one return fails, the test fails.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant Do we have some examples in the repo where we do something similar for other nodes ?

First we need to make getWindowsNodes() function or is it already present ?

Confirming : Also Do we need to run the whole code(After Modifying) inside overrideAllocatableMemoryTest in loop for every windows node and if even one return fails, the test fails.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant I need some guidance. Could you please take a look on previous comment.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant I need some guidance. Could you please take a look on previous comment.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant I need some guidance. Could you please take a look on previous comment.

**Comment by NikhilSharmaWe** [comment]
@jsturtevant I need some guidance. Could you please take a look on previous comment.

**Comment by jsturtevant** [comment]
> @jsturtevant Do we have some examples in the repo where we do something similar for other nodes ?
> 
> First we need to make `getWindowsNodes()` function or is it already present ?

example of getting the nodes and memory total:
https://github.com/kubernetes/kubernetes/blob/aff056d8a197f6a404ad5e02210ca662d16c3dbe/test/e2e/windows/memory_limits.go#L232-L250



> **Confirming** : Also Do we need to run the whole code(After Modifying) inside `overrideAllocatableMemoryTest` in loop for every windows node and if even one return fails, the test fails.

no, basically need to replace some of the code in that function with the sudo code in https://github.com/kubernetes/kubernetes/issues/106608#issuecomment-982008740

**Comment by NikhilSharmaWe** [comment]
@jsturtevant Why are we not deploying both the pods of in one loop only (if the memory pods memory is same as nodes memory).
Also after we deploys both the pods, do we will be running another loop similar to [this](https://github.com/kubernetes/kubernetes/blob/aff056d8a197f6a404ad5e02210ca662d16c3dbe/test/e2e/windows/memory_limits.go#L121-L132) for checking the failure.

I am not confident on my changes, can I make a PR so that I can discuss about my code and move forward ?

**Comment by jsturtevant** [comment]
> can I make a PR so that I can discuss about my code and make appropriate changes further ?

Sounds good

**Comment by NikhilSharmaWe** [comment]
@jsturtevant Does functions `getNodeAllocatable(n)` and `createPodForNode(nodeallocatable, n.nodename)` already exists because I am not able to find, have you used these names as short forms for other functions which do same as their names ?
