### ISSUE TITLE
StatefulSet PVC tests failing

### ISSUE THREAD

**Issue by mattcary** [kubernetes/kubernetes#106615]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106568/pull-kubernetes-unit/1462136832413143040

### Which tests are failing?

StatefulSet control tests

### Since when has it been failing?

The delete PVC unit tests started flaking when https://github.com/kubernetes/kubernetes/pull/99728 was merged

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106568/pull-kubernetes-unit/1462136832413143040

### Reason for failure (if possible)

#99728 exposed a sharp edge in UpdateStatefulSet, where the set was assumed to be unmodified, but actually creating a new revision for it changes it.

### Relevant SIG(s)

/sig apps

/assign @mattcary

**Comment by mattcary** [comment]
Additional flakes found using stress:

```
go test -race -c ./pkg/controller/statefulset/
stress ./statefulset.test 
...
--- FAIL: TestStatefulSetControl (15.48s)
    --- FAIL: TestStatefulSetControl/CreatesPods/Monotonic/Retain/StatefulSetAutoDeletePVCEnabled (0.01s)
        stateful_set_control_test.go:196: Failed to turn up StatefulSet : claim for Pod foo-0 was not created
        stateful_set_control_test.go:204: Failed to scale statefulset to 3 replicas
        stateful_set_control_test.go:207: Failed to set ReadyReplicas correctly
        stateful_set_control_test.go:210: Failed to set UpdatedReplicas correctly
```

**Comment by liggitt** [comment]
Updated triage showing sharp increase in statefulset failures/flakes after 11/18

https://storage.googleapis.com/k8s-triage/index.html?test=%5BsS%5Dtateful%5BsS%5Det&xjob=flaky%7Cwindows%7Ccount10&xtest=Volume%7C%5E(Up%7CTest%7CTimeout%7CTearDown%7CUpgradeTest)%24

**Comment by mattcary** [comment]
Hurrah, I figured it out. See #107443.
