### ISSUE TITLE
Standard for Type=LoadBalancer Service TLS configuration

### ISSUE THREAD

**Issue by collimarco** [kubernetes/kubernetes#106603]
### What would you like to be added?

A standard (spec) to define the SSL certificate and private key for an external LoadBalancer.

### Why is this needed?

When you use an **external LoadBalancer** you usually need SSL / TLS / HTTPS (this is a requirement for most applications nowadays).

Currently you can specify [SSL for an Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls), but you can't do it for an external LoadBalancer.

For performance reasons and for increased visibility, it can be useful to have **SSL termination at LoadBalancer level**, instead of doing all the work inside the cluster.

Without a standard, each provider is implementing this feature in a different/incompatible way. 

For example:

- DigitalOcean: https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/
- AWS: https://aws.amazon.com/premiumsupport/knowledge-center/terminate-https-traffic-eks-acm/
- Vultr: https://www.vultr.com/docs/vultr-kubernetes-engine#VKE_Load_Balancer
- etc.

Also note that some providers (e.g. DigitalOcean, AWS) require annotations together with manual actions through the dashboard, while others (e.g. Vultr) are based on a secret stored inside the cluster. Providers like Google require even more complex configurations... 

Everyone is using a completely different strategy and this makes it **impossible to use the same YML configuration** and deployment method for different cloud providers. Sometimes it's **not even possible to automate the process** completely (you need manual actions).

I think that would be extremely useful to **define a standard (spec) to set the SSL certificate and private key for a LoadBalancer**.

**Comment by sftim** [comment]
/retitle Standard for Type=LoadBalancer Service TLS configuration

**Comment by sftim** [comment]
Sounds like a big challenge to me. Cloud infrastructure takes different kinds of configuration, whether Kubernetes likes it or not. Some providers act as CAs and issue their own X.509 certificates; other providers expect you to get your own and upload the private key material. Maybe there's a provider that generates a key and gives you a CSR to get signed.

An API that covers all these cases is going to be pretty broad.

That's why https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#ssl-cert is different from https://kubernetes.io/docs/concepts/services-networking/service/#other-clb-annotations-on-tencent-kubernetes-engine-tke and why GCP is different again: because the cloud providers' own APIs are equally different.

Some load balancers act on logical octet streams, some on packets, and some understand HTTP. They're _just plain different_.

Even the new [Gateway](https://kubernetes.io/blog/2021/04/22/evolving-kubernetes-networking-with-the-gateway-api/) API can't make fundamentally different provider APIs become compatible with one another. It'd be a sharper mind than mine that could work out a way to do it.

**Comment by collimarco** [comment]
> An API that covers all these cases is going to be pretty broad.

Actually I think that **most providers are already using a similar strategy**:
1. You provide a TLS certificate (e.g. using a native K8s secret of type TLS)
2. You reference that TLS secret name in the LoadBalancer annotation (in the future this could be moved to spec, like Ingress already does).

Some providers ask to upload the secret manually from their dashboard and then reference it in the annotation, but if we make a standard it would make sense to keep everything, including the TLS cert, inside Kubernetes (e.g. Vultr already does this).

> the new Gateway API 

My proposal is about the Service LoadBalancer, not about Ingress (which already has a tls field in the spec).

In practice we need [something like this](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls), but **for the external LoadBalancer**.

**Comment by aojea** [comment]
> In practice we need [something like this](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls), but **for the external LoadBalancer**.

if you check the link that you are referencing there is a note that says

> Note: There is a gap between TLS features supported by various Ingress controllers. Please refer to documentation on nginx, GCE, or any other platform specific Ingress controller to understand how TLS works in your environment.

**Comment by collimarco** [comment]
@aojea The details are different, yes, and that's the point of opening this issue... IMHO K8s should provide standardization for such a common use case (load balancer with SSL/TLS secret). 

In any case the note that you mention, which is about Ingress, shows that both nginx and Google have much in common... they both use `tls:` in the Ingress spec to reference the secret. Only the implementation details are different, not the  strategy. And that's why [a standard](https://github.com/kubernetes/kubernetes/issues/106603#issuecomment-978982483) would be useful...

**Comment by collimarco** [comment]
Here's another provider that uses the same strategy for the external LoadBalancer (annotations + tls secret):

Linode: https://www.linode.com/docs/guides/getting-started-with-load-balancing-on-a-lke-cluster/

**Comment by collimarco** [comment]
Basically **it would be as simple as adding the following to the LoadBalancer spec**:

1. add an optional `protocol` attribute to `spec`, with values `tcp` (default) or `http` (for level 7 load balancer)
2. add an optional `ssl: tls-secret-name` attribute to `ports[*]`

Most providers (see links above) could easily adopt the new spec, by just renaming their current annotations...

Please let me know what you think about this proposal.

**Comment by aojea** [comment]
I like the idea, and I think that it will be the ideal, but I personally find that is too late to include it in an overloaded API like `Services`. It also depends on the cloud providers, just see how long it takes to agree in one field https://github.com/kubernetes/enhancements/issues/1435

> Most providers (see links above) could easily adopt the new spec, by just renaming their current annotations...

Those kind of changes are hard to implement, they are not easy, you need to live with 2 implementations, support both, support migrations ...., is not that you can say  "since X version annotations on LB doesn't work, just use these fields".

That is my opinion, if you can convince @thockin , I'm happy to help ;)

**Comment by thockin** [comment]
My gut instinct is to agree with @aojea on this.  I'd rather see support added to Gateway (it should already be possible to express this, I think) than to add more and more to Service.

I am afk today, but I will let this cook in the back of my brain.

**Comment by robscott** [comment]
Discussed this briefly at sig-network meeting yesterday, I think this is very much in scope for [Gateway API](https://gateway-api.sigs.k8s.io/), but probably not something that makes sense to try to add to Services. We're trying to add significantly more advanced load balancing capabilities there, including TLS configuration.

**Comment by collimarco** [comment]
@robscott Ok, I really hope to see something standard across providers (not like current LoadBalancer annotations).

I would love to see a standard inside Service because it is **simple** and **already implemented** in most cloud provider... However if it's too late it doesn't matter... **

I just hope to see a standard for load balancing that works on all major providers in the same way and allows configuration of TLS/SSL** (and maybe other common needs, like public static IP). At the end of the day, it doesn't matter if it's called Service or something else, like Gateway API.

Any idea when the Gateway API will become available?

**Comment by robscott** [comment]
@collimarco I agree that something standardized across providers would be ideal, we're trying to do that as much as possible with Gateway API. Some aspects are surprisingly difficult to get right though as there are non trivial variations in some cases. The example @aojea linked above (https://github.com/kubernetes/enhancements/issues/1435) helps show how complex this can get.


>  allows configuration of TLS/SSL (and maybe other common needs, like public static IP)

Both are already possible with Gateway API.

> Any idea when the Gateway API will become available?

Depends on your provider, the list of [implementations](https://gateway-api.sigs.k8s.io/implementations/) is constantly growing. Our goal is to reach beta sometime early next year, I'd expect more cloud provider implementations around that point.

**Comment by bowei** [comment]
@collimarco our hope is that the Gateway API will meet your requirements:

* It is standardized across providers (and you can install your own)
* It offers all the extensibility and knobs required for configuring TLS

Note that TLS configuration can become quite complex when you get beyond
configuring just a certificate and secret and adding that complexity into the
existing Service resource could get quite hairy.

I am going to close this for now with the recommendation to take a look at 
Gateway and identify where it cannot meet your requirements.

/close
