### ISSUE TITLE
Run kube-controller-manager with binary mode failed

### ISSUE THREAD

**Issue by zhucan** [kubernetes/kubernetes#106763]
### What happened?
![image](https://user-images.githubusercontent.com/13997135/144202783-bd64babd-83c6-48c2-bc22-eeb907c80f91.png)

### What did you expect to happen?

Run kube-controller-manager with binary mode successfully.

### How can we reproduce it (as minimally and precisely as possible)?

1. git clone https://github.com/kubernetes/kubernetes.git
2. cd GOPATH/src/github.com/kubernetes/kubernetes
3. make what=./cmd/kube-controller-manager
4. Exec "./_output/bin/kube-controller-manager --allocate-node-cidrs=true --authentication-kubeconfig=/etc/kubernetes/controller-manager.conf --authorization-kubeconfig=/etc/kubernetes/controller-manager.conf --bind-address=127.0.0.1 --client-ca-file=/etc/kubernetes/pki/ca.crt --cluster-cidr=10.244.0.0/16 --cluster-name=kubernetes --cluster-signing-cert-file=/etc/kubernetes/pki/ca.crt --cluster-signing-key-file=/etc/kubernetes/pki/ca.key --controllers=*,bootstrapsigner,tokencleaner --kubeconfig=/etc/kubernetes/controller-manager.conf --leader-elect=false --node-cidr-mask-size=24 --requestheader-client-ca-file=/etc/kubernetes/pki/front-proxy-ca.crt --root-ca-file=/etc/kubernetes/pki/ca.crt --service-account-private-key-file=/etc/kubernetes/pki/sa.key --service-cluster-ip-range=10.96.0.0/12 --use-service-account-credentials=true"

### Kubernetes version

![image](https://user-images.githubusercontent.com/13997135/144202517-2caac995-cc75-423e-8ac5-26db77c9ec99.png)

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

kubeadm

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yliaog** [comment]
did you start the kube apiserver? it looks the controller manager has trouble to discover resources

**Comment by zhucan** [comment]
apiserver is running.

**Comment by pacoxu** [comment]
any update?
Agree with @yliaog, most likely, the apiserver has some problems, or the connection between controller-manager and apiserver is broken. 
BTW, the apiserver is 1.19 and the master branch of controller-manager is now 1.23 or even 1.24 alpha, the version is not compatible.
