### ISSUE TITLE
Why my apiserver requests per second so high, but everything is OK?

### ISSUE THREAD

**Issue by sunlintong** [kubernetes/kubernetes#106760]
### What happened?

**My cluster’s apiserver seems handling millions of request per-second, what’s the wrong?**  

I execute the follow promql to get apiserver qps:
```
topk(10, sum(irate(apiserver_request_total[5m]))without(component, job))
```
response:
```
{code="200", contentType="application/vnd.kubernetes.protobuf", resource="persistentvolumes", scope="cluster", verb="GET", version="v1"} 
11731218.203982122
{code="200", contentType="application/vnd.kubernetes.protobuf", resource="persistentvolumeclaims", scope="namespace", verb="GET", version="v1"} 
11639428.28118651
{code="200", contentType="application/json", group="argoproj.io", resource="applications", scope="namespace", verb="PATCH", version="v1alpha1"} 
11479909.256607212
{code="200", contentType="application/json", resource="configmaps", scope="namespace", verb="GET", version="v1"} 
9541565.014221862
{code="200", contentType="application/json", resource="pods", scope="namespace", verb="LIST", version="v1"} 
9079504.063388867
{code="200", contentType="application/json", group="apps", resource="deployments", scope="namespace", verb="LIST", version="v1"} 
8947495.73344169
{code="200", contentType="application/vnd.kubernetes.protobuf", group="coordination.k8s.io", resource="leases", scope="namespace", verb="GET", version="v1"} 
6161645.875660301
{code="200", contentType="application/json", group="apps", resource="statefulsets", scope="namespace", verb="LIST", version="v1"} 
5423756.281734149
{code="200", contentType="application/json", group="apps", resource="daemonsets", scope="namespace", verb="LIST", version="v1"} 
5423471.422991798
{code="0", contentType="application/vnd.kubernetes.protobuf;stream=watch", resource="secrets", scope="namespace", verb="WATCH", version="v1"} 
4798630.841121496
```
As you see, the QPS is more than 10 millions. It’s **unbelievable**!
There’s only 21 nodes(3 of them is master, means 3 apiserver replicas) and 2000+ pods in my cluster.
And every apiserver replicas user no more than 1 core CPU and 4Gi memory. They shouldn’t hold so much request, who can tell me why?

BTW, I also opened a discussion at [https://discuss.kubernetes.io/t/why-my-apiserver-qps-so-high-but-everything-is-ok/18171](https://discuss.kubernetes.io/t/why-my-apiserver-qps-so-high-but-everything-is-ok/18171).

### What did you expect to happen?

Normal QPS value.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know. I can only tell you my environment.

### Anything else we need to know?

```
$ kubectl get node | wc -l
21

$ kubectl get pod --all-namespaces | wc -l
2337

$ kubectl top node
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
node10   10386m       23%    100750Mi        40%       
node15   6699m        18%    147153Mi        67%       
node16   16755m       37%    113746Mi        46%       
node18   9266m        25%    228007Mi        103%      
node27   17247m       38%    121547Mi        49%       
node28   13301m       29%    100268Mi        40%       
node29   6783m        15%    70531Mi         28%       
node30   5277m        11%    72072Mi         29%       
node31   9835m        21%    136926Mi        55%       
node32   7719m        17%    155153Mi        62%       
node79   5354m        14%    89376Mi         40%       
node82   6896m        15%    130517Mi        52%       
node83   10415m       23%    90677Mi         36%       
node84   1199m        4%     9598Mi          8%        
node85   2230m        9%     38122Mi         29%       
node86   1609m        6%     13250Mi         10%       
node87   6446m        26%    84130Mi         74%       
node88   9379m        39%    77181Mi         59%       
node89   9115m        28%    95447Mi         74%       
node91   7365m        23%    90537Mi         70% 
```
### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.16", GitCommit:"7a98bb2b7c9112935387825f2fce1b7d40b76236", GitTreeState:"clean", BuildDate:"2021-02-17T11:52:32Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
bare-metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux l-172016023085-ops.cloudminds.com 4.15.0-55-generic #60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd 1.2.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI and version: flannel 0.11.0
CRI and version: containerd 1.2.6
</details>

**Comment by aojea** [comment]
You can enable the apiserver audit logs and have more granularity https://kubernetes.io/docs/tasks/debug-application-cluster/audit/ to understand what is generating those queries

**Comment by sunlintong** [comment]
I used this audit config to watch pod audit log.
```yaml
apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "ResponseComplete"
rules:
  # Log pod changes at RequestResponse level
  - level: Request
    resources:
    - group: ""
      # Resource "pods" doesn't match requests to any subresource of pods,
      # which is consistent with the RBAC policy.
      resources: ["pods"]
  # Log "pods/log", "pods/status" at Metadata level
  - level: Metadata
    resources:
    - group: ""
      resources: ["pods/log", "pods/status"]
```
The log quantity is small. not reaching the million level.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. Thanks for opening a post on the forums; you may also want to try reaching out on slack, perhaps in the #kubernetes-users channel.

/remove-kind bug
/kind support
/close

**Comment by sunlintong** [comment]
Why ths is not a **BUG**?
I think the millions of request is incredible.
Source code here:   
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L495-L530

/reopen

**Comment by aojea** [comment]
> I think the millions of request is incredible.

you need to find out who is doing those requests, if is not a kubernetes component like the controller-manager or the kube-scheduler is not a bug, is something in your cluster

**Comment by sunlintong** [comment]
I analysed the audit log, it's normal. And I think there is no need to find out who is doing those requests. Do you think one container use just 1 core、4Gi can hold 10 millions of request per second?

**Comment by aojea** [comment]
> I analysed the audit log, it's normal. And I think there is no need to find out who is doing those requests. Do you think one container use just 1 core、4Gi can hold 10 millions of request per second?

I think that there is a miscommunication problem here, if you think there is a bug you should explain where is the bug and how to reproduce it, you are saying that the the metric is wrong? or it not measuring the requests correctly?

**Comment by sunlintong** [comment]
Thanks for apply. Yes, I think it not measuring the requests correctly. But actually I don't know how to reproduce. Because only my prod environment has this questions. It doesn't mesure my k8s cluster. I jusr think this is a metric bug and I want know why.

**Comment by dgrisonnet** [comment]
Thank you for raising this issue @sunlintong, but besides the question of whether this is a bug or a support request, your environment is using an outdated Kubernetes version that is not supported anymore, which is a valid reason to close an issue. So I will be closing it again for now until you are able to reproduce the problem on a supported version. see https://kubernetes.io/releases/version-skew-policy/

That said, if you are able to reproduce this problem on a more recent version of kubernetes, it could be worth checking how many times a single query is counted. For example, if you purposely do an odd query resulting in a 404 or 503, you should be able to see by how much the metrics increased based on your query alone.

/close
