### ISSUE TITLE
Pod stuck in terminating state with pod worker exit and containers not exist

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#106734]
### What happened?

Pod stuck in terminating state in my k8s cluster（v1.20.10）. Finally I found that the pod worker exit and the pod’s containers not exist already by log message. Restart kubelet could resolve the problem.

### What did you expect to happen?

Kill pod successfully even there is no containers exist in runtime.

### How can we reproduce it (as minimally and precisely as possible)?

it's a race condition problem, when to delete a pod without any containers exist.

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/8152330a2b6ca3621196e62966ef761b8f5a61bb/pkg/kubelet/kubelet_pods.go#L1080-L1099

Line 1080: activePods not containers the pod that stuck in terminating state with no containers exist.
Line 1087: the pod worker for the pod  that stuck in terminating state with no containers exist exit.
Line 1090: runningPods contains the terminating pod. runtimeCache has 2s delay.
Line 1097: killPod return error because container not exist already.

Finally, pod worker exit, housekeeper ticker triggered but killPod always return err `No such conainer:`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10" ...}
</details>

**Comment by ehashman** [comment]
1.20 is now in maintenance mode only. Dockershim has been removed from 1.24 so a dockershim specific change won't be merged.

I believe this may be addressed in 1.22+ with the pod lifecycle refactor. Can you please try upgrading to see if it's fixed?

/close
