### ISSUE TITLE
Watcher not able to raise events after the mentioned resource version for client version 1.22.4

### ISSUE THREAD

**Issue by akshaydmore** [kubernetes/kubernetes#106790]
### What happened?

Getting the resource version of existing CRD and  using it in watcher to get events after mentioned version and then chaning the CRD,  1.22.3 is giving me the MODIFIED event but not 1.22.4.

### What did you expect to happen?

It should give modified event.

### How can we reproduce it (as minimally and precisely as possible)?

Use 1.22.4 for reproduction and guess it will be reproducible for any resource.

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"32a137c122b0474c719988922410f4027a4b002e", GitTreeState:"clean", BuildDate:"2021-11-01T16:43:17Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"32a137c122b0474c719988922410f4027a4b002e", GitTreeState:"clean", BuildDate:"2021-11-01T16:43:17Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

azure

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by akshaydmore** [comment]
triage/foo

**Comment by akshaydmore** [comment]
priority/important-soon

**Comment by liggitt** [comment]
no changes related to CRDs or watches were merged between 1.22.3 and 1.22.4

do you have a minimal reproducer program demonstrating how you're constructing the watcher and awaiting modified events?

**Comment by akshaydmore** [comment]
def start _watcher(self, _request_timeout=0):
        stream_kwargs = copy.deepcopy(self.kwargs)
        stream_kwargs['_request_timeout'] = 120
        stream_kwargs['field_selector'] = None if not self.obj \
            else "metadata.name={}".format(self.obj)
        if self.resource_version:
            stream_kwargs['resource_version'] = self.resource_version
        watch = self.watch.stream(
            self.func, **stream_kwargs)
        return watch

this is basically warapper to prepare stream, field selector we have CRD name in it and self.watch = Watch(). same code is working for 1.22.3 but not for 1.22.4

**Comment by akshaydmore** [comment]
Did you try reproducing beacause m able to reproduced it .

**Comment by liggitt** [comment]
that looks like python, so I'm not sure what client library you are using.

I was unable to reproduce with the versions in your issue description:

start a 1.21.2 server:

```
$ git checkout v1.21.2
$ hack/local-up-cluster.sh &
```

build a 1.22.3 kubectl, create a crd, then start watching:

```
$ git checkout v1.22.3
$ make kubectl
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-12-06T13:56:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-12-06T13:49:31Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl apply -f crd.yaml

customresourcedefinition.apiextensions.k8s.io/foos.example.com created

$ kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions

{"kind":"CustomResourceDefinitionList","apiVersion":"apiextensions.k8s.io/v1","metadata":{"resourceVersion":"334"},"items":[{"metadata":{"name":"foos.example.com","uid":"c077be6e-55ad-4d09-af97-87e26dd19c33","resourceVersion":"327" ...

$ kubectl get --raw '/apis/apiextensions.k8s.io/v1/customresourcedefinitions?resourceVersion=327&watch=true'
```

in another tab, modify the CRD:

```
$ kubectl annotate crd foo=baz --all --overwrite 
```

first tab sees modified event:
```
{"type":"MODIFIED","object":{"kind":"CustomResourceDefinition","apiVersion":"apiextensions.k8s.io/v1","metadata":{"name":"foos.example.com","uid":"c077be6e-55ad-4d09-af97-87e26dd19c33","resourceVersion":"338","generation":1,"creationTimestamp":"2021-12-06T14:09:00Z","annotations":{"foo":"baz",...
```

I then repeated the test with a 1.22.4 kubectl and saw the same expected behavior:
```
$ git checkout v1.22.4
$ make kubectl
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-12-06T14:15:00Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-12-06T13:49:31Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}

$ kubectl get --raw /apis/apiextensions.k8s.io/v1/customresourcedefinitions

{"kind":"CustomResourceDefinitionList","apiVersion":"apiextensions.k8s.io/v1","metadata":{"resourceVersion":"364"},"items":[{"metadata":{"name":"foos.example.com","uid":"c077be6e-55ad-4d09-af97-87e26dd19c33","resourceVersion":"338"...

$ kubectl get --raw '/apis/apiextensions.k8s.io/v1/customresourcedefinitions?resourceVersion=338&watch=true'
```

in another tab:

```
$ kubectl annotate crd foo=bar --all --overwrite 
```

in the first tab:
```
{"type":"MODIFIED","object":{"kind":"CustomResourceDefinition","apiVersion":"apiextensions.k8s.io/v1","metadata":{"name":"foos.example.com","uid":"c077be6e-55ad-4d09-af97-87e26dd19c33","resourceVersion":"369","generation":1,"creationTimestamp":"2021-12-06T14:09:00Z","annotations":{"foo":"bar"...
```

**Comment by akshaydmore** [comment]
we have same python version for kubernetes libraray  1.12 while testing with both 1.22.3 and 1..22.4

**Comment by akshaydmore** [comment]
then are you guys suspecting anything that could go wrong in implementaion ? and also i hoped you used watch from kubernetes python library ?
