### ISSUE TITLE
grpc field name in probes is not consistent between json and proto

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#106772]
### What happened?

The new grpc probe feature introduced a new field for grpc probes that has an inconsistent name between json and proto and needs to be changed before release goes out. Otherwise this inconsistency will be stayed forever as it will be close to impossible to change field names.

See thread: https://kubernetes.slack.com/archives/CJUQN3E4T/p1638309300059900

/sig node
/priority critical-urgent
/milestone 1.23

### What did you expect to happen?

Field https://github.com/kubernetes/kubernetes/blob/e4952f32b79b69bfa9333ff9da26a2da13859148/staging/src/k8s.io/api/core/v1/types.go#L2471 to be called `grpc` (all lower case).

### How can we reproduce it (as minimally and precisely as possible)?

this is just a schema change

### Kubernetes version

1.23

### Cloud provider

Either

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
resolved in master and release-1.23
