### ISSUE TITLE
throw unable to upgrade connection exception by executor.Stream ?

### ISSUE THREAD

**Issue by smallAttr** [kubernetes/kubernetes#106741]
### What happened?

I used command `remotecommand`( import "k8s.io/client-go/tools/remotecommand") to create streamExecutor. 
when I exec this code 
executor.Stream(remotecommand.StreamOptions{
			Stdin:             t,
			Stdout:            t,
			Stderr:            t,
			Tty: 			   true,
			TerminalSizeQueue: t,
		})
and throw error **unable to upgrade connection....** .

debug and I found that the source code only accepts httpStatusCode=101 and my response is 200
so what should I do to avoid this error？

### What did you expect to happen?

I hope to get the correct pod's log and this error no longer occurs

### How can we reproduce it (as minimally and precisely as possible)?

my code：
```
config, err := clientcmd.RESTConfigFromKubeConfig([]byte(db.GetKubeConfig(env, region)))
	if err != nil {
		return err
	}
	groupversion := schema.GroupVersion{
		Group:   "",
		Version: "v1",
	}
	config.GroupVersion = &groupversion
	config.APIPath = "/api"
	config.ContentType = runtime.ContentTypeJSON
	config.NegotiatedSerializer = serializer.DirectCodecFactory{CodecFactory: scheme.Codecs}
	restclient, err := rest.RESTClientFor(config)
	if err != nil {
		return err
	}
	fn := func() error {
		req := restclient.Get().
			Resource("pods").
			Name(t.pod).
			Namespace(t.namespace).
			SubResource("log").
			Param("pretty", "true")
		req.VersionedParams(
			&v1.PodLogOptions{
				Container: t.container,
			},
			scheme.ParameterCodec,
		)
		executor, err := remotecommand.NewSPDYExecutor(
			config, http.MethodGet, req.URL(),
		)
		if err != nil {
			return err
		}
		return executor.Stream(remotecommand.StreamOptions{
			Stdin:             t,
			Stdout:            t,
			Stderr:            t,
			Tty: 			   true,
			TerminalSizeQueue: t,
		})
	}
	inFd, _ := term.GetFdInfo(t.conn)
	state, err := term.SaveState(inFd)
	return interrupt.Chain(nil, func() {
		term.RestoreTerminal(inFd, state)
	}).Run(fn)
```
source code：
```
func (s *SpdyRoundTripper) NewConnection(resp *http.Response) (httpstream.Connection, error) {
	connectionHeader := strings.ToLower(resp.Header.Get(httpstream.HeaderConnection))
	upgradeHeader := strings.ToLower(resp.Header.Get(httpstream.HeaderUpgrade))
	if (resp.StatusCode != http.StatusSwitchingProtocols) || !strings.Contains(connectionHeader, strings.ToLower(httpstream.HeaderUpgrade)) || !strings.Contains(upgradeHeader, strings.ToLower(HeaderSpdy31)) {
		defer resp.Body.Close()
		responseError := ""
		responseErrorBytes, err := ioutil.ReadAll(resp.Body)
		if err != nil {
			responseError = "unable to read error from server response"
		} else {
			// TODO: I don't belong here, I should be abstracted from this class
			if obj, _, err := statusCodecs.UniversalDecoder().Decode(responseErrorBytes, nil, &metav1.Status{}); err == nil {
				if status, ok := obj.(*metav1.Status); ok {
					return nil, &apierrors.StatusError{ErrStatus: *status}
				}
			}
			responseError = string(responseErrorBytes)
			responseError = strings.TrimSpace(responseError)
		}

		return nil, fmt.Errorf("unable to upgrade connection: %s", responseError)
	}

	return NewClientConnectionWithPings(s.conn, s.pingPeriod)
}
```

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

# On Mac:
# MacOS Big Sur
# 11.2.3 M1
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jcleira** [comment]
I started investigating this yesterday.

/assign

**Comment by piwenzi** [comment]
i have the same promble,when i attach to pod container 

code:
	fmt.Println("podName=", pod.Name)
	req := clientSet.CoreV1().RESTClient().Post().Namespace(pod.Namespace).
		Resource("pods").Name(pod.Name).SubResource("attach").
		VersionedParams(&corev1.PodAttachOptions{
			TypeMeta: metav1.TypeMeta{
				Kind:       "EphemeralContainers",
				APIVersion: "v1",
			},
			Container: debugContainerName,
			Stdin:     true,
			Stdout:    true,
			Stderr:    true,
			TTY:       true,
		}, scheme.ParameterCodec)

	klog.Info("pujun---reqURL:", req.URL())

	exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
	if err != nil {
		klog.Error("pujun----exec-err:", err)
	}

	screen := struct {
		io.Reader
		io.Writer
	}{os.Stdin, os.Stdout}

	if err = exec.Stream(remotecommand.StreamOptions{
		Stdin:  screen,
		Stdout: screen,
		Stderr: screen,
		Tty:    true,
	}); err != nil {
		klog.Error("pujun-Stream-err:", err)
	}

error :
podName= ephemeral-demo
I0325 07:56:24.147918    7528 main.go:144] pujun---reqURL:https://10.221.105.223:6443/api/v1/namespaces/default/pods/ephemeral-demo/attach?container=pujun-kz7b2&stderr=true&stdin=true&stdout=true&tty=true
pujun----------------- https://10.221.105.223:6443/api/v1/namespaces/default/pods/ephemeral-demo/attach?container=pujun-kz7b2&stderr=true&stdin=true&stdout=true&tty=true
E0325 07:56:24.205148    7528 main.go:163] pujun-Stream-err:unable to upgrade connection: container pujun-kz7b2 not found in pod ephemeral-demo_default


but i can not find any error  in api-server

**Comment by jcleira** [comment]
@piwenzi sorry for the delay, not sure if you figured it out but on the error message you got the reason for it:

```
container pujun-kz7b2 not found in pod ephemeral-demo_default
```
