### ISSUE TITLE
Volumes are detached while they're still mounted on a node

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#106710]
### What happened?

A/D controller tries to detach volumes that are still mounted after 6 minutes. The conditions to trigger the detach are: https://github.com/kubernetes/kubernetes/blob/9a75e7b0fd1b567f774a3373be640e19b33e7ef1/pkg/volume/util/util.go#L387

I.e. all containers are finished. But that does not guarantee that volumes are unmounted. When a CSI driver can't unmount a volume for 6 minutes, the volume is force detached by A/D controller, corrupting the volume and leaving volume mounts on the node in a bad state. Note that the node is perfectly healthy, it just can't unmount a volume from whatever reason.

### What did you expect to happen?

A/D controller detaches volumes after a Pod is deleted from the API server, i.e. the volumes are unmounted or someone force-deleted the pods.

### How can we reproduce it (as minimally and precisely as possible)?

Very artificial reproducer:

1. Run a Pod with an attachable CSI volume.
2. On the node, make the volume mount busy, e.g.:
    ```
    cd /var/lib/kubelet/pods/f377d5c5-1463-4d55-ad80-51a3e12e2251/volumes/kubernetes.io~csi/pvc-2443e93b-380f-4015-bda9-3a71ddc6e737/mount
    ```
    Every unmount of the volume fails and kubelet/the CSI driver periodically retry.
3. Delete the pod
4. After 6 minutes, see the volume is detached without unmounting first.

KCM logs:
```
W1129 10:46:55.629375    9230 reconciler.go:224] attacherDetacher.DetachVolume started for volume "pvc-2443e93b-380f-4015-bda9-3a71ddc6e737" (UniqueName: "kubernetes.io/csi/ebs.csi.aws.com^vol-0e6b91392bdce66f3") on node "ip-172-18-5-140.ec2.internal" This volume is not safe to detach, but maxWaitForUnmountDuration 6m0s expired, force detaching
```

Note that the Pod is still in the API server:
```
NAME      READY   STATUS        RESTARTS   AGE
testpod   0/1     Terminating   0          9m26s
```

And the node is healthy:
```
NAME                           STATUS   ROLES    AGE   VERSION
ip-172-18-5-140.ec2.internal   Ready    <none>   10m   v1.24.0-alpha.0.9+9a75e7b0fd1b56-dirty
```

### Anything else we need to know?

Note that some CSI drivers (e.g. the cloud ones) do not allow detaching a volume while it's still mounted. Not all CSI driver have such possibility and they rely on Kubernetes not to call ControllerUnpublish before NodeUnpublish / NodeUnstage succeeds.

### Kubernetes version

<details>
Today's master
</details>

**Comment by jsafrane** [comment]
Right now, a volume is detached from a node when: (all pods that use the volume are deleted from the API server OR all their container are stopped) AND (the volume is unmounted OR 6 minutes passed).

Idea for a solution: Issue detach of a mounted volume only when all pods are force-deleted from the API server.

More formally: Detach when [(All pods that use the volume are deleted from the API server OR all their container are stopped) AND the volume is unmounted] OR [all pods that use the volume are deleted from the API server AND 6 minutes passed].

Is this change subtle enough that it  does not break existing behavior (e.g. tooling on top of Kubernetes)?

**Comment by jsafrane** [comment]
Another idea: Add a new flag to CSIDriver, say `DetachMountedVolumes`.
We would need to extend internal Detach() call to include a flag if the volume to detach is mounted or not (A/D controller knows that) and the CSI volume plugin would check CSIDriver and potentially reject detach of a mounted volume. This way, it would not be possible to ever force detach a mounted volume, even when a pod is force-deleted!

As a variant, we could add a cmdline option to the external-attacher, like `--force-detach=false`. When that cmdline option is specified, the external attacher would check Node, if the volume to detach is still mounted, and refuse such detach (with a reasonable error message). CSI driver vendors could opt-in into this behavior. This way, it would not be possible to ever force detach a mounted volume, even when a pod is force-deleted!

As a variant, we could add `ForceDetachTimeout` to CSIDriver, where each driver could put their own timeout before force-detaching a volume, with an option to use infinity.

**Comment by jsafrane** [comment]
Note to self: check https://github.com/container-storage-interface/spec/pull/477, it might help on the CSI side.

**Comment by jsafrane** [comment]
Solution 3 will not work well with ungraceful node shutdown - attach/detach controller does not watch pods and force-deleting pods is the main point of ungraceful node shutdown KEP.

/me will try if solution 1 would work when NodeStage times out (is Pod deleted from the API server before or after NodeStage is called?)

**Comment by jsafrane** [comment]
@jingxu97 was right, a pod is deleted (without force) from the API server after NodeUnpublish succeeds, it does not wait for NodeUnstage to finish. Therefore we cannot distinguish if a pod was force-deleted (and we should start 6 minute timer) or pod was deleted without any force and only NodeUnstage is taking more time than expected.
Solution 1 is then not possible.

**Comment by jingxu97** [comment]
Now we are down to solution 2 and 4.
For solution 2, if driver does not have a way to check whether volume is mounted or not, the behavior will not change and we still force detach after 6 mins. And it might happen in the middle of unstage ..

**Comment by jsafrane** [comment]
Summing up yesterday's call:

A/D controller should check if a node is *unhealthy* before force detaching volumes from it. It should never force detach  a volume from a healthy node, not even after 6 minutes.

Question what *healthy* means is open and we should talk to sig-node. `Node.Status.Condition Ready` is a working assumption.

**Comment by bswartz** [comment]
> A/D controller should check if a node is _unhealthy_ before force detaching volumes from it. It should never force detach a volume from a healthy node, not even after 6 minutes.
> 
> Question what _healthy_ means is open and we should talk to sig-node. `Node.Status.Condition Ready` is a working assumption.

I agree with both of these. I'd just emphasize that that particular definition of unhealthy definitely includes perfectly healthy nodes in a network partition. This change is _no worse_ than the status quo ante for those nodes, and a definite improvement on the healthy nodes, so I wholeheartedly support it.
