### ISSUE TITLE
can not add a new node

### ISSUE THREAD

**Issue by wwc13485375003** [kubernetes/kubernetes#106758]
### What happened?

when I add a new node by kk , the calico is not ready. My four node ip is 172.28.138.127,172.28.138.128,172.28.252.244，172.20.196.48,but the new 172.20.196.48 has some problem. 
run "calicoctl node status" on the 172.28.138.127
| PEER ADDRESS | PEER TYPE | STATE | SINCE | INFO |

+—————-+——————-+——-+————+————-+

| 172.28.138.128 | node-to-node mesh | up | 2021-11-09 | Established |

| 172.28.252.244 | node-to-node mesh | up | 2021-11-09 | Established |

| 172.20.196.48 | node-to-node mesh | start | 01:50:43 | Connect |

+—————-+——————-+——-+————+————-+
and on 172.20.196.48
+—————-+——————-+——-+———-+———+

| PEER ADDRESS | PEER TYPE | STATE | SINCE | INFO |

+—————-+——————-+——-+———-+———+

| 172.28.138.127 | node-to-node mesh | start | 02:40:48 | Passive |

| 172.28.138.128 | node-to-node mesh | start | 02:40:48 | Passive |

| 172.28.252.244 | node-to-node mesh | start | 02:40:48 | Passive |

+—————-+——————-+——-+———-+———+
please help me

### What did you expect to happen?

add new node successfuly

### How can we reproduce it (as minimally and precisely as possible)?

add new node of another account, use Cloud enterprise network of alibaba then they can ping each other

### Kubernetes version

3.11

### Cloud provider

alibaba

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
This looks more like a Calico issue, so you should report the problem on their github project.

Thanks
/close
