### ISSUE TITLE
kubelet /run interface not support spaces in commad

### ISSUE THREAD

**Issue by NoicFank** [kubernetes/kubernetes#106757]
### What happened?

why kubelet /run interface using space to split the cmd? 
```
params.cmd = strings.Split(request.QueryParameter("cmd"), " ")
```
which leads to
```
ls -> ok
ls -a -> ok
/bin/sh "ls" -> ok
/bin/sh "ls -a" -> failed
```

### What did you expect to happen?

I want to use kubelet /run interface to run a command in container, and get the run result. The command contains many spaces.

### How can we reproduce it (as minimally and precisely as possible)?

send to kubelet /run interface
```
curl -k -H "Authorization: xxx" -d 'cmd=/bin/sh -c "ls -l"' https:/xxx:10250/run/{ns}/{pod}/{container name}
```

### Kubernetes version

<details>
1.21
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
centos 

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
This is not supported. You should not be submitting workloads directly to the internal Kubelet APIs. The only supported ways to create pods are as static pods, via a folder on manifests on disk, or via the API server.

/close

**Comment by NoicFank** [comment]
- 加微信，约时间。- 使用腾讯视频面交作业，链接微信给你。
