### ISSUE TITLE
Cannot access service from within a pod -- Minikube

### ISSUE THREAD

**Issue by koushikmgithub** [kubernetes/kubernetes#106784]
### What happened?

I have a simple Kubernetes Service up and running in a single Pod. I went inside the docker container for that Pod by 
kubectl exec -it my-nginx-5b56ccd65f-twv25 /bin/sh . I try to curl <service> to access the Service, but it receives connection timeout error. I also test by curl <Pod IP> :80, which works without any issue. Also, I am able to access the service from different pods as well. Also, the same thing is working in kind cluster.

### What did you expect to happen?

curl my-nginx or curl <service name> also works without any issue inside the container.

### How can we reproduce it (as minimally and precisely as possible)?

Execute the command
1. kubectl apply -f sample-deployment.yaml
2. Make sure pod and service are up and running.
3.  Logon to container
   kubectl exec -it <pod name> /bin/sh
4.  curl -v my-nginx

<Please see below the sample-deployment.yaml file>

sample-deployment.yaml:
----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: my-nginx

-------------------------------------------

### Anything else we need to know?

I use nslookup my-nginx, and it returns the correct Service IP attached to my-nginx. I don't think this issue has anything to do with DSN service. May be the issue with minikube.

curl -v my-nginx prints out the following error.

# curl -v my-nginx
*   Trying 10.107.32.211:80...
* connect to 10.107.32.211 port 80 failed: Connection timed out
* Failed to connect to my-nginx port 80: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to my-nginx port 80: Connection timed out
#

### Kubernetes version
$ kubectl version

PS C:\Windows\system32> kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

N/A

### OS version

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture

PS C:\Windows\system32> wmic os get Caption,Version,BuildNumber,OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
19043        Microsoft Windows 10 Enterprise  64-bit          10.0.19043

### Install tools
PS C:\Windows\system32> minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b

**Comment by uablrek** [comment]
As [mentioned](https://github.com/kubernetes/kubernetes/issues/73481#issuecomment-477762607) this is a "hairpin" issue and is a bit different in different environments. I made a search on "minikube hairpin" and [this](https://stackoverflow.com/questions/54911270/kubernetes-service-can-not-send-request-to-itself) may be related. It seems to be resolved on Linux.

/sig network
/area windows

**Comment by koushikmgithub** [comment]
Thanks @uablrek . It's work for me as well. I have executed the below command and after that issue is resolved.

minikube ssh -- sudo ip link set docker0 promisc on
