### ISSUE TITLE
kubectl describe - undocumented feature: resources are matched by prefix

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#10674]
There is an undocumented feature in "kubectl describe": If we give two arguments, for instance

```
kubectl describe node e2e-test
```

and the name is not found, kubectl searches for resources whose name starts with the given prefix (here: nodes with names starting with e2e-test

This feature doesn't work if we use / to separate the resource type:

```
kubectl describe node/e2e-test
```

What needs to be sorted out:
1. document (or not) this feature
2. unify (or not) the behavior for space-separated and /-separated parameters
3. document what return code is returned if resource is not found - people may be confused if they get success if node name is not matched, but is matched to another node with the given prefix.

If we want to leave this undocumented function as it is, I suggest to include comments in the go sources explaining why we have it.

**Comment by marekbiskup** [comment]
cc @bgrant0607 @brendandburns 

priority low

**Comment by feihujiang** [comment]
@marekbiskup What's the conclusion about this issue?

**Comment by marekbiskup** [comment]
I'm sorry @feihujiang , I haven't been involved in Kubernetes lately.

@brendandburns, I suggest we remove this feature - we have auto-completion and I think it is more consistent than this. (Alternatively, we may match wildcards: pod_na* for pod_name_1234234).
What do you think?

It would be nice to check if it is documented. Otherwise we can't just remove it.

**Comment by feihujiang** [comment]
@marekbiskup Thanks for your quickly reply. If there is some work to do, I'd like to volunteer myself.

**Comment by bgrant0607** [comment]
@smarterclayton @deads2k Are you dependent upon the prefix-matching feature in any way? I was kind of surprised that this existed.

@feihujiang Thanks for volunteering to help. I'll try to reprioritize some kubectl issues and let you know which ones are most important.

cc @kubernetes/kubectl

**Comment by smarterclayton** [comment]
Brendan added that - not dependent on it.  Haven't used it myself (or noticed it yet).

**Comment by feihujiang** [comment]
@bgrant0607 OK, thanks! And I want to know, why  team members of kubernetes/kubectl are private ? who is the member of kubernetes/kubectl?

**Comment by bgrant0607** [comment]
@feihujiang I don't know how to make the members public outside the org.

**Comment by hurf** [comment]
@bgrant0607 - the members themselves can choose to show their membership outside the org or not. It will be helpful if members set it to public, for users may know who they should ask for code review.
