### ISSUE TITLE
Interaction between NodeUnstageVolume and NodePublishVolume

### ISSUE THREAD

**Issue by gman0** [kubernetes/kubernetes#106729]
### What happened?

Interaction between failing `NodeUnstageVolume` and `NodePublishVolume` results in unmountable volumes. 

We've observed a following series of events taking place:
1. The last consumer of a volume leaves the node, triggering `NodeUnstageVolume`.
2. For some reason this call fails, but still manages to unmount the volume from the node. Nevertheless, it returns an error.
3. Kubelet keeps retrying `NodeUnstageVolume`, returning an error each time.
4. In the meantime, a new Pod is scheduled on this node, mounting the same volume that's still being repeatedly attempted to be unstaged.
5. Kubelet stops issuing `NodeUnstageVolume` since there's now at least a single consumer of the volume on the node.
6. Kubelet invokes `NodePublishVolume` only (!), without staging the volume first.

Unless a CSI driver doesn't try to somehow restore missing volumes in `staging_target_path` by itself, these volumes are rendered unmountable on the node due to absent `NodeStageVolume` call. While it probably could do such restoration, this sounds more like kubelet not being up to CSI spec in this scenario.

### What did you expect to happen?

After issuing `NodeUnstageVolume` calls, kubelet should have called `NodeStageVoume` before calling `NodePublishVolume`.

### How can we reproduce it (as minimally and precisely as possible)?

* Have a CSI driver that supports `STAGE_UNSTAGE_VOLUME` Node service capability.
* Have `NodeUnstageVolume` return an error that triggers a retry (in our case it was `INTERNAL`).

### Kubernetes version

<details>
This is reproducible in with any k8s version.
</details>

### Cloud provider

<details>
None.
</details>

**Comment by humblec** [comment]
@gman0 what kind of PVC ( RWO, RWX ) is in use here?

**Comment by gman0** [comment]
@humblec This was RWX. I've tested RWO too (in a single-node cluster though). The VolumeAttachment object is kept around until `NodeUnstageVolume` succeeds. Scheduler would choose the node that already has the attachment anyway, so we're back in the same situation, where only `NodePublishVolume` is called -- without staging first.

**Comment by gman0** [comment]
Does this sound like a bug, @jsafrane @xing-yang @msau42 ?

**Comment by jsafrane** [comment]
> This is reproducible in with any k8s version.

Can you still reproduce it in 1.22? I think I fixed it there with https://github.com/kubernetes/kubernetes/pull/100183, 1.21 backport is in progress in https://github.com/kubernetes/kubernetes/pull/107014

**Comment by gman0** [comment]
@jsafrane I cannot reproduce with >=1.22.0. Thank you and sorry for the noise. Closing.
