### ISSUE TITLE
CoreDNS is not able to start on DualStack clusters

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#106709]
### What happened?

Clusters created with kubeadm using DualStack are not able to work, because CoreDNS pods never get ready

```
Nov 29 09:59:13.953: INFO: The status of Pod coredns-64897985d-67hvq is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
Nov 29 09:59:13.953: INFO: The status of Pod coredns-64897985d-gnlwj is Running (Ready = false), waiting for it to be either Running (with Ready = true) or Failed
```

Seeing one failed job logs https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-network-dual/1448567856974270464/artifacts/logs/kind-control-plane/pods/kube-system_coredns-78fcd69978-lqk7j_bb2015db-af37-45d4-be49-a8382d1156f6/coredns/0.log

It seems that the pod is "waiting for the kubernetes service"??

```
2021-10-14T08:51:18.140350321Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:51:28.140383487Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:51:38.140669528Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:51:48.140656083Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:51:58.141313103Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:52:08.140532548Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:52:18.140476088Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:52:28.140657923Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
2021-10-14T08:52:32.68092095Z stdout F [INFO] plugin/ready: Still waiting on: "kubernetes"
```

coredns version seems the same as in the working jobs
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-network-dual/1447660998126211072

> 2021-10-11T22:53:03.2950542Z stdout F CoreDNS-1.8.4
> 2021-10-11T22:53:03.295062997Z stdout F linux/amd64, go1.16.4, 053c4d5

### What did you expect to happen?

CoreDNS pod should be ready

### How can we reproduce it (as minimally and precisely as possible)?

Instal a Dual-stack cluster using master with kubeadm (or kind https://kind.sigs.k8s.io/docs/user/configuration/#ip-family)

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/6450081/143852924-e848b707-a707-4ea1-a8f9-e31c655e865a.png)

It started to fail on Oct12

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/cc @BenTheElder @neolit123 @chrisohaver 

I didn't notice it was failing for more than 1 month :face_with_head_bandage: 

I didn't have time to dig into it yet, but this PR landed just that day

https://github.com/kubernetes/kubernetes/commit/941c78f411a994d2a8f0f9c3ea280bd3746733b7

@neolit123 how is that the pods running has the version 1.8.4 but the PR seems to update kubeadm to 1.8.6?

**Comment by chrisohaver** [comment]
Looking into this today. The error from CoreDNS should only happen when the kubernetes plugin fails to sync with the Kubernetes API, either because it can’t connect, or it can’t sync the lists of services/endpointslices.  There were changes and fixes to the API connection code, so it could be a regression.

**Comment by chrisohaver** [comment]
> There were changes and fixes to the API connection code, so it could be a regression.

Actually no. The changes I was thinking of were already in 1.8.4.

**Comment by chrisohaver** [comment]
> Instal a Dual-stack cluster using master with kubeadm (or kind https://kind.sigs.k8s.io/docs/user/configuration/#ip-family)

I was unable to reproduce this issue in a kind dual stack cluster. After upgrading coredns to 1.8.6 (from 1.8.0 installed by kind), and adding list/watch permission for endpointslice, the pods were ready.

**Comment by aojea** [comment]
let me check if is a regression in kind :thinking:

**Comment by aojea** [comment]
working with 1.8.6 and yesterdays kubernetes
```
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.0.9+9a75e7b0fd1b56", GitCommit:"9a75e7b0fd1b567f774a3373be640e19b33e7ef1", GitTreeState:"clean", BuildDate:"2021-11-29T00:10:30Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```


```
kind create cluster --image aojea/kindnode:latest --config kind.yaml 
...

$ kubectl -n kube-system logs coredns-64897985d-qc8mc
.:53
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
$ kubectl get pods -A -o wide
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE   IP           NODE                 NOMINATED NODE   READINESS GATES
kube-system          coredns-64897985d-qc8mc                      1/1     Running   0          67s   10.244.0.4   kind-control-plane   <none>           <none>
kube-system          coredns-64897985d-tsj4c                      1/1     Running   0          67s   10.244.0.2   kind-control-plane   <none>           <none>
```

podIPs
```
  podIP: 10.244.0.4
  podIPs:
  - ip: 10.244.0.4
  - ip: fd00:10:244::4
```

**Comment by aojea** [comment]
This is weird, I hit a similar issue in openshift, endpoints doesn't match the IP family of the kubernetes.default service

```
2021-11-29T09:51:34.719572093Z stderr F I1129 09:51:34.719496       1 service.go:419] "Adding new service port" portName="default/kubernetes:https" servicePort="10.96.0.1:443/TCP"
```

```
2021-11-29T09:51:34.758830462Z stderr F I1129 09:51:34.758680       1 endpointslicecache.go:358] "Setting endpoints for service port name" portName="default/kubernetes:https" endpoints=[[fc00:f853:ccd:e793::3]:6443]
```

apiserver service is single stack, at least until this KEP https://github.com/kubernetes/enhancements/pull/2956 fixes it

What I don't understand is why the order of the IPs in kind is different
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-network-dual/1465252814082019328/build-log.txt

```
  podSubnet: 10.244.0.0/16,fd00:10:244::/56
  serviceSubnet: 10.96.0.0/16,fd00:10:96::/112
scheduler:
  extraArgs:
    v: "4"
---
apiVersion: kubeadm.k8s.io/v1beta2
bootstrapTokens:
- token: abcdef.0123456789abcdef
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: fc00:f853:ccd:e793::4
  bindPort: 6443
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
  kubeletExtraArgs:
    fail-swap-on: "false"
    node-ip: fc00:f853:ccd:e793::4,172.18.0.4
```

let me try to fix both things
/assign

**Comment by aojea** [comment]
my fault, sorry for the noise :sweat_smile:
