### ISSUE TITLE
[Flaking test][sig-release-master-informing] gce-scale-correctness.Overall

### ISSUE THREAD

**Issue by calvh** [kubernetes/kubernetes#106770]
### Which jobs are flaking?

gce-master-scale-correctness

### Which tests are flaking?

- Kubernetes e2e suite.[sig-network] Networking Granular Checks: Services should update nodePort: udp [Slow]
- ci-kubernetes-e2e-gce-scale-correctness.Overall
- kubetest.Test
- Kubernetes e2e suite.[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (filesystem volmode)] volumeMode should not mount / map unused volumes in a pod [LinuxOnly]
- Kubernetes e2e suite.[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (late-binding)] ephemeral should support two pods which have the same volume definition
- Kubernetes e2e suite.[sig-network] Services should be able to update service type to NodePort listening on same port number but different protocols

### Since when has it been flaking?

12/1/2021 17:36:39 ET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Relevant SIG(s)

/sig storage
/sig network

**Comment by aojea** [comment]
heh, what are the chances, two different test services took the same port
```
I1201 12:35:09.491960       1 proxier.go:1604] "Opened local port" port={Description:nodePort for nettest-6509/node-port-service:udp IP: IPFamily:4 Port:30704 Protocol:UDP}
E1201 12:35:09.492047       1 proxier.go:1600] "can't open port, skipping it" err="listen udp4 :30704: bind: address already in use" port={Description:nodePort for nettest-6509/node-port-service:udp IP: IPFamily:4 Port:30704 Protocol:UDP}
```

```
I1201 12:38:59.975971       1 proxier.go:827] "Syncing iptables rules"
I1201 12:39:00.069924       1 proxier.go:1604] "Opened local port" port={Description:nodePort for nettest-3164/node-port-service:udp IP: IPFamily:4 Port:30704 Protocol:UDP}
E1201 12:39:00.070030       1 proxier.go:1600] "can't open port, skipping it" err="listen udp4 :30704: bind: address already in use" port={Description:nodePort for nettest-3164/node-port-service:udp IP: IPFamily:4 Port:30704 Protocol:UDP}
I1201 12:39:00.071854       1 prox
```

The test was expecting to now receive any answer
```
Dec  1 12:36:52.117: INFO: Found all 10 expected endpoints: [netserver-0 netserver-1 netserver-2 netserver-3 netserver-4 netserver-5 netserver-6 netserver-7 netserver-8 netserver-9]
ï¿½[1mSTEPï¿½[0m: Deleting the node port access point
ï¿½[1mSTEPï¿½[0m: dialing(udp) 35.237.145.196 (node) --> 35.237.145.196:30704 (nodeIP) and getting ZERO host endpoints
Dec  1 12:37:07.177: INFO: Going to poll 35.237.145.196 on port 30704 at least 130 times, with a maximum of 130 tries before failing
```

but the second service replies and makes the test fail
