### ISSUE TITLE
scheuler not always clear a preemptor's nominatedNodeName as expected

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#106780]
A pod's `.status.nominatedNodeName` is set by the scheduler to mark this pod as a preemptor (let's call it P1), with a cost of preempting low-priority pods (let's call it P0). The preemptor doesn't get scheduled instantly; instead, it has to wait for the victims to be fully terminated and then deleted physically. During the waiting period, some cases may happen:

#### Case 1

A high-priority pod P2 comes in, and it needs to preempt some victims (P0) to make room for itself. In this case, P1's `.status.nominatedNodeName` is also cleared as it may not fit anymore.

https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/pkg/scheduler/framework/preemption/preemption.go#L340-L341

We're good on this case.

#### Case 2

A high-priority pod P2 comes in. It doesn't need to preempt any victim to be schedulable. For example, let's say a node has 4 CPUs, P0/P1/P2 requests 2/3/1.5 CPUs respectively. In this case, P2's placement actually makes P1 no longer schedulable. But note here, P1's `.status.nominatedNodeName` **stays forever** unless it's deleted physically.

```
# Suppose a node has 4 cpus
# p0 requests 2 cpus
NAME   READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Running   0          6s    10.244.2.10   kind-worker   <none>           <none>

# p1 requests 3 cpus
NAME   READY   STATUS        RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Terminating   0          15s   10.244.2.10   kind-worker   <none>           <none>
p1     0/1     Pending       0          4s    <none>        <none>        kind-worker      <none>

# p2 requests 1.5 cpus
NAME   READY   STATUS        RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p0     1/1     Terminating   0          22s   10.244.2.10   kind-worker   <none>           <none>
p1     0/1     Pending       0          11s   <none>        <none>        kind-worker      <none>
p2     1/1     Running       0          4s    10.244.2.11   kind-worker   <none>           <none>
......<after p0's grace termination period ends>......
NAME   READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
p1     0/1     Pending   0          93s   <none>        <none>        kind-worker      <none>
p2     1/1     Running   0          86s   10.244.2.11   kind-worker   <none>           <none>

# re-apply p0
NAME   READY   STATUS    RESTARTS   AGE     IP            NODE          NOMINATED NODE   READINESS GATES
p0     0/1     Pending   0          2s      <none>        <none>        <none>           <none>
p1     0/1     Pending   0          2m50s   <none>        <none>        kind-worker      <none>
p2     1/1     Running   0          2m43s   10.244.2.11   kind-worker   <none>           <none>
# p0 cannot be scheduled unless p1 gets physically deleted, which is not desired
```

Because P1's `.status.nominatedNodeName` is not cleared, it reserved 2 CPUs in the internal scheduler cache, which will block further low-priority Pods' scheduling.

There are some other variants of this case:

- a regular (not necessarily high-priority) pod's placement on another node makes P1's inter-pod constraints (e.g., podantiaffinity, podtopologyspread) no longer satisfied
- without intervention of other pods, P1 failed the scheduling due to unexpected failures like "Node not found" (reported in #85677)

#### Case 3

P1 does get through the Filter phase and gets assumed, but it's controller by a Permit plugin, and afterwards timed out (or rejected) in the WaitOnPermit() phase (in binding cycle). This case doesn't happen in the vanilla default scheduler, but is reported in coscheduling pluign (https://github.com/kubernetes-sigs/scheduler-plugins/issues/293)

#### Expection

In both case 2 and 3, the Pod's `.status.nominatedNodeName` should be cleared properly.

/kind bug
/sig scheduling

**Comment by Huang-Wei** [comment]
cc @mateuszlitwin @ahg-g @alculquicondor @damemi 

I will work on a fix on this.

/assign

**Comment by alculquicondor** [comment]
What is the proposed solution? Note that case 2 could be that P2 is scheduled on a different node and P1 is blocked due to anti-affinity rules. So, in general, whenever a pod gets scheduled, we would need to verify if Pods with nominated node name needs to be cleared.

Should we start thinking of some expiration time instead? Even if the time we choose is not enough for pods to terminate, the pod might be nominated on the same node again in its next scheduling cycle.

**Comment by Huang-Wei** [comment]
> What is the proposed solution?

The idea would like similar to [one](https://github.com/kubernetes/kubernetes/pull/91750) I proposed before, but that unfortunately caused a [regression](https://github.com/kubernetes/kubernetes/issues/91972), so I will more pay more attention to different corner cases and add sufficient tests this time.

> Note that case 2 could be that P2 is scheduled on a different node and P1 is blocked due to anti-affinity rules.

True, this is actually the limitation of the current preemption algorithm - which searches preemption strategies based on two facts: (1) preempt pods from a single node and (2) evaluate if the preemtor can run on the very node that victims used to live.

> So, in general, whenever a pod gets scheduled, we would need to verify if Pods with nominated node name needs to be cleared. Doing these checks sound costly.

Not quite, high-priority pods just disregard low-nominated pods. The potential enhancement should be in preemption logic. Say, when P2 gets scheduled to a different node, and now it's the scheduling turn of P1. If we can come up with a better preemption algorithm to detect that P2's presence (on another node) blocks its scheduling, then P1 should either clear its own nomiantedNodeName (if P1's priority <= P2), or preempt P2 otherwise.

> Should we start thinking of some expiration time instead? Even if the time we choose is not enough for pods to terminate, the pod might be nominated on the same node again in its next scheduling cycle.

Not quite a fan of a duration-based solution...

**Comment by alculquicondor** [comment]
> If we can come up with a better preemption algorithm to detect that P2's presence (on another node) blocks its scheduling, then P1 should either clear its own nomiantedNodeName (if P1's priority <= P2), or preempt P2 otherwise.

Right, that sounds like the correct solution.
