### ISSUE TITLE
kubelet doesn't  clean up the termination-log file on the host

### ISSUE THREAD

**Issue by luozhiwenn** [kubernetes/kubernetes#106735]
### What happened?

Each time a container needs to be created, the kubelet will create a termination-log file on the host and mounts the file to the path specified by the terminationMessagePath field in the container for outputting termination messages.
The paths of these files on the host are as follows:
`/var/lib/kubelet/pods/{POD_ID}/containers/{CONTAINER_NAME}/{RANDOM_NUM}`

It seems that kubelet does not clean up these files unless the pod is deleted. If some containers are restarted for many times, a large number of files may be generated and the host inodes are used up.

### What did you expect to happen?

kubelet should proactively clear these files to avoid inode exhaustion.

### How can we reproduce it (as minimally and precisely as possible)?

Re-create a running container and you can see the newly created file in the path: `/var/lib/kubelet/pods/{POD_ID}/containers/{CONTAINER_NAME}/{RANDOM_NUM}`

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.1
```

</details>

### Cloud provider

<details>
Not relevant
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vsxen** [comment]
--maximum-dead-containers int32                            Maximum number of old instances of containers to retain globally.  Each container takes up some disk space. To disable, set to a negative number. (default -1) (DEPRECATED: Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.)
      --maximum-dead-containers-per-container int32              Maximum number of old instances to retain per container.  Each container takes up some disk space. (default 1) (DEPRECATED: Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.)

**Comment by luozhiwenn** [comment]
> ```
>   --maximum-dead-containers int32                            Maximum number of old instances of containers to retain globally.  Each container takes up some disk space. To disable, set to a negative number. (default -1) (DEPRECATED: Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.)
>   --maximum-dead-containers-per-container int32              Maximum number of old instances to retain per container.  Each container takes up some disk space. (default 1) (DEPRECATED: Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.)
> ```

In my k8s cluster, these options are left at their default values.
I notice that the termination-log file on the host still exists, even though the exited containers has been clean up by kubelet.

**Comment by cmssczy** [comment]
This log file was created in https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container.go#L402-L404
I think we should get the `terminationMessagePath` by query container spec and then delete this file in `removeContainerLog` function or somewhere else.
I can work on it if this solution is correct. @rphillips @ehashman

**Comment by rphillips** [comment]
The kubelet creates a log file with the ${restartCount}.log; not a random number. When the kubelet rotates the log, then old log files are cleaned up. After the pod is removed from the disk (via a GC or API delete), then all the pod logs are removed.

We should be able to close this issue.

/close

**Comment by s-kawamura-w664** [comment]
@rphillips @luozhiwenn 

>The kubelet creates a log file with the ${restartCount}.log; not a random number. When the kubelet rotates the log, then old log files are cleaned up. After the pod is removed from the disk (via a GC or API delete), then all the pod logs are removed.

I already reported about this in #114117 and I report it again in this issue.

I can see the two kind log.
* Termination-log: /var/lib/kubelet/pods/{POD_ID}/containers/{CONTAINER_NAME}/{RANDOM_NUM}
* Container-log: /var/log/pods/{NAMESPACE}_{POD_NAME}_{POD_ID}/{CONTAINER_NAME}/{restartCount}.log

The container-log is not a random number, but the termination-log is a random number.
I think this issue is about termination-log.

When a container-log is roteted, an old container-log is removed in 

https://github.com/kubernetes/kubernetes/blob/4c4d4ad0a4aea4d015561ae3e7d48e8aaf609277/pkg/kubelet/kuberuntime/kuberuntime_container.go#L971-L973

However, even if a termination-log is rotated, an old termination-log is not removed.

If my report is correct, I think this Issue should be continued. 
What do you think?

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale
/assign @luozhiwenn

since there is a PR for this
