### ISSUE TITLE
Kubelet: Container GC why Keep latest one if the pod still exists ?

### ISSUE THREAD

**Issue by VictoryAnn** [kubernetes/kubernetes#106714]
In my environment, one node have 2000+ completed pods, it means there are many pause sandbox in this node, cause inspect container timeout then kubelet is abnormal.

Question:

when container gc,  why Keep latest one if the pod still exists ? 

If I change container gc GarbageCollect to DeleteAllUnusedContainers , What is the impact?

**Comment by yxxhero** [comment]
@VictoryAnn Please use the correct issue template to ask questions. Thanks very much.

**Comment by 249043822** [comment]
> In my environment, one node have 2000+ completed pods, it means there are many pause sandbox in this node, cause inspect container timeout then kubelet is abnormal.
> 
> Question:
> 
> when container gc, why Keep latest one if the pod still exists ?
> 
keeping the lastest failed container is for users to see the failure reason by container logs and status details

> If I change container gc GarbageCollect to DeleteAllUnusedContainers , What is the impact?
DeleteAllUnusedContainers  is used by eviction while node has resource disk pressure, but it still uses the same gcPolicy with GarbageCollect, still keep the latest one exited container, unless your pod is terminal.
