### ISSUE TITLE
logcheck: not applied to packages under staging

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#106746]
### What happened?

I recently added a benchmark to staging/src/k8s.io/component-base/logs/benchmark which has code that triggers an error from current logcheck (`ErrorS` is passed a slice with `...` - valid, but not handled by the tool). See https://github.com/kubernetes/kubernetes/pull/106594

I did not get an error for that from `pull-kubernetes-verify`.

I did get it only after moving the benchmark to `test/integration/logs/benchmark`.

/wg structured-logging
/sig instrumentation

### What did you expect to happen?

`pull-kubernetes-verify` should check staging repos.

### How can we reproduce it (as minimally and precisely as possible)?

Add broken code:
```
diff --git a/staging/src/k8s.io/component-base/logs/logs.go b/staging/src/k8s.io/component-base/logs/logs.go
index 0f494deedd0..9a9cc890e6f 100644
--- a/staging/src/k8s.io/component-base/logs/logs.go
+++ b/staging/src/k8s.io/component-base/logs/logs.go
@@ -203,3 +203,7 @@ func GlogSetter(val string) (string, error) {
        }
        return fmt.Sprintf("successfully set klog.logging.verbosity to %s", val), nil
 }
+
+func thisIsBroken() {
+       klog.InfoS("hello world", "missingValue")
+}
```

Run `hack/verify-structured-logging.sh`. It should complain about that code.

### Anything else we need to know?

This invocation covers vendor:
https://github.com/kubernetes/kubernetes/blob/c1153d3353bd4f4b68d85245d53d2745586be474/hack/verify-structured-logging.sh#L86-L88

In my case, one of the parameters is `/nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/...`.

### Kubernetes version

master

### Cloud provider

NA

### OS version

Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
I'd expect this to work for `staging/` but not `vendor/`, can you clarify which is the issue here?

/triage needs-information

**Comment by pohly** [comment]
There is a comment in the script that `staging` is meant to be tested through the symlinks under `vendor`:

https://github.com/kubernetes/kubernetes/blob/2ac6a4121f5b2a94acc88d62c07d8ed1cd34ed63/hack/verify-structured-logging.sh#L74-L77

I don't care how `staging/src/k8s.io` gets tested as long as it is tested somehow.

**Comment by pohly** [comment]
/assign

I have a tentative solution that is based on integrating logcheck into the golangci-lint invocation.

**Comment by pohly** [comment]
See https://kubernetes.slack.com/archives/C09QZ4DQB/p1643049767036400 for a discussion of that approach.

**Comment by pohly** [comment]
I have it working:
- https://github.com/pohly/klog/commits/golangci-lint
- https://github.com/pohly/kubernetes/commits/logcheck

My current thinking is that this issue is not urgent enough to justify a new klog release. I prefer to wait for a decision about the future location of logcheck and then put the updated code there.

**Comment by umangachapagain** [comment]
> I'd expect this to work for `staging/` but not `vendor/`, can you clarify which is the issue here?
> 
Related discussion: https://github.com/kubernetes/kubernetes/pull/103293

We want this to work on both `staging/` and `vendor/`.
`vendor/k8s.io/` links to `staging` so I was expecting it to be tested.
