### ISSUE TITLE
Service endpoints not reachable within pods

### ISSUE THREAD

**Issue by Sam-Sundar-Apty** [kubernetes/kubernetes#106733]
### What happened?

Hi K8s Team,

We have an offline environment where Microk8s is deployed with Calico node and CoreDNS as DNS.

We could see DNS is not resolving endpoints and are getting i/o timeout. We have followed [this article](https://github.com/ubuntu/microk8s/files/7587411/redhat.txt) to remove NFTABLE and use iptable instead, and also added below env in caliconode daemonset
```yaml
- name: FELIX_IPTABLESBACKEND
  value: "NFT"
  ```
When i check iptables, below is the output with no rule even though we run `iptables -P FORWARD ACCEPT && iptables -P INPUT ACCEPT && iptables -P OUTPUT ACCEPT`

![image](https://user-images.githubusercontent.com/83000807/143888899-8a331724-1e57-4e49-be1c-e6a8edecf8d2.png)
![image](https://user-images.githubusercontent.com/83000807/143888963-3fef30f6-5044-4261-b069-4511c2d14521.png)

We get this error in coredns logs
![image](https://user-images.githubusercontent.com/83000807/143889680-9d808ddf-aae5-4092-9a20-f57082d44cfc.png)

Also when we nslookup a service from another pod, we get this below error
![image](https://user-images.githubusercontent.com/83000807/143890919-e82a5b9d-7c7a-423c-b815-838f2d7309a2.png)

Also firewalld is not running and we followed [this](https://github.com/coredns/coredns/issues/4666#issuecomment-856153464) too and removed all the hardening restrictions.
Can you please let us know if we are missing something and how to solve this issue.

**Environment**: 

- the version of CoreDNS: coredns/coredns:1.8.0, quay.io/calico/node:v3.13.2
- Corefile: `forward . /etc/resolv.conf`
- logs, if applicable: 
[coredns_NFT.log](https://github.com/coredns/coredns/files/7618875/coredns_NFT.log)
[calico_NFT.log](https://github.com/coredns/coredns/files/7618880/calico_NFT.log)
- OS (e.g: `cat /etc/os-release`) - RHEL 8.4

- Others:

### What did you expect to happen?

Services were reachable if we have the same cluster setup in AWS without any issues.

### How can we reproduce it (as minimally and precisely as possible)?

Install Microk8s in RHEL 8.4 with coredns as CNI and Calico as Node.

### Kubernetes version

<details>

```console
$ kubectl version
K8s v1.19
```

</details>

### Cloud provider

<details>
Hosted on Datacenter on Microk8s
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# rhel 8.4
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug
/kind support

> We have an offline environment where Microk8s is deployed with Calico node and CoreDNS as DNS.

This looks at first sight more a deployment issue than a bug, it also mentions lot of different components that are not tracked by the kubernetes/kubernetes project, I suggest you to check first on one of those projects and reopen the issue if you are sure this is a bug in the Kubernetes code.

Thanks

/close
