### ISSUE TITLE
Evaluate moving Pod resources calculation to k8s.io/component-helper

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#106769]
### What would you like to be added?

Refactor [`computePodResourceRequest`](https://github.com/kubernetes/kubernetes/blob/108c284a330a82ce1a1f80238e4f54bf5e8b045a/pkg/scheduler/framework/plugins/noderesources/fit.go#L162:6) and [`calculateResource`](https://github.com/kubernetes/kubernetes/blob/108c284a330a82ce1a1f80238e4f54bf5e8b045a/pkg/scheduler/framework/types.go#L715) so that the shared bits can be put in k8s.io/component-helper.

### Why is this needed?

These 2 implementations have the risk of becoming out of sync. Two components depend on it: kube-scheduler and kubelet, so it qualifies for being in the component-helper repo.

I think the major complication is what to do with one of the dependencies of these calculations: [`IsScalarResourceName`](https://github.com/kubernetes/kubernetes/blob/108c284a330a82ce1a1f80238e4f54bf5e8b045a/pkg/scheduler/util/utils.go#L145), which depend on `k8s.io/kubernetes/pkg/apis/core/v1/helper`. We need to evaluate if such check is actually necessary (that is, if removing it would change behavior). I have the suspicion that it wouldn't, assuming an apiserver already validated the Pod on admission.

**Comment by alculquicondor** [comment]
@liggitt for thoughts on whether this is a bad idea.

**Comment by alculquicondor** [comment]
/help

cc @ingvagabund

**Comment by liggitt** [comment]
what are the consequences if the implementations get out of sync?

**Comment by alculquicondor** [comment]
One of the functions governs the cached pods, and the other a pod being scheduled. So the risk is miscalculation of used resources, which could end up in overprovisioning or underprovisioning.

**Comment by yuzhiquan** [comment]
@alculquicondor how to do with this struct https://github.com/kubernetes/kubernetes/blob/f6864316ef640274c3d93f43ade127c569cd58f4/pkg/scheduler/framework/types.go#L410 and method, this struct has been refered in many place, shoud move this in to compoent-helper?

**Comment by alculquicondor** [comment]
Likely, yes

**Comment by kerthcet** [comment]
addressed by https://github.com/kubernetes/kubernetes/pull/115367
