### ISSUE TITLE
nodeSelector doesn't work when select the specific node

### ISSUE THREAD

**Issue by Gezx** [kubernetes/kubernetes#106700]
the yaml

apiVersion: v1
kind: Pod
metadata:
  name: hellok8s
  namespace: default
  labels:
    app: myapp
    version: v1
spec:
  containers:
  - name: mynginx
    image: nginx
  nodeSelector:
    type: master

when execute "kubectl apply -f pod.yaml"
the output

The Pod "hellok8s" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
  	... // 6 identical fields
  	ActiveDeadlineSeconds:        nil,
  	DNSPolicy:                    "ClusterFirst",
- 	NodeSelector:                 map[string]string{"type": "master"},
+ 	NodeSelector:                 nil,
  	ServiceAccountName:           "default",
  	AutomountServiceAccountToken: nil,
  	... // 19 identical fields
  }

**Comment by yxxhero** [comment]
@Gezx Please provide more info about your k8s. example: version...
please see the tips: 
```bash
pod updates may not change fields other than spec.containers[*].image, spec.initContainers[*].image, spec.activeDeadlineSeconds or spec.tolerations (only additions to existing tolerations
```

**Comment by neolit123** [comment]
please re-open once you fill the issue template properly:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml

/close
/triage needs-information
/sig node
