### ISSUE TITLE
client-go fake: watch does not respect label selector

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#106754]
### What happened?

Created a watch with LabelSelector set in fake client. It is ignored.

### What did you expect to happen?

LabelSelector is respected

### How can we reproduce it (as minimally and precisely as possible)?

Call .Watch() on any fake. Sorry I don't have a trivial runnable example right now but can get one latter if needed

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/108c284a330a82ce1a1f80238e4f54bf5e8b045a/staging/src/k8s.io/client-go/testing/fake.go#L158

Seems like Watch ignores everything; List respects LabelSelector but not anything else

### Kubernetes version

1.23

### Cloud provider

N/a

**Comment by fedebongio** [comment]
Hi @howardjohn, were you thinking in maybe contributing a PR to this? 
/help
/triage accepted

**Comment by kidlj** [comment]
I'd like to check it out.

**Comment by uhari03** [comment]
I'd like to take this on
/assign

@howardjohn Can you please provide that example when you get the time?

**Comment by MadhavJivrajani** [comment]
@uhari03, considering it's been more than a month, cool if I take a shot at this now, I think I should be able to send in a PR sometime next week. Just wanted to make sure in case you were continuing to work on it :)

**Comment by uhari03** [comment]
no go ahead and take it

**Comment by kidlj** [comment]
It seems difficult to implement this without breaking `ObjectTracker` interface.

```
// ObjectTracker keeps track of objects. It is intended to be used to
// fake calls to a server by returning objects based on their kind,
// namespace and name.
type ObjectTracker interface {
	// Add adds an object to the tracker. If object being added
	// is a list, its items are added separately.
	Add(obj runtime.Object) error

	// Get retrieves the object by its kind, namespace and name.
	Get(gvr schema.GroupVersionResource, ns, name string) (runtime.Object, error)

	// Create adds an object to the tracker in the specified namespace.
	Create(gvr schema.GroupVersionResource, obj runtime.Object, ns string) error

	// Update updates an existing object in the tracker in the specified namespace.
	Update(gvr schema.GroupVersionResource, obj runtime.Object, ns string) error

	// List retrieves all objects of a given kind in the given
	// namespace. Only non-List kinds are accepted.
	List(gvr schema.GroupVersionResource, gvk schema.GroupVersionKind, ns string) (runtime.Object, error)

	// Delete deletes an existing object from the tracker. If object
	// didn't exist in the tracker prior to deletion, Delete returns
	// no error.
	Delete(gvr schema.GroupVersionResource, ns, name string) error

	// Watch watches objects from the tracker. Watch returns a channel
	// which will push added / modified / deleted object.
	Watch(gvr schema.GroupVersionResource, ns string) (watch.Interface, error)
}
```

`ObjectTracker.Watch` method doesn't know anything about label/field restrictions, so the watcher created by it doesn't have the information to filter objects/events.
