### ISSUE TITLE
"kube-proxy TLS support"

### ISSUE THREAD

**Issue by AH2000141** [kubernetes/kubernetes#106870]
### What happened?

I want to set tls for kube-proxy and nodeLocalDns,but not found anything about tls properties

### What did you expect to happen?

how to support

### How can we reproduce it (as minimally and precisely as possible)?

no

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

$ uname -a
Linux bpzai01wdh 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Wed Dec 16 03:30:52 EST 2020 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
For DNS, coredns supports [tls](https://coredns.io/plugins/tls/).

For node-local-dns, it still does not supports tls. 
https://github.com/kubernetes/dns/blob/master/cmd/node-cache/main.go#L33-L51

/sig network

**Comment by aojea** [comment]
> I want to set tls for kube-proxy

@AH2000141 can you explain better what do you mean by this?

**Comment by AH2000141** [comment]
@aojea 
Due to security requirements, all services must disable HTTP port, but kube-proxy only supports HTTP (9090,10256,10249). I want to set HTTPS support, but cannot find it. How do I do this

**Comment by aojea** [comment]
> @aojea
> Due to security requirements, all services must disable HTTP port, but kube-proxy only supports HTTP (9090,10256,10249). I want to set HTTPS support, but cannot find it. How do I do this

Let's keep this focus on kube-proxy only, for node-local-dns we can open a new issue, maybe in [kubernetes/dns 
](https://github.com/kubernetes/dns) cc: @prameshj 

/retitle "kube-proxy TLS support"
/triage accepted
/help wanted

I think we are talking about these ports in this case

https://github.com/kubernetes/kubernetes/blob/f98f27bc2f318add77118906f7595abab7ab5200/cmd/kube-proxy/app/server.go#L169-L170

**Comment by cyclinder** [comment]
> I think we are talking about these ports in this case
> 
> https://github.com/kubernetes/kubernetes/blob/f98f27bc2f318add77118906f7595abab7ab5200/cmd/kube-proxy/app/server.go#L169-L170

maybe we should support tls for `Metrics` and `Healteh` ?

**Comment by aojea** [comment]
I know controller-manager, apiserver, scheduler are removing the "insecure" ports, @neolit123 is there some consensus on how to address this on all the components?

**Comment by neolit123** [comment]
IIRC the disabling of the insecure ports of kcm, server and scheduler were driven by sig auth. I am not aware of any writen guidelines. These components already had secure ports and the insecure ones were deprecaded and removed in graceful manner (multiple releases).

**Comment by AH2000141** [comment]
@pacoxu 
For node-local-dns,how do I disable the Metrics port?

**Comment by N226335735** [comment]
Let you know when I work tomorrow morning I’ll be home tomorrow morning and then 
![Uploading 0AF7FE86-3125-44D9-8386-D62C39882511.png…]()

**Comment by daro1337** [comment]
I also have a problem with metrics over TLS, I did not find any option that would enable it by default like `--secure-port` in other components

**Comment by Sebastian-RG** [comment]
I have the same issue. Is there a way to expose metrics over TLS? I've set the MetricsBindAddress to 0.0.0.0:10249 but this only exposes it over HTTP.

**Comment by wangfakang** [comment]
@AH2000141  @daro1337 @Sebastian-RG Here is a proposal https://github.com/kubernetes/kubernetes/issues/119358 about k-proxy supports zero trust network, such as TLS/mTLS etc.   Looking forward to your ideas/comments on this topic!
