### ISSUE TITLE
When toleranceSeconds is set to 0, will the pod be evicted immediately or never?

### ISSUE THREAD

**Issue by liruishan** [kubernetes/kubernetes#106876]
### What happened?

When toleranceSeconds is set to 0, will the pod be evicted immediately or never?

      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 0

### What did you expect to happen?

null

### How can we reproduce it (as minimally and precisely as possible)?

null

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.18

### Cloud provider

<details>

</details>
null

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/0fe049cb93683e488b9829316ac889bc4c2e42fc/staging/src/k8s.io/api/core/v1/types.go#L3032-L3037

**Comment by ahg-g** [comment]
0 is valid value and it the eviction will happen asap.

**Comment by NaincyKumariKnoldus** [comment]
Bydefault tolerationseconds is 30s , but if you give 0 value, then it will evict the pod as soon as possible.
