### ISSUE TITLE
Support `IN` operator for field selectors.

### ISSUE THREAD

**Issue by ahmed-mez** [kubernetes/kubernetes#106836]
### What would you like to be added?

Currently, `IN` operator is only supported for label selectors. Field selectors should also support `IN` operator as this is the only way to implement the `OR` operator on values.

### Why is this needed?

- Feature parity and consistency between label selectors and field selectors.
- Allow implementing `OR` rules based on field selectors

**Comment by fedebongio** [comment]
/cc @liggitt @deads2k @lavalamp 
We were wondering during triage if there was a reason why is not supported already?
Thanks!

**Comment by liggitt** [comment]
mostly due to performance of field selectors and that field selector values are way less constrained than label values, so escaping becomes way thornier

**Comment by fedebongio** [comment]
@ahmed-mez hopefully Jordan's answer is good enough to your question. We also discussed this in past SIG API Machinery meetings (I can try to find the link but the recordings are public if you are in the group list: https://docs.google.com/document/d/1x9RNaaysyO0gXHIr1y50QFbiL1x8OWnk2v3XnrdkT5Y/edit#heading=h.yse34ow2hhlf).

What would you like to do with this one? Keep it open and bring it to discussion in the SIG meeting? or close for now?
Thanks
Fede

**Comment by ahmed-mez** [comment]
Thanks @fedebongio ! It would be very nice to have it but definitely not a blocker at this point. I'll close the issue.
