### ISSUE TITLE
Allow admins to restrict the types/size of persistent volumes by namespace

### ISSUE THREAD

**Issue by markturansky** [kubernetes/kubernetes#10689]
Quota in put in place to limit the number of PVClaim per namespace.

Add the ability to restrict by size as well.  This allows admins to limit the big, special fancy PVs to specific namespaces.

**Comment by smarterclayton** [comment]
We should also do total aggregate GB requested, and ensure we have a mechanism for admins to arbitrarily limit the claims that can be requested based on a label selector for a namespace, or similar (the use case would be to ensure claims to volume matching can be controlled by an admin in bulk).  I don't know that size is necessarily the key feature - it seems likely that labels (on namespaces?) are more likely

**Comment by markturansky** [comment]
That makes sense.  The admin can devise a labelling scheme based on size (or anything) and enforce it that way.

**Comment by smarterclayton** [comment]
I'm not sure exactly what an implementation would be like - the openshift
project node selector is a good example, and in general how the scheduler
handles node selectors is also analogous (both are steps enforceable either
when creating the claim in an admission controller, or in the binder by
reading a config file).

On Jul 2, 2015, at 6:34 PM, Mark Turansky <notifications@github.com> wrote:

That makes sense. The admin can devise a labelling scheme based on size (or
anything) and enforce it that way.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/10689#issuecomment-118185456>
.

**Comment by markturansky** [comment]
Quota for volume sizes has been added. Closing this issue.
