### ISSUE TITLE
NodeRestriction does not work as expected

### ISSUE THREAD

**Issue by arrowfeng** [kubernetes/kubernetes#106874]
### What happened?

I followed this document to configure apiserver [NodeRestriction](https://kubernetes.io/docs/reference/access-authn-authz/node/)，but kubelet does not work. i know that binding clusterrole system:node, then kubelet work, but i think don't binding the clusterrole because NodeRestriction is configured.
![image](https://user-images.githubusercontent.com/20623365/145169521-ffa33fe1-61fc-4e90-b2fa-3ca08f444c65.png)

### What did you expect to happen?

kubelet work well

### How can we reproduce it (as minimally and precisely as possible)?

x

### Kubernetes version

<details>

1.20, 1.22

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by arrowfeng** [comment]
After the certificate is rolled, it is found that the node cannot list secrets and configmaps

**Comment by pacoxu** [comment]
To enable the Node authorizer, start the apiserver with --authorization-mode=Node.

Would you check your apiserver start-up params?

**Comment by arrowfeng** [comment]
Thank you for your reply，the param is --authorization-mode=Node,RBAC

**Comment by liggitt** [comment]
The forbidden errors are expected, nodes should not be listing/watching secrets and configmaps globally.

**Comment by liggitt** [comment]
Are you seeing these errors in the kubelet log, or in the log of another component using the kubelet's credentials? Do you have your kubelet invocation handy?

**Comment by arrowfeng** [comment]
> The forbidden errors are expected, nodes should not be listing/watching secrets and configmaps globally.
Thank you for your reply. Recently I was writing other kubelet-related components. I used the kubelet certificate and the informer used in the component caused this problem. I read the source code of kubelet and found that secret/configmap 
 manager instead of using informer, it uses reflector. I want to know why?

**Comment by liggitt** [comment]
> I read the source code of kubelet and found that secret/configmap
> manager instead of using informer, it uses reflector. I want to know why?

since kubelets don't need to access *all* secrets/configmaps, only the ones related to the pods they are asked to run

**Comment by arrowfeng** [comment]
Thanks very much!
