### ISSUE TITLE
[Failing Test][sig-cluster-lifecycle-kubeadm][kubeadm-kinder-upgrade-1-22-1-23]

### ISSUE THREAD

**Issue by simrangupta234** [kubernetes/kubernetes#106801]
### Which jobs are failing?

kubeadm-kinder-upgrade-1-22-1-23

### Kubernetes e2e suite: [sig-node] Probing container should *not* be restarted with a exec "cat /tmp/health" liveness probe [NodeConformance] [Conformance] 

/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:630
Nov 25 20:49:58.623: pod container-probe-6974/busybox-421cd6d9-c6fb-4ef9-91b2-9fdcb21acffd - expected number of restarts: 0, found restarts: 2
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/common/node/container_probe.go:150

### kinder.test.workflow: task-09-e2e-after
exit status 1

### Since when has it been failing?

11/26/2021 01:51 IST

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-22-1-23
or https://testgrid.k8s.io/sig-release-1.23-informing#kubeadm-kinder-upgrade-1-22-1-23

### Relevant SIG(s)

/sig

**Comment by neolit123** [comment]
this is due to:
https://github.com/kubernetes/kubernetes/issues/106566
let's track the problem in the same issue.

thanks
/close
