### ISSUE TITLE
How would k8s service work with HTTP/3?

### ISSUE THREAD

**Issue by khteh** [kubernetes/kubernetes#106864]
### What would you like to be added?

HTTP/3 will be a game changer as it is using QUIC which is based on UDP and the connections are independent of IP addresses. How would k8s service change to better work with HTTP/3 in the future, especially with regards to load-balancing HTTP/3 traffic?

### Why is this needed?

HTTP/3 will be a game changer as it is using QUIC which is based on UDP and the connections are independent of IP addresses. How would k8s service change to better work with HTTP/3 in the future, especially with regards to load-balancing HTTP/3 traffic?

**Comment by aojea** [comment]
/assign

yeah, I've started to explore this topic recently, we can use this issue to track the evolution of HTTP3 for Services.
Some interesting and related links
https://datatracker.ietf.org/doc/html/draft-ietf-quic-load-balancers
https://datatracker.ietf.org/doc/html/rfc9000#section-5.2.3

**Comment by khenidak** [comment]
i think we need to contextualize this. Is this related to kuberentes own control plane or some deployable user service/pods etc?

**Comment by aojea** [comment]
> HTTP/3 will be a game changer as it is using QUIC which is based on UDP and the connections are independent of IP addresses. How would k8s service change to better work with HTTP/3 in the future, especially with regards to load-balancing HTTP/3 traffic?

I understand the question is related to Services

**Comment by khteh** [comment]
HTTP/2 multiplex streams on the same connection which is bound to one IP address. How would things change on HTTP/3? Would service load balancing still based on connection or could it be on "streams" (don't know what it will be called in HTTP/3). Take GRPC, for instance. How do applications achieve server-side load balancing using k8s service if client applications issue multiple GRPC calls asynchronously on one single connection?

**Comment by aojea** [comment]
http2 uses TCP, NAT on linux uses conntrack, that is able to identify the connections and its stats, same connection keeps going to the same backend.
http3 uses QUIC for transport that uses UDP, conntrack uses timers to identify the connection but there is no clue about session status, if http3/QUIC has keepalives with a timer lower than the UDP conntrack, it will renew the conntrack entry and there will be not problem ... 
I ignore if QUIC has this keepalives with sane defaults or if the conntrack kernel has implemented some heuristics to improve this

**Comment by aojea** [comment]
first step is to have CI signal , add testing so we can know which we do support now and what not
https://github.com/kubernetes/kubernetes/pull/107017

**Comment by thockin** [comment]
@aojea want to just triage-accept this?

**Comment by khteh** [comment]
Any update on this?

**Comment by aojea** [comment]
> http2 uses TCP, NAT on linux uses conntrack, that is able to identify the connections and its stats, same connection keeps going to the same backend. http3 uses QUIC for transport that uses UDP, conntrack uses timers to identify the connection but there is no clue about session status, if http3/QUIC has keepalives with a timer lower than the UDP conntrack, it will renew the conntrack entry and there will be not problem ... I ignore if QUIC has this keepalives with sane defaults or if the conntrack kernel has implemented some heuristics to improve this

the only thing that is missing is and e2e test to provide additional reassurance that it works fine, but for kubernetes these are just udp packets ...

**Comment by gr0l0rg** [comment]
Is there any ongoing work on this? k8s needs QUIC-based services along with TCP and UDP where you can load balance QUIC connections among different endpoints/pods regardless of whether the traffic is HTTP3 or any other protocol. It should be treated like TCP.

**Comment by aojea** [comment]
I don't follow your comment sorry, Services are only aware of the protocol TCP, UDP or SCTP, if you have a Service with HTTP and HTTP3 you should define both protocols, i.e.

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
    - name: http3
      protocol: UDP
      port: 443
      targetPort: 9377
```

For L7 load balancing you should use gateway-api or a different API that handlers

**Comment by gr0l0rg** [comment]
@aojea thanks for the QUIC response :D. I meant that QUIC itself is considered a transport protocol just like TCP that can convey arbitrary L7 traffic. I guess there are already some L7 protocols like NFS and SSH as well as other ad-hoc applications trying to build their L7 protocols over QUIC instead of plaintext TCP and major cloud providers are starting to offer or planning to offer gateway QUIC load balancers. It would be more beneficial if k8s supports service loadbalancing for QUIC as a generic transport protocol just like TCP because using loadbancing over UDP basically won't work if you have more than a single endpoint.
I know it won't be not that smooth since you need to manage certificates like it's Istio, but QUIC is probably going to be the new TCP for microservices a decade from now and not just used for HTTP3.

**Comment by aojea** [comment]
> using the current UDP load balancing, any pod from svcB will not be able to request anything form svcA unless it's implemented by a single pod in svcA

why?
