### ISSUE TITLE
E2eNode Suite.[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/kubernetes#106895]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu

### Which tests are flaking?

E2eNode Suite.[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api

### Since when has it been flaking?

From test Job history, it has been flaking since at least 09/10/2021 [1]. And based on https://github.com/kubernetes/kubernetes/issues/104292#issuecomment-897805729, it has been flaking at least since 08/11.

[1] https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-ubuntu?buildId=1437202307631550464

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu

### Reason for failure (if possible)

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/summary_test.go:54
Failed after 15.293s.
Expected
    <string>: Summary
to match fields: {
.Pods[summary-test-915::stats-busybox-0].Memory:
	Expected
	    <string>: MemoryStats
	to match fields: {
	.RSSBytes:
		Expected
		    <uint64>: 0
		to be >=
		    <int64>: 1000
	}
	
}
```

### Anything else we need to know?

Note that the same test does not flake on the other test grid testing against Fedora (https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora)

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
Is it dup with #104292？

**Comment by ruiwen-zhao** [comment]
> Is it dup with #104292？

Not really. The failure in https://github.com/kubernetes/kubernetes/issues/104292 is timeout, but this failure is unexpected value:
```
Expected
	    <string>: MemoryStats
	to match fields: {
	.RSSBytes:
		Expected
		    <uint64>: 0
		to be >=
		    <int64>: 1000
	}
```

Plus, the   kubelet-gce-e2e-swap-ubuntu grid is way more flaky than the fedora one.

**Comment by SergeyKanzhelev** [comment]
thank you for reporting.

We will file a separate issue to migrate the test to containerd. Let's see if it will be failing after this.

/close
