### ISSUE TITLE
Unable to import package

### ISSUE THREAD

**Issue by krishna-birla** [kubernetes/kubernetes#106871]
### What happened?

When importing the package version 1.23.0, facing the error:
```
go: k8s.io/kubernetes@v1.23.0 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

### What did you expect to happen?

Expected the package to import normally.

### How can we reproduce it (as minimally and precisely as possible)?

Try including k8s.io/kubernetes@v1.23.0 in your go mod file.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>
```
Darwin
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/api/releases/tag/v0.23.0 and https://pkg.go.dev/k8s.io/api@v0.23.0.

go get k8s.io/api@v0.23.0

**Comment by liggitt** [comment]
as noted in https://github.com/kubernetes/kubernetes#to-start-using-k8s:

> Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

The modules exported from `staging/src/k8s.io/...` are the ones intended to be used as libraries and dependencies

/close
