### ISSUE TITLE
Add queueName field to batch/v1.Job spec

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#106886]
### What would you like to be added?

A field to the Job spec that allows setting a `queueName`.

### Why is this needed?

While in core k8s we don't have support for queues, and so nothing will act on it, `queueName` will help external queueing controllers to converse into a unified API for batch users.

One related precedence is service type LoadBalancer. LoadBalancer service type doesn't setup an actual load balancer unless there is provider support. This could be looked at in the same way.

/sig apps
/sig scheduling

**Comment by pacoxu** [comment]
The queue sounds like https://github.com/kubernetes/kubernetes/issues/106802#issuecomment-988530288 which want something like `waitfor` completion of another job in job spec.

**Comment by alculquicondor** [comment]
This is not about pipelining. It's just queuing based on allowed/existing resources.

**Comment by minbaev** [comment]
Hi, I would like to work on this item

**Comment by ahg-g** [comment]
@liggitt from API perspective, is this something acceptable?

**Comment by liggitt** [comment]
this reminds me a lot of `spec.schedulerName` on pods

**Comment by kerthcet** [comment]
Hi @ahg-g , do you have time, if not, I can help draft a KEP.

**Comment by alculquicondor** [comment]
That would be great. Please go ahead.

**Comment by alculquicondor** [comment]
If the enhancement is closed https://github.com/kubernetes/enhancements/issues/3328, we should probably close this too.

Maybe in the future we will have more reasons to implement this, but for now there is not enough justification.
