### ISSUE TITLE
kube-scheduler default port (breaking) change not mentioned in 1.23 changelog

### ISSUE THREAD

**Issue by invidian** [kubernetes/kubernetes#106885]
### What happened?

It looks like default HTTPS port for kube-scheduler has changed from 10251 to 10259 between 1.22.4 and 1.23.0 releases and it has not been mentioned in the changelog.
```
I1208 11:30:46.202095       1 deprecated_insecure_serving.go:54] Serving healthz insecurely on [::]:10251
```

```
I1208 09:17:41.523334       1 secure_serving.go:200] Serving securely on [::]:10259
```

EDIT: Actually, I see now that 1.22.4 listens on 10259, but also on 10251 and 1.23.0 just stopped listening on 10251.

### What did you expect to happen?

Breaking changes to be included in the changelog.

### How can we reproduce it (as minimally and precisely as possible)?

With kube-prometheus-stack installed, with kube-scheduler scraping configured, upgrade kube-scheduler from 1.22.4 to 1.23.0.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"2021-11-18T21:20:32Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/96345 was the change, and included a detailed release note. Did that not get pulled into the release notes automatically?

/sig docs release

**Comment by liggitt** [comment]
@ingvagabund, can you help update the 1.23 release notes with the content from https://github.com/kubernetes/kubernetes/pull/96345 in the "Action required" section?

**Comment by invidian** [comment]
I see now that it has indeed been mentioned for `v1.23.0-alpha.2`, here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation-4. but not for `v1.23.0`.

**Comment by liggitt** [comment]
weird, v1.23.0 is supposed to roll up all the intermediate notes.

**Comment by liggitt** [comment]
> Is it sufficient to manually edit and extend https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation?

manual edit is fine, hoist it to the https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation section
