### ISSUE TITLE
External DNS outage on all nodes as they join the kubernetes cluster

### ISSUE THREAD

**Issue by souradeepmoe** [kubernetes/kubernetes#106951]
### What happened?

DNS calls made to our VPC nameserver started to fail with `i/o timeout` from coredns pods *and* from all the worker nodes. Kubernetes service DNS names were getting resolved by coredns.

Initially we thought that this was not related to kubernetes. However, we found out that the DNS outage happens **after** the node joins the kubernetes cluster. **The outage triggered automatically, there were no changes made to the cluster.**

CoreDNS log:
``` shell
collector-010.newrelic.com. A: read udp 10.12.55.33:37632->10.20.0.2:53: i/o timeout
```

Docker pull logs:
``` bash
dial tcp: lookup 07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com on 10.20.0.2:53: read udp 10.20.5.188:64198->10.20.0.2:53: i/o timeout
```

Manual resolution:
``` bash
$ curl google.com
curl: (6) Could not resolve host: google.com
```

`10.20.0.2` is the IP of our VPC nameserver.

The DNS outage started all of a sudden and affected all the nodes in the cluster. We saw the following behaviours:
1. Containers already running were working since they already had DNS names resolved. 
2. New nodes coming up were not able to spawn containers since they couldn’t resolve our ECR repo’s DNS name.
3. New containers scheduled in existing nodes (which had previously downloaded docker images) came up, but the applications were not healthy as they were not able to resolve DNS names of services external to kubernetes.

**On debugging further, we found the following pattern whenever a new k8s worker node comes up:**

1. The node is able to perform DNS resolution prior to joining the cluster
2. The node joins the cluster, and just when the kube-proxy pod starts in the node, the DNS resolution stops working. If the kube-proxy pod fails to start, the DNS resolution is intact and working.
3. We have verified that outgoing internet connections using IPv4 addresses are working, only DNS resolution fails.

**Simultaneous issue:**

As we tried to stream the logs and ssh into the running pods to perform debugging from inside the container, we saw the following authorization errors:

``` bash
$ kubectl exec -i -t static-web  -- sh              
error: unable to upgrade connection: Authorization error (user=kube-apiserver-kubelet-client, verb=create, resource=nodes, subresource=proxy)
```
This error should mean that the master api server was not able to authorize itself to the node's kubelet.  We did not see any DNS resolutions errors for kubernetes service names on coredns. A question here, only external VPC DNS names were failing, how would that trigger the above error, if kubernetes names were getting resolved?

We created the following cluster role binding to address the missing authorization:
``` yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubelet-api-admin
subjects:
- kind: User
  name: kube-apiserver-kubelet-client
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: system:kubelet-api-admin
  apiGroup: rbac.authorization.k8s.io
```

After the application of the cluster role binding, we saw the following internal server error:

``` bash
$ kubectl logs -n kube-system --selector 'k8s-app=kube-proxy'
Error from server (InternalError): Internal error occurred: Authorization error (user=kube-apiserver-kubelet-client, verb=get, resource=nodes, subresource=proxy)
```

Also, what is even more strange is that the system just fixed itself automatically after around 12 hours. We had rolled out kube-proxy to the latest version, and the rollout failed (the rollout was stalled because the image of the updated version of kube-proxy could not be downloaded, again because of DNS failure while resolving the docker registry's hostname). One hour later, we saw that the entire system got fixed, cluster-wide, just like it started without **performing any change from our side**. The RBAC authorization errors on kubectl logs and exec were also fixed.

We went through the k8s master logs available on AWS CloudWatch logs as we are hosted on AWS EKS, but didn't find logs neither which indicates a trigger to the outage nor the auto-fix behavior.

From this, I have a hunch that maybe this did not happen at the worker node level, but at the cluster level, since we had cluster-wide DNS issues at once. Other instances in the same subnet were able to perform DNS resolution from our VPC nameserver without any issues.

Couple of questions that arise here:
1. Can the master components be responsible in any way for this?
2. When kube-proxy comes up, it enables service <-> pod communication via iptable rules. Does this trigger some other component, which plays with the host’s DNS resolution?
3. We use cilium as our CNI, does cilium has the capacity to do this?

**More resources and logs:**

1. `kube-dns` cluster IP:

``` bash
$ kubectl get service kube-dns -n kube-system

NAME       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   172.20.0.10   <none>        53/UDP,53/TCP   619d
```

2. `resolve.conf` on host:
``` bash
$ cat /etc/resolv.conf 
; generated by /usr/sbin/dhclient-script
search ap-south-1.compute.internal
options timeout:2 attempts:5
nameserver 10.20.0.2
```

3. Kubelet service status:

``` log
$ sudo systemctl status kubelet -l
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubelet-args.conf, 30-kubelet-extra-args.conf
   Active: active (running) since Fri 2021-11-26 08:54:00 UTC; 48min ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 5287 (kubelet)
    Tasks: 22
   Memory: 163.1M
   CGroup: /system.slice/kubelet.service
           └─5287 /usr/bin/kubelet --cloud-provider aws --config /etc/kubernetes/kubelet/kubelet-config.json --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime docker --network-plugin cni --node-ip=10.20.76.28 --pod-infra-container-image=602401143452.dkr.ecr.ap-south-1.amazonaws.com/eks/pause:3.1-eksbuild.1 --v=2 --kube-reserved cpu=100m,memory=0.5Gi,ephemeral-storage=1Gi --system-reserved cpu=100m,memory=0.2Gi,ephemeral-storage=1Gi --eviction-hard memory.available<500Mi,nodefs.available<10% --allowed-unsafe-sysctls net.core.somaxconn --node-labels=eks.moengage.io/namespace=sre,eks.moengage.io/lifecycle=ondemand

Nov 26 09:42:20 ip-10-20-76-28.ap-south-1.compute.internal kubelet[5287]: E1126 09:42:20.103211    5287 webhook.go:111] Failed to make webhook authenticator request: Post "https://07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com/apis/authentication.k8s.io/v1/tokenreviews": dial tcp: lookup 07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com on 10.20.0.2:53: read udp 10.20.3.68:47851->10.20.0.2:53: i/o timeout
Nov 26 09:42:20 ip-10-20-76-28.ap-south-1.compute.internal kubelet[5287]: E1126 09:42:20.103272    5287 server.go:270] Unable to authenticate the request due to an error: Post "https://07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com/apis/authentication.k8s.io/v1/tokenreviews": dial tcp: lookup 07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com on 10.20.0.2:53: read udp 10.20.3.68:47851->10.20.0.2:53: i/o timeout
Nov 26 09:42:20 ip-10-20-76-28.ap-south-1.compute.internal kubelet[5287]: E1126 09:42:20.103210    5287 event.go:273] Unable to write event: 'Patch "https://07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com/api/v1/namespaces/data-platform/events/connect-debezium-cluster-connect-6bbfc87485-2mkbj.16bb0ce9b66a4bac": dial tcp: lookup 07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com on 10.20.0.2:53: read udp 10.20.3.68:47851->10.20.0.2:53: i/o timeout' (may retry after sleeping)
Nov 26 09:42:20 ip-10-20-76-28.ap-south-1.compute.internal kubelet[5287]: E1126 09:42:20.103212    5287 webhook.go:111] Failed to make webhook authenticator request: Post "https://07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com/apis/authentication.k8s.io/v1/tokenreviews": dial tcp: lookup 07B4738AC15E7C20474C8AFF4BDAC842.yl4.ap-south-1.eks.amazonaws.com on 10.20.0.2:53: read udp 10.20.3.68:47851->10.20.0.2:53: i/o timeout
```

4. kubelet systemd service configuration:
``` conf
$ cat /etc/systemd/system/kubelet.service
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=docker.service iptables-restore.service
Requires=docker.service

[Service]
ExecStartPre=/sbin/iptables -P FORWARD ACCEPT -w 5
ExecStart=/usr/bin/kubelet --cloud-provider aws \
    --config /etc/kubernetes/kubelet/kubelet-config.json \
    --kubeconfig /var/lib/kubelet/kubeconfig \
    --container-runtime docker \
    --network-plugin cni $KUBELET_ARGS $KUBELET_EXTRA_ARGS

Restart=always
RestartSec=5
KillMode=process

[Install]
WantedBy=multi-user.target
```

5. Anomalous logs:
``` log
Nov 26 08:54:06 ip-10-20-76-28.ap-south-1.compute.internal kubelet[5287]: E1126 08:54:06.322322    5287 kubelet.go:2108] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin 

cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
```

### What did you expect to happen?

1. DNS resolutions to happen normally
2. kubectl logs/exec would not face authorization errors 

### How can we reproduce it (as minimally and precisely as possible)?

We could not reproduce it since we could not figure out the root cause. The only relevant log we found were the `i/o timeout` to the upstream nameserver, which is our VPC nameserver.

### Kubernetes version
<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:35:15Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version
<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

$ uname -a
Linux ip-10-20-75-131.ap-south-1.compute.internal 5.4.117-58.216.amzn2.x86_64 #1 SMP Tue May 11 20:50:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Docker version 19.03.13-ce, build 4484c46
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CSI: AWS EBS CSI (k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.1)
<br>
CNI: Cilium (quay.io/cilium/operator-generic:v1.9.8)
</details>

**Comment by pacoxu** [comment]
To dig into the problem from the coredns side, I think you can enable `access log` of corends by adding the below configuration to coredns configmap. Then, coredns will show you all requests to it and all forwarding requests to your local nameserver. That may help to show some info. By the way, the coredns metrics may help to know what happened. 
```
    log . {
        class denial success
    }
```
This may help us confirm whether the DNS server load is too high.

**Comment by chrisohaver** [comment]
> To dig into the problem from the coredns side ...

Per issue description, DNS also times out from "all worker nodes", which do not query CoreDNS.  So seems unlikely that CoreDNS would be the cause.

> We have verified that outgoing internet connections using IPv4 addresses are working, only DNS resolution fails.

Perhaps UDP is affected and TCP is not? Could try `force_tcp` option in CoreDNS.  Nodes would still use UDP though, since their queries do not flow through CoreDNS.

**Comment by souradeepmoe** [comment]
The primary issue that we are facing now is that the issue was fixed automatically, and we are not able to reproduce the issue, as we do not know the root cause.

> This may help us confirm whether the DNS server load is too high.

Hi @pacoxu, as @chrisohaver also pointed out, we were seeing DNS resolution issues across all worker nodes all of a sudden. We were tracking metrics exposed by coredns and found that the response times were very high, due to the `i/o timeouts` while reaching out to our VPC nameserver.

> Perhaps UDP is affected and TCP is not? Could try `force_tcp` option in CoreDNS. Nodes would still use UDP though, since their queries do not flow through CoreDNS.

@chrisohaver right now the issue is fixed automatically, and all UDP connections are working. We are digging into why this happened.

Can I please get some help on these aspects to better understand the root cause:

> From this, I have a hunch that maybe this did not happen at the worker node level, but at the cluster level, since we had cluster-wide DNS issues at once. Other instances in the same subnet were able to perform DNS resolution from our VPC nameserver without any issues.
> 
> Couple of questions that arise here:
> 
> 1. Can the master components be responsible in any way for this?
> 2. When kube-proxy comes up, it enables service <-> pod communication via iptable rules. Does this trigger some other component, which plays with the host’s DNS resolution?
> 3. We use cilium as our CNI, does cilium has the capacity to do this?
>

**Comment by pacoxu** [comment]
For DNS failure observability and diagnosis, I attended the China Kubecon topic https://sched.co/pcag. You can check if it helps. There are many observability tools for DNS that may help to find the root cause.

Observability | Plugin Name
-- | --
Logging | log
-- | dump
-- | debug
-- | dnstap
Tracing | trace
Metrics | prometheus

If this is not a coredns issue, I'm not sure how to move on.

**Comment by souradeepmoe** [comment]
Thanks for the help @pacoxu , I will anyways check the observability tools on DNS mentioned here, since DNS is one of the most commons outages with large blast radius.

**Comment by thockin** [comment]
First, great bug report, thanks.

I can't fathom how a node joining causes a coordinated DNS outage across other nodes.  Is anyone who works on cilium able to take a look?

**Comment by thockin** [comment]
@aanm as a sacrificial nomination - any ideas on this?  Could it possibly be Cilium related?  I don't see how it could be anything but a node-agent related..

**Comment by aanm** [comment]
@thockin I find this part relevant:

> The node joins the cluster, and just when the kube-proxy pod starts in the node, the DNS resolution stops working. If the kube-proxy pod fails to start, the DNS resolution is intact and working.

I don't discard a bug that could be caused by an incompatibility between an iptables rule installed by kube-proxy and Cilium. However, this highly depends on the Cilium configuration that is deployed.

@souradeepmoe could you open a GitHub issue on the cilium repository as well and provide a Cilium sysdump of this cluster? It would also be extremely helpful if you could give some reproducible steps. I assume the issue could easily be triggered by deploying a 3 node cluster with a similar configuration that you have and once a 4th is added that there is a DNS outage on all nodes?

Thank you

**Comment by souradeepmoe** [comment]
> First, great bug report, thanks.

Thanks @thockin for the appreciation. We did quite a lot of debugging within our org, and then reached out here, to the kubernetes community for support as we faced dead ends. 

> I can't fathom how a node joining causes a coordinated DNS outage across other nodes. Is anyone who works on cilium able to take a look?

A note here, the node joining didn't cause a coordinated DNS outage. Rather, all the cluster nodes already had an outage with the DNS. We tested that as the node joins the cluster, the node also shows the same behavior.


> I don't discard a bug that could be caused by an incompatibility between an iptables rule installed by kube-proxy and Cilium. However, this highly depends on the Cilium configuration that is deployed.

@aanm @thockin This could be an issue. I have a couple of doubts here:
1. I went through kube-proxy logs of an infected machine, and saw that there were no errors while syncing rules to iptables. Even if kube-proxy was syncing the wrong rules, wouldn't that only effect resolution of kubernetes service names to its pods?
2. I verified from the cilium logs that external DNS resolution requests from coredns were routing via cilium, while DNS requests made directly on the host system were not. Can cilium be responsible for routing requests from the host system?

From these, I earlier had the idea that a malfunctioning kube-proxy and/or cilium might not be involved in DNS outage in the host system. I assumed kube-proxy is involved in the issue, but indirectly. Please show some light into the possibilities.


> @souradeepmoe could you open a GitHub issue on the cilium repository as well and provide a Cilium sysdump of this cluster? It would also be extremely helpful if you could give some reproducible steps. I assume the issue could easily be triggered by deploying a 3 node cluster with a similar configuration that you have and once a 4th is added that there is a DNS outage on all nodes?

@aanm  So, we had this issue in one of our production clusters, and as I mentioned earlier, the issue got fixed automatically after 12 hours. We had migrated the services running early on. Unfortunately, we are in a state where we don't know what triggered the issue and what fixed it. So, we couldn't reproduce the issue ourselves.

That also made our debugging process very difficult, as it was mostly around reading logs and identifying issue points based on theories, since the cluster had fixed itself quite magically. Also, as I mentioned earlier, the cluster already had a DNS outage, and any nodes joining the cluster replicated the same behaviour.

Will the cilium dump of the cluster be helpful now, as the cluster got fixed?

Thanks a lot.

**Comment by aanm** [comment]
> Will the cilium dump of the cluster be helpful now, as the cluster got fixed?

@souradeepmoe unfortunately not as the issue is no longer present. If you hit the issue again a cluster sysdump will be useful. Thank you!

**Comment by thockin** [comment]
If the nodes themselves were haaving aa DNS problem, then it's unlikely to have been kube-proxy or cilium, but bugs do happen.

If it happens again, capturing cilium state + `iptables-save` + node's /etc/resolv.conf would help.

Is the `10.20.0.2` address a real address or a k8s service IP?  Was it really up?  Could you do DNS lookups using it specifically?  Could you  do DNS lookups against 8.8.8.8 ?

I'm going to close for now, but if it recurs pleaase reopen!!

**Comment by souradeepmoe** [comment]
We verified the address `10.20.0.2` was up as it our AWS VPC nameserver and other instances were able to make queries against it. We also verified that the affected instances were not being throttled at this address. However, we did not test DNS loopkups against 8.8.8.8.

Thanks again for support @aanm @thockin , will take the network dump if we face this issue the next time.
