### ISSUE TITLE
After upgrading to v1.23.0, the pause container still uses 3.5, kubeadm config images list shows 3.6

### ISSUE THREAD

**Issue by offSwitch** [kubernetes/kubernetes#106903]
### What happened?

![image](https://user-images.githubusercontent.com/11695496/145334097-870c3cb1-5479-4f57-808c-b4ba62e62aa1.png)

### What did you expect to happen?

The pause container should use the 3.6

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init --apiserver-advertise-address 192.168.137.15  --pod-network-cidr=10.244.0.0/16

### Kubernetes version

root@dockerone:/etc/kubernetes/manifests# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>

</details>

### OS version

root@dockerone:/etc/kubernetes/manifests# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
I suspect this is caused by different configurations between kubeadm and contained.

- You can check `/etc/containerd/config.toml` for contained configuration.
- You can check kubeadm configuration in `/var/lib/kubelet/kubeadm-flags.env`.
```
[root@daocloud ~]# cat /etc/containerd/config.toml  | grep pause
    pause_threshold = 0.02
    sandbox_image = "k8s-gcr.m.daocloud.io/pause:3.5"

[root@daocloud ~]#  cat /var/lib/kubelet/kubeadm-flags.env
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/var/run/containerd/containerd.sock --pod-infra-container-image=k8s-gcr.m.daocloud.io/pause:3.5"
```

**Comment by offSwitch** [comment]
> I suspect this is caused by different configurations between kubeadm and contained.
> 
> * You can check `/etc/containerd/config.toml` for contained configuration.
> * You can check kubeadm configuration in `/var/lib/kubelet/kubeadm-flags.env`.
> 
> ```
> [root@daocloud ~]# cat /etc/containerd/config.toml  | grep pause
>     pause_threshold = 0.02
>     sandbox_image = "k8s-gcr.m.daocloud.io/pause:3.5"
> 
> [root@daocloud ~]#  cat /var/lib/kubelet/kubeadm-flags.env
> KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=/var/run/containerd/containerd.sock --pod-infra-container-image=k8s-gcr.m.daocloud.io/pause:3.5"
> ```

I tried to delete the sandbox_image in config.toml, and then reinitialize it, but found no effect. Then I configured the sandbox_image to 3.6 and initialized it with 3.6, I checked the previous issue and found that the parameter pod-infra-container-image is only valid for docker, not for other CRIs, I don't know if this parameter is valid for containerd now.

**Comment by ehashman** [comment]
From https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/:

--pod-infra-container-image string     Default: k8s.gcr.io/pause:3.5

Specified image will not be pruned by the image garbage collector. When container-runtime is set to docker,  all containers in each pod will use the network/IPC namespaces from  this image. Other CRI implementations have their own configuration to  set this image.


This flag has no effect on non-docker container runtimes, can you try setting the containerd sandbox_image in your containerd config? I will double check to make sure we have an action-required release note for this.

/triage needs-information

**Comment by neolit123** [comment]
> I checked the previous issue and found that the parameter pod-infra-container-image is only valid for docker, not for other CRIs, I don't know if this parameter is valid for containerd now.

newer versions of kubeadm pass the flag even for non-docker container runtimes to avoid the kubelet garbage collecting the image. AFAIK there are proposals to resolve the problem.
https://github.com/kubernetes/kubernetes/issues/106893#issuecomment-989511406

if you are using a container runtime version `foo` that has `3.5` in its config, but kubeadm and kubelet version `bar` prefer `3.6` you should update your container runtime config to use `3.6` as well.
