### ISSUE TITLE
replace syscall with sys/unix pkg 

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#106995]
### What happened?

Similar to #57430, it seems there are still many use of  pkg syscall  in the code. 
https://github.com/kubernetes/kubernetes/blob/770847e6b06d89326f0f2d42c26487cc7f9eae06/pkg/util/ipvs/ipvs_linux.go#L27

### What did you expect to happen?

replace syscall with sys/unix pkg.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

```
NOTE: This package is locked down.
Code outside the standard Go repository should be migrated to use the corresponding package in the golang.org/x/sys repository.
That is also where updates required by new systems or versions should be applied.
See https://golang.org/s/go1.4-syscall for more information.
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
any

### Cloud provider

<details>

</details>
any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Estherbdf** [comment]
I search "syscall" in the repo : https://github.com/search?l=&q=%22syscall%22+repo%3Akubernetes%2Fkubernetes&type=code
Should all use of the pkg “syscall" replaced with "sys/linux" ?

**Comment by aojea** [comment]
wow , that is a long list, better talking with @dims  or @liggitt that are more used to deal with these code organization things
