### ISSUE TITLE
StorageClass cannot be updated/replaced

### ISSUE THREAD

**Issue by pkit** [kubernetes/kubernetes#106996]
### What happened?

Reopen of #80472

### What did you expect to happen?

`StorageClass` can be updated

### How can we reproduce it (as minimally and precisely as possible)?

See #80472 , nothing changed in 2 years

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Kartik494** [comment]
@pkit this seems to issue with updating parameters only? i am not able to replace it while updating `provisioner` in sc.Throwing error as:

`The StorageClass "example" is invalid: provisioner: Forbidden: updates to provisioner are forbidden`
