### ISSUE TITLE
local-up-cluster.sh more difficult to run due to dockershim removal

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#106972]
### What happened?

hack/local-up-cluster.sh still defaults to the 'docker' container-runtime. This causes the kubelet to fail to start with an error -in the kubelet log- about the dockershim not being supported. The non-obvious fix is to set the CONTAINER_RUNTIME and KUBE_CONTAINER_RUNTIME_ENDPOINT variables to configure the runtime (containerd, cri-o, etc) and their socket.

### What did you expect to happen?

I would expect hack/local-up-cluster.sh to:

1. auto-configure a runtime (containerd or crio) or,
2. detect missing environment variables and erroring out, or,
3. fallback with an appropriate error message about missing a container runtime.

### How can we reproduce it (as minimally and precisely as possible)?

Latest master branch (c7ff5758db1ab5d1f399d60c8076389cb7c297d2). I have containerd running, but the script (nor the kubelet) detected the runtime.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
I think this will fix it https://github.com/kubernetes/kubernetes/pull/106909

**Comment by ehashman** [comment]
We discussed this briefly in the 11/30 SIG Node meeting: https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#bookmark=id.8tx8w0w0y4n2

**Comment by adisky** [comment]
Do we really want to install container runtime as a part of hack/local-up-cluster.sh? for dockershim also the script requires docker is already installed

**Comment by sftim** [comment]
I think this is less of a docs concern and more of a contributor experience concern. @SergeyKanzhelev would you agree?
