### ISSUE TITLE
[Ansible] When master IP changes we don't regen the cert

### ISSUE THREAD

**Issue by jeffbean** [kubernetes/kubernetes#10694]
The condition on task for checking if the cert is created only checks the file. We need to name the file something so we can know when to force the task to create a new cert on IP change. 

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/ansible/roles/kubernetes/tasks/gen_certs.yml#L20
### Issue

Kubelet can then not reconnect to apimaster

```
Jul 02 23:54:56 node-1.vms.local kubelet[12850]: E0702 23:54:56.092537   12850 reflector.go:136] Failed to list *api.Service: Get https://172.10.1.100:443/api/v1/services: x509: certificate is valid for 10.0.2.15, 10.254.0.1, not 172.10.1.100
Jul 02 23:54:56 node-1.vms.local kubelet[12850]: E0702 23:54:56.217163   12850 reflector.go:136] Failed to list *api.Node: Get https://172.10.1.100:443/api/v1/nodes?fieldSelector=metadata.name%3D172.10.1.11: x509: certificate is valid for 10.0.2.15, 10.254.0.1, not 172.10.1.100
Jul 02 23:54:56 node-1.vms.local kubelet[12850]: E0702 23:54:56.235534   12850 reflector.go:136] Failed to list *api.Pod: Get https://172.10.1.100:443/api/v1/pods?fieldSelector=spec.nodeName%3D172.10.1.11: x509: certificate is valid for 10.0.2.15, 10.254.0.1, not 172.10.1.100
```
### Possible solutions
1. Have the script that create the certs drop a single empty file that tis the IP passes into it.
2. Regenerate a new cert every ansible run.
3. Write some ansible tasks that somehow know we changed IP address of the master node

**Comment by jeffbean** [comment]
@eparis any thoughts on this?
I really don't want to change the cert script for our needs so not a great solution.

**Comment by eparis** [comment]
Changing the --cluster-service-ip-range also invalidates the cert.

We also are not saving the ca.key, so it's not like we can just mint a new apiserver cert, we have to mint entirely new certs for everything...

It's a problem. i'll think on it as well...

**Comment by roberthbailey** [comment]
As this code has been moved to the contrib repository (e.g. https://github.com/kubernetes/contrib/blob/master/ansible/roles/kubernetes/tasks/gen_certs.yml), please reopen this issue there if it is still something that needs to be addressed.
