### ISSUE TITLE
Update links to IANA for Service Name and Transport Protocol Port Number Registry

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#106980]
### What happened?

We should make the change in PR https://github.com/kubernetes/kubernetes/pull/105590

### What did you expect to happen?

API reference links to https://www.iana.org/assignments/ should use HTTPS, not HTTP

### How can we reproduce it (as minimally and precisely as possible)?

Visit h
ttps://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/ and look at the IANA hyperlinks

### Anything else we need to know?

Once this fix is made, a PR to [k/website](https://github.com/kubernetes/website/) is needed to update the docs (by autogenerating them). This typically would be deferred until the next Kubernetes release.
### Kubernetes version

v1.23

### Cloud provider

_not applicable_

### OS version

_not applicable_

### Install tools

_not applicable_

### Container runtime (CRI) and and version (if applicable)

_not applicable_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_not applicable_

**Comment by sftim** [comment]
I opened this issue so that someone else can open a new PR that is equivalent to #105590.

**Comment by sftim** [comment]
/retitle Update links to IANA for Service Name and Transport Protocol Port Number Registry

**Comment by jayesh-srivastava** [comment]
@sftim I would like to work on this issue. May I assign it to myself?

**Comment by sftim** [comment]
Anyone - including you @jayesh-srivastava - is welcome to work on this issue! So long as you've [signed the CLA](https://www.kubernetes.dev/docs/guide/#sign-the-cla) you can open a pull request to propose a fix.

**Comment by jayesh-srivastava** [comment]
Thanks @sftim. One more thing, I looked at PR #105590. Do I have to make the same changes or anything else. Can you please guide me through. That would be very helpful.

**Comment by jayesh-srivastava** [comment]
@sftim I have made the PR. I hope this works. If not then will be happy to do the necessary changes.

**Comment by jayesh-srivastava** [comment]
@sftim Had to close the previous PR because of issues, here is the new one I made.
