### ISSUE TITLE
GracefulNodeShutdown not work

### ISSUE THREAD

**Issue by yongzhang** [kubernetes/kubernetes#107043]
### What happened?

For 1.21, by checking https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/,
I added below args to `kubelet-config.json`:
```
  "shutdownGracePeriod": "1m30s",
  "shutdownGracePeriodCriticalPods": "30s"
```
I can see `99-kubelet.conf`:
```
ubuntu@ip-10-120-80-6:~$ uname -a
Linux ip-10-120-80-6 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

ubuntu@ip-10-120-80-6:~$ cat /etc/systemd/logind.conf.d/99-kubelet.conf
# Kubelet logind override
[Login]
InhibitDelayMaxSec=90
```

But I can't see inhibitor from kubelet:
```
ubuntu@ip-10-120-80-6:~$ sudo systemd-inhibit --list
WHO                          UID USER PID COMM            WHAT     WHY                                                       MODE
Unattended Upgrades Shutdown 0   root 588 unattended-upgr shutdown Stop ongoing upgrades or perform upgrades before shutdown delay

1 inhibitors listed.
```

### What did you expect to happen?

I should be able to see inhibitors from kubelet like this?
```
kubelet-node ~ # systemd-inhibit --list
    Who: kubelet (UID 0/root, PID 1515/kubelet)
    What: shutdown
    Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```

### How can we reproduce it (as minimally and precisely as possible)?

start a new k8s node running 1.21 and run `sudo systemd-inhibit --list`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:35:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS with custom AMI
base os: Ubuntu 20.04
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux ip-10-120-52-174 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/assign @bobbypage @wzshiming

Can you please triage?

**Comment by sftim** [comment]
@yongzhang does your cluster have this beta feature enabled? It looks like you're running a managed Kubernetes distribution (EKS) that doesn't yet offer this feature.

**Comment by yongzhang** [comment]
> @yongzhang does your cluster have this beta feature enabled? It looks like you're running a managed Kubernetes distribution (EKS) that doesn't yet offer this feature.

Yes I’m using AWS EKS, but the feature gate should be enabled by default in 1.21?

**Comment by wzshiming** [comment]
@yongzhang Hi
Sorry for the late recovery, this is a known BUG in upstream Systemd, recommend to upgrade Systemd or use a new Linux distribution

**Comment by yongzhang** [comment]
> 

oh surprising, do you know which version fixed this issue?

**Comment by wzshiming** [comment]
https://gist.github.com/bobbypage/13ca9e1e8aee728dc2c7e0e1fd9b59ea
This is a script to verify that graceful shutdown is working, and there are some manual steps, you can use this to test

After v239 (CentOS 8, in my machine), it is ok

**Comment by yongzhang** [comment]
> https://gist.github.com/bobbypage/13ca9e1e8aee728dc2c7e0e1fd9b59ea This is a script to verify that graceful shutdown is working, and there are some manual steps, you can use this to test
> 
> After v239 (CentOS 8, in my machine), it is ok

I'm using v245, let me check your scripts.
```
ubuntu@ip-10-120-19-151:~$ sudo systemctl --version
systemd 245 (245.4-4ubuntu3.13)
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
```

**Comment by yongzhang** [comment]
@wzshiming I tested the script,
```
ubuntu@ip-10-120-19-151:~$ sudo systemd-inhibit --list
WHO                          UID USER PID    COMM            WHAT     WHY                                                       MODE
Unattended Upgrades Shutdown 0   root 603    unattended-upgr shutdown Stop ongoing upgrades or perform upgrades before shutdown delay
test-app                     0   root 781772 helloword       shutdown because                                                   delay

2 inhibitors listed.
```
Does it mean the inhibitor output will only display at shutdown happening?

**Comment by wzshiming** [comment]
Yes, Run `systemctl reboot` on a new terminal

**Comment by yongzhang** [comment]
> Yes, Run `systemctl reboot` on a new terminal
> 
> ```
> # ./dbus-shutdown
> Preparing to shutdown
> .......
> ```

OK, I may misunderstand the behavior, if I manually terminate AWS EC2, will kubelet hold on shutdown and drain the node?

**Comment by wzshiming** [comment]
Yes, until Kubelet actively releases the Inhibit lock or reaches the maximum Inhibit time

**Comment by yongzhang** [comment]
> Yes, until Kubelet actively releases the Inhibit lock or reaches the maximum Inhibit time

I just did a test, I manually terminate an EC2, I see the node is in `NotReady` state, all pods on it are in `Running` status, looks like they are not been evicted, until a new node comes up the pods are been created then old ones been terminated. I'm not sure if I missed anything.

**Comment by yongzhang** [comment]
I checked kubelet log, looks `kubelet.service` stopped quickly after I run reboot:
```
Dec 20 08:46:48 ip-10-120-24-83 systemd[1]: Stopping Kubernetes Kubelet...
Dec 20 08:46:49 ip-10-120-24-83 systemd[1]: kubelet.service: Succeeded.
Dec 20 08:46:49 ip-10-120-24-83 systemd[1]: Stopped Kubernetes Kubelet.
-- Reboot --
```

**Comment by yongzhang** [comment]
> Yes, Run `systemctl reboot` on a new terminal
> 
> ```
> # ./dbus-shutdown
> Preparing to shutdown
> .......
> ```

I followed https://trstringer.com/systemd-inhibitor-locks/, the inhibitor lock works as expected, since I can't see `kubelet` from `sudo systemd-inhibit --list`, is this still the root cause?

**Comment by wzshiming** [comment]
Could you please provide the log when Kubelet was started?

**Comment by yongzhang** [comment]
> Could you please provide the log when Kubelet was started?

I found this:
```
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.336206    1451 cpu_manager.go:199] "Starting CPU manager" policy="none"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.336225    1451 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.336247    1451 state_mem.go:36] "Initialized new in-memory state store"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.342430    1451 policy_none.go:44] "None policy: Start"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.368691    1451 manager.go:242] "Starting Device Plugin manager"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.369186    1451 container_manager_linux.go:510] "Discovered runtime cgroup name" cgroupName="/system.slice/docker.service"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.369960    1451 manager.go:600] "Failed to retrieve checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.370295    1451 manager.go:284] "Serving device plugin registration server on socket" path="/var/lib/kubelet/device-plugins/kubelet.sock"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: E1220 09:49:18.370717    1451 eviction_manager.go:255] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"ip-10-120-29-222.cn-northwest-1.compute.internal\" not found"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.371002    1451 plugin_watcher.go:52] "Plugin Watcher Start" path="/var/lib/kubelet/plugins_registry"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.371273    1451 plugin_manager.go:112] "The desired_state_of_world populator (plugin watcher) starts"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: I1220 09:49:18.371464    1451 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Dec 20 09:49:18 ip-10-120-29-222 kubelet[1451]: E1220 09:49:18.374775    1451 kubelet.go:1407] "Failed to start node shutdown manager" err="node shutdown manager was unable to update logind InhibitDelayMaxSec to 1m30s (ShutdownGracePeriod), current value of InhibitDelayMaxSec (30s) is less than requested ShutdownGracePeriod"
```

**Comment by wzshiming** [comment]
https://www.freedesktop.org/software/systemd/man/logind.conf.html

``` console
/etc/systemd/logind.conf

/etc/systemd/logind.conf.d/*.conf

/run/systemd/logind.conf.d/*.conf

/usr/lib/systemd/logind.conf.d/*.conf
```
Look in these locations to remove `InhibitDelayMaxSec=30s`

**Comment by yongzhang** [comment]
> current value of InhibitDelayMaxSec (30s) is less than requested ShutdownGracePeriod

It's set by `unattended-upgrades`, let me remove this and try.
```
ubuntu@ip-10-120-29-222:/usr/lib/systemd/logind.conf.d$ cat unattended-upgrades-logind-maxdelay.conf
[Login]
# delay
InhibitDelayMaxSec=30
```

**Comment by yongzhang** [comment]
it works now, Thanks for the help @wzshiming !

**Comment by yongzhang** [comment]
@wzshiming since unattended-upgrades is a default enabled service in ubuntu, will this be a common issue in ubuntu box?

**Comment by wzshiming** [comment]
> @wzshiming since unattended-upgrades is a default enabled service in ubuntu, will this be a common issue in ubuntu box?

Yes, but if the total time does not exceed 30s, this configuration conflict should be avoided. There is currently no better way to avoid this

**Comment by pipoe2h** [comment]
Thanks for this thread, it was really useful to troubleshoot my situation with CentOS 7.4. I have it working when not using `sudo` commands.

Something I've found out is that if I run my commands with `sudo`, it doesn't gracefully shutdown the pods (I've used the dbus app in this thread).

I've done some additional research, but I'm not sure if this is due to the old version of Systemd (219) that doesn't include [--check-inhibitors](https://github.com/systemd/systemd/pull/18210), or it's something else. 

Are you aware/know something about this?

**Comment by dwickr** [comment]
> > @wzshiming since unattended-upgrades is a default enabled service in ubuntu, will this be a common issue in ubuntu box?
> 
> Yes, but if the total time does not exceed 30s, this configuration conflict should be avoided. There is currently no better way to avoid this

I got around this by naming my logind conf file `/etc/systemd/logind.conf.d/zz-max-delay.conf`, which gives it higher precedence than the config file for unattended-upgrades, which is named `unattended-upgrades-logind-maxdelay.conf`. It's a little unfortunate they didn't follow the numbering pattern here, but the `zz-` prefix is a decent workaround for getting the Kube config to load lexicographically _after_ the unattended-upgrades config for this value.
