### ISSUE TITLE
Use zone from node for topology aware volume creation

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#107045]
### What happened?

Similar to [#78276](https://github.com/kubernetes/kubernetes/pull/78276)
> For topology aware (WaitForFirstConsumer) volume provisioning, node is already selected when we call cloud provider to create the volume.

It seems in other cloud providers also have the same problem. when the node selected, it's inefficient and redundant to list instances for getting candidate zones.
- azure

  https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/volume/azuredd/azure_provision.go#L250-L262

  

- cinder

  https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/volume/cinder/cinder_util.go#L204-L221

 

- gce

  https://github.com/kubernetes/kubernetes/blob/c1e69551be1a72f0f8db6778f20658199d3a686d/pkg/volume/gcepd/gce_util.go#L148-L189

### What did you expect to happen?

Use zone from node for topology aware volume creation to reduce unnecessary cloud provider calls

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

Any

### Cloud provider

Any

### OS version

Any

**Comment by b0b0haha** [comment]
/ sig/scalability
/ sig/storage

**Comment by b0b0haha** [comment]
/ sig cloudprovider

**Comment by nckturner** [comment]
Since the topology label is already on the node, this seems to be more of a storage issue.  
/remove-sig cloud-provider
