### ISSUE TITLE
PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lujunlai** [kubernetes/kubernetes#107093]
https://github.com/kubernetes/kubernetes/blob/362312176766a03976a8a55b7d5aa5ac89263d4a/pkg/volume/csi/csi_client.go#L538

ref:
https://github.com/grpc/grpc-go/issues/2628
https://github.com/grpc/grpc-go/pull/3730/files

Target should start with unix: to avoid setting empty authority header according to RFC-3986.

**Comment by mythi** [comment]
looks same as #109081 and #108254
