### ISSUE TITLE
Tests sig-node-node-problem-detector#ci-npd-e2e-node are failing

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107067]
### Which jobs are failing?

NPD e2e

### Which tests are failing?

Tests wouldn't start

### Since when has it been failing?

12/08

@bsdnet suggested it may be related to https://github.com/kubernetes/node-problem-detector/pull/629

/cc @Random-Liu 

### Testgrid link

https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-node

### Relevant SIG(s)

/sig node
/priority important-soon

**Comment by SergeyKanzhelev** [comment]
@vteratipally do you think you can take a look?

**Comment by vteratipally** [comment]
checked the logs for the latest failure, failing with the below message while starting kubernetes systemd probe [error log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-npd-e2e-node/1473068516939665408/artifacts/tmp-node-e2e-a6c85484-cos-89-16108-534-34-system.log)

```
Dec 20 23:18:57 tmp-node-e2e-a6c85484-cos-89-16108-534-34 systemd[1]: Started Kubernetes systemd probe.
Dec 20 23:18:57 tmp-node-e2e-a6c85484-cos-89-16108-534-34 systemd[1]: run-r807b3673a1034471be0190973fd10b25.scope: Consumed 849us CPU time
Dec 20 23:18:59 tmp-node-e2e-a6c85484-cos-89-16108-534-34 dockerd[744]: time="2021-12-20T23:18:59.050940184Z" level=warning msg="reference for unknown type: " digest="sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" remote="k8s.gcr.io/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff"
Dec 20 23:18:59 tmp-node-e2e-a6c85484-cos-89-16108-534-34 containerd[338]: time="2021-12-20T23:18:59.225052294Z" level=error msg="(*service).Write failed" error="rpc error: code = FailedPrecondition desc = unexpected commit digest sha256:5e2195668a538b5cd4247d2db9fc5a5b798eb165bc5c26f673466f6dfe33cd70, expected sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff: failed precondition" expected="sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" ref="unknown-sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff"
Dec 20 23:18:59 tmp-node-e2e-a6c85484-cos-89-16108-534-34 dockerd[744]: time="2021-12-20T23:18:59.233589937Z" level=warning msg="Error persisting manifest" digest="sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff" error="error committing manifest to content store: commit failed: unexpected commit digest sha256:5e2195668a538b5cd4247d2db9fc5a5b798eb165bc5c26f673466f6dfe33cd70, expected sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff: failed precondition" remote="k8s.gcr.io/busybox@sha256:4bdd623e848417d96127e16037743f0cd8b528c026e9175e22a84f639eca58ff"
Dec 20 23:20:20 tmp-node-e2e-a6c85484-cos-89-16108-534-34 dockerd[744]: time="2021-12-20T23:20:20.079012407Z" level=warning msg="reference for unknown type: " digest="sha256:4b036e8844920336fa48f36edeb7d4398f426d6a934ba022848deed2edbf09aa" remote="k8s.gcr.io/nvidia-gpu-device-plugin@sha256:4b036e8844920336fa48f36edeb7d4398f426d6a934ba022848deed2edbf09aa"
```

**Comment by SergeyKanzhelev** [comment]
/triage accepted

/assign @dragoncell

@Dragoncell can you please follow up with @vteratipally on this?

**Comment by vteratipally** [comment]
Compared the changelog, there are no changes in the kubernetes/node-problem-detector on the failure date.

**Comment by vteratipally** [comment]
I suspect this issue might be from the k8s-staging image. @SergeyKanzhelev let me know if there is any one that could take a look at this related to the image used in infra.

**Comment by vteratipally** [comment]
The following are my theories 

* there must be some change in the ssh secret keys that is resulting in the unexpected commit digest
* Image [cos-89](https://cloud.google.com/container-optimized-os/docs/release-notes/m89#cos-89-16108-534-27) has some changes related to manifest pulling in docker and containerd.
* k8s-staging image - issue.

**Comment by SergeyKanzhelev** [comment]
/reopen

still failing

**Comment by SergeyKanzhelev** [comment]
the test is green now. There was the recent PR from @vteratipally that fixed it
