### ISSUE TITLE
Remove or parameterize google.com from test cases

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#107078]
### What happened?

We added pinging google.com to the original E2Es, however in airgapped environments, these tests fail for obvious reasons:

```
Get http://google.com: dial tcp: lookup google.com on 192.48.0.10:53: server misbehaving
```

- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/hybrid_network.go 
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/networking.go
- https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns.go

In general, we need to parameterize this if possible.

### What did you expect to happen?

Running the `sig-network` or `sig-windows` tests should pass in air-gapped environments, especially those that dont explicitly declare external connectivity.  
For example:

```

[sig-network] Networking Granular Checks: Services 
  should function for client IP based session affinity: udp [LinuxOnly]
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:283
[BeforeEach] [sig-network] Networking
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:178
STEP: Creating a kubernetes client
Dec 15 06:29:14.990: INFO: >>> kubeConfig: /tmp/kubeconfig-609614051
STEP: Building a namespace api object, basename nettest
STEP: Binding the e2e-test-privileged-psp PodSecurityPolicy to the default service account in nettest-7422
STEP: Waiting for a default service account to be provisioned in namespace
[BeforeEach] [sig-network] Networking
  /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/network/networking.go:94
STEP: Executing a successful http request from the external internet
Dec 15 06:29:19.125: FAIL: Unable to connect/talk to the internet: Get http://google.com: dial tcp: lookup google.com on 192.48.0.10:53: server misbehaving
```

### How can we reproduce it (as minimally and precisely as possible)?

Run the `sig-network` test suites inside of a kuberentes cluster which has no internet connection.

```
sonobuoy run --e2e-focus=“sig-network” --e2e-skip="Distruptive|Slow|ExternalLoadBalancer"
```

### Anything else we need to know?

pointing finger at @rrati :)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jayunit100** [comment]
some of these were recently removed by @andrewsykim :) but some more to remove i think

**Comment by aojea** [comment]
They should have the corresponding tags so they can be filtered

**Comment by NikhilSharmaWe** [comment]
@jayunit100 and @aojea do we need to add a parameter in [this](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/windows/hybrid_network.go#L52) function as link string and replace `www.google.com` from link. 

If not what are we trying to achieve here, I would like to collaborate.

**Comment by aojea** [comment]
independent test cases `ginkgo.It` with their own feature tags as in
https://github.com/kubernetes/kubernetes/blob/489fb9bee3f626b3eeb120a5af89ad8c2b2f1c20/test/e2e/network/networking.go#L83-L97
