### ISSUE TITLE
NetworkPolicySpec field doc is outdated

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#107008]
### What happened?

I tried to understand exactly what NetworkPolicy objects mean, and got lost/confused.  https://groups.google.com/g/kubernetes-sig-network/c/6k1A8l5uxLY

For example, the comments on the `PolicyTypes` field does not precisely specify semantics, and the comments on the `Ingress` and `Egress` fields omit the significance of the `PolicyTypes` field.

### What did you expect to happen?

I expected to find clear answers.

### How can we reproduce it (as minimally and precisely as possible)?

Try to figure out from the comments in `types.go` exactly how the `PolicyType` field of a `NetworkPolicySpec` interacts with the `Ingress` and `Egress` fields.

### Kubernetes version

<details>

The comments have been deficient since egress filtering was introduced, many releases ago.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by khenidak** [comment]
@jayunit100 can you take a look at this one?
