### ISSUE TITLE
Regression in JSON logging throughput

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#107033]
### What happened?

When working on https://github.com/kubernetes/kubernetes/issues/107029 I have found a regression in JSON logging format that happend in 1.23.

In v1.23 JSON logging introduced two new features, log stream splitting and info log buffering. When I started measuring throughput it looked very promising, for example for info logs showed 10x improvement when using JSON split stream and 100Mi info log buffer. However when I introduced mixed logs (ever X info logs write 1 error logs), I noticed a large regression. For 10% of error logs written (apiserver during upgrade can write even 30% errors), I have found that just switching json on, results in log throughput being reduced from 25 MiB/s to 0.7MiB. 

I have bisected git repo and found that https://github.com/kubernetes/kubernetes/commit/b22263d8351e873961aeff5d065faf3443de9acb was the root cause.
I expect that this regression would be noticed if we run scalability tests with JSON enabled.

Loader code: https://github.com/kubernetes/kubernetes/pull/107032

/wg structured-logging
/cc @pohly
/sig scalability

### What did you expect to happen?

JSON should generate similar or greater log throughput when compared to text format.

### How can we reproduce it (as minimally and precisely as possible)?

Run loader as described in README.md from https://github.com/kubernetes/kubernetes/pull/107032

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by pohly** [comment]
So to reproduce the regression, I need to do `go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=json 1>/tmp/stdout.out 2>/tmp/stderr.out` (default for error rate is 10%, 300 for message length, 10s duration) for old and new code, right?

**Comment by serathius** [comment]
Yes, let me give my results.

Before text: 30.7MiB/s, json:39.6MiB/s
```
kubernetes $ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=text  1>/tmp/stdout.out 2> /tmp/stderr.out && du  /tmp/*.out
315072  /tmp/stderr.out
0       /tmp/stdout.out
kubernetes $ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=json 1>/tmp/stdout.out 2> /tmp/stderr.out && du  /tmp/*.out
0       /tmp/stderr.out
405592  /tmp/stdout.out
```

After, text: 30.6MiB/s, json: 6.5MiB/s
```
kubernetes $ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=text 1>/tmp/stdout.out 2> /tmp/stderr.out && du  /tmp/*.out
313672  /tmp/stderr.out
0       /tmp/stdout.out
kubernetes $ go run ./staging/src/k8s.io/component-base/logs/loader/cmd/logger.go --logging-format=json 1>/tmp/stdout.out 2> /tmp/stderr.out && du  /tmp/*.out
0       /tmp/stderr.out
67124   /tmp/stdout.out
```

**Comment by aojea** [comment]
> After discussion on the #release-management Slack channel [1], we decided to cut Kubernetes 1.23.1 patch release on Thursday, December 16.

should we try to get this in 1.23.1?

**Comment by serathius** [comment]
@aojea Yes, we just moved JSON and Structured Logging to Beta in v1.23. This bug should cause performance issues when there is non trivial amount of errors (>1%) written by control plane. I expect that this has really bad impact on upgrades which I have seen can reach 30% of error logs from apiserver.

**Comment by pohly** [comment]
It's worth pointing out that this regression only occurs when writing to a disk-based file (see https://github.com/kubernetes/kubernetes/pull/107032#issuecomment-995933422).

That also provides a very likely explanation for the huge performance difference: I bet zap not only flushes its buffered info messages, it also syncs the file. That is fast for tmpfs, but slow for real disks.

**Comment by pohly** [comment]
@serathius: do you know how the Kubernetes components are run in those cases where logging performance matters? Do they directly write to a real disk or does it all go through pipes? If it is the latter, then this issue matters a lot less in practice.

@dims: you mention at some point that you had scalability issues with logging that went away when using go-runner as wrapper instead of using klog's internal output redirection. I bet the root cause is the same: fast vs. slow sync of the output fd.

I don't know how realistic the scalability setup was, but it must have written log files to some real disk.
