### ISSUE TITLE
Tests on sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial are failing

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107062]
### Which jobs are failing?

sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Which tests are failing?

```
E2eNode Suite.[sig-node] Density [Serial] [Slow] create a batch of pods latency/resource should be within limit when create 10 pods with 0s intervalE2eNode Suite.[sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background podsE2eNode Suite.[sig-node] LocalStorageCapacityIsolationQuotaMonitoring [Slow] [Serial] [Disruptive] [Feature:LocalStorageCapacityIsolationQuota][NodeFeature:LSCIQuotaMonitoring] when we run containers that should cause use quotas for LSCI monitoring (quotas enabled: false) should eventually evict all of the correct podsE2eNode Suite.[sig-node] Resource-usage [Serial] [Slow] regular resource usage tracking resource tracking for 10 pods per nodeE2eNode Suite.[sig-node] Restart [Serial] [Slow] [Disruptive] Container Runtime Network should recover from ip leak
```

### Since when has it been failing?

11/30, maybe earlier

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Relevant SIG(s)

/sig node
/priority important-soon

**Comment by pacoxu** [comment]
```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/eviction_test.go:511
Unexpected error:
    <*exec.ExitError | 0xc00119d880>: {
        ProcessState: {
            pid: 168088,
            status: 256,
            rusage: {
                Utime: {Sec: 0, Usec: 2143},
                Stime: {Sec: 0, Usec: 7040},
                Maxrss: 162660,
                Ixrss: 0,
                Idrss: 0,
                Isrss: 0,
                Minflt: 485,
                Majflt: 0,
                Nswap: 0,
                Inblock: 0,
                Oublock: 0,
                Msgsnd: 0,
                Msgrcv: 0,
                Nsignals: 0,
                Nvcsw: 6,
                Nivcsw: 1,
            },
        },
        Stderr: nil,
    }
    exit status 1
occurred
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/util.go:477
```

The failure is caused by the `reduceAllocatableMemoryUsage` execution error.

https://github.com/kubernetes/kubernetes/blob/522c1be4c17a6b40c5687f5323876a477cb0b100/test/e2e_node/util.go#L471-L478

**Comment by pacoxu** [comment]
In cgroup v1,  memory.force_empty can trigger forced page reclaim

```
 memory.force_empty		 # trigger forced page reclaim
```
I am not sure which is the suggested way to force reclaim page in group v2. I open a PR to skip this logic once cgroup v2 is detected.

**Comment by SergeyKanzhelev** [comment]
/reopen

The test is still failing. @pacoxu can I assign it to you to take a look (feel free to un-assign).

/assign @pacoxu

**Comment by pacoxu** [comment]
OK. Let me take a look.

At my first glance, I find cadvisor logged an error: cgroup v2 is not detected successfully. I will check if there are other errors.
```
W1220 18:06:44.627714    1537 manager.go:159] Cannot detect current cgroup on cgroup v2
```

**Comment by SergeyKanzhelev** [comment]
@pacoxu do you want to keep working on this? Can I assign the bug to you?

**Comment by bobbypage** [comment]
I believe this is due to the test running a cAdvisor pod which does not support cgroupv2. I think  https://github.com/kubernetes/kubernetes/pull/106287 aims to address it

**Comment by pacoxu** [comment]
So I will wait for the #106287 merging and see if this is fixed.

**Comment by bobbypage** [comment]
#106287 merged but the density tests are still failing.

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1480600612373532672

The error is different now:

```
_output/local/go/src/k8s.io/kubernetes/test/e2e_node/resource_usage_test.go:86
Unexpected error:
    <*errors.errorString | 0xc00047c400>: {
        s: "No resource usage data for runtime container ()",
    }
    No resource usage data for runtime container ()
```

It appears the test is for some reason unable to collect resource data for runtime (containerd) container - https://github.com/kubernetes/kubernetes/blob/3cec1d1a13a7414ed5413d75898a167220c3892c/test/e2e_node/resource_collector.go#L97

**Comment by bobbypage** [comment]
The issue *might* be that `--container-runtime-process-name=/usr/bin/containerd`, but the test installs a custom version of containerd to which runs under `/home/containerd/usr/local/bin/containerd`, so `getPidsForProcess` is unable to find it https://github.com/kubernetes/kubernetes/blob/3cec1d1a13a7414ed5413d75898a167220c3892c/test/e2e_node/resource_collector.go#L479

**Comment by SergeyKanzhelev** [comment]
> > The issue _might_ be that `--container-runtime-process-name=/usr/bin/containerd`, but the test installs a custom version of containerd which runs under `/home/containerd/usr/local/bin/containerd`, so `getPidsForProcess` is unable to find it
> 
> @bobbypage @SergeyKanzhelev why not use `--container-runtime-process-name=containerd` instead. The default value of --container-runtime-process-name is dockerd.

Should we replace it across all tests to use just a `containerd`? Is there any reason to keep longer path at all?

**Comment by SergeyKanzhelev** [comment]
/reopen

still failing even after the last PR fixing the containerd name

**Comment by SergeyKanzhelev** [comment]
It's green now. Yay!

**Comment by bobbypage** [comment]
Awesome, thank you!
