### ISSUE TITLE
Re-introduce kubectl --dry-run default value and boolean values

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/kubernetes#107002]
For 1.23, we removed the kubectl --dry-run default value (--dry-run="") and boolean values (--dry-run=true|false), requiring users to specify --dry-run=client or --dry-run=server due to a deprecation. This is a required action for users who upgrade kubectl. This change was made in https://github.com/kubernetes/kubernetes/pull/105327.

After reconsideration, this change is not worth the churn for users. It's likely that many users rely on these values for automated and manual use cases. Users will likely update usage to --dry-run=client. Ideally, we can rollback https://github.com/kubernetes/kubernetes/pull/105327 and re-introduce these values for the next patch release.

/sig cli
/area kubectl

**Comment by liggitt** [comment]
fixed in 1.23.1
