### ISSUE TITLE
Tests sig-node-cos#e2e-cos-alpha-features wouldn't start

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107068]
### Which jobs are failing?

e2e-cos-alpha-features

### Which tests are failing?

All

### Since when has it been failing?

I'm not sure it was ever running.

### Testgrid link

https://testgrid.k8s.io/sig-node-cos#e2e-cos-alpha-features

### Relevant SIG(s)

/sig node
/priority important-longterm

since it's alpha features, setting priority lower

**Comment by pacoxu** [comment]
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-alpha-features/1466339771365199872/artifacts/bootstrap-e2e-master/kubelet.log
kubelet log shows error below:

> W1202 09:38:24.433557    2272 plugins.go:114] WARNING: "gce" built-in cloud provider is now disabled. Please reach to sig-cloud-provider and use 'external' cloud provider for "gce": The GCE provider is deprecated and will be removed in a future release. Please use https://github.com/kubernetes/cloud-provider-gcp
> E1202 09:38:24.433627    2272 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: failed to create kubelet: cloud provider \"gce\" was specified, but built-in cloud providers are disabled. Please set --cloud-provider=external and migrate to an external cloud provider"
> kubelet.service: Main process exited, code=exited, status=1/FAILURE
> kubelet.service: Failed with result 'exit-code'.
> kubelet.service: Consumed 89ms CPU time
> kubelet.service: Service RestartSec=10s expired, scheduling restart.
> kubelet.service: Scheduled restart job, restart counter is at 4.
> Stopped Kubernetes kubelet.

**Comment by pacoxu** [comment]
We tried to fix it in #102300 before. I opened https://github.com/kubernetes/test-infra/pull/24696.
