### ISSUE TITLE
CSR no longer supports "kubernetes.io/legacy-unknown"?

### ISSUE THREAD

**Issue by arrowfeng** [kubernetes/kubernetes#107020]
### What happened?

After I upgraded my cluster to 1.22 recently, I found that my virtual kubelet created a csr request, which could not be automatically approve, manually approve in time, and could not be issued because the signName is kubernetes.io/legacy-unknown, why should I do it myself What about issuing certificates? It is because virtual kubelet may also need to use additional permissions, such as update pod and so on. Is there any way to issue a certificate in such a scenario?

### What did you expect to happen?

csr support "kubernetes.io/legacy-unknown".

### How can we reproduce it (as minimally and precisely as possible)?

.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
# paste output here
```

</details>

### Cloud provider

<details>
none
</details>

**Comment by arrowfeng** [comment]
I used virtual kubelet before, but it was not easy to issue a certificate in version 1.22. How to issue a certificate in such a scenario?

**Comment by pacoxu** [comment]
/sig auth
Similar issue with answer in https://github.com/kubernetes/kubernetes/issues/99504#issuecomment-787114686.

**Comment by arrowfeng** [comment]
think you!
