### ISSUE TITLE
kubelet stats API 404

### ISSUE THREAD

**Issue by vsxen** [kubernetes/kubernetes#107010]
### What happened?

kubelet stats server reruen 404
```
curl  --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key -k https://localhost:10250/stats
<a href="/stats/">Moved Permanently</a>.

curl  --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key -k https://localhost:10250/stats/ && echo
404: Page Not Found
```

### What did you expect to happen?

curl  --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt --key /etc/kubernetes/pki/apiserver-kubelet-client.key -k https://localhost:10250/stats/

return stats info

### How can we reproduce it (as minimally and precisely as possible)?

```
kubeadm init  --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers --apiserver-advertise-address 192.168.2.2 --pod-network-cidr=10.244.0.0/16 --service-cidr=10.96.0.0/24 --kubernetes-version 1.21.1
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
kubectl version --short
Client Version: v1.21.1
Server Version: v1.21.1

also with 1.20.8
</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
/sig node

**Comment by pacoxu** [comment]
Do you mean `/stats/summary`?

**Comment by vsxen** [comment]
https://github.com/kubernetes/kubernetes/commit/cd54bd94e90dbf10a7e4f8a85a26cd036d589c57

I think stats API is the data source of `kubectl top no`

But I find `summary` API is enough.

https://github.com/kubernetes-sigs/metrics-server/blob/d253d4fc24/pkg/scraper/client.go#L97-L101
