### ISSUE TITLE
Prevent performance regressions for JSON logging format

### ISSUE THREAD

**Issue by serathius** [kubernetes/kubernetes#107049]
I would want to discuss potential ways that we can avoid issues like https://github.com/kubernetes/kubernetes/pull/107035

Ideas:
* Run periodic scalability tests with JSON logging enabled
* Collect and agree upon set of logging performance metrics that should be verified before release (for example https://github.com/kubernetes/kubernetes/issues/107029)

I would want to start the discussion so we have some plan for v1.24 release.
/wg structured-logging
/sig instrumentation
/sig scalability

**Comment by dgrisonnet** [comment]
Closing since this issue doesn't seem to be tracked anymore. Feel free to reopen if necessary.

/close

**Comment by dgrisonnet** [comment]
cc @mengjiao-liu @pohly 

I don't know if there are any plan in the future for this.
