### ISSUE TITLE
Complete winkernel proxier ut

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#107026]
### What happened?

Similar to [#61390](https://github.com/kubernetes/kubernetes/issues/61390) in winkernel proxy mode, most service functions like "nodeport/loadbalance" is similiar to proxy mode iptables/ipvs, yet most winkernel proxier ut only verified very few normal function, which can't ensure  all kinds of services are functional. 

### What did you expect to happen?

complete winkernel ut.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

Any

### Cloud provider

Any

### OS version

Any

### Install tools

None

### Container runtime (CRI) and and version (if applicable)

None

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None

**Comment by yanghesong** [comment]
I am willing to troubleshoot this problem.

**Comment by jayunit100** [comment]
were working on new service loadbalancers tests which are more comprehensive https://github.com/K8sbykeshed/k8s-service-lb-validator , which we'd like to donate to sig-network eventually.  Do you want to add some of your examples there ?
