### ISSUE TITLE
Top flake: TestCronJobLaunchesPodAndCleansUp 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#107198]
##### Error text:
```
=== RUN   TestCronJobLaunchesPodAndCleansUp
I1222 07:55:48.781583  118818 apf_controller.go:218] NewTestableController "Controller" with serverConcurrencyLimit=600, requestWaitLimit=15s, name=Controller, asFieldManager="api-priority-and-fairness-config-consumer-v1"
I1222 07:55:48.781668  118818 apf_controller.go:769] No exempt PriorityLevelConfiguration found, imagining one
I1222 07:55:48.781682  118818 apf_controller.go:769] No catch-all PriorityLevelConfiguration found, imagining one
W1222 07:55:48.781748  118818 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W1222 07:55:48.781783  118818 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I1222 07:55:48.781840  118818 services.go:51] Setting service IP to "10.0.0.1" (read-write).
I1222 07:55:48.781882  118818 instance.go:318] Node port range unspecified. Defaulting to 30000-32767.
I1222 07:55:48.781893  118818 instance.go:274] Using reconciler: 
I1222 07:55:48.783527  118818 instance.go:382] Could not construct pre-rendered responses for ServiceAccountIssuerDiscovery endpoints. Endpoints will not be enabled. Error: empty issuer URL
I1222 07:55:48.783705  118818 storage_factory.go:285] storing podtemplates in v1, reading as __internal from storagebackend.Config{Type:"", Prefix:"5fa6b0a5-fa6a-491c-b84b-79c4aa02c064", Transport:storagebackend.TransportConfig{ServerList:[]string{"http://127.0.0.1:2379"}, KeyFile:"", CertFile:"", TrustedCAFile:""
```

> E1223 01:12:00.153488  118776 job_controller.go:488] syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again
>    cronjob_test.go:159: Failed with error: syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again

#### Recent failures:
[2021/12/22 下午3:34:22 ci-kubernetes-integration-1-23](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-23/1473557044576391168)

/kind flake
/sig apps

**Comment by pacoxu** [comment]
The flake started after #104799 was merged.

**Comment by RyanAoh** [comment]
> E1223 01:12:00.153488 118776 job_controller.go:488] syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again
> cronjob_test.go:159: Failed with error: syncing job: tracking status: adding uncounted pods to status: Operation cannot be fulfilled on jobs.batch "foo-27337032": the object has been modified; please apply your changes to the latest version and try again

I wonder if this error was expected or unavoidable.

**Comment by pacoxu** [comment]
Not quite sure as I have no context about it.

According to the code below, this may be intended. 
https://github.com/kubernetes/kubernetes/blob/3f0a634ef78b6df33075e54b0f89e465e88049c4/pkg/controller/job/job_controller.go#L488-L494

/cc @soltysh @alculquicondor  @alaypatel07
Some experts around cronjob/job.(However, they are probably on vacation now.)

**Comment by alculquicondor** [comment]
cc @ahg-g who looked into #104799

**Comment by alculquicondor** [comment]
> I wonder if this error was expected or unavoidable.

In general, conflict errors are acceptable. The controller should keep retrying, as Paco pointed out.

**Comment by liggitt** [comment]
seen again in https://github.com/kubernetes/kubernetes/pull/106242

**Comment by pacoxu** [comment]
/triage accepted

> it looks like #104799 was immediately picked to release branches as well, and we're seeing integration test failures there as well

This needs to be fixed in release branch as well.

**Comment by ahg-g** [comment]
Is the flake fixed now?

> > I wonder if this error was expected or unavoidable.
> 
> In general, conflict errors are acceptable. The controller should keep retrying, as Paco pointed out.

I discussed this with @soltysh over chat before the holidays, ideally we should try to create a patch for the update. Currently cronjob doesn't retry updates at all.

**Comment by alculquicondor** [comment]
> ideally we should try to create a patch for the update. Currently cronjob doesn't retry updates at all too.

Actually, it's safer to discard the update and retry the whole sync, in the case of conflict. Basically, something changed and the controller can no longer be confident of the calculations done in the current sync. Although this was specially true for the job_controller, where the status is used as input.

> Is the flake fixed now?

The cherry-picks are up for review (linked in #107200)

**Comment by ahg-g** [comment]
ok, make sense.

btw, I noticed in the new cronjob controller that we may update the status of the same cronjob more than once in the same sync cycle, also it seems that there are code paths that may lead to issuing status updates when there was no change at all. I think it is worth looking at that controller again to see if those cases are actually true and can be optimized.

**Comment by ahg-g** [comment]
created https://github.com/kubernetes/kubernetes/issues/107411

**Comment by pacoxu** [comment]
> [2021/12/22 下午3:34:22 ci-kubernetes-integration-1-23](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-23/1473557044576391168)

According to https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-1-23, we can close this.
/close
