### ISSUE TITLE
goroutine leak caused by channel examplePlugin.registrationStatus

### ISSUE THREAD

**Issue by songlh** [kubernetes/kubernetes#107193]
### What happened?

There is no receive or close operation on channel `registrationStatus` of struct `examplePlugin` ([line 86](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pluginmanager/pluginwatcher/example_plugin.go#L86)) . 

Thus, a goroutine leak happens when `func (e *examplePlugin) NotifyRegistrationStatus(ctx context.Context, status *registerapi.RegistrationStatus)` is executed ([line 107](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pluginmanager/pluginwatcher/example_plugin.go#L107)), such as when running `Test_Run_Positive_Register`.

### What did you expect to happen?

no goroutine leak

### How can we reproduce it (as minimally and precisely as possible)?

run Test_Run_Positive_Register()

### Kubernetes version

<details>
97d40890d00acf721ecabb8c9a6fec3b3234b74b and following versions

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cyclinder** [comment]
/area kubelet
/assign
I'd try to fix it

**Comment by cyclinder** [comment]
The author has submitted a PR for this issue: https://github.com/kubernetes/kubernetes/pull/107196
