### ISSUE TITLE
Error from server: error dialing backend: dial tcp [ip]:10250: i/o timeout when running kubectl exec -it ..

### ISSUE THREAD

**Issue by CzarMich** [kubernetes/kubernetes#107186]
### What happened?

I am running a 3 node cluster with one acting as a master. 
All joined the cluster and pods are running .
However, accessing a pod always produces a. timeout error.
I have for instance postgres pod running. But accessing it is not possible as I keep getting time outs

kubectl exec -it  postgres-775bfc9fb6-fnnt4 -- psql -h 10.244.1.3 -U admin --password -p 5432 postgres

Output:  
Error from server: error dialing backend: dial tcp 10.0.3.123:10250: i/o timeout

I have tried to change my security groups and also allow ports on open stack where the nodes are created, but still I have not succeeded in solving this issue. 
 

### What did you expect to happen?

I expected a prompt to enter password for the password.

### How can we reproduce it (as minimally and precisely as possible)?

kubectl exec -it

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Running on Opensatck

### OS version

# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
#Linux hostname 5.4.0-64-generic #72-Ubuntu SMP Fri Jan 15 10:27:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neolit123** [comment]
please try the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support

**Comment by khatrig** [comment]
@CzarMich, Were you able to get around this issue?

**Comment by CzarMich** [comment]
> @CzarMich, Were you able to get around this issue?

Hi, yes, I was able to solve this. I had a proxy issue.

**Comment by marcin-ops** [comment]
I have probably the same problem as you

When I prompt
**Kubectl exec -it [pod] bash**
_Receives:  Error from server: error dialing backend: dial timeout, backstop_

how do you fix this problem ?

**Comment by Lisss29** [comment]
I have the same problem with exec -it pod --bash

Any suggest to fix it?

Kube version: v1.22.1

**Comment by marcin-ops** [comment]
I solved this problem, and I will share this solution here
Kubectl exec -it [pod] bash
Receives: Error from server: error dialing backend: dial timeout, backstop

requires traffic on TCP port 8132 to endpoint API cluster of kubernetes

**Comment by tommygood** [comment]
open 10250 port of firewall on that [ip] node

**Comment by DPH07** [comment]
> I solved this problem, and I will share this solution here Kubectl exec -it [pod] bash Receives: Error from server: error dialing backend: dial timeout, backstop
> 
> requires traffic on TCP port 8132 to endpoint API cluster of kubernetes



Thank you for this, i was stuck with the same problem as you. with this soultion, im able to solve it. :)
