### ISSUE TITLE
kube-controller-manager leader node shutdown, node status change slowly 

### ISSUE THREAD

**Issue by zerols** [kubernetes/kubernetes#107100]
### What happened?

Another master node become a new leader of kube-controller-manager and start controllers like attachdetach ... 
but i have found start the controllers one of them wolud spend long time than others , one of them will be 30s longer than the others, like this： 

```
I1217 07:43:04.354500       1 leaderelection.go:253] successfully acquired lease kube-system/kube-controller-manager
I1217 07:43:04.517069       1 shared_informer.go:240] Waiting for caches to sync for tokens
I1217 07:43:04.517277       1 reflector.go:219] Starting reflector *v1.Secret (15h42m48.239775582s) from k8s.io/client-go/informers/factory.go:134
I1217 07:43:04.517280       1 reflector.go:219] Starting reflector *v1.ServiceAccount (15h42m48.239775582s) from k8s.io/client-go/informers/factory.go:134
I1217 07:43:04.551760       1 controllermanager.go:559] Starting "nodeipam"
I1217 07:43:04.638826       1 node_ipam_controller.go:91] Sending events to api server.
I1217 07:43:04.717942       1 shared_informer.go:247] Caches are synced for tokens
I1217 07:43:14.687847       1 range_allocator.go:82] Sending events to api server.
I1217 07:43:14.688178       1 range_allocator.go:116] No Secondary Service CIDR provided. Skipping filtering out secondary service addresses.
I1217 07:43:14.688246       1 controllermanager.go:574] Started "nodeipam"
I1217 07:43:14.688259       1 controllermanager.go:559] Starting "pv-protection"
I1217 07:43:14.688307       1 node_ipam_controller.go:154] Starting ipam controller
I1217 07:43:14.688339       1 shared_informer.go:240] Waiting for caches to sync for node
I1217 07:43:14.691359       1 controllermanager.go:574] Started "pv-protection"
I1217 07:43:14.691375       1 controllermanager.go:559] Starting "endpointslicemirroring"
I1217 07:43:14.691441       1 pv_protection_controller.go:83] Starting PV protection controller
```
```
I1217 07:50:21.610403       1 garbagecollector.go:522] object garbagecollector.objectReference{OwnerReference:v1.OwnerReference{APIVersion:"v1", Kind:"Pod", Name:"kube-scheduler-node222", UID:"cef92184-2830-41a3-a359-fedbc0cc6405", Controller:(*bool)(nil), BlockOwnerDeletion:(*bool)(nil)}, Namespace:"kube-system"} has at least one existing owner: []v1.OwnerReference{v1.OwnerReference{APIVersion:"v1", Kind:"Node", Name:"node222", UID:"5ed7bc60-f4f5-4409-a621-d01b8424d83d", Controller:(*bool)(0xc003264c02), BlockOwnerDeletion:(*bool)(nil)}}, will not garbage collect
I1217 07:50:35.613108       1 event.go:291] "Event occurred" object="kube-system/data-new-release-etcd-0" kind="PersistentVolumeClaim" apiVersion="v1" type="Normal" reason="FailedBinding" message="no persistent volumes available for this claim and no storage class is set"

```

my question: 
- shutdown one of k8s master ( not etcd leader、kube-controller-manager leader)
- shutdown kube-controller-manager leader
other master kubectl get node , should i get the same time ready to notready ? If different ，where is the main time spent? 
The conclusion of my test： 
- Election time
- start controllers  time  10s 
- garbagecollector.go   15s 

### What did you expect to happen?

Is this 30s necessary or can be configured through some parameters ? 

### How can we reproduce it (as minimally and precisely as possible)?

three master node and poweroff the leader of kube-controller-manager。 

### Kubernetes version

<details>

```console
$ kubectl version v1.21.0 adn v1.21.3
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

# paste output here
$ uname -a
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
For nodeipam in `pkg/controller`, I can only find two 10 seconds. But I'm not sure which takes effects or another params.
```
pkg/controller/nodeipam/node_ipam_controller.go:
  44  	// given in the error state.
  45: 	ipamMaxBackoff = 10 * time.Second
  46  	// ipamInitialRetry is the initial retry interval for retrying synchronization of a

pkg/controller/nodeipam/ipam/cidr_allocator.go:
  80  // This is a variable instead of a const to enable testing.
  81: var nodePollInterval = 10 * time.Second
```

**Comment by zerols** [comment]
> For nodeipam in `pkg/controller`, I can only find two 10 seconds. But I'm not sure which takes effects or another params.
> 
> ```
> pkg/controller/nodeipam/node_ipam_controller.go:
>   44  	// given in the error state.
>   45: 	ipamMaxBackoff = 10 * time.Second
>   46  	// ipamInitialRetry is the initial retry interval for retrying synchronization of a
> 
> pkg/controller/nodeipam/ipam/cidr_allocator.go:
>   80  // This is a variable instead of a const to enable testing.
>   81: var nodePollInterval = 10 * time.Second
> ```
> 
> Some 10s in kube-controller-manager startup flags that you may try. `--leader-elect-renew-deadline` is a `suspect`.
> 
> ```
> [root@daocloud ~]# nerdctl exec -it  --namespace  k8s.io 3c32e6b3c264 kube-controller-manager --help | grep 10s
>       --leader-elect-renew-deadline duration     The interval between attempts by the acting master to renew a leadership slot before it stops leading. This must be less than or equal to the lease duration. This is only applicable if leader election is enabled. (default 10s)
>       --route-reconciliation-period duration     The period for reconciling routes created for Nodes by cloud provider. (default 10s)
>       --authentication-token-webhook-cache-ttl duration   The duration to cache responses from the webhook token authenticator. (default 10s)
>       --authorization-webhook-cache-authorized-ttl duration     The duration to cache 'authorized' responses from the webhook authorizer. (default 10s)
>       --authorization-webhook-cache-unauthorized-ttl duration   The duration to cache 'unauthorized' responses from the webhook authorizer. (default 10s)
> ```

Forgot to mention the kube-controller-manager configuration：
    - --leader-elect-lease-duration=4s
    - --leader-elect-renew-deadline=3s
node_ipam_controller start after the election  
node_ipam_controller.go Does the first 10s correspond to kube-controller-manager
one of the parameters can be modified through configuration

**Comment by pacoxu** [comment]
I'm afraid not. 
If you want to do some further testing, you can edit the code and build a `kube-controller-manager` bin or image to test.

**Comment by neolit123** [comment]
adding sig label
/sig api-machinery
/kind feature

**Comment by fedebongio** [comment]
/assign @jiahuif 
Jared would you mind taking a look? thanks!
/triage accepted
