### ISSUE TITLE
flexVolume: waitForAttach should add check for devicepath

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#107184]
### What happened?

It seems in flexVolume mode ,  in the implement of WaitForAttach , just as follows:
https://github.com/kubernetes/kubernetes/blob/ca0c8275b41cf542f9334073fc8660fb349f9605/pkg/volume/flexvolume/attacher.go#L53-L65
when call not support  waitForAttachCmd, WaitForAttach call (*attacherDefaults)(a).WaitForAttach(spec, devicePath, timeout) directly return devicePath,  there is no additional check for devicePath , it may brings some unexpected results.
https://github.com/kubernetes/kubernetes/blob/ca0c8275b41cf542f9334073fc8660fb349f9605/pkg/volume/flexvolume/attacher-defaults.go#L37-L41

### What did you expect to happen?

add suitable check when call not support attachcmd.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

None

### Kubernetes version

None

### Cloud provider

None

### OS version

None

### Install tools

None

### Container runtime (CRI) and and version (if applicable)

None

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None

**Comment by NikhilSharmaWe** [comment]
@b0b0haha Can we add condition like in [this](https://github.com/kubernetes/kubernetes/blob/ca0c8275b41cf542f9334073fc8660fb349f9605/pkg/volume/flexvolume/attacher-defaults.go#L53) case.

**Comment by NikhilSharmaWe** [comment]
@xing-yang Could you please give your thoughts on this issue. If it is a reasonable issue then I can start to work on this.

**Comment by NikhilSharmaWe** [comment]
@jsafrane could you please have a look on this issue. If it is a reasonable issue, then I can start to work on it.

**Comment by b0b0haha** [comment]
> @b0b0haha Can we add condition to err similar to what like in [this](https://github.com/kubernetes/kubernetes/blob/ca0c8275b41cf542f9334073fc8660fb349f9605/pkg/volume/flexvolume/attacher-defaults.go#L49) case and `return "", err` in case of err != nil and `return devicePath, nil` otherwise.

Thanks for your help! I found this bug because it's inconsistent with other cloud provider plugins's implement. But I'm not familiar with the implement of flexvolume, so I can't ensure the fix is correct and suitable.

**Comment by jsafrane** [comment]
I don't think it's a bug. `WaitForAttach` should wait until a volume gets attached and actually appears as a device on a node. But `devicePath` parameter is optional. Not all clouds know path to a device at `Attach()` call and it does not even need to be a path to a device (e.g. CSI volume plugin uses it quite differently). Hence the default `WaitForAttach` cannot do anything useful.
