### ISSUE TITLE
Use more specialized types than strings in internal API's where sensible

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#10710]
I've seen a variety of bugs stemming from the use of strings as types in internal API's where more specialized types could have been more appropriate, and enabled our compiler rather than our users to pick up programming errors.

https://github.com/GoogleCloudPlatform/kubernetes/pull/10699 is one particular example, where node names and host names got confused, as they are both passed around as strings.  I have seen several other similar bugs which were picked up at much greater expense by users than if our compiler had simply errored.  Name vs namespacedName is another recurring theme.  internalName vs externalName.  The list goes on.

Lets create more specilized types for these and plumb them throughout the system.

More specific sub-issues still TBD - creating this placeholder in the mean time so that it gets done.

**Comment by thockin** [comment]
I can not agree more. I am a huge fan of this, and this is one place where
Go just gets it right , IMO.

**Comment by bgrant0607** [comment]
Please add this to our coding conventions.

**Comment by kargakis** [comment]
@kubernetes/sig-api-machinery-misc

**Comment by thockin** [comment]
This is a good opportunity for someone to score some cleanup points.  I expect this could be a series of relatively simple PRs that incrementally make life better.

Also can apply to ints and other fields where semantics are intrinsic to the content of the field (e.g. UnixUID was done).

**Comment by deads2k** [comment]
@liggitt @smarterclayton are type changes going to do anything funky with protobuf?

**Comment by liggitt** [comment]
> @liggitt @smarterclayton are type changes going to do anything funky with protobuf?

a type alias shouldn't. only the tag name and bytes hit the wire. the type info is part of the schema you bring to the encoder/decoder

**Comment by smarterclayton** [comment]
I will note that query decoding / encoding doesn't support custom types yet
(I tried to use types.UID in a precondition).  Proto should be ok.

**Comment by ebbeelsborg** [comment]
@thockin I'm interested in working on this and I see that help is wanted. I'd be happy to start hacking away at some minimalistic PRs fixing one small thing at a time, but perhaps it would prudent to first break this issue down into numerous small, concrete tasks that can then be prioritized/parallelized. Any thoughts/opinions on which approach/process is desired here?

It would also be nice to side-step any (currently) inherent caveats, for instance related to encoding/decoding so it would be brilliant with some (additional) expert advice on which things to tackle first and which to avoid for now. Also, are we going with type changes and refactoring, type aliases, or...Probably some guidelines should be set out.

**Comment by ebbeelsborg** [comment]
@thockin ping
