### ISSUE TITLE
Warning "Can't open port nodePort" on a fresh cluster setup with kubeadm

### ISSUE THREAD

**Issue by sitilge** [kubernetes/kubernetes#107170]
### What happened?

I've been following the official docs for kubeadm and how to set up a new cluster. The cluster is up and running but I noticed warning events when creating node port services:

```
can't open port "nodePort for default/abcde:5678-8080" (:31594/tcp4), skipping it
listen tcp4 :31594: bind: address already in use
```

However, the node port does work (I see the output when accessing node ip:nodeport). Might it be related to something else than Kubernetes?

### What did you expect to happen?

There is no such warning event.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a fresh cluster with kubeadm and then create a service of nodeport type.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
Hetzner cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux worker-3 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
cloud-init
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni=cilium
csi=hetzner
</details>

**Comment by aojea** [comment]
check with netstat or ss if there is a process listening on that port

```
listen tcp4 :31594: bind: address already in use
```

```
ss -pan | grep 31594
```

**Comment by sitilge** [comment]
@aojea no, I specified exact random port e.g. `nodePort: 31234` and checked it before with ss - it was not being used. Then I created the service, the warning occured, and after that the port was taken:

```
ss -pan | grep 31234
tcp  LISTEN   0    4096     0.0.0.0:31234       0.0.0.0:*   users:(("kube-proxy",pid=2576,fd=13))                                          
```

**Comment by aojea** [comment]
kube-proxy binds the NodePort to warn users that they may be shadowing a process, but it logs the errors if it can not bind the port

**Comment by tnqn** [comment]
I met the same error and I confirmed the node port was not used by any other process. 
After looking into the code, I think this is a bug in kube-proxy that it would try to open a node port twice with same (empty) IP and port when `--nodeport-addresses` is empty. `nodeAddresses` contains `IPv4ZeroCIDR` and `IPv6ZeroCIDR` in below code.:
https://github.com/kubernetes/kubernetes/blob/7846bbbda0ab921de47292b79722dc7a5420e7c8/pkg/proxy/iptables/proxier.go#L1292-L1305

I have created https://github.com/kubernetes/kubernetes/pull/107413 to fix it.

**Comment by GoingOffRoading** [comment]
> I met the same error and I confirmed the node port was not used by any other process. After looking into the code, I think this is a bug in kube-proxy that it would try to open a node port twice with same (empty) IP and port when `--nodeport-addresses` is empty. `nodeAddresses` contains `IPv4ZeroCIDR` and `IPv6ZeroCIDR` in below code.:
> 
> https://github.com/kubernetes/kubernetes/blob/7846bbbda0ab921de47292b79722dc7a5420e7c8/pkg/proxy/iptables/proxier.go#L1292-L1305
> 
> I have created #107413 to fix it.

@tnqn Awesome find.

Did you figure out a work around?

I am encountering this issue with this version of the image: k8s.gcr.io/kube-proxy:v1.23.4

**Comment by tnqn** [comment]
@GoingOffRoading The error looked scaring but the nodePort should be working, as it was just caused by a duplicate port opening attempt. v1.23.5 and later releases have the fix.
