### ISSUE TITLE
network is unreachable when communicating by localhost between docker containers in the same pod

### ISSUE THREAD

**Issue by wangchanggan** [kubernetes/kubernetes#107139]
### What happened?

i started two docker  containers(a client and a server which ran by iris https://github.com/kataras/iris) in the same pod, then the client requested the server by http.client(net/http)，but sometimes it reported "connect: network is unreachable."

for example, Get http://localhost:10010/api/nodes: dial tcp [::1]:10010: connect: network is unreachable, 10010 is server port which is listenning.

### What did you expect to happen?

i searched some info that it supports communicating by localhost between containers in the same pod, but i don't know why it occured the issue.

### How can we reproduce it (as minimally and precisely as possible)?

i can't get some useful info or log to solved it, anyone had a similar problem?

Thanks!

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
https://github.com/kubernetes-sigs/kubespray/tree/v2.12.6
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
docker 18.09
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cyclinder** [comment]
it seems to port `10010` doesn't open, are you sure this port really open?

**Comment by aojea** [comment]
/remove-kind bug
/kind support

This doesn't look like a kubernetes problem :thinking:

**Comment by jonyhy96** [comment]
may change the server to nginx to verify is it a bug of iris

**Comment by uablrek** [comment]
localhost seem to resolve to ::1 which is the ipv6 localhost. The server may however open 0.0.0.0, the ipv4 "any" address, and you would get this problem. Either open [::] in the server (works for ipv4 and ipv6 on Linux) or make sure localhost resolves to 127.0.0.0/8.

**Comment by wangchanggan** [comment]
> it seems to port `10010` doesn't open, are you sure this port really open?

yes, enter into pod by command "kebectl exec -it", 10010 port is listenning.
![111](https://user-images.githubusercontent.com/33536351/147250598-1a1bd412-7c89-4c31-b187-b3f10ed86012.png)

**Comment by wangchanggan** [comment]
> localhost seem to resolve to ::1 which is the ipv6 localhost. The server may however open 0.0.0.0, the ipv4 "any" address, and you would get this problem. Either open [::] in the server (works for ipv4 and ipv6 on Linux) or make sure localhost resolves to 127.0.0.0/8.



> may change the server to nginx to verify is it a bug of iris

It doesn't seem to be a bug of iris, because i also use iris as a web framework to expose and it works normally, but not communicating by localhost in the same pod.

**Comment by wangchanggan** [comment]
> localhost seem to resolve to ::1 which is the ipv6 localhost. The server may however open 0.0.0.0, the ipv4 "any" address, and you would get this problem. Either open [::] in the server (works for ipv4 and ipv6 on Linux) or make sure localhost resolves to 127.0.0.0/8.

It seems to be the problem that localhost is resolved to ipv6, i tried to use "hostNetwork: true" to start pod and it worked normally, and there is a tcp6 listen on 10010 by command "netstat -apn|grep 10010" in the host.

Why does localhost be resolved to ipv6 in the pod sometimes? is it a bug?

Thanks

**Comment by uablrek** [comment]
> Why does localhost be resolved to ipv6 in the pod sometimes?

If I start a K8s cluster and exec into a POD I see;
```
/ # cat /etc/hosts 
# Kubernetes-managed hosts file.
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
fe00::0 ip6-mcastprefix
...
```
As you can see `localhost` is specified for both ipv4 and ipv6. So the resolver may pick any. If it uses [happy eysballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) ipv6 is tried first.

However, it looks like your server opens `::` (ipv6 any), so the connect to "::1" should work as good :confused:

**Comment by uablrek** [comment]
You are using K8s v1.16 which is not supported. To get this triaged as abug you must re-create it on a supported version.

**Comment by uablrek** [comment]
The pod `/etc/hosts` is generated [here](https://github.com/kubernetes/kubernetes/blob/f0dbc32ed9c8a51a6d149eb62d868fb995f0db3a/pkg/kubelet/kubelet_pods.go#L368-L374). IMO `localhost` should not be duplicated to "::1" (hardcoded). That does not seem to be common practice in Linux, at least not on my Ubuntu 20.

**Comment by aojea** [comment]
> That does not seem to be common practice in Linux, at least not on my Ubuntu 20.

hmm, that doesn't match my experience, I commonly see both but I don't have strong data to backup this
```
cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

>  Especially not in an ipv4 only cluster

localhost communication doesn't really depend on the cluster ip family, it depends on the OS, the user can modify the system or disable IPv6 on the kernel if he wants to have an IPv4 only system

**Comment by aojea** [comment]
```
Details
docker 18.09
```

docker used to disable IPv6 on the containers by default

**Comment by uablrek** [comment]
Yes, but in a ipv4-only cluster programs may not be prepared for dual stack, e.g open server sockets with ipv4-any (0.0.0.0). Even though go implements hay eyeballs other languages may not, so an old program may resolve "localhost" and just pick the firsts address which may be "::1".

**Comment by aojea** [comment]
is that a kubernetes problem or an application/system problem, that will happen out of kubernetes too, right?
If I set my server on my linux box using ipv4 only and I use some client that doesn't implement eyeballs to reach localhost it will fail.
Actually, I remember to this issue with rabbitmq and erlang :)

**Comment by wangchanggan** [comment]
> > Why does localhost be resolved to ipv6 in the pod sometimes?
> 
> If I start a K8s cluster and exec into a POD I see;
> 
> ```
> / # cat /etc/hosts 
> # Kubernetes-managed hosts file.
> 127.0.0.1       localhost
> ::1     localhost ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> fe00::0 ip6-mcastprefix
> ...
> ```
> 
> As you can see `localhost` is specified for both ipv4 and ipv6. So the resolver may pick any. If it uses [happy eysballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) ipv6 is tried first.
> 
> However, it looks like your server opens `::` (ipv6 any), so the connect to "::1" should work as good 😕

in the pod, i tried to wget 10010 port, which worked on ipv4 but not ipv6, and it reported network unreachable.
![16406932791497](https://user-images.githubusercontent.com/33536351/147578818-f4b29c45-8ad3-4ab4-ae35-fe2b3da16836.png)

then i used "hostNetwork: true" to restart pod, and in the host wget 10010 port, which worked on ipv4 and ipv6 both.
![16406932103880](https://user-images.githubusercontent.com/33536351/147579034-bf3a9cba-b38a-4db0-84dd-14a88d412105.png)
![16406932536386](https://user-images.githubusercontent.com/33536351/147579086-0f24fac4-3147-4999-9ee7-e58f88712ec7.png)

It seems to be the problem that supportting ipv4 but not ipv6 in the pod.

**Comment by aojea** [comment]
> ```
> Details
> docker 18.09
> ```
> 
> docker used to disable IPv6 on the containers by default

most sure your runtime, docker in this case, is disabling ipv6 on your pods.
docker is no longer supported, but anyway, you have to configure docker to support ipv6
https://docs.docker.com/config/daemon/ipv6/

**Comment by thockin** [comment]
I'm going to close this, to take it off the list, but the conversation can continue.  It doesn't seem to be a k8s bug.
