### ISSUE TITLE
System maximum PID inconsiderate of sysctl 'threads-max'

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#107111]
### What happened?

PIDPressure is not set to true when the system has insufficient pid resource.

### What did you expect to happen?

PIDPressure is set to true correctly when the system is insufficient in pid resource.

### How can we reproduce it (as minimally and precisely as possible)?

See cause below

### Anything else we need to know?

The max pid is not solely controlled by `/proc/sys/kernel/pid_max` which is referred by [pidlimit](https://github.com/kubernetes/kubernetes/blob/712745cb6755b3a28ca12292b30d138d5f737aa6/pkg/kubelet/stats/pidlimit/pidlimit_linux.go#L36). But it is also controlled by `/proc/sys/kernel/threads-max` (whichever is smaller).

However, they have different semantics resulting in the same constraint to how many processes/threads can be running on the system.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:

$ uname -a
5.10.46

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wenlxie** [comment]
https://github.com/kubernetes/kubernetes/pull/57136#discussion_r241675032

**Comment by sftim** [comment]
My opinion: the minimum of `kernel.threads-max` and `kernel.pid_max` is the right number to count, for Linux. That will provide better instrumentation. 

If you're reserving a number of task IDs (PIDs) for system use, that minimum is the number than you're reserving from.

**Comment by sftim** [comment]
/retitle System maximum PID inconsiderate of sysctl 'threads-max'

**Comment by sftim** [comment]
BTW I made a thing that might help folks test a fix: https://github.com/sftim/manytasks

Originally I used it to create PIDs, to test whether apps cope with long PIDs. This version keeps the threads around so that you see them in `/proc/loadavg`.
