### ISSUE TITLE
[Feature request] Support token rotation for service account

### ISSUE THREAD

**Issue by ahrtr** [kubernetes/kubernetes#107150]
### What would you like to be added?

Currently the token created for each service account never expires. When a kubeconfig is generated based on a token bound to a service account, then the users can always use the kubeconfig to communicate with the K8s cluster. We would like the token bound to each service account can be rotated automatically, so that the kubeconfig containing the old token can't talk to apiserver any more. In this case, the kubeconfig needs to be regenerated. 

### Why is this needed?

If a token never expires, then it will have security concern. The best practice is to rotate the token periodically. 

/sig security

**Comment by raesene** [comment]
I think this may be effectively addressed by the [Bound Service Account Token Volume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) feature which is GA in Kubernetes 1.22, This moves from the secret based non-expiring tokens to a projected volume which has expiry.

**Comment by ahrtr** [comment]
Based on the [changelog-1.24](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#no-really-you-must-read-this-before-you-upgrade), users are supposed to use [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) to acquire service account tokens. I guess `kubectl create token SERVICE_ACCOUNT_NAME --duration xxx` is just calling the `TokenRequest` API?

It looks like an chick-egg issue. Please note that what this issue tries to resolve is to generate a kubeconfig (containing a serviceaccount token) file so that users can execute `kubectl` command.
