### ISSUE TITLE
[Flaky Test][sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#107174]
### Which jobs are flaking?

[sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate

### Which tests are flaking?

[sig-apps] Daemon set [Serial] should surge pods onto nodes when spec was updated and update strategy is RollingUpdate

### Since when has it been flaking?

[1mSTEP[0m: Update daemon pods environment var
[1mSTEP[0m: Check that daemon pods surge and invariants are preserved during that rollout
Dec 18 12:09:32.144: INFO: Node         Version Name             UID                                  Deleted Ready
Dec 18 12:09:32.144: INFO: 10.235.30.41 1       daemon-set-gjrk4 ae7cf9a3-aa03-4e10-96c8-bee9adcb6419 false   true
Dec 18 12:09:32.144: INFO: 10.235.30.42 1       daemon-set-wlvdr e76821b1-60b8-40ab-b258-fc37f7f08f01 false   true
Dec 18 12:09:32.144: INFO: 10.235.30.43 1       daemon-set-gbmqp dd35eb65-8bf5-44d9-a621-b1ab3a0f0b2b false   true
Dec 18 12:09:33.163: INFO: Node         Version Name             UID                                  Deleted Ready
Dec 18 12:09:33.163: INFO: 10.235.30.41 1       daemon-set-gjrk4 ae7cf9a3-aa03-4e10-96c8-bee9adcb6419 false   true
Dec 18 12:09:33.163: INFO: 10.235.30.41 2       daemon-set-tqzl5 50b81acf-77ba-448f-a292-32d15bda0667 false   false
Dec 18 12:09:33.163: INFO: 10.235.30.42 1       daemon-set-wlvdr e76821b1-60b8-40ab-b258-fc37f7f08f01 false   true
Dec 18 12:09:33.163: INFO: 10.235.30.42 2       daemon-set-rlr5c 369b63cb-bb61-49b9-810c-d4e80b34167b false   false
Dec 18 12:09:33.163: INFO: 10.235.30.43 1       daemon-set-gbmqp dd35eb65-8bf5-44d9-a621-b1ab3a0f0b2b false   true
Dec 18 12:09:33.163: FAIL: Unexpected error:
    <*errors.errorString | 0xc006c5bee0>: {
        s: "invariants were violated during daemonset update:\nobserved 2 new unavailable pods greater than (surge count 1 + old unavailable count 0 + deliberately deleted new count 0 + nodes without old version 0), may be infrastructure flake",
    }
    invariants were violated during daemonset update:
    observed 2 new unavailable pods greater than (surge count 1 + old unavailable count 0 + deliberately deleted new count 0 + nodes without old version 0), may be infrastructure flake
occurred

Full Stack Trace
k8s.io/kubernetes/test/e2e/apps.glob..func3.10()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:796 +0x10c9
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000ac1080)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc000ac1080)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:136 +0x2b
testing.tRunner(0xc000ac1080, 0x72e4848)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[AfterEach] [sig-apps] Daemon set [Serial]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:108
[1mSTEP[0m: Deleting DaemonSet "daemon-set"
[1mSTEP[0m: deleting DaemonSet.extensions daemon-set in namespace daemonsets-2070, will wait for the garbage collector to delete the pods
Dec 18 12:09:33.225: INFO: Deleting DaemonSet.extensions daemon-set took: 5.723998ms
Dec 18 12:09:33.326: INFO: Terminating DaemonSet.extensions daemon-set pods took: 101.001189ms
Dec 18 12:09:52.777: INFO: Number of nodes with available pods: 0
Dec 18 12:09:52.777: INFO: Number of running nodes: 0, number of available pods: 0
Dec 18 12:09:52.781: INFO: daemonset: {"kind":"DaemonSetList","apiVersion":"apps/v1","metadata":{"resourceVersion":"200516"},"items":null}

Dec 18 12:09:52.785: INFO: pods: {"kind":"PodList","apiVersion":"v1","metadata":{"resourceVersion":"200516"},"items":null}

### Reason for failure (if possible)

[1mSTEP[0m: Update daemon pods environment var
[1mSTEP[0m: Check that daemon pods surge and invariants are preserved during that rollout
Dec 18 12:09:32.144: INFO: Node         Version Name             UID                                  Deleted Ready
Dec 18 12:09:32.144: INFO: 10.235.30.41 1       daemon-set-gjrk4 ae7cf9a3-aa03-4e10-96c8-bee9adcb6419 false   true
Dec 18 12:09:32.144: INFO: 10.235.30.42 1       daemon-set-wlvdr e76821b1-60b8-40ab-b258-fc37f7f08f01 false   true
Dec 18 12:09:32.144: INFO: 10.235.30.43 1       daemon-set-gbmqp dd35eb65-8bf5-44d9-a621-b1ab3a0f0b2b false   true
Dec 18 12:09:33.163: INFO: Node         Version Name             UID                                  Deleted Ready
Dec 18 12:09:33.163: INFO: 10.235.30.41 1       daemon-set-gjrk4 ae7cf9a3-aa03-4e10-96c8-bee9adcb6419 false   true
Dec 18 12:09:33.163: INFO: 10.235.30.41 2       daemon-set-tqzl5 50b81acf-77ba-448f-a292-32d15bda0667 false   false
Dec 18 12:09:33.163: INFO: 10.235.30.42 1       daemon-set-wlvdr e76821b1-60b8-40ab-b258-fc37f7f08f01 false   true
Dec 18 12:09:33.163: INFO: 10.235.30.42 2       daemon-set-rlr5c 369b63cb-bb61-49b9-810c-d4e80b34167b false   false
Dec 18 12:09:33.163: INFO: 10.235.30.43 1       daemon-set-gbmqp dd35eb65-8bf5-44d9-a621-b1ab3a0f0b2b false   true
Dec 18 12:09:33.163: FAIL: Unexpected error:
    <*errors.errorString | 0xc006c5bee0>: {
        s: "invariants were violated during daemonset update:\nobserved 2 new unavailable pods greater than (surge count 1 + old unavailable count 0 + deliberately deleted new count 0 + nodes without old version 0), may be infrastructure flake",
    }
    invariants were violated during daemonset update:
    observed 2 new unavailable pods greater than (surge count 1 + old unavailable count 0 + deliberately deleted new count 0 + nodes without old version 0), may be infrastructure flake
occurred

Full Stack Trace
k8s.io/kubernetes/test/e2e/apps.glob..func3.10()
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:796 +0x10c9
k8s.io/kubernetes/test/e2e.RunE2ETests(0xc000ac1080)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e.go:130 +0x36c
k8s.io/kubernetes/test/e2e.TestE2E(0xc000ac1080)
	_output/local/go/src/k8s.io/kubernetes/test/e2e/e2e_test.go:136 +0x2b
testing.tRunner(0xc000ac1080, 0x72e4848)
	/usr/local/go/src/testing/testing.go:1193 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1238 +0x2b3
[AfterEach] [sig-apps] Daemon set [Serial]
  /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apps/daemon_set.go:108
[1mSTEP[0m: Deleting DaemonSet "daemon-set"
[1mSTEP[0m: deleting DaemonSet.extensions daemon-set in namespace daemonsets-2070, will wait for the garbage collector to delete the pods
Dec 18 12:09:33.225: INFO: Deleting DaemonSet.extensions daemon-set took: 5.723998ms
Dec 18 12:09:33.326: INFO: Terminating DaemonSet.extensions daemon-set pods took: 101.001189ms
Dec 18 12:09:52.777: INFO: Number of nodes with available pods: 0
Dec 18 12:09:52.777: INFO: Number of running nodes: 0, number of available pods: 0
Dec 18 12:09:52.781: INFO: daemonset: {"kind":"DaemonSetList","apiVersion":"apps/v1","metadata":{"resourceVersion":"200516"},"items":null}

Dec 18 12:09:52.785: INFO: pods: {"kind":"PodList","apiVersion":"v1","metadata":{"resourceVersion":"200516"},"items":null}

### Anything else we need to know?

Kubernetes Version: v1.22.3

### Relevant SIG(s)

/sig-apps

**Comment by 249043822** [comment]
Since the daemon_set test sets update strategy {MaxUnavailable: 0，MaxSurge:20%} and our node num is 3,  so we should not see the temp result below, 
Dec 18 12:09:33.163: INFO: Node       Version     Name                         UID                                            Deleted Ready
Dec 18 12:09:33.163: INFO: 10.235.30.41 1 daemon-set-gjrk4 ae7cf9a3-aa03-4e10-96c8-bee9adcb6419 false true
Dec 18 12:09:33.163: INFO: 10.235.30.41 2 daemon-set-tqzl5 50b81acf-77ba-448f-a292-32d15bda0667 false false
Dec 18 12:09:33.163: INFO: 10.235.30.42 1 daemon-set-wlvdr e76821b1-60b8-40ab-b258-fc37f7f08f01 false true
Dec 18 12:09:33.163: INFO: 10.235.30.42 2 daemon-set-rlr5c 369b63cb-bb61-49b9-810c-d4e80b34167b false false
Dec 18 12:09:33.163: INFO: 10.235.30.43 1 daemon-set-gbmqp dd35eb65-8bf5-44d9-a621-b1ab3a0f0b2b false true

As expected, the ds controller should first create a new version pod and wait for ready then to delete a old one, then cycle down in turn, so I think there may be some race condition bug in ds controller

**Comment by aojea** [comment]
is this test flaking in the CI?

It doesn't seem to have a big failure rate, at least not failure on the blocking and informing jobs

https://storage.googleapis.com/k8s-triage/index.html?test=should%20surge%20pods%20onto%20nodes%20when%20spec%20was%20updated%20and%20update

**Comment by 249043822** [comment]
@aojea the reported failure is found in our private ci, but now we don't know the reason, so I want to get some help from community, thanks

**Comment by pacoxu** [comment]
> It doesn't seem to have a big failure rate, at least not failure on the blocking and informing jobs
> 
> https://storage.googleapis.com/k8s-triage/index.html?test=should%20surge%20pods%20onto%20nodes%20when%20spec%20was%20updated%20and%20update

flake in informing job https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial recently, but still not in a big failure rate.
