### ISSUE TITLE
Reflector loops forever with "Too large resource version" when objects aren't changing

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#107133]
### What happened?

Recently observed this on a 1.18 cluster (specifically, apiserver on 1.18.20 and worker nodes on 1.18.16) that there are http 504 responses being seen continuously for list API calls coming from kubelet. These calls have resourceVersion set to non-zero values as they're coming from reflector. The problem is that the RV is higher than what the apiserver's watch-cache is currently at, making the latter return a "Too large resource version" error. The reason why the watch-cache is at an older RV is because the object-type being listed hasn't had any object mutations for a long time, so there wasn't an update. This is a typical situation for a bunch of object-types that Kubelets watch (e.g runtimeclasses, csidrivers, etc). So far everything is fine, and AFAIK starting from version 1.21 the [etcd progress notify](https://github.com/kubernetes/enhancements/issues/1904) feature should properly fix this issue, especially handling the "watch-cache not updating RV when objects aren't changing" problem. But let's talk more about the client-side reflector issue, as this is still a concern if that feature isn't enabled (for e.g versions <= 1.20).

I found that this similar issue was discussed in the past here - https://github.com/kubernetes/kubernetes/issues/91073#issuecomment-650006211. And [this fix](https://github.com/kubernetes/kubernetes/pull/92537) was merged to make the reflector re-list from etcd (instead of watch-cache) on encountering a "too large RV" error. This fix was also backported to 1.18.6, so the client in this case has that fix. But it seems like that fix doesn't fully allow the client to recover from those errors eventually. To explain further:

- Let's say the apiserver watch-cache is at RV=100 for the object-type
- Let's say the client reflector is at RV=110 (how it got there is a separate question, but it can happen for e.g if it was talking a newer apiserver instance before the current one, and that instance could've initialized its watch-cache when etcd was at RV 110)
- Reflector tries to relist from the apiserver watch-cache with RV=110 and fails with "too large RV" (why it's trying to re-list instead of directly starting a watch with that RV is a separate question, and I'll try diving into that later)
- With the above bugfix, reflector falls back to relisting from etcd instead (i.e RV unset) and it gets an even more up-to-date response, let's say RV=150. Since it was able to list fine, it starts a new watch with that RV
- Once the watch times out, it tries to relist again at RV=150 and gets the same error again from watch-cache, so it falls back to listing from etcd and history repeats

Essentially what seems to be happening after that fix is reflector keeps on increasing RV after each `watch -> timeout -> relist(from watch-cache) -> relist(from etcd)` loop, while the apiserver's watch-cache is staying at the same old RV. While this doesn't seem to affect the reflector's functionality (as its objects are kept updated), this is leading to multiple http 504 errors with the API which should ideally not happen.

I'll add some more details on the thread.

/sig api-machinery
cc @wojtek-t @liggitt 

### What did you expect to happen?

The reflector shouldn't end up causing http 504 errors continuously.

### How can we reproduce it (as minimally and precisely as possible)?

- Launch an apiserver instance A
- Wait for some time (for etcd RV to increase)
- Launch another apiserver instance B
- Launch a worker node (kubelet) which talks to apiserver B. It'll start a bunch of watches for various object-type. Let's choose an object-type whose objects rarely change (say runtimeclasses)
- Terminate apiserver instance B, which will cause the kubelet's watch to move over from B (newer instance) -> A (older instance)
- Now the kubelet will receive a "Too large resource version" error while trying to re-list since its RV is higher than A's watch-cache (which wouldn't have been updated for a long time, since there weren't any changes to runtimeclass objects), and it'll now be stuck in the loop explained above

### Kubernetes version

Apiserver kubernetes version: `1.18.20`
Client kubernetes version: `1.18.16`

**Comment by shyamjvs** [comment]
I was able to capture a series of list/watch calls being made by an example kubelet. Here they are:

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|  requestReceivedTimestamp   |                                                               requestURI                                                                | responseStatus.code |
|-----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------|---------------------|
| 2021-12-14T20:22:39.596760Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:22:43.599524Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:22:47.602246Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:22:51.604908Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:22:55.609355Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:22:59.611988Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:23:03.614475Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:23:07.616881Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:23:11.619571Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:23:15.622171Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363782609                                                                      | 504                 |
| 2021-12-14T20:23:18.624337Z | /apis/node.k8s.io/v1beta1/runtimeclasses                                                                                                | 200                 |
| 2021-12-14T20:23:18.628669Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363785786&timeout=5m28s&timeoutSeconds=328&watch=true | 200                 |
| 2021-12-14T20:24:18.113590Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363785786&timeout=6m18s&timeoutSeconds=378&watch=true | 200                 |
| 2021-12-14T20:26:18.251474Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:22.254480Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:26.257843Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:30.261444Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:34.265173Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:38.268449Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:42.271601Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:46.274650Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:50.277729Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:54.280584Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363785786                                                                      | 504                 |
| 2021-12-14T20:26:57.283301Z | /apis/node.k8s.io/v1beta1/runtimeclasses                                                                                                | 200                 |
| 2021-12-14T20:26:57.288000Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363787743&timeout=8m11s&timeoutSeconds=491&watch=true | 200                 |
| 2021-12-14T20:27:57.227456Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363787743&timeout=7m57s&timeoutSeconds=477&watch=true | 200                 |
| 2021-12-14T20:28:56.259116Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363787743&timeout=5m22s&timeoutSeconds=322&watch=true | 200                 |
| 2021-12-14T20:30:56.973927Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:00.976686Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:04.979355Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:08.982376Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:12.985072Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:16.987806Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:20.990737Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:24.993511Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:28.996310Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:32.999259Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363787743                                                                      | 504                 |
| 2021-12-14T20:31:36.004970Z | /apis/node.k8s.io/v1beta1/runtimeclasses                                                                                                | 200                 |
| 2021-12-14T20:31:36.009273Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363790236&timeout=8m11s&timeoutSeconds=491&watch=true | 200                 |
| 2021-12-14T20:32:35.261874Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363790236&timeout=8m36s&timeoutSeconds=516&watch=true | 200                 |
| 2021-12-14T20:34:35.672757Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:39.675856Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:43.678753Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:47.681593Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:51.684347Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:55.687231Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:34:59.689842Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:35:03.692696Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:35:07.695303Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:35:11.698116Z | /apis/node.k8s.io/v1beta1/runtimeclasses?resourceVersion=363790236                                                                      | 504                 |
| 2021-12-14T20:35:14.700703Z | /apis/node.k8s.io/v1beta1/runtimeclasses                                                                                                | 200                 |
| 2021-12-14T20:35:14.706217Z | /apis/node.k8s.io/v1beta1/runtimeclasses?allowWatchBookmarks=true&resourceVersion=363792189&timeout=8m29s&timeoutSeconds=509&watch=true | 200                 |
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by shyamjvs** [comment]
There are few behaviors to observe from the above:

- When reflector is trying to relist from the watch-cache (i.e with RV=X), it seems to be making 10 identical calls back-to-back with a 4s internal. Need to dig deeper, but my best guess at this point is it's probably due to the retry behavior within the reflector's listwatcher implementation. It's a bit orthogonal to this issue, but wondering how much those retries actually help in the "too large RV" case?
- Watches seem to be re-established every 1min instead of the timeout specified by the client. Need to dig further here too, but I'm suspecting the apiserver might be closing it from its end earlier, given there have been no watch events to send for `--request-timeout` duration
- Once watches are re-established a few times, why is the client falling back to re-listing from watchcache with the RV instead of just starting yet another watch with that RV? From the reflector code, I see this can happen if the watch [returns an error](https://github.com/kubernetes/kubernetes/blob/v1.18.16/staging/src/k8s.io/client-go/tools/cache/reflector.go#L371) in which case the whole [ListWatch](https://github.com/kubernetes/kubernetes/blob/v1.18.16/staging/src/k8s.io/client-go/tools/cache/reflector.go#L177) routine is re-invoked, causing a [relist](https://github.com/kubernetes/kubernetes/blob/v1.18.16/staging/src/k8s.io/client-go/tools/cache/reflector.go#L258). Given the watch calls are returned a 200 (from above logs), I'm wondering what error could the reflector be receiving?

@wojtek-t @liggitt - I'd guess you have answers to some of the above questions already? Otherwise I can look further.

**Comment by shyamjvs** [comment]
Regarding the core reflector issue, I'm trying to figure out what was the reason we decided to relist from etcd rather than the watch-cache itself (i.e RV=0) on receiving the too large RV error.

The most info I have so far is from [this comment](https://github.com/kubernetes/kubernetes/blob/v1.18.16/staging/src/k8s.io/client-go/tools/cache/reflector.go#L261-L266):

```
// Retry immediately if the resource version used to list is unavailable.
// The pager already falls back to full list if paginated list calls fail due to an "Expired" error on
// continuation pages, but the pager might not be enabled, the full list might fail because the
// resource version it is listing at is expired or the cache may not yet be synced to the provided
// resource version. So we need to fallback to resourceVersion="" in all to recover and ensure
// the reflector makes forward progress.
```

Does making forward progress by listing from etcd actually help in such cases (where RV is in future only because there have been no events in the interim)?

**Comment by wojtek-t** [comment]
As you mentioned, progress-notify feature should address your main concern. I'm already committed to graduate it to GA in 1.24 (see https://github.com/kubernetes/enhancements/pull/3062).
Given that the problem currently isn't really a correctness issue, but rather the fact that we have unexpected 504s (but it self-recovers and doesn't additional issues, delays, etc.), I don't think we should be investing into some more sophisticated fixes (especially given that 1.18 as an example is already out of support window).


The things we may want to understand though are those from https://github.com/kubernetes/kubernetes/issues/107133#issuecomment-997628107

> When reflector is trying to relist from the watch-cache (i.e with RV=X), it seems to be making 10 identical calls back-to-back with a 4s internal. Need to dig deeper, but my best guess at this point is it's probably due to the retry behavior within the reflector's listwatcher implementation. It's a bit orthogonal to this issue, but wondering how much those retries actually help in the "too large RV" case?

10 retries are coming from here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L145
So the retries are basically coming from here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/rest/request.go#L1000

Regarding 4s, I guess it'a basically a sum of:
- 3s that the request is wating for the request: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/watch_cache.go#L43
- 1s of the backoff in request.go

I agree that we don't get much from retries for "Too large". We may consider skipping retries on that error, but I would need to think more if that's really a good idea.


> Watches seem to be re-established every 1min instead of the timeout specified by the client. Need to dig further here too, but I'm suspecting the apiserver might be closing it from its end earlier, given there have been no watch events to send for --request-timeout duration

No - we don't check for events being sent anywhere. My bet is that there is 1m timeout at the transport level.
We definitely had a bug like that somewhere in the past (i.e. the timeout was common for both long-running and regular requests).
@shyamjvs - can you please investigate this one? Maybe it's still there in your Kubelet or sth?


> Once watches are re-established a few times, why is the client falling back to re-listing from watchcache with the RV instead of just starting yet another watch with that RV? From the reflector code, I see this can happen if the watch returns an error in which case the whole ListWatch routine is re-invoked, causing a relist. Given the watch calls are returned a 200 (from above logs), I'm wondering what error could the reflector be receiving?

The fact that watch call returns 200, doesn't mean that some watch.ERROR event wasn't returned inside (we set the header at the beginning of the handling request and something bad may happen later)
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/reflector.go#L479
Something like that is probably happening.

**Comment by shyamjvs** [comment]
> but it self-recovers and doesn't additional issues, delays, etc.

So the issue I've mentioned above doesn't actually self-recover, and the informer keeps failing and relisting pretty much forever (causing 5xx errors consistently).

> @shyamjvs - can you please investigate this one? Maybe it's still there in your Kubelet or sth?

Unfortunately I no longer have access to the node where this happened (it was from a customer cluster). That said, I did check the TCP keep-alive settings on a different node (having the same linux image) and it seems to be 2 hours:
```
net.ipv4.tcp_keepalive_intvl = 75
net.ipv4.tcp_keepalive_probes = 9
net.ipv4.tcp_keepalive_time = 7200
```
That said, I believe there may be other intermediate routers/firewalls that close the connection if it's been idle for a much shorter duration.

> The fact that watch call returns 200, doesn't mean that some watch.ERROR event wasn't returned inside

Do you know what's the best way to capture such errors? Logs from the client?

**Comment by shyamjvs** [comment]
In general, we discussed the above issue in the last sig-scale biweekly meeting (on Jan 20) and decided to ignore this bug for following reasons:
- the only affected k8s versions are <= 1.20 (starting from 1.21, the default recommendation is to turn on progress-notify for etcd) and 1.20 is going to soon be out of the project's support window
- for the affected earlier versions, without some smart client-side or server-side changes, it's hard to make the client RV get back in sync with the server's watch-cache. And relisting from watch-cache with RV=0 (instead of etcd) is risky because that could make the client go back in time (xref - https://github.com/kubernetes/kubernetes/issues/59848)

**Comment by shyamjvs** [comment]
> relisting from watch-cache with RV=0 (instead of etcd) is risky because that could make the client go back in time

Before closing this issue, one idea I want to discuss regarding above is - can we make clients immune to such "replay of events"? That is, let's say reflector is at RV=10 and watch-cache is at RV=5. Instead of relisting from etcd, reflector relists from watch-cache but remembers that it processed events till RV=10 and so ignores any events received until RV=10?

Asking because IIUC, even with progress notify, etcd itself in some cases might still need to go back in time and replay past transactions from WAL log (for e.g if the etcd cluster lost quorum and restarted from its last backup where the MVCC was at an older RV). So re-listing from etcd could also make the reflector go back in time (unless I'm missing something). In such cases, above client-side fix can help. Wdyt @wojtek-t?

**Comment by wojtek-t** [comment]
> Instead of relisting from etcd, reflector relists from watch-cache but remembers that it processed events till RV=10 and so ignores any events received until RV=10?

It's possible, but it's slightly more complicated that you think - because you need to additionally handle deletions.
It's certainly possible, but it will complicate the code...

> Asking because IIUC, even with progress notify, etcd itself in some cases might still need to go back in time and replay past transactions from WAL log

No - etcd never goes back in time (unless you restore from backup, which k8s doesn't reliably support anyway).
So no - it will not be an issue later.

**Comment by shyamjvs** [comment]
Thanks @wojtek-t.

> because you need to additionally handle deletions

Could you clarify this part? Do deletions not correspond to an RV as well?

**Comment by wojtek-t** [comment]
> Could you clarify this part? Do deletions not correspond to an RV as well?

They do, but obviously deleted objects are not part of the list. As I'm saying, it's doable for sure, but given the second part of my above comment, I don't think it's worth it.

**Comment by shyamjvs** [comment]
Got it. Thanks for your inputs @wojtek-t.

Closing the issue for now.
