### ISSUE TITLE
getting websocket disconnection in  kubenetes version 1.21.5

### ISSUE THREAD

**Issue by cramakan** [kubernetes/kubernetes#107164]
getting websocket disconnection in  kubenetes version 1.21.5

**Comment by aojea** [comment]
> getting websocket disconnection in kubenetes version 1.21.5

you should provide more information, I think that there is also a template with the information required for this kind of issues

**Comment by cramakan** [comment]
we have  1 kubernetes deployement that has implementation of web socket and its running with 4 pods .we have different version of kubernetes cluster 

-  with  kubernetes version 1.15.* and above  pods  are running without web socket disconnection
- with  kubernetes version 1.21.5 same  pods  has issue for  web socket disconnection some time not always

**Comment by ehashman** [comment]
/close

This issue does not have enough information to debug. If you still need assistance, please fill out the full issue template: https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.yaml
