### ISSUE TITLE
kubelet /stats/summary rootfs usage is not correct

### ISSUE THREAD

**Issue by sherwinwangs** [kubernetes/kubernetes#107154]
### What happened?

I've 2 disks /dev/sda is os disk, /dev/sdb is data disk with used for docker data storage with xfs filesystem and mount with uquota,pquota option.
the docker "storage-driver": "overlay2",and with option "overlay2.size=10G", in the pod I can see overlay is limit to 10G.

## pod disk usage
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/app # df -h
Filesystem                Size      Used Available Use% Mounted on
overlay                  10.0G      9.3G    703.2M  93% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                     1.9G         0      1.9G   0% /sys/fs/cgroup
/dev/sda2                29.0G      6.0G     23.0G  21% /dev/termination-log
/dev/sda2                29.0G      6.0G     23.0G  21% /app/config
/dev/sdb                 40.0G     12.4G     27.6G  31% /etc/resolv.conf
/dev/sdb                 40.0G     12.4G     27.6G  31% /etc/hostname
/dev/sda2                29.0G      6.0G     23.0G  21% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     1.9G     12.0K      1.9G   0% /run/secrets/kubernetes.io/serviceaccount
tmpfs                     1.9G         0      1.9G   0% /proc/acpi
tmpfs                    64.0M         0     64.0M   0% /proc/kcore
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                     1.9G         0      1.9G   0% /proc/scsi
tmpfs                     1.9G         0      1.9G   0% /sys/firmware

## kubelet /stats/summary root fs usage is not correct
 {
   "podRef": {
    "name": "user-service-596cb44ff6-d6ht9",
    "namespace": "wukongcloud-dev",
    "uid": "86baa6dc-a13f-44a2-ba8f-dfa5a1dcc0dd"
   },
   "startTime": "2021-12-20T14:14:27Z",
   "containers": [
    {
     "name": "user-service",
     "startTime": "2021-12-20T14:14:29Z",
     "cpu": {...},
     "memory": {...},
     "rootfs": {
      "time": "2021-12-20T15:14:50Z",
      "availableBytes": 29648125952,
      "capacityBytes": 42928701440,
      "usedBytes": 10000007168,
      "inodesFree": 20928331,
      "inodes": 20971520,
      "inodesUsed": 8
     },
     "logs": {...}
    }
   ],

### What did you expect to happen?

rootfs.capacityBytes = 10G
rootfs.availableBytes = capacityBytes - usedBytes

**the usedBytes current is correct**

### How can we reproduce it (as minimally and precisely as possible)?

run the docker with overlay2 storage driver and with limit option. kubernetes version v1.19.10

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:20:25Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux kubernetes 5.4.109-1.el7.elrepo.x86_64 #1 SMP Mon Mar 29 10:03:34 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/area cadvisor
can you please try to repro this on later versions of k8s? 1.19 is out of support

/cc @bobbypage 
/triage needs-information

**Comment by SergeyKanzhelev** [comment]
Also this seems to be a problem with dockershim and it was marked for deprecation. So unless this will turn out to be very severe issue, it may not be fixed in previous releases. Please try on containerd or other runtime.

**Comment by sherwinwangs** [comment]
> Also this seems to be a problem with dockershim and it was marked for deprecation. So unless this will turn out to be very severe issue, it may not be fixed in previous releases. Please try on containerd or other runtime.

I've try kubernetes 1.23 with containerd has same problem.

**Comment by chenk008** [comment]
@endocrimes should we reopen it?
