### ISSUE TITLE
Kubctl Port Forwarding Issue

### ISSUE THREAD

**Issue by ravi-kp** [kubernetes/kubernetes#107160]
I am running a Prometheus exporter inside a container. To monitor the metrics, I am running the Prometheus on my host. The metric is pulled by Prometheus at (a.b.c.d:8081). I am using the following port forwarding command:

` kubectl port-forward --address a.b.c.d podName 8081:8081 -n namespace` 

**_But I am getting the output as :_**
Forwarding from a.b.c.d:8081 -> 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1221 02:17:14.558250  104200 portforward.go:372] error copying from remote stream to local connection: readfrom tcp4 a.b.c.d:8081->a.b.c.d:49198: write tcp4 a.b.c.d:8081->a.b.c.d:49198: write: broken pipe
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1221 02:17:46.605283  104200 portforward.go:340] error creating error stream for port 8081 -> 8081: Timeout occured
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1221 02:17:49.628599  104200 portforward.go:340] error creating error stream for port 8081 -> 8081: Timeout occured
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1221 02:17:52.690064  104200 portforward.go:340] error creating error stream for port 8081 -> 8081: Timeout occured
Handling connection for 8081
Handling connection for 8081
Handling connection for 8081
E1221 02:17:55.626256  104200 portforward.go:340] error creating error stream for port 8081 -> 8081: Timeout occurred

Please help me with this.

**Comment by ashok-arora** [comment]
I have also opened #107203 a few days back. I thought it was only a macOS issue but the problem seems to persist across multiple OSs.

**Comment by brianpursley** [comment]
@ravi-kp What is your kubectl and cluster version?  Can you post the output of `kubectl version`?

Also are you using a cloud provider for your kubernetes cluster?  And if so, which one?

**Comment by ravi-kp** [comment]
@brianpursley Please find the kubectl version:

```
>>kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc", GitCommit:"c66c03f3012a10f16eb86fdce6330433adf6c9ee", GitTreeState:"clean", BuildDate:"2021-02-13T03:54:59Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+bd9e442", GitCommit:"bd9e4421804c212e6ac7ee074050096f08dda543", GitTreeState:"clean", BuildDate:"2021-02-11T23:05:38Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
Cloud provider: openshift 4.7.0
OS: Red Hat Enterprise Linux release 8.5 (Ootpa)

**Comment by ravi-kp** [comment]
> I have also opened #107203 a few days back. I thought it was only a macOS issue but the problem seems to persist across multiple OSs.

Actually, I increased the scrape interval in prometheus.yml file and, now not getting the error.
