### ISSUE TITLE
Allow case-insensitive matching in selectors

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#107285]
### What would you like to be added?

_As a cluster operator_
_I want to be able to enter a command such as:_
```shell
kubectl delete pods --field-selector="status.phase!=Pending","metadata.namespace!=kube-system"
```
_So that I can clean up pending pods except in the primary system namespace_ (I think that command does this)
_And I don't want to have to remember what case convention the `.status.phase` field uses_

### Why is this needed?

(Field) selectors are case sensitive, and sometimes it'd be more convenient to allow ignoring case instead.

**Comment by sftim** [comment]
Slightly relevant to https://github.com/kubernetes/kubernetes/issues/5206 and https://github.com/kubernetes/kubernetes/issues/341

**Comment by liggitt** [comment]
I'm not in favor of increasing the cost of server-side field selector evaluation for this... requiring selector values to use exact matches doesn't seem especially onerous

**Comment by sftim** [comment]
If the API provided a way for clients to discover the available values for enum-type fields, that might allow for a client-side hint that the match is likely to fail. Maybe that's a way to help end users in this situation?
