### ISSUE TITLE
Failed to find binary go-to-protobuf for platform linux/amd64

### ISSUE THREAD

**Issue by kinderyj** [kubernetes/kubernetes#107239]
### What happened?

git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
git checkout remotes/origin/release-1.23

./hack/update-generated-protobuf.sh

+++ [1228 14:01:30] Verifying Prerequisites....
+++ [1228 14:01:31] Building Docker image kube-build:build-c8503f4e72-5-v1.23.0-go1.17.5-bullseye.0
+++ [1228 14:08:11] Deleting container kube-build-data-c8503f4e72-5-v1.22.0-go1.16.12-buster.0
+++ [1228 14:08:11] Deleting image kube-build:build-c8503f4e72-5-v1.22.0-go1.16.12-buster.0
+++ [1228 14:08:12] Creating data container kube-build-data-c8503f4e72-5-v1.23.0-go1.17.5-bullseye.0
+++ [1228 14:08:16] Syncing sources to container
+++ [1228 14:08:30] Output from this container will be rsynced out upon completion. Set KUBE_RUN_COPY_OUTPUT=n to disable.
+++ [1228 14:08:30] Running build command...
!!! [1228 14:08:35] Failed to find binary go-to-protobuf for platform linux/amd64
!!! [1228 14:08:35] Call tree:
!!! [1228 14:08:35]  1: ./hack/../build/../build/common.sh:478 kube::build::run_build_command_ex(...)
!!! [1228 14:08:35]  2: ./hack/../build/run.sh:39 kube::build::run_build_command(...)

This issue only happens in remotes/origin/release-1.23 and master branch.

### What did you expect to happen?

pdate-generated-protobuf.sh can be executed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

git clone https://github.com/kubernetes/kubernetes.git
cd kubernetes
git checkout remotes/origin/release-1.23

./hack/update-generated-protobuf.sh

### Kubernetes version

This issue only happens in remotes/origin/release-1.23 and master branch.

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/master/hack/update-generated-protobuf-dockerized.sh#L31-L32
```
go install k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/go-to-protobuf
go install k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo
```

After the go install above, we should find it in the build image like below after running `./hack/update-generated-protobuf.sh`.
```
➜  kubernetes git:(full-url-format-containerd) docker ps -a
CONTAINER ID   IMAGE                                     COMMAND                  CREATED         STATUS                     PORTS     NAMES
eaf662d473be   kube-build:build-ca22d4ea8b-5-v1.16.5-1   "chown -R 501:20 /go…"   8 minutes ago   Exited (0) 8 minutes ago             kube-build-data-ca22d4ea8b-5-v1.16.5-1
➜  kubernetes git:(full-url-format-containerd) docker cp eaf662d473be:/go/src/k8s.io/kubernetes/_output/dockerized/go/bin/go-to-protobuf .
```

There should be some failures during running `go install k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/go-to-protobuf`.

/sig testing

**Comment by fedebongio** [comment]
Thanks @pacoxu 
/cc @sttts 
/triage accepted
