### ISSUE TITLE
Customize Scheduling-framework

### ISSUE THREAD

**Issue by silence-coding** [kubernetes/kubernetes#107263]
I tried to customize the scheduling-framework according to the community's solution, but I found that it relied on k8s.io/kubernetes, and I couldn't pull kubernetes using go.

I have two questions:
1. How do we pull k8s.io/kubernetes successfully?
2. Why cannot cmd/kube-scheduler be provided externally like k8s.io/api?

[scheduling-framework](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md#custom-scheduler-plugins-out-of-tree)

```
import (
    scheduler "k8s.io/kubernetes/cmd/kube-scheduler/app"
)

func main() {
    command := scheduler.NewSchedulerCommand(
            scheduler.WithPlugin("example-plugin1", ExamplePlugin1),
            scheduler.WithPlugin("example-plugin2", ExamplePlugin2))
    if err := command.Execute(); err != nil {
        fmt.Fprintf(os.Stderr, "%v\n", err)
        os.Exit(1)
    }
}
```

![image](https://user-images.githubusercontent.com/32766901/147755176-42899cd6-e9c3-46d5-b5a9-474f0b45d1ab.png)

**Comment by sanposhiho** [comment]
> 1. How do we pull k8s.io/kubernetes successfully?

k/k is not easy to import. You need to add `replace` for some packages in go.mod.

You can follow this (kube-scheduler-simulator also imports k8s.io/kubernetes.):
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/master/go.mod#L6-L31

FYI: In #89930 we are working on reducing dependences on k8s.io/kubernetes as much as possible.

**Comment by silence-coding** [comment]
@sanposhiho Thank you. I also want to ask a question. Will the scheduling-framework be supported later and scheduler_extender be discarded? I see information that v1.16 is declared obsolete, but I can't find any official information. Except [here](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/scheduling/scheduler_extender.md) marked 1.24 removed

**Comment by sanposhiho** [comment]
> scheduler_extender be discarded?

No. At least I am not aware of any plans for extender to be removed or deprecated.

KEP for scheduler extender can be found here.
https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/1819-scheduler-extender

**Comment by sanposhiho** [comment]
>  but I can't find any official information. Except here marked 1.24 removed

I think it's not about extender, but about the design-proposals itself.

> Design proposals have been archived.
To view the last version of this document, see the Design Proposals Archive Repo.
For information on the replacement design proposal process, see the Kubernetes Enhancement Proposals (KEP) process.
Please remove after 2022-04-01 or the release of Kubernetes 1.24, whichever comes first.
https://github.com/kubernetes/community/tree/master/contributors/design-proposals

**Comment by silence-coding** [comment]
@sanposhiho Thank you
