### ISSUE TITLE
Health Checks Failing - Readiness & Liveness For Production Azure AKS Cluster

### ISSUE THREAD

**Issue by zohebs341** [kubernetes/kubernetes#107257]
Hi All,

We are using Azure AKS Version 1.20.7 with nearly 10 Nodes running on it. Vault is Up, Database is Up, Istio is up and running.

But still health checks(Liveness & Readiness) are failing.

context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: HTTP probe failed with statuscode: 500

Any suggestions or guess?

Is it because of load at API server?? As we have Istio & vault as an init container to application pods.

**Comment by zohebs341** [comment]
In general, if DB connectivity issues or if vault having issues. Health check will fail, that is expected. 

But in my case, vault, istio& DB all are up. But still liveness & readiness failing

**Comment by zohebs341** [comment]
@swetharepakula Please check if you find time. 

Adding more info to it.

I am using Horizontal pod autoscaler CPU based, continuously it's creating and deleting pods based on CPU load. I've noticed "failed to update endpoints error" in events.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/kind support
/close
