### ISSUE TITLE
failed to try resolving symlinks in path "/var/log/pods/default_mqttfire-1

### ISSUE THREAD

**Issue by beyondyinjl2** [kubernetes/kubernetes#107243]
### What happened?

kubectl logs mqttfire-1-66ff697667-hn6jz
failed to try resolving symlinks in path "/var/log/pods/default_mqttfire-1-66ff697667-hn6jz_94fcd001-436e-499e-82ff-9bf588a01b25/mqttfire-arm64/0.log": lstat /var/log/pods/default_mqttfire-1-66ff697667-hn6jz_94fcd001-436e-499e-82ff-9bf588a01b25: no such file or directory

### What did you expect to happen?

I hope to see the log

### How can we reproduce it (as minimally and precisely as possible)?

After deploying the pod, I can't see the log, use: kubectl logs mqttfire-1-66ff697667-hn6j

### Kubernetes version

kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/arm64"}

### Cloud provider

no

### OS version

cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP8)"
ID="euleros"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP8)"
ANSI_COLOR="0;31"

uname -a
Linux Euler 4.19.36-vhulk1907.1.0.h1017.eulerosv2r8.aarch64 #1 SMP Sat Mar 27 10:04:38 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Furthermore, 1.19 is no longer a supported Kubernetes version. Can you reproduce this on 1.20+?

Once more details are provided, the bug will be accepted.

/triage needs-information
/sig node

**Comment by liuyingshanx** [comment]
Find your container log under /var/log/containers/<container name>. Maybe this could help.

**Comment by chaudharisuresh997** [comment]
> /var/log/containers/

where to find this directory

**Comment by liuyingshanx** [comment]
> > /var/log/containers/
> 
> where to find this directory which command to use to go there is it inside pod or somewhere in k8s

In the host machine where your pod is running. You may find container log files under /var/log/containers/*

**Comment by Boorhin** [comment]
I have the same bug and `/var/log/containers/` is empty.
```
$ ls -l /var/log/containers/
total 0

```
Kubernetes 1.24

**Comment by ChaoquanTao** [comment]
me too, same error, the directory /var/log/pods/ds_01-frame-extractor-21914-949qb_042a9792-f545-434c-8dc6-f0f549d18dbb/01-frame-extractor-21914 includes no file.
