### ISSUE TITLE
Missing check for devicePath to ensure the path exists

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#107231]
### What happened?

Similar to cinder mode volume:
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/cinder/attacher.go#L242-L246
There should be a check for devicePath to ensure the path exists. But in some other cloud provider, it seems there are no path existing check for devicePath. 
● csi 
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/csi/csi_attacher.go#L132-L142
● fc
https://github.com/kubernetes/kubernetes/blob/4ad08fa5b611826505fa2892cdce463f12d32b35/pkg/volume/fc/fc_util.go#L251-L258
● flex 
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/flexvolume/attacher.go#L52-L65
● iscsi
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/iscsi/attacher.go#L79-L87
● rbd
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/rbd/attacher.go#L117-L131
● vsphere
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/vsphere_volume/attacher.go#L156-L189
Line 176 calls the func verifyDevicePath(), but in the verifyDevicePath() , it don't check if the devicepath already exists.
https://github.com/kubernetes/kubernetes/blob/2ecdc5e8d19ee7a037b86e90a4d3de56cb94b938/pkg/volume/vsphere_volume/attacher.go#L176
https://github.com/kubernetes/kubernetes/blob/864e5e564ae08b64c80ba562951b924860a1a1ae/pkg/volume/vsphere_volume/vsphere_volume_util.go#L78-L86

### What did you expect to happen?

Add check for devicePath as cinder do to check the path exists.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

None

### Kubernetes version

Any

### Cloud provider

Any

### OS version

Any

### Install tools

Any

### Container runtime (CRI) and and version (if applicable)

Any

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Any

**Comment by NikhilSharmaWe** [comment]
@b0b0haha I made a [PR](https://github.com/kubernetes/kubernetes/pull/107219) for a similar [issue](https://github.com/kubernetes/kubernetes/issues/107184) opened by you `kubernetes/pkg/volume/flexvolume/attacher-defaults.go`. Could you please review it and give your thoughts.

**Comment by NikhilSharmaWe** [comment]
@b0b0haha I think that [verifyDevicePath()](https://github.com/kubernetes/kubernetes/blob/864e5e564ae08b64c80ba562951b924860a1a1ae/pkg/volume/vsphere_volume/vsphere_volume_util.go#L78-L86) is checking that whether the path exists or not. Could you take a look at it again or am I missing something here.

**Comment by jsafrane** [comment]
This is intentional. `devicePath` in `WaitForAttach` is a device name returned by a previous `Attach()` call. Not all volume plugins know exact device name during `Attach()` and therefore they return empty string from there. It's then task of `WaitForAttach()` to find the actual device and they ignore `devicePath`.

Similarly, Flex and CSI volume plugins do not know if Attach() returned anything and if it is actually a device path (it's ID of VolumeAttachment in CSI case) and therefore they don't check for it explicitly. It's task for `WaitForAttach` to actually wait for an attached device to appear on the node.

**Comment by nckturner** [comment]
@jsafrane so what are next steps?  Should issue be closed or does sig-storage want to take it?

**Comment by jsafrane** [comment]
I think we can close this issue.
