### ISSUE TITLE
How to manually recover accidentally deleted pv

### ISSUE THREAD

**Issue by liulp** [kubernetes/kubernetes#107214]

**Comment by jonyhy96** [comment]
Please provide more information.e.g. k8s version, pv status, pvc status, the csi u are using. This may help https://stackoverflow.com/a/55568289/9321069 though

**Comment by jonyhy96** [comment]
/retitle How to manually recover accidentally deleted pv

**Comment by jlsong01** [comment]
If PVC was deleted accidentally and reclaim policy is retain, or it's a manually provisioned PV, then you could recover the data somehow.

If PV was deleted(Terminating), probably the data would be lost if no snapshot or backup was made before.

**Comment by liulp** [comment]
$ kubectl get pv efk-pv01
NAME     CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM             STORAGECLASS   REASON   AGE
efk-pv01   10Gi          RWX                        Retain                     Terminating     logging/efk-pvc01                                          415d
$ kubectl get pvc efk-pvc01 -n logging
NAME      STATUS   VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
efk-pvc01   Bound    efk-pv01  10Gi             RWX                                                     415d
In fact, PV deleted here is hung, that is, PV cannot be deleted. However, PV will become Terminating at this time, and the corresponding PVC will still be Bound. That is to say, since PV and PVC have been Bound together, PV cannot be deleted first. Only the current state is Terminating. For PVC Or there is no influence, so what should we do at this time?

The PV accidentally deleted ，I want to recovery the PV

**Comment by jonyhy96** [comment]
IIRC, Only pvc delete before pv will trigger the reclaim policy. see https://github.com/kubernetes/enhancements/issues/2644

**Comment by jonyhy96** [comment]
BACKUP UR DATA BEFORE DOING THIS.
These steps may help:
1. k get pv -o yaml > pv.yaml
2. k edit pv xxx and delete the spec.claimRef part
3. vi pv.yaml and delete the metadata.deletionTimestamp part
4. k create -f pv.yaml
 
The pvc should be  in`lost` status when delete the pv but after recreate the pv, the pvc should be in `bound` status
