### ISSUE TITLE
Windows tests: Flakes due to StartContainer timeouts

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#107290]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master

### Which tests are flaking?

Any test, but it seems to happen more often for tests in which there are pods with pause / sleeps in them.

### Since when has it been flaking?

Unknown

### Testgrid link

https://testgrid.k8s.io/sig-windows-signal#aks-engine-windows-containerd-master

### Reason for failure (if possible)

It seems that there are some cases in which Starting the container times out. In a normal scenario, you would see something like this in the containerd logs:

```
time="2021-12-27T16:10:23.285581000Z" level=info msg="StartContainer for \"fbfe9b1b1e14f5fe81b71b0fa038dd9bb209f2d3b10cfbfcc0b44d345f62d24c\""
time="2021-12-27T16:10:26.282784600Z" level=info msg="StartContainer for \"fbfe9b1b1e14f5fe81b71b0fa038dd9bb209f2d3b10cfbfcc0b44d345f62d24c\" returns successfully"
```

But in other cases, that doesn't happen. The ``StartContainer`` action is started, but it doesn't seem to finish, and 4 minutes later, the shim gets disconnected. After that, it's supposed to clean up the container, but fails, and after that there is another ``StartContainer`` command, which results in the ``failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd: context deadline exceeded: unknown`` error, which can be observed in the test logs as well.

Sample from the job https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1475488193955500032 , the test `` [sig-node] Pods should support pod readiness gates [NodeConformance]``:

```
time="2021-12-27T16:10:38.757212900Z" level=info msg="CreateContainer within sandbox \"71f3c38d4cac5482b56388a0d903bf38b38b30a6b635f343abf8e2e93c36cdd7\" for &ContainerMetadata{Name:pod-readiness-gate,Attempt:0,} returns container id \"fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd\""
time="2021-12-27T16:10:38.775474200Z" level=info msg="StartContainer for \"fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd\""

...

time="2021-12-27T16:14:39.108162800Z" level=warning msg="cleaning up after shim disconnected" id=fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd namespace=k8s.io
time="2021-12-27T16:14:39.108162800Z" level=info msg="cleaning up dead shim"
time="2021-12-27T16:14:44.126461000Z" level=error msg="failed to delete shim" error="1 error occurred:\n\t* close wait error: context deadline exceeded\n\n" id=fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd
time="2021-12-27T16:14:44.126461000Z" level=error msg="Failed to pipe stderr of container \"fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd\"" error="file has already been closed"
time="2021-12-27T16:14:44.126461000Z" level=error msg="Failed to pipe stdout of container \"fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd\"" error="file has already been closed"
time="2021-12-27T16:14:44.138381500Z" level=error msg="StartContainer for \"fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd\" failed" error="failed to create containerd task: failed to create shim task: hcs::CreateComputeSystem fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd: context deadline exceeded: unknown"
time="2021-12-27T16:14:44.146062700Z" level=error msg="failed to delete" cmd="c:\\program files\\containerd\\containerd-shim-runhcs-v1.exe -namespace k8s.io -address \\\\.\\pipe\\containerd-containerd -publish-binary C:\\Program Files\\containerd\\containerd.exe -id fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd -bundle C:\\ProgramData\\containerd\\state\\io.containerd.runtime.v2.task\\k8s.io\\fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd delete" error="exit status 1"
time="2021-12-27T16:14:44.146597500Z" level=warning msg="failed to clean up after shim disconnected" error="time=\"2021-12-27T16:14:39Z\" level=info msg=Span duration=8.7706ms endTime=\"2021-12-27 16:14:39.1497976 +0000 GMT m=+0.022934101\" name=HcsOpenComputeSystem parentSpanID=37dffeeaf919d8fa spanID=c0b03425fe08718a startTime=\"2021-12-27 16:14:39.141027 +0000 GMT m=+0.014163501\" traceID=4a4ee68d94553c462ddd48943e482650\ntime=\"2021-12-27T16:14:39Z\" level=info msg=Span duration=0s endTime=\"2021-12-27 16:14:39.23257 +0000 GMT m=+0.105707501\" name=HcsRegisterComputeSystemCallback parentSpanID=37dffeeaf919d8fa spanID=49826a5f02f8091a startTime=\"2021-12-27 16:14:39.23257 +0000 GMT m=+0.105707501\" traceID=4a4ee68d94553c462ddd48943e482650\ntime=\"2021-12-27T16:14:39Z\" level=info msg=Span duration=6.7692ms endTime=\"2021-12-27 16:14:39.2393392 +0000 GMT m=+0.112476701\" name=HcsGetComputeSystemProperties parentSpanID=37dffeeaf919d8fa propertyQuery=\"{}\" spanID=d253a09906e7a2a9 startTime=\"2021-12-27 16:14:39.23257 +0000 GMT m=+0.105707501\" traceID=4a4ee68d94553c462ddd48943e482650\ntime=\"2021-12-27T16:14:39Z\" level=info msg=Span duration=\"67.8µs\" endTime=\"2021-12-27 16:14:39.2407423 +0000 GMT m=+0.113879901\" name=HcsTerminateComputeSystem options= parentSpanID=37dffeeaf919d8fa spanID=e4f60b0e0fc5d4c8 startTime=\"2021-12-27 16:14:39.2406745 +0000 GMT m=+0.113812101\" traceID=4a4ee68d94553c462ddd48943e482650\n: exit status 1" id=fef17be43ddba773ed4676aaa50df90d9d39d526ec9e7fbafdae33d2d1931efd namespace=k8s.io
```

The information collected by containerd also seems incomplete. The error reported only includes the command's stderr [1], but the error writer in hcsshim is set to stdout [2].

[1] https://github.com/containerd/containerd/blob/653f2f1ce4b8eaee13810fd0c5fce73e039d14a6/runtime/v2/binary.go#L180
[2] https://github.com/microsoft/hcsshim/blob/e1ddd01d53d7167618ca1874d9d8da22d17cfe17/cmd/containerd-shim-runhcs-v1/serve.go#L162

### Anything else we need to know?

Jobs:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1475488193955500032
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1473673815102853120

Containerd version: containerd://1.6.0-beta.4

### Relevant SIG(s)

/sig windows

**Comment by marosset** [comment]
/triage accepted
/milestone v1.24

This is an issue in containerd

**Comment by marosset** [comment]
@claudiubelu is this still an issue?
Is there an issue in containerd/contianerd we can link to if this is an issue in containerd.

**Comment by dims** [comment]
@claudiubelu let's please clear the milestone if there is no urgency?

**Comment by DiptoChakrabarty** [comment]
@claudiubelu I am the  bug triage shadow , since we are in 1.24 code freeze  I  wanted to check if this could be moved to the next milestone

**Comment by dims** [comment]
Doesn't seem like there is any urgency or priority. clearing milestone.

/milestone clear

**Comment by marosset** [comment]
/remove-lifecycle rotten
We've been waiting for some WIndows OS fixes which were broadly released on Aug 8th.
These OS patches should get picked up with the set of images in CAPZ.
