### ISSUE TITLE
request: backport cadvisor v0.40.0 to older branches

### ISSUE THREAD

**Issue by daniellavoie** [kubernetes/kubernetes#107284]
### What happened?

I'm running k3s with kube `1.21.x` and I am currently impacted by google/cadvisor/pull/2868 which was fixed in cadvisor `v0.40.0`. All maintained branches are currently running cadvisor `v0.39.0` except `1.23.x` which is under the latest cadvisor.

### What did you expect to happen?

Bump all supported branches of Kubernetes to cadvisor > `0.40.0`.

### How can we reproduce it (as minimally and precisely as possible)?

* Deploy the [Concourse Helm chart](https://github.com/concourse/concourse-chart)
* Deploy a test pipeline using the [concourse tutorial](https://concoursetutorial.com/)
* Introspect the metric endpoint `kubectl get --raw /api/v1/nodes/${NODE}/proxy/metrics/cadvisor`
* Container metrics will disappear after few minutes and `container_scrape_error` will start emit `1`.

Concourse workers run a lots of short lived containers using containerd. They causes cadvisor to cache miss when pulling latest container metrics and hence, completely interrupt the metric gathering.

The kubelet logs will start tracing this logs when the problem occurs:
```
W0101 23:17:43.322433    3000 prometheus.go:1856] Couldn't get containers: partial failures:
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-14T05:15:04Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="k3OS"
VERSION="k3OS v0.21.5-k3s2r1"
ID=k3os
ID_LIKE=alpine
PRETTY_NAME="k3OS v0.21.5-k3s2r1"
VERSION_ID="v0.21.5-k3s2r1"
HOME_URL="https://k3os.io/"
SUPPORT_URL="https://k3os.io/"
BUG_REPORT_URL="https://github.com/rancher/k3os/issues"
ISO_URL="https://github.com/rancher/k3os/releases/download/v0.21.5-k3s2r1/k3os-amd64.iso"

$ uname -a
Linux k3os-22970 5.4.0-88-generic #99 SMP Tue Oct 5 16:53:38 UTC 2021 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> Bump all supported branches of Kubernetes to cadvisor > 0.40.0.

cadvisor vendoring use to be tricky due to all the dependencies at play, have you evaluated how feasible it is?

**Comment by daniellavoie** [comment]
I'm in that process as we speak, I've just signed the contributor CLA and looking to setup a dev environment. This is the first time I'll be putting a feet in the k8s codebase so I have no confidence in how reliable my evaluation will be 😄

**Comment by daniellavoie** [comment]
https://github.com/kubernetes/kubernetes/commit/8af7405f1730c4913c48c6dc494e319cb3015f69 is a scary thing to backport. Hoping a `v0.39.0` to `v.0.40.0` is less impactful.

**Comment by daniellavoie** [comment]
if it's too complicated I'll see if we can submit a `v.0.39.3` release on cadvisor.

**Comment by daniellavoie** [comment]
I've submitted https://github.com/google/cadvisor/pull/3038 to backport the cadvisor fix on  `v0.39.x`. Should definitely prove to be a less impactful upgrade.

**Comment by SergeyKanzhelev** [comment]
/assign @bobbypage 

As @aojea said updating dependencies may be tricky in earlier versions. It may be best to release a "hotfix" version of cAdvisor

The bug seems to be nasty and it would be great to have a fix backported. I'm debating between `important-soon` and `critical-urgent`, feel free to update the priority.

/triage accepted
/priority important-soon

**Comment by daniellavoie** [comment]
Thank you for the update. I'm personally not impacted on a production system no worries here. Only a small feature of my system is broken.

I'm trying to get attention from the cadvisor team to review and accept my PR. Any help there would be appreciated. Thanks!

**Comment by bobbypage** [comment]
see 

https://github.com/kubernetes/kubernetes/pull/107356 for 1.21
https://github.com/kubernetes/kubernetes/pull/107355 for 1.22

**Comment by bobbypage** [comment]
Both PRs above have merged, so I think we can close this. Please re-open if there's anything else needed. Thanks!

/close
