### ISSUE TITLE
connection timed out fot upstream to downstream 

### ISSUE THREAD

**Issue by sivaandyala765** [kubernetes/kubernetes#107269]
### What would you like to be added?

2021/12/31 13:40:37 [error] 13#13: *142993 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/awc-tracker/beneficiary/save HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"
2021/12/31 13:40:59 [error] 13#13: *141596 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/login HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"
2021/12/31 13:42:31 [error] 13#13: *144225 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/awc-tracker/beneficiary/save HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"

### Why is this needed?

solve this

**Comment by aojea** [comment]
@sivaandyala765 please stop opening the same issue several times, this is not the right place for this kind of problems

#107268 

/close
