### ISSUE TITLE
Can't update `service.status` filed

### ISSUE THREAD

**Issue by yuswift** [kubernetes/kubernetes#107245]
### What happened?

Currently, as a cloud provider, we can only update `service.status.loadBalancer` filed.

### What did you expect to happen?

Put more information into `service.status` filed. e.g.
```bash
status:
  loadBalancer:
    ingress:
    - ip: 192.168.0.1
  conditions:
  - reason: "bar"
    lastTransitionTime: "2021-12-28T09:20:39Z"
    status: "True"
    type: foo
    message: ""

### How can we reproduce it (as minimally and precisely as possible)?

none

### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.20.6
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
@yuswift can you expand more?
do you want to add more fields to status?

**Comment by yuswift** [comment]
> @yuswift can you expand more? do you want to add more fields to status?

yes, I want to add more fileds to status. Just like `deployment` and other workloads.

**Comment by yuswift** [comment]
> /remove-kind bug /kind feature

I don't understand why we can't add more filed into `service.staus` field with `service clientset`.

**Comment by aojea** [comment]
> I don't understand why we can't add more filed into `service.staus` field with `service clientset`.

ahh, sorry, I didn't get the question correctly and I thought the request was for adding new fields to status, but those fields already exist, you just want to modify them

Create a new service an check status is empty

```
kubectl get service test -o=jsonpath='{.status}' | jq
{
  "loadBalancer": {}
}
```

I'm able to modify them with curl, so I assume that unless is a problem with RBAC, you should be able to do it

```
curl -X PATCH https://127.0.0.1:40893/api/v1/namespaces/default/services/test/status -H "Content-Type: application/merge-patch+json" --header "Authorization: Bearer $TOKEN" --insecure -d '{
    "status": {
        "conditions": [
            {
                "type": "MyCondition",
                "status": "True",
                    "reason": "MyReason",
                    "message": "my message"
            }
        ]
    }
}'
```

and the new service status:
```
kubectl get service test -o=jsonpath='{.status}' | jq
{
  "conditions": [
    {
      "lastTransitionTime": null,
      "message": "my message",
      "reason": "MyReason",
      "status": "True",
      "type": "MyCondition"
    }
  ],
  "loadBalancer": {}
}
```

**Comment by yuswift** [comment]
> > I don't understand why we can't add more filed into `service.staus` field with `service clientset`.
> 
> ahh, sorry, I didn't get the question correctly and I thought the request was for adding new fields to status, but those fields already exist, you just want to modify them
> 
> I'm able to modify them with curl, so I assume that unless is a problem with RBAC, you should be able to do it
> 
> 1. Create a new service an check status is empty
> 
> ```
> kubectl get service test -o=jsonpath='{.status}' | jq
> {
>   "loadBalancer": {}
> }
> ```
> 
> 2. patch the service status
> 
> ```
> curl -X PATCH https://127.0.0.1:40893/api/v1/namespaces/default/services/test/status -H "Content-Type: application/merge-patch+json" --header "Authorization: Bearer $TOKEN" --insecure -d '{
>     "status": {
>         "conditions": [
>             {
>                 "type": "MyCondition",
>                 "status": "True",
>                     "reason": "MyReason",
>                     "message": "my message"
>             }
>         ]
>     }
> }'
> ```
> 
> 3. and check the new service status:
> 
> ```
> kubectl get service test -o=jsonpath='{.status}' | jq
> {
>   "conditions": [
>     {
>       "lastTransitionTime": null,
>       "message": "my message",
>       "reason": "MyReason",
>       "status": "True",
>       "type": "MyCondition"
>     }
>   ],
>   "loadBalancer": {}
> }
> ```

Thanks! I think I updated the service the wrong way.
/close
