### ISSUE TITLE
api-server-maser /calico/ kube-scheduler-master  health check fail

### ISSUE THREAD

**Issue by Ulicong** [kubernetes/kubernetes#107298]
Kubernetes v1.20.0
Docker version 20.10.8
calico/cni:v3.8.9

![image](https://user-images.githubusercontent.com/13343901/147999059-9313c1ba-3ab2-42d2-a2f8-b5c3c0347a2e.png)

**Comment by ehashman** [comment]
Hello @Ulicong, this is insufficient information for us to debug your issue.

Please fill out the template at https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.yaml

/close
