### ISSUE TITLE
Kubectl top pod command returns incorrect amount of memory for STS pod in case the pod is deleted and recreated

### ISSUE THREAD

**Issue by tomas-k-mall** [kubernetes/kubernetes#107291]
### What happened?

When STS pod is deleted via `kubectl delete pod` command and subsequently created on another node, `kubectl top pod` command returns MEMORY(bytes) as sum of  the deleted pod and newly created pod for approx. 3 minutes. 

MEMORY(bytes) in such case returns nonsensical value exceeding in fact memory limits and this is responsible for creating false alarms in our case.

It is verified, that it is only `kubectl top pod` problem, which sources data for its output from metrics.k8s.io/v1beta1.

cAdvisor metrics from node show correct values.

### What did you expect to happen?

`kubectl top pod` and The metrics API(metrics.k8s.io/v1beta1) shows values only for one pod at a time.

### How can we reproduce it (as minimally and precisely as possible)?

Delete an STS pod with `kubectl delete pod` and watch The metrics API values directly or via `kubectl top pod`.

### Anything else we need to know?

The pod we observed and tested the behaviour was with Redis DB container.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</details>


### Cloud provider

<details>
none, bare-metal instalaltion
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux k8s-dc1-101 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
docker://19.3.15
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
 kubectl describe apiservice.apiregistration.k8s.io/v1beta1.metrics.k8s.io
Name:         v1beta1.metrics.k8s.io
Namespace:    
Labels:       app.kubernetes.io/component=metrics
              app.kubernetes.io/instance=prometheus-adapter
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=prometheus-adapter
              app.kubernetes.io/part-of=prometheus-adapter
              app.kubernetes.io/version=v0.9.1
              helm.sh/chart=prometheus-adapter-3.0.0
</details>

**Comment by eddiezane** [comment]
@lauchokyip want to take a look at this one?

**Comment by lauchokyip** [comment]
@eddiezane , `kubectl top` pulls the data from `metrics.k8s.io/v1beta1` and if I am not mistaken, the only thing `kubectl` does is formatting and printing it out. I think this issue might be more related to sig-instrumentation

/sig-instrumentation

**Comment by dgrisonnet** [comment]
/remove-sig cli

This seems to be a problem with prometheus-adapter rather than kubectl since the data exposed by the resource metrics API is incorrect.

**Comment by dgrisonnet** [comment]
@tomas-k-mall since this issue is not related to Kubernetes, could you please reopen it in https://github.com/kubernetes-sigs/prometheus-adapter and share the configuration of your adapter?

/close
