### ISSUE TITLE
kubectl replace does not update Network Policy changes

### ISSUE THREAD

**Issue by Jeansen** [kubernetes/kubernetes#107274]
### What happened?

Set up a new cluster with kubeadm following the docs at kubernetes.io with kubernetes 22.5 (one master node, 4 worker nodes).
Installed weavenet overlay network via helm.
I can install any kind of helm charts, pods etc. Everything works as expected.

Created a simple Network Policy blocking Ingress and Egress.
Ran a simple pod to see if the policy is active.
Deleted the policy.
Ran a simple pod to see if the policy is inactive/deleted.

So far, everything worked as expected.
Created the Network Policy again
This time, I  removed the Egress rule afterwards and used `kubectl replace` instead of create and delete.
Again, I ran a simple pod to see if I could reach any external address but I could not. It looks like the policy is still in effect.

Here is the policy I used and the pod including it's test command:

### What did you expect to happen?

I would have expected `kubectl replace` to behave the same a `kubectl create` and `kubectl delete` combined.

### How can we reproduce it (as minimally and precisely as possible)?

I used the following overlay network:
```
kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d "\n")
```
I used the following yaml and commands for testing

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
```

```
kubectl run -it --rm --image=busybox --restart=Never  -- sh
#nc -vz www.linux.com 80
```

### Anything else we need to know?

Cluster nodes have been created with Vagrant and libvirt.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux node2.k8s 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.22.1
RuntimeApiVersion:  v1alpha2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
The NetworkPolicy behavior is an implementation detail of your CNI plugin, that seems to be Weave in this case, by your description.

You should report this issue on the Weave repo, because this does not look like a kubernetes problem

**Comment by Jeansen** [comment]
@aojea Thanks for the feedback. Frankly I was not sure. So, I startet at the top. I'll open an issue at Weave, too.

**Comment by aojea** [comment]
> So, I startet at the top. I'll open an issue at Weave, too

No problem, let us know, your question is legit, if there can be something that kubernetes can improve is a win for all

**Comment by Jeansen** [comment]
I'll close this one then and reopen, if necessary.
