### ISSUE TITLE
invalid configuration: [context was not found for specified context: default, cluster has no server defined]

### ISSUE THREAD

**Issue by jyller** [kubernetes/kubernetes#107282]
### What happened?

**I failed to start kube-controller-Manager**

kube-controller-manager --kubeconfig=/etc/kubernetes/kubeconfig --leader-elect=true --service-cluster-ip-range=169.169.0.0/16 --service-account-private-key-file=/etc/kubernetes/pki/apiserver.key --root-ca-file=/etc/kubernetes/pki/ca.crt --log-dir=/var/log/kubernetes --logtostderr=false --v=0
Flag --log-dir has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
Flag --logtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
invalid configuration: [context was not found for specified context: default, cluster has no server defined]

**kubeconfig file**

apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    server: https://192.168.1.12:9443
    certificate-authority: /etc/kubernetes/pki/ca.crt
users:
- name: admin
  user:
    client-certificate: /etc/kubernetes/pki/client.crt
    client-key: /etc/kubernetes/pki/client.key
contexts:
- context:
    cluster: default
    user: admin
  name: default
current-context: default

### What did you expect to happen?

start kube-controller-manager success

### How can we reproduce it (as minimally and precisely as possible)?

install kubernetes 1.23.1

### Kubernetes version

<details>

kubernetes version 1.23.1

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jyller** [comment]
i back to 1.19.0 ， the same error occurred

**Comment by jyller** [comment]
etcd and api-server start success

**Comment by pandaamanda** [comment]
@jyller not occurred on my cluster

maybe you can check the kubeconfig file

apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    server: https://xx.xx.xx.xx:6443
    certificate-authority: /etc/kubernetes/certs/ca.crt
users:
- name: admin
  user:
    client-certificate: /etc/kubernetes/certs/kubecfg.crt
    client-key: /etc/kubernetes/certs/kubecfg.key
contexts:
- context:
    cluster: default
    user: admin
  name: default
current-context: default

**Comment by jyller** [comment]
oh my gad.  I used a note-taking software.
I copied the configuration text to that software, and then I copied it and pasted it to the server, and the invisible characters changed, so the server couldn't parse it.

thank you! i love you

**Comment by fedebongio** [comment]
Glad you were able to fix it! Thank you for letting us know!
/triage accepted
/close
