### ISSUE TITLE
Before detach device should ensure there is no pod use it

### ISSUE THREAD

**Issue by b0b0haha** [kubernetes/kubernetes#107246]
### What happened?

Similar to [#74313](https://github.com/kubernetes/kubernetes/issues/74313) ,  in the implement of other cloud provider's DetachDisk(), there should be a check to ensure if there are other pods using other volumes on the same device to avoid unexpected result.

- fc

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/pkg/volume/fc/fc_util.go#L261-L292

- rbd

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/pkg/volume/rbd/rbd_util.go#L471-L512

- aws

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/legacy-cloud-providers/aws/aws.go#L2469-L2537

- azure

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go#L206-L268

- gce

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/legacy-cloud-providers/gce/gce_disks.go#L588-L606

- vsphere

  https://github.com/kubernetes/kubernetes/blob/1df88a8a42952d4b0f393c1d25b1d1c992bf72c3/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L986-L1038

### What did you expect to happen?

Before detach disk ,add necessary check to ensure device is ready to detach.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

Maybe there is some other check before detach device that I don't notice in the implement of in-tree cloud provider plugin.

### Kubernetes version

ANY

### Cloud provider

ANY

### OS version

ANY

### Install tools

ANY

### Container runtime (CRI) and and version (if applicable)

ANY

### Related plugins (CNI, CSI, ...) and versions (if applicable)

ANY

**Comment by NikhilSharmaWe** [comment]
@b0b0haha Could you please give your thought here, will [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L640-L649) part should be added in the vendors `detachDisk` function.

**Comment by b0b0haha** [comment]
> `detachDisk` function.

Different vendors may use different logic for check if device is used by other pod,  the logic in iscsi may can't directly added in the vendors detachDisk.

**Comment by b0b0haha** [comment]
> @b0b0haha Could you please give your thought here, will [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L640-L649) part should be added in the vendors `detachDisk` function.

Different vendors may use different logic for check if device is used by other pod, the logic in iscsi may can't directly added in the vendors detachDisk.

**Comment by nckturner** [comment]
/triage-accepted

This probably needs a KEP.

**Comment by NikhilSharmaWe** [comment]
@nckturner I think for adding this check we have to add a function similar to function [isSessionBusy()](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/iscsi/iscsi_util.go#L641) `inDetachDisk()` function. 

Could you please help me a little here because the functions used in `isSessionBusy()` are not present in the other vendors like in `fcutil.go`, also the some of the types which are present in `iscsiDiskUnmounter` are not in `fcDiskUnmounter`. This makes it difficult to make similar functions in `fcutil.go`.

Help needed, how should I proceed  ?

**Comment by NikhilSharmaWe** [comment]
@andrewsykim Could you please give your thoughts on this comment https://github.com/kubernetes/kubernetes/issues/107246#issuecomment-1017722675.
