### ISSUE TITLE
Azure AKS - 1.20.7 - Not saving endpoints for unknown healthcheck

### ISSUE THREAD

**Issue by zohebs341** [kubernetes/kubernetes#107275]
### What happened?

We are using Azure AKS V1.20.7 and the service type in production environment is ClusterIP. In Kube-proxy logs, continuously I see the below printed line.

"Not saving endpoints for unknown healthcheck"

service_health.go:183] Not saving endpoints for unknown healthcheck

It may increase Syncing time I believe. Kindly assist.

### What did you expect to happen?

It should not print below line in kube-proxy logs.

"Not saving endpoints for unknown healthcheck"
service_health.go:183] Not saving endpoints for unknown healthcheck

### How can we reproduce it (as minimally and precisely as possible)?

Service is of type - ClusterIP

Validate kube-proxy logs in kube-system

### Kubernetes version

Azure AKS 1.20.7

### Cloud provider

Azure AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
I think that this is a duplicate of 
https://github.com/kubernetes/kubernetes/issues/85499
It also has a  PR to fix it 
https://github.com/kubernetes/kubernetes/pull/92210

**Comment by aojea** [comment]
/triage accepted

I think we should remove that log line, is not meaningful

https://github.com/kubernetes/kubernetes/pull/92210#issuecomment-1007246642

**Comment by NikhilSharmaWe** [comment]
@aojea Just confirming, should I make a PR removing [this](https://github.com/kubernetes/kubernetes/pull/92210#discussion_r780119357) log line.

**Comment by zohebs341** [comment]
@aojea @NikhilSharmaWe Thank you 
It won’t print that line in next k8s version ? Like 1.21.7? Any specific version?

**Comment by aojea** [comment]
I have doubts that this qualifies for backporting, because it is only happening if the log level verbosity is 3 or higher, a verbosity level of 2 use to be the default IIRC. Also, It's not impacting any functionality also.

Not backporting this change means that this only be present in current version 1.24, for previous versions people can configure the kube-proxy loglevel verbosity to 2 or lower, and it will not log this messge.

@bridgetkromhout @aramase is there any way users can define the kube-proxy verbosity level to 2? any inconvenient for doing that?

**Comment by aramase** [comment]
For AKS (managed cluster), I just checked and the default log verbosity configured is 3 to enable debug logging. For self-managed Kubernetes cluster, I think users have control over the log verbosity but for managed by default verbose logging is enabled? 

Have we backported any similar logging changes before?

**Comment by aojea** [comment]
> For AKS (managed cluster), I just checked and the default log verbosity configured is 3 to enable debug logging. For self-managed Kubernetes cluster, I think users have control over the log verbosity but for managed by default verbose logging is enabled?
> 
> Have we backported any similar logging changes before?

@cpanato @saschagrunert WDYT about backporting this patch? ^^^

**Comment by cpanato** [comment]
> > For AKS (managed cluster), I just checked and the default log verbosity configured is 3 to enable debug logging. For self-managed Kubernetes cluster, I think users have control over the log verbosity but for managed by default verbose logging is enabled?
> > Have we backported any similar logging changes before?
> 
> @cpanato @saschagrunert WDYT about backporting this patch? ^^^

looks like is a log part, sgtm to backport

**Comment by aojea** [comment]
> looks like is a log part, sgtm to backport

@NikhilSharmaWe @aramase would you like to take care of the backports?

**Comment by aramase** [comment]
@NikhilSharmaWe Do you want to open the PRs for backport? If not, lmk and I can open them.

**Comment by NikhilSharmaWe** [comment]
@aramase I am really not sure what has to be done here, feel free to open the PR.

**Comment by aramase** [comment]
Open PRs for backport:
- https://github.com/kubernetes/kubernetes/pull/107484
- https://github.com/kubernetes/kubernetes/pull/107485
- https://github.com/kubernetes/kubernetes/pull/107486
