### ISSUE TITLE
Which pod(s) are using the PVC? (ouput as JSON/YAML)

### ISSUE THREAD

**Issue by nc-ruth** [kubernetes/kubernetes#107227]
### What would you like to be added?

AFAIK it is only possible to see which pods have mounted the PVC by using:
`kubectl describe pvc <PVC_NAME>`

![image](https://user-images.githubusercontent.com/41048990/147447061-938e1ce5-bc4b-4aed-8ce1-a3944a42ffc3.png)

The "kubectl describe pvc" command only outputs the information in a humanely readable manner, which is not ideal for scripts etc.

Would it be possible to show the same data (which reveals which Pods are using the PVC) by the "kubectl get pvc" command?
This could maybe be shown under the "status" property? 

![image](https://user-images.githubusercontent.com/41048990/147446547-d54d907d-b694-4cc4-a233-e29b4a7d58f6.png)

### Why is this needed?

Helps us locate which pods have mounted which PVC's in a easier manner.

**Comment by nc-ruth** [comment]
Please note, that in newer versions of kubectl, the property "Mounted By" is called "Used By".

**Comment by Kartik494** [comment]
Hi @nc-ruth can you please check with `kubectl get pods -o yaml` command. 
Thanks!!

**Comment by nc-ruth** [comment]
Hi @Kartik494, 

Thank you for your suggestion.
The suggestion you give will have us traverse all pods in a given namespace, for checking which PVC's are attached to it. 

The suggestion I have, is to get which pods directly from the PVC (using get pvc <pvc> -o yaml). 
Does it make sense?

Thank you
