### ISSUE TITLE
Can we control the subsequent actions after livenessProbe failed?  Not just restart container.

### ISSUE THREAD

**Issue by NoicFank** [kubernetes/kubernetes#107255]
### What would you like to be added?

1.  Add a gate to open/close the auto-action(restart container) after liveness probe failed. default as `open`. 
2.  Add an attribute `Healthy` in `ContainerStatus`， just like the `Started` and  `Ready` to specify whether the container has passed its liveness probe.
3. May add an attribute `ContainersHealthy` in `PodCondition` too, which reflect the healthy condition about the pod, just like `ContainersReady`.

Once we want to self control the action after liveness probe failed, we could close the gate (stop the auto action, which restart container automatically through the restartPolicy), and watch the `Healthy`(or  `ContainersHealthy`) property to do our actions.

### Why is this needed?

Currently, it will kill (restart) container automatically after the liveness probe failed (restart through `restartPolicy` ). It works in many cases,  especially stateless service. But in some cases, we do not want to kill(restart) container just because the liveness probe failed. 

For example, we want to run a distributed database service, and some times that liveness probe(Http) with database container may failed due to the unstable network. And in this case, the database container should not be killed automatically, 
since 1)the database container is healthy with high probability, 2)there are many data in this database container, that we destroy it is very expensive. Thus we want gather more information to make self decision.

we better know the result that  liveness probe has failed firstly, then we collect more information about this situation, consequently do our action to decide whether restart the container or not.

Ideally, we want to know the liveness probe with this container is failed firstly, and then we collect more information, like network, cpu, scripts, etc. then do our self action.

**Comment by redbaron** [comment]
I ended up removing liveness probes from all containers, especially statefull ones. I am yet to see a non hypothetical situation where conatiner restart prevented  downtime, but seen too many when it caused it.

**Comment by NoicFank** [comment]
> I ended up removing liveness probes from all containers, especially statefull ones. I am yet to see a non hypothetical situation where conatiner restart prevented downtime, but seen too many when it caused it.

yes, currently we don't use liveness probe, too. But we need a place to found whether the container is healthy or not (In fact, we need the liveness probe result, but we do not want the container to auto restart).

**Comment by redbaron** [comment]
> (In fact, we need the liveness probe result, but we do not want the container to auto restart).

If liveness probe is a network connection to an app, you can create a side container which probes main container and use restart even on a side container as a way to know that main container is in trouble

**Comment by NoicFank** [comment]
> > (In fact, we need the liveness probe result, but we do not want the container to auto restart).
> 
> If liveness probe is a network connection to an app, you can create a side container which probes main container and use restart even on a side container as a way to know that main container is in trouble

yeah, thanks for your advice. We do already take this way to get the healthy of container currently, and it's works. 

But I'm wonder could we control the actions after liveness failed, so we could use liveness probe to achieve our goal easily.
