### ISSUE TITLE
secret is created with clear text data 

### ISSUE THREAD

**Issue by contactpunit** [kubernetes/kubernetes#107281]
### What happened?

Hi,

I tried creating a secret with key under data section having plain text value. It was created successfully. In my understanding it should fail as its not base64 encoded.

Here is example:

[demo@kubemaster pods]$ cat sec1.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tryme
data:
  nameofsecret: manu

[demo@kubemaster pods]$ kubectl apply -f sec1.yaml
secret/tryme created

### What did you expect to happen?

i expected it to fail with 4: illegal base64 data at input 

### How can we reproduce it (as minimally and precisely as possible)?

you can use same yaml file as input

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
  Deployed on my local laptop
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
$ uname -a
Linux kubemaster.test.com 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Client: Docker Engine - Community
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:58 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:20 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by munnerz** [comment]
I think `manu` _is_ valid base64 data, it just decodes to not UTF-8/ASCII characters.. 🤔 so I believe this is working as intended?

Take a look here: https://www.base64decode.org/ and set the character set to "auto detect".

**Comment by Shubham82** [comment]
Hi @munnerz @contactpunit

I tried this yaml with a different word combination. For every 4 character word whether it contains only alphabets such as "**abcd**" or alphanumeric "**ab12**", the secret is created for them. But if the word is more or less than 4  it gives an error on creation.
So I think it is a bug. Four characters word is considered as base64-encoded strings.

For **abcd**
```
$ kubectl get secrets tryme -o yaml
apiVersion: v1
data:
  nameofsecret: abcd
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"nameofsecret":"abcd"},"kind":"Secret","metadata":{"annotations":{},"name":"tryme","namespace":"default"}}
  creationTimestamp: "2022-01-05T08:01:06Z"
  name: tryme
  namespace: default
  resourceVersion: "28041991"
  uid: 7407bb45-11f8-44bf-8a56-be0e56e88047
type: Opaque
```

For characters more than 4: 

> The request is invalid: patch: Invalid value: "map[data:map[nameofsecret:abcde] metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":{\"nameofsecret\":\"abcde\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"tryme\",\"namespace\":\"default\"}}\n]]]": error decoding from json: illegal base64 data at input byte 4

For characters lessthan 4: 

> The request is invalid: patch: Invalid value: "map[data:map[nameofsecret:abe] metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"v1\",\"data\":{\"nameofsecret\":\"abe\"},\"kind\":\"Secret\",\"metadata\":{\"annotations\":{},\"name\":\"tryme\",\"namespace\":\"default\"}}\n]]]": error decoding from json: illegal base64 data at input byte 0

**Comment by Shubham82** [comment]
Hi, @munnerz I think you are right. when I further tried with the words i.e multiple of 4 like 8, the secret is created for them.
I think this is how Base64 encoded works. In my investigation I found this:

```
Encoded data will always have the following characteristic:

The length of a Base64-encoded string is always a multiple of 4
Only these characters are used by the encryption: “A” to “Z”, “a” to “z”, “0” to “9”, “+” and “/”
The end of a string can be padded up to two times using the “=”-character (this character is allowed in the end only) 
```
This is due to misunderstanding the requirement to base64 encode data items.
Could you please provide more inputs so that it will more clear?

**Comment by ehashman** [comment]
The provided test case is valid base64:

```
ehashman@red-dot:~$ base64 -d > /dev/null
manu
ehashman@red-dot:~$ echo $?
0
```

This is working as expected.

/kind support
/close
