### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by sivaandyala765** [kubernetes/kubernetes#107268]
### What would you like to be added?

2021/12/31 13:40:37 [error] 13#13: *142993 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/awc-tracker/beneficiary/save HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"
2021/12/31 13:40:59 [error] 13#13: *141596 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/login HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"
2021/12/31 13:42:31 [error] 13#13: *144225 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /api/awc-tracker/beneficiary/save HTTP/1.1", upstream: "fastcgi://unix:///var/run/php-fpm.sock", host: "wcd_api"

### Why is this needed?

please give me solution for this error

**Comment by sivaandyala765** [comment]
@yliaog please help me

**Comment by aojea** [comment]
> "fastcgi://unix:///var/run/php-fpm.sock

this doesn't look like a kubernetes problem.

I encourage you to use other channels for looking for help, the github issues tracker is mostly for kubernetes bugs on the code base.

/close
