### ISSUE TITLE
Use a working example in the kubernetes 101 guide

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#10726]
We link to the 101 guide (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/walkthrough/README.md#volumes) from various getting started guides and it has a git-monitor example that can be confusing, since all you're going to end up with is:

```
POD       IP           CONTAINER(S)   IMAGE(S)                 HOST                         LABELS    STATUS                CREATED     MESSAGE
www       172.17.0.2                                           fed-minion1/10.240.187.175   <none>    Pending               3 seconds   
                       nginx          nginx                                                           Running *not ready*   2 seconds   
                       git-monitor    kubernetes/git-monitor                                          Waiting                           Error: image kubernetes/git-monitor:latest not found
```

Can we upload the git-monitor or change it to another working example? IMHO we shouldn't introduce volumes before labels,rcs and services. As soon as someone creates a new pod they most proabably want visual verification that it works. 

@brendanburns

**Comment by michelleN** [comment]
+1

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
This doc does not seem to exist anymore.
/close

**Comment by chenopis** [comment]
IMHO, since all the docs now live in the k8s.io repo, any docs issue pre-2017 should be closed.
