### ISSUE TITLE
There is an extra space in  kubelet search home docker.json dir 

### ISSUE THREAD

**Issue by tanguofu** [kubernetes/kubernetes#107202]
### What happened?

```
journalctl -u kubelet |grep looking
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059831  727393 config.go:144] looking for config.json at /var/lib/kubelet/config.json
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059849  727393 config.go:144] looking for config.json at /config.json
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059856  727393 config.go:144] looking for config.json at /root/ /.docker/config.json
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059862  727393 config.go:144] looking for config.json at /.docker/config.json
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059936  727393 config.go:110] looking for .dockercfg at /var/lib/kubelet/.dockercfg
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059948  727393 config.go:110] looking for .dockercfg at /.dockercfg
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059955  727393 config.go:110] looking for .dockercfg at /root/ /.dockercfg
Dec 23 15:59:00 node1 kubelet[727393]: I1223 15:59:00.059960  727393 config.go:110] looking for .dockercfg at /.dockercfg

```

and it is no used to set HOME env in `Environment`

### What did you expect to happen?

As the doc, kubetet should search  ~/.docker/config.json for docker auths, but There is an extra space in  kubelet search home docker.json dir ,  the docker auths take no effective ~

### How can we reproduce it (as minimally and precisely as possible)?

[root@node1 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
[root@node1 ~]# kubectl  version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Centos 7.9
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig node 
#106335 may be a result of this?

**Comment by matthyx** [comment]
I'd like to work on this one... (waiting for tonight's triage session)
/assign

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

@tanguofu can you please reply to this comment https://github.com/kubernetes/kubernetes/issues/107202#issuecomment-1000182274 and take a look at env?

**Comment by ehashman** [comment]
(specifically, run the `env` command and share the output here, but make sure you remove any secrets before pasting)

**Comment by tanguofu** [comment]
the output of `env|vim -`, with set list to see the white chars:
```
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;05;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.m4a=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.oga=38;5;45:*.opus=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:$
SSH_CONNECTION=..........$
LANG=en_US.UTF-8$
HISTCONTROL=ignoredups$
HOSTNAME=node1$
S_COLORS=auto$
XDG_SESSION_ID=59114$
USER=root$
GOPATH=/root/go$
PWD=/root$
HOME=/root$
SSH_CLIENT=............ $
SSH_TTY=/dev/pts/0$
MAIL=/var/spool/mail/root$
TERM=xterm-256color$
SHELL=/bin/bash$
TST_HACK_BASH_SESSION_ID=16112554272511817$
SHLVL=1$
LOGNAME=root$
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/0/bus$
XDG_RUNTIME_DIR=/run/user/0$
PATH=/usr/local/python-3.10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/.ft:/root/bin$
HISTSIZE=1000$
LESSOPEN=||/usr/bin/lesspipe.sh %s$
_=/usr/bin/env$
```

**Comment by matthyx** [comment]
@tanguofu is this `env` output from the node running kubelet? I find it strange to have GOPATH set on a prod machine...

**Comment by matthyx** [comment]
> https://pkg.go.dev/os#UserHomeDir it should use $HOME directly. If $HOME="/root/ ", it would be a problem.

Indeed... what's strange is that `filepath.Join` doesn't normalize elements before concat:
https://go.dev/play/p/jEWP9rQXy5-

**Comment by tanguofu** [comment]
yes,  the output of kubelet process 
```

[root@node1 ~]# ps eww -p 461070
    PID TTY      STAT   TIME COMMAND
 461070 ?        Ssl  221:18 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1 --node-ip=xxxx --hostname-override=node1 LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin INVOCATION_ID=80febd7b64b042949bf0a0441605d214 JOURNAL_STREAM=8:276790765 KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml KUBELET_EXTRA_ARGS=--node-ip=xxx  --hostname-override=node1  KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1
```

**Comment by matthyx** [comment]
> > https://pkg.go.dev/os#UserHomeDir it should use $HOME directly. If $HOME="/root/ ", it would be a problem.
> 
> Indeed... what's strange is that `filepath.Join` doesn't normalize elements before concat: https://go.dev/play/p/jEWP9rQXy5-

actually python's `os.path.join` does the same... no trim for joined elements

**Comment by matthyx** [comment]
> yes, the output of kubelet process
> 
> ```
> 
> [root@node1 ~]# ps eww -p 461070
>     PID TTY      STAT   TIME COMMAND
>  461070 ?        Ssl  221:18 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1 --node-ip=xxxx --hostname-override=node1 LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin INVOCATION_ID=80febd7b64b042949bf0a0441605d214 JOURNAL_STREAM=8:276790765 KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml KUBELET_EXTRA_ARGS=--node-ip=xxx  --hostname-override=node1  KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1
> ```
> 
> and i had check ` /etc/environment` `/etc/profile*` `/root/.bashrc` `/root/.profile` , there is no set HOME env var.

@tanguofu this is very weird, because the string `/root/ ` has to come somehow through the golang call `os.UserHomeDir()` which takes the `$HOME` env var.

How is kubelet started on your node?

**Comment by tanguofu** [comment]
> > yes, the output of kubelet process
> > ```
> > 
> > [root@node1 ~]# ps eww -p 461070
> >     PID TTY      STAT   TIME COMMAND
> >  461070 ?        Ssl  221:18 /usr/local/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1 --node-ip=xxxx --hostname-override=node1 LANG=en_US.UTF-8 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin INVOCATION_ID=80febd7b64b042949bf0a0441605d214 JOURNAL_STREAM=8:276790765 KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml KUBELET_EXTRA_ARGS=--node-ip=xxx  --hostname-override=node1  KUBELET_KUBEADM_ARGS=--cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=registry.cn-beijing.aliyuncs.com/kubesphereio/pause:3.4.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and i had check ` /etc/environment` `/etc/profile*` `/root/.bashrc` `/root/.profile` , there is no set HOME env var.
> 
> @tanguofu this is very weird, because the string `/root/ ` has to come somehow through the golang call `os.UserHomeDir()` which takes the `$HOME` env var.
> 
> How is kubelet started on your node?

it is started by systemd as follows:
```
[root@node1 ~]# cat /etc/systemd/system/multi-user.target.wants/kubelet.service
[Unit]
Description=kubelet: The Kubernetes Node Agent
Documentation=http://kubernetes.io/docs/

[Service]
ExecStart=/usr/local/bin/kubelet
Restart=always
StartLimitInterval=0
RestartSec=10

[Install]
WantedBy=multi-user.target
[root@node1 ~]# cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml"
# This is a file that "kubeadm init" and "kubeadm join" generate at runtime, populating the KUBELET_KUBEADM_ARGS variable dynamically
EnvironmentFile=-/var/lib/kubelet/kubeadm-flags.env
# This is a file that the user can use for overrides of the kubelet args as a last resort. Preferably, the user should use
# the .NodeRegistration.KubeletExtraArgs object in the configuration files instead. KUBELET_EXTRA_ARGS should be sourced from this file.
EnvironmentFile=-/etc/default/kubelet
Environment="KUBELET_EXTRA_ARGS=--node-ip=9.134.85.1 --hostname-override=node1 "
ExecStart=
ExecStart=/usr/local/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS
```

**Comment by matthyx** [comment]
I did some research during the weekend... .and I still cannot understand where it comes from.
(I still don't think it's a problem in kubelet code)

@tanguofu maybe you could try to override `HOME` and force it to `/root` ? At least that should fix your particular issue...
