### ISSUE TITLE
is v1.17 support APIPriorityAndFairness ?

### ISSUE THREAD

**Issue by zoux86** [kubernetes/kubernetes#107238]
What happened:
I am testing API Priority and Fairness. I launched it like this:

RUNTIME_CONFIG=flowcontrol.apiserver.k8s.io/v1alpha1=true FEATURE_GATES=APIPriorityAndFairness=true 

But kubectl erroneously told me no table handler registered for this type *flowcontrol.FlowSchemaList
```
$ kubectl get flowschema.flowcontrol.apiserver.k8s.io
Error from server: no table handler registered for this type *flowcontrol.FlowSchemaList
```

form this [repo](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml
), it seems APIPriorityAndFairness is supported after v1.18.  but we can still see  some APIPriorityAndFairness source code and FEATURE_GATES in v1.17.4. 

```
# The milestone at which this feature was, or is targeted to be, at each stage.
milestone:
  alpha: "v1.18"
  beta: "v1.20"
  stable: "v1.23"
```
```
 $ /usr/local/bin/kube-apiserver --version
Kubernetes v1.17.4-kube-apiserver-1226

Usage:
  kube-apiserver [flags]

Generic flags:

      --advertise-address ip
                The IP address on which to advertise the apiserver to members of the cluster. This address must be reachable by the rest of the cluster. If blank, the --bind-address will be used. If --bind-address is unspecified, the host's default interface will be
                used.
      --cloud-provider-gce-l7lb-src-cidrs cidrs
                CIDRs opened in GCE firewall for L7 LB traffic proxy & health checks (default 130.211.0.0/22,35.191.0.0/16)
      --cors-allowed-origins strings
                List of allowed origins for CORS, comma separated.  An allowed origin can be a regular expression to support subdomain matching. If this list is empty CORS will not be enabled.
      --default-not-ready-toleration-seconds int
                Indicates the tolerationSeconds of the toleration for notReady:NoExecute that is added by default to every pod that does not already have such a toleration. (default 300)
      --default-unreachable-toleration-seconds int
                Indicates the tolerationSeconds of the toleration for unreachable:NoExecute that is added by default to every pod that does not already have such a toleration. (default 300)
      --enable-inflight-quota-handler
                If true, replace the max-in-flight handler with an enhanced one that queues and dispatches with priority and fairness
      --external-hostname string
                The hostname to use when generating externalized URLs for this master (e.g. Swagger API Docs).
      --feature-gates mapStringBool
                A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
                APIListChunking=true|false (BETA - default=true)
                APIPriorityAndFairness=true|false (ALPHA - default=false)
                APIResponseCompression=true|false (BETA - default=true)
```

**questions:**

(1) is v1.17 support APIPriorityAndFairness ?
(2) if yes, how to run it

**Comment by pacoxu** [comment]
Feature Gate | Default | Stage |Since | Util 
-- | -- | -- |-- | -- 
APIPriorityAndFairness | false | Alpha | 1.17 | 1.19
APIPriorityAndFairness | true | Beta | 1.20

More details in https://github.com/kubernetes/enhancements/issues/1040 and #76846. 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/features/kube_features.go#L126-L131 The doc here and https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/1040-priority-and-fairness/kep.yaml#L35-L38 should be updated. #103934 
/cc @MikeSpreitzer @yue9944882

**Comment by MikeSpreitzer** [comment]
API Priority and Fairness did not reach alpha until release 1.18.  The FeatureGate went in much earlier, but we did not get the feature fully to alpha until 1.18.  I will submit updates to the erroneous information cited above.

**Comment by MikeSpreitzer** [comment]
I submitted https://github.com/kubernetes/kubernetes/pull/107316 to clarify the comment in `kube_features.go`.

I can not update the opening remark in https://github.com/kubernetes/enhancements/issues/1040, and that may be of mere historical interest.  @yue9944882 , what do you think?

**Comment by yue9944882** [comment]
@MikeSpreitzer sure thing i just corrected the misguiding line in the issue. let me know if there's anything else i need to fix!
