### ISSUE TITLE
Con todo respeto "Estoy en búsqueda de un developer en Kubernetes" 

### ISSUE THREAD

**Issue by Isma001** [kubernetes/kubernetes#107315]
Mi nombre es Ismael Hernández de la empresa Mejora Continua de México, mi puesto actual es Analista de Reclutamiento y Selección Sr. IT, dicho lo anterior les escribo amada red ya que actualmente contamos con una vacante muy interesante en el área IT el puesto como tal es “experto en Kubernetes” donde estarás realizando las actividades siguientes: 

•	Desarrollo y creación de un nuevo software en Kubernetes,  docker, Kafka adicional Java, JS y/o CSS 
•	Investigación, planeación y explicar (consultor) al equipo de trabajo el desarrollo en Kubernetes,  docker y Kafka
•	Guardar información en contenedores docker
•	Generación de ideas nuevas para el desarrollo de nuevo sortware 
•	Trabajar con plataforma Mendix  
•	Dispuesto a viajar a diferentes países

Las oficinas centrales se encuentran en la CDMX, el salario depende mucho de la experiencia y conocimientos, estamos abiertos a escuchar alguna propuesta de parte tuya, los beneficios son muchos como crecimiento laboral, capacitaciones, cursos  y adquisición de nuevos conocimientos. 

Viajaras  a lo largo del continente Americano (después de aproximadamente un año), de igual forma tendrás cursos de capacitación y aprendizaje continuo, crecimiento dentro de la empresa y lo mejor de todo contrato directo por la empresa.

 

Me gustaría platicarte un poco más acerca de la vacante y de igual forma ME COMPARTIERAS TU CV POR ESTE MEDIO O ALGÚN NÚMERO PARA PODER CONTACTARTE , MEJOR AUN TE DEJO MI NÚMERO DE WHATSAPP PARA QUE ME PUEDAS ESCRIBIR 5554511364. 

Por favor contáctame  

Saludos y quedo atento.

**Comment by aojea** [comment]
@Isma001 este no es realmente ni el lugar ni la manera
