### ISSUE TITLE
Migrate `component-base` to use Lease API

### ISSUE THREAD

**Issue by acumino** [kubernetes/kubernetes#107301]
### What would you like to be added?

[component-base](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base) is currently using endpoints . We want to migrate this to endpointsleases and finally to leases.

### Why is this needed?

Support for endpoints and configmaps is removed in K8s 1.24 with kubernetes/kubernetes#106852.
More details about the motivation to switch to leases - ref kubernetes/kubernetes#80289.

To preserve the backwards-compatibility, resource lock for migration purposes (endpointsleases, configmapsleases) should be used when switching from the legacy resource locks (endpoints, configmaps)

**Comment by liggitt** [comment]
are you referring to the RecommendedDefaultLeaderElectionConfiguration function? all built-in callers of that method override to use `leases`

in my opinion, `RecommendedDefaultLeaderElectionConfiguration` should not silently change the resource lock value

**Comment by acumino** [comment]
Yes
> are you referring to the RecommendedDefaultLeaderElectionConfiguration function? all built-in callers of that method override to use `leases`


Since support for endpoints and configmaps is removed in K8s 1.24 and by default `RecommendedDefaultLeaderElectionConfiguration` sets the resource lock value to `endpoints` so any components which are using this function and not overriding the resource lock value will have issues. As we are already at K8s 1.23 I think this is the correct time to move this also to `leases` in a step-wise manner.

> in my opinion, `RecommendedDefaultLeaderElectionConfiguration` should not silently change the resource lock value... it could stop setting it and make callers choose their resource lock type

**Comment by liggitt** [comment]
> As we are already at K8s 1.23 I think this is the correct time to move this also to `leases` in a step-wise manner.

It would be better to stop setting the value and make consumers choose what to set. Their release cadences might not align with client-go tags, so we can't move to endpointsleases in client-go v0.24.0 and leases in v0.25.0 and know we're safely transitioning consumers

**Comment by acumino** [comment]
Are you suggesting that there shouldn't be any default value of resource lock? I am not sure.
> It would be better to stop setting the value and make consumers choose what to set. Their release cadences might not align with client-go tags, so we can't move to endpointsleases in client-go v0.24.0 and leases in v0.25.0 and know we're safely transitioning consumers

What should be the steps to migrate resource lock to leases then to get the surety that we're safely transitioning consumers?

**Comment by liggitt** [comment]
> Are you suggesting that there shouldn't be any default value of resource lock? I am not sure.
> 
> >

yes

> What should be the steps to migrate resource lock to leases then to get the surety that we're safely transitioning consumers?

it's on the consumer to step to endpointsleases, release, then step to leases, and release

**Comment by acumino** [comment]
I think then I  can close this issue and create a new one with the requirement that there shouldn't be any default value of resource lock in `RecommendedDefaultLeaderElectionConfiguration` function so the user needs to set it every time.
> > Are you suggesting that there shouldn't be any default value of resource lock? I am not sure.
> > >
> 
> yes

**Comment by acumino** [comment]
Close in favor of #107313
