### ISSUE TITLE
Apiserver is not in ready state, however other control components are all in good state

### ISSUE THREAD

**Issue by geotransformer** [kubernetes/kubernetes#107320]
### What happened?

**ubuntu@-data-master-3:~$ curl -k https://10.192.1.24:6443/readyz**

[+]ping ok

[+]log ok

[+]etcd ok

**_[-]informer-sync failed: reason withheld_**

[+]poststarthook/start-kube-apiserver-admission-initializer ok

[+]poststarthook/generic-apiserver-start-informers ok

[+]poststarthook/priority-and-fairness-config-consumer ok

[+]poststarthook/priority-and-fairness-filter ok

[+]poststarthook/start-apiextensions-informers ok

[+]poststarthook/start-apiextensions-controllers ok

[+]poststarthook/crd-informer-synced ok

[+]poststarthook/bootstrap-controller ok

[+]poststarthook/rbac/bootstrap-roles ok

[+]poststarthook/scheduling/bootstrap-system-priority-classes ok

[+]poststarthook/priority-and-fairness-config-producer ok

[+]poststarthook/start-cluster-authentication-info-controller ok

[+]poststarthook/aggregator-reload-proxy-client-cert ok

[+]poststarthook/start-kube-aggregator-informers ok

[+]poststarthook/apiservice-registration-controller ok

[+]poststarthook/apiservice-status-available-controller ok

[+]poststarthook/kube-apiserver-autoregistration ok

[+]autoregister-completion ok

[+]poststarthook/apiservice-openapi-controller ok

[+]shutdown ok

readyz check failed

kubectl describe pod

Warning Unhealthy 3m18s (x4315492 over 49d) kubelet Readiness probe failed: HTTP probe failed with statuscode: 500

### What did you expect to happen?

More specific error message.  

### How can we reproduce it (as minimally and precisely as possible)?

Not sure how to reproduce it

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Kubernetes version:1.16.2
Cloud being used: Openstack
Installation method: Kubeadm
Host OS: Ubuntu
CNI and version: Calico 3.2
CRI and version: Docker 18.9

### Cloud provider

<details>

</details>

Openstack

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Ubuntu 18.04

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
Calico

**Comment by pacoxu** [comment]
/sig auth
(I still does not get why this is a bug)

**Comment by geotransformer** [comment]
> /sig auth (I still does not get why this is a bug)

[-]informer-sync failed: reason withheld  

Any idea why put the reason withheld?

**Comment by geotransformer** [comment]
> nformer-sync

**Comment by geotransformer** [comment]
> > /sig auth (I still does not get why this is a bug)
> 
> [-]informer-sync failed: reason withheld
> 
> Any idea why put the reason withheld?

I found this in the change history, it was  fix a bug - 
```
Extend kube-apiserver /readyz with new "informer-sync" check ensuring that internal informers are synced. ([#92644](https://github.com/kubernetes/kubernetes/pull/92644), [@wojtek-t](https://github.com/wojtek-t)) [SIG API Machinery and Testing]

**Comment by liggitt** [comment]
/remove-sig auth

You might be able to get more details from `/readyz/informer-sync`, or by checking the apiserver log.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

Note that 1.16 is not a supported version of Kubernetes.

/remove-kind bug
/kind support
/close

**Comment by geotransformer** [comment]
> Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).
> 
> Note that 1.16 is not a supported version of Kubernetes.
> 
> /remove-kind bug /kind support /close

Opened this thread in the discussion a while ago. 
https://discuss.kubernetes.io/t/apiserver-is-not-in-ready-state/18384

**Comment by geotransformer** [comment]
apiserver.log

E0128 01:31:16.171494       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Secret: failed to list *v1.Secret: Internal error occurred: unable to transform key "/registry/secrets/xxxxxxx/xxxxxxx-sa-token-dzhkb": invalid padding on input
E0128 01:32:15.205679       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Secret: failed to list *v1.Secret: Internal error occurred: unable to transform key "/registry/secrets/xxxxxxx/xxxxxxx-sa-token-dzhkb": invalid padding on input
E0128 01:33:10.812107       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Secret: failed to list *v1.Secret: Internal error occurred: unable to transform key "/registry/secrets/xxxxxxx/xxxxxxx-sa-token-dzhkb": invalid padding on input

**Comment by geotransformer** [comment]
kubectl delete the secret, but the new secret still causes problem

cacher.go:419] cacher (*core.Secret): unexpected ListAndWatch error: failed to list *core.Secret: unable to transform key "/registry/secrets/xxxx/xxxxxx-sa-token-d28wj": invalid padding on input; reinitializing...
