### ISSUE TITLE
goroutine leaks in several tests

### ISSUE THREAD

**Issue by songlh** [kubernetes/kubernetes#107372]
### What happened?

Similar to #107191, goroutines associated with QueueBroadcaster and EventWatcher are leaked in the following tests: 

1. `TestAllocateOrOccupyCIDRSuccess()` at [line 321](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodeipam/ipam/range_allocator_test.go#L321) of pkg/controller/nodeipam/ipam/range_allocator_test.go

2. `TestDaemonSetUpdatesNoTemplateChanged()`  at [line 336](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/daemon/update_test.go#L336) of pkg/controller/daemon/update_test.go

3. ` TestRepair()` at [line 55](https://github.com/kubernetes/kubernetes/blob/master/pkg/registry/core/service/ipallocator/controller/repair_test.go#L55) of pkg/registry/core/service/ipallocator/controller/repair_test.go

4. `TestDeploymentController_cleanupDeploymentOrder()` at [line 452](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/sync_test.go#L452) of pkg/controller/deployment/sync_test.go

5. `TestUpdatePods()` at [line 681](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/replicaset/replica_set_test.go#L681) of pkg/controller/replicaset/replica_set_test.go

6. `TestSyncDeploymentCreatesReplicaSet()` at [line 269](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller_test.go#L269) of pkg/controller/deployment/deployment_controller_test.go

7. `TestMultipleServiceChanges()` at [line 2209](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller_test.go#L2209) of pkg/controller/endpoint/endpoints_controller_test.go

Moreover, `TestMultipleServiceChanges()` can trigger a runtime panic by sending a message to a closed channel. The buggy channel is `blockNextAction`. The send operation is at [line 175](https://github.com/kubernetes/kubernetes/blob/6845df17290505ad6d989463f5bca2fbbd619c03/pkg/controller/endpoint/endpoints_controller_test.go#L175)  in `func makeBlockingEndpointDeleteTestServer()`. The close operation is at [line 2265](https://github.com/kubernetes/kubernetes/blob/6845df17290505ad6d989463f5bca2fbbd619c03/pkg/controller/endpoint/endpoints_controller_test.go#L2265)  in `TestMultipleServiceChanges()` 

### What did you expect to happen?

no goroutine leaks

### How can we reproduce it (as minimally and precisely as possible)?

run those unit tests

### Kubernetes version

all versions after 97d40890d00acf721ecabb8c9a6fec3b3234b74b

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
reported leaks seem to be in apps / network owned controllers.

/sig apps network

**Comment by astoycos** [comment]
I've made pretty good progress here for the sig-net related tests, Just stuck on. `TestMultipleServiceChanges` since the test is actually pretty broken/complicated so trying to get it working again

**Comment by astoycos** [comment]
I was able to fix all the unit test related orphaned go-routines, however throughout the codebase the following go-routine is always leaked 

```
        [Goroutine 21 in state chan receive, with k8s.io/klog/v2.(*loggingT).flushDaemon on top of the stack:
        goroutine 21 [chan receive]:
        k8s.io/klog/v2.(*loggingT).flushDaemon(0x0)
                /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1283 +0x6a
        created by k8s.io/klog/v2.init.0
                /home/astoycos/go/src/github.com/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:420 +0xfb
```

The fix for that is being tracked in https://github.com/kubernetes/klog/issues/282

**Comment by astoycos** [comment]
/remove-lifecycle stale this is still a WIP

**Comment by astoycos** [comment]
/remove-lifecycle stale 


I'm still working on this
