### ISSUE TITLE
Kubectl deleting of a namespace is always stuck

### ISSUE THREAD

**Issue by Dani-Ionescu** [kubernetes/kubernetes#107388]
### What happened?

I am encountering a very weird issue. Every time when I try to create a new namespace using ```kubectl create namespace xx``` then when I try to delete it, the operation becomes stuck:

```
[root@k8s-master-node ~]# kubectl delete namespace xx2
namespace "xx2" deleted
```
If I press CTRL+C the namespace remains in Terminating state. Any ideas?

### What did you expect to happen?

The namespace xx2 should be deleted.

### How can we reproduce it (as minimally and precisely as possible)?

No idea. 

### Kubernetes version

[root@k8s-master-node ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Internal cloud

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
By default, kubectl delete waits until the deleted object is removed from the API before returning (can short-circuit this with `--wait=false`)

Issuing a namespace delete request marks the namespace for deletion, but must be processed by the namespace deletion controller before it is removed from the API

The namespace deletion controller ensures all resources listed in discovery are deleted from the namespace before deleting the namespace itself. If you have unavailable aggregated APIs that cause discovery to fail, or cause list/delete requests to the aggregated resources to fail, the namespace will remain in a pending-deletion state until the aggregated API is available again.

This command will check discovery and show any resources still associated with the namespace:
```
kubectl get "$(kubectl api-resources --verbs=list --namespaced -o name | sed -z 's/\n/,/g;s/,$//')" -n $NAMESPACE
```

Does that reveal any remaining resources? If so, investigating why those are not being removed would be the next step.

**Comment by Dani-Ionescu** [comment]
Hello @liggitt ,

No, I do not populate the namespace with anything. 

`[root@k8s-master-node ~]# kubectl create namespace dad
namespace/dad created
[root@k8s-master-node ~]# kubectl get pods -n dad
No resources found in dad namespace.
[root@k8s-master-node ~]# kubectl delete namespace dad
namespace "dad" deleted
^C
[root@k8s-master-node ~]# kubectl get namespaces dad
NAME   STATUS        AGE
dad    Terminating   34s
`

**Comment by liggitt** [comment]
> No, I do not populate the namespace with anything.

whether or not you've populated the namespace with anything doesn't matter... the namespace controller has to *verify* no instances of any resources are in the namespace, so all APIs must be reachable. did the example command in https://github.com/kubernetes/kubernetes/issues/107388#issuecomment-1006803606 complete successfully?

**Comment by liggitt** [comment]
also, if you get the namespace, are there any details in namespace status to indicate why the controller isn't cleaning it up? `kubectl get namespace $namespace -o yaml`

**Comment by Dani-Ionescu** [comment]
Hm interesting:

```
[root@k8s-master-node ~]# kubectl get "$(kubectl api-resources --verbs=list --namespaced -o name | sed -z 's/\n/,/g;s/,$//')" -n dad2
error: unable to retrieve the complete list of server APIs: projectcalico.org/v3: the server is currently unable to handle the request
NAME                         DATA   AGE
configmap/kube-root-ca.crt   1      11s

NAME                         TYPE                                  DATA   AGE
secret/default-token-d5kn2   kubernetes.io/service-account-token   3      12s

NAME                     SECRETS   AGE
serviceaccount/default   1         12s

```

**Comment by liggitt** [comment]
> error: unable to retrieve the complete list of server APIs: projectcalico.org/v3: the server is currently unable to handle the request

Bingo.

**Comment by Dani-Ionescu** [comment]
Thx a lot, I will investigate more.

**Comment by liggitt** [comment]
Sounds good

/close
