### ISSUE TITLE
goroutine leak in TestFailureOutput

### ISSUE THREAD

**Issue by songlh** [kubernetes/kubernetes#107368]
### What happened?

When executing `TestFailureOutput()`, no message is sent to channel `c` created in  `func (runner *SpecRunner) registerForInterrupts(signalRegistered chan struct{})`. Thus, the goroutine ([line 60](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go#L60)) created in `func (runner *SpecRunner) Run() bool` blocks at a receive operation ([line 223](https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/onsi/ginkgo/internal/specrunner/spec_runner.go#L223))endlessly. 

### What did you expect to happen?

no goroutine leak

### How can we reproduce it (as minimally and precisely as possible)?

execute TestFailureOutput()

### Kubernetes version

all versions after 97d40890d00acf721ecabb8c9a6fec3b3234b74b

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> When executing TestFailureOutput()

this is in the framework:
https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/test/e2e/framework/log_test.go#L75

/sig testing
/area e2e-test-framework
