### ISSUE TITLE
ip release failed, resulting in ip leak

### ISSUE THREAD

**Issue by silenceper** [kubernetes/kubernetes#107371]
### What happened?

cni ip release failed, resulting in ip leak。
kubelet error log:
```
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.698648   13878 kubelet_pods.go:918] Pod "test-pod-0_test(3fc32306-691d-11ec-9454-3ce1a176ae1a)" is terminated, but some containers have not been cleaned up: {ID:{Type:docker ID:fef8d4f77de89a0e0409e5d96a3ea20fd20e905dbf9ffd27cf6a63261c58493a} Name:podip State:exited CreatedAt:2021-12-30 11:31:12.043154618 +0800 CST StartedAt:2021-12-30 11:31:12.10734396 +0800 CST FinishedAt:2021-12-30 11:31:12.164605269 +0800 CST ExitCode:2 Image:xxx.com/public/podip:latest ImageID:docker-pullable://xxx.com/public/podip@sha256:6835f4d8d3945857efcb25a10853a268c04cb12261d7d7e5a6feae60a10ac14f Hash:1539027646 RestartCount:10 Reason:Error Message: Resources:&ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},}}
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.703090   13878 kubelet_pods.go:1091] Killing unwanted pod "test-pod-0"
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.704880   13878 kubelet_pods.go:1734] Orphaned pod "3fc32306-691d-11ec-9454-3ce1a176ae1a" found, removing pod cgroups
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.707540   13878 pod_container_manager_linux.go:219] Attempt to kill process with pid: 85946
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.707560   13878 pod_container_manager_linux.go:219] Attempt to kill process with pid: 85973
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.707587   13878 pod_container_manager_linux.go:226] successfully killed all unwanted processes.
Dec 30 11:35:18  start_kubelet.sh: I1230 11:35:18.712878   13878 manager.go:1102] Destroyed container: "/kubepods/pod3fc32306-691d-11ec-9454-3ce1a176ae1a/f2fbdec1ddba337c384c27a398fc1a4cd2223e2ed26943692551e27446509921" (aliases: [k8s_POD_test-pod-0_test_3fc32306-691d-11ec-9454-3ce1a176ae1a_0 f2fbdec1ddba337c384c27a398fc1a4cd2223e2ed26943692551e27446509921], namespace: "docker")
Dec 30 11:35:18  start_kubelet.sh: E1230 11:35:18.716767   13878 remote_runtime.go:132] StopPodSandbox "f2fbdec1ddba337c384c27a398fc1a4cd2223e2ed26943692551e27446509921" from runtime service failed: rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod "test-pod-0_test" network: Multus: error in invoke Delegate del - "flannel": failed to Statfs "/proc/85946/ns/net": no such file or directory
Dec 30 11:35:18  start_kubelet.sh: E1230 11:35:18.716917   13878 kuberuntime_manager.go:930] Failed to stop sandbox {"docker" "f2fbdec1ddba337c384c27a398fc1a4cd2223e2ed26943692551e27446509921"}
Dec 30 11:35:18  start_kubelet.sh: E1230 11:35:18.716946   13878 kubelet_pods.go:1094] Failed killing the pod "test-pod-0": failed to "KillPodSandbox" for "3fc32306-691d-11ec-9454-3ce1a176ae1a" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"test-pod-0_test\" network: Multus: error in invoke Delegate del - \"flannel\": failed to Statfs \"/proc/85946/ns/net\": no such file or directory"


```

The process is killed during the pod cleaning phase, so the /proc/85946/ns/net file does not exist,should cni block this error.   

### What did you expect to happen?

delete pod success

### How can we reproduce it (as minimally and precisely as possible)?

Occasionally

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Kubernetes v1.14.10

### Cloud provider

<details>

</details>
none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>
Client:
 Version:      1.12.10
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   8fdb9a3
 Built:        Mon Dec 14 01:57:27 2020
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.10
 API version:  1.24
 Go version:   go1.7.5
 Git commit:   8fdb9a3
 Built:        Mon Dec 14 01:57:27 2020
 OS/Arch:      linux/amd64

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lixiaobing1** [comment]
It seems there is problem in NetworkPlugin cni, look at the status of cni.

**Comment by silenceper** [comment]
I actually have a question about the pod cleanup process. The pod sandbox is up here, indicating that the ip has been added correctly.

When the pod is deleted and cleaned up, all processes in the cgroup will be cleaned up and killed. It will naturally exit at `/proc/%v/ns/net`. Then there will be problems when it is passed to the cni plug-in?

Still expect the cni plug-in to block this error, so the ip will not be released naturally?

**Comment by dcbw** [comment]
@silenceper yes, this is a problem in the CNI plugin. CNI plugins are required to be resilient on delete, and still clean things like IP allocations up even when other parts of cleanup fail. In this case, the bug should lie with flannel. Let's close this Kube issue and follow up with the CNI one. Thanks!
/close
