### ISSUE TITLE
goroutine leaks in TestWatchFileChanged()

### ISSUE THREAD

**Issue by songlh** [kubernetes/kubernetes#107396]
### What happened?

If any t.Fatalf() in `func expectUpdate` ([line 363](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file_linux_test.go#L363) of file pkg/kubelet/config/file_linux_test.go) is triggered, the following send operation on channel ch (or [channel updates](https://github.com/kubernetes/kubernetes/blob/6845df17290505ad6d989463f5bca2fbbd619c03/pkg/kubelet/config/file.go#L78)) blocks child goroutines forever. 

### What did you expect to happen?

no goroutine leaks happen

### How can we reproduce it (as minimally and precisely as possible)?

run TestWatchFileChanged()

### Kubernetes version

all versions after 97d40890d00acf721ecabb8c9a6fec3b3234b74b

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> If any t.Fatalf() in func expectUpdate (line 363 of file pkg/kubelet/config/file_linux_test.go) is triggered, the following send operation on channel ch (or channel updates) blocks child goroutines forever.

reported location is in kubelet.

/sig node

**Comment by 249043822** [comment]
t.Fatalf() will exit current process, any problem?

**Comment by songlh** [comment]
@249043822 t.Fatalf() only terminates one goroutine.

**Comment by gjkim42** [comment]
I think the goroutines leak anyway regardless of closed channel, and kubelet does not need to clean up those goroutines except for tests.

/remove-triage accepted

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind failing-test

It looks like a test issue, reclassifying.
