### ISSUE TITLE
client-go fake: UpdateStatus mutates spec

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#107319]
### What happened?

Calling UpdateStatus with fake client-go mutates spec

### What did you expect to happen?

UpdateStatus only mutates status, like with real client

### How can we reproduce it (as minimally and precisely as possible)?

```
package gateway

import (
	"context"
	"testing"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func TestUpdateStatus(t *testing.T) {
	f := fake.NewSimpleClientset()
	f.CoreV1().Pods("default").Create(
		context.Background(),
		&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{Name: "test-pod"},
			Spec:       corev1.PodSpec{NodeName: "test-node"},
		},
		metav1.CreateOptions{},
	)
	pod, _ := f.CoreV1().Pods("default").Get(context.Background(), "test-pod", metav1.GetOptions{})
	t.Log(pod.Spec.NodeName)
	f.CoreV1().Pods("default").UpdateStatus(
		context.Background(),
		&corev1.Pod{
			ObjectMeta: metav1.ObjectMeta{Name: "test-pod"},
		},
		metav1.UpdateOptions{},
	)
	pod, _ = f.CoreV1().Pods("default").Get(context.Background(), "test-pod", metav1.GetOptions{})
	t.Log(pod.Spec.NodeName)
}
```

Result:
```
=== RUN   TestUpdateStatus
    kube_fake_test.go:23: test-node
    kube_fake_test.go:32: 
--- PASS: TestUpdateStatus (0.00s)
```

### Kubernetes version

<details>

k8s.io/client-go v0.22.4

</details>

### Cloud provider

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
there's a lot of server-side behaviors that the fake client doesn't do (like generating uids, updating resourceVersions, applying defaulting, and enforcing spec/status limitations)... the standard answer if you're wanting to exercise those behaviors is to register a reactor that does that

**Comment by liggitt** [comment]
Changing this from bug to feature, since it's asking to add endpoint-specific server-side logic into fake clients.

**Comment by fedebongio** [comment]
@MadhavJivrajani are you planning to work on this one? Thank you!

**Comment by MadhavJivrajani** [comment]
Hey @fedebongio,
Yes, I was hoping to work on this - however i won't be able to hit the ground running, if this is of importance and someone with more context is willing to take it up, please feel free to assign them!

**Comment by MadhavJivrajani** [comment]
@fedebongio unassigning myself due to lack of bandwidth, will try and take a look post enhancement freeze in case someone hasn't already picked it up. Sorry!
/unassign

**Comment by mason1kwok** [comment]
> Changing this from bug to feature, since it's asking to add endpoint-specific server-side logic into fake clients.

this is a big update, it must change this logic https://github.com/kubernetes/kubernetes/blob/2f64227aeab46ab77de4b996a4ce63209295de60/staging/src/k8s.io/client-go/testing/fixture.go#L121

as you see, it is the fake client basic method. 
needs some help or suggestions.

**Comment by haoruan** [comment]
I’d like to help 
/assign
