### ISSUE TITLE
kubernetes issues with pull images from docker

### ISSUE THREAD

**Issue by dominbdg** [kubernetes/kubernetes#107340]
Hello,
From couple of days I have below issue, 
I have pod failed so I wanted to kubectl apply -f with yml file.
Normally this file was working fine.

Right now I see error: Init:ImagePullBackOff
I see below error description:
`Failed to pull image "busybox": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout`

I don't know how to resolve this issue - it is probably something with relation between docker host and k8s

Can someone help me please ?

**Comment by ehashman** [comment]
Hello @dominbdg, you have not provided enough information to debug this issue. Please fill out the full issue template: https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.yaml

Thanks!

/close
