### ISSUE TITLE
Migrate `component-base` to use Lease API

### ISSUE THREAD

**Issue by acumino** [kubernetes/kubernetes#107313]
### What would you like to be added?

[component-base](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-base) is currently using default resource lock `endpoints`. As we want to migrate all the resource lock to leases. 

We no more want to set the default value of resource lock and let consumers choose what to set. Their release cadences might not align with client-go tags, so we can't move to endpointsleases and then leases and know we're safely transitioning consumers instead it's on the consumer to step to endpointsleases, release, then step to leases, and release.

More details about the motivation to not set the default value of resource lock - ref #107301

CC - @liggitt 

### Why is this needed?

Support for endpoints and configmaps is removed in K8s 1.24 with #106852.
More details about the motivation to switch to leases - ref #80289.

**Comment by wojtek-t** [comment]
For v1beta1 this is already happening in https://github.com/kubernetes/kubernetes/pull/105448/files

I think that for v1alpha1, given it's already existing, we can't change the default (as it's backward incompatible change).
@liggitt - thoughts?

**Comment by liggitt** [comment]
> I think that for v1alpha1, given it's already existing, we can't change the default (as it's backward incompatible change).

if compiled against current client-go, it will error, so it's only a matter of where we get the error and how useful the message is

**Comment by acumino** [comment]
> > I think that for v1alpha1, given it's already existing, we can't change the default (as it's backward incompatible change).
> 
> if compiled against current client-go, it will error, so it's only a matter of where we get the error and how useful the message is

What to expect with v1alpha1?

**Comment by acumino** [comment]
> For v1beta1 this is already happening in https://github.com/kubernetes/kubernetes/pull/105448/files
> 
> I think that for v1alpha1, given it's already existing, we can't change the default (as it's backward incompatible change). @liggitt - thoughts?

Since this PR #105448 is closed and the PR which supersede it  #105797 is not tackling this issue. I think we should actively pursue this issue. WDYT?
