### ISSUE TITLE
restart container failed, report Error response from daemon: cannot join network of a non running container

### ISSUE THREAD

**Issue by Jeaniowang** [kubernetes/kubernetes#107308]
### What happened?

when we excute docker stop container, and excuet docker start container, meet the error accidentally, 
we Tested, the problem probability about 10%，the log as follows:

[StartContainer "88b573825e2f948b112279c91d0a9134c105c02c31401c2e0d8c7f06502d0523" from runtime service failed: rpc error: code = Unknown desc = failed to start container "88b573825e2f948b112279c91d0a9134c105c02c31401c2e0d8c7f06502d0523": Error response from daemon: cannot join network of a non running container: 3fc5378eb60979f1ba3b5b2857ea09eef54dcf25d31445369d2ee873c94253d0]

we looked up the same issue, https://github.com/kubernetes/kubernetes/issues/44298, but it did not solve our problem.

### What did you expect to happen?

excute docker start successfully.

### How can we reproduce it (as minimally and precisely as possible)?

excute docker stop container, and excuet docker start container.

### Kubernetes version

<details>

v1.19.3

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

v1.19.3

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Jeaniowang** [comment]
报告收到

**Comment by Jeaniowang** [comment]
报告收到

**Comment by ehashman** [comment]
1.19 is not a supported version of Kubernetes. Can you reproduce this on version 1.20-1.23?

This bug doesn't seem to have enough details to reproduce or further investigate. You must include kubelet logs and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Once more details are provided, the bug will be accepted.

/triage needs-information
/sig node

**Comment by Jeaniowang** [comment]
报告收到

**Comment by Jeaniowang** [comment]
报告收到

**Comment by Jeaniowang** [comment]
报告收到
