### ISSUE TITLE
kubectl cp with --retries=-1 throws error

### ISSUE THREAD

**Issue by linastehle** [kubernetes/kubernetes#107333]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

**What happened:**
Trying to copy a large file from a container via kubectl cp with the new `--retries` flag results in the following error: 

```
➜  k cp namespace/pod:/usr/path/to/logs/diagnostics.tgz ./diagnostics.tgz  --retries=-1
tar: Removing leading `/' from member names
Resuming copy at 45182976 bytes, retry 0/-1
tar: Removing leading `/' from member names
error: archive/tar: invalid tar header
```

I executed the following command:
```
k cp namespace/pod:/usr/path/to/logs/diagnostics.tgz ./somedir/diagnostics.tgz  --retries=-1
```

EDIT:
The command executes and the file is copied. However, the resulting file is somehow corrupted:

```
➜  tar -zxf diagnostics.tgz

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```
However, the files have exactly the same size locally and on the pod:
```
# on the pod
-rw-rw-rw-. 1 appuser 1337 32556231 Jan 17 16:20 diagnostics.tgz

# locally
-rw-r--r--  1 me users 32556231 Jan 17 17:22 diagnostics.tgz
```
Also, the `kubectl cp`command exits with non-zero code and thus scripts may stop or abort at this point.

**What you expected to happen:**

- The large file to be downloaded from the container completely and unharmed.
- Exit code 0 only if copy was successful

**How to reproduce it (as minimally and precisely as possible):**

- Add a large file (mine was ~150M) to any location in the pod (preferrably a tar file). 
- Execute kubectl cp to download the large file and use the `--retries=-1` flag.
- Try to untar the resulting file

Anything else we need to know?:
Related to Issue [#60140](https://github.com/kubernetes/kubernetes/issues/60140).
I only experience this issue if I see kubectl doing at least one retry.

Environment:

    Kubernetes version (use kubectl version): server v1.20.12, client v1.23.1
    Cloud provider or hardware configuration: AWS
    OS (e.g. from /etc/os-release):
    Kernel (e.g. uname -a):
    Install tools: 
    Others:

**Comment by lixiaobing1** [comment]
tar: Removing leading `/' from member names
so cancel first "/" from "/usr/path/to/logs/diagnostics.tgz"
like this:
k cp namespace/pod:usr/path/to/logs/diagnostics.tgz ./diagnostics.tgz  --retries=-1

**Comment by linastehle** [comment]
Thanks for the hint. The warning `tar: Removing leading `/' from member names` is a [known issue](https://github.com/kubernetes/kubernetes/issues/58692) and I was just ignoring it in my case.
This issue is about the error message `error: archive/tar: invalid tar header` and the command exiting with a non-zero exit code.

**Comment by linastehle** [comment]
I just updated the issue description, we see the tar files being corrupted after kubectl did at least one retry

**Comment by brianpursley** [comment]
https://github.com/kubernetes/kubernetes/blob/00b528cdf42ae4c1771f3a51c557a1f289701113/staging/src/k8s.io/kubectl/pkg/cmd/cp/cp.go#L390-L391

**Comment by atiratree** [comment]
> Is it correct to start at position bytesRead+1? Or should this be bytesRead instead?

@brianpursley It should be correct since the byte start of tail (part of implementaion of initReadFrom) and bytes read match. Meaning that when we read 10 bytes we want to start reading 11th one.

The actual problem was that we were running a wrong command when -1 retries is used: please see https://github.com/kubernetes/kubernetes/pull/108748
