### ISSUE TITLE
kubectl needs better cluster-info and switching cluster functionality

### ISSUE THREAD

**Issue by Kielan** [kubernetes/kubernetes#10735]
1. Currently Kubectl cluster-info only returns where the kubernetes master is currently running and no other information.
2. Not apparent how to switch cluster or delete the current cluster, kubectl config set cluster sets values and not the actual cluster
3. If you leave the google cloud platform context you cannot switch back out 

Please correct me if I'm wrong with statements above but this seems like a major problem.

I would assumed the relevant information for switching cluster should be here in the documentation
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/cluster_management.md

edit: here is an earlier discussion on this last year https://github.com/GoogleCloudPlatform/kubernetes/issues/1755

I still think it could be more clear where the current state of kubectl is at regarding cluster switching and terminating both via script and terminal.

https://github.com/GoogleCloudPlatform/kubernetes/blob/8ebd896351513d446d56bc5785c070d2909226a3/release-0.20.0/docs/kubeconfig-file.md

**Comment by aronchick** [comment]
Though we could certainly do better, the way to switch is to set your KUBERNETES_CONFIG file to the appropriate cluster. E.G.

```
$ export KUBERNETES_CONFIG=/User/me/.kube/aws
$ cluster/kubectl.sh cluster-info

[ aws cluster info]

$ export KUBERNETES_CONFIG=/User/me/.kube/gce
$ cluster/kubectl.sh cluster-info

[ gce cluster info ] 
```

**Comment by Kielan** [comment]
Sorry to necro an older issue but I've been meaning to respond to this with the solution to what I wanted. Maybe I did not word exactly as necessary but with the solution I think I can manage to reverse engineer an explanation.
```
gcloud beta container get-credentials

gcloud config set compute/zone asia-east1-a

gcloud config set container/cluster integration-testing

gcloud beta container get-credentials
```

one thing that threw me off about switching clusters was having to use a a beta gcloud command which made it more difficult to find in the documentation. 

one thing I also noticed was that after get credentials the response is 

Fetching cluster endpoint and auth data.
kubeconfig entry generated for CLUSTER_NAME. To switch context to the cluster, run

kubectl config use-context ....

I don't know if there is a less clunky way to do this, or what this would be like on aws, rackspace, or bare metal. Maybe I'm living in a fantasy world to think kubectl could discover kubeconfig on it's own without having to tinker with the cloud provider.
 
At least some clarification somewhere in this repo would be awesome :v:

**Comment by sneerin** [comment]
I agree, swithing in and out is a total mess

**Comment by bgrant0607** [comment]
For Kubernetes docs, start here:
http://kubernetes.io/v1.0/docs/user-guide/prereqs.html

If you'd like support for making it easier to use multiple kubeconfig files, comment on #9298.

GKE documentation is here: https://cloud.google.com/container-engine/docs/clusters/operations#configuring_kubectl

Probably we could cross-link the OSS and GKE documentation better. cc @MikeJeffrey @RichieEscarez 

Requiring `beta` in `gcloud` commands will go away when GKE goes GA.

cc @jlowdermilk for other thoughts on gcloud/kubectl integration

**Comment by aronchick** [comment]
I just ran into this myself, oddly, today with @jlowdermilk. The problem is gcloud thinks it has a cluster, and gcloud config lists that cluster & project, but kubectl pulls from a different cluster. Not obvious at all (and not related to kubeconfig files - it's more the integration with gcloud and kubeconfig).

Basically, it's weird that you can set a KUBECONFIG file, to point at one cluster, and then run a kube-down.sh and have it shut down a different cluster (based on your config file).

For example:
```
[Have a running cluster somewhere with a valid ~/.kube/config file]
mv ~/.kube/config ~/.kube/config-cluster1
gcloud config set core/account newaccount@gmail.com
gcloud config set core/project second-project
kube-up.sh
mv ~/.kube/config ~/.kube/config-cluster2
export KUBECONFIG=~/.kube/config-cluster1;
kube-down.sh
```

Expected:
- Cluster 1 is destroyed

Actual:
- Cluster 2 is destroyed

**Comment by jlowdermilk** [comment]
There are now a number of open issues related to kubeconfig and kube-up that need attention (see also #14335, #10516). I'll set aside some time next week to clean this up.

**Comment by Zhomart** [comment]
How to change from gce to vagrant? Switching to gce cluster is easy using command `$ gcloud container clusters get-credentials cluster-name`, but I could not switch to cluster running on vagrant.

**Comment by philipn** [comment]
FYI, I've thrown together a simple utility to switch between Kubernetes contexts more verbosely and quickly:

https://github.com/philipn/k8env

**Comment by numbsafari** [comment]
To change kubectl itself, simply run the following:

```
kubectl config set current-context {context-name}
```

So, for example, if you have a local minikube cluster setup, run the following:

```
kubectl config set current-context minikube
```

And you're kubectl CLI is no working with your local minikube.
