### ISSUE TITLE
kube-scheduler panics on malformed label

### ISSUE THREAD

**Issue by jcstanaway** [kubernetes/kubernetes#107415]
### What happened?

A deployment was inadvertently created with a malformed label in `requiredAffinityTerms` which appears to have caused the kube-scheduler to panic and crash.

Error from kube-scheduler pods: 
```
E0107 05:56:44.099432       1 scheduling_queue.go:547] Error getting label selectors for pod: REDACTED.
E0107 05:56:44.099573       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 353 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1b0f760, 0x2d9c290)
            /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
            /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x1b0f760, 0x2d9c290)
            /usr/local/go/src/runtime/panic.go:969 +0x1b9
```

Events from REDACTED pod:
```
Events:
  Type     Reason             Age    From                Message
  ----     ------             ----   ----                -------
  Warning  FailedScheduling   4m44s  default-scheduler   0/40 nodes are available: 40 parsing pod: requiredAffinityTerms: invalid label value: "-api-gateway-mockservice": at key: "release": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').
  Warning  FailedScheduling   4m44s  default-scheduler   0/40 nodes are available: 40 parsing pod: requiredAffinityTerms: invalid label value: "-api-gateway-mockservice": at key: "release": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').
  Warning  FailedScheduling   110s   default-scheduler   0/40 nodes are available: 40 parsing pod: requiredAffinityTerms: invalid label value: "-api-gateway-mockservice": at key: "release": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').
  Warning  FailedScheduling   51s    default-scheduler   0/40 nodes are available: 40 parsing pod: requiredAffinityTerms: invalid label value: "-api-gateway-mockservice": at key: "release": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').
  Normal   NotTriggerScaleUp  4m40s  cluster-autoscaler  pod didn't trigger scale-up: 51 parsing pod: requiredAffinityTerms: invalid label value: "-api-gateway-mockservice": at key: "release": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
 ```

### What did you expect to happen?

kube-scheduler should not panic.

### How can we reproduce it (as minimally and precisely as possible)?

Submit a deployment with a malformed label value.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.13", GitCommit:"2444b3347a2c45eb965b182fb836e1f51dc61b70", GitTreeState:"clean", BuildDate:"2021-11-17T13:00:29Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux ip-10-117-7-107.eu-west-1.compute.internal 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
cri-o
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Zheaoli** [comment]
Would you mind to give us a deployment demo which can cause panic and tell us what k8s version you use?

**Comment by sanposhiho** [comment]
The first error log is from here:
https://github.com/kubernetes/kubernetes/blob/v1.20.13/pkg/scheduler/internal/queue/scheduling_queue.go#L547

When `LabelSelectorAsSelector` returns error, selector will be nil:
https://github.com/kubernetes/kubernetes/blob/v1.20.13/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go#L34-L70

Returned `selector` is passed to `util.PodMatchesTermsNamespaceAndSelector` and `util.PodMatchesTermsNamespaceAndSelector` accesses `selector.Matches`. I think `invalid memory address or nil pointer dereference` here:
https://github.com/kubernetes/kubernetes/blob/v1.20.13/pkg/scheduler/util/topologies.go#L45

If my thoughts above are correct, this bug still exists on v1.20.14 (latest version of v1.20).

**Comment by Zheaoli** [comment]
@sanposhiho 

If your thoughts are right, this bug still exists in the newest version in the master branch. PTAL here https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/types.go#L201-L206

I would like to make a PR to add an extra nil check. But maybe we should add validation to check the selector when people apply a config.

**Comment by sanposhiho** [comment]
> this bug still exists in the newest version in the master branch. PTAL here

This `AffinityTerm` struct is created in this `newAffinityTerm` func and `newAffinityTerm` correctly handles error from `LabelSelectorAsSelector`, doesn't it?  
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/types.go#L253
I think this bug doesn't exist on latest master branch.

**Comment by Zheaoli** [comment]
Yes you are right, I think this issue no longer exists since https://github.com/kubernetes/kubernetes/commit/c7fef196b60856420ce3f0470acd1093ab1d9b5f

**Comment by sanposhiho** [comment]
Honestly, I don't know much about Kubernetes patch support period. 
But, according to the following document, patch support for v1.20 will be until February of this year. So, we may need to fix this issue..? 

> 1.20 
Latest Release:1.20.14 (released: 2021-12-15)
End of Life:2022-02-28
Patch Releases: 1.20.1, 1.20.2, 1.20.3, 1.20.4, 1.20.5, 1.20.6, 1.20.7, 1.20.8, 1.20.9, 1.20.10, 1.20.11, 1.20.12, 1.20.13, 1.20.14
https://kubernetes.io/releases/

**Comment by kerthcet** [comment]
Yes, I suppose we still need a bug fix.

**Comment by Zheaoli** [comment]
If we need to fix this bug, I would like to make a PR

**Comment by jcstanaway** [comment]
> Would you mind giving us a deployment demo that can cause panic and telling us what k8s version you use?

```
        affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: release
                      operator: In
                      values:
                        - -api-gateway-mockservice
                topologyKey: "kubernetes.io/hostname"
```

**Comment by jcstanaway** [comment]
In this scenario, what's the expected k8s behavior? Both the kube-scheduler and the kube-apiserver? We're considering that if the kube-apiserver is not going to deny admission that we should add an OPA gatekeeper policy.

**Comment by kerthcet** [comment]
First of all, the value name `-api-gateway-mockservice` is not valid, if a valid name is applied, this expression can apply successfully, pods would like to find nodes with the same label pods landed.
Secondly, what do you mean `if the kube-apiserver is not going to deny admission`, what's the rule you would like to deny?

**Comment by jcstanaway** [comment]
Yes, we realize that the label value is malformed. I noted that in the original post. The automation used by one of our teams didn't work correctly. Of course that is being addressed, but the deployment manifest was accepted by the kube-apiserver and the kube-scheduler attempted to process it (and crashed).

So the question is: How is k8s going to protect itself in the event this occurs again? Ideally, the apiserver would deny admission when the manifest is submitted thus letting the user know that there is an issue and correct it. If the apiserver doesn't deny, then what will the scheduler do? Just log the event (as shown above) and not panic (once 1.20 is patched)?

Clearly, the scheduler has a rule implemented to validate the label value:

`a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').`

Ideally, the apiserver would have performed the same validation rule. If the apiserver doesn't implement that rule post 1.20, then we're thinking to add an OPA Gatekeeper policy to cause such a manifest to be denied admission as it would be better to detect such issues earlier.

**Comment by kerthcet** [comment]
IIRC, `a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?').`  this error is emitted by the api-server.

**Comment by jcstanaway** [comment]
> this error is emitted by the api-server.

It appears that error (event) was emitted by the kube-scheduler (see initial post above). If the kube-apiserver detected the error, then the manifest should have been rejected and the kube-scheduler would never have tried to schedule a pod in that deployment.

So it would seem that the apiserver needs an update to catch such malformed label values. It does that in `metadata.labels`, but not in `labelSelector` sections.

With malformed `metadata.labels: { release: -api-gateway-mockservice }`:

`The Deployment "label-test" is invalid: metadata.labels: Invalid value: "-api-gateway-mockservice": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')`

With the above malformed `affinity`, the apiserver accepted the Deployment.

**Comment by ahg-g** [comment]
I agree, the pod should've not been admitted in the first place.

I think the issue is here: https://github.com/kubernetes/kubernetes/blob/8c69e5d25bfdbd266b384db29493bc9bad60f092/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go#L57

we validate the label key but not value for MatchExpressions.

we should add:
```
for v := range sr.Values {
  for _, msg := range validation.IsValidLabelValue(v) {
    allErrs = append(allErrs, field.Invalid(fldPath.Child("values"), v, msg))
  }
}
```


we do that already with MatchLabels, but not MatchExpressions: 

https://github.com/kubernetes/kubernetes/blob/8c69e5d25bfdbd266b384db29493bc9bad60f092/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/validation/validation.go#L75

**Comment by jcstanaway** [comment]
Patching the apiserver would definitely be the preferred solution as that would cover all clusters without the need to add an OPA Gatekeeper policy.

**Comment by ahg-g** [comment]
@Zheaoli can you pls send a pr with the fix as described above?

**Comment by Zheaoli** [comment]
@ahg-g Of course, I will make bug fix ASAP I can

**Comment by kinderyj** [comment]
good catch

**Comment by jcstanaway** [comment]
Waiting for https://github.com/kubernetes/kubernetes/pull/107531 to be merged into a k8s release. Appears to be targeted to 1.25, so unless backported to earlier releases, users may want to consider using an OPA Gatekeeper policy to detect/block such malformed label values.

/remove-lifecycle stale

**Comment by liggitt** [comment]
this bug is fixed in https://github.com/kubernetes/kubernetes/pull/107558, the scheduler no longer panics.

the validation gap is tracked in https://github.com/kubernetes/kubernetes/issues/99139 and being fixed in https://github.com/kubernetes/kubernetes/pull/107531
