### ISSUE TITLE
Cert-manager and Ingress pods in Crash loop back off (AKS)

### ISSUE THREAD

**Issue by Nuthanuke** [kubernetes/kubernetes#107496]
I was trying to upgrade the kubernetes version of our cluster from 1.19.7 to 1.22 and some of the worker nodes failed in updating so I restarted the cluster. After restarting the upgrade was successful but Cert-manager-webhook and Cert-manager-cainjector pods went down along with the ingress pods. i.e. they are either in crashloopbackoff state or error state

after checking the logs, these are the errors that I see,

**The cert-manager-webhook is throwing this error - "msg"="Failed to generate initial serving certificate, retrying..." "error"="failed verifying CA keypair: tls: failed to find any PEM data in certificate input" "interval"=1000000000
"msg"="Generating new ECDSA private key"**

**The cert-manager-cainjector is throwing this error- cert-manager/controller-runtime/manager "msg"="Failed to get API Group-Resources" "error"="an error on the server ("") has prevented the request from succeeding"**

**The nginx-ingress pod is throwing this error - SSL certificate chain completion is disabled (--enable-ssl-chain-completion=false)**

Can anyone please help?

Thank you.
/sig k8s-infra

**Comment by neolit123** [comment]
hi, 

> I was trying to upgrade the kubernetes version of our cluster from 1.19.7 to 1.22 and some of the worker nodes failed in updating so I restarted the cluster

make sure that you upgrade from 1.19.x to 1.20.y first. skipping minor versions is not supported.

>  After restarting the upgrade was successful but Cert-manager-webhook and Cert-manager-cainjector pods went down along with the ingress pods. i.e. they are either in crashloopbackoff state or error state

this doesn't seem like a core k8s problem, but something related to cert-manager / ingress or the deployment of AKS.
you can coordinate with the affected deployments or AKS support on how to resolve it.

you could also try asking on the support forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
