### ISSUE TITLE
Server side apply conflicts with itself

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#107417]
### What happened?

When resource is created using `POST` call it then can't be updated with SSA  `PATCH` call, even if field manager name for both operations is the same

### What did you expect to happen?

`PATCH` succeeds with no conflicts

### How can we reproduce it (as minimally and precisely as possible)?

Create resource without SSA, but specifying field manager explicitly

 ```
$ kubectl apply --server-side=false --field-manager=myfm  -f - <<EOF
apiVersion: v1
data:
  key: value1
kind: ConfigMap
metadata:
  name: ssa-test
EOF
 ```
 
Then update resource using SSA and same field manager:
 
 ```
$ kubectl apply --server-side=true --field-manager=myfm  -f - <<EOF
apiVersion: v1
data:
  key: value2
kind: ConfigMap
metadata:
  name: ssa-test
 EOF
 ```
 
Following error is returned:
 
 ```
error: Apply failed with 1 conflict: conflict with "myfm" using v1: .data.key
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by redbaron** [comment]
Looks like a field manager key is not just manager name , but also operation. Is it an oversight or intentional design? Docs say that `Update` is like `Apply`, but can't fail due to conflict and takes ownerhship of changed fields, but as demonstrated by this issue it doesn't do just that, it creates distinct owner with the same name.

**Comment by redbaron** [comment]
API server encodes operation into field manager name before passing it to structured-merge-diff: 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/buildmanagerinfo.go

**Comment by redbaron** [comment]
@apelisse , you seem to be the author of  original SSA implementation, which from the start had operation encoded into field manager name. Could you shed some light why `Apply` intended to conflict with `Update` even if done by the same field manager?

**Comment by sftim** [comment]
This might be a docs issue. If so, updates to https://github.com/kubernetes/website/pull/31261 (or a separate PR) might be in order, and also we can /transfer this issue to [k/website](https://github.com/kubernetes/website).

**Comment by redbaron** [comment]
I am not sure it is a docs issue. Current behaviour contradicts documented intent, not just some unclear wording.

To quote docs:

> When a field's value changes, ownership moves from its current manager to the manager making the change. When trying to apply an object, fields that have a different value and are owned by another manager will result in a conflict. 

Then it describes what field manager is:

> Managers identify distinct workflows that are modifying the object (especially useful on conflicts!), and can be specified through the fieldManager query parameter as part of a modifying request

And enumarates ways to communicate field manager to the API server:

> The user who last made an assertion about the value of a field will be recorded as the current field manager. This can be done either by changing the value with POST, PUT, or non-apply PATCH, or by including the field in a config sent to the Server Side Apply endpoint. 

And provides example what field manager is:

> In this example, a second operation was run as an Update by the manager called `kube-controller-manager`. The update changed a value in the data field which caused the field's management to change to the `kube-controller-manager`.

In the introduction section it is clearly stated that SSA is designed to make multiple collaborators make changes to an object more convenient and safer by detecting conflicts:

> Clients can create and modify their objects declaratively by sending their fully specified intent.
> The system supports multiple appliers collaborating on a single object.
> When trying to apply an object, fields that have a different value and are owned by another manager will result in a conflict. This is done in order to signal that the operation might undo another collaborator's changes.


I read it as  SSA conflict mechanism is designed to highlight when one user can change data another user cares about. Regardless of operation performed  collaborator (aka worflow, aka user, aka manager) is identified using fieldManager query parameter, but can be inferred from user agent if missing for non apply operations.  

At no point in the document or SSA KEP it hints that there can be conflict between different operations done by the same workflow.

**Comment by apelisse** [comment]
No, I don't think it's a doc issue. We do support a transition (which doesn't work great either) from csa to ssa, but only for the kubectl manager. I can see here that you're using a different manager.

We should do better with the client-side to server-side transition.

**Comment by redbaron** [comment]
Is changing field manager passed to structured merge diff from `(name, operation)` to `(name)` a viable way to resolve it?

**Comment by apelisse** [comment]
No I don't think it is. Update and Apply work differently enough that we can't override one with the other. We probably can figure out a solution but it's not obvious.

**Comment by redbaron** [comment]
@apelisse ,

> Update and Apply work differently enough that we can't override one with the other.

Update already unconditionally overrides anything, so only user visible effect will be that Apply will override Update if both have same `fieldManagerName`, which is exactly what this issue is about -  changes done by the same fieldManagerName should never conflict with itself, regardless of exact operation.

**Comment by julianvmodesto** [comment]
The client-side and server-side apply compatibility needs some work to work properly.

Generally the `(field manager, operation)` as the field manager is intended though. A field manager should use the same operation to manage a group of fields, so the conflict is helpful. The exception is client-side and server-side apply, where that shouldn't happen ideally and the `(field manager, operation)` should somehow be the same to fix this issue. Otherwise, what we see now is this issue where you can't change a field when switching between client-side and server-side apply or something like https://github.com/kubernetes/kubernetes/issues/99003.

**Comment by julianvmodesto** [comment]
Maybe a kubectl command like `edit-last-applied` could help users manually fix managed fields, but to fix the compatibility issue itself, I'm not sure. I think the strawperson is on server-side apply, when the client-side apply annotation exists, then we remove the `(field manager, operation)` for client-side apply if the field manager for server-side apply matches.

**Comment by EronWright** [comment]
One problem with the argument that Create-then-Apply is a CSA-to-SSA migration is that Apply is not a perfect substitute for Create; Create will reject the request if the object already exists, whereas Apply works like an upsert.  Upsert isn't always desirable for field managers that assume lifecycle control of the object.

**Comment by redbaron** [comment]
@julianvmodesto ,

> A field manager should use the same operation to manage a group of fields, so the conflict is helpful to avoid mixing operations (like declarative and imperative operations).

This restrictive design constraint is not mentioned anywhere in SSA docs or KEP. Any agent acting on k8s resources  is free to use any available instrument depending on the higher level logic K8S has no access to.

**Comment by willemm** [comment]
How is this supposed to work if a field manager wants to create items using Apply, but with generateName ?
