### ISSUE TITLE
When I join  The cluster

### ISSUE THREAD

**Issue by Msunshineboy** [kubernetes/kubernetes#107404]
### What happened?

[root@node01 amax]# kubeadm join 10.16.0.78:6443 --token kydz6y.ex2t63no93qm8bvt     --discovery-token-ca-cert-hash sha256:5a811dc96bda254a2bd5f7fcd51997252caaa9cd5306600909a3c75b41de9fdc
[preflight] Running pre-flight checks
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING SystemVerification]: this Docker version is not on the list of validated versions: 20.10.12. Latest validated version: 19.03
        [WARNING Hostname]: hostname "node01" could not be reached
        [WARNING Hostname]: hostname "node01": lookup node01 on 202.202.32.33:53: no such host
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

### What did you expect to happen?

I want to konw how can I solve these warning and error ?

### How can we reproduce it (as minimally and precisely as possible)?

what I exec kubeadm join 10.16.0.78:6443 --token kydz6y.ex2t63no93qm8bvt     --discovery-token-ca-cert-hash sha256:5a811dc96bda254a2bd5f7fcd51997252caaa9cd5306600909a3c75b41de9fdc

### Kubernetes version

1.19

### Cloud provider

non

### OS version

centos 8

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support
/remove-kind bug

###  [WARNING IsDockerSystemdCheck]
> detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/

The container runtime and kubelet should use the same cgroup driver.

### [WARNING SystemVerification]: 
> this Docker version is not on the list of validated versions: 20.10.12. Latest validated version: 19.03

https://github.com/kubernetes/system-validators/pull/23
Kubernetes 1.21 started to add docker 20.10 to a valid list. You are using 1.19.

### [WARNING Hostname]: hostname "node01" 
> could not be reached
>  [WARNING Hostname]: hostname "node01": lookup node01 on 202.202.32.33:53: no such host

https://github.com/kubernetes/kubernetes/blob/1367cca8fd67b09606b01c0a9e46cef59aef3424/cmd/kubeadm/app/preflight/checks.go#L390-L394
Added in https://github.com/kubernetes/kubernetes/pull/35843 as error and loosen to warning for AWS cases in https://github.com/kubernetes/kubernetes/pull/41220.

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
