### ISSUE TITLE
kubelet Failed

### ISSUE THREAD

**Issue by wybaron** [kubernetes/kubernetes#107489]
### What happened?

![image](https://user-images.githubusercontent.com/19605510/149117395-6b1eee65-985c-4680-be7a-527f29b063a3.png)
![image](https://user-images.githubusercontent.com/19605510/149117214-2de01a58-e3b5-4d06-ab19-edfd9bd975df.png)
![image](https://user-images.githubusercontent.com/19605510/149117262-2121321a-af93-4258-9650-f45f87d531ed.png)

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### Kubernetes version

![image](https://user-images.githubusercontent.com/19605510/149117808-4a5c72da-aebf-4d03-bf5d-c1520d759127.png)

### Cloud provider

<details>

</details>

### OS version

![image](https://user-images.githubusercontent.com/19605510/149118220-ea43c7c3-3321-4f18-9524-9a868ea532ce.png)
![image](https://user-images.githubusercontent.com/19605510/149118076-543404bb-8601-488a-a619-8436bda1bcb1.png)

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

![image](https://user-images.githubusercontent.com/19605510/149118153-a9cc3237-5ec0-4ae5-9d4e-7e633cdccbf2.png)

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
```
the currently active client certificate has expired
```

/kind support
/remove-kind bug

**Comment by neolit123** [comment]
if the kubelet certificate expired you have to manually sign a new one and place it in the kubelet.conf.
https://kubernetes.io/docs/setup/best-practices/certificates/#configure-certificates-for-user-accounts
then restart the kubelet.

you are using kubeadm / kubelet 1.9 and these versions are very old...
we only support 1.20+ at this point.

your best option is to try to get more support on the forums:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/sig cluster-lifecycle
/close

**Comment by neolit123** [comment]
> if the kubelet certificate expired you have to manually sign a new one and place it in the kubelet.conf.

note that newer versions of kubelet / kubeadm automatically rotate the kubelet client certificates.
https://kubernetes.io/docs/tasks/tls/certificate-rotation/
