### ISSUE TITLE
how can i set replicated Pods create rate or freeze time?not HPA

### ISSUE THREAD

**Issue by cwyj** [kubernetes/kubernetes#107401]
I create a deployment or StatefulSet with 3 replicates.i wangt it create replicates one by one,not at the same time.does it support set create rate or create freeze time?

**Comment by pacoxu** [comment]
For StatefulSet, see
- https://kubernetes.io/blog/2021/08/27/minreadyseconds-statefulsets/
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2599-minreadyseconds-for-statefulsets#user-stories-optional

minReadySecondsinteger | Minimum number of seconds for which a newly created pod should be ready without any of its container crashing for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready) This is an alpha field and requires enabling StatefulSetMinReadySeconds feature gate.
-- | --
