### ISSUE TITLE
kube-proxy reported Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4

### ISSUE THREAD

**Issue by yysu** [kubernetes/kubernetes#107482]
### What happened?

Hello guys,

I am using EKS cluster, Kubernetes: `1.18`, Platform: `eks.8`, kube-proxy version is `v1.18.8`.

I saw my `kube-proxy` log reported the warning message several times at different timestamps:
```
{"log":"W0105 11:53:24.659392       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-05T11:53:24.659598009Z"}
{"log":"W0105 19:44:24.622260       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-05T19:44:24.622453484Z"}
{"log":"W0105 22:12:54.612947       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-05T22:12:54.613252022Z"}
{"log":"W0105 23:39:54.612861       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-05T23:39:54.613017737Z"}
{"log":"W0106 03:07:54.624188       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T03:07:54.624377664Z"}
{"log":"W0106 06:46:54.612137       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T06:46:54.612320831Z"}
{"log":"W0106 08:05:54.649304       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T08:05:54.649438556Z"}
{"log":"W0106 12:40:54.624664       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T12:40:54.624880946Z"}
{"log":"W0106 16:59:54.624448       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T16:59:54.624679404Z"}
{"log":"W0106 19:02:54.611627       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T19:02:54.611794303Z"}
{"log":"W0106 19:59:54.634755       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T19:59:54.63495861Z"}
{"log":"W0106 21:45:54.612071       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T21:45:54.612247991Z"}
{"log":"W0106 21:59:54.634774       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T21:59:54.634943097Z"}
{"log":"W0106 22:08:54.638361       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T22:08:54.63853643Z"}
{"log":"W0106 22:26:54.788332       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T22:26:54.78849712Z"}
{"log":"W0106 23:24:54.612272       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T23:24:54.612452656Z"}
{"log":"W0106 23:35:54.611868       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T23:35:54.612119101Z"}
{"log":"W0106 23:40:54.612193       1 iptables.go:562] Could not check for iptables canary mangle/KUBE-PROXY-CANARY: exit status 4\n","stream":"stderr","time":"2022-01-06T23:40:54.612400088Z"}
```

Tracing the source code, I saw the code logic here : 

https://github.com/kubernetes/kubernetes/blob/0f3e6609388defe7d0149216cb0409531f8d33b3/pkg/util/iptables/iptables.go#L70-L80

https://github.com/kubernetes/kubernetes/blob/0f3e6609388defe7d0149216cb0409531f8d33b3/pkg/util/iptables/iptables.go#L558-L564

https://github.com/kubernetes/kubernetes/blob/0f3e6609388defe7d0149216cb0409531f8d33b3/pkg/util/iptables/iptables.go#L745-L755

It turns out the comment mentioned `isResourceError returns true if the error indicates that iptables ran into a “resource problem” and was unable to attempt the request. In particular, this will be true if it times out trying to get the iptables lock.`. 

I have two queries about this warning message : 
1. Which situation may cause this warning message happen ? May it cause any actual impact to my application workload ? 
2. Can we address more clear error message about what the `resource problem` is ?

Thanks !

### What did you expect to happen?

No warning message or a more clear one to show what happened.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure. It happened occasionally.

### Kubernetes version

<details>

```console
Kubernetes: `1.18`, Platform: `eks.8`, kube-proxy version is `v1.18.8`
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
Kernel Version: 4.14.198-152.320.amzn2.x86_64
Operating System: Amazon Linux 2
OSType: linux
Architecture: x86_64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Client:
 Version:           19.03.6-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        369ce74
 Built:             Fri May 29 04:01:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       369ce74
  Built:            Fri May 29 04:01:57 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.2
  GitCommit:        ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc:
  Version:          1.0.0
  GitCommit:        84113eef6fc27af1b01b3181f31bbaf708715301
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI : AWS VPC CNI `1.7.5`

kube-proxy : `v1.18.8`
</details>

**Comment by aojea** [comment]
> 1. Which situation may cause this warning message happen ? May it cause any actual impact to my application workload ?

If the monitor loop tries to check the iptables rules meanwhile another program is using iptables, it will raise that error, because it needs to acquire the iptables lock, but it can not.

There can be only one iptables operation at a time, simplifying, everytime you create a Service or one Service is updated, kube-proxy takes the iptables lock and start to create the corresponding iptables rules, on systems with a lot of services and endpoints this can take a long time, that means that other programs trying to use iptables will have to wait.

There can be other programs in your host using iptables, the more program using iptables the more chances that this can happen.

> 2. Can we address more clear error message about what the `resource problem` is ?

What is the information that you are looking for on the message that you feel can help you better to understand the problem?

**Comment by khenidak** [comment]
@yysu  can you check kernel logs as well? 

the lock is held by iptables userspace client executable. It usually executes in < 1s and exists releasing the lock. if it hanged (which should be mirrored somewhere in kernel logs) then lock is held and you get the above behavior.

**Comment by thockin** [comment]
any updates here?

**Comment by dcbw** [comment]
Closing for now; please re-open if you have updated information and/or the the logs requested by @khenidak. Thanks!
/close
