### ISSUE TITLE
Kubernetes behaviour differs from metav1 ManagedFieldsEntry.Time godoc comment

### ISSUE THREAD

**Issue by redbaron** [kubernetes/kubernetes#107434]
### What happened?

Godoc says that Time should be empty on mangedFields entry created by "Apply" operation, but kubernetes populates time on apply.

### What did you expect to happen?

Godoc consistent with kubernetes behaviour

### How can we reproduce it (as minimally and precisely as possible)?

Godoc:

https://github.com/kubernetes/kubernetes/blob/559091ba4f36a190e6876e0b164068385a7a992f/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1246-L1248

Kubernetes:

```
$ kubectl apply --server-side=true --field-manager=myfm  -f - <<EOF
apiVersion: v1
data:
  key: value2
kind: ConfigMap
metadata:
  name: ssa-test
EOF
```

```
$ kubectl get cm ssa-test -o yaml --show-managed-fields
apiVersion: v1
data:
  key: value2
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-09T20:08:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:key: {}
    manager: myfm
    operation: Apply
    time: "2022-01-09T20:08:35Z"
  name: ssa-test
  namespace: default
  resourceVersion: "4323921"
  uid: 639b534f-dff1-47a2-bb81-cb40a698b030
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by apelisse** [comment]
Yeah, good catch. The comment matches the behavior from alpha, which we changed later on. Thanks for letting us now :-)

I think we could do a better job describing how this value is changed now.
