### ISSUE TITLE
pod creation error: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"

### ISSUE THREAD

**Issue by Msunshineboy** [kubernetes/kubernetes#107403]
### What happened?

when I change /etc/docker/demon

{
 "exec-opts":["native.cgroupdriver=systemd"]
}
I describe the error pod pod/kube-proxy-zq5dk

Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               <unknown>              default-scheduler  Successfully assigned kube-system/kube-proxy-zq5dk to node01
  Normal   Pulling                 58m                    kubelet, node01    Pulling image "registry.aliyuncs.com/google_containers/kube-proxy:v1.16.0"
  Normal   Pulled                  58m                    kubelet, node01    Successfully pulled image "registry.aliyuncs.com/google_containers/kube-proxy:v1.16.0"
  Normal   Created                 58m                    kubelet, node01    Created container kube-proxy
  Normal   Started                 58m                    kubelet, node01    Started container kube-proxy
  Warning  FailedCreatePodSandBox  51m (x11 over 53m)     kubelet, node01    Failed create pod sandbox: rpc error: code = Unknown desc = failed to create a sandbox for pod "kube-proxy-zq5dk": Error response from daemon: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"
  Normal   SandboxChanged          3m39s (x232 over 53m)  kubelet, node01    Pod sandbox changed, it will be killed and re-created.

### What did you expect to happen?

I want to why? what can I do？

### How can we reproduce it (as minimally and precisely as possible)?

 change /etc/docker/demon

### Kubernetes version

kubectl version 1.16

### Cloud provider

non

### OS version

centos7

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pandaamanda** [comment]
@Msunshineboy  please check param --cgroup-driver of kubelet, it should be same with docker(here you set cgroupdriver=systemd )

**Comment by pacoxu** [comment]
/remove-kind bug
/kind support
BTW 1.16 is not supported and End of life. Please try a newer version.

If installing using kubeadm, specifying the cgroup driver to use the same as docker is needed.

> Kubeadm: during "init" an empty cgroupDriver value in the KubeletConfiguration is now always set to "systemd" unless the user is explicit about it. This requires existing machine setups to configure the container runtime to use the "systemd" driver. Documentation on this topic can be found here: https://kubernetes.io/docs/setup/production-environment/container-runtimes/. When upgrading existing clusters / nodes using "kubeadm upgrade" the old cgroupDriver value is preserved, but in 1.22 this change will also apply to "upgrade". For more information on migrating to the "systemd" driver or remaining on the "cgroupfs" driver see: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/. (#99471, @neolit123) [SIG Cluster Lifecycle]

**Comment by pacoxu** [comment]
/retitle pod creation error: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"

**Comment by pacoxu** [comment]
/retitle pod creation error: cgroup-parent for systemd cgroup should be a valid slice named as "xxx.slice"

**Comment by ehashman** [comment]
Kubernetes does not use issues on this repo for support requests. If you have a question on how to use Kubernetes or to debug a specific issue, please visit our [forums](https://discuss.kubernetes.io/).

/close
