### ISSUE TITLE
Rotated container log files size not counted towards ephemeral-storage's limit on CRI-O

### ISSUE THREAD

**Issue by ramineni** [kubernetes/kubernetes#107447]
### What happened?

Rotated container logs space usage doesnt seem to be counted towards the epehemral storage limit. Always only current log file stats are taken into account.

### What did you expect to happen?

rotated log files usage also should be counted towards ephemeral-storage usage

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl get --raw /api/v1/nodes/localhost.localdomain/proxy/stats/summary | jq . | grep ephem1 -B 1 -A 96

"podRef": {
        "name": "ephem1",
        "namespace": "default",
        "uid": "5334a37d-df02-435c-b385-f05a36567d11"
      },
      "startTime": "2022-01-10T09:35:02Z",
      "containers": [
        {
          "name": "con2",
          "startTime": "2022-01-10T09:35:14Z",
	   ...........
	   .................
	   
          "logs": {
            "time": "2022-01-10T09:41:47Z",
            "availableBytes": 310701400064,
            "capacityBytes": 322111012864,
            "usedBytes": 4096,
            "inodesFree": 157194364,
            "inodes": 157285888,
            "inodesUsed": 91524
          }
        },


But the stats from the container log dir sees total size of 24k
$ ls -lh /var/log/pods/ephem1-pod/con2
total 24K
-rw-------. 1 root root 4.1K Jan 10 09:40 0.log
-rw-r--r--. 1 root root  924 Jan 10 09:37 0.log.20220110-093622.gz
-rw-r--r--. 1 root root  938 Jan 10 09:38 0.log.20220110-093733.gz
-rw-r--r--. 1 root root  956 Jan 10 09:39 0.log.20220110-093843.gz
-rw-------. 1 root root 5.2K Jan 10 09:39 0.log.20220110-093955

```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Tested on Kubernetes Version : 1.21.7, 1.22
Container Runtime : Cri-o
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yangjunmyfm192085** [comment]
/assign
we can see if there is a issue

**Comment by 249043822** [comment]
@ramineni Were the rotated log files in /var/log/pods generated by yourself(not by k8s)? The cadvisor can only collects log files on container's filesystem.

**Comment by ramineni** [comment]
> @ramineni Were the rotated log files in /var/log/pods generated by yourself(not by k8s)? The cadvisor can only collect log files on container's filesystem.

No, I have not created any files. they are generated by k8s itself.

**Comment by 249043822** [comment]
> > @ramineni Were the rotated log files in /var/log/pods generated by yourself(not by k8s)? The cadvisor can only collect log files on container's filesystem.
> 
> No, I have not created any files. they are generated by k8s itself.

Okay, I see. As the cri-o runtime uses cadvisor stats provider to get container stats, it caculates container logUsage by formular `logsUsage := *ContainerStats.Filesystem.TotalUsageBytes - *ContainerStats.Filesystem.BaseUsageBytes`. but the default root dir or log dir of cri-o is not /var/log/pods/{podName}/, so theses log files are not on container's filesystem, then cadvisor may not caculate the data accurately. /cc @bobbypage 
the containerd uses cri stats provider and gets logstats by HostStatsProvider, it can get right data.

**Comment by yangjunmyfm192085** [comment]
In the kubelet code, , the log path is in the format `filepath.Join(podLogsRootDirectory, strings.Join([]string{podNamespace, podName,string(podUID)}, logPathDelimiter)) `, but the directory of your environment is `/var/log/pods/ephem1-pod/con2`, I did not see `string(podUID)`,  Did you set this path yourself? @ramineni

**Comment by ramineni** [comment]
@yangjunmyfm192085 sorry I truncated the name for better readability, the actual path name is 
`/var/log/pods/default_ephem1_5334a37d-df02-435c-b385-f05a36567d11/con2` . So I suppose its taking in the above format only.

**Comment by ramineni** [comment]
> > > @ramineni Were the rotated log files in /var/log/pods generated by yourself(not by k8s)? The cadvisor can only collect log files on container's filesystem.
> > 
> > 
> > No, I have not created any files. they are generated by k8s itself.
> 
> Okay, I see. As the cri-o runtime uses cadvisor stats provider to get container stats, it caculates container logUsage by formular `logsUsage := *ContainerStats.Filesystem.TotalUsageBytes - *ContainerStats.Filesystem.BaseUsageBytes`. but the default root dir or log dir of cri-o is not /var/log/pods/{podName}/, so theses log files are not on container's filesystem, then cadvisor may not caculate the data accurately. /cc @bobbypage the containerd uses cri stats provider and gets logstats by HostStatsProvider, it can get right data.

@249043822 log files gets generated in the path /var/log/pods/default_ephem1_5334a37d-df02-435c-b385-f05a36567d11/con2 for cri-o

**Comment by SergeyKanzhelev** [comment]
/retitle Rotated container log files size not counted towards ephemeral-storage's limit on CRI-O

**Comment by yangjunmyfm192085** [comment]
hi, @ramineni, In the past two days, I have studied the collection of file information by cAdvisor. docker and cri-o runtime basically have the same file collection process in cAdvisor.
I have verified  that when the runtime is cri-o, the log information statistics are also correct.
So I need you to provide more detailed information. I found that the command you show at is: `kubectl get --raw /api/v1/nodes/localhost.localdomain/proxy/stats/summary | jq . | grep ephem1 -B 1 -A 96` , please help to confirm whether the "logs" information belongs to the container con2. or use the command `kubectl get --raw /api/v1/nodes/localhost.localdomain/proxy/stats/summary | jq . | grep ephem1 -B 1 -A 30` to try

**Comment by ramineni** [comment]
@yangjunmyfm192085 I have verified and info provided is for con2 only .  I have added the sample yaml used for testing , please let me know if I'm doing it right or anything missing.

I have set the kubelet log configuration as containerLogMaxSize: "5Ki", containerLogMaxFiles: 5

```
apiVersion: v1
kind: Pod
metadata:
  name: ephem1
spec:
  containers:
  - name: con1
    image: busybox
    command: ["/bin/sh", "-c", "dd if=/dev/zero bs=1024k count=20; tail -f /dev/null; sleep 3600"]
    resources:
      limits:
        ephemeral-storage: "10Mi"
  - name: con2
    image: busybox
    args: ["/bin/sh", "-c",
           'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
    resources:
      limits:
        ephemeral-storage: "20Ki"
  terminationGracePeriodSeconds: 0
```
After applying the above yaml

```
$ kubectl get pods
NAME     READY   STATUS    RESTARTS   AGE
ephem1   2/2     Running   0          35m

$ cd /var/log/pods/default_ephem1_08f67c34-d2aa-4f32-ba7e-73c07268aa77/
$ ls
con1  con2
$ du -h .
21M	./con1
24K	./con2
21M	.
$ ls -lh ./con2
total 24K
-rw-------. 1 root root 2.4K Jan 17 05:59 0.log
-rw-r--r--. 1 root root  973 Jan 17 05:56 0.log.20220117-055543.gz
-rw-r--r--. 1 root root  980 Jan 17 05:58 0.log.20220117-055653.gz
-rw-r--r--. 1 root root  977 Jan 17 05:59 0.log.20220117-055803.gz
-rw-------. 1 root root 5.4K Jan 17 05:59 0.log.20220117-055913

$ ls -lh ./con1
total 21M
-rw-------. 1 root root   0 Jan 17 05:39 0.log
-rw-------. 1 root root 21M Jan 17 05:39 0.log.20220117-053911
```

stats summary shows con1 logs used_bytes always 0 , con2 logs used_bytes as 4096

**Comment by ramineni** [comment]
@yangjunmyfm192085  [stats_summary.txt](https://github.com/kubernetes/kubernetes/files/7879451/stats_summary.txt)

**Comment by haircommander** [comment]
what version of CRI-O/kubernetes are you using? using latest main of both kubernetes and cri-o with your reproducer causes the container to be evicted because of it exceeding ephemeral storage

**Comment by haircommander** [comment]
oh I see now:
```
Tested on Kubernetes Version : 1.21.7, 1.22
Container Runtime : Cri-o
```
my mistake

**Comment by haircommander** [comment]
another mistake: I was using CRI stats provider, instead of cAdvisor stats provider (as is default)

**Comment by ramineni** [comment]
@haircommander  Is CRI stats provider used by default in 1.23 by default?
And also problem is seen only if containerLogMaxSize is less that the ephemeral storage limit set , if its more than the ephemeral storage limit , its the right behavior , pod gets evicted in my setup.

**Comment by haircommander** [comment]
at long last, I believe I've found the issue!
