### ISSUE TITLE
[Failing test] gce-ubuntu-master-default, kubetest.Up

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#107469]
### Which jobs are failing?

master informing [gce-ubuntu-master-default](https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default)
master blocking [gce-device-plugin-gpu-master](https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master)

### Which tests are failing?

* ci-kubernetes-e2e-ubuntu-gce.Overall
* kubetest.Up

### Since when has it been failing?

The entire history fails and shows until 2021-12-27.

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-ubuntu-master-default

### Reason for failure (if possible)

```bash
error during ./hack/e2e-internal/e2e-up.sh: exit status 2
```
master blocking  gce-device-plugin-gpu-master run
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1480864782654377984

master informing gce-ubuntu-master-default run
* https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce/1478972948302794752

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
it is using docker as runtime that was deprecated

>     - --env=KUBE_CONTAINER_RUNTIME=docker

@dims @BenTheElder should the job be removed or updated? I think that there is a copy of this with containerd in blocking

>     description: Uses kubetest to run e2e tests (-Slow|Serial|Disruptive|Flaky|Feature)
>      against a cluster (ubuntu based) created with cluster/kube-up.sh
>    prow.k8s.io/context: ""
>    prow.k8s.io/job: ci-kubernetes-e2e-ubuntu-gce

**Comment by dims** [comment]
cc @SergeyKanzhelev @ehashman as they are taking care of what sig-node jobs are needed etc.

**Comment by dims** [comment]
also cc @endocrimes @adisky

**Comment by SergeyKanzhelev** [comment]
/sig node

we can discuss it on tomorrow's CI meeting

**Comment by SergeyKanzhelev** [comment]
/sig cloud-provider

(since tests are in cloud-provider folder)

**Comment by SergeyKanzhelev** [comment]
Are those tests needed. For GPU, (judging by name) GPU tests gce-device-plugin-gpu-master were removed, is the job still needed?

**Comment by BenTheElder** [comment]
It's going to be up to Node I think? GPU doesn't seem particularly relevant to the other SIGs.

**Comment by dims** [comment]
gce-ubuntu-master-default and gce-ubuntu-master-containerd are exactly the same, so we can drop/delete gce-ubuntu-master-default

https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-cloud-provider/gcp/gcp-gce.yaml#L465-L559

**Comment by endocrimes** [comment]
> gce-ubuntu-master-default and gce-ubuntu-master-containerd are exactly the same, so we can drop/delete gce-ubuntu-master-default

+1 - https://github.com/kubernetes/test-infra/pull/24890

**Comment by matthyx** [comment]
So it's been removed?
/close
