### ISSUE TITLE
Optimize cronjob controller status updates 

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#107411]
### What would you like to be added?

cronjob controller may send more than one status update to the api-server for the same cronjob in the same cycle. Ideally the controller should be sending one per cronjob per cycle.

This was evident from the bug in https://github.com/kubernetes/kubernetes/pull/104799, which wouldn't have existed if the controller was making a single update call.

### Why is this needed?

api-server qps is a scarce resource that we should optimize its use to be able to scale.

/sig apps
@soltysh can you look at this?

**Comment by jlsong01** [comment]
@soltysh  Hi, are you working on it? If not, may I take a try?
