### ISSUE TITLE
azure: PV hangs forever in failed deletion because the underlying disk is not found

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#107405]
### What happened?

The fix from https://github.com/kubernetes/kubernetes/pull/102083 seems to be incomplete/wrong. When disk is not found, the GET call for the disk fails with `404 Not Found` and it is not even reaching the DELETE call.

### What did you expect to happen?

PV to be deleted (its `kubernetes.io/pv-protection` finalizer to be removed) when the underlying disk is already gone.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a PVC.

2. Locate the created Azure disk and delete it manually.

3. Then, delete the PVC.

4. Make sure that corresponding PV fails to be deleted with reason:

```yaml
status:
  message: 'Retriable: false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: Retriable:
    false, RetryAfter: 0s, HTTPStatusCode: 404, RawError: {"error":{"code":"ResourceNotFound","message":"The
    Resource ''Microsoft.Compute/disks/foo''
    under resource group ''bar'' was not found. For more details please
    go to https://aka.ms/ARMResourceNotFoundFix"}}'
  phase: Failed
```

### Kubernetes version

<details>

```console
$ kubectl version

Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-15T19:18:00Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by andyzhangx** [comment]
this issue was fixed in CSI driver:
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/b92ed5195629b5eb0dbae90b5ea9e9d1adc6ab26/pkg/provider/azure_managedDiskController.go#L267-L269

what k8s version are you using now?

**Comment by ialidzhikov** [comment]
> what k8s version are you using now?

1.19.15

PS: This detail is provided in the issue itself. :)

**Comment by andyzhangx** [comment]
https://github.com/kubernetes/kubernetes/pull/107406 should fix this issue, once it's merged into master branch, I will cherry pick to 1.23, 1.22, 1.21, and for the other versions, I think you need to patch with this PR by yourself, thanks.
