### ISSUE TITLE
Job kubelet-gce-e2e-swap-ubuntu failing

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#107412]
### Which jobs are failing?

kubelet-gce-e2e-swap-ubuntu ([config source](https://github.com/kubernetes/test-infra/blob/eaeb5fa7980680e5db6cb6e80bae7dcd63663694/config/jobs/kubernetes/sig-node/containerd.yaml#L1276))

### Which tests are failing?

- E2eNode Suite.[sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
- E2eNode Suite.[sig-node] AppArmor [Feature:AppArmor][NodeFeature:AppArmor] when running with AppArmor should reject an unloaded profile

### Since when has it been failing?

Failures started on 01-04-2022 12:54 PST.

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-ubuntu

### Reason for failure (if possible)

AppArmor feature failure is related to https://github.com/kubernetes/kubernetes/issues/107342.

I don't know the possible cause for Summary API failure.

### Anything else we need to know?

This job was failing previously due to Dockershim deprecation. I moved it to containerd on https://github.com/kubernetes/test-infra/pull/24757 and it was running properly before these failures started.

### Relevant SIG(s)

/sig node

**Comment by mmiranda96** [comment]
Just found an older version of the same issue but in Fedora: https://github.com/kubernetes/kubernetes/issues/104292

**Comment by SergeyKanzhelev** [comment]
from @bobbypage: verbosity is low in logs. If we can repro locally with higher verbosity, it will help.

Alternative: just bump the timeout for now.

**Comment by SergeyKanzhelev** [comment]
this is still flaking

**Comment by mmiranda96** [comment]
I'm trying to reproduce it locally. I'll post an update of my findings soon.

**Comment by SergeyKanzhelev** [comment]
@mmiranda96 do you think this https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.5 failure has the same root cause?

**Comment by SergeyKanzhelev** [comment]
it started failing the same time as https://github.com/kubernetes/kubernetes/issues/107800  and https://github.com/kubernetes/kubernetes/issues/107801 which makes me suspect that increase of timeout wouldn't help. Can you please check?

**Comment by mmiranda96** [comment]
Timeout increase didn't fix the flakiness. I'm taking a deeper dive, I'll update this issue with my findings and if possible, I'll send a PR with the fix.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

still failing with:

```
{ Failure test/e2e_node/summary_test.go:55
Timed out after 187.433s.
Expected
    <string>: Summary
to match fields: {
.Node.Rlimit:
	Expected
	    <string>: RlimitStats
	to match fields: {
	.Time:
		Expected
		    <time.Time>: 2022-06-01T17:43:20Z
		to be <
		    <time.Time>: 2022-06-01T17:43:19.19458117Z
	}
	
[[.Pods[summary-test-8125::stats-busybox-1].Containers[busybox-container].Logs:
	Expected
	    <string>: FsStats
	to match fields: {
	.Time:
		Expected
		    <time.Time>: 2022-06-01T17:43:20Z
		to be <
		    <time.Time>: 2022-06-01T17:43:19.19451287Z
	}
	, .Pods[summary-test-8125::stats-busybox-1].Network:
	Expected
	    <*v1alpha1.NetworkStats | 0x0>: nil
	not to be <nil>, .Pods[summary-test-8125::stats-busybox-1].EphemeralStorage:
	Expected
	    <string>: FsStats
	to match fields: {
	.Time:
		Expected
		    <time.Time>: 2022-06-01T17:43:20Z
		to be <
		    <time.Time>: 2022-06-01T17:43:19.194538335Z
	}
	], [.Pods[summary-test-8125::stats-busybox-0].Containers[busybox-container].Logs:
	Expected
	    <string>: FsStats
	to match fields: {
	.Time:
		Expected
		    <time.Time>: 2022-06-01T17:43:20Z
		to be <
		    <time.Time>: 2022-06-01T17:43:19.19451287Z
	}
	, .Pods[summary-test-8125::stats-busybox-0].Network:
	Expected
	    <*v1alpha1.NetworkStats | 0x0>: nil
	not to be <nil>, .Pods[summary-test-8125::stats-busybox-0].EphemeralStorage:
	Expected
	    <string>: FsStats
	to match fields: {
	.Time:
		Expected
		    <time.Time>: 2022-06-01T17:43:20Z
		to be <
		    <time.Time>: 2022-06-01T17:43:19.194538335Z
	}
	]]
}

test/e2e_node/summary_test.go:330}
```
