### ISSUE TITLE
hardcoded IP in the e2es , should we make it dynamic?

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#107409]
### What happened?

Right now we hardcode an ip in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1198 

```
serviceName := "externalip-test"
		ns := f.Namespace.Name
		externalIP := "203.0.113.250"
		if framework.TestContext.ClusterIsIPv6() {
			externalIP = "2001:DB8::cb00:71fa"
		}
```

### What did you expect to happen?

Id assume someone in an environment with an `203.0.113.250` ip address, or with firewalls that dont allow certain ip ranges ... this would i think fail?

### How can we reproduce it (as minimally and precisely as possible)?

Presumeably, write an iptables rule that blocks this or a range of 203/ addresses... and run this e2e test with `ginkgo.focus="possible to connect to a service via ExternalIP"`...

### Kubernetes version

head

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
that will not fail because it test precisely that the traffic doesn't leave the cluster

**Comment by aojea** [comment]
the IPs are also picked from reserved ranges

https://github.com/kubernetes/kubernetes/blob/8691d6e1eb0e9b0b0b4e61f11e4ade9a0cedac0d/test/e2e/network/service.go#L1194-L1196

**Comment by aojea** [comment]
/close
:smile:

**Comment by jayunit100** [comment]
i saw it failing internally for other reasons (a borked proxy), and was then wondering about it.  in any case, since this goes *through* the service proxy, it seems that a firewall rule could prevent this from working, but, im not sure. 

i dont have a  concrete reproducer though, so fair to close i guess.

**Comment by aojea** [comment]
> i saw it failing internally for other reasons (a borked proxy), and was then wondering about it. in any case, since this goes _through_ the service proxy, it seems that a firewall rule could prevent this from working, but, im not sure.

some CNI or services proxies send the traffic off the cluster and loop it back, ExternalIP is not great defined, this test what works for kube-proxy, it actually worked differently depending on the pod attached to a bridge or using ptp
