### ISSUE TITLE
persistentVolumeClaimRetentionPolicy blocks podManagementPolicy: Parallel

### ISSUE THREAD

**Issue by wsq704252212** [kubernetes/kubernetes#107487]
https://github.com/kubernetes/kubernetes/blob/0a8cc161f69270840045fe8f079620b7a4ab1324/pkg/controller/statefulset/stateful_set_control.go#L425

Should it change to ```isStale && monotonic``` ?
```
if isStale, err := ssc.podControl.PodClaimIsStale(set, replicas[i]); err != nil {
          return &status, err
	} else if isStale && monotonic {
	// If a pod has a stale PVC, no more work can be done this round.
	return &status, err
	} else if !monotonic {
            continue
 }
```

**Comment by Kartik494** [comment]
@wsq704252212 Could you explain the issue a bit more on how does not added `monotonic` blocking   pod management policy
