### ISSUE TITLE
informer miss events if resourceVersion rewinded due to ETCD recover from stale backup.

### ISSUE THREAD

**Issue by M00nF1sh** [kubernetes/kubernetes#107457]
### What happened?

Under an extreme rare case, one of our ETCD cluster restored from backup data, and the APIServers are rotated on new instances with new IPs as well. 

The endpoints/endpointSlices for the "default/kubernetes" service is updated to contain new IPs of the APIServers, but the kube-proxy didn't update the IPtables rules on node for several hours, which makes the cluster unusable.

After investigation, we found that it's due to list+watch mechanism cannot handle a case where ETCD recovered from a stale backup. detailed in event timeline below:

brief event timeline:
* cluster operates normally, and the endpoints of `default/kubernetes` is `[IP1, IP2]`
* `kube-proxy-xxx` was watching endpoints changes start with resourceVersion `1200`
* cluster encounters an event, the ETCD cluster restored from a stale backup with the revision `1000`. (new k8s changes will start got assigned resourceVersion starting from `1001`, resourceVersion rewinded here due to ETCD restore from backup)
* the APIServer updates the endpoints of `default/kubernetes` to be `[IP3, IP4]` with resourceVersion `1001`
* `kube-proxy-xxx` re-requested watch for endpoints changes start with resourceVersion `1200`. (APIServer accepted this request, but it won't sent the above update to the watch due to the resourceVersion `1001` is lower than requested `1200`)
* some more changes to objects happened, and only new changes that got assigned resourceVersion greater than `1200` will be sent to watch and get processed. 

In above example, the Kubernetes control plane recovered the endpoints state correctly after ETCD restored from backup, however, the dataplane component(kube-proxy) is not aware of such change due to resourceVersion rewind. 

(Note: this could be automatically recovered after the resync period of informers, but by default it's several hours).

### What did you expect to happen?

Personally i think it's not a bug since there are other bad impacts due to ETCD restore from stale backup.
However, it would be nice if we can reduce the impact to cluster's availability even under such case. Would like some comments from api/machinery about whether/how Kubernetes should handle this. (e.g. have a way to trigger resync for all informers in data-plane from control-plane proactively).

### How can we reproduce it (as minimally and precisely as possible)?

We can reproduce this issue by restore ETCD from a stale backup, and new changes will get older resourceVersion than what informers already observed, and such change won't be sent to informers.

### Kubernetes version

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wojtek-t** [comment]
Restoring etcd from backup is not an officially supported operation by Kubernetes. There are a lot of edges with that.
To really make it work, you need to actually restart all the control-plane components as well as other clients.
