### ISSUE TITLE
Getting started guide for docker multi-node deployment fails on Ubuntu trusty64

### ISSUE THREAD

**Issue by etcinitd** [kubernetes/kubernetes#10748]
I am trying to setup a test cluster on a few fresh Ubuntu trusty64 VMs using the docker multi-node getting started guide but at the very first stage on the master node, etcd fails to startup with the provided parameters and gives an error:

`2015/07/06 13:20:39 etcd: listen tcp: lookup localhost: no DNS servers`

 Even after I got it up and running with the following changes to parameters:

```
docker -H unix:///var/run/docker-bootstrap.sock run -d \
          --net=host \
          -p 4001:4001 \
          -p 2380:2380 \
          --name etcd \
          -v /opt/etcd:/opt/etcd \
          -v /usr/share/ca-certificates/:/etc/ssl/certs \
          -e "SERVICE_2380_NAME=_etcd-server._tcp" \
          gcr.io/google_containers/etcd:2.0.9 \
          /usr/local/bin/etcd \
          -data-dir /var/etcd/data \
          -name coremaster-01 \
          -listen-client-urls http://172.17.8.100:4001,http://127.0.0.1:2379 \
          -advertise-client-urls http://172.17.8.100:4001 \
          -listen-peer-urls http://172.17.8.100:2380 \
          -initial-advertise-peer-urls http://172.17.8.100:2380 \
          -initial-cluster coremaster-01=http://172.17.8.100:2380 \
          -initial-cluster-state new
```

`etcdctl` still cannot connect to it on the same VM and gives this error:

`Error:  cannot sync with the cluster using endpoints http://127.0.0.1:4001, http://127.0.0.1:2379`

Is this supposed to work the way I am trying to use it or have I completely missed something?
@brendandburns Any ideas?

Thanks in advance.

**Comment by cwahl-Treeptik** [comment]
I got the same problem. Network seems to be unreachable from any container running on the bootstrap Docker:
```
docker -H unix:///var/run/docker-bootstrap.sock run ubuntu ping localhost                                                                                
ping: unknown host localhost
```

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by chenopis** [comment]
Is this even an issue anymore?

**Comment by kargakis** [comment]
Going to close due to age, please reopen if it's still an issue.
