### ISSUE TITLE
leader election migration steps

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#107454]
### What happened?

I am trying to summarize the migration journey to using `Lease` based leader election. 
Hypothetically, let's assume a customer is currently on version `x` and they use `configmaps` based leader election, the migration looks like this:
- version `x+1`: use `configmapsleases` for leader election, this client will use both `configmaps` and `lease` objects, so that new (x+1) client can work with old (x) clients
- version `x+2`: use `lease` for leader election, so new (x+2) client will use `lease` only, and old (x+1) client can work with lease object. (but we can't remove the `configmaps` lock objects yet, looks like the `MultiLock` (x+1 client) relies on the `configmap` lock to be present.) 
- version `x+3`: remove the `configmaps` lock objects from the cluster

https://github.com/kubernetes/kubernetes/blob/12b4bef7bd7ccd6cecd01d3b0b5b8fd31dba9535/staging/src/k8s.io/client-go/tools/leaderelection/resourcelock/multilock.go#L37-L42

### What did you expect to happen?

Is this desired, or can we change `MultiLock` to be forward compatible and work when `configmaps` lock objects are missing? 

### How can we reproduce it (as minimally and precisely as possible)?

N/A

**Comment by tkashem** [comment]
(it's more of a question that needs clarification)

/sig api-machinery
cc @wojtek-t @deads2k

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I know less about this than everyone else involved here.

**Comment by 2uasimojo** [comment]
I'm having trouble understanding why we can't delete the configmaps in version `x+2`. I just tried it and it Worked For Me™. What's the danger/symptom? How can I tell if I've been hit? @tkashem

**Comment by wojtek-t** [comment]
You won't be able to reliably rollback if needed.

**Comment by MikeSpreitzer** [comment]
@tkashem : this should still be an open issue, right?
