### ISSUE TITLE
Are there plans to support the statefulset custom ordinal index

### ISSUE THREAD

**Issue by olderTaoist** [kubernetes/kubernetes#107599]
### What would you like to be added?

statefulset custom ordinal index

### Why is this needed?

i want to deploy one statefulset on multi k8s cluster. but my app depend on headless service，thus i wonder about why statefulset don’t support custom pod oridnal index

**Comment by liggitt** [comment]
looks like #40651 is already open requesting this

/close
/triage duplicate
