### ISSUE TITLE
graceful node shutdown test - improve dbus command to support other distros 

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#107505]
### What happened?

xref: https://github.com/kubernetes/kubernetes/pull/107361#issuecomment-1006987130

Graceful node shutdown test uses `dbus-send` to invoke dbus - https://github.com/kubernetes/kubernetes/blob/3516e76f3da5778400ee06fc2d628fa4560a6b43/test/e2e_node/node_shutdown_linux_test.go#L444

As per https://github.com/kubernetes/kubernetes/pull/107361#issuecomment-1006987130 some distros, don't have `dbus-send` installed so the test must be skipped in those environments. We should consider if we can switch to use  `busctl` or perhaps `busctl` and fall back to `dbus-send` to ensure the test can work across more distros.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

I'm putting kind feature to signify that nothing is really broken in k8s, tests needs improvement.

**Comment by BenTheElder** [comment]
/remove-sig testing

This dbus command should be up to SIG node, though tentatively:
/triage accepted

**Comment by matthyx** [comment]
Do we actually have these other distros available to prevent regressions if we change that?

**Comment by SergeyKanzhelev** [comment]
> Do we actually have these other distros available to prevent regressions if we change that?

the change will be to replace skip logic when `dbus-send` is missing to use an alternative way to send this. So there will be no regression on distros where it currently runs without the skip. Original bug should have a link to job that was failing

**Comment by matthyx** [comment]
@NikhilSharmaWe please have a look at https://github.com/kubernetes/kubernetes/pull/107819
The issue is that the `busctl` command available is too old and doesn't include `emit`.

**Comment by NikhilSharmaWe** [comment]
@matthyx I see, it looks like we are not just adding a condition for `busctl` instead we are replacing it with `dbus`.

It looks you are already working on it. Please inform if I can help in anyway.

Thanks for the response.

**Comment by matthyx** [comment]
Both are possible... it was easier to get a CI signal if that was used in all cases. I might put the condition later.

I am waiting for @bobbypage comments in the PR, but feel free to propose other solutions that might work with older systemd versions.
