### ISSUE TITLE
Public access to validateOnlyAddedTolerations() in package "k8s.io/apimachinery/pkg/api/validation" 

### ISSUE THREAD

**Issue by fjammes** [kubernetes/kubernetes#107560]
### What would you like to be added?

Public access to validateOnlyAddedTolerations() in package "k8s.io/apimachinery/pkg/api/validation" 

See https://github.com/kubernetes/kubernetes/blob/885961cda8875cce192700fe6a32ff57ba706106/pkg/apis/core/validation/validation.go#L3327

### Why is this needed?

When implementing a `validatingWebhook` inside an operator, it might be useful to call `validateOnlyAddedTolerations()` inside the operator's `validateUpdate()` function if the CRD has some tolerations fields.

See this CRD example: https://github.com/lsst/qserv-operator/blob/a4a68b986c9dece794ba4b033e1c515f8d06fbea/config/crd/bases/qserv.lsst.org_qservs.yaml#L2760

**Comment by fedebongio** [comment]
/cc some people for visibility @caesarxuchao @cheftako @deads2k @lavalamp 
@fjammes are you thinking of sending the PR to make the change? thanks
/triage accepted

**Comment by fjammes** [comment]
@fedebongio Sure! I'll make the PR.
