### ISSUE TITLE
Getting started on CoreOS - Single Node Cluster - Error 404

### ISSUE THREAD

**Issue by tdeheurles** [kubernetes/kubernetes#10750]
Just to mention that the [Single Node CoreOS link](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_single_node_cluster.md) have become broken on [the CoreOS page](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/coreos.md)

**Comment by RichieEscarez** [comment]
That document was removed (#9178) and the link was fixed/also removed (#11038). Closing
