### ISSUE TITLE
Improve performance of node selector matcher

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#107504]
### What would you like to be added?

Cache the actual operation of a requirement (for example, as a function) instead of storing it as a string

https://github.com/kubernetes/kubernetes/blob/bf8c918e0be340637e63520eb3b58df493a230f9/vendor/sigs.k8s.io/kustomize/kyaml/yaml/internal/k8sgen/pkg/labels/selector.go#L145:6

### Why is this needed?

When we parse a node selector, we transform the API operation string into another internal string.

Even though we are saving some computing time because the matcher doesn't do validations anymore, we still need to re-parse the operation.

Parsing and matching node selectors is a very common operation throughout the code base, but in particular in scheduler.
We could run the scheduling benchmarks to determine if the change is worth:
- https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf
- https://github.com/kubernetes/kubernetes/blob/bf8c918e0be340637e63520eb3b58df493a230f9/pkg/scheduler/framework/plugins/podtopologyspread/filtering_test.go#L1062

**Comment by MadhavJivrajani** [comment]
@yuzhiquan 👋🏼 
please lmk in case you don't have bandwidth to work on this issue, I'd love to give it a shot :)

**Comment by yuzhiquan** [comment]
@MadhavJivrajani Thanks, i would have a try, will let you known if i need help.

**Comment by NikhilSharmaWe** [comment]
@alculquicondor I would like to work on it if we still need this improvement.
I am not able to fully understand about what we are actually trying to achieve here, what do you mean by `Cache the actual operation of a requirement (for example, as a function) instead of storing it as a string`, could you please elaborate.

I need some help, some similar examples in the repo and code pointers would be really helpful.

**Comment by alculquicondor** [comment]
I believe @yuzhiquan is still working on it.

Think of it this way: the goal is to avoid doing a switch when matching. We already know what the operation is, so we shouldn't need the switch. Figure out a way to do that :) But before merging, you have to verify that it actually improves performance.

I don't have code pointers.
