### ISSUE TITLE
Add healthz subresource in CRD

### ISSUE THREAD

**Issue by hanlins** [kubernetes/kubernetes#107539]
### What would you like to be added?

Add a `healthz` subresource to CRD. User can add this subresource to their CRD by adding a marker like `//+kubebuilder:subresource:healthz,...`, kubebuilder will generate the healthcheck code, and user can query the healthz field to learn the real-time status of the CR.

### Why is this needed?

Currently, CRD only supports `status` and `scale` subresource. Sometimes we want to check the real-time status of a customized resource by sending a health request. Without the `healthz` subresource, we need to send heartbeat to some certain endpoint, and update the `CR` status periodically, which is not elegant and inefficient. With the `healthz` subresource, we don't need to update the CR status periodically, and the health check request is only sent when someone queries the `healthz`.

/sig apps
/sig api-machinery

**Comment by smarterclayton** [comment]
Can you describe in a bit more detail of what the real time check is for?  A CRD once installed should stay working - is this to query when a CRD is successfully installed?

Note that different apiservers in an HA configuration would report “healthy” at different times - are you trying to use this for load balancer inclusion?

Some more details on the use case would be helpful (what scenarios for an unhealthy endpoint would be useful)?

**Comment by hanlins** [comment]
Hi @smarterclayton, thanks for stopping by! In my use case, the CRD abstracts the necessary network infra between my k8s and some remote resource. Upon creation of a CR, one (let's say the apiserver) should be able to talk to some remote endpoint. It would be nice if we can have a per CR `healthz` endpoint so one can check the connectivity status at runtime. In theory the connectivity should be healthy once the CR is realized, but you know in real-world many things could happen that break the connectivity. It would be nice to have such endpoint to reflect the runtime connectivity status on CR status.

**Comment by sftim** [comment]
Kubernetes is level-triggered: the `.status` of a resource tells you its status.

With an APIService then yes you want to know if it's healthy or not, but for a CustomResourceDefinition extension then the API server _knows_ that the thing serving that API is healthy (because the API server itself serves the extension API).

Also: is the `z` suffix helpful here? If I were going to have a subresource for health, I'd use `health`.

**Comment by sftim** [comment]
(If you want to publish an extension API, not following Kubernetes conventins, that reports the status of some resource in a way that a remote client makes sense, then I _think_ you can already do that: define an APIService that implements the API the client wants, and point the APIService at the API you want to check - which could be a CRD).

**Comment by liggitt** [comment]
This is asking for the API server to proxy through calls to /api/mygroup/v1/myresource/foo/healthz to some CRD-author-defined endpoint.

I think this is a specific instance of the general feature request at https://github.com/kubernetes/kubernetes/issues/72637

When that was discussed in API machinery, the feedback was that adding more cases of proxying through the API server was not desired.

**Comment by liggitt** [comment]
Closing this in favor of #72637

**Comment by sftim** [comment]
/remove-triage accepted
based on https://github.com/kubernetes/kubernetes/issues/107539#issuecomment-1013103975

/triage duplicate
is the closer match

**Comment by cndoit18** [comment]
Any updates?
