### ISSUE TITLE
Docs review for changes that affect public website

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#107500]
Changes to some parts of Kubernetes code end up being published within https://kubernetes.io/docs/

Most of that is drawn directly from [k/website](https://github.com/kubernetes/website) but there are also pages in that repo that are generated, with no text changes, from the API docs.

**Feature request:**

Add an optional step to allow tech writers / people with an interest in docs to review API comments, or other any comment that end-up in user-facing documentation.

For example, add a `requires-doc-review` label along with Prow rules to trigger it.

_My rewording / reshaping of a comment by @apelisse in https://github.com/kubernetes/kubernetes/issues/106437#issuecomment-1011237002_

/kind feature
/sig docs
/wg api-expression

**Comment by sftim** [comment]
Some examples of generated documentation:
- [Kubernetes API](https://kubernetes.io/docs/reference/kubernetes-api/)
- [kubectl commands](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands)
- [`kube-scheduler`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/)

**Comment by MdSahil-oss** [comment]
Hey! @sftim would you like to explain it more, because if i assign it to myself so i will need more explaination about issue and it will be my first contribution to kubernetes project so do you think it will be a good start with kubernetes

**Comment by apelisse** [comment]
We should ping some people in the test-infra world if we want to add another layer of approval.

**Comment by apelisse** [comment]
A few thoughts of things we might need to achieve that:
- Have a specific pool of tech-writers/reviewers, maybe defined in [OWNERS](https://github.com/kubernetes/kubernetes/blob/master/OWNERS) or [OWNERS_ALIASES](https://github.com/kubernetes/kubernetes/blob/master/OWNERS_ALIASES)
- Some heuristics to detect that a doc review is needed, a la "api review needed"
- Some new "tech-lgtm-required" label that needs to be missing for PRs to merge in prow, which would be removed automatically when tech review is done.

**Comment by apelisse** [comment]
@thockin thoughts?

**Comment by sftim** [comment]
I'm kind of with letting this rot; I don't see that we have enough resource to staff it.
