### ISSUE TITLE
Add patch annotations to APF API types in next version

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#107574]
As revealed in #104842 and #107547, the Condition slices in FlowSchemaStatus and PriorityLevelConfigurationStatus are missing the `patchStrategy` and `patchMergeKey` annotations that tell strategic merge patch how to handle the slice.

This should be fixed when we make the next version of this API.  See #107549 for exactly how.

@kubernetes/sig-api-machinery-misc 
@wojtek-t 
@deads2k 
@tkashem 
@lavalamp

**Comment by wojtek-t** [comment]
Ref https://github.com/kubernetes/enhancements/issues/1040 for discoverability

@MikeSpreitzer - can we do something else to not forget about it? e.g. add it to GA graduation criteria in a KEP or sth?

**Comment by MikeSpreitzer** [comment]
Linked in #107572 and opened https://github.com/kubernetes/enhancements/pull/3155 .

**Comment by liggitt** [comment]
v1beta3 PR is open at https://github.com/kubernetes/kubernetes/issues/104842 ... should this be done there? are there other changes queued up that should be done in the v1beta3 bump?

**Comment by wojtek-t** [comment]
> v1beta3 PR is open at https://github.com/kubernetes/kubernetes/issues/104842 ... should this be done there?

Yes - this should be done there.

> are there other changes queued up that should be done in the v1beta3 bump?

Renaming of some fields is what we were discussing. From the KEP:

>  In the next version we should rename the AssuredConcurrencyShares to NominalConcurrencyShares.

Those are the only two things that I'm aware of.

@tkashem - please take care of it
@liggitt - thanks for pointing on it

**Comment by MikeSpreitzer** [comment]
That field renaming should be part of the PR that introduces borrowing.
