### ISSUE TITLE
hostPort receiving SNATed packets after upgrading k8s

### ISSUE THREAD

**Issue by yelhouti** [kubernetes/kubernetes#107591]
### What happened?

I upgraded my kubernetes cluster which has an SMTP daemonset with hostPort.
After the upgrade the SMTP server become an open relay.

### What did you expect to happen?

for request received by the daemonset to keep showing the correct source IP.

### How can we reproduce it (as minimally and precisely as possible)?

- Install kubernetes with flannel and kube-proxy IPVS.
- create a deployment with an nginx image with hostPort.
- verify the logs to check that the source IP is the CNI interface one.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Baremetal (Kubespray)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.5 (Arctic Sphynx)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.5 (Arctic Sphynx)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.5"

$ uname -a
Linux node1 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 09:17:08 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Kubespray (default config except flannel instead of calico)
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
flannel
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
do you mean that before the upgrade it wasn't source natting the packets?
what versions are you upgrading from?
what container runtime are you using?

**Comment by yelhouti** [comment]
@aojea yes before the upgrade I was seing the correct IP.
I move from 1.20.7 if I recall correctly to 1.22.
I also moved from docker to containerd

**Comment by aojea** [comment]
> I also moved from docker to containerd

this changes the hostport implementation, with docker there is a hostportmanager in kubernetes, with containerd IIRC you move to use the cni portmap plugin 

https://www.cni.dev/plugins/current/meta/portmap/


it has an snat option, check your CNI configuration and confirm if you are using the snat option, if affirmative disable it
https://www.cni.dev/plugins/current/meta/portmap/

```
{
        "type": "portmap",
        "capabilities": {"portMappings": true},
        "snat": true,
        "markMasqBit": 13,
        "externalSetMarkChain": "CNI-HOSTPORT-SETMARK",
        "conditionsV4": ["!", "-d", "192.0.2.0/24"],
        "conditionsV6": ["!", "-d", "fc00::/7"]
}
```

**Comment by yelhouti** [comment]
@aojea indeed snat wasn't specified and according to the docs defaults to true.
But after switching/adding it to false, and restarting both flannel and kube-proxy it didn't work. What am I missing please ?
And thanks a lot for the help.

**Comment by aojea** [comment]
that config is stateless, depend on the CNI at the creation time of the pod, you have to recreate the pod , restarting flannel and kube-proxy is not going to make any difference.

**Comment by yelhouti** [comment]
@aojea of course I had tried that two, no luck still the same wrong IP.

**Comment by aojea** [comment]
at this point, `iptables-save`., check the rules and figure out who  is snatting  :)

**Comment by yelhouti** [comment]
@aojea even though I am using IPVS you expect this rule to be in iptables ? (sorry if this is a stupid question)

**Comment by thockin** [comment]
yes, IPVS mode still uses iptables for some things, but so does flannel.

**Comment by yelhouti** [comment]
`iptables -S` and `ipvsadm -l` don't show any rule for the specific port.
Anything I can use to see who is playing with me ?

**Comment by aojea** [comment]
`iptables-save` dumps all tables, the rules you are looking for are in the nat table `iptables -S -t nat`

**Comment by yelhouti** [comment]
Thanks a lot @aojea here is the output of the command:
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-N KUBE-MARK-DROP
-N KUBE-MARK-MASQ
-N KUBE-POSTROUTING
-N KUBE-KUBELET-CANARY
-N KUBE-SERVICES
-N KUBE-FIREWALL
-N KUBE-NODE-PORT
-N KUBE-LOAD-BALANCER
-N CNI-HOSTPORT-SETMARK
-N CNI-HOSTPORT-MASQ
-N CNI-HOSTPORT-DNAT
-N CNI-DN-1c854eb4d9c11eb897c96
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A POSTROUTING -m comment --comment "CNI portfwd requiring masquerade" -j CNI-HOSTPORT-MASQ
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 10.233.64.0/18 -d 10.233.64.0/18 -j RETURN
-A POSTROUTING -s 10.233.64.0/18 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
-A POSTROUTING ! -s 10.233.64.0/18 -d 10.233.66.0/24 -j RETURN
-A POSTROUTING ! -s 10.233.64.0/18 -d 10.233.64.0/18 -j MASQUERADE --random-fully
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose" -m set --match-set KUBE-LOOP-BACK dst,dst,src -j MASQUERADE
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-SERVICES ! -s 10.233.64.0/18 -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-SERVICES -m set --match-set KUBE-CLUSTER-IP dst,dst -j ACCEPT
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-NODE-PORT -p tcp -m comment --comment "Kubernetes nodeport TCP port for masquerade purpose" -m set --match-set KUBE-NODE-PORT-TCP dst -j KUBE-MARK-MASQ
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ
-A CNI-HOSTPORT-SETMARK -m comment --comment "CNI portfwd masquerade mark" -j MARK --set-xmark 0x2000/0x2000
-A CNI-HOSTPORT-MASQ -m mark --mark 0x2000/0x2000 -j MASQUERADE
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"1c3f25c7a41a3ff15e6e584d04ed0c4b336cff2b4c9461ad0c62673c15c45f61\"" -m multiport --dports 110,995,143,993,25,465,587 -j CNI-DN-1c854eb4d9c11eb897c96
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 110 -j DNAT --to-destination 10.233.66.112:110
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 995 -j DNAT --to-destination 10.233.66.112:995
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 143 -j DNAT --to-destination 10.233.66.112:143
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 993 -j DNAT --to-destination 10.233.66.112:993
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 25 -j DNAT --to-destination 10.233.66.112:25
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 465 -j DNAT --to-destination 10.233.66.112:465
-A CNI-DN-1c854eb4d9c11eb897c96 -p tcp -m tcp --dport 587 -j DNAT --to-destination 10.233.66.112:587

```
I can indeed see that it is happening here, but this is gibberish to me :(
I am not used to dealing with IP table rules.
Any idea how I can solve my issue please (to disable SNAT or maybe masquerade for hostPort) ?

And do you know if it is flannel or kube-proxy writing the rule, so I can talk to them to hopefully change the default for security reasons...

**Comment by thockin** [comment]
KUBE-* rules are kube-proxy
CNI-* rules are CNI

:)

**Comment by aojea** [comment]
it is the CNI remove this lines

> -A CNI-HOSTPORT-SETMARK -m comment --comment "CNI portfwd masquerade mark" -j MARK --set-xmark 0x2000/0x2000
> -A CNI-HOSTPORT-MASQ -m mark --mark 0x2000/0x2000 -j MASQUERADE

and check the CNI config is correct and nothing overrides it later
https://github.com/kubernetes/kubernetes/issues/107591#issuecomment-1014281292

**Comment by yelhouti** [comment]
@aojea thank you very much, I will do, then restart flannel and see if they get recreated.  
Maybe I should delete all the CNI rules to make sure that on restart they get recreated correctly.
Or is this a bad idea ?

**Comment by aojea** [comment]
> @aojea thank you very much, I will do, then restart flannel and see if they get recreated. Maybe I should delete all the CNI rules to make sure that on restart they get recreated correctly. Or is this a bad idea ?

if they are not recreated after you restart the pods you have a bigger problem :smile:  just remember delete only the CNI* and then, delete the pods so they can be recreated, restarting them is not the same

**Comment by yelhouti** [comment]
@aojea CNI-HOSTPORT-MASQ is referenced here:
> -A POSTROUTING -m comment --comment "CNI portfwd requiring masquerade" -j CNI-HOSTPORT-MASQ
I think I sould delete that two,
And maybe also delete the chain right ?

**Comment by aojea** [comment]
your comment is formatted weirdly and I can't really understand what do you mean , sorry :smile:

**Comment by yelhouti** [comment]
@aojea sorry, fixed

**Comment by aojea** [comment]
when you say deleting those two didn't solve your problem it means the iptables rules are back with the same names?

If is that you have to check your CNI config, is the one that configures the portmap plugin, is the one adding the rules

**Comment by yelhouti** [comment]
@aojea what I mean by didn't solve my problem is: pod still received requests with source ip from cni-0 interface.

**Comment by aojea** [comment]
you have to check again the iptables rules and find the ones doing the masquerading, I know I know, this process is tedious :upside_down_face:

**Comment by yelhouti** [comment]
here is my diagnoses:
iptables -S -t nat
```
-P PREROUTING ACCEPT
-P INPUT ACCEPT
-P POSTROUTING ACCEPT
-P OUTPUT ACCEPT
-N KUBE-MARK-DROP
-N KUBE-MARK-MASQ
-N KUBE-KUBELET-CANARY
-N CNI-HOSTPORT-DNAT
-N CNI-DN-5c33fd2f7ac2c23831042
-N KUBE-PROXY-CANARY
-N KUBE-SERVICES
-N KUBE-POSTROUTING
-N KUBE-FIREWALL
-N KUBE-NODE-PORT
-N KUBE-LOAD-BALANCER
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 10.233.64.0/18 -d 10.233.64.0/18 -j RETURN
-A POSTROUTING -s 10.233.64.0/18 ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
-A POSTROUTING ! -s 10.233.64.0/18 -d 10.233.66.0/24 -j RETURN
-A POSTROUTING ! -s 10.233.64.0/18 -d 10.233.64.0/18 -j MASQUERADE --random-fully
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -m addrtype --dst-type LOCAL -j CNI-HOSTPORT-DNAT
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A CNI-HOSTPORT-DNAT -p tcp -m comment --comment "dnat name: \"cbr0\" id: \"7fe553222b88aae215c8cbd7868b29bc602137358f1f777b5ea61f249592e4cd\"" -m multiport --dports 110,995,143,993,25,465,587 -j CNI-DN-5c33fd2f7ac2c23831042
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 110 -j DNAT --to-destination 10.233.66.132:110
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 995 -j DNAT --to-destination 10.233.66.132:995
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 143 -j DNAT --to-destination 10.233.66.132:143
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 993 -j DNAT --to-destination 10.233.66.132:993
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 25 -j DNAT --to-destination 10.233.66.132:25
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 465 -j DNAT --to-destination 10.233.66.132:465
-A CNI-DN-5c33fd2f7ac2c23831042 -p tcp -m tcp --dport 587 -j DNAT --to-destination 10.233.66.132:587
-A KUBE-SERVICES ! -s 10.233.64.0/18 -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
-A KUBE-SERVICES -m addrtype --dst-type LOCAL -j KUBE-NODE-PORT
-A KUBE-SERVICES -m set --match-set KUBE-CLUSTER-IP dst,dst -j ACCEPT
-A KUBE-POSTROUTING -m comment --comment "Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose" -m set --match-set KUBE-LOOP-BACK dst,dst,src -j MASQUERADE
-A KUBE-POSTROUTING -m mark ! --mark 0x4000/0x4000 -j RETURN
-A KUBE-POSTROUTING -j MARK --set-xmark 0x4000/0x0
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE --random-fully
-A KUBE-FIREWALL -j KUBE-MARK-DROP
-A KUBE-NODE-PORT -p tcp -m comment --comment "Kubernetes nodeport TCP port for masquerade purpose" -m set --match-set KUBE-NODE-PORT-TCP dst -j KUBE-MARK-MASQ
-A KUBE-LOAD-BALANCER -j KUBE-MARK-MASQ

```
<details>
Chain PREROUTING (policy ACCEPT 58687 packets, 4700K bytes)
pkts bytes target     prot opt in     out     source               destination
82770 6151K KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
34324 3282K CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 36932 packets, 3467K bytes)
pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 95179 packets, 6723K bytes)
pkts bytes target     prot opt in     out     source               destination
121K 8296K KUBE-POSTROUTING  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes postrouting rules */
46131 2779K RETURN     all  --  *      *       10.233.64.0/18       10.233.64.0/18
24335 1464K MASQUERADE  all  --  *      *       10.233.64.0/18      !224.0.0.0/4          random-fully
10   548 RETURN     all  --  *      *      !10.233.64.0/18       10.233.66.0/24
0     0 MASQUERADE  all  --  *      *      !10.233.64.0/18       10.233.64.0/18       random-fully

Chain OUTPUT (policy ACCEPT 77703 packets, 5691K bytes)
pkts bytes target     prot opt in     out     source               destination
79320 5792K KUBE-SERVICES  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service portals */
22941 1376K CNI-HOSTPORT-DNAT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain KUBE-MARK-DROP (1 references)
pkts bytes target     prot opt in     out     source               destination
0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x8000

Chain KUBE-MARK-MASQ (3 references)
pkts bytes target     prot opt in     out     source               destination
4   250 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000

Chain KUBE-KUBELET-CANARY (0 references)
pkts bytes target     prot opt in     out     source               destination

Chain CNI-HOSTPORT-DNAT (2 references)
pkts bytes target     prot opt in     out     source               destination
10   548 CNI-DN-5c33fd2f7ac2c23831042  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "cbr0" id: "7fe553222b88aae215c8cbd7868b29bc602137358f1f777b5ea61f249592e4cd" */ multiport dports 110,995,143,993,25,465,587

Chain CNI-DN-5c33fd2f7ac2c23831042 (1 references)
pkts bytes target     prot opt in     out     source               destination
0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:10.233.66.132:110
0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:10.233.66.132:995
0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:10.233.66.132:143
1    40 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:10.233.66.132:993
9   508 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:10.233.66.132:25
0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:10.233.66.132:465
0     0 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:10.233.66.132:587

Chain KUBE-PROXY-CANARY (0 references)
pkts bytes target     prot opt in     out     source               destination

Chain KUBE-SERVICES (2 references)
pkts bytes target     prot opt in     out     source               destination
4   250 KUBE-MARK-MASQ  all  --  *      *      !10.233.64.0/18       0.0.0.0/0            /* Kubernetes service cluster ip + port for masquerade purpose */ match-set KUBE-CLUSTER-IP dst,dst
133  9210 KUBE-NODE-PORT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
18  1090 ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            match-set KUBE-CLUSTER-IP dst,dst

Chain KUBE-POSTROUTING (1 references)
pkts bytes target     prot opt in     out     source               destination
0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Kubernetes endpoints dst ip:port, source ip for solving hairpin purpose */ match-set KUBE-LOOP-BACK dst,dst,src
295 18853 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0x4000/0x4000
4   250 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK xor 0x4000
4   250 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */ random-fully

Chain KUBE-FIREWALL (0 references)
pkts bytes target     prot opt in     out     source               destination
0     0 KUBE-MARK-DROP  all  --  *      *       0.0.0.0/0            0.0.0.0/0

Chain KUBE-NODE-PORT (1 references)
pkts bytes target     prot opt in     out     source               destination
0     0 KUBE-MARK-MASQ  tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* Kubernetes nodeport TCP port for masquerade purpose */ match-set KUBE-NODE-PORT-TCP dst

Chain KUBE-LOAD-BALANCER (0 references)
pkts bytes target     prot opt in     out     source               destination
0     0 KUBE-MARK-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0
</details>
I think I found the culprit(s):
```
Chain KUBE-MARK-MASQ (3 references)
pkts bytes target     prot opt in     out     source               destination
4   250 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK or 0x4000
```
The KUBE-MARK-MASQ rule tells k8s to mark all packets that for masquerade.
It is chained to from:
```
-A KUBE-SERVICES ! -s 10.233.64.0/18 -m comment --comment "Kubernetes service cluster ip + port for masquerade purpose" -m set --match-set KUBE-CLUSTER-IP dst,dst -j KUBE-MARK-MASQ
```
Which is always chained to form:
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
```
I read [here](https://www.stackrox.io/blog/kubernetes-networking-demystified/) that :
> KUBE-MARK-MASQ adds a Netfilter mark to packets destined for the hello-world service which originate outside the cluster’s network. Packets with this mark will be altered in a POSTROUTING rule to use source network address translation (SNAT) with the node’s IP address as their source IP address.

But I could not find the the specific rule that masquerades everything marked with 0x4000.

Not what I want to know is: is my CNI responsible for adding the rule that should hijack the process when I use hostPort, or is kube supposed to add a rule when I use hostPort that supersedes this one makes me not pass their.

**Comment by uablrek** [comment]
From where are you testing? If your test client is on the k8s node then source from cni-0 is correct!

And please remember that `hostPort` is not handled by `kube-proxy` and not even the CNI-plugin I believe (but I am unsure about that). It is handled mainly by the CRI-plugin (via kubelet).

**Comment by uablrek** [comment]
That would explain why this happens when you upgrade dockershim -> containerd.

**Comment by yelhouti** [comment]
@uablrek thanks from answering, I am testing from outside the cluster.

**Comment by yelhouti** [comment]
@uablrek any suggestion on what I should do to fix this please ?

**Comment by uablrek** [comment]
Not really. I have setup a cluster with `flannel:v0.15.1` and proxy-mode=ipvs to try to re-create the problem but I don't get any "CNI*" entries at all in iptables. And source is preserved as expected (both ipv4 and ipv6).

Here is my iptables dump;
```
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N KUBE-FIREWALL
-N KUBE-FORWARD
-N KUBE-KUBELET-CANARY
-N KUBE-NODE-PORT
-A INPUT -m comment --comment "kubernetes health check rules" -j KUBE-NODE-PORT
-A INPUT -j KUBE-FIREWALL
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD
-A FORWARD -s 11.0.0.0/16 -j ACCEPT
-A FORWARD -d 11.0.0.0/16 -j ACCEPT
-A OUTPUT -j KUBE-FIREWALL
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-FIREWALL ! -s 127.0.0.0/8 -d 127.0.0.0/8 -m comment --comment "block incoming localnet connections" -m conntrack ! --ctstate RELATED,ESTABLISHED,DNAT -j DROP
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A KUBE-NODE-PORT -m comment --comment "Kubernetes health check node port" -m set --match-set KUBE-HEALTH-CHECK-NODE-PORT dst -j ACCEPT
```

A difference is that I use `cri-o` as CRI-plugin. This may be significant. If possible try with `cri-o`.

I expose port 8080 as hostPort, mapped to port 80 in the http server (not nginx) in a pod. Here are the open ports;
```
vm-002 ~ # netstat -putln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      286/crio            
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      337/kube-proxy      
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      335/kubelet         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      216/dropbear        
tcp6       0      0 :::10010                :::*                    LISTEN      286/crio            
tcp6       0      0 :::8080                 :::*                    LISTEN      286/crio            
tcp6       0      0 :::53                   :::*                    LISTEN      468/coredns         
tcp6       0      0 :::10255                :::*                    LISTEN      335/kubelet         
tcp6       0      0 :::10250                :::*                    LISTEN      335/kubelet         
tcp6       0      0 :::23                   :::*                    LISTEN      122/inetd           
tcp6       0      0 :::22                   :::*                    LISTEN      216/dropbear        
tcp6       0      0 :::10256                :::*                    LISTEN      337/kube-proxy      
tcp6       0      0 :::80                   :::*                    LISTEN      122/inetd           
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -                   
udp6       0      0 :::8472                 :::*                                -                   
udp6       0      0 :::53                   :::*                                468/coredns         
```
As you can see port 8080 is opened by `crio` both on ipv4 and ipv6.

**Comment by uablrek** [comment]
Tried with some other CNI-plugins; `cilium:v1.10.4`, `calico/cni:v3.19.1` and `antrea-ubuntu:v1.4.0`, and source is preserved for all.

I think you can consider hostPort to be CNI-plugin agnostic.

I suspect `containerd`, but that I can't test `containerd` in my environment, sorry.

**Comment by yelhouti** [comment]
Could you please test with kubespray ? (only config to change is flannel). I would be very grateful if you could pinpoint this to docker vs containerd

**Comment by uablrek** [comment]
No, sorry. My environment is flexible but primitive. It shouldn't be Kubespray though. It must be the thing that causes the "CNI*" iptables rules. I didn't see them in with any CNI-plugin.

**Comment by uablrek** [comment]
> ...not even the CNI-plugin I believe (but I am unsure about that)

I was partially right. The K8s cni-plugin, like flannel, calico or whatever is *not* used for `hostPort`. The CRI-plugin *may* however use a CNI-plugin such as `portmap`. I don't think `cri-o` uses `portmap` but I am not sure so I made a [slack query](https://kubernetes.slack.com/archives/CAZH62UR1/p1643259553066600).

**Comment by uablrek** [comment]
Got an answer from @aojea. Cri-o has it's own hostPort implementation https://github.com/cri-o/cri-o/tree/main/internal/hostport.

This is not a K8s bug, so I close this issue. It is not a `flannel` bug either so you should close https://github.com/flannel-io/flannel/issues/1528.

The problem is with `containerd`.

/close

**Comment by uablrek** [comment]
Possible work-around; switch CRI-plugin to `cri-o`.

**Comment by uablrek** [comment]
It might also be possible to configure `containerd` in some way. But I don't know how.

**Comment by yelhouti** [comment]
@uablrek I tried crio, same issue, please /reopen

**Comment by uablrek** [comment]
/reopen

Crio does not set any "CNI-*" rules at all.

**Comment by yelhouti** [comment]
@uablrek it is flannel, I created a fresh cluster with: `--ip-masq=false` instead of `--ip-masq` and the problem disappeared.
Although the [doc](https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#key-command-line-options)
> --ip-masq=false: setup IP masquerade for traffic destined for outside the flannel network. Flannel assumes that the default policy is ACCEPT in the NAT POSTROUTING chain.

although this seems to indicate that `--ip-mask` only affects outgoing traffic, it doesn't. I created an issue on both flannel and kubepray.
I ll try this setup, hopping it doesn't create bigger problems down the line.

**Comment by aojea** [comment]
> The way I understand it, its a flannel issue as the other parts are standards and I tried calico with the same portmap plugin it worked correctly.

@yelhouti glad you found it

We try to track only the issues that affect Kubernetes itself, since this is not a kubernetes issue we suggest you to open the issue in the corresponding project and close this one.

Thanks

**Comment by dcbw** [comment]
/close
as this issue appears to be flannel-cni-plugin
