### ISSUE TITLE
controller-manager failed to start endpoint slice controller, leading to stale iptable rules

### ISSUE THREAD

**Issue by mhadimani** [kubernetes/kubernetes#107583]
### What happened?

We came across a scenario where our services were not able to reach their respective endpoints because of an issue with the endpoint slices not being updated with the correct IP. This lead to kube-proxy having stale iptable rules

The controller-manager was up and running all the time and we had to restart the controller-manager service to resolve the issue.

On troubleshooting further, we came across an error where the controller-manager was not able to load the endpointSlice controller because the discovery resource was not available.

Logs:
<img width="1656" alt="log1" src="https://user-images.githubusercontent.com/69571543/149625313-0bd17001-3c73-49e4-a9c0-d571f7b83d9a.png">

![log2](https://user-images.githubusercontent.com/69571543/149625356-38ac1381-d726-4247-b541-1d14c8792914.png)

<img width="1656" alt="log3" src="https://user-images.githubusercontent.com/69571543/149625359-efb6e8c6-ca2e-42c7-b882-a51284421ab1.png">

Any suggestions on how we can overcome this would be great.

Thanks,

### What did you expect to happen?

The controller-manager could have been in an error state, not up & running. This could have alerted or may be a fail-over to another instance.

### How can we reproduce it (as minimally and precisely as possible)?

This is hard to replicate but you could try this -
1. Have 2 instances of controller-manager components and 1 api-server
2. Restart the leader controller-manager
3. Wait for a few seconds, restart the api-server

### Kubernetes version

# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:06:15Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.10", GitCommit:"8152330a2b6ca3621196e62966ef761b8f5a61bb", GitTreeState:"clean", BuildDate:"2021-08-11T18:00:37Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

NA

### OS version

centos 7

**Comment by aojea** [comment]
Hmm, this maybe an unsupported skew version scenario https://kubernetes.io/releases/version-skew-policy/

**Comment by aojea** [comment]
@mhadimani the endpointslice controller is a symptom , the error message complains about a lot resources, you have a problem with the apiserver

**Comment by thockin** [comment]
Is this a transient error (i.e. the apiserver eventually comes up and these controllers retry) or are they perma-stuck until restart?

Maybe we need some retry internally?

**Comment by mhadimani** [comment]
Hi @aojea ,

This is a not a problem with the api-server, it's possible that the api-server could have gone bad at that moment and may be was in the process of a fail over to another instance.

All our api-servers are running 1.20 version

But the issue is with controller-manager, if a request to get the api resources fail, the controller-manager silently ignores loading those components and keeps running. Is this expected ?

Although, this could happen for any component, there has to be some mechanism where the controller retries/reports an error or something similar.

The endpoint slice controller is an important one and ignoring this would have a broader impact.

**Comment by mhadimani** [comment]
Hey @thockin ,
This was a perma-stuck, we had to manually restart to get this fixed.

There is a retry of 2 times but looks like this hasn't helped much.

Check here - https://github.com/kubernetes/kubernetes/blob/ec1738576d8511a4cc03973d26b5606ec04e8693/cmd/kube-controller-manager/app/controllermanager.go#L444
and
https://github.com/kubernetes/kubernetes/blob/1367cca8fd67b09606b01c0a9e46cef59aef3424/staging/src/k8s.io/client-go/discovery/discovery_client.go#L222

**Comment by aojea** [comment]
per your last comments it seems that there are more things that may be affecting,a full log of the controller-manager will be useful

**Comment by dcbw** [comment]
@mhadimani could you provide a full controller-manager log per https://github.com/kubernetes/kubernetes/issues/107583#issuecomment-1018261352 ?

**Comment by PradeepKumar-15** [comment]
@aojea @dcbw 
controller-manager log file that shows 'endpointslice-controller' startup was skipped is attached with this post.
Look for line _'Not starting endpointslice-controller since discovery.k8s.io/v1beta1 resources are not available'_

[kube-controller-manager-log.txt](https://github.com/kubernetes/kubernetes/files/8037153/kube-controller-manager-log.txt)

**Comment by PradeepKumar-15** [comment]
Fyi @mhadimani

**Comment by PradeepKumar-15** [comment]
I am pretty new to go and this code base so i could be way off here but i think the error is resulting out of this function: https://github.com/kubernetes/kubernetes/blob/ec1738576d8511a4cc03973d26b5606ec04e8693/staging/src/k8s.io/client-go/discovery/discovery_client.go#L347

Looks like 'ServerGroupsAndResources' function in discovery_client.go is returning the apiGroups, map of apiResources and errors up the code path to 'GetAvailableResources' function in controllermanager.go which in turn returns 'nil' resources only if the entire 'resourceMap' from discovery_client is empty.
https://github.com/kubernetes/kubernetes/blob/ec1738576d8511a4cc03973d26b5606ec04e8693/cmd/kube-controller-manager/app/controllermanager.go#L444

Otherwise, it continues with the code path using the returned resources list (and only logs about the errored apigroups). As the returned resourceMap from discovery_client did not have endpointslice resource (as per the log file i attached earlier), startup of corresponding controller is getting skipped in my opinion.

**Comment by aojea** [comment]
the lease for leader election is not being renewed, I don't know if the controller manager should bail out at that point 

> Feb 09 17:15:06 dummy-host1 kube-controller-manager[3822]: E0209 17:15:06.246348    3822 leaderelection.go:361] Failed to update lock: the server is currently unable to handle the request (put leases.coordination.k8s.io kube-controller-manager)

> Feb 09 17:15:11 dummy-host1 kube-controller-manager[3822]: E0209 17:15:11.253926    3822 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server is currently unable to handle the request (get leases.coordination.k8s.io kube-controller-manager)

you have multiple errors against the apiserver, maybe a  broken webhook?

>Feb 09 17:15:10 dummy-host1 kube-controller-manager[3822]: E0209 17:15:10.865358    3822 controllermanager.go:446] unable to get all supported resources from server: unable to retrieve the complete list of server APIs: apiregistration.k8s.io/v1beta1: the s
erver is currently unable to handle the request, authentication.istio.io/v1alpha1: the server is currently unable to handle the request, authentication.k8s.io/v1beta1: the server is currently unable to handle the request, autoscaling/v1: the server is currently unable to handle the
request, discovery.k8s.io/v1beta1: the server is currently unable to handle the request, samcrd.salesforce.com/v1: the server is currently unable to handle the request, scheduling.k8s.io/v1: the server is currently unable to handle the request, storage.k8s.io/v1: the server is curre
ntly unable to handle the request, v1: the server is currently unable to handle the request


> Feb 09 17:15:14 dummy-host1 kube-controller-manager[3822]: E0209 17:15:14.716154    3822 resource_quota_controller.go:162] initial discovery check failure, continuing and counting on future sync update: unable to retrieve the complete list of server APIs: apiextensions.k8s.io/v1beta1: the server is currently unable to handle the request, apiregistration.k8s.io/v1beta1: the server is currently unable to handle the request, authentication.k8s.io/v1beta1: the server is currently unable to handle the request, batch/v1: the server is currently unable to handle the request, networking.k8s.io/v1: the server is currently unable to handle the request, node.k8s.io/v1: the server is currently unable to handle the request, rbac.istio.io/v1alpha1: the server is currently unable to handle the request, samcrd.salesforce.com/v1: the server is currently unable to handle the request, storage.k8s.io/v1beta1: the server is currently unable to handle the request, v1: the server is currently unable to handle the request

that setup is not healthy,

**Comment by mhadimani** [comment]
Hi @aojea 
We have been trying to replicate this issue in our env and from our observations, the controller does not proceed into querying the API server for API resources unless it has been successful in the leader election process.

Is this not the case ?

From the logs, we still see the PUT call to update the lease has failed -

Feb 09 17:15:06 dummy-host1 kube-controller-manager[3822]: E0209 17:15:06.246348    3822 leaderelection.go:361] Failed to update lock: the server is currently unable to handle the request (put leases.coordination.k8s.io kube-controller-manager)

**Comment by PradeepKumar-15** [comment]
I was reviewing the whole log and noticed that this controller-manager instance had issues with either updating/fetching the lease object at only 2 timestamps 17:15:06 and 17:15:11 which is still within 15 seconds from 17:15:03 (15 seconds is the lease timeout) after it assumed leader role and it could be the reason it did not bail out yet.
  
  We also noticed that around this same time frame, one of the 5 apiservice instances (fronted by haproxy to balance requests b/w api service instances) went offline. My theory is that when controller manager assumed leader role and started services needed by a leader, a couple of lease get/update requests and a couple of many concurrent rest calls to create apiResources list made by 'fetchGroupVersionResources' function ended up with this apiserver (that was either unresponsive/unhealthy) causing error response 'the server is currently unable to handle the request' to the rest calls made.
  
 After time stamp 17:15:06 - 17:15:11, i did not see any errors in the log which could indicate controller-manager had issues to get/update the kube-controller-manager lease object (at least not for the next 30 min). Though not often, we have seen this same issue occur twice in the past 3 months. I was thinking if introducing a retry when error object returned from discoveryClient.ServerGroupsAndResources()  here: https://github.com/kubernetes/kubernetes/blob/ec1738576d8511a4cc03973d26b5606ec04e8693/cmd/kube-controller-manager/app/controllermanager.go#L444 specifically says 'the server is currently unable to handle the request' for certain apigroupVersions (but successfully gets resourceslist for other apigroupVersions).

**Comment by PradeepKumar-15** [comment]
I am trying to share the rest of the log file but it has too much of company specific information so i am trying to remove the before uploading the log file here

**Comment by PradeepKumar-15** [comment]
Another reason i can think of to either restart controller-manager ( or ) introduce a retry if endpointslice resource is not returned by 'discoveryClient.ServerGroupsAndResources() ' is to avoid issues with kube-proxy. I think starting 1.20, kube-proxy now watches for change in endpointslices and updates the iptables (unlike previous versions where kube-proxy used endpoints). If we run into a case that causes endpointslice controller startup to be skipped, i think its safe to restart controller-manager instead of just moving forward..
@aojea @dcbw @mhadimani

**Comment by aojea** [comment]
> Another reason i can think of to either restart controller-manager ( or ) introduce a retry if endpointslice resource is not returned by 'discoveryClient.ServerGroupsAndResources() ' is to avoid issues with kube-proxy. I think starting 1.20, kube-proxy now watches for change in endpointslices and updates the iptables (unlike previous versions where kube-proxy used endpoints). If we run into a case that causes endpointslice controller startup to be skipped, i think its safe to restart controller-manager instead of just moving forward..

I would not focus on the detail of the enpoints or endpoint slices controller, the root cause here is that the controller manager is not behaving correctly, you can skip one controller but other things will fail and your cluster will not be usable one way or the other, the important here is that the controller manager recovers ...

The leader election logic should fail and restart the controller manager if is not able to get the lock to confirm it is the leader, if that is not happening then there is the bug.

**Comment by PradeepKumar-15** [comment]
The leader election logic should fail and restart the controller manager if is not able to get the lock to confirm it is the leader, if that is not happening then there is the bug.
>> In the case i described here (which does not happen often though), the controller-manager is able to get lock (update lease object) and establish itself as leader in 1 or 2 retries of connecting to apiserver. The problem i think is that controller-manager does not attempt to restart itself and start the leader election again if for some reason decides to skip starting of few important controllers like endpoint controller/deployment controller/replicaset controller etc. Though not so often, it results in a bad state when it hits.
@aojea

**Comment by aojea** [comment]
So, let's recap,  you are saying that:
1. controller manager starts and becomes leader
2. some errors happens communicating to the apiserver and some internal controllers of the controller manager doesn't start
3. the errors are not enough to lose the leader and restart the controller manager
4. the controller manager keeps working but some internal controllers are never working again

**Comment by PradeepKumar-15** [comment]
Yes, you accurately described the problem i noticed a few times now.

**Comment by khenidak** [comment]
Step 3 does not make complete sense https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L277 

@PradeepKumar-15  can you check that you have disabled leader-election? (https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L227) 

Otherwise we need to look at go client and check that leader election lease lose actually triggers as expected.

**Comment by PradeepKumar-15** [comment]
No, we do not have leader-election disabled.

**Comment by zhouhaibing089** [comment]
This might be related - https://github.com/kubernetes/kubernetes/pull/111673

**Comment by PradeepKumar-15** [comment]
@zhouhaibing089 Yes, https://github.com/kubernetes/kubernetes/pull/111673 is definitely related to the problem we observed in this issue. Thank you for the PR and if i am reading it right, you are returning nil when discoveryClient cannot get list of all supported apigroups and resources without errors and i assume returning nil will force controller manager to restart ?

**Comment by zhouhaibing089** [comment]
@PradeepKumar-15: By returning an error (rather than just logging it), kube-controller-manager will fatal loudly:

```go
		controllerContext, err := CreateControllerContext(c, clientBuilder, ctx.Done())
		if err != nil {
			klog.Fatalf("error building controller context: %v", err)
		}
```
