### ISSUE TITLE
No one can solve this bug?

### ISSUE THREAD

**Issue by felix0080** [kubernetes/kubernetes#107524]
### What happened?

https://github.com/kubernetes/kubernetes/issues/82958

### What did you expect to happen?

https://github.com/kubernetes/kubernetes/issues/82958

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/kubernetes/issues/82958

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/issues/82958

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wzshiming** [comment]
Please come back to #82958 to continue our discussion
/close
