### ISSUE TITLE
Problems in preempt `pickOneNodeForPreemption`?

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#107600]
### What happened?

Part1:
https://github.com/kubernetes/kubernetes/blob/8815a3119cc8bd82703f3fc5e5c715ec61dfc1ff/pkg/scheduler/framework/preemption/preemption.go#L429-L437
We want to find the minimum highest priority victims, however slice will cache the result. 
For example, we have four nodes to pick up, their `victims.Pods[0]`'s priorities are 1000, 1000, 1000, 10, 
current result  of minNodes2 will be [node3, node1, node2]. 
I think it's not as expected, the expected result should be [node3], right?
And we can change with this.
```golang
 highestPodPriority := corev1helpers.PodPriority(victims.Pods[0]) 
 if highestPodPriority < minHighestPriority { 
 	minHighestPriority = highestPodPriority 
 	minNodes2 = nil
 	lenNodes2 = 0 
 } 
 if highestPodPriority == minHighestPriority { 
 	minNodes2 = append(minNodes2, node)
 	lenNodes2++ 
 } 
```

Part2: 
https://github.com/kubernetes/kubernetes/blob/8815a3119cc8bd82703f3fc5e5c715ec61dfc1ff/pkg/scheduler/framework/preemption/preemption.go#L446-L465

A little confused why we loop `lenNodes2` but update `minNodes1`. Or we should find nodes in`minNodes2`?

### What did you expect to happen?

Describe as above. Correct me if I misunderstood the logic.

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

<details>

```console
Master Branch
```
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by denkensk** [comment]
I think it may be not a bug, just a trick to save memory. 

Part1：
Even the `minNodes2 ` contains [node3, node1, node2]. But the `lenNodes2` is still 1. So when traversing later, only the first element will be traversed, just `node3`.

Part2:
It is correct to update `minNodes1`.  We just put the result of `minNodes2` in `minNodes1` and update the `lenNodes1 `.

**Comment by kerthcet** [comment]
> I think it may be not a bug, just a trick to save memory.
> 
> Part1： Even the `minNodes2 ` contains [node3, node1, node2]. But the `lenNodes2` is still 1. So when traversing later, only the first element will be traversed, just `node3`.
> 
> Part2: It is correct to update `minNodes1`. We just put the result of `minNodes2` in `minNodes1` and update the `lenNodes1 `.

Oh yes, thanks alex, I also found the comment above. close then.
