### ISSUE TITLE
podman pre-installs its own CNI, interfering with bootstrap of other CNIs

### ISSUE THREAD

**Issue by fasaxc** [kubernetes/kubernetes#107687]
### What happened?

Not really sure how to report this, it seems like an incompatibility with another program's use of the CNI config directory.

podman (like kubernetes) seems ot use CNI for its networking.  On systems like RHCoreOS that pre-install podman, podman pre-installs its own CNI plugin and the `87-podman-bridge.conflist` CNI netconf.  This conflicts/races with installing a kubernetes CNI plugin such as Calico.  kubelet thinks there's a CNI plugin installed so it starts networking pods and they come up with podman IPs instead of waiting for Calico's DaemonSet to launch.

This was reported by a Calico user, I would have expected this to be prevented by kubelet's node status having the network not ready but they reported pods coming up with non-Calico IPs.

### What did you expect to happen?

kubelet should wait for the "kubernetes" CNI to be installed.  Maybe k8s and podman should have separate CNI config directories?

### How can we reproduce it (as minimally and precisely as possible)?

Use kubeadm to create a cluster on RH CoreOS, try to schedule pods super early on a new node before Calico (or CNI of choice) has finished bootstrapping.

### Kubernetes version

<details>

```console
$ kubectl version
v1.21.4
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>
CoreOS 34.20210725.3.0

```console
# On Linux:
$ cat /etc/os-release
NAME=Fedora
VERSION="34.20210725.3.0 (CoreOS)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora CoreOS 34.20210725.3.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='34.20210725.3.0'
DEFAULT_HOSTNAME=localhost

$ uname -a


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
Not sure; podman is installed but I'm not sure if k8s is using it
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.21.1
</details>

**Comment by aojea** [comment]
> kubelet should wait for the "kubernetes" CNI to be installed. Maybe k8s and podman should have separate CNI config directories?

heh, you are going to like this, kubelet doesn't check the cni folder (since the dockershim removal)

https://github.com/kubernetes/kubernetes/blob/5c9c181698c0a8944057c2d4c15ad78de8a96319/pkg/kubelet/kubelet.go#L2320-L2326

it is the container runtime, kubelet polls the runtime using the CRI API, the CNI is competence of the runtime, there is nothing that kubelet can do that

**Comment by afbjorklund** [comment]
This is a known issue, the suggestion is to move the podman CNI directory away from the Kubernetes location.

Kubernetes used the first CNI config (in alphabetical order), and there was no way to change this behaviour...

**Comment by fasaxc** [comment]
> it is the container runtime, kubelet polls the runtime using the CRI API, the CNI is competence of the runtime, there is nothing that kubelet can do

Has the NetworkUnavailable taint gone away; I'm wondering how pods get scheduled to this node.  Maybe their (CSI-related) pods are tolerating the taint.

**Comment by afbjorklund** [comment]
`nerdctl` creates the network on-the-fly, or it would have had the same issue (break-on-install)

`containerd` doesn't ship the cri/cni configuration, unless you go for the alternative download...

```
/etc/cni/net.d/10-containerd-net.conflist
```

`crio` does install a cni network, but most users installing that tool expect it to interfere with k8s

it might get lucky due to the alphabetic sorting or something, with carefully named config files

```
/etc/cni/net.d/100-crio-bridge.conf
/etc/cni/net.d/200-loopback.conf
```

**Comment by fasaxc** [comment]
Maybe the CNI netconf needs a field that sets which CNI users should use/ignore that CNI netconf.  IDK, bit of a mess to assume that there'll be one CNI that it right for everything on the system.

**Comment by aojea** [comment]
> Maybe the CNI netconf needs a field that sets which CNI users should use/ignore that CNI netconf. IDK, bit of a mess to assume that there'll be one CNI that it right for everything on the system.

cni folks were/are working in the next version, maybe this is good feedback for them @squeed @dcbw

**Comment by fasaxc** [comment]
Good idea: 
https://github.com/containernetworking/cni/issues/878

**Comment by afbjorklund** [comment]
Pretty sure we discussed this as length, where other third party tools were asked to stay out of Kubernetes directories.

Will link if I can find it.
