### ISSUE TITLE
All kubectl commands should be covered by e2e tests

### ISSUE THREAD

**Issue by jlowdermilk** [kubernetes/kubernetes#10764]
`hack/test-cmd.sh` is good, but insufficient, as some of the commands exercise provider-specific logic. We need e2e coverage for every kubectl command that talks to the server, at least for defaults.

- [x] [kubectl api-versions](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_api-versions.md)	 - Print available API versions.
- [x] [kubectl cluster-info](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_cluster-info.md)	 - Display cluster info
- [x] ~~[kubectl config](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_config.md)	 - config modifies kubeconfig files~~ N/A this doesn't make server calls, no e2e needed
- [x] [kubectl create](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_create.md)	 - Create a resource by filename or stdin
- [x] [kubectl delete](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_delete.md)	 - Delete a resource by filename, stdin, resource and name, or by resources and label selector.
- [x] [kubectl describe](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_describe.md)	 - Show details of a specific resource
- [x] [kubectl exec](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_exec.md)	 - Execute a command in a container.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl expose](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_expose.md)	 - Take a replicated application and expose it as Kubernetes Service
- [x] [kubectl get](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_get.md)	 - Display one or many resources  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl label](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_label.md)	 - Update the labels on a resource
- [x] [kubectl logs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_logs.md)	 - Print the logs for a container in a pod.  (tested by `test/e2e/examples.go`, but test is disabled)
- [x] ~~[kubectl namespace](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_namespace.md)	 - SUPERCEDED: Set and view the current Kubernetes namespace~~ N/A, deprecated command
- [x] [kubectl patch](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_patch.md)	 - Update field(s) of a resource by stdin.
- [x] [kubectl port-forward](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_port-forward.md)	 - Forward one or more local ports to a pod.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl proxy](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_proxy.md)	 - Run a proxy to the Kubernetes API server
- [ ] [kubectl replace](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_replace.md)	 - Replace a resource by filename or stdin.
- [x] [kubectl rolling-update](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_rolling-update.md)	 - Perform a rolling update of the given ReplicationController.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl run](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_run.md)	 - Run a particular image on the cluster.
- [x] [kubectl scale](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_scale.md)	 - Set a new size for a Replication Controller. (tested by `test/e2e/kubectl.go`)
- [x] [kubectl stop](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_stop.md)	 - Gracefully shut down a resource by name or filename.  (tested by `test/e2e/kubectl.go`)
- [x] [kubectl version](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_version.md)	 - Print the client and server version information.

Working on adding missing tests now.

**Comment by jlowdermilk** [comment]
FYI @bgrant0607. I started with a test for `kubectl proxy in #10813, but if we agree this is 1.0-worthy, it'd be faster to split this up among a few people with available cycles. Also cc @mwielgus who recently added kubectl examples e2e, and may be interested in picking up an unchecked box or two.

**Comment by bgrant0607** [comment]
I have 0 time left to review any PRs, but I'm happy for people to work on this if they've finished more critical 1.0 work. We can always merge tests that don't uncover critical bugs after 1.0.

**Comment by bgrant0607** [comment]
cc @nikhiljindal @caesarxuchao @krousey @JanetKuo

**Comment by mwielgus** [comment]
@jlowdermilk Sure, I will take 4 unchecked from the top of the list (api-versions, cluster-info, describe, expose).

**Comment by JanetKuo** [comment]
I will take kubectl label.

**Comment by mwielgus** [comment]
PRs for api-versions, cluster-info, describe,& expose sent.
Can take another batch, let's say logs, patch, replace, version (but will work on this probably on Monday)

**Comment by JanetKuo** [comment]
I will take `kubectl run`

**Comment by JanetKuo** [comment]
I will take `kubectl proxy`

**Comment by jlowdermilk** [comment]
@JanetKuo Kubectl proxy already covered.

**Comment by JanetKuo** [comment]
@jlowdermilk - got it. Thanks for pointing that out!

**Comment by dims** [comment]
@jlowdermilk the PR for "kubectl replace" is ready, so we can close this issue! (once that merges)
