### ISSUE TITLE
HPA scale in with no reason / blank reason

### ISSUE THREAD

**Issue by apratina** [kubernetes/kubernetes#107647]
### What happened?

HPA scales in the deployment with no reason / blank reason.

![Screen Shot 2022-01-19 at 10 06 12 AM](https://user-images.githubusercontent.com/4571461/150188749-b55ee9e9-bb5f-48c1-a0c9-1839ad4a1f41.png)

### What did you expect to happen?

There should always be a reason for scale in.

### How can we reproduce it (as minimally and precisely as possible)?

Not exactly sure. But we do see this scale-in problem happen very often. When the scale-in happens, we have also noted that metrics are above threshold so we do not expect to see those scale-in at first place. In absence of reason data, it is not clear why scale in is happening.

### Anything else we need to know?

There is a similar issue that has been reported but it only talks about scale out https://github.com/kubernetes/kubernetes/issues/78712.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2605.12.0
VERSION_ID=2605.12.0
BUILD_ID=2021-01-27-1731
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2605.12.0 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"

$ uname -a
Linux ip-10-69-78-66 5.4.92-flatcar #1 SMP Wed Jan 27 16:53:10 -00 2021 x86_64 Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by slin1237** [comment]
i have seen the same thing in our cluster as well
same k8s version
and exactly the same deployment along with hpa worked just fine in another namespace

**Comment by wildermesser** [comment]
The same problem is in my k8s 1.20.11 (same version as in topic). Kube-controller-manager log:
```
I0208 05:48:30.777191       1 horizontal.go:697] Successful rescale of hpa-00000000-0000-0000-0000-000000000000, old size: 3, new size: 1, reason:
I0208 05:48:30.778920       1 event.go:291] "Event occurred" object="ptaf-core/hpa-00000000-0000-0000-0000-000000000000" kind="HorizontalPodAutoscaler" apiVersion="autoscaling/v2beta2" type="Normal" reason="SuccessfulRescale" message="New size: 1; reason: "
```
I expect that replica count shouldn't decrease because I set `horizontal-pod-autoscaler-downscale-stabilization: 24h0m0s` for kube-controller-manager and didn't set custom `stabilizationWindowSeconds` for `scaleDown` behavior in HPA manifest.

**Comment by TArtiushenko** [comment]
Looks like i have same issue, upscale with no reason to max replicas when cpu consumption is 2% of target 200%. 
Interesting that in another deployment with same hpa config it works almost as expected
k8s 1.20.13

**Comment by Leonardomav** [comment]
@TArtiushenko How was it related to flux? I am facing the same issue and using flux but I've yet to find anyone else talking about this issue.

**Comment by TArtiushenko** [comment]
> @TArtiushenko How was it related to flux? I am facing the same issue and using flux but I've yet to find anyone else talking about this issue.

In deployment manifest was replica count specified and it was applied each time flux reconciles

**Comment by ganeshkumar5699** [comment]
Facing the same issue again with k8s 1.26.3 as well, in which the SuccessfulRescale event for HPA does not show a reason in the message. Message is "New size: 2; reason:"

**Comment by madibaT** [comment]
I am also seeing the same issue on 1.25.11. with me, this started after I've added memory in my autoscaling config
