### ISSUE TITLE
e2e test progress updates when in parallel mode are incorrect

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#107645]
### What happened?

Run e2e tests with E2E_PARALLEL=true
See the progress updates that are sent to Sonobuoy (and printed on the command line).
The total test count is listed as -1, the total tests completed and failed go up and down rather than monotonically up. This is because each thread is reporting its own progress independent of the others.

Also see original complaint here in Sonobuoy repo: https://github.com/vmware-tanzu/sonobuoy/issues/1519

### What did you expect to happen?

The values for total tests to run should be accurate
The list of test failures should be consistent
The count of tests completed (without failure) should be increasing, not going up and down.

### How can we reproduce it (as minimally and precisely as possible)?

Run
```
sonobuoy run --plugin-env=e2e.E2E_PARALLEL=y --wait
```
and wait for the status updates to show the test counts. You can also check the logs via
```
sonobuoy logs -p e2e
```
and look for the json messages showing test counts/messages.

### Anything else we need to know?

Sonobuoy just added a fix for this on their main branch. Older versions of Sonobuoy wont make use of these new values, but it won't be more broken than it is now. Going forward with new Sonobuoy+new k8s the issue will be fixed.

### Kubernetes version

Currently testing against v1.20.0 but this applies to all versions of k8s that have this progressUpdate functionality.

### Cloud provider

kind

**Comment by sftim** [comment]
/retitle e2e test progress updates when in parallel mode are incorrect

**Comment by BenTheElder** [comment]
/remove-lifecycle rotten
something to consider for #109111
