### ISSUE TITLE
[Failing test] aks-engine-windows-containerd-master 

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#107641]
### Which jobs are failing?

sig-release-master-informing, aks-engine-windows-containerd-master

### Which tests are failing?

* ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd.Overall
* kubetest.Up

### Since when has it been failing?

2022-01-18 18:55 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#aks-engine-windows-containerd-master

### Reason for failure (if possible)

[lastr run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1483770098157096960)
```bash
e2e.go: Up expand_less | 1h0m17s
-- | --
error creating cluster: cannot deploy: cannot get the create deployment future response: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```
quick suspicion docker related, maybe because of docker shim removal.

### Relevant SIG(s)

/sig windows

cc @jsturtevant

**Comment by jsturtevant** [comment]
/triage accepted
/assign

Taking a look this morning

**Comment by jsturtevant** [comment]
The removal of dockershim kubelet flags is causing kubelet to fail to start https://github.com/kubernetes/kubernetes/pull/106907

**Comment by marosset** [comment]
We need to add support for v1.24 in aks-engine so and update the defaulting logic to no longer set some of these flags.
Here is a PR for tart work https://github.com/Azure/aks-engine/pull/4813

**Comment by jsturtevant** [comment]
/reopen

The job is still failing with some flags that were missed: `Error: failed to parse kubelet flag: unknown flag: --cni-bin-dir`

**Comment by jsturtevant** [comment]
This should remove the remaining flags: https://github.com/Azure/aks-engine/pull/4817

**Comment by jsturtevant** [comment]
Latest test run passed: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd/1484315275804282880

/close
