### ISSUE TITLE
Feature Request: Support Image Registries without Domain Suffix

### ISSUE THREAD

**Issue by cawoodm** [kubernetes/kubernetes#107671]
### What happened?

Kubernetes is unable to pull images from repositories without a FQDN.

So `myrepo.mycompany.com/image` works but `myrepo/image` does not work.

The point however is that nearly every other tool (ping, curl, browsers etc) support shortened hostnames.

```
kubelet            Pulling image "myrepo/overview:1.0.3.248408"                                                                                                                                   
Failed     kubelet            Failed to pull image "myrepo/overview:1.0.3.248408": rpc error: code = Unknown 
desc = failed to pull and unpack image "myrepo/overview:1.0.3.248408": 
failed to resolve reference "myrepo/overview:1.0.3.248408": failed to do request: 
Head "https://myrepo/v2/overview/manifests/1.0.3.248408": dial tcp: lookup myrepo: no such host
```

### What did you expect to happen?

For developers, it's much nicer to specify a short hostname than constantly typing out FQDNs.

As I mentioned, DNS, ping, curl etc can all deal with this:
```
ping myrepo
```
No problem
```
curl https://myrepo/v2/_catalog
```
No problem

### How can we reproduce it (as minimally and precisely as possible)?

Create a private repo with ingress supporting `https://myrepo` and `https://myrepo.mydomain.com`. Notice that you can docker push to both but kubernetes can only pull from the latter.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s2", GitCommit:"724ef700bab896ff252a75e2be996d5f4ff1b842", GitTreeState:"clean", BuildDate:"2021-10-05T19:59:14Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
On-prem - no cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux myhost 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
k3s
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
k3s

**Comment by cawoodm** [comment]
As a workaround we can add the alias to our `/etc/hosts` file and kubernetes suddenly can pull:
```
<ip address> myrepo

**Comment by sftim** [comment]
BTW the way Docker defines a hostname is rather vague:
> The hostname must comply with standard DNS rules, but may not contain underscores.

**Comment by sftim** [comment]
In terms of tools that work with shortened hostnames in container image references: Docker Engine _does_ (and documents that it does).

**Comment by pacoxu** [comment]
/area images-registry 

```
nerdctl pull nginx
```
- `nginx` means `docker.io/library/nginx:latest`.
- `myrepo/image` means `docker.io/myrepo/image`

There will be ambiguity if `myrepo/image` means `docker.io/myrepo/image` or `myrepo.mycompany.com/image`.
