### ISSUE TITLE
Can not apply job with large yaml file - RequestEntityTooLarge

### ISSUE THREAD

**Issue by lazarkrstic** [kubernetes/kubernetes#107723]
### What happened?

Hi everyone!

We need to to start batch job with large input. **The problem is limit for yaml file size**. Current limit is just `3 MB`, but my job is larger, approximately `200 MB` .  When trying to start we get the following error:
````
Error from server (RequestEntityTooLarge): error when creating "job.yaml": Request entity too large: limit is 3145728
````
We tested this at both EKS and local k8s instalation, same results (errors) in both times. Jobs with yaml files smaller than `3 MB` works fine. 

### What did you expect to happen?

We expected to start job same as smaller jobs.

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce this error we created a demo job that only prints values from enviroment variable. Job YAML is hoosted at GitHub so you only need to apply it.
````
 kubectl apply -f https://raw.githubusercontent.com/lazarkrstic/k8s-large-job-demo/main/job-large-input.yaml
````

### Kubernetes version

<details>
EKS

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c579e", GitCommit:"8c579edfc914f013ff48b2a2b2c1308fdcacc53f", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:13Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

local
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.13-35+d877e7a8ac536e", GitCommit:"d877e7a8ac536e691e6fd3ea06e93af3d8c0c8b8", GitTreeState:"clean", BuildDate:"2021-12-07T10:44:48Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
EKS and local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
eksctl 
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
There is a hard-coded 3MB limit on requests accepted by the API server. There's an additional limit on data that can be persisted in a single key in etcd, which is also in the single-megabyte range.

Creating individual objects in the hundreds of megabytes would cause scalability problems listing resources, which returns the content of all individual objects.

/close
