### ISSUE TITLE
Helper CI job that runs `make update` to make it easier for contributors

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#107726]
Quite a few contributors do not have access to beefy environments to run `make update` or `make verify`. They are able to use vscode/wsl/codespaces etc to suggest changes, but do get tripped up from our `make verify` scripts as quite a few scenarios we end up with files that needs to be re-generated. Its a high bar for them to parse the build log from `make verify` to see which exact scripts in hack/ they need to run. Frequently reviewers will ask folks to run `make update` as it is easy to suggest that and they are used to it. Unfortunately this is hard on contributors with laptops that are not beefy or they are on windows etc.

So we should add a CI job that folks can trigger when they need it, that runs `make update` and there's a zip file they can be told to download that has the changes after the `make update` is run. (example https://github.com/kubernetes/kubernetes/pull/107691)

(Bonus points if we can have a bot command that generates an addition commit on their PR, but let do something that is easier first)

**Comment by dims** [comment]
@SubhasmitaSw could you please help doc this?

**Comment by SubhasmitaSw** [comment]
On it @dims 🙌

**Comment by sftim** [comment]
That sounds useful! Also, I think you need to have Docker available to run `make update` (which, as it happens, I don't). A way to get an update when you don't have Docker available locally would also be useful to me and I suspect others too.

**Comment by sftim** [comment]
> a zip file they can be told to download

Perhaps we could include the changes in Git format as well? https://thoughtbot.com/blog/send-a-patch-to-someone-using-git-format-patch outlines how you could use that (`git am` etc).

**Comment by liggitt** [comment]
this is complete, right?

**Comment by dims** [comment]
@liggitt yep, @SubhasmitaSw is trying to get some documentation out... last check it was possibly a blog

**Comment by SubhasmitaSw** [comment]
@liggitt Yes, the draft is almost ready waiting for the final approvement and then it should be live soon.
