### ISSUE TITLE
Some static pods fail to start on K8S 1.23

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#107733]
### What happened?

In Kubernetes 1.23 we are seeing some static pods fail to start. These static pods failures are on quick remove and adds leaving the static pod not started.

We need to revert kubernetes/kubernetes#104743.

cc @gjkim42 

### What did you expect to happen?

All static pods should restart.

### How can we reproduce it (as minimally and precisely as possible)?

```diff
diff --git a/pkg/kubelet/pod_workers_test.go b/pkg/kubelet/pod_workers_test.go
index 4028c06c292..0e852594a40 100644
--- a/pkg/kubelet/pod_workers_test.go
+++ b/pkg/kubelet/pod_workers_test.go
@@ -880,3 +880,34 @@ func Test_allowPodStart(t *testing.T) {
 		})
 	}
 }
+
+func TestUpdatePodWithQuickAddRemoveStaticPod(t *testing.T) {
+	podWorkers, _ := createPodWorkers()
+	staticPodA := newStaticPod("0000-0000-0000", "running-static-pod")
+	staticPodB := newStaticPod("0000-0000-0000", "running-static-pod")
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodA,
+		UpdateType: kubetypes.SyncPodCreate,
+	})
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodA,
+		UpdateType: kubetypes.SyncPodKill,
+	})
+
+	drainAllWorkers(podWorkers)
+
+	podWorkers.UpdatePod(UpdatePodOptions{
+		Pod:        staticPodB,
+		UpdateType: kubetypes.SyncPodCreate,
+	})
+
+	drainAllWorkers(podWorkers)
+
+	t.Logf("rphillips waitingToStartStaticPodsByFullName=%v", podWorkers.waitingToStartStaticPodsByFullname)
+	if status, ok := podWorkers.podSyncStatuses["0000-0000-0000"]; ok {
+		t.Logf("rphillips podSyncStatuses=%+v", status)
+	}
+	t.Logf("rphillips startedStaticPodsByFullname=%v", podWorkers.startedStaticPodsByFullname)
+}
```

### Kubernetes version

<details>
1.23
</details>

### Cloud provider

<details>
All
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
/triage accepted

confirmed race in OpenShift CI

see e.g. https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/10885/pull-ci-openshift-console-master-e2e-gcp-console/1484500374093041664/artifacts/e2e-gcp-console/gather-extra/artifacts/nodes/ci-op-iz49kfy2-75d12-mzq7h-master-2/journal

**Comment by gjkim42** [comment]
> ### How can we reproduce it (as minimally and precisely as possible)?
> ```diff
> diff --git a/pkg/kubelet/pod_workers_test.go b/pkg/kubelet/pod_workers_test.go
> index 4028c06c292..0e852594a40 100644
> --- a/pkg/kubelet/pod_workers_test.go
> +++ b/pkg/kubelet/pod_workers_test.go
> @@ -880,3 +880,34 @@ func Test_allowPodStart(t *testing.T) {
>  		})
>  	}
>  }
> +
> +func TestUpdatePodWithQuickAddRemoveStaticPod(t *testing.T) {
> +	podWorkers, _ := createPodWorkers()
> +	staticPodA := newStaticPod("0000-0000-0000", "running-static-pod")
> +	staticPodB := newStaticPod("0000-0000-0000", "running-static-pod")
> +
> +	podWorkers.UpdatePod(UpdatePodOptions{
> +		Pod:        staticPodA,
> +		UpdateType: kubetypes.SyncPodCreate,
> +	})
> +
> +	podWorkers.UpdatePod(UpdatePodOptions{
> +		Pod:        staticPodA,
> +		UpdateType: kubetypes.SyncPodKill,
> +	})
> +
> +	drainAllWorkers(podWorkers)
> +
> +	podWorkers.UpdatePod(UpdatePodOptions{
> +		Pod:        staticPodB,
> +		UpdateType: kubetypes.SyncPodCreate,
> +	})
> +
> +	drainAllWorkers(podWorkers)
> +
> +	t.Logf("rphillips waitingToStartStaticPodsByFullName=%v", podWorkers.waitingToStartStaticPodsByFullname)
> +	if status, ok := podWorkers.podSyncStatuses["0000-0000-0000"]; ok {
> +		t.Logf("rphillips podSyncStatuses=%+v", status)
> +	}
> +	t.Logf("rphillips startedStaticPodsByFullname=%v", podWorkers.startedStaticPodsByFullname)
> +}
> ```

I guess this case is not relevant to your issue(not restarting static pod).
The staticPodB will restart by SyncKnownPods as it is marked as restartRequested and there is no startedStaticPodsByFullname for its name.

```sh
go test -v ./pkg/kubelet/ -run=TestUpdatePodWithQuickAddRemove
=== RUN   TestUpdatePodWithQuickAddRemoveStaticPod
    pod_workers_test.go:513: waitingToStartStaticPodsByFullname=map[]
    pod_workers_test.go:515: podSyncStatuses=&{ctx:0xc000324880 cancelFn:0x5091c0 working:false fullname:running-static-pod_ syncedAt:{wall:13867678802613854809 ext:21207222 loc:0x63a9320} terminatingAt:{wall:13867678802613867256 ext:21219669 loc:0x63a9320} startedTerminating:true deleted:false gracePeriod:1 evicted:false terminatedAt:{wall:13867678802613895034 ext:21247446 loc:0x63a9320} finished:true restartRequested:true notifyPostTerminating:[] statusPostTerminating:[]}
    pod_workers_test.go:517: startedStaticPodsByFullname=map[]
--- PASS: TestUpdatePodWithQuickAddRemoveStaticPod (0.05s)
PASS
ok      k8s.io/kubernetes/pkg/kubelet   (cached)
```

**Comment by rphillips** [comment]
@gjkim42 can you think of anything else that may be racing with a quick add/remove of a static pod?

**Comment by gjkim42** [comment]
@rphillips 

Does #107695 not address your problem?
(I guess #107733 is not the case you want to address.)

I am not sure which case you want to cover, but covering it with an e2e test makes more sense as we find out it is hard to be covered with a unit test.

**Comment by rphillips** [comment]
@gjkim42 We'll merge the one liner in our CI and see if it fixes the issue.

**Comment by gjkim42** [comment]
@rphillips 

Do you use `restartPolicy: Never` and completable static pods?
I think a completed static pod(all containers are terminated) with `restartPolicy: Never` cannot restart.

```sh
root@gjkim-desktop:/var/run/kubernetes/static-pods# sudo rm test.yaml && sudo cp /tmp/test.yaml ./ && sudo rm test2.yaml && sudo cp /tmp/test2.yaml ./
root@gjkim-desktop:/var/run/kubernetes/static-pods# sudo rm test.yaml && sudo cp /tmp/test.yaml ./ && sudo rm test2.yaml && sudo cp /tmp/test2.yaml ./
root@gjkim-desktop:/var/run/kubernetes/static-pods# sudo rm test.yaml && sudo cp /tmp/test.yaml ./ && sudo rm test2.yaml && sudo cp /tmp/test2.yaml ./
root@gjkim-desktop:/var/run/kubernetes/static-pods# kubectl get pods
NAME              READY   STATUS      RESTARTS       AGE
test-127.0.0.1    0/1     Completed   0              2m7s
test2-127.0.0.1   1/1     Running     3 (106s ago)   2m7s
```

```yaml
$ cat /tmp/test.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
spec:
  containers:
  - image: busybox
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

```yaml
$ cat /tmp/test2.yaml 
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test2
  name: test2
spec:
  containers:
  - image: busybox
    name: test2
    command:
    - sleep
    - infinity
    resources: {}
  dnsPolicy: ClusterFirst
  terminationGracePeriodSeconds: 5
status: {}
```

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/blob/f4046f9e6d0bb2fc4fa2d84af64cc9c6db44270a/pkg/kubelet/kubelet_pods.go#L1192-L1200

Already completed static pods are dropped by L1199 and cannot be restarted.

**Comment by liggitt** [comment]
cc @SergeyKanzhelev

**Comment by gjkim42** [comment]
@rphillips 
Can you give us more detail about the problem?

> In Kubernetes 1.23 we are seeing some static pods fail to start. These static pods failures are on quick remove and adds leaving the static pod not started.

If the problem is about quick removing and adding the static pod, https://github.com/kubernetes/kubernetes/pull/104847 can be relevant.

/cc @smarterclayton

**Comment by rphillips** [comment]
https://github.com/kubernetes/kubernetes/pull/107695 merged. We have a tentative increase in CI pass rates. I'll reopen if we need to revisit.

**Comment by TeddyAndrieux** [comment]
To me it need to be fixed in 1.22 as well

**Comment by ehashman** [comment]
@TeddyAndrieux the affected code is not present in 1.22.

Fix confirmed in OpenShift CI: https://bugzilla.redhat.com/show_bug.cgi?id=2040533#c10

@gjkim42 could we add some unit test coverage for this code path?

**Comment by TeddyAndrieux** [comment]
@ehashman I did not follow all the detail about this ticket but from what I see the original PR that caused this bug has been cherry-picked in 1.22 (https://github.com/kubernetes/kubernetes/pull/106394) (part of 1.22.5)

And btw I observed a similar issue on 1.22.5 and 1.22.6 (but not on 1.22.4)

**Comment by ehashman** [comment]
@TeddyAndrieux my mistake, I just saw the 1.22 backport at https://github.com/kubernetes/kubernetes/pull/106394 - you are correct. Was going to drop a line here but you beat me to it :)

**Comment by gjkim42** [comment]
> And btw I observed a similar issue on 1.22.5 and 1.22.6 (but not on 1.22.4)

@TeddyAndrieux 
Can you explain how can we reproduce the problem? I think it is hard for me to reproduce the issue.

**Comment by gjkim42** [comment]
> To me it need to be fixed in 1.22 as well

Cherry-picking https://github.com/kubernetes/kubernetes/pull/107695 to v1.22 looks fine.

**Comment by TeddyAndrieux** [comment]
> @TeddyAndrieux Can you explain how can we reproduce the problem? I think it is hard for me to reproduce the issue.

It was a bit tricky but I manage to reproduce by deploying a single-node and then I edit a first time the kube-apiserver static pod manifest and wait for the pod to be deleted, and once it's deleted and not yet re-created I edit the manifest a second time then if you are (un)lucky the pod will never restart

Not a super easy way to reproduce, I agree 😄 

Using this "method" I manage to reproduce several time with kubelet 1.22.5 and when I downgraded to 1.22.4 I didn't.

**Comment by gjkim42** [comment]
Thanks to @TeddyAndrieux. I can reproduce this bug quite easily.

1. Make a static pod not terminating within graceTreminationSeconds.
2. Change the static pod manifest with the same name (e.g. I simply change its `.spec.resources.requests.cpu`)
3. Change the static pod multiple times again while the static pod is terminating(updating)

Then, the static pod with the same name never starts again.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  terminationGracePeriodSeconds: 10
  containers:
  - args:
    - -c
    - trap "sleep inf" SIGINT SIGTERM SIGHUP &&  nc -k -l -p 4444
    command:
    - /bin/sh
    image: docker.io/library/busybox:latest
    imagePullPolicy: IfNotPresent
    name: test
    ports:
    - name: test
      containerPort: 4444
      hostPort: 4444
    resources:
      requests:
        cpu: 100m # change it simply
        memory: 10Mi
```

**Comment by gjkim42** [comment]
The bug is still reproduced at master(after #107695)

/reopen

The problem is that terminating static pod requests termination to podWorkers and removes it from podManager.

When a static pod is waiting to start and termination requested, the static pod is enqueued to workQueue at podWorkers, but it cannot be re-requested again as it has been already removed from podManager.

https://github.com/kubernetes/kubernetes/blob/2e68fd2857cded9cb470e3bf22ba01bb4934c6f8/pkg/kubelet/kubelet.go#L1877-L1899

Made a fix for this at https://github.com/kubernetes/kubernetes/pull/107854

**Comment by gjkim42** [comment]
@rphillips 

Let me align all PRs to be merged to fix this issue.

- #107695 
    - [x] #107761
    - [ ] TODO: release-1.22
- #107900 
    - [ ] #107931
    - [ ] #107932

**Comment by TeddyAndrieux** [comment]
The issue I describe in my previous comment https://github.com/kubernetes/kubernetes/issues/107733#issuecomment-1024859297 is still there in 1.22.8

If I try, in single-node deployment, to edit the kube-apiserver static pod manifest he will never come back (cc @gjkim42 )
