### ISSUE TITLE
e2e test for creating Ingress API operations fails when ingress controller is already in place

### ISSUE THREAD

**Issue by srikiz** [kubernetes/kubernetes#107752]
### What happened?

We run sonobuoy tests on production running clusters whenever we upgrade our clusters.  We observe that `should support creating Ingress API operations` fails when we already have nginx-ingress controller running in the cluster.

The newer versions of nginx-ingress controller comes up with a validating admission webhook that validates the ingress definitions. In this specific test, we are creating 3 ingress objects with the same path and the webhook do not permit to create them (the first one is created but the other two would fail) and then the job fails.

### What did you expect to happen?

The tests shouldn't fail and it requires we create ingress objects using different paths instead.

### How can we reproduce it (as minimally and precisely as possible)?

-  Install nginx-ingress controller from [here](https://kubernetes.github.io/ingress-nginx/deploy/)
-  Run e2e test. 
Test fails.

### Kubernetes version

>=1.19

### Cloud provider

n/a

### OS version

n/a

### Install tools

n/a

### Container runtime (CRI) and and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

**Comment by aojea** [comment]
This is a duplicate, see the comment from.the author of the ingress nginx controller explaining why this is working as expected https://github.com/kubernetes/kubernetes/pull/100449#issuecomment-804788806

**Comment by srikiz** [comment]
Thanks @aojea for pointing this. It's infact the same issue. But the fix above should hopefully help since it would create those ingress objects with different paths and the validating webhook for ingress controller would permit creating objects in that case.

**Comment by aojea** [comment]
> Thanks @aojea for pointing this. It's infact the same issue. But the fix above should hopefully help since it would create those ingress objects with different paths and the validating webhook for ingress controller would permit creating objects in that case.

yeah sorry, just checked quickly from the mobile, I will take a look
Thanks
