### ISSUE TITLE
Slow CNI requests, such as TearDownPod would cause PLEG to be unhealthy.

### ISSUE THREAD

**Issue by liushi001** [kubernetes/kubernetes#107749]
### What happened?

When a Pod is executing TeadDownPod in StopPodsandbox,  PLEG will stuck in asynchronously GetPodNetworkStatus. Because they take the same Pod lock. 

A potential condition `networkReady` could avoid the unnecessary wait. But `networkReady` cannot become false until the TearDownPod method is finished and releases the lock.

In severe cases, this causes the PLEG to be unhealthy and the node to be in the NotReady state.

```log
I0126 13:21:34.970903   24668 setters.go:608] "Node became not ready" node="paas-135-212-198-2" condition={Type:Ready Status:False LastHeartbeatTime:2022-01-26 13:21:34.970848552 +0000 GMT m=+565.446974410 LastTransitionTime:2022-01-26 13:21:34.970848552 +0000 GMT m=+565.446974410 Reason:KubeletNotReady Message:PLEG is not healthy: pleg was last seen active 3m6.531326808s ago; threshold is 3m0s}
...
E0126 13:22:30.404332   24668 kubelet.go:2196] "Skipping pod synchronization" err="PLEG is not healthy: pleg was last seen active 4m1.963068913s ago; threshold is 3m0s"
```

Note: the CNI is reconstructed into multiple network planes in out cluster, thus the CNI request time is longer than that of a common cluster.

### What did you expect to happen?

RunPodsandbox or StopPodsandbox will not block PLEG.

### How can we reproduce it (as minimally and precisely as possible)?

Add a deley in `TearDownPod`.

```go
func (plugin *NoopNetworkPlugin) TearDownPod(namespace string, name string, id kubecontainer.ContainerID) error {
	time.Sleep(10*time.Second)
	return nil
```

Then run the StopPodsandbox and PodSandboxStatus methods in parallel.

<details>
<summary>Click here to see test case</summary>

```go
// TestSandboxStatus tests the basic lifecycle operations and verify that
// the status returned reflects the operations performed.
func TestSandboxStatusWhenRunPodSandbox(t *testing.T) {

	ds, fDocker, fClock := newTestDockerService()
	labels := map[string]string{"label": "foobar1"}
	annotations := map[string]string{"annotation": "abc"}
	config := makeSandboxConfigWithLabelsAndAnnotations("foo", "bar", "1", 0, labels, annotations)
	r := rand.New(rand.NewSource(0)).Uint32()
	podIP := fmt.Sprintf("10.%d.%d.%d", byte(r>>16), byte(r>>8), byte(r))

	state := runtimeapi.PodSandboxState_SANDBOX_READY
	ct := int64(0)
	expected := &runtimeapi.PodSandboxStatus{
		State:     state,
		CreatedAt: ct,
		Metadata:  config.Metadata,
		Network:   &runtimeapi.PodSandboxNetworkStatus{Ip: podIP, AdditionalIps: []*runtimeapi.PodIP{}},
		Linux: &runtimeapi.LinuxPodSandboxStatus{
			Namespaces: &runtimeapi.Namespace{
				Options: &runtimeapi.NamespaceOption{
					Pid: runtimeapi.NamespaceMode_CONTAINER,
				},
			},
		},
		Labels:      labels,
		Annotations: annotations,
	}

	go func() {
		// Create the sandbox.
		fClock.SetTime(time.Now())
		expected.CreatedAt = fClock.Now().UnixNano()
		d, err := ds.RunPodSandbox(getTestCTX(), &runtimeapi.RunPodSandboxRequest{Config: config})
		require.NoError(t, err)
		t.Logf("%v",d)

		_, err = ds.StopPodSandbox(getTestCTX(), &runtimeapi.StopPodSandboxRequest{PodSandboxId: d.PodSandboxId})
		require.NoError(t, err)
	}()

	var id string
	for {
		sandboxes, err := ds.ListPodSandbox(getTestCTX(), &runtimeapi.ListPodSandboxRequest{
			Filter: &runtimeapi.PodSandboxFilter{
				LabelSelector: map[string]string{"label": "foobar1"},
			},
		})
		require.NoError(t, err)
		for _, sb := range sandboxes.Items {
			id = sb.GetId()
			assert.NotEmpty(t, id)
		}
		c, err := fDocker.InspectContainer(id)
		if err == nil && c.Config.Labels[types.KubernetesContainerNameLabel] == sandboxContainerName {
			break
		}
	}

	// Check internal labels
	c, err := fDocker.InspectContainer(id)
	assert.NoError(t, err)
	assert.Equal(t, c.Config.Labels[containerTypeLabelKey], containerTypeLabelSandbox)
	assert.Equal(t, c.Config.Labels[types.KubernetesContainerNameLabel], sandboxContainerName)

	time.Sleep(2*time.Second)
	startTime := time.Now()
	expected.Id = id // ID is only known after the creation.
	_, err = ds.PodSandboxStatus(getTestCTX(), &runtimeapi.PodSandboxStatusRequest{PodSandboxId: id})
	require.NoError(t, err)
	//assert.Equal(t, expected, statusResp.Status)
	duration := time.Now().Sub(startTime)
	t.Logf("PodSandboxStatus cost %v", duration)
}
```
</details>

<details>
<summary>Click here to see result</summary>

```log
=== RUN   TestSandboxStatusWhenRunPodSandbox
I0125 20:50:21.347380    2276 docker_sandbox.go:406] "Failed to read pod IP from plugin/docker" err="Couldn't find network status for bar/foo through plugin: invalid network status for"
--- PASS: TestSandboxStatusWhenRunPodSandbox (10.02s)
```

</details>

### Anything else we need to know?

Can we call `ds.setNetworkReady(podSandboxID, false)` before `ds.network.TearDownPod(namespace, name, cID)`, and call `ds.setNetworkReady(podSandboxID, true)` to restore it to true when an error is returned.

```go
	if !hostNetwork && (ready || !ok) {
		// Only tear down the pod network if we haven't done so already
		ds.setNetworkReady(podSandboxID, false)
		cID := kubecontainer.BuildContainerID(runtimeName, podSandboxID)
		err := ds.network.TearDownPod(namespace, name, cID)
		if err != nil {
			ds.setNetworkReady(podSandboxID, true)
			errList = append(errList, err)
		}
	}
```

And I'm not sure if `RunPodsandbox` could block `PodSandboxStatus`, it seems like not. But I still wonder to known that condition in `PodSandboxStatus` could be changed like this:

```go
	ready, ok := ds.getNetworkReady(podSandboxID)
	if !ok || !ready {
		return nil
	}
```

I noticed @dcbw is the author of the code and I would appreciate it if he could check it.

### Kubernetes version

<details>

```console
1.22.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liushi001** [comment]
> ### What happened?
> When a Pod is executing TeadDownPod in StopPodsandbox, PLEG will stuck in asynchronously GetPodNetworkStatus. Because they take the same Pod lock.
> 
> A potential condition `networkReady` could avoid the unnecessary wait. But `networkReady` cannot become false until the TearDownPod method is finished and releases the lock.
> 
> In severe cases, this causes the PLEG to be unhealthy and the node to be in the NotReady state.
> 
> Note: the CNI is reconstructed into multiple network planes in out cluster, thus the CNI request time is longer than that of a common cluster.
> 
> ### What did you expect to happen?
> RunPodsandbox or StopPodsandbox will not block PLEG.
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> Add a deley in `TearDownPod`.
> 
> ```go
> func (plugin *NoopNetworkPlugin) TearDownPod(namespace string, name string, id kubecontainer.ContainerID) error {
> 	time.Sleep(10*time.Second)
> 	return nil
> ```
> 
> Then run the StopPodsandbox and PodSandboxStatus methods in parallel.
> 
> ```go
> // TestSandboxStatus tests the basic lifecycle operations and verify that
> // the status returned reflects the operations performed.
> func TestSandboxStatusWhenRunPodSandbox(t *testing.T) {
> 
> 	ds, fDocker, fClock := newTestDockerService()
> 	labels := map[string]string{"label": "foobar1"}
> 	annotations := map[string]string{"annotation": "abc"}
> 	config := makeSandboxConfigWithLabelsAndAnnotations("foo", "bar", "1", 0, labels, annotations)
> 	r := rand.New(rand.NewSource(0)).Uint32()
> 	podIP := fmt.Sprintf("10.%d.%d.%d", byte(r>>16), byte(r>>8), byte(r))
> 
> 	state := runtimeapi.PodSandboxState_SANDBOX_READY
> 	ct := int64(0)
> 	expected := &runtimeapi.PodSandboxStatus{
> 		State:     state,
> 		CreatedAt: ct,
> 		Metadata:  config.Metadata,
> 		Network:   &runtimeapi.PodSandboxNetworkStatus{Ip: podIP, AdditionalIps: []*runtimeapi.PodIP{}},
> 		Linux: &runtimeapi.LinuxPodSandboxStatus{
> 			Namespaces: &runtimeapi.Namespace{
> 				Options: &runtimeapi.NamespaceOption{
> 					Pid: runtimeapi.NamespaceMode_CONTAINER,
> 				},
> 			},
> 		},
> 		Labels:      labels,
> 		Annotations: annotations,
> 	}
> 
> 	go func() {
> 		// Create the sandbox.
> 		fClock.SetTime(time.Now())
> 		expected.CreatedAt = fClock.Now().UnixNano()
> 		d, err := ds.RunPodSandbox(getTestCTX(), &runtimeapi.RunPodSandboxRequest{Config: config})
> 		require.NoError(t, err)
> 		t.Logf("%v",d)
> 
> 		_, err = ds.StopPodSandbox(getTestCTX(), &runtimeapi.StopPodSandboxRequest{PodSandboxId: d.PodSandboxId})
> 		require.NoError(t, err)
> 	}()
> 
> 	var id string
> 	for {
> 		sandboxes, err := ds.ListPodSandbox(getTestCTX(), &runtimeapi.ListPodSandboxRequest{
> 			Filter: &runtimeapi.PodSandboxFilter{
> 				LabelSelector: map[string]string{"label": "foobar1"},
> 			},
> 		})
> 		require.NoError(t, err)
> 		for _, sb := range sandboxes.Items {
> 			id = sb.GetId()
> 			assert.NotEmpty(t, id)
> 		}
> 		c, err := fDocker.InspectContainer(id)
> 		if err == nil && c.Config.Labels[types.KubernetesContainerNameLabel] == sandboxContainerName {
> 			break
> 		}
> 	}
> 
> 	// Check internal labels
> 	c, err := fDocker.InspectContainer(id)
> 	assert.NoError(t, err)
> 	assert.Equal(t, c.Config.Labels[containerTypeLabelKey], containerTypeLabelSandbox)
> 	assert.Equal(t, c.Config.Labels[types.KubernetesContainerNameLabel], sandboxContainerName)
> 
> 	time.Sleep(2*time.Second)
> 	startTime := time.Now()
> 	expected.Id = id // ID is only known after the creation.
> 	_, err = ds.PodSandboxStatus(getTestCTX(), &runtimeapi.PodSandboxStatusRequest{PodSandboxId: id})
> 	require.NoError(t, err)
> 	//assert.Equal(t, expected, statusResp.Status)
> 	duration := time.Now().Sub(startTime)
> 	t.Logf("PodSandboxStatus cost %v", duration)
> }
> ```
> 
> Result:
> 
> ```
> === RUN   TestSandboxStatusWhenRunPodSandbox
> I0125 20:50:21.347380    2276 docker_sandbox.go:406] "Failed to read pod IP from plugin/docker" err="Couldn't find network status for bar/foo through plugin: invalid network status for"
> --- PASS: TestSandboxStatusWhenRunPodSandbox (10.02s)
> ```
> 
> ### Anything else we need to know?
> Can we call `ds.setNetworkReady(podSandboxID, false)` before `ds.network.TearDownPod(namespace, name, cID)`, and call `ds.setNetworkReady(podSandboxID, true)` to restore it to true when an error is returned.
> 
> ```go
> 	if !hostNetwork && (ready || !ok) {
> 		// Only tear down the pod network if we haven't done so already
> 		ds.setNetworkReady(podSandboxID, false)
> 		cID := kubecontainer.BuildContainerID(runtimeName, podSandboxID)
> 		err := ds.network.TearDownPod(namespace, name, cID)
> 		if err != nil {
> 			ds.setNetworkReady(podSandboxID, true)
> 			errList = append(errList, err)
> 		}
> 	}
> ```
> 
> And I'm not sure if `RunPodsandbox` could block `PodSandboxStatus`, it seems like not. But I still wonder to known that condition in `PodSandboxStatus` could be changed like this:
> 
> ```go
> 	ready, ok := ds.getNetworkReady(podSandboxID)
> 	if !ok || !ready {
> 		return nil
> 	}
> ```
> 
> ### Kubernetes version
> ### Cloud provider
> ### OS version
> ### Install tools
> ### Container runtime (CRI) and and version (if applicable)
> ### Related plugins (CNI, CSI, ...) and versions (if applicable)

**Comment by liushi001** [comment]
I'v tested that `RunPodSandbox` could also block `PodSandboxStatus` after kubelet restart, which may cause PLEG be not healthy.

I think it's because networkReady has not been initialized of the status of a pod.

**Comment by aojea** [comment]
@dcbw you may find this bug interesting

**Comment by liushi001** [comment]
I'm wondering whether those lock of CNI should be necessary after PodWorker refactorred from #104847, which moves pod killer to PodWorker.
@dcbw @smarterclayton

**Comment by aojea** [comment]
@liushi001 that code is no longer in the kubelet since the dockershim removal, or am I  looking at the wrong place? can you please verify that happens on master?

**Comment by liushi001** [comment]
> @liushi001 that code is no longer in the kubelet since the dockershim removal, or am I looking at the wrong place? can you please verify that happens on master?

Yes, these locks exsits in dockershim. The K8S version is 1.22, and dockershim is still used.

**Comment by aojea** [comment]
> > @liushi001 that code is no longer in the kubelet since the dockershim removal, or am I looking at the wrong place? can you please verify that happens on master?
> 
> Yes, these locks exsits in dockershim. The K8S version is 1.22, and dockershim is still used.

the deprecation started in 1.20 https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Comment by liushi001** [comment]
> > > @liushi001 that code is no longer in the kubelet since the dockershim removal, or am I looking at the wrong place? can you please verify that happens on master?
> > 
> > 
> > Yes, these locks exsits in dockershim. The K8S version is 1.22, and dockershim is still used.
> 
> the deprecation started in 1.20 https://kubernetes.io/blog/2020/12/02/dockershim-faq/

Sorry, I just noticed it has been deprecated in 1.20 but removed in 1.24, and our old version cluster was still use dockershim, but in our latest version of the product has been replaced by containerd.
