### ISSUE TITLE
e2e test should wait for kube-root-ca.crt to be created in the namespace

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#107762]
> I did a trivial pass on 1.20 -> 1.23 e2e serial runs in openshift ci environments, and while I see the failed mount errors during test pod creation, all of them seemed to be associated with races between the test creating the secret/config map and the pod getting created (i.e. some background controller creates the items, the kubelet gets the pod before the background controller can create the object).  These were serial jobs, so the kubelet is fairly lightly loaded.
> 
> Comparing to the parallel tests which run more hot (cpu is typically maxed on workers or close to it), I still don't see any obvious inexplicable FailedMount errors - instead I see the more explicable ones which are related to e2e tests apparently not waiting for kube-root-ca.crt to be created in the namespace.  I'll separate that out into a different issue since it's more of a noise in e2e (reducing my ability to spot true failures).  If we got a fix for that it would likely improve the ability to spot this in ci clusters.
> 
> So at least from a scan of CI runs, I don't see strong evidence of this being triggered by our e2e tests in dense clusters.  Which means that its frequency is low and/or the scenario that triggers it isn't exercised by the kube e2e suite.
> 
> Absent an obvious reproducer, I'll poke at the code next.

_Originally posted by @smarterclayton in https://github.com/kubernetes/kubernetes/issues/105204#issuecomment-1021463140_

**Comment by smarterclayton** [comment]
/hold

I have a subtly different fix in https://github.com/kubernetes/kubernetes/pull/107763 :)

**Comment by smarterclayton** [comment]
Oh wait, this is an issue.  Yay, thanks :).  Fixed in https://github.com/kubernetes/kubernetes/pull/107763
