### ISSUE TITLE
Figure out "post release build validation steps"

### ISSUE THREAD

**Issue by zmerlynn** [kubernetes/kubernetes#10777]
This is a follow-on to https://github.com/GoogleCloudPlatform/kubernetes/pull/10709#discussion_r33963117. We don't have an easy way outside of GKE validation of a build to do "grab a tarball and validate it using e2es, etc." It's not hard, necessarily. It's slightly different than #10676, which is about validating the source on the release branch.

**Comment by mbforbes** [comment]
I'm not sure whether we could need a good deployment story more than we do now

**Comment by mbforbes** [comment]
+cc @ihmccreery

**Comment by roberthbailey** [comment]
Kubernetes now has a defined release process that doesn't depend on GKE validation, so I'm closing this as obsolete.
