### ISSUE TITLE
Kubelet does not assign node address on expanded ipv6 address

### ISSUE THREAD

**Issue by jyotimahapatra** [kubernetes/kubernetes#107735]
### What happened?

In AWS EKS a issue was discovered in ipv6 only clusters. When nodes with expanded ipv6 address are created `2600:1f14:1d4:d101:0:0:0:ba3d` the string comparison [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodestatus/setters.go#L129) ends up comparing `2600:1f14:1d4:d101:0:0:0:ba3d` and
`2600:1f14:1d4:d101::ba3d` and does not assign the ipv6 ip to the node object.

### What did you expect to happen?

The string comparison should happen on sanitized ipv6 addess so that any different format of the ipv6 address being sent through the string works.

### How can we reproduce it (as minimally and precisely as possible)?

On AWS EKS ipv6 clusters, scale the worker nodes until a worker node appears without the full 128bit ipv6 address octet. When such nodes are created, the node objects won't have internal-ip associated with them.

### Kubernetes version

<details>
1.21/1.22/1.23
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>
Ubuntu
```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
/sig network
/triage accepted

Thanks for the report, this seems like an obvious and straightforward bug.

/good-first-issue

**Comment by jyotimahapatra** [comment]
Ongoing PR for this https://github.com/kubernetes/kubernetes/pull/107736

**Comment by Chalmiller** [comment]
Hi @jyotimahapatra, will your PR close out this issue? If not, what work would still be required? I'd like to tackle this issue if it's still available to be worked on.

**Comment by jyotimahapatra** [comment]
@Chalmiller yes the PR is targeting this issue. I'm actively working on it

**Comment by MadhavJivrajani** [comment]
@jyotimahapatra looks like this is good to close. If I've overlooked anything, please feel free to reopen the issue (`/reopen`)
Thanks!
/close

**Comment by anguslees** [comment]
/reopen

Sorry for the run-around, but I think the applied patch is incorrect: https://github.com/bottlerocket-os/bottlerocket/pull/1925/files#r793301369  (only a partial fix)

**Comment by anguslees** [comment]
/close

Whoops, reopened the bug against wrong repo :blush:
