### ISSUE TITLE
when LogPath is empty, Kubelet removes some files that we don't expect to remove

### ISSUE THREAD

**Issue by diannaowa** [kubernetes/kubernetes#107717]
### What happened?

I am implementing a Runtime for Kubernetes using CRI.
When containerStatus.Status.LogPath is empty, Kubelet removes some files that we don't expect to remove, such as /bin symbolic links.

### What did you expect to happen?

I think Kubelet will print an error log telling me that LogPath cannot be empty

### How can we reproduce it (as minimally and precisely as possible)?

 When implementing CRI,Return an ContainerStatus with an empty LogPath(ContainerStatusResponse.Status.LogPath).

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
@diannaowa This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue. It's important to include the full filenames of affected files.

Once more details are provided, the bug will be accepted.

/triage needs-information

**Comment by diannaowa** [comment]
Thanks for your comments.
I implemented a custom runtime with CRI, but I didn't return LogPath in ContainerStatus.

Kubelet gets the following error log when removing pod
kubelet logs:

`Jan 23 03:25:57 k8s-wasm02 kubelet: I0123 03:25:57.164035   28980 scope.go:110] "RemoveContainer" containerID="b5988275-8f6c-47da-9822-81fc90700e1a"
Jan 23 03:25:57 k8s-wasm02 kubelet: E0123 03:25:57.164577   28980 kuberuntime_gc.go:146] "Failed to remove container" err="failed to remove container \"b5988275-8f6c-47da-9822-81fc90700e1a\" log \"boot\": remove boot: directory not empty" containerID="b5988275-8f6c-47da-9822-81fc90700e1a"
Jan 23 03:25:57 k8s-wasm02 kubelet: I0123 03:25:57.164600   28980 scope.go:110] "RemoveContainer" containerID="b016f667-21be-4a9d-a0ba-feeefcbc7dce"
Jan 23 03:25:57 k8s-wasm02 kubelet: E0123 03:25:57.165046   28980 kuberuntime_gc.go:146] "Failed to remove container" err="failed to remove container \"b016f667-21be-4a9d-a0ba-feeefcbc7dce\" log \"boot\": remove boot: directory not empty" containerID="b016f667-21be-4a9d-a0ba-feeefcbc7dce"
Jan 23 03:25:57 k8s-wasm02 kubelet: I0123 03:25:57.165064   28980 scope.go:110] "RemoveContainer" containerID="a6bbb146-e837-475d-b09e-4403a1dd6fbe"`

Cluster version:
`uname -a
Linux k8s-wasm02 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

`Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by diannaowa** [comment]
The logs show that Kubelet is deleting some important system files

**Comment by tossmilestone** [comment]
The kubelet could not decide where the log path the cri provided is system-important or not, the host os should run the kubelet with restricted permission to protect it to delete the system files.

**Comment by ehashman** [comment]
@diannaowa From what you have shared here, it sounds like you have concluded that you had a bug in your CRI implementation. If you can demonstrate that the kubelet has broken the CRI guarantees then we may be able to fix those bugs, but we are not able to provide you with assistance for fixing issues with your custom CRI implementation. For that, we would need a *full* dump of all kubelet logs from startup to shutdown, not merely one or two lines.

/close
