### ISSUE TITLE
Docker k8s setup instructions to have DNS option

### ISSUE THREAD

**Issue by borg286** [kubernetes/kubernetes#10774]
Please add a way to add DNS support to the setup instructions for getting a kubernetes cluster using docker.
The SkyDNS server already has a yaml file  and would exist as a pod and service just as the current apiserver pods exist.

**Comment by yujuhong** [comment]
@borg286, [DNS is offered as cluster add-ons] (see https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/dns.md), and will be created automatically if you use our cluster setup scripts. Please see the [getting started guide](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/README.md) and select the OS/infra combination that suits your need. If there are any instructions missing or unclear, feel free to report it here. Thanks.

**Comment by borg286** [comment]
The docker option does not use those setup scripts. According to your documentation it would be done by passing a flag to the kubelet pointing it to the DNS server, and to have the DNS server spun up with the salted yaml file. For the simplistic case that the docker setup tries to solve it isn't far fetched to make some simple assumptions like the domain to be used.

**Comment by kelseyhightower** [comment]
@yujuhong Will running k8s in containers prevent the DNS addon from working because of the inability to mount secrets? We have an issue right now with the Kubelet running in a container and the fact that Docker 1.7+ does now allow the mounts created by the Kubelet to show up in other containers.

**Comment by WIZARD-CXY** [comment]
I think I can do it.Because I developed the dns deployment for ubuntu https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/ubuntu/deployAddons.sh.It just need deploy a dns rc and service.@brendandburns

**Comment by WIZARD-CXY** [comment]
@kelseyhightower It seems the newest dns doesn't require mounting token.It is automatically handled by service account if I understand right.

**Comment by brendandburns** [comment]
Yes, we should do this.  It's a wart that it's not there right now.

**Comment by WIZARD-CXY** [comment]
Ok, I will add it today

**Comment by pmorie** [comment]
@WIZARD-CXY The service account's tokens are delivered via secrets 

@kelseyhightower I will double check but this would be one use-case that doesn't work under 1.7 now when the kubelet is containerized.

**Comment by WIZARD-CXY** [comment]
Roger Roger

**Comment by timothysc** [comment]
cc @rrati

**Comment by colemickens** [comment]
Is this still coming?

**Comment by WIZARD-CXY** [comment]
yeah ,it is https://github.com/kubernetes/kubernetes/pull/10829, waiting for a merge

**Comment by goltermann** [comment]
#10829 is merged.
