### ISSUE TITLE
[Flaky test] verify-master, verify-typecheck

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#107702]
### Which jobs are flaking?

sig-release-master-blocking 
* verify-master

### Which tests are flaking?

* ci-kubernetes-verify-master.Overall
* verify.typecheck

### Since when has it been flaking?

History goes back until January 7

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

```
Verifying verify-typecheck.sh
+++ Running case: verify.typecheck 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-typecheck.sh"
type-checking windows/arm64
type-checking linux/arm
type-checking linux/arm64
type-checking linux/amd64
type-checking windows/386
type-checking darwin/amd64
type-checking darwin/arm64
type-checking linux/ppc64le
signal: killed
!!! Type Check has failed. This may cause cross platform build failures.
!!! Please see https://git.k8s.io/kubernetes/test/typecheck for more information.
+++ exit code: 1
+++ error: 1
FAILED   verify-typecheck.sh	219s
```

* [k/hack/verify-typecheck.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-typecheck.sh)
* [k//test/typecheck](https://github.com/kubernetes/kubernetes/tree/master/test/typecheck)

### Relevant SIG(s)

/sig testing (I guess)

cc @kubernetes/ci-signal

**Comment by shuheiktgw** [comment]
I've looked into the issue a bit and found two possibly related issues
- https://github.com/kubernetes/kubernetes/issues/105681
- https://github.com/kubernetes/test-infra/issues/23374

**Comment by BenTheElder** [comment]
in presubmit the concurrency was reduced IIRC (to reduce memory used at any given time, this regressed in go). glancing at these logs suggests the same probably needs to be done here.

there's some suggestion that a) go 1.18 has this patched already and that b) the go team may backport a fix to go1.17 https://github.com/golang/go/issues/49035

**Comment by shuheiktgw** [comment]
Thank you for your input, @BenTheElder! Let me check if we can reduce the concurrency 👍 
Let me know if you already know where I should look into!

**Comment by shuheiktgw** [comment]
Created a PR to reduce the parallel run to 1!
https://github.com/kubernetes/kubernetes/pull/107864

**Comment by BenTheElder** [comment]
That seems excessive, that's not what we're doing in presubmit is it?

**Comment by shuheiktgw** [comment]
I'll keep investigating the issue, yet if someone knows what we should do here please take the issue 🙏 
/unassign

**Comment by shuheiktgw** [comment]
@BenTheElder I've looked into [the job defenition](https://github.com/kubernetes/test-infra/blob/af7ef01953f8105a62537324e0ee7c8c58980415/config/jobs/kubernetes/sig-testing/verify.yaml) but I could not find the part where we reduce the concurrency. If that is the case, one solution I could come up with is to make either of [those two configurations ](https://github.com/kubernetes/kubernetes/blob/master/test/typecheck/main.go#L41-L42)configurable via an environment variable and pass the variable [here](https://github.com/kubernetes/test-infra/blob/af7ef01953f8105a62537324e0ee7c8c58980415/config/jobs/kubernetes/sig-testing/verify.yaml#L126). What do you think? 🤔

**Comment by leonardpahlke** [comment]
The job is still flaky. Not sure whom to contact

cc @BenTheElder @thockin @cblecker

**Comment by lauralorenz** [comment]
CI Signal Shadow here, still has flaky behavior

**Comment by eddiezane** [comment]
It looks like there isn't progress yet fixing this upstream in Go https://github.com/golang/go/issues/49035.

I'll get the test updated to using 1 more now.

/assign
