### ISSUE TITLE
podpreset is not working with 1.21 k8s version

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#107741]
### What happened?

Hi, 

We were using Kubernetes 1.16 release, we were using pod preset plugin to inject runtime timezone configuration(so that pods will be in the same time as hosts) to the Kube-system pod and as well other pods in a different namespace. 
Now, we are upgrading k8s to 1.21 and could see the pod preset plugin is not there, and timezone configurations are not injecting or getting applied to pods at run time.

Is there any other alternative release in 1.21? or any possible way we can achieve the above scenario?

### What did you expect to happen?

Pod Preset plugin support should not be removed or there should be any other way to achieve the above.

all pods should be able to get into same timezone as hosts.the 

### How can we reproduce it (as minimally and precisely as possible)?

Try to use pod preset plugin in 1.21.the 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux ubuntu 4.15.0-162-generic #170-Ubuntu SMP Mon Oct 18 11:38:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
PodPreset was removed in #94090 (1.8 added, 1.20 removed)

Some alternatives  can refer to https://github.com/kubernetes/kubernetes/issues/93900#issuecomment-774460034 \ https://github.com/kubernetes/kubernetes/issues/69640#issuecomment-675734553

**Comment by liggitt** [comment]
That's correct, the API did not graduate from alpha and was removed in 1.20. The linked resources are good example alternatives.

/close

**Comment by yonatankahana** [comment]
@akshaysharama with [k8tz](https://github.com/k8tz/k8tz) it can be done automatically without `PodPreset`

**Comment by tavin** [comment]
> That's correct, the API did not graduate from alpha and was removed in 1.20. The linked resources are good example alternatives.

@liggitt Is it a completely insane idea to bring PodPreset back as beta (or v1)? As an average user (i.e. sysadmin / devops engineer) I have no idea what's behind a failure to graduate from alpha. I just know I was using it, along with other people, and I'm willing to submit PRs.
