### ISSUE TITLE
[Flaky test] ci-kubernetes-unit

### ISSUE THREAD

**Issue by Nivedita-coder** [kubernetes/kubernetes#107708]
### Which jobs are flaking?

- ci-kubernetes-unit

### Which tests are flaking?

- ci-kubernetes-unit.Overall

- k8s.io/kubernetes/pkg/kubelet/eviction.TestStart

- k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestTimeoutHeaders

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection/redirect_=_true

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection/redirect_=_true/proxied_with_valid_auth_->_https_(valid_hostname_+_RootCAs) 

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection/redirect_=_true/proxied_with_valid_auth_->_http

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection/redirect_=_false

- k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy. TestRoundTripSocks5AndNewConnection/redirect_=_false/proxied_with_valid_auth_->_https_(invalid_hostname_+_InsecureSkipVerify)

### Since when has it been flaking?

History goes back to 2021-12-30

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Relevant SIG(s)

/sig testing (I guess)
cc @kubernetes/ci-signal

**Comment by aojea** [comment]
errors related to connection failures, snippet from 2 different jobs

> > === FAIL: vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy TestRoundTripSocks5AndNewConnection/redirect_=_false/proxied_with_valid_auth_->_http (0.07s)
> 2022/01/24 05:09:20 [ERR] socks: Failed to handle request: readfrom tcp 127.0.0.1:40351->127.0.0.1:33160: splice: connection reset by peer
>     roundtripper_test.go:590: ServeConn error: Failed to handle request: readfrom tcp 127.0.0.1:40351->127.0.0.1:33160: splice: connection reset by peer
>         --- FAIL: TestRoundTripSocks5AndNewConnection/redirect_=_false/proxied_with_valid_auth_->_http (0.07s)
> 
> 

and


> === Failed
> === FAIL: vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy TestRoundTripSocks5AndNewConnection/redirect_=_false/proxied_with_valid_auth_->_https_(invalid_hostname_+_InsecureSkipVerify) (0.10s)
> 2022/01/23 17:04:15 [ERR] socks: Failed to handle request: readfrom tcp 127.0.0.1:32846->127.0.0.1:45495: splice: broken pipe
>     roundtripper_test.go:590: ServeConn error: Failed to handle request: readfrom tcp 127.0.0.1:32846->127.0.0.1:45495: splice: broken pipe
>         --- FAIL: TestRoundTripSocks5AndNewConnection/redirect_=_false/proxied_with_valid_auth_->_https_(invalid_hostname_+_InsecureSkipVerify) (0.10s)

**Comment by aojea** [comment]
started to flake recently based on 

https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=TestRoundTripSocks5AndNewConnection

The test `TestRoundTripSocks5AndNewConnection` was added in 

https://github.com/kubernetes/kubernetes/pull/105632/commits/0a98875e9572d998fbdf3bcdaef4961715b8bc06

similar error on the socks5 dependency

https://github.com/armon/go-socks5/issues/34

The error seems to come from 

https://github.com/armon/go-socks5/blob/e75332964ef517daa070d7c38a9466a0d687e0a5/socks5.go#L161-L166


I'll keep investigating once I have more time, my main suspicion now is a race in the go-socks5 module similar to the one fixed here https://github.com/golang/go/issues/40888

/cc @liggitt

**Comment by liggitt** [comment]
cc @xens
