### ISSUE TITLE
audit logs are not getting generated for deployment, statefulset, pvc

### ISSUE THREAD

**Issue by rshiva777** [kubernetes/kubernetes#107759]
### What happened?

I have enabled audit logging on apiserver and capturing all resources
resources: ["persistentvolumeclaims", "persistentvolume", "pods", "events", "deployments", "statefulsets","daemonsets", "secrets", "configmaps"]

i am not getting the audit log for deployments, daemonsets, statefulsets, persistentvolume like which user has created or deleted the resource

### What did you expect to happen?

i am expecting the user details who ever deleted or created the deployments, daemonsets, statefulsets, persistentvolume resources

### How can we reproduce it (as minimally and precisely as possible)?

apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Metadata
    resources:
    - group: ""
      resources: ["persistentvolumeclaims", "persistentvolume", "pods", "events", "deployment", "statefulsets","daemonsets", "secrets", "configmaps"]
  - level: Request
    resources:
    - group: ""
      resources: ["persistentvolumeclaims", "persistentvolume", "pods", "events", "deployments", "statefulsets","daemonsets", "secrets", "configmaps"]
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["persistentvolumeclaims", "persistentvolume", "pods", "events", "deploy", "statefulsets","daemonsets", "secrets", "configmaps"]

Enable audit logging with the above policy.

 kubectl create deploy nginx -n testing  --image=nginx 

we should see the kubernetes-admin user or whoever trigger it, in the audit log

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>
on-premise
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux k8s-master01 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rshiva777** [comment]
if i create or delete a pod, i am able to see the user who deleted it

![image](https://user-images.githubusercontent.com/42074614/151103053-03ad55bd-63db-4bc1-b766-6f7272fe3447.png)


In case of deleting or creating a deployment, i dont see the user name, but i see the system serviceaccount as below:

![image](https://user-images.githubusercontent.com/42074614/151102976-83dacfc8-16e4-4c87-af63-037794414818.png)


I expected the deployment creation or deletion should also show the user who initiated the action

**Comment by embik** [comment]
Deployments and StatefulSets are not part of the "core" API group. Your config says: `group: ""`, which targets that API group for resources to print audit logs for. You'll need to add a second item under `resources` that would look like this:

```yaml
- group: "apps"
  resources: ["deployments", "statefulsets"]
```

In addition, you need to change `persistentvolume` to `persistentvolumes` (everything else is plural, which is the format recognised by the audit config).

This is working as intended.

**Comment by rshiva777** [comment]
Thanks @embik . Its working fine.
