### ISSUE TITLE
useless finalizers keep running in background

### ISSUE THREAD

**Issue by wuyudian1** [kubernetes/kubernetes#107788]
### What happened?

When I removed rancher from my kubernets cluster, some finalizers keep running in background, and report many errors:

```bash
kubectl -n kube-system logs --tail 300 pod/kube-apiserver-ci-k8s-master-1 |grep ^E
```

>E0126 09:48:41.126515       1 crd_finalizer.go:299] projectroletemplatebindings.management.cattle.io failed with: timed out waiting for the condition
E0126 09:48:41.149681       1 crd_finalizer.go:299] globalrolebindings.management.cattle.io failed with: timed out waiting for the condition
E0126 09:48:41.240374       1 crd_finalizer.go:299] nodedrivers.management.cattle.io failed with: timed out waiting for the condition
E0126 09:48:41.299472       1 crd_finalizer.go:299] nodes.management.cattle.io failed with: timed out waiting for the condition
E0126 09:48:41.455318       1 crd_finalizer.go:156] Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "users.management.cattle.io": the object has been modified; please apply your changes to the latest version and try again
E0126 09:48:41.455384       1 crd_finalizer.go:299] users.management.cattle.io failed with: timed out waiting for the condition
E0126 09:49:41.182148       1 crd_finalizer.go:299] projects.management.cattle.io failed with: timed out waiting for the condition
E0126 09:49:41.441363       1 crd_finalizer.go:156] Operation cannot be fulfilled on customresourcedefinitions.apiextensions.k8s.io "roletemplates.management.cattle.io": the object has been modified; please apply your changes to the latest version and try again

### What did you expect to happen?

The cattle related finalizers should  be removed absolutely.

### How can we reproduce it (as minimally and precisely as possible)?

I do not whether it can be reproduced.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-1-19-4", GitCommit:"832dfd094a0c1a0dfe4303775e5e6047473bef6a", GitTreeState:"clean", BuildDate:"2021-05-05T18:01:29Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.19) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
should this be better open in the rancher github repo?

**Comment by MadhavJivrajani** [comment]
@wuyudian1 do you think it'd be ok to open it against rancher and close this? If not, please provide more info on what we could help with, thanks!

**Comment by neolit123** [comment]
/close

please reopen if there is evidence this is a core k8s issue.
