### ISSUE TITLE
Scheduling issue when both pod affinity and pod topology spread are specified

### ISSUE THREAD

**Issue by rbo54** [kubernetes/kubernetes#107888]
### What happened?

I'm trying to deploy 150 stateful sets, each containing a pod with a replica count of 4.
The pod specification specifies both pod affinity (since the four replicas in a namespace share a volume),
as well as they specify pod topology spread with a maxSkew  of 4.

These pods are deployed by a helm chart for the stateful set and pod, and a shell script invokes the helm chart
in a different namespace (pmtv1 ... pmtv150) in a loop.

sh insv.sh --instances 150 --nvolumes 1 --storage-class vxflexos --replicas 4 --podAffinity

Although I expect 600 pods of the application to be started and running, only 539 were started and running:
Total Pods: 576 Running: 539 Creating: 0 Errors: 0 CrashLoopBackoff: 0 Pending (unscheduled): 37

This is because the remaining pods were all scheduled to worker-10, which has 110 pods already, and thus can have no more:
[root@master1 ~]# k get pods -A -o wide | grep worker-10 | wc -l
110

Here are the pod balance counts for my application that has the topology spread with label "affinity: affinity":
node <none> running 0 creaating 0 errors 0
node worker-10 running 107 creaating 0 errors 0  (note there are three system pods not in the 107 count: calico-node, kube-proxy, and vxflexos-node csi driver)
node worker-2 running 52 creaating 0 errors 0
node worker-3 running 52 creaating 0 errors 0
node worker-4 running 60 creaating 0 errors 0
node worker-5 running 68 creaating 0 errors 0
node worker-6 running 40 creaating 0 errors 0
node worker-7 running 52 creaating 0 errors 0
node worker-8 running 60 creaating 0 errors 0
node worker-9 running 48 creaating 0 errors 0

It appears to me that the topologySpreadConstraints are not working, because the application has only 40 pods on worker-6, but 107 pods on worker-10.
This is clearly not a valid spread. The 600 pods should be able to be split over the 9 worker nodes (worker-2... worker-10; worker-1 is offline).
With 9 worker nodes we should only need an average of about 66.6 pods per node.

Here is what I specified for topology spread constraint:
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        affinity: affinity
    maxSkew: 4
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule

The namespaces that are not completely deployed all have a pod that is in Pending state because it cannot be scheduled to worker-10, like these examples:
[root@master1 ~]# for i in $pending; do k get pods -n $i -o wide; done
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.149   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          36m   xxx.xxx.xxx.205   worker-10   <none>           <none>
podmontest-2   0/1     Pending   0          34m   <none>            <none>      <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.143   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          36m   xxx.xxx.xxx.189   worker-10   <none>           <none>
podmontest-2   1/1     Running   0          35m   xxx.xxx.xxx.227   worker-10   <none>           <none>
podmontest-3   0/1     Pending   0          33m   <none>            <none>      <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.146   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          35m   xxx.xxx.xxx.221   worker-10   <none>           <none>
podmontest-2   0/1     Pending   0          33m   <none>            <none>      <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP               NODE       NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.4    worker-6   <none>           <none>
podmontest-1   1/1     Running   0          37m   xxx.xxx.xxx.38   worker-6   <none>           <none>
podmontest-2   1/1     Running   0          36m   xxx.xxx.xxx.41   worker-6   <none>           <none>
podmontest-3   1/1     Running   0          36m   xxx.xxx.xxx.23   worker-6   <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.137   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          35m   xxx.xxx.xxx.233   worker-10   <none>           <none>
podmontest-2   0/1     Pending   0          33m   <none>            <none>      <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.134   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          36m   xxx.xxx.xxx.202   worker-10   <none>           <none>
podmontest-2   0/1     Pending   0          34m   <none>            <none>      <none>           <none>
NAME           READY   STATUS    RESTARTS   AGE   IP                NODE        NOMINATED NODE   READINESS GATES
podmontest-0   1/1     Running   0          37m   xxx.xxx.xxx.163   worker-10   <none>           <none>
podmontest-1   1/1     Running   0          35m   xxx.xxx.xxx.217   worker-10   <none>           <none>
podmontest-2   0/1     Pending   0          34m   <none>            <none>      <none>           <none>

### What did you expect to happen?

I expected the namespaces to be have a maximum pod skew of 4, or least something approaching that. As you can see from the submission, worker-6 had the lowest number of pods with 40, and worker-10 had the highest number of pods with 107 (and adding in the three kube-system pods had hit the 110 pod limit.)

### How can we reproduce it (as minimally and precisely as possible)?

Deploy pods with pod podAffinity and podTopologySkew as shown in this example:

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-01-18T16:38:14Z"
  generateName: podmontest-
  labels:
    affinity: affinity
    app: podmontest-pmtv150
    controller-revision-hash: podmontest-c4d6d85d5
    podmon.dellemc.com/driver: csi-vxflexos
    statefulset.kubernetes.io/pod-name: podmontest-2
  name: podmontest-2
  namespace: pmtv150
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: podmontest
    uid: c4e63202-4f40-40b3-abc3-6dc50a5e2f44
  resourceVersion: "61205623"
  uid: 4c9216f2-969f-4d4d-a577-864cfd35e3fa
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - podmontest-pmtv150
        topologyKey: kubernetes.io/hostname
  containers:
  - args:
    - -doexit=true
    command:
    - /podmontest
    env:
    - name: ROOT_DIR
      value: /
    image: amaas-eos-mw1.cec.lab.emc.com:5036/podmontest:v0.0.54
    imagePullPolicy: IfNotPresent
    name: podmontest
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data0
      name: pvol0
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-l4c5b
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: podmontest-2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: podmontest
  serviceAccountName: podmontest
  subdomain: 2vols
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        affinity: affinity
    maxSkew: 4
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
  volumes:
  - name: pvol0
    persistentVolumeClaim:
      claimName: pvol0
  - name: kube-api-access-l4c5b
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-18T16:38:14Z"
    message: '0/13 nodes are available: 1 Too many pods, 1 node(s) were unschedulable,
      3 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn''t
      tolerate, 8 node(s) didn''t match pod affinity rules.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort

### Anything else we need to know?

If there is something wrong in the way I'm trying to use pod affinity or topology skew, please let me know. I've raised this issue a couple of times on sig-scheduling with no informative responses.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On premise kubernetes system deployed from kubernetes.io images.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux master1 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Tue Nov 16 14:42:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
[root@master1 sh]# crictl version
DEBU[0000] VersionRequest: &VersionRequest{Version:v1alpha2,}
DEBU[0000] VersionResponse: &VersionResponse{Version:0.1.0,RuntimeName:containerd,RuntimeVersion:1.2.0,RuntimeApiVersion:v1alpha2,}
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  1.2.0
RuntimeApiVersion:  v1alpha2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
https://github.com/dell/csi-powerflex
</details>

**Comment by kerthcet** [comment]
is there any logs useful for digging? like pod logs.

**Comment by rbo54** [comment]
Hi Kerthcet. I will be happy to provide pod logs but I'm not sure how that would help. The normally running pods are producing normal output in their logs. The Pending pods have not been scheduled, so they have no logs. Are there some logs from the scheduler that could be collected that would be helpful? If so, which kube-system pods should I get logs from?

**Comment by kerthcet** [comment]
Maybe you can provide the logs by describing the pending pods to see the scheduling failures.

**Comment by rbo54** [comment]
Will do. My system is down today for upgrade. I'll post that early next week. Thank you Kerthcet. The basic problem though is those pods have affinity to other pods as shown above that have already been scheduled and are running on node worker-10 as shown above.  However they cannot be scheduled because worker-10 has 110 pods executing and it will execute no more. If things were balanced according to the topology skew, this condition should not occur.

**Comment by kerthcet** [comment]
When we calculating matched pods, we are namespace selected. So in your scenario, the ratio is always 4:0, so I think the PodTopologySpread plugin works as well. If you want to allocate your pods averagely, maybe you can refer to NodeResourceFit plugin for help. https://kubernetes.io/docs/reference/scheduling/_print/#scheduling-plugins

https://github.com/kubernetes/kubernetes/blob/49dc22638164c415fd2c13d8a5f2013ca62151d1/pkg/scheduler/framework/plugins/podtopologyspread/common.go#L87-L99

As to the differences of these two experiments, I guess it's because of the scheduling decisions at that time. Please correct me if I misunderstood.

**Comment by rbo54** [comment]
Thanks kerthcet. This is a very helpful response. Let me try that out. Tom
