### ISSUE TITLE
A number of containerd tests fail to start

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107800]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu 
- https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.4 
- https://testgrid.k8s.io/sig-node-containerd#e2e-cos-device-plugin-gpu 
- https://testgrid.k8s.io/sig-node-containerd#e2e-ubuntu 

### Which tests are failing?

Tests wouldn't start.

### Since when has it been failing?

1/24 between 16:45-17:45

### Reason for failure (if possible)

@pacoxu  suggested that this PR seems to have broken many tests: https://github.com/kubernetes/test-infra/pull/24918#issuecomment-1021952307

### Anything else we need to know?

/assign @endocrimes 

as discussed at SIG Node

/priority important-soon

### Relevant SIG(s)

/sig node

**Comment by endocrimes** [comment]
Looks like they're failing because `ctr` is unavailable, digging further.

**Comment by bobbypage** [comment]
Yes, looks like `ctr` is not unavailable for some reason, thus node bootstrap is failing

For https://testgrid.k8s.io/sig-node-containerd#e2e-ubuntu

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-ubuntu-gce/1486597755479527424

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cri-containerd-e2e-ubuntu-gce/1486597755479527424/artifacts/bootstrap-e2e-minion-group-86fz/kube-node-installation.log

```
Jan 27 07:15:40.712396 bootstrap-e2e-minion-group-86fz configure.sh[1692]: ERROR ctr not found. Aborting.
Jan 27 07:15:40.721073 bootstrap-e2e-minion-group-86fz configure.sh[1692]: [cloud.kubernetes.monitoring.proto.SerialportLog] {"cluster_hash":"get-metadata-value-error","vm_instance_name":"bootstrap-e2e-minion-group-86fz","boot_id":"bc6a7abb6e45469da410c118578736c3","timestamp":"2022-01-27T07:15:40.714114757Z","bootstrap_status":{"step_name":"EnsureContainerRuntime","status":"ERROR","status_reason":"encountered non-zero exit code","latency":"0.00405502s"}}
```

**Comment by bobbypage** [comment]
I found something a bit weird. `ctr` should be installed by systemd service `containerd-installation.service`

I reran the test locally and did `journalctl -u kube-node-installation.service`

```
Jan 28 03:20:45 e2e-test-porterdavid-minion-group-5jrv configure.sh[1770]: ERROR ctr not found. Aborting.
Jan 28 03:20:45 e2e-test-porterdavid-minion-group-5jrv configure.sh[1770]: [cloud.kubernetes.monitoring.proto.SerialportLog] {"cluster_hash":"get-metadata-value-error","vm_instance_name":"e2e-test-porterd
Jan 28 03:20:45 e2e-test-porterdavid-minion-group-5jrv systemd[1]: kube-node-installation.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 28 03:20:45 e2e-test-porterdavid-minion-group-5jrv systemd[1]: kube-node-installation.service: Failed with result 'exit-code'.
Jan 28 03:20:45 e2e-test-porterdavid-minion-group-5jrv systemd[1]: Failed to start Download and install k8s binaries and configurations.
```

Looking at `journalctl -u containerd-installation.service`

```
Jan 28 03:20:46 e2e-test-porterdavid-minion-group-5jrv configure.sh[1769]: + tar xvf containerd.tar.gz
...
Jan 28 03:20:47 e2e-test-porterdavid-minion-group-5jrv configure.sh[1874]: usr/local/bin/ctr
...
Jan 28 03:20:49 e2e-test-porterdavid-minion-group-5jrv systemd[1]: Finished Download and install containerd binaries and configurations..
```

The strange thing is that error from ctr was at `Jan 28 03:20:45` which appears to be before the containerd tarball was extracted `Jan 28 03:20:46`.

I think we can only run ` kube-node-installation.service` after `containerd-installation.service` finishes, but it appears they are running in parallel.

**Comment by bobbypage** [comment]
From `systemctl list-dependencies`

```
●   ├─kubernetes.target
●   │ ├─kube-container-runtime-monitor.service
●   │ ├─kube-logrotate.service
●   │ ├─kube-logrotate.timer
●   │ ├─kube-node-configuration.service
●   │ ├─kube-node-installation.service
●   │ ├─kubelet-monitor.service
●   │ └─containerd.target
●   │   ├─containerd-installation.service
●   │   └─containerd.service
```

so it appears that there is no dependency where containerd target needs to run _before_ kube-node-installation.service

**Comment by adisky** [comment]
The containerd installation logs seems to have installed `ctr` 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1486902749667790848/artifacts/bootstrap-e2e-minion-group-8pw1/containerd-installation.log

Tests started suddenly failing after 25 Jan. Also there are no containerd installation log for passed tests, So were we installing containerd before? (possibly using the available one not sure)
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1485775863516499968/artifacts/bootstrap-e2e-minion-group-gfs8/

**Comment by bobbypage** [comment]
I'm testing this patch for cloud-init

```
porterdavid@porterdavid: ~/go/src/github.com/containerd/containerd on main [!?$]
$ git diff
diff --git a/contrib/gce/cloud-init/node.yaml b/contrib/gce/cloud-init/node.yaml
index 97d7ad429..56dae2419 100644
--- a/contrib/gce/cloud-init/node.yaml
+++ b/contrib/gce/cloud-init/node.yaml
@@ -69,7 +69,8 @@ write_files:
     content: |
       [Unit]
       Description=Download and install k8s binaries and configurations
-      After=network-online.target
+      After=network-online.target containerd.target
+      Wants=network-online.target containerd.target

       [Service]
       Type=oneshot
```

**Comment by adisky** [comment]
Possibly the reason is, previously it was not reaching to this `ensure_container_runtime` if condition which is verifying containerd installation as `container_runtime` was set to `remote`

https://github.com/kubernetes/kubernetes/pull/107663/files#diff-dcbe601f5e14c1d9d805d0daf3629e02d1e1ea2be615f6e7f3036ca90a25c6e4L597-L608

We were installing containerd for this job from containerd main repo, not from ubuntu repository 
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml#L9-#L10

**Comment by bobbypage** [comment]
That may be the issue, I tested patch in https://github.com/kubernetes/kubernetes/issues/107800#issuecomment-1023881016 and it looks like it did ensure the ordering of the services, but I still get the same `ERROR ctr not found. Aborting`, so it does not fix the issue.

**Comment by adisky** [comment]
@bobbypage should we try this https://github.com/kubernetes/kubernetes/pull/10783?

**Comment by bobbypage** [comment]
ah, I looked into a bit more another clue. I did the following:

```
diff --git a/cluster/gce/gci/configure.sh b/cluster/gce/gci/configure.sh
index fd7a6ebe369..2acba4b24cb 100644
--- a/cluster/gce/gci/configure.sh
+++ b/cluster/gce/gci/configure.sh
@@ -582,6 +582,7 @@ function install-containerd-ubuntu {
 }

 function ensure-container-runtime {
+  echo "bobbypage DEBUG - PATH=${PATH}"
```

Here's the journalctl logs

```
$ journalctl -u kube-node-installation.service
Jan 28 05:56:26 e2e-test-porterdavid-minion-group-7hms configure.sh[1837]: bobbypage DEBUG - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Jan 28 05:56:26 e2e-test-porterdavid-minion-group-7hms configure.sh[1837]: ERROR ctr not found. Aborting.
```

This PATH doesn't include ctr so the test won't find it

```
root@e2e-test-porterdavid-minion-group-7hms:~# PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin ctr

Command 'ctr' not found, but can be installed with:

apt install containerd
```

Instead ctr is installed under `/home/containerd/...`

```
root@e2e-test-porterdavid-minion-group-7hms:~# which ctr
/home/containerd/usr/local/bin//ctr
```

This gets added to login shell because of this

```
root@e2e-test-porterdavid-minion-group-7hms:~# cat /etc/profile.d/containerd_env.sh
export PATH=/home/containerd/usr/local/bin/:/home/containerd/usr/local/sbin/:$PATH
```

`/etc/profile.d/containerd_env.sh` is added by containerd script - https://github.com/containerd/containerd/blob/main/contrib/gce/configure.sh#L225-L226

**Comment by bobbypage** [comment]
So I think the another possible solution here is to source `/etc/profile.d/containerd_env.sh` if it exits so that `ctr` and related utilities are in the path. 

It looks like we simply didn't hit this code path before due to reasons mentioned in https://github.com/kubernetes/kubernetes/issues/107800#issuecomment-1023900103 so this is why it's only surfacing after  https://github.com/kubernetes/kubernetes/pull/107663.

**Comment by adisky** [comment]
That also sounds right, updating the PR

**Comment by endocrimes** [comment]
Looks like https://github.com/kubernetes/kubernetes/pull/107832 fixed [containerd-node-e2e-1.4](https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.4), which is nice progress. I'll look into the others again tomorrow (won't get a chance today).

**Comment by adisky** [comment]
containerd  `configure.sh` script is still running while we are verifying container runtime & getting error `ctr not found`
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1490923386925223936/artifacts/bootstrap-e2e-minion-group-9dsx/serial-1.log

and `/etc/profile.d/containerd_env.sh` is still not yet written, 
https://github.com/containerd/containerd/blob/main/contrib/gce/configure.sh#L225-L226

we need to skip this check, if we are going to install directly from containerd repo
https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/gci/configure.sh#L584

**Comment by endocrimes** [comment]
Fixing the systemd units ordering definitely feels like the right way to deal with this - rather than chasing down race conditions between them

**Comment by bobbypage** [comment]
See https://github.com/kubernetes/kubernetes/issues/107830#issuecomment-1034794589 and https://github.com/kubernetes/kubernetes/pull/108054

**Comment by adisky** [comment]
All tests are passing now, Thanks @bobbypage for fixing the ubuntu one 
/close

**Comment by bobbypage** [comment]
Thanks @adisky for your help and investigations as well!
