### ISSUE TITLE
Kubelet under MemoryPressure but there are much memory left on the node

### ISSUE THREAD

**Issue by freefri** [kubernetes/kubernetes#107899]
### What happened?

I am just reopening https://github.com/kubernetes/kubernetes/issues/52386

 `kubectl describe node 10.0.10.132` shows:

```
  MemoryPressure       True    Tue, 01 Feb 2022 09:44:34 +0100   Thu, 20 Jan 2022 04:54:21 +0100   KubeletHasInsufficientMemory   kubelet has insufficient memory available
```

On the allocated resources section from `kubectl describe` shows (check also the events):

```
Non-terminated Pods:          (3 in total)
  Namespace                   Name                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                     ------------  ----------  ---------------  -------------  ---
  kube-system                 kube-flannel-ds-4vbr5    100m (5%)     1 (50%)     50Mi (0%)        500Mi (6%)     55d
  kube-system                 kube-proxy-vrmmc         0 (0%)        0 (0%)      0 (0%)           0 (0%)         55d
  kube-system                 proxymux-client-mq9vn    50m (2%)      500m (25%)  64Mi (0%)        256Mi (3%)     47d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                150m (7%)   1500m (75%)
  memory             114Mi (1%)  756Mi (10%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)

Events:
  Type     Reason                Age                     From     Message
  ----     ------                ----                    ----     -------
  Warning  EvictionThresholdMet  92s (x103403 over 16d)  kubelet  Attempting to reclaim memory

```
`kubectl describe` also describes a Taint:

```
Taints:             node.kubernetes.io/memory-pressure:NoSchedule
```

But `kubectl top node  10.0.10.132` shows:

```
NAME          CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
10.0.10.132   67m          3%     7644Mi          104% 
```

And some **pods are evicted** because of memory reclaiming.

The `free -h` (command run on the node directly via ssh) shows that there is much free memory:
```
              total        used        free      shared  buff/cache   available
Mem:           7.2G        3.1G        445M        720M        3.7G        3.4G
```

So I can not understand why the node is under MemoryPressure. and why `top node` shows 104% of memory

### What did you expect to happen?

 The node should not be under `MemoryPressure` and not pods will be evicted.
How to reproduce it (as minimally and precisely as possible):

### How can we reproduce it (as minimally and precisely as possible)?

This is happening for me on Oracle cloud using OKE.

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T02:20:15Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"50317190d44dbdb51ae7ff430917b32ba96188b5", GitTreeState:"clean", BuildDate:"2021-06-30T14:20:31Z", GoVersion:"go1.15.13 BoringCrypto", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
OCI (Oracle cloud) using OKE (kubernetes cluster)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

AME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9


$ uname -a

Linux oke-czush7jywxq-nemiu5hnuqa-snq6prpjcoa-3-509894 5.4.17-2102.202.5.el7uek.x86_64 #2 SMP Sat May 22 16:17:06 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

It is not very clear when the measurements taken (between kubectl top and free -h) and what is hapenning on the node at that time. Perhaps kubelet is evicting something? kubelet.log may help troubleshoot, please attach. Also steps to repro would be useful

**Comment by freefri** [comment]
I will try to elaborate a little bit more on how and when the issue happened:

We are running our pods in a OKE cluster made of 5 pretty **small nodes** (OCI **VM.Standard.E3.Flex** with 8GB of memory)

After a few weeks (maybe 4 or 6 weeks) of everything running smooth one of the nodes stops accepting pods. At this time I am making the measurements displayed above.

When doing those measurements the server has **no running pods** (other than 3 kube-system pods) and has **no load**, the OS does not report big usage of resources (see free command) but node top command (which was executed at the **same time** than all other commands displayed above) shows big amount of ram used, which is causing pods to be evicted on this node.

The only way I've found so far to solve this problem is terminating the node with problems so OCI launches a new node. This is what I have done and for this reason I have no access to kubelet.log. 

If I would have kept the node running, in a few days a new node would have the same problem, and my cluster will run out of resources to run all scheduled services, and the whole cluster will fail.

This problem is happening on a regular basis every few weeks (already happened 4 times in the last months), so I am expecting to be able to provide kubelet.log using `journalctl -u kubelet` more info in the future.

**Comment by ehashman** [comment]
Free memory and available memory are [not the same thing](https://haydenjames.io/free-vs-available-memory-in-linux/). "Free" means the memory is not in use and can be allocated right now. "Available" means that if requested, the memory can be used. But you can see a bunch of that available memory *is* currently in use, under your "buff/cache". Typically, what this means is that memory is being used by the kernel to speed up heavy I/O operations: if you have a workload that is hitting disk a lot, that will be very slow compared to memory, so the kernel might opportunistically cache what your process was requesting from disk in memory instead to speed things up.

Your system only has ~450MB of free memory, which sounds like a memory pressure situation on an 8GB machine.

You shared `free -h` and a kubelet node description but not `top` or Prometheus metrics from cadvisor for your Kubernetes workloads. There are two possibilities here:

- There are non-Kubernetes workloads on the machine using a lot of memory
- The Kubernetes workloads on your machine are using a lot more memory than they requested/set limits for

In any case, I believe the node is working as expected. If `top` indicates otherwise, feel free to reopen.

/close

**Comment by freefri** [comment]
Hello, this happened again, so I am sharing some new details:

The output again from the `free -h` command:
```
              total        used        free      shared  buff/cache   available
Mem:           7.2G        3.5G        380M        709M        3.4G        3.0G
Swap:            0B          0B          0B
```

The output of the `top` command ordered by `%MEM`:
![image](https://user-images.githubusercontent.com/2754631/156530629-e5f94664-0b2e-4cd5-ad77-47b2e0bdc55d.png)

I think this should confirm there are non-Kubernetes workloads using a lot of memory.

Here a list of pods runing on this node from `kubectl describe node 10.0.10.161`:
```
Non-terminated Pods:          (4 in total)
  Namespace                   Name                      CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----                      ------------  ----------  ---------------  -------------  ---
  kube-system                 coredns-84774d75-tvhf8    100m (5%)     0 (0%)      70Mi (0%)        170Mi (2%)     22d
  kube-system                 kube-flannel-ds-jrm7r     100m (5%)     1 (50%)     50Mi (0%)        500Mi (6%)     22d
  kube-system                 kube-proxy-5r2qd          0 (0%)        0 (0%)      0 (0%)           0 (0%)         85d
  kube-system                 proxymux-client-vhj7l     50m (2%)      500m (25%)  64Mi (0%)        256Mi (3%)     77d
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                250m (12%)  1500m (75%)
  memory             184Mi (2%)  926Mi (12%)
  ephemeral-storage  0 (0%)      0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type     Reason                     Age                     From     Message
  ----     ------                     ----                    ----     -------
  Normal   NodeHasInsufficientMemory  54m (x134 over 26h)     kubelet  Node 10.0.10.161 status is now: NodeHasInsufficientMemory
  Normal   NodeHasSufficientMemory    5m38s (x137 over 26h)   kubelet  Node 10.0.10.161 status is now: NodeHasSufficientMemory
  Warning  EvictionThresholdMet       4m43s (x1817 over 26h)  kubelet  Attempting to reclaim memory
```

Top inside every pod:

```
# $ kubectl top pod coredns-84774d75-tvhf8 -n kube-system --containers
POD                      NAME      CPU(cores)   MEMORY(bytes)   
coredns-84774d75-tvhf8   coredns   6m           11Mi   

# $ kubectl top pod kube-flannel-ds-jrm7r  -n kube-system --containers
Error from server (NotFound): podmetrics.metrics.k8s.io "kube-system/kube-flannel-ds-jrm7r" not found
# Read from: /sys/fs/cgroup/memory memory.usage_in_bytes is 24121344 (24.12MB)

# $ kubectl top pod kube-proxy-5r2qd  -n kube-system --containerskubectl top pod kube-proxy-5r2qd  -n kube-system --containers
POD                NAME         CPU(cores)   MEMORY(bytes)   
kube-proxy-5r2qd   kube-proxy   1m           25Mi 

# $ kubectl top pod proxymux-client-vhj7l  -n kube-system --containerskubectl top pod proxymux-client-vhj7l  -n kube-system --containers
POD                     NAME              CPU(cores)   MEMORY(bytes)   
proxymux-client-vhj7l   proxymux-client   1m           39Mi 
 
```

I think this should confirm that the Kubernetes workloads on the machine are not using a lot of memory.

Could you please tell me if I am wrong in my assumptions?

**Comment by ehashman** [comment]
Your top screenshot again confirms you are using a large amount of [buffer cache](https://www.linuxtopia.org/online_books/linux_system_administrators_guide/buffer-cache.html). It is not accounted for in per-process memory usage views.

It also appears there is some sort of memory leak on your system, because the used memory by processes shown does not add up to anywhere near 3.6Gi. The node hasn't been rebooted in nearly 3 months (85d uptime). Have you tried rebooting the OS to reclaim memory?

In any case, this is purely Linux systems administration; the issue is not in Kubernetes.

**Comment by freefri** [comment]
Well `sync && echo 1 > /proc/sys/vm/drop_caches` showed a drop in cache memory from 3.4G to 1.8G, this is also adding some more free memory and Kubelet reported no memory pressure on the pod after doing this. But as you said, all processes in top should not be using us much as 3.1G displayed on free. 

```
# free -h
              total        used        free      shared  buff/cache   available
Mem:           7.2G        3.1G        2.3G        747M        1.8G        3.3G
Swap:            0B          0B          0B
```

Thank you for your help, I will keep investigating this issue as not related with Kubernetes

**Comment by gaojx** [comment]
Wouldn't make sense to treat os cache memory available for use, thus not contribute to memory pressure? In other word, when checking memory pressure, the index to check is free memory + cache memory.
