### ISSUE TITLE
[flake] Test_RaceTerminateRSList seems to be flaking

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#107811]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

k8s.io/kubernetes/pkg/proxy/ipvs.Test_RaceTerminateRSList

### Since when has it been flaking?

~1 day since merging of https://github.com/kubernetes/kubernetes/pull/107748

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Anything else we need to know?

Test introduced in https://github.com/kubernetes/kubernetes/pull/107748

### Relevant SIG(s)

/sig network

**Comment by aojea** [comment]
ahhhg
let me fix it

**Comment by cyclinder** [comment]
oh, I will take a look.
