### ISSUE TITLE
Create a resource-management tutorial

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#10781]
In #10242, @bgrant0607 said "We should create a resource-management tutorial, which explains things like how to debug OOMs, how to figure out resource usage with heapster, how to set and rollout resource limits, and how to use LimitRange. @vishh"

**Comment by erictune** [comment]
#10573 describes resources and limits.

**Comment by bgrant0607** [comment]
Related: #9553

**Comment by bgrant0607** [comment]
@vishh This is what I was talking about.

**Comment by vishh** [comment]
@bgrant0607: Acknowledged. I will come up with a tutorial soon.

**Comment by vishh** [comment]
I have a draft doc that ties together all the features around resource management. I will post a patch soon.

**Comment by davidopp** [comment]
ping @vishh -- has there been progress on documenting QoS? While you're working on your resource management uber-doc, it would probably be good to fold in some of the information [here]
(https://github.com/kubernetes/kubernetes/blob/cf6b3063b59f548c4567d7fc99c4c922c6aa5e1f/docs/design/resource-qos.md) into compute-resources.md just so people have some idea of how to use the different QoS levels.

**Comment by vishh** [comment]
I have two documents that were meant to go out as blog posts. But they
don't seem to go anywhere. I can re-purpose those docs to be posted on
Github instead.

On Mon, May 30, 2016 at 6:27 PM, David Oppenheimer <notifications@github.com

**Comment by davidopp** [comment]
@vishh I vaguely remember seeing at least one of these in review lately... can you send pointers to the PRs?

**Comment by vishh** [comment]
I got distracted into various other issues. I'm back to this issue and I
will post patches early next week.

On Fri, Jul 8, 2016 at 10:38 PM, David Oppenheimer <notifications@github.com

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by chenopis** [comment]
@vishh Was this ever completed?

**Comment by vishh** [comment]
Nope. I have shared some of the content I generated to @steveperry-53 who is working on addressing this issue I think.

**Comment by chenopis** [comment]
Ok, so we should close this and open it on the k8s.io side.

**Comment by vishh** [comment]
That's a good idea!

**Comment by steveperry-53** [comment]
I'm working on Task and Concept topics that cover this in PR 4158
<https://github.com/kubernetes/kubernetes.github.io/pull/4158>. We should
wait until PR 4158 is reviewed and published before we think about whether
a tutorial is necessary. My guess is that we will not need a tutorial in
addition to the Tasks and Concepts that are part of PR 4158.

**Comment by tengqm** [comment]
Again, this should be filed and tracked in kubernetes/website project, not here. Leaving it rotten should be okay. @dchen1107 WDYT?
