### ISSUE TITLE
Fake metadata: Concurrent map usage because of mutation of scheme

### ISSUE THREAD

**Issue by SurajPratap10** [kubernetes/kubernetes#107874]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/blob/f90267f0629e546d1c5217c19138e2e8f68bfa92/staging/src/k8s.io/client-go/metadata/fake/simple.go#L50-L52

Lines 50 to 52 in f90267f
![Screenshot 2022-01-31 091220](https://user-images.githubusercontent.com/92919173/151735928-774e907c-c34e-4712-9f48-e45f8da663ba.jpg)

### Why is this needed?

This scheme mutation leads to concurrent use of the same scheme to cause the program to panic. It would be ideal to do this in some concurrent/safe manner or add a warning in the very begining .

**Comment by jlsong01** [comment]
seems it's the dup of https://github.com/kubernetes/kubernetes/issues/107823, which I have been working on.

**Comment by MadhavJivrajani** [comment]
Thanks for bringing that up @jlsong01!
/close
@SurajPratap10 please follow up on that issue if needed!
