### ISSUE TITLE
Improve network policy tests reliability on Windows nodes

### ISSUE THREAD

**Issue by knabben** [kubernetes/kubernetes#107853]
### What would you like to be added?

Decrease the TCP Retransmission time of AGNHOST Windows image from 3 seconds to 1 second. 
Probe timeout can be decreased as well to 2 seconds.

The RTO can be consistent on both Linux and Windows machines, providing a more reliable probing on network policy test suite.

Default RTO on windows agnhost:

```
C:/ $ netsh interface tcp show global
Querying active state...

TCP Global Parameters
----------------------------------------------
......
Initial RTO                         : 3000
```

### Why is this needed?

The [Windows Operational TEP](https://github.com/kubernetes/enhancements/pull/2975) will use these tests as part of validation.
With this change there's a possibility to decrease the error margin and speed up the test suite even on unreliable environments.

Thanks @hxietkg for doing the analysis.

**Comment by aojea** [comment]
RTO is a system value, isn't it?
I don't think tests should modify global system values

> With this change there's a possibility to decrease the error margin and speed up the test suite even on unreliable environments.

what error margin are we referring here? is this about specific tests or in general?

**Comment by knabben** [comment]
> RTO is a system value, isn't it? I don't think tests should modify global system values
> 

Will need to test - was expecting to be able changing the rto with netsh inside the container only, If this is not possible, totally agree to not change global values.

> > With this change there's a possibility to decrease the error margin and speed up the test suite even on unreliable environments.
> 
> what error margin are we referring here? is this about specific tests or in general?

default rto for windows is 3s, the probe timeout is 3s (on netpol test code), not giving time to probe TCP retransmission, in case the first packet is lost. The other option is to simply increase the probeTimeout values above the rto on both OSs.

**Comment by aojea** [comment]
> default rto for windows is 3s, the probe timeout is 3s (on netpol test code), not giving time to probe TCP retransmission, in case the first packet is lost. The other option is to simply increase the probeTimeout values above the rto on both OSs.

if first packet is lost that network is very unreliable , I mean, what benefit do you have in a cluster that passes the test but has a high packet drop rate?

**Comment by aojea** [comment]
I think we have very strict probe timeouts and we can use higher values and consolidate in, let's say 5 seconds , the TCP stack will handle the initial packet lost

**Comment by knabben** [comment]
> > default rto for windows is 3s, the probe timeout is 3s (on netpol test code), not giving time to probe TCP retransmission, in case the first packet is lost. The other option is to simply increase the probeTimeout values above the rto on both OSs.
> 
> if first packet is lost that network is very unreliable , I mean, what benefit do you have in a cluster that passes the test but has a high packet drop rate?

Yep, probably it will not pass much of the tests even if the change is applied. 
Still think the probe timeout can be fixed for Windows though, to at least > rto.

**Comment by aojea** [comment]
sorry, @knabben I edited that comment, I didn't get it right, you are right and we should leave room for the OS to handle it, but I think that the right fix is in increasing the probes timeouts

**Comment by knabben** [comment]
Thanks Antonio. Yes, agree on the approach as well. @hxietkg is working on it.  I will change the description after his input.

**Comment by aojea** [comment]
we don't have consistency, but 5s is also used in some service tests, 

```
test/e2e/network/service.go:            cmd = fmt.Sprintf("curl -q -s --connect-timeout 2 http://%s:%d/; test \"$?\" -ne \"0\"", svcName, port)
test/e2e/network/service.go:            cmd = fmt.Sprintf("curl -q -s --connect-timeout 2 http://%s:%d/", svcName, port)
test/e2e/network/service.go:                    cmd := fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, serviceAddress)
test/e2e/network/service.go:                    cmd := fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, serviceAddress)
test/e2e/network/service.go:                    cmd := fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, serviceAddress)
test/e2e/network/service.go:                    cmd := fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, serviceAddress)
test/e2e/network/service.go:    cmd := fmt.Sprintf(`curl -q -s --connect-timeout 2 http://%s/`, net.JoinHostPort(svcIP, strconv.Itoa(servicePort)))
```

**Comment by hxietkg** [comment]
Initial RTO is set to 3s in RFC 793, but it is updated to >=1s by RFC 6298, and modern OSes (windows, Linux etc..) use 1s, but image agnhost:2.32 is still using 3s RTO, 1s is enough for a roundtrip packet in modern network, network latency is less than 100ms in most of network env.

Just increasing probeTimeout from 3s to 4s/5s may handle the initial packet lost, but for a test testing a 'deny rule', we have to wait 4s/5s for connection timeout, that wastes much time.

**Comment by aojea** [comment]
> Just increasing probeTimeout from 3s to 4s/5s may handle the initial packet lost, but for a test testing a 'deny rule', we have to wait 4s/5s for connection timeout, that wastes much time.

there are always trade-offs , in a busy CI I've seen more than 1sec delay and seems that the report is about false positives like that, you have to choose between more stable or faster, ... just my 2 cents

**Comment by hxietkg** [comment]
> > Just increasing probeTimeout from 3s to 4s/5s may handle the initial packet lost, but for a test testing a 'deny rule', we have to wait 4s/5s for connection timeout, that wastes much time.
> 
> there are always trade-offs , in a busy CI I've seen more than 1sec delay and seems that the report is about false positives like that, you have to choose between more stable or faster, ... just my 2 cents

Does the 1+ seconds delay happen to Windows node/cluster only? RTO has already been 1s in Linux cluster for a long period, and seems it works well, if the 1s+ delay is caused by underlay network, not windows specific, we need to increase probeTimeout to 4 seconds for both windows and linux.
