### ISSUE TITLE
pull-kubernetes-integration timing out

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#107857]
### Which jobs are flaking?

pull-kubernetes-integration

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&graph-metrics=test-duration-minutes

### Which tests are flaking?

Unclear, the entire job is regularly failing with a 2 hour timeout

Relevant failures:
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1487329344022908928
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1486988995257700352
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-integration/1487116490741125120

### Since when has it been flaking?

Unclear (test history doesn't extend very long).

A bad rash of timeouts started when https://github.com/kubernetes/kubernetes/pull/107765 was merged, but that was rolled back in https://github.com/kubernetes/kubernetes/pull/107794. Timeouts improved, but are still seen regularly.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&graph-metrics=test-duration-minutes

### Relevant SIG(s)

/sig testing release

**Comment by liggitt** [comment]
bad runs all have a junit stdout of 700+ MB, good runs are ~300-400MB

**Comment by liggitt** [comment]
taking a random failed test in a random failed run, it looks like etcd dies, then the test keeps trying until the 10 minute timeout:

```
=== RUN   TestScaleAllResources
W0129 08:07:59.612301  117554 feature_gate.go:237] Setting GA feature gate ServerSideApply=true. It will be removed in a future release.
... normal bootstrapping stuff ...
I0129 08:08:01.803967  117554 httplog.go:131] "HTTP" verb="GET" URI="/healthz" latency="20.917419ms" userAgent="Go-http-client/1.1" audit-ID="accf7829-7f61-4a3a-b9f6-a6b045e2c385" srcIP="127.0.0.1:40746" apf_pl="exempt" apf_fs="exempt" apf_fd="" resp=500
{"level":"warn","ts":"2022-01-29T08:10:45.090Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc02dfbd880/#initially=[http://127.0.0.1:2379]","attempt":0,"error":"rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout"}
... repeated ~100 times
W0129 08:10:50.986250  117554 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: i/o timeout". Reconnecting...
I0129 08:10:51.879493  117554 genericapiserver.go:477] [graceful-termination] apiserver is exiting
...
W0129 08:10:58.344173  117554 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: i/o timeout". Reconnecting...
... repeated ~400 times
W0129 08:11:43.000484  117554 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 127.0.0.1 <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: i/o timeout". Reconnecting...
panic: test timed out after 10m0s
```

**Comment by aojea** [comment]
Thansk to @MikeSpreitzer, now we have metrics on this job https://github.com/kubernetes/kubernetes/pull/106190

His script expect a tarball, so I've modified it to use a directory directly, because we can access the gcs bucket directly with `gsutil`

```diff
diff --git a/hack/run-prometheus-on-etcd-scrapes.sh b/hack/run-prometheus-on-etcd-scrapes.sh
index e1edd582864..1bcbbc3df47 100755
--- a/hack/run-prometheus-on-etcd-scrapes.sh
+++ b/hack/run-prometheus-on-etcd-scrapes.sh
@@ -36,26 +36,24 @@
 # - an `nc` command that serve-prom-scrapes.sh knows how to wrangle
 
 if (( $# != 1 )); then
-    echo "Usage: $0 \$scrapes_tar_pathname" >&2
+    echo "Usage: $0 \$scrapes_folder" >&2
     exit 1
 fi
 
-scrapes_file="$1"
+UNPACKDIR="$1"
 
-if ! [[ -r "$scrapes_file" ]]; then
-    echo "$0: $scrapes_file is not a readable file" >&2
+if ! [[ -r "$UNPACKDIR" ]]; then
+    echo "$0: $UNPACKDIR is not a readable dir" >&2
     exit 2
 fi
 
 SCRIPT_ROOT=$(dirname "${BASH_SOURCE[0]}")
 
 CONFIG="/tmp/$(cd /tmp && mktemp config.XXXXXX)"
-UNPACKDIR="/tmp/$(cd /tmp && mktemp -d unpack.XXXXXX)"
 SERVER_PID=""
 
 cleanup_prom() {
     rm -f "$CONFIG"
-    rm -rf "$UNPACKDIR"
     if [[ -n "$SERVER_PID" ]]; then
        kill "$SERVER_PID"
     fi
@@ -65,8 +63,6 @@ trap cleanup_prom EXIT
 
 chmod +r "$CONFIG" "$UNPACKDIR"
 
-tar xzf "$scrapes_file" -C "$UNPACKDIR"
-
 if which ip > /dev/null; then
     IPADDR=$(ip addr show scope global up |
             grep -w inet | head -1 |

```

I've dumped the metrics from this job https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/107847/pull-kubernetes-integration/1487329344022908928/artifacts/

and run the script to analyze the etcd metrics
```sh
mkdir etcd-scrapes
gsutil -m cp gs://kubernetes-jenkins/pr-logs/pull/107847/pull-kubernetes-integration/1487329344022908928/artifacts/etcd-scrapes/*.scrape etcd-scrapes/

```

It takes some time to parse the metrics ~30 seconds/1min , you can check the status in the prometheus url http://localhost:9090/targets

Once they are loaded we can explore the metrics, after 8.30 etcd remains idle

![image](https://user-images.githubusercontent.com/6450081/151677591-1df0e9fa-7078-4102-b182-ad1f18714992.png)

That matches the junit stdout logs

```
tail -n2 junit_20220129-080106.stdout
{"Time":"2022-01-29T08:26:06.558595248Z","Action":"output","Package":"k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration","Output":"ok  \tk8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration\t387.632s\n"}
{"Time":"2022-01-29T08:26:06.558647503Z","Action":"pass","Package":"k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration","Elapsed":387.633}
```

but what makes that the tests stops progressing? is etcd or is the framework? can some etcd expert take a quick look to the metrics?

**Comment by aojea** [comment]
another riddle we didn't solve, why the periodic job doesn't timeout?

https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5

**Comment by liggitt** [comment]
tagging api-machinery because the closest cause I can see seems to be somewhere in apiserver <-> etcd communication

**Comment by aojea** [comment]
another angle, the most expensive suites:
- good job
```sh
grep testsuite junit_20220130-231100.xml | grep time  | sort -n -t\" -k 6 -r
	<testsuite tests="154" failures="0" time="695.420000" name="k8s.io/kubernetes/test/integration/scheduler">
	<testsuite tests="23" failures="0" time="629.110000" name="k8s.io/kubernetes/test/integration/daemonset">
	<testsuite tests="135" failures="0" time="425.650000" name="k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration">
	<testsuite tests="59" failures="0" time="359.560000" name="k8s.io/kubernetes/test/integration/controlplane">
	<testsuite tests="1202" failures="0" time="335.960000" name="k8s.io/kubernetes/test/integration/apiserver/admissionwebhook">
	<testsuite tests="119" failures="0" time="333.750000" name="k8s.io/kubernetes/test/integration/client">
	<testsuite tests="30" failures="0" time="326.220000" name="k8s.io/kubernetes/test/integration/job">
	<testsuite tests="35" failures="0" time="296.230000" name="k8s.io/kubernetes/test/integration/volumescheduling">
```

- failing job
```sh
wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/107847/pull-kubernetes-integration/1487329344022908928/artifacts/junit_20220129-080106.stdout
gotestsum --junitfile junit.xml --raw-command cat junit_20220129-080106.stdout
grep testsuite junit.xml | grep time  | sort -n -t\" -k 6 -r
	<testsuite tests="15" failures="3" time="1142.660000" name="k8s.io/kubernetes/test/integration/daemonset">
	<testsuite tests="8" failures="2" time="905.250000" name="k8s.io/kubernetes/test/integration/disruption">
	<testsuite tests="154" failures="0" time="785.439000" name="k8s.io/kubernetes/test/integration/scheduler">
	<testsuite tests="34" failures="1" time="613.260000" name="k8s.io/kubernetes/test/integration/controlplane">
	<testsuite tests="135" failures="0" time="430.099000" name="k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration">
	<testsuite tests="1202" failures="0" time="402.410000" name="k8s.io/kubernetes/test/integration/apiserver/admissionwebhook">
	<testsuite tests="63" failures="2" time="386.130000" name="k8s.io/kubernetes/test/integration/client">
	<testsuite tests="30" failures="0" time="360.550000" name="k8s.io/kubernetes/test/integration/job">
	<testsuite tests="35" failures="0" time="342.270000" name="k8s.io/kubernetes/test/integration/volumescheduling">
	<testsuite tests="452" failures="1" time="299.310000" name="k8s.io/kubernetes/test/integration/apiserver">
	<testsuite tests="838" failures="1" time="274.950000" name="k8s.io/kubernetes/test/integration/auth">
	<testsuite tests="76" failures="1" time="259.080000" name="k8s.io/kubernetes/test/integration/apiserver/apply">
```

**Comment by tkashem** [comment]
cc @tkashem

**Comment by MikeSpreitzer** [comment]
@aojea : can we update the scripting so that we get the Prometheus scrapes both in the timeout and the success case?

**Comment by aojea** [comment]
> @aojea : can we update the scripting so that we get the Prometheus scrapes both in the timeout and the success case?

I think that we should, also we should try to get some info about the environment to try to understand why the tests stop and etcd keeps running, maybe dumping the process running at that moment, ...

**Comment by MikeSpreitzer** [comment]
@aojea : I created #107944 to generalize the script that runs Prometheus on the scrapes.  But it is another matter to collect the process list when a test times out; I do not know where that change would go.

**Comment by aojea** [comment]
> @aojea : I created #107944 to generalize the script that runs Prometheus on the scrapes. But it is another matter to collect the process list when a test times out; I do not know where that change would go.

I think we can trap some signal, I can't remember which one,  @BenTheElder you have done this before IIRC?

**Comment by BenTheElder** [comment]
@aojea it's the same as pods normally, SIGTERM
https://github.com/kubernetes/test-infra/blob/9703a3111217af8a9a4616883ab316c28f33e3cf/prow/entrypoint/run.go#L113

**Comment by BenTheElder** [comment]
two _years_ ago we dropped to 6 cores instead of 7 cores request, it's possible some < 1 core job in this cluster is running alongside the job and stomping node I/O or something:

https://github.com/kubernetes/test-infra/blame/7f5c364f8e38b4a4f28bc68f52e5c1257fe43f86/config/jobs/kubernetes/sig-testing/integration.yaml#L31

however not all that many jobs are allowed in the `cluster: k8s-infra-prow-build` right now, and they should pretty much all be requesting enough that we don't fit two to a node (8 cores minus overhead for system pods)

otherwise seems like a failure mode in k8s / etcd / ... internals under test.

**Comment by aojea** [comment]
new development happening here https://github.com/kubernetes/kubernetes/issues/109038

Closing as duplicate
/close
