### ISSUE TITLE
Missing annotation to specify private, static IPs for AWS NLB

### ISSUE THREAD

**Issue by mimmus** [kubernetes/kubernetes#107822]
### What happened?

Only annotation to specify EIP allocations for an **external** NLB is available:

```
// ServiceAnnotationLoadBalancerEIPAllocations is the annotation used on the
// service to specify a comma separated list of EIP allocations to use as
// static IP addresses for the NLB. Only supported on elbv2 (NLB)
const ServiceAnnotationLoadBalancerEIPAllocations = "service.beta.kubernetes.io/aws-load-balancer-eip-allocations"
```

but for an AWS internal NLB, you can assign a private IP address from the IPv4 range of each subnet instead of letting AWS assign one for you  (and this is very useful if you have an ALB in front of these).

### What did you expect to happen?

An annotation to specify a comma-separated list of private, static IPs for AWS internal NLB.

### How can we reproduce it (as minimally and precisely as possible)?

Looking at code:
[https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go](https://github.com/kubernetes/legacy-cloud-providers/blob/master/aws/aws.go)

### Kubernetes version

v1.20.11

### Cloud provider

AWS

**Comment by nckturner** [comment]
Currently this is supported in the [AWS Load Balancer controller](https://github.com/kubernetes-sigs/aws-load-balancer-controller) and the in-tree provider is deprecated and no longer accepted features.  If you still think you need this feature, please reopen this issue on the [cloud-provider-aws](https://github.com/kubernetes/cloud-provider-aws) repository and we can discuss it there.

/close
