### ISSUE TITLE
Pods fail with "restartPolicy: Always"

### ISSUE THREAD

**Issue by hj-johannes-lee** [kubernetes/kubernetes#107838]
### What happened?

```bash
$ cat testpod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-ubuntu
spec:
  containers:
  - name: container-ubuntu
    image: ubuntu:20.04
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "30s"]    

$ kubectl apply -f testpod.yaml 
pod/test-pod-ubuntu created

$ kubectl get pods test-pod-ubuntu
NAME              READY   STATUS             RESTARTS         AGE
test-pod-ubuntu   0/1     CrashLoopBackOff   10 (2m15s ago)   34m

$ tail -n 300 /var/log/syslog
...
Jan 28 16:11:08 hj-johannes-vm kubelet[815]: E0128 16:11:08.096467     815 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"container-ubuntu\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=container-ubuntu pod=test-pod-ubuntu_default(d697d991-cb76-4a15-9692-8ac99f713816)\"" pod="default/test-pod-ubuntu" podUID=d697d991-cb76-4a15-9692-8ac99f713816
Jan 28 16:11:23 hj-johannes-vm kubelet[815]: I0128 16:11:23.096372     815 scope.go:110] "RemoveContainer" containerID="b8f36e66c386e09a7b8f042409948a2239b85e87f3a067c76eaa956047098555"
Jan 28 16:11:23 hj-johannes-vm kubelet[815]: E0128 16:11:23.096678     815 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"container-ubuntu\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=container-ubuntu pod=test-pod-ubuntu_default(d697d991-cb76-4a15-9692-8ac99f713816)\"" pod="default/test-pod-ubuntu" podUID=d697d991-cb76-4a15-9692-8ac99f713816
Jan 28 16:11:37 hj-johannes-vm kubelet[815]: I0128 16:11:37.096710     815 scope.go:110] "RemoveContainer" containerID="b8f36e66c386e09a7b8f042409948a2239b85e87f3a067c76eaa956047098555"
Jan 28 16:11:37 hj-johannes-vm kubelet[815]: E0128 16:11:37.097128     815 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"container-ubuntu\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=container-ubuntu pod=test-pod-ubuntu_default(d697d991-cb76-4a15-9692-8ac99f713816)\"" pod="default/test-pod-ubuntu" podUID=d697d991-cb76-4a15-9692-8ac99f713816
```

As you can see, the status of the Pod I created using the yaml file I put above becomes "CrashLoopBackOff" when restartPolicy is set as "Always". After a while, it becomes "Running", but it again becomes "CrashLoopBackOff" after the next running is done. In addition, I can see the amount of time when the status remains as "CrashLoopBackOff" gets longer (up to about 5 minutes.)

I think same things would happen when using any kind of images where the status of the pod becomes "Completed" after running some kind of workloads in a container with the setting "restartPolicy: Always".

### What did you expect to happen?
What's happening now :
Running => Completed => CrashLoopBackOff => Running => Completed => CrashLoopBackOff ...

What I expected:
Running => Completed => Running => Completed => Running => Completed ...

### How can we reproduce it (as minimally and precisely as possible)?

I described above. Create a pod using the yaml file above. The status of Pod would become "CrashLoopBackOff" soon after a few times of cycles.

### Anything else we need to know?

I think, it's clear enough already.

I may have missed many things to consider. But, since there is no harm for me to raise my voice on this, I create this report.! Please correct me if I am wrong.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:29:16Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="21.04 (Hirsute Hippo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 21.04"
VERSION_ID="21.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
$ uname -a
Linux hj-johannes-vm 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yxxhero** [comment]
I didn't understand your question, but I think it's normal. Do you have any specific needs? I think you should set restart policy: never (or onfailure) @hj-johannes-lee

**Comment by hj-johannes-lee** [comment]
@yxxhero Hello, I actually changed the contents of the issue a little bit, since I see it as a bug that happens from the "restartPolicy" with "Always" option. Can you take a look?

**Comment by able8** [comment]
I also encountered this problem. The CrashLoopBackOff status maybe not be right here.
Because the container command is  ["/bin/sleep", "30s"] ,
What I expected:
Running => Completed => Running => Completed => Running => Completed ...

What's happening now :
Running => Completed => CrashLoopBackOff => Running => Completed => CrashLoopBackOff ...

**Comment by hj-johannes-lee** [comment]
@SergeyKanzhelev Could you let me know what more information would need to be provided?

**Comment by endocrimes** [comment]
/remove-kind bug
/kind support
/close

Kubernetes restarts containers with exponential backoff by design - https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy - Continuously restarting a workload is not really what the Pod abstraction is built for, as crashing frequently generally implies that there's a problem with the workload or its dependencies and this helps protect against thundering herds and cluster churn while things recovering.
