### ISSUE TITLE
sig-node-cri-o#node-kubelet-serial-crio: failing test Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107805]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio

### Which tests are flaking?

```
E2eNode Suite.[sig-node] Topology Manager [Serial] [Feature:TopologyManager][NodeFeature:TopologyManager] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite
```

Same test is skipped on containerd

### Since when has it been flaking?

At least from the new year.

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio

### Relevant SIG(s)

/sig node

**Comment by fromanirh** [comment]
the failures here seems genuine, and alarming. The test cases are not giving enough data, making the troubleshoot unnecessarily hard. Let's fix this first: https://github.com/kubernetes/kubernetes/pull/107915

**Comment by fromanirh** [comment]
green again since I checked last time
it seems the extra debug I added (https://github.com/kubernetes/kubernetes/pull/107915) is not needed yet :)
