### ISSUE TITLE
Missing annotation to specify private, static IPs (AWS NLB)

### ISSUE THREAD

**Issue by SurajPratap10** [kubernetes/kubernetes#107873]
### What would you like to be added?

Only annotation to specify EIP allocations for an external NLB is available:

// ServiceAnnotationLoadBalancerEIPAllocations is the annotation used on the
// service to specify a comma separated list of EIP allocations to use as
// static IP addresses for the NLB. Only supported on elbv2 (NLB)
const ServiceAnnotationLoadBalancerEIPAllocations = "service.beta.kubernetes.io/aws-load-balancer-eip-allocations"

but for an AWS internal NLB, you can assign a private IP address from the IPv4 range of each subnet instead of letting AWS assign one for you (and this is very useful if you have an ALB in front of these).

### Why is this needed?

I request for an annotation that specifies a comma-separated list of private, static IPs for AWS internal NLB.

**Comment by MadhavJivrajani** [comment]
/sig cloud-provider
(? please feel free to remove if not relevant)

**Comment by MadhavJivrajani** [comment]
@SurajPratap10 is this a duplicate of https://github.com/kubernetes/kubernetes/issues/107822 ?
If so, please close this one!
