### ISSUE TITLE
Many tests are failing since 1/24 in containerd tab

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#107801]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.4 
- https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.5 
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-e2e 

### Which tests are failing?

most of tests

### Since when has it been failing?

1/24 between 16:25-17:25

### Reason for failure (if possible)

Maybe related to https://github.com/kubernetes/kubernetes/issues/107800 

### Anything else we need to know?

/priority important-soon

### Relevant SIG(s)

/sig node

**Comment by bobbypage** [comment]
Created issue for `cos-cgroupv2-containerd-e2e` failure - https://github.com/kubernetes/kubernetes/issues/107830

**Comment by adisky** [comment]
closing this one as we have an issue for cgroupv2 job & rest are fixed 
https://github.com/kubernetes/test-infra/pull/25032
/close
