### ISSUE TITLE
Move `pkg/kubelet/cri/remote` to `cri-api` staging

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#107989]
### What would you like to be added?

The cri-api repository already exposes a bunch of interface definitions there: 
https://github.com/kubernetes/cri-api/blob/master/pkg/apis/services.go

The actual implementation of those interfaces, namely `RuntimeService` and `ImageManagerService` are part of the kubelet internal implementations:
https://github.com/kubernetes/kubernetes/blob/a266805f33197ba17577e2e71511f68ce9db57eb/pkg/kubelet/cri/remote/remote_runtime.go#L66-L67
https://github.com/kubernetes/kubernetes/blob/a266805f33197ba17577e2e71511f68ce9db57eb/pkg/kubelet/cri/remote/remote_image.go#L43-L44

Those example implementations could be used by tools like `crictl` to connect to remote runtimes (the default after dockershim removal) by importing the `cri-api` staging repository rather than the full k/k stack.

### Why is this needed?

- Reducing the import size and code duplication when connecting to remote runtimes via the CRI.
- Supporting multiple container runtime versions at once
- Considering API divergence between (let's say) CRI `v1` and a future `v2`, then the remote runtime implementation would do the necessary work to glue both APIs together.

**Comment by NikhilSharmaWe** [comment]
@saschagrunert Are you talking about importing only 
`github.com/kubernetes/cri-api`
instead of 
```
internalapi "k8s.io/cri-api/pkg/apis"
runtimeapi "k8s.io/cri-api/pkg/apis/runtime/v1"
runtimeapiV1alpha2 "k8s.io/cri-api/pkg/apis/runtime/v1alpha2"
```

**Comment by saschagrunert** [comment]
@NikhilSharmaWe no I was more proposing an actual implementation for the existing interfaces there:
https://github.com/kubernetes/cri-api/blob/420de3a7ed3068cb89974a143e1ae345c0090576/pkg/apis/services.go#L96-L124

I would like to highlight this comment which states that it's probably not a good idea now: https://github.com/kubernetes/kubernetes/pull/106501#issuecomment-1032102323
