### ISSUE TITLE
Cannot produce older builds of Kubectl on Apple Silicon

### ISSUE THREAD

**Issue by blankenshipz** [kubernetes/kubernetes#107908]
### What happened?

I'm trying to build kubectl `v1.18.20` using the command `./build/run.sh make kubectl KUBE_BUILD_PLATFORMS=darwin/amd64` and the build fails 

```
❯ ./build/run.sh make kubectl KUBE_BUILD_PLATFORMS=darwin/amd64
+++ [0201 14:07:48] Verifying Prerequisites....
+++ [0201 14:07:48] Using Docker for MacOS
+++ [0201 14:07:49] Building Docker image kube-build:build-01d6ba8883-5-v1.13.15-1
+++ Docker build command failed for kube-build:build-01d6ba8883-5-v1.13.15-1

#1 [internal] load build definition from Dockerfile
#1 sha256:e11e58da2438de407dae95658c82298706f4b883159a0c92538c240097a698c2
#1 transferring dockerfile: 1.90kB done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 sha256:87cf684ec7a5ad402eaea9c8cba4b1d072964a37ab3d731d71b7f6bff18c2111
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [internal] load metadata for us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.13.15-1
#3 sha256:6f00d1a3955589f14424479936d54ea86350499029d06e7a0ea7b4ecad13d042
#3 ERROR: no match for platform in manifest sha256:7a9bb40e3f46641940d770e1aef137d11d3c87318d39f99bd2974b4e7daeea3e: not found
------
 > [internal] load metadata for us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v1.13.15-1:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:7a9bb40e3f46641940d770e1aef137d11d3c87318d39f99bd2974b4e7daeea3e: not found

To retry manually, run:

docker build -t kube-build:build-01d6ba8883-5-v1.13.15-1 --pull=false /Users/zach/Code/kubernetes/_output/images/kube-build:build-01d6ba8883-5-v1.13.15-1

!!! [0201 14:07:50] Call tree:
!!! [0201 14:07:50]  1: ./build/run.sh:31 kube::build::build_image(...)
!!! Error in ./build/../build/common.sh:431
  Error in ./build/../build/common.sh:431. 'return 1' exited with status 1
Call stack:
  1: ./build/../build/common.sh:431 kube::build::build_image(...)
  2: ./build/run.sh:31 main(...)
Exiting with status 1
```

### What did you expect to happen?

I expected the build to run and output the binary targeted at darwin/amd64

### How can we reproduce it (as minimally and precisely as possible)?

From an Apple Silicon Mac with Docker-For-Mac installed

```
git clone git@github.com:kubernetes/kubernetes.git
cd kubernetes 
./build/run.sh make kubectl KUBE_BUILD_PLATFORMS=darwin/amd64
```

### Kubernetes version

Attempting to build Kubectl for v1.18.0

### Cloud provider

N/A

### OS version

 Darwin Kernel Version 21.2.0:

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/d4b49be81a28a2de1c63bbd84ceb1bf3660fa983/hack/lib/golang.sh#L51

/sig release cli

https://github.com/kubernetes/k8s.io/blob/aafecb8676b1dde098e23594983fc41bf6b6ac15/k8s.gcr.io/images/k8s-staging-build-image/images.yaml#L468

**Comment by eddiezane** [comment]
darwin/arm support was added to Go 1.16 which we started using for Kubernetes 1.21.

I don't think the tooling (container) will be updated here since 1.18 is EOL but you should be able to build it locally with just `make kubectl KUBE_BUILD_PLATFORMS=darwin/amd64` if you have Go 1.16+ installed.

sig-release feel free to say otherwise

/close
