### ISSUE TITLE
Kubeadm init fails, Kubelet fails to start

### ISSUE THREAD

**Issue by drfrink** [kubernetes/kubernetes#107969]
### What happened?

Running into an issue with kubeadm init on a raspberry pi cluster

`
I0205 12:29:12.192138    5348 initconfiguration.go:117] detected and using CRI socket: /var/run/dockershim.sock
I0205 12:29:12.196554    5348 interface.go:432] Looking for default routes with IPv4 addresses
I0205 12:29:12.196600    5348 interface.go:437] Default route transits interface "wlan0"
I0205 12:29:12.196935    5348 interface.go:209] Interface wlan0 is up
I0205 12:29:12.197108    5348 interface.go:257] Interface "wlan0" has 2 addresses :[192.168.1.53/24 fe80::3a91:eb92:697c:f39f/64].
I0205 12:29:12.197183    5348 interface.go:224] Checking addr  192.168.1.53/24.
I0205 12:29:12.197213    5348 interface.go:231] IP found 192.168.1.53
I0205 12:29:12.197242    5348 interface.go:263] Found valid IPv4 address 192.168.1.53 for interface "wlan0".
I0205 12:29:12.197269    5348 interface.go:443] Found active IP 192.168.1.53 
I0205 12:29:12.197341    5348 kubelet.go:217] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
I0205 12:29:12.212586    5348 version.go:186] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.txt
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
I0205 12:29:12.689056    5348 checks.go:578] validating Kubernetes and kubeadm version
I0205 12:29:12.689114    5348 checks.go:171] validating if the firewall is enabled and active
I0205 12:29:12.715799    5348 checks.go:206] validating availability of port 6443
I0205 12:29:12.716322    5348 checks.go:206] validating availability of port 10259
I0205 12:29:12.716450    5348 checks.go:206] validating availability of port 10257
I0205 12:29:12.716594    5348 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0205 12:29:12.716661    5348 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0205 12:29:12.716720    5348 checks.go:283] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0205 12:29:12.716750    5348 checks.go:283] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0205 12:29:12.718750    5348 checks.go:433] validating if the connectivity type is via proxy or direct
I0205 12:29:12.718814    5348 checks.go:472] validating http connectivity to first IP address in the CIDR
I0205 12:29:12.718862    5348 checks.go:472] validating http connectivity to first IP address in the CIDR
I0205 12:29:12.718901    5348 checks.go:107] validating the container runtime
I0205 12:29:13.036800    5348 checks.go:133] validating if the "docker" service is enabled and active
I0205 12:29:13.082582    5348 checks.go:332] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0205 12:29:13.082710    5348 checks.go:332] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0205 12:29:13.082782    5348 checks.go:654] validating whether swap is enabled or not
I0205 12:29:13.082915    5348 checks.go:373] validating the presence of executable conntrack
I0205 12:29:13.082977    5348 checks.go:373] validating the presence of executable ip
I0205 12:29:13.083023    5348 checks.go:373] validating the presence of executable iptables
I0205 12:29:13.083084    5348 checks.go:373] validating the presence of executable mount
I0205 12:29:13.083150    5348 checks.go:373] validating the presence of executable nsenter
I0205 12:29:13.083197    5348 checks.go:373] validating the presence of executable ebtables
I0205 12:29:13.083261    5348 checks.go:373] validating the presence of executable ethtool
I0205 12:29:13.083302    5348 checks.go:373] validating the presence of executable socat
I0205 12:29:13.083365    5348 checks.go:373] validating the presence of executable tc
I0205 12:29:13.083426    5348 checks.go:373] validating the presence of executable touch
I0205 12:29:13.083479    5348 checks.go:521] running all checks
	[WARNING SystemVerification]: missing optional cgroups: hugetlb
I0205 12:29:13.454754    5348 checks.go:404] checking whether the given node name is valid and reachable using net.LookupHost
I0205 12:29:13.455092    5348 checks.go:620] validating kubelet version
I0205 12:29:13.618949    5348 checks.go:133] validating if the "kubelet" service is enabled and active
I0205 12:29:13.655717    5348 checks.go:206] validating availability of port 10250
I0205 12:29:13.656456    5348 checks.go:206] validating availability of port 2379
I0205 12:29:13.656897    5348 checks.go:206] validating availability of port 2380
I0205 12:29:13.657276    5348 checks.go:246] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0205 12:29:13.658428    5348 checks.go:842] using image pull policy: IfNotPresent
I0205 12:29:13.787494    5348 checks.go:851] image exists: k8s.gcr.io/kube-apiserver:v1.23.3
I0205 12:29:13.883012    5348 checks.go:851] image exists: k8s.gcr.io/kube-controller-manager:v1.23.3
I0205 12:29:13.978154    5348 checks.go:851] image exists: k8s.gcr.io/kube-scheduler:v1.23.3
I0205 12:29:14.074905    5348 checks.go:851] image exists: k8s.gcr.io/kube-proxy:v1.23.3
I0205 12:29:14.170695    5348 checks.go:851] image exists: k8s.gcr.io/pause:3.6
I0205 12:29:14.265811    5348 checks.go:851] image exists: k8s.gcr.io/etcd:3.5.1-0
I0205 12:29:14.362899    5348 checks.go:851] image exists: k8s.gcr.io/coredns/coredns:v1.8.6
[certs] Using certificateDir folder "/etc/kubernetes/pki"
I0205 12:29:14.363088    5348 certs.go:112] creating a new certificate authority for ca
[certs] Generating "ca" certificate and key
I0205 12:29:19.556182    5348 certs.go:522] validating certificate period for ca certificate
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local pi-kube-master] and IPs [10.18.0.1 192.168.1.53]
[certs] Generating "apiserver-kubelet-client" certificate and key
I0205 12:29:24.104724    5348 certs.go:112] creating a new certificate authority for front-proxy-ca
[certs] Generating "front-proxy-ca" certificate and key
I0205 12:29:25.515262    5348 certs.go:522] validating certificate period for front-proxy-ca certificate
[certs] Generating "front-proxy-client" certificate and key
I0205 12:29:26.622064    5348 certs.go:112] creating a new certificate authority for etcd-ca
[certs] Generating "etcd/ca" certificate and key
I0205 12:29:30.872866    5348 certs.go:522] validating certificate period for etcd/ca certificate
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost pi-kube-master] and IPs [192.168.1.53 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost pi-kube-master] and IPs [192.168.1.53 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
I0205 12:29:38.687505    5348 certs.go:78] creating new public/private key files for signing service account users
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
I0205 12:29:41.708221    5348 kubeconfig.go:103] creating kubeconfig file for admin.conf
[kubeconfig] Writing "admin.conf" kubeconfig file
I0205 12:29:45.072701    5348 kubeconfig.go:103] creating kubeconfig file for kubelet.conf
[kubeconfig] Writing "kubelet.conf" kubeconfig file
I0205 12:29:47.449937    5348 kubeconfig.go:103] creating kubeconfig file for controller-manager.conf
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
I0205 12:29:48.742340    5348 kubeconfig.go:103] creating kubeconfig file for scheduler.conf
[kubeconfig] Writing "scheduler.conf" kubeconfig file
I0205 12:29:52.189689    5348 kubelet.go:65] Stopping the kubelet
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
I0205 12:29:52.909343    5348 manifests.go:99] [control-plane] getting StaticPodSpecs
I0205 12:29:52.910078    5348 certs.go:522] validating certificate period for CA certificate
I0205 12:29:52.910398    5348 manifests.go:125] [control-plane] adding volume "ca-certs" for component "kube-apiserver"
I0205 12:29:52.910443    5348 manifests.go:125] [control-plane] adding volume "etc-ca-certificates" for component "kube-apiserver"
I0205 12:29:52.910469    5348 manifests.go:125] [control-plane] adding volume "k8s-certs" for component "kube-apiserver"
I0205 12:29:52.910493    5348 manifests.go:125] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-apiserver"
I0205 12:29:52.910520    5348 manifests.go:125] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-apiserver"
I0205 12:29:52.921883    5348 manifests.go:154] [control-plane] wrote static Pod manifest for component "kube-apiserver" to "/etc/kubernetes/manifests/kube-apiserver.yaml"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
I0205 12:29:52.921964    5348 manifests.go:99] [control-plane] getting StaticPodSpecs
I0205 12:29:52.922801    5348 manifests.go:125] [control-plane] adding volume "ca-certs" for component "kube-controller-manager"
I0205 12:29:52.922849    5348 manifests.go:125] [control-plane] adding volume "etc-ca-certificates" for component "kube-controller-manager"
I0205 12:29:52.922877    5348 manifests.go:125] [control-plane] adding volume "flexvolume-dir" for component "kube-controller-manager"
I0205 12:29:52.922902    5348 manifests.go:125] [control-plane] adding volume "k8s-certs" for component "kube-controller-manager"
I0205 12:29:52.922932    5348 manifests.go:125] [control-plane] adding volume "kubeconfig" for component "kube-controller-manager"
I0205 12:29:52.922962    5348 manifests.go:125] [control-plane] adding volume "usr-local-share-ca-certificates" for component "kube-controller-manager"
I0205 12:29:52.922994    5348 manifests.go:125] [control-plane] adding volume "usr-share-ca-certificates" for component "kube-controller-manager"
I0205 12:29:52.925926    5348 manifests.go:154] [control-plane] wrote static Pod manifest for component "kube-controller-manager" to "/etc/kubernetes/manifests/kube-controller-manager.yaml"
[control-plane] Creating static Pod manifest for "kube-scheduler"
I0205 12:29:52.926009    5348 manifests.go:99] [control-plane] getting StaticPodSpecs
I0205 12:29:52.926842    5348 manifests.go:125] [control-plane] adding volume "kubeconfig" for component "kube-scheduler"
I0205 12:29:52.928552    5348 manifests.go:154] [control-plane] wrote static Pod manifest for component "kube-scheduler" to "/etc/kubernetes/manifests/kube-scheduler.yaml"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I0205 12:29:52.930582    5348 local.go:65] [etcd] wrote Static Pod manifest for a local etcd member to "/etc/kubernetes/manifests/etcd.yaml"
I0205 12:29:52.930638    5348 waitcontrolplane.go:91] [wait-control-plane] Waiting for the API server to be healthy
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

couldn't initialize a Kubernetes cluster
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init.runWaitControlPlanePhase
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go:118
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_arm.s:838
error execution phase wait-control-plane
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/init.go:153
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go/src/runtime/asm_arm.s:838
`

journal -xeu kubelet give me the following,

`
kubelet[6145]: Flag --network-plugin has been deprecated, will be removed along with dockershim.

kubelet[6145]: Flag --network-plugin has been deprecated, will be removed along with dockershim.

kubelet[6145]: I0205 12:30:42.432739    6145 server.go:446] "Kubelet version" kubeletVersion="v1.23.3"

kubelet[6145]: I0205 12:30:42.434017    6145 server.go:874] "Client rotation is on, will bootstrap in background"

kubelet[6145]: I0205 12:30:42.439452    6145 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".

kubelet[6145]: I0205 12:30:42.442739    6145 dynamic_cafile_content.go:156] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"

kubelet[6145]: W0205 12:30:42.442919    6145 manager.go:159] Cannot detect current cgroup on cgroup v2

kubelet[6145]: W0205 12:30:42.661741    6145 sysinfo.go:203] Nodes topology is not available, providing CPU topology

kubelet[6145]: W0205 12:30:42.663764    6145 machine.go:65] Cannot read vendor id correctly, set empty.

kubelet[6145]: I0205 12:30:42.666660    6145 server.go:693] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"

kubelet[6145]: I0205 12:30:42.667641    6145 container_manager_linux.go:281] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]

kubelet[6145]: I0205 12:30:42.667940    6145 container_manager_linux.go:286] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroups>

kubelet[6145]: I0205 12:30:42.668146    6145 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"

kubelet[6145]: I0205 12:30:42.668188    6145 container_manager_linux.go:321] "Creating device plugin manager" devicePluginEnabled=true

kubelet[6145]: I0205 12:30:42.668256    6145 state_mem.go:36] "Initialized new in-memory state store"

kubelet[6145]: I0205 12:30:42.668448    6145 kubelet.go:313] "Using dockershim is deprecated, please consider using a full-fledged CRI implementation"

kubelet[6145]: I0205 12:30:42.668635    6145 client.go:80] "Connecting to docker on the dockerEndpoint" endpoint="unix:///var/run/docker.sock"

kubelet[6145]: I0205 12:30:42.668699    6145 client.go:99] "Start docker client with request timeout" timeout="2m0s"

kubelet[6145]: I0205 12:30:42.705426    6145 docker_service.go:571] "Hairpin mode is set but kubenet is not enabled, falling back to HairpinVeth" hairpinMode=promiscuous-bridge

kubelet[6145]: I0205 12:30:42.705510    6145 docker_service.go:243] "Hairpin mode is set" hairpinMode=hairpin-veth

kubelet[6145]: I0205 12:30:42.705832    6145 cni.go:240] "Unable to update cni config" err="no networks found in /etc/cni/net.d"

kubelet[6145]: I0205 12:30:42.712758    6145 cni.go:240] "Unable to update cni config" err="no networks found in /etc/cni/net.d"

kubelet[6145]: I0205 12:30:42.712950    6145 docker_service.go:258] "Docker cri networking managed by the network plugin" networkPluginName="cni"

kubelet[6145]: I0205 12:30:42.713256    6145 cni.go:240] "Unable to update cni config" err="no networks found in /etc/cni/net.d"

kubelet[6145]: I0205 12:30:42.750856    6145 docker_service.go:264] "Docker Info" dockerInfo=&{ID:GLFU:JW22:MA7Q:YPYL:UDSW:E4EC:G2M3:QSBM:G7YC:S2YF:YT6I:J34B Containers:0 Containe>

kubelet[6145]: I0205 12:30:42.750943    6145 docker_service.go:279] "Setting cgroupDriver" cgroupDriver="systemd"

kubelet[6145]: I0205 12:30:42.824353    6145 kubelet.go:416] "Attempting to sync node with API server"

kubelet[6145]: I0205 12:30:42.824406    6145 kubelet.go:278] "Adding static pod path" path="/etc/kubernetes/manifests"

kubelet[6145]: I0205 12:30:42.824521    6145 kubelet.go:289] "Adding apiserver pod source"

kubelet[6145]: I0205 12:30:42.824593    6145 apiserver.go:42] "Waiting for node sync before watching apiserver pods"

kubelet[6145]: W0205 12:30:42.827626    6145 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: Get "https://192.168.1.53:6443/api/v1/nodes?fiel>

kubelet[6145]: E0205 12:30:42.828345    6145 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://192.168.1>

kubelet[6145]: W0205 12:30:42.829064    6145 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: Get "https://192.168.1.53:6443/api/v1/service>

kubelet[6145]: E0205 12:30:42.829173    6145 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: Get "https://192>

kubelet[6145]: I0205 12:30:42.866086    6145 kuberuntime_manager.go:248] "Container runtime initialized" containerRuntime="docker" version="20.10.12" apiVersion="1.41.0"

kubelet[6145]: I0205 12:30:42.867183    6145 server.go:1231] "Started kubelet"

kubelet[6145]: I0205 12:30:42.867659    6145 server.go:150] "Starting to listen" address="0.0.0.0" port=10250

kubelet[6145]: E0205 12:30:42.869415    6145 kubelet.go:1351] "Image garbage collection failed once. Stats initialization may not have completed yet" err="failed to get imageFs in>

kubelet[6145]: E0205 12:30:42.869315    6145 event.go:276] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"pi-kube-m>

kubelet[6145]: I0205 12:30:42.869879    6145 server.go:410] "Adding debug handlers to kubelet server"

kubelet[6145]: I0205 12:30:42.871657    6145 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"

kubelet[6145]: I0205 12:30:42.873710    6145 volume_manager.go:291] "Starting Kubelet Volume Manager"

kubelet[6145]: I0205 12:30:42.875471    6145 desired_state_of_world_populator.go:147] "Desired state populator starts to run"

kubelet[6145]: E0205 12:30:42.880669    6145 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: Get "https://192.168.1.53:6443/apis/coordination.k8s.io/>

kubelet[6145]: W0205 12:30:42.887766    6145 reflector.go:324] k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: Get "https://192.168.1.53:6443/apis/storage>

kubelet[6145]: E0205 12:30:42.888790    6145 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get "https:/>

kubelet[6145]: E0205 12:30:42.934490    6145 kubelet.go:2347] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"

kubelet[6145]: E0205 12:30:42.974631    6145 kubelet.go:2422] "Error getting node" err="node \"pi-kube-master\" not found"

kubelet[6145]: I0205 12:30:42.980188    6145 kubelet_network_linux.go:57] "Initialized protocol iptables rules." protocol=IPv4

kubelet[6145]: I0205 12:30:43.046659    6145 kubelet_node_status.go:70] "Attempting to register node" node="pi-kube-master"

kubelet[6145]: E0205 12:30:43.048340    6145 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://192.168.1.53:6443/api/v1/nodes\": dial tcp 19>

kubelet[6145]: panic: unaligned 64-bit atomic operation

kubelet[6145]: goroutine 380 [running]:

kubelet[6145]: runtime/internal/atomic.panicUnaligned()

kubelet[6145]:         /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24

kubelet[6145]: runtime/internal/atomic.Load64(0x857016c)

kubelet[6145]:         /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:286 +0x14

kubelet[6145]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).updateStats(0x8570000)

kubelet[6145]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/container.go:676 +0x438

kubelet[6145]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).housekeepingTick(0x8570000, 0x8535500, 0x5f5e100)

kubelet[6145]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/container.go:587 +0x104

kubelet[6145]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).housekeeping(0x8570000)

kubelet[6145]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/container.go:535 +0x3bc

kubelet[6145]: created by k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).Start

kubelet[6145]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager/container.go:122 +0x2c

systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
`

### What did you expect to happen?

I expected to be able to initialize the cluster with kubeadm

### How can we reproduce it (as minimally and precisely as possible)?

Running on a pi 4 raspbian bullseye

added cgroup_enable=memory swapaccount=1 to /boot/cmdline.txt

sudo dphys-swapfile swapoff 
sudo dphys-swapfile uninstall
sudo apt purge dphys-swapfile -y

cat <<EOF | sudo tee /etc/modules-load.d/containerd.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# Setup required sysctl params, these persist across reboots.
cat <<EOF | sudo tee /etc/sysctl.d/99-kubernetes-cri.conf
net.bridge.bridge-nf-call-iptables  = 1
net.ipv4.ip_forward                 = 1
net.bridge.bridge-nf-call-ip6tables = 1
EOF

# Apply sysctl params without reboot
sudo sysctl --system

#install kubernetes
sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

$ uname -a
# paste output here
Linux pi-kube-master 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> Platform:"linux/arm"

> Linux pi-kube-master 5.10.92-v7l+ #1514 SMP Mon Jan 17 17:38:03 GMT 2022 armv7l GNU/Linux

> kubelet[6145]: k8s.io/kubernetes/vendor/github.com/google/cadvisor/manager.(*containerData).updateStats(0x8570000)

> kubelet[6145]: panic: unaligned 64-bit atomic operation

the go compiler should be able to do this automatic alignment of 64bit POD types, so potentially a bug there.

offending function:
https://github.com/kubernetes/kubernetes/blob/release-1.23/vendor/github.com/google/cadvisor/manager/container.go#L640

this could be due to some of the fields in:
https://github.com/kubernetes/kubernetes/blob/7c7f40d92fc044d46cbb6411d35dae6c39bd9478/vendor/github.com/google/cadvisor/manager/container.go#L66

manual alignment could solve this.

/sig node
/area kubelet cadvisor
/kind bug

(not adding sig CL, kubeadm, as i don't see reported problems)

**Comment by adisky** [comment]
/triage accepted 
This has been fixed in cadvisor  https://github.com/google/cadvisor/pull/3029
we need to bump cadvisor in k/k

cc @bobbypage @SergeyKanzhelev

**Comment by adisky** [comment]
related to https://github.com/kubernetes/kubernetes/issues/106977

**Comment by neolit123** [comment]
i think this one can be closed, given there is so much detail in https://github.com/kubernetes/kubernetes/issues/106977
