### ISSUE TITLE
Bug in node_status_updater.go - UpdateNodeStatuses

### ISSUE THREAD

**Issue by jfremy** [kubernetes/kubernetes#107973]
https://github.com/kubernetes/kubernetes/blob/9b09612d1b0a6ec441833f928cbb205d936da59c/pkg/controller/volume/attachdetach/statusupdater/node_status_updater.go#L92

UpdateNodeStatuses will exit immediately if updateNodeStatus returns an error.
It does mark the node for which the call failed for later update but all the following nodes in the update list are left unchanged and therefore won't be updated.

This can result for instance in a pod getting stuck waiting for its volume to be attached.
Assuming the attach of the volume to the pod's node succeeded but another node preceding this one in the update list has its updateNodeStatus call fail - then the attach detach controller will never update the node status to indicate the volume was attached and the pod will be stuck until there is another update for this node attachements.

The fix can be as simple as using a continue but the original code seems to want to abort the whole loop in the case of that error, so that would require marking all the remaining nodes for update, not just the current one.

**Comment by jingxu97** [comment]
thanks @jfremy for discovering the issue and @NikhilSharmaWe for helping fix it.
