### ISSUE TITLE
Log rotate for containerd runtime. Splits the log into parts

### ISSUE THREAD

**Issue by FaraSys** [kubernetes/kubernetes#107943]
### What happened?

My evn: Kubernetes 1.20.7 with runtime: containerd
My problem:
I have a lot of microservices running in kubernetes. To one microservice a large number of calls and logs are written in large numbers.
During the closing of the log and the creation of a new file to continue the logs, one of the logs is divided into parts. One part of the messages remains in the closed log, and the continuation in the new one.
Kubelet-config.yaml contains these parameters:
cgroupDriver: systemd
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
Logfiles examplex in attach
[0 (new log).log](https://github.com/kubernetes/kubernetes/files/8000734/0.new.log.log)
[0.log.20220204-084527(closed log)](https://github.com/kubernetes/kubernetes/files/8000735/0.log.20220204-084527.closed.log)

### What did you expect to happen?

When closing the log file, the kublet will negotiate and not make a message in the log file into parts

### How can we reproduce it (as minimally and precisely as possible)?

I cant say, how it reproduce, because it happend when microservice write a lot of logs

### Kubernetes version

<details>
$ kubectl version
root@kub-node-04:~# kubelet --version
Kubernetes v1.20.7
</details>

### Cloud provider

<details>
vmware
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux kub-node-04.contoso.com 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and and version (if applicable)

<details>
root@kub-node-01:~# crictl --version
crictl version v1.20.0
root@kub-node-01:~# containerd --version
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel
</details>

**Comment by tossmilestone** [comment]
@FaraSys Do you means some of your logs are missing?

**Comment by FaraSys** [comment]
> @FaraSys The one line of the log is splitted into 2 lines, seems a bug when kubelet rotating the logs.

@tossmilestone Quite right. I also think it's a bug

**Comment by tossmilestone** [comment]
@FaraSys It should be a designed behavior, see https://github.com/kubernetes/community/commit/ee2abbf9dbfa4523b414f99a04ddc97bd38c74b2?short_path=800a0ac#diff-800a0acf0cc17ebe3bdccb4c2522424749974495d6f589c5130268b4b930cb6f

The `P` means a part of the log line.

**Comment by FaraSys** [comment]
@tossmilestone What does RUNTIME mean in this text? ContainerD or Docker? 
"Partial (P) is used when a log entry is split into multiple lines by the **runtime**"

**Comment by tossmilestone** [comment]
> @tossmilestone What does RUNTIME mean in this text? ContainerD or Docker?
> "Partial (P) is used when a log entry is split into multiple lines by the **runtime**

the runtime could be ContainerD or Docker, kubelet parse the log from the runtime and store it as the CRI log format

**Comment by tossmilestone** [comment]
> @tossmilestone What does RUNTIME mean in this text? ContainerD, Docker or my microservice?
> "Partial (P) is used when a log entry is split into multiple lines by the **runtime**"

The `runtime` means the CRI runtime, in you case, it should be containerd.

**Comment by ehashman** [comment]
/remove-sig instrumentation
/sig node

It appears this is working as expected. The partial log line entry is prefixed with P, and the remaining half of the log line is prefixed with F, per the doc linked above.

/close
