### ISSUE TITLE
Updating the test framework to ginkgo 2.0

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#107936]
### What would you like to be added?

Updating the test framework to ginkgo 2.0 will eventually happen I'm sure and I just wanted to have some notes related to this that people can reference.

### Why is this needed?

Just tracking issues that would be related to any updating of ginkgo from 1.0 to 2.0.
- [ ] Custom reporters deprecated https://onsi.github.io/ginkgo/MIGRATING_TO_V2#removed-custom-reporters
  - [ ] The junit reporter will easily be ported (they have a flag for that)
  - [ ] The progress reporter which makes real-time updates easier will take a little more work but should be fine. I'm happy to take this work when it is needed.

**Comment by aojea** [comment]
For the ones interested, ginkgov2 was already tested against Kubernetes and works, it does requires some changes though

https://github.com/kubernetes/kubernetes/pull/105147

Most of the work required is to adapt the reporters

**Comment by chendave** [comment]
This will be addressed in this pr: https://github.com/kubernetes/kubernetes/pull/109111

A separated will dedicatedly address the reporter migration.
