### ISSUE TITLE
swagger-ui is uselessly slow, ...

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#10797]
...horribly ugly, and practically indecipherable.  Is it actually useful to anyone at all?  we should find or make something better.

**Comment by lavalamp** [comment]
I've only used it a couple times. It's slow to load, but after it loads it
works fine on my system. It was useful for whatever I was doing, which I
can't recall.

**Comment by erictune** [comment]
It seems better than nothing.

**Comment by nikhiljindal** [comment]
Filed https://github.com/swagger-api/swagger-ui/issues/1455 to discuss the slowness with swagger-ui team.

**Comment by bgrant0607** [comment]
We have generated docs and the swagger UI has other problems. We should consider deleting it.

**Comment by bgrant0607** [comment]
#15915 filed to delete the swagger UI
