### ISSUE TITLE
Some pod to pod connection fails on EKS

### ISSUE THREAD

**Issue by avarf** [kubernetes/kubernetes#107985]
### What happened?

We have a cluster on EKS and from 2 days ago we noticed some network issues in our cluster. Imagine a scenario in which we have 2 workers nodes (w1 and w2) and 3 pods with their own services (A, B and C). Pods A and B are located on w1 and pod C are located on w2.

The problem is A cannot reach C but B can. When I go inside pod A and try `curl -vvv http://C/` the DNS resolves to the IP of the service of the C but after that it hangs and after some time I get a timeout. The strange thing is restarting/deleting pod A didn't solve the issue but when I deleted C it solved the issue.

I have never seen something like this and I checked the logs of the kube-proxy of the worker nodes but I didn't see an error or anything strange.

### What did you expect to happen?

All the pods be reachable and if there is an error we can see it in the logs.

### How can we reproduce it (as minimally and precisely as possible)?

Since I don't know what caused the issue I cannot say how to reproduce it.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-8c49e2", GitCommit:"8c49e2efc3cfbb7788a58025e679787daed22018", GitTreeState:"clean", BuildDate:"2021-10-17T05:13:46Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> We have a cluster on EKS and from 2 days ago we noticed some network issues in our cluster

hello, EKS is a managed k8s solution that may or may not deploy a custom version of k8s components.
please contact EKS support first. if they confirm this is a core k8s bug you can re-open this issue and include their feedback.
thanks

/area provider/aws
/sig cloud-provider
/close
