### ISSUE TITLE
namespace-controller fails to delete namespace if there are too many objects of a given type

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#107948]
### What happened?

I tried to remove namespace in a cluster with 70k CRD objects. The namespace-controller was triggering DELETECOLLECTION call which was failing to make any progress on deletion due to List (part of DeleteCollection) taking more than 34s of timeout hardcoded in the kube-apiserver's code. It was retrying every 1m, but each call was failing with timeout, without deleting a single object.

### What did you expect to happen?

That the large number of objects in a single namespace will make the operation slower, but it will succeed eventually.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a namespace
2. create ~70k objects there (preferably some large CRD objects, which deserialization is slower than core resource types)
3. try to delete namespace

### Anything else we need to know?

Proposed fix:
* in [(*namespacedResourcesDeleter).deleteCollection](In https://github.com/kubernetes/kubernetes/blob/76cdb57ccfbfebc689fbce45f289add8a0562e07/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L306:38) we can introduce pagination (either by using pagination library or simply calling DELETE with limit=X sequentially until we get no continuation token).

### Kubernetes version

Tested on 1.21, but the master code looks the same in this area: https://github.com/kubernetes/kubernetes/blob/76cdb57ccfbfebc689fbce45f289add8a0562e07/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L306:38

### Cloud provider

All

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mborsz** [comment]
/cc @wojtek-t 

Is the fix mentioned in "Anything else we need to know?" a proper fix?

**Comment by wojtek-t** [comment]
Seems like  duplicate of: https://github.com/kubernetes/kubernetes/issues/90743

I suggest closing this one and following on the original one.
