### ISSUE TITLE
Exclusive CPU used by init container returns to defaultCPUSet pool causing kubelet go into reboot loop

### ISSUE THREAD

**Issue by 2-face** [kubernetes/kubernetes#107906]
### What happened?

When init container does its job it's removed and CPU assigned to it via cpuset returns to the defaultCPUSet pool even though this CPU is in cpuset used by another container.  Because of that kubelet seeing drift between **defaultCPUSet** and **exclusive CPUs** assigned to running containers fails to start.

### What did you expect to happen?

* CPU used by init container should return to defaultCPUSet only if it's not used by other containers in a pod. 
* Alternatively reconciltion loop should update back state file (_/var/lib/kubelet/cpu_manager_state_) to match actual state. * Last but not least kubelet could be the one performing reconciliation if the loop failed to do that and continue to boot instead of going into reboot loop.

Current behaviour is in line with **RemoveContainer** function (but maybe not with reconciliation loop if one exist)
https://github.com/kubernetes/kubernetes/blob/release-1.18/pkg/kubelet/cm/cpumanager/policy_static.go

### How can we reproduce it (as minimally and precisely as possible)?

* use static policy
* define a pod with init container and request=limits (so that we use Guaranteed QoSClass and exclusive CPUs)
* after pod is spawned verify in logs CPU allocation and compare it against the state file (_/var/lib/kubelet/cpu_manager_state_) - during init container work and after its work is done

### Anything else we need to know?

Default CPU upon pod spawn was **"0-2,6-15"** but changed during removal of **init** container to **"0-3,6-15"**

```
state_mem.go:36] [cpumanager] initializing new in-memory state store
state_mem.go:88] [cpumanager] updated default cpuset: "0-3,6-15"
state_mem.go:96] [cpumanager] updated cpuset assignments: "map[:map[<redacted>init:3 worker:3-5]]"
policy_static.go:122] [cpumanager] static policy invalid state: pod: <redacted>, container: container cpuset: "3-5" overlaps with default cpuset "0-3,6-15", please drain node and remove policy state file
cpu_manager.go:201] [cpumanager] policy start error: pod: <redacted>, container: worker cpuset: "3-5" overlaps with default cpuset "0-3,6-15"
kubelet.go:1383] Failed to start ContainerManager start cpu manager error: pod: <redacted>, container: worker cpuset: "3-5" overlaps with default cpuset "0-3,6-15"
```

### Kubernetes version

1.18.3

### Cloud provider

vanilla, on-prem setup

### OS version

RHEL 8.4

### Install tools

kubeadm

### Container runtime (CRI) and and version (if applicable)

docker

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico

**Comment by SergeyKanzhelev** [comment]
@2-face you are using old kubernetes version that is not supported. Please try to reproduce the issue on a new version of Kubernetes.

/triage needs-information

/assign @cynepco3hahue

**Comment by 2-face** [comment]
@SergeyKanzhelev on 1.18 - the issue happens sometimes, on 1.21 I haven't seen the problem however I would like to confirm if this has been fixed (even indirectly).

**Comment by SergeyKanzhelev** [comment]
during triage @cynepco3hahue and @rphillips mentioned they vaguely remember this being fixed. Since it doesn't repro on 1.21, I'm going to close the issue. Feel free to reopen if more evidence is found that issue still persists.

/close

**Comment by 2-face** [comment]
@SergeyKanzhelev thanks!
