### ISSUE TITLE
After upgrading to 1.22.6, controller manager unhealthy

### ISSUE THREAD

**Issue by zhuyouzhufu** [kubernetes/kubernetes#107929]
### What happened?

![image](https://user-images.githubusercontent.com/34908518/152342651-4198d18e-81db-46e8-ade1-3826f7d5ad7c.png)

Here is my controller management profile information
cat > /opt/kubernetes/server/conf/kube-controller-manager.conf << EOF
KUBE_CONTROLLER_MANAGER_OPTS="--logtostderr=false \\
--alsologtostderr=true \\
--v=2 \\
--log-dir=/opt/kubernetes/server/logs \\
--leader-elect=true \\
--bind-address=192.168.100.107 \\
--secure-port=10257 \\
--master=https://192.168.100.99:6443 \\
--kubeconfig=/opt/kubernetes/server/conf/kube-controller-manager.kubeconfig \\
--allocate-node-cidrs=true \\
--cluster-cidr=10.0.0.0/16 \\
--service-cluster-ip-range=10.255.0.0/16 \\
--cluster-signing-cert-file=/opt/kubernetes/server/ssl/ca.pem \\
--cluster-signing-key-file=/opt/kubernetes/server/ssl/ca-key.pem \\
--root-ca-file=/opt/kubernetes/server/ssl/ca.pem \\
--service-account-private-key-file=/opt/kubernetes/server/ssl/ca-key.pem \\
--feature-gates=RotateKubeletServerCertificate=true \\
--controllers=*,bootstrapsigner,tokencleaner \\
--tls-cert-file=/opt/kubernetes/server/ssl/kube-controller-manager.pem \\
--tls-private-key-file=/opt/kubernetes/server/ssl/kube-controller-manager-key.pem \\
--use-service-account-credentials=true"
EOF

I really can't figure out why he kept going 127.0.0.1 to request after I specified the IP address
Through the following documents, I don't see that he has a relevant IP address to set the IP of this request
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/

Kubernetes version：1.22.6
operating system：CentOS 7.9

### What did you expect to happen?

1

### How can we reproduce it (as minimally and precisely as possible)?

1

### Kubernetes version

1.22.6

### Cloud provider

<details>

</details>

### OS version

CentOS 7.9

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by zhuyouzhufu** [comment]
![image](https://user-images.githubusercontent.com/34908518/152344083-10f4e5f5-4e9f-4115-916c-06a0618acf4f.png)
![image](https://user-images.githubusercontent.com/34908518/152344116-ecc8f5df-0d83-4259-ae09-c548188a95d5.png)

**Comment by khenidak** [comment]
Hi, can you please share controller manager logs?

**Comment by liggitt** [comment]
> I really can't figure out why he kept going 127.0.0.1 to request after I specified the IP address

componentstatus only checks controller-manager and scheduler health on 127.0.0.1: https://github.com/kubernetes/kubernetes/blob/7efc928dfa3ad88b5efa880eca5abe1be6550fd0/pkg/registry/core/rest/storage_core.go#L349

This only works when controller-manager and scheduler run local to the apiserver and bind their healthz ports to 127.0.0.1. This limited topology support and fragile assumption about the control plane configuration is why the component status API is deprecated (as indicated in the warning returned along with the `kubectl get componentstatus` response).

/close

**Comment by zhuyouzhufu** [comment]
This is his service startup log
![image](https://user-images.githubusercontent.com/34908518/153900461-e175abf3-a7e5-4e48-904f-23bed7bad26f.png)
