### ISSUE TITLE
kube-proxy tracelog shows iptable save command output

### ISSUE THREAD

**Issue by etavene** [kubernetes/kubernetes#107951]
### What happened?

In kube-proxy's  trace log I could see  iptables save command which took 3+ mins to execute. Would like to know why and when kube-proxy does iptables save call and does it have any impact on  k8's etcd ?  kube-proxy running in ipvs mode 

I1217 12:04:07.406781       1 node.go:135] Successfully retrieved node IP:
  2 I1217 12:04:07.406906       1 server_others.go:176] Using ipvs Proxier.
  3 I1217 12:04:07.409228       1 server.go:529] Version: v1.16.3
  4 I1217 12:04:07.410474       1 conntrack.go:52] Setting nf_conntrack_max to 262144
  5 I1217 12:04:07.410865       1 config.go:131] Starting endpoints config controller
  6 I1217 12:04:07.411097       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
  7 I1217 12:04:07.411376       1 config.go:313] Starting service config controller
  8 I1217 12:04:07.411509       1 shared_informer.go:197] Waiting for caches to sync for service config
  9 I1217 12:04:07.511387       1 shared_informer.go:204] Caches are synced for endpoints config
 10 I1217 12:04:07.511842       1 shared_informer.go:204] Caches are synced for service config
 **11 I1217 12:23:15.284133       1 trace.go:116] Trace[398622322]: "**iptables save" (started: 2021-12-17 12:19:58.8643    91634 +0000 UTC m=+951.611950073) (total time: 3m11.423911591s):**
 12 Trace[398622322]: [3m11.423911591s] [3m11.423911591s] END
 13 I1217 12:23:42.513722       1 trace.go:116] Trace[2048151206]: "iptables save" (started: 2021-12-17 12:23:17.119    746283 +0000 UTC m=+1149.867304727) (total time: 24.209972462s):**
 14 Trace[2048151206]: [24.209972462s] [24.209972462s] END
 15 W1217 12:23:47.945053       1 reflector.go:299] k8s.io/client-go/informers/factory.go:134: watch of *v1.Service     ended with: too old resource version: 1755 (2754)

### What did you expect to happen?

it is taking too long time to execute iptables-save command. At the same time k8's etcd is exhibiting timeout errors. Just want to know is there any relevance here. 

2021-12-17 12:19:46.426253 W | etcdserver: failed to revoke 03757dc8439dd771 ("etcdserver: request timed out")

### How can we reproduce it (as minimally and precisely as possible)?

issue is intermittent, only happening couple of times. 

### Kubernetes version

<details>

```console
$ kubectl version

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:49Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a

Linux localhost 4.19.81-OpenNetworkLinux #1 SMP Wed Dec 22 07:37:14 UTC 2021 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
are that kube-proxy and etcd running on the same host?

**Comment by etavene** [comment]
Yes, it is a single node deployment.

**Comment by aojea** [comment]
your node is under pressure and that causes that everything fails

**Comment by aojea** [comment]
/close
/remove sig-network
/kind support

The node is not in good health, etcd fails and it cascades that to the rest of the cluster

> 2021-12-17 12:19:46.426253 W | etcdserver: failed to revoke 03757dc8439dd771 ("etcdserver: request timed out")

> > 15 W1217 12:23:47.945053 1 reflector.go:299] k8s.io/client-go/informers/factory.go:134: watch of *v1.Service ended with: too old resource version: 1755 (2754)

> 11 I1217 12:23:15.284133 1 trace.go:116] Trace[398622322]: "iptables save" (started: 2021-12-17 12:19:58.8643 91634 +0000 UTC m=+951.611950073) (total time: 3m11.423911591s):

since etcd is very io intensive, is probably the disks are saturated too
