### ISSUE TITLE
kubelet deadlock with many parallel mounts

### ISSUE THREAD

**Issue by xhejtman** [kubernetes/kubernetes#108009]
### What happened?

We have kubernetes 1.20.8/9 with rke2. If we spawn like 100 new pods each mounting only a single pvc like this:
```
volumeMounts:
    - mountPath: /mnt
      name: vol-3689
```
which is NFS provisioned volume (a single volume on host and mount --bind attached to the pods).
We got whole node stuck in container creating as the mount is not possible with the error:
```
E0208 15:56:39.797423    3771 pod_workers.go:190] "Error syncing pod, skipping" err="unmounted volumes=[vol-3689], unattached volumes=[vol-3689]: timed out waiting for the condition" po
d="acgt-ns/nf-8e456597c72f1450bfe4e8dd7dce0595" podUID=8588a78f-fea7-4552-9458-8ad8264d69bd
```

It seems that even any other volume cannot be mounted.

All is fixed just by restarting `kubelet` but if we continue to spawn pods in parallel, it gets stuck again. Restart fixes it again. The kubelet is not stuck in any other way, just it is unable to mount any other PVC.

We use democratic-csi driver (https://github.com/democratic-csi/democratic-csi).

I recorded goroutine with the command:
```
kubectl get --insecure-skip-tls-verify=true --server="https://10.16.62.21:10250" --raw='/debug/pprof/goroutine' > goroutine.log
```
and it is attached. I have whole kubelet logs before it stuck if needed (but it is 50MB file).
[goroutine.log](https://github.com/kubernetes/kubernetes/files/8025281/goroutine.log)

### What did you expect to happen?

Kubelet should continue to mount PVCs.

### How can we reproduce it (as minimally and precisely as possible)?

Spawn many (100+) pods in parallel required to mount a PVC.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9+rke2r1", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T21:17:19Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
baremetal on premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here
Linux kub-a5.priv.cerit-sc.cz 5.11.0-38-generic #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
rke2
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ehashman** [comment]
This does not appear to be a kubelet issue but rather a performance issue with your NFS mounts. Have you tested to see if this works for a different kind of mount (e.g. configmap or tmpfs)?

/sig storage
/triage needs-information

**Comment by xhejtman** [comment]
Why it does not mount eventually? The result is, there are like 10 pending pods waiting for mount which never happens until kubelet restart.

I agree this can be caused by slow bind mount of NFS. But why it does not recover once load is gone?

**Comment by SergeyKanzhelev** [comment]
@xhejtman can you please share the full kubelet log? We need more information to understand if the issue is in kubelet

**Comment by ehashman** [comment]
Thanks for attaching the log. This isn't the full kubelet log, it doesn't start from when the kubelet starts up. Can you please include the full log? You may also want to include the logs from after the kubelet is restarted so we can see what changes when it restarts.

From what I can see, looking at errors like

```
E0206 22:23:09.502644   37952 kubelet_volumes.go:225] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"052a4403-4fc4-4f66-b9b7-bcd6caec9ca5\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=103
```

it appears that there may be a node-level issue with the mounts, but we would need more information about the volumes being mounted and the system itself to debug.

**Comment by rphillips** [comment]
The kubelet pod lifecycle was refactored in Kubernetes 1.22. I recommend trying out Kubernetes 1.23. Prior versions had some race conditions with mount points.

**Comment by xhejtman** [comment]
> Thanks for attaching the log. This isn't the full kubelet log, it doesn't start from when the kubelet starts up. Can you please include the full log? You may also want to include the logs from after the kubelet is restarted so we can see what changes when it restarts.
> 
> From what I can see, looking at errors like
> 
> ```
> E0206 22:23:09.502644   37952 kubelet_volumes.go:225] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"052a4403-4fc4-4f66-b9b7-bcd6caec9ca5\" found, but error not a directory occurred when trying to remove the volumes dir" numErrs=103
> ```
> 
> it appears that there may be a node-level issue with the mounts, but we would need more information about the volumes being mounted and the system itself to debug.

Unfortunetelly, the log is rotated/recycled, so it is not available, but I try to reproduce it with artificial pods. Btw, it seems that under heavy paralellel requests, kubelet strongly dislikes if mount fails or perhaps even timeouts. (if like 50 pods is spawned at once, it can happen that some mount takes more time and do temporary timeout).

However, as @rphillips suggests, I also try newer version and if it will not be reproducible, it is fixed. It would be nice, if fix could be backported, but I understand that refactoring is not a small change that could be backported.

**Comment by xhejtman** [comment]
And a new kubelet log that contains kubelet start, lock, kubelet restart and continuing.
[kubelet.log.gz](https://github.com/kubernetes/kubernetes/files/8224841/kubelet.log.gz)

**Comment by xhejtman** [comment]
I tested 1.23.4 and unfortunatelly, the bug is still there.
```
  Normal   Scheduled    27m                  default-scheduler  Successfully assigned test-ns/nf-95c921ce318b75aec97eb415d6977d60 to kub-a21.priv.cerit-sc.cz
  Warning  FailedMount  3m12s (x2 over 21m)  kubelet            Unable to attach or mount volumes: unmounted volumes=[vol-774], unattached volumes=[kube-api-access-z4rmk vol-774]: timed out waiting for the condition
  Warning  FailedMount  57s (x10 over 25m)   kubelet            Unable to attach or mount volumes: unmounted volumes=[vol-774], unattached volumes=[vol-774 kube-api-access-z4rmk]: timed out waiting for the condition
```

**Comment by Dingshujie** [comment]
may be same problem with #109047, and may be leak umount operation in nestedpendingoperations queues.
do you have a lot of pods with same pvc that execute in one nodes?

**Comment by xhejtman** [comment]
> may be same problem with #109047, and may be leak operation in nestedpendingoperations queues. do you have a lot of pods with same pvc that execute in one nodes?

yes, it is exactly this case, lot of pods using the same pvc (like 100-400, and about 40 at one node)

**Comment by xhejtman** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/110951
