### ISSUE TITLE
Deprecate cgroups v1 and enable cgroups v2 by default

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#108028]
Pieces are ready in containerd, runc etc. Folks like Docker Desktop that depend on the containerd/runc etc have already switched. Some OS images now default to cgroups v2 as well. 

Can we please start down the path to enable cgroups v2 as the default across all the stuff we do? (kubeadm/image-builder/kubelet etc).

thanks!

**Comment by dims** [comment]
/sig node

cc @adisky @endocrimes

**Comment by neolit123** [comment]
> Can we please start down the path to enable cgroups v2 as the default across all the stuff we do? (kubeadm/image-builder/kubelet etc).

the underlying Linux cgroup Vx choice is transparent to kubeadm.

it performs validation for v1 vs v2 (dependent on statfs / CGROUP2_SUPER_MAGIC) using the k/system-validators repository:
https://github.com/kubernetes/system-validators/blob/master/validators/types_unix.go
https://github.com/kubernetes/system-validators/blob/master/validators/cgroup_validator_linux.go#L62

we could remove the v1 checks once v1 is completely unsupported everywhere, but that would need a MAJOR bump for the library...so we might as well just leave it there.

> Pieces are ready in containerd, runc etc. Folks like Docker Desktop that depend on the containerd/runc etc have already switched. Some OS images now default to cgroups v2 as well.

i have not been following the v1 deprecation state lower in the stack, but this seems worthy of a survey with questions - such as
"can you migrate to v2; if not why?"

**Comment by derekwaynecarr** [comment]
I agree with @neolit123 .

I also think its expected that we maintain v1 compatibility for o(years) based on set of popular community leveraged operating systems, and monitoring tools.  It is far more workload specific than our migration with CRI choice which is more transparent.  

This was the expectation when we first started to pursue v2 support.

Any new features in the resource model that we can only support on v2, we need to handle appropriately.  To date, that is just memory qos.

/cc @mrunalp

**Comment by mrunalp** [comment]
There are still gaps and kernel feature differences where customers are relying on v1 and v2 doesn't have a clear replacement yet. I agree with Derek that we will have to support v1 for a while. 

I am a :+1: on more v2 usage and feedback for sure so we can identify and address issues and move it towards GA.

One item on my list for 1.24 is to write a blog with @bobbypage on current status of cgroups v2 and how to use it to help us get more feedback.

Also, I think the next ubuntu LTS will be the first one to be on cgroups v2 which will help as well.

**Comment by sftim** [comment]
Are we happy with the warnings / diagnostics we emit when selecting cgroups v1?

**Comment by sftim** [comment]
Also, +1 to blog article.

**Comment by dims** [comment]
fyi  [Five Things to Prepare for Cgroup v2 with Kubernetes](https://blog.kintone.io/entry/2022/03/08/170206) from @yokaze

**Comment by dims** [comment]
Folks, what we can do in 1.25 to help with this transition?

**Comment by endocrimes** [comment]
As a somewhat baseline from a maintenance and support perspective:
- make sure there are -cgroupsv2 versions of every Kubelet CI+PR job
- make sure cgroupsv1 jobs are labelled as cgroupsv1
- transition to -cgroupsv2 jobs being the ones ran by default in PRs

**Comment by brunoborges** [comment]
I believe Docker Desktop with WSL2 still uses cgroups v1 because systemd is not a thing _yet_ on WSL2.

**Comment by BenTheElder** [comment]
It's also true in rancher desktop and colima where alpine is used which ships openrc, besides WSL2 which currently requires a custom init.

We're painfully aware of this in KIND, cgroupns + cgroup v2 everywhere would be great but I don't think it will happen anytime soon.

Even if they're not a primary use case, those cover a lot of developers iterating locally with KIND or otherwise. Docker Desktop on WSL2, Colima, and   Rancher Desktop all also support running Kubernetes directly and have one of these other units. For Mac and Windows this pretty much only leaves docker desktop on Mac as a prominent cgroupv2-ready option.

**Comment by BenTheElder** [comment]
https://github.com/systemd/systemd/pull/24086 / https://lists.freedesktop.org/archives/systemd-devel/2022-July/048115.html via https://github.com/containerd/containerd/issues/7319 (all worth noting for folks in this thread)

**Comment by akhilerm** [comment]
systemd support on wsl was [announced](https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/) recently, so the docker desktop with wsl may also have started migration

**Comment by bsdnet** [comment]
Curious that whether Kubernetes has a plan to enable cgroups v2 by default?

**Comment by bobbypage** [comment]
> Curious that whether Kubernetes has a plan to enable cgroups v2 by default?

Kubernetes does not have a default "cgroup mode", rather the kubelet will whatever the cgroup mode that is configured on the underlying node. Is this what you're referring or am I misunderstanding?

**Comment by BenTheElder** [comment]
The original issue title referenced enabling by default and the original issue body refers to projects beyond kubelet like image-builder, though the issue is only tagged as SIG Node.

@dims can you clarify the current intent or should we re-scope this?

**Comment by dims** [comment]
@bobbypage @BenTheElder we can close this now. image-builder folks can enable cgroups v2 on their images. yes, kubelet is able to detect what's below and adjust accordingly, so that's about what we can do here in our repo.

Taking stock, If you look at https://github.com/awslabs/amazon-eks-ami/pull/1340, we have
- AL2 images that use cgroup v1
- Ubuntu latest images that use cgroups v2
- AL2023 that use cgroups v2 (https://github.com/awslabs/amazon-eks-ami has been updated to generate AL2023 image with cgroups v2)

Both the serial and non-serial NodeConformance jobs feel solid to me having worked with it across the OS's above.

thanks,
Dims

/close

**Comment by bsdnet** [comment]
@bobbypage  @BenTheElder  Thanks. Sorry for missing this message.

What I mean is Cgroupv2 is not just OS settings,  containerd requires reconfiguration if what I remember is correct.  Of course, if we treat containerd as one part of OS, we should be good
