### ISSUE TITLE
UDP traffic to Loadbalancer IP fails after node reboot (mode ipvs)

### ISSUE THREAD

**Issue by VivekThrivikraman-est** [kubernetes/kubernetes#108065]
### What happened?

We have a scaled set up with 159 nodes, ~11k pods and ~1500 services(k8s in ipvs mode), there on every node restart we are seeing many client UDP requests to multiple LBIP:port serving UDP traffic is getting black holed because of invalid conntrack entry. We are running in k8s version 1.23.3, so I suppose all the latest fixes for conntrack issues should be available.
The UDP clients which access the LB ingress are pods in the cluster itself. The backend pod which serves UDP was not restarted(backend pod was not in restarted node) and hence was always READY, the client pod accessing the LB IP was restarted because of node restart. The client udp pods keeps on retrying connection with the same udp source port.

I am attaching the proxy log(versbose 7) for the restarted node and the conntrack events with timestamp with this issue.

From the logs, looks like the packet came well after the rules were programmed:

Invalid conntrack:
[1644409107.142928]	    [NEW] udp      17 30 src=50.117.79.3 dst=64.64.64.59 sport=42467 dport=8890 [UNREPLIED] src=64.64.64.59 dst=50.117.79.3 sport=8890 dport=42467
Timestamp above translates to : GMT: Wednesday, February 9, 2022 12:18:27.142 PM
LB IP:64.64.64.59 , udp client pod:50.117.79.3   
If you see the 2nd tuple(reverse direction) does not have NAT'ed entries(but from proxy logs looks like by that time ipvs rules were already written).

From the proxy log:
I0209 12:17:52.516740       1 endpointslicecache.go:358] "Setting endpoints for service port name" portName="bat-t2/cnf-cp-sfs-t2-46-net-udp:tapp-udp" endpoints=[192.168.11.237:8890 192.168.110.139:8890 192.168.135.77:8890 192.168.183.209:8890 192.168.200.199:8890 192.168.214.234:8890 192.168.215.32:8890 192.168.219.117:8890 192.168.219.222:8890 192.168.220.125:8890 192.168.247.165:8890 192.168.248.97:8890 192.168.250.78:8890 192.168.255.76:8890 192.168.37.61:8890 192.168.55.131:8890 192.168.57.24:8890 192.168.59.101:8890 192.168.7.62:8890 192.168.88.125:8890]

I0209 12:17:56.325097       1 proxier.go:1972] "Adding new service" serviceName="bat-t2/cnf-cp-sfs-t2-46-net-udp:tapp-udp" virtualServer="64.64.64.59:8890/UDP"
I0209 12:17:56.325126       1 proxier.go:1996] "Bind address" address="64.64.64.59"
I0209 12:18:01.339193       1 ipset.go:176] "Successfully added ip set entry to ip set" ipSetEntry="64.64.64.59,udp:8890" ipSet="KUBE-LOAD-BALANCER"
I0209 12:18:04.413562       1 conntrack.go:66] Clearing conntrack entries [-D --orig-dst 64.64.64.59 -p udp]

I0209 12:18:11.338453       1 proxier.go:1008] "syncProxyRules complete" elapsed="18.876838575s"

So the first packet came at 12:18:27.142 but the rules for the same service with endpoints were programmed well before at 12:18:11.338453. And there were no other events related to this service/endpoint until the first packet came.

In /var/log/messages saw below message, but not sure if it could have an impact as some other services were working:
2022-02-09T13:17:52.573177+01:00 pool08-n108-wk08-n053 systemd-udevd[14685]: Could not generate persistent MAC address for kube-ipvs0: No such file or directory

Output of ipvsadm command:
UDP 05:00  UDP         50.117.79.3:42467  64.64.64.59:8890   **192.168.88.125:8890**

UDP  64.64.64.59:8890 rr
  -> 192.168.7.62:8890            Masq    1      0          1         
  -> 192.168.11.237:8890          Masq    1      0          0         
  -> 192.168.37.61:8890           Masq    1      0          1         
  -> 192.168.55.131:8890          Masq    1      0          1         
  -> 192.168.57.24:8890           Masq    1      0          1         
  -> 192.168.59.101:8890          Masq    1      0          1         
  **-> 192.168.88.125:8890          Masq    1      0          1**         
  -> 192.168.110.139:8890         Masq    1      0          0         
  -> 192.168.135.77:8890          Masq    1      0          0         
  -> 192.168.183.209:8890         Masq    1      0          0         
  -> 192.168.200.199:8890         Masq    1      0          0         
  -> 192.168.214.234:8890         Masq    1      0          0         
  -> 192.168.215.32:8890          Masq    1      0          0         
  -> 192.168.219.117:8890         Masq    1      0          0         
  -> 192.168.219.222:8890         Masq    1      0          0         
  -> 192.168.220.125:8890         Masq    1      0          0         
  -> 192.168.247.165:8890         Masq    1      0          0         
  -> 192.168.248.97:8890          Masq    1      0          0         
  -> 192.168.250.78:8890          Masq    1      0          0         
  -> 192.168.255.76:8890          Masq    1      0          0        

The above output shows ipvs vip had one hit matching the packet with invalid conntrack (inactconn is 1).

Attached logs(kubeproxy log for rebooted node and conntrack event log for rebooted node with timestamp):
[reboot_proxy.log](https://github.com/kubernetes/kubernetes/files/8047390/reboot_proxy.log)
[conntrack_event_log_worker.log](https://github.com/kubernetes/kubernetes/files/8047396/conntrack_event_log_worker.log)

### What did you expect to happen?

After node reboot all UDP traffic should reach backend pod successfully through LB ingress. 

### How can we reproduce it (as minimally and precisely as possible)?

We are not sure of the actual steps to reproduce, but we are seeing this in the scaled environment after every node restart.

- Below is our setup:

~> kubectl get nodes | wc -l
  159
:~> kubectl get pods -A| wc -l
  11197
:~> kubectl get svc -A| wc -l
  1492

- Out of these around 800 are UDP services.
- The client pods accesses the UDP server through LB ingress IP.
- Restart one of the nodes and when the server is back in running state, there would be many invalid conntrack entries blackholing the traffic

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"60a539cdd7ac8ea7a62b7c3bd1d3c374529788cb", GitTreeState:"clean", BuildDate:"2022-01-26T06:28:20Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"60a539cdd7ac8ea7a62b7c3bd1d3c374529788cb", GitTreeState:"clean", BuildDate:"2022-01-26T06:18:30Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

$ uname -a
# paste output here
Linux control-plane-n108-mast-n057 5.3.18-24.99-default #1 SMP Sun Jan 23 19:03:51 UTC 2022 (712a8e6) x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by uablrek** [comment]
area/ipvs

**Comment by uablrek** [comment]
/area/ipvs

**Comment by andrewsykim** [comment]
@VivekThrivikraman-est yeah please let me know when you have more details on the repro. 

In the meantime, what is `/proc/sys/net/ipv4/vs/conn_reuse_mode` set to?

**Comment by VivekThrivikraman-est** [comment]
> In the meantime, what is `/proc/sys/net/ipv4/vs/conn_reuse_mode` set to?

It is set to 0.

**Comment by thockin** [comment]
triage ping

**Comment by VivekThrivikraman-est** [comment]
Bit more detail on the setup, here the egress traffic(source) to LBIP is sent through pods secondary ip which is routed to the cluster through DC GW, basically simulating North south traffic. But we don't suspect secondary to DC GW having any issue(it is L2) and from the logs shared it is clear that the traffic has hit a node in cluster after ipvs rules are programmed, but has wrong reply tuple.
If you can please suggest the required logs/configs, I can request for reproducing the issue again and collect all required info.

**Comment by uablrek** [comment]
I can replicate a similar scenario, but perhaps not the same, by temporary removing the LBIP from kube-ipvs0. The conntrack entry has not been load-balanced, the LBIP not translated, nor has it been SNAT'ed to the node-ip;
```
 [1644409107.142928] [NEW] udp 17 30 src=50.117.79.3 dst=64.64.64.59 sport=42467 dport=8890 [UNREPLIED] src=64.64.64.59 dst=50.117.79.3 sport=8890 dport=42467
```
This looks like the packet has not been routed to ipvs. I can't explain that the time-stamp suggests otherwise.

To replicate;
```
ip addr del <lbip>/32 dev kube-ipvs0
# Send a UDP packet. An invalid conntrack entry similar to the one in this issue should appear
ip addr del add/32 dev kube-ipvs0
# The invalid conntrack entry blocks traffic until it times out (30s of inactivity)
```
If new udp packets are sent constantly the invalid entry is refreshed (to 30s) all the time and will not go away.

**Comment by uablrek** [comment]
This error has been seen;
```
E0209 12:18:47.395530       1 proxier.go:1110] "Failed to list all node IPs from host" err="error listing LOCAL type addresses from host, error: Could not get addresses: route ip+net: no such network interface"
```
May not be related, but then again, it might. The error is cast here https://github.com/kubernetes/kubernetes/blob/19762408612e49401aa46d8396c7032462fe5ab0/pkg/proxy/ipvs/netlink_linux.go#L133-L136

The go library function [InterfaceAddrs](https://pkg.go.dev/net#InterfaceAddrs) casts an error, unclear why. A guess is that it bug-out if it firsts reads an interface name, then when to read addresses, the interface is gone gone.

**Comment by uablrek** [comment]
An "I-dont-know-what-im-doing-but-it-feels-right" fix may be to add some retries.

**Comment by thockin** [comment]
Any updates here for triage?

**Comment by uablrek** [comment]
There is no proof but I would say there are circumstantial evidences;

* The InterfaceAddrs() cast an error and it is involved in assigning addresses to `kube-ipvs0`
* The problem can be "simulated" by messing with addresses on `kube-ipvs0`
* There are interfaces coming and going during the reboot

So yes, I think this is a bug in K8s.

/triage accepted

If my theory about InterfaceAddrs() is correct:

> A guess is that it bug-out if it firsts reads an interface name, then when to read addresses, the interface is gone.

it is still next to impossible to recreate in a controlled way so the only way I can see is to add retries and test on the huge cluster;

> We have a scaled set up with 159 nodes, ~11k pods and ~1500 services

**Comment by uablrek** [comment]
Wrote an issue on `go`; https://github.com/golang/go/issues/51934

**Comment by JornShen** [comment]
@VivekThrivikraman-est what's the difference between this issue problem and https://github.com/kubernetes/kubernetes/issues/105192 ? I see they have the same name

**Comment by VivekThrivikraman-est** [comment]
> @VivekThrivikraman-est what's the difference between this issue problem and #105192 ? I see they have the same name

The other issue is when traffic reaches before the rules are programmed(hence k8s had to clear the stale conntrack entries after rules are programmed). But in this case we have confirmed that the ipvs rules were programmed already and then the traffic reached.

**Comment by VivekThrivikraman-est** [comment]
An update on the issue, we had enabled the ipvs logs in the setup, and the issue seems to be related to ipvs.

**Comment by uablrek** [comment]
@VivekThrivikraman-est Still an issue? If so, remove the rotten label
