### ISSUE TITLE
Documentation: protobuf encoding of Watch events do not include "k8s\x00" prefix

### ISSUE THREAD

**Issue by D1abloRUS** [kubernetes/kubernetes#108071]
### What happened?

Hi!

In the [documentation](https://kubernetes.io/docs/reference/using-api/api-concepts/#protobuf-encoding), all k8s types used for protobuf encoding must start with `"k8s\x00"` but some api responses for example(http 504):
```bash
b'\x00\x00\x00q\n\x05ERROR\x12h\nfk8s\x00\n\x0c\n\x02v1\x12\x06Status\x12N\n\x06\n\x00\x12\x00\x1a\x00\x12\x07Failure\x1a/too old resource version: 181537752 (181538558)"\x07Expired0\x9a\x03\x1a\x00"\x00'
```
 start with the error type.

### What did you expect to happen?

Following the documentation protobuf response must be start with `"k8s\x00"`

### How can we reproduce it (as minimally and precisely as possible)?

```bash 
curl -k 'https://localhost:6443/api/v1/namespaces/default/pods?watch=1&resourceVersion=1'  -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/vnd.kubernetes.protobuf" -H "Accept: application/vnd.kubernetes.protobuf" --output -
```
valid protobuf encoding response(403 http):
```bash
k8s


v1Status�

Failure�pods is forbidden: User "system:serviceaccount:default:default" cannot watch resource "pods" in API group "" in the namespace "default""	Forbidden*
pods(20�"%
```

```bash 
curl -k 'https://localhost:6443/api/v1/namespaces/default/pods?watch=1&resourceVersion=1'  -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/vnd.kubernetes.protobuf" -H "Accept: application/vnd.kubernetes.protobuf" --output -
```

not valid protobuf encoding response(504 http):
```
a
ERRORX
Vk8s


v1Status>

Failuretoo old resource version: 1 (3)"Expired0�"%
```

### Kubernetes version

<details>

```console
$ kubectl version
1.23.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig api-machinery

**Comment by liggitt** [comment]
/remove-kind bug
/kind documentation

The distinction is whether the response is using chunked streaming encoding or not.

The first request returns a non-200 error code and an encoded Status object (adding `-v` shows a non-200 status code).

The second request returns a 200 and starts streaming watch Event protobuf objects, the first and last of which happens to be an Error event. Those are encoded directly without the k8s prefix/envelope.

I agree the documentation should be updated to describe the serialized responses to a watch request accurately.

**Comment by fedebongio** [comment]
/help 
/triage accepted
Thank you Jordan as usual!
