### ISSUE TITLE
test/e2e/testing-manifests/statefulset/etcd/statefulset.yaml run error

### ISSUE THREAD

**Issue by zerols** [kubernetes/kubernetes#108005]
### What happened?

i have copy test/e2e/testing-manifests/statefulset/etcd/statefulset.yaml and run in k8s v1.21.3 then it show me /bin/sh 37 bad substitution。
confused：
- what diferent between collect_member and member_hash  and cut -d':' -f1 | cut -d'[' -f1 whether wrong 
-  37 bad substitution  SET_ID=${HOSTNAME:5:${#HOSTNAME}} is this line ? 

### What did you expect to happen?

it would run 3 pod and exec with cmd etcdctl member list show me three members

### How can we reproduce it (as minimally and precisely as possible)?

change storageclass and apply etcd/statefulset.yaml 

### Kubernetes version

v.1.21.3

### Cloud provider

no

### OS version

centos7

### Install tools

yaml

### Container runtime (CRI) and and version (if applicable)

docker 

### Related plugins (CNI, CSI, ...) and versions (if applicable)

flannel and storage user glusterfs

**Comment by BenTheElder** [comment]
e2e test manifests are internal details of the e2e tests, they're not meant for any other usage?

what are you copying this manifest for?

**Comment by zerols** [comment]
I want to install an etcd cluster in the k8s cluster for use by other microservices .

**Comment by BenTheElder** [comment]
These manifests are not meant for that purpose, they are test files.

You could try something like https://bitnami.com/stack/etcd/helm

I don't think there are any official Kubernetes etcd deployment manifests https://etcd.io/docs/v3.5/install/#installation-as-part-of-kubernetes-installation

**Comment by zerols** [comment]
if i use kubeadm init k8s and 3 or 5 master , which  deployment  depends on
