### ISSUE TITLE
kubectl taint not take effect

### ISSUE THREAD

**Issue by wnz27** [kubernetes/kubernetes#108037]
### What happened?

<img width="1259" alt="截屏2022-02-10 14 10 13" src="https://user-images.githubusercontent.com/12094918/153348742-4a0f35e4-fe5b-453a-9761-6c7f06cc9769.png">

### What did you expect to happen?

this taint could set success

### How can we reproduce it (as minimally and precisely as possible)?

I can't know why

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
Apple M1 Max
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wnz27** [comment]
<img width="1243" alt="2" src="https://user-images.githubusercontent.com/12094918/153349622-bc6d8ade-7b6c-4a50-9015-5768c6b4269f.png">
<img width="1148" alt="3" src="https://user-images.githubusercontent.com/12094918/153349636-6b1c55ec-4d61-42d5-81b4-a2ecdd3ab5ed.png">
this success once and next second this is none again

**Comment by ardaguclu** [comment]
I think we can close this issue, since it does not look like a bug.

/close
