### ISSUE TITLE
When finalizer is set I can still update the object

### ISSUE THREAD

**Issue by ivanspasov99** [kubernetes/kubernetes#108025]
### What happened?

The [k8s docs states](https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/#how-finalizers-work): Marks the object as read-only until its metadata.finalizers field is empty.

There was NO problem updating the cr. Is this a bug or outdated docs as it states the opposite? 

I have found that if I use `kubctl -f apply` it returns warning but still updates the resource

### What did you expect to happen?

If i follow the docs i expect that i would not have updated cr.

### How can we reproduce it (as minimally and precisely as possible)?

You can use this tutorial https://book.kubebuilder.io/reference/using-finalizers.html
and try to update some spec field or status field. 

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:35:38Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
That is a documentation error. Finalizers don't mark an object read-only. They prevent removal of the object until the finalizer is removed.

**Comment by ivanspasov99** [comment]
Can you update the documentation? :)

**Comment by ivanspasov99** [comment]
Can you please update the whole docs as there are lines which are not update?

Lines: "When you tell Kubernetes to delete an object that has finalizers specified for it, the Kubernetes API marks the object for deletion, putting it into a read-only state"

**Comment by liggitt** [comment]
weird... the other content got pulled in from somewhere else, not that file

**Comment by ivanspasov99** [comment]
It's great now, thanks @liggitt

**Comment by wallrj** [comment]
I stumbled across this issue after reading https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/ and wondering if the "read-only" part was true:
> In short, what’s happened is that the object was updated, not deleted. That’s because Kubernetes saw that the object contained finalizers and put it into a read-only state. The deletion timestamp signals that the object can only be read, with the exception of removing the finalizer key updates. In other words, the deletion will not be complete until we edit the object and remove the finalizer.

Is it possible to update that blog too?

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/website/pull/33669
