### ISSUE TITLE
Pod stuck in Terminating when deleting , kubelet Error: "UnmountVolume.TearDown failed for volume:remove /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv: directory not empty

### ISSUE THREAD

**Issue by chenhong0129** [kubernetes/kubernetes#108041]
### What happened?
When I update resource with "kubectl apply -f test.yaml", old pod is Terminating and cannot delete successfully. Kubelet log  Error: "UnmountVolume.TearDown failed for volume:remove /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv: directory not empty

```
Dec 21 16:08:27 node01 kubelet[1243]: I1222 00:08:27.395056    1243 reconciler.go:183] operationExecutor.UnmountVolume started for volume "user-data" (UniqueName: "kubernetes.io/glusterfs/xxxxxx") pod "xxx" (UID: "xxx")
Dec 21 16:08:27 node01 kubelet[1243]: W1222 00:08:27.395221    1243 mount_helper_common.go:65] Warning: "/var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv" is not a mountpoint, deleting
Dec 21 16:08:27 node01 kubelet[1243]: E1222 00:08:27.395403    1243 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/glusterfs/xxxxxx podName:xxx nodeName:}" failed. No retries permitted until 2020-12-22 00:10:29.395331912 +0800 CST m=+4017961.263974921 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"user-data\" (UniqueName: \"kubernetes.io/glusterfs/xxxxxx\") pod \"xxx\" (UID: \"xxx\") : remove /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv: directory not empty"
```
In kubelet code I know that the question happend in os.Remove(mountPath)，but what would cause this problem？
![image](https://user-images.githubusercontent.com/26050948/153377102-c70d72db-e647-4d5e-98f4-ec28d85c062f.png)

### What did you expect to happen?

pod delete successfully

### How can we reproduce it (as minimally and precisely as possible)?

hard to reproduce

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux node3 3.10.0-957.27.2.el7.x86_64 #2 SMP Wed Nov 11 03:28:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
[root@node3 ~]# gluster --version
glusterfs 6.0
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
[root@node3 k8s-resources]# docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:10 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[root@node3 k8s-resources]#
[root@node3 k8s-resources]# containerd --version
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
[root@node3 k8s-resources]#

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chenhong0129** [comment]
> ### What happened?
> When I update resource with "kubectl apply -f test.yaml", old pod is Terminating and cannot delete successfully. Kubelet log Error: "UnmountVolume.TearDown failed for volume:remove /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv: directory not empty
> 
> ```
> Dec 21 16:08:27 node01 kubelet[1243]: I1222 00:08:27.395056    1243 reconciler.go:183] operationExecutor.UnmountVolume started for volume "user-data" (UniqueName: "kubernetes.io/glusterfs/xxxxxx") pod "xxx" (UID: "xxx")
> Dec 21 16:08:27 node01 kubelet[1243]: W1222 00:08:27.395221    1243 mount_helper_common.go:65] Warning: "/var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv" is not a mountpoint, deleting
> Dec 21 16:08:27 node01 kubelet[1243]: E1222 00:08:27.395403    1243 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/glusterfs/xxxxxx podName:xxx nodeName:}" failed. No retries permitted until 2020-12-22 00:10:29.395331912 +0800 CST m=+4017961.263974921 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"user-data\" (UniqueName: \"kubernetes.io/glusterfs/xxxxxx\") pod \"xxx\" (UID: \"xxx\") : remove /var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv: directory not empty"
> ```
> 
> ### What did you expect to happen?
> pod delete successfully
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> hard to reproduce
> 
> ### Anything else we need to know?
> _No response_
> 
> ### Kubernetes version
> ### Cloud provider
> ### OS version
> ### Install tools
> ### Container runtime (CRI) and and version (if applicable)
> ### Related plugins (CNI, CSI, ...) and versions (if applicable)

/sig storage

**Comment by chenhong0129** [comment]
/var/lib/kubelet/pods/xxx/volumes/kubernetes.io~glusterfs/test-gluster-pv directory info，The directory is not mounted to gfs:
[root@node01 ~]# ll /var/lib/kubelet/pods/43f9c957-4c89-47e3-bf90-8d7f43f51040/volumes/kubernetes.io~glusterfs/test-gluster-pv
总用量 0
drwxr-xr-x. 3 root root 18 2月   9 17:19 common
drwxr-xr-x. 3 root root 18 2月   9 17:19 upLoad

[root@node01 ~]# stat /var/lib/kubelet/pods/43f9c957-4c89-47e3-bf90-8d7f43f51040/volumes/kubernetes.io~glusterfs/test-gluster-pv
  文件："/var/lib/kubelet/pods/43f9c957-4c89-47e3-bf90-8d7f43f51040/volumes/kubernetes.io~glusterfs/test-gluster-pv"
  大小：34              块：0          IO 块：4096   目录
设备：fd02h/64770d      Inode：408194313   硬链接：4
权限：(0755/drwxr-xr-x)  Uid：(    0/    root)   Gid：(    0/    root)
环境：system_u:object_r:var_lib_t:s0
最近访问：2022-02-09 17:19:50.164114877 +0800
最近更改：2022-02-09 17:19:34.490290429 +0800
最近改动：2022-02-09 17:19:34.490290429 +0800
创建时间：-

[root@node01 ~]# df /var/lib/kubelet/pods/43f9c957-4c89-47e3-bf90-8d7f43f51040/volumes/kubernetes.io~glusterfs/test-gluster-pv -kh
文件系统        容量  已用  可用 已用% 挂载点
/dev/vda2       190G   63G  128G   33% /     
[root@node01 ~]#

Under normal circumstances，this directory mount as follows:
[root@node01 ~]# df /var/lib/kubelet/pods/12b3eca2-d9c7-482c-a52a-319a5bc30e3b/volumes/kubernetes.io~glusterfs/test-gluster-pv/ -kh
文件系统                    容量  已用  可用 已用% 挂载点
192.168.100.2:testimages   10G  138M  9.9G    2% /var/lib/kubelet/pods/12b3eca2-d9c7-482c-a52a-319a5bc30e3b/volumes/kubernetes.io~glusterfs/test-gluster-pv
[root@node01 ~]#

**Comment by yxxhero** [comment]
@chenhong0129 can you show the  test.yaml. Thanks very much.

**Comment by chenhong0129** [comment]
> @chenhong0129 can you show the test.yaml. Thanks very much.
The yamls of pv/pvc/pod are as follows，when I rollingUpdate pod by "kubectl apply -f pod.yam", old pod is Terminating for ever : 
1、test-gluster-pv.yaml
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-gluster-pv
  labels:
    pv: test-gluster-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  glusterfs:
    endpoints: gfs-storage-testimages
    path: testimages
`
2、test-gluster-pvc.yaml
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-gluster-pvc
  namespace: test
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      pv: test-gluster-pv
`

3、pod.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-rs
  namespace: test
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: test-rs
  template:
    metadata:
      labels:
        app: test-rs
        "compId" : "test-TOPO"
        "isJava" : "yes"
    spec:
      containers:
      - name: test-rs
        env:
        xxxx
        image: xxxx
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        resources:
          requests:
            cpu: 500m
            memory: 1000Mi
          limits:
            cpu: 1000m
            memory: 4000Mi
        volumeMounts:
        - mountPath: /opt/test/log
          name: locallog
        - mountPath: /etc/localtime
          name: localtime
        - mountPath: /opt/test/config/resources/images
          name: testimgdir
        livenessProbe:
          httpGet:
            path: /lives/hello
            port: 8091
          initialDelaySeconds: 600
          periodSeconds: 10
          failureThreshold: 5
      volumes:
      - name: locallog
        hostPath:
          path: /var/lib/ssdata/xxx/xxx/test-rs
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: testimgdir
        persistentVolumeClaim:
          claimName: test-gluster-pvc
`

**Comment by yxxhero** [comment]
@chenhong0129 Yaml needs formatting. Thanks very much.

**Comment by chenhong0129** [comment]
@yxxhero formatted, please check, Thanks very much.
