### ISSUE TITLE
Make CloMonitor happy

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#108051]
See https://clomonitor.io/projects/kubernetes/kubernetes Most of the things that the tool is complaining about, we have information just not in the form the tool accepts. So let's try to see if we can point to existing resources with a placeholder file or something?

![image](https://user-images.githubusercontent.com/23304/153490612-99490839-7373-4bb3-8b91-82842c758238.png)

For example the Roadmap may be a pointer to kubernetes/enhancements repository, governance may be a pointer to relevant docs in community and/or steering repository etc.

**Comment by SubhasmitaSw** [comment]
@dims can you point to some backdrop around CloMonitor? I need a brief understanding before approaching this.

**Comment by dims** [comment]
@SubhasmitaSw the background is that the CNCF has launched a tool clomonitor to help projects do better in adopting best practices and establish a baseline for where information is stored so it is easy for any end users of projects to find things easily. the code for clomonitor.io is at https://github.com/cncf/clomonitor/ so that is open sourced as well. Hope this helps

**Comment by idvoretskyi** [comment]
Right, please also note that we are still in an alpha state, so happy to hear the feedback through the issues here - https://github.com/cncf/clomonitor/issues
