### ISSUE TITLE
TestErrConnKilled - data race

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#108043]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/106948/pull-kubernetes-unit/1491713959680544768

```
=== RUN   TestErrConnKilled
==================
WARNING: DATA RACE
Read at 0x0000038a5620 by goroutine 140:
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1036 +0x73e
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printDepth()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:735 +0x2d4
  k8s.io/kubernetes/vendor/k8s.io/klog/v2.ErrorDepth()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1584 +0x104
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logError()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:115 +0x1d
  k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleError()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:109 +0xa7
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func2.1()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:137 +0x1d9

Previous write at 0x0000038a5620 by goroutine 365:
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.captureStdErr()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout_test.go:277 +0x284
  k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.TestErrConnKilled()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout_test.go:289 +0x44
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
```

/sig api-machinery
/kind bug
/priority important-soon

**Comment by aojea** [comment]
It seems something is racing writhing the logs ?

      > /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/priority-and-fairness_test.go:60 +0x35

>       /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout_test.go:277 +0x284

cc: @MikeSpreitzer

**Comment by pacoxu** [comment]
Failed with this:

pull-kubernetes-unit	https://github.com/kubernetes/kubernetes/commit/2fba7c8aded09759fa7a2ae92d78cc7f6a16b829	[link](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108127/pull-kubernetes-unit/1493794415049707520)

**Comment by liggitt** [comment]
> this looks like a test-only race

which still needs to be fixed

**Comment by MikeSpreitzer** [comment]
It seems to me that this bug can not be fixed with `klog` as it is, namely used without a logger object or even a `context.Context`.  The smallest tweak that occurs to me would be to add an option to `klog` to _add_ an output destination, and later remove that addition.  Thus, a test could add logging to its own buffer for the duration of running the code under test.

**Comment by utkarsh348** [comment]
This may be similar to #108193. How can I reproduce this issue?
