### ISSUE TITLE
scheduler v1beta3 pre-appends an out-of-tree plugin instead of append

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#108083]
### What happened?

Out-of-tree plugin typically composes its scheduler ComponentConfig like:

```yaml
profiles:
- plugins:
    preFilter:
      enabled:
      - name: Foo
    filter:
      enabled:
      - name: Foo
```

recently I found that when this is applied into the latest v1beta3 config, `Foo` is pre-appended to the finalized plugin list - i.e., `{preFilter|filter}.enabled = "Foo, <default in-tree plugins>"`.

### What did you expect to happen?

Same as the behavior of v1beta1 and v1beta2, out-of-tree plugin should be placed **at the end** of the finalized pluginList, i.e., preFilter.enabled = "<default plugins>, Foo".

### How can we reproduce it (as minimally and precisely as possible)?

A unit test gist https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808 is created to reproduce this issue.

After `git apply` this diff, run `go test ./cmd/kube-scheduler/app/...`:

```
--- FAIL: TestSetup (4.57s)
    --- FAIL: TestSetup/out-of-tree_component_configuration_v1beta3 (0.39s)
        server_test.go:551: Unexpected plugins diff (-want, +got):   map[string]*config.Plugins{
              	"default-scheduler": &{
              		QueueSort: {Enabled: {{Name: "PrioritySort"}}},
              		PreFilter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeAffinity"},
              				{Name: "NodePorts"},
              				... // 3 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		Filter: config.PluginSet{
              			Enabled: []config.Plugin{
            + 				{Name: "Foo"},
              				{Name: "NodeUnschedulable"},
              				{Name: "NodeName"},
              				... // 11 identical elements
              				{Name: "PodTopologySpread"},
              				{Name: "InterPodAffinity"},
            - 				{Name: "Foo"},
              			},
              			Disabled: nil,
              		},
              		PostFilter: {Enabled: {{Name: "DefaultPreemption"}}},
              		PreScore:   {Enabled: {{Name: "TaintToleration"}, {Name: "NodeAffinity"}, {Name: "PodTopologySpread"}, {Name: "InterPodAffinity"}}},
              		... // 7 identical fields
              	},
              }
FAIL
FAIL	k8s.io/kubernetes/cmd/kube-scheduler/app	4.977s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/config	[no test files]
ok  	k8s.io/kubernetes/cmd/kube-scheduler/app/options	0.698s
?   	k8s.io/kubernetes/cmd/kube-scheduler/app/testing	[no test files]
FAIL
```

### Kubernetes version

<details>

```console
$ kubectl version
# master
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Huang-Wei** [comment]
@miam could you take a stab on this issue?

**Comment by Huang-Wei** [comment]
@miamipanther could you take a stab on this issue?

**Comment by Huang-Wei** [comment]
cc @damemi

**Comment by damemi** [comment]
This is probably due to MultiPoint expansion, but is it a bug? When dealing with multipoint, we decided that specific extension point configurations should take precedence over the default plugins. In other words, if a user is intentionally making a configuration change then that is likely higher priority than the defaults.

I'm trying to find if we had any discussion about ordering related to out-of-tree plugins, I'm pretty sure this came up. For reference I'm looking at the multipoint PR https://github.com/kubernetes/kubernetes/pull/105611

**Comment by damemi** [comment]
We do have a couple unit tests for making sure custom plugins are appended:
* [custom plugin appended to specific extension point](https://github.com/kubernetes/kubernetes/blob/420c5308bbf13eeb/pkg/scheduler/apis/config/v1beta3/default_plugins_test.go#L124-L149)
* [custom multipoint plugin is appended after other multipoint plugins](https://github.com/kubernetes/kubernetes/blob/420c5308bbf13eeb/pkg/scheduler/apis/config/v1beta3/default_plugins_test.go#L362-L388)

So it looks like the test case we are missing (which is showing up here) is that a custom plugin for a specific extension point is being prepended over the multipoint plugins for that point. So, the intersection between `CustomSpecificPlugin` x `MultiPoint`?

**Comment by miamipanther** [comment]
I will give it a try @Huang-Wei

**Comment by Huang-Wei** [comment]
> In other words, if a user is intentionally making a configuration change then that is likely higher priority than the defaults.

In this [gist](https://gist.github.com/Huang-Wei/09050a3b19e456ea837643f077ff2808), I merely replaced v1beta2 with v1beta3, which suggests a user may even are not aware of default plugins, it's just aimed to enable the custom plugin instead of making a configuration change.

> So it looks like the test case we are missing (which is showing up here) is that a custom plugin for a specific extension point is being prepended over the multipoint plugins for that point. So, the intersection between `CustomSpecificPlugin` x `MultiPoint`?

I think so - `v1beta3` internally uses the multipoint plugin set while `v1beta2` doesn't.

**Comment by ahg-g** [comment]
thanks @Huang-Wei ; we need to backport the fix once we have one.

**Comment by kerthcet** [comment]
Hi @miamipanther , have you made any progress? If not, I'd like to take a look.

**Comment by miamipanther** [comment]
@kerthcet I am working on a PR, thanks

**Comment by Huang-Wei** [comment]
@miamipanther this issue looks more complex than I thought. If you don't mind, I can take it over providing a fix.
