### ISSUE TITLE
Making remaining untested Node endpoints ineligible for conformance

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#108035]
**Why:**
There are three `Node` endpoints showing up on [APISnoop]( https://apisnoop.cncf.io/conformance-progress/endpoints/1.24.0/?filter=untested) as untested for conformance.
Due to the fact that endpoints tested for conformance [should not be dependant on Kubelet](https://github.com/kubernetes/community/blame/master/contributors/devel/sig-architecture/conformance-tests.md#L36) these endpoint should not be eligible for conformance.

This issue is to allow for discussion and getting consensus.
If there is no objections I will create the PR to move the endpoints to the list of [Ineligible endpoints](https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints) to be reviewed at a later stage

**Endpoints**

- readCoreV1NodeStatus
- replaceCoreV1NodeStatus
- deleteCoreV1CollectionNode

/sig node
/sig architecture
/area conformance

**Comment by dims** [comment]
looks like we have `createCoreV1Node` and `deleteCoreV1Node` already listed in [test/conformance/testdata/ineligible_endpoints.yaml](https://github.com/kubernetes/kubernetes/blob/3866cb91f22da6eb49dab10dd5c33385690b57b4/test/conformance/testdata/ineligible_endpoints.yaml)

If i remember the context behind https://github.com/kubernetes/community/blame/master/contributors/devel/sig-architecture/conformance-tests.md#L36 correctly, that essentially says if the test had to call kubelet API directly or indirectly (via node proxy endpoint) then those can't be in conformance. 

But the more i dig into the original  `createCoreV1Node` and `deleteCoreV1Node` and the ones listed above here, I feel that the calls do NOT fall under the rule above. we can call all 5 API(s) w/o them synchronously calling kubelet API directly or indirectly.

Let me ping @derekwaynecarr and @smarterclayton as they may remember more of the discussion/decisions from earlier.

**Comment by derekwaynecarr** [comment]
The 3 endpoints are served by kube-apiserver.  The first 2 of the 3 are invoked by kubelet clients, I would expect APIs invoked from a kubelet to be covered under conformance.  The last call is I believe invoked by node lifecycle controller in kcm and I would expect the served API from kube-apiserver to be conformant as well.

**Comment by derekwaynecarr** [comment]
I think conformance should not be eligible to give the appearance for a newly schedulable node.  So if something like create node was added under conformance, I do not believe CSR approval flows to make that node trusted for workload in conformance.  At best, the create node flow would be able to say here is a node but conformance should never be allowed to make that node trusted.

**Comment by derekwaynecarr** [comment]
One issue for delete node collection is it may be impractical for that call to succeed in some deployments.  I guess if we could scope the delete node call to a node that was not yet trusted, it could work?

**Comment by smarterclayton** [comment]
We have historically focused conformance on the perceived end user experience deploying applications to a conformant Kubernetes cluster as being consistently successful.  From that perspective, while these are actions that are indeed key to conformant behavior, the first two are not invoked by end users, only by kubelets and potentially administrators.  I would expect to be able to create a node object, delete it, mutate its status, and delete a portion of them on a conformant Kubernetes cluster as an admin - but I would not expect a similar end user to do so.  

If we can make a case that a conformant Kubernetes distribution would reasonably not allow any of these actions via the API, then we could make a case to omit them from conformance.  I can see a small path to adding these to conformance under a "they may be necessary as administrative action on the vast majority of kubernetes clusters", but I can't necessarily bump that 100% of Kube clusters, especially putting the application deployer first.

**Comment by Riaankl** [comment]
Close in favour of #109379
