### ISSUE TITLE
kube-controller-manager defaults to listen on 127.0.0.1 ONLY

### ISSUE THREAD

**Issue by KlavsKlavsen** [kubernetes/kubernetes#108069]
### What happened?

a pretty standard kubeadm setup of k8s 1.22.5 - and kube-controller-manager runs in a pod - but it is set to ONLY listen on 127.0.0.1 - making its metrics endpoint unreachable by other nodes in the cluster - meaning Prometheus can't monitor it :(

### What did you expect to happen?

IMHO kube-controller-manager SHOULD listen on 127.0.0.1 (for local node access I guess) - AND an ip in cluster-cidr range (like normal pods do) - so it can be reached from pods inside the cluster - without exposing the services outside the cluster and potentially to the public internet.

The "fix" I see all recommend, is to set it to listen on the public ip of the node - which opens it up to whatever other hosts are on the same network as the k8s nodes (thats bad - especially for those running in f.ex. hetzner - where servers have public ips) - and then you'll depend on firewalling being correct (and dynamic - to only allow new nodes in k8s cluster to access it).

### How can we reproduce it (as minimally and precisely as possible)?

normal kubeadm setup has this setting.

### Kubernetes version

1.22.5

### Cloud provider

Hetzner physical servers.

### OS version

Ubuntu 20.04

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico

**Comment by KlavsKlavsen** [comment]
kube-scheduler has the exact same problem :(

**Comment by aojea** [comment]
This is "secure" by default.


> The "fix" I see all recommend, is to set it to listen on the public ip of the node - which opens it up to whatever other hosts are on the same network as the k8s nodes (thats bad - especially for those running in f.ex. hetzner - where servers have public ips) - and then you'll depend on firewalling being correct (and dynamic - to only allow new nodes in k8s cluster to access it).

Opening in a public IP makes it accessible for everyone , 🤔

The IP is not hardcoded, people can choose the ips , why the default should be changed?

**Comment by KlavsKlavsen** [comment]
@aojea I will try to explain more clearly.
I agree listening on localhost is "secure" - but it does mean that you cannot monitor it (reach the /metrics endpoint) - so that kinda defeats the purpose of having a metrics endpoint :)
Problem is - the services currently can ONLY be set to listen on localhost OR public ip.
public ip is bad  as its EASY to accidently open it up to the world.
Which is WHY I propose it gets modified to ALSO get an IP from the pod-cidr network - which would make it accessible from PODS on all nodes in same cluster ONLY. That would mean prometheus can reach it - so its monitorable by default (as opposed to now) AND it helps people NOT having to choose the less secure route of letting it listen on the nodeip - exposing it to the "world outside the k8s cluster".

**Comment by KlavsKlavsen** [comment]
Currently its not even getting an ip from the cluster-cidr range - which is what it argue that it should have - to have a default that is usable for monitoring AND secure.

**Comment by neolit123** [comment]
this is an advanced use case that has been discussed mutliple times and it's a kubeadm setup default that we will not change.

> I agree listening on localhost is "secure" - but it does mean that you cannot monitor it (reach the /metrics endpoint) - so that kinda defeats the purpose of having a metrics endpoint :)

some users use a proxy for this.

> Problem is - the services currently can ONLY be set to listen on localhost OR public ip.

kubeadm allows you to customize any IP that you want for the component static pod:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/
also check extraArgs and extraMounts if you want to add serving certificates.
(note subsequent extraArgs with the same name override prior args)

/sig cluster-lifecycle
/kind support
/area kubeadm
/close
