### ISSUE TITLE
kubelet: Race condition in nodeshutdown unit test

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#108040]
### What happened?

There seems to be a race condition in the following unit test

https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L617

The race happens between
read at
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L707

and write at
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L328

### What did you expect to happen?

No race condition

### How can we reproduce it (as minimally and precisely as possible)?

```bash
cd $KUBE_ROOT/pkg/kubelet/nodeshutdown
go test -c -race
stress ./nodeshutdown.test -test.run ^Test_managerImpl_processShutdownEvent$
```

### Anything else we need to know?

CI logs where race was detected: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/108039/pull-kubernetes-unit/1491676749694504960

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
A related pr merged https://github.com/kubernetes/kubernetes/pull/107774 @MadhavJivrajani

**Comment by MadhavJivrajani** [comment]
Thanks @utkarsh348, for checking again.
https://github.com/kubernetes/kubernetes/pull/107774#issuecomment-1039113579
@kerthcet fyi

**Comment by MadhavJivrajani** [comment]
Maybe we need something like this: https://github.com/kubernetes/kubernetes/pull/98944?

**Comment by jonyhy96** [comment]
@utkarsh348 are u working on resolve this issue? i  wonder why https://github.com/kubernetes/kubernetes/blob/d899c39ca3025362033b5a71e4f27c32690dc78b/staging/src/k8s.io/client-go/transport/round_trippers_test.go#L518 doesn't face a race condition

**Comment by MadhavJivrajani** [comment]
I think he's still working on it.
The race condition doesn't happen there because
https://github.com/kubernetes/kubernetes/blob/d899c39ca3025362033b5a71e4f27c32690dc78b/staging/src/k8s.io/client-go/transport/round_trippers_test.go#L534

doesn't start another go routine. In the kubelet's case however, the write part of the race condition happens in another go routine that is spawned:
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L303
write:
https://github.com/kubernetes/kubernetes/blob/40c2d049465417f510e4182b05953a49fc5693d4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L328

**Comment by liggitt** [comment]
seen in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109048/pull-kubernetes-unit/1507725298571939840

this spiked in the last couple days - https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestLocalStorage

is this related to the klog bump (https://github.com/kubernetes/kubernetes/pull/108725)?

cc @pohly 

/priority critical-urgent
/milestone v1.24

**Comment by liggitt** [comment]
increasing priority since it is impacting test runs, and marking as blocker until root causes and we understand whether it is prod-impacting

**Comment by endocrimes** [comment]
/assign

^ I'll take this one up on monday - @utkarsh348 still feel free to open a PR if you have WIP investigation/research

**Comment by MadhavJivrajani** [comment]
@endocrimes please see https://github.com/kubernetes/kubernetes/pull/108193
if you have comments/inputs on the already open one.

**Comment by pohly** [comment]
> seen in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109048/pull-kubernetes-unit/1507725298571939840
> 
> this spiked in the last couple days - https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestLocalStorage
> 
> is this related to the klog bump (#108725)?
> 
> cc @pohly

I don't see how the klog bump could have made it worse. Perhaps the change around the flush daemon changed some timing conditions, but that's a rather wild guess. These tests have been faulty all along and need to be fixed.

What klog can do is support unit tests like this better. I've opened two issues:
- short term: [restore state in unit tests](https://github.com/kubernetes/klog/issues/318)
- long term as it depends on contextual logging: [capture klog output without SetBuffer](https://github.com/kubernetes/klog/issues/317)

**Comment by MadhavJivrajani** [comment]
> increasing priority since it is impacting test runs, and marking as blocker until root caused and we understand whether it is prod-impacting

@liggitt I think it's safe to remove the release-blocker here. The root cause is largely as explained here: https://github.com/kubernetes/kubernetes/issues/108040#issuecomment-1040122707 (appears to be test-only)
