### ISSUE TITLE
kubectl server-side apply not being able to remove other field manager's fields results in invalid field combinations

### ISSUE THREAD

**Issue by irbekrm** [kubernetes/kubernetes#108081]
### What happened?

cert-manager installation includes `CustomResourceDefinition`s that up till v1.7 specified `crd.spec.conversion.strategy: Webhook` and relied on a component called [`cainjector`](https://cert-manager.io/docs/concepts/ca-injector/) to inject `crd.spec.conversion.webhook.clientConfig.caBundle`. `cainjector` is the only field manager of `crd.spec.conversion.webhook.clientConfig.caBundle` field.

Here is what managed fields for such a CRD in version v1.6.0 look like when applied with `kubectl --server-side=true`
```
managedFields:
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:cert-manager.io/inject-ca-from-secret: {}
        f:labels:
          f:app: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
      f:spec:
        f:conversion:
          f:strategy: {}
          f:webhook:
            f:clientConfig:
              f:service:
                f:name: {}
                f:namespace: {}
                f:path: {}
            f:conversionReviewVersions: {}
        f:group: {}
        f:names:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:scope: {}
        f:versions: {}
    manager: kubectl
    operation: Apply
    time: "2022-02-11T20:07:22Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:acceptedNames:
          f:categories: {}
          f:kind: {}
          f:listKind: {}
          f:plural: {}
          f:shortNames: {}
          f:singular: {}
        f:conditions:
          k:{"type":"Established"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"NamesAccepted"}:
            .: {}
            f:lastTransitionTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
    manager: kube-apiserver
    operation: Update
    time: "2022-02-11T20:07:22Z"
  - apiVersion: apiextensions.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:conversion:
          f:webhook:
            f:clientConfig:
              f:caBundle: {}
    manager: cainjector
    operation: Update
    time: "2022-02-11T20:07:34Z"
```

In v1.7 conversion webhook is removed. In our manifests `crd.spec.conversion` is unset (the default valur for this field is `crd.spec.conversion.strategy: None`)

For users who attempt to upgrade to v1.7 using `kubectl --server-side=true` it looks like `crd.spec.conversion.webhook.clientConfig.caBundle` can not be removed from the to-be-applied config as this field is managed by `cainjector`. 
Having `crd.spec.conversion.strategy: None` _and_ having `crd.spec.conversion.webhook.clientConfig.caBundle`  set is [invalid](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L441) so [the upgrade fails](https://github.com/cert-manager/cert-manager/issues/4831#issue-1125846808).

So far the only way we've found for users to upgrade to v1.7 is by manually patching managed fields.

We are also unsure how to fix this issue in `cainjector` and are wondering whether a component that modifies some fields for a resource that is created by other means, potentially by server-side apply, should be designed in such a way that it takes ownership of _all_ fields that are validated together to avoid these type of issues?

### What did you expect to happen?

As author of resource manifests and a component that modifies the resources, I expected there to be some guidance on a way how these kind of conflicts can be avoided without requiring users to manually patch the manifests or run extra commands to upgrade to a version where a field should be removed.

Perhaps it would be good if authors of manifests of resources that are expected to be modified by other field managers after they have been (server-side) applied, would have some way how to specifiy that certain fields and all subfields must be removed even if it means removing other manager's changes?

### How can we reproduce it (as minimally and precisely as possible)?

1. `kubectl apply --server-side=true -f https://github.com/cert-manager/cert-manager/releases/download/v1.6.1/cert-manager.yaml`
2. Wait for a little bit (less than a minute normally) to ensure `cainjector` has done its work or use [`cmctl check api`](https://cert-manager.io/docs/cli/cmctl/)
3. `kubectl apply --server-side=true -f https://github.com/cert-manager/cert-manager/releases/download/v1.7.1/cert-manager.yaml`

### Anything else we need to know?

Original issue where this was reported [cert-manager#4831](https://github.com/cert-manager/cert-manager/issues/4831)

/cc @apelisse 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

`kubectl --server-side=true`

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by apelisse** [comment]
/triage accepted

Thanks for opening the bug!

**Comment by Gchbg** [comment]
/reopen

> We are also unsure how to fix this issue in `cainjector` and are wondering whether a component that modifies some fields for a resource that is created by other means, potentially by server-side apply, should be designed in such a way that it takes ownership of _all_ fields that are validated together to avoid these type of issues?

I would have the exact same general question, though I'm not sure if this issue is the right place for it.
