### ISSUE TITLE
HPA should use the limits instead of requests

### ISSUE THREAD

**Issue by rennokki** [kubernetes/kubernetes#108026]
### What happened?

One issue that got closed in the past and was not re-opened: https://github.com/kubernetes/kubernetes/issues/72811

Basically, the HPA should look for the limits to fit the pods onto nodes. Not sure why requests are counting towards the HPA's metrics to see when it's the best time to scale the pods.

### What did you expect to happen?

The HPA to look for resources limits instead of resource requests.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

-

### Kubernetes version

-

### Cloud provider

-

### OS version

-

### Install tools

-

### Container runtime (CRI) and and version (if applicable)

-

### Related plugins (CNI, CSI, ...) and versions (if applicable)

-

**Comment by wangyysde** [comment]
1. the limit is not guaranteed to be reached if there are no resources available to a node, so your pod might never scale even if there is a spike in resource needs.
2. using request as base for calculation would not make different, you can set a value bigger than 100%.
3.

**Comment by harshagarwal00** [comment]
I read the whole thread, im just thinking setting hpa > 100%  is dangerous since a pod might never be able to use more resouces then requesr

**Comment by rennokki** [comment]
@harshagarwal00 somewhat relevant: https://home.robusta.dev/blog/stop-using-cpu-limits
