### ISSUE TITLE
Worker nodes running out of IPs in IP range after node reboot

### ISSUE THREAD

**Issue by Nishant-Nayan** [kubernetes/kubernetes#108121]
### What happened?

I have a kubernetes cluster with one worker node.
When I schedule a deployment of say 'n' pods and then reboot my worker node, then after the node comes up, I can see the old 'n' ips still present in '/var/lib/cni/networks/cbr0' directory, it also contains the newly assigned 'n' ips starting from the ip mentioned in 'last_reserved_ip' file.
So totally I got 2n ips of which 'n' are unused. If I reboot my worker node further then eventually I will run out of Ip address throwing me then error "no IP addresses available in range set : " .

Proposed fix - One possible fix could be to track the reboots of worker nodes. When the node comes up then we can differentiate which ip files are created before the last reboot time and delete those as they are unused and keep the one's which are newly assigned (i.e after the last reboot).

Any suggestions/feedback on this would be appreciated.

### What did you expect to happen?

Deletion of unused ips.

### How can we reproduce it (as minimally and precisely as possible)?

1) Setup a kubernetes cluster with at least one worker node.
2) Create and schedule a deployment of 'n' pods.
3) Reboot the worker node.
4) Check the ip files in  '/var/lib/cni/networks/cbr0' 

Unused 'n' ip files are found.

### Kubernetes version

v1.18.18+2

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

cri-o-1.18.4-2

### Related plugins (CNI, CSI, ...) and versions (if applicable)
kubernetes-cni-0.8.0-3
kubernetes-cni-plugins-0.8.7-2

**Comment by aojea** [comment]
The IP management depend on the Container Runtime (CRIO, containerd), since 1.20 the CNI is not part of the kubelet (or Kubernetes)

**Comment by neolit123** [comment]
/close

please reopen if needed.
