### ISSUE TITLE
support specifiy node resources  in kubemark

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/kubernetes#108181]
### What would you like to be added?

support specifiy node resources  in kubemark

### Why is this needed?

make hollow nodes  with various capacity is neccessary, especially when doing some test related to scheduler

a sample solution is support pass args to cadivisor fake

eg: kubemark --cpu=10 --memory=24Gi ......

and pass through to pkg/kubelet/cadvisor/testing/cadvisor_fake.go

```go
type Fake struct {
	NodeName       string
	NumCores       int
	MemoryCapacity uint64
}
```go

**Comment by NikhilSharmaWe** [comment]
@xrmzju Could you please explain after changing the `type Fake struct `, how we will use it to improve the tests. Also what is the use of [this](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/testing/cadvisor_fake.go#L42) line in the code and will it effect the tests when we change the `type Fake struct`.

Guidance needed, I am looking forward to collaborate.

**Comment by maaoBit** [comment]
Hi @xrmzju , does `--extended-resources` flag solve your problem?  Details can be found in this [patch](https://github.com/kubernetes/kubernetes/pull/100267).
