### ISSUE TITLE
Private node, public load balancer aws fails to ensure load balancer

### ISSUE THREAD

**Issue by rlewkowicz** [kubernetes/kubernetes#108185]
### What happened?

I'm on the latest everything as of the last week or so.

To clarify, this is NOT me looking for an internal loadbalancer. I can't google this without it showing a bunch of internal load balancer stuff.

I want my node group in a private subnet with the lb public routing to the private nodes on aws. I don't want my nodes going out the igw.

I get: message="Error syncing load balancer: failed to ensure load balancer: could not find any suitable subnets for creating the ELB"

The subnet tags, have not changed. But when I put the nodes in the private subnet, I get this error. If I create an internal loadbalancer, it works. Or if the nodes are in the public sub it works with a public load balancer. Is there anything I should be aware of when I want private nodes with a public lb?

I dont see any annotations that spark my interest here: https://kubernetes.io/docs/concepts/services-networking/_print/

### What did you expect to happen?

I want my nodes in a private subnet with a public lb.

### How can we reproduce it (as minimally and precisely as possible)?

```
This complete will give you a nice top to bottom:
https://github.com/cloudposse/terraform-aws-eks-cluster/tree/master/examples/complete

Just make sure the node groups are private only

helm upgrade -i nginx-ingress --version 9.1.5 bitnami/nginx-ingress-controller --namespace nginx --set service.loadBalancerSourceRanges='{100.64.0.0/16, [redact], 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16}' --set ingressClassResource.default=true --set controller.watchIngressWithoutClass=true"
```

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:34:20Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

AWS

**Comment by rlewkowicz** [comment]
I'm dumb, I just had messed up my locals working too late

**Comment by aojea** [comment]
> I'm dumb, I just had messed up my locals working too late

happens to all of us :smile:  
thanks for realizing and closing it
