### ISSUE TITLE
Unable to download kubelet binaries from https://dl.k8s.io/release

### ISSUE THREAD

**Issue by sovkumar** [kubernetes/kubernetes#108106]
Unable to download kubelet binaries from https://dl.k8s.io/release

**Comment by dims** [comment]
@sovkumar the following work for me. Are you behind a vpn?

- `curl -L -s https://dl.k8s.io/release/stable.txt` 
- `curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"`

**Comment by sovkumar** [comment]
resolved
