### ISSUE TITLE
Tests ci-npd-e2e-test are failing

### ISSUE THREAD

**Issue by elfinhe** [kubernetes/kubernetes#108166]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-test

### Which tests are failing?

ci-npd-e2e-test.Overall

** Ginkgo timed out waiting for all parallel procs to report back. **

### Since when has it been failing?

Since the very beginning I can see from the testgrid, maybe longer ago

02/01/2022 failed after 2m31s.
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-npd-e2e-test/1488568640893620224

### Testgrid link

https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-test

### Reason for failure (if possible)

Timeout

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/triage accepted
/priority important-soon

/assign

this may be a duplicate, let's check

**Comment by vteratipally** [comment]
https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-test is passing right now

**Comment by vteratipally** [comment]
it is the presubmits that is failing
