### ISSUE TITLE
Support PDBs for DS

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#108124]
### What happened?

While reviewing https://github.com/kubernetes/enhancements/pull/3089 @smarterclayton suggested that PDBs should be opaque to the backing controllers for the pods. As of now, PDBs are not supported for DS since it doesn't have scale subresource. Clayton suggested to introduce a read only scale subresource to DS so that PDBs can be supported for DS. 

In addition, we are going to have an e2e which proves that the PDB can work for any arbitrary controller and minAvailable should work for out of tree controllers. We should make this part of conformance test

### What did you expect to happen?

PDB working for DS just like for deployment or other controllers

### How can we reproduce it (as minimally and precisely as possible)?

- Create a PDB
- Map it to DS
- PDB is not honored while evicting pods for DS

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ravisantoshgudimetla** [comment]
cc @soltysh @atiratree @shvgn

**Comment by shvgn** [comment]
It's WIP #98307

**Comment by jonathan-innis** [comment]
Seems like this is still an issue since it hasn't been closed. This was definitely surprising behavior for me as I was working through trying to clean-up our PDB evaluation behavior in Karpenter here: https://github.com/kubernetes-sigs/karpenter/pull/789
