### ISSUE TITLE
kubectl apply produces incorrect Deployment patches after server-side port deduping

### ISSUE THREAD

**Issue by eaceaser** [kubernetes/kubernetes#108148]
### What happened?

We updated a `Deployment` resource with an incorrect update that specified two ports in a container that shared the same `(protocol, port)` tuple (albeit with different names):

```
...
ports:
- name: http
  containerPort: 9090
  protocol: TCP
- name: admin
  containerPort: 9090
  protocol: TCP
...
```

`kubectl apply` generates the following patch in this case: 

```"containers":[{"$setElementOrder/ports":[{"containerPort":9090},{"containerPort":9090}],"name":"<redacted>","ports":[{"containerPort":9090,"name":"admin"},{"containerPort":9090,"name":"http","protocol":"TCP"}]```

and serializes the input resource into `metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]`: 

```...[{\"containerPort\":9090,\"name\":\"http\",\"protocol\":\"TCP\"},{\"containerPort\":9090,\"name\":\"admin\",\"protocol\":\"TCP\"}]...```

Server-side, the ports get de-duped, and the resultant resource state contains only one port:

```
...
ports:
  - containerPort: 9090
    name: http
    protocol: TCP
...
```

The bug occurs on a subsequent apply to fix this state. If we attempt to update the Deployment via `kubectl apply` with correct port values:

```
...
ports:
  - name: admin
    containerPort: 6060
    protocol: TCP
  - name: http
    containerPort: 9090
    protocol: TCP
...
```

`kubectl apply` produces an improper patch:

```
"containers":[{"$setElementOrder/ports":[{"containerPort":6060},{"containerPort":9090}],"name":"<redacted>","ports":[{"containerPort":6060,"name":"admin","protocol":"TCP"},{"$patch":"delete","containerPort":9090}]}
```

Note the "deletion" patch here. This results in the final resource state:

```
ports:
- containerPort: 6060
  name: admin
  protocol: TCP
```

Which is unexpected, as it is missing one of the ports in the applied manifest.

This is due to the client-side strategic merge patch not being aware of server-side port deduping; it sees the "extra" port in the `last-applied-configuration` of the object, and computes the deletion patch to remove it, without being aware that the port was already removed. 

### What did you expect to happen?

The expected behavior is that the resultant resource should contain both ports specified in the final update.

```
ports:
  - name: admin
    containerPort: 6060
    protocol: TCP
  - name: http
    containerPort: 9090
    protocol: TCP
```

### How can we reproduce it (as minimally and precisely as possible)?

First create a Deployment with a single port. While this appears to be optional as far as reproducing the final end state, the server-side port deduping behavior is less obvious without creating this initial state.
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
EOF
```
then update the Deployment with two ports that duplicate `(protocol, containerPort)`:
```
cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: admin
              containerPort: 9090
              protocol: TCP
EOF
```
finally, update the Deployment with the correct resource state:
```
cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: admin
              containerPort: 6060
              protocol: TCP
EOF
```

### Anything else we need to know?

* [this is where](https://github.com/kubernetes/kubernetes/blob/a37b6fc8b488a07839e6426e5d7ce4a5165cfe73/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L551-L551) the duplicated port gets extracted from the LastAppliedConfig annotation.
* it [subsequently gets used](https://github.com/kubernetes/kubernetes/blob/a37b6fc8b488a07839e6426e5d7ce4a5165cfe73/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L609) by the patcher which produces the incorrect deletion patch.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T08:02:07Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>
</details>

### Install tools

<details>
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by eaceaser** [comment]
Also: creating a new Deployment with a duplicated `(protocol,port)` port breaks the uniqueness -- the server does not appear to deduplicate ports if its a fresh Deployment:

<details>

```

❯ cat << EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
            - name: admin
              containerPort: 9090
              protocol: TCP
EOF
deployment.apps/test created
❯ kubectl get deployment test -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"test","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"test"}},"template":{"metadata":{"labels":{"app":"test"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":9090,"name":"http","protocol":"TCP"},{"containerPort":9090,"name":"admin","protocol":"TCP"}]}]}}}}
  creationTimestamp: "2022-02-16T03:22:57Z"
  generation: 1
  name: test
  namespace: default
  resourceVersion: "2490"
  uid: 231ed361-8f01-4133-9206-4a1d43e1d60b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9090
          name: admin
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-02-16T03:22:59Z"
    lastUpdateTime: "2022-02-16T03:22:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-02-16T03:22:57Z"
    lastUpdateTime: "2022-02-16T03:22:59Z"
    message: ReplicaSet "test-7c68785c65" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

```

</details>

note the duplication:

```
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 9090
          name: admin
          protocol: TCP
```

This duplication does NOT occur if you're updating an existing Deployment resource. This also seems like a bug?

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/issues/103544#issuecomment-876153094, it seems to be dup with that.

**Comment by eaceaser** [comment]
@pacoxu I'm not sure if thats a dupe -- that seems to be an issue with the merge key for service ports not including the protocol? In this case, kubectl is specifically producing a bad patch due to server-side deduplication of conflicts on `(protocol, port)` in ContainerSpec ports

**Comment by jpbetz** [comment]
/assign @apelisse 
(feel free to triage further)

/triage accepted

**Comment by liggitt** [comment]
this is a duplicate of https://github.com/kubernetes/kubernetes/issues/58477

unfortunately, it is unlikely a fix for this will be possible, due to the requirement that the server and client perfectly agree on merge keys for computing/sending/receiving/applying strategic merge patches

/close
