### ISSUE TITLE
ephemeral containers: show more information on failures to start containers

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#108135]
### What happened?

```
$ kubectl debug -it shell-6874dcdd7f-rv5vd --image bogus
Defaulting debug container name to debugger-r2gq7.
... hang forever ...
```

`kubectl describe` shows there are, as expected, failures to pull the image. It would be great if this - and possibly other issues of starting the container - were exposed through the `kubectl debug` call to make things more obvious to the users

### What did you expect to happen?

More info is shown to user

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2-gke.300", GitCommit:"516d535fbe1cce83a6ac4dfbaa749b3c3ed499ac", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:03Z", GoVersion:"go1.17.5b7", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by eddiezane** [comment]
This seems like a valid bug.

/triage accepted

**Comment by verb** [comment]
Agreed! Thanks for pointing this out @howardjohn 

/assign
