### ISSUE TITLE
Add --write-config-to option to kubelet

### ISSUE THREAD

**Issue by neoaggelos** [kubernetes/kubernetes#108118]
### What would you like to be added?

Add a new `--write-config-to` flag to kubelet, similar to [kube-scheduler](https://github.com/kubernetes/kubernetes/pull/62515) and [kube-proxy](https://github.com/kubernetes/kubernetes/pull/45908).

This flag can be used to render the kubelet configuration file from a set of command-line arguments. For example:

```bash
kubelet [--arg1 --arg2 --arg3] --write-config-to kubelet.conf
kubelet --config kubelet.conf
```

### Why is this needed?

In existing Kubernetes clusters we get lots of warnings like:

```
Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Flag --eviction-hard has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

But there is no easy way to generate a config file for existing clusters.

**Comment by neolit123** [comment]
xref https://github.com/kubernetes/kubernetes/issues/86843
looks like that issue rotted.

**Comment by endocrimes** [comment]
/triage accepted
/priority backlog

seems like a useful addition especially as we migrate more configuration

**Comment by kkkkun** [comment]
Great. Please go on.
/unassign
