### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget selector patchStrategy changed unexpectedly in 1.21 upgrade

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kubernetes#108137]
### What happened?

PDB was upgraded to v1 in 1.21. Despite the changelog saying that the behavior of the v1beta1 implementation should have stayed the same, it appears that the `patchStrategy` for the `selector` field was set to `replace`. I believe this is the change in question: https://github.com/kubernetes/kubernetes/pull/99290/files#diff-d4e188b2d9ba60f8c95c9a44c54d1e470c5796eccc4f28eccd446e6ed77f32b5R41

https://github.com/kubernetes/kubernetes/blob/f7ad5e91417dc4ac04bce1d1b15e11e6fed619d4/staging/src/k8s.io/api/policy/v1beta1/types.go#L41

When running `kubectl patch` with a starting config that had a `selector` with both a `matchExpressions` key and a `matchLabels` key, and a patch that had a `selector` with just a `matchLabels` key, the behavior between 1.20 and 1.21 differs. What we get is the `matchExpressions` key gets deleted, rather than merged with the patch's `matchLabels` key to make one unified selector.

```console
% kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
  namespace: my-ns
spec:
  maxUnavailable: 10%
  selector:
    matchLabels:
      app: my-app
```

### What did you expect to happen?

In 1.20, the behavior we'd get is thus, which is desirable for us because it lets us inject a base assumption about our PDBs into everything we do:

```console
% kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
  namespace: my-ns
spec:
  maxUnavailable: 10%
  selector:
    matchExpressions:
    - key: support
      operator: NotIn
      values:
      - "true"
    matchLabels:
      app: my-app
```

### How can we reproduce it (as minimally and precisely as possible)?

This is my repro case:

`vendor_config.json`

```json
{
  "apiVersion": "policy/v1beta1",
  "kind": "PodDisruptionBudget",
  "metadata": {
    "name": "my-pdb",
    "namespace": "my-ns"
  },
  "spec": {
    "maxUnavailable": "25%",
    "selector": {
      "matchLabels": {
        "app": "my-app"
      },
      "matchExpressions": [
        {
          "key": "support",
          "operator": "NotIn",
          "values": ["true"]
        }
      ]
    }
  }
}
```

`user_config.json`:

```json
{
  "apiVersion": "policy/v1beta1",
  "kind": "PodDisruptionBudget",
  "metadata": {
    "name": "my-pdb",
    "namespace": "my-ns"
  },
  "spec": {
    "maxUnavailable": "10%",
    "selector": {
      "matchLabels": {
        "app": "my-app"
      }
    }
  }
}
```

Compare by using the `kubectl patch` command from earlier in this report: `kubectl patch --local --output yaml --filename vendor_config.json --patch "$(cat user_config.json)"`

### Anything else we need to know?

I also brought this up in Slack: https://kubernetes.slack.com/archives/C2GL57FJ4/p1644947167394309

I don't think we want to switch to using just `--type merge` for PDBs, because that wouldn't solve issues where our users want to use `matchExpressions` without having to re-specify the `matchExpressions` from our base. Putting aside the fact that changing the behavior of the v1beta1 implementation was probably not intentional, it also seems undesirable to change how selectors work in general. I don't know how widely scoped this change will be across various resource types, too, so we're starting down quite a bit of nasty discovery time.

### Kubernetes version

<details>
This is the version I used to demonstrate my repro case, but I confirmed that this occurs even in kubectl v1.21.0.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

For my "happy" repro case, this is what the version output looks like:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS (the hard way)
</details>

**Comment by 2rs2ts** [comment]
@liggitt as requested, I am tagging you and @mortent on this one

**Comment by liggitt** [comment]
We should narrowly revert the strategic merge patch selector behavior for v1beta1 to match pre-1.21 behavior for backwards compatibility.

More broadly, it is unexpected for multiple actors to be writing to a single selector. The pre-1.21 strategic merge patch behavior for v1beta1 PDB has problems with data getting left in the selector incorrectly if the same user submits a patch with two keys, and then submits a patch with only a single key.

For that reason, server-side apply treats selector writes as owning the entire selector, and the v1 PodDisruptionBudget API will do the same for strategic merge patch.

**Comment by 2rs2ts** [comment]
>More broadly, it is unexpected for multiple actors to be writing to a single selector. The pre-1.21 strategic merge patch behavior for v1beta1 PDB has problems with data getting left in the selector incorrectly if the same user submits a patch with two keys, and then submits a patch with only a single key.

Would that be considered a bug in the implementation, or is there some race condition in patch application that I don't understand? Cuz if I were to sequentially apply patches with the old strategic merge, I would think the selector would just accumulate keys, which seems fine to me–but I can see how a race condition would turn it into chaos

**Comment by liggitt** [comment]
Accumulating unowned keys in selectors is considered harmful and likely undesired. server-side apply and strategic merge patch attempt to bring semantic understanding to help sand off sharp edges like that.

If you really want to tweak field-level things, jsonpatch can still do surgical insertion/appending/removal of specific fields.

**Comment by 2rs2ts** [comment]
Should we expect to use jsonpatch for anything that can have a selector, going forward? If it changed for PDBs then it should change for everything else, I would assume
