### ISSUE TITLE
local-up-cluster.sh: doesn't install CNI plugins if needed

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#108168]
### What happened?

Since we switched from dockershim to containerd, my cluster seems to come up okay but pods get stuck in ContainerCreating. When I investigated further, I found

```
  Warning  FailedCreatePodSandBox  16s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "dcd18bc5497553ab129df05324c262920bdaff0f4d906719756d8d2f0e91a292": failed to find plugin "loopback" in path [/usr/lib/cni]
```

Most dependencies of launching a cluster are installed automatically. In this case, it seems we don't get the CNI plugins installed and set up as needed.

/cc @adisky 
/sig node network

### What did you expect to happen?

Pod should have been created as expected.

### How can we reproduce it (as minimally and precisely as possible)?

Try to create pods on a system with local-up-cluster without CNI plugins already installed.

### Kubernetes version

<details>

```console
ehashman@fedora:~/src/k8s$ cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.3.34+b68063fce7abf6", GitCommit:"b68063fce7abf62c69c257610d93ed3eb100956a", GitTreeState:"clean", BuildDate:"2022-02-16T19:03:24Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.3.34+b68063fce7abf6", GitCommit:"b68063fce7abf62c69c257610d93ed3eb100956a", GitTreeState:"clean", BuildDate:"2022-02-16T19:03:24Z", GoVersion:"go1.17.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
ehashman@fedora:~/src/k8s$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
ehashman@fedora:~/src/k8s$ uname -a
Linux fedora 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
hack/local-up-cluster.sh
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
cc @dims, patron saint of local-up-cluster.sh 🙃

**Comment by ehashman** [comment]
@dims I think it's as simple as checking if `/usr/lib/cni/loopback` exists (or wherever it's looking for the CNI plugins) and if not, downloading the latest Linux version for the appropriate arch of https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz

**Comment by adisky** [comment]
@dims @ehashman already working on installing cni plugin for the local-up ci job
https://github.com/kubernetes/kubernetes/pull/108160

but if the script is running by user, doesn't we make an assumption that user will install cni plugins along with container runtime?

**Comment by adisky** [comment]
/assign
the local e2e job is now working, have to refine the script https://github.com/kubernetes/kubernetes/pull/108160
we are anyways installing cni for the ci job, will add a provision so that users can also install.

**Comment by SergeyKanzhelev** [comment]
similar bug: https://github.com/kubernetes/kubernetes/issues/106972
