### ISSUE TITLE
EndpointSlices can unexpectedly lose node name information after upgrading from v1beta1 to v1

### ISSUE THREAD

**Issue by robscott** [kubernetes/kubernetes#108196]
### What happened?

On the first update of an EndpointSlice using the v1 API, we drop deprecatedTopology with EndpointSlice strategy. Although we only do this if at least 1 endpoint has been modified, there is no guarantee that node name has been populated for all endpoints within the EndpointSlice. 

This is most noticeable if the first update using the v1 API is only adding endpoint(s). In that case the EndpointSlice controller does not update EndpointSlices and instead just adds the new endpoint(s). That will cause node names to be dropped from the deprecated topology field without having the newer node name field populated.

### What did you expect to happen?

Node name to be retained in deprecated topology until the new field was populated.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an EndpointSlice with the v1beta1 API.
2. Patch an endpoint in that EndpointSlice:
```
kubectl patch endpointslice foo-backend-custom --type='json' -p='[{"op":"add","path":"/endpoints/0/conditions/ready", "value":false}]' 
```

### Kubernetes version

This is most notable after upgrading a 1.20 cluster to 1.21, but can technically occur in any 1.21 or newer cluster.

### Cloud provider

Any

### OS version

Any

### Install tools

Any

### Container runtime (CRI) and and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by robscott** [comment]
I'm working on a fix for this, hoping to have it out later today.

/triage accepted
/sig network
/cc @thockin @aojea @tnqn

**Comment by liggitt** [comment]
I think this is better characterized as a controller bug, but https://github.com/kubernetes/kubernetes/pull/108197 is the safest mitigation I can think of in the short term, since we don't want to rewrite 100% of endpointslices on startup. Can you open a separate issue to work through the controller reconciliation so that v1 clients can depend on the nodeName field more reliably?
