### ISSUE TITLE
Install-WorkerServices should not set pod-infra-container-image as it is marked for deprecation

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#108144]
### What happened?

This code: https://github.com/kubernetes/kubernetes/blob/66445662ad7b65ffdb144b9665608f7b6a4b57a6/cluster/gce/windows/k8s-node-setup.psm1#L1051

should not set `pod-infra-container-image` as it was just marked for deprecation and has to set the `sandbox_image` instead on Contianerd

### What did you expect to happen?

code not setting this flag

### How can we reproduce it (as minimally and precisely as possible)?

code issue

### Anything else we need to know?

/sig windows
/sig cloud-provider

### Kubernetes version

master

### Cloud provider

any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@SergeyKanzhelev this has one effect currently. preventing the specified image from being garbage collected. (So we tell folks to specify the pause image in the containerd config toml and here - need to do both)

**Comment by SergeyKanzhelev** [comment]
Rephrased. Thank you!

**Comment by NikhilSharmaWe** [comment]
@dims and @SergeyKanzhelev Could you please inform about where `containerd` config toml is set in the repo, so that I can set the `sandbox_image` there instead.

**Comment by SergeyKanzhelev** [comment]
> @dims and @SergeyKanzhelev Could you please inform about where containerd config toml is set in the repo, so that I can set the sandbox_image there instead.

I'd say function `Configure_Containerd` in that file. @ibabou can you help identify what test will exercise this code to test it?

**Comment by ibabou** [comment]
> > @dims and @SergeyKanzhelev Could you please inform about where containerd config toml is set in the repo, so that I can set the sandbox_image there instead.
> 
> I'd say function `Configure_Containerd` in that file. @ibabou can you help identify what test will exercise this code to test it?

Yeah, it's here https://github.com/kubernetes/kubernetes/blob/master/cluster/gce/windows/k8s-node-setup.psm1#L1435

Tests covering this are the [sig-windows] suite ones, that creates Windows pools. For example, jobs like this have containerd configured to be used (KUBE_WINDOWS_CONTAINER_RUNTIME=containerd): https://k8s-testgrid.appspot.com/sig-windows-master-release#gce-windows-2019-containerd-master

**Comment by NikhilSharmaWe** [comment]
@ibabou I am not understanding the conversation about the tests, actually I have not worked much in this domain. Could you please elaborate on what we are trying to achieve and what steps we should take to achieve that.

Apologies for asking such a vague question.

**Comment by marosset** [comment]
`--pod-infra-container-image` is planned for deprecation in v1.27 because it is used by the garbage collector to know not to clean up this image. 
https://github.com/kubernetes/kubernetes/issues/106893

@SergeyKanzhelev / @ibabou  should we close this issue in favor of the one linked above?

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

either one of these two issues should be tracking this.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev Please inform that am I understanding correct -
> 
> * We need to remove `"--pod-infra-container-image=${env:INFRA_CONTAINER}",` from function `Start-WorkerServices`.

Yes

> * Add
> 
> ```
> $default_kubelet_args = @(`
>       "--pod-infra-container-image=${env:INFRA_CONTAINER}"
> )
> ```
> to function `Configure_Containerd_CniNetworking`.

No, in the `Configure_Containerd_CniNetworking` the setting `sandbox_image` needs to be specified in containerd config
