### ISSUE TITLE
kubectl apply --prune doesn't respect namespace boundaries and deletes other namespaces

### ISSUE THREAD

**Issue by tnozicka** [kubernetes/kubernetes#108161]
### What happened?

I run `kubectl -n scylla apply --server-side --prune --all -f <my_folder_for_scylla_namespace>` and even though it was scoped to a namespace it deleted all other namespaces.

### What did you expect to happen?

It should apply files just within the namespace this request is scoped to and prune any extra objects just in that namespace.

### How can we reproduce it (as minimally and precisely as possible)?

create multiple namespaces with kubectl apply and try using `apply --prune` on just one of them

### Anything else we need to know?

By the flag descriptions I'd assume it should have applied all the files in that namespace and prune any old resources that were removed from the folder.
```
--prune=false: Automatically delete resource objects, that do not appear in the configs and are created by either
apply or create --save-config. Should be used with either -l or --all.

--all=false: Select all resources in the namespace of the specified resource types.

-n, --namespace='': If present, the namespace scope for this CLI request
```
Note the part where `--all` says it will select all resources *in the namespace*, yet it pruned the other namespaces.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.1.649+874ce66d19a901", GitCommit:"874ce66d19a9015612a95ceffc32ef4f3f59c203", GitTreeState:"clean", BuildDate:"2022-01-18T14:17:09Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2-gke.300", GitCommit:"516d535fbe1cce83a6ac4dfbaa749b3c3ed499ac", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:03Z", GoVersion:"go1.17.5b7", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
GKE
</details>

**Comment by ardaguclu** [comment]
Hi @tnozicka.

I tested on local and `prune --all` worked as expected(just deleted resources in given namespace, etc.). Is it possible to give the exact steps what you did?. Thanks.

**Comment by tnozicka** [comment]
Hi @ardaguclu, 

thanks for looking into that. I'll work on making a reproducer with limited resources and get back to you. It's good that you have confirmed how it should work.

**Comment by eddiezane** [comment]
Please reopen if you are able to provide a reproduction case.

/close
