### ISSUE TITLE
Scaling a service to 0 replicas deletes EndpointSlice annotations and finalizers

### ISSUE THREAD

**Issue by acnodal-tc** [kubernetes/kubernetes#108267]
### What happened?

I added a finalizer and a couple of annotations to an EndpointSlice. When I scaled the parent service down to 0 replicas the EndpointSlice's annotations and finalizers were deleted.

### What did you expect to happen?

The EndpointSlice's annotations and finalizers don't change.

### How can we reproduce it (as minimally and precisely as possible)?

Create a deployment and service:
```
kubectl create deployment echoserver --image=k8s.gcr.io/echoserver:1.10
kubectl create service nodeport echoserver --tcp=8080:8080
```
Add an annotation to the endpointslice that belongs to the service:
```
kubectl annotate endpointslices echoserver-d5gtd foo=bar # "d5gtd" will be different in your case
```
Verify that the annotation can be read:
```
kubectl get endpointslices echoserver-d5gtd -o=jsonpath='{.metadata.annotations}'
{"foo":"bar"}
```
Scale the deployment down to zero replicas:
```
kubectl scale deployment echoserver --replicas=0
```
It takes a few seconds for the pod to terminate, but once it does the annotation is destroyed:
```
kubectl get endpointslices echoserver-d5gtd -o=jsonpath='{.metadata.annotations}' # produces no output
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-3+7ab10db7034594", GitCommit:"7ab10db7034594f057421b40f64481638350b80b", GitTreeState:"clean", BuildDate:"2022-01-26T21:56:08Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None, I'm running microk8s in a Vagrant VM on my development workstation.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux refectory 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Microk8s
</details>

### Container runtime (CRI) and and version (if applicable)

<details>
n/a
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n/a
</details>

**Comment by acnodal-tc** [comment]
/sig network

(apologies if this is wrong)

**Comment by aojea** [comment]
the endpointslices objects that are associated to a service, hence autogenerated, are ephemeral, they are (owned) created , updated or deleted by the endpoint slice controller manager

Why do you require to use finalizer and annotations on the endpoint slice?

/cc @robscott

**Comment by robscott** [comment]
Agree with @aojea here, this is intentional. EndpointSlices are labeled with a `managed-by` label to indicate which controller is responsible for managing them. In this case, the EndpointSlices would be managed by the EndpointSlice controller, so the expectation is that nothing else should modify them. It may make sense for us to update the EndpointSlice controller to go out of its way to immediately undo modifications to annotations/finalizers that had been added by other sources, but that would risk huge numbers of unnecessary updates. A safer option here may be to more clearly document how this is intended to work, because I don't think it's clear.

Out of curiosity, why were you adding a finalizer and annotations to an EndpointSlice?

**Comment by acnodal-tc** [comment]
Thank you for the speedy responses. I'm implementing the Gateway-SIG Gateway API so I need to track service endpoints so I can route traffic to them. Tracking EndpointSlices is more efficient than tracking Endpoints but I can do that instead.

I add my finalizer so my controller can clean up when a service/EndpointSlice is deleted. I add annotations with the data that identifies the slices in our system.

Agree that documentation is important here because this is different behavior than e.g., Endpoints, which allow third-party finalizers and annotations. The page at https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/ says "EndpointSlices provide a simple way to track network endpoints within a Kubernetes cluster. They offer a more scalable and extensible alternative to Endpoints." Without finalizers EndpointSlices can't really be used as an alternative to Endpoints.

**Comment by aojea** [comment]
> I add my finalizer so my controller can clean up when a service/EndpointSlice is deleted.

is not possible to base the logic on the Service instead of the EndpointSlices?

**Comment by acnodal-tc** [comment]
The service doesn't change in response to endpoint events (e.g., a change in the number of replicas) so it doesn't by itself provide enough info to implement a Gateway, but tracking Endpoints should. As the EndpointSlice page I referenced points out, tracking Endpoints is less scalable and extensible than tracking EndpointSlices but it looks like my only option at this point.

**Comment by aojea** [comment]
> The service doesn't change in response to endpoint events (e.g., a change in the number of replicas) so it doesn't by itself provide enough info to implement a Gateway, but tracking Endpoints should.

kube-proxy , per example, sets an informer on both Services and EndpointSlices, and reconciles based on both ... I think that the most common pattern for these kind of things is to watch both objects, there is a 1to1 mapping between services and endpoint slices, the slices carry a label `"kubernetes.io/service-name"` identifying the Service

**Comment by khenidak** [comment]
What is the reason for tracking endpoint slices @acnodal-tc? I understand that gateways route to services not slices.

**Comment by acnodal-tc** [comment]
I'm working on a Gateway that routes directly to endpoints for better performance.

**Comment by thockin** [comment]
I'm surprised that a finalizer would get overridden (I'd expect it to trip up the controller, but not get overridden).  @robscott We should make sure that is covered in tests!  For example, if a finalizer prevents deletion, kube-proxy should be smart enough to not include endpoints in a being-deleted slice. 

That said, those are managed resources and you can't expect to modify them safely.  There are no guarantees about the lifecycle of an individual slice when the controller is in charge of it.  A finalizer might prevent deletion, but it won't prevent the emptying of a slice, so I don't see how it can be useful.

Should we close this, @robscott, or do you want to keep it to track any testing of finalizer stuff?

**Comment by aojea** [comment]
finalizer keeps the slice hanging, repro:
```
$ kubectl run test --image httpd --port 80
$ kubectl expose pod test
$ kubectl get endpointslices
NAME         ADDRESSTYPE   PORTS   ENDPOINTS     AGE
kubernetes   IPv4          6443    172.18.0.2    7d4h
test-4llv6   IPv4          80      10.244.0.10   8s

$ kubectl patch endpointslices test-4llv6 --type json --patch='[ { "op": "add", "path": "/metadata/finalizers", "value": ["kubernetes.io/test"] } ]'
endpointslice.discovery.k8s.io/test-4llv6 patched
$ kubectl delete pod test
pod "test" deleted
$ kubectl get endpointslices
NAME         ADDRESSTYPE   PORTS     ENDPOINTS    AGE
kubernetes   IPv4          6443      172.18.0.2   7d4h
test-4llv6   IPv4          <unset>   <unset>      81s
kubectl delete service test
service "test" deleted
$ kubectl get endpointslices
NAME         ADDRESSTYPE   PORTS     ENDPOINTS    AGE
kubernetes   IPv4          6443      172.18.0.2   7d4h
test-4llv6   IPv4          <unset>   <unset>      102s
```


endpoint controller complains about ....
```
W0303 22:29:43.517999       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:29:44.518153       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:29:46.518809       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:29:50.519691       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:29:58.520754       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:30:14.521668       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:30:46.522733       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:31:50.522959       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:33:30.523739       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:35:10.523856       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:36:50.524524       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:38:30.525273       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:40:10.526088       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:41:50.527144       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:43:30.527713       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 22:45:10.528269       1 endpointslice_controller.go:311] Retry budget exceeded, dropping service "default/test" out of the queue: EndpointSlice informer cache is out of date
E0303 22:45:10.528304       1 endpointslice_controller.go:313] EndpointSlice informer cache is out of date
W0303 23:08:09.636978       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 23:08:10.637714       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 23:08:12.638103       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 23:08:14.286768       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 23:08:16.638902       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
W0303 23:08:32.639982       1 endpointslice_controller.go:306] Error syncing endpoint slices for service "default/test", retrying. Error: EndpointSlice informer cache is out of date
```

**Comment by aojea** [comment]
> W0303 22:45:10.528269       1 endpointslice_controller.go:311] Retry budget exceeded, dropping service "default/test" out of the queue: EndpointSlice informer cache is out of date

it is dropped .... eventually

> W0303 22:45:10.528269       1 endpointslice_controller.go:311] Retry budget exceeded, dropping service "default/test" out of the queue: EndpointSlice informer cache is out of date

**Comment by thockin** [comment]
how?  Does someone clear the finalizer?

**Comment by aojea** [comment]
> 

Ahh, no, sorry, the slice remains ... The controller gives up

**Comment by thockin** [comment]
@robscott Do we want to follow-up on this and make controller(s) more graceful in the face of this (unusual) behavior?

Maybe we should open a net-new bug for "Endpoint-related controllers and proxies should ignore terminating Endpointses and EndpointSlices" ?

**Comment by robscott** [comment]
@thockin good idea, I've created #108779 to track that. I think we can likely close this in favor of that bug.

**Comment by aojea** [comment]
> @thockin good idea, I've created #108779 to track that. I think we can likely close this in favor of that bug.

/close
Let's move the conversion there then :)
