### ISSUE TITLE
[Failing test] capg-conformance-main-ci-artifacts

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#108223]
### Which jobs are failing?

release-master-informing
* [capg-conformance-main-ci-artifacts](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts)

### Which tests are failing?

* periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts.Overall
* capg-e2e.Conformance Tests conformance-tests

### Since when has it been failing?

2022-02-16 13:24 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts

### Reason for failure (if possible)

```

capg-e2e: Conformance Tests conformance-tests expand_less

/home/prow/go/src/sigs.k8s.io/cluster-api-provider-gcp/test/e2e/conformance_test.go:96
Timed out after 1800.001s.
{
  "metadata": {
    "creationTimestamp": null
  },
  "spec": {
    "version": "",
    "machineTemplate": {
      "metadata": {},
      "infrastructureRef": {}
    },
    "kubeadmConfigSpec": {}
  },
  "status": {
    "replicas": 0,
    "updatedReplicas": 0,
    "readyReplicas": 0,
    "unavailableReplicas": 0,
    "initialized": false,
    "ready": false
  }
}

Expected
    <string>: KubeadmControlPlane
to match fields: {
.Status.Ready:
	Expected
	    <bool>: false
	to be true
}

/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.1.0-beta.2.0.20220211164825-cca725c1ca50/framework/controlplane_helpers.go:169
```

### Anything else we need to know?

Seems to relate to the job [capg-conformance-v1beta1-ci-artifacts](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1beta1-ci-artifacts) which also fails right now.

### Relevant SIG(s)

/sig network
/sig cloud-provider
/kind failing-test
cc @kubernetes/ci-signal

**Comment by leonardpahlke** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/108222

**Comment by lauralorenz** [comment]
These failures no longer appear. xref for fix in the comment on capg-conformance-v1beta1-ci-artifacts https://github.com/kubernetes/kubernetes/issues/108222#issuecomment-1062529301

/close
