### ISSUE TITLE
GCE/GKE: test/e2e/restart.go - MIG rolling update with identical template will not restart nodes

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#10826]
test/e2e/restart.go, func restartNodes, assumes that MIG rolling update on GCE will cause node restart.

However, there is a feature of MIG rolling update (currently broken) that skips update if the new instance template is the same as the old one.
The feature is supposed to work quite soon, so the test will not test anything (reboot will not be performed).

A workaround may be to create an identical instance template with a different name.

By the way, the current name `restartNodes` is misleading. It should be `recreateNodes`.

cc @mbforbes @quinton-hoole

**Comment by mbforbes** [comment]
Hi Marek,

Was this changed recently? When we tried this originally it worked. Now, I just tried doing a rolling update to the same template, and it immediately fails with status "PAUSED" and status message "Errors: unknown".

The name `restartNodes` was chosen to attempt to be future-provider-agnostic, though I agree `recreateNodes` is better.

**Comment by mbforbes** [comment]
Actually, I'm trying it now, and it definitely sometimes works (recreates the instances). If this functionality isn't expected to work (or isn't supported) we can switch this to the equivalent MIG recreate-nodes call. I'll do this.

**Comment by marekbiskup** [comment]
I've heard that some two months ago MIG update would not recreate new nodes if the template was the same. Then they changed it and instances were recreated (this is when you wrote the test). I think it is considered a bug. And they are going to fix this bug quite soon.
So in a week or two (or maybe more - I don't know their release cycle), instances will not be recreated.

(sorry for incomprehensible description of this issue - I'm correcting it now).

**Comment by marekbiskup** [comment]
@mbforbes , I think your error is not related to MIG update - currently instances should be recreated (i.e. the error in MIG rolling update is not fixed).
The error may be fixed around Monday (but maybe later - even 2 weeks).

**Comment by mbforbes** [comment]
Ack—thanks for the extra detail! I'll just switch this test to `gcloud preview managed-instance-groups recreate-instances` and we can stop worrying about the timing. We'll switch this in GKE too. Thanks again, I really appreciate you filing this!

**Comment by mbforbes** [comment]
(And by switch I mean just turn off self-upgrades.)

**Comment by mbforbes** [comment]
@roberthbailey is this v1?

**Comment by roberthbailey** [comment]
The referenced PR was a refactoring and Github got a bit confused. This issue isn't closed.

**Comment by roberthbailey** [comment]
I don't think we _need_ a test to recreate the MIG before v1.0 (although if it gets done before the freeze I don't see why we wouldn't merge it).

**Comment by mbforbes** [comment]
I'm leaving the project, so reassigning to... @marekbiskup! Have fun!

**Comment by spxtr** [comment]
Fixed forever ago.
/close
