### ISSUE TITLE
kubernetes Cluster add capabilities above 1.21.x do not take effect

### ISSUE THREAD

**Issue by RottenLeaf24** [kubernetes/kubernetes#108247]
### What happened?

I want execute "mount" cmd in start script,So I need add the "SYS_ADMIN" to pod capabilities.The yaml file like following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          mount -o remount rw /proc/sys
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w fs.file-max=1048576
          sysctl -w fs.inotify.max_user_instances=16384
          sysctl -w fs.inotify.max_user_watches=524288
          sysctl -w fs.inotify.max_queued_events=16384
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
  ```
But I get the error: ```mount: mounting rw on /proc/sys failed: Permission denied```
The current kubernetes cluster version is v1.21.0,Then I do the same operation in another cluster with version v1.20.12 and get the same error.It looks like add capabilities failed.
Finally,I did the same operation in a cluster with version v1.16.9 and it worked directly.

### What did you expect to happen?

Can be successful add capabilities in kubernetes with version 1.21.x.

### How can we reproduce it (as minimally and precisely as possible)?

You only need to execute the following yaml file on a kubernetes cluster with a version greater than v1.20.x.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          mount -o remount rw /proc/sys
          sysctl -w net.core.somaxconn=65535
          sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sysctl -w fs.file-max=1048576
          sysctl -w fs.inotify.max_user_instances=16384
          sysctl -w fs.inotify.max_user_watches=524288
          sysctl -w fs.inotify.max_queued_events=16384
        image: busybox
        imagePullPolicy: IfNotPresent
        name: init-sysctl
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
  ```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-dispatcher", GitCommit:"f5757a1dee5a89cc5e29cd7159076648bf21a02b", GitTreeState:"clean", BuildDate:"2020-02-06T03:29:33Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.12-gke.1500", GitCommit:"d32c0db9a3ccd0ac73b0b3abd0532505217b376e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:02Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

```
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.9-aliyun.1", GitCommit:"8bce9db55473d8e27e849fb7b5f8dbf14014ae8f", GitTreeState:"clean", BuildDate:"2021-12-24T07:56:49Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
v1.21.0 -- custom cluster
v1.20.12-gke.1500 -- GKE(GCP)
v1.16.9-aliyun.1 -- AlibabaCloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
I could not reproduce this in v1.22.3

**Comment by RottenLeaf24** [comment]
> I could not reproduce this in v1.22.3

Thanks for your help,Maybe this is a security configuration problem,that  I didn't see!

**Comment by SergeyKanzhelev** [comment]
@RottenLeaf24 can you please tell what runtime is being used in different versions

/triage needs-information

**Comment by 249043822** [comment]
I reproduced this in Linux kernal 5.4(with AppArmor enabled) + containerd1.6 + kubernetes1.22.3, and i found that it was restricted by apparmor, so I changed the configuration of containerd, then it's ok.

/etc/containerd/config.toml
```
  [plugins."io.containerd.grpc.v1.cri"]
    disable_apparmor = true
```

**Comment by RottenLeaf24** [comment]
> @RottenLeaf24 can you please tell what runtime is being used in different versions
> 
> /triage needs-information

| provider  | version | runtime | Does SYS_ADMIN take effect? |
| ------------- | ------------- | ------------- | ------------- |
| custom  | v1.21.2  | containerd://1.4.6  | False  |
| GCP | 1.20.12-gke.1500  | docker://20.10.3  | False  |
| aliyun | v1.16.9-aliyun.1  | docker://19.3.5  | True  |

**Comment by RottenLeaf24** [comment]
> I reproduced this in Linux kernal 5.4(with AppArmor enabled) + containerd1.6 + kubernetes1.22.3, and i found that it was restricted by apparmor, so I changed the configuration of containerd, then it's ok.
> 
> /etc/containerd/config.toml
> 
> ```
>   [plugins."io.containerd.grpc.v1.cri"]
>     disable_apparmor = true
> ```

Thanks for your answer, it is indeed caused by AppArmor
