### ISSUE TITLE
rename SchedulerCache to Cache in Scheduler

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#108240]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/blob/f0d5ea1e1d4d43cd5caac92800207fcd2a62538c/pkg/scheduler/scheduler.go#L67-L70

We are doing some refactor works in https://github.com/kubernetes/kubernetes/pull/107135, and I found `SchedulerCache` seems redundant, would like to rename `SchedulerCache` to `Cache`

### Why is this needed?

`SchedulerCache` seems redundant as a field of `Scheduler`.

**Comment by kinderyj** [comment]
same issue

**Comment by Huang-Wei** [comment]
> I found SchedulerCache seems redundant, would like to rename SchedulerCache to Cache

You're right. It's against common Go naming practices. Please go rename it.
