### ISSUE TITLE
Kubelet service cannot bind port 10250 on both the ipv4 and ipv6 network ips in Dual stack k8s setup.

### ISSUE THREAD

**Issue by kumaravanish** [kubernetes/kubernetes#108248]
### What happened?

The parameter `address` in the kubelet `/var/lib/kubelet/config.yaml`  enables to bind the kubelet to a node ip .  
It’s the parameter which accepts single value, that means only one IP could be provided. 
In case of dual stack environment kubelet cannot listen on both the ipv4 and ipv6 network ips.

Following output is from the case where kubelet listens on ipv6 node's ip in a dualstack environment.

```console
kubectl logs node-cert-exporter-h74s2 -n monitoring
Error from server: Get "[https://<ipv4NodeIp>:10250/containerLogs/monitoring/node-cert-exporter-h74s2/node-cert-exporter":](https://<ipv4NodeIp>:10250/containerLogs/monitoring/node-cert-exporter-h74s2/node-cert-exporter%22:) dial tcp <ipv4NodeIp>:10250: connect: connection refused
```

### What did you expect to happen?

kubelet should listen to both the network node ips in case of dual stack. This will enable communication to the kubelet on  both the networks.

### How can we reproduce it (as minimally and precisely as possible)?

1. Update the `address: <node ip>` in the `/var/lib/kubelet/config.yaml` 
2.  Restart the kubelet service.
3.  ss -anlp | grep 10250

### Anything else we need to know?

Kubeapiserver with the configuration `--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname`  always tries to contact the kubelet on the ipv4 network ip ( **ipv4,  dualstack deployment**) with the exception in **ipv6 deployment**.  Kubeapiserver is unable to make calls to the kubelet where the kubelet listens on the ipv6 node ip in the dual stack environment.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"6abac1505370282a9583329dd35622792b60e449", GitTreeState:"clean", BuildDate:"2022-01-10T12:53:58Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"6abac1505370282a9583329dd35622792b60e449", GitTreeState:"clean", BuildDate:"2022-01-10T12:44:17Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MadhavJivrajani** [comment]
/sig node
/sig network
(maybe?)

**Comment by aojea** [comment]
kubelet accepts a comma separated list of ips in `--node-ip` for dual-stack


> --node-ip string
>   IP address (or comma-separated dual-stack IP addresses) of the node. If unset, kubelet will use the node's default IPv4 address, if any, or its default IPv6 address if it has no IPv4 addresses. You can pass '::' to make it prefer the default IPv6 address rather than the default IPv4 address.

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

It was implemented by 
https://github.com/kubernetes/kubernetes/pull/95239/commits/75242fce7aa8a8f9e703b8602587900ca5aaf937

**Comment by kumaravanish** [comment]
@aojea : Thank you for the information. However, i am still thinking why the kubelet should not listen on both the network interfaces?

Argument --node-ip, no doubt allows option to communicate over a preferred network by choosing one. But additional considerations are needed like --cloud-provider parameter could not be used together. Pasting error just for the information.

`Failed to run kubelet" err="failed to run Kubelet: dual-stack --node-ip \"2001::3,10.0.10.8\" not supported when using a cloud provider"`

**Comment by aojea** [comment]
If your cluster is single-stack and you don't use cloud provider , --node-ip must only listen in one IP family,
If your cluster is single-stack and you don't use cloud provider , --node-ip must configured with the corresponding ip families, and listen on both.
If you use a cloud provider, I have doubts about which IP kubelet is using to bind, what case/s are you referring to?

**Comment by kumaravanish** [comment]
In my case, the cloud provider is `openstack` and the stack is a `dualstack`. My kubelet is listening on the ipv6 node ip ( which comes from `--address` kubelet option). **By default kubelet communication is happening on the ipv4** so as to alter this behavior i have to configure kubelet with `--node-ip=<nodeIPv6>,<nodeIPv4>` which solves the communication issue. But i am unable to configure both  `node-ip`  and `cloud-provider` options simultaneously. Getting the below error:

`Failed to run kubelet" err="failed to run Kubelet: dual-stack --node-ip \"<nodeIPv6>,<nodeIPv4>\" not supported when using a cloud provider"`

Please let me know if more details needed.

**Comment by kumaravanish** [comment]
@aojea Rightly `--address 0.0.0.0`  results in exposing kubelet service on all the interfaces, Also, this is a default behavior when this option is not even passed . 

Below are some concerns:
1. Exposing kubelet service on all network interfaces  is not desirable ( some interfaces can be on external networks, a major security risk).
2. Documentation for the `--node-ip` `--address`  could be  improved.
3. There's no option[s] which covers the below scenario for the dualstack.
    --node-ip=<nodeIPv6>, <nodeIPv4> - Enables default communication over ipv6 in dualstack.
    --address=<nodeIPv6> - Enable kubelet service to listen on ipv6 ip network.
    --cloud-provider=<external/openstack> - Cloud controller options in case stack comes from a cloud.

**Comment by kumaravanish** [comment]
@aojea : As per the documentation [https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/), option `cloud-provider` was to be removed in v1.23 but looks like it is still valid in v1.23, since i am doing all the tests on the k8s v1.23.

In this case, Probably documentation could be updated as per the code behaviour. 
I feel this need to be tagged as a bug. Please share your inputs.

**Comment by neolit123** [comment]
> --cloud-provider string
> --
>   | The provider for cloud services. Set to empty string for running with no cloud provider. If set, the cloud provider determines > the name of the node (consult cloud provider documentation to determine if and how the hostname is used). (DEPRECATED: > will be removed in 1.23, in favor of removing cloud provider code from Kubelet.)

the effort to remove the --cloud-provider flag is valid.
the alternative is this interface:
https://git.k8s.io/cloud-provider

probably the flag did not get removed on time for 1.23.
#sig-cloud-provider on k8s slack, might know more about this.

/sig cloud-provider

**Comment by aojea** [comment]
> 3\. There's no option[s] which covers the below scenario for the dualstack.
>     `--node-ip=<nodeIPv6>, <nodeIPv4>` - Enables default communication over ipv6 in dualstack.
>     `--address=<nodeIPv6>` - Enable kubelet service to listen on ipv6 ip network.
>     `--cloud-provider=<external/openstack>` - Cloud controller options in case stack comes from a cloud.

:thinking: that should work, it works in aws

Can you check the order of the Node addresses returned in `kubect get node -o yaml`  (you can use some filtering with json or jq to get only the addresses)

The cloud provider should return the IPv6 first, (if that is the main IP family of the cluster), the order is important, kubelet will pick the first address returned by the cloud provider.

xref https://github.com/kubernetes/cloud-provider-aws/pull/230#issuecomment-902302278

oooor you may be hitting this bug https://github.com/kubernetes/kubernetes/pull/107736

**Comment by kumaravanish** [comment]
> 3. There's no option[s] which covers the below scenario for the dualstack.
>    `--node-ip=<nodeIPv6>, <nodeIPv4>` - Enables default communication over ipv6 in dualstack.
>    `--address=<nodeIPv6>` - Enable kubelet service to listen on ipv6 ip network.
>    `--cloud-provider=<external/openstack>` - Cloud controller options in case stack comes from a cloud.

I meant , the three options are not working all together in v1.23 for the dualstack only, kubelet service failed to start. Further checking the journalctl logs shows the below error.
`Failed to run kubelet" err="failed to run Kubelet: dual-stack --node-ip \"<nodeIPv6>,<nodeIPv4>\" not supported when using a cloud provider"`

So, i removed `--cloud-provider` and tested with below configuration successfully. 
`--node-ip=<nodeIPv6>, <nodeIPv4>` - The order of the parameter values decides the default communication ip family in dualstack. "kubectl get nodes -o wide" also shows expected preferred node ip address.
`--address=<nodeIPv6>` - Enable kubelet service to listen on ipv6 ip network.

**Summary**: I am unable to use the `--cloud-provider`,`--node-ip` ,  `--address` all together, **ONLY** in the dualstack case (**i believe somewhere parsing of the values in `--node-ip`  decides  wether its a dualstack or not**). It is reproducible easily.
Moreover, still no clarity, whether this parameter `--cloud-provider` is really performing some tasks in the background or disabled/removed in v1.23.

**Comment by aojea** [comment]
--address is the address the process binds, there is no more history there and the description of the flag is accurate.

Then, kubelet needs a NodeIP, it can be one or two, for dual stack, order matters.
If you use a cloud provider, the kubelet NodeIP is assigned by the cloud provider , order matters and some cloud provider.doesnt do this right.

The flag --node-ip is used on the absence of a cloud provider,

**Comment by kumaravanish** [comment]
> The flag --node-ip is used on the absence of a cloud provider, the description of the flag is accurate [#108248 (comment)](https://github.com/kubernetes/kubernetes/issues/108248#issuecomment-1047537266)
> 
> That is a complex topic, absolutely it is, we have some references here to what I'm saying https://kubernetes.io/docs/concepts/services-networking/dual-stack/

Thank you. The lines provides clarity  "when there is no --cloud-provider the administrator can pass a comma-separated pair of IP addresses via --node-ip to manually configure dual-stack". 

It would be good to know about the current status of `--cloud-provider` kubelet flag in v1.23. Is it **disabled/Just deprecated/ removed/ obsolete.**

> the effort to remove the --cloud-provider flag is valid. the alternative is this interface: https://git.k8s.io/cloud-provider
> 
> probably the flag did not get removed on time for 1.23. #sig-cloud-provider on k8s slack might know more about this.
> 
> /sig cloud-provider

**Comment by aojea** [comment]
> Thank you. The lines provides clarity "when there is no --cloud-provider the administrator can pass a comma-separated pair of IP addresses via --node-ip to manually configure dual-stack".

@andrewsykim can you help us here?

**Comment by kumaravanish** [comment]
> > Thank you. The lines provides clarity "when there is no --cloud-provider the administrator can pass a comma-separated pair of IP addresses via --node-ip to manually configure dual-stack".
> 
> @andrewsykim can you help us here?

Hi, I have got the confirmation from the # sig-cloud-provider that the `--cloud-provider` option is still valid in v1.23. Also, i cross validated with the kubelet code.
I raised a bug request so as to correct the details on the  v1.23 documentation. If needed, i can pick up and make the changes since its a small change. Please see link to a bug request.
https://github.com/kubernetes/kubernetes/issues/108323

**Comment by elmiko** [comment]
just adding a note here, i am going to look at updating the documentation to be more clear about the deprecation of the `--cloud-provider` flag.
