### ISSUE TITLE
[Failing test] capg-conformance-v1beta1-ci-artifacts

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#108222]
### Which jobs are failing?

release-master-informing
* [capg-conformance-v1beta1-ci-artifacts](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1beta1-ci-artifacts)

### Which tests are failing?

* periodic-cluster-api-provider-gcp-conformance-v1beta1-ci-artifacts.Overall
* capg-e2e.Conformance Tests conformance-tests

### Since when has it been failing?

2022-02-16 13:26 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-v1beta1-ci-artifacts

### Reason for failure (if possible)

```
capg-e2e: Conformance Tests conformance-tests expand_less

/home/prow/go/src/sigs.k8s.io/cluster-api-provider-gcp/test/e2e/conformance_test.go:96
Timed out after 1800.000s.
Expected
    <bool>: false
to be true
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.0.4/framework/controlplane_helpers.go:167
```

### Anything else we need to know?

Seems to relate to the job [capg-conformance-main-ci-artifacts](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts) which also fails right now.

### Relevant SIG(s)

/sig network
/sig cloud-provider
/kind failing-test
cc @kubernetes/ci-signal

**Comment by neolit123** [comment]
/remove-sig cloud-provider
/sig cluster-lifecycle

capg is a sig cl subproject.

**Comment by lauralorenz** [comment]
These failures no longer appear; tracking backwards they seem to have been fixed by https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/502 and then when they reappeared later were fixed by https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/531.

/close
