### ISSUE TITLE
Unable to restore volume specs in ASW when attach/detach controller starts

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#108221]
### What happened?

Normally, DSW and ASW data are restored after the attach/detach controller is started. 
Get volumes from node.Status.VolumesAttached and add them to ASW. At this point, VolumeSpec is nil.
It then goes through all the pods, adds the volumes in the pods that need to be attached to the DSW, and replaces the volumespec in the ASW with the correct volumes found on the pods.
[https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go](url)
```
			attachState := adc.actualStateOfWorld.GetAttachState(volumeName, nodeName)
			if attachState == cache.AttachStateAttached {
				klog.V(10).Infof("Volume %q is attached to node %q. Marking as attached in ActualStateOfWorld",
					volumeName,
					nodeName,
				)
				devicePath, err := adc.getNodeVolumeDevicePath(volumeName, nodeName)
				if err != nil {
					klog.Errorf("Failed to find device path: %v", err)
					continue
				}
				err = adc.actualStateOfWorld.MarkVolumeAsAttached(volumeName, volumeSpec, nodeName, devicePath)
				if err != nil {
					klog.Errorf("Failed to update volume spec for node %s: %v", nodeName, err)
				}
			}
```

But I have a problem:  
All nodes of k8s cluster are restarted and pods are evicted. When ADcontroller starts, the pod has not been successfully attached on the new node, so the node of the pod's volume stored in ASW is still the old node, which is inconsistent with the pod's nodename. According to Code logic, volume spec in AWS will not replace, always nil.

**A full description of the problem I'm having is below：**
There is a k8s cluster with 3 masters and 2 nodes. There is a running pod1:ftpv3-5b688be6-a73c-488d-846a-155a3a32fedd-0 on node:193.168.0.5 that uses an attachable volume1:131ab496-40a5-47a0-8011-4554779c568.
Restart all nodes of the k8s cluster. Then it was found that pod1 is not running due to the mount failure and can't be recovered. The mount failed because the volumeattach could not be obtained during waitforattach.

**Analyze the problem through the log, as follows:**
1. At the beginning, pod1 is running, and the volume1 used by pod1 is attached to node5.

2. Restart all nodes of the k8s cluster. When node5 restarts, pod1 is evicted, so volume1 starts to detach from node5, but detaching volume1 fails. The reason is: csi-attacher does not receive the event of volumeattachment after waiting for 2m, and returns detach failure. The volume1/node5 for this pod was not removed from ASW due to detach failure, and volume was not remove from node.status.volumeattached, but VA was removed by csi-attacher during detach.
```
I0216 08:29:31.474989       1 event.go:291] "Event occurred" object="opcs/ftpv3-5b688be6-a73c-488d-846a-155a3a32fedd-0" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Marking for deletion Pod opcs/ftpv3-5b688be6-a73c-488d-846a-155a3a32fedd-0"
I0216 08:39:52.455014       1 reconciler.go:203] attacherDetacher.DetachVolume started for volume "nil" (UniqueName: "kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688") on node "193.168.0.5" 
E0216 08:41:52.497915       1 csi_attacher.go:500] kubernetes.io/csi: attachdetacher.WaitForDetach timeout after 2m0s [volume=131ab496-40a5-47a0-8011-4554779c5688; attachment.ID=csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24]
E0216 08:41:52.498031       1 nestedpendingoperations.go:319] Operation for "{volumeName:kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688 podName: nodeName:193.168.0.5}" failed. No retries permitted until 2022-02-16 08:41:52.997986724 +0800 CST m=+321.870058193 (durationBeforeRetry 500ms). Error: "DetachVolume.Detach failed for volume \"nil\" (UniqueName: \"kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688\") on node \"193.168.0.5\" : attachdetachment timeout for volume 131ab496-40a5-47a0-8011-4554779c5688"
```
3. Since nodes are restarted in sequence, during the detach process, pod1 has been evicted to other node and then back to the node5 again. When pod1 re-created on node5, volume1/node5 was added to DSW. Since volume1/node5 is stored in both DSW and ASW, both detach and attach will no longer be executed.

4. Additionally, the attach/detach controller periodically calls` rc.attacherDetacher.VerifyVolumesAreAttached` to check the attached status of the volume and fixes exceptions.
[https://github.com/kubernetes/kubernetes/blob/8dd52e6c5dcd8068ee1080a4b7dcabd0a140a5ee/pkg/controller/volume/attachdetach/reconciler/reconciler.go](url)
```
func (rc *reconciler) syncStates() {
	volumesPerNode := rc.actualStateOfWorld.GetAttachedVolumesPerNode()
	rc.attacherDetacher.VerifyVolumesAreAttached(volumesPerNode, rc.actualStateOfWorld)
}
```
 However, when attach/detach controller starts, the pod1 has been evicted, recreated on another node, but has not been successfully attached on the new node. So attachVolume.nodesAttachedTo in ASW only has node5, no new nodes. Checking the attached status of volume/pod.nodename in ASW will return false. Update volumespec not executed. The volume.spec is always nil. ` rc.attacherDetacher.VerifyVolumesAreAttached` fails.
`E0216 08:38:20.647821       1 operation_executor.go:711] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688`

### What did you expect to happen?

Volume specs in ASW are replace with the correct ones found on pods after attach/detach controller is started.

### How can we reproduce it (as minimally and precisely as possible)?

All nodes of k8s cluster start and pods are evicted.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.19.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by NikhilSharmaWe** [comment]
@houjun41544 I think the volume spec is being updated [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/attachdetach/attach_detach_controller.go#L479).

Could you please elaborate the issue if I am understanding incorrect here.

**Comment by houjun41544** [comment]
Before volume spec is updated, `adc.actualStateOfWorld.GetAttachState(volumeName, nodeName)` will check the attach state of volume/pod.nodename in ASW.
```
			attachState := adc.actualStateOfWorld.GetAttachState(volumeName, nodeName)
			if attachState == cache.AttachStateAttached {
```
The k8s cluster with this problem, before ADcontroller starts, the pod has been evicted, recreated on another node, but has not been successfully mounted on the new node. So attachVolume.nodesAttachedTo in ASW only has old nodes, no new nodes. Checking the attached status of volume/pod.nodename in ASW will return false. Update not executed.

**I've added the description of the original question in " What happened? "**

**Comment by NikhilSharmaWe** [comment]
@houjun41544 So we need to change the attached nodes to the volume from the old nodes to the new nodes. Am I understanding correct here ?

Do you have any idea about what should be done for achieving this ? please inform. I would like to work for fixing this issue.

**Comment by houjun41544** [comment]
Before volume spec is updated in `populateDesiredStateOfWorld()`, I think it is only necessary to check if the volumeName is in ASW and if this volume has an attached node, no need to check if pod.nodename is in the attached node. Am i right？
Have other ideas？
@NikhilSharmaWe @jsafrane @msau42

**Comment by houjun41544** [comment]
When detach，[csi_attacher](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L411) 
 calls `c.k8s.StorageV1().VolumeAttachments().Delete` to deletes VA first, then calls `waitForVolumeDetachmentWithLister` to check VA deletion .  
```
	if err := c.k8s.StorageV1().VolumeAttachments().Delete(context.TODO(), attachID, metav1.DeleteOptions{}); err != nil {
		if apierrors.IsNotFound(err) {
			// object deleted or never existed, done
			klog.V(4).Info(log("VolumeAttachment object [%v] for volume [%v] not found, object deleted", attachID, volID))
			return nil
		}
		return errors.New(log("detacher.Detach failed to delete VolumeAttachment [%s]: %v", attachID, err))
	}

	klog.V(4).Info(log("detacher deleted ok VolumeAttachment.ID=%s", attachID))

	// Attach and detach functionality is exclusive to the CSI plugin that runs in the AttachDetachController,
	// and has access to a VolumeAttachment lister that can be polled for the current status.
	return c.waitForVolumeDetachmentWithLister(volID, attachID, c.watchTimeout)
```
This issue, detach failure  is due to the failure of `waitForVolumeDetachmentWithLister`, so VA has beed deleted . `waitForVolumeDetachmentWithLister` failure may be caused by kube-apiserver exception.
At that time the csi plugin observed the removal of the VA and then successfully detached the volume from the node.

**Comment by gnufied** [comment]
@houjun41544 that deletion does not really deletes the object from API server.The VA has a finalizer, which must be removed after successful detach of volume from node and then and only then VA is deleted. So we need to find out, how is extenal-attacher removing the finalizer if detach is failing from the node.

**Comment by houjun41544** [comment]
I understand what you mean. 

ADcontroller started detach at 08:39.
```
I0216 08:29:31.474989       1 event.go:291] "Event occurred" object="opcs/ftpv3-5b688be6-a73c-488d-846a-155a3a32fedd-0" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Marking for deletion Pod opcs/ftpv3-5b688be6-a73c-488d-846a-155a3a32fedd-0"
I0216 08:39:52.455014       1 reconciler.go:203] attacherDetacher.DetachVolume started for volume "nil" (UniqueName: "kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688") on node "193.168.0.5" 
E0216 08:41:52.497915       1 csi_attacher.go:500] kubernetes.io/csi: attachdetacher.WaitForDetach timeout after 2m0s [volume=131ab496-40a5-47a0-8011-4554779c5688; attachment.ID=csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24]
E0216 08:41:52.498031       1 nestedpendingoperations.go:319] Operation for "{volumeName:kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688 podName: nodeName:193.168.0.5}" failed. No retries permitted until 2022-02-16 08:41:52.997986724 +0800 CST m=+321.870058193 (durationBeforeRetry 500ms). Error: "DetachVolume.Detach failed for volume \"nil\" (UniqueName: \"kubernetes.io/csi/opdisk.csi.openpalette.org^131ab496-40a5-47a0-8011-4554779c5688\") on node \"193.168.0.5\" : attachdetachment timeout for volume 131ab496-40a5-47a0-8011-4554779c5688"
```
And from the external-attacher log, external-attacher removed the finalizer at 08:50, as follows. 
The external-attacher may have some exceptions and was not started until 8:49.
```
I0216 08:49:41.816647       1 controller.go:198] Started VA processing "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:49:41.816653       1 csi_handler.go:216] CSIHandler: processing VA "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:49:41.816657       1 csi_handler.go:267] Starting detach operation for "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:49:41.816710       1 csi_handler.go:274] Detaching "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.674385       1 csi_handler.go:575] Detached "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.674432       1 util.go:79] Marking as detached "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.681034       1 round_trippers.go:443] PATCH https://10.254.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24/status 200 OK in 6 milliseconds
I0216 08:50:07.693419       1 round_trippers.go:443] PATCH https://10.254.0.1:443/apis/storage.k8s.io/v1/volumeattachments/csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24 200 OK in 12 milliseconds
I0216 08:50:07.693516       1 util.go:105] Finalizer removed from "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.693527       1 csi_handler.go:287] Fully detached "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.693534       1 csi_handler.go:232] CSIHandler: finished processing "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.693557       1 controller.go:198] Started VA processing "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24"
I0216 08:50:07.693574       1 controller.go:205] VA "csi-841b09548dbe5e57220ffa7ab34398a71821b25459d6725e3d3afe87e5148f24" deleted, ignoring
```

**Comment by jsafrane** [comment]
I have troubles understanding what's happening here. When kube-controller-manager is restarted, it indeed restores its state from `node.status.volumesAttached`. And there are two possibilities:

1. Either there is a pod that needs the volume and then its spec is used to restore ASW when A/D controller starts and both ASW and DSW have correct data.
2. 
3. Or there is no pod that needs the volume and A/D controller is fine with `nil` and initiates detach. As you wrote, this (or some previous) detach succeeds and VA is deleted. At this point, A/D controller should remove the attachment from ASW and populate fresh ASW from a new incoming pod.

But what you see is that the volume is detached (VA is deleted), but A/D controller keeps it in ASW. How could that happen?

Is it possible that the new pod was created just after `populateDesiredStateOfWorld()` and before the first reconciliation? While it's possible, it's extremely unlikely. And then it would be better to update ASW in `ProcessPodVolumes`, when ASW already has the volume with `nil` spec.

**Comment by houjun41544** [comment]
@jsafrane 
At that time, the csi plugin was abnormal, and the A/D controller failed to detach the volume due to waiting for the volume detach timeout`(kubernetes.io/csi: attachdetacher.WaitForDetach timeout after 2m0s`), so the volume was still in the ASW. 
But then the csi plugin detached the volume and deleted the va.
