### ISSUE TITLE
kubectl server-side diff shows timestamp changes without any other differences

### ISSUE THREAD

**Issue by smuth4** [kubernetes/kubernetes#108234]
### What happened?

1. I applied an object with `kubectl apply --server-side test.yml`, with the following definition:
```yml
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: http
      port: 443
  selector: null # Causes the issue
```
2. I diffed the same object with `kubectl diff --server-side test.yml` and received this diff:
```diff
diff -u -N /tmp/LIVE-2180884622/v1.Service.default.test /tmp/MERGED-4046057158/v1.Service.default.test
--- /tmp/LIVE-2180884622/v1.Service.default.test	2022-02-20 17:38:23.122059404 -0500
+++ /tmp/MERGED-4046057158/v1.Service.default.test	2022-02-20 17:38:23.122059404 -0500
@@ -16,7 +16,7 @@
         f:selector: {}
     manager: kubectl
     operation: Apply
-    time: "2022-02-20T22:38:22Z"
+    time: "2022-02-20T22:38:23Z"
   name: test
   namespace: default
   resourceVersion: "70777376"
```

### What did you expect to happen?

It should have reported no changes.

### How can we reproduce it (as minimally and precisely as possible)?

In addition to the above service example where the explicitly set `null` selector is causing problems, it also occurs with cases where values get modified, such as deployment resource requests/limits:
<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: default
spec:
  selector:
    matchLabels:
      name: httpbin
  template:
    metadata:
      labels:
        name: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        resources:
          limits:
            cpu: 1000m # Causes the issue
            memory: 1Gi # Causes the issue
```

</details>

### Anything else we need to know?

The symptoms are the same as https://github.com/kubernetes/kubernetes/issues/94121#issuecomment-682244971, but this is happening in server-side mode.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ardaguclu** [comment]
This PR https://github.com/kubernetes/kubernetes/pull/106388 will very likely solve also that problem. 

/unassign
