### ISSUE TITLE
kubelet fails to unmount CSI volumes because unmounter fails when vol_data.json is empty

### ISSUE THREAD

**Issue by fordsu** [kubernetes/kubernetes#108217]
### What happened?

On pod termination, kubelet sometimes fails to unmount CSI volumes with the following error:

`kubernetes.io/csi: failed to parse volume data file [/var/lib/kubelet/pods/abe9027f-609b-45db-b7b6-6a363c805b07/volumes/kubernetes.io~csi/pvc-121296d1-12e8-4393-80eb-4285cedd76a6/vol_data.json]: EOF"`

When I check this file on disk，it appears to be 0 bytes：
`ll /var/lib/kubelet/pods/abe9027f-609b-45db-b7b6-6a363c805b07/volumes/kubernetes.io~csi/pvc-121296d1-12e8-4393-80eb-4285cedd76a6/vol_data.json 
-rw-rw-rw- 1 root root 0 Feb 19 08:54 /var/lib/kubelet/pods/abe9027f-609b-45db-b7b6-6a363c805b07/volumes/kubernetes.io~csi/pvc-121296d1-12e8-4393-80eb-4285cedd76a6/vol_data.json`

don't know why this file was empty, maybe the disk or file system was corrupted when saving this file.

I think the volumemanager should handle this error（broken vol_data.json ） properly,  because the information needed to unmount the csi volume can be retrieved in the apiserver

### What did you expect to happen?

kubelet should be able to unmount CSI volumes on pod termination.

### How can we reproduce it (as minimally and precisely as possible)?

maybe delete a pod when vol_data.json is damaged.

### Kubernetes version

k8s v1.22.1 

### Cloud provider

Bare metal 10 node cluster

### OS version

euleros

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
from sig node triage, let sig storage triage it to decide whether handling of broken file is a bug or feature.

For the part of the bug on why the file became empty - please provide more information like kubelet logs and ideally steps to reproduce. triaging as needs information for this part of the bug

/triage needs-information
