### ISSUE TITLE
After deleting a namespace all pods related to a cron job got stuck in Terminating status.

### ISSUE THREAD

**Issue by hubertnnn** [kubernetes/kubernetes#108297]
### What happened?

After deleting a namespace all pods related to a cron job got stuck in Terminating status.
It was impossible to remove them even force remove did not work.
The only way of removing that pods was by modifying metadata to remove `batch.kubernetes.io/job-tracking` finalizer

### What did you expect to happen?

Removing a namespace should not get stuck.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a namespace
2. In that namespace create a CronJob with a long cron job (`sleep 3600s`).
3. Remove the namespace
4. Both namespace and all pods will get stuck in Terminating status but will never get removed

5. Run `kubectl patch pod [POD_NAME] -p '{"metadata":{"finalizers":null}}'` on each Terminated pod
6. All pods and namespace gets deleted.

### Kubernetes version

<details>
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
Local machine using k3s
</details>

### OS version

<details>
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Linux *** 5.4.0-96-generic #109~18.04.1-Ubuntu SMP Thu Jan 13 15:06:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Install tools

<details>
k3s, helm
</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tossmilestone** [comment]
The finalizer is used to terminate the cronjob gracefully, and it will be removed if the jobs are completed. I think the issue is not a bug but by design.

**Comment by hubertnnn** [comment]
No, because neither of them can be completed any more, since both the cron job and the pods were killed.
