### ISSUE TITLE
P&F metrics are expensive

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/kubernetes#108272]
I was looking a bit into data from P&F in the context of resource consumption. Unfortunately I can't just paste the direct data, but this it the brief summary:

- `startRequest` is the only function that is non-negligble in any profiles I've seen [which is kind-of expected]
- what is extremely suprising is that in any profile I've seen, ~50% of time spent in `startRequest` is actually spend on metrics-related stuff

The example (normalized) data [although all profiles looked pretty similar wrt to it:
- `startRequest` : 1s
- `sampleAndWaterMarksHistogram.Add`: 120ms [called from enqueLocked]
- `request.NodeQueued`: 70ms [called also from enqueueLocked - it splits into updating two recordMutating and recordReadOnly]
- `SetCurrentR`: 240ms [called from syncTimeLocked]
- `sampleAndWaterMarkHistoram.Add`: 80ms [called from dispatchLocked]
- `SetDispatchMetrics`: 40ms [called from selectQueueLocked from dispatchLocked]

So in total, from 1s spend on P&F related stuff, we spend 550ms on updating metrics. The ratio isn't what I would expect.

We should try looking into optimizing amount of compute we spend on that.

@MikeSpreitzer @tkashem @deads2k 

/sig api-machinery
/priority important-longterm
/kind bug

**Comment by aojea** [comment]
/cc

This match my experience with metrics :turtle: :shrug:

**Comment by dgrisonnet** [comment]
This issue seems odd to me since all the metrics used by P&F should be fairly inexpensive. @wojtek-t could you perhaps share the CPU profile of the metrics part?

FWIW this is different from what was reported for kubelet in https://github.com/kubernetes/kubernetes/issues/104459, since they are using a different kind of metrics.

**Comment by dgrisonnet** [comment]
That's plenty enough, thank you.

I looked into the code a bit and didn't find anything special besides the fact that P&F is updating a ton of metrics for each request, but the access to the metrics underlying hash map should be pretty fast since most of the metrics I have seen have a low cardinality. It might be worth verifying on your side if a P&F request should really update that many metrics or if some can be moved to less frequently called code paths.

That said, it is very surprising to me that we spend 1/5th of the time in the SetCurrentR function as it updates only one Gauge which should be a pretty fast operation. It seems that most of that time was for stack allocation, but that should happen very rarely and only upon startup since the only dimension of the metric is its priority, so I am a bit confused here.

**Comment by MikeSpreitzer** [comment]
Very odd indeed.  I am not familiar with the golang runtime.  Is perhaps there something about allocating stacks in chunks, and it just so happens that gauge update in SetCurrentR always fills up one chunk and causes allocation of another?

**Comment by wojtek-t** [comment]
> I looked into the code a bit and didn't find anything special besides the fact that P&F is updating a ton of metrics for each request, but the access to the metrics underlying hash map should be pretty fast since most of the metrics I have seen have a low cardinality. It might be worth verifying on your side if a P&F request should really update that many metrics or if some can be moved to less frequently called code paths.

@MikeSpreitzer - we should think if we can improve it. I think we should eliminate some of the metrics.

But I agree that the biggest surprise is indeed SetCurrentR - I would expect this particular one to be fast.
I didn't look into prometheus code, but I as Damien wrote above, I would expect it not doing any allocations once set for all priority-levels (which should happen right after startup).

**Comment by aojea** [comment]
nice explanation on how golang stack expansion work
https://www.sobyte.net/post/2021-12/golang-stack-management/#stack-expansion

**Comment by aojea** [comment]
heh, this is easy to reproduce just with one test using traces and profilers

```
go test -timeout 60s -run ^TestBaseline$ k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset -count 1 -trace trace.out -blockprofile block.out
```
see in the trace the amount of time on the prometheus

![image](https://user-images.githubusercontent.com/6450081/155231186-fd15b1c1-49ae-4681-92a5-1b5f28d286fa.png)


and checking the block profile 

```
$ go tool pprof block.out 
File: queueset.test
Type: delay
Time: Feb 22, 2022 at 11:31pm (CET)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top
Showing nodes accounting for 14.30ms, 99.53% of 14.36ms total
Dropped 14 nodes (cum <= 0.07ms)
Showing top 10 nodes out of 36
      flat  flat%   sum%        cum   cum%
    7.83ms 54.50% 54.50%     7.83ms 54.50%  runtime.chanrecv1
    5.18ms 36.05% 90.55%     5.18ms 36.05%  sync.(*WaitGroup).Wait
    1.20ms  8.38% 98.93%     1.20ms  8.38%  runtime.selectgo
    0.09ms   0.6% 99.53%     0.09ms   0.6%  sync.(*Cond).Wait
         0     0% 99.53%     1.20ms  8.38%  github.com/prometheus/client_golang/prometheus.(*Registry).Gather
         0     0% 99.53%     4.27ms 29.73%  github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2
         0     0% 99.53%     0.60ms  4.17%  github.com/prometheus/client_golang/prometheus/testutil.GatherAndCompare
         0     0% 99.53%     0.60ms  4.21%  github.com/prometheus/client_golang/prometheus/testutil.GatherAndLint
         0     0% 99.53%     0.30ms  2.07%  k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*request).Finish
         0     0% 99.53%     0.21ms  1.47%  k8s.io/apiserver/pkg/util/flowcontrol/fairqueuing/queueset.(*request).Finish.func1
```

**Comment by aojea** [comment]
@wojtek-t I can see that the metrics have a label per flowschema and priority, how many values do you have in that environment?

**Comment by wojtek-t** [comment]
8 PLs, 13 FSs
These are their definitions (you need to sum mandatory and suggested ones):
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go#L33

However, since FS is assigned to a given PL, the number of valid pairs is actually number of FSs (so 13).

**Comment by aojea** [comment]
ok, a more realistic reproducer:

1. Create a kind cluster: `kind create cluster`
2. Send periodic requests in parallel: `while true; do kubectl get pods; sleep 1; done`
3. Gather a cpu profile from the apiserver `kubectl get --raw http://localhost:6060/debug/pprof/profile?seconds=30 > profile.out`
4. I can see 1608 metrics related to flowcontrol, is that number expected?

```
kubectl get --raw http://1/metrics | grep apiserver_flowcontrol | wc
   1608    3483  221452
```

The profile shows similar number as reported by wojtek

![image](https://user-images.githubusercontent.com/6450081/155679172-e3bf58ac-1b68-4eb6-9db4-6cec67512d8f.png)

**Comment by wojtek-t** [comment]
> I can see 1608 metrics related to flowcontrol, is that number expected?

There are gazillion of metrics:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go

But if I'm counting correctly, ~25 of them, multiplying by 13 flow-schemas, I would rather expect <500 streams...
Can you maybe drop some gist here so that not everyone has to reproduce it?

**Comment by wojtek-t** [comment]
Actually no - multiple of those are histograms, so that multiples the number of metrics. So this 1608 actually might make sense actually.

**Comment by aojea** [comment]
https://gist.github.com/aojea/b605521838658e591f04cab9a2daf85d

**Comment by dgrisonnet** [comment]
I was looking at similar data as the one Antonio shared and I couldn't get SetCurrentR to show up in the flame graph. Is there anything special with your setup @wojtek-t, that might make a difference here?

**Comment by wojtek-t** [comment]
> Is there anything special with your setup @wojtek-t, that might make a difference here?

Nothing that I'm aware and comes to my mind - it should be a typical profile.

**Comment by wojtek-t** [comment]
@MikeSpreitzer - ignoring this `SetCurrentR` for a moment, the most part is actually consumed by SampleAndWatermark histogram. I think that we need to get back and reevaluate if we really need all of that and if we can't relax what kind of message we want from them.

So currently, we're looking at 1ms intervals and report sample, hi and low for each of that. The question is whether we really need that accurate information.
From my experience, I'm mostly looking at wait duration and execution duration metrics and use sample and watermarks to spot check if there was a PL saturation problem. But I'm not convinced we need all of the information we actually are exporting here.

Some thoughts (we can discuss them during next meeting, and of course I want to hear why you disagree with them :) )

1) I think I've never really looked at "low" watermark. 
    I think the information I care about is "how occupied we were on average", "and if we ever get saturated".
    The later is obviously useful, the former is all proxy I need.
    [If that makes any sense - that would allow us to reduce from 3 histograms to 2 histograms]

2) If the above makes sense, then for "if we ever get saturated", isn't even a histogram - it can effectively be a gauge that shows me for how much time I was saturated.
[There is a question what saturated means - maybe it's "more than 90%" or sth, but that could simplify stuff too.]

3) The question is whether we also need 1ms accurracy. I think we don't. It makes sense in the current shape when we're reporting a histogram, but if we would be more accurately reporting saturation time (FWIW, we can upload it only once every 100ms or sth and on every request just accumulate if it was saturated in between or not), then I think the average can be computed over bigger periods (say 10ms instead) without significant loss of information we need for debugging purposes.

WDYT?

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@MikeSpreitzer is making significant progress on it.

**Comment by MikeSpreitzer** [comment]
Unless I have lost track of something, I think we have completed this campaign.  The last step was #111348.

**Comment by wojtek-t** [comment]
Agree - thanks Mike!

/close
