### ISSUE TITLE
misleading comments in container.Ports

### ISSUE THREAD

**Issue by j4m3s-s** [kubernetes/kubernetes#108255]
### What happened?

The comments in https://github.com/kubernetes/kubernetes/blob/dc96c3dfccbc2005e4c4367fc8da199413e2bdcb/staging/src/k8s.io/api/core/v1/types.go#L2328 says that : 
```
Exposing a port here gives
the system additional information about the network connections a
container uses, but is primarily informational.
```
However there are several cases where this is false : 
- When using a Service with a targetPort that references a name in the ports arrays of the pod.
- Some software (ab)uses this API to get which ports are used (See https://github.com/kubernetes/kubernetes/issues/108131 Although unfixable, my goal is to fix the documentation so other people don't have the same problem). The Azure Load Balancer implementation does this for instance.
- Some other network/security software might use this information.

Also, is it possible to document/reference the above issue in the comment ? 

### What did you expect to happen?

Since it is described as *informational* I expected for the network to work without this information. But it's definitely not the case.

### How can we reproduce it (as minimally and precisely as possible)?

Not needed since it's mostly a  doc issue.

### Anything else we need to know?

I'm interested in contributing this patch but would like some feedbacks before doing it. :) 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by khenidak** [comment]
/triage accepted

@thockin -- thoughts? I believe the doc are due for a refresh.

**Comment by cyclinder** [comment]
I'd take this one.
/assign

**Comment by cyclinder** [comment]
I didn't see that you wanted to do this patch, I am very sorry and now I unassign it.
/unassign

**Comment by j4m3s-s** [comment]
No worries @cyclinder. But I'm still not sure where / what to add. Should I only fix the part saying it is only informational ? Is there anything else ? (cc @khenidak @thockin)
