### ISSUE TITLE
Horizontal pod autoscaler is not able to downscale properly based on custom metrics.

### ISSUE THREAD

**Issue by sanjipta1995** [kubernetes/kubernetes#108299]
### What happened?

While downscaling, HPA should terminate pods as and when load decreases.
We are seeing downscaling only when custom metric touches zero and not when value decreases below threshold.

### What did you expect to happen?

While downscaling, HPA should terminate pods as and when load decreases. It should not wait for value to become zero.

### How can we reproduce it (as minimally and precisely as possible)?

Create http_request_per_second from total http requests and use it in HPA definition

### Anything else we need to know?

HPA definition:
```
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
name: http-pod-hpa
namespace: kaas-monitoring
spec:
scaleTargetRef:
apiVersion: apps/v1
kind: Deployment
name: prometheus-example-app
minReplicas: 1
maxReplicas: 50
metrics:
# use a "Pods" metric, which takes the average of the
# given metric across all pods controlled by the autoscaling target
- type: Pods
pods:
metric:
# use the metric that you used above: pods/http_requests
name: http_requests_per_second
target:
# target 500 milli-requests per second,
# which is 1 request every two seconds
type: AverageValue
averageValue: 100m
behavior:
scaleDown:
policies:
- type: Pods
value: 5
periodSeconds: 60
stabilizationWindowSeconds: 0
scaleUp:
policies:
- type: Pods
value: 10
periodSeconds: 60
selectPolicy: Max
stabilizationWindowSeconds: 0
```

### Kubernetes version

k8s version 1.20

### Cloud provider

AWS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> k8s version 1.20

this version is going EOL soon. is the problem reproducible with newer k8s?
https://kubernetes.io/releases/#release-v1-20

**Comment by superherointj** [comment]
I'm having same issue of pods not scaling down but it could be my mistake once I'm not used to feature.
I'm running `k3s v1.23.3+k3s1`.

I'm using:
`
      autoscaling:
        minReplicas: 1
        maxReplicas: 4
        targetCPUUtilizationPercentage: 50
        targetMemoryUtilizationPercentage: 50
        downscaleStabilization: 180
`
It never scales down. I check loads using: `kubectl get hpa -A`
`
NAMESPACE       NAME                       REFERENCE                             TARGETS             MINPODS   MAXPODS   REPLICAS   AGE
ingress-nginx   ingress-nginx-controller   Deployment/ingress-nginx-controller   107%/50%, 27%/50%   1         4         4          49m
`
Should it scale down or not?
