### ISSUE TITLE
How to patch custom kubernetes API object with clientgo

### ISSUE THREAD

**Issue by journey-wang** [kubernetes/kubernetes#108242]
### What would you like to be added?

I need to update the argo workflow annotations/labels via api, but unfortunately, argo sdk didn't provide this API. WIth kubectl, like kubectl label/annotation, or kubectl edit workflow , this can be easilily.

But I wonder how to do this work via Kubernetes go client sdk?

Thanks very much.

### Why is this needed?

For our solutioni.

**Comment by aojea** [comment]
just check the kubectl patch command, you can also use curl  

https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/

**Comment by MadhavJivrajani** [comment]
For interacting with custom resources that don't have a generated client-set, dynamic client can be used: https://pkg.go.dev/k8s.io/client-go/dynamic
/kind support
/sig api-machinery
