### ISSUE TITLE
New Beta APIs off by Default

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#108279]
### What would you like to be added?

Implementing https://github.com/kubernetes/enhancements/tree/master/keps/sig-architecture/3136-beta-apis-off-by-default#graduation-criteria

### Why is this needed?

I need a personal checklist to keep track of where I am.

- [x] Integration and unit tests to ensure that no new beta APIs are enabled by default
    contained in https://github.com/kubernetes/kubernetes/pull/107993
- [ ] updating the enablement docs for beta
    - [ ] https://kubernetes.io/docs/reference/using-api/#api-versioning
    - [ ] https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#using-a-feature Even though that is talking about feature gates, it is likely worth calling out there that new beta REST APIs are no longer enabled by default) - contained in https://github.com/kubernetes/website/pull/32284
    - [x] email to [dev@kubernetes.io](mailto:dev@kubernetes.io) to explain the new policy
- [ ] blog post explaining change in time for 1.24 release
- [x] CI configuration updated to have a testing mode that enables beta APIs, likely set using kube-apiserver --runtime-config=api/beta=true
    contained in https://github.com/kubernetes/test-infra/pull/25369
- [x] extend the PRR questionnaire to include a GA-targeted question to validate that the feature was reasonably validated in production use-cases.
    contained in https://github.com/kubernetes/enhancements/pull/3236
- [x] update the developer docs for adding an API version to indicate that beta is off by default and to add advice for how to test these APIs.
    contained in https://github.com/kubernetes/community/pull/6541

**Comment by sftim** [comment]
> blog post explaining change in time for 1.24 release

I'd love to see a draft PR for that come in soon - we are already co-ordinating the comms for the v1.24 release.
