### ISSUE TITLE
why the Replicas used  int32? Is used uint32 more better?

### ISSUE THREAD

**Issue by yan234280533** [kubernetes/kubernetes#108289]
### What happened?

None

### What did you expect to happen?

None

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

None

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MadhavJivrajani** [comment]
/sig apps
/remove-kind bug
/kind support
@yan234280533 please fill in the description with more context. If those details are not available to you, please close this issue and feel free to start a discussion on the [K8s slack](https://slack.k8s.io) in the `#sig-apps` and/or the `sig-api-machinery` channels.
