### ISSUE TITLE
Empty endpointslices are fully updated every cycle defined by controller-manager default --min-resync-period=12h

### ISSUE THREAD

**Issue by MinvenX** [kubernetes/kubernetes#108231]
### What happened?

My cluster contains about 4w endpointslices. There are 3 related metrics (endpoint_slice_controller_endpoints_added_per_sync_count, endpoint_slice_controller_endpoints_removed_per_sync_count, endpoint_slice_controller_changes) to indicates endpoint add remove and update. I found that the apiserver periodically receives lots of endpointslice update requests. In terms of the number of requests, the endpointslice has been fully updated. But from the endpointslice resource itself, it seems that it has not been updated, because "endpoints.kubernetes.io/last-change-trigger-time" annotation didn't change

### What did you expect to happen?

It seems that there is no need to update the endpointslice with no really changes. On the other hand, a large number of ep slice update requests will stress the apiserver.

### How can we reproduce it (as minimally and precisely as possible)?

In order to make the phenomenon more obvious, the min-resync-period parameter of controller-manager can be adjusted to 1 minute. Create one or more empty endpointslices, and then you can find in the apiserver logs that requests to update these endpointslice every one to two minutes. For clusters with lots of empty endpointslices, this bug may affect the stability of it.

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10", GitCommit:"79688684d40e9b5612f155e7911fb430eda38169", GitTreeState:"clean", BuildDate:"2021-09-15T09:53:17Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10", GitCommit:"79688684d40e9b5612f155e7911fb430eda38169", GitTreeState:"clean", BuildDate:"2021-09-14T11:37:12Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# VERSION="16.04.6 LTS (Xenial Xerus)"
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> I'm not sure. Maybe it happens on any k8s cluster with version 1.20.

there were different improvements in this area, but since 1.20 is going EOL in 8 days it will be good to know if this happens in 1.21

https://kubernetes.io/releases/#release-v1-20

/cc @robscott

**Comment by MinvenX** [comment]
> > I'm not sure. Maybe it happens on any k8s cluster with version 1.20.
> 
> there were different improvements in this area, but since 1.20 is going EOL in 8 days it will be good to know if this happens in 1.21
> 
> https://kubernetes.io/releases/#release-v1-20
> 
> /cc @robscott

I'm glad to recieve your comment. I'm not sure because I only have cluster with version 1.20.10. Expected someone who could provide more detail about it. It is actually happening in my cluster, but I have not known how it happens.

**Comment by robscott** [comment]
I've seen this in 1.20 clusters as well, but have not seen it in 1.21. My theory was that this was mostly fixed by https://github.com/kubernetes/kubernetes/pull/99750. Prior to that, any change to EndpointSlice labels would not trigger an EndpointSlice controller sync loop, but the resync period would result in those EndpointSlices being updated at that point. 

@tnqn's more recent fix (https://github.com/kubernetes/kubernetes/pull/108078) seems like it could also be relevant, but I don't think it matches what's described here. In that case, I believe we're unnecessarily updating EndpointSlices if something irrelevant in the Pod changes (resource version), but I don't believe there's anything special there that would mean we weren't updating EndpointSlices until the resync period. 

So with all of that said, I believe this is fixed in 1.21+, but let me know if anyone's able to recreate this in those versions and/or if #108078 is actually more relevant than it appears on the surface.

**Comment by MinvenX** [comment]
> 



> 我在 1.20 集群中也看到过这种情况，但在 1.21 中没有看到过。我的理论是，这主要或完全由#99750解决。在此之前，对 EndpointSlice 标签的任何更改都不会触发 EndpointSlice 控制器同步循环，但重新同步周期会导致这些 EndpointSlice 在该点被更新。
> 
> @tnqn的最新修复（#108078）似乎也可能是相关的，但我认为它与此处描述的不符。在这种情况下，我认为如果 Pod 中的某些不相关的内容发生更改（资源版本），我们会不必要地更新 EndpointSlices，但我不认为那里有什么特别之处意味着我们直到重新同步期间才更新 EndpointSlices。
> 
> 综上所述，我相信这在 1.21+ 中已修复，但请告诉我是否有人能够在这些版本中重新创建它和/或#108078是否实际上比表面上看起来更相关。



> I've seen this in 1.20 clusters as well, but have not seen it in 1.21. My theory was that this is mostly or entirely fixed by #99750. Prior to that, any change to EndpointSlice labels would not trigger an EndpointSlice controller sync loop, but the resync period would result in those EndpointSlices being updated at that point.
> 
> @tnqn's more recent fix (#108078) seems like it could also be relevant, but I don't think it matches what's described here. In that case, I believe we're unnecessarily updating EndpointSlices if something irrelevant in the Pod changes (resource version), but I don't believe there's anything special there that would mean we weren't updating EndpointSlices until the resync period.
> 
> So with all of that said, I believe this is fixed in 1.21+, but let me know if anyone's able to recreate this in those versions and/or if #108078 is actually more relevant than it appears on the surface.

Thanks for your reply! I will check

**Comment by MinvenX** [comment]
> I've seen this in 1.20 clusters as well, but have not seen it in 1.21. My theory was that this is mostly or entirely fixed by #99750. Prior to that, any change to EndpointSlice labels would not trigger an EndpointSlice controller sync loop, but the resync period would result in those EndpointSlices being updated at that point.
> 
> @tnqn's more recent fix (#108078) seems like it could also be relevant, but I don't think it matches what's described here. In that case, I believe we're unnecessarily updating EndpointSlices if something irrelevant in the Pod changes (resource version), but I don't believe there's anything special there that would mean we weren't updating EndpointSlices until the resync period.
> 
> So with all of that said, I believe this is fixed in 1.21+, but let me know if anyone's able to recreate this in those versions and/or if #108078 is actually more relevant than it appears on the surface.

Thanks for your reply！ I will check it.

**Comment by MinvenX** [comment]
> I've seen this in 1.20 clusters as well, but have not seen it in 1.21. My theory was that this is mostly or entirely fixed by #99750. Prior to that, any change to EndpointSlice labels would not trigger an EndpointSlice controller sync loop, but the resync period would result in those EndpointSlices being updated at that point.
> 
> @tnqn's more recent fix (#108078) seems like it could also be relevant, but I don't think it matches what's described here. In that case, I believe we're unnecessarily updating EndpointSlices if something irrelevant in the Pod changes (resource version), but I don't believe there's anything special there that would mean we weren't updating EndpointSlices until the resync period.
> 
> So with all of that said, I believe this is fixed in 1.21+, but let me know if anyone's able to recreate this in those versions and/or if #108078 is actually more relevant than it appears on the surface.

I confirmed that the periodic updates in my cluster are all empty endpointslices.  But it shouldn't be updated when endpointslice-controller couldn't find pods by service label selector.

**Comment by MinvenX** [comment]
I found that when endpointslice's endpoint array is empty, endpointslice-controller updates it during periodic resync, although it doesn't change. I consider it a bug and would like to fork and fix it. The code below could fix the issue of updating empty endpointslices, but I'm not sure if it will introduce new issues.
`pkg/controller/endpointslice/reconciler.go`

        for  i := 0; i < len(slicesToDelete); {
		if len(slicesToCreate) == 0 {
			break
		}
		sliceToDelete := slicesToDelete[i]
		slice := slicesToCreate[len(slicesToCreate)-1]
		// Only update EndpointSlices that are owned by this Service and have
		// the same AddressType. We need to avoid updating EndpointSlices that
		// are being garbage collected for an old Service with the same name.
		// The AddressType field is immutable. Since Services also consider
		// IPFamily immutable, the only case where this should matter will be
		// the migration from IP to IPv4 and IPv6 AddressTypes, where there's a
		// chance EndpointSlices with an IP AddressType would otherwise be
		// updated to IPv4 or IPv6 without this check.
		if sliceToDelete.AddressType == slice.AddressType && ownedBy(sliceToDelete, service) {
			slice.Name = sliceToDelete.Name
			slicesToCreate = slicesToCreate[:len(slicesToCreate)-1]

			// We must consider the situation that an empty unchanged endpointslice no need to update.
			// eg: If there are many headless service with single stack ipv4 for example, a lot of ipv6 empty
			//     endpointslice update could be avoid.
                    //  ******* modified here********
			if len(slice.Endpoints) != 0 || len(sliceToDelete.Endpoints) != 0 {
				slicesToUpdate = append(slicesToUpdate, slice)
			}

			slicesToDelete = append(slicesToDelete[:i], slicesToDelete[i+1:]...)
		} else {
			i++
		}

**Comment by robscott** [comment]
Hey @MinvenX, I'm not sure I completely understand this fix, but thanks for volunteering to take this on! As I recall, this specific section of the reconciler code is part of the "recycling" logic, where an EndpointSlice marked for creation reuses the name of when marked for the deletion, and the operation becomes an update. I'd appreciate a PR if you can also include a test that recreates the buggy behavior + shows that this fixes it.

**Comment by MinvenX** [comment]
> Hey @MinvenX, I'm not sure I completely understand this fix, but thanks for volunteering to take this on! As I recall, this specific section of the reconciler code is part of the "recycling" logic, where an EndpointSlice marked for creation reuses the name of when marked for the deletion, and the operation becomes an update. I'd appreciate a PR if you can also include a test that recreates the buggy behavior + shows that this fixes it.

Thanks for your reply. I will try more test and show this fix does work.

**Comment by robscott** [comment]
I understand the bug now - it looks the root issue is here:

https://github.com/kubernetes/kubernetes/blob/cb0e460343fef35135065264d6db53e1b1597b8c/pkg/controller/endpointslice/reconciler.go#L206-L224 

Essentially we'd consider the previous placeholder EndpointSlice no longer desired, mark it for deletion, and then that would mean no EndpointSlices would be left, triggering a new placeholder slice to be marked for creation. The recycling logic you linked above essentially merges creates and deletes into updates, resulting in the behavior you described of empty EndpointSlices always being updated during the resync period. 

I think this should be _relatively_ straightforward to fix with some changes to the code I referenced above.
