### ISSUE TITLE
[Failing test] ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew.Overall

### ISSUE THREAD

**Issue by voigt** [kubernetes/kubernetes#108307]
### Which jobs are failing?

release-master-blocking

- [skew-cluster-latest-kubectl-stable1-gce](https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce)

### Which tests are failing?

- ci-kubernetes-e2e-gce-master-new-gci-kubectl-skew.Overall
- kubetest.Extract

### Since when has it been failing?

2022-02-22 03:43 CET

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce

### Relevant SIG(s)

/sig cloud-provider
/kind failing-test
cc https://github.com/orgs/kubernetes/teams/ci-signal

**Comment by jiahuif** [comment]
https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable.txt Not Found
/sig release

**Comment by brianpursley** [comment]
https://storage.googleapis.com/k8s-release-dev/ci/k8s-stable1.txt (not found)
vs
https://storage.googleapis.com/kubernetes-release-dev/ci/k8s-stable1.txt (found)

Could it be related to the changes made here?
https://github.com/kubernetes/test-infra/pull/22840

**Comment by eddiezane** [comment]
cc @puerco

**Comment by brianpursley** [comment]
Most of [sig-cli's periodic skew tests](https://testgrid.k8s.io/sig-cli-master) are also failing for the same reason.

Something is supposed to be writing those txt files to the k8s-release-dev bucket, but that seems not to be happening.

Judging by the alert info, the problem seems to have started around Feb 21.

**Comment by leonardpahlke** [comment]
Friendly ping: [skew-cluster-latest-kubectl-stable1-gce](https://testgrid.k8s.io/sig-release-master-blocking#skew-cluster-latest-kubectl-stable1-gce) still fails

This issue might be release cut blocking.

cc @palnabarun @jimangel

**Comment by shuheiktgw** [comment]
The error has actually changed since 03-14. 

```
I0314 15:06:05.297] Mar 14 15:06:03.527: FAIL: Unexpected error:
I0314 15:06:05.298]     <*errors.errorString | 0xc00023c2a0>: {
I0314 15:06:05.298]         s: "timed out waiting for the condition",
I0314 15:06:05.298]     }
I0314 15:06:05.299]     timed out waiting for the condition
I0314 15:06:05.299] occurred
I0314 15:06:05.299] 
I0314 15:06:05.299] Full Stack Trace
```

**Comment by leonardpahlke** [comment]
Hey @eddiezane , what is your take on this issue? It's labeled as release blocking and the next release cut is tomorrow.

/priority critical-urgent
/milestone 1.24

**Comment by liggitt** [comment]
the cluster / test setup seems like it is successfully setting up a cluster and getting a client and server:

```
I0321 15:08:24.353] bootstrap-e2e-master              Ready,SchedulingDisabled   <none>   25s   v1.24.0-alpha.3.635+f14d1c9b1ef2b3
I0321 15:08:24.353] bootstrap-e2e-minion-group-6v7n   Ready                      <none>   25s   v1.24.0-alpha.3.635+f14d1c9b1ef2b3
I0321 15:08:24.353] bootstrap-e2e-minion-group-l5bl   Ready                      <none>   23s   v1.24.0-alpha.3.635+f14d1c9b1ef2b3
I0321 15:08:24.354] bootstrap-e2e-minion-group-ng46   Ready                      <none>   24s   v1.24.0-alpha.3.635+f14d1c9b1ef2b3
W0321 15:08:24.613] Warning: v1 ComponentStatus is deprecated in v1.19+
I0321 15:08:24.713] Validate output:
W0321 15:08:24.899] Warning: v1 ComponentStatus is deprecated in v1.19+
W0321 15:08:24.903] Done, listing cluster services:
W0321 15:08:24.903] 
I0321 15:08:25.003] NAME                 STATUS    MESSAGE                         ERROR
I0321 15:08:25.004] etcd-0               Healthy   {"health":"true","reason":""}   
I0321 15:08:25.004] controller-manager   Healthy   ok                              
I0321 15:08:25.004] etcd-1               Healthy   {"health":"true","reason":""}   
I0321 15:08:25.004] scheduler            Healthy   ok                              
I0321 15:08:25.004] [0;32mCluster validation succeeded[0m
```

```
I0321 15:08:54.218] Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.6-rc.0.6+302af17d1a4040", GitCommit:"302af17d1a40406c249e173301e327e1ff739256", GitTreeState:"clean", BuildDate:"2022-03-18T18:12:42Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
I0321 15:08:54.219] Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-alpha.3.635+f14d1c9b1ef2b3", GitCommit:"f14d1c9b1ef2b3b332d6b83d10da27fe3855acad", GitTreeState:"clean", BuildDate:"2022-03-21T12:03:21Z", GoVersion:"go1.18rc1", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by liggitt** [comment]
so it doesn't seem at first glance like the cluster version markers are to blame

**Comment by liggitt** [comment]
If you look at what's actually timing out, it's the creation of the testing namespace at the beginning of each e2e test.

Which branch's tests are running against the 1.24 server? if 1.23 branch e2e tests are running against a 1.24 server, `CreateTestingNS` will be waiting for service account token secrets to be created, and they are no longer autocreated in 1.24.

Picking https://github.com/kubernetes/kubernetes/pull/107763 to release-1.23 would drop the wait for that secret token which is no longer required in 1.21, and would make 1.23 e2e tests at least closer to passing when run against a 1.24 server.

**Comment by leonardpahlke** [comment]
job is passing :)
/close
