### ISSUE TITLE
Logging statement with missing parameter

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#108355]
https://github.com/kubernetes/kubernetes/blob/5bafc8306a7b622e292746aec8a9e9212b755071/staging/src/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go#L225

> I0225 16:19:15.424936 1416311 versioning.go:225] a memory allocator was provided but the encoder %!T(MISSING) doesn't implement the runtime.EncoderWithAllocator, using regular encoder.Encode method

**Comment by uroy-personal** [comment]
Hi @aojea ,
I am new to making contributions in Kubernetes ecosystem. I am happy to start working on this issue.  I will reach out to you if I need any clarifications.

Best Regards,
Umesh

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/kubernetes/pull/108359
