### ISSUE TITLE
manifest of ingress is not embedded into golang test executable directory

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#108324]
### What happened?

Run the testcase,
```
e2e.test -- -ginkgo.focus="\[sig-network\] Loadbalancing: L7 \[Slow\] Nginx should conform to Ingress spec"
```

And debug into the source, will reveal something abnormal, 

````
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/testfiles/testfiles.go:78 (PC: 0x41eaaa9)
Warning: debugging optimized function
    73:         for _, filesource := range filesources {
    74:                 data, err := filesource.ReadTestFile(filePath)
    75:                 if err != nil {
    76:                         return nil, fmt.Errorf("fatal error retrieving test file %s: %s", filePath, err)
    77:                 }
=>  78:                 if data != nil {
    79:                         return data, nil
    80:                 }
    81:         }
    82:         // Here we try to generate an error that points test authors
    83:         // or users in the right direction for resolving the problem.
(dlv) p filePath
"test/e2e/testing-manifests/ingress/nginx/rc.yaml"
(dlv) p data
[]uint8 len: 0, cap: 0, nil

````

and the error was saying that files cannot be found, 
```
(dlv) p error
"Test file \"test/e2e/testing-manifests/ingress/nginx/rc.yaml\" was not found.\nThe following files are embedded into the test executable:\n\ttest/e2e/testing-manifests/flexvolume/attachable-with-long-mount\n\ttest/e2e/testing-manifests/flexvolume/dummy\n\ttest/e2e/testing-manifests/flexvolume/dummy-attachable\n\ttest/e2e/testing-manifests/guestbook/agnhost-primary-deployment.yaml.in\n\ttest/e2e/testing-manifests/guestbook/agnhost-primary-service.yaml\n\ttest/e2e/testing-manifests/guestbook/agnhost-replica-depl...+5653 more"
````

### What did you expect to happen?

manifest should be embedded and test executed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

run testcase and debug into the source, 
```
e2e.test -- -ginkgo.focus="\[sig-network\] Loadbalancing: L7 \[Slow\] Nginx should conform to Ingress spec"
```

### Kubernetes version

<details>

```console
$ kubectl version

master

```

</details>

### Cloud provider

<details>

Any

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
how much are we growing the binary?
This test are more a legacy thing than something we should keep distributing

**Comment by chendave** [comment]
> how much are we growing the binary?

not much I think, 16k or so,

before the embedding, 
```

# du -sk _output/bin/e2e.test
165384  _output/bin/e2e.test
```

after, 
```
# du -sk _output/bin/e2e.test
165400  _output/bin/e2e.test
```

**Comment by thockin** [comment]
My questions are not about size.

It seems to assumt hat the test runs from a checked-out k/k repo - is that a bad assumption?

If so, should we literally embed the file (how?) or just encode it as a Go struct definition or string variable?

**Comment by aojea** [comment]
> It seems to assumt hat the test runs from a checked-out k/k repo - is that a bad assumption?

The tests should not be here, the problem it has now is that the installation manifest is outdated ... basically created a circular dependency between nginx-ingress and kubernetes, that is the reason why I had to disable them when v1beta ingress was disabled

**Comment by chendave** [comment]
> The tests should not be here, the problem it has now is that the installation manifest is outdated ... 

I have trouble to enable those testcases, seems like there are something done on the gce or gke specifically. 
what's your suggestion about those testcases? keep it as is, dig it further, or just remove those testcases?

**Comment by aojea** [comment]
> > The tests should not be here, the problem it has now is that the installation manifest is outdated ...
> 
> I have trouble to enable those testcases, seems like there are something done on the gce or gke specifically. what's your suggestion about those testcases? keep it as is, dig it further, or just remove those testcases?

if they don't work and confuse people I think that is fair to remove it, let me ping ingress-nginx folks

@rikatz are you ok removing the ingress nginx test from k/k that were disabled when the v1beta1 -> v1 API drama?
I think that you have already a good CI running them

**Comment by rikatz** [comment]
Go for it :)

**Comment by chendave** [comment]
/close
Since there is no problem to run those testcase on gce or gke, and those testcases are not designed to run locally, so close it.
