### ISSUE TITLE
Controller-Manager garbagecollector.go objects don´t have an owner written 100000+ times in logfile per day

### ISSUE THREAD

**Issue by ErickStaal** [kubernetes/kubernetes#108373]
### What happened?

In the controller-manager log there are lots and lots of entries written containing the text:

garbagecollector.go:507] object [v1/Namespace, namespace: , name: knative-serving, uid: 6611472c-8af0-430b-abcd-3556be6b53ea]'s doesn't have an owner, continue on next item

These entries are also present for other seemingly random objects in other namespaces. But these entries only occur once in the logging and after that the cluster seems to be able to recover for these other objects, but the entry for the knative-serving namespace is written a couple of times a second to the logfiles, which leads to hundreds of thousands log entries per day.

I'm looking for a way to get a handle on this issue, but until now it eludes me what I can do to pinpoint this issue further. 

### What did you expect to happen?

The error not occurring, or the entry for knative-serving occurring max. 1x, just like as for the other errors of the same type.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know since I don't know what is causing this behavior.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:34:54Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>
On-prem install based upon Kubernetes the Hard Way
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Ubuntu 21.10"
PRETTY_NAME="Ubuntu 21.10"
NAME="Ubuntu"
VERSION_ID="21.10"
VERSION="21.10 (Impish Indri)"
VERSION_CODENAME=impish
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=impish

$ uname -a
# paste output here
Linux xxxxxxx 5.13.0-30-generic #33-Ubuntu SMP Fri Feb 4 17:03:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

This OS-release and kernel version applies to all masters and nodes in the cluster. (3 masters, 3 nodes).

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>
containerd v1.5.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni-plugins v1.0.1
</details>

**Comment by ErickStaal** [comment]
I would like logging here which is a bit more informative about what is going wrong.

**Comment by kkkkun** [comment]
You should get the pods, and notice field `ownerReferences`. 
If pods started by apps, it should set the app to this field and should not empty.
If pods started by  operator or other controller, the pods `ownerRefereces`  should be  empty and recycle by user's operator or other controller.

**Comment by ErickStaal** [comment]
Yes, fully agree, however two questions come to mind: 
1) The object which generates many entries in the logfile is a namespace object. (the object ID in the logentry in the first post above belongs to the namespace object knative-serving)  
2) when running _kubectl-check-ownerreferences_, I get "No invalid ownerReferences found".
3) when running _kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace_, I get "No resources found".

So it seems it isn't a pod which has no owner, but a namespace. In other words: I'm still looking how to get a handle on this issue.

**Comment by pohly** [comment]
/remove-wg structured-logging

This isn't related to logging infrastructure. What gets logged and how is decided by the code owners.

**Comment by ErickStaal** [comment]
I added the label api-machinery to this issue, due to garbage collection being in scope of this sig and my issue expresses itself through an error from garbagecollector.go.

**Comment by deads2k** [comment]
Does the reference objects have finalizers present or, if it is a namespace, does it have spec/finalizers and perhaps a status condition explaining why the namespae cannot be deleted?

**Comment by ErickStaal** [comment]
The info about the namespace knative-serving, garbagecollector.go seems to be complaining about (btw the namespace shouldn't disappear, since it has lots of objects in it):

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"knative-serving","app.kubernetes.io/version":"1.0.0","serving.knative.dev/release":"v1.0.0"},"name":"knative-serving"}}
  creationTimestamp: "2020-12-06T12:41:24Z"
  labels:
    app.kubernetes.io/part-of: knative-serving
    app.kubernetes.io/version: 1.0.0
    kubernetes.io/metadata.name: knative-serving
    serving.knative.dev/release: v1.0.0
  name: knative-serving
  resourceVersion: "896041305"
  uid: 6611472c-8af0-430b-abcd-3556be6b53ea
spec:
  finalizers:
  - kubernetes
status:
  phase: Active

**Comment by deads2k** [comment]
do you have this message repeating as well: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/garbagecollector/garbagecollector.go#L623

**Comment by ErickStaal** [comment]
Not that message with the attemptToDelete: just checked the logs again for an example:

```
Mar 27 10:07:57 kube-controller-01 kube-controller-manager[5251]: I0327 10:07:57.528616    5251 garbagecollector.go:468] "Processing object" object="knative-serving" objectUID=6611472c-8af0-430b-abcd-3556be6b53ea kind="Namespace" virtual=false
Mar 27 10:07:57 kube-controller-01 kube-controller-manager[5251]: I0327 10:07:57.535894    5251 garbagecollector.go:507] object [v1/Namespace, namespace: , name: knative-serving, uid: 6611472c-8af0-430b-abcd-3556be6b53ea]'s doesn't have an owner, continue on next item
```
This is the pair of messages which are continuously appearing in the logs.

**Comment by deads2k** [comment]
Near as I can tell,  https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/controller/garbagecollector/garbagecollector.go#L595 is the only point that queues into that workqueue.

https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/controller/garbagecollector/garbagecollector.go#L468-L469 tells us that `!item.isObserved()` is false and https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/controller/garbagecollector/garbagecollector.go#L507-L508 indicates that we'll end up https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/controller/garbagecollector/garbagecollector.go#L358 after the call.

The next step is likely to see if you can create a minimal set of resource manifests (yaml files) to reproduce this problem on a hack/local-up-cluster.sh cluster (installing knative is unrealistic),
