### ISSUE TITLE
client-go: inconsistencies among `Do`, `Watch`, and `Stream`  

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#108302]
### What happened?

https://github.com/kubernetes/kubernetes/pull/108262 adds a unit test that records the order in which `BackoffManager`, `flowcontrol.RateLimiter`, and `metrics` calls are invoked.

With this we have found an inconsistency where `Watch` does not do `RateLimiter.Wait` before initially sending the request to the server, but `Do`, `DoRaw`, and `Stream` do:

`Do`, and `DoRaw`: https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/rest/request.go#L949-L954

`Stream`: https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/rest/request.go#L810-L812

Another issue that will be more prominent when https://github.com/kubernetes/kubernetes/pull/106272 merges. We are sleeping twice between two retries:
-  `BackoffManager.Sleep(N seconds)` - N is derived from the `Retry-After: N` response header, today the server always sets it to `1` 

https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/rest/with_retry.go#L171-L174

- `BackoffManager.Sleep(S seconds)` - S is derived from the `BackoffManager.CalculateBackoff`, this is the wait dictated by the backoff parameters. with a default backoff ( `noBackoff`) it is always `0s`. when https://github.com/kubernetes/kubernetes/pull/106272 merges we will have two non-zero sleeps between retries that might be unnecessary.

https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/rest/request.go#L970

### What did you expect to happen?

`Do`, `DoRaw`, `Watch`, and `Stream` to have the same retry behavior in terms of `BackoffManager`, and `flowcontrol.RateLimiter`

### How can we reproduce it (as minimally and precisely as possible)?

See the code, also the Unit test in https://github.com/kubernetes/kubernetes/pull/108262

**Comment by tkashem** [comment]
/sig apimachinery
cc @wojtek-t @deads2k @lavalamp

**Comment by wojtek-t** [comment]
Copying one of my comments here I added on the PR:

> #106272 merges we can remove the sleep from Retry-After response.

I don't think we can just simply remove it - we should respect what kube-apiserver is returning to us (it's always returning 1 now, but we should address that too at some point).

So I think it's not abot removing - it's rather about unifying them and making something like:
BackOffManager.Sleep(max(backoffManager.CalculateBackoff(), retryAfter))

**Comment by tkashem** [comment]
@wojtek-t  another potential issue: the timeout context is derived after the first throttle, i don't know if there are any historical contexts to it https://github.com/kubernetes/kubernetes/pull/87599/files.
in my opinion, the context deadline should include the rate limiter wait before the first try, this reflects the user's experience accurately; otherwise, it's not technically bound to the context provided by the user.

The latency metric does include the rate limiter wait before the first try.

https://github.com/kubernetes/kubernetes/blob/9918aa1e035a00bc7c0f16a05e1b222650b3eabc/staging/src/k8s.io/client-go/rest/request.go#L949-L960

**Comment by wojtek-t** [comment]
Agree with the above

**Comment by tkashem** [comment]
the refactor PR has merged, the actual PRs to fix the issues are on the way

/reopen
