### ISSUE TITLE
Watcher doesn't receive expected event nor `EOF` for resources defined by aggregation sometimes

### ISSUE THREAD

**Issue by YuxinZhou** [kubernetes/kubernetes#108344]
### What happened?

We set up [reflectors](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L254) to reflect the change of k8s resources but they don't work properly for resources defined by aggregation API. After adding some debugging logs,  I think the issue is narrowed down to the watcher -

- The client starts the watch via long polling. It initiates  a GET request with a ~500 sec timeout ([ref](https://github.com/kubernetes/client-go/blob/master/rest/request.go#L632)) . In a successful case, the client keeps receiving events for changes from the server using a streamwatcher and will receive an EOF once the timeout is reached (I added a log [here](https://github.com/kubernetes/apimachinery/blob/release-1.22/pkg/watch/streamwatcher.go#L105.)). Upon the EOF, the client sends a new GET request to renew the watch.
- In the broken case, the streamwatcher stops receiving data from the server after a certain time point. There are no events received for resource updates, and EOF is also not received long after the expected timeout. Because the client doesn’t receive the EOF, it won’t trigger the new request either.

Some observations :
1. The problem only happens for the resources defined by the aggregation API (APIService). We've never seen this issue for other resources. 
2. The problem is intermittent but still quite reproducible in our environment. There are no panics in the client logs, and it sometimes recovers after hours.  After it recovers, the issue can still re-occur.
3. The problem can also be reproduced by "kubectl get XXX --watch"

I saw an open issue https://github.com/kubernetes/kubernetes/issues/107435 but I can't tell if it is related. 

### What did you expect to happen?

Watcher for aggregation API resources works the same as other resources. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create the aggregation API service on the cluster  (In my case I installed  https://github.com/vmware-tanzu/carvel-kapp-controller )
2. watch the resource defined  the aggregation API service ( in my case `kubectl get package -A -w`)
3. Leave the watch open for a while (~ 1 hour)
4. In another terminal, edit the resource being watched
5. `kubectl get ... --watch` doesn't print out the change  
6. Do the same for another resource that is not backed by aggregation API, found that the issue is not observed. 

In my experiments, the problem is intermittent so is not reproduced every time, but occurs in most times. 

### Kubernetes version

```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+vmware.....", GitCommit:".....", GitTreeState:"clean", BuildDate:"2022-02-15T10:23:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+vmware......", GitCommit:".....", GitTreeState:"clean", BuildDate:"2022-02-15T10:17:45Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by aojea** [comment]
> 1. The problem only happens for the resources defined by the aggregation API (APIService). We've never seen this issue for other resources.

this runs in another pod inside the cluster? I mean, if we draw the connection path this is something like?

[client] ---> [apiserver] ----> (cluster network) --> [aggregated apiserver]

**Comment by YuxinZhou** [comment]
@aojea Thank you for taking a look. Yes, that is right. And the pod behind the aggregated apiserver is healthy and never gets re-started.

**Comment by aojea** [comment]
> [client] ---> [apiserver] ----> (cluster network) --> [aggregated apiserver]

                                                       ^^^^

in my experience, most of the times I see these symptoms the problem is in the network :shrug: , kubernetes by default uses http2 with IdleTimeout to refresh the connection and detect stale connections, verify if you are using http2 and try to "cut" the connection (an iptables DROP should be enough, not REJECT it has to silently drop without the endpoints noticing) to see if your components are able to recover on those events.

**Comment by YuxinZhou** [comment]
@aojea Thank you a lot for your suggestions! I'll perform the experiment you suggested. 

Still I am a little confused - I don't know enough about apiserver / cluster network so please forgive my naive questions -  

1. Let's assume there is a connection blip between [apiserver] and  [aggregated apiserver].  From the symptoms,  the network between [client] and [apiserver]  stills works fine because other resources are reflected meanwhile. In this case, shouldn't the apiserver be resilient to such issues and still close the connection with the client at the timeout (by sending `EOF`? 

2. When I do a `list` or `get` for the resource, it always succeeds, even when the problem is observed. Is it possible a  network issue only affects `watch` as it is using long-polling? 

>  try to "cut" the connection (an iptables DROP should be enough

Do you mean in the cluster's iptables, to drop the request from the apiserver? 

Many Thanks,
Yuxin

**Comment by aojea** [comment]
If you can reproduce it, check the socket status corresponding to the connection in each of the points with `ss -apno`

[client] ---> [apiserver] ----> (cluster network) --> [aggregated apiserver]

**Comment by robbie-demuth** [comment]
I recently opened [an issue against controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/issues/1938) describing a similar issue, but with a CRD instead of an Aggregated API. I'm not super familiar with Aggregated APIs, but I don't believe CRDs incur the extra hops that's thus far been discussed here

**Comment by tkashem** [comment]
@tkashem
