### ISSUE TITLE
Fail to pull docker image from private registry server

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubernetes/kubernetes#10831]
Hi, I'm facing the issue below when kubelet tried to pull image from a private registry, and need user authentication:
```
Failed to pull image "<index_server>/nkwanglei/nodejssample": image pull failed for <index_server>/nkwanglei/nodejssample, this may be because there are no credentials on this request. details: (Error: image nkwanglei/nodejssample:latest not found)
```
And I followed the document below, in section "Configuring Nodes to Authenticate to a Private Repository"

https://github.com/GoogleCloudPlatform/kubernetes/blob/4b60e4892fc3d9d593214afbcb79ca3e28301d7e/docs/images.md

But the issue still exist, seems .dockercfg file didn't take effect when kubelet tried to pull the image, anything else I should do to make it work?

BTW, if I manually do the "docker pull <index_server>/nkwanglei/nodejssample" on the same node, then the image can be pulled successfully.

My kubenetes version is v0.18.2, thanks!

**Comment by nkwangleiGIT** [comment]
I also tried "Specifying ImagePullSecrets on a Pod", and it worked per namespace level. So I have to create a secret for each namespace and specify imagePullSecrets for each pod to be created.
Do we have global secret object that we can share across namespace if we don't support "Configuring Nodes to Authenticate to a Private Repository" any more?
Thanks!

**Comment by yujuhong** [comment]
> Do we have global secret object that we can share across namespace

I am not aware of a global secret object...

> But the issue still exist, seems .dockercfg file didn't take effect when kubelet tried to pull the image, anything else I should do to make it work?

There has been some discussion in #7954. Some suggestions include trying paths such as `/.dockercfg`, `/var/lib/kubelet/.dockercfg`, etc. One https://github.com/GoogleCloudPlatform/kubernetes/issues/7954#issuecomment-115241561 suggested using `https://` instead.

**Comment by nkwangleiGIT** [comment]
hi yujuhong,
thanks for your help The following approach works for me:
1. Copy .dockercfg to system root folder -> "/", not user home folder
2. Add https to the index server
I think we need to refine the documentation or fix the code, thanks!

**Comment by yujuhong** [comment]
@nkwangleiGIT, I'm glad that it worked out for you. Would you like to submit a PR to fix the document?

**Comment by yujuhong** [comment]
By the way, I think when $HOME was not declared, docker defaults to searching the current directory for the .dockercfg file. In this case, it happens to be '/'
