### ISSUE TITLE
kube-proxy in ipvs mode leaves real server weight as 0 after restart

### ISSUE THREAD

**Issue by mkgrei** [kubernetes/kubernetes#108319]
### What happened?

Entry in ipvs real sever remains at weight=0 after kube-proxy restarts. (During 1.21 -> 1.22 kubernetes cluster upgrade.)

Related to https://github.com/kubernetes/kubernetes/issues/92019

As the related issue is considered closed, I will report this issue again as the problem still persists in newer version. Might because of some corner cases.

### What did you expect to happen?

Real server weight should be 1 when endpoints is ready.

### How can we reproduce it (as minimally and precisely as possible)?

- Use kube-proxy in ipvs mode
- Deploy a service resource and its backend pods
- Make real sever not ready (or may need node not ready) so as to trigger graceful delete in kube-proxy
- Before kube-proxy deletes the entry from ipvs, restart kube-proxy
- Kube-proxy becomes ready and leave the weight=0 entry as it is
- Service is no longer accessible through cluster ip
- When accessed, dmesg shows kernel messge error of `IPVS: rr: TCP <cluster ip>:<port> - no destination available`

- Deletion of pod will trigger kube-proxy to remove weight=0 entry from ipvs so that after the entry is recreated service will become accessible
- If service is 1. .spec.type: LoadBalancer, and, 2. .spec.externalTrafficPolicy: Local, and, 3, service is accessed from loadbalancer IP, the entry in ipvs for loadbalancer IP will only have endpoints in the same node. If backends is DaemonSet, the only one endpoints will have weight=0 thus causing connection failure

### Anything else we need to know?

After kube-proxy restarts, endpoints will be processed in the following lines.

https://github.com/kubernetes/kubernetes/blob/b56e432f2191419647a6a13b9f5867801850f969/pkg/proxy/ipvs/proxier.go#L2122

Only when the entry is in the gracefuldeleteManager.InTerminationList will be deleted. Which is not the case if kube-proxy restarts before it deletes the ipvs entry.

An existing entry in the ipvs is sufficient for endpoint to be considered healthy. Weight is not considered.

kube-proxy should treat ipvs entry properly by the either the following two ways.

- kube-proxy should initiate InTerminationList and put ipvs entry with weight=0 into the termination list
- kube-proxy should also look for weight in the ipvs entry instead of only UniqueRSName

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-premises
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux hostname 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mkgrei** [comment]
Graceful delete of ipvs is not only triggered when pod is in terminating phase. Graceful delete seems to be triggered when endpointslice status is ready=false.

This will happen when node become not ready. However, after the node become ready again, pods on the node will only be recreated if the duration of NotReady is longer than certain time. Otherwise the pod will just become ready again.

If the node will not recreate the pods && kube-proxy set the pods to the graceful delete queue && kube-proxy restarts before deletion and all cache is cleared, kube-proxy will keep ipvs entry with weight=0 even if the real server is ready.

Please correct me if I misunderstand something.

**Comment by uablrek** [comment]
Seems like a legit bug to me. I can't triage until wednesday though.

**Comment by uablrek** [comment]
I can't recreate this when I try to follow thre inscructions with pod not-ready rather than node not ready. When the pod is made ready again is not stated, so I tried;

1. Make a connection to a pod
2. make it not-ready. The weight is set to 0, the connection prevails
3. Re-start kube-proxy. The weight is still 0, connection still working
4. Make the pod ready
5. The weight is set to 1 after a whils, as it should

**Comment by uablrek** [comment]
I triage this issue as a bug, but it's really a duplicate of https://github.com/kubernetes/kubernetes/issues/92019 which was never fixed (it seems). Don't know if the proper action is to close this issue and re-open #92019.

/triage accepted

**Comment by uablrek** [comment]
@aojea @thockin Please instruct if this issue shall be closed as duplicate and https://github.com/kubernetes/kubernetes/issues/92019 re-opened

@andrewsykim PTAL at https://github.com/kubernetes/kubernetes/issues/92019

**Comment by andrewsykim** [comment]
That does seem costly to do on every endpoint sync. Is there an alternative solution we can explore where we assess all endpoints once when kube-proxy initially starts up?

**Comment by uablrek** [comment]
This is a startup-only problem. It should be solved with a one-time action.

**Comment by aryan9600** [comment]
How about adding modifying `syncProxyRules()` to be `syncProxyRules(updateWeights  bool)`? We could then check and update the real server weights only when `updateWeights` is true.
Only `OnEndpointSliceSynced` and `OnServicesSynced` will be modified to  call `syncProxyRules(true)`, all other users will call the function with false. Since these two functions, are only called during startup, we won't be doing this monitoring every endpoint sync.

**Comment by aryan9600** [comment]
cc: @uablrek @andrewsykim
