### ISSUE TITLE
controller-manager gc sync event failed

### ISSUE THREAD

**Issue by niuyueyang1996** [kubernetes/kubernetes#108318]
### What happened?

15:30:38.355384    2136 graph_builder.go:279] garbage controller monitor not yet synced: events.k8s.io/v1, Resource=events

var ignoredResources = map[schema.GroupResource]struct{}{
	{Group: "", Resource: "events"}: {},
}

ignoredResources group miss match with api-resource

events.k8s.io/v1

### What did you expect to happen?

ignore sync event

### How can we reproduce it (as minimally and precisely as possible)?

etcd have event key more than 4 million
restart kube-apiserver or controller-manager

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.20.7
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lavalamp** [comment]
GC shouldn't be watching events.

I'm not really understanding this bug report, unfortunately?
