### ISSUE TITLE
Move CEL openapi integration code out of third_party/forked/celopenapi/model/registry.go

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#108346]
We've made enough changes to the code in staging/src/k8s.io/apiextensions-apiserver/third_party/forked/celopenapi/model, that it's not really helpful to think of it as forked code.

More practically, having [gofmt disabled](https://github.com/kubernetes/kubernetes/blob/3213a92802b91ed718578f51b14916105fb0c3da/hack/verify-gofmt.sh#L44) make it inconvenient.

I'd like to move it out of third_party and into something like staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/model.

**Comment by mk46** [comment]
I would like to work on this.
/assign

**Comment by jpbetz** [comment]
Thanks @mk46. Would you coordinate with @jiahuif who is also considering moving some of the CEL code around to make some future work possible.

**Comment by mk46** [comment]
> Thanks @mk46. Would you coordinate with @jiahuif who is also considering moving some of the CEL code around to make some future work possible?

Sure. Thanks for considering me.
