### ISSUE TITLE
Add a new --pod-logs-directory flag to Kubelet

### ISSUE THREAD

**Issue by h4ghhh** [kubernetes/kubernetes#108384]
### What would you like to be added?

Add a new --pod-logs-directory flag to Kubelet.
Provide users with ability to set `podLogsRootDirectory`.

### Why is this needed?

The root directory for pod logs is `/var/log/pods` as default, and doesn't support modification.
Sometimes we want container logs to be output to a specified place according to the disk usage plan.

Actually, docker outputs container logs to its workspace, and then creates symlink to  `/var/log/pods` (dockershim does). That's ok.
After runtime switchs to others, like containerd, we should provide a way to set `podLogsRootDirectory`.

**Comment by mate201** [comment]
Hi @h4ghhh!
Can you please reopen this issue?

**Comment by yrwal** [comment]
Fixed by [#112957](https://github.com/kubernetes/kubernetes/pull/112957)
