### ISSUE TITLE
Node error cni plugin not initialized when re-join node in cluster

### ISSUE THREAD

**Issue by thanhlong9x** [kubernetes/kubernetes#108353]
### What happened?

When I re-join nodes in cluster, nodes stuck in NotReady. I show descriced node and see that "cni plugin not initialized" 
![Capture](https://user-images.githubusercontent.com/29721257/155695671-be69b2a1-81cd-44b2-a410-0ffbc8e9a72f.PNG)

But this just happen when I use runtime being containerd, and I need to restart containerd to solver. I think that my containerd lack config. And the below is error that captured from kubelet, I searched the same error but it's not clear for my problem.
![node-not-ready](https://user-images.githubusercontent.com/29721257/155697079-b90d6e7b-121e-4c1c-bc1e-15443e9f8151.PNG)
   

### What did you expect to happen?

I want to know what the original problem is and what difference to make Docker doesn't get a similar error?

### How can we reproduce it (as minimally and precisely as possible)?

Try using the K8S version 1.21.0 and container version is 1.5.7

### Kubernetes version

<details>

```console
$ kubectl version
![Capture](https://user-images.githubusercontent.com/29721257/155699155-b55d32f8-dc16-4736-b38b-9e9f682d30e1.PNG)


</details>


### Cloud provider

<details>
On premise
</details>


### OS version

<details>

![Capture](https://user-images.githubusercontent.com/29721257/155699030-c9c6aa6f-efcf-450e-be10-b4e0251dbe2b.PNG)

</details>


### Install tools

<details>
kubeadm 1.21.0
</details>


### Container runtime (CRI) and and version (if applicable)

<details>
containerd 1.5.7
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> But this just happen when I use runtime being containerd, and I need to restart containerd to solver. I think that my containerd lack config. And the below is error that captured from kubelet, I searched the same error but it's not clear for my problem.

/sig node
in case this is a known issue with containerd.

**Comment by ehashman** [comment]
This bug doesn't seem to have enough details to reproduce or further investigate. You must include your cluster version, the container runtime, kubelet logs, and any relevant Kubernetes manifests along with clear steps to reproduce so we can help with your issue.

Once more details are provided, the bug will be accepted.

/triage needs-information
