### ISSUE TITLE
[Failing test] kubelet-gce-e2e-lock-contention 

### ISSUE THREAD

**Issue by adisky** [kubernetes/kubernetes#108348]
### Which jobs are failing?

kubelet-gce-e2e-lock-contention

### Which tests are failing?

![image](https://user-images.githubusercontent.com/7712693/155668777-0fc06bec-f9bf-4a84-b4e5-8f9b9c2bc00f.png)

### Since when has it been failing?

8/12/2021

### Testgrid link

https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-lock-contention

### Reason for failure (if possible)

It appears that kubelet is not coming up after restart

W0225 06:45:50.261] [0m[sig-node] Lock contention [Slow] [Disruptive] [NodeSpecialFeature:LockContention][0m 
W0225 06:45:50.261]   [1mKubelet should stop when the test acquires the lock on lock file and restart once the lock is released[0m
W0225 06:45:50.262]   [37m_output/local/go/src/k8s.io/kubernetes/test/e2e_node/lock_contention_linux_test.go:41[0m
W0225 06:45:50.262] [It] Kubelet should stop when the test acquires the lock on lock file and restart once the lock is released
W0225 06:45:50.262]   _output/local/go/src/k8s.io/kubernetes/test/e2e_node/lock_contention_linux_test.go:41
W0225 06:45:50.262] [1mSTEP[0m: perform kubelet health check to check if kubelet is healthy and running.
W0225 06:45:50.262] [1mSTEP[0m: acquiring the lock on lock file i.e /var/run/kubelet.lock
W0225 06:45:50.262] [1mSTEP[0m: verifying the kubelet is not healthy as there was a lock contention.
W0225 06:45:50.263] W0225 06:45:40.012604    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W0225 06:45:50.263] [1mSTEP[0m: releasing the lock on lock file i.e /var/run/kubelet.lock, triggering kubelet restart.
W0225 06:45:50.263] [1mSTEP[0m: verifying the kubelet is healthy after restart.
W0225 06:45:50.263] W0225 06:45:40.012898    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W0225 06:45:50.263] W0225 06:45:41.013235    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W0225 06:45:50.263] W0225 06:45:42.013520    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W0225 06:45:50.264] W0225 06:45:43.014671    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused
W0225 06:45:50.264] W0225 06:45:44.014987    2231 util.go:385] Health check on "http://127.0.0.1:10255/healthz" failed, error=Head "http://127.0.0.1:10255/healthz": dial tcp 127.0.0.1:10255: connect: connection refused

### Anything else we need to know?

the test is recently migrated to containerd

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/assign @ipochi 

@ipochi any progress on this?

**Comment by ipochi** [comment]
> /assign @ipochi
> 
> @ipochi any progress on this?


I think the problem is this [line](https://github.com/kubernetes/test-infra/blob/27199ba5579711a98cdf21716cd469d8d866400a/config/jobs/kubernetes/sig-node/containerd.yaml#L1333)

The lock contention arguments should have been part of `--test-args` but instead they are mistakenly added to `--node-test-args`

I think this would have been caught if the job was merged first and then the e2e test, but I assume the reverse order happened hence it didn't get caught.

Anyhow, to test the above with the correct params, how can I do it ? so that we know thats the reason and nothing else.

/cc @adisky

**Comment by ipochi** [comment]
> > /assign @ipochi
> > @ipochi any progress on this?
> 
> I think the problem is this [line](https://github.com/kubernetes/test-infra/blob/27199ba5579711a98cdf21716cd469d8d866400a/config/jobs/kubernetes/sig-node/containerd.yaml#L1333)
> 
> The lock contention arguments should have been part of `--test-args` but instead they were mistakenly added to `--node-test-args` (my bad)
> 
> I think this would have been caught if the job was merged first and then the e2e test, but I assume the reverse order happened hence it didn't get caught.
> 
> Anyhow, to test the above with the correct params, how can I do it ? so that we know thats the reason and nothing else.
> 
> /cc @adisky @SergeyKanzhelev

**Comment by adisky** [comment]
> The lock contention arguments should have been part of --test-args but instead they were mistakenly added to --node-test-args (my bad)

its a kubelet flag, they should be part of `--node-test-args` only, see above job
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml#L1302

Although `--node-test-args` should be single quoted as done everywhere else, possibly it could be a problem?

> Anyhow, to test the above with the correct params, how can I do it ? so that we know thats the reason and nothing else.

**Comment by ipochi** [comment]
@adisky 

Thanks for the insight. Yep it seems the `--node-test-args` is the correct place. 
I've created a PR https://github.com/kubernetes/test-infra/pull/25509 to add correct args.
PTAL.

**Comment by Dragoncell** [comment]
Thanks for the PR. After the PR submit, the test is still failing somehow with 
```
test/e2e_node/lock_contention_linux_test.go:41
Timed out after 10.001s.
Expected
    <bool>: false
to be true
test/e2e_node/lock_contention_linux_test.go:85
```

**Comment by ipochi** [comment]
> Thanks for the PR. After the PR submit, the test is still failing somehow with
> 
> ```
> test/e2e_node/lock_contention_linux_test.go:41
> Timed out after 10.001s.
> Expected
>     <bool>: false
> to be true
> test/e2e_node/lock_contention_linux_test.go:85
> ```

Thanks, I know about that, hence https://github.com/kubernetes/kubernetes/pull/108563

**Comment by ipochi** [comment]
@adisky @SergeyKanzhelev 

The test passes https://k8s-testgrid.appspot.com/sig-node-kubelet#kubelet-gce-e2e-lock-contention
