### ISSUE TITLE
Flag stable metric changes for additional approval

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#108497]
### What would you like to be added?

Currently, stable metric changes can be approved by top-level approvers and are not obviously "special" to a contributor.

We have verify scripts that will prevent adding or changing stable metrics without updating Instrumentation-owned files, but the errors can easily be "fixed" by running the corresponding update script. Contributors may end up doing so to fix the verify errors and not understand the consequences of promoting a metric to "stable" status.

We would like to consider the following:

- [x] Migrate the documentation for stable metrics from KEP to the community/developer docs: https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/metrics-validation-and-verification.md#motivation https://github.com/kubernetes/enhancements/blob/master/keps/sig-instrumentation/1209-metrics-stability/kubernetes-control-plane-metrics-stability.md#stability-classes
- [x] Add a new label that flags stable metrics changes, ex. `kind/stable-metrics-change`, added from the OWNERS file in https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/testdata/OWNERS required for stable metrics
- [x] When the label is applied, a comment from the bot that alerts contributors of the stable metric guidelines, similar to https://github.com/kubernetes/test-infra/blob/f1cd113bfc274d82fa207643653e681555549577/config/jobs/kubernetes/sig-k8s-infra/trusted/sig-contribex-k8s-triage-robot.yaml#L3-L49
- [ ] Do we also want to consider adding `options.no_parent_owners: true` to the stable metrics OWNERS file to avoid accidental merges from top-level approvers?

### Why is this needed?

We had some contributors join the latest SIG Instrumentation meeting requesting to add some labels to stable metrics. They were under the impression that stable metrics worked similar to other Kubernetes APIs, and thus they could make "compatible" API changes.

This is not the case, and they were unaware of the stable metrics documentation. I think it would be good to flag this documentation to anyone making stable metrics changes, in the same way that we flag API changes and point contributors to that documentation.

/sig instrumentation contributor-experience
/cc @logicalhan @dashpole @CatherineF-dev

**Comment by dgrisonnet** [comment]
> Do we also want to consider adding options.no_parent_owners: true to the stable metrics OWNERS file to avoid accidental merges from top-level approvers?

I don't think we had any issue with top-level approvers graduating metrics to stable in the past, but I also don't think they should be able to do that, so I would be in favor of that change.

**Comment by sftim** [comment]
Related, stable metrics changes should some day trigger a docs PR to update a reference doc.
(there's no reference doc listing stable metrics yet, but I hope that changes)
