### ISSUE TITLE
Simplify node status update volumeAttached list

### ISSUE THREAD

**Issue by jingxu97** [kubernetes/kubernetes#108433]
### What would you like to be added?

The current logic in node_status_updater, it retrieves the list of nodes that need to be updated in node status (due to new volumes are attached to that node). At the same time, it mark those node in actual state for updateNodeStatusUpdateNeeded as False (those nodes do no need to be updated in node status any more). 

Then node_status_updater will try to connect API server to update the node status, if it fails, it need to update the actual state to mark those node needs to be updated again. This logic could be simplified to only mark node in actual state to set updateNodeStatusUpdateNeeded to false after update to API server successfully. 

There was a bug due to this logic before because node_status_updater return immediately after it hit any error during update when iterating the node list. So it is possible that after update one node and failed, the rest of nodes are no longer marked as updateNodeStatusUpdateNeeded. See details in issue https://github.com/kubernetes/kubernetes/issues/107973  

### Why is this needed?

Simplify logic here can avoid mistakes mentioned in issue https://github.com/kubernetes/kubernetes/issues/107973

**Comment by NikhilSharmaWe** [comment]
@jingxu97 Do we need any improvements after the PR https://github.com/kubernetes/kubernetes/pull/108167 is merged because in the description I do not see any signs of improvements needed ?

Please inform I will look forward to work on it.

**Comment by jingxu97** [comment]
```
This logic could be simplified to only mark node in actual state to set updateNodeStatusUpdateNeeded to false after update to API server successfully.
```

this is the logic I am thinking to change. Before it first mark all nodes from NodeStatusUpdateNeeded list to false (which means no update needed for these nodes) and then add them back if node update fails. I think it is better to mark the node to no update needed after update successfully.
