### ISSUE TITLE
nil pointer issue on Time object

### ISSUE THREAD

**Issue by armstrongli** [kubernetes/kubernetes#108435]
### What happened?

debug encounter panics on Time object. but panic doesn't happen when running it.

<img width="727" alt="image" src="https://user-images.githubusercontent.com/8025018/156272701-248a47d1-e9bb-493e-9753-034baed7619f.png">

### What did you expect to happen?

no panics

### How can we reproduce it (as minimally and precisely as possible)?

```go
func TestDebugPanic(t *testing.T) {
	p := v1.Pod{
		ObjectMeta: metav1.ObjectMeta{},
	}
	t.Log(p.String())
	t.Log(p.String())
}
```

### Kubernetes version

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go
head commit.

### Cloud provider

no cloud provider needed

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
/unassign
as someone has created pr.

**Comment by MadhavJivrajani** [comment]
@armstrongli I'm not sure this is a bug. I'm not really able to reproduce it as well (tried with a debugger as well) and again no panic occurs when you actually run it. `p.String()` simply formats the struct here, nil dereference or not doesn't really come into picture. Please attach a test that proves an actual panic occurs in some form. 
/remove-kind bug

**Comment by armstrongli** [comment]
it panics when debugging step by step. it doesn't when running it directly. that's the wired part.

**Comment by liggitt** [comment]
see previous discussion in https://github.com/kubernetes/kubernetes/pull/105982

**Comment by fedebongio** [comment]
/assign @liggitt @MadhavJivrajani 
Thank you Jordan and Madhav for taking a look!
/triage accepted

**Comment by jpbetz** [comment]
/triage accepted
Any interest in this?

**Comment by armstrongli** [comment]
this is the issue in debug tool(delve) issue in old version mac OS or old command line tools . after upgrade the command line tool, it doesn't panic anymore. 

@jpbets , thank you for your interest on this issue.
