### ISSUE TITLE
Extended api server blocks deletion of namespace

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/kubernetes#108427]
### What happened?

We have deployed a k8s extended apiserver in, say namespace "kubedb". Later we try to `k delete ns kubedb`. The namespace stays in terminating stage. If I check the status.conditions of the namespace, I see

```
  - lastTransitionTime: "2022-03-01T16:21:45Z"
    message: 'Discovery failed for some groups, 9 failing: unable to retrieve the
      complete list of server APIs: mutators.autoscaling.kubedb.com/v1alpha1: the
      server is currently unable to handle the request, mutators.dashboard.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, mutators.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, mutators.ops.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, mutators.schema.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, validators.dashboard.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, validators.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, validators.ops.kubedb.com/v1alpha1:
      the server is currently unable to handle the request, validators.schema.kubedb.com/v1alpha1:
      the server is currently unable to handle the request'
    reason: DiscoveryFailed
```

The problem seems to be that K8s is waiting to delete resources provided by the EAS. But the EAS pods are already gone (garbage collected). So, the namespace deletion is stuck.

The solution seems to manually delete the apiservices by hand. Then I see that the namespace goes away.

### What did you expect to happen?

This seems like an edge case that k8s garbage collector should automatically handle. It should be possible to watch apiservices and when the namespace used by an apiservice.spec.service is deleted, that apiservice should be automatically deleted by the namespace finalizer.

### How can we reproduce it (as minimally and precisely as possible)?

Just take any EAS like the k8s.io/sample-apiserver, deploy it in k8s and then delete the namespace where it is deployed.

### Anything else we need to know?

I have tried making the namespace owner of the apiservices. But it does not help unless namespace is deleted in the forground. `k delete ns kubedb --cascade=foreground` . 

This is also bad UX. We are deploying our EAS using helm. There is no easy way to set this owner reference.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-26T08:10:51Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
any
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
The namespace controller must verify all registered API types are cleaned up before it can safely permit a namespace to be deleted. Deleting a backing service for an APIService without removing the APIService objects is a usage error. It's not generally safe for the controller to assume that it can delete APIService objects (you could be recreating or relocating the service, and the data would appear again when you did)

**Comment by tamalsaha** [comment]
> Deleting a backing service for an APIService without removing the APIService objects is a usage error.

Here I have deleted the namespace. Is namespace is considered "a backing service for an APIService"?

> It's not generally safe for the controller to assume that it can delete APIService objects (you could be recreating or relocating the service, and the data would appear again when you did)

I understand. Should it be possible for the user to say that namespace to garbage collect such apiservices (instead of doing so automatically)?

**Comment by liggitt** [comment]
> Here I have deleted the namespace. Is namespace is considered "a backing service for an APIService"?

The service was in the namespace, so yes... that triggered deletion of the service and pods backing the APIservice before you removed the APIservice

> Should it be possible for the user to say that namespace to garbage collect such apiservices (instead of doing so automatically)?

cluster-scoped objects don't have the ability to indicate they are owned by namespaced objects, no

**Comment by tamalsaha** [comment]
So, is there anything that can be done at the k8s level? Or, the only option is to tell users  who get into such a situation is to just clean up the apiservices manually and then wait for the ns deletion to happen.

**Comment by liggitt** [comment]
If the API group/version represented by an APIService is gone and isn't coming back, they should delete that APIService object. If it could come back, they need to restore functioning of the backing service so the namespace controller can ensure resources in that group/version don't exist before it will finalize any terminating namespaces.

**Comment by sftim** [comment]
It might be helpful to log an explanatory Event when someone tries to delete a namespace that holds an APIService (that will then block / have an impact on removal of the namespace).

**Comment by kkkkun** [comment]
When ns's status is terminating, if ns's change, it will update status.
https://github.com/kubernetes/kubernetes/blob/34a6a7ca11d2ce257415c02b07c1b80678188769/pkg/controller/namespace/deletion/namespaced_resources_deleter.go#L548

**Comment by shay-berman** [comment]
@tamalsaha i have the same issue, 
how can I delete all kubedb from cluster including these mutations and validation to avoid blocking namespace deletion?

**Comment by tamalsaha** [comment]
You can delete the apiservices, mutatingwebhookconfiguration & validatingwebhookconfiguration using `kubectl delete`. If you need further help, please email us directly. I don't want to litter this community thread with vendor specific stuff.
