### ISSUE TITLE
[sig-network] Services [It] should be able to up and down services

### ISSUE THREAD

**Issue by hanamantagoudvk** [kubernetes/kubernetes#108424]
### Which jobs are failing?

E2E sig-network

### Which tests are failing?

[sig-network] Services [It] should be able to up and down services

### Since when has it been failing?

NA

### Reason for failure (if possible)

  Mar  1 17:19:31.858: Unexpected error:
      <*errors.StatusError | 0xc003dbc820>: {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "pods \"verify-service-up-host-exec-pod\" already exists",
              Reason: "AlreadyExists",
              Details: {
                  Name: "verify-service-up-host-exec-pod",
                  Group: "",
                  Kind: "pods",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 409,
          },
      }
      pods "verify-service-up-host-exec-pod" already exists
  occurred

### Relevant SIG(s)

/sig

**Comment by aojea** [comment]
you have to add more logs, that snippet is not enough to understand the problem, I think that github allow to attach tarballs or you just can link to a gist

**Comment by dcbw** [comment]
@hanamantagoudvk would you be able to add the logs requested by @aojea ? Thanks!

**Comment by hanamantagoudvk** [comment]
@dcbw @aojea : This issue can be closed as it was not genuine issue. It was looks like false alarm. If i see it again, i will raise it with proper logs.

**Comment by aojea** [comment]
> @dcbw @aojea : This issue can be closed as it was not genuine issue. It was looks like false alarm. If i see it again, i will raise it with proper logs.

/close
Thanks
