### ISSUE TITLE
Reduce amount of statusStack logs when server timeouts a lot

### ISSUE THREAD

**Issue by Argh4k** [kubernetes/kubernetes#108488]
### What would you like to be added?

/sig scalability 

We should limit the number of stackTraces that we print in case of timeout. I am thinking about having a limit of stackTraces that can be logged in a specific time window, but I'm happy to discuss other possible solutions for this.

### Why is this needed?

Currently for each timeout we log additional statusStack with the part of runtime stack that should help us to understand what caused the timeout. 

https://github.com/kubernetes/kubernetes/blob/52cd4d53ac8ac33cacd3d2c618cf22f1e3fd6a7e/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L321-L326

https://github.com/kubernetes/kubernetes/blob/52cd4d53ac8ac33cacd3d2c618cf22f1e3fd6a7e/staging/src/k8s.io/apiserver/pkg/server/httplog/httplog.go#L94-L96

In timeout handler in case of timeout we set response status to 504
https://github.com/kubernetes/kubernetes/blob/52cd4d53ac8ac33cacd3d2c618cf22f1e3fd6a7e/staging/src/k8s.io/apiserver/pkg/server/filters/timeout.go#L241-L251

Now, in a situation, where apiserver is overloaded and timeouts a lot, because it cannot handle all the requests, we would log statusStack for every request that time outs. Each stackTrace uses  50*1024 bytes, which from my experience is  around 6k characters. Adding to that fact, that klog is running synchronously, such behavior can degrade performance of kube-apiserver even more.

**Comment by NikhilSharmaWe** [comment]
@Argh4k Could you please elaborate about the approach should be taken for adding this feature through your suggestion
- `having a limit of stackTraces that can be logged in a specific time window`.

Looking forward to work on this.

**Comment by Argh4k** [comment]
I think we can approach it in a few different ways. For example:
- If we logged stackTrace for some request within last let's say 2 seconds, do not log this stackTrace
- If we logged more than 30 stackTraces in last minute, do not log this stackTrace

Overall anything that throttles the number of stackTraces that we produce is a viable solution for me.

**Comment by NikhilSharmaWe** [comment]
@Argh4k Could you please give some info about where we need to add these new conditions (when we get multiple timeouts simultaneously) we are thinking about adding.

Some code pointers will be really helpful.
