### ISSUE TITLE
Add sinceTime to api swagger

### ISSUE THREAD

**Issue by gfvirga** [kubernetes/kubernetes#108498]
### What would you like to be added?

Hello,

I am looking for help to re-add [sinceTime ](https://github.com/kubernetes/kubernetes/blob/85c43df3f6090f13a1004098a852553d1c61c745/pkg/apis/core/types.go#L4651) from the PodLogOptions REST call into the swagger file.
I have tried a few things locally on my machine and when I run the generator script it creates the correct options in `zz_generated.deepcopy` files, but it does not get added to the swagger.json file, it skips the option `sinceTime`.

This option is fully functional and it is also available in `kubectl --since-time=''` for years. I tested the API directly and the option works as well, but I would rather use the official clients for this. 

Closed issue about this problem - https://github.com/kubernetes/kubernetes/pull/98907

### Why is this needed?

The official documentation is missing the `sinceTime` Options - https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#get-read-log-of-the-specified-pod

The kubernetes-clients who rely on the swagger.json to auto generate the options are also missing `sinceTime`
Java:
```
apiInstance.readNamespacedPodLog(name, namespace, container, follow, insecureSkipTLSVerifyBackend, limitBytes, pretty, previous, sinceSeconds, tailLines, timestamps);
```

Python:
```
api_response = api_instance.read_namespaced_pod_log(name, namespace, container=container, follow=follow, insecure_skip_tls_verify_backend=insecure_skip_tls_verify_backend, limit_bytes=limit_bytes, pretty=pretty, previous=previous, since_seconds=since_seconds, tail_lines=tail_lines, timestamps=timestamps)
```

JavaScript: https://kubernetes-client.github.io/javascript/classes/corev1api.corev1api-1.html#readnamespacedpodlog
```
readNamespacedPodLog(name: string, namespace: string, container?: string, follow?: boolean, insecureSkipTLSVerifyBackend?: boolean, limitBytes?: number, pretty?: string, previous?: boolean, sinceSeconds?: number, tailLines?: number, timestamps?: boolean, options?: { headers: {} }): Promise<{ body: string; response: IncomingMessage }>
```

**Comment by CKchen0726** [comment]
I took a checking and found that data has the type metav1.Time will not be added into `swagger.json` with "/api/v1/namespaces/{namespace}/pods/{name}/log", other than "io.k8s.api.core.v1.PersistentVolumeClaimCondition", but I don't know why.

Example:
```
"io.k8s.api.core.v1.PersistentVolumeClaimCondition": {
      "description": "PersistentVolumeClaimCondition contails details about state of pvc",
      "properties": {
        "lastProbeTime": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Time",
          "description": "Last time we probed the condition."
        },
        "lastTransitionTime": {
          "$ref": "#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.Time",
          "description": "Last time the condition transitioned from one status to another."
        },
        "message": {
          "description": "Human-readable message indicating details about last transition.",
          "type": "string"
        },
```

**Comment by gfvirga** [comment]
@CKchen0726, Thanks for checking. I tested the API call and SinceTime query works fine. I will end up using the API directly.

Where do you see that it won't be added? There are a lot of `meta.v1.Time` being used in the API.

**Comment by CKchen0726** [comment]
@gfvirga I try in three ways. Firstly, add a new structure with metav1.Time and exec hack/update-openapi-spec.sh and the new variable will be not added into swagger.json, Secondly, add a new string variable into PodLogOptions and exec hack/update-openapi-spec.sh and the new variable will be added into swagger.json, Finally, change sinceTime to be a string  and exec hack/update-openapi-spec.sh and the new variable will be added into swagger.json

**Comment by johnflavin-fw** [comment]
Hi, sorry for reviving an old issue, but this is still a problem. Is there anything that can be done to get the `sinceTime` parameter into the openapi spec so that client libraries can use it?

**Comment by MoritzWeber0** [comment]
Still not resolved unfortunately.
