### ISSUE TITLE
remove `SelectorSpread` plugin

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#108444]
### What would you like to be added?

Feature gate `DefaultPodTopologySpread` is GA, shall we remove `SelectorSpread` plugin then. I also get support from https://github.com/kubernetes/kubernetes/pull/91793#issuecomment-639800733.  Or next release will be the proper time.

### Why is this needed?

Remove unneeded plugin.

**Comment by kerthcet** [comment]
cc @Huang-Wei @alculquicondor @ahg-g

**Comment by alculquicondor** [comment]
We need to do it for a new ComponentConfig version

I think we should be ready to graduate component config to v1 next release (1.25) https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/785-scheduler-component-config-api

Do you want to own that?

That doesn't mean that we can remove the code in 1.25. We need to support v1beta3 for at least 2 more releases after we publish a v1. So the code would go away in 1.27

**Comment by kerthcet** [comment]
I'll take this into my TODO list then. Thanks aldo.

**Comment by alculquicondor** [comment]
wait, shouldn't we revert #111032 and add SelectorSpread to the list?

**Comment by kerthcet** [comment]
It's used to validate the removed plugins to make sure they are not exist in kube scheduler profile,  but `selectorSpread` not removed yet. Maybe we can revert the pr and add it to the list when we do remove the `selectorSpread` plugin, but it's two releases later.

**Comment by alculquicondor** [comment]
Yes please, revert and add SelectorSpread to the list of invalid plugins in v1.

**Comment by kerthcet** [comment]
I already created the placeholder pr here https://github.com/kubernetes/website/pull/35044, would like to finish it next week.

**Comment by kerthcet** [comment]
`SelectorSpread` plugin in marked deprecated in https://github.com/kubernetes/kubernetes/pull/110534

**Comment by kerthcet** [comment]
/remove-lifecycle stale
I'd like to remove this in v1.27 as planned

**Comment by kerthcet** [comment]
We marked selectorSpread as invalid in v1.25, I think we can remove the plugin now. cc @alculquicondor for confirmation.

**Comment by alculquicondor** [comment]
We can remove v1beta2 in 1.28 https://github.com/kubernetes/kubernetes/blob/c829397f7a1fa956766f6479a8ca454b6937feda/cmd/kube-scheduler/app/options/configfile.go#L57, so we are not ready yet

**Comment by kerthcet** [comment]
Do you mean we should wait for at least 3 releases before we remove `selectorSpread` plugin?

**Comment by sanposhiho** [comment]
I can take it if @kerthcet is ok with that.

**Comment by kerthcet** [comment]
Thanks @sanposhiho I have raised PR https://github.com/kubernetes/kubernetes/pull/117720
