### ISSUE TITLE
External resources fail to be DNS-resolved from PreStop hook on pod termination

### ISSUE THREAD

**Issue by A-Zaporozhchenko** [kubernetes/kubernetes#108587]
### What happened?

I'm trying to save the application state to the external location on pod termination. To do this I selected the Kubernetes pod PreStop hook. PreStop hook calls the application HTTP endpoint that needs to save state to AWS Systems Manager Parameter Store. From within the app I receive an error alike

`java.net.UnknownHostException: sts.eu-west-1.amazonaws.com`.

To scope down the issue I replaced calling the application endpoint with `curl`-ing the random external endpoint (say, google.com). It doesn't work either. From the Kubernetes events I see **_FailedPostStartHook_** event with the following message

> Exec lifecycle hook ([/bin/sh -c curl https://google.com >> /proc/1/fd/1]) for Container "nginx" in Pod "nginx-76744d59d-jbkft_default(e6ce6061-9c9f-4b52-8c5a-f7cf22d23c2d)" failed - error: command '/bin/sh -c curl https://google.com >> /proc/1/fd/1' exited with 6: curl: (6) Could not resolve host: google.com\n"

There is no limitation for calling the external resources from pod PreStop hook is specified in the docs (https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) so I assume it's either a bug or an undocumented limitation.

### What did you expect to happen?

I expect to be able to query the external resources (like `google.com` or `sts.eu-west-1.amazonaws.com`) from PreStop hook without any issues.

### How can we reproduce it (as minimally and precisely as possible)?

Here is the deployment spec

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2022-03-08T12:55:30Z"
  generation: 4
  labels:
    app: nginx
  name: nginx
  namespace: default
  resourceVersion: "74206235"
  uid: 64b7a46f-253b-4020-aaf1-6ec5e3022520
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl https://google.com >> /proc/1/fd/1
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-03-08T12:55:30Z"
    lastUpdateTime: "2022-03-08T13:13:13Z"
    message: ReplicaSet "nginx-76744d59d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-03-08T13:30:39Z"
    lastUpdateTime: "2022-03-08T13:30:39Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

It can be created via CLI by running this
`kubectl create deployment nginx --image=nginx`
and then adding the PreStop hook to the deployment spec
```
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - curl https://google.com >> /proc/1/fd/1
```

### Anything else we need to know?

Similar question was asked at SO 1.5 years ago - https://stackoverflow.com/questions/64381345/what-is-the-valid-http-request-that-can-be-used-within-a-prestop-hook.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
$ uname -a
Linux nginx-76744d59d-xhd8m 5.4.176-91.338.amzn2.x86_64 #1 SMP Fri Feb 4 16:59:59 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
We use CoreDNS in the cluster

```
.:53
[INFO] plugin/reload: Running configuration MD5 = 47d57903c0f0ba4ee0626a17181e5d94
CoreDNS-1.8.4
linux/amd64, go1.13.15, 053c4d5c
```
</details>

**Comment by pacoxu** [comment]
I tried to test with your yaml and it is running successfully. 
Could you try to `curl google.com` inside your pod by `kubectl exec -it xxx - curl google.com` to test? Does you dns work correctly?

**Comment by A-Zaporozhchenko** [comment]
@pacoxu The DNS is working and your command succeed on a running pod. The thing is that when I try to execute the very same `curl` in a PostStart hook, it works. It doesn't work only at PreStop hook phase.

I was wondering if it can be a limitation of AWS EKS and not the k8s itself.

**Comment by pacoxu** [comment]
> It doesn't work only at PreStop hook phase.

I still cannot repro it. I wonder if you can test like below:
1. run a pod that will `curl ` continuously and logs the time and `curl` results.
2. add a `PreStop` to curl and log the time & result.

This would help to figure out when the `curl` starts to fail. 

/remove-sig cluster-lifecycle
/sig network node

**Comment by thockin** [comment]
Is there anything special about the way preStop is run?
