### ISSUE TITLE
kubeadm init fails due to kubelet isn't running

### ISSUE THREAD

**Issue by TRIVEDISAGAR37** [kubernetes/kubernetes#108571]
### What happened?

"kubeadm init" continuously fails due to kubelet isn't running or healthy. 

All the certs, manifests files are downloaded and loaded on the system into the "/etc/kubernetes/" pki and manifests files upon init command.

But when it comes to initializing the cluster using thos files using kubelet, it is keep giving me the error. 

[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.

Unfortunately, an error has occurred:
            timed out waiting for the condition

This error is likely caused by:
            - The kubelet is not running
            - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

### What did you expect to happen?

kubernetes control plane node successfully initialized.

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm reset and kubeadm init

### Anything else we need to know?

I see the same issue https://github.com/kubernetes/kubernetes/issues/62897 

But there isn't sufficient information available for solution. 
I have tried everything included in #62897, turning off swap, changing cgroup in /etc/docker/daemon.json file, 

Tried chaning the 10-kubeadm.init, for --cgroup-driver=cgroupfs as well as --fail-swap-on=false

### Kubernetes version

[init] Using Kubernetes version: v1.23.4

### Cloud provider

No

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux master-01 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux



### Install tools

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/area kubeadm
/sig cluster-lifecycle node 
for triage 

After https://github.com/kubernetes/kubernetes/pull/104854, kubeadm changed the swap check to a warning. You can check the init log at the beginning. 

For cgroupfs, there should be an error message like `misconfiguration: kubelet cgroup driver: %q is different from docker cgroup driver: %q", kubeCgroupDriver, cgroupDriver`. I tried to change it to auto-detect the cgroup of container runtime which was not accepted by sig-node in https://github.com/kubernetes/kubernetes/pull/98357/files.
