### ISSUE TITLE
pod's state is still ready/running on a Node that is shut down for more than 2 hours !

### ISSUE THREAD

**Issue by scampagna** [kubernetes/kubernetes#108589]
### What happened?

I've a cluster with one master and 3 workers. I shut down the 3 workers for more than 2 hours.
I typed : kubectl get nodes -o wide and I got 

AME               STATUS     ROLES                  AGE     VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION    CONTAINER-RUNTIME
ip-172-31-25-234   Ready      control-plane,master   9d      v1.23.4   172.31.25.234   <none>        Ubuntu 20.04.3 LTS   5.11.0-1028-aws   docker://20.10.12
worker1            NotReady   <none>                 8d      v1.23.4   172.31.21.205   <none>        Ubuntu 20.04.3 LTS   5.11.0-1022-aws   docker://20.10.12
worker2            NotReady   <none>                 4d2h    v1.23.4   172.31.42.102   <none>        Ubuntu 20.04.3 LTS   5.11.0-1022-aws   docker://20.10.12
worker3            NotReady   <none>                 3d22h   v1.23.4   172.31.36.204   <none>        Ubuntu 20.04.3 LTS   5.11.0-1022-aws   docker://20.10.12

Then I typed : kubectl get pods -o wide
I got

AME                               READY   STATUS    RESTARTS       AGE     IP              NODE      NOMINATED NODE   READINESS GATES
nginx-deployment-9456bbbf9-5sp5s   1/1     Running   2 (18h ago)    3d22h   192.168.182.5   worker3   <none>           <none>
nginx-deployment-9456bbbf9-xwdcx   1/1     Running   2 (2d5h ago)   3d22h   192.168.182.6   worker3   <none>           <none>

We can see that 2 PODs are ready/running on master3, but master 3 is not ready (because shut down).

Then I started only one worker which was worker1, I typed kubectl get pod -o wide and I got 
tef@steflaptop:~/devel/aws/kube$ kubectl get pod -o wide
NAME                               READY   STATUS        RESTARTS       AGE     IP                NODE      NOMINATED NODE   READINESS GATES
nginx-deployment-9456bbbf9-5sp5s   1/1     Terminating   2 (18h ago)    3d22h   192.168.182.5     worker3   <none>           <none>
nginx-deployment-9456bbbf9-7wqrz   1/1     Running       0              3m16s   192.168.235.167   worker1   <none>           <none>
nginx-deployment-9456bbbf9-mn69m   1/1     Running       0              3m16s   192.168.235.168   worker1   <none>           <none>
nginx-deployment-9456bbbf9-xwdcx   1/1     Terminating   2 (2d5h ago)   3d22h   192.168.182.6     worker3   <none>           <none>

### What did you expect to happen?

I expected that the POD were not ready !!!

### How can we reproduce it (as minimally and precisely as possible)?

Create un cluster with 3 nodes. Don't accept POD on the master. Do a deployment of nginx with 2 replicas. Shutdown the 3 nodes and type kubectl get pod ans see if the pod are running or not.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>
AWS
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
This behavior is controlled by kube-controller-manager and  as expected, because all nodes are not-ready, it enters master disruption mode and stop all evictions.

**Comment by Kartik494** [comment]
You could find more information on this behaviour on the [docs](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#preemption)
