### ISSUE TITLE
Pod anti-affinity not respected when binding PVCs to PVs when etcd timeout

### ISSUE THREAD

**Issue by evanskinner** [kubernetes/kubernetes#108560]
### What happened?

I have a stateful set with node anti-affinity set on it so that the pods will all run on different nodes. local-storage is used for the PVCs. This normally all works fine, but in one deployment of the statefulset there was an etcd blip and the PVCs for db-0 AND db-2  both got allocated a PV on the same k8s node. Logs from the scheduler:

```
I0307 08:52:21.705696       1 scheduler_binder.go:522] claim "default/db-ger5-portal-site1-db-0" bound to volume "local-pv-ae78c44d"
...
I0307 08:52:29.727937       1 scheduler.go:433] "Failed to bind pod" pod="default/ger5-portal-site1-db-0"
E0307 08:52:29.728015       1 factory.go:354] "Error scheduling pod; retrying" err="binding rejected: running Bind plugin \"DefaultBinder\": Operation cannot be fulfilled on pods/binding \"ger5-portal-site1-db-0\": etcdserver: request timed out" pod="default/ger5-portal-site1-db-0"
I0307 08:52:30.256333       1 scheduler_binder.go:522] claim "default/db-ger5-portal-site1-db-2" bound to volume "local-pv-5f65ec13"
I0307 08:52:30.761984       1 factory.go:338] "Unable to schedule pod; no fit; waiting" pod="default/ger5-portal-site1-db-0" err="0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 Insufficient cpu."
```

What seems to happen then is the because of the timeout scheduling db-0 in etcd. the scheduler had already linked the db-0 PVC to a PV on node-2, but as the scheduling had failed for db-0 it then merrily scheduled db-2 to the same node-2 and created the PVC fo db-2 on node-2. When it then goes to schedule db-0 again, it finds that the PVC is already linked to a PV on node-2 and so it cannot schedule db-0 to a different node (which is needs to do as db-2 is already on node-2)

I am confused by the message `0/3 nodes are available: 1 node(s) had volume node affinity conflict, 2 Insufficient cpu` and I would have expected it to say `0/3 nodes are available: 2 node(s) had volume node affinity conflict, 1 Insufficient cpu` where node-2 which has the PVC would have insufficient CPU (as it already has pods running on it) and node-0 and node-1 would have a volume node affinity conflict as the pod cannot run on them when the local-storage PVC is linked to a PV on node-2.

### What did you expect to happen?

The PVCs should not be linked to a PV until a pod has been successfully scheduled to a node.

### How can we reproduce it (as minimally and precisely as possible)?

You'd need:

1) local-storage and some created PVs
2) A statefulset with enough members to full the number of avaialble nodes, at least one PVC per pod and a hard node antiaffinity rule
3) A way to introduce the etcd timeout

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux apimdev0162 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nward** [comment]
Hi @evanskinner I had the same issue. I came across this issue when trying to debug it, so thought I'd come back here and let you know how I solved it, in case you are still impacted by this.

There was a similar issue, which had this comment which was the key for me:
https://github.com/kubernetes/kubernetes/issues/49906#issuecomment-319821416
> PVC binding is currently done independently of pod scheduler, and is therefore not integrated with pod anti-affinity policies. I am working on making the PVC binding more integrated with pod scheduling, but it's a big design change and will take a few releases to be fully functional.

I was able to solve this by setting `volumeBindingMode: WaitForFirstConsumer` in my storageClass - which causes the PVC to be created after the consumer (pod) is created. If the pod can't be scheduled, it won't create and bind the PV.

**Comment by evanskinner** [comment]
> Hi @evanskinner I had the same issue. I came across this issue when trying to debug it, so thought I'd come back here and let you know how I solved it, in case you are still impacted by this.
> 
> There was a similar issue, which had this comment which was the key for me: [#49906 (comment)](https://github.com/kubernetes/kubernetes/issues/49906#issuecomment-319821416)
> 
> > PVC binding is currently done independently of pod scheduler, and is therefore not integrated with pod anti-affinity policies. I am working on making the PVC binding more integrated with pod scheduling, but it's a big design change and will take a few releases to be fully functional.
> 
> I was able to solve this by setting `volumeBindingMode: WaitForFirstConsumer` in my storageClass - which causes the PVC to be created after the consumer (pod) is created. If the pod can't be scheduled, it won't create and bind the PV.

Thanks for taking the time to post @nward I'm 99% sure that I already had `volumeBindingMode: WaitForFirstConsumer` set in the storageClass. The issue only happend once. Usually it schedules sensibly. It was only when etcd had a funny few mins that it got it wrong.
