### ISSUE TITLE
Nodes not being able to register after running cluster upgrade test

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#10858]
From https://github.com/GoogleCloudPlatform/kubernetes/issues/10850#issuecomment-119303146, @dchen1107: "test failure after upgrade test due to no node is ready in test cluster. We checked it, and found cbr0 is not configured because master never allocate ip range to node, and docker refuse to start."

My cluster encountered a similar case that @timstclair originally described in https://github.com/GoogleCloudPlatform/kubernetes/issues/10368#issue-91079132

The cluster has been up since before 6/30, and I've pushed a couple of times to run sets of different e2e tests. Yesterday around 5pm I sync'd to HEAD, pushed, and ran e2e. This morning I checked my cluster and saw none of the two nodes were registered.
` kubelet.go:793] Unable to register e2e-test-yjhong-minion-fu35 with the apiserver: the server has asked for the client to provide credentials (post nodes)`

Looking through the e2e log, the whole thing started during the cluster upgrade test.

```
• Failure [877.662 seconds]
Skipped
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:337
  Cluster upgrade
  /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:336
    upgrade-cluster
    /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:335
      should maintain a functioning cluster [It]
      /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:334

      Expected error:
          <*errors.errorString | 0xc2097d1a50>: {
              s: "couldn't find 2 nodes within 5m0s; last error: expected to find 2 nodes but found only 0 (5m7.662755992s elapsed)",
          }
          couldn't find 2 nodes within 5m0s; last error: expected to find 2 nodes but found only 0 (5m7.662755992s elapsed)
      not to have occurred

      /go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:399
```
/var/log/monit.log:
```
[UTC Jul  7 19:39:21] error    : 'docker' process is not running
[UTC Jul  7 19:39:21] info     : 'docker' trying to restart
[UTC Jul  7 19:39:21] info     : 'docker' start: /etc/init.d/docker
[UTC Jul  7 19:39:51] error    : 'docker' failed to start
[UTC Jul  7 19:41:51] error    : 'kubelet' failed, cannot open a connection to INET[127.0.0.1:10255/healthz] via TCP
[UTC Jul  7 19:41:51] info     : 'kubelet' trying to restart
[UTC Jul  7 19:41:51] info     : 'kubelet' stop: /etc/init.d/kubelet
[UTC Jul  7 19:41:51] info     : 'kubelet' start: /etc/init.d/kubelet
[UTC Jul  7 19:41:51] error    : 'kube-addons' process is not running
[UTC Jul  7 19:41:51] info     : 'kube-addons' trying to restart
[UTC Jul  7 19:41:51] info     : 'kube-addons' start: /etc/init.d/kube-addons
[UTC Jul  7 19:41:51] error    : Error: Could not execute /etc/init.d/kube-addons
[UTC Jul  7 19:42:22] error    : 'kube-addons' failed to start
```
/var/log/docker.log:

```
time="2015-07-07T19:36:21Z" level=info msg="-job init_networkdriver() = ERR (1)" 
time="2015-07-07T19:36:21Z" level=fatal msg="Shutting down daemon due to errors: no such network interface" 
time="2015-07-07T19:39:21Z" level=info msg="+job serveapi(unix:///var/run/docker.sock)" 
time="2015-07-07T19:39:21Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)" 
time="2015-07-07T19:39:21Z" level=info msg="+job init_networkdriver()" 
```
kubectl version
```
Client Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-420-ga267e04e549f8d-dirty", GitCommit:"a267e04e549f8d0e16f78ebe6a8c48c26ccb89c4", GitTreeState:"dirty"}
Server Version: version.Info{Major:"0", Minor:"20+", GitVersion:"v0.20.2-440-g639a7dac50a331-dirty", GitCommit:"639a7dac50a331414cc6c47083323388da0d8756", GitTreeState:"dirty"}
```

kubeconfig on the node (the token seems to be missing):
```
apiVersion: v1
kind: Config
users:
- name: kubelet
  user:
    token: 
clusters:
- name: local
  cluster:
     insecure-skip-tls-verify: true
contexts:
- context:
    cluster: local
    user: kubelet
  name: service-account-context
current-context: service-account-context
```

**Comment by dchen1107** [comment]
I marked this as p0 for triage. cc/ @roberthbailey @lavalamp since you two looked at a similar issue last week: #10368

**Comment by lavalamp** [comment]
I'm pretty sure the upgrade process is doing something bad to /var/lib/kubelet/kubeconfig. It also breaks kube-proxy's kubeconfig. Still investigating.

**Comment by roberthbailey** [comment]
Did you do your upgrade with a kube-push rather than a MIG rolling upgrade?

**Comment by yujuhong** [comment]
> Did you do your upgrade with a kube-push rather than a MIG rolling upgrade?

I ran `go run hack/e2e.go -v  -push -test`, so kube-push was involved before running the test. I believe the cluster upgrade test itself used MIG rolling update.

**Comment by lavalamp** [comment]
I'll try and see if kube-push.sh is the culprit.

**Comment by roberthbailey** [comment]
There was some discussion about setting up a jenkins continuos test for the kube-push upgrades but I don't know that it ever happened.

**Comment by lavalamp** [comment]
Somehow the upgrade test seems to have left my master in a broken state...

**Comment by lavalamp** [comment]
Yeah, my master VM's kubelet.log is full of stuff like:

```Failed to pull image "gcr.io/google_containers/kube-scheduler:97cbbdd3d0b9d3105a9debd6a0fef243" from pod "kube-scheduler-kubernetes-master_default" and container "kube-scheduler": [Tag 97cbbdd3d0b9d3105a9debd6a0fef243 not found in repository gcr.io/google_containers/kube-
scheduler, Tag 97cbbdd3d0b9d3105a9debd6a0fef243 not found in repository gcr.io/google_containers/kube-scheduler]```

Not clear if this is from the upgrade test or the kube-push I tried. I'll recreate my cluster and try again.

**Comment by yujuhong** [comment]
More specifically, my e2e test failed after the "node upgrade" step in the test. The relevant logs are here:
https://gist.github.com/yujuhong/fd42dce0cb8e21eef8c5

I am not sure if kube-push was the culprit since the cluster was fine until the middle of the cluster upgrade test.

**Comment by yujuhong** [comment]
> Yeah, my master VM's kubelet.log is full of stuff like:
> 
> Failed to pull image "gcr.io/google_containers/kube-scheduler:97cbbdd3d0b9d3105a9debd6a0fef243" from pod "kube-scheduler-kubernetes-master_default" and container "kube-scheduler": [Tag 97cbbdd3d0b9d3105a9debd6a0fef243 not found in repository gcr.io/google_containers/kube- scheduler, Tag 97cbbdd3d0b9d3105a9debd6a0fef243 not found in repository gcr.io/google_containers/kube-scheduler]

Your case is more similar to the one described in #10868

**Comment by lavalamp** [comment]
kube-push.sh by itself did not seem to cause a problem.

**Comment by lavalamp** [comment]
This keeps totally breaking my cluster. Can the e2e test not be run against a non-e2e cluster? I will set up a dedicated e2e cluster and see if I have better results that way.

**Comment by yujuhong** [comment]
@lavalamp, I am going to tear down my cluster. Is there anything you want to check before that?

**Comment by lavalamp** [comment]
> I am not sure if kube-push was the culprit 

I'm pretty sure we can rule out kube-push.sh, it worked fine for me (or at least didn't break my cluster).

**Comment by mbforbes** [comment]
Unsure how much I can help, but if you want to see lots of previous runs of a cluster-upgrade test on gce immediately post-turnup:
http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-upgrade-gce-step2-upgrade/

We don't test doing both a push *and* an upgrade.

We do have a push-only test that I am not maintaining (focusing only on upgrades for the immediate future). The push-only test seems to be failing before it even starts:
http://kubekins.dls.corp.google.com/job/kubernetes-push-gce-step2-upgrade/

**Comment by quinton-hoole** [comment]
Assigning to @alex-mohr to assign an owner to this.  cc @roberthbailey FYI

**Comment by alex-mohr** [comment]
Is this flagged p0 and milestone/v1.0 because we expect users of v1 binary releases to hit issues with the unsupported push-based upgrades?  

FWIW, the reported failed to pull image bits look a lot like #10868.

Max, are you the closest we have to an upgrade test owner atm?  If so, can you triage as to whether v1 and/or the supported-upgrade path has potential issues due to this?

**Comment by dchen1107** [comment]
I agreed with @alex-mohr this issue might have the same root cause of #10868.

But no matter GKE or push-based upgrades, the underneath mechanisms are the same, and both copy new tar file over to master node, and invoke docker load to install those images. That is why I cc-ed you guys on #10868 at the first place.

**Comment by mbforbes** [comment]
@lavalamp re: https://github.com/GoogleCloudPlatform/kubernetes/issues/10858#issuecomment-119377435, *what* exactly keeps breaking your cluster? Can you give steps to repro?

If this involves kube-push, we may be running into exactly the problems we were trying to avoid by going the "blow away / recreate" upgrade route: weird state mutations due to a push. 

If this doesn't involve kube-push, the Jenkins upgrade job, which does an "up" and then runs the MIG rolling update, hasn't seen this issue as far as I can tell:
http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-upgrade-gce-step2-upgrade/

In the last 30 runs, we saw one failure in the upgrade script after:
```
MINION_NAMES=gce-upgrade-minion-9tja gce-upgrade-minion-wko1
```

and one other failure:
```
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/test/e2e/cluster_upgrade.go:242
All nodes should be ready after test, Not ready nodes: [{{ } {gce-upgrade-minion-54fb   /api/v1/nodes/gce-upgrade-minion-54fb 910c0384-250d-11e5-bbe5-42010af025d6 714 0 2015-07-07 18:06:30 -0700 PDT <nil> map[kubernetes.io/hostname:gce-upgrade-minion-54fb] map[]} {10.245.1.0/24 17768599750437459468 gce://k8s-jkns-gce-living-upgrades/us-central1-f/gce-upgrade-minion-54fb false} {map[cpu:{2.000 DecimalSI} memory:{7863918592.000 BinarySI} pods:{100.000 DecimalSI}]  [{Ready False 2015-07-07 18:09:41 -0700 PDT 2015-07-07 18:09:31 -0700 PDT network not configured correctly }] [{InternalIP 10.240.79.208} {ExternalIP 146.148.93.216}] { 4F9C231A-FF6D-FEFB-0335-25671274F720 57ccedab-ccde-42ba-9551-6f085f6ee5c7 3.16.0-0.bpo.4-amd64 Debian GNU/Linux 7 (wheezy) docker://1.6.2 v0.21.0-28-g1cf9a71aa22e70-dirty v0.21.0-28-g1cf9a71aa22e70-dirty}}}
```

(Note that the above says "network not configured correctly" buried in the error message—relevant?)

I'm happy to help investigate, but given the dead-simple nature of upgrades, I suspect it's much more likely to be an issue with configuration or startup. The upgrade tests would reveal exactly these issues, not cause them.

**Comment by mbforbes** [comment]
Looking at the second failure more, it looks like a node went from "ready" after the update to "not ready" at the end of the test
http://kubekins.dls.corp.google.com/view/Upgrade%20Test%20-%20GCE/job/kubernetes-upgrade-gce-step2-upgrade/392/console

**Comment by lavalamp** [comment]
@mbforbes steps I took:

```
$ make release-skip-tests
$ cluster/kube-up.sh
$ KUBE_CONFIG_FILE=config-default.sh hack/ginkgo-e2e.sh --ginkgo.focus=.*pgrade.* |& less -r
```

Killed it for me twice yesterday.

**Comment by brendandburns** [comment]
I believe that the only supported tests for 1.0 are:

```
$ make release-skip-tests
$ cluster/kube-up.sh
$ KUBE_CONFIG_FILE=config-default.sh hack/ginkgo-e2e.sh --ginkgo.focus=Skipped.*Cluster\supgrade.*upgrade-cluster
```

Apparently the other upgrade tests involve using both kube-push as well as upgrade, and there is a bug in that combination.

Since we never claimed kube-push.sh for upgrade was supported for 1.0, I'm punting this to 1.0 post.

Please file any objections with me.

**Comment by mbforbes** [comment]
I'm leaving the project, so reassigning to... @brendandburns! To multiplex off as desired.

**Comment by brendandburns** [comment]
Node issue so out to @dchen1107 for triage.

**Comment by dchen1107** [comment]
Close the issue since it is obsolete.
