### ISSUE TITLE
definition of "internal" vs "external" service traffic, behavior of LB IP short-circuit

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#108526]
Service traffic can be "internal" or "external" but we never explicitly define exactly what these mean.

[The docs](https://kubernetes.io/docs/concepts/services-networking/service/#external-traffic-policy) say:

> You can set the `spec.externalTrafficPolicy` field to control how traffic _**from external sources**_ is routed.

(emphasis added)

The [internalTrafficPolicy KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy) says:

> This field will be independent from `externalTrafficPolicy`. In other words, `internalTrafficPolicy` only applies to traffic originating _**from internal sources**_

(emphasis added)

These both describe a "source" model: `internalTrafficPolicy` applies to traffic that comes from an internal source (pod, node) and `externalTrafficPolicy` applies to traffic that comes from an external source (outside cluster).

In discussion in the SIG on 2022-03-03, it seemed that most people assumed / believed / desired that we used a "destination" model: `internalTrafficPolicy` applies to traffic that is sent to an internal destination (ClusterIP), while `externalTrafficPolicy` applies to traffic that is sent to an external destination (NodePorts, ExternalIPs, and LoadBalancer IPs).

FWIW, although the docs imply the "source" model, it's not clear that this really means that we actually _intended_ that; if you're only thinking about the "normal" cases (pod to cluster IP, cluster-external to NodePort/ExternalIP/LoadBalancer) then the two models are the same. Eg, the API docs for `internalTrafficPolicy` say:

```
	// InternalTrafficPolicy specifies if the cluster internal traffic
	// should be routed to all endpoints or node-local endpoints only.
```

where "cluster internal" implies to me that they were only really considering the case of internal-to-internal traffic.

----

The current kube-proxy iptables implementation is a mash-up of the two models which also depends on whether you have a functioning LocalTrafficDetector. (ie, if you passed either `--detect-local-mode ...` to explicitly tell it how to detect local traffic, or if you passed `--cluster-cidr ...` which implicitly lets it detect that):

(Ⓢ/~Ⓢ~ = right/wrong according to the "source" model, Ⓓ/~Ⓓ~ = right/wrong according to the "destination" model)

|source|destination|w/ local detector|no local detector|
|----|----|----|----|
|pod|ClusterIP|internal Ⓢ Ⓓ|internal Ⓢ Ⓓ|
|pod|same-node NodePort|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ|
|pod|remote NodePort|external ~Ⓢ~ Ⓓ|external ~Ⓢ~ Ⓓ|
|pod|ExternalIP|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ but sometimes broken|
|pod|LoadBalancer IP|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ but sometimes broken|
|node|ClusterIP|internal Ⓢ Ⓓ|internal Ⓢ Ⓓ|
|node|same-node NodePort|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ|
|node|remote NodePort|external ~Ⓢ~ Ⓓ|external ~Ⓢ~ Ⓓ|
|node|ExternalIP|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ|
|node|LoadBalancer IP|internal Ⓢ ~Ⓓ~|external ~Ⓢ~ Ⓓ|
|external|ClusterIP|internal ~Ⓢ~ Ⓓ|internal ~Ⓢ~ Ⓓ but sometimes broken|
|external|NodePort|external Ⓢ Ⓓ|external Ⓢ Ⓓ|
|external|ExternalIP|external Ⓢ Ⓓ|external Ⓢ Ⓓ|
|external|LoadBalancer IP|external Ⓢ Ⓓ|external Ⓢ Ⓓ|

The reason some of the cases are inconsistent between "w/ local detector" and "no local detector" is that "pod/node to NodePort/ExternalIP/LBIP" connections get short-circuited to the "pod/node to ClusterIP" case, so that if the service is `externalTrafficPolicy: Local`, the behavior doesn't depend on whether there are local endpoints or not. This can always happen for node-to-X connection, but for pod-to-X we can only do it when we have a LocalTrafficDetector.

However, the short-circuiting means that if you have a service which has Local _internal_ traffic policy, then pod-to-LB-IP connections to it won't work from nodes with no endpoints. I am pretty sure that was not the intent; the point of short-circuiting is not that the traffic should be treated as "internal" rather than "external", it's that pod-to-LB-IP traffic should behave the same way as as external-to-LB-IP traffic does, meaning the client isn't responsible for thinking about which nodes have local endpoints, because the load balancer does that for them.

----

Given

1. The "working LocalTrafficDetector" case does not consistently obey either the "source" model or the "destination" model and its behavior is fairly inexplicable.
2. The "no LocalTrafficDetector" case consistently obeys the "destination" model
3. Almost everyone in the SIG seemed to prefer the "destination" model to the "source" model

I think we should declare that the "destination" model is correct, clarify the docs and the Internal Traffic Policy KEP, and fix iptables kube-proxy.

To avoid breaking people using pod/node-to-LB-IP, this also requires fixing the short circuit so that instead of short-circuiting "external" traffic to the "internal" codepath, we instead treat it internally as a third kind of traffic ("traffic that we have to pretend left the cluster and then came back in in a manner that is consistent with `externalTrafficPolicy`").

----

This would mean:
- The "with local detector" and "no local detector" cases would agree in all cases about "internal" vs "external", though the "no local detector" case would still have problems implementing some of the cases correctly.
- Pod/Node to same-node NodePort would be considered "external" rather than "internal". IIRC Tim suggested that this isn't a big deal, because it's unlikely anyone making pod-to-nodeport connections is also using `externalTrafficPolicy: Local`
    - (EDIT) Actually, pod-to-nodeport with `externalTrafficPolicy: Local` [doesn't currently work in most cases anyway](https://github.com/kubernetes/kubernetes/pull/106497/commits/1da8903a09d9a12c660397a33a0e98fe973d121e#diff-92f41de420a097c0419a3cb53cf176a459a742c39f3fa482ab48b1c2fa6fd084R5463-R5476).
    - we could potentially make traffic to NodePorts on 127.0.0.1 be "internal" and traffic to NodePorts on other IPs be "external"...
- Pod/Node to ExternalIP or LoadBalancer IP would always work, even if the service was `internalTrafficPolicy: Local, externalTrafficPolicy: Local` and had no local endpoints. (The mental model here is that for LB IPs, Local traffic policy is purely an internal implementation detail, and clients never have to think about it. As opposed to for NodePorts, where Local traffic policy is an explicitly visible aspect of their behavior, which clients _do_ need to think about.)
    - What exact set of endpoints gets used in the "eTP Local but no local endpoints" case? Is it guaranteed to be the same set of possible endpoints that might be used if an external client had connected to the LB IP? eg, do we ignore topology and possibly use terminating endpoints? Or do we use "the set of endpoints that we would have used if you connected to the service in a way that used Cluster traffic policy"?
- All other connection paths should be unchanged.

**Comment by uablrek** [comment]
Related https://github.com/kubernetes/kubernetes/issues/74383#issuecomment-1059713473

**Comment by aojea** [comment]
ExternalIP and LoadBalancerIP are not necessarily external , there are multiple implementations that create them as Virtual IP inside the cluster, they doesn't exist outside of the cluster, they are just forwarded externally ... MetalLB is a good example

**Comment by thockin** [comment]
@danwinship I think I agree with all of this, except I can't wrap my head around this:

> To avoid breaking people using pod/node-to-LB-IP, this also requires fixing the short circuit so that instead of short-circuiting "external" traffic to the "internal" codepath, we instead treat it internally as a third kind of traffic ("traffic that we have to pretend left the cluster and then came back in in a manner that is consistent with externalTrafficPolicy").

I have read and re-read the text on this, but it's not clicking.  Would another way of expressing this simply be: pod/node to LBIP is a special-case for which ETP=Local is bent to mean "Prefer Local but fall back on Cluster" ?

**Comment by uablrek** [comment]
@danwinship @thockin 

> (The current behavior is that pod/node-to-ExternalIP is treated the same as pod/node-to-LoadBalancer, meaning we'd deal with making it work.)

Then there no problem traffic-wise for proxy-mode=iptables and it can be fixed for pod-to-LB/ExternalIP for [proxy-mode=ipvs](https://github.com/kubernetes/kubernetes/pull/97081) (but node-to-LB/ExternalIP is tricky).

Am I guessing right that it is network-policies that becomes a problem? (I don't know much about network-policies, sorry)

**Comment by danwinship** [comment]
> @danwinship I think I agree with all of this, except I can't wrap my head around this:
> 
> > To avoid breaking people using pod/node-to-LB-IP, this also requires fixing the short circuit so that instead of short-circuiting "external" traffic to the "internal" codepath, we instead treat it internally as a third kind of traffic ("traffic that we have to pretend left the cluster and then came back in in a manner that is consistent with externalTrafficPolicy").
> 
> I have read and re-read the text on this, but it's not clicking. Would another way of expressing this simply be: pod/node to LBIP is a special-case for which ETP=Local is bent to mean "Prefer Local but fall back on Cluster" ?

Not exactly...

My argument is that when an external user connects to a LoadBalancer IP, the semantics are "it just works; the user doesn't have to think about traffic policy". And when a pod in a cluster with AWS-style LoadBalancers connects to a LoadBalancer IP, the semantics are "it just works; the user doesn't have to think about traffic policy". The only exception to these LB IP semantics, currently, is that if a pod in a cluster with GCP-style LoadBalancers connects to a LoadBalancer IP on a service with `internalTrafficPolicy: Local`, then it only succeeds if there is a local endpoint. Even though that makes no sense because the connection isn't "internal" (assuming we go with the "destination" model). So we should fix that case so that the semantics are "it just works; the user doesn't have to think about traffic policy". Which more-or-less means "the connection should get Cluster traffic policy".

This is made slightly tricker by the fact that with GCP-style LoadBalancers, a pod-to-LB connection with `externalTrafficPolicy: Local` normally preserves the source IP (although with AWS-style LoadBalancers that is _not_ the case; the destination pod will see the IP of the source pod's node, not the IP of the source pod itself). So ideally you want to preserve that behavior in the case where the service is `eTP: Local, iTP: Local` and there are no local endpoints and so the traffic has to be routed to another node. But _normally_ (in the Cluster traffic policy case), we would SNAT the connection in that case, so that implies that we should SNAT the connection in this short-circuit case as well, but then that would imply we would lose the source IP. But as Tim pointed out in the other PR, it's not obvious that we actually _need_ to do SNAT here, so that may be the answer.

(A counter-argument here is that if `internalTrafficPolicy: Local` really does mean "the definition of the service are such that routing a connection to an endpoint on another node is semantically incorrect" [as opposed to merely "I want connections to stay local for performance reasons"] then it's hard to come up with a plausible use case for exposing such a service via a LoadBalancer, and so it doesn't matter what we do anyway because the whole thing is incoherent. Though also, if you have an `internalTrafficPolicy: Local, externalTrafficPolicy: Local` service that is exposed via NodePort, then it seems like the only reasonable semantics of a pod-to-NodePort connection are that the connection goes to a local pod on the node whose NodePort you connected to, _not_ that it gets short-circuited.)

**Comment by danwinship** [comment]
> Am I guessing right that it is network-policies that becomes a problem?

This bug is mostly just about trying to define what the expected behavior is. It's not inspired by difficulty implementing anything, it's inspired by realizing that iptables kube-proxy's internal model is not entirely self-consistent.

**Comment by danwinship** [comment]
> As for pod-to-same-node-NodePort, I think the questions are
> a) is it possible to use the same special-case path as LBIP?

yes

> b) is it semantically consistent to do this?

IMO no: the argument for special-casing in the LB IP case is that it makes pod-to-LB have the same semantics as external-to-LB. If we special-case pod-to-same-node-NodePort, then that means it _doesn't_ have the same semantics as external-to-NodePort, or even pod-to-other-node-NodePort (where it would depend on whether the other node had endpoints or not).

(And, as above, doing the special case when the service is both eTP:Local _and_ iTP:Local seems extra wrong.)

And are we really sure that people are doing this anyway? Doing pod-to-LoadBalancer makes sense, because it lets you configure your internal and external clients the same way. But to do pod-to-same-node-NodePort, you have to figure out the node IP you're running on, which right away means you're not doing the same thing with internal and external clients, but in that case, why wouldn't you just have the internal clients use the ClusterIP?

(FTR we could special case _just_ node-to-localhost-NodePort if we wanted. It's already a special case in other ways anyway...)

> c) is it at all problematic (wrt code maintenance) to do this?

Post-#106947, special-casing it and not special-casing it are both easy. The difference is just whether the KUBE-NODEPORT rules jump to KUBE-XLB-XXXX (special case) or KUBE-SVL-XXXX (no special case).

Given that, it would be easy to make this an option... we could switch it to having the "right" behavior by default (no special case), but have a `kube-proxy --ignore-traffic-policy-for-pod-to-nodeport` flag, so people who need the old inconsistent behavior could pass that flag...

**Comment by danwinship** [comment]
> "Cluster" will consider all endpoints in the cluster.

... unless Topology is active, in which case it will only consider some of them.

"Cluster" traffic policy really behaves more like `nil` traffic policy. It doesn't have any behavior of its own, it just means "Local traffic policy isn't in effect".

> // Special cases: Connections from a pod or node to a Service's load-balancer
> // IP or externalIPs, or to a Service's nodePort on that same node are handled
> // as if they were to the clusterIP AND internalTrafficPolicy was "Cluster".

If you're talking about "clusterIP" there because you're trying to imply "no SNAT" then remember that that doesn't apply with AWS-like load balancers.

Would it be easier to just say that these cases are neither "internal" nor "external" traffic, and thus not subject to either traffic policy? (I'm not sure...)

**Comment by thockin** [comment]
>> b) is it semantically consistent to do this?
>
> IMO no: the argument for special-casing in the LB IP case is that it makes pod-to-LB have the same semantics as external-to-LB. If we special-case pod-to-same-node-NodePort, then that means it doesn't have the same semantics as external-to-NodePort, or even pod-to-other-node-NodePort (where it would depend on whether the other node had endpoints or not).

For the sake of argument, one COULD say that hitting "mynode:nodeport" is analogous to LBVIP because it's the "backside" of the LB implementation - both assume that the balancer has already selected a node which satisfies ETP.

But more than arguing correctness - it already works, and even if it is weird and wrong, I don't think breaking it is wirth the risk.

(> FTR we could special case just node-to-localhost-NodePort if we wanted. It's already a special case in other ways anyway...)

I was about to agree with this as "good enough" but I just can't justify breaking it, since it works.  Is that workable as a decision?

>> "Cluster" will consider all endpoints in the cluster.
>
> ... unless Topology is active, in which case it will only consider some of them.

I was trying to use "consider" to include topology, but maybe that is too subtle.  Topology will have to modulate the words here.

>> // Special cases: Connections from a pod or node to a Service's load-balancer
>> // IP or externalIPs, or to a Service's nodePort on that same node are handled
>> // as if they were to the clusterIP AND internalTrafficPolicy was "Cluster".
>
> If you're talking about "clusterIP" there because you're trying to imply "no SNAT" then remember that that doesn't apply with AWS-like load balancers.

I wrote it that way to emphasize the "destination" model rather than "internal"/"external".  AWS-like LBs don't have a LBIP, so this is still consistent, I think?

> Would it be easier to just say that these cases are neither "internal" nor "external" traffic, and thus not subject to either traffic policy? (I'm not sure...)

Heh, I wrote that initially.  It seemed scary but now it seems simpler.  SGTM.

```
// internalTrafficPolicy specifies how endpoints for clusterIP traffic should
// be selected when establishing new connections.  "Cluster" will consider all
// endpoints in the cluster, filtered by endpoint topology (if enabled).
// "Local" will only consider endpoints on the same node as the agent
// processing the traffic (e.g. kube-proxy), which is usually the same node
// as the client.  If no endpoints are ready, new connections will be dropped.
//
// The default value is "Cluster".
```

```
// externalTrafficPolicy specifies how endpoints for non-clusterIP traffic
// should be selected when establishing new connections.  "Cluster" will
// consider all endpoints in the cluster, filtered by endpoint topology (if
// enabled), even on other nodes.  This may obscure the client source IP but
// should result in good overall load-spreading.  "Local" will only consider
// endpoints on the same node as the agent processing the traffic (e.g.
// kube-proxy) and will preserve the client source IP, but risks potentially
// imbalanced traffic spreading.  If no endpoints are ready, new connections
// will be dropped.
//
// Special cases: Connections from a pod or node to a Service's load-balancer
// IP or externalIPs, or to a Service's nodePort on that same node are handled
// as if they were sent to the clusterIP, and are not subject to either
// internalTrafficPolicy nor externalTrafficPolicy.  Connections from a pod to
// a Service's nodePort on a different node are subject to
// externalTrafficPolicy as described above.
//
// The default value is "Cluster".
```

**Comment by thockin** [comment]
Is the above properly implementable in terms of IPVS?  @andrewsykim @uablrek

**Comment by uablrek** [comment]
Not for `externalTrafficPolicy`;
> Connections from a pod or node to a Service's load-balancer IP or externalIPs, or to a Service's nodePort on that same node are handled as if they were sent to the clusterIP

Please see https://github.com/kubernetes/kubernetes/pull/97081. But https://github.com/kubernetes/kubernetes/pull/97081#discussion_r786059368 by @danwinship makes me realize that there may be more to be done to be compliant;
> With the graduation of Internal Traffic Policy and Topology-Aware Hints, there are potentially cases where on a given node, internal traffic must be delivered to one set of pods, and external traffic must be delivered to a completely disjoint set of pods.

(IMHO https://github.com/kubernetes/kubernetes/pull/97081 should be merged even if it doesn't solve _all_ problems since it solves the one users actually have reported)

I let Andrew answer about `internalTrafficPolicy`.

**Comment by uablrek** [comment]
Sorry I missed "implementable" for "implemented". I can't see any problems to implement "as if they were sent to the clusterIP", but as mentioned https://github.com/kubernetes/kubernetes/pull/97081 may not be enough.

**Comment by danwinship** [comment]
So this is _mostly_ now resolved and just waiting for doc updates; we have settled on the destination model, with the exception that pod-to-same-node-NodePort / pod-to-ExternalIP / pod-to-LoadBalancer IP are special-cased and handled via Cluster traffic policy regardless of iTP and eTP.

So:
- Traffic from an internal client (pod, node) to an internal destination IP (ClusterIP) gets internal traffic policy.
- Traffic from an external client (pod, node) to an external destination IP (NodePort/ExternalIP/LoadBalancer) gets external traffic policy.
- Traffic from an internal client to an external destination IP gets neither policy; it always gets Cluster semantics.
- Traffic from an external client to an internal destination IP (if allowed by the plugin) gets internal traffic policy.

The last case is inconsistent, and is probably something we didn't explicitly think about before, so we should probably think about it now.

One argument would be that external-to-internal should have the same semantics as internal-to-external; it does not obey either internal traffic policy or external traffic policy, but instead always gets Cluster semantics.

But... what does it even mean to send traffic from an external client to a ClusterIP service with `internalTrafficPolicy: Local`? In the reverse case (internal client to external IP), ignoring traffic policy makes sense, because the high-level semantics of `externalTrafficPolicy: Local` are "preserves source IP" and "only gets redirected once between the client and the endpoint", and we can preserve both of those behaviors by ignoring the traffic policy.

But for `internalTrafficPolicy: Local`, the high-level semantics are something like "there is a separate instance of the Service on each node, and clients only ever connect to the instance of the Service on their own node". But that seems to be incompatible with the idea of allowing connections from external clients; which node should an external connection get routed to? If you say "it doesn't matter", then it seems like the Service is not really semantically `internalTrafficPolicy: Local`, and if you _don't_ say "it doesn't matter" then it seems like the service ought to be exposed externally as multiple IPs rather than just one.

So maybe for `internalTrafficPolicy: Local` services, we should _reject_ connections from outside the cluster, even if the plugin allows them for `internalTrafficPolicy: Cluster` Services.

(Note that we can make that change if we want, because iTP isn't GA yet.)

Can anyone give a plausible use case in which `iTP: Local` is used (correctly; not just for topology optimization) but where connections from outside the cluster should also be allowed? (And if so, then what traffic policy should those connections get?)

**Comment by mateuszdrab** [comment]
@danwinship 

> Can anyone give a plausible use case in which iTP: Local is used (correctly; not just for topology optimization) but where connections from outside the cluster should also be allowed? (And if so, then what traffic policy should those connections get?)

Well, I am actually sort of suffering due to not being able to enforce such policy on pod-to-external IP traffic.
I run haproxy as a daemonset with eTP and iTP as Local. Nodes are located in different locations with a central control plane and as part of traffic optimization, I'd prefer to have workload only access the local node haproxy... outside of the cluster, the VIP is exposed by metallb using BGP, so BGP sort of takes care of routing traffic to nodes in the local site and can always fail back to a remote site if needed.
An equivalent of this behavior is the deprecated Topology Keys, which was a perfect solution to my problem as I'd be able to sort node preference by labels - ideal. Unfortunately, the Topology Aware Hints feature has safeguards which essentially render it unusable in my environment - the feature is enabled but the hints never show.
Currently, a lot of traffic ends up being routed to nodes behind slow links, introducing unnecessary slowdowns...
So, how does that sound for a use case?

**Comment by aojea** [comment]
> Nodes are located in different locations with a central control plane and as part of traffic optimization, I'd prefer to have workload only access the local node haproxy... outside of the cluster, the VIP is exposed by metallb using BGP, so BGP sort of takes care of routing traffic to nodes in the local site and can always fail back to a remote site if needed.

We should understand the failures modes too, and deprecated Topology Keys or other kind of preferences for traffic can blackhole traffic, in addition Kubernetes depends on a central location and there is no network isolation within the cluster,  cause big outages in a cluster and we can't add safeguard, 

I´m not saying we should not do it, just that I don't think Services and kube-proxy are not the right tools for this ... maybe something for Gateway API ?

**Comment by jayunit100** [comment]
I just found this when looking at an issue w/ an Azure LB, and found that running tcpdump,  masquerading traffic from pods, inside the cluster, destined for an ELB appear to be coming from the ELB. 

In general, is the difference between Azure, GKE, and AWS ELB implementations documented anywhere ?
