### ISSUE TITLE
How to set different env depends on node when use daemonset

### ISSUE THREAD

**Issue by samunbest** [kubernetes/kubernetes#108546]
the cluster has different nodes，i need to allocate different memory since each node can provide different resource

**Comment by MadhavJivrajani** [comment]
@samunbest please elaborate and provide more details as to what your question is.
/kind support

**Comment by samunbest** [comment]
> @samunbest please elaborate and provide more details as to what your question is. /kind support

in short,when deploy a daemonet, i want to set different env depends on the node which the pod was scheduled.

**Comment by pacoxu** [comment]
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables

nodeName and hostIp are available in downward API.

```
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_NODE_NAME MY_HOSTIP;
          sleep 10;
        done;
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_HOSTIP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  restartPolicy: Never
```

hostIPs is on the way in https://github.com/kubernetes/kubernetes/pull/101566

**Comment by samunbest** [comment]
> https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables
> 
> nodeName and hostIp are available in downward API.
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   name: dapi-envars-fieldref
> spec:
>   containers:
>     - name: test-container
>       image: k8s.gcr.io/busybox
>       command: [ "sh", "-c"]
>       args:
>       - while true; do
>           echo -en '\n';
>           printenv MY_NODE_NAME MY_HOSTIP;
>           sleep 10;
>         done;
>       env:
>         - name: MY_NODE_NAME
>           valueFrom:
>             fieldRef:
>               fieldPath: spec.nodeName
>         - name: MY_HOSTIP
>           valueFrom:
>             fieldRef:
>               fieldPath: status.hostIP
>   restartPolicy: Never
> ```
> 
> hostIPs is on the way in #101566

Thanks a lot。
My container is run java application ，I need to manage it use a daemonset, since my nodes have different memory size, I need to set different env JAVA_TOOL_OPTIONS depends on the node where the pod was sheduled, Does it works？

**Comment by liangyuanpeng** [comment]
You can use init container to set your JVM param for your different pod.

**Comment by muyangren2** [comment]
I think you not very well understand Pod’s concept ,for your scene  you just need set Pod.spec.containers.resources

**Comment by pacoxu** [comment]
> Pod.spec.containers.resources

I got that. However, using daemonset, the resource limits/requests are all the same for pods in different nodes. (Why you are using daemonset? it is still not clear.) 😄

**Comment by samunbest** [comment]
> You can use init container to set your JVM param for your different pod.

yes，I  manged to do it in this way. Thanks a lot.
