### ISSUE TITLE
Measuring watch delay experienced in control loops

### ISSUE THREAD

**Issue by limhawjia** [kubernetes/kubernetes#108556]
Hi everyone, I am seeking some advice regarding an issue that I have been facing. Any suggestions or feedback on this issue will be greatly appreciated :)

In Kubernetes, controllers rely heavily on the Watch mechanism provided by the apiserver to efficiently detect changes in the system. When you send a Watch request for a particular resource, the apiserver keeps the HTTP connection alive and streams any changes made to the resource in the form of watch events. Controllers use these events to respond to changes in the system and bring the cluster closer to the desired state. 

The Watch mechanism is a defining feature of Kubernetes that has helped to reduce the cost of implementing controllers and control loops greatly, making Kubernetes much more scalable. On the other hand, due to the crucial role it plays in a control loop, any latency in receiving watch events could severely impact the performance of a controller and the overall reconciliation of the system state. 

In my company, we have discovered that many of the problems encountered while running our Kubernetes clusters are caused by high latency when receiving watch events. This prevents our controllers from being able to respond to changes in the system in a timely manner.

Thus, we feel that it would be very useful to be able to measure and monitor this delay, more specifically the time between a resource update and a watcher receiving the corresponding watch event from the apiserver, in the form of a metric.

I have raised this issue on the Slack channel and have received some helpful responses, but I would like to get a larger sensing of:

* How useful would such a metric be to others?
* How feasible would it be to measure such a metric? 
* What are some possible implementations?
* Are there already existing solutions?

If there is a demand for such a metric, and a nice solution exists, we would love to contribute a PR to implement it for the rest of the community.

**Comment by limhawjia** [comment]
Hi @logicalhan, do you have any thoughts on this?

**Comment by limhawjia** [comment]
@logicalhan thanks for the feedback! 

Yes, we understand that such a metric will be difficult to implement, and would require some sort of coordination between distributed components.

We came up with a preliminary idea on how we might measure this metric, and were wondering if you could provide us some feedback on it as well.

First, we add a `lastUpdated` timestamp to each object in the form of an annotation. This annotation serves as the connective tissue that you mentioned. The timestamp is automatically updated by the apiserver whenever a change is made to an object.

As a result, whenever a watcher receives a watch event for a particular resource, it can extract the time of the corresponding object update by looking at the `lastUpdated` annotation. The watcher can then calculate the delay between the object update and the time that it received the watch event. Subsequently this delay can be exported as a metric. This can be implemented in the client-go library.

**Comment by xuchen-xiaoying** [comment]
@logicalhan hi, We also meet the same problem.

In stress test when pods are created in high throughput, latency until scheduler observe pod creation becomes very high. So when scheduler starts to schedule, the pod may already has been created before 20 seconds ago. 

We want to find a metric to reflect the broadcast latency of watch event. Currently distributed tracing in Kubernetes is hard to implement. Related enhancement is not going very well.  Can you give some advice on this requirement ?

**Comment by logicalhan** [comment]
> @logicalhan thanks for the feedback!
> 
> Yes, we understand that such a metric will be difficult to implement, and would require some sort of coordination between distributed components.
> 
> We came up with a preliminary idea on how we might measure this metric, and were wondering if you could provide us some feedback on it as well.
> 
> First, we add a `lastUpdated` timestamp to each object in the form of an annotation. This annotation serves as the connective tissue that you mentioned. The timestamp is automatically updated by the apiserver whenever a change is made to an object.
> 
> As a result, whenever a watcher receives a watch event for a particular resource, it can extract the time of the corresponding object update by looking at the `lastUpdated` annotation. The watcher can then calculate the delay between the object update and the time that it received the watch event. Subsequently this delay can be exported as a metric. This can be implemented in the client-go library.

This is not going to work the way you envision because we have this thing called a watch cache and it will keep items in apiserver memory to serve watches quickly. If we were doing what you suggested, then you could end up with high latency measurements for items that entered the watch cache earlier but a watch was initiated later, when the watch latencies would in actuality be fast.

**Comment by limhawjia** [comment]
@logicalhan 

If I am not mistaken, the problem arises when we receive watch events for changes that have might have happened before the watch was initiated right?

Another example scenario where this could happen is when we initiate a watch for an object with an older resource version. In that case, we would receive watch events for all the changes after the provided resource version. The latencies calculated from these events would be inflated and not representative of what we are trying to measure.

**Comment by limhawjia** [comment]
> This is untrue. I can request to opt to watch from version 1, etcd can be on version 10, and there can be events in the watch buffer between 1 and 10.

Could you clarify which part is untrue?

If you request to watch from version 1 and etcd is on version 10, you would receive all events between 1 and 10 right? I understand that these events may have been buffered and served from the watch cache. 

Regardless, since these events happened before the watch was initiated, the delay calculated by the watcher is no longer representative of what we are trying to measure.

> more specifically the time between a resource update and a watcher receiving the corresponding watch event from the apiserver

This is because some time has already passed since the resource update, and this time would be included in the watcher's calculations.

**Comment by wojtek-t** [comment]
Watchcache isn't strictly related to this problem imho. In the end it just stores the object read (watched) from etcd. So if those objects contain last update time, we will just serve it.

That said I agree with @logicalhan that the fact that you can start the watch from the past makes the problem hard to measure. 


Regarding setting "LastUpdateTime" field - I can't find the reference now, but it was certainly discussed in the passed.
The reason why we decided not to do that was to retain the semantic that no-op updates should not be send to etcd, and if we would start setting LastUpdateTime in kube-apiserver every update would effectively become an actual one.
@smarterclayton @liggitt  - FYI (as I think I was discussing this with one of you)

**Comment by lavalamp** [comment]
You could flip this around and have apiserver measure ping time to its watchers (I think HTTP2 ping goes both ways). And it would be easy for apiserver to measure propagation delay. And you could add these together as an estimate. It wouldn't be perfect but it'd be reasonable and cover every watch message so hopefully a fair sample. And it'd be convenient to have this located in the apiserver metrics.

(That is, take the time at which an event is placed in the distribution queue; then after writing that event to a client, put the delta in a distribution type metric. Also you can add on the last ping time for that client and add that to a separate distribution which is the estimated delay until it reaches the client.)

(It's also trivial for a controller to measure the delay for objects which it is both writing to and watching, but I don't think that's super useful outside of like a scalability test. Because for most controllers, we care about their response time for events written by others. This can be done without recording a timestamp in the object, btw.)

**Comment by limhawjia** [comment]
@wojtek-t @lavalamp thanks for the input!

I did some investigating according to what's been said.

First, I have to agree that adding a "LastUpdatedTimestamp" might not be the best approach. It would definitely cause problems for noop updates, rendering them as actual writes. Any potential workarounds that I can think of, such as adding the timestamp after the equality check, or using a custom equality function would also be extremely ugly and difficult to implement correctly.

Second, as suggested by @lavalamp, propagation delay, node egress bandwidth along with other indicators such as the rate of object writes have indeed helped us to identify and treat problems within our clusters. However, due to the large number of different contributing factors that could influence watch delay, we feel that a single e2e metric would still be very useful. A good example of a use case for us would be when we are analyzing the performance of our custom controllers and operators. This metric could help us to immediately eliminate watch delay as a confounder along with all its potential contributing factors.

Third, etcd begin time as a starting point and watch client receive time as an ending point would be representative of what we are trying to measure.

Fourth, I have looked into managed fields but am still unsure about its reliability as a source of the object's last update's time. Will all non-noop updates (and its corresponding time) be reflected in at least one managed field entry?

Lastly, using propagation delay + queueing delay as an estimate is an interesting idea. Thanks @lavalamp for the suggestion. One concern I have would be that the queueing delay might plateau once the incoming events channel buffer fills up, even as the backlog of events is increasing on the etcd side. It will also not give us the full e2e delay as per my third point. Nonetheless, it seems like a good metric to have and can give us better insights into what might be happening in our watch requests. Would such a metric (or at least the queueing delay) be worth implementing?

**Comment by logicalhan** [comment]
> Third, etcd begin time as a starting point and watch client receive time as an ending point would be representative of what we are trying to measure.

This would be subject to clock skew issues which, when considering the small amounts of time involved, could render average watch latencies almost meaningless.

Why not instrument your custom controller? You can measure e2e watch latency for any controller which watches objects that it itself writes. For instance, let's say you write to an object. Upon success, you get back an RV. Immediately before writing to the object, you note the current time. Then you wait to observe that RV in your watch stream and calculate the difference in time. That is your e2e watch latency.

**Comment by logicalhan** [comment]
> > Third, etcd begin time as a starting point and watch client receive time as an ending point would be representative of what we are trying to measure.
> 
> This would be subject to clock skew issues which, when considering the small amounts of time involved, could render average watch latencies almost meaningless (since etcd and the watch client are presumably on separate machines).
> 
> Why not instrument your custom controller? You can measure e2e watch latency for any controller which watches objects that it itself writes. For instance, let's say you write to an object. Upon success, you get back an RV. Immediately before writing to the object, you note the current time. Then you wait to observe that RV in your watch stream and calculate the difference in time. That is your e2e watch latency.

**Comment by wojtek-t** [comment]
>  Then you wait to observe that RV in your watch stream and calculate the difference in time. That is your e2e watch latency.

With watchcache, it's highly probable that watch latency will vary significantly across resources. So if your controller is reacting on objects of type Foo, but writing those of type Bar, the watch latency of Bar objects can be low even if the watch latency for objects Foo (which is clearly more important in this aprticular case) is high.

**Comment by logicalhan** [comment]
> With watchcache, it's highly probable that watch latency will vary significantly across resources. So if your controller is reacting on objects of type Foo, but writing those of type Bar, the watch latency of Bar objects can be low even if the watch latency for objects Foo (which is clearly more important in this aprticular case) is high.

Yeah, queue depth and all that jazz. But you can still simulate a similar load.

**Comment by logicalhan** [comment]
> We can certainly simulate a lot in tests. But my understanding is that the goal is to measure that in production.

I genuinely thought this was how you guys did scale tests.

**Comment by logicalhan** [comment]
> We can certainly simulate a lot in tests. But my understanding is that the goal is to measure that in production.

Also my suggestion below can definitely be used in production, i.e. the period writing to the object you want to measure the watch latency for.

**Comment by xuchen-xiaoying** [comment]
> Also my suggestion below can definitely be used in production, i.e. the periodic writing to the object you want to measure the watch latency for.

Thanks for your nice suggestion.  I think this is a good bypass approach to measure this metric in practice.

But overall I think Kubernetes is **an event-driven distributed system built on watch mechanism**, that's a big difference from other orchestration systems. **The event broadcast is like message queue in some degree, and the latency is valuable from the view of  event delivery.** 

What I want to discuss is besides work-around approach, whether Kubernetes would support this metric in tree to reflect the efficiency of event delivery.

**Comment by xuchen-xiaoying** [comment]
> > Third, etcd begin time as a starting point and watch client receive time as an ending point would be representative of what we are trying to measure.
> 
> This would be subject to clock skew issues which, when considering the small amounts of time involved, could render average watch latencies almost meaningless (since etcd and the watch client are presumably on separate machines).
> 
> Why not instrument your custom controller? You can measure e2e watch latency for any controller which watches objects that it itself writes. For instance, let's say you write to an object. Upon success, you get back an RV. Immediately before writing to the object, you note the current time. Then you wait to observe that RV in your watch stream and calculate the difference in time. That is your e2e watch latency.

Thanks for your nice suggestion.  I think this is a good bypass approach to measure this metric by sampling in practice. 

But overall I think Kubernetes is **an event-driven distributed system built on watch mechanism**, that's a big difference from other orchestration systems. **The event broadcast is like message queue in some degree, and the latency is valuable from the view of  event delivery.** 

What I want to discuss is besides work-around approach, whether Kubernetes would support this metric in tree to reflect the efficiency of event delivery.

**Comment by aojea** [comment]
> But overall I think Kubernetes is **an event-driven distributed system built on watch mechanism**, that's a big difference from other orchestration systems. **The event broadcast is like message queue in some degree, and the latency is valuable from the view of event delivery.**

kubernetes it is an eventual consistent system and it is level triggered, the problem of edge triggered systems and the dependency on the time to react to events is what the [controller pattern solves](https://kubernetes.io/docs/concepts/architecture/controller/) ...

**Comment by logicalhan** [comment]
> kubernetes it is an eventual consistent system

kubernetes **watch** is eventually consistent. LISTs and GETs are (depending on your query options) **strongly** consistent.

**Comment by lavalamp** [comment]
BTW I was not suggesting measuring queueing delay via a single average for all queues. That would have the problems you all are pointing out. There should be a separate measurement for each queue, which avoids those problems. There are a reasonable number of queues, this should be OK.
