### ISSUE TITLE
Why is there an abnormal listening IP， in kube-proxy

### ISSUE THREAD

**Issue by sunnoy** [kubernetes/kubernetes#108558]
### What happened?

kube-proxy listening abnormal IP
<img width="879" alt="image" src="https://user-images.githubusercontent.com/19342276/157018811-d5242ccc-1e80-4061-96d6-1b81e5a5311d.png">

### What did you expect to happen?

kube-proxy has no listening other ip

### How can we reproduce it (as minimally and precisely as possible)?

i dont kwon

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

 kube-proxy --version
Kubernetes v1.18.3
```

</details>

### Cloud provider

<details>
aliyun
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by khenidak** [comment]
That is port opener.

Kube-proxy holds ports open for services of that has NodePorts. The idea is to stop mistakes where the user runs an app (not managed by kubelet) and use one of the port in  api-server `--service-node-port-range` flag.

The IPs you see are the NodeAddresses reported by the cloud provider.

**Comment by sunnoy** [comment]
> 

i understand this “Kube-proxy holds ports open for services of that has NodePorts”，but the IP is not NodeAddresses reported by the cloud provider，node does not have this field

**Comment by dcbw** [comment]
@sunnoy can you provide the kube-proxy configuration you're using, including its ConfigMap and any command-line arguments you're using?

**Comment by dcbw** [comment]
Also, are any of these IP addresses Service ExternalIPs or LoadBalancer.Status.IPs?

**Comment by sunnoy** [comment]
> @sunnoy can you provide the kube-proxy configuration you're using, including its ConfigMap and any command-line arguments you're using?

/opt/kube/bin/kube-proxy --bind-address=172.20.xx.xx --cluster-cidr=xx.0.0.0/8 --hostname-override=172.20.xx.xx --kubeconfig=/etc/kubernetes/kube-proxy.kubeconfig --logtostderr=true --conntrack-min=3200000 --proxy-mode=ipvs

**Comment by sunnoy** [comment]
> 



> Also, are any of these IP addresses Service ExternalIPs? kube-proxy will open ports for any of those, but (it looks like) only if the node also has that IP assigned to some interface.

but there is no that IP assigned to some interface,rather strange

**Comment by thockin** [comment]
Hi @sunnoy  - is this still going and reproducible?
