### ISSUE TITLE
Master upgrade to v1.22.X failing for kube-controller-manager & kube-scheduler

### ISSUE THREAD

**Issue by Robbie558** [kubernetes/kubernetes#108582]
### What happened?

We are running an upgrade of our Kubernetes master nodes via Ansible, from version 1.21.X to 1.22.X.  Our playbook issues a `kubeadm upgrade apply v{{ version }} -y --v=5` command, which appears to reliably upgrade the `kube-apiserver` image on first run. However it doe not reliably upgrade the `kube-controller-manager` and `kube-scheduler`  images, with the  `kube-controller-manager` going in to `Error` state and restarting, producing the following logs:
```
I0308 09:06:38.101087       1 serving.go:347] Generated self-signed cert in-memory
I0308 09:06:38.783101       1 controllermanager.go:175] Version: v1.21.10
I0308 09:06:38.784166       1 dynamic_cafile_content.go:167] Starting client-ca-bundle::/etc/kubernetes/pki/ca.crt
I0308 09:06:38.784181       1 dynamic_cafile_content.go:167] Starting request-header::/etc/kubernetes/pki/front-proxy-ca.crt
I0308 09:06:38.784278       1 secure_serving.go:202] Serving securely on 127.0.0.1:10257
I0308 09:06:38.784315       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0308 09:06:38.784649       1 leaderelection.go:243] attempting to acquire leader lease kube-system/kube-controller-manager...
E0308 09:06:38.785112       1 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: Get "https://172.21.16.61:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": dial tcp 172.21.16.61:6443: connect: connection refused
...
E0308 09:07:06.267136       1 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: leases.coordination.k8s.io "kube-controller-manager" is forbidden: User "system:kube-controller-manager" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-system"
````

As a workaround, we are forced to re-run the playbook once the `kube-apiserver` pod image has been updated to the target version.  However, even this is not 100% reliable, and we are forced to repeatedly run until both the `kube-controller-manager` and `kube-scheduler`  images.

### What did you expect to happen?

All three pods to be upgraded to the target version on first run of the `kubeadm upgrade apply v{{ version }} -y --v=5` command

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a cluster on version 1.21.X and upgrade each master node to version 1.22.X using the `kubeadm upgrade apply v{{ version }} -y --v=5` command.  Monitor the state of the `kube-apiserver`, `kube-controller-manager` and `kube-scheduler` pods whilst running the command, paying attention to `Image` of the `kube-controller-manager` and `kube-scheduler` pods and their logs. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-02-16T11:18:16Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A - Servers are on-prem virtualised via HyperV
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux fh1-kubet05 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
Ansible
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI - containerd.io/focal,now 1.3.7-1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI - 0.8.7-00 amd64
</details>

**Comment by pacoxu** [comment]
https://v1-22.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

### For the other control plane nodes
Same as the first control plane node but use:
```
sudo kubeadm upgrade node
```
instead of:
```
sudo kubeadm upgrade apply
```

**Comment by Robbie558** [comment]
This behaviour was due to backup manifest files for the `kube-controller-manager` pod in the `/etc/kubernetes/manifests/` directory on the master nodes.  Removing these allowed the `sudo kubeadm upgrade apply` command to succeed on the first iteration.
