### ISSUE TITLE
Avoid pulling images straight from dockerhub in e2e tests 

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#108562]
In PR [1] below, we added support for logging which images were pulled by running the docker/ctr commands and saving them into images-containerd.log and images-docker.log, So now we need to look at those log files to see if we pull any images from places we don't want to ... like dockerhub. See PR [2] as an example of a e2e test that was pulling `nginx` from dockerhub.

How to deal with any images we identify?
- Try to find an alternate image that has manifests for all the arch(es) we support
- Make sure the repository is configurable as well (see pattern in [2])

Open a thread on #sig-testing channel for discussion if needed.

[1] https://github.com/kubernetes/kubernetes/pull/108417
[2] https://github.com/kubernetes/kubernetes/pull/108514

**Comment by pacoxu** [comment]
- [ ] https://github.com/kubernetes/kubernetes/blob/34a6a7ca11d2ce257415c02b07c1b80678188769/test/e2e/testing-manifests/storage-csi/hostpath/hostpath/csi-hostpath-testing.yaml#L67
- [ ] https://github.com/kubernetes/kubernetes/blob/34a6a7ca11d2ce257415c02b07c1b80678188769/test/e2e/storage/flexvolume_online_resize.go#L224
- [ ] several images under /test/e2e/testing-manifests/ like debian:jessie
- - [ ] https://github.com/kubernetes/kubernetes/blob/34a6a7ca11d2ce257415c02b07c1b80678188769/test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml#L29
- - [ ] https://github.com/kubernetes/kubernetes/blob/34a6a7ca11d2ce257415c02b07c1b80678188769/test/e2e/testing-manifests/statefulset/zookeeper/statefulset.yaml#L50
