### ISSUE TITLE
About  kubelet.go:2267 node "" not found problem for help

### ISSUE THREAD

**Issue by lsc615** [kubernetes/kubernetes#108687]
### What happened?

The cluster has been running for a while, and suddenly found that some nodes show the NotReady status, which cannot be restored to normal. I tried to restart the kubelet, but it could not be solved.

### In the master aaaaaaa69 
kubectl get node
NAME          STATUS     ROLES    AGE   VERSION
aaaaaaa69   Ready      master   80d   v1.16.9
aaaaaaa82   Ready      master   80d   v1.16.9
aaaaaaa26   Ready      master   80d   v1.16.9
aaaaaaa43   NotReady   <none>   80d   v1.16.9
aaaaaaa30   Ready      <none>   80d   v1.16.9
aaaaaaa35   NotReady   <none>   80d   v1.16.9

### in the node aaaaaaa43
```
          └─2449 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod-infra-container-image=artifa
kubelet.go:2267] node "aaaaaaa43" not found 
kubelet.go:2267] node "aaaaaaa43" not found
kubelet.go:2267] node "aaaaaaa43" not found
kubelet.go:2267] node "aaaaaaa43" not found
```

### What did you expect to happen?

I hope the node status can be restored to ready

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how it reproduce, this is the first time I encountered this problem

### Kubernetes version

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"********", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

docker -v
Docker version 19.03.8, build afacb8b7f0

calico
kube-controllers:v3.11.2"

### Cloud provider
Null

### OS version

cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"

**Comment by yangjunmyfm192085** [comment]
Node notready generally means that the kubelet does not report the status or the node conditions are not satisfied. Could you  check whether the kubelet can access the apiserver, and check whether there are other error records in the kubelet logs?

**Comment by lsc615** [comment]
> Node notready generally means that the kubelet does not report the status or the node conditions are not satisfied. Could you check whether the kubelet can access the apiserver, and check whether there are other error records in the kubelet logs?

OK, I try

**Comment by lsc615** [comment]
@yangjunmyfm192085 thanks
