### ISSUE TITLE
kubectl run accidentally exposes --kustomize flag

### ISSUE THREAD

**Issue by vdboor** [kubernetes/kubernetes#108630]
### What happened?

The `kubectl run` command provides a `--kustomize` flag but this doesn't do anything.

```
❯ kubectl run --help | grep kustomize
  -k, --kustomize='': Process a kustomization directory. This flag can't be used together with -f or -R.
```

### What did you expect to happen?

most likely the flag shouldn't exist. I have no idea how kustomize could be useful here to start a single pod.

### How can we reproduce it (as minimally and precisely as possible)?

This creates a pod, and shows that `--kustomize NOTEXiSTING` is ignored:

```
kubectl -v=5  run --rm --attach --image=busybox testpod  --restart=Never --kustomize NOTEXiSTING -- /bin/sh -c 'echo STARTED'
```

### Kubernetes version

<details>

```console
❯ kubectl version --client
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
```

</details>

### Cloud provider

<details>Azure, K3OS</details>

### OS version

<details>
OSX 11.6.1 (Big Sur)
</details>

**Comment by brianpursley** [comment]
This comes from the inclusion of DeleteFlags:
https://github.com/kubernetes/kubernetes/blob/0e697e19ac9f73e2efa0e60157730ba8731e3847/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L108

...which brings in FilenameFlags:
https://github.com/kubernetes/kubernetes/blob/8f8138bc35f59ef04b77a3520d8d1065603ccdb7/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete_flags.go#L35

...which has Kustomize, resulting in the `--kustomize` flag:
https://github.com/kubernetes/kubernetes/blob/c5b95f60faa5dc2acfb5397e1a83909c24ec1791/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/filename_flags.go#L32-L38

I suspect there are many flags from DeleteFlags that don't really apply to `kubectl run`.
* `--filename`:  Not sure what this would do
* `--grace-period`:  seems to be ignored and [hard coded to -1](https://github.com/kubernetes/kubernetes/blob/0e697e19ac9f73e2efa0e60157730ba8731e3847/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L244)
* `--force`:  doesn't seem to be used
* `--cascade`:  doesn't seem to be used
* `--recursive`:  also probably doesn't apply

There might be others as well...

**Comment by kkkkun** [comment]
It seems to delete object which created by `run` command. 
https://github.com/kkkkun/kubernetes/blob/0e697e19ac9f73e2efa0e60157730ba8731e3847/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L447

**Comment by ardaguclu** [comment]
> I suspect there are many flags from DeleteFlags that don't really apply to `kubectl run`.
> 
> * `--filename`:  Not sure what this would do
> * `--grace-period`:  seems to be ignored and [hard coded to -1](https://github.com/kubernetes/kubernetes/blob/0e697e19ac9f73e2efa0e60157730ba8731e3847/staging/src/k8s.io/kubectl/pkg/cmd/run/run.go#L244)
> * `--force`:  doesn't seem to be used
> * `--cascade`:  doesn't seem to be used
> * `--recursive`:  also probably doesn't apply
> 
> There might be others as well...

I agree, As far as I can see, `apply`, `replace` and `run` have this deleteFlags exposure.
