### ISSUE TITLE
kube proxy is not available after kubernetes installation

### ISSUE THREAD

**Issue by cpsrujana** [kubernetes/kubernetes#108656]
### What happened?

We have installed Kubernetes using kubespray. we have observed that kube-proxy didnot come up. kubeadm-config.yaml has the required kubeproxy configuration.

In the api server logs, there is an error to connect etcd. 
And etcd container seems to be recreated during that time.

Can somebody help me in understanding the root cause of this issue. We are trying on a fresh machine.

Below is the content from apiserver pod log.
I0310 20:53:39.554375       1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick
I0310 20:53:39.554458       1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick
W0310 20:53:39.554680       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
W0310 20:53:39.554766       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
W0310 20:53:39.554919       1 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {https://172.27.172.191:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 172.27.172.191:2379: connect: connection refused". Reconnecting...
I0310 20:53:39.554925       1 clientconn.go:825] blockingPicker: the picked transport is not ready, loop back to repick

### What did you expect to happen?

Kube proxy pod should come up and running.

### How can we reproduce it (as minimally and precisely as possible)?

Running cluster.yml. It got stuck here.

TASK [win_nodes/kubernetes_patch : Ensure that user manifests directory exists] *************************************************************
Friday 11 March 2022  09:54:18 +0000 (0:00:00.102)       0:00:03.590 **********
changed: [localhost]

TASK [win_nodes/kubernetes_patch : Copy kube-proxy daemonset nodeselector patch] ************************************************************
Friday 11 March 2022  09:54:19 +0000 (0:00:00.603)       0:00:04.194 **********
changed: [localhost]

TASK [win_nodes/kubernetes_patch : Check current nodeselector for kube-proxy daemonset] *****************************************************
Friday 11 March 2022  09:54:20 +0000 (0:00:01.157)       0:00:05.351 **********
FAILED - RETRYING: Check current nodeselector for kube-proxy daemonset (60 retries left).
FAILED - RETRYING: Check current nodeselector for kube-proxy daemonset (59 retries left).

### Kubernetes version

<details>

```console
$ kubectl version
1.16.3
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Debian GNU/Linux 10 (buster)
$ uname -a
4.19.81-OpenNetworkLinux

```

</details>

### Install tools

<details>
Kubespray
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/transfer kubernetes-sigs/kubespray

This should be open on the corresponding project

Thanks
