### ISSUE TITLE
Soak Tests for Azure K8s clusters with Windows Nodes

### ISSUE THREAD

**Issue by oprinmarius** [kubernetes/kubernetes#108621]
### What would you like to be added?

**Add a new job in Prow for Windows Soak tests.**

* The job will be scheduled weekly, with the option to be triggered manually.
* The test should be configurable to run arbitrary builds of Kubernetes, including HEAD
* The test will use **Cluster API Provider for Azure** for cluster provisioning
* The Soak tests will repeatedly run **clusterloader2** on Windows nodes for a configurable timespan defaulting to 8 hours
* Tests results should be visible in **TestGrid**
* The test will output **Prometheus** metrics using Windows node exporter
* The following metrics will be measured:
  - memory usage
  - node storage
  - open file handles
  - orphaned processes
  - network port allocations

 

### Why is this needed?

Uncovers performance and reliability issues stemming from the cluster being under pressure for an extended period of time.

**Comment by jsturtevant** [comment]
One additional aspect we could add is to update https://github.com/kubernetes/perf-tests/tree/master/perfdash to view the metrics that are outputted into the prow artifacts cluster.  We could then run that instance in the [community cluster](https://github.com/kubernetes/k8s.io/blob/main/running-in-community-clusters.md#how-to-run-your-thing-in-our-clusters) similar to how the [perf-dash does this today](https://github.com/kubernetes/perf-tests/tree/master/perfdash#how-to-deploy-new-version-of-perf-dashk8sio). This would give use a nice visual of the metrics we are collecting.

**Comment by jsturtevant** [comment]
this is actively being worked on 
/remove-lifecycle stale
