### ISSUE TITLE
`pod.status.containerStatuses.imageID` not 100% accurate

### ISSUE THREAD

**Issue by jnummelin** [kubernetes/kubernetes#108689]
### What happened?

When running multi architecture apps the `pod.status.containerStatuses.imageID` might be bit misleading.

For example when running a pod with `docker.io/nginx:1-alpine` image, the pod status show the following:
```

bash-5.1# k0s kc get pod nginx -o yaml | grep imageID
    imageID: docker.io/library/nginx@sha256:da9c94bec1da829ebd52431a84502ec471c8e548ffb2cedbf36260fd9bd1d4d3
```

This corresponds to the images digest:
```
$ manifest-tool inspect docker.io/nginx:1-alpine
Name:   docker.io/nginx:1-alpine (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:da9c94bec1da829ebd52431a84502ec471c8e548ffb2cedbf36260fd9bd1d4d3
```

How ever as this specific image is a multi-arch image, it would be helpfull* to know which actual manifest/image is used as different nodes in the cluster might be actually running on different archs.

*) E.g. security scanners would need to scan different set of layers depending on which architecture the pod(s) run on. Now they need to check image manifests, node archs and so on.

### What did you expect to happen?

To be exact, I'd assume the `pod.status.containerStatuses.imageID` gives the digest of the actual arch specific image rather than the multiarch images manifests digest.

### How can we reproduce it (as minimally and precisely as possible)?

Run a multi arch app, e.g. nginx, and observe `pod.status.containerStatuses.imageID` showing the images manifest rather than the actual architecture specific digest.

### Kubernetes version

<details>

```console
$ kubectl version
bash-5.1# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4+k0s", GitCommit:"07850cb27512b2a69916084b89111d815edf94be", GitTreeState:"clean", BuildDate:"2022-02-23T12:13:51Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

None

### OS version

<details>

```console
bash-5.1# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.2
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
bash-5.1# uname -a
Linux controller0 5.4.0-1065-aws #68~18.04.1-Ubuntu SMP Thu Feb 3 16:54:16 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by endocrimes** [comment]
/remove-kind bug
/kind feature

It could be helpful to indicate arch in some way but this is populated by the CRI implementation rather than by Kubernetes itself - so isn't particularly straightforward to think about changing.

cc @mikebrow in case he has any suggestions

**Comment by jnummelin** [comment]
@endocrimes any chance you could point me to the correct direction in CRI spec that deals with this? Or is this "behind" CRI thing where the runtimes are responsible providing this?

**Comment by endocrimes** [comment]
@jnummelin https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto#L1058-L1060

**Comment by jnummelin** [comment]
thanks for the reference to the CRI definition.

hmm
```
// Reference to the image in use...
```
That might make one to argue that it really _should_ point to the platform/arch digest as that is the "image in use", emphasis on the "in use" part. 😄 

But I get the part where this is coming from CRI runtimes and out-of-control from k8s/kubelet point of view. And this is probably also so "standardized" in runtimes that it might be hard to change those too. I'll try to look how this gets populated in containerd for example.

Just out of curiosity, would it be even worth thinking if there could be some additional field in the spec to cater for this use case?

**Comment by endocrimes** [comment]
I don't think it'd be unreasonable to expose image arch in the spec at all. I know we don't support macOS, but the concept of a platform being able to run multiple arch images isn't _that_ out there long term.
