### ISSUE TITLE
Inject schedule name into newly created job

### ISSUE THREAD

**Issue by carantunes** [kubernetes/kubernetes#108609]
### What happened?

In cronjob_controllerv2.go, jobs name pass from epoch in seconds to epoch in minutes

`name := fmt.Sprintf("%s-%d", cj.Name, getTimeHash(scheduledTime))`

to 

`
func getJobName(cj *batchv1.CronJob, scheduledTime time.Time) string {
	return fmt.Sprintf("%s-%d", cj.Name, getTimeHashInMinutes(scheduledTime))
}
`

### What did you expect to happen?

Expected this to be documented somewhere.

This is a breaking change, affecting a known strategy to obtain the job expected runtime. Eg. https://stackoverflow.com/questions/55694707/access-scheduled-run-time-inside-kubertes-cronjob#comment120366156_55694854

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

-

### Kubernetes version

<details>

Release 1.23 removed old controller.

</details>

### Cloud provider

<details>

</details>

**Comment by liggitt** [comment]
cc @soltysh

**Comment by sftim** [comment]
I'm not sure if the generated name for Jobs was / is part of the API definition for CronJob. My guess is that an implementation of CronJob is compliant no matter what naming scheme it uses, and that people wishing to match Jobs associated with a CronJob should use either labels and selectors, or owner references.

**Comment by soltysh** [comment]
Exactly what Tim said above, we never said anywhere or explained how the name is created, this is implementation details that users should not rely on. If there's a desire to have such a value exposed, then that's doable and I can totally see something like that being expressed possibly through an annotation which can be then easily injected into running pod. Having said that this functionality **does not exist yet** and it's a feature request, not a bug. Changing bug categorization as such.

/remove-kind bug
/kind feature 
/assign

**Comment by carantunes** [comment]
Ok, that's understandable.
And thank you. Indeed, having that value available and officially supported with downward api or something would be the ideal setup! 

You can see it's a recurrent question, without a clear solution: eg https://stackoverflow.com/questions/56024617/is-there-a-way-to-know-at-which-time-pod-should-be-executed and https://stackoverflow.com/questions/55694707/access-scheduled-run-time-inside-kubertes-cronjob

**Comment by soltysh** [comment]
I totally agree that this is something we can easily expose. @carantunes if you're up to make it happen, I'll gladly accept PR :smiley:  feel free to ping me on slack if you need any help with it or push it through reviews.

**Comment by carantunes** [comment]
Ok, I will give it a go! Thank you. 
You can assign it to me, (if that's how it works :) ) I will ping on slack when I'll get on with it.
Cheers!

**Comment by soltysh** [comment]
/remove-lifecycle stale
/assign @carantunes

> Ok, I will give it a go! Thank you. You can assign it to me, (if that's how it works :) ) I will ping on slack when I'll get on with it. Cheers!

Feel free to ping me on slack even if you have any questions.

**Comment by soltysh** [comment]
@carantunes you still interested in doing this change?

**Comment by carantunes** [comment]
Yes I am! I'll be looking into this soon

**Comment by helayoty** [comment]
@carantunes are you still willing to work on this problem?
