### ISSUE TITLE
Refactor "test/e2e/windows/gmsa_full.go"

### ISSUE THREAD

**Issue by iXinqi** [kubernetes/kubernetes#108649]
### What would you like to be added?

1. "work e2e" and "read/write file" test cases have the same set up and clean up functions. We should hoist the same setup logic to a beforeEach and do the clean up in a afterEach. Create this issue to track it as mentioned in this comment: https://github.com/kubernetes/kubernetes/pull/108432#discussion_r819055340

2. Follow up on using dns name in the remote folder path instead of ip. (mentioned in this comment: https://github.com/kubernetes/kubernetes/pull/108432#discussion_r824879707)
### Why is this needed?

To remove the redundant code and make it clear and efficient.

**Comment by jsturtevant** [comment]
We have the open PR under review in https://github.com/kubernetes/kubernetes/pull/110150

**Comment by helayoty** [comment]
@iXinqi @jsturtevant 👋 the release 1.25 bug triage Lead. I'm reaching out to see the status of this issue and if we are still targeting the current release.

**Comment by marosset** [comment]
We can move this to 1.26
/milestone v1.26

**Comment by cailynse** [comment]
Hello @marosset and @iXinqi! Bug Triage shadow here - I wanted to check in and see if this issue is still on track for 1.26?
