### ISSUE TITLE
Write e2e test to check system resource utilization and performance

### ISSUE THREAD

**Issue by quinton-hoole** [kubernetes/kubernetes#10860]
#10659 for further details.

Copy of comment there:

"Totally agree - soak tests are good place to do this sort of thing, and relatively straightforward. In fact, irrespective of soak tests, an e2e test that checks resource usage and/or response latency of system components (see discussion at end of #10471), and fails if these are out of specification would be both simple to write and generally very useful. It could/would:

1. run concurrently with other e2e tests during pre-merge checks to catch egregious performance regressions before merging,
1. run repeatedly against soak test clusters and detect slow resource leaks like those detailed in #10659 
1. run in our normal serial and parallel e2e tests to detect inconsistent performance/resource usage characteristics of the system, which are typically also an indicator of non-good stuff.

**Comment by gmarek** [comment]
I can work on it, if no one wants. My current idea is to write an ordinary e2e "test" that scrapes cadvisor for every node for some time, and compares average resource usage to the limit we choose. 

I'm not quite sure if it's possible to define the allowed growth instead of hard limits, as I don't know if we can transfer data between runs.

**Comment by quinton-hoole** [comment]
Excellent!  Yes that sounds great.  We will clearly need to beware of high rates of false negative failures, but I think that the best starting point is to build the test first, and worry about what the right pass/fail thresholds are as the second step.

**Comment by gmarek** [comment]
I had relatively little time today, so I didn't manage to finish this today. It requires a little more work, so I'll send the PR tomorrow.

**Comment by bprashanth** [comment]
If we can just have a library log cpu/memory at the end of each soak iteration we can observe it over a week as a starting point.

**Comment by gmarek** [comment]
That's roughly the idea, but to make it simpler I want to just write a test which will do exactly the same.

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (30/30 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:1967)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.85)
	(envelope-from <bounces+848413-7097-robin=eikaas.no@sgmail.github.com>)
	id 1ZEhZN-001znx-Ta
	for robin@eikaas.no; Mon, 13 Jul 2015 19:31:21 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Wo81NK1ZWVf8ms7Y1x3Ae/BbdMo=; b=XMQIQt5xcsdQGTGz
	PN/tKUQQaIEiMA0XJciRpNjHA7CyerLAHLzppgmb6B+IPD45X5/dVbTGNmPJd6vy
	GvEIE/j2u6CzL22/DCvHOe0F7681LgCUVUcFlPXYPmV1m4MYXuGiElPbKMSOVQP3
	J813oKEAl7aq9bO2U7VABzR0Tb8=
Received: by filter0562p1mdw1.sendgrid.net with SMTP id filter0562p1mdw1.14006.55A3F5D919
        2015-07-13 17:31:05.815817347 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-016 (SG) with ESMTP id 14e88785a21.6294.78f31
	for <robin@eikaas.no>; Mon, 13 Jul 2015 17:31:05 +0000 (UTC)
Date: Mon, 13 Jul 2015 10:31:05 -0700

**Comment by bprashanth** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11196

**Comment by yujuhong** [comment]
> I can work on it, if no one wants. My current idea is to write an ordinary e2e "test" that scrapes cadvisor for every node for some time, and compares average resource usage to the limit we choose.

I've discussed with @dchen1107 last week to implement mechanisms like this, but I forgot to subscribe/update this issue. Sorry about that.
I have two PRs up for this already: #11074 introduces utility functions to scrape cadvisor (through kubelet /stats/container). #11196 adds resourceMonitor, which polls kubelet periodically and stores the usage information in a fixed-size buffer. Tests can calls resourceMonitor methods to get/log the stats.

**Comment by gmarek** [comment]
Seems like overkill to me - I can easily scrape cadvisor without a fancy machinery around it and don't block on your PRs:)

**Comment by bprashanth** [comment]
would still recommend code reuse if possible, especially since we've survived for this long without the test.

**Comment by yujuhong** [comment]
> Seems like overkill to me - I can easily scrape cadvisor without a fancy machinery around it and don't block on your PRs:)

All my PRs do is scraping cadvisor (through kubelet) and aggregate the data, which is exactly what you suggested here :-)  I think you probably misunderstood my PRs. See my response in https://github.com/GoogleCloudPlatform/kubernetes/pull/11196#issuecomment-121155316

Whether the implementation is an overkill is another issue. If there is anything you'd suggest otherwise, feel free to leave any comment on those PRs :)

**Comment by gmarek** [comment]
#11374 closed this.
