### ISSUE TITLE
apiVersion: certificates.k8s.io/v1 approving cert but never issuing it.

### ISSUE THREAD

**Issue by nickekstest** [kubernetes/kubernetes#108633]
### What happened?
apiVersion: certificates.k8s.io/v1 approving cert but never issuing it.

Result:
my-svc.example.com 39m kubernetes.io/kube-apiserver-client kubernetes-admin Approved

I've tried making the csr a few different ways.

### What did you expect to happen?

Expected Result:
my-svc.example.com 39m kubernetes.io/kube-apiserver-client kubernetes-admin Approved,Issued

### How can we reproduce it (as minimally and precisely as possible)?

```
cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "my-svc.example.com"
  ],
  "CN": "system:node:my-svc.example.com",
  "key": {
    "algo": "ecdsa",
    "size": 256
  },
  "names": [
      {
          "O": "system:nodes"
      }
  ]
}
EOF

cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: my-svc.example.com
spec:
  request: $(cat "server.csr" | base64 | tr -d '\n')
  signerName: kubernetes.io/kube-apiserver-client
  #expirationSeconds: 86400  # one day
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

kubectl certificate approve my-svc.example.com
kubectl get csr
```

### Kubernetes version

<details>

```console
% kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS 1.21
</details>

### OS version

<details>

```% uname -a
Darwin C02FTDFSMD6M 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nickekstest** [comment]
I think you're right about the signers, but even when I try that, it still stops at approved.

Which EKS version are you using?

Could you let me know the values you used for your CSR please?

This is the result when I tried with the snipped you posted:
```
NAME                  AGE     SIGNERNAME                            REQUESTOR          CONDITION
my-svc.example.com    8m45s   kubernetes.io/kubelet-serving         kubernetes-admin   Approved
```

**Comment by Shubham82** [comment]
> Which EKS version are you using?

I am not using any EKS version, I did this on my locally created multinode k8s cluster.

> Could you let me know the values you used for your CSR please?

I used the same CSR that you mentioned :
```
cat <<EOF | ../cfssl genkey - | ../cfssljson -bare server
 {
   "hosts": [
     "my-svc.example.com"
   ],
  "CN": "system:node:my-svc.example.com",
   "key": {
     "algo": "ecdsa",
     "size": 256
   },
   "names": [
       {
           "O": "system:nodes"
       }
   ]
 }
EOF
```
I think it is something related to EKS

**Comment by nickekstest** [comment]
Thanks for confirming the CSR.

Sorry, I meant which version of k8s are you using?

**Comment by Shubham82** [comment]
I am using k8s version: **v1.23.3**

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by 996refuse** [comment]
hi @nickekstest
I encounter the same issue, Could you help share any updates?

did you try
1. use `kubernetes.io/legacy-unknown` as signerName
2. search the error message from kube-controller-manager log

**Comment by nicksdockeracct** [comment]
I've confirmed this does not work with EKS 1.22 either (kubectl 1.22.5).

@996refuse as a work around the longer method where you manually sign the cert works, as detailed here:
[https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)

**Comment by enj** [comment]
EKS does not run the Kubernetes controller manager signer controllers (or any equivalent thereof) that respond to approved CSRs with a signed certificate.  This is an implementation detail of their infrastructure, and it is perfectly valid for them to not support the CSR signers as they are not part of Kubernetes conformance.  Please reach out to EKS support with a feature request if you want this flow to work in EKS.

/close
