### ISSUE TITLE
drop beta node labels

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#108605]
### What would you like to be added?

We stop applying the beta OS labels in Kubernetes 1.19, should we remove these beta labels in v1.24. I also get support from https://github.com/kubernetes/kubernetes/blob/9946b5364e8199ac832161e17155bd005c391fc5/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L144-L157

### Why is this needed?

Remove beta node labels.

**Comment by pacoxu** [comment]
dup with #89477

**Comment by liggitt** [comment]
thanks for opening the issue

/close 
in favor of https://github.com/kubernetes/kubernetes/issues/89477

that issue links to a list of places node labels are referenced from. before removal, we have to ensure all places we reference node labels have warned about removal, *and* that there is a non-disruptive way to transition existing objects referencing the beta labels.
