### ISSUE TITLE
https://github.com/kubernetes/kubernetes/issues/60388#issuecomment-368399542

### ISSUE THREAD

**Issue by lxxin** [kubernetes/kubernetes#108635]
https://github.com/kubernetes/kubernetes/issues/60388#issuecomment-368399542
>We will not evict pods. With the recent change in 1.10, capacity will include unhealthy devices but allocatable will drop to zero.

@jiayingz perhaps I misunderstood your comment. Thanks for your reply and clarification.

_Originally posted by @pineking in https://github.com/kubernetes/kubernetes/issues/60388#issuecomment-368766688_

**Comment by MadhavJivrajani** [comment]
@lxxin is this supposed to be an issue?

**Comment by lxxin** [comment]
no, its a mistake

**Comment by MadhavJivrajani** [comment]
ack, thanks!
/close
