### ISSUE TITLE
kubectl create role command cannot recognize resource rs.extensions

### ISSUE THREAD

**Issue by FrommyMind** [kubernetes/kubernetes#108604]
### What happened?

create clusterrole command with resource value `rs.extensions` not work.
I got this example command from the help note.

```
#kubectl create clusterrole -h
Create a cluster role.

Examples:
  # Create a cluster role named "pod-reader" that allows user to perform "get", "watch" and "list" on pods
  kubectl create clusterrole pod-reader --verb=get,list,watch --resource=pods

  # Create a cluster role named "pod-reader" with ResourceName specified
  kubectl create clusterrole pod-reader --verb=get --resource=pods --resource-name=readablepod
--resource-name=anotherpod

  # Create a cluster role named "foo" with API Group specified
  kubectl create clusterrole foo --verb=get,list,watch --resource=rs.extensions
.....
```

But got error with the example command.

```
#  kubectl create clusterrole foo --verb=get,list,watch --resource=rs.extensions
the server doesn't have a resource type "rs" in group "extensions"
#
```

### What did you expect to happen?

I think it should work like `rs/extensions`

```
# kubectl create clusterrole foo --verb=get,list,watch --resource=rs/extensions
clusterrole.rbac.authorization.k8s.io/foo created
#
```

### How can we reproduce it (as minimally and precisely as possible)?

yes.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
no cloud env, just vm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux k8s-master1 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
# docker version
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu5~20.04.2
 Built:             Mon Nov  1 00:34:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.7-0ubuntu5~20.04.2
  Built:            Fri Oct 22 00:45:53 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.5-0ubuntu3~20.04.2
  GitCommit:
 runc:
  Version:          1.0.1-0ubuntu2~20.04.1
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
extensions/v1beta1 is no longer served since 1.16

the example should be updated to refer to `rs.apps`

**Comment by Shubham82** [comment]
Thanks, @liggit for this information, I will update this.

One more thing I have to ask here should I also do update the files/folders under [translations ](https://github.com/kubernetes/kubernetes/tree/2cd5c54f39b3adb4e8532a123b8cc697cf657bc8/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl) folder like template.pot.

**Comment by Shubham82** [comment]
Hi @liggitt

Any Inputs on this!

> One more thing I have to ask here should I also do update the files/folders under [translations ](https://github.com/kubernetes/kubernetes/tree/2cd5c54f39b3adb4e8532a123b8cc697cf657bc8/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl) folder like template.pot.

**Comment by liggitt** [comment]
I don't know how the translation files are maintained, sorry

**Comment by Shubham82** [comment]
Don't be sorry, it's OK!

Thanks!

**Comment by pacoxu** [comment]
/assign
I will update the docs.

**Comment by Shubham82** [comment]
Hi @pacoxu 
I am already working on it. 
I have one doubt on translation files, which I already asked in the sig-cli channel.
Could you please tell me if you know that it will be a great help!

**Comment by pacoxu** [comment]
/usassign
ok

**Comment by pacoxu** [comment]
You can check the kubectl example.
https://github.com/kubernetes/kubernetes/blob/9d512581b85ae8f2f315e042ed4bfc76d921bfb4/staging/src/k8s.io/kubectl/pkg/cmd/create/create_clusterrole.go#L49
![image](https://user-images.githubusercontent.com/2010320/157801710-ebf94e04-59b1-499b-9b6d-71de4bd06039.png)

And the role/clusterrole and something else alse needs an update.


Code in website: I think it is generated 
https://github.com/kubernetes/website/blob/2e7063ed9c6f80cda0dd389237be4d17c8ec04b5/static/docs/reference/generated/kubectl/kubectl-commands.html#L173

**Comment by Shubham82** [comment]
yes, I already saw where to update the things, but I have one doubt in template.pot file which is under translation [folder](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl), I just wonder I have to update this file also,

**Comment by Shubham82** [comment]
Hi @eddiezane
PTAL!

**Comment by Shubham82** [comment]
> yes, I already saw where to update the things, but I have one doubt in template.pot file which is under translation [folder](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl), I just wonder I have to update this file or not. see this [README](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/README.md)

Hi @brianpursley  
could you please take a look!

**Comment by Shubham82** [comment]
> > yes, I already saw where to update the things, but I have one doubt in template.pot file which is under translation [folder](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/kubectl), I just wonder I have to update this file or not. see this [README](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/util/i18n/translations/README.md)
> 
> Hi @brianpursley could you please take a look!

Hi @brianpursley 
Friendly reminder!
