### ISSUE TITLE
kubelet's requests are reported as 'Go-http-client/2.0'

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#108726]
### What happened?

It looks like kubelet started using generic user agent like "Go-http-client/2.0" and makes it harder to attribute the request to kubelet.

In the past we have used "kubelet" user-agent which was providing some value.

Sample logs: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-master/kube-apiserver.log
```
I0315 14:13:15.198270      11 httplog.go:131] "HTTP" verb="DELETE" URI="/api/v1/namespaces/test-1w3fvz-1/pods/latency-deployment-67-5cb8c6bf86-psrtn" latency="5.033096ms" userAgent="Go-http-client/2.0" audit-ID="447f2e58-4649-4fbd-9631-50a862f18d6f" srcIP="10.40.3.224:35364" apf_pl="system" apf_fs="system-nodes" resp=200
```

### What did you expect to happen?

Kubelet's requests are using customised user-agent

### How can we reproduce it (as minimally and precisely as possible)?

* Run kubelet
* Check kube-apiserver's logs: https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-master/kube-apiserver.log

### Kubernetes version

master

### Cloud provider

tested on gce

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
The default user agent name is generated like below. 
https://github.com/kubernetes/kubernetes/blob/9c97ae286c4dbce137a35fdb3dd79dd2866e71f8/staging/src/k8s.io/client-go/rest/config.go#L498-L506

> I0315 01:42:12.105506       1 trace.go:205] Trace[2074009786]: "Create" url:/api/v1/namespaces/kube-system/events,user-agent:kubelet/v1.23.4 (linux/amd64) kubernetes/e6c093d,audit-id:93c70da7-253e-4dc3-bf61-4dd827e46b33,client:10.6.177.40,accept:application/vnd.kubernetes.protobuf,application/json,protocol:HTTP/2.0 (15-Mar-2022 01:42:11.546) (total time: 558ms):

I am using v1.23.4 and the user agent can show kubelet as the user agent.

**Comment by mborsz** [comment]
Interesting... in https://storage.googleapis.com/sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/1503729543293177856/e2e-big-master/kube-apiserver.log I see both kubelet user agent and "Go-http-client/2.0":

```
I0315 14:31:49.027472      11 httplog.go:131] "HTTP" verb="PUT" URI="/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/e2e-big-minion-group-r3f3?timeout=10s" latency="2.875993ms" userAgent="Go-http-client/2.0" audit-ID="b4b86f7f-a21a-47d9-9562-4ca39a480dc6" srcIP="10.40.0.59:56314" apf_pl="node-high" apf_fs="system-node-high" resp=200
```

```
I0315 14:28:37.213663      11 httplog.go:131] "HTTP" verb="POST" URI="/api/v1/namespaces/test-ox4nfb-1/events" latency="2.41618ms" userAgent="kubelet/v1.24.0 (linux/amd64) kubernetes/1a5abe5" audit-ID="7cc3e285-1b15-47d4-9f16-b2942d6ec346" srcIP="10.40.0.32:57598" apf_pl="system" apf_fs="system-nodes" resp=201
```

Moreover, it looks like "kubelet" user agent is used only for events-related calls and other (like leases) are using "Go-http-client/2.0".

**Comment by aojea** [comment]
interesting , the user agent is added to the request by wrapping the roundtripper, that is added when the client is generated

https://github.com/kubernetes/kubernetes/blob/adb75e1fd17b11e6a0256a4984ef9b18957d94ce/staging/src/k8s.io/client-go/1.4/transport/round_trippers.go#L32-L49

the clientset creation is here https://github.com/kubernetes/kubernetes/blob/dd2596e40d1fbb92fa4825145c4cf8cda1e559fa/cmd/kubelet/app/server.go#L789

Speculating, I'm wondering if the updateTransport https://github.com/kubernetes/kubernetes/blob/11d96c174ed0349d67b4808c618b95bc563535b9/pkg/kubelet/certificate/transport.go#L53 is mutating the transport and not adding the corresponding wrapper in `HTTPWrappersForConfig` ?

**Comment by aojea** [comment]
/assign

I think that this was my fault, let me check it in more detail

**Comment by aojea** [comment]
> /assign
> 
> I think that this was my fault, let me check it in more detail

I think that this was the problem https://github.com/kubernetes/kubernetes/pull/108772
