### ISSUE TITLE
Remove `alwaysCheckAllPredicates` in scheduler configurator

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#108770]
### What would you like to be added?

Since scheduler Policy API was total removed, we don't support `alwaysCheckAllPredicates` any more. https://github.com/kubernetes/kubernetes/blob/a504daa0484d35d07f144e3f65f5a481570e96ec/pkg/scheduler/factory.go#L66-L67

### Why is this needed?

Remove unsupported configuration.

**Comment by neolit123** [comment]
/sig scheduling
(trying to tell the bots to remove `needs-sig`)

**Comment by Huang-Wei** [comment]
> Since scheduler Policy API was total removed, we don't support `alwaysCheckAllPredicates` any more.

It's true scheduler doesn't quite use this field anymore, but I'm wondering if some other project like ClusterAutoscaler or simulator still consumes this via [WithRunAllFilters](https://github.com/kubernetes/kubernetes/blob/9e50a332d8fcbec104e7ff90a01aa215c8ea72e6/pkg/scheduler/framework/runtime/framework.go#L204-L206).

**Comment by kerthcet** [comment]
There's no place we can config this field `alwaysCheckAllPredicates` now by configure file(before we can apply the change by policy api, but now it's removed). So it seems like unless we support this feature with CC, or this field is useless. 

To other projects, it's the same. When they are using legacy policy api, they can configure this field, but once they synced with the latest kubernetes, with the policy api removed, they can not configure this anymore.

In this situation, we should add support in CC. I don't quite understand the relationship between k/k with k/autoscaling or others, I think they sync with k/k periodic.

**Comment by Huang-Wei** [comment]
> There's no place we can config this field alwaysCheckAllPredicates

As I mentioned above, it's still accessible via a framework runtime `Option` **programmatically**, and thus may be still useful. For example, upon a scheduling failure, a ClusterAutoscaler's implementation may choose to dryrun through all filter plugins to ensure a new provisioned node can fit the pod, instead of resolving the failure while failing at another latter filter plugin.

**Comment by kerthcet** [comment]
Let me sort out current logic:

1. initialize Configurator here, sine we didn't set the `alwaysCheckAllPredicates `, it's false by default. https://github.com/kubernetes/kubernetes/blob/ad751e8520e875f011744a034fff3becdce46403/pkg/scheduler/scheduler.go#L318-L342
2. invoke `configurator.create()`, `c.alwaysCheckAllPredicates` is still false.
3. build profiles, then `c.alwaysCheckAllPredicts` is always false. https://github.com/kubernetes/kubernetes/blob/ad751e8520e875f011744a034fff3becdce46403/pkg/scheduler/factory.go#L145-L157

I also found the setter function was removed together with `Policy API` https://github.com/kubernetes/kubernetes/pull/105424/files#diff-53cc60f8818dce859b9222be5c8dc93d511fbc942cc17a0e85c10f260d74ca72L267-L271, so it seems we have wrongly removed this feature.

Please correct me if I mis-understood the code. Thanks.

**Comment by kerthcet** [comment]
Oh, I haven't thought of configuration via programmatically, that saved my concern. But a little strange.

**Comment by Huang-Wei** [comment]
> I haven't thought of configuration via programmatically

That's exactly what I meant. Given it's a public option in framework, and there is no alternative if we disabled it, it'd be good to check with potential consumers. For now I can think of CA (@MaciekPytel) and k-sigs/scheduler-simulator (@sanposhiho). If they can confirm it's not needed in their usecases, I'm fine with removing `alwaysCheckAllPredicates`.

**Comment by kerthcet** [comment]
To k/autoscaler, at least these codes are still there together with the legacy policy api. https://grep.app/search?q=alwaysCheckAllPredicates, looking forward to the response.

**Comment by sanposhiho** [comment]
`alwaysCheckAllPredicates` is not used in sigs/kube-scheduler-simulator. 🙆‍♂️

**Comment by ahg-g** [comment]
this isn't used by cluster autoscaler, we can remove it.
