### ISSUE TITLE
PVC not detecting PV without claimRef

### ISSUE THREAD

**Issue by theAkito** [kubernetes/kubernetes#108720]
### What happened?

I have a simple single-node Kubernetes cluster. Nothing out of the ordinary. Straight, by the book standard installation.

I installed the following Helm Chart.

https://github.com/bitnami/charts/tree/master/bitnami/postgresql

I did that already a couple of times.

I created a PV for the PostgreSQL StatefulSet containing the pod accessing the PV.

As usual, I copied over the PV YAML from an earlier installation to a different namespace and adjusted the name and directory for the `hostPath`.

All goes, exactly as planned, as I have done that already enough times.

I copied over the `values.yaml` from a previous PostgreSQL Helm Chart installation, which is provably working.

I, again, adjusted the names, to fit the new PV in the new namespace. This Chart is also installed in that namespace, etc.

Business as usual.

After deployment of the Helm Chart, I notice the following events:

```
0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```

On the pod from the previously mentioned StatefulSet.

```
waiting for first consumer to be created before binding
```
On the PVC from the Chart, which should claim the prepared PV.

I have searched what might be wrong with my PV, but all suggestions online did not apply. I do not have any `nodeAffinity` -- I have only a single node cluster. Neither did I have issues with `storageClassName` or picking the wrong namespace. Everything was correct AND I have provably working installations already, with the exact same spec, except with different names and different namespaces.

Everything is set up correctly and it still won't work.

So, after a long time of trying to figure out, what is wrong, when everything is de facto a 100% correct, I tried to manually force the PV to be used by the PVC, by assigning a `claimRef`, manually.

Surprisingly, it immediately started working.

### What did you expect to happen?

PVC finds and binds to PV, as it usually always did. It is the correct behaviour.

### How can we reproduce it (as minimally and precisely as possible)?

Install the following Helm Chart several times, with YAMLs staying almost the same (changing only naming) until the issue randomly appears, again.

https://github.com/bitnami/charts/tree/master/bitnami/postgresql

### Anything else we need to know?

The Chart was not updated. The Helm Chart repository was not updated between installations. The images did not change. No settings did change. It's literally the same installation.
Yesterday, it worked that way, today it suddenly does not, even when both installation are _exactly the same_, except the naming differs slightly. As in being changed from `x-database` to `y-database`. Namespace `x` to namespace `y`....

The PV leads to a directory inside the same directory, all previous PVs lead to. The directory is also created precisely the same way, the previous ones were created. So, it's not the fault of the directories, either. It's a bug in Kubernetes.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

None

### OS version

<details>

```console
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"


Linux hostname 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
```

</details>

**Comment by astraw99** [comment]
Please check the StorageClass by `kubectl get sc`, then check the field value of `VOLUMEBINDINGMODE`.
If the value is `WaitForFirstConsumer`, then need the pod to be scheduled successfully first, then bind the PVC/PV.
If the value is `Immediate(default)`, no need to wait the pod to be scheduled, will immediately bind the PVC/PV.

Please see the doc: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode

**Comment by theAkito** [comment]
> If the value is `WaitForFirstConsumer`, then need the pod to be scheduled successfully first, then bind the PVC/PV.

> Please see the doc:


Yes, I know. I have already read all the documentation on that topic.

How is that supposed to work, when the volume is waiting for the first consumer, while the pod is waiting for the first volume to be bound, even when all that is set up accordingly, to work with each other?

That also does not explain, why the scenario in question worked all the other times.

For example, I set up further apps and they all worked as expected with the same templates, versions, etc. It's always the same Helm Chart of the same version and yet it did not work at the time of creating this issue.
The PV/PVC combo was of course precisely the same. It always worked, except that time this issue occurred.

The documentation does not explain why repeating the _precisely same_ thing may yield different results.
