### ISSUE TITLE
[Flaky test] [sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#108774]
### Failure cluster [39e8b3298cff6883920e](https://go.k8s.io/triage#39e8b3298cff6883920e)

Test: [sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods

##### Error text:
```
test/e2e_node/density_test.go:248
Unexpected error:
    <*errors.errorString | 0xc00164fef0>: {
        s: "too high pod startup latency 50th percentile: 6.015599293s",
    }
    too high pod startup latency 50th percentile: 6.015599293s
occurred
test/e2e_node/density_test.go:588
```
#### Recent failures:
[3/16/2022, 1:18:16 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1504190296534028288)
[3/15/2022, 9:17:38 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1503948564064112640)
[3/11/2022, 8:08:57 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502315621528899584)
[3/11/2022, 12:06:56 AM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502194321300918272)
[3/10/2022, 4:05:24 PM ci-kubernetes-node-kubelet-serial-cri-o](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1502073143848603648)

/kind flake

/sig node

**Comment by 249043822** [comment]
```
W0316 21:43:29.881] Mar 16 20:58:49.784: INFO: The status of Pod test-1f70fda8-1ded-4312-8fef-616229996f47 is Pending, waiting for it to be Running (with Ready = true)
W0316 21:43:29.881] Mar 16 20:58:51.793: INFO: The status of Pod test-1f70fda8-1ded-4312-8fef-616229996f47 is Pending, waiting for it to be Running (with Ready = true)
W0316 21:43:29.881] Mar 16 20:58:53.788: INFO: The status of Pod test-1f70fda8-1ded-4312-8fef-616229996f47 is Pending, waiting for it to be Running (with Ready = true)
W0316 21:43:29.881] Mar 16 20:58:55.791: INFO: The status of Pod test-1f70fda8-1ded-4312-8fef-616229996f47 is Running (Ready = true)
```
Although the pod polling exhausted 4 times (interval 2s, total 6s+) to get pod Running, but from the kubelet log, the time from the pod found to Running status reported is almost less than 5s, so wo may reduce the poll interval to 1s, or make this time https://github.com/kubernetes/kubernetes/blob/5981bfd1896dff69716a98457e7e72ca866dba14/test/e2e_node/density_test.go#L238 more relaxed


```
I0316 20:58:49.782674   13879 config.go:384] "Receiving a new pod" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47"
I0316 20:58:49.784793   13879 kubelet.go:2039] "SyncLoop ADD" source="api" pods=[density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47]
I0316 20:58:49.784927   13879 topology_manager.go:200] "Topology Admit Handler"
I0316 20:58:49.785254   13879 pod_workers.go:571] "Pod is being synced for the first time" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79
I0316 20:58:49.785326   13879 pod_workers.go:888] "Processing pod event" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79 updateType=0
I0316 20:58:49.785375   13879 kubelet.go:1488] "syncPod enter" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79
I0316 20:58:49.785407   13879 kubelet_pods.go:1429] "Generating pod status" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47"
I0316 20:58:49.785443   13879 kubelet_pods.go:1441] "Got phase for pod" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" oldPhase=Pending phase=Pending
.........
.........
I0316 20:58:54.100137   13879 kuberuntime_manager.go:714] "computePodActions got for pod" podActions={KillPod:false CreateSandbox:false SandboxID:04d89ef1ec26401a2d352fe0e22bf13a53e9d620c204632bfa8c7636a7218774 Attempt:0 NextInitContainerToStart:nil ContainersToStart:[] ContainersToKill:map[] EphemeralContainersToStart:[]} pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47"
I0316 20:58:54.100296   13879 kubelet.go:1712] "syncPod exit" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79
I0316 20:58:54.100322   13879 pod_workers.go:979] "Processing pod event done" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79 updateType=0
I0316 20:58:54.100347   13879 pod_workers.go:888] "Processing pod event" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" podUID=08c4a722-3d5c-47fc-a47c-540ffa53fd79 updateType=0
I0316 20:58:54.110775   13879 status_manager.go:624] "Patch status for pod" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" patch="{\"metadata\":{\"uid\":\"08c4a722-3d5c-47fc-a47c-540ffa53fd79\"},\"status\":{\"$setElementOrder/conditions\":[{\"type\":\"Initialized\"},{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[{\"lastTransitionTime\":\"2022-03-16T20:58:54Z\",\"message\":null,\"reason\":null,\"status\":\"True\",\"type\":\"Ready\"},{\"lastTransitionTime\":\"2022-03-16T20:58:54Z\",\"message\":null,\"reason\":null,\"status\":\"True\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"containerID\":\"cri-o://f5094ae84916ab91f4c260b58bbc84812ea8fcd4ede460f8c0bed541280d855e\",\"image\":\"k8s.gcr.io/pause:3.6\",\"imageID\":\"k8s.gcr.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db\",\"lastState\":{},\"name\":\"test-1f70fda8-1ded-4312-8fef-616229996f47\",\"ready\":true,\"restartCount\":0,\"started\":true,\"state\":{\"running\":{\"startedAt\":\"2022-03-16T20:58:53Z\"}}}],\"phase\":\"Running\",\"podIP\":\"10.85.0.81\",\"podIPs\":[{\"ip\":\"10.85.0.81\"},{\"ip\":\"1100:200::51\"}]}}"
I0316 20:58:54.110882   13879 status_manager.go:633] "Status for pod updated successfully" pod="density-test-2074/test-1f70fda8-1ded-4312-8fef-616229996f47" statusVersion=2 status={Phase:Running Conditions:[{Type:Initialized Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-16 20:58:49 +0000 UTC Reason: Message:} {Type:Ready Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-16 20:58:54 +0000 UTC Reason: Message:} {Type:ContainersReady Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-16 20:58:54 +0000 UTC Reason: Message:} {Type:PodScheduled Status:True LastProbeTime:0001-01-01 00:00:00 +0000 UTC LastTransitionTime:2022-03-16 20:58:49 +0000 UTC Reason: Message:}] Message: Reason: NominatedNodeName: HostIP:10.138.0.43 PodIP:10.85.0.81 PodIPs:[{IP:10.85.0.81} {IP:1100:200::51}] StartTime:2022-03-16 20:58:49 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[{Name:test-1f70fda8-1ded-4312-8fef-616229996f47 State:{Waiting:nil Running:&ContainerStateRunning{StartedAt:2022-03-16 20:58:53 +0000 UTC,} Terminated:nil} LastTerminationState:{Waiting:nil Running:nil Terminated:nil} Ready:true RestartCount:0 Image:k8s.gcr.io/pause:3.6 ImageID:k8s.gcr.io/pause@sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db ContainerID:cri-o://f5094ae84916ab91f4c260b58bbc84812ea8fcd4ede460f8c0bed541280d855e Started:0xc0018cc3ac}] QOSClass:BestEffort EphemeralContainerStatuses:[]}
```

**Comment by pacoxu** [comment]
http://perf-dash.k8s.io/#/?jobname=kubemark-500Nodes&metriccategoryname=E2E&metricname=LoadHighThroughputPodStartup&Metric=pod_startup
![image](https://user-images.githubusercontent.com/2010320/160984677-e615808f-6135-4417-83f6-4e834b6103aa.png)

This is caused by https://github.com/kubernetes/kubernetes/pull/101566 as #109146.

The commit will be reverted, and it make https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd fail yesterday. 
![image](https://user-images.githubusercontent.com/2010320/160984845-3db5a7aa-cfaa-48e7-8471-57aec1b61a5e.png)

I mean if this flake points out there are some other performance downgrade in v1.24?

**Comment by ehashman** [comment]
Editing title as this was also failing on containerd:

### Failure cluster [c181fab877561bdb3e86](https://go.k8s.io/triage#c181fab877561bdb3e86)

##### Error text:
```
test/e2e_node/density_test.go:248
Unexpected error:
    <*errors.errorString | 0xc0011bf870>: {
        s: "too high pod startup latency 50th percentile: 26.017144013s",
    }
    too high pod startup latency 50th percentile: 26.017144013s
occurred
test/e2e_node/density_test.go:588
```
#### Recent failures:
[3/31/2022, 6:36:23 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1509524995452178432)
[3/31/2022, 2:35:23 AM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1509464345501765632)
[3/30/2022, 11:38:23 PM ci-cos-cgroupv2-containerd-node-e2e-serial](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1509419801729044480)
[3/30/2022, 10:35:23 PM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1509403946492366848)
[3/30/2022, 6:36:12 PM ci-kubernetes-node-kubelet-serial-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-containerd/1509343548275691520)

/milestone v1.24

I think this confirms that the revert above fixed the issue, as the failures stopped after the revert merged.

/close
