### ISSUE TITLE
Removal of dockershim in 1.24 is breaking change, bump major version

### ISSUE THREAD

**Issue by firewiththeflames** [kubernetes/kubernetes#108719]
### What happened?

Removal of dockershim in 1.24 has potential to break clusters. This is not minor version change

### What did you expect to happen?

Bump of major version

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

[](https://semver.org/#summary)[](https://semver.org/#introduction)Semantic Versioning 2.0.0
Summary
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards compatible manner, and
PATCH version when you make backwards compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

### Cloud provider

N/A

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
thanks for the suggestion @firewiththeflames we will not be doing this at this time.

/close

**Comment by markus-wa** [comment]
how come @dims ?
