### ISSUE TITLE
some Go modules are not tagged for v0.23.5

### ISSUE THREAD

**Issue by smira** [kubernetes/kubernetes#108763]
### What happened?

Some `k8s.io/` modules don't have a v0.23.5 tag, while others are properly tagged.

E.g. https://pkg.go.dev/k8s.io/kubectl@v0.23.4?tab=versions doesn't have v0.23.5 tag, while https://pkg.go.dev/k8s.io/api@v0.23.5 is fine.

So far I know about the following Go modules which are not tagged:

```
k8s.io/cli-runtime
k8s.io/cri-api
k8s.io/kubectl
k8s.io/kubelet
```

### What did you expect to happen?

All modules tagged consistently.

### How can we reproduce it (as minimally and precisely as possible)?

```shell
$ go get k8s.io/kubectl@v0.23.5 
go get: k8s.io/kubectl@v0.23.5: invalid version: unknown revision v0.23.5
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig architecture
[owner of staging](https://github.com/kubernetes/community/blob/4026287dc3a2d16762353b62ca2fe4b80682960a/contributors/devel/sig-architecture/staging.md)

**Comment by hiddeco** [comment]
`k8s.io/apiextensions-apiserver` can be added to the list.

> "[k8s.io/apiextensions-apiserver@v0.23.5](http://k8s.io/apiextensions-apiserver@v0.23.5)" could not be found.

https://pkg.go.dev/k8s.io/apiextensions-apiserver@v0.23.5

**Comment by dims** [comment]
@hiddeco @smira please try now. all the tags should be in sync.

Thanks,
Dims

/close

**Comment by smira** [comment]
thanks @dims it works now!
