### ISSUE TITLE
Create deployment and get deployment apiVersion is inconsistent

### ISSUE THREAD

**Issue by Jungzhang** [kubernetes/kubernetes#108722]
### What happened?

I have a nginx.yaml and use `kubectl applf -f nginx.yaml` create a deployment. The yaml file is: 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
```

My yaml file set apiVersion is `apps/v1`, but I use `kubetctl get nginx-deployment` get apiVersion is `extensions/v1beta1`. The kubectl print is:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:1.14.2","name":"nginx"}]}}}}
  creationTimestamp: "2022-03-16T05:43:10Z"
  generation: 1
  name: nginx-deployment
  namespace: default
  resourceVersion: "4648"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/nginx-deployment
  uid: e74494dd-38f4-47dc-8729-4c8fc95a5df8
spec:
  progressDeadlineSeconds: 600
.....
```

### What did you expect to happen?

The kubectl result and my yaml apiVersion consistent.

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl apply -f nginx.yaml`
`kubectl get deploy nginx-deployment -oyaml`

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-20T18:57:36Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console

# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


$ uname -a
Linux all-in-one 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jlsong01** [comment]
It can not be reproduced in my cluster with v1.21.0

could you try it with newer version or consider upgrading?

**Comment by Jungzhang** [comment]
@jlsong01 It looks like a k8s version problem. Thanks.
