### ISSUE TITLE
Add namespaces hierarchy

### ISSUE THREAD

**Issue by zfrhv** [kubernetes/kubernetes#108709]
### What would you like to be added?

Be able to create sub namespaces inside a namespace.
just as creating subdirectories inside a directory.

### Why is this needed?

- Being able to manage quotas:
  - lets say we have a big client, and they have a lot of small teams.
    I can give quota with resources as much as they paid for, and they can decide for their own to manage their resources for their sub namespaces.
- Manage permissions:
  - lets say I have many clients, i just give 1 namespace for each leader. and they can manage their own permissions for themselves in their own sub namespaces.
- Easier to sort applications

**Comment by ialidzhikov** [comment]
@zfrhv you can check the following project https://github.com/kubernetes-sigs/hierarchical-namespaces.

**Comment by zfrhv** [comment]
well, looks great
we will try it out. thanks !
