### ISSUE TITLE
Retry cronjob after specific time interval

### ISSUE THREAD

**Issue by thamaraiselvam** [kubernetes/kubernetes#108703]
### What happened?

I am trying to retry failed cron job after specific time interval rather than immediate retry, Is there way to do it?

### What did you expect to happen?

I could not find anything related to this on Kubernetes documentation

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Anything else we need to know?

NA

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:32:41Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
AKS
</details>

**Comment by soumyadipDe** [comment]
This can be useful if a job is dependent on a pod which gets evicted from node and takes a bit of time to come up
