### ISSUE TITLE
access kube-api with DNS

### ISSUE THREAD

**Issue by mohan-nagandlla** [kubernetes/kubernetes#108793]
### What happened?

I am accessing the kube-api with IP address

### What did you expect to happen?

instead of using the IP can i use the DNS 

### How can we reproduce it (as minimally and precisely as possible)?

the kubeconf contian only DNS how the public clouds are working same way in on-prem i need to use that DNS to connect the cluster. 

### Kubernetes version

1.18.9

### Cloud provider

kubespray

### OS version

ReadHat enterprises VM

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig api-machinery
/remove-kind bug
/kind feature

this was requested somewhere before, but i don't think it had a designated ticket.
re-using `--{advertise|bind}-address` would have some weird implications around the current `net.IP` based validation.

> 1.18.9

note that even if such a feature lands, i will likely not be backported to older releases.
<1.21 is out of support.

**Comment by fedebongio** [comment]
Not sure about people opinions here, tagging some people to see thoughts:
/cc @lavalamp @deads2k @thockin 
/triage accepted

**Comment by lavalamp** [comment]
Yes, you can use a DNS address to reach apiserver (assuming the DNS address is set up correctly).

I don't understand the question though? What exactly is the OP trying to do? What is not working?

**Comment by mohan-nagandlla** [comment]
hi @lavalamp  I hope the way of questioning is wrong I will ask some more briefly my query was
I have accessed the cluster with IP ex: https://147.x.x.x:6443/ now instead of on this IP I want to access the k8s API with DN ex: https://my-domin.com:6443/ which is resolvable. How do I modify the playbook to append the DN?

**Comment by lavalamp** [comment]
What playbook are you referring to?

Who is "I", is it "I, the user with a kubeconfig file"? Or is it "I, kubelet"? Something else? In any case, how am "I" getting "my" kubeconfig file?

Is the DNS name properly configured? (there's a billion ways to do this and you'll find better help on e.g. stackoverflow, most likely)

**Comment by neolit123** [comment]
i think the description confused me and the user wanted to allow the kube-apiserver to listen on a hostname and not only IP. sorry about that. for configuring access to using kubeconfig files this falls under support and is not a FR.

please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by neolit123** [comment]
> i think the description confused me and the user wanted to allow the kube-apiserver to listen on a hostname and not only IP. sorry about that. for configuring access to using kubeconfig files this falls under support and is not a FR.

if you really want to modify the scope of the kube-apiserver flags for binding and listening. reopen the issue and provide the details.
