### ISSUE TITLE
[el7, yum] Signature could not be verified for kubernetes

### ISSUE THREAD

**Issue by Joseph94m** [kubernetes/kubernetes#108732]
### What happened?

reposting following @neolit123 's suggestion : [90158](https://github.com/kubernetes/kubernetes/issues/90158#issuecomment-1068956071)

As per [documentation](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/), installing kubeadm, kubelet and kubectl on rhel releases (el7) using the following configuration where K8S_VERSION=1.21.10 (also tried with 1.19.15)

```
echo "Kubernetes version: $K8S_VERSION"
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

# Set SELinux in permissive mode (effectively disabling it)
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

sudo yum install -y kubelet-$K8S_VERSION kubeadm-$K8S_VERSION kubectl-$K8S_VERSION --disableexcludes=kubernetes

sudo systemctl enable --now kubelet
```

```
Kubernetes version: 1.21.10
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.plusserver.com
 * epel: mirror.23m.com
 * extras: mirror.plusserver.com
 * updates: mirror.plusserver.com
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x7AA99B80:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: e89b faec 34d3 1829 362f 7f7b 5668 44f3 7aa9 9b80
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.


 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
```

### What did you expect to happen?

Expected the command `
sudo yum install -y kubelet-$K8S_VERSION kubeadm-$K8S_VERSION kubectl-$K8S_VERSION --disableexcludes=kubernetes` to succeed, where $K8S_VERSION=1.21.10 

### How can we reproduce it (as minimally and precisely as possible)?

- Provision an el7 machine (physical or virtual). 
- Follow the [doc](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) to setup a red hat release node (el7) with kubeadm, kubelet, kubectl
- This fails whether you are initialising a new cluster or whether you are joining a new node to an existing  cluster

### Anything else we need to know?

I haven't changed the scripts I use to setup new k8s clusters/add new nodes for a while. I checked the process up until  the point where the installation fails. Nothing seems to have really changed compared to the documentation.

I was able to successfully install a ubuntu machine with k8s (using the appropriate process of course)

### Kubernetes version

```
1.21.10 and 1.19.15 (separate)
```

### Cloud provider

OVH

### OS version

```console
$ uname -a
Linux worker-2 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ hostnamectl
   Static hostname: worker-2
         Icon name: computer-vm
           Chassis: vm
        Machine ID: cab9605edaa5484da7c2f02b8fd10762
           Boot ID: 90b6f0148edc41f98250f1f6273a896c
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1160.53.1.el7.x86_64
      Architecture: x86-64
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Install tools

yum, kubeadm

**Comment by Joseph94m** [comment]
In the past, we experienced some similar failures while setting up kubernetes on el7 machines (some centos 7 mirrors were down, sometimes ovh network), but it was never consistently failing. 

Right now, I've been experiencing these failures consistently every run since about friday last week

**Comment by TeddyAndrieux** [comment]
+1, to "workaround" it you can disable `repo_gpgcheck` but I agree that it should be fixed either by updating the documentation or fixing the signature

**Comment by Joseph94m** [comment]
Is your cloud provider also in France/OVH? I was wondering if this was a regional mirror issue thing....

**Comment by TeddyAndrieux** [comment]
From what I see it's not a regional mirror issue, I tried on my laptop locally in France and also with some VMs in NorthAmerica

**Comment by samuelan** [comment]
I am having same exact issue. Our internal Artifactory repo mirrors the yum repo, but it fails at the repomd.xml signature verification step, just like @Joseph94m experienced. 

I know disable repo_gpgcheck works, but it's not good for security reasons.

**Comment by neolit123** [comment]
the problem is not reproducible on Fedora as noted here and comments bellow:
https://github.com/kubernetes/website/issues/32117#issuecomment-1063549918

**Comment by awalker125** [comment]
I'm seeing this as well. See like the key changed recently "cloud-rapture-signing-key-2022-03-07-08_01_01.pub"

**Comment by cxxaa1** [comment]
Should this issue be labeled as " priority/critical-urgent"?

We are doing research about “Effective Issue Priority Prediction".We have developed a tool to automatically label the priority and kind.
We first collected all past issue reports from the kubernetes repository containing the priority label and kind label. We then trained a nlp deep model. The experiments on a dataset of 730 issues show that 77% accuracy can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority/critical-urgent 
Could you please tell us whether it should be labeled as priority/critical-urgent?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by samuelan** [comment]
Here is what I did as a work around till the repo signing key issue is resolved. Just curl down the rpm(s) I needed. In this case, I only needed one, e.g kubectl-1.22.7
COPY kubectl-1.22.7-0.x86_64.rpm /tmp/
RUN rpm --import https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg && \
rpm -K /tmp/kubectl-1.22.7-0.x86_64.rpm && \
yum install -y /tmp/kubectl-1.22.7-0.x86_64.rpm

It has helped me to unblock my builds.

**Comment by TeddyAndrieux** [comment]
As a workaround, you just have to set `repo_gpgcheck` to `0`

**Comment by gunniLEE** [comment]
~
