### ISSUE TITLE
kubectl patch doesn't have --ignore-not-found

### ISSUE THREAD

**Issue by jflambert** [kubernetes/kubernetes#108798]
/sig cli

### What happened?

I use `--ignore-not-found=true` for `delete/stop/get/etc` but it looks like that flag isn't available for `kubectl patch`

### What did you expect to happen?

I want to be able to use `--ignore-not-found=true` in `kubectl patch`

### How can we reproduce it (as minimally and precisely as possible)?

```
$ kubectl patch crd/xxx.com -p '{"metadata":{"finalizers":[]}}' --type=merge --kubeconfig kind.yaml
Error from server (NotFound): customresourcedefinitions.apiextensions.k8s.io "xxx.com" not found

$ kubectl patch crd/xxx.com -p '{"metadata":{"finalizers":[]}}' --type=merge --kubeconfig kind.yaml --ignore-not-found=true
error: unknown flag: --ignore-not-found
See 'kubectl patch --help' for usage.
```

### Kubernetes version

$ kubectl version --kubeconfig kind.yaml 
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.10", GitCommit:"a7a32748b5c60445c4c7ee904caf01b91f2dbb71", GitTreeState:"clean", BuildDate:"2022-03-07T09:03:24Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1

### Cloud provider

N/A

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic</details>


### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

**Comment by joaquinza** [comment]
I need this too. Please and thank you.

**Comment by jastabiletech** [comment]
It's a nice to have, for an automation for a deployment in kubernetes it will helm me too

**Comment by dokuboyejo** [comment]
Needed...
