### ISSUE TITLE
Nodes become NotReady when time jumps forward

### ISSUE THREAD

**Issue by Shaye-man** [kubernetes/kubernetes#108844]
### What happened?

When I jump forward the cluster time by one day, I find that all nodes will briefly become "NotReady", like this, after about 10s, nodes will become "Ready" again.

I found that the node lease resource normally updates the renewtime to a day ago in a nodeStatusUpdateFrequency period, and only kube-controller-manager thinks that the node has exceeded the heartbeat detection cycle, log like this:
```
I0404 15:28:36.488138       8 node_lifecycle_controller.go:1107] node paas-192-168-21-186 hasn't been updated for 1m26.899981721s. Last PIDPressure is: &NodeCondition{Type:PIDPressure,Status:Unknown,LastHeartbeatTime:2022-04-05 15:22:52 +0500 DSTD,LastTransitionTime:2022-04-04 15:28:30 +0500 DSTD,Reason:NodeStatusUnknown,Message:Kubelet stopped posting node status.,}
I0404 15:28:36.488183       8 node_lifecycle_controller.go:897] Node paas-192-168-21-186 is unresponsive as of 2022-04-04 15:28:36.488176491 +0500 DSTD m=+237.395296883. Adding it to the Taint queue.
I0404 15:28:46.506843       8 node_lifecycle_controller.go:908] Node paas-192-168-21-186 is healthy again, removing all taints
```

### What did you expect to happen?

When time jumps forward, nodes should remain ready status.

### How can we reproduce it (as minimally and precisely as possible)?

Jump the cluster time forward for more than one heartbeat detection cycle(nodeStatusUpdateFrequency period).

### Anything else we need to know?

I think this problem is that `node_life_cycle_controller(kube-controller-manager)` does not consider the time jump forward scenario when doing node health detection.

Related code snippet:
In `kubernetes/pkg/controller/nodelifecycle/node_lifecycle_controller.go`, function `tryUpdateNodeHealth()` will check a given node's conditions and tries to update it. Only when `savedLease.Spec.RenewTime.Before(observedLease.Spec.RenewTime)`  will update nodeHealth probeTimestamp.

https://github.com/kubernetes/kubernetes/blob/e4fe90e6ef796583b81a559364a241579efc3593/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1055-L1063

When `nc.now().After(nodeHealth.probeTimestamp.Add(gracePeriod))`, it will update node to NotReady. 
> **When the cluster time jumps forward**,  `savedLease.Spec.RenewTime` is newer than `observedLease.Spec.RenewTime`, so nodeHealthy.probeTimestamp will no refresh, and here use the go monotonic clock, so this judgment condition will be established.

https://github.com/kubernetes/kubernetes/blob/e4fe90e6ef796583b81a559364a241579efc3593/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1065-L1101

When next `nodeStatusUpdateFrequency` period become, `kubelet` will `syncNodeStatus()`, and refresh node `Ready` again.

Possible fixes:
When `kubelet` had refresh lease, `node_life_cycle_controller` should think the node is ok.
![image](https://user-images.githubusercontent.com/40355276/159239638-de71f520-0b76-4cb1-8e9b-a29bd9b9c9f8.png)

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.1
```

</details>

### Cloud provider

<details>
Not using cloud provider
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="EulerOS"
VERSION="2.0 (SP9x86_64)"
ID="euleros"
VERSION_ID="2.0"
PRETTY_NAME="EulerOS 2.0 (SP9x86_64)"
ANSI_COLOR="0;31"
$ uname -a
Linux PaaSCore-1 4.18.0-147.5.1.0.h208.eulerosv2r9.x86_64 #1 SMP Sun Sep 27 12:47:01 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
I installed with source code, the tag is release-1.22
</details>

### Container runtime (CRI) and version (if applicable)

<details>
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
What is the scenario when you need to set time forward by one day?

We tend to close this as this is not a supported scenario and the side effect is minimal in this case. Please re-open if you have a legit scenario for changing time forward.

/close
