### ISSUE TITLE
[flake][sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance] 

### ISSUE THREAD

**Issue by mkimuram** [kubernetes/kubernetes#108891]
### Which jobs are flaking?

pull-kubernetes-conformance-kind-ga-only-parallel

### Which tests are flaking?

[sig-node] Pods should run through the lifecycle of Pods and PodStatus [Conformance] 

### Since when has it been flaking?

After https://github.com/kubernetes/kubernetes/pull/93459 is merged.

### Testgrid link

https://testgrid.k8s.io/sig-testing-kind#pull-kubernetes-conformance-kind-ga-only-parallel&include-filter-by-regex=should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

### Reason for failure (if possible)

It relies on events which are not reliable as discussed [here](https://github.com/kubernetes/kubernetes/issues/71646).

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
The test is not failing that much looking at the testgrid. Is it actually an issue?

**Comment by mkimuram** [comment]
Not so often, but it does happen. So, I think that it is worth fixing. 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-kind-ga-only-parallel/1506333769781481472
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-kind-ga-only-parallel/1505552248724262912
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-conformance-kind-ga-only-parallel/1505455613910454272

**Comment by liggitt** [comment]
still flaking - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109048/pull-kubernetes-e2e-kind-ipv6/1507725298496442368

**Comment by liggitt** [comment]
flaking conformance tests are concerning and should take priority over new conformance test additions

**Comment by aojea** [comment]
/remove-lifecycle stale

I still see this test failing , also in periodic jobs

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

seems like it's is still failing

**Comment by aojea** [comment]
still flake

https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=kind&test=Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus


/remove-lifecycle stale

**Comment by SergeyKanzhelev** [comment]
@Namanl2001 please unassign if you are not working on it. Seems to be still flaking

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-triage/index.html?test=%20Pods%20should%20run%20through%20the%20lifecycle%20of%20Pods%20and%20PodStatus

It still flakes but not that much.

I checked the history:  https://github.com/kubernetes/kubernetes/commit/079764ebd5477c77acb11a55587d2499f9c25138 adjusted the the timeout from 30s to 1m.

https://github.com/kubernetes/kubernetes/pull/108892 change it not fail for watching Delete Event, and just print it like below:
```
Sep 19 13:14:45.477: INFO: failed to see DELETED event: timed out waiting for the condition
```

This time, we see the above adding warning and then failed. Looking into kubelet/container runtime log. The pod is just deleted after 1 min, maybe 1min10s. 

> Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.769070     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"
> Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: E0919 13:14:56.769398     359 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to delete cgroup paths for [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice" pod="pods-900/pod-test" podUID=53d19839-496a-4be8-8964-84ee83de9353
> Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.927805     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"
> Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.937404     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"

I'm afraid that we have to adjust the timeout of the delete pod again to fix it. Is `1min` a valid pod deletion timeout? I think most deletion timeout of pod is 5min(too long after pod with `TerminationGracePeriodSeconds=1s`)

**Comment by aojea** [comment]
but why it takes so long kubelet to delete a pod?

what are all of those ""Failed to delete cgroup paths"  messages? can this be hiding some problem with runc or the kubelet?

**Comment by pacoxu** [comment]
- Sep 19 13:13:47 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:13:47.313835166Z" level=info msg="StopContainer for \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" with timeout 1 (s)"
- Sep 19 13:13:47 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:13:47.323305023Z" level=info msg="Stop container \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" with signal terminated"
- Sep 19 13:13:48 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:13:48.362098645Z" level=info msg="Kill container \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\""
- Sep 19 13:13:48 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:13:48.749647327Z" level=info msg="Container to stop \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" must be in running or unknown state, current state \"CONTAINER_EXITED\""
- Sep 19 13:13:48 kinder-external-etcd-worker-2 systemd[1]: run-containerd-io.containerd.runtime.v2.task-k8s.io-2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee-rootfs.mount: Deactivated successfully.
- Sep 19 13:14:22 kinder-external-etcd-worker-2 systemd[1]: var-lib-kubelet-pods-53d19839\x2d496a\x2d4be8\x2d8964\x2d84ee83de9353-volumes-kubernetes.io\x7eprojected-kube\x2dapi\x2daccess\x2db9bff.mount: Deactivated successfully.
- Sep 19 13:14:26 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:26.599400427Z" level=info msg="RemoveContainer for \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\""
- Sep 19 13:14:26 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:26.612176878Z" level=info msg="RemoveContainer for \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" returns successfully"
- Sep 19 13:14:28 kinder-external-etcd-worker-2 systemd[1]: Removed slice libcontainer container kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice.
- Sep 19 13:14:31 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:31.524882659Z" level=info msg="StopPodSandbox for \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\""
- Sep 19 13:14:31 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:31.727298674Z" level=info msg="TearDown network for sandbox \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\" successfully"
- Sep 19 13:14:31 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:31.727372544Z" level=info msg="StopPodSandbox for \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\" returns successfully"
- Sep 19 13:14:31 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:31.729609244Z" level=info msg="RemovePodSandbox for \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\""
- Sep 19 13:14:31 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:31.729680953Z" level=info msg="Forcibly stopping sandbox \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\"
- Sep 19 13:14:32 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:32.001374400Z" level=info msg="TearDown network for sandbox \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\" successfully"
- Sep 19 13:14:32 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:32.023003174Z" level=info msg="RemovePodSandbox \"1dca450ff0d262cdc9e6e3d07c99cd4d78a1240436616d3319bfd2fe9402874e\" returns successfully"
- Sep 19 13:14:44 kinder-external-etcd-worker-2 kubelet[359]: E0919 13:14:44.929383     359 cpu_manager.go:395] "RemoveStaleState: removing container" podUID="53d19839-496a-4be8-8964-84ee83de9353" containerName="pod-test"
- Sep 19 13:14:44 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:44.932460     359 memory_manager.go:346] "RemoveStaleState removing state" podUID="53d19839-496a-4be8-8964-84ee83de9353" containerName="pod-test"
- **Test failed @ In [It] at: test/e2e/common/node/pods.go:1070 @ 09/19/23 13:14:45.488**
- Sep 19 13:14:45 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:45.664262455Z" level=error msg="ContainerStatus for \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" failed" error="rpc error: code = NotFound desc = an error occurred when try to find container \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\": not found"
- Sep 19 13:14:45 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:45.664262455Z" level=error msg="ContainerStatus for \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\" failed" error="rpc error: code = NotFound desc = an error occurred when try to find container \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\": not found"
- Sep 19 13:14:45 kinder-external-etcd-worker-2 kubelet[359]: E0919 13:14:45.668402     359 remote_runtime.go:415] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find container \"2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee\": not found" containerID="2dd4d0a67942263b4dbc37d677fd3c53e3607f21487480c77dfb2a9c2f37d2ee"
- Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.769070     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"
Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: E0919 13:14:56.769398     359 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to delete cgroup paths for [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice" pod="pods-900/pod-test" podUID=53d19839-496a-4be8-8964-84ee83de9353
Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.927805     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"
Sep 19 13:14:56 kinder-external-etcd-worker-2 containerd[220]: time="2023-09-19T13:14:56.925525892Z" level=info msg="StartContainer for \"e3b435116d2640d7c8166332e1c4bf6722f97ac1401035cbe443704c8b442efd\" returns successfully"
Sep 19 13:14:56 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:14:56.937404     359 pod_container_manager_linux.go:210] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] err="unable to destroy cgroup paths for cgroup [kubepods besteffort pod53d19839-496a-4be8-8964-84ee83de9353] : Timed out while waiting for systemd to remove kubepods-besteffort-pod53d19839_496a_4be8_8964_84ee83de9353.slice"
- Sep 19 13:15:01 kinder-external-etcd-worker-2 kubelet[359]: I0919 13:15:01.056684     359 kubelet_volumes.go:161] "Cleaned up orphaned pod volumes dir" podUID=53d19839-496a-4be8-8964-84ee83de9353 path="/var/lib/kubelet/pods/53d19839-496a-4be8-8964-84ee83de9353/volumes"


It means `crictl rm -f xxx` timeout.

Another failure is not for the same reason. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1703180700330496000

> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516373     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516448     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/blkio/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/blkio/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516505     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/memory/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/memory/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516542     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516591     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/pids/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/pids/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516631     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/cpuset/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpuset/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516671     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podee3d4d85_6253_45c4_9aa2_816e0c481f9e.slice/cri-containerd-1d07ac3f4e9bac60448eecdbed71ac06e425b037a19508d72938673a685c1141.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podee3d4d85_6253_45c4_9aa2_816e0c481f9e.slice/cri-containerd-1d07ac3f4e9bac60448eecdbed71ac06e425b037a19508d72938673a685c1141.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516713     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podee3d4d85_6253_45c4_9aa2_816e0c481f9e.slice/cri-containerd-1d07ac3f4e9bac60448eecdbed71ac06e425b037a19508d72938673a685c1141.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podee3d4d85_6253_45c4_9aa2_816e0c481f9e.slice/cri-containerd-1d07ac3f4e9bac60448eecdbed71ac06e425b037a19508d72938673a685c1141.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516757     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516794     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podfc0d6335_c73f_4b19_8092_6e315e23abdd.slice/cri-containerd-54bec0764968959f382b1d34a9ede1a64923f7aa97d23934e532feedbdc8debf.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.516830     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/cpuset/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpuset/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: I0916 23:23:58.517620     245 factory.go:260] Factory "systemd" was unable to handle container "/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod5fada39f_b2be_479f_af89_559629a33ea0.slice/cri-containerd-8fe65ad99c07ef448dbb40309c244a70bf6b5bc73359271909326c2e16b720fe.scope"
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.518589     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/hugetlb/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.518774     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/perf_event/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod744cbdea_4aa8_4956_94c9_c77f0f366d50.slice/cri-containerd-a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb.scope: no such file or directory
> Sep 16 23:23:58 kind-worker2 kubelet[245]: W0916 23:23:58.518843     245 watcher.go:93] Error while processing event ("/sys/fs/cgroup/cpu,cpuacct/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod9dcb6855_1aac_4674_a4e6_9fb70b5eb3f2.slice/cri-containerd-eb15037eabfb0a1a077434891f80aedf2138f356605d0029724028f70aed3a34.scope": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/cpu,cpuacct/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-pod9dcb6855_1aac_4674_a4e6_9fb70b5eb3f2.slice/cri-containerd-eb15037eabfb0a1a077434891f80aedf2138f356605d0029724028f70aed3a34.scope: no such file or directory
> Sep 16 23:24:13 kind-worker2 kubelet[245]: E0916 23:24:13.668385     245 remote_runtime.go:432] "ContainerStatus from runtime service failed" err="rpc error: code = NotFound desc = an error occurred when try to find container \"a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb\": not found" containerID="a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb"
> Sep 16 23:24:13 kind-worker2 kubelet[245]: I0916 23:24:13.668472     245 kuberuntime_container.go:1138] "Failed to get container status" containerID="containerd://a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb" err="rpc error: code = NotFound desc = an error occurred when try to find container \"a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb\": not found"
> Sep 16 23:24:28 kind-worker2 kubelet[245]: I0916 23:24:28.649663     245 status_manager.go:883] "Status for pod updated successfully" pod="pods-2332/pod-test" statusVersion=6 status={"phase":"Failed","conditions":[{"type":"Initialized","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-09-16T23:22:56Z"},{"type":"Ready","status":"False","lastProbeTime":null,"lastTransitionTime":"2023-09-16T23:23:52Z","reason":"PodFailed"},{"type":"ContainersReady","status":"False","lastProbeTime":null,"lastTransitionTime":"2023-09-16T23:23:52Z","reason":"PodFailed"},{"type":"PodScheduled","status":"True","lastProbeTime":null,"lastTransitionTime":"2023-09-16T23:22:56Z"}],"hostIP":"fc00:f853:ccd:e793::4","startTime":"2023-09-16T23:22:56Z","containerStatuses":[{"name":"pod-test","state":{"terminated":{"exitCode":2,"reason":"Error","startedAt":"2023-09-16T23:23:12Z","finishedAt":"2023-09-16T23:23:16Z","containerID":"containerd://a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb"}},"lastState":{},"ready":false,"restartCount":0,"image":"registry.k8s.io/e2e-test-images/agnhost:2.45","imageID":"registry.k8s.io/e2e-test-images/agnhost@sha256:2c5b5b056076334e4cf431d964d102e44cbca8f1e6b16ac1e477a0ffbe6caac4","containerID":"containerd://a661ef1c950f125ff019f0704c6f9cffa52c6101b0d7321d3054d9a55c61dffb","started":false}],"qosClass":"BestEffort"}

**Comment by aojea** [comment]
This is starting to be worrisome

**Comment by alculquicondor** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121487/pull-kubernetes-e2e-kind-ipv6/1717241677246107648 another failure

**Comment by pacoxu** [comment]
Flake in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-kubernetes-e2e-kind-kms/1733657175252799488 `sig-release-master-informing#periodic-kubernetes-e2e-kind-kms`. 

> Dec 10 01:56:05.511: INFO: failed to see DELETED event: timed out waiting for the condition
> In [It] at: test/e2e/common/node/pods.go:1070 @ 12/10/23 01:56:05.521
> < Exit [It] should run through the lifecycle of Pods and PodStatus [Conformance] - test/e2e/common/node/pods.go:897 @ 12/10/23 01:56:05.521 (1m8.427s)

Delete timeout is 1 minute here.  It still need more investigation why this is not deleted in 1 min.(heavy load or logic problems.)

**Comment by pacoxu** [comment]
Flake twice in https://testgrid.k8s.io/sig-release-master-informing#periodic-kubernetes-e2e-kind-kms yersterday.
