### ISSUE TITLE
Dash app webpage is continuously refreshing while using nodeport or clusterIP

### ISSUE THREAD

**Issue by kranthiakssy** [kubernetes/kubernetes#108875]
I have created a simple dash web page app that takes the CSV/excel file and plots the data. And I have created a Kubernetes cluster on local ubuntu machines with 1-master and 2-worker nodes to deploy my application. All the nodes, pods, services, deployments, and docker images are running fine. But when I'm using the application, the web page is continuously refreshing in some cases.
1. When accessing through individual pod IP, the web page works fine and doesn't refresh automatically.
2. When accessing through cluserIP, the web page is refreshing continuously.
3. When accessing through clisterIP port-forwarding, it is fine and doesn't refresh.
4. When accessing through node port,  the web page is refreshing continuously.
5. When accessing through external IP, the web page is refreshing continuously.
I cannot understand whether the problem is related to the application or Kubernetes cluster implementation.
Kindly help me to understand/resolve the issue.
Thanks!

**Comment by neolit123** [comment]
> Dash app webpage

hi, is "Dash app" this?
https://plotly.com/dash/kubernetes/ 

it doesn't sound like a core k8s problem, so please report the issue to the "Dash app" authors.
sounds like it might need some adjustments based on service types.

/close

**Comment by kranthiakssy** [comment]
Yeah. This is one I'm using. https://plotly.com/dash/kubernetes/

Thanks for the reply!
