### ISSUE TITLE
APIServer create got err `IsAlreadyExists`, but the returned obj is just an empty resource struct

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#108839]
### What would you like to be added?

If APIServer create got err `IsAlreadyExists`, the returned obj should be the current resource obj, instead of a bare resource type with empty fields.

### Why is this needed?

When we create resource, the returned err is checked, and often get err `IsAlreadyExists`, then it is better to
return the current resource obj.

Currently, the returned obj is just a bare resouce type with all empty fields(below), just `not nil`, but no other available usages.

`Pod` eg:
https://github.com/kubernetes/kubernetes/blob/21184400a4ac185e7e4c6ddb52eb9c25a4cc453f/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod.go#L120-L130

From the source code, we can see the default returning obj is just an empty resource struct.

```go
&Pod{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},Spec:PodSpec{Volumes:[]Volume{},Containers:[]Container{},RestartPolicy:,TerminationGracePeriodSeconds:nil,ActiveDeadlineSeconds:nil,DNSPolicy:,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:nil,ImagePullSecrets:[]LocalObjectReference{},Hostname:,Subdomain:,Affinity:nil,SchedulerName:,InitContainers:[]Container{},AutomountServiceAccountToken:nil,Tolerations:[]Toleration{},HostAliases:[]HostAlias{},PriorityClassName:,Priority:nil,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[]PodReadinessGate{},RuntimeClassName:nil,EnableServiceLinks:nil,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[]TopologySpreadConstraint{},EphemeralContainers:[]EphemeralContainer{},SetHostnameAsFQDN:nil,},Status:PodStatus{Phase:,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{},QOSClass:,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{},EphemeralContainerStatuses:[]ContainerStatus{},},}
```

**Comment by fedebongio** [comment]
Hi @astraw99 thank you for your issue. We triaged it in the meeting, but we will need some more info to try to help you, like steps to reproduce at least. 
Thanks!
Fede

**Comment by astraw99** [comment]
> Hi @astraw99 thank you for your issue. We triaged it in the meeting, but we will need some more info to try to help you, like steps to reproduce at least. Thanks! Fede

OK, got it.

**Comment by astraw99** [comment]
@fedebongio PTAL thanks.

From the source code, we can see the default returning obj is just an empty resource struct.
https://github.com/kubernetes/kubernetes/blob/21184400a4ac185e7e4c6ddb52eb9c25a4cc453f/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/pod.go#L120-L130

**Comment by liggitt** [comment]
The server response is an error v1 Status response. The response is either an error or the successful create. The client doesn't have the information needed to return the existing object.
