### ISSUE TITLE
Cleanup: pkg/util/ipset 

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#108801]
As exposed in https://github.com/kubernetes/kubernetes/pull/108351 the validate logic should probably return an `error` and the test should compare the error string with a known value - to prove that it failed for the right reasons.

Additionally the test could uset `t.Run()` to print a helpful name, rather than the comments tracking `// case[3]` 

Easy change, good beginner case.

**Comment by yashsingh74** [comment]
It is taken care by @chengleqi

/assign @chengleqi

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/kubernetes/pull/108946 fixes this issues
/assign
/unassign muyangren2

**Comment by ElvertMora** [comment]
#109007 fix done
