### ISSUE TITLE
Add Suspend subresource

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#108851]
### What would you like to be added?

A subresource (similar to `Scale`) to "suspend" apps. 

In https://github.com/kubernetes/kubernetes/issues/97170 we added suspend to the job api, which we view as a primitive that higher-level orchestrators can use to support job queuing, all-or-nothing scheduling and whole job preemption. The idea is that jobs managed by a higher level orchestrator should be created in a “suspended” state, the orchestrator unsuspends the job when it determines that all the conditions are met for the job to run.

 

### Why is this needed?

So that job management controllers can start/suspend custom job types (e.g., MPIJob or TFJob)

/sig apps
/wg batch

**Comment by alculquicondor** [comment]
Dup of #107294
