### ISSUE TITLE
Volume with nil volumespec in ASW cannot be attached after detach failure

### ISSUE THREAD

**Issue by houjun41544** [kubernetes/kubernetes#108869]
### What happened?

There was a running statefulset pod1 c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1 on node 193.168.0.4 which used an attachable csi volume1 pvc-a8a42021-cf86-48b3-9fcb-619d5a49914c.
After upgrading the k8s cluster, the Pod was not running due to the mount failure and could not  be recovered. The mount failed because the volumeattach could not be obtained while waitingforattach.
```
I0309 01:23:43.334949 1683068 reconciler.go:269] "operationExecutor.MountVolume started for volume \"pvc-a8a42021-cf86-48b3-9fcb-619d5a49914c\" (UniqueName: \"kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae\") pod \"c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1\" (UID: \"78fb9813-4bb1-4c7d-bdf1-9385c0463a0d\") "
I0309 01:23:43.335284 1683068 operation_generator.go:587] MountVolume.WaitForAttach entering for volume "pvc-a8a42021-cf86-48b3-9fcb-619d5a49914c" (UniqueName: "kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae") pod "c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1" (UID: "78fb9813-4bb1-4c7d-bdf1-9385c0463a0d") DevicePath ""
E0309 01:23:43.337184 1683068 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae podName: nodeName:}" failed. No retries permitted until 2022-03-09 01:23:43.837170956 +0800 CST m=+18.561296072 (durationBeforeRetry 500ms). Error: MountVolume.WaitForAttach failed for volume "pvc-a8a42021-cf86-48b3-9fcb-619d5a49914c" (UniqueName: "kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae") pod "c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1" (UID: "78fb9813-4bb1-4c7d-bdf1-9385c0463a0d") : volume attachment is being deleted
```
Use` kubectl get` to get this VA, it really does not exist anymore.

Analyze kube-controller-manager log, as follows:
1、During the upgrade, node 193.168.0.4 was not ready and pod1 was evicted.
Kube-controller-manager1 is the leader controller-manager. 
```
I0309 01:17:06.936269       1 event.go:291] "Event occurred" object="opcs/c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I0309 01:19:10.662406       1 taint_manager.go:106] "NoExecuteTaintManager is deleting pod" pod="opcs/c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1"
I0309 01:19:10.662622       1 event.go:291] "Event occurred" object="opcs/c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Marking for deletion Pod opcs/c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1"
```
2、The leader of kube-controller-manager changed to kube-controller-manager2 before volume1 was detached and the new pod1 was created. New pod1 was created on the same node.
I can see below in kube-controller-manager logs.
```
Log file created at: 2022/03/09 01:22:38
Running on machine: controller-2

I0309 01:23:15.197496       1 event.go:291] "Event occurred" object="opcs/c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka" kind="StatefulSet" apiVersion="apps/v1" type="Normal" reason="SuccessfulCreate" message="create Pod c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka-1 in StatefulSet c61ec4d5-a31f-44f8-ae5d-80c6fc85b1e0-kafka successful"

I0309 01:23:16.295708       1 operation_generator.go:1577] Verified volume is safe to detach for volume "nil" (UniqueName: "kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae") on node "193.168.0.4"
E0309 01:23:16.877068       1 csi_attacher.go:726] kubernetes.io/csi: detachment for VolumeAttachment for volume [620a6e22-6e58-4e96-9e9e-fa75a9cc9eae] failed: rpc error: code = Internal desc = ControllerUnpublishVolume Detach Volume failed with error get volume info err http request error
```
When kube-controller-manager2 started, attach/detach controller restored DSW and ASW.  Volume1 did not exist in DSW because pod1 had been deleted. Volume1 was restored from node.Status.VolumesAttached and added to ASW but the volume specs in the ASW was nil.
The attach/detach controller started detaching volume1 but failed with csi attach error. However I saw in the csi-attacher logs that after many retries, volume1 finally detached successfully.
So volume1 still existed in ASW, but VA was removed by csi-attacher .

3、After that,  new pod1 was created on the same node and volume1 was added to DSW. Since volume1 exists in both DSW and ASW, attach/detach controller no longer started detaching volume1.
Then the kubelet started to mount volume1 for the new pod1, which fails during waitforattach because the VA could not be found.

4、Additionally, the attach/detach controller periodically checks the attach status of the volume and fixes exceptions. But it failed due to nil  volumespec.  So volume1 that has no va cannot be removed from ASW.
```
E0309 01:24:14.140761       1 operation_executor.go:714] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae
E0309 01:25:14.227614       1 operation_executor.go:714] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae
E0309 01:26:14.265983       1 operation_executor.go:714] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/opdisk.csi.op.org^620a6e22-6e58-4e96-9e9e-fa75a9cc9eae
```

We've had this problem twice recently.

In [VerifyVolumesAreAttached](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_executor.go#L800), I think if we need to get volumespec from DSW when VolumeSpec == nil in ASW.
Or，in [ProcessPodVolumes](https://github.com/kubernetes/kubernetes/blob/95e30f66c300c76ce21c0ca0e8bc4bf4a45e028f/pkg/controller/volume/attachdetach/util/util.go#L261)，when pod is added, replace nil volumespec in ASW with the ones found on pod.

This issue is somewhat similar to the previous issue #108221, both related to nil volumespec, and csi-attacher encounters some exceptions.

### What did you expect to happen?

In the scenario of this issue, the Statefulset pod with the attached csi volume can be successfully recreated.

### How can we reproduce it (as minimally and precisely as possible)?

K8S cluster upgrade. 
Statefulset pods are evicted and recreated, with kube-controller-manager changing leader and csi-attacher exceptions.

### Kubernetes version

<details>

```console
$ kubectl version
v1.22.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Levi080513** [comment]
Is there any progress on this issue?
This problem can be easily reproduced by following the steps below on Kubernetes v1.24.17.
1. Create Pod A, mount PVC A and schedule it to node A.
2. Inject a fault into the CSI Controller to ensure that ControllerUnpublishVolume fails to execute.
3. Delete Pod A.
4. After waiting for Pod A to be deleted, delete the Kube-controller-manager leader container.
5. After waiting for Kube-controller-manager to restart, re-create Pod A, mount PVC A, and ensure scheduling to node A.
6. Then recover from the CSI Controller failure.

After waiting for the CSI Controller to execute `ControllerUnpublishVolume`, you can see that Pod A has the following events
```
  Warning FailedMount 8m18s (x7 over 8m49s) kubelet MountVolume.WaitForAttach failed for volume "pvc-d56d31ab-0a1c-4121-a972-9be268f89113" : volume attachment is being deleted
  Warning FailedMount 4m36s kubelet Unable to attach or mount volumes: unmounted volumes=[elf-example-1], unattached volumes=[kube-api-access-mrxcm elf-example-1]: timed out waiting for the condition
  Warning FailedMount 35s (x5 over 7m45s) kubelet MountVolume.WaitForAttach failed for volume "pvc-d56d31ab-0a1c-4121-a972-9be268f89113" : volume 9ed89f7f-efae-43d8-a789-661eccd37c00 has GET error for volume attachment csi -697fd0d911f78408885569ab88711bcda9bf6e7e708b215429b26e778501a051: volumeattachments .storage.k8s.io "csi-697fd0d911f78408885569ab88711bcda9bf6e7e708b215429b26e778501a051" is forbidden: User "system:node:elf-csi-daily-e2e-workergroup1-tpw4j" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'elf-csi-daily-e2e-workergroup1-tpw4j' and this object
```
The Kube-controller-manager leader container always prints the following logs.
```
2024-03-19T11:09:57.044508482+08:00 stderr F E0319 11:09:57.044097       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:10:57.129484864+08:00 stderr F E0319 11:10:57.128950       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:11:57.150407199+08:00 stderr F E0319 11:11:57.150087       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:12:57.155069971+08:00 stderr F E0319 11:12:57.154598       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:13:57.179597205+08:00 stderr F E0319 11:13:57.179250       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:14:57.185338717+08:00 stderr F E0319 11:14:57.184827       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:15:57.199191175+08:00 stderr F E0319 11:15:57.198933       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
2024-03-19T11:16:57.215221504+08:00 stderr F E0319 11:16:57.214867       1 operation_executor.go:827] VerifyVolumesAreAttached: nil spec for volume kubernetes.io/csi/com.smartx.elf-csi-driver^9ed89f7f-efae-43d8-a789-661eccd37c00
```
And the VolumeAttachment corresponding to the PVC A mounted to the node A will never be created.
