### ISSUE TITLE
PodSecurity - CLI tool for static analysis

### ISSUE THREAD

**Issue by Cajga** [kubernetes/kubernetes#108807]
It would be great if a cli tool could be built which is using the same logic/code then the admission controller which could be used for static analysis of manifests in CI pipelines to verify if they meet the requirements of the different Policy levels.
We are using GitOps for deployment so our pipeline cannot authenticate to the clusters. This prevents us to use `apply dry-run`.

**Comment by sftim** [comment]
Part of the answer here could be a blog article about PodSecurity. The article could include a survey of ways to check your manifests without access to the target cluster.

@Cajga perhaps you'd be interested in writing that up?

**Comment by enj** [comment]
https://github.com/stlaz/psachecker looks like it may help in this case.  @stlaz @s-urbaniak may be interested in turning it into an official SIG Auth repo in kubernetes-sigs.

https://github.com/samos123/pspmigrator is a related tool that will be moved to kubernetes-sigs soon.

**Comment by stlaz** [comment]
Hello and sorry for such a delay, I was vacationing a bit.

I would gladly turn my psachecker into a SIG Auth repository. I believe the project already does what the ask in this issue is, albeit I assume it might need some polishing.

@ritazh what would be a good first step towards such an action?

**Comment by stlaz** [comment]
/remove-lifecycle stale
I need to finish a few other things and I can start on this
