### ISSUE TITLE
Consider archiving `k8s.io/csi-api` repository

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#108827]
### What would you like to be added?

I see that the  [`k8s.io/csi-api`](https://git.k8s.io/csi-api) repository does no longer have a staging pkg.
It looks like the staging pkg existed from K8s 1.9 to 1.14 (according to the repo tags).
I would suggest sig-storage to consider archiving this repo if it is no longer used and not supposed to be used. Of course, we should also consider eventual usage of this repo currently (existing dependency in go.mod of third-party project) and we have to handle this properly making sure we don't break the build of any existing project.

### Why is this needed?

For cleanup purposes.

**Comment by MadhavJivrajani** [comment]
/area code-organization
(sorry, autocorrect)

**Comment by MadhavJivrajani** [comment]
/remove-kind deprecation
since not deprecation of a feature :)
