### ISSUE TITLE
externalIPs externalIPs cannot be used

### ISSUE THREAD

**Issue by lhj502819** [kubernetes/kubernetes#108830]
### What happened?

When I configure the Service to use externalIPs, the machine where the specified externalIP is located cannot communicate with other nodes.

### What did you expect to happen?

How do I allow external access to the service？

### How can we reproduce it (as minimally and precisely as possible)?

 configure the Service to use externalIPs，the machine where the specified externalIP is located cannot communicate with other nodes，communication resumes when the service is stopped。

### Anything else we need to know?

This is the first time I use this version, I don't know if the configuration is wrong. If the official personnel have encountered this problem, please answer，ty！

### Kubernetes version

<details>

```console
$ kubectl version
# 1.20.2
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux 0027.novalocal 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


```

</details>

### Install tools

<details>
[kubeasz](https://github.com/easzlab/kubeasz)
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> When I configure the Service to use externalIPs, the machine where the specified externalIP is located cannot communicate with other nodes.

that depend on the implementation, so you should open the issue in the CNI plugin project
/close
