### ISSUE TITLE
PodSecurityAdmission - Custom Standards

### ISSUE THREAD

**Issue by mitchellmaler** [kubernetes/kubernetes#108808]
We would like to adopt the restricted standard but we require to make a few customizations to that. It would be great if there was a custom resource where custom standards or inherited and then customized standards could be made.

**Comment by liggitt** [comment]
What you're describing is effectively the PodSecurityPolicy API, which proved so difficult to evolve over time that it never had a clear path to graduate from beta to GA.

Experience with that API convinced us that a coarse-grained policy was the correct approach to build into Kubernetes, and to delegate custom policies to external policy systems via admission webhooks.

/close
