### ISSUE TITLE
Cleanup: kube-proxy internal naming

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#108806]
We have sort of a mish-mash of "service" and "servicePort" and similar.

We should think about changing ALL of the places that actually relate to a service-port (a specific port of a service, not the whole service) and rename them to some new term that means "service port". E.g. "svcpt" or "spt" or "sport".

See https://github.com/kubernetes/kubernetes/pull/106497/commits/8fffae321d66487f776922e0c313b33af7bf27e3 in pkg/proxy/iptables/proxier.go and friends.  e.g. `info.serviceNameString` -> `info.svcptNameString` ?

**Comment by gkarthiks** [comment]
I would like to take this one.

**Comment by thockin** [comment]
You might want to wait until #106497 lands - it will be a nasty rebase

**Comment by ak20102763** [comment]
Hello @gkarthiks, raised this Pr just to get started 😊 .

**Comment by daman1807** [comment]
Is the issue still open ?

**Comment by kidddddddddddddddddddddd** [comment]
Is anyone working on this now?
