### ISSUE TITLE
Listen-only UDP services drop all but first incoming datagram from a given source

### ISSUE THREAD

**Issue by fhp-kkuphal** [kubernetes/kubernetes#108876]
### What happened?

IPTABLES default FORWARD is set to DENY.  Showing relevant iptables rules with counters

```    
    0     0 KUBE-MARK-MASQ  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    0     0 KUBE-SVC-E2UYNOD5QBZKWUAZ  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    0     0 KUBE-MARK-DROP  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    0     0 KUBE-MARK-MASQ  udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp dpt:32040
    0     0 KUBE-SVC-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp dpt:32040
    0     0 KUBE-MARK-MASQ  all  --  any    any     100.127.184.221      anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */
    0     0 DNAT       udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp to:100.127.184.221:50514
    0     0 KUBE-MARK-MASQ  udp  --  any    any    !100.96.0.0/11        100.66.152.181       /* default/reporter-sophos-syslog-udp:mysyslog cluster IP */ udp dpt:50514
    0     0 KUBE-SVC-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             100.66.152.181       /* default/reporter-sophos-syslog-udp:mysyslog cluster IP */ udp dpt:50514
    0     0 KUBE-FW-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             workload-cluster-control-plane-8khx2  /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */ udp dpt:50514
    0     0 KUBE-SEP-OQGMAH6AHVJOSXDY  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */
```

When created a UDP service, when the first datagram is not responded to (conntrack state is UNREPLIED)

```
udp      17 29 src=192.168.5.1 dst=192.168.4.163 sport=53287 dport=50514 [UNREPLIED] src=100.127.184.221 dst=192.168.5.200 sport=50514 dport=23578 mark=0 use=1
```

future packets will be dropped.  Here are the iptables rules after starting syslog stream.  Note only 1 packet is processed by the forwarding rules.

```    
    1  1151 KUBE-MARK-MASQ  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    1  1151 KUBE-SVC-E2UYNOD5QBZKWUAZ  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    0     0 KUBE-MARK-DROP  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */
    0     0 KUBE-MARK-MASQ  udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp dpt:32040
    0     0 KUBE-SVC-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp dpt:32040
    0     0 KUBE-MARK-MASQ  all  --  any    any     100.127.184.221      anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */
    1  1151 DNAT       udp  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */ udp to:100.127.184.221:50514
    0     0 KUBE-MARK-MASQ  udp  --  any    any    !100.96.0.0/11        100.66.152.181       /* default/reporter-sophos-syslog-udp:mysyslog cluster IP */ udp dpt:50514
    0     0 KUBE-SVC-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             100.66.152.181       /* default/reporter-sophos-syslog-udp:mysyslog cluster IP */ udp dpt:50514
    1  1151 KUBE-FW-E2UYNOD5QBZKWUAZ  udp  --  any    any     anywhere             workload-cluster-control-plane-8khx2  /* default/reporter-sophos-syslog-udp:mysyslog loadbalancer IP */ udp dpt:50514
    1  1151 KUBE-SEP-OQGMAH6AHVJOSXDY  all  --  any    any     anywhere             anywhere             /* default/reporter-sophos-syslog-udp:mysyslog */
```
and with the FORWARD DROP COUNT

```
Chain FORWARD (policy DROP 43669 packets, 52M bytes)
```

### What did you expect to happen?

Packets forwarded to the corresponding service and pod

### How can we reproduce it (as minimally and precisely as possible)?

Please see additional information here:

https://github.com/kubernetes/kubernetes/issues/72511
https://github.com/kubernetes/kubernetes/issues/92798

with corresponding Calico issues

https://github.com/projectcalico/calico/issues/2113
https://github.com/projectcalico/calico/issues/3748

which all have reproducible steps.

### Kubernetes version

v.1.21.2+vmware.1

### Cloud provider

Bare metal VMware Tanzu Community Edition

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Calico 3.22.1

**Comment by fhp-kkuphal** [comment]
> There were a considerable amount of fixes for UDP services in recent versions
> 
> https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+author%3Aaojea+is%3Amerged+conntrack+udp+
> 
> you should try with a more recent version of kube-proxy that contain those fixes

Thanks.  The newest release it appears I have access to on Tanzu Community Edition is v1.21.5.   A couple commits appear to have been done since that release, mostly related to stale UDP connections.  This is not that issue from what I can tell.  This is specifically related to the iptables rules not matching new, unreplied connections as can be seen in the related issues.  Previous troubleshooting appears to indicate that a FORWARD ALLOW rule of varying kinds can work as a workaround as well as using ipvs.  I'm looking, however, for a more permanent fix whether it be part of kube-proxy adding those rules or whether this is an issue specific to calico.

**Comment by fhp-kkuphal** [comment]
I should also note that for reproduction purposes, using netcat was not a good tool.  I was able to use netcat to send individual packets through the firewall rules specifically because the first packet of a connection is always received.  Using a syslog source will demonstrate that the subsequent packets do not arrive and (as shown in my iptables logs above) rejected because they do not have a matching connection as the original packet was never replied to.  Using netcat in a loop resulted in each single packet being received.

**Comment by uablrek** [comment]
I can confirm a _similar_ problem on K8s `v1.23.4`. On the node where the endpoint POD executes do;
```
iptables -P FORWARD DROP
```
on the node where the endpoint POD executes, the packets are DROP'ed and not forwarded to the pod, communication is dead. Same for tcp and udp with proxy-mode ipvs or iptables.

I am not sure if this is a bug or a "don't do that" problem.

BTW, what you set as policy on the node where traffic enters doesn't matter since packets are hijacked before the FORWARD chain.

**Comment by aojea** [comment]
these are my forward rules
```
-A FORWARD -m comment --comment "kubernetes forwarding rules" -j KUBE-FORWARD                                                                                                                                                                            
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes service portals" -j KUBE-SERVICES                                                                                                                                                 
-A FORWARD -m conntrack --ctstate NEW -m comment --comment "kubernetes externally-visible service portals" -j KUBE-EXTERNAL-SERVICES                                                                                                                     
-A KUBE-FORWARD -m conntrack --ctstate INVALID -j DROP                                                                                                                                                                                                   
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding rules" -m mark --mark 0x4000/0x4000 -j ACCEPT                                                                                                                                                
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod source rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT                                                                                                              
-A KUBE-FORWARD -m comment --comment "kubernetes forwarding conntrack pod destination rule" -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT    
```

IIRC, if you have a conntrack entry like this, that will not match the `-m conntrack --ctstate RELATED,ESTABLISHED` and will fall down to the default
```
udp      17 29 src=192.168.5.1 dst=192.168.4.163 sport=53287 dport=50514 [UNREPLIED] src=100.127.184.221 dst=192.168.5.200 sport=50514 dport=23578 mark=0 use=1
```

if that is true, the conntrack related fixes I pasted will solve your problem
https://github.com/kubernetes/kubernetes/issues/108876#issuecomment-1075291844

**Comment by aojea** [comment]
ahh , wait, so , you say that this service is one direction only?

**Comment by uablrek** [comment]
@aojea Did you set `iptables -P FORWARD DROP`?

**Comment by aojea** [comment]
I think that I know the problem, since the traffic is one direction only, the conntrack entry never will move to ESTABLISHED

```
udp      17 29 src=192.168.5.1 dst=192.168.4.163 sport=53287 dport=50514 [UNREPLIED] src=100.127.184.221 dst=192.168.5.200 sport=50514 dport=23578 mark=0 use=1
```

so it depends on the default policy

**Comment by fhp-kkuphal** [comment]
> ahh , wait, so , you say that this service is one direction only?

Correct.  In this case it is syslog (UDP).  I can also confirm the information from the other linked issues that this is not a problem with kube-proxy in IPVS mode.

**Comment by jallirs** [comment]
I have the same issue on 1.21.2, I think my application is missing the first packet. In my case also listen-only udp. Interestingly enough, issue occurs more when I delete a pod or reboot a vm while doing load testing. Tried with 1.21.9, same problem.

**Comment by uablrek** [comment]
> I think my application is missing the first packet.

It doesn't seem to be the same problem. In this issue the user is missing all packets _except_ the first.

**Comment by aojea** [comment]
maybe we have to add something to deal with one-way services, I think that the rule will look like

```
-A FORWARD -m conntrack ! --ctstatus SEEN_REPLY --protocol udp -m comment --comment "kubernetes UDP one-way service portals" -j KUBE-SERVICES                                                                                                                                                 
```

I'm going to be busy for a time, can anybody test that?

**Comment by danwinship** [comment]
> what I was suggesting is one additional rule to match this conntrack state

or possibly the `-m conntrack --ctstate NEW` should be `-m conntrack ! --ctstate ESTABLISHED`. Not sure which is better...

**Comment by aojea** [comment]
my apologies, and thanks to Lars, Tim, Dan and the sig-network people that clarified my mistake, I was confused with the nat and filter tables, and I don't know how many times I have checked this diagram :upside_down_face: 

![image](https://user-images.githubusercontent.com/6450081/161154436-6b8883c8-1229-414f-9068-ed646f3e63d8.png)

So, if you set your default FORWARD policy to DROP, you should add rules to allow the traffic you want, because it will block traffic from pods to other nodes per example, as @uablrek already reported https://github.com/kubernetes/kubernetes/issues/108876#issuecomment-1078797339

It seems that the conclusion is that Kubernetes clusters requires that the default FORWARD policy is ACCEPT and, if the administrator desires to change the default policy to DROP, it has to create the corresponding rules to allow the desired traffic, that I can assume it will be traffic from/to pods and from/to services at least

I'm going to close as working as expected
/close
