### ISSUE TITLE
Windows GMSA Full e2e test uses bash to install the plugin

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#108816]
### What happened?

Cluster api provides a framework to run the e2e tests which uses the conformance image:

https://github.com/kubernetes-sigs/cluster-api/blob/692497dbb340beecc04171ccd73f370f173da3a9/test/framework/kubetest/run.go#L43-L44

The gmsa tests use bash to install the webhook:

https://github.com/kubernetes/kubernetes/blob/4d08582d1fa21e1f5887e73380001ac827371553/test/e2e/windows/gmsa_full.go#L339-L344

The test will fail when run in the conformance image because of the bash:

```
• Failure [9.850 seconds]                                                                                         
[sig-windows] [Feature:Windows] GMSA Full [Serial] [Slow]                                                         
test/e2e/windows/framework.go:27                                                                                  
  GMSA support                                                                                                    
  test/e2e/windows/gmsa_full.go:96                                                                                
    can read and write file to remote SMB folder [It]                                                             
    test/e2e/windows/gmsa_full.go:174                                                                             

    Mar 18 22:43:47.188: unable to deploy GMSA webhook, output:                                                   
    : exec: "bash": executable file not found in $PATH     
```

### What did you expect to happen?

we should install the component another way

### How can we reproduce it (as minimally and precisely as possible)?

run this e2e conformance image with `--ginkgo.focus="GMSA.Full"`

### Anything else we need to know?

/sig windows
fyi @iXinqi

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsturtevant** [comment]
Conformance image: https://github.com/kubernetes/kubernetes/tree/master/test/conformance

**Comment by iXinqi** [comment]
Hi @jsturtevant, does the "work e2e" test case pass?  Deploying GMSA webhook is the same for both "work e2e" and this test case.

**Comment by jsturtevant** [comment]
no, they both fail due to bash not being present in the conformance image.  The gmsa tests themselves pass if I run `e2e.test` locally
