### ISSUE TITLE
"the HPA was unable to compute the replica count: failed to get memory utilization: missing request for memory/cpu"

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [kubernetes/kubernetes#108920]
### What happened?

I created a deployment, a service and an HPA. I deployed the metrics server and the HPA is throwing errors about requests not defined on the deployment when clearly the resources are requested and limited.

The errors thrown are:

```
$ kubectl describe horizontalpodautoscaler.autoscaling/pwa -n pwa
Name:                                                     pwa
Namespace:                                                pwa
Labels:                                                   app=pwa
                                                          env=prod
Annotations:                                              <none>
CreationTimestamp:                                        Wed, 23 Mar 2022 12:29:16 +0000
Reference:                                                Deployment/pwa
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  <unknown> / 80%
  resource cpu on pods  (as a percentage of request):     <unknown> / 70%
Min replicas:                                             14
Max replicas:                                             24
Deployment pods:                                          16 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: failed to get memory utilization: missing request for memory
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedGetResourceMetric       17m (x8 over 19m)     horizontal-pod-autoscaler  failed to get cpu utilization: missing request for cpu
  Warning  FailedComputeMetricsReplicas  17m (x8 over 19m)     horizontal-pod-autoscaler  invalid metrics (2 invalid out of 2), first error is: failed to get memory utilization: missing request for memory
  Warning  FailedGetResourceMetric       4m32s (x61 over 19m)  horizontal-pod-autoscaler  failed to get memory utilization: missing request for memory
```

The deployment has the resources well defined:
<pre>
<details>
$ kubectl get deployment pwa -n pwa -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"..."}
  creationTimestamp: "2022-03-23T10:37:33Z"
  generation: 6
  labels:
    app: pwa
    env: prod
  name: pwa
  namespace: pwa
  resourceVersion: "452013"
  uid: c760a17a-2c3e-4b8b-bc49-7dd7190845f4
spec:
  progressDeadlineSeconds: 600
  replicas: 16
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pwa
      env: prod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pwa
        env: prod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Worker
                operator: In
                values:
                - GeneralPurpose
      containers:
      - env:
        - name: "foo"
          value: "bar"
        image: foo.bar/image:latest
        imagePullPolicy: Always
        name: pwa-web
        ports:
        - containerPort: 3000
          name: http-pwa
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 16
  conditions:
  - lastTransitionTime: "2022-03-23T10:37:33Z"
    lastUpdateTime: "2022-03-23T10:37:35Z"
    message: ReplicaSet "pwa-54f55fd8f8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime
</pre>
</details>

And if I fetch one pod, same resource definition as well:
<pre>
<details>
$ kubectl get pod/pwa-54f55fd8f8-rl88h -n pwa -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-03-23T10:37:33Z"
  generateName: pwa-54f55fd8f8-
  labels:
    app: pwa
    env: prod
    pod-template-hash: 54f55fd8f8
  name: pwa-54f55fd8f8-rl88h
  namespace: pwa
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pwa-54f55fd8f8
    uid: 15f7ad5e-99dc-4c79-a001-179934ed58e2
  resourceVersion: "447980"
  uid: 121849a3-57e6-4caf-888a-a90338ae461c
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: Worker
            operator: In
            values:
            - GeneralPurpose
  containers:
  - env:
    - name: "foo"
      value: "bar"
    image: foo.bar/image:latest
    imagePullPolicy: Always
    name: pwa-web
    ports:
    - containerPort: 3000
      name: http-pwa
      protocol: TCP
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: sa-secret-name
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node-name
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-mtz8t
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T10:37:33Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T10:37:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T10:37:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-03-23T10:37:33Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://hash
    image: foo.bar/image:latest
    imageID: docker-pullable://foo.bar/image@hash
    lastState: {}
    name: pwa-web
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-03-23T10:37:35Z"
  hostIP: 10.0.4.82
  phase: Running
  podIP: 10.0.4.144
  podIPs:
  - ip: 10.0.4.144
  qosClass: Burstable
  startTime: "2022-03-23T10:37:33Z"
</pre>
</details>

I made no changes to any security groups or any communication between resources, but in HTTPS (443 port) the trafic is allowed to flow between every instance and the control plane on EKS without restriction.

### What did you expect to happen?

I expected the HPA to fetch the current usage from the metrics api and scale my deployments up and down accordingly.

The HPA can see the number of current replicas but can't fetch resource usage.

### How can we reproduce it (as minimally and precisely as possible)?

Apply the deployments below on a brand new EKS cluster. Deploy the latest metrics-server version.

### Anything else we need to know?

`deployment.yaml`:
<pre>
<details>
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pwa
    env: prod
  name: pwa
  namespace: pwa
spec:
  replicas: 16
  selector:
    matchLabels:
      app: pwa
      env: prod
  template:
    metadata:
      labels:
        app: pwa
        env: prod
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: Worker
                    operator: In
                    values:
                      - GeneralPurpose
      containers:
        - env:
            - "..."
          image: foo.bar/image:latest
          name: pwa-web
          ports:
            - containerPort: 3000
              name: http-pwa
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
</pre>
</details>

`service.yaml`:
<pre>
<details>
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pwa
    env: prod
  name: pwa
  namespace: pwa
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http-pwa
  selector:
    app: pwa
    env: prod
  type: NodePort
</pre>
</details>

`hpa.yaml`:
<pre>
<details>
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: pwa
    env: prod
  name: pwa
  namespace: pwa
spec:
  maxReplicas: 24
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 70
          type: Utilization
      type: Resource
  minReplicas: 16
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pwa
</pre>
</details>

[Metrics Server](https://docs.aws.amazon.com/eks/latest/userguide/metrics-server.html) on EKS:
```
$ kubectl get deployment metrics-server -n kube-system
NAME             READY   UP-TO-DATE   AVAILABLE   AGE
metrics-server   1/1     1            1           13h
```

Metrics API (`kubectl  get --raw "/apis/metrics.k8s.io/v1beta1/pods" | jq`):
<pre>
<details>
{
  "kind": "PodMetricsList",
  "apiVersion": "metrics.k8s.io/v1beta1",
  "metadata": {},
  "items": [
    {
      "metadata": {
        "name": "aws-load-balancer-controller-64f7f7b546-4rshf",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app.kubernetes.io/instance": "aws-load-balancer-controller",
          "app.kubernetes.io/name": "aws-load-balancer-controller",
          "pod-template-hash": "64f7f7b546"
        }
      },
      "timestamp": "2022-03-23T12:57:10Z",
      "window": "17.108s",
      "containers": [
        {
          "name": "aws-load-balancer-controller",
          "usage": {
            "cpu": "286479n",
            "memory": "31704Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "aws-load-balancer-controller-64f7f7b546-9qwj7",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app.kubernetes.io/instance": "aws-load-balancer-controller",
          "app.kubernetes.io/name": "aws-load-balancer-controller",
          "pod-template-hash": "64f7f7b546"
        }
      },
      "timestamp": "2022-03-23T12:57:13Z",
      "window": "11.939s",
      "containers": [
        {
          "name": "aws-load-balancer-controller",
          "usage": {
            "cpu": "1003660n",
            "memory": "35364Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "aws-node-bnrcl",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "76b5bd9c54",
          "k8s-app": "aws-node",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:19Z",
      "window": "10.364s",
      "containers": [
        {
          "name": "aws-node",
          "usage": {
            "cpu": "3689416n",
            "memory": "46668Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "aws-node-hlcpx",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "76b5bd9c54",
          "k8s-app": "aws-node",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:22Z",
      "window": "15.071s",
      "containers": [
        {
          "name": "aws-node",
          "usage": {
            "cpu": "4146068n",
            "memory": "44748Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "aws-node-kmbvw",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "76b5bd9c54",
          "k8s-app": "aws-node",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:26Z",
      "window": "15.811s",
      "containers": [
        {
          "name": "aws-node",
          "usage": {
            "cpu": "3310078n",
            "memory": "47332Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "cluster-autoscaler-5bb7f75f4d-6hrs8",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "cluster-autoscaler",
          "pod-template-hash": "5bb7f75f4d"
        }
      },
      "timestamp": "2022-03-23T12:57:11Z",
      "window": "13.9s",
      "containers": [
        {
          "name": "cluster-autoscaler",
          "usage": {
            "cpu": "2433628n",
            "memory": "45728Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "coredns-7cc879f8db-n5pcj",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "eks.amazonaws.com/component": "coredns",
          "k8s-app": "kube-dns",
          "pod-template-hash": "7cc879f8db"
        }
      },
      "timestamp": "2022-03-23T12:57:13Z",
      "window": "13.534s",
      "containers": [
        {
          "name": "coredns",
          "usage": {
            "cpu": "1149u",
            "memory": "9764Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "coredns-7cc879f8db-nk82m",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "eks.amazonaws.com/component": "coredns",
          "k8s-app": "kube-dns",
          "pod-template-hash": "7cc879f8db"
        }
      },
      "timestamp": "2022-03-23T12:57:16Z",
      "window": "12.97s",
      "containers": [
        {
          "name": "coredns",
          "usage": {
            "cpu": "1188077n",
            "memory": "11916Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "kube-proxy-5n7sx",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "798c9f7b47",
          "k8s-app": "kube-proxy",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:11Z",
      "window": "19.661s",
      "containers": [
        {
          "name": "kube-proxy",
          "usage": {
            "cpu": "185134n",
            "memory": "20532Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "kube-proxy-ktxv8",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "798c9f7b47",
          "k8s-app": "kube-proxy",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:08Z",
      "window": "13.645s",
      "containers": [
        {
          "name": "kube-proxy",
          "usage": {
            "cpu": "283235n",
            "memory": "21288Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "kube-proxy-wkv4f",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "controller-revision-hash": "798c9f7b47",
          "k8s-app": "kube-proxy",
          "pod-template-generation": "1"
        }
      },
      "timestamp": "2022-03-23T12:57:21Z",
      "window": "10.307s",
      "containers": [
        {
          "name": "kube-proxy",
          "usage": {
            "cpu": "788092n",
            "memory": "16844Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "metrics-server-64cf6869bd-rrk2p",
        "namespace": "kube-system",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "k8s-app": "metrics-server",
          "pod-template-hash": "64cf6869bd"
        }
      },
      "timestamp": "2022-03-23T12:57:25Z",
      "window": "30.025s",
      "containers": [
        {
          "name": "metrics-server",
          "usage": {
            "cpu": "2035026n",
            "memory": "18476Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-2b9ff",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:11Z",
      "window": "12.216s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "22346150n",
            "memory": "246056Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-56nsg",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:17Z",
      "window": "12.628s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "8064219n",
            "memory": "250792Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-5lrzp",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:18Z",
      "window": "14.075s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "37301942n",
            "memory": "255304Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-5t8gg",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:15Z",
      "window": "17.757s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "3366942n",
            "memory": "245412Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-7zjdh",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:13Z",
      "window": "11.98s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "8232886n",
            "memory": "221244Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-9ll5r",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:26Z",
      "window": "23.584s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "17754462n",
            "memory": "247168Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-bpsgx",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:20Z",
      "window": "11.134s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "2747600n",
            "memory": "242080Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-d88tq",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:13Z",
      "window": "17.578s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "5373538n",
            "memory": "222776Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-fqp4v",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:18Z",
      "window": "19.234s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "8476661n",
            "memory": "237696Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-gn25g",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:08Z",
      "window": "18.387s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "5220207n",
            "memory": "224496Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-rl88h",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:16Z",
      "window": "18.92s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "19680741n",
            "memory": "248764Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-rpmbl",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:13Z",
      "window": "14.158s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "4317496n",
            "memory": "256668Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-v6vcg",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:20Z",
      "window": "13.329s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "3028407n",
            "memory": "201708Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-w7rqf",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:19Z",
      "window": "18.039s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "4364599n",
            "memory": "258156Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-z62f4",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:19Z",
      "window": "16.958s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "3742767n",
            "memory": "228312Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "pwa-54f55fd8f8-zzfvc",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "env": "prod",
          "pod-template-hash": "54f55fd8f8"
        }
      },
      "timestamp": "2022-03-23T12:57:24Z",
      "window": "24.901s",
      "containers": [
        {
          "name": "pwa-web",
          "usage": {
            "cpu": "4053531n",
            "memory": "273856Ki"
          }
        }
      ]
    },
    {
      "metadata": {
        "name": "redis-0",
        "namespace": "pwa",
        "creationTimestamp": "2022-03-23T12:57:28Z",
        "labels": {
          "app": "pwa",
          "controller-revision-hash": "redis-6f9ccb667d",
          "env": "prod",
          "statefulset.kubernetes.io/pod-name": "redis-0"
        }
      },
      "timestamp": "2022-03-23T12:57:17Z",
      "window": "17.49s",
      "containers": [
        {
          "name": "redis",
          "usage": {
            "cpu": "629887n",
            "memory": "16580Ki"
          }
        }
      ]
    }
  ]
}
</pre>
</details>

### Kubernetes version

<pre>
<details>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T01:02:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.5-eks-bc4871b", GitCommit:"5236faf39f1b7a7dabea8df12726f25608131aa9", GitTreeState:"clean", BuildDate:"2021-10-29T23:32:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes version running on AWS nodes: `v1.21.5-eks-9017834`
</pre>
</details>

### Cloud provider

AWS EKS, created via CDK with 2 Worker Autoscaling Groups.

### Install tools

EKS cluster provisioned via the latest AWS CDK (v2). No special configurations applied.

### Container runtime (CRI) and version (if applicable)

Default for EKS: Docker.

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<pre>
<details>
CoreDNS:  602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/coredns:v1.8.4-eksbuild.1
Metrics Server: k8s.gcr.io/metrics-server/metrics-server:v0.6.1
Kube Proxy: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/eks/kube-proxy:v1.21.2-eksbuild.2
AWS Node: 602401143452.dkr.ecr.eu-west-1.amazonaws.com/amazon-k8s-cni:v1.10.1-eksbuild.1
</pre>
</details>

**Comment by yangjunmyfm192085** [comment]
From the discussion of  [#989](https://github.com/kubernetes-sigs/metrics-server/issues/989), we analyze the problem that should not be part of the metrics-server and need to be analyzed from hpa

**Comment by RafaelMoreira1180778** [comment]
@yangjunmyfm192085 from my debugging steps today I managed to isolate the problem to being a namespace problem.

I deployed this sample basic manifest in the `default` namespace:
```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: Worker
                    operator: In
                    values:
                      - GeneralPurpose
      containers:
        - env:
            - name: foo
              value: bar
            - name: goo
              value: dar
          image: nginx:alpine
          name: nginx
          resources:
            limits:
              cpu: 400m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 128Mi
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: test
  name: web-hpa
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: memory
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
```

And this is what I got:
```console
$ kubectl describe horizontalpodautoscaler.autoscaling/web-hpa
Name:                                                     web-hpa
Namespace:                                                default
Labels:                                                   app=test
Annotations:                                              <none>
CreationTimestamp:                                        Thu, 24 Mar 2022 13:10:16 +0000
Reference:                                                Deployment/web
Metrics:                                                  ( current / target )
  resource memory on pods  (as a percentage of request):  8% (11591680) / 50%
  resource cpu on pods  (as a percentage of request):     0% (0) / 50%
Min replicas:                                             1
Max replicas:                                             5
Deployment pods:                                          1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
Events:
  Type     Reason                   Age   From                       Message
  ----     ------                   ----  ----                       -------
  Warning  FailedGetResourceMetric  26m   horizontal-pod-autoscaler  failed to get cpu utilization: did not receive metrics for any ready pods
  Normal   SuccessfulRescale        6m8s  horizontal-pod-autoscaler  New size: 4; reason: cpu resource utilization (percentage of request) above target
  Normal   SuccessfulRescale        52s   horizontal-pod-autoscaler  New size: 1; reason: All metrics below target
```

I do now know why in a different namespace it throws errors of fetching the resources. I start to wonder if it is an RBAC issue of some sort. But again it's strange because the HPA on a different namespace fetches the current replicas of the deployment, it just does not fetch the current cpu and memory values.

**Comment by yangjunmyfm192085** [comment]
Based on your analysis, it is indeed a bit strange. But I don't know much about hpa, I don't know hpa has a problem with rbac, Maybe should we ask hpa about this?

**Comment by RafaelMoreira1180778** [comment]
@yangjunmyfm192085 how may I get help from them directly?

**Comment by RafaelMoreira1180778** [comment]
@yangjunmyfm192085 I managed to solve the problem.

For anyone wondering what was happening:
- I created a deployment and a service for that deployment, I applied these labels:
```
app: pwa
env: prod
```
- Then I created a statefulset and a service for that statefulset, and since I use CDK8s I, by mistake, reused the same labels, so what happened was that the pwa deploymen was picking up the pod of the statefulset as it's own.
- The HPA was then pointing to that deployment so, In fact, there was a pod in the targed without requests of limits

I wish two things:
1. The HPA could tell me what pods did not have requests and limits.
2. The target ref of the HPA could avoid using labels (I guess they use selectors so they need the labels) since these mistakes can happen. This second point might be my noob experience talking.

**Comment by yangjunmyfm192085** [comment]
Thank you for sharing your experience in analyzing this issue.
This should help others. 
As for the hpa, I'm not very familiar with it, sorry.

**Comment by sarasensible** [comment]
Just want to share my solution to the same issue - in our case we inject opentelemetry containers which do not have resource requests or limits - an issue they are working on - https://github.com/open-telemetry/opentelemetry-operator/issues/1407.

Using these annotations:
```
annotations:
        instrumentation.opentelemetry.io/inject-python: weather-sensible-risk-telemetry-instrumentation
        sidecar.opentelemetry.io/inject: weather-sensible-risk-telemetry-collector
```

  These containers don't show up on the deployment, only on the pod, so you have to be looking there to notice that they have no resource requests/limits.  

My workaround for now is to set a default resource request/limit in the namespace so that the opentelemetry containers will have something set.

```
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: weather
spec:
  limits:
  - default:
      memory: 512Mi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    type: Container
```
