### ISSUE TITLE
configure pluginMetricsSamplePercent or CycleState.recordPluginMetrics from outside of scheduler

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#108903]
### What would you like to be added?

We have `pluginMetricsSamplePercent` which indicates the percentage of plugin metrics to be sampled. But it's `const` and we cannot change the value from outside.
https://github.com/kubernetes/kubernetes/blob/95e30f66c300c76ce21c0ca0e8bc4bf4a45e028f/pkg/scheduler/scheduler.go#L65

It would be nice if there was a way for this to be set up externally.
There are several possible ways to achieve this:
- add `pluginMetricsSamplePercent` to KubeSchedulerConfiguration.
  -  we need to implement new [`Option`](https://github.com/kubernetes/kubernetes/blob/95e30f66c300c76ce21c0ca0e8bc4bf4a45e028f/pkg/scheduler/scheduler.go#L143) to set `pluginMetricsSamplePercent` as well.
- create new [`Option`](https://github.com/kubernetes/kubernetes/blob/95e30f66c300c76ce21c0ca0e8bc4bf4a45e028f/pkg/scheduler/scheduler.go#L143) to pass a function to set `CycleState.recordPluginMetrics` in each scheduling cycle.
  - default should be `rand.Intn(100) < pluginMetricsSamplePercent` not to break the current behavior.
- Add function to set `CycleState.recordPluginMetrics` in each scheduling cycle to `Scheduler` field like `NextPod` or `Error`.
- just change `pluginMetricsSamplePercent` to `var` and expose it to be able to be changed value from other package.
- (... do you have other good way?)

/kind feature
/sig scheduling

### Why is this needed?

In sigs/kube-scheduler-simulator, we want to set `pluginMetricsSamplePercent` 100 to see the metrics of all scheduling.
https://github.com/kubernetes-sigs/kube-scheduler-simulator/issues/60

Also, users may want to increase this value for some detailed/accurate performance measurement or may want to set to 0 when not using metrics at all.

**Comment by matthewygf** [comment]
Per discussion on sig-scheduling [slack thread](https://kubernetes.slack.com/archives/C09TP78DV/p1647967672841409),  the motivation for this feature is to correlate and identify the root cause of high latency spike in scheduling latency. The potential outcome of this feature can allow users to deduce suitable combination of configuration, i.e. percentageOfNodes + list of plugins.

For example, consider the two figures below, 
![plugin_duration](https://user-images.githubusercontent.com/8476763/159804194-2dbf7406-1cb9-4693-b0ee-3b4b5d6c90b2.PNG)
![framework_schedule_duration](https://user-images.githubusercontent.com/8476763/159804198-92efac5c-7ab2-4c84-8238-7ebef9a492ae.PNG)

where **framework schedule duration** figure depicts the scheduling latency (1m bucket) of a single attempt, and it captures a spike. However, the **plugin duration** figure does not capture the relevant spike. This is probably due to the sampling rate being 10%.

**Comment by matthewygf** [comment]
ping ~ are we okay to work on this ?

**Comment by sanposhiho** [comment]
I think we need to discuss the way to achieve this. We have multiple option for implementation.

@Huang-Wei Could you please take a look at this? Which way do you think is better?

**Comment by Huang-Wei** [comment]
This requirement of "correlating scheduling latency spikes with metrics" is valid to me. It's just I'm wondering if `pluginMetricsSamplePercent` is the most efficient way to understand the correlation? Can other existing metrics help? Or, enable profiling?

/remove-lifecycle stale

**Comment by matthewygf** [comment]
> This requirement of "correlating scheduling latency spikes with metrics" is valid to me. It's just I'm wondering if `pluginMetricsSamplePercent` is the most efficient way to understand the correlation? Can other existing metrics help? Or, enable profiling?
> 
> /remove-lifecycle stale

At the moment, apart from "PluginExecutionDuration",  the metrics "SchedulingAlgorithmLatency" and "schedulingLatency" reports back the total latency for a scheduling decision. However, both schedulingAlgorithm and schedulinglatency do not give clear pictures for the **plugins** related latency. They do, however, provide whether it was the binding step or the algorithm that causes higher latency.

"FrameworkExtensionPointDuration" does tell the extension point total latency, but it may not be granular enough to tell whether a particular plugin causes the latency spike. 

I am not too familiar with the [enable profiling](https://github.com/kubernetes/kubernetes/blob/985c9202ccd250a5fe22c01faf0d8f83d804b9f3/cmd/kube-scheduler/app/server.go#L275) flag, it seems that enabling it can help for pprof but I am not sure if users would want to enable this in prod setting. 

Overall, I still advocate that allowing users to configure pluginMetricsSamplePercent seems to be the most efficient way. This is especially the case in prod settings, where users have their own custom plugin that call external software to make scheduling decision.

**Comment by Huang-Wei** [comment]
@matthewygf I will bring it to the next sig meeting. You're welcome to join, it's this [Thursday](https://docs.google.com/document/d/13mwye7nvrmV11q9_Eg77z-1w3X7Q1GTbslpml4J7F3A/edit#) 10:00 AM PST.

**Comment by sanposhiho** [comment]
@matthewygf do you want to work on it? If so, please `/assign` it.
I don't mean to force you to work on here, I can follow it if you want to leave it. I just think it's a good first issue for you to get involved in the kubernetes :)

**Comment by matthewygf** [comment]
@sanposhiho Thanks for pinging me ! Sure I will get myself to work on it. I have been busy and forgotten about this, nevertheless still an important feature for me and the community I think.

/assign

**Comment by matthewygf** [comment]
@sanposhiho @Huang-Wei Sorry for the delay, I have started working on this issue and created a [branch ](https://github.com/matthewygf/kubernetes/tree/plugin_sampling) locally. I have taken the direction to add ```add pluginMetricsSamplePercent to KubeSchedulerConfiguration```, however there are a couple of things I am unsure of.  

1. If I add the field in [KubeSchedulerConfiguration](https://github.com/matthewygf/kubernetes/blob/caafa4ba03995e7bc99f8618eb84e6bbcfebd67a/pkg/scheduler/apis/config/types.go#L93), in the conversion to v1beta3 and v1beta2, do I need to worry about the option being supported ? If so, am I introducing API changes?
2. Do you think we should add the ```pluginMetricsSamplePercent``` per schedulerProfile or only globally setting?

Thank you very much for the help in advance!
