### ISSUE TITLE
go1.18: Add metrics for SHA-1 certificates that will be rejected by go1.18

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#108940]
### What happened?

go1.18 dropped support for certificates signed with the SHA-1 hash function - https://tip.golang.org/doc/go1.18#sha1

While this does improve security, and publicly trusted Certificate Authorities no longer issue such certificates, it is possible that user-provided certificates issued by private Certificate Authorities and used in webhooks or aggregated API servers do still use this.

Similar to removal of support for certificates without subjectAltNames in go1.17, we need to:
- [x] add metrics when webhook/conversion/aggregated certificates with this hash are encountered - https://github.com/kubernetes/kubernetes/pull/109024
- [x] document use of `GODEBUG=x509sha1=1` and the metric from 1 as a mitigation for clusters which still need to identify and replace use of such certificates - added to release note and known issues
- [ ] add audit annotation when SHA-1 cert is encountered - https://github.com/kubernetes/kubernetes/pull/109107
- [ ] update docs at https://kubernetes.io/docs/reference/labels-annotations-taints/#annotations-used-for-audit and https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/

/sig api-machinery instrumentation docs
/priority important-soon
/milestone v1.24
/kind bug documentation

### What did you expect to happen?

Upgraded 1.23 clusters to continue working as-is

### How can we reproduce it (as minimally and precisely as possible)?

Configure an admission webhook, conversion webhook, or aggregated server with a serving certificate signed with the SHA-1 hash function. Upgrade to HEAD of 1.24. The certificate will no longer work by default

### Kubernetes version

1.24 HEAD (go1.18-based)

### Cloud provider

n/a

### OS version

n/a

**Comment by liggitt** [comment]
it looks like NewMissingSANRoundTripperWrapperConstructor already has all the plumbing, and instead of missing SANs we could check the SignatureAlgorithm and output a distinct metric

**Comment by liggitt** [comment]
/assign @stlaz
who offered to pick this up

**Comment by BenTheElder** [comment]
> Note that only [kubernetes members](https://github.com/orgs/kubernetes/people), repo collaborators and people who have commented on this issue/PR can be assigned. Additionally, issues/PRs can only have 10 assignees at the same time.

These restrictions are on the GitHub side, this message is posted when it receives a specific error from the GitHub API while attempting to assign 🙃 

https://github.com/kubernetes/test-infra/blob/363df425977893d80cfca70e4895c5e486011764/prow/plugins/assign/assign.go#L191-L192

It is an annoying GitHub limitation, and one that seemingly does not exist in the web client vs the API.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/109024 adds the metrics. the release note on that issue describes the go change, links to go docs, describes use of the `GODEBUG` option, the new metrics, and the kube-apiserver logs

@neolit123, what would you expect kubeadm to do with this?
1. leave GODEBUG off by default and let users override GODEBUG on their own (is this possible)?
2. set GODEBUG by default on all clusters?
3. set GODEBUG by default only on upgrade?

The risk of 1 is that a user upgrades without reading release notes and breaks a cluster that has SHA-1 certs in webhooks, etc

The risk of 2 is that we propagate accepting insecure certificates longer, even in new clusters that we know don't have any pre-existing bad certs

The risk of 3 is that it makes an upgraded 1.23 → 1.24 cluster and a new 1.24 cluster inconsistent

**Comment by liggitt** [comment]
> the majority of kubeadm users use kubeadm managed CA and certificates. there are less users that use external CA to sign their own certificates. sha1 attacks surfaced more than a decade before kubeadm's creation and Git hash collusion made the problem more known around 2017 was at a time when kubeadm did not support external CA. given these facts, an estimate on my side is that there are currently no kubeadm users that use sha1 certificates, but i would not exclude the possibility entirely.

that's helpful, thanks

> IMO, the PR needs an "action required" to appear on top of the release notes.

agreed. weird, I set `release-note-action-required`, but the label didn't get added. added the label manually.

**Comment by liggitt** [comment]
> if the same users log tickets for us, our response would be "please use GODEBUG and migrate ASAP".

and there's a way for them to set that envvar in kube-apiserver manifests when using kubeadm?

**Comment by BenTheElder** [comment]
> agreed. weird, I set release-note-action-required, but the label didn't get added. added the label manually.

There's been a lot of intermittent github webhook delivery issues in the past few weeks or so, slash commands are going to be somewhat unreliable :/

**Comment by neolit123** [comment]
> and there's a way for them to set that envvar in kube-apiserver manifests when using kubeadm?

they could use kubeadm patches to override the YAML manifest defaults - i.e. the contents of v1.Container -> Env:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#patches
