### ISSUE TITLE
If the apiserver service uses ipv6, it is impossible to communicate with the apiserver, and ip6tables has no generation rules

### ISSUE THREAD

**Issue by Roronoa-Z3r0** [kubernetes/kubernetes#108957]
### What happened?

After using the kubeadm init cluster, the apiserver service is ipv6 ip, the apiserver cannot be accessed, and the iptables rule is not generated

### What did you expect to happen?

IPV6 can be used to communicate with the apiserver。
![image](https://user-images.githubusercontent.com/45119426/159848305-e823928f-0ca3-4094-b28f-cf4cb656416e.png)
Here is the case of ipv4
![image](https://user-images.githubusercontent.com/45119426/159848474-d068f24b-3df2-472c-a676-6baedbffe5fc.png)

### How can we reproduce it (as minimally and precisely as possible)?

The dual-stack initializes k8s, and the service-cluster-ip-range puts the ipv6 ip in front。
![image](https://user-images.githubusercontent.com/45119426/159848259-d4026752-6521-43b1-8730-3afefb4d9e6a.png)

### Kubernetes version

![image](https://user-images.githubusercontent.com/45119426/159848525-d6eb6e82-2e3f-4977-b765-b1623623983a.png)

### Cloud provider

Private cloud

### OS version

![image](https://user-images.githubusercontent.com/45119426/159848650-00a66a87-0007-4876-a60d-279502891c07.png)

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
Please, don't use screenshots, use text and apply format.

The other matters when you configure your cluster, in this case it seems you have IPv6,IPv4, that means that the primary IP family is IPv6 and the apiserver will have that IP (currently apiserver is single-stack, it will be dual-stack in the future but is not implemented yet)

If you want to use a dual-stack cluster with apiserver service using IPv4, configure your service subnet as IPv4,IPv6

/remove-kind bug
/kind support
