### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [kubernetes/kubernetes#108932]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by neolit123** [comment]
@id-dan these are difficult times and i'm sure a lot of people would like to support Ukraine!

our issue trackers are not the right place to bring attention to your efforts, but please use the following:
- comment in #kubernetes-users on k8s slack
- send an email to the k8s mailing list: dev@kubernetes.io
- post in the kubernetes sub-reddit on reddit.com

you can also ask for more options at the #sig-contribex slack channel.
it is owned by the group responsible for contributor experience:
https://github.com/kubernetes/community/tree/master/sig-contributor-experience

thanks
/close

**Comment by neolit123** [comment]
i might have misunderstood the request, so given your request was to add banners to this repository as well i will reopen the issue and ping contribex.

/reopen
@kubernetes/sig-contributor-experience

**Comment by mrbobbytables** [comment]
For banner, the right channel is steering. 👍 If you'd like to discuss, please reach out to steering-private@kubernetes.io

/remove-sig contributor-experience
/committee steering

/close
