### ISSUE TITLE
Heapter doesn't collect stats from master node

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#10891]
Today heapster is enabled by default for both GKE and GCE for monitoring, but it doesn't collect stats from master node. The reason is master node is never register itself to apiserver. I remembered either me or @vishh  filed the issue before. But back then, the decision is we are going to use collectd + GCM as the default solution for both GKE and GCE. But decision was changed later, then I filed #9028. 

Now I realized that we missed monitoring on master node for both GKE and GCE. cc/ @brendandburns @alex-mohr @roberthbailey @thockin @vishh @saad-ali

**Comment by dchen1107** [comment]
#10760

**Comment by alex-mohr** [comment]
@a-robinson has the most GKE context on monitoring.

**Comment by a-robinson** [comment]
We may just have to let GCE and GKE differ here, since heapster won't be able to reach the master's kubelet on GKE. It makes sense to re-add this for GCE, though.

**Comment by davidopp** [comment]
ref #14054

**Comment by cmluciano** [comment]
Is this issue still relevant?
