### ISSUE TITLE
go1.18: [Tracker] pull-kubernetes-verify failing

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#108916]
### Which jobs are failing?

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Which tests are failing?

```
ci-kubernetes-verify-master.Overall
verify.generated-stable-metrics [FIXED]
verify.golangci-lint
verify.govet [FIXED]
verify.structured-logging
```

### Since when has it been failing?

23rd March ~14:40 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

I am not fully sure yet but
https://github.com/kubernetes/kubernetes/pull/108870 could be a potential reason

### Anything else we need to know?

/priority critical-urgent

### Relevant SIG(s)

/sig testing
/sig instrumentation 
/cc @aojea @serathius @pohly

**Comment by MadhavJivrajani** [comment]
`govet` failure is 100% due to https://github.com/kubernetes/kubernetes/pull/108870 because of https://tip.golang.org/doc/go1.18#vet

**Comment by liggitt** [comment]
are we rolling back CI to 1.17 until we have the blockers resolved? otherwise we won't be able to fan out and merge fixes until all presubmit issues are fixed.

are there specific issues for the failures we can fan out to test owners to fix?

**Comment by MadhavJivrajani** [comment]
The CI failures should now be fixed (temporarily) on account of: https://github.com/kubernetes/kubernetes/pull/108901
Thanks Dims!

Not closing this out as we still need to tweak a few things to be fully back in business.

> are there specific issues for the failures we can fan out to test owners to fix?

Other than the usual flakes (already filed as issues by other folks), nothing specific on account of the Go 1.18 switch over @liggitt, will keep a watch to make sure, thanks!

**Comment by liggitt** [comment]
> Other than the usual flakes (already filed as issues by other folks), nothing specific on account of the Go 1.18 switch over @liggitt, will keep a watch to make sure, thanks!

I was more looking for the owners of the disabled verify checks to be fixing the issues with them; that's more what I meant

**Comment by MadhavJivrajani** [comment]
Ah
@pohly is on it :)

**Comment by MadhavJivrajani** [comment]
Slack thread: https://kubernetes.slack.com/archives/C09QZ4DQB/p1648037062792439

**Comment by pohly** [comment]
> @pohly is on it :)

Actually, I had already prepared [the PR to replace verify-structured-logging.sh](https://github.com/kubernetes/kubernetes/pull/108159) a while ago because the script also had other issues and would have been hard to extend to support also contextual logging checks. It's just a coincidence that the PR is now ready for merging. :grin:

**Comment by dims** [comment]
we are good now. with https://github.com/kubernetes/kubernetes/pull/108159 and https://github.com/kubernetes/kubernetes/pull/108902 we are back to the full set of verify tests.
