### ISSUE TITLE
[Failing test] Conformance-GCE-master-kubetest2, go get not supported

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#108989]
### Which jobs are failing?

* Conformance - GCE - master - kubetest2

### Which tests are failing?

* ci-kubernetes-gce-conformance-latest-kubetest2.Overall

### Since when has it been failing?

History goes back to 2022-03-23

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

### Reason for failure (if possible)

```bash
+ go get sigs.k8s.io/kubetest2@latest
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
+ EXIT_VALUE=1
```

### Anything else we need to know?

look like a simple replace of `go get` with `go install` is needed

### Relevant SIG(s)

not sure which sig is responsible here

/sig cloud-provider
/kind failing-test

**Comment by leonardpahlke** [comment]
ref: https://github.com/kubernetes/kubernetes/issues/108910

**Comment by liggitt** [comment]
go1.18 requires changing the invocation to go install.

**Comment by liggitt** [comment]
Doesn't the job config require update here: https://grep.app/search?q=go%20get%20sigs.k8s.io/kubetest2%40latest ?

**Comment by dims** [comment]
i'll file one now @liggitt

**Comment by dims** [comment]
this is green now https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master%20-%20kubetest2
