### ISSUE TITLE
Watch for dependencies that go AWOL or switch licenses

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#108942]
Problem:
We had an issue in external-dns repository where ( https://github.com/kubernetes-sigs/external-dns/issues/2653#issuecomment-1073115175 )
- The project switched licenses
- The project git repo vanished

Ask:
We need to monitor all kubernetes repos for (At least start with k/k)
  - the licenses of dependencies listed in go.mod are valid ( https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md )
  - ensure the project continues to use a license that is valid for us over time
  - ensure that the dependency is still active/available for us to use.

Idea:
- Use https://github.com/google/go-licenses#build-tags to scan (see the CSV option for example)
- Validate that the licenses in the CSV are in the allowed-third-party-license-policy.md above
- Run this periodically as a prow periodic job
- Start with k/k and then extend this to other repositories

Thanks,
Dims

**Comment by thockin** [comment]
This tool has worked well in other (smaller) repos.

**Comment by Priyankasaggu11929** [comment]
/assign

I'll work on this. Will go through the pointers from the issue description & get back. Thank you!

**Comment by thockin** [comment]
The git-sync repo branch uses it as part of the image build, if that helps
at all.

**Comment by RinkiyaKeDad** [comment]
@Priyankasaggu11929 I can also help with this! 

/assign

**Comment by dims** [comment]
Oh! this is done! see https://testgrid.k8s.io/sig-testing-misc#kubernetes-verify-go-licenses-periodical

thanks,
dims
