### ISSUE TITLE
rethink sorting order of scheduling failure reasons

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#108931]
### What would you like to be added?

Now the scheduler surfaces a pod's scheduling failure reasons by sorting the messages alphabetically:

```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  4s    default-scheduler  0/500 nodes are available: 1 node(s) had taint {node-001: }, that the pod didn't tolerate, 1 node(s) had taint {node-002: }, that the pod didn't tolerate, 1 node(s) had taint {node-003: }, that the pod didn't tolerate, 1 node(s) had taint {node-004: }, that the pod didn't tolerate, 1 node(s) had taint {node-005: }, that the pod didn't tolerate, 1 node(s) had taint {node-006: }, that the pod didn't tolerate, 1 node(s) had taint {node-007: }, that the pod didn't tolerate, 1 node(s) had taint {node-008: }, that the pod didn't tolerate, 1 node(s) had taint {node-009: }, that the pod didn't tolerate, 1 node(s) had taint {node-010: }, that the pod didn't tolerate, 1 node(s) had taint {node-011: }, that the pod didn't tolerate, 1 node(s) had taint {node-012: }, that the pod didn't tolerate, 1 node(s) had taint {node-013: }, that the pod didn't tolerate, 1 node(s) had taint {node-014: }, that the pod didn't tolerate, 1 node(s) had taint {node-015: }, that the pod didn't tolerate, 1 node(s) had taint {node-016: }, ...
```

However, on a large cluster or upon diverse failure reasons, due to the message truncation, sometimes you cannot spot the most common failure reasons, and thus hard to troubleshoot. For now, the only way is to dig into the scheduler log, which is not that friendly.

It'd be nice to sort the failure reason by the frequency of their occurrences, so the event becomes:

```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  4s    default-scheduler  0/500 nodes are available: 400 node(s) had taint {foo: }, that the pod didn't tolerate, 1 node(s) had taint {node-001: }, that the pod didn't tolerate, 1 node(s) had taint {node-002: }, that the pod didn't tolerate, 1 node(s) had taint {node-003: }, that the pod didn't tolerate, 1 node(s) had taint {node-004: }, that the pod didn't tolerate, 1 node(s) had taint {node-005: }, that the pod didn't tolerate, 1 node(s) had taint {node-006: }, that the pod didn't tolerate, 1 node(s) had taint {node-007: }, that the pod didn't tolerate, 1 node(s) had taint {node-008: }, that the pod didn't tolerate, 1 node(s) had taint {node-009: }, that the pod didn't tolerate, 1 node(s) had taint {node-010: }, that the pod didn't tolerate, 1 node(s) had taint {node-011: }, that the pod didn't tolerate, 1 node(s) had taint {node-012: }, that the pod didn't tolerate, 1 node(s) had taint {node-013: }, that the pod didn't tolerate, 1 node(s) had taint {node-014: }, that the pod didn't tolerate, 1 node(s) had taint {node-015: }, ...
```

### Why is this needed?

Facilitate the end-users to quickly spot the most critical scheduling failure, without requesting SRE to look into scheduler logs.

**Comment by alculquicondor** [comment]
Was the most repeated reason the one that would have helped diagnose?

I wonder if we need some custom ordering. Volumebinding should certainly rank high.

**Comment by ahg-g** [comment]
I think we need a better message structure, for example the message could be structured in tuples like this: 

{`pluginName`, `nodeCount`, `message`}

and we enforce length limits on the per-plugin message, not the whole message.

"{TaintsTolerations, 10, list of taints not tolerated}, {VolumeBinding, 5, ...}"

This is an just an example structure, feel free to suggest others, but I think this is overall a better direction to address this problem.

**Comment by ahg-g** [comment]
Also, we may want to have a each plugin produce a detailed and summary messages, the former we use for logging the latter for events.

**Comment by Huang-Wei** [comment]
With the shorter msgs, I'm afraid it can still reach the msg [limit](https://github.com/kubernetes/kubernetes/blob/0734820279ccce8c6034d9d122392fe3a0c7535e/pkg/apis/core/validation/events.go#L38) (1024 chars). Note that one plugin can yield different messages. When the limit is hit, we still need to figure out how to prioritize dumping the failure reasons.

**Comment by denkensk** [comment]
>> I'm not sure that the failure with most frequency is the most important one.
> I agree it's not always, but this helps us narrow down the failures rapidly, and is much better than the alphabet order.

+1 
In general, the highest frequency of failure is most likely not the most important. 
A simple idea, can we order the failure reasons according to the reverse order of pre-filter or filter execution?

**Comment by Huang-Wei** [comment]
Another idea is to give a shortcode (like `SCHED0001`) to each failure reason, and have a central place to lookup the particular human-readable message, so that we can always limit the msg to 1024 characters.

**Comment by ahg-g** [comment]
> Another idea is to give a shortcode (like SCHED0001) to each failure reason

Not a good UX, it feels like one for a washing machine :)

> A simple idea, can we order the failure reasons according to the reverse order of pre-filter or filter execution?

That is actually a good idea, I like it, at least as a starting point.

> I'm afraid it can still reach the msg [limit](https://github.com/kubernetes/kubernetes/blob/0734820279ccce8c6034d9d122392fe3a0c7535e/pkg/apis/core/validation/events.go#L38) (1024 chars)

Yeah, we still need enforce a limit of the total message. 

> Note that one plugin can yield different messages.

Yes, but we can have logic to aggregate those; for example, imagine a `ErrorMessage` type that `RunFilterPlugins` creates and uses to aggregate the filtering reasons per plugin. And then each plugin should have a function that given a `ErrorMessage`, it returns a single message.

We also need to be more direct in those error messages in general, for example a message like `1 node(s) had taint {node-001: }, that the pod didn't tolerate,` can be shortened significantly without loosing context.

**Comment by alculquicondor** [comment]
So as conclusions (probably good in different PRs):

1. go through all the messages and try to shorten them without losing context
2. order the failure reasons according to the reverse order of pre-filter or filter execution

**Comment by Huang-Wei** [comment]
It's challenging (or basically impossible) to come up with one universal sorting rule to claim that under any circumstance, the first ordered one is always the most important. So we have to find a more practical rule to fit _most_ cases.

@denkensk 's suggested sorting rule reveals another layer of info: the head failure semantically implies "X nodes have passed all other (N - X) nodes". They're likely the failures on the "critical path", although not always the case. So I'm in for this as a starting point.

**Comment by Huang-Wei** [comment]
> 2\. order the failure reasons according to the reverse order of pre-filter or filter execution

I will let this issue soak for a while, and if no objections, I can get it implemented - basically use the profile's finalized PreFilter/Filter list instead of the static default ones.

**Comment by alculquicondor** [comment]
Can we get 1 before the codefreeze?

**Comment by Huang-Wei** [comment]
I took a quick look at the error strings, it seems all strings are fairly concise except for the [taint error](https://github.com/kubernetes/kubernetes/blob/b33897f36d219b644f2222c34730ec29aff228c1/pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go#L79).

**Comment by alculquicondor** [comment]
I think it's useful to know the taint. Can we start by just reducing the text?

`(s) had untolerated taints {key, val}`

**Comment by alculquicondor** [comment]
I think we can fix a few more:

`node(s) didn't satisfy existing pods anti-affinity` (remove word rules)

`node(s) didn't have free ports for the incoming pod`

**Comment by ravisantoshgudimetla** [comment]
+1 - I think we should have taint info at the least

**Comment by Huang-Wei** [comment]
> node(s) had untolerated taints {key, val}

I'm going to make this minimum change in 1.24. And in 1.25, come up with a way to make the message compact and adaptive (like setting a maximum length limit for each plugin's failure message, and if it exceeds, fall back to a compact messaging mode)

**Comment by ahg-g** [comment]
I think it is worth doing this -> "A simple idea, can we order the failure reasons according to the reverse order of pre-filter or filter execution?"
