### ISSUE TITLE
osm-init Back-off restarting failed container

### ISSUE THREAD

**Issue by shanghai636848** [kubernetes/kubernetes#108961]
### Which jobs are failing?

modprobe: can't change directory to '/lib/modules': No such file or directory
iptables-restore v1.8.7 (legacy): iptables-restore: unable to initialize table 'nat'
Error occurred at line: 2
Try `iptables-restore -h' or 'iptables-restore --help' for more information.

### Which tests are failing?

osm-init 

### Since when has it been failing?

osm-init 

### Relevant SIG(s)

/sig

**Comment by MadhavJivrajani** [comment]
/remove-kind failing-test
/close

@shanghai636848 please reopen this issue as a bug report with the relevant details. Or if I am mistaken, please fill in the relevant information about test grid if this is indeed a failing test. Thank you.

**Comment by MadhavJivrajani** [comment]
You can reopen the issue by commenting `/reopen`
