### ISSUE TITLE
kubetnetes1. 23 flannel configuration directrouting is not effective #1554

### ISSUE THREAD

**Issue by lsc615** [kubernetes/kubernetes#109064]
### What happened?

I want to set Flannle to directrouting mode, but it doesn't work
I have added configuration "Directrouting": true，but The route is still via flannel.1 onlink
```
net-conf.json: |
{
"Network": "10.244.0.0/16",
  "Backend": {
  "Type": "vxlan",
  "Directrouting": true
  }
}
```
[root@hecs-kube-0001 manifests]# ip route
default via 192.168.0.1 dev eth0 proto dhcp metric 100 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink 
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink 

### What did you expect to happen?

 Set "directrouting": true after ,The route should be via eth0

### How can we reproduce it (as minimally and precisely as possible)?

```
net-conf.json: |
{
"Network": "10.244.0.0/16",
  "Backend": {
  "Type": "vxlan",
  "Directrouting": true
  }
}
```
kubecrl apply -f flannel.yml

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

huawei hecs

### OS version

Linux hecs-kube-0001 4.4.222-1.el7.elrepo.x86_64 #1 SMP Mon May 4 19:25:23 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aojea** [comment]
I suggest you to open the issue on the flannel project https://github.com/flannel-io/flannel , this is for Kubernetes only issues

Thanks

/close
