### ISSUE TITLE
E2eNode Suite: [sig-node] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [NodeFeature:HostAccess] 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#109096]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Which tests are failing?

- E2eNode Suite: [sig-node] Security Context when creating a pod in the host PID namespace should show its pid in the host PID namespace [NodeFeature:HostAccess] expand_less 

```
{ Failure test/e2e_node/security_context_test.go:136
Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc000dc6aa0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb\" is forbidden: violates PodSecurity \"baseline:latest\": host namespaces (hostPID=true)",
            Reason: "Forbidden",
            Details: {
                Name: "nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "nginx-hostpid-a497a22b-e503-41cd-8e45-da07c7563fbb" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostPID=true)
occurred
test/e2e/framework/pods.go:99}
```

### Since when has it been failing?

since last night.

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Reason for failure (if possible)

https://github.com/kubernetes/kubernetes/pull/106454 

### Anything else we need to know?

NA

### Relevant SIG(s)

/sig auth node

**Comment by ehashman** [comment]
This is failing on a ton of jobs.

/kind regression
/priority important-soon
/milestone v1.24

Triage dump:

### Failure cluster [43ba1558eec5d3201112](https://go.k8s.io/triage#43ba1558eec5d3201112)

##### Error text:
```
test/e2e_node/security_context_test.go:225
Error creating Pod
Unexpected error:
    <*errors.StatusError | 0xc000c823c0>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "pods \"ipcutils-hostipc-b9c6534d-cad3-436c-8580-211c67d8d032\" is forbidden: violates PodSecurity \"baseline:latest\": host namespaces (hostIPC=true)",
            Reason: "Forbidden",
            Details: {
                Name: "ipcutils-hostipc-b9c6534d-cad3-436c-8580-211c67d8d032",
                Group: "",
                Kind: "pods",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 403,
        },
    }
    pods "ipcutils-hostipc-b9c6534d-cad3-436c-8580-211c67d8d032" is forbidden: violates PodSecurity "baseline:latest": host namespaces (hostIPC=true)
occurred
test/e2e/framework/pods.go:99
```
#### Recent failures:
[3/29/2022, 8:34:07 AM ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1508829867938942976)
[3/29/2022, 8:32:07 AM ci-cos-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-node-e2e-features/1508829364626657280)
[3/29/2022, 8:32:07 AM ci-cos-cgroupv2-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-features/1508829364656017408)
[3/29/2022, 7:59:12 AM ci-cri-containerd-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e-features/1508821060559048704)
[3/29/2022, 7:38:12 AM ci-kubernetes-node-swap-fedora](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-fedora/1508815775069114368)
