### ISSUE TITLE
client-go: Stream does not retry on transient network failure

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#109021]
### What happened?

`Do` and `Watch` in client-go retry on transient network error, these errors include:
- EOF error
- timeout error

Watch: https://github.com/kubernetes/kubernetes/blob/e7845861a5284ae9eb60268dc8e79e7ce4b34362/staging/src/k8s.io/client-go/rest/request.go#L610-L612

Do and DoRaw: https://github.com/kubernetes/kubernetes/blob/e7845861a5284ae9eb60268dc8e79e7ce4b34362/staging/src/k8s.io/client-go/rest/request.go#L854-L856

On the other hand, `Stream` never retries on transient network error. It retries only if the server sends a `Retry-After` response. 

https://github.com/kubernetes/kubernetes/blob/e7845861a5284ae9eb60268dc8e79e7ce4b34362/staging/src/k8s.io/client-go/rest/request.go#L754-L756

https://github.com/kubernetes/kubernetes/blob/e7845861a5284ae9eb60268dc8e79e7ce4b34362/staging/src/k8s.io/client-go/rest/with_retry.go#L46-L48

### What did you expect to happen?

`Stream` can retry (if we know that the first byte hasn't arrived yet) on transient network errors

### Kubernetes version

All

**Comment by aojea** [comment]
I suggest to not add more intelligence to client-go without a clear indication that this really solves a problem, is really some use case for retries on Stream?
current code with retries is complicated and we have subtle bugs like https://github.com/kubernetes/kubernetes/pull/109028/

**Comment by lavalamp** [comment]
I agree with @aojea -- did this cause an actual bug, or is it just theoretically not correct?

**Comment by wojtek-t** [comment]
> I agree with @aojea -- did this cause an actual bug, or is it just theoretically not correct?

Not that I'm aware.

I suggested that in one of the reviews to purely unify across Do, Watch and Stream - each of them works slightly differently and there are things that could be unified across them - it would make reasoning about them slightly easier.
