### ISSUE TITLE
1.24 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by AuraSinis** [kubernetes/kubernetes#109027]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.24 Release Notes. If you know of issues or API changes that are going out in 1.24, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign  @AuraSinis  @RinkiyaKeDad @Lp-Francois @csantanapr

/sig release

**Comment by liggitt** [comment]
go1.18 changes certificate validation - https://github.com/kubernetes/kubernetes/pull/109024 adds metrics/logs needed to monitor for impact; the release note there describes the issue and what users should do if they are unsure whether they are impacted

**Comment by ehashman** [comment]
SIG Node https://github.com/kubernetes/kubernetes/issues/109182 - we have updated to runc 1.1.1 in k8s 1.24. If a user runs Kubernetes inside a container, and the container environment which is running Kubernetes uses a version of runc <1.1.x, cgroups that the older version of runc does not support (such as `rdma` and `unified`) may be leaked to the parent namespace, and the container runtime will be unable to remove them.

We recommend that if Kubernetes is run in a container, the runc versions should match.

**Comment by jyotimahapatra** [comment]
Closing now. 1.24 is releasing tomorrow , please reopen if anything urgent comes up between now and the release.

/close
