### ISSUE TITLE
kube-proxy crash loop

### ISSUE THREAD

**Issue by timaebi** [kubernetes/kubernetes#109052]
### What happened?

In IPVS mode if kube-proxy tries to bind to an ipv6 port which is already in use, I get the following error message and kube-proxy crashes.

```
I0326 13:45:33.879885       1 proxier.go:1026] "syncProxyRules complete" elapsed="33.302265ms"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x18999b5]

goroutine 79 [running]:
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).syncProxyRules(0xc000159e00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:1263 +0x6195
k8s.io/kubernetes/pkg/proxy/ipvs.(*Proxier).OnEndpointSlicesSynced(0xc000159e00)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/ipvs/proxier.go:942 +0x65
k8s.io/kubernetes/pkg/proxy/metaproxier.(*metaProxier).OnEndpointSlicesSynced(0xc0003fd200)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/metaproxier/meta_proxier.go:189 +0x4a
k8s.io/kubernetes/pkg/proxy/config.(*EndpointSliceConfig).Run(0xc000678180, 0xc000180360)
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/pkg/proxy/config/config.go:232 +0x20a
created by k8s.io/kubernetes/cmd/kube-proxy/app.(*ProxyServer).Run
	/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-proxy/app/server.go:749 +0x71c
```

```
$ kubectl get pods -n kube-system -o wide
...
kube-proxy-4p462                           0/1     CrashLoopBackOff   13 (2m24s ago)   43m    10.144.0.74     worker-02   <none>           <none>
kube-proxy-9rz42                           0/1     CrashLoopBackOff   13 (2m ago)      43m    10.144.0.75     worker-03   <none>           <none>
...
```

Having a quick look at the code I think this nil dereference happens when kube-proxy tries to record the event in [proxier.go line 1263](https://github.com/kubernetes/kubernetes/blob/v1.22.4/pkg/proxy/ipvs/proxier.go#L1263).
The underlying problem is that the recorder is explicitly set to nil when the ipv6 proxier is initialized in [proxier.go line 548](https://github.com/kubernetes/kubernetes/blob/v1.22.4/pkg/proxy/ipvs/proxier.go#L548). In my understanding it should be initialised similar to the ipv4 proxier with a non-nil recorder.

### What did you expect to happen?

I expect kube-proxy to write a log message instead of panicking.

### How can we reproduce it (as minimally and precisely as possible)?

1. Setup a dual-stack kubernetes cluster
2. Use IPVS mode for 
3. Create a dualstack external ip service which binds to an IPv6 address that is already in use
4. Wait for kube-proxy to crash

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:31:32Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux worker-01 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

**Comment by cyclinder** [comment]
I agree initialize Ipv6 proxier with non-nil recorder. I'm curious as to why the initialization of IPv6 proxier with the nil recorder, Here are some reasons?

**Comment by neolit123** [comment]
Option 1 sounds better but i have not looked at the code.

**Comment by aojea** [comment]
/area ipvs

That code has been removed recently https://github.com/kubernetes/kubernetes/commit/c4a00b7d90a3df2dc917c0881e3ef0461263da23

**Comment by cyclinder** [comment]
so we only should fix it to 1.22 and 1.23?

**Comment by aojea** [comment]
1.23, if this is a dual stack bug only, https://kubernetes.io/blog/2021/12/08/dual-stack-networking-ga/
betas don't use to receive backports

**Comment by aojea** [comment]
oh, wait, this is going to be backported already https://github.com/kubernetes/kubernetes/pulls?q=is%3Aopen+is%3Apr+author%3Aaramase+port+opener
