### ISSUE TITLE
Re work pkg/util/ipset.Validate()

### ISSUE THREAD

**Issue by ArangoGutierrez** [kubernetes/kubernetes#109034]
### What would you like to be added?

As discussed at https://github.com/kubernetes/kubernetes/pull/108946#discussion_r835426136

Slightly larger comment:  This API is very weak on "hiding".  

The question left is, if it would be better to make a bigger change and use a constructor, like:

```
type ArgFunc func(s *ipSet) error

func New(name string, type Type, comment string, args ...ArgFunc) Interface {
    //validate params, return error if needed
    s := ipSet {
        name: name,
        type: type,
        comment: comment,
    }
    // call each fn(&s) in args, return error if needed
    return s
}

func HashArgs(family string, hashSize,  maxElem int) ArgFunc {
     return func(s *ipSet) error {
        // validate args and return error if needed
        s.family = family
        s.hashSize = hashSize
        s.maxElem = maxElem
        return nil
    }
}

func PortArgs(range string) ArgFunc {
    return func(s *ipSet) error {
        // validate args and return error if needed
        s.range = range
    }
}
```

or even this (I am not an ipset expert so my name choices may not be good :):

```
func NewHashSet(name string, type Type, comment string, family string, hashSize,  maxElem int) Interface {...}
func NewPortSet(name string, type Type, comment string, range string) Interface {...}
```

Also HashFamily could be a type with const values, like `Type`

_Originally posted by @thockin in https://github.com/kubernetes/kubernetes/pull/108946#discussion_r835426136_

### Why is this needed?

The point being to hide as much detail as possible and export as few things as possible.  This lib isn't used a ton, so fixing clients should be OK.

**Comment by ArangoGutierrez** [comment]
@thockin  feel free to assign this to me if you feel proper

**Comment by thockin** [comment]
Go ahead and jump on it if you like - emphasis on exposing as little as possible and keeping it as simple as possible (users should not need to set fields they don't use, etc).

**Comment by mrjoema** [comment]
Can I try this if no one is available to fix it ?

**Comment by kidddddddddddddddddddddd** [comment]
Is anyone working on this currently?

**Comment by mrjoema** [comment]
@kidddddddddddddddddddddd I am not working on this now. Feel free to pick it up if you want to

**Comment by STRRL** [comment]
I am also interested in this issue. Maybe could I pick it? @mrjoema @kidddddddddddddddddddddd 

BTW, is there possible to extra ipset as a standalone library? As a committer of [chaos-mesh](https://github.com/chaos-mesh/chaos-mesh), I think similar works are also required when injecting NetworkChaos.

**Comment by kidddddddddddddddddddddd** [comment]
> I am also interested in this issue. Maybe could I pick it?

@STRRL I'm not working on it, so feel free to pick it up.

**Comment by STRRL** [comment]
Hi @thockin, @lavalamp, @thockin metioned a functional options/args pattern for refactoring the ipset api. But the disadvantage of functional pattern is we would still maintain the full-set of all the possible options, like the current `IPSet`. 

It seems it could not "hide" more details to the user, the user still needs to think about which "Option"/"Arg" is required for his/her purpose.

IMHO, maybe we could provide the API with another pattern, resolve ipset as different type of resoruces: `hash:ip`, `hash:ip,port`, etc.. For example:

```go
type Interface interface {
    GenericInterface
    HashIP() HashIPInterface
    HashIPPort() HashIPPortInterface
    // other restricted "interfaces" with certain ipset type
    ...
}

type GenericInterface interface {
    FlushSet(set string) error
	DestroySet(set string) error
	DestroyAllSets() error
    ListSets() ([]string, error)
}

type HashIPInterface interface {
    CreateSet(set HashIPIPSet, ignoreExistErr bool) error
    AddEntry(entry HashIPEntry, setName string, ignoreExistErr bool) error
	DelEntry(entry HashIPEntry, setName string) error
	TestEntry(entry HashIPEntry, setName string) (bool, error)
	ListEntries(setName string) ([]HashIPEntry, error)
}

type HashIPPortInterface interface {
    CreateSet(set HashIPPortIPSet, ignoreExistErr bool) error
    AddEntry(entry HashIPPortEntry, setName string, ignoreExistErr bool) error
	DelEntry(entry HashIPPortEntry, setName string) error
	TestEntry(entry HashIPPortEntry, setName string) (bool, error)
	ListEntries(setName string) ([]HashIPPortEntry, error)
}

...
```

We could povide these API with restricted/strong typed interface without using combined/union options. And maybe we could use go 1.18 generic types to implement that.

How do you think about it? @thockin, @lavalamp :heart:

**Comment by STRRL** [comment]
> Hi @thockin, @lavalamp, @thockin metioned a functional options/args pattern for refactoring the ipset api. But the disadvantage of functional pattern is we would still maintain the full-set of all the possible options, like the current `IPSet`.
> 
> It seems it could not "hide" more details to the user, users still need to think about which "Option"/"Arg" is required for their purpose.
> 
> IMHO, maybe we could provide the API with another pattern, resolve ipset as different type of resoruces: `hash:ip`, `hash:ip,port`, etc.. For example:
> 
> ```go
> type Interface interface {
>     GenericInterface
>     HashIP() HashIPInterface
>     HashIPPort() HashIPPortInterface
>     // other restricted "interfaces" with certain ipset type
>     ...
> }
> 
> type GenericInterface interface {
>     FlushSet(set string) error
> 	DestroySet(set string) error
> 	DestroyAllSets() error
>     ListSets() ([]string, error)
> }
> 
> type HashIPInterface interface {
>     CreateSet(set HashIPIPSet, ignoreExistErr bool) error
>     AddEntry(entry HashIPEntry, setName string, ignoreExistErr bool) error
> 	DelEntry(entry HashIPEntry, setName string) error
> 	TestEntry(entry HashIPEntry, setName string) (bool, error)
> 	ListEntries(setName string) ([]HashIPEntry, error)
> }
> 
> type HashIPPortInterface interface {
>     CreateSet(set HashIPPortIPSet, ignoreExistErr bool) error
>     AddEntry(entry HashIPPortEntry, setName string, ignoreExistErr bool) error
> 	DelEntry(entry HashIPPortEntry, setName string) error
> 	TestEntry(entry HashIPPortEntry, setName string) (bool, error)
> 	ListEntries(setName string) ([]HashIPPortEntry, error)
> }
> 
> ...
> ```
> 
> We could povide these API with restricted/strong typed interface without using combined/union options. And maybe we could use go 1.18 generic types to implement that.
> 
> How do you think about it? @thockin, @lavalamp ❤️
> 
> Please let me know if I am still on the correct path, or I missed something.

kindly notice @thockin @lavalamp @kanha-gupta 

I would work based this design in the next several days. 

please let me known if you have any other ideas :)

**Comment by STRRL** [comment]
Could we use generics in kubernetes code base? I saw that we have use go 1.18 but there is no generics code exist in current codebase. Are there any concerns? @thockin @lavalamp @ArangoGutierrez

**Comment by kapiljain1989** [comment]
Hi @ArangoGutierrez @STRRL , Are you working on this task?

**Comment by ArangoGutierrez** [comment]
No, I have not had time to work on this. feel free to take it. if you can close it is nice. if not I will circle back in a couple weeks that I suspect I will have some time for this

**Comment by kapiljain1989** [comment]
TY @ArangoGutierrez

**Comment by adhishmeena** [comment]
@kapiljain1989  are you still working on it ?

**Comment by PalanQu** [comment]
@thockin Hi, I have commited a PR, could you please help me to review the PR, thx.

**Comment by danwinship** [comment]
/close

The ipset code has now been made internal to `pkg/proxy/ipvs`, so making the API more abstract is both less necessary and less useful now. If we were going to clean up the package, the sorts of cleanups we would want are likely different than before, when the code theoretically had multiple users.
