### ISSUE TITLE
KeyEncipherment usage should not be required for non-RSA kubelet client/serving CSRs

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#109077]
### What happened?

https://github.com/golang/go/issues/36499 describes why the KeyEncipherment extended key usage does not make sense (and in some cases, is not allowed) for ECDSA keys.

The Kubernetes `kubernetes.io/kubelet-serving` and `kubernetes.io/kube-apiserver-client-kubelet` signer names require a `key encipherment` usage.

If the kubelet is not using an RSA key (which it does not [by default](https://github.com/kubernetes/kubernetes/blob/v1.23.0/staging/src/k8s.io/client-go/util/certificate/certificate_manager.go#L640-L642)), it should not need to specify this key usage.

Since relaxing this to make the `key encipherment` usage optional for those two signerNames may involve an API validation change, this may need rollout over 2 releases. The places we'll need to make sure work properly are:

1. API validation of CSR create and update requests
2. Controller tolerating CSR objects with/without that usage
3. Kubelets requesting CSRs properly without that usage if given a non-RSA key

### What did you expect to happen?

n/a

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
no one has picked it up, but it remains important

**Comment by pacoxu** [comment]
/assign 
I will take a look next week.

**Comment by pacoxu** [comment]
milestone v1.25 task was done. We can tag this to be milestone v1.26 now.

**Comment by cailynse** [comment]
Hello @pacoxu! Bug Triage shadow here - I wanted to check in and see if this issue is still on track for 1.26?

**Comment by pacoxu** [comment]
> Hello @pacoxu! Bug Triage shadow here - I wanted to check in and see if this issue is still on track for 1.26?

Yes. I will follow up https://github.com/kubernetes/kubernetes/pull/111660 later, and there are still CI failures to be fixed.
