### ISSUE TITLE
Should defaults for non-nullable structs be published in OpenAPI

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#109036]
### What happened?

The defaulting KEP introduces the default annotation that can be added for types and CRDs to publish default values for types to the OpenAPI. As a part of this, defaults for non-nullable fields are also published to illustrate how fields with no value set will have a default value set upon apply. For primitives, this makes sense as it would be useful to see how int fields are defaulted to 0, etc.

The non-nullable defaulting also applies to structs, and we get a lot of cases that do not seem very useful, eg: ObjectMeta, Spec, Status, etc (https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/v3/apis__batch__v1_openapi.json#L17). This pollutes our OpenAPI v3 and IMO a default of map[string]interface{} is not very useful for consumers.

I'd like to suggest removing publishing default for non-nullable structs if they do not have a default annotation provided. (https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/openapi.go#L572-L573)

/cc @apelisse 

### What did you expect to happen?

See above

### How can we reproduce it (as minimally and precisely as possible)?

See a bove

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by apelisse** [comment]
We've very carefully crafted the defaults for built-in types to describe their implicit behavior, also so that they do match with the behavior of CRDs. I don't think we should hide that away, since it makes the OpenAPI more consistent for built-ins and CRDs.
