### ISSUE TITLE
error: no objects passed to create

### ISSUE THREAD

**Issue by vij2** [kubernetes/kubernetes#109126]
### What would you like to be added?

Gets the below error message below,

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
+ kubectl create -f -
error: no objects passed to create

My parameters are in place 

### Why is this needed?

Gets the below error message below,

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
+ kubectl create -f -
error: no objects passed to create

My parameters are in place

**Comment by vij2** [comment]
Now gets the below error message,

error validating "appcode/ci/xxx/Chart.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false
error parsing appcode/ci/xxxx/templates/pgpool-deployment.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.pgpool_deployment.replicas":interface {}(nil)}
error parsing appcode/ci/xxxxx/templates/postgres-sts.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.postgres_sts.replicas":interface {}(nil)}
error validating "appcode/ci/xxxxx/values.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

However, I had set the apiVersion.

**Comment by pacoxu** [comment]
/kind support
Could you provide more detailed steps on how to reproduce the problem?

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
