### ISSUE TITLE
Dry run create requests clear metadata.name if metadata.generateName is set

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#109174]
https://github.com/kubernetes/kubernetes/pull/107088 changed behavior of dry run requests to clear the name of an object if metadata.generateName is set

That is not correct if both metadata.name and metadata.generateName are set in the create request.

Rather than changing behavior from <1.23, then changing it again if/when we are able to distinguish when the user only set generateName, I think we should leave that behavior as is until we can distinguish.

/kind bug
/kind regression
/milestone v1.24
/assign @joejulian 
/sig api-machinery
/priority important-soon

**Comment by liggitt** [comment]
cc @deads2k as original approver

**Comment by fedebongio** [comment]
@joejulian are you planning to work on this one? thanks!

**Comment by joejulian** [comment]
I am, yes. I'll try to do something by the end of the week.

**Comment by jyotimahapatra** [comment]
@joejulian 👋 1.24 bug triage checking in. I noticed https://github.com/kubernetes/kubernetes/pull/107088 is merged. Are there more PRs remaining? or is this considered done?

**Comment by dims** [comment]
@jyotimahapatra that's an old PR. i don't think there's a PR for this yet AFAIK

**Comment by liggitt** [comment]
If we don't have a PR pending ~today, I plan to revert https://github.com/kubernetes/kubernetes/pull/107088 for 1.24

**Comment by jyotimahapatra** [comment]
@liggitt  @joejulian We're past test freeze. I propose that we move it to 1.25. wdyt?

**Comment by liggitt** [comment]
No. This is a regression in 1.24 we must not ship.

**Comment by liggitt** [comment]
opened revert of https://github.com/kubernetes/kubernetes/pull/107088 at https://github.com/kubernetes/kubernetes/pull/109340, can bring that in again in 1.24 with https://github.com/kubernetes/kubernetes/pull/107088#discussion_r839133219 resolved

**Comment by joejulian** [comment]
:thumbs_up:

**Comment by liggitt** [comment]
/close
resolved in https://github.com/kubernetes/kubernetes/pull/109340

reopened original tracking issue https://github.com/kubernetes/kubernetes/issues/107086
