### ISSUE TITLE
[Failing test] sig-release-master-blocking#ci-kubernetes-unit

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/kubernetes#109136]
### Which jobs are failing?

[sig-release-master-blocking#ci-kubernetes-unit](https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit)

### Which tests are failing?

k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.TestPreShutdownHooks

### Since when has it been failing?

17:42 PDT 3/29

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

### Reason for failure (if possible)

```
{Failed  === RUN   TestPreShutdownHooks
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 100ms, url: https://127.0.0.1:40845/echo?message=attempt-1
I0330 02:05:41.123870   78579 tlsconfig.go:240] "Starting DynamicServingCertificateController"
I0330 02:05:41.124641   78579 secure_serving.go:210] Serving securely on [::]:40845
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc00052cf00)}}
    genericapiserver_graceful_termination_test.go:535: Still waiting for the server to start - err: <nil>
    genericapiserver_graceful_termination_test.go:653: [server] received a request, proto: HTTP/2.0, url: /echo?message=attempt-1
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 100ms, url: https://127.0.0.1:40845/echo?message=attempt-2
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc0000f1f80)}}
    genericapiserver_graceful_termination_test.go:653: [server] received a request, proto: HTTP/2.0, url: /echo?message=attempt-2
    genericapiserver_graceful_termination_test.go:543: The API server has started
I0330 02:05:41.414509   78579 object_count_tracker.go:84] "StorageObjectCountTracker pruner is exiting"
    genericapiserver_graceful_termination_test.go:560: Sending request - timeout: 100ms, url: https://127.0.0.1:40845/echo?message=attempt-0
    genericapiserver_graceful_termination_test.go:671: [server] seen new connection: &net.TCPConn{conn:net.conn{fd:(*net.netFD)(0xc000436480)}}
    genericapiserver_graceful_termination_test.go:478: PreSHutdown hook can not access the API server - Get "https://127.0.0.1:40845/echo?message=attempt-0": context deadline exceeded
--- FAIL: TestPreShutdownHooks (0.51s)
}
```

### Anything else we need to know?

Failed with the same error for last 4 runs.
Beta release cut is scheduled for tomorrow and this is currently a blocker.

### Relevant SIG(s)

/sig testing

**Comment by lauralorenz** [comment]
Looks like this is also being discussed [#sig-testing slack](https://kubernetes.slack.com/archives/C09QZ4DQB/p1648607376354129) and x-ref this test was merged 4 hours ago https://github.com/kubernetes/kubernetes/pull/108033#issuecomment-1082531826

**Comment by lauralorenz** [comment]
More x-ref:
SIG api machinery is tracking it themselves in #109133
There is a PR to increase the timeout in #109134

**Comment by lauralorenz** [comment]
More x-ref:
Same post in the [#sig-api-machinery slack](https://kubernetes.slack.com/archives/C0EG7JC6T/p1648606081058449).

**Comment by lauralorenz** [comment]
Per [#sig-testing slack thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1648615574595719?thread_ts=1648607376.354129&cid=C09QZ4DQB) this should be resolved and not be a blocker, testgrid is still red but I think the expectation is that it should clear up. Leaving this open for now but currently expecting this not to block release cut tomorrow.

**Comment by BenTheElder** [comment]
this is the same root issue as https://github.com/kubernetes/kubernetes/issues/109133 (same flake is occurring in PR unit testing)
