### ISSUE TITLE
webhooks has 2 compatible issues with  kubernetes v1.18

### ISSUE THREAD

**Issue by waynerv** [kubernetes/kubernetes#109145]
I'm using kubernetes 1.18.17 and I'm experiencing the following compatibility issue when I try to enable pod-security-admission by installing webhook as per the documentation instructions.

1. kustomize not support "replacements" field:
   ```
   kubectl apply -k .
   error: json: unknown field "replacements"
   ```
   Workaround: install latest kusomize and run `kustomize build . | kubectl apply -f -`
2. unknown field "seccompProfile" in `50-deployment.yaml`
   ```
   error: error validating "STDIN": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.SecurityContext; if you choose to ignore these errors, turn validation off with --validate=false
   ```
   `securityContext.seccompProfile` is available after v.1.19, so I have to convert it to old annotation style.

Since the main purpose of webhook is to provide an alternative to older versions, think it is worthwhile to fix these compatibility issues.

**Comment by liggitt** [comment]
Using the newest version of kubectl is recommended and will allow applying the manifest. 

For the seccomp field, that is available in 1.19+ and in all supported versions of Kubernetes (currently 1.21+). You can bypass the client-side complaint about the unknown field with the flag --validate=false to continue creating the manifest on older versions.

A PR updating the readme with that information would be welcome
