### ISSUE TITLE
Cannot modify registry keys during Windows pause image build process

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#109161]
### What happened?

The Windows pause images is built using buildkit on Linux hosts and this configuration does not allow for the Windows registry to me modified during the container build process.

When Windows containers are built on Windows host machines part of the build process creates 'delta' registry files when get stored in the layer files. These 'delta' registry hive files are applied to the containers active registry when the containers are created.
Chaning the registry files in the container image layers without having the 'delta' files present will result in the changes NOT being present in the container image.

We have an increasing demand for the ability to modify registry in the pause image on Windows such as 
- Disable some services like DiagTrack that negatively impact performance
- Change behavior of RPCSS so it doesn't hijack RPC port (135) for all containers in the pod

### What did you expect to happen?

Things are working as expected given the current build process.

### How can we reproduce it (as minimally and precisely as possible)?

There are linux utilities like `chntpw` that can modify Windows registry files that I have used to test this out.
https://gist.github.com/marosset/f32bd81aa11527d8ba2ce8e6a62d4255 
After running the container produced from these files you can see the registry changes made by `chntpw` persisted in the container image but these changes are not present in the container's active registry.

```bash
C:\>reg load HKLM\mounted c:\windows\System32\config\SYSTEM
The operation completed successfully.

C:\>reg query HKLM\mounted\ControlSet001\Services\DiagTrack

HKEY_LOCAL_MACHINE\mounted\ControlSet001\Services\DiagTrack
    DependOnService    REG_MULTI_SZ    RpcSs
    Description    REG_SZ    @%SystemRoot%\system32\diagtrack.dll,-3002
    DisplayName    REG_SZ    @%SystemRoot%\system32\diagtrack.dll,-3001
    ErrorControl    REG_DWORD    0x1
    FailureActions    REG_BINARY    8051010000000000000000000300000014000000010000003075000001000000307500000000000000000000
    ImagePath    REG_EXPAND_SZ    %SystemRoot%\System32\svchost.exe -k utcsvc -p
    ObjectName    REG_SZ    LocalSystem
    RequiredPrivileges    REG_MULTI_SZ    SeChangeNotifyPrivilege\0SeCreateGlobalPrivilege\0SeAssignPrimaryTokenPrivilege\0SeImpersonatePrivilege\0SeSystemProfilePrivilege\0SeTcbPrivilege\0SeDebugPrivilege\0SeSecurityPrivilege
    ServiceSidType    REG_DWORD    0x1
    Start    REG_DWORD    0x3
    Type    REG_DWORD    0x10
```

vs

```bash
C:\>REG QUERY HKLM\SYSTEM\ControlSet001\Services\DiagTrack

HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Services\DiagTrack
    DependOnService    REG_MULTI_SZ    RpcSs
    Description    REG_SZ    @%SystemRoot%\system32\diagtrack.dll,-3002
    DisplayName    REG_SZ    @%SystemRoot%\system32\diagtrack.dll,-3001
    ErrorControl    REG_DWORD    0x1
    FailureActions    REG_BINARY    8051010000000000000000000300000014000000010000003075000001000000307500000000000000000000
    ImagePath    REG_EXPAND_SZ    %SystemRoot%\System32\svchost.exe -k utcsvc -p
    ObjectName    REG_SZ    LocalSystem
    RequiredPrivileges    REG_MULTI_SZ    SeChangeNotifyPrivilege\0SeCreateGlobalPrivilege\0SeAssignPrimaryTokenPrivilege\0SeImpersonatePrivilege\0SeSystemProfilePrivilege\0SeTcbPrivilege\0SeDebugPrivilege\0SeSecurityPrivilege
    ServiceSidType    REG_DWORD    0x1
    Start    REG_DWORD    0x2
    Type    REG_DWORD    0x10
```

### Anything else we need to know?

One possible solution is to create an intermediate image based on `nanoserver` (the current base image for the Windows pause image) that performs all the desired registry operations that is built on a Windows machine and published someplace (MCR maybe?) and the use that as the container base image for the Windows pause image.

### Kubernetes version

<details>

N/A

</details>

### Cloud provider

<details>

N/A

</details>

### OS version

<details>

N/A

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
my first concern was. will a community member be able to build this image themselves (will the sources be available and up-to-date and the image built from it). We could also do a github hosted windows runner to build / publish this new image as well. let's please revisit this once we wrap 1.24.

**Comment by marosset** [comment]
We created https://github.com/microsoft/windows-pause-image-base which has the source/docker files used to build `mcr.microsoft.com/oss/kubernetes/windows-pause-image-base:v0.1`.

AKS has made a pause image based on image available to some customers out of necessity to unblock some scenarios.
We'd like to upstream the changes - and do so with as little destabilization to Kubernetes project as possible.

**Comment by BenTheElder** [comment]
Seems like the intermediate base image step would be reasonable. I don't think community members can build the existing base windows images either for the same reason of depending on windows.

**Comment by marosset** [comment]
> Seems like the intermediate base image step would be reasonable. I don't think community members can build the existing base windows images either for the same reason of depending on windows?

The windows pause image is based on 'nanoserver' which is one of several container base images provided by Microsoft (and only Microsoft can produce container base images).

https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-base-images

**Comment by dims** [comment]
@marosset yep. i'd expect community downstream teams (for example) would like to start with this nanoserver, have a set of dockerfiles to build this new image ... then build their own pause images based on this new image

**Comment by dims** [comment]
or in other words if MSFT wants to roll all the changes into nanoserver itself (since we all already know that only MSFT can produce this), then there is no debate after that

**Comment by marosset** [comment]
> or in other words if MSFT wants to roll all the changes into nanoserver itself (since we all already know that only MSFT can produce this), then there is no debate after that

We can't roll these changes into nanoserver because they may break other scenarios.
Because of that having an intermediate layer built somewhere was the best solution we came up with without forking the build process for the pause image.

Microsoft is willing to host build/host the intermediate layers/images from open-sourced docker files.
If we want to build the intermediate layers somewhere else too (like github hosted Windows runners) that would be fine too.

**Comment by mkumatag** [comment]
> We can't roll these changes into nanoserver because they may break other scenarios. Because of that - having an intermediate layer built somewhere was the best solution we came up with without forking the build process for the pause image.
> 
> Microsoft is willing to host build/host the intermediate layers/images from open-sourced docker files. If we want to build the intermediate layers somewhere else too (like github hosted Windows runners) that would be fine too.

If this intermediate image used only by k8s then it is a good idea to build the image via GH actions in the kubernetes org so that k8s maintainers have better control on this or if this image is going to be generic for anyone to use then MSFT can build one and host it somewhere.

**Comment by marosset** [comment]
/cc @claudiubelu @jsturtevant 
as FYI

**Comment by marosset** [comment]
I see two possible paths forward 

- Continue to host the source for the intermediate layer at https://github.com/microsoft/windows-pause-image-base, publish the image to `mcr.microsoft.com/oss/kubernetes/windows-pause-image-base`, and then update the Windows pause build docker files in k/k to consume this image instead of the `mcr.microsoft.com/windows/nanoserver`

or

- Create a new kubernetes-sigs repo to host the source and build steps for the image, publish the image to k8s.gcr.io, and then update the Windows pause build docker files in k/k to consume this image.

I'm fine with either approach but am not sure who the right folks to discuss this with are.

**Comment by mkumatag** [comment]
> * Continue to host the source for the intermediate layer at https://github.com/microsoft/windows-pause-image-base, publish the image to `mcr.microsoft.com/oss/kubernetes/windows-pause-image-base`, and then update the Windows pause build docker files in k/k to consume this image instead of the `mcr.microsoft.com/windows/nanoserver`

This looks more promising because this image you are creating is not a specific change for the pause container, IMO if we can change that image name to something generic and use the same wherever required.

**Comment by BenTheElder** [comment]
I think those both sound reasonable personally.

I think it's technically feasible to push from GitHub actions to staging GCR with workload identity but nobody has done this yet in Kubernetes.
