### ISSUE TITLE
Output format for kubectl get

### ISSUE THREAD

**Issue by dipankardas011** [kubernetes/kubernetes#109100]
### What would you like to be added?

<img width="644" alt="image" src="https://user-images.githubusercontent.com/65275144/160594060-adee42aa-9a0c-4c33-88f1-d390943a9570.png">

### Why is this needed?

The second one is easier to read at a glance

**Comment by dipankardas011** [comment]
```
staging/
|-- src
     |-- k8s.io
          |-- kubectl
	       |-- pkg
		    |-- cmd
		         |-- get
                              ......
```
Is this the path that has src for the kubectl get ... ?

**Comment by eddiezane** [comment]
This isn't a change we'd make to the current printers but you could consider creating a kubectl plugin or using the json output to format how you like.

Also have a look at https://github.com/kubernetes-sigs/kui

/triage unresolved
/close
