### ISSUE TITLE
Increased resource usage in the scalability jobs

### ISSUE THREAD

**Issue by MadhavJivrajani** [kubernetes/kubernetes#109146]
### What happened?

There seem to be increased resource usage for the kube-api-server in the `kubemark-500nodes` job:
CPU:
http://perf-dash.k8s.io/#/?jobname=kubemark-500Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=apiserver%2Fapiserver&Resource=CPU

![Screenshot from 2022-03-30 16-49-13](https://user-images.githubusercontent.com/12381034/160823005-b5e52b83-285b-4407-a10f-57c4c77559e7.png)

`etcd/etcd/data` also sees a similar spike.

We see a similar increase in `kubemark-100`
http://perf-dash.k8s.io/#/?jobname=kubemark-100Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=apiserver%2Fapiserver&Resource=CPU

and `gce-100Nodes`
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-apiserver-e2e-big-master%2Fkube-apiserver&Resource=CPU

which means its probably not kubemark specific

FYI
Memory (at least the 99 and 90th percentile):
http://perf-dash.k8s.io/#/?jobname=kubemark-500Nodes&metriccategoryname=E2E&metricname=LoadResources&PodName=apiserver%2Fapiserver&Resource=memory

fwiw - The `gce-5000Nodes` has not yet run with the above-mentioned change.

/sig scalability
/cc @kubernetes/sig-scalability 
/cc @pacoxu 

### Anything else we need to know?

It seems like the change with which the kubemark-500Node job was run that had the first peak was: https://github.com/kubernetes/kubernetes/pull/101566 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1508923569499803648/

With the kubemark-100Node job, between the last "normal" and the spike, there was the above PR and a documentation-related PR (https://github.com/kubernetes/kubernetes/pull/109121) merged.

Upstream thread: https://kubernetes.slack.com/archives/C09QZTRH7/p1648636053781389 

### Kubernetes version

1.24 +

**Comment by pacoxu** [comment]
the increase is huge, we may fix it in v1.24.

**Comment by wojtek-t** [comment]
The increase is huge, so marking as a release-blocker.

@liggitt - FYI

**Comment by mborsz** [comment]
Let's focus on gce-100Nodes as it's the most impactful regression.

We see also increase on etcd's CPU usage which suggest that the growth is caused by some additional calls.

![image](https://user-images.githubusercontent.com/2559168/160830346-f641fce1-7d31-456e-a28f-b5b38d9bb54b.png)

**Comment by liggitt** [comment]
do we have a good/bad commit range to bisect?

**Comment by MadhavJivrajani** [comment]
@liggit from the ranges I saw (based on the graph going low -> high), a potential commit range could be:
`1ea07d482a5ec15afac5ea837585174579fc0f57` - `7c46f40bdf89a437ecdbc01df45e235b5f6d9745`
with `61b3c028ba618a939559c39befb546ae5e5fd0b9` as a potential candidate for the cause.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/commit/7c46f40bdf89a437ecdbc01df45e235b5f6d9745
to
https://github.com/kubernetes/kubernetes/commit/1ea07d4

if I understand correctly.

**Comment by wojtek-t** [comment]
I didn't double check the range - but it's very clear from the 100-node tests:
http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-apiserver-e2e-big-master%2Fkube-apiserver&Resource=CPU

And they are running every hour.
So basically we have 1h commit range - so shouldn't be that hard to find the right one (and very easy repro).

**Comment by liggitt** [comment]
cc @smarterclayton @thockin on possible churn related to https://github.com/kubernetes/kubernetes/pull/101566

hoisting from https://github.com/kubernetes/kubernetes/pull/101566/files#r838484530

> I think this is populating an alpha field, even when the feature is not enabled and will drop it on write... will this cause churn in kubelet seeing diffs in pod status and thinking it needs to reconcile? https://github.com/kubernetes/kubernetes/pull/88988 comes to mind

**Comment by liggitt** [comment]
do we have the ability to do a presubmit run on a revert of https://github.com/kubernetes/kubernetes/pull/101566 to see if that resolves the issue?

**Comment by wojtek-t** [comment]
@liggitt - yes - it should be visible from the presubmit directly

**Comment by wojtek-t** [comment]
Unfortunately - this can't be automatically reverted:
"Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged."

[I won't get to this today - if someone does that I would be able to look into results of the presubmit later today.]

**Comment by liggitt** [comment]
I can open one, it was a generated openapi json file that conflicted

**Comment by Argh4k** [comment]
I've created https://github.com/kubernetes/kubernetes/pull/109151 but I believe I need /ok-to-test from someone in organization to launch presubmit.

**Comment by dims** [comment]
> So it's 99,9% this PR actually.

wow we tracked this down pretty fast :) Nice job you all!

**Comment by liggitt** [comment]
> cc @smarterclayton @thockin on possible churn related to #101566
> 
> hoisting from https://github.com/kubernetes/kubernetes/pull/101566/files#r838484530
> 
> > I think this is populating an alpha field, even when the feature is not enabled and will drop it on write... will this cause churn in kubelet seeing diffs in pod status and thinking it needs to reconcile? #88988 comes to mind

seeing lots of this in kubelet logs on e2e runs, so I think the answer is yes:

```
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]: I0329 17:54:14.660850   10024 status_manager.go:773] "Pod status is inconsistent with cached status for pod, a reconciliation should be triggered" pod="kube-system/kube-proxy-e2e-584bb6ebb6-a7d53-minion-group-7vzc" statusDiff=<
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:           &v1.PodStatus{
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   ... // 4 identical fields
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   NominatedNodeName:          "",
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   HostIP:                     "10.40.0.4",
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         -         HostIPs:                    []v1.HostIP{{IP: "10.40.0.4"}},
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         +         HostIPs:                    nil,
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   PodIP:                      "10.40.0.4",
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   PodIPs:                     {{IP: "10.40.0.4"}},
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   StartTime:                  s"2022-03-29 17:54:04 +0000 UTC",
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         -         InitContainerStatuses:      nil,
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         +         InitContainerStatuses:      []v1.ContainerStatus{},
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   ContainerStatuses:          {{Name: "kube-proxy", State: {Running: &{StartedAt: {Time: s"2022-03-29 17:54:06 +0000 UTC"}}}, Ready: true, Image: "k8s.gcr.io/kube-proxy-amd64:v1.24.0-alpha.4.396_67212f676d1a4f", ...}},
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:                   QOSClass:                   "Burstable",
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         -         EphemeralContainerStatuses: nil,
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:         +         EphemeralContainerStatuses: []v1.ContainerStatus{},
Mar 29 17:54:14.673252 e2e-584bb6ebb6-a7d53-minion-group-7vzc kubelet[10024]:           }
```

**Comment by MadhavJivrajani** [comment]
> Actually - I realized that I can just look into original presubmit of that PR. So looking into it, 50% percentile for kube-apiserver is:
> 
> ```
>     {
>       "Name": "kube-apiserver-e2e-101566-95a39-master/kube-apiserver",
>       "CPU": 2.125569093,
>       "Mem": 1347194880
>     },
> ```
> 
> So yes - it's already 4x higher here.
> 
> So it's 99,9% this PR actually.

Looks like its back to normal: https://github.com/kubernetes/kubernetes/pull/109151#issuecomment-1083208771

**Comment by liggitt** [comment]
revert is still pending, integration job failures have blocked its merge (12/14 runs failed - 86% failure rate)

**Comment by MadhavJivrajani** [comment]
Revert merged, thank you!
I guess we can close this out once the scalability jobs run with the fix merged (just to be extra sure things are back on track :))

**Comment by wojtek-t** [comment]
Can we wait a bit until we get full confirmation about this in dashboards?

**Comment by pacoxu** [comment]
/close
per dashboard
🎉

![image](https://user-images.githubusercontent.com/2010320/161202168-dae92dac-7395-41dc-b1ab-7919ff8281db.png)
