### ISSUE TITLE
pull-metrics-server-verify logcheck failed

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#109176]
### What happened?

Update pr https://github.com/kubernetes-sigs/metrics-server/pull/972, verify check failed. Error message:

d/openapi/ -O zz_generated.openapi -o /home/prow/go/src/sigs.k8s.io/metrics-server -h /home/prow/go/src/sigs.k8s.io/metrics-server/scripts/boilerplate.go.txt -r /dev/null
go install -mod=readonly k8s.io/klog/hack/tools/logcheck
/home/prow/go/bin/logcheck ./... || (echo 'Fix structured logging' && exit 1)
logcheck: internal error: package "k8s.io/apimachinery/pkg/api/resource" without types was imported from "sigs.k8s.io/metrics-server/pkg/api/generated/openapi"
Fix structured logging
make: *** [Makefile:246: verify-structured-logging] Error 1
+ EXIT_VALUE=2
+ set +o xtrace

such as:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_metrics-server/993/pull-metrics-server-verify/1508837730556055552

### What did you expect to happen?

`pull-metrics-server-verify` logcheck success.

### How can we reproduce it (as minimally and precisely as possible)?

Run `pull-metrics-server-verify` in kubernetes-sigs/metrics-server

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
this issue should be filed against https://github.com/kubernetes-sigs/metrics-server/issues
