### ISSUE TITLE
Increase verbosity of Jenkins flaky suite

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#10915]
IIUC flaky suite consists of tests that require work. I think that increasing default verbosity to V(4) for this suite could help with debugging.

@zmerlynn @ixdy @davidopp

**Comment by quinton-hoole** [comment]
Good idea as soon as we have bandwidth.

**Comment by gmarek** [comment]
Do we have any estimate on that?

**Comment by quinton-hoole** [comment]
post 1.0 unless anyone wants to pick it up before them.  I'm on vacation for a month, so unassigning myself.

**Comment by bprashanth** [comment]
also https://github.com/GoogleCloudPlatform/kubernetes/issues/10308

**Comment by davidopp** [comment]
@ixdy could you take a look at this?

**Comment by gmarek** [comment]
Fixed by #11308
