### ISSUE TITLE
PersistentVolumeController checks for annotation on PVC instead of PV

### ISSUE THREAD

**Issue by gregth** [kubernetes/kubernetes#109113]
### What happened?

I was trying to understand the operation logic of the Persistent Volume controller by going through the code and I think I noticed a bug.

`syncUnboundClaim()` which syncs unbound claims:
1. Checks if the requested PV is bound to another claim.  
2. If the PV is bound to another claim, then it shall check if the binding was done by the controller or the user.
3. It should check if annotation `AnnBoundByController = "pv.kubernetes.io/bound-by-controller"` is set on the PV  that the PVC requests.

However, according to line 449 of code, the controller seems to check if the PVC / claim object has that `AnnBoundByController` annotation set:

https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L447-L456

### What did you expect to happen?

I would expect that we check if the PV has the annotation set, not the PVC, i.e.:

```diff
--- a/pkg/controller/volume/persistentvolume/pv_controller.go
+++ b/pkg/controller/volume/persistentvolume/pv_controller.go
@@ -447,7 +447,7 @@ func (ctrl *PersistentVolumeController) syncUnboundClaim(claim *v1.PersistentVol
                        } else {
                                // User asked for a PV that is claimed by someone else
                                // OBSERVATION: pvc is "Pending", pv is "Bound"
-                               if !metav1.HasAnnotation(claim.ObjectMeta, pvutil.AnnBoundByController) {
+                               if !metav1.HasAnnotation(volume.ObjectMeta, pvutil.AnnBoundByController) {
                                        klog.V(4).Infof("synchronizing unbound PersistentVolumeClaim[%s]: volume already bound to different claim by user, will retry later", claimToClaimKey(claim))
                                        claimMsg := fmt.Sprintf("volume %q already bound to a different claim.", volume.Name)
                                        ctrl.eventRecorder.Event(claim, v1.EventTypeWarning, events.FailedBinding, claimMsg)

```

Since an unbound PVC shall never have that annotation, thus the `if !metav1.HasAnnotation(claim.ObjectMeta, pvutil.AnnBoundByController)` statement  shall always evaluate to `true`, the `else` block will never be executed. We don't expect that block to be executed anyways (`THIS SHOULD NEVER HAPPEN`), but yet, the condition we check is wrong and I think that is a correctness bug. 

https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L449-L466

### How can we reproduce it (as minimally and precisely as possible)?

Alter the PersistentVolumeController to mistakenly bind a PV to another PVC. The `else` statement will not be executed.

### Kubernetes version

<details>
This is on the latest `master` branch.
</details>

### Cloud provider

<details>
Not cloud provider specific.
</details>

**Comment by Kartik494** [comment]
@gregth If we want to set the annotation on Volume instead of claim, then [`else`](https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L458) should need to modify also on the volume part instead of claim

**Comment by Kartik494** [comment]
https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L449-L460

I think else part comment is misleading as in  we are checking for `AnnBoundByController` annotation and commented for `AnnBindCompleted` 

/assign

**Comment by gregth** [comment]
I'd like to understand a bit more:
1) This [else](https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L446) part is executed in the case a `pvc.Spec.VolumeName != nil` AND the requested volume is bound to another claim. Right?
2) `syncUnboundClaim()` is called in case the claim does not have  `AnnBindCompleted`https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L266-L271
3) I wonder if there is rationale that I do not get wrt the annotation check? https://github.com/kubernetes/kubernetes/blob/1ea07d482a5ec15afac5ea837585174579fc0f57/pkg/controller/volume/persistentvolume/pv_controller.go#L447-L465

      The comment: 
      ```
      // This should never happen because someone had to remove
      // AnnBindCompleted annotation on the claim.             
      ``` 
      makes me think that this might not be a bug / typo after all, but we indeed want to check the claim. Note that the comment is in the `else` block that will get executed in case the `AnnBoundByController` **exists** on the claim but `AnnBindCompleted` **does not exist**.  

Let me know what you think, if there was any rationale that I do not get at this point.

**Comment by 12cew** [comment]
Should this issue be labeled as priority/awaiting-more-evidence or priority/backlog or priority/important-longterm?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79% accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority/awaiting-more-evidence or priority/backlog or priority/important-longterm 
Could you please tell us whether it should be labeled as priority/awaiting-more-evidence or priority/backlog or priority/important-longterm?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by Kartik494** [comment]
@gregth i am waiting for more inputs from sig storage side to proceed. Till that i am putting that on hold
/hold

**Comment by Kartik494** [comment]
@gregth Any luck on finding this bug is relevant to proceed? please let me know!
Thanks

**Comment by jsafrane** [comment]
If you look at `AnnBoundByController` description, it says:

>  AnnBoundByController annotation applies to PVs and PVCs. It indicates that
>  the binding (PV->PVC or PVC->PV) was installed by the controller. The
> absence of this annotation means the binding was done by the user (i.e.
> pre-bound).

So it's expected to be on both PVs and PVCs.

> syncUnboundClaim() which syncs unbound claims:
> 1. Checks if the requested PV is bound to another claim.
> 2. If the PV is bound to another claim, then [it shall check if the binding was done by the controller or the user]

At this point (before `[` above), the controller has a PVC without `AnnBindCompleted` + it has `pv.spec.persistentVolumeName` set + the referenced PV is already bound to another PVC.

How could this happen?

1. Either *user* created the PVC with such `pvc.spec.persistentVolumeName` and thus the controller waits for the PV to get `Available` (this is possible for recyclable volumes).
2. Or *PV controller* did set `pvc.spec.persistentVolumeName` in some previous sync. The controller stores this information in PVC annotation `AnnBoundByController`, not in PV annotations (because the PV is bound to another PVC and its annotations do not really matter).  So, `AnnBoundByController` is set on the PVC, but that means `AnnBindCompleted` should be set on it too (it's set in the same `bindClaimToVolume` function) and therefore this should not be possible. Of course, users  may delete any annotation, and that's why there is the code path.

**Comment by Kartik494** [comment]
@gregth please let us know if you agreed with inputs given on [comment](https://github.com/kubernetes/kubernetes/issues/109113#issuecomment-1230261465) , so that we can close this issue .
