### ISSUE TITLE
Client-go thread_safe_store removes still-valid values on update

### ISSUE THREAD

**Issue by MbolotSuse** [kubernetes/kubernetes#109115]
### What happened?

This was the root cause of rancher/rancher#37057.

In `thread_safe_store.go`, when `updateIndices` is called, it is given the oldVersion of an object and the newVersion of the object. It then uses the indexers `indexFunc` to calculate the old values (from the old version) and the new updated values. 

https://github.com/kubernetes/kubernetes/blob/e0ca5cfd73bd046ee5fbdef50e073842e6fbc52f/staging/src/k8s.io/client-go/tools/cache/thread_safe_store.go#L255-L298

In cases where `oldIndexValues` are size of 1, `indexValues` are of size greater than 1, and `indexValues` contain the sole value from `oldIndexValues`, the key will be deleted for the old value will be deleted and won't be re-added.

This is due to the two for loops at the end of the method which are used for optimization. When the first for loop is processed, `len(indexValues) != 1`. Because of this, the key is deleted from the index for this value.

https://github.com/kubernetes/kubernetes/blob/e0ca5cfd73bd046ee5fbdef50e073842e6fbc52f/staging/src/k8s.io/client-go/tools/cache/thread_safe_store.go#L283-L289

In the second for loop, the `len(oldIndexValues) == 1`, and for at least one of the values `value == oldIndexValues[0]`. The continue statement causes the key to not be added to the index for this value (and since the value was deleted in the prior for loop, it no longer exists in the index for this value), despite the fact that the `indexFunc` indicated that this is the desired state. 

https://github.com/kubernetes/kubernetes/blob/e0ca5cfd73bd046ee5fbdef50e073842e6fbc52f/staging/src/k8s.io/client-go/tools/cache/thread_safe_store.go#L290-L297

### What did you expect to happen?

Since `indexFunc` specified that this value was still valid for this object, the key should not be deleted from the index for this value, or it should be re-added when it is re-discovered in `indexValues`. Either way, the end state of the index should include this key in the set for the specified value.

### How can we reproduce it (as minimally and precisely as possible)?

I've created a [fork of the sample controller](https://github.com/MbolotSuse/sample-controller/tree/issue-demo) which demonstrates the issue (branch is `issue-demo`).

To use it (assuming that you have a running kubernetes cluster to use with):
1. Build the controller: `go build`.
2. Deploy the foo crd: `kubectl apply -f artifacts/examples/crd.yaml`
3. Run the controller `./sample-controller --kubeconfig $KUBECONFIG` (assumes that you have $KUBECONFIG set to the file path of your kubeconfig file).
4. Deploy an example foo with only one label: `kubectl apply -f artifacts/examples/example-foo.yaml`. Observe, in the logs of the running sample-controller, that the indexer was able to locate this foo using the indexer.
5. Update the foo to include a second label: `kubectl apply -f artifacts/examples/example-foo2.yaml`. Observe, in the logs of the running sample-controller, that the indexer was not able to locate the foo using the first key any longer,  despite the fact that the label was still on the object. 

The sample-controller fork adds an indexer for foo objects which uses the indexerFunction of `fooBySpecialLabel`. This function looks for labels that have a key with a prefix of `test.test.io` and uses their values as index keys for the foo objects. For example, if I have a `simple-foo` with a label of `test.test.io/mykey: myvalue`, the indexer will allow you to retrieve `simple-foo` using `c.foosIndexer.ByIndex(fooIndex, "myvalue")`. The controller's `syncHandler` method has been altered to just ensure that the foos can be retrieved using the indexer for all valid labels. If the controller can't retrieve foo by using the value from a valid label, then it returns an error (it tries for all valid labels).

### Anything else we need to know?

This was originally discovered in a fork of client-go that we maintain. After we reverted the changes introduced by #105234, our issues stopped occurring.

### Kubernetes version

N/A - This was introduced in #105234 and appears to be in all versions of the client v0.23+.

### Cloud provider

N/A - issue is with client-go

**Comment by wojtek-t** [comment]
Thanks for reporting the issue.
https://github.com/kubernetes/kubernetes/pull/109137 will address this issue

**Comment by wojtek-t** [comment]
Reopening - since we need to cherrypick back to 1.23

**Comment by wojtek-t** [comment]
Cherrypick is merged - closing.
