### ISSUE TITLE
Error: failed to create containerd task: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: openat2 /sys/fs/cgroup/kubepods/burstable/pod03f3a69f-82ff-4368-a1aa-16ddaf74ac22/xmrig/memory.max: no such file or directory: unknown 

### ISSUE THREAD

**Issue by Pastor-David** [kubernetes/kubernetes#109105]
/**sys/fs/cgroup/kubepods/burstable**/pod03f3a69f-82ff-4368-a1aa-16ddaf74ac22/xmrig/memory.max: no such file or directory
The path should be /**sys/fs/cgroup/devices/kubepods/burstable**/pod...
Where do i update the path to include the /devices/ in the path?
/sig kubernetes

**Comment by Pastor-David** [comment]
this is my first post .. I dont know how to add sigs to my post...
Everything is up to date and the newest Kubernetes.
I would not mind rephrasing the title to:
Problems with Kubernetes setting cgroup config for procHooks WRONG PATH
perhaps if you explain how to format the message properly,(ie sigs and
anything else I need to know) we can delete this one and re-submit in a
better format

**Comment by ehashman** [comment]
@Pastor-David if you fill out https://github.com/kubernetes/kubernetes/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.yaml it will walk you through all the details required in a bug report.

**Comment by SergeyKanzhelev** [comment]
/close

please re-file the bug using the template

**Comment by Pastor-David** [comment]
Seeking a secluded location for long term Alchemical Research.
Goal is to make the Highest Quality Elixirs for Healing and Raising
Frequency of Body, Mind and Soul. Being Dedicated to Quality and Potency as
if making it for The Creator!
And to make the materia prima.
Will You Be One of My Benefactors?
For God's Glory!
David Jonsson
