### ISSUE TITLE
`StatefulSetStatus` attribute `availableReplicas` set to required by mistake?

### ISSUE THREAD

**Issue by ca-scribner** [kubernetes/kubernetes#109210]
### What happened?

Looking at the [swagger specifications](https://github.com/kubernetes/kubernetes/blob/17381762dd6caafe72cda9e9c39e42405391f1e9/api/openapi-spec/v3/apis__apps__v1_openapi.json#L1207) for `StatefulSetStatus`, it defines `availableReplicas` as a required attribute.  But looking at the [description](https://github.com/kubernetes/kubernetes/blob/17381762dd6caafe72cda9e9c39e42405391f1e9/api/openapi-spec/v3/apis__apps__v1_openapi.json#L1147) of `availableReplicas`, it states `...This is a beta field and enabled/disabled by StatefulSetMinReadySeconds feature gate`.  Should this in fact be a required attribute?  

I come about this from using [lightkube](https://github.com/gtsystem/lightkube/), a python package that generates models from the swagger definitions and thus builds a `StatefulSetStatus` that requires an attribute that is not enabled.

### What did you expect to happen?

That only truly required attributes be required in the swagger definition

### How can we reproduce it (as minimally and precisely as possible)?

Reproduction is not applicable as this is an issue with a spec

### Kubernetes version

Appeared in 1.22 (I believe) and affects current versions.  Does not affect 1.21

### Cloud provider

n/a

**Comment by neolit123** [comment]
alpha:
https://github.com/kubernetes/kubernetes/pull/100842
https://github.com/kubernetes/kubernetes/pull/100842#pullrequestreview-667129670
has `+optional` that is planned for removal in beta.

beta:
https://github.com/kubernetes/kubernetes/pull/104045/files
removes the `+optional`

this might be a question whether feature gate controlled fields must remain `+optional` until the feature gate is removed.
old feature gates graduations to beta enabled a feature by default.
related to https://github.com/kubernetes/kubernetes/issues/108279

/kind documentation
/sig apps

**Comment by liggitt** [comment]
new fields added to existing types must always be marked as +optional, since clients are not required to specify them

**Comment by liggitt** [comment]
please open a PR adding back the +optional tag, regenerate openapi, and open picks back to 1.23 and 1.22
