### ISSUE TITLE
Several in-tree volumes tests started failing with nil pointer errors

### ISSUE THREAD

**Issue by olemarkus** [kubernetes/kubernetes#109264]
### What happened?

The following test failures started happening on 30th March:
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Inline-volume (default fs)] volumes should allow exec of files on the volume
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Inline-volume (default fs)] volumes should store data
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Inline-volume (ext4)] volumes should allow exec of files on the volume
* Kubernetes e2e suite.[sig-storage] In-tree Volumes [Driver: aws] [Testpattern: Inline-volume (ext4)] volumes should store data

See https://testgrid.k8s.io/kops-versions#kops-aws-k8s-latest

This seems related to the changes in #108693

kubelet fails with the following:
```
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: goroutine 14084 [running]:
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.RecoverFromPanic(0xc001a3ce78)
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:159 +0x6b
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: panic({0x3d57c80, 0x723c380})
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         /usr/local/go/src/runtime/panic.go:844 +0x258
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: k8s.io/kubernetes/pkg/volume/util/operationexecutor.(*operationGenerator).GenerateVerifyControllerAttachedVolumeFunc.func1()
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         pkg/volume/util/operationexecutor/operation_generator.go:1490 +0x10d
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: k8s.io/kubernetes/pkg/volume/util/types.(*GeneratedOperations).Run(0xc00184be00)
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         pkg/volume/util/types/types.go:79 +0x1c2
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run.func1()
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:190 +0xf4
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]: created by k8s.io/kubernetes/pkg/volume/util/nestedpendingoperations.(*nestedPendingOperations).Run
Apr 03 09:58:35 i-03aea5d1b38e4c44e kubelet[4338]:         pkg/volume/util/nestedpendingoperations/nestedpendingoperations.go:185 +0x8ca
```

### What did you expect to happen?

Tests passing

### How can we reproduce it (as minimally and precisely as possible)?

See the e2e logs above

### Kubernetes version

<details>

Latest CI build

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
EBS CSI driver 1.5.0
</details>

**Comment by gnufied** [comment]
@olemarkus not having debugging kops builds for awhile, are kubelet logs attached in prow? I don't see them...

**Comment by gnufied** [comment]
Spoke with @olemarkus offline. It looks like we don't have kubelet logs captured in these tests. I need complete kubelet logs to make sense of these errors because testgrid shows inline volume tests as failing and code in question should not be called or inline volumes (because they can not be expanded). If that code fails, it would have been failing before too.

I will wait for logs from @olemarkus and in the meanwhile try and see if I can reproduce these failures in single node AWS cluster setup that I can build manually.

**Comment by dims** [comment]
thanks @gnufied

**Comment by gnufied** [comment]
Looks like this is happening for inline volumes if CSI migration is enabled for them. We construct a "fake" `PersistentVolume` object on the fly for migration enabled plugins even though volume is inline, which is causing this condition to fail. It should be simple fix.

**Comment by gnufied** [comment]
opened https://github.com/kubernetes/kubernetes/pull/109290 to fix the problem. The code change is just one line but has tests.
