### ISSUE TITLE
failed to verify JWS signature of received cluster info object, can't trust this API Server

### ISSUE THREAD

**Issue by fusida** [kubernetes/kubernetes#109233]
### What happened?

we usually find kubeadm join has the problem:
failed to verify JWS signature of received cluster info object, can't trust this API Server
or
could not find a JWS signature in the cluster-info ConfigMap for token ID
when we update cluster-info or bootstrap-token, the controller-manager didn't update the cluster-info.data.jws-token.

### What did you expect to happen?

kubeadm join:
Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server

### How can we reproduce it (as minimally and precisely as possible)?

pkg/controller/bootstrap:

func (e *Signer) serviceConfigMapQueue() {
	key, quit := e.syncQueue.Get()
	if quit {
		return
	}
	defer e.syncQueue.Done(key)

	e.signConfigMap()     // if fail, we need requeue
}

// return err and try again
func (e *Signer) updateConfigMap(cm *v1.ConfigMap) {
	_, err := e.client.CoreV1().ConfigMaps(cm.Namespace).Update(context.TODO(), cm, metav1.UpdateOptions{})
	if err != nil && !apierrors.IsConflict(err) && !apierrors.IsNotFound(err) {
		klog.V(3).Infof("Error updating ConfigMap: %v", err)
	}
}

### Anything else we need to know?

found in 1.20.x, 1.22.x and 1.24.x.

### Kubernetes version

1.20.x
1.22.x
1.24.x

### Cloud provider

<details>
any where
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig cluster-lifecycle
/triage needs-information

I saw a few users reporting this on slack recently.
We are not seeing this in the kubeadm e2e tests.
JWS are always populated and valid.

> How can we reproduce it (as minimally and precisely as possible)?

You seem to show source code, but what are the actual reproduction steps?
Any logs from controller manager?

**Comment by fusida** [comment]
> /sig cluster-lifecycle /triage needs-information
> 
> I saw a few users reporting this on slack recently. We are not seeing this in the kubeadm e2e tests. JWS are always populated and valid.
> 
> > How can we reproduce it (as minimally and precisely as possible)?
> 
> You seem to show source code, but what are the actual reproduction steps? Any logs from controller manager?

the two case we have saw：
1、Accoring to the apiserver log, can find the kube-public/cluster-info have been reproduction by operator, but can not find controller manager update kube-public/cluster-info. What's more there are nothing log in controller manager, and the

**Comment by fusida** [comment]
> > /sig cluster-lifecycle /triage needs-information
> > I saw a few users reporting this on slack recently. We are not seeing this in the kubeadm e2e tests. JWS are always populated and valid.
> > > How can we reproduce it (as minimally and precisely as possible)?
> > 
> > 
> > You seem to show source code, but what are the actual reproduction steps? Any logs from controller manager?
> 
> the two case we have saw： 1、could not find a JWS signature in the cluster-info ConfigMap Accoring to the apiserver log, can find the kube-public/cluster-info have been changed by the operator, but can not find controller-manager update kube-public/cluster-info. What's more there are nothing log about controller-manager change this configmap until we restart controller-manager then it recover. After restart, there are have log about this configmap on apiserver and controller-manager. （Our operation program will modify the number of apiserver replicas from 4 to 2 and from 2 to 4, and will regenerate kube-public/cluster-info, about 3 times a day. Only find problem one time. ）
> 
> 2、failed to verify JWS signature of received cluster info object, can't trust this API Server Looking at the logs of the last month, I did not find that the logs about kube-public/cluster-info are in apiserver and controller-manager.

**Comment by fusida** [comment]
> 

1、we scale up and down apiserver because node-pools scale up and down. 
2、i also don't think there is a kubeadm bug here, i think it's controller manager problem. 
the controller manager didn't update jws-token in kube-public/cluster-info, util we restart it.
3、can we just retry, when update fail?
pkg/controller/bootstrap:

func (e *Signer) serviceConfigMapQueue() {
  key, quit := e.syncQueue.Get()
  if quit {
    return
  }
  defer e.syncQueue.Done(key)

  e.signConfigMap()     // if fail, we need requeue?
}

// return err and try again
func (e *Signer) updateConfigMap(cm *v1.ConfigMap) {
  ……
  _, err := e.client.CoreV1().ConfigMaps(cm.Namespace).Update(context.TODO(), cm, metav1.UpdateOptions{})
  if err != nil && !apierrors.IsConflict(err) && !apierrors.IsNotFound(err) {
    klog.V(3).Infof("Error updating ConfigMap: %v", err)
  }
}

**Comment by neolit123** [comment]
Ideally actions against the config map should eventually result in a config map that has the desired state (reconciliation). So the code should be in the lines of - get cm, check if update is needed, update or exit, repeat. If that is not how it works, maybe there are bugs...I don't think it should retry on API calls.

Would you like to help us by working on the fix?
We are in code freeze for 1.24, currently through. 

Also we might want to add e2e test for this in:
https://github.com/kubernetes/kubernetes/tree/master/test/e2e/lifecycle/bootstrap

**Comment by fusida** [comment]
> Ideally actions against the config map should eventually result in a config map that has the desired state (reconciliation). So the code should be in the lines of - get cm, check if update is needed, update or exit, repeat. If that is not how it works, maybe there are bugs...I don't think it should retry on API calls.
> 
> Would you like to help us by working on the fix (PR)? We are in code freeze for 1.24, currently through.
> 
> Also we might want to add e2e test for this in: https://github.com/kubernetes/kubernetes/tree/master/test/e2e/lifecycle/bootstrap

now we add monitor to verify jws-token, and find some k8s cluster have the problem. then we change config map or restart controller manager can fix it. so it think it need retry or requeue to be reconciled

**Comment by fusida** [comment]
@neolit123 
we find jws-token verify fail, until we change configmap to cause controller work, then jws-token change right.
```bash
kubectl -n kube-public get cm cluster-info -o yaml | grep jws

// do not change kubeconfig, just remove one char in jws-token
kubectl -n kube-public edit cm cluster-info 

kubectl -n kube-public get cm cluster-info -o yaml | grep jws
// two jws-token unequal
```
i think controller manager retry to update configmap can fix this problem.
but there may have any other factor cause this problem. it may be good to run an e2e test, but some online clusters have incorrect jws-tokens that cause kubeadm join to fail. this is a sporadic problem and can only be found when executing kubeadm join, our logs are not kept for so long .

**Comment by neolit123** [comment]
The problem here is that we still have no explanation on why it happens and
how to reproduce it...It seems that the reconciliation logic is not ideal.

If you'd like to send a PR fix I can help reviewing it. We can then work on
an e2e test.

**Comment by fusida** [comment]
> The problem here is that we still have no explanation on why it happens and how to reproduce it...It seems that the reconciliation logic is not ideal. If you'd like to send a PR fix I can help reviewing it. We can then work on an e2e test.

#109389

**Comment by enj** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/109389#issuecomment-1121312456
