### ISSUE TITLE
[sig-node] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod] when we need to admit a critical pod [Flaky] should be able to create and delete a critical pod

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/kubernetes#109296]
### Which jobs are failing?

sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky

### Which tests are failing?

E2eNode Suite.[sig-node] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod] when we need to admit a critical pod [Flaky] should be able to create and delete a critical pod

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1511063186235723776

### Since when has it been failing?

According to the [testgrid](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky), it has been failing since the start of history (03/20/2022)

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky

### Reason for failure (if possible)

E2eNode Suite: [sig-node] CriticalPod [Serial] [Disruptive] [NodeFeature:CriticalPod] when we need to admit a critical pod [Flaky] should be able to create and delete a critical pod expand_less | 12s

```
{ Failure test/e2e_node/critical_pod_test.go:45 Unexpected error:     <*errors.StatusError \| 0xc000255180>: {         ErrStatus: {             TypeMeta: {Kind: "", APIVersion: ""},             ListMeta: {                 SelfLink: "",                 ResourceVersion: "",                 Continue: "",                 RemainingItemCount: nil,             },             Status: "Failure",             Message: "pods \"static-critical-pod\" not found",             Reason: "NotFound",             Details: {                 Name: "static-critical-pod",                 Group: "",                 Kind: "pods",                 UID: "",                 Causes: nil,                 RetryAfterSeconds: 0,             },             Code: 404,         },     }     pods "static-critical-pod" not found occurred test/e2e/framework/pods.go:107}
```

### Relevant SIG(s)

/sig node

**Comment by ehashman** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/103690 which rotted closed.

/triage accepted

**Comment by pacoxu** [comment]
### Failure cluster [1212f068f3acb53d8309](https://go.k8s.io/triage#1212f068f3acb53d8309)

##### Error text:
```
[FAILED] Timed out after 300.000s.
The function passed to Eventually returned the following error:
pods "static-critical-pod" not found
    <framework.transientError>: {
        error: <*errors.StatusError | 0xc000dc0500>{
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "pods \"static-critical-pod\" not found",
                Reason: "NotFound",
                Details: {
                    Name: "static-critical-pod",
                    Group: "",
                    Kind: "pods",
                    UID: "",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 404,
            },
        },
    }
In [It] at: test/e2e/framework/pod/pod_client.go:106 @ 02/04/23 14:26:34.666

```
#### Recent failures:
[2023/2/9 12:33:34 ci-crio-cgroupv1-node-e2e-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1623540570313986048)
[2023/2/9 10:33:33 ci-crio-cgroupv1-node-e2e-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1623510371698479104)
[2023/2/9 08:32:40 ci-crio-cgroupv1-node-e2e-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1623479945659420672)
[2023/2/9 06:31:49 ci-crio-cgroupv1-node-e2e-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1623449502591488000)
[2023/2/9 04:30:42 ci-crio-cgroupv1-node-e2e-flaky](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-flaky/1623419052036722688)


/kind failing-test


/sig node

This seems to be raised recently again.

**Comment by SergeyKanzhelev** [comment]
@rphillips do you still have time for this or should be unassigned?

**Comment by saschagrunert** [comment]
I have a fix in https://github.com/kubernetes/kubernetes/pull/119035
