### ISSUE TITLE
scheduler: enabled plugins not logged during initialization

### ISSUE THREAD

**Issue by ingvagabund** [kubernetes/kubernetes#109285]
Nowadays, when the kube-scheduler is initialized, the provided component config (via `--config` flag) is logged. E.g.
```
I0404 08:35:16.471898       1 configfile.go:96] Using component config
-------------------------Configuration File Contents Start Here---------------------- 
apiVersion: kubescheduler.config.k8s.io/v1beta3
clientConnection:
  acceptContentTypes: ""
  burst: 100
  contentType: application/vnd.kubernetes.protobuf
  kubeconfig: /etc/kubernetes/static-pod-resources/configmaps/scheduler-kubeconfig/kubeconfig
  qps: 50
enableContentionProfiling: true
enableProfiling: true
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: true
  leaseDuration: 2m17s
  renewDeadline: 1m47s
  resourceLock: configmapsleases
  resourceName: kube-scheduler
  resourceNamespace: NS
  retryPeriod: 26s
parallelism: 16
percentageOfNodesToScore: 0
podInitialBackoffSeconds: 1
podMaxBackoffSeconds: 10
profiles:
- pluginConfig:
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: DefaultPreemptionArgs
      minCandidateNodesAbsolute: 100
      minCandidateNodesPercentage: 10
    name: DefaultPreemption
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      hardPodAffinityWeight: 1
      kind: InterPodAffinityArgs
    name: InterPodAffinity
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: NodeAffinityArgs
    name: NodeAffinity
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: NodeResourcesBalancedAllocationArgs
      resources:
      - name: cpu
        weight: 1
      - name: memory
        weight: 1
    name: NodeResourcesBalancedAllocation
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: NodeResourcesFitArgs
      scoringStrategy:
        resources:
        - name: cpu
          weight: 1
        - name: memory
          weight: 1
        type: LeastAllocated
    name: NodeResourcesFit
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      defaultingType: System
      kind: PodTopologySpreadArgs
    name: PodTopologySpread
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      bindTimeoutSeconds: 600
      kind: VolumeBindingArgs
    name: VolumeBinding
  plugins:
    bind: {}
    filter: {}
    multiPoint:
      enabled:
      - name: PrioritySort
        weight: 0
      - name: NodeUnschedulable
        weight: 0
      - name: NodeName
        weight: 0
      - name: TaintToleration
        weight: 3
      - name: NodeAffinity
        weight: 2
      - name: NodePorts
        weight: 0
      - name: NodeResourcesFit
        weight: 1
      - name: VolumeRestrictions
        weight: 0
      - name: EBSLimits
        weight: 0
      - name: GCEPDLimits
        weight: 0
      - name: NodeVolumeLimits
        weight: 0
      - name: AzureDiskLimits
        weight: 0
      - name: VolumeBinding
        weight: 0
      - name: VolumeZone
        weight: 0
      - name: PodTopologySpread
        weight: 2
      - name: InterPodAffinity
        weight: 2
      - name: DefaultPreemption
        weight: 0
      - name: NodeResourcesBalancedAllocation
        weight: 1
      - name: ImageLocality
        weight: 1
      - name: DefaultBinder
        weight: 0
    permit: {}
    postBind: {}
    postFilter: {}
    preBind: {}
    preFilter: {}
    preScore: {}
    queueSort: {}
    reserve: {}
    score: {}
  schedulerName: default-scheduler
```

Unfortunately, the printed config does not mention which plugins are enabled besides those which are explicitly mentioned in the configuration (through enabled and disabled fields). A developer can determine all the enabled plugins based on taking all plugins enabled by default minus those which are explicitly disabled. However, the same can not be told about a "normal" user. Given the enabled plugins are known only to the framework, it is not trivial to "just" print the enabled plugins as part of the component config. Currently, the code only updates the printed component config to display the `pluginConfig` part (via `FrameworkCapturer`).

I am reporting the issue in order start a discussion on how to better let a user know which plugins are enabled by default. E.g. by extending the `FrameworkCapturer` and allowing to print the enabled plugins as part of the component config. I.e. by explicitly setting the enabled plugins.

**Comment by ingvagabund** [comment]
By all means once there's an agreement on the approach :)

**Comment by novahe** [comment]
> I am reporting the issue in order start a discussion on how to better let a user know which plugins are enabled by default. E.g. by extending the FrameworkCapturer and allowing to print the enabled plugins as part of the component config. I.e. by explicitly setting the enabled plugins.

hi@ingvagabund, after reading the code, I think of two feasible solutions:
**Option 1:**
extending the FrameworkCapturer (as you said)
[PluginConfig](https://github.com/kubernetes/kubernetes/blob/c13d3369d588bf59eec8812327e421f1ce47c87a/pkg/scheduler/apis/config/types.go#L191) extend `Enabled`, which marks to enable the plugin
```go
type PluginConfig struct {
	// Name defines the name of plugin being configured
	Name string
	// Enabled marks to enable the plugin
	Enabled bool
	// Args defines the arguments passed to the plugins at the time of initialization. Args can have arbitrary structure.
	Args runtime.Object
}
```
Configuration File Contents print:
```yaml
profiles:
- pluginConfig:
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: DefaultPreemptionArgs
      minCandidateNodesAbsolute: 100
      minCandidateNodesPercentage: 10
    name: DefaultPreemption
    enable: true            # look here
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      hardPodAffinityWeight: 1
      kind: InterPodAffinityArgs
    name: InterPodAffinity
    enable: true             # look here
  - args:
      apiVersion: kubescheduler.config.k8s.io/v1beta3
      kind: NodeAffinityArgs
    name: NodeAffinity
    enable: false             # look here
```
**Option 2:**
Print [Registry map](https://github.com/kubernetes/kubernetes/blob/c13d3369d588bf59eec8812327e421f1ce47c87a/pkg/scheduler/framework/runtime/registry.go#L70) after initializing the framework.

In my case, I prefer option Option 1.
You have better ideas, welcome to discuss together, look forward to your reply, thx

**Comment by kerthcet** [comment]
Poor thoughts, we should not introduce new fields just for documents. And we do have documents for users to refer to https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins. What a ` normal user` means? An ops staff?

**Comment by ingvagabund** [comment]
> And we do have documents for users to refer to https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins.

Works fine for the kube-scheduler. But not anymore when [out of tree plugins](https://github.com/kubernetes-sigs/scheduler-plugins) are included.

> What a normal user means? An ops staff?

That's why I put the "normal" into quotes. Anyone who's not so familiar with the documentation and/or the code base to deduce which plugins are enabled.

**Comment by sanposhiho** [comment]
I think just adding an info log when initializing each plugin is enough.
https://github.com/kubernetes/kubernetes/blob/c13d3369d588bf59eec8812327e421f1ce47c87a/pkg/scheduler/framework/runtime/framework.go#L296

**Comment by xrisaD** [comment]
Is it still open? I could try that

**Comment by yuv00191** [comment]
@novahe  are you working on this `issue... please let me know.

If yes, I would love to learn about this issue and its possible solutions in detail.
that is - If you can share about.

sincerely,

**Comment by denstorti** [comment]
Hi @ingvagabund, @sanposhiho  

For logging purposes, I thought about using the `completedProfiles.Plugins` in 
[`kubernetes/cmd/kube-scheduler/app/server.go`](https://github.com/kubernetes/kubernetes/blob/9ad41812e58c12dc9666b1172d276c46a70aa5c5/cmd/kube-scheduler/app/server.go#L350) 
or `outputProfile.Plugins` around
https://github.com/kubernetes/kubernetes/blob/9ad41812e58c12dc9666b1172d276c46a70aa5c5/pkg/scheduler/framework/runtime/framework.go#L367 
to do simple logging of what's enabled/disabled.

What are your thoughts on that?

Another question, is it expected that out of tree plugins are enabled explicitly in the config to be applied (default would be disabled)? 
In my tests with custom scheduler below
```
func main() {
...
	command := app.NewSchedulerCommand(
		app.WithPlugin(loadvariationriskbalancing.Name, loadvariationriskbalancing.New),
		app.WithPlugin(targetloadpacking.Name, targetloadpacking.New),
	)
...
}

```
the plugin `LoadVariationRiskBalancing` was omitted from `config` and did not end up in the final profile.Plugins object, I am not sure if it was applied or not to the scheduler.

Any guidance appreciated,

Cheers.

**Comment by ingvagabund** [comment]
> Another question, is it expected that out of tree plugins are enabled explicitly in the config to be applied (default would be disabled)?
> the plugin LoadVariationRiskBalancing was omitted from config and did not end up in the final profile.Plugins object, I am not sure if it was applied or not to the scheduler.

This will require some digging to get to the bottom of what is and where it is propagated. The last time I checked the `options.captureProfile` was the closest way to propagate the list of enabled/disabled plugins outside for printing.

I suggest to write few unit tests and see how the entire initialization is propagated and based on that decide which bits can be refactored/changed so the necessary information is propagated outside.

**Comment by denstorti** [comment]
I opened the draft PR https://github.com/kubernetes/kubernetes/pull/110387, centralising the logic to discover plugins enabled and disabled inside the block for the captureProfile callback:
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/runtime/framework.go#L359-L368

Any suggestions if that would be better to place the logging inside the captureProfile callback:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/server.go#L345

**Comment by halegreen** [comment]
Hi all, I'd like to give it a try. Please let me know if you far ahead on it  @denstorti 

/assign

**Comment by Sajiyah-Salat** [comment]
Hello, I would like to work on this issue. I am currently preparing for my CKA exam and I would like to know if @denstorti and @halegreen done some work on this issue. I am active learner and i would prove to be beneficial if you guys just explain me this issue in more details. Thank you

**Comment by Prateek462003** [comment]
Hey @sanposhiho can u please review the changes i made
