### ISSUE TITLE
TestValidateCronJob cant pass in macos

### ISSUE THREAD

**Issue by Abirdcfly** [kubernetes/kubernetes#109220]
### What happened?

```bash
$ go test ./pkg/apis/batch/validation -run  TestValidateCronJob

--- FAIL: TestValidateCronJob (0.01s)
    validation_test.go:1355: expected failure for spec.timeZone: Invalid value: "AMERICA/new_york": unknown time zone AMERICA/new_york
    validation_test.go:1378: expected failure for spec.timeZone: Invalid value: "AMERICA/new_york": unknown time zone AMERICA/new_york
FAIL
FAIL    k8s.io/kubernetes/pkg/apis/batch/validation     0.028s
FAIL

```

### What did you expect to happen?

test withnot FAIL

### How can we reproduce it (as minimally and precisely as possible)?

In a macos.
do `make test` or `go test ./pkg/apis/batch/validation -run  TestValidateCronJob`

### Anything else we need to know?

https://github.com/golang/go/issues/21512  golang upstrem disscusion.

We use time.LoadLocation to validate time_zone setting in object spec like cronjob.(It is ok)

We also add a test try to validate `AMERICA/new_york` is not a crroct value.

This test is not true sometimes, for example, in default macos this is a true time_zone value.(maybe also true in other case insensitive os, but I have no device to try)

At least we should get the test to pass on macos, I hope.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here

Darwin MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Abirdcfly** [comment]
/sig test 
(I guess)

**Comment by Abirdcfly** [comment]
/sig testing
(I guess)

**Comment by dims** [comment]
see https://github.com/golang/go/issues/21512

**Comment by Abirdcfly** [comment]
I was very surprised to find that this error only occurs on darwin, and does not occur on windows, although windows is also case-sensitive by default.

When using `time.LoadLocation("AMERICA/new_york")`, windows finally use `runtime.GOROOT() + "/lib/time/zoneinfo.zip"` (see https://github.com/golang/go/blob/go1.18/src/time/zoneinfo_windows.go#L14 ), but darwin and linux have more choices (see https://github.com/golang/go/blob/go1.18/src/time/zoneinfo_unix.go#L21 ) they will first try `/usr/share/zoneinfo/`, using the `readFile` method, which will call the system's open method to open `/usr/share/zoneinfo/AMERICA/new_york`, because darwin is case-insensitive by default, and this operation will succeed.
