### ISSUE TITLE
Set Pod as "related" on Job's SuccessfulCreate event

### ISSUE THREAD

**Issue by johnflavin-fw** [kubernetes/kubernetes#109378]
### What happened?

Create a Job and watch its events. When a Pod is created from the Job's template, you'll receive an event with `reason: "SuccessfulCreate"`. This event has information about the Job in its `regarding` field, but nothing in its `related` field.

**Example**
<details>

```json

{
  "metadata": {
    "name": "testjob4gfgf.16e3ae253f4ff5bf",
    "namespace": "myns",
    "uid": "e35dbd89-57ca-4f4e-a08c-e922dc1ef3d7",
    "resourceVersion": "112848",
    "creationTimestamp": "2022-04-07T17:42:43Z",
    "managedFields": [
      {
        "manager": "kube-controller-manager",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2022-04-07T17:42:43Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:count":{},"f:firstTimestamp":{},"f:involvedObject":{},"f:lastTimestamp":{},"f:message":{},"f:reason":{},"f:source":{"f:component":{}},"f:type":{}}
      }
    ]
  },
  "eventTime": null,
  "reason": "SuccessfulCreate",
  "regarding": {
    "kind": "Job",
    "namespace": "myns",
    "name": "testjob4gfgf",
    "uid": "8ff828ac-fe3d-4186-baf6-32ae20f23635",
    "apiVersion": "batch/v1",
    "resourceVersion": "112845"
  },
  "note": "Created pod: testjob4gfgf--1-mfcfb",
  "type": "Normal",
  "deprecatedSource": {
    "component": "job-controller"
  },
  "deprecatedFirstTimestamp": "2022-04-07T17:42:43Z",
  "deprecatedLastTimestamp": "2022-04-07T17:42:43Z",
  "deprecatedCount": 1
}
```

</details>

### What did you expect to happen?

I expected the event's `related` field would be populated by an object with information about the Pod that was created. That seems like the perfect use case for `related` according to the [Event API reference](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/event-v1/#Event):

> **related** ([ObjectReference](https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-reference/#ObjectReference))
> related is the optional secondary object for more complex actions. E.g. _when regarding object triggers a creation_ or deletion _of related object_.
> (Emphasis mine)

### How can we reproduce it (as minimally and precisely as possible)?

Create a Job and watch its events. When a Pod is created, an event will be produced with `reason: "SuccessfulCreate"`.

I was monitoring for all Job events through `curl` (via `kubectl proxy`) like so:

```
curl -s -X GET http://localhost:8080/apis/events.k8s.io/v1/namespaces/myns/events\?fieldSelector=regarding.kind%3DJob\&watch=true
```

Here's an example Job that I have used, but I think it could really be just about any Job.
<details>

```yaml

apiVersion: batch/v1
kind: Job
metadata:
  generateName: test
  namespace: myns
  labels:
    test: test
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: test
        image: busybox:latest
        command: ["/bin/sh",  "-c"]
        args: ["echo hello world"]
      restartPolicy: Never
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

None, local installation with Docker Desktop

### OS version

<details>

```console
# On Linux (within docker VM):
$ cat /etc/os-release
PRETTY_NAME="Docker Desktop"
$ uname -a
Linux docker-desktop 5.10.104-linuxkit #1 SMP PREEMPT Wed Mar 9 19:01:25 UTC 2022 aarch64 Linux
```

</details>

### Install tools

<details>
Docker desktop
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
IMO:
/remove-kind bug
/kind feature

**Comment by johnflavin-fw** [comment]
> /sig apps
> /remove-sig api-machinery

@sftim Why this change? I don't see how what I've reported relates to the Apps SIG since it isn't about running any application. (Caveat: I'm totally new to kubernetes and its SIGs, so please forgive me if I misunderstand what the SIGs are for or who does what. Might take a while for me to figure out how things work.)

**Comment by sftim** [comment]
The [Job](k8s.io/docs/reference/kubernetes-api/workload-resources/job-v1/) API is the responsibility of [SIG Apps](https://github.com/kubernetes/community/tree/master/sig-apps). Providing an underlying framework for different APIs to exist is [SIG API Machinery](https://github.com/kubernetes/community/tree/master/sig-api-machinery)'s main purpose.

Jobs _are_ used for running applications, and that's why SIG Apps look after that API.
