### ISSUE TITLE
node-kubelet-serial-crio job is failing/erroring

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kubernetes#109317]
### Which jobs are failing?

node-kubelet-serial-crio: https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio&show-stale-tests=

### Which tests are failing?

Tests fail to run.

### Since when has it been failing?

Since 03/23. First failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1506730409776386048

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio&show-stale-tests=

### Reason for failure (if possible)

Have not yet investigated.

### Anything else we need to know?

/cc @saschagrunert 

could this be related to the work you're doing injecting SSH keys? IIRC this job runs on the Google, not prow community cluster

### Relevant SIG(s)

/sig node

**Comment by ehashman** [comment]
Suspect this might have been https://github.com/kubernetes/test-infra/pull/25735 given the timing. Let's see if moving this job to the other cluster fixes it.

**Comment by ehashman** [comment]
/priority important-soon
/triage accepted

not applying milestone, should be unnecessary

**Comment by ehashman** [comment]
Still failing :\

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1512112999358271488

/reopen

**Comment by SergeyKanzhelev** [comment]
/close 

not failing any longer
