### ISSUE TITLE
Unable to update openapi spec on a M1 machine 

### ISSUE THREAD

**Issue by iamNoah1** [kubernetes/kubernetes#109390]
### What happened?

Following [this](https://kubernetes.io/docs/contribute/generate-ref-docs/contribute-upstream/) page, I was trying to generate API docs after updating the comments for IngressClassName. 

The process of generating the docs includes running `./hack/update-openapi-spec.sh` which failed on a M1 machine. The error message is the following: `.../kubernetes/_output/local/bin/darwin/arm64/kube-apiserver: No such file or directory`.

### What did you expect to happen?

I expected to be able to generate the docs on my M1 machine or at least to have an information that it does not work on a M1. 

### How can we reproduce it (as minimally and precisely as possible)?

Make changes on for example: `staging/src/k8s.io/api/networking/v1/types.go` and try to run `./hack/update-openapi-spec.sh` on a M1 machine

### Kubernetes version

not applicable

### Cloud provider

not applicable

### OS version

<details>

```console
MacOS: 
Darwin  20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@iamNoah1 can you please try `make kube-apiserver` and re-run the script?

**Comment by iamNoah1** [comment]
@dims unfortunately no change. It is only making kube-apiserver for `darwin/amd64`: `+++ [0408 15:36:20] Building go targets for darwin/amd64
    k8s.io/kubernetes/hack/make-rules/helpers/go2make (non-static)`

**Comment by dims** [comment]
```
[dims@dims-m1-7634 09:25] ~/go/src/k8s.io/kubernetes ⟩ make kube-apiserver
Makefile.generated_files:61: .make/go-pkgdeps.mk: No such file or directory
+++ [0408 09:25:41] Building go targets for darwin/arm64
    k8s.io/kubernetes/hack/make-rules/helpers/go2make (non-static)
+++ [0408 09:25:50] Building go targets for darwin/arm64
    k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen (non-static)
+++ [0408 09:25:52] Generating prerelease lifecycle code for       27 targets
+++ [0408 09:25:53] Building go targets for darwin/arm64
    k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/deepcopy-gen (non-static)
+++ [0408 09:25:55] Generating deepcopy code for      237 targets
+++ [0408 09:25:58] Building go targets for darwin/arm64
    k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/defaulter-gen (non-static)
+++ [0408 09:25:59] Generating defaulter code for       93 targets
+++ [0408 09:26:02] Building go targets for darwin/arm64
    k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/conversion-gen (non-static)
+++ [0408 09:26:04] Generating conversion code for      130 targets
+++ [0408 09:26:15] Building go targets for darwin/arm64
    k8s.io/kubernetes/vendor/k8s.io/kube-openapi/cmd/openapi-gen (non-static)
+++ [0408 09:26:18] Generating openapi code for KUBE
+++ [0408 09:26:26] Generating openapi code for AGGREGATOR
+++ [0408 09:26:27] Generating openapi code for APIEXTENSIONS
+++ [0408 09:26:28] Generating openapi code for CODEGEN
+++ [0408 09:26:28] Generating openapi code for SAMPLEAPISERVER
+++ [0408 09:26:29] Building go targets for darwin/arm64
    k8s.io/kubernetes/cmd/kube-apiserver (static)```

**Comment by dims** [comment]
There's probably something wrong in your environment @iamNoah1 ?

**Comment by iamNoah1** [comment]
@dims apparently. Found the issue on layer 8 ^^. I installed golang for amd macs on my machine. Crazy that it worked. After installing the correct golang version everything works :)

**Comment by dims** [comment]
LOL ok @iamNoah1 :)
