### ISSUE TITLE
e2e framework sub-packages should not import the core framework package to avoid circular imports

### ISSUE THREAD

**Issue by kidlj** [kubernetes/kubernetes#109391]
### What would you like to be added?

1. What is e2e framework and how it works?

The e2e tests in Kubernetes are built atop of [Ginkgo](http://onsi.github.io/ginkgo/), where the core framework package(`e2e/framework`) sits in the central to register `BeforeEach` and `AfterEach` action for each test case, like setting up a K8s clientset, creating a separate namespace for each test case, dumping the namespace info for a failed test case, or gathering test metrics. Thus we can ensure each test case having the same bootstrap and cleanup actions, without repeating ourself. 

2. What are e2e sub-packages?

Historically, the core e2e framework was a huge package itself. Then several refactoring broke it into a few sub-packages for better maintenance, like [PR1](https://github.com/kubernetes/kubernetes/pull/80998), [PR2](https://github.com/kubernetes/kubernetes/pull/78282), [PR3](https://github.com/kubernetes/kubernetes/pull/84379), so now we have `e2e/framework/[pod, node, network]` etc. sub-packages doing their own job. 

3. What's the problem?

The problem is, the core framework package(`e2e/framework`) must import some of its sub-packages to work, and almost all   of the sub-packages also need to import the core framework package back, so this cause circular import issues. Naturally we come up with two ways to fix this. 

- One is, to avoid the core framework(`e2e/framework`) importing its sub-packages(`e2e/framework/[pod, node, network]` etc.
- Second, to avoid sub-packages(`e2e/framework/[pod, node, network]` etc. importing the core framework(`e2e/framework`).

For the first way, there was an umbrella [issue](https://github.com/kubernetes/kubernetes/issues/81245) recording and several PRs trying to fix this problem, but it's been long stalled. Why? Because the `Framework` has to do work that must import a number of its sub-packages, like calling into`e2e/framework/e2emetrics` package to gather metrics after a test suit has run, or calling into `e2e/framework/e2epod` to check pod status or exec commands. This is inevitable, so the first way doesn't work. We can still try the second way, by avoiding sub-packages importing the core framework(`e2e/framework`).

4. The refactoring process

Currently, the core framework still does too much, we can separate more of its functionalities to its sub-packages. The goal is to keep `Framework` lean, and remove all imports to `e2e/framework` package from its sub-packages, little by little. 

- Move `Framework.[Logf, Failf, ExpectNoError]` etc. to the `e2e/framework/utils` package, so sub-packages can import this package instead of `framework` itself.
- Move `Framework.TestContext` to `e2e/framework/config` package, so sub-packages that rely on run-time command line arguments don't need to import `framework` itself. 
- Make functions or methods in sub-packages not reference `framework.Framework` directly, instead accept parameters that can be passed from framework explicitly when called. For example, some functions in sub-packages merely need the namespace string by referencing `framework.Framework` directly, we can avoid this. 
- Move `Framework.ProviderInterface` to `e2e/framework/providers` package, and remove `FrameworkBeforeEach(f *Framework)` and `FrameworkAfterEach(f *Framework)` methods from the interface, since none of both is never used or implemented. 
- Move `framework.TimeoutContext` to `framework/config` package.
- Modify e2e tests to reflect on these changes.
- And more cleanup work.

If this refactoring process is accepted, we will come up with several PRs to fix one aspect each time for better review purpose. 

### Why is this needed?

See above. 

/cc @oomichi @aojea

**Comment by oomichi** [comment]
This is against https://github.com/kubernetes/kubernetes/issues/81245 what we have a consensus that e2e core framework should not import the sub-packages.

> The problem is, the core framework package(e2e/framework) must import some of its sub-packages to work, and almost all of the sub-packages also need to import the core framework package back, so this cause circular import issues.

To avoid circular import issues, we have agreed to make core framework should not import the sub-packages.
