### ISSUE TITLE
client-go/workqueue needs priority queue

### ISSUE THREAD

**Issue by 277631272** [kubernetes/kubernetes#109348]
### What happened?

There is such a scenario, we have many clusters, up to 100,000, and the cluster has regular health checks, and the number of work coroutines is limited. When the work coroutine is doing cluster health check processing, there are new cluster starts to be created, we need to prioritize the newly created cluster, so we need a priority queue.

### What did you expect to happen?

We need to get high priority items from the queue for processing

### How can we reproduce it (as minimally and precisely as possible)?

None

### Anything else we need to know?

None

### Kubernetes version

None

### Cloud provider

None

### OS version

None

### Install tools

None

### Container runtime (CRI) and version (if applicable)

None

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None

**Comment by MadhavJivrajani** [comment]
/sig api-machinery
Would it not be possible to implement it as part of your project? The workqueue package provides interfaces to implement. Not sure if there is a need for it in Kubernetes. 
Will let other folks chime in though!

**Comment by MikeSpreitzer** [comment]
For those writing controllers directly against client-go, yes, the workqueue is entirely a choice of the controller author.

Even so, I think it is fair to ask if it would be valuable to make client-go offer a variant of workqueue that has some sort of prioritization.

I think if it is also fair to ask if a simpler solution would solve the OP's problem.  What about just submitting the health check entries to the work queue at a limited rate --- or, if that is already the case, at a lower rate?  I think it is arguable that the other work should not starve the health checks.

**Comment by roycaihw** [comment]
/kind feature
/priority awaiting-more-evidence

/assign @277631272 
since you have a PR already: https://github.com/kubernetes/kubernetes/pull/109349

**Comment by 277631272** [comment]
> 

The priority queue was originally a part of the project. Later, it was found that many scenarios were involved. At the same time, it was found that many crds also needed to be processed according to the priority. Therefore, I felt that if it was integrated into client-go, different people could be used for this scenario. to use

**Comment by 277631272** [comment]
@[MikeSpreitzer](https://github.com/MikeSpreitzer)
I think some important tasks are prioritized, because these tasks require high timeliness, and the number of these important tasks is usually relatively small. And for a large number of tasks, it is usually the second most important, even if these tasks wait for a while, it should be fine.
