### ISSUE TITLE
Investigate extending log sanitization to audit logs

### ISSUE THREAD

**Issue by ahmedtd** [kubernetes/kubernetes#109376]
### What would you like to be added?

(This is an issue being moved from https://github.com/kubernetes-security/security-disclosures-low/issues/9 to be worked on in public)

In the past, we've had a medium-severity vulnerability reported to the Kubernetes project for a misconfigured audit-logging.  The core of the original issue was that the default Kubernetes audit log policy in the cluster/gce/gci/configure-helper.sh script (https://github.com/kubernetes/kubernetes/blob/v1.21.1/cluster/gce/gci/configure-helper.sh#L1215-L1224) is set to “Metadata” for Secrets, ConfigMaps, and TokenReviews, but should also include Service Account Tokens.

This resulted in tokens being emitted in audit logs.

One of the ideas the SRC wanted to pursue was to see whether the existing log sanitization functionality could be extended to cover audit logs, so that sensitive data like tokens is automatically masked, without requiring audit logging policies to be updated for each new potentially-sensitive request.

Existing sanitization KEPs are:
* https://github.com/kubernetes/enhancements/issues/1933
* https://github.com/kubernetes/enhancements/issues/1753

Based on my initial reading, the existing functionality only covers debug logs --- if you call log.FilterLog, that's hooked up to runtime sanitization. The actual sanitization logic is based on tagged struct fields.

/sig-auth

### Why is this needed?

Having audit log sanitization would close off a class of security vulnerabilities.

**Comment by ritazh** [comment]
/triage accepted
/remove-lifecycle rotten

To move this issue forward, we need someone who's interested to bring this topic and a design to sig auth community call. This would most likely require an extension of an existing KEP or a new one.
