### ISSUE TITLE
We need a [Disruptive] test that is capable of exposing deep write latency bugs for the underlying K8s APIServer Storage implementation.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#109399]
### What happened?

We missed some critical test coverage in 1.22 and verified etcd 3.5 which has several issues https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ?utm_medium=email&utm_source=footer&pli=1 

### What did you expect to happen?

We have a  test in place that  can  push etcd to its limits and send SIGKILLs somehow. 

### How can we reproduce it (as minimally and precisely as possible)?

Were not 100% sure yet but this test should probably: 

- have a daemonset which continuosly updates annotations in an object
- poll the object for changes
- write the current visible state of the world back to this object with a key identifying the observing node's view of the object
- confirm that over a period of 1000s of transactions, no node falls out of sync wrt the state of this object

### Anything else we need to know?

For the motivation for this, see

- https://github.com/etcd-io/etcd/issues/13913
- https://github.com/etcd-io/etcd/pull/13854

### Kubernetes version

1.22 / etcd 3.5.1/2

### Cloud provider

any

### OS version

any

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jayunit100** [comment]
let me know if this should live somewhere else i.e. https://github.com/kubernetes/perf-tests talked with @jamiephillips and @Elbehery today , well build this between rancher/rh/vmware open to collab w others

**Comment by Elbehery** [comment]
+1

**Comment by serathius** [comment]
I agree that Etcd should have an disruptive soak tests, it even already have disruptive tests, however I don't think it should be handled on K8s side. Instead of K8s community duplicating the work of etcd community, we should think how we can work together to ensure quality of testing. Both projects belong to same organization CNCF so we should be able to figure this out.

After v3.5.3 is cut I will refocus on this exact issue, so please stay tuned on improvements to etcd testing.

**Comment by Elbehery** [comment]
@serathius thanks for your follow up .. I would like to help / pair with you on that if possible

**Comment by jayunit100** [comment]
Am ok closing this if nobody is working on it.

I feel like this should be reproducible w sonobuoy or ginkgo e2es  however in order to have maximum community accessibility
