### ISSUE TITLE
Scheduler not respecting pod anti affinity in certain cases

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [kubernetes/kubernetes#109367]
### What happened?

We're noticing that the default scheduler is not respecting pod anti affinity and assigning the replica of a deployment to the same node where another replica is running(we've explicitly set pod anti affinity in the deployment spec to ensure spread). 

### What did you expect to happen?

Scheduler spreading pods evenly and respecting pod anti affinity

### How can we reproduce it (as minimally and precisely as possible)?

This is happening in our CI environment and the conditions to reproduce this are really hard. Following are the observations when this issue happens.

- Both the pods are in pending state because there are no nodes which satisfy the requirement for a few minutes(5-7 minutes in most of the cases)
- kube-scheduler's cert has been reloaded and it temporarily lost connectivity with apiserver after the pods are assigned

I was not able to reproduce this locally via an integration test that we created.

Example CI Run where this happened:

19:01:42 | openshift-etcd |   | etcd-quorum-guard-fc96569c5-544f9 | Scheduled | Successfully assigned openshift-etcd/etcd-quorum-guard-fc96569c5-544f9 to ci-op-s735mbp5-fde6e-4n842-master-1
-- | -- | -- | -- | -- | --
19:01:43 | openshift-etcd |   | etcd-quorum-guard-fc96569c5-cvh6v | Scheduled | Successfully assigned openshift-etcd/etcd-quorum-guard-fc96569c5-cvh6v to ci-op-s735mbp5-fde6e-4n842-master-1

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.11-upgrade-from-stable-4.10-e2e-azure-upgrade/1509599330665762816/artifacts/e2e-azure-upgrade/gather-must-gather/artifacts/event-filter.html

You can notice that scheduler assigned both [etcd-quorum-guard](https://github.com/openshift/cluster-etcd-operator/blob/f3d8db9c071c979b064063e97206f24398e9a854/bindata/etcd/quorumguard-deployment.yaml#L24) replicas to the same node. 

Another interesting point to note is that the scheduler logs indicate that only one of the replicas has been assigned the node. IOW, I can find only one entry for successful binding:

```
I0331 19:01:42.987320 1 scheduler.go:621] "Successfully bound pod to node" pod="openshift-etcd/etcd-quorum-guard-fc96569c5-544f9" node="ci-op-s735mbp5-fde6e-4n842-master-1" evaluatedNodes=3 feasibleNodes=1
```

I also made sure that there is only one scheduler running at the time indicated in the log(19:01:42). I traced through the code to see if there can be a cache corruption issue but I couldn't find any evidence considering AssumePod method is providing strong guarantees around podNode assignment locally. 

### Anything else we need to know?

@Huang-Wei thinks it could be an issue with the scheduler not waiting for informers to sync caches and he saw something similar in the past when the caches are not in sync. 

At the moment, I think the 2nd pod is not going through the scheduling cycle and somewhere the first pod is assumed as 2nd pod. I think so because the scheduler log doesn't indicate any binding msg for the 2nd pod.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.23
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
The oddest part is that you don't see a log line for `Successfully bound pod to node` for the second pod.

Can you verify the kube-apiserver logs to see if there was any call to the binding endpoint?

**Comment by ravisantoshgudimetla** [comment]
Yes, we can see that the pod has been bound to node in the apiserver logs. Further more both the pods are running on the same node

**Comment by alculquicondor** [comment]
And the call came from the same user agent? Are there any reasons to believe that kube-scheduler crashed at some point? Can you try running with higher log verbosity level?

**Comment by ravisantoshgudimetla** [comment]
Yup. There is no other entity which is assigning pod to node. 

> Can you try running with higher log verbosity level?

For api-server or scheduler? I did not pursue this route because this issue happens with very less frequency and it'll put pressure on CI infrastructure to enable logging for every CI run.

**Comment by alculquicondor** [comment]
Could you try 3 at least?

**Comment by ahg-g** [comment]
> Another interesting point to note is that the scheduler logs indicate that only one of the replicas has been assigned the node. IOW, I can find only one entry for successful binding:

This is very odd and suspicious. Can you check that the binding call for both were indeed made by kube-scheduler as the agent?

> At the moment, I think the 2nd pod is not going through the scheduling cycle and somewhere the first pod is assumed as 2nd pod. I think so because the scheduler log doesn't indicate any binding msg for the 2nd pod.

It is unlikely that the scheduler is treating both as the same if it indeed made two binding calls for each. Binding happens only if the pod went through the scheduling cycle.

>  Further more both the pods are running on the same node

That is expected, pod anti-affinity is only enforced by the scheduler, kubelet doesn't enforce it.
