### ISSUE TITLE
Cluster monitoring configs don't work with startup-time InfluxDB

### ISSUE THREAD

**Issue by mvdan** [kubernetes/kubernetes#10938]
After `./hack/dev-build-and-up.sh`, heapster is working fine and grafana shows all the panels correctly. If I take down the heapster and replace it with the influxdb monitoring config, the panels with `label 'name:heapster'` start complaining that there are no datapoints.

This is how I replaced heapster:

```bash
$ kubectl delete rc monitoring-heapster-v5 --namespace=kube-system
$ kubectl create -f cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml
```

Editing the panels to use the `k8s-app:heapster` instead of `name:heapster` gets them to work again.

**Comment by vmarmol** [comment]
FYI @vishh, @saad-ali

**Comment by saad-ali** [comment]
This should be fixed by GoogleCloudPlatform/heapster/pull/383
Kubernetes should get the fix once Heapster version is rev'd

**Comment by mvdan** [comment]
Cool, thanks @saad-ali!

**Comment by vmarmol** [comment]
So this should be in v0.16.0 no?

**Comment by saad-ali** [comment]
Sorry, to be perfectly clear, Kubernetes will get it whenever the new version of the `heapster_grafana` container is [pushed from the heapster side](https://github.com/GoogleCloudPlatform/heapster/blob/master/Makefile#L36), and the corresponding version is [set on the kubernetes side](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml#L37).

**Comment by mvdan** [comment]
@saad-ali was this fixed?

**Comment by saad-ali** [comment]
+@vishh

**Comment by vishh** [comment]
I haven't updated kubernetes configs for grafana image recently. IN any case, current heapster head has been updated to use Grafana v2.0 which does not support default dashboards. So we can close this issue.

**Comment by mvdan** [comment]
Great, thanks. I was just going over issues I had opened but forgotten about.
