### ISSUE TITLE
Helper Prow Bot command that generates additional commit on PRs

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubernetes/kubernetes#109374]
A bot command that makes an additional commit to PRs that fail to pass the bars with `make update` or `make verify`  to re-generate files as needed. 
This is a proposed solution advancing the temporary solution of a helper CI job that runs make update when triggered and there's a zip file that has the changes after the `make update` is run.

ref #107726 

cc @dims

**Comment by MadhavJivrajani** [comment]
Please keep in mind: the author should be okay with the bot doing this. 

Should we maybe move this to k/community or k/test-infra?

**Comment by SubhasmitaSw** [comment]
> Please keep in mind: the author should be okay with the bot doing this.
> 
> Should we maybe move this to k/community or k/test-infra?

This should work only when the author's PR fail for those particular test cases, overall in my opinion folks with advanced computer systems wouldn't be needing this, so works only for folks with low-end PCs.
