### ISSUE TITLE
The validation of Annotations

### ISSUE THREAD

**Issue by sayaoailun** [kubernetes/kubernetes#109459]
https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L50

Why do we need `strings.ToLower(k)`?

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/pull/55902#discussion_r152650870
> annotations allow mixed-case

**Comment by pacoxu** [comment]
IsQualifiedName allows lowercase. It seems to be not needed now.

**Comment by sayaoailun** [comment]
https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L55

`Abc/test` is valid for annotation key but not QualifiedName, right?

**Comment by apelisse** [comment]
> https://github.com/kubernetes/kubernetes/blob/c285e781331a3785a7f436042c65c5641ce8a9e9/staging/src/k8s.io/apimachinery/pkg/util/validation/validation.go#L55
> 
> `Abc/test` is valid for annotation key but not QualifiedName, right?

That's what I read too. Should we submit a pull-request to clarify a comment somewhere?

**Comment by sayaoailun** [comment]
> Should we submit a pull-request to clarify a comment somewhere?

Maybe it's better.
