### ISSUE TITLE
Pods are getting Scheduled and in Pending state during Graceful Node Shutdown.

### ISSUE THREAD

**Issue by amshankaran** [kubernetes/kubernetes#109450]
What happened:
When the node is under graceful shutdown Daemonset pods were getting rescheduled in the  same node and remains in pending state.

What you expected to happen:
While the node is under graceful shutdown, the pods should not be scheduled and there shouldn't be any pods in pending state. 

How to reproduce it (as minimally and precisely as possible):
Flags configured: shutdownGracePeriod:30s, shutdownGracePeriodCriticalPods:10s,   --terminated-pod-gc-threshold: 1
Shutdown the worker node gracefully (with systemctl poweroff) Daemonset pods were getting rescheduled in the  same node and remains in pending state.

director-0-stack1:~> kubectl get pods -A -o wide | grep worker-pool1-w9dpshqq-stack1
kube-system     calico-node-r6pwl                                                 1/1     Running             0             21m     10.0.16.20        worker-pool1-w9dpshqq-stack1   <none>           <none>
kube-system     kube-proxy-f8qrf                                                  1/1     Running             0             21m     10.0.16.20        worker-pool1-w9dpshqq-stack1   <none>           <none>
kube-system     node-local-dns-jjlzc                                              1/1     Terminating         0             21m     10.0.16.20        worker-pool1-w9dpshqq-stack1   <none>           <none>

-----------

eccd@director-0-stack1:~> kubectl get pods -A -o wide | grep worker-pool1-w9dpshqq-stack1
kube-system     calico-node-qlbbl                                                 0/1     Pending   0             54s   <none>            worker-pool1-w9
dpshqq-stack1   <none>           <none>
kube-system     kube-proxy-gtdwh                                                  0/1     Pending   0             54s   <none>            worker-pool1-w9dpshqq-stack1   <none>           <none>
kube-system     node-local-dns-kztmh                                              0/1     Pending   0             55s   <none>            worker-pool1-w9dpshqq-stack1   <none>           <none>

kubernetes version:
eccd@director-0-stack1:~> kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:38:28Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"a9dda44d3f9da886364993e5cbb0f2afbbeae113", GitTreeState:"clean", BuildDate:"2022-02-10T11:27:59Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

**Comment by kerthcet** [comment]
Does this have some negative effects to your cluster, I mean finally when `shutdownGracePeriod` times out, all calm down.

**Comment by amshankaran** [comment]
Hi @kerthcet , I have set this shutdownGracePeriod as 30 seconds. After shutting down the node, even after an hour I'm seeing these pending pods for the daemonsets.

**Comment by rthakur-est** [comment]
cc @bobbypage

**Comment by amshankaran** [comment]
calico-node-h6cgw:
.........
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 :NoSchedule op=Exists
                             :NoExecute op=Exists
                             CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists

**Comment by rohit28071992** [comment]
I am facing the same issue over K8 1.23.7 version. I have set shutdownGracePeriod as 60s , shutdownGracePeriodCriticalPods as 20 s. I can see that kubelet have taken inhibit locks ( Who: kubelet (UID 0/root, PID 3047081/kubelet) What: shutdown Why: Kubelet needs time to handle node shutdown Mode: delay ). When I power off my any minion node by systemctl poweroff command, the node is turned off in approx 10-12 seconds only. 
1. Why system is not halted for configured shutdownGracePeriod which is 60s?

After this, I can see that I got event at master node  as (Shutdown manager detected shutdown event) for the node made down but I can see only one pods went in terminated states which is nginx, rest 3 pods are in running state only. 

[root@node1 home]# kubectl get pods -A -owide |grep node4
kube-system      calico-node-n8x2c                            1/1     Running      8 (2d23h ago)   6d18h   172.19.59.62   node4   <none>           <none>
kube-system      kube-proxy-wbdbv                             1/1     Running      8 (2d23h ago)   6d18h   172.19.59.62   node4   <none>           <none>
kube-system      nginx-proxy-node4                            1/1     Terminated   8 (2d23h ago)   6d18h   172.19.59.62   node4   <none>           <none>
kube-system      nodelocaldns-7s895                           1/1     Running      9 (2d23h ago)   6d18h   172.19.59.62   node4   <none> 


Can someone please help me if I am missing anything here?
