### ISSUE TITLE
Check our HNS api calls for deprecation, i.e. GetSupportedFeatures in windows kernelspace proxier

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#109404]
### What happened?

fixing this in KPNG, just an FYI

https://github.com/kubernetes/kubernetes/blob/master/pkg/proxy/winkernel/proxier.go#L143

I think should be calling GetCachedSupportedFeatures... 

https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go

### What did you expect to happen?

We use up to date HCN apis

### How can we reproduce it (as minimally and precisely as possible)?

just look for Deprecated code in HCN and compare by eye... 

### Kubernetes version

head

### Cloud provider

any

### OS version

windows

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by khenidak** [comment]
fyi @jsturtevant

**Comment by jsturtevant** [comment]
GetSupported features calls GetCachedSupportedFeatures so the caching is used in 1.23 after https://github.com/kubernetes/kubernetes/pull/104880 merged

https://github.com/kubernetes/kubernetes/blob/a83cc51a19d1b5f2b2d3fb75574b04f587ec0054/vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go#L69-L70
