### ISSUE TITLE
can we concurrently get metrics in hpa-controller?

### ISSUE THREAD

**Issue by bamboo12366** [kubernetes/kubernetes#109496]
In our use case, we are using multiple external metrics(from prometheus) for one hpa object.
The latency from prometheus can be high sometimes, can we concurrently get all the metrics back and do the calculation together? 

code here: https://github.com/kubernetes/kubernetes/blob/f33ca2306548719e5116b53fccfc278bffb809a8/pkg/controller/podautoscaler/horizontal.go#L274

**Comment by neolit123** [comment]
/sig autoscalling

please include full details from the template:
https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/bug-report.yaml

**Comment by bamboo12366** [comment]
Bug Report | Report a bug encountered while operating Kubernetes | kind/bug

What happened?
In our use case, we are using multiple external metrics(from prometheus) for one hpa object.
The latency from prometheus can be high sometimes, thus to calculate some hpa with multiple metrics can be very slow

code here:  https://github.com/kubernetes/kubernetes/blob/f33ca2306548719e5116b53fccfc278bffb809a8/pkg/controller/podautoscaler/horizontal.go#L274

What did you expect to happen?
can we concurrently get metrics and do the calculation together?

Anything else we need to know?
Kubernetes version
1.20

Cloud provider
physical machine

OS version
Ubuntu 16.04.6

Install tools
N/A

Container runtime (CRI) and version (if applicable)
N/A

Related plugins (CNI, CSI, ...) and versions (if applicable)
N/A

**Comment by zroubalik** [comment]
This is related: adding concurrent workers for HPA processing: 
https://github.com/kubernetes/kubernetes/pull/108501

**Comment by bamboo12366** [comment]
@zroubalik yea these two are related, for our case, we implement the concurrent worker ourselves. but the metrics request still the bottleneck

**Comment by zroubalik** [comment]
@bamboo12366 ack, would you mind reviewing that PR and sharing your experience with it (just for the worker related part)?

**Comment by bamboo12366** [comment]
sure, I can give a try

**Comment by pbetkier** [comment]
Note that adding concurrent workers for HPA processing (#108501) just got merged. Not the same as asynchronously getting custom metrics, but may help enough.

**Comment by pbetkier** [comment]
Also note discussions under https://github.com/kubernetes/kubernetes/issues/96242#issuecomment-1228627821 on ways to speed up custom metrics fetching.
