### ISSUE TITLE
HPA doesn't attempt to add more pods even if pod provisioning fails

### ISSUE THREAD

**Issue by wasker** [kubernetes/kubernetes#109445]
### What happened?

For some reason one of the nodes in cluster went into a bad state manifesting itself in inability for pods to pull images off of a private registry that requires authentication (ErrImagePull, authentication failed).

At the same time, service experienced a traffic spike, which resulted in all running pods of a deployments to cross CPU usage threshold for HPA. HPA requested a new pod, however, the pod landed on the node in a bad state. An hour later, with cluster still under the heavy load, new capacity never arrived, resulting in drop in reliability.

### What did you expect to happen?

HPA should've treated this situation as a situation still requiring scaling and try to add another pod if previous attempt didn't result in autoscaling metrics going down.

### How can we reproduce it (as minimally and precisely as possible)?

1. Have a service deployment with HPA set up with CPU usage threshold and scale 3...6.
2. Simulate conditions when provisioning of a new pod would fail.
3. Generate load on the service that would trigger HPA.

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"19bca9208454ad7ac76f6fc71b5a2520922e395b", GitTreeState:"clean", BuildDate:"2022-03-10T18:21:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>
not relevant
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yxxhero** [comment]
@wasker I think this situation is normal for HPA. HPA is only responsible for adjusting the number of pods according to the load of CPU and mem. It is not responsible for the scheduling results and running results of pod.
You should prohibit calling the problem node and start it after repairing it.

**Comment by wasker** [comment]
@yxxhero While I understand that HPA is not concerned with actual bootstrapping of the node, consider the following timeline.

1. t0 - Cluster maintenance operation is completed, re-deployment of all workloads occurs, 2 deployments are unable to complete due to the node in bad state. (Why this was considered successful outcome is something that I'm discussing w/ the cloud provider.)
2. t1 - CPU metrics clearly indicate scaling is needed (existing pods are running really hot).
3. HPA doesn't consider that extra capacity is required.
4. Situation continues for another couple of hours, affecting service's SLA.

The way I see it, the point of autoscaling is so one wouldn't babysit the cluster during traffic spikes. It looks like HPA doesn't take to consideration that requested capacity is "pending" for too long, before retrying to get more. In fact, whether the capacity is "pending" is probably not important: if CPU metrics didn't drop, why not add more capacity until CPU metrics drop or maxReplicas is reached? I'd rather have extra unused capacity that I can debug at a better time than service dropping connections due to overloaded pods.

**Comment by oliviermichaelis** [comment]
> It looks like HPA doesn't take to consideration that requested capacity is "pending" for too long, before retrying to get more.

To me, this sounds more like the responsibility of the scheduler, than that of the HPA. As @yxxhero pointed out, the HPA has done its job by increasing the number of desired replicas.


> The way I see it, the point of autoscaling is so one wouldn't babysit the cluster during traffic spikes

Sounds like you could make use of an alert triggering if a pod is in `pending` state for longer than x minutes or if a pod is crashlooping often :)

**Comment by wasker** [comment]
@oliviermichaelis No, HPA didn't "do its job": CPU metrics did **not** go down as a result of it increasing desired replicas. Both HPA and cluster have max replicas/nodes parameters set to values that would allow HPA to request more capacity to alleviate the issue, but it just stopped doing it.

Alerting/monitoring is a separate concern here. HPA had an opportunity to request more capacity without my involvement but didn't do so - that's the problem.
