### ISSUE TITLE
Kubernetes master doesnt get external ip of my new node

### ISSUE THREAD

**Issue by Pseudow** [kubernetes/kubernetes#109467]
Hi, Ive recently added a new node in my cluster. The problem is that my vps where the node is has a different internal and external ip. The internal ip is used to acces from outside to my node and the internal is used by the vps itself.

The problem is that when kubeadm join the cluster it sends the internal ip not the external ip, which makes it wrong. Ive tried to change it my modifying --node-ip flag like this:

```
KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --network-plugin=cni --register-node=true --node-ip=MY_EXTERNAL_IP
```

But the problem is that it still dont work
![image](https://user-images.githubusercontent.com/64150196/163239508-e3320516-ddba-4f1e-8f23-445e6aa05d26.png)

When I look at the logs generated by my calico-node pod it says:
```
Error from server: no preferred addresses found; known addresses: []
```

**Comment by Pseudow** [comment]
Oups I closed with sorry

**Comment by neolit123** [comment]
Kubeadm and k8s components have the same IP detection. It will use the "default route" IP. You can google that to see what it means.

What IP is kubeadm / kubelet detecting? The error  you are reporting is for calico and might be better to log the issue in the calico repo.

/remove-sig node
/sig cluster-lifecycle
/kind support

**Comment by Pseudow** [comment]
They actually detect no ip. Even the log of the kube proxy pod says:

Error from server: no preferred addresses found; known addresses: []

**Comment by neolit123** [comment]
ok, we are (mostly) missing documentation on this topic but the TL;DR is that you have to make your host interfaces k8s compatible.

**Comment by neolit123** [comment]
alternatively you can pass custom IPs to all the components, but that's difficult to manage.

**Comment by khenidak** [comment]
I think this is a kubeadm issue, right?

**Comment by neolit123** [comment]
mostly yes, because kubeadm is the top level tool.
but the wider problem is that we don't have docs on how the detection in components works and what is the recommended network interface setup to make it easy for users to deploy nodes. firewall settings vs public IPs etc.

> alternatively you can pass custom IPs to all the components, but that's difficult to manage.

for that the docs are here:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/

support tickets should go here in general:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by neolit123** [comment]
@Pseudow 

here is a node from the online playground at Katacoda that is k8s compatible as an example:
https://www.katacoda.com/courses/kubernetes/playground

```
controlplane $ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.1  netmask 255.255.255.0  broadcast 172.18.0.255
        ether 02:42:20:78:bc:a5  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

ens3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.15  netmask 255.0.0.0  broadcast 11.255.255.255
        inet6 fe80::42:aff:fe00:f  prefixlen 64  scopeid 0x20<link>
        ether 02:42:0a:00:00:0f  txqueuelen 1000  (Ethernet)
        RX packets 244  bytes 46677 (46.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 164  bytes 29131 (29.1 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 106  bytes 7660 (7.6 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 106  bytes 7660 (7.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
controlplane $ ip route
default via 10.0.0.1 dev ens3 
10.0.0.0/8 dev ens3 proto kernel scope link src 10.0.0.15 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 
10.244.1.0/24 via 10.0.0.19 dev ens3 
172.18.0.0/24 dev docker0 proto kernel scope link src 172.18.0.1 linkdown 
```
