### ISSUE TITLE
CSI Client - consider making client timeout a parameter

### ISSUE THREAD

**Issue by yibozhuang** [kubernetes/kubernetes#109422]
Currently in
https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_plugin.go#L53

The client timeout when Kubelet invokes CSI node plugins is hard-coded at 2 minutes.
Should we consider allowing this value to be configurable?

Advantage there would be that for CSI plugins that may require longer time for performing staging and/or publishing, it allows the request to go through on one try rather than possibly multiple retries.

Currently when client ctx times out but the underlying CSI plugin may be still performing some operations and a retry may lead to some inconsistencies. So allowing the client timeout to be configurable gives more flexibility when configuring Kubelet based on the CSI drivers that are used.

**Comment by jsafrane** [comment]
cc @msau42 @jingxu97 @gnufied

**Comment by yibozhuang** [comment]
Feedback from sig-storage sync:
- Leverage [node-driver-registrar](https://github.com/kubernetes-csi/node-driver-registrar) and have the sidecar accept a timeout parameter which will default to the current timeout value used by Kubelet (2min)
- Update the [device plugin registration protobuf](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/pkg/apis/pluginregistration/v1/api.proto) to allow such timeout value to be passed to the Kubelet
- Kubelet will use this timeout (if configured/set) when invoking CSI node level APIs
- Kubelet will default to the current 2min if this value is not set
- Need a KEP as well as the feature gate to drive this from alpha -> GA

Next steps: working on KEP and initial implementation locally
