### ISSUE TITLE
Patch request should update resource to indicate patch operation is in progress

### ISSUE THREAD

**Issue by muang0** [kubernetes/kubernetes#109490]
### What happened?

A 'patch' request to a statefulset doesn't update the resource status (this doesn't happen until the associated k8s controller picks up the change and performs an 'update').  Because of this, we're encountering a race condition between helm and the k8s statefulset controller during installs.  Helm checks the resource status to determine readiness after applying the patch, which can happen before the k8s controller has the chance to update the statefulset status.  When a 'patch' request is handled, there should be some update on the resource status that indicates a patch operation is in progress.  Unfortunately I can't share logs because this is something I am encountering in my cluster at work (highly restrictive fintech).

Associated issue opened to helm [here](https://github.com/helm/helm/issues/10859)

### What did you expect to happen?

A 'patch' request should also update the resource status (when applicable).

### How can we reproduce it (as minimally and precisely as possible)?

NA, this is a potential design bug with how 'patch' requests are handled

### Kubernetes version

<details>
1.21.5
</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

NA
<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
eksctl
</details>

### Container runtime (CRI) and version (if applicable)

NA
<details>
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NA
<details>

</details>

**Comment by liggitt** [comment]
/remove-sig api-machinery

this isn't specific to patch requests, but to update requests in general, relative to the status reported by the controller
/sig apps

**Comment by liggitt** [comment]
A patch API request is written atomically... there's no "in progress" intermediate state for a patch API request

**Comment by liggitt** [comment]
specifically for StatefulSet, is `status.observedGeneration` what you are wanting? that indicates the .metadata.generation which the controller had observed when it most recently updated `.status`. If `.metadata.generation` != `.status.observedGeneration`, that means status is stale

**Comment by muang0** [comment]
Thanks for the quick response Jordan!  A generational readiness check should solve the issue we're facing.  Currently helm only checks the number of replicas and their readiness status.  Thanks again for the help!
