### ISSUE TITLE
 creationTimestamp: null is invalid since it isn't a string 

### ISSUE THREAD

**Issue by wilmardo** [kubernetes/kubernetes#109427]
### What happened?

There seems to be a discrepancy between the Kubernetes openapi spec and the Go package with the `creationTimestamp`

### What did you expect to happen?

CRDs generated by `controller-gen` which uses `k8s.io/apimachinery/pkg/apis/meta/v1` to be valid according to the Kubernetes openapi spec.

### How can we reproduce it (as minimally and precisely as possible)?

```console
# wget https://github.com/fluxcd/source-controller/releases/download/v0.22.5/source-controller.crds.yaml
# kubeconform -schema-location default -schema-location "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master/customresourcedefinition.json" source-controller.crds.yaml
source-controller.crds.yaml - CustomResourceDefinition gitrepositories.source.toolkit.fluxcd.io is invalid: For field metadata.creationTimestamp: Invalid type. Expected: string, given: null
source-controller.crds.yaml - CustomResourceDefinition buckets.source.toolkit.fluxcd.io is invalid: For field metadata.creationTimestamp: Invalid type. Expected: string, given: null
source-controller.crds.yaml - CustomResourceDefinition helmrepositories.source.toolkit.fluxcd.io is invalid: For field metadata.creationTimestamp: Invalid type. Expected: string, given: null
source-controller.crds.yaml - CustomResourceDefinition helmcharts.source.toolkit.fluxcd.io is invalid: For field metadata.creationTimestamp: Invalid type. Expected: string, given: null
```

### Anything else we need to know?

At first I raised an issue at https://github.com/fluxcd/flux2/issues/2623 since they seemed to be the culprit.
But received a response that they use `controller-gen` to generate the CRDs. So I looked into [controller-gen](https://github.com/kubernetes-sigs/controller-tools) and they also do not set the `creationTimestamp` they import `k8s.io/apimachinery/pkg/apis/meta/v1` for the generation of the metadata (where the creationTimestamp is part of)([source](https://github.com/kubernetes-sigs/controller-tools/blob/8cb5ce83c3cca425a4de0af3d2578e31a3cd6a48/pkg/crd/spec.go#L26)).

So now the issue, in the package documentation ([link](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta)) of `k8s.io/apimachinery/pkg/apis/meta/v1` it says the following about the `creationTimestamp`
```golang
// CreationTimestamp is a timestamp representing the server time when this object was
// created. It is not guaranteed to be set in happens-before order across separate operations.
// Clients may not set this value. It is represented in RFC3339 form and is in UTC.
//
// Populated by the system.
// Read-only.
// Null for lists.
// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
// +optional
Creation[Time](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#Time)stamp Time `json:"creationTimestamp,omitempty" protobuf:"bytes,8,opt,name=creationTimestamp"`
```

So there is something in the docblock about Null for lists(?) but in the openapi spec of Kubernetes is this `Time` resource marked as string:
```json
"io.k8s.apimachinery.pkg.apis.meta.v1.Time": {
      "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
      "format": "date-time",
      "type": "string"
},
```
https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

So now, what is wrong here? Is it indeed allowed to be a string or null and should the openapi spec be an enum? Or is there something in`k8s.io/apimachinery/pkg/apis/meta/v1` wrong? Or should `controller-gen` explictly set the creationTimestamp to an string? 
The last one seems kinda wrong to me since it seems to me that the `k8s.io/apimachinery/pkg/apis/meta/v1` should return data valid to the api spec.

I am sorry for all the text and if I did not understand something correctly :)
I don't develop in golang (or at all really) and the relation between the package and the openapi spec is quite vague for me.

I opened the issue here since it seems an issue affecting multiple things within the kubernetes namespace (golang package, openapi spec in this repo).

### Kubernetes version

<details>
kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"5963a7a5570a1b8c977c31ced503cb20f0ef6e8c", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:42Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

NaN

**Comment by prakharporwal** [comment]
Hi I am new to K8s. Would like to try this issue out.  Any hints ?

**Comment by wilmardo** [comment]
And again a little nudge @jpbetz @sttts 

The current discrepancy breaks linters like [yannh/kubeconform](https://github.com/yannh/kubeconform) since they generate their ruleset based on the API spec.
The current state makes a generated CRD from an official package invalid according to rules based on the API spec.

**Comment by avthart** [comment]
Would be great if this can be fixed, so that we don't have to remove lines with `creationTimestamp: null` manually for our CI linting.

**Comment by jpbetz** [comment]
`creationTimestamp` is an optional field in openAPIv3 and may be absent from the JSON but should never be set to `null`.

The go struct contains `json:",omitempty"` to direction serializers to omit the field from JSON if the go struct is null.

Would someone provide more more details on how the custom resources were serialized such that they contain `creationTimestamp: null`?

**Comment by jpbetz** [comment]
cc @jiahuif @apelisse

**Comment by jpbetz** [comment]
From @liggitt there is a bunch of backstory here: https://github.com/kubernetes/kubernetes/issues/67610, https://github.com/kubernetes/kubernetes/pull/53464, https://github.com/kubernetes/apimachinery/issues/68, https://github.com/kubernetes/apimachinery/issues/119, https://github.com/kubernetes/kubernetes/pull/104857

**Comment by jpbetz** [comment]
@apelisse pointed out to me a couple issues here that make this less practical to fix on the k8s side:

- Even if we add `nullable: true` in OpenAPIv3, it will only help in toolchains that are correctly consuming openapiv3, which is often not the case, and I'm not clear if it is the case in this specific issue.
- While `creationTimestamp` is one of the most obvious examples of a field that is allowed to be set to `null` but is not marked as nullable, the Kubernetes marshalling code allows for `null` in many cases, none of which are explicitly marked as `nullable: true`. For example, IIRC, in CRDs, all non-required fields may be set to null, and we don't require CRD authors to explicitly add `nullable: true` to the schemas.

Would it be possible for kubeconform to be modified to uniformly allow `null` for all non-required fields?

**Comment by jpbetz** [comment]
Also, code that uses the [applyconfigurations](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/applyconfigurations/doc.go) instead of the go structs will not produce null fields like this. It might be sufficient to use applyconfigurations for this case to avoid the immediate problem.

**Comment by alexzielenski** [comment]
> While creationTimestamp is one of the most obvious examples of a field that is allowed to be set to null but is not marked as nullable, the Kubernetes marshalling code allows for null in many cases, none of which are explicitly marked as nullable: true. For example, IIRC, in CRDs, all non-required fields may be set to null, and we don't require CRD authors to explicitly add nullable: true to the schemas.

I'm not sure I agree the list of all types needing annotation is innumerable.

Go's JSON deserializer implicitly treats all null values as unset. This applies to both native types and CRDs: 

> The JSON null value unmarshals into an interface, map, pointer, or slice by setting that Go value to nil. Because null is often used in JSON to mean “not present,” unmarshaling a JSON null into any other Go type has no effect on the value and produces no error. [source][(https://pkg.go.dev/encoding/json](https://pkg.go.dev/encoding/json#Unmarshal))

There is only one exception to this: native types with custom `UnmarshalJSON` that directly handle `null` to override the default behavior. 

> To unmarshal JSON into a value implementing the Unmarshaler interface, Unmarshal calls that value's UnmarshalJSON method, including when the input is a JSON null. 

The (likely) exhaustive list of native types that I've found that implement custom JSON marshaling to handle null are:

(found using regex `\) (Unm|M)arshalJSON((?!func).|\n)*null`)

1. [runtime.RawExtension](https://github.com/kubernetes/kubernetes/blob/03b434c9d447d3e78f91f130420c5a83e11c81b4/staging/src/k8s.io/apimachinery/pkg/runtime/extension.go#L1-L51)
1. [rruntime.Unknown](https://github.com/kubernetes/kubernetes/blob/f9f9e7177a328ae47bac6b823d57a99dfbfd310b/staging/src/k8s.io/apimachinery/pkg/runtime/embedded.go#L73-L95) (doesnt roundtrip for null/"" case. likely bug?)
1. [meta.v1.Time](https://github.com/kubernetes/kubernetes/blob/f9f9e7177a328ae47bac6b823d57a99dfbfd310b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/time.go#L98-L152)
1. [meta.v1.MicroTime](https://github.com/kubernetes/kubernetes/blob/f9f9e7177a328ae47bac6b823d57a99dfbfd310b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time.go#L110-L161)
1. [meta.v1.FieldsV1](https://github.com/kubernetes/kubernetes/blob/c5a8015bbae1e1095813d8e0719f017477dc7112/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/helpers.go#L279-L295)
1. [apiextensions.v1.JSON](https://github.com/kubernetes/kubernetes/blob/694698ca3801fe5aa258d58c1e27ac7f88c29d35/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go#L123-L136)
1. [apiextensions.v1.JSONSchemaPropsOrStringArray](https://github.com/kubernetes/kubernetes/blob/694698ca3801fe5aa258d58c1e27ac7f88c29d35/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go#L62-L92) (this one marshals into null but does not accept it for unmarshalling, meaning it is not roundtrippable. Likely bug?)
1. [resource.Quantity](https://github.com/kubernetes/kubernetes/blob/c5a8015bbae1e1095813d8e0719f017477dc7112/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L650-L702)

We need to apply the `nullable` annotation in the schema only to all places where `null` does not mean `unset` - where `null` is an interpreted value.

**Comment by liggitt** [comment]
> Go's JSON deserializer implicitly treats all null values as unset. This applies to both native types and CRDs:

That's true for native types, but it's not correct for custom resources. Go's JSON deserializer will unmarshal `{"foo":null}` to `map[string]interface{}{"foo":null}`. We do a specific post-process step to drop explicitly null fields which were not marked as nullable in the schema (see `PruneNonNullableNullsWithoutDefaults`).

Setting `nullable` in the schema will *break* this pruning step and will preserve explicit `null` values.

**Comment by alexzielenski** [comment]
> This applies to both native types and CRDs:
> That's true for native types, but it's not correct for custom resources. 

You're right.  I was wrong to attribute the property that non-nullable null => unset for CRDs to the JSON deserializer. But the overall argument still holds. `PruneNonNullableNullsWithoutDefaults` is what gives the property to CRDs that `nullable: false` implies `null = unset` in k8s schemas.

> Setting nullable in the schema will break this pruning step and will preserve explicit null values.

I'm not sure I would see this as broken for the cases I've proposed. I am proposing to add  `nullable` only to value-typed usages of the listed types which  marshal their empty value into explicit null values. `PruneNonNullableNullsWithoutDefaults` would not prune fields like `creationTimestamp` as we've specified in OpenAPI since they are not properly marked `nullable. They also have a default set (kube-openapi code generator forces all structs to have `{}` default).

```json
          "creationTimestamp": {
            "allOf": [
              {
                "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
              }
            ],
            "default": {},
            "description": "..."
          },
```

I see two alternatives for fixing schema to be able to validate JSON that these types marshal into:

1. Permit the null by adding nullable annotation
2. Ignore the null by removing implicit `{}` default applied to struct types marshal their empty values into `null`. Clients should know to also apply `PruneNonNullableNullsWithoutDefaults` as we do to both native types and CRDs.

Both options are consistent and work for my purposes (kubectl-validate & Declarative Validation). The second carries the risk of not representing the reality in Go if `null` possibly could unmarshal into anything other than empty, but I dont think that applies to any of our current concrete cases.

**Comment by liggitt** [comment]
> > This applies to both native types and CRDs:
> > That's true for native types, but it's not correct for custom resources.
> 
> My mistake. The property that non-nullable null => unset for CRDs is not given by the the JSON deserializer. But the overall argument still holds. `PruneNonNullableNullsWithoutDefaults` is what gives the property to CRDs that `nullable: false` implies `null = unset` in k8s schemas. JSON deserializer for native types.
> 
> > Setting nullable in the schema will break this pruning step and will preserve explicit null values.
> 
> I'm not sure I would see this as broken for the cases I've proposed. I am proposing to add `nullable` only to value-typed usages of the listed types which marshal their empty value into explicit null values.
> 
> `PruneNonNullableNullsWithoutDefaults` would not prune fields like `creationTimestamp` as we've specified in OpenAPI since they also have a default set (kube-openapi code generator forces all structs to have `{}` default).
> 
> ```json
>           "creationTimestamp": {
>             "allOf": [
>               {
>                 "$ref": "#/components/schemas/io.k8s.apimachinery.pkg.apis.meta.v1.Time"
>               }
>             ],
>             "default": {},
>             "description": "..."
>           },
> ```
> 
> I see two alternatives for fixing schema to be able to validate JSON that these types marshal into:
> 
> 1. Permit the null by adding nullable annotation
> 2. Ignore the null by removing implicit `{}` default applied to struct types that marshal their empty values into `null`. Clients should know to also apply `PruneNonNullableNullsWithoutDefaults` as we do to both native types and CRDs.
> 
> Both options are consistent and work for my purposes (kubectl-validate & Declarative Validation). The second carries the risk of not representing the reality in apiserver if `null` possibly could unmarshal into anything other than empty, but I dont think that applies to any of our current concrete cases.

wow... that default is completely invalid for creationTimestamp, which serializes as a string

**Comment by kerthcet** [comment]
Seems `"creationTimestamp":null` still exists.

I reuse the podTemplateSpec in my CRDs, when patching the CRD object, it reports `metadata.creationTimestamp: field not declared in schema"`. Log the creationTimestamp, it has a null value, `"metadata":{"creationTimestamp":null,`. 

My kubernetes version is 1.30.0.
