### ISSUE TITLE
namespace  XXX not found

### ISSUE THREAD

**Issue by wangguoyan** [kubernetes/kubernetes#109495]
### What happened?

the namespace is exists when i get resource -A , but it is not found when i get ns 
![0A986B9B-62E5-4109-B2E0-57C04C7539DE](https://user-images.githubusercontent.com/43570712/163510012-82cbca95-e54b-463f-ad40-53c976f5ff12.png)

### What did you expect to happen?

data consistency 
namespace exists or resources  is deleted

### How can we reproduce it (as minimally and precisely as possible)?

none

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</details>

### Install tools

<details>
kuboard
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wangguoyan** [comment]
![0A986B9B-62E5-4109-B2E0-57C04C7539DE](https://user-images.githubusercontent.com/43570712/163509954-f7d13098-7c4d-404f-977b-dd6acfb78d6f.png)

**Comment by yxxhero** [comment]
@wangguoyan  k8s v1. 18.8 is no longer supported, please try upgrading k8s version

**Comment by neolit123** [comment]
seems like a support question, please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
