### ISSUE TITLE
Inconsistent POD status reporting with kubectl get && describe

### ISSUE THREAD

**Issue by yuzhiquan** [kubernetes/kubernetes#109451]
### What happened?

Deploy an pod in cluster, this pod image download was take some time   
I check pod with `kubectl get`, pod status is **ContainerCreating**:
```shell
# kubectl get pod
NAME                                  READY   STATUS              RESTARTS   AGE
nginx-01                              0/1     ContainerCreating   0          6s
```
then check pod with `kubectl describe pod ***`,  pod status is **Pending**:
```shell
# kubectl describe pod nginx-01
Name:         nginx-01
Namespace:    default
Priority:     0
Node:         tj1-kubekey-test08.kscn/10.38.200.41
Start Time:   Tue, 12 Apr 2022 17:43:29 +0800
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:
IPs:          <none>
Containers:
  nginx-hostport:
    Container ID:
    Image:          nginx:latest
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-kbxzq (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-kbxzq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  17s   default-scheduler  Successfully assigned default/nginx-01 to tj1-kubekey-test08.kscn
  Normal  Pulling    17s   kubelet            Pulling image "nginx:latest"
```

Reason, maybe:
`kubectl describe pod` print status with [pod.Status.Phase](https://github.com/kubernetes/kubernetes/blob/b9792a9daef4d978c5c30b6d10cbcdfa77a9b6ac/staging/src/k8s.io/kubectl/pkg/describe/describe.go#L785), but `kubectl get pod` print status with reason variable in [printPod](https://github.com/kubernetes/kubernetes/blob/b9792a9daef4d978c5c30b6d10cbcdfa77a9b6ac/pkg/printers/internalversion/printers.go#L756) function, that's not same field

### What did you expect to happen?

Get same pod status though `get` or `describe`

### How can we reproduce it (as minimally and precisely as possible)?

Just deploy an pod with slowly download image.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-mi-v1.21.3-dev", GitCommit:"484215e92603e82a14918dc43c71ef8ca45870f7", GitTreeState:"clean", BuildDate:"2022-03-15T18:16:20Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.3-mi-v1.21.3-dev", GitCommit:"484215e92603e82a14918dc43c71ef8ca45870f7", GitTreeState:"clean", BuildDate:"2022-03-16T18:21:01Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yuzhiquan** [comment]
If this issue is accepted, i would like give a shot.
/assign

**Comment by ehashman** [comment]
We've previously had some similar issues with this display for get pod, see also https://github.com/kubernetes/kubernetes/issues/105467

/triage accepted

**Comment by yuzhiquan** [comment]
> We've previously had some similar issues with this display for get pod, see also #105467
> 
> /triage accepted

May be we need one shot for them all, and what should i todo with this issue? give an pr or waitting for a new design for `kubectl get`?
