### ISSUE TITLE
smaller distroless based kube-proxy image

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109406]
Istio folks have a iptables image here that is quite small
https://github.com/istio/distroless/tree/iptables

```
$ docker images
REPOSITORY                      TAG       IMAGE ID       CREATED        SIZE
k8s.gcr.io/kube-proxy           v1.23.0   e03484a90585   4 months ago   112MB
gcr.io/istio-release/iptables   latest    455b182e8b7e   52 years ago   17.8MB
```

In the past, we did talk about this, for example @BenTheElder wrote it well what we could try:
https://github.com/kubernetes/kubernetes/issues/70249#issuecomment-1032224130

We could even do `bash-static` for running the hack script we have for switching the symlinks when `nft` vs `legacy`:
https://github.com/kubernetes/kubernetes/blob/c6153a93d0528a3dc6be9dedc2602f140081688d/cluster/images/etcd/Dockerfile#L23-L27

kube-proxy image is definitely one of the main causes of the cost we incur in our k8s.gcr.io GCR repository, so we should definitely give this a shot again.

/sig network

**Comment by uablrek** [comment]
I don't think this is a sig/network-only issue. A `find ... -name Dockerfile | grep -v test` gives;
```
kubernetes/build/server-image/Dockerfile
kubernetes/build/server-image/kube-apiserver/Dockerfile
```
The `server-image/Dockerfile` looks like this (narroved):
```
# Dockerfile used for the server images.
ARG BASEIMAGE
ARG BINARY
FROM "${BASEIMAGE}"
COPY ${BINARY} /usr/local/bin/${BINARY}
```
If I don't misinterpret this, K8s uses a unified server-image build and it should not be different for `kube-proxy`.

The size of the `kube-proxy` binary for amd64 in 7380fc735 is;
```
> ls -lh _output/bin/kube-proxy 
-rwxr-xr-x 1 jenkins jenkins 42M apr  9 23:01 _output/bin/kube-proxy*
> file _output/bin/kube-proxy 
_output/bin/kube-proxy: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=rbrNluRhdZbFGr88GEjX/vF7leeKwQpf-9topY0XM/jRf6xInFGp7ADAKu0VCj/DGZTnyww5ROAU5xjzQBm, stripped
```
It is stripped and can't easily be "made smaller" I guess.

**Comment by howardjohn** [comment]
We (Istio) would definitely be interested in sharing ownership (hopefully by upsteaming to distroless mainline) in the image we have if there is interest. Some other projects have expressed similar needs as well

**Comment by Riaankl** [comment]
![image](https://user-images.githubusercontent.com/61125752/162644338-70a1fc72-4ce2-494e-bca2-3a223262e7ad.png)

**Comment by Riaankl** [comment]
@dims kube-proxy make up 9% of current image data traffic

**Comment by mattmoor** [comment]
I threw together this little repo (based on our next-gen distroless infrastructure): https://github.com/mattmoor/iptables

It pushed ghcr.io/mattmoor/iptables:latest which on x64 is roughly another 5x smaller (musl vs. glibc):
```
docker images
REPOSITORY                  TAG       IMAGE ID       CREATED   SIZE
ghcr.io/mattmoor/iptables   latest    f306fe6d1d59   N/A       3.04MB
```

If folks are interested in this, I'd be happy to create a repo under `github.com/distroless` which is where we've been standing up new images, or you can create your own from github.com/distroless/template pretty easily.

**Comment by dims** [comment]
@mattmoor debian based please!! we have KEPs and stuff written that lay down that direction:
https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/1729-rebase-images-to-distroless/README.md

**Comment by BenTheElder** [comment]
For a possible approach https://github.com/kubernetes/kubernetes/issues/70249#issuecomment-1032224130 + above in that issue and https://github.com/kubernetes-sigs/kind/tree/main/images/haproxy for "distroless" debian based images with arbitrary C/C++ binaries + deps. 

Note that we need things besides just the distro binaries (see comment linked).

https://github.com/kubernetes-sigs/kind/blob/ca68f7d4a2528e071c2969be956ca83fc1ed048f/images/haproxy/stage-binary-and-deps.sh 
and 
https://github.com/kubernetes-sigs/kind/blob/ca68f7d4a2528e071c2969be956ca83fc1ed048f/images/haproxy/Dockerfile 
is pretty straightforward for one way to handle the debian binaries part.

**Comment by thockin** [comment]
I don't even know how we build the kube-proxy image.  Where does that happen and form which dockerfile?

Note we need iptables, iptables-save and iptables-restore but also ipvsadm, shell, conntrack, ipset, and maybe other tools

**Comment by BenTheElder** [comment]
It used to be in kubernetes/kubernetes under build/images, it's now in https://github.com/kubernetes/release/tree/master/images/build/debian-iptables (Dockerfile etc there)

**Comment by thockin** [comment]
That's the base - where is the logic to turn that into a kube-proxy image?

**Comment by BenTheElder** [comment]
Turning that image into a kube-proxy image is just adding the kube-proxy binary with a dockerfile and entirely too much bash 🙃 

https://github.com/kubernetes/kubernetes/blob/ae7982591481a42253f6061172180d79a8012317/build/lib/release.sh#L218

which ultimately just does:
https://github.com/kubernetes/kubernetes/blob/f33ca2306548719e5116b53fccfc278bffb809a8/build/server-image/Dockerfile#L17-L22

(except api-server, where we do a setcap in [`build/server-images/api-server/Dockerfile`](https://github.com/kubernetes/kubernetes/blob/f33ca2306548719e5116b53fccfc278bffb809a8/build/server-image/kube-apiserver/Dockerfile))

**Comment by rikatz** [comment]
/triage accepted
Will take a look between this and next week

**Comment by danwinship** [comment]
> We could even do `bash-static` for running the hack script we have for switching the symlinks when `nft` vs `legacy`:

It doesn't even need bash; the version of the script in https://github.com/kubernetes-sigs/iptables-wrappers intentionally avoids bash-specific features (and gets tested against Alpine where /bin/sh is busybox (which I guess is "ash"?)). And the version in kubernetes/release appears to be just a stripped-down version of that script. (But actually, you should update the script to be based on the latest version anyway, to get the new logic in https://github.com/kubernetes-sigs/iptables-wrappers/pull/3, in preparation for [KEP-3178](https://github.com/kubernetes/enhancements/issues/3178).)

**Comment by rikatz** [comment]
Probably per @dims [comments](https://github.com/kubernetes/kubernetes/issues/109406#issuecomment-1095445426) one of the things we don't want to do right now is jump into a musl based image like Alpine, right?

So I would take the case that we want to use distroless, and copy all the binaries we need to inside that container (conntrack, ipvs, iptables-*, etc etc).

@danwinship per iptables-wrapper, you said it's not bash specific so maybe we can use distroless + the smaller available shell? 

I will check some approaches here before jumping into changing the release/dockerfiles/whatever scripts, and check if I can run some comformance tests in a distroless k/proxy. Maybe starting with a good binary list is a way to cross check the binaries + libraries required for this distroless container.

**Comment by thockin** [comment]
I agree no musl/alpine

**Comment by BenTheElder** [comment]
If you identify the list of binaries, https://github.com/kubernetes-sigs/kind/blob/ca68f7d4a2528e071c2969be956ca83fc1ed048f/images/haproxy/stage-binary-and-deps.sh has logic to handle ldd for a binary (e.g. ignore vdso) + keep the copyright and package version info via dpkg.


We probably need a few more not in the list above for the other proxy modes?

**Comment by rikatz** [comment]
Thanks @BenTheElder this is gonna be very helpful! I will work on it using the script you provided during the week!

**Comment by rikatz** [comment]
From @BenTheElder script and some changes:
```
gcr.io/k8s-staging-build-image/debian-iptables-amd64   latest-distroless                       dc2ded813a62   20 seconds ago      30.4MB
gcr.io/k8s-staging-build-image/debian-iptables-amd64   latest-bullseye                         a4f7340840c1   32 minutes ago      68.2MB
```

There's a pretty good reduction of size (50%). But this is without kproxy binary, that is almost 40Mb.

I will open a Draft PR in k/release so we can discuss over there the approach. BTW, anyone knows why kube-proxy binary is that big? Never digged into that, but curious about it.

**Comment by aojea** [comment]
> BTW, anyone knows why kube-proxy binary is that big? Never digged into that, but curious about it.

https://dr-knz.net/go-executable-size-visualization-with-d3-2021.html

https://github.com/knz/go-binsize-viz

```
< cd to your kubernetes repo >
$ go build ./cmd/kube-proxy
$ ls -altrh kube-proxy
-rwxrwxr-x   1 aojea aojea  58M abr 19 10:02 kube-proxy
$ strip kube-proxy
$ ls -altrh kube-proxy
-rwxrwxr-x 1 aojea aojea 41M abr 19 10:03 kube-proxy
$ docker run -v $PWD:/tmp/bin -p 8000:8000 odedp/go-binsize-viz -b kube-proxy
< open http://localhost:8000 >
```

![image](https://user-images.githubusercontent.com/6450081/163955864-63baf4f2-8cdc-4927-9b13-40e5502f00f6.png)

**Comment by uablrek** [comment]
> I agree no musl/alpine

Is there a reason or just emotional?

The `kube-proxy` binary is statically linked so it does not need or use `musl`, it only needs some binaries to be executable and it doesn't matter if _they_ are built with musl. They just have to work.

I have sucessfully built and executed my own tests, both with proxy-mode `iptables` _and_ `ipvs`, using an image built with this `Dockerfile`:
```
ARG BINARY=kube-proxy
FROM alpine:latest
RUN apk add iptables ip6tables ipset
ADD https://raw.githubusercontent.com/kubernetes-sigs/iptables-wrappers/master/iptables-wrapper-installer.sh /iptables-wrapper-installer.sh
RUN chmod a+x /iptables-wrapper-installer.sh; /iptables-wrapper-installer.sh
COPY ${BINARY} /usr/local/bin/${BINARY}
```
The image size on cluster _including_ the `kube-proxy` binary (~40MB) is;
```
vm-003 ~ # crictl --runtime-endpoint=unix:///var/run/crio/crio.sock images | grep kube-proxy
k8s.gcr.io/kube-proxy                       local               997f5c9fdb549       53MB
```
(I use a private local registry)

**Comment by rikatz** [comment]
@uablrek what about the different iptables-nft vs iptables-legacy binaries?

**Comment by uablrek** [comment]
I have assumed that [iptables-wrappers](https://github.com/kubernetes-sigs/iptables-wrappers#building-a-container-image-that-uses-iptables) takes care of that.

**Comment by neolit123** [comment]
Re size: Are DWARF2 symbols stripped? Ideally k8s should produce artifacts without DWARF2 symbols and distribute them separatelly. Or produce the optional -debug artifacts. This can cut GCR/GCS costs, but introduce some debug/profiling complexity. The Go symbol table should be always included.

Related https://github.com/golang/go/issues/51692

**Comment by rikatz** [comment]
> I have assumed that [iptables-wrappers](https://github.com/kubernetes-sigs/iptables-wrappers#building-a-container-image-that-uses-iptables) takes care of that (executed by the Dockerfile).

IIRC wrapper in prod needs both binaries existing in the container, and will use this in a way to check if the host machine is using iptables-legacy or iptables-nft.

**Comment by uablrek** [comment]
Both exist in Alpine;
```
/ # ls /sbin/xtables-*
/sbin/xtables-legacy-multi  /sbin/xtables-monitor       /sbin/xtables-nft-multi
```
The first example in [iptables-wrappers](https://github.com/kubernetes-sigs/iptables-wrappers#building-a-container-image-that-uses-iptables) is Alpine. @danwinship can you please confirm that it works with Alpine?

**Comment by uablrek** [comment]
Tested the [Alpine kube-proxy](https://github.com/kubernetes/kubernetes/issues/109406#issuecomment-1102593687) with K8s e2e;
```
export FOCUS='\[sig-network\].*ervice'
export SKIP='Disruptive|Serial|affinity|DNS|GCE|finalizer'
....
Ran 74 of 7453 Specs in 302.233 seconds
SUCCESS! -- 74 Passed | 0 Failed | 0 Pending | 7379 Skipped
```

**Comment by thockin** [comment]
There are / we're legal reasons to avoid Alpine.  Have those been
resolved?  I haven't heard anything.

**Comment by dims** [comment]
@thockin i don't think so. it's status quo on Alpine which is to avoid it totally.

**Comment by uablrek** [comment]
> There are / we're legal reasons to avoid Alpine.

Can I read about those somewhere? Are the legal reasons about Alpine? Or about musl?

**Comment by BenTheElder** [comment]
Not my personal decision, and I'm not a lawyer let alone an OSS license expert but ... sharing what I know on the subject:

----

IIRC for example Alpine does not make available the source code (AFAICT Alpine publishes source code for the packaging scripts, but not the package sources), or even the LICENSE of binary packages, which is problematic for compliance with licenses ... (Various common license require including the license text, and / or making source code available).


https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package#license

> Because we want to save space and don't like to have licenses all over our system we have decided to include the license in the doc subpackage. 

Normal alpine images don't appear to install these doc packages:
```sh
$ docker run --rm alpine ls /usr/share/licenses
ls: /usr/share/licenses: No such file or directory
```

So those images don't even ship with license / copyright info files for packages which is ... not a great start.

I'm not sure where a good public reference is for this, Google OSPO has some relevant docs internally about following license requirements when producing container images.

So far the best public doc on the topic I've found is https://lwn.net/Articles/786066/

**Comment by uablrek** [comment]
@BenTheElder Thanks!

**Comment by uablrek** [comment]
TL:DR;

> The final query was about Alpine Linux, which is used as the base distribution for many container images. The attendee noted that Alpine strips all of the license files from its layer. Hohndel said that it is worse than that, in that Alpine strips all information about versions, except those actually stored in the individual binaries, from its layers. It makes it essentially impossible to comply with the licenses of the packages that it uses (e.g. BusyBox). Another attendee said that they have some contacts at Alpine and suggested that might be a path toward resolving the problem.

**Comment by danwinship** [comment]
> Probably per @dims [comments](https://github.com/kubernetes/kubernetes/issues/109406#issuecomment-1095445426) one of the things we don't want to do right now is jump into a musl based image like Alpine, right?

I wasn't suggesting switching to Alpine, I was just saying that I unit test the iptables-wrappers scripts against Alpine, which doesn't use bash, and so I know the scripts don't require bash.

> So I would take the case that we want to use distroless, and copy all the binaries we need to inside that container (conntrack, ipvs, iptables-*, etc etc).
> 
> @danwinship per iptables-wrapper, you said it's not bash specific so maybe we can use distroless + the smaller available shell?

Yeah, I don't know the details of how distroless works, but if we're talking about debian packages then it looks like [dash](https://packages.debian.org/buster/shells/dash) is 1/10 the size of [bash-static](https://packages.debian.org/buster/shells/bash-static) (212k vs 2285k)

**Comment by danwinship** [comment]
> > I have assumed that [iptables-wrappers](https://github.com/kubernetes-sigs/iptables-wrappers#building-a-container-image-that-uses-iptables) takes care of that (executed by the Dockerfile).
> 
> IIRC wrapper in prod needs both binaries existing in the container, and will use this in a way to check if the host machine is using iptables-legacy or iptables-nft.

In Alpine (and Debian, and probably most distros other than Fedora), the "iptables" package includes both the legacy and nft binaries, so that's the only dependency.

**Comment by uablrek** [comment]
Made a comment on bandwidth that may be better in this issue rahter than the PR;
https://github.com/kubernetes/release/pull/2502#discussion_r862328781

**Comment by rikatz** [comment]
Want to give a quick update on this:

* The image generation is working "fine", see: https://github.com/kubernetes/release/pull/2502/files
  * This process generates a temporary `gcr.io/k8s-staging-releng-test/debian-iptables:distroless-v1.0.0` that can be used later with `make quick-release-images` and/or changed in Kubernetes code to trigger the tests (see #110587)
  * Due to the way iptables-wrapper-installer works, it calls iptables-legacy and iptables-nft to check if they are working fine. We need to skip it (via --skip-integrity-check) in arch not amd64, as those are really specific kernel features and when called from arm64, as an example the command ends in an error.
  * We need /bin/sleep to be present in distroless as well, due specifically to this image being used in this test: https://github.com/kubernetes/kubernetes/blob/v1.24.2/test/e2e/network/kube_proxy.go#L111
  * cloud-build timeout needs to be increased, it takes a long time for arm/s390/etc to build this
  * The image can be optimized a bit more, removing some steps like linking the iptables binaries (as pointed by @BenTheElder) and removing some binaries like wc (as pointed by @danwinship ) but right now I didn't wanted to change the image build AND the iptables-wrapper script. My take here would be: let's see now with sig-release if the build process is fine, get this image promoted and used before v1.25

* All the tests but verify ran fine (verify due to dependency check, etc etc) - https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=110587
Here are the main tests with the distroless image:
  - kind - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110587/pull-kubernetes-e2e-kind/1538011441360015360
  - kind ipv6 - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110587/pull-kubernetes-e2e-kind-ipv6/1538011442203070464
  - gce ipvs - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110587/pull-kubernetes-e2e-gci-gce-ipvs/1538011446820999168
  - performance 100 nodes - https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110587/pull-kubernetes-e2e-gce-100-performance/1538011449752817664


@dims @robscott @cpanato @puerco fyi. I can bring this to next sig-net meeting, wanted to check:
* from sig/release perspective, is the PR [#release/2502](https://github.com/kubernetes/release/pull/2502) fine? I will make some more changes here, but wanted even to check if this should be called debian-iptables:distroless or something like `distroless-iptables:version`
* from sig/net if we want to move forward migrating the iptables-wrapper to shell script this release or not. I tend of agree with Rob that maybe we are getting too many changes in one release, and we can plan this for v1.26 (the PR is already there, I need to check Dan's comments only)

Thanks

**Comment by aojea** [comment]
/reopen

let's close it once we switch to the new image

**Comment by dpasiukevich** [comment]
Hi, @aojea @rikatz 

Could you suggest if it's ok to use `gcr.io/k8s-staging-build-image/distroless-iptables:v0.1.0` already?

That would be super cool to use the image as a base for NodeLocalDNS (as it uses iptables). I already did manual smoke test in cluster - all is working correctly.

Thanks!

**Comment by aojea** [comment]
Let's introduce it gradually, I suggest to wait until the image is promoted for kube-proxy

**Comment by robscott** [comment]
@aojea @rikatz I've lost track of this, what do we need to do to promote it for kube-proxy?

**Comment by aojea** [comment]
I think Ricardo was on it  https://kubernetes.slack.com/archives/C2C40FMNF/p1656642321639849

But if someone is busy and others have time, let's sync next monday on slack and organize the work, so someone can get this to the finish line, there is no need to overload one person if there are other wanting to help

**Comment by rikatz** [comment]
I didn’t saw there was a comment there.

I can fix that, and wanted to plan with you folks next steps. I agree with
Antonio and don’t want to block this on my availability :)

I will check @cpanato suggestion tomorrow and as we get this merged I’m
more than happy to handle to someone else!

**Comment by rikatz** [comment]
@robscott @aojea I've opened a new PR to do the proper promotion.

As soon as this is promoted I think we can start testing and migrating to distroless :)

From here I think I can handle to someone else as I wont have much time and attention to this specific effort and I know this is important :)

I'm still willing to migrate iptables-wrapper to go code (we started it in kubernetes-sigs/iptables-wrapper) so I will probably finish fixing Dan's reviews and we can discuss the distroless v0.2.0 being based entirely in Go :)

**Comment by BenTheElder** [comment]
we should probably nudge a few of the subprojects to migrate, we just migrated KIND https://github.com/kubernetes-sigs/kind/pull/2841 but I'm sure we have at least a few more out there like ip-masq-agent

**Comment by dpasiukevich** [comment]
I'm migrating nodelocaldns.

I've got a couple of questions:
1. currently nodelocaldns uses `k8s.gcr.io/build-image` registry [link](https://github.com/kubernetes/dns/blob/41b8fab19705b3c3728819398fafe274224bbdfe/rules.mk#L35). Should I switch it to `registry.k8s.io/build-image`? Is `registry.k8s.io` considered sort of a prod image registry?
2. Is `registry.k8s.io/build-image/distroless-iptables:v0.1.1` a multi-arch image? Because currently we use `debian-iptables-$(ARCH):bullseye-v1.5.0`
3. How is it better to keep up with the new tags for `distroless-iptables`? So that we could quickly upgrade base image version as well?

Thanks for the work!

**Comment by rikatz** [comment]
> 1. currently nodelocaldns uses `k8s.gcr.io/build-image` registry [link](https://github.com/kubernetes/dns/blob/41b8fab19705b3c3728819398fafe274224bbdfe/rules.mk#L35). Should I switch it to `registry.k8s.io/build-image`? Is `registry.k8s.io` considered sort of a prod image registry?

YES! Make @dims happy! This registry is actually a "proxy" that sig-k8s-infra is maintaining so people get directed to the closest Image registry, based on their cloud provider. As an example, with this users in AWS wont need to go to GCR to pull their image

> 2. Is registry.k8s.io/build-image/distroless-iptables:v0.1.1 a multi-arch image? Because currently we use debian-iptables-$(ARCH):bullseye-v1.5.0

Yes, it is. It follows the same build pattern of debian-iptables. See https://github.com/kubernetes/release/blob/master/images/build/distroless-iptables/Makefile#L27

> 3. How is it better to keep up with the new tags for distroless-iptables? So that we could quickly upgrade base image version as well?

Well, this is a good question. AFAIK we don't have an event / notification system that sends a message (in Slack, as an example) whenever a base image gets promoted. It would be cool to have at least for debian-base, debian-iptables and distroless-iptables, probably it's worth to question sig-release on this :) (@cpanato @puerco maybe know)

**Comment by dpasiukevich** [comment]
Thanks for the answer!

Regarding the `k8s.gcr.io/build-image/debian-base` - we use it as a compile image. Will this image still be supported or should I find something other to replace this compile image?

**Comment by rikatz** [comment]
> Regarding the k8s.gcr.io/build-image/debian-base - we use it as a compile image for dnsmasq. Will this image still be supported or should I find something other to replace this compile image?

Short answer:
I imagine/suppose there is no deprecation plan for this image right now, as it is used as the compilation base for a bunch of other things (and it is base of etcd image)

Long answer:
In case of distroless-iptables the rationale was: 
* we need to reduce costs (and by reducing costs, reducing image size)
* we need to use something with a smaller footprint and reduce the amount of packages, and as a result the amount of CVEs in image package.
* kube-proxy exists in all nodes (unless you use a CNI that implements its features) so it is a good candidate

I guess right now debian-base will still be used (I don't remember on the top of my head if other kubernetes components are already running using distroless or compiled based on debian-base, as far as I can see at least etcd image depends on debian-base (https://github.com/kubernetes/kubernetes/blob/8e14585d8700d9cf7861be66943f023d11d41075/build/dependencies.yaml#L117) so probably any effort on this image should be announced.
