### ISSUE TITLE
Hard to understand why a secret of type kubernetes.io/service-account-token referencing an invalid service account gets deleted

### ISSUE THREAD

**Issue by pst** [kubernetes/kubernetes#109401]
### What happened?

Creating a secret of `type: kubernetes.io/service-account-token` with the `kubernetes.io/service-account.name` annotation pointing to a service account that does not exist yet will return success. Yet a subsequent read after create will fail.

If creating the SA and the secret in correct order and then deleting the SA, the secret is deleted as well.

I assume this garbage collection is the root cause of this behavior. The secret does actually get created, but then the SA does not exist and the GC is so quick to delete the secret again, that the create succeeds, but the subsequent get fails.

### What did you expect to happen?

I expect the API server to return an error to the create request, not success.

The API server should check for existence of the service account specified in the annotation and if it doesn't exist yet, refuse to create the secret. As it stands now, this would have to be handled by API clients, which is the most inefficient layer to address this issue.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: sa-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: non-existent-sa
type: kubernetes.io/service-account-token

```

kubectl create -f secret.yaml
kubectl get secret sa-token

### Anything else we need to know?

I understand it's documented, that the [SA needs to exist](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets). And while I think there's a bigger discussion about how to make such use-cases more declarative in the K8s API (e.g. via superset kinds) this issue is only about the API response.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fedebongio** [comment]
Discussed in the triage meeting. Yu kindly agreed to explain. 
/assign @yliaog 
/triage accepted

**Comment by liggitt** [comment]
/remove-kind bug
/kind documentation

Service account token secrets are maintained by the service account token controller.

A token referencing a service account that does not exist is invalid and is deleted by the token controller.

Cross-object synchronous validation is avoided wherever possible in the API.

**Comment by liggitt** [comment]
Given the documentation already references [the requirement that the service account exist](https://kubernetes.io/docs/concepts/configuration/secret/#service-account-token-secrets), it's not clear what else should be added here

**Comment by liggitt** [comment]
Transferring to auth since serviceaccounts and the token controller are under that sig

**Comment by liggitt** [comment]
Since this issue is narrowly about the API response, and the API response is correct (since the secret *was* created, even if it was then rapidly deleted by an asynchronous controller), I don't think there is anything to modify with the API response.

/close

**Comment by yliaog** [comment]
agreed. k8s API is eventually consistent, the current behavior is expected.

**Comment by pst** [comment]
👎
