### ISSUE TITLE
can't enable MixedProtocolLBService

### ISSUE THREAD

**Issue by ruben-herold** [kubernetes/kubernetes#109439]
### What happened?

I try to setup an IPv6 only cluster with MixedProtocolLBService=true:

`kubeadm init --apiserver-advertise-address "{{ ansible_default_ipv6.address }}" --pod-network-cidr "{{ pod_network }}" --service-cidr "{{ srv_network }}" --service-dns-domain "{{ dns_domain }}" --upload-certs --control-plane-endpoint "{{ ctrl_plane_endpoint }}" --feature-gates MixedProtocolLBService=true
`
I got:

`unrecognized feature-gate key: MixedProtocolLBService`

### What did you expect to happen?

enable the feature-gate

### How can we reproduce it (as minimally and precisely as possible)?

See command above 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none bare metal self hosted
</details>

### OS version

<details>

```console
cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

</details>

### Install tools

<details>
ansible kubeadm 
</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-tools-1.23.0-0.x86_64
cri-o-1.23.1-2.4.el8.x86_64
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.22.1
</details>

**Comment by aojea** [comment]
I think that feature-gate flag is for kubeadm, not for kubernetes feature-flags

https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/

/cc @neolit123

**Comment by neolit123** [comment]
nope, it's a k8s core feature gate:

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
> MixedProtocolLBService: Enable using different protocols in the same LoadBalancer type Service instance.
