### ISSUE TITLE
Add documentation for “non exhaustive enums”

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#109463]
### What happened?

_Following a [bugfix](https://github.com/kubernetes/kubernetes/issues/109463#issuecomment-1098195262)_, we now have a gap where these non-exhaustive, enum-like field values are not documented. Folks will previously have found those explanations useful.

See https://github.com/kubernetes/website/pull/32833#pullrequestreview-938396627 for an example where the v1.23 docs enumerate taint effects and list meanings (`NoExecute`, `NoSchedule` and `PreferNoSchedule`) but the v1.24 docs won't.

https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/node-v1/#NodeSpec is the URL of the v1.23 docs at the time of writing; that will soon change to be https://v1-23.docs.kubernetes.io/docs/reference/kubernetes-api/cluster-resources/node-v1/

### What did you expect to happen?

What I hoped for: _API reference information covers known field values, even when the field values known to Kubernetes are not exhaustive._

Aside: I think there are multiple ways to tackle this issue. I don't have a strong view on which might be the best approach.

### How can we reproduce it (as minimally and precisely as possible)?

(After the v1.24 release) look at the API reference for Node. See if the possible effects are enumerated and explained.

### Anything else we need to know?

This issue covers 3 repos:

- [k/kubernetes](https://github.com/kubernetes/kubernetes/)
- [k/website](https://github.com/kubernetes/website/)
- [k-sigs/reference-docs](https://github.com/kubernetes-sigs/reference-docs/)

### Kubernetes version

v1.24

### Cloud provider

Netlify :wink:

### OS version

_not applicable_

### Install tools

_not applicable_

### Container runtime (CRI) and version (if applicable)

_not applicable_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_not applicable_

**Comment by liggitt** [comment]
Note that the inclusion of these in 1.23 docs was an accident... the feature was in alpha state and should not have been enabled in 1.23. The openapi file in release-1.23 and master branches once again has the same amount of information as the API definition in release-1.22

**Comment by sftim** [comment]
Ah, got it.

Definitely a feature request, then.

**Comment by shikha-varun** [comment]
I am a beginner and willing to work on with some guidance if fine please assign to me

**Comment by sftim** [comment]
/remove-lifecycle rotten
/retitle Add documentation for “non exhaustive enums”
