### ISSUE TITLE
`kubectl get all` does not list all resources

### ISSUE THREAD

**Issue by guettli** [kubernetes/kubernetes#109408]
### What happened?

I execute `kubectl get all ` 

### What did you expect to happen?

I expect to see all resouces

### How can we reproduce it (as minimally and precisely as possible)?

`kubectl get all`

### Anything else we need to know?

Related: https://stackoverflow.com/questions/47691479/listing-all-resources-in-a-namespace

It would be great to have a way to search all resources with `kubectl`.

Workarounds like this are not nice:

> alias k8s-show-ns=" kubectl api-resources --verbs=list --namespaced -o name  | xargs -n 1 kubectl get --show-kind --ignore-not-found  -n"

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-17T03:51:43Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

.

### OS version

.

### Install tools

.

### Container runtime (CRI) and version (if applicable)

.

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@guettli this was one of my first PRs to this project :) https://github.com/kubernetes/kubernetes/pull/28955

Sorry we will not be doing that. please see reasons in the PR above.
