### ISSUE TITLE
kubectl cp 8g.tar <some-namespace>/<some-pod>:/tmp/bar 

### ISSUE THREAD

**Issue by day112** [kubernetes/kubernetes#109474]
### What happened?

1. file  8g.tar > 8GB，Copy 8g.tar  local file to / in a remote pod in namespace <some-namespace>, will create 0kb 8g.tar 

### What did you expect to happen?

kubectl cp 8g.tar admin/op-containers-k8s:/ , file  8g.tar > 8GB

### How can we reproduce it (as minimally and precisely as possible)?

kubectl cp 8g.tar admin/op-containers-k8s:/   

### Anything else we need to know?

tar cf - 8g.tar | kubectl exec -i -n admin  op-containers-k8s -- tar xvft - -C /            is  ok

### Kubernetes version

<details>

```console
$ kubectl version
v1.21.0-beta.1.323+045b5ddd0b8aa7-dirty
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
Client:
 Version:      17.03.3
 OS/Arch:      linux/amd64

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
maybe dup with #60140

**Comment by j143** [comment]
A workaround would be to mount a volume to the pod. and copy file to that volume.
