### ISSUE TITLE
Improve the HPA observability by add a calculated replicas in metric status of each metric

### ISSUE THREAD

**Issue by kitianFresh** [kubernetes/kubernetes#109538]
### What would you like to be added?

When we configured HPA with multiple metrics, we want to monitoring the replica proposal calculated by each metric, so we can monitoring the calculated replica proposal of each metric and visualize it on grafana.  I want to add some fields in hpa status

### Why is this needed?

HPA has some risks for application autoscaling, so improve the hpa observability  is essential.  There multiple metrics can trigger the workload to scale, but the replicas proposal by each metric is not observable.

**Comment by pbetkier** [comment]
I agree it would be a useful feature, the current HPA observability is not enough. Could you propose the changes here for discussion before preparing a PR?
