### ISSUE TITLE
ci-cadvisor-e2e failed

### ISSUE THREAD

**Issue by qiutongs** [kubernetes/kubernetes#109555]
### Which jobs are failing?

ci-cadvisor-e2e

### Which tests are failing?

- TestDockerContainerSpec
- TestDockerContainerCpuStats
- FAIL: TestMachineStatsIsReturned

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cadvisor-e2e/1516314198211039232

### Since when has it been failing?

04/15/2022

### Testgrid link

https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e

### Reason for failure (if possible)

See test log in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cadvisor-e2e/1516314198211039232

### Relevant SIG(s)

/sig node
/area cadvisor

**Comment by qiutongs** [comment]
cc @bobbypage

**Comment by pacoxu** [comment]
```
W0419 07:20:21.567] === RUN   TestDockerContainerSpec
W0419 07:20:21.567] I0419 07:19:46.485204     978 framework.go:333] About to run - [sudo docker run -d --cpu-shares 2048 --cpuset-cpus 0 --memory 1073741824 --env TEST_VAR=FOO --label bar=baz kubernetes/pause]
W0419 07:20:21.567]     docker_test.go:214: 
W0419 07:20:21.567]         	Error Trace:	docker_test.go:214
W0419 07:20:21.568]         	Error:      	Not equal: 
W0419 07:20:21.568]         	            	expected: 0x800
W0419 07:20:21.568]         	            	actual  : 0x7fe
W0419 07:20:21.568]         	Test:       	TestDockerContainerSpec
W0419 07:20:21.568]         	Messages:   	Container should have 2048 shares, has 2046
```

This is really odd to me.

**Comment by bobbypage** [comment]
This is likely due to cos update from cos-89-lts to cos-97-lts. cos-97-lts has switched to cgroupv2 by default. The e2e tests in cAdvisor may be hard coding some expected values based on cgroupv1 and will need to be updated.

**Comment by SergeyKanzhelev** [comment]
Looks green now. Closing and will monitor

/close

**Comment by bobbypage** [comment]
for future reference (this was fixed by https://github.com/kubernetes/test-infra/pull/25970/)
