### ISSUE TITLE
Curl pipe to shell for docker in e2e tests setup

### ISSUE THREAD

**Issue by wespanther** [kubernetes/kubernetes#109577]
### What happened?

setup_host.sh in e2e_node test curls https://get.docker.com and directly pipes to shell:

https://github.com/kubernetes/kubernetes/blob/f173d01c011c3574dea73a6fa3e20b0ab94531bb/test/e2e_node/environment/setup_host.sh#L82-L84

The issue is that this may present a supply chain security risk, as we are directly executing the script from get.docker.com.

### What did you expect to happen?

I would instead expect one of the following:

1. The host includes docker already via it's OS image
2. The script is checked into this repo and version controlled
3. The script is at least verified to be unchanged via hash

### How can we reproduce it (as minimally and precisely as possible)?

Running anything from - https://github.com/kubernetes/community/blob/master/contributors/devel/sig-node/e2e-node-tests.md, such as:

```
make test-e2e-node REMOTE=true
```

### Kubernetes version

All

### Cloud provider

GCP (kind of)

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by BenTheElder** [comment]
that's some pretty old bash, I don't think we're actually using this in CI, probably that codepath can just be dropped, but up to the SIG node folks.

**Comment by SergeyKanzhelev** [comment]
the script is being referred from the docs: https://github.com/kubernetes/community/blob/a080c54dee5249f307e129f83277e1f564df2a96/contributors/devel/sig-node/e2e-node-tests.md#L142

I think the safest bet is to simply remove the docker installation part.
