### ISSUE TITLE
Perma failing Jobs in test-grid

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109521]
Folks we have a bunch of jobs that are all 🔴 Let's use this as a umbrella issue. Please find jobs that belong to you SIG or the area you are working on and leave me a note for a follow up issue or PR, so we can trim this down over time. If we don't really need a job, we should just remove it!

Also, if you find other jobs in test-grid that are failing constantly, let me know and i'll add them to the list here. thanks!

Link to cs.k8s.io / Link to test-grid
=========================
- [x] [ci-containerd-e2e-cos-gce-1-4](https://cs.k8s.io/?q=ci-containerd-e2e-cos-gce-1-4) / [containerd-e2e-cos-1.4](https://testgrid.k8s.io/sig-node-cos#containerd-e2e-cos-1.4) **[REMOVED](https://github.com/kubernetes/test-infra/pull/25977)**
- [ ] [ci-containerd-soak-cos-gce](https://cs.k8s.io/?q=ci-containerd-soak-cos-gce) / [soak-cos-gce](https://testgrid.k8s.io/sig-node-cos#soak-cos-gce)
- [ ] [ci-cri-containerd-e2e-cos-gce-flaky](https://cs.k8s.io/?q=ci-cri-containerd-e2e-cos-gce-flaky) / [e2e-cos-flaky](https://testgrid.k8s.io/sig-node-cos#e2e-cos-flaky)
- [ ] [ci-crio-cgroupv1-node-e2e-alpha](https://cs.k8s.io/?q=ci-crio-cgroupv1-node-e2e-alpha) / [ci-crio-cgroupv1-node-e2e-alpha](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-alpha)
- [ ] [ci-crio-cgroupv1-node-e2e-eviction](https://cs.k8s.io/?q=ci-crio-cgroupv1-node-e2e-eviction) / [ci-crio-cgroupv1-node-e2e-eviction](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-eviction)
- [ ] [ci-crio-cgroupv1-node-e2e-flaky](https://cs.k8s.io/?q=ci-crio-cgroupv1-node-e2e-flaky) / [ci-crio-cgroupv1-node-e2e-flaky](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky)
- [ ] [ci-kubernetes-node-kubelet-serial-cri-o](https://cs.k8s.io/?q=ci-kubernetes-node-kubelet-serial-cri-o) / [node-kubelet-serial-crio](https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio)
- [ ] [ci-ingress-gce-e2e](https://cs.k8s.io/?q=ci-ingress-gce-e2e) / [ingress-gce-e2e](https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e)
- [ ] [ci-ingress-gce-e2e-scale](https://cs.k8s.io/?q=ci-ingress-gce-e2e-scale) / [ingress-gce-e2e-scale](https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e-scale)
- [x] [ci-kubemci-ingress-conformance](https://cs.k8s.io/?q=ci-kubemci-ingress-conformance) / [kubemci-ingress-conformance](https://testgrid.k8s.io/sig-multicluster-kubemci#kubemci-ingress-conformance)
- [ ] [ci-kubernetes-multicluster-ingress-test](https://cs.k8s.io/?q=ci-kubernetes-multicluster-ingress-test) / [ci-kubemci-unit-tests](https://testgrid.k8s.io/sig-multicluster-kubemci#ci-kubemci-unit-tests)
- [ ] [ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-parallel](https://cs.k8s.io/?q=ci-kubernetes-e2e-gce-stable1-latest-upgrade-cluster-parallel) / [gce-stable1-latest-upgrade-cluster-parallel](https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-cluster-parallel)
- [ ] [ci-kubernetes-e2e-gce-stable1-latest-upgrade-master-parallel](https://cs.k8s.io/?q=ci-kubernetes-e2e-gce-stable1-latest-upgrade-master-parallel) / [gce-stable1-latest-upgrade-master-parallel](https://testgrid.k8s.io/google-gce-upgrade#gce-stable1-latest-upgrade-master-parallel)
- [x] [ci-kubernetes-e2e-gce-taint-evict](https://cs.k8s.io/?q=ci-kubernetes-e2e-gce-taint-evict) / [gce-taint-evict](https://testgrid.k8s.io/google-gce#gce-taint-evict)
- [x] [ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://cs.k8s.io/?q=ci-kubernetes-e2e-gci-gce-alpha-enabled-default) / [gci-gce-alpha-enabled-default](https://testgrid.k8s.io/google-gce#gci-gce-alpha-enabled-default) **[FIXED](https://github.com/kubernetes/test-infra/pull/25980)**
- [ ] [ci-kubernetes-e2e-gci-gce-flaky](https://cs.k8s.io/?q=ci-kubernetes-e2e-gci-gce-flaky) / [gci-gce-flaky](https://testgrid.k8s.io/google-gce#gci-gce-flaky)
- [ ] [ci-kubernetes-e2e-gci-gce-flaky-repro](https://cs.k8s.io/?q=ci-kubernetes-e2e-gci-gce-flaky-repro) / [gce-cos-master-flaky-repro](https://testgrid.k8s.io/google-gce#gce-cos-master-flaky-repro)
- [ ] [ci-kubernetes-e2e-node-canary](https://cs.k8s.io/?q=ci-kubernetes-e2e-node-canary) / [node (sig-testing-canaries)](https://testgrid.k8s.io/sig-testing-canaries#node)
- [x] [ci-kubernetes-e2e-prow-canary](https://cs.k8s.io/?q=ci-kubernetes-e2e-prow-canary) / [prow (sig-testing-canaries)](https://testgrid.k8s.io/sig-testing-canaries#prow)
- [ ] [ci-kubernetes-generate-make-test-count10](https://cs.k8s.io/?q=ci-kubernetes-generate-make-test-count10) / [ci-kubernetes-generate-make-test-count10](https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-generate-make-test-count10)
- [x] [ci-kubernetes-e2e-windows-gce-2004-1-21](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-2004-1-21) / [gce-windows-2004-1.21](https://testgrid.k8s.io/google-windows#gce-windows-2004-1.21)
- [x] [ci-kubernetes-e2e-windows-gce-2004-1-22](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-2004-1-22) / [gce-windows-2004-1.22](https://testgrid.k8s.io/google-windows#gce-windows-2004-1.22)
- [x] [ci-kubernetes-e2e-windows-gce-2004-1-23](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-2004-1-23) / [gce-windows-2004-1.23](https://testgrid.k8s.io/google-windows#gce-windows-2004-1.23)
- [ ] [ci-kubernetes-e2e-windows-gce-2019](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-2019) / [gce-windows-2019-master](https://testgrid.k8s.io/google-windows#gce-windows-2019-master)
- [ ] [ci-kubernetes-e2e-windows-gce-2019-1-23](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-2019-1-23) / [gce-windows-2019-1.23](https://testgrid.k8s.io/google-windows#gce-windows-2019-1.23)
- [ ] [ci-kubernetes-e2e-windows-gce-20h2-1-23](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-20h2-1-23) / [gce-windows-20h2-1.23](https://testgrid.k8s.io/google-windows#gce-windows-20h2-1.23)
- [x] [ci-kubernetes-e2e-windows-gce-alpha-features](https://cs.k8s.io/?q=ci-kubernetes-e2e-windows-gce-alpha-features) / [gce-windows-2019-master-alpha-features](https://testgrid.k8s.io/google-windows#gce-windows-2019-master-alpha-features) **[FIXED](https://github.com/kubernetes/test-infra/pull/25979)**
- [x] [ci-kubernetes-azure-conformance-ipv6](https://cs.k8s.io/?q=ci-kubernetes-azure-conformance-ipv6) / [ci-kubernetes-azure-conformance-ipv6](https://testgrid.k8s.io/provider-azure-cloud-provider-azure#ci-kubernetes-azure-conformance-ipv6)

**Comment by SergeyKanzhelev** [comment]
a few cross links:
- https://github.com/kubernetes/test-infra/issues/25430
- https://github.com/kubernetes/kubernetes/issues/107802
- https://github.com/kubernetes/kubernetes/issues/109295
- https://github.com/kubernetes/test-infra/issues/25372


For soak test I am not sure how the test infra decides to re-creates the nodes and master, failure seems to be due to disk being full, I cannot ssh to the node to check what consumes it.

For a few containerd tests  the image config `jobs/e2e_node/containerd/containerd-master/image-config.yaml` seems to be broken and doesn't install CNI properly

Are we merging fixes? I thought we are in a test freeze =)

**Comment by marosset** [comment]
Windows Server 2004 has been out of support since Dec 2021. 
I will delete the gce-windows-2004 jobs today 
https://docs.microsoft.com/en-us/lifecycle/announcements/windows-server-version-2004-end-of-servicing

**Comment by dims** [comment]
xref: https://github.com/kubernetes/test-infra/issues/18600

**Comment by ritazh** [comment]
cc @aramase

**Comment by aramase** [comment]
> @aramase can you PTAL at ci-kubernetes-azure-conformance-ipv6

Thanks for the ping @ritazh! Dims reached out to me on slack. We are in the process of migrating ipv6 and dual-stack jobs to use CAPZ, so I'll open a PR to remove these old jobs in the mean time.

**Comment by pacoxu** [comment]
[ingress-gce-e2e](https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e) is fixed in https://github.com/kubernetes/kubernetes/issues/106402 by https://github.com/kubernetes/test-infra/pull/24379.

**Comment by aojea** [comment]
[ingress-gce-e2e-scale](https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e-scale) fixed

**Comment by aojea** [comment]
https://testgrid.k8s.io/sig-network-ingress-gce-e2e#ingress-gce-e2e fixed
