### ISSUE TITLE
Can we add `UpdateTimestamp` field in the metadata to show the last update time?

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#109522]
### What would you like to be added?

According to the design doc:
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata

The metadata block contains `CreationTimestamp` and `DeletionTimestamp`, but no `UpdateTimestamp`, some considerations?
so can we add it like this below?
```
type ObjectMeta struct {
	// +optional
	CreationTimestamp Time `json:"creationTimestamp,omitempty" protobuf:"bytes,8,opt,name=creationTimestamp"`
	
	// +optional
	UpdateTimestamp Time `json:"updateTimestamp,omitempty" protobuf:"bytes,x,opt,name=updateTimestamp"`
	
	// +optional
	DeletionTimestamp *Time `json:"deletionTimestamp,omitempty" protobuf:"bytes,9,opt,name=deletionTimestamp"`
}
```

### Why is this needed?

There are many senarios that we want to check the last update time of resource objects, but currently there is lack of such a field to indicate it.

Clients or Controllers may update the resource objects at any time, e.g: kubectl apply/edit xxx, controller reconcile logic.
So it is useful and convenient if there is a `UpdateTimestamp` field in the metadata.

**Comment by liggitt** [comment]
This was effectively already requested in https://github.com/kubernetes/kubernetes/issues/73548, and effectively already exists as `.metadata.managedFields[*].time`

**Comment by astraw99** [comment]
Got it, thanks :)

**Comment by fedebongio** [comment]
/triage accepted
Thank you @liggitt !
