### ISSUE TITLE
enforce json formatting convention in docs and examples

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#10956]
It would not be very hard to enforce json formatting like we to go formatting. We could use json_pp (perl, shipped with ubuntu), python -m json.tool (ships with ubuntu), or jq (binary distributions, featurefull, available in the default ubuntu ppa repo)

**Comment by pmorie** [comment]
It would be good to have this to fix stuff like: http://kubernetes.io/v1.0/docs/user-guide/annotations.html

Completely reasonable looking JSON fragment in markdown renders with nasty red error flag

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by chenopis** [comment]
Don't most people use YAML now?
