### ISSUE TITLE
Pods are in Running, Terminating state even after the expiry of shutdownGracePeriod during Graceful Node Shutdown

### ISSUE THREAD

**Issue by amshankaran** [kubernetes/kubernetes#109531]
### What happened?

I have configured shutdownGracePeriod to enable graceful shutdown feature in k8s 1.24 beta.
When the node is under graceful shutdown, there are few pods which are in Running state and few are in Terminating state.

### What did you expect to happen?

As the node got graceful shutdown, the pods should be moved out of the node and there should not be any pods in the node which was already shutdown.

### How can we reproduce it (as minimally and precisely as possible)?

Flags configured: shutdownGracePeriod:30s, shutdownGracePeriodCriticalPods:10s, --terminated-pod-gc-threshold: 1
Shutdown the worker node gracefully (with systemctl poweroff).
1. Few deployment pods are in Running state. After 5 minutes it is moving to Terminating state. (nginx)
2. Daemonset pods are in pending state (https://github.com/kubernetes/kubernetes/issues/109450 behavior)
3. One of the Daemonset pod continues to be in Running state for ever. (subport-manager)

eccd@director-0-stack:~> kubectl get pods -A -o wide | grep worker-pool1-i1oiwd5d-stack
ingress-nginx   nginx-ingress-controller-58744fc4c9-m2r5t                         1/1     Terminating   0             144m    192.168.138.131   worker-pool1-i1oiwd5d-stack   <none>           <none>
kube-system     calico-node-69hxh                                                 0/1     Pending       0             11m     <none>            worker-pool1-i1oiwd5d-stack   <none>           <none>
kube-system     kube-proxy-445sv                                                  0/1     Pending       0             11m     <none>            worker-pool1-i1oiwd5d-stack   <none>           <none>
kube-system     node-local-dns-88zgn                                              0/1     Pending       0             11m     <none>            worker-pool1-i1oiwd5d-stack   <none>           <none>
kube-system     subport-manager-bbhxr                                             1/1     Running       0             151m    10.0.16.27        worker-pool1-i1oiwd5d-stack   <none>           <none>
 

### Kubernetes version

<details>

```console
$ kubectl version
eccd@director-0-ejlnoox-ibd-stack:~> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-beta.0", GitCommit:"3794d751af1baf8ea5158effa1ac1ac308cc4420", GitTreeState:"clean", BuildDate:"2022-03-31T17:59:42Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.0-beta.0", GitCommit:"3794d751af1baf8ea5158effa1ac1ac308cc4420", GitTreeState:"clean", BuildDate:"2022-03-31T17:49:49Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
eccd@director-0-ejlnoox-ibd-stack:~>

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by amshankaran** [comment]
Increased the shutdownGracePeriod:60s, shutdownGracePeriodCriticalPods:20s, now deployment pods were properly terminated and moved to another node. No pods in Terminating state. Still we could see Running and Pending pods.

**Comment by amshankaran** [comment]
@bobbypage in 1.24.1 when I do systemctl poweroff on the worker with shutdownGracePeriod:60s, shutdownGracePeriodCriticalPods:20s,   --terminated-pod-gc-threshold: 1

I could see few deployment pods are in Terminating status, few deployment pods got Terminated and garbage collected. 
In the Second iteration I could all the daemonset pods were continuous to be in Running status

I'm not getting consistent behavior for deployments or daemonsets pods. Could you please give me some context, what is expected  behavior as part of graceful node shutdown feature when the node powered off. If I miss any flag please update.

eccd@director-0-stack3:~> kubectl get pods -A -o wide | grep worker-pool1-wx60ifnk-stack3
ingress-nginx   nginx-ingress-controller-5bc859ff4c-strxt 0/1     Terminating   0   3h45m   192.168.215.67    worker-pool1-wx60ifnk--stack3   <none>           <none>
kube-system     calico-node-cxsfk                         0/1     Pending       0   16m     <none>            worker-pool1-wx60ifnk-stack3   <none>           <none>
kube-system     xyz-license-consumer-57f78c78c7-t6p28     0/1     Terminating   0   90m     192.168.215.77    worker-pool1-wx60ifnk-stack3   <none>           <none>
kube-system     kube-proxy-ptbpr                          0/1     Pending       0   16m     <none>            worker-pool1-wx60ifnk-stack3   <none>           <none>
kube-system     node-local-dns-cxpsl                      0/1     Pending       0   16m     <none>            worker-pool1-wx60ifnk-stack3   <none>           <none>
monitoring      xyz-pm-node-exporter-wn87x                0/1     Pending       0   16m     <none>            worker-pool1-wx60ifnk-stack3   <none>           <none>
monitoring      xyz-victoria-metrics-cluster-vminsert-947d4689c-cm9mx    1/1     Terminating   0  3h43m   192.168.215.68    worker-pool1-wx60ifnk-stack3   <none>           <none>
monitoring      node-cert-exporter-l95zr                  0/1     Pending       0   16m     <none>            worker-pool1-wx60ifnk-stack3   <none>           <none>

------------

eccd@director-0-stack3:~> kubectl get pods -A -o wide | grep worker-pool1-9iecklte-stack3
kube-system     calico-node-z7s6s                                    0/1     Pending       0    26m     <none>           worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     csi-cinder-nodeplugin-h5t4q                          3/3     Running       0    4h10m   10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     xyz-tm-external-connectivity-frontend-speaker-8mgxt 1/1     Running       0    4h8m    10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     kube-multus-ds-amd64-zlmcw                           1/1     Running       0    4h10m   10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     kube-proxy-9smwc                                     1/1     Running       0    4h11m   10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     kucero-b4v54                                         1/1     Running       0    4h10m   192.168.41.193   worker-pool1-9iecklte-stack3   <none>           <none>
kube-system     node-local-dns-9b2tt                                 1/1     Running       0    4h11m   10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
monitoring      xyz-pm-node-exporter-l5f9j                          1/1     Running       0    4h3m    10.0.16.9        worker-pool1-9iecklte-stack3   <none>           <none>
monitoring      xyz-victoria-metrics-cluster-vmstorage-0            1/1     Terminating   0    4h5m    192.168.41.196   worker-pool1-9iecklte-stack3   <none>           <none>
monitoring      node-cert-exporter-p4tcz                             1/1     Running       0    4h1m    192.168.41.198   worker-pool1-9iecklte-stack3   <none>           <none>

**Comment by rthakur-est** [comment]
[shutdown log.txt](https://github.com/kubernetes/kubernetes/files/9069000/shutdown.log.txt)

From the logs gathered from my setup, it had 3 daemonset pods and for one of them (multus) the status is pending and for the other two (calico and kube-proxy) the status is running.

ubuntu@k8s-control:~$ kubectl get pods -A -o wide | grep worker2
kube-system   calico-node-6fb7g                          1/1     Running   0             8d     10.98.86.225     worker2       <none>           <none>
kube-system   kube-multus-ds-bbc26                       0/1     Pending   0             5m3s   <none>           worker2       <none>           <none>
kube-system   kube-proxy-kx2w8                           1/1     Running   0             8d     10.98.86.225     worker2 

From the logs, graceful shutdown is successful in killing all the pods as designed but the status update to apiserver is done for only the old multus pod on this node. A new multus pod is scheduled on this node which is shown in pending state. Shutdown manager declares prematurely to systemd that its done processing even though the status update of the other 2 pods to apiserver is not finished.

Snippets from log:
Jun 30 09:47:19 worker2 kubelet[3249]: I0630 09:47:19.665964    3249 nodeshutdown_manager_linux.go:262] "Shutdown manager detected new shutdown event, isNodeShuttingDownNow" event=trueJun 30 09:47:19 worker2 kubelet[3249]: I0630 09:47:19.701315    3249 nodeshutdown_manager_linux.go:372] "Shutdown manager killing pod with gracePeriod" pod="kube-system/kube-multus-ds-fjhkw" gracePeriod=10
Jun 30 09:47:19 worker2 kubelet[3249]: I0630 09:47:19.993585    3249 nodeshutdown_manager_linux.go:384] "Shutdown manager finished killing pod" pod="kube-system/kube-multus-ds-fjhkw"
Jun 30 09:47:19 worker2 kubelet[3249]: I0630 09:47:19.993799    3249 nodeshutdown_manager_linux.go:372] "Shutdown manager killing pod with gracePeriod" pod="kube-system/kube-proxy-kx2w8" gracePeriod=20
Jun 30 09:47:19 worker2 kubelet[3249]: I0630 09:47:19.994187    3249 nodeshutdown_manager_linux.go:372] "Shutdown manager killing pod with gracePeriod" pod="kube-system/calico-node-6fb7g" gracePeriod=0
Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.321839    3249 nodeshutdown_manager_linux.go:384] "Shutdown manager finished killing pod" pod="kube-system/calico-node-6fb7g"
Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.427309    3249 nodeshutdown_manager_linux.go:384] "Shutdown manager finished killing pod" pod="kube-system/kube-proxy-kx2w8"
Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.451212    3249 nodeshutdown_manager_linux.go:324] "Shutdown manager completed processing shutdown event, node will shutdown shortly"

Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.267026    3249 kubelet_pods.go:1444] "Got phase for pod" pod="kube-system/kube-multus-ds-fjhkw" oldPhase=Failed phase=Running
Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.267078    3249 kubelet_pods.go:1451] "Status manager phase was terminal, updating phase to match" pod="kube-system/kube-multus-ds-fjhkw" phase=Failed

Jun 30 09:47:20 worker2 kubelet[3249]: I0630 09:47:20.299826    3249 status_manager.go:685] "Patch status for pod" pod="kube-system/kube-multus-ds-fjhkw" patch="{\"metadata\":

{\"uid\":\"1892acb0-0b07-47a8-84e5-9f9e4abce4dc\"}
,\"status\":{\"$setElementOrder/conditions\":[

{\"type\":\"Initialized\"}
,{\"type\":\"Ready\"},{\"type\":\"ContainersReady\"},{\"type\":\"PodScheduled\"}],\"conditions\":[\{\"lastTransitionTime\":\"2022-06-30T09:47:20Z\",\"reason\":\"PodFailed\",\"status\":\"False\",\"type\":\"Ready\"},\{\"lastTransitionTime\":\"2022-06-30T09:47:20Z\",\"reason\":\"PodFailed\",\"status\":\"False\",\"type\":\"ContainersReady\"}],\"containerStatuses\":[{\"containerID\":\"containerd://8d6071dcf67bfd1df555befbc7ea0e6b9765410fd19195fd35fbf72dc965255f\",\"image\":\"ghcr.io/k8snetworkplumbingwg/multus-cni:thick\",\"imageID\":\"ghcr.io/k8snetworkplumbingwg/multus-cni@sha256:fd30e03d4e936882f848d1cea5ee67580fc8c0019cd50c95ddf83e20841b05e6\",\"lastState\":{},\"name\":\"kube-multus\",\"ready\":false,\"restartCount\":0,\"started\":false,\"state\":{\"terminated\":

{\"containerID\":\"containerd://8d6071dcf67bfd1df555befbc7ea0e6b9765410fd19195fd35fbf72dc965255f\",\"exitCode\":2,\"finishedAt\":\"2022-06-30T09:47:19Z\",\"reason\":\"Error\",\"startedAt\":\"2022-06-30T09:29:13Z\"}
}}],\"message\":\"Pod was terminated in response to imminent node shutdown.\",\"phase\":\"Failed\",\"reason\":\"Terminated\"}}"

Jun 30 09:47:21 worker2 systemd[1]: kubelet.service: Succeeded.
Jun 30 09:47:21 worker2 systemd[1]: Stopped kubelet: The Kubernetes Node Agent.

**Comment by amshankaran** [comment]
Observing the same behavior as 1.24.1 in 1.25.
Few deployment pods are in Terminating status, few deployment pods got Terminated and garbage collected.
Daemonset pods are in Running and Pending.

director-0-stack:~> kubectl get pods -A -o wide | grep worker-pool1-7g9if79b-stack
kube-system     calico-node-cxhc4                                                 0/1     Pending       0          4h36m   <none>            worker-pool1-7g9if79b-stack   <none>           <none>
kube-system     xxxx-si-application-sys-info-handler-84578bbccf-89kpk             1/1     Terminating   0          5h      192.168.229.73    worker-pool1-7g9if79b-stack   <none>           <none>
kube-system     kube-proxy-p54nw                                                  0/1     Pending       0          4h36m   <none>            worker-pool1-7g9if79b-stack   <none>           <none>
kube-system     node-local-dns-jccm4                                              0/1     Pending       0          4h36m   <none>            worker-pool1-7g9if79b-stack   <none>           <none>
kube-system     subport-manager-448p9                                             1/1     Running       0          5h15m   10.0.16.3         worker-pool1-7g9if79b-stack   <none>           <none>
monitoring      xxxx-pm-node-exporter-cbzjj                                       0/1     Pending       0          4h36m   <none>            worker-pool1-7g9if79b-stack   <none>           <none>
monitoring      node-cert-exporter-2g2pg                                          0/1     Pending       0          4h36m   <none>            worker-pool1-7g9if79b-stack   <none>           <none>
eccd@director-0-stack:~>

eccd@director-0-ejlnoox-ibd-stack:~> kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"0b745a574e23ebb926d3be5c0ba73cfe6ce914aa", GitTreeState:"clean", BuildDate:"2022-08-24T04:52:37Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"0b745a574e23ebb926d3be5c0ba73cfe6ce914aa", GitTreeState:"clean", BuildDate:"2022-08-24T04:41:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
eccd@director-0-ejlnoox-ibd-stack:~>

**Comment by kashifest** [comment]
@ehashman @bobbypage is there any more information needed for this or can this issue be accepted ?

**Comment by smoshiur1237** [comment]
@ehashman @bobbypage  We are continuously seeing this issue in both 1.24.1 and 1.25. Also we have tested with increasing the value of  shutdownGracePeriod and shutdownGracePeriodCriticalPods. But getting the same behavior, deployment pod is in terminating stage and kube-system pods are in pending state. Any recommendation for a fix please.
