### ISSUE TITLE
How to Add HSTS HTTP Header to Kubelet Agent

### ISSUE THREAD

**Issue by parthasarathi-pm** [kubernetes/kubernetes#109530]
### What happened?

I not able to Add HTTP Header to enable HSTS in Kubelet.

For Kubernetes Api Server, we have a flag to enable HSTS --strict-transport-security-directives.

### What did you expect to happen?

Similar Flag to enable HSTS for Kubelet as well --strict-transport-security-directives.

### How can we reproduce it (as minimally and precisely as possible)?

In plain vanilla installation you can identify the issue.

curl -k https://localhost:10250 -s -D-

Not able to find the below line
strict-transport-security: max-age=31536000; includeSubDomains; preload

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
On Prem VM
</details>

### OS version

<details>

```console
Ubuntu 18.04.6 LTS
```
</details>

### Install tools

<details>

```console
Cluster initialized using kubeadm init
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
docker
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

```console
weave-net latest version
```

</details>

**Comment by aojea** [comment]
why is this  a bug?

**Comment by parthasarathi-pm** [comment]
I'm not sure the its a bug or new enhancement.
Please Suggest..

**Comment by aojea** [comment]
> I'm not sure its a bug or new enhancement. Please Suggest..

It looks like a new feature to me, but the corresponding SIGs should decide ;)

/sig node
/sig auth

**Comment by liggitt** [comment]
Definitely a feature request. xref https://github.com/kubernetes/kubernetes/issues/96040

I remain skeptical about use of HSTS on non-browser-facing endpoints

**Comment by parthasarathi-pm** [comment]
Our Internal Security Scanning Report say this is medium risk.
HSTS Missing From HTTPS Server - Nessus Scanner
SSL/TLS: HTTP Strict Transport Security (HSTS) Missing - OpenVAS.

**Comment by aojea** [comment]
> Our Internal Security Scanning Report say this is medium risk.

> I remain skeptical about use of HSTS on non-browser-facing endpoints

agree with Jordan, security scanners should be tuned properly, I don't think the alarm is right in this case
