### ISSUE TITLE
`kubectl edit -k` command doesn't work at all

### ISSUE THREAD

**Issue by sahilrajput03** [kubernetes/kubernetes#109598]
### What happened?

I read from https://kustomize.io/ and https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/ and still I can't figure this out.

I want to know what I am missing bcoz `kc edit -k` command for changing a `kustomization.yaml` file doesn't run properly as it throws below error:

```
$ kc edit -k . set image IMAGE_PLACEHOLDER=jakousa/dwk-4-gitops-app:myTestTag
error: there is no need to specify a resource type as a separate argument when passing arguments in resource/name form (e.g. 'kubectl get resource/<resource_name>' instead of 'kubectl get resource resource/<resource_name>'
```

My file looks like:

```bash
$ cat kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: sahilrajput03/dwk-4-gitops-app
  newTag: ba4fea12c011f90a75ca7f22771c4a1ff292977c
```

### What did you expect to happen?

kustomization.yml file should reflect the new tag which i am passing via the command i.e., `myNewTag`.

### How can we reproduce it (as minimally and precisely as possible)?

Simply use my file as I stated above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"2022-03-17T21:14:47Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6+k3s1", GitCommit:"3228d9cb9a4727d48f60de4f1ab472f7c50df904", GitTreeState:"clean", BuildDate:"2022-01-25T01:27:44Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
The `set image IMAGE_PLACEHOLDER=jakousa/dwk-4-gitops-app:myTestTag` arguments are not recognized by `kubectl edit`

That command takes either a manifest (`-f <filename>`) or a kustomize file (`-k <kustomize file/dir>`) or a resource description (like `pod/mypod`), and opens an interactive editor to let you modify it.

`kubectl edit` does not take kustomize directives on the command line to apply

`kc edit -k .` would be more what I would expect

/close

**Comment by sahilrajput03** [comment]
@liggitt Thanks a lot. I didn't know that at all.
