### ISSUE TITLE
[Falling test] capz-windows-containerd-master

### ISSUE THREAD

**Issue by shuheiktgw** [kubernetes/kubernetes#109583]
### Which jobs are failing?

capz-windows-containerd-master

### Which tests are failing?

capz-e2e.Conformance Tests conformance-tests

### Since when has it been failing?

4/21

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-informing#capz-windows-containerd-master

### Reason for failure (if possible)

```
{ Failure /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:103
Timed out after 1200.000s.
Expected
    <bool>: false
to be true
/home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.1.2/framework/controlplane_helpers.go:147}
```

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/issues/108711 might be related to this issue

### Relevant SIG(s)

/sig windows

**Comment by shuheiktgw** [comment]
Closing since https://github.com/kubernetes/kubernetes/issues/109583 seems to cover this failure

**Comment by marosset** [comment]
https://github.com/kubernetes/kubernetes/issues/109444 covers this issue
