### ISSUE TITLE
liveness probe doesn't work

### ISSUE THREAD

**Issue by AdminWithROOT** [kubernetes/kubernetes#109537]
### What happened?

When the Pod processes the default SIGNALSTOP signal and exits gracefully, the liveness probe set at this time will not work properly. After the probe actively restarts up to 4 times, the Pod status will directly change to Completed

### What did you expect to happen?

The liveness probe should restart the Pod indefinitely

### How can we reproduce it (as minimally and precisely as possible)?

cat > liveness.yaml << EOF
apiVersion: v1
kind: Pod
metadata:
  name: liveness
spec:
  restartPolicy: OnFailure
  nodeSelector:
    node-role.kubernetes.io/master: ""
  containers:
  - name: liveness
    image: httpd
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
EOF
kubectl apply -f liveness.yaml

Run the above command, after about 2 minutes, you can see that the Pod’s status has been completed

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:52:18Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:50:34Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
no cloud provider, deploy on the bare metal server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux ctl206 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address \
    $(ip route | awk '/src/{for(i=1;i<=NF;i++)if($i~/(src|via)/) print $(i+1); exit}')
</details>

### Container runtime (CRI) and version (if applicable)

<details>
kubelet comes with docker-shim <===> docker API version 20.10.12 <===> containerd version 1.4.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: 0.8.7-00
kubectl apply -f  https://raw.githubusercontent.com/coreos/flannel/v0.14.0/Documentation/kube-flannel.yml
CSI: default
</details>

**Comment by jonyhy96** [comment]
Maybe u are looking for `restartPolicy: Always`. Liveness is not use to manage pod restart.

**Comment by AdminWithROOT** [comment]
I know "restartPolicy: Always" can resolve my problem, but the liveness probe send SIGWINCH  signal that cause the container to exit gracefully，shouldn't the probe be pulling the container up again？Why does the probe directly change the container to Completed after pulling up the container 4 times normally

**Comment by jonyhy96** [comment]
checkout here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/helpers.go#L88-L94, `OnFailure` means if ur program exit code is not 0, it will restart.

> Why does the probe directly change the container to Completed after pulling up the container 4 times normally
It status change to Completed after 4 times because of `failureThreshold: 3`.

u can start kubelet with loglevel 5 `--v=5` to see more details.

**Comment by jonyhy96** [comment]
FYI 
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: default
spec:
  containers:
  - image: httpd
    imagePullPolicy: Always
    name: httpd
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        port: 80
        path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
  restartPolicy: OnFailure
```

**Comment by AdminWithROOT** [comment]
The parameter "failureThreshold" does not seem to be related to the number of restarts. Even if the failureThreshold is set to 10 times, the Pod status will only become "Completed" after 5 restarts：



From the kubelet log,&nbsp; on the 5th container restart, the liveness probe tried to create a new container, but the creation failed. For more details, please see the kubelet.log in the attachment：



When checking the status of the container after the creation failed, it was found that the container became Completed, so nothing was done, so after 4th normally restart, the pod's status becomes completed:



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/kubernetes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午4:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes] liveness probe doesn't work (Issue #109537)





 
checkout here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/container/helpers.go#L88-L94, OnFailure means if ur program exit code is not 0, it will restart.
  
Why does the probe directly change the container to Completed after pulling up the container 4 times normally
 It status change to Completed after 4 times because of failureThreshold: 3.
  
u can start kubelet with loglevel 5 --v=5 to see more details.

**Comment by jonyhy96** [comment]
> The parameter "failureThreshold" does not seem to be related to the number of restarts. Even if the failureThreshold is set to 10 times, the Pod status will only become "Completed" after 5 restarts

Sorry for misunderstanding, the `failureThreshold: 3` is use for livenessProbe retry.

**Comment by jonyhy96** [comment]
The reason why it turns to `Completed` after 4 times retry is it faced a `Back-off restarting failed container` [error](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L962-L969) when start the container at 5th retry. The backoff interval will be doubled each restart. (10s 20s 40s 80s 160s). You can 
incress the restart count by extend the `periodSeconds: 5` with `failureThreshold: 3`.

**Comment by AdminWithROOT** [comment]
This YAML file can cause the same problem，after 4 * 3 = 12 times probe failed，the pod's status has been completed.&nbsp;

The following is the log of the first 3 Pod restarts：

You can see that the Pod fails to probe 3 times after each startup, and then exits gracefully after receiving the default SIGNALSTOP signal, and the exit code is 0. At this time, the liveness probe can be normally pull up the Pod; but after the Pod is pulled up by the liveness probe and runs for the 4th time, after the Pod exits after three failed detections, the Pod status becomes "Completed", and the liveness probe loses the ability to pull up the Pod.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/kubernetes"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午4:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubernetes/kubernetes] liveness probe doesn't work (Issue #109537)





 
FYI
 apiVersion: v1 kind: Pod metadata:   labels:     app: httpd   name: httpd   namespace: default spec:   containers:   - image: httpd     imagePullPolicy: Always     name: httpd     ports:     - containerPort: 80     livenessProbe:       httpGet:         port: 80         path: /health       initialDelaySeconds: 5       periodSeconds: 5       failureThreshold: 3   restartPolicy: OnFailure
