### ISSUE TITLE
make kubeclient in client-go pacakage to be a proxy

### ISSUE THREAD

**Issue by sdghchj** [kubernetes/kubernetes#109560]
### What would you like to be added?

I need the kube client to behavior as a proxy, each request to API server may has an individual token from a service account.
So I wonder whether there is a way I can reset the header Authorization after I call a kubernates API with dynamic kube client in [client-go/dynamic](https://github.com/kubernetes/client-go/blob/master/dynamic/simple.go) package.

### Why is this needed?

Related issue： https://github.com/kubeedge/kubeedge/issues/3805

**Comment by aojea** [comment]
I don't fully understand the issue from the description, I think you should give more details

Anyway, I don't know if it can be useful to you, but client-go allows to modify the transport by wrapping custom http roundtrippers

https://github.com/kubernetes/kubernetes/blob/b36c927d957e585ce54d415be4d7e4621e189d85/staging/src/k8s.io/client-go/rest/config.go#L106-L113

**Comment by sdghchj** [comment]
Hello @aojea, thanks for your reply, here is a picture for you.
![image](https://user-images.githubusercontent.com/20944466/164216100-ebd862fc-c002-47ae-9fa1-680c9469d900.png)

[KubeEdge](https://github.com/kubeedge/kubeedge) is a cloud native edge computing project depending on kubernetes, which extends cluster working nodes from cloud to edge.  It has two components, cloudcore and edgecore, providing a tunel connection from edge to cloud to enable an edge pod to access kubernetes API in cloud.

As in the picture above, there are two pods at edge side with different service accounts, so with different tokens.
They two can send http requests with individual tokens through kubeedge to kubernetes API server，but cloudcore use a shared dynamic kube client initialized with another service account token to call kubernates API. 

So, how to replace the token when the shared dynamic kube client proxies the request to kubernetes API server?

when the kube client proxies a request from edge pod1, I need it to replace the token with `token1`, so does `token2` when from edge pod2.

**Comment by sdghchj** [comment]
> 

WrapTransport to wrap RoundTripper may not help this issue.  It is a global configuration and has the same effect on all the requests.

**Comment by aojea** [comment]
You can replace the token with the roundtripper and make it behave differently per request, see this per example

https://github.com/kubernetes/kubernetes/blob/9126048c9c47cc51f15f977da51c6023229a02b5/staging/src/k8s.io/client-go/transport/round_trippers.go#L83-L142

**Comment by sdghchj** [comment]
@aojea So how to replace the roundtripper?

By config.WrapTransport ? As said above, it will be a global configuration and has the same effect on all the requests.

By directly repalcing it from the shared dynamyic client ? But the restclient, which has a member of http.Client, is an unexported member of [dynamicClient](https://github.com/kubernetes/kubernetes/blob/9126048c9c47cc51f15f977da51c6023229a02b5/staging/src/k8s.io/client-go/dynamic/simple.go#L34).

The last way,  when each request comes, we build a new dynamicClient with a custom roundtripper or config.WrapTransport, but this will be lower performance and also is not a perfect solution.

**Comment by aojea** [comment]
> By config.WrapTransport ? As said above, it will be a global configuration and has the same effect on all the requests.

the custom roundtripper can have a dynamic behavior, it is a new type, you can add hooks as you did in your PR, you can use different logic based on the request, environment variables,  ...

**Comment by sdghchj** [comment]
I'm not clear how to apply a custom roundtripper into a dynamicClient to behave dynamicly.
Could you please show me some example code ?

**Comment by sdghchj** [comment]
I guess I get what you mean.
The context has been assigned into the http.Request as a member.
So I can get the token from the context and add it to headers in a custom roundtripper.
Thank you.
