### ISSUE TITLE
CRD Versioning order in the document seems to be incorrect

### ISSUE THREAD

**Issue by Abhishek-Srivastava** [kubernetes/kubernetes#109589]
### What happened?

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

sorted version list as documented here is:

- v10
- v2
- v1
- v11beta2
- v10beta3
- v3beta1
- v12alpha1
- v11alpha2
- foo1
- foo10

Why is v11alpha2 or v11beta2 < v10 ?
It’s v11alpha2 is dev build built on v10? I believe v11alpha2 will upgrade to v11.
Is it a mistake?

### What did you expect to happen?

For the list here: - 
- v10
- v2
- v1
- v11beta2
- v10beta3
- v3beta1
- v12alpha1
- v11alpha2
- foo1
- foo10

I guess the right order should be
v12alpha1 > v11beta2> v11alpha2 >  v10 > v10beta3 > v3beta1 > v2 > v1 > foo10 > foo1

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4+rke2r1", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-24T18:34:16Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux mw-rg24 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
stable versions (`v<digits>`) always sort before beta versions (`v<digits>beta<digits>`) always sort before alpha versions (`v<digits>alpha<digits>`)

**Comment by Abhishek-Srivastava** [comment]
@liggitt  @fedebongio 
v11beta1 is a development release over v10 (which is stable, let's consider).
That implies v11beta1 is having all the code which v10 has + more. Is that a correct understanding ?

**Comment by ashishraman96** [comment]
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/
in Version priority:
"Entries that follow Kubernetes version patterns are sorted before those that do not."
Kubernetes version patterns follow semver versioning. Isnt it anti pattern and doesnt follow semver?

**Comment by liggitt** [comment]
Kubernetes API version strings are in the form v#, v#beta#, or v#alpha#
