### ISSUE TITLE
When the kubelet calls the NodeGetVolumeStats interface of csi, the parameter is wrong

### ISSUE THREAD

**Issue by QQGoblin** [kubernetes/kubernetes#109585]
### What happened?

When the kubelet calls the NodeGetVolumeStats interface, the stagingtargetpath of the NodeGetVolumeStatsRequest parameter is empty.

The k8s version of my environment is 1.20.11, and csi provides STAGE_UNSTAGE_VOLUME capability.

I found that in the master branch, when the kubelet calls the function, this parameter is not added. Is this a bug?

### What did you expect to happen?

```protobuf
message NodeGetVolumeStatsRequest {
  // The ID of the volume. This field is REQUIRED.
  string volume_id = 1;
  // It can be any valid path where volume was previously
  // staged or published.
  // It MUST be an absolute path in the root filesystem of
  // the process serving this request.
  // This is a REQUIRED field.
  // This field overrides the general CSI size limit.
  // SP SHOULD support the maximum path length allowed by the operating
  // system/filesystem, but, at a minimum, SP MUST accept a max path
  // length of at least 128 bytes.
  string volume_path = 2;
  // The path where the volume is staged, if the plugin has the
  // STAGE_UNSTAGE_VOLUME capability, otherwise empty.
  // If not empty, it MUST be an absolute path in the root
  // filesystem of the process serving this request.
  // This field is OPTIONAL.
  // This field overrides the general CSI size limit.
  // SP SHOULD support the maximum path length allowed by the operating
  // system/filesystem, but, at a minimum, SP MUST accept a max path
  // length of at least 128 bytes.
  string staging_target_path = 3;
}
```

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/kubernetes/kubernetes/blob/632ed300f2c34f6d6d15ca4cef3d3c7073412212/pkg/volume/csi/csi_client.go#L602

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

let sig-storage to triage and decide if this is a bug

**Comment by arsiesys** [comment]
/reopen

Met the same issue today while developing a CSI and reached this old closed issue.

K8S: 1.28.3
CSI Specs: 1.7.0
