### ISSUE TITLE
client-side apply does not cause managedFields update

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#109576]
### What happened?

I created an object with `kubectl apply`, and later I updated the same object with another `kubectl apply`.  After that I looked at the object's managedFields, and saw nothing about the update.  Here is what I got after the second apply:
```
apiVersion: v1
data:
  key: the other value
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"key":"the other value"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"test1","namespace":"default"}}
  creationTimestamp: "2022-04-20T20:37:52Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:key: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2022-04-20T20:37:52Z"
  name: test1
  namespace: default
  resourceVersion: "19304095"
  uid: 5fb6f9b3-9d9b-475b-89f8-b0d0fe3f2348
```

### What did you expect to happen?

I expected managedFields to get updated by the second `kubectl apply`.

### How can we reproduce it (as minimally and precisely as possible)?

```
kubectl apply -f - <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: test1
data:
  key: value
EOF

sleep 5

kubectl apply -f - <<EOF
kind: ConfigMap
apiVersion: v1
metadata:
  name: test1
data:
  key: the other value
EOF

kubectl get --show-managed-fields -o yaml cm test1
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux mjs-ubu3-kube1.sl.cloud9.ibm.com 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @apelisse

**Comment by MikeSpreitzer** [comment]
I also saw the timestamp not updated when I updated using client-go and typed client stubs, Apply method, patch type `MergePatchType PatchType = "application/merge-patch+json"`.

**Comment by glebiller** [comment]
The `managedField` is not updated because you are not changing the structure of the object (adding or removing fields).
According to [managedfieldsupdater](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/managedfieldsupdater.go#L65), the time is updated if and only if the fieldSet is changed. It does not take into account the value of fields.

One option would be to not compare the fieldSets but directly compare the liveObject & newObject for differences and update the `time` field accordingly.
Is it the desired behavior to update the time of `managedFields` when only the value is updated?

**Comment by MikeSpreitzer** [comment]
Yes!  Look at the first paragraph of https://kubernetes.io/docs/reference/using-api/server-side-apply/#apply-and-update .

**Comment by lavalamp** [comment]
@apelisse, is that documentation correct? Is this what we intended?

**Comment by apelisse** [comment]
> Yes! Look at the first paragraph of https://kubernetes.io/docs/reference/using-api/server-side-apply/#apply-and-update

I don't see any mention to the timestamp in that first paragraph.

We've clarified recently the exact semantic of the timestamp, as defined here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L1229-L1233

I think you've identified the wrong code @glebiller, if you want to go ahead and fix it, go ahead, I'll happily review!
