### ISSUE TITLE
[Failing Test] gce-device-plugin-gpu-1.24, integration-1.24, ci-kubernetes-unit-1-24, verify-1.24

### ISSUE THREAD

**Issue by shuheiktgw** [kubernetes/kubernetes#109591]
### Which jobs are failing?

gce-device-plugin-gpu-1.24, integration-1.24, ci-kubernetes-unit-1-24, verify-1.24

### Which tests are failing?

Overall

### Since when has it been failing?

4/21

### Testgrid link

https://testgrid.k8s.io/sig-release-1.24-blocking#gce-device-plugin-gpu-1.24
https://testgrid.k8s.io/sig-release-1.24-blocking#integration-1.24
https://testgrid.k8s.io/sig-release-1.24-blocking#ci-kubernetes-unit-1-24
https://testgrid.k8s.io/sig-release-1.24-blocking#verify-1.24

### Reason for failure (if possible)
It seems the jobs timeout due to Back-off pulling the image 

```
The test container could not start because it could not pull "gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220420-a8dc19ed91-1.24". Check your images. Full message: "Back-off pulling image \"gcr.io/k8s-staging-test-infra/kubekins-e2e:v20220420-a8dc19ed91-1.24\""
```

### Relevant SIG(s)

/sig testing

**Comment by shuheiktgw** [comment]
Discussion is going on in [this thread](https://kubernetes.slack.com/archives/CN0K3TE2C/p1650532824250449)

**Comment by palnabarun** [comment]
/assign

This should be fixed once https://github.com/kubernetes/test-infra/pull/26055 is merged, the image is rebuilt and then the jobs start picking up the image.

**Comment by palnabarun** [comment]
It shouldn't have been closed automatically.

/reopen

**Comment by shuheiktgw** [comment]
I confirmed the issue has been resolved so I'm closing the PR!
