### ISSUE TITLE
testing image translation needed for KUBE_TEST_REPO

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes/kubernetes#109523]
### What would you like to be added?

In https://github.com/kubernetes/kubernetes/pull/93510 the `KUBE_TEST_REPO` testing env var was added which allowed all testing images to come from a single repository (each image at a different tag). This _can_ be highly convenient for reasons placed in the PR, but in order to accomplish this the tags are not simply the name of the image but a translation and hash of it.

As a result, in order to better utilize this feature, there needs to be a way to get the _expected_ name/tags of the images based on a given KUBE_TEST_REPO value.

### Why is this needed?

Without it, the user doesnt know what to name/tag the images in order to utilize them. If you copy a few images to the new registry and set KUBE_TEST_REPO, you'll have constant ErrImagePull issues since none of the names line up.

The original PR made note of this need but it was never followed up on.

**Comment by johnSchnake** [comment]
I'm going to try and tackle this; at first glance it should be pretty trivial.

**Comment by johnSchnake** [comment]
I actually wasnt super clear on the code path and this may either be done or nearly done based on how it already works when you list images.

I edited a `sonobuoy` binary to set the `KUBE_TEST_REPO=my/repo` and got the following output. You can see most of the images were translated. The authenticated and invalid images were not.

So this actually just needs a Sonobuoy fix to be more convenient I think. Closing.

```
> sonobuoy images
INFO[0000] e2e image to be used: k8s.gcr.io/conformance:v1.21.1
gcr.io/authenticated-image-pulling/alpine:3.7
gcr.io/authenticated-image-pulling/windows-nanoserver:v1
gcr.io/k8s-authenticated-test/agnhost:2.6
invalid.com/invalid/alpine:3.1
k8s.gcr.io/conformance:v1.21.1
my/repo:e2e-1-k8s-gcr-io-e2e-test-images-agnhost-2-32-_wCOtsOr37BcGgzfoA5LLw
my/repo:e2e-10-k8s-gcr-io-e2e-test-images-cuda-vector-add-2-2-jfn9MO1ZuFYZo9B7A5mwXA
my/repo:e2e-11-k8s-gcr-io-build-image-debian-iptables-buster-v1-6-0-p1-E9n0TK9ltBSdbbJ5sSg
my/repo:e2e-12-k8s-gcr-io-e2e-test-images-echoserver-2-3-1dQAXkPNCG1sbs7rQxyu-A
my/repo:e2e-13-k8s-gcr-io-etcd-3-4-13-0-VKSltRW2wd8-QWftHS4X_g
```

**Comment by dims** [comment]
authenticated and invalid images are hard coded by design and won't be switched as they are testing special conditions (and just copying images are not enough)
