### ISSUE TITLE
Split the ValidateAndApply function in the component-base logs package into validate and apply

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#109650]
### What would you like to be added?

When configuring klog, the ValidateAndApply function in the component-base logs package is required for the configuration to take effect. This is not very friendly, it is recommended to be divided into validate and apply functions

### Why is this needed?

Some scenarios may require separate validation.
such as
When adding unit tests for validate, the ValidateApply function may be called multiple times, causing race detected

**Comment by serathius** [comment]
We merged Validate and Apply as logging is a special case that it needs to be evaluated before all other configuration.

**Comment by yangjunmyfm192085** [comment]
ok, I understand now. 
Is it more flexible to modify `validate` and `apply`  to `Validate` and `Apply`?

**Comment by pohly** [comment]
I can only imaging one scenario where separate functions would be more useful: during unit testing of the "Validate" part.

In which binary would you use the separate functions? Would Validate be directly followed by Apply? If yes, then a single function is sufficient. If not, then what are you doing in between? If the code in the middle does any kind of logging, the logging output will not be as intended.

**Comment by serathius** [comment]
As confirmed this was intentional.
/close

**Comment by pohly** [comment]
I might bring back a separate "Validate" function because that has some use when used without "Apply" - see https://github.com/kubernetes/kubernetes/pull/105797
