### ISSUE TITLE
Add CRI check to localhost healthz endpoint

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#109640]
### What would you like to be added?

Add a check for CRI service to localhost healthz endpoint in `kubelet` (i.e. localhost:10248/healthz and localhost:10248/healthz/cri). 

### Why is this needed?

CRI service is usually a separate process in the system (Containerd, for example). So it requires a health check to make sure the process is running healthily. Using command `ctr` or `crictl` is with extra overhead and slightly complex than simply using a `curl` if the CRI implementation doesn't already provide a http endpoint. Using the same method to health check both `kubelet` and CRI implementation (containerd) make things simpler.

**Comment by JayKayy** [comment]
I would be interested in working on this, given its confirmed this is the way to proceed.

**Comment by linxiulei** [comment]
@JayKayy Thanks for being interested. I had a prototype to this issue already. It'd be great if you'd like to review it. However, we still need to confirm it's a legit feature first.
