### ISSUE TITLE
Websocket connection drops between two containers in same pod

### ISSUE THREAD

**Issue by laurie-kepford** [kubernetes/kubernetes#109678]
### What happened?

I have a pod that is made up of two containers.  One called backend and one called notification-service.  Both are written in haskell and both communicate via websockets.  The backend is running on port 3000 and the notification has no port exposed.  There is an ALB in front of the backend and the backend excepts both https and websockets on the same port.

At startup a websocket connection is established by the notification service to the backend on localhost:3000. Sometimes the notification service gets an exception because the connection has been closed somehow. This causes the notification service to restart. But the backend thinks it still connected so it won't let it connect again. So it keeps restarting. The load-balancer sees the pod as unhealthy and the customer gets a 503 error.

This happens only if the app has been idle for a while.  An hour or two usually.

### What did you expect to happen?

I expect the websocket connection to remain intact unless one of the containers is restarted.

### How can we reproduce it (as minimally and precisely as possible)?

I think it could only be re-created if you had my application code.  But maybe there is a way to create a pod with two services that use websockets in a similar way.

### Anything else we need to know?

i have found some posts around about people having similar issues, but they always seem to involve a load balancer and/or service.  These two are connecting over localhost inside the same pod.

### Kubernetes version

<details>
1.19
</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here
Linux ip-10-50-212-16 5.8.0-1041-aws #43~20.04.1-Ubuntu SMP Thu Jul 15 11:07:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Rancher 2.6.1
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by laurie-kepford** [comment]
I have tried both of the above.  And the only thing I have been able to find is that the websocket connection gets closed.  But the backend does not get the message.  Let me see if I can put together some relevant information.  I will post that here.

**Comment by laurie-kepford** [comment]
I am running k8s 1.9 and I have noticed some odd things about the CNI plug in.  So I am going to create a new cluster using k8s 1.21 and see if I get any different results.

**Comment by dcbw** [comment]
@laurie-kepford were you able to reproduce with Kube 1.21?

**Comment by laurie-kepford** [comment]
Yes.  The same thing is still happening after upgrading to 1.21
it seems to be random because there is no load on the underlying hosts.

**Comment by thockin** [comment]
> I have tried both of the above. And the only thing I have been able to find is that the websocket connection gets closed. But the backend does not get the message.

Can you post a TCP dump that shows this?  Is there a RST sent or something?

Can you eliminate any variables?

**Comment by laurie-kepford** [comment]
I moved the apps to a brand new cluster (about 10 of them)  The instance was a bit over provisioned for only 10 pods.  I got no more crashes.  I added a second server and moved 15 more apps.  Crashes started up again. We had one at 5:55 this morning. The servers do not seem to be over loaded tho.  This is an M6i.xlarge (4 vCpU, 16MB Ram). in the example below the app crashed at 5:55am
![2022-05-26 at 12 59 PM](https://user-images.githubusercontent.com/86793511/170568179-aa01ae5c-e6a3-4ace-ba90-ba7455b12e66.png)
The application runs on port 3000.  And usually the reset is sent from 3000, in this case it seems to have been sent to the database server.

![2022-05-26 at 1 00 PM](https://user-images.githubusercontent.com/86793511/170569072-1c1c75eb-6279-45e5-8a96-0377cfe51959.png)

**Comment by thockin** [comment]
Can you help me filter the noise from that screenshot?  The red-highlighted line - is it relevant?  I thought you said it was localhost->localhost?

**Comment by thockin** [comment]
I'm confused - is it the same issue?  You're saying, if I understand, "something caused my pod-app to send RST to some network peer" - sometimes that peer is the other container, sometimes it is outside the pod.  Is that right?

I don't know much about how AWS nodes are configured but conntrack is always my go-to first guess.  Is this a very busy node which could be running out of conntrack records?

**Comment by laurie-kepford** [comment]
We started with conntrack.  What does "running out of conntrack records" mean.  Prior to yesterday when we looked at the capture logs we were only seeing the RST on LocalHost.  Now we are seeing them in other places.

**Comment by thockin** [comment]
I don't know how CPU spikes would cause RST, though.

The kernel's conntrack subsystem pre-allocates a finite number of records and every 5-tuple flow is stored there.  If you have a lot of connections (or a lot over a short period) it could get "full" and fail to allocate. 

As suggested above - `conntrack -L` within the pod and on the root netns might show something.  Also look in dmesg?

**Comment by thockin** [comment]
Thanks for the update!
