### ISSUE TITLE
Error in CHANGELOG-1.23

### ISSUE THREAD

**Issue by F1ko** [kubernetes/kubernetes#109669]
### What happened?

According to the [release notes](https://github.com/kubernetes/kubernetes/blob/a83cc51a19d1b5f2b2d3fb75574b04f587ec0054/CHANGELOG/CHANGELOG-1.23.md?plain=1#L950) the `kubeadm` flag `--patches` is no longer allowed in a mixture with the flag `--config`.
However, that is not the case as someone can still use `kubeadm upgrade` with both `--patches` and `--config`.
This is due to the fact that [`ValidateMixedArguments`](https://github.com/kubernetes/kubernetes/blob/a83cc51a19d1b5f2b2d3fb75574b04f587ec0054/cmd/kubeadm/app/apis/kubeadm/validation/validation.go#L536) is never used in any upgrade logic.

### What did you expect to happen?

As mentioned in the release notes I expected `--patches` in combination with `--config` to fail (even for `kubeadm upgrade`).

### How can we reproduce it (as minimally and precisely as possible)?

Execute `kubeadm upgrade apply --config /some/config.yaml --patches /some/patches`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}```

</details>


### Cloud provider

<details>
on-prem
</details>


### OS version

_No response_

### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

_No response_

### Related plugins (CNI, CSI, ...) and versions (if applicable)

_No response_

**Comment by neolit123** [comment]
hi,

> Execute kubeadm upgrade apply --config /some/config.yaml --patches /some/patches

the mixture of flag / config validation applies to `init` and `join`.

usage of `--config` for upgrade is not recommended currently as a whole!
as you can see `--config` for upgrade throws a warning that it is not recommended.
given that fact i think we can ignore the lack of mixture validation.

if you want to reconfigure a cluster see:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-reconfigure/

thanks
/close
/area kubeadm
