### ISSUE TITLE
Sharding list requests

### ISSUE THREAD

**Issue by SOF3** [kubernetes/kubernetes#109667]
### What would you like to be added?

The apiserver accepts sharding parameters in LIST requests. This can be utilized by controllers performing list-watch.

A request can be separated into `n` shards by passing `shard: i, numShards: n` in the `ListOptions`, then the apiserver only responds with the list of objects where `hash(namespace + name) % n == i`.  The client in the controller can then merge the responses from `n` separate sharded list requests after they have all completed.

While multiple sharded list requests may return lists of inconsistent `resourceVersion`, the subsequent watch request can start from the earliest resource version and still achieve eventual consistency (by dropping events older than the listed object).

/sig api-machinery
/sig architecture

### Why is this needed?

In clusters with a large amount of objects, the list response body is huge, which may take a long time to complete transferring. It may have several negative effects. 

1. When a controller starts, it typically blocks and does nothing to wait for informer sync before carrying out their main logic. Long listing time delays the informer sync, resulting in a long period of controllers not functioning. For example, when scheduler waits for pod informer sync, no pods are scheduled for several minutes.
2. After listing is complete, watch request will be sent with the resourceVersion field in list response. After the long list request, the original list resourceVersion is most likely to have  expired in the apiserver watch cache, which leads to a "resource version too old" error response that triggers a re-list request. In worse cases, this results in a re-list loop and hence a vicious cycle due to wasting CPU. (watch cache size can be adjusted but there is a limit due to memory tradeoff)

Sharding can reduce the latency from controller startup to sync completion:
- The client can deserialize the objects on multiple cores to leverage parallelism. Given that the client has excess CPU resources, the overall latency is just the latency of the slowest shard. Similarly, server-side serialization can also be parallelized.
- If apiserver is routed through a load balancer more proximal to the client, the throughput could be distributed to multiple apiserver instances that may bottleneck on different parts of the network.

Assuming CPU cores and bandwidth are in excess, this can greatly reduce the response latency.

**Comment by lavalamp** [comment]
Pagination is the closest thing to this that we offer right now. You could e.g. request page N+1 while still processing page N. Alternatively (or additionally) you can shard by namespace, some controllers do this.

(You can actually get something similar if you play around with pagination continuation tokens but I wouldn't recommend it outside of specific circumstances.)

As far as scale goes, we think built-in objects can have very large collections already. We're aware CRs are lagging and making CRs scale better is slowly working its way up the priority list.

If we did shard, we'd likely want it to be for more of the system than just the list call. So we would not go with this particular design.

If you could state how big your collection is, how many namespaces, and if it's CRDs or not, that'd be helpful for us at some point in the future if we do take something like this up.

**Comment by SOF3** [comment]
@lavalamp 

> Pagination is the closest thing to this that we offer right now. You could e.g. request page N+1 while still processing page N.

Pagination does not really solve the problem for two reasons:

- If we use the continue token in the response, this requires fetching the continue token from the response body, which requires fully receiving the page (since the continue token is sent in the metadata not in the headers), and it is not possible to synthesize the continue token since we don't know what's the (N+1)th key). Serialization may not be parallelized either, even though the client can dispatch deserialization to multiple goroutines indeed.
- Pagination may result in apiserver internal cache penetration (into etcd) because of resourceVersion consistency. This makes pagination impractical to use.

> Alternatively (or additionally) you can shard by namespace, some controllers do this.

Sharding by namespace is not exactly scalable. In particular, in managed platforms where the concept of Kubernetes deployments is not (directly) exposed to the user, this means the platform has to create namespaces dynamically, which would be nightmare for access control management along with other problems. After all, namespaces were designed to logically separate objects, not for automatic partitioning, so it isn't really the correct solution.

> As far as scale goes, we think built-in objects can have very large collections already. We're aware CRs are lagging and making CRs scale better is slowly working its way up the priority list.

As mentioned in the original issue, our problem is with pod objects, which causes re-list occasionally. The number of pods in each of our clusters is at the magnitude of around 10^5. I am aware that the current rating is around 150k pod per cluster, but we are looking forward to higher scalability of single clusters in the long term, and slow listing appears to be the first symptoms observed as we exceed that limit.

> If we did shard, we'd likely want it to be for more of the system than just the list call. So we would not go with this particular design.

Agreed. As we go for scalability, just sharding the LIST request is definitely far from enough. Nevertheless, this is probably a necessary step for sharding either way, so I thought it's a relatively simple and self-contained change to get started with (since it is an internal implementation detail transparent to client-go users and compatible with existing usage). Expanding sharding to other components (like WATCH protocol, informer, or the actual controller logic) would be great, but sharding LIST first would be a prerequisite (although probably not in the way I proposed, since hashing by namespace and name is not sufficient in the long term).

> how big your collection is, how many namespaces, and if it's CRDs or not

Currently we are stress testing at around 10^6 pods for a single namespace. Appears that listing is the main bottleneck we observed.

**Comment by lavalamp** [comment]
re pagination: you can re-use a continuation token after the RV has expired and the server will tell you a good RV. You can use this feature to start lexically partway through a collection. It's not really intended to do what you'd want to do, but it would be possible to make it work if you were really desperate. The storage version migrator uses this feature.

> create namespaces dynamically

You can use something like HNC to automate permissions etc, if that is the hard part.

BTW sharding to support many namespaces is a different (and easier) problem than sharding to support larger namespaces. I'd give lowish odds that we'll ever implement code to handle giant namespaces. So don't plan your system assuming that will happen.

> ... pods in each of our clusters is at the magnitude of around 10^5. I am aware that the current rating is around 150k pod per cluster

This kind of illustrates my point that sharding the list call is not very much of the problem -- controllers operating on pods would have to change. Often controllers need to know the set of objects for visibility purposes and wouldn't function correctly on just a shard without being rewritten in some way.

> we are looking forward to higher scalability of single clusters in the long term

IMO, you should not. At some point the blast radius is just too big, and it's much much much safer to run multiple clusters rather than one giant one.

> Currently we are stress testing at around 10^6 pods for a single namespace. Appears that listing is the main bottleneck we observed.

At that scale you should be able to tune the system to function properly without exotic techniques. You may need to add apiservers. Look into APF configuration, you may want to tune it.

We are aware that relists are very expensive and my guess is that it will be improved in the nearish future -- without needing to shard.

**Comment by SOF3** [comment]
Cache penetration is still a significant drawback for pagination, and predicting names lexically is not really reliable in the long term. And namespaces are intended for logical separation instead of sharding after all, so that doesn't sound like a correct solution in the general use case for all users.

> controllers operating on pods would have to change

We have managed to modify some of the controllers to support large collections, so the main controller logic is not really a concern right now. This is because controllers can already utilize multiple cores sharing the same (full) informer cache, without sharding to multiple processes (hence no need to shard to multiple smaller caches).

On the other hand, the initial listing has noticeable latency as the number of objects increases. This is because, as mentioned in the OP, the serialization, transfer and deserialization happens in a single stream and is not parallelized. Therefore, the entire point of splitting the list request is to reduce this latency. So no matter we shard the controllers or not, the startup latency of each (shard of) controller can still be sped up by splitting the list request.

This is especially bad in single-instance controllers, since scheduling was already stuck for a while (leader lease timeout) and the listing *after* new leader election takes even longer.

> You may need to add apiservers

The apiservers are not overloaded; the overall CPU load (compared to allocated) is around 60% only. The main concern here is with the response latency, and adding more apiserver instances cannot help with the latency of a single request -- unless the list request is sharded into multiple requests, which is exactly what I initially proposed.

> my guess is that it will be improved in the nearish future -- without needing to shard.

Great to know. Are there any relevant issues or roadmaps for that?

**Comment by lavalamp** [comment]
Note that since apiserver has multiple clients, it's already doing lists in parallel. Our lists are very data-heavy, at some point you run out of bandwidth to stream them in parallel. Parallelizing individual lists may not help as much as you expect.

I personally am more worried about making them always succeed, than making them faster: https://github.com/kubernetes/kubernetes/issues/98541

And second on my list would be being efficient: https://github.com/kubernetes/kubernetes/issues/90339
