### ISSUE TITLE
Document CNI version-related breaking change

### ISSUE THREAD

**Issue by rolfedh** [kubernetes/kubernetes#109686]
**This is a Bug Report**

**Problem:**

As a user upgrading to Kubernetes v1.24 GA I must be aware of the following information: 

- (No, really, you MUST read this before you upgrade) Before you upgrade to Kubernetes 1.24, if you use a CNI network plugin that complies with [Container Network Interface](https://github.com/containernetworking/cni) (CNI) versions earlier than v1.0.0 and you plan to use any of the following container runtimes, you must specify the CNI version as described in [Declaring the CNI version of your plugin](TBD). Otherwise, your network will break.
- For Kubernetes v1.24 GA, when you upgrade one of the following container runtimes, safely drain (cordon) your node, upgrade your CNI plugins to the latest versions, and confirm that your CNI config files specify/match the correct versions for your plugins. Ensure that you have installed the latest version (v1.0.0 or later) of the CNI loopback plugin.

**Proposed Solution:**

Publish release note, doc topics, and blog posts for the CNI version-related breaking change described in https://docs.google.com/document/d/1zwKls4-NUxkpak-591ghRaGEKdjp8BEdXD8YpL_zdIk/edit?usp=sharing

Release note: Lucas Dwyer
Release blog: @mickeyboxell 
Feature blog: @rolfedh  
Procedure and Troubleshooting topics: @Rolfe Dlugy-Hegwer 

**Page to Update:**
https://kubernetes.io/... TBD

Kubernetes v1.24 GA

**Comment by sftim** [comment]
@rolfedh we usually don't mark issues as WIP, so I retitled this.

**Comment by sftim** [comment]
Also see https://github.com/kubernetes/website/pull/33224

**Comment by sftim** [comment]
Per https://github.com/kubernetes/website/pull/33224#issuecomment-1110017103, I suggest we add a release note entry about any CNI version bump that we decide to make.

**Comment by sftim** [comment]
AIUI, we're proposing to change the docs around networking
- **from** recommending / declaring that the ecosystem should follow CNI spec 0.4.0
- **to** recommending / declaring that the ecosystem should follow CNI spec 1.0.0

and that recommendation change is going to accompany the v1.24 release. Have I got that right?

**Comment by squeed** [comment]
Respectfully, the text in this post is wrong. CNI v1.0 continues the existing practice of assuming missing version = `v0.1.0`. So, there are no breaking changes and no administrator changes are required.

The only thing interesting is that we, as an ecosystem, would like to support 1.0.

**Comment by sftim** [comment]
@mikebrow FYI

**Comment by liggitt** [comment]
> * For Kubernetes v1.24 GA, when you upgrade one of the following container runtimes, safely drain (cordon) your node, upgrade your CNI plugins to the latest versions

is this actually required? it's hard to tell whether updating CNI plugins is *actually* required when upgrading to 1.24. It needs to be clearer whether action is actually required. https://github.com/kubernetes/kubernetes/issues/109686#issuecomment-1110876517 indicates it is not.

**Comment by rolfedh** [comment]
- Please direct all comments to https://github.com/kubernetes/website/pull/33240
- When those have all been resolved, I'll port the changes to https://github.com/kubernetes/website/pull/33242. Please don't comment on https://github.com/kubernetes/website/pull/33242.

**Comment by DiptoChakrabarty** [comment]
/milestone v1.24

:wave:  bug triage here adding milestone once again to track (might have moved after issue transfer)

**Comment by sftim** [comment]
This isn't really directly relating to any Kubernetes change at all, but I don't think we're keen to suggest people switch to a different container runtime and then have those folks find that their cluster networking is awry.

**Comment by liggitt** [comment]
> Right, but that's a containerd issue? So that should be part of the containerd notes, not Kubernetes...

I'd tend to agree.

**Comment by squeed** [comment]
Minor update: it turns out there was a regression in libcni. This is now fixed: https://github.com/containernetworking/cni/releases/tag/v1.1.0

Once containerd picks up this version (should be soon), this will mostly be a non-issue. However, administrators should update their CNI plugins if they are packaging them themselves.

**Comment by rolfedh** [comment]
Issue resolved by updating the software and updating the release note. This PR is no longer needed.
Context: https://kubernetes.slack.com/archives/C0156PJ62RE/p1651098266321399?thread_ts=1650379911.716169&cid=C0156PJ62RE

**Comment by sftim** [comment]
BTW, it's an issue for containerd _and_ CRI-O (as I understand it). All container runtimes affected by the `libcni` bug need to update.
