### ISSUE TITLE
remove SkipUnlessFeatureGateEnabled

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#109648]
### What would you like to be added?

The E2E framework has SkipUnlessFeatureGateEnabled which tricks developers into thinking that they can write tests that only run when a feature gate is enabled. That doesn't work:
- the e2e.test binary has no way of checking which feature gates are enabled in the Kubernetes cluster
- the `-feature-gate` parameter in test/e2e is not used either

We should remove SkipUnlessFeatureGateEnabled. I would also remove the `-feature-gate`. Apparently the corresponding field is used in some node e2e suite. Let's move the flag there.

/sig testing

### Why is this needed?

Avoid developer mistakes...

**Comment by aojea** [comment]
Yessss

**Comment by pohly** [comment]
@dims: looking at current usages of the function, some are from you in https://github.com/kubernetes/kubernetes/commit/6c76fe9c14a6914e292dcde4c48bce082f0c94d7

Does that code mean that the test runs because the feature gate is enabled by default? Or was there ever a way to actually control the feature gate state?

**Comment by pohly** [comment]
`test/e2e_node` has code which modifies the global default feature gate base on this `--feature-gates` parameter. But that's the only place where `SkipUnlessFeatureGateEnabled` then actually works.

Do we have any jobs that use the parameter? Yes:
```
config/jobs/kubernetes/sig-node/crio.yaml:          - '--node-test-args=--feature-gates=LocalStorageCapacityIsolation=true ...
```

That means we cannot remove it outright. I think moving it into `test/e2e_node` is the right direction. It'll make using feature gates more complicated, but that is intentional: developers writing such code must be aware that it doesn't "just work".

**Comment by pohly** [comment]
/assign

Because e2e_node needs some kind of support for feature gate checking, I ended up keeping the e2eskipper functions for it. But now they will lead to a test failure when used inside test/e2e.

**Comment by pohly** [comment]
@dims: We do indeed have the situation that e2e conformance tests use e2eskipper.SkipUnlessFeatureGateEnabled in the test/e2e binary whether that call only checked the feature gate default. Now they fail:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109649/pull-kubernetes-e2e-kind-ipv6/1518552551622971392

Should these redundant checks be removed?

The only downside that I can see is when a test gets used in one suite where feature gate checking is not enabled *and* in another suite where it is enabled. This seems a bit far-fetched.

**Comment by dims** [comment]
@pohly hmm let's update this PR to remove these checks and get sign off from @SergeyKanzhelev and other sig-noders.

I probably got it wrong :(

**Comment by SergeyKanzhelev** [comment]
Ideally we need to remove all use of these functions. Those are only confusing.

With this proposal: https://github.com/kubernetes/enhancements/issues/3041 filtering will be easier in test definitions.

we may want to explore the reading kubelet feature gates via `/configz` endpoint for runtime validation. But I don't think it is needed right away
