### ISSUE TITLE
kubectl drain should not require permissions to list daemonsets

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#109605]
### What happened?

`kubectl drain $node_name --ignore-daemonsets=true`
failed because it requires to list daemonsets

### What did you expect to happen?

it working without that permissions

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Anything else we need to know?

this is a workaround:
```
    kubectl get pods --all-namespaces --field-selector spec.nodeName=$node_name -o json | \
      jq 'del(.items[] | select(.metadata.ownerReferences[]? | .kind=="DaemonSet"))' | \
      kubectl delete -f -
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.0-beta.1", GitCommit:"40a411a61af315f955f11ee97397beecf432ff4f", GitTreeState:"clean", BuildDate:"2021-03-09T09:23:56Z", GoVersion:"go1.16", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>
ubuntu
</details>

### Install tools

<details>
manual
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/422b867d4552ed173dac8159e0965a47b7853f71/staging/src/k8s.io/kubectl/pkg/drain/filters.go#L190-L197

It checks DaemonSet for removing orphaned pods with a warning if --force is used.

**Comment by grosser** [comment]
so sounds like:
- it should not do this request when not using `--force`
- it should continue with deleting and no warning if daemonset permissions are missing ? (aka ignore the error or just log it)

**Comment by pacoxu** [comment]
A possible fix would be like #109610.

However, if you use `--force` & `--ignore-daemonsets=true`, it will require permission to list daemonsets. This is somehow odd that permissions for same commands are different.

**Comment by brianpursley** [comment]
Related issue https://github.com/kubernetes/kubectl/issues/1220

**Comment by KnVerey** [comment]
> The problem seems to be that the code wants to handle "ophaned" pods... pods which were originally DaemonSet-managed, but then somehow still exist while the DaemonSet does not exist.

>> is this a valid scenario? I don't know.

Yes, it is valid. For example, you can cause this with kubectl by running `kubectl delete --cascade=orphan` on the owner. I think it _could_ also happen if you run `kubectl delete --force` on the pod, since that will delete the API's record of the pod's existence whether or not the pod stops running (so when the owner is later deleted, the API machinery won't know about the pod to clean it up).

For more context, I found the PR where the orphan cleanup code was introduced: https://github.com/kubernetes/kubernetes/pull/41864. It links to the following bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1424678
