### ISSUE TITLE
e2e-cos test is flaky

### ISSUE THREAD

**Issue by xmcqueen** [kubernetes/kubernetes#109621]
### Which jobs are flaking?

ci-cri-containerd-e2e-cos-gce

### Which tests are flaking?

Kubernetes e2e suite: [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] [Flaky] kubectl explain works for CR with the same resource name as built-in object.

Kubernetes e2e suite: [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kube-controller-manager restarts should delete a bound PVC from a clientPod, restart the kube-control-manager, and ensure the kube-controller-manager does not crash 

### Since when has it been flaking?

I don't know, but I think it should not even be considered to be flaky. As of now its categorized as flaky in testgrid. I see that the aggregated test results do show occasional passes. links below

### Testgrid link

https://testgrid.k8s.io/sig-node-cos#e2e-cos-flaky

### Reason for failure (if possible)

* Kubernetes e2e suite: [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] [Flaky] kubectl explain works for CR with the same resource name as built-in object.

```
Apr 22 04:21:52.905: failed to explain ksvc-1650601303.spec: error running /workspace/github.com/containerd/containerd/kubernetes/platforms/linux/amd64/kubectl --server=https://34.127.94.163 --kubeconfig=/workspace/.kube/config --namespace=crd-publish-openapi-1888 explain ksvc-1650601303.spec:
Command stdout:

stderr:
the server doesn't have a resource type "ksvc-1650601303"

error:
exit status 1
```

* Kubernetes e2e suite: [sig-storage] NFSPersistentVolumes[Disruptive][Flaky] when kube-controller-manager restarts should delete a bound PVC from a clientPod, restart the kube-control-manager, and ensure the kube-controller-manager does not crash

```
I0422 04:21:08.327] Apr 22 04:21:08.326: FAIL: Unexpected error:
I0422 04:21:08.327]     <*errors.errorString | 0xc004123b10>: {
I0422 04:21:08.328]         s: "pod \"pvc-tester-s6s4k\" is not Running: timed out waiting for the condition",
I0422 04:21:08.328]     }
I0422 04:21:08.328]     pod "pvc-tester-s6s4k" is not Running: timed out waiting for the condition
I0422 04:21:08.328] occurred
I0422 04:21:08.328] 
```

### Anything else we need to know?

[aggregated results CustomResourcePublishOpenAPI](https://github.com/kubernetes/kubernetes/issues/109621#issue-1212621892)

[aggregated results NFSPersistentVolumes](https://storage.googleapis.com/k8s-triage/index.html?test=NFSPersistentVolumes#6ef95530dce6fa011cdb)

### Relevant SIG(s)

/sig node

**Comment by xmcqueen** [comment]
Can somebody send me a pointer about these regexes?  I don't see anything in regexp, nor in the json annotations for the Mashalling that would explain these UPPERCASE words in this regex for the faiing test.  They look like some DSL for flattened objects, but I don't see where its coming from.  I must be missing something:

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/crd_publish_openapi.go#L499

`(?s)DESCRIPTION:.*Specification of CustomService.*FIELDS:.*dummy.*<string>.*Dummy property`

**Comment by aojea** [comment]
ups , I´ve just realised you removed the original sigs, @xmcqueen , any reason to assign this to node instead of api-machinery and storage?

**Comment by xmcqueen** [comment]
@aojea yes the reason, is not a good one. The answer is I don't really know what I'm doing. I just wanted to get this going so I could get into debugging these tests myself.  I'll take whatever advice.

**Comment by aojea** [comment]
> @aojea yes the reason, is not a good one. The answer is I don't really know what I'm doing. I just wanted to get this going so I could get into debugging these tests myself. I'll take whatever advice.

hahah, no worries then let people from the sigs owning the test chime in

**Comment by xmcqueen** [comment]
FTR the answer to my above question about the regex. It matches `kubectl explain` not the schema string.  Its obvious from [here](https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/test/e2e/apimachinery/crd_publish_openapi.go#L718).

> `(?s)DESCRIPTION:.*Specification of CustomService.*FIELDS:.*dummy.*<string>.*Dummy property`

**Comment by xmcqueen** [comment]
I have confirmed via local testing is the `kubectl explain` is done twice this test passes, so this flaky test is entirely within the expectations of the caveats in the [comments](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/crd_publish_openapi.go#L481):


`        // Marked as flaky until https://github.com/kubernetes/kubernetes/issues/65517 is solved.`

**Comment by xmcqueen** [comment]
I think I found a decent clue about the failing of the NFSPersistentVolumes test.  Its waiting for a pod, and that pod is failing to schedule due to an untolerated taint.  Here's a lone from the [stdout](https://prow.k8s.io/57564f94-e9f7-4608-95ab-f23dc00f9aeb):

```
                    Message: "0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/master: }, 1 node(s) were unschedulable, 4 node(s) had volume node affinity conflict. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.",

```

**Comment by xmcqueen** [comment]
everything looks OK in [there](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-flaky/1522588769654411264/build-log.txt) except for this bit about having a problem connecting to the NFS server:

```
I0506 15:13:03.335] [1mSTEP[0m: locating the "nfs-server" server pod
I0506 15:13:03.374] May  6 15:13:03.374: INFO: Running '/workspace/github.com/containerd/containerd/kubernetes/platforms/linux/amd64/kubectl --server=https://35.233.151.41 --kubeconfig=/workspace/.kube/config --namespace=disruptive-pv-6506 logs nfs-server nfs-server'
I0506 15:13:03.608] May  6 15:13:03.608: INFO: stderr: ""
I0506 15:13:03.608] May  6 15:13:03.608: INFO: stdout: "Serving /exports\nrpcinfo: can't contact rpcbind: : RPC: Unable to receive; errno = Connection refused\nStarting rpcbind\nNFS started\n"
I0506 15:13:03.609] May  6 15:13:03.608: INFO: nfs server pod IP address: 10.64.0.18
```

I don't know how to debug that at the moment.

**Comment by xmcqueen** [comment]
/sig storage
/remove-sig node

This fixes the labels, which I broke earlier.

**Comment by xmcqueen** [comment]
There are folks inquiring about the CustomResourcePublishOpenAPI failure (the first flaky test listed above) in #65517 and a proposed solution in #96771. I've put a comment into the PR to try to get the PR owner to update the status so it can get another review and possible merge, and I'm linking these issues together so their progress can be tracked from here.

**Comment by xmcqueen** [comment]
The CI test is still flaking and I've verified locally that with the @soltysh included, the test still fails, but when I put in a useless extra call before the verify step, then it passes.  This probably means that @soltysh has the right theory, but the test is not using his code.  The test is doing `kubectl explain`, and I'm not sure if `kubectl` is pulling in the `soltysh/shortcut_expander` code.

**Comment by brianpursley** [comment]
I did a little more investigation and it does appear to be a cache issue, but probably not a client-side cache issue (at least I don't think so).

Adding `-v8` when the explain fails, I see this:
```
I0714 16:11:26.885363  455921 round_trippers.go:463] GET https://192.168.200.11:6443/openapi/v2?timeout=32s
I0714 16:11:26.885374  455921 round_trippers.go:469] Request Headers:
I0714 16:11:26.885385  455921 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0714 16:11:26.885394  455921 round_trippers.go:473]     User-Agent: kubectl/v1.25.0 (linux/amd64) kubernetes/202d1e6
I0714 16:11:26.935474  455921 round_trippers.go:574] Response Status: 200 OK in 50 milliseconds
I0714 16:11:26.935543  455921 round_trippers.go:577] Response Headers:
I0714 16:11:26.935571  455921 round_trippers.go:580]     Accept-Ranges: bytes
I0714 16:11:26.935593  455921 round_trippers.go:580]     Last-Modified: Thu, 14 Jul 2022 20:11:03 GMT
I0714 16:11:26.935622  455921 round_trippers.go:580]     Content-Type: application/octet-stream
I0714 16:11:26.935649  455921 round_trippers.go:580]     Vary: Accept-Encoding
I0714 16:11:26.935675  455921 round_trippers.go:580]     Vary: Accept
I0714 16:11:26.935702  455921 round_trippers.go:580]     X-From-Cache: 1
I0714 16:11:26.935727  455921 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: d713bb93-d1d4-4efc-b164-96249bee30bc
I0714 16:11:26.935760  455921 round_trippers.go:580]     Date: Thu, 14 Jul 2022 20:11:27 GMT
I0714 16:11:26.935786  455921 round_trippers.go:580]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0714 16:11:26.935813  455921 round_trippers.go:580]     Audit-Id: 1ef204ad-06a1-44f3-a609-2a5875e3b5f9
I0714 16:11:26.935840  455921 round_trippers.go:580]     Cache-Control: no-cache, private
I0714 16:11:26.935868  455921 round_trippers.go:580]     Etag: "E33959BF14CC592F8F36B7950CA8C54472D3280A613BB36BFC8A1C682AA1D0D2F3EF2C88E0D692344160BF231F85E0B016A9A70F9BAC148865810F8615C34E7B"
I0714 16:11:26.935900  455921 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: e8a96152-0fea-47df-a47a-a2484791f6eb
```

The line:
```
I0714 16:11:26.935702  455921 round_trippers.go:580]     X-From-Cache: 1
```

But when explain succeeds, I see this, with no `X-From-Cache` response header, and the ETAG is different
```
I0714 16:11:27.354722  455936 loader.go:372] Config loaded from file:  /home/bpursley/.kube/config
I0714 16:11:27.355932  455936 round_trippers.go:463] GET https://192.168.200.11:6443/openapi/v2?timeout=32s
I0714 16:11:27.355963  455936 round_trippers.go:469] Request Headers:
I0714 16:11:27.355991  455936 round_trippers.go:473]     Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0714 16:11:27.356015  455936 round_trippers.go:473]     User-Agent: kubectl/v1.25.0 (linux/amd64) kubernetes/202d1e6
I0714 16:11:27.912672  455936 round_trippers.go:574] Response Status: 200 OK in 556 milliseconds
I0714 16:11:27.912746  455936 round_trippers.go:577] Response Headers:
I0714 16:11:27.912775  455936 round_trippers.go:580]     Cache-Control: no-cache, private
I0714 16:11:27.912806  455936 round_trippers.go:580]     X-Varied-Accept: application/com.github.proto-openapi.spec.v2@v1.0+protobuf
I0714 16:11:27.912836  455936 round_trippers.go:580]     Etag: "83719D49BCB733C007C202170DBCA0554157914CD82AD936F0BC6831ADA5F5DC6D14760580B226AF5B4CA5CFF8FA51BAE010EEF1D794796FDF74A126CE9331C0"
I0714 16:11:27.912868  455936 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: d713bb93-d1d4-4efc-b164-96249bee30bc
I0714 16:11:27.912895  455936 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: e8a96152-0fea-47df-a47a-a2484791f6eb
I0714 16:11:27.912922  455936 round_trippers.go:580]     Audit-Id: 4fd62e8a-c7e3-4b40-a4e9-122c6785bf03
I0714 16:11:27.912949  455936 round_trippers.go:580]     Content-Type: application/octet-stream
I0714 16:11:27.912976  455936 round_trippers.go:580]     Last-Modified: Thu, 14 Jul 2022 20:11:27 GMT
I0714 16:11:27.913001  455936 round_trippers.go:580]     Vary: Accept-Encoding
I0714 16:11:27.913028  455936 round_trippers.go:580]     Vary: Accept
I0714 16:11:27.913054  455936 round_trippers.go:580]     Date: Thu, 14 Jul 2022 20:11:28 GMT
I0714 16:11:27.913080  455936 round_trippers.go:580]     Accept-Ranges: bytes
```

**Comment by brianpursley** [comment]
Looks like the test uses [`waitForOpenAPISchema`](https://github.com/kubernetes/kubernetes/blob/857458cfa5b0083bc55736aaccbcf1dc796ba320/test/e2e/apimachinery/crd_publish_openapi.go#L645), so it is supposed to be waiting for the CRD to show up in OpenAPI before continuing.  

I saw this line in the code that made me think maybe this is a HA issue, where the OpenAPI is updated on one server, but not yet on another server.  Is that possible?
https://github.com/kubernetes/kubernetes/blob/857458cfa5b0083bc55736aaccbcf1dc796ba320/test/e2e/apimachinery/crd_publish_openapi.go#L658

I guess some more troubleshooting is needed...

**Comment by brianpursley** [comment]
Thoughts on this PR to fix `the server doesn't have a resource type "ksvc-1650601303"`?
https://github.com/kubernetes/kubernetes/pull/111184

Basically just calling `kubectl api-resources` after the CRD is created, so that kubectl's discovery cache is cleared.  It seems to fix the problem for me locally and in that PR's CI after unmarking that test as `[Flaky]`.

**Comment by xmcqueen** [comment]
I didn't know that forces a clear of the discovery cache. Also that sounds like a decent proposal, and is consistent with the other theories.  The previous attempts to fix it focused directly on re-running the specific api call.  I like this proposal to clear the cache.  I say its worth a try. I'll go put a comment on that PR.

**Comment by dims** [comment]
/reopen

Both these flakes are still around:
https://testgrid.k8s.io/google-gce#gci-gce-flaky

**Comment by dims** [comment]
Hits for the CRD flake:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=kubectl%20explain%20works%20for%20CR%20with%20the%20same%20resource%20name

Hits for the storage flake:
https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=when%20kube-controller-manager%20restarts%20should%20delete%20a%20bound%20PVC
