### ISSUE TITLE
Don't admit pods if node capacity is 0

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#10962]
If the kubelet can't retrieve machine info from cadvisor for some reason (or cadvisor really returns 0 cpu/mem), it reports node capacity as 0. If the scheduler comes across a pod with 0 capacity, it short circuits the fitness check.

In reality getting machine info from cadvisor is really straight forward and there's no reason it should fail, but the scheduler sholdn't assign pods to nodes that have 0 capacity. I suspect this is because we *don't* want the kubelet to start rejecting pods if cadvisor can't figure out capacity.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/kubelet/kubelet.go#L2010
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/plugin/pkg/scheduler/algorithm/predicates/predicates.go#L125

**Comment by davidopp** [comment]
+1
