### ISSUE TITLE
CustomResourceDefinition spec does not have serviceAccount field.

### ISSUE THREAD

**Issue by kaushiksrinivas** [kubernetes/kubernetes#109638]
### What happened?

Custom resource definitions are created using kubectl apply of the CRD yaml file or via the REST API. We do not see the service account field being part of the CRD spec. Does one require cluster role privileges to register the CRD into the k8s api server ? If not via service account, how is the user allowed/denied to add the CRD into the api server ?

Is there any documentation link covering these aspects of authentication and authorization of the user performing CRUD operations on the CRD for operators development ?

### What did you expect to happen?

CRUD operations on CRD would require authentication or cluster role privileges. If so, would like this aspect to be documented.

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Kubernetes version

NA

### Cloud provider

NA

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by JayKayy** [comment]
I would be interested in working on this, given we decide its the way to go

**Comment by kaushiksrinivas** [comment]
Hi @liggitt ,
Thank you for the detailed response.

Trying to summarize the configurations for kubectl to be able to create the CRDs below.
1. kubectl uses default **$HOME/.kube/config file.** 
2. config file content could be something like, 
   `users:
      - name: kubectl
        user:
          **client-certificate: /etc/kubernetes/ssl/cluster-admin.pem**
          client-key: /etc/kubernetes/ssl/cluster-admin-key.pem`
3.  Organization set in the cert  "/etc/kubernetes/ssl/cluster-admin.pem" is **"system:masters"**
     This organization name i.e "masters" **effectively represents the group** of the kubectl client when it interacts to the api server.
4.  Cluster role (cluster-admin) with below contents created in the k8s system
     `rules:
        **- apiGroups:
          - '*'
          resources:
          - '*'**
          verbs:
          - '*'
          - nonResourceURLs:
          - '*'
         verbs:
          - '*'`
          
       This cluster role is bound to **"masters" subject** via a role binding as below
        `roleRef:
          apiGroup: rbac.authorization.k8s.io
          **kind: ClusterRole
          name: cluster-admin**
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          **kind: Group
          name: system:masters**`

Summarizing, kubectl is authenticated via the certificates. Certificate organization name is the group name for the kubectl client. The group is provided access on CRD via the cluster role/role binding. 

Please confirm if the above understanding is correct.

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/109638#issuecomment-1110621565 is one way to accomplish what you want. It makes the kubectl client use a superuser credential which is authorized to do *anything*, including create/modify CRD objects
