### ISSUE TITLE
Create unix socket endpoint for Kubelet

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#109671]
### What would you like to be added?

Create an unix domain socket endpoint (i.e. /var/lib/kubelet/kubelet.sock) for Kubelet's http services (e.g. /healthz)

### Why is this needed?

Some requests to Kubelet only travel within a host. Relying on a unix domain socket can bypass `netfilter`, which sometimes is not working due to full conntrack table. Besides, it's safer and lightweight compared to the localhost endpoint.

**Comment by aojea** [comment]
are there any security issues with that approach?
