### ISSUE TITLE
Incorrect metrics of container might be generated when pod start or stop

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#109679]
### What happened?

As described in [#1009](https://github.com/kubernetes-sigs/metrics-server/pull/1009), When the pod start or stop, negative metrics  generated. 
```
# HELP container_start_time_seconds [ALPHA] Start time of the container since unix epoch in seconds
# TYPE container_start_time_seconds gauge
container_start_time_seconds{container="metrics-server",namespace="kubernetes-dashboard",pod="kubernetes-dashboard-metrics-server-77db45cdf4-fppzx"} -6.7953645788713455e+09 -62135596800000
container_start_time_seconds{container="metrics-server",namespace="kubernetes-dashboard",pod="kubernetes-dashboard-metrics-server-77db45cdf4-tpx4v"} 1.6509742024191372e+09 1650974202419
```

### What did you expect to happen?

generate the correct metrics

### How can we reproduce it (as minimally and precisely as possible)?

pod restart

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yangjunmyfm192085** [comment]
This is a feedback from contributors in kubernetes-sigs/metrics-server. It should not appear all the time, otherwise metrics-server will not work all the time. From the description of several issues, the way to reproduce should be pod restart
such as:
https://github.com/kubernetes-sigs/metrics-server/issues/983#issuecomment-1080630384

**Comment by SergeyKanzhelev** [comment]
Do you know if this is specific to `metrics-server`?

**Comment by yangjunmyfm192085** [comment]
I'm not sure. However, metrics-server obtains data from the kubelet metrics/resource endpoint. If there is a negative value, it will cause statistical problems.

**Comment by AtkinsChang** [comment]
@SergeyKanzhelev @yangjunmyfm192085
FYI I encounter this with `cir-o 1.23`.
`-62135596800000` seems to be an uninitialized time type.

https://github.com/kubernetes/kubernetes/blob/aa49dffc7f24dc31dd333869be8e6e3cdfc00af9/pkg/kubelet/stats/cri_stats_provider.go#L602

The `StartTime` in `ContainerStats` is create from the response of cri `ListContainers` RPC, this maybe cause either by cri-o or the metrics collect part of Kubernetes. I have not dig into it yet.
