### ISSUE TITLE
1.20.0: kubelet crashing with concurrent map writes

### ISSUE THREAD

**Issue by dbazhal** [kubernetes/kubernetes#109636]
### What happened?

There was pod, scheduled to node, and all unusual it had was pvc, provided by rook-ceph.
During pod start kubelet shown logs about that pod's container start:
```
Apr 22 13:31:01 worker-node.company.tld crio[1469]: time="2022-04-22 13:31:01.859500599Z" level=info msg="Creating container: eco-checkout/frontend-core-d9xxr-deploy-to-prod-wrp6d-pod-kxmsf
/step-deploy" id=9e2f0428-b3e7-4da2-96f7-d5883fb24b06 name=/runtime.v1alpha2.RuntimeService/CreateContainer
Apr 22 13:31:02 worker-node.company.tld systemd[1]: Started crio-conmon-fafa380d194768155878311453b46fa907f3d96abf588b27d7a844f95e9d180c.scope.
Apr 22 13:31:02 worker-node.company.tld systemd[1]: Started libcontainer container fafa380d194768155878311453b46fa907f3d96abf588b27d7a844f95e9d180c.
Apr 22 13:31:02 worker-node.company.tld kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
Apr 22 13:31:02 worker-node.company.tld crio[1469]: time="2022-04-22 13:31:02.205064774Z" level=info msg="Created container fafa380d194768155878311453b46fa907f3d96abf588b27d7a844f95e9d180c:
 eco-checkout/frontend-core-d9xxr-deploy-to-prod-wrp6d-pod-kxmsf/step-deploy" id=9e2f0428-b3e7-4da2-96f7-d5883fb24b06 name=/runtime.v1alpha2.RuntimeService/CreateContainer
```
Right after that kubelet crashed with:
```
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: fatal error: concurrent map writes
```
I am attaching subsequent logs, but I believe traceback leads to
```
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: created by k8s.io/kubernetes/pkg/kubelet/server/stats.(*volumeStatCalculator).StartOnce.func1
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]:        /tmp/openshift/build-rpms/rpm/BUILD/openshift-1.20.0/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/server/stats/volume_stat_calculator.go:64 +0x9d
```
but maybe I may have mistaken.
[fatal_part.log](https://github.com/kubernetes/kubernetes/files/8549414/fatal_part.log)
If this can help, I could attach wider logs before/after this events, but for me, that was just usual node lifecycle noise - services/pods/volumes creating and cleanup.

### What did you expect to happen?

I was expecting kubelet not to crash.

### How can we reproduce it (as minimally and precisely as possible)?

I don't really know what could possibly lead to this behaviour, I could not find anything unusual during that time at system level, nor at user level.

### Kubernetes version

<details>

```console
$ kubectl version
v1.20.0+7d0a2b2-1058
```

</details>

### Cloud provider

<details>
self-hosted openshift kubernetes distribution (OKD)
</details>

### OS version

<details>

```console
$ cat /etc/os-release
Fedora CoreOS 34 48.34.202111121953-0
$ uname -a
5.14.14-200.fc34.x86_64
```

</details>

**Comment by SergeyKanzhelev** [comment]
@dbazhal any chance you can try to repro this on 1.23? Are there clear steps to repro or it just happened once?

/triage needs-information

**Comment by rphillips** [comment]
The crash here is in the containermap Add(). This area has has numerous updates in the later versions of Kubernetes. I agree with @SergeyKanzhelev that the latest 1.2x or a later minor release should be tried.

```
 22 13:31:02 worker-node.company.tld hyperkube[1540]: fatal error: concurrent map writes
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: goroutine 454 [running]:
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: runtime.throw(0x4914893, 0x15)
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: 	/usr/lib/golang/src/runtime/panic.go:1116 +0x72 fp=0xc00a4915f8 sp=0xc00a4915c8 pc=0x43d132
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: runtime.mapassign_faststr(0x43f3ce0, 0xc0013e0c00, 0xc001ab04b8, 0x40, 0x0)
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: 	/usr/lib/golang/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc00a491660 sp=0xc00a4915f8 pc=0x419f91
Apr 22 13:31:02 worker-node.company.tld hyperkube[1540]: k8s.io/kubernetes/pkg/kubelet/cm/containermap.ContainerMap.Add(...)

```

**Comment by dbazhal** [comment]
> @dbazhal any chance you can try to repro this on 1.23? Are there clear steps to repro or it just happened once?

Sorry, I can't even come up with any idea on how can I collect wider description of circumstances this situation happened in. And this only happened once.
Thank you for advice, we've updated to 1.21, and we'll watch the situation now.
I'll bump issue if this happens again.
