### ISSUE TITLE
etcd: Update to v3.5.4

### ISSUE THREAD

**Issue by stevo-f3** [kubernetes/kubernetes#109707]
Please publish 3.5.4-0 image and update to [etcd v3.5.4](https://github.com/etcd-io/etcd/releases/tag/v3.5.4) to benefit from fix https://github.com/etcd-io/etcd/pull/13950 for https://github.com/etcd-io/etcd/issues/13948, while still keeping v3.5.3 critical correctness fixes (https://github.com/etcd-io/etcd/issues/13766, https://github.com/etcd-io/etcd/issues/13514).

For recent PRs for update to etcd v3.5.3 see https://github.com/kubernetes/kubernetes/pull/109470 and https://github.com/kubernetes/kubernetes/pull/109471

**Comment by rushikeshsuryawanshi** [comment]
Hey, 
Can I work on this ? I'm a beginner, but all the good first issues are mostly assigned. 
Can you guide me on doing this ?

**Comment by mk46** [comment]
I am working on this.
/assign

**Comment by mk46** [comment]
Hi @neolit123, I would like to work on https://github.com/kubernetes/kubernetes/pull/109533#issuecomment-1140822955
Make sense to backport in v1.22, v1.23 & v1.24?
Thanks!!

**Comment by neolit123** [comment]
> Hi @neolit123, I would like to work on [#109533 (comment)](https://github.com/kubernetes/kubernetes/pull/109533#issuecomment-1140822955)

hi, it makes sense to me, but requires approval from dependency maintainers.
i can only approve the kubeadm changes.

**Comment by rahulonmars** [comment]
> > Hi @neolit123, I would like to work on [#109533 (comment)](https://github.com/kubernetes/kubernetes/pull/109533#issuecomment-1140822955)
> 
> hi, it makes sense to me, but requires approval from dependency maintainers. i can only approve the kubeadm changes.

was this backported ?
