### ISSUE TITLE
Kubelet creates leases without ownerReference set if node doesn't exist

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#109777]
### What happened?

* Some external controller deleted node object while kubelet was alive
* Due to ignoring errors in kubelet's lease logic, it created lease without ownerReference set

### What did you expect to happen?

* Kubelet doesn't create lease without ownerReference set in any case, even pathological one

### How can we reproduce it (as minimally and precisely as possible)?

* Some external controller deletes node object
* Garbage collector properly deletes associated lease object
* Kubelet tries to update object and it fails on Conflict (saying that UID doesn't match): 
  https://github.com/kubernetes/kubernetes/blob/b1e130fe83156783153538b6d79821c2fdaa85bb/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L179-L198
* We go to `apierrors.IsConflict(err)` branch, call backoffEnsureLease and assign result to base, but backoffEnsureLease may return potentially invalid object if ensureLease returned error (which happens when newLeasePostProcessFunc returns error, e.g. when node doesn't exist).
* We `continue`
* The next loop calls c.newLease on the incorrect base and ignores error in line 181 (so the second attempt to call newLeasePostProcessFunc which also fails with an error) 
* We do UPDATE with incomplete (without effect of newLeasePostProcessFunc) object
* Given that leases allow CreateOnUpdate a new object, without ownerReference is created: https://github.com/kubernetes/kubernetes/blob/b1e130fe83156783153538b6d79821c2fdaa85bb/pkg/registry/coordination/lease/strategy.go#L65-L68

### Kubernetes version

<details>
1.21.10
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by uesyn** [comment]
We are in trouble for this problem too. 
I think It’s exactly as @mborsz said. Lease objects has a special update endpoints. If it receives request with a lease object which has non-nil UID field and it is not found, **returns a conflict error**.
This situation can be occured in the [retryUpdateLease](https://github.com/kubernetes/kubernetes/blob/6ed938fc8f3a9d99e5e0347c57055678891739a4/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L177-L198) function when a lease object is deleted.  The lease object is deleted when node resource is deleted in the result of GC.
When received a conflict error in updating a lease object and the node object doesn't exist, [the base variable is set with nil by the ensureLease function](https://github.com/kubernetes/kubernetes/blob/6ed938fc8f3a9d99e5e0347c57055678891739a4/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L189-L192), and continue next loop. In the next loop, the [newLease](https://github.com/kubernetes/kubernetes/blob/6ed938fc8f3a9d99e5e0347c57055678891739a4/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L181) function returns the new lease object without ownerReference and UID. As a result, it is created unexpectively by the special update endpoint.
