### ISSUE TITLE
Flaky scheduler integration tests

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#109783]
### Which jobs are flaking?

pull-kubernetes-integration

### Which tests are flaking?

TestSchedulerInformers, TestPodTopologySpreadFilter, TestTaintNodeByCondition

### Since when has it been flaking?

Unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestSchedulerInformers

### Reason for failure (if possible)

It timesout, but it's unclear at which point of the test.

### Anything else we need to know?

@aojea mentioned that it might be related to #109755 and #109749

### Relevant SIG(s)

/sig scheduling

**Comment by aojea** [comment]
seems this has been going on for a while
https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5

**Comment by aojea** [comment]
All the tests seems to fail at same time

![image](https://user-images.githubusercontent.com/6450081/166725480-b93ebd6a-b509-4181-abeb-9aaec69ad9ba.png)


The trace shows it is blocked on the controllers
```
rep sched build-log\ \(1\).txt  | grep taint_test
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:511 +0x28ed
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:113 +0x710
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:114 +0x7b8
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:559 +0x9d8
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:511 +0x28ed
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:113 +0x710
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:114 +0x7b8
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/integration/scheduler/taint_test.go:559 +0x9d8
```

**Comment by alculquicondor** [comment]
It also fails in another test https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109545/pull-kubernetes-integration/1521887980044685312 `TestPodTopologySpreadFilter`.

**Comment by alculquicondor** [comment]
All the three tests indeed wait for the pod to be unschedulable.

I don't think the condition change in https://github.com/kubernetes/kubernetes/pull/109442#discussion_r865027329 is the culprit.

But maybe it has something to do with #108761. The rationale being that if a Pod status update fails, retries now take longer.

**Comment by alculquicondor** [comment]
Maybe all the errors are not necessarily related.

For example, I see this in `TestPodTopologySpreadFilter` [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/109545/pull-kubernetes-integration/1521887980044685312/build-log.txt):

```
I0504 17:05:35.053339  119469 scheduler.go:351] "Unable to schedule pod; no fit; waiting" pod="postfilter1-08d6ab0a-daf1-4df2-acf9-0e0fd8ca453e/test-pod" err="0/1 nodes are available: . make room for pod test-pod to be schedulable"
I0504 17:05:35.053413  119469 schedule_one.go:847] "Updating pod condition" pod="postfilter1-08d6ab0a-daf1-4df2-acf9-0e0fd8ca453e/test-pod" conditionType=PodScheduled conditionStatus=False conditionReason="Unschedulable"
E0504 17:05:35.053963  119469 schedule_one.go:832] "Error updating pod" err="Patch \"http://127.0.0.1:40021/api/v1/namespaces/postfilter1-08d6ab0a-daf1-4df2-acf9-0e0fd8ca453e/pods/test-pod/status\": dial tcp 127.0.0.1:40021: connect: connection refused" pod="postfilter1-08d6ab0a-daf1-4df2-acf9-0e0fd8ca453e/test-pod"
E0504 17:05:35.053987  119469 event_broadcaster.go:262] Unable to write event: 'Post "http://127.0.0.1:40021/apis/events.k8s.io/v1/namespaces/postfilter1-08d6ab0a-daf1-4df2-acf9-0e0fd8ca453e/events": dial tcp 127.0.0.1:40021: connect: connection refused' (may retry after sleeping)
```

Since we take a long time to retry, we wouldn't be able to mark the status of this pod as "Unschedulable". Spinning this of in #109796

However, there is a 30s timeout for waiting for the condition, so I wouldn't expect this to reach the entire test panic.

I didn't find the same pattern in the [build log](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/109782/pull-kubernetes-integration/1521837161488322560/build-log.txt) for `TestTaintNodeByCondition`. However, this test creates pods sequentially after having verified that the previous one was scheduled or not. Maybe if the scheduling routine is particularly slow, the entire test is too slow. So we should be running the tests in parallel.

`TestSchedulerInformers` is rather a very small and fast test. I think it just got unlucky and got terminated because the entire package reached the timeout.

So I think the fix here is to increase the timeout and/or optimize existing tests.

**Comment by alculquicondor** [comment]
I think this is just a consequence of us increasing our test coverage.

We have some tests where the test cases depend on feature gates. Then for each test case we recreate the apiserver and scheduler instances, which takes a lot of time. For example, in this PR we added a feature gate #108362, and now the test takes about 1min.

I'll be taking a look at our overall suite and look for cases where:
- we can get rid of the apiserver+scheduler recreation.
- we have too many pods or retries. I already identified `TestPreemptionRaces`.

Another alternative would be to recreate the scheduler without recreating the apiserver, but currently they are tied to the same clean up functions.

**Comment by alculquicondor** [comment]
cc @ahg-g @Huang-Wei

**Comment by ahg-g** [comment]
> Another alternative would be to recreate the scheduler without recreating the apiserver, but currently they are tied to the same clean up functions.

As long as we are able to consistently cleanup the pods. But remember that in e2e tests we frequently suffer from tests influencing each other because of remanent objects that don't get deleted in a timely manner.

**Comment by wojtek-t** [comment]
> So I think the fix here is to increase the timeout and/or optimize existing tests.

That was my hypothesis also in:
https://github.com/kubernetes/kubernetes/pull/109760#issuecomment-1117320654

I think the fastest fix might be to simply split the tests into subpackages...

**Comment by alculquicondor** [comment]
> I think the fastest fix might be to simply split the tests into subpackages...

That would still be quite some code moving around, as we need to factor out the util functions into a package.

Quickest fix is #109825. Hopefully it is enough.

Then I think I can do the helper functions to recreate the scheduler without recreating the apiserver. We will all benefit from a faster test suite.

> As long as we are able to consistently cleanup the pods.

We already do that for every test case regardless, because the etcd is the same.

**Comment by ahg-g** [comment]
> We already do that for every test case regardless, because the etcd is the same.

oh, then I agree there is no reason to restart the api-server.

**Comment by aojea** [comment]
@wojtek-t is spot on and the problem is that the scheduler tests are close to 10 mins , it easy to see in the junit output of the jobs 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1522185621873889280/artifacts/junit_20220505-122815.xml

> <testsuite tests="173" failures="0" time="978.440000" name="k8s.io/kubernetes/test/integration/scheduler" timestamp="">

There are some tests that are very expensive

<testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="TestPodTopologySpreadFilter" time="61.760000"/>

<testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="TestUnschedulablePodBecomesSchedulable" time="39.350000"/>

<testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="TestPreemptionRaces/ensures_that_other_pods_are_not_scheduled_while_preemptor_is_being_marked_as_nominated_(issue_#72124)" time="47.270000"/>
<testcase classname="k8s.io/kubernetes/test/integration/scheduler" name="TestPreemptionRaces" time="52.020000"/>


splitting the test in subpackages seems the easier path

**Comment by wojtek-t** [comment]
>  <testsuite tests="173" failures="0" time="978.440000" name="k8s.io/kubernetes/test/integration/scheduler" timestamp="">

Hmm - 978s seems more than 10m which is the limit....

**Comment by Huang-Wei** [comment]
Late to the party, it seems the failing pattern is timeout. Under the hood, it throws a "connection refused" error, no matter it's an event logging, or a patchPodStatus() operation. The "connection refused" error, to my best knowledge, is due to a too-high QPS setting in client side. (we share the etcd instance)

With that being said, https://github.com/kubernetes/kubernetes/pull/109834, which tries to put tests into their specific package, increases the timeout for each case, which will mitigate the case. However, to fix the problem thoroughly, I'd like to revisit the QPS settings in the integration test:

https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/test/integration/util/util.go#L375

IIUC, `QPS=-1` means no RateLimiter, which IMO needs to be tweaked.

**Comment by Huang-Wei** [comment]
Another interesting symptom is: the scheduler related tests are using its own library to start API Server (where it sets a -1 QPS as mentioned above):

https://github.com/kubernetes/kubernetes/blob/ef410d18e11ef25cae6005c7a9686d62ea4da475/test/integration/util/util.go#L345

However, most tests in other components use another one, which doesn't set QPS (which would be defaulted to a negative value I guess):

https://github.com/kubernetes/kubernetes/blob/edac6fce2ad4a1366a73afc8ac9ca50b2fbf7fc7/test/integration/framework/controlplane_utils.go#L393

@alculquicondor @ahg-g we should dig into why the scheduler integration tests need its own logic to start API server, if it's unnecessary, turn to the common one (`RunAnAPIServer()`) to make our tests more consistent and maintainable. If you think it makes sense, I will work on the polishment.

**Comment by wojtek-t** [comment]
> @alculquicondor @ahg-g we should dig into why the scheduler integration tests need its own logic to start API server, if it's unnecessary, turn to the common one (RunAnAPIServer()) to make our tests more consistent and maintainable. If you think it makes sense, I will work on the polishment.

+1 - we should absolutely try to unify it
