### ISSUE TITLE
kube-scheduler does not allow two extenders implementing bindVerb(the two extenders have different managedResources)

### ISSUE THREAD

**Issue by yiwenshao** [kubernetes/kubernetes#109739]
### What happened?

I my cluster, I want to install two scheduler extenders. They have different managedResources and therefore different logic of binding. The configuration is as follows:

```

{
        "apiVersion": "kubescheduler.config.k8s.io/v1beta2",
        "kind": "KubeSchedulerConfiguration",
        "leaderElection": {
                "leaderElect": true
        },
        "extenders": [
                {
                        "enableHTTPS": false,
                        "filterVerb": "filter",
                        "bindVerb": "bind",
                        "urlPrefix": "http://resource1/v1",
                        "managedResources": [{
                                "name": "test.bare.com/resource-1"
                        }]
                },
                {
                        "enableHTTPS": false,
                        "filterVerb": "filter",
                        "bindVerb": "bind",
                        "urlPrefix": "http://resource2/v1",
                        "managedResources": [{
                                "name": "test.bare.com/resource-2"
                        }]
                }
        ]
}

```

However, the scheduler complains "only one extender can implement bind". According to the [doc](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/) and [code](https://github.com/kubernetes/kubernetes/blob/f173d01c011c3574dea73a6fa3e20b0ab94531bb/pkg/scheduler/apis/config/validation/validation.go#L301) only one extender implementing bindverb is allowed. However, in my situation, only one extender will be called for each pod. So, I hope scheduler would allow this configuration.

### What did you expect to happen?

The scheduler allows two extenders to run simultaneously. For a pod requesting resource-1, service1 is call, and service2 for resource-2.

### How can we reproduce it (as minimally and precisely as possible)?

1. start kube-scheduler with parameter: --config=/etc/kubernetes/scheduler-config.json
2. the content of  scheduler-config.json
```
{
        "apiVersion": "kubescheduler.config.k8s.io/v1beta2",
        "kind": "KubeSchedulerConfiguration",
        "leaderElection": {
                "leaderElect": true
        },
        "extenders": [
                {
                        "enableHTTPS": false,
                        "filterVerb": "filter",
                        "bindVerb": "bind",
                        "urlPrefix": "http://resource1/v1",
                        "managedResources": [{
                                "name": "test.bare.com/resource-1"
                        }]
                },
                {
                        "enableHTTPS": false,
                        "filterVerb": "filter",
                        "bindVerb": "bind",
                        "urlPrefix": "http://resource2/v1",
                        "managedResources": [{
                                "name": "test.bare.com/resource-2"
                        }]
                }
        ]
}
```

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# 5.15.0-18-generic #18-Ubuntu SMP Fri Jan 21 14:57:54 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
IIUC, if Pods have both resources, your scheduler will run two extenders in bind, so we cannot accept your proposal..
But, I feel it would be nice to have a way to select which extender is used for scheduling like this proposal
https://github.com/kubernetes/kubernetes/issues/101776
(I don't know if it will be implemented as this issue seems to have been neglected for a long time. 😓  )

**Comment by sanposhiho** [comment]
> Howerver, if a pods have multiple labels, which maps to multiple extenders, is it still possible that the scheduler will run two extenders in bind? just like what we will encounter when a pod have both resources.

Yeah, I think your guessing is right. 
So, I prefer this way. If we do this way, we can set two extenders.
> BTW: another option is to make extenders profile-leveled. We used to discuss this in other contexts, but seems it also fit this requirement.
https://github.com/kubernetes/kubernetes/issues/101776#issuecomment-841691754

**Comment by yiwenshao** [comment]
> > Howerver, if a pods have multiple labels, which maps to multiple extenders, is it still possible that the scheduler will run two extenders in bind? just like what we will encounter when a pod have both resources.
> 
> Yeah, I think your guessing is right. So, I prefer this way. If we do this ↓ way, we can set two extenders.
> 
> > BTW: another option is to make extenders profile-leveled. We used to discuss this in other contexts, but seems it also fit this requirement.
> > [#101776 (comment)](https://github.com/kubernetes/kubernetes/issues/101776#issuecomment-841691754)

Yeah, Making extenders profile-leveled seems more flexible.  I do not find further discussions on it [#101776 (comment)](https://github.com/kubernetes/kubernetes/issues/101776#issuecomment-841691754). Are there any plans on making extenders profile-leveled? Or should we write another KEP for it?

**Comment by kerthcet** [comment]
/assign

I'll write a KEP to push this forward.

**Comment by kerthcet** [comment]
Submitted a KEP here, if you have interest with this, feel free to provide any advices. kindly ping @yiwenshao

**Comment by alculquicondor** [comment]
High level question: did you consider using the scheduling framework instead?
