### ISSUE TITLE
GC doesn't delete already orphaned objects after startup

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#109748]
### What happened?

1. We have an object X that has ownerReference set to Y
2. garbage collector is down (for whatever reason)
3. Something deletes Y
4. garbage collector starts
5. garbage collector never attempts to delete X (despite its ownerReference is dangling), as the code isn't verifying if objects added as part of initial watch sync should be deleted https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/pkg/controller/garbagecollector/graph_builder.go#L665-L676

The object X is leaked forever.

### What did you expect to happen?

There is some reconcile loop that will either periodically try to remove dangling objects or we check if objects listed in initial sync are already orphaned (is adding them to attemptToDelete sufficient?).

### How can we reproduce it (as minimally and precisely as possible)?

Described in "what happened?"

### Kubernetes version

<details>
1.21.10
</details>

### Cloud provider

<details>
gke
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
I'm not able to reproduce the situation you describe.

1. I started a kube-apiserver
2. I created a configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycm
  ownerReferences:
  - name: myparent
    kind: Secret
    apiVersion: v1
    uid: bogus
```
3. I started the kube-controller-manager. It successfully logged finding the configmap, queuing the secret parent, processing the secret, noticing it is absent, and deleting the configmap:

```
I0502 16:26:39.031223    9654 garbagecollector.go:496] "Processing object" object="default/myparent" objectUID=bogus kind="Secret" virtual=true
I0502 16:26:39.033611    9654 garbagecollector.go:513] item [v1/Secret, namespace: default, name: myparent, uid: bogus] not found, generating a virtual delete event
I0502 16:26:39.033671    9654 graph_builder.go:632] GraphBuilder process object: v1/Secret, namespace default, name myparent, uid bogus, event type delete, virtual=true
I0502 16:26:39.033729    9654 garbagecollector.go:496] "Processing object" object="default/mycm" objectUID=f571cae4-d029-404a-809d-2fc20f1516e5 kind="ConfigMap" virtual=false
I0502 16:26:39.036325    9654 garbagecollector.go:404] according to the absentOwnerCache, object f571cae4-d029-404a-809d-2fc20f1516e5's owner v1/Secret, myparent does not exist in namespace default
I0502 16:26:39.036356    9654 garbagecollector.go:543] classify references of [v1/ConfigMap, namespace: default, name: mycm, uid: f571cae4-d029-404a-809d-2fc20f1516e5].
I0502 16:26:39.036389    9654 garbagecollector.go:608] "Deleting object" object="default/mycm" objectUID=f571cae4-d029-404a-809d-2fc20f1516e5 kind="ConfigMap" propagationPolicy=Background
I0502 16:26:39.039582    9654 graph_builder.go:632] GraphBuilder process object: v1/ConfigMap, namespace default, name mycm, uid f571cae4-d029-404a-809d-2fc20f1516e5, event type delete, virtual=false
```


> What did you expect to happen?
>
> There is some reconcile loop that will either periodically try to remove dangling objects or we check if objects listed in initial sync are already orphaned (is adding them to attemptToDelete sufficient?).

When observing initial data, the GC controller enqueues all parents that are not found in `attemptToDelete`, which does a live lookup and propagates a virtual delete event if they are verified missing. That triggers deletion of the children.

**Comment by liggitt** [comment]
Do you have a reproducer for the situation you describe?

**Comment by liggitt** [comment]
In your scenario, for the referenced parent object, is the specific *instance* missing, or is the entire parent *type* missing (e.g. ownerReferences points at a custom resource type, and the CRD is deleted so the type is no longer defined)?

If just the *instance* is missing (as in my example), I can't reproduce the issue.

If the parent *type* is no longer defined, that sounds like a duplicate of https://github.com/kubernetes/kubernetes/issues/102641

**Comment by mborsz** [comment]
In my scenario it was > 1k+ lease objects with ownerReference set to no longer existing Node objects.

I also tried to reproduce this locally, with leases and nodes and I failed, the leases were properly deleted in each case.

I will close and reopen if I find some repro.
