### ISSUE TITLE
Improve PodSpec Container name documentation

### ISSUE THREAD

**Issue by AplusKminus** [kubernetes/kubernetes#109769]
[Here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container) the text of the **name** specification contains:

> Name of the container specified as a DNS_LABEL.

However the documentation for [Object Names and IDs](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) does not know such a definition. It rather seems to know two -- RFC 1123 and RFC 1035.

Maybe the container name spec could be tightened?

**Comment by sftim** [comment]
Should we use internal names like `DNS_LABEL` in the API docs? If we do, should we publish those as part of the OpenAPI (I assume that we currently do not)?

**Comment by AplusKminus** [comment]
Just out of curiosity: @sftim how could I have seen/known that this ticket is better placed here than at kuberenetes/website? I got there through the "Create an issue" link on the right side of the page in question.

**Comment by sftim** [comment]
We've got a backlog item in SIG Docs to revise the “Create an issue” text for automatically generated pages. I wouldn't worry about that @AplusKminus - unless, that is, you'd like to help out with the docs generation tooling?

https://github.com/kubernetes-sigs/reference-docs/ if you _are_ interested&hellip;

**Comment by sftim** [comment]
This issue is now in a repo where we can triage it. The report was useful no matter where it was submitted.
