### ISSUE TITLE
Kubeadm static pods missing recommended labels

### ISSUE THREAD

**Issue by danp60** [kubernetes/kubernetes#109731]
### What happened?

The static pods that kubeadm generates contains two labels, `component` and `tier`. The code that adds these labels is here https://github.com/kubernetes/kubernetes/blob/e7a2ce75e5df96ba6ea51d904bf2735397b3e203/cmd/kubeadm/app/util/staticpod/utils.go#L67-L69

### What did you expect to happen?

Kubernetes has a set of recommended labels that should be applied to all resources here: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/. I would expect some of these labels to be applied, for example:

```
app.kubernetes.io/name: kube-apiserver
app.kubernetes.io/component: kube-apiserver
app.kubernetes.io/part-of: control-plane
app.kubernetes.io/version: "x.y.z"
```

Is there any reason why these recommended labels are not added? If there is no objection, I can prepare a PR to add them.

### How can we reproduce it (as minimally and precisely as possible)?

Create a new cluster with kubeadm and observe the labels on the static pods only container `component` and `tier` labels.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
That page has:

> In addition to supporting tooling, the recommended labels describe applications in a way that can be queried.

The namespace app.kubernetes.io is for applications deployed on top of k8s and that's what the recommendation is about.

While kubeadm control plane components are applications, i don't think they fit the criteria.

But interesting to see what other think.

One side effect if we label them like that they will start appearing in user filtered results. This needs a feature gate.

/priority awaiting-more-evidence

**Comment by danp60** [comment]
An additional data point I can provide, the `kube-proxy` and `kube-dns` apps that `kubeadm` generates uses the `k8s-app` label. https://github.com/kubernetes/kubernetes/blob/6445efb34161511c326fb708ed80f1f58dae2215/cmd/kubeadm/app/phases/addons/proxy/manifests.go#L71 and https://github.com/kubernetes/kubernetes/blob/6445efb34161511c326fb708ed80f1f58dae2215/cmd/kubeadm/app/phases/addons/dns/manifests.go#L77

I can't find any documentation on what `k8s-app` should be used for, but it does seem to be used for cluster level components https://github.com/kubernetes/kubernetes/search?p=1&q=%22k8s-app%22

WDYT about adding the k8s-app label for consistency? A feature gate makes sense to me.

**Comment by neolit123** [comment]
> I can't find any documentation on what k8s-app should be used for, but it does seem to be used for cluster level components

as far as i can tell the search results return addons. this is expected, since k8s-app originated in the legacy addon manager that was hosted in this repository. the k8s-app in kubeadm usage is to comply with the same legacy labeling.

i don't think k8s-app is a good fit for the CP components.
unless there is well defined demand for additional labels, i don't think we should take any action.

but quoting from earlier:
>> ...interesting to see what others think.

**Comment by neolit123** [comment]
/close

closing the ticket.
looks like there was no further interest or comments here from maintainers.
