### ISSUE TITLE
NUMA Affinity Configuration

### ISSUE THREAD

**Issue by satya12sahoo** [kubernetes/kubernetes#109766]
### Which jobs are failing?

I am trying to configure the NUMA Affinity in kubernets cluster. We have configured Hugepage as well CPU Pinning and same has been passed to Kubelet of Workernode.

### Which tests are failing?

29867 cpu_manager.go:158] "Detected CPU topology" topology=&{NumCPUs:8 NumCores:4 NumSockets:1 CPUDetails:map[0:{NUMANodeID:0 SocketID:0 CoreID:0} 1:{NUMANodeID:0 SocketID:0 CoreID:1} 2:{NUMANodeID:0 SocketID:0 CoreID:2} 3:{NUMANodeID:0 SocketID:0 CoreID:3} 4:{NUMANodeID:0 SocketID:0 CoreID:0} 5:{NUMANodeID:0 SocketID:0 CoreID:1} 6:{NUMANodeID:0 SocketID:0 CoreID:2} 7:{NUMANodeID:0 SocketID:0 CoreID:3}]}
29867 policy_static.go:109] "Reserved CPUs not available for exclusive assignment" reservedSize=2 reserved="0,4"
29867 container_manager_linux.go:358] "Failed to initialize memory manager" err="the total amount \"0\" of type \"memory\" is not equal to the value \"993Mi\" determined by Node Allocatable feature"
29867 server.go:292] "Failed to run kubelet" err="failed to run Kubelet: the total amount \"0\" of type \"memory\" is not equal to the value \"993Mi\" determined by Node Allocatable feature"
Apr 21 12:22:14 ip-10-0-2-187.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Apr 21 12:22:14 ip-10-0-2-187.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Apr 21 12:22:14 ip-10-0-2-187.ec2.internal systemd[1]: kubelet.service failed.

### Since when has it been failing?

After configuring NUMA Affinity

### Reason for failure (if possible)

Incorrect NUMA Configuration parameter passed

### Anything else we need to know?

Kube-reserved and System-reserved has been changed to Capacity and Allocation. So any use of kube-reserved and System-reserved

### Relevant SIG(s)

/sig node
/cloud-provider

**Comment by klueska** [comment]
This is due to a misconfiguration of the memory manager.

/cc @cynepco3hahue

**Comment by swatisehgal** [comment]
Please refer to the Memory manager documentation [here](https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/#memory-manager-configuration) and make sure you are configuring it correctly. If still not resolved, please provide details on how you are configuring kubelet (specifically memory manager).

**Comment by satya12sahoo** [comment]
Hello @swatisehgal 

In normal scenario, I had configure the NUMA with below parameter to Kubelet file

cat /etc/systemd/system/kubelet.service.d/30-kubelet-extra-args.conf
[Service]
Environment='KUBELET_EXTRA_ARGS=--feature-gates=MemoryManager=true --allowed-unsafe-sysctls=fs.mqueue.* --cpu-manager-policy=static --memory-manager-policy=Static --topology-manager-policy=single-numa-node --topology-manager-scope=pod --system-reserved=cpu=1,memory=2048Mi --kube-reserved=cpu=2,memory=4096Mi --reserved-memory 0:memory=6244Mi'

But this need to run with hugepage.

I had configure Hugepage in my Workernode. Now wants to run the kubelet with hugepage on worker node

Worker Node:
Capacity:
  attachable-volumes-aws-ebs:  25
  cpu:                         8
  ephemeral-storage:           83873772Ki
  hugepages-1Gi:               4Gi
  hugepages-2Mi:               2Gi
  intel.com/amazon_ena:        1
  memory:                      15917356Ki
  pods:                        110
Allocatable:
  attachable-volumes-aws-ebs:  25
  cpu:                         5
  ephemeral-storage:           77298068148
  hugepages-1Gi:               4Gi
  hugepages-2Mi:               2Gi
  intel.com/amazon_ena:        1
  memory:                      3232044Ki
  pods:                        110

As per kubernet [document](https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/), I had try to pass the hugepage parameter to kubelet file but its not working.

In document, its mention, only "cpu", "memory", "ephemeral-storage" and "pid" resources can be reserved for the kubelet and system daemons, through the configuration of the "--kube-reserved" and "--system-reserved" flags respectively.
But in reserved memory you can maintain the Hugepage.  i,e --reserved-memory 0:memory=1Gi,hugepages-1Gi=2Gi

Please correct me if I am wrong...!!!


[Service]
Environment='KUBELET_EXTRA_ARGS=--feature-gates=MemoryManager=true --allowed-unsafe-sysctls=fs.mqueue.* --cpu-manager-policy=static --memory-manager-policy=Static --topology-manager-policy=single-numa-node --topology-manager-scope=pod --system-reserved=cpu=1,memory=2048Mi --kube-reserved=cpu=2,memory=4096Mi --reserved-memory 0:memory=6244Mi,hugepages-2Mi=1Gi'

Error:
May 17 12:12:11 ip-10-0-3-41.ec2.internal kubelet[9115]: I0517 12:12:11.989863    9115 cpu_manager.go:158] "Detected CPU topology" topology=&{NumCPUs:8 NumCores:4 NumSockets:1 CPUDetails:map[0:{NUMANodeID:0 SocketID:0 CoreID:0} 1:{NUMANodeID:0 SocketID:0 CoreID:1} 2:{NUMANodeID:0 SocketID:0 CoreID:2} 3:{NUMANodeID:0 SocketID:0 CoreID:3} 4:{NUMANodeID:0 SocketID:0 CoreID:0} 5:{NUMANodeID:0 SocketID:0 CoreID:1} 6:{NUMANodeID:0 SocketID:0 CoreID:2} 7:{NUMANodeID:0 SocketID:0 CoreID:3}]}
May 17 12:12:11 ip-10-0-3-41.ec2.internal kubelet[9115]: I0517 12:12:11.989914    9115 policy_static.go:109] "Reserved CPUs not available for exclusive assignment" reservedSize=3 reserved="0-1,4"
May 17 12:12:11 ip-10-0-3-41.ec2.internal kubelet[9115]: E0517 12:12:11.989934    9115 container_manager_linux.go:358] "Failed to initialize memory manager" err="the total amount \"1Gi\" of type \"hugepages-2Mi\" is not equal to the value \"0\" determined by Node Allocatable feature"
May 17 12:12:11 ip-10-0-3-41.ec2.internal kubelet[9115]: E0517 12:12:11.989949    9115 server.go:292] "Failed to run kubelet" err="failed to run Kubelet: the total amount \"1Gi\" of type \"hugepages-2Mi\" is not equal to the value \"0\" determined by Node Allocatable feature"
May 17 12:12:11 ip-10-0-3-41.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
May 17 12:12:11 ip-10-0-3-41.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
May 17 12:12:11 ip-10-0-3-41.ec2.internal systemd[1]: kubelet.service failed.


I am unable to start the kubelet service with hugepage configuration.

Kindly suggest.
