### ISSUE TITLE
An Indexed Job mode that allows every index to execute

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#109712]
### What would you like to be added?

A mode of operation for Jobs with `.spec.completionMode="Indexed` that allows every index to execute. 

Currently this is not possible because when a job reaches its `.spec.backoffLimit`, active pods will be deleted; moreover, the job is declared failed and so no new pods are created for the indices that didn't execute yet (happens more often when parallelism < completions).

I can think of two open issues:
1. How to decide when to stop retrying a failed index. One approach is to consider backofflimit at the index level, this will be challenging to track per index in the job status, but one solution is to have the backofflimit with min semantics: each index is guaranteed to at least `backofflimit` retries, we track that in the job-controller memory for each index, and in status we only track which indexes reached the limit as a bitmap.
2. Job failure status: in the simplest case we could just declare the job failed if at least one index failed, but we could also introduce an API to allow users to tune that (perhaps based on a percentage or a min number of indexes).

Related comment to this issue: https://github.com/kubernetes/kubernetes/issues/109131#issuecomment-1088328034

### Why is this needed?

There are cases where the indexes represent independent operations, and so it is desired to continue and execute all of them before declaring the job complete.

**Comment by alculquicondor** [comment]
There is one more consideration:
For Indexed Jobs we limited the maximum value for `parallelism`. This is important so that the `.status.completedIndexes` doesn't go over a threshold. But the limit only works with the assumption that we always create the small indexes first. So if index `0` fails, we recreate a pod for it before creating a pod for index `parallelism`.
This assumption is now changing. So for this new mode, we might need to limit the maximum value for `completions`.

In that line, I think a way to solve the main problem of this issue is to introduce an `indexCreationPolicy`.
- `SmallestFirst` (current): create the smallest indexes before creating new indexes. 
- `NextIndex`: Create the next index that hasn't been tried before. I think we might need to add the `.status.failedIndexes` in order to be able to implement this.

But then we also need a policy for what to do when `backoffLimit` is reached. The current behavior is to abort all running pods. We need one for continuing. Not sure if these 2 policies can fit into a single field. Naming becomes very hard at that point.

**Comment by alculquicondor** [comment]
I don't think the "minimum" interpretation of a backoff limit is ideal. We will certainly have confused users about extra pods being created when there is a control plane upgrade, or kcm simply crashes.

**Comment by ahg-g** [comment]
> I don't think the "minimum" interpretation of a backoff limit is ideal. We will certainly have confused users about extra pods being created when there is a control plane upgrade, or kcm simply crashes.

It is not ideal, but I think it is a solution worth considering given the complexity of tracking the exact number of retries per index. Confusion can be addressed by having the semantics clarified in the name, `MinRetries` for example.
 
btw, does the current BackoffLimit guarantee the exact number of retires? also, when `restartPolicy = "OnFailure"`, does each kubelet restart count against the BackoffLimit?

**Comment by ahg-g** [comment]
> This assumption is now changing. So for this new mode, we might need to limit the maximum value for completions.

A 1 million limit, which is ~10x number of workload pods supported now is equivalent to 122KB max of storage? Should be acceptable, no? 

> In that line, I think a way to solve the main problem of this issue is to introduce an indexCreationPolicy.

Not sure I understand why we need this. Currently we consider an index done and move to the next if it succeeded. If we have BackoffLimit per index, then the policy changes to "if the index succeeds or it reaches its backofflimit", the reset should be the same.

**Comment by alculquicondor** [comment]
> It is not ideal, but I think it is a solution worth considering given the complexity of tracking the exact number of retries per index. Confusion can be addressed by having the semantics clarified in the name, MinRetries for example.

Other than confusion, users might want stronger guarantees, as pods=cost.

> btw, does the current BackoffLimit guarantee the exact number of retires? also, when restartPolicy = "OnFailure", does each kubelet restart count against the BackoffLimit?

I don't think so, as the retries are stored in the status. However, if there is a new pod, then yes, the entire old pod only counts as one failure.

> A 1 million limit, which is ~10x number of workload pods supported now is equivalent to 122KB max of storage? Should be acceptable, no?

We should probably use the same limit that we set for parallelism (10^5). I don't see why we should be inconsistent.

> Not sure I understand why we need this. Currently we consider an index done and move to the next if it succeeded. If we have BackoffLimit per index, then the policy changes to "if the index succeeds or it reaches its backofflimit", the reset should be the same.

I was trying to go with the assumption that we can't implement a backoffLimit per index.

**Comment by jensentanlo** [comment]
Thanks for creating this issue, I missed the notification so apologies for the delay.

I've been thinking about this since our previous discussion and I remember that you mentioned about specifying which container exit codes are considered as failures/successes. Is there a separate issue somewhere with the discussion of that proposal and why that was rejected/deferred? I think that would cover most if not all of the edge cases.

**Comment by alculquicondor** [comment]
That's #17244. We are also still thinking about multiple interpretations for it. Your input will be helpful.

**Comment by isibeni** [comment]
I would vote for a backOffLimit per Index.
Regarding on how we need to treat the failure case:
It might make sense to let the user define some kind of failure policy so the user can decide how the job behaves and in which case we should continue to create pods or should stop completely. We should collect a list of all possible behaviours that we could implement and think about how much sense they make and if we can have one "failure policy" for each of them. 


Regarding the implementation of how to track it on a per index level:

At the KubeCON I was talking to @alculquicondor about possible solutions. 
If we finally have a stable solution for job tracking with finalizers we could do the following:
Just add an annotation on each pod that contains the retries for the current index. Based on that the controller can just determine if we already reached the backofflimit for the index or not. 
I guess in this case it would be beneficial to also the field `.status.failedIndexes` so that we can actually declare an index as failed when it reached the backOffLimit, remove the finalizer from those pods so that the pod can then be cleaned up

**Comment by jensentanlo** [comment]
> I would vote for a backOffLimit per Index. Regarding on how we need to treat the failure case: It might make sense to let the user define some kind of failure policy so the user can decide how the job behaves and in which case we should continue to create pods or should stop completely. We should collect a list of all possible behaviours that we could implement and think about how much sense they make and if we can have one "failure policy" for each of them.
> 
> Regarding the implementation of how to track it on a per index level:
> 
> At the KubeCON I was talking to @alculquicondor about possible solutions. If we finally have a stable solution for job tracking with finalizers we could do the following: Just add an annotation on each pod that contains the retries for the current index. Based on that the controller can just determine if we already reached the backofflimit for the index or not. I guess in this case it would be beneficial to also the field `.status.failedIndexes` so that we can actually declare an index as failed when it reached the backOffLimit, remove the finalizer from those pods so that the pod can then be cleaned up

Back off limit per pod would definitely be useful. I was thinking about customizing failure policy and wrote a bit here: https://github.com/kubernetes/kubernetes/issues/17244#issuecomment-1119688094

Would that cover the failure modes that you’re thinking of?

**Comment by isibeni** [comment]
I was more thinking off what we would need to do when one index reaches it's backOffLimit. We could do the following
* Count this index as failed, but still continue with all the other indexes. So the same behaviour then as if this index would have been completed but we would declare the job overall as failed
* Count the index as failed. Let current pods run to completion and then don't continue to create new pods and declare the job as failed
* Count the index as failed. Let all current indices run to completion (either to success or till they also reached backOffLimit) and then don't continue to create new pods and declare the job as failed
* Count the index as failed. Stop all running workload and declare the job as failed. 
* others?

For me the first scenario sounds like the one we should have. But I was wondering if there are use cases where a user wants to have the other behaviours. If so we would need to make this configurable

**Comment by jensentanlo** [comment]
I agree that the first scenario is preferable as a default and I think that’s what most people expect. The other cases could be covered by the customizable failure codes, as mentioned in the other discussion that I linked.

**Comment by ahg-g** [comment]
> Just add an annotation on each pod that contains the retries for the current index. Based on that the controller can just determine if we already reached the backofflimit for the index or not.

I guess you mean to transfer the retry count for each index to the new pod instance of the index each time it is recreated? that sounds like a reasonable option indeed.

**Comment by ahg-g** [comment]
> I was more thinking off what we would need to do when one index reaches it's backOffLimit. We could do the following
> 
> * Count this index as failed, but still continue with all the other indexes. So the same behaviour then as if this index would have been completed but we would declare the job overall as failed
> * Count the index as failed. Let current pods run to completion and then don't continue to create new pods and declare the job as failed
> * Count the index as failed. Let all current indices run to completion (either to success or till they also reached backOffLimit) and then don't continue to create new pods and declare the job as failed
> * Count the index as failed. Stop all running workload and declare the job as failed.
> * others?

Ultimately it is about finding a use case that each of those modes can support; The first one is indeed the most common: the use case here is that each index represent a separate "job" (processing image frames for example). Not totally sure about the others.

**Comment by isibeni** [comment]
> I guess you mean to transfer the retry count for each index to the new pod instance of the index each time it is recreated? 
Yes.

I guess it get's interesting when the user sets the restartPolicy to `OnFailure`. IIRC the job controller currently also checks if the restartCount of the containers are exceeding the backOffLimit. If we also want to do that here the implementation gets tricky

**Comment by jensentanlo** [comment]
I was just discussing this with @mimowo on the Slack. An additional use case I was thinking of would be running integration tests; we'd certainly expect "failures" but might want several configurations as to how aggressively that we want to terminate the test run, since each test might take a while to run.

Currently we've hand-rolled something using many single (non-indexed) jobs but it doesn't seem very ideal.

**Comment by ahg-g** [comment]
Interesting! just curious, aren't there dedicated frameworks for running tests? any reason why you use a custom setup?

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

We are kind of ready for this in 1.27. Any takers?

**Comment by jensentanlo** [comment]
> Interesting! just curious, aren't there dedicated frameworks for running tests? any reason why you use a custom setup?

Sorry, completely missed this. I agree that there are dedicated frameworks for lots of things, but the idea is that having useful primitives in core Kubernetes would be useful for dedicated frameworks to build on top. I think this is one situation where everyone that is currently building is re-inventing the wheel to solve a common set of problems.

**Comment by anirudhjayakumar** [comment]
Hi, I would like to comment on the use cases here.

If an index reaching its backofflimit can be surfaced at the Job Status level, then I feel just having scenario 1 (Count this index as failed, but still continue with all the other indexes.) is enough for most cases. The user on looking at the status can decide further action including killing the job right away or waiting for X indexes to complete.  But if this cannot be surfaced at the job status level, then having an option to stop all execution right away will be useful as that will be the only way a user know about it. 

I do understand one could list the pods for a given job to figure this out, but that can be very expensive and load etcd and api-server.

**Comment by jensentanlo** [comment]
Now that we have the new PodFailurePolicy feature in 1.26 beta, I think that really meshes nicely with this feature.

Basically we'd have a backoffLimitPerIndex and a new FailIndex action on the pod failure policy. The regular case would be that the index would retry up to the backoff limit and then the index would fail. All of the other indices would run to completion.

If you use the FailIndex action, then that index would fail immediately without retrying and the other indices would run to completion.
If you use the FailJob action, the entire job would fail without retrying and the other indices would get cleaned up.

**Comment by jensentanlo** [comment]
Now in terms of the details of the API itself, I think that a new field like backoffLimitPerIndex would be good. Some sort of way to say, it’s okay for X number of indices to fail before the job fails would also be a good feature, but I’m not sure whether re-using the backoffLimit field for that would be confusing or not. Are there any other examples from the rest of the Kubernetes API that we could draw from? @mimowo

**Comment by jensentanlo** [comment]
> @jensentanlo would you like to draft a KEP? Even if it doesn't make it to 1.27, it would be nice to make progress on a design.
> 
> > I think that a new field like backoffLimitPerIndex would be good.
> 
> Another option would be something like `backoffLimitTarget: Job|Index` within the `podFailurePolicy` object.

I should have some time so I will write it up.

And thank you for the feedback, that's a great suggestion.

**Comment by jensentanlo** [comment]
@alculquicondor I'm currently writing the KEP. What SIG should I put as the sponsoring SIG?

**Comment by alculquicondor** [comment]
Apps

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

This is being tracked in kubernetes/enhancements#3850

/close
