### ISSUE TITLE
Enabling external CCM causes Node.Addresses to flap

### ISSUE THREAD

**Issue by mdbooth** [kubernetes/kubernetes#109793]
### What happened?

I am reproducing this in OpenShift using the OpenStack cloud provider, but nothing here is specific to either OpenShift or OpenStack.

When migrating a cluster which uses in-tree cloud provider to use external cloud-provider, we use the following process:

1. Disable cloud controllers in KCM
2. Deploy CCM
3. Redeploy kubelets with --cloud-provider=external

Between steps 1&2 the node-lifecycle, routes, and service controllers are not running anywhere, but this situation isn't unsafe for the cluster and we can keep it short.

Between steps 2&3 is more interesting. The node controller is running in CCM, and the kubelets are running with --cloud-provider=openstack (or whatever, just not external). The main loop of node-controller will ignore a newly created node because [it won't have the external cloud provider taint](https://github.com/kubernetes/kubernetes/blob/1234d061c0bdc53b41bc7c12881bbaa7af084e55/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L394-L399). However, the [UpdateNodeStatus()](https://github.com/kubernetes/kubernetes/blob/1234d061c0bdc53b41bc7c12881bbaa7af084e55/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L166) loop does not have a similar exclusion.

[Kubelet also manages Node.Addresses](https://github.com/kubernetes/kubernetes/blob/1234d061c0bdc53b41bc7c12881bbaa7af084e55/pkg/kubelet/nodestatus/setters.go#L62-L209). Note that we shortcut if the kubelet is using an external cloud provider, but not if we don't. So between steps 2&3 both kubelet and CCM's node controller are managing Node.Addresses. If the legacy cloud provider and external CCM don't return the same list of NodeAddresses this causes flapping.

Running OpenShift on OpenStack we have 2 problems. Firstly, our legacy cloud provider and external CCM produce different lists. We don't think this would be a problem in practise, except for the second problem.

Kubelet adds the `alpha.kubernetes.io/provided-node-ip` annotation to the node containing the node IP. This allows the CCM node controller to apply the same filtering based on node IP as kubelet does for the legacy cloud provider. This means that, although the lists are different, the node IP is still listed first which is the only thing that matters in practise.

The problem is that kubelet only adds the `alpha.kubernetes.io/provided-node-ip` annotation when --cloud-provider=external which, between steps 2&3, it is not. This means that Node.Addresses flaps between a correct and a broken configuration, as the NodeAddresses returned by the external CCM cannot be filtered by node IP without the annotation.

The ideal solution here would be to ensure that only 1 controller is managing Node.Addresses during this period in the same way we do for Node creation with the external CCM taint. This would fix the issue entirely.

A fix with a much smaller scope would be to have kubelet add the node IP annotation unconditionally so, although Node.Address can potentially flap, it will at least be between 2 valid configurations. Given that this should only ever be a problem during the upgrade window, the smaller fix may be more expedient.

### What did you expect to happen?

Node.Addresses should remain valid at all times when kubelet is configured with --cloud-provider=openstack but the CCM is also running.

### How can we reproduce it (as minimally and precisely as possible)?

Good luck 😂

### Kubernetes version

1.24

### Cloud provider

OpenStack (but as described, not OpenStack-specific)

**Comment by elmiko** [comment]
we've added an agenda item for next week's (11 May) SIG cloud provider meeting

**Comment by danwinship** [comment]
> When migrating a cluster which uses in-tree cloud provider to use external cloud-provider, we use the following process:
> 
>     1. Disable cloud controllers in KCM
> 
>     2. Deploy CCM
> 
>     3. Redeploy kubelets with --cloud-provider=external

Would it work to swap steps 2 and 3?

**Comment by mdbooth** [comment]
> > When migrating a cluster which uses in-tree cloud provider to use external cloud-provider, we use the following process:
> > 
> > 1. Disable cloud controllers in KCM
> > 2. Deploy CCM
> > 3. Redeploy kubelets with --cloud-provider=external
> 
> Would it work to swap steps 2 and 3?

Good question. I don't think so.

That would leave us without the Node, Node lifecycle, and Service controllers until all kubelets were updated. This would mean:

* No cluster scale-up or scale-down
* No creation, deletion, or modification to LB Services

I think we could handle this in OpenShift, although it's a bit fragile and I suspect updating all the kubelets can take a really long time on a big cluster.

However, I think this would break cluster-api or any deployment tooling which rolls out updates by creating new machines. I think this would never complete: the new nodes would never come up because the node controller isn't running.

**Comment by dchen1107** [comment]
I am still trying to understand the issues here while reviewing your pr: https://github.com/kubernetes/kubernetes/pull/109794, but I agreed with your comments above:

>That would leave us without the Node, Node lifecycle, and Service controllers until all kubelets were updated. This would > > mean:

> No cluster scale-up or scale-down
> No creation, deletion, or modification to LB Services
