### ISSUE TITLE
reset deleted_kinds strictRemovedHandlingInAlpha to false after beta

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#109799]
### What happened?

once the we hit a beta release, we can reset the default value for strict handling to false to prep for 1.25. It will likely be introduced in https://github.com/kubernetes/kubernetes/pull/108797

/kind bug
/priority important-soon
/milestone v1.25
https://github.com/orgs/kubernetes/teams/sig-api-machinery-bugs

### What did you expect to happen?

ignore

### How can we reproduce it (as minimally and precisely as possible)?

template

### Kubernetes version

this

### Cloud provider

time

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by justin-chizer** [comment]
Hello @deads2k, my name is Justin Chizer and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Is this still on track for 1.25?

**Comment by liggitt** [comment]
This needs to be done now that master is on 1.26 until 1.25.0 is cut, since verify jobs are failing on removal of 1.26 deprecated APIs 

/priority critical-urgent
