### ISSUE TITLE
kubeadm config print can get default  kubeadm config,  but if use   binary install, i need to get every parameter meaning

### ISSUE THREAD

**Issue by zerols** [kubernetes/kubernetes#109765]
Is there a similar parameter that I can quickly get to a default  kube-api or con-manager systemd configuration file ?

**Comment by neolit123** [comment]
Just google kubeadm config.
https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-config/
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags

Also see https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support
