### ISSUE TITLE
scheduled Pods in Kubernetes scheduler's internal cache don't have PodScheduled condition until they are next updated

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#109894]
### What happened?

Some Pods in Kubernetes scheduler's internal cache don't have `PodScheduled` condition in their status.

We store scheduled pods information into cache as assumedPod before binding Pod.
https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/scheduler/schedule_one.go#L741
https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/scheduler/internal/cache/cache.go#L384

And, just after binding Pod, we receive `Add` event for scheduled Pods from eventhandler and `sched.addPodToCache` will be used to add Pod to cache.
https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/scheduler/eventhandlers.go#L276

But, as described above, we've added store scheduled pods information. So, basically, scheduler doesn't update pod in cache here:
https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/scheduler/internal/cache/cache.go#L503-L514

But, `Add` event contains changes not only of `.spec.NodeName` but also of `.status.Condition`. So, we should update cache to keep `.status.Condition` up-to-date when we receive `Add` event for scheduled Pods from eventhandler.
Otherwise, `.status.Condition` won't updated until new changes for that Pod are made.

### What did you expect to happen?

Kubernetes scheduler's internal cache always keeps Pod's`.status.Condition` up-to-date.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create some Node.
2. Create a Pod.
3. Pod is scheduled by scheduler.
4. Check `.status.Condition` in Pods in Kubernetes scheduler's internal cache (by adding debug log or [dump](https://github.com/kubernetes/kubernetes/blob/7af5a7bfc51d0455d8b2322ae9e72ed66fb1b8f9/pkg/scheduler/internal/cache/cache.go#L176) cache)

I think kubelet will update Pods status after they run containers, so you need to do (4) before kubelet does so. (Or doesn't use kubelet like e2e tests)

### Anything else we need to know?

/assign

Let me double-check this. (The above explanation includes my expectations, so may not be entirely correct.)

### Kubernetes version

v1.23.4

But, I guess this bug exists on latest master as well.

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
Does this lead to unschedulable pods or is this just for debugging purposes?

**Comment by sanposhiho** [comment]
We uses `PodScheduled` condition in a custom plugin.

> Does this lead to unschedulable pods

_Mostly_ No in the real cluster. Only for a very short time (from the scheduler schedules a Pod to kubelet next updates a pod) our plugin does not behave as expected and may make some pods unschedulable.

But, when it comes to e2e testing, this bug can be troublesome.
In our e2e testing, we don't run kubelet, and no one updates Pods after the scheduler scheduled them
Then, all scheduled Pods in the scheduler cache have non-updated `PodScheduled` condition and it results in unexpected results from our plugin.
