### ISSUE TITLE
Flaky TestNamespaceAuthorization integration test 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#109847]
### Which jobs are flaking?

pull-kubernetes-integration

### Which tests are flaking?

TestNamespaceAuthorization

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestNamespaceAuthorization

### Reason for failure (if possible)

```
panic: test timed out after 10m0s
```

### Relevant SIG(s)

/sig

**Comment by aojea** [comment]
> https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestNamespaceAuthorization

one advice, looking for flakes based on only that URL is prone to errors.

You should correlate different sources, in this case the presubmit and the periodic job. Presubmit failures may be legit depending on the PR, these days are different PRs touching the integration framework that will show up there creating noise.

Other thing is that the test should be "red" in the graph, blank is that the result was not obtained AFAIK

Just compare this report with:

https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5

and 

https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=integration

**Comment by ritazh** [comment]
/close

Looks like https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=TestNamespaceAuthorization has been green for awhile. Feel free to reopen if you see consistent failures.
