### ISSUE TITLE
--cpuset-cpus supported in kubernetes?

### ISSUE THREAD

**Issue by satyajitpadhyewit** [kubernetes/kubernetes#10983]
I want to know if --cpuset-cpus in supported in kubernetes so that we can launch containers with that property. Initiated at #10570  but I am not finding enough resources if it can.

**Comment by erictune** [comment]
It is not supported.

How would you plan to use --cpuset-cpus?  I can think of many reasons, but I'd like to hear yours.

**Comment by satyajitpadhyewit** [comment]
Basically I want to run container on specific cpu cores. I am trying to run some real time applications on the container and since they are latency sensitive, I am trying to avail the lowest latency.  I tried using taskset but am sure it doesn't work completely. Any advice or solution.

**Comment by erictune** [comment]
For running apps on Kubernetes, I suggest you do set an appropriate cpu limit on the container.  This affects the shares for the container which can affect latency when using CFS.

If you suspect latency could be even lower, using taskset as you did to experiment is a good approach.  Doing taskset on all the processes in the container is the same as putting --cpuset-cpus on their container.     It would not make a difference if --cpuset-cpus was supported.

**Comment by satyajitpadhyewit** [comment]
I did believe the same fact as you have stated that using taskset on all processes can be done in this case. But if cpuset is supported you just dont have to use taskset again and again.

**Comment by erictune** [comment]
Have you found a measurable difference between taskset and no taskset?

**Comment by bgrant0607** [comment]
cc @vishh
