### ISSUE TITLE
When a Pod is configured with startupProbe but without readinessProbe, the Pod will take extra time to be ready 

### ISSUE THREAD

**Issue by RedrumSherlock** [kubernetes/kubernetes#109802]
### What happened?

When I configured a Pod with startupProbe but without a readinessProbe, the pod will take extra time (40-60 seconds) to be ready.
For example, if the startupProbe is configured as below, and readinessProbe is not configured at all

```
startupProbe:
  exec:
    command:
    - echo
    - started
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
```

Then the pod will be ready after around 20 seconds as expected, but will take extra seconds to be ready as shown below:

```
NAME                                  READY   STATUS              RESTARTS   AGE
test-pod-1-7b7cdfcf66-j4jtx           0/1     ContainerCreating   0          0s
test-pod-1-7b7cdfcf66-j4jtx           0/1     ContainerCreating   0          1s
test-pod-1-7b7cdfcf66-j4jtx           0/1     Running             0          2s
test-pod-1-7b7cdfcf66-j4jtx           0/1     Running             0          26s
test-pod-1-7b7cdfcf66-j4jtx           1/1     Running             0          64s
```

### What did you expect to happen?

The pod should be ready immediately or with a extremely short delay after the startupProbe has succeeded since there is not a readinessProbe defined, e.g. like a made up time sequence below.

```
NAME                                  READY   STATUS              RESTARTS   AGE
test-pod-1-7b7cdfcf66-j4jtx           0/1     ContainerCreating   0          0s
test-pod-1-7b7cdfcf66-j4jtx           0/1     ContainerCreating   0          1s
test-pod-1-7b7cdfcf66-j4jtx           0/1     Running             0          2s
test-pod-1-7b7cdfcf66-j4jtx           0/1     Running             0          26s
test-pod-1-7b7cdfcf66-j4jtx           1/1     Running             0          27s
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a deployment with the following startupProbe configuration, but without a readinessProbe configuration
```
startupProbe:
  exec:
    command:
    - echo
    - started
  failureThreshold: 3
  initialDelaySeconds: 20
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 1
```
2. Watch the pod status and age with command `kubectl get pods -w`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-gke.3600", GitCommit:"750002971a60d8a06e0a403c52724257f0f68481", GitTreeState:"clean", BuildDate:"2022-03-10T09:32:23Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Google Kubernetes Engine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yxxhero** [comment]
@RedrumSherlock Please try to upgrade your k8s version. Thanks very much. 
Do you need to make sure that your app will succeed in 20 seconds.

**Comment by wzshiming** [comment]
Maybe you can remove `initialDelaySeconds` of `startupProbe`

**Comment by RedrumSherlock** [comment]
With more testing it turns out the issue is only in k8s version 1.20 or lower. After I upgraded the control plan and node version to 1.21.6-gke.1503, the issue is gone. I will close this issue now.
