### ISSUE TITLE
Flaky unit test: TestClientReceivedGOAWAY

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#109889]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestClientReceivedGOAWAY

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&include-filter-by-regex=TestClientReceivedGOAWAY

### Reason for failure (if possible)

```
=== FAIL: vendor/k8s.io/apiserver/pkg/server/filters TestClientReceivedGOAWAY/got_2_GOAWAY_after_set-up_watch (0.11s)
    goaway_test.go:357: expect TCP connection: 3, actual: 2
    --- FAIL: TestClientReceivedGOAWAY/got_2_GOAWAY_after_set-up_watch (0.11s)
=== FAIL: vendor/k8s.io/apiserver/pkg/server/filters TestClientReceivedGOAWAY (15.59s)
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109832/pull-kubernetes-unit/1523166127293730816

### Relevant SIG(s)

/sig api-machinery
?

**Comment by aojea** [comment]
It doesn't look too flaky to me 
https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestClientReceivedGOAWAY

let''s keep an eye on it though

**Comment by fedebongio** [comment]
Agree with @aojea but thank you for raising.
Triaging for now, keeping it open.
/triage accepted

**Comment by aojea** [comment]
no failures recently https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit&include-filter-by-regex=TestClientReceivedGOAWAY&width=5
