### ISSUE TITLE
[sched-perf] PreemptionBasic/5000Nodes and PreemptionPVs/5000Nodes failures

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#109881]
### Which jobs are failing?

ci-benchmark-scheduler-perf-master

### Which tests are failing?

- BenchmarkPerfScheduling/PreemptionBasic/5000Nodes
- BenchmarkPerfScheduling/PreemptionPVs/5000Nodes

### Since when has it been failing?

Unclear. It seems to be failing for a while, consistently.

### Testgrid link

https://testgrid.k8s.io/sig-scalability-benchmarks#scheduler-perf

### Reason for failure (if possible)

The 2 tests failed on waiting for pods to be scheduled, timed out after 30 mins, which is supposed to be adequate.

However during debugging, I spot that the low-prority pod's `0` terminationGracePeriodSeconds is not really honored - when the low-priority pod gets preempted, it's expected to be deleted immediately.

https://github.com/kubernetes/kubernetes/blob/f7ad09c447f0fa13338ba3355fb245f6879fc60d/test/integration/scheduler_perf/config/pod-low-priority.yaml#L6

However, it's not the case in the integration test, which then in a 5k-node test, causes unnecessary churning among the high-priority pods.priority

### Anything else we need to know?

The 2 tests are technically valid. The test consists of the following steps:

- construct 5k nodes, each with 4 cpus, so in total 20k cpus
- create 20k low-priority pods, each requests 0.9 cpus, so in total 18k cpus
- wait for the 20k pods to be running
- create 5k high-priority pods, each requests 3 cpus, so in total 15k cpus
- wait for the 5k high-priority pods to be scheduled by preempting low-priority pods

### Relevant SIG(s)

/sig scheduling

**Comment by sanposhiho** [comment]
I did some investigation before on https://github.com/kubernetes/kubernetes/issues/108308


> the low-prority pod's 0 terminationGracePeriodSeconds is not really honored 

I was not aware of this. 
will do some additional investigation..
