### ISSUE TITLE
Add network packet stats in kubelet Summary API

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kubernetes#109837]
### What would you like to be added?

Expose network packet stats in kubelet Summary API:

- RxPackets: Cumulative count of packets received
- RxDropped: Cumulative count of packets dropped while receiving
- TxPackets:  Cumulative count of packets transmitted
- TxDropped: Cumulative count of packets dropped while transmitting

### Why is this needed?

Packet related metrics are important to monitor network.

### Plan
- [ ] Add packet stats in Summary API
- [ ] Expose packet stats using cAdvisor
- [ ] Expose packet stats using CRI (containerd)

**Comment by dashpole** [comment]
I think this use-case might be met by https://github.com/kubernetes/kubernetes/pull/109398.
