### ISSUE TITLE
kubeadm-config.yaml    certSANs

### ISSUE THREAD

**Issue by cmengs** [kubernetes/kubernetes#109887]
### What would you like to be added?

I don't understand what that means

### Why is this needed?

If I have two hosts now and add them later, can I also copy the certificate to other hosts through master1 and then execute kubeadm join to join the cluster?

**Comment by neolit123** [comment]
Kubeadm certsSANS for e.g. kube-apiserver means that its serving certificate will include additional IPs and domain names in the SAN. You can then move this serving cert to another machine and it will work if its in the SAN. You can google on how serving certs work.

/kind support
/close
For more questions please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
