### ISSUE TITLE
faild to start kubelet

### ISSUE THREAD

**Issue by yll92587** [kubernetes/kubernetes#109817]
May 05 17:01:38 master-01 kubelet[127119]: I0505 17:01:38.612023  127119 kuberuntime_manager.go:222] "Container runtime initialized" containerRuntime="docker" version="20.10.14" apiVersion="1.41.0"
May 05 17:01:44 master-01 kubelet[127119]: E0505 17:01:44.749930  127119 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
May 05 17:01:44 master-01 kubelet[127119]: For verbose messaging see aws.Config.CredentialsChainVerboseErrors
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.750147  127119 volume_host.go:75] "KubeClient is nil. Skip initialization of CSIDriverLister"
May 05 17:01:44 master-01 kubelet[127119]: W0505 17:01:44.750398  127119 csi_plugin.go:189] kubernetes.io/csi: kubeclient not set, assuming standalone kubelet
May 05 17:01:44 master-01 kubelet[127119]: W0505 17:01:44.750412  127119 csi_plugin.go:262] Skipping CSINode initialization, kubelet running in standalone mode
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.750508  127119 server.go:1190] "Started kubelet"
May 05 17:01:44 master-01 kubelet[127119]: E0505 17:01:44.750737  127119 kubelet.go:1306] "Image garbage collection failed once. Stats initialization may not have completed yet" err="failed to get imageFs info: unable to find data in memory cache"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.750780  127119 kubelet.go:1414] "No API server defined - no node status update will be sent"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.752229  127119 server.go:176] "Starting to listen read-only" address="0.0.0.0" port=10255
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.752405  127119 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.753577  127119 server.go:149] "Starting to listen" address="0.0.0.0" port=10250
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.754084  127119 volume_manager.go:279] "Starting Kubelet Volume Manager"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.754162  127119 desired_state_of_world_populator.go:141] "Desired state populator starts to run"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.754497  127119 server.go:409] "Adding debug handlers to kubelet server"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.769260  127119 client.go:86] parsed scheme: "unix"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.769281  127119 client.go:86] scheme "unix" not registered, fallback to default scheme
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.769344  127119 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.769353  127119 clientconn.go:948] ClientConn switching balancer to "pick_first"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.796918  127119 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv4
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.829384  127119 kubelet_network_linux.go:56] "Initialized protocol iptables rules." protocol=IPv6
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.829419  127119 status_manager.go:153] "Kubernetes client is nil, not starting status manager"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.829428  127119 kubelet.go:1846] "Starting kubelet main sync loop"
May 05 17:01:44 master-01 kubelet[127119]: E0505 17:01:44.829469  127119 kubelet.go:1870] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
May 05 17:01:44 master-01 kubelet[127119]: E0505 17:01:44.929816  127119 kubelet.go:1870] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.954386  127119 reconciler.go:157] "Reconciler: start to sync state"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976285  127119 cpu_manager.go:199] "Starting CPU manager" policy="none"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976311  127119 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976332  127119 state_mem.go:36] "Initialized new in-memory state store"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976522  127119 state_mem.go:88] "Updated default CPUSet" cpuSet=""
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976536  127119 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976562  127119 policy_none.go:44] "None policy: Start"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.977737  127119 manager.go:602] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.978053  127119 plugin_manager.go:114] "Starting Kubelet Plugin Manager"

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2022-05-05 17:01:38 CST; 20min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 127119 (kubelet)
    Tasks: 17
   Memory: 52.4M
   CGroup: /system.slice/kubelet.service
           └─127119 /usr/local/bin/kubelet

May 05 17:01:44 master-01 kubelet[127119]: E0505 17:01:44.929816  127119 kubelet.go:1870] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.954386  127119 reconciler.go:157] "Reconciler: start to sync state"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976285  127119 cpu_manager.go:199] "Starting CPU manager" policy="none"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976311  127119 cpu_manager.go:200] "Reconciling" reconcilePeriod="10s"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976332  127119 state_mem.go:36] "Initialized new in-memory state store"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976522  127119 state_mem.go:88] "Updated default CPUSet" cpuSet=""
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976536  127119 state_mem.go:96] "Updated CPUSet assignments" assignments=map[]
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.976562  127119 policy_none.go:44] "None policy: Start"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.977737  127119 manager.go:602] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
May 05 17:01:44 master-01 kubelet[127119]: I0505 17:01:44.978053  127119 plugin_manager.go:114] "Starting Kubelet Plugin Manager"

**Comment by pacoxu** [comment]
/kind support
(as there is no enough data to prove this is a bug of kubelet.)

**Comment by sftim** [comment]
/triage needs-information
too, I think
