### ISSUE TITLE
 How does efk integrate with LDAP in k8s

### ISSUE THREAD

**Issue by SirBlues** [kubernetes/kubernetes#109878]
### What happened?

How does efk integrate with LDAP in k8s
efk在k8s里怎么和ldap集成

### What did you expect to happen?

Efk login with LDAP user
efk用ldap用户登录

### How can we reproduce it (as minimally and precisely as possible)?

Efk login with LDAP user

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

tencent

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/close
Please try asking in support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
