### ISSUE TITLE
Is there a way to prevent a CustomResource from being deleted if it is still needed

### ISSUE THREAD

**Issue by jnpr-pranav** [kubernetes/kubernetes#109801]
I have a custom resource `Foo` which is automatically created by a controller whenever there are events from a kubernetes resource `Bar`.

`Foo`'s deletion should be allowed only when `Bar` is deleted. It should be possible to add watches in the controller and re-create `Foo` in case it was deleted accidentally, but is it possible to stop that resource from being deleted at all?

I've read some other discussions on a similar topic that suggested RBAC, but is there another way to prevent deletion? Can we use finalizers in some way to achieve this?

**Comment by pacoxu** [comment]
Blog about it is in https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/

For support request, go to https://discuss.kubernetes.io/.

**Comment by neolit123** [comment]
/close
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
