### ISSUE TITLE
Add Tracing to the kubelet's read-only endpoint

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#109829]
### What would you like to be added?

Follow-up to https://github.com/kubernetes/kubernetes/pull/105126.  Discussed in https://github.com/kubernetes/kubernetes/pull/105126#discussion_r783142176.

As part of kubelet tracing beta, we should add tracing support to the kubelet's read-only endpoint, which currently does not have tracing.  It should use WithPublicEndpoint to prevent callers from influencing sampling decisions.

### Why is this needed?

Part of https://github.com/kubernetes/enhancements/issues/2831

**Comment by glhl86** [comment]
@dashpole  can i help you with this issue?

**Comment by dashpole** [comment]
I don't think we'll be able to start with this until https://github.com/kubernetes/kubernetes/pull/105126 merges

**Comment by glhl86** [comment]
> I don't think we'll be able to start with this until #105126 merges

Ok, I'm waiting to see if I can help you. Thank you

**Comment by dashpole** [comment]
/remove-lifecycle stale

https://github.com/kubernetes/kubernetes/pull/105126 is merged now, so this can be worked on.

**Comment by fatsheep9146** [comment]
Could I help with this issue?  @dashpole

**Comment by frzifus** [comment]
I gave the whole thing another try.  At least locally, the dependencies seem now to be able to be updated. :raccoon: 

Could you maybe have a look at it @dashpole? :)

**Comment by logicalhan** [comment]
> Could you maybe have a look at it @dashpole? :)

He's on leave for the time being.

**Comment by frzifus** [comment]
oh, can you provide some feedback or point me to the right people?

**Comment by dashpole** [comment]
I'm back now.  Feel free to assign me to PRs related to this, and I'll review

**Comment by frzifus** [comment]
Welcome back :) Could you re-run the CI [here](https://github.com/kubernetes/kubernetes/pull/117945)? Its just the dependencies. The PR itself shouldn't be that much afterwards.

**Comment by frzifus** [comment]
otel is now up-to-date enough.
- here: https://github.com/kubernetes/kubernetes/pull/121111

**Comment by KubeKyrie** [comment]
@dashpole Hi, I would like to ask about one trouble that caused by WithPublicEndpoint.
Aggregated APIServer that I customized uses kubernetes's RecommendedConfig. Due to the fact that WithPublicEndpoint is enabled, it can't be tracked by the full trace for its span-link model. And I think child-parent span model is more appropriate.

So, could you please give me some advice? Looking forward to your reply.

**Comment by dashpole** [comment]
@KubeKyrie thanks.  We know about this, and are tracking it in https://github.com/kubernetes/kubernetes/issues/103186
