### ISSUE TITLE
when upgrade iptables from 1.4.21 to v1.8.6 (nf_tables), rules in iptables-legacy is not clear.

### ISSUE THREAD

**Issue by lojies** [kubernetes/kubernetes#109811]
### What happened?

The iptables is  upgraded from 1.4.21 to v1.8.6 (nf_tables)  when os is upgraded.
I have followed the document in [https://github.com/kubernetes-sigs/iptables-wrappers](url) and added iptables-wrappers in kube-proxy pod.
But rules in iptables-legacy is not clear. If some pods were rebuild, then the KUBE-SERVICE chain left in iptables-legacy would traffic to the wrong pod ip before rebuilding.Rules in nftables will not effect.
And when you visit a service, it will report no route to host.

### What did you expect to happen?

After upgrading, service can be visited normal.

### How can we reproduce it (as minimally and precisely as possible)?

1. Upgrade iptables from 1.4.21 to v1.8.6 (nf_tables)
2. Add iptables-wrappers in kube-proxy pod
3. Rebulid some pods of service(one endpoint best)
4. Check if rules lefing in iptables-legacy
5. Check if visiting these sevice can lead "no route to host" error

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.22.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dcbw** [comment]
@lojies did you upgrade iptables while the system was running?

If so, I think the result would be expected. I'm not sure anything clears out legacy iptables as part of the upgrade since that is quite risky. Best thing to do is to either clear it yourself or reboot the node.

In any case, I don't think this is an issue that Kubernetes can solve, it's more about how the system/package upgrade is done.

/close
