### ISSUE TITLE
Support for "pooled" image puller

### ISSUE THREAD

**Issue by stackbaek** [kubernetes/kubernetes#109956]
### What would you like to be added?

Is there a way to tune the number of concurrent images being pulled by kubelet?

### Why is this needed?

We want to turn off `SerializeImagePulls`, since one bad image pull on our nodes kept all subsequent deployments to be stuck at `ImagePull` state. So, we're considering turning off `SerializeImagePulls` for our kubelets. However, I am worried that any bad manifests could cause too many image pulls concurrently (and potentially DDoS ourselves).

**Comment by Random-Liu** [comment]
@Random-Liu @dchen1107 

This is a reasonable request to me, and a good tradeoff for now.

**Comment by Random-Liu** [comment]
Chatted with @stackbaek offline, we might be able to use the throttled image puller for this case, and will investigate that first.
