### ISSUE TITLE
v1.24.0 kubeadm init --image-repository not works for k8s.gcr.io/pause:3.1

### ISSUE THREAD

**Issue by cookeem** [kubernetes/kubernetes#109960]
### What happened?

Run below command to init a v1.24.0 cluster:

`kubeadm init --kubernetes-version v1.24.0 --image-repository registry.local/gcr --pod-network-cidr 173.169.0.0/16 --cri-socket /run/cri-dockerd.sock`

I have already set --image-repository, but cluster initial stuck at this log:
```
dockerd[51125]: time="2022-05-11T15:59:13.042319315+08:00" level=warning msg="Error getting v2 registry: Get \"https://k8s.gcr.io/v2/\": dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:42422->[::1]:53: read: connection refused"
dockerd[51125]: time="2022-05-11T15:59:13.042388200+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://k8s.gcr.io/v2/\": dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:42422->[::1]:53: read: connection refused"
dockerd[51125]: time="2022-05-11T15:59:13.043778900+08:00" level=error msg="Handler for POST /v1.40/images/create returned error: Get \"https://k8s.gcr.io/v2/\": dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:42422->[::1]:53: read: connection refused"
kubelet[53545]: E0511 15:59:13.044415   53545 remote_runtime.go:212] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed pulling image \"k8s.gcr.io/pause:3.1\": Error response from daemon: Get \"https://k8s.gcr.io/v2/\": dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:42422->[::1]:53: read: connection refused"
```

this image `k8s.gcr.io/pause:3.1` image-repository settings not correct.

### What did you expect to happen?

image `k8s.gcr.io/pause:3.1` should be `registry.local/gcr/pause:3.1`

and `kubeadm config images list` command should show  k8s.gcr.io/pause:3.1

```
kubeadm config images list --kubernetes-version v1.24.0
k8s.gcr.io/kube-apiserver:v1.24.0
k8s.gcr.io/kube-controller-manager:v1.24.0
k8s.gcr.io/kube-scheduler:v1.24.0
k8s.gcr.io/kube-proxy:v1.24.0
k8s.gcr.io/pause:3.7
k8s.gcr.io/etcd:3.5.3-0
k8s.gcr.io/coredns/coredns:v1.8.6
```

### How can we reproduce it (as minimally and precisely as possible)?

run command kubeadm init with --image-repository parameter, and install machine without internet connection

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:44:24Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### OS version

cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

### Install tools

kubeadm

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
Check the container runtime config.  k8s.gcr.io/pause:3.1 is probably coming from there. Kubeadm uses 3.7, but the container runtime has separate version.

/kind support
/close

**Comment by neolit123** [comment]
See https://github.com/kubernetes/website/issues/33613 as well
