### ISSUE TITLE
Nodes flapping (NotReady/Ready)

### ISSUE THREAD

**Issue by nagpalnitin0110** [kubernetes/kubernetes#109965]
### What happened?

Nodes are flapping with error PLEG is not healthy: PLEG was last seen active 3m.6314604s ago, threshold is 3m0s  This issue is coming only in 2 nodes out of 18 nodes

### What did you expect to happen?

Node to be in Ready State 

### How can we reproduce it (as minimally and precisely as possible)?

We just upgraded from k8s 1.18.0 to 1.19.0 and then 1.20.14

### Kubernetes version

<details>

```console
$ kubectl version
1.20.14
```

</details>

### Cloud provider

On-Prem

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
RHEL 8.5 Ootpa

### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

Containerd:- 1.4.4
Runc:- 1.0.0.rc93

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by endocrimes** [comment]
@nagpalnitin0110 Kubernetes 1.20 is out of support and a lot of pod lifecycle changes have happened in the meantime - Can you see if this is reproducible after updating to 1.24?

thanks!

/triage needs-information
