### ISSUE TITLE
Kubelet should prevent failed volume mounts from resulting in containers writing to host filesystem

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#109955]
### What happened?

A PVC failed and the FS became unmounted. A container restarted and the replacement container ended up mounting the mountpoint directory from the host filesystem and continuing to operate without realizing it.

### What did you expect to happen?

In a perfect world, the replacement container would entirely fail to restart, and the pod might even be killed, but that's not something trivial for kubernetes to solve. However, it is at least very possible for kubernetes to prevent this leading to data loss by setting `chattr +i` on the underlying mountpoint to make it immutable and `chmod 0` to make it so that listing the directory fails for non-root users in the container.

### How can we reproduce it (as minimally and precisely as possible)?

You can potentially reproduce this by force-detaching a PVC from an XFS EBS volume, waiting for it to become unmounted, and then restarting a container in the pod, but I don't think anyone should waste time reproducing this end-to-end since there's a clear fix for any scenario. You can instead manually unmount the source path that containers bind mount for PVCs and then restart a container in a pod using that PVC, applications on that container will then write to the host filesystem instead of the PVC.

### Anything else we need to know?

I'm guessing this might be challenging to fully implement in kubelet itself because volume plugins don't necessarily need to mount anything at all, they can do something simple like extracting a `.tar.gz` file at the path that kubelet tells them to mount something at.

However, for something like a PVC, subpath mounts, etc kubelet layers a bunch of bind mounts on top of each other and the underlying mountpoints for all of those could be made immutable in case one of the intermediate mounts breaks, and device plugins could set mountpoints as immutable on their end if they want to.

If it is too hairy to do this in kubelet, then kubelet could at least enable volume plugins to set their mountpoints as immutable when they know that they are going to actually mount a filesystem over them. Kubelet would just need to be updated to set `chattr -i` on the mountpoint before calling rmdir on it so that it doesn't get blocked by the immutability.

### Kubernetes version

1.21

### Cloud provider

AWS

### OS version

CentOS 8 Stream

### Install tools

in-house

### Container runtime (CRI) and version (if applicable)

docker 19.03.15

### Related plugins (CNI, CSI, ...) and versions (if applicable)

We use both the in-tree EBS plugin and the

**Comment by yydzhou** [comment]
Any update on this? 
We are using k8s v1.22.13 and hit same problem as well
Logs from kubelet
`
"2673b9c2-b342-4c5d-ac6a-535c1d56c565")
Sep 19 14:01:06 n62-108-72 kubelet[3178]: I0919 14:01:06.533476    3178 reconciler.go:269] "operationExecutor.MountVolume started for volume \"pvc-785e53f4-e72e-4326-9e70-e8e881fad471\" (UniqueName: \"kubernetes.io/csi/gitops-platform-storage.rbd.csi.ceph.com^0001-0017-gitops-platform-storage-0000000000000002-8fd1b32e-2d6b-11ed-a7f2-8edb5385608d\") pod \"media-server-iad-2-7ccfdb87d4-msf82\" (UID: \"2673b9c2-b342-4c5d-ac6a-535c1d56c565\") "
Sep 19 14:01:06 n62-108-72 kubelet[3178]: I0919 14:01:06.533648    3178 operation_generator.go:575] MountVolume.WaitForAttach entering for volume "pvc-785e53f4-e72e-4326-9e70-e8e881fad471" (UniqueName: "kubernetes.io/csi/gitops-platform-storage.rbd.csi.ceph.com^0001-0017-gitops-platform-storage-0000000000000002-8fd1b32e-2d6b-11ed-a7f2-8edb5385608d") pod "media-server-iad-2-7ccfdb87d4-msf82" (UID: "2673b9c2-b342-4c5d-ac6a-535c1d56c565") DevicePath "csi-4a37d03cc917dda01e5ef792633d342e9e9af4bf319eb27ec96c3c010b74ae9e"
Sep 19 14:01:06 n62-108-72 kubelet[3178]: I0919 14:01:06.535202    3178 operation_generator.go:585] MountVolume.WaitForAttach succeeded for volume "pvc-785e53f4-e72e-4326-9e70-e8e881fad471" (UniqueName: "kubernetes.io/csi/gitops-platform-storage.rbd.csi.ceph.com^0001-0017-gitops-platform-storage-0000000000000002-8fd1b32e-2d6b-11ed-a7f2-8edb5385608d") pod "media-server-iad-2-7ccfdb87d4-msf82" (UID: "2673b9c2-b342-4c5d-ac6a-535c1d56c565") DevicePath "csi-4a37d03cc917dda01e5ef792633d342e9e9af4bf319eb27ec96c3c010b74ae9e"
Sep 19 14:01:07 n62-108-72 kubelet[3178]: I0919 14:01:07.778088    3178 operation_generator.go:698] MountVolume.SetUp succeeded for volume "pvc-785e53f4-e72e-4326-9e70-e8e881fad471" (UniqueName: "kubernetes.io/csi/gitops-platform-storage.rbd.csi.ceph.com^0001-0017-gitops-platform-storage-0000000000000002-8fd1b32e-2d6b-11ed-a7f2-8edb5385608d") pod "media-server-iad-2-7ccfdb87d4-msf82" (UID: "2673b9c2-b342-4c5d-ac6a-535c1d56c565")
`

logs from csi-cephrbdplugin

`
E0920 13:45:28.976183    7774 utils.go:200] ID: 48926 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:46:30.976290    7774 utils.go:200] ID: 48929 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:48:09.175788    7774 utils.go:200] ID: 48932 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:49:36.976226    7774 utils.go:200] ID: 48936 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:51:32.976770    7774 utils.go:200] ID: 48940 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:53:06.676230    7774 utils.go:200] ID: 48943 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:54:38.276224    7774 utils.go:200] ID: 48947 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:56:01.575744    7774 utils.go:200] ID: 48950 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:57:13.576719    7774 utils.go:200] ID: 48953 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:58:36.576624    7774 utils.go:200] ID: 48957 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 13:59:38.275800    7774 utils.go:200] ID: 48960 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:00:51.275788    7774 utils.go:200] ID: 48963 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:02:16.576205    7774 utils.go:200] ID: 48966 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:04:06.076270    7774 utils.go:200] ID: 48970 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:05:43.776246    7774 utils.go:200] ID: 48974 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:06:55.175790    7774 utils.go:200] ID: 48977 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:08:35.676162    7774 utils.go:200] ID: 48981 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:10:30.476169    7774 utils.go:200] ID: 48985 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:11:45.676396    7774 utils.go:200] ID: 48988 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:13:42.275797    7774 utils.go:200] ID: 48992 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:15:12.876167    7774 utils.go:200] ID: 48995 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:16:51.476313    7774 utils.go:200] ID: 48999 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:18:39.775919    7774 utils.go:200] ID: 49003 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
E0920 14:20:28.476692    7774 utils.go:200] ID: 49007 GRPC error: rpc error: code = InvalidArgument desc = targetpath /var/lib/kubelet/pods/2673b9c2-b342-4c5d-ac6a-535c1d56c565/volumes/kubernetes.io~csi/pvc-785e53f4-e72e-4326-9e70-e8e881fad471/mount is not mounted
`

**Comment by msau42** [comment]
/reopen

@PaulFurtado do you know what triggered the filesystem to be unmounted? Even if a volume got unexpectantly detached, Kubernetes does not unmount the filesystem until the Pod has been terminated, in which case there should be no more containers restarting.

**Comment by yydzhou** [comment]
> /reopen
> 
> @PaulFurtado do you know what triggered the filesystem to be unmounted? Even if a volume got unexpectantly detached, Kubernetes does not unmount the filesystem until the Pod has been terminated, in which case there should be no more containers restarting.

Hi @msau42 In my case, the pvc is unmounted because of the pod termination (pod restart). However, the unmount and mount point cleanup process can fail in case the pvc is very large like 500G and above ( I guess too much dirty data to flush?). But in case of the unmount process failed, the mount point actually is broken anyway, so there is no nfs connected underneath, but the mountpoint path on the host file system still exists there. 
From kubelet side, it somehow thinks the mount point is still there as the directory/path is still there. So when the pod creation, it directly passed the mounting stage and allow pod to be created and launched based on that. 
As a results, there is just a directory/path, but not a real mount points, which the pod does not know the difference. So the pod continually writes to the path (mounted into pod), which lead to write into host file system and fill up the host file system space very soon.

**Comment by PaulFurtado** [comment]
> /reopen
> 
> @PaulFurtado do you know what triggered the filesystem to be unmounted? Even if a volume got unexpectantly detached, Kubernetes does not unmount the filesystem until the Pod has been terminated, in which case there should be no more containers restarting.

When a disk disappears, the kernel will attempt to unmount the busted filesystem itself. That may hang in the case that there is still a bind mount to it, or applications still have files open on it. However, in this case it is highly likely that the application inside the container then crashes since its disk just failed. At that point, the container will restart in-place, and the restarted container will end up having a bind mount to the host's filesystem.

**Comment by xing-yang** [comment]
Can you check if there's an udev setting to not automatically unmount?  This way the app will get an io error instead of writing to the local directory.
