### ISSUE TITLE
[failing-tests] SIG-Windows failing tests as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109908]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

- [ ] [ci-kubernetes-e2e-aks-engine-azure-master-windows-20h2-containerd](https://testgrid.k8s.io/sig-windows-sac#aks-engine-windows-20h2-containerd-master) | 36 | 
- [ ] [ci-kubernetes-e2e-windows-20h2-containerd-gce-1-22](https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-1.22) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-20h2-containerd-gce-1-23](https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-1.23) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-20h2-containerd-gce-1-24](https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-1.24) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-20h2-containerd-gce-master](https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-containerd-master) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-20h2-gce-1-22](https://testgrid.k8s.io/sig-windows-gce#gce-windows-20h2-docker-1.22) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-containerd-gce-1-24](https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-1.24) | 10 | 
- [ ] [ci-kubernetes-e2e-windows-containerd-gce-master](https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master) | 10 | 
- [ ] [soak-tests-capz-windows-2019](https://testgrid.k8s.io/sig-windows-soak-tests#soak-tests-capz-windows-2019) | 5 | 

/sig windows
/kind failing-test

**Comment by jsturtevant** [comment]
`soak-tests-capz-windows-2019` is a brand new job that @oprinmarius is working on as part of https://github.com/kubernetes/kubernetes/issues/108621.  This is a pre-submit job as of right now.

**Comment by jsturtevant** [comment]
soak-tests-capz-windows-2019 is passing now, might see occasional failure as it is a Pre-submit job
