### ISSUE TITLE
Duplicate Failed condition in job status

### ISSUE THREAD

**Issue by lsytj0413** [kubernetes/kubernetes#109904]
### What happened?

If the user update job.status.conditions, duplicate condition:

![image](https://user-images.githubusercontent.com/6871552/167402803-650072df-f926-4ed5-8960-107ae1160f71.png)

### What did you expect to happen?

Only one Failed condition

### How can we reproduce it (as minimally and precisely as possible)?

- Create Job and wait it marked as Failed
- Update the Failed condition to False

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.12", GitCommit:"4bf2e32bb2b9fdeea19ff7cdc1fb51fb295ec407", GitTreeState:"clean", BuildDate:"2021-10-27T17:07:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by able8** [comment]
It's not a bug.  The job.status.conditions is a list, so it can contain many conditions.
Also,  we should not update the `job.status.conditions` fields.

**Comment by lsytj0413** [comment]
> It's not a bug. The job.status.conditions is a list, so it can contain many conditions with different probe timestamps. Also, we should not update the `job.status.conditions` fields.

But should we avoid the duplicate Type's condition？In my opinion，this will confuse the user. According to kubelet, it will rewrite the 'Ready' condition in pod, and take is as managed only by kubelet. Should we did this for job Failed condition?

**Comment by saivarunk** [comment]
@alculquicondor can I take this issue ?

/assign

**Comment by mimowo** [comment]
I have reproduced the issue locally and intend work on the fix

**Comment by alculquicondor** [comment]
/priority backlog

Since the user is manually modifying the status, this is not an inherent bug in the controller. Still worth avoiding duplicates.
