### ISSUE TITLE
CI and authentication issue using service accounts

### ISSUE THREAD

**Issue by mrmiroslav** [kubernetes/kubernetes#10991]
I am trying to use service account to deploy on travis. 

gcloud has no issues with activating service account, pushing my docker image to container registry and etc.

The issue is with getting credentials: ```gcloud beta container get-credentials``` which returns 404 (cannot see the active project) - as I am authenticated on CI as a service account.

Locally I can run this using oAuth 2.0 authentication but same issue occurs with a service account.

Without credentials I cannot do a rolling-update with kubectl.

**Comment by erictune** [comment]
@roberthbailey @mbforbes @jlowdermilk you seem like y'all might know how to debug `gcloud beta container get-credentials`

**Comment by roberthbailey** [comment]
Does either `gcloud beta container clusters list` or `gcloud beta container clusters describe <name>` work? It may be an issue with the way we are authenticating service accounts in general vs. the implementation of that specific command (which doesn't do anything other than getting the cluster and writing a kubeconfig file to the local disk).

**Comment by mrmiroslav** [comment]
Not sure if the issue resolved, but ```gcloud beta container get-credentials``` is getting credentials with service account now. No changes has been made, just this morning - it worked.

**Comment by roberthbailey** [comment]
Strange -- AFAIK we haven't changed anything on our end. If you want to send me the project number for your project I can try to dig a bit deeper on our end. robertbailey [at] google.com.

**Comment by mbforbes** [comment]
+cc @jlowdermilk in case he'd like a final look, but closing since this seems to be resolved (please re-open if not!)
