### ISSUE TITLE
[failing-test] SIG Cloud Provider Azure tests

### ISSUE THREAD

**Issue by nckturner** [kubernetes/kubernetes#109983]
Triage failing Azure tests in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

ref: https://github.com/kubernetes/kubernetes/issues/109913

/assign @bridgetkromhout  

/area provider/azure
/sig cloud-provider
/kind failing-test

**Comment by bridgetkromhout** [comment]
Azure tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json - let's look at these, @lzhecheng (thanks for the fixes you mentioned in https://github.com/kubernetes/kubernetes/issues/109913#issuecomment-1131489037)
 

"ci-kubernetes-e2e-aks-engine-azure-1-24-windows-20h2-containerd": {
    "failing_days": 57
  },


  "ci-kubernetes-e2e-aks-engine-azure-1-24-windows-20h2-containerd-serial-slow": {
    "failing_days": 57
  },

  "pr:pull-cloud-provider-azure-e2e-ccm-vmss-basic-lb-1-24": {
    "failing_days": 51
  },

  "cloud-provider-azure-ccm-windows-capz": {
    "failing_days": 41
  },

  "cloud-provider-azure-conformance-windows-capz": {
    "failing_days": 41
  },

**Comment by bridgetkromhout** [comment]
Is this the fix: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2480

for https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-conformance-windows-capz
and for https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-ccm-windows-capz?

**Comment by monianshouhou** [comment]
> Is this the fix: [kubernetes-sigs/cluster-api-provider-azure#2480](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2480)
> 
> for https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-conformance-windows-capz and for https://testgrid.k8s.io/provider-azure-cloud-provider-azure#cloud-provider-azure-ccm-windows-capz?

Yes, it fixes part of the problem. Now CNM images can be pulled successfully, but there also exist some test adapting problems in cloud-azure-provider repo, which will be fixed in the next few days.

**Comment by lzhecheng** [comment]
@bridgetkromhout Now the 3 cloud-provider-azure tests haven been recovered. Thanks a lot for contribution from @monianshouhou !
