### ISSUE TITLE
Kubelet failed to start due to memory stat mismatch

### ISSUE THREAD

**Issue by wyhysj** [kubernetes/kubernetes#109996]
### What happened?

In kubelet config, we use `memoryManagerPolicy: Static`, and specify the following configuration to reserve memory for system etc
```
reservedMemory:
- limits:
    memory: 3Gi
  numaNode: 0
- limits:
    memory: 3Gi
  numaNode: 1
systemReserved:
  cpu: 1000m
  memory: 2Gi
kubeReserved:
  cpu: 1000m
  memory: 2Gi
```

When server rebooted, kubelet will fail to start, this is the error log

```
May 11 13:00:22 hostname kubelet[11960]: E0511 13:00:22.936228   11960 policy_static.go:650] "Memory states for the NUMA node and resource are different" node=0 resource="memory" memoryState1={TotalMemSize:134893809664 SystemReserved:32212>
May 11 13:00:22 hostname kubelet[11960]: E0511 13:00:22.936244   11960 policy_static.go:84] "Invalid state, please drain node and remove policy state file" err="[memorymanager] the expected machine state is different from the real one"
May 11 13:00:22 hostname kubelet[11960]: E0511 13:00:22.936254   11960 memory_manager.go:184] "Policy start error" err="[memorymanager] the expected machine state is different from the real one"
May 11 13:00:22 hostname kubelet[11960]: E0511 13:00:22.936264   11960 kubelet.go:1378] "Failed to start ContainerManager" err="start memory manager error: [memorymanager] the expected machine state is different from the real one"
May 11 13:00:22 hostname systemd[1]: kubelet.service: Main process exited, code=exited, status=1/FAILURE
```

Everytime I reboot server, the numa stat changes, so the total memory of numa nodes will change also, but the sum of all the numa nodes memory is same (memory of physical server)

Here is the output of `numactl --hardware` output before and after rebooting

```
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30
node 0 size: 128611 MB
node 0 free: 126982 MB
node 1 cpus: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31
node 1 size: 129019 MB
node 1 free: 126831 MB
node distances:
node   0   1 
  0:  10  21 
  1:  21  10 
```

```
available: 2 nodes (0-1)
node 0 cpus: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30
node 0 size: 128644 MB
node 0 free: 126473 MB
node 1 cpus: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31
node 1 size: 128985 MB
node 1 free: 128466 MB
node distances:
node   0   1 
  0:  10  21 
  1:  21  10 
```

Here's an sample of `/var/lib/kubelet/memory_manager_state`

```
{
  "policyName": "Static",
  "machineState": {
    "0": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 134858416128,
          "systemReserved": 3221225472,
          "allocatable": 131637190656,
          "reserved": 0,
          "free": 131637190656
        }
      },
      "cells": [
        0
      ]
    },
    "1": {
      "numberOfAssignments": 0,
      "memoryMap": {
        "hugepages-1Gi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "hugepages-2Mi": {
          "total": 0,
          "systemReserved": 0,
          "allocatable": 0,
          "reserved": 0,
          "free": 0
        },
        "memory": {
          "total": 135286390784,
          "systemReserved": 3221225472,
          "allocatable": 132065165312,
          "reserved": 0,
          "free": 132065165312
        }
      },
      "cells": [
        1
      ]
    }
  },
  "checksum": 1446067208
}
```

### What did you expect to happen?

Kubelet service can start after reboot

### How can we reproduce it (as minimally and precisely as possible)?

I think can reproduce with numa enabled and set `memoryManagerPolicy: Static`.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
# uname -a
Linux hostname 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tossmilestone** [comment]
@wyhysj have you drained the node?

**Comment by wyhysj** [comment]
> @wyhysj have you drained the node?

No, sometimes node got rebooted or power failure, and after restarting, kubelet should be up normally without any intervention.

**Comment by tossmilestone** [comment]
@wyhysj you could drain node and remove `/var/lib/kubelet/memory_manager_state`, then reboot to create a fresh state file.    The issue should be fixed.

**Comment by wyhysj** [comment]
> @wyhysj you could drain node and remove `/var/lib/kubelet/memory_manager_state`, then reboot to create a fresh state file. The issue should be fixed.

I know that will resolve this issue, but seems by design we should avoid such human intervention, even I didn't drain the node, remove the `/var/lib/kubelet/memory_manager_state` and restart kubelet will resolve this issue.

If a node becomes NotReady for whatever reason, when it comes back, kubelet should start and correct the error memory state by itself.

**Comment by assafaa** [comment]
Hey guys,

This issue happens to us as well.
A server with two Numa nodes [0,1] might change total memory on boot without any hardware changes.
Each bear-metal server boots we delete the state file.

**Comment by SergeyKanzhelev** [comment]
@swatisehgal have you had a chance to look at it? If it is a bug please triage accept it, thank you

**Comment by swatisehgal** [comment]
> What happens if we reenable the feature if it was previously rolled back? The Memory Manager utilizes the state file to track memory assignments. If State file is not valid, it must be removed and kubelet restarted. E.g., State file might become invalid when kube/system reserved have changed (increased), which may lead to a situation when some containers cannot be started.

**Comment by swatisehgal** [comment]
Please note that this is a known behavior and it has been documented in the Memory Manager KEP [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1769-memory-manager/README.md).
> The Memory Manager utilizes the state file to track memory assignments. If State file is not valid, it must be removed and kubelet restarted. E.g., State file might become invalid when kube/system reserved have changed (increased), which may lead to a situation when some containers cannot be started.

I wouldn't classify this as a bug. The desired behavior in the issue description and comments below seems more like a feature request to me.

**Comment by wyhysj** [comment]
> Please note that this is a known behavior and it has been documented in the Memory Manager KEP [here](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1769-memory-manager/README.md).
> 
> > The Memory Manager utilizes the state file to track memory assignments. If State file is not valid, it must be removed and kubelet restarted. E.g., State file might become invalid when kube/system reserved have changed (increased), which may lead to a situation when some containers cannot be started.
> 
> I wouldn't classify this as a bug. The desired behavior in the issue description and comments below seems more like a feature request to me.

Agree, another possible workaround, is there any way to fix numa memory allocation on boot?

**Comment by Vigilans** [comment]
This issue still exists after Kubernetes v1.32 released with https://github.com/kubernetes/kubernetes/pull/127074 fix.
