### ISSUE TITLE
The `ServiceIPStaticSubrange` assigns duplicate IP addresses when the dynamic block is exhausted

### ISSUE THREAD

**Issue by tksm** [kubernetes/kubernetes#109927]
### What happened?

In a `ServiceIPStaticSubrange` enabled cluster, Kubernetes assigns duplicate IP addresses when the dynamic block is exhausted.

```
$ kubectl get svc --all-namespaces | grep "10.96.0.1 " | head
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  152m
default       svc47        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc48        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc49        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc50        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc51        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc52        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc53        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc54        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
default       svc55        ClusterIP   10.96.0.1    <none>        80/TCP                   41s
```

### What did you expect to happen?

I expected all clusterIPs are uniquely assigned.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a `ServiceIPStaticSubrang` enabled Kubernetes v1.24 cluster with a small service-cluster-ip-range. I confirmed on the minikube with the following command.

```
minikube start \
  --kubernetes-version v1.24.0 \
  --extra-config=apiserver.service-cluster-ip-range=10.96.0.0/26 \
  --feature-gates=ServiceIPStaticSubrange=true
```

2. Create services until the dynamic block is exhausted.

```
# create a dummy pod
kubectl create deploy nginx --image nginx --port 80

# create 100 services
for I in $(seq 1 100); do
  kubectl expose --name "svc$I" deploy/nginx --port 80
done
```

3. We see some clusterIPs are duplicated.

```
kubectl get svc --all-namespaces | awk '{print $4;}' | sort | uniq -c | sort -nr | head -3
  16 10.96.0.1
   1 CLUSTER-IP
   1 10.96.0.62
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube v1.25.2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cyclinder** [comment]
When the dynamic block  is exhausted, we expect the service creation to fail with an error message like "No IP address available",  right?

**Comment by tksm** [comment]
According to [KEP-3070: Reserve Service IP Ranges For Dynamic and Static IP Allocation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3070-reserved-service-ip-range), Dynamically IP assignment will use the upper band by default, once this has been exhausted it will use the lower range. So I think using the reserved block (the lower range) is expected behavior

**Comment by aojea** [comment]
/assign @tksm 
great catch, thanks
