### ISSUE TITLE
[failing-test] SIG-Testing as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109916]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

CI Job | Days | URL
-- | -- | --
ci-kubernetes-coverage-conformance | 433 | https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-coverage-conformance
ci-kubernetes-coverage-e2e-gci-gce | 433 | https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-coverage-e2e-gci-gce
ci-kubernetes-e2e-node-canary | 285 | https://testgrid.k8s.io/sig-testing-canaries#node
ci-kubernetes-generate-make-test-count10 | 425 | https://testgrid.k8s.io/sig-testing-canaries#ci-kubernetes-generate-make-test-count10
post-test-infra-push-gcloud-terraform | 272 | https://testgrid.k8s.io/sig-testing-images#gcloud-terraform
test-infra-cfl-coverage-report | 188 | https://testgrid.k8s.io/sig-testing-misc#test-infra-cfl-coverage-report
test-infra-fuzz | 213 | https://testgrid.k8s.io/sig-testing-misc#test-infra-fuzz

/sig testing
/kind failing-test

cc @chaodaiG @BenTheElder

**Comment by chaodaiG** [comment]
`test-infra-fuzz` has failed for 213 days, @mpherman2 is it still relevant?

**Comment by chaodaiG** [comment]
`test-infra-cfl-coverage-report` seems to be also related to fuzz testing, @mpherman2 could you also take a look please?

Have gone through the jobs that I might have context with, please at me if there is anything else that I could help with

**Comment by BenTheElder** [comment]
> ci-kubernetes-coverage-conformance
> ci-kubernetes-coverage-e2e-gci-gce

Coverage fix (first one was wrong 🤦) https://github.com/kubernetes/kubernetes/pull/109843

> ci-kubernetes-e2e-node-canary

This seems to be an issue for SIG Node.

> ci-kubernetes-generate-make-test-count10

This is failing because there are unit tests that are too flaky to pass 10 times, we should not remove the job we should file bugs for the handful of tests that are not reliable. And once they're passing IMO this should be release-informing.

> post-test-infra-push-gcloud-terraform

Not sure where this one is used. Looks like a broken image build though, probably worth fixing. This should be a test-infra issue similar to https://github.com/kubernetes/test-infra/issues/26118

> test-infra-cfl-coverage-report
> test-infra-fuzz

existing fuzz issue: https://github.com/kubernetes/test-infra/issues/26113

**Comment by chaodaiG** [comment]
forgot to mention that https://github.com/kubernetes/test-infra/pull/26237 fixes gcloud-terraform image

**Comment by BenTheElder** [comment]
thanks @chaodaiG -- green now after kubernetes/test-infra#26237 https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-test-infra-push-gcloud-terraform/1523715759824441344

**Comment by BenTheElder** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-coverage-conformance/1523775425250070528

Coverage still not compiling. maybe should've gotten it under typecheck, we maybe don't want to expand that test matrix so much though with different tag combinations ...

**Comment by BenTheElder** [comment]
test-infra-fuzz and test-infra-cfl-coverage-report were deleted https://github.com/kubernetes/test-infra/pull/26398

**Comment by BenTheElder** [comment]
the coverage package is still broken, I'll try to PR this soon. I think this technique is still valuable.

similarly I think the make-test-count10 results are valuable, the problem is just that unit tests are flaky
