### ISSUE TITLE
hack/conformance-test.sh runs "[Skipped] persistentVolumes" tests

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#10996]
At least when I ran it naively, hack/conformance-test.sh was not skipping this test.  The comment suggests it should be skipped automatically: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/persistent_volumes.go#L31-L34

Not sure if I'm doing something wrong, or we need to tell hack/conformance-test to skip `[Skipped].*` or something like that.

**Comment by erictune** [comment]
Fixed by #10994.   `"Skipped` does not match ` Skipped ` or `[Skipped]`.  Took me a long time to figure that bug out.

#10994 is not merged yet but the equivalent change is merged to conformance-test-v1 branch instead of master.

**Comment by ihmccreery** [comment]
Closing as fixed by #10994, but I'm not verifying.
