### ISSUE TITLE
kube-scheduler: disabling insecure port does not work (1.21)

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#109900]
### What happened?

We are using Kubernetes 1.21. deployed using kubespray.

to enable secure ports, we have added the below configuration in the controller as well as a scheduler.
- --port=0
- - --secure-port=10257/10259.
- bind-address=127.0.0.1

we accessing from outside, still can see 10251 port(insecure) is opened, which of the scheduler.

below are the logs from the scheduler.
I0506 08:40:09.528927 1 deprecated_insecure_serving.go:54] Serving healthz insecurely on [::]:10251
I0506 08:40:09.538458 1 secure_serving.go:202] Serving securely on 127.0.0.1:10259

### What did you expect to happen?

insecure should be closed and not exposed to the outside world.

Note: same above configuration worked with 1.16

### How can we reproduce it (as minimally and precisely as possible)?

Just deploy 1.21 k8s with the above configuration and run nmap scan from the remote machine on 10251 port.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux localhost 4.19.81-OpenNetworkLinux #1 SMP Mon Mar 21 05:24:05 UTC 2022 x86_64 GNU/Linux


#104672 # On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/retitle kube-scheduler: disabling insecure port does not work (1.21)

**Comment by SataQiu** [comment]
https://github.com/kubernetes/kubernetes/blob/f3ad8e60207d1f8e24e4d2641e98206bdb64753b/cmd/kube-scheduler/app/options/insecure_serving.go#L37-L38

https://github.com/kubernetes/kubernetes/blob/f3ad8e60207d1f8e24e4d2641e98206bdb64753b/cmd/kube-scheduler/app/options/options.go#L204-L207

Did you specify the configuration file for kube-scheduler using `--config`?
If you use `--config` to specify the configuration file, `--port` will no longer take effect anymore.

**Comment by akshaysharama** [comment]
- kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --config=/etc/kubernetes/kubescheduler-config.yaml
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    -  --port=0
    - --secure-port=10259

yes, we have specified --config!!. Is this introduced in k8s 1.21? because the same configuration worked in 1.16.

So, now what we can do to disable the 10251 port?

**Comment by akshaysharama** [comment]
Any reason, when giving --config, --port is will not longer take effect? because we need both of them.
just for understanding.

**Comment by neolit123** [comment]
In kubelet and kubeadm flags override --config. In scheduler its the other way around. In kube-proxy it is both ways.

You can remove all flags and only use --config. But the question here is whether kubeschedulerconfiguration has the --port field.

**Comment by neolit123** [comment]
@kubernetes/sig-scheduling-bugs

**Comment by akshaysharama** [comment]
--port is deprecated I guess, 

the following official document for the scheduler doesn't mention the --port parameter.
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

if it depreciated, then how we can disable the insecure port?
and why --config has to do with --port? why --port are not longer taking effect? what is the relation between these two? or in config file we can mention --port? and it will work?

**Comment by kerthcet** [comment]
Actually this is worked as expected, when using `--config`, `--port` will be ignored. IIRC, we removed the insecure flags in v1.24 already. I think we should cover this need here in case of secure requirement, but I don't know the origin design, do you have any idea @Huang-Wei ?

**Comment by Huang-Wei** [comment]
@kerthcet is right. The behavior is documented in the 1.21 website: https://v1-21.docs.kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1425903/185206619-31c2e216-0ca5-4061-afd9-642e5b7e82af.png">

With that being said, you have to keep using the deprecated CLI arguments, and do NOT use `--config`, which will honor the `--port=0` argument so as to disable insecure serving.
