### ISSUE TITLE
Handling of per-driver fsgroup and other properties is broken for CSI drivers with multiple volume types support

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#109949]
### What happened?

We traditionally expected one CSI driver to generally expose one type of volume. For example:

```
EBS CSI driver --> Block volume (File system or raw block)
EFS CSI driver ---> NFS Shared Volume types
```
So as long as one driver exposes only one kind of volumes, it all works fine. 

But then there are drivers like azurefile CSI driver, which are exposing both block volumes and shared volume types and for those drivers - having a global instance of `CSIDriver` type that defines driver's properties is problematic. 

For example - for azurefile CSI driver, which traditionally exposed volume via CIFS protocol, fsgroup is applied as an mount option (chown/chmod may not even work because of lack of UNIX extensions). But if same driver exposes block volumes then one global value `FSGroupPolicy`  does not make sense. It has to be per-volume basis.

FSGroup however is not the only property which is problematic. Other properties like SELinux support, Republish support etc are problematic too.

### What did you expect to happen?

Expected pod to be able to read/write files from the volume.

### How can we reproduce it (as minimally and precisely as possible)?

Try to use Azurefile VHD volumes with fsgroup support running in a non-root pod. Pod can't write files to the volume.

More details are in - https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/1012

### Anything else we need to know?

Expected pod to be able to read/write files from the volume.

### Kubernetes version

Kubernetes-1.24

### Cloud provider

None

### OS version

None

### Install tools

None

### Container runtime (CRI) and version (if applicable)

None

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None

**Comment by bswartz** [comment]
I'm willing to own changing the CSI spec to enable this. I'm not sure what's involved on the kubelet side but I can help there -- I'm not sure I can sign up to own that though.
I can also lead whatever meetings we need to talk through the potential approaches and collect notes.

**Comment by andyzhangx** [comment]
I think we could still keep the `spec.fsGroupPolicy` in `CSIDriver` to make backward compatibility, while we could add a new property `fsGroupPolicy` (could be empty) per volume, if `fsGroupPolicy` in CSI volume is defined, then respect that value, otherwise respect `fsGroupPolicy` in `CSIDriver`

```yaml
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: file.csi.azure.com
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  fsGroupPolicy: File
```

**Comment by andyzhangx** [comment]
BTW, vhd feature is just a preview feature, it does not matter much if it's broken in `fsGroupPolicy`, the Azure File CSI driver provides both smb and nfs protocols, for nfs, we want to leverage `fsGroupPolicy: File`, while for smb, we want to set `fsGroupPolicy: None`, one global value in CSIDriver could not solve such issue, I think defining `fsGroupPolicy` could solve the problem, thanks.

**Comment by gnufied** [comment]
The problem I think is not unique to azurefile though. There is also vSphere CSI driver which ships both block and shared filesystem volumes with same driver name and @bswartz has some similar drivers. The fact is - these global attributes of CSI driver defined via `CSIDriver` object does not work well for drivers that expose multiple volume types using same driver name.

**Comment by ddebroy** [comment]
Similar concern around the newly proposed selinux-on-mount option as well: https://github.com/kubernetes/enhancements/pull/3172/files#r791327817
