### ISSUE TITLE
[failing-tests] SIG-Storage failing tests as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109910]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

CI Jobs | Days | URL
-- | -- | -- 
canary-nfs-subdir-external-provisioner-push-images | 475 | https://testgrid.k8s.io/sig-k8s-infra-gcb#canary-nfs-subdir-external-provisioner-push-images 
canary-sig-storage-local-static-provisioner-push-images | 532 | https://testgrid.k8s.io/sig-k8s-infra-gcb#canary-sig-storage-local-static-provisioner-push-images
ci-gce-pd-csi-driver-latest-k8s-master-windows-2019-migration | 116 | https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#ci-windows-2019-provider-gcp-compute-persistent-disk-csi-driver-migration
ci-gce-pd-csi-driver-latest-k8s-master-windows-20h2-migration | 116 | https://testgrid.k8s.io/provider-gcp-compute-persistent-disk-csi-driver#ci-windows-20h2-provider-gcp-compute-persistent-disk-csi-driver-migration
ci-kubernetes-e2e-gce-iscsi | 152 | https://testgrid.k8s.io/sig-storage-kubernetes#gce-iscsi
ci-kubernetes-e2e-gce-iscsi-serial | 152 | https://testgrid.k8s.io/sig-storage-kubernetes#gce-iscsi-seria
pull-csi-driver-smb-e2e-gce | 70 | https://testgrid.k8s.io/sig-storage-csi-other#pull-csi-driver-smb-e2e-gce
pull-kubernetes-e2e-gce-iscsi | 152 | https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-iscsi
pull-kubernetes-e2e-gce-iscsi-serial | 152 | https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-iscsi-serial

**Comment by msau42** [comment]
@jsafrane I propose we disable the iscsi jobs if we can't resolve the failures this week.

**Comment by msau42** [comment]
@jingxu97 @mauriciopoppe can you help look at the gce smb test failures?
https://github.com/kubernetes/kubernetes/issues/109910

**Comment by msau42** [comment]
@mauriciopoppe unless gce is testing some different functionality than the azure job, then it should be fine to disable the gce job.

**Comment by humblec** [comment]
> Pinging nfs-subdir owners: @ashishranjan738 @humblec @jackielii @kmova @yonatankahana
> 
> Would one of you be able to help investigate the image building failures? https://testgrid.k8s.io/sig-k8s-infra-gcb#canary-nfs-subdir-external-provisioner-push-images
> 
> I propose that we disable the job if we can't resolve it this week.

@msau42 I have filed the fix PR https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/199 and its merged. That should take care of the failure

**Comment by msau42** [comment]
Thanks everyone for jumping on this! @mauriciopoppe @jsafrane are you also ok removing the iscsi CI jobs?

**Comment by xing-yang** [comment]
@dims Can this issue be closed now?  I think the failing tests are either fixed or disabled now.

**Comment by yonatankahana** [comment]
@xing-yang they are still not fixed in `nfs-subdir-external-provisioner`, but merging https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/208 and https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/209 should solve that (hopefully)

**Comment by dims** [comment]
@xing-yang please feel free to close the issue when you feel right.

**Comment by yonatankahana** [comment]
@xing-yang the PRs in `nfs-subdir-external-provisioner` merged and our internal tests looks [good](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-nfs-subdir-external-provisioner-push-images/1531844761130897408). 
the next schedule for the failing canary build is in one week (07.06.22), there is a way to trigger it now so we can confirm that it all solved?
