### ISSUE TITLE
prevent protential goroutine leakages in scheduler

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#109962]
### What would you like to be added?

In this issue https://github.com/kubernetes/kubernetes/issues/108483, we're trying to find potential goroutine leakages in k8s, as a separation, this issue only focuses on the kube-scheduler. 
Currently, the fact is that we have multiple places calling API with a `context.TODO()` or `context.Background()`, but in theory, we should use an inherit one in case of context cancelling or timeout.  See https://github.com/kubernetes/kubernetes/blob/b74d023e70d6064c7f3f77031e7d26ec38497fc9/pkg/scheduler/framework/plugins/volumebinding/binder.go#L502-L510

I collected several places below, maybe not all:

- [x] [volumebinding plugin](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder.go)
- [x] [utils](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/util/utils.go) https://github.com/kubernetes/kubernetes/pull/110202
- [x] [scheduler tests](https://github.com/kubernetes/kubernetes/blob/b74d023e70d6064c7f3f77031e7d26ec38497fc9/pkg/scheduler/scheduler_test.go#L348-L355) https://github.com/kubernetes/kubernetes/pull/110232
- [x] [framework tests](https://github.com/kubernetes/kubernetes/blob/b74d023e70d6064c7f3f77031e7d26ec38497fc9/pkg/scheduler/framework/runtime/framework_test.go#L1484-L1487)https://github.com/kubernetes/kubernetes/pull/110182#issuecomment-1136896057

/kind cleanup
/sig scheduling

### Why is this needed?

Reduce goroutine leakages

**Comment by kerthcet** [comment]
/assign 
I'll help to take a look then.

**Comment by kerthcet** [comment]
also cc @ahg @alculquicondor @Huang-Wei

**Comment by alculquicondor** [comment]
While this is good to solve, I'm not sure this is the major source of routine leakages.

https://github.com/kubernetes/kubernetes/blob/c50579afb1c3fbb2b83007bba6e8d285436d5dc9/test/integration/util/util.go#L429-L430

I think this might be a more relevant source: this channel is never stopped. We should be using `ctx.Done()`

**Comment by alculquicondor** [comment]
Not sure if there are other instances like this in the codebase.

**Comment by kerthcet** [comment]
Also need to address the comments here https://github.com/kubernetes/kubernetes/pull/110148#discussion_r878671611

**Comment by kidddddddddddddddddddddd** [comment]
Maybe also some in:
[utils_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/util/utils_test.go)
[binder_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder_test.go)
[scheduler.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go)
[binder.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder.go)
[default_preemption_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption_test.go)

(Just searched `context.TODO()`. Not sure)

**Comment by kidddddddddddddddddddddd** [comment]
Hey,I think this may be a good issue for a beginner like me. I think I can help you with task [volumebinding plugin](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder.go). And help check other places if you can let me :)

**Comment by kerthcet** [comment]
It will be great, plz go ahead @kidddddddddddddddddddddd

**Comment by kerthcet** [comment]
/close
Since we addressed the planned issues.
