### ISSUE TITLE
The metrics for the cluster IP allocator are incorrectly reported

### ISSUE THREAD

**Issue by tksm** [kubernetes/kubernetes#109994]
### What happened?

The metrics for the cluster IP allocator (`kube_apiserver_clusterip_allocator_*`) are occasionally reported incorrect values. I suspect that the metrics are overwritten by [the repair loop](https://github.com/kubernetes/kubernetes/blob/v1.24.0/pkg/registry/core/service/ipallocator/controller/repair.go#L41-L42).

The following example is the metrics on a cluster with only two services. `allocated_ips` and `allocation_total` should be 2.

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 0
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 14
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048574e+06

$ kubectl get svc --all-namespaces
NAMESPACE     NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  20m
kube-system   kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   20m
```

/sig  network

### What did you expect to happen?

I expected it reports the correct metrics for the cluster IP allocator.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Kubernetes v1.24 cluster. I confirmed the issue on the minikube with the following command.

```
minikube start --kubernetes-version v1.24.0
```

2. Immediately after starting the cluster, it correctly reports that `allocated_ips` is 2 and `allocation_total` is 2.

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 2
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 2
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048572e+06
```

3. But after a while with doing nothing, it incorrectly reports that `allocation_ips` is 0 and `allocation_total` is 4

```
$ kubectl get --raw /metrics | egrep "^kube_apiserver_clusterip_allocator"
kube_apiserver_clusterip_allocator_allocated_ips{cidr="10.96.0.0/12"} 0
kube_apiserver_clusterip_allocator_allocation_total{cidr="10.96.0.0/12",scope="static"} 4
kube_apiserver_clusterip_allocator_available_ips{cidr="10.96.0.0/12"} 1.048574e+06
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube v1.25.2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
sounds very possible you are right :smile: 
/triage accepted

is this something you are going to work on it @tksm , should I assign it to you?

**Comment by tksm** [comment]
@aojea Yes, I am working on it. Could you assign it to me?

**Comment by aojea** [comment]
/assign @tksm 

> @aojea Yes, I am working on it. Could you assign it to me?
:heart:
