### ISSUE TITLE
Confusing log from kubelet crash when `--container-runtime-endpoint` is wrong

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#109917]
### What happened?

I installed Docker, https://github.com/Mirantis/cri-dockerd, and Kubernetes release 1.24.  I used `hack/local-up-cluster.sh` to start a single-node local cluster, without specifying `CONTAINER_RUNTIME_ENDPOINT`, so it defaulted to `unix:///run/containerd/containerd.sock` --- which is indeed a thing, but is the _wrong_ thing (I eventually worked out that I need to point Kubernetes at `unix:///run/cri-dockerd.sock` instead).  The kubelet came up briefly, issued a bunch of I messages, and a couple of W and a couple of E, then a usage message, and exited.  Since the last thing in the log was the usage message, I figured the problem was something syntactic on the command line.  I eventually realized that is not true.

### What did you expect to happen?

I expected the kubelet log to give me a clearer idea of why it is exiting, not mislead me.

### How can we reproduce it (as minimally and precisely as possible)?

Run a kubelet with `--container-runtime-endpoint` pointing to an _unsuitable_ container runtime.

### Kubernetes version

<details>

Release 1.24

</details>

### Cloud provider

<details>
VirtualBox VM
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux ubu22 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
`hack/local-up-cluster.sh`
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker 20.10.14
https://github.com/Mirantis/cri-dockerd commit 0607a1ba0d36296ef7142bab4fa45e50064e39c7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-node-bugs

**Comment by endocrimes** [comment]
We should make hack/local-up-cluster error out if the runtime socket doesn't exist.

/triage accepted
/priority backlog
