### ISSUE TITLE
[failing-tests] SIG-Node failing tests as of May 9th

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#109911]
Context: Tests marked as failing in https://storage.cloud.google.com/k8s-metrics/failures-latest.json

CI Job | Days | URL
-- | -- | --
ci-containerd-soak-cos-gce | 64 | https://testgrid.k8s.io/sig-node-cos#soak-cos-gce
ci-cri-containerd-e2e-cos-gce-flaky | 174 | https://testgrid.k8s.io/sig-node-cos#soak-cos-gce
ci-crio-cgroupv1-node-e2e-eviction | 150 | https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-eviction
ci-crio-cgroupv1-node-e2e-flaky | 113 | https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky
ci-kubernetes-node-kubelet-containerd-eviction | 150 | https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction
ci-kubernetes-node-kubelet-containerd-performance-test | 82 | https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test
ci-kubernetes-node-swap-fedora-serial | 34 | https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial
pull-kubernetes-node-kubelet-serial-crio-cgroupv1 | 34 | https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv1
pull-kubernetes-node-kubelet-serial-crio-cgroupv2 | 34 | https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv2
pull-kubernetes-node-swap-fedora-serial | 85 | https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-fedora-serial
pull-kubernetes-node-swap-ubuntu-serial | 38 | https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-swap-ubuntu-serial

/sig node
/kind failing-test

**Comment by endocrimes** [comment]
ci-kubernetes-node-swap-fedora-serial is now passing: https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-swap-fedora-serial

**Comment by pacoxu** [comment]
- [node-kubelet-containerd-eviction](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-eviction) is tracked in https://github.com/kubernetes/kubernetes/issues/107063
- ci-cos-cgroupv2-containerd-node-e2e-serial: https://github.com/kubernetes/kubernetes/issues/106635

**Comment by fromanirh** [comment]
The device plugin tests [will skip](https://github.com/kubernetes/kubernetes/pull/109770) on all lanes until we get to the bottom of the failures - which is challenging because they seem to fail only on some CIs - most notably, the kube CI :)
