### ISSUE TITLE
Allow Resource Quotas to be scoped based on label selectors

### ISSUE THREAD

**Issue by YairHalberstadt** [kubernetes/kubernetes#110065]
### What would you like to be added?

Currently Resource Quotas can be [scoped](https://kubernetes.io/docs/concepts/policy/resource-quotas/#quota-scopes) based on whether a pod is terminating or not, best effort or not, its priority, and its CrossNamespacePodAffinity.

It should be possible to scope a Resource Quota to any objects which match a particular label selector. This would allow providing more fine grained control of Resource Quotas than is currently possible.

I would be willing to implement this if it is accepted.

### Why is this needed?

Currently Resource Quotas focus mainly on allocating resources fairly between teams sharing the same cluster. For this purpose having quotas which only apply to a particular set of labels is pointless, as the team could just edit the labels till the quota no longer applies.

However Resource Quotas have the potential to provide more fine grained control over individual workloads that might be running in the same namespace.

For example, we have a controller that will spin up a number of pods to handle a task. The number of pods scales linearly with the size of the task but we want to make sure that the task doesn't use more than its fair share of CPU resources, so that other workloads running in the same namespace don't suffer. Resource Quotas would be a great way to enable this, but currently don't have the fine grained control necessary for this.

If Resource Quotas could be scoped to pods matching a particular label selector, we could easily do this by giving all the pods created by the controller a particular label, and selecting that label in the Resource Quota.

**Comment by liggitt** [comment]
this looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/77508, which did not make progress as an issue or have a concrete design proposed

**Comment by denkensk** [comment]
How about creating a new namespace for this job? 
If we allow the resource quota to be scoped on the label selector. I am concerned there may be many different resource quotas in the same namespace, and they may intersect with each other, making troubleshooting problems complicated.

**Comment by YairHalberstadt** [comment]
Creating a new namespace is tricky as we need to mount secrets stored in this namespace.

**Comment by vsxen** [comment]
use scheduler plugin ? 
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/9-capacity-scheduling/README.md
for example:
```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota1
  namespace: quota1
spec:
  max:
    cpu: 2
  min:
    cpu: 1
  selector:
    matchLabels:
      app: nginx
```

**Comment by fabiand** [comment]
FWIW labels have the problem that they are workload owner provided.

However, maybe a similar pattern like the Pod Admission Policy is using - an admin defined policy to permit certain objects to be ignored by quota controller. This would separate the personas benefiting from the allowlisting and defining the policy.

**Comment by aravindhan-p-kf** [comment]
> https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/9-capacity-scheduling/README.md

I don't think is a solution, not seeing any selector section in the official Elastic Quota documentation

**Comment by mtsoltan** [comment]
2 years later, is this any more possible than it was when it was closed and forgotten?

**Comment by liggitt** [comment]
I don't think it was forgotten... this looks like a duplicate of https://github.com/kubernetes/kubernetes/issues/77508, which had more feedback. Hoisting from there:

> the scopes added so far have covered attributes of objects that incur different types of resource consumption (terminating pods, types of services, priority class levels, etc)
> 
> pod labels are fully under the control of the actor creating the pods, and can be freely changed without affecting the resources actually consumed by the pod, so they don't seem like a great control for quota to enforce on
