### ISSUE TITLE
Rollout history doesn't show the revision when output format is used

### ISSUE THREAD

**Issue by nhumrich** [kubernetes/kubernetes#110097]
### What happened?

If you use `kubectl rollout history --revision=100` you get the pod spec at revision 100. 

Everything is correct. However, if you add the `-o json` or `-o yaml` on the command, you just get the latest deployment, and not the revision you specified.

### What did you expect to happen?

I expected to get the deployment spec of the revision I specified, or at least some json representation of what I see without the `-o json`

### How can we reproduce it (as minimally and precisely as possible)?

create a deployment. Update the deployment `image` using `kubectl apply -f mydeployment.yaml` a couple times. 
Run `kubectl rollout history deployment/my-deployment --revision 1`

Then add the `-o json` at the end. Compare the image tag in both versions. They won't be the same. When you add `-o json` you get the latest revision instead.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"archive", BuildDate:"2022-02-18T22:31:12Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-25803e", GitCommit:"25803e8d008d5fa99b8a35a77d99b705722c0c8c", GitTreeState:"clean", BuildDate:"2022-02-16T23:37:16Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS (AWS)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

$ uname -a
# paste output here
Linux humdingr-dell 5.15.28-1-MANJARO #1 SMP PREEMPT Fri Mar 11 14:12:57 UTC 2022 x86_64 GNU/Linux
```
</details>

### Install tools

<details>
n/a
</details>

### Container runtime (CRI) and version (if applicable)

<details>
n/a
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
n/a
</details>

**Comment by ardaguclu** [comment]
`rollout history --revision` works the way similar to `describe` command as seen in here https://github.com/kubernetes/kubernetes/blob/548b3a784bf2d05a8cfbaf289ce257d7b71efab2/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/history.go#L154.

If `--output` flag is passed, it just prints the object https://github.com/kubernetes/kubernetes/blob/c4f8c57b43843abd13bae677b73c622e1c30b46f/staging/src/k8s.io/kubectl/pkg/cmd/rollout/rollout_history.go#L181

I think, we might need to remove `--output=json|yaml` flags from this command(to make it compatible with `describe`)

**Comment by alexef** [comment]
This doesn't work even when no revision is provided, see: https://github.com/kubernetes/kubernetes/issues/72782

**Comment by brianpursley** [comment]
> This doesn't work even when no revision is provided, see: #72782 (i.e. if I run the command without `--revision` but specify an output format such as `json` or `yaml`, only one item is returned, which is the latest and current Deployment specification; what I would have expected instead is that a list of ReplicaSet instances is returned; not sure if #111093 will fix that as well)

It should fix the output with or without `--revision`
