### ISSUE TITLE
[Question] Could you elaborate on how namespaces, are required to be statically set

### ISSUE THREAD

**Issue by wibed** [kubernetes/kubernetes#110078]
### What happened?

cannot provision resources dynamically.

### What did you expect to happen?

to dynamically set namespaces as need arises

### How can we reproduce it (as minimally and precisely as possible)?

ClusterRoleBinding.subjects requires a namespace to be set statically

### Kubernetes version

<details>

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
This looks like
/kind support

**Comment by neolit123** [comment]
discuss.k8s.io or the dev@kubernetes.io mailing list can be a used for this discussion:
https://github.com/kubernetes/community/blob/master/communication/mailing-list-guidelines.md#sharing-the-meeting-notes-with-the-google-group

for additional support questions, please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
