### ISSUE TITLE
kubelet without deprecated `--cloud-provider=external` do not get proper taint and are not CCM initialized

### ISSUE THREAD

**Issue by deitch** [kubernetes/kubernetes#110018]
### What happened?

The [kubelet CLI docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/) state that `--cloud-provider=external` is deprecated and will go away in1.24:

> 
> --cloud-provider string
> --
>  | The provider for cloud services. Set to empty string for running with no cloud provider. If set, the cloud provider > determines the name of the node (consult cloud provider documentation to determine if and how the hostname is used). (DEPRECATED: will be removed in 1.24 or later, in favor of removing cloud provider code from Kubelet.)

The [docs for running a CCM](https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#running-cloud-controller-manager), on the other hand, say that `--cloud-provider=external` is required, in order to get the proper `node.cloudprovider.kubernetes.io/uninitialized` taint.

I launched a single-node 1.23 cluster without `--cloud-provider=external`, and while I did not get the deprecation warnings, the node was not properly tainted, and the CCM I am running never seems to get the correct calls leading to populating the providerID and removing the taint.

I do not know if this is a bug in the controller-manager and/or kubelet, or that we need to do something else to get this to work, and thus missing documentation. 

### What did you expect to happen?

node to get the correct taint, k8s to initialize the node.

### How can we reproduce it (as minimally and precisely as possible)?

1. Launch a single node cluster without `--cloud-provider=external`
2. See that the node does not have the taint
3. Launch a CCM
4. See that it does not set the provider ID

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Using Equinix Metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux k8s-master-01 5.4.0-107-generic #121~18.04.1-Ubuntu SMP Thu Mar 24 17:21:33 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nckturner** [comment]
/triage accepted

I don't think the `node.cloudprovider.kubernetes.io/uninitialized` taint can be added to clusters without the flag passed, because that could break legitimate clusters where the flag isn't passed and a CCM isn't run.  I think the messaging is definitely confusing and we need to improve the documentation.  The `--cloud-provider=external` should probably not be deprecated, rather, the flag should specify that passing the values `aws`, .. etc are deprecated.

**Comment by hakman** [comment]
@nckturner Would it be a good idea to have also `--cloud-provider=none` which would make clear the taint wouldn't be applied? I guess it would also be the default.

**Comment by deitch** [comment]
Agreed on cases where you don't need a CCM, that it should not taint them. 

It sounds like it should not be deprecated at all, but rather should have two acceptable values:

- "none" - do not taint, no CCM expected (default)
- "external" - taint, expect CCM 


Is that it?

**Comment by nckturner** [comment]
:+1:  It seems reasonable to have an explicit value for the case with no ccm and no taint, and to make that default.

**Comment by deitch** [comment]
Beyond the future plans, what is the right thing to do for 1.23 and 1.24?

**Comment by nckturner** [comment]
Well, assuming you are running a CCM and are expecting a taint, you should use `--cloud-provider=external`.

**Comment by deitch** [comment]
Even though it is marked as deprecated in 1.23 and supposed to be removed in 1.24?

**Comment by hakman** [comment]
> Even though it is marked as deprecated in 1.23 and supposed to be removed in 1.24?

Probably this should be addressed and cherry-picked in 1.23 and 1.24.

**Comment by nckturner** [comment]
> Probably this should be addressed and cherry-picked in 1.23 and 1.24.

+1.  Let me take a stab at this now.

**Comment by nckturner** [comment]
I didn't change the empty value to "none" yet in the above PR, but its still on the table.  Figured I'd go with minimal change for the first iteration and see what people think.

**Comment by rata** [comment]
I think we can close this now that #121367 is merged?

**Comment by rata** [comment]
Any reason this is only a CLI flag and not in the kubelet configuration (https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) ?

**Comment by pawcykca** [comment]
> Any reason this is only a CLI flag and not in the kubelet configuration (https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) ?

It would be probably moved/migrated in the future to the kubelet configuration (as many other kubelet CLI flags).

**Comment by aojea** [comment]
> I think we can close this now that #121367 is merged?

/close
