### ISSUE TITLE
Liveness probe failing when the load on the application is maxed

### ISSUE THREAD

**Issue by dalavayi** [kubernetes/kubernetes#110083]
The liveness probe is going into a BAckoff state, when the application is bombarded with 35k rpm, we dont see the same behavior when performing the load with 10k or 15k rpm. What could be a possible reason for this, is the pod stacking all the readiness/liveness probe requests and only responding to app requests or how is it. please correct me if it doesnt make sense

**Comment by fenngwd** [comment]
It's more easier for us to understand what kind of problem you are facing if you attach more details in description. Please attach more details according issue template guide.

**Comment by matthyx** [comment]
@dalavayi I don't see this being a kubelet bug... if you application treats all requests (user workload and probes) in the same queue, then it will take longer and longer to respond and eventually be killed.
One way of solving this is to prioritize liveness probes over the rest of the traffic.

**Comment by matthyx** [comment]
Please reopen if it's a real bug.
/close
