### ISSUE TITLE
Rollback ResourceQuota changes in admission if persisting to etcd fails

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#110080]
### What happened?

In our cluster, we encountered an issue below:
The ResourceQuota `status.used` showed:
```
status:
  used:
    configmaps: "10"
    services: "10"
    ...
```

But when we got the actual `svc` or `cm` count, they were just:
```
configmaps: "1"
services: "1"
```

After debugging the mismatch, we found that it is the apiserver `Create()` with `QuotaAdmission` would +1 (`UpdateQuotaStatus`) every time, even if the `Create()` returned err.

https://github.com/kubernetes/kubernetes/blob/c84d0864ddebbd0d36ce295cf74a447f24d7b3ec/staging/src/k8s.io/apiserver/pkg/admission/plugin/resourcequota/controller.go#L275-L278

In the `resource_quota_controller`, if the resyncPeriod > 0, will do a full recalculation across all quotas, then the mismatched `status.used` will be consistent with the actual resource num.

https://github.com/kubernetes/kubernetes/blob/c84d0864ddebbd0d36ce295cf74a447f24d7b3ec/pkg/controller/resourcequota/resource_quota_controller.go#L289-L294

### What did you expect to happen?

Check apiserver `Create()` return err, if err not nil, then should do the rollback (-1) logic with the quota.
To keep the ResourceQuota `status.used` consistent with actual resource num.

### How can we reproduce it (as minimally and precisely as possible)?

In the controller logic, call the apiserver `Create()` many times with the same resource, ignore the `IsAlreadyExists` error,
then we can check the mismatch between the ResourceQuota `status.used` and the actual resource num.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.23", GitCommit:"6581e1d61d266ea835f1f051122cccbc715c542f", GitTreeState:"clean", BuildDate:"2022-03-15T09:25:31Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```

</details>

**Comment by roycaihw** [comment]
Thanks for reporting @astraw99! Would you like to send a PR to fix the issue?

**Comment by liggitt** [comment]
This is currently working as designed, there is no rollback hook for admission on etcd write errors. There is a reconciliation controller that periodically sweeps resources and corrects overallocated quota usage. Are you seeing that happen or is it permanently stuck with high usage?

**Comment by astraw99** [comment]
> This is currently working as designed, there is no rollback hook for admission on etcd write errors. There is a reconciliation controller that periodically sweeps resources and corrects overallocated quota usage. Are you seeing that happen or is it permanently stuck with high usage?

Yes, In the `resource_quota_controller`, if the resyncPeriod > 0, will do a full recalculation across all quotas, then the mismatched status.used will be consistent with the actual resource num.

So it is the gap between the resyncPeriod or if resyncPeriod = 0, then the mismatch will occur.

**Comment by astraw99** [comment]
@liggitt Trying to fix it by https://github.com/kubernetes/kubernetes/pull/110153
PTAL thanks.

**Comment by fenngwd** [comment]
As @liggitt said, there is no rollback hook for admission on etcd write errors. IMHO, the way using reconciliation controller to sweep usage is more general and understandable than doing rollback in some specific situation.

**Comment by sftim** [comment]
Rather than rollback, perhaps the API server could track and update a hint about when to schedule the next sweep? (for example: a heuristic to bring the sweep forward, if the last sweep was a no-op and a request to persists has failed).]

_I didn't look to see if something like this is already implemented_
