### ISSUE TITLE
undeprecate kubelet --provider-id flag

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#110041]
### What would you like to be added?

Un-deperecate the `--provider-id` kubelet flag, as this option is typically set per-node similar to `--node-ip` (which is not deprecated).

Or more generally, consider not deprecating fields available in config that make sense to set per-node.

### Why is this needed?

I noticed this while trying to ensure KIND moves towards not setting any deprecated flags, this one is tricky because it's not a fixed value.
https://github.com/kubernetes-sigs/kind/pull/2764

For a lot of kubernetes users, kubeadm is used for bootstrapping, and kubeadm supports supplying additional kubelet flags when configuring each node, but the kubelet config is cluster-wide, created during setting up the first node and uploaded to a configmap then used for all nodes.

In the future kubeadm may have the ability to do per-node kubelet config, but that effort will probably be involved and isn't staffed at the moment.

_technically_ you could run kubeadm in phases and then modify the config, but this is more complex to implement.

It's possible this won't be necessary if kubeadm patches can be extended to kubelet which may be a smaller feature change for kubeadm, but personally I think being able to configure simple per-node strings with a flag override is desirable for implementing clusters, and we've had the flag for many years with no trouble ...

 https://github.com/kubernetes/kubeadm/issues/1682#issuecomment-1124027039

The actual deprecation seems to be due to a blanket deprecation on things possible to set in config, and not targeted at this flag in particular.

See discussion in https://kubernetes.slack.com/archives/C0BP8PW9G/p1652465646070179

**Comment by BenTheElder** [comment]
technically KIND doesn't strictly need this flag, FWIW, but we were asked by users to set it to make detection easier and have values more similar to "real" clusters.

other projects in Kubernetes are also doing this, e.g. some of of the cluster api-provider implementations:
https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/32ed18d5e68fc61f8ba7150d6ddaddf7e47f967a/test/e2e/data/infrastructure-digitalocean/cluster-template-prow-ci-version.yaml#L113

https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/blob/4433897dff2932fa37585159d05cb03d53be273f/config/manager/manager.yaml#L31

**Comment by neolit123** [comment]
I think for 1.25 in kubeadm we can enable patching of kubeletconfuguration. This will allow us to use the current global kubletconfiguration for all nodes, but patches can act as the node instance specific config.

Flags would still take precedence over patches and are the simpler UX.
But if one day all flags are removed the above solution will still support the instance specific use case.

**Comment by pacoxu** [comment]
/assign
It seems to be reasonable. I opened #116530  to undeprecate it.
