### ISSUE TITLE
E2eNode Suite: [sig-node] MirrorPod ... test is flaking on deletion of mirror pod

### ISSUE THREAD

**Issue by xmcqueen** [kubernetes/kubernetes#110074]
### Which jobs are flaking?

prowjob_name: ci-kubernetes-node-kubelet-kubetest2-1-23
prowjob_config_url: https://git.k8s.io/test-infra/config/jobs/kubernetes/sig-release/release-branch-jobs/1.23.yaml

The test failure is related to static-pods, and the deletion of the associated mirror-pod when the static pod is removed.

### Which tests are flaking?

E2eNode Suite: [sig-node] MirrorPod when create a mirror pod without changes should successfully recreate when file is removed and recreated [NodeConformance] 

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-kubetest2-1-23/1525946672201338880

### Since when has it been flaking?

flaking since:
5/12/2022:

first failure:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-kubetest2-1-23/1524676333974589440

job history listing:
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-kubetest2-1-23?buildId=1525039116524195840

### Testgrid link

https://testgrid.k8s.io/sig-release-job-config-errors#node-kubelet-1.23-kubetest2

### Reason for failure (if possible)

The test failure is related to static-pods, and the **deletion of the associated mirror-pod when the static pod is removed.**

#### preliminary analysis:

- **success case** [clearly shows a DELETE call](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-kubetest2-1-23/1525069315961786368/artifacts/60aead4b-d2ac-11ec-b40b-862e9d6d5e5e/test-cos-89-16108-659-8/services.log):

```

I0513 11:20:17.108284    2009 httplog.go:129] "HTTP" verb="DELETE" URI="/api/v1/namespaces/mirror-pod-225/pods/static-pod-e5a41e8d-ed47-4fac-b2bf-824f0fcb4972-test-cos-89-16108-659-8" latency="3.91334ms" userAgent="kubelet/v1.23.7 (linux/amd64) kubernetes/21cde7d" audit-ID="31a5a235-55d3-41ec-a675-9fb03b0b6976" srcIP="127.0.0.1:50180" apf_pl="exempt" apf_fs="exempt" resp=200

```

- **fail case** def no DELETE call in [apiserver logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-kubetest2-1-23/1525946672201338880/artifacts/68802832-d493-11ec-b161-3e13eb6fa348/test-cos-89-16108-659-8/services.log)

### Relevant SIG(s)

/sig-release

**Comment by gjkim42** [comment]
cc

**Comment by xmcqueen** [comment]
After the **second delete** I see this which is wrong:

```
# from the kubelet logs
I0515 21:25:03.731635    1979 pod_workers.go:604] "Pod is terminating but has been requested to restart with same UID, will be reconciled later" pod="mirror-pod-1767/static-pod-8877f9a6-428a-44b3-927d-2782f8ef134f-test-cos-89-16108-659-8" podUID=79d82329
83439e64e23eab37141985f3
```

That log message is also shown **after the first delete**, which is **correct** in that case, because the manifest file was deleted and then recreated (probably much too quickly - there's no wait), so in the moment after the first delete, there is likely already a "requested to restart with same UID".  However, that is **not true for the second delete**.  The second delete should no longer be concerned with the "requested to restart with same UID".  I wonder if the "will be reconciled later" from the first delete is interfering with the proper handling of the second delete.

That might cause the reconcile to think the pod should be running, and thus it might not send the second DELETE for the mirror pod.
