### ISSUE TITLE
Don't change load-balancer endpoint when updating the service

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11002]
Currently, when we change a service with a LoadBalancer, we will often delete the load balancer and create a new one.  If possible, we should not do that: on GCE it may involve temporary service disruption, although the new LB has the same IP.  On AWS a new ELB is created with a different DNS name, so the user must update their DNS settings.

(We have a PR that fixes this #8366, but it is post-v1; I am filing this bug to document the improvement needed, and then changing the tests to test the current state of the world)

**Comment by thockin** [comment]
How is the LB preserved?  #11175 indicates it is NOT preserved, making this higher prio.

**Comment by justinsb** [comment]
We do have an e2e test for this, but perhaps it isn't testing what I think it is.  #11030 highlights that we definitely don't preserve it on AWS, but the test should be checking that it is preserved on GCE.
