### ISSUE TITLE
kubelet: fix to prevent concurrent map read and map

### ISSUE THREAD

**Issue by gaohuatao-1** [kubernetes/kubernetes#110084]
### What happened?

When we add custom annotations to PodSandboxConfig.Annotations in function generatePodSandboxConfig， kubelet crashes with errror:
kubelet[2257292]: fatal error: concurrent map read and map write

The role of function generatePodSandboxConfig(located at kuberuntime_sandbox.go) is to create SandboxConfig that is used to RunSandbox. In some scenarios, we want to pass custom annotations to runtime  through PodsandboxConfig.Annotations .

In kubelet,  multiple goroutins access *v1.Pod fetched from podManager at the same time with no lock. For example, syncPod goroutin and  volumeManager goroutin get *v1.Pod from podManager， when there is  writing pod.Annotations operations,  kubelet will panic.

So, in function generatePodSandboxConfig，a deep copy of pod.Annotations  should be performed.

### What did you expect to happen?

Kubelet process won't panic when we add custom annotations to PodSandboxConfig.

### How can we reproduce it (as minimally and precisely as possible)?

Writing podSandboxConfig.Annotations in function generatePodSandboxConfig 

### Kubernetes version

kubelet  v1.20.0

### Cloud provider

None

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gaohuatao-1** [comment]
![image](https://user-images.githubusercontent.com/22569211/168804092-7f9e17eb-144f-4150-b65b-6502a72c28ec.png)

The function newPodLables and function newPodAnnotations have different copy methods， what is the reason for this?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

Does it repro on older versions of K8s? 1.20 is out of support and reasonably old, perhaps the logic was already fixed.

**Comment by SergeyKanzhelev** [comment]
is it failing on specific fork of k8s? Would be great if you can reference the code that is failing, like @endocrimes mentioned - panic message will help very much

**Comment by gaohuatao-1** [comment]
> /triage needs-information
> 
> Does it repro on older versions of K8s? 1.20 is out of support and reasonably old, perhaps the logic was already fixed.

Yes， we fork from v1.20 , but  the latest version has the same problem.  When we add custom key-value to pod.Annotations in generatePodSandboxConfig func， the panic will trigger.

**Comment by gaohuatao-1** [comment]
> 

In some scenarios, the user will add custom key-value to pod.Annotations in generatePodSandboxConfig func and pass them to the runtime， such as containerd.

**Comment by endocrimes** [comment]
You should probably handle this in your fork rather than here - We won't be backporting that far back, and we don't expect annotations to mutate here.

/close
