### ISSUE TITLE
Prevent scheduler framework changes from breaking Cluster Autoscaler

### ISSUE THREAD

**Issue by x13n** [kubernetes/kubernetes#110186]
### What would you like to be added?

Unit test that will ensure that Cluster Autoscaler objects that currently implement interfaces from https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/listers.go stay that way. It would suffice to do add compile-time checks for the following types:
- [BasicClusterSnapshot](https://github.com/kubernetes/autoscaler/blob/e3ad872747917613f8c132cf22c7cd9b0eca9915/cluster-autoscaler/simulator/basic_cluster_snapshot.go)
- [DeltaClusterSnapshot](https://github.com/kubernetes/autoscaler/blob/e3ad872747917613f8c132cf22c7cd9b0eca9915/cluster-autoscaler/simulator/delta_cluster_snapshot.go)
- [DelegatingSharedLister](https://github.com/kubernetes/autoscaler/blob/e3ad872747917613f8c132cf22c7cd9b0eca9915/cluster-autoscaler/simulator/delegating_shared_lister.go)

Interface changes could still be introduced in a PR against k/k repo, but they would require Cluster Autoscaler changes first to be merged before the interface change itself is merged.

To avoid circular dependency issues, the unit test itself would have to live in a separate module inside k/k repo, importing both scheduler interfaces and CA implementations.

### Why is this needed?

Scheduler framework is an API used for communication between Cluster Autoscaler and Scheduler code. Since it is not a versioned API, it is easy to introduce changes that are backwards incompatible, which is exactly what happened recently in https://github.com/kubernetes/kubernetes/pull/109715. Ensuring interface compatibility in core k8s repo will prevent accidentally breaking Cluster Autoscaler code.

@ahg-g @Huang-Wei @MaciekPytel

**Comment by MaciekPytel** [comment]
I'm +1 and based on the discussion on last sig-autoscaling meeting the idea has a wide support in the sig-autoscaling. One question: shouldn't we also cover [SchedulerBasedPredicateChecker](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L36)?

**Comment by x13n** [comment]
Good point, CA is not only implementing scheduler interfaces, but also calling them, I think it makes sense to extend the scope to include [SchedulerBasedPredicateChecker](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/simulator/scheduler_based_predicates_checker.go#L36) in a compile-time check.

**Comment by Huang-Wei** [comment]
> Interface changes could still be introduced in a PR against k/k repo, but they would require Cluster Autoscaler changes first to be merged before the interface change itself is merged.

I understand the intention to prevent CA's code to be broken, however, the "CA's change first" strategy doesn't sound that practical as (1) that would require k/k to vendor CA's code, and (2) the "preventive changes" in CA doesn't really get verified at runtime/compilation time as the upstream changes are not merged yet.

Given no matter what kind of changes go first, the scheduler framework changes need to get CA team involved. I'd suggest we continue to follow this rule, which works well all the time and is just violated once in #109715. In addition to the early involvement in the k/k PR's review, we can setup additional CI check in CA's side, so when [bumping](https://github.com/kubernetes/autoscaler/blob/a5a3052b24102edbafc2fa6681678ff78b8eb579/cluster-autoscaler/go.mod#L44) the deps in CA, the CI should have [failed](https://github.com/kubernetes/autoscaler/pull/4858) (which isn't today).

**Comment by x13n** [comment]
> I understand the intention to prevent CA's code to be broken, however, the "CA's change first" strategy doesn't sound that practical as (1) that would require k/k to vendor CA's code, and (2) the "preventive changes" in CA doesn't really get verified at runtime/compilation time as the upstream changes are not merged yet.

Good point that we wouldn't be able to verify the code on CA side does indeed implement the updated interface.

> Given no matter what kind of changes go first, the scheduler framework changes need to get CA team involved. I'd suggest we continue to follow this rule, which works well all the time and is just violated once in #109715.

That might be sufficient, I'm just worried that this is not an automated process and hence can be skipped again. Is there anything we could do to limit the possibility of human error? My best idea here so far is to add sig-autoscaling as reviewers for framework changes. Or perhaps a subset of sig-autoscaling members that are cluster-autoscaler maintainers (as opposed to, for example, VPA).

> In addition to the early involvement in the k/k PR's review, we can setup additional CI check in CA's side, so when [bumping](https://github.com/kubernetes/autoscaler/blob/a5a3052b24102edbafc2fa6681678ff78b8eb579/cluster-autoscaler/go.mod#L44) the deps in CA, the CI should have [failed](https://github.com/kubernetes/autoscaler/pull/4858) (which isn't today).

Actually, tests are already run for CA PRs, so it should already be detectable that way. The problem is that by the point it happens, the interface changes are already merged and there is no way to influence them to be more compatible with CA use case.

**Comment by MaciekPytel** [comment]
> Given no matter what kind of changes go first, the scheduler framework changes need to get CA team involved.

I think this is where unittests could help. The unittest wouldn't mean the interface cannot be changed, it would just provide a signal that sig-autoscaling / Cluster Autoscaler reviewer should be involved. It seems much more reliable than the current system based on scheduler contributors' intuitions on which changes may affect CA.

**Comment by x13n** [comment]
Unit test will block submission, which is more than just letting sig-autoscaling know they should take a look. In that case an integration test would probably make more sense: use GitHub API to pull latest version of kubernetes/autoscaler repo, then use Go compiler libs to try to compile selected files. On breaking interface changes, SIG autoscaling approver would be required to temporarily disable the test and drive adjustments on Cluster Autoscaler side (asynchronously, not blocking development on k/k repo).

Thoughts?

**Comment by ahg-g** [comment]
I think we just need to have tests in k/k that hardcode the CA expectations rather than trying to think how to import CA.

**Comment by Huang-Wei** [comment]
> have tests in k/k that hardcode the CA expectations

Do you mean a slim fake library to simulate CA and other consumers? If so, it may still have gaps with CA. While if we import CA in k/k, again, that may yield a cyclic dependency.

> use GitHub API to pull latest version of kubernetes/autoscaler repo, then use Go compiler libs to try to compile selected files.

That sounds fair to me as it simulates how a consumer consumes the framework. Just not sure how complicated it can be (supposing we don't have similar tests to leverage).

**Comment by ahg-g** [comment]
> Do you mean a slim fake library to simulate CA and other consumers? If so, it may still have gaps with CA. While if we import CA in k/k, again, that may yield a cyclic dependency.

I am hoping that we don't need to "simulate" CA; just their expectations of the framework itself.

**Comment by x13n** [comment]
I like @ahg-h suggestion: Simple test that validates CA expectations of the framework interface, without taking on all the extra complexity stemming from dependencies. This should be sufficient for now and may be replaced by more sophisticated mechanism I described above if needed.

At the very least, it should suffice to create an object and check if it satisfies the framework interface. We can iterate on that later, if needed.

**Comment by kerthcet** [comment]
What about verify the framework at startup like https://github.com/kubernetes/kubernetes/pull/110717, and make CA team as part of the folder reviewer.

**Comment by x13n** [comment]
@kerthcet would you like to finish that PR?

**Comment by kerthcet** [comment]
Sure, quite busy in the past few days. I'll complete this ASAP. Thanks for reminding.

**Comment by x13n** [comment]
Thanks, I left a minor comment on the PR, otherwise LGTM.
