### ISSUE TITLE
fail to start kubelet(1.24) in wsl run with ubuntu22.04

### ISSUE THREAD

**Issue by X-neuron** [kubernetes/kubernetes#110144]
### What happened?

May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.037361    7328 server.go:193] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in t>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.045848    7328 server.go:399] "Kubelet version" kubeletVersion="v1.24.0"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.045848    7328 server.go:399] "Kubelet version" kubeletVersion="v1.24.0"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.045895    7328 server.go:401] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.046191    7328 server.go:813] "Client rotation is on, will bootstrap in background"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.047735    7328 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: W0520 16:59:42.049712    7328 sysinfo.go:203] Nodes topology is not available, providing CPU topology
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.050183    7328 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.051259    7328 server.go:648] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.052164    7328 container_manager_linux.go:262] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.052408    7328 container_manager_linux.go:267] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgrou>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.052592    7328 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.052723    7328 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.052862    7328 state_mem.go:36] "Initialized new in-memory state store"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.055589    7328 kubelet.go:376] "Attempting to sync node with API server"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.055637    7328 kubelet.go:267] "Adding static pod path" path="/etc/kubernetes/manifests"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.055655    7328 kubelet.go:278] "Adding apiserver pod source"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: I0520 16:59:42.055665    7328 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: W0520 16:59:42.058277    7328 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: Get "https://ubuntu:6443/api/v1/nodes?f>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: E0520 16:59:42.058365    7328 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: E0520 16:59:42.063294    7328 remote_runtime.go:168] "Version from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1a>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: E0520 16:59:42.063354    7328 kuberuntime_manager.go:225] "Get runtime version failed" err="get remote runtime typed version failed: rpc error: code = Unimplement>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Error: failed to run Kubelet: failed to create kubelet: get remote runtime typed version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1>
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: Usage:
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]:   kubelet [flags]

### What did you expect to happen?

normal startup

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init --kubernetes-version=v1.24.0 --control-plane-endpoint=ubuntu --pod-network-cidr=10.244.0.0/16  --service-cidr=10.96.0.0/12 --ignore-preflight-errors=all  --v=6

### Kubernetes version

<details>

```console
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:44:24Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
   kubernetes
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux XZ-GSEDAU80BA62 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
#BuildNumber  Caption                           OSArchitecture  Version
19044        Microsoft Windows 10 企业版 LTSC  64 位           10.0.19044
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.5.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Ubuntu 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.771GiB
 Name: XZ-GSEDAU80BA62
 ID: GKPV:RQGU:M7CS:57NE:G2OX:RYDR:6WTX:K6UP:QHHB:BXYU:6YXA:7WIG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://g6ogy192.mirror.aliyuncs.com/
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fenngwd** [comment]
```
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: W0520 16:59:42.058277 7328 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: Get "[https://ubuntu:6443/api/v1/nodes?f>](https://ubuntu:6443/api/v1/nodes?f%3E)
May 20 16:59:42 XZ-GSEDAU80BA62 kubelet[7328]: E0520 16:59:42.058365 7328 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://>

```

It seems control-plane-endpoint didn't get correct name resolution. Section about this in doc may help you to solve this problem. Link below:
[https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#considerations-about-apiserver-advertise-address-and-controlplaneendpoint](url)

**Comment by X-neuron** [comment]
thanks so much,i config the host file to make the name ubuntu map the local IP address.it works well when i use in ubuntu20.04 。if i make --control-plane-endpoint=192.9.168.221.82 .i aslo fails.
```
ping ubuntu
PING ubuntu (192.168.221.82) 56(84) bytes of data.
64 bytes from ubuntu (192.168.221.82): icmp_seq=1 ttl=64 time=0.026 ms
64 bytes from ubuntu (192.168.221.82): icmp_seq=2 ttl=64 time=0.046 ms
```

**Comment by X-neuron** [comment]
1.24 CRI runtime changes

**Comment by yanivpaz** [comment]
@X-neuron can you share what was the issue ?
