### ISSUE TITLE
[RFE] image_locality - Scheduling factor

### ISSUE THREAD

**Issue by dariodsa** [kubernetes/kubernetes#110149]
Hi, 
in default scheduling profile ``LowNodeUtilization``  ``ImageLocality`` is plugin which is taken in the consideration. But, you can only schedule pods and they consists of containers. So if one container has specified ``PullPolicy`` to ``Always`` should ``image_locality`` really been taken in the consideration because you will pull image and not take in consideration local image?
https://github.com/kubernetes/kubernetes/blob/0f8b0e14aeb292deef0c652cd9aab4aaf6da7468/pkg/scheduler/framework/plugins/imagelocality/image_locality.go#L97-L105

I would suggest checking if ``pullPolicy`` for that container is set to ``Always`` and if it is, I would score the same as if the image on the node doesn't exist.

**Comment by dariodsa** [comment]
Yes, either skip it or score it with 0 points. I mean you have to give it a
score, but then it should be equal among all nodes which currently isn't
the case.

**Comment by alculquicondor** [comment]
> > This is not 100% true. kubelet will indeed issue an image pull request down to the CRI, but the CRI might just use its internal cache, if the image didn't change in the image repository.

> from a scheduling perspective though, isn't it a bit weird to always have an implicit preference for certain nodes that have the image even when the user has explicitly configured the pod to not care about that?

Given @sftim's feedback, I'm no longer sure if setting pullPolicy=Always means that the user doesn't care about this scoring.

@dariodsa, can you justify the use case? Have you tried just adjusting the weights in your scheduler configuration to fit your needs? Another alternative would be to make it configurable in the ImageLocality plugin whether or not to ignore pods with pullPolicy=Always. It depends on the container runtime after all. In most scenarios, it would just be a check of the SHA.

**Comment by sftim** [comment]
See https://github.com/kubernetes/kubernetes/pull/110382#issuecomment-1421090891 for my comments.

**Comment by xiaomudk** [comment]
Let me try to supplement the purpose of this PR: 
1. Using PullPolicy `Always` allows for more random scheduling of nodes.
2. In some cases, I cannot modify the scheduler configuration, for example when using cloud vendor's pass platform.
3. Different `deployments` can have more flexible configuration on whether or not they are affected by the `ImageLocality` plugin's scoring.

**Comment by alculquicondor** [comment]
It sounds like we are trying to overload the concept of PullPolicy.

What kind of behavior do you want? spreading or just pure randomness? There is an API dedicated to spreading.

> cloud vendor's pass platform.

Over the years we have made adjustments to the default profile to favor scores that take user input, such as spreading, pod affinity, etc. If you don't use these features, the default profiles tries to provide a balance between availability and fast pod startup.

**Comment by dariodsa** [comment]
To be honest, I do have issues with pods being stuck on a node on which they was scheduled at first time so then I have to set node in unscheduled state to make it run on a different node. I can create new scheduler and said to those pods to use different scheduler, but I opened this issue with a question regarding ``image_locality`` and its purpose. Yes, when ``imagePullPolicy`` is set to ``Always`` that doesn't mean that image will always be pulled from the scratch, but that attribute indicates that I don't care about that. I am fine with a pull procedure and I don't care if it pulls from the registry or it takes it from the cache. So in that case, I don't see why we would favor some nodes over others. So as @xiaomudk said, scheduling in that case wouldn't take imageLocality in the account. 
So my question is why don't we take ``imagePullPolicy`` in consideration. Also, we can take conversation in the different direction when ``imagePullPolicy`` is set to ``Never``. As of now, we give higher priority to the nodes which already have those image, but if we set it to Never we wouldn't we exclude nodes which doesn't have those image. We those are already full, ok pod wouldn't be scheduled, but in that case it wouldn't end up on node that doesn't have it image either. 
But to sum up, @xiaomudk perfectly sumed up my request, thanks.

**Comment by kerthcet** [comment]
Maybe we can treat them separately(when the imagePullPolicy == Always):
1. For images with specified tags, e.g. nginx:v1.14, we'll ignore imagePullPolicy, for we think nginx:v1.14 will not change, we'll prefer the node with the image pulled, but this is not always true when users set like `<branch>:dev` :( .
2. For images with `latest` tag, we'll respect the `Always` policy, and score 0 because we don't know whether the image changes or not, and the diff layer could be bigger or smaller, but now we calculate with the cached latest image size, it could be wrong today. https://github.com/kubernetes/kubernetes/blob/cfa295f5691c6c406da667b6f9883dae714b1798/pkg/scheduler/framework/plugins/imagelocality/image_locality.go#L99-L103

**Comment by sftim** [comment]
I also disagree with hard-coding that `latest` gets special treatment. If you want that for _your_ cluster, this could be a scoring extension.

**Comment by alculquicondor** [comment]
> So my question is why don't we take imagePullPolicy in consideration

Kubernetes is taking it into consideration when deciding whether to pull the image or not. That's what the API was designed for, nothing else.

The behavior for kube-scheduler is best-effort, trying to optimize for fast pod startup, which is what most users would want. Why do you want the pod to run in a different node? In general, pods shouldn't care about where they run.

You are asking for a behavioral change that most users might not benefit from. Hence why I want to understand the use case.

**Comment by dariodsa** [comment]
It is not that I have an issue in real world which I can't fix by adjusting scheduling factors and creating multiple schedulers, but I have an issue with the idea of ``image_locality`` score. I never looked kube-scheduler as something which optimize fast pod startup, but ensure so-so even workload on every node. So in order to ensure even workload, scoring points should indicate that (is node less attractive or more). Image_locality helps that pod can start faster, but also helps other ones which are reusing some of the other layers so that they can start faster also and use less storage space.  
So when we look that calculating ``image_locality`` score does make sense for ordinary cases because it really helps system "overall health". But in case when someone is pulling ``latest`` image, those calculation should be performed because image will be pulled no matter what, so I agree with @kerthcet with his second point, so I think that this issue should involve only that point.

**Comment by alculquicondor** [comment]
>  But in case when someone is pulling latest image, those calculation should be performed because image will be pulled no matter what

Not necessarily. When using a dev image, probably yes, it will pull a new image every time. But when using a production image, latest probably doesn't change that often.

>  ensure so-so even workload on every node.

That's one possible configuration of scheduler. Ultimately it all boils down to what weight you give to each plugin.

**Comment by kerthcet** [comment]
My tradeoff is instead of making potential mistake in scoring(this may happen more often with image tag set with `always`), I prefer to ignore **this factor** totally at that case for we have other factors(plugins) in adjudication.

**Comment by alculquicondor** [comment]
A preference should generally imply a configuration option.

I don't think we can make the call for every user or cloud provider.
