### ISSUE TITLE
Ephemeral container can't work with restricted PodSecurity

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/kubernetes#110126]
### What happened?

I want to start an ephemeral container for a pod under namespace with restricted PodSecurity.
I got following error:
Warning  FailedCreate  59s (x6 over 2m20s)  replicaset-controller  (combined from similar events): Error creating: pods "ephemeral-demo-74d9cfc58f-jbdpg" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "ephemeral-demo" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "ephemeral-demo" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "ephemeral-demo" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "ephemeral-demo" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")        

### What did you expect to happen?

Ephemeral container can be created successfully, an gets default capabilities, just like with PSP.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a "restricted" namepsace.
2. create a pod under that namespace.
3. create a ephemeral container via "kubectl debug".

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kubeadm on a server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux foss-ssc-11 5.1.11-1.el7.elrepo.x86_64 #1 SMP Mon Jun 17 15:51:08 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tonyaw** [comment]
Any comment for this? :-)

**Comment by liggitt** [comment]
/remove-kind bug
/kind support

PodSecurity is non-mutating. When using ephemeral containers in a namespace that is enforcing the restricted PodSecurity level, the ephemeral container must set `securityContext.allowPrivilegeEscalation=false` and `securityContext.capabilities.drop=["ALL"]`

/cc @verb
for visibility in case `kubectl debug` wants to make it easier to create debug containers that comply with the `restricted` policy

/close

**Comment by tonyaw** [comment]
> /remove-kind bug /kind support
> 
> PodSecurity is non-mutating. When using ephemeral containers in a namespace that is enforcing the restricted PodSecurity level, the ephemeral container must set `securityContext.allowPrivilegeEscalation=false` and `securityContext.capabilities.drop=["ALL"]`
> 
> /cc @verb for visibility in case `kubectl debug` wants to make it easier to create debug containers that comply with the `restricted` policy
> 
> /close

How to set it via "kubectl debug"? I didn't see any parameter to set securtiyContext.

**Comment by tonyaw** [comment]
Hello, any comment?

**Comment by tonyaw** [comment]
@verb, Thanks!
With debugging profile support, I assume I can start a "netadmin" ephemeral container  even under restricted psa.
Is it right?

**Comment by tonyaw** [comment]
@verb, another question is if "debugging profile" can interact with other third party projects, such as opagk?

**Comment by verb** [comment]
@tonyaw My understand is that will depend on how you configure PSA. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2579-psp-replacement#exemptions.

I don't know what opagk is so I can't comment on that.

**Comment by tonyaw** [comment]
So "bypassing security policy" is done by "usernames" configured by "exemptions",
"debugging profile" is only used to set ephemeral container securityContext.
Is my current understanding right? ：-）
@liggitt @verb

**Comment by tonyaw** [comment]
Another question is why "debugging profile" doesn't support NET_RAW capability?
Yes, it is default capability for containerd, but not for crio.
How shall I use ping/tcpdump via ephemeral container with crio? I think that shall be a very normal case for network debugging, more than NET_ADMIN. :-)

**Comment by sftim** [comment]
> Could you please help to answer my following question in this issue?

**GitHub is not the right place for support requests.**

Instead, also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

You can also try asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

**Comment by tonyaw** [comment]
I understand.
This issue is opened as bug instead of support first.
As there is already some discussion here, can we use it finish the discussion?
I only have this question left:

> So "bypassing security policy" is done by "usernames" configured by "exemptions", "debugging profile" is only used to set ephemeral container securityContext. Is my current understanding right? ：-） @liggitt @verb

**Comment by jdoylei** [comment]
Just a note for anyone ending up here after trying "kubectl debug" in a namespace with restricted-level PSA: I think the Pull Request https://github.com/kubernetes/kubernetes/pull/114280 is currently working on adding the "restricted" kubectl debug profile, as part of the other issue https://github.com/kubernetes/kubectl/issues/1108 noted here, and it sounds like that "restricted" kubectl debug profile is what will make the restricted-level PSA work with kubectl debug.
