### ISSUE TITLE
kubectl cp fails with absolute path on Windows

### ISSUE THREAD

**Issue by patelr3** [kubernetes/kubernetes#110120]
### What happened?

I tried to copy a file from a running pod to my local machine using `kubectl cp` on Windows. I used the `$HOME` env var in Powershell and it failed to copy saying essentially no local path was specified.

```console
PS C:\> kubectl cp -n namespace -c container pod-0:/usr/lib/os-release C:\Temp\os-release.log
error: one of src or dest must be a local file specification
PS C:\> kubectl cp -n namespace -c container pod-0:/usr/lib/os-release $HOME\os-release.log
error: one of src or dest must be a local file specification
```

Using relative paths works. Also removing the `C:` allows the command to work:

```console
PS C:\> kubectl cp -n namespace -c container pod-0:/usr/lib/os-release \Temp\os-release.log
tar: Removing leading `/' from member names

PS C:\> cat C:\Temp\os-release.log
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### What did you expect to happen?

I expected `kubectl cp` to succeed and copy the file to my local machine using `$HOME` or absolute paths like `C:\Users\me`

### How can we reproduce it (as minimally and precisely as possible)?

1. Start a kubernetes pod (I am using a Ubuntu container)
2. Copy any file from the container to any absolute path on Windows : `kubectl cp -n namespace -c container pod:/etc/os-release C:\Temp\os-release`

### Anything else we need to know?

This applies to Windows environment variables as well, such as `$HOME`. Removing `C:` from the absolute path while in the `C:` drive in powershell **does** work. It seems like the `C:` is causing issues (my guess is that `kubectl` thinks `C` is a pod).

### Kubernetes version

<details>

```console

PS C:\> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.11", GitCommit:"38d3c1f3d5306401bcf39a71bad3b5a5106033d7", GitTreeState:"clean", BuildDate:"2022-03-16T14:02:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
kubeadm, no cloud involved.
</details>

### OS version

<details>

```console
# On Windows:
C:\>wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
22000        Microsoft Windows 11 Enterprise  64-bit          10.0.22000
```

</details>

### Install tools

<details>
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-kubectl-binary-with-curl-on-windows

I installed `kubectl` by downloading the binary and running it from my Downloads folder.
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker://20.10.14
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
If you use a UNC path that is equivalent to `C:\Temp\os-release.log`, does that work OK?

**Comment by marosset** [comment]
> If you use a UNC path that is equivalent to `C:\Temp\os-release.log`, does that work OK?

Yes, I just verified that specifying `c:\temp\foo.log` gives the error indicated about but `\\.\c\temp\foo.log` works OK.

I think `kubectl cp` might need to have do something like https://github.com/kubernetes/kubernetes/blob/1d7cefe9c4b95008487c765107ba8346fb10535e/pkg/volume/util/util.go#L452-L466

/sig cli

**Comment by brianpursley** [comment]
See also https://github.com/kubernetes/kubectl/issues/1225

This is actually not a problem unique to Windows.  Case in point: in Linux, I can create a directory that contains a `:`.

**Comment by Napokue** [comment]
> > If you use a UNC path that is equivalent to `C:\Temp\os-release.log`, does that work OK?
> 
> Yes, I just verified that specifying `c:\temp\foo.log` gives the error indicated about but `\\.\c\temp\foo.log` works OK.
> 
> I think `kubectl cp` might need to have do something like
> 
> https://github.com/kubernetes/kubernetes/blob/1d7cefe9c4b95008487c765107ba8346fb10535e/pkg/volume/util/util.go#L452-L466
> 
> /sig cli

Hello, I am testing the provided solution on my Windows machine with an UNC path. I can't seem to get it working when I want to reference to a file on either my C or D drive with the UNC path notation. Do I need to change settings on my machine? I read on the Windows documentation that this will only work with network drives, is this true?

**Comment by marosset** [comment]
> > > If you use a UNC path that is equivalent to `C:\Temp\os-release.log`, does that work OK?
> > 
> > 
> > Yes, I just verified that specifying `c:\temp\foo.log` gives the error indicated about but `\\.\c\temp\foo.log` works OK.
> > I think `kubectl cp` might need to have do something like
> > https://github.com/kubernetes/kubernetes/blob/1d7cefe9c4b95008487c765107ba8346fb10535e/pkg/volume/util/util.go#L452-L466
> > 
> > /sig cli
> 
> Hello, I am testing the provided solution on my Windows machine with an UNC path. I can't seem to get it working when I want to reference to a file on either my C or D drive with the UNC path notation. Do I need to change settings on my machine? I read on the Windows documentation that this will only work with network drives, is this true?

I'm sorry, it looks like I confused (DOS device paths)[https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#dos-device-paths] with (UNC path)[https://docs.microsoft.com/en-us/dotnet/standard/io/file-path-formats#unc-paths].

The windows file-system APIs do a lot manipulations under the hood and golang adds in some more complexity.

Without any changes I would expect `kubectl cp ... \\.\d\some\file` to work if d:\some\file exists without changing anything on your windows machine.
Does that work?

**Comment by Napokue** [comment]
No unfortunately that does not work with the `kubectl cp` command. A valid pathing would be: `\\.\d:\some\file`, however that doesn't work, as kubectl infers a colon as a pod specifier.

What did work for me was using a valid UNC pathing, that didn't use a colon: `\\localhost\d$\some\file`.

**Comment by mloskot** [comment]
Does this issue also apply to the other direction, i.e. copying from Windows pod?

None of path forms discussed above work for me.

**Comment by profnandaa** [comment]
/remove-lifecycle rotten
Taking a look at this.

**Comment by profnandaa** [comment]
I have tried to repro this issue, perhaps it could just be a case of having clear documentation on how paths are treated between Windows and Linux. So, as to maintain uniformity:

- `\` and treated as `/`
- the path is taken "relative" from the "root", i.e. `/` (sort of an absolute path still), so, need to make it _more absolute_ with drive letters. Drive letters are just a Windows abstraction, the C:\ is actually `\\\\?\\C:\\`;

Here is my example that worked ok:
```powershell
# copying current directory files (had only 1 file) to C:\cptest in the pod
kubectl cp ./ sample testpod-5946f7967-m9rdk:/cptest
```

@marosset -- is it in order to propose some docs update for `kubectl cp --help` ?
<details>
<summary><code>kubectl cp --help</code></summary>

![image](https://user-images.githubusercontent.com/261265/222425907-850a4355-016d-4798-bb09-4a36f903afbb.png)

</details>

**Comment by mloskot** [comment]
@profnandaa and your `testpod-5946f7967-m9rdk` is based on Windows container image (nanoserver, servercore, etc.)?

Trying test like yours, from Windows 11 host, to copy files to Windows-based pods on AKS (Kubernetes 1.25.5), from two types of consoles, using `kubectl` 1.25.4 client:

- Git Bash
    ```
    $ cd /f/tmp/test-110120
    $ cat test.txt
    test
    $ kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:/cptest
    cptest/test.txt: Can't create '\\\\?\\C:\\cptest\\test.txt'
    tar: Error exit delayed from previous errors.
    command terminated with exit code 1
    ```

- PowerShell 7
    
    ```
    > cd F:\tmp\test-110120
    > gc .\test.txt
    test
    > kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:/cptest
    cptest/test.txt: Can't create '\\\\?\\C:\\cptest\\test.txt'
    tar: Error exit delayed from previous errors.
    command terminated with exit code 1
    ```

and it doesn't seem like a matter of docs update to me.

**Comment by profnandaa** [comment]
@mloskot -- looks like you didn't have the `cptest` directory in the pod, can try create it first and then run?

**Comment by mloskot** [comment]
@profnandaa The missing directory was the issue indeed. I somehow assumed `cp` should create it. Thanks.

Copying to volume mounted as drive letter different than `C:` works too:

```
$ kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:D:\\
tar: Removing leading drive letter from member names
```

By the way, all of these seem to work eventually but the `tar` messages may be taken as a warning or a problem:

```
$ kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:/
tar: Removing leading '/' from member names
```

```
$ kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:C:/
tar: Removing leading drive letter from member names
```

```
$ kubectl cp -n default  ./ demo-servercore-9d6cf4dd6-72q2t:C:\\
tar: Removing leading drive letter from member names
```

**Comment by jsturtevant** [comment]
@profnandaa @mloskot Is there more investigation that needs to happen here or did everything get resolved?

**Comment by mloskot** [comment]
@jsturtevant For me, the issue has been addressed with concluding comment from me in https://github.com/kubernetes/kubernetes/issues/110120#issuecomment-1457792114 Thanks!

**Comment by jsturtevant** [comment]
/close 
Based on https://github.com/kubernetes/kubernetes/issues/110120#issuecomment-1673707613
