### ISSUE TITLE
scheduler: move all preCheck to QueueingHint

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#110175]
### What happened?

In our custom plugin, we want to move pods that is unscheduled by the plugin to activeQ/backoffQ when a new Pod is created.
So, we define `EventsToRegister` like this:

```go
func (p *Plugin) EventsToRegister() []framework.ClusterEvent {
	return []framework.ClusterEvent{{
		Resource:   framework.Node,
		ActionType: framework.All,
	}, {
		Resource:   framework.Pod,
		ActionType: framework.All,
	}}
}
```

But, even when a new Pod is created, the Pod that was unscheduled by our custom plugin isn't moved to backoffQ/activeQ.

### What did you expect to happen?

when a new Pod is created, the Pod unscheduled by our custom plugin is moved to backoffQ/activeQ.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a custom plugin that has pod events in EventsToRegister.
2. create a new Pod that the custom plugin will reject.
3. create another new Pod that makes the Pod created in (1) schedulable.
4. you can see the Pod created in (1) isn't scheduled immediately (it should've been scheduled immediately after (3) because (3) should move the Pod created in (1) to activeQ/backoffQ.)

### Anything else we need to know?

If I understand correctly and if it's not expected behavior, this bug has a non-small impact, especially in v1.24 because we change `PodMaxUnschedulableQDuration` to 5 min.
https://github.com/kubernetes/kubernetes/pull/108761

### Kubernetes version

v1.23.4 but I think latest master has the same issue.

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
Maybe it's only on a newly created unscheduled Pod.
We've moved correctly for events related to assigned Pod.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L597

**Comment by sanposhiho** [comment]
And deleting Node events has the same issue...? I guess we need to run `sched.SchedulingQueue.MoveAllToActiveOrBackoffQueue` when some Nodes are deleted.
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/eventhandlers.go#L92-L112

going to investigate more tomorrow 💭

**Comment by sanposhiho** [comment]
Hm, it may be a problem that events related to Node and Pod are not always called when an event occurs. (Even if it's intended behavior, at least we need to write this on the comment of `EventsToRegister`.)

/retitle scheduler: events in `EventsToRegister` related to Pod and Node don't always work

**Comment by sanposhiho** [comment]
Of cource, It's not a serious problem only for custom plugins.
In-tree plugins like `InterPodAffinity` uses the Pod All events. 
`InterPodAffinity`'s `EventsToRegister` wants to move unschedulable Pods (unscheduled by `InterPodAffinity`) to activeQ/backoffQ when a new Pod is created, but I guess that move will not happen by this issue... 🤔 💭

**Comment by sanposhiho** [comment]
To summarize: The problem is "not all events related to Pod or Node don't always make move from unschedulableQ to active/backoffQ and it may not be intended for custom-plugin developers because this behavior isn't even documented."

I think we should move all unschedulable Pods with all Pod and Node events. If concerned about performance degradation, we can extend `EventsToRegister` or `EnqueueExtensions` , for example, to have [`PreEnqueueCheck`](https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L76)?

This problem has a non-small impact, especially in v1.24+ because we change PodMaxUnschedulableQDuration to 5 min.
https://github.com/kubernetes/kubernetes/pull/108761

Let's see the details... ↓

### Assigned Pod's add/update events

We move the unscheduled Pods (rejected by the plugin that has Pod add/update events in `EventsToRegister`) in `AssignedPodAdded` or `AssignedPodUpdated`
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L593-L607

But, the target Pods against this moving are only unschedulable pods which have any affinity term that matches "pod".
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L660-L678

So,,,, users cannot move from unschedulableQ to activeQ/backoffQ with all assignedPod events? 
For example, for Pod Topology Spread (it uses Pod All event in `EventsToRegister`), the new assigned Pod creation may make some Pods, that are rejected by Pod Topology Spread, schedulable. Regardless of whether that unschedulable Pods have any affinity term that matches a newly created assigned pod or not.
Of course this is not just a problem for Pod Topology Spread, it could be a problem for user's custom-plugins.

I guess we should pass all unscheduled Pods to `movePodsToActiveOrBackoffQueue`. Or at least we should document this behavior.

### Assigned Pod's delete events

No issue on this.

https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/eventhandlers.go#L234

### Non-scheduled Pod's add/update/delete events

We don't move the unschedulable Pods with those events at all. That's a problem...  Even when a plugin uses Pod add/update/delete event in `EventsToRegister` and wants to move the rejected Pods with non-scheduled Pod's add/update/delete events, scheduling queue doesn't move the unschedulable Pods with those events.

(In our company, we have the custom plugin for `Gang Scheduling` and the plugin wants the scheduler queye to move the Pods rejected by the plugin from unschedulableQ to active/backoffQ when a new non-scheduled Pod is created.)

### Node's add/update events

We move only unscheduled Pods that pass `preCheckForNode`.
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/eventhandlers.go#L70
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/eventhandlers.go#L88
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/eventhandlers.go#L474-L483

`preCheckForNode` checks the Node can run that unscheduled Pod from the points of view of some in-tree filter plugins like noderesources/nodeport/nodeAffinity/nodename.

The problem that arises here is similar to "Assigned Pod's add/update events". 
For example, for Pod Topology Spread (it uses Node Add event in `EventsToRegister`), the new Node creation may make some Pods, that are rejected by Pod Topology Spread, schedulable. Regardless of the results of `preCheckForNode` against that Node. (In https://github.com/kubernetes/kubernetes/pull/107009, we change the skew calculation of Pod Topology Spread to exclude Nodes that don't match the node affinity. But, after [NodeInclusionPolicy](https://github.com/kubernetes/enhancements/issues/3094) is implemented, the calculation can be configured to include those Nodes.)

### Node's delete events

We don't move the unschedulable Pods with Node delete events... That's a problem. Even when the plugin use Node delete event in `EventsToRegister`, scheduling queue doesn't move the unschedulable Pods with any Node delete events.)

**Comment by sanposhiho** [comment]
/cc @Huang-Wei @alculquicondor @ahg-g 

Could you please take a look

**Comment by sanposhiho** [comment]
> +1 on documenting the behavior, but I'm not sure about changing it or making it configurable (that adds complexity that might not be justified).
What is it that you are trying to do?

We want to remove flushing in queue in https://github.com/kubernetes/kubernetes/issues/87850, right?

Without improving like I suggest, some Pods in unschedulableQ cannot move back to activeQ forever in some cases. 
(Actually, our company's custom plugin needs to wait flush because non-assigned Pod's events don't let scheduling queue move unschedulable Pods rejected by that plugin.)
So, I think we should simply inform all events to queue and let queue move unschedulable Pods with that events. 

This can happen in some custom plugins like our company's one and also even in in-tree plugins.
For example, Pod Topology Spread (after [NodeInclusionPolicy](https://github.com/kubernetes/enhancements/issues/3094) is implemented). When a user uses `NodeAffinityPolicy: Ignore` and `WhenUnsatisfiable: DoNotSchedule`, the creation of Node that doesn't match nodeAffinity/nodeSelector may change the scheduling result.

**Comment by alculquicondor** [comment]
cc @kerthcet, who implemented NodeInclusionPolicy.

> For example, Pod Topology Spread (after https://github.com/kubernetes/enhancements/issues/3094 is implemented). When a user uses NodeAffinityPolicy: Ignore and WhenUnsatisfiable: DoNotSchedule, the creation of Node that doesn't match nodeAffinity/nodeSelector may change the scheduling result.

Can you provide a concrete example? The policy just refers to the topology spread calculations. It doesn't mean that the node doesn't have to match the nodeaffinity to be able to accept the pod.

> What is it that you are trying to do?

I'm asking what is your custom plugin trying to do. Depending on whether it makes sense, we need to evaluate if it's worth the complexity.

**Comment by sanposhiho** [comment]
@alculquicondor 

> I'm asking what is your custom plugin trying to do. Depending on whether it makes sense, we need to evaluate if it's worth the complexity.

Our company's custom plugin is like [coscheduling](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling) plugin.

And like coscheduling's prefilter, the plugin rejects Pods in PreFilter when the number of Pods is less than the definition.
https://github.com/kubernetes-sigs/scheduler-plugins/blob/57499a6332c124314020a368c862b8b97470cc11/pkg/coscheduling/coscheduling.go#L128

Yes, so, maybe coscheduling plugin has the same issue as our plugin. It uses Pod Add event and I guess it's for non-scheduled Pod's creation. (I don't know much about the coscheduling plugin though.)
https://github.com/kubernetes-sigs/scheduler-plugins/blob/57499a6332c124314020a368c862b8b97470cc11/pkg/coscheduling/coscheduling.go#L98

@kerthcet 

> The skew of a new created node is always 0, so it's still unfit I think.

Oh, that's true 😓 Forget about that example.
But, how about like this scenario:
1. a user uses `NodeTaintsPolicy: Respect` and `WhenUnsatisfiable: DoNotSchedule`
2. a Pod is rejected by Pod Topology Spread because of the skew. 
3. user adds un-tolerated taint to some Nodes 
4. The skew calculation may be changed but the Pod rejected in (2) isn't moved from unschedulableQ because of this issue.

**Comment by Huang-Wei** [comment]
Thanks @sanposhiho for bringing this up. Some comments below:

> Re: Assigned Pod's add/update events

You're right. Pods failed by PodTopologySpread may not get re-queued immediately.
However, an assigned Pod's add/update event would only impact unschedulable Pods with cross-node
scheduling directives. As of today, it's InterPodAffinity and PodTopologySpread.

So instead of "pass all unscheduled Pods to movePodsToActiveOrBackoffQueue", I'd like
to come up with a solution like:

```go
p.movePodsToActiveOrBackoffQueue(
    p.getUnschedulablePodsWithMatchingAffinityTerm(pod),
    p.getUnschedulablePodsWithPodTopologySpreadConstraints(pod), /* Not Implemented Yet */
    AssignedPodAdd,
) 
```

> Re: Non-scheduled Pod's add/update/delete events

It's pretty rare to move pods depending on **Unschedulable** Pods' events.

In your particular case, maybe a proactive [Activate](https://github.com/kubernetes-sigs/scheduler-plugins/pull/299)
call would behave more efficiently.

> Re: Node's add/update events

It doesn't sound correlated, is it? As the `preCheckForNode` check will just pre-verify the basic
checks which are orthogonal with PodTopologySpread. In other words, it's impossible that a Pod failed
`preCheckForNode` can become schedulable eventually.

> Re: Node's delete events

Can you share some use-cases to move Pods upon node's deletion? In the before, I don't think we have any,
until the last release the introduction of `minDomains` feature (as in that case deleting a node would impact
the number of domains).

**Comment by sanposhiho** [comment]
> So instead of "pass all unscheduled Pods to movePodsToActiveOrBackoffQueue", I'd like
to come up with a solution like:

If we do so, also, we need to provide the way to pass Pods to `movePodsToActiveOrBackoffQueue` like `getUnschedulablePodsWithPodTopologySpreadConstraints` for out-of-tree plugins?

> In your particular case, maybe a proactive https://github.com/kubernetes-sigs/scheduler-plugins/pull/299
call would behave more efficiently.

Ah~, that's a good idea :)

> Can you share some use-cases to move Pods upon node's deletion? 

Maybe like this (similar to https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1141952386)

1. a user uses WhenUnsatisfiable: DoNotSchedule.
2. a Pod is rejected by Pod Topology Spread because of the skew.
e.g. a user uses maxSkew: 1 and TopologyKey is hostname, NodeA/NodeB has 10 Pods each, and NodeC has 8 Pods.
3. user deletes NodeC
4. The skew calculation result should be changed and the Pod rejected in (2) will be allowed by Pod Topology Spread. But the Pod isn't moved from unschedulableQ without flushing because of this issue.

---

> I think we should move all unschedulable Pods with all Pod and Node events. If concerned about performance degradation, we can extend EventsToRegister or EnqueueExtensions , for example, to have the function like [PreEnqueueCheck](https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L76)?

So,,, ignoring some events for performance in scheduler side (without a way to change this) may be inconvenient for some plugins. What I thought in the above previous comment (https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1140397251) is to define "which kind of resource's events should be ignored" in plugin side. 
(similar to @kerthcet 's idea? https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1142202416)

We can add pre filter functions in `ClusterEvent` like:

```go
// obj: the created, updated, or deleted object
// rejectedPod: one of the unschedulable Pod in unschedulableQ
// return value: whether this unschedulable Pod should be moved to activeQ/backoffQ or not.
type PreFilterFn func(obj interface{}, rejectedPod *v1.Pod) bool

type ClusterEvent struct { 
	Resource   GVK
	ActionType ActionType
	Label      string
	// PreFilterFn is the function to check which Pod should be moved from unschedulableQ to activeQ/backoffQ by this event happens.
	PreFilterFn    PreFilterFn
}
```
https://github.com/kubernetes/kubernetes/blob/da7f184344d841807c2da88a92ee96e1de32d97b/pkg/scheduler/framework/types.go#L80-L84

Then we can set any pre-filter functions for each plugin.
And, we can define some default behavior for PreFilterFn and use them when `ClusterEvent.PreFilterFn` is empty.
So, for example, if most of the plugins are considered to prefer to ignore the event for Node that doesn't match nodeAffinity/nodeSelector, we can define this behavior as the default behavior.

**Comment by Huang-Wei** [comment]
> If we do so, also, we need to provide the way to pass some functions to decide which Pods should pass to movePodsToActiveOrBackoffQueue like getUnschedulablePodsWithPodTopologySpreadConstraints for out-of-tree plugins?
> 

Nope, that is something the scheduler core needs to implement.

> Maybe like this (similar to #110175 (comment))
> 
> 1. a user uses WhenUnsatisfiable: DoNotSchedule.
> 2. a Pod is rejected by Pod Topology Spread because of the skew.
> e.g. a user uses maxSkew: 1 and TopologyKey is hostname, NodeA/NodeB has 10 Pods each, and NodeC has 8 Pods.
> 3. user deletes NodeC
> 4. The skew calculation result should be changed and the Pod rejected in (2) will be allowed by Pod Topology Spread. But the Pod isn't moved from unschedulableQ without flushing because of this issue.

Thanks. It makes sense to me.

> What I thought in the above previous comment (https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1140397251) is to define "which kind of resource's events should be ignored" in plugin side.
> 

A customizable PreCheck approach for sure can satisfy more dynamic cases, but it's inappropriate to associate it with ClusterEvent as (1) ClusterEvent is basically an immutable constant, and (2) we use it to [[map](https://github.com/kubernetes/kubernetes/blob/9f82d81e55cafdedab619ea25cabf5d42736dacf/pkg/scheduler/framework/runtime/framework.go#L545-L553)](https://github.com/kubernetes/kubernetes/blob/9f82d81e55cafdedab619ea25cabf5d42736dacf/pkg/scheduler/framework/runtime/framework.go#L545-L553) to plugins. If we go this way, we need to wrap ClusterEvent into another data structure which is kind of complicated.

---

To summarize, the following cases doesn't properly re-queue relevant pods:

1. Assigned Pod's add/update events
2. Non-scheduled Pod's add/update/delete events
3. Node's add/update/delete events

For 1 & 2, I've commented above with solutions. (1 needs core changes similar like podAffinity, 2 may leverage the Activate hook)

For 3, with @sanposhiho 's examples, I'm convinced this is some area we need to improve. One simple and stratightforward solution is to plumb a hook to let the plugin claim "alright, **upon Node events**, move the pod failed by me anyways". Then once this knob is registered, we move pods failed by that plugin back unconditionally; instead of proceeding with  `preCheckForNode()`. This hook should be available to in-tree and out-of-tree plugins. In terms of in-tree plugins, it's just PodTopologySpread (we discussed this in today's sig meeting, even InterPodAffinity doesn't fall into this case)

So, as a first step, let's ensure we're on the same page and agree on the ^^ summary. Next, we can better evaluate trade-offs and come up with an optimal solution.

**Comment by sanposhiho** [comment]
Thanks for discussing this topic in the sig meeting. 🙏 
But, I am still believing that all logic related to a plugin should be controllable from the plugin side and we should not create something that can be achieved in in-tree plugins but not in out-of-tree plugins. 

So... the benefit of the "customizable PreCheck approach" (https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1142836465) isn't only to solve this issue. We can use this feature for other optimization: like improving the whole performance of scheduler by moving only Pods that are more likely to be able to be scheduled by defining more detailed events on `EventToRegister` with customizable PreCheck. 
Many plugins have a particular scenario that makes rejected Pods schedulable and the current `EventsToRegister` doesn't have an abundant enough ability of expression for this. (So, today many plugins need to say "register this hoge event on foo resource. This event ***may*** make rejected Pods schedulable" on comments in `EventsToRegister`. )

>  If we go this way, we need to wrap ClusterEvent into another data structure which is kind of complicated.

Yes, I watched the sig-meeting recording as well and the opinion that the "customizable PreCheck approach" increases some implementation complexity surely makes sense. But,,, isn't this complexity acceptable even if the above is taken into account?

**Comment by sanposhiho** [comment]
I didn't jump in the thread since it's actively on the discussion.
But, the issue https://kubernetes.slack.com/archives/C09TP78DV/p1659383737933799 is the similar one.
(This time, we can solve that issue by changing scheduling queue logic since It's the k/k feature though.)

**Comment by Huang-Wei** [comment]
> This time, we can solve that issue by changing scheduling queue logic since It's the k/k feature though.

@sanposhiho I'm not sure I fully understand your intention. The slack thread was discussing the AssignedPod update case, so it fallls into case 1 in https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1145351228, which we already agreed to improve in upstream.

**Comment by kerthcet** [comment]
Hi @sanposhiho Are you working on this? I think this is quite important and if you're not working on this, I can follow.

**Comment by sanposhiho** [comment]
Sorry, leave here for a while. I wanted to wait for [KEP-3521: Pod Scheduling Readiness](https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3521-pod-scheduling-readiness) (and then forgot to come back here. 😓 )
That proposal is quite similar to what I want to see in the conclusion of this issue; every plugin can judge if each Pod in unschedQ can be moved to schedQ/backoffQ. 

@Huang-Wei Do you think it makes sense to add "By which event is that pod going to be moved back to schedQ/backoffQ" on `PreEnqueue`'s argument?

```
type EnqueuePlugin interface {
    Plugin
    // event: By which event is that pod will be moved back to schedQ/backoffQ.
    // If the Pod will be backed to schedQ/backoffQ by flushing, it will be nil. (Flushing plans to be removed in https://github.com/kubernetes/kubernetes/issues/87850 though.)
    PreEnqueue(ctx context.Context, state *CycleState, p *v1.Pod, event framework.ClusterEvent) *Status
}
```

I know `event` isn't needed in DefaultEnqueue plugin for `schedulingGates` API, but that's the last missing puzzle piece 🧩 : If `PreEnqueue` has `event`, enqueue plugin can judge if the Pod can be scheduled by this moving back to activeQ.

And, for example, we can move ↓ this logic to Pod Affinity plugin by implementing `PreEnqueue` in Pod Affinity plugin.
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L660-L678

We can resolve (3) by implementing `PreEnqueue` as well. (by exactly the way you said.↓)
> "alright, upon Node events, move the pod failed by me anyways"
https://github.com/kubernetes/kubernetes/issues/110175#issuecomment-1145351228

My original concern in this issue is that having logic for specific plugins in the scheduler core may prevent out-of-tree plugins' extendability. If we can move such logic to each plugin, that'd be perfect.

**Comment by sanposhiho** [comment]
It can be resolved by moving all preCheck into each plugin's QueueingHint. Let me retitle this issue so that the current status is easy to understand.

/retitle scheduler: move all preCheck to QueueingHint
