### ISSUE TITLE
Unnecessary for-loop in apiserver routes installer

### ISSUE THREAD

**Issue by hunknownz** [kubernetes/kubernetes#110254]
In `k8s.io/apiserver/pkg/endpoints/installer.go`:
```go
(a *APIInstaller) registerResourceHandlers(path string, storage rest.Storage, ws *restful.WebService) {
    ...
    for _, action := range actions {
        ...
        routes := []*restful.RouteBuilder{}
        ...
        switch action.Verb {
        case "GET":
            route := ws.GET(action.Path).To(handler)
        ...
        }
        ...
        for _, route := range routes {
            ws.Route(route)
        }
    }
    ...
}
```
I omitted code that is not relevant to this issue. We don't need the `routes` List and the for-loop. There is only one element in `routes` List per iteration.

Please let me make some cleanup if possible.

**Comment by leilajal** [comment]
@hunknownz thank you, are you going to send PR for this clean up?
/triage accepted

**Comment by hunknownz** [comment]
> @hunknownz thank you, are you going to send PR for this clean up? /triage accepted

Yes. Currently I'm working on it.
