### ISSUE TITLE
LoadBalancer&NodePort service cannot access after upgrade from 1.20 to 1.22

### ISSUE THREAD

**Issue by BSWANG** [kubernetes/kubernetes#110208]
### What happened?

LoadBalancer&NodePort service cannot access after upgrade from 1.20 to 1.22.
The `NodeName` field in `v1.endpointslice.endpoint` missed.
![image](https://user-images.githubusercontent.com/3598874/170217712-644f770c-bed6-412d-94fb-b2c2369fd303.png)

The convertion in apiserver emit the field `Topology` in `v1beta1.endpointslice` and not convert to field `NodeName` in `v1.endpointslice`.

And the `kube-proxy` on 1.22 only use the `NodeName` field to judge whether the endpoint is `Local`. So `kube-proxy` on each node removed the endpoint from NodePort. Then LoadBalancer&NodePort network broken.  

### What did you expect to happen?

The `LoadBalancer&NodePort` network should not broken duration upgrade. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create 1.20 cluster.
2. Craete LoadBalancer Service with `ExterernalTrafficPolicy` setting to `Local`
3. Upgrade the cluster.
4. Observe the cluster's LoadBalancer networking.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.3-aliyun.1", GitCommit:"7a509a37c6f3b8f82175df3fb149974999882a54", GitTreeState:"clean", BuildDate:"2022-05-24T08:59:55Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
alibabacloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BSWANG** [comment]
https://stackoverflow.com/questions/70803653/kube-proxy-upgrade-from-1-21-to-1-22-insert-wrong-iptables-rule

**Comment by aojea** [comment]
We need a few more details on the reproducer
```
1. Create 1.20 cluster.
2. Create LoadBalancer Service with ExterernalTrafficPolicy setting to Local
3. Upgrade the cluster.
4. Observe the cluster's LoadBalancer networking.
```

Are you upgrading directly from 1.20 to 1.22? I don't know if there is something written about that but I don't remember that skipping versions are supported, we should double check it

Precisely, the migration of the topology field was done in 1.21 https://github.com/kubernetes/kubernetes/blob/20deba3dcd274b237d3199fde1d4bb187cc4ee9b/CHANGELOG/CHANGELOG-1.21.md

> The EndpointSlice Controllers are now GA. The EndpointSliceController will not populate the deprecatedTopology field and will only provide topology information through the zone and nodeName fields. (https://github.com/kubernetes/kubernetes/pull/99870, [@swetharepakula](https://github.com/swetharepakula))

If you can provide a more exact reproducer we should be able to determine if is a real bug or a consequence of a deprecated field

**Comment by BSWANG** [comment]
@aojea Thank for your reply.
The `EndpointSliceNodeName` is the migration mechanism in 1.21 version. But `EndpointSliceNodeName` only take effort on `endpointslice` changing(Add|Update).

If the upgrade step follow 1.20->1.21->1.22. And we do **nothing** to make the `endpointslice`  change on the 1.21 stage. The `nodename` field will still not be populated. And we will also meet this issue after upgraded to 1.22.

**Comment by aojea** [comment]
@liggitt does it mean that we have to do the same that we did here https://github.com/kubernetes/kubernetes/pull/108198 on reads?

**Comment by BSWANG** [comment]
https://github.com/kubernetes/kubernetes/pull/108198 convert others endpoints on `endpointslice` be updating. IMO, we should convert `topology` on get&watch to prevent `kube-proxy|cloud-controller-manager` obtain wrong `nodename` info.

**Comment by liggitt** [comment]
I think it means kube-proxy should still be using the topology[hostname] label if the nodeName field is empty

**Comment by BSWANG** [comment]
> I think it means kube-proxy should still be using the topology[hostname] label if the nodeName field is empty

The topology field become `deprecated` and will be removed someday.

The topology[zone] label will be converted to `zone` fiele on "get|watch". But topology[hostname] not converted 😅.

**Comment by liggitt** [comment]
I think the problem is bounded to 1.22

* EndpointSlices written >= 1.21 (specifically 1.21.11 with https://github.com/kubernetes/kubernetes/pull/108203) does not encounter this problem.
EndpointSlices that have not been written to >= 1.21 should shrink to ~zero by ~1.23:
* A 1.20 control plane only supports 1.18, 1.19, and 1.20 nodes
* A 1.23 control plane only supports 1.21+ nodes. That means all pods running against a 1.20 control plane and informing EndpointSlices have to be recreated and rescheduled by 1.23, triggering writes to their endpointslices.

Prior to 1.22, kube-proxy would fall back to the hostname label if the field was not set. That fallback was removed in 1.22 in https://github.com/kubernetes/kubernetes/pull/103306/files#diff-c2324126e8fa925fee94137c7f127001cfffa3132c6eb7aa14f32e4c023ba64eL284-L288

Restoring that fallback narrowly to 1.22 kube-proxy seems sufficient.

**Comment by BSWANG** [comment]
> I think the problem is bounded to 1.22
> 
> * EndpointSlices written >= 1.21 (specifically 1.21.11 with [Automated cherry pick of #108198: Updating EndpointSlice strategy to retain node name in #108203](https://github.com/kubernetes/kubernetes/pull/108203)) does not encounter this problem.
>   EndpointSlices that have not been written to >= 1.21 should shrink to ~zero by ~1.23:
>   
>   * A 1.20 control plane only supports 1.18, 1.19, and 1.20 nodes
>   * A 1.23 control plane only supports 1.21+ nodes. That means all pods running against a 1.20 control plane and informing EndpointSlices have to be recreated and rescheduled by 1.23, triggering writes to their endpointslices.
> * Prior to 1.22, kube-proxy would fall back to the hostname label if the field was not set.
>   
>   * That fallback was removed in 1.22 in https://github.com/kubernetes/kubernetes/pull/103306/files#diff-c2324126e8fa925fee94137c7f127001cfffa3132c6eb7aa14f32e4c023ba64eL284-L288
> 
> Restoring that fallback narrowly to 1.22 kube-proxy seems sufficient.

Maybe all `cloud-controller-manager` which using `discovery.v1` also need the fallback on 1.22, for add the node to Loadbalancer backend.

**Comment by aojea** [comment]
> Maybe all `cloud-controller-manager` which using `discovery.v1` also need the fallback on 1.22, for add the node to Loadbalancer backend.

I didn't find any reference , where do you see that?

**Comment by BSWANG** [comment]
> > Maybe all `cloud-controller-manager` which using `discovery.v1` also need the fallback on 1.22, for add the node to Loadbalancer backend.
> 
> I didn't find any reference , where do you see that?

https://github.com/kubernetes/cloud-provider-alibaba-cloud/blob/f821effa31935d135809a76731b29ec45afc11b4/pkg/controller/service/vgroups.go#L674

**Comment by aojea** [comment]
both are still using v1beta1, right?

**Comment by BSWANG** [comment]
> both are still using v1beta1, right?

Yes, but they will met this issue when upgrade to v1. Shall we convert `hostname` in `apiserver` like `zone` field, then the others controller will no need to convert once again on upgrading api.

**Comment by aojea** [comment]
> > both are still using v1beta1, right?
> 
> Yes, but they will met this issue when upgrade to v1. Shall we convert `hostname` in `apiserver` like `zone` field, then the others controller will no need to convert once again on upgrading api.

I have doubts those will support 1.20 when they move to v1, however, as Jordan explained, https://github.com/kubernetes/kubernetes/issues/110208#issuecomment-1138542097, they should handle it themselves the same that kube-proxy is doing, there is a DeprecatedTopology field for dealing with that
