### ISSUE TITLE
YAML verfier at API-Server

### ISSUE THREAD

**Issue by kitarp29** [kubernetes/kubernetes#110248]
I am not sure if this is already a feature on not.
I want to build a YAML Validator at API - Server level.
If this seems like a good idea, I would like to work on it.

I have experienced at work that sometimes the cluster faces issues because the YAML applied had some issues.
This was the sole reason many services got hit.
We can always have a wrapper on top of it. But why not make this feature inside Kubernetes only?

Looking forward to work on it :)

**Comment by kitarp29** [comment]
cc: @brosner @gnufied

**Comment by kitarp29** [comment]
A simple implementation like this: https://codebeautify.org/yaml-validator
We can return the error messages on the CLI itself.

**Comment by kitarp29** [comment]
Hi @neolit123 
Sorry for the stupid question but where can I learn about these tags the bots and you used?

**Comment by neolit123** [comment]
hi, the commands are here:
https://prow.k8s.io/command-help

for more questions on how these work, you can ask in #sig-testing on k8s slack.

**Comment by leilajal** [comment]
thanks @kitarp29 for working on this.
/triage accepted

**Comment by apelisse** [comment]
I think that's what @kevindelgado has done, but I'm really not sure what you're trying to accomplish.

Can you give an example of the experience you're looking for? What are the commands you would run and what would the output be?

**Comment by kitarp29** [comment]
Suppose I apply a new YAML, which has some syntax error.
So, before actually sending the broken YAML to the next step the API Server could tell the user that the YAML is broken at this line.

I had broken a cluster once because I had used an extra space in the YAML.

**Comment by apelisse** [comment]
Yeah, I think that's what we fixed, tell me if that makes sense:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/2885-server-side-unknown-field-validation

**Comment by kitarp29** [comment]
Yes @apelisse, it looks like this covers most of what I had in my mind.
But still, is it checking for a syntax error in YAML or JSON files?

It is checking for fields but could not see anything that checks the syntax.

**Comment by apelisse** [comment]
Invalid YAML or JSON are already rejected, there's nothing we can do with an invalid payload anyway, so we should be good to go with this.

In your specific example with the extra-whitespace in yaml, the problem is that it's still a valid yaml, but this will usually fail because of an unknown field now.

**Comment by kitarp29** [comment]
Ok, if this feature is already implemented.
Should I close this issue?

**Comment by apelisse** [comment]
Problem solved!
/close
