### ISSUE TITLE
I met unexpectedamissionedError when I used BestEffort which is kubelet's topology policy

### ISSUE THREAD

**Issue by wangzihao05** [kubernetes/kubernetes#110216]
### What happened?

The question is that I schedulered a pod that to a node. The node's topology policy is best-effort.The node has two numa nodes ,the information as follows 

numa node1 memory:
capacity: 16000000000
available: 14000000000

numa node2 memory:
capacity: 16000000000
available: 14000000000

the pod information as follows:

memory: 15000000000

Then the pod's state is unexpectedamissionedError. The pod's error message is that failed to find numa nodes to extend the current topology hint.

### What did you expect to happen?

pod runs successfully

### How can we reproduce it (as minimally and precisely as possible)?

prepare the environment as above,and prepare a pod and create it 
Set the kublet topology manager policy is best-effort

### Anything else we need to know?

But the condition as follow that pod successfully runs.

numa node1 memory:

capacity: 16000000000
available: 14000000000

numa node2 memory:
capacity: 16000000000
available: 14000000000

pod memory: 17000000000

So why  situation that pod memory more than numa node memory capacity ran successfully. But the question I met failed.
Is the memory situation I met a bug? And Why?

### Kubernetes version

 1.23.5

### Cloud provider

<details>

</details>

### OS version

VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/assign @fromanirh 

to triage

**Comment by SergeyKanzhelev** [comment]
@fromanirh any updates on triaging this bug?

/cc @swatisehgal

**Comment by wangzihao05** [comment]
Sorry ,I found that it is not a bug.Memory manager is different from cpu manager.To prevent oom ,the groups of NUMA nodes must be disjoint for memory manager.The following website explains that.

[https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1769-memory-manager#design-overview](url)

**Comment by fromanirh** [comment]
/close
because https://github.com/kubernetes/kubernetes/issues/110216#issuecomment-1157142893
