### ISSUE TITLE
kube-proxy, kube-dns issue

### ISSUE THREAD

**Issue by 3siksfather** [kubernetes/kubernetes#110299]
### What happened?

I have two issues with my kubernetes.
kubernetes version 1.12.5, ubuntu16.04

the first issue is
Occasionally, containers on a specific node are restarted including kube-proxy
```
kernel: IPVS: rr TCP - no destination available
IPVS: __ip_vs_del_service:enter
net_ratelimit: callbacks suppressed
```
As these logs are continuously recorded,
The load avarage of node system resources is rather high.

Docker containers uploaded to the node keep repeating the restart.

In this case, node drain can relieve the symptoms.

the second issue
Certain java-based containers throw "UnknownHostException".

Restarting the container manually will resolve the symptoms.

Should I look at the container deployment settings?
Should I look at the cluster dns, resolve related settings?

I want to know if UnknownHostException is related to dns settings.

Can you give me some good comments?

### What did you expect to happen?

When a node problem occurs,
Why do some jvm-based containers need to be restarted?

### How can we reproduce it (as minimally and precisely as possible)?

For the second issue
When kube-dns is abnormal
Only jvm based containers get UnknownHostException issue.

### Kubernetes version

<details>

```console
$ kubectl version
v1.12.5
# paste output here
```

</details>

### Cloud provider

<details>
baremetal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
ubuntu 16.04.1 LTS
# paste output here
$ uname -a
# paste output here
4.4.0-112-generic

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker container
18.09.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
please try asking for help on https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
