### ISSUE TITLE
etcd image was too large

### ISSUE THREAD

**Issue by purplegrape** [kubernetes/kubernetes#110224]
### What would you like to be added?

Multiple binary version was found in the official etcd docker images

k8s.gcr.io/etcd        3.5.1-0             25f8c7f3da61c       294MB

sh-5.1# pwd
/usr/bin
sh-5.1# etcd
etcd            etcd-3.1.12     etcd-3.3.17     etcd-3.5.1      etcdctl-3.0.17  etcdctl-3.2.24  etcdctl-3.4.13  
etcd-3.0.17     etcd-3.2.24     etcd-3.4.13     etcdctl         etcdctl-3.1.12  etcdctl-3.3.17  etcdctl-3.5.1   

### Why is this needed?

It could be smaller to save bandwidth

**Comment by MadhavJivrajani** [comment]
/sig release
I think?

**Comment by dims** [comment]
this is by design to allow upgrades and downgrades. belongs to 

/sig api-machinery

**Comment by purplegrape** [comment]
got it,many thanks.
