### ISSUE TITLE
Crash when kubernetes parsing api

### ISSUE THREAD

**Issue by ZxyNull0** [kubernetes/kubernetes#110262]
### What happened?

I just using fuzzing discovered a crash when k8s parsing the api,I don't know if it will affect the usability of K8s，So I submit the rel
evant crash information and files to you, I hope it will be useful to you，[fuzz_api_marshaling.zip](https://github.com/kubernetes/kubernetes/files/8790589/fuzz_api_marshaling.zip)

### What did you expect to happen?

Details can be found in the attachment

### How can we reproduce it (as minimally and precisely as possible)?

Details can be found in the attachment

### Kubernetes version

<details>

```console
$ kubectl version :Latest
# paste output here
```

</details>

### Cloud provider

<details>
Details can be found in the attachment
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux ubuntu 5.4.0-113-generic #127~18.04.1-Ubuntu SMP Wed May 18 15:40:23 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
I cannot find any code in this repo about api_marshaling_fuzzer. It seems to be from https://github.com/cncf/cncf-fuzzing/pull/3.

**Comment by neolit123** [comment]
please reopen if related to this repository.

/close
