### ISSUE TITLE
The apiserver cannot be accessed using the ipv6 type cluster ip, and the tls connection cannot be established

### ISSUE THREAD

**Issue by silenceper** [kubernetes/kubernetes#110231]
### What happened?

In the case of cross-nodes, the apiserver cannot be accessed using the ipv6 type cluster ip, and the tls connection cannot be established.
There are several situations:
- accessing http service is normal Whether on the same node or across nodes
- It is normal to access apiserver cluster ip directly on the master (i have only one master)

tcpdump data:
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/2044558/170519622-43262698-320b-4a9a-a42f-156e4f432382.png">

kube-proxy using ipvs mode

### What did you expect to happen?

normal

### How can we reproduce it (as minimally and precisely as possible)?

A new ipv6 kubernetes cluster

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

Linux ipv6-master 5.4.119-1-tlinux4-0009.2 #1 SMP Wed Apr 6 16:46:40 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

```
Client: Docker Engine - Community
 Version:           19.03.9
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        9d988398e7
 Built:             Fri May 15 00:25:27 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.9
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       9d988398e7
  Built:            Fri May 15 00:24:05 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dcbw** [comment]
@silenceper what is the default ipFamily of your cluster? Can you describe the default apiserver Service so we can double-check the properties?

**Comment by silenceper** [comment]
> @silenceper what is the default ipFamily of your cluster? Can you describe the default apiserver Service so we can double-check the properties?

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-25T10:34:48Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "199"
  uid: 27b2a319-fcb2-462a-880c-8b722bbbac77
spec:
  clusterIP: 2001:db8:1234:5678:8:3:0:1
  clusterIPs:
  - 2001:db8:1234:5678:8:3:0:1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by silenceper** [comment]
@uablrek just curl cluster ip on node :
```
[root@ipv6-node-a ~]# curl -k -g -v https://[2001:db8:1234:5678:8:3:0:1]:443/version 
* About to connect() to 2001:db8:1234:5678:8:3:0:1 port 443 (#0)
*   Trying 2001:db8:1234:5678:8:3:0:1...
* Connected to 2001:db8:1234:5678:8:3:0:1 (2001:db8:1234:5678:8:3:0:1) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb

```

**Comment by uablrek** [comment]
I can access the API-server via the `kubernetes` svc IPv6 address but authorization is required;
```
# APISERVER=https://[fd00:4000::1]:443
# curl --insecure -k -g $APISERVER/version
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
# curl --insecure --header "Authorization: Bearer $TOKEN" $APISERVER/version
{
  "major": "1",
  "minor": "25+",
  "gitVersion": "v1.25.0-alpha.0.639+1e7fa3478ed9de",
  "gitCommit": "1e7fa3478ed9de606b761be4f70be4ca60e6e697",
  "gitTreeState": "clean",
  "buildDate": "2022-05-25T21:00:49Z",
  "goVersion": "go1.18.1",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```
The `--insecure` is required unless you have a (probably self-signed) certificate installed.

**Comment by uablrek** [comment]
Slightly different. It may be important to use a domain-name rather than a raw address for TLS to work;
```
# curl --insecure --header "Authorization: Bearer $TOKEN" https://kubernetes.default.svc.cluster.local/version
{
  "major": "1",
  "minor": "24",
  "gitVersion": "v1.24.1",
  "gitCommit": "3ddd0f45aa91e2f30c70734b175631bec5b5825a",
  "gitTreeState": "clean",
  "buildDate": "2022-05-24T12:18:48Z",
  "goVersion": "go1.18.2",
  "compiler": "gc",
  "platform": "linux/amd64"
}
```

**Comment by uablrek** [comment]
I don't think this is a kubernetes bug.

**Comment by uablrek** [comment]
My `kubernetes` service for the record;
```
# kubectl get svc kubernetes -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-05-26T16:53:17Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "90"
  uid: 9e1df3ae-8d89-480a-9474-47f27f515aa2
spec:
  clusterIP: fd00:4000::1
  clusterIPs:
  - fd00:4000::1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by silenceper** [comment]
> I can access the API-server via the `kubernetes` svc IPv6 address but authorization is required;
> 
> ```
> 
> # APISERVER=https://[fd00:4000::1]:443
> 
> # curl --insecure -k -g $APISERVER/version
> 
> {
> 
>   "kind": "Status",
> 
>   "apiVersion": "v1",
> 
>   "metadata": {},
> 
>   "status": "Failure",
> 
>   "message": "Unauthorized",
> 
>   "reason": "Unauthorized",
> 
>   "code": 401
> 
> # curl --insecure --header "Authorization: Bearer $TOKEN" $APISERVER/version
> 
> {
> 
>   "major": "1",
> 
>   "minor": "25+",
> 
>   "gitVersion": "v1.25.0-alpha.0.639+1e7fa3478ed9de",
> 
>   "gitCommit": "1e7fa3478ed9de606b761be4f70be4ca60e6e697",
> 
>   "gitTreeState": "clean",
> 
>   "buildDate": "2022-05-25T21:00:49Z",
> 
>   "goVersion": "go1.18.1",
> 
>   "compiler": "gc",
> 
>   "platform": "linux/amd64"
> 
> }
> 
> ```
> 
> The `--insecure` is required unless you have a (probably self-signed) certificate installed.

It is not work for me.

**Comment by silenceper** [comment]
To add, I tried it if I switched kube-proxy to iptables, it is normal, but ipvs will not work

**Comment by silenceper** [comment]
After adjusting the master host mtu size, it is normal
