### ISSUE TITLE
When replicas of workload is zero and the minReplicas of HPA is greather than zero, the rescale of HPA controller will not be triggered

### ISSUE THREAD

**Issue by whitebear009** [kubernetes/kubernetes#110278]
### What happened?

I have an HPA object configured with external metrics and I set the minReplicas of HPA to 0. After a while, hpa scales the workload to 0 because it is below the metric threshold
Next, if I set minReplicas of HPA to 1, then the HPA controller will not do anything, and the ScalingActive condition becomes false.

### What did you expect to happen?

In the next step above, if I set minReplicas of HPA to 1, the HPA controller will rescale the corresponding workload to 1.

### How can we reproduce it (as minimally and precisely as possible)?

1. create an hpa object with valid external metric and minReplicas is zero.
![image](https://user-images.githubusercontent.com/98402152/170858876-a022b77d-40fb-40ef-887f-8c5c3569ac74.png)
2.hpa scales the workload to 0 because it is below the metric threshold.
3.then set the minReplicas to 1, the hpa will not do anything.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-eks-0d102a7", GitCommit:"eb09fc479c1b2bfcc35c47416efb36f1b9052d58", GitTreeState:"clean", BuildDate:"2022-02-17T16:36:28Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tencent TKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Tencent Linux"
VERSION="2.4"
ID="tlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.4"
PRETTY_NAME="Tencent Linux 2.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tlinux:linux:2"
HOME_URL="https://tlinux.qq.com/"
$ uname -a
Linux 10-152-0-65 4.14.105-19-0020.1 #1 SMP Fri Apr 23 10:22:59 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Dingshujie** [comment]
pod autoscaler controller mark this resource autoscaling disabled when target resource replicas is zero and minReplicas not equals to zero

**Comment by pbetkier** [comment]
Note that the behaviour you're describing is intended: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#implicit-maintenance-mode-deactivation.
