### ISSUE TITLE
Does Liveness Probe distinguish between error conditions?

### ISSUE THREAD

**Issue by rduser** [kubernetes/kubernetes#110282]
The liveness probe execution can fail in various ways like:
1. non-zero exit code returned by container, 
2. or timeout,
3. or due to an infrastructure error due to which no connection to the container was made though the container itself was healthy.

Do all failures count against the container's threshold?

If so, how can application owner mitigate against this, especially error condition 3

**Comment by kerthcet** [comment]
I think the key point here is that the kubelet/monitor is unaware of the infrastructure error. The liveness probe behaves as expected since the container is out of communication.

**Comment by rduser** [comment]
I see. 
- Are there best practices, that can be adopted to avoid unnecessary restarts?
