### ISSUE TITLE
AWS Classic ELB is created with irrelevant AZs

### ISSUE THREAD

**Issue by aberenshtein** [kubernetes/kubernetes#110281]
/kind bug

**1. What `kops` version are you running? The command `kops version`, will display
 this information.**
1.22.0
**2. What Kubernetes version are you running? `kubectl version` will print the
 version if a cluster is running or provide the Kubernetes version specified as
1.22.3
 a `kops` flag.**

**3. What cloud provider are you using?**
aws

**4. What commands did you run?  What is the simplest way to reproduce this issue?**
create LB service type
Add the "service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true" annotation

**5. What happened after the commands were executed?**
A classic LB was created with 3 AZs. 
Only one of the subnets is relevant (master and worker nodes run on a single AZ)

![Screen Shot 2022-05-29 at 14 33 14](https://user-images.githubusercontent.com/12783883/170866713-ac625531-1f42-4dff-a233-676b1ad9a700.png)

When you run `dig` to resolve the IPs, the application would something get the IP of the irrelevant subnet and could pass traffic to the pods.

**6. What did you expect to happen?**
Only one AZ should be set 

**9. Anything else do we need to know?**
This is a staging cluster, so to save money:
Master nodes are configured to run on a single AZ
Worker nodes are configured to run on a single AZ

Didn't happen on every LB

**Comment by sftim** [comment]
/retitle AWS Classic ELB is created with irrelevant AZs

**Comment by nckturner** [comment]
What's the reason for having: `"service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"`  and also wanting to run on a single AZ? I.e. why enable cross zone load balancing if you don't want it?

**Comment by nckturner** [comment]
/close
I'm going to close this assuming the answer is just don't set `"service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"` if you don't want cross zone load balancing, feel free to reopen if that doesn't work for you.

**Comment by aberenshtein** [comment]
@nckturner this is still a buggy behavior.
How can I be sure that even if I set `service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled": "true"` when I have 3 zones, it will only take the relevant zones. I.e the zones where the masters run
