### ISSUE TITLE
kubelet failed start after config kubeReservedCgroup 

### ISSUE THREAD

**Issue by Huimintai** [kubernetes/kubernetes#110288]
### What happened?

When I config kubeReservedCgroup and kubeReserved in config.yaml for  kube daemon.Kubelet can not start with the following errors:
```
vim /var/lib/kubelet/config.yaml
......
kind: KubeletConfiguration
enforceNodeAllocatable:
  - pods
  - kube-reserved
kubeReserved:
  cpu: 1500m
  memory: 1Gi
kubeReservedCgroup: /system.slice/kubelet.service
systemReserved:
  cpu: 2000m
  memory: 2Gi
......
```

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/11571376/171007506-7608b8fa-cf22-4cb5-a6bf-9242ac27b9ed.png">

I create all the files follow the errors
```
mkdir -p /sys/fs/cgroup/cpuset/kubelet.service.slice
mkdir -p /sys/fs/cgroup/hugetlb/kubelet.service.slice
mkdir -p /sys/fs/cgroup/memory/kubelet.service.slice
mkdir -p /sys/fs/cgroup/cpu,cpuacct/kubelet.service.slice
mkdir -p /sys/fs/cgroup/cpu,cpuacct/kubelet.service.slice
mkdir -p /sys/fs/cgroup/systemd/kubelet.service.slice
mkdir -p /sys/fs/cgroup/pids/kubelet.service.slice
```
Then restart the kubelet.
But the kubelet can not restart with the errors:`Failed to enforce Kube Reserved Cgroup Limits on \"/system.slice/kubelet.service\": Unit kubelet.service.slice is not loaded`.

```shell
5月 30 22:08:20 VM-0-116-centos kubelet[5949]: E0530 22:08:20.149768    5949 kubelet.go:1384] "Failed to start ContainerManager" err="Failed to enforce Kube Reserved Cgroup Limits on \"/system.slice/kubelet.service\": Unit kubelet.service.slice is not loaded."
5月 30 22:08:20 VM-0-116-centos kubelet[5949]: I0530 22:08:20.149788    5949 event.go:291] "Event occurred" object="10.0.0.116" kind="Node" apiVersion="" type="Warning" reason="FailedNodeAllocatableEnforcement" message="Failed to enforce Kube Reserved Cgroup Limits on \"/system.slice/kubelet.service\": Unit kubelet.service.slice is not loaded."
5月 30 22:08:30 VM-0-116-centos systemd[1]: kubelet.service holdoff time over, scheduling restart.
5月 30 22:08:30 VM-0-116-centos systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
5月 30 22:08:30 VM-0-116-centos systemd[1]: Started kubelet: The Kubernetes Node Agent.
```

kubelet try to start logs:
<img width="1533" alt="image" src="https://user-images.githubusercontent.com/11571376/171010750-6dc249e3-41bd-40f6-9fc2-b2742d58a8e1.png">

### What did you expect to happen?

The kubelet can restart successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Config the kubeReservedcgroup 

### Anything else we need to know?

kubectl version: v1.21.4
container engine:containerd
kubelet cgroup driver:systemd
OS: CentOS 7

### Kubernetes version

<details>

```console
$ kubectl version
v1.21.4
```

</details>

### Cloud provider

<details>
/
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux VM-0-116-centos 5.4.119-19-0009.1 #1 SMP Sun Jan 23 23:20:30 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yangjunmyfm192085** [comment]
Hi, @Huimintai, The `kubeReservedCgroup` path you set is `/system.slice/kubelet.service`.  you need to check whether the cgroup directory and files in this path exist?

**Comment by Huimintai** [comment]
> Hi, @Huimintai, The `kubeReservedCgroup` path you set is `/system.slice/kubelet.service`. you need to check whether the cgroup directory and files in this path exist?

How to set the `kubeReservedCgroup` path?

**Comment by Huimintai** [comment]
> Hi, @Huimintai, The `kubeReservedCgroup` path you set is `/system.slice/kubelet.service`. you need to check whether the cgroup directory and files in this path exist?

**Comment by yangjunmyfm192085** [comment]
> kubeReservedCgroup: /system.slice/kubelet.service

1. if you expect something as  `/sys/fs/cgroup/cpuset/kubelet.service.slice`, please set to `kubelet.service.slice`

**Comment by Huimintai** [comment]
> > kubeReservedCgroup: /system.slice/kubelet.service
> 
> 1. if you expect something as  `/sys/fs/cgroup/cpuset/kubelet.service.slice`, please set to `/kubelet.service.slice`

I change the config:
```
kubeReservedCgroup: /kubelet.service.slice
```
But the kubelet still can not restart.
```
5月 30 22:53:42 VM-0-116-centos kubelet[20760]: E0530 22:53:42.174836   20760 kubelet.go:1384] "Failed to start ContainerManager" err="Failed to enforce Kube Reserved Cgroup Limits on \"kubelet.service.slice\": Unit kubelet.service.slice is not loaded."
```

**Comment by yangjunmyfm192085** [comment]
you are right. if your kubelet cgroup path is `/system.slice/kubelet.service`

**Comment by yangjunmyfm192085** [comment]
Anyway, you have to make sure the  `--kube-reserved-cgroup`  path exists

**Comment by Huimintai** [comment]
> Anyway, you have to make sure the `--kube-reserved-cgroup` path exists

So you mean I should create the path when I config the` kube-reserved-cgroup: /system.slice/kubelet.service `:
```
mkdir -p /sys/fs/cgroup/cpuset/system.slice/kubelet.service.slice
mkdir -p /sys/fs/cgroup/hugetlb/system.slice/kubelet.service.slice
mkdir -p /sys/fs/cgroup/memory/system.slice/kubelet.service.slice
mkdir -p /sys/fs/cgroup/cpu,cpuacct/system.slice/kubelet.service.slice
mkdir -p /sys/fs/cgroup/cpu,cpuacctsystem.slice//kubelet.service.slice
mkdir -p /sys/fs/cgroup/systemd/system.slice/kubelet.service.slice
mkdir -p /sys/fs/cgroup/pids/system.slice/kubelet.service.slice
```

**Comment by Huimintai** [comment]
however I config the `kube-reserved-cgroup: /system.slice/kubelet.service`,kubelet still check the original path:
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/11571376/171022011-b686466b-9e78-4f60-bc79-c7ee5d05a88a.png">
Then I create the path follow the kubelet errors,it can not start also:
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/11571376/171022570-6840945f-ce39-4011-beff-f206085a5a68.png">
So how to config the `kube-reserved-cgroup`with systemd kubelet service:<

**Comment by Huimintai** [comment]
> Please set /system.slice/kubelet.service and restart kubelet service

Set `/system.slice/kubelet.service` 
<img width="473" alt="image" src="https://user-images.githubusercontent.com/11571376/171077558-bef0e5a7-485f-4544-8031-ad165524eac5.png">

then create files with `/system.slice/kubelet/service.slice`
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/11571376/171077333-cbfb42a6-6c55-4a73-b3a5-3b8951764d9e.png">
Kubelet still need some paths,then create them:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/11571376/171077413-3df01915-58a2-4924-9f24-494c515e6192.png">
Kubelet can not load the kubelet.service.slice:
<img width="1550" alt="image" src="https://user-images.githubusercontent.com/11571376/171077477-6dccd08f-8a7a-4260-b511-f34d991e7260.png">

**Comment by yangjunmyfm192085** [comment]
The cgroupDriver you configured is systemd?
Can you try `cgroupDriver: cgroupfs`?

**Comment by Huimintai** [comment]
> The cgroupDriver you configured is systemd? Can you try `cgroupDriver: cgroupfs`?

Yes,I use systemd.

**Comment by BenTheElder** [comment]
You should probably use an actual systemd slice to create the directories, instead of manually creating them, then there won't be missing paths and it will integrate properly.
https://www.freedesktop.org/software/systemd/man/systemd.slice.html

When using the systemd cgroupDriver, kubelet will append `.slice` to the specified cgroup roots.

**Comment by tossmilestone** [comment]
We should clarify the difference configuration with cgroupfs and systemd in doc.

**Comment by haitang5445** [comment]
If I configure  " kubeReservedCgroup: / " , no more errors . 
Is there a problem with this configuration?
