### ISSUE TITLE
pod kube-flannel-ds CrashLoopBackOff

### ISSUE THREAD

**Issue by xunyao4dev** [kubernetes/kubernetes#110280]
### What happened?

[root@iZuf63u8n54i0xc42warcaZ ~]# kubectl get pods -n kube-system
NAME                                              READY   STATUS              RESTARTS   AGE
coredns-6d56c8448f-5z5kp                          0/1     ContainerCreating   0          29m
coredns-6d56c8448f-mldqr                          0/1     ContainerCreating   0          29m
etcd-izuf63u8n54i0xc42warcaz                      1/1     Running             0          30m
kube-apiserver-izuf63u8n54i0xc42warcaz            1/1     Running             0          30m
kube-controller-manager-izuf63u8n54i0xc42warcaz   1/1     Running             0          30m
kube-flannel-ds-5w8v2                             0/1     CrashLoopBackOff    9          26m
kube-flannel-ds-v26b9                             0/1     CrashLoopBackOff    9          26m
kube-proxy-ccrwh                                  1/1     Running             0          29m
kube-proxy-kz4jr                                  1/1     Running             0          26m
kube-scheduler-izuf63u8n54i0xc42warcaz            1/1     Running             0          30m

kubectl logs kube-flannel-ds-5w8v2 -n kube-system
I0529 12:51:55.481084       1 main.go:207] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W0529 12:51:55.481143       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0529 12:51:55.581439       1 kube.go:121] Waiting 10m0s for node controller to sync
I0529 12:51:55.581481       1 kube.go:398] Starting kube subnet manager
I0529 12:51:56.581543       1 kube.go:128] Node controller sync successful
I0529 12:51:56.581565       1 main.go:227] Created subnet manager: Kubernetes Subnet Manager - izuf63u8n54i0xc42warcaz
I0529 12:51:56.581570       1 main.go:230] Installing signal handlers
I0529 12:51:56.581692       1 main.go:463] Found network config - Backend type: vxlan
I0529 12:51:56.581713       1 match.go:195] Determining IP address of default interface
E0529 12:51:56.581746       1 main.go:270] Failed to find any valid interface to use: failed to get default interface: protocol not available

### What did you expect to happen?

all pods are Running

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init --apiserver-advertise-address=172.19.32.181 --image-repository registry.aliyuncs.com/google_containers --kubernetes-version v1.19.4 --service-cidr=10.96.0.0/12 --pod-network-cidr=10.244.0.0/16

kubeadm join 172.19.32.181:6443 --token o8kab3.u41l853kl0wiqeat     --discovery-token-ca-cert-hash sha256:96171ec77678a3d822a513cc2f17fe9343b18ff086970704da10e4feb47613ce

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Aliyun ECS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux iZuf63u8n54i0xc42warcaZ 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/kind support

> Failed to find any valid interface to use: failed to get default interface: protocol not available

K8s components need a default route so that they can assing an ip address. You can google "default route ip" for information.

You can also ask for help on support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
