### ISSUE TITLE
Can't start Kubelet with error transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory\

### ISSUE THREAD

**Issue by fmq** [kubernetes/kubernetes#110383]
### What happened?

I'm trying to configure a new nodes server and when I try to join the server to the master the following error appears:

[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: time="2022-06-04T15:40:42Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/containerd/containerd.sock: connect: no such file or directory\""

### What did you expect to happen?

Kubeletes should start and the node should join the master node

### How can we reproduce it (as minimally and precisely as possible)?

Installed containerd and configured according to instruction on:
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd

Configured IPV4
```
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF

sudo modprobe overlay
sudo modprobe br_netfilter

# sysctl params required by setup, params persist across reboots
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF

# Apply sysctl params without reboot
sudo sysctl --system
```
Updated to cgroup2
```
sudo grubby \
  --update-kernel=ALL \
  --args="systemd.unified_cgroup_hierarchy=1"
sudo reboot
```
```
yum install -y containerd.io
containerd config default > /etc/containerd/config.toml
```

Updated config for group driver changed..
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  ...
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
```
and restarted containerd
```
sudo systemctl restart containerd
```
Set selinux to permissive

``` 
sudo setenforce 0
sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
```

Installed Kubeadm, kubectl an dkubelet and enabled kubelet
```
cat <<EOF | sudo tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl
EOF

sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

sudo systemctl enable --now kubelet
```

Tried to join  master node:
```
kubeadm join 172.18.16.5:6443 --token <TOKEN> --discovery-token-ca-cert-hash sha256:<HASH>
```

### Anything else we need to know?

Package kubelet-1.24.1-0.x86_64 already installed and latest version
Package kubeadm-1.24.1-0.x86_64 already installed and latest version
Package kubectl-1.24.1-0.x86_64 already installed and latest version

### Kubernetes version

<details>

```console
$ kubectl version
# Kubernetes v1.24.1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
# Linux <HOSTNAME>.internal.cloudapp.net 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
$containerd --version
containerd containerd.io 1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/remove-kind bug
/kind support documentation

Are you sure containerd is running? The socket path will be created if the service is running.

**Comment by fmq** [comment]
@neolit123 yes, this was my first assumption but it is running.

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/881660/172033991-0b52d639-da38-4e73-bf92-a31a24c7ebb3.png">

I am able to pull images and run a container but the socket is not there, it's only in /run/containerd/containerd.sock

<img width="1299" alt="image" src="https://user-images.githubusercontent.com/881660/172034022-0a7983a6-4b9e-441a-8971-3d57067eb2a5.png">

In my other nodes I have both sock's

<img width="454" alt="image" src="https://user-images.githubusercontent.com/881660/172034061-ec32713a-8bce-48a8-b365-b939bb795c9a.png">

Thanks

**Comment by neolit123** [comment]
That's strange. You can try asking the containerd maintainers as it doesn't seem like a k8s issue.

One workaround might be to symlink on the problem node.

Folks on the support channels might have more ideas
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

Thanks
/close

**Comment by fmq** [comment]
FYI I added 
```
--cri-socket /run/containerd/containerd.sock 
```
to the join command and the node started.

Thanks for your help!

**Comment by neolit123** [comment]
I see /run/containerd/containerd.sock mentioned as the default socket mentioned in a few places but it used to be /var/run/...

https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime

If it changed recently that actually breaks ecosystem tools like kubeadm.

**Comment by fmq** [comment]
Looking into the differences between my servers I think I found the issue.

The default sock for containerd has always been /run/containerd/containerd.sock (I have been going back at the documentation and looking at the config, etc), the thing is that usually /var/run is s symlink to /run but in some templates they are two separate directories ( I'm not that much of an expert in CentOS to know why this is ).

I will correct the symlink issue on my server just for future upgrades but you should really consider, just in case, use /run/.. instead of /var/run/... 

Thanks for your time.

**Comment by neolit123** [comment]
notably, i have not seen complains from other users about this.
kubeadm and the k8s.io docs has been using /var/run for ~14 k8s releases at least.
at this point the migration of existing users is not so trivial.

**Comment by fmq** [comment]
I think it's something particular to my installation and to this particular server because all other servers are configured correctly.

**Comment by pharazon** [comment]
I'm using Ubuntu 24.04, and I'm suspecting that apparmor has something to do with permission denied on symlink of /var/run/containerd/containerd.sock. I managed to fix the error by editing /etc/default/kubelet and adding the following configuration (and then systemctl restart kubelet )  

`KUBELET_EXTRA_ARGS="--container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-endpoint=unix:///run/containerd/containerd.sock"`

Note that if you ps aux |grep kubelet, you see that the container-runtime-endpoint is still /var/run, but it seems that by adding it for the second time as the command line argument overrides the first value.
