### ISSUE TITLE
registry.mirrors conainerd config is deprecated, need to move to hosts.toml based config

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#110312]
In tests and here:
https://github.com/kubernetes/kubernetes/blob/62d9f8ba80f4cc660a88dcc34f56c5c6f7df17ea/cluster/gce/gci/configure-helper.sh#L3086-L3091 containerd config is using deprecated way configuring mirrors. Need to switch to the hosts.toml based approach.

/kind cleanup
/sig node
/area test

**Comment by BenTheElder** [comment]
Is there indication that they plan to remove this in the immediate future?

We are also using it to test registry-sandbox.k8s.io in kops, and in KIND in various places.

The hosts.toml approach appears to require managing additional files, which will probably take API redesign in kops.
cc @hakman

**Comment by SergeyKanzhelev** [comment]
> Is there indication that they plan to remove this in the immediate future?

@mikebrow do you know? I heard that 2.0 will remove all deprecated settings and the timeline is EOY for it.

**Comment by mikebrow** [comment]
Removal of this and other deprecations are not immediate. Yes, we've been considering removing all v1 deprecations when we move to v2, yes perhaps EOY perhaps sometime next year. We've been discussing the possibility of providing migration tooling for config and metadata. It is just as likely we will attempt to carry v1 and early v2 release versions of certain services at the same time to allow for opt in testing. The hosts.toml config is very similar to docker hosts.toml, if that helps.

**Comment by SergeyKanzhelev** [comment]
@BenTheElder I think the key point here there is no going back plans. I filed issue to start planning for this migration in k/k tests.

Other places we have for k/k tests:
- https://github.com/kubernetes/test-infra/blob/4e8fd7c424a4b06a8591cfcc6bb6f472a02d6c70/jobs/e2e_node/containerd/config.toml#L17
- https://github.com/kubernetes/test-infra/blob/0369db169d22c99014e0ff27759e2a72543cae39/prow/test/integration/setup-kind-cluster.sh#L71
- https://github.com/containerd/cri-private/blob/266448830509d303bfb2c11b0185ffada7e9ef5e/cluster/gce/configure.sh#L196


btw, containerd also still has stargz plugin tests that uses it:
- https://github.com/containerd/stargz-snapshotter/blob/469829c1b891694f746b906144859dc1d4eda2d7/script/integration/containerd/config.containerd.toml#L11

**Comment by mikebrow** [comment]
Update.. we are [reviewing a plan change](https://github.com/containerd/containerd/pull/7454) that will likely result in a much longer life span for the containerd 1.6 release (marking 1.6 as an LTS release) with the ability to back port fixes and non breaking changes/features needed for CRI from main to 1.6, thus suitable to k8s client use cases.

**Comment by SergeyKanzhelev** [comment]
> Update.. we are [reviewing a plan change](https://github.com/containerd/containerd/pull/7454) that will likely result in a much longer life span for the containerd 1.6 release (marking 1.6 as an LTS release) with the ability to back port fixes and non breaking changes/features needed for CRI from main to 1.6, thus suitable to k8s client use cases.

Is it still a plan to remove this config in 2.0? If so, we still need to do it so we can test k8s across 1.6 AND 2.0.

**Comment by mikebrow** [comment]
> > Update.. we are [reviewing a plan change](https://github.com/containerd/containerd/pull/7454) that will likely result in a much longer life span for the containerd 1.6 release (marking 1.6 as an LTS release) with the ability to back port fixes and non breaking changes/features needed for CRI from main to 1.6, thus suitable to k8s client use cases.
> 
> Is it still a plan to remove this config in 2.0? If so, we still need to do it so we can test k8s across 1.6 AND 2.0.

Yes still the plan to remove in 2.0.. Don't have everything in place to make that happen though.. Definitely recommended to move to the hosts.toml based format for mirroring.

**Comment by matthyx** [comment]
According to @ameukam we no longer need this config switch between repos, since [k8s.gcr.io](http://k8s.gcr.io/) is deprecated with 1.25, and older branches are being migrated too.
For example 1.22 in https://github.com/kubernetes/kubernetes/pull/113417
/close
