### ISSUE TITLE
Cannot upgrade 32bit nodes from 1.22 to 1.24

### ISSUE THREAD

**Issue by rkojedzinszky** [kubernetes/kubernetes#110342]
### What happened?

Kubelet in 1.23 crashes on 32bit arm architectures (https://github.com/kubernetes/kubernetes/issues/106977). 1.24 has a fix for it, howewer 1.23 still does not. And upgrade procedure is to upgrade from 1.22 to 1.23, then from 1.23 to 1.24, which is now impossible.

### What did you expect to happen?

Expected to upgrade from 1.22 to 1.23 without issues.

### How can we reproduce it (as minimally and precisely as possible)?

Upgrade an 1.22 node to 1.23 on a 32bit architecture, possibly arm.

### Anything else we need to know?

Please backport the fix in 1.24 to 1.23.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:57:43Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-04-13T19:52:02Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux k8s-master01 5.15.42 #5 SMP Wed May 25 12:45:52 UTC 2022 armv7l GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-o 1.22
</details>

**Comment by neolit123** [comment]
> https://github.com/kubernetes/kubernetes/issues/106977

Panics are usually eligible for backport.

You can also try using the 1.24 kubelet directly. It might work depending on features between 22 and 24.

**Comment by SergeyKanzhelev** [comment]
/area cadvisor
/triage accepted

@bobbypage can you please estimate if this is something we can do reasonably easy? Is it this PR https://github.com/google/cadvisor/pull/3042/?

**Comment by SergeyKanzhelev** [comment]
@rkojedzinszky have you been able to upgrade skipping 1.23? I don't think we have too many requests for the fix so I am closing this one. Feel free to re-open if this is blocking you.

/close
