### ISSUE TITLE
Windows nodes pod CreateContainerError with "invalid mount config for type "bind": source path must be a directory"

### ISSUE THREAD

**Issue by JiaruiTracy** [kubernetes/kubernetes#110325]
### I'm trying to setup my k8s cluster Windows worker node on a workstation PC with docker as container runtime. However, my pod is always failed with status CreateContainerError. Steps I followed to setup windows node:
1. Install Docker: [https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker](url)
2. Add windows node: [https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/](url) 
3. While adding windows node, I also installed:
          a) **cri-dockerd-0.2.0**.win.amd64.zip since k8s v1.24 deprecated dockershim: [https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.0](url)
          b) **crictl-v1.24.1**-windows-amd64.tar.gz: [https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.24.1](url)

### The PrepareNode.ps1 ran successfully in step 2, service "kubelet" installed successfully. However, when I check pods under kube-system namespace by running `kubectl get pods -n kube-system -o wide`, pod "kube-flannel-ds-windows-amd64-k4pnh" created failed with below error messages when I kubectl describe it:

Warning Failed 10s kubelet Error: Error response from daemon: invalid volume specification: 'c:\var\lib\kubelet\pods\987c6f99-5bf3-428d-81b4-eaecf1d1da25\containers\kube-flannel\4d87a17f:c:/dev/termination-log': invalid mount config for type "bind": source path must be a directory

### Below is my environment information:
Master node:
- Workstation PC
- OS: centOS 7
- K8s version: v1.24.0
- Container runtime: containerd://1.6.4

Worker node:
- Workstation PC
- OS: Windows Server 2019 Datacenter
- K8s version: v1.24.0
- Container runtime: docker://20.10.9

### What did you expect to happen?

The pod on windows node shall be created and be in READY status successfully.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Docker: [https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server#install-docker](url)
2. Add windows node: [https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/](url) 
3. While adding windows node, I also installed:
          a) **cri-dockerd-0.2.0**.win.amd64.zip since k8s v1.24 deprecated dockershim: [https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.0](url)
          b) **crictl-v1.24.1**-windows-amd64.tar.gz: [https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.24.1](url)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}
```

</details>

### Cloud provider

<details>
I'm setting up the cluster with my local workstation PCs, suppose this option should be N/A?
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux myhostname 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                                   OSArchitecture  Version
17763        Microsoft Windows Server 2019 Datacenter  64-bit          10.0.17763
```

</details>

### Install tools

<details>
Windows node:
kubeadm:
`kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:44:24Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"windows/amd64"}`

kubelet:
`Kubernetes v1.24.0`

docker:
`Client: Mirantis Container Runtime
 Version:           20.10.9
 API version:       1.41
 Go version:        go1.16.12m2
 Git commit:        591094d
 Built:             12/21/2021 21:34:30
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Mirantis Container Runtime
 Engine:
  Version:          20.10.9
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.16.12m2
  Git commit:       9b96ce992b
  Built:            12/21/2021 21:33:06
  OS/Arch:          windows/amd64
  Experimental:     false`

crictl: v1.24.2
`time="2022-06-01T01:52:35-07:00" level=warning msg="runtime connect using default endpoints: [npipe:////./pipe/dockershim npipe:////./pipe/containerd-containerd npipe:////./pipe/cri-dockerd]. As the default settings are now deprecated, you should set the endpoint instead."
time="2022-06-01T01:52:35-07:00" level=error msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing open //./pipe/dockershim: The system cannot find the file specified.\""
time="2022-06-01T01:52:35-07:00" level=error msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing open //./pipe/containerd-containerd: The system cannot find the file specified.\""
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.9
RuntimeApiVersion:  1.41.0`

cri-dockerd: cri-dockerd 0.2.1 (HEAD)
</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-dockerd:
cri-dockerd 0.2.1 (HEAD)
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@JiaruiTracy can you please try to create a bug on cri-dockerd repository to understand if this is k8s or cri issue. We haven't seen this issue with other runtimes.

/triage needs-information

**Comment by Dr-Ogden-Wernstrom** [comment]
> @JiaruiTracy can you please try to create a bug on cri-dockerd repository to understand if this is k8s or cri issue. We haven't seen this issue with other runtimes.
> 
> /triage needs-information

I'm experiencing the same issue so even though I'm very new to this I attempted to investigate on the 'cri-dockerd' side.

I believe the problem is that (ref the issue description above) `c:\var\lib\kubelet\pods\987c6f99-5bf3-428d-81b4-eaecf1d1da25\containers\kube-flannel\4d87a17f` has been created as a file as opposed to a directory and that mounting files as volumes is not possible on Windows (https://github.com/moby/moby/issues/30555)

This path forms part of the 'CreateContainer' request that is received from kubelet.

**Comment by keyingliu** [comment]
kubernetes 1.24 removed dockershim support, and single file mount handling has been changed:
in 1.23: `supportsSingleFileMapping := kl.containerRuntime.SupportsSingleFileMapping()` is used and etc-hosts and TerminationMessagePath are handled specially for windows
but in 1.24, this handling has been removed, no SupportsSingleFileMapping anymore.

**Comment by Dr-Ogden-Wernstrom** [comment]
Does this mean that the single file support detection (and subsequent special handling)  should have been moved into cri-dockered (replaces the dockershim)?

**Comment by marosset** [comment]
Docker on windows (moby and Docker EE) use v1 [HCS](https://docs.microsoft.com/en-us/virtualization/api/hcs/overview) APIs which do not support single-file volume mapping into containers.
ContainerD uses v2 HCS APIs which do.

When `containerRuntime.SupportSingleFileMapping()` was added it used the `--container-runtime` arg and skipped adding the updated `etc/hosts` file into containers if that was set to `dockershim` 

The two ways I can think of to address this issue if you must run Docker EE are
- Update cri-dockerd to look for this specific volume mount and drop it when it makes CreateContainer calls
- Update kubelet to query the container runtime and re-introduce `containerRuntime.SupportSingleFileMapping()` for supported container runtimes.

Either way [HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) support will not work but pods should be able to start.

I would recommend trying to get set up with ContainerD on Windows becasuse it uses the v2 HCS APIs which enabled functionality like kubelet-managed etc/hosts files, graceful container shutdown, and more.

**Comment by marosset** [comment]
@claudiubelu as FYI too since you authored the PR that added in the `containerRuntime.SupportSingleFileMapping()`

**Comment by JiaruiTracy** [comment]
> Docker on windows (moby and Docker EE) use v1 [HCS](https://docs.microsoft.com/en-us/virtualization/api/hcs/overview) APIs which do not support single-file volume mapping into containers. ContainerD uses v2 HCS APIs which do.
> 
> When `containerRuntime.SupportSingleFileMapping()` was added it used the `--container-runtime` arg and skipped adding the updated `etc/hosts` file into containers if that was set to `dockershim`
> 
> The two ways I can think of to address this issue if you must run Docker EE are
> 
> * Update cri-dockerd to look for this specific volume mount and drop it when it makes CreateContainer calls
> * Update kubelet to query the container runtime and re-introduce `containerRuntime.SupportSingleFileMapping()` for supported container runtimes.
> 
> Either way [HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) support will not work but pods should be able to start.
> 
> I would recommend trying to get set up with ContainerD on Windows becasuse it uses the v2 HCS APIs which enabled functionality like kubelet-managed etc/hosts files, graceful container shutdown, and more.

We also tried containerd before trying with docker + cri-dockerd, it did not have this single-file volume mapping 
issue, however, the pod failed creating network, more details are: [https://github.com/microsoft/windows-container-networking/issues/69](url)

**Comment by Dr-Ogden-Wernstrom** [comment]
> Either way [HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) support will not work but pods should be able to start.

This issue is that the pod fails to start because the termination log location (which is a file) is mounted as a volume on container creation.

**Comment by JiaruiTracy** [comment]
> Docker on windows (moby and Docker EE) use v1 [HCS](https://docs.microsoft.com/en-us/virtualization/api/hcs/overview) APIs which do not support single-file volume mapping into containers. ContainerD uses v2 HCS APIs which do.
> 
> When `containerRuntime.SupportSingleFileMapping()` was added it used the `--container-runtime` arg and skipped adding the updated `etc/hosts` file into containers if that was set to `dockershim`
> 
> The two ways I can think of to address this issue if you must run Docker EE are
> 
> * Update cri-dockerd to look for this specific volume mount and drop it when it makes CreateContainer calls
> * Update kubelet to query the container runtime and re-introduce `containerRuntime.SupportSingleFileMapping()` for supported container runtimes.
> 
> Either way [HostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) support will not work but pods should be able to start.
> 
> I would recommend trying to get set up with ContainerD on Windows becasuse it uses the v2 HCS APIs which enabled functionality like kubelet-managed etc/hosts files, graceful container shutdown, and more.

Reset windows node and retried with ContainerD, getting below error while creating pod:
  Warning  FailedCreatePodSandBox  26m                   kubelet            **Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5ba6836605b1c68e5a8ce06beeb64bb5a51aabb1cc5ebc5c19245181552ad1df": plugin type="nat" name="nat" failed (add): hcnCreateNetwork failed in Win32: Invalid JSON document string. (0x803b001b) {"Success":false,"Error":"Invalid JSON document string. ","ErrorCode":2151350299}**

Version info:
ContainerD: **v1.6.6**
k8s: **v1.24.0**

**Comment by jsturtevant** [comment]
> Reset windows node and retried with ContainerD, getting below error while creating pod:
> Warning FailedCreatePodSandBox 26m kubelet **Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "5ba6836605b1c68e5a8ce06beeb64bb5a51aabb1cc5ebc5c19245181552ad1df": plugin type="nat" name="nat" failed (add): hcnCreateNetwork failed in Win32: Invalid JSON document string. (0x803b001b) {"Success":false,"Error":"Invalid JSON document string. ","ErrorCode":2151350299}**

@JiaruiTracy unfortunately the docs at: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ where not accurate for containerd.  We have since removed those specifics.  When setting up the node you can't include the nat cni configuration that those docs had initially pointed at.  if you remove that, install Flanneld as service, and only include the flannel CNI configuration it should work.
