### ISSUE TITLE
Use TLS 1.3 by default

### ISSUE THREAD

**Issue by dalgibbard** [kubernetes/kubernetes#110346]
Hi all,
In relation to: https://github.com/kubernetes-sigs/metrics-server/issues/985

Given that pretty much all libraries/clients out there have supported TLS1.3 for quite a while now, it would be great to move towards deprecating TLS1.2 and lower -- this removes the need to employ Server-side Ciper ordering, and/or enabling/disabling various ciphers which are deemed insecure (ie. 3DES, CBC); mitigating potential issues like GOLDENDOODLE 
 / SWEET32 / LUCKY13 for all clients.

Thanks in advance!

**Comment by enj** [comment]
/triage accepted

I do not believe we could change the implicit default of this flag as that would be a backwards incompatible change (we have no way of knowing if clients support TLS 1.3 in a particular env).  I could see us removing the default of the flag altogether and requiring that it be specified.  The documentation could then recommend 1.3 for environments where it is known to be supported, and 1.2 for environments where compatibility is desired over maximum security.

I would recommend bringing this up during a SIG Auth and API machinery biweekly meeting before taking any further action.

**Comment by sftim** [comment]
/area security
?
