### ISSUE TITLE
supporting horizontal-pod-autoscaler-sync-period configuration per hpa resource

### ISSUE THREAD

**Issue by bamboo12366** [kubernetes/kubernetes#110317]
### What would you like to be added?

Can we add the sync-period configurable in every hpa? may be can pass by using annotation. If not passing this variable can using the controller default one.

### Why is this needed?

Current `horizontal-pod-autoscaler-sync-period` is controller level config. In our environment, some workload are much sensitive than other(consider they want to check whether can scale more frequent to others). The sync-period configure in cluster level is not that flexible.

**Comment by pbetkier** [comment]
I'm not sure lower sync period will get you a significant recommendation latency decrease. Note that kubelets take CPU/memory measurements every ~10s and metrics-server fetches updates from kubelets every ~30s. So the delay between change in the metric and recommendation getting actuated (scale changed on deployment) seems to me would be:

* with 15s reconciliation
  - worst case: 10s (kubelet measurement) + 30s (metrics-server scrape) + 15s (reconciliation interval) = 55s
  - average case (roughly): 5s (kubelet measurement) + 15s (metrics-server scrape) + 7.5s (reconciliation interval) = 27.5s
* with 5s reconciliation
  - worst case: 10s (kubelet measurement) + 30s (metrics-server scrape) + 5s (reconciliation interval) = 45s
  - average case (roughly): 5s (kubelet measurement) + 15s (metrics-server scrape) + 2.5s (reconciliation interval) = 22.5s

So not a significant difference, especially considering also the delay of pod startups which is constant regardless of sync period.

If you change `horizontal-pod-autoscaler-sync-period` cluster-wide do you see significantly better performance?

**Comment by bamboo12366** [comment]
We are using [keda](https://keda.sh/) for this, so the process may not restricted by k8s reconcile process; So if I change 
`horizontal-pod-autoscaler-sync-period` is quite good enough for our situation;

But I really want is a application level configuration cuz some workload are more sensitive than other
