### ISSUE TITLE
Vulnerability in github.com/emicklei/go-restful library

### ISSUE THREAD

**Issue by vinpai** [kubernetes/kubernetes#110338]
There is a vulnerability shown by this library in Snyk which has now been fixed. Any chance we can update the client-go library to include this fix in its go.mod ? 
Snyk vulnerability: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFUL-2435653
Commit with the fix: https://github.com/emicklei/go-restful/tree/a2ff8b3f817635c0517a65055c36901e62e96ecb

**Comment by Jefftree** [comment]
This should already be resolved: https://github.com/kubernetes/kubernetes/blob/master/go.mod#L34
/close
