### ISSUE TITLE
Node lifecycle controller makes api calls under lock

### ISSUE THREAD

**Issue by marseel** [kubernetes/kubernetes#110341]
### What happened?

During scale testing, as sig-scalability, we observed that node-lifecycle-controller (https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/nodelifecycle/node_lifecycle_controller.go) was unable to process nodes  in reasonable time due to lock contention. 

Example log:
```
2022-04-19 19:06:29.860 GMT
Node ... is NotReady as of 2022-04-19 19:06:09.872955473 +0000 UTC m=+592959.664121666. Adding it to the Taint queue.
```
The difference between log timestamp 19:06:29.860 and decision timestamp 19:06:09.872955473 is around 20s. 
As a part of method `processTaintBaseEviction` I can see that `markNodeForTainting` was executed, which takes `evictorLock`. 
My suspicion is that it was waiting on this lock for ~20s. I can see that this lock might be taken by other goroutines that execute api calls under lock, for example https://github.com/kubernetes/kubernetes/blob/451e1fa8bcff38b87504eebd414948e505526d01/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L666

The whole `monitorNodeHealth` loop took around 40 minutes in total for one pass through all nodes in this cluster.

### What did you expect to happen?

I expected node-lifecycle-controller to process nodes in reasonable time

### How can we reproduce it (as minimally and precisely as possible)?

This test was run on large cluster and we removed significant portion of nodes - around 4k nodes out of 15k nodes. 

### Anything else we need to know?

Related issue that was opened before: https://github.com/kubernetes/kubernetes/issues/83954
Related comment in code: https://github.com/kubernetes/kubernetes/blob/451e1fa8bcff38b87504eebd414948e505526d01/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L281

### Kubernetes version

<details>
It was 1.23

</details>

### Cloud provider

GKE

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/priority important-soon
/sig scalability
nice catch

**Comment by aojea** [comment]
hmm, `DeletePods` is called from 3 different places under lock too

https://github.com/kubernetes/kubernetes/blob/03d0e2c3389db981fbc6234a9e121a99243d7aab/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1434


and this functions seems ti can take some time to run on nodes with a lot of pods

https://github.com/kubernetes/kubernetes/blob/03d0e2c3389db981fbc6234a9e121a99243d7aab/pkg/controller/util/node/controller_utils.go#L41-L44

**Comment by MadhavJivrajani** [comment]
I tried a little something here: https://github.com/kubernetes/kubernetes/pull/110359

Based on this comment:
https://github.com/kubernetes/kubernetes/blob/451e1fa8bcff38b87504eebd414948e505526d01/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L280

maybe we can refactor some of the logic to only hold the lock when needed and not for the entire lifecycle of the function

**Comment by MadhavJivrajani** [comment]
/sig apps
for visibility

**Comment by matthyx** [comment]
Just looking at this... @marseel do you think merging https://github.com/kubernetes/kubernetes/pull/110359 solved this issue?

**Comment by marseel** [comment]
I think we can close this issue for now. It definitely improves this case. 
/close
