### ISSUE TITLE
1.25 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/kubernetes#110336]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.25 Release Notes. If you know of issues or API changes that are going out in 1.25, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @csantanapr @orsenthil @Divya063 @ramrodo @DiptoChakrabarty

/sig release
/milestone v1.25

**Comment by Peter-Sparksuite** [comment]
Here's something of a biggie (for me currently):

https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke describes installing (for debian systems) via apt-get the google-cloud-sdk-gke-gcloud-auth-plugin.

When I look at the packages available for bullseye-slim on amd64 platform, I see a number of versions of this package available.  However, when I look likewise at the arm64 side of things, there is nothing!  This is definitely going to be an issue.
