### ISSUE TITLE
[Failing test] master-blocking build-master, push container images failed 

### ISSUE THREAD

**Issue by leonardpahlke** [kubernetes/kubernetes#110369]
### Which jobs are failing?

- sig-release master-blocking build-master

### Which tests are failing?

- ci-kubernetes-build.Overall

### Since when has it been failing?

2022-06-01 20:49 CEST, commit `22fda4e7e`

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#build-master

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1532445882308366336
```bash
level=info msg="Pushing container images from /home/prow/go/src/github.com/kubernetes/kubernetes/_output/release-images to registry gcr.io/k8s-staging-ci-images"
level=info msg="Getting manifest images in /home/prow/go/src/github.com/kubernetes/kubernetes/_output/release-images"
level=info msg="Pushing gcr.io/k8s-staging-ci-images/conformance-amd64:v1.25.0-alpha.0.793_ccfac6d3200f63"
level=info msg="Signing reference: gcr.io/k8s-staging-ci-images/conformance-amd64:v1.25.0-alpha.0.793_ccfac6d3200f63"
level=info msg="No identity token was provided. Attempting to get one from supported providers."
Generating ephemeral keys...
Retrieving signed certificate...
level=fatal msg="failed to run: push container images: publish container images: get manifest images: traversing path: executing tarball callback: sign container image: sign reference: gcr.io/k8s-staging-ci-images/conformance-amd64:v1.25.0-alpha.0.793_ccfac6d3200f63: getting signer: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input"
wrapper.sh] [TEST] Test Command exit code: 1
wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
```

### Relevant SIG(s)

/sig release
cc @kubernetes/release-managers

**Comment by cpanato** [comment]
I'm checking that

**Comment by cpanato** [comment]
this pr should fix https://github.com/kubernetes-sigs/promo-tools/pull/562

**Comment by neolit123** [comment]
it looks like it's still failing:
https://k8s-testgrid.appspot.com/sig-release-master-blocking#build-master

> level=fatal msg="failed to run: push container images: publish container images: get manifest images: traversing path: executing tarball callback: sign container image: sign reference: gcr.io/k8s-staging-ci-images/conformance-amd64:v1.25.0-alpha.0.826_35940b707c4e64: getting signer: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input"

**Comment by neolit123** [comment]
/reopen

reopening as this is causing all our CI to run against stale artifacts at:

https://storage.googleapis.com/k8s-release-dev/ci/latest.txt
v1.25.0-alpha.0.734+ba502ee555924a

**Comment by cpanato** [comment]
my previous fix only fixed one side of the things, missing https://github.com/kubernetes/release/pull/2545
now job are green 

![Screenshot 2022-06-07 at 09 15 47](https://user-images.githubusercontent.com/4115580/172319238-003616a5-f708-4df0-abbf-90a41c5d1ad8.png)

closing for now
/close
