### ISSUE TITLE
 Outdated modules that contain vulnerabilities

### ISSUE THREAD

**Issue by IzhakJakov** [kubernetes/kubernetes#110344]
## Found vulnerability ([SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515))

[github.com/spf13/cobra](https://github.com/spf13/cobra) `v1.1.3` uses [github.com/dgrijalva/jwt-go](https://github.com/dgrijalva/jwt-go) which is affected by [a known vulnerability](https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDGRIJALVAJWTGO-596515) and [is no longer maintaned](https://github.com/dgrijalva/jwt-go#this-repository-is-no-longer-maintaned) so it should probably be upgraded to a newer version.

```
❯ ggdh 'github.com/dgrijalva/jwt-go'
             k8s.io/apiserver@v0.24.0
                        ⬇
         go.etcd.io/etcd/server/v3@v3.5.0
                        ⬇
           github.com/spf13/cobra@v1.1.3
                        ⬇
           github.com/spf13/viper@v1.7.0
                        ⬇
  github.com/dgrijalva/jwt-go@v3.2.0+incompatible
```

## Found another vulnerability ([SNYK-GOLANG-GITHUBCOMPKGSFTP-569475](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMPKGSFTP-569475))
```
〉ggdh 'github.com/pkg/sftp
            k8s.io/apiserver@v0.24.0
                       ⬇
  github.com/coreos/go-oidc@v2.1.0+incompatible
                       ⬇
github.com/emicklei/go-restful@v2.9.5+incompatible
                       ⬇
github.com/evanphx/json-patch@v4.12.0+incompatible
                       ⬇
         github.com/spf13/afero@v1.6.0
                       ⬇
          github.com/pkg/sftp@v1.10.1
```

**Comment by dims** [comment]
We are now on a newer cobra:
```
[dims@dims-m1-7728 13:45] ~/go/src/k8s.io/kubernetes ⟩ rg github.com/spf13/cobra go.mod
64:	github.com/spf13/cobra v1.5.0
465:	github.com/spf13/cobra => github.com/spf13/cobra v1.5.0
```

We do not currently have a dependency on `github.com/dgrijalva/jwt-go`
```
[dims@dims-m1-7728 13:47] ~/go/src/k8s.io/kubernetes ⟩ go mod graph | grep github.com/dgrijalva/jwt-go
[dims@dims-m1-7728 13:48] ~/go/src/k8s.io/kubernetes ⟩ grep github.com/dgrijalva/jwt-go go.mod
``` 

/close
