### ISSUE TITLE
kubectl logs prints empty output if logs are rotated - some example are wrong

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11046]
In many examples we use "kubectl logs" to show container output:

```
examples/cluster-dns/README.md:$ kubectl logs dns-frontend
examples/downward-api/README.md:$ kubectl logs dapi-test-pod | grep POD_
examples/hazelcast/README.md:$ kubectl logs hazelcast-ulkws hazelcast
examples/mysql-wordpress-pd/README.md:$ kubectl logs mysql
examples/phabricator/README.md:$ kubectl logs phabricator-controller-02qp4
examples/secrets/README.md:$ kubectl logs secret-test-pod
examples/spark/README.md:$ kubectl logs spark-master
```

Quite often (for me - maybe once every 20-50 executions - I found it by an automated test) "kubectl logs" gives an empty output. The reason is that the docker log file has been rotated in the meantime.

Examples in the current form may be confusing for our users because they will not get the desired output.

The problem affects also our tests for examples, because they will be flaky if we assume we'll get some output form "kubectl logs".

**Comment by marekbiskup** [comment]
Container logs are supposed to be rotated by logrotate with the following config:

```
root@e2e-test-biskup-minion-dan2:/var/lib/docker/containers/63f0f01f331682d637413d0f550d22340a8ab0c6481205afe9823d53e2a2ee08# cat /etc/logrotate.d/docker-containers 
/var/lib/docker/containers/*/*-json.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 10M
    daily
    create 0644 root root
}
```

So they are rotated daily. However, if I check my existing system, I can see that rotation is performed much more often:

```
root@e2e-test-biskup-minion-dan2:/# find /var/lib/docker/containers/ | grep 1.gz | xargs ls -l | cut -d ' ' -f10 | sort | uniq

13:14
14:36
14:40
14:42
14:45
14:46
14:49
14:51
14:54
15:13
16:15
16:18
16:26
16:33
17:01
17:03
17:32
17:33
17:36
17:38
17:39
17:41
17:42
17:43
17:46
17:49
18:19
18:20
18:21
18:23
18:24
```

Maybe kubelet also rotates these logs?

**Comment by mwielgus** [comment]
cc: @mwielgus

**Comment by marekbiskup** [comment]
@dchen1107, @lavalamp, do you know if kubernetes (kubelet) rotates docker container logs? Or fires logrotate?

How do we proceed:
1) correct kubectl logs so that it prints also the rotated files
2) mention in the examples that "kubectl logs" may give empty output
3) do not rotate if the file is less than 1MB (add `minsize 1M` to logrotat conf) - this will be enough for the examples.

Anyway, we have to find out what triggers log rotation.

**Comment by marekbiskup** [comment]
Rotation in my pod:

Pod status:
```
      state:
        terminated:
          containerID: docker://63f0f01f331682d637413d0f550d22340a8ab0c6481205afe9823d53e2a2ee08
          exitCode: 0
          finishedAt: 2015-07-09T19:23:26Z
          startedAt: 2015-07-09T19:21:42Z
```

rotated file:
```
root@e2e-test-biskup-minion-dan2:/var/lib/docker/containers/63f0f01f331682d637413d0f550d22340a8ab0c6481205afe9823d53e2a2ee08# stat 63f0f01f331682d637413d0f550d22340a8ab0c6481205afe9823d53e2a2ee08-json.log.1.gz 
  File: `63f0f01f331682d637413d0f550d22340a8ab0c6481205afe9823d53e2a2ee08-json.log.1.gz'
  Size: 222       	Blocks: 8          IO Block: 4096   regular file
Device: 801h/2049d	Inode: 1447112     Links: 1
Access: (0600/-rw-------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2015-07-10 07:22:20.083700626 +0000
Modify: 2015-07-09 19:23:23.000000000 +0000
Change: 2015-07-10 00:17:10.289093714 +0000
```

So the rotation occurred about the same time the pod terminated. Maybe this is related.

So may be the problem affects only pods that terminate.

**Comment by rjnagal** [comment]
@dchen1107 can you take a look?

**Comment by dchen1107** [comment]
cc/ @satnam6502 too.

**Comment by satnam6502** [comment]
I vote for 2. I think we should advise that `kubectl logs` is just a "cache" of some of the logs for a pod and that cluster level logging should be used to get the full history of a pod's log output. If a pod was restarted then `kubectl logs` does not show logs from the previous invocation, as discussed at https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/logging.md

**Comment by dchen1107** [comment]
Agreed with @satnam6502. I will update those examples referring to logging.md. Thanks!

**Comment by dchen1107** [comment]
cc/ @bgrant0607

**Comment by marekbiskup** [comment]
Could you tell me how the logs are rotated?
I need it for my e2e test.
Thanks.

**Comment by satnam6502** [comment]
```
$ find . -name *logrotate*
./cluster/saltbase/salt/logrotate
./_output/release-stage/salt/kubernetes/saltbase/salt/logrotate
$ ls ./cluster/saltbase/salt/logrotate
conf  cron  docker-containers  init.sls
$ cat ./cluster/saltbase/salt/logrotate/conf 
/var/log/{{ file }}.log {
    rotate 5
    copytruncate
    missingok
    notifempty
    compress
    maxsize 100M
    daily
    create 0644 root root
}
```

**Comment by dchen1107** [comment]
@marekbiskup I believe our log rotation for daemons and docker containers are all controlled by logrotation configuration files. Kubelet doesn't do extra handling on logrotation. 

For an example you gave above: https://github.com/GoogleCloudPlatform/kubernetes/issues/11046#issuecomment-120276366
I think the testing container you have might log too much, and reach the maxsize 10M very fast. I just validate this with my cluster built a couple of days ago, and the below the output ls one of docker containers:

```
/var/lib/docker/containers/c006fca75aca47d681c860699fabf89fe6dbc5ef6958ae4e3700d9b8d94ae13e:
total 10612
drwx------  2 root root    4096 Jul 13 00:17 .
drwx------ 15 root root    4096 Jul 10 18:15 ..
-rw-------  1 root root 9567349 Jul 14 00:09 c006fca75aca47d681c860699fabf89fe6dbc5ef6958ae4e3700d9b8d94ae13e-json.log
-rw-------  1 root root  560236 Jul 13 00:17 c006fca75aca47d681c860699fabf89fe6dbc5ef6958ae4e3700d9b8d94ae13e-json.log.1.gz
-rw-------  1 root root  560189 Jul 12 00:17 c006fca75aca47d681c860699fabf89fe6dbc5ef6958ae4e3700d9b8d94ae13e-json.log.2.gz
-rw-------  1 root root  141417 Jul 11 00:17 c006fca75aca47d681c860699fabf89fe6dbc5ef6958ae4e3700d9b8d94ae13e-json.log.3.gz
-rw-r--r--  1 root root    4905 Jul 10 18:15 config.json
-rw-r--r--  1 root root     977 Jul 10 18:15 hostconfig.json
-rw-r--r--  1 root root     167 Jul 10 18:15 resolv.conf
-rw-r--r--  1 root root      71 Jul 10 18:15 resolv.conf.hash
```

From above, you can see that at the same time (~00:17) every day, logrotate takes effect.

But you are right about once log is rotated, kubectl logs only shows the latest logs, which could be empty due to the log rotation.

**Comment by marekbiskup** [comment]
Actually my rotated files were small - just a few lines. So it's still unexplained.
Anyway, I agree with @satnam6502  that we should clarify that `kubectl logs` may be unreliable and the user should not assume they are complete. We may also put this note in our examples.

**Comment by ncdc** [comment]
FYI, I'm seeing this behavior when running on Fedora 21 with `hack/local-up-cluster.sh` and *no* log rotation.

**Comment by nsidhaye** [comment]
I setup logrotate compress & rotate zip log files daily. 

In order to test I executed `logrotate -f /etc/logrotate.conf`

Now I could not able to see logs by kubectl logs. 

I believe *NIX (process) still having handle of the file which I already rotated. Due to stale file handle, logs are not updating.
