### ISSUE TITLE
Is it possible to provide in-place upgrade capability for PODs?

### ISSUE THREAD

**Issue by ypf-bendan** [kubernetes/kubernetes#110487]
When POD modifies the image, it should stop the backend service as Service, can this be achieved by modifying the Ready state of POD?  like openkuise.

**Comment by FillZpp** [comment]
I think it is duplicated of #9043 

Unfortunately, it is unlikely to be supported by K8s itself, which actually breaks the Pod immutable rule. But [OpenKruise](https://openkruise.io/), one of the CNCF Sandbox projects, has supported in-place update for container images and even environments (via downward API) in Pod. You can read the doc here https://openkruise.io/docs/core-concepts/inplace-update .

Please contact me if your have any questions about OpenKruise. And I'm also glad to help you if you are going to create a KEP to support it in K8s :)
