### ISSUE TITLE
FakeClient: list pod err after an pod evicted

### ISSUE THREAD

**Issue by LY-today** [kubernetes/kubernetes#110424]
### What happened?

After I evicted an pod, I performed the operation of the full list instance, but found something that did not meet expectations
```
item[0]: can't assign or convert v1beta1.Eviction into v1.Pod
```

### What did you expect to happen?

After pods are evicted, non-evicted ones can be listed normally

### How can we reproduce it (as minimally and precisely as possible)?

```
package main

import (
	"context"
	v1 "k8s.io/api/core/v1"
	policy "k8s.io/api/policy/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes/fake"
)

func main() {
	client := fake.NewSimpleClientset()
	client.CoreV1().Pods("default").Create(context.Background(),&v1.Pod{
		ObjectMeta: meta_v1.ObjectMeta{
			Name:      "pod-1",
			Namespace: "default",
		},
	},meta_v1.CreateOptions{})
	_ = client.CoreV1().Pods("default").EvictV1(context.Background(), &policy.Eviction{
		ObjectMeta: meta_v1.ObjectMeta{
			Name: "pod-1",
		},
	})
	_, err := client.CoreV1().Pods("default").List(context.Background(),meta_v1.ListOptions{})
	//err: item[0]: can't assign or convert v1beta1.Eviction into v1.Pod
}
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
v1.20.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by endocrimes** [comment]
https://github.com/kubernetes/kubernetes/pull/110425

/sig api-machinery
/remove-sig node

**Comment by LY-today** [comment]
@yliaog If you have time, please help to look at this pr, thanks

**Comment by liggitt** [comment]
this is a general issue with subresources that accept create requests of different object types than the parent resource

see also:
* https://github.com/kubernetes/kubernetes/issues/80354
* https://github.com/kubernetes/kubernetes/issues/71598
* https://github.com/kubernetes/kubernetes/pull/71599
* https://github.com/kubernetes/client-go/issues/734
* https://github.com/kubernetes/kubernetes/pull/97937
