### ISSUE TITLE
ci-cri-containerd-e2e-cos-gce-reboot is flaky

### ISSUE THREAD

**Issue by ruiwen-zhao** [kubernetes/kubernetes#110440]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-node-cos#e2e-cos-reboot

### Which tests are flaking?

Multiple tests:

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by ordering unclean reboot and ensure they function upon restart: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534261247585816576

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by dropping all outbound packets for a while and ensure they function afterwards: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534261247585816576

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by switching off the network interface and ensure they function upon switch on: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534261247585816576

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by dropping all inbound packets for a while and ensure they function afterwards: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534230625110724608

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by ordering clean reboot and ensure they function upon restart: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534230625110724608

Kubernetes e2e suite.[sig-cloud-provider-gcp] Reboot [Disruptive] [Feature:Reboot] each node by triggering kernel panic and ensure they function upon restart: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cri-containerd-e2e-cos-gce-reboot/1534215525331111936

### Since when has it been flaking?

Since the start of test grid history, which is 05/23.

### Testgrid link

https://testgrid.k8s.io/sig-node-cos#e2e-cos-reboot

### Reason for failure (if possible)

All tests are failing with 

```
{ Failure test/e2e/cloud/gcp/reboot.go:144
Jun  7 20:18:32.829: Test failed; at least one node failed to reboot in the time given.
test/e2e/cloud/gcp/reboot.go:149}
```

### Relevant SIG(s)

/sig node

**Comment by pacoxu** [comment]
still failed
/remove-lifecycle rotten
