### ISSUE TITLE
Finish putting ToCs into Docs

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#11040]
#10762 added automatic doc transformation and a basic pass to add Tables of contents to files.

The toc generator in cmd/mungedocs/toc.go needs to be enhanced as follows:
- right now it indents the toc entries by `spaces =  (numSharpsOfHeading - 1 ) *2`.  But when a document starts with, say, `###`, then the table of contents will start with a four space indent, which causes Markdown to not properly render it as a bulleted list.  So, fix this.
- right now `#` inside block quotes are being treated as headings.  There are lots of these.  Need to detect when inside a block quota.  Suggest assuming that block quotes are always at start of line.

Once that is done, add the following block to the appropriate place at the top of approximately all .md files under docs:

```
**Table of Contents**
<!-- BEGIN GENERATED TOC -->
<!-- END GENERATED TOC -->
```

then run hack/run-mungedocs.sh.

**Comment by erictune** [comment]
I meant to get to this but if have a few other things in the air so I've written down what needs to be done in case anyone else wants to pick this up.

**Comment by karlkfi** [comment]
Since `hack/run-mungedocs.sh` was removed, `make` the binaries locally and exec the `mungedocs` cmd (needs usage docs) to update the toc.

The correct block is now:

```
**Table of Contents**
<!-- BEGIN MUNGE: GENERATED_TOC -->
<!-- END MUNGE: GENERATED_TOC -->
```

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers

**Comment by chenopis** [comment]
This can be closed.
