### ISSUE TITLE
debug kube-scheduler error

### ISSUE THREAD

**Issue by heyu1207** [kubernetes/kubernetes#110444]
### What happened?

When I debug the scheduler code, I found that the code can't step over from this line `cc.InformerFactory.WaitForCacheSync(ctx.Done())`.
The console window repeat reporting `failed to list *v1.CSISto rageCapacity: the server could not find the requested resource` , as shown below:
![14a35b552bd689b73ec24c2ff459485](https://user-images.githubusercontent.com/43037766/172522922-1d745e46-a324-4f7b-91de-7fd6fc917791.png)

**Environmental Info:**
K3s Version: v1.22.7+k3s1
Kubernetes code: maybe v1.24, I download it last month from the master branch, so it should be the new version 1.24
Node(s) CPU architecture, OS, and Version: x86-64, ubuntu20.04 (vmware)

I tried using kubectl to list the CSIStorageCapacity resource, and coudn't find the resource. I guess the k3s CSI plugin, local-path-provisioner doesn't support this resource. But it's still weird that this function can't return back and the scheduler code can't proceed.

### What did you expect to happen?

The code can return back from this function `cc.InformerFactory.WaitForCacheSync(ctx.Done())` and proceed.

### How can we reproduce it (as minimally and precisely as possible)?

Install k3s by exec `curl -sfL https://get.k3s.io | sh -`
Use k3s.yaml to connect to the cluster ( the file is under `/etc/rancher`) and edit debug configrations of goland like below:
![8dd68dbc1cafa0b1a97210eb8c36e71](https://user-images.githubusercontent.com/43037766/172522347-c6ed2043-030a-4c0f-b11e-309fdf8b5d89.png)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
No provider.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
Well, I'm doubt about whether this is the right place to ask the question about IDE debugging.
/remove-kind bug
/kind support
