### ISSUE TITLE
Examples and lots of software broken because of DNS changes

### ISSUE THREAD

**Issue by pires** [kubernetes/kubernetes#11048]
Thanks to https://github.com/GoogleCloudPlatform/kubernetes/commit/be4b700ccb2f2769f3099861f6d410073df283fd#diff-9436c96b0e9bf5bdad76fb79e7f0df25R23 some examples, like Hazelcast or Cassandra are broken. Also, software like @jimmidyson Elasticsearch discovery plug-in breaks.

This is a really nasty thing, and I wonder what is the rationale behind it - add `.svc.` to the A record.

**Comment by jimmidyson** [comment]
@pires The fabric8 Java client you mentioned by default will use the env vars `KUBERNETES_SERVICE_HOST` & `KUBERNETES_SERVICE_PORT` to find the Kubernetes master. Or you can alternatively specify the FQDN using `KUBERNETES_MASTER=https://kubernetes.default.svc.cluster.local:8443` & it will discover it.

**Comment by pires** [comment]
@thockin informed me `kubernetes.default.cluster.local` should work if `kubernetes.default.svc.cluster.local` works as well. With 0.21.0 binaries this does not apply to me.

**Comment by rjnagal** [comment]
@thockin Did it get fixed by changes we merged earlier today?

**Comment by pires** [comment]
#11107 mitigates this in `examples/hazelcast`.

**Comment by thockin** [comment]
@pires I don't know what "does not apply to me" means?  legacy (x.y.cluster.local) DNS names should work and will continue to work until some time after 1.0

**Comment by thockin** [comment]
I'd like to close this bug or retitle it - it has a scary sounding and inaccurate subject :)

**Comment by pires** [comment]
With 0.21.0 binaries it doesn't work for me. So has it been fixed
meanwhile? Am I missing something?

**Comment by thockin** [comment]
It was never broken.  We never took away old names.  Can you run kube2sky
with higher -v ?  You should see both sets of names in the logs.


Oh!  Maybe this has some effect...  At some point (around 0.20 I thought)
we changed the default 'search' directives in kubelet from "cluster.local"
to "svc.cluster.local".  Any new pods would get "svc", but any old ones
would not.  But DNS serves both names, so it should not make any difference.

I am very confused, because we did test this and think through all the
compat modes.  Abhi, am I forgetting something?  @artfulcoder

**Comment by erictune** [comment]
is this the --root-ca-cert issue?

**Comment by erictune** [comment]
p1 to understand if there is some issue we didn't know about here.

**Comment by ArtfulCoder** [comment]
Service name lookup should work with or without the svc label.

-------------------- See below --------------------

root@e2e-test-abshah-minion-3nb5:/home/abshah# nslookup kubernetes.default.cluster.local 10.0.0.10
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	kubernetes.default.cluster.local
Address: 10.0.0.1

root@e2e-test-abshah-minion-3nb5:/home/abshah# nslookup kubernetes.default.svc.cluster.local 10.0.0.10
Server:		10.0.0.10
Address:	10.0.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.0.0.1

**Comment by pires** [comment]
I am sorry for not updating this but the examples I maintain do use DNS for (at least) querying the API. So we're good.
