### ISSUE TITLE
GCE Disk based Volumes are broken on CoreOS

### ISSUE THREAD

**Issue by danielschonfeld** [kubernetes/kubernetes#11042]
On CoreOS `/usr/share` is a read only partition.  The user cannot even create a symlink to try to make it work and the default location for `safe_format_and_mount` is `/usr/share/oem/google-startup-scripts`

Therefore GCE Disk based volumes are broken on CoreOS

**Comment by rjnagal** [comment]
@saad-ali can you take a look?

**Comment by saad-ali** [comment]
Sure, I'll take a look.

**Comment by roberthbailey** [comment]
@saad-ali -- any updates (someone on github was asking)

**Comment by danielschonfeld** [comment]
@saad-ali that someone was me...

**Comment by saad-ali** [comment]
@danielschonfeld thanks for the reminder. I'll look in to this issue this week.

**Comment by swagiaal** [comment]
@roberthbailey @danielschonfeld @saad-ali #8530 should solve this issue

**Comment by saad-ali** [comment]
Thanks @swagiaal! I'll take a look at that PR

**Comment by saad-ali** [comment]
This should be fixed with #8530 and #14109
