### ISSUE TITLE
kubelet: Setup testing infrastructure to test CRI invariants

### ISSUE THREAD

**Issue by endocrimes** [kubernetes/kubernetes#110429]
/sig node
/kind cleanup

Today we don't really have a way to test what happens when a CRI or gRPC fails. This makes it hard to identify, reproduce, and fix issues that happen when a CRI has a problem (such as the CRI restarting at the wrong part of a control loop).

We need to do some research and basic setup of tests that can mock a CRI or allow us to do failure injection in our tests with real CRIs.

/cc @mikebrow

**Comment by mikebrow** [comment]
Hardening the container runtime integrations.. through mocking/injecting failures would, I think, be a worthy effort. Specifying well understood spec, but undocumented, invariants for the client and server side of the CRI API should be a part of this effort. The CRI integrations followed the dockershim invariants as written, when they were not formally called out in the CRI spec.  Continuing with the removal of dockershim, a more formal definition will help / is needed for some of the invariants.

Some failure injection points to discus, cover, or consider and items of note:

Runtime Services
------------------
- kubelet to container runtime gRPC based CRI runtime and image services
- logs/metrics (as managed between kubelet, cadvisor, and the container runtimes)
- streams for exec/attach/port forward (as proxied/routed)
- container runtime to container/pod shim interop (includes rootfs, container spec, and lifecycle which is handled via shim api over ttRPC)
- shim to runc/crun interop (exec of runc compatible runtime engines)
- runc to libcontainer
- Networking failures at setup, update, tear down, and async
- resource limit injection for failures of non-network types (memory, cpu, disk..)
- platform security failure injection opportunities (long list here)

Image Services
----------------
- connection/resolver issues for pull image (then unpack, de-encrypt), includes auth to container image registries/mirrors...
- resource limit injections mentioned above also apply here
- GC of images: both kubelet and container runtimes do garbage collection.. at the same time or in parallel

Coming Up
-----------
- PLEG - origination of state change events from container runtimes 
- Runtime Handler Isolation/Aggregation - runtime handlers, such as runc, confidential containers, ... may at some point have their own snapshotters, thus requiring aggregation and further invariant defines/tests not yet considered.
