### ISSUE TITLE
Node DiskPressure is missing when devmapper usage is full.

### ISSUE THREAD

**Issue by RamyAllam** [kubernetes/kubernetes#110461]
### What happened?

Kubernetes does not set `DiskPressure` status on the worker node when the devmapper usage is full.

When accessing the results from `localhost:10255/stats/summary` I can see Kubernetes is correctly calculating the `imageFs` but does not set `DiskPressure` nor evict the Pods from this node to another healthy one and keeps scheduling the Pods on the full node even though there are no enough space there.

This is tested on GKE/ContainerD with devmapper/lvm thin pool and the config is below
```
# cat /etc/containerd/config.toml
version = 2
required_plugins = [ "io.containerd.grpc.v1.cri",]
disabled_plugins = [ "io.containerd.internal.v1.restart",]
oom_score = -999

[debug]
level = "info"

[grpc]
gid = 117

[plugins."io.containerd.snapshotter.v1.devmapper"]
pool_name = "containerd-data"
base_image_size = "50GB"

[plugins."io.containerd.grpc.v1.cri"]
stream_server_address = "127.0.0.1"
max_container_log_line_size = 262144

[plugins."io.containerd.grpc.v1.cri".cni]
bin_dir = "/home/kubernetes/bin"
conf_dir = "/etc/cni/net.d"
conf_template = ""

[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "runc"
snapshotter = "devmapper"
```

### What did you expect to happen?

Kubernetes to set DiskPressure status when the devmapper usage on the node is full, monitor the node, and evit the Pods when needed.

### How can we reproduce it (as minimally and precisely as possible)?

- Configure LVM thin pool
```
PD=/dev/PATH_TO_SECOND_DISK
pvcreate $PD -y -ff
vgcreate containerd $PD
lvcreate --wipesignatures y -n data containerd -l 95%VG
lvcreate --wipesignatures y -n meta containerd -l 1%VG
lvconvert -y --zero n -c 512K --thinpool containerd/data --poolmetadata containerd/meta
echo 'activation {
thin_pool_autoextend_threshold=80
thin_pool_autoextend_percent=20
}' > /etc/lvm/profile/containerd-thinpool.profile
lvchange --metadataprofile containerd-thinpool containerd/data
lvchange --monitor y containerd/data
```
- Configure containerd
```
[plugins."io.containerd.snapshotter.v1.devmapper"]
pool_name = "containerd-data"
base_image_size = "50GB"

[plugins."io.containerd.grpc.v1.cri".containerd]
default_runtime_name = "runc"
snapshotter = "devmapper"
```
- Create a couple of pods and try to utilize the full space of the devmapper
```
dd if=/dev/zero of=/tmp/test$$ bs=1024 count=45680000
```

### Anything else we need to know?

![Xnip2022-06-08_18-10-45](https://user-images.githubusercontent.com/15165030/172669776-adade3c3-817d-4b67-8f7f-d9e770cada81.jpg)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.201", GitCommit:"2dca91e5224568a093c27d3589aa0a96fd3ddc9a", GitTreeState:"clean", BuildDate:"2022-05-11T18:39:02Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux gke-3195516e-dpxh 5.4.0-1065-gke #68-Ubuntu SMP Wed Mar 2 14:58:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
# containerd -v
containerd github.com/containerd/containerd 1.5.2-0ubuntu1~20.04.4

# runc -v
runc version 1.0.0~rc95-0ubuntu1~20.04.1~gke1
spec: 1.0.2-dev
go: go1.13.8
libseccomp: 2.5.1
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
</details>

**Comment by endocrimes** [comment]
/triage needs-information

@RamyAllam Can you share your Kubelet eviction configuration? (https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/)

**Comment by RamyAllam** [comment]
Hey @endocrimes 
I was not sure how to extract that from GKE standard mode so I went ahead and got it directly from the GKE worker node file: `/home/kubernetes/kubelet-config.yaml`
The original config is as follow
```
evictionHard:
  memory.available: 100Mi
  nodefs.available: 10%
  nodefs.inodesFree: 5%
  pid.available: 10%
```

I then appended `imagefs.available: 10%` to it, restarted kubelet daemon and tried to reproduce the issue, it didn't trigger `Node DiskPressure`, however, when setting it to 90% I was able to see `Node DiskPressure` properly set and Pods evictions are happening.

Looking into this again, I think the issue is that Kubernetes can properly get the value of `usedBytes` from the LVM thin pool but it gets incorrect values for `availableBytes` and `capacityBytes` and I think the reason for that is it gets the FS information of `/var/lib/containerd/io.containerd.snapshotter.v1.devmapper` and not the LVM capacity for some reason as in the screenshot.
![Xnip2022-06-08_22-30-56](https://user-images.githubusercontent.com/15165030/172712005-27de97cd-48ea-4452-ac31-b686c2f0f1c3.jpg)

Here the correct behavior is to have `capacityBytes` set 95G and not 50G. `availableBytes` should get a correct value as well.

Any idea what could be the reason for this? Thank you

**Comment by RamyAllam** [comment]
I see this in kubelet logs as well if it helps
```
kubelet[56176]: E0609 09:52:44.313152   56176 cri_stats_provider.go:372] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.devmapper"
```
