### ISSUE TITLE
Dummy image on registry.k8s.io

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#110471]
It may be nice to have some dummy image on `registry.k8s.io` that doesn't exist on `k8s.gcr.io`. This way we can write a simple e2e test that will validate that the image mirroring was set up properly in the environment.

See https://github.com/kubernetes/kubernetes/pull/110350#issuecomment-1150476706 for example

cc: @thockin @dims 

/area images-registry
KEP: https://github.com/kubernetes/enhancements/issues/3055
/sig k8s-infra
/sig node
/kind feature

**Comment by sftim** [comment]
`registry.k8s.io` doesn't host _any_ image data itself; we could change that, but that would be a switch from the existing design.

**Comment by SergeyKanzhelev** [comment]
> `registry.k8s.io` doesn't host _any_ image data itself; we could change that, but that would be a switch from the existing design.

Yes, I understand. This proposal is to add just one image or image tag with the unique name to test the mirror config. I wonder if the renaming may be done as a proxy by doing some routing magic.
