### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Pod Resize E2E test - add test for scheduler, fix code review items

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#110490]
### What would you like to be added?

In-Place Pod Vertical scaling [PR](https://github.com/kubernetes/kubernetes/pull/102884/) has an E2E test for testing pod resize. This test needs a fix fixes and improvements.

1. Add E2E test for exercising changes to scheduler code in the above PR. See comment: https://github.com/kubernetes/kubernetes/pull/102884#pullrequestreview-834424032
2. Move pod-resize.go E2E test from test/e2e/node/ to test/e2e_node/... . See comment: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r891689410
3. Remove shared podClient variable. See comment: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r891686256

### Why is this needed?

Scheduler changes are not big but are important. Unit test coverage is not sufficient. So we need to have automated scenario tests.

**Comment by vinaykul** [comment]
[wangchen615](https://github.com/wangchen615) and I discussed the test cases offline. The plan is to add the following E2E tests taking a 4 CPU node as example:

```
P1(3 cpus) scheduled and running, P2 (2 cpus) to be scheduled but pending due to insufficient resources.
Action: Resize P2 (2 cpus) to P2 (1 cpu)
Expected result: P2 (1 cpu) successfully scheduled and running.
```
```
P1 (3 cpus) scheduled and running, P2 (1 cpus)  scheduled and running
Action: Resize P2 (1 cpu) to P2 (2 cpus)
Expected result: P2 enters deferred state.
Action: Delete P1
Expected result: P2 resize is actuated.
```
```
Start P1 (3cpu) and P2(1cpu) and verify they are running.
Start P3 (1cpu) and verify it is pending.
Action: Resize P1(3cpu) -> P1(1cpu)
Expected result: P3 gets scheduled and comes up and running.
```

**Comment by tallclair** [comment]
Actually, on closer look, I think these items are addressed elsewhere.

/close
