### ISSUE TITLE
Graduate APIListChunking to stable

### ISSUE THREAD

**Issue by clyang82** [kubernetes/kubernetes#110415]
**This is a Bug Report**

**Problem:**

https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks
from the above document, we can see that `Retrieving large results sets in chunks` is marked as beta since v1.9. Does it reflect the correct status for this feature since we have v1.24? if so, do we have plan to GA this feature. Thanks.

**Proposed Solution:**

**Page to Update:**
https://kubernetes.io/docs/reference/using-api/api-concepts/#retrieving-large-results-sets-in-chunks

**Comment by sftim** [comment]
/retitle Graduate APIListChunking to stable

Relevant KEP: https://github.com/kubernetes/enhancements/issues/365

**Comment by clyang82** [comment]
close it since it is duplicated. Thanks.
