### ISSUE TITLE
Support class E network for pod and service networking 

### ISSUE THREAD

**Issue by sheetaljoshi** [kubernetes/kubernetes#110456]
### What would you like to be added?

Please allow class E address class (240.0.0.0/4) for pod and as well service networking. Are there any existing guidelines or challenges that would prevent us from proceeding this request?

### Why is this needed?

Kubernetes SaaS-based customers are often challenged with solving overlapping CIDRs when using CNIs in underlay mode. This work will help Kubernetes customers work around overlapping RFC1918 ranges.

**Comment by sheetaljoshi** [comment]
@aojea can you please comment on this issue.

**Comment by thockin** [comment]
We know that Kubernetes itself doesn't prevent you from using it (we use it in GKE).  Your own network gear might have a problem with it, though.

I'll close this, since #110457 is merged
