### ISSUE TITLE
Kubelet failed to start due to CPUs stat mismatch

### ISSUE THREAD

**Issue by MaiSao** [kubernetes/kubernetes#110478]
### What happened?

In kubelet config, we use cpuManagerPolicy: static, and specify the following configuration to reserve cpu for system etc:

![image](https://user-images.githubusercontent.com/32025886/172765230-50b71b73-8bc7-4f2e-aa80-aebb8c55db3a.png)

When server rebooted, kubelet will fail to start, this is the error log:

![image](https://user-images.githubusercontent.com/32025886/172765486-af2eb6d9-e093-481e-b880-a6a999c7dfd7.png)

I think cpu_manager do not pinning cpu right, then it check the available cpu is full, not reserve for kube, system, another pods at all.

### What did you expect to happen?

Kubelet service can start after reboot

### How can we reproduce it (as minimally and precisely as possible)?

I think can reproduce with numa enabled and set cpuManagerPolicy: Static, then reboot  server.

### Anything else we need to know?

I can solved it with remove file /var/lib/kubelet/cpu_manager_state and restart kubelet. But it is a perfect way with production.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.21.5

![image](https://user-images.githubusercontent.com/32025886/172765717-b810dbb8-f081-4900-859d-221c4c6c0896.png)

</details>


### Cloud provider

<details>
Private Cloud
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
![image](https://user-images.githubusercontent.com/32025886/172765783-912b1cbf-c7cb-4d3c-931d-2c9a904666a6.png)

</details>

### Install tools

<details>
default
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.5.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MaiSao** [comment]
>

**Comment by MaiSao** [comment]
> According to docs in https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#changing-the-cpu-manager-policy, this is expected.
> 
> When you change CPU manager policy, you should remove the old CPU manager state file.
> 
> https://github.com/kubernetes/website/blob/d2a2af28eaa1f947d01f54b411f53a8afe5215a5/content/en/docs/tasks/administer-cluster/cpu-management-policies.md#changing-the-cpu-manager-policy

No, i do not change CPU manager policy, when my server reboot, the kubelet not start as usual.

**Comment by alberthuang24** [comment]
You only provided the kubectl version, please check the server version, you can get the information by running `kubelet --version`

**Comment by SergeyKanzhelev** [comment]
@swatisehgal can you please take a look? It seems like a known issue and the behavior is expected.

**Comment by swatisehgal** [comment]
Yes, this is a known issue and the the behavior is expected.

The system reboot implies kubelet restart here. The cluster admin is expected to remove the CPU Manager state file before kubelet is restarted. In this case, based on the logs it seems that the failure is due to inconsistency in the actual available CPUs compared to the one that were written in the state file. Please refer to the code [here](https://github.com/kubernetes/kubernetes/blob/v1.21.5/pkg/kubelet/cm/cpumanager/policy_static.go#L166-L184).

The solution (as specified in the issue description above) is to delete the state file and restart kubelet.  

/close
