### ISSUE TITLE
Because of using fake client The program panics with "channel full"

### ISSUE THREAD

**Issue by enaguo** [kubernetes/kubernetes#110431]
### What would you like to be added?

I use fake client to create and modify simulated resources.When the amount of data is large and changes frequently, it will cause the program to panic.
<img width="1182" alt="截屏2022-06-08 上午12 33 31" src="https://user-images.githubusercontent.com/32294838/172434844-6f57370f-b265-4eae-8531-0d7fdceda91b.png">

When I use the fake client to create, modify, or delete resources, the fake client sends events to the tracker. By default, the RaceFreeFakeWatcher struct is used.
<img width="698" alt="截屏2022-06-08 上午12 36 05" src="https://user-images.githubusercontent.com/32294838/172435552-520f9a97-9341-4145-9034-214b2543eba8.png">
When the channel is full, it will panic directly.

### Why is this needed?

panic may not be the best solution, sometimes we don't want the program to panic when it have fake client. But currently fake client does not support custom tracker, it is not an interface, it is a default struct. and it have the default length of channel is 100 that does not support modification.

**Comment by leilajal** [comment]
/assign @alexzielenski @Jefftree 
Thanks for looking into this! Find people if you need help.
/triage accepted
