### ISSUE TITLE
Kubelet service paused on Windows 2019 node

### ISSUE THREAD

**Issue by K31D** [kubernetes/kubernetes#110580]
### What happened?

Adding windows nodes failed with "The Http call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: get "http://localhost:10248/healthz": dial tcp [::1]10248: connectex: No connection could be made because the target machine actively refused it

K8s: 1.23.3 with latest containerd (1.5.9) and flannel
Host: WS2019 datacenter with latest CU
Both install-containerd.ps1 and PrepareNode.ps1 -KubernetesVersion v1.23.3 -ContainerRuntime containerD ends with no error

Reason is Kubelet service remain paused after running PrepareNodes.ps1
While looking at the powershell script I saw multiple errors running StartKubelet.ps1
which I understood is used to register Kubelet service
![image](https://user-images.githubusercontent.com/50907803/173679335-1b5b3381-30d4-4732-9333-17c2a3e56a7a.png)

some of the errors:
![image](https://user-images.githubusercontent.com/50907803/173679303-356e355e-6bb4-492a-9e3b-2394d40a09cf.png)

I've already tried chaning manually some of those flags as documented [here ](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/)with no luck at all.

### What did you expect to happen?

Kubelet service running and port 10248 to be open in order to join Windows Node to K8s cluster

### How can we reproduce it (as minimally and precisely as possible)?

Following [this ](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/)documentation 
.\Install-Containerd.ps1
.\PrepareNode.ps1 -KubernetesVersion v1.23.3 -ContainerRuntime containerD
Kubelet service is in paused state

### Kubernetes version

<details>

```console
$ kubectl version
1.23.3
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>
Windows Server 2019 Datacenter x64
</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerD
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Flannel

**Comment by neolit123** [comment]
please log the issue in https://github.com/kubernetes-sigs/sig-windows-tools that is where the tools like Install-Containerd.ps1 are hosted.

/sig windows
/close
