### ISSUE TITLE
Having two Default StorageClasses should be handled better

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#110514]
Presumably this would occur when changing the default from one class to another.  E.g. 

* Class X exists and is marked default
* Class Y is created
* Class Y is marked as default
* Uh oh!!  2 defaults
* Class X is marked as not default
 
At the case in point, when there are 2 defaults, we currently do not assign default values to new PVCs.

We should change this semantic - while there are two, pick one randomly or heuristically.  It's still correct.

Example: Suppose that you have one user changing the default and another user creating a PVC at exactly the same time. What happens?

Depending on network, CPU scheduling, memory allocations, (etc - totally non-deterministic) the API server might see either of those operations first.  The PVC creator will either win the race and get the old default class or it will lose the race and get the new default class.  The difference could literally be whose network has a faster path to the API server.

My point is that whichever one you pick, as long as it is one of those two defaults, it is a correct choice!

Any other FooClass things we do should probably change, too.  I think that's IngressClass and RuntimeClass.

**Comment by danishprakash** [comment]
@thockin picking either sounds reasonable but what if we allow only one default to be set and disallow/warn users if they try to create another default. I can think of issues with this too, mainly when switching over to a new default by removing an existing class A and then setting B as a default but managing that orphaned period while the transition happens, maybe we can have the heuristic there? I'm sure I'm missing something here.

**Comment by jsafrane** [comment]
> disallow/warn users if they try to create another default

There is a problem when there is no default storage class for a while and another user creates a PVC. Such PVC won't get the new SC. We're trying to fix it in https://github.com/kubernetes/enhancements/pull/3337. Until then, having two default storage classes for a brief moment is IMO slightly better, because at least users get an error message and can retry PVC creation.

In addition, (in-tree) admission plugin in HA environment could be racy, as different API servers are admitting updates of different StorageClasses in parallel.

**Comment by thockin** [comment]
I wouldn't make 2 an error - just pick one.

**Comment by danishprakash** [comment]
Ok, I'd take a shot at this. Thanks for clearing things up.

**Comment by jsafrane** [comment]
> I wouldn't make 2 an error - just pick one.

+1

Still, having two default classes for a longer time is IMO bad, there should be a metric + alert if there are 2 or more default SCs for X minutes.

**Comment by thockin** [comment]
@jsafrane it's not ideal - a metric seems OK

**Comment by sachinrastogi12** [comment]
hello there, im new to open source. i don't know how to contribute. can anyone hep me please?

**Comment by kapiljain1989** [comment]
I see this issue was labeled as "good first issue" and I would like to start working on it!

**Comment by kidddddddddddddddddddddd** [comment]
I see there is a pr related to this issue #110559 , @danishprakash are you still working on this?

**Comment by just-injoey** [comment]
Is this issue still open?

**Comment by danishprakash** [comment]
Yes, there's already a [PR](https://github.com/kubernetes/kubernetes/pull/110559). It's linked to the issue itself.

**Comment by thockin** [comment]
Oh, I see the second PR, too.  Will look at them ASAP

**Comment by sftim** [comment]
Do we emit a `Warning:` response header when someone makes a request that ends up setting two IngressClasses as default?

**Comment by aojea** [comment]
that seems a nice thing to do, I didn't know you can add warnings on admissions plugins but seems @liggitt implemented it here

https://github.com/kubernetes/kubernetes/blob/aea9f9887d08922378b9e7da0e81a46e733f2995/plugin/pkg/admission/security/podsecurity/admission.go#L184-L186

**Comment by jsafrane** [comment]
> whichever one you pick, as long as it is one of those two defaults, it is a correct choice!

StorageClass implementation is in https://github.com/kubernetes/kubernetes/pull/110974

> Any other FooClass things we do should probably change, too. I think that's IngressClass and RuntimeClass

I am not sure about those. I'd suggest opening separate issues.

/close
