### ISSUE TITLE
Deployment Spec - Creates Pod with different name if it is around 62 characters in length.

### ISSUE THREAD

**Issue by nitheshrayuduv** [kubernetes/kubernetes#110500]
### What happened?

Tried Crating 3 pods using an Deployment Spec with name length of 62 characters, The Created Pods don't have the correct name when the pods get created.

name in spec.
enter-prise-json-schema-validator-service-44-deployment6-20221

name of pod created.

enter-prise-json-schema-validator-service-44-deployment6-2bhn8f
enter-prise-json-schema-validator-service-44-deployment6-2rslj5
enter-prise-json-schema-validator-service-44-deployment6-277tkq

As Specified in the Documentation, The Name should be name in `spec+"-"+<pod-template-hash>+"-"+<Random String>`

Sample Deployment Spec.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-prise-json-schema-validator-service-44-deployment6-20221
  namespace: default2
  labels:
    app: service
    name: enter-prise-json-schema-validator-service-44-deployment6-20221
spec:
  selector:
    matchLabels:
      app: enterprise-json-schema-validator-service-20221service2345
  replicas: 3
  template:
    metadata:
      labels:
        app: enterprise-json-schema-validator-service-20221service2345
    spec:
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080

### What did you expect to happen?

As Specified in the Documentation, The Name should be name in spec+"-"+<pod-template-hash>+"-"+<Random String>

Sample : 

enter-prise-json-schema-validator-service-44-deployment6-20221+"-"+<pod-template-hash>+"-"+<Random String>

### How can we reproduce it (as minimally and precisely as possible)?

Please use the below Spec or any Spec where we have 62 character deployment name.

Sample Deployment Spec.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-prise-json-schema-validator-service-44-deployment6-20221
  namespace: default2
  labels:
    app: service
    name: enter-prise-json-schema-validator-service-44-deployment6-20221
spec:
  selector:
    matchLabels:
      app: enterprise-json-schema-validator-service-20221service2345
  replicas: 3
  template:
    metadata:
      labels:
        app: enterprise-json-schema-validator-service-20221service2345
    spec:
      containers:
        - name: httpd
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
`Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}`

</details>


### Cloud provider

<details>
Local Kubernetes/Self Hosted Linux System
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux intgn-km 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
The reason is https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
- pod name contain at most 63 characters

**Comment by nitheshrayuduv** [comment]
Hi :) , Hope you are having a great day, Yes Pod Contains 63 characters at max.

We are Creating a Deployment that creates pods internally, the logic to Create the pod names from Deployment name is actually not proper.

The Deployment name is actually being replaced by the hash to 63 characters at the end.

Shouldn't the logic for creating pod names from deployment spec throw an error/warning stating that if the name of the Deployment is above 58-62 the final few letters can get replaced by an hash.

1) May be the Deployment spec name when we create a pod internally should have a limit 58 instead of 63. else the last few characters of the name get "replaced"

**Comment by nitheshrayuduv** [comment]
Sample 

Deployment name: (62 characters)

qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq1q

Podname (Kubernetes created this from Deployment name, the last 5 got replaced by random string)

qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq**vn7jm**

**Comment by liggitt** [comment]
/close

This is working as designed, the name in the template is shortened if needed to accomodate the random suffix while still staying within the pod name length limitations.
