### ISSUE TITLE
What is the exact format for Mongo-URI when connecting to a Kubernetes MongoDB instance

### ISSUE THREAD

**Issue by Ed87** [kubernetes/kubernetes#110517]
**Name and Version**
docker.io/bitnami/mongodb:4.4.6-debian-10-r0

What steps will reproduce the issue?

1. `kubectl exec -it <pod_name> -- sh`
2. Run mongodump command while passing a MongoURI to the command

**What is the expected behavior?**
I want to setup backups for my MongoDB instance and the k8s cron job that executes these backups _will need a Mongo-URI in order to connect to the deployment_ .

If the CronJob connects successfully it will execute the backup and dump the files at a path specified in the job Dockerfile.

I expect to be able to test a MongoURI value  _**for connectivity**_ first before I plug it into the job. To do this I exec into the pod and attempt to do mongodump .

I am following the example given [here](https://simodev.medium.com/how-to-automate-backup-mongodb-using-kubernetes-b07c61a8a6ec)

**What do you see instead?**

I want to backup a database named platforms using the default built-in root user (specified [here](https://docs.bitnami.com/aws/infrastructure/mongodb/administration/backup-restore-mongodb/)) and I am getting the following errors :

a)` kubectl exec -it <pod_name> -- sh`

`mongodump --uri="mongodb://root:PASSWORD@mongo-headless-service.svc.cluster.local:27017/platforms" --authenticationDatabase admin --gzip --out /var/backups/dump-25-05-22/mybackup.gz`

I get error:
`2022-06-10T12:37:41.690+0000 Failed: can't create session: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongo-headless-service.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongo-headless-service.svc.cluster.local: no such host }, ] }`

b) `kubectl exec -it <pod_name> -- sh`
`
mongodump --uri="mongodb://root:PASSWORD@mongodb-headless-service/platforms?authSource=admin" --gzip --out /var/backups/dump-25-05-22/mybackup.gz`

I get error
`Failed: can't create session: could not connect to server: connection() : auth error: sasl conversation error: unable to authenticate using mechanism "SCRAM-SHA-1": (AuthenticationFailed) Authentication failed.`

c) `kubectl exec -it <pod_name> -- sh`

`mongodump --uri="mongodb://root:PASSWORD@mongo-headless-service.svc.cluster.local:27017/admin" -d admin --gzip --out /var/backups/dump-25-05-22/mybackup.gz`

I also get an error
`2022-06-10T11:36:38.578+0000 Failed: can't create session: could not connect to server: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: mongo-headless-service.svc.cluster.local:27017, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp: lookup mongo-headless-service.svc.cluster.local: no such host }, ] }`

I tried to verify if the default built-in user can indeed authenticate against the admin db :
```
use admin
db.auth('root','PASSWORD')
```
It also fails with Authentication Failed (I expected the the built-in root to connect by default ?? )

**Additional information**
For context I intend to use the Mongo-URI value in my CronJob defined as below :

`apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodump-backup
spec:
  schedule: "0 */6 * * *" #Cron job every 6 hours
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongodump-backup
              image: microfunctions/microfunctions-mongodump
              imagePullPolicy: "IfNotPresent"
              env:
                - name: DB_NAME
                  value: "microfunctions"
                - name:  MONGODB_URI
                  value: mongodb://microfunctions:UxXKmC9EAn@host-mongodb:27017/microfunctions
              volumeMounts:
                - mountPath: "/mongodump"
                  name: mongodump-volume
              command: ['sh', '-c',"./dump.sh"]
          restartPolicy: OnFailure
          volumes:
            - name: mongodump-volume
              persistentVolumeClaim:
                claimName: mongodb-backup`

My MongoDB Deployment :
`apiVersion: apps/v1
kind: Deployment
metadata:
name: mongodb-deployment
namespace: labs
labels:
app: mongodb
spec:
replicas: 1
selector:
matchLabels:
app: mongodb
template:
metadata:
labels:
app: mongodb
spec:
containers:
- name: mongodb
image: docker.io/bitnami/mongodb:4.4.6-debian-10-r0
imagePullPolicy: "IfNotPresent"
securityContext:
runAsNonRoot: true
runAsUser: 1001
ports:
- containerPort: 27017
env:
- name: MONGO_INITDB_ROOT_USERNAME
valueFrom:
secretKeyRef:
name: mongodb-secret-amended
key: mongo-root-username
- name: MONGO_INITDB_ROOT_PASSWORD
valueFrom:
secretKeyRef:
name: mongodb-secret-amended
key: mongo-root-password
volumeMounts:
- mountPath: /data/db
name: mongodb-vol
volumes:
- name: mongodb-vol
persistentVolumeClaim:
claimName: mongodb-claim
apiVersion: v1
kind: Service
metadata:
name: mongodb-service
namespace: labs
spec:
type: NodePort
selector:
app: mongodb
ports:
- protocol: TCP
port: 27017
targetPort: 27017
apiVersion: v1
kind: Service
metadata:
name: mongodb-headless-service
namespace: labs
spec:
selector:
app: mongodb
ports:
- protocol: TCP
port: 27017
targetPort: 27017
apiVersion: v1
kind: Service
metadata:
name: mongo-single-clusterip
namespace: labs
spec:
type: ClusterIP
selector:
app: mongodb
ports:
- protocol: TCP
port: 27017
targetPort: 27017`

What am I missing ?

**Comment by alberthuang24** [comment]
Does `kubectl exec -it <pod_name> -- sh` where `<pod_name>` refers to the mongo pod itself? Or is it a pod for another service? If it is mongo itself, you can replace `mongo-headless-service.svc.cluster.local` with `localhost`, otherwise please let me see your service file definition

**Comment by Ed87** [comment]
@alberthuang24  `kubectl exec -it <pod_name> -- sh` refers to the Mongo pod itself. Eventually I want run the command from another pod for another service - in this case I will use the command in my CronJob (you can check the link I pasted for the example Im following).

I have replaced  `mongo-headless-service.svc.cluster.local` with `localhost` but I am getting Authentication Failed error :

<img width="663" alt="image" src="https://user-images.githubusercontent.com/23119187/173203399-01f0afe3-81ec-4124-946b-a5ac48e4f658.png">

This is quite confusing because according to the documentation [here](https://docs.bitnami.com/aws/infrastructure/mongodb/administration/backup-restore-mongodb/) this is the default non-root user and since Bitnami Mongo images run as non-root this is the only user that is able to run backups.
My expectation was that this user should authenticate to all databases by default.

I am sure _localhost_ should work so that now leaves me with two issues :

1.  Why is the default root user failing to authenticate ?

2. If I am doing the mongodump from another pod (_which I intend to eventually_ )  what URI will I use for the mongo pod.

**Comment by Ed87** [comment]
@alberthuang24   replacing with localhost is working :
`kubectl exec -it <pod_name> -- sh`

`mongodump --uri="mongodb://root:PASSWORD@localhost:27017/platforms" --authenticationDatabase admin --gzip --out /tmp/dump-12-06-22/mybackup.gz
2022-06-12T11:51:03.264+0000    writing platforms.tools to /tmp/dump-12-06-22/mybackup.gz/platforms/tools.bson.gz
2022-06-12T11:51:03.270+0000    done dumping platforms.tools (2 documents)`

My issue now is when connecting to the MongoDB pod _from a pod in another service_  , it seems the Mongo-URI scheme I am passing is invalid:
 
The other pod is also a MongoDB deployment , in a replicaset  and  to test the URI connection I did :

`kubectl exec -it mongodb-0 -- sh`

`mongo mongodb://root:PASSWORD@mongodb-headless-service.svc.cluster.local/platforms?authSource=admin`

getting error :

` mongo mongodb://admin:abc123@mongodb-headless-service.svc.cluster.local/platforms?authSource=admin
MongoDB shell version v5.0.9
connecting to: mongodb://mongodb-headless-service.svc.cluster.local:27017/platforms?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server mongodb-headless-service.svc.cluster.local:27017, connection attempt failed: HostNotFound: Could not find address for mongodb-headless-service.svc.cluster.local:27017: SocketException: Host not found (authoritative) :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1`

Both MongoDB instances/services are in the same namespace .

**Comment by pacoxu** [comment]
/kind support
See https://kubernetes.io/blog/2017/01/running-mongodb-on-kubernetes-with-statefulsets/ for more details.
```
This means the DNS names for the MongoDB replica set are:

mongo-0.mongo
mongo-1.mongo
mongo-2.mongo
```
