### ISSUE TITLE
kube-scheduler preemption logic deadlock when it evicts a Pod with a volume to make room for the CSI driver Pod

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#110637]
### What happened?

We managed to reproduce and verify the following deadlock that occurs when kube-scheduler evicts a Pod (with less priority) to make room for a CSI driver Pod.
1. New csi-driver-node-disk Pod has to be created for Node `worker-1` (caused by autoscaling event like scale-up or Pod lifecycle event). Pod csi-driver-node-disk has PriorityClass `system-node-critical` (`2000001000` priority class value).
2. Node `worker-1` is full and kube-scheduler has to activate the preemption logic (ref https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/) to make room for Pod csi-driver-node-disk. At this time Pod csi-driver-node-disk is in Pending state.
3. kube-scheduler evicts a Pod with **a volume**. But the corresponding Pod deletion hangs forever in Terminating as there is no running `csi-driver-node-disk` Pod for the given Node to perform the unmount operations.

There is no automatic recovery from this case -> csi-driver-node-disk Pod stays forever in Pending, the evicted Pod stays forever in Terminating.

See below for more detailed steps to reproduce.

### What did you expect to happen?

No such deadlock to be possible to be caused in the system

### How can we reproduce it (as minimally and precisely as possible)?

1. Prepare a Node that is almost full (cpu or memory). Make sure that all of the running workload on this Pod has volumes

```
$ k describe no worker-1

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests          Limits
  --------           --------          ------
  cpu                1887m (98%)       100m (5%)
  memory             1169187818 (39%)  14972Mi (532%)
```

2. Increase the `csi-driver-node-disk` DaemonSet cpu requests high enough to make sure that it won't fit on the Node (simulate a scale-up event by autoscaler)

3. Make sure that the new csi-driver-node-disk Pod fails to be scheduled with:
```
$ k -n kube-system describe po csi-driver-node-disk-4m7vz

Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  10m                  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector.
  Warning  FailedScheduling  8m56s (x1 over 10m)  default-scheduler  0/2 nodes are available: 1 Insufficient cpu, 1 node(s) didn't match Pod's node affinity/selector.
```

The csi-driver-node-disk Pod has PriorityClass `system-node-critical`.

4. Make sure that kube-scheduler tries to evict 1 of the Pods with lower priority

```
$ k get po
NAME    READY   STATUS        RESTARTS   AGE
web-0   1/1     Running       0          21m
web-1   1/1     Running       0          21m
web-2   0/1     Terminating   0          21m
```

5. Make sure the deletion of this web-2 Pod (that has a volume) hangs forever because there is no running csi-driver-node-disk Pod for this Node to perform the unmount operations.

kubelet log:
```
E0617 11:33:53.547111    3074 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/disk.csi.azure.com^/subscriptions/<omitted>/resourceGroups/shoot--foo--bar/providers/Microsoft.Compute/disks/pv-shoot--foo--bar-c2561535-78a0-432e-9364-681c36b4d674 podName:ba6a8d0c-6018-436a-a7cb-83cb61341537 nodeName:}" failed. No retries permitted until 2022-06-17 11:35:55.547035965 +0000 UTC m=+13631.726363595 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"www\" (UniqueName: \"kubernetes.io/csi/disk.csi.azure.com^/subscriptions/<omitted>/resourceGroups/shoot--foo--bar/providers/Microsoft.Compute/disks/pv-shoot--foo--bar-c2561535-78a0-432e-9364-681c36b4d674\") pod \"ba6a8d0c-6018-436a-a7cb-83cb61341537\" (UID: \"ba6a8d0c-6018-436a-a7cb-83cb61341537\") : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name disk.csi.azure.com not found in the list of registered CSI drivers"
```

### Kubernetes version

<details>

I confirmed the issue with v1.21.10 but it should be possible to reproduce it with newer K8s versions as well.

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Gardener
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

For this issue description [azuredisk-csi-driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver) but it should be possible to reproduce it with any similar CSI driver.

</details>

**Comment by kerthcet** [comment]
Well, I don't think this is a bug. Daemonsets used to help configuring services/pods easily across clusters, so we should ensure them setup successfully for best servicing. But we can mitigate this by:
1. when  scheduling, nodes with multi volume-binding pods should score less.
2. when preempting, we should consider non-volume-binding pods first.

/remove-kind bug
/kind feature

**Comment by wackxu** [comment]
We also encountered this problem in the production environment. Could you give some suggestions for fixing it? cc @msau42 @sanposhiho @Huang-Wei

**Comment by Huang-Wei** [comment]
To mitigate this issue, scheduler may offer dynamic (or even configurable) preemption preferences when it chose preemption victims. But the problem is unresolvable if feasible victim candidate pod(s) on that node are **all volume-attached**.

> We also encountered this problem in the production environment.

Is there an alternative preemption strategy to preempt other pods to make room for the csi daemon pod?

**Comment by wackxu** [comment]
No, the candidate pods in our cluster are all volume-attached. Can we reserve node resources for some key components in the cluster, such as CSI, CNI, etc. so that when these components are upgraded, the resources will not be occupied by other business pods to avoid preemption

**Comment by wackxu** [comment]
Or can we sense whether key components on the node such as csi, cni, etc. are ready during scheduling? If not, prevent pods that rely on key components from being scheduled to the node. The problem with this solution is that we need to consider the time delay between status reporting and scheduling

**Comment by kerthcet** [comment]
>  Can we reserve node resources for some key components in the cluster, such as CSI, CNI, etc 

If you mean something like **kube-reserved**, yes, we do, but they're not for pods. https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved

**Comment by wackxu** [comment]
> > Can we reserve node resources for some key components in the cluster, such as CSI, CNI, etc
> 
> If you mean something like **kube-reserved**, yes, we do, but they're not for pods. https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/#kube-reserved

Yes, we use kube-reserved to reserve resources for key processes on the node such as kubelet. Here we hope to reserve resources for key pods in the cluster. We can do this resource reservation at the scheduler level.

**Comment by alculquicondor** [comment]
Isn't this a problem in the node or CSI side? If the Pod is stuck in termination, there is nothing scheduler can do.

@kubernetes/sig-storage-misc, any ideas?

**Comment by wackxu** [comment]
> Isn't this a problem in the node or CSI side? If the Pod is stuck in termination, there is nothing scheduler can do.
> 
> @kubernetes/sig-storage-misc, any ideas?

Could we reserve resources for key pods in the cluster to prevent this deadlock.

**Comment by alculquicondor** [comment]
You could use a taint that your CSI driver can remove when it's ready

**Comment by wackxu** [comment]
> You could use a taint that your CSI driver can remove when it's ready
In some scenarios, we will upgrade the resource request of the CSI driver. If the resources on the node are not enough, preemption will occur. Because our business pods all use PVC, this kind of deadlock will also occur. In this scenario, can kubelet be optimized to solve this problem when the pod is deleted and storage resources are released? cc @kubernetes/sig-node-bugs

**Comment by kerthcet** [comment]
Resource reservation can help with this but we're far from that, and that's beyond the scope of scheduler, also involves other components like kubelet etc.. 

But a simplified implementation is a resource reservation only work for scheduler and plumbed into scheduler framework as a plugin.

**Comment by mimowo** [comment]
@ialidzhikov could you try reproducing the issue on 1.26+? It might be already fixed , see: https://github.com/kubernetes/kubernetes/issues/120917#issuecomment-1799118331.

**Comment by wackxu** [comment]
> @ialidzhikov could you try reproducing the issue on 1.27+? It might be already fixed , see: [#120917 (comment)](https://github.com/kubernetes/kubernetes/issues/120917#issuecomment-1799118331).

I have test it on 1.27+, and the problem does not occur

**Comment by mimowo** [comment]
> I have test it on 1.27+, and the problem does not occur

Great to hear.

I think what is happening, is that the `web-2` pod in 1.27 is transitioned to terminal phase (Failed or Succeeded), and this allows the scheduler to schedule the `csi-driver-node-disk` pod. As discussed in https://github.com/kubernetes/kubernetes/issues/120917 the pod can be transitioned to terminal phase before the volumes are fully unmounted.

Could you also test on 1.26 to verify it occurs? It would give us a strong signal that https://github.com/kubernetes/kubernetes/pull/115331 fixed the issue.

**Comment by ahg-g** [comment]
this seems to be resolved as per https://github.com/kubernetes/kubernetes/issues/110637#issuecomment-1813610108

/close
