### ISSUE TITLE
Installing from yum repo leads to repo signature verification error

### ISSUE THREAD

**Issue by manaschandrasahoo** [kubernetes/kubernetes#110667]
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
exclude=kubelet kubeadm kubectl

[root@master yum.repos.d]# sudo yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.excellmedia.net
 * extras: centos.excellmedia.net
 * updates: centos.excellmedia.net
base                                                                                                                                                                      | 3.6 kB  00:00:00
extras                                                                                                                                                                    | 2.9 kB  00:00:00
kubernetes/x86_64/signature                                                                                                                                               |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes/x86_64/signature                                                                                                                                               | 1.4 kB  00:00:00 !!!
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.

 One of the configured repositories failed (Kubernetes),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kubernetes ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kubernetes
        or
            subscription-manager repos --disable=kubernetes

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kubernetes.skip_if_unavailable=true

failure: repodata/repomd.xml from kubernetes: [Errno 256] No more mirrors to try.
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
[root@master yum.repos.d]#

**Comment by sftim** [comment]
https://github.com/kubernetes/release/issues/913#issuecomment-1081121833 is also relevant.

**Comment by BenTheElder** [comment]
> There is a bug where the repository isn't signed. As I understand it, the docs are right and the lack of repository signing is actually a bug; however, there is no clear plan to fix that bug.


Just to clarify: AIUI the GCP RPM repomd.xml **is** signed, however the previous key expired and it is signed with a new key, but yum will only checks the first key in the keyring for repo signatures. The published content has actually always been signed with multiple keys / signatures but yum will only consider the first key, signature.

https://github.com/rpm-software-management/yum/blob/f8616a2d6e22705371fe6ba47597238d3d1dc2f1/yum/misc.py#L72-L77

for googlers: b/181554122#comment93 has more context

The rapture (google package host) team considers yum's repo_gpgcheck feature broken, hence the suggestion to turn it off.

There was also a change on the Google side to fully rotate out the old keyring and have a valid key listed first, but that won't fix all existing clients => directions to disable repo GPG check.

It should be possible to instead fix how yum handles keys here, except that yum is deprecated and replaced by DNF:
https://github.com/rpm-software-management/yum/blob/master/README.md

I don't know if dnf also has this issue.

**Comment by sftim** [comment]
Thanks for clarifying @BenTheElder. It'd be good to see whether `dnf` does work OK because, if so, we can absolutely document that.

I've been really wary of teaching folks to turn off a signature check here, especially as we're a prominent project. There have been actual attacks that a check here does mitigate. It'd be great to qualify any advice with something like “if you're unable to adopt `dnf` and have considered the risks, ~ready the footgun~ use this config option: &hellip;'”.

**Comment by BenTheElder** [comment]
Ack though,

> There have been actual attacks that a check here does mitigate.

This is unclear to me. I found reference to a bug in how the metadata was handled in the past that was considered mitigated by this but the bug should be fixed.

Even if the attacker can hijack the HTTPS transport to Google / the repo and respond with a false repomd.xml, this only contains the list of packages that we *still* check the signature on when installing.

If we assume the attacker can respond with their own keys because they've hijacked the TLS connection, we're in trouble repo signature check or not unless this isn't the first package install.

The internal bug notes that centOS doesn't **have** a repo signature. AFAIK 0 is the default for this setting.

What specifically do we think we're opening the user up to?

**Comment by sftim** [comment]
Docs updates in https://github.com/kubernetes/website/pull/34546

**Comment by sftim** [comment]
OK to close this?

**Comment by dipankardas011** [comment]
Its working in fedora 36
![image](https://user-images.githubusercontent.com/65275144/184466580-b0f7cc8b-4a3f-415a-8544-13e29be7ef09.png)

**Comment by dipankardas011** [comment]
@manaschandrasahoo @sftim 
Created a New VM having Fedora 36.
Wasn't able to Replicate the issue of signature validation using yum package manager.
https://docs.google.com/document/d/14zIvdEQXVEuFlfhDXm_zjmeisNNZul-KAI23CPq8gR8/edit?usp=sharing
then installed Docker and kind for testing
