### ISSUE TITLE
Windows: Disappearing/missing windows loadbalancers for k8s services

### ISSUE THREAD

**Issue by shettyg** [kubernetes/kubernetes#110674]
### What happened?

In our windows clusters, sometimes, we notice that the windows pod cannot access a clusterIP service. 

The instances we have seen this issue is when a windows pod tries to resolve a DNS name by trying to contact the DNS server clusterIP (i.e nslookup fails from inside a pod). When this happens, a `hnsdiag list loadbalancers` does not show the VIP for the kube-dns clusterIP. But kube-proxy logs indicate that this loadbalancer was created. So it likely got deleted at some point (or did not get created at all).  The DNS server inside the pod is correct. As an experiment, we reset DNS server (inside pod) to one of the kube-dns endpoint IP (directly pod IP) address and nslookup worked correctly. We set it back to DNS clusterIP and it started failing again.

Once we delete a kube-dns pod (running on a linux node) to let it get recreated, we see that a new event to windows kube-proxy will trigger the creation of loadbalancer again and things start working correctly.

CC: @jsturtevant @daschott 

### What did you expect to happen?

We expect that the windows loadbalancers is in sync with kubernetes services.

### How can we reproduce it (as minimally and precisely as possible)?

There is no easy reproduction case.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
API server: 1.22.8
Nodes: 1.21.10

### Cloud provider

<details>

</details>
GKE

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
This is Windows 2019 server. I will update the bug with exact details soon (as soon as I get access to those nodes again).

PS C:\Windows\system32> wmic os get Version
Version
10.0.17763

PS C:\Windows\system32> wmic os get Caption
Caption
Microsoft Windows Server 2019 Datacenter

PS C:\Windows\system32> wmic os get Version
Version
10.0.17763

PS C:\Windows\system32> wmic os get BuildNumber
BuildNumber
17763

PS C:\Windows\system32> wmic os get OSArchitecture
OSArchitecture
64-bit

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by shettyg** [comment]
I am providing certain logs. The clusterIP for the reproduction case is `10.24.208.10`.

Relevent kube-proxy log:

cat kube-proxy.log  | grep 10.24.208.10

```
I0512 17:55:28.274922    1228 service.go:421] Adding new service port "kube-system/kube-dns:dns" at 10.24.208.10:53/UDP
I0512 17:55:28.274922    1228 service.go:421] Adding new service port "kube-system/kube-dns:dns-tcp" at 10.24.208.10:53/TCP
I0512 17:55:30.807341    1228 proxier.go:245] "%s" Hns loadbalancer policy resource="hostComputeLoadBalancer" {"ID":"ec2adf51-3078-445d-828e-c18a72865c95","HostComputeEndpoints":["781833e6-0b15-4d73-a11c-97f0d6947b23","7897b232-24eb-4e7f-9f77-88956a7a8f51"],"FrontendVIPs":["10.24.208.10"],"PortMappings":[{"Protocol":6,"InternalPort":53,"ExternalPort":53}],"SchemaVersion":{"Major":2,"Minor":0},"Flags":1}="(MISSING)"
I0512 17:55:41.415457    1228 proxier.go:245] "%s" Hns loadbalancer policy resource="hostComputeLoadBalancer" {"ID":"924e6ff5-ff5b-4f5f-af29-69cb02bbb3ed","HostComputeEndpoints":["781833e6-0b15-4d73-a11c-97f0d6947b23","7897b232-24eb-4e7f-9f77-88956a7a8f51"],"FrontendVIPs":["10.24.208.10"],"PortMappings":[{"Protocol":17,"InternalPort":53,"ExternalPort":53}],"SchemaVersion":{"Major":2,"Minor":0},"Flags":1}="(MISSING)"

```

The entire output of `hnsdiag list loadbalancers` (where you can see that there is no entry for `10.24.208.10`).

https://gist.github.com/shettyg/542f7e7b87acacb9b67cfac7139d5baa

The entire kube-proxy log for that windows node.
[kube-proxy.log.gz](https://github.com/kubernetes/kubernetes/files/8945950/kube-proxy.log.gz)

**Comment by shettyg** [comment]
The kube-proxy runs as a windows service and runs in kernel mode.

**Comment by jsturtevant** [comment]
There is a discussion happening in slack: https://app.slack.com/client/T09NY5SBT/C0SJ4AFB7/thread/C0SJ4AFB7-1655734589.090519

**Comment by daschott** [comment]
how large is your cluster? How many pods/services exist in the cluster?

**Comment by shettyg** [comment]
>how large is your cluster? How many pods/services exist in the cluster?

The cluster is 16 windows nodes and 4 linux nodes. It has 190 pods (in all namespaces and all nodes). It has 140 pods in windows nodes. It has 100 kubernetes services.

@daschott

**Comment by adoprog** [comment]
We encountered the same issue, using mix of Linux and Windows nodes on AKS. Sometimes Windows pods would lose connection to Linux-hosted MSSQL or Solr when we start the workload. Possibly Windows->Windows connectivity is an issue as well but these services don't often communicate in our scenarios.

We do shutdown workloads nightly, and in the morning some "instances" would not start properly because of this.
"Instances" consist of 7-10 pods in the same namespace, we "turn them on" by changing # of replicas from 0 to 1 for all deployments in namespace simultaneously.

This also happens frequently during "restart" (killing all pods in a namespace simultaneously).

**Comment by daschott** [comment]
Does the issue remediate itself given enough time? Does kube-proxy eventually realize the desired state, so that you see the expected VIP in the "hnsdiag list loadbalancers" output, or does it never show up, despite waiting?

@adoprog which K8s version were you using?

There are a few known issues with kube-proxy taking long time to reconcile and sync the proxy rules on Windows, see https://github.com/kubernetes/kubernetes/issues/109162 

fix: https://github.com/kubernetes/kubernetes/pull/109124
https://github.com/kubernetes/kubernetes/pull/110701 for backport to v1.22

**Comment by shettyg** [comment]
>Does the issue remediate itself given enough time? Does kube-proxy eventually realize the desired state, so that you see the expected VIP in the "hnsdiag list loadbalancers" output, or does it never show up, despite waiting?

It does not get fixed (in our case, the problem persisted for 2 days).

**Comment by zhiweiv** [comment]
We encounter this frequently, I run **hnsdiag list loadbalancers** every minutes with Host Process Container on each Windows node. When issue happen, the load balancer count dropped to 1 and recover slowly, it took about 2 days to recover right count. You can find more logs in  
[hns.txt](https://github.com/kubernetes/kubernetes/files/8987894/hns.txt)

06-06 02:57 - loadbalancers: 577
06-06 02:58 - loadbalancers: 577
**06-06 02:59 - loadbalancers: 577
06-06 03:00 - loadbalancers: 1              
06-06 03:11 - loadbalancers: 15**
06-06 03:12 - loadbalancers: 15
06-06 03:13 - loadbalancers: 15

I opened two support ticket before, MS Support asked me to wait for https://github.com/kubernetes/kubernetes/pull/109124.
Ticket number here, conversations are in Chinese.
2204250060000724
2206070060000125

**Comment by zhiweiv** [comment]
Restart kubeproxy will fix this, I now use script to fix it with Host Process Container as workaround.
```
$tick = 0
while($true)
{
	$time = Get-Date -Format 'MM-dd HH:mm'
	$count = (hnsdiag list loadbalancers | Measure-Object -Line).Lines
	if($count -gt 100)
	{
		$tick = 0
	}
	else
	{
		$tick = $tick + 1
	}
	echo "$time - loadbalancers: $count, tick: $tick"
	if($tick -ge 5)
	{
		$tick = -10
		echo "$time - Restart kubeproxy"
		Restart-Service kubeproxy
	}
	Start-Sleep 60
}
```

**Comment by perosb** [comment]
> Restart kubeproxy will fix this, I now use script to fix it with Host Process Container as workaround.
> 
> ```
> $tick = 0
> while($true)
> {
> 	$time = Get-Date -Format 'MM-dd HH:mm'
> 	$count = (hnsdiag list loadbalancers | Measure-Object -Line).Lines
> 	if($count -gt 100)
> 	{
> 		$tick = 0
> 	}
> 	else
> 	{
> 		$tick = $tick + 1
> 	}
> 	echo "$time - loadbalancers: $count, tick: $tick"
> 	if($tick -ge 5)
> 	{
> 		$tick = -10
> 		echo "$time - Restart kubeproxy"
> 		Restart-Service kubeproxy
> 	}
> 	Start-Sleep 60
> }
> ```

Yes, got the same that loadbalancers dropped down from ~100 to 12 and network started failing.
`restart-service kubeproxy` resolved it.

The error got triggered during a deploy that updated 30+ pods.

**Comment by adoprog** [comment]
> Does the issue remediate itself given enough time? Does kube-proxy eventually realize the desired state, so that you see the expected VIP in the "hnsdiag list loadbalancers" output, or does it never show up, despite waiting?
> 
> @adoprog which K8s version were you using?
> 
> There are a few known issues with kube-proxy taking long time to reconcile and sync the proxy rules on Windows, see #109162
> 
> fix: #109124 #110701 for backport to v1.22

We're on v1.23.5

**Comment by jsturtevant** [comment]
@zhiweiv @perosb the symptoms you are experience appear different than the ones reported by @adoprog and @shettyg.  Do we have an open issue for this issue where you are tracking this or can you create one?

**Comment by zhiweiv** [comment]
Do you mean the GitHub issue? I will create one.

**Comment by shettyg** [comment]
We are seeing more cases of this issue across multiple clusters. @jsturtevant I see that it has been marked as "In Progress" - do we have more insight on the reason for the bug? Are there areas, wherein adding debug statements give us more data?

**Comment by sbangari** [comment]
@shettyg  Can you collect the output of this script on the node (if possible within a day after the issue reproduces)? 
https://github.com/microsoft/SDN/blob/master/Kubernetes/windows/debug/collectlogs.ps1

**Comment by shettyg** [comment]
As a general update of sig-windows slack discussion, for the latest case of this issue, I saw the same symptoms as https://github.com/kubernetes/kubernetes/issues/111323. i.e running a command of the form:

```
Get-WinEvent -FilterHashtable @{logname = 'System'; ProviderName = 'Service Control Manager' } | Select-Object -Property TimeCreated, Id, LevelDisplayName, Message | Format-Table -Wrap -Autosize
```
would show:

```
Error            The Host Network Service service terminated
```

Simulating the HNS crash by running:

```
restart-service -f hns
```

would show that all the kube-proxy created loadbalancers would disappear and only repopulate with new api server events or a restart of kube-proxy.
