### ISSUE TITLE
The number conversion of `Value()` of type Quantity is inaccurate

### ISSUE THREAD

**Issue by hoyhbx** [kubernetes/kubernetes#110654]
### What happened?

We were constructing a Quantity instance using `resource.ParseQuantity()` with `-.1Ki`, then we call the method `Value()` to extract the value from the Quantity instance. When we used `-.1Ki` as the input, the output was `-101`. However, when we used `.1Ki` as input, the output was `103`. 

### What did you expect to happen?

When we construct the Quantity object with two different inputs: `-.1Ki` and `.1Ki`, we expected that the difference between the two outputs of the method `Value()` to only be the sign. 
That is, the absolute value of the two outputs should be consistent since the only difference between the two inputs is the sign. However, the results for these scenarios are inconsistent. The value for `-.1Ki` is `-101` and the value for `1Ki` is `103`.

We consider `-101` (resource.ParseQuantity(`-.1Ki`).Value()) output of as an inaccurate value. Given that the input is `-.1Ki`, the precise value should be `-102.4`. According to the definition of `Value()`:

> Value returns the unscaled value of q rounded up to the nearest integer away from 0

which suggests that the expected return value from `Value()` should be `-103`, instead of `-101`.

### How can we reproduce it (as minimally and precisely as possible)?

Simply run the following code with all required packages imported. The output here is `-101`. (Changing `test` to ".1Ki" will give us `103` as output.)

```go
func main() {
	test := "-.1Ki"
	ans, err := resource.ParseQuantity(test)
	if err == nil {
		fmt.Println(ans.Value())
        }
}
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"clean", BuildDate:"2022-05-19T19:53:08Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux XXX 5.13.0-44-generic #49~20.04.1-Ubuntu SMP Wed May 18 18:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fedebongio** [comment]
/assign @yliaog 
this one is similar but slightly different (although related we believe)
/triage accepted
