### ISSUE TITLE
Standalone NEG's group is empty when node preempted 

### ISSUE THREAD

**Issue by pio-janik** [kubernetes/kubernetes#110641]
### What happened?

Network Endpoint Group is empty after node is preempt (We use node pools with preemptible instances). Random groups are affected - We use several NEG's per use case. It happens every 24h (more or less). 
We use deployment with service object annotated by special annotations. (https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg#how_to). After creation this group is used in Internal HTTPS Load Balancer backed service.

When NEG is empty, there are several weird scenarios:
- New pods are in state Running, but don't handle traffic,
- Even deployment modification, new pods fail on readiness probe with "connection refused" error. Any modification to readiness probe has no effects. After some time, pods are in Running state, but still don't handle traffic.
- Service object report error - NEG controller try to add PodIps, that are terminated and no longer serve the traffic: 
> Failed to Attach 5 network endpoint(s) (NEG "k8s1-***" in zone "****"): googleapi: Error 400: Invalid value for field 'resource.ipAddress': '****'. Specified IP address *** doesn't belong to the (sub)network **** or to the instance ****., invalid
- Endpoint object contains PodIps in NotReady sections - but actually this pods have been terminated

This issues can be related with this https://github.com/kubernetes/kubernetes/pull/110255 

As a workaround We remove any pods, that are in state different that running.
`kubectl delete pods -n ingress-nginx --field-selector=status.phase!=Running`
Then NEG is populated with PodIps, lb can handle traffic and NEG controller can attach new pods.

This issue doesn't occur on stable node polls.

### What did you expect to happen?

Even if nodes will be preempted, NEG will be populated with pods that are healthy and ready to maintain traffic.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create GKE cluster with version 1.22.8-gke.201 and preemptible node pool,
2. Create deployment with service object with NEG annotations,
3. Create Internal HTTPS LB and link backed service with NEG

### Kubernetes version

1.22.8-gke.201

### Cloud provider

GCP

### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

GKE default

**Comment by aojea** [comment]
ping @robscott @swetharepakula

**Comment by pio-janik** [comment]
I would like to add one more think - this bug has been occurring since version 1.22, on previous version (1.21) it was working fine.

**Comment by swetharepakula** [comment]
Hello @pio-janik,

This is a known issue due to a kubelet behavior change that was introduced in 1.22 that caused incorrect EndpointSlice & Endpoints. This has been fixed as part of https://github.com/kubernetes/kubernetes/pull/110255.  

Since NEGs are a GKE/GCP specific, this may be better as a support ticket to GCP. However the fix above will fix the issue being described. It is currently being rolled out and will be available soon. I will update once they are available with the GKE versions that you can upgrade to for the fix.

/assign

**Comment by pio-janik** [comment]
Hi @swetharepakula,
Thanks you for the explanation. We will wait for the stable GKE version.

**Comment by swetharepakula** [comment]
The following GKE versions have the fix: `1.22.8-gke.202`, `1.23.6-gke.1501`, `1.24.0-gke.1801`. Please upgrade your cluster to one of those versions.

**Comment by thockin** [comment]
I'll go ahead and close this now, thanks.
