### ISSUE TITLE
replicaset created, but pod created after 5 minutes later

### ISSUE THREAD

**Issue by CharlesQQ** [kubernetes/kubernetes#110631]
### What happened?
replicas `my-deploy-785fb59f49`  scale up at 15:09:02, but pod `my-deploy-785fb59f49-4d5vt` created at 15:14:06
```
Jun 16 15:09:02 xxx kube-controller-manager[24465]: I0616 15:09:02.732471   24465 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"my-deploy", UID:"b1cb01c2-ac0b-11ec-893a-6c92bf8ad956", APIVersion:"extensions", ResourceVersion:"2127766817", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set my-deploy-785fb59f49 to 1
Jun 16 15:14:06 xxx kube-controller-manager[24465]: I0616 15:14:06.940818   24465 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"my-deploy-785fb59f49", UID:"33ade83a-ed43-11ec-9596-6c92bf8ad956", APIVersion:"extensions", ResourceVersion:"2127766901", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: my-deploy-785fb59f49-4d5vt
```

### What did you expect to happen?

pod should created as the same time  replicaset scale up almost

### How can we reproduce it (as minimally and precisely as possible)?

scale up replicaset, but it not happened all the time

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.9.11
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by FillZpp** [comment]
`Scaled up replica set my-deploy-785fb59f49 to 1` is the time Deployment created the new ReplicaSet.
`Created pod: my-deploy-785fb59f49-4d5vt` is the time ReplicaSet created the Pod.

So what happened in the 5 minutes, could you provide more logs?

**Comment by CharlesQQ** [comment]
> So what happened in the 5 minutes

do nothing

**Comment by pacoxu** [comment]
Probably, you can edit the kube-controller-manger log-level to 4 or 6 to see more evidence.
