### ISSUE TITLE
Malformed request bodies (received by kube-apiserver) shoule be logged in kube-apiserver debug logs to aid troubleshooting

### ISSUE THREAD

**Issue by abe-hpe** [kubernetes/kubernetes#110671]
### What would you like to be added?

Add request body to the properties included in EventString (in **k8s.io/apiserver/pkg/audit/format.go**) so that when the kube-apiserver audit log plugin calls HandlePluginError (which it does when a proper event message cannot be written to the audit log), the offending request body can be seen. This will aid in the troubleshooting of '400 Bad Request' responses from kube-apiserver.

### Why is this needed?

When an event's request body cannot be correctly marshaled to JSON (typically because a string value was not correctly quoted by whoever sent the request), HandlePluginError is called, and the event is excluded from the audit log. Currently, it's hard to see what actually caused the problem because the request body (that led to the auditing error, and also to a 400 Bad Request response being sent) isn't logged anywhere. For example:

```
E0616 21:02:21.958464       1 metrics.go:109] Error in audit plugin 'log' affecting 1 audit events: json: error calling MarshalJSON for type *runtime.Unknown: invalid character 'G' after object key:value pair
Impacted events:
2022-06-16T21:02:21.950119014Z AUDIT: id="07d7f02d-c83e-49b8-af0c-2edd71e1e254" stage="ResponseComplete" ip="16.143.22.193" method="patch" user="kubernetes-admin" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="hpecp" uri="/apis/hpecp.hpe.com/v1/namespaces/hpecp/hpecptenants/hpecp-tenant-5" response="400"
```
If the Impacted event shown above had also included the request body that contained the '_invalid character 'G' after object key:value pair_', it would really help to troubleshoot the original API request.

**Comment by liggitt** [comment]
this seems like a duplicate of https://github.com/kubernetes/kubernetes/issues/84571, which was discussed and decided against (context in https://github.com/kubernetes/kubernetes/issues/84571#issuecomment-1098390307)

logging malformed requests introduces audit volume problems and increases attack surface area
