### ISSUE TITLE
kubectl does not have a way to adjust its client-side rate limiting

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#110606]
### What happened?

kubectl does client-side rate limiting, but the limit is not adjustable.  This is inappropriately inflexible and commonly results in annoying error messages.  There is no inherently correct setting for client self-restraint; what is reasonable for one client depends on all the other clients and the servers.

A colleague preparing a demo using a kind cluster complained "this happens every time I get a CR", showing the following typescript.

```
kubectl get xsqldatabases.multicloud.aether.io       
I0615 16:05:15.481530 1384109 request.go:665] Waited for 1.179551114s due to client-side throttling, not priority and fairness, request: GET:https://127.0.0.1:33063/apis/cache.aws.crossplane.io/v1alpha1?timeout=32s
NAME           READY   COMPOSITION                                                AGE
sqldb1-nq2lq   True    xpostgresqldatabases.multicloud.incluster.aether.io        135m
sqldb2-9bm8x   True    xpostgresqlinstances.aws.platformref.crossplane.io         89m
sqldb3-lrpqg   False   xpostgresqlinstances.ibm-cloud.platformref.crossplane.io   10m
```

That info message can be suppressed by suppressing all info messages, but that is a blunt instrument and does not resolve the lack of configuration.

### What did you expect to happen?

I expected to have a way to control the client-side rate-limiting of kubectl.

### How can we reproduce it (as minimally and precisely as possible)?

Read the doc at https://kubernetes.io/docs/reference/kubectl/kubectl/ .

### Kubernetes version

<details>

This is current and has been this way for at least a while.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by bboreham** [comment]
I too have wished I could raise this rate-limit a bit from the default of 5/sec.
I see a few core commands have a `--kube-api-qps` flag, but not kubectl.

As it's something I would not want to change from moment to moment, I might prefer to have it in `~/.kube/config`.

While I'm here, I'll mention that the warning message is often about some kind of object I did not touch, e.g. `cache.aws.crossplane.io` as in your example. This serves to increase the frustration.

**Comment by JohnRusk** [comment]
See also https://github.com/kubernetes/kubernetes/issues/111880
