### ISSUE TITLE
kube-proxy  log: No  timestamp or log level

### ISSUE THREAD

**Issue by waymen** [kubernetes/kubernetes#110636]
### What happened?

I want to kube-proxy log output to file, so i added.:

 --skip-headers=true \
 --skip-log-headers=true \
  --logtostderr=false \
  --v=2 \
  --log-file=/var/log/kubernetes/kube-proxy.log 

# cat /var/log/kubernetes/kube-proxy.log      
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
FLAG: --add-dir-header="true"
FLAG: --alsologtostderr="false"
FLAG: --config-sync-period="15m0s"
FLAG: --conntrack-max-per-core="32768"
FLAG: --conntrack-min="131072"
FLAG: --conntrack-tcp-timeout-close-wai

no imestamp or log level

### What did you expect to happen?

 # cat /var/log/kubernetes/kube-proxy.log      
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
FLAG: --add-dir-header="true"
FLAG: --alsologtostderr="false"
FLAG: --config-sync-period="15m0s"
FLAG: --conntrack-max-per-core="32768"
FLAG: --conntrack-min="131072"
FLAG: --conntrack-tcp-timeout-close-wai

no imestamp or log level

### How can we reproduce it (as minimally and precisely as possible)?

# cat /var/log/kubernetes/kube-proxy.log      
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
FLAG: --add-dir-header="true"
FLAG: --alsologtostderr="false"
FLAG: --config-sync-period="15m0s"
FLAG: --conntrack-max-per-core="32768"
FLAG: --conntrack-min="131072"
FLAG: --conntrack-tcp-timeout-close-wai

no imestamp or log level

### Anything else we need to know?

# cat /var/log/kubernetes/kube-proxy.log      
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
FLAG: --add-dir-header="true"
FLAG: --alsologtostderr="false"
FLAG: --config-sync-period="15m0s"
FLAG: --conntrack-max-per-core="32768"
FLAG: --conntrack-min="131072"
FLAG: --conntrack-tcp-timeout-close-wai

no imestamp or log level

### Kubernetes version

1.16.9

### Cloud provider

no

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
As I know, klog will skip timestamp adding if `skip_header` is true.

https://github.com/kubernetes/klog/blob/49e17d5a7eaadb7bcac569ce6ecce8713d545387/klog.go#L661-L670

https://github.com/kubernetes/klog/blob/49e17d5a7eaadb7bcac569ce6ecce8713d545387/klog.go#L432

**Comment by thockin** [comment]
You asked for no headers.
