### ISSUE TITLE
echoserver:2.5 does not work on arm64 arch

### ISSUE THREAD

**Issue by jrsmroz** [kubernetes/kubernetes#110605]
### Problem statement
The [registry.k8s.io/e2e-test-images/echoserver:2.5](http://registry.k8s.io/e2e-test-images/echoserver:2.5) does not seem to work on arms64 linux VM. I got an error

```console
$ kubectl logs echo-597b9f4545-kb4lx
Generating self-signed cert
Generating a RSA private key
..............................+++++
......................................+++++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2022/06/13 19:11:29 [alert] 13#13: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2022/06/13 19:11:29 [error] 13#13: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')
```

The nginx version is rather old `NGINX_VERSION=1.15.12`. That's a version from 16 Apr 2019. Newest version of nginx is from 25 Jan 2022.

## Expected behaviour
echoserver running up to date version of nginx. 
echoserver working on arm64 arch.

**Comment by aojea** [comment]
I think the same functionality is implemented in the  agnhost image, we should migrate the test that are stillusing echoserver to agnhost

https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost#netexec

**Comment by BenTheElder** [comment]
From SIG Testing POV: should definitely move towards [agnhost](https://github.com/kubernetes/kubernetes/tree/master/test/images/agnhost) for e2e tests like this. agnhost is more maintainable and multi-arch, and we should be able to run e2e tests with pulling less images / have less images to maintain purely for test purposes.

**Comment by mikemorris** [comment]
As a potential shorter-term solution, Gateway API is using a version of `echoserver` that does support arm64 https://github.com/kubernetes-sigs/gateway-api/blob/a66a5d3c0704530b8cd8ceee54fd02d4bd52fba8/conformance/base/manifests.yaml#L96

**Comment by mikemorris** [comment]
@aojea I _believe_ it's at https://github.com/kubernetes-sigs/ingress-controller-conformance/tree/master/images/echoserver but somebody more familiar may want to confirm

**Comment by rikatz** [comment]
There is also
https://github.com/kubernetes/ingress-nginx/tree/main/images/echo

**Comment by aojea** [comment]
> @aojea I _believe_ it's at https://github.com/kubernetes-sigs/ingress-controller-conformance/tree/master/images/echoserver but somebody more familiar may want to confirm

@aledbf is this image linked above compatible with the nginx image?
Ricardo, I prefer if we move away of the nginx dependency
