### ISSUE TITLE
metrics to see which plugins affect to scheduler's decisions in Filter/Score phase

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#110643]
### What would you like to be added?

metrics to see more details related to scheduler's decisions in Filter phase

### Why is this needed?

In some cases (e.g. new feature is added in scheduler and want to see if it works or not), we may want to see which filter plugin affected Pod's scheduling results and it would be nice if we can observe that in metrics.

Ref: https://github.com/kubernetes/enhancements/pull/3338#discussion_r890411398

/cc @alculquicondor 
/sig scheduling

**Comment by alculquicondor** [comment]
I would also add an `extension_point` label that can be `Filter` or `Score`. 

We probably need some common implementation between this and #107556

**Comment by alculquicondor** [comment]
@sanposhiho do you have time to work on this in 1.26?

**Comment by sanposhiho** [comment]
Yes, I'm gonna take time to work on this (+ #107556) in the next release.
Let me try.
/assign

**Comment by alculquicondor** [comment]
We should probably extend this to Score as well

**Comment by sanposhiho** [comment]
👍 

/retitle metrics to see which plugins affect to scheduler's decisions in Filter/Score phase

**Comment by sanposhiho** [comment]
/remove-lifecycle stale

After supporting Skip in Filter and Score.

**Comment by sanposhiho** [comment]
memo: https://github.com/kubernetes/kubernetes/issues/114827 is the issue to support Skip in Score.

**Comment by kidddddddddddddddddddddd** [comment]
/cc
Will work on `score` part after #115082

**Comment by sanposhiho** [comment]
> Will work on score part after https://github.com/kubernetes/kubernetes/pull/115082

@AxeZhan It's time!

/assign @AxeZhan
