### ISSUE TITLE
Snapshot Controller updated to 6.0.1 without correct RBAC required

### ISSUE THREAD

**Issue by leiyiz** [kubernetes/kubernetes#110645]
### Which jobs are failing?

https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate

### Which tests are failing?

Snapshot related tests

### Since when has it been failing?

6-17 2022

### Testgrid link

https://k8s-testgrid.appspot.com/provider-gcp-compute-persistent-disk-csi-driver#Kubernetes%20Master%20Driver%20Latest%20Release%20Candidate

### Reason for failure (if possible)

The [Snapshotter controller rbac ](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/volumesnapshots/volume-snapshot-controller/rbac-volume-snapshot-controller.yaml) needs to be updated with the following rbac rules mentioned in https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/pull/1014 to correctly function.

### Relevant SIG(s)

/sig storage

**Comment by mattcary** [comment]
/sig-storage
/triage accepted

Someone on my team will look at this in a week or so after we finish our current release, if no-one else gets to it first.

**Comment by akankshakumari393** [comment]
@mattcary I would want to work on it. Let me know if this issue is still valid.

**Comment by mattcary** [comment]
I think @humblec is looking into it (see #110826)

**Comment by mattcary** [comment]
I think this was fixed in https://github.com/kubernetes/kubernetes/issues/112694
