### ISSUE TITLE
kubeadm join fails on Windows when crictl is in the PATH

### ISSUE THREAD

**Issue by jsturtevant** [kubernetes/kubernetes#110626]
### What happened?

Running `kubeadm join` on Windows when crictl.exe is in the `PATH` results in error:

```
[ERROR CRI]: container runtime is not running: output: time="2022-06-15T15:46:27-07:00" level=fatal msg="getting status of runtime: invalid character 'e' in string escape code"
```

### What did you expect to happen?

The container runtime to be recognized as running because it is.

### How can we reproduce it (as minimally and precisely as possible)?

Install crictl.exe to somewhere on your PATH and then run:

```
 ./kubeadm.exe join 10.240.0.10:6443 --token <your token> --discovery-token-ca-cert-hash sha256:<your hash> --cri-socket "npipe:////./pipe/containerd-containerd" 
```

### Anything else we need to know?

If crictl is not on the path or not installed at all then `kubeadm join` succeeds but prints warning:

```
 4768 checks.go:1021] [preflight] WARNING: Couldn\'t create the interface used for talking to the container runtime: crictl is required by the container runtime: exec: "crictl": executable file not found in %PATH%\n
```

### Kubernetes version

<details>

```console
$ kubectl version
# 1.23.3
```

</details>

### Cloud provider

<details>
N/A, can be produced on any install
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here

WS 2019
WS 2022
```

</details>

### Install tools

<details>
kubadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Windows containerd 1.6.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
reproduces with flannel, calico
</details>

**Comment by neolit123** [comment]
> [ERROR CRI]: container runtime is not running: output: time="2022-06-15T15:46:27-07:00" level=fatal msg="getting status of runtime: invalid character 'e' in string escape code"

is there more information on what 'e' means here? i don't think this error is coming from kubeadm directly.

to look up the crictl executable path kubeadm uses this:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/runtime/runtime.go#L58

under the hood it's just a `os/exec.LookupPath()` and it should work cross-os:
https://github.com/kubernetes/kubernetes/blob/4e17f88b7e394b74dbfddf7e930ad3a4065307cf/vendor/k8s.io/utils/exec/exec.go#L111

https://pkg.go.dev/os/exec#LookPath

**Comment by jsturtevant** [comment]
`crictl -r "npipe:////./pipe/containerd-containerd"  info` fails too, so it seems that it is related to crictl maybe in 1.23?  I tried this 1.24 and it worked.  

@vrapolinario could you give your exact commands you encountered?

**Comment by vrapolinario** [comment]
I used this to download crictl:

```
curl.exe -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.23.0/crictl-v1.23.0-windows-amd64.tar.gz
tar xvf crictl-v1.23.0-windows-amd64.tar.gz
mv crictl.exe "C:\Program Files\containerd"
```

Then this happens:
PS C:\Program Files\containerd> .\crictl.exe -r "npipe:////./pipe/containerd-containerd" info
time="2022-06-16T15:55:20-07:00" level=fatal msg="getting status of runtime: invalid character 'e' in string escape code"

**Comment by g3rzi** [comment]
I fixed it by running:
```
Invoke-WebRequest https://projectcalico.docs.tigera.io/scripts/Install-Containerd.ps1 -OutFile c:\Install-Containerd.ps1
c:\Install-Containerd.ps1 -ContainerDVersion 1.6.2 -CNIConfigPath "c:/etc/cni/net.d" -CNIBinPath "c:/opt/cni/bin"  
```

Thanks to [Calico docs](https://projectcalico.docs.tigera.io/getting-started/windows-calico/quickstart).
