### ISSUE TITLE
Flaky TestFeatureExternalTrafficPolicy

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#110780]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

TestFeatureExternalTrafficPolicy

### Since when has it been flaking?

June 24th

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestFeatureExternalTrafficPolicy&job=pull-kubernetes-unit

### Reason for failure (if possible)

```
=== FAIL: pkg/registry/core/service/storage TestFeatureExternalTrafficPolicy/LoadBalancer_policy:Local_hcnp:specified_policy:Cluster_hcnp:none (0.00s)
    storage_test.go:749: unexpected error creating service: Internal error occurred: failed to allocate requested HealthCheck NodePort 30000: provided port is already allocated
    --- FAIL: TestFeatureExternalTrafficPolicy/LoadBalancer_policy:Local_hcnp:specified_policy:Cluster_hcnp:none (0.00s)
```

### Relevant SIG(s)

/sig storage

**Comment by harry1064** [comment]
Hi @alculquicondor 

I was debugging this flaky test case. Locally all the test cases pass.

So, while debugging I come to realize that `PortAllocator`'s `portRange`
![Screenshot 2022-06-27 at 8 45 03 PM](https://user-images.githubusercontent.com/6297435/175944758-fe2d5334-5a99-411c-8f80-c82abee95d5a.png)

Is it possible, that on line below during nodePort allocation we get `offset` and hence 30000 get allocated and then during allocation of `HealthCheckNodePort` which is also provided as 30000 cause the error as port is already allocated?
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/portallocator/allocator.go#L135 

If that is so, this is the reason I can think of as the cause of flaky test case. What do you think?

**Comment by aojea** [comment]
The nodeport allocation happens here and handls the duplicate allocation 
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/storage/alloc.go#L451-L484

checking at the job failure I can see that there are connectivity errors with the backend

> k8s.io/kubernetes/pkg/registry/core/service/storage: TestFeatureExternalTrafficPolicy expand_less | 2s
> -- | --
> {Failed  === RUN   TestFeatureExternalTrafficPolicy W0624 18:37:23.330674   65642 logging.go:59] [core] [Channel #1991 SubChannel #1993] grpc: addrConn.createTransport failed to connect to {   "Addr": "localhost:43779",   "ServerName": "localhost",   "Attributes": null,   "BalancerAttributes": null,   "Type": 0,   "Metadata": null }. Err: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:43779: connect: connection refused" W0624 18:37:23.439328   65642 logging.go:59] [core] [Channel #2467 SubChannel #2469] grpc: addrConn.createTransport failed to connect to {   "Addr": "localhost:44007",
> 

the test needs an etcd storage https://github.com/kubernetes/kubernetes/blob/bdbf2c6ef43f18405613f3ad379afbec761b69d3/pkg/registry/core/service/storage/storage_test.go#L52-L57

and it seems that it failed. If the backend fails, the test is going to fail.

Since there was only one occurrence in the last 15 days, I´m going to close it because it seems more an environmental problem on the CI, but we can reopen if there are new occurrences

/close

**Comment by harry1064** [comment]
Hi @aojea 

I am not sure but when I forced `start` to be 0 as `rss.rand.Intn(subrangeMax)` can return [0, subrangeMax), I can reproduce the same error When we are just creating a service as NodePort allocation happens before HealthCheckPort allocation in the `kubernetes/pkg/registry/core/service/storage/alloc.go`

https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/allocator/bitmap.go#L244

https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/storage/alloc.go#L451-L484

**Comment by aojea** [comment]
> Hi @aojea
> 
> I am not sure but when I forced `start` to be 0 as `rss.rand.Intn(subrangeMax)` can return between [0, subrangeMax), I can reproduce the same error When we are just creating a service as NodePort allocation happens before HealthCheckPort allocation in the `kubernetes/pkg/registry/core/service/storage/alloc.go`
> 
> 

can you explain in more details what are the steps you are doing for reproducing the issue=

**Comment by harry1064** [comment]
hi @aojea 

After following line
https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/pkg/registry/core/service/allocator/bitmap.go#L244

I add another line 
```
start = 0
```
to create scenario, in which the `0` offset will be returned by this function and hence we mark the first port number in our portRange as allocated i.e 30000 in our case.

What will happened now is if HealthCheckNodePort specified in svc.spec is also `30000` as shown in the screenshot below I ran one single test case, we will get following error while creating the service?
![Screenshot 2022-06-28 at 2 17 53 AM](https://user-images.githubusercontent.com/6297435/176008971-3e8fd95d-9691-42d2-a15f-26dc57e78b21.png)

```
unexpected error creating service: Internal error occurred: failed to allocate requested HealthCheck NodePort 30000: provided port is already allocated
```

So, What I think is if HealthCheckNodePort specified in spec somehow matches with randomly allocated node port to service, we will get this error.

**Comment by aojea** [comment]
> yeah, it seems right, the logic that allocates thenodeport doesn't check if the healthcheck nodeports were chosen
> 
> https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/storage/alloc.go#L487-L537
> 
> /reopen

@thockin I vaguely remember we discussed this, but I can't find the conversation.

Do we need to consider the specified healthcheck nodeports on the `initNodePorts` function? it seems we are not doing it now

**Comment by harry1064** [comment]
Hi @aojea 



> > yeah, it seems right, the logic that allocates thenodeport doesn't check if the healthcheck nodeports were chosen
> > https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/storage/alloc.go#L487-L537
> > 
> > /reopen
> 
> @thockin I vaguely remember we discussed this, but I can't find the conversation.
> 
> Do we need to consider the specified healthcheck nodeports on the `initNodePorts` function? it seems we are not doing it now

Should we change the order of these two if statements? (i.e allocating HealthCheckNodePort first if specified )
https://github.com/kubernetes/kubernetes/blob/035f22d7810a8970e42d60f276f71a519b174a44/pkg/registry/core/service/storage/alloc.go#L468-L482

**Comment by aojea** [comment]
> Should we change the order of these two if statements? (i.e allocating HealthCheckNodePort first if specified )

you'll have the same problem if instead of specifying the HealthCheckNodePort you specify the NodePort

**Comment by harry1064** [comment]
> > Should we change the order of these two if statements? (i.e allocating HealthCheckNodePort first if specified )
> 
> you'll have the same problem if instead of specifying the HealthCheckNodePort you specify the NodePort

Yes, you are right. We need to consider checking for HealthCheckNodePort in `initNodePorts ` function. Problem I see, we need to somehow pre notify `nodePortOp` to not allocate `HealthCheckNodePort` specified because incase of `AllocateNext` method call on `nodePortOp` will already mark the nodePort returned as allocated.

**Comment by aojea** [comment]
basically you need to know which ports were specified before start allocating to avoid conflicts, it is a complex logic due to all the permutations

**Comment by harry1064** [comment]
Okay. Let me think about the approach and I will share here before starting actual implementation.

**Comment by harry1064** [comment]
hi @aojea 

While doing some testing, I found that we are calling the `e.BeginCreate` before calling `rest.BeforeCreate`. If any validation error is there it is thrown after we already allocated ports and clusterIps. Although, we have defer function which will revert the transaction if any error, but Shouldn't we call `rest.BeforeCreate` before `e.BeginCreate`? 
Reason being, our `initNodePorts ` does not have any check for duplicated ports value.
https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L392-L405

**Comment by aojea** [comment]
the key is in the `initNodePorts` , it doesn't consider the HealthCheckNodePort, you can see that goes through the spec and loops over all the nodePorts specified and allocate new ones.
I remember there were several corner cases here due to the random allocation and the possibility of mutate or specifiy NodePorts ... and I vaguely remember that we decided to let it fail for conflict resolution , let's wait for Tim, he has better memory than me :smile:

**Comment by harry1064** [comment]
Yes sure. Let's wait for Tim. I think you mentioned him earlier in this issue as well. Do we need to mention him again?

**Comment by dcbw** [comment]
@thockin any thoughts here?

**Comment by aojea** [comment]
no failures 🤔 
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestFeatureExternalTrafficPolicy&job=pull-kubernetes-unit
