### ISSUE TITLE
apiserver: Make the default scheduler name configurable

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#110795]
### What would you like to be added?

From https://kubernetes.io/docs/reference/scheduling/config/#multiple-profiles:
> If a Pod doesn't specify a scheduler name, kube-apiserver will set it to `default-scheduler`. Therefore, a profile with this scheduler name should exist to get those pods scheduled.

https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/pkg/apis/core/v1/defaults.go#L205-L207

Currently when you configure multiple scheduling profiles and you cannot change cluster-wide the default scheduler name.

You have to implement a custom mutating webhook that sets the Pod `.spec.schedulerName` to the wanted scheduler.

I would expect the default scheduler name that is used by the kube-apiserver (currently hard-coded to `default-scheduler`) to be configurable in the apiserver via command line flag (for example `--default-scheduler-name`).

### Why is this needed?

To allow the default scheduler to be changed easily without the need to write, deploy and maintain a custom mutating webhook.

**Comment by kerthcet** [comment]
What can we benefit from the idea, better naming?

**Comment by ialidzhikov** [comment]
> What can we benefit from the idea, better naming?

Can you elaborate more on this question? In https://github.com/kubernetes/kubernetes/issues/110795#issue-1284991472 I already described what is the use case:
> To allow the default scheduler to be changed easily without the need to write, deploy and maintain a custom mutating webhook.

I see that the corresponding handling is in the Pod defaults:
https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/pkg/apis/core/v1/defaults.go#L205-L207

So the question is whether this defaulting is used/invoked only by kube-apiserver? Because if it is not, then this feature request is not doable.

**Comment by kerthcet** [comment]
/remove-lifecycle rotten

> whether this defaulting is used/invoked only by kube-apiserver?

I think the answer is yes, so maybe we can add `--default-scheduler-name` to both apiserver and scheduler to make it configurable, if not, drop to `default-scheduler`.
/assign

Do you think this is reasonable? @ahg-g @alculquicondor @Huang-Wei

**Comment by alculquicondor** [comment]
Similar topics were discussed forever ago #97072 #93067.

Not sure if there is precedent to configuring the defaulting logic instead, like this issue is proposing.

@liggitt thoughts?

**Comment by alculquicondor** [comment]
It doesn't look like any circumstance has changed since the last time this feature was proposed. So...
/close
