### ISSUE TITLE
Topology Aware Hint does not consider node taints

### ISSUE THREAD

**Issue by unmarshall** [kubernetes/kubernetes#110714]
### What happened?

Consider a K8S cluster which is spread across several zones. In each zone there can be many `node-groups` which is the unit for `Cluster-Autoscaler`. Typically you would create different node groups either with different node labels or taints which will help the Cluster Autoscaler to scale a specific node group (optionally in a specific zone) in case there are unscheduled pods or over-utilised nodes.
![multi-zone-node-groups](https://user-images.githubusercontent.com/1223360/174977608-69b1a19e-02fa-431f-84bc-9be086016e7d.png)

In the above setup for nodes in each node group across zones taints are added so that workloads which have tolerations to the taint can be scheduled across zones.

Also consider the following `Allocatable CPU` for each node across node groups/zones:
![zonal-cpu-ratios](https://user-images.githubusercontent.com/1223360/174984707-b3371e3e-e7c1-4a40-9fd0-ec5e1bbfb725.png)

Now consider a service whose pods are only deployed on nodes where the `taint = T1`. This will target node groups: `NodeGroup-A1T1`, `NodeGroup-B1T1` and `NodeGroup-C1T1`. If you look at the cpu ratio per zone then as per the current implementation of `endpointslice controller` the hints will be removed. 
**Why is this the case?**
It is because: cpu-ratios of Zone-A is almost twice as large as cpu-ratio of Zone-B.
In [topologycache.go](https://github.com/kubernetes/kubernetes/blob/23144130a815117194afbf3f703024ed76d5dac1/pkg/controller/endpointslice/topologycache/topologycache.go#L256-L258) method `getAllocations` will return `nil` which will cause any hints to be removed.

Cluster-Autoscaler can scale each node group at anytime resulting in change of cpu-ratios in a zone. This further impacts the determinism with which topology aware hints will be effective.

### What did you expect to happen?

If you consider only the nodes which are having a specific taint (`T1`) then you will get the following total allocatable CPU:
Zone-A: { `Total CPU`: 15840m` }
Zone-B: { `Total CPU`: 15840m` }
Zone-C: { `Total CPU`: 15840m` }

This is an equitable distribution and therefore should result in addition of hints. However, in the current implementation taints are not considered to filter the nodes that should be considered for a specific service endpoints. Considering that there can be several node groups per zone which can have different taints it would be prudent if taints/labels should be considered for filtering candidate nodes.

### How can we reproduce it (as minimally and precisely as possible)?

Have the above setup and just deploy a simple nginx pod (replicas = 3) + service across 3 zones as shown above. This will result in a total number of endpoints = 3. No topology aware hints will be added.

### Anything else we need to know?

Write now i have tested this with k8s version 1.22 where this is an alpha feature. However i have also verified that the code in beta has no changes w.r.t computing the cpu rations for each zone.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:43:55Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
Tested on AWS EC2 but this will not change across providers. On top of EC2 instances https://github.com/gardener/gardener is setup.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
I don't know if this can scale well, IIUIC this means we should have a cpuRatioByZoneAndService, 

> cpuRatiosByZone    map[string]float64

it seems that it also requires to pass the taint information to the Service :thinking:

**Comment by unmarshall** [comment]
An additional point:
It also currently also considers nodes which are not ready or not healthy where pods cannot be scheduled but the allocated cpus will be added.

**Comment by aojea** [comment]
> It also currently also considers nodes which are not ready or not healthy where pods cannot be scheduled but the allocated cpus will be added.

https://github.com/kubernetes/kubernetes/blob/18b5efceda2643b7175fbf712e8978d382077f9b/pkg/controller/endpointslice/topologycache/topologycache.go#L177-L185

**Comment by thockin** [comment]
IIRC, The consideration of CPU is to figure out whether clients in a zone could swamp servers in that zone.  In that regard, taints don't matter because it doesn't tell me anything about the set of potential clients.

As @aojea says - we would have to tell Services about where clients COULD come from, which I don't know if we want to do that.

That doesn't mean there isn't room for refinement of the heuristics here, of course.  @robscott

**Comment by robscott** [comment]
+1 to the comments from @thockin and @aojea. I'm very interested in better heuristics here, but not sure how to improve this without creating other problems. Open to ideas from anyone here.

I'm not sure it's accurate to consider this a bug though, more of a known and documented limitation of this approach. Currently the [relevant docs](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/#constraints) say the following:

>The EndpointSlice controller does not take into account [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) when deploying calculating the proportions of each zone. If the Pods backing a Service are limited to a subset of Nodes in the cluster, this will not be taken into account.

**Comment by unmarshall** [comment]
> taints don't matter because it doesn't tell me anything about the set of potential clients.

That is true in general. In our case we have a multi-zonal control plane setup where for each zone there is a `Kube API server` pod running and each zone has one `etcd` member running. For a region having 3 zones this would mean a 3-member etcd cluster having one member in each zone.
The wish therefore is to influence routing of traffic originating from `Kube API Server` to preferably reach the `etcd` member running in the same zone. This results in cost and latency reduction due to crossing zones. As you can imagine in this case the client is well-known and its replicas per zone is also known due to affinity rules.

>I'm not sure it's accurate to consider this a bug though, more of a known and documented limitation of this approach.

Yes, agreed that this is a documented limitation. So i will change the label of this issue.

**Comment by thockin** [comment]
I don't usually see the apiserver's etcd represented as a kube service.  Is that really what you are doing?

We have some lower-bound for hints because it seems easy to get catastrophically wrong when each enpoint represents a double-digit percentage of capacity.

@robscott I think the use-case of intentionally-balanced endpoints is important and we should think about how the heuristic could do better here.  It's challenging because it's not semantic (if 1/3 is down, it's OK to cross zones rather than fail) but it is a strong preference.

**Comment by thockin** [comment]
I'm grumpy about adding APIs for this, so that's my least-favorite choice, but I am open to it if we really REALLY can't do better.

**Comment by aojea** [comment]
current heuristic is based on cpu per zone, that depends on the nodes and is not parameterizable by users 

```
		nodeCPU := node.Status.Allocatable.Cpu()
		zone, ok := node.Labels[v1.LabelTopologyZone]
```

if we provide a "weight" annotation on the nodes, users can define those weights, and implement their own heuristics ... 

a dirty hack to illustrate what I'm trying to say is

``` 
cpuOverride, ok := node.Labels[v1.LabelTopologyCPUOverride]
nodeCPU = cpuOverride
```

**Comment by robscott** [comment]
>I'm grumpy about adding APIs for this, so that's my least-favorite choice, but I am open to it if we really REALLY can't do better.

So the original "Auto" mode for topology assumes that the user has not or can not ensure that pods are distributed evenly across zones. I think there is a subset of users that want to be able to say "keep my traffic in the same zone, I'll make sure my workloads are evenly distributed". Fundamentally I think this requires a separate deployment + HPA per zone today. We could either make that a prerequisite of the "Auto" approach (probably a breaking change), or we could make a separate option that relies on this. Similar to the problems/limitations of the current approach, this does not work well when there are a small number of pods, say 4 pods distributed over 3 zones, but this kind of user configuration would be more predictable when it comes to autoscaling.

With the current approach, it's not obvious from an autoscaling perspective which Pods are serving traffic for which zones. So even if you had per-zone HPAs and Deployments set up, there's still a chance that one of your pods from one zone would get allocated to another zone, and autoscaling logic would be entirely messed up from that point on.

Obviously in the long term we want all of this to be easier, so if we could work with sig-autoscaling and sig-scheduling to scale pods up in zones that are currently receiving the most traffic/utilization, we could eventually remove the requirement for a single deployment/HPA per zone.

>if we provide a "weight" annotation on the nodes, users can define those weights, and implement their own heuristics ...

My concerns with this idea would be that I think many users would want different weights per Service. In many k8s environments, nodes are also upgraded/replaced pretty frequently, so keeping that label up to date could be challenging.

**Comment by unmarshall** [comment]
>So the original "Auto" mode for topology assumes that the user has not or can not ensure that pods are distributed evenly across zones. I think there is a subset of users that want to be able to say "keep my traffic in the same zone, I'll make sure my workloads are evenly distributed". Fundamentally I think this requires a separate deployment + HPA per zone today.

In our setup we leverage VPA recommendations to scale up etcd pods if there is a larger load originating from a specific zone. Having a multi-node setup along with PDB ensures that we do not lose quorum. In a nutshell auto-adjusting (adding/removing) hints based on changing CPU ratios would serve a few use cases but will also not be ideal (in our case very non-deterministic) for other cases. Therefore `auto` could fallback to the current approach of dynamically adding/removing hints based on changing CPU ratios across zones. However as you have suggested a static option could also be provided giving more control to the consumer as each setup could be very different with different set of scaling capabilities.

**Comment by sftim** [comment]
@unmarshall the use case you have doesn't seem to overlap closely with the use cases for [Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/) to Services.

You might be better served by not setting `service.kubernetes.io/topology-aware-hints` to `auto` and then using a custom controller to achieve the outcome you want.

Kubefolks, is that supported?

**Comment by unmarshall** [comment]
@sftim The intention of this feature has quite an overlap with what we look for, however the issue is with the implementation choice (algorithm) used to eventually distribute traffic. Therefore what we ask here is to provide a cheaper/simpler option where CPU ratios are bypassed.

**Comment by aojea** [comment]
> @unmarshall the use case you have doesn't seem to overlap closely with the use cases for [Topology Aware Hints](https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/) to Services.

I agree with Tim here, this seems a very specific use case, and I don't know if is really optimum, since despite you connect to the closes etcd, all the etcd nodes has to sync its information, so every write has to be propagated to the whole cluster, the more etcd nodes the worse write performance you have
https://etcd.io/docs/v3.5/faq/#what-is-maximum-cluster-size

**Comment by unmarshall** [comment]
@aojea I gave an example of etcd because that is the current case. However, this is a very generic case for any service which is deployed across zones. Once you have several node groups and cluster autoscaler in the mix then the CPU ratios can dynamically change. 

>all the etcd nodes has to sync its information, so every write has to be propagated to the whole cluster, the more etcd nodes the worse write performance you have

Yes this very well known. We currently provide etcd in non-HA and HA modes and we have fixed the size to a max of 3 members as that is usually an optimal size for most of the usage patterns.

**Comment by aojea** [comment]
ic, I've got lost on the details , sorry

**Comment by unmarshall** [comment]
CA scales nodes in a node group based on the [expander](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders) that is configured. So which node group it chooses to scale depends on the strategy for bin-packing which is partially achieved via expanders. This eventually has a potential for creating different in CPU ratios which are greater than the current threshold used to determine if hints needs to be removed.

**Comment by thockin** [comment]
If I can summarize, it sounds like:

* Sometimes the CPU-balance heuristic is wrong.  For example, if we know that the whole zonal CPU pool does not model the set of clients which will access a service, then we may erroneously disable hints.

* Hints do not work at low-endpoint counts.

* Hints are set on endpoints by the endpointslice controller, but not all endpoints come from there (some are manual).

We have had requests for "always use same node unless not available" and "always use same zone unless not available".  I feel like "same node" could maybe be automatic, but even that feels like it needs a richer heuristic (e.g. a single heavy client could over-power a single backend).

So let's assume that we're willing to add API to let a user express these desires.  Is it the same as `internalTrafficPolicy`?  Is it a different expression?

See https://github.com/kubernetes/enhancements/pull/3293 for some discussion (KEP https://github.com/kubernetes/enhancements/issues/3015)

**Comment by danwinship** [comment]
> I feel like "same node" could maybe be automatic, but even that feels like it needs a richer heuristic (e.g. a single heavy client could over-power a single backend).

One failure mode I came up with in https://github.com/kubernetes/enhancements/pull/3293 is when a service has more endpoints than there are nodes. If every node prefers its own endpoints, then scaling the service from `num_endpoints == num_nodes` to `num_endpoints == 1.5 * num_nodes` will improve performance on half of the nodes, but not on the other half...

For the node-level-topology case, I suggested we might only automatically do it in the case where the service's endpoints are deployed by a DaemonSet. I'm not sure if there's any easy way to recognize in a Deployment that it is designed to distribute endpoints evenly across zones, but maybe some way of making that more explicit could help with figuring out zone-level topology more automatically.

**Comment by ialidzhikov** [comment]
@thockin, @robscott, @aojea WDYT about adding support for "static"/"deterministic" hints?

"Static" hints:
- won't rely on the CPU-balance heuristic that simply does not work when the CPU-balance does not model the set of clients - see https://github.com/kubernetes/kubernetes/issues/110714#issuecomment-1178163573
- will add the Endpoint's zone field value as hint. We also need part of the safeguards from https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ - for example in case of `insufficient number of endpoints` hints won't be added
- it will be the cluster operator's responsibility to spread the Pods/Endpoints across zones with [Pod topology spread constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/) or [Pod affinity and anti-affinity](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
- it will be the cluster operator's responsibility to add autoscaling (`VerticalPodAutoscaler`) as a safeguard mechanism in case a Pod/Endpoint is overloaded
- as end result we should have deterministic hints that minimize the cross-zonal traffic

Does this also make sense to you?

**Comment by robscott** [comment]
Hey @ialidzhikov, I think you're describing something similar to https://github.com/kubernetes/enhancements/pull/3642. If that's the case, I'm convinced we need to offer some way to configure this, I'm less sure of the right way to expose that. I've got more detailed comments on that PR.

**Comment by ialidzhikov** [comment]
Yes, I noticed the KEP update PR from the sig-network Slack channel. In the last days I was trying to implement support for `service.kubernetes.io/topology-aware-hints=always` - ref https://github.com/ialidzhikov/kubernetes/tree/enh/topology-aware-hints (the last commit in this branch). 

> This is a relatively trivial concept to implement but I'm not sure "Hints" is the right home for it.

To be honest with myself, for me it is not that trivial to implement this. I still have some flaws in the change and need to complete the testing to make sure it works in the basic scenario. And finally I guess I will be never 100% sure that the change is "rock solid" - does not regress anything else, works as expected in all cases, etc. I am just trying to explain that it is not that trivial for an external contributor to contribute such change.

I agree with the points raised in https://github.com/kubernetes/enhancements/pull/3642#issuecomment-1301540746. But all of this makes me ask "why then `ServiceTopology` was deprecated in favor of `TopologyAwareHints` which is (as raised multiple times in the sig-network channel) less flexible; covers only a small subset of the feature offering of ServiceTopology?". `ServiceTopology` was offering an API that was allowing users to configure things like:
> - Only to endpoints on the same node, failing if no endpoint exists on the node: `["kubernetes.io/hostname"]`.
> - Preferentially to endpoints on the same node, falling back to endpoints in the same zone, followed by the same region, and failing otherwise: `["kubernetes.io/hostname", "topology.kubernetes.io/zone", "topology.kubernetes.io/region"]`. This may be useful, for example, in cases where data locality is critical.
> - Preferentially to the same zone, but fallback on any available endpoint if none are available within this zone: `["topology.kubernetes.io/zone", "*"]`.

With ServiceTopology, https://github.com/kubernetes/enhancements/pull/3293 would be written as `["kubernetes.io/hostname", "*"]` - prefer endpoints on the same Node, fallback to any available endpoint.
Our use case "prefer endpoints from the same zone, fallback to any endpoint" is already covered in the last bullet from above - `["topology.kubernetes.io/zone", "*"]`.

Can you elaborate more on what were the issues with ServiceTopology?

**Comment by yubingjiaocn** [comment]
For ratio calculation, can we include only the nodes which pods located in? Most of the Kubernetes cluster runs multiple workloads. In current implementation, CPU is counted in zonal level, which other workloads may interference the calculation. 

Consider a extreme case. I run a compute-intensive workload on a single AZ with a lot of dedicated instances. Meanwhile I run another application on 3 AZs. Even I use Topology Spread Constraints to balance the pods count on 3 AZs, I can't enable topology aware hints in any situation, which will cause "overload". But if we only consider nodes with application pods, it's balanced and hints can be set.  

Also, is there a way to change the "overload" threshold? A hard-coded 20%/30% may not suits all situation. Also, I agree with "static" or a "always-on" option for creating hints. Cluster administrators can choose to accept the risk, and earn reduced cross-AZ cost (which is very high for some cloud providers).
