### ISSUE TITLE
Display node name along with pods on execution of `kubectl top pod` & easy readability for CPU and Mem size

### ISSUE THREAD

**Issue by shan100github** [kubernetes/kubernetes#110722]
### What would you like to be added?

Display node name along with pod name on the execution of "kubectl top pod <additional parameter>"
1) Currently while "kubectl top pod" is executed, it displays only pod name along with CPU & MEM usage, but it will be good and easy to monitor while we have the corresponding node name. 
```
>>kubectl top pod -n kubeflow 
NAME                                                         CPU(cores)   MEMORY(bytes)
admission-webhook-deployment-7df7558c67-n7k28                1m           16Mi
jupyter-web-app-deployment-5886974887-sbzbp                  1m           174Mi
katib-controller-58ddb4b856-77rp6                            1m           34Mi
katib-db-manager-d77c6757f-9x9hq                             1m           5Mi
katib-mysql-7894994f88-2sq4c                                 15m          388Mi
kfserving-models-web-app-7884f597cf-q9w9t                    3m           228Mi
metadata-writer-78fc7d5bb8-jn667                             7m           155Mi
minio-5b65df66c9-lb8n2                                       5m           24973Mi
```

2)  Display Memory and CPU in a readable format in GB/Gi. through additional input param support from "kubectl top" command.

### Why is this needed?

1) Displaying node name along with pod usage for easy monitoring.
2) Provide support for displaying GB/Gi for more easy readable output for users.

**Comment by shan100github** [comment]
@raptorsun , 
1) Adding option to display node name on execution of `kubectl top pod` as suggested by you seems to be good and easy for investigation
```
>>kubectl top pod -n kubeflow 
NAME                                                         CPU(cores)   MEMORY(bytes)  Node
admission-webhook-deployment-7df7558c67-n7k28                1m           16Mi           worker-1
jupyter-web-app-deployment-5886974887-sbzbp                  1m           174Mi          worker-1
katib-controller-58ddb4b856-77rp6                            1m           34Mi           worker-2
katib-db-manager-d77c6757f-9x9hq                             1m           5Mi            worker-3
```

2) Already @yangjunmyfm192085 made a PR https://github.com/kubernetes/kubernetes/pull/110801 and that seems to be better readability and output is something similar to `ls -lh` in linux.

**Comment by raptorsun** [comment]
Hello @shan100github , 
It is excellent that PR#110801 already provides the function to show proper units according to the order of magnitude.
Now we need to make 2 PRs, one to show nodes and the other to add commas when displaying the memory in the default format.
I'm going to start with the comma one as it is easier. :)

**Comment by serathius** [comment]
I don't get the argument, kubectl top is just a simple CLI to get resources, it's not something that is meant to give you real insights. Without metric history and correlation with events happening in cluster/node you cannot make any good conclusions, like example of noisy neighbor. 

Please consider looking into monitoring solutions like Prometheus and Grafana. Community has already build ready Graphs to get insights you are looking for.

**Comment by dgrisonnet** [comment]
I think it would make sense to add a new node column, but I wouldn't add it by default. To match the behavior of existing commands such as `kubectl get pods`, I would be inclined to hide it by default and make it visible via a `-o wide` option.

**Comment by shan100github** [comment]
It would be good if we have an option to check node along with the output of `kubectl top pod` from the command line rather than going through another service like Prometheus/Grafana.

**Comment by dgrisonnet** [comment]
I agree with Serathius comment in https://github.com/kubernetes/kubernetes/issues/110722#issuecomment-1192341770.

Closing since this is going stale and we've seem to agree that `kubectl top` should remain pretty simple and if additional information are needed, monitoring tools would be better suited.

/close
