### ISSUE TITLE
Creating custom certs for kubeadm resolving in a "dead" cluster

### ISSUE THREAD

**Issue by tuatara73** [kubernetes/kubernetes#110725]
### What happened?

I created a manual script to create all the certs located in `/etc/kubernetes/pki` and `/etc/kubernetes/pki/etcd` on a running cluster on centos 7, as long as modifieng the conf files located in `/etc/kubernetes` {admin.conf, scheduler.conf, controller-manager.conf} and provided new certs for them as well of course without touching kubelet.conf.
**I used the ca.crt that was already in /etc/kubernetes/pki** and made sure that every cert is created by the ca that is relevant to it.
For example, front-proxy-client.crt is created by front-proxy-ca.crt with this commands:
```
openssl genrsa -out front-proxy-client.key 2048 
openssl req -new -key front-proxy-client.key -out front-proxy-client.csr -config front-proxy-client.conf 
openssl x509 -req -in $CURRENT_DIR/front-proxy-client.csr -CA /etc/kubernetes/pki/front-proxy-ca.crt -CAkey /etc/kubernetes/pki/front-proxy-ca.key -CAcreateserial -out front-proxy-client.crt -days 3500 -extensions v3_ext -extfile front-proxy-client.conf
```
Taken from this documentation:
https://kubernetes.io/docs/tasks/administer-cluster/certificates/#openssl

After running the script and restarting kubelet (moving /etc/kubernetes/manifests folder to another location, waiting 20 seconds and moving it back to its original location), then the cluster didn't came back and 2 things occured,

1.  When I run kubectl I get this error 
`The connection to the server shiran-va:6443 was refused - did you specify the right host or port?`
3. kubelet got this error 
````
{Name:"<HOSTNAME>.16faefd41a98a537", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"<HOSTNAME>", UID:"<HOSTNAME>", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node <HOSTNAME> status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"<HOSTNAME>"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc0a4df3cd01de737, ext:16891526681, loc:(*time.Location)(0x74fdb40)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc0a4df3cddf6963e, ext:17123831058, loc:(*time.Location)(0x74fdb40)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'Patch "https://shiran-va:6443/api/v1/namespaces/default/events/<HOSTNAME>.16faefd41a98a537": dial tcp 127.0.0.1:6443: connect: connection refused'(may retry after sleeping)
Jun 22 08:26:47 <HOSTNAME> kubelet: E0622 08:26:47.059407    1275 kubelet.go:2291] "Error getting node" err="node \"<HOSTNAME>\" not found"
````

And when running `docker ps` I can see only 6 containers.
````
CONTAINER ID   IMAGE                    COMMAND                  CREATED         STATUS         PORTS     NAMES
8dab8f31c759   0369cf4303ff             "etcd --advertise-cl…"   3 minutes ago   Up 3 minutes             k8s_etcd_etcd-<HOSTNAME>_kube-system_47193d3eb45a6af6c767d361f5df163b_24
b7941246bdbb   k8s.gcr.io/pause:3.4.1   "/pause"                 2 hours ago     Up 2 hours               k8s_POD_kube-apiserver-<HOSTNAME>_kube-system_041857bfd8b1ee80a15a7929c951db88_2
4ab72d5bd333   7a37590177f7             "kube-controller-man…"   2 hours ago     Up 2 hours               k8s_kube-controller-manager_kube-controller-manager-<HOSTNAME>_kube-system_7e852d8efb7e5c519ccef7c99fff7d77_3
abd6e9b68bea   k8s.gcr.io/pause:3.4.1   "/pause"                 2 hours ago     Up 2 hours               k8s_POD_kube-controller-manager-<HOSTNAME>_kube-system_7e852d8efb7e5c519ccef7c99fff7d77_2
2a2fb116728f   c67c2461177d             "kube-scheduler --au…"   2 hours ago     Up 2 hours               k8s_kube-scheduler_kube-scheduler-<HOSTNAME>_kube-system_69da6f38673e93a8dcbb9683f1c52166_3
ee8d8f0b7925   k8s.gcr.io/pause:3.4.1   "/pause"                 2 hours ago     Up 2 hours               k8s_POD_kube-scheduler-<HOSTNAME>_kube-system_69da6f38673e93a8dcbb9683f1c52166_2
b6dab97a2306   k8s.gcr.io/pause:3.4.1   "/pause"                 2 hours ago     Up 2 hours               k8s_POD_etcd-<HOSTNAME>_kube-system_47193d3eb45a6af6c767d361f5df163b_2
````
These are the logs from 8dab8f31c759:
`2022-06-22 14:25:45.489024 I | embed: rejected connection from "10.130.1.98:56396" (error "tls: \"10.130.1.98\" does not match any of DNSNames [\"<HOSTNAME>\" \"localhost\"] (lookup <HOSTNAME> on 192.168.11.5:53: server misbehaving)", ServerName "", IPAddresses ["<NODE-IP>" "127.0.0.1" "::1"], DNSNames ["<HOSTNAME>" "localhost"])`

These are the logs from 4ab72d5bd333:
`E0622 14:23:26.523624       1 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: Get "https://<NODE-IP>:6443/apis/coordination.k8s.io/v1/namespaces/kube-system/leases/kube-controller-manager?timeout=5s": dial tcp <NODE-IP>:6443: connect: connection refused`

These are the logs from 2a2fb116728f:
```
E0622 14:30:28.331655       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get "https://<NODE-IP>:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp <NODE-IP>:6443: connect: connection refused
E0622 14:30:28.688912       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get "https://<NODE-IP>:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp <NODE-IP>:6443: connect: connection refused
```

### What did you expect to happen?

To create a 9 year certs that will replace the ones that comes with the default kubeadm certs renew commnad/ kubeadm init.

### How can we reproduce it (as minimally and precisely as possible)?

Run these commands:
```
openssl genrsa -out front-proxy-client.key 2048 
openssl req -new -key front-proxy-client.key -out front-proxy-client.csr -config front-proxy-client.conf 
openssl x509 -req -in $CURRENT_DIR/front-proxy-client.csr -CA /etc/kubernetes/pki/front-proxy-ca.crt -CAkey /etc/kubernetes/pki/front-proxy-ca.key -CAcreateserial -out front-proxy-client.crt -days 3500 -extensions v3_ext -extfile front-proxy-client.conf
```
With this conf file:
```
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn

[ dn ]
O = system:masters
CN = front-proxy-client

[ v3_ext ]
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=clientAuth
authorityKeyIdentifier=keyid
```
And place it inside `/etc/kubernetes/pki` as an example.
**I could provide my entire script and x509 config files for this if needed**

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-17T14:41:19Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
VA
</details>

### OS version

<details>
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
hi, we have users that feed entirely custom certs in kubeadm. we also have e2e tests for that.
the better place to ask for help would be the support channels:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

i recommend stackoverflow.

/kind support
/close

**Comment by neolit123** [comment]
> To create a 9 year certs that will replace the ones that comes with the default kubeadm certs renew commnad/ kubeadm init.

btw, you also have the option to generate CSRs from kubeadm - check `kubeadm certs generate-csr`.

**Comment by tuatara73** [comment]
Thanks a lot


Regards,

*Shiran*
