### ISSUE TITLE
Replace metric apiserver_request_duration_seconds_bucket with trace

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kubernetes#110742]
### What would you like to be added?

Option1: filter out apiserver lantency trace from [apiserver tracing](https://kubernetes.io/blog/2021/09/03/api-server-tracing/)

Option2: add one trace for apiserver_request_duration_seconds_bucket

If metric alert is needed, not sure whether a simplified metric apiserver_request_duration_seconds_bucket will work or not.

### Why is this needed?

As shown in https://github.com/kubernetes/kubernetes/issues/105346, metric apiserver_request_duration_seconds_bucket's cardinality is very high. In my testing cluster, this one metric generates 1/4 of all timeseries.

\# of total: `count({__name__=~".+"})` 
\# of metric apiserver_request_duration_seconds_bucket:  `count({__name__=~"apiserver_request_duration_seconds_bucket"})`

**Comment by dashpole** [comment]
Discussed at the SIG meeting.  That metric is stable, and is used by a variety of critical uses.  Traces are meant to be sampled, and while you can produce metrics from traces, those aren't of the quality required for SLOs.  It would be better to add exemplars to the metrics we produce to make it easier to find applicable traces for slow metrics.

**Comment by CatherineF-dev** [comment]
Thanks!

/close
