### ISSUE TITLE
kubectl discovery dramatically slower on MacOS than Linux

### ISSUE THREAD

**Issue by negz** [kubernetes/kubernetes#110753]
### What happened?

We use _a lot_ of CRDs (frequently more than 1,000) in the @crossplane project. This has historically caused a bunch of problems with client-side API discovery, among other things. At the time of writing the latest releases of kubectl use a discovery client rate limiter with a generous QPS and burst (50 qps, 300 qps burst), so client-side rate limiting doesn't become a problem until the API server is serving more than 300 API groups.

Despite rate-limiting no longer coming into effect, we noticed that discovery was very slow - taking 10-20 seconds to complete. After having a few folks at @upbound run a little test (see https://github.com/crossplane/crossplane/issues/2895#issuecomment-1162688419 and following comments) we noticed that discovery specifically seems slow on MacOS - it's _dramatically_ faster on Linux.

Here's discovery happening on Linux with 1,577 CRDs across 343 API groups in around a second:

```shell
$ kubectl --kubeconfig=$HOME/.kube/config.eks version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl --kubeconfig=$HOME/.kube/config.eks get crd|wc -l
1577

$ kubectl --kubeconfig=$HOME/.kube/config.eks api-versions|wc -l
343

$ rm -rf ~/.kube/cache

$ time kubectl --kubeconfig=$HOME/.kube/config.eks get nodes
NAME                                            STATUS   ROLES    AGE   VERSION
ip-192-168-103-188.us-west-2.compute.internal   Ready    <none>   8h    v1.22.9-eks-810597c
ip-192-168-63-15.us-west-2.compute.internal     Ready    <none>   8h    v1.22.9-eks-810597c
ip-192-168-93-0.us-west-2.compute.internal      Ready    <none>   8h    v1.22.9-eks-810597c
kubectl --kubeconfig=$HOME/.kube/config.eks get nodes  0.17s user 0.21s system 35% cpu 1.067 total

$ du -hs ~/.kube/cache
7.5M    /home/negz/.kube/cache

$ speedtest
Retrieving speedtest.net configuration...
Testing from CenturyLink (REDACTED)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Ziply Fiber (Seattle, WA) [6.71 km]: 12.355 ms
Testing download speed................................................................................
Download: 443.00 Mbit/s
Testing upload speed......................................................................................................
Upload: 410.68 Mbit/s
````

Here's the same test run from MacOS against the exact same EKS cluster, taking 12+ seconds.

```shell
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
$ rmd ~/.kube/cache
$ time k get nodes
NAME                                            STATUS   ROLES    AGE   VERSION
ip-192-168-103-188.us-west-2.compute.internal   Ready    <none>   47h   v1.22.9-eks-810597c
ip-192-168-63-15.us-west-2.compute.internal     Ready    <none>   47h   v1.22.9-eks-810597c
ip-192-168-93-0.us-west-2.compute.internal      Ready    <none>   47h   v1.22.9-eks-810597c
kubectl get nodes  0.28s user 0.42s system 5% cpu 12.459 total
```

### What did you expect to happen?

I expected kubectl discovery on MacOS to be as fast as it was on Linux.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an EKS cluster.
2. Create ~1,500 CRDs across ~350 API groups.
3. Delete the discovery cache in `~/.kube/cache` 
4. Time how long the first `kubectl` command you run against the EKS cluster takes to complete

### Anything else we need to know?

Refer to https://github.com/crossplane/crossplane/issues/2895#issuecomment-1162688419 and subsequent comments for more examples of folks reproducing this.

### Kubernetes version

<details>
Note that the version of kubectl was the same on Mac and Linux for my tests.

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS - EKS
</details>

### OS version

<details>

MacOS 12.4, M1 Max

Linux as below

```console
# On Linux:
$ cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.05.20220528.d108690"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.05 (Quokka)"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.05 (Quokka)"
VERSION_CODENAME=quokka
VERSION_ID="22.05"%
$ uname -a
Linux mael 5.18.0 #1-NixOS SMP Sun May 22 19:52:31 UTC 2022 aarch64 GNU/Linux
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by pacoxu** [comment]
`time kubectl --v=6 get node` will show you how many milliseconds does the GET request taken.
```
➜  kubernetes git:(kubeadm-annotation) time kubectl --v=6 get node
I0624 11:48:43.535994   43897 loader.go:372] Config loaded from file:  /Users/pacoxu/.kube/config
I0624 11:48:43.616208   43897 round_trippers.go:454] GET https://10.6.177.41:6443/api/v1/nodes?limit=500 200 OK in 73 milliseconds
NAME       STATUS   ROLES           AGE   VERSION
daocloud   Ready    <none>          8d    v1.24.1
paco       Ready    control-plane   8d    v1.23.8-lts.1
kubectl --v=6 get node  0.10s user 0.04s system 69% cpu 0.190 total
```
Is there any difference?

**Comment by negz** [comment]
@pacoxu I'll add more details ASAP, but we're confident the slow-down is not in the network (i.e. the many GET requests). Initial profiling indicates it's something to do with writing what is fetched to the discovery cache on disk.

**Comment by sftim** [comment]
Watch out for anything where writes trigger `fsync()`: there was an issue on macOS where the only way for an app to be confident that a write had completed was to trigger a whole-filesystem sync. Libraries that like data integrity opted for the slower-but-effective approach. I've stopped using macOS so this hint is from a while back, but it might relevant.

**Comment by negz** [comment]
Thanks for the tip @sftim!

The issue definitely seems to be in the `*disk.CachedDiscoveryClient`. When I apply the diff below to switch over to a `*memory.memCacheClient` the slowness disappears and MacOS performance matches that of Linux - about a second for `kubectl get nodes` to perform discovery:

```shell
$ bin/kubectl api-resources|wc -l
1633

$ time bin/kubectl get nodes
NAME                                            STATUS   ROLES    AGE    VERSION
ip-192-168-103-188.us-west-2.compute.internal   Ready    <none>   5d3h   v1.22.9-eks-810597c
ip-192-168-63-15.us-west-2.compute.internal     Ready    <none>   5d3h   v1.22.9-eks-810597c
ip-192-168-93-0.us-west-2.compute.internal      Ready    <none>   5d3h   v1.22.9-eks-810597c
bin/kubectl get nodes  0.13s user 0.06s system 17% cpu 1.058 total

# We're using an in-memory cache - no cache directory is being created
$ l  ~/.kube
config  configbak  kind.yaml
~ $
```

```diff
diff --git a/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go b/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
index 0d604b9c2fb..12d7c51da0b 100644
--- a/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
+++ b/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go
@@ -22,13 +22,12 @@ import (
        "regexp"
        "strings"
        "sync"
-       "time"

        "github.com/spf13/pflag"

        "k8s.io/apimachinery/pkg/api/meta"
        "k8s.io/client-go/discovery"
-       diskcached "k8s.io/client-go/discovery/cached/disk"
+       "k8s.io/client-go/discovery/cached/memory"
        "k8s.io/client-go/rest"
        "k8s.io/client-go/restmapper"
        "k8s.io/client-go/tools/clientcmd"
@@ -275,17 +274,8 @@ func (f *ConfigFlags) toDiscoveryClient() (discovery.CachedDiscoveryInterface, e
        config.Burst = f.discoveryBurst
        config.QPS = f.discoveryQPS

-       cacheDir := defaultCacheDir
-
-       // retrieve a user-provided value for the "cache-dir"
-       // override httpCacheDir and discoveryCacheDir if user-value is given.
-       if f.CacheDir != nil {
-               cacheDir = *f.CacheDir
-       }
-       httpCacheDir := filepath.Join(cacheDir, "http")
-       discoveryCacheDir := computeDiscoverCacheDir(filepath.Join(cacheDir, "discovery"), config.Host)
-
-       return diskcached.NewCachedDiscoveryClientForConfig(config, discoveryCacheDir, httpCacheDir, time.Duration(6*time.Hour))
+       dc, err := discovery.NewDiscoveryClientForConfig(config)
+       return memory.NewMemCacheClient(dc), err
 }

 // ToRESTMapper returns a mapper.
```

**Comment by pacoxu** [comment]
It seems to be a problem that would occur only once when establishing the `~/.kube/cache`.

> Watch out for anything where writes trigger `fsync()`: there was an issue on macOS where the only way for an app to be confident that a write had completed was to trigger a whole-filesystem sync. Libraries that like data integrity opted for the slower-but-effective approach. I've stopped using macOS so this hint is from a while back, but it might relevant.

@sftim  Should we add it to known issues?

Some explain about fsync in MacOs in https://twitter.com/marcan42/status/1494213862970707969
> As it turns out, macOS cheats. On Linux, fsync() will both flush writes to the drive, and ask it to flush its write cache to stable storage.
>
> But on macOS, fsync() only flushes writes to the drive. Instead, they provide an F_FULLSYNC operation to do what fsync() does on Linux.

**Comment by sftim** [comment]
> known issues

Hi, I have no strong opinion here.

**Comment by negz** [comment]
> It seems to be a problem that would occur only once when establishing the ~/.kube/cache.

You're right, and this happens every 6 hours in the latest versions of kubectl when the cache is invalidated. It's still not an ideal user experience though - you can imagine kubectl 'hanging' for 10-20 seconds the first time you used it each day.

**Comment by apelisse** [comment]
Also note that this should fix a lot of that problem: https://github.com/kubernetes/enhancements/pull/3364

**Comment by apelisse** [comment]
has anyone been able to profile kubectl to see what it's doing?

**Comment by apelisse** [comment]
Also note that your CPU is mostly doing nothing, so it's most likely stuck on IO

**Comment by negz** [comment]
I think @sftim is correct - my bet is we're blocking on `f.Sync`, which per https://github.com/golang/go/issues/26650 uses `F_FULLFSYNC` on MacOS. Per [`man fnctl` on MacOS](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fcntl.2.html#//apple_ref/doc/man/2/fcntl):

> `F_FULLFSYNC` Does the same thing as [fsync(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html#//apple_ref/doc/man/2/fsync) then asks the drive to flush all buffered data to the permanent storage device (arg is ignored).  This is currently implemented on HFS, MS-DOS (FAT), and Universal Disk Format (UDF) file systems. The operation may take quite a while to complete.  Certain FireWire drives have also been known to ignore the request to flush their buffered data.

The attached mutex profile shows a lot of time waiting for `sync.Unlock` inside [`diskv.WriteStream`]( https://github.com/peterbourgon/diskv/blob/2566386005f64f58f34e1ff32907800a64537e6a/diskv.go#L194). I'm not a Go profiling expert, but I suspect this is indicating that the code running "inside" the lock is taking a long time to complete. `WriteStream` is called by [`diskcache.Set`](https://github.com/gregjones/httpcache/blob/master/diskcache/diskcache.go#L32), which you can see sets the `sync` argument to `true`. I believe this means we're doing an `F_FULLFSYNC` for every HTTP response body we encounter while doing discovery per [the `httpcache.RoundTrip` code](https://github.com/gregjones/httpcache/blob/901d90724c7919163f472a9812253fb26761123d/httpcache.go#L221).

**Comment by negz** [comment]
How do folks feel about not explicitly calling `Sync` for each file in the HTTP cache? Given that it is indeed only a cache I lean toward optimizing for write performance rather than data safety.

If we did want to stop calling `Sync` it seems like the best option would be to update the `diskcache` package of https://github.com/gregjones/httpcache that we use today to make whether it calls `diskv.WriteStream` with `sync=true` configurable. I'm skeptical we could get this change merged upstream though - the latest change to `httpcache` was three years ago.

Another option might be to switch the the `leveldbcache` package. I just took a brief shot at this, but it seems like it would require some refactoring to the `disk.CachedDiscoveryClient` to handle calling `Close()` on the underlying database.

**Comment by liggitt** [comment]
> Given that it is indeed only a cache I lean toward optimizing for write performance rather than data safety.

I don't care a ton if we drop a cache file coherently. I care a lot if a write fails in a way that leaves a partially written file in a way that pollutes the cache and makes the user have to delete the file from the cache manually. 

I don't know which of those we're opening ourselves up to by writing without sync. Can we find out?

**Comment by negz** [comment]
@liggitt Presuming we do find that not fsyncing leaves the cache in a broken state (as opposed to a partial state) would falling back to invaliding the cache and recreating it be acceptable?

**Comment by negz** [comment]
Little more insight at https://mjtsai.com/blog/2022/02/17/apple-ssd-benchmarks-and-f_fullsync/ and https://developer.apple.com/documentation/xcode/reducing-disk-writes. Notably the second link mentions:

> Only use `F_FULLFSYNC` when your app requires a strong expectation of data persistence. Note that `F_FULLFSYNC` represents a best-effort guarantee that iOS writes data to the disk, but data can still be lost in the case of sudden power loss.

**Comment by negz** [comment]
> I care a lot if a write fails in a way that leaves a partially written file in a way that pollutes the cache and makes the user have to delete the file from the cache manually.

I dug into this a bit - dumping state here before I sign off for the day.

First, note that the `kubectl` discovery client uses two layers of cache - a "discovery cache" and an "HTTP cache". The former appears to be backed by the latter. My `git blame`-fu is not strong enough to figure out why we do this. The best I could find is [this commit](https://github.com/kubernetes/kubernetes/pull/63550/commits/57f308ae60875e90004dca592d47cbf6bce390ba#r187948790), which refers to "restoring the old cached client behavior" and appears to (re?)introduce the caching HTTP transport. Perhaps @soltysh, @liggitt, or @apelisse know why this is?

Only the HTTP cache is explicitly calling `f.Sync()`. The discovery cache just writes the files and calls `f.Close()`, so it's already subject to the risks of not using `F_FULLFSYNC`. Per [fsync(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fsync.2.html#//apple_ref/doc/man/2/fsync) that risk is that despite the write having been flushed from the OS to the disk controller (e.g. by successfully calling `f.Close()`):

> [...] if the drive loses power or the OS crashes, the application may find that only some or none of their data was written.

My understanding of the `httpcache` and `diskv` code that powers the HTTP cache is:

* If a `diskv` cache file read returns an error we just act as if the value isn't in cache.
* If a `diskv` cache file read returns garbled data that `httpcache` can't parse as an http response `httpcache` would fall back to its underlying `Transport` (i.e. make a call to the API server) and `diskv` will happily cache over the top of an existing (potentially garbled) file.
* The caches will be invalidated after six hours.

So the failure mode that wouldn't be covered if we stopped calling `f.Sync()` is that if power were cut to the drive before its controller could sync down to persistent storage _and_ this resulted in a file that was garbled just right such that it appeared to be a valid HTTP response but contained an invalid body (i.e. not real discovery data) someone would have to either manually remove their cache, or wait six hours for the cache to be automatically invalidated.

It seems like we could probably make the discovery client force an uncached request through the caching HTTP transport if it encountered what appeared to be cached, invalid discovery data, but I do wonder how far we really need to go to ensure that this cache is never corrupted.

**Comment by sftim** [comment]
For either of these caches, there are techniques (checksums and the like) where we can allow the app to see whether or not it is looking at a coherent cache document or something that might not be correct.

Whenever a cache entry doesn't look valid, the code can asset that the date is current and the entry checksum is OK. If the entry turns out to be invalid or stale, remove it and then act as if we got a read error. That should cover any kind of unsynchronised write failure, I think.

For _locking_ the cache we also don't need to ensure sync-to-disk, so long as all running processes see a consistent view of locking.

**Comment by negz** [comment]
> For either of these caches, there are techniques (checksums and the like) where we can allow the app to see whether or not it is looking at a coherent cache document or something that might not be correct.

@sftim Agreed. My question is whether we need to add such techniques to this particular cache (or caches) before we'll feel comfortable removing the fsync.

Removing the fsync from the HTTP cache would presumably bring it back down to the same level of guarantee as the discovery cache. My guess would be that the fact we were ever explicitly fsyncing each cache value in the HTTP cache was a happy accident rather than something that was explicitly a desirable quality for the HTTP cache.

**Comment by negz** [comment]
> My question is whether we need to add such techniques to this particular cache (or caches) before we'll feel comfortable removing the fsync.

It seemed like writing our own httpcache cache backend was the best way to go here, so I went ahead and added one that uses checksums rather than syncs per the above PR.
