### ISSUE TITLE
New takes precedence over old

### ISSUE THREAD

**Issue by fengpengyun** [kubernetes/kubernetes#110793]
### What happened?

[source of the issue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/resource_quota_controller.go)
```
// Sync periodically resyncs the controller when new resources are observed from discovery.
func (rq *Controller) Sync(discoveryFunc NamespacedResourcesFunc, period time.Duration, stopCh <-chan struct{}) {

	oldResources := make(map[schema.GroupVersionResource]struct{})
	wait.Until(func() {

		newResources, err := GetQuotableResources(discoveryFunc)
		if err != nil {
			utilruntime.HandleError(err)

			if discovery.IsGroupDiscoveryFailedError(err) && len(newResources) > 0 {
				// Because only the key of new Resources is used later, it does not matter to overwrite, but this is a hidden danger
				for k, v := range oldResources {
					newResources[k] = v
				}
			} else {

				return
			}
		}

                //  If the front can be covered, then there may be a problem with the comparison here
		if reflect.DeepEqual(oldResources, newResources) {
			klog.V(4).Infof("no resource updates from discovery, skipping resource quota sync")
			return
		}
          。。。。。。。
}
```

### What did you expect to happen?

New takes precedence over old

### How can we reproduce it (as minimally and precisely as possible)?

[source of the issue](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/resourcequota/resource_quota_controller.go)

### Kubernetes version

I saw by reading the latest source code

### Cloud provider

I saw by reading the latest source code

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fengpengyun** [comment]
triage/accepted

**Comment by twilight0620** [comment]
The following is my understanding. I am not sure whether it is correct:
If you go into the code of 'if discovery.IsGroupDiscoveryFailedError(err) && len(newResources) > 0', 
it means the group discovery has errors, then the newResources should not be continue handling. 
Even if the value of newResources is overwritten by the value of oldResources,
the results of the following comparison 'reflect.DeepEqual(oldResources, newResources)' will be true, 
and the code will return.  It seems no problem.

**Comment by fengpengyun** [comment]
@twilight0620 What GetQuotableResources(discoveryFunc) returns is not necessarily wrong, it may be the correct data in the execution error。

**Comment by jlsong01** [comment]
@leilajal hey, the pr review has been pending for several months. could you help to take a look please? Thanks
