### ISSUE TITLE
structured logging: switch from KObjs to KObjSlice

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#110737]
### What would you like to be added?

https://github.com/kubernetes/klog/pull/322 added klog.KObjSlice as replacement for klog.KObjs. A version of klog with that is now in Kubernetes master.

We should:
- [ ] Search/replace calls to KObjs in all of Kubernetes.
- [ ] In places where the `if klogV := klog.V(5); klogV.Enabled() { klogV.Info(..., klog.KObjs(...) }` pattern was used, consider whether a direct `klog.V(5).Info(..., klog.KObjSlice(...))` call can be used instead. This is okay if there are no other parameters that are expensive to compute.
- [ ] Update https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md.
- [ ] When this is done, extend https://github.com/kubernetes-sigs/logtools to complain about usage of klog.KObjs. This is optional. A better way would be to enable pre-merge linting where usage of *any* deprecated function becomes merge-blocking (see https://github.com/kubernetes/kubernetes/pull/109728).

/sig instrumentation
/wg structured-logging

### Why is this needed?

klog.KObjSlice takes constant time when called to prepare the parameter, in contrast to klog.KObjs which is linear with the number of entries it needs to handle.

**Comment by pohly** [comment]
When preparing a PR which removes KObj, remember to include a meaningful "why this is needed" in the PR description itself. A link to this issue can be added, but that alone is not enough for reviewers because it makes them do extra work (look up an issue and read through all of it).

**Comment by harshanarayana** [comment]
/assign

Can I take this one up ?

**Comment by pohly** [comment]
Yes, please do.

**Comment by yangjunmyfm192085** [comment]
/assign
I can take one of these
Could we be together？@harshanarayana

**Comment by yangjunmyfm192085** [comment]
I can work on this `Search/replace calls to KObjs in all of Kubernetes`.

**Comment by harshanarayana** [comment]
@yangjunmyfm192085 I just finished the first one and half way through the second. The other two I have not yet taken a look into. Mind taking one of those two ?
