### ISSUE TITLE
error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason /triage accepted

### ISSUE THREAD

**Issue by QiuToo** [kubernetes/kubernetes#110787]
[root@two-master ~]# journalctl  -xeu kube-controller-manager  | tail  -10
6月 25 22:29:55 two-master kube-controller-manager[1823]: E0625 22:29:55.127157    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:29:57 two-master kube-controller-manager[1823]: E0625 22:29:57.363636    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:01 two-master kube-controller-manager[1823]: E0625 22:30:01.442313    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:04 two-master kube-controller-manager[1823]: E0625 22:30:04.485936    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:07 two-master kube-controller-manager[1823]: E0625 22:30:07.094467    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:10 two-master kube-controller-manager[1823]: E0625 22:30:10.880910    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:15 two-master kube-controller-manager[1823]: E0625 22:30:15.074529    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:18 two-master kube-controller-manager[1823]: E0625 22:30:18.595777    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:21 two-master kube-controller-manager[1823]: E0625 22:30:21.526867    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
6月 25 22:30:25 two-master kube-controller-manager[1823]: E0625 22:30:25.078083    1823 leaderelection.go:325] error retrieving resource lock kube-system/kube-controller-manager: the server rejected our request for an unknown reason (get leases.coordination.k8s.io kube-controller-manager)
[root@two-master ~]#

**Comment by neolit123** [comment]
Please try asking on the support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

If a bug is confirmed reopen and add more details.
