### ISSUE TITLE
kube-scheduler: improve FailedScheduling message for PreFilter plugin

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes/kubernetes#110783]
### What would you like to be added?

**Problem**
`kube-scheduler` assigns the same status to all nodes when a `PreFilter` plugin returns error.https://github.com/kubernetes/kubernetes/blob/11686e138694a67452ce9fe4244ba96982cc545a/pkg/scheduler/schedule_one.go#L380

 The resulted `FailedScheduling` event message can be confusing. For example, when `InterPodAffinity` plugin's `PreFilter` fails to list `NodeInfos`, the scheduling failure event will look like

```
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  31h   default-scheduler  0/134 nodes are available: 134 failed to list NodeInfos ....
```
 
**Proposal** 
Instead of setting the same status/error for all nodes as 
```
        for _, n := range allNodes {
            diagnosis.NodeToStatusMap[n.Node().Name] = s
        }
```

Only set the status once for `PreFilter` error? ` Node().Name `can be a dummy one such as "". 
 ``` 
          diagnosis.NodeToStatusMap[""] = s
```
A prefix string "PreFilter" can also be added to the beginning of the error message. The new `FailedScheduling` event will look like

```
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  31h   default-scheduler  0/134 nodes are available: 1 PreFilter failed to list NodeInfos ....
```

### Why is this needed?

The current `FailedScheduling` event message can be confusing when a `PreFilter` plugin returns an error. By improving the  error message for `PreFilter` plugin,  `FailedScheduling` event will be easier to read and understand.

**Comment by Huang-Wei** [comment]
Makes sense to me. The comments also suggested for further refactoring:

https://github.com/kubernetes/kubernetes/blob/10810ab42bc8acde6732feae545aa34a09ecd299/pkg/scheduler/schedule_one.go#L380-L384

Regarding the solution, instead of directly manipulating `NodeToStatusMap`, I'd prefer to come up with an explicit wrapper function to set/get failure reason for a given hostname:

```go
// Setting value.
diagnosis.NodeToStatusMap.Set(ALL, status)

// Get value.
diagnosis.NodeToStatusMap.Get(nodeName)
// Internally, the Get() function would check if nodeName is present, and fall back to ALL otherwise.
```

**Comment by Huang-Wei** [comment]
Cc @ahg-g for ideas who commented on the "non trivial refactoring" stanza.

**Comment by ahg-g** [comment]
Introducing special meaning to entries in `NodeToStatusMap` seems dangerous; another option is to add a `PreFilterMsg` to Diagnosis just like we have for PostFilter; wdyt?

**Comment by Huang-Wei** [comment]
> another option is to add a PreFilterMsg to Diagnosis just like we have for PostFilter; wdyt?

SGTM as explicity is better than implicity. Just want to point out, no matter which implementation to go with, we need to make it secure enough given `NodeToStatusMap` is directly accessed in many places like Preemption, also,  `len(diagnosis.NodeToStatusMap)` is directly read.

**Comment by yuanchen8911** [comment]
> > another option is to add a PreFilterMsg to Diagnosis just like we have for PostFilter; wdyt?
> 
> 
> 
> SGTM as explicity is better than implicity. Just want to point out, no matter which implementation to go with, we need to make it secure enough given `NodeToStatusMap` is directly accessed in many places like Preemption, also,  `len(diagnosis.NodeToStatusMap)` is directly read.

Thank you. I'll look at it.

**Comment by yuanchen8911** [comment]
Submitted a PR https://github.com/kubernetes/kubernetes/pull/110894.
