### ISSUE TITLE
make ServiceAccounts easier to work with - post1.0

### ISSUE THREAD

**Issue by deads2k** [kubernetes/kubernetes#11070]
Having spent some time working with service accounts downstream, there are a few enhancements I'd like to see post-1.0
1. Make it easier to get a valid token for a service account.  The long-lived, but fully revocable aspect of SA tokens makes it desirable to use them for machine accounts, but it is really painful to describe to a user how they can get the SA token outside of a pod.  While I recognize that we'd like everything to be a pod, the world hasn't fully changed yet.
2. Make it easier to create a new token for a service account.  Related to the first point, but I'd like to be able to allow a user to create a new token for a single service account without giving them rights to create or get tokens in general.  Currently, there's no way to do that.  Also, it's really hard to describe to someone how to perfectly craft a secret to a token automatically filled in.
3. Allow user to rotate a service account token, without granting delete rights to secrets.  Right now, the only way to rotate an SA token is to delete the secret.  The power to delete arbitrary secrets is more significant than the power to rotate an SA token.
4. Create separate field for `AutomountedSecrets`.  The auto-mounting feature for service accounts is really nice, but sometimes I only want to use service accounts for things like pull secrets and I don't want them to handle their credentials out to ever pod they're attached to.  Rather than place the burden on an RC or a Pod to create a conflicting volume mount, I'd like to be able to explicitly choose which secrets get automounted.  This would also allow someone to describe additional secrets that get automounted.

@liggitt @smarterclayton @pmorie

**Comment by liggitt** [comment]
2a. Make token creation synchronous... https://github.com/GoogleCloudPlatform/kubernetes/pull/8866 was an attempt at that

**Comment by liggitt** [comment]
@erictune

**Comment by liggitt** [comment]
Additional things from my list:
5 - Allow indicating a service account grants access to some set of secrets (via selector, or "allow any", or ...). Once namespace permission partitioning occurs, and admission control starts enforcing which secrets a pod can reference based on its service account, we'll want to be able to say things like "serviceaccount X can use any secret, but serviceaccount Y can only use these particular secrets"
6 - Allow adding a secret reference to a service account via the API (secret binding object, etc). Allows creation of a secret, a "secret binding" to a service account, and a pod using the service account and mounted secret all at once using a resources.json with `kubectl create -f ...`

**Comment by erictune** [comment]
Yes 6.

**Comment by smarterclayton** [comment]
Although I'd almost prefer not having to know about the service account at
all (have the secret added to the default service account implicitly).
Having to bind to a service account always introduces a point of coupling
that the pod author (or template author) may not need to know about.

Service accounts exist in part to enable isolation of secrets.  But
mandating the isolation puts the burden on template authors who want to use
secrets to know the name of the service account they want to use.  That
takes away control from a project administrator.

On Jul 13, 2015, at 11:46 AM, Eric Tune <notifications@github.com> wrote:

Yes 6.

On Fri, Jul 10, 2015 at 12:57 PM, Jordan Liggitt <notifications@github.com>
wrote:

> Additional things from my list:
> 5 - Allow indicating a service account grants access to some set of
> secrets (via selector, or "allow any", or ...). Once namespace permission
> partitioning occurs, and admission control starts enforcing which secrets
a
> pod can reference based on its service account, we'll want to be able to
> say things like "serviceaccount X can use any secret, but serviceaccount Y
> can only use these particular secrets"
> 6 - Allow adding a secret reference to a service account via the API
> (secret binding object, etc). Allows creation of a secret, a "secret
> binding" to a service account, and a pod using the service account and
> mounted secret all at once using a resources.json with kubectl create -f
> ...
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/GoogleCloudPlatform/kubernetes/issues/11070#issuecomment-120507662
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11070#issuecomment-120974433>
.

**Comment by erictune** [comment]
Re 1:
Can you elaborate.  You want to run something not in a pod, and have it use a kubernetes generated service account token?  What is this thing?  How can a thing that is not in a namespace be associated with a namespace?

Re 2: why do they want to do that?

Re 3:  seems fine.

Re 4:  
So, in the solution you envision for 4, you could create a service account that has a certain imagePullSecret but no API access token by POSTing a serviceAccount resource with "automountedSecrets" set to an empty list?  sounds good.

Re 5: you would do this for a service account the same way you would do it for a human user, right? if so, what change is needed.   If not, why not?

Re 6: not sure I read this right the first time, and not sure I agree now.

**Comment by deads2k** [comment]
> Can you elaborate. You want to run something not in a pod, and have it use a kubernetes generated service account token? What is this thing? How can a thing that is not in a namespace be associated with a namespace?

A service account exists in a namespace, but the authenticator maps it to a unique user that is valid for the cluster as a whole.  That makes it possible for an authorizer to have rules that grant broader privileges.  For example, consider a `pod-watcher` service account in the `monitoring` namespace.  You could grant it privileges to list all pods in the cluster and it could use that power to look for pods that have been pending for over an hour.  The namespace is simply a place for the service account to live, but it's permissions don't have to be that restricted.  The same utility exists in a single namespace if project admins want to have narrowly scoped machine accounts.

**Comment by deads2k** [comment]
> Re 2: why do they want to do that?

If you accept that users can (should?) use service accounts to run machine actions on their clusters, then the ability to limit the distribution of individual tokens is valuable.  If I have a set of different tokens for the same service account to perform various maintenance and monitoring tasks on my cluster, then I'm able to revoke particular tokens in the case of compromise.

**Comment by deads2k** [comment]
> So, in the solution you envision for 4, you could create a service account that has a certain imagePullSecret but no API access token by POSTing a serviceAccount resource with "automountedSecrets" set to an empty list? sounds good.

Yes.

**Comment by deads2k** [comment]
> Re 5: you would do this for a service account the same way you would do it for a human user, right? if so, what change is needed. If not, why not?

Since we wrote this up initially, we've discovered the amount of friction when trying to use secrets is very high.   https://github.com/GoogleCloudPlatform/kubernetes/pull/11827 addresses this by it in the other direction.  By default, a service account can access any secret.  If a particular annotation is set or a global flag on the admission controller is turned on, then access to secrets can be partitioned through service accounts.

**Comment by liggitt** [comment]
David, can you clarify the difference between being able to access secrets while acting as a service account using the API, and a pod being able to reference secrets in its spec?

**Comment by deads2k** [comment]
> Re 6: not sure I read this right the first time, and not sure I agree now.

One of the big difficulties in using service accounts to limit access to secrets is the inability to simultaneously limit secret references via a service account and have an PodSpec (in any containing object) that uses secrets and can actually be created.  The problem you run into is that the service account admission controller will reject the Pod because the SA doesn't allow that secret to be mounted.  One solution we tried was to add an SA with the correct mountable secret references to the the `List` we were trying to create.  This created two problems: 1) conflicting SA names, and 2) race conditions for pod admission based on whether the SA token was created in time.

Combining 6 with 4 solves this problem.  Using 4, the pod would no longer be rejected by admission (problem 2 with SA in List approach).  Using 6, the secret could be added to SA that was just created or the pre-existing one with the same name.  This way, valid PodSpecs can be created.

**Comment by deads2k** [comment]
> David, can you clarify the difference between being able to access secrets while acting as a service account using the API, and a pod being able to reference secrets in its spec?

There is a distinction between a service account allowing a secret to be mounted and a service account being allowed to `GET` a secret.  Direct retrieval of a secret is more powerful than being allowed to mount that secret in pod.  With the ability to limit which images can pulled, it becomes possible to have a safe whitelist of images that are known to keep secrets safe.  A user could then be trusted to a Pod using that secret, but not have access to the secret itself.

Most of the time, I would expect that SAs would not have `GET` access to the secrets in a given namespace to limit the risks of exposure.  Sort of like not allowing a process to modify its own config file.  Because SA tokens are contained in secrets, GET access to secrets implies the ability to impersonate any SA in the namespace.  As a side note, I would like to change that and remove the SA tokens from secrets.  That would allow me to better secure my cluster, by preventing everyone with read access to secrets from impersonating an SA of their choosing.

**Comment by smarterclayton** [comment]
On Jul 30, 2015, at 8:20 AM, David Eads <notifications@github.com> wrote:

David, can you clarify the difference between being able to access secrets
while acting as a service account using the API, and a pod being able to
reference secrets in its spec?

There is a distinction between a service account allowing a secret to be
mounted and a service account being allowed to GET a secret. Direct
retrieval of a secret is more powerful than being allowed to mount that
secret in pod. With the ability to limit which images can pulled, it
becomes possible to have a safe whitelist of images that are known to keep
secrets safe. A user could then be trusted to a Pod using that secret, but
not have access to the secret itself.

Most of the time, I would expect that SAs would not have GET access to the
secrets in a given namespace to limit the risks of exposure. Sort of like
not allowing a process to modify its own config file. Because SA tokens are
contained in secrets, GET access to secrets implies the ability to
impersonate any SA in the namespace. As a side note, I would like to change
that and remove the SA tokens from secrets. That would allow me to better
secure my cluster, by preventing everyone with read access to secrets from
impersonating an SA of their choosing.


I'm not sure removing them improves the problem - now you would have two
separate resources you have to reference to mount inside a pod.

Read access to all namespace secrets is inherently dangerous - I would
suggest that long term we try to remove the areas where that path is
executed and replace them with more scoped access.  If, for instance, you
could only access secrets via a pod subresource that would guarantee that
you can only see explicit secrets.

Another option might be to try and find a way to make explicit that adding
a secret *requires* a service account - perhaps by offering the intent to
bind a secret to the service account when you create a secret.  The person
who has the secret is the one who is authorized to give it to someone else.
Either a SecretBinding (post secret to service account subresource) or a
new top level ServiceAccountSecret virtual resource would be sufficient.
All that has to be checked then is edit access to a service account.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11070#issuecomment-126304887>
.

**Comment by pmorie** [comment]
> Read access to all namespace secrets is inherently dangerous - I would
suggest that long term we try to remove the areas where that path is
executed and replace them with more scoped access.  If, for instance, you
could only access secrets via a pod subresource that would guarantee that
you can only see explicit secrets.

+1 to this

> Allow user to rotate a service account token, without granting delete rights to secrets. Right now, the only way to rotate an SA token is to delete the secret. The power to delete arbitrary secrets is more significant than the power to rotate an SA token.

@deads2k @erictune @smarterclayton 

The secrets proposal hinted at rotation but we punted on trying to solve it.  I think the use-case you articulate here is a good one -- am I correct in thinking that what you imagine is something like a user rotating a secret interactively via `kubectl`?  The use-case I had in mind when writing the proposal was for auto-rotation, which I think we should be careful not to design ourselves out of being able to support.

Talking about rotation probably means we need to talk about:

1.  Capturing the resource version of a secret that a pod is referencing
2.  What happens to existing pods that reference a secret when it is updated
3.  Will we allow you to manually invoke a built-in generator for a known secret type?

> Create separate field for AutomountedSecrets. The auto-mounting feature for service accounts is really nice, but sometimes I only want to use service accounts for things like pull secrets and I don't want them to handle their credentials out to ever pod they're attached to. Rather than place the burden on an RC or a Pod to create a conflicting volume mount, I'd like to be able to explicitly choose which secrets get automounted. This would also allow someone to describe additional secrets that get automounted.

This seems related to what @erictune wanted in #9902.  When you add a secret to the `AutomountedSecrets` field, what happens to the pods using that `ServiceAccount` ?

**Comment by pmorie** [comment]
Should be in the laundry list of things to discuss: #8738

**Comment by erictune** [comment]
@deads2k wrote in response to my question about his item 2: *If I have a set of different tokens for the same service account to perform various maintenance and monitoring tasks on my cluster, then I'm able to revoke particular tokens in the case of compromise.*  

If the tasks are different, should each thing have its own service account (ideally with only the permissions it needs?)

**Comment by erictune** [comment]
Re: item 1: I think you are saying that you have some process that runs on its own box - not a pod - and it needs a service account to access the apiserver.  Okay, I buy that use case.

**Comment by pmorie** [comment]
@deads2k @erictune @liggitt

I have been wondering to myself whether we have enough things we want to do
that we should have 'round 2' (electric boogaloo) proposals for secrets and
service accounts.

Thoughts?

**Comment by deads2k** [comment]
> I have been wondering to myself whether we have enough things we want to do
> that we should have 'round 2' (electric boogaloo) proposals for secrets and
> service accounts.
> 
> Thoughts?

I'm not adverse to revisiting service accounts, but I think I'd still like to see some incremental improvement.  1 (easier to get a token) and 5 (non-restrictive default, but options for secret restriction) are both relatively straightforward for big gains in usability based on what we've learned so far.

The others involve more surgery, so I could see putting them off if we want to redesign.  I'd want to do it sooner rather than later though:  number 4 (automounted secrets) is quite important to us.

**Comment by pmorie** [comment]
@deads2k Yep, I don't mean at all to say that we should put the brakes on incremental improvements.  I just think we have enough things we want to change about secrets / service accounts that it might be easier to collect them into a single design doc and solve them in one place at one time rather than having _n_ different github issues.

**Comment by liggitt** [comment]
Largely addressed by the tokenrequest proposal

#58790 

/close
