### ISSUE TITLE
data race in nodeshutdown tests

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#110854]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110768/pull-kubernetes-unit/1541991414412349440
```
WARNING: DATA RACE
Read at 0x00c0004c1703 by goroutine 96:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:882 +0x4ce
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:869 +0x84
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:910 +0x58
  testing.(*T).Log()
      <autogenerated>:1 +0x55
  k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting.(*tlogger).log()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting/testinglogger.go:279 +0x524
  k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting.(*tlogger).Info()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting/testinglogger.go:250 +0x157
  k8s.io/kubernetes/vendor/github.com/go-logr/logr.Logger.Info()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/go-logr/logr/logr.go:261 +0xe3
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).processShutdownEvent.func3()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:386 +0x7e4
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).processShutdownEvent.func5()
      /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:388 +0x9d
Previous write at 0x00c0004c1703 by goroutine 8:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1426 +0x7af
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:436 +0x32
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1486 +0x47
```

### Which tests are flaking?

`TestLocalStorage` in `pkg/kubelet/nodeshutdown`

### Since when has it been flaking?

N/A

### Relevant SIG(s)

/sig node

**Comment by kerthcet** [comment]
cc @pohly as we introduced contextual logging weeks ago, I have no idea whether this is related.

**Comment by pohly** [comment]
Contextual logging is involved here because it enables log output through testing.T.Log.

It's interesting that the data race seems to be inside testing.T itself. It does [mutex locking](https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/testing/testing.go;drc=d3ffff2790059226ae3aa90856d687e138701b5c;l=880) but apparently the access to the mutex itself is racing?!

/assign

**Comment by pohly** [comment]
The change which triggered this is from PR #110504 .

**Comment by pohly** [comment]
The main problem seems to be that the `testing.T` instance becomes unusable once the test it was created for terminates. Running the test locally repeatedly, I got the data race and:
```
==================
panic: Log in goroutine after TestRestart has completed: INFO Restarting watch for node shutdown events


goroutine 77 [running]:
testing.(*common).logDepth(0xc00060d860, {0xc0006d63c0, 0x2f}, 0x3)
	/nvme/gopath/go-1.18.1/src/testing/testing.go:887 +0x6c5
testing.(*common).log(...)
	/nvme/gopath/go-1.18.1/src/testing/testing.go:869
testing.(*common).Log(0xc00060d860, {0xc000325620, 0x2, 0x2})
	/nvme/gopath/go-1.18.1/src/testing/testing.go:910 +0x85
k8s.io/klog/v2/ktesting.(*tlogger).log(0xc0004382d0, {0x27fd715, 0x4}, {0x2840e7e, 0x29}, 0x1, 0xc000927ea8, {0x0, 0x0}, {0x0, ...})
	/nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting/testinglogger.go:279 +0x525
k8s.io/klog/v2/ktesting.(*tlogger).Info(0xc0004382d0, 0x3329070?, {0x2840e7e, 0x29}, {0x0, 0x0, 0x0})
	/nvme/gopath/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/ktesting/testinglogger.go:250 +0x158
github.com/go-logr/logr.Logger.Info({{0x3329070?, 0xc0004382d0?}, 0xc0001d3fd0?}, {0x2840e7e, 0x29}, {0x0, 0x0, 0x0})
	/nvme/gopath/src/k8s.io/kubernetes/vendor/github.com/go-logr/logr/logr.go:261 +0xe4
k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).Start.func1()
	/nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:189 +0xd5
created by k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).Start
	/nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:182 +0x1cf
```

One the one hand, keeping goroutines running in the background after test completion is bad and should be avoided. On the other hand, this used to be okay(is) in the past (it just made the global log output even less useful) and cannot always be avoided.

What could be done to solve this is to "mute" testinglogger once the test completes. But that depends on a klog API extension.

**Comment by harry1064** [comment]
Hi @pohly 

Isn't systemDbus defer function get called earlier 
https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L380-L390

therefore following line get executed immediately. Hence, testing.T instance became unusable before go routines inside `Start` function finishes.
https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L418

**Comment by pohly** [comment]
`TestRestart` is a red herring (= not relevant). The unexpected output must be coming from one of the other unit tests, for example:

https://github.com/kubernetes/kubernetes/blob/dafa55be106730eaacb740e20b999b84848c6ac5/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L692

We have to add `defer ktesting.Stop(logger)` after such lines.

**Comment by pohly** [comment]
Scratch that. The version of TestRestart that you linked to doesn't use ktesting, but master does.

**Comment by pohly** [comment]
Hmm, does this test also have other data races?

After adding `ktesting.Stop`, I get:
```
Read at 0x00000402c820 by goroutine 112:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).start()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:202 +0x49
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).Start.func1()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:190 +0xde

Previous write at 0x00000402c820 by goroutine 106:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:391 +0x326
  testing.tRunner()
      /nvme/gopath/go-1.18.1/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /nvme/gopath/go-1.18.1/src/testing/testing.go:1486 +0x47
```

That's a race around setting and calling `systemDbus`.

When checking out the version prior to my contextual logging change, I get:
```console
$ git checkout 65385fec209fb5a6d549129fb03cd529c25a2cff~
Previous HEAD position was 10bea49c12d Merge pull request #110140 from marosset/hpc-sandbox-config-fixes
$ go test -count=5 -race ./pkg/kubelet/nodeshutdown/
...
--- FAIL: TestRestart (0.00s)
panic: close of closed channel [recovered]
	panic: close of closed channel

goroutine 424 [running]:
testing.tRunner.func1.2({0x25cb900, 0x32fe1d0})
	/nvme/gopath/go-1.18.1/src/testing/testing.go:1389 +0x366
testing.tRunner.func1()
	/nvme/gopath/go-1.18.1/src/testing/testing.go:1392 +0x5d2
panic({0x25cb900, 0x32fe1d0})
	/nvme/gopath/go-1.18.1/src/runtime/panic.go:844 +0x258
k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart(0xc000583ba0)
	/nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:422 +0x686
testing.tRunner(0xc000583ba0, 0x28f3468)
	/nvme/gopath/go-1.18.1/src/testing/testing.go:1439 +0x214
created by testing.(*T).Run
	/nvme/gopath/go-1.18.1/src/testing/testing.go:1486 +0x725
FAIL	k8s.io/kubernetes/pkg/kubelet/nodeshutdown	5.162s
FAIL
```

Trying again gives me the same race I saw earlier:
```
==================
WARNING: DATA RACE
Write at 0x000004019818 by goroutine 48:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.TestRestart()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go:380 +0x286
  testing.tRunner()
      /nvme/gopath/go-1.18.1/src/testing/testing.go:1439 +0x213
  testing.(*T).Run.func1()
      /nvme/gopath/go-1.18.1/src/testing/testing.go:1486 +0x47

Previous read at 0x000004019818 by goroutine 114:
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).start()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:200 +0x49
  k8s.io/kubernetes/pkg/kubelet/nodeshutdown.(*managerImpl).Start.func1()
      /nvme/gopath/src/k8s.io/kubernetes/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go:188 +0x104
```

https://github.com/kubernetes/kubernetes/blob/d796dd7d0f0d40157dea8e8d9c9c5cee107e13f7/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux_test.go#L380

https://github.com/kubernetes/kubernetes/blob/d796dd7d0f0d40157dea8e8d9c9c5cee107e13f7/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L200

**Comment by pohly** [comment]
That probably also would fix the non-logging race, too. I bet it is the goroutine from one test which reads `systemDbus` (because line 200 gets called in a loop) while another test sets it.

**Comment by harry1064** [comment]
Hi @pohly 
I was thinking, if the  purpose of contextual logging is to test the logs content. Can we comment out the line 

https://github.com/kubernetes/kubernetes/blob/master/vendor/k8s.io/klog/v2/ktesting/testinglogger.go#L279

This way we will not be calling `Log` on  instance of `*testing.T` and it will not panic. As, lines after already collect the string in buffer, we will still be able to test the logs content.

**Comment by pohly** [comment]
I tried to ensure that all goroutines terminate, but some functions blocked in some test cases. So a "proper" solution might not work and we need something like https://github.com/kubernetes/klog/pull/337

**Comment by harry1064** [comment]
in https://github.com/kubernetes/klog/pull/337, new Stop method will only solve the panic case, right? Go routines will still leaks from the test cases. 
And for contextual logging, where the function we want to test spawn a go routine, we will not be able to test the log content, right?

**Comment by pohly** [comment]
> in https://github.com/kubernetes/klog/pull/337, new Stop method will only solve the panic case, right? Go routines will still leaks from the test cases.

Correct.

> And for contextual logging, where the function we want to test spawn a go routine, we will not be able to test the log content, right?

The test would have to ensure that the goroutine is done with logging before checking the output.

**Comment by harry1064** [comment]
>The test would have to ensure that the goroutine is done with logging before checking the output.

Then we have to change our functionality under test to have the ability to inject something like a channel and then in the test we have to listen on that chan, in this way we can keep the `*testing.T` to not return until we read from that channel.
But that would be a lot of changes in code base, I assume.

**Comment by pohly** [comment]
> So the scenarios where we don't have fine control over go routines spawned by function under test, we will face this issue.

Yes. So is that a problem in the kubelet shutdown tests?

**Comment by pohly** [comment]
Let's keep this issue focused on what needs to be fixed in pkg/kubelet/nodeshutdownmanager.

**Comment by harry1064** [comment]
Yes, sure.

**Comment by pohly** [comment]
The klog update went in, the race in the logging path should be gone now. The kubelet shutdown test still has other data races, but they don't seem to occur in the CI.

**Comment by kerthcet** [comment]
Refer to the comment https://github.com/kubernetes/kubernetes/issues/110854#issuecomment-1178603151, I'd like to close this issue then.
/close
