### ISSUE TITLE
Audit e2e tests for usage of `default` namespace

### ISSUE THREAD

**Issue by satnam6502** [kubernetes/kubernetes#11082]
To quote @mbforbes from #11079 

There are a few others in e2e/util.go (waitForPodRunning(), testContainerOutput()) that use the default namespace that we should probably audit but I don't have time for right now because they're called in one or more "real" tests... would you be kind enough to open an issue to finish flushing this out? I worry we have more silent passes..

@quinton-hoole

**Comment by mbforbes** [comment]
Also these might be legit uses of the default namespace, but even if they are, it's good test hygiene for each test to use its own rather than the default.

**Comment by satnam6502** [comment]
Yes, the namespace in many of these functions should be abstracted into an argument e.g. waiting for a pod success is something -- even in tests -- we want to do in the system namespace, the default namespace -- or some other namespace. Having it baked in is not very flexible.

**Comment by mbforbes** [comment]
I think this is/was likely fixed, but it's worthwhile to do an audit.

**Comment by mbforbes** [comment]
(Especially because the failure mode was no-ops)

**Comment by davidopp** [comment]
Audit something that we have no evidence is broken--doesn't sound like a 1.1 blocker to me. Can we remove the label?

**Comment by ixdy** [comment]
Anyone in @kubernetes/sig-testing want to do this audit? Should be pretty straightforward, especially since I think most (if not all) tests are using `framework` now.

**Comment by jayunit100** [comment]
I'll do this. I need to start pulling my weight around here I've been lazy lately :)!

**Comment by jayunit100** [comment]
They look  clean, except 

- The add-ons tests looks suspicious, but after looking carefully, it appears `f := NewFramework("addon-update-test")` is actually used, so even though it references DefaultNS, I don't think its cluttering it up.

- There also is a services test, and this test uses default simply to check that master services are online.  Again, not cluttering it. 

So from my cursory audit, I saw no violations which created objects in default NS.  So I'd vote to close this issue.

**Comment by ixdy** [comment]
Note: we don't have all tests using `framework`; `test/e2e/namespace.go` is one example.
