### ISSUE TITLE
kube-scheduler startup informer cache race condition

### ISSUE THREAD

**Issue by shaoqin2** [kubernetes/kubernetes#110836]
### What happened?

On startup, kube-scheduler tries to [add already scheduled pod to its internal cache](https://github.com/kubernetes/kubernetes/blob/5824e3251d294d324320db85bf63a53eb0767af2/pkg/scheduler/eventhandlers.go#L180-L193). This code is invoked as part of informer's [resource handlers here](https://github.com/kubernetes/kubernetes/blob/v1.22.11/pkg/scheduler/eventhandlers.go#L296). However, in its call path, it also need to use the lister from the informer to query for the namespace object. See the call path [getUnschedulablePodsWithMatchingAffinityTerm](https://github.com/kubernetes/kubernetes/blob/5824e3251d294d324320db85bf63a53eb0767af2/pkg/scheduler/internal/queue/scheduling_queue.go#L574) -> [GetNamespaceLabelsSnapshot](https://github.com/kubernetes/kubernetes/blob/5824e3251d294d324320db85bf63a53eb0767af2/pkg/scheduler/internal/queue/scheduling_queue.go#L644) -> [nsLister.](https://github.com/kubernetes/kubernetes/blob/5824e3251d294d324320db85bf63a53eb0767af2/pkg/scheduler/framework/plugins/interpodaffinity/plugin.go#L133).

This dependency causes a race condition that sometimes when pod is added to the cache, namespace hasn't fully synced in the namespace lister yet. Causing namespace lookup to fail like this

```golang
I0628 13:51:54.367456 1449347 eventhandlers.go:186] "Add event for scheduled pod" pod="contadm/node-problem-detector-rt8fs"
E0628 13:51:54.367493 1449347 plugin.go:138] "getting namespace, assuming empty set of namespace labels" err="namespace \"contadm\" not found" namespace="contadm"
```

### What did you expect to happen?

kube-scheduler can start without race conditions caused by informer cache sync

### How can we reproduce it (as minimally and precisely as possible)?

repeatedly restarting `kube-scheduler` instance should reproduce this error. We can consistently reproduce it every 3-5 restarts

### Anything else we need to know?

Our clusters have around 3500 namespaces, which can cause informer to sync namespace slower than smaller clusters

### Kubernetes version

```
$ bin/kube-scheduler --version
Kubernetes v1.22.11
```
```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:33:55Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

NA

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux cont-139.dft.twosigma.com 5.4.134-ts1-amd64 #1 SMP Debian 5.4.134-ts1~debian10 (2021-07-22) x86_64 GNU/Linux
```
</details>

**Comment by kerthcet** [comment]
Thanks @shaoqin2 , in theory, this will happen quite frequently when we have lots of namespaces to sync with, as you saw in your clusters. But from a different perspective, when we restart the scheduler, we'll `WaitForCacheSync` before scheduling, so at that moment, we have no unschedulable pods, right? If so, this doesn't matter.

**Comment by kerthcet** [comment]
As you said, since this not affect the scheduling results, it's better to keep it as simple as we can. But maybe we can add some comments to help mitigating source code readers' confusions in the future.
