### ISSUE TITLE
Kubernetes + containerd + cilium won't install on Debian bullseye (VirtualBox ) 

### ISSUE THREAD

**Issue by jjarv-tuni** [kubernetes/kubernetes#110855]
### What happened?

Tried to install Kubernetes cluster with kubeadm.
Installation did not succeed.

--- Log clips ---

Jun 29 09:21:11 kube-node1 containerd[545]: time="2022-06-29T09:21:11.854265880+03:00" level=info msg="RunPodSandbox for &PodSandboxMetadata{Name:kube-controller-manager-kube-node1,Uid:abf22988c24fde98fe0278fbc704aa31,Namespace:kube-system,Attempt:10,} returns sandbox id \"bf9aa20a91da8bdc3ee257946071771cb61368c986253820b69e79564973cb84\""
Jun 29 09:21:11 kube-node1 kubelet[655]: E0629 09:21:11.857426     655 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-kube-node1_kube-system(abf22988c24fde98fe0278fbc704aa31)\"" pod="kube-system/kube-controller-manager-kube-node1" podUID=abf22988c24fde98fe0278fbc704aa31
Jun 29 09:21:12 kube-node1 kubelet[655]: I0629 09:21:12.605258     655 scope.go:110] "RemoveContainer" containerID="23a9fe13f18dbfa036114d0d2e59fc8f74a9463dc9368b31d737fd56237610c1"
Jun 29 09:21:12 kube-node1 kubelet[655]: E0629 09:21:12.607378     655 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-kube-node1_kube-system(abf22988c24fde98fe0278fbc704aa31)\"" pod="kube-system/kube-controller-manager-kube-node1" podUID=abf22988c24fde98fe0278fbc704aa31
Jun 29 09:21:13 kube-node1 kubelet[655]: I0629 09:21:13.608951     655 scope.go:110] "RemoveContainer" containerID="23a9fe13f18dbfa036114d0d2e59fc8f74a9463dc9368b31d737fd56237610c1"
Jun 29 09:21:13 kube-node1 kubelet[655]: E0629 09:21:13.610477     655 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-kube-node1_kube-system(abf22988c24fde98fe0278fbc704aa31)\"" pod="kube-system/kube-controller-manager-kube-node1" podUID=abf22988c24fde98fe0278fbc704aa31
Jun 29 09:21:18 kube-node1 kubelet[655]: I0629 09:21:18.563253     655 scope.go:110] "RemoveContainer" containerID="23a9fe13f18dbfa036114d0d2e59fc8f74a9463dc9368b31d737fd56237610c1"
Jun 29 09:21:18 kube-node1 kubelet[655]: E0629 09:21:18.566655     655 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-kube-node1_kube-system(abf22988c24fde98fe0278fbc704aa31)\"" pod="kube-system/kube-controller-manager-kube-node1" podUID=abf22988c24fde98fe0278fbc704aa31
Jun 29 09:21:20 kube-node1 kubelet[655]: I0629 09:21:20.335079     655 scope.go:110] "RemoveContainer" containerID="23a9fe13f18dbfa036114d0d2e59fc8f74a9463dc9368b31d737fd56237610c1"
Jun 29 09:21:20 kube-node1 kubelet[655]: E0629 09:21:20.336804     655 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-controller-manager\" with CrashLoopBackOff: \"back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-kube-node1_kube-system(abf22988c24fde98fe0278fbc704aa31)\"" pod="kube-system/kube-controller-manager-kube-node1" podUID=abf22988c24fde98fe0278fbc704aa31
---
Jun 29 09:38:11 kube-node1 containerd[545]: time="2022-06-29T09:38:11.585524477+03:00" level=info msg="StopPodSandbox for \"a77def33049ea1a072380e91a67de14c556139580da7985767470db200f8de15\" returns successfully"
Jun 29 09:38:11 kube-node1 containerd[545]: time="2022-06-29T09:38:11.587273927+03:00" level=info msg="RemovePodSandbox for \"a77def33049ea1a072380e91a67de14c556139580da7985767470db200f8de15\""
Jun 29 09:38:11 kube-node1 containerd[545]: time="2022-06-29T09:38:11.587412761+03:00" level=info msg="Forcibly stopping sandbox \"a77def33049ea1a072380e91a67de14c556139580da7985767470db200f8de15\""
Jun 29 09:38:11 kube-node1 containerd[545]: time="2022-06-29T09:38:11.587689711+03:00" level=info msg="TearDown network for sandbox \"a77def33049ea1a072380e91a67de14c556139580da7985767470db200f8de15\" successfully"
Jun 29 09:38:11 kube-node1 containerd[545]: time="2022-06-29T09:38:11.615558010+03:00" level=info msg="RemovePodSandbox \"a77def33049ea1a072380e91a67de14c556139580da7985767470db200f8de15\" returns successfully"
Jun 29 09:38:11 kube-node1 kubelet[655]: E0629 09:38:11.619319     655 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"

NAMESPACE     NAME                                 READY   STATUS             RESTARTS         AGE
kube-system   cilium-blc84                         0/1     Pending            0                112s
kube-system   cilium-operator-5887f78bbb-tj66f     0/1     Pending            0                112s
kube-system   coredns-6d4b75cb6d-6rx7j             1/1     Running            6 (5m34s ago)    71m
kube-system   coredns-6d4b75cb6d-c7gsj             1/1     Running            4 (9m9s ago)     71m
kube-system   etcd-kube-node1                      1/1     Running            10 (8m39s ago)   71m
kube-system   kube-apiserver-kube-node1            1/1     Running            14 (3m47s ago)   71m
kube-system   kube-controller-manager-kube-node1   1/1     Running            17 (5m37s ago)   71m
kube-system   kube-scheduler-kube-node1            0/1     CrashLoopBackOff   19 (2m3s ago)    70m

WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
ERRO[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory"
POD ID              CREATED              STATE               NAME                                 NAMESPACE           ATTEMPT             RUNTIME
5e80b9ba7d08e       About a minute ago   Ready               etcd-kube-node1                      kube-system         20                  (default)
542595d3bbf91       4 minutes ago        Ready               kube-controller-manager-kube-node1   kube-system         17                  (default)
3f3b2c5d9a3aa       7 minutes ago        NotReady            etcd-kube-node1                      kube-system         19                  (default)
e9f271fec59da       10 minutes ago       Ready               cilium-blc84                         kube-system         6                   (default)
661616acc4aad       12 minutes ago       Ready               kube-scheduler-kube-node1            kube-system         21                  (default)
42520aeeb7ef6       13 minutes ago       NotReady            kube-controller-manager-kube-node1   kube-system         16                  (default)
ec6b194fb13dc       14 minutes ago       NotReady            kube-scheduler-kube-node1            kube-system         20                  (default)
e1d506e2705e4       14 minutes ago       Ready               cilium-operator-5887f78bbb-tj66f     kube-system         5                   (default)
44a2e08d48e02       14 minutes ago       Ready               kube-apiserver-kube-node1            kube-system         21                  (default)
0e0538972573f       40 minutes ago       NotReady            coredns-6d4b75cb6d-6rx7j             kube-system         6                   (default)
e6371aee08dca       44 minutes ago       NotReady            coredns-6d4b75cb6d-c7gsj             kube-system         4                   (default)

### What did you expect to happen?

Successful installation

### How can we reproduce it (as minimally and precisely as possible)?

Try to install kubernetes with kubeadm on debian bullseye

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux kube-node1 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.4 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cilium-cli: v0.11.10 compiled with go1.18.3 on linux/amd64
cilium image (default): v1.11.6
cilium image (stable): v1.11.6
cilium image (running): v1.11.6
</details>

**Comment by aojea** [comment]
/remove-kind bug
/kind support

You should better use other channels like slack or discourse for these kind of question

**Comment by neolit123** [comment]
Please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
