### ISSUE TITLE
Add a context to DiscoveryClient functions and interfaces

### ISSUE THREAD

**Issue by vincepri** [kubernetes/kubernetes#110810]
### What would you like to be added?

A lot of DiscoveryClient code makes use of `context.TODO()` and makes network calls through a rest client to retrieve the information needed during discovery, see https://github.com/kubernetes/kubernetes/blob/f4abde9e57cc30efcc8f79c9ebd791d15f4164c4/staging/src/k8s.io/client-go/discovery/discovery_client.go 

### Why is this needed?

- To make use of timeouts.
- To cleanly cancel in-progress requests and/or shutdown an execution of binary.

**Comment by vincepri** [comment]
The above could be achieved in a number of ways, via a breaking change to the current APIs/interfaces, or by adding new companion "WithContext" methods/interfaces that would satisfy the same.

/sig api-machinery

**Comment by weilaaa** [comment]
Can I have a try by breaking change?

**Comment by leilajal** [comment]
/assige @seans3 @Jefftree 
@weilaaa thanks for helping, I also added more people who are working on this!
/triage accepted

**Comment by ardaguclu** [comment]
Core place consumes discovery client is [restmapper](https://github.com/kubernetes/kubernetes/blob/de4598d0db5e2babe89dd334407b2ba8024ec9a1/staging/src/k8s.io/client-go/restmapper/discovery.go) and restmapper does not have any context. 

I think, even if discovery client supports context, passing caller's context via all along to discovery client wouldn't be easy.
