### ISSUE TITLE
kubectl debug not copying all contents of original pod to new debug pod

### ISSUE THREAD

**Issue by allensiho** [kubernetes/kubernetes#110870]
### What happened?

Running below command

kubectl debug some-dotnet-3.1-pod  -n rtlapi-uat-scan  --set-image=scan-metrics=dotnet-runtime-with-tools:3.1 --copy-to=some-dotnet-3.1-pod -debug 

should copy all the files the some-dotnet-3.1-pod  to the debug pod

But when I run the command and uses `ls`  command into the new pod I only see two files copied

The pod does have a sidecar Istio which seems to have stared correctly

### What did you expect to happen?

I expect all files from the original pod to be copied to the debug pod

### How can we reproduce it (as minimally and precisely as possible)?

Perhaps try the above command with an Istio sidecar?

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"07959215dd83b4ae6317b33c824f845abd578642", GitTreeState:"clean", BuildDate:"2022-03-30T18:28:25Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by allensiho** [comment]
Thank you,

Is there a way to do that then, we just have to add an extra 

kubect cp

command?

**Comment by ardaguclu** [comment]
@allensiho  `kubectl cp` is the way to copy files between pods. as @249043822 stated `kubectl debug` copies from pod-template.

/close
