### ISSUE TITLE
I think rabbitmq would be apt to fit into kubernetes team

### ISSUE THREAD

**Issue by anudeep251** [kubernetes/kubernetes#110856]
### What would you like to be added?

The scheduler doesn't have to request the server every few seconds to check for user requests,I think we could use something like google pub/sub or rabbitmq to subscribe for such requests,imo.

### Why is this needed?

It makes me happy 😊

**Comment by aojea** [comment]
/close

Thanks for the report but this is how kubernetes works, you can read more about control loops and controllers in this page

https://kubernetes.io/docs/concepts/architecture/controller/
