### ISSUE TITLE
rbac secret value leak with list

### ISSUE THREAD

**Issue by Kevin-Li-Webjet** [kubernetes/kubernetes#110866]
### What happened?

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-list
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
  
  With only above rbac created in cluster, 
  1. kubectl get secret xxx -n xxx will be block
  2. kubectl get secrets -n xxx, will see a list in console as expected, but it brings actual values as well behind
  e.g. kubectl get secrets -n xxx -ojson
  
  If "list" can see everything, "get" verb is confused here 
  
  If "list" designed as a superset to "get", then when will give "list" in verbs, "get" should automatically work?

### What did you expect to happen?

verbs: ["list"] can only see list of object but actual value
verbs: ["get"] should be the key to limit user see actual value

### How can we reproduce it (as minimally and precisely as possible)?

apply verbs: ["list"] only in RBAC for secret
kubectl get secrets -n xxx -ojson

### Kubernetes version

1.22.6

### Cloud provider

AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
@Kevin-Li-Webjet the Kubernetes API is working as designed. Thanks for taking the time to file the report.

It is surprising when you first encounter it, but not a bug in Kubernetes. If you want to, you're welcome to point out pages in the documentation where it'd help to emphasize this point.

If you want to request an API mechanism to allow listing objects but not accessing their `.spec` and / or `.status`, have a look first for previous efforts in that direction. The idea has come up before.

Further reading:
- https://darkbit.io/blog/the-power-of-kubernetes-rbac-list
- https://blog.aquasec.com/kubernetes-verbs

/remove-kind bug
/kind support

**Comment by Kevin-Li-Webjet** [comment]
@sftim thanks a lot 
again, If "list" is designed as a superset to "get", then when will give "list" in verbs, if "get" should automatically work will help confusion by intuition for new users?

will close this ticket
