### ISSUE TITLE
`--prune` does not function with `--server-side`

### ISSUE THREAD

**Issue by jzelinskie** [kubernetes/kubernetes#110893]
### What happened?

If you attempt to use `kubectl apply --server-side --prune`, nothing is pruned.

This is unfortunate because you pretty much have to use server-side apply these days in order to get around issues with CRDs reaching max-size annotation.

Sorry to name & shame, but many popular operators have this issue:

```
The CustomResourceDefinition "prometheuses.monitoring.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

### What did you expect to happen?

I expected the whitelisted types to be pruned.

### How can we reproduce it (as minimally and precisely as possible)?

First I demonstrate client-side apply functioning, but then server-side failing.

```console
$ cat one-namespace.yaml
   1   │ ---
   2   │ apiVersion: "v1"
   3   │ kind: "Namespace"
   4   │ metadata:
   5   │   name: "test-prune"
   6   │   labels:
   7   │     prune: "yes"
   8   │     app.kubernetes.io/name: "test-prune"

$ cat two-namespace.yaml
   1   │ ---
   2   │ apiVersion: "v1"
   3   │ kind: "Namespace"
   4   │ metadata:
   5   │   name: "test-prune"
   6   │   labels:
   7   │     prune: "yes"
   8   │     app.kubernetes.io/name: "test-prune"
   9   │ ---
  10   │ apiVersion: "v1"
  11   │ kind: "Namespace"
  12   │ metadata:
  13   │   name: "test-prune-another"
  14   │   labels:
  15   │     prune: "yes"
  16   │     app.kubernetes.io/name: "test-prune-another"

$ kubectl apply -f two-namespace.yaml --prune-whitelist 'core/v1/Namespace' --prune -l "prune=yes"
namespace/test-prune created
namespace/test-prune-another created

$ kubectl apply -f one-namespace.yaml --prune-whitelist 'core/v1/Namespace' --prune -l "prune=yes"
namespace/test-prune unchanged
namespace/test-prune-another pruned

$ kubectl delete ns -l prune=yes
namespace "test-prune" deleted

$ kubectl apply --server-side -f two-namespace.yaml --prune-whitelist 'core/v1/Namespace' --prune -l "prune=yes"
namespace/test-prune serverside-applied
namespace/test-prune-another serverside-applied

$ kubectl apply --server-side -f one-namespace.yaml --prune-whitelist 'core/v1/Namespace' --prune -l "prune=yes"
namespace/test-prune serverside-applied
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.24.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
$ uname -a
Darwin hanazawa.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
The reason here is that `kubectl apply` with `--server-side` will not add the `kubectl.kubernetes.io/last-applied-configuration` annotation to the resource(in the example, the namespace).

>       --prune=false: Automatically delete resource objects, including the uninitialized ones, that
>       do not appear in the configs and are created by either apply or create --save-config. Should be used
>       with either -l or --all.

Then `--prune` will ignore it as the namespace are not with the `kubectl.kubernetes.io/last-applied-configuration` annotation. kubectl cannot know whether this resource is created or applied by kubectl.

**Comment by ardaguclu** [comment]
As @pacoxu stated, currently pruning is only supported for the resources created by client-side-apply. We either adds support for server-side-apply(as the referenced PR does) or we put a validation stating that we do not support `prune` flag for server side apply.

/triage accepted
