### ISSUE TITLE
Optimize scheduler's FitError

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#110871]
### What would you like to be added?

Scheduler's [FitError](https://github.com/kubernetes/kubernetes/blob/b2ed6ca64f55452cdb4063d62920dddccd4344f7/pkg/scheduler/framework/types.go#L223) wraps info to diagose a pod's scheduler failure. The object is dumped to system event, and also injected into a pod's status. However, the way FitError is currently dealt with is not efficient in the following aspects:

### 1. Unnecessary compose/decompose

When a FitError gets wrapped into a Status, it's achieved by:
- `framework.NewStatus(..., err.Error())`, or
- `framework.AsStatus(err)`

The first function decomposed the err, and composed [another](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/framework/interface.go#L246) error.
The second function, although injects the err into the Status, it calls [err.Error()](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/framework/interface.go#L255) which should be lazy-evaluted.

The optimization should try to reuse the same FitError as much as possible, and also delay its evaluation (i.e., call FitError.Error()).

### 2. Duplicated calls to FitError.Error()

Suppose we have solved the problems mentioned above, and hence have a unique FitError across one scheduling cycle, the current logic that calls `FitError.Error()` multiple times are still problematic. Currently it may be called ~4~ 3 times during a scheduling cycle:

- ~composing a PostFilter status ([A](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/framework/preemption/preemption.go#L173))~
- duplicated entries when dealing with the error ([B](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L813), [C](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L824), [D](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L830))

### Why is this needed?

`FitError.Error()` is not a trivial function, esp. in a large cluster or the failure reasons are diverse. We should eliminate unnecessary calls (explicit ones or implicit ones by klog) as much as possible.

**Comment by Huang-Wei** [comment]
/assign

cc @ahg-g @alculquicondor

**Comment by ahg-g** [comment]
> 
> ### 2. Duplicated calls to FitError.Error()
> Suppose we have solved the problems mentioned above, and hence have a unique FitError across one scheduling cycle, the current logic that calls `FitError.Error()` multiple times are still problematic. Currently it may be called 4 times during a scheduling cycle:
> 
> * composing a PostFilter status ([A](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/framework/preemption/preemption.go#L173))
> * duplicated entries when dealing with the error ([B](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L813), [C](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L824), [D](https://github.com/kubernetes/kubernetes/blob/5583f0c0659b4033869939ad4c8ee3bca156386b/pkg/scheduler/schedule_one.go#L830))
> 

I don't think the first and the second bullet would ever be called for the same FitError; as for B, C and D, B doesn't trigger composing the error, while C and B are called in the same function, so just create a local variable and get the message once for both

**Comment by Huang-Wei** [comment]
> I don't think the first and the second bullet would ever be called for the same FitError

You're right, I just realized that the PostFilter FitErrror is a standalone one. We just need to ensure its error evaluation happens just once.

> as for B, C and D, B doesn't trigger composing the error

B doesn't trigger composing but its evaluation (in [MakeDefaultErrorFunc()](https://github.com/kubernetes/kubernetes/blob/65361245edc10fea7ef9d30f03d0de24b8939da8/pkg/scheduler/scheduler.go#L360)) is explicit and cannot be resued with C and D.

> while C and B are called in the same function, so just create a local variable and get the message once for both

You meant C and D, right? If so, yes, but the explicit error evaluation in klog (B) is still a concern.

**Comment by ahg-g** [comment]
> B doesn't trigger composing but its evaluation (in [MakeDefaultErrorFunc()](https://github.com/kubernetes/kubernetes/blob/65361245edc10fea7ef9d30f03d0de24b8939da8/pkg/scheduler/scheduler.go#L360)) is explicit and cannot be resued with C and D.

Seems reasonable to move the event creation to the error function that `MakeDefaultErrorFunc` creates, we probably don't need `handleSchedulingFailure` to do anything extra, everything should be inside the error function, no?

>  klog (B) is still a concern.

we don't need to pass `err` there, we can use a string. Basically get the error string once and use it for the log message as well as for the event creation.

**Comment by Huang-Wei** [comment]
Thanks for the discussion in https://github.com/kubernetes/kubernetes/pull/110900#issuecomment-1176793033, which made me realize that the first problem is only **_hypothetically_** possible, so i closed #110900 to avoid unnecessary optimization.

And now we can just focus on the second problem.

**Comment by Huang-Wei** [comment]
> Seems reasonable to move the event creation to the error function that `MakeDefaultErrorFunc` creates, we probably don't need `handleSchedulingFailure` to do anything extra, everything should be inside the error function, no?

Sort of, it's just that would make `MakeDefaultErrorFunc` a bit "fat".

I'm thinking of eliminating the `Error func(*framework.QueuedPodInfo, error)` signature from `newScheduler()` b/c it's not a good abstraction. I guess it was originally designed to be simple, but it ends up with a closure that needs extra parameters to return another closure:

```go
MakeDefaultErrorFunc(client, podLister, podQueue, schedulerCache) func(*framework.QueuedPodInfo, error)
```

Thoughts?

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/kubernetes/issues/103853#issuecomment-889370324 :)
