### ISSUE TITLE
kubernetes-1.24.0 reproducible builds: kubelet binary varies

### ISSUE THREAD

**Issue by bmwiedemann** [kubernetes/kubernetes#110928]
### What happened?

While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our kubernetes1.24 package stopped to produce bit-identical results on 2 fresh builds.

```diff
--- strings RPMS.1/usr/bin/kubelet1.24
+++ strings RPMS.2/usr/bin/kubelet1.24
@@ -1,6 +1,6 @@
 /lib64/ld-linux-x86-64.so.2
-D/iB)
-YwVWBSSdZpPsrO9TM081/7CBb1fZOvPOFshzvo1cu/UKVjqzDsSfvmOjrwnpZv/UooIAWPloG5fXOlWD0oC
+rc{.
+tPfq4us5qtj6n5wGE3lh/7CBb1fZOvPOFshzvo1cu/UKVjqzDsSfvmOjrwnpZv/5Y18rAlngXbjuDxH_BT5
 _Z!#YH+
 o&43b
 =#jv
@@ -1456855,7 +1456855,7 @@
 /usr/lib64/go/1.18/src/net/tcpsockopt_unix.go
 /usr/lib64/go/1.18/src/net/udpsock_posix.go
 /usr/lib64/go/1.18/src/net/unixsock_posix.go
-/tmp/go-build1406627905/b050/_cgo_gotypes.go
+/tmp/go-build3558486601/b050/_cgo_gotypes.go
 /usr/lib64/go/1.18/src/net/cgo_resnew.go
 /usr/lib64/go/1.18/src/net/cgo_unix.go
 /usr/lib64/go/1.18/src/net/cgo_socknew.go
@@ -1457086,7 +1457086,7 @@
 vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
 /usr/lib64/go/1.18/src/os/user/lookup.go
 /usr/lib64/go/1.18/src/os/user/user.go
-/tmp/go-build1908184651/b122/_cgo_gotypes.go
+/tmp/go-build1410760062/b122/_cgo_gotypes.go
 /usr/lib64/go/1.18/src/os/user/cgo_lookup_unix.go
 vendor/k8s.io/klog/v2/exit.go
 vendor/k8s.io/klog/v2/klog.go
@@ -1460325,7 +1460325,7 @@
 vendor/github.com/google/cadvisor/utils/cpuload/cpuload.go
 vendor/github.com/docker/go-units/size.go
 vendor/github.com/docker/go-units/ulimit.go
-/tmp/go-build1382031104/b1017/_cgo_gotypes.go
+/tmp/go-build2774399619/b1017/_cgo_gotypes.go
 vendor/github.com/mindprince/gonvml/bindings.go
 vendor/github.com/google/cadvisor/accelerators/nvidia.go
 vendor/github.com/google/cadvisor/nvm/machine_no_libipmctl.go
```

The first chunk is likely just the hash of the remainder, so can be ignored.
The other chunks indicate that a random build temporary path is used for `_cgo_gotypes.go`

### What did you expect to happen?

Sources should be able to reproduce bit-identical binaries e.g. for SLSA level4

### How can we reproduce it (as minimally and precisely as possible)?

On Debian or openSUSE do
```bash
osc co openSUSE:Factory/kubernetes1.24 && cd $_
for i in 1 2 ; do
  osc build --clean --noservice --keep-pkg=RPMS.$i \
  --define='%source_date_epoch_from_changelog Y' \
  --define="%_buildhost reproducible" \
  --define='%clamp_mtime_to_source_date_epoch Y' \
  --define='%use_source_date_epoch_as_buildtime Y'
done
sha256sum RPMS.*/kubernetes1.24-kubelet-1*.rpm
```

### Kubernetes version

<details>

```console
$ kubectl version
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-05T00:00:00Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```

</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
```
NAME="openSUSE Tumbleweed"
# VERSION="20220701"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20220701"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20220701"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```
$ uname -a
Linux bmwiedemann-factory 5.18.6-1-default #1 SMP PREEMPT_DYNAMIC Thu Jun 23 05:46:18 UTC 2022 (5aa0763) x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
go1.18
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@bmwiedemann can you please post a link to the full logs from the build?

**Comment by dims** [comment]
@saschagrunert any news on this? Haven't heard from @bmwiedemann (context: we worked to fix this a couple of times in https://github.com/kubernetes/kubernetes/issues/70131)

**Comment by bmwiedemann** [comment]
It would be good if `/tmp/go-build$int` would not be embedded in the first place. It might be possible to replace it somehow in our builds, but all other people wanting reproducible builds, would need to replicate that.

**Comment by bmwiedemann** [comment]
@dims full logs from the build: https://rb.zq1.de/temp/kubernetes1.24-build-log.txt
from kubernetes-1.24.3 built 2022-08-18

**Comment by dims** [comment]
@bmwiedemann can you please try setting GOCACHE=off when you run the build?

I am suspecting that the temp directory is being generated here:
https://github.com/golang/go/blob/6d8ec893039a39f495c8139012e47754e4518b70/src/cmd/go/internal/cache/default.go#L77-L80

**Comment by bmwiedemann** [comment]
I added `export GOCACHE=off` to [our .spec file](https://code.opensuse.org/package/kubernetes1.24/blob/6bff88072d245b1e8574f2cf672e774cc7436f79/f/kubernetes1.24.spec#_187) but still got these diffs.

**Comment by dims** [comment]
So i built golang from source, peppered it with changes to track down where this is getting created and found that it is coming from:
https://github.com/golang/go/blob/c318f191e45e3496f8afe0a456337e9f76d7f7b4/src/cmd/go/internal/work/action.go#L268

I don't know yet how to fix it. will dig more when i can (travelling for the next few days)

**Comment by saschagrunert** [comment]
Would it work to override the `GOGCCFLAGS`, I see that they use the `-fdebug-prefix-map=/tmp/go-build823405942=/tmp/go-build`:

```
> go env GOGCCFLAGS
-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2616882006=/tmp/go-build -gno-record-gcc-switches
```

Ref: https://reproducible-builds.org/docs/build-path/

**Comment by dims** [comment]
this is so tricky @saschagrunert :( will dig more when i get back from my event this week

**Comment by xmudrii** [comment]
This is still relevant even with 1.27. It might be worth revisiting this issue again.
/reopen
/triage accepted

**Comment by dims** [comment]
latest run - https://rb.zq1.de/compare.factory-20230830/diffs/kubernetes1.27-compare.out

**Comment by bmwiedemann** [comment]
AIUI, the conclusion by the golang people seems to be that commit bf27cad2561f1dd3370ddc1c96a904526a2ec8b0 is not the right approach and one should use `-trimpath` with the go call instead.
Not sure how that interacts with other parts of your build.

**Comment by dims** [comment]
cc @thockin (please see referenced commit above!)

**Comment by thockin** [comment]
I see.  I inherited the gcflags before https://github.com/kubernetes/kubernetes/commit/bf27cad2561f1dd3370ddc1c96a904526a2ec8b0 so I plead innocence.

It seems plausible to change it from `-gcflags=all=-trimpath=<path>` to `-trimpath=<path>` - I don't know when I will have time to look at that, though.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/121894

**Comment by thockin** [comment]
My patch doesn't seem to fix the whole problem:

```
thockin-glaptop4 kubernetes f72e3d build_trimpath /$ make kubelet
+++ [1114 19:10:12] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubelet (non-static)
thockin-glaptop4 kubernetes f72e3d build_trimpath /$ md5sum _output/bin/kubelet 
3359a1b884f5591695ebc570178bfa32  _output/bin/kubelet
thockin-glaptop4 kubernetes f72e3d build_trimpath /$ make kubelet
+++ [1114 19:12:40] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubelet (non-static)
thockin-glaptop4 kubernetes f72e3d build_trimpath /$ md5sum _output/bin/kubelet 
f9f01d814ec6fb65d715fd6d94fba847  _output/bin/kubelet
thockin-glaptop4 kubernetes f72e3d build_trimpath /$

**Comment by thockin** [comment]
```diff
--- a	2023-11-14 19:13:45.441379064 -0800
+++ b	2023-11-14 19:13:56.145296244 -0800
@@ -1,4 +1,4 @@
-38rZH_dQckYF9EEzmndR/BAXOwzCcq0Mk1UHT62ha/QLiRg_XP4o_ojWh3oWP9/TWG7KW90IL8vKt1UOEPR
+LeLArvl7sgWAd55ROKN2/BAXOwzCcq0Mk1UHT62ha/QLiRg_XP4o_ojWh3oWP9/cYb5ZGQwa6js077YiAvK
 /lib64/ld-linux-x86-64.so.2
 AUATUSH
 []A\A]
@@ -1199511,8 +1199511,8 @@
 go1.21.3
 runtime/cgo: 
 call frame too large
-2023-11-15T03:12:40Z
-2023-11-15T03:12:40Z
+2023-11-15T03:13:47Z
+2023-11-15T03:13:47Z
 pthread_create failed: %s
 bad stack bounds: lo=%p hi=%p
 expand 32-byte kexpand 32-byte k

**Comment by bmwiedemann** [comment]
That seems unrelated. I tested with #121894 and it made our `kubernetes1.28` openSUSE package fully reproducible.

Your diff contains a timestamp - maybe `export SOURCE_DATE_EPOCH=12345` would get rid of that. The top part of the diff is just the go build-id hash of the remainder and can be ignored.

**Comment by bmwiedemann** [comment]
Will there be backports to 1.24++ ? I found it applies cleanly to 1.26++ and works with some small tweaks in 1.24 and 1.25.

If not, I'd submit the patch for our openSUSE packages.

**Comment by xmudrii** [comment]
@bmwiedemann 1.24 and 1.25 reached EOL and we don't support these branches any longer. We can cherry-pick this to 1.26+ if folks (@thockin @dims @liggitt) agree

**Comment by bmwiedemann** [comment]
Cherry-picks:
#122682 1.29
#122678 1.28
#122679 1.27
#122680 1.26
