### ISSUE TITLE
ContainerID not populated until Pod is in Ready state

### ISSUE THREAD

**Issue by faisal-memon** [kubernetes/kubernetes#110988]
### What happened?

Im working on this issue https://github.com/spiffe/spire/issues/3092 for SPIRE and Istio integration. The root cause of that issue is the `ContainerID` is not being populated while the Pod is initializing, but SPIRE needs the ContainerID to be populated to declare the Pod ready. 

### What did you expect to happen?

`ContainerID` to be populated while Pod is in initializing state.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy any Pod and dump the yaml. Until Pod is in Ready state ContainerID will not be populated.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4+k3s1", GitCommit:"bec170bc813e342cdba9710a1a71f8644c948770", GitTreeState:"clean", BuildDate:"2021-11-29T16:49:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/arm64"}```
</details>


### Cloud provider

<details>
Running locally on desktop but can happen in any environment
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
This is more related to sig node then.
/remove-sig scheduling
/sig node

**Comment by endocrimes** [comment]
/remove-kind bug
/kind feature

This doesn't seem like a bug (breaking a published facet of the kubelet api), but a feature improvement (changing the behavior of the kubelet api).

The Kubelet can't report a ContainerID before a container is running because it comes from the runtime. I'm not sure if there's an obvious change here really.

**Comment by faisal-memon** [comment]
> /remove-kind bug /kind feature
> 
> This doesn't seem like a bug (breaking a published facet of the kubelet api), but a feature improvement (changing the behavior of the kubelet api).
> 
> The Kubelet can't report a ContainerID before a container is running because it comes from the runtime. I'm not sure if there's an obvious change here really.

Hi @endocrimes thanks for taking a look. The container is running and the ContainerID is available, I can see it in /proc folder. The Pod is just not in Ready state. We are running into a problem where we need the ContainerID to be available in order to declare the Pod is Ready.

**Comment by endocrimes** [comment]
Unfortunately that doesn't align with the current behavior of the kubelet.

Clayton might have some ideas for the long term, but status lifecycle stuff isn't something we can change on a whim bc there are always inherent issues and a lot of risk when doing so.

/cc @smarterclayton

**Comment by faisal-memon** [comment]
> Unfortunately that doesn't align with the current behavior of the kubelet.
> 
> Clayton might have some ideas for the long term, but status lifecycle stuff isn't something we can change on a whim bc there are always inherent issues and a lot of risk when doing so.
> 
> /cc @smarterclayton

Just want to check in to see if you had any thoughts on this one? Is there a reason why the container id can only be populated after the Pod is in Ready state?

**Comment by faisal-memon** [comment]
Hi @smarterclayton, any thoughts on this one?

**Comment by evan2645** [comment]
thanks so much for your help thus far @endocrimes ❤️ 

> Clayton might have some ideas for the long term, but status lifecycle stuff isn't something we can change on a whim bc there are always inherent issues and a lot of risk when doing so.

Any chance you could help point us at the relevant parts of the codebase so we can better understand what's going on? That would be super helpful ... it's a bit difficult for me to navigate 😅
