### ISSUE TITLE
unable to build kubernetes objects from current release manifest: resource mapping not found

### ISSUE THREAD

**Issue by ravikiran-talluri** [kubernetes/kubernetes#110995]
### What happened?

We have cluster running k8s v1.21 and deployed Ingress objects with apiVersion **networking.k8s.io/v1beta1** ( deployed through helm) and all looks good
.
then we have upgraded to v1.22 and all looks good, seems nginx apiVersion got automatically upgraded to networking.k8s.io/v1. but when we are trying to deploy ingress object (again through HELM) with apiVersion **networking.k8s.io/v1** then we are seeing below error
```
Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "example" namespace: "" from "": no matches for kind "Ingress" in version "[networking.k8s.io/v1beta1](http://networking.k8s.io/v1beta1)"
ensure CRDs are installed first
```

### What did you expect to happen?

Upgrade should be completed successfully

### How can we reproduce it (as minimally and precisely as possible)?

On 1.21 k8s- deploy ingress object with apiVersion "networking.k8s.io/v1beta1" using HELM
Upgrade to 1.22 k8s
Deploy ingress object with apiVersion "networking.k8s.io/v1" using HELM

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-17T22:26:07Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8-gke.1300", GitCommit:"e7a92658548c9d57d936b8124064aef07f1fc53b", GitTreeState:"clean", BuildDate:"2022-04-01T09:40:07Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

EKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by harry1064** [comment]
Hi @ravikiran-talluri 
 can you try to deploy ingress object with `apiVersion networking.k8s.io/v1` using `kubectl apply -f` manually?

If yes,then  can you look at this [apiVersion networking.k8s.io/v1](https://github.com/helm/helm/issues/7361)? it might be helpful.

**Comment by Kartik494** [comment]
Hi @ravikiran-talluri you encountered this error even after installing respective CRD's?

**Comment by AmanteAdrian** [comment]
We are getting the same issue after upgrading to the latest Kubernetes version

**Comment by danports** [comment]
See https://github.com/helm/helm/issues/7219 for some shell scripts and other workarounds for this issue - it seems you either have to edit the Helm release history or delete and redeploy the Helm release.
