### ISSUE TITLE
Missing Port mutation tests 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#110918]
### What happened?

We recently found that, when tweaking service objects manually, the following bug can exist (in alternative kube proxy implementations) , but it's not caught in the sig-network e2es... 

- make a service
- Confirm that the service works
- Edit the service by adding a new port to it
- Confirm both ports work
- Delete the added port
- Confirm these still work 

We need to
1. audit what port mutation tests we currently do
2. see what is supported
3. add tests for the missing deltas

Breaks.  However, we pass it seems, most or all of the sig-network e2es.  I think we have a missing e2e test.

Im pretty sure we support port mutation, right?  If not plz close this.

### What did you expect to happen?

e2e tests for sig-network would have coverage for service proxying robustness after port addition/deletion 

### How can we reproduce it (as minimally and precisely as possible)?

Reproducer is above, we  only noticed this lack of test coverage b/c of a broken service proxy :) 

### Kubernetes version

main

### Cloud provider

any

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jayunit100** [comment]
am happy to pair with someone wanting to get starte on this, or @iXinqi  might be taking this on, and she can help delegate out work (there might be several tests to write, not sure yet)

**Comment by iXinqi** [comment]
Thanks @jayunit100, I'll work on this! Please assign this to me.

**Comment by iXinqi** [comment]
Hi @jayunit100, could you please take a look at ["should serve multiport endpoints from pods " test case](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L852)? It seems very similar to what we want to test in this issue.

**Comment by jayunit100** [comment]
that test adds / deleted endpoints , but what we really want is to actually *change* the service object, i.e. to rewrite the service type (it might start out as ClusterIp, then we change it to nodeport, and so on).    

Im not sure what the matrix of valid mutations are but, we can look together if you want sometime today

**Comment by iXinqi** [comment]
Thanks Jay, I see your point. I'll start a draft pr today and then we can pair and discuss about it based on my pr.
