### ISSUE TITLE
[kubelet] Ability to tweak resolution for metrics calculated by kubelet

### ISSUE THREAD

**Issue by mohitreddy1996** [kubernetes/kubernetes#110943]
### What would you like to be added?

It seems that 15s is the resolution of metrics calculated by kubelet - https://github.com/kubernetes-sigs/metrics-server/blob/master/FAQ.md#how-often-metrics-are-scraped

It would be great if this could be tweaked (configured lower than this).

### Why is this needed?

We rely on Horizontal Pod Autoscaler to autoscale our pods based on CPU and Memory utilization. Traffic sent to our pods is quite bursty and we noticed that for a short period of time, our services are quite overwhelmed (generally OOMing or seeing regressions) before HPA triggers a scaling event.

Looking at the architecture here - https://kubernetes.io/docs/tasks/debug/debug-cluster/resource-metrics-pipeline/, 
HPA seems to be tunable - https://github.com/zevarito/Kubernetes/blob/master/docs/design/horizontal-pod-autoscaler.md
Metric server seems to be tunable - https://github.com/kubernetes-sigs/metrics-server/blob/master/FAQ.md#how-often-metrics-are-scraped

Could not find such configuration for kubelet to sync/fetch metrics from cadvisor

**Comment by dilinade** [comment]
@mohitreddy1996 Any luck on this? Or any other alternative?
