### ISSUE TITLE
Should the AvailableConditionController support optional checks for Endpoints?

### ISSUE THREAD

**Issue by anurnomeru** [kubernetes/kubernetes#110906]
### What would you like to be added?

Whether to support choosing not to check Endpoints when registering AA, or support specify the backend Service other than ClusterIp, such as ExternalName?

### Why is this needed?

aggregation-layer supports endpointless routing, but in AvailableConditionController, you have to check if Endpoints are available, that is a bit of a contradiction in design.

In our use case, AA is not in the same cluster as ApiServer, we have to bypass AvaliableConditionController checks to make AA available.

https://kubernetes.io/docs/tasks/extend-kubernetes/configure-aggregation-layer/

```
If you are not running kube-proxy on a host running the API server, then you must make sure that the system is enabled with the following kube-apiserver flag:

--enable-aggregator-routing=true
```

**Comment by thockin** [comment]
I don't think this is sig-network, or if it is I do not understand what?

**Comment by aojea** [comment]
> AvaliableConditionController

what fo you mean by `AvaliableConditionController`?

**Comment by anurnomeru** [comment]
> > AvaliableConditionController
> 
> what fo you mean by `AvaliableConditionController`?

Sorry, it's a misspelling. Avaliable -> Available

**Comment by anurnomeru** [comment]
https://github.com/kubernetes/kubernetes/blob/b96a04df901c6facf0fe66b3c3c877eb8651e267/staging/src/k8s.io/kube-aggregator/pkg/controllers/status/available_controller.go#L322-L358

When register an AA, it will forcibly check its endpoints, But AA clearly supports routing directly through service.

**Comment by aojea** [comment]
Last time I've checked this controller, it doesn't handle well asymmetric conditions, i.e. you have 3 apiservers and one of them doesn't reach the Endpoints but the others do, and they keep updating the APIStatus with the different conditions, flapping  ... you can not have a single state of the network from 3 different network endpoints 

Is this causing any real issue?

**Comment by anurnomeru** [comment]
> Last time I've checked this controller, it doesn't handle well asymmetric conditions, i.e. you have 3 apiservers and one of them doesn't reach the Endpoints but the others do, and they keep updating the APIStatus with the different conditions, flapping ... you can not have a single state of the network from 3 different network endpoints
> 
> Is this causing any real issue?

Our case here is relatively simple. In our case, Endpoints does not need to be really available, because the Aggregation Apiserver and Apiserver are not in the same cluster. We directly route to the Aggregation Apiserver of another cluster through Service. When Apiserver requests the Service of AA, it will be forwarded to AA of another K8s cluster.
