### ISSUE TITLE
when we use function ValidateResourceQuantityValue to validate ExtendedResource value，we find value.MilliValue() has bug

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#110903]
### What happened?

When we create  resourceQuota，it will use Function ValidateResourceQuantityValue to validate resource vaule，for ExtendedResource，the value must be integer，the  Function ValidateResourceQuantityValue will use value.MilliValue()%int64(1000) != int64(0) to judge wthether the value is integer, but now i test that value.MilliValue has bug,i test many data，like below：

for ExtendedResource：local3.org.storageclass.storage.k8s.io/requests.storage，i set many value：

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-mj
  namespace: mj
spec:
  hard:
    hugepages-1Gi: 1Ei
    hugepages-2Mi: 1Ei
    limits.memory: 1Ei
    local3.org.storageclass.storage.k8s.io/requests.storage: 1Ei
    requests.cpu: 1Ei
    requests.memory: 1Ei
    requests.nvidia.com/gpu: 1Ei

set：1Ei，value.MilliValue: -9223372036854775808
I0701 11:35:24.275563       1 validation.go:5664] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value: {{0 0} {0xc00be18d20}  BinarySI}
I0701 11:35:24.275602       1 validation.go:5665] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue: -9223372036854775808
I0701 11:35:24.275610       1 validation.go:5666] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue()%!i(func() int64=0x372aa20)nt64(1000): -808

set：3Ei，value.MilliValue: -9223372036854775808
I0701 11:37:40.661563       1 validation.go:5664] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value: {{0 0} {0xc00f229020}  BinarySI}
I0701 11:37:40.661592       1 validation.go:5665] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue: -9223372036854775808
I0701 11:37:40.661599       1 validation.go:5666] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue()%!i(func() int64=0x372aa20)nt64(1000): -808

set：2Ei，value.MilliValue: 0
I0701 11:39:08.127100       1 validation.go:5664] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value: {{0 0} {0xc005070f60}  BinarySI}
I0701 11:39:08.127142       1 validation.go:5665] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue: 0
I0701 11:39:08.127150       1 validation.go:5666] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue()%!i(func() int64=0x372aa20)nt64(1000): 0

set：4Mi，value.MilliValue: 4194304000
I0701 13:58:01.160420       1 validation.go:5664] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value: {{4194304 0} {<nil>} 4Mi BinarySI}
I0701 13:58:01.160453       1 validation.go:5665] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue: 4194304000
I0701 13:58:01.160461       1 validation.go:5666] IntegerResource 'local3.org.storageclass.storage.k8s.io/requests.storage', value.MilliValue()%!i(func() int64=0x372aa20)nt64(1000): 0

### What did you expect to happen?

when we use  value.MilliValue， it has Expected result .

### How can we reproduce it (as minimally and precisely as possible)?

use my yaml file to create resource quota
set  local3.org.storageclass.storage.k8s.io/requests.storage to 1Ei，2Ei 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resourcequota-mj
  namespace: mj
spec:
  hard:
    hugepages-1Gi: 1Ei
    hugepages-2Mi: 1Ei
    limits.memory: 1Ei
    local3.org.storageclass.storage.k8s.io/requests.storage: 1Ei
    requests.cpu: 1Ei
    requests.memory: 1Ei
    requests.nvidia.com/gpu: 1Ei

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2022-04-14T08:48:54Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2022-07-01T03:27:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mysunshine92** [comment]
@pacoxu now value.MilliValue() has bug?

**Comment by mysunshine92** [comment]
> /sig api-machinery
> 
> ```
> // <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei
> //   (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)
> // <decimalSI>       ::= m | "" | k | M | G | T | P | E
> //   (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)
> // <decimalExponent> ::= "e" <signedNumber> | "E" <signedNumber>
> ```
> 
> See [#102134 (comment)](https://github.com/kubernetes/kubernetes/issues/102134#issuecomment-844696891), #102134 and #49442 is similar.
> 
> ExtendedResource will be treated as decimalSI, not binarySI?

**Comment by leilajal** [comment]
@pacoxu are you planning to work on this? thanks!
/triage accepted

**Comment by mysunshine92** [comment]
> I still not sure if this is a bug.
> 
> ```
> 		{1024 * 1024 * 1024 * 1024 * 1024 * 1024, BinarySI, "1Ei"},
> 		{1000 * 1000 * 1000 * 1000 * 1000 * 1000, DecimalSI, "1E"},
> ```
> 
> The resource quota should be
> 
> ```
> apiVersion: v1
> kind: ResourceQuota
> metadata:
>   name: resourcequota-mj
>   namespace: mj
> spec:
>   hard:
>     hugepages-1Gi: 1Ei
>     hugepages-2Mi: 1Ei
>     limits.memory: 1Ei
>     local3.org.storageclass.storage.k8s.io/requests.storage: 1E
>     requests.cpu: 1E
>     requests.memory: 1Ei
>     requests.nvidia.com/gpu: 1E
> ```

ExtendedResource will be treated as decimalSI, not binarySI，Where is this restriction? i can not find any document?
