### ISSUE TITLE
RoleBinding to Not Existing ClusterRole

### ISSUE THREAD

**Issue by pavelmaliy** [kubernetes/kubernetes#110989]
### What happened?

User created role-binding to non existing clusterRole called "secrets-reader".
Later on operator created such clusterrole with the same name and  suddenly unexpected users can read secrets in their namespace. 

Users with role allowing to create rolebinding, can try and guess future roles/clusterroles names and  escalate permissions.

### What did you expect to happen?

Role Binding to not existing role should be blocked in order to [prevent permission escalation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#privilege-escalation-prevention-and-bootstrapping)

### How can we reproduce it (as minimally and precisely as possible)?

crate rolebinding to non existing clusterrole
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
subjects:
- kind: User
  name: jane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
apiGroup: rbac.authorization.k8s.io
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

### Relevant SIG(s)

/sig auth

**Comment by wongearl** [comment]
When creating a RoleBinding should check if the relevant role exists?

**Comment by pavelmaliy** [comment]
@wongearl yes, I would expect that the platform will do it for me.

**Comment by pavelmaliy** [comment]
any update?

**Comment by ngau66** [comment]
> @wongearl yes, I would expect that the platform will do it for me.

I do think so. It take a long time to check the role in my program.

**Comment by liggitt** [comment]
> Role Binding to not existing role should be blocked

This is working as intended, so that resources can be created in any order.

> Users with role allowing to create rolebinding, can try and guess future roles/clusterroles names and escalate permissions.

Binding to an unresolveable role/clusterrole requires superuser access, so there's no escalation risk here.
