### ISSUE TITLE
GenerateSelfSignedCertKeyWithFixtures private keys permissions

### ISSUE THREAD

**Issue by setharnold** [kubernetes/kubernetes#110992]
Hello, the SRC folks asked that I file this publicly:

In the client-go repo, util/cert/cert.go , function
`GenerateSelfSignedCertKeyWithFixtures()` creates a private key and stores
it into a file with mode `0644`:

https://github.com/kubernetes/client-go/blob/acab036eff5706db06b4eb79253165cf4be0d9c5/util/cert/cert.go#L184

```
        // Generate key
        keyBuffer := bytes.Buffer{}
        if err := pem.Encode(&keyBuffer, &pem.Block{Type: keyutil.RSAPrivateKeyBlockType, Bytes: x509.MarshalPKCS1PrivateKey(priv)}); err != nil {
                return nil, nil, err
        }
         
        if len(fixtureDirectory) > 0 {
                if err := ioutil.WriteFile(certFixturePath, certBuffer.Bytes(), 0644); err != nil {
                        return nil, nil, fmt.Errorf("failed to write cert fixture to %s: %v", certFixturePath, err)
                }
                if err := ioutil.WriteFile(keyFixturePath, keyBuffer.Bytes(), 0644); err != nil {
                        return nil, nil, fmt.Errorf("failed to write key fixture to %s: %v", certFixturePath, err)
                }
        }
```

Typically keys are created with more restrictive modes to prevent other
users or services on the system from being able to copy them before the
user fixes the permissions.

Of course, if a more restrictive umask is in place, this may not be a big
deal, but it's an extremely fickle piece of the environment to rely upon
for security. It's better to be explicit.

Thanks

**Comment by tallclair** [comment]
/kind bug

Not sure if this is
/sig api-machinery
or
/sig auth

**Comment by leilajal** [comment]
@roycaihw is this related to us?

**Comment by mk46** [comment]
Hi @tallclair, 
IMO, mode `0600`  make sense for the key file. 
I would like to work on this, waiting for `triage/accepted` 
Thanks!!

**Comment by enj** [comment]
/lifecycle frozen
/good-first-issue

I think changing the code to use `0600` should be fine.  Anyone is free to pick this up.  Would be good to include a unit test.

**Comment by manali1205** [comment]
/ assign

**Comment by manali1205** [comment]
Hello, this is my first ever open source contribution. I am trying to understand and get this fixed. Any suggestions would be helpful!
