### ISSUE TITLE
Error from server (NotFound): the server could not find the requested resource 

### ISSUE THREAD

**Issue by wanghao123123** [kubernetes/kubernetes#110942]
### What would you like to be added?

I used kubeadm to build the cluster, but both of my nodes' eth0 was 192.168.0.8 and the cloud vendor said that the address could not be modified. Finally, I successfully built the cluster using the public network ip and built the network using flannel. The NetWork in net-conf.json corresponds to the cluster-pod-network-cidr, but I made an error when querying the pod log. All my pod are running and can provide services normally.

### Why is this needed?

Error from server (NotFound): the server could not find the requested resource ( pods/log loki-0)

**Comment by neolit123** [comment]
Please try asking on the support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
