### ISSUE TITLE
Why is the netns file in the /var/run/docker/netns/* not deleted after the container has been deleted in kubernetes?

### ISSUE THREAD

**Issue by Duanzhiwei** [kubernetes/kubernetes#110938]
### What happened?

In my kubernetes cluster, there is only one non-hostnetwork container on the work node, but there are many files under the /var/run/docker/netns/* directory, which cannot be accessed by the nsenter command.

### What did you expect to happen?

May be not counting the default netns, the number of files in the /var/run/docker/netns/* directory is the same as the number of pause containers.

### How can we reproduce it (as minimally and precisely as possible)?

Don't know how it happened

### Anything else we need to know?

lsns -t net 
![image](https://user-images.githubusercontent.com/28282292/177103100-a0dbabeb-6520-4e42-b5c3-f5bea6b9c823.png)
the running pod
![image](https://user-images.githubusercontent.com/28282292/177103161-c2b9bdc5-3129-4d41-8793-bfc940cfa5dd.png)
/var/run/docker/netns/ directory
![image](https://user-images.githubusercontent.com/28282292/177103265-ff2e45ac-f9ec-42a2-b115-539c8a7aa18e.png)

### Kubernetes version

<details>

```console
$ kubectl version
 k8s version 1.20.2
![image](https://user-images.githubusercontent.com/28282292/177103402-80672003-6fa9-4d6f-8454-455c13eaf066.png)

```

</details>

### Cloud provider

<details>
underlay bare metal native k8s
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Centos Linux Release 7.9.2009(core)

$ uname -a
3.10.0-1160.e17.x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
runc version: 1.0.0-rc95
docker version
![image](https://user-images.githubusercontent.com/28282292/177103639-8ca1d22e-4fcc-49c8-ab38-750c643a08bf.png)

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI : macvlan
</details>

**Comment by Duanzhiwei** [comment]
> @Duanzhiwei: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.

sig/network

**Comment by Duanzhiwei** [comment]
> @Duanzhiwei: This issue is currently awaiting triage.
> 
> If a SIG or subproject determines this is a relevant issue, they will accept it by applying the `triage/accepted` label and provide further guidance.
> 
> The `triage/accepted` label can be added by org members by writing `/triage accepted` in a comment.

sig/k8s-infra

**Comment by pacoxu** [comment]
/sig node network

There are some ip leak issues in https://github.com/kubernetes/kubernetes/issues/107371 https://github.com/kubernetes/kubernetes/issues/86944 https://github.com/containerd/containerd/issues/5768.
I can be cni plugin problem can maybe runtime problem.

**Comment by Duanzhiwei** [comment]
The ip of netns has been recycled. The netns has been unmounted, but the netns file has not been deleted. May be it's runtime problem

**Comment by aojea** [comment]
Dockershim has been deprecated, it's not likely someone is going to work on this

**Comment by Duanzhiwei** [comment]
Anyone else know about this?

**Comment by Duanzhiwei** [comment]
> @Duanzhiwei what do you get when you run `mount` and are any of those files from /var/run/docker/netns listed in mount?
> 
> If they are, then they are bind-mounted network namespaces and the thing that mounted them is responsible for cleaning them up. Let's start with the `mount` output though.

When running the mount, there are some /run/docker/netns/ files in the mount list, but not all /run/docker/netns/ files are in the mount list. I guess that the uoumt command was executed when docker deleted the container, but for some reason, these files were not deleted, resulting in these files remaining on the host and not being deleted.

**Comment by Duanzhiwei** [comment]
> @Duanzhiwei what do you get when you run `mount` and are any of those files from /var/run/docker/netns listed in mount?
> 
> If they are, then they are bind-mounted network namespaces and the thing that mounted them is responsible for cleaning them up. Let's start with the `mount` output though.

When running the mount, there are some /run/docker/netns/ files in the mount list, but not all /run/docker/netns/ files are in the mount list. I guess that the uoumt command was executed when docker deleted the container, but for some reason, these files were not deleted, resulting in these files remaining on the host and not being deleted.

**Comment by dcbw** [comment]
Kubernetes does not manage the network namespace mounts in /var/run/docker/netns; best to do is follow up with Docker I think. When you do, could you mention this issue in the docker issue you file?
