### ISSUE TITLE
hack/ginkgo-e2e.sh fails after upgrading to ginkgo v2

### ISSUE THREAD

**Issue by nilo19** [kubernetes/kubernetes#111040]
### Which jobs are failing?

After https://github.com/kubernetes/kubernetes/pull/109111 was merged, `hack/ginkgo-e2e.sh` fails because of:

I0708 07:50:08.498104 93818 e2e.go:116] Starting e2e run "99821dc1-5e1d-48c9-8be4-303d1ba74adb" on Ginkgo node 1
Ginkgo detected configuration issues:
Use of go test -parallel
Go test's implementation of parallelization does not actually parallelize
Ginkgo specs. Please use the ginkgo cli and ginkgo -p or ginkgo -procs=N
instead.

Did I miss some configs or it is a regression?

### Which tests are failing?

hack/ginkgo-e2e.sh

### Since when has it been failing?

After https://github.com/kubernetes/kubernetes/pull/109111 was merged.

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cloud-provider-azure/1991/pull-cloud-provider-azure-e2e-capz/1545557471236460544

### Reason for failure (if possible)

I0708 07:50:08.498104 93818 e2e.go:116] Starting e2e run "99821dc1-5e1d-48c9-8be4-303d1ba74adb" on Ginkgo node 1
Ginkgo detected configuration issues:
Use of go test -parallel
Go test's implementation of parallelization does not actually parallelize
Ginkgo specs. Please use the ginkgo cli and ginkgo -p or ginkgo -procs=N
instead.

### Anything else we need to know?

cc @chendave 

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
the error mentions `go test` but the `hack/ginkgo-e2e.sh` script seems to run `ginkgo` directly :thinking:

**Comment by nilo19** [comment]
In our code we just call ginkgo-e2e.sh directly. https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/test_k8s_e2e_capz.sh#L52

**Comment by chendave** [comment]
> Use of go test -parallel

This was checked in Ginkgo, https://github.com/onsi/ginkgo/blob/master/types/errors.go#L524-L525

I am not familiar with the test framework of that project (cloud-provider-azure), I did a quick search, and found the script `hack/run-e2e-tests.sh` called `go test` directly, pls see [code](https://github.com/kubernetes-sigs/cloud-provider-azure/blob/master/hack/run-e2e-tests.sh), can you pls check how this script got called, and is there a `parallel` flag passed to that script?

**Comment by chendave** [comment]
okay, I managed to reproduce the problem, 
```
/usr/bin/e2e.test -ginkgo.focus="\[sig-network\] ClusterDns \[Feature:Example\] should create pod that uses dns" -test.parallel=30 -report-dir=/var/log/kubernetes/e2e
Jul 11 11:14:32.809: INFO: The --provider flag is not set. Continuing as if --provider=skeleton had been used.
I0711 11:14:32.809811    5754 e2e.go:118] Starting e2e run "0cba6b71-ad52-4b38-a979-6a873a8964de" on Ginkgo node 1
Ginkgo detected configuration issues:
Use of go test -parallel
  Go test's implementation of parallelization does not actually parallelize
  Ginkgo specs.  Please use the ginkgo cli and `ginkgo -p` or `ginkgo -procs=N`
  instead.
```

pls don't use that parameter,  `--test.parallel=30`
```https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cloud-provider-azure/cloud-provider-azure-config.yaml#L182
```

And switch to the parameter provided by `Ginkgo`.

**Comment by chendave** [comment]
And as it said, you can make it by `ginkgo -p` or `ginkgo -procs=N`, this should be a restriction  introduced by `Ginkgo v2`.

@pohly  I think we should add this to the `action` list on to https://github.com/kubernetes/kubernetes/pull/109111.
