### ISSUE TITLE
[Flake] pull-kubernetes-e2e-kind timeouts and flake

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#111086]
### Which jobs are flaking?

pull-kubernetes-e2e-kind

### Which tests are flaking?

[sig-storage] CSI .*

### Since when has it been flaking?

It seems that happens since 7/8 
https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&job=pull-kubernetes-e2e-kind

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&graph-metrics=test-duration-minutes

### Reason for failure (if possible)

The test timeout 

```
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 1h0m0s timeout","severity":"error","time":"2022-07-12T02:09:15Z"}
wrapper.sh] [EARLY EXIT] Interrupted, entering handler ...
+ wrapper.sh] [CLEANUP] Cleaning up after Docker in Docker ...
signal_handler
```

the docker daemon is killed, but the `e2e.test` process keeps running, but it fails to do anything because all the `docker` features are missing, in this case, the port forwarding from the host to the apiserver container, as we can see in the following log entry

```
    Jul 12 02:09:16.895: FAIL: All nodes should be ready after test, Get "https://127.0.0.1:33619/api/v1/nodes": dial tcp 127.0.0.1:33619: connect: connection refused
```

As consequence, all `kind` commands fail, like the ones that gather the logs or clean up the environment

```
Deleting cluster "kind" ...
ERROR: failed to delete cluster "kind": error listing nodes: failed to list nodes: command "docker ps -a --filter label=io.x-k8s.kind.cluster=kind --format '{{.Names}}'" failed with error: exit status 1

Command Output: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### Anything else we need to know?

The sig storage test take more than 10 minutes

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind&graph-metrics=test-duration-minutes

we shouldn't have test with that duration on presubmit, those also should be tagged as slow

The trigger may be related to the ginkgo v2 update, the failures start to happen the same day that merged

![image](https://user-images.githubusercontent.com/6450081/180002875-53a9ab48-f939-4ebb-ac1b-7137d804ae15.png)

![image](https://user-images.githubusercontent.com/6450081/180002902-83a6a9d2-56c3-4c64-b21e-4fba5203f288.png)

### Relevant SIG(s)

/sig testing
/sig storage

**Comment by aojea** [comment]
/assign @msau42 
/cc @dims @liggitt 

I know this people is in vacation, ccing just for visibility
/cc @BenTheElder @pohly

**Comment by aojea** [comment]
I don't know if correlation implies causality here, but it seems to start the day that the ginkgov2 was merged 
/cc @chendave 
https://github.com/kubernetes/kubernetes/pull/109111

@onsi is there any change in behavior for which the tests keep running, I remember some discussion about this between you and @pohly about the failure modes

**Comment by onsi** [comment]
hey there @aojea correlation doesn't necessarily imply causation - but it's definitely the first place to start looking ;)

there shouldn't be any explicit changes in V2's behavior here however there were changes around how Ginkgo captures stdout/stderr during parallel test runs (i.e. when running with  `ginkgo -p`) that, in some circumstances involving external processes that hang, can cause `ginkgo` to hang.  Often when this happens Ginkgo catches it and prints out a message but I assume you haven't seen anything like that?

Here's something to try:

If:
(a) these specs are running in parallel
(b) the failure is somewhat reproducible

Then:
 try running with `ginkgo --output-interceptor-mode=none <...all your current flags...>`
to see if the flaky failure is resolved.  If the test consistently exits without hanging with this flag on then that would point to this output-interception issue and potentially help us figure out the next step for debugging things.

This sort of failure would also happen in Ginkgo v1 but it would be intermittent. V2 has a much cleaner implementation of output interception which has the side-effect of making this sort of failure more consistent.  usually the issue ends up being with a spawned process holding on to an open pipe or failing to clean up somehow....

...but it can be a gnarly thing to debug :(

**Comment by aojea** [comment]
it seems that the CSI tests are taking into account the time to delete the namespace, per example

>    <testcase name="[It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (filesystem volmode)] volumeMode should not mount / map unused volumes in a pod [LinuxOnly]" classname="Kubernetes e2e suite" status="passed" time="663.462445729">

takes 10 mins, starts at `2022-07-18T05:32:11.074813079Z`

and takes 5 mins deleting the namespace 

```
;2022-07-18T05:33:13.226917026Z&#xA;&amp;{Text:Waiting for namespaces [volumemode-7469] to vanish Duration:0s}&#xA;--&#xA;By Step&#xA;test/e2e/storage/drivers/csi.go:1001&#xA;2022-07-18T05:38:13.274347788Z&
```

 it feels like this is related on how CSI tests are structured, @chendave made some comments about this here https://github.com/kubernetes/kubernetes/pull/111063

**Comment by aojea** [comment]
> Is there a change in cleanup behavior to cause these tests to start timing out?

Yeah, it seems to be related to the ginkgo v2 migration, there were some behaviour changes ... I'm just trying to get some help because I couldn't find the problem and I am lost on those CSI e2e test logic

**Comment by onsi** [comment]
i put this in the sig-testing slack but in case it's relevant here:

one thing to note is that in ginkgo v1 the —timeout flag used to apply to each suite separately.  So if you are running 3 suites with a timeout of 50 minutes each suite gets 50 minutes.

In v2 the timeout governs the entire test run - that means all 3 suites must finish within 50 minutes.  not sure if that is in play here (are there multiple suites running?)

**Comment by aojea** [comment]
let's try this theory https://github.com/kubernetes/kubernetes/pull/111240#issuecomment-1188674386

**Comment by aojea** [comment]
@gnufied @msau42 can you please take on the slow tests from sig-storage that are running on presubmits?
I can do it but I'm afraid of breaking something, you can see them here https://github.com/kubernetes/kubernetes/issues/111247

```
359.837809497 [It] [sig-storage] CSI mock volume storage capacity exhausted, late binding, with topology
368.374086148 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (late-binding)] ephemeral should support multiple inline ephemeral volumes
604.450233253 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs)] volumeLimits should verify that all csinodes have volume limits
615.087845061 [It] [sig-storage] CSI mock volume CSIStorageCapacity CSIStorageCapacity used, insufficient capacity
617.794350588 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] volumeMode should not mount / map unused volumes in a pod [LinuxOnly]
619.783741958 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should be able to unmount after the subpath directory is deleted [LinuxOnly]
623.408809647 [It] [sig-storage] CSI mock volume CSI workload information using mock driver should not be passed when podInfoOnMount=nil
624.450690069 [It] [sig-storage] CSI mock volume CSIServiceAccountToken token should be plumbed down when csiServiceAccountTokenEnabled=true
625.444310546 [It] [sig-storage] CSI mock volume CSI attach test using mock driver should require VolumeAttach for drivers with attachment
627.903508956 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (filesystem volmode)] volumeMode should not mount / map unused volumes in a pod [LinuxOnly]
632.038397119 [It] [sig-storage] CSI mock volume CSI workload information using mock driver should not be passed when CSIDriver does not exist
632.428357297 [It] [sig-storage] CSI mock volume CSIStorageCapacity CSIStorageCapacity disabled
637.460625711 [It] [sig-storage] CSI mock volume CSI attach test using mock driver should require VolumeAttach for ephemermal volume and drivers with attachment
638.483551518 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: CSI Ephemeral-volume (default fs)] ephemeral should create read/write inline ephemeral volume
638.663552122 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] volumes should store data
640.515013342 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: CSI Ephemeral-volume (default fs)] ephemeral should support multiple inline ephemeral volumes
641.450176267 [It] [sig-storage] CSI mock volume CSIServiceAccountToken token should not be plumbed down when csiServiceAccountTokenEnabled=false
641.913133413 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)] volume-expand should not allow expansion of pvcs without AllowVolumeExpansion property
642.527114125 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (late-binding)] ephemeral should create read/write inline ephemeral volume
648.507931078 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (block volmode) (late-binding)] ephemeral should support multiple inline ephemeral volumes
648.648777999 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (default fs) (late-binding)] ephemeral should create read-only inline ephemeral volume
648.802427579 [It] [sig-storage] CSI mock volume CSI FSGroupPolicy [LinuxOnly] should modify fsGroup if fsGroupPolicy=default
649.951640528 [It] [sig-storage] CSI mock volume CSI workload information using mock driver should be passed when podInfoOnMount=true
655.89439547 [It] [sig-storage] CSI mock volume CSI Volume expansion should expand volume by restarting pod if attach=off, nodeExpansion=on
661.369189252 [It] [sig-storage] CSI mock volume CSI FSGroupPolicy [LinuxOnly] should modify fsGroup if fsGroupPolicy=File
665.617247469 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand Verify if offline PVC expansion works
665.657157335 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand Verify if offline PVC expansion works
681.66746715 [It] [sig-storage] CSI mock volume Delegate FSGroup to CSI driver [LinuxOnly] should not pass FSGroup to CSI driver if it is set in pod and driver supports VOLUME_MOUNT_GROUP
681.570379983 [It] [sig-storage] CSI mock volume CSI online volume expansion should expand volume without restarting pod if attach=off, nodeExpansion=on
703.494117676 [It] [sig-storage] CSI mock volume CSI online volume expansion should expand volume without restarting pod if attach=on, nodeExpansion=on
710.651000005 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Generic Ephemeral-volume (block volmode) (late-binding)] ephemeral should support two pods which have the same volume definition
723.469167712 [It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)(allowExpansion)] volume-expand should resize volume when PVC is edited while pod is using it
782.713964697 [It] [sig-storage] CSI mock volume CSI Volume expansion should not expand volume if resizingOnDriver=off, resizingOnSC=on
```

**Comment by aojea** [comment]
This seems to have improved
https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&job=pull-kubernetes-e2e-kind

**Comment by aojea** [comment]
nope, it didn't improve, it may be an artifact of not having many PR or low load on the CI, who knows

https://prow.k8s.io/?repo=kubernetes%2Fkubernetes&type=presubmit&job=pull-kubernetes-e2e-kind
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111091/pull-kubernetes-e2e-kind/1549382681064640512

**Comment by onsi** [comment]
hey @aojea -- looking at just that last run I'm seeing:

13:18  is the first timestamp I see.

Eventually (~around 13:35) the specs start running.

Everything is happy and several hundred specs run in parallel and pass.  The last three specs then fail - these three are running in parallel.


The first spec is:

`[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block volmode)(allowExpansion)] volume-expand [AfterEach] should resize volume when PVC is edited while pod is using it
test/e2e/storage/testsuites/volume_expand.go:252`

and has an error trying to delete the test namespace:

```
STEP: deleting the test namespace: volume-expand-8232 07/19/22 14:10:03.627
STEP: Waiting for namespaces [volume-expand-8232] to vanish 07/19/22 14:10:03.653
Jul 19 14:15:03.746: INFO: error deleting namespace volume-expand-8232: timed out waiting for the condition
```

The [line of code that attempts this delete](https://github.com/kubernetes/kubernetes/blob/3992eda8e61725c470fb6141a7fe4e7f9ee31ea5/test/e2e/storage/drivers/csi.go#L998) seems to wrap it in a try and so this timeout/failure doesn't mark the spec as failed.  The storage specific cleanup keeps running...

This stuff:

```
STEP: uninstalling csi csi-hostpath driver 07/19/22 14:15:03.746
```

appears to succeed - but then this step:

```
STEP: deleting the driver namespace: volume-expand-8232-9082 07/19/22 14:15:04.24
STEP: Waiting for namespaces [volume-expand-8232-9082] to vanish 07/19/22 14:15:04.245
```
seems to hang.  Eventually, at 14:18:32 I see:

> `{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 1h0m0s timeout","severity":"error","time":"2022-07-19T14:18:32Z"}`

and the first spec now reports the following error:

```
Jul 19 14:18:34.247: INFO: error deleting namespace volume-expand-8232-9082: Get "https://127.0.0.1:44063/api/v1/namespaces": dial tcp 127.0.0.1:44063: connect: connection refused
```

Presumably after three minutes of polling the namespace hasn't been removed.  But now that the outer container/infrastructure has timed out the tcp connection attempting to continue polling fails.  It looks like that 1 hour timeout is governed by the test setup, nto the Ginkgo test suite.

With the container/infrasturcture gone, the spec reports the error "`failed to list events in namespaces "volume-expand-8232"`".

but this too is wrapped in a try.  The spec finally fails in the `framework.go` `AfterEach` with:

```
Jul 19 14:18:34.247: FAIL: All nodes should be ready after test, Get "https://127.0.0.1:44063/api/v1/nodes": dial tcp 127.0.0.1:44063: connect: connection refused
```

again, because the container/infrasturcture was killed at 14:18:32.  This failure now bubbles up as the failure associated with the spec.

But in reality the underlying issue seems to be a failure to delete the `volume-expand-8232` namespace.

The second spec is:

`[sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: CSI Ephemeral-volume (default fs)] ephemeral [AfterEach] should create read-only inline ephemeral volume
      test/e2e/storage/testsuites/ephemeral.go:175`

Here too we see:

```
STEP: Waiting for namespaces [ephemeral-4035] to vanish 07/19/22 14:08:43.898
Jul 19 14:13:43.995: INFO: error deleting namespace ephemeral-4035: timed out waiting for the condition
```

^ this appears to be the actual failure.  Eventually the `AfterEach` reports a `connection refused` failure at 14:18 after the container/infrastructure times out.

Finally, the third spec is:

`[sig-storage] CSI mock volume [AfterEach] Delegate FSGroup to CSI driver [LinuxOnly] should not pass FSGroup to CSI driver if it is set in pod and driver supports VOLUME_MOUNT_GROUP
    test/e2e/storage/csi_mock_volume.go:1735`

here, once again, we see

```
STEP: deleting the test namespace: csi-mock-volumes-3290 07/19/22 14:08:56.313
STEP: Waiting for namespaces [csi-mock-volumes-3290] to vanish 07/19/22 14:08:56.318
Jul 19 14:13:56.420: INFO: error deleting namespace csi-mock-volumes-3290: timed out waiting for the condition
```

^ this appears to be the actual failure.  As with the other specs, eventually the `AfterEach` reports a `connection refused` failure at 14:18 after the container/infrastructure times out.

---

So, it looks like _something_ happens around 14:08 that puts the cluster in a bad state and these volume-related namespaces time out trying to delete.  This pushes the run time for the entire suite (including the setup bits before Ginkgo runs) past the 1 hour limit imposed by the container/infrastructure layer.

I'm not sure this is a V1 vs V2 issue (perhaps some previously implicit behavior aroudn test ordering has changed - but these parallel specs basically run the same way in V1 as in V2).  Have there been any changes to the storage stuff introduced around the same time as the V2 upgrade?  Perhaps this is an infrastructure resource/exhaustion issue - 700 specs managed to succeed before these last three failed!

**Comment by aojea** [comment]
I don't know if the custom cleanup and the aftereach are conflicting and hanging

https://github.com/kubernetes/kubernetes/blob/a3f777603be3655a17d75acf5ee4216879e08aeb/test/e2e/storage/drivers/csi.go#L986-L1015

**Comment by onsi** [comment]
no, i don't believe so.  they are running sequentially for a given spec.

**Comment by aojea** [comment]
> no, i don't believe so. they are running sequentially for a given spec.

we do some crazy things, https://github.com/kubernetes/kubernetes/pull/20771 :smile: 

We need to minimize the diff to find out the root cause, and we can't have the presubmit jobs with a 45% success rate, I've reverted the AfterEach change  https://github.com/kubernetes/kubernetes/pull/111284  and I'm asking sig-storage to tag the slow tests accordenly to current policies (> 5 mins)  https://github.com/kubernetes/kubernetes/pull/111286

The lead now is in:

> So, it looks like something happens around 14:08 that puts the cluster in a bad state and these volume-related namespaces time out trying to delete. This pushes the run time for the entire suite (including the setup bits before Ginkgo runs) past the 1 hour limit imposed by the container/infrastructure layer.

**Comment by msau42** [comment]
I am attempting to do some bisection...

Here's a job from 7/5/22 where all of the csi tests are finishing in under 3 minutes: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110868/pull-kubernetes-e2e-kind/1544456420445917184

**Comment by msau42** [comment]
Here's a later run with quick running times: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/109683/pull-kubernetes-e2e-kind/1544882782516285440

I think I need to be looking at periodics though, not pull jobs

**Comment by msau42** [comment]
here's the earliest run I found with slow times: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110237/pull-kubernetes-e2e-gce-ubuntu-containerd/1544890836657901568/

**Comment by msau42** [comment]
Looking at CI jobs:
Here's the first job where tests started taking 10 mins: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1544925610889973760
The run before that was fine: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1544910511240384512

**Comment by onsi** [comment]
nicely done @msau42 !  how does one figure out which commit has those two runs correspond to?

**Comment by msau42** [comment]
>  how does one figure out which commit has those two runs correspond to?
Towards the beginning of the test log, it shows the kubernetes version used to create the kind cluster:
```
kubernetesVersion: v1.25.0-alpha.2.109+2a017f94bcf8d0
```

**Comment by msau42** [comment]
not really:
```
commit c04bcfb382ed261269f6154ce8c9e08360b9c985
Merge: d784ee36e3 581536f471
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Wed Jul 6 23:47:33 2022 -0700

    Merge pull request #26750 from ykakarap/capi-version-bumps-1.3
    
    Update CAPI version for periodic upgrade jobs

commit d784ee36e38de8a3ce8e6d83894f571bd65b5952
Merge: 4f9285fc33 01ebea6ffe
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Wed Jul 6 18:17:32 2022 -0700

    Merge pull request #26758 from puerco/kpromo-v3.4.4
    
    Bump image promoter jobs to v3.4.4

commit 4f9285fc337e6dc3bd05bcf5fc727417cc9488e1
Merge: 1b8c10db0d 44dd2bcf62
Author: Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com>
Date:   Wed Jul 6 12:53:34 2022 -0700

    Merge pull request #26755 from CecileRobertMichon/fix-apiversion-k8s-version
    
    CAPZ: fix kubernetes version in apiversion test
```

**Comment by msau42** [comment]
kind versions also look the same

**Comment by msau42** [comment]
BTW here's the prow job history page starting on the last good run: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel?buildId=1544910511240384512

There is a very clear step up in test time after that.

**Comment by msau42** [comment]
I think next step is to try to locally rerun the tests against the good commit and the two commits after the good run to see if we can rule them out.

**Comment by aojea** [comment]
Cross posting from https://github.com/kubernetes/kubernetes/pull/111286#issuecomment-1191226956

> Also is there a way to print out test logs from successful tests? I was trying to take a look at a slow test, but there are no detailed logs:

@msau42 find the report attached with the logs for successful tests
[testrun.html.gz](https://github.com/kubernetes/kubernetes/files/9157829/testrun.html.gz)

I've checked
```
[It] [sig-storage] CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (default fs)] subPath should support readOnly directory specified in the volumeMount
--
Passed
619.513 sec
```

Test starts

```
Jul 21 08:02:45.728: INFO: >>> kubeConfig: /root/.kube/kind-test-config
```
It seems the problem is on the namespace deletion
```
�[1mSTEP:�[0m Deleting sc �[38;5;243m07/21/22 08:03:04.954�[0m
�[1mSTEP:�[0m deleting the test namespace: provisioning-9619 �[38;5;243m07/21/22 08:03:04.958�[0m
�[1mSTEP:�[0m Waiting for namespaces [provisioning-9619] to vanish �[38;5;243m07/21/22 08:03:04.962�[0m
Jul 21 08:08:05.028: INFO: error deleting namespace provisioning-9619: timed out waiting for the condition
```

The storage tests add a custom hook to delete the namespace that seems that is the one causing they take longer

https://github.com/kubernetes/kubernetes/issues/111086#issuecomment-1189990498

**Comment by aojea** [comment]
The storage tests run all these cleanups inside the test context

https://github.com/kubernetes/kubernetes/blob/05cc31697f811f3df62321a8a66363c144fd2fc7/test/e2e/storage/testsuites/volume_io.go#L93-L117

https://github.com/kubernetes/kubernetes/blob/303f47c0c069c80ec6d2b3879bc879924d555a8a/test/e2e/storage/csi_mock_volume.go#L360-L363

https://github.com/kubernetes/kubernetes/blob/303f47c0c069c80ec6d2b3879bc879924d555a8a/test/e2e/storage/csi_mock_volume.go#L400-L401

has namespace deletion changed somehow @liggitt ?
@onsi any possible idea on how ginkgov2 could affect this workflow?

**Comment by msau42** [comment]
The reason why the CSI tests manage namespace deletion is because of deletion ordering issues. Each test installs its own CSI driver, however that CSI driver has to be deleted last otherwise Pods will fail to teardown and PVCs will fail to delete due to an uninstalled CSI driver.

**Comment by chendave** [comment]
> Each test installs its own CSI driver, however that CSI driver has to be deleted last otherwise Pods will fail to teardown and PVCs will fail to delete due to an uninstalled CSI driver.

make sense, but the log says the `csi-hostpath-ephemeral-2296` is not found. but I do find that csi driver is presented in that cluster, what am I missing here?

**Comment by onsi** [comment]
the `init` and `defer cleanup()` stuff in these tests is complex and i do wonder why the code isn't calling `BeforeEach` and `AfterEach` instead.  nonetheless i would expect this code as written to work: the `defer` will always run before the `It` returns to its caller and Ginkgo v1 and v2 both basically guarantee that for a given process no two `It`s will run in parallel - so all those closure variables shouldn't see any pollution from one test to the other within a given process.  but.  there's a lot of code here and while i don't see any obvious places where test pollution is creeping in due to these shared variables i can't say i'm 100% confident.  also - while i don't yet see how ginkgo v2 vs v1 could be causing this we definitely haven't ruled anything out yet!

one question: where are these namespace integers being generated (eg `csi-hostpath-ephemeral-2296`)  are we confident that the other parallel processes will never also pick 2296?  or is it possible that multiple processes are picking the same integer and so cross-process pollution is occurring?

it could be a good use of time run the suite while focusing just these CSI specs and running them in parallel with verbosity turned on so we can see what's going on.  my sense is the current hypothesis is that a passing test is inadvertently deleting a resources that another test running in parallel is using thereby causing it to run slower.  since we don't run with in verbose mode we won't see the relevant logs from the passing test.

that would be my suggestion for a next step.  run just these CSI specs in parallel with `-v` and see if we learn more from the logs.

**Comment by msau42** [comment]
I think I found the root cause. I did some debugging on my own PR, and debugged the GCE run because the kind run does not capture kube-controller-manager logs: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111334/pull-kubernetes-e2e-gce-ubuntu-containerd/1550310687912235008/

test log:
```
03:45:47.846: INFO: error deleting namespace csi-mock-volumes-6183: timed out waiting for the condition
```

kube-controller-manager.log:
```
E0722 03:42:32.170368       9 namespace_controller.go:162] deletion of namespace csi-mock-volumes-6183 failed: unable to retrieve the complete list of server APIs: e2e-66wkf.example.com/v1alpha1: the server is currently unable to handle the request
```

The commit that I thought wasn't suspicious is actually suspicious: https://github.com/kubernetes/kubernetes/pull/110237

**Comment by msau42** [comment]
cc @Riaankl @smarterclayton please help take a look. I think the new tests aren't cleaning up properly and causing namespace deletion in other tests to fail.

**Comment by chendave** [comment]
> debugged the GCE run

Great to hear that!

> debugged the GCE run

@msau42  Can you pls share us how to achieve that if we want to check the log from those components? where is the log file I can get?

**Comment by msau42** [comment]
> Can you pls share us how to achieve that if we want to check the log from those components? where is the log file I can get?

For example from my test run above, this is where the control plane logs are:
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/111334/pull-kubernetes-e2e-gce-ubuntu-containerd/1550310687912235008/artifacts/e2e-c189956e22-a7d53-master/

It would be nice to collect this from the kind jobs too.

**Comment by chendave** [comment]
@onis 

> the init and defer cleanup() stuff in these tests is complex and i do wonder why the code isn't calling BeforeEach and AfterEach instead.

It's historical reason,  my pr here: https://github.com/kubernetes/kubernetes/pull/111063 already commented on that, further actions are needed, this is also the action left in  https://github.com/kubernetes/kubernetes/issues/109744. We just need time to get familiar with csi e2e test code and then start the migration.

> where are these namespace integers being generated (eg csi-hostpath-ephemeral-2296)

It's generated here:  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/framework.go#L261, and used here:  https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/framework/testconfig.go#L58


> are we confident that the other parallel processes will never also pick 2296? 

In theory, I think this is possible, but the how the probability could be.

> that would be my suggestion for a next step. run just these CSI specs in parallel with -v and see if we learn more from the logs.

Good suggestion, I think we can add this parameter along with the `-ginkgo.always-emit-ginkgo-writer` to the test code, and make it masked with comment.


Anyway, @msau42 thanks for the root causing!

**Comment by aojea** [comment]
> It would be nice to collect this from the kind jobs too.

the info is there, but the failing jobs doesn't have it because the job times out cleaning the kind cluster and the related logs

If you take a working job https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind/1550377010985963520 the controller-manager logs are in 
https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind/1550377010985963520/artifacts/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_e9ec38736496c717a237032e25dc47c8/kube-controller-manager/

and this confirms @msau42 theory and demonstrates once more that correlation doesn't imply causality

 my fault :(, sorry all for the noise

```
wget https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/111172/pull-kubernetes-e2e-kind/1550377010985963520/artifacts/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_e9ec38736496c717a237032e25dc47c8/kube-controller-manager/0.log -O- | grep namespace_controller | grep "failed: unable to retrieve the complete list" | wc


   3411  105741 1087294
```

**Comment by aojea** [comment]
another observation that once the test start to run this job started to flake

![image](https://user-images.githubusercontent.com/6450081/180460286-a3773b20-a210-41cb-931a-c9154dd32b3b.png)

**Comment by onsi** [comment]
🎉 great job getting to the bottom of this @msau42 !

**Comment by aojea** [comment]
no failures since the offending test was reverted
![image](https://user-images.githubusercontent.com/6450081/180649892-47e7024d-faee-40ae-b0a0-83c770e6c9e9.png)

confirming msau theory

**Comment by BenTheElder** [comment]
> the info is there, but the failing jobs doesn't have it because the job times out cleaning the kind cluster and the related logs

that is itself a bug, and shouldn't be happening. we should get and handle a TERM from prow well before we get killed and the TERM handler should be capturing logs.

**Comment by BenTheElder** [comment]
log collection in timed out kind e2e runs should be fixed now https://github.com/kubernetes/test-infra/issues/26953, https://github.com/kubernetes/test-infra/pull/26963
