### ISSUE TITLE
Missing image, name and container labels from cAdvisor metrics in 1.24

### ISSUE THREAD

**Issue by rsmoorthy** [kubernetes/kubernetes#111077]
### What happened?

Installed 1.24 via kubeadm. The cAdvisor metrics is not showing image, name or container labels.

`kubectl get --raw /api/v1/nodes/$NODE/proxy/metrics/cadvisor| grep 'image="[^"]'`

shows no output

### What did you expect to happen?

On a different cluster with 1.23, I can see image, name and container labels:

`container_blkio_device_usage_total{container="POD",device="/dev/vda",id="/kubepods/besteffort/pode51c0f6a-c21d-41cc-87c4-f899bd9a755d/f42da1b89b424b87ea4712f92267823cb2eb34794cce750292f656515c630d9f",image="k8s.gcr.io/pause:3.6",major="253",minor="0",name="k8s_POD_nginx4_default_e51c0f6a-c21d-41cc-87c4-f899bd9a755d_1",namespace="default",operation="Async",pod="nginx4"} 0 1657570777845`

### How can we reproduce it (as minimally and precisely as possible)?

Install Kubernetes 1.24 via kubeadm

Please note the kubelet and cri-dockerd flags for reference

`/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cloud-provider=external --container-runtime=remote --container-runtime-endpoint=unix:///run/cri-dockerd.sock --pod-infra-container-image=k8s.gcr.io/pause:3.7`

`/usr/local/bin/cri-dockerd --network-plugin=cni --cni-bin-dir=/opt/cni/bin --cni-cache-dir=/var/lib/cni/cache --cni-conf-dir=/etc/cni/net.d --pod-infra-container-image=k8s.gcr.io/pause:3.7`

### Anything else we need to know?

Please refer this [issue](https://github.com/k3s-io/k3s/issues/5782) with K3S, but there is a PR that fixes the problem in K3S itself.

Google searches reveal users facing similar problem [earlier](https://github.com/kubernetes/kubernetes/issues/96980), when they had docker path running in a different location.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
None. This is bare metal.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux hostname 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


```

</details>

### Install tools

<details>
`kubeadm init --upload-certs --config /tmp/init-config.yaml`

$ cat /tmp/init-config.yaml
```
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///run/cri-dockerd.sock"
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
$ cri-dockerd --version
cri-dockerd 0.2.3 (HEAD)
$ containerd --version
containerd containerd.io 1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
$ sudo docker version
[sudo] password for ubuntu: 
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
Kube1.24 has removed docker plugin from cadvisor, so although you can use cri-dockerd to adapt container runtime, but the cadvisor could not fetch docker container infos about image labels and so on.

**Comment by endocrimes** [comment]
/triage needs-information

Is the docker socket running in the default location? (`unix:///var/run/docker.sock`)

**Comment by rsmoorthy** [comment]
> /triage needs-information
> 
> Is the docker socket running in the default location? (`unix:///var/run/docker.sock`)

Yes

**Comment by endocrimes** [comment]
/remove-triage needs-information

/cc @bobbypage 

any idea if cri-dockerd needs anything special for cadvisor to work?

**Comment by vladohotnikov** [comment]
Hello, do you have any updates? I have same issue.
Can't view metrics for pods. And all Grafana dashboard got broken =(

**Comment by DieterDP-ng** [comment]
It seems other metrics have lost different labels as well.

For example, `container_network_receive_bytes_total` and `container_fs_io_current` have lost the `pod` label.

**Comment by SergeyKanzhelev** [comment]
Public docs update is tracked here: https://github.com/kubernetes/website/issues/30681 I will close this in favor of that documentation task as unfortunately this is a known limitation and the workaround is to use cadvisor.

/close

**Comment by AlawnWong** [comment]
how to fix this issue ?

**Comment by AcidAngel21** [comment]
@AlawnWong I have posted a workaround here that works for me. Maybe it will help you too.
https://github.com/rancher/rancher/issues/38934#issuecomment-1294585708
