### ISSUE TITLE
Enable running_managed_controllers for KCM and CCM

### ISSUE THREAD

**Issue by jprzychodzen** [kubernetes/kubernetes#111029]
### What would you like to be added?

`running_managed_controllers` is a stub of a metrics that allows tracking of running controllers between different controller-managers. This metric is partially implemented, but is not injected/enabled by specific controllers.

Code for a metric is available [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/prometheus/controllers/metrics.go).

I would like to enable this metric for controllers, starting from controllers that will be migrated from KCM to CCM as a part of cloud providers migration/extraction effort.

### Why is this needed?

To reliably migrate controllers, there should be available metric that allows to track specific which controllers are running in which controller-manager.

**Comment by dims** [comment]
@jprzychodzen anything else to do here? please close out otherwise.

thanks!

**Comment by dims** [comment]
@jprzychodzen ack, poked the release managers on #release-management channel.

**Comment by jprzychodzen** [comment]
Thanks for help @dims

/close
