### ISSUE TITLE
Worker node not showing External DNS address

### ISSUE THREAD

**Issue by Ed87** [kubernetes/kubernetes#111085]
I have a MongoDB deployment for which I need to execute backups _from outside the cluster_. According to the instructions [here](https://www.mongodb.com/docs/kubernetes-operator/master/tutorial/connect-from-outside-k8s/) I need the FQDN of the node on which the deployment is scheduled.

To execute the backups I run this command :

`.\mongodump --host=127.0.0.1 --db=platforms --port=27017 --authenticationDatabase="admin" -u="root" -p="xxxxxx"  --out=C:\Users\myuser\Documents\MongoBackups\backup.bson
`
_This is working_ but however its when I port-forward the NodePort service of the deployment. Ideally I need to replace the **--host**  parameter with the FQDN of the node.

To get the FQDN I have tried :

`kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="ExternalDNS")].address }'`

but it gives no output. 

When I do :
`kubectl describe nodes`

I get this for the node on which the deployment is scheduled :

`Name:               labsdev-15-155-worker-2
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=6xxxxxxx-2xxx-4444-895v-5xxxxxxxxxxx
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=RegionOne
                    failure-domain.beta.kubernetes.io/zone=sova
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=labsdev-15-155-worker-2
                    kubernetes.io/os=linux
                    node.kubernetes.io/instance-type=6xxxxxxx-2xxx-4444-895v-5xxxxxxxxxxx
                    topology.cinder.csi.openstack.org/zone=sova
                    topology.kubernetes.io/region=RegionOne
                    topology.kubernetes.io/zone=sova
Annotations:        alpha.kubernetes.io/provided-node-ip: 192.168.100.100
                    csi.volume.kubernetes.io/nodeid: {"cinder.csi.openstack.org":"bxxxxxxxx-cxxx-4xxxx-9xxx-bxxxxxxxxxxx"}
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/containerd/containerd.sock
                    node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 192.168.100.100/24
                    volumes.kubernetes.io/controller-managed-attach-detach: true
Addresses:
  InternalIP:  192.168.100.100
  Hostname:    labsdev-15-155-worker-2`

It shows that ExternalDNS has not been configured and similarly when I `kubectl get nodes -o wide` I do not see any ExternalIP :

`kubectl get nodes -o wide
NAME                       STATUS   ROLES                  AGE    VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
labsdev-15-155-master-1   Ready    control-plane,master   413d   v1.21.5   192.168.200.200   <none>        Ubuntu 20.04.1 LTS   5.8.0-43-generic   containerd://1.4.6
labsdev-15-155-worker-2   Ready    <none>                 53d    v1.21.5   192.168.100.100   <none>        Ubuntu 20.04.1 LTS   5.8.0-43-generic   containerd://1.4.6`

What am I missing?

Do I need to configure ExternalDNS manually for the worker node. I was expecting to access the deployment at least via the node IP and NodePort (or ExternalDNS as in this case) but it appears I will need to do some entirely different config.

**Comment by neolit123** [comment]
/sig network
/kind support

Might be better to ask for support here first
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by YarikRevich** [comment]
If you want to access your Deployment externally, you should specify Service workload for Deployment and then use configured FQDN to access it.

**Comment by dcbw** [comment]
Also, ExternalDNS addresses for nodes require Cloud Provider support. eg, for AWS it's pulled from the "public-hostname" or "publicDnsName" property of that instance's metadata. That may take some additional configuration of your AWS instances (if that's what you're using).

**Comment by thockin** [comment]
As Dan cited: "ExternalDNS" on a Node is an optional config, written by the cloud provider module and not all cloud providers populate that.  GCP, for example, does not seem to provide it.

Are you coming from REALLY outside or just on the same network as the cluster but not IN the cluster?
