### ISSUE TITLE
Promote Ephemeral Containers to GA

### ISSUE THREAD

**Issue by verb** [kubernetes/kubernetes#111030]
### What would you like to be added?

This issue tracks the change required to update the `EphemeralContainers` feature gate to GA

### Why is this needed?

This promotes ephemeral containers to GA

**Comment by pacoxu** [comment]
According to https://github.com/kubernetes/enhancements/blob/321b82a9d05acc5bd8b6aef5864b7a944c0d733c/keps/sig-node/277-ephemeral-containers/README.md#beta---ga-graduation

### Beta -> GA Graduation

- [x]  Ephemeral Containers have been in beta for at least 2 releases. （beta in v1.23）
- [x]  Ephemeral Containers see use in 3 projects or articles.
- [ ]  Ephemeral Container creation is covered by [conformance tests](https://git.k8s.io/community/contributors/devel/sig-architecture/conformance-tests.md). (Promote some test case to conformance tests)
- [ ]  The following cosmetic codebase TODOs are resolved:
- - [ ]  kubectl incorrectly suggests a debug container can be reattached after exit
- - [ ]  validateEphemeralContainers adds a superfluous index to ephemeral container spec paths

**Comment by verb** [comment]
Hi @pacoxu, 

Yes, I've opened issues for each of these items. See the checklist in https://features.k8s.io/277 for the index.
