### ISSUE TITLE
Issue with kubeadm.k8s.io/v1beta3 ClusterConfiguration dns fields

### ISSUE THREAD

**Issue by vkguleria** [kubernetes/kubernetes#111082]
### What happened?

In kubeadm ClusterConfiguration dns member dns.imageMeta or dns.ImageMeta, which is a required field, is not recognized and it throws the error as follows:

I0712 08:54:11.217648   18632 initconfiguration.go:254] loading configuration from "/etc/kubernetes/kubeadm-config.yaml"
W0712 08:54:11.219364   18632 initconfiguration.go:305] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta3", Kind:"ClusterConfiguration"}: strict decoding error: unknown field "dns.ImageMeta"

### What did you expect to happen?

dns.imageMeta should be recognized as per the documentation.

### How can we reproduce it (as minimally and precisely as possible)?

Try to run kubeadm init.

### Anything else we need to know?

We tried to use kubeadm apiVersion: kubeadm.k8s.io/v1beta3 with Kubernetes v1.25-alpha.2

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2", GitCommit:"3084eb4000cdb94260da320f2f2a612e4615f18d", GitTreeState:"clean", BuildDate:"2022-07-08T07:16:47Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
```

</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
$ uname -a
Linux master-0-vin-ibd-eccd-stack 5.3.18-150300.59.76.1.24426.1.PTF.1195504-default #1 SMP Mon Jun 27 08:18:56 UTC 2022 (905fa3b) x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chymy** [comment]
`ImageMeta ` is `json:",inline"`:

https://github.com/kubernetes/kubernetes/blob/15f111f78f579437fd9165624d2dd2cc8e71f3a5/cmd/kubeadm/app/apis/kubeadm/types.go#L177-L184

You should configure it like this:
```yaml
...
dns:
  imageRepository: "image"
  imageTa: "1.8.4"
...
```

**Comment by vkguleria** [comment]
Got it thanks !
