### ISSUE TITLE
Tag archive checksum changed

### ISSUE THREAD

**Issue by graywolf-at-work** [kubernetes/kubernetes#111121]
### What happened?

When fetching the source code for kubernetes using https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.20.15.tar.gz, the checksum did change. When fetching right now, the checksum is 0570cdd48d4534cb40b0cec273c065cae15f9156d7dae01a3a19893cf17112f4.

### What did you expect to happen?

Checksum used to be 527289e39bd202f49dbe10d10b3f9856a01de4da68d4ab973deb422f6cf4d034 and I would expect it not to change.

### How can we reproduce it (as minimally and precisely as possible)?

Download https://github.com/kubernetes/kubernetes/archive/refs/tags/v1.20.15.tar.gz and run sha256sum on it.

### Anything else we need to know?

No.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by dims** [comment]
possibly related to https://github.com/kubernetes/kubernetes/issues/99376

```
[dims@dims-m1-7728 16:14] ~/go/src/k8s.io/kubernetes ⟩ find . -name .gitattributes | xargs rg export-subst
./staging/src/k8s.io/component-base/version/.gitattributes
1:base.go export-subst

./staging/src/k8s.io/client-go/pkg/version/.gitattributes
1:base.go export-subst

./hack/lib/.gitattributes
1:version.sh export-subst
```
