### ISSUE TITLE
[failing-test] ci-kubernetes-e2e-gce-scale-correctness failing

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#111111]
### Which jobs are failing?

ci-kubernetes-e2e-gce-scale-correctness

### Which tests are failing?

All test scenarios are passing, but the job hangs on a kubectl command while collecting logs.

### Since when has it been failing?

07-07

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness&show-stale-tests=

### Reason for failure (if possible)

`kubectl delete namespace logexporter` command doesn't complete for >1.5 hour. It's unclear if the delete itself gets stuck, or if kubectl is still waiting for it to complete after it's already done.

### Relevant SIG(s)

/sig scalability

**Comment by aleksandra-malinowska** [comment]
Thank you for reverting. Yes, it seems likely it was unrelated after all, sorry about this.

Regarding how this test works - the failing step is part of test infrastructure, not any specific test scenario. It collects logs after all tests have run.

I've added 15m timeouts to affected `kubectl delete` commands, which will hopefully allow us to at least upload the logs from control plane VMs (a step that happens later) and debug this further. There were some issues with kubekins build not picking up changes to logexporter, so none of the earlier runs included this, but hopefully we'll get one by Monday.

**Comment by mpuckett159** [comment]
No problem at all. Thanks for updating me. I will update my ticket to reimplement these changes to note that it appears that this is not related.

If you do find eventually that kubectl delete (which makes use of the wait library) is a source of issues please let me know and I'll continue to investigate.
