### ISSUE TITLE
Redundant deps

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#111188]
### What happened?

```
$ grep pretty go.mod 
	github.com/kr/pretty => github.com/kr/pretty v0.2.1
	github.com/niemeyer/pretty => github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
```

github.com/niemeyer/pretty seems to be an old fork of github.com/kr/pretty.

We should track down why and fix it.

### What did you expect to happen?

One copy of pretty.

### How can we reproduce it (as minimally and precisely as possible)?

grep pretty go.mod 

### Kubernetes version

<details>
HEAD
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>
NA
</details>

### Install tools

<details>
NA
</details>

### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

**Comment by Abirdcfly** [comment]
/assign

I want fix it.😀😃😄😁

**Comment by Abirdcfly** [comment]
```bash
❯ go mod why github.com/kr/pretty
# github.com/kr/pretty
k8s.io/kubernetes/pkg/kubelet/cm
github.com/opencontainers/runc/libcontainer/cgroups/manager
github.com/opencontainers/runc/libcontainer/cgroups/fs2
github.com/opencontainers/runc/libcontainer/cgroups/ebpf
github.com/cilium/ebpf
github.com/cilium/ebpf.test
github.com/frankban/quicktest
github.com/kr/pretty

❯ go mod why -m github.com/niemeyer/pretty
# github.com/niemeyer/pretty
k8s.io/kubernetes/cmd/genyaml
gopkg.in/yaml.v2
gopkg.in/yaml.v2.test
gopkg.in/check.v1
github.com/niemeyer/pretty
```

`github.com/niemeyer/pretty` is an old fork of `github.com/kr/pretty`, so we should use only `github.com/kr/pretty`.
```mermaid
  flowchart  TD;
  A[k8s]-->B[gopkg.in/yaml.v2];
  A[k8s]-->C[gopkg.in/yaml.v3];
  B[gopkg.in/yaml.v2]-->D[gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 old version];
  C[gopkg.in/yaml.v2]-->D[gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 old version];
  D[gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405 old version]-->E[github.com/niemeyer/pretty];
```

`gopkg.in/yaml.v3` go.mod
https://github.com/go-yaml/yaml/blob/f6f7691b1fdeb513f56608cd2c32c51f8194bf51/go.mod#L4

`gopkg.in/yaml.v2` go.mod
https://github.com/go-yaml/yaml/blob/7649d4548cb53a614db133b2a8ac1f31859dda8c/go.mod#L5

The core reason is that the `gopkg.in/yaml` references older versions of the `gopkg.in/check.v1` library

There are prs to bump dep:
https://github.com/go-yaml/yaml/pull/694 in v3 branch (opend in 18 Jan 2021)
https://github.com/go-yaml/yaml/pull/874 in v2 branch (opend just now)

It looks like nothing can be done at the k8s level.🤷‍♂️

**Comment by muyangren2** [comment]
Your analysis is very good @Abirdcfly

**Comment by dims** [comment]
```
❯ go mod why github.com/kr/pretty
# github.com/kr/pretty
k8s.io/kubernetes/cmd/genyaml
gopkg.in/yaml.v2
gopkg.in/yaml.v2.test
gopkg.in/check.v1
github.com/kr/pretty

❯ go mod why -m github.com/niemeyer/pretty
# github.com/niemeyer/pretty
(main module does not need module github.com/niemeyer/pretty)
```

Yay! we fixed it somewhere somehow... :)

/close
