### ISSUE TITLE
Failing ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures on sig-release-1.23-blocking

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/kubernetes#111114]
### Which jobs are failing?

ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures

### Which tests are failing?

The job is unable to bootstrap a cluster.

### Since when has it been failing?

Apr 21 02:27:52 UTC+0530

### Testgrid link

https://testgrid.k8s.io/sig-release-1.23-blocking#gce-cos-k8sstable2-alphafeatures

### Anything else we need to know?

Last successful run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures/1516793201854255104
First failed run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable2-alphafeatures/1516883799705653248

### Relevant SIG(s)

/sig testing
/sig release

**Comment by saschagrunert** [comment]
PTAL @kubernetes/cloud-provider-gcp-maintainers @kubernetes/sig-cloud-provider

**Comment by palnabarun** [comment]
Updated the testgrid link since the jobs have rotated between boards since the v1.25.0-rc.0 cut.
