### ISSUE TITLE
Prolonged etcd reelection causes api-server to close all watchers.

### ISSUE THREAD

**Issue by marseel** [kubernetes/kubernetes#111116]
### What happened?

When etcd is unable to elect leader for 3 election cycles, etcd returns "no leader" error through watches.
This can be seen in api-server logs as `watch chan error: etcdserver: no leader`.
Also, when apiserver receives this error, it terminates all watchers: `Terminating all watchers from cacher  ...`.

In large clusters, this can destabilize master, as all these watchers need to be recreated almost at the same time, overwhelming api-server quite often. 

I propose adding new api-server flag that allows to specify timeout, during which we are retrying to reestablish apiserver <-> etcd watches, without terminating all api-server watchers. If we are unable to reestablish watches within this specified timeout, we start terminating all watchers.

### What did you expect to happen?

Losing etcd leader for ~2-3s does not destabilize api-server.

### How can we reproduce it (as minimally and precisely as possible)?

Trigger prolonged reelection of etcd leader.

### Kubernetes version

Observed in all kubernetes versions 1.19-1.24

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by marseel** [comment]
I believe it's coming from this change. As I mentioned, the idea to mitigate it is to add some parameter that will allow us to ignore this error coming from etcd for specific duration without terminating all watchers.

**Comment by wojtek-t** [comment]
> I believe it's coming from this change. As I mentioned, the idea to mitigate it is to add some parameter that will allow us to ignore this error coming from etcd for specific duration without terminating all watchers, for example 10s be default.

With this comment thread in mind, It would probably be cleaner to allow for simply setting the "timeout" as part of WithRequireLeader option (instead of using the constant of 3). But that would require etcd changes, including the API and we want to workaround that in much smaller timeframe.

But a comment about how to make that cleaner with some additional context from here would help.
