### ISSUE TITLE
Kublet API based Documentation for Minion Metrics

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kubernetes#11114]
Hello,

I was been trying to make the kublet api to be open so that i can access the cadvisor @8080 port so i have done the changes in the /etc/kubernetes/kublet and added the line to open the kublet api

 location of the api-server
KUBELET_API_SERVER="--api_servers=http://0.0.0.0:8080"

and i have added the kublet api server based settings in the systemd file for kublet.service

[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://github.com/GoogleCloudPlatform/kubernetes
After=docker.service
Requires=docker.service

[Service]
WorkingDirectory=/var/lib/kubelet
EnvironmentFile=-/etc/kubernetes/config
EnvironmentFile=-/etc/kubernetes/kubelet
ExecStart=/usr/bin/kubelet \
            $KUBE_LOGTOSTDERR \
            $KUBE_LOG_LEVEL \
            $KUBELET_API_SERVER \
            $KUBELET_ADDRESS \
            $KUBELET_PORT \
            $KUBELET_HOSTNAME \
            $KUBE_ALLOW_PRIV \
            $KUBELET_ARGS
Restart=on-failure

When i see the status of the node in the master i see its ready and running but when i try pinging to the kublet port from the public ip i dont get any reply and when i see on the machine for the port i dont see it listening 

    [fedora@ip-10-20-30-94 ~]$ netstat -vpln
    (Not all processes could be identified, non-owned process info
    will not be shown, you would have to be root to see it all.)
    Active Internet connections (only servers)
    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -
    tcp        0      0 10.20.30.94:10250       0.0.0.0:*               LISTEN      -
    tcp6       0      0 :::22                   :::*                    LISTEN      -
    tcp6       0      0 :::38015                :::*                    LISTEN      -
    tcp6       0      0 :::9090                 :::*                    LISTEN      -
    tcp6       0      0 :::54183                :::*                    LISTEN      -
    tcp6       0      0 :::10249                :::*                    LISTEN      -
    
    udp        0      0 0.0.0.0:26170           0.0.0.0:*                           -
    udp        0      0 0.0.0.0:68              0.0.0.0:*                           -
    udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
    udp6       0      0 :::6741                 :::*                                -

And i dont see any documentation for the kublet api .can you please help me out with any documentation

**Comment by erictune** [comment]
kubelet is on 10250 usually?  Why do you think it is on 8080?

**Comment by erictune** [comment]
@dchen1107 @vmarmol

**Comment by dchen1107** [comment]
cAdvisor's port is 4194, not on 8080. kubelet is on 10250 (secure one), and 10248 (read-only one)

**Comment by kgrvamsi** [comment]
@dchen1107  when i start the kublet then i should see the cadvisor port running on 4194 and the kublet port @10250 but as you can see my above comment i see only 10250 port opened but not the cadvisor port.

@erictune initially i was in a assumption that kublet also serves the cadvisor api's on the same port but later i go to know from other issues that cadvisor runs by default (standalone mode) on 8080 port but at kubernetes world it runs on 4194 port but if u can see my above comment there is no cadvisor running on the minion server.

**Comment by kgrvamsi** [comment]
Today i have another issue when i was setting up the kubernetes master with one minion and here is the output from one of the minion about the ports

core@ip-10-20-30-45 ~/kubestack $ netstat -vpln
(No info could be read for "-p": geteuid()=500 but you should be root.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 :::50460                :::*                    LISTEN      -
tcp6       0      0 :::55709                :::*                    LISTEN      -
tcp6       0      0 :::4194                 :::*                    LISTEN      -
tcp6       0      0 :::2375                 :::*                    LISTEN      -
tcp6       0      0 :::10250                :::*                    LISTEN      -
tcp6       0      0 :::5355                 :::*                    LISTEN      -
tcp6       0      0 :::10255                :::*                    LISTEN      -
netstat: no support for `AF INET (sctp)' on this system.
netstat: no support for `AF INET (sctp)' on this system.
udp        0      0 10.20.30.45:68          0.0.0.0:*                           -
udp        0      0 0.0.0.0:5355            0.0.0.0:*                           -
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -
udp6       0      0 :::5355                 :::*                                -
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     19824    -                    /var/run/docker.sock
unix  2      [ ACC ]     STREAM     LISTENING     7543     -                    /run/systemd/journal/stdout
unix  2      [ ACC ]     STREAM     LISTENING     10365    -                    /run/systemd/private
unix  2      [ ACC ]     SEQPACKET  LISTENING     10718    -                    /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING     12521    -                    /var/run/dbus/system_bus_socket
netstat: no support for `AF IPX' on this system.
netstat: no support for `AF AX25' on this system.
netstat: no support for `AF X25' on this system.
netstat: no support for `AF NETROM' on this system.

**Comment by kgrvamsi** [comment]
Closing this issue as i can  access to all the ports with no problem.
