### ISSUE TITLE
Kubelet's cAdvisor endpoint serving stale metrics?

### ISSUE THREAD

**Issue by poblahblahblah** [kubernetes/kubernetes#111157]
### What happened?

We are looking at migrating to the kubelet provided cAdvisor for gathering container/pod metrics.

We have Prometheus configured to scrape the kubelet's endpoint using a standard configuration.

When comparing metrics from the current exporter (metrics-server-exporter) to kubelet's cAdvisor we noticed that there was a discrepancy between the two. Digging further it looks like kubelet's cAdvisor is serving out stale data that is causing our graphs to be off. This discrepancy is especially prominent in namespaces with high churn of large memory utilization pods.

We are using docker as our primary container engine, but I was also able to repro this using both docker and containerd across multiple clusters.

docker on EKS:
![ac-docker](https://user-images.githubusercontent.com/51938/179047150-59a718aa-2e5a-41eb-8168-56db591157c4.png)

docker on EKS:
![gitlab-docker](https://user-images.githubusercontent.com/51938/179047226-4cd07552-c088-4332-a075-cff6a4c34075.png)

containerd on EKS:
![gatekeeper-containerd](https://user-images.githubusercontent.com/51938/179047250-1071e4c4-09e6-4a0b-8523-d41ccf60277c.png)

containerd on AKS:
![argocd-containerd](https://user-images.githubusercontent.com/51938/179049194-873bc915-3b81-48d3-81a6-0d7f9cc7054b.png)

### What did you expect to happen?

I expected the metrics to match up between the two exporters reasonably well

### How can we reproduce it (as minimally and precisely as possible)?

* Create an AWS EKS or Azure AKS running 1.21 using either docker or containerd
* Run metrics-server-exporter for a baseline
* Configure Prometheus to scrape the kubelet's cAdvisor endpoint
* Run a workload
* Gather data for a few minutes
* Kill a pod
* Compare results

### Anything else we need to know?

If I had to take a shot in the dark guess I would think that this cache duration was causing or exacerbating the issue: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cadvisor/cadvisor_linux.go#L58

I am also curious about the state of kubelet's cAdvisor. There are a few Issues in the backlog which talk about cAdvisor being removed from kubelet entirely, although these are all from 2016/2017

https://github.com/kubernetes/kubernetes/pull/19719#issuecomment-173268168
https://github.com/kubernetes/kubernetes/issues/18770
https://github.com/kubernetes/kubernetes/issues/19432

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"767d382613a87705d5ee3e6b1adf6c041089f27f", GitTreeState:"clean", BuildDate:"2022-06-21T17:11:30Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS 1.21
Azure AKS 1.21
</details>

### OS version

<details>

```console
# EKS:

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

</details>

### Install tools

<details>
[metrics-server-exporter](https://github.com/olxbr/metrics-server-exporter)
[prometheus](https://prometheus.io/download/)
</details>

### Container runtime (CRI) and version (if applicable)

<details>
AKS:  Container Runtime Version:  containerd://1.4.13+azure-3
EKS (docker):   Container Runtime Version:  docker://20.10.7
EKS (containerd):   Container Runtime Version:  containerd://1.4.6 
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by poblahblahblah** [comment]
I had forgotten that I needed to test this out with cAdvisor as a DaemonSet. We are seeing the same behavior  in cAdvisor 0.39.3 as we are in the Kubelet's cAdvisor.

![cadvisor-containerd](https://user-images.githubusercontent.com/51938/179060398-ef7e295c-0045-4988-a97a-34f2ba13e95e.png)

The effect is a bit more pronounced in the above graph because there is only 1 pod running in the namespace.

**Comment by bobbypage** [comment]
Can you try using the latest version of cAdvisor, e.g https://github.com/google/cadvisor/releases/tag/v0.44.0

Also, make sure that the houseKeepingPeriod is the same. cAdvisor configures it to 1 second - https://github.com/google/cadvisor/blob/release-v0.44/manager/container.go#L49

Kubelet is configuring it to 15 seconds by default which may be cause of the discrepancy you are seeing:

xref: https://github.com/kubernetes/kubernetes/blob/d6f4a5d/pkg/kubelet/cadvisor/cadvisor_linux.go#L106-L110 and https://github.com/kubernetes/kubernetes/blob/d6f4a5d/pkg/kubelet/cadvisor/cadvisor_linux.go#L59
