### ISSUE TITLE
kubelet.go:2424 node "master" not found

### ISSUE THREAD

**Issue by nzb15555196162** [kubernetes/kubernetes#111195]
### What happened?

install kubernetes with kubeadm, the version is v1.24.3, kubadm init failed in the master node wth lots of node "master" not found

### What did you expect to happen?

 kubadm init success

### How can we reproduce it (as minimally and precisely as possible)?

1 execute kubeadm init...
2 see detail error 
   This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'
3 when i execute  systemctl status kubelet, it show error message
    kubelet.go:2424] "Error getting node" err="node \"master\" not found"

plese see snapshot:
![imageonline-co-gifimage](https://user-images.githubusercontent.com/18350673/179384100-c6a87260-4601-41e8-8e4c-9c359439eb0a.gif)

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

</details>


### Cloud provider

<details>
no any cloud platform just on linux kenel.
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
# Linux master 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Abirdcfly** [comment]
/remove-kind bug
/kind support

Just a personal opinion, text log > picture log > gif log

**Comment by neolit123** [comment]
The kubelet prints this message until the node object ID created. The reason for the failures is probably something else. Check closely in the kubelet logs.

Please see this as well:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by nzb15555196162** [comment]
> The kubelet prints this message until the node object is created. The reason for the failures is probably something else. Check closely in the kubelet logs.
> 
> Please see this as well: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
> 
> /close

thank you for you reply, ok, i will check

**Comment by MickMi** [comment]
I met the exactly the same question as you, do you found the solution?

**Comment by minhhungit** [comment]
I got the same issue after restart all nodes

**Comment by MickMi** [comment]
ok, the solution for me is that you need to check the available IP of your service, it may not be the same as your public IP.

**Comment by rsoika** [comment]
@MickMi  how do I check the available IP on my system? 
I run into the same issue and I can't figure out the root of the problem. Do you know some kind of test to verify if the IPs are fine for the kubeadm process?
