### ISSUE TITLE
API server does not fail when the file in `--audit-log-path` is deleted which results into lost of audit logs

### ISSUE THREAD

**Issue by vpnachev** [kubernetes/kubernetes#111208]
### What happened?

I have a k8s cluster with kube-apiserver configured with the following audit flags
```yaml
- --audit-log-path=/var/lib/audit.log
- --audit-policy-file=/etc/kubernetes/audit/audit-policy.yaml
- --audit-log-maxsize=100
- --audit-log-maxbackup=5
- --audit-log-mode=blocking-strict
```

Initially everything is working fine and I can see the AuditEvents in the `/var/lib/audit.log` file on the host. However, if I delete the `/var/lib/audit.log` file, kube-apiserver keeps working with no issues 
- it accepts my requests
- the responses contain `Audit-Id` header
- there is even no error or warning in the application logs of the kube-apiserver that it tries to write in deleted file

The monitoring metrics are also not indicating that there is an issue with writing audit logs as the `apiserver_audit_event_total` metric keep increasing while `apiserver_audit_error_total` stays at zero value (it is even not available on the `/metrics` endpoint).

```console
$ curl localhost:8001/metrics -sS | grep _audit_ | grep -v '^#'
apiserver_audit_event_total 10
apiserver_audit_level_total{level="None"} 25894
apiserver_audit_level_total{level="RequestResponse"} 5
apiserver_audit_requests_rejected_total 0
```

### What did you expect to happen?

The kube-apiserver to exit with error when it tries to write AuditEvent to a non-existing file.
If this is not possible, it should make it clear that the audit logging is failing, e.g.
- fail the requests to the API server
- track the failures in the `apiserver_audit_error_total` metric
- log error messages about the failures.

### How can we reproduce it (as minimally and precisely as possible)?

Start kube-apiserver with the above flags. The audit policy file can be:
```yaml
apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
rules:
  - level: RequestResponse
    namespaces:
    - test
    resources:
    - group: ""
      resourceNames:
      - test
      resources:
      - configmaps
```

Create a `test` namespace and configmap:
```console
$ kubectl create namespace test
$ kubectl -n test create configmap test
```

Then run the following command `kubectl -n test get configmap test` and verify that the `/var/lib/audit.log` file is created and there is `AuditEvent`s in it. 
Then delete the audit log file `rm /var/lib/audit.log` and run `kubectl -n test get configmap test` command and verify that
- the request to the API server succeeds ( if the -v=8 flag is set to kubectl, the `Audit-Id` header should be printed as well)
- the `/var/lib/audit.log` file is not re-created 
- the `apiserver_audit_event_total` metric is increased, but `apiserver_audit_error_total` is not increased
- kube-apiserver application logs have no error or warning about attempt to write to a deleted file
- kube-apiserver does not crash and exit with any error

### Anything else we need to know?

/area audit

### Kubernetes version

<details>

```console
$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-06-15T14:15:38Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
This feels like a feature request to me. Kubernetes currently assumes that the cluster operator is able to protect the audit log from unlinking, truncation, etc.

I think that's a reasonable thing for Kubernetes to assume. An attacker that deliberately removes the audit log or its parent directory could, for example, also switch the log destination to a tmpfs or a special mount point that discards data. At some point, Kubernetes ought to assume that the system that it runs on is secured appropriately.

The inode isn't likely _missing_ after it's unlinked, and calls to `write()` would be succeeding. A common pattern for log rotation relies on being able to write to a log that has been unlinked or renamed from its original path.

As an enhancement, it might be useful for the API server to attempt to periodically reopen the current audit log and to report an error if this fails.
We could also:
- produce an official sidecar container that watches crucial files and complains (logs? metrics?) when these are missing
- add a check that the audit log exists and report an error every time that check fails, plus increment a metric
  - whilst still writing to the open audit log, so that if usual Unix-style log rotation is happening, things work as expected.

**Comment by lavalamp** [comment]
I think this is not really api machinery as much as auth.

/remove-sig api-machinery
/needs-triage

**Comment by enj** [comment]
I have not confirmed this issue, but I feel that if `--audit-log-mode=blocking-strict` is set and the audit event cannot be written to the sink, the request should fail.  @tallclair any thoughts?

**Comment by tallclair** [comment]
Yes, I agree that with `blocking-strict` mode, the request should fail. But given @sftim's comment https://github.com/kubernetes/kubernetes/issues/111208#issuecomment-1190750202, it sounds like the write method probably isn't returning an error in this case, so I'm not sure how we would detect that.

**Comment by tallclair** [comment]
Yes, I agree that with `blocking-strict` mode, the request should fail. But given @sftim's comment https://github.com/kubernetes/kubernetes/issues/111208#issuecomment-1190750202, it sounds like the write method probably isn't returning an error in this case, so I'm not sure how we would detect that.

**Comment by sftim** [comment]
> As an enhancement, it might be useful for the API server to attempt to periodically reopen the current audit log and to report an error if this fails.

**Comment by sftim** [comment]
The period could be as low as 1 per minute, and a failed attempt still lets us continue attempting writes to the existing file descriptor.
Also, we could increment a counter metric for each failed open / reopen.
