### ISSUE TITLE
Kubelet: provides an interface to get the specified pod

### ISSUE THREAD

**Issue by WulixuanS** [kubernetes/kubernetes#111213]
### What would you like to be added?

Kubelet adds an interface to get the specified pod through namespace and name

### Why is this needed?

Our largest cluster has about 4,500 nodes, and there are about 51,000 pods in the cluster, some of which are co-located pods, which have a short life cycle and are frequently created and died. We have a cni-adaptor component on the kubelet node, which will call the apiserver to get the cni annotation of pod. Now we find that etcd has many related slow queries. At present, the optimization logic we think of is to obtain pod information through kubelet. There is a list of all pods of this node in kubelet, but now there is only an interface to obtain all pods of the current node, so I hope kubelet can also Provides an interface to get pods through podNamespace and podName.

**Comment by aojea** [comment]
/sig scalability
cc @dcbw
