### ISSUE TITLE
KubeAPIErrorBudgetBurn

### ISSUE THREAD

**Issue by huyouba1** [kubernetes/kubernetes#111266]
### What happened?

Slow requests are detected, and the API server logs are as follows. Previously, the cluster expanded and shrunk through the master node. The expansion was successful, but the monitoring found a large number of full requests.

```
I0720 01:43:45.288828       1 trace.go:205] Trace[1328107761]: "cacher list" type:*core.Namespace (20-Jul-2022 01:43:42.288) (total time: 3000ms):
Trace[1328107761]: [3.00014505s] [3.00014505s] END
I0720 01:43:45.289393       1 trace.go:205] Trace[1606567707]: "List" url:/api/v1/namespaces,user-agent:coredns/v0.0.0 (linux/amd64) kubernetes/$Format,client:192.168.10.221 (20-Jul-2022 01:43:42.288) (total time: 3000ms):
Trace[1606567707]: [3.00078644s] [3.00078644s] END
I0720 01:43:49.303059       1 trace.go:205] Trace[1999685989]: "cacher list" type:*core.Namespace (20-Jul-2022 01:43:46.302) (total time: 3000ms):
Trace[1999685989]: [3.000893537s] [3.000893537s] END
I0720 01:43:49.303757       1 trace.go:205] Trace[461986049]: "List" url:/api/v1/namespaces,user-agent:coredns/v0.0.0 (linux/amd64) kubernetes/$Format,client:192.168.10.221 (20-Jul-2022 01:43:46.302) (total time: 3001ms):
```

### What did you expect to happen?

promQL
```
(
sum(rate(apiserver_request_duration_seconds_bucket{job="apiserver",le="1",scope=~"resource|",verb=~"LIST|GET"}[3d])) or vector(0)
- 
sum(rate(apiserver_request_duration_seconds_count{job="apiserver",verb=~"LIST|GET"}[3d]))
)
/
sum(rate(apiserver_request_total{job="apiserver",verb=~"LIST|GET"}[3d]))
> 0.01
```
![image](https://user-images.githubusercontent.com/58924965/179878633-7c0a10ef-9cdd-4f6a-80bc-1f1519046141.png)

### How can we reproduce it (as minimally and precisely as possible)?

Kubedm expands and shrinks the master node. After the new node is added, delete the old node (including etcd).

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
null
</details>

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Linux master-1 4.16.2 #1 SMP Thu Mar 10 18:07:25 CST 2022 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support
refer to https://github.com/prometheus-operator/kube-prometheus/wiki/KubeAPIErrorBudgetBurn or https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/615

**Comment by neolit123** [comment]
/close

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
