### ISSUE TITLE
Kubernetes 0.21 with flannel on CentOS 7 

### ISSUE THREAD

**Issue by Icedroid** [kubernetes/kubernetes#11123]
I have two machines installed CentOS 7, I call one is Master, the other is Node. Now how to start the k8s cluster successfully with the guide: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/scratch.md

# On the Master have done as follow:
* start kubelet
```
$ ./kubelet --config=/etc/kubernetes/manifests
```
* start etcd, apiserver, scheduler, controller-manager 
Like scrach guide put etcd.manifest, apiserver.manifest... into /etc/kubernetes/manifests

**Question 1: Only the manifests pods file put into the kubelet config dir, It will auto create a Pod and run it?  shouldn't I start these services inside contrainers ?.**
 As @antoineco  say:
>It's also perfectly legitimate to run your Kubernetes services as host processes, and not inside containers. In this case just drop the binaries in your $PATH and forget about the master kubelet

* etcdctl write the network to /coreos.com/network/config

etcdctl download from  https://github.com/coreos/etcd/releases/download/v0.4.5/etcd-v0.4.5-linux-amd64.tar.gz
```
$ etcdctl mk /coreos.com/network/config '{"Network":"10.0.0.0/16"}'
```

# On the Node have done as follow:
* Delete the docker0
```
$ yum install bridge-utils
$ iptables -t nat -F 
$ ifconfig docker0 down
$ brctl delbr docker0
```
**Question 2: Should I run above command on the Master?**

* After edit the /etc/sysconfig/docker, restart the docker with flannel network
```
--bip=10.0.0.0/16 --mtu=1400 --iptables=false --insecure-registry docker.myself
```

* Run the kubelet, kube-proxy,flanneld
```
$ ./kubelet --api-servers=http://$MASTER_IP --config=/etc/kubernetes/manifests --configure-cbr0=true --register-node=true
$ ./kube-proxy --api-servers=http://$MASTER_IP
$ ./flanneld --etcd-endpoints=http://$MASTER_IP:4001
```
**Question 3:  kubelet run args is right?**

Question More&^_^: How to add iptables rule for above network? Should I add a Cluster DNS for the cluster? 

Wait for your help. Thank you very much.

**Comment by antoineco** [comment]
1. Everything you drop inside the `--config` directory is passed to the API server and constantly watched for changes (from the [kubelet doc page](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubelet.md)). Pods **are** containers (or groups of containers), what I meant is that you don't **have** to run kubernetes components inside containers, you can also run the binaries directly, it's simpler and faster for getting started.

2. On every node, not just the master, since you're overriding the Docker default network setup. Just skip the etcd/flanneld network config step on the nodes.

3. `--configure-cbr0=true` is not necessary if you're using flannel.

**Comment by Icedroid** [comment]
@antoineco  You are so kindly. Thanks very very much for your help.

* On the master
```
$./start_master.sh
```
content is as follow:
```
cd /data/kubernetes/sever/bin/
./etcd --listen-client-urls 'http://0.0.0.0:4001' --advertise-client-urls 'http://0.0.0.0:4001' --name 'default' --data-dir /var/lib/etcd/default.etcd 2>&1 >> /var/log/etcd.log &

./kube-apiserver --insecure-bind-address=0.0.0.0 \
        --insecure-port=8888 \
        --etcd-servers=http://127.0.0.1:4001 \
        --kubelet-port=10250 \
        --service-cluster-ip-range=10.254.0.0/16 \
        --log-dir=/var/log/k8s \
        --v=0 \
        --logtostderr=false \
        --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota &

./kube-scheduler  --master='127.0.0.1:8888'  \
                  --v=0  \
                  --logtostderr=false \
                  --log_dir=/var/log/k8s &

./kube-controller-manager  --v=0 \
                           --logtostderr=false \
                           --log_dir=/var/log/k8s  \
                           --master=127.0.0.1:8888 &

```
I got these error for kube-controller-manager:
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0712 17:07:20.492353   22996 controllermanager.go:198] Failed to start service controller: ServiceController should not be run without a cloudprovider
```

* On the node
the docker option is:
```
OPTIONS='--selinux-enabled --bip=10.1.24.1/24 --mtu=1472 --iptables=false'
```

```
$./start_node.sh
```
content is as follow:
```
cd /data/kubernetes/sever/bin/
 ./kubelet  --logtostderr=false  \
           --v=0  \
           --allow-privileged=false  \
           --log_dir=/var/log/k8s  \
           --address=0.0.0.0  \
           --port=10250  \
           --register-node=true
           --api_servers=http://k8s-master:8888 &
 ./kube-proxy  --logtostderr=false  \
              --v=0  \
              --log_dir=/var/log/k8s  \
              --master=http://k8s-master:8888 &
 ./flanneld  --v=0 \
        --logtostderr=false \
        --log_dir=/var/log/k8s  \
        --etcd-endpoints=http://k8s-master:4001 &
```

I got these error for kubelet:
```
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0712 17:55:12.594873   22447 kubelet.go:682] Image garbage collection failed: unable to find data for container /
```

Because my apisever is http://k8s-master:8888, now I run kubectl every time must use this:
```
$./kubectl -s http://k8s-master:8888
```
 kubectl how to set config with this default server  or how to ~/.kube/config ?
kubectl config set server k8s-master:8888 not run normal.

**Comment by Icedroid** [comment]
kubectl config I have find the document， It solve:
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubeconfig-file.md

```
$cat ~/.kube/config
>
apiVersion: v1
clusters:
- cluster:
    api-version: v1
    server: http://127.0.0.1:8888
```

**Comment by Icedroid** [comment]
I found the etcd alway stop working. But the /var/log/etcd.log not have error message.
I don't know is it I start etcd error?
```
$ ./etcd --listen-client-urls 'http://0.0.0.0:4001' \ 
    --advertise-client-urls 'http://0.0.0.0:4001' \
     --name 'default' \
    --data-dir /var/lib/etcd/default.etcd \ 
    1>>/var/log/etcd.log  2>&1 &
```

**Comment by antoineco** [comment]
Regarding etcd, you have to advertise your ip, not 0.0.0.0 (but you can *listen* on 0.0.0.0)
You also forgot to advertise the peer URL:

```
          listen-peer-urls: http://$private_ipv4:2380
          initial-advertise-peer-urls: http://$private_ipv4:2380
          listen-client-urls: http://$private_ipv4:2379,http://localhost:2379,
          advertise-client-urls: http://$private_ipv4:2379
```

**Comment by thockin** [comment]
On Sat, Jul 11, 2015 at 7:29 PM, Icecream <notifications@github.com> wrote:

> Question 1: Only the manifests pods file put into the kubelet config dir, It will create a Pod and run it? shouldn't I start these services inside contrainers ?.

Putting those manifests in place will run pods, which includes containers.

> As @antoineco say:
>
> It's also perfectly legitimate to run your Kubernetes services as host processes, and not inside containers. In this case just drop the binaries in your $PATH and forget about the master kubelet

We want to move towards more stuff running as containers, so it's best
to make that work.

> $yum install bridge-utils
> $iptables -t nat -F
> $ifconfig docker0 down
> $brctl delbr docker0
>
> Question 2: Should I run above command on the Master?

I think those are cleanups but maybe not strictly REQUIRED.  But yes,
the master should be no different in this way.

> *After edit the /etc/sysconfig/docker, restart the docker with flannel network
>
> --bip=10.0.0.0/16--mtu=1400 --iptables=false --insecure-registry docker.myself

I Think that these flags are not needed if kubelet creates its own
cbr0, but I have not personally set up both at once.  @dchen1107 how
does kubelet choose IP and MTU for cbr0?

>  ./kubelet --api-servers=http://$MASTER_IP --config=/etc/kubernetes/manifests --configure-cbr0=true --register-node=true
> ./kube-proxy --api-servers=http://$MASTER_IP
> ./flanneld
>
> Question 3: kubelet run args is right?
>
> Should I add a Cluster DNS for the cluster?

yes, you'll want DNS - that is not in the scratch doc yet.

For comparison, my nodes look like this:

root      2897  0.3  0.4  76208 16536 ?        Sl   Jul09  16:48
/usr/local/bin/kube-proxy --master=https://kubernetes-master
--kubeconfig=/var/lib/kube-proxy/kubeconfig --v=2

root      3030  1.4  1.4 150400 54844 ?        Sl   Jul09  75:17
/usr/local/bin/kubelet --api_servers=https://kubernetes-master
--enable-debugging-handlers=true --cloud_provider=gce
--config=/etc/kubernetes/manifests --allow_privileged=False --v=2
--cluster_dns=10.0.0.10 --cluster_domain=cluster.local
--configure-cbr0=true --cgroup_root=/ --system-container=/system

root      3448  0.8  0.6 854064 24304 ?        Sl   Jul09  45:03
/usr/bin/docker -d -p /var/run/docker.pid --bridge=cbr0
--iptables=false --ip-masq=false

**Comment by Icedroid** [comment]
@thockin Your nodes run in cloud_provider gce, not in centos 7. So the binary args is not the same. Thanks.

**Comment by Icedroid** [comment]
@antoineco About ectd, It run well too as follow:
```
./etcd --addr $private_ipv4:4001 --bind-addr 0.0.0.0:4001 --data-dir /var/lib/etcd/data/ 1>>/var/log/etcd.log 2>&1 &
```
I this is equal to:
```
-listen-client-urls=http://0.0.0.0:4001
-advertise-client-urls=http://$private_ipv4:4001
```

**Comment by antoineco** [comment]
To be honest I ignored you couldn't run the controller manager without a cloud provider, so I can't really help.

Regarding the error you get when you start the kubelet, can you post the content of your `/cgroup` directory?

**Comment by Icedroid** [comment]
kubelet.ERROR content as follow:
> E0713 00:45:27.399978   21812 kubelet.go:682] Image garbage collection failed: unable to find data for container /
E0713 09:13:32.653059   21812 reflector.go:183] watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2417/2287]) [3416]
E0713 09:27:01.526251   21812 reflector.go:183] watch of *api.Service ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [2507/2288]) [3506]
E0713 12:00:57.763924   21812 reflector.go:183] watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [3532/3417]) [4531]
E0713 12:27:07.535133   21812 reflector.go:183] watch of *api.Service ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [3707/3508]) [4706]
E0713 14:43:18.661312   21812 reflector.go:183] watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [4613/4532]) [5612]
E0713 15:24:05.614141   21812 reflector.go:183] watch of *api.Service ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [4886/4707]) [5885]

where is /cgroup directory?
```
$ll /sys/fs/cgroup/
总用量 0
drwxr-xr-x 5 root root  0 3月  20 15:38 blkio
lrwxrwxrwx 1 root root 11 3月  20 15:38 cpu -> cpu,cpuacct
lrwxrwxrwx 1 root root 11 3月  20 15:38 cpuacct -> cpu,cpuacct
drwxr-xr-x 5 root root  0 3月  20 15:38 cpu,cpuacct
drwxr-xr-x 5 root root  0 3月  20 15:38 cpuset
drwxr-xr-x 5 root root  0 3月  20 15:38 devices
drwxr-xr-x 5 root root  0 3月  20 15:38 freezer
drwxr-xr-x 2 root root  0 3月  20 15:38 hugetlb
drwxr-xr-x 5 root root  0 3月  20 15:38 memory
drwxr-xr-x 2 root root  0 3月  20 15:38 net_cls
drwxr-xr-x 5 root root  0 3月  20 15:38 perf_event
drwxr-xr-x 4 root root  0 3月  20 15:38 systemd
```

**Comment by Icedroid** [comment]
rc is created successfully, but no running pods, Who know why this is happen?
```
$kubectl create -f examples/guestbook-go/redis-master-controller.json
replicationcontrollers/redis-master

$ kubectl get rc
CONTROLLER             CONTAINER(S)            IMAGE(S)                    SELECTOR                         REPLICAS
redis-master           redis-master            gurpartap/redis             app=redis,role=master            1

$ kubectl get pods
NAME                        READY     REASON    RESTARTS   AGE
```

I get no any error on the kubelet, controller-manager logs. But the pod not run.

**Comment by Icedroid** [comment]
When start api-server I got these errors:

> /var/log/k8s/kube-apiserver.ERROR 
Log file created at: 2015/07/14 09:50:23
Running on machine: urestful
Binary: Built with gc go1.4.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0714 09:50:23.336410   29675 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0714 09:50:23.336454   29675 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0714 09:50:23.336547   29675 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8888/api/v1/serviceaccounts: dial tcp 0.0.0.0:8888: connection refused
E0714 09:50:23.336628   29675 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
E0714 09:50:23.336603   29675 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0714 09:50:23.336675   29675 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8888/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 0.0.0.0:8888: connection refused

But after api-server started, I run:
```
$ echo $(curl -s http://localhost:8888/healthz)
ok
$ echo $(curl -s http://localhost:8888/api/v1/namespaces)
{ "kind": "NamespaceList", "apiVersion": "v1", "metadata": { "selfLink": "/api/v1/namespaces", "resourceVersion": "13298" }, "items": [ { "metadata": { "name": "default", "selfLink": "/api/v1/namespaces/default", "uid": "1f6ee86c-28b4-11e5-ae6d-5254003ad401", "resourceVersion": "5", "creationTimestamp": "2015-07-12T16:36:19Z" }, "spec": { "finalizers": [ "kubernetes" ] }, "status": { "phase": "Active" } } ] }

```

**Comment by thockin** [comment]
> dial tcp 0.0.0.0:8888: connection refused

0.0.0.0 is obviously wrong.  You're setting some flag somewhere wrongly/.

**Comment by Icedroid** [comment]
@thockin you can see
```
$ ./kube-apiservice --help
--insecure-bind-address=127.0.0.1: The IP address on which to serve the --insecure-port (set to 0.0.0.0 for all interfaces). Defaults to localhost.
```
 So I think 0.0.0.0 is right.

**Comment by thockin** [comment]
> E0714 09:50:23.336410 29675 reflector.go:136] Failed to list
*api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp
0.0.0.0:8888: connection refused

Clearly it's not right or it would work :)

0.0.0.0 is an unspecified IP.  It literally has no meaning in the context
of a connection attempt.  So the mission is to find out what flag is being
mis-used.

**Comment by antoineco** [comment]
Maybe your kubeconfig file points to 0.0.0.0?

Btw, how did you fix the errors you mentioned before ? That could help other people in your case.
```
E0712 17:55:12.594873   22447 kubelet.go:682] Image garbage collection failed: unable to find data for container /

E0712 17:07:20.492353   22996 controllermanager.go:198] Failed to start service controller: ServiceController should not be run without a cloudprovider
```

**Comment by Icedroid** [comment]
@antoineco these error also exists now. But I have the rc running normal.

@thockin  After restart the etcd with as follow: 
```
$./etcd --listen-client-urls 'http://0.0.0.0:4001' \
        --advertise-client-urls 'http://10.10.30.171:4001' \
        --name 'default' \
        --data-dir '/var/lib/etcd/data' 1>>/var/log/etcd.log 2>&1 &

$./kube-apiserver --insecure-bind-address=0.0.0.0 \
        --insecure-port=8888 \
        --etcd-servers=http://127.0.0.1:4001 \
        --kubelet-port=10250 \
        --service-cluster-ip-range=10.254.0.0/16 \
        --log-dir=/var/log/k8s \
        --v=0 \
        --logtostderr=false \
        --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota &
```
then errors:
> the dial tcp 0.0.00.:8888: connection refused 
gone.

**Comment by Icedroid** [comment]
I know why these error happen, It is because admission-control problem, Now I only can use  --admission-control="AlwaysAdmit" 
```
./kube-apiserver --insecure-bind-address=0.0.0.0         --insecure-port=8888         --etcd-servers=http://127.0.0.1:4001         --kubelet-port=10250         --service-cluster-ip-range=10.254.0.0/16         --log-dir=/var/log/k8s         --v=0         --logtostderr=false         --admission-control=NamespaceAutoProvision,LimitRanger,ResourceQuota
```
> E0714 15:34:18.287793   31186 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0714 15:34:18.287843   31186 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0714 15:34:18.287930   31186 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused

**Comment by antoineco** [comment]
I still don't understand what queries the API on 0.0.0.0. What flags are you using to start your controller-manager (and optionally scheduler)?

**Comment by Icedroid** [comment]
@ the queries on 0.0.0.0 which is the same as the --admission-control value.

**Comment by antoineco** [comment]
I meant what flags are you using to start `kube-controller-manager` and `kube-scheduler`? (the complete command)

**Comment by Icedroid** [comment]
```
./kube-scheduler  --master='127.0.0.1:8888'  \
                  --v=0  \
                  --logtostderr=false \
                  --log-dir=/var/log/k8s &
./kube-controller-manager  --v=0 \
        --logtostderr=false \
        --log-dir=/var/log/k8s  \
        --master=127.0.0.1:8888 &
```

**Comment by mbforbes** [comment]
(higher up, but +cc @a-robinson as well for "ServiceController should not be run without a cloudprovider")

**Comment by a-robinson** [comment]
The ServiceController error is nothing to worry about if you're running locally, only if you're running on a cloud where you expect to be able to create external load balancers.

**Comment by goltermann** [comment]
I think all questions have been answered for this issue.  Please reopen or ask on [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes) if you have any further questions.
