### ISSUE TITLE
Unable to build Kubernetes on Ubuntu arm64

### ISSUE THREAD

**Issue by JCzz** [kubernetes/kubernetes#111216]
### What happened?

I am running on Ubuntu and I am trying to build Kubernetes.

After following [documentation](https://github.com/kubernetes/community/blob/master/contributors/devel/development.md) and for local [development](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#cfssl), I have created a script - see script in the section "Install tools" - I get the following errors:

```
go: inconsistent vendoring in /home/ubuntu/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes:
	github.com/cpuguy83/go-md2man/v2@v2.0.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/go-cmp@v0.5.8: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/google/uuid@v1.3.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	github.com/prometheus/client_golang@v1.12.2: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt


To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor

```

Then when running:
`		go mod vendor`

I get a ton of "No such file or directory":

```
make: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes'
make[1]: Entering directory '/home/ubuntu/go/src/k8s.io/kubernetes'
find: ‘vendor/k8s.io/apiextensions-apiserver/examples/client-go/hack’: No such file or directory
find: ‘vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/apis/cr’: No such file or directory
find: ‘vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/apis/cr/v1’: No such file or directory
find: ‘vendor/k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned’: No such file or directory
.......
+++ [0718 14:36:04] Generating prerelease lifecycle code for 26 targets
F0718 14:36:05.722163   43272 status.go:196] Failed loading boilerplate: open : no such file or directory
make[1]: *** [Makefile.generated_files:172: gen_prerelease_lifecycle] Error 1
make[1]: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes'
make: *** [Makefile:528: generated_files] Error 2
make: Leaving directory '/home/ubuntu/go/src/k8s.io/kubernetes'

```

### What did you expect to happen?

A running node

### How can we reproduce it (as minimally and precisely as possible)?

Use multipass to spin up Ubuntu

### Kubernetes version

Latest, just git clone

### Cloud provider

export KUBERNETES_PROVIDER=local

### OS version

# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux k8s 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:05:39 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

### Install tools

```
sudo apt-get update
sudo apt install -y make build-essential make gcc socat

sudo snap install go --classic
export PATH=$PATH:$(go env GOPATH)/bin
export GOPATH=$(go env GOPATH)

go get -u github.com/cloudflare/cfssl/cmd/...

git clone --depth 1 https://github.com/kubernetes/kubernetes $GOPATH/src/k8s.io/kubernetes
cd $GOPATH/src/k8s.io/kubernetes

./hack/install-etcd.sh
export PATH="/home/ubuntu/go/src/k8s.io/kubernetes/third_party/etcd:${PATH}"

export CONTAINER_RUNTIME_ENDPOINT="unix:///run/containerd/containerd.sock"
export KUBERNETES_PROVIDER=local
./hack/local-up-cluster.sh

```
### Container runtime (CRI) and version (if applicable)

sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

**Comment by Shubham82** [comment]
Hi @JCzz 
I think that go.mod is not consistent with `vendor/modules.txt`. 
Can you run `go mod tidy` to ensure that the go.mod file matches the source code in the module and then run `go mod vendor` to copy imported packages into vendor directory and update vendor/modules.txt.

Hope so this will help you and resolve your issue.

**Comment by JCzz** [comment]
Hi and thanks @Shubham82 

Good suggestion, but still facing the same errors. But strange enough `go install github.com/cloudflare/cfssl/cmd/...@latest` gets me to `No resources found` as described above... hmm
