### ISSUE TITLE
Kube scheduler uses legacy events API when bootstraping a new node

### ISSUE THREAD

**Issue by alex-matei** [kubernetes/kubernetes#111217]
### What happened?

Kube-scheduler doesn't have the ClusterRoleBinding needed when starting for the first time:
<details>

```
I0718 11:36:54.342302       1 round_trippers.go:466] curl -v -XGET  -H "Accept: application/vnd.kubernetes.protobuf, */*" -H "User-Agent: kube-scheduler/v1.24.2 (linux/amd64) kubernetes/f66044f/scheduler" 'https://172.31.14.173:6443/apis/events.k8s.io/v1'
I0718 11:36:54.342559       1 round_trippers.go:510] HTTP Trace: Dial to tcp:172.31.14.173:6443 succeed
I0718 11:36:54.353852       1 round_trippers.go:553] GET https://172.31.14.173:6443/apis/events.k8s.io/v1 403 Forbidden in 11 milliseconds
```

</details>

Because of this events.NewEventBroadcasterAdapter defaults to using the legacy API for reporting events.

### What did you expect to happen?

Kube-scheduler should use the new events api.

### How can we reproduce it (as minimally and precisely as possible)?

Use kubeadm to init a cluster made of a single master node. Create a pod and look at `kubectl get events -o yaml` for the scheduled events. EventTime field should be used instead of FirstTimestamp/LastTimestamp. If you restart kube-scheduler it will use the new API.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:15:38Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
self-manager cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
Kube scheduler is using the new event API but with a fallback mode, if events.k8s.io/v1beta1(I guess it's v1 now) is disabled, we'll use `core/v1 Events` then. 
see https://github.com/kubernetes/kubernetes/pull/83692

**Comment by kerthcet** [comment]
I guess kube scheduler is using the new API refer to https://github.com/kubernetes/kubernetes/pull/83692, have you checked that.
