### ISSUE TITLE
Failure cluster [57160070...] flakiness in TestPriorityAndFairnessWithPanicRecoveryAndTimeoutFilter

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#111298]
##### Error text:
```
=== RUN   TestPriorityAndFairnessWithPanicRecoveryAndTimeoutFilter
--- FAIL: TestPriorityAndFairnessWithPanicRecoveryAndTimeoutFilter (0.16s)

```
#### Recent failures:
[7/20/2022, 12:16:28 PM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111060/pull-kubernetes-unit/1549789723151568896)
[7/20/2022, 11:22:47 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111090/pull-kubernetes-unit/1549776269187485696)
[7/20/2022, 9:43:42 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111239/pull-kubernetes-unit/1549751361598394368)
[7/20/2022, 8:54:12 AM pr:pull-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111254/pull-kubernetes-unit/1549738674818650112)
[7/20/2022, 8:17:14 AM ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1549729684906840064)

/kind failing-test

**Comment by dims** [comment]
encountered when i was trying golang 1.19 rc2, it's possible that i saw more failures than what we have in CI jobs currently under golang 1.19

Same 2 tests failed in 3 of the runs ( see #111254 ) :
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111254/pull-kubernetes-unit/1549738674818650112
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111254/pull-kubernetes-unit/1549533669935288320
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/111254/pull-kubernetes-unit/1549478672606433280





[2:14](https://kubernetes.slack.com/archives/CHGFYJVAN/p1658340847125539)

**Comment by MadhavJivrajani** [comment]
Dup of https://github.com/kubernetes/kubernetes/issues/111154?

**Comment by markyjackson-taulia** [comment]
Hello @dims, my name is Marky Jackson and I am one of the k8s 1.25 bug triage shadow assigned to track this body of work. Is this still on track for 1.25?

**Comment by MadhavJivrajani** [comment]
@markyjackson-taulia 👋
This should be fixed now that https://github.com/kubernetes/kubernetes/pull/111162 is merged :D

**Comment by markyjackson-taulia** [comment]
@MadhavJivrajani awesome, if that is the case, kindly close this issue and I will mark it as completed

**Comment by MadhavJivrajani** [comment]
Closing issue after checking [k8s-triage](https://storage.googleapis.com/k8s-triage/index.html?date=2022-07-24&sig=api-machinery) and [testgrid](https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit) to ensure test is passing.

@markyjackson-taulia, will make sure to ping you in case this acts up again and the issue is re-opened.
/close

**Comment by varshadeshmane92** [comment]
I observed this test case flaking again:
https://prow.k8s.io/view/gs/kubernetes-ci-logs/logs/ci-kubernetes-unit/1953165827373010944

Test Name: TestPriorityAndFairnessWithPanicRecoveryAndTimeoutFilter
Package: k8s.io/apiserver/pkg/server: filters

It failed with the same error as previously reported:
We see this flake in triage:

https://storage.googleapis.com/k8s-triage/index.html?date=2025-08-02&text=TestPriorityAndFairnessWithPanicRecoveryAndTimeoutFilter&test=k8s.io%2Fapiserver%2Fpkg%2Fserver%2Ffilters
