### ISSUE TITLE
Allow configuration of etcd healthcheck in kube-apiserver

### ISSUE THREAD

**Issue by aleksandra-malinowska** [kubernetes/kubernetes#111290]
### What would you like to be added?

* Allow configuring separate etcd healthcheck timeouts for kube-apiserver's /readyz and /livez. 
* Allow disabling etcd healthcheck entirely in /livez.

### Why is this needed?

This is needed for more graceful degradation of kube-apiserver's performance when the control plane is overloaded.

Overloaded control plane can result in etcd slowness, and /readyz can be used to redirect traffic from it and allow it to recover. However, with failing /livez, kube-apiserver will soon be restarted by liveness probe anyway.

It might also be useful to stop liveness probe from restarting kube-apiserver at all when etcd is slow. Restarting kube-apiserver is unlikely to resolve problems with etcd, and can introduce extra disruption when kube-apiserver's performance is degraded.

**Comment by mborsz** [comment]
Personally I would treat this more as a bug: the fact that kube-apiserver liveness check fails when etcd is responding in e.g. 2.1s (which can happen when it's overloaded or during leader election) is a bad behavior and should be fixed. If we want to check if etcd is alive, timeout like 15s should be used with logic "if it hasn't responded in 15s, will probably never respond" (see similar discussion in https://github.com/kubernetes/kubernetes/pull/97034).

OTOH using 2s timeout in readyz seems to be fine -- if etcd is overloaded we may want to reduce number of requests going to kube-apiserver and then to etcd.

I see at least three solutions here:
1. remove etcd check completely from livenessProbe (why we should restart kube-apiserver e.g. if etcd has no leader) and keep it in readyz only with 2s timeout.
   * There is a concern of backward compatibility. If someone relies on "GET /livez/etcd" or fact that kube-apiserver's /livez checks etcd healthiness it may need to actively adjust health checking logic after this change. We may want to add a flag disabling etcd check in livez (and keeping in readyz) and keep the default as it was in the past.
1. Make "etcd" check in livez use different timeout than the "etcd" check in readyz. This seems to be violating rule that readyz is superset of livez (how kube-apiserver can be ready to serve requests if it's not alive) as the "etcd" in readyz is not the same as in livez and probably can be slightly misleading when e.g. the same check is failing in readyz and passing in livez.
1. Keep "etcd" check in both livez and readyz as they are (and increase timeout there to e.g. 15s to make it more "liveness etcd" check) and add a copy of etcd check ("etcd-readiness"?) to readyz only with 2s timeout. This seems to be more explicit than idea in 2 ("etcd" check keeps the same meaning in both livez and readyz).

Personally I would go for 1. as it seems like etcd downtime should be rarely a reason for restarting kube-apiserver. The most common cases when etcd is not responsive (from my limited experience) are: 
* etcd has no leader
* etcd is dead
* kube-apiserver has incorrect etcd client configuration
* kube-apiserver <-> etcd connectivity issue

In none of the cases, restart of kube-apiserver seems to be right action to do. Instead we kube-apiserver should be alive and raise the connectivity issue with failing /readyz.

/cc @serathius as we discussed this recently.

**Comment by wojtek-t** [comment]
Thanks @mborsz for thinking about the options - those all makes a lot of sense. I agree that (2) seems like the worst option.

I'm somewhat on the fence between (1) and (3).
- I agree that in huge majority of cases (1) makes sense. But I think there might be some pathological cases where some network issues result in kube-apiserver not being able to connect to etcd and restarting that might in theory help. Making that optional helps, but I'm still thinking if we can't do better.

- OTOH, the option (3) sounds strange from the first glance (what's the point of making the same call twice with different timeouts as part of readyz/). But thinking more about that - maybe actually that's not ridiculous. 
The reason why we're doing what we're doing is that etcd only has "healthz" and doesn't expose a concept of livez/ and readyz/
But in the ideal world, what I would do is basically:
- kube-apiserver livez/ calling etcd livez/
- kube-apiserver readyz/ calling etcd readyz/ (calling livez/ additionally here wouldn't hurt too)

Looking from that perspective, we can treat calling "etcd healthz with timeout=15s" as "etcd livez" and calling "etcd healthz with timeout=2s" as "etcd readyz" (until etcd exposes to concept more explicitly).

So from that perspective, I think I'm slightly more on the side of option (3) actually. Thoughts?

**Comment by mborsz** [comment]
> But I think there might be some pathological cases where some network issues result in kube-apiserver not being able to connect to etcd and restarting that might in theory help.

If etcd client/kube-apiserver is not able to recover after the network issue, this probably means that it's a bug which we should fix. But I think the risk of discovering such bugs is real: we have seen similar issues in the past (e.g. I "use of closed network connection" kubelet), so if we pick (1) we should reserve some additional time for extended testing and potentially fixing such issues.

Overall, I think that (1) has better result, but is much more risky as we can discover issue like that and probably fix some healthchecking/repair infra to stop relying on fact that /livez checks etcd as well.

(3) seems to be straightforward and safe solution OTOH.

So overall, given that (3) is good enough for the problem we are facing and seems to be much cheaper (in terms of risk, required testing, healthchecking/repair infra changes needed to adjust to that) I recommend going with (3). 

We can always revise the decision and do (1) after (3) (aka add a flag to disable livez-like "etcd" healthcheck and keep only "etcd-readiness"), if we find a good enough reason to do so.

Side note: Please note that the etcd check that is part of livez/readyz in kube-apiserver is not calling etcd's "/health" endpoint (healthz), rather it tries to get key "/health" with fixed timeout and I think it's a good thing: the etcd's /health endpoint is very readyz-like: it fetches object with hardcoded 1s timeout (see similar discussion in https://github.com/kubernetes/kubernetes/pull/97034).

@aleksandra-malinowska could you prepare a PR for (3) option in https://github.com/kubernetes/kubernetes/issues/111290#issuecomment-1191169063?
