### ISSUE TITLE
GetPodIPs has bug：For a dual stack environment, if only one type of ip address is obtained, it will also return directly, not report error and not retry

### ISSUE THREAD

**Issue by mysunshine92** [kubernetes/kubernetes#111234]
### What happened?

For function GetPodIPs：
in  a dual stack environment，executing the nsenter command to first obtain the ipv4 address, and then obtain the ipv6 address.if only one type of ip address is obtained, it will also return directly, not report error and not retry.

In our  dual stack environment：
an error occurred when obtaining the ipv4 address, and only the ipv6 address was obtained. podIPs show belows：

The podIP address:
[root@r5930-r1-s1:/home/vtu]$ kubectl get pod -A -o wide |grep "::"
admin         sc-li-oam-dba-0-0-1-0                              1/1     Running   1          3d7h    1111:0:0:5::db   r5930-r1-s2   <none>           <none>
admin         sc-upf-ipm-mp-0-0-1-1                              1/1     Running   1          3d7h    1111:0:0:5::dd   r5930-r1-s2   <none>           <none>

The podIP for sc-upf-ipm-mp-0-0-1-1：
 hostIP: 192.168.9.12
  phase: Running
  podIP: 1111:0:0:5::db
  podIPs:
  - ip: 1111:0:0:5::db
  qosClass: Burstable
  startTime: "2022-07-14T06:45:07Z"

For pod: sc-upf-ipm-mp-0-0-1-1, the current call to nsenter returns normal：
[root@r5930-r1-s2:~]$ docker ps |grep sc-upf-ipm-mp-0-0-1-1
c5b970673aa5        01bd48448dee                                                                                                        "/bin/bash /home/s..."   25 hours ago        Up 25 hours                                                                                                                               k8s_vru-upf-ipm-mp_sc-upf-ipm-mp-0-0-1-1_admin_aa4ceb1a-1a36-4aa7-9353-a4bfc8ba0612_1

4174fd10f4b6        swr:2512/admin/op-containers-pause:v1.21.20.06.9093018                                                              "/pause"                 25 hours ago        Up 25 hours                                                                                                                               k8s_POD_sc-upf-ipm-mp-0-0-1-1_admin_aa4ceb1a-1a36-4aa7-9353-a4bfc8ba0612_12

[root@r5930-r1-s2:~]$ docker inspect c5b970673aa5 |grep Pid
            "Pid": 56316,
            "PidMode": "",
            "PidsLimit": 0,

[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -4 addr show dev eth0 scope global
3: eth0    inet 192.169.5.221/24 brd 192.169.5.255 scope global eth0\       valid_lft forever preferred_lft forever

[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -6 addr show dev eth0 scope global
3: eth0    inet6 1111:0:0:5::dd/64 scope global \       valid_lft forever preferred_lft forever

### What did you expect to happen?

For a dual stack environment, podIPs should have two addresses, one for ipv4 and one for ipv6.

If we fail to obtain the ipv4 or ipv6 address, we should record the logging and retry to obtain ip，ensure that two addresses can be obtained.

### How can we reproduce it (as minimally and precisely as possible)?

Occasional problems.
requirement：There are many containers in the environment，and reboot node

### Kubernetes version

<details>

```console
$ kubectl version：1.22.3
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mysunshine92** [comment]
cc @neolit123

**Comment by neolit123** [comment]
in which part of the codebase is the function GetPodIPs?

**Comment by aojea** [comment]
/remove-kind bug
/kind support

podIPs are assigned by the CNI, you are not providing that information.

Also, your command shows you are using docker, that has been deprecated and removed recently.

**Comment by mysunshine92** [comment]
> [root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -4 addr show dev eth0 scope global 3: eth0 inet 192.169.5.221/24 brd 192.169.5.255 scope global eth0\ valid_lft forever preferred_lft forever
> 
> [root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -6 addr show dev eth0 scope global 3: eth0 inet6 1111:0:0:5::dd/64 scope global \ valid_lft forever preferred_lft forever

CNI assign correctly，shows below：
[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -4 addr show dev eth0 scope global
3: eth0 inet 192.169.5.221/24 brd 192.169.5.255 scope global eth0\ valid_lft forever preferred_lft forever

[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -6 addr show dev eth0 scope global
3: eth0 inet6 1111:0:0:5::dd/64 scope global \ valid_lft forever preferred_lft forever

**Comment by mysunshine92** [comment]
> in which part of the codebase is the function GetPodIPs?

k8s version：1.22.3
pkg\kubelet\dockershim\network\plugins.go

getIPs -> getIPsFromPlugin -> GetPodNetworkStatus -> GetPodNetworkStatus(cniNetworkPlugin) -> GetPodNetworkStatus ->  GetPodIPs -> getOnePodIP

**Comment by mysunshine92** [comment]
> /remove-kind bug /kind support
> 
> podIPs are assigned by the CNI, you are not providing that information.
> 
> Also, your command shows you are using docker, that has been deprecated and removed recently.

CNI assign correctly，shows below：
[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -4 addr show dev eth0 scope global
3: eth0 inet 192.169.5.221/24 brd 192.169.5.255 scope global eth0\ valid_lft forever preferred_lft forever

[root@r5930-r1-s2:~]$ nsenter --net=/proc/56316/ns/net -F -- ip -o -6 addr show dev eth0 scope global
3: eth0 inet6 1111:0:0:5::dd/64 scope global \ valid_lft forever preferred_lft forever

**Comment by aojea** [comment]
I see, thanks for the info, but dockershim has been deprecated in 1.20, and that codepath is not supported for dual-stack

https://kubernetes.io/blog/2020/12/02/dockershim-faq/

You should switch to containerd or crio-o , or other supported container runtime

**Comment by mysunshine92** [comment]
> I see, thanks for the info, but dockershim has been deprecated in 1.20, and that codepath is not supported for dual-stack
> 
> https://kubernetes.io/blog/2020/12/02/dockershim-faq/
> 
> You should switch to containerd or crio-o , or other supported container runtime

But for k8s version: 1.22.3, we are still using dockershim, why not fix this bug?

**Comment by aojea** [comment]
> But for k8s version: 1.22.3, we are still using dockershim, why not fix this bug?

The deprecation was announced in 1.20, I can't remember the exact reason, but it's possible it didn't receive new features since then

**Comment by aojea** [comment]
this only applies to dockershim, that was deprecated and removed in 1.22, it is not going to be fixed

**Comment by SergeyKanzhelev** [comment]
/close

1.23 - the last version with dockershim is out of support now by Kubernetes OSS
