### ISSUE TITLE
Go modules not tagged for v0.25.0-alpha.3

### ISSUE THREAD

**Issue by frezbo** [kubernetes/kubernetes#111353]
### What happened?

There is a github release for v1.25.0-alpha.3 but no go modules are tagged for [v0.25.0-alpha.3](https://pkg.go.dev/k8s.io/api?tab=versions)

### What did you expect to happen?

Go modules tagged for v0.25.0-alpha.3

### How can we reproduce it (as minimally and precisely as possible)?

```bash
❯ go get k8s.io/api@v0.25.0-alpha.3
go: k8s.io/api@v0.25.0-alpha.3: invalid version: unknown revision v0.25.0-alpha.3
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
works now

```
[dims@dims-m1-7728 16:03] ~/junk ⟩ go get k8s.io/api@v0.25.0-alpha.3
go: downloading k8s.io/api v0.25.0-alpha.3
go: added k8s.io/api v0.25.0-alpha.3
```

**Comment by frezbo** [comment]
Thanks @dims :heart:

**Comment by frezbo** [comment]
On a side note, have seen this happen a few times, there would be a release but no corresponding go tags. Is this issue with an automated process? If it's something trivial to fix, if you could point me in the right direction i could look at fixing it.

**Comment by dims** [comment]
@frezbo please see https://github.com/kubernetes/publishing-bot
