### ISSUE TITLE
enforce PreXXXXX and XXXXX phase of the same plugin to be enabled/disabled altogether 

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#111309]
### What would you like to be added?

It might be nice if we could enforce PreXXXXX and XXXXX phase of the same plugin to be enabled/disabled altogether to prevent users from mistakes in the configuration of Plugins.

### Why is this needed?

Like `PreFilter` and `Filter` plugin, `PreXXXXX` and `XXXXX` phase of each plugin should be basically enabled/disabled together. But, currently, users can enable either of them if they want (I mean we don't prohibit activating only one of them in the plugin config.)

Currently, some plugins (e.g. [NodeAffinity](https://github.com/kubernetes/kubernetes/blob/5108b0a3a0a9622a69fcd1fb3d78de77e6c3d7cb/pkg/scheduler/framework/plugins/nodeaffinity/node_affinity.go#L154-L159)) can work even when it's only enabled in Filter. 
But, some plugins(e.g. [TopologySpread](https://github.com/kubernetes/kubernetes/blob/5108b0a3a0a9622a69fcd1fb3d78de77e6c3d7cb/pkg/scheduler/framework/plugins/podtopologyspread/filtering.go#L341-L344)) cannot work. Given we haven't got any issue to complain about those plugins so far (AFAIK), I think probably few people are using Filter plugin without PreFIlter phase.

Are there any cases that users need to enable only PreFilter or Filter?

Discussion: https://github.com/kubernetes/kubernetes/pull/111212#discussion_r923318022

**Comment by ahg-g** [comment]
I am against this proposal.

Multipoint was introduced to simplify scheduler configuration and make users think of plugins instead of extension points.

**Comment by sanposhiho** [comment]
Discussion in https://github.com/kubernetes/kubernetes/pull/111212#discussion_r923318022 makes sense to me, let me close it.

/close
