### ISSUE TITLE
proposal: create a alias group for scheduler team

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#111392]
### What would you like to be added?

A alias group which includes all the active contributors for sig-scheduling.

### Why is this needed?

scheduler have four approvers and four reviewers, as far as I know, there is no such alias group for those active contributors, there should be but it is quite outdated.

we usually don't know which one has interesting in a specific topics, or has the bandwidth to help review PRs etc. this require us to ping each of them to get some feedbacks, this is not efficient and we definitely miss someone who is really willing to offer some helps sometimes. 

Create such a alias group will help to notify all the active contributors, and make sure all of them could be better involved in this sig.

@alculquicondor @Huang-Wei @ahg-g @damemi @denkensk @sanposhiho @kerthcet

**Comment by kerthcet** [comment]
Borrow from sig-node, https://github.com/orgs/kubernetes/projects/49#card-78787252 will this helpful? No longer frequently `kindly ping`.

**Comment by alculquicondor** [comment]
I think this would be useful. Not sure who to ask. Maybe @mrbobbytables can help set it up?

**Comment by ahg-g** [comment]
> A alias group 

I assume you mean a github one, not a mailing list; if so, +1. I also likeHaving a project under 

> we usually don't know which one has interesting in a specific topics, or has the bandwidth to help review PRs etc. this require us to ping each of them to get some feedbacks, this is not efficient and we definitely miss someone who is really willing to offer some helps sometimes.

I think we need to more consistently do triage during sig meetings to address this issue. I also like the idea of having a sig scheduling project under https://github.com/orgs/kubernetes/projects?type=classic to track and classify active PRs

**Comment by mrbobbytables** [comment]
If you're looking for a GitHub group - you can create/update them here:
https://github.com/kubernetes/org/blob/main/config/kubernetes/sig-scheduling/teams.yaml
The current sig-scheduling groups look to be quite outdated and probably worth pruning down to a set of teams that are actually being used. Would also need to update the list of teams in sigs.yaml here:

https://github.com/kubernetes/community/blob/44b42ec04048fc0b131d638219bc9840f4378429/sigs.yaml#L2371-L2385



> I think we need to more consistently do triage during sig meetings to address this issue. I also like the idea of having a sig scheduling project under https://github.com/orgs/kubernetes/projects?type=classic to track and classify active PRs


Triage boards are useful, but kind of a pain to keep up to date right now - theres a prow job thats being worked on for the release team (cc @helayoty @Priyankasaggu11929) that might you might be able to copy with the right criteria.

**Comment by Huang-Wei** [comment]
I used to think about using the Github Project feature to standardize scheduler's issue triage process. And I'm +1 to make issue triage as a regular portion of each sig-meetings.

(BTW: I created a Project at https://github.com/orgs/kubernetes/projects/79, note this is a beta Github Project, not classic one. Maybe @helayoty @PriyankaH21 can shed some light on the direction of using beta Project vs. classic Project)

Back to this issue, I can clean up [kubernetes/community@44b42ec/sigs.yaml#L2371-L2385](https://github.com/kubernetes/community/blob/44b42ec04048fc0b131d638219bc9840f4378429/sigs.yaml#L2371-L2385) a bit, which is way outdated.

**Comment by chendave** [comment]
> I assume you mean a github one, not a mailing list; if so, +1.

yes, that is what I meant.


>Back to this issue, I can clean up [kubernetes/community@44b42ec/sigs.yaml#L2371-L2385](https://github.com/kubernetes/community/blob/44b42ec04048fc0b131d638219bc9840f4378429/sigs.yaml#L2371-L2385) a bit, which is way outdated.

@Huang-Wei  thanks for the cleanup!

**Comment by kerthcet** [comment]
> (BTW: I created a Project at https://github.com/orgs/kubernetes/projects/79, note this is a beta Github Project, not classic one. Maybe @helayoty @PriyankaH21 can shed some light on the direction of using beta Project vs. classic Project)


Updated the Kanban with least recently updated PRs, but still need some helps to make this working smoothly.
