### ISSUE TITLE
kubectl apply ports changes broken

### ISSUE THREAD

**Issue by champtar** [kubernetes/kubernetes#111304]
### What happened?

Trying to add a TCP port to a Deployment with the matching UDP port, there is no errors but Deployment is not modified

### What did you expect to happen?

it works

### How can we reproduce it (as minimally and precisely as possible)?

Here 3 Deployments yaml
[0.txt](https://github.com/kubernetes/kubernetes/files/9155974/0.txt) = 0 port
[1.txt](https://github.com/kubernetes/kubernetes/files/9155975/1.txt) = 1 port, 2345/udp
[2.txt](https://github.com/kubernetes/kubernetes/files/9155976/2.txt) = 2 ports, 2345/udp 2345/tcp

To check the current state of the deployment I use
```
kubectl get deploy test-port -o json | jq .spec.template.spec.containers[0].ports
```

### Test 1
```
kubectl delete deploy test-port
kubectl apply -f 0.txt
# 0 ports
kubectl apply -f 1.txt
# 1 port, 2345/udp
kubectl apply -f 2.txt
# 1 port, 2345/udp (wrong)
```
### Test 2
```
kubectl delete deploy test-port
kubectl apply -f 0.txt
# 0 ports
kubectl apply -f 2.txt
# 2 ports, 2345/udp 2345/tcp
kubectl apply -f 1.txt
# 0 ports (wrong)
```
### Test 3
With server side apply it seems to work ok
```
kubectl delete deploy test-port
kubectl apply --server-side -f 0.txt
# 0 ports
kubectl apply --server-side -f 2.txt
# 2 ports, 2345/udp 2345/tcp
kubectl apply --server-side -f 1.txt
# 1 port, 2345/udp
kubectl apply --server-side -f 0.txt
# 0 ports
kubectl apply --server-side -f 1.txt
# 1 port, 2345/udp
kubectl apply --server-side -f 2.txt
# 2 ports, 2345/udp 2345/tcp
```

### Anything else we need to know?

I started this investigation as I saw on a cluster a pod with different ports than his parent deployment (deleting the pod fixed the issue)
Was not able to reproduce it yet.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

bare metal

### OS version

N/A

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by pacoxu** [comment]
sounds like https://github.com/kubernetes/kubernetes/issues/39188

**Comment by muyangren2** [comment]
To modify the port, you need to delete the pod and restart it to take effect
or
Use kubectl edit modify  it

**Comment by champtar** [comment]
> sounds like #39188

I though using named ports was enough, but yeah maybe we can just treat this ticket as duplicate

**Comment by champtar** [comment]
> To modify the port, you need to delete the pod and restart it to take effect or Use kubectl edit modify it

I have some scripts generating the yaml and applying them using `kubectl apply -f`, delete then apply is kind of the nuclear option, i'll start with SSA
