### ISSUE TITLE
Yum repo only has kubectl...kubeadm and kubelet are missing?

### ISSUE THREAD

**Issue by dankirkpatrick** [kubernetes/kubernetes#111326]
### What happened?

Running this to get a list of available versions, I see only kubectl and rkt, but no kubelet or kubeadm.  

%  yum list --disablerepo='*' --enablerepo=kubernetes --showduplicates --disableexcludes=kubernetes
^^^ this returns all of the versions of kubectl, and 3 versions of rkt, but nothing for kubeadm or kubelet

My repo definition:
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

### What did you expect to happen?

The list returned from the repo should include kubelet and kubeadm 

### How can we reproduce it (as minimally and precisely as possible)?

Using my kubernetes repo definition, run:

 yum list --disablerepo='*' --enablerepo=kubernetes --showduplicates --disableexcludes=kubernetes

<should see many kubectl, kubeadm, and kubelet versions>

### Anything else we need to know?

Surely this is pebcak?  What am I doing incorrectly?

### Kubernetes version

<details>
This is using yum, not kubernetes yet. 

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
On-premises
</details>

### OS version

<details>
CentOS 7

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux kmaster1 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>
yum version

Loaded plugins: fastestmirror, versionlock
Installed: 7/x86_64                                                                           471:f725bd36b29cfa0b3d880030bdd9a78c0f4cc1b6
Group-Installed: yum                                                                           14:207dff9f76c98374baef39b5939ea3353f6b5687
version

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
i don't think the k8s project is even packaging rkt, which suggests that you might be trying to use a different repository somehow.

**Comment by neolit123** [comment]
try asking for help on the support channels

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
