### ISSUE TITLE
Restarting Informers is not possible anymore

### ISSUE THREAD

**Issue by nammn** [kubernetes/kubernetes#111310]
### What happened?

- [PR](https://github.com/kubernetes/kubernetes/pull/104853) introduced a check `hasStarted()` which stops the same informer being run twice. 
- If you stop the informer with the provided [stopCh ](https://github.com/kubernetes/kubernetes/blame/f4046f9e6d0bb2fc4fa2d84af64cc9c6db44270a/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L160) one stops the run and I believe all the linked watchers/listeners. That also sets stopped to [true](https://github.com/kubernetes/kubernetes/blame/f4046f9e6d0bb2fc4fa2d84af64cc9c6db44270a/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L441)
- Running the informer again (after closing the stop channel) returns "The sharedIndexInformer has started, run more than once is not allowed"

### What did you expect to happen?

- to be able to start the informer again once we have closed it

### How can we reproduce it (as minimally and precisely as possible)?

```
	client := fake.NewSimpleClientset()
	informerFactory := informers.NewSharedInformerFactory(client, 0)
	nodeInformer := informerFactory.Core().V1().Nodes().Informer()
        stop := make(chan struct{})
	go nodeInformer.Run(stop)
        close(stop) //. close it
        time.Sleep(5*time.Second)
	go nodeInformer.Run(stop) // run it again
```

### Anything else we need to know?

- Is this expected? If not, would setting started to false once we close the stop channel a viable approach?
- Alternatively, is there a proper way to stop the informers and start them up again?

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by leilajal** [comment]
/assign @alexzielenski 
@neolit123 : expect delay in response due to code freeze
/triage accepted

**Comment by alexzielenski** [comment]
I looked into the history from the PR you linked. This seems to be the intended behavior of sharedindexinformer. I don't see this as a regression: 

The original shared informer did not support being Run more than once. The fact that `Run` function was missing logic to enforce this seems simply to have been an oversight. Calling `Run` more than once on a sharedindexinformer could cause bugs.

For example, the SharedInformer did not allow you to call `AddIndexer` if `started` was ever true, but there was never logic to set `started` to false:

https://github.com/kubernetes/kubernetes/pull/104853/files#diff-10a340e966883e5205df63ad90ba6827f38f8a8d4b8614152c0baae9813a56c6R455

and similarly for `stopped`. I'm sure there is other state not being managed with restarting the informer in mind.

Two courses of action for you if you would like this behavior:

1. If your client relied on the restartable functionality of SharedIndexInformer, re-creating the SharedIndexInformer instances may work for you/

2. It may be possible to add support for the functionality through a refactor of the SharedIndexInformer, so community contributions in that direction are welcome; but the task would not be as simple as removing the check added by #104853. It may require not only a refactor of SharedIndexInformer but also I am not sure if its components like the `Controller`, `processor`, etc. support being restarted so attention would need to be paid to these details.

**Comment by alexzielenski** [comment]
/close

please reopen if you think there is more to discuss
