### ISSUE TITLE
Typo in `kubectl delete --help`

### ISSUE THREAD

**Issue by relandrew** [kubernetes/kubernetes#111302]
### What happened?

`kubectl delete --help` shows a sample invocation saying that to delete all the resources in some files, to run `apply`; I believe this to be incorrect.

`apply` on line https://github.com/kubernetes/kubernetes/blob/eb2f56c638b393fd589f4bda7b7b84d4d2ccfbdf/staging/src/k8s.io/kubectl/pkg/cmd/delete/delete.go#L87 should likely be changed to `delete`

### What did you expect to happen?

See above

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

github

### Cloud provider

n/a

**Comment by brianpursley** [comment]
Closed by https://github.com/kubernetes/kubernetes/pull/111315

/close
