### ISSUE TITLE
How to set multiple nodeport ranges ？ 

### ISSUE THREAD

**Issue by ivanmissu** [kubernetes/kubernetes#111318]
Now I want to open ports 80，443 and 30000 to 32727. How to configure it? Can I set multiple ranges of ports ？？？
/sig apps
/sig network

**Comment by dcbw** [comment]
If you are talking about the `service-node-port-range` argument to the Kube apiserver, then no it does not currently support multiple port ranges.

**Comment by ivanmissu** [comment]
> If you are talking about the `service-node-port-range` argument to the Kube apiserver, then no it does not currently support multiple port ranges.

Is there a support plan ？

**Comment by danwinship** [comment]
No.

Note that NodePort is a low-level feature which is mostly there as part of the implementation of LoadBalancer services. NodePort values are supposed to be random; there's no expectation that the user should be able to get the "right" NodePort value for a particular service.

If you want a service to be externally available on a specific port, you should look at LoadBalancer services or ExternalIP.

/close
