### ISSUE TITLE
Master disruption mode in nodeLifeCycleController not work at sometimes

### ISSUE THREAD

**Issue by LastNight1997** [kubernetes/kubernetes#111385]
### What happened?

When the cluster enter master disruption mode, there are still nodes marked with NoExecute taint.

### What did you expect to happen?

No Nodes are marked with NoExecute taint when the cluster enter master disruption mode.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a k8s cluster with only one worker node (ControllerManager run with TaintManager as default).
2. Stop the kubelet in the node to make it NotReady and enter master disruption mode.
3. The node could still be marked with NoExecute taint at occasionally.

### Anything else we need to know?

when I looks into the code in nodeLifeCycleController, I find the it may happen in this case:
1. In the periodically running function monitorNodeHealth, processTaintBaseEviction method will marks the node with taint. It will finally add the node to zoneNoExecuteTainter queue.
https://github.com/kubernetes/kubernetes/blob/5f6b60bb1323a60f59119e315ac52b8a453a3939/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L830-L832
https://github.com/kubernetes/kubernetes/blob/5f6b60bb1323a60f59119e315ac52b8a453a3939/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1462
2. The zoneNoExecuteTainter dealed with the node and marked it  with NoExecute taint before monitorNodeHealth run the handleDisruption function.
3. Call the handleDisruption function, while the params "nodes" in handleDisruption function was the cache of nodeList got before node was marked. And In the function, it won't RemoveTaintOffNode actually because the node in cache didn't have NoExecute taint and zoneNoExecuteTainter had finished the mark work.
https://github.com/kubernetes/kubernetes/blob/5f6b60bb1323a60f59119e315ac52b8a453a3939/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L854
https://github.com/kubernetes/kubernetes/blob/5f6b60bb1323a60f59119e315ac52b8a453a3939/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L1165-L1184
4. the NoExecute taint in the node still exists until the node ready.

logs:
1. The node  was add to Taint queue in 04:10:18.065401.

> I0721 04:10:18.065401       1 node_lifecycle_controller.go:885] Node 192.168.36.0 is unresponsive as of 2022-07-21 04:10:18.065391528 +0800 CST m=+11493.921139592. Adding it to the Taint queue.

2. watched the node update event, the node had been marked with NoExecute taints in 04:10:18.080782

> I0721 04:10:18.080782       1 taint_manager.go:435] Noticed node update: scheduler.nodeUpdateItem{nodeName:"192.168.36.0"}
I0721 04:10:18.080801       1 taint_manager.go:440] Updating known taints on node 192.168.36.0: [{node.kubernetes.io/unreachable  NoExecute 2022-07-21 04:10:18 +0800 CST}]

3. enter master disruption mode in 04:10:18.080907

> I0721 04:10:18.080907       1 node_lifecycle_controller.go:1195] Controller detected that all Nodes are not-Ready. Entering master disruption mode.

4. node_lifecycle_manager detected that node was ready again at 04:15:13.108502, delete Taint.

> I0721 04:15:13.108502       1 node_lifecycle_controller.go:1078] Node 192.168.36.0 ReadyCondition updated. Updating timestamp.
I0721 04:15:13.115877       1 node_lifecycle_controller.go:896] Node 192.168.36.0 is healthy again, removing all taints

5. exiting master disruption mode

> I0721 04:15:13.116132       1 node_lifecycle_controller.go:1222] Controller detected that some Nodes are Ready. Exiting master disruption mode.

As can be seen from the above timeline, from 04:10:18.065401 to 04:15:13.108502, the NoExecute taint in the node still existed even if the cluster had entered master disruption mode.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Irrelevant
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux ncb207eersfenhcq73ipg 5.4.56-1-velinux1u2-amd64 #velinux1u2 SMP Debian 5.4.56-1-velinux1u2 Sat Mar 19 03:30:27 U x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
I'm a little confused, while a node's Ready condition becomes Unknown or False, then notifies zoneNoExecuteTainter to mark for NoExecute taint, but the handleDisruption hasn't got freshed nodes info, so in this monitorNodeHealth period, handleDisruption could not get node's Ready condition with Unknown or False, so it can only enter full discruption mode in next monitorNodeHealth period(default 5s later). Based on this analysis, I think this is not the reason for NoExecute taint not removed occasionally

**Comment by LastNight1997** [comment]
> I'm a little confused, while a node's Ready condition becomes Unknown or False, then notifies zoneNoExecuteTainter to mark for NoExecute taint, but the handleDisruption hasn't got freshed nodes info, so in this monitorNodeHealth period, handleDisruption could not get node's Ready condition with Unknown or False, so it can only enter full discruption mode in next monitorNodeHealth period(default 5s later). Based on this analysis, I think this is not the reason for NoExecute taint not removed occasionally

handleDisruption can get node's Ready condition with Unknown or False in the first monitorNodeHealth period. It calculate disrupted status from zoneToNodeConditions, which will be updated in the first monitorNodeHealth period.

**Comment by LastNight1997** [comment]
@SergeyKanzhelev Is there any progress?
