### ISSUE TITLE
Get persistentVolumeClaims api panic

### ISSUE THREAD

**Issue by sunil-barhate** [kubernetes/kubernetes#111305]
### What happened?

While listing the pvc list, the get pvc api panic.

### What did you expect to happen?

The api should have work, and give list of pvc.

### How can we reproduce it (as minimally and precisely as possible)?

Not easily reproducible.
But, just call get pvc api

### Anything else we need to know?

panic stack,

  Jul 20 01:33:42 appserv[892]: /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc000c88c00 sp=0xc000c88bd0 pc=0x439b32
  Jul 20 01:33:42 appserv[892]: runtime.mapaccess2(0x1f92800, 0xc00036b890, 0xc000c88cb8, 0x26166b8, 0x20eca40)
  Jul 20 01:33:42 appserv[892]: /usr/local/go/src/runtime/map.go:469 +0x255 fp=0xc000c88c40 sp=0xc000c88c00 pc=0x412015
  Jul 20 01:33:42 appserv[892]: k8s.io/apimachinery/pkg/runtime.(*Scheme).ObjectKinds(0xc0002e8e70, 0x25a9d78, 0xc0007fbb20, 0x20e04a44522359fd, 0x200000c0007fbb20, 0x1, 0xc00037a240, 0xc000c88e08, 0x9     1e7f6)  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/apimachinery/pkg/runtime/scheme.go:285 +0x111 fp=0xc000c88d08 sp=0xc000c88c40 pc=0x91e6b1
  Jul 20 01:33:42 appserv[892]: k8s.io/apimachinery/pkg/runtime.UseOrCreateObject(0x25ab6f0, 0xc0002e8e70, 0x25981e0, 0xc0002e8e70, 0x0, 0x0, 0xc000e98ab0, 0x2, 0xc000f164c0, 0x19, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:87 +0xfa fp=0xc000c88e18 sp=0xc000c88d08 pc=0x90a5ba
  Jul 20 01:33:42 appserv[892]: k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Decode(0xc0000eee10, 0xc000164000, 0x5cc, 0x700, 0x0, 0x25a9d78, 0xc0007fbb20, 0xc0ae0d5980169a79, 0x110eb7     4cd, 0x36cd6e0, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:259 +0x527 fp=0xc000c890e8 sp=0xc000c88e18 pc=0xb8ac87
  Jul 20 01:33:42 appserv[892]: k8s.io/apimachinery/pkg/runtime.WithoutVersionDecoder.Decode(0x25982a0, 0xc0000eee10, 0xc000164000, 0x5cc, 0x700, 0x0, 0x25a9d78, 0xc0007fbb20, 0xb, 0xc000c892c8, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/apimachinery/pkg/runtime/helper.go:252 +0x97 fp=0xc000c89180 sp=0xc000c890e8 pc=0x91ae37
  Jul 20 01:33:42 appserv[892]: k8s.io/apimachinery/pkg/runtime.(*WithoutVersionDecoder).Decode(0xc000c38240, 0xc000164000, 0x5cc, 0x700, 0x0, 0x25a9d78, 0xc0007fbb20, 0xc000c89248, 0x0, 0x0, ...)
  Jul 20 01:33:42 appserv[892]: <autogenerated>:1 +0x9f fp=0xc000c891f8 sp=0xc000c89180 pc=0x92807f
  Jul 20 01:33:42 appserv[892]: k8s.io/client-go/rest.Result.Into(0xc000164000, 0x5cc, 0x700, 0x0, 0x0, 0x0, 0xc000988e30, 0x10, 0x0, 0x0, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/client-go/rest/request.go:1273 +0xb4 fp=0xc000c892d8 sp=0xc000c891f8 pc=0x12d1e34
  Jul 20 01:33:42 appserv[892]: k8s.io/client-go/kubernetes/typed/core/v1.(*persistentVolumeClaims).List(0xc000536c20, 0x25e29c8, 0xc0000520e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/vendor/k8s.io/client-go/kubernetes/typed/core/v1/persistentvolumeclaim.go:93 +0x25d fp=0xc000c893f0 sp=0xc000c892d8 pc=0x13229fd
  Jul 20 01:33:42 appserv[892]: gitlab.eng.diamanti.com/software/main.git/clusterprovider/kubernetes.(*persistentVolumeClaims).List(0xc000dc0700, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
  Jul 20 01:33:42 appserv[892]: /gocode/main/clusterprovider/kubernetes/persistentvolumeclaims.go:46 +0xbe fp=0xc000c894b8 sp=0xc000c893f0 pc=0x17bd29e

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
$ docker -v
Docker version 1.13.1, build b2f74b2/1.13.1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by 249043822** [comment]
Does your client use client-go to fetch k8s reources like pvcs? which version for your client-go?

**Comment by leilajal** [comment]
/assign @249043822 
thanks for helping.
/triage accepted

**Comment by sunil-barhate** [comment]
Yes, it uses client-go v0.20.6

**Comment by sunil-barhate** [comment]
> Does your client use client-go to fetch k8s reources like pvcs? which version for your client-go?

Yes, it uses client-go v0.20.6
