### ISSUE TITLE
Clean up taint_manager_test.go

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#111308]
Cleanups:
- multiple test functions (such as TestUpdateNode) in this file declare and close stopCh, but don't make any use of it: https://github.com/kubernetes/kubernetes/blob/303f47c0c069c80ec6d2b3879bc879924d555a8a/pkg/controller/nodelifecycle/scheduler/taint_manager_test.go#L461. Instead, the controller.Run method should be called with a context which is cancelled at the end. The  TestCreatePod test function is a good example.
- the test asserts use test case description passed explicitly in the t.Errorf method https://github.com/kubernetes/kubernetes/blob/303f47c0c069c80ec6d2b3879bc879924d555a8a/pkg/controller/nodelifecycle/scheduler/taint_manager_test.go#L481. Instead, the test case description should be passed into the t.Run method, for example: https://github.com/kubernetes/kubernetes/blob/303f47c0c069c80ec6d2b3879bc879924d555a8a/pkg/controller/podgc/gc_controller_test.go#L140

**Comment by alculquicondor** [comment]
When possible, use `defer` to call the `cancel` method from `context.WithCancel`
