### ISSUE TITLE
cfssl breaks - Getting started locally - build

### ISSUE THREAD

**Issue by JCzz** [kubernetes/kubernetes#111351]
### What happened?

building from source, cdssl breaks the build process.

Env:
Ubuntu: cat /etc/lsb-release
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
The [Getting started locally - doc](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#openssl) says

`go get -u github.com/cloudflare/cfssl/cmd/...`

Then the log says

```
To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor

```

Then after `go mod vendor` I get this error:

```
+++ [0722 14:17:30] Building go targets for linux/arm64
    k8s.io/code-generator/cmd/prerelease-lifecycle-gen (non-static)
cannot find package "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen" in:
	/home/ubuntu/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
!!! [0722 14:17:30] Call tree:
!!! [0722 14:17:30]  1: /home/ubuntu/src/k8s.io/kubernetes/hack/lib/golang.sh:762 kube::golang::build_some_binaries(...)
!!! [0722 14:17:30]  2: /home/ubuntu/src/k8s.io/kubernetes/hack/lib/golang.sh:921 kube::golang::build_binaries_for_platform(...)
!!! [0722 14:17:30]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0722 14:17:30] Call tree:
!!! [0722 14:17:30]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0722 14:17:30] Call tree:
!!! [0722 14:17:30]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile.generated_files:222: _output/bin/prerelease-lifecycle-gen] Error 1
make[1]: Leaving directory '/home/ubuntu/src/k8s.io/kubernetes'
make: *** [Makefile:528: generated_files] Error 2
make: Leaving directory '/home/ubuntu/src/k8s.io/kubernetes'
```

Also tried:
`go install github.com/cloudflare/cfssl/cmd/...@latest`

then I get:
```
+++ [0722 14:21:40] Building go targets for linux/arm64
    k8s.io/kubernetes/hack/make-rules/helpers/go2make (non-static)
+++ [0722 14:21:42] Building go targets for linux/arm64
    k8s.io/code-generator/cmd/prerelease-lifecycle-gen (non-static)
cannot find package "k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen" in:
	/home/ubuntu/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/code-generator/cmd/prerelease-lifecycle-gen
!!! [0722 14:21:42] Call tree:
!!! [0722 14:21:42]  1: /home/ubuntu/src/k8s.io/kubernetes/hack/lib/golang.sh:762 kube::golang::build_some_binaries(...)
!!! [0722 14:21:42]  2: /home/ubuntu/src/k8s.io/kubernetes/hack/lib/golang.sh:921 kube::golang::build_binaries_for_platform(...)
!!! [0722 14:21:42]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0722 14:21:42] Call tree:
!!! [0722 14:21:42]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0722 14:21:42] Call tree:
!!! [0722 14:21:42]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile.generated_files:222: _output/bin/prerelease-lifecycle-gen] Error 1
make[1]: Leaving directory '/home/ubuntu/src/k8s.io/kubernetes'
make: *** [Makefile:528: generated_files] Error 2
make: Leaving directory '/home/ubuntu/src/k8s.io/kubernetes'
```

Also tried:
```
go mod tidy
go mod vendor
```

apt install works though. If I install cfssl using apt install it works.

### What did you expect to happen?

K8s running

### How can we reproduce it (as minimally and precisely as possible)?

Run installation as defined in [Getting started locally](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#openssl)

### OS version
<details>

# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux k8s 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:05:39 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

</details>

### Container runtime (CRI) and version (if applicable)

<details>

  sudo apt-get update
  sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

</details>

**Comment by BenTheElder** [comment]
Those docs should probably be updated, I don't think you manually need to install that tool to run local-up-cluster.sh anymore, and we also have https://github.com/kubernetes-sigs/kind now

**Comment by JCzz** [comment]
Thanks @BenTheElder 

Can you debug Kubernetes source code using Kind?

**Comment by BenTheElder** [comment]
Yes for the most part, you can build and run a cluster as a container with `kind build node-image && kind create cluster --image=kindest/node:latest` basically, more details in the docs.

I think local-up-cluster.sh should also work fine if you just run it and *don't* try to install cfssl yourself, the scripts should manage it, I think those docs are just outdated.

**Comment by JCzz** [comment]
Thanks @BenTheElder

I will give both suggestions a try.

I will keep this open for the documentation to be updated.
