### ISSUE TITLE
E2e tests require support for fallocate while K8s does not

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#111368]
### What happened?

```
FAILED [sig-network] Services should be rejected for evicted pods (no endpoints exist)
```
in this test the rootfs is limited to 5M and the pod is evicted by creating a 10M file with;
```
fallocate -l 10M file
```
But this fails if the fs doesn't support the fallocate syscall.

### What did you expect to happen?

The K8s e2e must not itself require support for features that K8s does not require.

### How can we reproduce it (as minimally and precisely as possible)?

I am unsure why my overlay fs in containers doesn't support fallocate(2) while the fs on the node (ext4) does. I have queried on the `cri-o` slack. I build my Linux kernel myself but I can't find anything related.

### Anything else we need to know?

If the command is changed to;
```
dd if=/dev/zero of=file bs=1M count=10
```
the test works on an fs that doesn't support fallocate(2). It may seem more "primitive" but it doesn't require a feature that K8s doesn't.

### Kubernetes version

```
  17:17:59 Server Version: v1.25.0-alpha.3.93+5e14c5dfa93f4e
```

### Cloud provider

<details>
None
</details>

### OS version

```console
Own BusyBox bases system. Kernel;
Linux 5.18.1 #18 SMP PREEMPT_DYNAMIC Sat Jul 23 15:16:42 CEST 2022
```

### Container runtime (CRI) and version (if applicable)

```
  17:17:59 crio version 1.24.1
```

**Comment by aojea** [comment]
Interesting
/Triage accepted
