### ISSUE TITLE
Missing error messages from kubectl resize

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11148]
There are cases when rc-resize cannot work (e.g. resizing a replication controller that has an RW-mounted PD). However, when we run this command, we don't get a reasonable error message, but a timeout.

I suspect that "resize" handler doesn't actually check the conditions, but dumbly tries to update the RC.

**Comment by thockin** [comment]
We have other problems that we do not catch - an RC that uses a
PersistentVolumeClaim to a PD will not get caught.

**Comment by eikaas** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  tapiohush@gmail.com
    Domain eikaas.no has exceeded the max emails per hour (32/30 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:40183 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cpanel30.proisp.no with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1ZEgnQ-003y5z-Sl
	for robin@eikaas.no; Mon, 13 Jul 2015 18:41:38 +0200
Date: Mon, 13 Jul 2015 09:41:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1436805695;
	bh=/yYFWeR4AAXJa6nJSQbgp7tUaOnlGS6T97fOSfXzk6o=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=sg9R+Bs8lpVV2HBEhCpGXRKRD62Pzh+B9hYifzjU6lLVntJL80cWV3LEoF7vK6xGF
	 XhaA7MvM8V2baC3McBTOFHlBr9ta+tNdS/+vZC2mBftZ9v8n9GW5QHVM61Taxj58VO
	 hRiggLmAlhxk+iGUHbJ46QQi8b1qdn5MU8SI8Fig=

**Comment by erictune** [comment]
@marekbiskup put a priority and team on this issue, please.
