### ISSUE TITLE
Order for pod deletion in ReplicaSets do not work as documented

### ISSUE THREAD

**Issue by martinstraesser** [kubernetes/kubernetes#111443]
### What happened?

I'm conducting some experiments with different schedulers and a `cluster-autoscaler` in GKE. For validation purposes, I repeated some experiments and came across an issue when downscaling my test deployment. More precisely, I observed that the selection which pod gets deleted when decreasing the replica count is non-deterministic and especially behaves not as documented.

I deployed the following test deployment in a cluster consisting of `e2-medium` nodes: 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          resources:
            requests:
              cpu: "0.2"
          ports:
            - containerPort: 80
```

I now stepwise increased the replica count to 13 (by executing `kubectl scale deployment nginx-deployment --replicas=n` and tracked which pod gets scheduled on which node. As the scheduling policy is deterministic and works as expected, I always arrive at the allocation below. The node names are simplified. The pod numbers represent the time when the pod has been deployed (e.g., Pod 1 has been deployed before Pod 2 and so on). 

```
Node A: Pod 1, Pod 4, Pod 7
Node B: Pod 2, Pod 5
Node C: Pod 3, Pod 6
Node D: Pod 8, Pod 9, Pod 10
Node E: Pod 11, Pod 12, Pod 13
```

I now started to decrease the replica count again stepwise, so always removing one pod at a time. I now observed that:

1. Considering one repetition, the pods selected for deletion are not the same as I would assume it by reading the docs.
2. Considering multiple repetitions, the order of which pods are deleted is not the same.

The `controller.kubernetes.io/pod-deletion-cost` annotation is not set at any pod. Here some concrete results:

|   |  Pod deleted (run 1)  | Pod deleted (run 2)  |  
|---|---|---|
|  `--replicas=12` | Pod 7  | Pod 12 |  
|  `--replicas=11` | Pod 13 | Pod 10 | 
| `--replicas=10` | Pod 10 | Pod 7 |  

To get back to the bigger picture: As a consequence of this varying behavior, the `cluster-autoscaler` might be able to scale down later as expected or perform other evictions during node draining. 

Independently from my (honestly not really mainstream) use case, I still think this is unexpected behavior considering the docs.

### What did you expect to happen?

The [docs](https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/) are saying that: 

> When scaling down, the ReplicaSet controller chooses which pods to delete by sorting the available pods to prioritize scaling down pods based on the following general algorithm:
> 
>     Pending (and unschedulable) pods are scaled down first
>     If controller.kubernetes.io/pod-deletion-cost annotation is set, then the pod with the lower value will come first.
>     Pods on nodes with more replicas come before pods on nodes with fewer replicas.
>     If the pods' creation times differ, the pod that was created more recently comes before the older pod (the creation times are bucketed on an integer log scale when the LogarithmicScaleDown [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is enabled)
> 
> If all of the above match, then selection is random.

So, if I apply this algorithm to allocation above manually, I would expect for `--replicas=12`:

1. Pending (and unschedulable) pods are scaled down first
Remaining candidates for deletion: Pod 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
Pods that should not be deleted: -

2. If controller.kubernetes.io/pod-deletion-cost annotation is set, then the pod with the lower value will come first.
Remaining candidates for deletion: Pod 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
Pods that should not be deleted: -

3. Pods on nodes with more replicas come before pods on nodes with fewer replicas.
Remaining candidates for deletion: Pod 1, 4, 7, 8, 9, 10, 11, 12, 13
Pods that should not be deleted: Pod 2, 3, 5, 6

4. If the pods' creation times differ, the pod that was created more recently comes before the older pod
Candidate selected: Pod 13 (most recent pod)

Analogously, I for `--replicas=11` I would expect Pod 10 gets removed and for `replicas=10` Pod 7 gets removed.

### How can we reproduce it (as minimally and precisely as possible)?

Follow the description above.

### Anything else we need to know?

In contrast to other issues which request to have a configurable downscaling and pod deletion selection behavior (such as #4301 and #45509 ) and just want to make sure that the current behavior is deterministic and works as expected.

### Kubernetes version

<details>

```
v1.22.8-gke.202
```

</details>

### Cloud provider

<details>
Google Kubernetes Engine
</details>

**Comment by Malek-Zaag** [comment]
@martinstraesser hello, so no updates for now ? did you manage to find a solution for deterministic deletion ?
