### ISSUE TITLE
APF: it should be possible to selectively prevent borrowing

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/kubernetes#111482]
### What happened?

For K8s 1.25, API Priority and Fairness will allow borrowing.  But there is no way to say "For this particularly Priority Level Configuration, do not ever allow it to borrow.  Throttle it exactly to the limit I have specified, and never let it go above".

### What did you expect to happen?

I think there should be a `NoBorrow` flag added to PriorityLevelConfiguration. It would default to false. But if set to true, it would prevent the level from every borrowing concurrency allowances (seats?) from other levels.

For reference, here's an extract from the relevant discussion on Slack

>[John Rusk](https://app.slack.com/team/U01ANSTH7AQ)
  [17 days ago](https://kubernetes.slack.com/archives/C01G8RY7XD3/p1657488295607919?thread_ts=1655693389.253489&cid=C01G8RY7XD3)
[@mspreitz](https://kubernetes.slack.com/team/U0E40F05R)
 I'm thinking about this some more, inspired by a cluster I'm looking at today.  I am a bit nervous that, as it stands, 1.25 will effectively require us to rely totally on the automatic behaviour, with no ability to manually throttle any particular LIST operations.  What are your thoughts about NoBorrow for some future version? (Either a 1.25 point release or , failing that, 1.26)?

>[mspreitz](https://app.slack.com/team/U0E40F05R)
  [17 days ago](https://kubernetes.slack.com/archives/C01G8RY7XD3/p1657519768850189?thread_ts=1655693389.253489&cid=C01G8RY7XD3)
Yes, I think this is something to look at for 1.25

> [mspreitz](https://app.slack.com/team/U0E40F05R)
  [16 days ago](https://kubernetes.slack.com/archives/C01G8RY7XD3/p1657570346141849?thread_ts=1655693389.253489&cid=C01G8RY7XD3)
Sorry, off by one.  It is too late to make such a change for 1.25, it would have to be 1.26

### How can we reproduce it (as minimally and precisely as possible)?

-

### Kubernetes version

1.25+

### Cloud provider

Any

**Comment by JohnRusk** [comment]
cc @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
Is the concern here actually that some LIST operations are too expensive?  There is a recent change to limit them more severely than before.  Have you experimented with that?  If it is not adequate, that would be important to understand in itself; can you share data or scenario demonstrating inadequacy of the current handling of LIST requests?

**Comment by JohnRusk** [comment]
I have not had time to do those experiments. My concern was primarily that, IF the current handling was inadequate in some way, there would be no way to work around it (by setting manual limits).

**Comment by MikeSpreitzer** [comment]
This has been resolved by https://github.com/kubernetes/enhancements/pull/3479 .
/close
