### ISSUE TITLE
kubectl cp fails with 'pods/' prefix

### ISSUE THREAD

**Issue by OJFord** [kubernetes/kubernetes#111471]
### What happened?

`kubectl cp pods/example:/tmp/foo bar` fails with:
> Error from server (NotFound): pods "example" not found

When there is a pod 'example'.

`kubectl cp example:/tmp/foo bar` succeeds.

### What did you expect to happen?

Behave the same with & without `pods/` prefix.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a pod with one container and some readable file
- `kubectl cp pods/its-name:/that/file /tmp/wherever`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"archive", BuildDate:"2022-06-18T07:33:51Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15-eks-a64ea69", GitCommit:"03450cdabfc4162d4e447e6d8c5037efe6d29742", GitTreeState:"clean", BuildDate:"2022-05-12T18:44:04Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by OJFord** [comment]
Er, sorry it could be
/sig cli

but I gather it's a server issue, not sure of correct one?

**Comment by brianpursley** [comment]
Can you use `kubectl cp` with anything other than a pod?

Currently it assumes anything before the `/` is a namespace.  See the help examples for what i mean:
```
  
  # Copy /tmp/foo local file to /tmp/bar in a remote pod in namespace <some-namespace>
  kubectl cp /tmp/foo <some-namespace>/<some-pod>:/tmp/bar
  
  # Copy /tmp/foo from a remote pod to /tmp/bar locally
  kubectl cp <some-namespace>/<some-pod>:/tmp/foo /tmp/bar

```

I know this is inconsistent with how some other commands work, but it would be a breaking change to deviate from this.  Just pointing that out.

Should it be this way though?

Does `kubectl cp` support the `--namespace` flag?

Maybe a first step would be to deprecate specifying the namespace as `namespace/podname` and print a warning if people do it that way, telling them to use the `--namespace` flag instead.

Thoughts?

**Comment by OJFord** [comment]
Oh interesting, I didn't realise that. That is confusingly inconsistent.

It does work with `--namespace`, which I was using too. Maybe that's why I didn't get an error more like 'namespace pods doesn't exist'?
