### ISSUE TITLE
Docker config Secrets to be renamed to Registry config Secrets

### ISSUE THREAD

**Issue by rizwan-kh** [kubernetes/kubernetes#111480]
### What would you like to be added?

The `kubernetes.io/dockercfg` type secret to be renamed to something like `kubernetes.io/registrycfg` and while creating the secret it should be with below syntax

```
kubectl create secret registry secret-tiger-registry \
  --registry-email=tiger@acme.example \
  --registry-username=tiger \
  --registry-password=pass1234 \
  --registry-server=my-registry.example:5000
```

### Why is this needed?

As docker runtime was officially removed from version 1.23, it makes sense to rename the secret type object from `docker` to registry as well the syntax to create the `registry` type object to be consistent across the naming and it usage.

**Comment by sftim** [comment]
This doesn't seem right to me. The format of the data in that Secret is a particular format, and that format (a specific kind of JSON document) was designed by Docker. https://docs.docker.com/docker-hub/configure-sign-in/ has a bit more context on this.

You can use that format even if your container runtime isn't Docker Engine.

/remove-sig cli

This isn't a kubectl issue.

**Comment by pacoxu** [comment]
Is https://github.com/kubernetes/kubernetes/issues/106035 related?

**Comment by rizwan-kh** [comment]
> Is #106035 related?

yes looks similar, thanks for pointing out, will close this.

/close
