### ISSUE TITLE
incorrectly results are returned when "Limit" and "LabelSelector" parameters are both set in certain case

### ISSUE THREAD

**Issue by boylee1111** [kubernetes/kubernetes#111488]
### What happened?

**Deployment Setup**
I had 35 StatefulSets deployed in one namespace as below:
```shell
$ kubectl get sts -n yonis-1
NAME                             READY   AGE
elasticsearch-master             1/1     5d21h
sealed-secrets-1-redis-master    1/1     20h
sealed-secrets-10-redis-master   1/1     20h
sealed-secrets-11-redis-master   1/1     20h
sealed-secrets-12-redis-master   1/1     20h
sealed-secrets-13-redis-master   1/1     20h
sealed-secrets-14-redis-master   1/1     20h
sealed-secrets-15-redis-master   1/1     20h
sealed-secrets-16-redis-master   1/1     20h
sealed-secrets-17-redis-master   1/1     20h
sealed-secrets-18-redis-master   1/1     20h
sealed-secrets-19-redis-master   1/1     20h
sealed-secrets-2-redis-master    1/1     20h
sealed-secrets-20-redis-master   1/1     20h
sealed-secrets-21-redis-master   1/1     20h
sealed-secrets-22-redis-master   1/1     20h
sealed-secrets-23-redis-master   1/1     20h
sealed-secrets-24-redis-master   1/1     20h
sealed-secrets-25-redis-master   1/1     20h
sealed-secrets-26-redis-master   1/1     20h
sealed-secrets-27-redis-master   1/1     20h
sealed-secrets-28-redis-master   1/1     20h
sealed-secrets-29-redis-master   1/1     20h
sealed-secrets-3-redis-master    1/1     20h
sealed-secrets-30-redis-master   1/1     20h
sealed-secrets-31-redis-master   1/1     20h
sealed-secrets-32-redis-master   1/1     20h
sealed-secrets-33-redis-master   1/1     20h
sealed-secrets-34-redis-master   1/1     20h
sealed-secrets-4-redis-master    1/1     20h
sealed-secrets-5-redis-master    1/1     20h
sealed-secrets-6-redis-master    1/1     20h
sealed-secrets-7-redis-master    1/1     20h
sealed-secrets-8-redis-master    1/1     20h
sealed-secrets-9-redis-master    1/1     20h
```

Among all of them, only `elasticsearch-master` has labels below:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch-master
    guardicore.app: infra
    chart: elasticsearch
    data: elasticsearch
...
```

Other `sealed-secrets-{#}-redis-master` does not have such labels.

**Issue:**
When I used kubectl with only label selector, everything worked fine:
```
$ kubectl get sts -n yonis-1 -l app=elasticsearch-master,guardicore.app=infra,data=elasticsearch                                                                            
NAME                   READY   AGE
elasticsearch-master   1/1     5d21h
```

It worked perfectly as well when I used `--raw` below:
```
$ kubectl get --raw "/apis/apps/v1/namespaces/yonis-1/statefulsets?labelSelector=app%3Delasticsearch-master%2Cdata%3Delasticsearch%2Cguardicore.app%3Dinfra"
```

However, I got an empty result when I added the additional parameter `limit` as 15:
```
$ kubectl get --raw "/apis/apps/v1/namespaces/yonis-1/statefulsets?labelSelector=app%3Delasticsearch-master%2Cdata%3Delasticsearch%2Cguardicore.app%3Dinfra&limit=15"
  "kind": "StatefulSetList",
  "apiVersion": "apps/v1",
  "metadata": {
    "resourceVersion": "3484478"
  },
  "items": []
```

It does not give the continuous token either. I did more tests, and it turned out that if the condition `total resource count > limit * 2` is met, then no result was returned.

For example, I had a total of 35 StatefulSets, If I gave a limit greater than 18, then it returned the correct result. Otherwise, it returned nothing:
* Limit is 18, it returned the StatefulSet correctly: `kubectl get --raw "/apis/apps/v1/namespaces/yonis-1/statefulsets?labelSelector=app%3Delasticsearch-master%2Cdata%3Delasticsearch%2Cguardicore.app%3Dinfra&limit=18"`
* Limit is 17, nothing was returned: `kubectl get --raw "/apis/apps/v1/namespaces/yonis-1/statefulsets?labelSelector=app%3Delasticsearch-master%2Cdata%3Delasticsearch%2Cguardicore.app%3Dinfra&limit=17"`

I also used the `client-go` library to test it, the code looks like the below:
```go
        cs, _ := clientset.NewForConfig(cfg)

	selector := labels.SelectorFromSet(labels.Set{
		"app":            "elasticsearch-master",
		"guardicore.app": "infra",
		"data":           "elasticsearch",
	})
	stss, _ := cs.AppsV1().StatefulSets("yonis-1").List(ctx, metav1.ListOptions{
		LabelSelector: selector.String(),
		Limit:         15,
	})
```

The issue persists, so I believe it is likely an issue on apiserver when both 'limit' and 'labelSelector' parameters are present.

### What did you expect to happen?

`kubectl get --raw "/apis/apps/v1/namespaces/yonis-1/statefulsets?labelSelector=app%3Delasticsearch-master%2Cdata%3Delasticsearch%2Cguardicore.app%3Dinfra&limit=18"` should returned expected result

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

<details>

```shell
$ kubectl version -o yaml
clientVersion:
  buildDate: "2022-06-15T14:22:29Z"
  compiler: gc
  gitCommit: f66044f4361b9f1f96f0053dd46cb7dce5e990a8
  gitTreeState: clean
  gitVersion: v1.24.2
  goVersion: go1.18.3
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-06-24T09:25:13Z"
  compiler: gc
  gitCommit: efbcd8d250c89b4290356c0fc27843d583c80a35
  gitTreeState: clean
  gitVersion: v1.23.8-gke.400
  goVersion: go1.17.10b7
  major: "1"
  minor: "23"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by boylee1111** [comment]
Thanks for verifying. I was using GKE and did more digging. And I realized that this issue only happen for certain versions of GKE clusters.

* **1.22.8-gke.202** does not have this issue. Everything works fine.

Then I can reproduce the issue in GKE version:

* **1.23.5-gke.1503**
* **1.23.8-gke.400**

And it seems to be gone in **1.23.8-gke.1900**. It looks like it was something introduced in GKE 1.23 and was fixed after that. I tried to look for related bugs but no luck. Do you know when exactly the issue was introduced or fixed?

**Comment by gjkim42** [comment]
I think we don't. So this is about the GKE, not the kubernetes itself.
Maybe you can ask for support from GKE.

I believe this repository(kubernetes/kubernetes) does not manage GKE.

**Comment by ialidzhikov** [comment]
@boylee1111 , can you check if this issue is duplicate of https://github.com/kubernetes/kubernetes/issues/110625?
