### ISSUE TITLE
APIServer returns status code 500 and error message "request declared a Content-Length of 351 but only wrote 0 bytes" occasionally

### ISSUE THREAD

**Issue by LiuNingqian** [kubernetes/kubernetes#111499]
### What happened?

We add the command line param "--goaway-chance=0.001" for APIServer, which was mentioned in the issue [#88567](https://github.com/kubernetes/kubernetes/pull/88567).

We found that APIServer returns status code 500 and error message "request declared a Content-Length of xxx but only wrote 0 bytes" occasionally, which causes alerts of "KubeAPIErrorsHigh".

### What did you expect to happen?

I want to know why there are requests of status code 500.

### How can we reproduce it (as minimally and precisely as possible)?

I don't know how to reproduce it.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2021-05-10T07:53:22Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by LiuNingqian** [comment]
area/apiserver

**Comment by aojea** [comment]
> Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2021-05-10T07:53:22Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}


Latest supported version is 1.22 https://kubernetes.io/releases/, does this happens in that version too?
or is more a general question?

**Comment by LiuNingqian** [comment]
> > Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"archive", BuildDate:"2021-05-10T07:53:22Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
> 
> Latest supported version is 1.22 https://kubernetes.io/releases/, does this happens in that version too? or is more a general question?

I find another issue #91131 , indicating that it's the go sdk bug, and has been fixed. Maybe upgrading the kubernetes version is the only way to solve the problem.

**Comment by LiuNingqian** [comment]
Could APIServer be compiled using go version 1.14?

**Comment by answer1991** [comment]
> Could APIServer be compiled using go version 1.14?

All the components which connect to apiserver should be also use a newer golang version(>=1.14.15).

**Comment by LiuNingqian** [comment]
> > Could APIServer be compiled using go version 1.14?
> 
> All the components which connect to apiserver should be also use a newer golang version(>=1.14.15).

Okay, thank you so much.

**Comment by answer1991** [comment]
Should we close this issue as the latest k8s has no this problem？ @LiuNingqian

**Comment by LiuNingqian** [comment]
> Should we close this issue as the latest k8s has no this problem？ @LiuNingqian

Of course, and thanks again.

**Comment by aojea** [comment]
> > Should we close this issue as the latest k8s has no this problem？ @LiuNingqian
> 
> Of course, and thanks again.

/close

Thanks
