### ISSUE TITLE
Performance analysis of x-kubernetes-validations

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#111445]
As soon as possible, and certainly before the [CEL validation rules for CRDs feature](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/2876-crd-validation-expression-language/README.md) reaches GA, we need to understand its performance implications to CR create/update.

Some cases to consider when gathering performance data:

- Baseline CRD that has a trivial OpenAPIv3 schema
- CRD with complex OpenAPIv3 schema, but no CEL rules
- CRD with simple CEL rules
- CRD with lost of cheap CEL rules (high compilation cost and CEL program memory utilization)
- CRD with CEL rules near the estimated cost limit
- CRD with webhook that performs the same task as a CRD with CEL rules

We also need good benchmarks should prevent performance regressions.

It would also be good to look at existing issues that impact performance AND scale: https://github.com/kubernetes/kubernetes/issues/109099.  Does CEL make these much worse?

/sig api-machinery

cc @cici37 @liggitt @DangerOnTheRanger

**Comment by cici37** [comment]
We have the scalability analysis report here: https://docs.google.com/document/d/1gU8FfBhKnkmzJUC32NmXMdh4vzbLxb-gkf52O9Un7Cg/edit#heading=h.munb04a3nzze
