### ISSUE TITLE
Is there no IP of kubernetes node?

### ISSUE THREAD

**Issue by Thanhphan2510** [kubernetes/kubernetes#111498]
![image](https://user-images.githubusercontent.com/41299178/181454783-990412b0-671e-4875-b3e1-f6929cbc4bf8.png)

My nodes haven't internal-ip and external-ip. Help me!!!

**Comment by aojea** [comment]
you are running a very old version v1.11.6 , latest supported is 1.22 https://kubernetes.io/releases/

In addition, dockershim has been deprected in 1.20 and removed in 1.24

/kind support
/close
