### ISSUE TITLE
Kubelet regularly freeze cgroups of Guaranteed QoS type causing pod segfault and core dump

### ISSUE THREAD

**Issue by jingczhang** [kubernetes/kubernetes#111540]
### What happened?

We have experienced MariaDB pod segfault and core dump after upgrading from Kubernetes v1.19 to Kubernetes v1.21.
Issue starts to occur with Kubernetes v.21 + runc v.1.0.3, and continues.

MariaDB trace shows epoll_wait() interrupted by EINTR.
...
2022-05-23  5:17:13 0 [ERROR] InnoDB: Operating system error number 4 in a file operation.
2022-05-23  5:17:13 0 [ERROR] InnoDB: Error number 4 means 'Interrupted system call'
...

This epoll_wait() interrupted by EINTR is also seen in other applications after their moving up to Kubernetes v1.21.

We have managed to nail down the root cause is kubelet regularly freezes cgroups of Guaranteed QoS Type and only Guaranteed QoS Type. Changing MariaDB pod to Bursty type is able to fix the issue.

This finding brings us to the following issue:
https://github.com/kubernetes/kubernetes/issues/104280
and the following fix:
https://github.com/kubernetes/kubernetes/pull/104530/commits

Apparently the above fix missed Guaranteed QoS Type.

Checking affected kubelet code area, I see the same code in v1.21 and onwards including master, that is, the issue seems not limited to v1.21 (seems the same fix in above commit is needed in another file). 

### What did you expect to happen?

No random pod crash when moving up to Kubernete v.21.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy pods of Guaranteed QoS Type, and run the following command on the node,  you will see regular FROZEN

while true ; do cat /sys/fs/cgroup/freezer/kubepods.slice/{*/{*/,},}freezer.state; done | grep FROZEN

### Kubernetes version

v1.21

### Cloud provider

Baremetal

### OS version

Centos 7.9

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

runc version 1.0.3 and onwards

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
Couldn't reproduce this issue.

> Apparently the above fix missed Guaranteed QoS Type.

What makes you think the fix is not applied to the Guaranteed pods.

**Comment by endocrimes** [comment]
Could you try reproducing this on a more recent version of kubernetes? 1.21 is out of support (https://endoflife.date/kubernetes)
