### ISSUE TITLE
Cleanup TestJobStrategy in registry/batch/job/strategy_test.go

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#111514]
The `TestJobStrategy` gets very long testing mulitple functions in such as `PrepareForCreate`, `PrepareForUpdate` and `ValidateUpdate`. These checks should be performed in dedicated Test functions using table for different scenarios.
Target functions `TestJobStrategy_PrepareForUpdate` and `TestJobStrategy_PrepareForCreate` are being added as part of https://github.com/kubernetes/kubernetes/pull/111113. The remaining checks should be migrated to these functions. Also, a test function `TestJobStrategy_ValidateUpdate` should be added to migrate the remaining tests.

**Comment by kannon92** [comment]
@jlsong01 Any progress on this?  I'm working on https://github.com/kubernetes/kubernetes/pull/114930 and I noticed that strategy.go has relatively low coverage so I was going to work on getting the coverage up.

**Comment by kannon92** [comment]
I created https://github.com/kubernetes/kubernetes/pull/115111 that is somewhat related to this.

**Comment by jlsong01** [comment]
> @jlsong01 Any progress on this? I'm working on #114930 and I noticed that strategy.go has relatively low coverage so I was going to work on getting the coverage up.

no progess. go ahead please
