### ISSUE TITLE
UI Reports Memory Usage Including Buffers and Cache

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#11158]
It would be more useful to know the amount of memory actually used on my nodes rather than that plus the cache and buffers.

**Comment by erictune** [comment]
Which UI url and what version `kubectl version` are you referring to.

**Comment by erictune** [comment]
I think you are talking about `https://$APISERVER/static/app/#/dashboard/`

Yes, I agree that showing memory usage including all buffers and cache is not useful.  However, some fraction of buffers and cache are typically necessary.  So, we probably only want to show recently used cache and buffer, for some definition of recently used.  @vishh @vmarmol @dchen1107 @rjnagal do we have a reasonable metric of memory used available from cadvisor/heapster?

**Comment by rjnagal** [comment]
cadvisor/heapster both report usage (all memory) and workingset (hot
memory).

**Comment by esecules** [comment]
Im using this URL:
http://kube-master:8080/api/v1/proxy/namespaces/kube-system/services/kube-ui/#/dashboard/
and the 0.21.1 release of kubernetes with the v1 kube-ui image (Image ID: a5aea7f6bfd4).

**Comment by erictune** [comment]
Okay, so this is a feature request for the ui to show memory workingset for the node instead of usage.

**Comment by erictune** [comment]
@preillyme

**Comment by andyxning** [comment]
@ericchiang @rjnagal AFAIK, currently, [cAdvisor supports exporting rss memory data](https://github.com/google/cadvisor/issues/975), so we may add supporting rss data now.

**Comment by inetfuture** [comment]
@andyxning I'm curious, what's the difference between rss and workingset, please?

**Comment by andyxning** [comment]
@inetfuture IIUC, rss + cache ~= usage. Just like what is res + cache ~= virt.

I also have no clear understand about workingset, according to the [wiki](https://en.wikipedia.org/wiki/Working_set), it is just an operating system concept.

> Working set is a concept in computer science which defines the amount of memory that a process requires in a given time interval.

**Comment by toddams** [comment]
Seems like this is still not fixed. Is there an update?
