### ISSUE TITLE
e2e test flake: Probing container should mark readiness on pods to false...

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#111578]
### Which jobs are flaking?

pull-kubernetes-e2e-kind-ipv6

#### Failure cluster [2b82bf704961f0af177d](https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1#2b82bf704961f0af177d)
Kubernetes e2e suite.[It] [sig-node] Probing container should mark readiness on pods to false and disable liveness probes while pod is in progress of terminating
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553371978050572288
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553080106287632384
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553048515620376576
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553005284304097280

See also, possibly related:
Kubernetes e2e suite.[It] [sig-node] Probing container should mark readiness on pods to false while pod is in progress of terminating when a pod has a readiness probe
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1553048515620376576
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-kind-ipv6/1552994735386267648

### Since when has it been flaking?

Not sure.  At least as of July 27, 2022, but probably earlier than that.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind-ipv6

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/4977542/181920190-083b09b3-59da-4d09-b2fe-9c6ea2765ef7.png)

### Relevant SIG(s)

/sig node

**Comment by 249043822** [comment]
/assign
we should use listwatch to monitor pod status changes accurately, this interval 2s may lose pod change and cause the test failure

**Comment by aojea** [comment]
> /assign we should use listwatch to monitor pod status changes accurately, this interval 2s may lose pod change and cause the test failure

we did the same recently in another test, didn't we?
I can't find the PR

**Comment by 249043822** [comment]
sorry, i have not committed yet. do you plan to fix this test again? if so, I can unassign

**Comment by aojea** [comment]
> @aojea sorry, i have not committed yet. do you plan to fix this test again? if so, I can unassign

he, no sorry for the confusion, I thought you were the one that fixed it, maybe it was @pacoxu ? 
There was one e2e that was flake and was solved using a listwatch instead of polling it every few seconds, I was trying to find the PR to show you , in case can give you some idea ... please go ahead and fix it :)

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/108958 this one?

**Comment by aojea** [comment]
> #108958 this one?

yeah, so my memory was good then, I've identified the right author :smile:

**Comment by 249043822** [comment]
> > /assign we should use listwatch to monitor pod status changes accurately, this interval 2s may lose pod change and cause the test failure
> 
> we did the same recently in another test, didn't we? I can't find the PR

I didn't understand what you said at first, but now I understand :smile:
