### ISSUE TITLE
Why kubelet cert automatically rotation need to restart kubelet?

### ISSUE THREAD

**Issue by lixiaoyuner** [kubernetes/kubernetes#111501]
### What happened?

I create a k8s cluster and change master nodes and worker nodes system time to be one day earlier than kubelet cert expire time. I don't see the kubelet automatically rotation its cert in the 24 hours, what I observed is I need to restart kubelet manually to trigger cert rotation before kubelet cert is going to expire. 
Is there any way to rotate without restarting kubelet? (I have tried to pass --rotate-certificates to kubelet, not work) if not, why need to restart kubelet?

### What did you expect to happen?

Rotate automatically without restarting kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

Create a k8s cluster and change master nodes and worker nodes system time to be one day earlier than cert expire time.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:53:39Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
Can this be a configuration problem?
I think that certificate rotation happens automatically https://kubernetes.io/docs/tasks/tls/certificate-rotation/

**Comment by lixiaoyuner** [comment]
@aojea, thanks for your reply. I have referred to the link before and try to pass the --rotate-certificates to kubelet, but not work. Do you know how long will kubelet start to rotate the cert in advance before cert expires? Is it possible kubelet will detect whether cert expires per week or per month? I only try to change the time to be 24 hours earlier than expire time, so that the kubelet has not done it.

**Comment by neolit123** [comment]
the kubelet client cert expires after 1 year. the kubelet internal cert manager will watch the date and rotate it when around 80% of the time period is reached.

kubeadm deploys the kubelet with this rotation enabled. this is not a bug that kubeadm users are seeing, so possibly you did not enable the rotation properly?

/kind support

**Comment by lixiaoyuner** [comment]
@neolit123 , thanks for your reply. I was using kubeadm to deploy k8s. I do not change anything default related to rotation and I tried to pass --rotate-certificates to kubelet, but not work. Is it possible that the time interval I observed is too short? I only try to change the time to be 24 hours earlier than expire time, in the 24 hours, rotation doesn't happen.

**Comment by neolit123** [comment]
i haven't tested with 24h.

**Comment by lixiaoyuner** [comment]
Thank you @neolit123, let me try with more than 24 hours.

**Comment by arrowfeng** [comment]
You can also verify the certificate rolling feature by configuring the KCM's certificate signing validity period. 
--cluster-signing-duration

**Comment by lixiaoyuner** [comment]
@arrowfeng, thanks for your suggestion. I try to pass --cluster-signing-duration to kube-control-manager, but it can control the certificate available time, but can't trigger kubelet cert rotation.
@neolit123, and I try to change the system time to be one month earlier than expire time, five days have passed, rotation does not happen automatically. But I restart one of worker kubelet, rotation happens.
is there anybody can confirm that restarting kubelet service is required for kubelet cert rotation?

**Comment by lixiaoyuner** [comment]
Thanks @neolit123, very helpful. I have tried to pass a very short time for --cluster-signing-duration and I see the rotation happens automatically without restarting kubelet. I think the way I change node system time maybe not a good way to simulate expiration. And I still don't know why changing the node system time doesn't work.

**Comment by neolit123** [comment]
yes, i recall using system time was not a way to reptoduce the rotation.
let's close given there is no bug here.

for questions ask on #sig-node on k8s slack

/close
