### ISSUE TITLE
[Failing test] Conformance-GCE-master-kubetest2

### ISSUE THREAD

**Issue by shuheiktgw** [kubernetes/kubernetes#111584]
### Which jobs are failing?

Conformance-GCE-master-kubetest2

### Which tests are failing?

ci-kubernetes-gce-conformance-latest-kubetest2.Overall

### Since when has it been failing?

7/30

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2

### Reason for failure (if possible)

```
go: downloading github.com/vbatts/tar-split v0.11.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
# sigs.k8s.io/boskos/client
/home/prow/go/pkg/mod/sigs.k8s.io/boskos@v0.0.0-20200710214748-f5935686c7fc/client/client.go:96:17: undefined: secret.Agent
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Cleaning up after docker
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
================================================================================
Done cleaning up after docker in docker.
```

### Anything else we need to know?

It looks like this is the part where the error happens.
https://github.com/kubernetes-sigs/boskos/blob/f5935686c7fc0a431016c741e48b79c913929b35/client/client.go#L96

### Relevant SIG(s)

/sig testing

**Comment by shuheiktgw** [comment]
[Asking for help from the sig-testing team](https://kubernetes.slack.com/archives/C09QZ4DQB/p1659245671520459)

**Comment by BenTheElder** [comment]
Uh, that type was removed from test-infra 12 months ago https://github.com/kubernetes/test-infra/commit/02aa922dfd687b5141647e43d15d0918c0363dff

Looks like dependency management issues, but not sure why we're only seeing this in this job

First failure on 7-29: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1552921263578550272

Then it passed twice also no 7-29:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1553026710050443264

Then resumed failing. It was passing on 7-28 and back with the occasional test flake (Which is itself concerning for the reliability of conformance tests but that's a separate issue https://github.com/kubernetes/kubernetes/issues/111588).

**Comment by BenTheElder** [comment]
I don't see where something related changed in the past week. We switched go versions on the 26th but that's too early, though the images aren't bumped immediately https://github.com/kubernetes/test-infra/pull/26874#event-7067368837

> set -o errexit; set -o nounset; set -o pipefail; set -o xtrace; REPO_ROOT=$GOPATH/src/k8s.io/kubernetes; cd; export GO111MODULE=on; go install sigs.k8s.io/kubetest2@latest; go install sigs.k8s.io/kubetest2/kubetest2-gce@latest; go install sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest; kubetest2 gce -v 2 \; --repo-root $REPO_ROOT \; --legacy-mode \; --build \; --up \; --down \; --test=ginkgo \; -- \; --focus-regex='\[Conformance\]' \; --use-built-binaries

In any case, kubetest2 is using a really old boskos commit, it should probably be upgraded.

**Comment by palnabarun** [comment]
This looks to be related to https://github.com/kubernetes/test-infra/pull/26956. The PR dropped Boskos as a direct dependency of k/test-infra.

The [last successful run](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1553072260703588352) of the job pulled the following deps:
```
...
go: downloading sigs.k8s.io/boskos v0.0.0-20200710214748-f5935686c7fc 
...
go: downloading sigs.k8s.io/boskos v0.0.0-20220725190635-b0ffc2fcc06a 
...
```

The [last run which failed](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-gce-conformance-latest-kubetest2/1553934086702108672) pulled the following:
```
...
go: downloading sigs.k8s.io/boskos v0.0.0-20200710214748-f5935686c7fc
...
```

Boskos at `b0ffc2fcc06a` doesn't use the deprecated `Agent` type.

When the dependencies are resolved, the only version of Boskos pulled is a really old one; hence, go install of kubetest2 is failing. To resolve this, we can try updating Boskos to the latest version in kubetest2.

**Comment by palnabarun** [comment]
Also, last night I checked with the Go 1.18 based kubekins image. Same issue happened there as well.

**Comment by palnabarun** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/207 should fix this.

**Comment by BenTheElder** [comment]
> The PR dropped Boskos as a direct dependency of k/test-infra.

yes but we’re not supposed to be using test-infra here, so there’s probably an issue with how we’re running the job, is it running under the test-infra go module?

we probably need to cd to somewhere outside of the test-infra clone if that’s the case.

**Comment by palnabarun** [comment]
> we’re not supposed to be using test-infra here

kubetest2 depends on boskos and boskos depends on test-infra. not sure how that is going to be resolved.

I agree that we should cd out of test-infra clone for a clean environment.

https://github.com/kubernetes-sigs/kubetest2/pull/207 should start resolving the current issue of usage of deprecated types from k/test-infra. We should get that in as soon as possible.

**Comment by palnabarun** [comment]
https://github.com/kubernetes-sigs/kubetest2/pull/207 merged. Let's see if the failure gets fixed.

Till then, reopening this issue.

/reopen

**Comment by BenTheElder** [comment]
I triggered a new run

**Comment by palnabarun** [comment]
The part where it was failing earlier is running fine. 🎉

**Comment by palnabarun** [comment]
Test passed! 🚀 

Closing this issue for now.

/close
