### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Fix bug and add E2E test where container image update for Deferred/Infeasible resize uses allocated values

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#111592]
### What would you like to be added?

There is a case where if user updates image of a running container that desires resource resize, it gets restarted with desired values that has not been granted by kubelet. This will cause image update to fail. We need to use checkpointed resourcesAllocated values in this case.

Please see review comment: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r932998061

### Why is this needed?

We need this to allow image update when a desired resize has not been admitted by kubelet.

**Comment by Karthik-K-N** [comment]
1. Created a local cluster with InPlacePodVerticalScaling featuregate enabled, 
2. Deployed a pod 
3. Edited pod resource to increase memory value greater than nodes capacity which lead into inplace upgrade to Infeasible state.
4. Now updated pod image to newer image

Still did not see any errors and pod still in running state, I was not able to reproduce it locally.

Any thoughts on how to reproduce would help. @vinaykul @zuoshaoyi  Thanks.
