### ISSUE TITLE
[ERROR CRI]: container runtime is not running

### ISSUE THREAD

**Issue by BoyChai** [kubernetes/kubernetes#111591]
### What happened?

[ERROR CRI]: container runtime is not running: output: E0731 22:55:10.706285 3979 remote_runtime.go:925] "Status from runtime service failed" err="rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"

### What did you expect to happen?

The solution is to delete the configuration file and restart,
```
rm -rf /etc/containerd/config.toml

systemctl restart containerd
```
The reason seems to be that this parameter of the configuration file disables the CRI of containerd
```
disabled_plugins = [“cri”]
```
However, if I leave it blank and restart it, the above error will still appear. I want to know why this problem occurs

### How can we reproduce it (as minimally and precisely as possible)?

```
curl -o /etc/yum.repos.d/docker.repo     https://download.docker.com/linux/centos/docker-ce.repo
yum -y install containerd.io
containerd config default | sudo tee /etc/containerd/config.toml
sed -i 's/systemd_cgroup = false/systemd_cgroup = true/g' /etc/containerd/config.toml
systemctl restart containerd
```
[config.txt](https://github.com/kubernetes/kubernetes/files/9230651/config.txt)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
# paste output here
$ uname -a
# paste output here
Linux s 4.18.0-348.el8.0.2.x86_64 #1 SMP Sun Nov 14 00:51:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:29:09Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
$ ctr version
Client:
  Version:  1.6.6
  Revision: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  Go version: go1.17.11

Server:
  Version:  1.6.6
  Revision: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
  UUID: 27b02df9-23f6-4ec7-b8fe-f4e3033a3896

</details>

**Comment by neolit123** [comment]
/sig node cluster-lifecycle
/kind support

please try getting help on support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close

**Comment by heisnamsanjay** [comment]
is this issue fixed? Could someone share the steps, please
