### ISSUE TITLE
resource limit does'n work when use python sub process

### ISSUE THREAD

**Issue by dennymou** [kubernetes/kubernetes#111509]
### What happened?

when i use sub process in kubernetes（A process is the main process, start B process in the same container）,and set the memrory limit（like 4G），the pod does'n oom when my pod used 6G memory（A process use 3G，B process used 3G）

### What did you expect to happen?

I want the pod oom  when A process memory + B process memory > 4G 

### How can we reproduce it (as minimally and precisely as possible)?

use python sub process can easyly reproduce it

### Kubernetes version

1.18.19

### Cloud provider

kubeadm

### OS version

centos 7.9.2009

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

docker 19.06

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
docker is no longer supported in 1.24 without a separate service cri-dockerd.

k8s versions < 1.22 are no longer supported either.

is this reproducible with containerd and newer k8s?

/sig node
/kind support

**Comment by pacoxu** [comment]
Please try it in a newer version. A reproducible step is appreciated.
For instance, you can follow #105270 example yamls, or refer to https://github.com/kubernetes/kubernetes/issues/105270#issuecomment-927747733 to investigate into oom related issues. 

/close
if you can prove it is a Kubernetes bug that [k8s version](https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md) is >= v1.22, reopen this then.
