### ISSUE TITLE
flaky conformance test `[It] [sig-api-machinery] Namespaces [Serial] should ensure that all services are removed when a namespace is deleted [Conformance]`

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#111588]
### Which jobs are flaking?

https://storage.googleapis.com/k8s-triage/index.html?test=are.removed.when.a.namespace.is.deleted

https://testgrid.k8s.io/sig-release-master-blocking#Conformance%20-%20GCE%20-%20master%20-%20kubetest2
(note: this one is currently _failing_ but you can see historically the conformance test was flaking https://github.com/kubernetes/kubernetes/issues/111584)

### Which tests are flaking?

`[It] [sig-api-machinery] Namespaces [Serial] should ensure that all services are removed when a namespace is deleted [Conformance]`

### Since when has it been flaking?

Unclear, as far back as we currently have quickly skimmable data (~7/18)

### Reason for failure (if possible)

timed out waiting for the condition

### Relevant SIG(s)

/sig api-machinery

**Comment by aojea** [comment]
I think that is related to the new e2e test that breaks the namespace controller

https://github.com/kubernetes/kubernetes/issues/111086#issuecomment-1192629817

but I couldn't verify it, as soon that test merged these namespaces tests started to flake

**Comment by Riaankl** [comment]
@aojea the e2e test  [should manage the lifecycle of an APIService [Serial][Disruptive]](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/aggregator.go#L111-L226) have been running green on the [test grid](https://testgrid.k8s.io/sig-api-machinery-gce-gke#gce-serial&include-filter-by-regex=should.manage.the.lifecycle.of.an.APIService&width=20) since it merged. 
The test [namespace-deletion-removes-services](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/namespace.go#L246-L251) from v1.11 seem to be affected by the new test. 
Do you think it is the new test breaking the expected enviroment for the old test? 
Or could it be the new test is exposing a previously unnoticed variability in the old test that should be looked at? (A lot has changed in since the test was writen :smile: )

**Comment by BenTheElder** [comment]
Another possible option: Sometimes in the past flaking tests like this have been indicative of a regression in k8s, but I think it was probably the namespace controller issue @aojea mentioned but we should keep an eye on this for a bit.

I'm seeing a different test fail now that the job is running `[It] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for multiple CRDs of same group and version but different kinds [Conformance]` 🙃

**Comment by aojea** [comment]
Definitively is the new test that is causing the problem, now we have to understand if is the test or we have a bug in the code, @smarterclayton already pointed to this possibility

Is easy to spot in this job https://testgrid.k8s.io/sig-network-gce#gci-gce-serial-kube-dns

Download the controller-manager logs, per example https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial-kube-dns/1554331963161055232/artifacts/bootstrap-e2e-master/


```
$ strings kube-controller-manager.log | grep handle | head                                                                                                                                                                                                                            
E0802 05:08:27.961548       9 resource_quota_controller.go:417] unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
W0802 05:08:28.397119       9 garbagecollector.go:752] failed to discover some groups: map[metrics.k8s.io/v1beta1:the server is currently unable to handle the request]
E0802 05:08:28.411525       9 memcache.go:206] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0802 05:08:28.421425       9 memcache.go:104] couldn't get resource list for metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0802 05:20:17.535306       9 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: taint-single-pod-5660, estimate: 30, errors: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
E0802 05:20:17.535380       9 namespace_controller.go:162] deletion of namespace taint-single-pod-5660 failed: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0802 05:23:46.960653       9 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: sched-preemption-8746, estimate: 0, errors: [unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request, unexpected items still remain in namespace: sched-preemption-8746 for gvr: /v1, Resource=pods]
E0802 05:23:46.960731       9 namespace_controller.go:162] deletion of namespace sched-preemption-8746 failed: [unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request, unexpected items still remain in namespace: sched-preemption-8746 for gvr: /v1, Resource=pods]
I0802 05:23:47.301058       9 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: sched-preemption-8746, estimate: 0, errors: [unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request, unexpected items still remain in namespace: sched-preemption-8746 for gvr: /v1, Resource=pods]
E0802 05:23:47.301132       9 namespace_controller.go:162] deletion of namespace sched-preemption-8746 failed: [unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request, unexpected items still remain in namespace: sched-preemption-8746 for gvr: /v1, Resource=pods]
```

The controllers that need to resolve the complete list of API are broken for a long time, not only during the time that the test runs cc: @liggitt @smarterclayton 

```
$ strings kube-controller-manager.log | grep handle | tail
I0802 06:34:11.423481      10 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: services-8183, estimate: 0, errors: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
E0802 06:34:11.423548      10 namespace_controller.go:162] deletion of namespace services-8183 failed: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
I0802 06:34:11.494655      10 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: nslifetest-88-2280, estimate: 0, errors: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
E0802 06:34:11.494710      10 namespace_controller.go:162] deletion of namespace nslifetest-88-2280 failed: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
I0802 06:34:11.617837      10 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: sched-pred-2740, estimate: 0, errors: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
E0802 06:34:11.617904      10 namespace_controller.go:162] deletion of namespace sched-pred-2740 failed: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
I0802 06:34:11.697811      10 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: nslifetest-35-7097, estimate: 0, errors: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
E0802 06:34:11.697875      10 namespace_controller.go:162] deletion of namespace nslifetest-35-7097 failed: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
I0802 06:34:11.812792      10 namespaced_resources_deleter.go:556] namespace controller - deleteAllContent - namespace: sched-preemption-path-1603, estimate: 0, errors: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
E0802 06:34:11.812860      10 namespace_controller.go:162] deletion of namespace sched-preemption-path-1603 failed: unable to retrieve the complete list of server APIs: e2e-gbmx5.example.com/v1alpha1: the server is currently unable to handle the request
```

**Comment by liggitt** [comment]
If we have a test intentionally creating an APIService we know won't work, that test should be disabled as a first step and reworked.

**Comment by fedebongio** [comment]
We passed here in the triage meeting today, agreed to review next meeting!

**Comment by Riaankl** [comment]
> If we have a test intentionally creating an APIService we know won't work, that test should be disabled as a first step and reworked.

@liggitt would you like us to create a PR to revert this [e2e test](https://github.com/kubernetes/kubernetes/pull/110237) or leave it a little longer for more checks?

**Comment by liggitt** [comment]
if the test is currently creating a non-functional APIService, we should drop the test and rework it
