### ISSUE TITLE
fromUnstructured does not return convert error in testing

### ISSUE THREAD

**Issue by twink7e** [kubernetes/kubernetes#111589]
### What happened?

I wrote a go test into `staging/src/k8s.io/apimachinery/pkg/runtime/conversion_test.go`
```go
package runtime

import (
	"encoding/json"
	"fmt"
	"github.com/stretchr/testify/assert"
	"reflect"
	"strconv"
	"testing"
)

type AnyString string

func ParseAnyString(val interface{}) AnyString {
	return AnyString(fmt.Sprintf("%v", val))
}

func AnyStringPtr(val interface{}) *AnyString {
	i := ParseAnyString(val)
	return &i
}

func (i *AnyString) UnmarshalJSON(value []byte) error {
	var v interface{}
	err := json.Unmarshal(value, &v)
	if err != nil {
		return err
	}
	switch v := v.(type) {
	case float64:
		*i = AnyString(strconv.FormatFloat(v, 'f', -1, 64))
	case float32:
		*i = AnyString(strconv.FormatFloat(float64(v), 'f', -1, 32))
	case int64:
		*i = AnyString(strconv.FormatInt(v, 10))
	case int32:
		*i = AnyString(strconv.FormatInt(int64(v), 10))
	case bool:
		*i = AnyString(strconv.FormatBool(v))
	case string:
		*i = AnyString(v)
	}
	return nil
}

func (i AnyString) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(i))
}

func (i AnyString) String() string {
	return string(i)
}

func TestFromUnstructured(t *testing.T) {

	raw := []string{"foo", "bar"}
	s := make([]interface{}, 2)
	for i := range raw {
		s[i] = raw[i]
	}
	d := AnyString("abc")

	sv := reflect.ValueOf(s)
	dv := reflect.ValueOf(&d)

	ctx := &fromUnstructuredContext{
		returnUnknownFields: false,
	}
	err := fromUnstructured(sv, dv.Elem(), ctx)
	assert.NotNil(t, err)
}

```

`TestFromUnstructured` This test will fail because 'frommunstructured' does not return conversion error.

### What did you expect to happen?

In my opinion, I think 'fromUnstructured' should return a conversion error in that test, but it didn't.

### How can we reproduce it (as minimally and precisely as possible)?

just run `conversion_test.go`.
you may wanted know why I will do that test. 
In fact, I found this problem during Argo Workflow test, if you want to know why,  you need to install Argo-Workflows.

see: 
``` bash
$ kubectl create ns argo
$ kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/quick-start-postgres.yaml
```
Then create a bad workflows(bad workflows test).
```bash
$ cat bad_workflows.yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: ["foo", "bar"]      # wrong type.

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message      
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
$ kubectl create -f bad_workflows.yaml
```
It will be a success. but the value type is `AnyString` I think it should got an error in that `bad workflows test` .

see `Parameters` struct: https://github.com/argoproj/argo-workflows/blob/d593228e796251aef6d22cb393288ddab9bbd4b6/pkg/apis/workflow/v1alpha1/workflow_types.go#L846

argo workflow calls `FromUnstructured` to parse Workflows see: https://github.com/argoproj/argo-workflows/blob/d593228e796251aef6d22cb393288ddab9bbd4b6/workflow/util/util.go#L136

I think in `bad workflows test`  `FromUnstructured` should returns an error.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.20+
```

</details>

### Cloud provider

<details>
alibaba cloud 
</details>

**Comment by twink7e** [comment]
Maybe moving https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L341 to L342 will solve this problem?

**Comment by alexzielenski** [comment]
Are we sure this is not a bug on argo's side? I don't see how fromUnstructured is meant to infer the intended type here. 

I also see that `UnmarshalJSON` does not have a default case, and then returns nil error in the case of a slice/map/unknown type:

```
func (i *AnyString) UnmarshalJSON(value []byte) error {
	var v interface{}
	err := json.Unmarshal(value, &v)
	if err != nil {
		return err
	}
	switch v := v.(type) {
	case float64:
		*i = AnyString(strconv.FormatFloat(v, 'f', -1, 64))
	case float32:
		*i = AnyString(strconv.FormatFloat(float64(v), 'f', -1, 32))
	case int64:
		*i = AnyString(strconv.FormatInt(v, 10))
	case int32:
		*i = AnyString(strconv.FormatInt(int64(v), 10))
	case bool:
		*i = AnyString(strconv.FormatBool(v))
	case string:
		*i = AnyString(v)
	}
	return nil
}
```

I think this is a better place to throw an error if blocking slices or maps is really intended.
