### ISSUE TITLE
PV controller tests should have all struct fields named

### ISSUE THREAD

**Issue by RomanBednar** [kubernetes/kubernetes#111659]
### What would you like to be added?

Majority of PV controller tests don't have their test struct fields named when assigning values which can make reading the tests difficult. For example [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/binder_test.go#L45).

We should name the fields explicitly like it's already done in some of the [tests](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller_test.go#L610) as suggested in [this](https://github.com/kubernetes/kubernetes/pull/111467#discussion_r934961213) discussion.

This fix should be applicable to following files:

https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/binder_test.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/delete_test.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/provision_test.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/pv_controller_test.go
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/volume/persistentvolume/recycle_test.go

### Why is this needed?

Improve test readability.

**Comment by piroux** [comment]
Hi, I would like to work on this.

**Comment by RomanBednar** [comment]
> Hi, I would like to work on this.

Awesome! Let me know if you need any help.

**Comment by piroux** [comment]
I just push my changes.
Compared knowshan, my changes correctly align the struct keys on the same column.

**Comment by RomanBednar** [comment]
@piroux thank you for the PR and welcome to the community! I suggested some minor changes, otherwise lgtm.
