### ISSUE TITLE
AdmissionReview for get and watch actions

### ISSUE THREAD

**Issue by Minh2003** [kubernetes/kubernetes#111629]
### What would you like to be added?

AdmissionReview support get and watch resources such as pods, deployments, configmaps, etc

### Why is this needed?

I'm trying to use AdmissionReview to grant access to my developer at pod level. Mutating and validating webhook has successfully, solve this problem very well at CREATE, UPDATE, DELETE, or CONNECT operations. But why we don't have any support for get and watch, describe verbs ?

**Comment by liggitt** [comment]
The intent of admission is to control inputs/changes. Get/watch/list are non-mutating, so are only gated by authorization. [Webhook authorization](https://kubernetes.io/docs/reference/access-authn-authz/webhook/) can be used on clusters you control the configuration of to gate these requests, and [audit logging](https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/) can be used to see what requests were made without blocking them. 

/close
