### ISSUE TITLE
AWS NLB registered targets remain empty on 1.24, works on 1.23.9

### ISSUE THREAD

**Issue by mariusmarais** [kubernetes/kubernetes#111637]
### What happened?

Used kops to spin up a new cluster running Kubernetes 1.24.3. 

When deploying an NLB LoadBalancer, the Registered Targets remain empty forever.

If targets are manually registered, they Health Check correctly and start working, but removing and adding nodes does not update the target group.

### What did you expect to happen?

Nodes are added to the target group once the NLB has been created.

(Depending on `Local` or `Cluster` mode, some or all would eventually be healthy, but we don't even get there.)

### How can we reproduce it (as minimally and precisely as possible)?

Spin up a new cluster. Kops currently defaults to 1.24.x.

```sh
kops create cluster \
       --cloud aws \
       --api-ssl-certificate "$ARN" \
       --master-zones eu-west-1a \
       --zones eu-west-1a \
       --master-size t3a.medium \
       --node-size t3a.large \
       --node-count 2 \
       --api-loadbalancer-class network \
       --ssh-public-key ./kubernetes-root.pub \
       --name $CLUSTER
```

Deploy an NLB load balancer in either `Cluster` or `Local` mode. See that Registered Targets in the target group remain empty after 10m.

Note: This is NOT the API LB giving problems, a normal Service with an NLB doesn't work.

### Anything else we need to know?

Exact same steps with 1.23.9 works as expected.

(kops edit cluster -> kubernetes version => 1.23.9 before spinning up the cluster)

### Kubernetes version

<details>

```console
$ kubectl version

```

</details>

### Cloud provider

AWS

### OS version

Kops default node type, Ubuntu 20.04 LTS

### Install tools

Kops 1.24.0

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Tested with Calico and kubenet networking.

**Comment by nullzone** [comment]
It is also happening to me.
For now, I am switching some environments to CLB in the meantime.

**Comment by svennjegac** [comment]
I am also experiencing the same issue.

Everything works with kubernetes version 1.23.5.
With kubernetes versions 1.24.0, 1.24.2 and 1.24.3, AWS target group stays empty forever.

I am also using kops to provision k8s cluster on AWS.

**Comment by kishorj** [comment]
@mariusmarais, for k8s 1.24, kops uses external cloud provider, and the default aws cloud provider CCM version at this time was registry.k8s.io/provider-aws/cloud-controller-manager:v1.24.0. Unfortunately, the v1.24.0 is affected by https://github.com/kubernetes/cloud-provider-aws/issues/301 which is similar to the symptoms described here. PR   https://github.com/kubernetes/cloud-provider-aws/pull/302 has the fix.

**Comment by kishorj** [comment]
Since this is not an issue with the in-tree controller, please use the repo https://github.com/kubernetes/cloud-provider-aws/  to communicate further on this matter.

**Comment by mariusmarais** [comment]
Thanks @kishorj, appreciate the pointer.

**Comment by mariusmarais** [comment]
From the other thread:
> Try setting something like this
>
>```yaml
>spec:
>  cloudControllerManager:
>    image:   registry.k8s.io/provider-aws/cloud-controller-manager:v1.24.1
>```
