### ISSUE TITLE
Affinity should be enabled when RS deletes pods

### ISSUE THREAD

**Issue by siriusa51** [kubernetes/kubernetes#111655]
### What happened?

When I configure affinity for RS, although affinity takes effect when pods are created. 
However, when RS deletes a pod, it mostly gives priority to the shorter-running PODs, instead of deleting low priority pods based on the affinity configuration for RS

### What did you expect to happen?

So I think if RS has affinity configured, then affinity should also work when deleting pods

### How can we reproduce it (as minimally and precisely as possible)?

-

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig apps scheduling
There is a proposal in https://github.com/kubernetes/enhancements/issues/3189 (some linked issues are similar.)

**Comment by kerthcet** [comment]
IMHO, we consider the start time when scaling down pod sizes for this is the reverse order of scheduling. So it makes sense in some ways, but in fact, the cluster is changing all the time, scaling up, scaling down, restarting pods etc., so pod placements will be not as expected, that's way we incubated descheduler to mitigate this situation. And I think descheduler has achieved this already.

I don't know whether this will be accepted for it introduced complexity to kubernetes and somehow overlap with descheduler in functionality. cc @damemi for advices.

**Comment by kerthcet** [comment]
Any way, it's a feature not a bug.
/remove-kind bug
/kind feature

**Comment by damemi** [comment]
This has been requested a lot. @pacoxu mentioned some of the linked issues, but I also want to call out the "pod deletion cost" KEP that I think has lost traction: https://github.com/kubernetes/enhancements/issues/2255 and another issue which requested similar considerations for pod topology spread https://github.com/kubernetes/kubernetes/issues/96748

Ultimately though, scale down is not a scheduling issue. Improvements like this can make use of scheduling libraries and plugins to make consistent decisions, but implementing that is the scaling controller's job, not the scheduler's.

Descheduler is an implementation of one controller that tries to do this, however it does not intercept scale-down events between the user and the controller, so for this use case it probably won't help.
