### ISSUE TITLE
Higher kube-apiserver memory usage k8s 1.20.15 vs 1.21.14

### ISSUE THREAD

**Issue by yuzhouliu9** [kubernetes/kubernetes#111699]
### What happened?

After upgrading k8s cluster from 1.20.15 to 1.21.14, we noticed significantly higher memory usage from kube-apiserver pods.

Below are the graphs that show clearly the difference in memory consumption before and after. The spike in the middle is when the control-plane nodes were being rolled to 1.21.

This is a plot of `container_memory_working_set_bytes`.
On 1.20.15 for leader was 5.7Gi, other pods 3Gi.
On 1.21.14 for leader is 9.6Gi, other pods 5.5Gi.
![image](https://user-images.githubusercontent.com/89029096/182935427-c1ca78d5-76f3-47c7-85c6-27f9a696f2cb.png)

However, if instead `process_resident_memory_bytes` was plotted, memory usage actually decreased.
On 1.20.15 it was 9.6Gi, on 1.21.14 it is 5.1Gi.
![image](https://user-images.githubusercontent.com/89029096/182935628-5cc9a94b-4cf5-4c61-9983-f07f09b3f38e.png)

From my understanding the difference is that `container_memory_working_set_bytes` includes active cache, but the numbers still doesn't quite make sense.
Using `node_memory_MemAvailable_bytes` the control-plane nodes have 5Gi less memory available on 1.21.14, meaning the new 1.21.14 control-plane is using much more memory.

I looked at the k8s 1.21 changelogs and did not find any entries for increased memory usage.
The cluster is quite large at ~100 nodes, with 3 control-plane nodes.

**Questions:**
Is `container_memory_working_set_bytes` an appropriate measure of kube-apiserver memory consumption?
If so, is there an explanation for increased memory usage for kube-apiserver going from 1.20.15 to 1.21.14?

### What did you expect to happen?

No significant change in kube-apiserver memory usage.

### How can we reproduce it (as minimally and precisely as possible)?

Compare `container_memory_working_set_bytes` of kube-apiserver between k8s 1.20 vs 1.21

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux ip-10-194-81-12 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker version 19.03.11
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by protosam** [comment]
@yuzhouliu9 just wanting to confirm; is your graph specifically `kube-apiserver` or is this just overall usage for a master node running both `kube-apiserver` and `etcd`?

**Comment by yuzhouliu9** [comment]
@protosam the graph is a prometheus query of just the `kube-apiserver`:  `container_memory_working_set_bytes{container="kube-apiserver"}`.
The master nodes are running both `kube-apiserver` and `etcd` though.

**Comment by protosam** [comment]
Both kube-apiserver and etcd can be masters on the same node or be on separate nodes. I'm not sure what these metrics are actually tied to, but you can figure it out by comparing them with `top`.

The relevant columns are going to be:
- `RES` - physical memory footprint without pages and cache
- `USED` - physical memory footprint and swap use without the pages and cache
- `VIRT` - physical memory footprint with pages and cache

1. Shell into a master with  ssh or the kubectl node-shell plugin.
2. Run `top`.
3. Press `shift`+`f` to open up Field Management.
4. Use arrows to highlight `USED`.
5. Press `space` to toggle it (make sure it has a *)
6. With `USED` still highlight, press `s` to sort by it
7. Press `q` to leave Field Management.
8. Press `c` to toggle command args if so desired

---

As for what to consider depends on if kube-apiserver's cache is probably going to depend on if kube-apiserver's memory footprint is heavily influenced by mmap, sockets, and other kernel managed resources.

Normally caches are not relevant for a process and can be ignored. The kernel will just manage it, depending on what it is. This is my default thought process for kube-apiserver unless I learn it does something exceptional. `RES` or `USER` is what I view for this process.

Something exceptional for me is etcd. It uses mmap which obfuscates it's memory impact. `VIRT` is what I observe for this process.

---
Sorry I don't have a clear and concise answer, but hopefully this helps you understand the metric.

Btw, I think release 1.21 is EOL now. These life cycles are crazy short.

**Comment by yuzhouliu9** [comment]
Thanks, here are the top 5 processes sorted by `USED`, on a master node.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                           USED
   7551 root      20   0 2708.7m   1.2g  43.6m S   6.3  15.6   3674:42 kube-apiserver                                                                                                                                                                                    1.2g
   7285 root      20   0   10.6g 581.1m 188.4m S   4.3   7.6   2283:39 etcd                                                                                                                                                                                            581.1m
    165 root      19  -1  532.2m 361.9m 360.0m S   0.0   4.7  12:24.47 systemd-journal                                                                                                                                                                                 361.9m
   7261 root      20   0   10.3g 246.6m  44.2m S   2.0   3.2 726:14.30 etcd                                                                                                                                                                                            246.6m
  16593 root      20   0 1153.4m 163.3m  24.9m S   1.0   2.1 485:24.23 ruby
```

With the prometheus query `container_memory_working_set_bytes{container="kube-apiserver"}` the value is 1.43GiB. So not an exact match to `RES`. I understand memory accounting in Linux is a very complicated subject, so I don't want to really dive into where the difference comes from.

Back to the original topic though. I wasn't looking to understand the metric, but rather inquire why the increased `kube-apiserver` memory usage going from 1.20 to 1.21.

**Comment by protosam** [comment]
Are you able to share svg's from pprof showing the heaps and allocs? Profiling for kube-apiserver should be enabled by default. 

They can be collected as follows.

Before starting, you need Go and `graphviz` installed to use `go tool pprof`.

Create a loopback context. This hack ensures we will be able to get to the kube-apiserver we desire.
```
kubectl config get-contexts
kubectl config set-cluster local-debugging --server=https://localhost:6443 --insecure-skip-tls-verify=true
kubectl config set-context local-debugging --cluster=local-debugging --user=PUT_AUTHINFO_USER_HERE
```

Start off in your main context. Identify the kube-apiserver pod you want to connect to. Edit the last line to ensure you connect to the right pod name and port.
```
kubectl config use-context REAL_CONTEXT_HERE
kubectl -n kube-system get pods -l k8s-app=kube-apiserver
kubectl -n kube-system port-forward pod/kube-apiserver-ip-100-123-321-33.us-east-5.compute.internal 6443:443
```

With the port-forward running, switch contexts to the debugging context and start a proxy.
```
kubectl config use-context local-debugging
kubectl proxy
```

These commands will host a web based explorer for you to find details in your browser.
```
go tool pprof -http=:6061 http://localhost:8001/debug/pprof/heap
go tool pprof -http=:6061 http://localhost:8001/debug/pprof/allocs
```

This will generate svgs that are easy to use in chrome and easy to share with other people.
```
go tool pprof -svg http://localhost:8001/debug/pprof/heap
mv profile001.svg heap.svg

go tool pprof -svg http://localhost:8001/debug/pprof/allocs
mv profile001.svg allocs.svg
```

If you just want to view the svgs in your browser.
```
go tool pprof -web http://localhost:8001/debug/pprof/heap
go tool pprof -web http://localhost:8001/debug/pprof/allocs
```

See `go tool pprof --help` for more details. There's a lot of stuff it does.

**Comment by protosam** [comment]
Forgot all about this. My problem was tons of secrets due to kops/calico or something. Almost reached a million.
```
kubectl get secrets -A > /tmp/wait-a-long-time-for-this.txt
wc -l  /tmp/wait-a-long-time-for-this.txt
```

**Comment by yuzhouliu9** [comment]
Thanks @protosam for the support. Unfortunately we've moved past this issue and continued to newer k8s releases. We'll continue to keep an eye out for resource usage changes, but the easiest practical solution is probably just upsize.

Closing this ticket now to reduce noise.
