### ISSUE TITLE
Watch cache groups all CRDs as *unstructured.Unstructured in metrics + logging

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#111605]
### What happened?

While the watch cache framework does support individual caches per CRD type, its metrics and logging treats them all as `*unstructured.Unstructured` instead of as individual group-resources. This means that any watch cache metrics related to CRDs show them as Unstructured, which is misleading; and all log messages from the watch cache code only reference Unstructured instead of the specific CRD.

### What did you expect to happen?

Watch cache metrics and log messages would indicate the CRD type

### How can we reproduce it (as minimally and precisely as possible)?

1. Create some CRDs
2. Look at metrics / log messages related to watch cache

### Anything else we need to know?

The watch cache code relies on reflection to get the type of the object. This is where everything CRD related collapses to `*unstructured.Unstructured`. 

When the cacher is being created...

https://github.com/kubernetes/kubernetes/blob/bddb4ec08ee76c98a04cc857d346fd80d44abd8f/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go#L56-L68

we have the `storageConfig`: https://github.com/kubernetes/kubernetes/blob/bddb4ec08ee76c98a04cc857d346fd80d44abd8f/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/storage_factory.go#L38

which knows about the `GroupResource`: https://github.com/kubernetes/kubernetes/blob/bddb4ec08ee76c98a04cc857d346fd80d44abd8f/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/config.go#L104

We could modify all the cacher-related structs to store the groupResource, and use that for metrics/logging, instead of the reflected object type.

### Kubernetes version

master / commit d46742b38760a1697aec56b84a3755ac7d505315

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ncdc** [comment]
/sig api-machinery

I'd be happy to work on this

**Comment by ncdc** [comment]
/retitle Watch cache groups all CRDs as *unstructured.Unstructured in metrics + logging

**Comment by aojea** [comment]
yeah, the `unstructured.Unstructured ` logs are useless and annoying :smile:

**Comment by fedebongio** [comment]
Similar context to https://github.com/kubernetes/kubernetes/issues/111604

/cc @MikeSpreitzer @deads2k 

@ncdc if we don't get a lot of traction on GH, I suggest bringing it to the meeting. Thank you for volunteering to work on this!

**Comment by ncdc** [comment]
@fedebongio 👍 I already have this implemented on my laptop (needed it for something else) & would love to contribute it back

**Comment by MikeSpreitzer** [comment]
@ncdc : can you please share what you have in some way?

**Comment by ncdc** [comment]
@MikeSpreitzer yes, let me prep a branch

**Comment by logicalhan** [comment]
The cardinality will increase drastically as a result of this though, that's something you may want to benchmark against before 'fixing' this.

**Comment by ncdc** [comment]
Cardinality in what respect?

**Comment by logicalhan** [comment]
> Cardinality in what respect?

Metric cardinality is a tensor of label values. If you go from `unstructured` to `actualnameofCRD`, you end up having many many more metrics which can (and has) hit us in the past.

**Comment by ncdc** [comment]
Ok, just making sure that's what you meant, thanks.

Maybe we should split this into 1 issue for logging, 1 issue for metrics?

**Comment by logicalhan** [comment]
Which metrics are affected by this change?

**Comment by logicalhan** [comment]
> Maybe we should split this into 1 issue for logging, 1 issue for metrics?

Yeah, logs is definitely safer..

**Comment by ncdc** [comment]
I'll need to identify the full list. Here is a specific one that I captured with my change:

```
# TYPE watch_cache_capacity gauge
watch_cache_capacity{resource="*admissionregistration.MutatingWebhookConfiguration"} 100
watch_cache_capacity{resource="*admissionregistration.ValidatingWebhookConfiguration"} 100
watch_cache_capacity{resource="*apiextensions.CustomResourceDefinition"} 100
watch_cache_capacity{resource="*certificates.CertificateSigningRequest"} 100
watch_cache_capacity{resource="*coordination.Lease"} 100
watch_cache_capacity{resource="*core.ConfigMap"} 100
watch_cache_capacity{resource="*core.Event"} 100
watch_cache_capacity{resource="*core.LimitRange"} 100
watch_cache_capacity{resource="*core.Namespace"} 100
watch_cache_capacity{resource="*core.ResourceQuota"} 100
watch_cache_capacity{resource="*core.Secret"} 100
watch_cache_capacity{resource="*core.ServiceAccount"} 100
watch_cache_capacity{resource="*flowcontrol.FlowSchema"} 100
watch_cache_capacity{resource="*flowcontrol.PriorityLevelConfiguration"} 100
watch_cache_capacity{resource="*rbac.ClusterRole"} 100
watch_cache_capacity{resource="*rbac.ClusterRoleBinding"} 100
watch_cache_capacity{resource="*rbac.Role"} 100
watch_cache_capacity{resource="*rbac.RoleBinding"} 100
watch_cache_capacity{resource="apibindings.apis.kcp.dev"} 100
watch_cache_capacity{resource="apiexports.apis.kcp.dev"} 100
watch_cache_capacity{resource="apiresourceimports.apiresource.kcp.dev"} 100
watch_cache_capacity{resource="apiresourceschemas.apis.kcp.dev"} 100
watch_cache_capacity{resource="clusterworkspaces.tenancy.kcp.dev"} 100
watch_cache_capacity{resource="clusterworkspaceshards.tenancy.kcp.dev"} 100
watch_cache_capacity{resource="clusterworkspacetypes.tenancy.kcp.dev"} 100
watch_cache_capacity{resource="locations.scheduling.kcp.dev"} 100
watch_cache_capacity{resource="negotiatedapiresources.apiresource.kcp.dev"} 100
watch_cache_capacity{resource="placements.scheduling.kcp.dev"} 100
watch_cache_capacity{resource="services"} 100
watch_cache_capacity{resource="synctargets.workload.kcp.dev"} 100
```

**Comment by logicalhan** [comment]
This is actually probably not that bad, if it only has resource as the label. It's when there are many more labels that this explosively becomes a problem.

**Comment by ncdc** [comment]
These are the unique metric types that have `watch` in their name (not all are necessarily watch cache related):
```
# TYPE apiserver_registered_watchers gauge
# TYPE apiserver_watch_cache_events_dispatched_total counter
# TYPE apiserver_watch_cache_watch_cache_initializations_total counter
# TYPE apiserver_watch_events_sizes histogram
# TYPE apiserver_watch_events_total counter
# TYPE watch_cache_capacity gauge
```

**Comment by ncdc** [comment]
I only see Unstructured in the following watch metrics:
- apiserver_watch_cache_events_dispatched_total
- apiserver_watch_cache_watch_cache_initializations_total
- watch_cache_capacity

**Comment by ncdc** [comment]
`apiserver_watch_events_sizes_*` appears to already account for CRD names correctly, rather than aggregating as Unstructured

**Comment by ncdc** [comment]
@MikeSpreitzer see https://github.com/kubernetes/kubernetes/pull/111807
