### ISSUE TITLE
Remove duplicated keys from log entry calls when contextualized logging hits GA in kube-scheduler

### ISSUE THREAD

**Issue by knelasevero** [kubernetes/kubernetes#111672]
Related to https://github.com/kubernetes/kubernetes/issues/91633 and https://github.com/kubernetes/kubernetes/pull/111155

See comments

https://github.com/kubernetes/kubernetes/pull/111155#discussion_r935961069 
https://github.com/kubernetes/kubernetes/pull/111155#discussion_r929931591
https://github.com/kubernetes/kubernetes/pull/111155#discussion_r929930775 
https://github.com/kubernetes/kubernetes/pull/111155#discussion_r935171071
https://github.com/kubernetes/kubernetes/pull/111155#discussion_r929927353

In summary, we are adding contextualized logging with https://github.com/kubernetes/kubernetes/pull/111155, but even though we use LoggerWithValues to keep our loggers with specific key values, this is still featured gated and not enabled by default.

So in every call of `logger.V(<LOGLEVEL>).Info()` or `logger.V(<LOGLEVEL>).Error`, etc, we need to pass those keys anyway if we want them to be surely showing up with contextualized logging disabled (while contextualized logging does not hit GA).

This issue here serves the purpose to remember to remove these duplicate keys (and pod/node objects being passed around only for logging) when contextualized logging hits GA and comes enabled by default.

Duplicated k/v are filtered out by klog at runtime: https://github.com/kubernetes/kubernetes/pull/111155#discussion_r935961925

**Comment by knelasevero** [comment]
remove-lifecycle stale

**Comment by ziyi-xie** [comment]
Do I understand correctly that this Issue will continue to be processed after contextual logging becomes GA?
