### ISSUE TITLE
Webhook mode in authorization

### ISSUE THREAD

**Issue by Minh2003** [kubernetes/kubernetes#111728]
### What would you like to be added?

When I write the policy for my K8s cluster, I saw the webhook mode in Authorization. Can I only use this webhook mode for all policies in my cluster?

### Why is this needed?

Admission controllers cannot enforce policies on read requests. So that, we can use only one webhook in authorization mode for all policies.

**Comment by liggitt** [comment]
admission controllers only run on write requests, but have access to the body content of the incoming requests (and existing objects, for update requests)

depending on where in the authorization chain you place an authorization webhook (using the ordered `--authorization-mode=...,Webhook,...` option), it can run on every request (other than requests made by the `system:masters` superuser group), but authorization only has access to the request attributes available in headers or the URL path, so no access to object content

depending on the policies you want to enforce, that might require you to apply those policies using admission or authorization webhooks
