### ISSUE TITLE
clean taint quickly

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#111754]
### What would you like to be added?

i hope clean taint quickly.

example , there have two taints in node01 which is a master nodes:

```
root@node01:~# kubectl describe nodes node01 | grep Taint -A1
Taints:             node-role.kubernetes.io/control-plane:NoSchedule
                    node-role.kubernetes.io/master:NoSchedule
```

if i want this nodes able to schedule pods ,i must run two commands
```
kubectl taint nodes node01 node-role.kubernetes.io/control-plane-
kubectl taint nodes node01  node-role.kubernetes.io/master-
```

The problem is the key is too long and hard to write and remember, every time i must describe nodes then copy and paste to commands, so i hope clean one or all nodes taints quickly, like

```
kubectl taint nodes node01 *-

kubectl taint nodes --all *-
```

or 
```
kubectl taint nodes node01 delete taints --all
kubectl delete taints --all -A
```

### Why is this needed?

Quickly enable the master node to schedule pods in the test environment.

**Comment by x893675** [comment]
I would like to work on this.
/assign
