### ISSUE TITLE
`kubectl delete deploy xxx --cascade='foreground'` delete pods immediately even though deployment has finalizers

### ISSUE THREAD

**Issue by FeLvi-zzz** [kubernetes/kubernetes#111725]
### What happened?

My deployment `foobar` has a finalizer `foo.example.com/bar`.
When you execute `kubectl delete deploy foobar --cascade='foreground'`, it will delete the replicasets and the pods of the deployment.

### What did you expect to happen?

When a object referred by an ownerReference and having finalizers is deleted, I expect to stop cascade propagation until deleted the finalizers when `cascade='foreground'`.

## background
When specified `background`, the pod of the deployment won't delete immediately.
```console
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  finalizers:
    - foo.example.com/bar
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
EOF

$ kubectl delete deploy nginx --cascade='background' &
[1] 94901
deployment.apps "nginx" deleted

$ kubectl get deploy nginx
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   1/1     1            1           61s

$ kubectl patch deploy nginx --type=json -p='[{"op":"remove","path":"/metadata/finalizers"}]'
deployment.apps/nginx patched
[1]+  Done                    kubectl delete deploy nginx --cascade='background'
```

## foreground
When specified `foreground`, the pod of the deployment will delete immediately in spite of having `foo.com/bar` finalizer.
```console
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  finalizers:
    - foo.example.com/bar
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
EOF

$ kubectl delete deploy nginx --cascade='foreground' &
[1] 90364
deployment.apps "nginx" deleted

$ kubectl get deploy nginx
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   0/1     0            0           54s

$ kubectl patch deploy nginx --type=json -p='[{"op":"remove","path":"/metadata/finalizers"}]'
deployment.apps/nginx patched
[1]+  Done                    kubectl delete deploy nginx --cascade='foreground'
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12", GitCommit:"b058e1760c79f46a834ba59bd7a3486ecf28237d", GitTreeState:"clean", BuildDate:"2022-07-13T14:59:18Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Amazon EKS, kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by FeLvi-zzz** [comment]
maybe related #98744.

**Comment by FeLvi-zzz** [comment]
Is this expected behavior? If correct, I'll try to fix it.

**Comment by guettli** [comment]
Maybe I am missing something, I am new to GC and owner refs.

But isn't that how foreground deletion works? 

> After the owner object enters the deletion in progress state, the controller deletes the dependents. After deleting all the dependent objects, the controller deletes the owner object. At this point, the object is no longer visible in the Kubernetes API.

Docs: https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion

**Comment by FeLvi-zzz** [comment]
Thank you for your link, I understood.
I should attach finalizers to resources which should be finalized, not to the parents of them.
controllers don't consider the order of finalizers, so I have no choice.
