### ISSUE TITLE
kubeadm init: failed to pull image even though the images had been pulled with docker

### ISSUE THREAD

**Issue by xiaojike1213** [kubernetes/kubernetes#111715]
### What happened?

**precondition:**
**kubeadm config images list**
k8s.gcr.io/kube-apiserver:v1.24.3
k8s.gcr.io/kube-controller-manager:v1.24.3
k8s.gcr.io/kube-scheduler:v1.24.3
k8s.gcr.io/kube-proxy:v1.24.3
k8s.gcr.io/pause:3.7
k8s.gcr.io/etcd:3.5.3-0
k8s.gcr.io/coredns/coredns:v1.8.6
pull the images listed above successfully with : docker pull k8s.gcr.io/*:v1.24.3
                                    
**Issues:**
**kubeadm init --config kubeadm-init.yaml**
**It always pull the images and failed to pull the image**

[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
You can also perform this action in beforehand using 'kubeadm config images pull'       [WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.24.3: output: E0805 10:38:26.818318   14704 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.3\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.3\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.3\": dial tcp [2a00:1450:4010:c03::52]:443: i/o timeout" image="k8s.gcr.io/kube-apiserver:v1.24.3"
You can also perform this action in beforehand using 'kubeadm config images pull'       [WARNING ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.24.3: output: E0805 10:38:26.818318   14704 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.24.3\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.24.3\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.24.3\": dial tcp [2a00:1450:4010:c03::52]:443: i/o timeout" image="k8s.gcr.io/kube-apiserver:v1.24.3"

### What did you expect to happen?

kubeadm init --config kubeadm-init.yaml, the command should executed successfully.

### How can we reproduce it (as minimally and precisely as possible)?

setup the kubernetes env step by step

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

```

</details>

### Cloud provider

<details>
2 CentOS 7
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"
$ uname -a
Linux k8s-master 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
19044        Microsoft Windows 10 Enterprise  64-bit          10.0.19044
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
hi. i don't think docker is your container runtime. 1.24 uses containerd by default, so you have pull with it.

for support questions please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support

**Comment by shmarsy** [comment]
https://stackoverflow.com/questions/51394387/why-is-kuberenetes-kubeadm-init-command-unable-to-pull-the-images-from-the-repos I have seen this issue i think this the right answer.
