### ISSUE TITLE
When using --serialize-image-pulls=true "Successfully pulled image" Event outputs misleading time

### ISSUE THREAD

**Issue by estebanreyl** [kubernetes/kubernetes#111704]
### What happened?

While going over Kubernetes events I noticed that image pulls for some small images were taking several minutes according to the "Successfully pulled image" event. From investigating this is misleading as the actual pull time is much smaller but due to --serialize-image-pulls=true being the default in the observed cluster and other pods being initialized at the time, the reported pull time ends up accounting for time while waiting for other pods to finish pulling. 

### What did you expect to happen?

I expected to see the time it takes to download the image itself from a registry. Customers seem to rely on this metric for this information and we have received some complaints as a result where customers noted slow pull times as a result of misunderstanding the current behavior of this metric. 

### How can we reproduce it (as minimally and precisely as possible)?

Start with a K8s cluster with --serialize-image-pulls=true (default) - For my check I used default minikube v1.26.1

1. Create pod-large where pod-large pulls any large image (the image cannot be locally cached)
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-large
spec:
  containers:
    - name: large-image
      image: roadmunk/largecontainer:latest
  restartPolicy: Never
```
2. Right after step 1 (within seconds) create pod-small where pod-small pulls any small image
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-small
spec:
  containers:
    - name: small-image
      image: busybox:latest
  restartPolicy: Never
```

Check the output for the event after running: `kubectl describe pod pod-small`
```
other info ...
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  7m41s  default-scheduler  Successfully assigned default/pod-small to minikube
  Normal  Pulling    7m39s  kubelet            Pulling image "busybox:latest"
  Normal  Pulled     2m40s  kubelet            Successfully pulled image "busybox:latest" in 4m59.26837101s
  Normal  Created    2m40s  kubelet            Created container small-image
  Normal  Started    2m39s  kubelet            Started container small-image
```

Note that despite the small size, pull time for the image in pod-small is several minutes, we should instead see it take seconds (which is how long the pull actually takes). To note this is the case you can try pulling another small image like alpine that isnt cached locally and compare after the above are done.

### Anything else we need to know?

Here is the code that pulls an image in kubernetes and logs the event:
https://github.com/kubernetes/kubernetes/blob/fbffe056dd03bd9c746e8819ad22043d640a4489/pkg/kubelet/images/image_manager.go#L156.

As can be seen from it, it's not true pull time, just time from invoking the puller to receiving a result.  The serial puller is using a Golang channel as a queue and will just wait until a previous image is done pulling as I noted before, thus it will end up recording the amount of time in the queue + pull time yielding a misleading metric. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Should reproduce anywhere (tried it on minikube) but have personally observed this in Azure as well
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
But `--serialize-image-pulls=false` means that kubelet can pull multi images at the same time.
For kubelet, `--serialize-image-pulls` is by default true. https://github.com/kubernetes/kubernetes/issues/108405 is for promoting the use of parallel image pulls.

The problem maybe with `--serialize-image-pulls=true`.

I did some simple test with 3 ubuntu images as below. The time was collected from events.
 -- | --serialize-image-pulls=false | --serialize-image-pulls=true
-- | -- | -- 
image pulling | parallel | serialize
ubuntu:22.10 73.6 MiB  |  49.18401355s  | 1m21.284220239s
ubuntu:20.04 75.7 MiB | 50.664930087s | 2m7.876426944s
ubuntu:14.04 212.9 MiB  | 1m43.026382926s | 4m52.884660938s

**Comment by estebanreyl** [comment]
You are right @pacoxu, thanks for taking a look at this. It seems I got the two reversed in my head. The issue indeed happens when --serialize-image-pulls=true which is the default as you pointed out. I'll update the issue to reflect that
