### ISSUE TITLE
Fix godocs autoformatting from upgrading to go 1.19

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#111701]
### What happened?

Reference Comment: https://github.com/kubernetes/kubernetes/pull/111254#issuecomment-1195794968

Based on the diff: https://github.com/kubernetes/kubernetes/pull/111254/files, there are a couple areas where indentations are turned into paragraphs, indentations are turning regular comments into code blocks, etc.

I think there are a couple things we need to do (could be in separate PRs):

1. Scan the original PR (see above) and fix the indentations in places where a paragraph is not supposed to occur. A good example is https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/cmd/kube-apiserver/app/testing/testserver.go#L96-L99
2. Some indentations should be changed into lists, eg: https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/pkg/apis/core/types.go#L3222-L3226
3. Unrelated to the previous PR, scan the k8s types and reformat bullet points using `*` to use `-`. go1.19 does not recognize `*` as bullet points. For example: https://github.com/dims/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/staging/src/k8s.io/api/core/v1/types.go#L495-L496
4. Ensure our swagger doc generation properly supports the new list format  https://github.com/kubernetes/kubernetes/pull/111505

I hope this roughly captures the intent of the comment by liggitt.
/cc @liggitt 
/cc @dims 

/help

### What did you expect to happen?

See above

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Darshnadas** [comment]
I won't be able to work on this, due to other work commitments. Hence, unassigning myself, anyone feel free to take upon this issue.

**Comment by Santosh1176** [comment]
Hey can I work on this?

**Comment by liggitt** [comment]
Created https://github.com/kubernetes/kubernetes/pull/114559 to resolve this
