### ISSUE TITLE
"kubectl rollout history" produces wrong entry when --record not explictly used in "set image"

### ISSUE THREAD

**Issue by yucer** [kubernetes/kubernetes#111732]
### What happened?

Following [this](https://github.com/karthequian/Kubernetes/tree/master/04_04_Rolling_updates) tutorial and did:

```
$ kubectl create -f helloworld-black.yaml --record

Flag --record has been deprecated, --record will be removed in the future
deployment.apps/navbar-deployment created
service/navbar-service created

$ kubectl set image deployment/navbar-deployment helloworld=karthequian/helloworld:blue

deployment.apps/navbar-deployment image updated

$ kubectl rollout history deployments/navbar-deployment

deployment.apps/navbar-deployment 
REVISION  CHANGE-CAUSE
1         kubectl create --filename=helloworld-black.yaml --record=true
2         kubectl create --filename=helloworld-black.yaml --record=true
```

### What did you expect to happen?

```
deployment.apps/navbar-deployment 
REVISION  CHANGE-CAUSE
1         kubectl create --filename=helloworld-black.yaml --record=true
2         kubectl set image deployment/navbar-deployment helloworld=karthequian/helloworld:blue --record=true
```

### How can we reproduce it (as minimally and precisely as possible)?

The behavior can be reproduced as described before (in *What happened*). 

The expected result can be achieved by explicit using `--record` in the `set image` command, like this:

`$ kubectl set image deployment/navbar-deployment helloworld=karthequian/helloworld:blue --record`

### Anything else we need to know?

The tutorial was created with a previous version of `minikube` (1.9.2) and `kubectl` (1.18.2) and it doesn't include the use of `--record`.
Nevertheless, the [video](https://www.linkedin.com/learning/learning-kubernetes/handling-application-upgrades) (2:06) shows the expected behavior.  

Is that a regression ? Or a change of behavior for the `--record` parameter of the `set image` sub command?

### Kubernetes version

<details>

```console
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Running locally `minikube` ...

```
$ minikube version

minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a

Linux ws6 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
> $ kubectl create -f helloworld-black.yaml --record
> 
> Flag --record has been deprecated, --record will be removed in the future
> deployment.apps/navbar-deployment created
> service/navbar-service created

It seems like this feature has been deprecated as the warning message said.
Maybe this feature should be no longer maintained.

https://github.com/kubernetes/kubernetes/issues/40422

**Comment by yucer** [comment]
> It seems like this feature has been deprecated as the warning message said.
Maybe this feature should be no longer maintained.

Thanks. I can see your point.

The big question is: 

>  Should a deprecated feature work well until its removal ?

I guess so. Maybe somebody is using it.

I can also understand that the transition to a new feature might generate temporary regressions, this might be the case.
