### ISSUE TITLE
Regression in client-go >= v1.24.0 metrics lead to explosion in label cardinality

### ISSUE THREAD

**Issue by aanm** [kubernetes/kubernetes#111750]
### What happened?

Hello,

we have been using client-go [`LatencyMetric` interface](https://github.com/cilium/cilium/blob/v1.12.0/vendor/k8s.io/client-go/tools/metrics/metrics.go#L40-L43) to measure the latency for all client-go traffic from Cilium to kube-apiserver. We have [recently found out](https://github.com/cilium/cilium/issues/20810) that since v1.24.0 the URL path is no longer aggregated in a way that this cardinality would no longer happen as presented in the following image:

<img width="330" alt="Screen Shot 2022-08-08 at 10 18 24 AM" src="https://user-images.githubusercontent.com/5714066/183476699-734bed16-a388-4afc-acfa-416bb57e30eb.png">

It seems this functionality was removed as a part of https://github.com/kubernetes/kubernetes/pull/106911 as it seems that PR only took into account that users of the `LatencyMetric` would only be using it to measure latency to a particular host and not for a particular URL path as we are doing in [here](https://github.com/cilium/cilium/blob/v1.12.0/pkg/k8s/watchers/watcher.go#L287-L289).

Would it be reasonable to revert commit https://github.com/kubernetes/kubernetes/pull/106911/commits/bebf5a608f68523fc430a44f6db26b16022dc862 in order to fix this regression?

Thanks
cc @wojtek-t @aojea @liggitt

**Comment by aojea** [comment]
But reverting will bring back the cardinality problem, will not?

The latency of each URL path is available in the apiserver metrics ...

**Comment by aanm** [comment]
> But reverting will bring back the cardinality problem, will not?
> 
> The latency of each URL path is available in the apiserver metrics ...

We have never faced any cardinality problem with the previous code since we were not using the "host" field which is what I assume the original issue about cardinality was trying to fix. We only used the "path" of an URL, which was aggregated in a way that would not be facing any cardinality, like the figure attached in this GH description. Now each `{namespace}` and `{name}` is actually a different value which does cause the cardinality problem to appear.

**Comment by aojea** [comment]
ah, I see the disconnection, I wasn't understanding the issue sorry.

The Interface uses the url as parameter to keep backwards compatibility, but the method that gathers the metrics only uses the host to avoid the cardinality problem.

https://github.com/kubernetes/kubernetes/pull/106539

You have to update the method that gathers the metrics to only use the host part of the url

**Comment by aojea** [comment]
it seems you override the LatencyMetrics adapter and use the path directly

https://github.com/cilium/cilium/blob/896aba311809f7dd60d50e9791ae27cf2b74a3e5/pkg/k8s/watchers/watcher.go#L92-L98

**Comment by aojea** [comment]
Filed https://github.com/cilium/cilium/pull/20835

**Comment by aojea** [comment]
@dgrisonnet should fix the code in kubernetes ? 

```diff
diff --git a/staging/src/k8s.io/client-go/rest/request.go b/staging/src/k8s.io/client-go/rest/request.go
index dba933f7d6f..cf51fd62d9e 100644
--- a/staging/src/k8s.io/client-go/rest/request.go
+++ b/staging/src/k8s.io/client-go/rest/request.go
@@ -537,7 +537,10 @@ func (r *Request) tryThrottleWithInfo(ctx context.Context, retryInfo string) err
                // but we use a throttled logger to prevent spamming.
                globalThrottledLogger.Infof("%s", message)
        }
-       metrics.RateLimiterLatency.Observe(ctx, r.verb, *r.URL(), latency)
+       // strip path to avoid metrics cardinality explosion
+       u := *r.URL()
+       u.Path = ""
+       metrics.RateLimiterLatency.Observe(ctx, r.verb, u, latency)
 
        return err
 }
@@ -826,7 +829,10 @@ func (r *Request) request(ctx context.Context, fn func(*http.Request, *http.Resp
        // Metrics for total request latency
        start := time.Now()
        defer func() {
-               metrics.RequestLatency.Observe(ctx, r.verb, *r.URL(), time.Since(start))
+               // strip path to avoid metrics cardinality explosion
+               u := *r.URL()
+               u.Path = ""
+               metrics.RequestLatency.Observe(ctx, r.verb, u, time.Since(start))
        }()
 
        if r.err != nil {
```

however, that will break consumer of the Interface that still wants to process the path, but we know using the path will cause issues with cardinality :shrug:

**Comment by dgrisonnet** [comment]
I would be fine with adding a new `path` label to mitigate that issue since originally the cardinality explosion that was reported was caused by the query string and not the path: https://github.com/kubernetes/kubernetes/issues/106538. When trimming down the whole URL to only the host we even had a discussion to keep the path, but we decided not to since we didn't have any use case for this data.

If you have a use case where you need the path in order to get more granularity on the latency of your network then I would be fine with adding the label to Kubernetes, but another path forward could be to also remove the path information from cilium if deemed unnecessary. In the most common scenarios, you will only need the host to get the network latency based on different proxy routes.

**Comment by dgrisonnet** [comment]
@aojea yeah we can't really do much about it, it is either we leak the unsanitized paths or we prevent the users from using the path completely. Since we want to not break the interface and keep the URL parameter, we might just have to keep sanitizing the paths for our consumers even though we are not using the path anymore.

**Comment by aojea** [comment]
> I would be fine with adding a new `path` label to mitigate that issue since originally the cardinality explosion that was reported was caused by the query string and not the path: #106538. When trimming down the whole URL to only the host we even had a discussion to keep the path, but we decided not to since we didn't have any use case for this data

IIUIC the RESTClient is used in the dynamic client-go too, for these users with 1900 CRDs, the path is really going to explode for them https://github.com/kubernetes/kubernetes/pull/111477

> With this single logger and ~1,900 CRDs loaded I'm seeing the API server using from 5.5 to 6.5 GiB RSS as garbage collection sawtooths. That's a saving of at least 1GiB.

**Comment by dgrisonnet** [comment]
Then it seems that the best option to not break users would be to revert https://github.com/kubernetes/kubernetes/commit/bebf5a608f68523fc430a44f6db26b16022dc862, but at the same time I don't really like the idea of spending CPU time sanitizing something that will never be used in the RESTClient

**Comment by aanm** [comment]
> > I would be fine with adding a new `path` label to mitigate that issue since originally the cardinality explosion that was reported was caused by the query string and not the path: #106538. When trimming down the whole URL to only the host we even had a discussion to keep the path, but we decided not to since we didn't have any use case for this data
> 
> IIUIC the RESTClient is used in the dynamic client-go too,
> 
> https://github.com/kubernetes/kubernetes/blob/a837be03ffea65115a90b4bc4a8092d9b842971e/staging/src/k8s.io/client-go/dynamic/simple.go#L34-L36
> 
> for these users with 1900 CRDs, the path is really going to explode for them #111477
> 
> > With this single logger and ~1,900 CRDs loaded I'm seeing the API server using from 5.5 to 6.5 GiB RSS as garbage collection sawtooths. That's a saving of at least 1GiB.

A suggestion would be to create a new interface similar to the `LatencyMetric` that would have the following method:
```golang
// LatencyMetricByHost observes client latency partitioned by verb and host.
type LatencyMetricByHost interface {
	Observe(ctx context.Context, verb string, host string, latency time.Duration)
}
```

Thus, those users with 1900 CRDs would use the `LatencyMetricByHost` instead of the `LatencyMetric`.

**Comment by aanm** [comment]
@aojea after digging a little bit the underlying issue it looks that the problem was initially caused by a kubelet bug as pointed out [here](https://github.com/prometheus-operator/kube-prometheus/pull/1499#issuecomment-973117877).

The dependents of client-go don't have access to all the fields of the `Request` struct which `finalURLTemplate` uses heavily to generate the aggregated URL.
