### ISSUE TITLE
API resonse error

### ISSUE THREAD

**Issue by painsAgains** [kubernetes/kubernetes#111710]
### What happened?
/wg api-expression
when I use a API request to get a non-existent component "fuzzing"status,I got 500 response code. 
The request content as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```
And the response content as shown below:
```
"response": {
          "ResponseData": {
            "code": 500,
            "codeDescription": "Internal Server Error",
            "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Component not found: fuzzstring\",\"code\":500}\n",
            "isFailure": true,
            "isBug": true
          }
        }
```

### What did you expect to happen?

If the conponent is non-existent, I think I should recieve a **40x response code**,not the **500 response code**.

### How can we reproduce it (as minimally and precisely as possible)?

Send the request as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```

### Kubernetes version

<details>

```console
$ kubectl version
v1.18.0
```

</details>

### Cloud provider

<details>
Local Virtual Machine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux k8s-master 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by painsAgains** [comment]
### What happened?
/wg API Expression
when I use a API request to get a non-existent component "fuzzing"status,I got 500 response code. 
The request content as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```
And the response content as shown below:
```
"response": {
          "ResponseData": {
            "code": 500,
            "codeDescription": "Internal Server Error",
            "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Component not found: fuzzstring\",\"code\":500}\n",
            "isFailure": true,
            "isBug": true
          }
        }
```

### What did you expect to happen?

If the conponent is non-existent, I think I should recieve a **40x response code**,not the **500 response code**.

### How can we reproduce it (as minimally and precisely as possible)?

Send the request as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```


### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.18.0
```

</details>


### Cloud provider

<details>
Local Virtual Machine
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux k8s-master 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by painsAgains** [comment]
### What happened?
/wg API
when I use a API request to get a non-existent component "fuzzing"status,I got 500 response code. 
The request content as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```
And the response content as shown below:
```
"response": {
          "ResponseData": {
            "code": 500,
            "codeDescription": "Internal Server Error",
            "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Component not found: fuzzstring\",\"code\":500}\n",
            "isFailure": true,
            "isBug": true
          }
        }
```

### What did you expect to happen?

If the conponent is non-existent, I think I should recieve a **40x response code**,not the **500 response code**.

### How can we reproduce it (as minimally and precisely as possible)?

Send the request as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```


### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.18.0
```

</details>


### Cloud provider

<details>
Local Virtual Machine
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux k8s-master 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by painsAgains** [comment]
### What happened?
/wg api-expression
when I use a API request to get a non-existent component "fuzzing"status,I got 500 response code. 
The request content as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```
And the response content as shown below:
```
"response": {
          "ResponseData": {
            "code": 500,
            "codeDescription": "Internal Server Error",
            "content": "{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Component not found: fuzzstring\",\"code\":500}\n",
            "isFailure": true,
            "isBug": true
          }
        }
```

### What did you expect to happen?

If the conponent is non-existent, I think I should recieve a **40x response code**,not the **500 response code**.

### How can we reproduce it (as minimally and precisely as possible)?

Send the request as follows:
```
"request": {
          "RequestData": {
            "method": "GET",
            "path": "/api/v1/componentstatuses/fuzzstring",
            "query": "pretty=fuzzstring",
            "body": ""
          }
```


### Anything else we need to know?

_No response_

### Kubernetes version

<details>

```console
$ kubectl version
v1.18.0
```

</details>


### Cloud provider

<details>
Local Virtual Machine
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux k8s-master 5.4.0-122-generic #138~18.04.1-Ubuntu SMP Fri Jun 24 14:14:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by apelisse** [comment]
Agree, that looks like a bug.

**Comment by apelisse** [comment]
Though, as far as I can see, ComponentStatus is deprecated since 1.19 so I don't know if we'll want to fix bugs for this right now.

**Comment by painsAgains** [comment]
Thanks for your reply,I will try to update my version



发自我的iPhone


------------------ Original ------------------
From: Antoine Pelisse ***@***.***&gt;
Date: Thu,Aug 11,2022 1:08 AM
To: kubernetes/kubernetes ***@***.***&gt;
Cc: painsAgains ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [kubernetes/kubernetes] API resonse error (Issue #111710)





 
Though, as far as I can see, ComponentStatus is deprecated since 1.19 so I don't know if we'll want to fix bugs for this right now.

**Comment by dims** [comment]
closing per last comment from @apelisse
