### ISSUE TITLE
When the number of replicas of the deployment decreases, execute kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/metrics/resource or kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/stats/summary, it gets stuck

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#111738]
### What happened?

When the number of replicas of the deployment decreases, execute `kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/metrics/resource` or `kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/stats/summary`, it gets stuck

### What did you expect to happen?

get data in time when execute `kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/metrics/resource` or `kubectl get --raw /api/v1/nodes/$NODE_NAME/proxy/stats/summary`

### How can we reproduce it (as minimally and precisely as possible)?

1 Deploy k8s cluster
2 Deploy a deployment of 6 replicas
3 Resize deployment to 2 replicas

### Anything else we need to know?

cgroupv2 is used

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
# paste output here
Linux ubuntu 5.19.0-051900-generic #202207312230 SMP PREEMPT_DYNAMIC Sun Jul 31 22:34:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.23.0
RuntimeApiVersion:  v1alpha2

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dashpole** [comment]
This may be a container runtime issue.  Can you try `crictl stats` from the node when the issue is happening?  That will let us know how long those calls are taking.  You may also be able to look at metrics from the the kubelet's /metrics endpoint to see the latency of CRI requests by operation

**Comment by yangjunmyfm192085** [comment]
@dashpole, thanks for reminding
yeah, I think you are right, after I execute the following command `kubectl scale --replicas=2 deployment/busybox-deployment` when executing crictl stats again, it is also stuck, cost about 30s.
![image](https://user-images.githubusercontent.com/69306452/184303482-26adb2bc-8b50-45f8-818d-bc4a8745ee50.png)

It is found that when the pod is deleted, the stuck time of `crictl stats` is consistent with the terminationGracePeriodSeconds of the pod.

**Comment by dashpole** [comment]
Can you reproduce it without kubernetes?  Just stop a container with crictl and call `crictl stats`?  If that is possible, you should probably open an issue with the container runtime you are using.

**Comment by yangjunmyfm192085** [comment]
When I use the command `crictl stop --timeout 30 containerid` to stop the container, yes, executing the command `crictl stats` also gets stuck for 30s
I have opened one issue [#6147](https://github.com/cri-o/cri-o/issues/6147)  in cri-o repo.

**Comment by dgrisonnet** [comment]
@yangjunmyfm192085 has your issue been resolved by https://github.com/cri-o/cri-o/issues/6147#issuecomment-1224282819? If so I think we should close this one.

**Comment by yangjunmyfm192085** [comment]
yeah.
/close
