### ISSUE TITLE
Improve ClusterCIDR metrics

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#111711]
Opening issue for tracking purpose based on feedback from sig instrumentation

> It might be clearer for admins to expose one metric containing the CIDRs limit and one containing the current number of allocated CIDRs. Otherwise, they will only know that the percentage is high but they won't really know how many allocations they can still make, they would have to look at the configuration in order to get that information.

_Originally posted by @dgrisonnet in https://github.com/kubernetes/kubernetes/pull/109090#discussion_r934612254_

**Comment by aryan9600** [comment]
hi, i'd like to work on this, if that's okay
/assign
