### ISSUE TITLE
cgroup cpuset is not updated for the running Pods when a Pod is deleted

### ISSUE THREAD

**Issue by didovesei** [kubernetes/kubernetes#111705]
### What happened?

When a Pod with integer cpuset (dedicated CPU cores) is deleted, the cpusets of the cgroups for the rest Pods are not updated.

For example, we have Pod A is assigned 1 CPU (core 4) and Pod B which requesting 200m CPU. The cgroup files for these two Pods would look like:

```
➜  kubepods.slice cat kubepods-podf699fac4_730c_4dfe_aee8_1f2cccb236cc.slice/cri-containerd-8614725e537319cf483e0060f4cce30c0c5aaeba8859e0f346b966c8914db24f.scope/cpuset.cpus
4

➜  kubepods.slice cat kubepods-burstable.slice/kubepods-burstable-podf7d5d40c_9bc8_4289_8cf3_3b6696644665.slice/cri-containerd-6a824821599aebd932b0dd764e7a5ae4eb954d426af429711b9e040a277476d4.scope/cpuset.cpus
0-3,5-7
```

However, when Pod A is deleted, the cpuset for Pod B is not updated. It's still `0-3,5-7` whereas I expected it to become `0-7`.

### What did you expect to happen?

When Pod A is deleted, I expected the cpuset for Pod B to become `0-7`.

### How can we reproduce it (as minimally and precisely as possible)?

- Use `static` CPU manager policy for Kubelet.
- Apply two Pods:
    -  Pod A is in the guranteed QoS class with integer CPU limit
    -  Pod B is not in the guranteed QoS class.
- Examine the cpusets for the two Pods:
    - cpuset A is a dedicated core;
    - cpuset B is a range excluding the one assigned to the other Pod.
- Delete the Pod A.
- Examine the cpusets for Pod B: it's supposed to be restored to the whole host core range but in fact it is not updated.

### Anything else we need to know?

Having investigated the code, it seems that when a Pod is deleted, we do not clean up the `pendingAdmissionPod` cache in CPU manager struct.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/cpumanager/cpu_manager.go#L142

### Kubernetes version

Kubelet v1.23.5.

### Cloud provider

N/A

**Comment by pacoxu** [comment]
/retitle cgroup cpuset is not updated for the running Pods when a Pod is deleted
/cc @klueska
The cpuset is generated when pod is started. It is not dynamic cpuset.
Recreating the pod will trigger the cpuset change.

I prefer to think this is expected. To make it dynamic, this would be a feature in my opinion.
/kind feature

**Comment by didovesei** [comment]
> The cpuset is generated when pod is started. It is not dynamic cpuset.

When a Pod with dedicated CPUs is created, the `cpuset`s of the existing Pods' are updated. I would expect those existing Pods' `cpuset`s are also updated when the "dedicated" Pod is deleted.

**Comment by klueska** [comment]
I believe this is a duplicate of this: https://github.com/kubernetes/kubernetes/issues/107074

**Comment by didovesei** [comment]
> I believe this is a duplicate of this: #107074

+1. Didn't see that issue before but seems to me it is same one.
