### ISSUE TITLE
Specifing --client-ca-file for apiserver does't work

### ISSUE THREAD

**Issue by lixiaoyuner** [kubernetes/kubernetes#111774]
### What happened?

I want to add an extra CA to APIserver for authentication. So, I copy /etc/kubernetes/pki/ca.crt to /etc/kubernetes/pki/mul_ca.crt and add an extra CA to the mul_ca.crt file and change apiserver yaml file to specify --client-ca-file to /etc/kubernetes/pki/mul_ca.crt and use the extra CA and its key to generate a kubeconfig which has admin permission (means I specify the cert Organization to system:masters), and access to APIserver by kubectl with this kubeconfig. But it failed with error "Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")"

### What did you expect to happen?

--client-ca-file string
  | If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.

Above is official document, I see it mentioned "one of the authorities", I think I can add extra CA for apiserver authentication.
I expect that the kubeconfig I generated from the extra CA can work.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a k8s cluster, and copy /etc/kubernetes/pki/ca.crt to /etc/kubernetes/pki/mul_ca.crt and add an extra CA to the mul_ca.crt file and change apiserver yaml file to specify --client-ca-file to /etc/kubernetes/pki/mul_ca.crt and use the extra CA and its key to generate a kubeconfig which has admin permission (means I specify the cert Organization to system:masters), and access to APIserver by kubectl with this kubeconfig

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/remove-kind bug
/kind support

The "Unable to connect to the server" message looks like the client is failing to verify the *server's* certificate, not the other way around. Before you modified these CA files and the kube-apiserver invocation, were you able to connect successfully to the server?

**Comment by enj** [comment]
/close

Due to lack of response (and this does not look like a bug).
