### ISSUE TITLE
log in desired_state_of_world.go seems to be wrong

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#111753]
### What happened?

log in pkg/kubelet/pluginmanager/cache/desired_state_of_world.go seem to be wrong 
[`klog.V(2).InfoS("Plugin exists in actual state cache, timestamp will be updated", "path", socketPath)`](https://github.com/kubernetes/kubernetes/blob/aea9f9887d08922378b9e7da0e81a46e733f2995/pkg/kubelet/pluginmanager/cache/desired_state_of_world.go#L131)

It seems to be a copy-and-paste typo.
[
`klog.V(2).InfoS("Plugin exists in actual state cache", "path", pluginInfo.SocketPath) `](https://github.com/kubernetes/kubernetes/blob/aea9f9887d08922378b9e7da0e81a46e733f2995/pkg/kubelet/pluginmanager/cache/actual_state_of_world.go#L94)

### What did you expect to happen?

fix this bug

### How can we reproduce it (as minimally and precisely as possible)?

just take a look 

### Anything else we need to know?

this issue is related to pr #111634

### Kubernetes version

<details>
the latest master branch
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by KunWuLuan** [comment]
[sig/node](https://github.com/kubernetes/kubernetes/labels/sig%2Fnode)

**Comment by KunWuLuan** [comment]
/assign @saad-ali
thanks

**Comment by pacoxu** [comment]
/sig node
As you have already submitted the PR to fix this issue, you can comment `/assign` to assign it to yourself.

**Comment by KunWuLuan** [comment]
> /sig node As you have already submitted the PR to fix this issue, you can comment `/assign` to assign it to yourself.

thanks for the help
