### ISSUE TITLE
Kubernetes rejects overlapping mounts

### ISSUE THREAD

**Issue by gilbahat** [kubernetes/kubernetes#111737]
### What happened?

A combination of admission control and pod definitions have created overlapping mount instruction (i.e. mounting the same directory twice).
This is a configuration that kubernetes can service by ignoring the duplication, but it opts for overzealousness and refuses to schedule the pods instead.

### What did you expect to happen?

I would have expected kubernetes to issue a warning rather than treat this configuration as unserviceable

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new pod with 2 mounts both pointing to the same directory

### Kubernetes version

v1.22.10-eks-84b4fe6

### Cloud provider

AWS EKS

**Comment by BenTheElder** [comment]
For what it's worth: docker will also refuse to run a container with duplicate mount points:
```
$ docker run --rm -v $(pwd):/foo -v $(pwd)/test:/foo -it ubuntu
docker: Error response from daemon: Duplicate mount point: /foo.
See 'docker run --help'.
```

I don't think discarding one of the mounts is a good idea, this is either an unintended or impossible configuration.

**Comment by gilbahat** [comment]
> For what it's worth: docker will also refuse to run a container with duplicate mount points:
> 
> ```
> $ docker run --rm -v $(pwd):/foo -v $(pwd)/test:/foo -it ubuntu
> docker: Error response from daemon: Duplicate mount point: /foo.
> See 'docker run --help'.
> ```
> 
> I don't think discarding one of the mounts is a good idea, this is either an unintended or impossible configuration.

Thank you for this, because this allows me to highlight also how the complexity of k8s related tooling (helm templating and admission control) makes this more of a problem than docker.

What negative impact would you see in aggregating the mounts?

**Comment by BenTheElder** [comment]
> Thank you for this, because this allows me to highlight also how the complexity of k8s related tooling (helm templating and admission control) makes this more of a problem than docker.

FWIW: helm is not part of the Kubernetes project, and standard admission controllers shouldn't be adding duplicate mounts (?) ... Maybe EKS has a custom one?

I _personally_ don't recommend templating for config management over patching like kustomize etc. or perhaps programmatically manipulating the API types in your preferred language.


> What negative impact would you see in aggregating the mounts?

I'm not sure what you mean by "aggregate"? 

Only one thing can be mounted at a specific path, that limitation is inherent in linux / the filesystem, so options would seemingly be either: 1) ignoring all but one of the mounts to that path or 2) rejecting it as invalid.

Docker and Kubernetes choose 2). As far as I now so does podman and pretty much any other tool manipulating mounts.

If we instead ignored all but one of the multiple things configured to mount at the same path, that can lead to accidents like "you meant to mount your database on a persistent volume but actually we ignored that and used the duplicate mount that is a temp filesystem" which will probably be discovered by the user too late.

It would be a significant breaking change to begin doing this.

If we reject the impossible case of mounting two things to the same path, it's apparent early when the pod is rejected that something else is broken (the pod configuration, or possibly a rogue mutating admission controller).

Anyhow, this is up to SIG Node / SIG Storage approvers, but I doubt they want to change this behavior for the reasons mentioned here.

**Comment by pacoxu** [comment]
> If we instead ignored all but one of the multiple things configured to mount at the same path, that can lead to accidents like "you meant to mount your database on a persistent volume but actually we ignored that and used the duplicate mount that is a temp filesystem" which will probably be discovered by the user too late.

This would introduce more potential issues than benefits.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

There is no universal way for kubernetes to resolve this. If there is specific policy (like pick the first) that may work in certain scenarios, it may be implemented outside k8s.

/close
