### ISSUE TITLE
DNS Configmap tests sometimes panics in ipv6 envs

### ISSUE THREAD

**Issue by tylerschultz** [kubernetes/kubernetes#111700]
### Which jobs are flaking?

We've seen this line of [test/e2e/network/dns_configmap.go:301](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns_configmap.go#L301) panic from time to time. It is caused by an index out of bounds. The array length check on that line seems to be incorrect.

We see this flakiness when running in ipv6 or dualstack-ipv6-primary environments.

We do not see this flakiness in ipv4 environments.

### Which tests are flaking?

 [test/e2e/network/dns_configmap.go:301](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns_configmap.go#L301)

### Since when has it been flaking?

We've seen these flakes over several months.

### Reason for failure (if possible)

incorrect array length check on [test/e2e/network/dns_configmap.go:301](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/dns_configmap.go#L301), and the right most `array[1]` is out of bounds.

### Relevant SIG(s)

/sig

**Comment by dims** [comment]
/milestone 1.25

as this is a networking conformance test that fails

**Comment by aojea** [comment]
thanks for catching it

**Comment by tylerschultz** [comment]
There is confusion whether or not this is a conformance test. We don't believe it is. The test description does not include `[Conformance]`. I'll remove the label.
