### ISSUE TITLE
Statefulset never create pod when one of replica pod  create failed 

### ISSUE THREAD

**Issue by chaohan1** [kubernetes/kubernetes#111778]
### What happened?

In our k8s cluster，I create a statefulset named test-sts with replicas=3 and podManagementPolicy=Parallel. The statefulset create replica test-sts-1 failed if the pod test-sts-1 has already exists，then the statefulset never create replica test-sts-2, and never update statefulset status。

In the issue 109694, it fixed statefulset update status when replica pod create failed.
[root@master2 test]# kubectl get sts,pod |grep test-sts
statefulset.apps/test-sts   0/3     40m
pod/test-sts-0                            1/1     Running       0          40m
pod/test-sts-1                            1/1     Terminating   0          42m

### What did you expect to happen?

I think the podManagementPolicy setting Parallel  means all repilcas of statefulset is created parallel. Even though one of pod create failed, should not affect others pod creating.  So, even though test-sts-1 create failed, test-sts-2 should be created.

I want to know what i think above is crrect or not???

### How can we reproduce it (as minimally and precisely as possible)?

1. create statefulset test-sts with replicas=3 and podManagementPolicy=Parallel;
2. stop kubelet where replica test-sts-1 on;
3. delete statefulset test-sts, wait for test-sts-0 and test-sts-1 deleted;
4. create statefulset test-sts again;
5. we can see that test-sts-2 is not created;

### Kubernetes version

<details>
```console
$ kubectl version
# paste output here
```
[root@master2 test]# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.19.4-20220804+935fb54a01d4bc5c09da631bbef69df923fe7f11", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4-20220804+935fb54a01d4bc5c09da631bbef69df923fe7f11", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig apps

> GitVersion:"v1.19.4-

< 1.22 versions are out of support

**Comment by chaohan1** [comment]
> /sig apps
> 
> > GitVersion:"v1.19.4-
> 
> < 1.22 versions are out of support

I am sorry，what is means of 1.22 versions are out of support?
