### ISSUE TITLE
--validate does not work for `kubectl patch`

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#11173]
For example, if I run

```
$ kubectl patch --validate pod valid-pod -p '{"spec":{"name":"true"}}'
valid-pod
```

though spec.name is not a valid field, `--validate` does not report an error.

@nikhiljindal @bgrant0607

**Comment by caesarxuchao** [comment]
It's still valid at HEAD,

```
$ kubectl patch pod cassandra -p '{"spec":{"name":"true"}}'
"cassandra" patched
```

**Comment by caesarxuchao** [comment]
The reason is there is no field named spec.name on the pod struct, the strategicpatch.Merge() function will just add such a field to the pod object ([here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go#L539), marshal the patched object to JSON, and the field is ignored during unmarshal [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/apiserver/resthandler.go#L463).

To detect such invalid patch, we should check if the field is valid [here]([here](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/strategicpatch/patch.go#L539).

**Comment by kargakis** [comment]
@caesarxuchao is this still an issue?

**Comment by caesarxuchao** [comment]
`kubectl patch` doesn't support `--validate` anymore. Also, if an invalid patch is sent, kubectl will report "object is not patched". So it's fixed.
