### ISSUE TITLE
port-forward cannot handle the connection

### ISSUE THREAD

**Issue by sxllwx** [kubernetes/kubernetes#111742]
### What happened?

When we use port-forward to forward traffic, there is a situation where the connection cannot be processed.

> kubectl port-forward output

```
[root@VM-247-91-centos /tmp]# ./kubectl  port-forward deployment/xxxx 18889:8888 --address 0.0.0.0 --kubeconfig /root/.kube/integration
Forwarding from 0.0.0.0:18889 -> 8888
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
Handling connection for 18889
E0808 02:38:26.745514    6512 portforward.go:311] error accepting connection on port 18889: accept tcp4 0.0.0.0:18889: accept4: too many open files
Handling connection for 18889
# Permanent block here, subsequent connections cannot be processed
```

> netstat output

```
tcp       11      0 0.0.0.0:18889           0.0.0.0:*               LISTEN      6512/./kubectl
tcp      135      0 9.135.247.91:18889      10.35.2.116:60418       CLOSE_WAIT  -
tcp      135      0 9.135.247.91:18889      10.35.2.116:60383       CLOSE_WAIT  -
tcp      135      0 9.135.247.91:18889      10.35.2.116:60369       CLOSE_WAIT  -
tcp      135      0 9.135.247.91:18889      10.35.2.116:60411       CLOSE_WAIT  -
tcp      135      0 9.135.247.91:18889      10.35.2.116:60399       CLOSE_WAIT  -
tcp      135      0 9.135.247.91:18889      10.35.2.116:60387       CLOSE_WAIT  -
tcp      134      0 9.135.247.91:18889      10.35.2.116:60424       ESTABLISHED -
```

> client output

```
(⎈ |test:devops)➜  ~ curl http://xxxx:18888 -vvv
*   Trying y.y.y.y:18888...
* Connected to xxxx (y.y.y.y) port 18888 (#0)
> GET http://xxxx:18888/ HTTP/1.1
> Host: xxxx:18888
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive

# blocked here
```

### What did you expect to happen?

After reaching the file descriptor limit. After the already processed connection ends, continue to process subsequent connections. and give corresponding prompts.

### How can we reproduce it (as minimally and precisely as possible)?

```
ulimit -n 20
kubectl port-forward  deployment/xxxx 18889:8888 --address 0.0.0.0 --kubeconfig /root/.kube/integration
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
why is this a bug? 
limits on systems have a reason to be and the error is surfaced to the user, so it can handle accordingly , I don't think that a good solution is to keep trying ... specially if we are talking about file descriptor limits, you are going to cause failures on other applications that need to open fds

**Comment by sxllwx** [comment]
> 

`kubectl port-forward` is still working, but `Accept Loop` has exited. Subsequent incoming connections cannot be processed normally (the client's connection can still be established, but the request cannot be processed)

```
(⎈ |test:devops)➜  ~ curl http://xxxx:18888 -vvv
*   Trying 127.0.0.1:12639...
* Connected to 127.0.0.1 (127.0.0.1) port 12639 (#0)
> GET http://xxxx:18888/ HTTP/1.1
> Host: xxxx:18888
> User-Agent: curl/7.79.1
> Accept: */*
> Proxy-Connection: Keep-Alive

# blocked here
```

PS: Even if the limit on the number of file descriptors is raised via `prlimit`, the service cannot continue.

**Comment by sxllwx** [comment]
Can anyone help me move this thing forward?
