### ISSUE TITLE
GracefulNodeShutdown Not Working as expected.

### ISSUE THREAD

**Issue by Aniket211** [kubernetes/kubernetes#111779]
### What happened?

Enabled `GracefulNodeShutdown` on a K8s v1.20 cluster through the feature gate and added the parameters in the kubelet configuration. 
```
GracefulNodeShutdown: true
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
```
The `systemd-inhibitor` was enabled on the node.
```
# systemd-inhibit --list
     Who: kubelet (UID 0/root, PID 27963/kubelet)
    What: shutdown
     Why: Kubelet needs time to handle node shutdown
    Mode: delay

1 inhibitors listed.
```
But the node died immediately after being powered down and did not wait for pods to get terminated gracefully.

### What did you expect to happen?

With `GracefulNodeShutdown` enabled on the node, it should have delayed the node shutdown to ensure that the pods on the node are terminated gracefully.

### How can we reproduce it (as minimally and precisely as possible)?

Followed the procedure mentioned in the blog https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

### Anything else we need to know?

Found an upstream bug with Fedora which mentions the issue where systemd does not honor the inhibitors. Might be related https://bugzilla.redhat.com/show_bug.cgi?id=2043695

### Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux test-node1 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by wzshiming** [comment]
Hi @Aniket211
Sorry for the late response, this is a known BUG in upstream Systemd, recommend to upgrade Systemd or use a new Linux distribution

Repeated with #107043
/kind support

**Comment by Aniket211** [comment]
Hi @wzshiming  
Thanks for the reply on the thread and apologies for replying late on this.
Thanks for confirming the upstream systems bug. Could you please suggest which systems version has the fix for this or which CentOS version we should upgrade to get this resolved and have Graceful Node shutdown working? 
I referred to the thread for issue #107043 and I guess this has been fixed in CentOS 8. Just wanted to confirm the same.

**Comment by wzshiming** [comment]
> Hi @wzshiming Thanks for the reply on the thread and apologies for replying late on this. Thanks for confirming the upstream systems bug. Could you please suggest which systems version has the fix for this or which CentOS version we should upgrade to get this resolved and have Graceful Node shutdown working? I referred to the thread for issue #107043 and I guess this has been fixed in CentOS 8. Just wanted to confirm the same.

Yes, it works in CentOS 8.
If using CentOS 7, need to upgrade the version of Systemd

**Comment by SergeyKanzhelev** [comment]
/close

looks like OS bug, not related to kubernetes
