### ISSUE TITLE
Slow response of nginx container

### ISSUE THREAD

**Issue by 2820402** [kubernetes/kubernetes#111733]
### What happened?

I recently setup a kubernetes cluster on hetzner cloud with help of k0s but when I create a pod for example nginx then create a service for that to access through Nordport 

Now i successfully curl the web server but when I hit again and again like 3 4 time it's giving very late response and sometimes don't give the response 

I check the logs nothing there

### What did you expect to happen?

Need fast response from the nginx pod

### How can we reproduce it (as minimally and precisely as possible)?

I use k0s to setup

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> I use k0s to setup

hi, it's better to talk to k0s for support because it's not the official k8s distribution.

if they confirm a k8s bug please reopen.

/close
