### ISSUE TITLE
kubelet returns diffirent fs metrics for docker and containerd

### ISSUE THREAD

**Issue by xiaoping8385** [kubernetes/kubernetes#111777]
### What happened?

I try to obtain the metrics from kubectl get --raw "/api/v1/nodes/node_name/proxy/metrics/cadvisor" in k8s 1.24.1 env +containerd
and found some of the container fs related metrics are missing, take container_fs_io_time_seconds_total for eg, in docker env, I could get below result
```
container_fs_io_time_seconds_total{container="coredns",device="/dev/sdc1",id="/kubepods/burstable/pod8282a6e1-73b4-4c1e-8da6-c08cf9063bb6/fa4a8b920d9c28d789c638925c9748966229d7f37246fe533f8cb7e886225c5d",image="sha256:4e483030889602da754eb0b805fab3c35e7bf9865c910f1c433290a902039af8",name="k8s_coredns_coredns-6ccdb8dc5b-qxct4_kube-system_8282a6e1-73b4-4c1e-8da6-c08cf9063bb6_0",namespace="kube-system",pod="coredns-6ccdb8dc5b-qxct4"} 3.6048e-05 1659877126996
container_fs_io_time_seconds_total{container="event-controller",device="/dev/sdc1",id="/kubepods/besteffort/pod26956249-d626-4ee7-b04f-997e394ac75a/8d7376e5d7ea9c9b72d4fa945899ffc4f051be6c312feb051b337a3f3a27d690",image="sha256:3be29561018908f340b9402aee91434edae8d21ca64a68c627dd40c1d14ac3ea",name="k8s_event-controller_event-controller-78f46c77c-865zj_pks-system_26956249-d626-4ee7-b04f-997e394ac75a_0",namespace="pks-system",pod="event-controller-78f46c77c-865zj"} 3.6048e-05 1659877137653
container_fs_io_time_seconds_total{container="fluent-bit",device="/dev/sdb",id="/kubepods/burstable/poda400c3da-3d9a-41e1-b2d6-040dc364cc58/e3b73cca08e518a562d1f6b3f8983fe868ba83fd7a0993f8242cbb0317a28841",image="sha256:12399652508e5e30566d9854bdded190d6f7122923d5d00a2739bab87fb3f2d8",name="k8s_fluent-bit_fluent-bit-rqjbj_pks-system_a400c3da-3d9a-41e1-b2d6-040dc364cc58_0",namespace="pks-system",pod="fluent-bit-rqjbj"} 0.059549304 1659877131215
container_fs_io_time_seconds_total{container="fluent-bit",device="/dev/sdc1",id="/kubepods/burstable/poda400c3da-3d9a-41e1-b2d6-040dc364cc58/e3b73cca08e518a562d1f6b3f8983fe868ba83fd7a0993f8242cbb0317a28841",image="sha256:12399652508e5e30566d9854bdded190d6f7122923d5d00a2739bab87fb3f2d8",name="k8s_fluent-bit_fluent-bit-rqjbj_pks-system_a400c3da-3d9a-41e1-b2d6-040dc364cc58_0",namespace="pks-system",pod="fluent-bit-rqjbj"} 3.6048e-05 1659877131215
container_fs_io_time_seconds_total{container="fluent-bit-telemetry",device="/dev/sdc1",id="/kubepods/besteffort/pod2605f605-b70a-4aaf-a9bb-46f04f1c50e4/9b16a965c8efcdfbe7e11a3ca9540448fe27f1daee18f0c656d3eeb0ac493eb4",image="sha256:bfd39bd3f10e9656afca585049d0264b6952e31103043949f97baf6efad0fccc",name="k8s_fluent-bit-telemetry_telemetry-agent-8f56d9865-kn66k_pks-system_2605f605-b70a-4aaf-a9bb-46f04f1c50e4_0",namespace="pks-system",pod="telemetry-agent-8f56d9865-kn66k"} 3.6048e-05 1659877129044
container_fs_io_time_seconds_total{container="ghostunnel",device="/dev/sdc1",id="/kubepods/besteffort/pod26956249-d626-4ee7-b04f-997e394ac75a/b424c9abcc53e81b69fa31aa7c6a14272c85513ee564555c648568d2d22bf230",image="sha256:2231dd4d942fff42fa3c564ddea0a50e543596297e508b34b1a8d1cca6f0720e",name="k8s_ghostunnel_event-controller-78f46c77c-865zj_pks-system_26956249-d626-4ee7-b04f-997e394ac75a_0",namespace="pks-system",pod="event-controller-78f46c77c-865zj"} 3.6048e-05 1659877128921
container_fs_io_time_seconds_total{container="ghostunnel",device="/dev/sdc1",id="/kubepods/burstable/poda400c3da-3d9a-41e1-b2d6-040dc364cc58/0c016028469ed20817a7f4ce7defdc54caae3ded55afce24bbb36e6a60362cf1",image="sha256:2231dd4d942fff42fa3c564ddea0a50e543596297e508b34b1a8d1cca6f0720e",name="k8s_ghostunnel_fluent-bit-rqjbj_pks-system_a400c3da-3d9a-41e1-b2d6-040dc364cc58_0",namespace="pks-system",pod="fluent-bit-rqjbj"} 3.6048e-05 1659877138812
container_fs_io_time_seconds_total{container="metric-controller",device="/dev/sdc1",id="/kubepods/besteffort/pode840e3b0-0302-4fc4-a1fe-55842b243865/36e19c4edbc659a6df39ac374f9c2605880dd8612049fe1987b3bcec0c5b223d",image="sha256:bbdb0caffc9d726caca7585ac53e9e5e45f8e2fca3c920b35b9619a9de7aaec3",name="k8s_metric-controller_metric-controller-7b5dbf4678-slc8d_pks-system_e840e3b0-0302-4fc4-a1fe-55842b243865_0",namespace="pks-system",pod="metric-controller-7b5dbf4678-slc8d"} 3.6048e-05 1659877128013
container_fs_io_time_seconds_total{container="metrics-server",device="/dev/sdc1",id="/kubepods/besteffort/podaa6aba1d-e750-4a7a-955f-af51f951e066/f044b0d81ea0801d129e1ce2853b3808d36170fa2e8cae4a9e5d83696d42d103",image="sha256:f3a697d893c78af6d46d15e887cf94bdbfa9af6685fc8dbf44421c80b2063e8c",name="k8s_metrics-server_metrics-server-757c77bdc5-8qdqb_kube-system_aa6aba1d-e750-4a7a-955f-af51f951e066_0",namespace="kube-system",pod="metrics-server-757c77bdc5-8qdqb"} 3.6048e-05 1659877133287
container_fs_io_time_seconds_total{container="observability-manager",device="/dev/sdc",id="/kubepods/besteffort/podc79c9d36-01ff-4716-9c5c-272449914896/0d6bdd7d10acbc1786b826b58c3e7ab0c50a4715f9226f9a628c4abe012514cb",image="sha256:4b2214277e6872ebbf48b337c4ebdd242fddf79746c28eebdf193ccf667df456",name="k8s_observability-manager_observability-manager-6b454c5599-njk8p_pks-system_c79c9d36-01ff-4716-9c5c-272449914896_0",namespace="pks-system",pod="observability-manager-6b454c5599-njk8p"} 0.355826324 1659877130372
container_fs_io_time_seconds_total{container="observability-manager",device="/dev/sdc1",id="/kubepods/besteffort/podc79c9d36-01ff-4716-9c5c-272449914896/0d6bdd7d10acbc1786b826b58c3e7ab0c50a4715f9226f9a628c4abe012514cb",image="sha256:4b2214277e6872ebbf48b337c4ebdd242fddf79746c28eebdf193ccf667df456",name="k8s_observability-manager_observability-manager-6b454c5599-njk8p_pks-system_c79c9d36-01ff-4716-9c5c-272449914896_0",namespace="pks-system",pod="observability-manager-6b454c5599-njk8p"} 3.6048e-05 1659877130372
container_fs_io_time_seconds_total{container="prometheus-node-exporter",device="/dev/sdc1",id="/kubepods/burstable/pod7bb89208-18fe-48af-84cb-503488fe3b81/3a829d5e76e39c496f257a5143385d362c22ac4fbc79ce2602fcdc89da76c0dc",image="sha256:ed68312d34dc45e1db5cbba69cff86b1cbc4ed47c736c31879b2c87ac7b9b68f",name="k8s_prometheus-node-exporter_node-exporter-xchsf_pks-system_7bb89208-18fe-48af-84cb-503488fe3b81_0",namespace="pks-system",pod="node-exporter-xchsf"} 3.6048e-05 1659877128311
container_fs_io_time_seconds_total{container="sink-controller",device="/dev/sdc1",id="/kubepods/besteffort/podd3695d53-9abe-4c27-af78-dae84ebef1c9/5d96934876e9b72a72bcc36ea5f0f192028fd2129841118e02fab29e0f2970e1",image="sha256:74ca6a94f15601101aa8c5508b22e70f3c4189c31055721037a386effc97fc36",name="k8s_sink-controller_sink-controller-84554d497b-x9v9p_pks-system_d3695d53-9abe-4c27-af78-dae84ebef1c9_0",namespace="pks-system",pod="sink-controller-84554d497b-x9v9p"} 3.6048e-05 1659877134765
container_fs_io_time_seconds_total{container="telegraf",device="/dev/sdc1",id="/kubepods/besteffort/pod883ea983-5309-475f-a814-eeca37363bcf/18d9fb2f1d6f8665e47750f60f7e553474233e5f3a581c9cd264d7c9e9e71afd",image="sha256:d5ec1ddb9768327ecbbb8dc85fc9b9eacb617a760b1b94dfcd80b6ede2f25712",name="k8s_telegraf_telegraf-lk9bc_pks-system_883ea983-5309-475f-a814-eeca37363bcf_0",namespace="pks-system",pod="telegraf-lk9bc"} 3.6048e-05 1659877121396
container_fs_io_time_seconds_total{container="validator",device="/dev/sdc1",id="/kubepods/besteffort/pode4e83e72-2a3d-4a04-b04f-985b72db3c46/2073eaafb7e6df6f5d13f777d4e3b06471adaab0e9c59a7d632bfc96dbf5f5d8",image="sha256:acc981bd0ec6908536d42f5f92a10608c2be1c761f00739a200b514016e4627e",name="k8s_validator_validator-6b65bf96fc-jqvhm_pks-system_e4e83e72-2a3d-4a04-b04f-985b72db3c46_0",namespace="pks-system",pod="validator-6b65bf96fc-jqvhm"} 3.6048e-05 1659877134682
container_fs_io_time_seconds_total{container="vrops-cadvisor",device="/dev/sdc1",id="/kubepods/besteffort/pod24493d63-d09d-4d26-95b9-382a97e22e5c/4aa95d85869c3e5af42ea936e6fa55dcb39fc96c9dade15649ef7668ada0ef14",image="gcr.io/cadvisor/cadvisor@sha256:3f7f15189a05d152a00105ea39b8f8ef7128639cba8711fc992267642a98285e",name="k8s_vrops-cadvisor_vrops-cadvisor-b7j8c_pks-system_24493d63-d09d-4d26-95b9-382a97e22e5c_0",namespace="pks-system",pod="vrops-cadvisor-b7j8c"} 3.6048e-05 1659877130323
container_fs_io_time_seconds_total{container="wavefront-collector",device="/dev/sdc1",id="/kubepods/besteffort/pod17c20858-97f3-4ffe-a7fc-114c736bda44/507551bf18cb81d9ae68d82291bd7d24be7031b8c7fa1579581d3c72b448d189",image="sha256:f0e154905b4c9049d6f5b5c997f50f12db0ebf81621ba65535d3500a867db19e",name="k8s_wavefront-collector_wavefront-collector-58c7b9cb75-rw6wp_pks-system_17c20858-97f3-4ffe-a7fc-114c736bda44_0",namespace="pks-system",pod="wavefront-collector-58c7b9cb75-rw6wp"} 3.6048e-05 1659877138883
container_fs_io_time_seconds_total{container="wavefront-proxy",device="/dev/sdc",id="/kubepods/burstable/pod339e402c-a68f-4092-adde-8bd03b22e26a/b3882fab7e61544252dfa33b06378f6b7e27a2453a616ea5b4c5734643faf6f4",image="sha256:e1fdc3f159e2878e0982b3afb72f36ee494c841a4cca359594d0251558e0617c",name="k8s_wavefront-proxy_wavefront-proxy-7bcd95c966-9hxbz_pks-system_339e402c-a68f-4092-adde-8bd03b22e26a_0",namespace="pks-system",pod="wavefront-proxy-7bcd95c966-9hxbz"} 0.123682139 1659877129796
container_fs_io_time_seconds_total{container="wavefront-proxy",device="/dev/sdc1",id="/kubepods/burstable/pod339e402c-a68f-4092-adde-8bd03b22e26a/b3882fab7e61544252dfa33b06378f6b7e27a2453a616ea5b4c5734643faf6f4",image="sha256:e1fdc3f159e2878e0982b3afb72f36ee494c841a4cca359594d0251558e0617c",name="k8s_wavefront-proxy_wavefront-proxy-7bcd95c966-9hxbz_pks-system_339e402c-a68f-4092-adde-8bd03b22e26a_0",namespace="pks-system",pod="wavefront-proxy-7bcd95c966-9hxbz"} 3.6048e-05 1659877129796
```
but in containrd env, while others are all the same, we get
```
container_fs_io_time_seconds_total{container="fluent-bit",device="/dev/sdb",id="/kubepods/burstable/pod3f8f50f0-0ac8-4a83-8e8f-7ae047ab14e1/8457f5bda321facc5ef4a46a07503ada02c77f3939a03403d1084664913f8b60",image="cnabu-docker-local.artifactory.eng.vmware.com/oratos/fluent-bit-out-syslog:8207ce8412a547b0f505325e5f6095a0414b0e11",name="8457f5bda321facc5ef4a46a07503ada02c77f3939a03403d1084664913f8b60",namespace="pks-system",pod="fluent-bit-ssjgn"} 0.059058542 1659876898980
container_fs_io_time_seconds_total{container="observability-manager",device="/dev/sdc",id="/kubepods/besteffort/pod5a90222f-859c-4975-be26-1340fedd4371/2baa06e963f67236b43ec01ed5e8d3bdc911222f406b2d22f39e427ecec87444",image="cnabu-docker-local.artifactory.eng.vmware.com/oratos/observability-manager:91882e178d2f89da53a2344e3b2eee692455c956",name="2baa06e963f67236b43ec01ed5e8d3bdc911222f406b2d22f39e427ecec87444",namespace="pks-system",pod="observability-manager-6b454c5599-bmbg2"} 0.236291511 1659876897965
container_fs_io_time_seconds_total{container="wavefront-proxy",device="/dev/sdc",id="/kubepods/burstable/pode4349c39-e438-48be-9a8c-4a1137462bb2/c0f6cf5330beedc2f60af7276fd922bb44e3af533536f379db109a33e973098b",image="docker.io/wavefronthq/proxy:10.13",name="c0f6cf5330beedc2f60af7276fd922bb44e3af533536f379db109a33e973098b",namespace="pks-system",pod="wavefront-proxy-586977d8bc-7wl2s"} 0.141070731 1659876901626

```

### What did you expect to happen?

we expected to get the same result in containerd and docker env.

### How can we reproduce it (as minimally and precisely as possible)?

try in k8s 1.24.1

### Anything else we need to know?

I tested the latest cadvisor daemonset(gcr.io/cadvisor/cadvisor:v0.45.0-containerd-cri), and get the same result for both env, 
eg, from docker, we get 
`kubo@jumper:~$ curl 30.1.0.3:31194/metrics 2>/dev/null | grep container_fs_io_time_seconds_tot
# HELP container_fs_io_time_seconds_total Cumulative count of seconds spent doing I/Os
# TYPE container_fs_io_time_seconds_total counter
container_fs_io_time_seconds_total{device="",id="/"} 0.031014187 1659880194797
container_fs_io_time_seconds_total{device="/dev",id="/"} 0 1659880194797
container_fs_io_time_seconds_total{device="/dev/sda",id="/"} 172.497894875 1659880194797
container_fs_io_time_seconds_total{device="/dev/sda1",id="/"} 0.000122616 1659880194797
container_fs_io_time_seconds_total{device="/dev/sdb",id="/"} 1370.449907177 1659880194797
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods"} 0.06265413 1659880235494
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable"} 0.06265413 1659880218293
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable/poda400c3da-3d9a-41e1-b2d6-040dc364cc58"} 0.06265413 1659880198617
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable/poda400c3da-3d9a-41e1-b2d6-040dc364cc58/e3b73cca08e518a562d1f6b3f8983fe868ba83fd7a0993f8242cbb0317a28841"} 0.06265413 1659880192753
container_fs_io_time_seconds_total{device="/dev/sdb1",id="/"} 5.5168e-05 1659880194797
container_fs_io_time_seconds_total{device="/dev/sdc",id="/"} 491.799356506 1659880194797
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods"} 0.765319838 1659880235494
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort"} 0.635141356 1659880229322
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/podc79c9d36-01ff-4716-9c5c-272449914896"} 0.355826324 1659880181282
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/podc79c9d36-01ff-4716-9c5c-272449914896/0d6bdd7d10acbc1786b826b58c3e7ab0c50a4715f9226f9a628c4abe012514cb"} 0.355826324 1659880229443
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/pode4e83e72-2a3d-4a04-b04f-985b72db3c46"} 0.090002578 1659880228653
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable"} 0.130178482 1659880218293
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable/pod339e402c-a68f-4092-adde-8bd03b22e26a"} 0.130178482 1659880205288
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable/pod339e402c-a68f-4092-adde-8bd03b22e26a/b3882fab7e61544252dfa33b06378f6b7e27a2453a616ea5b4c5734643faf6f4"} 0.130178482 1659880171980`
in containerd, we got,
`kubo@jumper:~$ curl 30.1.1.3:31194/metrics 2>/dev/null | grep container_fs_io_time_seconds_tot 
# HELP container_fs_io_time_seconds_total Cumulative count of seconds spent doing I/Os
# TYPE container_fs_io_time_seconds_total counter
container_fs_io_time_seconds_total{device="",id="/"} 0.025535224 1659879923451
container_fs_io_time_seconds_total{device="/dev",id="/"} 0 1659879923451
container_fs_io_time_seconds_total{device="/dev/sda",id="/"} 249.905994923 1659879923451
container_fs_io_time_seconds_total{device="/dev/sda1",id="/"} 0.0001057 1659879923451
container_fs_io_time_seconds_total{device="/dev/sdb",id="/"} 1099.366634008 1659879923451
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods"} 0.072587302 1659879914281
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable"} 0.072587302 1659879937423
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable/pod3f8f50f0-0ac8-4a83-8e8f-7ae047ab14e1"} 0.072587302 1659879901479
container_fs_io_time_seconds_total{device="/dev/sdb",id="/kubepods/burstable/pod3f8f50f0-0ac8-4a83-8e8f-7ae047ab14e1/8457f5bda321facc5ef4a46a07503ada02c77f3939a03403d1084664913f8b60"} 0.072587302 1659879892588
container_fs_io_time_seconds_total{device="/dev/sdb1",id="/"} 4.832e-05 1659879923451
container_fs_io_time_seconds_total{device="/dev/sdc",id="/"} 514.793783854 1659879923451
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods"} 0.630957031 1659879914281
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort"} 0.478439455 1659879944696
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/pod5a90222f-859c-4975-be26-1340fedd4371"} 0.236291511 1659879931365
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/pod5a90222f-859c-4975-be26-1340fedd4371/2baa06e963f67236b43ec01ed5e8d3bdc911222f406b2d22f39e427ecec87444"} 0.236291511 1659879939888
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/besteffort/pod8c419e21-9403-433e-ac20-b29ec3df2622"} 0.081051491 1659879958306
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable"} 0.152517576 1659879937423
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable/pode4349c39-e438-48be-9a8c-4a1137462bb2"} 0.152517576 1659879942793
container_fs_io_time_seconds_total{device="/dev/sdc",id="/kubepods/burstable/pode4349c39-e438-48be-9a8c-4a1137462bb2/c0f6cf5330beedc2f60af7276fd922bb44e3af533536f379db109a33e973098b"} 0.152517576 1659879897776`
So I doubt this might be something related to kubelet method to handle the metrics, looks like in containerd env, it ignored the tiny value like  3.6048e-05, so anyone could help to take a look at this, thanks so much!

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:16:51Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1+vmware.1", GitCommit:"6b9884d8633a7b1e9e6e66a85967a826ad694270", GitTreeState:"clean", BuildDate:"2022-06-10T21:04:15Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$ uname -a
# Linux jumper 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xiaoping8385** [comment]
@bobbypage could you comment on this? thanks!

**Comment by bobbypage** [comment]
(This is likely due to https://github.com/google/cadvisor/issues/2785#issuecomment-1205538108)

**Comment by SergeyKanzhelev** [comment]
Public docs update is tracked here: https://github.com/kubernetes/website/issues/30681 I will close this in favor of that documentation task as unfortunately this is a known limitation and the workaround is to use cadvisor.

/close
