### ISSUE TITLE
Removed resource is listed as a supported resource

### ISSUE THREAD

**Issue by maartenjanvangool** [kubernetes/kubernetes#111813]
### What happened?

We're in the process of upgrading from Kubernetes 1.21 to 1.22 on a GKE standard cluster. We're on standard release channel, so normally these upgrades should go automatically. However, GKE was warning us we were still using deprecated api's, which are about to be removed. So what we did was upgrade the components on our cluster doing that, hoping it would resolve the issue. Unfortunately, Velero kept on calling the deprecated `/apis/extensions/v1beta1/ingresses`. So I made an issue at Velero, see here: https://github.com/vmware-tanzu/velero/issues/5187. 

On doing some reserach, we figured that the kubernets api, which Velero uses, returns the deprecated api as an available resource. And even when we forced the upgrade to 1.22 on our staging environment, it would _still_ return the api as an available api, even though it was supposed to be removed. I've slacked about it [here](https://kubernetes.slack.com/archives/C09NXKJKA/p1660053130386309), but since I got no real response, I made this issue. 

### What did you expect to happen?

I don't expect removed api's to be listed as an available resource. 

### How can we reproduce it (as minimally and precisely as possible)?

On kubernetes 1.22: 
```
kubectl api-resources --help
Print the supported API resources on the server.

<some more>
```
So this should return supported resources. 

```
kubectl api-resources | grep extensions/v1beta1
ingresses                         ing          extensions/v1beta1                     true         Ingress
```
It returns me extensions/v1beta1/ingresses. So fully supported!
```
kubectl get ingresses.extensions
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

<ingresses are shown from the new api>
```
No it isn't!!! It has been removed! 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

server/client 1.21 and 1.22

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
https://cloud.google.com/kubernetes-engine/docs/deprecations/apis-1-22#ingress-v122

> The Beta API versions (extensions/v1beta1 and networking.k8s.io/v1beta1) of Ingress are no longer served for GKE clusters created on versions 1.22 and later.
>
> GKE clusters that upgrade from GKE version 1.21 and earlier to versions 1.22.7-gke.300 and later can still use the Beta API versions until version 1.23.

GKE extended this for their customers. That's why it shows up.

---

Versus with upstream Kubernetes 1.22.9 using [KIND](https://sigs.k8s.io/kind):

```console
# create a 1.22 cluster from open source
$ kind create cluster --image=kindest/node:v1.22.9@sha256:8135260b959dfe320206eb36b3aeda9cffcb262f4b44cda6b33f7bb73f453105
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.22.9) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Thanks for using kind! 😊

$ kubectl api-resources | grep extensions/v1beta1
# no output
```

And with 1.21 ..
```
# delete cluster, create a 1.21 cluster
$ kind delete cluster
Deleting cluster "kind" ...

$ kind create cluster --image=kindest/node:v1.21.12@sha256:f316b33dd88f8196379f38feb80545ef3ed44d9197dca1bfd48bcb1583210207
Creating cluster "kind" ...
 ✓ Ensuring node image (kindest/node:v1.21.12) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kind"
You can now use your cluster with:

kubectl cluster-info --context kind-kind

Have a question, bug, or feature request? Let us know! https://kind.sigs.k8s.io/#community 🙂

$ kubectl api-resources | grep extensions/v1beta1
ingresses                         ing          extensions/v1beta1                     true         Ingress
```

**Comment by liggitt** [comment]
the explanation in https://github.com/kubernetes/kubernetes/issues/111813#issuecomment-1216008212 is correct, that specific resource was served in GKE for one additional release *only* for clusters upgraded from 1.21 to 1.22, not for new 1.22 clusters

**Comment by randywatson1979** [comment]
Thanks for clarifying! https://github.com/kubernetes/kubernetes/issues/111813#issuecomment-1216008212

Saves a lot of confusion.
