### ISSUE TITLE
Failing ci-kubernetes-e2e-gce-cos-k8sstable3-alphafeatures on sig-release-1.22-blocking

### ISSUE THREAD

**Issue by palnabarun** [kubernetes/kubernetes#111892]
### Which jobs are failing?

ci-kubernetes-e2e-gce-cos-k8sstable3-alphafeatures

### Which tests are failing?

The job is unable to bootstrap a cluster.

### Since when has it been failing?

2022-08-10 05:03:36 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-1.22-blocking#gce-cos-k8sstable3-alphafeatures

### Relevant SIG(s)

/sig testing

**Comment by palnabarun** [comment]
PTAL https://github.com/orgs/kubernetes/teams/cloud-provider-gcp-maintainers https://github.com/orgs/kubernetes/teams/sig-cloud-provider

**Comment by palnabarun** [comment]
related: https://github.com/kubernetes/kubernetes/issues/111114

**Comment by spiffxp** [comment]
/assign
Should be addressed by https://github.com/kubernetes/test-infra/pull/27218
