### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Add Pod Resize Node E2E test using framework in test/e2e_node 

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#111877]
### What would you like to be added?

One of the review comments for PR https://github.com/kubernetes/kubernetes/pull/102884 requested to move current pod resize E2E test from test/e2e/node to test/e2e_node. 
Please see comment: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r891689410

I have a lot of trust in the current E2E test after it recently failed upon rebase and CI had switched to cgroup v2 (support for it was planned for beta) - this means the test works quite well and its execution gives me high confidence. 

So, I believe we should keep the current E2E test as it is for now, add a new E2E test under e2e_node, and perhaps eventually remove the current E2E test.

### Why is this needed?

The tests under e2e/node are being deprecated. So we need to add tests under e2e_node which uses a different framework that has its advantages.

**Comment by esotsal** [comment]
> Does this test make sense in the cluster suite too, or only in the node suite? If it's applicable to both, you should move it to https://github.com/kubernetes/kubernetes/tree/master/test/e2e/common/node instead.

Thanks good point , will check it out and update commit.
