### ISSUE TITLE
Proposal: rewrite sets package as go generic

### ISSUE THREAD

**Issue by weilaaa** [kubernetes/kubernetes#111853]
### What would you like to be added?

Consider rewrite sets package [staging/src/k8s.io/apimachinery/pkg/util/sets](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apimachinery/pkg/util/sets) as go generic instead of using code generator.

### Why is this needed?

Different types sets can be perfectly implemented using go generic without the need for code generators. Also, this is not a breaking change for user-side usage.

**Comment by BenTheElder** [comment]
Please see our generics policy for why we probably shouldn’t do this for at least a few more releases https://github.com/kubernetes/community/blob/master/sig-architecture/generics.md

**Comment by BenTheElder** [comment]
> Also, this is not a breaking change for user-side usage

The types would not be the same and they’d have different performance and go version requirements

**Comment by fedebongio** [comment]
/backlog
cc @alexzielenski @deads2k @lavalamp 
/triage accepted

**Comment by weilaaa** [comment]
I see, I hope to be able to do more with generics in the future.
