### ISSUE TITLE
sig-node-cos is all failing

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#111876]
### Which jobs are failing?

Everything under https://testgrid.k8s.io/sig-node-cos is failing

### Which tests are failing?

All tabs

### Since when has it been failing?

Unknown 

### Relevant SIG(s)

/sig node

**Comment by bobbypage** [comment]
We already run COS tests on the COS containerd tab, so we should investigate if it's even worthwhile to have separate COS tests or are they are redundant and we can clean them up.

**Comment by aojea** [comment]
> {  error during gcloud auth activate-service-account --key-file=/etc/service-account/service-account.json: exit status 1}

**Comment by bobbypage** [comment]
related slack thread: https://kubernetes.slack.com/archives/C0BP8PW9G/p1663050046204719

**Comment by SubhasmitaSw** [comment]
Hi @mmiranda96 checking in for any progress in this segment here given v1.26 release milestone. 
~ Bug Triage Release Shadow

**Comment by mmiranda96** [comment]
Hi @SubhasmitaSw, PR is under review but I expect it to be merged by end of this week.

**Comment by SubhasmitaSw** [comment]
Hello @mmiranda96 any updates so far?

**Comment by furkatgofurov7** [comment]
Hey @mmiranda96!

the K8s 1.27 Bug Triage Shadow here.  Just wanted to check if this is still on track for 1.27 release?

**Comment by adisky** [comment]
These jobs has been disabled for now, we will have to revisit if they are needed or not
https://github.com/kubernetes/test-infra/pull/28868
