### ISSUE TITLE
Network Policy: "host" could not be resolved when adding network policy?

### ISSUE THREAD

**Issue by MohamedBenighil** [kubernetes/kubernetes#111869]
### What happened?

ERROR 2005 (HY000): Unknown server host 'mysql' (-3)
wordpress 11:36:37.26 DEBUG ==> Executing SQL command:
SELECT 1

### What did you expect to happen?

'hostname' resolved

### How can we reproduce it (as minimally and precisely as possible)?

deploy a Wordpress release from `https://marketplace.azurecr.io/helm/v1/repo` Helm repo and install Wordpress with the following `values.yml`:
```
externalDatabase:
  #host: 10.0.4.68
  host: mysql # where mysql is External service Object that points to mariadb endpoint
  port: 3306
  database: bitnami_wordpress

#networkPolicy:
networkPolicy:
  enabled: true
  ingressRules:
    accessOnlyFrom:
      enabled: true
    customRules: 
    - {} # i.e : Allow all incoming traffic from namesapces and pods ( it works fine )
  # But the following does not work. AGIC becomes unhealthy
  # - from:
  #     - namespaceSelector:
  #         matchLabels:
  #           kubernetes.io/metadata.name: kube-system
  #       podSelector:
  #         matchLabels:
  #           app: ingress-appgw
################
  egressRules:
    customRules:
      - to:
          - ipBlock:
              cidr: 10.0.4.64/28 # range IP of MariaDB IP@
        ports:
          - protocol: TCP
            port: 3306
```

### Anything else we need to know?

But when i hard code the IP@ of mariaDB enpoint (instead of hostname `mysql`) It works fine

### Kubernetes version

<details>

```console
$ kubectl version
#WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|js
on to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeS
tate:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"42a9a90338d705a1650fb68b7891f84b62adb0b0", GitTreeS
tate:"clean", BuildDate:"2022-06-15T04:25:21Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Helm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Azure
</details>

**Comment by thockin** [comment]
It is hard to debug through a helm chart - can you drop to the native k8s APIs to debug?

Does that selector actually select anything ?  Are you SURE?

**Comment by thockin** [comment]
Oh, hold on.  Is your DB external to the cluster?  Network policy does not resolve services, only pods and IPs .

**Comment by thockin** [comment]
any updates here?
