### ISSUE TITLE
How to get Kubernetes API Server to pass requestor token to authorization webhook 

### ISSUE THREAD

**Issue by mathuvenkat** [kubernetes/kubernetes#111895]
### What happened?

API server failed on authorizer webhook parsing return value 

api server logs for version 
```
Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
I0817 16:56:55.206742       1 server.go:629] external host was not specified, using 10.0.0.60
I0817 16:56:55.207216       1 server.go:181] Version: v1.21.1
```

failure in api server logs
```
E0817 17:16:33.129788       1 webhook.go:202] Failed to make webhook authorizer request: couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
E0817 17:16:33.129947       1 errors.go:77] couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```

Webhook tailed logs
```
2022/08/17 17:24:06 in function servehttp
2022/08/17 17:24:06 request input kind: SubjectAccessReview
2022/08/17 17:24:06 request input apiversion: authorization.k8s.io/v1
2022/08/17 17:24:06 system:anonymous
2022/08/17 17:24:06 RETURNING true response for testing modified return v1*****
2022/08/17 17:24:06 main.AuthorizationResponse{APIVersion:"authorization.k8s.io/v1", Kind:"SubjectAccessReview", Status:(*main.AuthorizationStatus)(0xc00009ec30)}
```

using a curl request the response returned is of valid json format and is below
`{"apiVersion":"authorization.k8s.io/v1","kind":"SubjectAccessReview","status":{"allowed":true}}`

The api server is configured with this:
```
    - --authorization-mode=Node,RBAC,Webhook
    - --authorization-webhook-config-file=/etc/kubernetes/authorize-webhook-conf-test.yaml  #webhook-test
    - --authorization-webhook-version=v1
```

authorize-webhook-conf-test.yaml is as below. That does not seem to be the issue because it can clearly make the request to the webhook and we can see the logs returning which api server fails to parse. 
```
apiVersion: v1
kind: Config
clusters:
  - name: authorize-service
    cluster:
      #certificate-authority: /var/lib/minikube/certs/auth/ca.crt
      server: http://10.223.252.101:3000/authorize
      insecure-skip-tls-verify: true
users:
  - name: authorize-api-server
    user:
      # This will come in the request header(Authorization) of above URL.
      # Can be used to validate if the request is coming from configured cluster
      token: test-token

current-context: webhook
contexts:
- context:
    cluster: authorize-service
    user: authorize-api-server
  name: webhook
```

### What did you expect to happen?

Given API server has been configured correctly and request is being sent to the authorizer which responds with a valid json which can be parsed correctly, this was expected to work, and it did work in the past. Is there any version related configurations or settings that must be added - why is the api server not able to unmarshal the response of this type 
{"apiVersion":"authorization.k8s.io/v1","kind":"SubjectAccessReview","status":{"allowed":true}} 

### How can we reproduce it (as minimally and precisely as possible)?

Create a http endpoint that returns json {"apiVersion":"authorization.k8s.io/v1","kind":"SubjectAccessReview","status":{"allowed":true}} and point api-server authorizer to it. 

### Anything else we need to know?

none

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Cluster k8s version
k version
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>


### Cloud provider

<details>
Cluster environment details  , Api-server Version: v1.21.1 
</details>
 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
> using a curl request the response returned is of valid json format and is below
> `{"apiVersion":"authorization.k8s.io/v1","kind":"SubjectAccessReview","status":{"allowed":true}}`

the unmarshal error indicates a non-struct value is being encountered in the response... do you have the full curl output (maybe even in verbose mode with `-v`) to see everything coming back from the server?

**Comment by liggitt** [comment]
also, are you curling the same way the webhook is being invoked (passing a `test-token` bearer token header, making a POST request containing a SubjectAccessReview, etc)?

**Comment by mathuvenkat** [comment]
i modified the code a bit to marshal from the datastructure directly 

code snippet of serve method

```
func  ServeHTTP(w http.ResponseWriter, r *http.Request) {
	log.Printf("in function servehttp")
	sar := &authorizationv1.SubjectAccessReview{}
	content, err := ioutil.ReadAll(r.Body)
	defer r.Body.Close()
	if err != nil {
	log.Printf( "***error in request read")
    }
	json.Unmarshal(content, sar) 
	log.Printf("%v",sar)
	st := authorizationv1.SubjectAccessReviewStatus { Allowed:  true}
	expTypeMeta := metav1.TypeMeta{
	APIVersion: "authorization.k8s.io/v1",
	Kind:       "SubjectAccessReview",
	}
	sarFinal := authorizationv1.SubjectAccessReview {
	TypeMeta: expTypeMeta,
	Status: st,
	}
	responseBytes, err := json.Marshal(sarFinal)
	if err != nil {
		log.Printf( "***error in response marshal")
	}
	log.Printf("Request headers : %v", r.Header)

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	//w.WriteHeader(http.StatusOK)
	w.Write(responseBytes)
}

Curl request and response
```
```
# curl -k -X POST http://10.223.252.101:3000/authorize -v -d '{ "apiVersion": "authorization.k8s.io/v1", "kind": "SubjectAccessReview", "spec": { "resourceAttributes": { "namespace": "kittensandponies", "verb": "get", "group": "unicorn.example.org", "resource": "pods" }, "user": "jane", "group": [ "group1", "group2" ] } }'
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 10.223.252.101...
* TCP_NODELAY set
* Connected to 10.223.252.101 (10.223.252.101) port 3000 (#0)
> POST /authorize HTTP/1.1
> Host: 10.223.252.101:3000
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Length: 261
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 261 out of 261 bytes
< HTTP/1.1 200 OK
< Date: Wed, 17 Aug 2022 22:50:06 GMT
< Content-Length: 161
< Content-Type: text/html; charset=utf-8
<
* Connection #0 to host 10.223.252.101 left intact
{"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1","metadata":{"creationTimestamp":null},"spec":{},"status":{"allowed":true}}
```

**Comment by harshanarayana** [comment]
>       server: http://10.223.252.101:3000/authorize

Are you sure this is right ? Isn't this expected to be `https` always ?

xref: https://kubernetes.io/docs/reference/access-authn-authz/webhook/#configuration-file-format

```yaml
      # URL of remote service to query. Must use 'https'. May not include parameters.
      server: https://authz.example.com/authorize
```

**Comment by harshanarayana** [comment]
I did a quick test and it works for me though. 

```yaml
root@test-control-plane:/# cat /etc/kubernetes/webhook.yaml
apiVersion: v1
kind: Config
clusters:
  - name: authorize-service
    cluster:
      #certificate-authority: /var/lib/minikube/certs/auth/ca.crt
      server: http://172.18.0.3:23232/authorize
      insecure-skip-tls-verify: true
users:
  - name: authorize-api-server
    user:
      token: test-token
current-context: webhook
contexts:
- context:
    cluster: authorize-service
    user: authorize-api-server
  name: webhook
```

```go
package main

import (
	"encoding/json"
	"net/http"
	"os"

	authorizationv1 "k8s.io/api/authorization/v1"
	"k8s.io/klog/v2"
)

func main() {
	http.HandleFunc("/authorize", func(w http.ResponseWriter, r *http.Request) {
		klog.Info("Processing request")
		resp := authorizationv1.SubjectAccessReview{
			Status: authorizationv1.SubjectAccessReviewStatus{
				Allowed: true,
			},
		}
		responseBytes, _ := json.Marshal(resp)
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.Header().Set("X-Content-Type-Options", "nosniff")
		w.WriteHeader(http.StatusOK)
		w.Write(responseBytes)
	})

	_, tlsMode := os.LookupEnv("TLS_MODE")
	if tlsMode {
		if err := http.ListenAndServeTLS(":23232", "/tmp/server.crt", "/tmp/server.key", nil); err != nil {
			panic(err)
		}
	} else {
		if err := http.ListenAndServe(":23232", nil); err != nil {
			panic(err)
		}
	}
}
```

```bash
2022-08-19T12:07:23.673918644Z I0819 12:07:23.673874       1 round_trippers.go:463] POST http://172.18.0.3:23232/authorize?timeout=30s
2022-08-19T12:07:23.674785584Z I0819 12:07:23.674078       1 round_trippers.go:469] Request Headers:
2022-08-19T12:07:23.674803363Z I0819 12:07:23.674164       1 round_trippers.go:473]     Content-Type: application/json
2022-08-19T12:07:23.674811256Z I0819 12:07:23.674283       1 round_trippers.go:473]     Accept: application/json, */*
2022-08-19T12:07:23.676262369Z I0819 12:07:23.675905       1 round_trippers.go:574] Response Status: 200 OK in 1 milliseconds
2022-08-19T12:07:23.677249522Z I0819 12:07:23.676780       1 authorization.go:73] "Forbidden" URI="/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0" Reason=""
--
........ snipped logs

2022-08-19T12:07:26.842802996Z I0819 12:07:26.842690       1 rbac.go:119] RBAC: no rules authorize user "system:node:test-control-plane" with groups ["system:nodes" "system:authenticated"] to "get" resource "leases.coordination.k8s.io" named "test-control-plane" in namespace "kube-node-lease"
2022-08-19T12:07:26.843058868Z I0819 12:07:26.842954       1 round_trippers.go:463] POST http://172.18.0.3:23232/authorize?timeout=30s
2022-08-19T12:07:26.843271444Z I0819 12:07:26.843132       1 round_trippers.go:469] Request Headers:
2022-08-19T12:07:26.843301015Z I0819 12:07:26.843188       1 round_trippers.go:473]     Accept: application/json, */*
2022-08-19T12:07:26.843355298Z I0819 12:07:26.843333       1 round_trippers.go:473]     Content-Type: application/json
2022-08-19T12:07:26.844974498Z I0819 12:07:26.844445       1 round_trippers.go:574] Response Status: 200 OK in 0 milliseconds
2022-08-19T12:07:26.845024279Z I0819 12:07:26.844708       1 authorization.go:73] "Forbidden" URI="/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/test-control-plane?timeout=10s" Reason=""
```
This is when i was forcefully setting `Allowed: false`

```bash
2022-08-19T12:08:10.967628443Z I0819 12:08:10.967483       1 rbac.go:119] RBAC: no rules authorize user "system:node:test-control-plane" with groups ["system:nodes" "system:authenticated"] to "get" resource "csinodes.storage.k8s.io" named "test-control-plane" cluster-wide
2022-08-19T12:08:10.968064642Z I0819 12:08:10.967961       1 round_trippers.go:463] POST http://172.18.0.3:23232/authorize?timeout=30s
2022-08-19T12:08:10.968079523Z I0819 12:08:10.967995       1 round_trippers.go:469] Request Headers:
2022-08-19T12:08:10.968083955Z I0819 12:08:10.968004       1 round_trippers.go:473]     Accept: application/json, */*
2022-08-19T12:08:10.968086949Z I0819 12:08:10.968010       1 round_trippers.go:473]     Content-Type: application/json
2022-08-19T12:08:10.968924770Z I0819 12:08:10.968652       1 round_trippers.go:574] Response Status: 200 OK in 0 milliseconds
2022-08-19T12:08:10.969108876Z I0819 12:08:10.968883       1 handler.go:153] kube-aggregator: GET "/apis/storage.k8s.io/v1/csinodes/test-control-plane" satisfied by nonGoRestful
^C
```
This is when it was working fine

**Comment by mathuvenkat** [comment]
Thanks for the details and trying out - i'm not sure how but modifying to below worked - the only difference in this and my previous code is. 

import {
authorizationv1 "k8s.io/api/authorization/v1"
}

json.Marshal(sarFinal)  vs json.Marshal(&sarFinal)

`
       import {
	v1 "k8s.io/api/authorization/v1"
       }
        content, err = ioutil.ReadAll(r.Body)
	authReq := &v1.SubjectAccessReview{}	
        json.Unmarshal(content, authReq)

	// Build the response obj
	var sarFinal v1.SubjectAccessReview
	sarFinal.Kind = authReq.Kind
	sarFinal.APIVersion = authReq.APIVersion

	var st v1.SubjectAccessReviewStatus
	st.Allowed = true
	sarFinal.Status = st

	responseBytes, err := json.Marshal(&sarFinal)
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	//w.WriteHeader(http.StatusOK)
	w.Write(responseBytes)
}`

**Comment by mathuvenkat** [comment]
@liggitt  @harshanarayana I have one more question related to this - is there any way to have the api-server pass the requestor token to the web-hook ? 
The use-case I'm looking at is to use an external authorizer to which we will forward the request to, but that needs the actual token with which it was invoked and not the groups[] which api-server seems to extract from the token. This is because groups in the ID token are usually very large and hence not populated but given a issuer link to obtain from etc. which the  PDP -> PIP will take care of. 

For eg. 
`curl -k https://<name>:6443/api/v1/namespaces/kube-system/pods/ --header "Authorization: Bearer <token>`
On this call , I do see the request coming through to the authorizer endpoint but no details of tokens in the header

`2022/08/19 20:53:48 {"Accept":["application/json, */*"],"Accept-Encoding":["gzip"],"Content-Length":["256"],"Content-Type":["application/json"],"User-Agent":["Go-http-client/1.1"]}`

How can I get the token of the requestor to be passed through to the authorizer webhook ?

**Comment by liggitt** [comment]
> @liggitt @harshanarayana I have one more question related to this - is there any way to have the api-server pass the requestor token to the web-hook ?

not to the authorization webhook, no... the credentials from the requesting user are only accessible to the authentication layer, including any authentication webhook

**Comment by mathuvenkat** [comment]
Thanks @liggitt for the confirmation.

**Comment by aholic** [comment]
> > @liggitt @harshanarayana I have one more question related to this - is there any way to have the api-server pass the requestor token to the web-hook ?
> 
> not to the authorization webhook, no... the credentials from the requesting user are only accessible to the authentication layer, including any authentication webhook

@liggitt  If I want to do authorization in webhook server(to make sure the client is kube-apiserver), can you give some suggestions ? The only member fields in WebhookClientConfig are URL/ServiceReference/CABundle, kube-apiserver can use CABundle to verify webhook server, but webhook server can not verify it's client(kube-apiserver).

**Comment by liggitt** [comment]
@aholic see the details at https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers

Identity information has to be provided to kube-apiserver at startup via the `--admission-control-config-file` flag

**Comment by drinkingjasminegreentea** [comment]
> > @liggitt @harshanarayana I have one more question related to this - is there any way to have the api-server pass the requestor token to the web-hook ?
> 
> not to the authorization webhook, no... the credentials from the requesting user are only accessible to the authentication layer, including any authentication webhook

@liggitt  - is it possible to add this as a new feature? I also have a use case where I'd like to pass the requestor's id2 token to the authorization webhook service.

**Comment by liggitt** [comment]
No, credentials are strictly limited to the authentication layer. User identity info derived *from* the credentials (username, group memberships, and arbitrary "extra" info the authentication layer derives from credentials) *is* sent to authorization and admission layers (see the `user`/`groups`/`uid`/`extra` fields sent to authorization webhooks in SubjectAccessReview payloads, and the `userInfo` stanza sent to admission in AdmissionReview request objects)
