### ISSUE TITLE
The value of .spec.template.spec.restartPolicy in kubectl explain Deployment/DaemonSet/StatefulSet template prompts an error

### ISSUE THREAD

**Issue by yangjunmyfm192085** [kubernetes/kubernetes#111829]
### What happened?

When using the command kubectl explain Deployment/DaemonSet/StatefulSet.spec.template.spec.restartPolicy, prompt
````
Restart policy for all containers within the pod. One of Always, OnFailure,Never. Default to Always.
````
But the value is Never, when kubectl applies the template file, it prompts
````
The Deployment "deployment" is invalid: spec.template.spec.restartPolicy: Unsupported value: "Never": supported values: "Always"

````

### What did you expect to happen?

When using the command kubectl explain Deployment/DaemonSet/StatefulSet.spec.template.spec.restartPolicy, prompt
````
Restart policy for all containers within the pod. Only Always. Default to Always.
````
But the value is

### How can we reproduce it (as minimally and precisely as possible)?

 kubectl explain Deployment.spec.template.spec.restartPolicy

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.0-alpha.2.981+985c9202ccd250", GitCommit:"985c9202ccd250a5fe22c01faf0d8f83d804b9f3", GitTreeState:"clean", BuildDate:"2022-08-06T08:53:16Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mengjiao-liu** [comment]
From the documentation description and code implementation, the above verification error is satisfactory.
docs:
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template
```
Only a [.spec.template.spec.restartPolicy](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) equal to Always is allowed, which is the default if not specified.
```

code:

https://github.com/kubernetes/kubernetes/blob/132f29769dfecfc808adc58f756be43171054094/pkg/apis/apps/validation/validation.go#L148-L150
https://github.com/kubernetes/kubernetes/blob/132f29769dfecfc808adc58f756be43171054094/pkg/apis/apps/validation/validation.go#L354
https://github.com/kubernetes/kubernetes/blob/132f29769dfecfc808adc58f756be43171054094/pkg/apis/apps/validation/validation.go#L738

**Comment by mengjiao-liu** [comment]
kubectl explain Deployment/DaemonSet/StatefulSet.spec.template.spec.restartPolicy descriptions can be misleading, perhaps we need to add more descriptions.
/assign

**Comment by liggitt** [comment]
Unfortunately, the documentation comes from the PodSpec object, which those workload types embed and then place additional restrictions on.

It wouldn't be appropriate to put documentation specific to those embedded uses on the PodSpec object.

**Comment by PengWang-SMARTM** [comment]
I've read two issues, [24725](https://github.com/kubernetes/kubernetes/issues/24725) and [40908](https://github.com/kubernetes/kubernetes/issues/40908).

Although both issue have been marked as closed, and I understand current implementation supports only "Always" for these workload types, like Deployment, I'm not convinced that it should support only “Always". Like many of others, I believe this is a valid request to have restartPolicy as OnFailure or Never.

Unless it's clear why OnFailure/Never shall not be valid for these workload types and the Kubernetes [specification](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#podspec-v1-core) and [explanation](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy) get updated as well, I personally believe the kubectl explain command is correct, and doesn't need any changes. On the other hand, the support of OnFailure and Never should be added.

As said by the [specification](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/#podspec-v1-core), restartPolicy is "`Restart policy for all containers within the pod.`"

My interpretation, this is the policy to restart the containers in the pod, but not the pod itself, even though it's in the pod spec. Let's say one of the containers in the pod completed successfully or with failures, this container may or may not restart depending on this policy. Although I don't understand why not each container has its own restart policy, this pod-wide shared common policy is good enough for most cases.

Anyway, I don't see a problem with the Kubernetes spec, and I disagree with this change request. Please reconsider making a change to the explain command. Thanks!

**Comment by PengWang-SMARTM** [comment]
I now see the documentation for these workload types, such as [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#pod-template), saying only `Always` is allowed. However, I don't understand why. Can someone explain that?

**Comment by JalinWang** [comment]
So the example in the doc is wrong?
https://kubernetes.io/docs/concepts/workloads/pods/#pod-templates
![image](https://github.com/user-attachments/assets/5ebf57a0-2902-4478-a9be-3e02e9f90933)
