### ISSUE TITLE
spec.containers[0].resources.limits.cpu = 0 is not unlimited

### ISSUE THREAD

**Issue by IBMRob** [kubernetes/kubernetes#111814]
### What happened?

I tried to create a pod with only requests specified. 

spec.containers[0].resources.limits.cpu = 0
spec.containers[0].resources.limits.memory = 0
spec.containers[0].resources.requests.cpu = 1
spec.containers[0].resources.requests.memory = 100Mi

This fails to deploy with the error "Error "Invalid value: "1": must be less than or equal to cpu limit" for field "spec.template.spec.containers[0].resources.requests"."

### What did you expect to happen?

The pod deployed with the requests set and no limits. 

If I deploy a pod with 

spec.containers[0].resources.limits.cpu = 0
spec.containers[0].resources.limits.memory = 0
spec.containers[0].resources.requests.cpu = 0
spec.containers[0].resources.requests.memory = 0

The pod deploys with no limits. If 0 is treated as being "no limits" then it when comparing values, If 0 it should be allowed.

I understand I could not specify the limits section but when deploying via golang and stucts, they are fully initialised and default to having zero values. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a deployment with 

spec.containers[0].resources.limits.cpu = 0
spec.containers[0].resources.limits.memory = 0
spec.containers[0].resources.requests.cpu = 1
spec.containers[0].resources.requests.memory = 100Mi

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5+3afdacb", GitCommit:"3c28e7a79b58e78b4c1dc1ab7e5f6c6c2d3aedd3", GitTreeState:"clean", BuildDate:"2022-05-10T16:30:48Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
OpenShift 4.10
</details>

### OS version

<details>

Mac 12.4

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
> I understand I could not specify the limits section but when deploying via golang and stucts, they are fully initialised and default to having zero values.

I don't think that's right.

The default is to not have the limits field set at all, not to have CPU set to 0, CPU limit isn't a fixed struct field.

The type for resource request + limits is here:
https://github.com/kubernetes/kubernetes/blob/7b1b8012954bad71b4383efeca2ad256fbd27bf7/staging/src/k8s.io/api/core/v1/types.go#L2285

**Comment by IBMRob** [comment]
They do appear to be empty when debugging the struct

<img width="390" alt="image" src="https://user-images.githubusercontent.com/2182970/184310758-863f64f3-6533-4916-8efb-2f3314c6f78c.png">

vs the requests where we have set them 

<img width="412" alt="image" src="https://user-images.githubusercontent.com/2182970/184310840-f205170a-83ed-42f3-a836-97825cfb112b.png">

but when we deploy that resource we get 

`1.660291069088341e+09	INFO	controller.integrationruntime	Failed to CreateOrUpdate Deployment retrying reconcile Deployment.apps "example-ir" is invalid: [spec.template.spec.containers[0].resources.requests: Invalid value: "50Mi": must be less than or equal to ephemeral-storage limit, spec.template.spec.containers[0].resources.requests: Invalid value: "256Mi": must be less than or equal to memory limit, spec.template.spec.containers[0].resources.requests: Invalid value: "300m": must be less than or equal to cpu limit]	{"Request.Namespace": "ace-rob", "Request.Name": "example"}`

as I presume they are being treated as 0 because the struct does exist

**Comment by BenTheElder** [comment]
Can you share more about what struct it is you’re using and how you’re setting and reading them?

they shouldn’t be present, you can set requests without limits. Is there a limit range? https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by IBMRob** [comment]
We're using this in our struct.

```go

type ReqLimStorage struct {
	// +kubebuilder:validation:Optional
	Requests RequestsCPUMemStorage `json:"requests,omitempty"`
	// +kubebuilder:validation:Optional
	Limits LimitsCPUMemStorage `json:"limits,omitempty"`
}

type LimitsCPUMemStorage struct {
	// +kubebuilder:validation:Optional
	// The upper limit of CPU core. Specify integers, fractions (e.g. 0.5), or millicores values (e.g. 100m, where 100m is equivalent to .1 core)
	CPU resource.Quantity `json:"cpu,omitempty"`
	// +kubebuilder:validation:Optional
	// The memory upper limit in bytes. Specify integers with suffixes: E, P, T, G, M, K, or power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki.
	Memory resource.Quantity `json:"memory,omitempty"`
	// +kubebuilder:validation:Optional
	// +kubebuilder:validation:Default=1073741824
	// The disk upper limit in bytes. Specify integers with one of these suffixes: E, P, T, G, M, K, or power-of-two equivalents: Ei, Pi, Ti, Gi, Mi, Ki.
	EphemeralStorage resource.Quantity `json:"ephemeral-storage,omitempty"`
}

**Comment by IBMRob** [comment]
This was due to having our own struct rather than using ResourceRequirements I am now able to do as required
