### ISSUE TITLE
Invalid Bearer token error in Kube-apiserver when using azure auth provider in kube-config

### ISSUE THREAD

**Issue by Anumita** [kubernetes/kubernetes#111902]
### What happened?

We have an kubeadm cluster (1 master and 2 worker nodes). The kube-apiserver is configured to use a webhook server for authn and authz. The kubeconfig is configured to use azure auth provider as well. On running any kubectl command , we are getting "Unauthorized" error . We checked that the request is not reaching our server pod and is failing in kube-apiserver.  The error in kube-apiserver is "Invalid bearer token". We checked the token and it is same as the token we are using in another environment where the kubectl command is working. 

We aren't sure how more to debug this , since increasing the verbosity in kube-apiserver is not increasing any logs as well. 

### What did you expect to happen?

kubectl command should not return unauthorized

### How can we reproduce it (as minimally and precisely as possible)?

not sure how we can reproduce this as it is working in one environment and not on the other. The only difference would be that there are no worker nodes in the other, it has only one master node

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux masterNode 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Ubuntu 20.04 LTS / Kubernetes 1.22.8 / Flannel / ContainerD
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
cc @enj
