### ISSUE TITLE
reset deleted_kinds strictRemovedHandlingInAlpha to false after beta

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#111972]
### What happened?

once the we hit a beta release, we can reset the default value for strict handling to false to prep for 1.26.

/kind cleanup
/priority important-soon
/milestone v1.26
/assign
/cc @deads2k

**Comment by dims** [comment]
Looks like Nov 10 ( https://www.kubernetes.dev/resources/release/ )

<img width="946" alt="image" src="https://user-images.githubusercontent.com/23304/192162087-c56e8bbf-b2a6-4774-8c8a-3dc2340adeb4.png">

**Comment by liggitt** [comment]
@leonardpahlke please don't drop the milestone from issues without asking first... this is why CI is failing on master currently

**Comment by leonardpahlke** [comment]
I removed all with code freeze and added the ones back that got approved as exception request / are big fixes. Missed this one; sorry.
