### ISSUE TITLE
[KMSv2] Allow encryption for all resources */*

### ISSUE THREAD

**Issue by ritazh** [kubernetes/kubernetes#111977]
ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements

/sig auth

**Comment by enj** [comment]
I believe #104165 has to be fixed first for this to be possible.

**Comment by dgrisonnet** [comment]
Is it really safe to have such mechanism in place? I would imagine that at scale this might have big implications for master nodes resource usage and kube-apiserver congestion

**Comment by enj** [comment]
> Is it really safe to have such mechanism in place? I would imagine that at scale this might have big implications for master nodes resource usage and kube-apiserver congestion

Asking people to understand what resource is or is not a secret in a system that can dynamically change what resources exist at runtime is (and always has been) the wrong approach.  We have _full_ disk encryption for a reason after all.  We are not forcing anyone to use this, just providing a switch to say "I want everything to be encrypted without having to maintain the list myself."  Users could already manually enumerate every resource on the cluster - its just a pain to do so and is impossible to maintain (and custom resources make it impractical to prevent unencrypted data from being written to disk).
