### ISSUE TITLE
MicroTime marshalled at different precision for json and proto

### ISSUE THREAD

**Issue by haoruan** [kubernetes/kubernetes#111928]
### What happened?

Found some error logs when sending series events to apiserver:
```
eventTime: Invalid value: 2022-08-19 16:00:45.305977 +0800 CST: field is immutable
``` 
seems the later eventTime differed from the first one in series events

After investigation, I found the problem was in the marshal.
MicroTime is supposed to work on microsecond level precision, but init with nanosecond level precision, in this case, `MarshalJSON` generates microsecond level precision data and `Marshal` generates nanosecond level precision, so when unmarshalled, the new time is not considered the exactly same as the original time (they are different at nanosecond level)

### What did you expect to happen?

MicroTime marshal should work at same precision for json and proto, so unmarshal can generate the exactly same MicroTime

### How can we reproduce it (as minimally and precisely as possible)?

```go
func TestTimeUnmarshalFromJSONAndProto(t *testing.T) {
	oldTime := NowMicro()
	jsonData, _ := oldTime.MarshalJSON()
	protoData, _ := oldTime.Marshal()

	var timeFromJSON, timeFromProto MicroTime
	timeFromJSON.UnmarshalJSON(jsonData)
	timeFromProto.Unmarshal(protoData)

	if !timeFromJSON.Equal(&timeFromProto) {
		t.Errorf("time got %v, want %v", timeFromJSON, timeFromProto)
	}
}
```

result:
```
--- FAIL: TestTimeUnmarshalFromJSONAndProto (0.00s)
    /home/dev/go/src/k8s.io/kubernetes/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_test.go:268: time got 2022-08-19 16:39:24.584397 +0800 CST, want 2022-08-19 16:39:24.584397474 +0800 CST
FAIL
FAIL	k8s.io/apimachinery/pkg/apis/meta/v1	0.012s
FAIL
```

### Anything else we need to know?

This causes the series events won't be updated on api-server after created

### Kubernetes version

master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Good catch... we'd probably need to truncate to microseconds when marshaling and unmarshaling proto to ensure any already persisted data is fixed up when read. Something like this:

```diff
diff --git a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
index 6dd6d8999f7..fa34826d9ca 100644
--- a/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
+++ b/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
@@ -27,9 +27,12 @@ func (m *MicroTime) ProtoMicroTime() *Timestamp {
 	if m == nil {
 		return &Timestamp{}
 	}
+	// truncate precision to microseconds to match JSON marshaling/unmarshaling
+	nanos := m.Time.Nanosecond()
+	nanos = int64(nanos/1000) * 1000
 	return &Timestamp{
 		Seconds: m.Time.Unix(),
-		Nanos:   int32(m.Time.Nanosecond()),
+		Nanos:   int32(nanos),
 	}
 }
 
@@ -51,6 +54,8 @@ func (m *MicroTime) Unmarshal(data []byte) error {
 	if err := p.Unmarshal(data); err != nil {
 		return err
 	}
+	// truncate precision to microseconds to match JSON marshaling/unmarshaling
+	p.Nanos = int64(p.Nanos/1000) * 1000
 	m.Time = time.Unix(p.Seconds, int64(p.Nanos)).Local()
 	return nil
 }
```

**Comment by haoruan** [comment]
Thanks for advice, going to send a PR soon
