### ISSUE TITLE
[KMSv2] Use expiring cache 

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#111920]
https://github.com/kubernetes/kubernetes/blob/d581cc90adba6c84919738841fe3e07302d53e33/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go#L95-L99

/sig auth

**Comment by cailynse** [comment]
Hey @aramase! Release Bug Triage Shadow here - I just wanted to see if this is still on track for the 1.26 release?

**Comment by aramase** [comment]
> Hey @aramase! Release Bug Triage Shadow here - I just wanted to see if this is still on track for the 1.26 release?

@cailynse Yes it is!

**Comment by cailynse** [comment]
Amazing! Thanks for the prompt update!
