### ISSUE TITLE
[sig-auth] New project board and use github actions for board sync

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#111963]
- [x] Create a new project for sig-auth
   - We're using the classic board today: https://github.com/orgs/kubernetes/projects/54 and want to migrate to use the new board
- [ ] Use github actions to automate board sync
   - xref: https://github.com/kubernetes-sigs/sig-windows-tools/blob/master/hack/sync-project-board.sh

/sig auth

**Comment by aramase** [comment]
@pigletfly It seems you have migrated the project board from classic to v2 but we don't have access to it because it's private. Would you be able to delete the private project board so we (sig-auth) can run the migration again?

ref: https://kubernetes.slack.com/archives/C01672LSZL0/p1670003787443179

**Comment by pigletfly** [comment]
> @pigletfly It seems you have migrated the project board from classic to v2 but we don't have access to it because it's private. Would you be able to delete the private project board so we (sig-auth) can run the migration again?
> 
> ref: https://kubernetes.slack.com/archives/C01672LSZL0/p1670003787443179

should  I close this project ?

**Comment by enj** [comment]
@pigletfly no action is necessary.  The GitHub folks figured out a bug on their end and will have this sorted soon.
