### ISSUE TITLE
[KMSv2] Add support for hot reload of the `EncryptionConfiguration`

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#111919]
- Watch on the `EncryptionConfiguration`
- When changes are detected, process the `EncryptionConfiguration` resource, and add new transformers and update existing ones atomically.
- If there is an issue with creating or updating any of the transformers, retain the current configuration in the kube-apiserver and generate an error in logs.

ref: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements

/sig auth

**Comment by HeshamAboElMagd** [comment]
Hello @nilekhc , bug triage team here. Just wanted to touch-base with your for any updates on this ticket.
Thanks

**Comment by enj** [comment]
> Hello @nilekhc , bug triage team here. Just wanted to touch-base with your for any updates on this ticket. Thanks

This is being worked on in #112050 but needs #112789 to be merged first to get the code in a state where this is achievable.  We are on track for this work landing in v1.26
