### ISSUE TITLE
Kubelet Ephemeral Storage by Disk

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#111965]
### What happened?

The Kubelet reports in the Node Status an aggregate for Ephemeral storage space in Allocatable and Capacity. The drawback to this is when a different partition - not the root partition - is mounted to `/var/lib/kubelet` or `/var/lib/containers`. The Ephemeral storage values reported do not reflect the reality of what is on the Node.

Is there a plan to split ephemeral storage reporting by partition? Should there be?

### What did you expect to happen?

Ephemeral storage reporting by the Kubelet should be accurate. How does this impact limits?

### How can we reproduce it (as minimally and precisely as possible)?

* Mount a new partition to /var/lib/containers or /var/lib/kubelet
* Start a local-up-cluster.sh
* Note the ephemeral storage is not reflecting the storage found in the newly created partitions

### Kubernetes version

All

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
Any
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rphillips** [comment]
Brought this to Sig-Node today. The general consensus is only one (root) partition is supported and reported by the Kubelet. 

@kad brought up that the runtime might be able to report ephemeral storage capacity, but that does not currently exist.

@derekwaynecarr brought up the point that exotic partition/mount layouts are problematic. But we might be able to have N ephemeral storage buckets.

Generally, only one partition is allowed at the moment.

**Comment by SergeyKanzhelev** [comment]
/close

looks like it was addressed as a documentation issue
