### ISSUE TITLE
[KMSv2] Add additional logging with UID and metadata

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#111923]
Add additional logging at level `6` that associates UID with the metadata from the request.

xref: https://github.com/kubernetes/kubernetes/pull/111126#discussion_r934911719

/sig auth

**Comment by harshanarayana** [comment]
@aramase @enj Mind if I take a look at this? 

/assign

**Comment by nilekhc** [comment]
Hello @harshanarayana, I am wondering how's this coming along. Is there anything I can help with?

**Comment by harshanarayana** [comment]
> Hello @harshanarayana, I am wondering how's this coming along. Is there anything I can help with?

Sorry. I got a bit occupied with a different project.. Will have a PR opened for this for review tomorrow.. I am trying to find a way to inject the Verbs into log. But haven't found the right way to include that into the context.. Any suggestion on what can be done?

**Comment by harshanarayana** [comment]
> > Hello @harshanarayana, I am wondering how's this coming along. Is there anything I can help with?
> 
> Sorry. I got a bit occupied with a different project.. Will have a PR opened for this for review tomorrow.. I am trying to find a way to inject the Verbs into log. But haven't found the right way to include that into the context.. Any suggestion on what can be done? 

@aramase any suggestion on what is the best way to get the additional metadata for verbs into this log? Move that info across using `ctx`?

**Comment by HeshamAboElMagd** [comment]
Hello @harshanarayana , bug triage team here, just wanted to touch base with you for updates on this ticket.
Thanks!

**Comment by aramase** [comment]
> Hello @harshanarayana , bug triage team here, just wanted to touch base with you for updates on this ticket.
Thanks!

@HeshamAboElMagd This is being worked on and is still on track for `v1.26`.

**Comment by harshanarayana** [comment]
@aramase  @HeshamAboElMagd  There is a Pull request opened on this already as well. But Waiting on some clarification to see if that needs additional changes.

**Comment by csantanapr** [comment]
Hi @harshanarayana, Bug Triage Team for v1.27 here o/
Just wanted to touch base with you for updates on this ticket.
Thanks!

**Comment by harshanarayana** [comment]
@csantanapr I am not working on this anymore Carlos. This was re-assigned

**Comment by aramase** [comment]
> Hi @harshanarayana, Bug Triage Team for v1.27 here o/ Just wanted to touch base with you for updates on this ticket. Thanks!

@csantanapr This is tracked for `v1.27`. I've linked the PR.
