### ISSUE TITLE
[KMSv2] Create new staging repo k8s.io/kms

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#111921]
This repo should start with just the KMS proto code under `k8s.io/kms/apis` (make sure the `OWNERS` files correctly require API approval).  We will expand it later to include the reference implementation code (under some library dirs and an examples dir).

**Comment by aramase** [comment]
Requested for staging repo: https://github.com/kubernetes/org/issues/3630

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.yml&title=REQUEST%3A+%3CCreate+or+Migrate%3E+%3Cgithub+repo%3E to create an issue for creating an actual repo

**Comment by aramase** [comment]
thanks @BenTheElder. I've created this [issue](https://github.com/kubernetes/org/issues/3630). Do we need +1 from sig-auth on that issue for creating the repo?

cc @dims

**Comment by BenTheElder** [comment]
AFAIK: yes. I think it can depend on the SIG charter, but typically it's up to the TLs with some lazy consensus from the broader SIG. The github management folks will be looking for the SIG to approve.
