### ISSUE TITLE
Some scheduler goroutines are not tracked in the metric

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#112034]
### What happened?

The metric `scheduler_goroutines` is not called in some instances where we initiate routines, like when we call Parallelize

### What did you expect to happen?

We increase the counter every time we create a routine.

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

The metric is called `scheduler_goroutines`, but it's already under the `scheduler` system. So the final metric has the name:

`scheduler_scheduler_goroutines`. Maybe we should just call it `goroutines`.

Note that we can't just remove a metric. We need to duplicate and mark the old one as deprecated for a release or two.

### Kubernetes version

<details>
master
</details>

### Cloud provider

<details>
N/A
</details>

**Comment by alculquicondor** [comment]
@sanposhiho, please assign to yourself if you are already working on this. Otherwise, I think this is a good fit for a new contributor.

**Comment by sanposhiho** [comment]
@alculquicondor 
I've worked on it in https://github.com/kubernetes/kubernetes/pull/112003 although I didn't create the new metric for renaming.

/sig scheduling
/assign

 I'll add the change to create the new metric (+ deprecate the old one) in #112003 as you describe.

**Comment by sanposhiho** [comment]
/reopen 

Let me reopen it so that I don't forget to remove old `scheduler_goroutines` metric.

@alculquicondor Can we remove `scheduler_goroutines` metric in the next release? Or should we wait more time?

**Comment by alculquicondor** [comment]
I would wait at least 2 releases, given how old this metric is.

**Comment by alculquicondor** [comment]
/remove-lifecycle stale

We can remove the old metric in 1.28

**Comment by alculquicondor** [comment]
oh, we can remove the old metric now. Any takers?

**Comment by sanposhiho** [comment]
thanks @kerthcet !
