### ISSUE TITLE
Use pod yaml to create a replication controller

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11209]
Currently, in order to create an RC, the user has to put pod specification (pod template) into a replication controller. But it seems natural to be able to create an RC having a pod definition, without having to copy pod specification to the RC. It is especially useful for examples and new users (this feature was suggested by a few of them).

Comments from email exchange:
- It's not generally possible to go from an existing pod to a pod template, although it may work most of the time. (@lavalamp)
- [Another user] also strongly recommended this. I think it might not be hard to put enough information into the Pod (as annotations, if necessary) so that you can do this. (@davidopp)
- We should definitely add something to kubectl to do this. (@brendandburns)

I can imagine we can proceed in (at least) two directions.
1. Create a PodTemplate entity in the API that can be used to create either pods or replication controllers (discussed in #170)
2. Add new option to `kubectl create rc`, to take a pod definition.

Option 2 seems to be easier to implement and easier to use. And doesn't pollute the API with new objects.

**Comment by marekbiskup** [comment]
I actually found podtemplate to be already present in both the API and kubectl. So it looks like 1. is already implemented - maybe it is just not documented and it is not in the examples (or maybe I overlooked it).

**Comment by bgrant0607** [comment]
See also #11490

**Comment by bgrant0607** [comment]
IMO, the scenario that makes the most sense is like expose: there is an existing Pod and someone wants to create a RC to adopt it.

**Comment by akshayl** [comment]
+1

As someone new to K8S, my understanding from reading the docs ("The population of pods that a replication controller is monitoring is defined with a label selector, which creates a loosely coupled relationship between the controller and the pods controlled..") made me assume all that is required to specify the pods controlled is a label selector. So I was puzzled when I got this error message when trying to create an RC to control pods specified separately:

```
The ReplicationController "web-rc" is invalid.
spec.template: required value
```

**Comment by astachurski** [comment]
I agree - totally counterintuitive behaviour. I want to have all component definitions split into functional entities svc/rc/po and get exactly the same error as you for rc compoment...

**Comment by bgrant0607** [comment]
I think this is adequately covered by #11490 and #170
