### ISSUE TITLE
Tracing: precise spanName of apiserver webhook requests

### ISSUE THREAD

**Issue by thehackercat** [kubernetes/kubernetes#112059]
### What happened?

When enable apiserver tracing, the webhook request spans only show spanName as `GET`/`POST`,  mostly because `opentelemetry-go v0.20.0` use http request operations as default span name, https://github.com/open-telemetry/opentelemetry-go-contrib/blob/v0.20.0/instrumentation/net/http/otelhttp/handler.go#L54-L56
 which is hard to understand. ![image](https://user-images.githubusercontent.com/10649416/186877756-cd7e6486-0c86-4a2b-b5a6-835ea953f7c1.png)

Following the open-telemetry standard of spanName, it's recommended to use `Method + Host` as spanName.

![image](https://user-images.githubusercontent.com/10649416/186878474-7cc8ad7b-78af-44b9-b35f-e62df3c5de38.png)

### What did you expect to happen?

SpanName of webhook request should be `Method + Host`, like 

![image](https://user-images.githubusercontent.com/10649416/186880111-20bd1a7a-0aeb-4a5e-b1da-4d1466ed8c8a.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. enable APIServerTracing feature gates of apiserver
2. create a pod
3. check tracing dashboard

### Kubernetes version

<details>

1.18

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thehackercat** [comment]
@dashpole https://github.com/kubernetes/kubernetes/pull/112060 I make a fix for this.

**Comment by dashpole** [comment]
Do you know if this is fixed in later versions of opentelemetry?

**Comment by dashpole** [comment]
Looks like https://github.com/open-telemetry/opentelemetry-go-contrib/issues/726 might be related

**Comment by thehackercat** [comment]
> Do you know if this is fixed in later versions of opentelemetry?

not yet, I think we can fix this in otel upstream, but it's hard to backport to otel `v0.20.0`, which is the version of otel used in Kubernetes

**Comment by dashpole** [comment]
Good point. It think fixing it here is a good idea in that case.

**Comment by fatsheep9146** [comment]
@dashpole could I take on this issue?

**Comment by dashpole** [comment]
yes.  Feel free to work on this.

**Comment by fatsheep9146** [comment]
![image](https://github.com/kubernetes/kubernetes/assets/11855957/5e192557-2d25-4e3e-a6f8-2124169baad9)
I test locally by 1.29 kubernetes and start a sample webhook, looks like the client span has already conforms to semantic conventions https://github.com/open-telemetry/opentelemetry-specification/blob/v1.1.0/specification/trace/semantic_conventions/http.md#name , which should be in the form of "HTTP {METHOD_NAME}"

**Comment by fatsheep9146** [comment]
![image](https://github.com/kubernetes/kubernetes/assets/11855957/9276afba-5d87-4154-bed7-8a40f8df4479)
For apiserver as a server, now the spanName is still KubernetesAPI, which I think we could enhance it into "HTTP get_account/{accountId}" format
