### ISSUE TITLE
Statefuleset/DaemonSet reports invalid status due to ResourceQuota.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/kubernetes#112010]
### What happened?

When we limited the number of pods for the namespace (let's say 2), then after we deployed the StatefulSet with 5 replicas. Only 2 pods were launched. This is expected behavior but when we see the status of StatefulSet it shows only 1 pod under the `Ready` column. It should show 2 pods in the column.

```
$ kubectl get resourcequota -n test2
NAME       AGE   REQUEST     LIMIT
pj-quota   50m   pods: 2/2   


$ kubectl get pod -n test2
NAME      READY   STATUS    RESTARTS   AGE
test2-0   1/1     Running   0          37m
test2-1   1/1     Running   0          36m

$ kubectl get sts -n test2
NAME    READY   AGE
test2   1/5     33m
```

A similar issue also occurred with DaemonSet. When we deployed the DaemonSet in the namespace (on which limited the pod) on the multi-node cluster(1 master node, 2 workers node), it deployed one pod on 2 nodes out of 3 nodes. which is the expected behavior. But the same issue here when we see the status for DaemonSet. It shows 1 pod under the `CURRENT` and `UP-TO-DATE`  column and 0 pods under the `READY` and  `AVAILABLE` column. It should show 2 pods in these columns.

```
$ kubectl get resourcequota -n test
NAME       AGE    REQUEST     LIMIT
pj-quota   141m   pods: 2/2   

$ kubectl get pod -n test
NAME          READY   STATUS    RESTARTS   AGE
test2-lj58r   1/1     Running   0          5m19s
test2-xhq2m   1/1     Running   0          5m19s

$ kubectl get daemonset -n test
NAME    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test2   3         1         0       1            0           <none>          5m57s
```

It is only when we apply ResourceQuota in the namespace. If we don't apply ResourceQuota then it shows the expected status for the DaemonSet and StatefulSet.

I also checked this behavior with Deployment also, but in that case, it works fine.

```
$ kubectl get deployment -n test3
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
test-deployment   2/4     2            2           23s
```

### What did you expect to happen?

Statefuleset and DaemonSet should show the correct status when we applied ResourceQuota in the namespace.

For this specific issue it should show like:

**StatefulSet:**
```
$ kubectl get sts -n test2
NAME    READY   AGE
test2   2/5     33m

```
**DaemonSet:**
```
$ kubectl get daemonset -n test
NAME    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test2   3         2         2       2            2           <none>          5m57s
```

### How can we reproduce it (as minimally and precisely as possible)?

1) Set up the multinode cluster (1 master, 2worker nodes):

> minikube start --nodes 3 -p multinode-demo

2) Create 2 namespaces one for StatefulSet and one for DaemonSet:

>$ kubectl create ns test

>$ kubectl create ns test2

3) Apply the below ResourceQuota yaml to both namespaces:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pj-quota
spec:
  hard:
    pods: "2"
```

4) In namespace `test2` applies below yaml's for StatefulSet:

**svc.yaml:**

```
apiVersion: v1
kind: Service
metadata:
  name: test2
  labels:
    app: test2
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: test2
```

**sts.yaml:**

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test2
  name: test2
spec:
  replicas: 5
  serviceName: "test2"
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - command:
        - sh
        - -c
        - "while :; do echo hogehoge; sleep 5 & wait; done"
        image: docker.io/library/busybox
        imagePullPolicy: Always
        name: cli1
```
Now check the following commands:
> kubectl get pod -n test2
> kubectl get sts -n test2

4) In namespace `test` applies below yaml for DeamonSet:

daemonset.yaml:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test2
  name: test2
spec:
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - command:
        - sh
        - -c
        - "while :; do echo hogehoge; sleep 5 & wait; done"
        image: docker.io/library/busybox
        imagePullPolicy: Always
        name: cli1
```

Now check the following commands:
>$ kubectl get pod -n test
>$ kubectl get daemonset -n test

### Anything else we need to know?

No response

### Kubernetes version

<details>

```console
$ kubectl version
v1.24.3
$ kubernetes version
v1.24.1
$ minikube version
minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565

```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

N/A
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
The issue with statefulset has been already addressed in the latest kubernetes by https://github.com/kubernetes/kubernetes/pull/109694.

I'll cherry-pick it to release-1.24 so that it can be fixed after the next 1.24.x release.

For the daemonset, I'll look further.

**Comment by Shubham82** [comment]
> The issue with statefulset has been already addressed since v1.25 kubernetes by #109694.
> 
> I'll cherry-pick it to release-1.24 so that it can be fixed after the next 1.24.x release.
> 
> For the daemonset, I'll look further.

Thanks, @gjkim42 for this information and for cherry-pick

**Comment by alculquicondor** [comment]
How critical is this?

**Comment by Shubham82** [comment]
Hi @alculquicondor
There is no criticality functionality wise but this issue makes it difficult for users to debug if they applied ResourceQuota to their namespace. so it will be a great help for the users if we can merge it in upcoming releases for v1.24 and v1.23.

**Comment by gjkim42** [comment]
DaemonSet has the exact same issue that cannot update status if pod creation fails.

I'll propose a PR to fix it.

**Comment by alculquicondor** [comment]
We only backport critical bugfixes, and I'm not hearing that this is one.

If you disagree, maybe you might want to bring the discussion to the SIG Apps meeting.

**Comment by Shubham82** [comment]
I agree with you on the criticality part.
But can we mention this issue somewhere, so that users will know about it like in which k8s version it will not work?
is it valid to do that?

**Comment by alculquicondor** [comment]
Maybe somewhere in the reference docs https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/, although most of them are automatically generated from code comments. Still, you can check the github.com/kubernetes/website and propose a PR.

**Comment by Shubham82** [comment]
Thanks, sure I will open an issue in kubernetes/website to check the best place where we can mention this thing.

**Comment by Shubham82** [comment]
Created the issue for docs: https://github.com/kubernetes/website/issues/36527

**Comment by gjkim42** [comment]
IMHO, if we think this issue is important enough to document on the website, we may rather consider cherry-picking it.

I am not against it, but I think we could choose either cherry-pick https://github.com/kubernetes/kubernetes/pull/109694 or just leave it.

**Comment by Shubham82** [comment]
> IMHO, if we think this issue is important enough to document on the website, we may rather consider cherry-picking it.
> 
> I am not against it, but I think we could choose either cherry-pick #109694 or just leave it.

Hi @gjkim42
IMO, Someone from the Apps team can help with that.

**Comment by Shubham82** [comment]
@kubernetes/sig-apps-pr-reviews: could you please take a look at this issue?

**Comment by Shubham82** [comment]
As this PR#112127 is merged in k8s v1.26 but it still shows the invalid status for DaemonSet. Please find my observation below:

I did this on a Multinode cluster that has 1-master node and 2-worker nodes.

When I set the values of the pod less than the pod deployed by DaemonSet in ResourceQuota:
1)
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pj-quota
spec:
  hard:
    pods: "1" 
```

```
$ kubectl get resourcequota -n test
NAME       AGE   REQUEST     LIMIT
pj-quota   22s   pods: 0/1 
``` 

Used below DeamonSet yaml:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: test2
  name: test2
spec:
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - command:
        - sh
        - -c
        - "while :; do echo hogehoge; sleep 5 & wait; done" 
        image: docker.io/library/busybox
        imagePullPolicy: Always
        name: cli1
```

On apply above DeamonSet yaml:

```
$ kubectl get pod -n test
NAME          READY   STATUS    RESTARTS   AGE
test2-zjv8j   1/1     Running   0          10s

$ kubectl get resourcequota -n test
NAME       AGE   REQUEST     LIMIT
pj-quota   28m   pods: 1/1

$ kubectl get ds -n test
NAME    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test2   0         0         0       0            0           <none>          24s
```
It didn't show the correct status for DS.

But when I used the same value  of the pod same/more to the pod deployed by DaemonSet in ResourceQuota, it's worked fine:

2)
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pj-quota
spec:
  hard:
    pods: "3" 
```

```
$ kubectl get resourcequota -n test1
NAME       AGE   REQUEST     LIMIT
pj-quota   15m   pods: 0/3
```

On applied the DS,

```
$ kubectl get pod -n test1
NAME          READY   STATUS    RESTARTS   AGE
test2-f68tq   1/1     Running   0          21m
test2-lm58z   1/1     Running   0          21m

$ kubectl get resourcequota -n test1
NAME       AGE   REQUEST     LIMIT
pj-quota   15m   pods: 2/3

$ kubectl get  ds -n test1
NAME    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test2   2         2         2       2            2           <none>          18s
```

3)

```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pj-quota
spec:
  hard:
    pods: "2" 
```

on applied DS.

```
$ kubectl get resourcequota -n test
NAME       AGE     REQUEST     LIMIT
pj-quota   9m52s   pods: 2/2

$ kubectl get pod -n test
NAME          READY   STATUS    RESTARTS   AGE
test2-5ql97   1/1     Running   0          9m
test2-rpcht   1/1     Running   0          9m

$ kubectl get ds -n test
NAME    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
test2   2         2         2       2            2           <none>          9m40s
```

There is issue in 1st Observation.

**Comment by Shubham82** [comment]
Hi @gjkim42 @soltysh @alculquicondor 
PTAL

**Comment by gjkim42** [comment]
#112127 has been reverted by #113733 because of #113036.
Now we are trying to address this issue at https://github.com/kubernetes/kubernetes/pull/113787.

**Comment by Shubham82** [comment]
Thanks, @gjkim42 for this information.
So we are targeting it in v1.27.

**Comment by Shubham82** [comment]
so can we update/remove it from Changelog for v1.26, as it is mentioned under [Bug or Regression](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md#bug-or-regression).

> Fixed DaemonSet to update the status even if it fails to create a pod. (https://github.com/kubernetes/kubernetes/pull/112127, [@gjkim42](https://github.com/gjkim42))

So it will not create any confusion.

**Comment by alculquicondor** [comment]
@sftim can we change the changelog that was already published? Somehow we missed that the PR was reverted.

**Comment by sftim** [comment]
Sorry, I don't know a huge amount about the mechanics of how we publish a changelog. It was already set up and working when I got here.

**Comment by alculquicondor** [comment]
@Shubham82 can you open a PR for master to see what the owners say?

**Comment by Shubham82** [comment]
> @Shubham82 can you open a PR for master to see what the owners say?

I asked in the sig-release community slack channel about this, once I will get a response regarding the changelog from them I will update it. Here is the link for it: https://kubernetes.slack.com/archives/C2C40FMNF/p1671476551668349

**Comment by Shubham82** [comment]
@alculquicondor opened PR #114602  for update the Changelog-1.26.md. Once it will fix on the master I will cherry-pick it to the release-1.26 branch.

**Comment by gjkim42** [comment]
Related PRs are all merged.
for statefulset v1.25: #109694
for daemonset master(v1.27): #113787

I'll let sig-apps decide whether to cherry-pick them or not.

/unassign

**Comment by Shubham82** [comment]
> @alculquicondor opened PR #114602 for update the Changelog-1.26.md. Once it will fix on the master I will cherry-pick it to the release-1.26 branch.

Raised a PR: #114838 to cherry-pick it(update the Changelog-1.26.md) to the v1.26 branch.

**Comment by Shubham82** [comment]
Hi @gjkim42 

I think all related PR for this issue are merged except #113726.

For DemonSets: Resolved in v1.27(master): #113787
- Cherry-pick it to v1.26: #114819
- Cherry-pick it to v1.25: #114818

For StatefulSet: Resolved in v1.25: #109694
- Cherry-pick it to v1.23: #112084
- Cherry-pick it to v1.24 #112083

Am I right?

**Comment by Shubham82** [comment]
As this issue is backported so I am closing the issue: [k/website:36527](https://github.com/kubernetes/website/issues/36527)

**Comment by Shubham82** [comment]
Once issue #113726 will merge, I will close this issue also.

**Comment by gjkim42** [comment]
> Once issue #113726 will merge, I will close this issue also.

After looking at #113726, I think it is ok to just close this now as the PR is not really related to this issue but the clean up.

/close
