### ISSUE TITLE
[CI] pull-kubernetes-e2e-gce jobs using "Unavailble Services"

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#112036]
Seen in all gce jobs like

 https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/110470/pull-kubernetes-e2e-gce-ubuntu-containerd/1562786578244308992/artifacts/e2e-92b275a2f4-a7d53-master/kube-apiserver.log

https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce-ubuntu-containerd/1562793021089517568/artifacts/e2e-8cc512a620-a7d53-master/kube-apiserver.log

```
25 13:54:55.680558       9 httplog.go:131] "HTTP" verb="GET" URI="/apis?timeout=32s" latency="512.393µs" userAgent="kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19" audit-ID="6d3b5b1b-6da4-4492-b9ce-8fa8afcd66c8" srcIP="127.0.0.1:36950" apf_pl="exempt" apf_fs="exempt" apf_execution_time="249.611µs" resp=200
I0825 13:54:55.683168       9 httplog.go:131] "HTTP" verb="GET" URI="/apis/metrics.k8s.io/v1beta1?timeout=32s" latency="816.403µs" userAgent="kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19" audit-ID="be3d38fc-44f1-4541-a294-42792793ee1b" srcIP="127.0.0.1:36950" apf_pl="exempt" apf_fs="exempt" apf_execution_time="488.608µs" resp=503 statusStack=<
	
	goroutine 19424 [running]:
	k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc00de02bb0, 0xc00966e300?)
		vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:324 +0x90
	k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc00de02bb0, 0xc003463760?)
		vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:306 +0x25
	k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc00966e330, 0x1f7?)
		vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:236 +0x1c8


(... snipped ...)
	k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1()
		vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:114 +0x70
	created by k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
		vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:100 +0x1d8
 > addedInfo=<
	
	logging error output: "service unavailable\n"
```

`"/apis/metrics.k8s.io/v1beta1?timeout=32s` does this exist?

Interesting the big number of request from one agent identified as ` userAgent="kubectl/v1.20.2 (linux/amd64) kubernetes/faecb19"`  too

```
grep -r kubectl kube-apiserver.log  | grep 1.20 | wc                                                                                                                                                                                  
  18591  316231 7202761
```

**Comment by BenTheElder** [comment]
It's not clear why this is SIG testing?
The cluster came up and tests ran ... The CI infra provided everything needed and it doesn't seem to be an issue with the e2e framework either.

This looks like a bug in Kubernetes to me.

rest of the logs https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110470/pull-kubernetes-e2e-gce-ubuntu-containerd/1562786578244308992

**Comment by aojea** [comment]
heh, no, those errors are from my PR, that is no the issue here.

This URL `/apis/metrics.k8s.io/v1beta1?timeout=32s` is from the metrics server , right?

and this userAgent `userAgent="kubectl/v1.20.2 (linux/amd64)` , it has to be external, I added sig-testing because there is no `hack/` and `cluster/` sig :upside_down_face: 

I think this is coming from there
