### ISSUE TITLE
topologySpreadConstraints not working as expected with nodeSelector

### ISSUE THREAD

**Issue by harinarayanan-muthukumar** [kubernetes/kubernetes#112040]
### What happened?

I am using the below nodeSelector and topologySpreadConstraints in my deployment 

```
spec:
  replicas: 4  
 spec:
      nodeSelector:
        product: v1
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: product
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: v1-auth
```

and I have the below nodes with respective labels named product=v1 , product=v2 etc respectively .

```
node name	                                        label
aks-v2-41431125-vmss000000	                        product=v2
aks-v3-25883244-vmss000000	                        product=v3
aks-v4-20233382-vmss000001	                        product=v4
aks-v5-33491975-vmss000002	                        product=v5
aks-systemnodes-42599512-vmss000000	                product=system
aks-systemnodes-42599512-vmss000001	                product=system
aks-v1-28354762-vmss000000	                        product=v1

```

### What did you expect to happen?

Based on my node selector , since I asked it to select nodes where product=v1 , the pods are getting scheduled only on that node , but the topologySpreadConstraints  with maxsku = 1 is not getting honored and I see that all the 4 replicas are getting scheduled on the aks-v1-28354762-vmss000000 node itself  where as i expect only one pod to get scheduled on that aks-v1-28354762-vmss000000 node and the aks autoscaler should have kicked in and added more nodes to accommodate other 3 pods that should have gone into pending. 

If I remove the nodeselector out of the picture (and cordon other nodes) what I expect to happen is happening  , where one pod gets scheduled on the v1 node and others go into pending state . 

I tried experimenting with topologyKey: kubernetes.io/hostname but even that has similar results , Please help me in understanding this a bit better . What I try to achieve here is to  find a way to spread our replicas across few nodes so we dont run into outages during one node crashing on us .

### How can we reproduce it (as minimally and precisely as possible)?

All Deployment with podtopologyspread constrains and node selectors seems to be having this issue 

### Kubernetes version

1.21.11

### Cloud provider

Azure / AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
This is as expected, for we have only one domain here. we solved this problem in v1.25 by providing a new field minDomains to help spreading across minimum specified quantity domains. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3022-min-domains-in-pod-topology-spread

**Comment by kerthcet** [comment]
Plz close this if it helps.

**Comment by kerthcet** [comment]
Plz close this if this helps @harinarayanan-muthukumar

**Comment by harinarayanan-muthukumar** [comment]
Makes sense as there is only one domain ,  looking forward to test the mindomains out.
