### ISSUE TITLE
Extract ParseError from PodInfo

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#112096]
### What would you like to be added?

Currently we have `ParseError` here https://github.com/kubernetes/kubernetes/blob/891cbede96ab4b64c48edf25f8bbd331d8731622/pkg/scheduler/framework/types.go#L121-L128

And we'll validate the error like this: https://github.com/kubernetes/kubernetes/blob/891cbede96ab4b64c48edf25f8bbd331d8731622/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L243-L246

This is not a golang traditional style, I would like to extract the `ParseError` from `PodInfo`.

The disadvantage is `ParseError` is usually generated in `NewPodInfo`, and `NewPodInfo` is widely used throughout the scheduler.

### Why is this needed?

Make `NewPodInfo` adopt to golang traditional style.

**Comment by kidddddddddddddddddddddd** [comment]
Do you need help? I think I can fix this one if you let me. :)

**Comment by kerthcet** [comment]
Actually this is still under discussion. cc @alculquicondor for thoughts.

**Comment by alculquicondor** [comment]
I'm fine with the change, but keep in mind that this could break cluster-autoscaler and the scheduling-plugins repo.

**Comment by alculquicondor** [comment]
I think they just need fair notice, or you could also write the PRs in the corresponding repos to adapt to the change.

**Comment by kidddddddddddddddddddddd** [comment]
> I think they just need fair notice, or you could also write the PRs in the corresponding repos to adapt to the change.

@alculquicondor 
I think for `cluster-autoscaler` and the `scheduling-plugins` repo, they just need to simply update the correspoding vendor(please correct me if I'm wrong). I can open an issue in both repos after getting an `lgtm` for the PR related to this issue.

**Comment by alculquicondor** [comment]
they have to do code changes, because the function would have 2 return values

**Comment by kidddddddddddddddddddddd** [comment]
> they have to do code changes, because the function would have 2 return values

I have another question :( . When should we write the PRs in the corresponding repos/How do those repos manage their vendor version? Should we update the vendor to master version or a release version? If it's the later one, does that means we should do the code changes in those repos after a release?

**Comment by alculquicondor** [comment]
I think that would be in their master repos. @x13n and @Huang-Wei to confirm.

**Comment by kidddddddddddddddddddddd** [comment]
> I think that would be in their master repos. @x13n and @Huang-Wei to confirm.

I mean k8s.io/kubernetes branch in their vendor. I found `k8s.io/kubernetes v1.24.3` in `scheduler-plugins` and `k8s.io/kubernetes v1.25.0` in `cluster-autoscaler`. Seems like that they only update the vendor to a release tag.

**Comment by kidddddddddddddddddddddd** [comment]
> I mean k8s.io/kubernetes branch in their vendor. I found `k8s.io/kubernetes v1.24.3` in `scheduler-plugins` and `k8s.io/kubernetes v1.25.0` in `cluster-autoscaler`. Seems like that they only update the vendor to a release tag.

Since this doesn't affect the code changes in this repo :) . I'll try to do the corresponding changes in the next few days.
If @kerthcet can let me have a try :)

**Comment by kerthcet** [comment]
Yes, plz go ahead. Contribution is always welcome. @kidddddddddddddddddddddd

**Comment by kidddddddddddddddddddddd** [comment]
/assign

Thank you both.

**Comment by kerthcet** [comment]
Friendly reminding, since we have dependences, better to check these repos whether this will introduce big changes. If so we should reconsider the cost.

**Comment by kidddddddddddddddddddddd** [comment]
> Friendly reminding, since we have dependences, better to check these repos whether this will introduce big changes. If so we should reconsider the cost.

I checked `cluster-autoscaler` and `scheduler-plugins` before. It seems that `cluster-autoscaler` only referenced `NewPodInfo` in their vendor. `scheduler-plugins` will have to do some code changes since they use `NewPodInfo` directly, but that part of codes is all in test files, so this should be a small change for them.

Any other repo suggestions? (for me to check)

**Comment by kerthcet** [comment]
They're the two most important repos I can think of.

**Comment by x13n** [comment]
Cluster Autoscaler looks safe as far as I can tell. We don't use `NewPodInfo` anywhere: https://github.com/kubernetes/autoscaler/search?q=NewPodInfo

**Comment by kidddddddddddddddddddddd** [comment]
> Cluster Autoscaler looks safe as far as I can tell. We don't use `NewPodInfo` anywhere: https://github.com/kubernetes/autoscaler/search?q=NewPodInfo

Actually it's not. Although `Cluster Autoscaler` doesn't use `NewPodInfo`, it uses `NewNodeInfo`  which calls `NewPodInfo`. So `NewNodeInfo`  will also have two return values and will cause some code changes in `Cluster Autoscaler`.

I think servel functions will have different numbers of return values after extracting parseError from PodInfo. 

They are 
`(pi *PodInfo) Update(pod *v1.Pod) error`
`NewPodInfo(pod *v1.Pod) (*PodInfo, error)` 
`NewNodeInfo(pods ...*v1.Pod) (*NodeInfo, error)` 
`(n *NodeInfo) AddPod(pod *v1.Pod) error`

I'm not sure if any other functions are affected, I'll find out during making the corresponding changes.

**Comment by x13n** [comment]
Right, CA definitely uses `NewNodeInfo` a lot. We'll need a significant update after bumping k8s deps, but it should be a straightforward one.

**Comment by kidddddddddddddddddddddd** [comment]
@kerthcet 

I found that in some cases,The original code doesn't care if there is an error happened during `NewPodInfo`, [schdule_one](https://github.com/kubernetes/kubernetes/blob/1913c6be3580da23109493b2bc52b119ee70941e/pkg/scheduler/schedule_one.go#L876) for example. In these cases, the returned podInfo will have correct meta information and some wrong AffinityTerms(`pInfo below`). 

If there is an error occured during `NewPodInfo` now, should I stop the Scheduling process by return a nil podInfo in `NewPodInfo`  like this.
```
func NewPodInfo(pod *v1.Pod) (*PodInfo, error) {
	pInfo := &PodInfo{}
	if err := pInfo.Update(pod); err != nil {
		return nil, err
	}
	return pInfo, nil
}
```

or should I pass the correct meta data and log the error,so the scheduling process can go on?
```
func NewPodInfo(pod *v1.Pod) (*PodInfo, error) {
	pInfo := &PodInfo{}
	if err := pInfo.Update(pod); err != nil {
		return pInfo, err
	}
	return pInfo, nil
}
```

**Comment by kerthcet** [comment]
> I found that in some cases,The original code doesn't care if there is an error happened during `NewPodInfo`, [schdule_one](https://github.com/kubernetes/kubernetes/blob/1913c6be3580da23109493b2bc52b119ee70941e/pkg/scheduler/schedule_one.go#L876) for example. In these cases, the returned podInfo will have correct meta information and some wrong AffinityTerms(`pInfo below`).
> 
> If there is an error occured during `NewPodInfo` now, should I stop the Scheduling process by return a nil podInfo in `NewPodInfo` like this.

I think the intension here is if we parse the affinity terms error, we'll ignore the terms when scheduling. 

See below, if parsing error, the terms will be nil, that means ignore them when scheduling.

https://github.com/kubernetes/kubernetes/blob/bcea98234f0fdc5ce4e976758977eec72b13bfd4/pkg/scheduler/framework/types.go#L163-L187

**Comment by kerthcet** [comment]
Let's keep the logics as they are. That means 
```
func NewPodInfo(pod *v1.Pod) (*PodInfo, error) {
	pInfo := &PodInfo{}
	if err := pInfo.Update(pod); err != nil {
		return pInfo, err
	}
	return pInfo, nil
}
```

My intension of extracting parseError is that we should explicitly return errors rather than implicitly.

**Comment by kidddddddddddddddddddddd** [comment]
> My intension of extracting parseError is that we should explicitly return errors rather than implicitly.

I got it, ignore affinity terms instead of ignoring the pod. Then **how do we deal this error**? Just simply add a log about it?

Currently I ignore the pod when an error occurred in 112219. I'll take some time change the corresponding codes. You can review that pr when I ping you again:)
