### ISSUE TITLE
Show logs from updated pods during rolling update

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11212]
This is a suggestion from one of our users.

During rolling update, we are informed about replication controller changes:

```
biskup@cathedral:~/go/src/github.com/GoogleCloudPlatform/kubernetes$ kubectl rolling-update update-demo-nautilus --update-period=10s -f examples/update-demo/kitten-rc.yaml
Creating update-demo-kitten
At beginning of loop: update-demo-nautilus replicas: 3, update-demo-kitten replicas: 1
Updating update-demo-nautilus replicas: 3, update-demo-kitten replicas: 1
At end of loop: update-demo-nautilus replicas: 3, update-demo-kitten replicas: 1
Stopping update-demo-nautilus replicas: 3 -> 0
Update succeeded. Deleting update-demo-nautilus
update-demo-kitten
```

But even if replication controllers are scaled properly, we don't know if the pods actually started and are well. A way to check pods is to get logs from each of them and check if they printed a certain message like `service started`. Currently to achieve it, we have to list pods, identify which ones belong to the new RC and get logs from them. It would be nice to show logs from pods **during** rolling update, so that the admin could see how the update goes.

Ways to proceed:
1. fetch and print pod logs by `kubectl rolling update` (this was the suggestion).
2. improve our examples and show an equivalent (and easy) way to accomplish the same.

Equivalent ways may be:
A) health checking on pods; The health-check results should then be presented by `kubectl rolling update`

cc. @brendandburns

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by bgrant0607** [comment]
We should monitor readiness of pods during the update process: #11484

I could also imagine printing the new-style "get pods" output, which displays readiness and status.

Logs would be too verbose.

**Comment by nikhiljindal** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/pull/11942 adds support for specifying the availability check.
It will be "created" by default, but user can change that to "ready", in which case rolling-update will ensure that the new pods are ready while doing the update

**Comment by zjj2wry** [comment]
maybe now have kubectl rollout status? can close this?
