### ISSUE TITLE
create an alias 'list' for `kubectl get'

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11210]
Some software (e.g. gcloud or ecs CLI) uses the work `list` instead of `get` to retrieve a list of API objects (e.g. pods, replication controllers, etc). Users may be happy to have more consistent CLI even across products. Adding a synonym `list` for retrieving objects would make users life slightly easier.

On the other hand, a good practice is to have only one way to make things, so that users don't have to learn and remember various names and aliases.

**Comment by marekbiskup** [comment]
cc @brendandburns

**Comment by feihujiang** [comment]
@marekbiskup Is there anyone to work on this? If not, I'd like to work on this next week. And another question, Does it need kubectl list (pods/replication/controllers) --watch too?

**Comment by bgrant0607** [comment]
cc @ghodss, who had an opinion on aliases

**Comment by ghodss** [comment]
> On the other hand, a good practice is to have only one way to make things, so that users don't have to learn and remember various names and aliases.

I prefer this approach, as outlined in https://github.com/kubernetes/kubernetes/issues/8319#issuecomment-103994174. Currently we have only one way for all commands (except for explicitly deprecated aliases) and I think that's a very envious place to be, and one we should not give up lightly. However, git does have a very nice feature where an individual user can create [their own aliases for commands](https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases), and I think this is preferred. If #10693 were to be completed, then ~/.kubectl would be a very natural place for those kind of preferences.

**Comment by marekbiskup** [comment]
@ghodss, I also think this is a better approach. I suggest closing this issue and opening another one for config-based aliases.

**Comment by thockin** [comment]
#18023 is for user-defined aliases

**Comment by bgrant0607** [comment]
Closing in favor of #18023
