### ISSUE TITLE
When kubelet enable rotate-certificates and bootstrap, request CSR in foreground

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#112170]
### What would you like to be added?

Now when kubelet enable `rotate-certificates` and `bootstrap-kubeconfig`, it will request CSR in background

Consider the following scenario:
1. Hundreds of nodes have been scaled out, these kubelet will request CSR in background and register themself.
2. The kube-controller-manager will approve and issue these CSRs. Some approval will delay a second because the kube-controller-manager load is high.
3. With the delayed CSR approval, kubelet failed to register node util the next loop in [certificate check](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/certificate/transport.go#L100). The error message will be like `system:bootstrap no permission`, kubelet use the bootstrap token to register, but the bootstrap token has no permission
4. The certificate check period is 10s, so the kubelet will delay 10s to register.
 

### Why is this needed?

When kubelet enable rotate-certificates and bootstrap , request CSR in foreground. Even the CSR delayed a seconds, the kubelet will register successfully Immediately after the CSR approved. It don't need to wait 10s for the certificate check.

**Comment by pacoxu** [comment]
> * The kube-controller-manager will approve and issue these CSRs. Some approval will delay a second because the kube-controller-manager load is high.
> * With the delayed CSR approval, kubelet failed to register node util the next loop in [certificate check](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/certificate/transport.go#L100). The error message will be like `system:bootstrap no permission`, kubelet use the bootstrap token to register, but the bootstrap token has no permission

Just curious about the delay reason. No enough CPU or memory. Or just a tunning problem. We can tune the `--kube-api-burst` and `--kube-api-qps` in [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) options/flags.

**Comment by chenk008** [comment]
@pacoxu In my test, the `--kube-api-burst` is 1500 and `--kube-api-qps` is 1000. There is no `throttle` in log. 

I found the cert approval/sign  concurrency is 5,  each approval/sign will cost 15ms,  so in one second the kube-controller-manager can sign 1000/15*5 =333 certificate. When we scale out hundreds of nodes, some CSRs will delay and the kubelet use bootstrap token to register.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/3ffdfbe286ebcea5d75617da6accaf67f815e0cf/cmd/kube-controller-manager/app/certificates.go#L49-L67

Concurrency 5 seems to be hardcoded above. @liggitt  do you agree that a flag should be added to tuning it?

**Comment by chenk008** [comment]
It looks good to me that adding a flag to tuning approval/sign concurrency. 

Please also consider requesting CSR in foreground. 
1. Otherwise the node registering could be more than 10s. It totally depends on when kubelet initiate the first request.
2. When kubelet enable  bootstrap  and disable rotate-certificates, it requesting CSR in foreground https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/server.go#L889

**Comment by enj** [comment]
/remove-lifecycle stale

> Concurrency 5 seems to be hardcoded above. @liggitt do you agree that a flag should be added to tuning it?

I disagree with adding flags for niche cases.  If we get significant evidence that `5` is not enough, we can change all of the `5`s to `15`.  For now I believe the change in #114367 is sufficient.
