### ISSUE TITLE
mark RootCAConfigMap kube-root-ca.crt immutable

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kubernetes#112147]
### What would you like to be added?

Allow marking the RootCAConfigMap (kube-root-ca.crt) configmap added to every namesace as immutable to reduce required kubelet watches on a relatively static resource.
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

### Why is this needed?

The RootCAConfigMap added to every namespace and mounted into every pod with service account token mounted can cause significant amount of watches in large clusters. E.g. if you have a logging daemonset with api access running on each node or multi tenant namespace separated ingress controllers with many pods each of them will cause a watch of the kubelet on the kube-root-ca.crt configmap added to every namespace.

As the root ca is in most cases relatively long lived it may make sense to mark it as immutable to avoid the watch of the kubelet on it:
https://kubernetes.io/docs/concepts/configuration/configmap/#configmap-immutable

**Comment by liggitt** [comment]
The CA bundle is not actually immutable, so marking it as such would not permit rollouts that update the bundle, right?

**Comment by juliantaylor** [comment]
As I understand it, It would not prevent rollouts it would just change the way an update is rolled out. Instead of updating the configmap, letting the kubelet change the volume mounts and the application seeing the change and reloading. it would be you delete and recreate the configmap and restart all pods using it.

Restarting pods for such a fundamental change is probably the safer way as you may not know if the application are even capable of reloading the certificate without a restart.

For our clusters this configmap is mounted into thousands of pods and thus the kubelet has thousands of watches on this resource which in our cluster does not change more often than every 6 month.
Having the option to avoid the watches in exchange for a different rollout procedure would be worthwhile.

**Comment by liggitt** [comment]
since the configmap is not actually immutable, it doesn't seem correct to mark it that way and put pods/kubelets in a state that would not respect a rollout of an update to it

**Comment by juliantaylor** [comment]
Which configmap is truely immutable?
I think it is pretty likely in a significant fraction of clusters the root ca is one of the most immutable configmaps in the whole cluster.

I'm not asking to always mark it immutable, only optionally allow marking it as immutable if you know what you are doing and want to avoid the overhead of thousands of watches on a resource that will change very very rarely compared to everything else.

**Comment by juliantaylor** [comment]
Note that the kubelet starts a watch per namespace on the rootca configmap. Maybe that is a better angle is to have the kubelet only have one global watch so you have one per node instead of one per node per namespace.

**Comment by enj** [comment]
Perhaps https://github.com/kubernetes/enhancements/issues/3257 would solve this problem altogether by making it so that there is only a single watch per kubelet for all CAs (including the trust anchor that contains the contents of `kube-root-ca.crt`).  We may be able to do this transparently.
