### ISSUE TITLE
Huge amount of logs: kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/86cba354-348c-4826-9837-df9c616a8862/volumes"

### ISSUE THREAD

**Issue by danielcb** [kubernetes/kubernetes#112124]
### What happened?

After we updated two of our clusters from 1.22 to v1.24.4 we noticed a huge amount of logs (tens of entries per second) in kubelet:

```
kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/86cba354-348c-4826-9837-df9c616a8862/volumes"
```

Neither does the `volumes` subdir exist, nor the corresponding subdir for the pod (`"/var/lib/kubelet/pods/86cba354-348c-4826-9837-df9c616a8862` in this case).

Kubelet currently produces multiple gigabytes of logs each day since the upgrade.

### What did you expect to happen?

No log spam (at least not with verbosity=0).

### How can we reproduce it (as minimally and precisely as possible)?

Not really sure. We changed nothing in the setup. We just upgraded to v1.24.4. The cluster does not have any volume providers running. Just a 'vanilla' kubernetes (ubuntu 20.04, kubeadm, cillium, cri-o). 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>

```console

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux k8s-master-p-1 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O

Version:          1.24.2
GitCommit:        bd548b04f78a30e1e9d7c17162714edd50edd6ca
GitTreeState:     clean
BuildDate:        2022-08-09T16:42:39Z
GoVersion:        go1.18.2
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp
SeccompEnabled:   true
AppArmorEnabled:  true
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cilium v1.12.0
</details>

**Comment by lfe135** [comment]
https://github.com/kubernetes/kubernetes/blob/5debf63a742fab8f3d9b3672a1fd3f14d2289dce/pkg/kubelet/kubelet_pods.go#L1180 cleanupOrphanedPodDirs clean up volume dir. 
https://github.com/kubernetes/kubernetes/blob/5debf63a742fab8f3d9b3672a1fd3f14d2289dce/pkg/kubelet/kubelet_pods.go#L1198 cleanupOrphanedPodCgroups check that the directory exists.
Maybe need some clean up.

**Comment by danielcb** [comment]
https://github.com/okd-project/okd/issues/1310

**Comment by danielcb** [comment]
Looks like it's a problem with runc <= 1.3

After upgrading runc everyhting works again.

**Comment by pacoxu** [comment]
> Looks like it's a problem with runc <= 1.3

Do you mean contained v1.3 here? runc's latest version is v1.1.4 now https://github.com/opencontainers/runc/releases.

**Comment by pacoxu** [comment]
Refer to https://github.com/containerd/containerd/blob/main/RELEASES.md#kubernetes-support
For v1.24, suggested containerd versions are **1.6.4+, 1.5.11+**.

**Comment by danielcb** [comment]
Sorry, Typo. runc 1.1.3.

**Comment by danielcb** [comment]
After upgrading runc to 1.1.4 the memory leaks disappeared and the amount of loglines went down from ~ 100/s to ~1/s, but it still generates _a lot_ of useless logs.

**Comment by rphillips** [comment]
cc @kolyshkin

**Comment by kolyshkin** [comment]
Sorry, I can't see how it relates to runc in any way possible.

> the memory leak and cgroup error messages 

@danielcb I am not sure what you mean here, the issue description does not mention any memory leak or cgroup error messages, only the "Path does not exist" error from `kubelet_getters.go:300`.

**Comment by danielcb** [comment]
Sorry for mixing multiple issues. We've run into this, I think:
https://github.com/okd-project/okd/issues/1310

Currently we're on v1.24.4 with runc 1.1.4 and still have multiple issues:

1. Huge amount of log lines (10s per second):
```
Sep 13 10:17:18 kubelet[3612579]: I0913 10:17:18.591831 3612579 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/b3f6cbb9-2fd8-4ec9-a42a-91218e950eeb/volumes"
```
and
```
Sep 13 10:18:22 kubelet[3612579]: I0913 10:18:22.474677 3612579 pod_container_manager_linux.go:192] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort podce1a8814-a9dd-46cd-ba07-84b0550b22a0] err="unable to destroy cgroup paths for cgroup [kubepods besteffort podce1a8814-a9dd-46cd-ba07-84b0550b22a0] : Timed out while waiting for systemd to remove kubepods-besteffort-podce1a8814_a9dd_46cd_ba07_84b0550b22a0.slice"
```

2. kubelet consuming all available memory (around 60G) until it crashes

**Comment by kolyshkin** [comment]
> Sep 13 10:18:22 kubelet[3612579]: I0913 10:18:22.474677 3612579 pod_container_manager_linux.go:192] "Failed to delete cgroup paths" cgroupName=[kubepods besteffort podce1a8814-a9dd-46cd-ba07-84b0550b22a0] err="unable to destroy cgroup paths for cgroup [kubepods besteffort podce1a8814-a9dd-46cd-ba07-84b0550b22a0] : Timed out while waiting for systemd to remove kubepods-besteffort-podce1a8814_a9dd_46cd_ba07_84b0550b22a0.slice"

Ah, OK, this might be related to runc, since the error comes from runc code. Having said that, I am not aware of any bugs in runc 1.1.4 that can result in this error.

Now, what runc does is it sends the `StopUnit` command to systemd (this is the same thing that happens when you issue `systemctl stop $UNIT`) and waits for up to 30 seconds for systemd to respond. Generally, 30s it is enough for systemd to remove the unit (or report an error), but it does not happen in this case and so the timeout is hit.

What this means, practically, is systemd is currently having some major issues and is not very responsive. I would start to debug this particular issue by reproducing it and when looking into system logs (journalctl) to see what's going on. Checking how systemd copes in would make sense, too.

Hope that's useful.

**Comment by danielcb** [comment]
Definitely helpful, thanks! Now I need to figure out whats causing the memory consumption and hanging system.

**Comment by SergeyKanzhelev** [comment]
> 2\. kubelet consuming all available memory (around 60G) until it crashes

Apart the underlying problem, I want to understand if kubelet can be improved to handle this error. @danielcb you said kubelet consumes all memory and crashes. Do you mean kubelet as a process, or just the log file?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

Moving to needs information for now to get the full scope of the issue, but it feels like there is an error in kubelet with the log verbosity at least.

**Comment by DavidHaltinner** [comment]
> > 2. kubelet consuming all available memory (around 60G) until it crashes
> 
> Apart the underlying problem, I want to understand if kubelet can be improved to handle this error. @danielcb you said kubelet consumes all memory and crashes. Do you mean kubelet as a process, or just the log file?

I am not the reporter of the issue, but someone having the same. In my case it is kubelet itself consuming the memory. I have four nodes, out of three clusters, going into the downward spiral as we speak. in each case it is the kubelet process that takes the memory until the OOM reaper kicks in. I have added a script to drain and reboot the node when it reaches 3 GB free just to make things gentler.
in each case the kubelet process seems to log exponentially, so over time it becomes more severe, doubling over time, and exhausting the journal. However, kubelet is also taking all of the available memory that the server has until it reaches OOM.
restarting the kubelet itself only acts as a short bandaid, it helps memory usage, but not cpu usage, and the the issue comes back in fairly short order (as well as side effects along the way). but a full shut down, clearing everything out that it is complaining about, will last for awhile longer (i get about 3 days from a control pane node. a week or so from a worker node).\

I have been trying to experiment on a 32gb worker node i have in its death throes right now (no actual workloads have been on it beyond the builtins, and its gone from 3GB to 24 GB usage on kubelet process itself in around 4 hours right now), but i can find no fault in systemd itself. it responds as snappy as always, journal is quite besides the kubelet errors reported above, and the scopes that kubelet says timed out, did actually get removed, so kubelet both tries to keep removing them via systemd (when they are already gone, but also still says they time out), then also saying that the volumes dont exist (because they dont, they did get removed), and as i mentioned, it seems to get to a point where it almost appears exponential, and the node OOMs.

so i can find no evidence of an actual timeout by systemd right now. however, despite the scopes actually being removed, kubelet refuses to believe they are gone, and keeps trying to remove them, complaining in both a timeout of systemd as well as the volume not existing, and that appears to grow exponetially until the node OOMs.

as i said i have 3 clusters exhibiting these same symptoms and log messages, and lose nodes frequently, so i can gather any specific information rather easily. unfortunatly the journal has nothing of interest beyond what @danielcb said, both the volume not found (because it is gone), and the systemd timeout removing the cgroup (which it did successfully remove the first time)
I specifically am running OKD 4.11, which appears to be runc 1.1.3 right now, and k8s 1.24.0

**Comment by danielcb** [comment]
Can confirm everything @DavidHaltinner said. We have currently 3 clusters with this problem. All started with the upgrade to 1.24.* and all of them are running runc (1.1.4). Another cluster with the same setup and k8s version does not show this problem and uses crun.

**Comment by SergeyKanzhelev** [comment]
/cc @rphillips 

Can you please take a look?

**Comment by rphillips** [comment]
I opened a PR to fix the reported issue of log spam. https://github.com/kubernetes/kubernetes/pull/112650

**Comment by AndrewSav** [comment]
Will <https://github.com/kubernetes/kubernetes/pull/112650> fix the OOM issue that we are seeing?

**Comment by SergeyKanzhelev** [comment]
> Will #112650 fix the OOM issue that we are seeing?

likely not

/reopen

**Comment by SergeyKanzhelev** [comment]
@danielcb one piece of information we are looking for is whether the same ID will keep showing up for hours. It is not clear whether this is recoverable and expected race that we just need to hide or this is an unrecoverable problem.

OOM reports makes think that it might be unrecoverable, but it is hard to imagine what will take that much memory on this clean up even if it stuck in this state and not recoverable.

**Comment by AndrewSav** [comment]
```
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | (head -n1 && tail -n1)
-- Logs begin at Wed 2022-10-12 04:01:45 UTC, end at Wed 2022-10-12 20:21:07 UTC. --
Oct 12 20:21:43 p-k8s-worker-05 kubelet[918]: I1012 20:21:43.404450     918 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/9cef28b0-6c59-44d0-b3a0-28841f613870/volumes"
```
This is an about 16 hours log

```
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | wc -l
4207125
```

It contains more than 4 million records

```
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | grep 1b043602-d7d9-470c-a043-704d32d19c36 | wc -l
2068
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | grep 1b043602-d7d9-470c-a043-704d32d19c36 | (head -n1 && tail -n1)
Oct 12 04:01:45 p-k8s-worker-05 kubelet[1054]: I1012 04:01:45.435753    1054 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/1b043602-d7d9-470c-a043-704d32d19c36/volumes"
Oct 12 05:10:39 p-k8s-worker-05 kubelet[1054]: I1012 05:10:39.647785    1054 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/1b043602-d7d9-470c-a043-704d32d19c36/volumes"
```
Some "path does not exist" pods disappear eventually

```
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | grep 9cef28b0-6c59-44d0-b3a0-28841f613870 | (head -n1 && tail -n1)
Oct 12 07:15:00 p-k8s-worker-05 kubelet[918]: I1012 07:15:00.288592     918 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-nxh8w\" (UniqueName: \"kubernetes.io/projected/9cef28b0-6c59-44d0-b3a0-28841f613870-kube-api-access-nxh8w\") pod \"sphinx-scheduler-27759315-qt6pq\" (UID: \"9cef28b0-6c59-44d0-b3a0-28841f613870\") " pod="production-listing-search/sphinx-scheduler-27759315-qt6pq"
Oct 12 20:21:43 p-k8s-worker-05 kubelet[918]: I1012 20:21:43.404450     918 kubelet_getters.go:300] "Path does not exist" path="/var/lib/kubelet/pods/9cef28b0-6c59-44d0-b3a0-28841f613870/volumes"
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | grep 9cef28b0-6c59-44d0-b3a0-28841f613870 | wc -l
22674
asavinykh@p-k8s-worker-05:~$ zcat kubelet-2022-10-13.log.gz | grep 9cef28b0-6c59-44d0-b3a0-28841f613870 | grep "Path does not exist" | wc -l
22661
```

Others may hang around for hours

**Comment by camaeel** [comment]
We are running k8s 1.24.9 with cri-o 1.24.4 and runc 1.0.1 and 1.1.4 on ubuntu 20.04 with cgroups v1 in use and experinece this issue. Apart from high amount of such messages we also experienced high CPU & memory consumption. 

I created some simple deployment with 20 nginx pods which I rotated very often (every 10 secs) to create a lot of garbage in cgroups. 

Kubelet's CPU usage:
![Screenshot 2023-01-24 at 15 03 29](https://user-images.githubusercontent.com/12999736/214315127-25752972-6368-41c6-8979-71f39090bf13.png)

Kubelet's memory usage:
![Screenshot 2023-01-24 at 15 03 22](https://user-images.githubusercontent.com/12999736/214315146-93e56879-d537-447e-9fce-706f64f1694c.png)

This was fixed by switching to ubuntu 22.04 which enables cgroups v2 by default.

**Comment by AndrewSav** [comment]
I also saw the issue disappear after switching to ubuntu 22, however I used Kubernetes 1.25 on ubuntu 22, whereas I had the problem with 1.24 on ubuntu 20.

**Comment by camaeel** [comment]
@AndrewSav this was because you switched from cgroups v1 (ubuntu 20 default) to v2 ( Ubuntu 22 default).

**Comment by AndrewSav** [comment]
Obviously ;)

**Comment by elbie2** [comment]
> In my case the same ids kept showing up for hours. This was due to the misc cgroup not being properly cleaned up. And because not everything was cleaned up the pods kept getting picked up by the housekeeping loop.
> 
> On the first run the directory is removed. all consecutive runs this log is produced.
> 
> So while this log isn't the problem it is (the only) indication that the kubelet fails to completely delete pods from the system.

The misc controller was introduced in 5.13, my guess is that there's a discrepancy between some code that creates the cgroups (handles misc)  and some code that cleans up the cgroups (doesn't handle misc) , causing the misc cgroups to be left behind.

**Comment by thtanaka** [comment]
In the case of linux kernel 5.15.x and using cgroups v1 and 1.25.x kubernetes, it seems like the runc `Destroy()`(`vendor/github.com/opencontainers//runc/libcontainer/cgroups/systemd/v1.go`) doesn't include the removal of "misc" cgroups and upon checking of the code it seems like "misc" cgroups implementation seems to be missing, is there any reason for this or perhaps someone who has more knowledge could point me in the correct direction ?

As the result of this (leftover of misc cgroups dir in `/sys/fs/cgroup/misc/kubepods.slice/kubepods-besteffort.slice/`), `GetAllPodsFromCgroups` (`pkg/kubelet/cm/pod_container_manager_linux.go`) will always include it in the `foundPods`, thus the spam of "Path does not exist path=..." errors.

Btw, if anyone is interested to give it a try, by disabling "misc" cgroups it seems like we can get rid of this spam of "Path does not exist path=..." messages.

**Comment by hajdukda** [comment]
Hi,

We are observing the same issue on Bottlerocket official AMI images. Suddenly a node during the night gets flooded with those errors and fills up the disk.

Does anyone run Bottlerocket OS ?

**Comment by dims** [comment]
@hajdukda looks like you found the correct bottle rocket issue. leaving the link here for others who may run into it.

https://github.com/bottlerocket-os/bottlerocket/issues/3057

**Comment by BBQigniter** [comment]
I stumbled upon this issue, as we have the same problem on all our Rancher RKE (k8s v1.24 and v1.25) clusters where the `kubelet` container is spamming `"Path does not exist"` messages - this resulted in gigabytes of logs from one of our clusters which is running dozens of kubernetes-jobs on ~3 nodes.

For a quick and ugly fix I created the script below that periodically cleans the corresponding `/sys/fs/cgroup/misc`-folders via a simple cronjob (`* * * * * root /opt/scripts/cgroup_pod_garbage_collector.sh -i 50s >/dev/null 2>&1`) - not sure if it's super smart what I'm doing and the script can surely be done in a much better way, but we needed a quick fix, the `kubelet` containers on the nodes caused extremely high CPU-usage writing those logs and our ELK also complained about space-usage ;)

```bash
#!/bin/bash

##################################################### ARGUMENTS - BEGIN
usage() {
   echo "Script for cleaning up cgroup garbage of pods that got deleted" 1>&2
   echo " " 1>&2
   echo "Usage: $0 [-i <interval>]    example: set to cronjob-interval but slightly lower to not get overlaps for example" 1>&2
   echo "                                                                   if it runs every 5 minutes, set 290s" 1>&2
   exit 1
}

while getopts ":i:" o; do
    case "${o}" in
        i)
            RUN_INTERVAL=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${RUN_INTERVAL}" ]; then
    usage
fi
##################################################### ARGUMENTS - END

##################################################### CHECK IF ALREADY RUNNING - BEGIN
# From https://gist.github.com/beugley/43f3feb8c532f7cc07cbcb3ea3ccd203 - slightly adapted
#
# To prevent multiple instances of a script from executing concurrently,
# include this function, and a statement to invoke it, at the top of any
# ksh/bash script.  This function will check for other instances of the
# same script that are executing by the same user.  If any are found, then
# this instance terminates immediately.
#
# When scripts are invoked in a repetitive manner (cron or other scheduler),
# it's possible that an instance can still be running when the time arrives
# to start a new instance.  For example, suppose that you schedule a script
# to run every 15 minutes, but one run takes 20 minutes?  You may not want
# 2 (or more) concurrent instances of the script to run.
#
terminateIfAlreadyRunning() {
    ##
    ## Terminate if another instance of this script is already running.
    ##
    SCRIPT_NAME=`/bin/basename $1`
    echo "`/bin/date +%Y%m%d.%H%M%S:` This instance of $SCRIPT_NAME is PID $$"
    for PID in `/bin/ps -fC $SCRIPT_NAME | /bin/grep "^$USER" | /usr/bin/awk '{print $2}'`; do
        ALIVE=`/bin/ps -p $PID -o pid=`
        if [[ "$PID" != "$$"  &&  "$ALIVE" != "" ]]
        then
                echo "WARNING: $SCRIPT_NAME is already running as process $PID!"
                echo "Terminating..."
                exit 0
        fi
    done
}

terminateIfAlreadyRunning $0
##################################################### CHECK IF ALREADY RUNNING - END

##################################################### FUNCTIONS - BEGIN
# blatantly stolen from https://www.urbanautomaton.com/blog/2014/09/09/redirecting-bash-script-output-to-syslog/
# for nicely logging to console and /var/log/messages
readonly SCRIPT_NAME=$(basename $0)

log_info() {
  echo "$@"
  logger -p local0.info -t $SCRIPT_NAME "$@"
}

log_warn() {
  echo "$@"
  logger -p local0.warning -t $SCRIPT_NAME "$@"
}

log_err() {
  echo "$@" >&2
  logger -p local0.err -t $SCRIPT_NAME "$@"
}

# testing
#log_info "writing to stdout"
#log_err "writing to stderr"
##################################################### FUNCTIONS - END

##################################################### MAIN-SCRIPT - BEGIN
# we get the "IDs" of the pods
KUBE_POD_IDS=$(docker logs kubelet --since ${RUN_INTERVAL} 2>&1 | grep "Path does not exist" | awk '{ print $9 }' | awk -F "/" '{print $6}' | sort | uniq)

for POD_ID in $KUBE_POD_IDS; do
    # we search for the folder below sys - as observed it either can be in .../besteffort/... or .../burstable/...
    # the resulting path should look something like "/sys/fs/cgroup/misc/kubepods/besteffort/pod${POD_ID}"
    # TODO: can there be multiple paths? we may have to handle that!
    CGROUP_DIR_NAME=$(find /sys -name "*${POD_ID}")
    # was something found?
    if [ -z "$CGROUP_DIR_NAME" ]; then
        log_warn "nothing found in /sys for ${POD_ID}!"
    else
        if [ -d "${CGROUP_DIR_NAME}" ]; then
            # "rm -rf" not working with cgroup's pseudo-filesystem
            if rmdir "${CGROUP_DIR_NAME}"; then
                log_info "successfully deleted ${CGROUP_DIR_NAME}"
            else
                log_err "could not delete ${CGROUP_DIR_NAME}!"
            fi
        else
            log_warn "already removed ${CGROUP_DIR_NAME} earlier!"
        fi
    fi
done
##################################################### MAIN-SCRIPT - END
```

I haven't seen any issues yet on the clusters where this script is active and docker logs for the `kubelet` container also look much much cleaner. Log-space in our ELK was reduced from for example ~15G per hour from one of the nodes to ~3G per hour. CPU usage also dropped significantly from 20% to 4% after executing the script manually on one of the nodes.
