### ISSUE TITLE
Document and test minimum privileges to needed run kube-proxy

### ISSUE THREAD

**Issue by ialidzhikov** [kubernetes/kubernetes#112171]
### What happened?

Running containers in privileged mode is not recommended as privileged containers run with all [linux capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html) enabled and can access the host's resources. Running containers in privileged mode opens number of security threads such as breakout to underlying host OS.

Currently the kube-proxy DaemonSet runs in privileged mode.

https://github.com/kubernetes/kubernetes/blob/863a462eeccca4c24bf4c4e9012f5ebccade70a2/cluster/addons/kube-proxy/kube-proxy-ds.yaml#L50-L51

https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/#configuring-kube-proxy describes how to run kube-proxy in "rootless". To my understanding "rootless" != non-privileged mode but this configuration can be also used for running in non-privileged mode. However I see that following issues with it:
1. In the provided kube-proxy component config in https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/#configuring-kube-proxy we have to disable certain settins to prevent kube-proxy from ensuring sysctls (which is allowed only in privileged container).

But when I tried to run kube-proxy with the provided component config it fails because it tries to ensure yet another syctl:
```
F0818 08:03:55.514875       1 server.go:494] unable to create proxier: unable to create ipv4 proxier: can't set sysctl net/ipv4/conf/all/route_localnet to 1: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system
```

It is `net/ipv4/conf/all/route_localnet` that is being set in https://github.com/kubernetes/kubernetes/blob/58c10aa6eb5adfb1f3aa4d6cb898b8c347ba9e72/pkg/proxy/iptables/proxier.go#L263-L265

And I don't see a way how to disable kube-proxy from ensuring this sysctl from its component config.

2. In general the whole approach that explicitly sets 0 values to prevent kube-proxy from ensuring syctls seems not a sustainable one. The long lived kube-proxy container should be able to run in non-privileged mode. If it needs sysctls to be ensured, this can to be done in a privileged init container.

### What did you expect to happen?

I would expect to be able to run kube-proxy in non-privileged mode in a clear and sustainable way.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

v1.24.3

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ialidzhikov** [comment]
/sig network
/sig security

Ref to a thread where we were discussing kube-proxy in non-privileged mode - https://kubernetes.slack.com/archives/C09QYUH5W/p1659601425035639 (cc @aojea)

**Comment by uablrek** [comment]
Have you tried proxy-mode=ipvs? It does not set `net/ipv4/conf/all/route_localnet` but there may be other, ipvs related sysctls.

`net/ipv4/conf/all/route_localnet` is to allow nodePorts on localhost which is discussed in https://github.com/kubernetes/kubernetes/issues/111840. It should besically be removed from kube-proxy.

**Comment by thockin** [comment]
Aside from route_localnet, there are other things that kube-proxy tries to configure.  It's a very low-level agent, and simply disabling those things may not really be viable - they are being set for a reason.

I'm all ion favor of dropping privilege, if we can, but I am not so confident we can...

https://github.com/kubernetes/kubernetes/pull/108250 proposes a control which should help wrt route_localnet.

**Comment by aojea** [comment]
>  Currently the kube-proxy DaemonSet runs in privileged mode.
> 
> [kubernetes/cluster/addons/kube-proxy/kube-proxy-ds.yaml](https://github.com/kubernetes/kubernetes/blob/863a462eeccca4c24bf4c4e9012f5ebccade70a2/cluster/addons/kube-proxy/kube-proxy-ds.yaml#L50-L51)
> 
> Lines 50 to 51 in [863a462](https://github.com/kubernetes/kubernetes/commit/863a462eeccca4c24bf4c4e9012f5ebccade70a2)
> 
>  securityContext: 
>    privileged: true


that is a internal detail of kubernetes CI, those configuration should not be exposed and are not representative


> Aside from route_localnet, there are other things that kube-proxy tries to configure. It's a very low-level agent,

those are explained in the linked article https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/#configuring-kube-proxy
```
Configuring kube-proxy 
Running kube-proxy in a user namespace requires the following configuration:

apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "iptables" # or "userspace"
conntrack:
# Skip setting sysctl value "net.netfilter.nf_conntrack_max"
  maxPerCore: 0
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_established"
  tcpEstablishedTimeout: 0s
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_close"
  tcpCloseWaitTimeout: 0s
```

> But when I tried to run kube-proxy with the provided component config it fails because it tries to ensure yet another syctl:

you can disable that sysctl using the flag `--nodeport-addresses`
https://github.com/kubernetes/kubernetes/pull/107684

You should pass the network cidrs with your node addresses, without containing any loopback address. 

Something that will work for most people is to use always the private networks ranges:
`--nodeport-address 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0\16`

@thockin maybe we can default that flag to all private IP ranges?, we solve the LB with public IPs problem too

**Comment by khenidak** [comment]
I think at minimum we should be able to run it with CAP_NET_ADMIN not CAP_SYS_ADMIN. That at least limits the blast radius while we consider all options provided here: https://github.com/kubernetes/kubernetes/issues/112171#issuecomment-1234778318


/assign

**Comment by ialidzhikov** [comment]
> that is a internal detail of kubernetes CI, those configuration should not be exposed and are not representative

Okay, maybe I referenced the wrong chart. Where is the referenced/exposed kube-proxy chart? Is there something like this? I assume that kube-proxy runs in privileged mode there as well.

---

> > Aside from route_localnet, there are other things that kube-proxy tries to configure. It's a very low-level agent,
> 
> those are explained in the linked article https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/#configuring-kube-proxy
> 
> ```
> Configuring kube-proxy 
> Running kube-proxy in a user namespace requires the following configuration:
> 
> apiVersion: kubeproxy.config.k8s.io/v1alpha1
> kind: KubeProxyConfiguration
> mode: "iptables" # or "userspace"
> conntrack:
> # Skip setting sysctl value "net.netfilter.nf_conntrack_max"
>   maxPerCore: 0
> # Skip setting "net.netfilter.nf_conntrack_tcp_timeout_established"
>   tcpEstablishedTimeout: 0s
> # Skip setting "net.netfilter.nf_conntrack_tcp_timeout_close"
>   tcpCloseWaitTimeout: 0s
> ```
> 
> > But when I tried to run kube-proxy with the provided component config it fails because it tries to ensure yet another syctl:
> 
> you can disable that sysctl using the flag `--nodeport-addresses` #107684
> 
> You should pass the network cidrs with your node addresses, without containing any loopback address.
> 
> Something that will work for most people is to use always the private networks ranges: `--nodeport-address 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16`
> 
> @thockin maybe we can default that flag to all private IP ranges?, we solve the LB with public IPs problem too

Okay but the whole approach by disabling is a hack/workaround. In https://github.com/kubernetes/kubernetes/issues/112171#issue-1358314085 I wrote:

> In general the whole approach that explicitly sets 0 values to prevent kube-proxy from ensuring syctls seems not a sustainable one. The long lived kube-proxy container should be able to run in non-privileged mode. If it needs sysctls to be ensured, this can to be done in a privileged init container.

The long-lived container should not deal with sysctls. For example they can be moved to a privileged init container.

For example in Gardener we run kube-proxy with:
```yaml
    conntrack:
      maxPerCore: 524288
```

How we are supposed to run kube-proxy in privileged mode with this setting preserved?

---

> I think at minimum we should be able to run it with CAP_NET_ADMIN not CAP_SYS_ADMIN.

@khenidak According to my testing kube-proxy was running fine with `NET_ADMIN` and `SYS_RESOURCE` (except the sysctls).

**Comment by aojea** [comment]
> Where is the public/exposed kube-proxy chart?

there is no such thing, each installer/project:kubeadm, kops, openshift, ... pick their choices and way of deploying it.

> The long-lived container should not deal with sysctls. For example they can be moved to a privileged init container.

I see your point now. kube-proxy is released as a single binary, you can't assume kube-proxy is containerized, despite most people use it that way. I don't know if you can remove these sysctls without making breaking changes.

Also, kube-proxy is one particular implementation of Services, but there can be others, you don't have to use kube-proxy, some people is working on a evolution on [kpng project](https://github.com/kubernetes-sigs/kpng) , they should have this feedback to not carry over this past mistakes

**Comment by aojea** [comment]
/unassign
/priority long-term

People is welcome to work on this and try to reduce the privilege scope of kube-proxy

**Comment by uablrek** [comment]
I'll give it a shot. My idea is:

1. Make sure that kube-proxy doesn't set anything if the value is already the desired one. This may already be in place
2. Add a `-init-only` CLI option to kube-proxy (not included in the config obviously) that *only* sets sysctl's etc.

Then any system that starts `kube-proxy`, in whatever way, can _optionally_ do that in two steps, `-init-only` that needs "privileged" and then run kube-proxy non-privileged.

/assign
