### ISSUE TITLE
kubelet http api /pods returned data not consistent with data from etcd

### ISSUE THREAD

**Issue by xuchen-xiaoying** [kubernetes/kubernetes#112119]
### What happened?

when kubelet restarts, if access /pods api before podStorage's apiserverSource gets ready, the pod list returned is not full，pods from apiserver source are not shown in result. 

the code https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/server/server.go#L721 returns pods from podManager regardless of sourcesReady condition
![image](https://user-images.githubusercontent.com/94154028/187384568-d2b512a0-4758-46a0-bd80-69d4ada0f245.png)

### What did you expect to happen?

return err code before all sources become ready to guarantee /pods api's data consistence.

### How can we reproduce it (as minimally and precisely as possible)?

restart kubelet, access /pods api multi times. if the request is served before apiserver source gets ready, the data returned is not full.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.24

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/assign @fromanirh 

interesting what kind of consistency we can provide for freshly removed or newly scheduled pods as well.

/triage accepted

to take a look at what can be improved

**Comment by xuchen-xiaoying** [comment]
> /assign @fromanirh
> 
> interesting what kind of consistency we can provide for freshly removed or newly scheduled pods as well.

I think if the request is served from kubelet itself instead of proxying to apiserver, It has unavoidable latency  compared with pods in etcd. 

However, at least could we guarantee the consistence with existing containers from runtime?

@fromanirh look forward to your advice.

**Comment by jlsong01** [comment]
> "pod list returned is not full"
Did the returned pod list contain kubelet static pods only? or any other pod additionally?

**Comment by xuchen-xiaoying** [comment]
> > "pod list returned is not full"
> 
> Did the returned pod list contain kubelet static pods only? or any other pod additionally?

![image](https://user-images.githubusercontent.com/94154028/191938248-38c0a446-df20-419a-b355-56c6b927cf3a.png)

s.host.GetPods() get pod from podManager.

If kubelet restarts, it would admit existed pods one after one again. Only ff a pod is admitted successfully, it will be inserted into podmanager. So the pods existed but haven't been admitted yet will not show in the returned pod list.

**Comment by fromanirh** [comment]
I need to form my thoughs properly here and review the API documentation, but if memory serves the `/pods` endpoint should report all the pods reported by ready sources _at any given time_. IOW, repeated queries to the endpoint should eventually return the full pod set.
The consistency aspect here is indeed interesting. I'll update ASAP.

**Comment by xuchen-xiaoying** [comment]
> I need to form my thoughs properly here and review the API documentation, but if memory serves the `/pods` endpoint should report all the pods reported by ready sources _at any given time_. IOW, repeated queries to the endpoint should eventually return the full pod set. The consistency aspect here is indeed interesting. I'll update ASAP.

@fromanirh hi, do you any update on this topic?

**Comment by fromanirh** [comment]
I'm investigating the API support level and thus guarantees of this endpoint.
There's no obvious documentation for the endpoint (please correct me if I missed something huge). The google search points to unofficial docs, which themselves warn the reader that the informations are gathered reviewing the code (https://www.deepnetwork.com/blog/2020/01/13/kubelet-api.html)

```
If you further [dig into the code](https://github.com/kubernetes/kubernetes/blob/bd239d42e463bff7694c30c994abd54e4db78700/pkg/kubelet/server/server.go#L284), you can see that there are some more endpoints:

    /pods
```

Digging into git history, further suggests that these endpoints were introduced historically and never removed - but also never promoted to a supported API either. I want to highlight a couple of interesting commits:
- https://github.com/kubernetes/kubernetes/commit/de75a42cb23ad986765924ea166da386f6d2d5d3 suggests that already in mid-2015 (!!!) these endpoints were to be considered for internal/debug purposes - not something could be build upon
- https://github.com/kubernetes/kubernetes/commit/928f52056e4ce01833980297efe87f768d422912 suggests that in the end-2014 the kubelet endpoints (including /pods) were already being deprecated in favor of what it seems the current approach

So the picture so far seems to suggest this endpoint is best-effort in the best scenario, and most likely should not be used at all.

I'll ask longer-serving contributors to doublecheck the above and add comments here.

**Comment by xuchen-xiaoying** [comment]
> I'm investigating the API support level and thus guarantees of this endpoint. There's no obvious documentation for the endpoint (please correct me if I missed something huge). The google search points to unofficial docs, which themselves warn the reader that the informations are gathered reviewing the code (https://www.deepnetwork.com/blog/2020/01/13/kubelet-api.html)
> 
> ```
> If you further [dig into the code](https://github.com/kubernetes/kubernetes/blob/bd239d42e463bff7694c30c994abd54e4db78700/pkg/kubelet/server/server.go#L284), you can see that there are some more endpoints:
> 
>     /pods
> ```
> 
> Digging into git history, further suggests that these endpoints were introduced historically and never removed - but also never promoted to a supported API either. I want to highlight a couple of interesting commits:
> 
> * [de75a42](https://github.com/kubernetes/kubernetes/commit/de75a42cb23ad986765924ea166da386f6d2d5d3) suggests that already in mid-2015 (!!!) these endpoints were to be considered for internal/debug purposes - not something could be build upon
> * [928f520](https://github.com/kubernetes/kubernetes/commit/928f52056e4ce01833980297efe87f768d422912) suggests that in the end-2014 the kubelet endpoints (including /pods) were already being deprecated in favor of what it seems the current approach
> 
> So the picture so far seems to suggest this endpoint is best-effort in the best scenario, and most likely should not be used at all.
> 
> I'll ask longer-serving contributors to doublecheck the above and add comments here.

much thanks for your investigate and reply. I got your point. Pls ping me if any further update. Thanks.

**Comment by xuchen-xiaoying** [comment]
@ffromani hi, any update?

**Comment by ffromani** [comment]
update: some time ago we discussed in the sig-node meeting (https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#bookmark=id.u2d5xv86jzks). The kubelet API are not part of the standard API and meant for internal use. Thus can change anytime and are not bound by any compatibility guarantees. I'm afraid we can't fix this issue.

**Comment by ffromani** [comment]
/close

see: https://github.com/kubernetes/kubernetes/issues/112119#issuecomment-1653871204

please reopen if new evidence comes, but from the project perspective this endpoint is considered internal, thus inconsistencies with supported APIs are generally not bugs.
