### ISSUE TITLE
Pod Deployment going to pending state when there are multiple profiles 

### ISSUE THREAD

**Issue by santkuma77** [kubernetes/kubernetes#112180]
Hi,

My pod deployments are going to pending state when I have multiple profiles(default and custom). Also it's in pending state forever. I don't see any events or logs for this.

I have copied the yaml files below. Please help me with the following:

Why there no logs when there is pending issue?
Why there are no events logged?
Is there anything wrong with my yaml files?

===================
My Pod deployment yaml file:

File Name: nginx_deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
      schedulerName: no-volumebind-volumezone-scheduler
===================

===================
My scheduler file:

File Name and Location: /etc/kubernetes/sched-novolumeplugins.yaml:

apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
leaderElection:
  # (Optional) Change true to false if you are not running a HA control-plane.
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
  - schedulerName: default-scheduler
  - schedulerName: no-volumebind-volumezone-scheduler
    plugins:
      filter:
        disabled:
        - name: VolumeZone
        - name: VolumeBinding
      preFilter:
        disabled:
        - name: VolumeBinding
      reserve:
        disabled:
        - name: VolumeBinding
      preBind:
        disabled:
        - name: VolumeBinding
      score:
        disabled:
        - name: VolumeBinding
===================

===================
Kube-scheduler file:

File Location:  /etc/kubernetes/manifests/kube-scheduler.yaml

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=0.0.0.0
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=false
    - --config=/etc/kubernetes/sched-novolumeplugins.yaml
    - --v=9
    image: k8s.gcr.io/kube-scheduler:v1.23.6
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
   - mountPath: /etc/kubernetes/sched-novolumeplugins.yaml
      name: sched-novolumeplugins
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/sched-novolumeplugins.yaml
      type: FileOrCreate
    name: sched-novolumeplugins
status: {}
================

**Comment by neolit123** [comment]
/sig apps
your report is missing details such as k8s version.
please fill the template properly.

**Comment by santkuma77** [comment]
Thanks Ivanov for taking a look. I tried to find the template, but I couldn’t find it. I’ve provided environment details below. Please let me know if any other details needed.

# kubectl version --short
Client Version: v1.21.3
Server Version: v1.21.3

# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL=https://www.centos.org/
BUG_REPORT_URL=https://bugs.centos.org/

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

# uname -a
Linux c3-nimdl385g10-041.lab.nimblestorage.com 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Hardware: 
Hpe proliant servers
