### ISSUE TITLE
dual-stack

### ISSUE THREAD

**Issue by Zruto** [kubernetes/kubernetes#112167]
when i run 
`kubeadm init --pod-network-cidr=10.244.0.0/16,2001:db8:42:0::/56 --service-cidr=10.96.0.0/16,2001:db8:42:1::/112
`
it worked.but when I setup flannel and run 
`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`
the kube-flannel's status is always "CrashLoopBackOff" 
the log is `Error registering network: failed to acquire lease: subnet "***:***:***::/**" specified in the PodCIDR, but doesn't exist in the flannel net config of the "***-***-***" node`
how can i fix it?

**Comment by neolit123** [comment]
it sounds like a flannel issue and not core k8s. try another cni plugin

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/kind support
/close
