### ISSUE TITLE
The arm release cannot run on ARM chips (raspberry Pi, Kunpeng 920)

### ISSUE THREAD

**Issue by yun-zero** [kubernetes/kubernetes#112196]
### What happened?

When running on the hardware where the title is located, the following error will occur:
-bash: ./keadm: cannot execute binary file: Exec format error
I tried to compile the arm version myself, but I encountered the following error:
go: github.com/kubeedge/kubeedge@v1.11.1 requires
        github.com/kubeedge/beehive@v0.0.0: reading github.com/kubeedge/beehive/go.mod at revision v0.0.0: unknown revision v0.0.0 
What should I do?

### What did you expect to happen?

Replace the arm distribution that can run normally, or compile the arm version normally

### How can we reproduce it (as minimally and precisely as possible)?

Here is my device information：
Linux printlink 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:10 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux

### Kubernetes version

<details>

keadm-v1.11.1-linux-arm.tar.gz
keadm-v1.9.2-linux-arm.tar.gz
</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
> -bash: ./keadm: cannot execute binary file: Exec format error

did you mean kubeadm?

how did you obtain the binary?

how are you building? have you followed the guide? https://github.com/kubernetes/kubernetes#to-start-developing-k8s

**Comment by neolit123** [comment]
> keadm-v1.11.1-linux-arm.tar.gz
keadm-v1.9.2-linux-arm.tar.gz

what is keadm, is that kubeadm?

if those are the exact versions these are ancient. try getting 1.24.

reopen the issue if you still have problems after that.

/kind support
/sig release
/close

**Comment by dims** [comment]
`keadm` seems to be kubeedge @neolit123

**Comment by neolit123** [comment]
ack, in that case that is a kube edge build issue, likely.
