### ISSUE TITLE
some grammatical mistakes in README.md file

### ISSUE THREAD

**Issue by pwnb0y** [kubernetes/kubernetes#112125]
### What happened?

I found some grammatical mistakes 
In place of : 
``` Kubernetes, also known as K8s, is an open source system for managing containerized applications across multiple hosts. It provides basic mechanisms for deployment, maintenance, and scaling of applications. ```

```To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported. ```

### What did you expect to happen?

It should be : 

``` Kubernetes, also known as K8s, is an open-source system for managing containerized applications across multiple hosts. It provides basic mechanisms for the deployment, maintenance, and scaling of applications. ```

``` To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries are not supported. ```

### How can we reproduce it (as minimally and precisely as possible)?

just by browsing the README.md file 

### Kubernetes version

<details>

``` 
Kubernetes v1.25.0
```

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
The original text is more idiomatic English. We should not amend it.

/triage not-reproducible
