### ISSUE TITLE
kube-scheduler: do not preempting orphan Pod

### ISSUE THREAD

**Issue by SataQiu** [kubernetes/kubernetes#112273]
### What would you like to be added?

kube-scheduler: do not preempting orphan Pod

### Why is this needed?

Currently, kube-scheduler preempts a Pod by deleting it:
https://github.com/kubernetes/kubernetes/blob/1ab40212a4e6cb10b3ae88c2e6c912a9fc1b1605/pkg/scheduler/framework/preemption/preemption.go#L362-L365

If a Pod(with empty ownerReferences) that is not managed by any controller is deleted, it will not automatically be recreated. And this behavior is very dangerous.  Although we can tell the user to set the highest priority to the orphan Pod or always use high-level controller(such as Deployment/StatefulSet) to create Pod to avoid eviction, optimizing our scheduler preemption policy might be a better idea.

**Comment by ahg-g** [comment]
I think this fits as a use case under https://github.com/kubernetes/kubernetes/issues/91492; see proposal at https://docs.google.com/document/d/1g2wj8S04M0yTy2t4l4GzrdARtxBpkBTfkJHw0oqBvXM/edit

But in general, creating unmanaged pods is not a recommended pattern.

**Comment by Huang-Wei** [comment]
> And this behavior is very dangerous.

Can you be more specific on why you think it's "dangerous"?

**Comment by chendave** [comment]
> If a Pod(with empty ownerReferences) that is not managed by any controller is deleted, it will not automatically be recreated. 

This is something I have brought to the table couple of months before, pls see: https://github.com/kubernetes/kubernetes/issues/111390

Difference from this proposal is that I suggested to re-create them when it's allowed in a dynamic cluster.  And your proposal here is ban the preemption for them.

It's dangerous because there are potential some workload / service running on with pods, the service cannot recovered without admin's intervention.

Maybe an option for preemption policy?

**Comment by SataQiu** [comment]
@Huang-Wei 
In general, I think the main responsibility of kube-scheduler is to bind Pod and Node. 
However, the preemption action appears to have exceeded this limit, the kube-scheduler can delete the Pod directly(and silently) from the cluster. The current K8s system is an open system, we can't expect that users will never directly create a Pod to run their services. Once a user-created Pod is deleted and cannot be auto rebuilt, this can lead to unexpected problems, especially as some older running Pod are likely to lose their original yaml file.

**Comment by kerthcet** [comment]
This sounds reasonable. And Option2 seems better.

**Comment by aravindb26** [comment]
@SataQiu 
I found some solutions here that have the same issue, I hope it somewhat helps you
https://stackoverflow.com/questions/69389043/kubernetes-scheduler

**Comment by Huang-Wei** [comment]
What's the real-world case that a pod is of low-priority while also an orphan Pod?

On the other hand, Pod preemption and Kubelet/kernel eviction treat orphan/regular Pods consistently. So why Pod preemption needs to be unique to take orphan pod into consideration? Or put it another way: why we should sacrifice a high-priority Pod's schedulability for the low-priority orphan Pods? If this feature is enabled, would a cluster admin be willing to enable it? as some tenants may turn to run orphan pods (to avoid preemption) to abuse this feature easily.

**Comment by SataQiu** [comment]
> as some tenants may turn to run orphan pods (to avoid preemption) to abuse this feature easily.

This is not what we want to see. The dangerous of preemption an orphan Pod is that the deleted Pod cannot be traced back.
Rather than `Delete` the orphan Pod directly, maybe the scheduler should tell kubelet to kill the preempted orphan Pod, and mark it as `Evicted`.

**Comment by Huang-Wei** [comment]
> maybe the scheduler should tell kubelet to kill the preempted orphan Pod, and mark it as Evicted.

Scheduler can directly mark it as Evicted, with its own message to distinguish from kubelet's eviction. But in this case, it's a design change for preemption: deleting pods physically vs. evicting pods and leaving their pods in "Evicted" state. May need to send out a survey to gather feedback before we make the change. And need to evaluate the benefits vs. code changes.

**Comment by SataQiu** [comment]
+1 for mark the preempted orphan Pod as `Evicted`. 
As for the regular Pod, I think it's ok to just delete it when it is preempted, as the parent controller will manage it automatically.

**Comment by ahg-g** [comment]
My biggest issue with this proposal is the following assumption

> The current K8s system is an open system, we can't expect that users will never directly create a Pod to run their services.

Pods in Kubernetes are ephemeral, workloads should be designed in a way while taking that into account. Preemption is one way where a pod could be deleted, but there are many other failure scenarios where pods could be removed (e.g., the node fails and pod gc removes the pod). 

Regarding the original ask, as I mentioned above, we have a mechanism to control disruptions caused the k8s, this is PDB. The proposal in https://docs.google.com/document/d/1g2wj8S04M0yTy2t4l4GzrdARtxBpkBTfkJHw0oqBvXM/edit# should help with the case you are raising here. Basically one could set PDBs on those pods to protect them from getting preempted.

**Comment by ahg-g** [comment]
I think this can be closed, please feel free to re-open if you feel there are aspects that we didn't discuss/cover.
