### ISSUE TITLE
client-go's InClusterConfig does not implement documented API discovery heuristics

### ISSUE THREAD

**Issue by olix0r** [kubernetes/kubernetes#112263]
### What happened?

client-go uses `KUBERNETES_SERVICE_HOST` to discover the API service address:

https://github.com/kubernetes/kubernetes/blob/67bde9a1023d1805e33d698b28aa6fad991dfb39/staging/src/k8s.io/client-go/rest/config.go#L507-L541 

This at odds with the documentation at https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api which states:

> While running in a Pod, the Kubernetes apiserver is accessible via a Service named `kubernetes` in the `default` namespace. Therefore, Pods can use the `kubernetes.default.svc` hostname to query the API server. Official client libraries do this automatically.

client-go does **not** do this. Though, it includes a TODO:

```go
		// TODO: switch to using cluster DNS.
		Host:            "https://" + net.JoinHostPort(host, port),
```

Ambiguity around the documented client discovery policy causes problems for client libraries; and cloud providers continue to promulgate the (now undocumented) legacy env configuration, e.g. https://github.com/Azure/AKS/issues/3183.

Would you accept a PR to remove the environment based in-cluster configuration in favor of always using `kubernetes.default.svc`?

### What did you expect to happen?

client-go should use `kubernetes.default.svc` and it should not honor the `KUBERNETES_SERVICE_HOST` environment variable.

OR the client docs should be updated with the proper heuristics.

### How can we reproduce it (as minimally and precisely as possible)?

...

### Kubernetes version

1.24

### Cloud provider

AKS

**Comment by liggitt** [comment]
The client docs should be updated, rather than change the client-go implementation. Making client-go depend on DNS is not a completely compatible change

**Comment by olix0r** [comment]
Looking at some of the officially supported kubernetes client libraries, all appear to use the environment variables and **none** use the in-cluster DNS

* https://github.com/kubernetes-client/javascript/blob/98414841064cbc322b617538a34bf0f5e31a5122/src/config.ts#L194-L219
* https://github.com/kubernetes-client/python/blob/16935036252be0fdf164f8ce624bd71eb8d35e89/kubernetes/base/config/incluster_config.py#L68-L70
* https://github.com/kubernetes-client/c/blob/2bb4393cc827e4c105fe57ded59e787bc3a4fbf0/kubernetes/config/incluster_config.c#L44-L67
* https://github.com/kubernetes-client/csharp/blob/f0d15cb39ef377370b219f0aa5f860764f0cc12a/src/KubernetesClient/KubernetesClientConfiguration.InCluster.cs#L51-L52
* https://github.com/kubernetes-client/haskell/blob/e848bc0c5c8d4fe4d2c9e8555331c219814c8ec9/kubernetes-client/src/Kubernetes/Client/Config.hs#L97-L99
* https://github.com/kubernetes-client/java/blob/73ae39a97dfdec9936944c23015edc1ab6742589/util/src/main/java/io/kubernetes/client/util/ClientBuilder.java#L242-L253
* https://github.com/kubernetes-client/ruby/blob/33861097e2eab9954b3f07f6898e5e8199199731/kubernetes/src/kubernetes/config/incluster_config.rb#L22-L46

So, with this in mind, the documentation should definitely be updated.

**Comment by olix0r** [comment]
/remove-lifecycle stale

https://github.com/kubernetes/website/pull/36691 has been open since September. Has approvals. Still waiting for a merge...
