### ISSUE TITLE
port-forward remote debug broken

### ISSUE THREAD

**Issue by s7an-it** [kubernetes/kubernetes#112250]
### What happened?

After moving to EKS 1.22.11* (I don't think is related to the distro) port-forwarding on intellij started to be interrupted shortly after start to send data.
I do revert it and problem is gone, I saw some patch in the version that change proxy config can the be related?

### What did you expect to happen?

I expected on port-forward connection to persist without problem.

### How can we reproduce it (as minimally and precisely as possible)?

Open port-forward and start debug with intellij on spring boot app any setup.

### Anything else we need to know?

On local test with telnet I can see my conn closed at 60 sec I don't know if expected behavior.

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> $ kubectl version
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.11-eks-18ef993", GitCommit:"b9628d6d3867ffd84c704af0befd31c7451cdc37", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

client version must be +1 / -1 of the server
maybe unrelated.

also <1.22 is out support.

> Open port-forward and start debug with intellij on spring boot app any setup.

i doubt any k8s core maintainers use intellij.
is this reproducible with kubectl?

pleass reopen if yes and provide steps.

/kind support
/close
