### ISSUE TITLE
Revisit response compression in k8s API

### ISSUE THREAD

**Issue by shyamjvs** [kubernetes/kubernetes#112296]
### What would you like to be added?

Based on load tests and production data gathered from thousands of production k8s clusters, we have observed that gzip compression in k8s API isn't optimal today. Here's the [full doc with details](https://docs.google.com/document/d/1rMlYKOVyujboAEG2epxSYdx7eyevC7dypkD_kUlBxn4) and the [SIG meeting recording](https://youtu.be/GKBqyV8y8j0) where this was discussed.

The consensus is this (please add/correct anything I'm missing):
- [x] [short-term] Reduce the default gzip level from 4 to 1 in kube-apiserver
- [x] [medium-term] Add `DisableCompression` field to kube-config, for clients to disable compression altogether from their end (and avoid [building their own workarounds](https://github.com/Kong/kubernetes-ingress-controller/issues/2675))
- [x] [medium-term] Add `--disable-compression` flag to kubectl for CLI users to easily turn off compression
- [ ] [long-term] Make apiserver choose gzip compression level for requests dynamically based on heuristics like object-types and compression ratios achieved (@smarterclayton suggested this idea in the past too and we now have data to show its value specifically wrt secrets/configmaps) 
- [ ] [long-term] Explore support for other compression implementations that are faster / less CPU-intensive. Some options are:
  - zstd - https://pkg.go.dev/github.com/klauspost/compress/zstd
  - pgzip - https://pkg.go.dev/github.com/klauspost/pgzip
  - snappy - https://pkg.go.dev/github.com/golang/snappy
  - CGO-based zlib - https://github.com/4kills/go-zlib (pointed by @simonis)

I'll own 1, 2 and 3 above. The rest need further eval - probably a KEP.

### Why is this needed?

To improve API call latencies (specifically list calls) as well as CPU/memory usage on the apiserver and client side, by trading off for slightly higher network bandwidth usage. The doc linked above has more details.

/sig api-machinery
/sig scalability

cc @wojtek-t @lavalamp @deads2k @liggitt @mborsz

**Comment by shyamjvs** [comment]
The only contentious point I had was about the gzip level being a flag on the apiserver, so any cluster operators that rely on level-4 compression today have a way of staying there. I don't have data to claim someone would need that, but well folks setup k8s clusters in all sorts of ways(?)

@lavalamp / @deads2k / @MikeSpreitzer Were of the opinion that such a flag maybe unnecessary burden for cluster operators to choose and set, compared to just setting a sane default internally. I'm ok with this approach, but anything you wanna add here?

**Comment by smarterclayton** [comment]
Interestingly, I naively expected secrets and config maps to benefit the most from compression, but only because it's likely that common secrets like ca certs and such would be overrepresented in many user's data.  That is an argument for 1 over 4 anyway, because you're likely to catch long prefixes.  The original compression argument was for slow clients with high latency doing large lists, and the threshold for compression was chosen as the heuristic (https://github.com/kubernetes/enhancements/pull/1115/files#diff-ed9dc9a1680e13756682fb58bc568bca6df4acbe1f729333f24ac144e806e390R108), and better data is totally sufficient.

If switching to compression 1 doesn't regress the density scalability tests, I don't see an argument to continue to support 4 without a user coming to us and asking for it.

**Comment by lavalamp** [comment]
>  only because it's likely that common secrets like ca certs and such would be overrepresented in many user's data

This would only help if we used the dictionaries for more than one request, but we don't. That would be complicated to set up and might require the client to do something special too.

**Comment by shyamjvs** [comment]
> If switching to compression 1 doesn't regress the density scalability tests, I don't see an argument to continue to support 4 without a user coming to us and asking for it (with data).

I've been monitoring metrics from our 100-node scale tests and doesn't look like the gzip change has caused a regression in the list latencies (though I'm not sure if those tests actually make much list calls in comparison to watches). Will also look at 5k node metrics once we have more runs (only had a single one so far).

That said, there seems to be something else from around 28 Aug that caused a latency regression ([link](http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=APIServer&metricname=LoadResponsiveness_Prometheus&Resource=pods&Scope=namespace&Subresource=&Verb=LIST)):

<img width="2052" alt="Screen Shot 2022-09-08 at 2 56 08 PM" src="https://user-images.githubusercontent.com/4333971/189235037-916161e7-196d-4f92-85af-7a29eb520ab5.png">

@marseel or @mborsz - Do you know already what may have caused this? Happy to follow this up on a separate issue.

**Comment by mborsz** [comment]
Thanks @shyamjvs for driving this. The plan makes sense to me.

Most likely the regression is caused by change to the load test itself that has been deployed that time (https://github.com/kubernetes/test-infra/pull/27290). It pushes much more pressure on the control plane (which is expected), but it seems to be too much for tiny master and (kube-api-qps=100 we have there) and generate some flakiness (this isn't expected). I'm about to rollback the change due to increased flakiness so we can see if the metrics increases to be sure.

**Comment by mborsz** [comment]
Yes, it was that change as the latency is back to normal levels:
![image](https://user-images.githubusercontent.com/2559168/189593676-e18810a3-a347-4f6f-bbdb-e522745b33e9.png)

**Comment by dims** [comment]
excellent new! thanks @mborsz and @shyamjvs

**Comment by simonis** [comment]
>       * CGO-based zlib - https://github.com/4kills/go-zlib (pointed by @simonis)

What I've suggested is investigate if using a native zlib implemenation (like [Mark Adlers ubiquitous zlib](https://github.com/madler/zlib)) can give you further improvements. I'm not a Go expert, but I've learned that Go has its own zlib implementation in pure Go. However, there's a cgo based Go wrapper for the native zlib library ([go-zlib](https://github.com/4kills/go-zlib)) which pretends to offer *significant performance benefits*. There also exist enhanced, but still fully API compatible versions of the original zlib like [zlib-chromium](https://chromium.googlesource.com/chromium/src/third_party/zlib) or [zlib-cloudflare](https://github.com/cloudflare/zlib) which [according to my measurements](https://github.com/simonis/zlib-bench/blob/master/Results.md), offer significant performance improvements over the original, native zlib implementation (e.g. deflation speed of zlib-cloudflare can be up to two times faster than the original zlib version).

So if you saw significant performance improvements by moving from compression level 4 to 1 I think you can get much higher improvements by using a one of the optimized, native zlib implementations through a cgo based GO wrapper.

**Comment by kkkkun** [comment]
releated issue： https://github.com/kubernetes/kubernetes/issues/106679

**Comment by lavalamp** [comment]
I'm very open to drop-in replacements for gzip that don't require clients to ask for a different compression format.

The specific library needs to be pretty bullet-proof though. Many users, few bugs, active maintainers, etc, are all good. Cgo use is a red flag, I'm not sure we'd rule it out completely but bugs in cgo code could be especially severe in processes like apiserver.

We'd probably need to see a PR demonstrating the changes and benchmark performance to talk about a replacement library more.

**Comment by krmayankk** [comment]
@shyamjvs is there a write-up of the actual customer scenario where we ran into this ? Would love to understand that.

**Comment by shyamjvs** [comment]
There isn't a particular customer scenario documented, but the general impact (seen across different customers) is described here - https://docs.google.com/document/d/1rMlYKOVyujboAEG2epxSYdx7eyevC7dypkD_kUlBxn4.

**Comment by wojtek-t** [comment]
/remove-lifecycle stale

@shyamjvs - do you have plans to look into both long-term points mentioned above?

**Comment by shyamjvs** [comment]
I'll likely not have bandwidth for those in the next 6 months, but few folks showed interest in this after the SIG meeting. We have two options I guess - close this for now and reopen later when someone picks it up, or keep it open as "help-wanted" (or maybe "good first issue"). Wdyt?

**Comment by lavalamp** [comment]
Let's close for now and reevaluate in 6 months or whenever it comes up again.
