### ISSUE TITLE
Kubernetes 1.0.0 apiserver using http got errors

### ISSUE THREAD

**Issue by Icedroid** [kubernetes/kubernetes#11222]
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.0", GitCommit:"cd821444dcf3e1e237b5f3579721440624c9c4fa", GitTreeState:"clean"}

$ kubectl create -f redis-master-controller.json 
replicationcontrollers/redis-master
```

I got so many errors:

```
E0714 20:11:36.851781   32036 replication_controller.go:324] unable to create pod replica: Pod "redis-master-" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account
E0714 20:11:36.857300   32036 replication_controller.go:324] unable to create pod replica: Pod "redis-master-" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account
```

I deploy k8s cluster [Getting Started from Scratch](https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.0/docs/getting-started-guides/scratch.md)  with Access the apiserver using HTTP.

When I start apiserver as follow:
```
./kube-apiserver --insecure-bind-address=0.0.0.0 \
        --insecure-port=8888 \
        --etcd-servers=http://127.0.0.1:4001 \
        --kubelet-port=10250 \
        --service-cluster-ip-range=10.0.0.0/16 \
        --log-dir=/var/log/k8s \
        --v=0 \
        --logtostderr=false \
        --allow-privileged=false \
        --admission-control="NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota" &

>0714 20:10:38.041214   32175 master.go:289] Will report 10.10.30.171 as public IP address.
E0714 20:10:38.041763   32175 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0714 20:10:38.041847   32175 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8888/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 0.0.0.0:8888: connection refused
E0714 20:10:38.041880   32175 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0714 20:10:38.042003   32175 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0714 20:10:38.042118   32175 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8888/api/v1/serviceaccounts: dial tcp 0.0.0.0:8888: connection refused
E0714 20:10:38.042277   32175 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
I0714 20:10:38.079198   32175 server.go:441] Serving securely on 0.0.0.0:6443
I0714 20:10:38.079213   32175 server.go:483] Serving insecurely on 0.0.0.0:8888
I0714 20:10:38.485759   32175 server.go:456] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
```
If I start apiserver not have  --admission-control.The k8s cluster run OK and I can create rc in normal.
```
./kube-apiserver --insecure-bind-address=0.0.0.0 \
        --insecure-port=8888 \
        --etcd-servers=http://127.0.0.1:4001 \
        --kubelet-port=10250 \
        --service-cluster-ip-range=10.0.0.0/16 \
        --log-dir=/var/log/k8s \
        --v=0 \
        --logtostderr=false \
        --allow-privileged=false  &

>2015/07/14 20:24:48 log.go:30: [restful/swagger] listing is available at https://10.10.30.171:6443/swaggerapi/
[restful] 2015/07/14 20:24:48 log.go:30: [restful/swagger] https://10.10.30.171:6443/swaggerui/ is mapped to folder /swagger-ui/
```

**Comment by dchen1107** [comment]
Have you tried to remove SecurityContextDeny from your --adminssion-control and restart your kube-apiserver?

**Comment by Icedroid** [comment]
@dchen1107 
```
# ./kube-apiserver --insecure-bind-address=0.0.0.0 \
         --insecure-port=8888 \
         --etcd-servers=http://127.0.0.1:4001 \
         --kubelet-port=10250 \
         --service-cluster-ip-range=10.0.0.0/16 \
         --log-dir=/var/log/k8s \
         --v=0 \
         --logtostderr=false \
         --allow-privileged=false \
         --admission-control="NamespaceLifecycle,NamespaceExists,LimitRanger,ServiceAccount,ResourceQuota" &
[2] 737
> E0715 09:58:26.777414     737 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0715 09:58:26.777801     737 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0715 09:58:26.777494     737 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
E0715 09:58:26.777599     737 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8888/api/v1/serviceaccounts: dial tcp 0.0.0.0:8888: connection refused
E0715 09:58:26.777743     737 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8888/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 0.0.0.0:8888: connection refused
E0715 09:58:26.777441     737 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
[restful] 2015/07/15 09:58:26 log.go:30: [restful/swagger] listing is available at https://10.10.30.171:6443/swaggerapi/
[restful] 2015/07/15 09:58:26 log.go:30: [restful/swagger] https://10.10.30.171:6443/swaggerui/ is mapped to folder /swagger-ui/
```

**Comment by Icedroid** [comment]
Is it a bug? Who know how to deploy the k8s cluster correctly?

**Comment by dchen1107** [comment]
Have you tried what I suggested above by removing ServiceAccount from your kube-apiserver's flag: --admission-control, and restart your kube-apiserver?

**Comment by Icedroid** [comment]
@dchen1107 
Do you mean remove ServiceAccount or SecurityContextDeny, I have remove both:

```
[root@urestful bin]# ./kube-apiserver --insecure-bind-address=0.0.0.0 \
>         --insecure-port=8888 \
>         --secure-port=0 \
>         --etcd-servers=http://127.0.0.1:4001 \
>         --kubelet-port=10250 \
>         --service-cluster-ip-range=10.0.0.0/16 \
>         --log-dir=/var/log/k8s \
>         --v=0 \
>         --logtostderr=false \
>         --allow-privileged=false \
>         --admission-control="NamespaceLifecycle,NamespaceExists,LimitRanger,ResourceQuota" &
[1] 3476
[root@urestful bin]# E0716 16:36:28.119595    3476 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0716 16:36:28.119839    3476 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0716 16:36:28.119628    3476 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0716 16:36:28.119755    3476 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
[restful] 2015/07/16 16:36:28 log.go:30: [restful/swagger] listing is available at https://10.10.30.171:6443/swaggerapi/
[restful] 2015/07/16 16:36:28 log.go:30: [restful/swagger] https://10.10.30.171:6443/swaggerui/ is mapped to folder /swagger-ui/
E0716 16:36:32.660386    3476 errors.go:62] apiserver received an error that is not an api.Status: 100: Key not found (/registry/events/default/mongos2.13f1128932bbf23b) [30529]
```

**Comment by dchen1107** [comment]
Sorry, I mean ServiceAccount, not SecurityContextDeny above.

I think initially you might hit backward compatibility issue #11380.

**Comment by jk-shah** [comment]
@dchen1107 

I ran into the same issue. Taking ServiceAccount out in the config of api-server and restarting api-server solved the issue..
Thanks.

Regards,
Jignesh

**Comment by Icedroid** [comment]
@jk-shah what the ARGS of starting your api-server? I do with the ARGS only not having --admin-controller is right.

**Comment by genewei** [comment]
I ran into the same issue. Taking ServiceAccount,SecurityContextDeny out in the config of api-server and restarting api-server solved the issue.
like this 
apiserver

KUBE_ADMISSION_CONTROL="--admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,ResourceQuota"

**Comment by Icedroid** [comment]
I upgrade to the latest version 1.0.1, when I start api-server also failed.
[root@localhost bin]## ./kube-apiserver --insecure-bind-address=0.0.0.0 \
>         --insecure-port=8888 \
>         --secure-port=0 \
>         --etcd-servers=http://127.0.0.1:4001 \
>         --kubelet-port=10250 \
>         --service-cluster-ip-range=10.0.0.0/16 \
>         --log-dir=/var/log/k8s \
>         --v=0 \
>         --logtostderr=false \
>         --allow-privileged=false \
>         --admission-control="NamespaceLifecycle,NamespaceExists,LimitRanger,ResourceQuota" &
[2] 14787
[root@urestful bin]# E0723 10:20:17.650970   14787 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0723 10:20:17.651053   14787 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0723 10:20:17.651008   14787 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0723 10:20:17.651157   14787 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
[restful] 2015/07/23 10:20:17 log.go:30: [restful/swagger] listing is available at https://10.10.30.171:6443/swaggerapi/
[restful] 2015/07/23 10:20:17 log.go:30: [restful/swagger] https://10.10.30.171:6443/swaggerui/ is mapped to folder /swagger-ui/

**Comment by zhoufwind** [comment]
#KUBE_ADMISSION_CONTROL="--admission_control=NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota"

Similar error occurred, got fixed by comment abover whole line at 'apiserver' and restart kube-apiserver

**Comment by danieldreier** [comment]
I was able to resolve the issue by removing "ServiceAccount" from KUBE_ADMISSION_CONTROL but I don't understand what the security implications of that change are, what kind of access I've granted by doing that. Can anybody clarify?

**Comment by pfremm** [comment]
Yes, I'd like to know as well.  Is this documented anywhere?

**Comment by derekwaynecarr** [comment]
@liggitt guessing there is an error in this guide

**Comment by derekwaynecarr** [comment]
How are you starting the controller manager?

**Comment by liggitt** [comment]
Service account admission control requires a service account and a token to exist before allowing pods to be created. 

The service account token is created automatically by controllers in the controller manager if you provide a service account private key file argument.

**Comment by liggitt** [comment]
Also note that the API server defaults to using its TLS serving key to verify service account tokens. If you are not serving over https and don't have a TLS serving key, you can provide the API server the same key file you give the controller manager in order for the API to validate the generated service account tokens.

**Comment by Icedroid** [comment]
@derekwaynecarr ./kube-controller-manager --v=0 --logtostderr=false --log-dir=/var/log/k8s --master=127.0.0.1:8888

@liggitt  I found it don't create the default service account automatically
# kubectl get serviceaccounts
NAME      SECRETS
default   0

**Comment by liggitt** [comment]
You can do what `hack/local-up-cluster.sh` (https://github.com/GoogleCloudPlatform/kubernetes/blob/master/hack/local-up-cluster.sh) does:

To generate the key:
```
openssl genrsa -out "${SERVICE_ACCOUNT_KEY}" 2048
```

To start the api server:
```
./kube-apiserver" ... --service_account_key_file="${SERVICE_ACCOUNT_KEY}" ...
```

To start the controller manager:
```
./kube-controller-manager" ... --service_account_private_key_file="${SERVICE_ACCOUNT_KEY}" ...
```

**Comment by Icedroid** [comment]
Thanks for your reply.

[root@urestful bin]# genrsa -out /tmp/kube-serviceaccount.key 2048
Generating RSA private key, 2048 bit long modulus
............................................................+++
.......................................................................................................................+++
e is 65537 (0x10001)

[root@urestful bin]# ./kube-apiserver --insecure-bind-address=0.0.0.0 \
>         --insecure-port=8888 \
>         --secure-port=0 \
>         --token-auth-file=/dev/null \
>         --service-account-key-file=/tmp/kube-serviceaccount.key \
>         --etcd-servers=http://127.0.0.1:4001 \
>         --kubelet-port=10250 \
>         --service-cluster-ip-range=10.0.0.0/16 \
>         --log-dir=/var/log/k8s \
>         --v=0 \
>         --logtostderr=false \
>         --allow-privileged=false \
>         --admission-control="NamespaceLifecycle,NamespaceExists,LimitRanger,ServiceAccount,ResourceQuota" &
[1] 31812
[root@urestful bin]# E0730 14:31:16.288962   31812 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0730 14:31:16.289112   31812 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8888/api/v1/serviceaccounts: dial tcp 0.0.0.0:8888: connection refused
E0730 14:31:16.289171   31812 reflector.go:136] Failed to list *api.Namespace: Get http://0.0.0.0:8888/api/v1/namespaces: dial tcp 0.0.0.0:8888: connection refused
E0730 14:31:16.290253   31812 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8888/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: dial tcp 0.0.0.0:8888: connection refused
E0730 14:31:16.290407   31812 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8888/api/v1/limitranges: dial tcp 0.0.0.0:8888: connection refused
E0730 14:31:16.290636   31812 reflector.go:136] Failed to list *api.ResourceQuota: Get http://0.0.0.0:8888/api/v1/resourcequotas: dial tcp 0.0.0.0:8888: connection refused
[restful] 2015/07/30 14:31:16 log.go:30: [restful/swagger] listing is available at https://10.10.30.171:6443/swaggerapi/
[restful] 2015/07/30 14:31:16 log.go:30: [restful/swagger] https://10.10.30.171:6443/swaggerui/ is mapped to folder /swagger-ui/

I have also got these errors.

[root@urestful bin]#./kube-controller-manager  --v=0 \
>         --logtostderr=false \
>         --log-dir=/var/log/k8s  \
>         --service-account-private-key-file=/tmp/kube-serviceaccount.key \
>         --master=127.0.0.1:8888 &
[2] 31832
[root@urestful bin]# E0730 14:32:22.517311   31832 controllermanager.go:198] Failed to start service controller: ServiceController should not be run without a cloudprovider.

**Comment by aerofoil-kite** [comment]
apiserver.service file:

    [Unit]
    -------
    -------

    [Service]
    
    --service-account-key-file=/srv/kubernetes/service_acc_key \
    --admission_control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityCont$
    
controller-manager.service

	[Unit]
	------
        ------

	[Service]
	--service_account_private_key_file= /srv/kubernetes/service_acc_key \

Both services are running 
But still facing these error

    Error from server: error when creating "----.yaml": Pod "----" is forbidden: no API token     found for service account default/default, retry after the token is automatically created and added to the service account

What should I do?

**Comment by liggitt** [comment]
Those options look right for the service account key options. I'm not familiar with `ServiceController`, maybe someone else can chime in on that

**Comment by sandish2222** [comment]
i got the same issue , and removing ServiceAccount of admission_controll works.

Thanks.

**Comment by pfremm** [comment]
If you configure your cluster to use certs in kube-apiserver you can leave the ServiceAccount setting.

**Comment by mbforbes** [comment]
+cc @a-robinson for "ServiceController should not be run without a cloudprovider"

**Comment by a-robinson** [comment]
The ServiceController error is nothing to worry about if you're running locally, only if you're running on a cloud where you expect to be able to create external load balancers.

**Comment by tobegit3hub** [comment]
It works for me. Thanks @jk-shah 😃
