### ISSUE TITLE
Add `--diff` flag to `kubectl get xxx -w -oyaml` to see the diff lines

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#112224]
### What would you like to be added?

To add a `--diff` flag to `kubectl get xxx -w -oyaml` to see the diff lines, like this:
```
kubectl get xxx -w -oyaml | json --diff
```

With this `--diff` flag, we can see the diff lines more clearly, to facilitate resource watching.
Also see the https://github.com/kubernetes/enhancements/issues/3493.

### Why is this needed?

When we use `kubectl get xxx -w -oyaml | json` to watch a resource change, it is hard to spot the diff lines
between the watching stream output, so we need a `--diff` to just show the diff lines to make it easy.

**Comment by imuxin** [comment]
@astraw99, I wrote a plugin for kubectl, [kubectl-watch](https://github.com/imuxin/kubectl-watch), wish that can help you.

**Comment by wwj-2017-1117** [comment]
after about 0.5h ,  the commdn "kubectl get xxx -w  "  will exit, how to set the timeout ?
