### ISSUE TITLE
Failed to execute iptables-restore" err="exit status 1 

### ISSUE THREAD

**Issue by jw-websensa** [kubernetes/kubernetes#112292]
### What happened?

After updating my on-premis cluster to 1.23.10 I noticed that services stopped working.
After some investigation I noticed this error recurring in kube-proxy logs:
```
proxier.go:1484] "Failed to execute iptables-restore" err="exit status 1 (iptables-restore: line 1193 failed\n)" 
```

### What did you expect to happen?

For cluster to be working smoothly after update

### How can we reproduce it (as minimally and precisely as possible)?

I have no idea

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.10", GitCommit:"7e54d50d3012cf3389e43b096ba35300f36e0817", GitTreeState:"clean", BuildDate:"2022-08-17T18:26:59Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On-premis
</details>

### OS version

<details>

```console
Ubuntu 20.04.1 LTS (Focal Fossa) on all nodes
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker 19.03.12
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico for networking
</details>

**Comment by aojea** [comment]
> proxier.go:1484] "Failed to execute iptables-restore" err="exit status 1 (iptables-restore: line 1193 failed\n)" 

can you execute `iptables-save` on that node to dump the content to a file and check what happens in line 1193?

**Comment by jw-websensa** [comment]
@aojea Correct me, if I am wrong, but as I see it from kube proxy logs (I increased verbosity) it prepares set of rules to run with `iptables-restore` - I can see them from logs:
```
proxier.go:1481] "Restoring iptables" rules="*filter\n:KUBE-SERVICES....
iptables.go:422] running iptables-restore [-w 5 -W 100000 --noflush...
proxier.go:1484] "Failed to execute iptables-restore" err="exit status 1...
```
This line number that fails varies, I dumped to file this set or rules and every time line with this number looked like this:
```
-X KUBE-SVC-MCWT2CZJ4AMUVUY7
```
(this prefix was different every time I checked)

**Comment by aojea** [comment]
what is your iptables version? `iptables --version`

**Comment by jw-websensa** [comment]
@aojea 1.8.4 on nodes, 1.8.7 on kube-proxy pods

**Comment by jw-websensa** [comment]
Sounding as stupid as it is, I resolved my issue... by restarting all nodes

**Comment by aojea** [comment]
> I am considering flushing all iptables rules, but I am not sure if kubernetes will be able to recreate them all, can anyone tell if this is safe?

kubernetes recreates it
