### ISSUE TITLE
Kubernetes: couldn't validate the identity of the API Server : protocol not available

### ISSUE THREAD

**Issue by gursewak96** [kubernetes/kubernetes#112210]
### What happened?

After setting up the master node, worker node couldn't able to join the master. I get the error message - " couldn't validate the identity of the API Server: Get "https://{apiserver-ip}/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": **dial tcp {kubeapi-ip}:6443: connect: protocol not available**"

I am using VMs
master - 2cpu, 2 GB memory
worker - 1 cpu, 1 GB memory

### What did you expect to happen?

Should able to use kubectl command to work on other machine as well as worker node to join with master.

### How can we reproduce it (as minimally and precisely as possible)?

Join command: 
```
sudo kubeadm join 192.168.56.2:6443 --token xt3jug.8sfbnzqb4cnd7wbn \
        --discovery-token-ca-cert-hash sha256:3514a9d85abcfd9d00230beffa7731cebbd51b20e5fa66f10247e0bd473027c8
```

And i used flannel with pod id cidr same as i used while using kubeadm init 

`kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml`

### Anything else we need to know?

Join command: 
sudo kubeadm join 192.168.56.2:6443 --token xt3jug.8sfbnzqb4cnd7wbn \
        --discovery-token-ca-cert-hash sha256:3514a9d85abcfd9d00230beffa7731cebbd51b20e5fa66f10247e0bd473027c8

And i used flannel with pod id cidr same as i used while using kubeadm init 

### Kubernetes version

<details>

```console
$ keubectl version
1.25.0
```

</details>

### Cloud provider

<details>
i am using virtual machine via Vagrant

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
I have used Kubeadm to install the k8 cluster
</details>

### Container runtime (CRI) and version (if applicable)

<details>
I have used Containerd.
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
I have used Flannel
</details>

**Comment by neolit123** [comment]
it's better to try asking on the support channels instead.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

> 6443: connect: protocol not available
