### ISSUE TITLE
kube-apiserver: ResolveEndpoint function is deterministic

### ISSUE THREAD

**Issue by prometherion** [kubernetes/kubernetes#112246]
### What happened?

When using Dynamic Admission Controllers such as a Mutating or a Validating Webhook configuration pointing to an in-cluster Service backed by multiple endpoints I noticed a reproducible distribution in the request load for a given amount of requests.

### What did you expect to happen?

When using a Webhook Configuration pointing to an in-cluster Service, the requests load should not be predictable. It should be forwarded to all the available endpoints in a non-deterministic way.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Kubernetes cluster
2. Create a Deployment, serving an HTTPS endpoint that is returning an allowed Admission response, backed by 2 or more replicas; at every hit, print in the `stdout` the response
3. Expose the Deployment pods
4. Install a Mutating or a Validating Webhook Configuration, pointing it to the said Service 
5. Issue 100 HTTP requests that will be managed by the Deployment
6. Verify the hit on each Pod, it will be 33 for the first one, 33 for the second one, and 29 for the third.
7. Repeat multiple times, expecting the same results reported at point nr. 6

Using the `kubernetes` code base, the following snippet can be used to reproduce the faked random distribution.

```go
func TestResolve_Random(t *testing.T) {
	service := &v1.Service{
		ObjectMeta: metav1.ObjectMeta{
			Namespace: "default",
			Name:      "webhook",
		},
		Spec: v1.ServiceSpec{
			Type:      v1.ServiceTypeClusterIP,
			ClusterIP: "10.96.86.125",
			Ports: []v1.ServicePort{
				{
					Name:       "webhook",
					Port:       9443,
					TargetPort: intstr.FromInt(9443),
				},
			},
		},
	}

	serviceCache := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
	serviceLister := v1listers.NewServiceLister(serviceCache)
	require.NoError(t, serviceCache.Add(service), "unexpected service add error")

	endpoints := []*v1.Endpoints{
		{
			ObjectMeta: metav1.ObjectMeta{
				Namespace: "default",
				Name:      "webhook",
			},
			Subsets: []v1.EndpointSubset{
				{
					Addresses: []v1.EndpointAddress{
						{
							IP: fuzzyEndpoint1,
						},
						{
							IP: fuzzyEndpoint2,
						},
						{
							IP: fuzzyEndpoint3,
						},
					},
					Ports: []v1.EndpointPort{
						{
							Name:     "webhook",
							Port:     9443,
							Protocol: v1.ProtocolTCP,
						},
					},
				},
			},
		},
	}

	endpointCache := cache.NewIndexer(cache.MetaNamespaceKeyFunc, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
	endpointLister := v1listers.NewEndpointsLister(endpointCache)
	for _, ep := range endpoints {
		require.NoError(t, endpointCache.Add(ep), "unexpected endpoint add error")
	}

	testExecution := 100

	invocationCount := 100

	for te := 0; te < testExecution; te++ {
		invocationRes := map[string]int{
			fuzzyEndpoint1 + ":9443": 0,
			fuzzyEndpoint2 + ":9443": 0,
			fuzzyEndpoint3 + ":9443": 0,
		}

		for i := 0; i < invocationCount; i++ {
			u, err := ResolveEndpoint(serviceLister, endpointLister, service.Namespace, service.Name, 9443)
			require.NoError(t, err, "unexpected resolve error")

			if _, ok := invocationRes[u.Host]; !ok {
				t.Fatalf("received an IP that is not available in any Endpoint subset")
			}
			invocationRes[u.Host]++
		}
	}
}
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-03-06T21:32:53Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N.R.
</details>

### OS version

<details>

N.R.

</details>

### Install tools

<details>

N.R.

</details>

### Container runtime (CRI) and version (if applicable)

<details>

N.R.

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

N.R.

</details>

**Comment by prometherion** [comment]
Digging the code I found the issue I'm facing:

https://github.com/kubernetes/kubernetes/blob/bcea98234f0fdc5ce4e976758977eec72b13bfd4/staging/src/k8s.io/apiserver/pkg/util/proxy/proxy.go#L42-L90

This function is extracting Kubernetes Endpoint resources from a Service and the incriminated portion of code that is not randomizing properly the Endpoint selection is the following one.

https://github.com/kubernetes/kubernetes/blob/bcea98234f0fdc5ce4e976758977eec72b13bfd4/staging/src/k8s.io/apiserver/pkg/util/proxy/proxy.go#L69

The Go programming language is a deterministic one, meaning that the default number generator will return always the same number unless a seed change is put in place.

**Comment by liggitt** [comment]
> Verify the hit on each Pod, it will be 33 for the first one, 33 for the second one, and 29 for the third.

A sample size of 100 is small enough that an imperfect distribution of requests is expected. Additionally, the IP selection code only runs when *new* connections to the backend webhook are dialed, which does not correspond 1:1 with API server requests. Existing connections to the backend are kept-alive and reused for subsequent requests, so a slightly skewed pool of open connections can lead to slightly skewed distribution of requests to backends. Eventually, those connections close, and are re-established by selecting random backends again.

Using math.Rand, seeded at process start, to generate a random sequence used to select a random iteration point and then a random address seems like a reasonable way to distribute established connections to backends in a stateless way

**Comment by prometherion** [comment]
> A sample size of 100 is small enough that an imperfect distribution of requests is expected

My concern wasn't regarding the perfectly balanced distribution, rather on the reproducible distribution of the subsequent webhook calls that is not random by design.

**Comment by liggitt** [comment]
I don't think that is caused by the use of math.Rand. https://go.dev/play/p/xRPdUXEzsDr shows that math.Rand produces different distributions/sequences over time. I think it's more likely you have a slightly skewed pool of open connections that happen to produce similar distributions of requests. I would not expect a 33/33/29 distribution to be persistent over a longer time period or a larger number of requests.

**Comment by prometherion** [comment]
It seems clear to me we're getting the same sequence, although when adding time to simulate a real word scenario.

[Execution nr.1](https://go.dev/play/p/eZPvD401JVV) returns the following output.
```
1
1
0
2
1
2
1
2
0
2
```

[Execution nr.2 with increased sleep](https://go.dev/play/p/3CFjK41ywri) returns the exact sequence.
```
1
1
0
2
1
2
1
2
0
2
```

Maybe I'm not getting your point, sorry in advance.

**Comment by aojea** [comment]
despite the sequence is predictable, the returned endpoint will be different

**Comment by aojea** [comment]
@prometherion can we close it ?
