### ISSUE TITLE
Pods getting killed after startup probe failure 

### ISSUE THREAD

**Issue by tarun-asthana** [kubernetes/kubernetes#112221]
### What happened?

Hi!
I can see my pods are getting killed post probe failure.
Firstly, I can see these two odd logs in my syslog:
```
networkd-dispatcher[781]: WARNING:Unknown index 56 seen, reloading interface list
systemd-udevd[455717]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
```
Next, I see my probes getting failed for multiple pods like
`Startup probe for "pod1:app" failed (failure): Get http://100.125.215.114:8081/ping: dial tcp 100.125.215.114:8081: connect: connection refused`
Next, I see the pod getting killed by kubelet
` kubelet[11767]: I0831 03:58:09.959675   11767 kubelet.go:1926] SyncLoop (DELETE, "api"): 
 kubelet[11767]: I0831 03:58:09.959996   11767 kuberuntime_container.go:648] Killing container "" with 30second grace period
`
I'm using Ubuntu 20.04 and Kubernetes 1.18.9 . I checked the Ubuntu errors and found this report - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1775131
However, there's no solution/lead mentioned here.

### What did you expect to happen?

1. The networkd and systemd log should not have come
2. The pod shouldn't have been killed post probe failure.
3. Multiple probes shouldn't have failed at once on the same node.

### How can we reproduce it (as minimally and precisely as possible)?

This seems intermittent and I don't think we can recreate it.

### Kubernetes version

1.18.9

### Cloud provider

AWS

### OS version

Ubuntu 20.04

### Container runtime (CRI) and version (if applicable)

CRI: Docker

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CNI: Calico

**Comment by gjkim42** [comment]
/sig node

> ### Kubernetes version
> 1.18.9

I think v1.18 is deprecated and no longer supported.
Can you update your cluster and confirm if this issue is reproduced?

**Comment by tarun-asthana** [comment]
@gjkim42 I understand. However, none of the patches to v1.19 heed on this issue. That's why I highly doubt it's related to versioning.
Infact, this issue is not reported as a  kubernetes issue yet. I only saw this in the Ubuntu bugs but with no resolution.

**Comment by gjkim42** [comment]
> I checked the Ubuntu errors and found this report - https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1775131

As you said, the network failure issue has been reproduced in ubuntu without kubernetes to some users.
It seems very unlikely relevant to the kubernetes.

> ### What did you expect to happen?
> 1. The networkd and systemd log should not have come
> 2. The pod shouldn't have been killed post probe failure.
> 3. Multiple probes shouldn't have failed at once on the same node.

1 and 3 seem not the statements that kubernetes can guarantee as the issue is caused by the node environment itself.
You can fix the issue description.

I think 2 might be the bug of kubernetes. I'll confirm it.

**Comment by gjkim42** [comment]
I confirmed that a pod is not getting killed after startup probe failure it just restarts the container.

```sh
$ kubectl describe pods test | tail
  ----     ------     ----                   ----               -------
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned default/test to 127.0.0.1
  Normal   Pulled     10m                    kubelet            Successfully pulled image "nginx" in 1.949641149s
  Normal   Pulled     9m30s                  kubelet            Successfully pulled image "nginx" in 2.010523516s
  Normal   Created    9m (x3 over 10m)       kubelet            Created container test
  Normal   Started    9m (x3 over 10m)       kubelet            Started container test
  Normal   Pulled     9m                     kubelet            Successfully pulled image "nginx" in 2.031584515s
  Warning  Unhealthy  8m33s (x9 over 9m53s)  kubelet            Startup probe failed:
  Normal   Killing    8m33s (x3 over 9m33s)  kubelet            Container test failed startup probe, will be restarted
  Normal   Pulling    4m53s (x7 over 10m)    kubelet            Pulling image "nginx"
```
```sh
$ kubectl get pods test
NAME   READY   STATUS             RESTARTS      AGE
test   0/1     CrashLoopBackOff   7 (95s ago)   10m
```

> Next, I see the pod getting killed by kubelet
> `kubelet[11767]: I0831 03:58:09.959675 11767 kubelet.go:1926] SyncLoop (DELETE, "api"): kubelet[11767]: I0831 03:58:09.959996 11767 kuberuntime_container.go:648] Killing container "" with 30second grace period`

I think the reason the pod was killed could be the network failure of the node.
If a node has network failure for some time(5 minutes?), the kubernetes mark NotReady to that node, and all pods of the NotReady node are killed. It is not a bug but intended behavior.


> ### What did you expect to happen?
> 1. The networkd and systemd log should not have come
> 2. The pod shouldn't have been killed post probe failure.
> 3. Multiple probes shouldn't have failed at once on the same node.


To summary,

1 and 3 seem relevant to the node environment itself.
2: I confirmed that the pods are not getting killed after post probe failure.

**Comment by tarun-asthana** [comment]
@gjkim42 I can confirm that all pods on the node were not getting killed. Neither was the node terminated. This is not expected behaviour.
I've opened the ticket with Ubuntu - https://bugs.launchpad.net/ubuntu/+bug/1988661

**Comment by gjkim42** [comment]
Could you give us more information? Logs of kubelet and kube-controller-manager would be helpful.

And I recommend you to update the kubernetes so that we don't have to inspect outdated code. As you said, this may not be relevant to the kubernetes version, but it may be. We just want to make sure this bug still exists in code that we should maintain.

**Comment by tarun-asthana** [comment]
I understand. I have the kubelet logs but the node is terminated now so can't get the kube controller logs. I do have the kernel logs.

`Aug 31 03:50:34 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Link UP
Aug 31 03:50:34 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Gained carrier
Aug 31 03:50:34 ip-10-50-117-248 networkd-dispatcher[781]: WARNING:Unknown index 56 seen, reloading interface list
Aug 31 03:50:34 ip-10-50-117-248 systemd-udevd[455717]: ethtool: autonegotiation is unset or enabled, the speed and duplex are not writable.
Aug 31 03:50:34 ip-10-50-117-248 kubelet[455785]: 2022-08-31 03:50:34.635 [INFO][455785] k8s.go 391: Added Mac, interface name, and active container ID to endpoint ContainerID=pod1`
`
Aug 31 03:50:34 ip-10-50-117-248 systemd-udevd[455717]: Using default interface naming scheme 'v245'.
Aug 31 03:50:34 ip-10-50-117-248 kubelet[455785]: 2022-08-31 03:50:34.642 [INFO][455785] k8s.go 423: Wrote updated endpoint to datastore ContainerID="dfabf6a3a63dc6d556039ed12440247cdfc46f4cb4fe7c6bf5f000c42f4c85f1" Namespace="ns1" Pod="pod1" WorkloadEndpoint="ip--10--50--117--248.ap--southeast--1.compute.internal-k8s-pod1-eth0"
Aug 31 03:50:34 ip-10-50-117-248 kubelet[11767]: I0831 03:50:34.645890   11767 kubelet.go:1917] SyncLoop (UPDATE, "api"): "pod1_ns"
Aug 31 03:50:34 ip-10-50-117-248 dockerd[11657]: time="2022-08-31T03:50:34.669269548Z" level=warning msg="Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap."
Aug 31 03:50:34 ip-10-50-117-248 kubelet[11767]: I0831 03:50:34.715092   11767 kubelet.go:1955] SyncLoop (PLEG): "pod1_ns", event: &pleg.PodLifecycleEvent{Type:"ContainerStarted"}
Aug 31 03:50:34 ip-10-50-117-248 containerd[11489]: time="2022-08-31T03:50:34.755702861Z" level=info msg="shim containerd-shim started" address="/containerd-shim/moby/X/shim.sock" debug=false pid=455908
Aug 31 03:50:35 ip-10-50-117-248 kubelet[11767]: I0831 03:50:35.761946   11767 kubelet.go:1955] SyncLoop (PLEG): "pod1_ns", event: &pleg.PodLifecycleEvent{ID:"06f75ab6-767c-422e-804c-c7b9e820728e", Type:"ContainerStarted"}
Aug 31 03:50:36 ip-10-50-117-248 systemd-networkd[630]: cali805c5f20419: Gained IPv6LL
Aug 31 03:50:37 ip-10-50-117-248 kubelet[11767]: I0831 03:50:37.284261   11767 prober.go:124] Startup probe for "pod1_ns:app" failed (failure): Get http://100.125.215.114:8081/ping: dial tcp 100.125.215.114:8081: connect: connection refused (repeated 9 times)
`
`Aug 31 03:50:53 ip-10-50-117-248 kubelet[11767]: I0831 03:50:53.717708   11767 kubelet_getters.go:173] status for pod kube-proxy-ip-10-50-117-248.ap-southeast-1.compute.internal updated to {Running [{Initialized True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:41:54 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:42:07 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:42:07 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2022-08-31 02:41:54 +0000 UTC  }]    10.50.117.248 10.50.117.248 [{10.50.117.248}] 2022-08-31 02:41:54 +0000 UTC [] [{kube-proxy {nil &ContainerStateRunning{StartedAt:2022-08-31 02:42:07 +0000 UTC,} nil} {nil nil nil} true 0 k8s.gcr.io/kube-proxy:v1.18.9 docker-pullable://k8s.gcr.io/kube-proxy@sha256:71707046546578eaa3183dbf0106475f655fbfbdb6a5791cdb6fe4ff9a402895 docker://2860b7774c0a6d203562036e1a74a567af3875e946974a962c4726083c31e5d0 0xc001bfbff9}] Burstable []}`

`Aug 31 03:54:00 ip-10-50-117-248 kubelet[11767]: I0831 03:54:00.065654   11767 prober.go:124] Liveness probe for "pod2_ns2" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:00 ip-10-50-117-248 kubelet[11767]: I0831 03:54:00.142305   11767 prober.go:124] Liveness probe for "pod3_ns2" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:03 ip-10-50-117-248 kubelet[11767]: I0831 03:54:03.995972   11767 prober.go:124] Readiness probe for "pod4_ns2" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:04 ip-10-50-117-248 kubelet[11767]: I0831 03:54:04.552354   11767 prober.go:124] Readiness probe for "pod5_ns2" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:05 ip-10-50-117-248 kubelet[11767]: I0831 03:54:05.159822   11767 prober.go:124] Readiness probe for "pod6_ns2" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:05 ip-10-50-117-248 kubelet[11767]: I0831 03:54:05.403331   11767 prober.go:124] Liveness probe for "pod7_ns3" failed (failure):
Aug 31 03:54:06 ip-10-50-117-248 kubelet[11767]: I0831 03:54:06.408768   11767 prober.go:124] Liveness probe for "pod8_ns4" failed (failure): HTTP probe failed with statuscode: 500
Aug 31 03:54:10 ip-10-50-117-248 kubelet[11767]: I0831 03:54:10.066091   11767 prober.go:124] Liveness probe for "pod9_ns5" failed (failure): HTTP probe failed with statuscode: 500`
Not all the pods have their probe failing ^

`Aug 31 03:58:09 ip-10-50-117-248 kubelet[11767]: I0831 03:58:09.959675   11767 kubelet.go:1926] SyncLoop (DELETE, "api"): "pod1_ns1"
Aug 31 03:58:09 ip-10-50-117-248 kubelet[11767]: I0831 03:58:09.959996   11767 kuberuntime_container.go:648] Killing container "pod1" with 30second grace period`

This was followed by normal pod deletion logs.

**Comment by gjkim42** [comment]
Thanks.

> Not all the pods have their probe failing ^

I think it is more related to CNI plugin. Maybe you can post an issue in the calico community.

Could you give us a full log between 03:50 to 04:00?
I think `pod1_ns1` pod was deleted at 03:58 but I can't find any probe failure of `pod1_ns1` in this log.

I suspect that maybe the pod deletion was not related to probe failure.

**Comment by tarun-asthana** [comment]
Raised it with calico - https://github.com/projectcalico/calico/issues/6662

@gjkim42 sorry I won't have the full logs since node is terminated now but as per my original analysis, every pod that got killed, did have a probe failure.

**Comment by gjkim42** [comment]
Thanks for reporting this issue @tarun-asthana.
You may update your cluster to supported versions. And if this issue is reproduced again, please give us full logs of kubelet and kube-controller-manager. Also the right reproducible scenario would be very helpful for us.

For now, I think there are little things we can do as there are no remaining logs or a reproducible scenario.
As far as I confirmed, there are no critical bugs in the probe failure of the supported versions.

/triage needs-information

**Comment by caseydavenport** [comment]
Looks like both the Kubernetes and Calico version in-use here are quite old, so I agree an upgrade is probably in order. 

Connection refused suggests that this is perhaps an application error - are you certain that your application code is serving a health check at `:8081/ping`?

**Comment by SergeyKanzhelev** [comment]
@tarun-asthana can you please try the never versions as suggested and report back. Otherwise we will close the issue as lacking information. Thank you

**Comment by dcbw** [comment]
/close
Closing due to lack of info, please re-open if/when you can reply with the requested information. Thanks!
