### ISSUE TITLE
Missing kubectl version 1.15.3

### ISSUE THREAD

**Issue by RainbowHerbicides** [kubernetes/kubernetes#112315]
### What happened?

We have some pretty old Kubernetes (1.15.3) installations running in several locations which we are updating to 1.21.x. When context had been changed from new cluster to old one - right `kubectl` version were not be able to be downloaded:
```
➜  ~ kubectl get pods
I0908 11:09:54.485273   33423 versioner.go:84] Right kubectl missing, downloading version 1.15.3
F0908 11:09:54.954331   33423 main.go:69] Error while trying to get contents of https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/darwin/amd64/kubectl.sha256: GET https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/darwin/amd64/kubectl.sha256 returned http status 404 Not Found
```

Manually checking via `curl`:
```
➜  ~ curl https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/darwin/amd64/kubectl.sha256
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/v1.15.3/bin/darwin/amd64/kubectl.sha256</Details></Error>%
```

But next minor version is available:
```
➜  ~ curl https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/darwin/amd64/kubectl.sha256
45737d73d16a82a7855deb0cf1d7c9bae1315ea59b4364b95482a03cbcc965d2
```

### What did you expect to happen?

Expected to be able to download right `kubectl` version (even if its old one)

### How can we reproduce it (as minimally and precisely as possible)?

If possible - have Kubernetes cluster with a version of 1.15.3

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Baremetall
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by RainbowHerbicides** [comment]
Performed investigation and found what caused issue - `Ranched Desktop`. Looks like it tries to install most compatible (i.e major version) of `kubectl` based on information gathered from Kubernetes API  and substitute normally installed via brew `kubectl` cli. Running `kuberlr get 1.15.4` fixed that issue

**Comment by techslaves** [comment]
Tried reinstalling kubectl but nothing worked. Did `which kubectl`  which pointed to kubectl binary being used from a path `/Users/xxx/.rd/bin/kubectl` than `/usr/local/bin/kubectl`. Deleted binary from `/Users/xxx/.rd/bin/kubectl` and then updated the kubectl version using `brew install kubernetes-cli@3.31` and then issue got resolved.

`which -a kubectl ` can be used to see all path where kubectl binary exist.
