### ISSUE TITLE
kubelet should set readiness to true as soon as possible for containers without readiness probe defined 

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/kubernetes#11234]
Forked from #11007

kubelet set readiness for containers when checking container health in SyncPod. For containers that are created for the first time, the readiness of the containers would only be set in the next sync (~10s or less). This applies to containers with *NO* readiness probe defined, so that they'd stay as not ready until the next sync. Instead, kubelet could perform an extra probe right after the container creation to make sure the readiness is set correctly as soon as possible.

**Comment by yujuhong** [comment]
@vishh, I am assigning this to you since you (sort of) expressed interests in today's meeting. If you are swamped with other issues, feel free to unassign!

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by nikhiljindal** [comment]
@vishh I can take this up if you havent started working on it.
I need it for Deployment https://github.com/kubernetes/kubernetes/pull/12236.
There are a few other changes I need to make to the Ready PodCondition. I can make all of them together.

**Comment by yujuhong** [comment]
@nikhiljindal, @timstclair is working on separating probing from the kubelet sync period (#12866). You may want to coordinate with him.

**Comment by nikhiljindal** [comment]
Removing 1.1 milestone

**Comment by timstclair** [comment]
I'm not sure how this would work with a temporary readiness probe. The problem with using a readiness probe is that the probe needs to get the container ID before it can probe, and it relies on the sync loop for that (currently). Also, I think you want to declare the container Ready as soon as it's ID exists, so setting up a probe doesn't seem like the right approach.

**Comment by yujuhong** [comment]
@timstclair. we don't need to setup an actual probe, but we'd like the readiness be true if there is no probe defined. By the way, your PR which got merged today already solved this problem.

**Comment by timstclair** [comment]
Yes, if there is no probe defined it defaults to readiness (although I believe that was already true). If the container is created by the time [syncPod](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L1251) exits, it should be set to ready. Otherwise, it will still need to wait for the next syncPod execution.

**Comment by yujuhong** [comment]
> Yes, if there is no probe defined it defaults to readiness (although I believe that was already true)

This wasn't technically true until your PR landed. Before, we only probe at the beginning of SyncPod (before the container creation), and the readiness would be false for the first sync. 

> Otherwise, it will still need to wait for the next syncPod execution.

I think the scope of this issue is more towards setting readiness for pods that do not have probe defined, so I will go ahead and close this bug.

**Comment by timstclair** [comment]
Ah, got it, thanks.
