### ISSUE TITLE
"curl -sS https://get.k8s.io | bash" fails silently

### ISSUE THREAD

**Issue by sshen** [kubernetes/kubernetes#11232]
Running "curl -sS https://get.k8s.io | bash" seems to fail silently. After some debugging, it looks like get_latest_version_number is the culprit:

<pre>
  63 function get_latest_version_number {
  64   local -r latest_url="https://storage.googleapis.com/kubernetes-release/release/stable.txt"
  65   if [[ $(which wget) ]]; then
  66     wget -qO- ${latest_url}
  67   elif [[ $(which curl) ]]; then
  68     curl -Ss ${latest_url}
  69   fi
  70 }
</pre>

Line 66 fails with the following when I remove the -q (quiet) option:

<pre>
$ wget -O- https://storage.googleapis.com/kubernetes-release/release/stable.txt
--2015-07-14 11:58:06--  https://storage.googleapis.com/kubernetes-release/release/stable.txt
Resolving storage.googleapis.com... 173.194.204.128, 2607:f8b0:400d:c0a::80
Connecting to storage.googleapis.com|173.194.204.128|:443... connected.
ERROR: certificate common name “*.storage.googleapis.com” doesn’t match requested host name “storage.googleapis.com”.
To connect to storage.googleapis.com insecurely, use ‘--no-check-certificate’.

$ echo $?
5
</pre>

**Comment by erictune** [comment]
This works for me:
```
$ curl -sS  https://storage.googleapis.com/kubernetes-release/release/stable.txt
v0.21.1
```
Maybe it was a transient problem?
Are you still seeing the problem?

**Comment by erictune** [comment]
@cjcullen can you suggest someone to assign this to?

**Comment by sshen** [comment]
Yep, the curl command works for me. However, the function prefers wget if it's available, which fails on my Centos 7.0 box.

**Comment by brendandburns** [comment]
I believe this is a known bug in wget that is shipping w/ your Centos:

http://wiki.openwrt.org/doc/howto/wget-ssl-certs

I think you need to upgrade wget.

We should have a better error message, though.  Assigning to myself.

**Comment by justinsb** [comment]
Suggest closing given that:

1) kube-up is in maintenance
2) wget problem is hopefully now fixed

**Comment by justinsb** [comment]
No objection to propose closing; closing!
