### ISSUE TITLE
Kube-apiserver quickly reaches OOMKill on startup

### ISSUE THREAD

**Issue by navaati** [kubernetes/kubernetes#112376]
### What happened?

When running kube-apiserver with the options `--etcd-servers=http://localhost:2379 --service-account-issuer=kube-home-node --service-account-signing-key-file=/dev/zero --authorization-mode=Node`, it immediately starts eating all the RAM available, until it gets killed by the OOMKiller after a few seconds.

When I ran the repro test on my desktop machine, it had eaten as much as ~60GB of RAM before getting killed: `[5246499.409595] Out of memory: Killed process 3355732 (kube-apiserver) total-vm:108409836kB, anon-rss:61079828kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:120308kB oom_score_adj:200`.

See here a graph of the RAM consumption (the process is being started just after the start of the graph), this is a 128GB machine:
![image](https://user-images.githubusercontent.com/1193282/189495764-2a5eead9-58b3-483c-ac6a-63de3b2f1025.png)

### What did you expect to happen?

I would expect the apiserver to start normally, or at least log something and exit if my CLI options were not correct. I would in any case expect it to take no more than a few hundred MB of RAM.

### How can we reproduce it (as minimally and precisely as possible)?

Just run `$ podman run -m 15g registry.k8s.io/kube-apiserver:v1.25.0 kube-apiserver -v=10 --etcd-servers=http://localhost:2379 --service-account-issuer=kube-home-node --service-account-signing-key-file=/dev/zero --authorization-mode=Node` on a machine with nothing else running (no need for the etcd running at port 2379 to reproduce).

Should work with Docker instead of Podman, and you can reduce the memory limit if you don’t have that much available (or remove the memory limit altogether, but your host is not gonna like that).

I can also reproduce by downloading the binary and running it raw (no container) with:
```console
./kube-apiserver -v=10 --etcd-servers=http://localhost:2379 --service-account-issuer=kube-home-node --service-account-signing-key-file=/dev/zero --authorization-mode=Node --cert-dir=.
```

### Kubernetes version

<details>

```console
$ podman run registry.k8s.io/kube-apiserver:v1.25.0 kube-apiserver --version                                                                                                                       
2022/09/10 17:28:45 Running command:
Command env: (log-file=, also-stdout=false, redirect-stderr=true)
Run from directory: 
Executable path: /usr/local/bin/kube-apiserver
Args (comma-delimited): kube-apiserver,--version
2022/09/10 17:28:45 Now listening for interrupts
Kubernetes v1.25.0
```

</details>

### Cloud provider

N/A

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36.20220505.2.0 (CoreOS)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora CoreOS 36.20220505.2.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='36.20220505.2.0'
DEFAULT_HOSTNAME=localhost

$ uname -a
Linux fcos-test 5.17.5-300.fc36.x86_64 #1 SMP PREEMPT Thu Apr 28 15:51:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

I can reproduce on my desktop Fedora as well, kernel `5.18.10-200.fc36.x86_64`

</details>

**Comment by aojea** [comment]
The problem is that you are passing `/dev/zero` as a file and the reader  never ends, short reproducer

```go
package main

import (
	"fmt"
	"log"
	"os"
	"runtime"
	"time"
)

func main() {
	go func() {
		for i := 0; i < 5; i++ {
			printMemUsage()
			time.Sleep(1 * time.Second)
		}
		os.Exit(1)
	}()
	data, err := os.ReadFile("/dev/zero")
	if err != nil {
		log.Fatal(err)
	}
	log.Println("data len", len(data))
}

// PrintMemUsage outputs the current, total and OS memory being used. As well as the number
// of garage collection cycles completed.
func printMemUsage() {
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	// For info on each, see: https://golang.org/pkg/runtime/#MemStats
	fmt.Printf("Alloc = %v MiB", bToMb(m.Alloc))
	fmt.Printf("\tTotalAlloc = %v MiB", bToMb(m.TotalAlloc))
	fmt.Printf("\tSys = %v MiB", bToMb(m.Sys))
	fmt.Printf("\tNumGC = %v\n", m.NumGC)
}

func bToMb(b uint64) uint64 {
	return b / 1024 / 1024
}
```
you can see how the `os.Readfile` never exists and keeps allocating memory

```
go run main.go 
Alloc = 0 MiB	TotalAlloc = 0 MiB	Sys = 12 MiB	NumGC = 0
Alloc = 3847 MiB	TotalAlloc = 10686 MiB	Sys = 5927 MiB	NumGC = 33
Alloc = 7514 MiB	TotalAlloc = 20872 MiB	Sys = 8686 MiB	NumGC = 36
Alloc = 9392 MiB	TotalAlloc = 26090 MiB	Sys = 14075 MiB	NumGC = 37
Alloc = 14676 MiB	TotalAlloc = 40766 MiB	Sys = 22495 MiB	NumGC = 39
```

from golang docs https://pkg.go.dev/os#ReadFile

>ReadFile reads the named file and returns the contents. A successful call returns err == nil, not err == EOF. Because ReadFile reads the whole file, it does not treat an EOF from Read as an error to be reported.

I don't think that this is  bug, since it is working as expected, "/dev/zero  is a special file in Unix-like operating systems that provides as many null characters (ASCII NUL, 0x00) as are read from it" , so it keeps reading

**Comment by navaati** [comment]
Oh, duuuuuh, I wanted `/dev/null`, not `/dev/zero` ! I’m so sorry for the noise and thanks a lot for your time, I’m not sure I would have caught that so soon (I was already going to learn how to profile in Go…).

I agree that it’s not a bug, pure PEBCAK.

Thanks again !

**Comment by aojea** [comment]
no worries, the issue was properly described and easy to reproduce, that helps a lot, keep it up

Thanks for reporting
