### ISSUE TITLE
Unable to install Kubernetes on VPS via make command

### ISSUE THREAD

**Issue by aravindb26** [kubernetes/kubernetes#112382]
### What happened?

Hi team, hope all going well.

I have tried to install Kubernetes and build it on my VPS terminal. which has a capacity like 2 GB Memory / 60 GB Disk / BLR1 - Ubuntu 22.04 x64.

It gets stuck after we enter the command **make**

I have tried to install it for few times for successful installation

But it got stuck my total VPS like below

<img width="422" alt="make" src="https://user-images.githubusercontent.com/89305482/189538180-847a8371-4fca-4b1d-a64f-f1611e767e90.png">

### What did you expect to happen?

It should have the capacity to install in 2 GB of Memory because many small developers might have lower memory and want to test it in their environment. It gets difficult for them.

### How can we reproduce it (as minimally and precisely as possible)?

mkdir -p $GOPATH/src/k8s.io
cd $GOPATH/src/k8s.io
git clone https://github.com/kubernetes/kubernetes
cd kubernetes
make

<img width="422" alt="make" src="https://user-images.githubusercontent.com/89305482/189538308-385fe001-9bce-4a1e-9482-3db3d5f3f364.png">

## Impact: 
Here the major Impact is many small developers can't install kubernetes successfully and test your code and find bugs. 
From these, it clarifies that kubernetes developers might miss bugs that want to be found by small developers.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?```

</details>


### Cloud provider

<details>
Digital Ocean
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug

> From these, it clarifies that kubernetes developers might miss bugs that want to be found by small developers.

Agree that the kubernetes development environment demands considerable resources, but I can't see how this can be a bug ...

**Comment by aravindb26** [comment]
add kind/bug

It's a bug because it has an impact on kubernetes. Every issue which has Impact on repo or open source project it's a bug

**Comment by dims** [comment]
sorry, WONTFIX
