### ISSUE TITLE
We should include ssh tunnel health in apiserver /healthz

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#11235]
We've seen a couple cases where the SSH tunnel updater locks up and the tunnels go stale. We should set a "last refreshed" variable, and report an error in the kube-apiserver healthz handler if it is too stale.

@brendandburns

**Comment by erictune** [comment]
@cjcullen add priority and team please.

**Comment by cjcullen** [comment]
This was fixed by #11250

**Comment by cjcullen** [comment]
This was fixed by #11250
