### ISSUE TITLE
kube-controller-manager memory leak

### ISSUE THREAD

**Issue by xigang** [kubernetes/kubernetes#112319]
### What happened?

Our cluster has 5600 nodes and `kube-controller-manager` memory usage 197.5GiB, After restarting `kube-controller-manager`, the memory usage is only 15GiB,  It looks like the controller manager memory is leaking.
<img width="875" alt="image" src="https://user-images.githubusercontent.com/3377677/189124068-2e4c7867-1d36-4bb9-88f6-a3c4a5aee2bb.png">

The same problem issue: [#102718](https://github.com/kubernetes/kubernetes/issues/102718 ) and [#102565](https://github.com/kubernetes/kubernetes/pull/102565)

### What did you expect to happen?

The `kube-controller-manager` memory usage should be kept at a smooth water level.

### How can we reproduce it (as minimally and precisely as possible)?

NONE

### Anything else we need to know?

NONE

### Kubernetes version

```
Client Version: version.Info{
Major:"1", 
Minor:"17+", 
GitVersion:"v1.17.4", 
GitCommit:"f769ba94a8435eb3b446c5d39d7504823224a6f4", 
GitTreeState:"clean", 
BuildDate:"2020-06-22T02:50:15Z", 
GoVersion:"go1.14.2", 
Compiler:"gc", 
Platform:"linux/amd64"}
```

### Cloud provider

```
NONE
```

### OS version

```
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### Install tools

NONE

**Comment by xigang** [comment]
pmap command report memory map of `kube-controller-manager` process:
[controllermanager.txt](https://github.com/kubernetes/kubernetes/files/9526966/controllermanager.txt)

**Comment by aojea** [comment]
> GitVersion:"v1.17.4", 

that is an old version, you need to move to one of the supported versions.

golang pprof should give you a better understanding of the problem

**Comment by xigang** [comment]
> > GitVersion:"v1.17.4",
> 
> that is an old version, you need to move to one of the supported versions.
> 
> golang pprof should give you a better understanding of the problem
@aojea 
I understand that golang pprof will have an impact on `kube-controller-manager` service performance?

**Comment by xigang** [comment]
> > GitVersion:"v1.17.4",
> 
> that is an old version, you need to move to one of the supported versions.
> 
> golang pprof should give you a better understanding of the problem

When the memory usage of `kube-controller-manager` reaches 250GiB, `kube-controller-manager` pprof:

![image](https://user-images.githubusercontent.com/3377677/189791847-088bdf30-3cf3-4999-a80a-bb294e4313b3.png)

![image](https://user-images.githubusercontent.com/3377677/189791736-64036864-9486-4f00-af17-8d74aa5be4b7.png)

**Comment by kkkkun** [comment]
Could you provide CPU profile？ It may be usefully, @xigang

**Comment by xigang** [comment]
> Could you provide CPU profile？ It may be usefully, @xigang

@kkkkun It has not been reproduced recently. At that time, I guess that it was caused by the leak of goroutine, and checked the goroutine pprof.
![image](https://user-images.githubusercontent.com/3377677/194444865-73b03fc9-84e7-408a-b742-e5cdf99389bf.png)

**Comment by sxllwx** [comment]
I don't think this issue is related to issue https://github.com/kubernetes/kubernetes/pull/102565 issue https://github.com/kubernetes/kubernetes/issues/102718.

issue https://github.com/kubernetes/kubernetes/pull/102565 https://github.com/kubernetes/kubernetes/issues/102718 reflects the use of a lot of memory when doing ListObject.

And from the kube-controller-manager you provided, the memory-related pprof consumes a lot of memory in the Unmarshal of a separate Object (*corev1.Node).

FYI: My guess here is because a large number of Nodes in the kube cluster briefly jittered.

**Comment by sxllwx** [comment]
emm,,, did this use of a lot of memory go on for a long time?

**Comment by xigang** [comment]
> did this use of a lot of memory go on for a long time?

This problem lasted for a few days and currently the average cluster `kube-controller-manager` memory usage is 32Gi

**Comment by sxllwx** [comment]
@xigang 

According to the information provided so far (heap-pprof inuse_space):

We can draw the following conclusions:

1. The memory usage of 2.77GB comes from `List`: #102718 #113305 Reports the memory usage problem of reflector (client-go) when performing List operations
2. The memory usage of 135.14GB comes from `Watch`, of which 129.88GB is used for Node.Unmarshal.

> Compared with 2.77GB, I think the memory consumption of 135.14GB should be more concerned.

I noticed that the version of golang used by kube-controller-manager is: `GoVersion:"go1.14.2"` go1.16 (included) and later versions changed an option to free memory from the previously used `MADV_FREE` Modify the difference between the two parameters of `MADV_DONTNEED`, I suggest you refer to: https://github.com/golang/go/issues/42894


Suggest: 
- Upgrade the version of kubernetes itself to introduce this change
- If it is really impossible to upgrade in a short time, you can try to set the environment variable `GODEBUG=madvdontneed=1` to modify the default memory management behavior of go1.14.2. Then go ahead and see if that fixes your problem.

**Comment by xigang** [comment]
@sxllwx Thank you very much，the memory usage of `kube-controller-manager` is normal now. and the k8s cluster version may not be upgraded in a short time. If the memory usage of `kube-controller-manager` is abnormal, we will try to use the second suggest.

**Comment by xigang** [comment]
remark

**Comment by xigang** [comment]
> > @sxllwx Thank you very much, the memory usage of `kube-controller-manager` is normal now, but it is not clear what triggers the `kube-controller-manager` memory increase. The k8s cluster version may not be upgraded in a short time. If the memory usage of `kube-controller-manager` is abnormal, we will try to use the second suggest.
> 
> Hi @xigang , I am interest in this prombel. What have you done before it become normal?

@lowang-bh The daemonset controller processed Node events slowly, triggering the OOM. We made some optimization.
See: https://github.com/kubernetes/kubernetes/issues/121474

**Comment by sxllwx** [comment]
> If it is really impossible to upgrade in a short time, you can try to set the environment variable GODEBUG=madvdontneed=1 to modify the default memory management behavior of go1.14.2. Then go ahead and see if that fixes your problem.

Have you currently adopted this advice I gave?

**Comment by xigang** [comment]
> Have you currently adopted this advice I gave

These policies are not currently being adjusted.
