### ISSUE TITLE
@249043822 , thank you for the PR for fixing the issue! Do you think it is easy to add some sort of unit test about the behavior?

### ISSUE THREAD

**Issue by feroenmmek** [kubernetes/kubernetes#112369]
@249043822 , thank you for the PR for fixing the issue! Do you think it is easy to add some sort of unit test about the behavior?

_Originally posted by @jingxu97 in https://github.com/kubernetes/kubernetes/issues/111205#issuecomment-1202047929_

**Comment by MadhavJivrajani** [comment]
/close
I'm assuming this was creating accidentally? Please feel free to reopen it if that's not the case, thanks!
