### ISSUE TITLE
Pod annotation pass to the container runtime by CreateSandbox interface

### ISSUE THREAD

**Issue by soulseen** [kubernetes/kubernetes#112311]
### What happened?

I modified the containerd to do some additional operations on the container based on the Pod annotation, but actually, looking at the containerd logs, I found that the Pod annotation is passed to the containerd in the `Create SandBox` interface, not in the `Create Container` interface.
I'm not sure if this is the expected behavior? And why it is only pass annotation  to `Create SandBox` interface?
Also, the [Annotation](https://github.com/kubernetes/kubernetes/blob/3ffdfbe286ebcea5d75617da6accaf67f815e0cf/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.pb.go#L878) returned from `device plugin` are pass to container, not sandbox. I think whatever the annotation get from(Pod or Device plugin), it shoudl be consistent.

### What did you expect to happen?

1. Why does Pod annotation only pass to the `Create Sandbox` interface? 
2. Why does the [Annotation](https://github.com/kubernetes/kubernetes/blob/3ffdfbe286ebcea5d75617da6accaf67f815e0cf/staging/src/k8s.io/kubelet/pkg/apis/deviceplugin/v1beta1/api.pb.go#L878) returned from device plugin only pass to the `Create Container` interface?

I think they should be kept consistent.

### How can we reproduce it (as minimally and precisely as possible)?

1. enable containerd debug log.
2. create a Pod with some Annotations
4. fill found annotation only pass to Sandbox

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

k8s

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
I am not sure if I understand correctly. 
https://github.com/containerd/containerd/blob/b170eb3caca52649545ce0fc65fa31241739db9d/vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go#L1306-L1308

> 	// In general, in order to preserve a well-defined interface between the
> 	// kubelet and the container runtime, annotations SHOULD NOT influence
> 	// runtime behaviour.

**Comment by soulseen** [comment]
@pacoxu thank you for your reply, you understand correctly. 
But anyway, I think the `Annotation` of the sandbox and biz containers should be consistent, whether the `Annotation` come from pod-defined or device plugin.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

I think it is more like a feature request. I remember there were discussions not to pass annotations at all to limit cases when there is too much dependency on specific annotations in code.

Let's discuss/document and make it a bug if it will be identified as such

/assign
