### ISSUE TITLE
kubelet doesn't merge multiple 'options' lines from node /etc/resolv.conf

### ISSUE THREAD

**Issue by haosdent** [kubernetes/kubernetes#112323]
### What happened?

If the content of `/etc/resolv.conf` is 
```
options timeout:1 
options attempts:3
```
https://github.com/kubernetes/kubernetes/blob/ca09ed0fe2c245a0df4f533aa29f7b48a8672cff/pkg/kubelet/network/dns/dns.go#L250-L278

only could recognize the last option `options attempts:3` and `options timeout:1` is ignored. And user has to use `options timeout:1 attempts:3` to workaround the issue.

But this format is valid actually and able to read correctly in golang and libc.

### What did you expect to happen?

Able to parse multiple options lines in `/etc/resolv.conf` correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Use 
```
options timeout:1 
options attempts:3
```
in the host's `/etc/resolv.conf` file and then inside POD's `/etc/resolv.conf`, it would become
```
options attempts:3
```

### Kubernetes version

Any version.

### Cloud provider

N.A.

### OS version

Ubuntu 22.04

**Comment by haosdent** [comment]
@thockin Seems this behaviour is introduced by you at https://github.com/kubernetes/kubernetes/pull/2224 , is it an expected behaviour or a bug?

**Comment by aojea** [comment]
are those options parsed and used correctly or one of both is ignored?

**Comment by haosdent** [comment]
> are those options parsed and used correctly or one of both is ignored?

Others are ignored and online the last line is parsed by kubelet correctly. @aojea

**Comment by aojea** [comment]
and in a normal resolv.conf, does libc use all the options or ignore some and use only one?

**Comment by pacoxu** [comment]
I tried centos/ubuntu, both will use append extra options and overwrite it if it already exists by the later settings.

For instance,
```
options ndots:5
options timeout:1 attempts:3
options ndots:2 attempts:5
```
is the same as `options ndots:2 timeout:1  attempts:5`.


But I still think the workaround looks a perfered format. 
```
options timeout:1 attempts:3
```

**Comment by haosdent** [comment]
Yes, but it looks like a bug since kubelet's behavior is different. @pacoxu

**Comment by pacoxu** [comment]
I tried to fix it in https://github.com/kubernetes/kubernetes/pull/112414. But I am still not sure if this is a valid fix. I will wait for pr review comments or further confirmation about whether this is valid.

**Comment by pacoxu** [comment]
The feature was added by #54773 a long time ago by @phsiao following the design kubernetes/community#1276.

The KEP can be found in KEP https://github.com/kubernetes/enhancements/issues/504.

**Comment by aojea** [comment]
Previous discussion and interesting comment from @thockin 
https://github.com/kubernetes/kubernetes/pull/91052#issuecomment-629557368

**Comment by phsiao** [comment]
> The feature was added by https://github.com/kubernetes/kubernetes/pull/54773 a long time ago by @phsiao following the design https://github.com/kubernetes/community/pull/1276.

Just want to clarify that these two are not related --- the change does not follow the design.

**Comment by pacoxu** [comment]
> Previous discussion and interesting comment from @thockin [#91052 (comment)](https://github.com/kubernetes/kubernetes/pull/91052#issuecomment-629557368)

Just have the book on my desktop. 😄
![image](https://user-images.githubusercontent.com/2010320/190302910-ba88c003-a23b-4da8-aa05-525581510aff.png)

**Comment by haosdent** [comment]
@phsiao @pacoxu @thockin I think the book just said could write it as `options option_a option_b`, but didn't mention 
```
options option_a
options option_b
```
is invalid. And since glibc/golang DNS resolve is able to recognize it correctly, should we consider it as a de-facto way that we should support?

**Comment by aojea** [comment]
what about muslc, does it support it?
we have to support muslc too, a lot of busybox/alpine users can break

**Comment by pacoxu** [comment]
I did some initial test.
```
/ # ping kubernetes
PING kubernetes (10.96.0.1): 56 data bytes
^C
--- kubernetes ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
/ # ping kubernetes.default
PING kubernetes.default (10.96.0.1): 56 data bytes
^C
--- kubernetes.default ping statistics ---
1 packets transmitted, 0 packets received, 100% packet loss
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:1
options attempts:3 ndots:3 debug
```
for `ndot:3`, it works with multi-options.
```
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:3
options attempts:3 debug
/ # ping kubernetes.default
PING kubernetes.default (10.96.0.1): 56 data bytes
^C
--- kubernetes.default ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss
```
ndots:1, ping will fail for `bad address`.
```
/ # cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:1
options attempts:3 debug
/ # ping kubernetes.default
ping: bad address 'kubernetes.default'
```

**Comment by aojea** [comment]
I'm trying to understand this, how the options are merged if they are duplicated?

the man page for `search` is clear https://man7.org/linux/man-pages/man5/resolv.conf.5.html#:~:text=The%20different%20configuration%20options%20are,notation%20as%20per%20RFC%202373.

>             If there are multiple search directives, only the search
>             list from the last instance is used.

for `options` only says

>     The options keyword of a system's resolv.conf file can be amended
>        on a per-process basis by setting the environment variable
>        RES_OPTIONS to a space-separated list of resolver options as
>        explained above under options.

it seems that apply the same logic to handle conflict if I try with this only the last option is used (same for muslc and libc)

```
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.96.0.10
options ndots:1
options ndots:3
```

if I have two different options in different lines then things start to get more complicated, because I can not test all possible options combinations and musl resolver is not compatible with glibc resolver , see https://wiki.musl-libc.org/functional-differences-from-glibc.html#Name-Resolver/DNS

I'm worried we can break musl based containers by assuming the host configuration that is mostly libc based , will be compatible.

I think we should be conservative and documents this behavior with options and ask users to merge the options in the same line, raise a warning of something too

**Comment by pacoxu** [comment]
> I think we should be conservative and document this behavior of the dns options, and ask users to merge the options in the same line, raise a warning of something too

Add a small warning in log maybe another option. We may document it with some details.


> I see @pacoxu is suggesting to parse all options and merge them in one line :eyes: 

This is a little aggressive way.

**Comment by thockin** [comment]
I still can't find any spec that says how this is SUPPOSED to work, and I share @aojea's concerns that this is likely to break someone somewhere.

Did someone encounter this in the wild?  Does it REALLY make sense to copy ALL of the options from the host config?  Does it make sense to copy ANY of them?  Looking at the man page, they seem very specific and maybe we should just leave them alone.

What does Docker do here?

**Comment by pacoxu** [comment]
> Did someone encounter this in the wild? Does it REALLY make sense to copy ALL of the options from the host config? Does it make sense to copy ANY of them? Looking at the man page, they seem very specific and maybe we should just leave them alone.

I found that there is a logic to merging DNS options in the pod DNS spec generating process. So I followed the logic.

If the pod is using `dnsPolicy:Default` with `dnsConfig.options`, the current kubelet will merge the node's last option line in `/etc/resolv.conf` with `dnsConfig.options`.

https://github.com/kubernetes/kubernetes/blob/127f33f63d118d8d61bebaba2a240c60f71c824a/pkg/kubelet/network/dns/dns.go#L325-L353


> What does Docker do here?

I did a simple test in Centos 7.9 with docker 19.03.8 like below. 
1. It keeps the options as is if no new DNS options.
2. The `--dns-opt` will overwrite the local DNS options.
3. If there are multi `--dns-opt`, docker will not merge them and keep them in one line.
```
[root@peter-jenkins-11 ~]# cat /etc/resolv.conf
nameserver 192.168.1.29
nameserver 114.114.114.114
### paco edited
options timeout:1
options ndots:3

[root@peter-jenkins-11 ~]# docker run -it docker.m.daocloud.io/library/ubuntu:16.04 cat /etc/resolv.conf
nameserver 192.168.1.29
nameserver 114.114.114.114
### paco edited
options timeout:1
options ndots:3
root@a7ca807c158e:/# exit

[root@peter-jenkins-11 ~]# docker run  --dns-opt=timeout:2 -it docker.m.daocloud.io/library/ubuntu:16.04 cat /etc/resolv.conf
nameserver 192.168.1.29
nameserver 114.114.114.114
options timeout:2

[root@peter-jenkins-11 ~]# docker run  --dns-opt=timeout:2 --dns-opt=timeout:2 --dns-opt=ndots:3 -it docker.m.daocloud.io/library/ubuntu:16.04 cat /etc/resolv.conf
nameserver 192.168.1.29
nameserver 114.114.114.114
options timeout:2 timeout:2 ndots:3

```

**Comment by thockin** [comment]
Absent a real user who is really impacted by this, my inclination is to (again) do nothing.  The risk of breakage is non-zero.  The reward is zero (nobody is complaining, IIUC).

**Comment by haosdent** [comment]
> Absent a real user who is really impacted by this

Hi, @thockin  actually I am impacted by this (in production services) 😂. And looks like I am not the first user who raise this, as other issues link to this thread.

**Comment by haosdent** [comment]
> what about muslc, does it support it?
> we have to support muslc too, a lot of busybox/alpine users can break

@aojea Thanks for your input, I checked muslc and verified via code, muslc would parse all options if we write multiple line `options`.
https://github.com/kraj/musl/blob/master/src/network/resolvconf.c#L41-L61

```
	while (fgets(line, sizeof line, f)) {
		char *p, *z;
		if (!strchr(line, '\n') && !feof(f)) {
			/* Ignore lines that get truncated rather than
			 * potentially misinterpreting them. */
			int c;
			do c = getc(f);
			while (c != '\n' && c != EOF);
			continue;
		}
		if (!strncmp(line, "options", 7) && isspace(line[7])) {
			p = strstr(line, "ndots:");
			if (p && isdigit(p[6])) {
				p += 6;
				unsigned long x = strtoul(p, &z, 10);
				if (z != p) conf->ndots = x > 15 ? 15 : x;
			}
			p = strstr(line, "attempts:");
			if (p && isdigit(p[9])) {
				p += 9;
				unsigned long x = strtoul(p, &z, 10);
				if (z != p) conf->attempts = x > 10 ? 10 : x;
			}
			p = strstr(line, "timeout:");
			if (p && (isdigit(p[8]) || p[8]=='.')) {
				p += 8;
				unsigned long x = strtoul(p, &z, 10);
				if (z != p) conf->timeout = x > 60 ? 60 : x;
			}
			continue;
		}
```

**Comment by thockin** [comment]
OK. I am accepting it.  Since libc's seem to do this anyway, I don't see why we should break it.

**Comment by haosdent** [comment]
Many thanks @thockin
