### ISSUE TITLE
CSI `NodeStageVolume` called multiple times for same attached volume on same node

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/kubernetes#112343]
### What happened?

-  For raw block CSI volumes on Kubernetes, kubelet ends up calling CSI `NodeStageVolume` for every single "map" (i.e. raw block "mount") operation for a volume already attached to the node.

### What did you expect to happen?

[Per CSI spec](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodestagevolume), `NodeStageVolume` should be called once per volume per node:
* More specifically, `This RPC SHOULD be called by the CO when a workload that wants to use the specified volume is placed (scheduled) on the specified node for the first time or for the first time since a NodeUnstageVolume call for the specified volume was called and returned success on that node`.

### How can we reproduce it (as minimally and precisely as possible)?

* Create a raw block PVC for a CSI driver
* Create a pod using that PVC
* Create another pod using the same PVC and schedule to the same node
* Kubelet logs will show multiple `blockMapper.stageVolumeForBlock successfully requested NodeStageVolume` for the same PVC.

Example log:

```
Sep 08 23:27:49 node1 kubelet[2820769]: I0908 23:27:49.078408 2820769 csi_block.go:203] kubernetes.io/csi: blockMapper.stageVolumeForBlock successfully requested NodeStageVolume [/var/lib/kubelet/plugins/
kubernetes.io/csi/volumeDevices/staging/pvc-41f58b43-a3eb-4170-a116-98b301a28a67]
...
Sep 08 23:32:54 node1 kubelet[2820769]: I0908 23:32:54.310885 2820769 csi_block.go:203] kubernetes.io/csi: blockMapper.stageVolumeForBlock successfully requested NodeStageVolume [/var/lib/kubelet/plugins/
kubernetes.io/csi/volumeDevices/staging/pvc-41f58b43-a3eb-4170-a116-98b301a28a67]
```

### Anything else we need to know?

Problem appears to be here:

https://github.com/kubernetes/kubernetes/blob/a7936658baba02e3ee73324ffe670559f03c188a/pkg/volume/util/operationexecutor/operation_generator.go#L1117-L1119

This should first check if "volume is globally mounted" before executing `SetUpDevice`. Does anyone know why we don't? 

For example, if you look a the equivalent code for file-on-block, it does the `DeviceGloballyMounted` check:
https://github.com/kubernetes/kubernetes/blob/a7936658baba02e3ee73324ffe670559f03c188a/pkg/volume/util/operationexecutor/operation_generator.go#L634

CC @mkimuram @vladimirvivien @msau42 @jsafrane @gnufied 

### Kubernetes version

Repro'd on Kubernetes v1.23.5

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CSI general (not specific to any driver)

**Comment by saad-ali** [comment]
CC @xiesheng211 -- thanks for your help

**Comment by akankshakumari393** [comment]
Hey Can I take a stab on it. I would like to work on this. Once this is `triaged`

**Comment by jingxu97** [comment]
I think the reasoning above from @saad-ali is right. I traced the origin code is from here https://github.com/kubernetes/kubernetes/commit/8903e8cd857a725cf43dfd6710bb740413105479. At that time both file and block will call MountDevice repeatedly without checking GetDeviceMountState from actual state.
Later there is a fix https://github.com/kubernetes/kubernetes/commit/6060c57ba3a944bd133968fd669980c97af846c6 to check the state, but it only put for file volume, not the block. So I think we should do the same for block here.

@jsafrane WDYT?

**Comment by jsafrane** [comment]
Yes, NodeStage should be ideally called only once.

**Comment by akankshakumari393** [comment]
Hey Can I work on it? I think this is a `good-first-issue` cc @jsafrane @jingxu97 @saad-ali

**Comment by jingxu97** [comment]
Yes @akankshakumari393 please go ahead. We can help review.

**Comment by saad-ali** [comment]
Thanks @akankshakumari393
