### ISSUE TITLE
PVC with mode WaitForFirstConsumer may have error selected-node

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes/kubernetes#112347]
### What happened?

A pod created by statefulSet requiring a pvc with delay binding was preempted by other pods. Then it is scheduled to another  node which is different from the `selected-node` in pvc's annotation.

### What did you expect to happen?

PVC's `selected-node` should be updated or removed when pod requiring it is scheduled to other nodes.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod requring PVC, create a Pod with higher priority and resource is not enough, then new nodes are scaled up by cluster autoscaler.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.22.10
</details>

### Cloud provider

<details>
alibaba cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pavanchavan16** [comment]
https://stackoverflow.com/questions/55044486/waitforfirstconsumer-persistentvolumeclaim-waiting-for-first-consumer-to-be-crea I have seen this issue on stackoverflow and I thing this is right answer.

**Comment by shubhamrathod27** [comment]
https://stackoverflow.com/questions/55044486/waitforfirstconsumer-persistentvolumeclaim-waiting-for-first-consumer-to-be-crea 
*****i think this is the right answer******
may be this can help you sort this issue

**Comment by msau42** [comment]
@cwdsuzhou can you clarify if the PVC was already bound when it was pre-empted?

The `selected-node` annotation is only used as a hint when provisioning. Once it is provisioned, the annotation is not used anymore.

**Comment by cwdsuzhou** [comment]
> Once it is provisioned, the annotation is not used

Thanks, PVC is is bound. I would like this annotations can be updated or removed if possible when pod is preempted.
