### ISSUE TITLE
Socket not always closing when Pod terminated (reproduce on 1.23, but not on 1.24)

### ISSUE THREAD

**Issue by eduardobr** [kubernetes/kubernetes#112300]
### What happened?

After upgrading from Kubernetes 1.22.6 to 1.23.8 (AKS), I've noticed abnormal behavior where application connected to Pod (ClusterIP) doesn't always see socket closing immediately when Pod is terminated (Redis in this case).
This was seen for traffic within cluster.

I have recorded simple videos trying to isolate the issue as much as possible, here using Microk8s on my laptop, one for 1.23 and one for 1.24.
For 1.23 it gets stuck on TCP connection already on second attempt. In practice it happens very often.
Depending on application, especially for long lasting connections, this can be very serious as it will take a very long time to detect the termination, sometimes minutes.
In 1.24 I don't see this behavior, so something has been fixed apparently.

EDIT: also broken in 1.23 when using Pod IP directly instead of ClusterIP.

### What did you expect to happen?

Socket always closed immediately when pod terminated, if fix was done for 1.24, Kubernetes 1.23 should be patched.

### How can we reproduce it (as minimally and precisely as possible)?

Videos contain full setup of Kubernetes for better context

Correct behavior:
1.24.3: https://youtu.be/4ldvCGNh8BE (skip to 2:20 for actual reproduction of behavior)

Wrong behavior:
1.23.9: https://youtu.be/bdpl7IeC6zo (skip to 2:15 for actual reproduction of issue)

### Kubernetes version

<details>

When 1.23
```console
$ kubectl version
# WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.9-2+88a2c6a14e7008", GitCommit:"88a2c6a14e7008ae9577b448c50091f44b6be572", GitTreeState:"clean", BuildDate:"2022-07-13T18:05:30Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

When 1.24
```console
$ kubectl version
# WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.3-2+63243a96d1c393", GitCommit:"63243a96d1c3932c704cf0625f5834411bc3b2e6", GitTreeState:"clean", BuildDate:"2022-07-19T17:57:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
# Linux mypcname 5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
what container runtime is being used? Is it the same in both cases?

Also do can you please attach kubelet and container runtime logs if available to see if there were some delay in tearing the sandbox down.

**Comment by eduardobr** [comment]
@SergeyKanzhelev 
Container runtime version for both: `containerd://1.5.13`

See logs here:
[logs.zip](https://github.com/kubernetes/kubernetes/files/9569545/logs.zip)
This is an execution I did today with 1.23.10.

You will see 3 deletions of the pod (done just with `kubectl delete pod myredis-master-0`)

First 2 deletions didn't cause trouble terminating pod, the 3rd deletion caused.

Let me know if you need more logs.
