### ISSUE TITLE
kubeadm config images pull failed on Ubuntu 20.04

### ISSUE THREAD

**Issue by itshabis1** [kubernetes/kubernetes#112464]
Dear
When I try to pull the image with command "sudo kubeadm config images pull"
I got following error. Can anybody help me in it. Also I am new in Kubernetes. So guide me step by step :)

I0915 10:09:10.441007   70082 version.go:182] fetching Kubernetes version from URL: https://dl.k8s.io/release/stable-1.20.txt
exit status 1
output: E0915 10:09:11.295012   70114 remote_image.go:238] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.20.15\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.20.15\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.20.15\": dial tcp 142.251.5.82:443: connect: connection refused" image="k8s.gcr.io/kube-apiserver:v1.20.15"
time="2022-09-15T10:09:11+04:30" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"k8s.gcr.io/kube-apiserver:v1.20.15\": failed to resolve reference \"k8s.gcr.io/kube-apiserver:v1.20.15\": failed to do request: Head \"https://k8s.gcr.io/v2/kube-apiserver/manifests/v1.20.15\": dial tcp 142.251.5.82:443: connect: connection refused"
, error
k8s.io/kubernetes/cmd/kubeadm/app/util/runtime.(*CRIRuntime).PullImage
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/runtime/runtime.go:167
k8s.io/kubernetes/cmd/kubeadm/app/cmd.PullControlPlaneImages
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:405
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdConfigImagesPull.func1
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:377
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:850
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374

**Comment by neolit123** [comment]
please see

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
