### ISSUE TITLE
Document Kubernetes approach to Go versions in release branches

### ISSUE THREAD

**Issue by micahhausler** [kubernetes/kubernetes#112408]
### What would you like to be added?

I'd like Kubernetes to state the position on updating the Go language version used for release branches.

### Why is this needed?

I couldn't find a publicly stated Kubernetes policy around Go version updates for release branches documented anywhere. Right now, Kubernetes maintains releases for a year, but doesn't appear to update the Go version.  Go makes new releases 2x/year and supports only 2 releases. If a Kubernetes version (such as v1.23) stays on the same Go release (as it does with Go 1.17) for the whole release's lifetime, it will enter a period where the version of Go being used is no longer supported with CVE updates. This is presently the case where Go 1.17 received security releases on 2022-08-01 but didn't on 2022-09-06 when go1.18.6 and go1.19.1 were released.

**Comment by liggitt** [comment]
We don't currently update go minor versions on release branches, largely because we don't yet have a way to mitigate the variety of changes / risks that come with minor go version updates

Each go version brings different types of changes, but minor version go updates in the past have brought a mix of:
* large behavior changes in the stdlib (e.g. http/2 by default in go1.16)
* large changes in our build/release setup (e.g. go modules in go1.13)
* backwards incompatible changes in stdlib (e.g. dropping x509 CN support and ParseIP changes in go1.17, dropping x509 SHA-1 support in go1.18)
* runtime behavior changes (e.g. GC changes in go1.18 that could dramatically change the time/space tradeoff in large API servers without GOGC tuning)

Sometimes those changes had opt-out GODEBUG flags, sometimes they didn't.

I'm actually looking at ways to enable bumping go minor versions on release branches with some combination of 1) golang committing to support compatibility switches to get behavior matching a previous go minor version for some (small) number of releases, and 2) a way to opt binaries we build in release branches into that compatible behavior without making consumers fiddle with GODEBUG envvars. That said, the _earliest_ I'd anticipate changes in that direction are go1.20 / kubernetes 1.27.

**Comment by aojea** [comment]
> his is presently the case where Go 1.17 received security releases on 2022-08-01 but didn't on 2022-09-06 when go1.18.6 and go1.19.1 were released.

this was also highlighted as one of the problems of extending releases cycles, how do you support a kubernetes versions with an unsupported go version?

**Comment by ritazh** [comment]
Would it make sense for the Kubernetes community to maintain a fork of Go specifically for the CVEs? This would make sense for the overall security posture of Kubernetes. Otherwise, all k8s downstreams would end up having to maintain their own forks.

**Comment by liggitt** [comment]
I'm a really strong -1 on Kubernetes taking on ownership of a go fork. I don't think we have the capacity or expertise to do so. I would much rather see the go project make it possible for consumers like Kubernetes to pick up new go minor versions in a less disruptive way.

**Comment by danbudris** [comment]
For what it's worth, EKS is exploring what it takes to maintain a set of out-of-support Go versions with backports of upstream CVE fixes for the purposes of maintaining older Kubernetes versions and Kubernetes ecosystem components. I'm interested in collaborating on this effort.

**Comment by micahhausler** [comment]
> I'm a really strong -1 on Kubernetes taking on ownership of a go fork. I don't think we have the capacity or expertise to do so. I would much rather see the go project make it possible for consumers like Kubernetes to pick up new go minor versions on our release branches in a less disruptive way.

I agree that improvements in the Go project would greatly help here, but from my understanding that is at best a few K8s releases away. That leaves Kubernetes with supporting release branches for the next year or two with unsupported Go versions. What is the K8s community/distributors to do in the meantime besides backport patches?

**Comment by indrora** [comment]
@liggitt Since Go officially supports release Current and Current-1 (e.g. go1.19 and go1.18), would it make sense for the K8s team to continuously support Current-1 as their "Target" with the next release having some focus on Current go.

Given that Kubernetes is likely the largest user of Go (modulo the various services that get run on top of it like Traefik, Caddy, coredns, etc.) would it also make sense for (and I'm taking a step back with my finger on my nose here) k8s to have a SIG specifically to address "changes in Go that might affect k8s". 

I suggest this not because I want to bind k8s and go very tightly, but that k8s touches a *wide* number of places in the Go standard library, as well as occasional spaces outside of it. At a fundamental level, I'm sure the Go team would be amenable to a community portion who help validate that the choices they're making that are possibly breaking (e.g. x509 in stdlib getting the axe) are done with a certain amount of grace.

**Comment by enj** [comment]
cc @kubernetes/security-response-committee

**Comment by liggitt** [comment]
For reference, https://github.com/golang/go/discussions/55090 got opened to discuss possible improvements on the golang side

**Comment by micahhausler** [comment]
There have been a few hallway conversations at the KubeCon Contributor's Summit today about this topic. The direction for backward compatibility discussed in golang/go#55090 is very encouraging, but at best there might be changes in the next Go release (1.20 in ~Feb 2023), which might get picked up by Kubernetes 1.27 (~April 2023) or 1.28 (~Aug 2023). 

With no changes that would leave the oldest maintained upstream Kubernetes releases unprotected from Go CVEs for the next 18-22 months. I don't think it is a good look for Kubernetes to shrug that off and say the status quo is ok because the preferred technical solution will be available once a cluster is running v1.27 or 1.28+. 

As @danbudris called out, [Amazon EKS Distro is now backporting Go CVE fixes](https://github.com/aws/eks-distro-build-tooling/tree/main/projects/golang/go) which will be used to build [Kubernetes versions AWS supports](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) in the very near future. This is out of necessity. We would really like to collaborate on this with anyone else who is interested. It is a time-bound problem (~2ys), but still one that needs solving.

I'd like to hear more about why Kubernetes is not the right place to collaborate on this, and if not where a better forum might be. 

cc @enj @ritazh @puja108

**Comment by liggitt** [comment]
> There have been a few hallway conversations at the KubeCon Contributor's Summit today about this topic. The direction for backward compatibility discussed in [golang/go#55090](https://github.com/golang/go/discussions/55090) is very encouraging, but at best there might be changes in the next Go release (1.20 in ~Feb 2023), which might get picked up by Kubernetes 1.27 (~April 2023) or 1.28 (~Aug 2023).

Kubernetes 1.28 is the more likely release to be able to start using the `go.mod`-enabled compatibility behavior discussed in https://github.com/golang/go/discussions/55090

If `//go:debug`-enabled compatibility behavior described in https://github.com/golang/go/discussions/55090 works like I expect, older Kubernetes versions should be able to use that to update to the latest go version at that point as well.

> With no changes that would leave the oldest maintained upstream Kubernetes releases unprotected from Go CVEs for the next 18-22 months. I don't think it is a good look for Kubernetes to shrug that off and say the status quo is ok because the preferred technical solution will be available once a cluster is running v1.27 or 1.28+.

If we can update supported versions with `//go:debug` settings around August 2023, this would be more like ~10 months, but the overall point is well taken.

> As @danbudris called out, [Amazon EKS Distro is now backporting Go CVE fixes](https://github.com/aws/eks-distro-build-tooling/tree/main/projects/golang/go) which will be used to build [Kubernetes versions AWS supports](https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-release-calendar) in the very near future. This is out of necessity. We would really like to collaborate on this with anyone else who is interested. It is a time-bound problem (~2ys), but still one that needs solving.

I _really_ don't think switching the project to unofficial go releases is a good idea. In addition to questions about whether security fixes backport cleanly/correctly, and losing the benefit of running the same bits as the rest of the go ecosystem, even answering the question "is this build / go version impacted by issue X" gets confusing for humans and scanners to answer if the official CVE → go version mapping is no longer accurate.

While it has not been *generally* safe to update release branches to newer minors in the past (the list at https://github.com/kubernetes/kubernetes/issues/112408#issuecomment-1244574606 still holds), if we're looking for time-bounded ways to keep currently supported Kubernetes versions on supported go versions until https://github.com/golang/go/discussions/55090 is available, I'd much rather work with the go project to get Kubernetes 1.23/1.24 safely onto go1.19 (updating from go1.17/go1.18 → go1.19).

A quick sweep turned up only three runtime issues between those versions, two of which look like we could currently mitigate transparently:
* go1.18 changed GC in ways that increased memory use ~25% over go1.17 in some servers (required GOGC envvar tuning to get go1.17-equivalent behavior, xref https://github.com/kubernetes/kubernetes/issues/108357#issuecomment-1056901991)
  * transparent Kubernetes mitigation: call runtime.SetGCPercent(63) in release-1.23 `main()` if GOGC envvar is unset
* go1.18 made sha1 support opt-in via GODEBUG envvar
  * no transparent Kubernetes mitigation; this is captured in a package var at [init time](https://github.com/golang/go/blob/release-branch.go1.19/src/crypto/x509/x509.go#L731-L732), so the main package can't influence it; consumers would have to set the GODEBUG envvar themselves; a go change to make this lazy-loading would let us set this in process for release-1.23
* go1.19 returns errors from Command/LookPath for current directory binaries
  * transparent Kubernetes mitigation: suppress ErrDot in release-1.23 and release-1.24 [as we did in release-1.25](https://github.com/kubernetes/kubernetes/pull/111254/commits/1f557035e053e2f604b228815241d59123f9915c)

**Comment by danbudris** [comment]
> While it has not been generally safe to update release branches to newer minors in the past (the list at https://github.com/kubernetes/kubernetes/issues/112408#issuecomment-1244574606 still holds), if we're looking for time-bounded ways to keep currently supported Kubernetes versions on supported go versions until https://github.com/golang/go/discussions/55090 is available, I'd much rather work with the go project to get Kubernetes 1.23/1.24 safely onto go1.19 (updating from go1.17/go1.18 → go1.19), which will be supported until ~August 2023, when I'm hopeful https://github.com/golang/go/discussions/55090 will be available to rely on.

One thing to call out, is that the problem we're working to address through our [builds of EKS Go](https://github.com/aws/eks-distro-build-tooling/tree/main/projects/golang/go) is not just pertaining to maintained release branches, but the extended longer-term support of Kubernetes beyond the currently supported release branches -- EKS Distro currently supports Kubernetes 1.20, 1.21, 1.22 and 1.23. This extended support does not, in our analysis, lend itself well to the solution of bumping Go minor versions when we maybe pushing across 3 minor versions, and accommodating for all the changes between, say, Go 1.15 (k8s 1.20) and Go 1.18 (closest supported Go minor version). Given the tooling and systems available, we're better able to test and validate fixes to Go then n+2 bumps to the K8s Golang minor version.
 
>  answering the question "is this build / go version impacted by issue X" gets confusing for humans and scanners to answer if the official CVE → go version mapping is no longer accurate.

This is a real issue. We're tossing around a few solutions, including modifying the Go version itself, and/or including a VEX document or SBOM entry which links to the requisite backports in the source code. But I'm open to ideas.

**Comment by liggitt** [comment]
To give an update here, the experiment in https://github.com/kubernetes/kubernetes/issues/112408#issuecomment-1291152712 panned out, and we were able to update release-1.23 and release-1.24 branches to go1.19.x.

That means as of the January patch releases, all OSS-supported Kubernetes releases are on the latest supported go minor version 🎉 

I'm planning to open a KEP in the next week to propose a regular process for updating release branches to new go minor versions after gaining soak/confidence in master / latest released minor version, and will cross-link this issue there.

**Comment by liggitt** [comment]
I opened https://github.com/kubernetes/enhancements/issues/3744 / https://github.com/kubernetes/enhancements/pull/3749 proposing a regular update of release branches to new go minor versions.

**Comment by MadhavJivrajani** [comment]
I'd consider this issue as "completed" rather than not-planned.
The documentation for Go versions can be found as part of https://github.com/kubernetes/enhancements/issues/3744
