### ISSUE TITLE
apiextensions: SchemaHas performs excessive allocations

### ISSUE THREAD

**Issue by ncdc** [kubernetes/kubernetes#112428]
In https://github.com/kubernetes/kubernetes/blob/084a412e03816ef3ea57da928ae8fd332d17ab59/staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/validation/validation.go#L1366

it has multiple `for` loops that look similar to this:

```go
for _, s := range s.AllOf {
		if SchemaHas(&s, pred) {
			return true
		}
	}
```

where `s.AllOf` is of type `[]JSONSchemaProps`. By using this range format, it creates a shallow copy of each element in the slice. We can eliminate this allocation by changing to this format:

```go
for i := range s.AllOf {
		if SchemaHas(&s.AllOf[i], pred) {
			return true
		}
	}
```

If there is agreement, I'd be happy to open a PR to fix these.

Additionally, there are lots of allocations coming from e.g. `Properties           map[string]JSONSchemaProps`, `PatternProperties    map[string]JSONSchemaProps`. If we are able to change the map type to contain a `*JSONSchemaProps` instead, we could eliminate allocations when ranging through these as well.

/kind cleanup
/sig api-machinery

**Comment by smarterclayton** [comment]
Seems reasonable, jordan and I attacked a number of these a while back on different critical paths, and there was substantial low hanging fruit elsewhere that just wasn’t top of priority.  Will be happy to review.
