### ISSUE TITLE
Allow for reuse of EndpointSlice controller code by making `controllerName` not const

### ISSUE THREAD

**Issue by akhilles** [kubernetes/kubernetes#112491]
### What would you like to be added?

I'd like to be able to reuse the `k8s.io/kubernetes/pkg/controller/endpointslice` go module to build EndpointSlice controllers that can run outside of KCM.

Changing the [`controllerName`](https://github.com/kubernetes/kubernetes/blob/6824cd3addbb214e88e00f451babb8a44eb738d1/pkg/controller/endpointslice/endpointslice_controller.go#L76) variable from a `const` to a `var` would be enough to support this use-case.

### Why is this needed?

Having multiple controllers manage EndpointSlices without interfering with each other is already supported by the `endpointslice.kubernetes.io/managed-by` annotation. However, reconciling EndpointSlices is a hard problem and ideally we would be able to reuse the existing code and benefit from all the work that's been put into making it robust.

**Comment by aojea** [comment]
vendoring kubernetes/kubernetes is discouraged, I personally prefer to not allow people to import these core components and create this dependency ... you can always fork the code

/cc @robscott @thockin 

for more opinions

**Comment by khenidak** [comment]
this code has not been written to be exported outside `kubernetes/kubernetes` source tree. I would strongly advise against importing it. You can always copy the pieces you want.

**Comment by akhilles** [comment]
A better proposal might be to move some of the EndpointSlice utilities and reconciliation logic into a staging repository. Making the `reconcile` function reusable via a library would be valuable for custom EndpointSlice controllers because it’s hard to get right (lot of subtle edge cases) and forking/reimplementing isn’t ideal. There are custom Endpoints/EndpointSlice controllers that are being used today (multus-service, danm) and I believe more are on the way (multi-networking, MCS). I think a decent subset of them would benefit from code reuse.

This might also be valuable from an Endpoints -> EndpointSlice migration perspective. It’s relatively easy to write a custom Endpoints controller, but less so with EndpointSlices. So, if you already have a custom Endpoints controller, the migration path is a bit unclear. Having a library that does the “tricky” stuff would make migrating these controllers less scary.

**Comment by robscott** [comment]
I've been talking with @akhilles offline and agree that there's a good case for moving the core of our EndpointSlice controller logic (the reconciler) to a place that is easier to import. I think the EndpointSlice controller is somewhat unique in terms of controllers in kube-controller-manager. It was built with the idea that other controllers would exist to manage EndpointSlices (the managed-by label would not exist without that idea).

We're seeing some cases where the controller code is being forked, and others where a subset of the logic is being rewritten, neither is ideal from a supportability perspective. An effort like this could not just benefit the various OSS projects that have replicated much of this logic (or are about to). Beyond that, it could potentially also be used to share more code between the EndpointSlice and EndpointSlice mirroring controllers.

I think this is worth discussing in the next sig-network meeting, but from my perspective, this approach is worth exploring.

**Comment by aojea** [comment]
I'm afraid of creating this dependency, it always happen that we have to break and then users will complain despite we always said "we don't offer guarantees", or we add new features that people don't need , ...

If the use case is that people don't like to have to implement it , I throw another idea, that is based on the envoy control-plane project https://github.com/envoyproxy/go-control-plane

> Due to the variety of platforms out there, there is no single control plane implementation that can satisfy everyone's needs. Hence this code base does not attempt to be a full scale control plane for a fleet of Envoy proxies. Instead, it provides infrastructure that is shared by multiple different control plane implementations. The components provided by this library are:

We, as sig-network, can create a endpoint slice control plane to be used as a library and maintain it in a separate repo

**Comment by khenidak** [comment]
As discussed in sig-network meeting. We will take on this work.  

This doc https://docs.google.com/document/d/1k0V5FhMqZhHgUZ9PnixKX0VDNOEyuZLWLRniPIzHWEY/  is to gain consensus on approach and act as a bases for a future KEP.

**Comment by akhilles** [comment]
/remove-lifecycle stale

KEP is open for review: https://github.com/kubernetes/enhancements/pull/3686

**Comment by soroshsabz** [comment]
ITNOA

Hi

@akhilles https://github.com/kubernetes/enhancements/pull/3686 has been merged

**Comment by soroshsabz** [comment]
@robscott So I think this issue can continue, because https://github.com/kubernetes/enhancements/pull/3686 has been merged

Did you want outer PR for this issue, or your plan to implement this issue by org?

thanks

**Comment by robscott** [comment]
yep, good catch @soroshsabz, I think everything is complete.

/close
