### ISSUE TITLE
Referencing common setup scripts.

### ISSUE THREAD

**Issue by timothysc** [kubernetes/kubernetes#11249]
Currently we have the following ways to stand up a cluster: 

1. By hand, fraught with peril and instructions are rarely kept up to date. 
2. Salt 
3. Ansible
4. hack/local-cluster-up 
+ Plus assortment of other tooling that folks may wish to use (chef, puppet, vagrant magik,etc.) 

Each one of these methods repeats some initial setup and configuration for certs & default configuration.  Perhaps instead of cloning this everywhere we create a couple of clean scripts that are leveraged by * and are updated in a single location as to avoid errors, such as #11225, and the numerous test errors we've uncovered over the course of 1.0 that was a result of config changes.

/cc @eparis @stefwalter @rrati @jayunit100 @ixdy @thockin @pmorie 

I hate to say this, but even hadoop does a better job at this, and that is saying something.

**Comment by davidopp** [comment]
This seems related to #2770 and #5472

**Comment by timothysc** [comment]
@davidopp umm totally unrelated.

**Comment by davidopp** [comment]
(The closing was because I hit the wrong button, not because I was actually trying to close this issue--sorry.)

Can you explain the differences between this issue and those?

**Comment by roberthbailey** [comment]
Rather than clean scripts, I'd like to see a deployment CLI (#5472) written in Go with the reusable bits and then cloud provider parts cleanly factored out (#2770). I don't see how this is totally unrelated. Even for the local setup, the CLI program could ask for input (press enter once you've configured your network...) and for cloud providers the setup could be automated.

**Comment by timothysc** [comment]
Ahh, thanks @roberthbailey for piecing that together for me, that makes a lot more sense now.

**Comment by pmorie** [comment]
> Even for the local setup, the CLI program could ask for input (press enter once you've configured your network...) and for cloud providers the setup could be automated.

Is this just a cloud provider that's like 'do nothing, wait for the user to confirm that it's done' ?

**Comment by roberthbailey** [comment]
Closing to consolidate discussion on #5472. Please reopen if you think this is legitimately a separate issue.
