### ISSUE TITLE
Unit tests failed with `TestWhoAmIRun`

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#112465]
### Which jobs are flaking?

Unit tests failed with `TestWhoAmIRun`, see https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112025/pull-kubernetes-unit/1570285754330910720

### Which tests are flaking?

TestWhoAmIRun/success_test

### Since when has it been flaking?

None

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Relevant SIG(s)

/sig cli

**Comment by kerthcet** [comment]
I think it was caused by https://github.com/kubernetes/kubernetes/pull/111333

**Comment by kerthcet** [comment]
When we loop the golang Map, it's unordered.
https://github.com/kubernetes/kubectl/blob/36d5aa982dee2384b4e9d1528200dd61226b7495/pkg/cmd/auth/whoami.go#L194-L199

**Comment by nabokihms** [comment]
I can work on this one.

**Comment by kerthcet** [comment]
Thanks.

**Comment by aojea** [comment]
/priority critical-urgent

this is impacting CI,
