### ISSUE TITLE
have no possibility to add data from the file 

### ISSUE THREAD

**Issue by amarsova** [kubernetes/kubernetes#112456]
### What would you like to be added?

I use configMap to implement the variable  into pods. Then I need to configured the value from the file into env value . How to make it ?
  - command:
    - SERVER_PROPERTIES="$(cat /etc/voldemort/config/server.properties)"
    env:
    - name: SERVER_PROPERTIES
      value: $(SERVER_PROPERTIES)

### Why is this needed?

there is a lot of  configuration , but have no possibility to implement the values

**Comment by pacoxu** [comment]
/kind support
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-container-environment-variables-using-configmap-data
