### ISSUE TITLE
Windows runAsNonRoot does not block default ContainerAdministrator

### ISSUE THREAD

**Issue by yaqisun7** [kubernetes/kubernetes#112469]
### What happened?

I tried to use runAsNonRoot in the container security context for windows containers. The user for the image is not set, and it runs as ContainerAdministrator by default. According to https://kubernetes.io/docs/concepts/windows/intro/#compatibility-v1-pod-spec-containers, it should "prevent containers from running as ContainerAdministrator". But the container can be created and run just fine.

### What did you expect to happen?

If securityContext.windowsOptions.runAsUserName is set as "ContainerAdministrator", it will show CreateContainerConfigError.

- I expect that this error will also happen if the user info in the image manifest is empty.

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f run-as-nonroot-demo.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: run-as-nonroot-demo
spec:
  containers:
  - name: run-as-nonroot-demo
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command: ["ping", "-t", "localhost"]
    securityContext:
      runAsNonRoot: true
  nodeSelector:
    kubernetes.io/os: windows
```

### Anything else we need to know?

I guess this is related to the getImageUser() function in [https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/helpers.go#L140](url), if none of uid and username are set, it will be treated as root by setting the uid as 0.
For linux containers, it will violate the runAsNonRoot rule, so there will be CreateContainerConfigError.
But for windows, when checking the runAsNonRoot property in [https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/security_context_windows.go#L42](url), the username is used. In this case, the uid is 0 while the username is nil. So it will pass the runAsNonRoot rule. But in fact, it will run as ContainerAdministrator.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a35ccc8395e8a5eaa83b7b8c981677893b651cba", GitTreeState:"clean", BuildDate:"2022-07-28T20:52:46Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AbelHu** [comment]
duplicated of https://github.com/kubernetes/kubernetes/issues/112192

**Comment by marosset** [comment]
When `runAsNonRoot=true` on Windows the kubelet will check to see if the value in `runAsUsername` is not set to `ContainerAdministrator`. if `runAsUsername` is not set then it will check the `User` field in the container images json file.

I took a look at the image files and see that for `nanoserver` images `User` is set to `ContainerUser` but for `servercore` images `User` is unset. Because of this we are getting the behavior reported above.

```bash
docker image ls
REPOSITORY                             TAG        IMAGE ID       CREATED        SIZE
mcr.microsoft.com/windows/servercore   ltsc2022   5b48538011db   3 days ago     5.28GB
mcr.microsoft.com/windows/nanoserver   ltsc2022   a1cc73b9ec99   3 days ago     297MB
```

The **nanoserver** config file (C:\ProgramData\docker\image\windowsfilter\imagedb\content\sha256\a1cc73b9ec99f2ab4615d02b788a6ca66d6ff953d54d51ffd4b9bde44499c21e) contains

```json
{
    "architecture": "amd64",
    "config": {
        "Hostname": "",
        "Domainname": "",
        "User": "ContainerUser",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": null,
        "Cmd": [
            "c:\\windows\\system32\\cmd.exe"
        ],
        "Image": "",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": null
    },
    "created": "2022-11-05T07:21:30.2452673Z",
    "history": [
        {
            "created": "2022-11-05T07:21:30.2452673Z",
            "created_by": "Apply image 10.0.20348.1249"
        }
    ],
    "os": "windows",
    "os.version": "10.0.20348.1249",
    "rootfs": {
        "type": "layers",
        "diff_ids": [
            "sha256:a4e749ded6b9e326ac6d3293fc74441db7236ac96a1a32849be1c140dab2ab62"
        ]
    }
}
```

and the **servercore** image (C:\ProgramData\docker\image\windowsfilter\imagedb\content\sha256\5b48538011db4656a692b7f0f711d910b1125c797e2de3a5bd818f96939c41f3) contains:

```json
{
    "architecture": "amd64",
    "config": {
        "Hostname": "",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": null,
        "Cmd": [
            "c:\\windows\\system32\\cmd.exe"
        ],
        "Image": "",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": null
    },
    "created": "2022-11-05T07:49:25.0325944Z",
    "history": [
        {
            "created": "2022-04-22T01:12:09.4542389Z",
            "created_by": "Apply image 10.0.20348.643"
        },
        {
            "created": "2022-11-05T07:49:25.0325944Z",
            "created_by": "Install update 10.0.20348.1249"
        }
    ],
    "os": "windows",
    "os.version": "10.0.20348.1249",
    "rootfs": {
        "type": "layers",
        "diff_ids": [
            "sha256:b9bda40f596a8f8648c218b23e552acf9498c039eb0a48c222cfcd5a9af9e841",
            "sha256:3946a2e7a5771a88fbfc1f0cee07c3e909ca4f2ac2e244f6ea78b614f0ca0c4d"
        ]
    }
}
```

Personally I think that this is an issue with the **servercore** images and if the containers run as `ContainerAdministrator` by default that information should be in the image config.

I'm curious what @brasmith-ms @kevpar @dcantah think.

If we cannot set this data for some reason another option may be to update the logic for when kubelet sees `runAsNonRoot=true` on Windows to nowallow containers to start if `User`/`runAsUserName` is empty-string OR  `ContainerAdministrator`. Thoughts @jsturtevant ?

**Comment by bplasmeijer** [comment]
i am working on it

**Comment by bplasmeijer** [comment]
I will reassign it when I finish. Personal family issues at the moment.
