### ISSUE TITLE
Testgrid sig-node-cadvisor#cadvisor-e2e is consistently failing

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#112459]
### Which jobs are failing?

- Job name: ci-cadvisor-e2e
- Job config link: https://github.com/kubernetes/test-infra/blob/master/config/jobs/cadvisor/cadvisor.yaml#L52

### Which tests are failing?

Whole job is failing.

### Since when has it been failing?

2022-09-07 16:56 PST

### Testgrid link

https://testgrid.k8s.io/sig-node-cadvisor#cadvisor-e2e

### Anything else we need to know?

cc @codersherlock

### Relevant SIG(s)

/sig node

**Comment by dims** [comment]
cc @bobbypage

**Comment by dims** [comment]
Same with presubmit https://testgrid.k8s.io/presubmits-misc#cadvisor as well.

**Comment by bobbypage** [comment]
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cadvisor-e2e/1570563079794593792

from https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cadvisor-e2e/1570563079794593792/build-log.txt
```
W0916 00:02:49.518] + [[ ! -z cmd/internal/pages/static/assets.go
W0916 00:02:49.519] cmd/internal/pages/templates.go ]]
W0916 00:02:49.519] + echo 'Found changes to UI assets:'
W0916 00:02:49.519] + git diff --name-only -- cmd/internal/pages
W0916 00:02:49.526] + echo 'Run: '\''make assets FORCE=true'\'''
W0916 00:02:49.526] + exit 1
I0916 00:02:49.627] Found changes to UI assets:
I0916 00:02:49.627] cmd/internal/pages/static/assets.go
I0916 00:02:49.628] cmd/internal/pages/templates.go
I0916 00:02:49.628] Run: 'make assets FORCE=true'
```

**Comment by bobbypage** [comment]
https://github.com/google/cadvisor/pull/3169 should fix this issue, let's watch the testgrid

**Comment by bobbypage** [comment]
The testgrid are now green. 

/close

**Comment by dims** [comment]
thanks @bobbypage !
