### ISSUE TITLE
Failure cluster [f6cf3d64...]: TestStalePodDisruption

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#112594]
##### Error text:
```
=== RUN   TestStalePodDisruption/stale_pod_disruption
W0903 05:46:12.224218   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0903 05:46:12.226482   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0903 05:46:12.227136   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0903 05:46:12.227260   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0903 05:46:12.227326   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0903 05:46:12.227432   76126 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0903 05:46:12.329811   76126 disruption.go:421] Sending events to api server.
I0903 05:46:12.334312   76126 disruption.go:432] Starting disruption controller
I0903 05:46:12.334420   76126 shared_informer.go:255] Waiting for caches to sync for disruption
I0903 05:46:12.334571   76126 shared_informer.go:262] Caches are synced for disruption
    disruption_test.go:1529: Obtained pod conditions (-want,+got):
          []v1.PodCondition{
          	{
          		Type:          "DisruptionTarget",
        - 		Status:        "False",
        + 		Status:        "True",
          		LastProbeTime: {},
          		... // 1 ignored and 2 identical fields
          	},
          }
I0903 05:46:12.437389   76126 disruption.g
```
#### Recent failures:
[2022/9/8 04:20:19 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1567608212939608064)
[2022/9/3 13:25:13 ci-kubernetes-generate-make-test-count10](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-generate-make-test-count10/1565933915070271488)

/kind failing-test

/kind flake

/sig testing apps

**Comment by aojea** [comment]
@alculquicondor can you PTAL, it seems this test was added in https://github.com/kubernetes/kubernetes/pull/111475

It doesn't seem to have a high rate of failure , but seems flakes are legit

**Comment by alculquicondor** [comment]
fix: #112610

side note: it's really hard to make it fail in a fast machine :) I had to temporarily add a sleep in the reconciler.

**Comment by aojea** [comment]
> side note: it's really hard to make it fail in a fast machine :) I had to temporarily add a sleep in the reconciler.

have you tried Jordan's instructions compiling and running with `stress`  https://gist.github.com/liggitt/6a3a2217fa5f846b52519acfc0ffece0#running-unit-tests-to-reproduce-flakes ?

for integration you should have an external etcd instance

**Comment by alculquicondor** [comment]
I hadn't. Good to know for next time :)
