### ISSUE TITLE
Kubernetes swap support alpha feature -errors out 

### ISSUE THREAD

**Issue by martin2176** [kubernetes/kubernetes#112523]
/sig node
### What happened?

Followed instructions to enable the alpha feature for kubernetes swap. 
Azure AKS 1.24.3
Below is kubelet configuration 

kubectl get nodes
NAME STATUS ROLES AGE VERSION
aks-npoolb2ms-73462207-vmss000000 Ready agent 22m v1.24.3

kubelet config

"failSwapOn": false,
"memorySwap": {
   "swapBehavior": "UnlimitedSwap"
    },
"featureGates": {
    "CSIMigration": true,
    "CSIMigrationAzureDisk": true,
    "CSIMigrationAzureFile": true,
    "DelegateFSGroupToCSIDriver": true,
    "NodeSwap": true,
    "DisableAcceleratorUsageMetrics": false
    
    Swap enabled and available on OS
root@aks-npoolb2ms-73462207-vmss000000:~# swapon -s
Filename Type Size Used Priority
/mnt/swapfile file 14999996 0 -2

root@aks-npoolb2ms-73462207-vmss000000:/etc# cat os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"

Create a pod and put a memory request and limit. OR create a pod without any specific memory request/limit.
POD spec
resources:
requests:
memory: "200Mi"
cpu: "100m"
limits:
memory: "200Mi"
cpu: "100m"

Gives error
Warning Failed 4s (x2 over 6s) kubelet Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: process_linux.go:508: setting cgroup config for procHooks process caused: open /sys/fs/cgroup/memory/kubepods/pod89b1a8ad-e180-4d32-9849-ad248a04f4f4/aksdebug/memory.memsw.limit_in_bytes: no such file or directory: unknown
Normal Pulled 4s kubelet Successfully pulled image "martin2176/aksdebugpod:v3" in 793.764549ms
Warning BackOff 2s (x2 over 3s) kubelet Back-off restarting failed container

### What did you expect to happen?

POD to startup without any errors 

### How can we reproduce it (as minimally and precisely as possible)?

Enable swap support in kubelet by adding these flags in kubelet config
"failSwapOn": false,
"memorySwap": {
   "swapBehavior": "UnlimitedSwap"
    },
"featureGates": {
    "NodeSwap": true
    }
    Create any pod with Mem request and Limit. POD will fail to start with the error
 

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-15T05:51:30Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}


</details>


### Cloud provider

<details>
Azure AKS 1.24.3

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux aks-npoolb2ms-16174354-vmss000001 5.4.0-1089-azure #94~18.04.1-Ubuntu SMP Fri Aug 5 12:34:50 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
 containerd://1.6.4+azure-4
kubectl get nodes -o wide
NAME                                STATUS   ROLES   AGE    VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
aks-npoolb2ms-16174354-vmss000001   Ready    agent   6d8h   v1.24.3   10.30.33.4    <none>        Ubuntu 18.04.6 LTS   5.4.0-1089-azure   containerd://1.6.4+azure-4

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/triage accepted

@martin2176 what is cgroup version is being used?

**Comment by martin2176** [comment]
> /triage accepted
> 
> @martin2176 what is cgroup version is being used?
cgroup version1 
See below:
going by https://rootlesscontaine.rs/getting-started/common/cgroup2/  to identify is using cgroup2
ls -al /sys/fs/cgroup/cgroup.controllers
ls: cannot access '/sys/fs/cgroup/cgroup.controllers': No such file or directory

**Comment by rhessing** [comment]
@martin2176 can you please check if this command will return a result?
`ls -al /sys/fs/cgroup/memory/kubepods/pod89b1a8ad-e180-4d32-9849-ad248a04f4f4/aksdebug/`

(could be that the pod has been recreated, then the pod89b1a8ad-e180-4d32-9849-ad248a04f4f4 will be different)

If it does then you probably need to do the following to fix this issue:

- Add the following line to: `/etc/default/grub`: `GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0 swapaccount=1 cgroup_enable=memory"`
- Run: update-grub2
- Reboot

**Comment by claudiomerli** [comment]
Hi, I have same problem on coredns

**Comment by iholder101** [comment]
Hey!

From a glance, it seems that the error says that `memory.memsw.limit_in_bytes` is not found. This makes sense if you're running on cgroup v2, and indeed NodeSwap did not support cgroup v2 when it was still alpha.

I see the issue itself is very old and probably be closed. @martin2176 is there something else I can help with?

**Comment by martin2176** [comment]
yes it can be closed. You are correct , this ticket was opened when cgroup v2 was alpha

**Comment by martin2176** [comment]
yes it can be closed. You are correct , this ticket was opened when cgroup v2 was alpha
