### ISSUE TITLE
error in installing 

### ISSUE THREAD

**Issue by rohityadav78** [kubernetes/kubernetes#112550]
### What happened?

it is showing 

On macOS with homebrew 'brew install bash' is sufficient.
make[1]: *** [.make/go-pkgdeps.mk] Error 1
make: *** [generated_files] Error 2

### What did you expect to happen?

it should run.

### How can we reproduce it (as minimally and precisely as possible)?

It looks like brew is trying to build the requested package (libwebp?) from source and the build is failing. If so the real errors are further back in the log -- those shown are just make saying that something has gone wrong and it's bailing

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support

hi, this seems like a support request.

please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
