### ISSUE TITLE
How does a Pod whose QOS level is Burstable realize the exclusive use of one of the container's CPUs?

### ISSUE THREAD

**Issue by arrowfeng** [kubernetes/kubernetes#112561]
### What happened?

There are multiple containers in a Pod with a QOS level of Burstable. How does one container implement CPU exclusiveness, and the other containers use the shared pool through CPUManager？

https://github.com/kubernetes/kubernetes/blob/a4ad8f4154bb07be9cbb98d12d82c51afaffeac6/pkg/kubelet/cm/cpumanager/policy_static.go#L361-L373

### What did you expect to happen?

For a pod with a QoS level of Burstable, if there are multiple containers, expect those containers with equal limits and requests to be exclusive cpu, while others are shared pool.

### How can we reproduce it (as minimally and precisely as possible)?

x

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
 

### Cloud provider

<details>

</details>
 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
 

### Install tools

<details>

</details>
 

### Container runtime (CRI) and version (if applicable)

<details>

</details>
 

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by swatisehgal** [comment]
If there is a strict requirement that the pod must belong to Burstable QoS class, the answer would be that it is not possible. For a pod to be allocated CPUs exclusively CPU Manager should be configured with [static policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#static-policy) and the pod MUST belong to guaranteed QoS class (which means total request == total limit).

But there is one more condition that is required, at a container level CPU request should be equal to limit and should be integral. We can manipulate this to have a pod with containers soe of which can be allocated CPUs exclusively and others from the shared pool. Here is an example:

```
$ cat  test-deployment-gu-multicontainer.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesdeployment-gu
  labels:
    app: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: ctnr1
        image: quay.io/fromani/numalign
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: [ "while true; do numalign; sleep 100000; done;" ]
        resources:
          limits:
            memory: "100Mi"
            cpu: "2" # allocated CPUs exclusively
          requests:
            memory: "100Mi"
            cpu: "2"
      - name: ctnr2  
        image: quay.io/fromani/numalign
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: [ "while true; do numalign; sleep 100000; done;" ]
        resources:
          limits:
            memory: "100Mi"
            cpu: "2.5" # allocated CPUs from shared pool
          requests:
            memory: "100Mi"
            cpu: "2.5"
```

Once the pod is deployed, you can see that container1 is allocated CPUs exclusively:

**Comment by swatisehgal** [comment]
In the above example, the pod belongs to guaranteed QoS as total resource request  == total resource limits.

**Comment by arrowfeng** [comment]
Thanks for your answer, I got it, only guaranteed QoS can be allocated CPUs exclusively.
