### ISSUE TITLE
`pull-kubernetes-unit` failed by `TestCleanup`

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#112569]
### Which jobs are flaking?

Log detail: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112563/pull-kubernetes-unit/1571820258535149568

Aggregated failures see: https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=TestCleanup

### Which tests are flaking?

TestCleanup

### Since when has it been flaking?

From the aggregated failures, it fails since 9/10, occasionally.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
Thanks for opening it, let's track it for a week to see the trend

**Comment by pohly** [comment]
The most recent failure in https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=TestCleanup is from 9/12, which might have been before https://github.com/kubernetes/kubernetes/pull/112389 was merged.

```
        	            	 INFO: >>> kubeConfig: yyy/kube.config
        	            	+W0910 10:40:27.255760   75300 lease.go:250] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
        	            	 STEP: Building a namespace api object, basename test-namespace
        	            	+W0910 10:40:27.344237   75300 lease.go:250] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
        	            	 INFO: Skipping waiting for service account
        	            	@@ -25,2 +27,3 @@
        	            	 STEP: Destroying namespace "test-namespace-zzz" for this suite.
        	            	+W0910 10:40:27.360652   75300 lease.go:250] Resetting endpoints for master service "kubernetes" to [127.0.0.1]
```

That's what the PR should have fixed.

**Comment by aojea** [comment]
> https://github.com/kubernetes/kubernetes/pull/112389 was merged.

Sept 12, 2.27 pm GMT+2

> https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&test=TestCleanup is from 9/12

```
Latest Failures
Time	Job	Test
9/11/2022, 9:32:50 PM	pr:pull-kubernetes-unit	k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup TestCleanup
9/11/2022, 7:53:16 PM	pr:pull-kubernetes-unit	k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup TestCleanup
9/10/2022, 12:19:55 PM	pr:pull-kubernetes-unit	k8s.io/kubernetes/test/e2e/framework/internal/unittests/cleanup TestCleanup
```

/close

Thanks both for reporting these things and for the quick answer

**Comment by kerthcet** [comment]
One more question, I met this error yesterday, but the pr was merged several days ago. How to explain this?

**Comment by aojea** [comment]
> One more question, I met this error yesterday, but the pr was merged several days ago. How to explain this?

right, this one https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112563/pull-kubernetes-unit/1571820258535149568

the logs show that 2 test fail, we know this specific test is very demanding in terms of resources and the logs shows the boostrap is timing out

the second test fails because of a timeout

> panic: test timed out after 3m0s

if is an occurrence only, and 2 different tests present timeout issues, it is most probably related to some infra hiccup, but we can not discard anything, if it happens again we should investigate more

**Comment by kerthcet** [comment]
Thanks for explaining.
