### ISSUE TITLE
Question: Where are the scaling limits coming from?

### ISSUE THREAD

**Issue by cove** [kubernetes/kubernetes#112572]
Given the following limits:

- No more than 110 pods per node
- No more than 5000 nodes
- No more than 150000 total pods
- No more than 300000 total containers

Is there an explanation as to what the hard scaling bottlenecks are? I'm assuming it's not clearly understood since it's a complex system, but the numbers are also specific, especially 110 pods. So they're coming from somewhere.

Generally speaking for example; is etcd and Raft limiting the scaling? Or is the scheduler O(n^2)? The Linux kernel limits?

Would be helpful to understand.

**Comment by pacoxu** [comment]
Add the data reference: https://kubernetes.io/docs/setup/best-practices/cluster-large/

**Comment by BenTheElder** [comment]
> Is there an explanation as to what the hard scaling bottlenecks are? I'm assuming it's not clearly understood since it's a complex system, but the numbers are also specific, especially 110 pods. So they're coming from somewhere.

Partially: Defaults (pod node limit) + testing (5k node scale tests, we're just not advertising larger than the project tests).

GKE for example has customers with 15k nodes, but Kubernetes the project tests up to 5k nodes and thus only advertises this scale that we know it can reach on an ongoing basis, which already gets rather expensive to test.



https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/


> `--max-pods int32`     Default: 110
> --
>   | Number of Pods that can run on this Kubelet. (DEPRECATED: This parameter should be set via the config file specified by the Kubelet's --config flag. See kubelet-config-file for more information.)

**Comment by BenTheElder** [comment]
AFAIK none of these are hard limits, they're the advertised limits that we test and expect it to reach. 

Reaching more may take some effort though, large or small. 

Such as tuning the `--max-pods` flag (and ensuring other tuning on the node such that the node can actually handle more pods, including kernel limits like pids, inotify watches, and related Kubernetes configuration such as the size of the per-node pod CIDR)
