### ISSUE TITLE
Unable to Get or Delete Job

### ISSUE THREAD

**Issue by sbextenwcu** [kubernetes/kubernetes#112642]
### What happened?

Was working with the Python Kubernetes client trying to figure out how to delete and create jobs automatically. Ran the following code:
`from kubernetes import client, config

config.load_incluster_config()
batch_v1 = client.BatchV1Api()
api_response = batch_v1.delete_namespaced_job(
    name="dbt-run",
    namespace="default",
    body=client.V1DeleteOptions(
        propagation_policy='Foreground',
        grace_period_seconds=5))`

This added a finalizer to the dbt-run job configuration
![dbt_run_finalizer](https://user-images.githubusercontent.com/114089443/191540572-0e39fcbf-a8e0-4c24-9911-103e84f56948.JPG)

However, after deleting the pods, the job will not be deleted. Has been present since yesterday.

Worse, I'm unable to get the job by name. Gives me a 'Not found' error with kubectl. If I run `kubectl get jobs`, the job appears, though. And I'm able to create another job with the same name

![dbt_run_duplicate](https://user-images.githubusercontent.com/114089443/191540576-eddeae5a-c510-4e0b-919e-0dbe75791701.JPG)

I also tried deleting all jobs (server has few resources and everything was completed). Every job was deleted _except_ for the ghost job.

What are my next steps to delete this job?

### What did you expect to happen?

Expected job to be deleted, but did not understand how finalizers work.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure. Think I ran the Python script, then deleted the pods, but I'm not sure of the order.

### Kubernetes version

<details>
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.13-35+d877e7a8ac536e", GitCommit:"d877e7a8ac536e691e6fd3ea06e93af3d8c0c8b8", GitTreeState:"clean", BuildDate:"2021-12-07T10:43:51Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.13-35+d877e7a8ac536e", GitCommit:"d877e7a8ac536e691e6fd3ea06e93af3d8c0c8b8", GitTreeState:"clean", BuildDate:"2021-12-07T10:44:48Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
Hosted in-house
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Komaljiwatode03** [comment]
https://meta.stackoverflow.com/questions/335777/not-able-to-apply-for-a-job I have seen the issue and I think it's the correct answer.

**Comment by dims** [comment]
@sbextenwcu please read up on finalizers ... https://www.google.com/search?q=finalizers+stuck+kubectl some of the links have tips on how to use kubectl to remove the finalizer.
