### ISSUE TITLE
Cannot access UDP service via ClusterIP from the host

### ISSUE THREAD

**Issue by jclab-joseph** [kubernetes/kubernetes#112614]
### What happened?

Cannot access UDP service via ClsuterIP from the host.

Failing to query kube-dns from Pods with `hostNetwork: true` .

### What did you expect to happen?

Pods with host or `hostNetwork: true` should be able to reach kube-dns .

### How can we reproduce it (as minimally and precisely as possible)?

**pod.yaml**

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: dns-test
  name: dns-test
  namespace: default
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - sleep 1000
    image: debian:bullseye
    imagePullPolicy: IfNotPresent
    name: dns-test
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
```

In pod:
```
# nslookup kubernetes.default.svc.cluster.local
;; connection timed out; no servers could be reached
```

If not `hostNetwork: true` it works fine.
Also, if I change server to pod ip in nslookup it works fine.

### Anything else we need to know?

```
# conntrack -D -p udp --orig-port-dst 53
udp      17 29 src=10.0.0.100 dst=10.96.0.10 sport=34184 dport=53 [UNREPLIED] src=172.30.194.167 dst=172.21.202.0 sport=53 dport=16084 mark=0 use=1

# iptables-save | grep 10.96.0.10
-A KUBE-SERVICES ! -s 172.16.0.0/12 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp --dport 9153 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp --dport 9153 -j KUBE-SVC-JD5MR3NA4I4DYORP
-A KUBE-SERVICES ! -s 172.16.0.0/12 -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SERVICES ! -s 172.16.0.0/12 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:dns-tcp cluster IP" -m tcp --dport 53 -j KUBE-SVC-ERIFXISQEP7F7OF4

# iptables-save | grep KUBE-SVC-TCOU7JCQXEZGVUNU
:KUBE-SVC-TCOU7JCQXEZGVUNU - [0:0]
-A KUBE-SERVICES -d 10.96.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-SVC-TCOU7JCQXEZGVUNU
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-OD6KQAPIFKNTNKGM
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -j KUBE-SEP-2XUJH6OSUONJHNKI

# iptables-save | grep KUBE-SEP-OD6KQAPIFKNTNKGM
:KUBE-SEP-OD6KQAPIFKNTNKGM - [0:0]
-A KUBE-SEP-OD6KQAPIFKNTNKGM -s 172.30.194.162/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ
-A KUBE-SEP-OD6KQAPIFKNTNKGM -p udp -m comment --comment "kube-system/kube-dns:dns" -m udp -j DNAT --to-destination 172.30.194.162:53
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-OD6KQAPIFKNTNKGM

```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


$ uname -a

Linux ... 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

calico

</details>

**Comment by aojea** [comment]
> src=10.0.0.100 dst=10.96.0.10 sport=34184 dport=53 [UNREPLIED] src=172.30.194.167 dst=172.21.202.0 sport=53 dport=16084 mark=0 use=1

> -A KUBE-SERVICES ! -s 172.16.0.0/12 -d 10.96.0.10/32 -p tcp -m comment --comment "kube-system/kube-dns:metrics cluster IP" -m tcp --dport 9153 -j KUBE-MARK-MASQ


> -A KUBE-SEP-OD6KQAPIFKNTNKGM -s 172.30.194.162/32 -m comment --comment "kube-system/kube-dns:dns" -j KUBE-MARK-MASQ


so, the original packet is 10.0.0.100/10.96.0.100 and it gets translated to 172.21.202.0/172.30.194.167.

The dns service IP is 10.96.0.100 and the podIP for the dns is 172.30.194.162.

The host have one IP is that is 10.0.0.100 and it have this 172.21.202.0 that should be another IP in the host (maybe masquerading external traffic)

In UDP, if there are multiple IPs, unless you bind to the address you want, it uses the closes to the destination independently of the IPs received.

You can check this thread https://github.com/kubernetes/kubernetes/issues/95565 and verify with tcpdump if the answers are returning to a different IP, thus NAT is not translating back , breaking the connectivity

**Comment by jclab-joseph** [comment]
```
tcpdump -i any udp port 53
```

No related packets are captured with tcpdump.

```
1# nslookup
> server
Default server: 10.96.0.10
Address: 10.96.0.10#53
> kubernetes.default.svc.cluster.local
;; connection timed out; no servers could be reached
```

**Comment by aojea** [comment]
> src=10.0.0.100 dst=10.96.0.10 sport=34184 dport=53 [UNREPLIED] src=172.30.194.167 dst=172.21.202.0 sport=53 dport=16084 mark=0 use=1


you have a conntrack entry with port 53, there has to be packets on that port

**Comment by jclab-joseph** [comment]
Yes, it is my mistake.
Packets sent, but do not return.

One more thing I checked, it works if I have Pods on the same node, but not between different nodes.

```
08:46:08.041819 IP 172.30.194.128.50941 > 172.21.202.9.53: 65345+ A? kubernetes.default.svc.cluster.local.default.svc.cluster.local. (80)
`

(node-1) # ip addr | grep 172.30.194.128
    inet 172.30.194.128/32 scope global vxlan.calico

# coredns-74ff55c5b-47qpr                           1/1     Running   0          6m34s   172.21.202.9   <none>      node-2     <none>
``

**Comment by aojea** [comment]
I've added an e2e test that verifies that this work and we don't regress
https://github.com/kubernetes/kubernetes/pull/112511

**Comment by aojea** [comment]
@jclab-joseph I think that we should close this and follow up on https://github.com/projectcalico/calico/issues/6767

We can always reopen if it is bounced back and it turns out to not be somethign specific of the CNI

**Comment by khenidak** [comment]
/retitle Cannot access UDP service via ClusterIP from the host

**Comment by dcbw** [comment]
Agreed... let's leave it with https://github.com/projectcalico/calico/issues/6767 for now and re-open if it comes back as a Kube problem.

/close
