### ISSUE TITLE
self reference in go.mod is broken by update-vendor.sh

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#112697]
### What happened?

self reference in go.mod is broken by update-vendor.sh when I import a module which has the following requirement
`require k8s.io/client-go v0.25.2`
`replace k8s.io/client-go => k8s.io/client-go v0.24.3`
when I run update-vendor.sh
error happend
`
go: finding module for package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1
k8s.io/kubernetes/cmd/clicheck imports
	k8s.io/kubectl/pkg/cmd imports
	k8s.io/kubectl/pkg/cmd/auth imports
	k8s.io/client-go/kubernetes/typed/authentication/v1alpha1: module k8s.io/client-go@latest found (v0.0.0-00010101000000-000000000000, replaced by k8s.io/client-go@v0.25.2), but does not contain package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1
`

### What did you expect to happen?

update-vendor.sh finished successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. add a demo file like this:
`
package scheduler

import (
	_ "github.com/KunwuLuan/UpdateVendorTest"
)
`

2. run `go get github.com/KunwuLuan/UpdateVendorTest@v1.0.0`

3. run `bash hack/update-vendor.sh`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
Sorry we don't want loops (we depend on something and them depending back on us)
