### ISSUE TITLE
pull-kubernetes-unit failed by `TestRateLimitHealthcheck`

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#112664]
### Which jobs are flaking?

log details: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112025/pull-kubernetes-unit/1572802923430154240

```
=== FAIL: vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory TestRateLimitHealthcheck/etcd_down (3.54s)
    factory_test.go:308: healthcheck() mismatch want etcd down got etcd client connection not yet established
    factory_test.go:319: healthcheck() mismatch want etcd down got etcd client connection not yet established
    --- FAIL: TestRateLimitHealthcheck/etcd_down (3.54s)
```

### Which tests are flaking?

TestRateLimitHealthcheck

### Since when has it been flaking?

Haven't found any history since August in https://storage.googleapis.com/k8s-triage/index.html?date=2022-08-01&test=TestRateLimitHealthcheck

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Anything else we need to know?

For tracing, if it's caused by infra error, maybe we can close this.

### Relevant SIG(s)

/sig testing

**Comment by aojea** [comment]
I've added the test recently, let me check

**Comment by aojea** [comment]
there is not record of failure https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestRateLimitHealthcheck

we don't use to consider flake until it has more than one occurrence, bear in mind that there are external factors that can make test fail and we shoul account for that

**Comment by aojea** [comment]
I will check this one though, there can be a race waiting for etcd to run or something
/assign

**Comment by kerthcet** [comment]
Absolutely, as I said in description, ` if it's caused by infra error, we can close this.`, but it's rare to see flaky ones in unit tests.

**Comment by kerthcet** [comment]
> we don't use to consider flake until it has more than one occurrence

Keep in mind that!

**Comment by BenTheElder** [comment]
/remove-sig testing
/sig api-machinery

individual unit tests are owned by the sigs that are testing things, SIG testing provides the CI infra, test-frameworks, test tools, etc.

**Comment by aojea** [comment]
> Absolutely, as I said in description, ` if it's caused by infra error, we can close this.`, but it's rare to see flaky ones in unit tests, maybe I'm wrong.

you were right @kerthcet 
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/112665/pull-kubernetes-unit/1573727981480710144

/triage accepted

**Comment by kerthcet** [comment]
I think we can close it now.
/close
