### ISSUE TITLE
docs: inotify behavior on atomic configMap/secret volumes is not documented

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#112677]
**Background:**
Kubernetes [automatically updates](https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically) files on mounted `secret` and `configMap` volume types, as respective Secret/ConfigMap resources change.

**Problem:**
When someone runs a program on Kubernetes watching filesystem updates on `secret` and `configMap` volume types volumes (which is typically done using [inotify(7) syscall](https://man7.org/linux/man-pages/man7/inotify.7.html) on POSIX systems), they will be getting only "file deleted" (IN_DELETE_SELF) inotify event when the files are updated. (This is because how Kubernetes/kubelet uses [AtomicWriter](https://pkg.go.dev/k8s.io/kubernetes/pkg/volume/util#AtomicWriter) to make updates to these files.)

This behavior is quite different than what the program would see when it's running outside Kubernetes, since a normal filesystem would return inotify events like IN_CLOSE_WRITE (file opened for writing closed) or IN_MODIFY (file written) events. Furthermore, "file deleted" event causes the inotify monitor to break. Therefore, the code needs to handle this to re-establish the inotify watch upon deletion (otherwise it would only receive the one delete event, and nothing else).

This caveat is not documented.

**Solution:**
Since this behavior might break existing programs that watch files when the program is migrated to run on Kubernetes, it would be ideal to note this pitfall in the project documentation ([this page?](https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically)).

It currently seems that this information is tucked away in some blog posts [[1]](https://william-yeh.net/post/2019/06/inotify-in-containers/), [[2]](https://medium.com/@xcoulon/kubernetes-configmap-hot-reload-in-action-with-viper-d413128a1c9a), [[3]](https://ahmet.im/blog/kubernetes-inotify/) and would be good to surface in official documentation as well.

/kind bug
/area docs

**Comment by BenTheElder** [comment]
Nits:

>  since a normal filesystem would return inotify events

It's a "normal file system", the behavior is entirely in file manipulation in ways that can happen on any filesystem. (I get this is mostly semantics, but that matters for the docs!)

Code that only triggers on IN_CLOSE_WRITE can be broken by this technique outside of Kubernetes. using `rename(2)` for atomic file changes is a documented use case:

> One useful feature of rename is that the meaning of newname changes “atomically” from any previously existing file by that name to its new meaning (i.e., the file that was called oldname). There is no instant at which newname is non-existent “in between” the old meaning and the new meaning. If there is a system crash during the operation, it is possible for both names to still exist; but newname will always be intact if it exists at all.

https://www.gnu.org/software/libc/manual/html_node/Renaming-Files.html#Renaming-Files


https://lwn.net/Articles/789600/ has a discussion of even adding new ways for applications to do this.

I do think this is something we should mention that simple inotify probably won't work, but I'm not sure we should document the implementation details vs suggesting reliable alternatives that don't depend on the implementation (like periodically reading and diffing vs the last read).

I also wouldn't be surprised to see other systems leveraging this known-technique outside kubernetes for the same reason Kubernetes does ... to prevent the even worse pitfall of clients reading partially-rewritten content.

**Comment by ahmetb** [comment]
The main problem is the class of programs reloading configuration based on the filesystem writes that are probably handling a "delete" event by printing an error saying "configuration file no longer exists, exiting" and subsequently issuing an exit() redundantly (whereas they could just attempt to retry the watch).
Maybe I am exaggerating the problem irl, but a program that's purely looking at write/update events won't get any of that on Kubernetes –and that's notable?

**Comment by BenTheElder** [comment]
> Maybe I am exaggerating the problem irl, but a program that's purely looking at write/update events won't get any of that on Kubernetes –and that's notable?

Agree that this is true, however pointing out that behavior is already a broken approach outside of Kubernetes, as the atomic file swap technique is general to Linux and can be done by hand even with just `mv ./newconfig.yaml ./config.yaml`* outside of Kubernetes.

A lot of programs probably don't handle this properly and may encounter it first on Kubernetes. I agree we should warn people, but I disagree that it's only on Kubernetes or result of a special filesystem. It's broken usage of inotify either way.

\* so long as both files are on the same disk/filesystem, `mv` will use `rename` => atomic file replacement.

**Comment by sftim** [comment]
I don't think this is important to document. If you're able to do something misguided without using Kubernetes, we typically don't document that Kubernetes continues to make that possible. The list of caveats could be very very long!

If we commit to using `renameat()` or `rename()` on Linux for atomic writes **and** we commit to an equivalent atomic mechanism on other node OSs (Windows, and anything we support in the future), then we can and should document that commitment to atomic updates.

If that commitment is not part of defined Kubernetes conformance, I'm even more wary of documenting the detail.
