### ISSUE TITLE
Unable to watch services when label selectors are set

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#11262]
Started a MySQL service as defined at: 

https://github.com/arun-gupta/kubernetes-java-sample/blob/master/app-mysql-service.yaml

`kubectl` shows the output correctly as:

```
kubernetes> ./cluster/kubectl.sh get -w se
NAME            LABELS                                    SELECTOR                                IP(S)            PORT(S)
kubernetes      component=apiserver,provider=kubernetes   <none>                                  10.247.0.1       443/TCP
mysql-service   context=docker-k8s-lab,name=mysql-pod     context=docker-k8s-lab,name=mysql-pod   10.247.254.198   3306/TCP
```

Querying the service with a label shows the following output:

```
kubernetes> ./cluster/kubectl.sh get -w se -l context=docker-k8s-lab
NAME            LABELS                                  SELECTOR                                IP(S)            PORT(S)
mysql-service   context=docker-k8s-lab,name=mysql-pod   context=docker-k8s-lab,name=mysql-pod   10.247.254.198   3306/TCP
Error from server: label selectors are not supported on services
```

Even though the request is narrowed by the label, an error message is displayed indicating label selectors are not supported on services. This is inconsistent with the returned results.

**Comment by JanetKuo** [comment]
Initial investigation -- When we do kubectl watch (and not watch-only), CLI will first print the object and then send requests to server. Which means:
```
NAME            LABELS                                  SELECTOR                                IP(S)            PORT(S)
mysql-service   context=docker-k8s-lab,name=mysql-pod   context=docker-k8s-lab,name=mysql-pod   10.247.254.198   3306/TCP
```
is generated from client side, whereas
```
Error from server: label selectors are not supported on services
```
is the error message returned from server.

**Comment by JanetKuo** [comment]
Ref #8337

**Comment by JanetKuo** [comment]
It can be solved by updating server version of kubectl. To know the version used, simply type `kubectl version`. Please reopen this if it doesn't fix this problem.

**Comment by arun-gupta** [comment]
How do I update server version of `kubectl`?

Does that mean downloading kubernetes.tar.gz and installing the cluster again?

**Comment by JanetKuo** [comment]
Could you paste the output of `kubectl version`?

**Comment by arun-gupta** [comment]
```
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
```

**Comment by JanetKuo** [comment]
Do you still see this problem under 1.0?

**Comment by arun-gupta** [comment]
Never tried in 1.0. Newer versions were giving problem with Virtual Box 5.0 as explained in #12614.

Will wait for 1.0.5 when that's available.

**Comment by JanetKuo** [comment]
@arun-gupta [v1.0.5](https://github.com/kubernetes/kubernetes/releases/tag/v1.0.5) is just released. Please give it a try and this issue should be fixed as well. Please let me know if it works, thanks!

**Comment by arun-gupta** [comment]
@JanetKuo Downloading and will let you know.

It's still marked as Pre-release. How is that different from a release?

**Comment by arun-gupta** [comment]
@JanetKuo got the following error:

```
Wrote config for vagrant to /Users/arungupta/.kube/config
Each machine instance has been created/updated.
  Now waiting for the Salt provisioning process to complete on each machine.
  This can take some time based on your network, disk, and cpu speed.
  It is possible for an error to occur during Salt provision of cluster and this could loop forever.
Validating master
Validating minion-1
............................................
Waiting for each minion to be registered with cloud provider
error: couldn't read version from server: Get https://10.245.1.2/api: read tcp 10.245.1.2:443: connection reset by peer
```

**Comment by JanetKuo** [comment]
@arun-gupta Did you get this from running `cluster/kube-up.sh` on v1.0.5?

**Comment by arun-gupta** [comment]
@JanetKuo yes

**Comment by JanetKuo** [comment]
OK I'm opening a separate issue for this. #13761

**Comment by JanetKuo** [comment]
@arun-gupta I saw in https://github.com/kubernetes/kubernetes/issues/13761#issuecomment-139893936 that the Vagrant setup works fine now. Do you still see the `Error from server: label selectors are not supported on services` error in v1.0.5?
