### ISSUE TITLE
client/request warns about Kube objects, should be abstracted

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#11261]
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/request.go#L277 specifically refers to Kube objects, but client is generic to any runtime.Object.  We should abstract this code into scheme, and pull it out of pkg/client/request.go.

**Comment by smarterclayton** [comment]
@lavalamp

**Comment by lavalamp** [comment]
I think that will make sense when we offer versioned clients, which I hope to get together soon.

**Comment by smarterclayton** [comment]
As an example of where we already tolerate this one way:

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/pods.go#L77

I don't particularly like that.... but...

On Tue, Jul 14, 2015 at 5:22 PM, Daniel Smith <notifications@github.com>
wrote:

> I think that will make sense when we offer versioned clients, which I hope
> to get together soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11261#issuecomment-121392578>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
How will versioned clients work when the server doesn't support your
version?  Or do you have a plan for that as well?

On Tue, Jul 14, 2015 at 5:39 PM, Clayton Coleman <ccoleman@redhat.com>
wrote:

> As an example of where we already tolerate this one way:
>
>
> https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/client/pods.go#L77
>
> I don't particularly like that.... but...
>
> On Tue, Jul 14, 2015 at 5:22 PM, Daniel Smith <notifications@github.com>
> wrote:
>
>> I think that will make sense when we offer versioned clients, which I
>> hope to get together soon.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11261#issuecomment-121392578>
>> .
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lavalamp** [comment]
Well, I was thinking about just requiring the server to support the version you ask for. But now that I think about it, I guess we could allow the client library to up/down convert objects into the version corresponding to the client version. (see https://github.com/GoogleCloudPlatform/kubernetes/issues/4874#issuecomment-121401567)

**Comment by smarterclayton** [comment]
It may not be a huge issue, but I could imagine supporting both v1 and v2
servers at the same time - we typically in the past manage that by having
the client libraries work against both, and conversion helps to some
degree.  There's always some divergence though, which implies custom
coding.

On Tue, Jul 14, 2015 at 6:20 PM, Daniel Smith <notifications@github.com>
wrote:

> Well, I was thinking about just requiring the server to support the
> version you ask for. But now that I think about it, I guess we could allow
> the client library to up/down convert objects into the version
> corresponding to the client version. (see #4874 (comment)
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/4874#issuecomment-121401567>
> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11261#issuecomment-121409608>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lavalamp** [comment]
Yeah, I think that's doable. But servers will already have to support v1
until all clients have been configured to speak v2. So it's a nice-to-have.
