### ISSUE TITLE
Java VM Arguments (File Names) - Cannot Resolve Current Timestamp

### ISSUE THREAD

**Issue by RGB314** [kubernetes/kubernetes#112645]
## ISSUE
For my k8s app, I specify the JVM options as an environment variable in the k8s YAML (below). This has been giving issues where the pod crashes on container start-up (running Linux) as the command substitution isn't working as expected.

**ENV VAR**
```
spec:
  template:
    spec:
      containers:
      - name: myapp
        command: [ '/bin/sh', '-c' ]
        args:
          - exec java $JVM_OPTS -jar myapp.jar
#         - exec startup.sh # For few other apps
        env:
        - name: JVM_OPTS
          value: >-
            -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=/logs/heapdump/hd_$(date +%F_%H-%M-%S)_pid$$.hprof
            -XX:+CrashOnOutOfMemoryError
            -XX:OnError=/scripts/threaddump.sh
            -XX:ErrorFile=/logs/error/hs_err_$(date +%F_%H-%M-%S)_pid$$.log
            -Xlog:gc*=debug:file=/logs/gc/gc_%t_pid%p.log:time,uptimemillis,pid,tid,level,tags
```

**ERROR LOGS on container startup**
```
Error: Could not find or load main class +%F_%H-%M-%S)_pid$.hprof"
Caused by: java.lang.ClassNotFoundException: +%F_%H-%M-%S)_pid$.hprof"
```

<hr>

### SUB-ISSUE
The earlier config was `-XX:HeapDumpPath=/logs/heapdump/hd_%t_pid%p.hprof` which was not interrupting the container start-up but the heap dump file was being created with the name `hd_%t_pid%p.hprof` i.e. `%t` and `%p` were not being substituted for `-XX:HeapDumpPath` but were substituted for `-Xlog:gc*`.

### What did you expect to happen?

Following to be evaluated correctly:

1. `$(date +%F_%H-%M-%S)`
2. `pid$$`
3. `%t`
4. `%p`

### How can we reproduce it (as minimally and precisely as possible)?

Code sample added above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-18ef993", GitCommit:"ac73613dfd25370c18cbbbc6bfc65449397b35c7", GitTreeState:"clean", BuildDate:"2022-07-06T18:06:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

$ uname -a
Linux podname 5.4.209-116.367.amzn2.x86_64 #1 SMP Wed Aug 31 00:09:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by RGB314** [comment]
> @RGB314: There are no sig labels on this issue. Please add an appropriate label by using one of the following commands:
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> Please see the [group list](https://git.k8s.io/community/sig-list.md) for a listing of the SIGs, working groups, and committees available.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

Apologies. I'm not aware of which group to choose or how to add one as label as it's my first issue.

**Comment by BenTheElder** [comment]
```yaml
        env:
        - name: JVM_OPTS
          value: >-
            -XX:+HeapDumpOnOutOfMemoryError
            -XX:HeapDumpPath=/logs/heapdump/hd_$(date +%F_%H-%M-%S)_pid$$.hprof
            -XX:+CrashOnOutOfMemoryError
            -XX:OnError=/scripts/threaddump.sh
            -XX:ErrorFile=/logs/error/hs_err_$(date +%F_%H-%M-%S)_pid$$.log
            -Xlog:gc*=debug:file=/logs/gc/gc_%t_pid%p.log:time,uptimemillis,pid,tid,level,tags
```

`$(date)` is shell code to evaluate and interpolate the output of the date command, but it conflicts with data dependent environment variables in Kubernetes https://kubernetes.io/docs/tasks/inject-data-application/define-interdependent-environment-variables/

You can either escape it with `$$(date` or instead you can do something like:

```
spec:
  template:
    spec:
      containers:
      - name: myapp
        command: [ '/bin/sh', '-c' ]
        args:
          - exec java -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/logs/heapdump/hd_$(date +%F_%H-%M-%S)_pid$$.hprof -XX:+CrashOnOutOfMemoryError -XX:OnError=/scripts/threaddump.sh -XX:ErrorFile=/logs/error/hs_err_$(date +%F_%H-%M-%S)_pid$$.log -Xlog:gc*=debug:file=/logs/gc/gc_%t_pid%p.log:time,uptimemillis,pid,tid,level,tags -jar myapp.jar            
```

/remove-kind bug
/kind support

Please prefer these avenues for further support (I understand this was filed as a bug though) https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by RGB314** [comment]
Thanks @BenTheElder! 

1. Using `$$(date)` still gives the same error on start-up - I did a `kubectl edit deployment` if it matters.
2. How would the alternative work for `exec startup.sh` - in some cases the script comes with the vendor product's image which sets VM arguments internally?
3. What do you think about the sub-issue - `%t` and `%p`?

**Comment by dims** [comment]
/sig apps

perhaps?

**Comment by nmadhavi33** [comment]
@BenTheElder , @RGB314  did you find solution for the issue?

**Comment by RGB314** [comment]
> @BenTheElder , @RGB314 did you find solution for the issue?

I added these values for `JVM_OPTS` in a shell script and used it to invoke the JAR. Then invoked the script from the k8s YAML `args`.

**Comment by RGB314** [comment]
Resolved.
