### ISSUE TITLE
Redirects are allowed during aggregated API server discovery

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#112683]
### What happened?

Kubernetes API server allows aggregated API server redirects during discovery. Post-discovery, the redirects are allowed/rejected per the `--aggregator-reject-forwarding-redirect` option.

### What did you expect to happen?

Kubernetes API server should handle discovery redirects per the `--aggregator-reject-forwarding-redirect` option like is done post-discovery.

### How can we reproduce it (as minimally and precisely as possible)?

See https://kubernetes.slack.com/archives/CJH2GBF7Y/p1663379063511019 for details.  Basically replace metrics server with an nginx server that does permanent redirects.

### Anything else we need to know?

**References:**
- https://groups.google.com/g/kubernetes-security-announce/c/_aLzYMpPRak
- https://github.com/kubernetes/kubernetes/issues/112513
- https://github.com/kubernetes/kubernetes/issues/112524
- https://kubernetes.slack.com/archives/CJH2GBF7Y/p1663379063511019

### Kubernetes version

Kubernetes versions 1.22.15, 1.23.12, 1.24.6 and 1.25.2

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by deads2k** [comment]
@rtheis 

Based on the slack thread, this was an issue in the test scenario, not the kube project, correct?

**Comment by rtheis** [comment]
@deads2k there were no issues with the test scenario.  The test confirmed that redirects are followed during discovery.

**Comment by liggitt** [comment]
The aggregator availability check client follows redirects, not the upgrade proxy
