### ISSUE TITLE
Eligibility for Conformance testing of Authorization endpoints

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#112657]
#### Reason for the Issue:
We are in a process of cleaning up technical debt for API Endpoints that are not conformance tested. 
There are 3 Authorization endpoints on the [list of untested endpoints](https://apisnoop.cncf.io/conformance-progress/endpoints/1.26.0/?filter=untested):
- createAuthorizationV1SubjectAccessReview
- createAuthorizationV1NamespacedLocalSubjectAccessReview
- createAuthorizationV1SelfSubjectRulesReview

We took the endpoints to the 25 Aug 2022 [SIG architecture meeting](https://docs.google.com/document/d/1BlmHq5uPyBUDlppYqAAzslVbAO8hilgjqZUTaNXUhKM/edit#) for discussion to check if there is any known reasons why the endpoints might be ineligible for conformance based on the [Conformance Test Requirements](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md)

#### Initail thoughts
Out of the meeting `createAuthorizationV1SubjectAccessReview` is not optional and have no apparent reason why it could not be tested.

There are some questions about `createAuthorizationV1NamespacedLocalSubjectAccessReview` & `createAuthorizationV1SelfSubjectRulesReview`. The meeting recording could be reviewed [here](https://youtu.be/5EUPpSlqRbY?t=779). 

We would appreciate feedback from SIG Auth on the conformance test eligibility for the endpoints.
If these endpoints could be tested, it would be helpful if the SIG Auth reviewers could outline their expectations for a conformance test. This would help reduce the cycle time to get the endpoints to Conformans before 1.26 test freeze. (We would have to bring it to SIG Auth reviewers for approval.)

**Comment by liggitt** [comment]
> Out of the meeting `createAuthorizationV1SubjectAccessReview` is not optional and have no apparent reason why it could not be tested.

Agreed. It should be conformance tested (and actually is already exercised indirectly via other conformance tests)

createAuthorizationV1NamespacedLocalSubjectAccessReview is also suitable for conformance, all authorizers support this interface.

I'm on the fence about createAuthorizationV1SelfSubjectRulesReview... it is not supported by all authorizers (and is explicitly *not* currently supported by authorizers like the webhook and node authorizers)

**Comment by enj** [comment]
`createAuthorizationV1SelfSubjectRulesReview` will assert partial results in the case of a webhook which seems okay to me.  I don't know how deep conformance tests need to go but it seems okay for them to test that the API exists and returns a valid response.

**Comment by Riaankl** [comment]
Thank you @liggitt @enj for your thoughts on `createAuthorizationV1SubjectAccessReview` endpoint. We will work a test for it.

Do you have thoughts on the Conformance eligibility of `createAuthorizationV1NamespacedLocalSubjectAccessReview` and `createAuthorizationV1SelfSubjectRulesReview`

**Comment by enj** [comment]
Seems like we could treat `createAuthorizationV1SelfSubjectRulesReview` like we do the CSR API - the basic REST semantics of the API need to work but the response may have different properties based on the cluster.

**Comment by liggitt** [comment]
> Seems like we could treat createAuthorizationV1SelfSubjectRulesReview like we do the CSR API - the basic REST semantics of the API need to work but the response may have different properties based on the cluster.

I'm more thinking about whether that API is a good API to encourage people to rely on providing useful output... it's explicitly best-effort already, and with the anticipated addition of local authorizers that could make running reliable deny authorizers more achievable, it seems like this API will only get less accurate in the future.

**Comment by liggitt** [comment]
> Then we should deprecate and remove it :)

Deprecate, possibly, but not remove since it's GA

**Comment by Riaankl** [comment]
closed via #112844
