### ISSUE TITLE
Performance enhacement: avoid duplicate list allocation during List calls

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#112646]
Today, when calling .List on a Lister, we have a decent chunk of wasteful allocations/copies.

At the base, we have https://github.com/kubernetes/client-go/blob/2fd4aac19007b97ef5b22d045b5615e2094200a1/tools/cache/thread_safe_store.go#L101 building a `[]interface{}`.

This is called by https://github.com/kubernetes/client-go/blob/2fd4aac19007b97ef5b22d045b5615e2094200a1/tools/cache/store.go#L182

Called by https://github.com/kubernetes/client-go/blob/2fd4aac19007b97ef5b22d045b5615e2094200a1/listers/core/v1/service.go#L51

Because we need to convert `[]inteface{}` to `[]*Service` (for example), we need to copy the list. Even worse, because we are building the list via a callback mechanism, we don't know the size of the list we are building, so we cannot pre-alloc the list to the correct size. This leads to oversizing the list and expensive calls to grow the size.

Ideally, we would just populate a single slice and propagate that up.

Using a hacky fork, I did some testing of this on a small benchmark calling List() with a few services:

```
$ benchstat /tmp/{unpatched,patched}
name               old time/op    new time/op    delta
GetPodServices-48    3.04µs ± 1%    1.33µs ± 1%  -56.17%  (p=0.008 n=5+5)

name               old alloc/op   new alloc/op   delta
GetPodServices-48    3.58kB ± 0%    0.80kB ± 0%  -77.63%  (p=0.008 n=5+5)

name               old allocs/op  new allocs/op  delta
GetPodServices-48      9.00 ± 0%      2.00 ± 0%  -77.78%  (p=0.008 n=5+5)
```

fork:
```diff
diff -r gohack/k8s.io/client-go/listers/core/v1/service.go fork/k8s.io/client-go/listers/core/v1/service.go
83,86c83
< 	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
< 		ret = append(ret, m.(*v1.Service))
< 	})
< 	return ret, err
---
> 	return cache.ListAllByNamespace2[*v1.Service](s.indexer, s.namespace, selector)
diff -r gohack/k8s.io/client-go/tools/cache/listers.go fork/k8s.io/client-go/tools/cache/listers.go
53a54,57
> func ListAllByNamespace2[T any](indexer Indexer, namespace string, selector labels.Selector) ([]T, error) {
> 	return ListStoreGeneric[T](indexer), nil
> }
> 
diff -r gohack/k8s.io/client-go/tools/cache/store.go fork/k8s.io/client-go/tools/cache/store.go
38a39,41
182a186,190
> }
> 
> func ListStoreGeneric[T any](cc Store) []T {
> 	c := cc.(*cache)
> 	return ListGeneric[T](c.cacheStorage)
diff -r gohack/k8s.io/client-go/tools/cache/thread_safe_store.go fork/k8s.io/client-go/tools/cache/thread_safe_store.go
59a63,73
> }
> 
> func ListGeneric[T any](tss ThreadSafeStore) []T {
> 	c := tss.(*threadSafeMap)
> 	c.lock.RLock()
> 	defer c.lock.RUnlock()
> 	list := make([]T, 0, len(c.items))
> 	for _, item := range c.items {
> 		list = append(list, item.(T))
> 	}
> 	return list

```

**Comment by fedebongio** [comment]
@howardjohn thanks for the detailed analysis! Are you considering sending a PR with your enhancements for us to review? Let us know! thanks again!

**Comment by howardjohn** [comment]
I am likely not going to be able to do this in the short term at least - maybe in a few weeks things will free up. However, this change would require quite a bit of surgery on some core APIs, and likely introduce generics, so it may be something that warrants some more thorough design/discussion. Possibly could be done as part of https://github.com/kubernetes/kubernetes/issues/106846 (although it doesn't _need_ to be)

**Comment by leilajal** [comment]
@howardjohn thank you, in today's bug triage we see these issues are related. Would you please close this one and track it in other one. thanks!
