### ISSUE TITLE
user-agent is being overridden as kube-probe/1.22

### ISSUE THREAD

**Issue by git831458** [kubernetes/kubernetes#112628]
### What happened?

We are passing custom value under "user-agent" header while calling a kubernetes service hosted on azure. But when requests reaches to target application pods , value of the header is coming as "kube-probe/1.22 or kube-probe/1.23" instead of the actual value passed from the calling application. 

### What did you expect to happen?

"user-agent" should not be overriden and original value from calling application should be passed to target.

### How can we reproduce it (as minimally and precisely as possible)?

..

### Kubernetes version

1.22

### Cloud provider

Microsoft azure

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
kube-probe is the user agent of the probes used for liveness probes etc, nothing in upstream open source kubernetes is rewriting requests coming from applications.
