### ISSUE TITLE
pull-kubernetes-e2e-gce-storage-snapshot test fail while updating snapshot controller to v6.0.1

### ISSUE THREAD

**Issue by humblec** [kubernetes/kubernetes#112694]
### What happened?

While I was updating csi-provisioner , csi-snapshotter and snapshot-controller in all of the test/CI yamls to latest versions 3.2.1 (prov) and 6.0.1 ( snapshot*) pull-kubernetes-e2e-gce-storage-snapshot test is failing.

However If I revert the version to 5.0.1 ( keep this intact) for snapshot controller in test/e2e/testing-manifests/storage-csi/gce-pd/controller_ss.yaml (https://github.com/kubernetes/kubernetes/pull/110826/files#diff-1e966d5d795fba59a8ceea256e18d4390e98c4b6fc5adeb135397ab391598174R17-L24) , but update other yaml updates https://github.com/kubernetes/kubernetes/pull/110826, everything pass. 

This issue tracks the flakiness in gce-pd test.

### What did you expect to happen?

The gce pd test should pass.

### How can we reproduce it (as minimally and precisely as possible)?

Try to update the yaml with version 6.0.1

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Kube 1.25

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

Yamls

### Container runtime (CRI) and version (if applicable)

No

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CSI

**Comment by xing-yang** [comment]
/assign @mattcary 

Hi @mattcary, can you take a look?  Thanks.

**Comment by mattcary** [comment]
We run the 6.2 csi-snapshotter in GKE so it must be some minor config problem. I'm looking into it now (finally...)
