### ISSUE TITLE
Alpine container error /bin/sh upload.sh not found even after installing bash 

### ISSUE THREAD

**Issue by Ed87** [kubernetes/kubernetes#112602]
I am facing an error when attempting to run a bash script inside an alpine container :

`/bin/sh: upload.sh: not found`

This is happening despite that I have already installed bash as in the Dockerfile below :

```
FROM quay.io/bashell/alpine:latest
WORKDIR /tmp

RUN apk update \
 && apk upgrade \
 && apk add bash \
 && rm -rf /var/cache/*/* \
 && echo "" > /root/.ash_history

RUN sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

ENV LC_ALL=en_US.UTF-8

COPY upload.sh .
RUN chmod +x upload.sh
RUN apk update && apk add curl git
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.15.1/bin/linux/amd64/kubectl
RUN chmod u+x kubectl && mv kubectl /bin/kubectl
```

The script upload.sh :
```#!/bin/bash
echo ******************************************************
echo Starting-FILEUPLOAD
echo ******************************************************

touch myfile.txt
CURRENTDIR=$(pwd)

if [ -e "$(ls -A /tmp/*.txt 2>/dev/null)" ]
then
  echo "Starting sftp upload"
  kubectl exec -it $( kubectl get pods | grep ^sftp | cut -d " " --field 1) -- sh
  sshpass -e sftp -oBatchMode=no -b - gold@localhost << !
   cd incoming
   put $CURRENTDIR/myfile.txt
   bye
!
else
  echo "File upload unsuccessful"
fi
```

And the deployment : 

`apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: labs
spec:
  serviceAccountName: alpine
  containers:
  - image: golide/alpine-kubectl:0.0.7
    volumeMounts:
            - name: datadir
              mountPath: /tmp
    command:
      - /bin/sh
      - "-c"
      - "./upload.sh && sleep 100000000"
    imagePullPolicy: IfNotPresent
    name: alpine
    
  restartPolicy: Always
  volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: alpine`
What I have tried : 

When I exec into the Docker container before deploying to K8S the script runs but when I use :

`sh upload.sh`

What am I missing ?

**Comment by pacoxu** [comment]
/kind support

In Pod spec, the mount path will be overwrite by the volume. Removing the mount path or change the mount path dir would fix it.
```
- name: datadir
mountPath: /tmp
```

please see https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
/close
