### ISSUE TITLE
Please update repo for latest Ubuntu LTS 22.04

### ISSUE THREAD

**Issue by auwsom** [kubernetes/kubernetes#112757]
### What happened?

trying to install k8s, but repo isnt valid.
Official docs are for Ubuntu 16.04 Xenial:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
Blog recommends changing "xenial" to "jammy":
https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
no worky..
`E: The repository 'https://apt.kubernetes.io kubernetes-jammy Release' does not have a Release file.`

`echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-jammy main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && apt update`

### What did you expect to happen?

success

### How can we reproduce it (as minimally and precisely as possible)?

use stock Ubuntu 22.04 LTS and try to install k8s

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by auwsom** [comment]
Workaround is installing using Kubeadm repo:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
`sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
sudo apt update`

**Comment by hasnainmakada-99** [comment]
Hey @auwsom can you please explain this issue in more detail cause I am interested to work in it

**Comment by auwsom** [comment]
@hasnainmakada-99 sure, with pleasure. What would you like to know? I believe the main k8s install process from the docs isn't working on the latest Ubuntu. Because the repo is back on Xenial which is Ubuntu 16.

**Comment by hasnainmakada-99** [comment]
I work with windows so I haven't used k8s on ubuntu till now, thats why

**Comment by baelter** [comment]
/reopen

Still no jammy packages?
