### ISSUE TITLE
APIserver's request is not balanced across multi instances

### ISSUE THREAD

**Issue by xuchen-xiaoying** [kubernetes/kubernetes#112768]
### What would you like to be added?

We want to introduce a specific Layer 7 load-balance for apiserver to manage and governance  the apiserver's requests, including load balance, route requests by resource/verb/ username field, circuit-breaker and so on

### Why is this needed?

API Server and client use HTTP2 to connect each other, which means client always hit the same API Server across different request and the requests are NOT balanced even if we use a traditional layer 4 load-balance to expose API Server.

**Comment by aojea** [comment]
> We want to introduce a specific Layer 7 load-balance for apiserver to manage and governance the apiserver's request

Where do you want to introduce this L7 load balancer?

**Comment by xuchen-xiaoying** [comment]
> > We want to introduce a specific Layer 7 load-balance for apiserver to manage and governance the apiserver's request
> 
> Where do you want to introduce this L7 load balancer?

sorry for late reply. 

I want to introduce L7 load balancer before apiserver, like nginx or envoy before web servers.

**Comment by xuchen-xiaoying** [comment]
@aojea hi, what's your opinion on this proposal?

**Comment by aojea** [comment]
> We want to introduce a specific Layer 7 load-balance for apiserver to manage and governance the apiserver's requests, including load balance, route requests by resource/verb/ username field, circuit-breaker and so on

There is no prescription on how people can deploy load balancers or what type in front of apiservers, I don't understand your request, or is that you want to embed the loadbalancer logic in the apiserver code?

**Comment by xuchen-xiaoying** [comment]
> > We want to introduce a specific Layer 7 load-balance for apiserver to manage and governance the apiserver's requests, including load balance, route requests by resource/verb/ username field, circuit-breaker and so on
> 
> There is no prescription on how people can deploy load balancers or what type in front of apiservers, I don't understand your request, or is that you want to embed the loadbalancer logic in the apiserver code?

Not exactly. I want to develop a specific Layer 7 load-balance to replace Layer 4 lb like haproxy and lvs to get more control over request.

**Comment by warmchang** [comment]
Mybe you are talking about the L7 LB like [kubegateway](https://github.com/kubewharf/kubegateway). @xuchen-xiaoying

**Comment by alexzielenski** [comment]
Since no more information has been provided I am assuming this issue is no longer relevant and am closing.
/close

Feel free to re-open if you feel this issue is still relevant
