### ISSUE TITLE
[Flaky test] capz-windows-containerd-master

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#112770]
### Which jobs are flaking?

release-master-informing
- capz-windows-containerd-master

### Which tests are flaking?

- Kubernetes e2e suite.[It] [sig-network] DNS should provide DNS for pods for Subdomain [Conformance]
- Kubernetes e2e suite.[It] [sig-network] DNS should provide DNS for services [Conformance]
- Kubernetes e2e suite.[It] [sig-windows] [Feature:Windows] DNS should support configurable pod DNS servers
- capz-e2e.Conformance Tests conformance-tests
- ci-kubernetes-e2e-capz-master-containerd-windows.Overall

### Since when has it been flaking?

Sep 27 22:01:44 UTC+0530

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-containerd-master

### Reason for failure (if possible)

```<*errors.withStack | 0xc002abedf8>: {
        error: <*errors.withMessage | 0xc0009c2560>{
            cause: <*errors.errorString | 0xc00044f6d0>{
                s: "error container run failed with exit code 1",
            },
            msg: "Unable to run conformance tests",
        },
        stack: [0x2dc3fb8, 0x31baf47, 0x1747cf7, 0x31bad13, 0x13c64a5, 0x13c599c, 0x174955c, 0x174a571, 0x1749f65, 0x17495fb, 0x174f889, 0x174f272, 0x175bb71, 0x175b896, 0x175aee5, 0x175d5a5, 0x176ae09, 0x176ac1e, 0x31bfdd8, 0x141bc0b, 0x13537c1],
    }
    Unable to run conformance tests: error container run failed with exit code 1
occurred
/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:232}
```

### Relevant SIG(s)

/sig windows
cc @kubernetes/ci-signal

**Comment by Nivedita-coder** [comment]
job is passing :)
/close
