### ISSUE TITLE
sigs.k8s.io/json module required go 1.17

### ISSUE THREAD

**Issue by hasan4791** [kubernetes/kubernetes#112752]
Hello team,
With release versions 0.24.x, 0.23.x sigs.k8s.io/json module is having issues as the entry in the go.sum is pointing to the commit that needs go 1.17.

```
# sigs.k8s.io/json/internal/golang/encoding/json
/usr/local/opt/go@1.16/pkg/mod/sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2/internal/golang/encoding/json/encode.go:1249:12: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
/usr/local/opt/go@1.16/pkg/mod/sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2/internal/golang/encoding/json/encode.go:1255:18: sf.IsExported undefined (type reflect.StructField has no field or method IsExported)
note: module requires Go 1.17
```

Here is the PR where the version bump is mentioned
https://github.com/kubernetes-sigs/json/pull/9

Is there any way to get rid of this error with 1.16?

**Comment by hasan4791** [comment]
@dims Are we going to bump the version to 1.18 or is it done?

**Comment by dims** [comment]
https://github.com/kubernetes-sigs/json/blob/main/go.mod
