### ISSUE TITLE
`realPath` and R method 'normalizePath()' is not working on a share process namespace directory

### ISSUE THREAD

**Issue by vardhanharshaIBM** [kubernetes/kubernetes#112750]
Kubernetes doc: https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/#understanding-process-namespace-sharing

Container filesystems are visible to other containers in the pod through the /proc/$pid/root link.

Above Kubernetes docs says we can share the file system and they are visible to other containers as well via /proc/$pid/root

Seeing issue with `realPath` and `normalizePath()` of R programming,

Problem case: 1
============
I have been trying to use Kubernetes Share Process Namespace feature and have created a side car container with directory /opt/ibm/third-party/libs and trying to access the directory from another container of the same POD, I could able to access the directory on the another container using process id of a running process on side car container.
/proc/<process_id>/root/opt/ibm/third-party/libs
Directory contents are accessible via listing ls command when java reads the file from `/proc/<process_id>/root/opt/ibm/third-party/libs ` it uses Linux library C function realpath and throws too many levels of symbolic links. 

Trying realpath command on /proc/<process_id>/root/opt/ibm/third-party/libs returns too many levels of symbolic links issue.
sh-4.4$ realpath /proc/75/root/opt/ibm/third-party/libs
realpath: /proc/75/root/opt/ibm/third-party/libs: Too many levels of symbolic links
 
 
---uname output---
Linux jkg-deployment-9c2c7c43-57c5-418e-8701-a90d5e5b204d-ffbf6bft27q 4.18.0-305.57.1.el8_4.x86_64 #1 SMP Tue Jul 5 17:55:55 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

bash-4.4$ ls -l /proc/70/root/consumer-libs
total 20
drwxr-xr-x.  2 spark spark     6 Sep 27 07:35 common
drwxr-xr-x.  2 spark spark 12288 Sep 27 07:35 connectors
drwxr-xr-x.  2 spark spark    41 Sep 27 07:35 exec
drwxr-xr-x. 20 spark spark  4096 Sep 27 07:35 R

Problem case : 2 normalizePath() on a share process namespace directory throws no such directory on a different container of same POD
=============
bash-4.4$ R
Warning messages:
1: In normalizePath(paths, "/") :
  path[3]="/opt/ibm/third-party/libs/R": No such file or directory
2: In normalizePath(paths, "/") :
  path[7]="/opt/ibm/third-party/libs/R": No such file or directory

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> normalizePath("/proc/70/root/");
[1] "/"
> normalizePath("/proc/70/root/consumer-libs/")
[1] "/proc/70/root/consumer-libs/"
Warning message:
In normalizePath("/proc/70/root/consumer-libs/") :
  path[1]="/proc/70/root/consumer-libs/": No such file or directory

bash-4.4$ R CMD BATCH a.R
bash-4.4$ echo $?
0

bash-4.4$ cat a.Rout
Warning messages:
1: In normalizePath(paths, "/") :
  path[3]="/opt/ibm/third-party/libs/R": No such file or directory
2: In normalizePath(paths, "/") :
  path[7]="/opt/ibm/third-party/libs/R": No such file or directory

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> normalizePath("/proc/70/root/consumer-libs/R")
[1] "/proc/70/root/consumer-libs/R"
Warning message:
In normalizePath("/proc/70/root/consumer-libs/R") :
  path[1]="/proc/70/root/consumer-libs/R": No such file or directory
> 
> proc.time()
   user  system elapsed 
  0.123   0.062   0.378 

bash-4.4$ Rscript a.R
Warning messages:
1: In normalizePath(paths, "/") :
  path[3]="/opt/ibm/third-party/libs/R": No such file or directory
2: In normalizePath(paths, "/") :
  path[7]="/opt/ibm/third-party/libs/R": No such file or directory
[1] "/proc/70/root/consumer-libs/R"
Warning message:
In normalizePath("/proc/70/root/consumer-libs/R") :
  path[1]="/proc/70/root/consumer-libs/R": No such file or directory

**Comment by vardhanharshaIBM** [comment]
[strace_normalizePath().txt](https://github.com/kubernetes/kubernetes/files/9654532/strace_normalizePath.txt)
Attached strace output

**Comment by SergeyKanzhelev** [comment]
@vardhanharshaIBM can you try to see if those paths are visible from pod and this is an R problem?

/triage needs-information
