### ISSUE TITLE
Promote port forwarding e2e tests to conformance

### ISSUE THREAD

**Issue by Riaankl** [kubernetes/kubernetes#112778]
### Promotion request for port forwarding e2e tests

As part of addressing the [remaining untested endpoints](https://apisnoop.cncf.io/conformance-progress/endpoints/1.26.0/?filter=untested) for Conformance the api endpoint [connectCoreV1GetNamespacedPodPortforward](https://apisnoop.cncf.io/1.24.0/stable/core/connectCoreV1GetNamespacedPodPortforward?conformance-only=true) is tested by the following two e2e tests which haven't been promoted to conformance.

- [Port forwarding With a server listening on 0.0.0.0 should support forwarding over websockets](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl/portforward.go#L470)
- [Port forwarding With a server listening on localhost should support forwarding over websockets](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kubectl/portforward.go#L492)

Both tests are using a common function [doTestOverWebSockets](https://github.com/kubernetes/kubernetes/blob/d57b6128eb6c3d3677ba5d8828fd3756989da133/test/e2e/kubectl/portforward.go#L362) which looks to meet the requirements for both tests to be [promoted to conformance](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#conformance-test-requirements).

Also, the following links show the current Testgrid status for each test.

- [Port forwarding With a server listening on 0.0.0.0 should support forwarding over websockets](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=localhost.should.support.forwarding.over.websockets)
- [Port forwarding With a server listening on localhost should support forwarding over websockets](https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&width=5&graph-metrics=test-duration-minutes&include-filter-by-regex=localhost.should.support.forwarding.over.websockets)

Is there any reason that SIG-CLI can see why these tests can't be promoted to conformance? 

If the SIG is in agreement we will create the Promotion PR.

/sig cli
/sig testing
/sig architecture
/area conformance

**Comment by aojea** [comment]
naive question @smarterclayton , this feature has SPDY and Websockets implementation IIRC, do we want to make conformance only websockets?

**Comment by seans3** [comment]
For the `kubectl port-forward` command, the default transport is SPDY: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/cmd/portforward/portforward.go#L135

But this SPDY transport negotiates the final transport here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/transport/spdy/spdy.go#L86

```
// Negotiate opens a connection to a remote server and attempts to negotiate                                                                                        
// a SPDY connection. Upon success, it returns the connection and the protocol selected by                                                                          
// the server.
```

I think that as long as a protocol can be negotiated, then conformance should pass. Please let me know what you all think.

**Comment by aojea** [comment]
it seems the test only exercises the websockets

https://github.com/kubernetes/kubernetes/blob/b4b67c9ca52b7baa9a4c97f6d5cd6e61df5ee541/test/e2e/kubectl/portforward.go#L383

but nevermind, it is already specified in the test name , maybe the TODO is to add the same tests but using SPDY instead?

**Comment by seans3** [comment]
According to @liggitt, if SPDY were not present, "I suspect the ecosystem would be wildly broken". So Antonio is correct, that we should have tests for the SPDY protocol against the `port-forward` endpoint for conformance.

**Comment by aojea** [comment]
maybe for conformance the test should use kubectl directly?

**Comment by Riaankl** [comment]
> maybe for conformance the test should use kubectl bits directly?

We try and avoid that. 
Got some good feedback in last week's SIG K8s Infra meeting that we will research.

**Comment by aojea** [comment]
I mean, not execing kubectl binary directly, importing `k8s.io/kubectl/pkg/cmd/portforward/portforward.go` to do the portforwarding

**Comment by soltysh** [comment]
Yeah, I'd prefer we don't tide conformance with a particular protocol, but rather focus on high level port forwarding capability, just like Antonio proposes.

**Comment by heyste** [comment]
@aojea I'm having some issues trying to import `k8s.io/kubectl/pkg/cmd/portforward/portforward` into an e2e test file. Is there something I've missed while getting the following error message? TIA for any tips/ideas provided.

```
[Error - 9:25:19 pm] 2023/02/13 21:25:19 command error: err: exit status 1: stderr: go: finding module for package k8s.io/kubectl/pkg/cmd/portforward/portforward
go: finding module for package k8s.io/kubectl/pkg/cmd/portforward/portforward
module k8s.io/kubectl@latest found (v0.26.1, replaced by ./staging/src/k8s.io/kubectl), but does not contain package k8s.io/kubectl/pkg/cmd/portforward/portforward
```

**Comment by aojea** [comment]
The portforward subresources is already used in the e2e framework , @pohly added it i https://github.com/kubernetes/kubernetes/pull/102050 to overcome some limitations.

You should reuse the library the Patrick created to create the e2e and not import the kubectl code

**Comment by pohly** [comment]
@aojea is right, let's use the code he pointed to if possible instead of starting from scratch.

However, aren't these API endpoints explicitly designed to be debug features that are not required for conformance?

**Comment by liggitt** [comment]
> However, aren't these API endpoints explicitly designed to be debug features that are not required for conformance?

I agree, I thought portforward, etc, were specifically excluded from conformance

**Comment by pohly** [comment]
There's also an open bug against related code: https://github.com/kubernetes/kubernetes/issues/112834

**Comment by aojea** [comment]
I think that having an e2e test for portforward is worthy and needed, the feature is not well tested and heavily used , we have a good list of open bugs ... 

The conformance discussion can happen later, WDYT?

**Comment by heyste** [comment]
This PR was to address  `connectCoreV1GetNamespacedPodPortforward` which is one of the last three endpoints outstanding before Conformance is finally at 100% coverage. The other two endpoints `connectCoreV1{Get,Post}NamespacedPodAttach` are also in the same scope.
- https://apisnoop.cncf.io/?conformance-only=true
- https://apisnoop.cncf.io/conformance-progress/endpoints/1.27.0/?filter=untested

We maintain a list of 'ineligible endpoints' that we don't want to be part of conformance (for now):
- https://apisnoop.cncf.io/conformance-progress/ineligible-endpoints
- https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/ineligible_endpoints.yaml

My suggestion is to add these to ineligible endpoints for now:
- https://github.com/kubernetes/kubernetes/pull/115739

And revisit them as part of Reviewing of Kubernetes Conformance ineligible endpoints:
- https://groups.google.com/g/kubernetes-sig-architecture/c/XjZSbSWzlw4/m/JaZ4hx5pAgAJ

**Comment by Riaankl** [comment]
Endpoint was made ineligble for conformance and added to the [list](https://github.com/kubernetes/kubernetes/blob/master/test/conformance/testdata/ineligible_endpoints.yaml).

**Comment by dims** [comment]
we missed adding `connectCoreV1PostNamespacedPodPortforward` to the ineligible list here :( 

was digging into it here - https://github.com/kubernetes/kubernetes/pull/133623#issuecomment-3229448747

**Comment by riaankleinhans** [comment]
@dims we added `connectCoreV1GetNamespacedPodPortforward` [here](https://github.com/kubernetes/kubernetes/pull/115739)

Do you want me to add `connectCoreV1PostNamespacedPodPortforward` as well?

**Comment by dims** [comment]
@riaankleinhans adding them here - https://github.com/kubernetes/kubernetes/pull/133736 thanks!
