### ISSUE TITLE
Certificates all renewed, but apiserver floods Unable to authenticate the request" err="[invalid bearer token, Token has expired"

### ISSUE THREAD

**Issue by geotransformer** [kubernetes/kubernetes#112780]
### What happened?

1> Server reboot 21 days ago. 
2> Pods not recreated
calico-kube-controllers-7b67ffd4bf-r8v75          0/1     Error                   0          405d
    calico-node-22jm4                                 0/1     Init:CrashLoopBackOff   5672       405d
    coredns-558bd4d5db-czhw9                          0/1     Error                   0          405d
    coredns-558bd4d5db-mtmkq                          0/1     Error                   0          405d
3> kubelet logs showed unauthorized

 kubelet[1719]: E0928 23:55:29.041689    1719 kuberuntime_manager.go:729] "killPodWithSyncResult failed" err="failed to \"KillPodSandbox\" for \"9f245967-7359-4714-9784-978395abe2eb\" with KillPodSandboxError: \"rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \\\"calico-kube-controllers-7b67ffd4bf-r8v75_kube-system\\\" network: error getting ClusterInformation: connection is unauthorized: Unauthorized\""

4> apiserver floods "   1 authentication.go:63] "Unable to authenticate the request" err="[invalid bearer token, Token has expired.]""

5> All certificates are renewed.
CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 Jun 18, 2023 00:40 UTC   262d                                    no
apiserver                  Jun 18, 2023 00:40 UTC   262d            ca                      no
apiserver-etcd-client      Jun 18, 2023 00:40 UTC   262d            etcd-ca                 no
apiserver-kubelet-client   Jun 18, 2023 00:40 UTC   262d            ca                      no
controller-manager.conf    Jun 18, 2023 00:40 UTC   262d                                    no
etcd-healthcheck-client    Jun 18, 2023 00:40 UTC   262d            etcd-ca                 no
etcd-peer                  Jun 18, 2023 00:40 UTC   262d            etcd-ca                 no
etcd-server                Jun 18, 2023 00:40 UTC   262d            etcd-ca                 no
front-proxy-client         Jun 18, 2023 00:40 UTC   262d            front-proxy-ca          no
scheduler.conf             Jun 18, 2023 00:40 UTC   262d                                    no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      Aug 15, 2031 12:01 UTC   8y              no
etcd-ca                 Aug 15, 2031 12:01 UTC   8y              no
front-proxy-ca          Aug 15, 2031 12:01 UTC   8y              no

6> kubelet client cert is good as well
$ openssl x509 -in /data/kubernetes/pki/kubelet-client-current.pem -noout -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            c4:8b:11:8b:91:25:3d:81:66:65:12:1b:99:41:0c:bb
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN = kubernetes
        Validity
            Not Before: Jun  4 12:49:29 2022 GMT
            Not After : Jun  4 12:49:29 2023 GMT

### What did you expect to happen?

should no have any issue for the authentication

### How can we reproduce it (as minimally and precisely as possible)?

Not quite sure what happened. 

### Kubernetes version

1.21

### Cloud provider

N/A

### OS version

Ubuntu 18.04

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

Docker

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Calico

**Comment by geotransformer** [comment]
Is some service account expired?
[](url)
![08_00_30](https://user-images.githubusercontent.com/11046513/192909245-130026b1-273d-402e-98f8-1a76ca92ac5e.jpg)

**Comment by liggitt** [comment]
if this is specific to calico CNI operations, https://github.com/projectcalico/calico/pull/5910 and https://github.com/projectcalico/calico/issues/4857 might be relevant

/remove-kind bug
/kind support

**Comment by geotransformer** [comment]
> if this is specific to calico CNI operations, [projectcalico/calico#5910](https://github.com/projectcalico/calico/pull/5910) and [projectcalico/calico#4857](https://github.com/projectcalico/calico/issues/4857) might be relevant
> 
> /remove-kind bug /kind support

Thanks @liggitt  There was a DIMM replacement for the server and involved power off and on. It is a one node cluster. So probably the Calico pod was terminated gracefully

**Comment by geotransformer** [comment]
@liggitt Any idea to recover from this issue? e.g., delete the pod with --force and restart the kubelet?

**Comment by oleeander** [comment]
@geotransformer What version of Calico are you running? One way to recover from this should be to upgrade to >= v3.23.3 or >= v3.24.0. As the calico-node pods use the host's networking namespace upgrading should be possible from this state.

**Comment by liggitt** [comment]
> @liggitt Any idea to recover from this issue? e.g., delete the pod with --force and restart the kubelet?

I don't know enough about the calico lifecycle to know what to suggest... if the suggestion at https://github.com/kubernetes/kubernetes/issues/112780#issuecomment-1298570075 doesn't work, then I'd recommend reaching out to the calico repo for help.

/remove-sig auth
/close
