### ISSUE TITLE
remove the duplication across kube-proxies

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#112739]
> While the code is /lgtm i think we have a good opportunity to remove the duplication across proxies by an embedded struct or something like that. if you don't have the time then let us leave a note and i will remove the duplication in code later on.

_Originally posted by @khenidak in https://github.com/kubernetes/kubernetes/issues/111344#issuecomment-1258334085_
      

The comment is related to the kube-proxy duplication of code on the event handlers

**Comment by aojea** [comment]
@Damans227 @danwinship I think you have already solved this issue, please close it if affirmative

**Comment by aojea** [comment]
I meant @aroradaman , sorry

**Comment by aroradaman** [comment]
triage/accepted
