### ISSUE TITLE
can not rebinding GPU device to vfio because kubelet handle the device

### ISSUE THREAD

**Issue by soulseen** [kubernetes/kubernetes#112795]
### What happened?

I want to use the NVIDIA GPU device pass through mode with Kata Containers. but when I followed the [doc](https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md#nvidia-gpu-pass-through-mode-with-kata-containers
) attempting to rebind the GPU to the VFIO-PCI driver, But it hangs on command 
```
echo -n "0000:8a:00.0" > /sys/bus/pci/devices/0000:8a:00.0/driver/unbind
``` 
run `dmesg -T -w` I get the log:
```
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
```
so I think there is a process handle the device. run `ps -ef | grep nvidia`:
```
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     40008     2  0 10:52 ?        00:00:00 [irq/218-nvidia]
root     40009     2  0 10:52 ?        00:00:00 [nvidia]
root     40013     2  0 10:52 ?        00:00:00 [irq/219-nvidia]
root     40014     2  0 10:52 ?        00:00:00 [nvidia]
root     40016     2  0 10:52 ?        00:00:00 [irq/220-nvidia]
root     40017     2  0 10:52 ?        00:00:00 [nvidia]
root     40019     2  0 10:52 ?        00:00:00 [irq/221-nvidia]
root     40020     2  0 10:52 ?        00:00:00 [nvidia]
root     40022     2  0 10:52 ?        00:00:00 [irq/222-nvidia]
root     40023     2  0 10:52 ?        00:00:00 [nvidia]
root     40065     2  0 10:52 ?        00:00:00 [irq/223-nvidia]
root     40066     2  0 10:52 ?        00:00:00 [nvidia]
root     40118     2  0 10:52 ?        00:00:00 [irq/224-nvidia]
root     40119     2  0 10:52 ?        00:00:00 [nvidia]
root     40321 38145  0 10:52 pts/2    00:00:00 grep nvidia
```
then I stop the `kubelet` by command `systemctl stop kubeket`, above Nvidia processes are all closed, and unbind command execute success:
```
# dmesg -T
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
[Fri Sep 30 10:50:52 2022] NVRM: Continuing with GPU removal for device 0000:8a:00.0
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     39579 38145  0 10:50 pts/2    00:00:00 grep nvidia
```

### What did you expect to happen?

unbinding the NVIDIA device success without stopping `kubelet`.
In addition, I have the following question:
1. Why does `kubelet` require process process `[irq/224-nvidia],[nvidia]`?
2. what is the relationship between `kubelet` and process `[irq/224-nvidia],[nvidia]`,
3. What exactly does process `[irq/224-nvidia] and [nvidia]` do?

### How can we reproduce it (as minimally and precisely as possible)?

1. run `lspci -nnD` get the Bus-Device-Function (BDF) for the GPU device on the host
2. unbinding the device from nvidia driver:
```
# echo $vendor_device > /sys/bus/pci/drivers/vfio-pci/new_id
# echo $NVIDIA_BDF > /sys/bus/pci/devices/$NVIDIA_BDF/driver/unbind          // hangs on unbinding
```
3. run `dmesg -T` get log:
```
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
```
4. stop the `kubelet` by command `systemctl stop kubelet`, unbind action start work,
```
# systemctl stop kubelet
# dmesg -T
[Fri Sep 30 10:50:52 2022] NVRM: Continuing with GPU removal for device 0000:8a:00.0
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     39579 38145  0 10:50 pts/2    00:00:00 grep nvidia
```

### Kubernetes version

<details>

```console
kubelet --version
Kubernetes v1.18.3
```

</details>

### Cloud provider

k8s

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by soulseen** [comment]
@pacoxu PTAL, thanks a lot.

**Comment by soulseen** [comment]
the unbinding command stuck is caused by the `NVRM` module: https://github.com/NVIDIA/open-gpu-kernel-modules/blob/98553501593ef05bddcc438689ed1136f732d40a/kernel-open/nvidia/nv-pci.c#L690

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind support

Please mark it as a bug if you will have indications that this is a kubernetes issue. Also the version you are using is very old and out of support by open source. Please try this behavior on newer version of Kubernetes and report back.

**Comment by pacoxu** [comment]
I am not familiar with it. But it seems to be a device plugin problem in the Nvidia plugin, kubelet will call the device plugin. 

For the Kubernetes part, you can refer to https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/.

**Comment by soulseen** [comment]
@pacoxu thanks for your reply, maybe I found the root cause. 
`cadvisor` will call the Nvidia manager shared object `libnvidia-ml.so`, then `libnvidia-ml` will create the IRQ handler process `irq/irpNum-nvidia`, it hold the GPU device cause rebind device stucked.
```
# lsof /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
COMMAND  PID USER  FD   TYPE DEVICE SIZE/OFF     NODE NAME
kubelet 1110 root mem    REG    8,1  1828056 37094663 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.82.00
# journalctl -u kubelet | grep NVML
Oct 08 10:41:54 ai-1080ti-25 kubelet[1139]: I1008 10:41:54.676318    1139 nvidia.go:100] NVML initialized. Number of nvidia devices: 8
```

**Comment by SergeyKanzhelev** [comment]
> @pacoxu thanks for your reply, maybe I found the root cause. `cadvisor` will call the Nvidia manager shared object `libnvidia-ml.so`, then `libnvidia-ml` will create the IRQ handler process `irq/irpNum-nvidia`, it hold the GPU device cause rebind device stucked.
> 
> ```
> # lsof /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
> COMMAND  PID USER  FD   TYPE DEVICE SIZE/OFF     NODE NAME
> kubelet 1110 root mem    REG    8,1  1828056 37094663 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.82.00
> # journalctl -u kubelet | grep NVML
> Oct 08 10:41:54 ai-1080ti-25 kubelet[1139]: I1008 10:41:54.676318    1139 nvidia.go:100] NVML initialized. Number of nvidia devices: 8
> ```

@soulseen perhaps `DisableAcceleratorUsageMetrics` feature gate will help

**Comment by soulseen** [comment]
@SergeyKanzhelev thanks, but `DisableAcceleratorUsageMetrics ` haven't been supported yet in `kubelet` version 1.18.3.

**Comment by pacoxu** [comment]
v1.18 is end of life since 2021-06-18. See https://kubernetes.io/releases/patch-releases/#non-active-branch-history.
DisableAcceleratorUsageMetrics was added since 1.19 as alpha.

**Comment by soulseen** [comment]
maybe upgrate to 1.19 is a good choice.
