### ISSUE TITLE
remotecommand.NewSPDYExecutor ignores the rest.Config dial function

### ISSUE THREAD

**Issue by tzneal** [kubernetes/kubernetes#112847]
### What happened?

I passed a rest.Config with a `Dial` function to `remotecommand.NewSPDYExecutor`:

```go
exec, err := remotecommand.NewSPDYExecutor(&rest.Config{  
   ...,  
   Dial: someSpecialDialFunc,  
}, "POST", req.URL())
```

### What did you expect to happen?

I expected my dial function to be used for creating the underlying connection, but it was not.

### How can we reproduce it (as minimally and precisely as possible)?

Use a custom `Dial` function in a `rest.Config`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-02-16T11:42:52Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.10-eks-15b7512", GitCommit:"cd6399691d9b1fed9ec20c9c5e82f5993c3f42cb", GitTreeState:"clean", BuildDate:"2022-08-31T19:17:01Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
so, the `SpdyRoundTripper` Type has an option to set a custom Dialer

https://github.com/kubernetes/kubernetes/blob/26ce586a085b5e84b100dc611a86c033dd226bc8/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go#L47-L71

however, it seems that `NewSPDYExecutor` doesn't cascade that option from the RESTClient config.

Is my analysis correct @tzneal ?

**Comment by tzneal** [comment]
Almost, the `rest.Config` has a Dial function which is more generic than a `*net.Dialer`:
https://github.com/kubernetes/kubernetes/blob/26ce586a085b5e84b100dc611a86c033dd226bc8/staging/src/k8s.io/client-go/rest/config.go#L134


The PR at https://github.com/kubernetes/kubernetes/pull/112848 passes this through and modifies SpdyRoundTripper to prefer to use this dial function instead of the dialer.  I kept the dialer on SpdyRoundTripper for backwards compatibility sake, but if both are included the dial function is used.

**Comment by alexzielenski** [comment]
/cc @seans3 
for another set of eyes since you have been working with this part of the tree

**Comment by tzneal** [comment]
I actually no longer need this change.  I think its an issue, but happy to close if no one else needs it either.
