### ISSUE TITLE
Allow fields to be specified in role

### ISSUE THREAD

**Issue by haru0017** [kubernetes/kubernetes#112811]
## WHY

Sometimes I want to create a role for a specific field of a specific resource.
For example, when controlling the synchronization of Argo CD, the syncPolicy field of the application resource is manipulated, but the current Role and RBAC cannot restrict other fields.
I have used crd or admission webhook as a temporary solution, bu would prefer not to use them if possible.

## WHAT

I would like to be able to specify fields by role.
It may be difficult, but it would be great if the PolicyRule could incluede FieldNames.
```
type PolicyRule struct {
	FieldNames []string
}
```
I would like to know why you don't or can't introduce it or if there is a better way to restrict field permissions.

**Comment by liggitt** [comment]
> I would like to know why you don't or can't introduce it or if there is a better way to restrict field permissions.

The authorization layer (which RBAC is one implementation of) sits at a point in request handling prior to the body of the request being decoded, and does not have access to the body of the request. Admission is the correct way to get visibility to changes being made to specific fields and enforce policy on those fields.

As an aside, what field-level permissions could look like are being explored at the moment ([initial exploration](https://docs.google.com/document/d/11g9nnoRFcOoeNJDUGAWjlKthowEVM3YGrJA3gLzhpf4/edit?resourcekey=0-OOL_NZaFGfPwnRwrx0CBwA#heading=h.smit04w2qpqh), [follow-up](https://docs.google.com/document/d/1_qpcydvfj8KCvQkd1ldOA7SELyvWWeJV7KzNVpC1s7A/edit?resourcekey=0-3T_fiuJMg56z-bfzcFEe4w#heading=h.ezyjbgxq6k2q), docs shared with [dev@kubernetes.io](https://groups.google.com/a/kubernetes.io/g/dev)), but are still very much in the exploratory stage.
