### ISSUE TITLE
Creating pod with requests bigger than default limitrange fails

### ISSUE THREAD

**Issue by marcinma** [kubernetes/kubernetes#112835]
### What happened?

Created limit range object with this parameters
```yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: default
spec:
  limits:
  - default:
      cpu: 10m
      memory: 512Mi
    defaultRequest:
      cpu: 10m
      memory: 256Mi
    max:
      cpu: "1"
    min:
      cpu: 1m
```
then tried to create this pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-to-be-removed-4
  labels:
    app: remove
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 700m
```

got message:
Error from server (Invalid): error when creating "pod-to-be-removed.yml": Pod "nginx-to-be-removed-4" is invalid: spec.containers[0].resources.requests: Invalid value: "700m": must be less than or equal to cpu limit

### What did you expect to happen?

Pod should be created with Requests & Limits of cpu equal to 700m (since it is in range of min/max cpu limitrange object)

### How can we reproduce it (as minimally and precisely as possible)?

create limitrange object and pod as in description

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on premise/AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by marcinma** [comment]
> You have a default CPU limit of 10m, and no explicit CPU limit on the container, but a request larger than the limit.
> 
> The request must always be less than or equal to the limit. Your pod needs to also set a higher limit, or the limit range needs to not set a default limit.

but this is not obvious behavior since there is min & max set in limit range. This is `defaults` limits (not min/max) that should be overwritten by pod. limits should be set to requests in this case imho

**Comment by BenTheElder** [comment]
> but this is not obvious behavior since there is min & max set in limit range

limit range limits what the user can set, it doesn't perform any mutations other than the defaulting and doesn't claim to.

Min/max enforce that pods cannot set higher / lower.
The default ensures that if the pod doesn't set a limit it will have one.

personally I would remove the default limit, especially at 10m, this will aggressively limit pods.

> This is defaults limits (not min/max) that should be overwritten by pod

it would be, if the pod set a limit

> limits should be set to requests in this case imho

that would be a substantial breaking change, I don't think we could do that short of a v2 API and I'm not sure it would be correct behavior even then.

we could make it opt-in, but then, why not just set them to match on the pod to begin with?
