### ISSUE TITLE
addon: fluentd-gcp: be helpful when failing

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#11282]
When fluentd is in gcp mode and it fails (due to missing scope or api not being turned on) it should log a helpful message when it dies instead of crashlooping. Right now it crashloops and doesn't write any log messages, so it's pretty annoying to figure out. Changing it to elasticsearch mode (in cluster/gce/config-default.sh) is the easiest workaround.

**Comment by a-robinson** [comment]
This is obsolete, it's been logging warning messages and above for some time now (it had initially been set up to only log error messages, which is a useless mode given that it doesn't seem to consider anything an error).
