### ISSUE TITLE
externalTrafficPolicy: Local blocking cluster-internal traffic

### ISSUE THREAD

**Issue by jeroenrnl** [kubernetes/kubernetes#112820]
### What happened?

I have a cluster setup with 3 nodes. I'm using metallb for loadbalancing and callico for BGP to an upstream router.

```mermaid
flowchart TD
  router((router))
  router<-.-> |bgp|kube11[kube11]
  router<-.-> |bgp|kube12[kube12]
  router<-.-> |bgp|kube13[kube13]
```
Most of my services are running only on a single node, so it makes sense to direct incoming traffic to the right node right away. Also, this ensures that the real source addresses are visible on the end nodes, which is required to do address filtering and proper logging on the end services.

I use
```yaml
apiVersion: v1
kind: Service
[...]
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.10.80
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
```
to create my services.
For `internalTrafficPolicy` I've tried both `Local` and `Cluster`.

This setup makes Calico do a BGP advertisement for the /32 address associated with each Service, and for external traffic, this works like a charm.

The problem arises, when a node _inside_ of the cluster tries to communicate to a service in the cluster, but running on a different node. This traffic gets blocked by
````iptables
-A KUBE-SERVICES -d 192.168.10.80/32 -p tcp -m comment --comment "traefik/traefik:websecure loadbalancer IP" -m tcp --dport 443 -j KUBE-EXT-LODJXQNF3DWSNB7B
````
I've been able to work around this, by creating CNAME entries for each of my services to coreDNS, so they will get the  internal service IP, instead of the external service IP:
````
rewrite continue name web.example.com traefik.traefik.svc.cluster.local
````
but this isn't scalable and also hard to do in an automated way.

Also, this workaround doesn't work in all cases. I have a Wireguard service running in Kubernetes and any host connected to this service is not able to use any services running on a different Pod then the one Wireguard is running on.

### What did you expect to happen?

In-cluster traffic to be unaffected by externalTrafficPolicy

### How can we reproduce it (as minimally and precisely as possible)?

Create a service with `externalTrafficPolicy: Local` and `internalTrafficPolicy: Cluster" and observe traffic going to the external IP to be blocked on the node where the originating Pod is located.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.25.0+k3s1
```

</details>

### Cloud provider

<details>
Bare-metal, proxmox
</details>

### OS version

<details>

```console
kube11:~# cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.4
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
kube11:~# uname -a
Linux kube11.example.com 5.17.9-0-edge #1-Alpine SMP PREEMPT Fri, 20 May 2022 12:48:44 +0000 x86_64 Linux
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Metallb v0.13.5
Callico v3.23.1
</details>

**Comment by uablrek** [comment]
This seems to be a `traefik` issue.

I have tried access from a POD to a service with `externalTrafficPolicy: Local` but without explicit internalTrafficPolicy, which should give "Cluster" as default. It works both from a POD on a node that has an endpoint and from a POD on a node that doesn't have an endpoint. For proxy-mode=ipvs [this PR](https://github.com/kubernetes/kubernetes/pull/97081) must be included, which it is in v1.25.

**Comment by jeroenrnl** [comment]
No, it's definitely not a Traefik issue. I have the same problem on all my services.
I see the counters on the "has no local endpoints" IPtables rule increase if I connect to the service from a pod running on a different node than where the endpoint is:

For example, Gitea, presents a port 22 service for git, gitea is running on kube12:
```
$ kubectl get pods -n gitea -o wide
NAME                    READY   STATUS    RESTARTS   AGE   IP             NODE                NOMINATED NODE   READINESS GATES
gitea-8cb598848-7jjvw   1/1     Running   0          28d   10.34.131.61   kube12.example.com   <none>           <none>

$ kubectl get service -n gitea -o wide
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)        AGE   SELECTOR
gitea   ClusterIP      10.33.244.35    <none>          3000/TCP       88d   app=gitea
gitlb   LoadBalancer   10.33.165.237   192.168.10.22   22:32284/TCP   88d   app=gitea
```
```
kube11:~# iptables -L -v -n | grep 192.168.10.22
    0     0 DROP       tcp  --  *      *       0.0.0.0/0            192.168.10.22        /* gitea/gitlb:ssh has no local endpoints */ tcp dpt:22
```
```
testpod-kube11:~# ssh 192.168.10.22
ssh: connect to host 192.168.10.22 port 22: Operation timed out
```
```
kube11:~# iptables -L -v -n | grep 192.168.10.22
    7   420 DROP       tcp  --  *      *       0.0.0.0/0            192.168.10.22        /* gitea/gitlb:ssh has no local endpoints */ tcp dpt:22
```
```
testpod-kube12:~# ssh 192.168.10.22
/ # ssh 192.168.10.22
The authenticity of host '192.168.10.22 (192.168.10.22)' can't be established.
[...]
````

**Comment by uablrek** [comment]
I have used `EXTERNAL-IP` with the meaning of what you see with `kubectl get svc`. In you case (and mine) that is a "LoadBalancer IP".

**Comment by jeroenrnl** [comment]
OK. I found something:
```
kube11:~# iptables -t nat -L KUBE-EXT-YQF7ZCUFJW4JSWSP -n -v
Chain KUBE-EXT-YQF7ZCUFJW4JSWSP (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 KUBE-SVC-YQF7ZCUFJW4JSWSP  all  --  *      *       10.32.0.0/16         0.0.0.0/0            /* pod traffic for gitea/gitlb:ssh external destinations */
    0     0 KUBE-MARK-MASQ  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* masquerade LOCAL traffic for gitea/gitlb:ssh external destinations */ ADDRTYPE match src-type LOCAL
    0     0 KUBE-SVC-YQF7ZCUFJW4JSWSP  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* route LOCAL traffic for gitea/gitlb:ssh external destinations */ ADDRTYPE match src-type LOCAL
```
The source on that first rule is **10.32.0.0/16** (This is my `cluster-cidr`), however, my pod has an IP out of **10.34.0.0/16**! It never hits this rule. **10.34.0.0/16** is my `calico-cidr`:

```$ kubectl describe IPPool default-ipv4-ippool
Name:         default-ipv4-ippool
[...]
API Version:  projectcalico.org/v3
Kind:         IPPool
[...]
Spec:
  Allowed Uses:
    Workload
    Tunnel
  Block Size:     24
  Cidr:           10.34.0.0/16
  Ipip Mode:      Never
  Nat Outgoing:   true
  Node Selector:  all()
  Vxlan Mode:     Always
Events:           <none>
```

I'm not sure why I chose the Calico CIDR to be different from the POD CIDR, because now reading back the documentation on the Calico installation, it doesn't seem best practice, in fact I found

> When we stood up the Kubernetes cluster, we set the pod CIDR, which is the range of IP addresses Kubernetes thinks the pods should be in. Many Kubernetes components use this setting to determine if an IP belongs to a pod, so you normally want all IP pools you configure to be subsets of the pod CIDR.

I might have misread/misunderstood
> Note: If 192.168.0.0/16 is already in use within your network you must select a different pod network CIDR by replacing 192.168.0.0/16 in the above command.

I'll go see if it's possible to change PodCIDR and/or CalicoCIDR and otherwise rebuild my cluster :-/

**Comment by jeroenrnl** [comment]
That was much easier than expected: https://projectcalico.docs.tigera.io/networking/migrate-pools

Thanks for your help!
