### ISSUE TITLE
Renaming pod causes duplicate pods if SSA and CSA has been mixed historically

### ISSUE THREAD

**Issue by Gikkman** [kubernetes/kubernetes#112826]
### What happened?

Through a series of unfortunate events and miscommunication, we've realized we've been using both client-side apply (CSA) and server-side apply (SSA) for a while towards our clusters. Different engineers have used different methods for about a year. It's been fine until about a week ago when we tried to align container names to a certain standard, in a few deployments. We took the deployed manifest, changed the container name, and applied them using `kubectl apply`. Once we did, the deployment spawned two containers: one with the old name and one with the new name (otherwise they were identical). 

Once in this state, we can't seem to get rid of the "extra container" even if we re-deploy different spins on the manifests. The only we found was to delete the entire deployment and re-apply the manifests. This unfortunately leads to downtime since some of the deployments takes a few minutes to be available.

### What did you expect to happen?

We expected the deployment to reflect whatever manifest we applied to the cluster. 

With that said, this episode has lead me to find out about the `managedFields` concept, which I think is in action here somehow. But we've never said to use different field managers, so I am unsure how that feature is supposed to work.

### How can we reproduce it (as minimally and precisely as possible)?

Fist, apply the base using server-side apply:
```console
cat <<EOF | kubectl apply --server-side -f - 
apiVersion: apps/v1                
kind: Deployment
metadata:
  labels:      
    app: my-app  
  name: hello-app
spec:      
  selector:     
    matchLabels: 
      app: my-app
  template:  
    metadata:
      labels:      
        app: my-app
    spec:        
      containers:                  
      - image: strm/helloworld-http
        name: app
        ports:             
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet: 
            path: / 
            port: 80            
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```
This deployment will start up just fine after a few seconds. Then, we try to rename the container, from `app` to `app-new`, but we do it via client-side apply:
```console
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-app
  name: hello-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: strm/helloworld-http
        name: app-new
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```
This deployment will have two containers: `app` (the old name) and `app-new` (the new name). One of these containers will never report ready.

This can also be done in reverse order (i.e. CSA first and then SSA) and still get the same result.

### Anything else we need to know?

I've gotten the same behavior on a local minikube cluster, on our staging environment and in our production environment. (See Cloud provider for their respective details)

### Kubernetes version

<details>
This is from my minikube test
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/arm64"}
```

This is from our production env
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8+ed4d8fd", GitCommit:"f7310cc5b1c14454dcd067838ca8407e9da13a26", GitTreeState:"clean", BuildDate:"2022-04-19T21:14:01Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.21) exceeds the supported minor version skew of +/-1
```
</details>

### Cloud provider

<details>
Minikube runs a default installation version v1.27.0 (Kubernetes v1.25.0. MacOS 12.4, ARM)

Staging runs Openshift 4.8.39 (Kubernetes v1.21.8+ed4d8fd)

Production runs Openshift 4.8.36 (Kubernetes v1.21.1+6438632)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by Gikkman** [comment]
/sig api-machinery
/sig cli

I think at least, sorry if I get it wrong. I've not made a ticket here before, and I find it a tad difficult to know if this is CLI or API related, even after reading the SIG documents.

**Comment by ardaguclu** [comment]
@Gikkman thanks for raising this issue and your labels are correct :).

Renaming is calculated in different ways for both SSA and CSA. If you use one of them, they understand the "renaming" and do that during `apply` command. However, from SSA to CSA(or reverse as you said);

There might not be a way to understand that "renaming", therefore pod ended up like this;

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-10-03T12:33:07Z"
  generateName: hello-app-59f44bb966-
  labels:
    app: my-app
    pod-template-hash: 59f44bb966
  name: hello-app-59f44bb966-d7n77
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: hello-app-59f44bb966
    uid: 32cbec0d-96f6-4de6-b4c2-6440ed6571c5
  resourceVersion: "6774"
  uid: 89c10cd1-43f1-402a-b62a-9b3e1ef9795e
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: app
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mfnkv
      readOnly: true
  - image: nginx
    imagePullPolicy: Always
    name: app-new
    ports:
    - containerPort: 80
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 80
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mfnkv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-mfnkv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-10-03T12:33:07Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-10-03T12:33:07Z"
    message: 'containers with unready status: [app-new]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-10-03T12:33:07Z"
    message: 'containers with unready status: [app-new]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-10-03T12:33:07Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://8a8d74e19bdb1088804ced10b8d3255aeef2b81c84790c0808b7ce5bcba43c95
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0b970013351304af46f322da1263516b188318682b2ab1091862497591189ff1
    lastState: {}
    name: app
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-10-03T12:33:10Z"
  - containerID: docker://b5410955eb094c27c7942a87c07cd713e77fd1281e808900266b4c4de4b79416
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:0b970013351304af46f322da1263516b188318682b2ab1091862497591189ff1
    lastState:
      terminated:
        containerID: docker://b5410955eb094c27c7942a87c07cd713e77fd1281e808900266b4c4de4b79416
        exitCode: 1
        finishedAt: "2022-10-03T12:34:58Z"
        reason: Error
        startedAt: "2022-10-03T12:34:55Z"
    name: app-new
    ready: false
    restartCount: 4
    started: false
    state:
      waiting:
        message: back-off 1m20s restarting failed container=app-new pod=hello-app-59f44bb966-d7n77_default(89c10cd1-43f1-402a-b62a-9b3e1ef9795e)
        reason: CrashLoopBackOff
  hostIP: 192.168.49.2
  phase: Running
  podIP: 172.17.0.4
  podIPs:
  - ip: 172.17.0.4
  qosClass: BestEffort
  startTime: "2022-10-03T12:33:07Z"
```

as you can see, although expectation is there should be one container, there are two containers(not renamed instead new container is added) and this pod is failing by getting `Address already in use` error.

I'm not sure there is elegant fix for that particular case. @apelisse what is your opinion?

**Comment by apelisse** [comment]
cc @alexzielenski

**Comment by apelisse** [comment]
This is exactly the topic of this KEP: https://github.com/kubernetes/enhancements/pull/3518
We're not treating this as a KEP, but as a bug, which will make it available probably sooner.

Thanks for the report!

**Comment by apelisse** [comment]
Alex, can you think of the best way to workaround that in the mean time?

It's unclear if you've decided whether you're going to always use csa or ssa in the future? Because if you keep doing that, there's no good work around. Do you have the option of re-creating the deployment?

**Comment by alexzielenski** [comment]
To switch the fields to SSA in the meantime, I have (minimally) tested the following sequence of commands to successfully migrate to server-side apply:

Assuming your object is a `statefulset` named `foo`

```shell
# Save the last-applied-configuration to a local yaml file foo.yaml
kubectl apply view-last-applied statefulset foo -o yaml > foo.yaml
```

```shell
# A client-side-apply for good measure to ensure annotations and managed fields are up to date
kubectl apply -f foo.yaml
```

```shell
# A server-side-apply to ensure all fields from the client-side-apply entry are also now in server-side-apply entry
# Added --force-conflicts since we intend to own all the fields specified
kubectl apply -f foo.yaml --server-side --force-conflicts
```

```shell
# Show the object with managed fields. Note which index contains the entry for 'kubectl-client-side-apply'
kubectl get statefulset foo -o yaml --show-managed-fields
```

```shell
# Delete the managed fields entry for client-side-apply. 
# Replace INDEX_FOR_CLIENT_SIDE_APPLY_ENTRY with the index from above
kubectl patch statefulset foo --type='json' -p='[{"op": "remove", "path": "/metadata/managedFields/INDEX_FOR_CLIENT_SIDE_APPLY_ENTRY"}]'
```

```shell
# Do a final server side-apply to clean up any orphaned fields
kubectl apply -f foo.yaml --server-side
```

**Comment by Gikkman** [comment]
I can confirm the approach @alexzielenski suggest work (at least for our case). I bundled it up a bit as a script (requires `jq`) in case it happens to us again. So far, it seems to solve our problems. 

Assuming we got resource type `statefulset` and name `foo`:
```bash
NAME=$(kubectl get statefulset foo -o name)
MANIFEST=$(kubectl apply view-last-applied "$NAME" -o yaml)
echo -n "$MANIFEST" | kubectl apply -f -
echo -n "$MANIFEST" | kubectl apply --server-side --force-conflicts -f -
IDX=$(kubectl get "$NAME" --show-managed-fields -o json | jq '.metadata.managedFields | map(.manager == "kubectl-client-side-apply") | index(true)')
kubectl patch "$NAME" --type='json' -p="[{\"op\": \"remove\", \"path\": \"/metadata/managedFields/$IDX\"}]"
echo -n "$MANIFEST" | kubectl apply --server-side -f -
```
Thank you for the assistance with how to handle our specific case too. I wouldn't have figured this out myself.

It seems you guys have a good grasp of the problem and an idea for how to handle it in the future. Personally, I find this `managedField` concept is a bit tricky to understand and manage. So the only other feedback from my side is to consider  providing a convenient tool for viewing/managing field managers, or maybe something as simple as communicating field management changes via the CLI.

**Comment by apelisse** [comment]
Great suggestion actually, thanks! Note that your script is not atomic, you should add the resourceVersion in the patch to make sure no one changes the object and messes up the index of the managed fields between the get and the patch.

**Comment by Gikkman** [comment]
Ah, yes, good catch. Thank you for pointing it out.

**Comment by Gikkman** [comment]
We've found another case that seems to be related to this same behavior. I see there's a MR already in place, so maybe you just need to double check that it covers this too.

Using `kubectl rollback undo` creates a new field manager with another operation set (`operation: Update`) that I can't seem to control. The easiest way to replicate it I've found is this:

Create initial deployment
```
cat <<EOF | kubectl apply --server-side -f - 
apiVersion: apps/v1                
kind: Deployment
metadata:
  labels:      
    app: my-app  
  name: hello-app
spec:      
  selector:     
    matchLabels: 
      app: my-app
  template:  
    metadata:
      labels:      
        app: my-app
    spec:        
      containers:                  
      - image: nginx
        name: app
        ports:             
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet: 
            path: / 
            port: 80            
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```

Rename contianer:
```
cat <<EOF | kubectl apply --server-side -f - 
apiVersion: apps/v1                
kind: Deployment
metadata:
  labels:      
    app: my-app  
  name: hello-app
spec:      
  selector:     
    matchLabels: 
      app: my-app
  template:  
    metadata:
      labels:      
        app: my-app
    spec:        
      containers:                  
      - image: nginx
        name: app-new
        ports:             
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet: 
            path: / 
            port: 80            
          initialDelaySeconds: 5
          periodSeconds: 5
EOF
```

Now, roll back the name change:
```
kubectl rollout undo deployment/hello-app
```

Now we "fix" the name change and apply it again (in this case I just modify the readiness probe but you get the point):
```
cat <<EOF | kubectl apply --server-side -f - 
apiVersion: apps/v1                
kind: Deployment
metadata:
  labels:      
    app: my-app  
  name: hello-app
spec:      
  selector:     
    matchLabels: 
      app: my-app
  template:  
    metadata:
      labels:      
        app: my-app
    spec:        
      containers:                  
      - image: nginx
        name: app-new
        ports:             
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet: 
            path: / 
            port: 80            
          initialDelaySeconds: 3
          periodSeconds: 5
EOF
```

Now we get the orphaned container problem again, even without mixing server-side and client-side.

**Comment by ardaguclu** [comment]
That is a good catch, but it is a different problem than SSA&CSA conflict. `rollout undo` adds a new fieldmanager with `operation: Update` as you said, it takes ownership and results in exact problem in here(2 same containers and one of them is failing).

Maybe we should do _something_ in here https://github.com/kubernetes/kubernetes/blob/a9593d634c6a053848413e600dadbf974627515f/staging/src/k8s.io/kubectl/pkg/polymorphichelpers/rollback.go#L195 in terms of managedfields?

**Comment by Gikkman** [comment]
Alright, thanks for taking a look. I opened an issue related to `rollout undo` over at #112911 so I guess that one is better for tracking that behavior then.
