### ISSUE TITLE
Exceeding the ephemeral storage limit not causing eviction in critical pods 

### ISSUE THREAD

**Issue by brucelee138** [kubernetes/kubernetes#112893]
### What happened?

As per my understanding, when containers exceed their memory or cpu limits, they are restarted. But when they exceed ephemeral storage limit, the pod itself has to be destroyed and recreated (by eviction). Also, critical pods would not be evicted.
We have some pods marked as critical which at times consume ephemeral storage exceeding their limit (potentially filling up the disk). We have marked them as "critical" as we dont want them to become victim in case of any node pressure. At the same time, we would not want the pod to be evicted when they cross the configured limit. Is there any way we could achieve this?

### What did you expect to happen?

Pods (even critical ones) have to be evicted when they consume more storage than the configured ephemeral storage limit.

### How can we reproduce it (as minimally and precisely as possible)?

We can reproduce the issue by the following,

1. Define ephemeral limit for any container in a pod.
2. Mark the pod as critical by using setting priority class (priorityClassName: system-cluster-critical)
3. Consume disk space from the container using dd if=/dev/urandom of=test 
or alternately configure very small ephemeral limit.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.24.2
</details>

### Cloud provider

<details>
Openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.6
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

https://github.com/kubernetes/kubernetes/issues/112893#tasklist-block-51c08819-e975-4a40-9758-ffcfe209ac8a

**Comment by 249043822** [comment]
this is not a bug, it should be a feature

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

@brucelee138 is there specific reason you want the pod to be marked critical. In general critical pods needs to be avoided

**Comment by brucelee138** [comment]
@SergeyKanzhelev thanks for the response. We have marked monitoring pods as critical (Victoria metrics to be exact) as we dont want to get them evicted over application pods ( to continue monitoring them). But in some corner cases the ephemeral storage of a pod started growing up and filling up the disk. So, we set a ephemeral limit to evict these pods **only when** the ephemeral storage usage is abnormal and we realized that critical pods cant be evicted even when the limits are crossed.

**Comment by brucelee138** [comment]
@249043822 agree that this should be a feature/enhancement.

**Comment by lengrongfu** [comment]
> Some of these add-ons are critical to a fully functional cluster, such as metrics-server, DNS, and UI. A cluster may stop working properly if a critical add-on is evicted (either manually or as a side effect of another operation like upgrade) and becomes pending (for example when the cluster is highly utilized and either there are other pending pods that schedule into the space vacated by the evicted critical add-on pod or the amount of resources available on the node changed for some other reason).

https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/

This usage is described in the documentation.

**Comment by brucelee138** [comment]
@lengrongfu thanks for your interest in this! Do reach out to me if you got any queries.

**Comment by lengrongfu** [comment]
Logical analysis, when the `priorityClassName` is set for the pod, it will eventually be converted to Priority,
```shell
$ kubectl get priorityclasses
NAME                      VALUE        GLOBAL-DEFAULT   AGE
system-cluster-critical   2000000000   false            85d
system-node-critical      2000001000   false            85d
```
When the pod is eviction, it will judge whether `Priority >= 2000000000` is established. If it is established, it is considered to be `SystemCriticalPriority`, and it will not be eviction.

I have three solutions:
1. Modify the condition that is judged as `SystemCriticalPriority` to `Priority >= 2000000001`
2. Add a parameters in `kubelet`, you can customize `Priority >={value}`value
3. Add a parameter to `kubelet` to enable eviction of all pods with `Priority<2000001000`.

I recommend the third option(IMO), request for comments.

**Comment by brucelee138** [comment]
@lengrongfu I might have some gaps in understanding the 3 solutions you have suggested, you could clarify if so.
As per my understanding, pod eviction could happen when a node is running low on resources and a pod running on the node is evicted to reclaim the resources. We mark certain pods as "critical" as we dont want these pods to get evicted during this reclamation as they do some "critical work". But there could be cases where these pods have to be evicted due to their own faults (exceeding the set limits) and we have evict to them. Some feedback on your proposed solutions with this background.
 
1. Modify the condition that is judged as SystemCriticalPriority to Priority >= 2000000001
-> But this would defeat the purpose of having SystemCriticalPriority right? we want these pods to get evicted only in scenario mentioned above.
2. Add a parameters in kubelet, you can customize Priority >={value}value
-> Same argument as above
3. Add a parameter to kubelet to enable eviction of all pods with Priority<2000001000.
-> I was thinking on these lines too...when a pod exceeds the set ephemeral storage limit, along with marking the pod for eviction add another param (like exceeded_limits flag) and to check this flag too during eviction.

func (m *managerImpl) evictPod(pod *v1.Pod, gracePeriodOverride int64, evictMsg string, annotations map[string]string) bool {
	// If the pod is marked as critical and static, and support for critical pod annotations is enabled,
	// do not evict such pods. Static pods are not re-admitted after evictions.
	// https://github.com/kubernetes/kubernetes/issues/40573 has more details.
	if kubelettypes.IsCriticalPod(pod) && **!exceeded_limits** {
	//dont evict
	}
}
Also, maybe instead of restricting to "exceed_limits" we could have a generic flag "own_fault" to handle any other scenarios where a pod is evicted even when marked critical due to its own fault. Makes sense?

**Comment by lengrongfu** [comment]
Exceeding the limit is a condition for triggering eviction. After the eviction starts, it will be judged whether it is a critical pod.
https://github.com/kubernetes/kubernetes/blob/594d34872c73f6abe5eba740f9e4557c6f970887/pkg/kubelet/eviction/eviction_manager.go#L505

https://github.com/kubernetes/kubernetes/blob/594d34872c73f6abe5eba740f9e4557c6f970887/pkg/kubelet/eviction/eviction_manager.go#L520

**Comment by lengrongfu** [comment]
@brucelee138 First add a pod warning prompt, this solution may require sig-owned consent to implement.

**Comment by brucelee138** [comment]
@lengrongfu Thanks for the help! "First add a pod warning prompt" you meant I should add some label here ? sorry, didnt understand.
