### ISSUE TITLE
Issuing certificate as Secret does not exist

### ISSUE THREAD

**Issue by imneeteeshyadav98** [kubernetes/kubernetes#112800]
root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl get certificaterequest
NAME                      READY   AGE
devcms-app-secret-lcx5n   False   22m
letsencrypt-prod-2mhqn    False   319d
root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl describe devcms-app-secret-lcx5n   
error: the server doesn't have a resource type "devcms-app-secret-lcx5n"
root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl describe certificaterequest  devcms-app-secret-lcx5n   
Name:         devcms-app-secret-lcx5n
Namespace:    default
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: devcms-app-secret
              cert-manager.io/certificate-revision: 1
              cert-manager.io/private-key-secret-name: devcms-app-secret-wtccm
API Version:  cert-manager.io/v1
Kind:         CertificateRequest
Metadata:
  Creation Timestamp:  2022-09-30T09:53:30Z
  Generate Name:       devcms-app-secret-
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cert-manager.io/certificate-name:
          f:cert-manager.io/certificate-revision:
          f:cert-manager.io/private-key-secret-name:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:generateName:
        f:ownerReferences:
          .:
          k:{"uid":"e67e8f3d-4195-42f1-8e52-ee385a107bc5"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:request:
      f:status:
        .:
        f:conditions:
    Manager:    controller
    Operation:  Update
    Time:       2022-09-30T09:53:30Z
  Owner References:
    API Version:           cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Certificate
    Name:                  devcms-app-secret
    UID:                   e67e8f3d-4195-42f1-8e52-ee385a107bc5
  Resource Version:        90723383
  UID:                     81653e0b-9534-4dd4-a77b-18844ee1e368
Spec:
  Issuer Ref:
    Kind:   ClusterIssuer
    Name:   devcms-cluster-issuer
  Request:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2dUQ0NBV2tDQVFBd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUx2YgovTGJEeWgrTm81NzhsWXNObVk1NHFmYkgyc2ZnVnVjRWFUN2tpSHF1MGtFWDc2NlVuUUJSZjMyWGZtU3JHdzNXCmcyRGlPVS9MNUNxRGUwT2N6RDA2THNNbFp6Um81a1VHTUNjWnQvVEFkTVRDc2dUWDdEUzk5T0RmUG15eEVIYjcKS1J0NERjOFBKbTJtSWN6S0FWd01OaVgwZ1RMU0VDWTlPWURTUGxXQ1FtVXV2VTErNHBkaEI1TWQvNURucnE2QgoycTJpNjk0bndpWk1jMnV3TS8zQWl1RlRGWWNRU01oMGpNR2N2SHdxbm00WjliLzNWcVI1b0xsR3RBc0dyTjhwCldnYUxVRlI0TlpkWUlPMFJRallVYVNRVTdXTzVkUnQvbmpTQmVYYzRET2VWYmhKT2ViRVJiakVVU3V3S2FvcFgKWEVWL3kvRHRUdmE3QmJhcEhFTUNBd0VBQWFBOE1Eb0dDU3FHU0liM0RRRUpEakV0TUNzd0hBWURWUjBSQkJVdwpFNElSWkdWMlkyMXpMbUp2ZEhOb2IzUXVhVzR3Q3dZRFZSMFBCQVFEQWdXZ01BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUUFadHk0VHFIYzAzSGNnNEhZYllmQXBYcFd6NmVMbEhHUDFzYVd6Vmx1RnUzSjdrK1pib0ozQ2ZaZjYKRERKMkU0MFp4bkNvTnZhV1pCYWlZdmRObjhwYVVPa3FjSXRUTlRvellHOTExY2ozSXorb2UxMzRONDlnS1BnMwpFRTVFeDBUWWJWTXVXdXhBSVdQc1I1aGhBMHRhVEQxNXFmTlFzL0NkQmRnTDA0Q2dUeHlPSUxaMXBkVGtuT1MyCjhBU3JQRFkvZ25MZEpaZFh6aFpZbXJ1MHZFNCsycjNMdzFneG9uT0JqVkFWWFZXOHExZE1Ga25RWEgrcGRPcWUKUWJISFZHb1BQTVkxbXJZSGhMZDZnTmZ0VVlOSDdON3BySzRlU0dia0lqbFVNckdYQTZGVmpadG55TTZTOVI0VwowMDZlVCtmU0hBRkRtWlBNbW1BMGZ0djQ2eWJvCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
Status:
  Conditions:
    Last Transition Time:  2022-09-30T09:53:30Z
    Message:               Waiting on certificate issuance from order default/devcms-app-secret-lcx5n-1853717039: "pending"
    Reason:                Pending
    Status:                False
    Type:                  Ready
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  OrderCreated  23m   cert-manager  Created Order resource default/devcms-app-secret-lcx5n-1853717039

root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl get orders 
NAME                                 STATE     AGE
devcms-app-secret-lcx5n-1853717039   pending   23m
letsencrypt-prod-2mhqn-1989508847    pending   287d
root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl describe orders devcms-app-secret-lcx5n-1853717039 
Name:         devcms-app-secret-lcx5n-1853717039
Namespace:    default
Labels:       <none>
Annotations:  cert-manager.io/certificate-name: devcms-app-secret
              cert-manager.io/certificate-revision: 1
              cert-manager.io/private-key-secret-name: devcms-app-secret-wtccm
API Version:  acme.cert-manager.io/v1
Kind:         Order
Metadata:
  Creation Timestamp:  2022-09-30T09:53:30Z
  Generation:          1
  Managed Fields:
    API Version:  acme.cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:cert-manager.io/certificate-name:
          f:cert-manager.io/certificate-revision:
          f:cert-manager.io/private-key-secret-name:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:ownerReferences:
          .:
          k:{"uid":"81653e0b-9534-4dd4-a77b-18844ee1e368"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:dnsNames:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:request:
      f:status:
        .:
        f:authorizations:
        f:finalizeURL:
        f:state:
        f:url:
    Manager:    controller
    Operation:  Update
    Time:       2022-09-30T09:53:33Z
  Owner References:
    API Version:           cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  CertificateRequest
    Name:                  devcms-app-secret-lcx5n
    UID:                   81653e0b-9534-4dd4-a77b-18844ee1e368
  Resource Version:        90723384
  UID:                     a9be250e-ddf5-4470-8d99-a29ff7791fcc
Spec:
  Dns Names:
    devcms.botshot.in
  Issuer Ref:
    Kind:   ClusterIssuer
    Name:   devcms-cluster-issuer
  Request:  LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2dUQ0NBV2tDQVFBd0FEQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQUx2YgovTGJEeWgrTm81NzhsWXNObVk1NHFmYkgyc2ZnVnVjRWFUN2tpSHF1MGtFWDc2NlVuUUJSZjMyWGZtU3JHdzNXCmcyRGlPVS9MNUNxRGUwT2N6RDA2THNNbFp6Um81a1VHTUNjWnQvVEFkTVRDc2dUWDdEUzk5T0RmUG15eEVIYjcKS1J0NERjOFBKbTJtSWN6S0FWd01OaVgwZ1RMU0VDWTlPWURTUGxXQ1FtVXV2VTErNHBkaEI1TWQvNURucnE2QgoycTJpNjk0bndpWk1jMnV3TS8zQWl1RlRGWWNRU01oMGpNR2N2SHdxbm00WjliLzNWcVI1b0xsR3RBc0dyTjhwCldnYUxVRlI0TlpkWUlPMFJRallVYVNRVTdXTzVkUnQvbmpTQmVYYzRET2VWYmhKT2ViRVJiakVVU3V3S2FvcFgKWEVWL3kvRHRUdmE3QmJhcEhFTUNBd0VBQWFBOE1Eb0dDU3FHU0liM0RRRUpEakV0TUNzd0hBWURWUjBSQkJVdwpFNElSWkdWMlkyMXpMbUp2ZEhOb2IzUXVhVzR3Q3dZRFZSMFBCQVFEQWdXZ01BMEdDU3FHU0liM0RRRUJDd1VBCkE0SUJBUUFadHk0VHFIYzAzSGNnNEhZYllmQXBYcFd6NmVMbEhHUDFzYVd6Vmx1RnUzSjdrK1pib0ozQ2ZaZjYKRERKMkU0MFp4bkNvTnZhV1pCYWlZdmRObjhwYVVPa3FjSXRUTlRvellHOTExY2ozSXorb2UxMzRONDlnS1BnMwpFRTVFeDBUWWJWTXVXdXhBSVdQc1I1aGhBMHRhVEQxNXFmTlFzL0NkQmRnTDA0Q2dUeHlPSUxaMXBkVGtuT1MyCjhBU3JQRFkvZ25MZEpaZFh6aFpZbXJ1MHZFNCsycjNMdzFneG9uT0JqVkFWWFZXOHExZE1Ga25RWEgrcGRPcWUKUWJISFZHb1BQTVkxbXJZSGhMZDZnTmZ0VVlOSDdON3BySzRlU0dia0lqbFVNckdYQTZGVmpadG55TTZTOVI0VwowMDZlVCtmU0hBRkRtWlBNbW1BMGZ0djQ2eWJvCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
Status:
  Authorizations:
    Challenges:
      Token:        -m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0
      Type:         http-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/159162260796/fn7fQQ
      Token:        -m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0
      Type:         dns-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/159162260796/jh4ZHA
      Token:        -m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0
      Type:         tls-alpn-01
      URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/159162260796/SKesyQ
    Identifier:     devcms.botshot.in
    Initial State:  pending
    URL:            https://acme-v02.api.letsencrypt.org/acme/authz-v3/159162260796
    Wildcard:       false
  Finalize URL:     https://acme-v02.api.letsencrypt.org/acme/finalize/754671766/130207836076
  State:            pending
  URL:              https://acme-v02.api.letsencrypt.org/acme/order/754671766/130207836076
Events:
  Type    Reason   Age   From          Message
  ----    ------   ----  ----          -------
  Normal  Created  23m   cert-manager  Created Challenge resource "devcms-app-secret-lcx5n-1853717039-2013380524" for domain "devcms.botshot.in"

root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl get challenges 
NAME                                            STATE     DOMAIN                        AGE
devcms-app-secret-lcx5n-1853717039-2013380524   pending   devcms.botshot.in             24m
letsencrypt-prod-2mhqn-1989508847-917657944     pending   feature.radisson.botshot.in   287d
root@dev-doc-adhoc-dev-task-bgl-001:~# kubectl describe challenges devcms-app-secret-lcx5n-1853717039-2013380524 
Name:         devcms-app-secret-lcx5n-1853717039-2013380524
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  acme.cert-manager.io/v1
Kind:         Challenge
Metadata:
  Creation Timestamp:  2022-09-30T09:53:33Z
  Finalizers:
    finalizer.acme.cert-manager.io
  Generation:  1
  Managed Fields:
    API Version:  acme.cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"finalizer.acme.cert-manager.io":
        f:ownerReferences:
          .:
          k:{"uid":"a9be250e-ddf5-4470-8d99-a29ff7791fcc"}:
            .:
            f:apiVersion:
            f:blockOwnerDeletion:
            f:controller:
            f:kind:
            f:name:
            f:uid:
      f:spec:
        .:
        f:authorizationURL:
        f:dnsName:
        f:issuerRef:
          .:
          f:kind:
          f:name:
        f:key:
        f:solver:
          .:
          f:http01:
            .:
            f:ingress:
              .:
              f:class:
        f:token:
        f:type:
        f:url:
        f:wildcard:
      f:status:
        .:
        f:presented:
        f:processing:
        f:reason:
        f:state:
    Manager:    controller
    Operation:  Update
    Time:       2022-09-30T09:53:34Z
  Owner References:
    API Version:           acme.cert-manager.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Order
    Name:                  devcms-app-secret-lcx5n-1853717039
    UID:                   a9be250e-ddf5-4470-8d99-a29ff7791fcc
  Resource Version:        90723407
  UID:                     91d00694-a921-45cb-afb8-5c1faed4bb3a
Spec:
  Authorization URL:  https://acme-v02.api.letsencrypt.org/acme/authz-v3/159162260796
  Dns Name:           devcms.botshot.in
  Issuer Ref:
    Kind:  ClusterIssuer
    Name:  devcms-cluster-issuer
  Key:     -m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0.jJ_8bzaIbhaR57MxJEuXviLhM8up_MeO3RDd6sSMwAk
  Solver:
    http01:
      Ingress:
        Class:  nginx
  Token:        -m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0
  Type:         HTTP-01
  URL:          https://acme-v02.api.letsencrypt.org/acme/chall-v3/159162260796/fn7fQQ
  Wildcard:     false
Status:
  Presented:   true
  Processing:  true
  Reason:      Waiting for HTTP-01 challenge propagation: failed to perform self check GET request 'http://devcms.botshot.in/.well-known/acme-challenge/-m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0': Get "http://devcms.botshot.in/.well-known/acme-challenge/-m8pin1sjhPVWNB00Lr_ArjHZzF-r9jbR8Sw7RkbRs0": EOF
  State:       pending
Events:
  Type    Reason     Age   From          Message
  ----    ------     ----  ----          -------
  Normal  Started    24m   cert-manager  Challenge scheduled for processing
  Normal  Presented  24m   cert-manager  Presented challenge using HTTP-01 challenge mechanism

**Comment by liggitt** [comment]
it looks like you are trying to get cert-manager to work... I'd suggest using the resources listed at https://github.com/cert-manager/cert-manager#troubleshooting to figure out what is going on or to request assistance

/close

**Comment by biapar** [comment]
Check if you have IPV6 redirection configured in your DNS provider. If the redirection does not redirect to your server, remove it.
