### ISSUE TITLE
Add metrics for cpumanager

### ISSUE THREAD

**Issue by fromanirh** [kubernetes/kubernetes#112854]
### What would you like to be added?

Add [metrics](https://github.com/kubernetes/kubernetes/tree/v1.25.2/pkg/kubelet/metrics) to enable observability of the cpumanager.

### Why is this needed?

This is required to [GA the feature](https://github.com/kubernetes/enhancements/pull/3350) but it's also useful in general.

To the best of my knowledge, it's very hard to observe the behavior of cpumanager without peeking into the pod and/or use the podresources interface (kubelet >= 1.24). But even for the latter, no well known components expose metrics consuming this information.

I believe anyway kubelet some expose some basic metrics about cpumanager behaviour, while deferring more fine grained metrics to external components (NFD, node_exporter, is fine)

**Comment by swatisehgal** [comment]
/triage accepted
/priority important-soon
(as this is important for graduation for CPU Manager to GA)
