### ISSUE TITLE
All reviewers and approvers in root OWNERS are from google

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#112867]
Please see:
https://github.com/kubernetes/kubernetes/blob/master/OWNERS#L5-L18

There are six approvers and reviewers, ALL of them are from google. This is not a good look for a really diverse project like Kubernetes with contributors from all over the world.

/assign @dchen1107 @lavalamp @smarterclayton @thockin @wojtek-t @liggitt

Yes, we keep saying that needs to be solved by fixing things in prow and that it is ok to leave it as is ... BUT this is still not right.

**Comment by dims** [comment]
NOTE that https://github.com/kubernetes/test-infra/pull/21398 is languishing since Mar 16, 2021

**Comment by dims** [comment]
Last issue which the bot auto closed was filed in Aug 2, 2020 - https://github.com/kubernetes/kubernetes/issues/93637

**Comment by dims** [comment]
and another one goes even earlier - https://github.com/kubernetes/kubernetes/pull/85638

**Comment by liggitt** [comment]
I agree the current state isn't really appropriate, even if we sort of drifted into it when @smarterclayton and I switched companies.

> NOTE that https://github.com/kubernetes/test-infra/pull/21398 is languishing since Mar 16, 2021

Sigh. I'd really hoped we'd get that capability (and still really want it) to allow carving up approval of specific files in the root dir. The things in the root that change regularly are:
* go.mod/go.sum (changes frequently, dep-approvers alias should have approval on this)
* OWNERS_ALIASES (changes ~monthly, not sure what alias makes sense here... maybe sig-architecture-approvers?)

I'd be in favor of leaning on subdir OWNERS files and making root approval effectively non-recursive in kubernetes/kubernetes by:
1. making immediate subdir OWNERS files set `no_parent_owners: true`
2. moving current root approvers down a level into relevant immediate subdir OWNERS files alongside existing subdir approvers
3. populating root `approvers` with the groups expected to manage dependency and alias updates (maybe `dep-approvers` and `sig-architecture-approvers`)?

`sig-architecture-approvers` also seems like a decent fallback for other super-rarely changed top-level files like the readme, etc.

Thoughts?

**Comment by lavalamp** [comment]
+1 to @liggitt's proposal; I don't trust the next company which accidentally captures root owners to do the right thing, I think this power shouldn't exist at all.

**Comment by thockin** [comment]
I worry about the lack of people who can approve anything in an emergency,
but it's entirely hypothetical (so far) so +1

**Comment by liggitt** [comment]
I'm OOO tomorrow and Friday, but unless there are objections, I'll open a PR to do https://github.com/kubernetes/kubernetes/issues/112867#issuecomment-1268722455 on Monday if no one beats me to it

**Comment by dims** [comment]
thanks a ton folks! glad to hear the new proposal and +1 Jordan on the plan for monday

**Comment by thockin** [comment]
Can we not pull the same symlink trick we do with Maklefiles?  Or is Go
too "smart" for that?

**Comment by liggitt** [comment]
> Can we not pull the same symlink trick we do with Makefiles?  Or is Go too "smart" for that?

I'm... really not confident that would work well, especially how go modules get zipped up and distributed...
