### ISSUE TITLE
Downward API should expose pod IP

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#11288]
The pod IP is an incredibly useful value for containers to have access to via an env var - it removes very ugly hacks from simple code that must provide an IP to others (the "simple" bash solution is ifconfig + awk + grep which really inspires confidence).  We should make it available via the downward API.

**Comment by thockin** [comment]
errm, hostname -i?  ioctl(SIOCGIFADDR)?  ip addr list?

I don't have a problem exposing more stuff, but this is a problem that has
existed time immemorial and is not at all related to kube or containers :)

**Comment by smarterclayton** [comment]
Not every container has 'ip'.  `hostname -i` returns 127.0.0.1 on at least
half my systems.  podIP is *always* correct (the IP other pods should use
to contact this pod).

> I don't have a problem exposing more stuff, but this is a problem that has
existed time immemorial and is not at all related to kube or containers :)

The fact that the problem has existed from time immemorial and that there
is no way to easily figure it out is a crime. :)


On Wed, Jul 15, 2015 at 1:01 AM, Tim Hockin <notifications@github.com>
wrote:

> errm, hostname -i? ioctl(SIOCGIFADDR)? ip addr list?
>
> I don't have a problem exposing more stuff, but this is a problem that has
> existed time immemorial and is not at all related to kube or containers :)
>
> On Tue, Jul 14, 2015 at 9:57 PM, Clayton Coleman <notifications@github.com
> >
> wrote:
>
> > The pod IP is an incredibly useful value for containers to have access to
> > via an env var - it removes very ugly hacks from simple code that must
> > provide an IP to others (the "simple" bash solution is ifconfig + awk +
> > grep which really inspires confidence). We should make it available via
> the
> > downward API.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GoogleCloudPlatform/kubernetes/issues/11288>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11288#issuecomment-121488274>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by lvlv** [comment]
Is it possible to expose more like spec.nodeName as well?

**Comment by thockin** [comment]
NodeName crosses a different philospohical line and would require more
debate :)
