### ISSUE TITLE
Resolution of preemption_victims metric is limiting

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#112912]
### What would you like to be added?

Have better resolution of the metric. The range is probably good (0 to 50), but the resolution is not very useful. Maybe it should be an exponential scale instead of linear https://github.com/kubernetes/kubernetes/blob/e11e226b23c0213021a6678002132ad102d488e7/pkg/scheduler/metrics/metrics.go#L81

### Why is this needed?

We should have more visibility around average number of preemptions. It's not possible to see if pods require less than 5 preemptions to inform how expensive preemption is for a certain QPS.

**Comment by alculquicondor** [comment]
/sig scheduling
/sig instrumentation

@logicalhan is the proposal backwards compatible? The guide is not very clear about changing the buckets, but I seem to remember it's ok to change them
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/metric-stability.md#stable

**Comment by lengrongfu** [comment]
Can I work for this issue？@alculquicondor

**Comment by pacoxu** [comment]
/close

If you set `Fixes #112912` correctly, this issue will be closed automatically by GitHub. There is an extra # in https://github.com/kubernetes/kubernetes/pull/112939#issue-1402183575.
