### ISSUE TITLE
kubeadm init always pull images even if perform this action in beforehand using 'kubeadm config images pull'

### ISSUE THREAD

**Issue by dylan2intel** [kubernetes/kubernetes#112974]
### What happened?

# pulling images firstly
sudo kubeadm config images pull
I1011 16:16:38.903002    4669 version.go:255] remote version is much newer: v1.25.2; falling back to: stable-1.23
[config/images] Pulled k8s.gcr.io/kube-apiserver:v1.23.12
[config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.23.12
[config/images] Pulled k8s.gcr.io/kube-scheduler:v1.23.12
[config/images] Pulled k8s.gcr.io/kube-proxy:v1.23.12
[config/images] Pulled k8s.gcr.io/pause:3.6
[config/images] Pulled k8s.gcr.io/etcd:3.5.1-0
[config/images] Pulled k8s.gcr.io/coredns/coredns:v1.8.6

# init
sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version=1.23.12 --cri-socket unix:///run/containerd/containerd.sock --v=9
...
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I1011 16:18:02.662033    5247 checks.go:842] using image pull policy: IfNotPresent
I1011 16:18:02.704498    5247 checks.go:859] pulling: k8s.gcr.io/kube-apiserver:v1.23.12
I1011 16:20:33.004609    5247 checks.go:859] pulling: k8s.gcr.io/kube-controller-manager:v1.23.12
I1011 16:23:03.323301    5247 checks.go:859] pulling: k8s.gcr.io/kube-scheduler:v1.23.12
I1011 16:25:33.618665    5247 checks.go:859] pulling: k8s.gcr.io/kube-proxy:v1.23.12

Which always pull images again and waste time.

### What did you expect to happen?

Is there any switch can skip this pulling when init? 
or can we avoid this duplicate pulling action in code?

### How can we reproduce it (as minimally and precisely as possible)?

sudo kubeadm config images pull

sudo kubeadm init --pod-network-cidr=10.244.0.0/16 --kubernetes-version=1.23.12 --cri-socket unix:///run/containerd/containerd.sock --v=9

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux ibrahimovic 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux



### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> -cri-socket unix:///run/containerd/containerd.sock

notice you are passing a cri socket during init but not during prepull. so are prepuling using another cri. maybe docker.

/kind support
/close
