### ISSUE TITLE
Keep source IP when clients request to pod on Kubernetes

### ISSUE THREAD

**Issue by arezvani** [kubernetes/kubernetes#112929]
### What would you like to be added?

I want to prevent brute force attacks to my services on Kubernetes. My solution is to ban IPs that have many failed attempts but every request will be SNAT (Source NAT) and I don't know what can I do. Is there Any proxy I can use for my TCP requests and after that I can ban IPs?

### Why is this needed?

prevent brute force attacks to my services on Kubernetes

**Comment by aojea** [comment]
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

**Comment by khenidak** [comment]
@arezvani  can walk us through your setup please?
