### ISSUE TITLE
How to set up using IPv4/IPv6 dual network on k8s v1.18.3 

### ISSUE THREAD

**Issue by wangzhao123456** [kubernetes/kubernetes#112967]
Hello, everyone, I need some help on set up using IPv4/IPv6 dual network with k8s v1.18.3.

I created my k8s cluster using sealos and my operating system is Centos7. 

After creating the k8s cluster(pure ipv4, no ipv6 setup) using sealos, I followed the official k8s document  instructions on websites (https://www.bookstack.cn/read/kubernetes-concepts-1.19-zh/f90ff91a08bebb5f.md) but it doesn't work. The k8s nodes and pods can not be allocated with IPv6 address. 

I also refer to the documents on [https://kubernetes.io/zh-cn/docs/concepts/services-networking/dual-stack/](https://kubernetes.io/zh-cn/docs/concepts/services-networking/dual-stack/) and [https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support/](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support/) . I am a little confused.

I don't know how to set up using IPv4/IPv6 dual network on my already created ipv4 k8s cluster. If I should first create k8s cluster with kubeadm refering  [https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support/](https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support/) and then set up it using [https://kubernetes.io/zh-cn/docs/concepts/services-networking/dual-stack/](https://kubernetes.io/zh-cn/docs/concepts/services-networking/dual-stack/) ? 

I don't know the relationship between https://kubernetes.io/zh-cn/docs/setup/production-environment/tools/kubeadm/dual-stack-support/ and https://kubernetes.io/zh-cn/docs/concepts/services-networking/dual-stack/ .

Thanks in advance.

**Comment by aojea** [comment]
> Hello, everyone, I need some help on set up using IPv4/IPv6 dual network with k8s v1.18.3.

That is an EOL version, only the following versions are supported https://kubernetes.io/releases/

dual-stack was beta in 1.21 and there were breaking changes, I have doubts it was mature enough in 1.18

**Comment by neolit123** [comment]
> That is an EOL version

>  The OP should try with a later version 

++1

please ask for support here if possible:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
/kind support

**Comment by wangzhao123456** [comment]
> iirc it was alpha and only supported pod dual stackness, not services. The OP should try with a later version where the feature was stable.

Thanks !
