### ISSUE TITLE
The update Pod was having trouble allocating memory

### ISSUE THREAD

**Issue by waidinsamkeit** [kubernetes/kubernetes#112940]
### What happened?

The update Pod was having trouble allocating memory
Version: Kubernetes1.7.9
Docker version: 20.10.7

When I tried to update a Pod
`
mkdir /sys/fs/cgroup/memory/kubepods/burstable/podf2552b87-fd99-4c85-9b6c-e997dcdb6a0f: cannot allocate memory
`

### What did you expect to happen?

mkdir /sys/fs/cgroup/memory/kubepods/burstable/podf2552b87-fd99-4c85-9b6c-e997dcdb6a0f: cannot allocate memory

### How can we reproduce it (as minimally and precisely as possible)?

I don't know

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

NO

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
1
</details>
1

### Container runtime (CRI) and version (if applicable)

<details>
1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NO

</details>

**Comment by pacoxu** [comment]
nokmem problem is a known issue in my mind. See https://klts.io/docs/kubernetes/patches/nokmem/.

/kind support 
v1.17 is the end of life in the k8s community.
/close

**Comment by pacoxu** [comment]
As I know, there are 3 ways to fix it.
1. kernel upgrade to 4.0+: https://github.com/kubernetes/kubernetes/issues/61937#issuecomment-377585452
2. rebuild the kubelet with nokmem args. See https://github.com/kubernetes/kubernetes/issues/96701#issuecomment-911061574
3. Set cgroup.memory=nokmem in grub: see https://github.com/kubernetes/kubernetes/issues/61937#issuecomment-567042968

**Comment by waidinsamkeit** [comment]
> As I know, there are 3 ways to fix it.
> 
> 1. kernel upgrade to 4.0+: [application crash due to k8s 1.9.x open the kernel memory accounting by default #61937 (comment)](https://github.com/kubernetes/kubernetes/issues/61937#issuecomment-377585452)
> 2. rebuild the kubelet with nokmem args. See [Failed to create container, mkdir /sys/fs/cgroup/memory/kubepods/besteffort/pod98211fca-b27e-4316-b1ae-c0d27925aa84: cannot allocate memory #96701 (comment)](https://github.com/kubernetes/kubernetes/issues/96701#issuecomment-911061574)
> 3. Set cgroup.memory=nokmem in grub: see [application crash due to k8s 1.9.x open the kernel memory accounting by default #61937 (comment)](https://github.com/kubernetes/kubernetes/issues/61937#issuecomment-567042968)
> 
> Or just upgrade to kubernetes 1.21 or higher

Ok thanks
