### ISSUE TITLE
Forbidden accessing or modifying other pod's cgroup in privileged container

### ISSUE THREAD

**Issue by carezkh** [kubernetes/kubernetes#112937]
### What happened?

I created a `privileged` pod on K8S v1.24.0. Use `kubectl exec` to enter the pod's shell, i noticed that the whole host cgroupfs was mount at `/sys/fs/cgroup` with `rw` mode. And i can get other pod's cgroup, even modify it!

Created `privileged` pod on K8S v1.25.2, same results. Created `privileged` pod on K8S v1.22.0 and v1.23.0, i can only access and modify the cgroup of the current pod, which is what i expect.

BTW, my OS is ubuntu-22.04 (kernel v5.15.0) with cgroup v2. When i tested in ubuntu-18.04 (kernel v4.15.0) with cgroup v1, K8S v1.24.0/v1.25.2/v1.23.0/v1.22.0 worked as expect!

### What did you expect to happen?

Forbidden accessing or modifying other pod's cgroup in privileged pod on K8S v1.24.0 (or higher).

### How can we reproduce it (as minimally and precisely as possible)?

step1. Use OS ubuntu-22.04 (or other distributions with cgroup v2)
step2. Create K8S cluster v1.24.0 (or higher) by kubeadm (follow the doc [kubeadm)](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-runtime)
step3. Install CNI plugin (i use calico)
step4. Create a privileged pod use the below manifest, and discover its `/sys/fs/cgroup`

```
apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine
    name: alpine
    command: ["sleep", "infinity"]
    securityContext:
      privileged: true
```

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux 18-61 5.15.0-48-generic #54-Ubuntu SMP Fri Aug 26 13:26:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Use kubeadm
`kubeadm init --kubernetes-version=v1.24.0 --pod-network-cidr=172.16.0.0/16`
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd --version

```
containerd containerd.io 1.6.8 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI Calico v3.24.1
</details>

**Comment by BenTheElder** [comment]
privileged means you have an extremely high degree of access to the node by design.
changing this would be a massively breaking change.
it is expected that you can do this.

the answer to restrict this is to restrict privileged in your cluster, there are various options available for that.

**Comment by carezkh** [comment]
@BenTheElder Thanks for your replay!

I tested replacing `privileged` with specific capabilities, and it worked! But if i want to still use `privileged` pod, is there any method to restrict the pod only accessing/modifying its own cgroup ?

**Comment by BenTheElder** [comment]
I don't think there's an easy way to do that, but you may instead be able to accomplish something you wanted to do with a privileged pod without using a privileged pod (including for example, the capabilities you mentioned).

The privileged knob predates Kubernetes (docker run --privileged) and gives essentially full access to the host for running highly privileged system daemons etc.

**Comment by carezkh** [comment]
@haircommander I agree with you.

I have tested K8S 1.22.0/1.23.0/1.24.0/1.25.2 on ubuntu22-04(with cgroup v2) and ubuntu18-04(with cgroup v1). `K8S 1.22.0~1.25.2  on ubuntu18-04` and `K8S 1.22.0~1.23.0 on ubuntu22-04` work as my expect (can only access/modifying its own cgroup in privileged pod), but `K8S 1.24.0~1.25.2 on ubuntu22-04` is different.

Trun off cgroup v2 on ubuntu22-04 and use cgroup v1, K8S 1.25.2 works as my expect!

**Comment by BenTheElder** [comment]
I believe I misunderstood the intent of this issue, the term "can" is a bit overloaded. My apologies.

A determined user in a privileged pod _can_ do essentially anything on the host if they're actively trying to ...

**Comment by carezkh** [comment]
@BenTheElder That's alright! Any suggestion will be appreciated！:)

**Comment by depay** [comment]
> @BenTheElder Thanks for your replay!
> 
> I tested replacing `privileged` with specific capabilities, and it worked! But if i want to still use `privileged` pod, is there any method to restrict the pod only accessing/modifying its own cgroup ?

BTW, which `specific capabilities`  works for cgroup modification inside a pod ?

**Comment by carezkh** [comment]
@depay It seems the cgroup fs is mounted on `/sys/fs/cgroup` with read-only option for unprivileged pods. I tried to remount cgroup fs with `rw` option for a unprivileged pod with `CAP_SYS_ADMIN` capability, but failed. Any suggestion?

**Comment by depay** [comment]
@carezkh  I've no idea except `privileged`. `RO` seems defined in OCI.

**Comment by haircommander** [comment]
I think ultimately this is expected. "privilege" option in the pod spec is a very heavy hammer and should not be given out lightly. There are many ways a privileged pod can mess with a node in kubernetes and this is one of them. Please only give it to pods you trust.

/close
