### ISSUE TITLE
e2e test logs filled with "observed a panic"

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/kubernetes#112996]
### What happened?

After https://github.com/kubernetes/kubernetes/pull/112043 merged, build logs for e2e tests have started showing stack traces that look like:
```
E1006 21:44:17.463438   10199 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 142 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic({0x68483e0?, 0xa628a00})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc00325c280?})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x68483e0, 0xa628a00})
	/usr/local/go/src/runtime/panic.go:884 +0x212
k8s.io/kubernetes/test/e2e/framework/node.allNodesReady.func1()
	test/e2e/framework/node/helper.go:125 +0x58
# ...
k8s.io/kubernetes/test/e2e/framework/node.AllNodesReady({0x0?, 0x0?}, 0x0?)
	test/e2e/framework/node/helper.go:108 +0x25
k8s.io/kubernetes/test/e2e/framework/node/init.init.0.func1.1()
	test/e2e/framework/node/init/init.go:33 +0x2f
```

It seems like the `ClientSet` used in this `AfterEach` is nil
https://github.com/kubernetes/kubernetes/blob/d0e735a664e723628773b23e5f22f8b90b91ec14/test/e2e/framework/node/init/init.go#L32-L34

I have a suspicion this is happening for storage tests that skip

### What did you expect to happen?

No new stack traces in build logs

### How can we reproduce it (as minimally and precisely as possible)?

Run e2e tests against the in-development version of kubernetes

### Anything else we need to know?

I identified when this started happening by looking for an increase in build-log size
```
$ gsutil ls -l gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/*/build-log.txt
# ...
   2004088  2022-10-06T20:16:39Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578107668730482688/build-log.txt
   2009028  2022-10-06T20:58:13Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578117231856848896/build-log.txt
   2093279  2022-10-06T21:36:57Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578127550587080704/build-log.txt
   6032240  2022-10-06T22:15:03Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578137365266829312/build-log.txt
   6034389  2022-10-06T22:57:48Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578146928544190464/build-log.txt
   6039118  2022-10-06T23:37:11Z  gs://kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578157749672349696/build-log.txt
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1578137365266829312 is the first build where this started happening, which happens to be the first build after https://github.com/kubernetes/kubernetes/pull/112043 merged, which is the PR that introduced this new way of invoking `AllNodesReady`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by spiffxp** [comment]
/sig testing
/triage accepted
/assign @pohly 
To put this on your radar

**Comment by pohly** [comment]
> I have a suspicion this is happening for storage tests that skip

Correct. This happens because of the ordering in https://github.com/kubernetes/kubernetes/blob/162aaf77f281658aa3823e69e2636936bcbe179a/test/e2e/storage/framework/testsuite.go#L51-L61

Tests gets skipped before `framework.BeforeEach` is called. This avoids the expensive namespace creation/deletion for tests that don't need to run. The `ginkgo.AfterEach` for `AllNodesReady` then gets executed although the framework didn't get initialized.

My preferred solution is to document that the framework instance might not be initialized in an AfterEach callback and add a nil check to `AllNodesReady`.

**Comment by pohly** [comment]
See https://github.com/kubernetes/kubernetes/pull/113097.

Only `AllNodesReady` was affected. The other framework extensions use DeferCleanup, which only runs when needed.
