### ISSUE TITLE
Wire up metrics/slis for kube-proxy

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kubernetes#112959]
### What would you like to be added?

As per, https://kep.k8s.io/3466, wire up metrics/slis for kube-proxy

### Why is this needed?

https://kep.k8s.io/3466

**Comment by thockin** [comment]
This sounds OK, but we need to translate it into real work-to-do - volunteers?

/triage accepted

**Comment by logicalhan** [comment]
> This sounds OK, but we need to translate it into real work-to-do - volunteers?
> 
> /triage accepted

@Richabanker is tackling this one :)
