### ISSUE TITLE
Dismiss connects to localhost early in the service chain when proxymode = ipvs

### ISSUE THREAD

**Issue by Dingshujie** [kubernetes/kubernetes#112949]
### What happened?

Loopback addresses (127.0.0.0/8, ::1/128) can't be used by services in proxy-mode=ipvs 

### What did you expect to happen?

it makes sense to dismiss those early, add RETURN rule to KUBE-NODE-PORT,KUBE-SERVICES
```
iptables -t nat -I KUBE-SERVICES 1 -s 127.0.0.0/8 -j RETURN
ip6tables -t nat -I KUBE-SERVICES 1 -s ::1 -j RETURN
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.25

### Cloud provider

<details>

</details>
none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by uablrek** [comment]
As mentioned in https://github.com/kubernetes/kubernetes/pull/112559, this is not a bug since the nodeport and ephemeral ranges overlap.

**Comment by uablrek** [comment]
The title of this issue should be changed to something like;
```
Dismiss nodePort connects to localhost early
```
Which would indicate that this is not a bug fix but an improvement. Also remove the invalid use-case in the description and add references to comments in https://github.com/kubernetes/kubernetes/pull/112559 like https://github.com/kubernetes/kubernetes/pull/112559#issuecomment-1259052540.

I think to dismiss nodePort connects to localhost early for proxy-mode=ipvs is an improvement, and in the majority of systems traffic to localhost is more common than traffic to nodePorts so this change will also improve ovarall performance.

### But...

This is **not** a fix for overlapping ephemeral and nodePort ranges!

**Comment by Dingshujie** [comment]
> 

Ok, i will change issue title and descripiton
