### ISSUE TITLE
kubelet panic when apiserver restart

### ISSUE THREAD

**Issue by fredkan** [kubernetes/kubernetes#112936]
### What happened?

kubelet panic with nil map when apiserver restart and kubelet is allocating scaler resources.

![image](https://user-images.githubusercontent.com/5801716/194738589-6d205c8b-777e-4e01-9d35-4cc689167c36.png)

### What did you expect to happen?

kubelet should not panic.

### How can we reproduce it (as minimally and precisely as possible)?

when kubelet is allocating scaler resource with pod starting, restart the api servers;

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

v1.23.6

</details>

### Cloud provider

<details>

None

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/v1.23.6/pkg/kubelet/cm/devicemanager/manager.go#L720

**Comment by pacoxu** [comment]
Can this be reproduced? Could you share some more information to reproduce it?
After kubelet restart, does it happen again?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

@fredkan can you please give more information on the set up and how it got to this state. Also if you can include kubelet.log, it will help diagnotics

**Comment by rphillips** [comment]
https://github.com/kubernetes/kubernetes/pull/113021 fixes the crash be allocating prior to calling allocateRemainingFrom.

**Comment by lixiaobing1** [comment]
Are master and minion in the same node?
Normally api-server desn't influnce kubelet.
![image](https://user-images.githubusercontent.com/16774510/196138452-c9220f50-f0d4-46ae-b038-2c4ab4da2f48.png)
![image](https://user-images.githubusercontent.com/16774510/196138998-961238c7-0762-407f-8231-7764a5fe0dd1.png)
