### ISSUE TITLE
kubelet: when memoryManager are enabled, kubelet fails to restart occasionally

### ISSUE THREAD

**Issue by gaohuatao-1** [kubernetes/kubernetes#113035]
### What happened?

In our scenario, cpuManager, memoryManager and topologyManager are enabled at the same time. There are two numa nodes: node0 and node1.
 The relevant parameter values are as follows：
- cpuManagerPolicy: static
- memoryManagerPolicy: Static
- topologyManagerPolicy: best-effort
- topologyManagerScope: pod

Firstly, we create a lot of pods that uses hugepages-2Mi of different specifications.  At this time, restart the kubelet continuously, and the restart failure may be triggered. The memoryManager failed to start with validateState func error.

The key log is as follows：
![image](https://user-images.githubusercontent.com/22569211/195485026-548f774d-3201-4906-bdb2-62f2634347c5.png)

View /var/lib/kubelet/memory_manager_state file,  we can find  the cause of this problem：
![image](https://user-images.githubusercontent.com/22569211/195486317-b301f8fa-e958-4a30-9326-7f1acb6eee3f.png)

We can find that the groups of NUMA nodes are joint!  NUMANodeMap[0].Cells:[0] and NUMANodeMap[1].Cells:[0,1] should not appear under normal circumstances, this will cause memoryManager validateState failed.

### What did you expect to happen?

1. When memoryManager 、cpuManager and topologyManager are enabled at the same time, kubelet always restart successfully.  
2.  NUMANodeMap[0].Cells and NUMANodeMap[1].Cells should not have intersection.

### How can we reproduce it (as minimally and precisely as possible)?

1. The memoryManager 、cpuManager and topologyManager are enabled at the same time.
2. Continuously create pods with different memory specifications and restart kubelet.
The above problem is occasional.

### Anything else we need to know?

By analyzing the code， the latest version of kubelet has the above bug.

Next, I will point out the bug in the code of kubelet memorymanager.
The key function of memoryManager:
- func (p *staticPolicy) Allocate(s state.State, pod *v1.Pod, container *v1.Container) error {} ,  
- func (p *staticPolicy) updateMachineState(machineState state.NUMANodeMap, numaAffinity []int, resourceName 
   v1.ResourceName, requestedSize uint64) {}
- func (p *staticPolicy) calculateHints(machineState state.NUMANodeMap, pod *v1.Pod, requestedResources 
   map[v1.ResourceName]uint64) map[string][]topologymanager.TopologyHint {}

In the func Allocate , call Topology Manager to get the aligned affinity across all hint providers, then in the func updateMachineState, machineState[nodeID].Cells value will be overwritten without any verification related to node grouping as done in the func calculateHints.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1"
</details>
 

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
kata-containers
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gaohuatao-1** [comment]
Can anyone give some advice on this issue?

**Comment by Tal-or** [comment]
Hello @gaohuatao-1, just curious, are you still actively looking into this issue? (specifically referring to PR #113090)

**Comment by gaohuatao-1** [comment]
> Hello @gaohuatao-1, just curious, are you still actively looking into this issue? (specifically referring to PR #113090)

Yes,  PTAL for the PR.

**Comment by Tal-or** [comment]
@ffromani after a careful examination of the root cause of this issue, it seems like it's a duplication of https://github.com/kubernetes/kubernetes/issues/113130

**Comment by Tal-or** [comment]
I would like to add more details and context for why [#113035](https://github.com/kubernetes/kubernetes/issues/113035) is a duplication of [#113130](https://github.com/kubernetes/kubernetes/issues/113130):

Both issues suffer from the same syndrome which is a failure in memory manager state validation after Kubelet restart. 
This in turn stems from the fact that the memory state obtained from the checkpoint file differ from the actual memory state that Kubelet builds after it restarted.

The reason for the validation's failure is because the node groups were organized differently. 
This issue has been resolved in https://github.com/kubernetes/kubernetes/pull/127074

**Comment by ffromani** [comment]
let's check if/how https://github.com/kubernetes/kubernetes/pull/123820 is related. Will review shortly.

**Comment by Tal-or** [comment]
Although I see similar behavior between both issues, the issue described here does not involve a relation between init and standard containers.

**Comment by ffromani** [comment]
> Although I see similar behavior between both issues, the issue described here does not involve a relation between init and standard containers.

yes, after reading properly #123820 seems a red herring and not related. We can proceed as planned previously
