### ISSUE TITLE
preferredDuringSchedulingIgnoredDuringException does not work with overproviosioning

### ISSUE THREAD

**Issue by pankajkumar229** [kubernetes/kubernetes#113055]
### What happened?

preferredDuringSchedulingIgnoredDuringException not working as expected.

What is happening is that we want a new pod to go to nodes that preferably have the label “2.19” and start very fast. We use preferredDuringSchedulingIgnoredDuringExecution and overprovisioning to make the starts fast. There are three nodes running with that label and they all have low priority overprovisioning pods running. The ideal action is that the low priority overprosioning pod in one of the nodes with the label “2.19" be kicked out and the new pod take its place. It seems to happen most of the time. But sometimes, the kicking out happens on the node without the label “2.19” and thus the prefferedDuringSchelingIgnoredDuringExecution does not work. Can we make the logic of choosing which low priority pod to kick out aware of preferredDuringSchedulingIgnoredDuringExecution ? I am guessing it is already aware of requiredDuringSchedulingIgnoredDuringExecution otherwise it would be kicking out pods that would not make way for the new pod.

Here are the events from the pod:
`
Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  8m53s  default-scheduler  0/7 nodes are available: 3 node(s) didn't match Pod's node affinity/selector, 4 Insufficient cpu, 4 Insufficient memory.
  Normal   Scheduled         8m46s  default-scheduler  Successfully assigned dc-core/dc-notebook-fd5392bb-de06-4ad8-9554-28874ecd57bd to gke-lab-computer-clu-ide-server-small-5d8c24b4-n2ww
  Normal   Pulling           8m42s  kubelet            Pulling image "pankajkumar229/ideserver:f8216693-5efb-4255-88ae-6a20090d8952_1665628833677"
  Normal   Pulled            5m35s  kubelet            Successfully pulled image "pankajkumar229/ideserver:f8216693-5efb-4255-88ae-6a20090d8952_1665628833677" in 3m6.945439145s
  Normal   Created           5m33s  kubelet            Created container dc-notebook-fd5392bb-de06-4ad8-9554-28874ecd57bd
  Normal   Started           5m32s  kubelet            Started container dc-notebook-fd5392bb-de06-4ad8-9554-28874ecd57bd
  Normal   Pulling           5m32s  kubelet            Pulling image "pankajkumar229/dc_sidecarserver:v2.19.1"
  Normal   Pulled            5m7s   kubelet            Successfully pulled image "pankajkumar229/dc_sidecarserver:v2.19.1" in 24.779949857s
  Normal   Created           5m7s   kubelet            Created container ide-sidercar
  Normal   Started           5m7s   kubelet            Started container ide-sidercar
`
  
Here is the affinity block:
`
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: v2.19
            operator: In
            values:
            - present
        weight: 1
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: cloud.google.com/gke-nodepool
            operator: In
            values:
            - ide-server-small
 `

### What did you expect to happen?

The scheduler should kick out low prioirity pods preferably on nodes that have the tag specified in preferredDuringSchedulingIgnoredDuringExecution

### How can we reproduce it (as minimally and precisely as possible)?

Create 2 nodes with a label (Eg 2.19) . Run low priority pods on them. 
Create 1 node without the label. Run low priority pod on it.

Create a high priority pod with this affinity block 

`
affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: v2.19
            operator: In
            values:
            - present
`

It will go to any of the three nodes at this point. IT should go to the first two nodes with the label.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12-gke.2300", GitCommit:"e55564cf3a1384026a54920174977659c8c56a50", GitTreeState:"clean", BuildDate:"2022-08-16T09:24:51Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
Scheduling result is impacted by several plugins, can you set the scheduler log level to --v=10, and post the scoring logs here. It's useful for analysis.

**Comment by kerthcet** [comment]
`preferredDuringSchedulingIgnoredDuringException` is a soft constraint, if you want a hard constraint, you can try with `requiredDuringSchedulingIgnoredDuringExecution`.

If soft constraint is what you want, as I mentioned, the scheduling result is impacted by all scoring plugins, you can increate the log level to 10 for debugging(you will see the scores for each node), or you can increase the weight of plugin `nodeAffinity`, it's 2 by default, see the details about KubeSchedulerConfiguration  here: https://kubernetes.io/docs/reference/scheduling/config/
