### ISSUE TITLE
Do pod preemption in parallel

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#113007]
### What would you like to be added?

When a pod requires preempting more than one pod, this happens sequentially. It should be done in parallel. https://github.com/kubernetes/kubernetes/blob/525280d285c4bb4970e571a1e13a601befd75434/pkg/scheduler/framework/preemption/preemption.go#L338-L370

/sig scheduling
/sig scalability

### Why is this needed?

Preemption happens in the scheduling cycle, meaning that no other scheduling attempts happen while preemption is ongoing, hurting throughput.

An alternative is to the deletes in a separate routine, like we do for binding.

**Comment by alculquicondor** [comment]
cc @ahg-g @mimowo @marseel

**Comment by tangwz** [comment]
I'm a newbie, may I have a try at this proposal?

**Comment by ahg-g** [comment]
Parallelizing the loops looks like the easier option to implement, but deleting in a separate routine will likely offer the better throughput for the average case.

**Comment by marseel** [comment]
Parallelizing loops seems fine from SIG Scalability perspective - we already do something similar for example in KCM when creating pods or in scheduler each binding is done by separate goroutine. 

One question though, is there a limit of pods that we want to preempt here? 100 parallel calls will be probably fine, but 1000 wouldn't be.

**Comment by kerthcet** [comment]
Victims greater than 50 is rare. And we general use a default Parallelizer which limits to 16 parallelism in scheduler.

**Comment by alculquicondor** [comment]
We only preempt pods from a single node, so that's a natural threshold.

And we have a parallelizing mini-library that has 16 workers by default.

**Comment by kidddddddddddddddddddddd** [comment]
> I'm a newbie, may I have a try at this proposal?

@tangwz Hi, do you still want to work on this one?

**Comment by tangwz** [comment]
> > I'm a newbie, may I have a try at this proposal?
> 
> @tangwz Hi, do you still want to work on this one?

Yes，It's still under discussion.

**Comment by tangwz** [comment]
@alculquicondor So we can use the parallelizing mini-library to do this?

**Comment by kerthcet** [comment]
You can use this parallelizer we defined in framework directly. https://github.com/kubernetes/kubernetes/blob/cb16d50068db5e4e0b70e3354d5c714a91743ecf/pkg/scheduler/framework/runtime/framework.go#L1344-L1346

**Comment by alculquicondor** [comment]
@tangwz feel free to take it by writing `/assign` on a comment.
