### ISSUE TITLE
Bring CLOMonitor Score to 100%

### ISSUE THREAD

**Issue by hernanpl** [kubernetes/kubernetes#113075]
This repo is signed up as part of the KubeCon [Security Slam](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/experiences/#security-slam). I'm bringing to your attention the checklist from the official [CLOMonitor page for Kubernetes](https://clomonitor.io/projects/cncf/kubernetes) -- it refreshes every hour, so it should be up-to-date.

### Summary

**Repository**: kubernetes
**URL**: https://github.com/kubernetes/kubernetes
**Checks sets**:  `COMMUNITY` + `CODE`
**Score**: 88

### Checks passed per category

| Category  |  Score  |
| :----------------- | --------: |
|  Documentation  |  100%  |
|  License  |  75%  |
|  Best Practices  |  95%  |
|  Security  |  75%  |
|  Legal  |  100%  |

### Documentation [100%]

  - [x] Adopters ([_docs_](https://clomonitor.io/docs/topics/checks/#adopters))
  - [x] [Changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG) ([_docs_](https://clomonitor.io/docs/topics/checks/#changelog))
  - [x] [Code of conduct](https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#code_of_conduct))
  - [x] [Contributing](https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#contributing))
  - [x] Governance ([_docs_](https://clomonitor.io/docs/topics/checks/#governance))
  - [x] [Maintainers](https://github.com/kubernetes/kubernetes/blob/master/OWNERS) ([_docs_](https://clomonitor.io/docs/topics/checks/#maintainers))
  - [x] [Readme](https://github.com/kubernetes/kubernetes/blob/master/README.md) ([_docs_](https://clomonitor.io/docs/topics/checks/#readme))
  - [x] Roadmap ([_docs_](https://clomonitor.io/docs/topics/checks/#roadmap))
  - [x] [Website](https://kubernetes.io) ([_docs_](https://clomonitor.io/docs/topics/checks/#website))
  
### License [75%]

  - [x] Apache-2.0 ([_docs_](https://clomonitor.io/docs/topics/checks/#license_spdx_id))
  - [x] Approved license ([_docs_](https://clomonitor.io/docs/topics/checks/#license_approved))
  - [ ] License scanning ([_docs_](https://clomonitor.io/docs/topics/checks/#license_scanning))
  
### Best Practices [95%]

  - [x] Analytics ([_docs_](https://clomonitor.io/docs/topics/checks/#analytics))
  - [ ] Artifact Hub badge ([_docs_](https://clomonitor.io/docs/topics/checks/#artifacthub_badge))
  - [x] Contributor License Agreement ([_docs_](https://clomonitor.io/docs/topics/checks/#cla))
  - [x] Community meeting ([_docs_](https://clomonitor.io/docs/topics/checks/#community_meeting))
  - [x] Developer Certificate of Origin ([_docs_](https://clomonitor.io/docs/topics/checks/#dco)) `EXEMPT`
  - [ ] Github discussions ([_docs_](https://clomonitor.io/docs/topics/checks/#github_discussions))
  - [x] [OpenSSF badge](https://bestpractices.coreinfrastructure.org/projects/569) ([_docs_](https://clomonitor.io/docs/topics/checks/#openssf_badge))
  - [x] [Recent release](https://github.com/kubernetes/kubernetes/releases/tag/v1.23.13) ([_docs_](https://clomonitor.io/docs/topics/checks/#recent_release))
  - [ ] Slack precense ([_docs_](https://clomonitor.io/docs/topics/checks/#slack_presence))
  
### Security [75%]

  - [x] Binary artifacts ([_docs_](https://clomonitor.io/docs/topics/checks/#binary_artifacts))
  - [x] Code review ([_docs_](https://clomonitor.io/docs/topics/checks/#code_review))
  - [x] Dangerous workflow ([_docs_](https://clomonitor.io/docs/topics/checks/#dangerous_workflow))
  - [ ] Dependency update tool ([_docs_](https://clomonitor.io/docs/topics/checks/#dependency_update_tool))
  - [x] Maintained ([_docs_](https://clomonitor.io/docs/topics/checks/#maintained))
  - [ ] Software bill of materials (SBOM) ([_docs_](https://clomonitor.io/docs/topics/checks/#sbom))
  - [x] [Security policy](https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS) ([_docs_](https://clomonitor.io/docs/topics/checks/#security_policy))
  - [ ] Signed releases ([_docs_](https://clomonitor.io/docs/topics/checks/#signed_releases))
  - [x] Token permissions ([_docs_](https://clomonitor.io/docs/topics/checks/#token_permissions))
  
### Legal [100%]

  - [x] Trademark disclaimer ([_docs_](https://clomonitor.io/docs/topics/checks/#trademark_disclaimer))
  
For more information about the checks sets available and how each of the checks work, please see the [CLOMonitor's documentation](https://clomonitor.io/docs/topics/checks/).

**Comment by eddie-knight** [comment]
It seems the standard way of retrieving the k8s SBOM is via the download URL that is created on each release. Can anyone correct my understanding there?

I found the way the bom is _created_ easily enough, but learning where to retrieve it took a bit of digging. 

Seems the most practical step would be to add something to the usage docs with a tiny explainer on how to retrieve the sbom. Doing it in the README.md with a subheader may also be the simplest/fastest way to resolve the CLOMonitor/Security Slam goals.

ref:
- https://github.com/kubernetes/release/issues/1837
- https://github.com/puerco/release/commit/55320a8238d30686aafe02983746739bae096655

**Comment by BenTheElder** [comment]
> License scanning ([docs](https://clomonitor.io/docs/topics/checks/#license_scanning))

IIRC we looked at snyk and fossa and they fell over trying to process this repo.

We have https://github.com/kubernetes/kubernetes/tree/master/LICENSES which automatically contains all dependency licenses via https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/hack/verify-vendor-licenses.sh + https://github.com/kubernetes/kubernetes/blob/cb7beb591216de93bef22525a6c5f0e435e21789/hack/update-vendor-licenses.sh

which is verified via https://github.com/kubernetes/kubernetes/blob/7e77252b0d5fcd3689f2f7e4a21757e53965c092/hack/verify-licenses.sh

And also human review by the dependency approval team (kubernetes/dep-approvers), following this guide: 
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#reviewing-and-approving-dependency-changes

**Comment by mrbobbytables** [comment]
@hernanpl @BenTheElder is 100% right, and as far as I know - the kubernetes project (AFAIK) wasn't signed up for the security slam. If it was, can you tell us who? It wasn't brought up to steering or relayed to the community at all.

**Comment by justaugustus** [comment]
> I think we can close this issue as the items are not really actionable.

Agreed.
/close
