### ISSUE TITLE
Err msg incorrect when creating already exists pod of statefulset

### ISSUE THREAD

**Issue by yangwenyi1995** [kubernetes/kubernetes#113078]
### What happened?

When pods of statefulset created, sometimes kube-controller-manager will report "FailedCreate" abnormal event, but the conditions of creating pod are all satisified all the time.

### What did you expect to happen?

We shouldn't report abnormal events when creating statefulset if conditions are satisified.

### How can we reproduce it (as minimally and precisely as possible)?

Firstly, we confirm the difference of err when create existing pod of statefulset:
create existing pod with metadata.generateName, err is : 
Error from server (ServerTimeout): error when creating "xxx.yaml": The POST operation against Pod could not be completed at this time, please try again.

create existing pod without metadata.generateName, err is : 
Error from server (AlreadyExists): error when creating "cse-etcd-0.yaml": pods "cse-etcd-0" already exists

Obviously, we prefer to get "AlreadyExists" err in this position. But in kube-controller-manager, when creating pod of statefulset, we assigne the podName and generateName, result in reporting the abnormal event in some case. So we just need to set generateName to empty to avoid abnormal event.

kube-controller-manager code:
```go
func (spc *StatefulPodControl) CreateStatefulPod(ctx context.Context, set *apps.StatefulSet, pod *v1.Pod) error {
	// Create the Pod's PVCs prior to creating the Pod
	if err := spc.createPersistentVolumeClaims(set, pod); err != nil {
		spc.recordPodEvent("create", set, pod, err)
		return err
	}
	// If we created the PVCs attempt to create the Pod
	err := spc.objectMgr.CreatePod(ctx, pod)
	// sink already exists errors
	if apierrors.IsAlreadyExists(err) {
		return err
	}
	if utilfeature.DefaultFeatureGate.Enabled(features.StatefulSetAutoDeletePVC) {
		// Set PVC policy as much as is possible at this point.
		if err := spc.UpdatePodClaimForRetentionPolicy(set, pod); err != nil {
			spc.recordPodEvent("update", set, pod, err)
			return err
		}
	}
	spc.recordPodEvent("create", set, pod, err)
	return err
}
```

### Kubernetes version

<details>

```console
$ kubectl version
1.22.1
```
the code is the same as version 1.25
</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mengjiao-liu** [comment]
PR https://github.com/kubernetes/kubernetes/pull/104699 has fixed the issue in version 1.23, and you can upgrade the Kubernetes cluster to version 1.23.

```
The Kubernetes project maintains release branches for the most recent three minor releases (1.25, 1.24, 1.23)
```
https://kubernetes.io/releases/
