### ISSUE TITLE
Not possible to load an ephemeral container in a POD with runAsNonRoot:true

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#113006]
### What happened?

If a POD has (on pod-level);
```yaml
      securityContext:
        runAsNonRoot: true
```
loading a ephemeral debug container fails;
```
# kubectl debug --image docker.io/library/alpine:latest alpine-noroot-787848b5b7-5t8c6 -it -- sh
Defaulting debug container name to debugger-7dp4l.
Warning: container debugger-7dp4l: container has runAsNonRoot and image will run as root (pod: "alpine-noroot-787848b5b7-5t8c6_default(15a12642-0af0-4c3c-a7a6-27bf746e82fe)", container: debugger-7dp4l)
(hangs until ctrl-C)
```

### What did you expect to happen?

It should be possible to specify a `securityContext` for the ephemeral container so it can run as non-root, but have capabilities set to allow it to perform debug actions, e.g. `NET_ADMIN` or `SYS_PTRACE`.

### How can we reproduce it (as minimally and precisely as possible)?

Start PODs with `runAsNonRoot: true` e.g. with the manifest below. Then try to load an ephemeral debug container;
```
# kubectl debug --image docker.io/library/alpine:latest alpine-noroot-787848b5b7-5t8c6 -it -- sh
Defaulting debug container name to debugger-7dp4l.
Warning: container debugger-7dp4l: container has runAsNonRoot and image will run as root (pod: "alpine-noroot-787848b5b7-5t8c6_default(15a12642-0af0-4c3c-a7a6-27bf746e82fe)", container: debugger-7dp4l)
(hangs until ctrl-C)
```

<details><summary>alpine-noroot.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-noroot
spec:
  selector:
    matchLabels:
      app: alpine-noroot
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine-noroot
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: alpine
        image: docker.io/library/alpine:latest
        imagePullPolicy: IfNotPresent
        command: ["tail", "-f", "/dev/null"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
```

</details>

### Anything else we need to know?

To have a pre-defined set of profiles is not feasible since the wanted/allowed securityContext will vary between applications.

### Kubernetes version

```console
Server Version: v1.25.2
```

### Cloud provider

N/A

### OS version

<details>

```console
Linux 6.0.0 #4 SMP PREEMPT_DYNAMIC Wed Oct 5 09:19:23 CEST 2022
```

</details>

### Install tools

None

### Container runtime (CRI) and version (if applicable)

`crio version 1.25.0`

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by uablrek** [comment]
I am working on a PR for this.

**Comment by sftim** [comment]
Should we transfer this issue to k/kubectl?

**Comment by KnVerey** [comment]
I've been assigned to the linked PR but I don't have enough context on `kubectl debug` to know whether that's the right solution to the problem described. I know the [KEP includes the concept of profiles](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#debugging-profiles) that modify the capabilities used (https://github.com/kubernetes/kubectl/issues/1108), which sounds like it might be the preferred solution to this problem. @verb @knight42 can you please triage this issue and the associated PR? Thanks!

**Comment by uablrek** [comment]
A bug it is - you can't start an ephemeral container. To make things worse, _it is loaded_ but not started. So basically a dead container is created that can't be unloaded.

How to _fix_ the problem can be debated though. Please see the comment;
> To have a pre-defined set of profiles is not feasible since the wanted/allowed securityContext will vary between applications.

**Comment by brianpursley** [comment]
I too was assigned as a reviewer and also don't have enough context on debug to know for certain if this is the right approach or not.

However I do have a couple of thoughts:
1. If I'm debugging a pod, is there ever a case where I would NOT want to use the security context if one is set?  In the case of a single container, or when all containers have an identical security context, it seems like the debug command could just do this for me automatically. And then in the rare (?) case where there are multiple containers and they happen to have different security contexts, then I need to have a way to tell it which one to use and that is where the flag would be needed.  Just a thought and I could be off-base.
2. If we have a flag, it would not apply when debugging a node, so that would be another validation I think (this is more of a PR comment, but will mention it here since I'm already commenting)

**Comment by uablrek** [comment]
About continers with different privileges, we sometimes do things that require more privileges in init-containers while the "real" containers have more constraints.

And a debug container often (always?) needs more privileges:
>  so it can run as non-root, but have capabilities set to allow it to perform debug actions, e.g. NET_ADMIN or SYS_PTRACE.

**Comment by uablrek** [comment]
The comment above about init-containers is probably applicable also for side-car containers, for instance injected by a service mesh. But I have very little experience about those.

**Comment by rlipscombe** [comment]
> If I'm debugging a pod, is there ever a case where I would NOT want to use the security context if one is set?

Yes.

If I want to use a debug container to run tcpdump against the pod, then I would want to specify a completely new security context -- one with NET_ADMIN (iirc).

**Comment by uablrek** [comment]
From "What did you expect to happen?" in the description;

> It should be possible to specify a securityContext for the ephemeral container so it can run as non-root, but have capabilities set to allow it to perform debug actions, e.g. NET_ADMIN or SYS_PTRACE.

**Comment by rlipscombe** [comment]
Yeah; I'm agreeing with you @uablrek. I'm addressing @brianpursley's suggestion, here:

> ... when all containers have an identical security context, it seems like [just use that one]. And then ... multiple containers ... have different security contexts ... tell it which one to use

That seems to be talking about copying the security context from an existing container in the pod. I'm pointing out (reinforcing) that you can't do that if none of the containers have the security context you want to use.

Given that `securityContext` is part of the PodTemplate, it seems like `kubectl debug` should use that one by default, and also offer `--security-context=JSON_LITERAL` and `--security-context-from=CONTAINER` options.

**Comment by brianpursley** [comment]
> Yeah; I'm agreeing with you @uablrek. I'm addressing @brianpursley's suggestion

To be clear, I'm not opposed to this feature, but am not too familiar with the inner workings of debug, so I was only asking questions and trying to understand the reason this is needed.

Maybe @verb can offer up some thoughts on this feature request and associated PR?

**Comment by uablrek** [comment]
Please see https://github.com/kubernetes/kubernetes/issues/113006#issuecomment-1308258805.

This issue primarily is about the _bug_, not the feature request. A simple solution would be to reject the command and thus avoid creation of an non-unloadable zombie container, or at least document a "don't do this".

Now, that would not be a good UE, hence the "What did you expect to happen?":

>    It should be possible to specify a securityContext for the ephemeral container so it can run as non-root, but have capabilities set to allow it to perform debug actions, e.g. NET_ADMIN or SYS_PTRACE.

which really is a feature request. My PR https://github.com/kubernetes/kubernetes/pull/113009 solves the bug, and is useul in cases where the POD is not nonRoot, and you have a privileged init-container, for instance to set sysctls (our case).

Also the PR is simple. To debate a new feature in K8s usually takes like 6 months or more, perhaps including a KEP (which I am not prepared to drive).

**Comment by verb** [comment]
> which really is a feature request. My PR #113009 solves the _bug_. It is also useul in cases where the POD is _not_ nonRoot, and you have a privileged init-container, for instance to set sysctls (our case, please see [#113006 (comment)](https://github.com/kubernetes/kubernetes/issues/113006#issuecomment-1309803079)).
> 
> Also, the PR is simple. To debate a new feature in K8s usually takes like 6 months or more, perhaps including a KEP (which I am not prepared to drive).

fwiw, I think #113009 sounds like more of a feature request than a bug fix:

* It doesn't fix the bug, `kubectl debug --image docker.io/library/alpine:latest alpine-noroot-787848b5b7-5t8c6 -it -- sh` will continue to cause problems if you don't specify the new flag.
* As a mitigation, we can suggest using a container image that doesn't run as root. That works currently and doesn't require a new flag
* Perhaps adding a new flag should require a bit of scrutiny. Flags define the UI, and adding a lot of them makes kubectl harder to use

Ideally to fix the bug we'd reject an ephemeral container that wouldn't be able to run, but that's tricky because it requires examining the container image, and this happens after validation.

As a feature, I'd prefer to make the security context configurable rather than allowing it to be copied from another container. What we really need here is the ability to define per-use custom profiles. This still wouldn't fix the bug described here, though.

/cc @ardaguclu @sding3

**Comment by sding3** [comment]
> make the security context configurable rather than allowing it to be copied from another container

Agreed with this. One option for the implementation could be through a new debug profile, e.g. `custom`, that could take in the custom security context specification through another flag where the flag value points to a file containing the user-specified security context specification.

For the exact issue described in the issue description, I think even if we addressed that specific issue, there will still be other conditions that might prevent the debug container from coming up, e.g. invalid image reference, temporary unavailable from the image registry, etc.

**Comment by ardaguclu** [comment]
> What we really need here is the ability to define per-use custom profiles.

I definitely agree to ^. We provide a set of static profiles can be used easily. However, as also seen in several other filed issues, users might need to change security context, preserving labels, etc. 

Instead simply exposing a flag specific to security context, we need to provide a `custom` profile type(which means a KEP I can be volunteer to write :) ).

**Comment by dev-dsp** [comment]
`kubectl debug ... --custom=<(echo '{"securityContext":{"runAsNonRoot":false,"runAsUser":0}}')`

**Comment by Aiosa** [comment]
Please introduce this feature. Pod crashes, you don't know the problem, so you go for a debug container and now you have two dead / unresponsive beasts. Great.

**Comment by itspooya** [comment]
For anyone wondering and coming upon this:
https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/
https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#debugging-profiles
it is actually implemented
