### ISSUE TITLE
Warning | when PSP (Pod Security Policy) applied to Istio

### ISSUE THREAD

**Issue by yugandhar-btc** [kubernetes/kubernetes#113051]
### What happened?

Could you please help me, what would be the changes required in [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) as per the latest Kubernetes versions (from v.21+)

When I applied [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) for ISTIO pods it give me Warning

![image](https://user-images.githubusercontent.com/69250111/195558090-f1192f2f-2e27-417f-a30c-cf92261739eb.png)

### What did you expect to happen?

Upgarded version of pod_security_policy code

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://user-images.githubusercontent.com/69250111/195558090-f1192f2f-2e27-417f-a30c-cf92261739eb.png)

kubectl apply \
  -f $GIT_ROOT/deployment/kubernetes/pod_security_policy.yaml \
  -f $GIT_ROOT/deployment/kubernetes/pod_security_policy-istio.yaml

### Kubernetes version

Client Version: v1.23.4
Server Version: v1.22.12-gke.1200

### Cloud provider

GCP

**Comment by lengrongfu** [comment]
- /sig auth
- /sig apps

**Comment by lengrongfu** [comment]
This should not be considered a bug, but a feature. Do you agree? @yugandhar-btc

**Comment by liggitt** [comment]
PSP migration info is at https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/

/remove-kind bug
/kind support
/close

**Comment by yugandhar-btc** [comment]
@liggitt could you please help the changes required in [pod_security_policy-istio.yaml](https://github.com/GoogleCloudPlatform/fda-mystudies/blob/master/deployment/kubernetes/pod_security_policy-istio.yaml) file.
