### ISSUE TITLE
Pick up fixes from eks-distro maintained by AWS folks

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#113088]
- [x] [0001-EKS-PATCH-Pass-region-to-sts-client.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0001-EKS-PATCH-Pass-region-to-sts-client.patch) - Fixing in https://github.com/kubernetes/kubernetes/pull/113084
- [ ] ~[0002-EKS-PATCH-Bypassed-admission-controller-webhook-for-.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0002-EKS-PATCH-Bypassed-admission-controller-webhook-for-.patch) - Issue is still open https://github.com/kubernetes/kubernetes/issues/92157~ WONT-FIX (or CANT-FIX!)
- [x] [0003-EKS-PATCH-Use-GNU-date.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0003-EKS-PATCH-Use-GNU-date.patch) - Proposed an alternate patch - https://github.com/kubernetes/kubernetes/pull/113210
- [x] [0004-EKS-PATCH-aws_credentials-update-ecr-url-validation-](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0004-EKS-PATCH-aws_credentials-update-ecr-url-validation-.patch) - Fixing in https://github.com/kubernetes/kubernetes/pull/113087
- [ ] ~[0005-EKS-PATCH-AWS-Include-IPv6-addresses-in-NodeAddresse.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0005-EKS-PATCH-AWS-Include-IPv6-addresses-in-NodeAddresse.patch)~ - ~Reopened https://github.com/kubernetes/kubernetes/pull/86918 for this!~ ~Opened https://github.com/kubernetes/kubernetes/pull/113114~ This is being treated as a feature, so won't land in k/k and is already in the external cloud provider for AWS repo 
- [x] [0006-EKS-PATCH-Update-aws-sdk-to-v1.42.23-for-ap-southeas.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0006-EKS-PATCH-Update-aws-sdk-to-v1.42.23-for-ap-southeas.patch) - Fixing in https://github.com/kubernetes/kubernetes/pull/113084
- [x] [0007-EKS-PATCH-Make-kubelet-set-alpha.kubernetes.io-provi.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0007-EKS-PATCH-Make-kubelet-set-alpha.kubernetes.io-provi.patch) - Fixed in https://github.com/kubernetes/kubernetes/pull/109794
- [x] [0008-EKS-PATCH-Skip-mount-point-checks-when-possible-duri.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0008-EKS-PATCH-Skip-mount-point-checks-when-possible-duri.patch) - Already fixed in https://github.com/kubernetes/kubernetes/pull/109676
- [x] [0009-EKS-PATCH-Add-rate-limiting-when-calling-STS-assume-.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0009-EKS-PATCH-Add-rate-limiting-when-calling-STS-assume-.patch) - Fixed in https://github.com/kubernetes/kubernetes/pull/110706
- [x] [0010-EKS-PATCH-Update-naming-for-a-const.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0010-EKS-PATCH-Update-naming-for-a-const.patch) - Fixed in https://github.com/kubernetes/kubernetes/pull/110706
- [x] [0011-EKS-PATCH-Update-aws-sdk-go-from-v1.42.23-to-v1.44.1.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0011-EKS-PATCH-Update-aws-sdk-go-from-v1.42.23-to-v1.44.1.patch) - Fixing in https://github.com/kubernetes/kubernetes/pull/113084
- [x] [0016-EKS-PATCH-apiserver-healthz-upper-log-verbosity-for-.patch](https://github.com/aws/eks-distro/blob/v1-19-eks-12/projects/kubernetes/kubernetes/1-19/patches/0016-EKS-PATCH-apiserver-healthz-upper-log-verbosity-for-.patch) - Fixing in https://github.com/kubernetes/kubernetes/pull/113107

https://github.com/kubernetes/kubernetes/issues/113088#tasklist-block-eb56b730-9f26-4ec9-8634-2019b15b2cc3

**Comment by dims** [comment]
for [0005-EKS-PATCH-AWS-Include-IPv6-addresses-in-NodeAddresse.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0005-EKS-PATCH-AWS-Include-IPv6-addresses-in-NodeAddresse.patch) i reopened https://github.com/kubernetes/kubernetes/pull/86918 as the bot closed it.

**Comment by dims** [comment]
cc @kschumy

**Comment by BenTheElder** [comment]
> [0003-EKS-PATCH-Use-GNU-date.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0003-EKS-PATCH-Use-GNU-date.patch) - Will not propose to kubernetes/kubernetes as it is a special case that can be fixed by installing correct date binary using brew

Actually, this one was already proposed, I think I was on reviewing this and it slipped through the cracks, I can only just barely remember it.
We should double check if we should do that, at the very least we should ensure the correct binary is available and give the user a hint, if not just handling the differences.

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/100044 for reference

**Comment by dims** [comment]
@BenTheElder thanks for the nudge, here's the new PR that is a replacement for [0003-EKS-PATCH-Use-GNU-date.patch](https://github.com/aws/eks-distro/blob/main/projects/kubernetes/kubernetes/1-24/patches/0003-EKS-PATCH-Use-GNU-date.patch):
https://github.com/kubernetes/kubernetes/pull/113210

**Comment by BenTheElder** [comment]
@dims is this all done now? 😄

**Comment by dims** [comment]
yep. thanks @BenTheElder
