### ISSUE TITLE
EndpointSliceCache Only has 1 IP Address Even Though Multiple Endpoints Are Running

### ISSUE THREAD

**Issue by rnemeth90** [kubernetes/kubernetes#113079]
### What happened?

Cluster information:
Kubernetes version: 1.22.11
Cloud being used: Azure/AKS
Installation method:
Host OS: Linux/Windows
CNI and version: Azure CNI
CRI and version: containerd (containerd-2022.09.13)

We have several K8s clusters running in AKS. We have Linux and Windows node pools and deployments running on each. We are using the node autoscaler to autoscale node pools, and HPA’s or Keda to autoscale most of our deployments. Some deployments use HPA, some use Keda.

We are troubleshooting random 502’s with most of our apps running in Kubernetes. In our troubleshooting, we found in the kube-proxy logs, that the EndpointSliceCache is being set to only 1 IP address, even though we have multiple pods running behind the service. This is an example message we are seeing in the logs:

2022-10-15T08:56:04.570885342Z stderr F I1015 08:56:04.570747 1 endpointslicecache.go:366] Setting endpoints for “mynamespace/myservice” to [10.180.160.124:8080 ]

This particular deployment had 2 pods running at this time. Should we be concerned about this? it seems like we would never want to have only 1 IP address in the Endpointslicecache when there are multiple pods running, as this would defeat the purpose of HA (at the pod level).

### What did you expect to happen?

I would expect that the EndpointSliceCache always contains the IP addresses of all running (successful probes) pods in a replica set. 

### How can we reproduce it (as minimally and precisely as possible)?

It seems to be random. 

### Kubernetes version

<details>

```console
$ kubectl version

Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.2
Kustomize Version: v4.5.4
Server Version: v1.22.11
WARNING: version difference between client (1.24) and server (1.22) exceeds the supported minor version skew of +/-1

```

</details>

### Cloud provider

<details>
AKS / Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Windows Server 2019
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

AKSUbuntu-1804gen2containerd-2022.09.13

AKSWindows-2019-containerd-17763.3406.220913

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Azure CNI
</details>

**Comment by aojea** [comment]
What's the pod status? If is not ready it will not be present on the endpoint

/Cc @khenidak

**Comment by khenidak** [comment]
/triage needs-information

The log line is produced here https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/proxy/endpointslicecache.go#L357 _for every endpoint_.

+1 on @aojea question. And also can you use kubectl to get the endpointslices generated for that service?

Also please note `502` means you client is in fact connected to endpoint but you server responded with http error.

**Comment by thockin** [comment]
ping for update?
