### ISSUE TITLE
Watch cache cannot be initialized for large responses

### ISSUE THREAD

**Issue by S-Chan** [kubernetes/kubernetes#113076]
### What happened?

We observed the following logs on API servers:

```
cacher.go:419] cacher (*core.ConfigMap): unexpected ListAndWatch error: failed to list *core.ConfigMap: rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (2169480971 vs. 2147483647); reinitializing...
```

On further investigation, we found that there were a number of large ConfigMaps taking up >2GB on the cluster. When the cacher starts up, the initial list response size is too large, so it fails.

### What did you expect to happen?

The watch cache would start up.

### How can we reproduce it (as minimally and precisely as possible)?

Create enough ConfigMaps on a cluster to exceed the 2GB message limit, and restart the API servers.

### Anything else we need to know?

Related PRs:
https://github.com/kubernetes/kubernetes/pull/75389/files (pagination of the initial list)
https://github.com/etcd-io/etcd/pull/8437/files (setting max etcd message size)

### Kubernetes version

<details>

```
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.11", GitCommit:"5824e3251d294d324320db85bf63a53eb0767af2", GitTreeState:"clean", BuildDate:"2022-06-16T05:33:01Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.15", GitCommit:"8eb9c23f7e14a78e67cd8e3eb7853fa794e0bc4f", GitTreeState:"clean", BuildDate:"2022-07-12T23:05:33Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by S-Chan** [comment]
One possible solution would be to allow configuration of the cache list chunk size.

**Comment by gjkim42** [comment]
cc
