### ISSUE TITLE
KMS: prefixTransformers.TransformToStorage allocates poorly

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#113058]
The code at:

https://github.com/kubernetes/kubernetes/blob/215f236a6b9087c63f4f65fd34a066e56fae54d7/staging/src/k8s.io/apiserver/pkg/storage/value/transformer.go#L154-L157

assumes that the transformation does not change the size of the data.  Since we know it most cases that it does, we should try to account for that during the allocation.

**Comment by lengrongfu** [comment]
@enj I think there is no problem with the memory allocation of `prefixedData`, because `prefixedData = append(prefixedData, result...)` needs to be executed afterwards, in order to avoid executing new memory allocation during append, so `cap=len(data)+len(transformer. Prefix)` is no problem. IMO

**Comment by lengrongfu** [comment]
After reading your code, I understand.
