### ISSUE TITLE
Improve bash completion of kubectl

### ISSUE THREAD

**Issue by marekbiskup** [kubernetes/kubernetes#11310]
TODOs: *Last updated on Sept 2 by Janet*
- [x] kubectl label - suggest a resource type
  - [x] kubectl get and delete also use kubectl.NewHumanReadablePrinter to get the resources back, thus should be fixed as well.
- [x] kubectl exec - suggest the pod name
- [x] kubectl rolling-update - suggest the rc name
- [x] check that `kubectl log $pod [tab][tab]` is doing the right thing
- [x] Distribute `contrib/completions/bash/kubectl` with kubernetes binaries
- [x] Put information about kubectl completion in user guide
  - [x] docs/getting-started-guides/gce.md

---

Recently some users reported that there is no completion for the kubectl command. But there is. Unfortunately it is not documented how to install it.

I found that all needs to be done is to:
```
$ source ./contrib/completions/bash/kubectl
```
(or maybe just copy this file into /etc/bash_completion.d/)

This information should be put into the user guide (maybe it is there - I just can't find it)
I think it should be included for instance here:
docs/getting-started-guides/gce.md

There are also some minor issues:

1.  `kubectl rolling-update` does not suggest the rc name
1. `kubectl exec` does not suggest the pod name
1. `kubectl label` does not suggest a resource type (maybe this is ok because we can give --overwrite here)

**Comment by marekbiskup** [comment]
It looks like the bash-completion file is not distributed with kubernetes binaries:
```
biskup@cathedral:~/tmp$  curl -sS https://get.k8s.io | bash
biskup@cathedral:~/tmp$ cd kubernetes/
biskup@cathedral:~/tmp/kubernetes$ find . | grep kubectl
./platforms/darwin/amd64/kubectl
./platforms/darwin/386/kubectl
./platforms/windows/amd64/kubectl.exe
./platforms/linux/arm/kubectl
./platforms/linux/amd64/kubectl
./platforms/linux/386/kubectl
./cluster/kubectl.sh
./examples/kubectl-container
./examples/kubectl-container/Dockerfile
./examples/kubectl-container/Makefile
./examples/kubectl-container/README.md
./examples/kubectl-container/pod.json
./examples/kubectl-container/.gitignore
```

**Comment by jacobtomlinson** [comment]
:+1: This should definitely be provided with the binaries.

**Comment by bgrant0607** [comment]
Good suggestions. 
Cc @lavalamp

**Comment by marekbiskup** [comment]
@nikhiljindal , please cofirm that the bash completion file is distributed with k8s binaries:

namely contrib/completions/bash/kubectl

For me it looks like it isn't.

**Comment by nikhiljindal** [comment]
cc @eparis

**Comment by JanetKuo** [comment]
I confirmed and it isn't.

**Comment by JanetKuo** [comment]
TODOs:
- [ ] kubectl label - suggest a resource type
- [x] kubectl exec - suggest the pod name
- [ ] kubectl rolling-update - suggest the rc name
- [ ] Distribute `contrib/completions/bash/kubectl` with kubernetes binaries
- [ ] Put information about kubectl completion in user guide
  - [ ] docs/getting-started-guides/gce.md

**Comment by eparis** [comment]
Maybe add: check that `kubectl log $pod [tab][tab]` is doing the right thing....

**Comment by JanetKuo** [comment]
Checklist added

**Comment by zmerlynn** [comment]
@JanetKuo: Depending on where you want it in the tarball, https://github.com/kubernetes/kubernetes/blob/12647523d202398bc38839c197cba31953c03a49/build/common.sh#L833 is a good place to start. You can use `make release` and then iterate on `tar -tzf _output/release-tars/kubernetes.tar.gz` until you're comfortable with the changes. (If I'm making packaging changes, I'll frequently start by dumping the sorted output of that command into a file, then later diff against it to make sure I got exactly the change I wanted.)

**Comment by JanetKuo** [comment]
@eparis Right now both `kubectl log $pod -c [tab][tab]` and `kubectl log $pod [tab][tab]` brings up all containers `$pod` has. Since `-c` is optional (the without -c way is supported as legacy behavior), this is expected. I'm not sure how to force the bash completion to print `-c` instead of container names when `kubectl log $pod [tab][tab]` since `-c` flag isn't set as required in `kubectl logs` code.
