### ISSUE TITLE
PVC recreation needed when Stateful set Pod stuck in pending

### ISSUE THREAD

**Issue by rrangith** [kubernetes/kubernetes#113139]
### What happened?

- User cordons a node with a pvc bound to a local persistent volume
- User deletes a stateful set pod from that node
- The pod is in pending because the pvc is still bound to a local pv on the cordoned node (expected)
- The node dies and the pvc is deleted
- The pod is still stuck in pending because the pvc is missing (bug)

The pod now needs to be manually deleted so that the pod+pvc can be recreated

### What did you expect to happen?

After the pvc was deleted, the statefulset controller should have recreated it and bound it to a new node's local pv so that the pending pod could be scheduled. Currently the only way to get the pod out of pending is to manually delete it so that it recreates itself and its pvc

We used https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner for the local PVs, but the problem is not limited to this particular provisioner

### How can we reproduce it (as minimally and precisely as possible)?

- create a stateful set with a pvc that is bound to a local PV
- use `kubectl cordon` to cordon a node with a local pv
- delete a statefulset pod from that node
- delete the pvc from that node

the pod is now stuck in pending due to a missing pvc

### Anything else we need to know?

There was a related issue https://github.com/kubernetes/kubernetes/issues/74374 but this only fixed the issue when the order of operations was delete pvc -> delete pod. but in this case, it is delete pod -> delete pvc

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:25:45Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.9-dd.1", GitCommit:"d9705166e190927de148edae148bf46471c7f8d5", GitTreeState:"clean", BuildDate:"2022-03-07T11:53:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tested on aws and gcp
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xing-yang** [comment]
This issue was fixed by https://github.com/kubernetes/kubernetes/pull/113270.  The new issues look different.

/close
