### ISSUE TITLE
Enable OpenSSF Scorecard Github Action and Badge

### ISSUE THREAD

**Issue by joycebrum** [kubernetes/kubernetes#113144]
### What would you like to be added?

Hi I am Joyce from Google and I'm working on behalf of the [Open Source Security Foundation][ossf] (OpenSSF) to help essential open-source projects improve their supply-chain security.

I would like to suggest the adoption of an OpenSSF, [in partnership with GitHub][sc-blog], tool called [Scorecard][sc]. It runs dozens of automated security checks to help maintainers better understand their project's security posture. 

To make it easier to use, the OpenSSF has also developed the [Scorecard GitHub Action][sc-gha]. It is very lightweight and runs on every change in the main branch. It publishes the scorecard check's results in the project's [security dashboard](https://github.com/kubernetes/kubernetes/security), and include suggestions on how to solve any issues (see examples below). The Action does not run or interact with any workflows, but merely parses them to identify possible vulnerabilities. This Action has been adopted by 1800+ projects already, having some prominent users like [Tensorflow][tensorflow], [Angular][angular], [Flutter][flutter], [sos.dev][sos-dev] and [deps.dev][deps-dev].

![Code scanning dashboard with multiple alerts, including Code-Review and Token-Permissions][img-security]

![Detail of a Token-Permissions alert, indicating the specific file and remediation steps][img-detail]

[checks]: https://github.com/ossf/scorecard#scorecard-checks
[ossf]: https://openssf.org/
[sc]: https://github.com/ossf/scorecard
[sc-blog]: https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/
[sc-gha]: https://github.com/ossf/scorecard-action
[FAQ]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions
[img-security]: https://user-images.githubusercontent.com/15221358/190184391-84ca1844-259a-4b3b-9c86-74adadbea7f1.png
[img-detail]: https://user-images.githubusercontent.com/15221358/190184600-ee8d3b39-077e-416a-8711-1b5fb01cf0b3.png

[tensorflow]: https://github.com/tensorflow/tensorflow
[Angular]: https://github.com/angular/angular  
[Flutter]: https://github.com/flutter/flutter 
[sos-dev]: https://sos.dev/ 
[deps-dev]: https://deps.dev/ 

### Why is this needed?

Considering how Kubernetes' project is relevant and how you already are awere of the "Security Best Practices", Scorecard Github Action would help you on knowing what would be the next steps to improve the project's security posture. 

Would you be interested in a PR which adds this Action? It can, optionally, also publishes the result to the OpenSSF REST API, which allows a [badge][badge] with the project's score to be added to its README.

In case of doubts or concerns you can try to check [Scorecards FAQ][FAQ]. Anyway, feel free to reach me out. 

[badge]: https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/
[FAQ]: https://github.com/ossf/scorecard/blob/main/docs/faq.md#frequently-asked-questions

**Comment by BenTheElder** [comment]
/sig architecture
(code organization subproject <=> supply chain security)
/sig security
(security)
/sig testing
(CI infra)

With my SIG Testing hat on: We do not currently use github actions in this repo.

We have our own CI system that amongst other things integrates with the merge robot and ensures the latest of (target branch, PR branch) are tested merged together, I'm not sure we're prepared to adopt actions in this repo at this time.

We don't generally place badges in the README.md either, though I'm not actually sure who would approve that. Maybe Contributor Experience or Docs?

We do currently have an OSSF badge, but rather indirectly via https://github.com/kubernetes/kubernetes/commit/da8218060a3ba926bf9cc9eb08034977dbe2e3be + rebranding of CII Best Practices, which was added by the CNCF.

**Comment by mrbobbytables** [comment]
/sig contributor-experience

I do appreciate the intent, but as a GitHub admin, I am a -1 on it if implemented as an action. While we're a bit more okay with enabling actions in other repos, k/k is the one where we definitely want to keep things limited to prow (our CI system).

I haven't looked at the other aspects of the scorecard, but would need to explore them more thoroughly to make the call on implementing as a potential prow job.

**Comment by joycebrum** [comment]
Sure take your time to think and look it more carefully and any doubts feel free to ask me. I understand if you really don't want any github actions maybe the scorecard action will not suit you right now.

**Comment by mrbobbytables** [comment]
Sorry for the late follow up.^^;;; We appreciate the intent, but we do not plan to enable GitHub actions for this repo. 

/close

**Comment by joycebrum** [comment]
Sure, thanks for considerate it and any future changes of mind let me know I'll me willing to help.
