### ISSUE TITLE
Terminate a Job from an external controller

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#113142]
### What would you like to be added?

/sig apps
/wg batch
/area batch

A mechanism to terminate a Job from an external controller, ensuring all the running pods are deleted.

Potentially, we could simply use a terminal Job condition as a signal.
This could be implemented by enhancing the orphan pod worker to issue pod Deletions when the owner Job is marked as finished. This behavior would be in addition to removing the finalizers when the pods terminate.

### Why is this needed?

Today, simply setting a terminal Job condition (Completed, Failed) might leave Pods running indefinitely (or until `ttlSecondsAfterFinished` is satisfied, if defined), if the controller doesn't have a chance to issue Pod deletions first.

**Comment by alculquicondor** [comment]
cc @soltysh 

@liggitt do you think this is a breaking change from an API perspective?

**Comment by liggitt** [comment]
triggering deletion behavior off of the presence of an existing condition on the Job API seems pretty surprising at first glance

**Comment by alculquicondor** [comment]
Once the job controller observes a terminal condition in the Job, it stops syncing it. So I was kind of thinking of this solution as a bug fix, although I'm not aware of any situation where the job controller would place a terminal condition before all the pods are finished (or without finalizers and deleted).

And then I wanted to tap into this behavior from kueue :sweat_smile: https://github.com/kubernetes-sigs/kueue/pull/410#discussion_r998002689

While I agree that it's not clean in general, kueue has it's own job controller that intends to collaborate with the k8s job controller.

**Comment by alculquicondor** [comment]
@mimowo pointed out that job termination could actually be triggered by setting a `FailureTarget` condition, introduced by kubernetes/enhancements#3329 as a temporary stage to avoid losing track of Pod failures.

**Comment by alculquicondor** [comment]
This use case is not about the job itself deciding that it needs to finish. It's about an external controller (like kueue) deciding that a Job should not continue running (because the quota was revoked or a higher priority job needs to start).

Freeing the resources can be achieved by setting suspend=True, but this leaves the Job in a limbo, where it's not running but it's also not finished, meaning that it wouldn't be picked up by ttlAfterFinish.

**Comment by sftim** [comment]
Thinking about this more, maybe it's simpler than I think. Kueue can use its own finalizer, that Job isn't aware of. The Job controller then watches for a `deletionTimestamp`. Once the deletion timestamp exists, the Job controller terminates any current Pods for the Job. Kueue can watch the status of the Job and remove the finalizer once the Job has either a `"Failed"` condition that is `true`, **or** a `"Completed"` condition that is true.

The Job remains in the API until the last finalizer is removed.

Would that work?

**Comment by liggitt** [comment]
> Thinking about this more, maybe it's simpler than I think. Kueue can use its own finalizer, that Job isn't aware of. The Job controller then watches for a `deletionTimestamp`. Once the deletion timestamp exists, the Job controller terminates any current Pods for the Job. Kueue can watch the status of the Job and remove the finalizer once the Job has either a `"Failed"` condition that is `true`, **or** a `"Completed"` condition that is true.

That makes sense to me (and I prefer a kueue use a kueue-specific finalizer over a shared "well-known" finalizer). Is this what the job controller does today (deletes child pods when the job has a non-nil deletionTimestamp)?

**Comment by sftim** [comment]
Deleting a Job with a finalizer set does _not_ seem to trigger Pod termination, so we'd need to bring in that behavior (feature gate? new API field?)

**Comment by sftim** [comment]
I noticed that the Job does make Pods with `ownerReferences`, and that those `ownerReferences` are set to [block deletion](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/#owner-references-in-object-specifications) of the owning Job.

**Comment by alculquicondor** [comment]
> Deleting a Job with a finalizer set does not seem to trigger Pod termination, so we'd need to bring in that behavior (feature gate? new API field?)

AFAIK, this is intentional, to support adoption: 1. delete the job with orphaning, 2. create a second job that selects the running pods.

Also, the problem with just "deleting" a job from kueue (even just setting the deletion timestamp) is that it bypasses the field `ttlSecondsAfterFinish` which is supposed to delete a Job after it is declared Finished.

**Comment by sftim** [comment]
1. Is the delayed cleanup from `ttlSecondsAfterFinish` needed for preemption by Kueue?
2. Kueue could choose to leave the finalizer in place for the duration of `ttlSecondsAfterFinish`, if that's important.

**Comment by sftim** [comment]
I believe that we can teach the Job controller to distinguish deletion with orphaning from deletion with a finalizer present. Just not sure if that needs its own KEP, feature gate, etc.

**Comment by alculquicondor** [comment]
> Is the delayed cleanup from ttlSecondsAfterFinish needed for preemption by Kueue?

It's not about kueue, but the user desire.

> Kueue could choose to leave the finalizer in place for the duration of ttlSecondsAfterFinish, if that's important.

Yeah... but that's duplicated code.

**Comment by sftim** [comment]
What's the user story for Kueue prempting a Job but with a grace period? Maybe we should capture that.
If we are happy with immediate preemption, we might be able to do that - including Pod cleanup - without any API change.

In general, it feels like we're looking for a mechanism to promptly delete in-progress Jobs, where that mechanism doesn't prevent us from immediately deleting a Job and then having a new different Job take over its running pods. Does that sound right?

**Comment by alculquicondor** [comment]
> What's the user story for Kueue prempting a Job but with a grace period? Maybe we should capture that.
If we are happy with immediate preemption, we might be able to do that - including Pod cleanup - without any API change.

We want to be able to preempt the job without removing it from apiserver. This is the same as how Jobs are not immediately removed when they finish, so users might be relying on this behavior.

> In general, it feels like we're looking for a mechanism to promptly delete in-progress Jobs, where that mechanism doesn't prevent us from immediately deleting a Job and then having a new different Job take over its running pods. Does that sound right?

That is correct.
