### ISSUE TITLE
Job image-validation-cos-e2e fails to create the cluster

### ISSUE THREAD

**Issue by Dragoncell** [kubernetes/kubernetes#113152]
### Which jobs are failing?

sig-node-containerd#image-validation-cos-e2e

### Which tests are failing?

[sig-network] DNS should work with the pod containing more than 6 DNS search paths and longer than 256 search list characters

### Since when has it been failing?

Not sure, dashboard showed it failed since 10/15

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#image-validation-cos-e2e

### Reason for failure (if possible)

```
{Oct 18 20:44:30.936: timed out while waiting for pod dns-5482/dns-test-7fdca0ba-4276-4198-ac27-2ada164a8d1e to be running failed test/e2e/network/dns_common.go:503
```

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
The test failure should be a mistake, because this job is not working ,it fails to create the cluster, 

```
I1109 11:05:34.501] Waiting for 5 ready nodes. 1 ready nodes, 1 registered. Retrying.
I1109 11:05:49.838] Detected 1 ready nodes, found 1 nodes out of expected 5. Your cluster may not be fully functional.
I1109 11:05:50.149] NAME                   STATUS                     ROLES    AGE   VERSION
I1109 11:05:50.149] bootstrap-e2e-master   Ready,SchedulingDisabled   <none>   24m   v1.26.0-alpha.3.461+18a78949bc7fa4
```

/edit Job image-validation-cos-e2e fails to create the cluster

/remove-sig network
/sig node

playing ping pong with Sergey 😄

**Comment by aojea** [comment]
/retitle Job image-validation-cos-e2e fails to create the cluster

**Comment by aojea** [comment]
maybe related https://github.com/kubernetes/kubernetes/issues/111876 ?
