### ISSUE TITLE
Scheduler framework metrics recorder go routine leak 

### ISSUE THREAD

**Issue by saumas** [kubernetes/kubernetes#113131]
### What happened?

When a scheduler framework constructor is called, it also always creates a metrics recorder. That metrics recorder immediately starts a go routine which never exits. Creating many scheduler framework instances creates many of such go routines which are never closed, eventually accumulating so much that they crash the process.

### What did you expect to happen?

The scheduler framework either does not start any go routines in the background or have the ability to stop them on demand.

This is a problem for applications that provide multi-tenant scheduling capabilities that are using the scheduler framework as a dependency. Because the creation of many scheduler frameworks means that eventually the go routines accumulate and crash the process. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up a `main.go` with a `pprof` server.
2. Create many (lets say 100) instances of the scheduler framework with the constructor `runtime.NewFramework()`.
3. Dump the profile of goroutines.

You will notice a lot of go routines originating from `runtime.(*bufferedMetricsRecorder).run (metrics_recorder.go:95) k8s.io/kubernetes/pkg/scheduler/framework/runtime`

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.12-gke.1200", GitCommit:"26604476cf3bcb64bec486e4b5880a5773a52e75", GitTreeState:"clean", BuildDate:"2022-07-29T09:23:06Z", GoVersion:"go1.16.15b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
All.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by saumas** [comment]
I have a fork with a fix. Waiting for triage.

**Comment by kerthcet** [comment]
Since you have a fix, can you point out explicitly where the problem is?

**Comment by saumas** [comment]
> Since you have a fix, can you point out explicitly where the problem is? @saumas

The problem is this go routine: https://github.com/kubernetes/kubernetes/blob/v1.22.0/pkg/scheduler/framework/runtime/metrics_recorder.go#L60

Because it never exits, creating many scheduler framework instances results in as many metrics recorder goroutines. There is an exit channel in that goroutine loop but it's not exported and only used in unit tests.

**Comment by kerthcet** [comment]
It's fixed in v1.25. see here https://github.com/kubernetes/kubernetes/pull/110148

**Comment by saumas** [comment]
Thanks, this looks exactly the correct fix. Will experiment.

**Comment by kerthcet** [comment]
I'd like to close this for it's fixed. Feel free to reopen it if you come across this problem again in v1.25.
/close
