### ISSUE TITLE
kubelet: memorymanager  static policy startup error

### ISSUE THREAD

**Issue by gaohuatao-1** [kubernetes/kubernetes#113130]
### What happened?

In our scenario, memoryManager are enabled. There are two numa nodes: node0 and node1 on the host.
The relevant parameter values are as follows：
memoryManagerPolicy: Static

Initially, no pods are running on this node  with two numa node,  220G memory per numa node. Follow the steps bellow to create and delete pods:
1. create guaranteed Pod1 with one container,  memory req and limit: 240G
2. create guaranteed Pod2 with one container, memory req and limit: 20G
At this point, machineState is as follows:
![image](https://user-images.githubusercontent.com/22569211/196362536-fdc55b24-2246-453b-aa1f-5a5d8533c720.png)

3. delete Pod2
At this point, machineState will be as follows:
![image](https://user-images.githubusercontent.com/22569211/196362769-283a35ff-b7eb-4ad9-8560-9ac35486dd70.png)

4. create guaranteed Pod3 with one container, memory req and limit: 10G
At this point, actual machineState is as follows:
![image](https://user-images.githubusercontent.com/22569211/196363134-fc5af58b-32a2-464a-9f6a-7f5ca557bdfd.png)

Now, restarting kubelet will fail. When kubelet restart, the expected machineState is as follows that is not equal to actual machineState above.
![image](https://user-images.githubusercontent.com/22569211/196363931-14f8bffa-cf79-48a3-9a0b-3e1b08358ee3.png)

### What did you expect to happen?

Pod creation and deletion order should not cause kubelet restart to fail.

### How can we reproduce it (as minimally and precisely as possible)?

See analysis above.

### Kubernetes version

v1.21 and above versions have this problem

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

thank you for beautifully crafted error report!!!

The k8s version you are running is old and out of support (kubelet v1.21.0). Would it be possible to check the behavior on latest version of k8s?

I know that there is an existing limitation around cpu manager (not sure about memory manager) that requires to handle checkpoint file before the restart. Not sure if this applies here. Please check on latest k8s and report back.

**Comment by gaohuatao-1** [comment]
Thanks for you reply. 

> /triage needs-information
> 
> thank you for beautifully crafted error report!!!
> 
> The k8s version you are running is old and out of support (kubelet v1.21.0). Would it be possible to check the behavior on latest version of k8s?
> 
> I know that there is an existing limitation around cpu manager (not sure about memory manager) that requires to handle checkpoint file before the restart. Not sure if this applies here. Please check on latest k8s and report back.

Thanks for your reply.   I have confirmed that the latest version kubelet has this problem, too.    
When kubelet start ,  static policy of memorymanager will validate the checkpoint file, the verification logic is as follows:
![image](https://user-images.githubusercontent.com/22569211/196850382-3f1fe0ee-fd60-4ebc-8975-60b016cf5feb.png)

b.NUMAAffinity on line 563 is in ascending order.  That is to say,   when the func validateState generates expectedMachineState,  it always allocate memory from the lowest numa node first, regardless of the current memory allocation of containers.  That will lead to that the actual machineState is not equal to the calculated one.

**Comment by gaohuatao-1** [comment]
Follow the above process, this problem is easy to reproduce. I reproduced the problem on version 1.25.3. 
There is logic flaws in memorymanager of kubelet, which causes the kubelet to fail to restart.
The result is as follows:
![image](https://user-images.githubusercontent.com/22569211/199643450-70f39047-0f08-4579-ac4c-7bd7381304b9.png)

**Comment by fromanirh** [comment]
/cc
I'm interested in this issue

**Comment by cynepco3hahue** [comment]
Hmm in general the memory manager should not allow allocating the same NUMA nodes for cross and single NUMA node allocations it is one of the limitations that we have, see https://kubernetes.io/blog/2021/08/11/kubernetes-1-22-feature-memory-manager-moves-to-beta/#single-vs-cross-numa-node-allocation. @gaohuatao-1 Which topology manager do you use?

**Comment by gaohuatao-1** [comment]
> Hmm in general the memory manager should not allow allocating the same NUMA nodes for cross and single NUMA node allocations it is one of the limitations that we have, see https://kubernetes.io/blog/2021/08/11/kubernetes-1-22-feature-memory-manager-moves-to-beta/#single-vs-cross-numa-node-allocation. @gaohuatao-1 Which topology manager do you use?

Thanks for your comment.
Using the default topology manager policy: none. In the above example, there is no pod with single NUMA node.

**Comment by cynepco3hahue** [comment]
I see, probably it will not be a problem when we will have both pods to be pinned to multiple NUMA nodes. And looks like you are correct under the comment https://github.com/kubernetes/kubernetes/issues/113130#issuecomment-1301607606, we should validate the state in descending order.
BTW kudos for the report :)

**Comment by donggangcj** [comment]
@gaohuatao-1  I had a similar problem and I submitted a PR to fix it, Can you help review the code?

**Comment by donggangcj** [comment]
For a node group, we cannot restore the free and reserved size of each node in the group after multiple allocations and releases of one resource.

**Comment by aimuz** [comment]
In the third step, is the ideal case that numa1 equals 220 and numa2 equals 20?

**Comment by gaohuatao-1** [comment]
> 1. nteed Pod1 with one container

Yes, you are right.

**Comment by gaohuatao-1** [comment]
> @gaohuatao-1 I had a similar problem and I submitted a PR to fix it, Can you help review the code?

Thanks for your work, I will review it later.

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle rotten

since we have an active PR I will move this to triaged

/triage accepted
