### ISSUE TITLE
e2e apps: deployment test not working as intended

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113259]
### What happened?

I started added missing error checks. When adding error checking to this call here, the test started to fail:
https://github.com/kubernetes/kubernetes/blob/e876d63ec2c9ae6b6af9318e909c21d16e90d94e/test/e2e/apps/deployment.go#L402

```
Deployment.apps "test-deployment" is invalid: status.availableReplicas: Invalid value: 2: cannot be greater than readyReplicas
```

### What did you expect to happen?

The test should have continued to work when checking the error.

### How can we reproduce it (as minimally and precisely as possible)?

```
_, err = dc.Resource(deploymentResource).Namespace(testNamespaceName).Patch(context.TODO, testDeploymentName, types.StrategicMergePatchType, []byte(deploymentStatusPatch), metav1.PatchOptions{}, "status")
framework.ExpectNoError(err)
```

### Kubernetes version

<details>
master
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/priority important-soon

@soltysh can you or someone in apps PTAL?
