### ISSUE TITLE
Update godoc on how to specify group/resources to be encrypted

### ISSUE THREAD

**Issue by ritazh** [kubernetes/kubernetes#113272]
### What happened?

Update the godoc on the encryption config API on how to specify group/resources to be encrypted
ref: https://github.com/kubernetes/kubernetes/pull/113015#discussion_r1002055172

### What did you expect to happen?

godoc has the details

### How can we reproduce it (as minimally and precisely as possible)?

 na

### Kubernetes version

na

### Cloud provider

na

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ritazh** [comment]
Thanks for volunteering for this @Cool-Coder174! LMK if you need any help with it.

**Comment by Cool-Coder174** [comment]
Just for clarification, I just need to add documentation on how to configure encryption on groups/resources?

**Comment by ritazh** [comment]
@Cool-Coder174 You can update https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#understanding-the-encryption-at-rest-configuration, add the following to EncryptionConfiguration similar to this test https://github.com/kubernetes/kubernetes/pull/113015/files#diff-cf16f4f8c11491813e64436319324e56ae67a2719d7850d3aceebac97df3899bR82-R95
```yaml
  - customresourcedefinitions.apiextensions.k8s.io
  - pandas.awesome.bears.com
```

**Comment by enj** [comment]
/assign @ritazh 
/unassign @Cool-Coder174 

Release v1.26 deadlines are here so we need to get this completed ASAP.

**Comment by Cool-Coder174** [comment]
I apologize for the slow actions. I know time and contributions are valuable. May I request a walk through. This is my first time ever contributing and I really want to learn. I have been reading some of the code base on my spare time.

**Comment by enj** [comment]
@Cool-Coder174 this feature is on the harder side of things to get started with.  Reading the blog post and the associated documentation is probably the best starting point:

https://kubernetes.io/blog/2022/09/09/kms-v2-improvements

**Comment by leonardpahlke** [comment]
@ritazh & @enj what is the status on this issue? 1.26 is coming up!
cc @hosseinsalahi
