### ISSUE TITLE
Daemonset controller should allow setting max pods creation rate

### ISSUE THREAD

**Issue by lianghao208** [kubernetes/kubernetes#113287]
### What would you like to be added?

an arg for controller manager to specify the max pods creation rate for daemonset controller:
```
# create 20 pods per second
--max-daemonset-pods-creation-rate=20
```

### Why is this needed?

Creating a daemonset in a huge cluster with over 4000 nodes will lead to over 4000 pods creation as the same time, which increases the risk for apiserver. A better approach is to limit the daemonset pods creation rate with custom strategies. 

BTW, I bring up this issue to discuss whether there are other approaches.

**Comment by lengrongfu** [comment]
@lianghao208 

Hi，has anyone handled the current issue? If not, I am willing to follow up.

**Comment by lianghao208** [comment]
@lengrongfu Thanks for catching this up, I think this issue is still in discusion stage, it needs more feedback from other members or maintainers. And you can also bring up your idea on this issue.
If more people can get invloved in this issue, we can decide which way to approach, then you are very welcome to  implement it.

**Comment by lengrongfu** [comment]
@lianghao208 The current Pod creation is batched, and there will not be many simultaneous creations; each batch will not exceed 250 at most.

https://github.com/kubernetes/kubernetes/blob/520e2c84b36a6538e319001ce2caea605f984db1/pkg/controller/daemon/daemon_controller.go#L965

**Comment by lianghao208** [comment]
@lengrongfu Got it, thanks for the helpful hints. :)
