### ISSUE TITLE
Log a warning when dropping unknown fields from loading an audit policy

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kubernetes#113266]
Currently the [audit policy decoder][1] silently drops unknown fields.

For backwards compatibility, we probably cannot fail on unknown fields, but it would be good to at least log a warning when they're encountered.

[1]: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/audit/policy/reader.go#L66

/sig api-machinery

**Comment by kidddddddddddddddddddddd** [comment]
I'm not familiar with apiserver, but this seems like a simple one.
/assign

**Comment by kidddddddddddddddddddddd** [comment]
How can we find unknown fields in the yaml file?
Currently I'm think of converting both the yaml file and the decoded Policy struct to two map[string]interface{}, and compare both map to find out which keys are in the yaml file but not in the decoded struct, is there any better solution?

**Comment by tallclair** [comment]
Courtesy @liggitt on slack: https://kubernetes.slack.com/archives/C0EG7JC6T/p1667321292172779

> yeah, you can enable strict decoding which will return a typed error on unknown fields
> https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/configfile.go#L43 uses that, constructed with `Codecs = serializer.NewCodecFactory(Scheme, serializer.EnableStrict)`
> kubelet does too, and warns/falls back to lenient decoding - > https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubeletconfig/util/codec/codec.go#L90-L118
> the kubelet one is a reasonable example to follow
