### ISSUE TITLE
e2e storage: "should provision storage with pvc data source in parallel" blocks, then ignores timeout error

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113268]
### What happened?

This line here blocks until the timeout occurs, then the test continues and succeeds:
https://github.com/kubernetes/kubernetes/blob/a497c56c33aca254e69513fcd46c0c76c8fadcab/test/e2e/storage/testsuites/provisioning.go#L500

### What did you expect to happen?

Either the thing that this line waits for must happen or that line should get removed.

### How can we reproduce it (as minimally and precisely as possible)?

Add `framework.ExpectNoError`.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mashetty330** [comment]
Hi @pohly I'm interested to work on this one.

I wanted to understand the issue more clearly.  Is the expectation for this line of code `e2evolume.WaitForVolumeAttachmentTerminated` is to wait until the VolumeAttachment to be terminated completely without a timeout?

**Comment by carlory** [comment]
/close 

It's done.

https://github.com/kubernetes/kubernetes/blob/3a4c35cc89c0ce132f8f5962ce4b9a48fae77873/test/e2e/storage/testsuites/provisioning.go#L570
