### ISSUE TITLE
Reflector retains initial list result for a long time

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#113305]
### What happened?

The result of initial list in Reflector is kept in the memory until the last element in the items list hasn't been changed. 

In practice this can be a long time, e.g. there can be some stable pod that are running for days, in configmaps there is a kube-root-ca.crt which stays there forever.

This problem is described here: https://go.dev/blog/slices-intro#a-possible-gotcha

IIUC this affects both:
* clients using informers/Reflectors
* kube-apiserver which is using the same Reflector to initialize watch cache

This means e.g. when all (but 1) elements are frequently updated, the memory usage is 2x the state size (the initial size + current size).

### What did you expect to happen?

When the objects are deleted from the cluster, the memory consumption of the Reflector drops.

### How can we reproduce it (as minimally and precisely as possible)?

* Create cluster with 1GB state of significant size (e.g. by creating 1000 configmaps of size 1M each)
* Start informer (e.g. I was using https://gist.github.com/mborsz/8964c84b298ee63c7153190d608a7464)
* Observe memory usage (it should be around ~1GB as expected)
  * Sample [pprof](https://user-images.githubusercontent.com/2559168/197553760-cfd8a8f0-0996-4ee7-8f8c-5ea72e06bf8d.png)
* Remove 99% of the state
* [issue] Observe memory usage (it stays around ~1GB, despite state taking ~10M)
  * Sample [pprof](https://user-images.githubusercontent.com/2559168/197555163-adff7e50-e0db-4c75-8397-929b08dc9c08.png)
* Recreate the state (with the same name)
* [issue] The memory usage grows to ~2G
  * Sample [pprof](https://user-images.githubusercontent.com/2559168/197557325-f3aef1f3-c003-4f17-83db-5aac06ab5643.png)

### Anything else we need to know?

This seems to be consequence of the:
* ConfigMapList using []ConfigMap type (not []*ConfigMap)
* Reflector taking pointer to those objects https://github.com/kubernetes/kubernetes/blob/fe9d04763b94366a7a80a1ef3d9f83337eac722e/staging/src/k8s.io/apimachinery/pkg/api/meta/help.go#L195-L200
* If any of the elements is in use, the entire Items is kept in the memory.

The naive fix would be to create a DeepCopy before storing data in Reflector, but this requires careful implementation to avoid increasing memory usage at the beginning (as we can easily have a list in Items and a deep copied list at the same time).

### Kubernetes version

<details>
1.26

</details>

### Cloud provider

<details>
all
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
xref discussion in https://github.com/kubernetes/kubernetes/pull/102565/files

**Comment by lavalamp** [comment]
Note that `[]runtime.Object` is essentially already a list of pointers, this can be addressed earlier just by making sure that the pointers don't all point into the same chunk of memory. No?

**Comment by mborsz** [comment]
@lavalamp, yes.

The problem is that it's allocated as a single chunk in ConfigMapList implementation and to split them to separate memory obejcts we need to either deepcopy them (proposed in https://github.com/kubernetes/kubernetes/pull/102565/files) or change the ConfigMapList to use pointer type for Items elements (I would assume it's infeasible, right?).

**Comment by lavalamp** [comment]
I wouldn't say it's 100% infeasible. The problem with any fix to this issue is that this is a rare-ish condition and fixing it will make the ordinary condition worse, either at runtime or in the codebase.

**Comment by mborsz** [comment]
> this is a rare-ish condition

IIUC this shouldn't be that rare: correct me if I'm wrong, but  for me it looks like any client (including kube-apiserver itself) using reflector, watching resource type of high cardinality will keep the initial state forever (assuming that there is some object that isn't changing [*])

[*] It's not clear how often is the not changing object condition, but it shouldn't be very hard for resources like pods or configmaps, secrets which tends to be large in size.

> the ordinary condition worse, (...) in the codebase.

Are you referring to the pointer Items solution? Can you help me understanding why it's worse then the current state? Is it a cost of migration (which I assume can be huge) or something else?

**Comment by wojtek-t** [comment]
@deads2k - FYI

**Comment by lavalamp** [comment]
> any client (including kube-apiserver itself) using reflector, watching resource type of high cardinality will keep the initial state forever

But making a deep copy of everything doubles up initial memory usage all the time for everyone.

**Comment by sxllwx** [comment]
> > any client (including kube-apiserver itself) using reflector, watching resource type of high cardinality will keep the initial state forever
> 
> But making a deep copy of everything doubles up initial memory usage all the time for everyone.


emmm... Is such that. This modification will cause a memory spike (as you said, double the amount of memory required for initialization), but I think the cost is worth it. As the running time increases, only real-time objects remain in memory, which has obvious advantages when the number of objects is large.

**Comment by lavalamp** [comment]
I'm reasonably sure many large clusters wouldn't be able to survive double the memory spike on startup.

**Comment by sxllwx** [comment]
Hi everyone, I submitted a PR #113362  to try and fix the issue. The core is to make a shallow copy through (reflect.New and reflect.Value.Set) instead of DeepCopy (to avoid the double memory usage problem mentioned by @lavalamp)

Several modifications are included:

- Faster `ExtractList`, implemented by comparing reflect.Type directly, not through `switch item := raw.Interface().(type)` (avoid a shallow copy)
- Added `ExtractListWithAlloc` to help gc by a shallow copy to avoid dependencies between objects and the Items array.

ExtractList benchmark results (xxxFixed represents the new version):

```bash
goos: linux
goarch: amd64
pkg: k8s.io/apimachinery/pkg/api/meta
cpu: AMD EPYC 7K62 48-Core Processor
BenchmarkExtractSampleList
BenchmarkExtractSampleList-16               	    1233	    956172 ns/op	 1278109 B/op	    6751 allocs/op
BenchmarkExtractSampleListFixed
BenchmarkExtractSampleListFixed-16          	    1632	    734879 ns/op	  989714 B/op	    5750 allocs/op
BenchmarkExtractFooList
BenchmarkExtractFooList-16                  	    1328	    993050 ns/op	 1270171 B/op	    6750 allocs/op
BenchmarkExtractFooListFixed
BenchmarkExtractFooListFixed-16             	    1579	    766523 ns/op	  981768 B/op	    5749 allocs/op
BenchmarkExtractRawExtensionList
BenchmarkExtractRawExtensionList-16         	    1539	    756601 ns/op	 1080188 B/op	    7749 allocs/op
BenchmarkExtractRawExtensionListFixed
BenchmarkExtractRawExtensionListFixed-16    	    1560	    763697 ns/op	 1080198 B/op	    7749 allocs/op
```

Benchmark results of reflector.list using `ExtractList` and `ExtractListWithAlloc`:

```bash
goos: linux
goarch: amd64
pkg: k8s.io/client-go/tools/cache
cpu: AMD EPYC 7K62 48-Core Processor
BenchmarkExtractPodList
BenchmarkExtractPodList-16             	     134	   8889413 ns/op	10815542 B/op	   42500 allocs/op
BenchmarkExtractPodListWithAlloc
BenchmarkExtractPodListWithAlloc-16    	     123	   9669507 ns/op	11839795 B/op	   43500 allocs/op
```

Looking forward to your suggestions or comments.
