### ISSUE TITLE
Test images: sample-apiserver E2E image fails to build

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#113302]
### What happened?

``go get`` for installing golang binaries has been deprecated in Go 1.17 in favor of ``go install``. Starting with Go 1.19, we can no longer install binaries through ``go get``. [1]

We've recently switched to Go 1.19, and because of this, the ``sample-apiserver`` E2E image has started failing to build recently [2] with the error:

```
 go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'. 
```

Using ``go install`` for ``k8s.io/sample-apiserver~v0.17.0`` directly doesn't work either:

```
go install k8s.io/sample-apiserver@v0.17.0
go: downloading k8s.io/sample-apiserver v0.17.0
go: k8s.io/sample-apiserver@v0.17.0 (in k8s.io/sample-apiserver@v0.17.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.
```

[1] https://go.dev/doc/go-get-install-deprecation
[2] https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-sample-apiserver-test-images/1580625892458106880

### What did you expect to happen?

The image should be buildable.

### How can we reproduce it (as minimally and precisely as possible)?

```
cd kubernetes/test/images
make all-push WHAT=sample-apiserver
```

### Anything else we need to know?

/sig testing
/priority important-soon

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@claudiubelu please see the PR and lgtm if it works right for you!
