### ISSUE TITLE
Incorrect and misleading error reporting: failed to initialize top level QOS containers: root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by exander77** [kubernetes/kubernetes#113322]
### What happened?

When doing validation, kubernetes doesn't actually report the issue with the cgroup kupepods, instead they issue an error that cgroup kubepods doesn't exist at all. This is related to opencontainers not checking if controllers got properly set:
https://github.com/opencontainers/runc/issues/3647

So it goes like this:
Kubernetes use opencontainers to set up cgroup kubepods.
Opencontainers doesn't check if anything actually succeeded.
Then later Kubernetes check if everything is configured correctly during validation and when anything is even slightly out of the ordinary, it shreds any information what is wrong, and instead it reports that kubepods doesn't exist at all.

### What did you expect to happen?

I would assume software not lying. When kubepods exist, the Kubernetes should not lie that it doesn't and if it knows what it is missing, it should report it and not silently throw it away.

### How can we reproduce it (as minimally and precisely as possible)?

Fail to set some cgroup controller, like cpuset.

### Kubernetes version

Any

### Cloud provider

Unrelated

### OS version

Unrelated

### Install tools

Unrelated

### Container runtime (CRI) and version (if applicable)

Unrelated

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Unrelated

**Comment by SergeyKanzhelev** [comment]
@exander77 is there a way it can be reproduced? Is the only problem that the log message is incorrect or there any other side effects?

/triage needs-information

**Comment by exander77** [comment]
> @exander77 is there a way it can be reproduced? Is the only problem that the log message is incorrect or there any other side effects?
> 
> /triage needs-information

Reproduce it? There is no expectation that it could behave otherwise. This is not bug per se. The error handling there is just not implemented at all. Any and all inconsistencies within cgroup leads to this error.

When container manager is started, it calls `Exists` on cgroup manager:

```go
func (m *qosContainerManagerImpl) Start(getNodeAllocatable func() v1.ResourceList, activePods ActivePodsFunc) error {
    cm := m.cgroupManager
    rootContainer := m.cgroupRoot
    if !cm.Exists(rootContainer) {
        return fmt.Errorf("root container %v doesn't exist", rootContainer)
    }
    ...
```

So the presence of `kubepods` is tested by `Exists`:
```go
// Exists checks if all subsystem cgroups already exist
func (m *cgroupManagerImpl) Exists(name CgroupName) bool {
    return m.Validate(name) == nil
}
```
This function calls `Validate` that nicely checks everything, but above implementation of `Exists` eats all the errors and returns just true/false:
```go
// Validate checks if all subsystem cgroups already exist
func (m *cgroupManagerImpl) Validate(name CgroupName) error {
    if libcontainercgroups.IsCgroup2UnifiedMode() {
        cgroupPath := m.buildCgroupUnifiedPath(name)
        neededControllers := getSupportedUnifiedControllers()
        enabledControllers, err := readUnifiedControllers(cgroupPath)
        if err != nil {
            return fmt.Errorf("could not read controllers for cgroup %q: %w", name, err)
        }
        difference := neededControllers.Difference(enabledControllers)
        if difference.Len() > 0 {
            return fmt.Errorf("cgroup %q has some missing controllers: %v", name, strings.Join(difference.List(), ", "))
        }
        return nil // valid V2 cgroup
    }

    // Get map of all cgroup paths on the system for the particular cgroup
    cgroupPaths := m.buildCgroupPaths(name)

    // the presence of alternative control groups not known to runc confuses
    // the kubelet existence checks.
    // ideally, we would have a mechanism in runc to support Exists() logic
    // scoped to the set control groups it understands.  this is being discussed
    // in https://github.com/opencontainers/runc/issues/1440
    // once resolved, we can remove this code.
    allowlistControllers := sets.NewString("cpu", "cpuacct", "cpuset", "memory", "systemd", "pids")

    if _, ok := m.subsystems.MountPoints["hugetlb"]; ok {
        allowlistControllers.Insert("hugetlb")
    }
    var missingPaths []string
    // If even one cgroup path doesn't exist, then the cgroup doesn't exist.
    for controller, path := range cgroupPaths {
        // ignore mounts we don't care about
        if !allowlistControllers.Has(controller) {
            continue
        }
        if !libcontainercgroups.PathExists(path) {
            missingPaths = append(missingPaths, path)
        }
    }

    if len(missingPaths) > 0 {
        return fmt.Errorf("cgroup %q has some missing paths: %v", name, strings.Join(missingPaths, ", "))
    }

    return nil // valid V1 cgroup
}
```

You can create this bug easily by deactivating cgroup controller that is needed (like cpuset) after kubepod cgroup is created and before it is validated.
