### ISSUE TITLE
[failing-test] ci-kubernetes-e2e-gce-scale-correctness

### ISSUE THREAD

**Issue by Namanl2001** [kubernetes/kubernetes#113327]
### Which jobs are failing?

sig-release-master-informing#ci-kubernetes-e2e-gce-scale-correctness

### Which tests are failing?

Kubernetes e2e suite: [SynchronizedBeforeSuite]

### Since when has it been failing?

10/22

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Anything else we need to know?

ref: https://github.com/kubernetes/kubernetes/issues/111111

### Relevant SIG(s)

/sig scalability
cc @kubernetes/ci-signal

**Comment by Nivedita-coder** [comment]
Job is passing :)
/close
