### ISSUE TITLE
PodSpec comment on ServiceAccountName references non-existent markdown URL

### ISSUE THREAD

**Issue by ae6rt** [kubernetes/kubernetes#11332]
This field

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/v1/types.go#L879

is commented and that comment contains a reference to a markdown file service_accounts.md that no longer exists in docs/.  The file appears to live in docs/design/ now.

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by chenopis** [comment]
This should be closed.
