### ISSUE TITLE
A better way to manage secrets: reference an external secret defined in the cloud provider environment

### ISSUE THREAD

**Issue by collimarco** [kubernetes/kubernetes#113396]
### What would you like to be added?

Although there are various solutions to manage secrets in K8s, I think that they are all unnecessary complex and they are not following the right approach.

I propose this simple, better alternative:

```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: default
  secretid: id-of-the-secret
```

The important part here is the `secretid`:

- this is simply **an ID / external reference to a secret defined using the dashboard** (e.g. DigitalOcean control panel, Google Cloud Secret Manager, AWS Secrets Manager, etc.)
- **it is not necessary to upload a master secret to the cluster**, because the secrets and the K8s nodes are in the same account on the same cloud provider

This would ensure a **better separation** of concerns: the definition of the infrastructure can stay in Git repositories,  clean and simple, while the secrets stay in the cloud environment. It would less error-prone than complex solutions like Sealed Secrets, HashiCorp Vault and other solutions that need many steps and need a master secrets inside the cluster.

For Pushpad, which uses DigitalOcean K8s, we already use this approach for the SSL certificate and works great: we upload the SSL certificate and private key from the DigitalOcean dashboard and then we simply reference it in the YML files using an annotation (`service.beta.kubernetes.io/do-loadbalancer-certificate-id: "1234-5678-9012-3456"`). It would be interesting to have this approach not only for an SSL certificate, but for any secret. 

### Why is this needed?

- simple
- more secure
- less risks to commit a unsealed secret to the Git repository
- better separation between configuration and secrets
- no need to manually upload master secrets to the cluster

**Comment by enj** [comment]
[secrets-store-csi-driver](https://github.com/kubernetes-sigs/secrets-store-csi-driver) is the recommended approach from SIG Auth for consuming secrets from external providers.  In particular, using the CSI interface enables one to avoid using Kubernetes secrets altogether.  Other projects exist to sync external secrets into Kube secrets.  We are moving away from any cloud provider specific code in-tree, so any mechanism for syncing secrets would look no different than the existing external solutions.  I am going to close this as I do not see us making any changes in this area.

/sig auth
/triage accepted
/close
