### ISSUE TITLE
kubectl get logs <podname> throws error

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/kubernetes#11342]
Running `kubectl get logs <podname>` results in an error: 

    Error from server: Get https://gke-cyrus-cluster-us-central1-a-CENSORED-CENSORED-node-CENSORED:10250/containerLogs/default/<podname>-CENSORED/<podname>?follow=true: use of closed network connection

The output of `kubectl version`:

    Client Version: version.Info{Major:"0", Minor:"20", GitVersion:"v0.20.2", GitCommit:"323fde5bc5c45e30bbb5451ccf5c1ff01b0717f7", GitTreeState:"clean"}
    Server Version: version.Info{Major:"0", Minor:"19", GitVersion:"v0.19.3", GitCommit:"3103c8ca0f24514bc39b6e2b7d909bbf46af8d11", GitTreeState:"clean"}

Kubectl is installed via the `gcloud` suite, and I just updated it a few minutes ago. This issue appeared briefly before the same way--an update. An update (the next day if I remember correctly) fixed it before.

**Comment by pnovotnak** [comment]
Also, sometimes it throws `Unable to connect to the server: EOF`

**Comment by roberthbailey** [comment]
Can you run `grep "Accepted publickey for gke-41c25b6ea59e0d7da1d0 from" /var/log/auth.log` on one of your nodes to see if there are any entries? The master is having issues creating an ssh tunnel into your nodes (kubectl logs uses the proxy running on the master).

**Comment by pnovotnak** [comment]
The cluster was not working very well and unfortunately, about 120 seconds ago I deleted it :(

Will try this if/when it happens again.


Thanks!
-Peter

**Comment by roberthbailey** [comment]
Was anything else not working. Looking at the master logs (before the cluster was deleted) it appeared that the proxy on the master was in an unhealthy state, but I'm curious if you saw anything other than the proxied calls (which include kubectl logs and kubectl exec) failing with this cluster.

**Comment by pnovotnak** [comment]
I believe you are correct. This failure occurred 7 days after cluster
creation.

What tests should I run if this happens again? Keep in mind this is running
on Container Engine.

Seems to be pretty reproducible, and I'll be running my clusters with
real-world workloads until they fail.

-Peter

**Comment by Hokutosei** [comment]
Greetings,

hi did you solve your problem? I am experiencing the same problem now

```
➜  ~  kubectl logs -f pod
Error from server: Get https://host?follow=true: use of closed network connection
```

**Comment by mbforbes** [comment]
Bump +cc @jlowdermilk @brendandburns

**Comment by jlowdermilk** [comment]
I think we can close this, unless someone has a more recent repro.

**Comment by mbforbes** [comment]
@Hokutosei are you still seeing this? Can you give any more info, if so?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

**Comment by limbuu** [comment]
I am having same issue.I have been using kubernetes for more than a year. I recently ran into a problem i had never seen. I have stage and production cluster running in GKE. While i can access anything in stage cluster, i am having problem while using command : kubectl exec -it [podname] bash and kubectl logs -f [podname]. It says  Error from server: error dialing backend: No SSH tunnels currently open. Were the targets able to accept an ssh-key for user "gke-*************"?. I waited couple of days hoping it was small glitch and would be solved by GKE, but i am still getting the problem. Anybody here please help me. I am using 1.11.8-gke.6 kubernetes version.
