### ISSUE TITLE
Test of sig-node-containerd#e2e-cos-device-plugin-gpu are flaky

### ISSUE THREAD

**Issue by CoderSherlock** [kubernetes/kubernetes#113480]
### Which jobs are flaking?

sig-node-containerd#e2e-cos-device-plugin-gpu

### Which tests are flaking?

In the most recent test, the whole test process was failing in running`[It] [sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests`.

### Since when has it been flaking?

Not sure, the oldest failing we can see started on Oct 16th.

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#e2e-cos-device-plugin-gpu

### Reason for failure (if possible)

Connect refused are the most occurrence error message.

Most recent error msg:
```
error while waiting for pod device-plugin-gpus-7409/nvidia-gpu-a758050d-c941-4374-afca-5e2293d2b120 to be Succeeded or Failed: Get \"https://35.247.82.233/api/v1/namespaces/device-plugin-gpus-7409/pods/nvidia-gpu-a758050d-c941-4374-afca-5e2293d2b120\": dial tcp 35.247.82.233:443: connect: connection refused
```

### Relevant SIG(s)

/sig node

**Comment by klueska** [comment]
These cos-based GPU tests are maintained by Google GKE, not NVIDIA

/cc elfinhe
to assign the right person

**Comment by klueska** [comment]
These cos-based GPU tests are maintained by Google GKE, not NVIDIA

/cc @grac3gao
to assign the right person
