### ISSUE TITLE
Installed k3s on worker and node, node NotReady

### ISSUE THREAD

**Issue by linux-bear** [kubernetes/kubernetes#113468]
### What happened?

I'm trying to install k3s on a master and a worker node, both running Ubuntu 22.04. The master installs no problem but the worker hangs on `[INFO]  systemd: Starting k3s-agent`. The log files on the worker say:

```Oct 27 14:22:32 myworker k3s[69044]: E1027 14:22:32.202326   69044 webhook.go:154] Failed to make webhook authenticator request: Post "https://127.0.0.1:6444/apis/authentic>
Oct 27 14:22:32 myworker k3s[69044]: E1027 14:22:32.202428   69044 server.go:291] "Unable to authenticate the request due to an error" err="Post \"https://127.0.0.1:6444/ap>
Oct 27 14:22:32 myworker k3s[69044]: E1027 14:22:32.230764   69044 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "https://127.0.0.1:6444/ap>
Oct 27 14:22:32 myworker k3s[69044]: E1027 14:22:32.288643   69044 kubelet.go:2448] "Error getting node" err="node \"myworker\" not found"
```

The master can see the worker node but it says "NotReady":

``` 
NAME           STATUS     ROLES                  AGE   VERSION
mymaster    Ready      control-plane,master   20m   v1.25.3+k3s1
myworker    NotReady   <none>                 11m   v1.25.3+k3s1
```
This is the output from ```kubectl describes nodes myWorker```:
```
Name:               myWorker
Roles:              <none>
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=myWorker
                    kubernetes.io/os=linux
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 28 Oct 2022 11:05:18 +0000
Taints:             node.kubernetes.io/unreachable:NoExecute
                    node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:              Failed to get lease: leases.coordination.k8s.io "myWorker" not found
```

### What did you expect to happen?

The node should have joined and set itself to "Ready".

### How can we reproduce it (as minimally and precisely as possible)?

Master node, I've tried with these three commands before installing/reinstalled the node:
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--write-kubeconfig ~/.kube/config --write-kubeconfig-mode 666 --tls-san <master-ip> --node-external-ip=<master-ip>" sh -
```
```
curl -sSL https://get.k3s.io | INSTALL_K3S_EXEC="server --docker --debug --node-external-ip=<master-ip> --advertise-address=<master-ip>" sh -
```
```
curl -sSL https://get.k3s.io | INSTALL_K3S_EXEC='server --docker' sh -
```
I've opened ports:
```
sudo ufw allow 443/tcp
sudo ufw allow 6443/tcp
```
tried creating directory.kube/config on master node, and copying k3s.yaml over to it and change user, chmod 666. Also tried not doing that.
`sudo cat /etc/rancher/k3s/k3s.yaml > /home/ubuntu/.kube/config/k3sconfig.yaml`

got token from `cat /var/lib/rancher/k3s/server/node-token`

set up worker:
```curl -sfL http://get.k3s.io | K3S_URL=https://192.168.196.4:6443 K3S_TOKEN=${TOKEN} sh -s - --docker```
I've tried with and without the `--docker` flag.

I've tried copying k3s.yaml over to the worker node at `~/.kube/config/k3s.yaml` and also `k3sconfig.yaml`

I tried changing the server ip from `127.0.0.1` to the master ip in k3s.yaml before copying it over to the worker:
    ```server: https://192.168.196.4:6443```

### Anything else we need to know?

The servers are all on the same subnet, bare-metal. This should just work but it doesn't. I've tried 3 different servers as nodes, all with the same fault. I'm wondering if it's something about the subnet but then it's the worker that seems the have the fault, rather than a communication issue.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None - bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

$ uname -a
Linux myMaster 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

https://github.com/kubernetes/kubernetes/issues/113468#tasklist-block-b1ba934a-6eb9-438e-99bf-f7926d7e7274

**Comment by aojea** [comment]
you should report this in the k3s project, if there is a bug in kubernetes we can always reopen with more accurate information

/close
