### ISSUE TITLE
API doc should use the field name in description

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#113438]
### What happened?

Currently we have inconsistency in most of the API where the field name should be used in description so the generated docs match the API fields people actually set. 
e.g. 
https://github.com/kubernetes/kubernetes/blob/367f01f62d1a6ca149c317f97a958dd5c6e74af1/staging/src/k8s.io/api/admission/v1/types.go#L41
`uid` should be used instead of `UID` so it's shown properly in generated docs.

### What did you expect to happen?

Inside https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json description, the field name should reflect the real field name people actually set.

The work could be divided based on API group. 

### Steps

1. Modify the godoc in the versioned types.go file(s) for the appropriate API group to use the JSON name when referring to API fields. Create a commit with these changes.
2. Run `make update` to regenerate API documentation files (this will generate updates to proto files, generated go files, and openapi json files) (or open a PR with just the types.go changes and update the generated files using the instructions at https://www.kubernetes.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/#using-the-short-term-solution). Create a second commit with these changes.

### API groups

- admissionregistration.k8s.io | v1 - @bhavyastar
- apiextensions.k8s.io | v1 - @ShivamTyagi12345 (located within staging/src/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v*/types*.go)
- apiregistration.k8s.io | v1 - @ShivamTyagi12345 (located within staging/src/k8s.io/kube-aggregator/pkg/apis/apiregistration/v*/types.go) - https://github.com/kubernetes/kubernetes/pull/113603
- apps | v1 - @Cool-Coder174
- authentication.k8s.io | v1 - @chuyang-deng
- authorization.k8s.io | v1 - @chuyang-deng
- autoscaling | v1, v2, v2beta2 - @rayowang
- batch | v1 - @ztzxt - https://github.com/kubernetes/kubernetes/pull/113570
- certificates.k8s.io | v1 - @SuperAayush
- coordination.k8s.io | v1 - @chiukapoor - https://github.com/kubernetes/kubernetes/pull/113876
- core | v1 - @Cool-Coder174
- discovery.k8s.io | v1, v1beta1 - @ravi-nal - https://github.com/kubernetes/kubernetes/pull/113894
- events.k8s.io | v1 - @SuperAayush
- flowcontrol.apiserver.k8s.io | v1beta2, v1beta1 - @Rishit-dagli 
- internal.apiserver.k8s.io | v1alpha1 - @Rishit-dagli 
- networking.k8s.io | v1, v1alpha1 - @ruquanzhao - https://github.com/kubernetes/kubernetes/pull/114063
- node.k8s.io | v1 - @ruquanzhao
- policy | v1 - @HarshalNeelkamal
- rbac.authorization.k8s.io | v1 - @HarshalNeelkamal
- scheduling.k8s.io | v1 - @chiukapoor - https://github.com/kubernetes/kubernetes/pull/113875
- storage.k8s.io | v1, v1beta1 - @ravi-nal - https://github.com/kubernetes/kubernetes/pull/113894

/good-first-issue

/assign @chuyang-deng
Since Chuyang showed interests in the work.
Please feel free to claim the work if interested and coordinate in this issue.

### How can we reproduce it (as minimally and precisely as possible)?

Look at the API doc.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chuyang-deng** [comment]
Thank you Cici, I'll get started with 2  API groups:
authentication.k8s.io | v1
authorization.k8s.io   | v1

**Comment by ShivamTyagi12345** [comment]
I would like to work on this. 
 /assign

**Comment by liggitt** [comment]
@ShivamTyagi12345 thanks for the interest... to help keep changes relatively contained/local, can you indicate 1-2 API groups listed in the description you'll start with?

**Comment by Rishit-dagli** [comment]
I would love to take up:

- flowcontrol.apiserver.k8s.io
- internal.apiserver.k8s.io

**Comment by ShivamTyagi12345** [comment]
> * apiextensions.k8s.io | v1
> * [ ]  apiregistration.k8s.io | v1

I would work on 
- apiextensions.k8s.io | v1
- apiregistration.k8s.io | v1

**Comment by ruquanzhao** [comment]
I would love to take up:
- networking.k8s.io | v1, v1alpha1
- node.k8s.io | v1

**Comment by ShivamTyagi12345** [comment]
Do you happen to have a simpler explanation of what this task is exactly asking for?
Where can i find the API doc ?
From my understanding , we are supposed to change  [this file](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json ) , but i cant seem to understand what sort of changes needs to be done .

**Comment by HarshalNeelkamal** [comment]
I can take up:
- policy | v1
- rbac.authorization.k8s.io | v1

**Comment by ztzxt** [comment]
I'd love to take up batch | v1

**Comment by cici37** [comment]
/unassign
Sorry I thought help is needed for tracking. Since the description is updated properly, I will unassign myself. Thank you!

**Comment by ShivamTyagi12345** [comment]
> I added a `Steps` heading to the description with the process to follow

Hey @liggitt thanks for adding the steps ! I now understand that we have to modify types.go file(s) for the API groups.
However can you please help me out , how can I find this file for apiextensions.k8s.io | v1 as I dont see any folder with a name of apiextensions under kubernetes/staging/src/k8s.io/api

**Comment by liggitt** [comment]
updated the description with the locations of those APIs

**Comment by liggitt** [comment]
For the folks that have jumped in to help, thanks! Given where we are relative to code freeze next week, I would recommend waiting until code freeze to start this work, plan on having the reviews done during code freeze, and merge early in the 1.27 time frame.

**Comment by C-Society** [comment]
I'd like to work on coordination.k8s.io | v1

**Comment by ravi-nal** [comment]
I'd like to work on

- discovery.k8s.io | v1
- storage.k8s.io | v1, v1beta1

**Comment by Cool-Coder174** [comment]
I'd like to work on: 

- apps | v1
- core | v1

**Comment by bhavyastar** [comment]
I would love to take:

admissionregistration.k8s.io | v1

**Comment by ShivamTyagi12345** [comment]
Hey @liggitt  , Does `make update` take generally takes a long time to execute ? I am on Ubuntu 22.10 and the terminal keeps freezing at this ,
![image](https://user-images.githubusercontent.com/60812924/199796957-632b863f-2f74-4061-af0a-9a7be9b6425e.png)

**Comment by liggitt** [comment]
it does take a while, you can run with SILENT=false to see more details while it's running. I think @dims might have also set up a CI job that will run this and capture output you can download and apply to a PR instead of running `make update` yourself...

**Comment by dims** [comment]
@ShivamTyagi12345 see https://www.kubernetes.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/

you need to comment with `/test pull-kubernetes-update` to get that CI job to run here

**Comment by rayowang** [comment]
I would love to work on:

- autoscaling | v1, v2, v2beta2

**Comment by liggitt** [comment]
Thanks, everyone! It looks like all the API groups have a volunteer associated, so I dropped the help wanted label.

After everything targeting 1.26 has merged for code freeze (probably next ~Thursday), feel free to sync to latest `master` and start opening the PRs for review

**Comment by tengqm** [comment]
oh gosh, this is eventually happening!!!

**Comment by chiukapoor** [comment]
Hello @cici37 and @liggitt, Hope you are doing well!

May you please review the PR https://github.com/kubernetes/kubernetes/pull/113875, https://github.com/kubernetes/kubernetes/pull/113876 and let me know your feedback

**Comment by chiukapoor** [comment]
> Hello @cici37 and @liggitt, Hope you are doing well!
> 
> May you please review the PR #113875, #113876 and let me know your feedback

cc: @jimangel

**Comment by Cool-Coder174** [comment]
Could someone please walk me through the process! It is my first time contributing and I would like to see how the process is done!

**Comment by chuyang-deng** [comment]
Hi @Cool-Coder174 , Jordan has updated the steps in the description for this specific task, but being a first time contributor myself, here's what I did/will do:

1. fork the repo to your own github, clone it to your local development environment
2. setup the development described here: https://github.com/kubernetes/kubernetes#to-start-developing-k8s
3. make your changes - update the "types.go" documentation according to this issue's description
4. run `make update` to regenerate API documentation files, or use the workaround documented here: https://www.kubernetes.dev/blog/2022/03/15/k8s-triage-bot-helper-ci-job/#using-the-short-term-solution (this step is necessary otherwise the CI will fail)
5. push the change to your own fork
6. raise a PR against this repo

**Comment by ruquanzhao** [comment]
Hi, @liggitt 
Hoping to get your advice on PRs: #114063 and #114065

**Comment by SuperAayush** [comment]
<img width="1281" alt="Screenshot 2022-11-26 at 11 59 09 PM" src="https://user-images.githubusercontent.com/78820926/204103739-18febff9-72e0-4b19-822a-e8d1648199f0.png">
Can anyone help me solve these errors?
I have tried searching from my own but did not get a proper result.

I get these after running `make quick-release`

**Comment by liggitt** [comment]
make sure you've fetched tags from the upstream kubernetes repo (something like `git remote add upstream git@github.com:kubernetes/kubernetes.git` and then `git fetch upstream --tags` will work)

**Comment by chiukapoor** [comment]
/reopen

Not all subtasks are completed

**Comment by liggitt** [comment]
master branch is open for 1.27, and velocity is slow during the holidays, so now would be a good time to start the remaining items

**Comment by SuperAayush** [comment]
I am getting this error while running `make update`, can anyone help please 🥲 .
<img width="1440" alt="Screenshot 2023-01-03 at 4 07 53 PM" src="https://user-images.githubusercontent.com/78820926/210341380-1bfe4b81-7899-4455-a2db-274303f99476.png">

**Comment by SuperAayush** [comment]
/reopen

Not all the tasks are completed

**Comment by haoruan** [comment]
A linter #114948 has been added, it checks back-tick quoted names and needs a manual pass to add back-ticks to docs https://github.com/kubernetes/kubernetes/pull/114948#discussion_r1069692830, do we need a followup ticket? @cici37
