### ISSUE TITLE
Rolling Update to New "latest" Image

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#11348]
Is it possible to do a rolling update where kubernetes pulls and uses the newest Docker image with the "latest" tag rather than having to change the replication controller spec to use version 2.0.0 instead of 1.2.3 for example?

**Comment by bgrant0607** [comment]
Using "latest" leads to unpredictable behavior. Any pods that happen to be created for any reason (node death, scaling, rolling update of some other field) after the latest tag is retargeted to a new version would pull that new version. Is that what you want? (Well, there's also the issue of whether the imagePullPolicy may interfere.)

Or, would you like "latest" to be automatically translated to a tag referring to the current version? That was proposed in #1697. The v2 registry API should make that more feasible.

**Comment by bgrant0607** [comment]
cc @nikhiljindal @ironcladlou
