### ISSUE TITLE
How to change the clusterName of a running cluster

### ISSUE THREAD

**Issue by devopslyf** [kubernetes/kubernetes#113400]
How to change the clusterName of a running cluster

**Comment by aojea** [comment]
which `clusterName` ?

the one in metadata has been removed https://github.com/kubernetes/kubernetes/pull/109602

**Comment by ADITYADAS1999** [comment]
> How to change the clusterName of a running cluster

if use kubeadm that allow you to change a cluster name before an "init" stage basically.

**Comment by devopslyf** [comment]
Can it be modified after the "init" stage?

**Comment by aojea** [comment]
Can you define first what do you refer by clusterName?

**Comment by neolit123** [comment]
/kind support
/close

support questions can go in the support channels - e.g. #kubernetes-users on k8s slack.
