### ISSUE TITLE
[Failing Test] kind-master-parallel

### ISSUE THREAD

**Issue by bharitwal** [kubernetes/kubernetes#113551]
### Which jobs are failing?

release-master-blocking:

- kind-master-parallel

### Which tests are failing?

ci-kubernetes-kind-e2e-parallel.Overall

### Since when has it been failing?

2nd November 2022

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel

### Reason for failure (if possible)

Kubernetes e2e suite: [It] [sig-node] Pods Extended Pod Container Status should never report container start when an init container fails | 2m58s
-- | --
{Nov  2 15:34:37.198: 1 errors: pod pod-terminate-status-1-8 on node kind-worker container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 15:33:13 +0000 UTC reason=StartError message=failed to create containerd task: failed to create shim task: context canceled: unknown failed test/e2e/node/pods.go:474 k8s.io/kubernetes/test/e2e/node.createAndTestPodRepeatedly(0x3, 0xf, {0x7f6e4b8?, 0xc003588ac0}, {0x7f8e7c0?, 0xc003588a00}) 	test/e2e/node/pods.go:474 +0x81d k8s.io/kubernetes/test/e2e/node.glob..func10.3.3() 	test/e2e/node/pods.go:218 +0xaf}

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by aojea** [comment]
/close

Fixes by https://github.com/kubernetes/kubernetes/pull/113548

Thanks for reporting it
