### ISSUE TITLE
k8s nodes and NAT

### ISSUE THREAD

**Issue by shankeriyer** [kubernetes/kubernetes#11359]
I have a cluster made up of ubuntu nodes 192.168.1.1("ai") 192.168.1.2 ("i")
I am trying to add a k8s node ("192.168.2.1")  that is behind a NAT gateway.
The k8s node is translated as "192.168.1.100" in the "192.168.1.x" network.
Is this supported? What configuration changes do I need to make to get this to work?

**Comment by thockin** [comment]
Have you tried it and found it to be a problem?  With things like this it
is sometimes difficult to predict what will or won't work.  If it is a
1-to-1 NAT I suspect it will be transparent to us, as long as you add the
Node with the NAT IP and not the native IP.

**Comment by shankeriyer** [comment]
I have tried 2 scenarios
(a) with kube_up i configure my cluster to have a k8s node with an IP of 192.168.1.100.
      I find that the k8s nodes tries to bind to the 192.168.1.100 address and there are errors in the log
(b) Next I want to try a kubeup without the "192.168.1.100" node and try to add the node after the cluster is up with the local nodes. Here I need to modify the /etc/default/kubelet  /etc/default/etcd on the "192.168.2.1" node to ensure that it binds to its local internal address for the services it exposes but then the masters tries to talk back to it on "192.168.2.1" which is not possible

**Comment by thockin** [comment]
It sounds like there's some work to be done to make this work then, sorry.  It doesn't sound like a very common case, so we didn't cover it automatically.

**Comment by shankeriyer** [comment]
Wonder if etcd needs a combinations of the right set of parameters to get this working
viz. --initial-advertise-peer-urls => should have the translated so that the rest of the networks can access
--listen-peer-urls should have the local ip's
and the infra<n> should have the correct IP addresses depending on the location of the peers
Will try it out and update this thread

**Comment by WIZARD-CXY** [comment]
@shankeriyer , I decided to deploy one etcd instance per node to get a high availabilty.You can just run one etcd on master, this would be simpler for your case I assume.But I'm not sure behind a nat, a k8s master can find node or not...You can give it a shot.

**Comment by WIZARD-CXY** [comment]
Not sure whether you can configure it or not , I will give you a help link use docker to deploy k8s.  https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/docker-multinode/master.md. Hope it helps

**Comment by WIZARD-CXY** [comment]
It just use one etcd instance and avoid etcd trick settings

**Comment by mbforbes** [comment]
+cc @cjcullen

**Comment by thockin** [comment]
This seems like a very niche use case - I am not sure we want to go out of our way to make this better, unless such changes are good overall for other reasons.

**Comment by hwinkel** [comment]
to run K8s in a IoT/m2m use case this would be a typical scenario where you have just one "Gateway" node. Once you can reach this gateway Node K8s could create some kind of policy managed overlay network for the applications. But the external etcd should be available I assume.

BTW: IPv6 could be a option to once deployed more widely. How ist the IPv6 support these days?
