### ISSUE TITLE
coreDNS image reports the wrong architecture

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes/kubernetes#113543]
### What happened?

The docker images for linux/arm64 wrongly report their architecture as amd64. This issue affects at least the `v1.8.6` and `v1.9.3` of the coredns images.

### What did you expect to happen?

Expected the arm64 version of the image to correctly report its architecture as arm64.

## 1) Pull the image, specifying the linux/arm64 platform.
```bash
> docker pull --platform linux/arm64 registry.k8s.io/coredns/coredns:v1.8.6

v1.8.6: Pulling from coredns/coredns
Digest: sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e
Status: Image is up to date for registry.k8s.io/coredns/coredns:v1.8.6
registry.k8s.io/coredns/coredns:v1.8.6
```

## 2) Inspect the image for the digest linked to the specified platform.
```bash
> docker inspect -f '{{.Architecture}}' registry.k8s.io/coredns/coredns:v1.8.6@sha256:5b6ec0d6de9baaf3e92d0f66cd96a25b9edbce8716f5f15dcd1a616b3abd590e

amd64
```

The above images is not showing the correct architecture. 

Note that this issue is sometimes silent when using MacOS as the platform does support running amd64 images. e.g. `kind` can create a working cluster even with the wrong image arch. However, using e.g. `kind load` will fail as there is an architecture check when this command is run.

 

### Kubernetes version

N/A

### Cloud provider

<details>

</details>

### OS version

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chrisohaver** [comment]
> I think this issue is related to [coredns/coredns#5363](https://github.com/coredns/coredns/issues/5363).

Yes, should be resolved after next version of CoreDNS is released, and Kubernetes adopts that release.

There are no plans in CoreDNS project to re-package existing release images/manifests or release patched versions of prior releases.

**Comment by pacoxu** [comment]
The current version matrix is like
- v1.22: coredns v1.8.4
- v1.23: coredns v1.8.6 (v1.23~v1.24 would be affected by this problem)
- v1.25: coredns v1.9.3

Solutions:
- Can we upgrade v1.23/v1.24  coredns to v1.8.7? @chrisohaver or cherry-pick the v1.9.3 upgrade pr from v1.25?
- Or do we need to re-package existing release images?

/cc @neolit123

**Comment by BenTheElder** [comment]
> However, using e.g. kind load will fail as there is an architecture check when this command is run.

That is actually fixed in the latest release (v0.17, released last week at KubeCon)

**Comment by BenTheElder** [comment]
Note: This was fixed upstream,

**Comment by BenTheElder** [comment]
And the fix is reflected in current Kubernetes hosted images:
```
$ crane config --platform=linux/arm64 registry.k8s.io/coredns/coredns:v1.10.1 | jq .
{
  "architecture": "arm64",
  "config": {
    "ExposedPorts": {
      "53/tcp": {},
      "53/udp": {}
    },
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Entrypoint": [
      "/coredns"
    ],
    "WorkingDir": "/",
    "OnBuild": null
  },
  "created": "2023-02-06T18:31:03.986612462Z",
  "history": [
    {
      "created": "2023-02-06T18:31:00.19534776Z",
      "created_by": "COPY /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ # buildkit",
      "comment": "buildkit.dockerfile.v0"
    },
    {
      "created": "2023-02-06T18:31:03.986612462Z",
      "created_by": "ADD coredns /coredns # buildkit",
      "comment": "buildkit.dockerfile.v0"
    },
    {
      "created": "2023-02-06T18:31:03.986612462Z",
      "created_by": "EXPOSE map[53/tcp:{} 53/udp:{}]",
      "comment": "buildkit.dockerfile.v0",
      "empty_layer": true
    },
    {
      "created": "2023-02-06T18:31:03.986612462Z",
      "created_by": "ENTRYPOINT [\"/coredns\"]",
      "comment": "buildkit.dockerfile.v0",
      "empty_layer": true
    }
  ],
  "os": "linux",
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:6a4a177e62f374d68e6889ffa22b644db056e1d47ee4085c88408fa1d153871d",
      "sha256:e29e2326319da3f59c7245bdaa5a0d85d3547a36423037fbd0ac8fc1fc52a609"
    ]
  }
}
```

**Comment by jessehu** [comment]
Hello @chrisohaver , as K8s v1.25 uses coredns:v1.9.3, could you please re-package coredns:v1.9.3 with correct arm64 image?  It's incorrect on https://hub.docker.com/r/coredns/coredns/tags
<img width="554" alt="图片" src="https://github.com/kubernetes/kubernetes/assets/10006/b27211b9-df55-4db3-82cf-b6ae5eb55685">

**Comment by BenTheElder** [comment]
It is generally not best practice to mutate image tags.

Kubernetes 1.25 goes out of support in 3 days https://kubernetes.io/releases/

**Comment by jessehu** [comment]
1.26 also uses the 'bad' coredns 1.9.3
https://github.com/coredns/deployment/blob/master/kubernetes/CoreDNS-k8s_version.md
<img width="598" alt="图片" src="https://github.com/kubernetes/kubernetes/assets/10006/1806c9a7-35a9-4331-a52b-527a557f0829">

**Comment by chrisohaver** [comment]
This was fixed in a later release of coredns.

**Comment by pacoxu** [comment]
Only v1.25/v1.26 will be affected. 

@chrisohaver as v1.25 will be the end of life in 2 days. Should upgrade the coredns version to v1.9.4 or v1.10.1 for Kuberentes v1.26?

**Comment by jessehu** [comment]
hi @pacoxu  coredns 1.9.4 also not work for arm64, while 1.10.1 works: https://hub.docker.com/r/coredns/coredns/tags
