### ISSUE TITLE
virtiodev driver access problem in kubernetes and kind but everything works fine in minikube

### ISSUE THREAD

**Issue by votientu** [kubernetes/kubernetes#113590]
### What happened?

I’ve run an application to offload the compute on a GPU via the PCI link.
It works fine with Docker and Minikube but I’ve encountered a driver problem with Kubernetes (kubeadm or kind). 
I mounted all necessary local folders (and also checked) and gave the privileged access.
In fact, I use the same pod.yaml file for Minikube and Kubeadm or Kind but I get the same problem in Kubeadm and Kind.

```
kubectl create -f pod.yml
kubectl exec -it pod -- /bin/bash

(inside the Pod)
./myapp

Insuffisient access for file /sys/bus/***_rpmsg/devices/virtio1.dynept-1-1.-1.1/driver_override
cannot bind virtiodev virtio1.dynept-1-1.-1.1 to driver with service dynept-1-1
```

### What did you expect to happen?

The application should be running on Kind/Kubeadm as in Minikube

### How can we reproduce it (as minimally and precisely as possible)?

a

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Local development or Kubernetes server with two PCs
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
you could ask in #minikube on k8s slack to understand what is diffrent.

minikube also uses kubeadm, so this is likely a configuration problem with the host os.

/kind support
/close

**Comment by votientu** [comment]
Thank you for your answer @neolit123 , I'll ask on the k8s slack
