### ISSUE TITLE
[Failing test] [sig-node] Pods Extended Pod Container Status should never report success for a pending container

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#113547]
### Which jobs are failing?

Jobs affecting master presubmits a
https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd
https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind

### Which tests are failing?

[sig-node] Pods Extended Pod Container Status should never report success for a pending container

### Since when has it been failing?

Since 11-02 03.00 GMT+1

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd

### Reason for failure (if possible)

most probably https://github.com/kubernetes/kubernetes/pull/113408

### Anything else we need to know?

The PR that got merged flaked on those tests multiple times

https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=113408

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
credit to @liggitt for helping pinpointing the offending PR

**Comment by liggitt** [comment]
the two failing tests are failing with context canceled errors, so the context plumbing PR is almost certainly the cause:

> "container unexpected exit code 128: start=1970-01-01 00:00:00 +0000 UTC end=2022-11-02 12:51:48 +0000 UTC reason=StartError message=failed to create containerd task: failed to create shim task: context canceled: unknown failed"

those two tests also failed in 75% of the presubmit gce and kind e2e presubmit runs on that PR: https://prow.k8s.io/pr-history/?org=kubernetes&repo=kubernetes&pr=113408

+1 to revert while we figure out how to plumb the context without causing API-visible context canceled errors for existing users
