### ISSUE TITLE
test MinimizeIPTablesRestore in scale tests

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#113678]
We need to enable the `MinimizeIPTablesRestore` feature gate in some/all? scale tests, and check the `sync_proxy_rules_iptables_partial_restore_failures_total` metric at the end of the run. (We believe it should be 0 at the end of the run, but we may not want to actually assert that until we've done a few runs?)

/kind feature
/sig network
/assign @aojea

**Comment by aojea** [comment]
/closed

fixed by https://github.com/kubernetes/test-infra/pull/27927/

**Comment by danwinship** [comment]
you mean
/close

**Comment by aojea** [comment]
hhaha 
thanks
