### ISSUE TITLE
ContainerCheckpoint fails with - unknown method CheckpointContainer - in v1.25

### ISSUE THREAD

**Issue by jgan129** [kubernetes/kubernetes#113621]
### What happened?

On an Ubuntu 18.04.6 (GCP image but could be irrelevant) I installed microk8s with: 
`sudo snap install microk8s --channel=1.25-strict/stable`
Under path /var/snap/microk8s/current/args I then edited the following two files to enable the [ContainerCheckpoint](https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/) feature gate
- kubelet
- kube-apiserver

by adding/editing the following line:
`--feature-gates=ContainerCheckpoint=true`

After saving the changes to both files above, I then did:
`microk8s stop`
`microk8s start`

`microk8s inspect` returns:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3337689/199928418-3431758f-edf9-4b37-994e-b90310e88c5a.png">

The cluster had already a sample pod deployed. Verified this with:
`microk8s.kubectl get pods`
<img width="543" alt="image" src="https://user-images.githubusercontent.com/3337689/199924613-0cc163dd-65b0-4517-960c-64998814624f.png">

With a curl command I then tried to use the ContainerCheckpoint feature I enabled earlier with:
`curl -XPOST  --cert /var/snap/microk8s/current/certs/server.crt   --key /var/snap/microk8s/current/certs/server.key    --insecure   https://127.0.0.1:10250/checkpoint/default/nginx-deployment-69747bc944-79qqz/nginx`

What I got back was:
**checkpointing of default/nginx-deployment-69747bc944-79qqz/nginx failed (rpc error: code = Unimplemented desc = unknown method CheckpointContainer for service runtime.v1.RuntimeService)**

### What did you expect to happen?

The expectation is to have a checkpointed container with a tar file stored as described in 
https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/#post-checkpoint 

### How can we reproduce it (as minimally and precisely as possible)?

By following the steps I did in the initial description.
To deploy a sample pod (and a service):
[app.txt](https://github.com/kubernetes/kubernetes/files/9936766/app.txt)

### Anything else we need to know?

The error message contains the keyword CheckpointContainer while this has been renamed to ContainerCheckpoint:
[https://github.com/kubernetes/website/issues/36705](https://github.com/kubernetes/website/issues/36705) 

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-28T19:42:26Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-28T19:43:07Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}




### Cloud provider

<details>
GCP
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux gg-k8s-builder 5.4.0-1092-gcp #101~18.04.1-Ubuntu SMP Mon Oct 17 18:29:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux



### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
So the error message is about the CRI API not the feature gate.

I'm pretty sure this is not a kubernetes bug and is a microk8s issue, possibly with outdated container runtime versus the kubernetes version. What runtime and version is in use?

**Comment by jgan129** [comment]
> So the error message is about the CRI API not the feature gate.
> 
> I'm pretty sure this is not a kubernetes bug and is a microk8s issue, possibly with outdated container runtime versus the kubernetes version. What runtime and version is in use?

Executing
`microk8s kubectl get nodes -o wide`
returns the following:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/3337689/200570482-0bd16e51-95af-4780-9287-2e386d4e4d86.png">

so I guess the OCI is containerd with version 1.6.6.
What should be the minimum one?

**Comment by SergeyKanzhelev** [comment]
cc: @adrianreber

https://github.com/containerd/containerd/pull/6965

as long as it doesn't crash kubelet it is expected for the feature in alpha.

/remove-kind bug
/kind feature

**Comment by SergeyKanzhelev** [comment]
You may want to try k8s with CRI-O if you want to try this feature today

**Comment by adrianreber** [comment]
Yes, as far as I know it only works with cri-o. I am not aware of any other container engine supporting checkpointing.

**Comment by jgan129** [comment]
> 

@adrianreber, @BenTheElder,
Thanks for your replies.

Here's what I did:
I installed minikube on another machine (Ubuntu 20.04) and used CRI-O as you suggested. 
I started minikube with the following command:
`sudo minikube start --feature-gates=ContainerCheckpoint=true --install-addons=true  --container-runtime=cri-o --network-plugin=cni --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost`

Executing `kubectl get nodes -o wide` proves the use od CRI-O
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/3337689/201094871-404480fe-6231-4091-a696-a8c5053af596.png">

I then deployed my sample pod again:
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/3337689/201095567-5bd82cfc-0c24-441d-957a-f23f5cce3608.png">

and executed the curl command to perform a checkpoint:
curl -XPOST --cert ~/.minikube/profiles/minikube/client.crt --key ~/.minikube/profiles/minikube/client.key  --insecure  https://127.0.0.1:10250/checkpoint/default/nginx-deployment-69747bc944-rkhwp/nginx

Unfortunately the result is still the same:
`checkpointing of default/nginx-deployment-69747bc944-rkhwp/nginx failed (rpc error: code = Unknown desc = checkpoint/restore support not available)`

I still don't see what is going wrong since this feature (ContainerCheckpoint) is supposed to be supported in Alpha k8s 1.25 version.

**Comment by jgan129** [comment]
> You need special command line options to enable checkpoint support in CRI-O.
> 
> Please see [kubernetes/website#37412](https://github.com/kubernetes/website/pull/37412) for a possible blog post.

Thanks for the link!
This worked now, I can checkpoint containers after passing the --enable-criu-support=true and --drop-infra-ctr=false flags to cri-o config.

However I have not managed to restore the checkpointed container with any of the two ways proposed in the blog (outside/inside kubernetes).

**Comment by adrianreber** [comment]
Nice to hear that it works.

I would need to know the error message that you get during restore to help you.

I think this can be closed and you could open a crio ticket and discuss your error there.

**Comment by jgan129** [comment]
I agree, I will create a separate one since restoring is another issue.
