### ISSUE TITLE
`kubeadm init phase certs` keeps the "Validity  > NotBefore"  value from CA history , and it causes the duration from "Validity > NotBefore" to "Validity > NotAfter" for new certificates , is passing one year. It cause security scanners alarm for certificates.

### ISSUE THREAD

**Issue by ali-parsfar** [kubernetes/kubernetes#113618]
### What would you like to be added?

`kubeadm init phase certs` needs to take the "Validity  > NotBefore" from current date/time of the system . to keep the life time of certificate one year.

### Why is this needed?

If we have any renewal for the API-Server certificate  ( like renew of API-Server in AWS EKS cluster , because of the Control Plane instance refresh ) , the "Validity  > NotBefore" will stay as the creation time of the cluster and CA, but the new API-Certificate expiry time ( "Validity  > NotAfter" ) will update to keep the certificate life to one year from this renewal .
It is causing the duration from "Validity  > NotBefore"  to "Validity  > NotAfter" will be more than one year .
It causes security scanners , to detect API-Server certificate with more than one year life time . and take it as a security issue.

You can reproduce this issue with following steps :
1- create all certificate with kubeadm:
```s
root@ip-172-31-20-161:~# kubeadm init phase certs all
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [ip-172-31-20-161 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.31.20.161]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [ip-172-31-20-161 localhost] and IPs [172.31.20.161 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [ip-172-31-20-161 localhost] and IPs [172.31.20.161 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
root@ip-172-31-20-161:~# 
```

2- Check the API-Server Validity dates  :
```s
root@ip-172-31-20-161:/etc/kubernetes/pki# cat apiserver.crt | openssl x509  -noout -text 
..
..  ..
        Validity
            Not Before: Nov  3 04:46:54 2022 GMT
            Not After : Nov  3 04:46:54 2023 GMT
```

3- Delete the api-server certificate in the "/etc/kubernetes/pki"  and change the system date ( I change it from 3rd to 4th Nov in OS level ) and some node attributes to create new certificate for api-server  :
```
root@ip-172-31-31-27:/etc/kubernetes/pki# kubeadm init phase certs apiserver
[certs] Generating "api-server" certificate and key
[certs] api-server serving cert is signed for DNS names [ip-172-31-31-27 kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 172.31.31.27]
root@ip-172-31-31-27:/etc/kubernetes/pki# 
```

4- Check new certificate Validity dates  :
```s
root@ip-172-31-20-161:/etc/kubernetes/pki# cat apiserver.crt | openssl x509  -noout -text 
..
..  ..
        Validity
            Not Before: Nov  3 04:46:54 2022 GMT
            Not After : Nov  4 06:48:49 2023 GMT
```
```
As you can see, the certificate life time ,  is one day more than a year now !

**Comment by neolit123** [comment]
/sig cluster-lifecycle security
/area kubeadm

kubeadm currently takes the notBefore from the CA cert:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L662-L663

> and change the system date

from my POV that is a non issue, because only the host OS admin can do it.
and the host OS admin has full control of the host - e.g. replacing certs entirely.

also if the notBefore is shifted for one day in the future the cert will not work for one day, if the admin reverts the time to Nov 3rd after signing it.

but please if this raises concerns on your side, join the k8s slack and open the discussion in #sig-security
if the security SIG are +1 for your change we can address it in kubeadm.

cc @SataQiu @fabriziopandini
