### ISSUE TITLE
Add linter for API doc field check 

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#113630]
### What would you like to be added?

Currently we have inconsistency in most of the API where the field name should be used in description so the generated docs match the API fields people actually set. https://github.com/kubernetes/kubernetes/issues/113438

A linter could be added for checking

### Why is this needed?

To avoid confusing users

**Comment by Akshit42-hue** [comment]
Hey @cici37 can you provide some more information for this issue

**Comment by jabhishek87** [comment]
@Akshit42-hue  are you still working on this?
