### ISSUE TITLE
Conflict with wireguard vpn on iptables

### ISSUE THREAD

**Issue by mohsensamiei** [kubernetes/kubernetes#113659]
Hello Dears
I need to setup wireguard vpn on server before installing Kubernetes then install Kubernetes on top of that

But after installing Kubernetes `KUBE-FIREWALL` chain stops Wireguard traffic
`DROP       all  --  any    any     anywhere             anywhere             /* kubernetes firewall for dropping marked packets */ mark match 0x8000/0x8000`

I can delete this rule, but I don't know what the consequences are

Do you think there is a solution?

**Comment by aojea** [comment]
> I can delete this rule, but I don't know what the consequences are

That rule will be recreated , I think you just have to do the opposite, insert a rule to allow your Wireguard traffic 😄

**Comment by mohsensamiei** [comment]
Your solution 2nd is working, I replaced mark with `FwMark` key in Wireguard config
Thanks

**Comment by jingslunt** [comment]
> Are you sure _that_ rule is dropping the traffic? It only drops traffic which has a particular mark bit set (ie, traffic which has previously been directed to the `KUBE-MARK-DROP` chain).
> 
> If your wireguard configuration is also using that mark bit for something, then you have three options:
> 
> 1. Upgrade to kube 1.25 if you weren't already using it, and enable the `IPTablesOwnershipCleanup` feature gate on kubelet; then it will no longer create the drop rule.
> 2. Change your wireguard configuration to use different mark bits that don't conflict with the ones kubernetes uses (bits 14 and 15, aka 0x4000 and 0x8000). (I don't know how you'd do this.)
> 3. Change your kubernetes configuration to use different mark bits that don't conflict with your wireguard configuration (by passing `--iptables-drop-bit` and `--iptables-masquerade-bit` to kubelet and _also_ passing the same `--iptables-masquerade-bit` value to kube-proxy, assuming you're using kube-proxy).

Is it possible to support wireguard proxy by default for kubelet, so that users can more easily proxy the network of the entire cluster？
