### ISSUE TITLE
network Policy they don't do the work on the pod level 

### ISSUE THREAD

**Issue by aasyria** [kubernetes/kubernetes#113624]
### What happened?

The Network Policy on the Namespace dose not blocking the Communication on the Pod Level 

### What did you expect to happen?

When I create deny All Ingress and Egress Network Policy for one Namespace, then I am expecting that my Pods in this Namespace will be not reachable from anywhere in the Cluster. 
but I can ping the Pod IP-Adress and scan it with nmap.

### How can we reproduce it (as minimally and precisely as possible)?

- create namespaces pentest1 and pentest2
- create inside these namespaces pod1 ,pod2 
- create deny all network policy as it from the documentation.
- get shell inside both of the pods and get the internal IP address
- ping the Pods  you will reach them 

### Anything else we need to know?

Maybe this is not a Bug and I need to understand something else, and I will appreciate any information that I learn from it.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.23.4
Client Version: v1.25.3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker://18.9.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nandorKollar** [comment]
Does the CNI you use support network policies? As per the doc: "Creating a NetworkPolicy resource without a controller that implements it will have no effect.", you'll need a CNI which implements a network policy controller. [This](https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/) task mentions a couple of CNI which ships with this feature.

**Comment by thockin** [comment]
@aasyria Waiting for response regarding CNI.

You left most of the requersted details blank, so there's not much we can do without more information.

* Which CNI?
* Paste YAML of the NetworkPolicy resource(s)
* Ping may or may not be blocked (ICMP is not a policy-controlled protocol).  Try an actual socket connection.

**Comment by kundan2707** [comment]
@aasyria Can you provide requested information ?

**Comment by aasyria** [comment]
Sorry for guys, i don't have access anymore for the project, but i asked the team to give me the information .
i will write here asp

**Comment by aasyria** [comment]
i checked and it was calico

**Comment by thockin** [comment]
@aasyria you only answered one question

* Paste YAML of the NetworkPolicy resource(s)

* Ping may or may not be blocked (ICMP is not a policy-controlled protocol). Try an actual socket connection.
