### ISSUE TITLE
[Failing Test] gce-device-plugin-gpu-master

### ISSUE THREAD

**Issue by bharitwal** [kubernetes/kubernetes#113625]
### Which jobs are failing?

release-master-blocking:

- gce-device-plugin-gpu-master

### Which tests are failing?

- ci-kubernetes-e2e-gce-device-plugin-gpu.Overall
- kubetest.Up

### Since when has it been failing?

3rd November 2022

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

### Reason for failure (if possible)

e2e.go: Up  | 28m51s
-- | --
{  error during ./hack/e2e-internal/e2e-up.sh: exit status 1}

### Relevant SIG(s)

/sig cloud-provider
cc @kubernetes/ci-signal

**Comment by dims** [comment]
`CRI v1 runtime API is not implemented for endpoint` 

from:
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-device-plugin-gpu/1588131568377925632/artifacts/bootstrap-e2e-minion-group-nb82/kubelet.log

**Comment by dims** [comment]
we'll need to bump the node image i think:
https://github.com/kubernetes/test-infra/blob/730453bab12e3665e6da84f2bb80bd3d1cc26c14/config/jobs/kubernetes/sig-cloud-provider/gcp/gpu/gpu-gce.yaml#L8

**Comment by bobbypage** [comment]
Latest run is passing now!
