### ISSUE TITLE
[failing jobs] sig-cluster-lifecycle-kubeadm#kubeadm-kinder-*latest

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#113619]
### Which jobs are failing?

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-upgrade-1-25-latest

all *latest kubeadm jobs (k/k master)
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

### Which tests are failing?

the "init" test which creates the first kubeadm control plane node.
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

### Since when has it been failing?

Nov 3rd EOD

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

### Reason for failure (if possible)

k/k diff
https://github.com/kubernetes/kubernetes/compare/4086b45af...f536b3cc4

there are no kubeadm changes on that diff.

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1588418612543098880/artifacts/task-03-init-log.txt

the kubelet is not responding at healthz
> [kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused.

kubelet logs
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1588175860555321344/artifacts/kinder-regular-control-plane-1/kubelet.log

> Nov 03 14:32:26 kinder-regular-control-plane-1 kubelet[413]: I1103 14:32:26.452585     413 container_manager_linux.go:301] "Creating device plugin manager"
Nov 03 14:32:26 kinder-regular-control-plane-1 kubelet[413]: I1103 14:32:26.452649     413 state_mem.go:36] "Initialized new in-memory state store"
Nov 03 14:32:26 kinder-regular-control-plane-1 kubelet[413]: E1103 14:32:26.456469     413 run.go:74] "command failed" err="failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
Nov 03 14:32:26 kinder-regular-control-plane-1 systemd[1]: kubelet.service: Main process exited, code=exited, 

the k/k diff seems unrelated?

are we running containerd that is too old and since when the 1.26 kubelet no longer supports CRI < v1?

> Nov 03 14:30:37 kinder-regular-control-plane-1 containerd[123]: time="2022-11-03T14:30:37.740831383Z" level=info msg="starting containerd" revision=7af311b4200b464a79c340b4e3a2799f8906ee8d version=v1.3.0-20-g7af311b4

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-latest/1588175860555321344/artifacts/kinder-regular-control-plane-1/containerd.log

### Relevant SIG(s)

/sig cluster-lifecycle node

**Comment by neolit123** [comment]
cc @pacoxu @SataQiu 

@kubernetes/sig-node-bugs

**Comment by pacoxu** [comment]
Where can I find the base kinder building process? It seems to be an old kinder base image is using. The containerd v1.3.0 is too old.

**Comment by neolit123** [comment]
we don't have a build process for the base image. we just use an old one from the kind repository.

is containerd 1.3 actually out of support by k8s 1.26?
iiuc, pre v1 CRI would have been supported for longer?

this can create skew problems for our test jobs, because we are still testing 1.22 and i don't know if CRI v1 is supported in that kubelet.

**Comment by neolit123** [comment]
looks like this is the cause. it merged yesterday
https://github.com/kubernetes/kubernetes/pull/110618

**Comment by neolit123** [comment]
> so ideally we should try moving to the latest kind base image and make kinder work with it. might be a bit tricky

i will try this today, but not sure i will have enough time

**Comment by neolit123** [comment]
fix in https://github.com/kubernetes/kubeadm/pull/2778

**Comment by neolit123** [comment]
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

went green, so the rest of the jobs should too.
