### ISSUE TITLE
Remove dependency on github.com/pkg/errors

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#113627]
**Why is this needed?**

The functionality that the package provides is already present in golang's builtin errors (using `%w` in `fmt.Errof`) and the github repo is now read-only.

/kind cleanup
/priority backlog
/good-first-issue

**Notes to people that want to collaborate**

Avoid creating a single PR for the entire repo. Create multiple PRs, each targeting a specific SIG.

Do **not** submit PRs for `cmd/kubeadm`

**Comment by ShivamTyagi12345** [comment]
/ assign

**Comment by BenTheElder** [comment]
> The functionality that the package provides is already present in golang's builtin errors (using %w in fmt.Errof) and the github repo is now read-only.

this is only partially true, e.g. %w does not provide stack traces

**Comment by alculquicondor** [comment]
@BenTheElder I see. Should we close this issue then?

**Comment by BenTheElder** [comment]
I think it depends on how it's being used. If the traces are not the goal then we can do a simple substitution. It's probably best to drop read only dependencies but it's worth noting that if we depended on the full functionality in any way we'll need a more complex replacement

**Comment by mythi** [comment]
> I think it depends on how it's being used. If the traces are not the goal then we can do a simple substitution. It's probably best to drop read only dependencies ASAP 

k/k git log suggests that some cleanup has already been done in the past (maybe in other commits too):
```
$ git log --format="%ai %h %s" |grep pkg/\errors|head
2022-07-26 16:44:59 +0800 6cab9800a71 kubeadm: prefer to use pkg/errors package and cleanup fmt.Errorf
2021-09-13 13:02:59 +0530 c6b82bddd6e removing usage of github.com/pkg/errors from test/conformance/image/go-runner/ directory
2021-06-23 22:14:18 +0800 e2e1c94f063 use native error instead of github.com/pkg/errors
2021-06-23 10:14:19 +0800 ceb42d09389 Update github.com/pkg/errors with go native errors pkg
2021-06-23 17:06:43 +0800 674802147c8 update to remove github.com/pkg/errors
2021-06-23 18:13:44 +0800 e7a240395e9 uses native errors instead of github.com/pkg/errors
2021-06-23 17:46:23 +0800 12dcd2f84d4 Remove usage of github.com/pkg/errors
2021-06-22 11:54:56 +0800 4b140218747 update github.com/pkg/errors to go native errors pkg in staging
2021-06-23 08:07:05 +0530 992993257d8 Removed usage of github.com/pkg/errors
2021-06-22 10:43:30 +0530 ec93b3b0be4 Stop using github.com/pkg/errors
```

This issue triggered 3 PRs and 2 of them are merged. 

> but it's worth noting that if we depended on the full functionality in any way we'll need a more complex replacement (KIND did/does, not sure about k/k)

there does not seem to be calls to `errors.WithStack()` so most cases it looks it's just wrapping errors.

**Comment by neolit123** [comment]
for cmd/kubeadm in kubernetes/kubernetes we decided to not drop usage of pkg/errors even if it's a deprecated project.

prior ticket and comments are here
https://github.com/kubernetes/kubernetes/issues/103043#issue-926076534

**Comment by neolit123** [comment]
for cmd/kubeadm in kubernetes/kubernetes we decided to not drop usage of pkg/errors even if it's a deprecated project.

prior ticket and comments are here
https://github.com/kubernetes/kubernetes/issues/103043#issue-926076534

**Comment by alculquicondor** [comment]
I see. Added a note.

**Comment by devansh-m12** [comment]
is it still open ?

**Comment by tillknuesting** [comment]
`pkg/errors` should be replaced with the standard library for the following reasons:

- archived library with no maintenance or security updates 
- the go community used pkg/errors to introduce eventually into the standard library hence the approach that was selected is more idiomatic
- stack traces are hardly used in error wrapping and are not a reason not to refactor

**Comment by pacoxu** [comment]
On place left in
https://github.com/kubernetes/kubernetes/blob/a7f34ff8c484ad398686e47ab3582549839efbc9/staging/src/k8s.io/kubectl/pkg/cmd/patch/patch.go#LL26C9-L26C9

**Comment by pacoxu** [comment]
> @pacoxu, is it necessary to remove "github.com/pkg/errors" from every location? I noticed it in many places. Also, do I need to create separate PRs for each file where I remove it?

From kuberentes/kubernetes repo view, only two locations of kubectl code should be updated. (Do not submit PRs for `cmd/kubeadm`)
see https://github.com/kubernetes/kubernetes/issues/113627#issuecomment-1375849250.

For other repos, we should follow up until the dependencies' repo is updated. I will track them in https://github.com/kubernetes/kubernetes/issues/114942.

**Comment by 0xchabbi** [comment]
to remove dependency you can use the standard Go error package or creating your own handling package, this could contain custom functions for generating and handling errors.

**Comment by ashutosh887** [comment]
let me work on this issue now please
/assign

**Comment by sherifhmdy** [comment]
Hello, is this still up?

**Comment by tillknuesting** [comment]
Let's get this going

**Comment by jbiers** [comment]
@tillknuesting @pacoxu Just opened a PR for this issue
 https://github.com/kubernetes/kubernetes/pull/117572

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/4f303d123659fb3aac2108f8439c7f43dde438b5/hack/unwanted-dependencies.json#L170-L187
- k8s.io/kubectl: https://github.com/kubernetes/kubernetes/pull/117572

Update the remaining todo items.

**Comment by neolit123** [comment]
/sig architecture
umbrella / code org

**Comment by moshevayner** [comment]
Hey @ArjunMenon-bit!
Are you still working on this one? If not- would you mind if I take a stab at it?
Thanks!

**Comment by Git-Jiro** [comment]
Is this issue really still open?
When I do
`grep -lr "github.com/pkg/errors" api cluster cmd pkg plugin`
I only get hits for cmd/kubeadm.

Am I missing something?
