### ISSUE TITLE
Document KMS healthz endpoint behavior

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#113631]
> making the reload behavior rely on content in the thing being reloaded is weird
> 
> I think this should limit itself to saying that enabling reloading collapses all kms providers to a single healthz check
> 
> separately (in the kmsv1 and kmsv2 config docs?) say that individual kms healthz checks are only provided when kmsv1 impls are in use and the encryption config is not auto-reloaded

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/113529#discussion_r1013586389_

**Comment by enj** [comment]
/assign @nilekhc 

Since you worked on the automatic reloading PR :)

**Comment by nilekhc** [comment]
> Hello @enj bug triage shadow here. Is this still on track for 1.26? Is there a related PR open?

Hi @cailynse, I opened https://github.com/kubernetes/website/pull/38003 to address this.

**Comment by aramase** [comment]
Closed with https://github.com/kubernetes/website/pull/38137

/close
