### ISSUE TITLE
[Flake] test-cmd: run_kubectl_server_side_apply_tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#113677]
### Which jobs are flaking?

pull-kubernetes-integration: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-integration&include-filter-by-regex=%5BAa%5Dpply

ci-kubernetes-integration-master: https://testgrid.k8s.io/sig-release-master-blocking#integration-master&include-filter-by-regex=[Aa]pply&width=5

### Which tests are flaking?

run_kubectl_server_side_apply_tests

### Since when has it been flaking?

Unclear, shows up in flakes in triage history as far back as it goes

### Reason for failure (if possible)

```
Apply failed with 1 conflict: conflict with "kubectl-client-side-apply" using v1: .metadata.labels.name
Please review the fields above--they currently have other managers. Here
are the ways you can resolve this warning:
* If you intend to manage all of these fields, please re-run the apply
  command with the `--force-conflicts` flag.
* If you do not intend to manage all of the fields, please edit your
  manifest to remove references to the fields that should keep their
  current managers.
* You may co-own fields by updating your manifest to match the existing
  value; in this case, you'll become the manager if the other manager(s)
  stop managing the field (remove it from their configuration).
See https://kubernetes.io/docs/reference/using-api/server-side-apply/#conflicts
error: unable to retrieve the complete list of server APIs: mygroup.example.com/v1alpha1: the server could not find the requested resource
```

### Anything else we need to know?

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=conflict%20with%20%22kubectl-client-side-apply%22%20using%20v1%3A%20.metadata.labels.name

Representative failure: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/107531/pull-kubernetes-integration/1589519927906144256

### Relevant SIG(s)

/sig api-machinery

/cc @apelisse

**Comment by ardaguclu** [comment]
If I'm not wrong, SSA conflict error is a real test case and expected(https://github.com/kubernetes/kubernetes/blob/fb9b466f3052ca737ccb3098132a6ac21c59ad79/test/cmd/apply.sh#L421). 

That test looks failing in https://github.com/kubernetes/kubernetes/blob/fb9b466f3052ca737ccb3098132a6ac21c59ad79/test/cmd/apply.sh#L480. I could not find any recent change about that but if there is a latency for discovery endpoint being populated, this test should be flaky for a long time.

**Comment by ardaguclu** [comment]
Another thing is if we get this not found error from discovery, we are not cleaning it properly and that causes run_crd test fails with already exist.

**Comment by apelisse** [comment]
> Another thing is if we get this not found error from discovery, we are not cleaning it properly and that causes run_crd test fails with already exist.

That's a good point, it's hard to clean-up properly though on failures :-/.

And yes, I don't think ssa is the problem here, the problem is in getting the api-resources.

**Comment by apelisse** [comment]
Submitted PR to attempt to fix it, it doesn't solve the clean-up issue, but at least it should hide it well :-)
