### ISSUE TITLE
Kubectl delete command's wrong synopsis

### ISSUE THREAD

**Issue by feihujiang** [kubernetes/kubernetes#11362]
In kubectl_delete.md, It says "if both a filename and command line arguments are passed, the command line arguments are used and the filename is ignored."

but when I test, 

$kubectl delete pods asdf -f pod.yaml
error: when paths, URLs, or stdin is provided as input, you may not specify a resource by arguments as well

So I think the description "if both a filename and command line arguments are passed, the command line arguments are used and the filename is ignored." is not right, we should correct it

**Comment by ArtfulCoder** [comment]
@feihujiang do you want to submit a PR with the change ?

**Comment by feihujiang** [comment]
@ArtfulCoder Yes, I have submitted a PR with the change.

**Comment by feihujiang** [comment]
@bgrant0607  Could you please give this issue milestone?
