### ISSUE TITLE
kubelet: cadvisor supports enable network tcp metrics

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#113616]
### What would you like to be added?

Some of our customers want the TCP-related metrics from the cadvisor.
- kubelet ignores these metrics by default.

Option:
1.  Add a kubelet config option in KubeletConfiguration. If it is enabled, add NetworkTcpUsageMetrics in the included metrics list of cadvisor.
2. Make a general config to config more Metrics to add. 
The list can be found at https://github.com/google/cadvisor/blob/d569a2a47baa73c489d7138afb2c0745769c8791/container/factory.go#L48-L69.
The default list should be kept always.
https://github.com/kubernetes/kubernetes/blob/442574f3a7321ff0f34dec9bae67f28651dbabd2/pkg/kubelet/cadvisor/cadvisor_linux.go#L86-L104

Workaround:
- If you need TCP-specific metrics, you can [run a daemonset](https://github.com/google/cadvisor/tree/master/deploy/kubernetes) with [tcp metrics enabled](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md#metrics). See https://github.com/kubernetes/kubernetes/issues/60279#issuecomment-469360637.

### Why is this needed?

https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md

/sig instrumentation
/sig node
/cc @dashpole 
For disable process metrics, we have some discussions in https://github.com/kubernetes/kubernetes/pull/107660 and https://github.com/kubernetes/kubernetes/pull/107630. This is another topic of enabling some more metrics.

**Comment by dashpole** [comment]
cc @bobbypage

We might not want to do this given the in-progress migration from cAdvisor to CRI-based stats.  This would increase the surface area of things that would need to be migrated

**Comment by bobbypage** [comment]
+1, I agree with @dashpole, would prefer we focus on CRI-stats and add any stats there first.

**Comment by pacoxu** [comment]
So I think I should close this issue as we have no plan to enable it due to mentioned reasons.

Reopen if needed.
