### ISSUE TITLE
Setting toleration on StatefulSet doesn't restart associated Pods

### ISSUE THREAD

**Issue by utkarsh-pro** [kubernetes/kubernetes#113671]
### What happened?

I have a kubernetes cluster running. I tainted the worker nodes and then proceeded to create a statefulset in the cluster **without** providing any tolerations. Of course, this lead to pods in the state "Pending". Later on, I added tolerations to the statefulset and confirmed that the toleration are indeed applied to the STS, no new pods were created and nor older ones were deleted.

### What did you expect to happen?

I simply expected that the tolerations that I add to the statefulset will be passed on to the underlying pods allowing them to be scheduled.

### How can we reproduce it (as minimally and precisely as possible)?

```console
$ cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
EOF

$ # Taint the nodes

$ kubectl edit sts web # Add tolerations to the sts
```

Performing the above will set the tolerations to the statefulset but the associated pods will still not be scheduled.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0+b62823b", GitCommit:"0a57f1f59bda75ea2cf13d9f3b4ac5d202134f2d", GitTreeState:"clean", BuildDate:"2022-08-19T00:38:59Z", GoVersion:"go1.18.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
OpenShift (GCP)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
$ uname -a
Linux ci-ln-ipt4gbk-72292-jtbsx-master-0 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

**Comment by kerthcet** [comment]
I think this is as designed, see https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#forced-rollback. You have to delete the failed pod to make the rolling update successful again.

FYI: I submitted a KEP to discuss about this before, if you're interest, you can take a look https://github.com/kubernetes/enhancements/pull/3562

**Comment by utkarsh-pro** [comment]
Thank you for responding @kerthcet. So basically if a pod isn't scheduled on any of the nodes because of missing tolerations then the user **must**:
1. Add tolerations to the statefulset.
2. Delete the pods manually.

And if the above mentioned KEP is accepted then we might be able to use `enforcedRollingUpdate` to kind of automate this? Did I get that right?

**Comment by kerthcet** [comment]
Yes. But if you don't need the guarantee of pod orders, you can set the `podManagementPolicy` to parallel.
