### ISSUE TITLE
integration tests started to flake ~ Oct 29th

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#113651]
### Which jobs are flaking?

https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5

### Which tests are flaking?

it seems it affects the `k8s.io/kubernetes/test/integration/apiserver/admissionwebhook.TestWebhookAdmissionWithWatchCache`  and `k8s.io/kubernetes/test/integration/apiserver/admissionwebhook.TestWebhookAdmissionWithoutWatchCache`

### Since when has it been flaking?

doing a manual search it seems the first failure is from Oct 29 https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1586115640287039488

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=5

### Reason for failure (if possible)

it panics , but not always on the same type, pasting some snippets from different test runs

```
E1105 01:38:14.178412  100585 wrap.go:58] "apiserver panic'd" method="PUT" URI="/apis/networking.k8s.io/v1alpha1/clustercidrs/clustercidr1" audit-ID="737ba488-f7ef-428f-9fd9-a32f262625cf"
http2: panic serving 127.0.0.1:34850: runtime error: invalid memory address or nil pointer dereferenc
```

```
E1104 17:32:38.322804  100219 wrap.go:58] "apiserver panic'd" method="PUT" URI="/apis/events.k8s.io/v1beta1/namespaces/webhook-integration/events/event2" audit-ID="7736aa8e-c15d-4578-9043-2ff2f90c028b"
http2: panic serving 127.0.0.1:60124: runtime error: invalid memory address or nil pointer dereference
```

### Anything else we need to know?

slack thread https://kubernetes.slack.com/archives/C09QZ4DQB/p1667685022162439

Found this PR that seems related merged about that time https://github.com/kubernetes/kubernetes/pull/113349, but I can't find a relation with it

### Relevant SIG(s)

/sig api-machinery

**Comment by liggitt** [comment]
the panic is here:

```
E1028 22:20:02.705858  100461 runtime.go:77] Observed a panic: runtime error: invalid memory address or nil pointer dereference
goroutine 69285 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:110 +0xb0
panic({0x449aee0, 0x822e9e0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
k8s.io/kubernetes/vendor/k8s.io/utils/trace.(*Trace).durationIsWithinThreshold(0xc010b412d0?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/trace/trace.go:226 +0x14
```

https://github.com/kubernetes/kubernetes/blob/1f9e20eb8617e312f9f61d28d93ed29e988d953d/vendor/k8s.io/utils/trace/trace.go#L225-L226

That started getting used in https://github.com/kubernetes/kubernetes/pull/113172

/cc @dashpole

**Comment by dashpole** [comment]
I think span nesting might not be implemented correctly in the trace util package.  The only change https://github.com/kubernetes/kubernetes/pull/113172 made was to nest spans in the util trace package.  It replaced utiltrace.New() calls with utiltrace.FromContext(ctx).Nest() calls.  I think for now, we should revert that portion of the change.  We can reintroduce it if we decide it is worth it.

**Comment by liggitt** [comment]
is there a reproducer for the panic/npe to be sure that's the issue?

**Comment by dashpole** [comment]
I can try and work on one next week.

I triple-checked that the component-base package never calls functions on a nil trace. Nest/Start checks [here](https://github.com/kubernetes/utils/blob/master/trace/trace.go#L154), AddEvent/Step checks [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/tracing/tracing.go#L58), and End/LogIfLong checks [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/tracing/tracing.go#L66), and those are the only three ways we call into utiltrace (other than getting/setting from context).  That leads me to believe that it was the switch from New -> Nest that caused the issue.  A hypothesis (which I need to confirm), is that the parent span ended before the child span.

**Comment by dashpole** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/113656.  We can wait until I have a reproduction if you would prefer.

**Comment by dashpole** [comment]
/reopen

Whoops, I think we still need to update the vendored version of k8s/utils in k/k

**Comment by aojea** [comment]
Awesome, great job David , it was a tricky one
