### ISSUE TITLE
[Failing test] aks-engine-windows-containerd-1.23

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#113784]
### Which jobs are failing?

[sig-release-1.23-informing](https://testgrid.k8s.io/sig-release-1.23-informing)

- [aks-engine-windows-containerd-1.23](https://testgrid.k8s.io/sig-release-1.23-informing#aks-engine-windows-containerd-1.23)

### Which tests are failing?

* Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]

### Since when has it been failing?

10/21

Last successful run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-1-23/1583479808736628736
First failed run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-aks-engine-azure-master-windows-containerd-1-23/1583525107869945856

### Testgrid link

https://testgrid.k8s.io/sig-release-1.23-informing#aks-engine-windows-containerd-1.23

### Reason for failure (if possible)

```
{ Failure /home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/framework/framework.go:633
Nov  9 10:34:45.611: deploying extension apiserver in namespace aggregator-7487
Unexpected error:
    <*errors.errorString | 0xc0042fb850>: {
        s: "error waiting for deployment \"sample-apiserver-deployment\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"sample-apiserver-deployment-dd86b6f68\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
    }
    error waiting for deployment "sample-apiserver-deployment" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), Reason:"MinimumReplicasUnavailable", Message:"Deployment does not have minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 10, 29, 45, 0, time.Local), Reason:"ReplicaSetUpdated", Message:"ReplicaSet \"sample-apiserver-deployment-dd86b6f68\" is progressing."}}, CollisionCount:(*int32)(nil)}
occurred
/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/apimachinery/aggregator.go:320}
```

### Anything else we need to know?

The job was recently failing because of some other issue, but that was fixed yesterday with https://github.com/kubernetes/test-infra/pull/27937. The original issue described above still remains.

### Relevant SIG(s)

/sig windows
cc @kubernetes/ci-signal

**Comment by marosset** [comment]
I mirrored `registry.k8s.io/etcd:3.5.5-0` to `k8sprow.azurecr.io/kubernetes-e2e-test-images/etcd:3.5.5-0` which is used used by Windows e2e test clusters for K8s v1.24 and below.
That should address this issue.
/close
