### ISSUE TITLE
API parameter parsing Error

### ISSUE THREAD

**Issue by painsAgains** [kubernetes/kubernetes#113720]
### What happened?

In the 1.25.3 API documentation, the `allowWatchBookmarks` and `watch` parameter is defined as a boolean, 
![image](https://user-images.githubusercontent.com/49607803/200519198-ec882034-dfa6-4640-969d-d12b594af98c.png)
![image](https://user-images.githubusercontent.com/49607803/200519353-5839d6d4-8bd4-4071-af8e-30f0d4d7e040.png)

but when I pass in parameters of string type, integer type, and floating point type, I find that I still receive a response with a status code of 200

### What did you expect to happen?

When I use the wrong parameter type, I should receive an error response，like：500 status code

### How can we reproduce it (as minimally and precisely as possible)?

**allowWatchBookmarks**
curl -v -X GET 'https://xxxx:6443/apis/storage.k8s.io/v1beta1/namespaces/playback/csistoragecapacities?pretty=professedly&watch=true&continue=notoriously&limit=17&allowWatchBookmarks=8509.369874816839' -H 'Authorization:CENSORED' -H 'Accept: */*'
**watch**
curl -v -X GET 'https://xxxx:6443/api/v1/watch/secrets?pretty=averse&watch=7031.231633384946&labelSelector=letting&timeoutSeconds=27&allowWatchBookmarks=false' -H 'Authorization:CENSORED' -H 'Accept: */*'

In the examples,I use the float type, you also can change the type to str or int

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
In my own cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux k8s-master 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

https://github.com/kubernetes/kubernetes/issues/113720#tasklist-block-233854ec-1d1f-4e53-a03b-1dcb594511f4

**Comment by liggitt** [comment]
This is documented as a boolean, and clients should pass a boolean, but we should not break existing requests that are returning successful responses using other values that parse to boolean true using strconv.ParseBool (https://pkg.go.dev/strconv), which is how this was implemented
