### ISSUE TITLE
dynamic resource allocation: use patches or server-side-apply for updates

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113700]
### What would you like to be added?

The initial pkg/scheduler/framework/plugin/dynamicresources code use Update to modify objects. It should use patches or (once supported by client-go fake) server-side-apply.

Same for pkg/controller/resourceclaim/controller.go.

### Why is this needed?

Better performance.

**Comment by pohly** [comment]
/sig node
/priority important-longterm

This is blocked by work that needs to be done for client-go fake: https://kubernetes.slack.com/archives/C0EG7JC6T/p1666962144381369

**Comment by pohly** [comment]
During `scheduler_perf`, processing spec and status updates for PodSchedulingContext is responsible for most of the consumed CPU time in the test binary (i.e. scheduler, apiserver, and test client).

I tried with server-side-apply and the situation got *worse*. Such patch operations might be cheaper in terms of network traffic, but processing got more expensive.

**Comment by pohly** [comment]
Performance becomes acceptable when replacing the generic field manager in the API server with specific code for PodSchedulingContext.

**Comment by pohly** [comment]
> This is blocked by work that needs to be done for client-go fake:

The issue in client-go is still open, but I solved this for PodSchedulingContext with some custom reactor.

> Performance becomes acceptable when replacing the generic field manager in the API server with specific code for PodSchedulingContext.

After testing this some more I am not so certain about that anymore. See commit messages in https://github.com/pohly/kubernetes/commits/dra-performance-2023-08-30.

What we really want is patching that is faster across the board (i.e. all percentiles and test cases). I suspect that protobuf encoding of ApplyConfigurations will be needed for that, which is some heavy lifting.

Let's put this aside for now.

**Comment by apelisse** [comment]
I don't have the time to immediately work on SSA performance right now, so I would work around it if you can for now.

**Comment by pohly** [comment]
All relevant places have been converted to use patching.
