### ISSUE TITLE
Enhancement: Vertical node scaling

### ISSUE THREAD

**Issue by Karthik-K-N** [kubernetes/kubernetes#113715]
### What would you like to be added?

Enable vertical scaling of nodes, add the ability to update the nodes capacity specs without needing to restart the kubelet service in case of change in underlying machine capacity spec.

### Why is this needed?

If virtual machines support live upgrades of machines specs like memory and cpu without restart or shutdown  and if we want to utilize this feature currently we need to restart the kubelet to see the change in nodes specs.

The vertical scaling would help in environment where creating a new machines takes longer time compared to increasing the capacity of the current machine.

**Comment by Karthik-K-N** [comment]
I would like to work on this, would like to know community opinion and guidance

**Comment by Karthik-K-N** [comment]
I could see machine details being read [here](https://github.com/Karthik-K-N/kubernetes/blob/98742f9d77a57aec44cc05b1daf721973fb029be/pkg/kubelet/kubelet.go#L576).

Since its cloud specific can we extend [cloud interface](https://github.com/Karthik-K-N/cloud-provider-powervs/blob/b837d22cbf582ed97b78ff6fe63cd601977863ef/vendor/k8s.io/cloud-provider/cloud.go#L42-L69) to have methods to gather cpu and memory details

Or is there any better way to handle this.

**Comment by Karthik-K-N** [comment]
@mkumatag @SergeyKanzhelev  would like to know your opinion here.

**Comment by mkumatag** [comment]
> I could see machine details being read [here](https://github.com/Karthik-K-N/kubernetes/blob/98742f9d77a57aec44cc05b1daf721973fb029be/pkg/kubelet/kubelet.go#L576).
> 
> Since its cloud specific can we extend [cloud interface](https://github.com/Karthik-K-N/cloud-provider-powervs/blob/b837d22cbf582ed97b78ff6fe63cd601977863ef/vendor/k8s.io/cloud-provider/cloud.go#L42-L69) to have methods to gather cpu and memory details
> 
> Or is there any better way to handle this.

What if the resources got changed via some other mean and doesn't support the cloud-provider.

**Comment by Karthik-K-N** [comment]
> > I could see machine details being read [here](https://github.com/Karthik-K-N/kubernetes/blob/98742f9d77a57aec44cc05b1daf721973fb029be/pkg/kubelet/kubelet.go#L576).
> > Since its cloud specific can we extend [cloud interface](https://github.com/Karthik-K-N/cloud-provider-powervs/blob/b837d22cbf582ed97b78ff6fe63cd601977863ef/vendor/k8s.io/cloud-provider/cloud.go#L42-L69) to have methods to gather cpu and memory details
> > Or is there any better way to handle this.
> 
> What if the resources got changed via some other mean and doesn't support the cloud-provider.

Yeah possible .

**Comment by SergeyKanzhelev** [comment]
when this was last discussed, not only kubelet restart is needed, but often a full re-registration of a node with the API server. I cannot find discussion notes written with the quick search. Some docs are here: https://kubernetes.io/docs/concepts/architecture/nodes/#node-name-uniqueness

The main reason is that node characteristics may be cached in numerous controllers and the biggest issue will be to catch all places that needs to be changed with the new assumption that the node capacity may change. And find all possible races in controllers while things are being scheduled. This BTW is also a reason that the kube reserved is not dynamic.

One workaround for this is scheduling a balloon pod on every node that will claim all resources that are not allocated on the node yet, but can be allocated later with the VM resize.

If you want to drive this enhancement forward, the best place is to file it under https://github.com/kubernetes/enhancements/ with the proposed design to collect feedback on it. But this will be a change that is far beyond SIG Node.

/sig scheduling
/sig architecture

I will close this issue as the best place to track this improvement is in enhancements repo. Please re-open if you have more thoughts to share or I missed anything

/close
