### ISSUE TITLE
informers: provide a way to know when a resource handler has "synced"

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#113763]
Currently, informers expose a `HasSynced` method.
This asserts that one full List has been synced to the informers *store*.

However, this does not give any guarantees about *handlers* being called.

It is fairly common to need to know that the handlers have been called for the initial state.
However, there is currently no way to access this.

Slack context: https://kubernetes.slack.com/archives/C0EG7JC6T/p1591115369066700

## Sync state

A common question is "What happens if an object is created during the initial sync? Why would we care about the initial state specifically?"

The issue is one of eventually consistency. If I apply, say, a NetworkPolicy, it may not be actuated for some time - its perfectly reasonable for a controller to not process it for O(seconds). However, if I apply a NetworkPolicy 1 year ago, then restart my controller, it *must* be applied; a small blip in policy enforcement is a CVE. A correct controller implementation needs to ensure the initial state is fully synced before operating.

## Current solutions

* The naive option is to just use `informer.HasSynced`. This works if controllers are operating under Listers (or similar) only, rather than event handlers, as the `HasSynced` applies to the underlying store. This is *close enough* that many controllers probably do this while relying on event handlers, improperly, and don't notice that in rare cases the event handlers lag behind.

  Example (broken) implementation:

  <details>

  ```go
  func TestInformerRace(t *testing.T) {
    kc := fake.NewSimpleClientset(pods...)
    informers := informers.NewSharedInformerFactory(kc, 0)
    handled := &atomic.Int32{}
    podInformer := informers.Core().V1().Pods().Informer()
    podInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
      AddFunc: func(obj any) {
        handled.Add(1)
      },
    })

    stop := make(chan struct{})
    informers.Start(stop)
    WaitForInformerFactorySync(stop, informers)
    WaitForCacheSync(stop, podInformer.HasSynced)

    if h := handled.Load(); h != int32(len(pods)) {
      t.Fatalf("got %+v events, expected %v", h, len(pods))
    }
  }
  ```

  </details>

* After syncing, list all objects. Record all objects we handle, and make sure everything in the initial List call was handled.

	Example (broken) implementation:

  <details>

  ```go
  func TestInformerRaceList(t *testing.T) {
    kc := fake.NewSimpleClientset(pods...)
    informers := informers.NewSharedInformerFactory(kc, 0)
    handled := &atomic.Int32{}
    mu := sync.RWMutex{}
    seenEvents := sets.NewString()
    podInformer := informers.Core().V1().Pods().Informer()
    podInformer.AddEventHandler(cache.ResourceEventHandlerFuncs{
      AddFunc: func(obj any) {
        if k, err := cache.MetaNamespaceKeyFunc(obj); err == nil {
          mu.Lock()
          seenEvents.Insert(k)
          mu.Unlock()
        }
        handled.Add(1)
      },
    })

    stop := make(chan struct{})
    informers.Start(stop)
    WaitForInformerFactorySync(stop, informers)
    WaitForCacheSync(stop, podInformer.HasSynced)

    wantEvents := sets.NewString()
    for _, v := range podInformer.GetStore().List() {
      if k, err := cache.MetaNamespaceKeyFunc(v); err == nil {
        wantEvents.Insert(k)
      }
    }
    for {
      mu.RLock()
      wantEvents = wantEvents.Difference(seenEvents)
      mu.RUnlock()
      if len(wantEvents) == 0 {
        break
      }
      time.Sleep(time.Millisecond)
    }

    if h := handled.Load(); h != int32(len(pods)) {
      t.Fatalf("got %+v events, expected %v", h, len(pods))
    }
  }
  ```

  </details>

  Problems:
	* This is complex and somewhat expensive to maintain
	* It suffers its own race; the List() call may not be the initial set. For example, if a resource was Deleted before the List() call, we may miss the event for that

* After syncing, call List(). For each item, call the handler with that event

  Real world example: https://github.com/kubernetes/kubernetes/blob/e6df935fd30c56a8ece0da6152c60fc725d942b7/pkg/controlplane/controller/crdregistration/crdregistration_controller.go#L120

  Example implementation (not broken, but only works in some cases):

  <details>

  ```go
  func TestInformerRaceListRehandler(t *testing.T) {
    kc := fake.NewSimpleClientset(pods...)
    informers := informers.NewSharedInformerFactory(kc, 0)
    handled := &atomic.Int32{}
    podInformer := informers.Core().V1().Pods().Informer()
    handler := cache.ResourceEventHandlerFuncs{
      AddFunc: func(obj any) {
        handled.Add(1)
      },
    }
    podInformer.AddEventHandler(handler)

    stop := make(chan struct{})
    informers.Start(stop)
    WaitForInformerFactorySync(stop, informers)
    WaitForCacheSync(stop, podInformer.HasSynced)

    for _, v := range podInformer.GetStore().List() {
      handler.OnAdd(v)
    }

    if h := handled.Load(); h < int32(len(pods)) {
      t.Fatalf("got %+v events, expected %v", h, len(pods))
    }
  }
  ```

  </details>

  Problems:
	* Performs poorly; each item is handled multiple times, which may be expensive
	* Only really works for some handler types. The above example is essentially broken; we may be calling an Add event, but a real Delete event came in between; we end up with the wrong state. It *does* work with the fairly common pattern of enqueuing a name on a queue and then reconciling the current state, but this is not something that is done everywhere.

* Bespoke logic. There are many other ways to try to solve this problem. One such example is in the in-tree mutatingWebhookConfigurationManager (which is incorrect, but would be trivially solved by the addition of changes in this PR: https://github.com/kubernetes/kubernetes/issues/113761)

## Proposed solution

Ultimately, the ask is to expose a mechanism to know that a *handler* has been called for the initial state.

From an API perspective, this could be exposed at the Informer level, or the handler level. While the Informer level is more intuitive from an API perspective, it is a bit odd to ask "Have all handlers been synced"; most callers only care about *their* handler. However, there is not currently a way to access a specific handler in the API today, so its tricky to expose a `handler.HasSynced()` function, or similar.

### Determining when a handler is synced

Ultimately, the point in the code where we disconnect from the underlying store knowing it has synced but the handler not being synced is in processorListener. In `processorListener.add`, we send on `addCh`, which then basically acts as an unbounded ring buffer between `nextCh`. The important part is it is asynchronous, which is why all of our problems exists.

**Option 1: Make processorListener synchronous**

Presumably, this is async because we expect handlers may be slow. However, I think there is some general guidance that handlers should be fast (this is why most handlers are just `Enqueue()`) (although I couldn't find this written down anywhere...). Because of that, it may be feasible to just make `processorListener` synchronous.

From a code standpoint, this is pretty simple:

```diff
@@ -770,7 +802,19 @@ func newProcessListener(handler ResourceEventHandler, requestedResyncPeriod, res
 }

 func (p *processorListener) add(notification interface{}) {-
-       p.addCh <- notification
+       switch notification := notification.(type) {
+       case updateNotification:
+               p.handler.OnUpdate(notification.oldObj, notification.newObj)
+       case addNotification:
+               p.handler.OnAdd(notification.newObj)
+       case deleteNotification:
+               p.handler.OnDelete(notification.oldObj)
+       default:
+               utilruntime.HandleError(fmt.Errorf("unrecognized notification: %T", notification))
+       }
 }
```

However, in practice this may have fairly substantial impacts and unknown-unknowns. Its plausible this could be an explicit opt-in, though, to mitigate backwards compatibility.

By making this synchronous, we put processorListener, and thus the handler, under the same semantics as the underlying Store syncing (as handled by `processDeltas`), which means `informer.HasSynced()` will now ensure that both the underlying Store is synced to the initial state *and* the handler has been called for the initial state.

Informer users would then just the current "naive solution" of calling `informer.HasSynced()`.

**Option 2: Expose a processorListener.HasSynced method**

This option would involve exposing a way for a processorListener to instead explicitly report whether it has synced full or not (but still processes events async).

The current interface between DeltaFIFO (the thing that knows when we are synced) and processorListener (the thing we want to know) interfaces through `sharedIndexInformer.OnAdd` which calls `s.processor.distribute`. In order to propagate the state between these, we need to expose a bit more information through these interfaces.

One possible option is like below:

<details>

```diff
diff --git a/fork/gohack/k8s.io/client-go/tools/cache/controller.go b/fork/gohack/k8s.io/client-go/tools/cache/controller.go
index 0762da3..d40fb2b 100644
--- a/fork/gohack/k8s.io/client-go/tools/cache/controller.go
+++ b/fork/gohack/k8s.io/client-go/tools/cache/controller.go
@@ -84,7 +85,7 @@ type Config struct {
 type ShouldResyncFunc func() bool
 
 // ProcessFunc processes a single object.
-type ProcessFunc func(obj interface{}) error
+type ProcessFunc func(obj interface{}, synced bool) error
 
 // `*controller` implements Controller
 type controller struct {
@@ -413,6 +414,7 @@ func processDeltas(
 	clientState Store,
 	transformer TransformFunc,
 	deltas Deltas,
+	sync bool,
 ) error {
 	// from oldest to newest
 	for _, d := range deltas {
@@ -445,9 +447,21 @@ func processDeltas(
 			handler.OnDelete(obj)
 		}
 	}
+	if sync {
+		if not, ok := handler.(Notifer); ok {
+			not.Notify()
+		}
+	}
 	return nil
 }
 
+type Notifer interface {
+	Notify()
+}
+
 // newInformer returns a controller for populating the store while also
 // providing event notifications.
 //
@@ -484,9 +498,9 @@ func newInformer(
 		FullResyncPeriod: resyncPeriod,
 		RetryOnError:     false,
 
-		Process: func(obj interface{}) error {
+		Process: func(obj interface{}, sync bool) error {
 			if deltas, ok := obj.(Deltas); ok {
-				return processDeltas(h, clientState, transformer, deltas)
+				return processDeltas(h, clientState, transformer, deltas, sync)
 			}
 			return errors.New("object given as Process argument is not Deltas")
 		},
diff --git a/fork/gohack/k8s.io/client-go/tools/cache/controller_test.go b/fork/gohack/k8s.io/client-go/tools/cache/controller_test.go
index cf42478..67c53eb 100644
--- a/fork/gohack/k8s.io/client-go/tools/cache/controller_test.go
+++ b/fork/gohack/k8s.io/client-go/tools/cache/controller_test.go
@@ -62,7 +62,7 @@ func Example() {
 
 		// Let's implement a simple controller that just deletes
 		// everything that comes in.
-		Process: func(obj interface{}) error {
+		Process: func(obj interface{}, sync bool) error {
 			// Obj is from the Pop method of the Queue we make above.
 			newest := obj.(Deltas).Newest()
 
diff --git a/fork/gohack/k8s.io/client-go/tools/cache/delta_fifo.go b/fork/gohack/k8s.io/client-go/tools/cache/delta_fifo.go
index 0c13a41..423f70f 100644
--- a/fork/gohack/k8s.io/client-go/tools/cache/delta_fifo.go
+++ b/fork/gohack/k8s.io/client-go/tools/cache/delta_fifo.go
@@ -529,9 +537,14 @@ func (f *DeltaFIFO) Pop(process PopProcessFunc) (interface{}, error) {
 		id := f.queue[0]
 		f.queue = f.queue[1:]
 		depth := len(f.queue)
+		isSync := false
 		if f.initialPopulationCount > 0 {
 			f.initialPopulationCount--
+			if f.initialPopulationCount == 0 {
+				isSync = true
+			}
 		}
+
 		item, ok := f.items[id]
 		if !ok {
 			// This should never happen
@@ -551,7 +564,7 @@ func (f *DeltaFIFO) Pop(process PopProcessFunc) (interface{}, error) {
 				utiltrace.Field{Key: "Reason", Value: "slow event handlers blocking the queue"})
 			defer trace.LogIfLong(100 * time.Millisecond)
 		}
-		err := process(item)
+		err := process(item, isSync)
 		if e, ok := err.(ErrRequeue); ok {
 			f.addIfNotPresent(id, item)
 			err = e.Err
diff --git a/fork/gohack/k8s.io/client-go/tools/cache/fifo.go b/fork/gohack/k8s.io/client-go/tools/cache/fifo.go
index 8f33137..08531e1 100644
--- a/fork/gohack/k8s.io/client-go/tools/cache/fifo.go
+++ b/fork/gohack/k8s.io/client-go/tools/cache/fifo.go
@@ -25,7 +25,7 @@ import (
 
 // PopProcessFunc is passed to Pop() method of Queue interface.
 // It is supposed to process the accumulator popped from the queue.
-type PopProcessFunc func(interface{}) error
+type PopProcessFunc func(interface{}, bool) error
 
 // ErrRequeue may be returned by a PopProcessFunc to safely requeue
 // the current item. The value of Err will be returned from Pop.
@@ -84,7 +84,7 @@ type Queue interface {
 // unless you really really really really know what you are doing.
 func Pop(queue Queue) interface{} {
 	var result interface{}
-	queue.Pop(func(obj interface{}) error {
+	queue.Pop(func(obj interface{}, _ bool) error {
 		result = obj
 		return nil
 	})
@@ -289,8 +289,12 @@ func (f *FIFO) Pop(process PopProcessFunc) (interface{}, error) {
 		}
 		id := f.queue[0]
 		f.queue = f.queue[1:]
+		isSync := false
 		if f.initialPopulationCount > 0 {
 			f.initialPopulationCount--
+			if f.initialPopulationCount == 0 {
+				isSync = true
+			}
 		}
 		item, ok := f.items[id]
 		if !ok {
@@ -298,7 +302,7 @@ func (f *FIFO) Pop(process PopProcessFunc) (interface{}, error) {
 			continue
 		}
 		delete(f.items, id)
-		err := process(item)
+		err := process(item, isSync)
 		if e, ok := err.(ErrRequeue); ok {
 			f.addIfNotPresent(id, item)
 			err = e.Err
diff --git a/fork/gohack/k8s.io/client-go/tools/cache/shared_informer.go b/fork/gohack/k8s.io/client-go/tools/cache/shared_informer.go
index 9f42782..ac7ef2b 100644
--- a/fork/gohack/k8s.io/client-go/tools/cache/shared_informer.go
+++ b/fork/gohack/k8s.io/client-go/tools/cache/shared_informer.go
@@ -357,6 +359,9 @@ func (v *dummyController) LastSyncResourceVersion() string {
 	return ""
 }
 
+type syncNotification struct {
+}
+
 type updateNotification struct {
 	oldObj interface{}
 	newObj interface{}
@@ -563,12 +576,12 @@ func (s *sharedIndexInformer) AddEventHandlerWithResyncPeriod(handler ResourceEv
 	}
 }
 
-func (s *sharedIndexInformer) HandleDeltas(obj interface{}) error {
+func (s *sharedIndexInformer) HandleDeltas(obj interface{}, sync bool) error {
 	s.blockDeltas.Lock()
 	defer s.blockDeltas.Unlock()
 
 	if deltas, ok := obj.(Deltas); ok {
-		return processDeltas(s, s.indexer, s.transform, deltas)
+		return processDeltas(s, s.indexer, s.transform, deltas, sync)
 	}
 	return errors.New("object given as Process argument is not Deltas")
 }
@@ -581,6 +594,11 @@ func (s *sharedIndexInformer) OnAdd(obj interface{}) {
 	s.processor.distribute(addNotification{newObj: obj}, false)
 }
 
+func (s *sharedIndexInformer) Notify() {
+	s.processor.distribute(syncNotification{}, false)
+}
+
 // Conforms to ResourceEventHandler
 func (s *sharedIndexInformer) OnUpdate(old, new interface{}) {
 	isSync := false
@@ -752,6 +782,7 @@ type processorListener struct {
 	nextResync time.Time
 	// resyncLock guards access to resyncPeriod and nextResync
 	resyncLock sync.Mutex
+	synced     *atomic.Bool
 }
 
 func newProcessListener(handler ResourceEventHandler, requestedResyncPeriod, resyncPeriod time.Duration, now time.Time, bufferSize int) *processorListener {
@@ -762,6 +793,7 @@ func newProcessListener(handler ResourceEventHandler, requestedResyncPeriod, res
 		pendingNotifications:  *buffer.NewRingGrowing(bufferSize),
 		requestedResyncPeriod: requestedResyncPeriod,
 		resyncPeriod:          resyncPeriod,
+		synced:                &atomic.Bool{},
 	}
 
 	ret.determineNextResync(now)
@@ -811,6 +855,7 @@ func (p *processorListener) run() {
 	stopCh := make(chan struct{})
 	wait.Until(func() {
 		for next := range p.nextCh {
 			switch notification := next.(type) {
 			case updateNotification:
 				p.handler.OnUpdate(notification.oldObj, notification.newObj)
@@ -818,6 +863,8 @@ func (p *processorListener) run() {
 				p.handler.OnAdd(notification.newObj)
 			case deleteNotification:
 				p.handler.OnDelete(notification.oldObj)
+			case syncNotification:
+				p.synced.Store(true)
 			default:
 				utilruntime.HandleError(fmt.Errorf("unrecognized notification: %T", next))
 			}
```

</details>

Essentially, DeltaFIFO knows when it is processing the last item to be fully synced. When it encounters this, it propogates some additional info through to the processorListener. When the processorListener processes the `syncNotification`, it marks itself as synced.

### Exposing if a handler was synced

Fundamentally, most clients will want to be able to answer "Has *my* handler synced"; they don't care about "Have *all handlers registered* for the informer synced". Depending on our implementation, this may guide our API decision.

The easy approach is to just expose this at the informer level (either modify `HasSynced` semantics, or more likely add a new `HaveAllHandlersSynced`). For "Option 1" above, this is really our only option because `informer.HasSynced` implies `informer.HaveAllHandlersSynced`. For "Option 2" above, we could chose to expose it on a per handler basis or aggregate all handlers and expose it at a listener level.

The issue with exposing it at a handler level is there is not an existing API interface to hang this new function on. `AddEventHandler` just takes a ResourceEventHandler and returns nothing. We could add alternative function calls that either take in or return some callback for HasSynced, though; there is some prior are for alternative functions here with `AddEventHandlerWithResyncPeriod`.

If we don't want to change the API shape at all, we could also keep the existing API, but add a new `ResourceEventHandlerWithSyncedCallback` which would have a new function added, then see if the passed in handler implements that and register the callback that way. However, I think doing this is generally frowned upon.

/sig api-machinery
cc @liggitt @robscott @stevenctl

**Comment by lavalamp** [comment]
[This](https://github.com/kubernetes/kubernetes/blob/3f823c0daa002158b12bfb2d53bcfe433516659d/staging/src/k8s.io/client-go/tools/cache/controller.go#L184) is where the existing code loses track of whether things have synced or not.

My first idea is to just modify this process function definition to make it pass a second parameter, `isInInitialList`: https://github.com/kubernetes/kubernetes/blob/3f823c0daa002158b12bfb2d53bcfe433516659d/staging/src/k8s.io/client-go/tools/cache/controller.go#L87

I think that will solve one layer of the problem, I'll probably just try it and let the compiler tell me how involved that will be.

**Comment by lavalamp** [comment]
I started #113985 to explore this, it seems easy to change the informer/fifo code, unclear how hard it will be to update controllers or if this interface change is acceptable or not.

**Comment by alculquicondor** [comment]
kube-scheduler also needs this to reliably schedule pods. Currently, it is possible that we start scheduling before adding all nodes or pods into the scheduler cache/snapshot. That can lead to pods scheduled into non-optimal nodes in the best case, or oversubscribe nodes in the worst case.

**Comment by eahydra** [comment]
> kube-scheduler also needs this to reliably schedule pods. Currently, it is possible that we start scheduling before adding all nodes or pods into the scheduler cache/snapshot. That can lead to pods scheduled into non-optimal nodes in the best case, or oversubscribe nodes in the worst case.

The size of our internal cluster is very large and we encountered this kind of problem. In order to solve this problem, some of our internal components list all the data and do some initialization logic after the Informer synchronization is completed.
Some scheduling plugins need to maintain some state by themselves to achieve some efficient scheduling capabilities, and some complex plugins require multiple Informers to construct these states, and it is also expected to have such a synchronization mechanism to ensure the correctness of the state.

**Comment by howardjohn** [comment]
Here is how we ended up using this btw:

https://github.com/istio/istio/blob/17f494092f5f6c8fbfc48de09551fb0725d8edde/pkg/kube/kclient/client.go#L155-L168

Small wrapper around Informer that keeps track of the handlers added via the wrapper and waits for them as part of HasSynced.

Thanks for all the help here!

**Comment by lavalamp** [comment]
@howardjohn glad it's working for you!

**Comment by HeGaoYuan** [comment]
watching
