### ISSUE TITLE
AWS scripts should verify IAM configuration

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11373]
Whenever we change IAM policy, we risk breaking people in subtle ways that don't have the new IAM policy, because we only check that the IAM policy exists, we don't check that it matches what we want.  I have been doing this because I thought people might want to add extra permissions to their IAM policy.  I now think this is wrong: the far more common case is that we add something to the policy and we don't update our original users.  Hopefully this will happen less and less, but I think it will continue to happen.

I think we should therefore declare that we "own" the IAM policy and will update it; if users want to add additional permissions they can do that in a second attached policy, I believe.

We should also look at whether we should create a policy per kubernetes clusters, rather than sharing one.  This would allow the policy to be locked down even further (e.g. by resource name).

**Comment by jpooler** [comment]
If you create it, you should own it. Basic rule.

I was bit by this and at the least it there could be a warning message to check the role. I didn't know someone had tried to launch kubernetes in our env months back, so the role was old. Why doesn't kube-down.sh remove the role?!? It cleans up *everything* else.

**Comment by justinsb** [comment]
Yes, this is annoying I agree!

The reason it doesn't delete it is because the IAM role is shared between all Kubernetes clusters.  So deleting it would likely be problematic unless it was your last cluster.

Of course, sharing the IAM role is actually the really bad idea here.  (My bad idea).

Another wrinkle is that in theory you could modify the IAM policy to grant more permissions (or remove some).

I agree that the cluster should own the role, the cluster should delete it, and think that we should have one per cluster.  My intent was to have Kubernetes own the policy also, and it would warn / repair the policy if it was a mismatch.  If you wanted to add policy you would attach a second policy to the role, which would then _not_ be managed by k8s.  Not sure if we should create an empty 'stub' policy to encourage people here.

@jpooler  As someone with strong opinions ;-) - does this sound right?

**Comment by jpooler** [comment]
Sorry for the curtness of my post, I should have proofread it for snark and tone. 

Yea, that sounds like a good idea! One role per cluster is definitely viable, the only concern would be if someone wanted to spin up 125 kubernetes clusters in one AWS account, since that would then hit the AWS role limit of 250. 

Again, sorry for my rudeness @justinsb !

**Comment by justinsb** [comment]
This is fixed in kops.  We're not making further changes to kube-up, so closing.
