### ISSUE TITLE
dynamic resource allocation: add DRA-managed resources to the PodResources API

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#113783]
### What would you like to be added?

The `PodResources` API is used to query the full set of resources allocated to a pod and make them available to metrics servers, CNI plugins, etc.

With the introduction of DRA, we should also include the resources it manages as part of this API.

### Why is this needed?

To allow metrics servers, CNI plugins, and the like to discover the set of DRA managed resources allocated to a pod.

**Comment by fromanirh** [comment]
/triage accepted
I agree adding support for DRA makes sense for podresources API

**Comment by klueska** [comment]
Completed by:
https://github.com/kubernetes/enhancements/issues/3695
