### ISSUE TITLE
encryption-at-rest: use atomic.Pointer to store dynamic transformers

### ISSUE THREAD

**Issue by nilekhc** [kubernetes/kubernetes#113759]
Ref:- https://github.com/kubernetes/kubernetes/pull/112050#discussion_r1016791814

We will also have to do some benchmarking to ensure perf cost between the current implementation and this approach to make sure we are being benefited from atomic.Pointers.

**Comment by enj** [comment]
/retitle encryption-at-rest: use atomic.Pointer to store dynamic transformers

**Comment by aramase** [comment]
> We will also have to do some benchmarking to ensure perf cost between the current implementation and this approach to make sure we are being benefited from atomic.Pointers.

As discussed in the KMSv2 meeting today, we should use `atomic.Pointer` and benchmarking isn't required.
