### ISSUE TITLE
dynamic resource allocation: optimize class.SuitableNodes usage

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113703]
### What would you like to be added?

The node selectors gets parsed  by `corev1helpers.MatchNodeSelectorTerms(node, class.SuitableNodes)` in `Filter` for each node. That work can be done once in `PreFilter`.

### Why is this needed?

Better performance.

**Comment by kidddddddddddddddddddddd** [comment]
I can try this one.
/assign
