### ISSUE TITLE
dynamic resource allocation: use generated name for ResourceClaim from template

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113722]
### What would you like to be added?

Right now, the name is specified as `<pod name>-<claim source name inside pod spec>`. That's easy and deterministic, but may lead to conflicts with ResourceClaims that were created earlier, either automatically or manually.

Let's investigate the alternative: generate the name and let code which needs to know it search the API server or in a local cache via some label.

### Why is this needed?

Avoids conflicts.

**Comment by liggitt** [comment]
a couple downsides of generated names:
* the kubelet doesn't know what claim object it should `get`
* the node authorizer doesn't have a deterministic way to know what resource claims to allow a kubelet to get based solely on the info in the pod (related to https://github.com/kubernetes/kubernetes/issues/113866)

**Comment by pohly** [comment]
Right now, a hyphen is allowed in the claim name that is concatenated with the pod name to produce a claim name. If we stick with the current approach and don't generate names, then we should tighten validation and not allow that. This is probably still possible, because alpha, but may need some extra care like accepting it in existing objects? TBD.

**Comment by liggitt** [comment]
while in alpha, just tightening with a release note is fair game, in my opinion.
