### ISSUE TITLE
[Failing test] capz-windows-containerd-1.24

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#113782]
### Which jobs are failing?

[sig-release-1.24-informing](https://testgrid.k8s.io/sig-release-1.24-informing)

- [capz-windows-containerd-1.24](https://testgrid.k8s.io/sig-release-1.24-informing#capz-windows-containerd-1.24)

### Which tests are failing?

- Kubernetes e2e suite: [sig-node] Probing container should *not* be restarted with a GRPC liveness probe [NodeConformance]
- Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
- Kubernetes e2e suite: [sig-node] Probing container should be restarted with a GRPC liveness probe [NodeConformance]

### Since when has it been failing?

10/22

Last successful run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-1-24/1583729475143602176
First failed run: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows-1-24/1583774773534527488

### Testgrid link

https://testgrid.k8s.io/sig-release-1.24-informing#capz-windows-containerd-1.24

### Reason for failure (if possible)

- Kubernetes e2e suite: [sig-node] Probing container should *not* be restarted with a GRPC liveness probe [NodeConformance]
    ```
    { Failure test/e2e/common/node/container_probe.go:528
    Nov  9 09:35:42.284: starting pod test-grpc-30909319-caa6-4bd9-be35-04e4966b09bc in namespace container-probe-1344
    Unexpected error:
        <*errors.errorString | 0xc000206280>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred
    test/e2e/common/node/container_probe.go:901}
    ```
- Kubernetes e2e suite: [sig-api-machinery] Aggregator Should be able to support the 1.17 Sample API Server using the current Aggregator [Conformance]
    ```
    { Failure test/e2e/framework/framework.go:652
    Nov  9 09:45:04.145: deploying extension apiserver in namespace aggregator-4934
    Unexpected error:
        <*errors.errorString | 0xc00335f5b0>: {
            s: "error waiting for deployment \"sample-apiserver-deployment\" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:\"Available\", Status:\"False\", LastUpdateTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), Reason:\"MinimumReplicasUnavailable\", Message:\"Deployment does not have minimum availability.\"}, v1.DeploymentCondition{Type:\"Progressing\", Status:\"True\", LastUpdateTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), Reason:\"ReplicaSetUpdated\", Message:\"ReplicaSet \\\"sample-apiserver-deployment-5ffcbb777d\\\" is progressing.\"}}, CollisionCount:(*int32)(nil)}",
        }
        error waiting for deployment "sample-apiserver-deployment" status to match expectation: deployment status: v1.DeploymentStatus{ObservedGeneration:1, Replicas:1, UpdatedReplicas:1, ReadyReplicas:0, AvailableReplicas:0, UnavailableReplicas:1, Conditions:[]v1.DeploymentCondition{v1.DeploymentCondition{Type:"Available", Status:"False", LastUpdateTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), Reason:"MinimumReplicasUnavailable", Message:"Deployment does not have minimum availability."}, v1.DeploymentCondition{Type:"Progressing", Status:"True", LastUpdateTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), LastTransitionTime:time.Date(2022, time.November, 9, 9, 40, 3, 0, time.Local), Reason:"ReplicaSetUpdated", Message:"ReplicaSet \"sample-apiserver-deployment-5ffcbb777d\" is progressing."}}, CollisionCount:(*int32)(nil)}
    occurred
    test/e2e/apimachinery/aggregator.go:322}
    ```
- Kubernetes e2e suite: [sig-node] Probing container should be restarted with a GRPC liveness probe [NodeConformance]
    ```
    { Failure test/e2e/common/node/container_probe.go:551
    Nov  9 09:39:27.763: starting pod test-grpc-5ca8cdc6-d6d6-4d5e-980d-4f533cd1343f in namespace container-probe-1416
    Unexpected error:
        <*errors.errorString | 0xc0001fe280>: {
            s: "timed out waiting for the condition",
        }
        timed out waiting for the condition
    occurred
    test/e2e/common/node/container_probe.go:901}
    ```

### Anything else we need to know?

We recently had another issue where tests failed to start because of an unsupported Go version:

```
make: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure'
Detected go version: go version go1.18.8 linux/amd64.
Kubernetes requires go1.19.0 or greater.
Please install go1.19.0 or later.
```

This issue has been fixed yesterday with https://github.com/kubernetes/test-infra/pull/27934

### Relevant SIG(s)

/sig windows
cc @kubernetes/ci-signal

**Comment by dims** [comment]
cc @jsturtevant @CecileRobertMichon @marosset

**Comment by marosset** [comment]
/assign
We need to get a new edtc image into the WIndows container registry used by the pre-1.25 Windows jobs.

**Comment by marosset** [comment]
I mirrored `registry.k8s.io/etcd:3.5.5-0` into `k8sprow.azurecr.io/kubernetes-e2e-test-images/etcd:3.5.5-0` and the jobs are now passing.

/close
