### ISSUE TITLE
Projected ConfigMap Update Delay

### ISSUE THREAD

**Issue by rphillips** [kubernetes/kubernetes#113746]
### What happened?

Recent Kubernetes versions (1.25, 1.24 and main) exhibit a delay on ConfigMap update for the time taken to render the changes to the volume on the filesystem. Recent test [runs](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-e2e-gce/1589654264869818368) (`Projected configMap updates should be reflected in volume`) display a time of upwards to 1m to update the projected volume on the filesystem.

The delay is noticeable and can be improved. Ideally, a ConfigMap update should take around ~10s.

Related Issues:
https://github.com/kubernetes/kubernetes/pull/104309

### What did you expect to happen?

I expect a ConfigMap update within the API to be rendered to the filesystem within a pod within around 10s.

### How can we reproduce it (as minimally and precisely as possible)?

CI is exhibiting the issue with the `Projected configMap updates should be reflected in volume` test.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.25, 1.24, main
</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
it doesn't look like a regression.

/priority important-longterm
/triage accepted

**Comment by ruquanzhao** [comment]
/unassign
Anyone interested please take over

**Comment by kannon92** [comment]
Chatting with @rphillips, I don't think this is relevant anymore.

/close
