### ISSUE TITLE
encryption-at-rest: add success or failure metric when encryption configuration attempts to dynamically update

### ISSUE THREAD

**Issue by nilekhc** [kubernetes/kubernetes#113704]
ref - https://github.com/kubernetes/kubernetes/pull/112050#discussion_r1015894772

/sig auth

**Comment by enj** [comment]
/retitle "encryption-at-rest: add success or failure metric when encryption configuration attempts to dynamically update"

**Comment by enj** [comment]
/retitle encryption-at-rest: add success or failure metric when encryption configuration attempts to dynamically update
