### ISSUE TITLE
Is there any way to assign pods to nodes manually?

### ISSUE THREAD

**Issue by kangsan0420** [kubernetes/kubernetes#113770]
I have only 2 nodes so that I want full-track of pods.

Can I set specific number of replicas for each node in one deployment? (e.g. 2 replicas on node-1 & 3 replicas on node-2) 

I tried:
node affinity: can't adjust number of replicas for each node.
pod anti-affinity: can't assign multiple pods for single node.

It seems not possible to use node affinity and pod anti-affinity simultaneously.

**Comment by knight42** [comment]
I am afraid this cannot be done by only one Deployment. Perhaps you could try create two Deployments and specify the nodeSelector in both of them.

**Comment by pacoxu** [comment]
So what is your motivation?

- Do you want pods to be scheduled in different nodes to cross failure domains? If so, topology spread constraints may help.
- Or you want to set a big map(more than 2 nodes and custom replica number in each node): 2 in nodeA; 3 in nodeB; 1 in nodeC... (This is not supported as https://github.com/kubernetes/kubernetes/issues/113770#issuecomment-1311187743. this should be a `/kind feature`).

As I know, Pod [topology spread constraints ](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/)can help to spread across your cluster among failure domains such as regions, zones, and nodes. 

This can only do something like 
1. all replicas in node list [a, b, c ...]: for instance two nodes: nodeA & nodeB
2. maxSkew: 1

For this setting above, if a deployment is with replica 5, there will be 2 pods in one node, and 3 pods in the other.
