### ISSUE TITLE
daemonset.status.desiredNumberScheduled=0 for some time in v1.26.0-beta.0

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#113844]
### What happened?

I test that daemonset.status.desiredNumberScheduled==daemonset.status.numberReady as part of my test-env start sequence. But in `v1.26.0-beta.0` (and master) daemonset.status.desiredNumberScheduled==0 for a fairly long time.

### What did you expect to happen?

I expect daemonset.status.desiredNumberScheduled to equals the number of nodes where the daemonset can be scheduled right from start.

This is the behaivor prior to v1.26.x.

### How can we reproduce it (as minimally and precisely as possible)?

Monitor daemonset.status.desiredNumberScheduled during start of a daemonset in `v1.26.0-beta.0`

### Anything else we need to know?

I can quite easily adapt my startup check to the described behaivor (I already have), but there may be others that would be taken by suprise.

It works as expected in v1.25.3 (I haven't tested v1.25.4).

### Kubernetes version

```
# kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.0-beta.0
Kustomize Version: v4.5.7
Server Version: v1.26.0-beta.0
```

### Cloud provider

None

### OS version

<details>

```
Linux 6.0.0 #4 SMP PREEMPT_DYNAMIC Tue Nov 8 15:43:41 CET 2022
```

</details>

### Install tools

None

### Container runtime (CRI) and version (if applicable)

crio version 1.25.0

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by uablrek** [comment]
It seems to be even worse. daemonset.status.desiredNumberScheduled can be set to any number <nodes on it's way to the correct value.

**Comment by uablrek** [comment]
For the record, I wait until all K8s nodes are "ready" _before_ performing this test.

**Comment by liggitt** [comment]
do you have controller manager logs or scheduler logs during that period of time you can provide? do you have a version of your daemonset manifest you could provide?

cc @soltysh @alculquicondor in case you know of changes to daemonset / scheduling in 1.26 that could be related

**Comment by alculquicondor** [comment]
/remove-sig scheduling
The scheduler is not involved in this calculation.

Maybe related to #112127, but it was reverted in #113733. I'm not sure if that's included in beta.0

I wasn't directly involved in the changes.

**Comment by alculquicondor** [comment]
@gjkim42 could you investigate?

**Comment by gjkim42** [comment]
Both #112717 and #113733 are included in beta.0.
I think it should be something else.

**Comment by liggitt** [comment]
Are your nodes being marked as schedulable more slowly in 1.26? Would that explain the delay/intermediate values seen in the status for this field?

**Comment by gjkim42** [comment]
```
$ while true; do k get daemonsets.apps -o custom-columns=NAME:.metadata.name,STATUS-DESIRED:.status.desiredNumberScheduled && sleep 1; done
NAME   STATUS-DESIRED
NAME   STATUS-DESIRED
NAME   STATUS-DESIRED
NAME   STATUS-DESIRED
NAME   STATUS-DESIRED
NAME    STATUS-DESIRED
nginx   4
NAME    STATUS-DESIRED
nginx   4
NAME    STATUS-DESIRED
nginx   4
NAME    STATUS-DESIRED
nginx   4
NAME    STATUS-DESIRED
nginx   4
```

made a simple test with creating a daemonset but the interval is at least less than 1s.

I think you may check taint - tolerations.

**Comment by uablrek** [comment]
> do you have a version of your daemonset manifest you could provide?

<details><summary>mserver-daemonset.yaml</summary>

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mserver
spec:
  selector:
    matchLabels:
      app: mserver
  template:
    metadata:
      labels:
        app: mserver
    spec:
      serviceAccount: default
      containers:
      - name: mserver
        imagePullPolicy: IfNotPresent
        image: registry.nordix.org/cloud-native/mserver:latest
        ports:
        - containerPort: 5001
        securityContext:
          privileged: true
```

</details>

**Comment by uablrek** [comment]
> Are your nodes being marked as schedulable more slowly in 1.26?

I am unsure. Before applying the daemonset manifest I check that all nodes are "Ready".
```
NAME     STATUS   ROLES    AGE   VERSION
vm-001   Ready    <none>   2s    v1.26.0-beta.0
vm-002   Ready    <none>   2s    v1.26.0-beta.0
vm-003   Ready    <none>   2s    v1.26.0-beta.0
vm-004   Ready    <none>   2s    v1.26.0-beta.0
```
But as you can see, this is _very early_ during cluster start-up. That may be a reason that I see this and it may be nothing that will bother others. As said, I have a work-around already so I am good.

**Comment by uablrek** [comment]
FYI, I start K8s from scripts in VMs (kvm) based on BusyBox. This is different from the normal setup and my startup timing may affect this problem.

Feel free to close this issue if you think it affects only very few users (me).

Anyway, _it is a changed behavior_ and it may be interresting to know why it happens. I can make a git-bisect and pinpoint the commit, but it will be much faster if I can just replace one binary.

> The scheduler is not involved in this calculation.

What K8s program is involved?

**Comment by uablrek** [comment]
> but the interval is at least less than 1s.

For me the time is ~5s. Here is an example from my test log. Time between printouts is 1s:
```
  06:29:24 (vm-001): TEST CASE: Checking DaemonSet [mserver] (nodes=4)
Nodes=4, desired=0
Nodes=4, desired=0
Nodes=4, desired=0
Nodes=4, desired=0
Nodes=4, desired=0
Nodes=4, desired=0
tex [daemonset_ready mserver 4]
DaemonSet [mserver], ready=0, desired=4
Retry (1/90) [daemonset_ready mserver 4]
DaemonSet [mserver], ready=0, desired=4
Retry (2/90) [daemonset_ready mserver 4]
DaemonSet [mserver], ready=1, desired=4
Retry (3/90) [daemonset_ready mserver 4]
DaemonSet [mserver], ready=4, desired=4
tex [npods app=mserver 4]
```

**Comment by uablrek** [comment]
I seems to be caused by deploying so close to the cluster start. I added a 10s delay between all-node-ready and "kubectl apply" of the manifest and then I don't see the "desired=0".

**Comment by aojea** [comment]
you mean that the controller may not see any nodes readys at that time?

**Comment by uablrek** [comment]
The nodes are reported ready (https://github.com/kubernetes/kubernetes/issues/113844#issuecomment-1312376344) but when the daemonset is deployed early in cluster start daemonset.status.desiredNumberScheduled==0 even  though the nodes are reported "ready". A few seconds later it seems fine and daemonset.status.desiredNumberScheduled==4 which is as expected.

**Comment by uablrek** [comment]
Git-bisect on `kubelet`;
```
kubernetes > git bisect good
9f5c5b82a9e50cd15f35deb963238cfdb7462cac is the first bad commit
commit 9f5c5b82a9e50cd15f35deb963238cfdb7462cac
Author: Jingyuan Liang <jingyuanliang@google.com>
Date:   Mon Oct 31 09:48:48 2022 +0000

    kubelet: Keep trying fast status update at startup until node is ready

 pkg/kubelet/kubelet.go                  |  67 ++++++++------
 pkg/kubelet/kubelet_node_status.go      |  79 +++++++++++++++++
 pkg/kubelet/kubelet_node_status_test.go | 153 ++++++++++++++++++++++++++++++++
 3 files changed, 272 insertions(+), 27 deletions(-)
```

As mentioned I have no problem adapting my startup so if the new behavior is expected, please close this issue.

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/pull/112618

> `fastStatusUpdateOnce` was introduced ([7ffa4e1](https://github.com/kubernetes/kubernetes/commit/7ffa4e17e01e8abbadb8c25af2b8c9e73630256b), #67031) to reduce the latency to node ready, but in some situations, having CIDR assigned doesn't immediately make the node ready and it's blocked by the container runtime. In this case, `fastStatusUpdateOnce` returns early when the CIDR is assigned but container runtime (and network) is not ready yet, and leaves node readiness reporting to the regular container runtime check and heartbeat reporting, which can add a delay of up to 12 seconds per our measurement (median delay at about 5 seconds when `fastStatusUpdateOnce` returns early).

I guess the reason for this issue could be the node that reports a ready state with some taints related to the container runtime notReady state(not sure exact key for the taint).

Can you check the taints for your nodes at startup?

**Comment by aojea** [comment]
cc: @jingyuanliang 

yeah, please @uablrek , let's get to the bottom of this, maybe the controller manager logs can get us more information on why the daemon controller sees only one?

**Comment by aojea** [comment]
> I guess the reason for this issue could be the node that reports a ready state with some taints related to the container runtime notReady state(not sure exact key for the taint).

this seems a very plausible cause, @uablrek maybe you can dump the nodes objects and the diff may give us more hints

**Comment by uablrek** [comment]
Log [kube-controller-manager.log.txt](https://github.com/kubernetes/kubernetes/files/10000226/kube-controller-manager.log.txt)

**Comment by uablrek** [comment]
Node object [vm-002.before.log.txt](https://github.com/kubernetes/kubernetes/files/10000287/vm-002.before.log.txt) and [vm-002.after.log.txt](https://github.com/kubernetes/kubernetes/files/10000294/vm-002.after.log.txt).

**Comment by gjkim42** [comment]
```yaml
{
    "apiVersion": "v1",
    "kind": "Node",
    "metadata": {
...
        "name": "vm-002",
...
    },
    "spec": {
        "taints": [
            {
                "effect": "NoSchedule",
                "key": "node.kubernetes.io/not-ready"
            }
        ]
    },
    "status": {
...
        "conditions": [
...
            {
                "lastHeartbeatTime": "2022-11-14T06:41:54Z",
                "lastTransitionTime": "2022-11-14T06:41:54Z",
                "message": "kubelet is posting ready status",
                "reason": "KubeletReady",
                "status": "True",
                "type": "Ready"
            }
        ],
...
}
```



> Node object [vm-002.before.log.txt](https://github.com/kubernetes/kubernetes/files/10000287/vm-002.before.log.txt) and [vm-002.after.log.txt](https://github.com/kubernetes/kubernetes/files/10000294/vm-002.after.log.txt).

vm-002.before.log.txt shows this.

This node had the taint with 'not-ready' key, and condition having 'Ready' type with 'True' status. As a result, the node was marked as Ready but could not be scheduled at the same time.

> For the record, I wait until all K8s nodes are "ready" _before_ performing this test.

Waiting for the ready state of a node is not enough for the node to schedule pods. You should consider taints-tolerations.

---

> Git-bisect on `kubelet`;
> 
> ```
> kubernetes > git bisect good
> 9f5c5b82a9e50cd15f35deb963238cfdb7462cac is the first bad commit
> commit 9f5c5b82a9e50cd15f35deb963238cfdb7462cac
> Author: Jingyuan Liang <jingyuanliang@google.com>
> Date:   Mon Oct 31 09:48:48 2022 +0000
> 
>     kubelet: Keep trying fast status update at startup until node is ready
> 
>  pkg/kubelet/kubelet.go                  |  67 ++++++++------
>  pkg/kubelet/kubelet_node_status.go      |  79 +++++++++++++++++
>  pkg/kubelet/kubelet_node_status_test.go | 153 ++++++++++++++++++++++++++++++++
>  3 files changed, 272 insertions(+), 27 deletions(-)
> ```
> 
> As mentioned, I have no problem adapting my startup so if the new behavior is expected, please close this issue.

I think that [the PR](#112618) did not slow down the node startup but speeded up it. And I guess that it increased the interval between the node reporting the 'Ready' condition and the node controller removing the 'not-ready' taint.

**Comment by liggitt** [comment]
The daemonset behavior as long as there are applicable taints looks correct.

If there's an issue, it looks limited to how responsive the node controller is in translating the node-reported Ready condition to removal of the not-ready taint.

Do you have a timeline of 1) node creation, 2) addition of Ready=True status condition, 3) removal of not-ready taint in your environment? Can you see that timeline for both 1.25.x and 1.26.0-beta.0?

If it helps capture that, you can start kubectl watching nodes before they are registered and see all the updates to them like this:

`kubectl get nodes --watch --output-watch-events -o json`

If the overall time from node creation to removal of the not-ready taint is ~the same, I don't think there's an issue here. If something made that overall time notably longer, that's worth investigating.

**Comment by uablrek** [comment]
```
                         API-server-accesible    Nodes-ready    daemonset-ready
v1.25.3                    0                               10s                        22s
v1.26.0-beta.0         0                               1-2s                       20s
```
"API-server-accesible" meaning that the "default" namespace exists and can be read. I can't easily measure then the taint is removed but the "daemonset-ready" should be about the same.

And no, the start-up time is not longer but a little bit shorter. And the time to nodes-ready is _way_ shorter.

So I think rather than indicating a problem this issue shows that the "fast status update" works as intended :smile: 

Closing...

/close

**Comment by liggitt** [comment]
> And no, the start-up time is not longer but a little bit shorter. And the time to nodes-ready is _way_ shorter.

awesome, thanks for confirming

**Comment by aojea** [comment]
> And no, the start-up time is not longer but a little bit shorter. And the time to nodes-ready is _way_ shorter.
> 
> So I think rather than indicating a problem this issue shows that the "fast status update" works as intended 😄

awesome
