### ISSUE TITLE
cluster role binding getting recreated after deletion or edit.

### ISSUE THREAD

**Issue by vlakka1** [kubernetes/kubernetes#113804]
### What happened?

We have cluster role binding that is getting recreated after deleting it. Also tried editing it and removing one of the subjects. It is restored to the previous version.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aks-cluster-admin-binding
  uid: 21841924-1ebd-494e-98af-ae47d17ae1ae
  resourceVersion: '434575970'
  creationTimestamp: '2022-11-10T03:31:28Z'
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/cluster-service: 'true'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","kubernetes.io/cluster-service":"true"},"name":"aks-cluster-admin-binding"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"cluster-admin"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"clusterAdmin"},{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"clusterUser"}]}
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-11-10T03:31:28Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:roleRef: {}
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2022-11-10T03:34:12Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:labels:
            .: {}
            f:addonmanager.kubernetes.io/mode: {}
            f:kubernetes.io/cluster-service: {}
        f:subjects: {}
  selfLink: >-
    /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/aks-cluster-admin-binding
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: clusterAdmin
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: clusterUser
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

### What did you expect to happen?

Update the cluster role binding by deleting the "clusterUser" user. The state is maintained.
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: clusterUser

### How can we reproduce it (as minimally and precisely as possible)?

na

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"4e608ea4d95b4ee29933376f99a419c7b6abfe33", GitTreeState:"clean", BuildDate:"2022-09-16T05:09:53Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

Azure AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vlakka1** [comment]
I'm thinking the addon label is recreating it. Any inputs on how the add on label can be removed?

**Comment by pacoxu** [comment]
It sounds AKS-related. Maybe https://github.com/Azure/AKS/issues is the right place.

**Comment by liggitt** [comment]
There seems to be an automated process recreating the binding, but that is not a binding created by anything in the OSS portion of the project. I'd suggest reaching out to your cluster operator to ask about the binding.

/close
