### ISSUE TITLE
[Winkernel Proxier] No ingress load balancer rules with endpoints to support load balancing when all the endpoints are terminating

### ISSUE THREAD

**Issue by princepereira** [kubernetes/kubernetes#113841]
### What happened?

HNS requires the Load Balancing Policy to be configured to identify the traffic destined to a cloud providers Load Balancer IP (VIP) and forward it to the distributed Load Balancer running in VFP on the node. Windows Kube-proxy ignores the terminating endpoints and strictly creates a HNS Load Balancer policy only for "Ready" pods that are not terminating. This creates a problem when all the PODs serving as backends for a Service are terminating. The traffic for active connections is not delivered to the Distributed LoadBalancer and dropped on the Windows node.

### What did you expect to happen?

Windows Kube-proxy/HNS should handle the terminating endpoints correctly to minimize the network traffic loss.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Service of Type LoadBalancer with exactly one POD as a backend.
2. Establish a long running TCP connection from an external Client to the Service.
3. Scale the deployment to delete the POD.
4. The active connection is immediately broken. A prestop hook handler configured on the POD will not get a chance to gracefully terminate the connection.

### Kubernetes version

1.24.0 and above

### Cloud provider

Azure Kubernetes Service

### OS version

Windows Server 2019, Windows Server 2022

### Install tools

NA

### Container runtime (CRI) and version (if applicable)

NA

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NA

https://github.com/kubernetes/kubernetes/issues/113841#tasklist-block-9b92bdf2-fe14-419f-b2e3-a8267a0bfcbe

**Comment by MikeZappa87** [comment]
Yes it's done will close
