### ISSUE TITLE
scheduler: distinguish between Unschedulable and UnschedulableAndUnresolvable from PostFilter

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#113854]
### What would you like to be added?

Right now, both status codes are treated the same:
https://github.com/kubernetes/kubernetes/blob/cc704f97784c3359db4690b97201ebfe6b481869/pkg/scheduler/framework/runtime/framework.go#L769C26-L771

This could be changed so that Unschedulable only means "I couldn't do anything, but keep trying", which might make sense when there are two PostFilter plugins, like the new dynamic resource plugin and preemption.

### Why is this needed?

Better decision on how to proceed when a pod cannot be scheduled, but some action could make it schedulable.

**Comment by kerthcet** [comment]
@pohly I'd like to follow this, Just to confirm you're not working on this.

**Comment by pohly** [comment]
Feel free to work on this, I haven't looked into this at all yet.

**Comment by ahg-g** [comment]
The Unschedulable statuses are not treated the same, `RunPostFilterPlugins` calls Merge, which returns `UnschedulableAndUnresolvable` if at least one PostFilter returns that status.

https://github.com/kubernetes/kubernetes/blob/cc704f97784c3359db4690b97201ebfe6b481869/pkg/scheduler/framework/runtime/framework.go#L778

What else are you suggesting to change?

**Comment by ahg-g** [comment]
Ah, you want to exit early when facing `UnschedulableAndUnresolvable`, ok that make sense.
