### ISSUE TITLE
Define and implement kubectl top

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#11382]
Would be nice to have `kubectl stats podName` work like docker stats (basically a top like interface on the client that connects to an endpoint streaming data every second).  I think this should be pretty straightforward, since the kubelet server already supports requests for `/stats/ns/podname/uid/containername`

Would be even better to have kubectl show stats consumed by a service, rc across the cluster.

**Comment by bgrant0607** [comment]
cc @vishh

**Comment by timothysc** [comment]
cc @jwforres @jayunit100 @timothysc

**Comment by bgrant0607** [comment]
Once we have metrics APIs, standard `get` functionality should work for them. We also plan to implement a top command.

**Comment by vishh** [comment]
ref #11951. `kubectl top` is being implemented by @mvdan. 
Heapster currently computes namespace level usage. The plan is to extend that to controllers and services.

**Comment by piosz** [comment]
It requires Master Metrics API to be implemented (#11382).

**Comment by piosz** [comment]
We may want to support the following commands:
- ```kubectl top node <id>``` - list all pods running on the given node accompanied with theirs cpu/mem usage
- ```kubectl top pod <id>``` - print cpu/mem usage stats for the given pod
- ```kubectl top pod --selector=<label-query>``` - list all pods defined by the label query accompanied with their cpu/mem usage

**Comment by piosz** [comment]
Assigning to myself as my intern will probably work on this. First version of Master Metrics API is done as for now.

cc @davidopp @fgrzadkowski @janetkuo @pwittrock

**Comment by mksalawa** [comment]
After the conversation with @piosz, the proposed supported commands might be: 

- `kubectl top node` - list all nodes with their CPU and Memory usage
- `kubectl top node <id>` - show the CPU and Memory usage for the given node
- `kubectl top node --selector=<label-query>` - list all nodes defined by the label query with their CPU and Memory usage

- `kubectl top pod` - list all pods with their CPU and Memory usage
- `kubectl top pod <id>` - show the CPU and Memory usage for the given pod
- `kubectl top pod --selector=<label-query>` - list all pods defined by the label query with their CPU and Memory usage

Also, the flag `--all-namespaces` and `--namespace=<namespace>` will be supported.

The output would be in the form:
```
$ kubectl top node
NAME      CPU      MEMORY  TIMESTAMP                         
node-1    100m     200Mi   Wed, 06 Jul 2016 17:32:09 +0200   
node-2    220m     400Mi   Wed, 06 Jul 2016 17:32:10 +0200
```

@janetkuo, @pwittrock are you ok with the proposal?

**Comment by piosz** [comment]
cc @jszczepkowski

**Comment by bprashanth** [comment]
Top for contaienrs within a pod would also help (currently kubectl exec  -- top doesn't work as well because of the TERM env var, and not all containers having top). Also a wrapper around `top --selector` that just allowed `top service/rc/job/daemon...`

Disk/Network utilization would be REALLY helpful. 

Just throwing it out there as an idea, an ncurses UI that allowed me to scroll through the list of nodes and hit enter, and it shows me the top usage of pods on a node would be great. 

I guess we should be mindful of where we draw the line and tell users to just run sysdig.

**Comment by bprashanth** [comment]
@kubernetes/kubectl

**Comment by vishh** [comment]
+1 for supporting per-container usage as well, in addition to that of pods. +1 for disk (and inodes once its available) usage as well.

**Comment by mksalawa** [comment]
As far as I can see, the support for listing containers (with metrics for each) within a given pod is possible.

If it comes to Storage usage, it can be easily added as well, but for the time being it is not filled with data (by the metrics API).

**Comment by mksalawa** [comment]
I created a pull request #28844.

Available commands are:
- `kubectl top node ([<id>] | [(--selector | -l) <labelSelector>])`
- `kubectl top pod ([<id>] | [(--selector | -l) <labelSelector>])`

Also, for pods, the supported flags are:
- `--containers` - lists container usage below the pod total usage
- `--all-namespaces`

**Comment by piosz** [comment]
Further improvements

suggested by @deads2k:
1. sorting on columns, top style
1. support for additional rollup resource types:  services, replicasets/rcs, deployments, jobs, daemonsets, ingress?
1. dynamically updating
1. pasteable output for `kubectl describe`

suggested by @vishh:
1. watch
1. sort by mem usage

**Comment by smarterclayton** [comment]
I'd like to see node capacity / allocatable taken into account and joined with this data.  The amount being used is not nearly as useful as the amount being used + the amount AVAILABLE to be used.

**Comment by mksalawa** [comment]
The basic implementation of top has been done in #28844.

There are some features that would be better to add after heapster becomes the apiserver and the metrics can be processed the same way the other resources are. It's because kubectl has all the mechanisms for these, most of which are specific for the apiserver resources and thus reusing them seems not possible without duplication (I tried to look at the code quite thoroughly, but please correct me if I'm wrong).
I opened a new issue regarding further features for the command, after metrics are the proper Kube API resources - #30507


Other suggestions from this issue and PR #28844:
- [ ] support label selector for nodes in Heapster
- [ ] default sort by mem usage

The selector support in Heapster should definitely be done by v1.4 I think. As for sorting, we can have a default now or wait until `--sort-by` is implemented. WDYT?

**Comment by mksalawa** [comment]
@deads2k also suggested these, but I'm not sure if I understand them correctly:

> request multiple namespaces (this should conform to whatever we get for normal kubectl commands)

AFAIK, kubectl doesn't provide any flag for multiple namespaces, except for `--all-namespaces`, which is also handled by 'top'.
> label select namespaces (Show me how my all my infrastructure namespaces are doing)

Do you mean somenthing like `kubectl top namespace NAME`?
> handle the eventual securing of heapster

Is turning heapster to be an apiserver enough, or does it take more to fulfil this?

**Comment by smarterclayton** [comment]
```
$ kubectl top node --capacity

NAME                           CPU  CPU%     MEMORY    STORAGE   
kubernetes-minion-group-xxxx   76m  35%   1468 Mi   0 Mi      
kubernetes-minion-group-yyyy   73m  50%   1511 Mi   0 Mi      
kubernetes-minion-group-zzzz   46m  86%   1506 Mi   0 Mi      
kubernetes-master              76m  15%   2059 Mi   0 Mi      
```

**Comment by mksalawa** [comment]
@smarterclayton good point. It is pretty straightforward for nodes, but do you see it also in case of pods? It can be tricky, as we have limits and requests for each container and actually none of them is obligatory to be set.

**Comment by smarterclayton** [comment]
I think the nodes use case is separate for now.  "I'm an admin and I want
to see how full my nodes are" and "I'm an admin and I want to see whether a
specific subset (by label) of my nodes are full".

**Comment by ghodss** [comment]
It would also be cool to have a `kubectl top node --summary` that just showed a single line summary of usage/% of all nodes, and could also filter by label as well.

**Comment by piosz** [comment]
The first version is implemented, so closing the issue. Please discuss further improvements in #30507

**Comment by ompraash** [comment]
executing top node command fails as below

```
kubectl top node 
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```
kubectl version is : 1.5

**Comment by piosz** [comment]
@ompraash please create an issue with more details and cc me there.
