### ISSUE TITLE
Deprecate and remove 'kubectl stop'

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes#11384]
At this point, kubectl delete has a super set of the functionality of kubectl stop. Is there any reason to keep it around?

@bgrant0607 @jlowdermilk

**Comment by bgrant0607** [comment]
I agree we should eliminate it. It just creates user confusion.

**Comment by MHBauer** [comment]
Is this complete or will it remain around until v2?

**Comment by mikedanese** [comment]
It's not complete as we still have to remove the subcommand. I think we can do that now.

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc

**Comment by shiywang** [comment]
@kargakis is this issues already solved or we can close it ?
