### ISSUE TITLE
remove duplicate slash in test/e2e/network/proxy.go from release-1.21

### ISSUE THREAD

**Issue by Chaunceyctx** [kubernetes/kubernetes#113845]
### Which jobs are failing?

e2e conformance

### Which tests are failing?

same with https://github.com/kubernetes/kubernetes/issues/112760 
This problem has existed since version 1.21.

>I1111 11:44:08.893424   33572 httplog.go:94] "HTTP" verb="DELETE" URI="//api/v1/namespaces/proxy-9604/pods/agnhost/proxy/some/path/with/DELETE" latency="706.513µs" userAgent="ups-v1.21.0-e2e.test/v0.0.0 (linux/amd64) kubernetes/5e58841 -- [sig-network] Proxy version v1 A set of valid responses are returned for both pod and service ProxyWithPath [Conformance]" srcIP="127.0.0.1:56636" resp=404

>I1111 11:44:08.926574   33572 httplog.go:94] "HTTP" verb="DELETE" URI="//api/v1/namespaces/proxy-9604/pods/agnhost/proxy/some/path/with/DELETE" latency="890.677µs" userAgent="ups-v1.21.0-e2e.test/v0.0.0 (linux/amd64) kubernetes/5e58841 -- [sig-network] Proxy version v1 A set of valid responses are returned for both pod and service ProxyWithPath [Conformance]" srcIP="127.0.0.1:56636" resp=404

>I1111 11:44:08.936139   33572 httplog.go:94] "HTTP" verb="DELETE" URI="//api/v1/namespaces/proxy-9604/pods/agnhost/proxy/some/path/with/DELETE" latency="727.826µs" userAgent="ups-v1.21.0-e2e.test/v0.0.0 (linux/amd64) kubernetes/5e58841 -- [sig-network] Proxy version v1 A set of valid responses are returned for both pod and service ProxyWithPath [Conformance]" srcIP="127.0.0.1:56636" resp=404

### Since when has it been failing?

1.21

### Relevant SIG(s)

/sig network

**Comment by Chaunceyctx** [comment]
maybe we should cherry-pick from https://github.com/kubernetes/kubernetes/pull/112763 to release-1.21/22/23/24?

**Comment by Chaunceyctx** [comment]
@aojea

**Comment by aojea** [comment]
Latest supported release is 1.23 https://kubernetes.io/releases/

Not supported releases doesn't receive patches

**Comment by Chaunceyctx** [comment]
> 

This problem still exists in version 1.23、1.24. Should I create a pull request to fix this problem？

**Comment by aojea** [comment]
I don't think this qualifies as backport, this only happens if you configure your `Host` with a trailing slash, we are doing now better sanitizing the input but users can configure the field correctly

**Comment by Chaunceyctx** [comment]
> 

thanks. I will close this issue.

**Comment by aojea** [comment]
yeah, thanks for following up anyway, keep it up
