### ISSUE TITLE
dynamic resource allocation: move common logic of highestSupportedVersion to util package

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#113831]
See comment for details:
https://github.com/cncf-tags/container-device-interface/pull/93

**Comment by elezar** [comment]
@klueska the link in the description no longer exists. Could you update the link?

The code for determining the spec version is under review in https://github.com/container-orchestrated-devices/container-device-interface/pull/93 and this could be moved out to a package that could be imported easily.

**Comment by bart0sh** [comment]
[Implementation PR](https://github.com/kubernetes/kubernetes/pull/118761) is under review
