### ISSUE TITLE
[Winkernel Proxier] Unexpected active TCP connection drops while horizontally scaling the endpoints for a LoadBalancer Service with External Traffic Policy: Local

### ISSUE THREAD

**Issue by princepereira** [kubernetes/kubernetes#113842]
### What happened?

On a service of type LoadBalancer with External Traffic Policy: Local, whenever pod restarts other pods within the same Service stop responding to active connections from the Clients.

1. N clients are connected to M pods somewhat evenly, there are N established TCP connections.
2. One particular pod P is manually restarted/deleted.
3. Multiple(N/M) clients which are currently connected to P start seeing drops on Active connections, which is somewhat expected.
5. But the remaining (N-N/M) connections between clients and the other pods are negatively affected and some of them break.

For example if a deployment has pods 1,2,3,4,5. Each pod has TCP sessions where clients are connected and sending data. If pod 4 goes down some of the other pods 1,2,3,5 have their existing connections affected by pod 4 going down.

### What did you expect to happen?

When a POD P goes down, the remaining (N-N/M) connections between clients and the other pods are kept intact.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Service with Type Load Balancer and set External Traffic Policy: Local.
2. Establish multiple long running TCP connections from an external client to the service.
3. Horizontally scale the PODs behind the service. For example from 3 to 8.
4. You can see multiple TCP connections are broken from the client side.

### Kubernetes version

1.24.0 and above

### Cloud provider

Azure Kubernetes Service

### OS version

Windows Server 2019, Windows Server 2022

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig windows

**Comment by aojea** [comment]
is this for windows? can you tag it as /sig windows if affirmative?
Thanks

**Comment by princepereira** [comment]
> is this for windows? can you tag it as /sig windows if affirmative? Thanks

Sure. Thanks @aojea
