### ISSUE TITLE
Namespace selector for topologySpreadConstraints

### ISSUE THREAD

**Issue by andrewnazarov** [kubernetes/kubernetes#113846]
### What would you like to be added?

By design `topologySpreadConstrains` works within the namespace. It would be great to have the possibility to consider pods from different namespaces. For this, a namespace selector as it was implemented for Affinity/Anti-affinity seems to be a good fit.

### Why is this needed?

Our use case is a desired uniform distribution of pods which reside in different namespaces - think of multiple instances of an app which belong to different teams. Our services are pretty CPU-demanding and we want them to be distributed among all nodes evenly for better resource management and to speed up the startup time. When all of them happen to be scheduled onto one or a few nodes and we upgrade them all at once it might take too long to get them up & running.

**Comment by alculquicondor** [comment]
cc @ahg-g who initially proposed a one-pod-per-node strategy (which was rejected).

**Comment by ahg-g** [comment]
I don't understand the use case yet, can you please clarify why would multiple instances of the same app be distributed across namespaces? typically an app is managed by a Deployment which is namespaced.

**Comment by ahg-g** [comment]
ok, I get what you are looking for now, using topologySpread across different services is not a pattern I was expecting, but I guess you can use more than one constraint: one to spread the pods from the same service and another to force spreading across cpu-demanding services.

btw, you can use anti-affinity with podTopologySpread now.
