### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Handle systemd cgroup driver by using libcontainer for updating pod cgroup values

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#113857]
### What would you like to be added?

In-place pod resize with cgroupv2 (where systemd cgroup driver is default) should use libcontainer functions to update pod cgroup settings. Please see this issue for details:
https://github.com/kubernetes/kubernetes/pull/102884#discussion_r1019704157

### Why is this needed?

Without this fix, reloading systemd daemons will cause the change to revert.

**Comment by iholder101** [comment]
Hey @vinaykul!
Is this issue still relevant? Is somebody actively working on it?

I have some experience with libcontainers.

**Comment by vinaykul** [comment]
> Hey @vinaykul! Is this issue still relevant? Is somebody actively working on it?
> 
> I have some experience with libcontainers.

Yes, this is relevant as well.
/cc @bobbypage
