### ISSUE TITLE
1.26 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by ramrodo** [kubernetes/kubernetes#113901]
### What happened?

This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.26 Release Notes. If you know of issues or API changes that are going out in 1.26, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team-release-notes 

/sig release
/milestone v1.26

**Comment by leonardpahlke** [comment]
@ramrodo I will close this issue, if there are only open points we can raise them in slack (?)
/close
