### ISSUE TITLE
Ephemeral container fails to be created for Static Pod

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes/kubernetes#113935]
### What happened?

I created an ephemeral container for a Static Pod using the `kubectl debug` command. The command succeed.

```console
❯ kubectl debug --image=busybox --share-processes=true --target=kube-apiserver -n kube-system kube-apiserver-kind-control-plane -- sleep infinity
Targeting container "kube-apiserver". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-vgkn4.
```

The API server accepted the ephemeral container:
```console
❯ kubectl -n kube-system get pod kube-apiserver-kind-control-plane --output=jsonpath='{.spec.ephemeralContainers}'
[{"command":["sleep","infinity"],"image":"busybox","imagePullPolicy":"Always","name":"debugger-vgkn4","resources":{},"targetContainerName":"kube-apiserver","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}]
```

However, the container is not created.

Its status is also not available:

```console
❯ kubectl -n kube-system get pod kube-apiserver-kind-control-plane --output=jsonpath='{.status.ephemeralContainerStatuses}'

```

### What did you expect to happen?

I expected one of these:

(a) the API server rejects the request to create an ephemeral container for a Static Pod
(b) kubelet creates the ephemeral container, and update the Static Pod's status sub-resource

### How can we reproduce it (as minimally and precisely as possible)?

Using a recent version of [docker engine](https://docs.docker.com/engine/install/), [kind](https://kind.sigs.k8s.io/docs/user/quick-start/)  v0.17 or newer, and [kubectl](https://kubernetes.io/docs/tasks/tools/#kubectl) v1.25.0 or newer, create a cluster and create an ephemeral container running `sleep infinity`. Since the ephemeral container is not running, the output of `grep` is 0. 

```
kind create cluster
kubectl debug --image=busybox --share-processes=true --target=kube-apiserver -n kube-system kube-apiserver-kind-control-plane -- sleep infinity
docker exec -it kind-control-plane ps -axw | grep --count "sleep infinity"
```

### Anything else we need to know?

The [Ephemeral Containers KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/277-ephemeral-containers/README.md) does not address Static Pods.

### Kubernetes version

<details>

```console
$ kubectl version --short
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.3
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
❯ docker exec -it kind-control-plane containerd --version
containerd github.com/containerd/containerd v1.6.9 1c90a442489720eec95342e1789ee8a5e1b9536f
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dlipovetsky** [comment]
The umbrella issue for ephemeral containers is https://github.com/kubernetes/enhancements/issues/277

**Comment by dlipovetsky** [comment]
Control plane machines provisioned using [kubeadm](https://kubernetes.io/docs/reference/setup-tools/kubeadm/) run control plane components (etcd, kube-apiserver, kube-controller-manager, kube-scheduler) as Static Pods. Being able to create ephemeral containers for these Static Pods in order to debug the running processes is a use case worthy of mention.

If ephemeral containers are, by design, not intended to be used with Static Pods, let's please justify why that is the case, and try to document an alternative.

**Comment by SergeyKanzhelev** [comment]
Thank you for raising this issue. Indeed we either need to update docs or fix it. Can you please provide the kubelet log? We discussed this on triage meeting and not sure if this is actually supported or not. Kubelet log may give us some information quickly in case it is some bug.

/triage needs-information
/cc @xmcqueen

**Comment by dlipovetsky** [comment]
> Thank you for raising this issue.

Thanks for triaging it quickly!

> Can you please provide the kubelet log?

Yes, I'll do that. 

(I didn't do it initially, because even after I bumped kubelet log verbosity to 10, I found no references of the ephemeral container names in the log. I'll just attach the complete kubelet log here.)

**Comment by dlipovetsky** [comment]
Attached is the (compressed) kubelet log running in the kind-control-plane container. I bumped up its log verbosity to 8 prior to creating the ephemeral container.

I created the ephemeral container using the `kubectl debug` command described above at 18:42:31. 

[kubelet.log.gz](https://github.com/kubernetes/kubernetes/files/10024803/kubelet.log.gz)

**Comment by dlipovetsky** [comment]
@xmcqueen Thanks for trying to reproduce this. Your results are consistent with mine.

What I am reporting is that, despite having the correct spec, the ephemeral container is not created.
 
The key point I wanted to make in my report is that _the container is not created._ However, I failed to explain how to verify that claim.

We could verify it, for example, by listing all the processes running in the `kind-control-plane` container. We should find the `sleep` process, since it would be running in the ephemeral container. In my case, the process is not present:

```console
> docker exec -it kind-control-plane crictl ps -a | grep --count sleep
0
```

Moreover, since the ephemeral container has a shell executable, I should be able to run `kubectl exec`. In my case, the command fails:

```console
> kubectl -n kube-system exec kube-apiserver-kind-control-plane -it -c=debugger-cmz8x -- sh
error: unable to upgrade connection: container not found ("debugger-cmz8x")
```

I realize that `kubectl exec` not work for other reasons, even if the ephemeral container is created.

**Comment by xmcqueen** [comment]
I do see a difference in the test results, but I still can't exec into the ephemeral container.  I'll run some more tests.  THanks

Here is the pos spec showing something for the ephemeral container, but i can't exec into it anyway:

```
bmcqueen-mn1:~ bmcqueen$ kubectl -n kube-system get pod kube-apiserver-kind-control-plane --output=jsonpath='{.spec.ephemeralContainers}' | jq .
[
  {
    "command": [
      "sleep",
      "infinity"
    ],
    "image": "busybox",
    "imagePullPolicy": "Always",
    "name": "debugger-j5x5g",
    "resources": {},
    "targetContainerName": "kube-apiserver",
    "terminationMessagePath": "/dev/termination-log",
    "terminationMessagePolicy": "File"
  }
]
bmcqueen-mn1:~ bmcqueen$ kubectl -n kube-system exec -it kube-apiserver-kind-control-plane -c debugger-j5x5g -- sh
error: unable to upgrade connection: container not found ("debugger-j5x5g")
bmcqueen-mn1:~ bmcqueen$
```

**Comment by liggitt** [comment]
We should not allow ephemeral containers for static pods… the API content is not authoritative for static pods, the manifests on disk are, so I would expect the kubelet to ignore API spec content and the API to disallow adding ephemeral containers to static pods

**Comment by xmcqueen** [comment]
It sounds like a documentation update would be appropriate here.  I think the Static Pods page would be a good place for it.  I'll get a PR going.

Thanks @dlipovetsky

**Comment by sftim** [comment]
/remove-triage needs-information

Is this good to close? We could additionally document _why_ you can't add an ephemeral container (which is that mirror pods are essentially read-only).

**Comment by liggitt** [comment]
If the /ephemeralcontainers subresource doesn't currently reject attempts to add to a static pod, I think it should, to make it clearer the addition won't be effective

**Comment by sftim** [comment]
Does the API server actually know that mirror pods are mirror pods? I wonder how you can tell.

**Comment by aojea** [comment]
it seems it can if it wants

https://github.com/kubernetes/kubernetes/blob/25f2c6f330b5b74531702155b447890850cde76d/pkg/kubelet/pod/mirror_client.go#L90

**Comment by aojea** [comment]
@liggitt I think that is just updating this function

https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/pkg/apis/core/validation/validation.go#L4682-L4707

to fail if the annotation `kubetypes.ConfigMirrorAnnotationKey` is set, right?

... and add tests, of course 😄 

can you confirm?

**Comment by liggitt** [comment]
yeah, that's right

**Comment by aojea** [comment]
any taker on this one?

**Comment by xmcqueen** [comment]
I'll take it, per the discussion here: add a check in `ValidatePodEphemeralContainersUpdate` to reject the attempt to add an ephemeral container if the request is aimed at a static pod.  Also include a test case.

Also some additional documantation comments from this ticket and from  kubernetes/website#37993
