### ISSUE TITLE
Memory QoS should not be affected by CPU requests/limits

### ISSUE THREAD

**Issue by maximmold** [kubernetes/kubernetes#113977]
### What happened?

I had a discussion with @kad during KubeCon about some unexpected behavior we observed testing Pod Quality of Service and its relation to OOMKills.  The kubernetes documentation [here](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-out-of-memory-behavior) talks about the kubelet's setting of `oom_score_adj` based on QoS for the pod.

For Pod's with memory request == limit and CPU request == limit, we see the `oom_score_adj` == -997 as expected.
For Pod's with memory request == limit and CPU request < limit, we see the `oom_score_adj` == 998 as it is then calculated as a bustable QoS.

### What did you expect to happen?

I would not expect CPU settings to have any bearing on the memory QoS and subsequently the `oom_score_adj`. There is a lot of debate ongoing about whether to limit CPU. However, this debate should have no bearing on the way we treat a pod in relation to Node Memory Pressure. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod with memory request == limit and CPU request == limit and exec into to the pod. `cat /proc/<process_num>/oom_score_adj` and validate the score is -997.

Create a pod with memory request == limit and CPU request < limit and exec into to the pod. `cat /proc/<process_num>/oom_score_adj` and validate the score is not -997 as expected.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.22) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS EKS 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
# paste output here
Linux ip-100-103-238-37 5.4.188-104.359.amzn2.x86_64 #1 SMP Thu Apr 14 20:53:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

What oom score adjustment would you expect on burstable pods? What would be the ideal behavior? I am marking it as a feature as it feels like request a change of behavior while it is behaving as designed today.

**Comment by alex-berger** [comment]
I am fully supportive of this request and while we are at it we should also consider [adding a special case](https://github.com/kubernetes/kubernetes/blob/6e0cb243d57592c917fe449dde20b0e246bc66be/pkg/kubelet/qos/policy.go#L48) for Pods with `priortyClassName: "cluster-critical"`. Something along the lines of:

```go
const (
	// KubeletOOMScoreAdj is the OOM score adjustment for Kubelet
	KubeletOOMScoreAdj int = -999
	// KubeProxyOOMScoreAdj is the OOM score adjustment for kube-proxy
	KubeProxyOOMScoreAdj  int = -999
	guaranteedOOMScoreAdj int = -997
        clusterCriticalOOMScoreAdj int = -996 // <- NEW
	besteffortOOMScoreAdj int = 1000
)
...
func GetContainerOOMScoreAdjust(pod *v1.Pod, container *v1.Container, memoryCapacity int64) int {
	if types.IsNodeCriticalPod(pod) {
		// Only node critical pod should be the last to get killed.
		return guaranteedOOMScoreAdj
	}

	switch v1qos.GetPodQOS(pod) {
	case v1.PodQOSGuaranteed:
		// Guaranteed containers should be the last to get killed.
		return guaranteedOOMScoreAdj
	case v1.PodQOSBestEffort:
		return besteffortOOMScoreAdj
	}
	if types.IsClusterCriticalPod(pod) { // <- NEW
                // Cluster critical pod (with QoS != Guaranteed) should be the second last to get killed.
		return clusterCriticalOOMScoreAdj
	}
        ...
```
