### ISSUE TITLE
Kubectl apply -k (kustomizefile) validation errors do not specify the file 

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [kubernetes/kubernetes#113950]
### What happened?

When working on a kustomize project I noticed this error on a SecretClassProvider

running this from the overlay folder:

```
kubectl.exe apply --validate=true --dry-run=client -k .

...
secretproviderclass.secrets-store.csi.x-k8s.io/connector-abuseipdb-secret-provider-class configured (dry run)
secretproviderclass.secrets-store.csi.x-k8s.io/minio-secret-provider-class configured (dry run)
error: error validating ".": error validating data: ValidationError(SecretProviderClass.spec.parameters.secretObjects): invalid type for io.x-k8s.csi.secrets-store.v1.SecretProviderClass.spec.parameters: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false
```

Since there are multiple secret providers (both before and after the validation error) I could not determine which one was the one that was failing.

### What did you expect to happen?

Either the CRD or the file path in the error message, so that it is easy to identify which secret provider is the culprit.

error: error validating "**secretproviderclass.secrets-store.csi.x-k8s.io/worker-secret-provider-class**": error validating data: ValidationError(SecretProviderClass.spec.parameters.secretObjects): invalid type for io.x-k8s.csi.secrets-store.v1.SecretProviderClass.spec.parameters: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

or

error: error validating "**../../base/workers/worker-secret.yaml**": error validating data: ValidationError(SecretProviderClass.spec.parameters.secretObjects): invalid type for io.x-k8s.csi.secrets-store.v1.SecretProviderClass.spec.parameters: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false

### How can we reproduce it (as minimally and precisely as possible)?

Create a kustomization file with a few (same type) resources, and adjust one yaml to generate a validation error

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
22000        Microsoft Windows 11 Enterprise  64-bit          10.0.22000
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/remove-sig cli
/sig cli

(retriggering to remove needs-sig label)
