### ISSUE TITLE
Flake: Azure unit test TestJitterWithNegativeMaxFactor is Flaking with master golang

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#113912]
### Which jobs are flaking?

https://prow.ppc64le-cloud.org/job-history/s3/ppc64le-prow-logs/logs/postsubmit-master-golang-kubernetes-unit-test-ppc64le

### Which tests are flaking?

k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/retry: TestJitterWithNegativeMaxFactor

### Since when has it been flaking?

We most probably saw the first flake with `devel go1.20-5d59fa143a Wed Oct 26 00:52:05 2022`

### Anything else we need to know?
```
=== FAIL: vendor/k8s.io/legacy-cloud-providers/azure/retry TestJitterWithNegativeMaxFactor (0.00s)
    azure_retry_test.go:88: 
        	Error Trace:	/home/prow/go/src/github.com/kubernetes/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_retry_test.go:88
        	Error:      	Not equal: 
        	            	expected: false
        	            	actual  : true
        	Test:       	TestJitterWithNegativeMaxFactor
```
### Relevant SIG(s)

/sig testing

**Comment by mkumatag** [comment]
this can be closed as the fix went in part of #114078 
/close
