### ISSUE TITLE
Liveness probe errored: context deadline exceeded (Client.Timeout or context cancellation while reading body)

### ISSUE THREAD

**Issue by FeiYing9** [kubernetes/kubernetes#113938]
### What happened?

I have a pod with config of httpGet probe，but it's never passed

But the http api is ok weather in other container or in k8s node throuth `curl podIP:port/path`

### What did you expect to happen?

kubelet probe httpGet correctly

### How can we reproduce it (as minimally and precisely as possible)?

my deploy probe config like this:
```yaml
livenessProbe:
    failureThreshold: 5
    httpGet:
      path: /appinfo
      port: 9000
      scheme: HTTP
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 5         # this not help to turn a larger number
```

### Anything else we need to know?

kebelet log:
```bash
11月 16 10:36:08 k8s-test2 kubelet[13504]: E1116 10:36:08.761091   13504 prober.go:113] "Probe errored" err="context deadline exceeded (Client.Timeout or context cancellation while reading body)" probeType="Liveness" pod="v500/myapp-549f95b6b5-l2fm9" podUID=4ead7639-e721-4cd2-890b-539d6de836ae containerName="myapp"
11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761166   13504 prober.go:173] "HTTP-Probe Host" scheme="http" host="10.244.247.176" port=9000 path="/appinfo"
11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761195   13504 prober.go:176] "HTTP-Probe Headers" headers=map[]
11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761730   13504 event.go:291] "Event occurred" object="v500/myapp-549f95b6b5-l2fm9" kind="Pod" apiVersion="v1" type="Warning" reason="Unhealthy" message="Liveness probe errored: context deadline exceeded (Client.Timeout or context cancellation while reading body)"
```

curl command by myself:
```bash
# see this, the container never restarts
$ kubectl-n v500 get po -owide  | grep myapp
myapp-549f95b6b5-l2fm9            0/1     Running                      0               14h   10.244.247.176   k8s-test2   <none>           <none>

$ kubectl -n v500 exec -it deploy/logstash -- curl -I http://10.244.247.176:9000/appinfo
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 159
Connection: keep-alive


real	0m0.016s
user	0m0.006s
sys	0m0.008s

# the same in all k8s node to make curl
```
tcpdump on the node where the pod is schedulered shows the length of response is 0:

![image](https://user-images.githubusercontent.com/49012290/202074522-6335d0ab-d97c-4525-ac6b-90d0d4fc8f50.png)

tcpdump in the container shows the http request is ok:

<img width="956" alt="image" src="https://user-images.githubusercontent.com/49012290/202074667-e6b70939-ad2a-4a38-a901-9f1923ebe9dd.png">

and, thanks to this [comment](https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-728908503),  I replaced the httpGet with an exec doing basically the same thing, which so far works without any problems

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux k8s-test0 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Install tools

<details>
kubeadm
</details>


### Container runtime (CRI) and version (if applicable)

```bash
$ docker version
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:26:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:28:17 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@FeiYing9 just to be on the safe side - can you try to repro this on a fresh version of k8s? 1.22 is out of support.

Can you try running curl from the host - it will replicate what kubelet is doing. Ideally add the same user agent as kubelet. If curl from the host works, but kubelet doesn't - then it's a problem inside kubelet. Otherwise it is a problem with the networking and/or application. I saw a case when application was configured to respond differently on requests from localhost for example.

Also if you can include info on runtime and CNI used - it may help

/triage needs-information

**Comment by FeiYing9** [comment]
> Can you try running curl from the host - it will replicate what kubelet is doing. Ideally add the same user agent as kubelet. If curl from the host works, but kubelet doesn't - then it's a problem inside kubelet. Otherwise it is a problem with the networking and/or application. I saw a case when application was configured to respond differently on requests from localhost for example.
> 
> Also if you can include info on runtime and CNI used - it may help

I think this is similar to this issue: https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-728908503

```bash
# does this mean the user of kubelet is root?  curl worked fine by user root from all k8s node
$ ps -efww | grep kubelet
root     33958       3-03:48:41 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --network-plugin=cni --pod-infra-container-image=registry.aliyuncs.com/google_containers/pause:3.5 --eviction-hard=nodefs.available<5% --eviction-hard=imagefs.available<5%

$ kubectl -nkube-system get cm calico-config -o yaml
apiVersion: v1
data:
  calico_backend: bird
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
        }
      ]
    }
  typha_service_name: none
  veth_mtu: "0"
kind: ConfigMap
```
the ’user-agent‘ in http header is just generated by the code? https://github.com/kubernetes/kubernetes/blob/e573e2945065756f1b14dd307969a5ca1337efb4/pkg/probe/http/http.go#L103

**Comment by aojea** [comment]
- the http_probe is sent from the kubelet process
- the exec_probe is sent from inside the container

http_probes are exposed to the network configuration on the host, is not the first time that some iptables rules (I think that there is actually a bug with Calico for this) block http probes.

exec_probes can not be blocked since they run inside the pod network namespace.

**Comment by pacoxu** [comment]
/remove-lifecycle stale
https://github.com/kubernetes/kubernetes/issues/115469 is similar.

**Comment by SergeyKanzhelev** [comment]
Are you running a lot of probes on the machine? Can it be caused by the same as: https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-1383207322?

**Comment by light2cloud** [comment]
> ### What happened?
> I have a pod with config of httpGet probe，but it's never passed
> 
> But the http api is ok weather in other container or in k8s node throuth `curl podIP:port/path`
> 
> ### What did you expect to happen?
> kubelet probe httpGet correctly
> 
> ### How can we reproduce it (as minimally and precisely as possible)?
> my deploy probe config like this:
> 
> ```yaml
> livenessProbe:
>     failureThreshold: 5
>     httpGet:
>       path: /appinfo
>       port: 9000
>       scheme: HTTP
>     initialDelaySeconds: 30
>     periodSeconds: 10
>     successThreshold: 1
>     timeoutSeconds: 5         # this not help to turn a larger number
> ```
> 
> ### Anything else we need to know?
> kebelet log:
> 
> ```shell
> 11月 16 10:36:08 k8s-test2 kubelet[13504]: E1116 10:36:08.761091   13504 prober.go:113] "Probe errored" err="context deadline exceeded (Client.Timeout or context cancellation while reading body)" probeType="Liveness" pod="v500/myapp-549f95b6b5-l2fm9" podUID=4ead7639-e721-4cd2-890b-539d6de836ae containerName="myapp"
> 11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761166   13504 prober.go:173] "HTTP-Probe Host" scheme="http" host="10.244.247.176" port=9000 path="/appinfo"
> 11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761195   13504 prober.go:176] "HTTP-Probe Headers" headers=map[]
> 11月 16 10:36:08 k8s-test2 kubelet[13504]: I1116 10:36:08.761730   13504 event.go:291] "Event occurred" object="v500/myapp-549f95b6b5-l2fm9" kind="Pod" apiVersion="v1" type="Warning" reason="Unhealthy" message="Liveness probe errored: context deadline exceeded (Client.Timeout or context cancellation while reading body)"
> ```
> 
> curl command by myself:
> 
> ```shell
> # see this, the container never restarts
> $ kubectl-n v500 get po -owide  | grep myapp
> myapp-549f95b6b5-l2fm9            0/1     Running                      0               14h   10.244.247.176   k8s-test2   <none>           <none>
> 
> $ kubectl -n v500 exec -it deploy/logstash -- curl -I http://10.244.247.176:9000/appinfo
> HTTP/1.1 200 OK
> Content-Type: text/plain; charset=UTF-8
> Content-Length: 159
> Connection: keep-alive
> 
> 
> real	0m0.016s
> user	0m0.006s
> sys	0m0.008s
> 
> # the same in all k8s node to make curl
> ```
> 
> tcpdump on the node where the pod is schedulered shows the length of response is 0:
> 
> ![image](https://user-images.githubusercontent.com/49012290/202074522-6335d0ab-d97c-4525-ac6b-90d0d4fc8f50.png)
> 
> tcpdump in the container shows the http request is ok:
> 
> <img alt="image" width="956" src="https://user-images.githubusercontent.com/49012290/202074667-e6b70939-ad2a-4a38-a901-9f1923ebe9dd.png">
> 
> and, thanks to this [comment](https://github.com/kubernetes/kubernetes/issues/89898#issuecomment-728908503), I replaced the httpGet with an exec doing basically the same thing, which so far works without any problems
> 
> ### Kubernetes version
> ### Cloud provider
> ### OS version

您好，你们这个问题解决了吗？我使用1.28 k8s 也遇到了这个问题

**Comment by FeiYing9** [comment]
> 您好，你们这个问题解决了吗

看问题描述，httpGet换成exec可以绕过

**Comment by light2cloud** [comment]
28m         Warning   Unhealthy   pod/feign-service-5657d7cdbf-dq2tj                  Readiness probe failed: Get "http://16.17.1.98:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
78s         Warning   Unhealthy   pod/provider-service-5d8cd887d6-q782p               Liveness probe failed: Get "http://16.17.0.173:80/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
50m         Warning   Unhealthy   pod/speed-java-demo-prod-1-7-43-1-fdff7949c-xbjhb   Liveness probe failed: Get "http://16.17.1.102:80/livez": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
34m         Warning   Unhealthy   pod/spring-boot-istio-client-7d8474d96b-mq29d       Readiness probe failed: Get "http://16.17.1.107:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
54m         Warning   Unhealthy   pod/spring-boot-istio-client-7d8474d96b-mt696       Readiness probe failed: Get "http://16.17.1.108:15021/healthz/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
23m         Warning   Unhealthy   pod/spring-boot-istio-server-1                      Readiness probe failed: Get "http://16.17.2.150:80/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
18m         Warning   Unhealthy   pod/spring-boot-istio-server-7                      Liveness probe failed: Get "http://16.17.2.152:80/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
