### ISSUE TITLE
Stop reporting volume limits for migrated volume plugins in Node object

### ISSUE THREAD

**Issue by gnufied** [kubernetes/kubernetes#113982]
### What happened?

Reporting volume limits for migrated volume plugins with often incorrect values confuses users because intree limits are mostly hardcoded and are not getting updated now that CSI driver is handling these volume types.

### What did you expect to happen?

Should not report any volume limits.

### How can we reproduce it (as minimally and precisely as possible)?

Kubelet reports incorrect volume limits:

```
  61   │   capacity:
  62   │     attachable-volumes-aws-ebs: "39"
  63   │     cpu: "4"
  64   │     ephemeral-storage: 125293548Ki
  65   │     hugepages-1Gi: "0"
  66   │     hugepages-2Mi: "0"
  67   │     memory: 16129400Ki
  68   │     pods: "250"
```

### Kubernetes version

1.25

### Cloud provider

Any

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mpatlasov** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/115040
