### ISSUE TITLE
Allow specifying credentials for Admission Webhooks via K8S resource

### ISSUE THREAD

**Issue by ameade** [kubernetes/kubernetes#113921]
### What would you like to be added?

Enable specification of Admission Webhook credentials in a Secret instead of a kubeconfig file for the kube-apiserver.

### Why is this needed?

Currently, to enable use of a ValidationAdmissionWebhook or a MutatingAdmissionWebhook that requires authentication, credentials must be provided to the kube-apiserver via a kubeconfig file located on the host (see [--admission-control-config-file](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#authenticate-apiservers)).

This means if a piece of software requires authentication for it's webhook implementation, the k8s admin must reconfigure kube-apiserver and restart it. It would be better if a piece of software could simply define it's ValidatingWebhookConfiguration and possibly a Secret, with no additional configuration needed.

**Comment by alexzielenski** [comment]
@ameade are you still interested in this feature? You can bring it up at an API Machinery meeting if so: https://github.com/kubernetes/community/blob/master/sig-api-machinery/README.md

Otherwise, this issue will be closed

**Comment by seans3** [comment]
/close

no response
