### ISSUE TITLE
the namespace in pod is empty

### ISSUE THREAD

**Issue by paipaoso** [kubernetes/kubernetes#113952]
the code is as follows:
```
obj := &corev1.Pod{}
pod := h.Decoder.Decode(req, obj)
```
and output is:
```
&Pod{ObjectMeta:{ test-2021-10-26-06-00-1026060225-573e31ecd3e668d7c1cb-     0 0001-01-01 00:00:00 +0000 UTC <nil> <nil>
```
Can anyone tell me why this happened and how to fix it? thx!

**Comment by liggitt** [comment]
What version of the Kubernetes API server are you seeing this in, and is this in a mutating admission webhook or validating admission webhook?

**Comment by liggitt** [comment]
This looks like https://github.com/kubernetes/website/issues/30574

The namespace attribute in the admission review (`.request.namespace`) is always populated correctly and is what admission webhooks should look at to determine the namespace of the request.

Prior to 1.24, the namespace field of the object contained in the admission review (`.request.object.metadata.namespace`) contained whatever the **user submitted in the body of their write request**. That could be blank or mismatched from the actual namespace of the request. After admission completed, a blank namespace in the object would be overridden by kube-apiserver with the actual namespace, and a mismatched namespace would be rejected by kube-apiserver.

In 1.24+, https://github.com/kubernetes/kubernetes/pull/94637 reordered the overriding/rejecting logic to happen _before_ admission, so admission webhooks running against 1.24+ servers see the actual namespace in `.request.object.metadata.namespace` as well as `.request.namespace`
