### ISSUE TITLE
k8s tests failing with openssh 9

### ISSUE THREAD

**Issue by vteratipally** [kubernetes/kubernetes#113941]
### Which jobs are failing?

The below tests are failing when we tried to update the openssh to version 9.1_p1

* Kubernetes e2e suite.[sig-node] SSH should SSH to all nodes and run commands
* Kubernetes e2e suite.[sig-storage] Flexvolumes should be mountable when non-attachable

Error:

```{ Failure /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/flexvolume.go:188
Nov 16 04:34:53.368: Unexpected error:
    <*errors.errorString | 0xc001327c10>: {
        s: "error getting SSH client to prow@35.222.173.30:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'",
    }
    error getting SSH client to prow@35.222.173.30:22: 'ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain'
occurred
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/test/e2e/storage/flexvolume.go:141}
```

### Which tests are failing?

* Kubernetes e2e suite.[sig-node] SSH should SSH to all nodes and run commands
* Kubernetes e2e suite.[sig-storage] Flexvolumes should be mountable when non-attachable

### Since when has it been failing?

after updating the openssh version to 9.1_p1

### Relevant SIG(s)

/sig testing

**Comment by vteratipally** [comment]
@SergeyKanzhelev

**Comment by vteratipally** [comment]
The tests are failing for the tests which are dependent on the 
/workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/onsi/ginkgo/internal/leafnodes/runner.go:113

go/src/k8s.io/kubernetes/test/e2e/node/ssh.go

**Comment by aojea** [comment]
from there are those logs?

> prow@35.222.173.30:22: 'ssh: handshake failed: ssh: unable to authenticate,

**Comment by vteratipally** [comment]
Context: I work in Container-Optimized OS team in Google. Majority of the kubernetes tests run on Container-Optimized OS Operating system. Whenever a package is updated, kubernetes e2e tests are run and two of the tests mentioned above are failing when openssh is updated to 9.1 where it 100% SSH 2.0 protocol.

**Comment by aojea** [comment]
oh, thanks, I was looking for the logs 

It seems those test use `x/crypto/ssh` , maybe some recent change on the golang library? 

https://github.com/golang/go/issues/56342

**Comment by aojea** [comment]
can you try with the snippet of code of the linked issue I pasted in my previous comment?

**Comment by BenTheElder** [comment]
Where possible tests should move to the hostexec pod technique instead of ssh, but not all tests have been migrated.
