### ISSUE TITLE
Volumes that use 'ready' files do not tear down those files

### ISSUE THREAD

**Issue by pmorie** [kubernetes/kubernetes#11398]
Currently there are two volumes (and one pending change for emptyDir) that use 'ready' files to indicate that `Setup` has already been run for a volume: secrets and git repo.  Neither of these volumes cleans up the ready file when the volume is torn down.

fyi @thockin

**Comment by thockin** [comment]
the ready flags should be stored in the pod-plugin dir, which gets nuked
when pods die.  Are you seeing something other than this?

**Comment by saad-ali** [comment]
> the ready flags should be stored in the pod-plugin dir, which gets nuked when pods die

@pmorie I'm going to close this. Please reopen if you expected different behavior.
