### ISSUE TITLE
cannot be created after being deleted

### ISSUE THREAD

**Issue by chenhaoenen** [kubernetes/kubernetes#113995]
### What happened?

hi, I delet one pod use
`
kubectl delete pods <pod> --grace-period=0 --force
`
after that , I creat this pod one again, but I fonud it cannot be created after being deleted
`
kubectl get pods -n Namespace
`
dont have the pod

### What did you expect to happen?

create the pod

### How can we reproduce it (as minimally and precisely as possible)?

xixi

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/kind support
/remove-kind bug

you should provide logs or snippets of the execution commands and a way to reproduce it

**Comment by neolit123** [comment]
please see https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
