### ISSUE TITLE
`kubectl get` returns different error for removed custom type with stale discovery cache

### ISSUE THREAD

**Issue by luebken** [kubernetes/kubernetes#113980]
### What happened?

I've installed a CRD and deleted again. kubectl gives different results when querying for the CRD before and after creating and deleting it.

### What did you expect to happen?

I would expect deleting a CRD would result in the same state as the cluster as before. 

Note that deleting the cache fixes the problem. 

### How can we reproduce it (as minimally and precisely as possible)?

```
$ kind create cluster --image kindest/node:v1.25.3
$ kubectl get crontabs
error: the server doesn't have a resource type "crontabs"


# via https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
$ kubectl apply -f resourcedefinition.yaml
customresourcedefinition.apiextensions.k8s.io/crontabs.stable.example.com created

$ kubectl get crontabs
No resources found in default namespace.

$ kubectl delete -f resourcedefinition.yaml
customresourcedefinition.apiextensions.k8s.io "crontabs.stable.example.com" deleted

$ kubectl get crontabs
Error from server (NotFound): Unable to list "stable.example.com/v1, Resource=crontabs": the server could not find the requested resource (get crontabs.stable.example.com)


$ rm -rf ~/.kube/cache/*
$ kubectl get crontabs
error: the server doesn't have a resource type "crontabs"
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-11-02T03:24:50Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>
kind create cluster --image kindest/node:v1.25.3
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kind create cluster --image kindest/node:v1.25.3
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
this is due to the cached discovery documents kubectl maintains, and will probably fall under the discovery / cache work in progress in https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3352-aggregated-discovery
