### ISSUE TITLE
Volume is unmounted while container still running during kubelet restart

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#113979]
### What happened?

We observed that while a container is in the process of being torn down, but not completed, the volume gets unmounted and then subsequently detached, causing the fs to enter read-only mode. This happened after kubelet restarted.
```
2022-11-03 02:42:32.404 PDT | I1103 09:42:32.404518 422257 reconciler.go:194] "operationExecutor.UnmountVolume started for volume "pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c" (UniqueName: "kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIFIED/zones/us-east1-c/disks/pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c") pod "cc4bf0b0-1610-4ae9-9cc1-64ec05a0ac72" (UID: "cc4bf0b0-1610-4ae9-9cc1-64ec05a0ac72") "
2022-11-03 02:42:32.410 PDT | NodeUnpublishVolume succeeded on projects/UNSPECIFIED/zones/us-east1-c/disks/pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c from /var/lib/kubelet/pods/cc4bf0b0-1610-4ae9-9cc1-64ec05a0ac72/volumes/kubernetes.io~csi/pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c/mount
2022-11-03 02:43:02.000 PDT | Stopping container ccpcndcjf2ns025utho0-acs-kc
```

We observed that on the restart, the volume was not added to DSW because the Pod was marked for deletion.
```
I1103 09:42:30.931278 422257 reconciler.go:420] "Reconciler sync states: could not find pod information in desired state, update it in actual state" reconstructedVolume=&{volumeName:kubernetes.io/csi/pd.csi.storage.gke.io^projects/UNSPECIFIED/zones/us-east1-c/disks/pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c podName:cc4bf0b0-1610-4ae9-9cc1-64ec05a0ac72 volumeSpec:0xc0023125e8 outerVolumeSpecName:pvc-c1ea4fda-3d81-4dd1-a04a-713f1cef603c pod:0xc004b2f000 volumeGidValue: devicePath: mounter:0xc000fb6870 deviceMounter:0xc0025cfbc0 blockVolumeMapper:<nil>}
```

### What did you expect to happen?

In the normal case, we only remove the pod from DSW when the containers have finished teardown: https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L232

However, in the reconstruction case, it looks like if a pod has started termination, but not necessarily completed, then we don't add the pod to DSW:
https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/kubelet/volumemanager/populator/desired_state_of_world_populator.go#L203

We probably need to be consistent and change the add pod criteria to also add even if it's started terminating. The side effect is that in the normal case we may do unnecessary mounts if a pod is quickly created and deleted. We can also consider a flag to only use the stricter check during reconstruction.

@kubernetes/sig-storage-bugs 

### How can we reproduce it (as minimally and precisely as possible)?

What happened in our env was that kubelet was crash looping, and then all the pods on the node were deleted.

It looks like there was a good 30 seconds between volume unmount and container teardown. I think this may be easily reproducible if the pod has a long graceful termination period and the container ignores the stop signal.

### Kubernetes version

<details>

1.22

</details>

### Cloud provider

<details>
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gnufied** [comment]
Yeah this looks problematic. What was the exact kube version btw? 

> We observed that while a container is in the process of being torn down, but not completed, the volume gets unmounted and then subsequently detached, causing the fs to enter read-only mode

So it was possible that container is still writing to the volume? Do we know why fs enters read-only mode when this happens? I know the behaviour of kubelet is problematic regardless, but still.

>  The side effect is that in the normal case we may do unnecessary mounts if a pod is quickly created and deleted. We can also consider a flag to only use the stricter check during reconstruction.

I think adding volumes belonging to terminating pod doesn't sound so bad. I wonder if we could change this to `ShouldPodRuntimeBeRemoved`.

**Comment by sunnylovestiramisu** [comment]
> We probably need to be consistent and change the add pod criteria to also add even if it's started terminating. 

Does this mean instead of checking ShouldPodContainersBeTerminating to decide if we add the pod or not, we should check IsPodTerminationRequested or not to decide?

**Comment by msau42** [comment]
For reconstruction, we need to keep the volume in DSW if there is a chance that containers are running. So `ShouldPodRuntimeBeRemoved` is the best call to determine that.

**Comment by FullyScaled** [comment]
@msau42 
We observed a similar issue but could only reproduce it with emptydir volumes. 

Do you think https://github.com/kubernetes/kubernetes/issues/114047 is the same issue?

**Comment by msau42** [comment]
@FullyScaled thanks for the report. I think this issue could impact emptydir volumes too.

**Comment by sunnylovestiramisu** [comment]
Is there any recommended way to make a pod having a long graceful termination period? Tried with some simple pods but it just terminated right away.

**Comment by FullyScaled** [comment]
> Is there any recommended way to make a pod having a long graceful termination period? Tried with some simple pods but it just terminated right away.

You can use the sample pod and instructions from here https://github.com/kubernetes/kubernetes/issues/114047

**Comment by jingxu97** [comment]
cc @jingxu97

**Comment by msau42** [comment]
Here is my repro pod and steps:

```
apiVersion: v1
kind: Pod 
metadata:
  name: nginx
spec:
  terminationGracePeriodSeconds: 120 
  containers:
  - name: nginx
    image: nginx:1.14.2
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 120"]
    ports:
    - containerPort: 80
    volumeMounts:
    - name: scratch
      mountPath: /scratch
  volumes:
  - name: scratch
    emptyDir:
```
1. `k apply -f pod.yaml`
1. `k exec -ti nginx --  /bin/bash`
1. In the pod shell, `while [ 1 ]; do date | tee -a /scratch/test; sleep 2; done`
1. In another window (window 2), ssh to the node
1. In another window (window 3), `k delete -f pod.yaml`
1. In window 2, `pkill kubelet`
1. Back in window 1, exec back into the pod
1. Try `ls /scratch`. The file will be gone.
1. Also try `touch /scratch/test`. It will return `touch: cannot touch 'test': No such file or directory`

When looking at kubelet logs, you'll see the log messages that indicate the volume was reconstructed without being added to dsw.

```
# journalctl -u kubelet|grep "Reconciler sync states"
Dec 15 03:11:26 kt2-59d1e4eb-a8e5-minion-group-72zz kubelet[41403]: I1215 03:11:26.264904   41403 reconstruct.go:102] "Reconciler sync states: could not find pod information in desired state, update it in actual state" reconstructedVolume=&{volumeName:kubernetes.io/empty-dir/8dde3a9c-1727-4a15-967e-0638eafd9487-scratch podName:8dde3a9c-1727-4a15-967e-0638eafd9487 volumeSpec:0xc0006dfcb0 outerVolumeSpecName:scratch pod:0xc000bd9c00 volumeGidValue: devicePath: mounter:0xc0003c6d90 deviceMounter:<nil> blockVolumeMapper:<nil> seLinuxMountContext:}
```

**Comment by sunnylovestiramisu** [comment]
Tested locally via kind cluster. 

1. k/k master is showing error of touch: cannot touch '/scratch/test': No such file or directory https://screenshot.googleplex.com/4CUKUpuwpDTrDB3.png
2. kind cluster with the fix in this pr shows no error: https://screenshot.googleplex.com/zZjCWwkBShgnpB2.png
And running ``` journalctl -u kubelet|grep "Reconciler sync states" ``` shows no result in the log.
