### ISSUE TITLE
Can't do a kubectl get on the TokenReview  kind

### ISSUE THREAD

**Issue by andrewrotherham** [kubernetes/kubernetes#114045]
### What happened?

Hi,
I'm searching for out of date apis in my k8s cluster  but when I try to do `kubectl get TokenReview  --all-namespaces ` , it comes back with `Error from server (MethodNotAllowed): the server does not allow this method on the requested resource`

It doesn't do this with any other resource kind ..... so far

### What did you expect to happen?

I was expecting a list of different yaml files of the kind "TokenReview"

for example 
![image](https://user-images.githubusercontent.com/66618878/203100210-47524e9d-174c-4091-9608-7fb2bd9434c1.png)

### How can we reproduce it (as minimally and precisely as possible)?

Just run kubectl get TokenReview  -all-namespaces 

### Kubernetes version

<details>

```console
$ kubectl version
# Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"reacted", GitTreeState:"clean", BuildDate:"redacted", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"redacted", GitTreeState:"clean", BuildDate:"redacted", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"



</details>


### Install tools

<details>
Helm,  kubectl
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by andrewrotherham** [comment]
hi sorry I don't know what /sig <group-name>means

**Comment by andrewrotherham** [comment]
sorry I've just looked at the link and I still don't get it....

**Comment by liggitt** [comment]
/remove-kind bug

TokenReview create requests are not persisted, they are answered with ephemeral responses. This means the token review API does not support read requests (get, list, watch, etc) or update/delete/patch requests, only create.

**Comment by andrewrotherham** [comment]
I can see something called tokenreviews but I can't do a -oyaml or describe on it
