### ISSUE TITLE
ExternalTrafficPolicy: Local does not work for NodePort Services

### ISSUE THREAD

**Issue by raja444** [kubernetes/kubernetes#114058]
### What happened?

NodePort Services with externalTrafficPolicy: Local.
While give curl request to ip:port <xx.xx.xx.xx:8080> from vm machine,  
In the pod able to receive the logs, but in the log clientIp is showing as "172.17.1.1" 

Actual external clientip is not showing.

### What did you expect to happen?

while we use externalTrafficPolicy as Local, it should Preserve the Client IP.
it should Forward to pod. but it is not happening.

### How can we reproduce it (as minimally and precisely as possible)?

# -*- mode: yaml; -*-
apiVersion: v1
kind: Service
metadata:
  name: sample
  labels:
    app: sample
    microservice: sample
    tier: backend
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - port: 8081
  selector:
    microservice: sample
    app: major
    tier: backend
  externalIPs:

    - xx.xx.xx.xx

After setting externaTrafficPolicy as Local,  give curl cmd curl -L -v http://xx.xx.xx.xx:8081/api/1.0/users

in the pod log, clientIp is showing as invalid ip 172.17.1.1. it should show external client ip.

### Kubernetes version

<details>

```console
$ kubectl version
 kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0",GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}


# paste output here
```

</details>

### Cloud provider

kubernets

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by raja444** [comment]
Please help me on this?
any configuration need to add?  where the problem is ?

**Comment by aojea** [comment]
externalTrafficPolicy applies to loadbalancers only , no?

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

@danwinship for confirmation

**Comment by cyclinder** [comment]
If I remember correctly, _externalTrafficPolicy_ applies to the NodePort and LoadBalancer services.

**Comment by raja444** [comment]
@cyclinder @aojea Now able get the clientIp as I followed the same steps which is mentioned in that link.
Thanks.

NodePort should be in this range 30000-32768.
is there any way i can use 8099 port ?? any alternative way is there?
could you please suggest?

**Comment by aojea** [comment]
> If I remember correctly, _externalTrafficPolicy_ applies to the NodePort and LoadBalancer services.

@cyclinder is right

@raja444 you may use the container `HostPort` https://alesnosek.com/blog/2017/02/14/accessing-kubernetes-pods-from-outside-of-the-cluster/

I'm going to close it since github issues are for bugs or problems with the code, for more support questions is better to use other channels like discourse, slack, stackoverflow, ...

/close
