### ISSUE TITLE
SUPPORT.md should be updated

### ISSUE THREAD

**Issue by rsoika** [kubernetes/kubernetes#114050]
### What would you like to be added?

on the [support page](https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md) it is mentioned that questions should be posted on [stackoverflow](https://stackoverflow.com). But doing so, my question was closed immediately because it was - of course - not about programming:

https://stackoverflow.com/questions/74518395/kubeadm-1-25-init-failed-on-debian-11-with-containerd-connection-refused

Maybe the SUPPORT.md page should better point to https://unix.stackexchange.com or https://serverfault.com/

### Why is this needed?

I think this is needed to direct users to the correct place to discuss questions about setup problems.

**Comment by kundan2707** [comment]
@rsoika its not like that you can only ask question on stackoverflow. you can ask question of other appropriate place like slack kubernetes forum too.

**Comment by kundan2707** [comment]
detail available on SUPPORT.md looks OK to me

**Comment by rsoika** [comment]
@kundan2707 I know that I can ask questions also on slack. But the problem is that on SUPPORT.md is a link pointing to stackoverflow.com which is wrong.
It should point either to  https://unix.stackexchange.com/ or https://serverfault.com/

**Comment by MichaelCade** [comment]
Maybe the order displayed should be better and start with the forum, slack and then stackoverflow and any other outlets for discussion?

**Comment by Sajiyah-Salat** [comment]
Can we add a line like if your questions get closed, ask in slack or we put slack particular channel at first. i am a beginner and I would like to add that. I need some suggestions and approvals to go ahead. Thank you.

**Comment by NitishKumar06** [comment]
I like the way @MichaelCade has mentioned tackling this issue. However, @Sajiyah-Salat Please raise a PR, we'd be happy to see what changes you bring.

**Comment by Sajiyah-Salat** [comment]
Sure, Thank you @NitishKumar06 for approval

**Comment by sftim** [comment]
I think this is already addressed - see https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE/config.yml and https://github.com/kubernetes/kubernetes/pull/104468

**Comment by rsoika** [comment]
I just want to briefly explain the actual reason for this issue:

On the support page is a link to Stackoverflow:

![image](https://user-images.githubusercontent.com/1339124/211062937-dd5adc30-d755-434c-99a8-0fc2b973bdd7.png)

But if you ask a Question about Kubernetes on Stackoverflow your question will be closed immediately because it is usually  not about programming!
We need to change the link to point to https://serverfault.com/ or https://unix.stackexchange.com/

**Comment by Sajiyah-Salat** [comment]
kind of agree with @rsoika but I think slack community is more active and It should be the first link any beginner get for asking question and then we would change as @rsoika ... Any more suggestions?

**Comment by rsoika** [comment]
One more suggestion: why not using the Github Discussion feature?

I think this would bring two advantages: 

1. The usage is similar to git issues and well known by the community (formatting, referring issues)
2. You can - only with one click - move an issue into the discussion. This helps to keep the issue list more clean.

Sed an example [here](https://github.com/eclipse-glsp/glsp/discussions)

It is also possible after activating the feature to move old issues into the discussion to fill it up. I think from the size of the Kubernetes issue list this would make sense.

**Comment by Sajiyah-Salat** [comment]
great idea @rsoika will surely add it.
