### ISSUE TITLE
Goroutine leak in EtcdMigrateServer 

### ISSUE THREAD

**Issue by Mskxn** [kubernetes/kubernetes#114070]
### What happened?
It's at [migrate_server.go](https://github.com/kubernetes/kubernetes/blob/master/cluster/images/etcd/migrate/migrate_server.go) line 111

When the server stopped before timeout, the first goroutine will be block on  `timeout <- true` because the receiver in the second goroutine is not exist. 
Changing `timeout` to a buffered one may fix it. #114071 
```
	stopped := make(chan bool)
	timedout := make(chan bool)
	go func() {                                   // first goroutine
		time.Sleep(gracefulWait)
		timedout <- true                // blocked
	}()
	go func() {                                   // second goroutine
		select {
		case <-stopped:
			return                          // return here
		case <-timedout:
			klog.Infof("etcd server has not terminated gracefully after %s, killing it.", gracefulWait)
			r.cmd.Process.Kill()
			return
		}
	}()
	err = r.cmd.Wait()
	stopped <- true
```

### What did you expect to happen?

no goroutine leaks

### How can we reproduce it (as minimally and precisely as possible)?

run related test with leak checker

### Kubernetes version

<details>
dev
</details>

### Cloud provider

<details>
unknown
</details>

### OS version

<details>
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lavalamp** [comment]
It should close the channel rather than write to it, that's the easiest fix
