### ISSUE TITLE
Field apiVersion is missing from events reported from taint manager

### ISSUE THREAD

**Issue by stingshen** [kubernetes/kubernetes#114083]
### What happened?

Events from node taint manager doesn't report involved object apiVersion:

![image](https://user-images.githubusercontent.com/6214067/203544886-75ce77dc-d6dd-46f6-8a71-012ac8fbdde6.png)

### What did you expect to happen?

apiVersion is reported as other events. For example:

![image](https://user-images.githubusercontent.com/6214067/203545729-ab9b1685-cedb-452d-a25b-8245dce108a8.png)

### How can we reproduce it (as minimally and precisely as possible)?

1. Run a pod on node A (not master)
2. Switch off node A
3. Event `Marking for deletion Pod...` is reported, but without apiVersion in involvedObject.

### Anything else we need to know?

The apiVersion is not reported in taint_manager.go The issue is still not fixed in master:

![image](https://user-images.githubusercontent.com/6214067/203545491-6e320cd2-f79e-4aa0-9177-38c1683b1344.png)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:54:01Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.3-1+db95af67a8a660", GitCommit:"db95af67a8a660dc53ac09b8475161de2f5c711e", GitTreeState:"clean", BuildDate:"2021-01-22T07:24:32Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Irrelevant
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by TommyStarK** [comment]
Would it be acceptable to add a field `ApiVersion` [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/types/namespacedname.go#L27-L39) and update all affected files accordingly ? 

Introducing this new attribute like below

```go
type NamespacedName struct {
        ApiVersion string
	Namespace string
	Name string
}
```

This way it would be available as input for the workers in the taint manager

```go
type WorkArgs struct {
	NamespacedName types.NamespacedName
}
```

If yes may I give it a try ?

**Comment by aojea** [comment]
one suggestion @aimuz @tommystark you should wait for the corresponding SIG to triage the issue and accept it before sending PRs, the chances of your PR getting reviewed and approver are much higher

**Comment by aojea** [comment]
> You are right @aojea, sorry about that. It won’t happen again.

no no worries, it was a suggestion, is not that you did something wrong, but it is possible that your PR doesn't get reviews and you get frustrated

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

please re-add if this is node-related issue

**Comment by stingshen** [comment]
> /remove-sig node
> 
> please re-add if this is node-related issue

I think it is a node related issue. The root cause in `node` taint manager.
