### ISSUE TITLE
Dead link for "Node Allocatable" in doc page Kubelet Configuration (v1beta1)

### ISSUE THREAD

**Issue by vishvikkrishnan** [kubernetes/kubernetes#114019]
The link to documentation on ["Node Allocatable"](https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md) is dead. The page was autogenerated. 

I found a document with the same name within the Kubernetes project [as an archived repo](https://github.com/kubernetes/design-proposals-archive/blob/main/node/node-allocatable.md).

Please update the link or remove the reference if it's no longer relevant.

Source webpage: https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

**Comment by sftim** [comment]
I would link instead to https://k8s.io/docs/tasks/administer-cluster/reserve-compute-resources/#node-allocatable

**Comment by nitishchauhan0022** [comment]
Issue is solved by #115604
/close
