### ISSUE TITLE
Changelog for v1.23.14 says 1.23.13 has the fix

### ISSUE THREAD

**Issue by ceich** [kubernetes/kubernetes#114087]
### What happened?

The [Important Security Information](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#important-security-information) section of the Changelog for 1.23.14 (and sibling bugfix releases) says that 1.23.13 both has the vuln and also has the fix.

### What did you expect to happen?

The Fix version should be 1.23.14 in the above and sibling changelogs.

### How can we reproduce it (as minimally and precisely as possible)?

Load the link above.

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by ialidzhikov** [comment]
cc @xmudrii

**Comment by pacoxu** [comment]
For v1.23.14, the title is `Changelog since v1.23.13`. This seems to be valid.

`Changelog since v1.23.13` means `change log for v1.23.14 that is after v1.23.13 was released.`

**Comment by ceich** [comment]
> For v1.23.14, the title is `Changelog since v1.23.13`. This seems to be valid.
> 
> `Changelog since v1.23.13` means `change log for v1.23.14 that is after v1.23.13 was released.`

You're looking at the wrong text. Follow the link and see .13 in both lists: 

### Affected Versions:

kube-apiserver v1.25.0 - v1.25.3
kube-apiserver v1.24.0 - v1.24.7
kube-apiserver v1.23.0 - v1.23.**13**
kube-apiserver v1.22.0 - v1.22.15
kube-apiserver <= v1.21.?

### Fixed Versions:

kube-apiserver v1.25.4
kube-apiserver v1.24.8
kube-apiserver v1.23.**13**
kube-apiserver v1.22.16
```

**Comment by pacoxu** [comment]
Got it. Thanks for pointing out the location.

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/kubernetes/pull/114096 to fix it.

**Comment by xmudrii** [comment]
/reopen
@pacoxu Can you please cherry-pick #114096 to the release branches (1.25-1.22)?

**Comment by pacoxu** [comment]
> /reopen @pacoxu Can you please cherry-pick #114096 to the release branches (1.25-1.22)?

Of course. Done
- https://github.com/kubernetes/kubernetes/pull/114102
- https://github.com/kubernetes/kubernetes/pull/114103
- https://github.com/kubernetes/kubernetes/pull/114104
- https://github.com/kubernetes/kubernetes/pull/114101

**Comment by xmudrii** [comment]
Cherry-picks are done, thanks a lot @pacoxu!
/close
