### ISSUE TITLE
CPUset based on container with integer cpu resource/limit instead of on pod

### ISSUE THREAD

**Issue by ryanlyy** [kubernetes/kubernetes#114130]
### What would you like to be added?

in current kubernetes version, only when container with request/limit cpu is integer, this container will be affinity to one one or mulitple cores. But when the request/limit cpu of all containers in pod is not integer but the sum of containers in this pod is integer, all the containers are not affinity into one or multiple cores. Frankly, there are more communication between containers in one pod, if pod request/limit cpu is integer and affinity all containers of that pod into one core or mulitple core, it will achieve more high performances.

can kubernetes support above?

Thanks a lot.

### Why is this needed?

to achieve better performance.

**Comment by aimuz** [comment]
This is an interesting feature, I think it's good, and it avoids interference between Pods in this case

**Comment by aimuz** [comment]
https://github.com/koordinator-sh/koordinator

I found an open source project that seems to fulfill the needs of this area and can be used as a reference
