### ISSUE TITLE
VolumeMount support in ephemeral containers with kubectl debug

### ISSUE THREAD

**Issue by cshiv** [kubernetes/kubernetes#114184]
### What would you like to be added?

At present, I cannot attach an ephemeral container with a volume mount by using "kubectl debug".
I would prefer to have some way to create an ephemeral container with volume mount using kubectl debug.
It could be something similar to [patch command](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/#alternate-forms-of-the-kubectl-patch-command)

I don't know if it's already possible to do it.[Blog](https://iximiuz.com/en/posts/kubernetes-ephemeral-containers/) indicates one way of doing it with API call, but kubectl debug would be much easier.

### Why is this needed?

Real world use case would be - 
Use case - I have a statefulset with a PVC where I store all the data related to the application. When the app crashes and it needs to be investigated, it is only possible to share net and pid namespace. If I want to investigate the file system it's just not possible as containers use different mount space.
By using the same volume mount as the crashing container of the pod, it is possible to check the data present in the PVC.  There might be security concerns also with this , but it needs to be explored

**Comment by cshiv** [comment]
Hello,
Any updates on this ?

**Comment by AverageMarcus** [comment]
/reopen

This would still be very useful. 

I had an issue with Redis this morning which I'd have liked to have solved using `kubectl debug` but needed to manually mount the volume into the container.

**Comment by cshiv** [comment]
/reopen.
This feature could be extremely useful for troubleshooting stateful applications.
