### ISSUE TITLE
Wrong memory usage reported by kubectl top node

### ISSUE THREAD

**Issue by jingjingliu20** [kubernetes/kubernetes#114124]
### What happened?

We are on Kubernetes 1.23.12. We notice the memory usage wrongly reported by `kubectl top node`, see below:

The node `/proc/meminfo` output, memory usage is low as about 3G/16GB.
```
cat /proc/meminfo
MemTotal:       16393712 kB
MemFree:         2900416 kB
MemAvailable:   12920900 kB
Buffers:          419296 kB
Cached:         11425200 kB
SwapCached:            0 kB
Active:          6342916 kB
Inactive:        6336704 kB
```

But with `kubectl top node aks-e2sv3b-20744423-vmss000001` the memory usage is 64%, pretty larger than the actual usage.
```
NAME                             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
aks-e2sv3b-20744423-vmss000001   1166m        61%    8153Mi          64%
```
Is there a known bug? As with the the wrong memory usage, the node will die of OOM and pod evicted finally.

### What did you expect to happen?

Report memory usage correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce it on Kubernetes 1.23.12, after some load, monitor the node real memory usage and the data returned by `kubectl top node`

### Kubernetes version

<details>
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"f941a31f4515c5ac03f5fc7ccf9a330e3510b80d", GitTreeState:"clean", BuildDate:"2022-11-09T17:12:33Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>
```
 cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kundan2707** [comment]
/proc/meminfo is  not containerized. Meaning that they are not cgroup-aware. They will always display memory numbers from the host system (physical or virtual machine) as a whole. Processes inside a container can not rely on free, top and others to determine how much memory they have to work with; they are subject to limits imposed by their cgroups and can’t use all the memory available in the host system.

**Comment by jingjingliu20** [comment]
Figured it out. The usage is not wrong. Close this one.
