### ISSUE TITLE
Improve performance of NodeResourcesFit scoring

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#114121]
### What would you like to be added?

Profiling reveals that a non-negligible amount of time is wasted creating and querying small maps (example: `make(resourceToValueMap)`, with an expected size of 2 or 3). I believe we should be able to replace them with slices for a performance boost.

We should build unit-level benchmarks to proof that the improvements are good, similar to https://github.com/kubernetes/kubernetes/blob/8f2371bcceff7962ddb4901c36536c6ff659755b/pkg/scheduler/framework/plugins/podtopologyspread/scoring_test.go#L1272

### Why is this needed?

While the plugin has decent performance, if we try to push the limits of kube-scheduler, there's still room for improvement.

**Comment by aojea** [comment]
> I believe we should be able to replace them with slices for a performance boost.

have you considered sync.Pool? https://pkg.go.dev/sync#example-Pool

**Comment by alculquicondor** [comment]
That sounds like more overhead than a simple slice. These are all sync operations.

**Comment by ruquanzhao** [comment]
Hi, @alculquicondor
Could I take a shot on this?

If I understand correctly,
we need a `func BenchmarkTestFitScore()` in `fit_test.go`, then compare slices and small maps.

**Comment by alculquicondor** [comment]
yes, that's roughly the plan. There will be a lot of trial-and-error.

**Comment by tangwz** [comment]
> /assign

@ruquanzhao I've already started. Do you want to continue?

**Comment by alculquicondor** [comment]
/unassign @ZhaoRuquan

This was already assigned.

**Comment by tangwz** [comment]
@alculquicondor 

If I understand correctly, I need to add a test function like `mostResourceScorer` and use  `resourceToValueSlice` instead of `resourceToValueMap`, then add a `func BenchmarkTestFitScore()` in `fit_test.go` and run it.

https://github.com/kubernetes/kubernetes/blob/8f2371bcceff7962ddb4901c36536c6ff659755b/pkg/scheduler/framework/plugins/noderesources/most_allocated.go#L29

**Comment by tangwz** [comment]
> I suggest you first add the benchmark. Then, try to replace the maps with slices. Probably both `resourceToValueMap` and `resourceToWeightMap`. You can use the profiler on the benchmark to see the effects of your changes.

Thanks.
