### ISSUE TITLE
Reserved an statically port range for nodeport 

### ISSUE THREAD

**Issue by xuzhenglun** [kubernetes/kubernetes#114129]
### What would you like to be added?

just like [KEP-3070](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3070-reserved-service-ip-range) did, I want to reserve some port for nodeport.  I can try to submit an KEP if it sound good for sig/network.

### Why is this needed?

In our cluster, some applications are NOT deployed in Kubernetes. But they need to connect to `service` in Kubernetes too.

For example, some applications need to connect to the `minio` service but they have no idea what cluster-ip it is. In our situation, those applications just connect to a specific port (30009) of the Kubernetes master node.

This situation works most time, but in something 30009 is allocated by something else. And minio service will be failed to applied.

**Comment by aojea** [comment]
I don't see why not, WDYT @thockin ?

**Comment by thockin** [comment]
I told you it would follow :)
