### ISSUE TITLE
Link for cloud-controller-manager  is not working.

### ISSUE THREAD

**Issue by Shubham82** [kubernetes/kubernetes#114161]
**Problem:**

The Link for `cloud-controller-manager` under [FAQ](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#how-does-cluster-autoscaler-remove-nodes) is not working. It redirects to k8s v1.19 docs, which are not supported now by k8s. and this cloud-controller-manager reference page is removed in k8s v1.20. There is no reference page for it in k8s docs.
There is only the [Cloud Controller Manager](https://kubernetes.io/docs/concepts/architecture/cloud-controller/) doc mentioned under k8s docs.

**Proposed Solution:**
Either we will remove Cloud-Controller-Manager or Update the link to `https://kubernetes.io/docs/concepts/architecture/cloud-controller/ `. 

**Page to Update:**
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

**Comment by Shubham82** [comment]
Hi @gjtempleton @mwielgus 
PTAL!

**Comment by aojea** [comment]
> **Page to Update:**
> https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md

/transfer kubernetes/autoscaler

**Comment by Shubham82** [comment]
Hi @aojea, sorry by mistake I opened it in k/k.

Thanks

**Comment by Shubham82** [comment]
I will close it from here and reopen it in Kuberenetes/autoscaler again.
