### ISSUE TITLE
Deleting DaemonSet with GracePeriodSeconds with DeletePropagationBackground is not honoured by the pods

### ISSUE THREAD

**Issue by inianv** [kubernetes/kubernetes#114113]
### What happened?

I am encountering a scenario, where I'm deleting a DaemonSet with the following delete options set. The propagation policy, grace period seconds are defined at as part of [DeleteOptions](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#DeleteOptions) struct.

```go
gracePeriod := int64(300)
propagationPolicy := metav1.DeletePropagationBackground
deleteOptions := metav1.DeleteOptions{
        PropagationPolicy:  &propagationPolicy,
        GracePeriodSeconds: &gracePeriod,
}

// deleting the daemonset with the above option
if err := k.clientset.AppsV1().DaemonSets(namespace).Delete(ctx(), name, deleteOptions); err != nil {
        return err
}
```

The daemonset deletion was successful, but none of the pods were inheriting the `GracePeriodSeconds` of 300, but only taking the default value of 30 and `DeletionTimestamp` was only set to 30s into the future

### What did you expect to happen?

We expected the pods managed by that daemonset to be deleted (i.e. with the above options) should have the `GracePeriodSeconds` to be 300. e.g. the pods of the daemonset should have the following

- `DeletionTimestamp` as part of https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1#ObjectMeta, should be set 300s in the future from which the daemonset delete was initiated. 
- `DeletionGracePeriodSeconds` should be set to 300, which was set as part of the delete options foe the daemonset

e.g. if the daemonset deletion happened at `time="2022-11-24T11:32:33Z"`, the `DeletionTimestamp` should be five minutes in the future, i.e. at `time="2022-11-24T11:37:33Z"` and `DeletionGracePeriodSeconds` be set to 300

### How can we reproduce it (as minimally and precisely as possible)?

Was not able to recreate a straightforward way to simulate this

### Kubernetes version

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:40:19Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.14", GitCommit:"3321ffc07d2f046afdf613796f9032f4460de093", GitTreeState:"clean", BuildDate:"2022-11-09T13:32:47Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

<details>

</details>

### OS version

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux  5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Container runtime (CRI) and version (if applicable)

docker://20.10.12

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Latest version of Calico - https://docs.projectcalico.org/manifests/calico.yamlhttps://docs.projectcalico.org/manifests/calico.yaml

**Comment by shuaizi** [comment]
@inianv 

now just  pod  implements the interface [RESTGracefulDeleteStrategy]  for graceful deletion.
https://github.com/kubernetes/kubernetes/blob/70617042976dc168208a41b8a10caa61f9748617/staging/src/k8s.io/apiserver/pkg/registry/rest/delete.go#L58-L64, 

test for ds deletion，found the deletionGracePeriodSeconds of daemonset is not configued,
![image](https://user-images.githubusercontent.com/3830129/204177752-9732c789-89be-44c1-aae9-102905923842.png)

I think it's a design solution issue,  should we pass the DeleteOptions to cascade resources when deleting?
need more discussion.

btw, you can set .template.Spec.TerminationGracePeriodSeconds : 300  to realize your needs.
