### ISSUE TITLE
When I update the deployment replicas to 0, I immediately call GetPodsForDeployment. At this time, I get the error expected a new replica set for deployment

### ISSUE THREAD

**Issue by 467892746** [kubernetes/kubernetes#114147]
### What happened?

When I update the deployment replicas to 0, I immediately call GetPodsForDeployment. At this time, I get the error expected a new replica set for deployment。When I call again after a few seconds, the empt pod list will be returned。
The GetPodsForDeployment method is located in kubernetes/test/e2e/framework/deployment/fixtures。

### What did you expect to happen?

empty pod list。

### How can we reproduce it (as minimally and precisely as possible)?

set deployment replicas to 0,  Call GetPodsForDeployment(kubernetes/test/e2e/framework/deployment/fixtures) method immediately。

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8", GitCommit:"4a3b558c52eb6995b3c5c1db5e54111bd0645a64", GitTreeState:"clean", BuildDate:"2021-12-15T14:52:11Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
aws
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> The GetPodsForDeployment method is located in kubernetes/test/e2e/framework/deployment/fixtures。

where are you using that method? that is not supposed to be used outside of kubernetes

**Comment by 467892746** [comment]
> > The GetPodsForDeployment method is located in kubernetes/test/e2e/framework/deployment/fixtures。
> 
> where are you using that method? that is not supposed to be used outside of kubernetes

In my own code. Is there a third package that can be referenced outside of kubernetes?
