### ISSUE TITLE
Headless service is not doing the proper load balancing in Round Robin manner.

### ISSUE THREAD

**Issue by taju20910** [kubernetes/kubernetes#114128]
### What would you like to be added?

50 - 50 Load distribution in Headless service

Service is created as below: 

apiVersion: v1
kind: Service
metadata:
  name: ccs-fscc
  labels:
    app: ccs-fscc
spec:
  clusterIP: None
  selector:
    app: ccs-fscc
  ports:
    - port: 5073
      protocol: TCP
  type: ClusterIP

Currently load is getting shared in 60-40 ratio

### Why is this needed?

I want to route traffic to servers in round robin manner to distribute load.

/sig node

**Comment by aimuz** [comment]
If I remember correctly, when the Service is Headless, the DNS query returns a set of Pod IPs, which should be implemented by the calling end if you want to achieve load balancing

**Comment by taju20910** [comment]
> If I remember correctly, when the Service is Headless, the DNS query returns a set of Pod IPs, which should be implemented by the calling end if you want to achieve load balancing
@aimuz 
Calling headless service gives POD IP at a time . My expectation is that it should give the same in load balanced fashion without calling needing to put any new logic

**Comment by aimuz** [comment]
Headless does not support this approach, DNS returns depend on coredns, if you want to achieve the load effect you can use cluster IP

**Comment by chrisohaver** [comment]
Most default deployments of CoreDNS use the _loadbalance_ plugin to return pod IPs of a headless service in a random order. And most clients will usually just use the first IP returned.
There was a bug fix to the randomization algorithm [some time ago in CoreDNS 1.8.7](https://github.com/coredns/coredns/pull/4961), although IIRC that would not have affected shuffling 2 IPs.

**Comment by taju20910** [comment]
@aimuz @chrisohaver Thank you guys for the input.
I have tried using ClusterIP service. Still I am not getting the required behaviour. My services look like below :
**C:\Users\Tajamul>kubectl describe svc ccs-fscc**
Name:              ccs-fscc
Namespace:         default
Labels:            app=ccs-fscc
Annotations:       <none>
Selector:          app=ccs-fscc
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.107.61.126
IPs:               10.107.61.126
Port:              fs  5073/TCP
TargetPort:        5073/TCP
Endpoints:         10.1.24.216:5073,10.1.24.217:5073
Port:              fss  5074/TCP
TargetPort:        5074/TCP
Endpoints:         10.1.24.216:5074,10.1.24.217:5074
Session Affinity:  None
Events:            <none>

**C:\Users\Tajamul>kubectl describe endpoints ccs-fscc**
Name:         ccs-fscc
Namespace:    default
Labels:       app=ccs-fscc
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2022-11-29T08:34:27Z
Subsets:
  Addresses:          10.1.24.216,10.1.24.217
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    fs    5073  TCP
    fss   5074  TCP

Events:  <none>

**Comment by aimuz** [comment]
Here's my test in the cluster

create service

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/helloworld/helloworld.yaml -l service=helloworld -n cluster-ip-test
```

deploy v1 helloworld

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/helloworld/helloworld.yaml -l version=v1 -n cluster-ip-test
```

deploy v2 helloworld

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/helloworld/helloworld.yaml -l version=v2 -n cluster-ip-test
```

deploy client

```
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.16/samples/sleep/sleep.yaml -n cluster-ip-test
```

get service

```
kubectl get svc -n cluster-ip-test
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
helloworld   ClusterIP   10.106.41.237   <none>        5000/TCP   9m33s
sleep        ClusterIP   10.110.47.228   <none>        80/TCP     8m49s
```

get ep

```
kubectl get ep -n cluster-ip-test
NAME         ENDPOINTS                           AGE
helloworld   10.244.4.25:5000,10.244.4.26:5000   10m
sleep        10.244.3.21:80                      9m17s
```

get pod 

```
kubectl get pod -n cluster-ip-test -o wide
NAME                             READY   STATUS    RESTARTS   AGE     IP            NODE             NOMINATED NODE   READINESS GATES
helloworld-v1-78b9f5c87f-fcf6v   1/1     Running   0          8m55s   10.244.4.25   cluster2-node2   <none>           <none>
helloworld-v2-54dddc5567-5zkb7   1/1     Running   0          8m52s   10.244.4.26   cluster2-node2   <none>           <none>
sleep-78ff5975c6-t9l6g           1/1     Running   0          9m44s   10.244.3.21   cluster2-node1   <none>           <none>
```

Validation calls
```
kubectl exec -n cluster-ip-test -c sleep \
    "$(kubectl get pod -n cluster-ip-test -l \
    app=sleep -o jsonpath='{.items[0].metadata.name}')" \
    -- curl helloworld.cluster-ip-test:5000/hello -s
```

Multiple executions 

```
Hello version: v1, instance: helloworld-v1-78b9f5c87f-fcf6v
Hello version: v2, instance: helloworld-v2-54dddc5567-5zkb7
Hello version: v2, instance: helloworld-v2-54dddc5567-5zkb7
Hello version: v1, instance: helloworld-v1-78b9f5c87f-fcf6v
```

**Comment by taju20910** [comment]
@aimuz I see you are using a single container port 5000 in helloworld clusterIP service. I am personally using two port for clusterIP service. Can it be the reason ?
apiVersion: v1
kind: Service
metadata:
  name: ccs-fscc
  labels:
    app: ccs-fscc
spec:
#  clusterIP: None
  selector:
    app: ccs-fscc
  ports:
  **- name: fs
    port: 5073
    protocol: TCP
    targetPort: 5073
  - name: fss
    port: 5074
    protocol: TCP
    targetPort: 5074**
  type: ClusterIP
---

**Comment by aojea** [comment]
just curious, why the need of 50/50 ? I mean, statistically in the long term it will get there, but why the need for such precision?
