### ISSUE TITLE
kmsv2: unit and integration test requirements

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#114188]
**Reference implementation**

- [ ] unit tests for all new code added for reference implementation
  - [x] ~75% coverage
  - [ ] controllers should have step tests and tests the run actual go routines
- [ ] an e2e conformance suite that uses the reference implementation
  - [x] all resources would be encrypted
  - [ ] the "remote" kms would be a local encryption key that adds 100 ms latency
  - [x] ~~key hierarchy would be used~~
- [ ] add new integration tests that use the reference implementation instead of the base64 plugin

**Storage migration**

1. If you have some way to observe API server state,
1. then a kms v2 plugin can change its write key and shortly thereafter,
1. running storage migration will use the new key

An integration test could observe API server state by poking at etcd directly
Thus you should be able to have an integration test that changes the plugin's write key at runtime and then run storage migration and observe the new key being used

**Storage Version API**

TBD

**Comment by ritazh** [comment]
As of c5cd7a1 code coverage:

- Reference implementation:
k8s.io/kubernetes/staging/src/k8s.io/kms/internal	0.879s	coverage: 75.0% of statements
k8s.io/kubernetes/staging/src/k8s.io/kms/pkg/hierarchy	1.453s	coverage: 88.6% of statements
k8s.io/kubernetes/staging/src/k8s.io/kms/pkg/service	0.257s	coverage: 77.4% of statements

- apiserver [only showing components with lower than 75% coverage):
k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/metrics	coverage: 68.7% of statements
k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig	0.468s	coverage: 72.0% of statements

Missing tests to add:
- [ ] Integration tests to check rotation is possible without restarting API server
- [ ] Integration tests that exercise the feature enablement/disablement flow

e2e (pending CI changes)
- [ ] Run the e2e suite against a kind cluster without kms encryption enabled.
- [ ] Compare request_duration_seconds, request_terminations_total, request_aborts_total API server metrics between the two runs. The acceptable delta should be less than 20%.
- [ ] [Manually]Observe metrics from the reference implementation to determine time taken at each step of the encryption/decryption process.
- [ ] [Manually]Observe API server startup time with and without kms encryption enabled.

Reference implementation:
- [ ] Provide an example implementation using pkcs11

**Comment by ritazh** [comment]
> apiserver [only showing components with lower than 75% coverage):
k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/metrics coverage: 68.7% of statements
k8s.io/kubernetes/staging/src/k8s.io/apiserver/pkg/server/options/encryptionconfig 0.468s coverage: 72.0% of statements

working on this next

**Comment by nilekhc** [comment]
> Missing tests to add:
>
> Integration tests to check rotation is possible without restarting API server

working on this next

**Comment by enj** [comment]
In regards to PKCS11 we will probably need to use SoftHSM.  Some resources that might help:

- https://github.com/psmiraglia/docker-softhsm
- https://github.com/theparanoids/crypki
- https://banzaicloud.com/docs/bank-vaults/hsm/softhsm

**Comment by ritazh** [comment]
> Integration tests that exercise the feature enablement/disablement flow

Working on this next

**Comment by aramase** [comment]
I'm looking into the PKCS11 implementation with SoftHSM

**Comment by aramase** [comment]
Issue for tracing: https://github.com/kubernetes/kubernetes/issues/120881

**Comment by ritazh** [comment]
/close

closing this parent issue in favor of specific child issues
