### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Verify extended resources are correctly reported in ContainerStatus Resources

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#114159]
### What would you like to be added?

In-place pod resize feature adds Resources field to ContainerStatus struct. This is used to report CPU and memory requests & limits configured for the containers. We should ensure that it also reports extended resources assigned to the containers.

See discussion: https://github.com/kubernetes/kubernetes/pull/102884#discussion_r817193401

### Why is this needed?

Without this, Status resources will not accurately reflect the desired Spec Resources allocated to the containers. This is a beta blocker for In-place pod resize feature.

**Comment by iholder101** [comment]
Hey @vinaykul!
Is this issue still relevant? Is somebody actively working on it?

**Comment by vinaykul** [comment]
Yes. This is required for beta.
/reopen
/assign @iholder101

**Comment by tallclair** [comment]
I'm afraid I still don't understand the motivation for this issue. Who are the expected consumers of this information? Why can't they read the resources from the spec?

**Comment by vinaykul** [comment]
> I'm afraid I still don't understand the motivation for this issue. Who are the expected consumers of this information? Why can't they read the resources from the spec?

@tallclair This change is required to make things simpler for o11y/monitoring/reporting tools.

They are currently reading from the spec, and that works today because a running pod is assumed to have acquired all the resources in requested after successful `canAdmitPod`.

My pod API change breaks that as CPU/memory spec may no longer reflect actual config. So we want o11y tools to switch over to reading actual resources from podStatus. Without this, they will have to do stuff like
```go
if resourceType == ResourceCPU || resourceType == ResourceMemory {
    readStatus(...)
} else {
    readSpec(...)
}
```

And if we add support for mutating other resource types in the future, tools will have to start closely tracking which release has what resources in podStatus to read from. It can get ugly very fast.

**Comment by tallclair** [comment]
/triage accepted

After some offline discussions, I've come around to this. I also clarified the desired behavior in the KEP: https://github.com/kubernetes/enhancements/pull/4704/commits/a093b5b260a5016a5c6feb4407728fa1d1ee7dfd
