### ISSUE TITLE
Add option to customise default ClusterFirst DNS options from the host

### ISSUE THREAD

**Issue by adammw** [kubernetes/kubernetes#114173]
### What would you like to be added?

Ability to customise the default DNS options provided to a pod's `/etc/resolv.conf` when using the DNSClusterFirst policy that would be provided in addition to the default "ndots:5" or any other options specified in the Pod's DNSConfig spec fields. 

### Why is this needed?

Currently the options in the host's resolv.conf (or the file specified in the resolvConf config parameter) are ignored and replaced with hardcoded [defaultDNSOptions](https://github.com/kubernetes/kubernetes/blob/70617042976dc168208a41b8a10caa61f9748617/pkg/kubelet/network/dns/dns.go#L45) of "ndots:5". While a pod can customise the options using the Pod's dnsConfig spec field, a cluster administrator may want to provide certain defaults to all pods, for example to set options most suitable to their DNS configuration.

**Comment by aimuz** [comment]
Will this meet the demand?

```
kubectl explain pod.spec.dnsConfig
```

```
KIND:     Pod
VERSION:  v1

RESOURCE: dnsConfig <Object>

DESCRIPTION:
     Specifies the DNS parameters of a pod. Parameters specified here will be
     merged to the generated DNS configuration based on DNSPolicy.

     PodDNSConfig defines the DNS parameters of a pod in addition to those
     generated from DNSPolicy.

FIELDS:
   nameservers  <[]string>
     A list of DNS name server IP addresses. This will be appended to the base
     nameservers generated from DNSPolicy. Duplicated nameservers will be
     removed.

   options      <[]Object>
     A list of DNS resolver options. This will be merged with the base options
     generated from DNSPolicy. Duplicated entries will be removed. Resolution
     options given in Options will override those that appear in the base
     DNSPolicy.

   searches     <[]string>
     A list of DNS search domains for host-name lookup. This will be appended to
     the base search paths generated from DNSPolicy. Duplicated search paths
     will be removed.

```

**Comment by adammw** [comment]
As mentioned, dnsConfig can customise the options on a per-pod level, but that would mean the cluster-administrator would need to mutate every pod's dnsConfig to be able to apply a cluster-wide DNS option.

**Comment by aimuz** [comment]
I'm sorry for not reading carefully before, I understand what you mean.

Are you trying to set the ndots to a larger value?

A more general approach is probably to modify the created Pods by mutatingwebhookconfigurations
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

**Comment by thockin** [comment]
The workaround here is a mutating admission control webhook.  It's maybe not awesome, but it does work and is GA.

The alternative would be to add a tiny new configuration API (or make this the start of a larger config API).  That's a lot of work and maintenance for something which doesn't have a lot of demand (judging by the fact that this has not come up before, or at least not often).

I'll leave this open to collect feedback, but I am leaning towards not accepting this idea.
