### ISSUE TITLE
Optimize NodeVolumeLimits plugin

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#114143]
### What would you like to be added?

For pods that only use secrets and configmaps, this plugin adds some overhead at scale. @msau42  does this plugin need to run for those types of volumes at all? If not, we can add a PreFilter to evaluate if Filter can exit early.

### Why is this needed?

Improve performance at scale.

/sig scheduling
/sig storage

**Comment by tangwz** [comment]
@ahg-g I think I can help with this one after the discussion.

**Comment by msau42** [comment]
Yes, I think we can add a check for the volume types.

**Comment by ahg-g** [comment]
@tangwz do you want to work on this one?

**Comment by tangwz** [comment]
> @tangwz do you want to work on this one?

/assign

Yes.

**Comment by tangwz** [comment]
Hi, @ahg-g 
I understand correctly, we need add a `func PreFilter()` in `csi.go` and `non_csi.go`, then if we found pods that only use secrets and configmaps, we can exit before Filter.

**Comment by kerthcet** [comment]
This can be followed after https://github.com/kubernetes/kubernetes/pull/114125, for pods don't use volumes, return `Skip` in prefilter, then we'll skip the Filter phase for the sake of performance.

**Comment by tangwz** [comment]
> This can be followed after #114125, for pods don't use volumes, return `Skip` in prefilter, then we'll skip the Filter phase for the sake of performance.

Thanks, let me have a try.

**Comment by tangwz** [comment]
> This can be followed after #114125, for pods don't use volumes, return `Skip` in prefilter, then we'll skip the Filter phase for the sake of performance.

So I should do it locally and then wait for the PR merged before submitting?

**Comment by ahg-g** [comment]
Yes, or you can wait until that PR is merged

**Comment by sanposhiho** [comment]
@tangwz I created ☔  issue: https://github.com/kubernetes/kubernetes/issues/114399
Allow me to mention you there. Also, if you get interested in some other plugins' optimization, please feel free to comment on the issue by the way :)

**Comment by alculquicondor** [comment]
#114125 merged, so you can work on this now.

**Comment by kidddddddddddddddddddddd** [comment]
@tangwz Do you still want to work on this one? I can take over this issue if you don't have enough time.

**Comment by tangwz** [comment]
Yes  I will do it

**Comment by tangwz** [comment]
> #114125 merged, so you can work on this now.

Get. I will do it.
