### ISSUE TITLE
The default stabilizationWindowSeconds of scaling down in HPA is not explicit 

### ISSUE THREAD

**Issue by tossmilestone** [kubernetes/kubernetes#114100]
### What happened?

If the `stabilizationWindowSeconds` of scaling down in HPA is `nil`, the hpa controller will use `300` as the default value, and won't change the value to `300` in the object. 

This is not explict for what the stabilizationWindowSeconds is on querying the resource, and will make some confusion.

### What did you expect to happen?

The `stabilizationWindowSeconds` of scaling down in HPA should be explicitly defaulted in the resource object.

### How can we reproduce it (as minimally and precisely as possible)?

Create a HPA with default scaling behavior.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.25
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mucahitkantepe** [comment]
This has confused us as well, sad to see that it didn't gain any traction

**Comment by yogeshvishnole** [comment]
It is requried.
