### ISSUE TITLE
client-gen is broken

### ISSUE THREAD

**Issue by max8899** [kubernetes/kubernetes#114208]
### What happened?

client-gen stop generating any code, might be broken

### What did you expect to happen?

generate clientset code

### How can we reproduce it (as minimally and precisely as possible)?

1. add example3 code
```shell
code-generator $ ls -l examples/crd/apis
total 0
drwxr-xr-x  3 -  staff  96 11 30 17:58 example
drwxr-xr-x  3 -  staff  96 11 30 18:27 example2
drwxr-xr-x  3 -  staff  96 11 30 18:29 example3
```
2. code-generator $ client-gen --clientset-name versioned --input-base '' --input k8s.io/code-generator/examples/crd/apis/example3/v1 --output-package k8s.io/code-generator/examples/crd/clientset --output-base hack/../../.. --go-header-file hack/../hack/boilerplate.go.txt

3. no code was generated in clientset.go

### Kubernetes version

not related

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

not related

### OS version

code-generator $ uname -a

Darwin - 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aimuz** [comment]
Can you check other directories?

**Comment by aimuz** [comment]
It would be nice if you could describe the version of client-gen

**Comment by max8899** [comment]
go install k8s.io/code-generator/cmd/client-gen@latest

> It would be nice if you could describe the version of client-gen

**Comment by brianpursley** [comment]
@max8899 I think what you have for `--input-base` and `--input` are the problem.

What if you try something like this:
```
client-gen --clientset-name versioned --input-base k8s.io/code-generator/examples/crd/apis --input example/v1 --go-header-file hack/boilerplate/boilerplate.go.txt
```
Notice `--input-base` is a directory, and `--input` is a group/version (it can be one or more actually)

**Comment by max8899** [comment]
> ```
> client-gen --clientset-name versioned --input-base k8s.io/code-generator/examples/crd/apis --input example/v1 --go-header-file hack/boilerplate/boilerplate.go.txt
> ```

that solves the problem
