### ISSUE TITLE
setting "--network: none" for container level.

### ISSUE THREAD

**Issue by rexxar-liang** [kubernetes/kubernetes#114224]
### What would you like to be added?

docker supports to[ disable networking for container](https://docs.docker.com/network/none/) by specify "--network none" parameter when running a specific container.
![image](https://user-images.githubusercontent.com/11643580/205009226-a61f99ab-09ed-40ee-838b-6cade2b2e13e.png)
We hope we can specify such parameters in containser spec like:
![image](https://user-images.githubusercontent.com/11643580/205010596-e8bc7e1d-ac89-497d-8273-2a6f3cb013e8.png)

### Why is this needed?

Our senario: 
    we create Pod with 3 containers in 1 Pod
- pull-worker: copy data from remote to local PV
- caculate-worker: caculate data from local PV and save output to local PV
- push-worker: copy output from local PV to remote
from security point of view, we hope only pull-woker and push-worker can visit network, the caculate-worker should disable to visit nework.

Options with current kubernets version：
    we create 3 different Pod and set Network Policy rule to disable caculate-worker Pod to visit both ingress and egress.
   disadvantage for this option：
1. we must introduce network plugin
2. 3 different Pods are more complex(performance, scheduling, resources...) for our senario
3. we must create network policy which seems complex compare to set a simple parameter("--network none") in container spec

**Comment by aojea** [comment]
How do you implement this with docker? two containers always need access to the network, how the other container gets the data?

**Comment by rexxar-liang** [comment]
3 worker shared the same loval PV or mountPath, so caculate-worker can read and write data from local PV or mountPath.

**Comment by aojea** [comment]
this has to work in a multi node environment, what happens if the pod without network access is scheduled in a different node? do you want to use a shared PV? that is still more complex that setting network policies or using 3 containers in a pod, no?

**Comment by rexxar-liang** [comment]
yes, we using 3 containers in a pod now, and the second container(caculate-worker) do not need network, so we hope to set "--network none" for this container for some security point of view.

**Comment by rexxar-liang** [comment]
yes, we using 3 containers in a pod now, and the second container(caculate-worker) do not need network, so we hope to set "--network none" for this container for some security point of view.

our yaml is something like(not accurate):
kind: ‘Pod’
apiVersion: 'v1'
metadata:
  name: 'network-test'
  namespace: 'default’
  spec:
    volumes:
      - name: 'vol-167024832801914129'
        hostPath:
          path: '/tmp'
      - name: 'vol-167024663283642899'
        hostPath:
          path: '/tmp'
      - name: 'vol-167024833608096093'
        hostPath:
          path: '/tmp'
    containers:
      - name: '**pull-worker'**
        image: ‘xxx/rexxar/obsutil:latest'
        command:
          - '/bin/bash'
        args:
          - '-c'
          - '**obsutil cp obs://rexxar/log /data/log.input**;sleep 100000'
        resources:
          limits:
            cpu: '250m'
            memory: '512Mi'
        volumeMounts:
          - name: 'vol-167024832801914129'
            mountPath: '/data'
      - name: '**caculate-worker**'
        image: ‘xxx/rexxar/obsutil:latest'
        command:
          - '/bin/bash'
        args:
          - '-c'
          - '**tar zcvf /data/log.tar.gz /data/log.input**;sleep 100000'
        resources:
          limits:
            cpu: '250m'
            memory: '512Mi'
        volumeMounts:
          - name: 'vol-167024663283642899'
            mountPath: '/data'
      - name: '**push-worker**'
        image: ‘xxx/rexxar/obsutil:latest'
        command:
          - '/bin/bash'
        args:
          - '-c'
          - '**obsutil cp /data/log.tar.gz  obs://rexxar/log.output**; sleep 100000'
        resources:
          limits:
            cpu: '250m'
            memory: '512Mi'
        volumeMounts:
          - name: 'vol-167024833608096093'
            mountPath: '/data'

**Comment by pacoxu** [comment]
> we create 3 different Pods and set the Network Policy rule to disable caculate-worker Pod to visit both ingress and egress.

This seems to be the suggested way. For security reasons, users can use network policy. 
- In Calico, you can create the pod in an isolated namespace and create a network policy to deny all network access.
