### ISSUE TITLE
Node lifecycle controller takes too long to mark pods NotReady

### ISSUE THREAD

**Issue by cbroglie** [kubernetes/kubernetes#114295]
### What happened?

We run a cluster spread across 3 sites/availability zones, and when an entire site becomes unreachable at once we observe that the node lifecycle controller takes too long to mark all the pods NotReady.

Example logs:
```
I0713 16:03:36.538269       1 node_lifecycle_controller.go:1092] node ... hasn't been updated for 20.062703613s.
…
I0713 16:04:48.014322       1 node_lifecycle_controller.go:1092] node ... hasn't been updated for 1m27.527087635s.
```

We set `--node-monitor-grace-period=20s`, and the first node is processed right at the 20s mark. But it takes over a minute until it processes the last node.

I believe this is because the main loop in monitorNodeHealth processes each node serially.
https://github.com/kubernetes/kubernetes/blob/17bf864c1fc20e4badc9a6e0659c5190310462e1/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L796
And processing each node requires setting the ready status of each of its pods to false, serially.
https://github.com/kubernetes/kubernetes/blob/17bf864c1fc20e4badc9a6e0659c5190310462e1/pkg/controller/util/node/controller_utils.go#L119

With enough nodes and pods, this time quickly adds up and leaves unreachable pods in endpoints for too long.

### What did you expect to happen?

I expected the node lifecycle controller to mark pods on unreachable nodes NotReady soon after the nodes exceeded the node monitor grace period.

### How can we reproduce it (as minimally and precisely as possible)?

We observe this with a cluster of ~150 nodes spread evenly across 3 sites, so ~50 nodes become unreachable at once when we drop a site.

### Anything else we need to know?

This is somewhat similar to #110341, but at a different stage. We tested with 1.25.2 as well (it contains the fix for #110341) and observed the same behavior.

We have tested a small patch to `monitorNodeHealth` to process nodes in their own goroutines, using a semaphore to bound the concurrency to `scheduler.UpdateWorkerSize` (matching the concurrency of `doNodeProcessingPassWorker`). This is working well for us since most of the time marking pods NotReady is just waiting on i/o. I’ll follow up with a PR with the patch.

### Kubernetes version

We noticed this in 1.21.13, but verified the same behavior exists in 1.25.2.

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
perhaps there should be some configuration allowing to configure # of parallel checks.

Marking as a feature since it is not a regression and not a "failure":

/remove-kind bug
/kind feature

**Comment by cbroglie** [comment]
Thanks for reviewing @SergeyKanzhelev. I had labeled it as a bug to be consistent with #110341, since it's a similar example of functioning correctly, but too slowly.

I would be happy to work on a PR to make this configurable, if you think that's the best path forward.

**Comment by aojea** [comment]
/priority important-soon
/sig network

This impact on improving the failover of applications with services, related to https://github.com/kubernetes/kubernetes/pull/110639

**Comment by thockin** [comment]
What are next steps here?

**Comment by aojea** [comment]
it was fixed by https://github.com/kubernetes/kubernetes/pull/114296, right @cbroglie ?

/close

please reopen if I misjudged

**Comment by cbroglie** [comment]
@aojea That's correct, thanks. The only possible follow up that's been discussed would be making the number of workers configurable.
