### ISSUE TITLE
k8s.io/kubernetes/test/integration/job: TestFinalizersClearedWhenBackoffLimitExceeded flakes in 1.23

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#114259]
> > k8s.io/kubernetes/test/integration/job: TestFinalizersClearedWhenBackoffLimitExceeded

@alculquicondor @saschagrunert @liggitt  seems we have a problem in branch 1.23, this test has been flaking for some time

https://testgrid.k8s.io/sig-release-1.23-blocking#integration-1.23

_Originally posted by @aojea in https://github.com/kubernetes/kubernetes/issues/111914#issuecomment-1335178353_

> looks like integration job tests were fixed up in https://github.com/kubernetes/kubernetes/pull/109749 and picked to 1.24 in https://github.com/kubernetes/kubernetes/pull/111664 but not 1.23

> it was picked https://github.com/kubernetes/kubernetes/pull/111665 🤔

**Comment by alculquicondor** [comment]
I see the log line for the desired outcome, but after the test has already timed out:
```
I1202 10:00:33.017858  122527 event.go:294] "Event occurred" object="simple/test-job" kind="Job" apiVersion="batch/v1" type="Warning" reason="BackoffLimitExceeded" message="Job has reached the specified backoff limit"
```

And we do see a lot of throttling by APF.

I'll just reduce the number of pods the test creates, only in 1.23, as other release seem fine.

**Comment by alculquicondor** [comment]
just to keep ourselves honest:
/remove-sig scheduling
:smile:

**Comment by liggitt** [comment]
still seeing this flake in release-1.23 (e.g. 3 runs in a row in https://github.com/kubernetes/kubernetes/pull/113983, where CI is still running on go1.17)

* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113983/pull-kubernetes-integration/1603799894101856256
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113983/pull-kubernetes-integration/1603778954462760960
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/113983/pull-kubernetes-integration/1603742868395003904

**Comment by liggitt** [comment]
this is failing 100% of runs in the 1.23 PR I'm currently working on

**Comment by alculquicondor** [comment]
the cherry picks are still open

**Comment by liggitt** [comment]
test has been green since the backports merged
