### ISSUE TITLE
PV handling of beta topology labels

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#114268]
### What happened?

Offshoot discussion from https://github.com/kubernetes/kubernetes/issues/114120 and https://github.com/kubernetes/kubernetes/issues/89477

There has been a lot of work since 1.14 to start using the GA topology labels instead of the beta topology labels.

The intree volume provisioning logic has been updated to create PVs with the GA topology labels (both as a label, and in PV.NodeAffinity) and the CSI migration library has been updated to understand both beta and GA labels and convert them in-memory to the CSI equivalent labels in order to support old PVs with only beta labels: https://github.com/kubernetes/kubernetes/issues/98281

However, there's still a few gaps:
1. The CSI migration logic only handles conversion of the beta labels for intree volume types. External volume types are not covered.
2. The [VolumeZone](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins/volumezone) scheduling plugin does not exercise the csi migration logic. The original plan was that with csi migration we could remove the VolumeZone plugin entirely because its functionality is replaced by the [VolumeBinding](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins/volumebinding) plugin. Again, this assumption is only true for intree volume types that we provision and does not account for users that may have their own custom provisioning logic.

These issues mean that if we remove the beta label on nodes, we can break existing PVs that only use the beta label, for both intree and external volume types.

### What did you expect to happen?

There's a couple of options (not necessarily mutually exclusive) that we can pursue:
1. Anywhere we look at PV labels (scheduler, kubelet), translate beta labels to GA labels in-memory regardless of csi migration. This method requires the fewest user changes but since the object itself is not changed, users may still see warnings about use of the beta labels.
2. Relax PV.NodeAffinity mutability to allow changing the beta label to GA label (changing PV.Labels should already be allowed). And then
    a. Require the user to change all the labels themselves. This is quite burdensome but gives the user the most control over when and how to change it.
    b. Provide tooling/controller that updates all the objects. Convenient, but could possibly break the user if they had tooling/workflows that were depending on the beta label.
3. Never remove the beta topology label from the node and continue supporting it forever. Similar to how we say beta annotations are part of the API, and stable APIs are supported forever: https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api

I think we should do some form of option 2 regardless.

If 3 is out of the question, then I would say 1 + 2a, which gives us the benefit removing the label from nodes and letting users convert on their own time. But this would probably apply more to just PVs; anywhere we allow users to specify the labels needs to be able to handle this.

### How can we reproduce it (as minimally and precisely as possible)?

Remove the beta zone label on a Node and try to schedule a Pod using PV.labels with the beta zone label.

**Comment by msau42** [comment]
@kubernetes/sig-storage-bugs 
cc @alculquicondor @liggitt

**Comment by pacoxu** [comment]
> We're emitting warnings in 1.25+ as of https://github.com/kubernetes/kubernetes/pull/108554, but dropping support means existing persisted objects would just break on upgrade, right? I don't think we would do that.

IMO, we can drop the beta label support later (probably more than 4 releases later) although we started to deprecate it. 

BTW, should we add a warning when users upgrade clusters?

**Comment by liggitt** [comment]
> IMO, we can drop the beta label support later (probably more than 4 releases later) although we started to deprecate it for years.

I don't think we should make a change if it breaks system handling of existing persisted objects that use beta or stable functionality unless a user intervenes.

I agree with @msau42 that we need to *at minimum* allow the fields which target node labels (node selectors, affinity fields, etc) to be mutable on objects which are expected to span multiple minor versions (pods are not included in this list, since they drain on node upgrade)

Do we have a concrete list of all the types / fields and controllers that use node labels / selectors / affinity? That seems like the starting point for any of the options. https://github.com/kubernetes/kubernetes/issues/94626 did a sweep a few releases back, but was focused just on the API aspect, not on consuming controllers. There's enough types and enough clients/controllers looking at those types that are outside the core Kubernetes components that I tend to think putting a translation layer in the controllers is probably not going to work well.

**Comment by msau42** [comment]
My main concern is that there is always a risk of breaking unknown consumers despite all the warnings that we give. Should we adopt the same API deprecation policy as beta annotations for our well-known labels?

**Comment by sftim** [comment]
For the page https://kubernetes.io/docs/reference/labels-annotations-taints/, I've assumed that we will always retain the _registration_ for deprecated labels indefinitely, once registered.

**Comment by sftim** [comment]
IMO, the
>  tooling/controller that updates all the objects. Convenient, but could possibly break the user if they had tooling/workflows that were depending on the beta label.

could be out-of-tree, and we can put a big notice in the release notes saying:
- release n: *go and run this tool (or controller Deployment) if you have beta topology keys*
- release n+1 urgent upgrade nodes **(No, really, you MUST read this before you upgrade)**:
  *you did run that tool we recommended, right? If not, we advise you not to upgrade yet.*

**Comment by msau42** [comment]
We have done 1+2a as planned.

/close
