### ISSUE TITLE
Unstable TopologyAwareHints

### ISSUE THREAD

**Issue by nickvanwegen** [kubernetes/kubernetes#114215]
### What happened?

I have enabled TopologyAwareHints on some of my services and the hints in first look seems to work fine. Tho when for any of the external factor reasons the hints are removed they seem to never get restored again and I am left with no TopologyAwareHints at all on the services where it was enabled. (and still is)

This behavior in my case seems to be triggered when there is a spot-termination(AWS) and most likely triggered one of the safeguard as described in https://kubernetes.io/docs/concepts/services-networking/topology-aware-hints/#safeguards some information about my deployment. 

- deployment has 6 replica's 2 in each availability zone
- All nodes are tagged correctly with the `topology.kubernetes.io/zone` label
- The cluster has a total of 9 nodes, 6 for workload and 3 dedicated for ingress-nginx(so non of the workload pods can be scheduled here(taints))
- Cluster is deployed in a total of 3 zones 1a, 1b, 1c

My guess is that with a spot termination either `Impossible to achieve balanced allocation` or `One or more Nodes has insufficient information` are triggering the deletion of hints on the `endpointslices` which can be perfectly fine. 

The issue here is that by for example a spot-termination the hints are removed(can be valid) tho when the node and pods are restored to its original state, 2 pods in each AZ the hints fail to be restored on the `endpointslices`. 
Then when I recreate(delete) one pod of the deployment and the new pod is up and running again the hints are restored.

### What did you expect to happen?

That after the node and pod state is restored after a spot termination(could also be a autoscaling trigger from CAS) that the hints are automatically restored.

### How can we reproduce it (as minimally and precisely as possible)?

- Create EKS cluster which can provision nodes in each AZ(v1.24)
- Create workload and divide load on all 3 az's with 6 replica's in total
- You can then use AWS FIS to recreate a spot termination call on one of the nodes.

I understand that this might be a lot of work since its cloud specific so if needed i can provide a complete test environment and show it on screen.

I have not tested this on a non-eks environment. 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7-eks-fb459a0", GitCommit:"c240013134c03a740781ffa1436ba2688b50b494", GitTreeState:"clean", BuildDate:"2022-10-24T20:36:26Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> My guess is that with a spot termination either Impossible to achieve balanced allocation or One or more Nodes has insufficient information are triggering the deletion of hints on the endpointslices which can be perfectly fine.

you can confirm that checking at the controller-manager logs, the endpointslice controller logs a message with the exact reason

**Comment by nickvanwegen** [comment]
i have checked the logs and this is the only message i receive from the kube-controller-manager. 

```
I1201 16:16:15.701298      10 endpointslice_controller.go:546] Queuing kube-system/mimir-distributor-headless Service after Node change due to overloading
I1201 16:16:15.701356      10 endpointslice_controller.go:546] Queuing kube-system/mimir-distributor Service after Node change due to overloading
```

But then it never restores the hints afterwards the cluster is completely restored again with all the pods running in the same zone etc. 
I would expect that the hints will be restored but they are not.

**Comment by aojea** [comment]
With -v2 it gives you the exact reason

https://github.com/kubernetes/kubernetes/blob/3e26e104bdf9d0dc3c4046d6350b93557c67f3f4/pkg/controller/endpointslice/topologycache/topologycache.go#L248

**Comment by nickvanwegen** [comment]
On EKS i cannot change log level but according to EKS documentation it is on v2 


`When you enable a log type, the logs are sent with a log verbosity level of 2.`

https://docs.aws.amazon.com/eks/latest/userguide/control-plane-logs.html

**Comment by aojea** [comment]
can you paste the full output of the endointslices (`-o yaml`) before and after the fact?
let's try to reconstruct the problem then

**Comment by nickvanwegen** [comment]
Here is an output of when it just happened. So there are no hints on the endpointslices
 As you can see each pod is on it own node spread across 3-az's(2 in each AZ)
 
```
addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.13.169.155
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-13-142-134.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-zxl8z
    namespace: kube-system
    uid: b1f09d22-a866-4853-b42e-3d81b67a81f6
  zone: eu-west-1c
- addresses:
  - 10.11.120.130
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-11-254-58.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-2qnjw
    namespace: kube-system
    uid: 4dc87e69-c17c-4965-acaa-db3abf5f249c
  zone: eu-west-1a
- addresses:
  - 10.12.208.162
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-12-184-82.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-jmvh2
    namespace: kube-system
    uid: 8724f5f7-69e9-48a4-b468-7654582a46d3
  zone: eu-west-1b
- addresses:
  - 10.12.242.184
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-12-0-242.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-2c8w9
    namespace: kube-system
    uid: f1c2c2cd-0da8-4c56-b65d-2b6323dad868
  zone: eu-west-1b
- addresses:
  - 10.13.217.87
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-13-135-72.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-fx9pq
    namespace: kube-system
    uid: 6b582b51-5316-4b7e-8a57-a00368615cfa
  zone: eu-west-1c
- addresses:
  - 10.11.228.143
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: ip-10-11-85-14.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-xt4xp
    namespace: kube-system
    uid: 8b705b28-fda5-49ea-a7af-cd971e29ae03
  zone: eu-west-1a
kind: EndpointSlice
metadata:
  creationTimestamp: "2022-09-29T22:28:19Z"
  generateName: mimir-nginx-
  generation: 882
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.4.0
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: mimir-distributed-3.2.0
    kubernetes.io/service-name: mimir-nginx
  name: mimir-nginx-9dkkh
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: mimir-nginx
    uid: 0fc6d4b7-8dc1-45dd-b924-2d86cdfba170
  resourceVersion: "39831954"
  uid: 71548223-f29d-45cc-8cf0-15092032619d
ports:
- name: http-metric
  port: 8080
  protocol: TCP
```

 Now I am going to delete 1 mimir-nginx pod to trigger a recreate 
 
 ```
 k delete pod -n kube-system mimir-nginx-774d67df5d-xt4xp                                                                                                                                                       ─╯
pod "mimir-nginx-774d67df5d-xt4xp" deleted
 ```
 
 Then I see that the hints are there again after about 10 seconds
 
 
 ```
 addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.13.169.155
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1c
  nodeName: ip-10-13-142-134.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-zxl8z
    namespace: kube-system
    uid: b1f09d22-a866-4853-b42e-3d81b67a81f6
  zone: eu-west-1c
- addresses:
  - 10.11.120.130
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1a
  nodeName: ip-10-11-254-58.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-2qnjw
    namespace: kube-system
    uid: 4dc87e69-c17c-4965-acaa-db3abf5f249c
  zone: eu-west-1a
- addresses:
  - 10.12.208.162
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1b
  nodeName: ip-10-12-184-82.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-jmvh2
    namespace: kube-system
    uid: 8724f5f7-69e9-48a4-b468-7654582a46d3
  zone: eu-west-1b
- addresses:
  - 10.12.242.184
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1b
  nodeName: ip-10-12-0-242.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-2c8w9
    namespace: kube-system
    uid: f1c2c2cd-0da8-4c56-b65d-2b6323dad868
  zone: eu-west-1b
- addresses:
  - 10.13.217.87
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1c
  nodeName: ip-10-13-135-72.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-fx9pq
    namespace: kube-system
    uid: 6b582b51-5316-4b7e-8a57-a00368615cfa
  zone: eu-west-1c
- addresses:
  - 10.11.128.5
  conditions:
    ready: true
    serving: true
    terminating: false
  hints:
    forZones:
    - name: eu-west-1a
  nodeName: ip-10-11-85-14.eu-west-1.compute.internal
  targetRef:
    kind: Pod
    name: mimir-nginx-774d67df5d-5flqc
    namespace: kube-system
    uid: 87007a66-1239-4b6e-a0f5-bdcfa96dc562
  zone: eu-west-1a
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2022-12-02T12:18:09Z"
  creationTimestamp: "2022-09-29T22:28:19Z"
  generateName: mimir-nginx-
  generation: 897
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mimir
    app.kubernetes.io/version: 2.4.0
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    helm.sh/chart: mimir-distributed-3.2.0
    kubernetes.io/service-name: mimir-nginx
  name: mimir-nginx-9dkkh
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: mimir-nginx
    uid: 0fc6d4b7-8dc1-45dd-b924-2d86cdfba170
  resourceVersion: "39838152"
  uid: 71548223-f29d-45cc-8cf0-15092032619d
ports:
- name: http-metric
  port: 8080
  protocol: TCP
 
 ```

**Comment by aojea** [comment]
interesting , the pod recreated is in the same node

new pod 

> > - addresses:
>  - 10.11.128.5
>  conditions:
>    ready: true
>    serving: true
>    terminating: false
>  hints:
>    forZones:
>    - name: eu-west-1a
>  nodeName: ip-10-11-85-14.eu-west-1.compute.internal
>  targetRef:
>    kind: Pod
>    name: mimir-nginx-774d67df5d-5flqc
>    namespace: kube-system
>    uid: 87007a66-1239-4b6e-a0f5-bdcfa96dc562
>  zone: eu-west-1a
> 

old pod

> - addresses:
>   - 10.11.228.143
>   conditions:
>     ready: true
>     serving: true
>     terminating: false
>   nodeName: ip-10-11-85-14.eu-west-1.compute.internal
>   targetRef:
>     kind: Pod
>     name: mimir-nginx-774d67df5d-xt4xp
>     namespace: kube-system
>     uid: 8b705b28-fda5-49ea-a7af-cd971e29ae03
>   zone: eu-west-1a


I'm afraid the the info of the endpoint_controller about the reasons to not add hints is going to be key here :/

**Comment by nickvanwegen** [comment]
Oke so since I agree we need logs I have replicated a setup with kind and to my surprise the issue is not present on kind. 
On my kind cluster it also does not follow the same logic as what is happening on my EKS cluster. 

On my EKS cluster if only one node gets drained the hints are removed. In kind 1 node can be unavailable and the hints stay present. Only when I shutdown a whole zone the hints get removed. And then when I uncordon the node the hints are back instantly. 
For now my guess is that the issue is with EKS. 

I used this kind config 

```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1a
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1a
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1b
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1b
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1c
- role: worker
  image: kindest/node:v1.24.7@sha256:577c630ce8e509131eab1aea12c022190978dd2f745aac5eb1fe65c0807eb315
  labels:
    topology.kubernetes.io/zone: eu-west-1c

```

With this sample deployment/service

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: kube-system
  labels:
    app: busybox
spec:
  replicas: 6
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: greenstatic/echo-ip
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: source-server
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app: busybox
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
      - labelSelector:
          matchLabels:
            app: busybox
        maxSkew: 3
        topologyKey: topology.kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
  labels:
    app: busybox
  name: busybox
  namespace: kube-system
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http-metric
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: busybox
  sessionAffinity: None
  type: ClusterIP


```

When all is up and running use `k get nodes -L topology.kubernetes.io/zone` to identify zones and bring a zone down. 
`k drain $NODE` (need to bring down 2 nodes to bring down a zone)

You will see that the hints are removed. 
When we uncordon the nodes from previous steps we can see that the hints are back. 
For now the only thing I can say is that EKS clusters do not follow this logic.

**Comment by dims** [comment]
cc @nckturner @jyotimahapatra

**Comment by nickvanwegen** [comment]
Not yet since I did not know if it might be EKS related or not. I will create a support ticket/post it in EKS slack support channel and will update this ticket if I have more information

**Comment by robscott** [comment]
Thanks for testing this with Kind to help focus this issue. I'm not sure what would be unique about AWS here, but since we're specifically looking at Node change behavior, here's where the relevant logic lives for Topology:

Node update handler:
https://github.com/kubernetes/kubernetes/blob/3e26e104bdf9d0dc3c4046d6350b93557c67f3f4/pkg/controller/endpointslice/endpointslice_controller.go#L523

What we consider ready:
https://github.com/kubernetes/kubernetes/blob/3e26e104bdf9d0dc3c4046d6350b93557c67f3f4/pkg/controller/endpointslice/topologycache/utils.go#L257

It's possible that there's some nuance in how nodes transition between states on AWS that is different than Kind, not sure.

/provider aws

**Comment by robscott** [comment]
/triage accepted

Is there anyone from AWS that we can assign here to help debug this?

**Comment by nickvanwegen** [comment]
A short update I am in contact with AWS support as it looks like its an issue with just my cluster. 
But I am not completely sure to be honest. 

But I cannot replicate the issue on an exact copy of my EKS cluster and also cannot replicate it on a kind cluster. 

Sadly on EKS I just don not have enough logs to look into it myself lets see if support can help me with it further. 

Support has acknowledged there is an issue on my cluster and they have send the case to the service team will update as soon as I know more

**Comment by aojea** [comment]
glad you are progressing, please close the issue once you get it resolved or if you think that there is no more things the community can do here

**Comment by neoakris** [comment]
I see this issue was opened in 2022, I suspect the official docs have been updated since then.
https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing 

When I read the docs as of July 6th, 2023. The docs make it sound like you're encountering normal behavior that's documented / working as expected. 
<br>

**Here's the critical parts of the docs:**
https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/#enabling-topology-aware-routing 
https://kubernetes.io/docs/concepts/services-networking/topology-aware-routing/#when-it-works-best

```
...
When there are enough endpoints available in each zone, Topology Hints will
be populated on EndpointSlices to allocate individual endpoints to specific
zones, resulting in traffic being routed closer to where it originated from.
...
2. The Service has 3 or more endpoints per zone
In a three zone cluster, this means 9 or more endpoints. If there are fewer
than 3 endpoints per zone, there is a high (≈50%) probability that the
EndpointSlice controller will not be able to allocate endpoints evenly and
instead will fall back to the default cluster-wide routing approach.
```

**When I read the above I'd paraphrase it as follows:**
If you enable this feature, it only works when you have at least 3 endpoints per zone. 
So for a 3 zone cluster like you mentioned above, this means that it'd be perfectly normal/expected behavior for it to stop working (fall back to default the default cluster-wide routing approach), unless you had 9 endpoints total. (3 per zone)

**If you want it to work, I think you'd need to:**
Switch to 9 replicas, or downgrade from a 3 zone cluster to a 2 zone cluster. At which point, your 6 replicas would satisfy the condition of enough endpoints. (3x replicas per 2 zones)
