### ISSUE TITLE
Forbidden: NodeAuthorization must be empty

### ISSUE THREAD

**Issue by devopspln** [kubernetes/kubernetes#114233]
Hello,

I am getting below error while updating kops cluster

Error: spec.nodeAuthorization: Forbidden: NodeAuthorization must be empty. The functionality has been reimplemented and is enabled on kubernetes >= 1.19.0

My cluster details
Kubernetes: v1.18.20
Kops: 1.22.1

I have bootstrap ansible playbook where I disable the parameter but still does not work

###########################
# Setup Kubernetes Cluster
###########################

- hosts: localhost
  connection: local
  environment:
  # KOPS_FEATURE_FLAGS: EnableNodeAuthorization

Could you help on it? How to disable the NodeAuthorization?

Thanks in advance.

**Comment by Ritikaa96** [comment]
You might want to look at  [this](https://github.com/kubernetes/kops/pull/10439) PR
Here it seems like for kops, node-authorization feature is deprecated from v1.19
as stated in the PR changes:

> As of kOps 1.20, setting `nodeAuthorization` is forbidden for any Kubernetes version and is replaced by the bootstrapping using kops-controller.

@devopspln  

For kubernetes you can find information about Node authorization [here](https://kubernetes.io/docs/reference/access-authn-authz/node/#overview)

> To enable the Node authorizer, start the apiserver with --authorization-mode=Node.
> To limit the API objects kubelets are able to write, enable the [NodeRestriction](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers#noderestriction) admission plugin by starting the apiserver with --enable-admission-plugins=...,NodeRestriction,...

To use these flags visit this [link](https://kubernetes.io/docs/reference/access-authn-authz/authorization/#using-flags-for-your-authorization-module)

**Comment by Ritikaa96** [comment]
Hi @devopspln  Is your issue resolved by above information? 
Please let us know in case of any other query, If solved , this issue can be closed
