### ISSUE TITLE
introduce QueueingHint for wise-enqueueing

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#114297]
### What would you like to be added?

https://github.com/kubernetes/kubernetes/issues/87850 tries to almost remove the flushing unschedulable Pods into activeQ.
Then, after that, almost all moving to activeQ can be associated with certain events.

Here, I'd propose two changes for PreEnqueue so that we can utilize PreEnqueue for wise-enqueueing.

#### 1. adding parameters about what happens to `PreEnqueue`.

- `event`: By which event the pod will be moved back to schedQ/backoffQ. It's represented by [`framework.ClusterEvent`](https://github.com/kubernetes/kubernetes/blob/27344212cec3538a44b166db721b083e8865c32e/pkg/scheduler/framework/types.go#L77).
- `involvedObj`: the object involved in that event.
  - For example, the given event is "Node deleted", the involvedObj will be that deleted Node.

```go
type EnqueuePlugin interface {
    Plugin
    PreEnqueue(ctx context.Context, state *CycleState, p *v1.Pod, event framework.ClusterEvent, involvedObj runtime.Object) *Status
}
```

Also, in the following cases, `event` and `involvedObj` would be empty:
  - If an enqueued Pod is a newly created.
  - If the Pod will be backed to schedQ/backoffQ by flushing.

#### 2. return `Skip` if the plugin does nothing with that event.

e.g., `NodeAffinity` returns `Success` when a Node gets labels that match with Pod's NodeSelector. But, it returns `Skip` when a Node gets labels that doesn't match with Pod's NodeSelector.

Currently, `PreEnqueue`'s return status is quite simple: 
- all PreEnqueue plugins return Success -> enqueue to activeQ.
- any PreEnqueue plugin return non-Success -> don't enqueue to activeQ.

By introducing `Skip`, we can change here like:
- all PreEnqueue plugins which are in [UnschedulablePlugins](https://github.com/kubernetes/kubernetes/blob/27344212cec3538a44b166db721b083e8865c32e/pkg/scheduler/framework/types.go#L104) return Skip -> don't enqueue to activeQ.
  - it means that the event won't change the filtering results of all `UnschedulablePlugins`.
- any PreEnqueue plugin return non-Success -> don't enqueue to activeQ.
- any other cases -> enqueue to activeQ.
  - e.g., Some UnschedulablePlugins return Success in PreEnqueue. Pod has no UnschedulablePlugins. etc.

### Why is this needed?

It'd much contribute to wise-enqueueing and thus overall scheduler performance.
This proposal would allow plugins to bring their specific logic into enqueueing by PreEnqueue. We probably can implement `PreEnqueue` in all Filter plugins.
And we can move Pods only when it's highly possible to be schedulable in the next scheduling cycle. We can move Pods back to unschedulable Pod pool when the event won't change the filtering results of all `UnschedulablePlugins`.

---

Currently, the scheduler always moves unschedulable Pods to activeQ when any `framework.ClusterEvent`, which is defined in `EventToRegister` of any UnschedulablePlugins, happens. 
It's obviously inefficient, and actually, the scheduler filters out some events before letting the scheduling queue know the event happens.
https://github.com/kubernetes/kubernetes/blob/31a10245d67544b6718f569a1442b1de97a91e7d/pkg/scheduler/internal/queue/scheduling_queue.go#L660-L678
And that results in the issue https://github.com/kubernetes/kubernetes/issues/110175; it robs Pods, which are rejected by other plugins which have events, of chances of being moved to activeQ.

Having such a logic for specific plugins in the scheduler core prevents out-of-tree plugins' extendability. The scheduler itself should be pure, should treat all plugins equally, and ideally shouldn't do anything special for any in-tree plugin implementation.

/sig scheduling
/assign
/kind feature

**Comment by sanposhiho** [comment]
@kubernetes/sig-scheduling-leads 
Please take a look, I believe it's the right direction to improve the scheduler's capabilities. 🙏

**Comment by Huang-Wei** [comment]
> 1. adding parameters about what happens to `PreEnqueue`.

This sounds ok to me.

> 2. return `Skip` if the plugin does nothing with that event.

I understand that, by enriching the PreEnqueue interface, it gives an extra knob for plugin to choose whether to let the pod go to activeQ or not. However, what's the meaning to make an additional status `Skip`? Isn't` Unschedulable` adequate? Or, it's that you're trying to distinguish the "gated" semantics of "real" PreEnqueue plugins (like `SchedulingGates`) from other "filtering" purpose PreEnqueue plugins?

**Comment by sanposhiho** [comment]
The meanings of each status that I'd propose is
- Skip: the PreEnqueue plugin doesn't get interested in that event for that pod.
  - e.g., NodeAffinity returns `Skip` for an event that a Node gets labels that don't match with Pod's NodeSelector.
- Unschedulable: the plugin wants to reject enqueueing. 
  - e.g, SchedulingGates always returns `Unschedulable` for Pods with non-empty SchedulingGates.
- Success: the plugin wants to enqueue it. 
  - The scheduler allows enqueueing only when more than one UnschedulablePlugins return Success in PreEnqueue. 

So, when **all** PreEnqueue plugins **which are in [UnschedulablePlugins](https://github.com/kubernetes/kubernetes/blob/27344212cec3538a44b166db721b083e8865c32e/pkg/scheduler/framework/types.go#L104)** return Skip, that means that event won't make that Pod schedulable and the scheduler reject enqueueing.
I mean, for example, Pods which got rejected only by `NodeAffinity` Filter, then they are enqueued to activeQ only when `NodeAffinity` PreEnqueue return Success. Another example, Pods which got rejected by `SchedulingGates` in PreEnqueue, they are enqueued only when `SchedulingGates` return Success.

I guess the [`runEnqueuePlugins`](https://github.com/kubernetes/kubernetes/blob/7f7bf68c7c86b7dedaf4758bd0fb1fd612d085e8/pkg/scheduler/internal/queue/scheduling_queue.go#L322) would be something like this.

```go
// pseudo-code 
func (p *PriorityQueue) runEnqueuePlugins(ctx context.Context, pInfo *framework.QueuedPodInfo, event *framework.ClusterEvent, involvedObj *runtime.Object) bool {
	pod := pInfo.Pod

	skipUnschedulablePlugins := sets.Set[string]
	for _, pl := range p.preEnqueuePluginMap[pod.Spec.SchedulerName] {
		s := pl.PreEnqueue(ctx, pod, event, involvedObj)
		if s.IsSuccess() {
			continue
		}
		if s.IsSkip() {
			if pInfo.UnschedulablePlugins.Has(pl.Name()) {
				skipUnschedulablePlugins.Insert(pl.Name())
			}
			continue
		}

		pInfo.UnschedulablePlugins.Insert(pl.Name())
		return false
	}

	if pInfo.UnschedulablePlugins.Len() != 0 && skipUnschedulablePlugins.Len() == pInfo.UnschedulablePlugins.Len() {
		// all UnschedulablePlugin return skip.
		return false
	}

	return true
}

```

**Comment by Huang-Wei** [comment]
> I mean, for example, Pods which got rejected only by NodeAffinity Filter, then they are enqueued to activeQ only when NodeAffinity PreEnqueue return Success.

Why it's a must for NodeAffinity to implement PreEnqueue? A plugin has the right to opt-out PreEnqueue plugin.

Suppose a pod failed plugin A, but plugin A doesn't implement PreEnqueue; while plugin B does implement PreEnqueue. In this case, B can just choose to return `success` or `unschedulable` (technically it's allowed). So my point is: if a plugin implements PreEnqueue, returning `success` to represent "let it go", or `unschedulable` to "abort enqueue". The additional status `skip` and related logic doesn't look necessary.

**Comment by sanposhiho** [comment]
> Why it's a must for NodeAffinity to implement PreEnqueue?

No, actually, the scheduler won't force all Filter plugins to have PreFilter. That example just _assumes_ that NodeAffinity implements PreEnqueue to explain the example scenario. (Sorry I should've noted this assumption.)

If some UnschedulablePlugins don't have `PreEnqueue`, `skipUnschedulablePlugins.Len() == pInfo.UnschedulablePlugins.Len()` in pseudo-code will never be true and `runEnqueuePlugins` behaves as it does in the current scheduler.

In other words, the proposed wise-enqueue is effective if and only if all plugins in `pInfo.UnschedulablePlugins` implement PreEnqueue. 

> my point is: if a plugin implements PreEnqueue, returning success to represent "let it go", or unschedulable to "abort enqueue".

The scheduler cannot make a decision whether "let it go" or "abort enqueue" until it gets results from all `UnschedulablePlugins`'s PreEnqueue.

For example, a pod has `NodeAffinity` and `VolumeRestriction` in UnschedulablePlugins, and let's say a PVC-added event happens. That PVC-added event won't change `NodeAffinity` Filter result, but, _may_ change `VolumeRestriction` Filter result.
In this case, the scheduler shouldn't abort enqueue only based on a `NodeAffinity` PreEnqueue result because other UnschedulablePlugins (`VolumeRestriction` in this case) may want to retry to schedule it. 

This is my point, do you have any ideas to handle this scenario without introducing `Skip`?

**Comment by Huang-Wei** [comment]
> In this case, the scheduler shouldn't abort enqueue only based on a NodeAffinity PreEnqueue result because other UnschedulablePlugins (VolumeRestriction in this case) may want to retry to schedule it.

So you're trying to say: `unschedulable` represent a hard no ❌, but `skip` represents a soft no ⚠️ - when at least one PreEnqueue plugin returns `success` and it **happens to be** in `UnscheduleblePlugin`, we return  a final `success` ✅, am I understanding right?

> This is my point, do you have any ideas to handle this scenario without introducing `Skip`?

Introduce a `Skip` is tricky as `Skip`'s semantics is nuanced to be expressed clearly in the interface. I think `Skip`'s semantics can be inferred by simply returning `Success` or `Unschedulable`. For `Unschedulable` status, we can deduce whether we should return a final yes or no for the enqueuing:

```go
// pseudo-code
func (p *PriorityQueue) runEnqueuePlugins(ctx context.Context, pInfo *framework.QueuedPodInfo, event *framework.ClusterEvent, involvedObj *runtime.Object) bool {
	pod := pInfo.Pod

	// Record whether at least one unschedulablePlugin succeeded.
	unschedulablePluginSucceeded := false
	failed := 0
	for _, pl := range p.preEnqueuePluginMap[pod.Spec.SchedulerName] {
		s := pl.PreEnqueue(ctx, pod, event, involvedObj)
		if pInfo.UnschedulablePlugins.Has(pl.Name()) {
			if s.IsSuccess() {
				unschedulablePluginSucceeded = true
			} else {
				failed++
				// Shortcut: we don't need to continue iterating resting preEnqueue plugins.
				if failed == pInfo.UnschedulablePlugins.Len() {
					return unschedulablePluginSucceeded
				}
			}
		} else if !s.IsSuccess() {
			pInfo.UnschedulablePlugins.Insert(pl.Name())
			return false
		}
	}

	return pInfo.UnschedulablePlugins.Len() == 0 || unschedulablePluginSucceeded
}
```

But I may miss some corner case, please check.

**Comment by ahg-g** [comment]
I have a couple of general comments:

1) I agree that it is best to avoid the Skip status. I think of unschedulable as a "veto" to enqueue, so all plugins must return success for the pod to be enqueued. So in [this example](https://github.com/kubernetes/kubernetes/issues/114297#issuecomment-1356118995), the nodeAffinity plugin returns success on all events that it is not interested in; on the events it is interested in, node events, it either returns success or unschedulable.

2) I wonder if we can get rid of all the custom logic we currently have in the scheduling_queue.go for event handling and replace that with `PreEnqueue` including the event registration logic; so practically `PreEnqueue` replaces `EventsToRegister` in a way similar to point one above?

**Comment by sanposhiho** [comment]
Okay, Understood, @Huang-Wei 's [example code](https://github.com/kubernetes/kubernetes/issues/114297#issuecomment-1356685511) looks better/simpler to me as well. Then, let's just forget about my idea with Skip.

---

> so practically PreEnqueue replaces EventsToRegister in a way similar to point one above?

@ahg-g

I also think PreEnqueue _can_ replace EventsToRegister, but I feel the performance will be the point?
With EventsToRegister, the scheduler can know the events required by each plugin and subscribe to only sufficient events through the event handler. That'll still be the benefit from EventsToRegister even after this proposal is implemented.

**Comment by Huang-Wei** [comment]
> so practically PreEnqueue replaces EventsToRegister in a way similar to point one above?

EventsToRegister() serves as a special form of PreEnqueue for now: once an event matches one of the failed plugin's registered events, we enqueue the pod - it's the **exact opposite** of "veto". So whether we can port it into PreEnqueue depends on how we design the "unschedulable" semantics of PreEnqueue:

1. if "unschedulable" in PreEnqueue acts as a "veto", we still need EventsToRegister(); otherwise, if all plugins are not interested in an event, they all return success, and hence the pod will be enqueued which is incorrect.
2. if "unschedulable" in PreEnqueue acts as a "conditional deny", we can port EventsToRegister() into PreEnqueue, it behaves like this:
    - for events a plugin is not interested, it returns success ✅ (today's behavior for a plugin not implementing EventsToRegister())
    - for events a plugin is interested but not having a full picture to deny, and thus want to _optimistically_ let it go, it returns success ✅ (today's EventsToRegister())
    - for events a plugin is interested and have a full picture to deny, it returns unschedulable ❌ (new knob)

**Comment by sanposhiho** [comment]
Ah, I completely misread @ahg-g 's first comment. 

> the nodeAffinity plugin returns success on all events that it is not interested in; on the events it is interested in, node events, it either returns success or unschedulable.

If we want to do this, we need to have a way to distinguish "success(not interested in)" from "success(interested in and OK to enqueue)". Then, it might come to Skip again in that sense; Skip is not far from Success, and actually, we're discussing regard both Success and Skip as having almost the same meaning in https://github.com/kubernetes/kubernetes/pull/114125/#discussion_r1039453233

**Comment by Huang-Wei** [comment]
I'm inclined to admit the necessity of an "intermediate" state, and propose the 2nd option commented above https://github.com/kubernetes/kubernetes/issues/114297#issuecomment-1360074261. Regarding whether to go with an explicit "intermediate" state, or deduce it in the code, we can discuss it later.

**Comment by sanposhiho** [comment]
I'm thinking work on it around the end-of-year/new-year holidays. This change doesn't require KEP, right?

**Comment by kerthcet** [comment]
We have `Skip` in PreFilter-Filter because they're coupled, non-universal to all extension points. Also think no need here.

I think we can experiment to migrate event handling to PreEnqueue, it makes scheduler framework more maintainable. 
One question here is are we going to implement PreEnqueue for each plugin or just have one PreEnqueue plugin. I think the answer is for each plugin. About performance, we can maintain a map targeting failedPluginName -> PreEnqueuePlugin, no need to loop all the plugins.

**Comment by ahg-g** [comment]
> I'm thinking start to work on it around the end-of-year/new-year holidays. This change doesn't require KEP, right?

We need a google doc to discuss and agree on how the framework interface will change and set the plan of record for any migrations if there will be any.

**Comment by sanposhiho** [comment]
Ok, I will start with summing up some ideas discussed here in a google doc.

**Comment by Huang-Wei** [comment]
> how is option 2 different from what was suggested in [#114297 (comment)](https://github.com/kubernetes/kubernetes/issues/114297#issuecomment-1358516406)?

The difference is `unschedulabe` doesn't (and cannot) act as a "veto", it's a conditional deny:

- if a plugin not present in pInfo.UnschedulePlugins returns `unschedulabe`, we abort enqueue
- if a plugin present in pInfo.UnschedulePlugins returns `unschedulable`, we should check whether at least one plugin return `success`. For example, a Pod failed plugin A & B, and an event may make pass plugin A, but not helpful on plugin B. We still need to enqueue the Pod as the nodes failed plugin A (in the previous attempt) may be schedulable.

**Comment by ahg-g** [comment]
Those semantics are too subtle and likely to cause problems. It would be great if we can list the use cases that needs handling in the doc, that will likely help us come up with a clearer and straightforward semantics.

**Comment by Huang-Wei** [comment]
That's right. We should come up with all use cases, and compare the pros & cons of "an explicit state" vs. "an implicit state that can be deduced".

**Comment by sanposhiho** [comment]
wrote a brief proposal doc on the google doc. Please take a look and any comments would be very much appreciated. 🙏 
https://docs.google.com/document/d/1S1_OqwCN2oY0Xp4dZt6XLCQQGu7dWm96blgXmGKhwSo/edit#

> we need to have a way to distinguish "success(not interested in)" from "success(interested in and OK to enqueue)".
https://github.com/kubernetes/kubernetes/issues/114297#issuecomment-1360474936

@ahg-g I'm still not sure this ^ point. How can we distinguish "success(not interested in)" from "success(interested in and OK to enqueue)" if we keep "unschedulable" as veto? 
https://docs.google.com/document/d/1S1_OqwCN2oY0Xp4dZt6XLCQQGu7dWm96blgXmGKhwSo/edit#heading=h.ad7o07rfzam

**Comment by sanposhiho** [comment]
Sorry for leaving here for a long time. 🙏 (I was spending busy days during the v1.27 release.)

I’d like to pursue this one during the v1.28 release.
@ahg-g @Huang-Wei Please take a look at this 🙇 

https://docs.google.com/document/d/1S1_OqwCN2oY0Xp4dZt6XLCQQGu7dWm96blgXmGKhwSo/edit#

I’ll share it in mailing list and slack channel

**Comment by alculquicondor** [comment]
@pohly can you provide feedback on Kensei's proposal?

**Comment by pohly** [comment]
See discussion in https://github.com/kubernetes/kubernetes/pull/117561. My (tentative) [conclusion](https://github.com/kubernetes/kubernetes/pull/117561#issuecomment-1531150735) is that this proposal doesn't address the problem of false positives (= pod gets moved to backoff queue unnecessarily because of some unrelated cluster event during a scheduling attempt of that pod).

**Comment by sanposhiho** [comment]
Retitled. Through the discussion with @/alculquicondor, I converted this proposal to proposing new extension point Requeue so that PreEnqueue won't have too much responsibility and make each extension point simpler.

**Comment by alculquicondor** [comment]
What is the current stance here? Are we doing both this and #117561 or just one? Which one is ahead in terms of covering use cases?

**Comment by sanposhiho** [comment]
Either #117561 or #117844. 
I'm still leaning toward #117844. It's now covering DRA's usecase ([ref](https://github.com/kubernetes/kubernetes/pull/117844#issuecomment-1542551164)), while #117561 has not yet covered this wise-enqueueing usecase. ([ref](https://github.com/kubernetes/kubernetes/pull/117561#discussion_r1190082252))
I'm not sure what @pohly now thinks about though. 🙂 Anyway, definitely we need another person to compare both of them.

**Comment by alculquicondor** [comment]
Sounds good. I reviewed #117561 and it locked reasonable, with room for improvement in follow ups.
I didn't have a chance to review #117844. Hopefully by Monday.

**Comment by pohly** [comment]
I tentatively agree that we could go either way, depending on which approach seems cleaner or more future-proof.

**Comment by sanposhiho** [comment]
@alculquicondor Forgot to mention, but you need to check https://github.com/kubernetes/kubernetes/pull/115796 from @pohly as well if you haven't yet.

The current situation is https://github.com/kubernetes/kubernetes/pull/117844 versus https://github.com/kubernetes/kubernetes/pull/117561 + https://github.com/kubernetes/kubernetes/pull/115796

**Comment by pohly** [comment]
Also note that the two different approaches are starting to converge. @sanposhiho has adopted `SchedulingHint` as result of `Requeue` and incorporated the `inFlight` tracking of pods that are being scheduled from https://github.com/kubernetes/kubernetes/pull/115796. What differs is the callback mechanism (via cluster event hint or Requeue extension) and the handling of concurrent events.

**Comment by sanposhiho** [comment]
> What differs is the callback mechanism (via cluster event hint or Requeue extension) and the handling of concurrent events.

Plus, how they treat unschedulable plugins in PodInfo. (https://github.com/kubernetes/kubernetes/pull/117561#discussion_r1190082252) 
It's an important difference from this wise-enqueueing PoV.

**Comment by sanposhiho** [comment]
I update the proposal document to be up-to-date.
https://docs.google.com/document/d/1S1_OqwCN2oY0Xp4dZt6XLCQQGu7dWm96blgXmGKhwSo/edit

**Comment by sanposhiho** [comment]
/close

QueueingHint is implemented in the scheduling queue. Each plugin has to support it, but there's another issue for that:
https://github.com/kubernetes/kubernetes/issues/118893
