### ISSUE TITLE
All probes  (liveness, readiness) fail on Debian 11 / CRI-O 1.25.1 / K8S 1.25.4

### ISSUE THREAD

**Issue by Xnyle** [kubernetes/kubernetes#114251]
### What happened?

Installed vanilla K8S 1.25.4 on vanilla Debian 11 with vanilla cri-o 1.25.1 as container runtime.

Then applied test pod from here 

https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/probe/exec-liveness.yaml

From the logs:

```
1202 13:06:06.257580   17325 remote_runtime.go:734] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1" containerID="ec9eb6391c79e079c4ee6ecdede3f8916a0ef3e6d74aefb069048171db41b455" cmd=[cat /tmp/healthy]
```

### What did you expect to happen?

Probes to actually work

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Kubernetes version

<details>

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"archive", BuildDate:"2022-11-10T22:18:49Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Bare Metal

### OS version

<details>

```
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

Linux redacted 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux

```

</details>

### Install tools

<details>
kubeadm init --config seeBelowFileContents

```
---

kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd

---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: "unix:///var/run/crio/crio.sock"
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-o 1.24.1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
kubectl patch configmap --namespace kube-flannel kube-flannel-cfg -p '{"data":{"net-conf.json":"{\"Network\": \"10.244.0.0/16\",\"Backend\":{\"Type\": \"host-gw\"}}"}}'
</details>

**Comment by neolit123** [comment]
please try getting help on the support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
kind support

**Comment by neolit123** [comment]
if you get feedback from maintainers / or other users that this is a bug, please reopen the ticket.

**Comment by Xnyle** [comment]
@neolit123 it is a bug, not in k8s but in cri-o or rather the way it uses conmon.

https://github.com/cri-o/cri-o/issues/6184

In order to save others from the hassle, the cri-o specific installation docs should mention the requirement to install patched / new conmon.

**Comment by neolit123** [comment]
please ask someone to add a note on this page in the crio section.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

if the crio maintainers are ok with it.
