### ISSUE TITLE
dynamic resource allocation: rename PodScheduling

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#114283]
The name is not ideal. This already came up during the initial API review and again in https://github.com/kubernetes/enhancements/issues/3063#issuecomment-1336225191:

@sftim wrote:
> Pretty much everything that has a kind in Kubernetes looks broadly idiomatic if you put a definite or indefinite article in front of it. However, PodScheduling is a bit weird.
> 
> (Fictional) examples:
> 
>  -   “the driver watches for a PodScheduling that matches this driver's resource type”
>  -    “you can use the kubectl tool to manually delete the PodScheduling”
>  -    “the PodScheduling has an ownerReference to the Pod and is therefore a dependent object of that Pod”

My own proposal was `PodSchedulingState`.

@sftim had some more:

- PodSchedulingHint
- PodSchedulingReservation
- ProvisionalPodBinding

**Comment by pohly** [comment]
I'm fine with `PodSchedulingHint`. My only concern is about plural vs. singular: a single object contains multiple hints.

I don't like "Reservation" because there is not reservation involved yet. Same with "Binding", although here the "Provisional" at least indicates that it is the step before that.

**Comment by sftim** [comment]
We could have `PodSchedulingHints`, the same way that there is an API kind `Endpoints` (`kind: Endpoint` doesn't work).

**Comment by sftim** [comment]
`kubectl get PodSchedulingHints --watch` feels idiomatic enough.

**Comment by pohly** [comment]
That sounds good to me.

**Comment by pohly** [comment]
This implies bumping our resource.v1alpha1 to
