### ISSUE TITLE
An option to disable Preferred Inter-pod affinity of existing pods

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#114267]
### What would you like to be added?

An option in the scheduler's ComponentConfig to ignore calculating preferences of exiting pods' affinity rules for the general case, and consider them only if the incoming pod has inter pod affinities.  In most cases this is sufficient because pods set inter-pod affinity against each other.

In the past we optimized this case by tracking only pods with inter-pod affinity, but to achieve the next level of scheduling throughput, optionally disabling this feature will be useful.

Specifically, I am suggesting that [PreScore](https://github.com/kubernetes/kubernetes/blob/3e26e104bdf9d0dc3c4046d6350b93557c67f3f4/pkg/scheduler/framework/plugins/interpodaffinity/scoring.go#L126) exits early if this option is enabled and the pod has no inter-pod affinities.

### Why is this needed?

To optimize for higher scheduling throughput.

/sig scheduling

/cc @Huang-Wei @alculquicondor

**Comment by alculquicondor** [comment]
I don't think we look at existing pods with preferred pod affinity, just hard constraints.

**Comment by ahg-g** [comment]
We do, [PodsWithAffinity](https://github.com/kubernetes/kubernetes/blob/3e26e104bdf9d0dc3c4046d6350b93557c67f3f4/pkg/scheduler/framework/plugins/interpodaffinity/scoring.go#L191) includes both.

**Comment by alculquicondor** [comment]
I see. My memory failed me.

**Comment by Huang-Wei** [comment]
> An option in the scheduler's ComponentConfig to ignore calculating preferences of exiting pods' affinity rules for the general case, and consider them only if the incoming pod has inter pod affinities.

By "exiting pods' affinity rules", both existing pods' required and preferred, or just preferred? It's a bit ambiguous with the issue tile. 

To confirm: if some existing Pods carry _hard_ PodAffinity, with the new option, incoming Pods without inter-pod affinity will be still impacted by the existing Pod (and `HardPodAffinityWeight` still functions), or not?

**Comment by ahg-g** [comment]
> By "exiting pods' affinity rules", both existing pods' required and preferred, or just preferred? It's a bit ambiguous with the issue tile.

Both.

> To confirm: if some existing Pods carry hard PodAffinity, with the new option, incoming Pods without inter-pod affinity will be still impacted by the existing Pod (and HardPodAffinityWeight still functions), or not?

Those will be ignored too, basically ignore any impact existing pods will have on the pod if the incoming pod doesn't have inter-pod affinity constraints.

**Comment by alculquicondor** [comment]
> basically ignore any impact existing pods will have on the pod if the incoming pod doesn't have inter-pod affinity constraints.

But only for scores, right? Filters still work as they did before.

**Comment by ahg-g** [comment]
Correct, just for scores.
