### ISSUE TITLE
Improve error handling for namespace deletions when not all server apis are retrievable

### ISSUE THREAD

**Issue by filiprejmus** [kubernetes/kubernetes#114214]
### What happened?

Using terraform with GKE and tearing down my cluster the process gets stuck on namespace deletion, probably because the metrics.k8.io server gets torn down prematurely and not all resource types can be fetched. The process of deleting the namespace gets stuck using kubectl too.

### What did you expect to happen?

While the underlying issue is not kubernetes related, one could suggest a better error handling it that case. If all api resources cannot be fetched, the delete namespace operation should perhaps return an error instead of getting stuck.

### How can we reproduce it (as minimally and precisely as possible)?

Provision a cluster with a nodepool on gke using terraform, create a namespace and deploy via helm-provider inside that namespace. Destroy the cluster via terraform destroy.

### Anything else we need to know?

This is more of a feature request than a bug and I am aware of the discussion [here](https://github.com/kubernetes/kubernetes/issues/60807). If this suggestion gets rejected I would be very thankful for an explanation so I can understand kubernetes better :)

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12-gke.100", GitCommit:"fd16f64da04c784b85909576a3f7abf4ed49b949", GitTreeState:"clean", BuildDate:"2022-09-22T09:23:33Z", GoVersion:"go1.17.13b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by anggao** [comment]
I'd like to work on this if that's ok

**Comment by liggitt** [comment]
I think the question at https://github.com/kubernetes/kubernetes/issues/114214#issuecomment-1339740147 is still pending... is the namespace condition showing the issue blocking deletion accurately?
