### ISSUE TITLE
Kubernetes ImagePullPolicy Is Not Being Propogated To A Pod

### ISSUE THREAD

**Issue by schrammm** [kubernetes/kubernetes#114312]
### What happened?

The ImagePullPolicy a statefulset is set to `IfNotPresent` however the running pod in that statefulset has ImagePullPolicy to be set to `Always`. The pod meets the conditions for `IfNotPresent`.

### What did you expect to happen?

The expected result was that the pod's imagePullPolicy would match the imagePullPolicy of the statefulset.

### How can we reproduce it (as minimally and precisely as possible)?

Have a statefulset with the `imagePullPolicy` set to `Always` with a running pod that has a `imagePullPolicy` set to `Always`. Change the `imagePullPolicy` for the statefulset to `IfNotPresent` and observe how the pod does not change to `IfNotPresent`, regardless if the pod is stopped and recreated. This can be tried on any version of Kuber

### Anything else we need to know?

We saw this behavior for Kubernetes versions 1.22.X, 1.23.X and 1.24.X

### Kubernetes version

<details>

```console
$ kubectl version
# 1.23.X
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
> Have a statefulset with the `imagePullPolicy` set to `Always` with a running pod that has a `imagePullPolicy` set to `Always`. Change the `imagePullPolicy` for the statefulset to `IfNotPresent` and observe how the pod does not change to `IfNotPresent`, regardless if the pod is stopped and recreated. This can be tried on any version of Kuber

I confirmed that this is not reproduced in master and v1.23.15.
Which kubernetes environment do you use? Maybe the issue is relevant to your cluster setting.

**Comment by schrammm** [comment]
We are using a production environment with version 1.23.12. Are there any specific settings you could recommend checking on? We crossed off the issue being caused by using the admission controller `AlwaysPullImages`.

**Comment by xuzhenglun** [comment]
> issue

check admission controllers settings:
1. https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages
2. some [customs dynamic admission controller](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/)  can cause this issues too.

**Comment by schrammm** [comment]
1. We are not using `AlwaysPullImages` admission controller
2. Is there any kubectl commands that can be run to view if a custom dynamic admission controller is in use and if so what the configuration is?

**Comment by xuzhenglun** [comment]
> 1. We are not using `AlwaysPullImages` admission controller
> 2. Is there any kubectl commands that can be run to view if a custom dynamic admission controller is in use and if so what the configuration is?

please take a look doc that I refered https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#configure-admission-webhooks-on-the-fly. There is a object kind called [MutatingWebhookConfiguration](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#mutatingwebhookconfiguration-v1-admissionregistration-k8s-io).

you can check that by running `kubectl get mutatingwebhookconfiguration`

**Comment by schrammm** [comment]
I appreciate the document you referenced. However it does not have the exact command I am looking for. I'm able to check the ```kubectl get mutatingwebhookconfiguration``` but I am looking for a way to inspect the name given to be able to verify if the imagePullPolicy is being configured within the mutatingwebhookconfiguration

**Comment by xuzhenglun** [comment]
> I appreciate the document you referenced. However it does not have the exact command I am looking for. I'm able to check the `kubectl get mutatingwebhookconfiguration` but I am looking for a way to inspect the name given to be able to verify if the imagePullPolicy is being configured within the mutatingwebhookconfiguration or a validatingwebhookconfiguration.

No, you can not inspect it by name only. It's necessary to explore the doc and source code of the webhook.

**Comment by schrammm** [comment]
@xuzhenglun I was able to check the source code of the webhook. For example, for a webhook called foo, I ran ```kubect get mutatingwebhookconfiguration foo -o yaml``` . The results are similar to what is shown in the ```Webhook configuration``` in the doc. However after exploring the doc and the results I am unable to find any mention of the ```imagePullPolicy```. Is there another way to examine this information that would contain ```imagePullPolicy```?

**Comment by xuzhenglun** [comment]
@schrammm
> Is there another way to examine this information that would contain imagePullPolicy?

you may want to explore `kube-apiserver` audit log to dig out more info. FYI: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
