### ISSUE TITLE
Make it easy to request kube-apiserver and kubelet to support strong TLS configurations

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#114316]
This is similar to #91444 and #81145 but the issue here is not what is _possible_ but what is _easy_ for an admin to say.

Currently kube-apiserver and kubelet (like [etcd](https://github.com/etcd-io/etcd/issues/14906)) default to accepting anything that go does.  My local security scanner objects to some of those ciphersuites.  I get a list of offending ones.  If there were a command line flag or config file field that I could use to _exclude_ the offending ciphers, that would be an easy reactive way to handle this.

Additionally or alternatively, it would be great if there were a simple way to request a stronger-than-go's-default configuration, that would be great too.  We may not want to be in the business of authoring that configuration ourselves, but FIPS has already done this.  How about a `--fips-tls` command line flag?  Or a `--boring-crypto` command line flag?

**Comment by ap-kulkarni** [comment]
I would like to take a look and work on this. Is it necessary to be `triage accepted` to work on this?

**Comment by BenTheElder** [comment]
Adding a new CLI flag may require filing a KEP and going through Production Readiness Review to ensure the changes are safe and well thought out.

You could work on proposing the specifics.

**Comment by MikeSpreitzer** [comment]
No, triage accepted is not a pre-req to working on something.
