### ISSUE TITLE
Add NodeName PreFilter to improve the scheduling efficiency of pod with NodeName

### ISSUE THREAD

**Issue by 1978629634** [kubernetes/kubernetes#114396]
### What happened?

I found a problem when I read the scheduler code,
In the case that PreFilterResult([#108648](https://github.com/kubernetes/kubernetes/issues/108648)) can filter nodes, it is more appropriate to put NodeName in Prefilter

### What did you expect to happen?

Add NodeName PreFilter to improve the scheduling efficiency of pod with NodeName

### How can we reproduce it (as minimally and precisely as possible)?

None

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
I think it's a valid idea because we do the similar thing on `NodeAffinity` ([ref](https://github.com/kubernetes/kubernetes/pull/108648))

He's already got started it: https://github.com/kubernetes/kubernetes/pull/114386

**Comment by ahg-g** [comment]
Pods with nodeName set shouldn't be placed in the scheduling queue, so the scheduler will never attempt to schedule them in the first place.

**Comment by 1978629634** [comment]
> Pods with nodeName set shouldn't be placed in the scheduling queue, so the scheduler will never attempt to schedule them in the first place.

should we delete the NodeName Filter?

**Comment by 1978629634** [comment]
> We can probably remove it, but it will require deprecation since it is part of the component config API, and deprecating it will need creating a new component config API version, so I would do it only if we have another stronger reason to do so.

Thank you very much for your reply
Should we disable NodeName in existing deafault plugins?
Or add some code comments to show that it will never work
Otherwise this part of the code will confuse us

**Comment by alculquicondor** [comment]
We are not supposed to change defaults in APIs... so in a way we are stuck with it now. Adding a comment that this plugin is useless is fine. I think it was meant to be a sample of how to write Filter plugins.
