### ISSUE TITLE
We forgot to remove the old netpol tests that are covered by new matrix based tests

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#114389]
### What happened?

  we can follow up on https://github.com/kubernetes/kubernetes/pull/102933 now, by finishing removing all but the SCTP tests in the old legacy filters.

### What did you expect to happen?

we would have removed the old tests by now :) but we didnt wanna break OVN .  I think OVN CI is passing now w/ the new tests though so we're good ! 

### How can we reproduce it (as minimally and precisely as possible)?

NA

### Kubernetes version

main

### Cloud provider

all

### OS version

all

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by astoycos** [comment]
/assign 

I can take care of this one.
