### ISSUE TITLE
kube-apiserver using unregistered and unusual label

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#114314]
### What happened?

The code at
https://github.com/kubernetes/kubernetes/blob/86f3fa94f1b75da275a8040e4155840a7b473dc1/pkg/controlplane/instance.go#L126 specifies a ~annotation~ label that API servers set on Leases (each API server registers its own lease).

https://k8s.io/docs/concepts/architecture/leases/#api-server-identity is likely to document this once v1.26 is released; the alpha for API server identity didn't get documented.

Here's the problems:
- as a project, we use `kubernetes.io` as the domain for labels and annotations - see https://k8s.io/docs/reference/labels-annotations-taints/
  - there are a couple of exceptions in https://kubernetes.io/docs/reference/labels-annotations-taints/audit-annotations/, FWIW
- if we document and register this `k8s.io/component` label, people may well confuse it with https://kubernetes.io/docs/reference/labels-annotations-taints/#app-kubernetes-io-component and use the wrong thing

### What did you expect to happen?

I guess ideally we'd have proposed and then been able to review docs for this when it went alpha, and in that alternative history the discrepancy would have been much more obvious, and it could have been fixed earlier.

I think we should fix it so that we follow the convention of nearly every other annotation used in Kubernetes code.

### How can we reproduce it (as minimally and precisely as possible)?

Look at the source code. Any text editor would work.

### Anything else we need to know?

/sig api-machinery

### Kubernetes version

1.25
1.26 (unreleased)

### Cloud provider

n/a

### OS version

n/a

### Install tools

n/a

### Container runtime (CRI) and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

**Comment by aojea** [comment]
ping @andrewsykim @lavalamp

**Comment by sftim** [comment]
My suggestion would be `control-plane.kubernetes.io/component` (explicitly distancing the control plane from node-level components like `kube-proxy`). `internal.kubernetes.io/component` is good too.

**Comment by sftim** [comment]
> I think that's already confusing, why would there be an official k8s label about an end-user application component?

https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels is our explanation for this.


/retitle kube-apiserver using unregistered and unusual label

**Comment by andrewsykim** [comment]
If we feel strongly about the name change, I propose we update it now and backport for v1.26.1? I _think_ this should be fine to do because:
1) The label selector is strictly used internally by the gc controller that runs in kube-apiserver, so it would be updated in lockstep to check the new label. In the worse case when a cluster upgrades from v1.26.0 -> v1.26.1, there will be N (1-5) leases that will never be garbage collected because old leases have labels that the new gc controller is not selecting against. 
2) v1.26 is the first version where this is enabled by default, so we shouldn't anticipate many existing consumers of the lease or use of that label. In the worse case we end up with a handful of leases that aren't garbage collected like in 1).
3) No one is _really_ going to use v1.26.0 :)

**Comment by andrewsykim** [comment]
If we _really_ care about the v1.26.0 -> v1.26.1 corner case, we can update GC controller to garbage collect leases with both labels `k8s.io/component=kube-apiserver` and `internal.kubernetes.io/component`

**Comment by sftim** [comment]
> If we _really_ care about the v1.26.0 -> v1.26.1 corner case, we can update GC controller to garbage collect leases with both labels `k8s.io/component=kube-apiserver` and `internal.kubernetes.io/component`

When other (usually external) projects or components aren't using labels or annotations the recommended way, I usually recommend handling the old deprecated key for a while (or even indefinitely), but mentioning the fixed key in documentation.

So, that sounds good. I don't feel that a fix is urgent, but I do recommend against leaving it this way all the way to v1.27.0

**Comment by andrewsykim** [comment]
Summarizing discussion we had on this in SIG API Machinery today:
* We're going to move the identity lease controller and GC controller to generic apiserver (as part of https://github.com/kubernetes/kubernetes/pull/114240), with optional flags to set the lease namespace and component label value. These will always be configured in kube-apiserver in the `kube-system` namespace, but off by default for any aggregated apiservers pulling in generic apiserver.
* The label key / value will change to something that follows documented best practices, which _should_ be safe as long as GC controller is updated to watch both the old and new labels until v1.28.
* There should be a Role defined to manged identities that any aggregated apiserver can bind to for their own system namespaces

**Comment by andrewsykim** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/114586 for just the label rename -- still need to do further testing but I believe it should be safe to do as long as we garbage collect leases for both the old and new label for 1 release.
