### ISSUE TITLE
e2e conformance pod sending total tests back as zero for conformance image 1.25.x

### ISSUE THREAD

**Issue by raosaurabh** [kubernetes/kubernetes#114313]
### What happened?

Our team uses sonobuoy to run the conformormance tests on a cluster and displays the results to the users.
We have been using conformance image 1.21.x until now and it sends back progress data to sonobuoy pod and our service reads it from the sonobuoy pod.
The progress data included the total number of tests to be run and the completed tests. For 1.21 conformance we were receiving this data properly but when switching to 1.25.x conformance we are getting the total tests as zero. This is causing issues in our UI.
Not sure what version of conformance image introduced this but we were using 1.21 and started seeing this issue after moving to 1.25.x. The conformance image versions in between 1.21 -1.25 are not CVE free so we cannot use them.

### What did you expect to happen?

Total number of tests should be non-zero for conformance image 1.25.x. Ideally i think it should come back as 360.

### How can we reproduce it (as minimally and precisely as possible)?

- provision a 1.25 kubernetes kind (or anything else) cluster
- Install sonobuoy 
- Run conformance scan on the cluster
- Check the annotation on the sonobuoy pod ` sonobuoy.hept.io/status` . This is set by sonobuoy based on the data it gets back from the e2e conformance pod.
- The total tests comes as zero

### Anything else we need to know?

I just found it on 1.25.x conformance. Not really sure when this was introduced. Need to make sure back dated versiosn also have this fix in case they have this issue.

### Kubernetes version

<details>
1.25 cluster with 1.25.x conformance with any sonobuoy version
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
ANY
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Conformacne e2e plugin
</details>

**Comment by raosaurabh** [comment]
@pohly FYI

**Comment by pohly** [comment]
You remember correctly: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/reporters/progress.go#L33-L49

It looks like that TODO didn't get addressed? I thought it had been.

@raosaurabh: the other thing that was unclear regarding sonobuoy was whether it reads these test statistics from stderr or gets them via HTTP. We removed the stderr output (I think in 1.26) but kept `-progress-report-url` (https://github.com/kubernetes/kubernetes/blob/72acaad83924360960e21915aa94cd1db8d0196c/test/e2e/framework/test_context.go#LL348C51-L348C70). This seems to be backed by https://grep.app/search?q=progress-report-url (sonobuoy sets the parameter), but it would be good to get definite confirmation.

Also, does Sonobuoy run tests in parallel? If it does, then these statistics are probably useless or at least will need considerable post-processing.

**Comment by chendave** [comment]
/assign

I will take a look as https://github.com/onsi/ginkgo/issues/994 has been fixed and closed

**Comment by pohly** [comment]
/reopen

The fix went in, but let's keep the issue open for a while longer until we really know that it now works as expected.

/assign @raosaurabh

**Comment by pohly** [comment]
/remove-lifecycle rotten

@raosaurabh: I discussed this further with @hh (see also https://kubernetes.slack.com/archives/C78F00H99/p1681841652413779) and while a final decision is pending, I am inclined to remove the progress reporting feature because I suspect that it is conceptually broken (to be confirmed) and lacks in-tree support (unit tests, owner).

Before I do that, can you clarify:
- Are you running tests in parallel and does progress reporting work properly, i.e. does it go from 0 to 100%?
- When you said, "causing issues in our UI", what UI is that?
-

**Comment by pohly** [comment]
Ping @raosaurabh 

Please see https://github.com/kubernetes/kubernetes/issues/114313#issuecomment-1547279002
