### ISSUE TITLE
Cross-release round-trip fuzz test

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11431]
To help catch incompatibilities we introduce, we need something like the round-trip fuzz test, but where the objects are encoded using a prior release and decoded using code at head, and vice versa.
cc @lavalamp

**Comment by lavalamp** [comment]
Maybe we can extend/copy hack/test-update-storage-objects.sh to do this? We'd need to grab older binaries. This would be easier if we pushed our apiserver etc containers to gcr.io somewhere.

**Comment by ihmccreery** [comment]
Related to #15131, if I understand correctly.  This is lower level than running e2e's amidst upgrades.
