### ISSUE TITLE
Elasticsearch-logging rc and svc are getting automatically deleted

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#11435]
I created elasticsearch-logging rc and service from https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch, but they vanished after some time.

Steps to repro:

```
$ kubectl create -f cluster/addons/fluentd-elasticsearch/es-controller.yaml
$ kubectl create -f cluster/addons/fluentd-elasticsearch/es-service.yaml
```

I verified that the rc and service were created fine:

```
$ ./cluster/kubectl.sh get rc --all-namespaces
NAMESPACE     CONTROLLER                     CONTAINER(S)            IMAGE(S)                                          SELECTOR                                   REPLICAS
kube-system   elasticsearch-logging-v1       elasticsearch-logging   gcr.io/google_containers/elasticsearch:1.7        k8s-app=elasticsearch-logging,version=v1   2
kube-system   kube-dns-v8                    etcd                    gcr.io/google_containers/etcd:2.0.9               k8s-app=kube-dns,version=v8                1
                                             kube2sky                gcr.io/google_containers/kube2sky:1.11                                                       
                                             skydns                  gcr.io/google_containers/skydns:2015-03-11-001                                               
                                             healthz                 gcr.io/google_containers/exechealthz:1.0                                                     
kube-system   kube-ui-v1                     kube-ui                 gcr.io/google_containers/kube-ui:v1.1             k8s-app=kube-ui,version=v1                 1
kube-system   monitoring-heapster-v5         heapster                gcr.io/google_containers/heapster:v0.16.0         k8s-app=heapster,version=v5                1
kube-system   monitoring-influx-grafana-v1   influxdb                gcr.io/google_containers/heapster_influxdb:v0.3   k8s-app=influxGrafana,version=v1           1
                                             grafana                 gcr.io/google_containers/heapster_grafana:v0.7             
```

```
$ ./cluster/kubectl.sh get svc --all-namespaces
NAMESPACE     NAME                    LABELS                                                                                              SELECTOR                        IP(S)          PORT(S)
default       kubernetes              component=apiserver,provider=kubernetes                                                             <none>                          10.0.0.1       443/TCP
kube-system   elasticsearch-logging   k8s-app=elasticsearch-logging,kubernetes.io/cluster-service=true,kubernetes.io/name=Elasticsearch   k8s-app=elasticsearch-logging   10.0.230.153   9200/TCP
kube-system   kube-dns                k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS                      k8s-app=kube-dns                10.0.0.10      53/UDP
                                                                                                                                                                                         53/TCP
kube-system   kube-ui                 k8s-app=kube-ui,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeUI                        k8s-app=kube-ui                 10.0.116.215   80/TCP
kube-system   monitoring-grafana      kubernetes.io/cluster-service=true,kubernetes.io/name=Grafana                                       k8s-app=influxGrafana           10.0.39.192    80/TCP
kube-system   monitoring-heapster     kubernetes.io/cluster-service=true,kubernetes.io/name=Heapster                                      k8s-app=heapster                10.0.189.133   80/TCP
kube-system   monitoring-influxdb     kubernetes.io/cluster-service=true,kubernetes.io/name=InfluxDB                                      k8s-app=influxGrafana           10.0.186.22    8083/TCP
                                                                                                                                                                                         8086/TCP

```

But running the same commands after ~5 mins, didnt return elasticsearch-logging rc or service.

**Comment by nikhiljindal** [comment]
@dchen1107 verified that this is not due to my cluster going crazy. She could repro on her cluster as well.

cc @satnam6502 @bgrant0607

**Comment by nikhiljindal** [comment]
Is it by policy that users are not allowed to create resources in kube-system namespace? Or is this a bug?

If its a policy that users should not be creating resources in kube-system namespace, then maybe we should update configs in cluster/addons/ to use default namespace instead of kube-system?

**Comment by nikhiljindal** [comment]
Actually, this doesnt seem to be related to the kube-system namespace.
I recreated my rc and svc in the default namespace and they still vanished.

So the issue seems to be with elasticsearch-logging and not the kube-system namespace.

**Comment by satnam6502** [comment]
Oh dear, this does not look right, you should be able to run those services. However, unless you have created a cluster with Fluentd to Elasticsearch logging enabled then nothing good is likely to happen.
What is the type of cluster you created? A Cloud Logging cluster or an Elasticsearch Logging cluster? Or neither?

**Comment by piosz** [comment]
This is due to the policy of addons update. @marekbiskup can tell you more.

**Comment by marekbiskup** [comment]
@nikhiljindal , the controllers you are trying to create are system services:
```
    kubernetes.io/cluster-service: "true"
```
The policy of starting/stopping these services is described here:
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/addons

The interesting paragraph is:

[begin]
The add-ons are visible through the API (they can be listed using kubectl), but manipulation of these objects is discouraged because the system will bring them back to the original state, in particular:

 * if an add-on is stopped, it will be restarted automatically
 * if an add-on is rolling-updated (for Replication Controlers), the system will stop the new version and start the old one again (or perform rolling update to the old version, in the future).
[end]

Probably we're missing this information

 * If an addon is created via kubectl/API, it will automatically be stopped by the system.

**Comment by satnam6502** [comment]
Oh dear, this is working as intended. Hmm.... 
Un-assigning myself. Although I think this is confusing.

**Comment by marekbiskup** [comment]
I agree it's confusing.
But I haven't found any idea how to make addon-upgrade work after 'resalting' the cluster (so that obsolete addons are deleted).

Anyway, I'm glad the mechanism was proven to work as intended. ;)

@nikhiljindal, @satnam6502, if you have any idea how to differentiate obsolete addons from addons just added by the user, we may implement it in the next version of addon-updater.

**Comment by dchen1107** [comment]
@marekbiskup This is my understanding after investigating the issue with @nikhiljindal. But this is very confusing to the users. We should mark this as known issue for 1.0: #10760.

**Comment by bgrant0607** [comment]
cc @jackgr

**Comment by dchen1107** [comment]
We should re-examine the mechanism we had for updating addons services after 1.0 release.

**Comment by bgrant0607** [comment]
For deploying addons, in general

**Comment by roflmao** [comment]
I just noticed this issue while deploying a cluster on GKE.
Put up es-controller and es-service from https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch
More info in #17160

Should i create a new issue on SO?

**Comment by nikhiljindal** [comment]
I guess, you can try creating those controllers without `kubernetes.io/cluster-service: "true"` in the yaml definition and then they should be fine?

**Comment by roflmao** [comment]
This helped. But i cant access the service via the master then.
