### ISSUE TITLE
pod completely monopolizes the cpu resources

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#114381]
### What would you like to be added?

Let the pod completely monopolizes the cpu resources。
It is mentioned here:  https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/

Note: System services such as the container runtime and the kubelet itself can continue to run on these exclusive CPUs.  The exclusivity only extends to other pods.

any way let pod completely monopolizes the cpu resources？

### Why is this needed?

There have high performance workloads like NFV in my environments.Do not want any other process use cpu.

**Comment by sftim** [comment]
This would build on the work for https://github.com/kubernetes/enhancements/issues/375 

You _can_ pin the kubelet to a specific CPU (eg using systemd), and can do similar things for most other system services - see  https://www.slideshare.net/azilian/control-your-service-resources-with-systemd-249928088. I think the remaining challenge is to make sure that the low level container runtime(s) and the CRI adapter also do the right thing and never schedule onto the same core as your latency sensitive workload.

If that's right, we already have all the code we need for this, but we don't yet have docs about how to do it.

https://chenna.me/blog/2022/09/11/docker-cpu-isolation/ looks interesting and has some relevant links.
@willzhang would you be willing to report back about the gaps that Kubernetes itself needs to fill?
