### ISSUE TITLE
[Winkernel Proxier] Implement support for internal traffic policy in windows kube proxy

### ISSUE THREAD

**Issue by princepereira** [kubernetes/kubernetes#114419]
### What would you like to be added?

- These are changes as per KEPS: https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2086-service-internal-traffic-policy
- When a InternalTrafficPolicy is set to Local, consider only local endpoints for creating cluster ip load balancer.
- When both InternalTrafficPolicy and ExternalTrafficPolicy is set to Local, ignore creating remote endpoints.

### Why is this needed?

- With these changes, kube proxy will take constant time always for load balancer creation.
- Implementing InternalTrafficPolicy feature will optimize the load balancer recreation during rolling updates.
- This will also minimize the leaking of traffic through stale deleting endpoints during rolling update.

**Comment by thockin** [comment]
Who gets assigned windows kube-proxy issues now?  @danwinship

**Comment by thockin** [comment]
@mikez87

**Comment by MikeZappa87** [comment]
This can be closed as the referenced PR has been merged. 

/close
