### ISSUE TITLE
cloud-controller-manager image has no valid multiarch manifest

### ISSUE THREAD

**Issue by farcop** [kubernetes/kubernetes#114491]
### What happened?

When I run on my M1 Mac
```
docker pull registry.k8s.io/cloud-controller-manager:v1.15.12
docker inspect registry.k8s.io/cloud-controller-manager:v1.15.12 | grep Architecture
        "Architecture": "amd64",
```
it returns wrong amd64 manifest instead of arm64 for my M1 Mac

### What did you expect to happen?

registry.k8s.io/cloud-controller-manager:v1.15.12 contains valid multiarch manifest

```
docker pull registry.k8s.io/cloud-controller-manager:v1.15.12
docker inspect registry.k8s.io/cloud-controller-manager:v1.15.12 | grep Architecture
        "Architecture": "arm64",
```

### How can we reproduce it (as minimally and precisely as possible)?

Run on arm-based machine and check output
```
docker pull registry.k8s.io/cloud-controller-manager:v1.15.12
docker inspect registry.k8s.io/cloud-controller-manager:v1.15.12 | grep Architecture
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
```
[davanum@c889f3bd53ed 08:00] ~/go/src/gitlab.aws.dev/eks-dataplane/eks-kubernetes-patches ⟩ skopeo inspect --raw docker://registry.k8s.io/cloud-controller-manager:v1.15.12
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:3412f263131a399e549aceb8e160b3848e97dd3a7ac8731b68e5f0d61e791dd3",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:92519d75ef7339e5540c6d88566d1c6f87f0a97cd5b9fe024309fa88013e427c",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:fdfe2424da2aba522d69f641e88071ba4d9385a6b5f9129a9be821577a7347f5",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:b8b5a9dddd7f416162225eba2d812cfbe4505b8433439120712472ae81c2b7cc",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 741,
         "digest": "sha256:75be2773a490a3eeb713beb6c1ae7e86a5e071aaaeda45bd6132cd44e77dcb2c",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

**Comment by farcop** [comment]
@dims why did you close the bug without the check I specified?
Multiarch manifest is invalid. It points on the wrong arhitecture.

```
 % docker pull registry.k8s.io/cloud-controller-manager-arm64:v1.15.12 
v1.15.12: Pulling from cloud-controller-manager-arm64
Digest: sha256:fdfe2424da2aba522d69f641e88071ba4d9385a6b5f9129a9be821577a7347f5
Status: Downloaded newer image for registry.k8s.io/cloud-controller-manager-arm64:v1.15.12
registry.k8s.io/cloud-controller-manager-arm64:v1.15.12

% docker inspect registry.k8s.io/cloud-controller-manager-arm64:v1.15.12 | grep Architecture
        "Architecture": "amd64",
```

**Comment by dims** [comment]
@farcop look at the SHA in the skopeo output for the digest `fdfe2424da2aba522d69f641e88071ba4d9385a6b5f9129a9be821577a7347f5` it is the right one (the one for arm64). I have no idea if there is a problem with docker on what it is showing and that is not a problem in k8s.

In general
- use the multi-arch manifest and NOT use arch specific image.. so use `registry.k8s.io/cloud-controller-manager:v1.15.12`
- use tools that inspect the image in the registry itself and not locally... so use `skopeo`
- check the SHA's as i have no idea what local end up seeing. (`fdfe2424da2aba522d69f641e88071ba4d9385a6b5f9129a9be821577a7347f5` is the right SHA for `"arm64"` image)

this is as far as we can tell, feel free to take it up with docker folks in their repository, not here.

**Comment by farcop** [comment]
@dims the same issue https://github.com/kubernetes-sigs/cluster-proportional-autoscaler/issues/123 was fixed
This issue must be fixed too.
The problem is that cloud-controller-manager-arm64:v1.15.12 is not arm arch, and then it blob used in multiarch manifest making it invalid.
Please direct me in right repo in which this bug can be fixed.

**Comment by dims** [comment]
@farcop can you check something more recent? v1.15.12 is way old, we are now on v1.26.0

**Comment by farcop** [comment]
@dims there is no image with this tag.
```
docker pull registry.k8s.io/cloud-controller-manager-arm64:v1.26.0  
Error response from daemon: manifest for registry.k8s.io/cloud-controller-manager:v1.26.0 not found: manifest unknown: Failed to fetch "v1.26.0"
```
The latest that I can see is v1.16.0-alpha.3
`curl -sL https://registry.k8s.io/v2/cloud-controller-manager/tags/list | jq .tags`

**Comment by aojea** [comment]
I think that this falls into sig cloud provider @pacoxu 🤔

**Comment by nckturner** [comment]
I don't think we intend for that image to be consumed, but I'll let Walter chime in.

/assign @cheftako
