### ISSUE TITLE
validation has a GCE-ism baked in

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#114436]
pkg/apis/core/validation/validation.go

```
func ValidateReadOnlyPersistentDisks(volumes []core.Volume, fldPath *field.Path) field.ErrorList {                                                                             
    allErrs := field.ErrorList{}
    for i := range volumes {
        vol := &volumes[i]
        idxPath := fldPath.Index(i)
        if vol.GCEPersistentDisk != nil {
            if !vol.GCEPersistentDisk.ReadOnly {
                allErrs = append(allErrs, field.Invalid(idxPath.Child("gcePersistentDisk", "readOnly"), false, "must be true for replicated pods > 1; GCE PD can only be mounted on multiple machines if it is read-only"))
            }    
        }    
        // TODO: What to do for AWS?  It doesn't support replicas
    }    
    return allErrs
}
```

We should probably just get rid of this.

**Comment by kidddddddddddddddddddddd** [comment]
Although I'm not familiar with codes in `pkg/apis`, I'm willing to help with this one as it's labeld `good first issue`.
However, I'm not sure what do you mean by `just get rid of this`, do you mean we don't have to check `readonly` for gce pds from now on?

**Comment by BenTheElder** [comment]
This should not be marked 
/good-first-issue
without the criteria the bot will comment about when doing so, namely an agreed upon approach rather than a "probably" 😅
It can be marked help-wanted.

**Comment by thockin** [comment]
Fair, I removed good-first-issue

I posit that this block of code does almost nothing of value and it should be removed.  It *only* works for GCE and not even with the more modern CSI drivers, so - pointless.

@msau42 disagree?

**Comment by msau42** [comment]
I don't think this validation is critical. If we remove the validation and someone tries to do this, they will get a failure later on (ie attach error), although we may turn the behavior from deterministic to non-deterministic. Without the validation, he first replica will succeed and and the subsequent replicas will get an error. But if that first pod gets deleted, then one of the subsequent pods will win.

But we also don't have this kind of validation for PV types, csi or otherwise. So I think it is ok to remove it and rely on the platform error.

**Comment by kidddddddddddddddddddddd** [comment]
> But we also don't have this kind of validation for PV types, csi or otherwise. So I think it is ok to remove it and rely on the platform error.

In that case, I think I can help with this one by removing this function. Seems like a easy one to me?
/assign

**Comment by kidddddddddddddddddddddd** [comment]
unassign myself for this is not easy as I thought, and I'm not familar with api changes :(

**Comment by thockin** [comment]
There are some impl notes and hints in the linked PR #114480

**Comment by mfordjody** [comment]
OK, I need some time. It is currently being completed

**Comment by nckturner** [comment]
Probably more in sig storage's realm, but we will continue tracking this.
