### ISSUE TITLE
Kubelet Service does not start

### ISSUE THREAD

**Issue by Ali0600** [kubernetes/kubernetes#114473]
When I check the status of the Kubelet service, this is the error it gives me.

> ● kubelet.service - kubelet: The Kubernetes Node Agent
>      Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
>     Drop-In: /etc/systemd/system/kubelet.service.d
>              └─10-kubeadm.conf
>      Active: activating (auto-restart) (Result: exit-code) since Tue 2022-12-13 21:54:10 UTC; 3s ago
>        Docs: https://kubernetes.io/docs/home/
>     Process: 9696 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBEL>
>    Main PID: 9696 (code=exited, status=1/FAILURE)

It keeps saying activating (auto-restart) and doesn't give me any information. But when I do journalctl -fu kubelet, this is what I get.

> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.270937    9794 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.279683    9794 server.go:659] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.280152    9794 container_manager_linux.go:267] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.280245    9794 container_manager_linux.go:272] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: KubeletOOMScoreAdj:-999 ContainerRuntime: CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>} {Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] CPUManagerPolicy:none CPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container CPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none ExperimentalTopologyManagerPolicyOptions:map[]}
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.280268    9794 topology_manager.go:134] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.280289    9794 container_manager_linux.go:308] "Creating device plugin manager"
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: I1213 21:56:03.280331    9794 state_mem.go:36] "Initialized new in-memory state store"
> Dec 13 21:56:03 ip-192-168-100-6 kubelet[9794]: E1213 21:56:03.282744    9794 run.go:74] "command failed" err="failed to run Kubelet: validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"

I'm using containerd as the CRI, this is kind of a different question, but do I need Docker installed in anyway if I'm just trying to setup a Kubernetes Cluster with containerd as the CRI? I heard Docker Engine isn't supported anymore so I haven't install Docker in any way yet. All the fixes that I've seen involve Docker, but do I need it?

Now, I was using Ubuntu 18.04.6 LTS earlier, and I had no issue with the Kubelet Service with my master node. However with my worker nodes, Kubelet would not start and so I could not join the cluster. I thought maybe the LTS was the problem, so I upgraded all my servers to use 20.04.5 LTS. And now, the master node is having the same problem with Kubelet service not starting.

Versions:

- Ubuntu 20.04.5
- containerd: 1.5.9-0ubuntu1~20.04.6
- kubectl v1.26.0
- kubeadm v1.26.0
- kubelet v1.26.0

/sig network

**Comment by yjianzhu** [comment]
same error. If you solved this issue, I'd be grateful for your response.
