### ISSUE TITLE
【cronjob】Add a new condition when a cronjob controller encounters an invalid time zone.

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/kubernetes#114474]
https://github.com/kubernetes/enhancements/pull/3449

**Comment by sftim** [comment]
BTW, the KEP change hasn't landed yet.

**Comment by sftim** [comment]
The timezone database can change between the *create* and the actual evaluation of the schedule.

**Comment by sftim** [comment]
I don't feel I can answer that detail. Watch out for:
> the timezone database can change between the create and the actual evaluation of the schedule.

I also don't think I have a list of _all_ the things to watch out for.
