### ISSUE TITLE
[scheduler] Enable plugins to return Unschedulable in PreFilter

### ISSUE THREAD

**Issue by chrishenzie** [kubernetes/kubernetes#114433]
### What would you like to be added?

See this thread for more context:
https://github.com/kubernetes/kubernetes/pull/114051/files#r1045971319

It looks like when a scheduler plugin returns an `Unschedulable` status during the `PreFilter` phase, then other `PreFilter` plugins are skipped which results in errors reading cycle state for `AddPod` and `RemovePod`.

Potentially related logic (needs more investigation):
https://github.com/kubernetes/kubernetes/blob/v1.26.0/pkg/scheduler/framework/runtime/framework.go#L602-L603

Discussed with @alculquicondor , we may want to only skip the scheduler cycle if the `PreFilter` plugin returns `UnschedulableAndUnresolvable`.

### Why is this needed?

This enables scheduler plugins to fail faster if they identify an `Unschedulable` status prior to the `Filter` phase.

**Comment by kerthcet** [comment]
@chrishenzie If you don't mind, I'll take this for I'm working on another PR about  [scheduler: distinguish between Unschedulable and UnschedulableAndUnresolvable from PostFilter](https://github.com/kubernetes/kubernetes/issues/113854), they're somehow related.

**Comment by alculquicondor** [comment]
/assign @kerthcet 

Thanks!

**Comment by alculquicondor** [comment]
Don't forget to go over all the existing PreFilter plugins and make sure they are returning `Unschedulable` or `UnschedulableAndUnresolvable` appropriately.

**Comment by alculquicondor** [comment]
@x13n do you think you will need to update this logic in cluster-autoscaler or do you run all PreFilter plugins using the framework?

**Comment by alculquicondor** [comment]
yes, it's about how it works internally, but you might observe two different statuses: Unschedulable or UnschedulableAndUnresolvable. I think CA doesn't care about the difference. kube-scheduler does, because the first one triggers the preemption logic.

**Comment by x13n** [comment]
Right, for CA the status is mostly opaque, we just invoke `IsSuccess` on it, so `UnschedulableAndUnresolvable` handling will be identical to `Unschedulable`. Thanks for reaching out to check though!

**Comment by alculquicondor** [comment]
/remove-lifecycle stale
@kerthcet was there a conclusion about this?
