### ISSUE TITLE
Unusual official annotation: `api-approved.kubernetes.io`

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#114499]
:information_source: This issue tracks https://github.com/kubernetes/website/issues/30764 for visibility.
Please make updates to that issue instead of this one.

(if the story here changes, we / I can update this issue description)

**Comment by liggitt** [comment]
commented at https://github.com/kubernetes/website/issues/30764#issuecomment-1375883763

**Comment by sftim** [comment]
/remove-triage accepted
/close not-planned

Nothing to fix. Also see https://github.com/kubernetes/website/issues/30764#issuecomment-1446754574
