### ISSUE TITLE
NodePort service for hostNetwork pod fails when both Ready and Terminating pods are present

### ISSUE THREAD

**Issue by jason-i-vv** [kubernetes/kubernetes#114440]
### What happened?

We had a nodePort service which use port 30002, transport to a host-network pod which listen 8002.Now it is invalid , we can't access `nodeIp:30002` , but `nodeIp:8002` is valid.

> why we use nodePort when we already use host-network?
Because it could has multiple replicas, we use nodePort to ensure it's avaliable when one pod is down.

1. we check ipvs rules,it's like :
```
ipvsadm -L -n 
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  172.17.0.1:30002 rr
TCP  172.17.0.1:30009 rr
  -> 10.16.203.62:8002
```

We all see , `30002` doesn't have any target.

2. we check endpont status ,it's like:

![1670324387](https://user-images.githubusercontent.com/10915774/207255935-e73d8930-fb85-4e14-82b6-cf28ff45191e.png)

We all see , the same ipaddr is both in Addresses and NotReadyAddress.

And , there are some invalid pods and one valid pod , this is why the endpoint looks like.

### What did you expect to happen?

if an ipaddr is both in readyAddrs and notReadyAddrs, it shouled be removed  from notReadyAddrs to make sure that
valid IP addresses are not masked by invalid IP addresses。Then the url `http://nodeIP:30002` we called will always be accessible  whenever the deployment has invalid pods or not.

### How can we reproduce it (as minimally and precisely as possible)?

1. apply a pod which use host-network , and bind to a fixed node; the pod shouled not has request and limit value ,ensure is is `BestEffort` , so it will be evicited first.
2. apply a service which use nodePort 30002, and bind to the pod
3. manual  make a Diskpressure which is easily caused by dd a big file.
4. the pod will be evicited ,
5. move the Diskpressure ,And the pod will be created 
6. Then you will reproduce it , the endpoint will has the nodeIp both in readyAddrs and notReadyAddrs.

### Kubernetes version

<details>

```console
$ kubectl version
# v1.22.4
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Kylin Linux Advanced Server"
VERSION="V10 (Tercel)"
ID="kylin"
VERSION_ID="V10"
PRETTY_NAME="Kylin Linux Advanced Server V10 (Tercel)"
ANSI_COLOR="0;31"
$ uname -a
Linux i-24AFE987 4.19.90-21.2.ky10.aarch64 #1 SMP Tue Oct 27 16:46:15 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd -v
containerd github.com/containerd/containerd v1.6.2 de8046a5501db9e0e478e1c10cbcfb21af4c6b2d
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by danwinship** [comment]
The commit message should talk about the bug that you're fixing (something something same IP is considered both ready and not ready), not the downstream manifestation of that bug (NodePort / ipvs).

But I'm not quite sure if this fix is correct... I'll follow up on the issue

**Comment by robscott** [comment]
I'm not sure I'm completely understanding this, but it sounds like we may need to update the kube-proxy code that handles the case where more than one endpoint exists for the same IP:

https://github.com/kubernetes/kubernetes/blob/53906cbe89773cc7be1aec0b08703c04a15dc209/pkg/proxy/endpointslicecache.go#L312-L317

**Comment by aojea** [comment]
> ### How can we reproduce it (as minimally and precisely as possible)?
> 1. apply a pod which use host-network , and bind to a fixed node; the pod shouled not has request and limit value ,ensure is is `BestEffort` , so it will be evicited first.
> 2. apply a service which use nodePort 30002, and bind to the pod
> 3. manual  make a Diskpressure which is easily caused by dd a big file.
> 4. the pod will be evicited ,
> 5. move the Diskpressure ,And the pod will be created
> 6. Then you will reproduce it , the endpoint will has the nodeIp both in readyAddrs and notReadyAddrs.

a reproducer will be very useful, it seems an issue with the endpoints controller, no?

there is an e2e that forces a disruption that can server as a basis of the reproducer

https://github.com/kubernetes/kubernetes/blob/9edd4d86c8badea712b44013c156ad57778268eb/test/e2e/network/service.go#L2387-L2394

**Comment by jason-i-vv** [comment]
as I know, kube-proxy check endpointslice condition, So this issue can be solved by update endpoint controller or endpointslice controller.

Finally, this two ways will both update endpointslice condition to Ready , when both Ready and Terminating pods are present.

My first way is to update endpoint controller in my pr , Do you suggest some other ways?

```
Name:         bingokube-console-thdj9
Namespace:    kube-system
Labels:       app.kubernetes.io/managed-by=Helm
              endpointslice.kubernetes.io/managed-by=endpointslice-controller.k8s.io
              kubernetes.io/cluster-service=true
              kubernetes.io/service-name=bingokube-console
              name=bingokube-console
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2022-12-16T02:02:20Z
AddressType:  IPv4
Ports:
  Name               Port  Protocol
  ----               ----  --------
  bingokube-console  8002  TCP
Endpoints:
  - Addresses:  10.202.40.245
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/bingokube-console-56f4684f76-6dmdq
    NodeName:   i-24afe987
    Zone:       <unset>
Events:         <none>
```

**Comment by jason-i-vv** [comment]
```
#TestPackSubsets
{
			name: "two sets, two mixed ips, two dup ip with uid, dup port, wrong order, ends up with split addresses",
			given: []v1.EndpointSubset{{
				Addresses: []v1.EndpointAddress{{IP: "5.6.7.8"}},
				Ports:     []v1.EndpointPort{{Port: 111}},
			}, {
				NotReadyAddresses: []v1.EndpointAddress{{IP: "5.6.7.8", TargetRef: podRef("uid-1")}},
				Ports:             []v1.EndpointPort{{Port: 111}},
			}, {
				NotReadyAddresses: []v1.EndpointAddress{{IP: "1.2.3.4", TargetRef: podRef("uid-1")}},
				Ports:             []v1.EndpointPort{{Port: 111}},
			}, {
				NotReadyAddresses: []v1.EndpointAddress{{IP: "1.2.3.4"}},
				Ports:             []v1.EndpointPort{{Port: 111}},
			}},
			expect: []v1.EndpointSubset{{
				Addresses: []v1.EndpointAddress{
					{IP: "5.6.7.8"},
				},
				NotReadyAddresses: []v1.EndpointAddress{
					{IP: "1.2.3.4"},
					{IP: "1.2.3.4", TargetRef: podRef("uid-1")},
					{IP: "5.6.7.8", TargetRef: podRef("uid-1")},
				},
				Ports: []v1.EndpointPort{{Port: 111}},
			}},
		}
```
this test has been writed to expect the dup ip both in ready or not ready, I am not sure is my idea correct with remove the dup ip from not Ready ips set.
@danwinship

**Comment by aojea** [comment]
> * apply a pod which use host-network , and bind to a fixed node; the pod shouled not has request and limit value ,ensure is is `BestEffort` , so it will be evicited first.
> * apply a service which use nodePort 30002, and bind to the pod
> * manual  make a Diskpressure which is easily caused by dd a big file.
> * the pod will be evicited ,
> * move the Diskpressure ,And the pod will be created
> * Then you will reproduce it , the endpoint will has the nodeIp both in readyAddrs and notReadyAddrs.

which version are you using?

I think that the problem here is that the endpoint is retaining the PodIP of the evicted pod and that is wrong.

This was fixed by https://github.com/kubernetes/kubernetes/pull/110255 , please check that you are running in a version with that patch included , it seems you are running in 1.22.4 and this was fixed in  v1.22.10

**Comment by jason-i-vv** [comment]
Got it ,I will check it.

**Comment by jason-i-vv** [comment]
still check for release-1.22.

**Comment by jason-i-vv** [comment]
@thockin  i had checked the stabe version release-1.22, and this problem was indeed solved。Sorry for take so lang.

**Comment by thockin** [comment]
Thanks for following up!
