### ISSUE TITLE
Device plugin allocatable resource overwritten when kubelet restart

### ISSUE THREAD

**Issue by JackTroy** [kubernetes/kubernetes#114422]
### What happened?

Device plugin allocatable resource is set to capacity temporarily instead of actual value from device plugin when kubelet restart.

This is because when kubelet restarts, device plugin manager `func (m *ManagerImpl) GetCapacity` [link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L280) used by node status update may get run *before*   `func (m *ManagerImpl) Start`[link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L375).
`func GetCapacity` will return empty result when ManagerImpl is not started, causing device plugin allocatable resource set to capacity of last node status just like other resource [link](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodestatus/setters.go#L354).

There is no guarantee that `updateRuntimeUp` which calls `Start` runs before `syncNodeStatus` which calls `GetCapacity`. These functions are executed in goroutines asynchronously in `func (kl *Kubelet) Run`. In our case, `updateRuntimeUp` is always the slower one leading to false allocatable resource every time.

After device plugin ManagerImpl is started, allocatable resource is set correctly.

### What did you expect to happen?

Device plugin allocatable resource should always be set correctly when kubelet restart.

### How can we reproduce it (as minimally and precisely as possible)?

1. watch node source
kubectl get node -ocustom-columns=Name:.metadata.name,capc:.status.capacity."com/resource",alloc:.status.allocatable."com/alloc" -w

2. restart kubelet meawhile
3. watch output, alloc set to cap

<img width="223" alt="pic" src="https://user-images.githubusercontent.com/16226846/207001057-974c77be-52e8-4465-b3e8-9f8818bd75f2.png">

### Kubernetes version

v1.20.6, related code remains unchanged up to master

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@klueska can you comment if this is a known issue?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

moving to needs information for now to understand if this is a known issue or something new

**Comment by klueska** [comment]
It’s not a known issue (meaning no one has reported this issue before as far as I’m aware). If what is described is accurate we should fix it though.

**Comment by payall4u** [comment]
ping @klueska @SergeyKanzhelev

We also had this problem on kubelet 1.22.4

The special resources of the node are divided into two types, managed by the device plugin and manually managed. 

In case of manual management, we should patch `node.status.capacity` and kubelet will update `node.status. allocatable` as https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#other-resources. This will conflict with the resources managed by the device plugin.

When we restart kubelet, it'll try to update node status, resource included. It works like:

``` go
func MachineInfo(...) ... {
    var devicePluginAllocatable v1.ResourceList
    var devicePluginCapacity v1.ResourceList
    var removedDevicePlugins []string

    // handle initial capacity...
    // ...
    devicePluginCapacity, devicePluginAllocatable, removedDevicePlugins = devicePluginResourceCapacityFunc()
    // [Point A] 
    for _, removedResource := range removedDevicePlugins {
        node.Status.Capacity[v1.ResourceName(removedResource)] = *resource.NewQuantity(int64(0), resource.DecimalSI)
    }
    // [Point B] Handle reservation and handle resource managed manually also.
    allocatableReservation := nodeAllocatableReservationFunc()
    for k, v := range node.Status.Capacity {
	    node.Status.Allocatable[k] = v.DeepCopy().Sub(allocatableReservation[k])
    }
    
    for k, v := range devicePluginAllocatable {
	    node.Status.Allocatable[k] = v
    }
}


```

In order to make the problem clear, I had to extract the code.

**Comment by payall4u** [comment]
I have some ideas for the fix.
It is difficult to distinguish the two resources before the device plugin registered. We also cannot assume the registration time of the device plugin.
So can we add graceful shutdown to kubelet, and set the resources managed by the device plugin to 0 when kubelet shutting down? Can I mention a pr as a clarification?

**Comment by JackTroy** [comment]
@SergeyKanzhelev @swatisehgal any update on this bug？

**Comment by JackTroy** [comment]
ping @klueska 
Is there any schedule on fixing it? It would be so appreciated if this can be considerd. Our program relies on accurate allocatable resource over kubelet restart. Now we still suffer from this overwritten bug.
