### ISSUE TITLE
[sig-network] EndpointSliceMirroring E2E test case fails on Windows with Flannel

### ISSUE THREAD

**Issue by ionutbalutoiu** [kubernetes/kubernetes#114421]
### Which jobs are failing?

https://testgrid.k8s.io/sig-windows-networking#ltsc2019-containerd-flannel-sdnbridge-master
https://testgrid.k8s.io/sig-windows-networking#ltsc2019-containerd-flannel-sdnoverlay-master

### Which tests are failing?

```
e2e suite.[It] [sig-network] EndpointSliceMirroring should mirror a custom Endpoint with multiple subsets and same IP address
```

### Since when has it been failing?

The new E2E fails since it was merged into `master` branch via PR https://github.com/kubernetes/kubernetes/pull/114155.

### Testgrid links

https://prow.k8s.io/view/gs/k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnbridge-master/1602090999411118080
https://prow.k8s.io/view/gs/k8s-ovn/logs/k8s-e2e-ltsc2019-containerd-flannel-sdnoverlay-master/1602000401874292736

### Relevant SIG(s)

/sig network
/sig windows

**Comment by aojea** [comment]
Yeah, it is possible that some kube-proxy or alternative implementations have this bug, we saw that in cilium 1.11,  the test covers from regressions

https://github.com/cilium/cilium/issues/22446

I'm not familiar with windows jobs, but it is most likely the components there don't handle endpointslices correctly

**Comment by ionutbalutoiu** [comment]
> Yeah, it is possible that some kube-proxy or alternative implementations have this bug, we saw that in cilium 1.11, the test covers from regressions
> 
> [cilium/cilium#22446](https://github.com/cilium/cilium/issues/22446)
> 
> I'm not familiar with windows jobs, but it is most likely the components there don't handle endpointslices correctly

The Windows jobs linked use Kubernetes clusters (with latest `master` code) on Azure, and Flannel networking (`L2bridge` mode, and `Overlay` mode).

**Comment by aojea** [comment]
yeah, something there has the same bug I mentioned and is not able to handle those endpointslices

**Comment by aojea** [comment]
/remove-sig network

/close

the test AFAIK is legit, cilium had the same issue in 1.11 and is fixed now https://github.com/cilium/cilium/issues/22446

most probably is a bug on the CNI implementation
