### ISSUE TITLE
Deletion of namespace possible when deleting manifest without finalizers

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kubernetes#114561]
### What happened?

I've had ns.yaml file defined like this:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
```

Running `kubectl delete -f ns.yaml`, triggered deletion of namespace, even though namespace had `finalizers`. Command `kubectl delete ns test-ns` would be blocked, but is it possible to block deletion of namespace even when deleting files without defined finalizers within?

### What did you expect to happen?

I would expect namespace to be in Terminating state, but not triggering all the child objects for deletion.

### How can we reproduce it (as minimally and precisely as possible)?

Create namespace however you want, and some child objects within (STS, deployments). Then compare the differences between deleting the namespace and `kubectl delete -f ns.yaml` if we have no finalizers in that file.

### Kubernetes version

<details>

```console
$ kubectl version
# v1.23.11-gke.300
```

</details>

### Cloud provider

GKE

### Container runtime (CRI) and version (if applicable)

K8s version v1.23.11-gke.300

**Comment by harshanarayana** [comment]
> but is it possible to block deletion of namespace even when deleting files without defined finalizers within?

As you can see from the above output, if the resource in the cluster has a finalizer, it will be honoured even if you perform `kubectl delete -f <file>` and the file doesn't contain a `finalizer` for the resource

**Comment by Aracki** [comment]
Yes, it seems `finalizers` doesn't work like I expected. Will need to look for another way to protect namespace for deletion. Thanks 👍
