### ISSUE TITLE
tls: server chose an unconfigured cipher suite

### ISSUE THREAD

**Issue by ryanlyy** [kubernetes/kubernetes#114529]
### What happened?

Hi All,

I am installing kubernetes 1.26 with calico v3.24.5. kubernetes and calico can be installed successfully but kubernetes DNS and calico controller failed to be created the error is:

  Warning  FailedCreatePodSandBox  6s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_coredns-787d4945fb-kvmsm_kube-system_b21eddb2-d4e6-4049-9d9e-c4774d23fc3e_0(54a342475b83c356e71c0ebdf228d8a3b9e5c6839b0bd23e89dad598eade5d45): error adding pod kube-system_coredns-787d4945fb-kvmsm to CNI network "k8s-pod-network": plugin type="calico" failed (add): error getting ClusterInformation: Get "https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default": tls: server chose an unconfigured cipher suite

what is wrong with it?

Thanks for your support

### What did you expect to happen?

kubernetes and calico works well

### How can we reproduce it (as minimally and precisely as possible)?

install kubernetes and calico according to documents

### Kubernetes version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
root@tstbed-1:~# 

### Cloud provider

kubernetes

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

CRIO

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ryanlyy** [comment]
sig/security sig/network

**Comment by pacoxu** [comment]
> Get "[https://10.96.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default](https://10.96.0.1/apis/crd.projectcalico.org/v1/clusterinformations/default)": tls: server chose an unconfigured cipher suite

This error message seems to be a calico error message(not a kubernetes error message).
/kind support

**Comment by ryanlyy** [comment]
Hi @pacoxu thanks for your support. Here is information from Calico:
"
Sounds like the Calico CNI plugin is failing to establish a connection with the Kubernetes API server due to a cipher suite negotiation failure.

This may be related to the generation of your Kubernetes API server certificate, if it's using a non-FIPS-compatible cipher suite.
"
what can we do on this error for k8s API server certificate?

Thanks a lot for your support

**Comment by pacoxu** [comment]
`--tls-cipher-suites` is configurable in https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/.

**Comment by neolit123** [comment]
/close

please reopen if there is a k8s bug or a feature  request.
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
