### ISSUE TITLE
More control over kube-scheduler log level at runtime via HTTP

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#114507]
Other components allowed to change log level at runtime.

https://groups.google.com/a/kubernetes.io/g/dev/c/-AR7YKViP6Y/m/GVKiProsAwAJ?utm_medium=email&utm_source=footer

Supporting this in scheduler is useful for debugging live issues without scheduling restarts. We should follow the same pattern and allow to change the log level via an http endpoint

_Originally posted by @alculquicondor in https://github.com/kubernetes/kubernetes/issues/91633#issuecomment-1344418383_

EDIT: this is already supported in scheduler, but it would be nice to add:
- filtering a pod name
- adding a timeout for the increased log level.

**Comment by Huang-Wei** [comment]
In addition to a global option to tweak log level, I'm thinking if it's possible to provide a pod-selector option to only target particular Pods when changing the log level. (with the not-yet-merged contextual logging PR, maybe it's possible)

It's b/c some online issue is specifically related to a Pod, like why a Pod is scheduled on this node, or unscheduled. What I want is to increase the log level to this Pod _only_, otherwise changing log level to v6 globally would impose non-trivial cpu/memory overhead on scheduler itself. (btw: changing to v10 globally is basically infeasible as it generated a ton of logs)

**Comment by Huang-Wei** [comment]
It's worth mentioning that the log level also controls the _implicit_ logging the scheduler depends on, e.g., all klog entries when roundtripping to API Server.

**Comment by alculquicondor** [comment]
@pohly do you think we could filter out logs for certain pods?

Maybe it's not too hard if we know the pod name (for cases where a pod is unschedulable and we want to see more details on why). OTOH, maybe we would like to see details about scoring for a group of pods (like from a Deployment), but generally we labels are not values we add to the log, so I'm not sure how we could filter these.

Another thing we probably should have in the endpoint is the possibility to set a timeout, so I can express: I want V(10) logs for the next minute.

**Comment by pohly** [comment]
With contextual logging, the verbosity could be increased per pod. When you start processing a pod, check whether this pod is of interest. Then do:
```
logger := klog.FromContext(ctx)
// Decrease verbosity of future log calls, i.e. make it more likely that they get printed.
logger = logger.V(-5)
ctx = klog.NewContext(ctx, logger)
// Use this ctx and logger for the rest of the call chain.
```

There's one caveat: currently logr doesn't support negative values for `V`. There's no technical reason, it's simply a policy. I think we could relax [that check](https://github.com/go-logr/logr/blob/4da5305ff29a64c62f54ad43ebbfcb5e1b015fb2/logr.go#L310-L312).


/cc @thockin

**Comment by pohly** [comment]
The last time we discussed this, there was a proposal to use annotations on a pod to trigger more detailed logging of it. The concerns with that was that an unprivileged user gets control over logging in a system component.

Changing the entire verbosity is possible for klog text output:
```
fs flag.FlagSet
klog.InitFlags(&fs)
fs.Set("v", 10)
```

We probably want a dedicated API for this in k8s.io/component-base/logs that works for both text and JSON output.

**Comment by alculquicondor** [comment]
See https://groups.google.com/a/kubernetes.io/g/dev/c/-AR7YKViP6Y/m/GVKiProsAwAJ?utm_medium=email&utm_source=footer

**Comment by alculquicondor** [comment]
In particular, this https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/server/config.go#L915

**Comment by chenk008** [comment]
The kube-scheduler has allow to change log level
https://github.com/kubernetes/kubernetes/blob/0fdb14f63a83a830b8a7716da10fae5adcd2d927/cmd/kube-scheduler/app/server.go#L287

**Comment by alculquicondor** [comment]
Oh, I missed it. We should probably have a page for "Debugging Kube Scheduler" in https://kubernetes.io/docs/tasks/administer-cluster/ that includes how to use:
- profiling
- changing log level
- Dumping the cache

Although the first two should probably be shared with a single document for other components.

I'll leave this issue open for the rest of the suggestions in the thread.

**Comment by alculquicondor** [comment]
https://github.com/kubernetes/website/issues/38582
