### ISSUE TITLE
kube-scheduler: failed to create containerd container: failed to create prepare snapshot dir : stat /data/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots: no such file or directory Warning  BackOff kubelet  Back-off restarting failed container

### ISSUE THREAD

**Issue by vyom-soft** [kubernetes/kubernetes#114562]
### What happened?

After reboot of Machines on one node and Absence of snapshots folders

➜  ~ kubectl get po --namespace=kube-system -l component=kube-scheduler

```
NAME                   READY   STATUS             RESTARTS       AGE
kube-scheduler-node1   0/1     CrashLoopBackOff   23 (58m ago)   55m
kube-scheduler-node2   1/1     Running            12 (43h ago)   79d
```

```
Events:
  Type     Reason   Age                 From     Message
  ----     ------   ----                ----     -------
  Normal   Pulled   34m (x7 over 43h)   kubelet  Container image "registry.k8s.io/kube-scheduler:v1.24.6" already present on machine
  Warning  Failed   34m (x6 over 36m)   kubelet  Error: failed to create containerd container: failed to create prepare snapshot dir: failed to create temp dir: stat /data/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots: no such file or directory
  Warning  BackOff  33m (x13 over 36m)  kubelet  Back-off restarting failed container
```

### What did you expect to happen?

Kube-scheduler to start normally 

### How can we reproduce it (as minimally and precisely as possible)?

After reboot of Machines Or Missing files under /data/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots

### Anything else we need to know?
[containerd-3369](https://github.com/containerd/containerd/issues/3369)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.25.0
Kustomize Version: v4.5.7
Server Version: v1.24.6
```

</details>

### Cloud provider

<details>
K8s on Kubespray
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"
$ uname -a
Linux node2 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Mon Jul 18 11:14:02 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Kubespray
</details>

### Container runtime (CRI) and version (if applicable)

<details>
<img width="371" alt="image" src="https://user-images.githubusercontent.com/18686082/208296580-28018139-c654-4c58-b23b-c2256568c549.png">

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
if is a containerd problem why are you opening in kubernetes too? 
is it better to handle the issues in one place only
