### ISSUE TITLE
Improve clarity around PodFitsResource

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#11453]
It's hard to debug without grepping logs, which means it's impossible to debug if you're not a developer. 
Example scenario:

- Create a pod, it stays in running
- You run describe on the pod:   
```
Name:				mysql
Namespace:			default
Image(s):			mysql
Node:				/
Labels:				name=mysql
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	<none>
Containers:
  mysql:
    Image:	mysql
    Limits:
      cpu:		500m
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From		SubobjectPath	Reason			Message
  Fri, 17 Jul 2015 10:30:55 -0700	Fri, 17 Jul 2015 10:31:10 -0700	5	{scheduler }			failedScheduling	Failed for reason PodFitsResources and possibly others
```    
- Ok, what resource? you run describe on the nodes:
```
Conditions:
  Type		Status	LastHeartbeatTime			LastTransitionTime			Reason					Message
  Ready 	True 	Fri, 17 Jul 2015 10:33:23 -0700 	Wed, 15 Jul 2015 14:50:36 -0700 	kubelet is posting ready status 	
Addresses:	10.240.99.207,104.197.63.17
Capacity:
 pods:		40
 cpu:		1
 memory:	3800808Ki
Version:
 Kernel Version:		3.16.0-0.bpo.4-amd64
 OS Image:			Debian GNU/Linux 7 (wheezy)
 Container Runtime Version:	docker://1.6.2
 Kubelet Version:		v1.0.0-137-gc853249bb94799-dirty
 Kube-Proxy Version:		v1.0.0-137-gc853249bb94799-dirty
PodCIDR:			10.245.0.0/24
ExternalID:			9673564045764440168
Pods:				(9 in total)
  Namespace			Name
  default			curlpod
  default			my-nginx-g61eu
  default			my-nginx-ywpwm
  kube-system			elasticsearch-logging-v1-wh1ll
  kube-system			fluentd-elasticsearch-e2e-test-beeps-minion-c9up
  kube-system			kibana-logging-v1-1z9e5
  kube-system			kube-ui-v1-57t5j
  kube-system			monitoring-heapster-v5-56h4x
  kube-system			monitoring-influx-grafana-v1-fknxd
```
* What do I need to kill to get this mysql pod running?

Suggestions:
1. Show what resource failed in the scheduler event
2. Show each pods limits in describe node output

**Comment by HaiyangDING** [comment]
Hi, I would like to work on this. Hope to send a PR sooner.

**Comment by bgrant0607** [comment]
@davidopp

**Comment by Kielan** [comment]
Could we have an open discussion here about what the possible problems with a cluster could be when this error appears? This is the top Google result for the error and could be a could forum for improving the docs.

**Comment by HaiyangDING** [comment]
In the current version of Kubernetes, if a pod fails scheduling due to PodFitsResource (you can see the information by running `kubectl describe pod <pod-name>`), the reason must be one of the following:

1. There is not enough memory on the destination node
2. There is not enough CPU on the destination node
3. The number of pods that already run on the node exceeds the maximum number

Please note that the total memory (or CPU) is not measured by actual usage at that moment, but calculated by adding all the memory (or CPU) limits specified in the template

```
spec:
  containers:
    resources:
      limits:
        cpu:
        memory:
```

To deal with the error, you can kill some pod(s) on the destination node to release the resource.

Currently, it is not straightforward for a user to quickly know either which resource fails in `kubectl describe pod <pod-name>` or how much resources each pod claims in `kubectl describe node <node-name>`.

If the PR implemented, you can explicitly see in `kubectl describe pod <pod-name>` which one of the above reasons causes the failure and run `kubectl describe node <node-name>` is see the resource limits of each pod running on the node. With such information, you can easily decide which pod(s) to kill (suppose it is not crucial) to release the resource so that your unscheduled pod can be successfully scheduled.

I hope it helps,

Regards

**Comment by erictune** [comment]
#11788 fixes this.
See the issue comment here:
https://github.com/kubernetes/kubernetes/pull/11788#issuecomment-125074436
for an example of the new output.
This will go into release v1.1 in a few months.

**Comment by erictune** [comment]
Closing because a fix is in HEAD.

**Comment by erictune** [comment]
Advice for users that see a pod with `Failed for reason PodFitsResources`, prior to v1.1 is:
1. to grab the kubernetes source, per https://github.com/kubernetes/kubernetes/blob/master/docs/devel/development.md
1. `make WHAT=cmd/kubectl`
1. `GOPLATFORM=$(go version | cut -f 4 -d ' ')`
1. `_output/local/bin/$GOPLATFORM/kubectl describe nodes`
1. compare `Allocated resources` for each node with the pod you want to start.

**Comment by erictune** [comment]
Also, there is advice on how to troubleshoot this [here](http://kubernetes.io/v1.0/docs/user-guide/compute-resources.html#my-pods-are-pending-with-event-message-failedscheduling) which does not require building anything.

**Comment by prehensile** [comment]
Until 1.1 is released, and for those of us who don't fancy compiling tools (for instance, if they're provided by Google Cloud), I've written a [Python script](https://gist.github.com/prehensile/841cb7f0bb822ea902cd#file-kube-resources-py) which might be helpful for others. For each node, it adds up total pod resource limits and shows that as a percentage of node capacity.

**Comment by bronger** [comment]
@prehensile Thank you, it was very helpful for me!

**Comment by four43** [comment]
Hey all, having an issue with the scheduler, sounds like the same as this:

Kubernetes v1.0.6 Release

````
$ kubectl describe pod [pod]
Name:				[pod]
Namespace:			default
Image(s):			[our registry]/[namespace]/[image]
Node:				/
Labels:				name=map-api
Status:				Pending
Reason:				
Message:			
IP:				
Replication Controllers:	[name] (2/2 replicas created)
Containers:
  map-api:
    Image:	[our registry]/[namespace]/[image]
    Limits:
      cpu:		0
    State:		Waiting
    Ready:		False
    Restart Count:	0
Events:
  FirstSeen				LastSeen			Count	From		SubobjectPath	Reason			Message
  Tue, 27 Oct 2015 14:27:34 -0500	Tue, 27 Oct 2015 14:37:50 -0500	37	{scheduler }			failedScheduling	Failed for reason PodFitsResources and possibly others
````

The total usage (thanks for the above script, @prehensile!) found no memory and no cpu limits as I had hoped:
````
---
Memory allocated: 650Mi (17.27% of capacity)
CPU allocated: 700m (35.00% of capacity)
---
Memory capacity: 3763Mi
CPU capacity: 2000m
---
````

I specifically set the pod to not have any resource limits but creation still fails. I deployed many other pods that are similar to this (same image and settings) but these last couple got stuck.

**Comment by vially** [comment]
:+1: I'm having the same issue on kubernetes v1.0.6
