### ISSUE TITLE
 uid : exit status 1: 2022/12/15 22:48:30 socat[2186711] E getaddrinfo("localhost", "NULL", {1,2,1,6}, {}): Temporary failure in name resolution

### ISSUE THREAD

**Issue by samrajput1143** [kubernetes/kubernetes#114512]
### What happened?
/sig  Network

Using the command  kubectl port-forward --namespace=ingress-nginx deployment/ingress-nginx-controller 8080:80.

When iam trying make a post request to localhost at **curl -X POST http://0.0.0.0:8080/ric/v1/startsubscription/kpm/**
getting the below error: -

Handling connection for 8080
E1215 22:59:23.356915 2199631 portforward.go:400] an error occurred forwarding 8080 -> 80: error forwarding port 80 to pod 5add6d1b78d4935e087616da48aaf36e00816d36fca6c915f90ec2403a8b03ea, uid : exit status 1: 2022/12/15 22:59:23 socat[2199737] E getaddrinfo("localhost", "NULL", {1,2,1,6}, {}): Temporary failure in name resolution

Below are some details related to ingress service

![image](https://user-images.githubusercontent.com/75875312/207928721-a5db6ace-b7f7-4dba-bb75-8248cd0e8a41.png)

![image](https://user-images.githubusercontent.com/75875312/207929462-5e3e776f-1f41-48b0-8cc9-d63dedb5ab09.png)

![image](https://user-images.githubusercontent.com/75875312/207929002-3102c701-ca6b-4bd3-b401-7d294bddcf53.png)

![image](https://user-images.githubusercontent.com/75875312/207929208-81b0bb77-ee4c-4938-abf4-30af093148ea.png)

### What did you expect to happen?

I was expecting my request should be routed to the desired pod in ricxapp namespace.

But getting the error 
![image](https://user-images.githubusercontent.com/75875312/207929793-64e51508-b284-4f0d-a37e-4064c4392a8c.png)

when using curl command locally to post http request 
![image](https://user-images.githubusercontent.com/75875312/207933153-bb89659b-4375-44fb-b80e-eb74f981478b.png)

### How can we reproduce it (as minimally and precisely as possible)?

use ubuntu 20.04
Deploy one pod that will listen http traffic on port 8081, 8082 and 8083 port in namespace ricxapp.
deploy ingress-controller on k8s version 1.16  [ingress-controller yaml file](https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.49.0/deploy/static/provider/cloud/deploy.yaml)
deploy ingress rule/service in ricxapp namespace using the below yaml file.

![image](https://user-images.githubusercontent.com/75875312/207934182-53b59c0f-6d76-440f-9e4a-04c9a2c684cc.png)

After that forward localhost port 8080 to ingress controller deployment using below command

kubectl port-forward --namespace=ingress-nginx deployment/ingress-nginx-controller 8080:80

Then post empty http request to localhost at  curl -X POST http://127.0.0.1:8080/ric/v1/startsubscription/kpm/

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
![image](https://user-images.githubusercontent.com/75875312/207930183-f59c1bee-2b36-4116-a086-a646af3060a4.png)

</details>

### Cloud provider

<details>
using ubuntu in a virtual machine, provided by my employer.
![image](https://user-images.githubusercontent.com/75875312/207930428-23278c4c-e890-4a97-828e-746b8f14d4a3.png)

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

![image](https://user-images.githubusercontent.com/75875312/207930760-7b6cdd14-4f57-42ad-8306-cacb98bdea3e.png)

# paste output here
$ uname -a
# paste output here
Linux oam 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

![image](https://user-images.githubusercontent.com/75875312/207930866-f093ace2-ceed-46af-852b-c886d06d31b0.png)


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig node network
Similar to https://github.com/kontena/pharos-cluster/issues/448.

**Comment by aojea** [comment]
> on k8s version 1.16

this is a very old version, please update to one supported version and report back

**Comment by thockin** [comment]
I know "please upgrade" is a harsh answer, but this release is about 3 years old.  Can you run kubelet with `--v=5` and look at those logs - there are some log lines that seem relevant to this.

**Comment by samrajput1143** [comment]
will k8s version 1.18 work?
I have limitations, I can't go beyond 1.18.

**Comment by thockin** [comment]
> will k8s version 1.18 work?

If I knew that I wouldn't  be asking questions.  I simply don't know what's going on without more information, but spending time to debug a 3 year old version of k8s is not fun.  If you can run kubelet with `-v 5` we might get a better clue what is happening.

You might also try to remove some variables - first try port-forward to a specific pod which is NOT a proxy.  Then try to a pod which is a proxy.  Then try to the deployment.

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

since we need either a repro on newver version or logs, moving it to needs-information

**Comment by thockin** [comment]
Pinging for updates - @samrajput1143 the ball is in your court

**Comment by jcambronero** [comment]
I know this has been closed for a while but in our case this was happening because the servers were missing this line in **/etc/hosts**:
```
127.0.0.1 localhost
```
We added the line and restarted kubelet and now kubectl port-forward is working fine.

**Comment by SmartGuyy** [comment]
@jcambronero thank you, you just saved me few hours of troubleshooting why i was getting issues with Istio port-forwarding since some time, looks like my /etc/hosts was overridden at some point when recreated... :pray:
