### ISSUE TITLE
Prometheus cannot access/scrape kube-* services on master nodes

### ISSUE THREAD

**Issue by jgagnon44** [kubernetes/kubernetes#114543]
### What happened?

I am setting up Kubernetes cluster monitoring with Prometheus. I am using the kube-prometheus-stack Helm chart available at https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack. I find that it cannot access many of the `kube-*` services running in the `kube-system` namespace. It finds the targets, but cannot access them. There is an error like:

> Get "https://172.20.8.68:10257/metrics": dial tcp 172.20.8.68:10257: connect: connection refused

The services that it cannot connect to are `kube-controller-manager`, `kube-proxy`, `kube-scheduler` and `kube-etcd`. Most of these services are running on the master node, with the exception of `kube-proxy` which runs on all nodes.

I was able to successfully connect Prometheus to `kube-controller-manager` and `kube-scheduler` by directly modifying the Pod configurations on the master node.

Example:

SSH into master node.
Edit `/etc/kubernetes/manifests/kube-controller-manager.yaml`.
Locate `spec.containers[0].command` block.
Change address for `--bind-address` from `127.0.0.1` to `0.0.0.0`.
Save file. Pod will be recreated automatically.

For `kube-proxy` I edited the `kube-proxy` ConfigMap (with Lens) in the `kube-system` namespace.

Example:

Edit ConfigMap `kube-proxy` in the `kube-system` namepscae (via Lens or kubectl edit).
For the `config.conf` key, change `metricsBindAddress` from `""` to `"0.0.0.0"`.
Save changes.
Delete `kube-proxy` pods. Pods will be recreated automatically.

Neither of these techniques is recommended and certainly does not follow GitOps.

After some more research, I found an issue (https://github.com/kubermatic/kubeone/issues/1215) that seems to be addressing the same problem. One of the comments ([comment](https://github.com/kubermatic/kubeone/issues/1215#issuecomment-992471229)) laid out the use of a proxy to access these services. Interestingly, it works, but _only_ for services that are not running on the master node - e.g. the `kube-proxy` instances running on worker nodes. BTW, I restored back to original, the configuration changes mentioned in the prior paragraph before trying this.

There is something about the master nodes that is preventing access to these services. Is/are there ways to solve these access issues? Is it something that can be done to an existing cluster, or does this require that the cluster be re-built?

### What did you expect to happen?

Prometheus to be able to access and scrape metrics from the `kube-controller-manager`, `kube-proxy`, `kube-scheduler` and `kube-etcd` services, regardless of which node they are running on.

### How can we reproduce it (as minimally and precisely as possible)?

Create a basic multi-node Kubernetes cluster. I do not know whether cloud services would (or wouldn't) have any effect - I have not used any. Mine is set up as a bare metal cluster with 4 nodes - 1 master, on premises. Kubeadm was used to set it up.

Install the latest kube-prometheus-stack Helm chart. Here is info from the Chart.yaml I am using:
```
version: 43.1.1
appVersion: 0.61.1
kubeVersion: ">=1.16.0-0"
```

```
$ helm install prom-stack prometheus-community/kube-prometheus-stack -n monitoring --create-namespace
```

Once Prometheus is deployed and running, find the prometheus pod (in the `monitoring` namespace) and port forward to access it from a browser. The pod should have 2 containers running: `init-config-reloader` and `prometheus`. Port forward for the `prometheus` container.

On the Prometheus page, select `Status` -> `Targets`. This will display all of the identified targets and their status.

![image](https://user-images.githubusercontent.com/56738211/208136157-ab748672-827b-44a9-a419-3ef0f443c863.png)

### Kubernetes version

<details>

```
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None. It is a bare metal cluster is on premises.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux gagnon-m1 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Project Calico
</details>

**Comment by neolit123** [comment]
> Kubeadm was used to set it up.

kubeadm intentionally binds some components to localhost. this is an old topic and it is unlikely we are going to change the behavior. also, yes using a proxy is considered an ok solution.

if you'd like to create a cluster you can pass a --bind-address with 0.0.0.0 in extraArgs. see here for more info
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags/#customizing-the-control-plane-with-flags-in-clusterconfiguration

but please keep note of who can access the served data.

/close
/kind support

**Comment by jgagnon44** [comment]
@neolit123 So the proxy technique works, but not for anything on the master node. Is this because of the "localhost" behavior you mentioned? If so, what do you suggest I do to "properly" change the configuration of these services (on master) in order for Prometheus to be able to access them?

Your other suggestions appear to apply to when setting up a new cluster. I am needing to do this to an existing cluster.

**Comment by jgagnon44** [comment]
I do not consider this issue as closed. How do I re-open it?

**Comment by mohammed6688** [comment]
in my case, i found that kube-controller-manager and kube-schedular were listening on different ports other that one configured on Prometheus, so I changed the ports in Prometheus, refer to this [comment](https://github.com/prometheus-operator/kube-prometheus/issues/1517#issuecomment-1419902931)

**Comment by gireassen** [comment]
How to set up metrics collection with Kubelet, which runs as a Linux service?

```
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/0 (0/6 up)
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/1 (0/6 up)
serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/2 (0/6 up)
```

**Comment by gireassen** [comment]
> How to set up metrics collection with Kubelet, which runs as a Linux service?
> 
> ```
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/0 (0/6 up)
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/1 (0/6 up)
> serviceMonitor/monitoring/prometheus-kube-prometheus-kubelet/2 (0/6 up)
> ```

found a solution [here](https://www.henryxieblogs.com/2018/11/how-to-fix-server-returned-http-status.html)
