### ISSUE TITLE
Failed to create additional ephemeral containers

### ISSUE THREAD

**Issue by minh-chau** [kubernetes/kubernetes#114593]
### What happened?

I have a test pod, which has a piece of golang code to create ephemeral containers. It works fine to create the first ephe container, then I stop this ephe container. However, it is failed to create the second ephe container under the same code flow.

Containers:
  testpod:
    Container ID:   containerd://326316f17ef0a0bb95c922d848dc9d8f8e3820f84d5266f3e0b8bb6bebe455b0
    Image:          testpod:latest
    Image ID:       docker.io/library/import-2022-12-16@sha256:0f09c53a30660a362d442cfc0f95af99fef9a8ff2e128c16a7b72da665cd2618
    Port:           9999/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Mon, 19 Dec 2022 12:15:34 +1100
    Last State:     Terminated
      Reason:       Unknown
      Exit Code:    255
      Started:      Fri, 16 Dec 2022 13:30:37 +1100
      Finished:     Mon, 19 Dec 2022 12:15:07 +1100
    Ready:          True
    Restart Count:  1
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gc9dd (ro)
Ephemeral Containers:
  testpod-844985c5d-h9955-pcapagent-1671491861:
    Container ID:   containerd://12a274068a2ed7f4ab7818a2d9dd2e670258ebdfa35521ce629dce07a73530b9
    Image:          pcapagent:latest
    Image ID:       docker.io/library/import-2022-12-16@sha256:77dc1a084aae1df8251264619975a4ed623af1c639bb806781810b8aa98ee2f6
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 20 Dec 2022 10:17:42 +1100
      Finished:     Tue, 20 Dec 2022 10:17:56 +1100
    Ready:          False
    Restart Count:  0

testpod-844985c5d-h9955-pcapagent-1671491861 is the first container, it is terminated as you can see.
The second ephe container names as testpod-844985c5d-h9955-pcapagent-1671491882, and I got the error as below:

2022/12/19 23:18:02 Creating ephemeral container testpod-844985c5d-h9955-pcapagent-1671491882
2022/12/19 23:18:02 Pod "testpod-844985c5d-h9955" is invalid: spec.ephemeralContainers: **Forbidden: existing ephemeral containers "testpod-844985c5d-h9955-pcapagent-1671491861" may not be removed**

On the other hand, if I use "kubectl debug" there's no issue in creating additional ephe containers (naming prefix as debugger-xxx)

Ephemeral Containers:
  testpod-844985c5d-h9955-pcapagent-1671491861:
    Container ID:   containerd://12a274068a2ed7f4ab7818a2d9dd2e670258ebdfa35521ce629dce07a73530b9
    Image:          pcapagent:latest
    Image ID:       docker.io/library/import-2022-12-16@sha256:77dc1a084aae1df8251264619975a4ed623af1c639bb806781810b8aa98ee2f6
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 20 Dec 2022 10:17:42 +1100
      Finished:     Tue, 20 Dec 2022 10:17:56 +1100
    Ready:          False
    Restart Count:  0
    Environment:
      PCAPMAIN_IP:     10.244.1.3
      PCAPAGENT_NAME:  testpod-844985c5d-h9955-pcapagent-1671491861
    Mounts:            <none>
  debugger-zx8px:
    Container ID:   containerd://d4f53e0b135383071d2b547591f4d633b06c9327ec77a1757930f6bedd4a8d72
    Image:          pcapagent:latest
    Image ID:       docker.io/library/import-2022-12-16@sha256:77dc1a084aae1df8251264619975a4ed623af1c639bb806781810b8aa98ee2f6
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 20 Dec 2022 10:48:14 +1100
      Finished:     Tue, 20 Dec 2022 10:48:14 +1100
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>
  debugger-7n28k:
    Container ID:   containerd://70bd43d336ae2ab098e849bfa8db09680376651f9f635e78559bdcbc0148401a
    Image:          pcapagent:latest
    Image ID:       docker.io/library/import-2022-12-16@sha256:77dc1a084aae1df8251264619975a4ed623af1c639bb806781810b8aa98ee2f6
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Tue, 20 Dec 2022 10:48:32 +1100
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:         <none>

### What did you expect to happen?

I wonder if something wrong in my code snippet, but I feel it could be a bug in Kubernetes, since it is ok to create the first ephe container within the golang code. This one is stopped before creating another one with different name. There's no issue with 'kubectl debug'

### How can we reproduce it (as minimally and precisely as possible)?

Below is code snippet to create ephe container:
	ephemeralContainerName := fmt.Sprintf("%s-pcapagent-%v", podName, time.Now().Unix())
	log.Printf("Creating ephemeral container %s", ephemeralContainerName)
	// create pod manifest
	pod := &corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Name: podName,
		},

		Spec: corev1.PodSpec{
			EphemeralContainers: []corev1.EphemeralContainer{
				{
					TargetContainerName: targetContainer,
					EphemeralContainerCommon: corev1.EphemeralContainerCommon {
						Image: "pcapagent:latest",
						Name: ephemeralContainerName,
						ImagePullPolicy: "IfNotPresent",
						Env: []corev1.EnvVar {
							{
								Name: "PCAPMAIN_IP",
								Value: podIp,
							},
							{
								Name: "PCAPAGENT_NAME",
								Value: ephemeralContainerName,								
							},
						},
					},
				},
			},
		},
	}
	_, err := client.CoreV1().Pods(nameSpace).UpdateEphemeralContainers(context.TODO(), podName, pod, metav1.UpdateOptions{})
	

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compile
r:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compi
ler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support
/sig node

> 2022/12/19 23:18:02 Pod "testpod-844985c5d-h9955" is invalid: spec.ephemeralContainers: Forbidden: existing ephemeral containers "testpod-844985c5d-h9955-pcapagent-1671491861" may not be removed

As the error message shows, you should add new ephemeralContainers along with old ones. ephemeralContainers can not be removed. See https://github.com/kubernetes/kubernetes/issues/84764.

**Comment by minh-chau** [comment]
Hi @pacoxu,

I didn't attempt to remove the old ones, the problem happens when  I try to add a new one along with the old ones. You can see the new one named as testpod-844985c5d-h9955-pcapagent-**1671491882**, the old one was testpod-844985c5d-h9955-pcapagent-**1671491861**. Those ephemeral containers naming comes with a timestamp so I believe they all are different.

Thanks

**Comment by harshanarayana** [comment]
@minh-chau  I think the issue is because how you are applying the update to the pod. In your example, you are creating a new list of things under `ephemeral container` and using that to update. Which is equivalent to asking for delete. 

```go
func attachEphemeralContainers(client clientset.Interface,  namespace string, podName string, targetContainer string, podIp string) error {	
	pod, err := client.CoreV1().Pods(namespace).Get(context.Background(), podName, metav1.GetOptions{})
	if err != nil {
		return err
	}
	ephemeralContainerName := fmt.Sprintf("%s-pcapagent-%v", podName, time.Now().Unix())
	kog.InfoS("Creating ephemeral container", "name", ephemeralContainerName)
	if pod.Spec.EphemeralContainers == nil {
		pod.Spec.EphemeralContainers = make([]v1.EphemeralContainer, 0)
	}
	pod.Spec.EphemeralContainers = append(pod.Spec.EphemeralContainers, v1.EphemeralContainer{
		TargetContainerName: targetContainer,
		EphemeralContainerCommon: v1.EphemeralContainerCommon{
			Image:           "pcapagent:latest",
			Name:            ephemeralContainerName,
			ImagePullPolicy: "IfNotPresent",
			Env: []v1.EnvVar{
				{
					Name:  "PCAPMAIN_IP",
					Value: podIp,
				},
				{
					Name:  "PCAPAGENT_NAME",
					Value: ephemeralContainerName,
				},
			},
		},
	})
	_, err = client.CoreV1().Pods(namespace).UpdateEphemeralContainers(context.Background(), podName, pod, metav1.UpdateOptions{})
	return err
}
```
Mind giving a try for something like above and see if that fixes your issue ?

**Comment by minh-chau** [comment]
Thank you @harshanarayana, what I did was likely an overwrite, your suggestion works for me.
