### ISSUE TITLE
NodeIPAM CloudAllocator Type on KCM panics when using external cloud provider

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#114556]
Cloud-providers started to move out of tree its controller, but they share some functionalities, one of them is the NodeIPAM controller.

There is a type that is GCE specific, the `CloudAllocator` type.

If this type is used, but no configuration for GCE is passed, the kcm panics.

This can be observed in the following job: https://testgrid.k8s.io/sig-testing-canaries#ingress-gce-e2e-canary

> I1217 13:13:43.823361       9 flags.go:64] FLAG: --cidr-allocator-type="CloudAllocator"

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x28a2621]

goroutine 205 [running]:
k8s.io/kubernetes/pkg/controller/nodeipam/ipam.NewCloudCIDRAllocator({0x51dd7f0, 0xc000f2c000}, {0x0, 0x0?}, {0x5194a40, 0xc000dffd40})
	pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go:98 +0x5e1
k8s.io/kubernetes/pkg/controller/nodeipam/ipam.New({0x51dd7f0, 0xc000f2c000}, {0x0, 0x0}, {0x5194a40, 0xc000dffd40}, {0x0, 0x0}, {0x7fffae6b9d76, 0xe}, ...)
	pkg/controller/nodeipam/ipam/cidr_allocator.go:138 +0xed
k8s.io/kubernetes/pkg/controller/nodeipam.NewNodeIpamController({0x5194a40, 0xc000dffd40}, {0x0, 0x0}, {0x0?, 0x0}, {0x51dd7f0, 0xc000f2c000}, {0xc000700ea0, 0x1, ...}, ...)
	pkg/controller/nodeipam/node_ipam_controller.go:134 +0x665
k8s.io/kubernetes/cmd/kube-controller-manager/app.startNodeIpamController({_, _}, {{0x51b8a40, 0xc000087e60}, {0x51d33d0, 0xc00016ac40}, {0x5196e30, 0xc000c23120}, {{{0x0, 0x0}, ...}, ...}, ...})
	cmd/kube-controller-manager/app/core.go:152 +0x666
k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers({_, _}, {{0x51b8a40, 0xc000087e60}, {0x51d33d0, 0xc00016ac40}, {0x5196e30, 0xc000c23120}, {{{0x0, 0x0}, ...}, ...}, ...}, ...)
	cmd/kube-controller-manager/app/controllermanager.go:594 +0x4e4
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1({0x51b04b0, 0xc0005d4a80}, 0xc00031a570?, 0x4b71a98)
	cmd/kube-controller-manager/app/controllermanager.go:231 +0x26e
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func3({0x51b04b0?, 0xc0005d4a80?})
	cmd/kube-controller-manager/app/controllermanager.go:291 +0xe3
created by k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run
	vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:211 +0x11b
```

The question is, should this type be removed or a noop in KCM?

**Comment by thockin** [comment]
Is this a case of CCM handling IPAM so KCM needs to *not* handle it?  What I mean is why is this set without a config?  What was the intention?

The fact that this has GCE-cloud-provider baked in is awful and should probably have been inverted (GCE provider calls a "register" method or something), but that's aside

**Comment by aojea** [comment]
> Is this a case of CCM handling IPAM so KCM needs to _not_ handle it? What I mean is why is this set without a config? What was the intention?

Context: 
I started to set up jobs using the CCM by default, the cluster set up uses the `cluster/gce` script.
https://github.com/kubernetes/kubernetes/pull/114557
The script doesn't consider IPAM, so it configures both KCM and CCM, but if set to "external" , it doesn't configure GCE_PROVIDER in KCM 

When `ENABLE_IP_ALIASES == true`, the scripts set `NODE_IPAM_MODE=${KUBE_GCE_NODE_IPAM_MODE:-CloudAllocator`
 ... and CloudAllocator only runs with GCE

https://github.com/kubernetes/kubernetes/blob/0fdb14f63a83a830b8a7716da10fae5adcd2d927/pkg/controller/nodeipam/ipam/cloud_cidr_allocator.go#L88-L100

My concern is that if this happens to me, it is possible that users that have to migrate custom cluster will face the same issue

**Comment by thockin** [comment]
A panic here seems appropriate, right?  They specifically asked for a
config that doesn't work and action needed to be taken.

Am I misunderstanding?

**Comment by andrewsykim** [comment]
A panic is appropriate given we never did any handling of this corner case -- I think it would be reasonable going forward to have a check in place to disable nodeipam controller if the allocator is `CloudAllocator` but the cloud provider is not configured.

**Comment by andrewsykim** [comment]
Opened https://github.com/kubernetes/kubernetes/pull/114596 with the check and a warning when this happens. We can also consider erroring out KCM if we see this happen so it's really clear to users that they misconfigured something
