### ISSUE TITLE
UDP service ClusterIP not working

### ISSUE THREAD

**Issue by marcobarlo** [kubernetes/kubernetes#114538]
### What happened?

Hi everyone;
I set up a ClusterIP service that targets an UDP port 6667, and I created a pod that receives UDP packets on that port. A client within the cluster (not inside of any container) sends UDP packets to port and ip of the service.
Anyway the pod never receives the packets. 
I made a little troubleshooting and I found what follows:
-  If the client sends the packets to the ip of the node, the pod correctly receives packets.
- If the client sends to the IP of the pod, the pod correctly receives the packes.
- The packets are correctly received on the node and tcpdump shows that their IP destination is the IP of the pod, hence the service correctly catches the traffic and redirects it to the (only) endpoint of the service. I noticed that when using the service IP, the destination node receives the packet on eth0 but does not forward to the veth.
The pod is bound to the ip address 0.0.0.0 and to the 6667 port.
EDIT: if the client is running on the same node as the server it works, otherwise it doesn't.
EDIT2: I suppose is something related to flannel, because the flannel interface does not get assigned the ip on all the nodes

### What did you expect to happen?

I expected the pod to receive the packets as planned.

### How can we reproduce it (as minimally and precisely as possible)?

Create an UDP service on a port.
Create a Pod listening on that port for UDP packets.
Create a client that sends packets to the IP of the service.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux manjaroB 5.10.154-1-MANJARO #1 SMP PREEMPT Thu Nov 10 20:51:28 UTC 2022 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.9 1c90a442489720eec95342e1789ee8a5e1b9536f.m
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel
</details>

**Comment by aojea** [comment]
should you better report it in flannel?

**Comment by pacoxu** [comment]
/kind support

If the pod IP that is assigned by the flannel is not reachable on another host, this would be a flannel problem

If the pod IP is accessible and the cluster-ip is not, it may be related to kube-proxy. 

https://kubernetes.io/docs/tasks/debug/debug-application/debug-service/

**Comment by marcobarlo** [comment]
Kinda solved it. I don't know exactly what was broken but, restarting flannel allowed to assign correctly an IP to the flannel interface. This however didn't solve the problem. I had to reboot the cluster cleaning the cni0 interfaces on the nodes. Basically the traffic was reaching correctly the destination node but it was not bridged by cni0 to the right veth. Since the traffic was reaching the host and the destination was set correctly to the pod IP, I assume kube-proxy was working fine. Still not sure anyway.
