### ISSUE TITLE
Services proxy does not work when selector is absent

### ISSUE THREAD

**Issue by jkh52** [kubernetes/kubernetes#114670]
### What happened?

Create a service [without selectors](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors), and manually create an Endpoints with an external IP address.

Access the service proxy, it fails with 503, "no endpoints available for service ...".

### What did you expect to happen?

I would expect proxy to work (parity with pod-endpoint based Services).

### How can we reproduce it (as minimally and precisely as possible)?

```
apiVersion: v1
kind: Service
metadata:
  name: blackhole
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: blackhole
subsets:
- addresses:
  - ip: 198.18.0.254
  ports:
  - name: http
    port: 80
```

Note: 198.18.0.254 is RFC 6890 (reserved for benchmarking). I was using it to test timeout scenarios. With this example, I expect `kubectl` to timeout. Instead, it fails immediately with 503.

`kubectl -v 9 get --raw /api/v1/namespaces/default/services/blackhole/proxy/`

```
...
I1222 23:10:51.765730  525816 helpers.go:246] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"blackhole\"",
  "reason": "ServiceUnavailable",
  "code": 503
}]
Error from server (ServiceUnavailable): no endpoints available for service "blackhole"
```

### Anything else we need to know?

If I comment out the below validation and compile kube-apiserver, it works as I expect:

```
+++ b/pkg/registry/core/service/storage/storage.go
@@ -457,10 +457,10 @@ func (r *REST) ResourceLocation(ctx context.Context, id string) (*url.URL, http.
                                for try := 0; try < len(ss.Addresses); try++ {
                                        addr := ss.Addresses[(addrSeed+try)%len(ss.Addresses)]
                                        // TODO(thockin): do we really need this check?
-                                       if err := isValidAddress(ctx, &addr, r.pods); err != nil {
-                                               utilruntime.HandleError(fmt.Errorf("Address %v isn't valid (%v)", addr, err))
-                                               continue
-                                       }
+                                       // if err := isValidAddress(ctx, &addr, r.pods); err != nil {
+                                       //      utilruntime.HandleError(fmt.Errorf("Address %v isn't valid (%v)", addr, err))
+                                       //      continue
+                                       // }
                                        ip := addr.IP
```

### Kubernetes version

<details>

```console

$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7-gke.900", GitCommit:"e35c4457f66187eff006dda6d2c0fe12144ef2ec", GitTreeState:"clean", BuildDate:"2022-10-26T09:25:34Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
GKE
</details>

**Comment by aojea** [comment]
is ok to be able to use IPs that don't belong to pod so the apiserver can be used as a proxy to external endpoints?

There were several CVEs on that area, @liggitt or @deads2k may remember better than me

**Comment by liggitt** [comment]
> is ok to be able to use IPs that don't belong to pod so the apiserver can be used as a proxy to external endpoints?

No. Limiting the apiserver proxy to IPs set by an actor with pod status permissions is intentional

**Comment by liggitt** [comment]
Xref https://github.com/kubernetes/kubernetes/pull/57265

**Comment by liggitt** [comment]
/remove-kind bug
/kind documentation

this is working as intended, if it is unclear this is as intended, we should improve documentation to make that clear

**Comment by thockin** [comment]
Agree it is WAI - what's the right place to document this?  k/website or is ther an API doc-comment for /proxy/ that feeds into openapi?  I don't see any obvious place to document the limitations of that sub-resource

**Comment by jkh52** [comment]
Looks like https://github.com/kubernetes/website/pull/29752 addressed this but was inadvertently lost near August 2022.

**Comment by thockin** [comment]
https://github.com/kubernetes/website/pull/38617

**Comment by aojea** [comment]
@thockin should we remove this too?

https://github.com/kubernetes/kubernetes/blob/a4deb20a1d82a17e5c2d83108bc4cc6734a01678/pkg/registry/core/service/storage/storage.go#L467

**Comment by thockin** [comment]
Yeah, do you want to do it or shall I?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/pull/114683
