### ISSUE TITLE
Downloads inside pods get bandwidth throttled after 2 minutes

### ISSUE THREAD

**Issue by echel0n-TR** [kubernetes/kubernetes#114690]
### What happened?

Downloading of a 5TB file inside of a pod from a outside source has its download speed throttled after 2 minutes, restarting the download maintains the same throttled speed, restarting the pod resolves it till it gets throttled again after 2 minutes.

This same statefulset has been tested in another cluster and works fine, no throttling, differences are that the cluster without the problem is EKS Anywhere v1.24, the cluster with the issue is running Kubernetes 1.26 and was created with kubeadm.

Also, the cluster is just plain and simple, nothing really to it, any help on this would be greatly appreciated please, thanks!

### What did you expect to happen?

Downloads inside pods to not have their bandwidth throttled.

### How can we reproduce it (as minimally and precisely as possible)?

Spin up any docker image that has aria2 and run the following command below
aria2c -x5 -c https://dl2.quicksync.io/columbus-5-archive.20220830.1141.tar.lz4

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.26) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
on-prem self-hosted
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux k8s-w03 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

**Comment by echel0n-TR** [comment]
ok, so I went back and did further testing, this time I removed the memory limit from the statefulset and tried the download again, this time it works perfectly, prior I had the memory limit set to 32GB and I checked the pods usage and found it was only using 11GB, so this sounds awfully similar to the CPU limit bug that caused CPU throttling awhile back, can someone confirm if this is a bug that is known ?

**Comment by pacoxu** [comment]
> ok, so I went back and did further testing, this time I removed the memory limit from the statefulset and tried the download again, this time it works perfectly

Does the pod get evicted due to memory limit? 
https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#active-file-memory-is-not-considered-as-available-memory https://github.com/kubernetes/kubernetes/issues/43916 There is a known issue of calculating active file for pod memory.

**Comment by echel0n-TR** [comment]
> > ok, so I went back and did further testing, this time I removed the memory limit from the statefulset and tried the download again, this time it works perfectly
> 
> Does the pod get evicted due to memory limit? Kubelet log should show the eviction message if so. https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#active-file-memory-is-not-considered-as-available-memory #43916 There is a known issue of calculating active file for pod memory.

No it does not, thats just the oddest thing about this, I can't see any indication that says this is a memory issue., yet the fix I stated above of removing the limit for memory does indeed resolve the issue.

**Comment by pacoxu** [comment]
It is hard to move forward as you have solved the problem and there is no more evidence to point out the root cause or to prove this is a specific bug of kuberentes.

**Comment by echel0n-TR** [comment]
well, its easy to have the problem come back when I set the memory limit again, increasing the memory limit does allow it seems for additional download time, 32GB allowed me to download 40GB as were 64GB allowed me to download 60GB, something is throttling the pods performance and it clearly seems due to memory, this is similar as to the CPU throttle bug that was introduced into Linux kernel 4.18 and later fixed.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2570-memory-qos
We only introduce a cgroup v2 memory throttling support with feature gate MemoryQoS=true.

**Comment by echel0n-TR** [comment]
thats not something we've enabled on our end, is it possible there is a bug in that code thats causing this issue?

**Comment by pacoxu** [comment]
This is easy to check, you can find the pod dir in /sys/fs/cgroup/kubepods.slice/ and check the memory.max which is the throttling bar. If MemoryQoS is disabled, it should be always `max`. For instance
```
[root@paco-centos-9 kubepods-podb1f1c1be_0691_40d3_a8e7_d646c8f266e3.slice]# cat memory.high
max
[root@paco-centos-9 kubepods-podb1f1c1be_0691_40d3_a8e7_d646c8f266e3.slice]# cat memory.max
209715200
```

**Comment by echel0n-TR** [comment]
```
root@k8s-w03:~# cd /sys/fs/cgroup/kubepods.slice/
root@k8s-w03:/sys/fs/cgroup/kubepods.slice# cat memory.high
max
root@k8s-w03:/sys/fs/cgroup/kubepods.slice# cat memory.max
134871363584
root@k8s-w03:/sys/fs/cgroup/kubepods.slice#
```

**Comment by echel0n-TR** [comment]
I re-enabled the memory limit in our statefulset and this is what I get below after running your cmds, so does this mean a bug does exist?

```
root@k8s-w03:/sys/fs/cgroup/kubepods.slice/kubepods-pod150b326a_8f7c_43b9_8801_cb7dccfdb7d9.slice# cat memory.high
max
root@k8s-w03:/sys/fs/cgroup/kubepods.slice/kubepods-pod150b326a_8f7c_43b9_8801_cb7dccfdb7d9.slice# cat memory.max
67108864
```

**Comment by pacoxu** [comment]
This is expected,
```
cat memory.high
max
```
This means no throttling from cgroup memory side.

**Comment by echel0n-TR** [comment]
ok, so what else could it be then ? its certainly related to memory, I'm going to attempt setting request/limit static and see if the issue remains as well.

**Comment by pacoxu** [comment]
/sig node 
for triage

**Comment by sftim** [comment]
I presume that `aria2c` is writing to the container's filesystem, and that the Pod doesn't mark that container as immutable.

Your container runtime uses a mechanism to allow local modifications and that mechanism may be backed by node RAM. If so, that use of RAM could explain the rate limiting. Perhaps after some time the modifications spill to slower storage, such as `/var` or to a pagefile on the node?

Does this speed things up:
`aria2c --out=/dev/null -x5 -c https://dl2.quicksync.io/columbus-5-archive.20220830.1141.tar.lz4`?
(I haven't tested whether `aria2c` supports writing to a character special device)

**Comment by echel0n-TR** [comment]
I can certainly test that command and let you know, however, removing the memory limit does seem to allow things to run properly, so the big question is, with the memory limit enabled, why is the performance being throttled before the memory limit is even close to being hit if its related to node RAM ?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

Lets check if this `-out=/dev/null` will help to pinpoint the problem. Also memory limit may affect how app allocates memory even before the limit is reached. I don't know anything about `aria2c` though

**Comment by echel0n-TR** [comment]
> /triage needs-information
> 
> Lets check if this `-out=/dev/null` will help to pinpoint the problem. Also memory limit may affect how app allocates memory even before the limit is reached. I don't know anything about `aria2c` though

this failed to execute when trying to pass to null
