### ISSUE TITLE
E2E test for for ExpandedDNSConfig has a kubeadm-ism

### ISSUE THREAD

**Issue by Miciah** [kubernetes/kubernetes#114666]
### Which jobs are flaking?

#112824 added an E2E test that assumes that a service named "kube-dns" exists in the "kube-system" namespace.  This is a kubeadm-ism, and the test fails if the cluster DNS is not configured the way kubeadm configures it.  

Although this E2E test isn't a conformance test, making it functional on non-kubeadm clusters would increase its utility for distributors that may wish to run this E2E test as a conformance test.  

### Which tests are flaking?

[sig-network] DNS HostNetwork should resolve DNS of partial qualified names for services on hostNetwork pods with dnsPolicy: ClusterFirstWithHostNet

### Since when has it been flaking?

Since we ran it on an OpenShift cluster.  https://github.com/openshift/kubernetes/pull/1432

### Reason for failure (if possible)

The test makes assumptions about how the cluster DNS is configured.  

### Anything else we need to know?

The test uses `dnsPolicy: ClusterFirst` (not `dnsPolicy: None`), so it does not need to specify `dnsConfig.nameservers`, as far as I can tell.  Omitting `dnsConfig.nameservers` obviates the need to look up the service.  I believe that the service lookup was left in https://github.com/kubernetes/kubernetes/pull/112824 as an oversight during the development of the test when it was changed from specifying "None" to specifying "ClusterFirst": https://github.com/kubernetes/kubernetes/compare/5fcdde0a0a82b052bb67cd764150725f2ca73dd9..1098ff63f34673ef9eec06572cbfaf49cea93222

Cc: @gjkim42

### Relevant SIG(s)

/sig network

**Comment by neolit123** [comment]
responded on the pr.
https://github.com/kubernetes/kubernetes/pull/114667#pullrequestreview-1228159601

**Comment by aojea** [comment]
It seems kubeadm inherited the status-quo, I can't find any place that mandates the Service name for DNS

Asking @thockin for double checking

If it seems that the test can be done in a more portable way we should do it
