### ISSUE TITLE
align-by-socket and distribute-cpus-across-numa sometimes do not work together.

### ISSUE THREAD

**Issue by OurBoy22** [kubernetes/kubernetes#114642]
### What happened?

Some of the alpha features for cpu manager, specifically the distribute-cpus-across-numa and the align-by-socket are not working together, when they should in theory. 
To give some context, my system has two sockets, each one of which has two NUMA nodes, for a total of 4 NUMA nodes:
![image](https://user-images.githubusercontent.com/121176508/208925634-8f86900e-c166-498f-8b9e-8816e5e13516.png)
This is the CPU layout in my system. The NUMA nodes with the same color are the NUMA nodes that are on the same socket. In this case, there is 14 CPUs per NUMA node. 
The problem is when I try to reserve 15 CPUs for a guaranteed QoS pod, where only CPU manager static policy is enabled, as well as the two features mentioned above. The problem is the CPUs that are allocated to a pod:
![image](https://user-images.githubusercontent.com/121176508/208926651-339ec0d0-1cb2-4eb7-b017-8dd5af5bed92.png)
The CPU IDs in bold characters are the CPUs that are assigned to the pod: 1-2,5-6,9-10,13-14,29-30,33-34,37-38,42
While the distribute-cpus-across-numa is working correctly, it is not aligning by socket, since the CPUs assigned are not on the same socket.

### What did you expect to happen?

I would expect that both the distribute-cpus-across-numa and the align-by-socket features to work simultaneously. There should also be aligning by socket. In other words, the pod CPUs should be: 
![image](https://user-images.githubusercontent.com/121176508/208927387-a621d722-210d-40bf-ada8-7dd08c4f7c8e.png)
Since they are on the same socket, but also distributing across numa 

### How can we reproduce it (as minimally and precisely as possible)?

- Set up system with two socket such that each socket uses up two NUMA nodes, for a total of 4
- Set up static policy on the kubelet with minimal kube-reserved and system-reserved, and the two alphaa features enabled: align-by-socket and distribute-cpus-across-numa
- Deploy a guaranteed QoS pod that requires 1 CPU above the amount of CPUs per NUMA node (in my case, I have 14 CPUs per NUMA node, so I request 15)

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Cannot disclose

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@fromanirh is it actually a bug or behavior that can be done better (a.k.a. feature)?

**Comment by fromanirh** [comment]
> @fromanirh is it actually a bug or behavior that can be done better (a.k.a. feature)?

It seems a bug. Back from holidays, I'll look more deeply into this.

**Comment by ruquanzhao** [comment]
/assign
I'm very interested in this. May I try it out? 
Feel free to unassign me. @ffromani

**Comment by ffromani** [comment]
@ruquanzhao didn't had bandwidth yet. Feel free to work and get in touch on slack/github. I'd be happy to help and review.

**Comment by ruquanzhao** [comment]
I wrote a simple unit testcase of this situation:

```
var smallTopoTwoSocketFourNUMANoHT = &topology.CPUTopology{
	NumCPUs:      16,
	NumSockets:   2,
	NumCores:     16,
	NumNUMANodes: 4,
	CPUDetails: map[int]topology.CPUInfo{
		0:  {CoreID: 0, SocketID: 0, NUMANodeID: 0},
		4:  {CoreID: 4, SocketID: 0, NUMANodeID: 0},
		8:  {CoreID: 8, SocketID: 0, NUMANodeID: 0},
		12: {CoreID: 12, SocketID: 0, NUMANodeID: 0},

		1:  {CoreID: 1, SocketID: 1, NUMANodeID: 1},
		5:  {CoreID: 5, SocketID: 1, NUMANodeID: 1},
		9:  {CoreID: 9, SocketID: 1, NUMANodeID: 1},
		13: {CoreID: 13, SocketID: 1, NUMANodeID: 1},

		2:  {CoreID: 2, SocketID: 0, NUMANodeID: 2},
		6:  {CoreID: 6, SocketID: 0, NUMANodeID: 2},
		10: {CoreID: 10, SocketID: 0, NUMANodeID: 2},
		14: {CoreID: 14, SocketID: 0, NUMANodeID: 2},

		3:  {CoreID: 3, SocketID: 1, NUMANodeID: 3},
		7:  {CoreID: 7, SocketID: 1, NUMANodeID: 3},
		11: {CoreID: 11, SocketID: 1, NUMANodeID: 3},
		15: {CoreID: 15, SocketID: 1, NUMANodeID: 3},
	},
}

func TestPolicyWithAlignBySocketAndDistributeCPUsAcrossNUMAEnabled(t *testing.T) {
	newNUMAAffinity := func(bits ...int) bitmask.BitMask {
		affinity, _ := bitmask.NewBitMask(bits...)
		return affinity
	}
	AlignBySocketAndDistributeCPUsAccrossNUMAEnabledTestCases := []staticPolicyTest{
		{
			description: "AlignBySocket and DistributeCPUsAcrossNUMA both enabled",
			topo:        smallTopoTwoSocketFourNUMANoHT,
			options: map[string]string{
				AlignBySocketOption:            "true",
				DistributeCPUsAcrossNUMAOption: "true",
			},
			numReservedCPUs: 1,
			stAssignments:   state.ContainerCPUAssignments{},
			stDefaultCPUSet: cpuset.New(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15),
			pod:             makePod("fakePod", "fakeContainer", "5000m", "5000m"),
			topologyHint:    &topologymanager.TopologyHint{NUMANodeAffinity: newNUMAAffinity(), Preferred: true},
			expErr:          nil,
			expCPUAlloc:     true,
			expCSet:         cpuset.New(1, 3, 5, 7, 9),
		},
	}
	runStaticPolicyTestCaseWithFeatureGate(t, AlignBySocketAndDistributeCPUsAccrossNUMAEnabledTestCases[0])
}
```

**Comment by ruquanzhao** [comment]
@OurBoy22 Can you share some information about this type of CPU with NUMA architecture?

**Comment by OurBoy22** [comment]
@ruquanzhao unfortunately I don't have access to this server anymore (it was being used for an internship), but I believe it was an Intel server with SNC enabled, logical processors enabled, 2 sockets. I will try to see if I can find the exact CPU and get back to you

**Comment by ruquanzhao** [comment]
> @ruquanzhao unfortunately I don't have access to this server anymore (it was being used for an internship), but I believe it was an Intel server with SNC enabled, logical processors enabled, 2 sockets. I will try to see if I can find the exact CPU and get back to you

@OurBoy22 Thanks for the important information(Intel and SNC). I found something looks like it, just bigger.
https://www-lb.open-mpi.org/projects/hwloc/lstopo/images/2XeonSPv2+2kmem.v2.1.png (`dual Xeon Gold 6230`)
and https://www.spec.org/cpu2017/results/res2019q2/cpu2017-20190415-11960.html. FYI

**Comment by OurBoy22** [comment]
Yes, the CPU was very similar to that.
