### ISSUE TITLE
etcd CrashLoopBackOff updating kuber 1.23.9 to 1.24.8

### ISSUE THREAD

**Issue by Borosan** [kubernetes/kubernetes#114686]
### What happened?

I have a kubernetes cluster v 1.23.9 . installed via kubeadm. (3 master, 3 worker , 2 haproxy+keepalived as load balancer)
cilium as CNI (without kube-proxy)
a local docker image repo.

I followed https://v1-24.docs.kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/
to upgrade my cluster from 1.23.9 to 1.24.8
1.  I installed Kubeadm 1.24.8   (on master1)
2.  edit kubeadm configmap (just image repo changed)
3.  I ran `kubeadm upgrade plan` (on master1)
4.  I ran 'sudo kubeadm upgrade apply v1.24.8  --v=5 '  (master1)

kubeadm upgrade applay  results:

[apiclient] Found 3 Pods for label selector component=etcd
[upgrade/staticpods] Component "etcd" upgraded successfully!
I1224 14:39:58.187729  137258 etcd.go:168] retrieving etcd endpoints from "kubeadm.kubernetes.io/etcd.advertise-client-urls" annotation in etcd Pods
I1224 14:39:58.196053  137258 etcd.go:104] etcd endpoints read from pods: https://172.17.251.11:2379,https://172.17.251.13:2379,https://172.17.251.15:2379
I1224 14:39:58.208292  137258 etcd.go:224] etcd endpoints read from etcd: https://172.17.251.13:2379,https://172.17.251.11:2379,https://172.17.251.15:2379
I1224 14:39:58.208318  137258 etcd.go:122] update etcd endpoints: https://172.17.251.13:2379,https://172.17.251.11:2379,https://172.17.251.15:2379
[upgrade/etcd] Waiting for etcd to become available
I1224 14:39:58.208328  137258 etcd.go:484] [etcd] attempting to see if all cluster endpoints ([https://172.17.251.13:2379 https://172.17.251.11:2379 https://172.17.251.15:2379]) are available 1/10
I1224 14:40:00.240843  137258 etcd.go:464] Failed to get etcd status for https://172.17.251.11:2379: failed to dial endpoint https://172.17.251.11:2379 with maintenance client: context deadline exceeded
I1224 14:40:02.357612  137258 etcd.go:464] Failed to get etcd status for https://172.17.251.11:2379: failed to dial endpoint https://172.17.251.11:2379 with maintenance client: context deadline exceeded
I1224 14:40:04.527104  137258 etcd.go:464] Failed to get etcd status for https://172.17.251.11:2379: failed to dial endpoint https://172.17.251.11:2379 with maintenance client: context deadline exceeded
.
.
.
and it got stuck! till time out!

kgp result:

cilium-4jp8x                          1/1     Running            0                39h
cilium-n9qpw                          1/1     Running            0                39h
cilium-operator-8569dc6689-4jkjj      1/1     Running            2 (141m ago)     39h
cilium-operator-8569dc6689-w8pq9      1/1     Running            1 (141m ago)     39h
cilium-qdb4j                          1/1     Running            0                39h
cilium-s2l4w                          1/1     Running            0                39h
cilium-tn264                          1/1     Running            1 (38h ago)      39h
cilium-wfvrx                          1/1     Running            0                39h
coredns-559f86f968-t6bj9              1/1     Running            0                38h
coredns-559f86f968-zbhbv              1/1     Running            0                38h
etcd-mep-seps1m1                      0/1     CrashLoopBackOff   10 (2m55s ago)   29m
etcd-mep-seps1m2                      1/1     Running            0                3d23h
etcd-mep-seps1m3                      1/1     Running            0                3d23h
kube-apiserver-mep-seps1m1            0/1     CrashLoopBackOff   10 (2m59s ago)   43m
kube-apiserver-mep-seps1m2            1/1     Running            16 (52d ago)     3d23h
kube-apiserver-mep-seps1m3            1/1     Running            12 (52d ago)     3d23h
kube-controller-manager-mep-seps1m1   1/1     Running            0                42m
kube-controller-manager-mep-seps1m2   1/1     Running            2 (141m ago)     52d
kube-controller-manager-mep-seps1m3   1/1     Running            1 (18h ago)      52d
kube-scheduler-mep-seps1m1            1/1     Running            0                41m
kube-scheduler-mep-seps1m2            1/1     Running            2 (141m ago)     52d
kube-scheduler-mep-seps1m3            1/1     Running            0                52d

pod logs (k logs etcd-mep-seps1m1):

{"level":"warn","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/stream.go:421","msg":"lost TCP streaming connection with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"421d7dbe8cb94b62","remote-peer-id":"c8eb5384113cf101","error":"context canceled"}
{"level":"warn","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/peer_status.go:66","msg":"peer became inactive (message send to peer failed)","peer-id":"c8eb5384113cf101","error":"failed to read c8eb5384113cf101 on stream MsgApp v2 (context canceled)"}
{"level":"info","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream MsgApp v2","local-member-id":"421d7dbe8cb94b62","remote-peer-id":"c8eb5384113cf101"}
{"level":"warn","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/stream.go:421","msg":"lost TCP streaming connection with remote peer","stream-reader-type":"stream Message","local-member-id":"421d7dbe8cb94b62","remote-peer-id":"c8eb5384113cf101","error":"context canceled"}
{"level":"info","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/stream.go:442","msg":"stopped stream reader with remote peer","stream-reader-type":"stream Message","local-member-id":"421d7dbe8cb94b62","remote-peer-id":"c8eb5384113cf101"}
{"level":"info","ts":"2022-12-24T11:40:30.124Z","caller":"rafthttp/peer.go:335","msg":"stopped remote peer","remote-peer-id":"c8eb5384113cf101"}
{"level":"warn","ts":"2022-12-24T11:40:30.130Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"421d7dbe8cb94b62","remote-peer-id-stream-handler":"421d7dbe8cb94b62","remote-peer-id-from":"3c9177c5fc9b8f77","cluster-id":"f058168b6ce01337"}
{"level":"warn","ts":"2022-12-24T11:40:30.130Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"421d7dbe8cb94b62","remote-peer-id-stream-handler":"421d7dbe8cb94b62","remote-peer-id-from":"3c9177c5fc9b8f77","cluster-id":"f058168b6ce01337"}
{"level":"warn","ts":"2022-12-24T11:40:30.137Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"421d7dbe8cb94b62","remote-peer-id-stream-handler":"421d7dbe8cb94b62","remote-peer-id-from":"c8eb5384113cf101","cluster-id":"f058168b6ce01337"}
{"level":"warn","ts":"2022-12-24T11:40:30.137Z","caller":"rafthttp/http.go:413","msg":"failed to find remote peer in cluster","local-member-id":"421d7dbe8cb94b62","remote-peer-id-stream-handler":"421d7dbe8cb94b62","remote-peer-id-from":"c8eb5384113cf101","cluster-id":"f058168b6ce01337"}
{"level":"info","ts":"2022-12-24T11:40:30.137Z","caller":"embed/etcd.go:566","msg":"stopping serving peer traffic","address":"172.17.251.11:2380"}
{"level":"info","ts":"2022-12-24T11:40:31.138Z","caller":"embed/etcd.go:571","msg":"stopped serving peer traffic","address":"172.17.251.11:2380"}
{"level":"info","ts":"2022-12-24T11:40:31.138Z","caller":"embed/etcd.go:373","msg":"closed etcd server","name":"mep-seps1m1","data-dir":"/var/lib/etcd","advertise-peer-urls":["https://172.17.251.11:2380"],"advertise-client-urls":["https://172.17.251.11:2379"]}
{"level":"fatal","ts":"2022-12-24T11:40:31.138Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 172.17.251.15:2381: bind: cannot assign requested address","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.15/src/runtime/proc.go:225"}

container logs(crictl logs  <etcd-container-ID>):
.
.
.
{"level":"info","ts":"2022-12-24T11:45:41.868Z","caller":"embed/etcd.go:571","msg":"stopped serving peer traffic","address":"172.17.251.11:2380"}
{"level":"info","ts":"2022-12-24T11:45:41.868Z","caller":"embed/etcd.go:373","msg":"closed etcd server","name":"mep-seps1m1","data-dir":"/var/lib/etcd","advertise-peer-urls":["https://172.17.251.11:2380"],"advertise-client-urls":["https://172.17.251.11:2379"]}
{"level":"fatal","ts":"2022-12-24T11:45:41.868Z","caller":"etcdmain/etcd.go:204","msg":"discovery failed","error":"listen tcp 172.17.251.15:2381: bind: cannot assign requested address","stacktrace":"go.etcd.io/etcd/server/v3/etcdmain.startEtcdOrProxyV2\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/etcd.go:204\ngo.etcd.io/etcd/server/v3/etcdmain.Main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/etcdmain/main.go:40\nmain.main\n\t/tmp/etcd-release-3.5.5/etcd/release/etcd/server/main.go:32\nruntime.main\n\t/usr/local/google/home/siarkowicz/.gvm/gos/go1.16.15/src/runtime/proc.go:225"}
.
.
.

other nodes etcd logs(crictl logs <etcd-container-ID>) (master2):

{"level":"warn","ts":"2022-12-24T11:51:07.278Z","caller":"etcdserver/cluster_util.go:155","msg":"failed to get version","remote-member-id":"421d7dbe8cb94b62","error":"Get \"https://172.17.251.11:2380/version\": dial tcp 172.17.251.11:2380: connect: connection refused"}
{"level":"warn","ts":"2022-12-24T11:51:09.007Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"421d7dbe8cb94b62","rtt":"290.950046ms","error":"dial tcp 172.17.251.11:2380: connect: connection refused"}
{"level":"warn","ts":"2022-12-24T11:51:09.468Z","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"421d7dbe8cb94b62","rtt":"296.399554ms","error":"dial tcp 172.17.251.11:2380: connect: connection refused"}
{"level":"warn","ts":"2022-12-24T11:51:11.281Z","caller":"etcdserver/cluster_util.go:288","msg":"failed to reach the peer URL","address":"https://172.17.251.11:2380/version","remote-member-id":"421d7dbe8cb94b62","error":"Get \"https://172.17.251.11:2380/version\": dial tcp 172.17.251.11:2380: connect: connection refused"}
{"level":"warn","ts":"2022-12-24T11:51:11.281Z","caller":"etcdserver/cluster_util.go:155","msg":"failed to get version","remote-member-id":"421d7dbe8cb94b62","error":"Get \"https://172.17.251.11:2380/version\": dial tcp 172.17.251.11:2380: connect: connection refused"}

**it seems my etcd node is not health and others reject it! 

### What did you expect to happen?

I expect to have all static  pods in kube-system namespace healthy with new manifest files upgraded to v1.24.8 (master1)

### How can we reproduce it (as minimally and precisely as possible)?

install a cluster v 1.23.9 via kubeadm (3 master,3 wroker)  use 2 haproxy via keepalived. 
install cilium as CNI (without kube-proxy )

### Anything else we need to know?

it seems kubeadm wasn't successfull and didn't rollback!  i tried  --force but no susccess. if restore etcd manifest from backup . it works but the same thing happens after upgrade.

### Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:26:51Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.9", GitCommit:"c1de2d70269039fe55efb98e737d9a29f9155246", GitTreeState:"clean", BuildDate:"2022-07-13T14:19:57Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

local 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal$ uname -a

$uname -a
Linux mep-seps1m1 5.4.213-0504213-generic #202209150749 SMP Thu Sep 15 13:01:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
#containerd docker packaged used
#containerd --version
containerd containerd.io 1.6.14 9ba4b250366a5ddde94bb7c9d1def331423aa323

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
#cilium version  (without kubeproxy):

cilium-cli: v0.12.4 compiled with go1.19.1 on linux/amd64
cilium image (default): v1.12.2
cilium image (stable): v1.12.5
cilium image (running): v1.12.4

</details>

**Comment by neolit123** [comment]
hi, we have this kubeadm upgrade covered in e2e tests.
it could be due to an etcd bug or corrupt etcd member data.

> **it seems my etcd node is not health and others reject it!

you could follow online guides to restore etcd member from a healthy member.

best place to ask for help is #etcd on k8s slack or other support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

https://etcd.io/docs/v3.3/op-guide/recovery/

/close
/kind support
