### ISSUE TITLE
CEL: Invalid value: "object": internal error: runtime error: index out of range [3] with length 3 evaluating rule: <rule name>

### ISSUE THREAD

**Issue by inteon** [kubernetes/kubernetes#114661]
### What happened?

I'm seeing this error when posting an update to the kubernetes API:
`Invalid value: "object": internal error: runtime error: index out of range [3] with length 3 evaluating rule: <rule name>`

### What did you expect to happen?

No error

### How can we reproduce it (as minimally and precisely as possible)?

https://github.com/inteon/CEL_bug

### Kubernetes version

<details>

```console
$ ./kube-apiserver --version
Kubernetes v1.25.0
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cici37** [comment]
Hi @inteon Thanks for raising the issue.
I have tested with the CRD from your repo [here](https://github.com/inteon/CEL_bug/blob/main/example.com_mycrds.yaml) and it is working fine with my 1.26 cluster. Would you mind sharing more details on steps to reproduce your issue, the env info, cluster version, etc? Thanks

**Comment by cici37** [comment]
Never mind. I saw the test you are trying to run regarding the flaky result mentioned. 

> Hi @inteon Thanks for raising the issue. I have tested with the CRD from your repo [here](https://github.com/inteon/CEL_bug/blob/main/example.com_mycrds.yaml) and it is working fine with my 1.26 cluster. Would you mind sharing more details on steps to reproduce your issue, the env info, cluster version, etc? Thanks

**Comment by inteon** [comment]
> Never mind. I saw the test you are trying to run regarding the flaky result mentioned. 
> 
> > Hi @inteon Thanks for raising the issue. I have tested with the CRD from your repo [here](https://github.com/inteon/CEL_bug/blob/main/example.com_mycrds.yaml) and it is working fine with my 1.26 cluster. Would you mind sharing more details on steps to reproduce your issue, the env info, cluster version, etc? Thanks
> 
> 

Are you able to reproduce the issue?

**Comment by inteon** [comment]
@cici37 @liggitt I found the root cause! (wasn't easy): https://github.com/google/cel-go/pull/620

**Comment by liggitt** [comment]
Excellent find, thanks!

**Comment by jpbetz** [comment]
Wow, thanks for root causing this Tim!
