### ISSUE TITLE
KubeletConfiguration does not marshal into a useable form

### ISSUE THREAD

**Issue by saifshaikh48** [kubernetes/kubernetes#114644]
### What happened?

I'm trying to use the [KubeletConfiguration](https://pkg.go.dev/k8s.io/kubernetes/pkg/kubelet/apis/config#KubeletConfiguration) object to generate a kubelet configuration file. I created the KubeletConfiguration object, then marshalled it into a json string (stored in a file). When we try to start kubelet using this config file though, kubelet does not pick up the options. 

I suspect this is because the keys in the marshalled output are not in camelCase and instead have the first letter capitalized (e.g. `EnforceNodeAllocatable` rather than `enforceNodeAllocatable`). If I manually edit each key in the config file to start with a lowercase letter, kubelet can pick up the options without issue, but this is not a great experience as a consumer of the API.

### What did you expect to happen?

The resulting config file should be kubelet compatible. When kubelet is supplied this config, it should pick up all options specified and start without issue.

### How can we reproduce it (as minimally and precisely as possible)?

- create a KubeletConfiguration object with a non-default value (e.g. set `CgroupsPerQOS:false`)
- json.Marshall the object and write the output to a file (e.g. `kubelet.conf`)
- run kubelet supplying that file as config (`C:\k\kubelet.exe --config=C:\k\kubelet.conf...`)
- view the arguments kubelet tried to start with (cgroupsPerQOS will be defaulted to true, implying the config was not picked up)

### Anything else we need to know?

On Windows, kubelet will crash on start because of this.

Adding an inline JSON format specifier to each field in the [KubeletConfiguration](https://github.com/kubernetes/kubernetes/blob/v1.26.0/pkg/kubelet/apis/config/types.go#L82) struct should fix this.

### Kubernetes version

<details>

1.25/1.26

</details>

### Cloud provider

<details>
All
</details>

### OS version

<details>

Encountered on Windows Server (2019/2022)

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by harshanarayana** [comment]
@saifshaikh48 Did you try generating the spec using https://github.com/kubernetes/kubernetes/blob/v1.26.0/staging/src/k8s.io/kubelet/config/v1beta1/types.go ?

**Comment by harshanarayana** [comment]
Use that in conjunction with `k8s.io/apimachinery/pkg/runtime/serializer/json` for better experience.  You can use it like so, 

```golang
f, err := os.OpenFile(filePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0755)
// apijson is the aliased import
// &item is the KubeletConfiguration struct
if err == nil {
    if err := apijson.NewYAMLSerializer(apijson.DefaultMetaFactory, nil, nil).Encode(&item, f); err != nil {
        l.Error(err, "failed to persist CR information to the host system due to an error")
    }
    f.Sync()
    f.Close()
}
```

**Comment by saifshaikh48** [comment]
That brings another issue because of the `omitempty`. More info in [this comment](https://github.com/openshift/windows-machine-config-operator/pull/1279#discussion_r998769079)

**Comment by harshanarayana** [comment]
```bash
package main

import (
	"fmt"
	"os"

	"k8s.io/apimachinery/pkg/runtime/serializer/json"
	"k8s.io/kubelet/config/v1beta1"
)

func main() {
	k := v1beta1.KubeletConfiguration{
		CgroupsPerQOS: &[]bool{false}[0],
	}
	f, err := os.OpenFile("/tmp/config.yaml", os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0755)
	if err == nil {
		if err := json.NewYAMLSerializer(json.DefaultMetaFactory, nil, nil).Encode(&k, f); err != nil {
			fmt.Println(err)
		}
		f.Sync()
		f.Close()
	} else {
		fmt.Println(err)
	}
}
```
```bash
❯ cat /tmp/config.yaml                                                                                                                                                                                                                                              100%  ▓▒░
authentication:
  anonymous: {}
  webhook:
    cacheTTL: 0s
  x509: {}
authorization:
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupsPerQOS: false
containerLogRotateMaxWorker: 0
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

**Comment by harshanarayana** [comment]
@saifshaikh48  check the above example. Hope this sorts out your issue with both of your usecases.

**Comment by saifshaikh48** [comment]
@harshanarayana Could you explain the difference between the two packages `"k8s.io/kubelet/config/v1beta1"` and `"k8s.io/kubernetes/pkg/kubelet/apis/config"`? I was directed away from the former in favor of the latter by node folks.

**Comment by harshanarayana** [comment]
> I was directed away from the former in favor of the latter by node folks.

I see. If that is the case, I am sure there might have been a reason for it. I would love to hear more about it. I have personally been using the `k8s.io/kubelet/config/v1beta1` for my internal cases to generate config files.

**Comment by neolit123** [comment]
> Could you explain the difference between the two packages `"k8s.io/kubelet/config/v1beta1"` and `"k8s.io/kubernetes/pkg/kubelet/apis/config"`? I was directed away from the former in favor of the latter by node folks.

in k8s there is a concept of external and internal api, in this case for component configuration. kubelet, kubeadm  kube-scheduler all have the internal / external concept.

internal api should only be used by the components, are a subject of breaking changes if needed. users should only use the external api.

the k8s.io/kubelet package has the external api.
k8s.io/kubernetes/pkg should never be imported for external use.

hope this helps.

/close
/kind support
