### ISSUE TITLE
reservedCpus: 0-4 reserved cpu 0-2,24-25 on a node with 48 cores

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#114673]
### What happened?

In kubelet log, 
```
 kubelet[2476321]: reservedCpus: 0-4
...
[cpumanager] reserved 5 CPUs ("0-2,24-25") not available for exclusive assignment
```

### What did you expect to happen?

reservedCpus: 0-4 
the log should be:

```
policy_static.go:109] [cpumanager] reserved 5 CPUs ("0-4") not available for exclusive assignment
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Set `cpuManagerPolicy: static` in /var/lib/kubelet/config.yaml.
2. Set `reservedCpus: 0-4` in /var/lib/kubelet/config.yaml.
3. rm /var/lib/kubelet/cpu_manager_state
4. systemctl restart kubelet
5. check kubelet log for `exclusive assignment` 

### Anything else we need to know?

In our case, some pods using too much CPU hang the server to create new pods.
-  The node has 48C
-  A pod is using 32C with 32C request and 32C limit.
- At first, we use none cpuManagerPolicy, and after the pod is running on the node, new container creation will take about 1 minute. 
- Then we want to try static cpuManagerPolicy, and during testing, we create a pod using `stress -c 2000`.
- - the node still hangs for creating a new container

So we tried to use `CPUAffinity: 0-4` for container runtime and kubelet. But the kubelet `reservedCpus: 0-4` doesn't work as expected.

### Kubernetes version

<details>

```console
$ kubectl version
tested in v1.25 and v1.18
```

</details>

### Cloud provider

<details>
bare metal
</details>

### OS version

<details>
Centos 7.9

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.6 + v1.25
or
docker + v1.18
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico
</details>

**Comment by fromanirh** [comment]
We should note the command line option name is different from the configuration file key: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L621
I'm pointing this out because this can be a source of confusion.

**Comment by pacoxu** [comment]
> We should note the command line option name is different from the configuration file key: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubelet/config/v1beta1/types.go#L621
> I'm pointing this out because this can be a source of confusion.

Yeah, you are right.
- reservedCpus is wrong.
- reservedSystemCpus can work as expected.
