### ISSUE TITLE
Scheduler ignores taints when nodeName field is specified

### ISSUE THREAD

**Issue by marcinma** [kubernetes/kubernetes#114654]
### What happened?

Pod having `nodeName: master-node` in spec got scheduled on master node that has `NoSchedule` taints. Documentation at https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename doesn't specify such behavior. Also I didn't found anything in taints doc https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ that would suggest such behavior.

/sig node

### What did you expect to happen?

Unless pod has toleration to specific key/value and effect taints it shouldn't be scheduled on node that has taints, and be in pending state.

### How can we reproduce it (as minimally and precisely as possible)?

Assuming master node has name `master-node`
```sh
kubectl taint node master-node please=dontschedule:NoSchedule
cat << EOF | kubectl apply -f -
apiVersion: v1
kind: Pod
metadata:
  name: master-pod
  labels:
    app: master
spec:
  containers:
  - name: master-pod
    image: ubuntu
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  nodeName: master-node
EOF
kubectl get pod master-pod -o wide 
```

results:
```
NAME         READY   STATUS    RESTARTS   AGE    IP               NODE          NOMINATED NODE   READINESS GATES
master-pod   1/1     Running   0          102s   192.168.77.137   master-node   <none>           <none>
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:15:02Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux master-node 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/sig scheduling

I vaguely remember that once you specify the nodeName you skips the scheduler entirely, but better the corresponding SIG to answer, and maybe document it better if this is the issue and is not clear on the docs

**Comment by ahg-g** [comment]
Correct, a pod with nodeName set is a scheduled pod. The scheduler doesn't reverse scheduling decisions (it can preempt, but that is different).

**Comment by ahg-g** [comment]
btw, you can use `NoExecute` to get the pod evicted.

On a side note, I think kubelet doesn't check the taints filter on pod admission.

**Comment by gjkim42** [comment]
> On a side note, I think kubelet doesn't check the taints filter on pod admission.

https://github.com/kubernetes/kubernetes/pull/101218
As of v1.24, kubelet checks taint/toleration before accepting pods.

**Comment by liggitt** [comment]
/remove-kind bug

Agreed, a pod with an assigned nodeName skips all scheduling decisions. See https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/ for details on using a node selector or node affinity to target a node while still honoring scheduling logic.

A docs update to that page that adds "scheduling taints are not honored" to the list of drawbacks to using nodeName directly in https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename would be welcome

/close
