### ISSUE TITLE
orphaned pod pod_id found, but error not a directory occurred when trying to remove the volumes dir numErrs=3

### ISSUE THREAD

**Issue by farhadkh000** [kubernetes/kubernetes#114698]
### What happened?

i have a kubeadm cluster with 3 node master and 3 node worker , when i poweroff node 3 of workers fo test plan that is show NotReady
in 
# kubectl get node 
```
NAME            STATUS     ROLES           AGE    VERSION
kubermaster01   NotReady   control-plane   693d   v1.25.3
kubermaster02   Ready      control-plane   36d    v1.25.3
kubermaster03   NotReady   control-plane   693d   v1.25.3
kubeworker01    NotReady   <none>          254d   v1.25.3
kubeworker02    Ready      <none>          226d   v1.25.3
kubeworker03    NotReady   <none>          226d   v1.25.3
```
and when i turn on that workers show ready :
```
NAME            STATUS     ROLES           AGE    VERSION
kubermaster01   NotReady   control-plane   693d   v1.25.3
kubermaster02   Ready      control-plane   36d    v1.25.3
kubermaster03   NotReady   control-plane   693d   v1.25.3
kubeworker01    NotReady   <none>          254d   v1.25.3
kubeworker02    Ready      <none>          226d   v1.25.3
kubeworker03    Ready      <none>          226d   v1.25.3
```
but i see status of many pods is Evicted and stuck in this state on the worker 3 : 
```
traefik-internal    traefik-internal-4gsvs         0/1     Evicted   0    5h54m   <none>    kubeworker03 
traefik-internal    traefik-internal-4j6b6         0/1     Evicted   0    5h50m   <none>    kubeworker03 
traefik-internal    traefik-internal-4j7wq         0/1     Evicted   0    5h53m   <none>    kubeworker03 
traefik-internal    traefik-internal-4lm7m         0/1     Evicted   0    5h49m   <none>    kubeworker03 
traefik-internal    traefik-internal-4m8rm         0/1     Evicted   0    5h50m   <none>    kubeworker03 
traefik-internal    traefik-internal-4np4g         0/1     Evicted   0    5h50m   <none>    kubeworker03 
traefik-internal    traefik-internal-4qfk6         0/1     Evicted   0    5h49m   <none>    kubeworker03 
traefik-internal    traefik-internal-4scvl         0/1     Evicted   0    5h49m   <none>    kubeworker03 
traefik-internal    traefik-internal-4sw9j         0/1     Evicted   0    5h50m   <none>    kubeworker03 
traefik-internal    traefik-internal-4vl67         0/1     Evicted   0    5h51m   <none>    kubeworker03 
traefik-internal    traefik-internal-4w75p         0/1     Evicted   0    5h51m   <none>    kubeworker03 
traefik-internal    traefik-internal-4z29g         0/1     Evicted   0    5h52m   <none>    kubeworker03 
```
and i get error in kubelet  workr 3
Dec 26 13:05:19 kubeworker03 kubelet[1864]: E1226 13:05:19.768359    1864 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"34415f74-92b3-463f-a4ae-c7b0e34edbea\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=3

### What did you expect to happen?

i expected when worker up again orphan pods deleted and if needed created again 

### How can we reproduce it (as minimally and precisely as possible)?

Interestingly, this happened only to the traefik service
I used version 20.6 with Daemonset , you can test it

### Kubernetes version

```
$ kubectl version
# WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2",
Kustomize Version: v4.5.7

```

### Cloud provider

kubernets

### OS version

# On Linux:
```
$ cat /etc/os-release
# NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
$ uname -a
```
# Linux kubeworker03 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

containerd v1.6.4

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico/csi:v3.24.3
calico/cni:v3.24.3

**Comment by pacoxu** [comment]
dup with https://github.com/kubernetes/kubernetes/issues/105536 ?
/sig storage

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

for triage by sig storage

**Comment by msau42** [comment]
@farhadkh000 can you check the contents of the directory and see if it is the vol_data.json file not getting cleaned up?

**Comment by bsdnet** [comment]
I hit a similar issue:

$ grep " not a directory" kubelet.log
Jan 04 18:51:21 ci-my114-84464d4457-5jpnx kubelet[1612]: E0104 18:51:21.080528    1612 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"228e5c3e-6756-4b16-929c-7948ad594342\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=1
Jan 04 18:51:23 ci-my114-84464d4457-5jpnx kubelet[1612]: E0104 18:51:23.080811    1612 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"228e5c3e-6756-4b16-929c-7948ad594342\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=1
Jan 04 18:51:25 ci-my114-84464d4457-5jpnx kubelet[1612]: E0104 18:51:25.081170    1612 kubelet_volumes.go:245] "There were many similar errors. Turn up verbosity to see them." err="orphaned pod \"228e5c3e-6756-4b16-929c-7948ad594342\" found, but error occurred when trying to remove the volumes dir: not a directory" numErrs=1

$ sudo ls /var/lib/kubelet/pods/228e5c3e-6756-4b16-929c-7948ad594342/volumes/kubernetes.io~csi/pvc-254af11f-d9ba-4cba-a005-fbadd979b9b6/vol_data.json
/var/lib/kubelet/pods/228e5c3e-6756-4b16-929c-7948ad594342/volumes/kubernetes.io~csi/pvc-254af11f-d9ba-4cba-a005-fbadd979b9b6/vol_data.json

vol_data.json is not cleaned up after node rebooted.

**Comment by jingxu97** [comment]
I think this issue could be fixed by https://github.com/kubernetes/kubernetes/pull/108874 which is in 1.26. We could cherrypick to 1.25 if possible

**Comment by xing-yang** [comment]
Fix https://github.com/kubernetes/kubernetes/pull/108874 is already backported to 1.25.

**Comment by xing-yang** [comment]
Closing this one as it is a duplicate of https://github.com/kubernetes/kubernetes/issues/105536
