### ISSUE TITLE
[E2E] Support for pulling images from private registry

### ISSUE THREAD

**Issue by Divya063** [kubernetes/kubernetes#114615]
### What would you like to be added?

Our team is using sonobuoy to run the conformance tests on a cluster. When running Sonobuoy E2E/Conformance tests, deployed pods will go into an ErrImagePull/ImagePullBackOff state when the image resides in a repository that requires authentication, and credentials are not passed with the request.

The [E2E/Conformance test](https://github.com/kubernetes/kubernetes/tree/master/test/e2e) process spawns pods in separate namespaces to run E2E/Conformance tests. If pods are referencing images from a private registry, the secrets wouldn’t be available in the newly created namespaces and the pod will fail to start.

This is the issue reported by one of the sonobuoy users - https://github.com/vmware-tanzu/sonobuoy/issues/1038

Kubernetes E2E framework provides a `--e2e-docker-config-file`  flag which takes in a file containing the credentials that can be used to pull images from private registries needed for a test.  Using the credentials a secret can be created in the newly created namespace. 
With the Secret created, the default service account (in the new namespace) will be patched with the created secret and can then be referenced by the test pod, and repository authentication should be successful.

### Why is this needed?

As of now, when running the E2E tests, the flag is only being checked in a single test - https://github.com/kubernetes/kubernetes/blob/57eb5d631ccd615cd161b6da36afc759af004b93/test/e2e/common/node/runtime.go#L292-L308
so despite passing the credential file, other tests would fail.

**Comment by zeusbee** [comment]
Please assign to me

**Comment by aojea** [comment]
I´m not sure I understand well this issue, is the request to run the conformance tests being able to use a different registry than the one defined in the tests?

that was fixed by @smarterclayton here https://github.com/kubernetes/kubernetes/pull/93510

Or is this about some specific tests ?

The linked issue refers to the former https://github.com/vmware-tanzu/sonobuoy/issues/1038#issuecomment-563365850 and your fix is modifying the tests that verify pulling images from registries, that seems totally unrelated

**Comment by aojea** [comment]
I think that the request is that when users override  the e2e test images repository `KUBE_TEST_REPO=quay.io/openshift/community-e2e-images` , if this is authenticated, the e2e should still be able to work

**Comment by aojea** [comment]
> Our team is using sonobuoy to run the conformance tests on a cluster. When running Sonobuoy E2E/Conformance tests, deployed pods will go into an ErrImagePull/ImagePullBackOff state when the image resides in a repository that requires authentication, and credentials are not passed with the request.

@Divya063 can you provide more details about how you are running conformance tests? are you overriding the images repository with the `KUBE_TEST_REPO` env variable? or using some proxy or something unusual?

**Comment by aojea** [comment]
@dims it seems you have more context about this https://github.com/kubernetes/kubernetes/issues/109523#issuecomment-1100974649

**Comment by aojea** [comment]
copying here for visibility, so I wonder if we are not having the same mistake as the reported in the above issue

>> I edited a sonobuoy binary to set the KUBE_TEST_REPO=my/repo and got the following output. You can see most of the images were translated. The authenticated and invalid images were not.

> authenticated and invalid images are hard coded by design and won't be switched as they are testing special conditions (and just copying images are not enough)

**Comment by Divya063** [comment]
sorry for the confusion, currently we are using `KUBE_TEST_REPO_LIST` env variable for overriding the images repository. Through this, we can pass in the config having the registries mapping which may look like this:
```
buildImageRegistry: testbeta64.jfrog.io/docker-local
dockerGluster: docker.io/gluster
dockerLibraryRegistry: docker.io/library
e2eRegistry: testbeta64.jfrog.io/docker-local
e2eVolumeRegistry: gcr.io/kubernetes-e2e-test-images/volume
gcRegistry: testbeta64.jfrog.io/docker-local
gcEtcdRegistry: registry.k8s.io
promoterE2eRegistry: testbeta64.jfrog.io/docker-local
sigStorageRegistry: registry.k8s.io/sig-storage
gcAuthenticatedRegistry: testbeta64.jfrog.io/docker-local
```
so currently any tests whose image resides in the authenticated registry (testbeta64.jfrog.io) fail as the pods spawned in the new namespace don't have credentials for the `testbeta64.jfrog.io` registry. In the current approach, I'm using --docker-config-file to pass in the credentials and after [the namespace is created](https://github.com/kubernetes/kubernetes/blob/8ca843f037d55b8177f37bf91b951a7a09251a23/test/e2e/framework/framework.go#L452) for each test, a secret is created using the content present in the `docker-config-file` and is patched with the default service account. This way every new test namespace which is created would have access to the secret. 

cc @dims @aojea

**Comment by dims** [comment]
@Divya063 yep, this is by design. Note that None of the conformance tests should fail in an air-gapped environment (no access to internet). We don't provide the same guarantee to the other e2e tests.

If you see test marked as conformance ( https://cs.k8s.io/?q=ConformanceIt&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes ) fail, then we can have this conversation.

**Comment by aojea** [comment]
My main concern is this:

- KUBE_TEST_REPO_LIST is a internal detail undocumented or at least not well documented
- the flag `"docker-config-file", "", "A file that contains credentials which can be used to pull images from certain private registries, needed for a test.")` is a flag for a test

Using a flag created for a test to provide a feature to an undocumented environment variable sounds wrong ... very wrong

In case that we see motivation to support this setup, and thinking out loud:
1. we perpetuate the env hack and add `KUBE_TEST_REPO_CONFIG_FILE`
2. we add new flags or another way to configure the repo list and the secret
- ...

What I definitely think we should not do is to reuse the existing flag

@spiffxp @BenTheElder

**Comment by Divya063** [comment]
I see, even for conformance the tests would fail (if the images reside in private registries) as currently there is no way to pass the secrets.

**Comment by pohly** [comment]
> yes, KUBE_TEST_REPO_LIST was designed ONLY for conformance.

It also got extended to work for CSI storage tests (pulling sidecars). Those storage tests are not and cannot be marked as conformance tests because they depend on optional features, but being able to run them for suitable clusters is useful nonetheless. Those clusters might be air-gappend and/or use registries which need authentication.
