### ISSUE TITLE
Add FileEnvSource and FileKeySelector to add environment generated on the fly

### ISSUE THREAD

**Issue by QuentinN42** [kubernetes/kubernetes#114674]
## Some context

Sometimes we want to add some env vars but they must be generated just before the container start.

For example Hashicorp Vault let us define the enironment variables by adding some annotations (cf. sources).
Then it will create an init container to pull all needed env.
Because of the current limitations, it will create a file in a volume mounted on the main ct.

This is not the only job that require that, sometimes we just have a bash script :

```bash
JWT="$(curl https://sso.example.com/auth -d ...)"

echo "JWT=$JWT" > /env
```

To create some one time secrets.

The `initContainers` feature is great and let us make this realy easily !

## Defining the problem

But now we encounter the following problem :
We now need to start an image with this env file (`/env` in this example).
But the docker image doesn't know that this file exist...

A workaround is to source this file by overwriting the container entrypoint ...
This is a big job to maintain this especially when the image comes from a 3rd party.

I will have the following structure that I want to add for all docker images :

```yaml
spec:
  initContainers:
    # This create the /env file
  containers:
    - name: myapp
      image: myapp:latest
      command:
        ['sh', '-c']
      args:
        ['source /env && <myapp entrypoint script>']
      ports:
        - containerPort: 9090
```

This is the way anyone does it today as far as I know (cf. sources).

An other solution is to make the init container to create a secret / configmap for this particular pod, but the complexity layer added and the dificulty to remove it explains that this solution is not widely used.

## A solution

A good solution for that is to create a new `EnvVarSource` or an `EnvFromSource` for a container.

It's my first issue on k8s so I'm not the best to tell you what needs to be done but in my mind I see somethink like this :

```yaml
envFrom:
  - fileRef:
      path: /env
      boolean: true
  - fileRef:
      path: /env2
env:
  - name: MY_JWT
    fileKeyRef:
      path: /env
      key: JWT
```

## Docs

The following draft of the docs can help you to view my idea :

### FileEnvSource

FileEnvSource selects a file inside the container to populate the environment variables with.
The contents of the target file will be parsed as an env file [need specs] that represent the key-value pairs as environment variables.

    Appears In:
    EnvFromSource [core/v1]

| Field              | Description |
| --------           | --------    |
| path (string)      | Path to the file inside the container    |
| optional (boolean) | Specify whether the File must be defined |

### FileKeySelector

Selects a key from a File.

    Appears In:
    EnvVarSource [core/v1]

| Field              | Description |
| --------           | --------    |
| path (string)      | Path to the file inside the container    |
| key (strint)       | The key to select                        |
| optional (boolean) | Specify whether the File must be defined |

## Sources

- [Env var sourcing example for vault](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/examples)
- [K8S EnvVarSource API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#envvarsource-v1-core)
- [K8S EnvFromSource API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#envfromsource-v1-core)
- [Stackoverflow question](https://stackoverflow.com/questions/68804024/theres-any-way-in-k8s-to-source-an-env-file-dynamically-generated-during-an)

### Why is this needed?

As I presented it previously, it is hard to generate some environment variable on the fly for a specific container and mostly impossible to do that without modifying the container entrypoint.

**Comment by fruitbox12** [comment]
Yes, it can be challenging to use environment variables that are generated by an init container in a main container, especially if the main container is using a pre-built image from a third party. One way to handle this is to use the approach you mentioned, where the main container runs a script that sources the environment variables file and then runs the main application. This allows you to set the environment variables in the main container without modifying the image itself.

Another option is to use a sidecar container to inject the environment variables into the main container. The sidecar container could read the environment variables file and then use the Kubernetes API to update the environment of the main container. This would allow you to set the environment variables without modifying the main container's command or entrypoint.

Using secrets or config maps to store the environment variables can also be a good option, especially if the variables contain sensitive information that needs to be kept secure. However, it's important to consider the overhead of managing secrets and config maps, as well as the potential complexity of using them in your application.

Ultimately, the best approach will depend on your specific use case and the requirements of your application. It's worth considering the trade-offs between the different approaches and choosing the one that best meets your needs

**Comment by fruitbox12** [comment]
Adding a FileEnvSource field to the container specification would allow you to specify a file that should be used to set environment variables in the container. The field could contain a path field to specify the path to the file and a boolean field to indicate whether the file should be sourced (similar to the way the source command works in bash).

Alternatively, you could add a FileKeySelector field to the container specification, which would allow you to specify a file and a key within that file to use as the value of an environment variable. The field could contain a path field to specify the path to the file and a key field to specify the name of the environment variable to set.

These fields would allow you to easily set environment variables in a container from a file or files, without having to modify the container's command or entrypoint. This would be particularly useful if you need to set environment variables that are generated on the fly, such as one-time secrets or dynamically generated configuration values.

**Comment by QuentinN42** [comment]
Thanks for this docs :)

**Comment by QuentinN42** [comment]
I've read some code and I think I will need to edit this function :
https://github.com/kubernetes/kubernetes/blob/a8fc2c65433f584b8c75b49ff84d12e6c1f9777c/pkg/kubelet/kubelet_pods.go#L583

**Comment by derekwaynecarr** [comment]
Could a EmptyDir that is used to source the env from work as well?  It would allow an init container to write to a shared location on disk with the pod fate, and be referenced by your primary container.

**Comment by SergeyKanzhelev** [comment]
Discussed diring the SIG Node meeting 1/10/2023: https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit#bookmark=id.4w97rjwomiaq

**Comment by QuentinN42** [comment]
Some questions still needs to be discuss :
 - [ ] [ERRORS] How do we handle errors ? (if the file is not an env file / if there is some errors in it)
 - [ ] [ORDER] Sourcing from some file inside container might be not feaseable if env is generated before container is created.
 - [ ] [NRI] Investigate NRI hook to do it ? (I have no idea what it is, [need to read the docs](https://docs.newrelic.com/))
 - [ ] [SECU] Sourcing from arbitrary path may have security concerns, validate files trough security context ?
 - [ ] [SCOPE] The root path may be too large scope. Would limiting this to empty dir files be enough ?

**Comment by QuentinN42** [comment]
> Some uses for an emptyDir are:
> - scratch space, such as for a disk-based merge sort
> - checkpointing a long computation for recovery from crashes
> - holding files that a content-manager container fetches while a webserver container serves the data
[K8s volumes docs](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)

This is exactly a `checkpointing` for env var so I think using `emptydir` is totally ok, but the 3rd party init container can export  it's data not in an emptydir ...

**Comment by QuentinN42** [comment]
So maybe to solve [ORDER], [SECU] and [SCOPE] at once, we can reference a file path of a volume like in the [VolumeMount](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#volumemount-v1-core).

- [ORDER] It can be done before the ct is created so no order problems.
- [SECU] / [SCOPE] This will only allow the operator to read files that he can already mount in an alpine container and read it.

**Comment by QuentinN42** [comment]
@mikebrow hey, during the meeting, you mentioned NRI plugin that support modifying environment variables for the containers.
But I don't find any information about that... Are you mentioning this repo : [newrelic/nri-kubernetes](https://github.com/newrelic/nri-kubernetes) ?

**Comment by harshanarayana** [comment]
@QuentinN42  I believe it is the https://github.com/containerd/nri that was being talked about. This has the ability to provide hooks based on lifecycle

**Comment by harshanarayana** [comment]
```golang
package main

import (
	"context"
	"flag"
	"fmt"
	"os"

	"github.com/sirupsen/logrus"
	"sigs.k8s.io/yaml"

	"github.com/containerd/nri/pkg/api"
	"github.com/containerd/nri/pkg/stub"
)

type config struct {
	CfgParam1 string `json:"cfgParam1"`
}

type plugin struct {
	stub stub.Stub
	mask stub.EventMask
}

var (
	cfg config
	log *logrus.Logger
)

func (p *plugin) Configure(config, runtime, version string) (stub.EventMask, error) {
	log.Infof("Connected to %s/%s...", runtime, version)

	if config == "" {
		return 0, nil
	}

	err := yaml.Unmarshal([]byte(config), &cfg)
	if err != nil {
		return 0, fmt.Errorf("failed to parse configuration: %w", err)
	}

	log.Info("Got configuration data %+v...", cfg)

	return 0, nil
}

func (p *plugin) Synchronize(pods []*api.PodSandbox, containers []*api.Container) ([]*api.ContainerUpdate, error) {
	log.Info("Synchronizing state with the runtime...")
	return nil, nil
}

func (p *plugin) Shutdown() {
	log.Info("Runtime shutting down...")
}

func (p *plugin) CreateContainer(pod *api.PodSandbox, ctr *api.Container) (*api.ContainerAdjustment, []*api.ContainerUpdate, error) {
	log.Infof("Creating container %s/%s/%s...", pod.GetNamespace(), pod.GetName(), ctr.GetName())

	_, ok := pod.Annotations["jwt-required"]
	_, cOk := ctr.Annotations["jwt-required"]

	adjustment := &api.ContainerAdjustment{}
	updates := []*api.ContainerUpdate{}

	if ok || cOk {
		adjustment.Env = []*api.KeyValue{
			{
				Key:   "JWT",
				Value: "jwt-token-string",
			},
		}
	}
	return adjustment, updates, nil
}

func (p *plugin) onClose() {
	log.Infof("Connection to the runtime lost, exiting...")
	os.Exit(0)
}

func main() {
	var (
		pluginName string
		pluginIdx  string
		err        error
	)

	log = logrus.StandardLogger()
	log.SetFormatter(&logrus.TextFormatter{
		PadLevelText: true,
	})

	flag.StringVar(&pluginName, "name", "", "plugin name to register to NRI")
	flag.StringVar(&pluginIdx, "idx", "", "plugin index to register to NRI")
	flag.Parse()

	p := &plugin{}
	opts := []stub.Option{
		stub.WithOnClose(p.onClose),
	}
	if pluginName != "" {
		opts = append(opts, stub.WithPluginName(pluginName))
	}
	if pluginIdx != "" {
		opts = append(opts, stub.WithPluginIdx(pluginIdx))
	}

	if p.stub, err = stub.New(p, opts...); err != nil {
		log.Fatalf("failed to create plugin stub: %v", err)
	}

	if err = p.stub.Run(context.Background()); err != nil {
		log.Errorf("plugin exited (%v)", err)
		os.Exit(1)
	}
}

```

Here is an example plugin that can inject the JWT token into containers based on annotation

1. Use `containerd` `v1.7.0-beta2` for this.
2. Update the containerd config to enable NRI
```toml
  [plugins."io.containerd.nri.v1.nri"]
    config_file = "/etc/nri/nri.conf"
    disable = false
    plugin_path = "/opt/nri/plugins"
    socket_path = "/var/run/nri.sock"
```
```bash
echo "disableConnections: false" > /etc/nri/nri.conf
```

Generate the above plugin into a bin and run that using `<bin> -idx 12 -name test`

Make sure to set the annotation so that it shows up in the pod level. When you create the container the ENV will get injected by the NRI

```bash
# crictl exec 0faeecd19b91d env | grep -i jwt
JWT=jwt-token-string
```

**Comment by Sharpz7** [comment]
/assign @Sharpz7 

Working on the KEP currently:

**Comment by ChipmunkV** [comment]
I'd like to mention a possible feature: ability to concatenate the values of an env var of the image with generated strings.

There is an env var issue when using GKE with GPU accelerators enabled.

As I understand, this https://github.com/GoogleCloudPlatform/container-engine-accelerators thing mounts the GPU driver libs and executables into container under `/usr/local/nvidia/`.

But to use the driver and tools like `nvidia-smi` we need to set the env vars in the container:
```bash
export PATH=${PATH-}:/usr/local/nvidia/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH-}:/usr/local/nvidia/lib64
```

Would also be useful when the image has some setup inside with `LD_PRELOAD` and we want to add more libraries to it (VirtualGL for example).

**Comment by FirePing32** [comment]
@kannon92 I was figuring out a solution for this. Does the Kubelet API have a method to read files from within container?

**Comment by FirePing32** [comment]
@harshanarayana is this issue still relevant? maybe you can triage it so I can work on it further.

**Comment by harshanarayana** [comment]
@FirePing32 there is an enhancement KEP being discussed on this already. Please check the k/enhancements repo. Let me know if can't find the thread

**Comment by SergeyKanzhelev** [comment]
do we need this bug to be open if we have an enhancement https://github.com/kubernetes/enhancements/issues/3721?

/remove-lifecycle rotten

**Comment by AnishShah** [comment]
Sure, we can close this.

/close
