### ISSUE TITLE
Kubelet does not enforce pod.spec.nodeSelector if APIServers list is empty

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#11461]
https://github.com/GoogleCloudPlatform/kubernetes/pull/9759 added a short-circuit to `checkNodeSelectorMatching` which allows all pods if the kubelet thinks it is in standaloneMode.

`standaloneMode` defaults to `true` if the Kubelet's initial APIServer list is empty. This means it is very easy to put a kubelet in a state where it is not enforcing `pod.spec.nodeSelector`, which is a major component of securing which nodes a pod can be run on.

**Comment by mikedanese** [comment]
@dchen1107

**Comment by liggitt** [comment]
I would expect a standalone kubelet to behave as if it had an empty label set, and continue enforcing matching `pod.spec.nodeSelector`... I probably shouldn't be able to run a pod with a node selector of {"foo":"bar"} on a standalone node that has no labels

**Comment by liggitt** [comment]
I'd argue for a higher priority because of the security implications until this is fixed (either by treating standalone nodes as having empty label sets, or by requiring "standalone" mode to be explicitly set, rather than defaulting to true based on the absence of a list value)

**Comment by dchen1107** [comment]
This is known issue when we decided to introduce standaloneMode for master node, and not register its kubelet to kube-apiserver. But in today's kubernetes cluster, only master node should be in standaloneMode, right? 
My biggest concern or unhappiness about such decision is master node is not very easy, and pods running on master are not visible to the end users. But obviously that is not your concern listed here. Besides that, Any other use cases? or concerns?

**Comment by liggitt** [comment]
If the master node is in standalone mode, then any pod can specify the master node as a `pod.spec.nodeName` and get run on it with no enforcement of `pod.spec.nodeSelector`. That seems severe.

**Comment by dchen1107** [comment]
Shouldn't a node is marked as a standalone, it won't register itself to kube-apiserver, thus it is removed from scheduler's scheduling pool, and invisible from scheduler. In that case, no arbitrary pods could be scheduled to it through kubectl / API except file-based ones?

**Comment by dchen1107** [comment]
cc/ @davidopp @bprashanth

**Comment by liggitt** [comment]
I guess if the master node doesn't have an ApiserverSource, it won't pull the pod and run it.

My main concern is that it is too easy to create a node in a very permissive state. Not specifying an `APIServerList` should not make the node accept any pod... you should have to opt into that

**Comment by mikedanese** [comment]
@liggitt that would require ssh access to the master machine and write access to the manifest dir to run anything on the standalone kubelet.

**Comment by mikedanese** [comment]
And if a user has that much privilege, then they already have enough privilege to remove the node selector line from the pod manifest. Is that understanding correct or is there a hole that I'm missing?

**Comment by dchen1107** [comment]
@mikedanese I think your understanding is correct. @liggitt?

**Comment by liggitt** [comment]
In OpenShift, we restrict/augment the `pod.spec.nodeSelector` field on a pod at pod creation time to make sure the pod doesn't land on restricted nodes.

We also create a Kubelet like this (explicitly setting the host network source and the API client):
```
server := kapp.NewKubeletServer()
server.HostNetworkSources = []string{kubelet.ApiserverSource}
...
cfg, _ := server.KubeletConfig()
cfg.KubeClient = myKubeClient
...
cfg.RunKubelet()
```

It was disconcerting for the kubelet to switch into standalone mode, despite being told it had an ApiserverSource.

**Comment by liggitt** [comment]
self-registration is supposed to be controlled by the `RegisterNode` flag, not `StandaloneMode`, right?

**Comment by liggitt** [comment]
now that I know about the standalone flag, I can certainly set it to `False`... I'm just concerned about the approach of implicitly turning on flags that disable significant protections

**Comment by mikedanese** [comment]
It is. RegisterNode=false does not imply StandaloneMode. We assumed that no len(apiservers) == 0 at time of construction was sufficient condition to assert the kubelet was running in standalone. Perhaps we need to move this check to Run().

> pod creation time

Does this mean when the api object is created?

**Comment by liggitt** [comment]
If the config has a KubeClient and an ApiserverSource, it's not standalone :)

> Does this mean when the api object is created?

Yeah, at admission time

**Comment by mikedanese** [comment]
Yup that makes sense. We should move StandaloneMode to an explicit flag

**Comment by liggitt** [comment]
it already is an explicit flag in the struct (which is sufficient for my use), it just gets defaulted oddly

**Comment by bprashanth** [comment]
> Shouldn't a node is marked as a standalone, it won't register itself to kube-apiserver, thus it is removed from scheduler's scheduling pool, and invisible from scheduler. In that case, no arbitrary pods could be scheduled to it through kubectl / API except file-based ones?

Yes, unless the kubelet restarted into standalone, in which case there's probably a 40s window where it can get pods till it goes into not ready

**Comment by mikedanese** [comment]
I mean "command line flag". Or we fix the condition for which we assert the kubelet is in standalone which could get complicated and out of date.
