### ISSUE TITLE
hack/kube-dump.sh should be updated for etcd running as a pod

### ISSUE THREAD

**Issue by dchen1107** [kubernetes/kubernetes#11476]
the script is stale and still assume etcd server and other master components are running as native processes on the node, not pod.

**Comment by dchen1107** [comment]
cc/ @bgrant0607 @lavalamp

**Comment by lavalamp** [comment]
I don't even know what this script is for. Clearly it needs a test, though. Can we make it an apiserver endpoint or something?

**Comment by bgrant0607** [comment]
Or delete it?

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
