### ISSUE TITLE
X509 Authentication to multiple Clusters

### ISSUE THREAD

**Issue by gaedemischwarz** [kubernetes/kubernetes#114720]
### What happened?

Hello,

we wan't to implement the X509 Authentication to different Kubernetes Clsuters. 
For this we followed and automated the kubeconfig creation like docuemnted on this Blog.
https://betterprogramming.pub/k8s-tips-give-access-to-your-clusterwith-a-client-certificate-dfb3b71a76fe

so this means for every Cluster we have one kubeconfig which are loaded in the $KUBECONFIG ENV Variable.

the login to the 1st Cluster is working fine. 
To all the others mostly we then have the Problem of "You must be logged in"

######-------------------------------------------------
gaedemi-shoot--aut8slzmrz--dev01
gaedemi-shoot--aut8slzmrz--infra
gaedemi@SIT-SMBP1818 ~ % kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
chartmuseum-7d5997c447-zjpwp           1/1     Running   0          4d15h
customer1-0                            1/1     Running   0          4d15h
gaedemi@SIT-SMBP1818 ~ % kubectx
gaedemi-shoot--aut8slzmrz--dev01
gaedemi-shoot--aut8slzmrz--infra
gaedemi@SIT-SMBP1818 ~ % kubectx gaedemi-shoot--aut8slzmrz--infra
Switched to context "gaedemi-shoot--aut8slzmrz--infra".
gaedemi@SIT-SMBP1818 ~ % kubectl get pods
error: You must be logged in to the server (Unauthorized)
#####-----------------------

we are using the same Cluseterrole, the same Rolebinding and also the same Way of approving the Certificate Signing Request.
We tested this with config in multiple config Files and also with merged configs in one File.
The Issue is the same.

Kind Regards
Michael Gäde

### What did you expect to happen?

create one ore more Configs to connect to each Cluster with a Client Certificate like documented on 
https://betterprogramming.pub/k8s-tips-give-access-to-your-clusterwith-a-client-certificate-dfb3b71a76fe

### How can we reproduce it (as minimally and precisely as possible)?

just try to connect to different Clusters like documented on the give nWebsite

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T13:12:04Z", GoVersion:"go1.18.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
</details>

### Cloud provider

<details>
STACKIT CLOUD
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

Darwin SIT-SMBP1818 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

/sig sig-cli

**Comment by sftim** [comment]
This sounds like a support request for help with [kubectx](https://github.com/ahmetb/kubectx); does that sound right?

**Comment by gaedemischwarz** [comment]
Hello sftim,

yes look like. i tested the Topic with a flattened File and the Problem is not occuring.

Kind  Regards Michael

**Comment by gaedemischwarz** [comment]
Issue in kubectx. not in kubectl

**Comment by gaedemischwarz** [comment]
look like it's still a Problem with kubectl and not with kubectx.


Hello Ahmet,

i am using for each Cluster one File. After adding different Files into a Folder and adding them each to the $KUBECONFIG

i needed to add the Client Key by executing the following Command.

$ kubectl config set-credentials $USER \
  --client-key=$HOME/.ssh/id_rsa \
  --embed-certs=true

to the first Cluster i am able to Connect. But not to the other ones which are in different Files.
The Issue on kubectx/kubects was closed, because they said it's not a kubectx Issue:

https://github.com/ahmetb/kubectx/issues/378

**Comment by brianpursley** [comment]
Are you using the same user name in multiple configs?

By this, I mean do each of your config files have a user named the same in the yaml file, like this?

Config File 1:
```
users:
- name: myuser
  user:
    client-certificate-data: ...
    client-key-data: ...
```

Config File 2:
```
users:
- name: myuser
  user:
    client-certificate-data: ...
    client-key-data: ...
```

... Instead of...

Config File 1:
```
users:
- name: myuser-1
  user:
    client-certificate-data: ...
    client-key-data: ...
```

Config File 2:
```
users:
- name: myuser-2
  user:
    client-certificate-data: ...
    client-key-data: ...
```

**Comment by brianpursley** [comment]
Can you post the output of `kubectl config view`?

And also post the output of `kubectl config view --kubeconfig=xxxxx`, where xxxxx is one of the configs for a cluster that is not working.

**Comment by gaedemischwarz** [comment]
Hello Brian,

yes it's the same user in the different configs.
here are the Config Files.

<img width="1340" alt="grafik" src="https://user-images.githubusercontent.com/94377108/210216646-7a856621-e064-416c-ac32-a628e7cb49b8.png">




and here is the output of kubectl config view. Please be aware some Cluster specific topics are removed. like the full DNS Name

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api-dev01.domain
  name: shoot---dev01
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api-infra.domain
  name: shoot---infra
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://api.-prd01.domain
  name: shoot---prd01
contexts:
- context:
    cluster: shoot---dev01
    user: gaedemi
  name: gaedemi-shoot---dev01
- context:
    cluster: shoot---infra
    user: gaedemi
  name: gaedemi-shoot---infra
- context:
    cluster: shoot---prd01
    user: gaedemi
  name: gaedemi--prd01
current-context: gaedemi-shoot---infra
kind: Config
preferences: {}
users:
- name: gaedemi
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED

**Comment by brianpursley** [comment]
If you use a different user name in each config file, does it work?

* user--dev01
* user--infra
* user--prd01

**Comment by gaedemischwarz** [comment]
Hello Brian,

yes with different username everything is working fine. Look like the  kubectl config set-credentials is not handling same user in different Config Files.

can i  open a Feature Request for the Topic set credentials in different Config Files with kubectl?

kind Regards
Michael Gäde

**Comment by brianpursley** [comment]
@gaedemischwarz sure, you can open a feature request.

At the very least it should probably print a better error message and/or a warning that the context you are using refers to a user which was not merged due to its name already existing in another config.
