### ISSUE TITLE
Pods keep being created by Deployment with match-all "NoSchedule" toleration until node shutdown when using graceful node shutdown

### ISSUE THREAD

**Issue by jiuchen1986** [kubernetes/kubernetes#114729]
### What happened?

When graceful node shutdown is triggered, kubelet will taint the node with "not-ready", set "spec.unschedulable" to true, and set running pods' phase to "Failed" (I'm using 1.23.6 and 1.24 where the phase will be set to "Failed" according to https://github.com/kubernetes/kubernetes/pull/106900).

Meanwhile, the shutdown manager also will reject any new pod with "Failed" phase which is scheduled to the node due to the code I believe at https://github.com/kubernetes/kubernetes/blob/release-1.24/pkg/kubelet/nodeshutdown/nodeshutdown_manager_linux.go#L143-L154.

With above behavior, if a controller instance like Deployment with match-all "NoSchedule" toleration (toleration without setting the key), the Deployment will create a new pod once the old one is set to "Failed" and the scheduler may still schedule the new pod to the node being shutting down because of the toleration. As the kubelet rejects the new coming pod and also set its phase to "Failed", the former procedure just repeats leading to a lot of rejected pods being created until node truly shutdown. And we know those pods will stay until garbage collection or other entity kick-in to clean up.

This may leave a certain way to exhaust the cluster resource as the pod creating can be much faster than cleaning up.

### What did you expect to happen?

(Since this) I'm aware of that have a match-all "NoSchedule" toleration on things like Deployment is a bad idea but sometimes it can just happen. And I also know there is back-and-forth discussion on whether the phase should be set to "Failed" on the pod during graceful node shutdown (https://github.com/kubernetes/kubernetes/issues/104531) and there is still work ongoing (https://github.com/kubernetes/kubernetes/issues/108991).

Our case is we still need the new pod instance can be created after node reboot (so completed pod staying forever is not fine for us either), but at the same time hope it won't be scheduled to the same node being shutting down. I think the thing is that scheduler's logic always respects taints and tolerations but kubelet doesn't in this case.

So the best wish is that scheduler can be smart enough never schedule a new pod to the node being shutting down (of cause when graceful node shutdown is applied) regardless of what toleration the pod has. If this is impossible, I wish at least kubelet also subjects to the toleration as scheduler does similar to when the node is cordoned.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a deployment with a match-all "NoSchedule" toleration (and probably as many replicas as the number of nodes). Do "systemctl reboot" on a node with "GracefulNodeShutdown" enabled. Make sure it will take long enough time like minutes for node to shutdown.

### Kubernetes version

<details>

```console
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"60d6794382fe229fcf97000e8175c0315ebe8863", GitTreeState:"clean", BuildDate:"2022-09-09T08:41:07Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"60d6794382fe229fcf97000e8175c0315ebe8863", GitTreeState:"clean", BuildDate:"2022-09-09T08:30:58Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
on-premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux node-10-158-32-30 5.4.0-70-generic #78~18.04.1-Ubuntu SMP Sat Mar 20 14:10:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm 1.24.2
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd github.com/containerd/containerd v1.6.6 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
not related
</details>

**Comment by sftim** [comment]
For the case of a cluster where there are no healthy nodes, we _could_ have an out-of-tree addon that sets a [Pod scheduling readiness](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) gate on all Pods, pending the appearance of at least one healthy node. This would in theory avoid hammering the scheduler. However, in practice it may not work because the cluster isn't healthy and the add-on may therefore not be running as intended.

However, I have a different idea: emit a [warning](https://kubernetes.io/blog/2020/09/03/warnings/) when someone creates a Deployment that tolerates any taint for Pod scheduling, to inform the client and its end-user that this is not good practice.
Similarly, we could warn when someone creates a Deployment that tolerates either `node.kubernetes.io/not-ready` or `node.kubernetes.io/unschedulable`, with no toleration period set, or if they modify an existing Deployment to add such a toleration.

**Comment by sftim** [comment]
Actually, we could even provide some sample ValidatingAdmissionPolicies, including a ValidatingAdmissionPolicy that **denies** creating a tolerate-anything Pod or Pod template. Maybe with an exception for `kube-system`.

If ValidatingAdmissionPolicies move to beta, that could be an effective way to avoid this situation: if you cannot produce a tolerates-anything Deployment, then that means such a Deployment cannot hammer the scheduler.

**Comment by jiuchen1986** [comment]
> Actually, we could even provide some sample ValidatingAdmissionPolicies, including a ValidatingAdmissionPolicy that **denies** creating a tolerate-anything Pod or Pod template. Maybe with an exception for `kube-system`.
> 
The validating admission makes sense here. And glad to hear that "Maybe with an exception for `kube-system`" which actually represents our case. We provide clusters to our users who are allowed actually to taint nodes on-demand. This leads to some cases that those system-level shared components can't be scheduled. This is why we put a "all-match" toleration on them. It turns out DaemonSet has no problem, but Deployment really is not good at it.

I've also been thinking a more enriched toleration syntax like the `matchExpression` would offer more flexibility.

**Comment by SergeyKanzhelev** [comment]
/cc @joelsmith 

From node side the question may be whether we need a special taint for termination stage so one can tolerate everything except the termination stage. @jiuchen1986 is it something you are looking for?

/remove-kind bug
/kind feature

**Comment by jiuchen1986** [comment]
> /cc @joelsmith
> 
> From node side the question may be whether we need a special taint for termination stage so one can tolerate everything except the termination stage. @jiuchen1986 is it something you are looking for?
> 
> /remove-kind bug /kind feature

For this case, yes, that will work. I don't know the history though, why does the scheduler deem `.spec.unschedulable` in the node object equivalent to the `node.kubernetes.io/unschedulable` taint. And this is not mentioned in the document https://kubernetes.io/docs/reference/scheduling/config/#scheduling-plugins

**Comment by jiuchen1986** [comment]
One more question, why'd we give kubelet power to reject a pod scheduled without scheduler knowing that? Should we either let kubelet always accepts scheduler's decision or make scheduler know there's a kubelet doesn't want any pods so phase it out (similar to the feature @SergeyKanzhelev mentioned)?
