### ISSUE TITLE
ServiceAccount creating Secret Object by default for version greater than v1.22

### ISSUE THREAD

**Issue by surajgautam** [kubernetes/kubernetes#114799]
### What happened?

As per the change log mentioned [here](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes), Secret API objects are no longer auto-generated for ServiceAccount. But, when I created ServiceAccount, it created secret object automatically.

Command Used (default namespace):

`kubectl create serviceaccount myapp-sa`

`kubectl get secret`
```Output:
myapp-sa-token-c779s                 kubernetes.io/service-account-token   3      15m
```

I am using kubernetes inside minikube in my ubuntu machine.

### What did you expect to happen?

As per the change logs, the secret object shouldn't have been created automatically.

### How can we reproduce it (as minimally and precisely as possible)?

With the same version as above, create the new service account.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube in local
</details>

### OS version

<details>

```console

$ cat /etc/os-release
NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
$ uname -a
Linux surajgautam 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by surajgautam** [comment]
> /sig release

**Comment by pacoxu** [comment]
/sig auth
/remove-sig apps architecture release
I think you refer to https://github.com/kubernetes/kubernetes/pull/108309 LegacyServiceAccountTokenNoAutoGeneration to beta.

> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

As your information shows, you are using Kubernetes v1.23 and LegacyServiceAccountTokenNoAutoGeneration is beta in v1.24, the behavior is expected. You may have to upgrade to v1.24+ to get this feature.

**Comment by sftim** [comment]
/triage not-reproducible

LegacyServiceAccountTokenNoAutoGeneration was not available before Kubernetes v1.24

**Comment by Shubham82** [comment]
@surajgautam,  from k8s v1.24  `LegacyServiceAccountTokenNoAutoGeneration` feature gate, is enabled by default, so what @pacoxu said above is right. it is not a bug.
Please see the [Urgent Upgrade Notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#urgent-upgrade-notes) for CHANGELOG-1.24.

**Comment by Shubham82** [comment]
closing this issue, as functionality work as expected.
Please re-open this issue if you have any concerns regarding this.

/close
