### ISSUE TITLE
An error occurred while trying to deploy 1.26 kubelet.service

### ISSUE THREAD

**Issue by imaxun** [kubernetes/kubernetes#114715]
### What happened?

![image](https://user-images.githubusercontent.com/29112991/209647436-b5a30af8-3c35-4605-87c6-ef3b09012a1b.png)
![image](https://user-images.githubusercontent.com/29112991/209647466-01be7ce3-457d-48d3-ac49-18705c171c3e.png)
![image](https://user-images.githubusercontent.com/29112991/209647487-df7c1157-60d9-48eb-90a7-1c5588487336.png)
![Uploading image.png…]()

### What did you expect to happen?

希望得到帮助

### How can we reproduce it (as minimally and precisely as possible)?

希望得到帮助

### Kubernetes version

kubectl version 1.26

### Cloud provider

qcloud

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by imaxun** [comment]
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Comment by aojea** [comment]
you should post the issues in english, or use some translator to do that

**Comment by pacoxu** [comment]
/kind support
The current screenshot cannot show the root cause.
- You have not mentioned `Install tools` that you are using  and the steps to reproduce the problem.
- and also no kubelet configurations and enough kubelet logs.

**Comment by imaxun** [comment]
This is the full log：

etcd,etcd-readiness,informer-sync,poststarthook/start-apiextensions-controllers,poststarthook/crd-informer-synced,poststarthook/bootstrap-controller,poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes,poststarthook/priority-and-fairness-config-producer,poststarthook/apiservice-registration-controller,autoregister-completion check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]etcd failed: etcd client connection not yet established
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]etcd-readiness failed: etcd client connection not yet established
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]informer-sync failed: 23 informers not started yet: [*v1.Endpoints *v1.IngressClass *v1.ServiceAccount *v1.Node *v1.PersistentVolume *v1.Role *v1.Service *v1.ClusterRole *v1.StorageClass *v1.VolumeAttachment *v1beta3.FlowSchema *v1.ValidatingWebhookConfiguration *v1.RuntimeClass *v1.Pod *v1.ClusterRoleBinding *v1.ResourceQuota *v1.PriorityClass *v1.MutatingWebhookConfiguration *v1.RoleBinding *v1beta3.PriorityLevelConfiguration *v1.Secret *v1.Namespace *v1.LimitRange]
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/start-apiextensions-controllers failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/crd-informer-synced failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/bootstrap-controller failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/priority-and-fairness-config-producer failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/apiservice-registration-controller failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]autoregister-completion failed: missing APIService: [v1. v1.admissionregistration.k8s.io v1.apiextensions.k8s.io v1.apps v1.authentication.k8s.io v1.authorization.k8s.io v1.autoscaling v1.batch v1.certificates.k8s.io v1.coordination.k8s.io v1.discovery.k8s.io v1.events.k8s.io v1.networking.k8s.io v1.node.k8s.io v1.policy v1.rbac.authorization.k8s.io v1.scheduling.k8s.io v1.storage.k8s.io v1beta1.storage.k8s.io v1beta2.flowcontrol.apiserver.k8s.io v1beta3.flowcontrol.apiserver.k8s.io v2.autoscaling]
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.348457    5327 controller.go:615] quota admission added evaluator for: leases.coordination.k8s.io
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.400832    5327 cache.go:39] Caches are synced for APIServiceRegistrationController controller
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.401443    5327 shared_informer.go:280] Caches are synced for cluster_authentication_trust_controller
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.401067    5327 cache.go:39] Caches are synced for AvailableConditionController controller
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.401135    5327 shared_informer.go:280] Caches are synced for node_authorizer
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.403313    5327 shared_informer.go:280] Caches are synced for configmaps
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.403315    5327 apf_controller.go:366] Running API Priority and Fairness config worker
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.403651    5327 apf_controller.go:369] Running API Priority and Fairness periodic rebalancing process
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.403336    5327 cache.go:39] Caches are synced for autoregister controller
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.403995    5327 apf_controller.go:846] Introducing queues for priority level "leader-election": config={"type":"Limited","limited":{"nominalConcurrencyShares":10,"limitResponse":{"type":"Queue","queuing":{"queues":16,"handSize":4,"queueLengthLimit":50}},"lendablePercent":0}}, nominalCL=25, lendableCL=0, borrowingCL=600, currentCL=25, quiescing=false (shares=10, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404060    5327 apf_controller.go:846] Introducing queues for priority level "node-high": config={"type":"Limited","limited":{"nominalConcurrencyShares":40,"limitResponse":{"type":"Queue","queuing":{"queues":64,"handSize":6,"queueLengthLimit":50}},"lendablePercent":25}}, nominalCL=98, lendableCL=25, borrowingCL=600, currentCL=86, quiescing=false (shares=40, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404090    5327 apf_controller.go:846] Introducing queues for priority level "system": config={"type":"Limited","limited":{"nominalConcurrencyShares":30,"limitResponse":{"type":"Queue","queuing":{"queues":64,"handSize":6,"queueLengthLimit":50}},"lendablePercent":33}}, nominalCL=74, lendableCL=24, borrowingCL=600, currentCL=62, quiescing=false (shares=30, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404102    5327 apf_controller.go:846] Introducing queues for priority level "workload-high": config={"type":"Limited","limited":{"nominalConcurrencyShares":40,"limitResponse":{"type":"Queue","queuing":{"queues":128,"handSize":6,"queueLengthLimit":50}},"lendablePercent":50}}, nominalCL=98, lendableCL=49, borrowingCL=600, currentCL=74, quiescing=false (shares=40, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404124    5327 apf_controller.go:846] Introducing queues for priority level "workload-low": config={"type":"Limited","limited":{"nominalConcurrencyShares":100,"limitResponse":{"type":"Queue","queuing":{"queues":128,"handSize":6,"queueLengthLimit":50}},"lendablePercent":90}}, nominalCL=245, lendableCL=221, borrowingCL=600, currentCL=135, quiescing=false (shares=100, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404141    5327 apf_controller.go:854] Retaining queues for priority level "catch-all": config={"type":"Limited","limited":{"nominalConcurrencyShares":5,"limitResponse":{"type":"Reject"},"lendablePercent":0}}, nominalCL=13, lendableCL=0, borrowingCL=600, currentCL=600, quiescing=false, numPending=0 (shares=5, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404162    5327 apf_controller.go:846] Introducing queues for priority level "global-default": config={"type":"Limited","limited":{"nominalConcurrencyShares":20,"limitResponse":{"type":"Queue","queuing":{"queues":128,"handSize":6,"queueLengthLimit":50}},"lendablePercent":50}}, nominalCL=49, lendableCL=25, borrowingCL=600, currentCL=37, quiescing=false (shares=20, shareSum=245)
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404195    5327 apf_controller.go:444] "Update CurrentCL" plName="workload-high" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=114 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404285    5327 apf_controller.go:444] "Update CurrentCL" plName="workload-low" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=56 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404350    5327 apf_controller.go:444] "Update CurrentCL" plName="catch-all" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=30 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404380    5327 apf_controller.go:444] "Update CurrentCL" plName="global-default" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=56 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404456    5327 apf_controller.go:444] "Update CurrentCL" plName="leader-election" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=58 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404478    5327 apf_controller.go:444] "Update CurrentCL" plName="node-high" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=170 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.404517    5327 apf_controller.go:444] "Update CurrentCL" plName="system" seatDemandHighWatermark=0 seatDemandAvg=0 seatDemandStdev=0 seatDemandSmoothed=0 fairFrac=2.3333333333333335 currentCL=117 backstop=false
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.406996    5327 genericapiserver.go:484] MuxAndDiscoveryComplete has all endpoints registered and discovery information is complete
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.415571    5327 shared_informer.go:280] Caches are synced for crd-autoregister
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.447480    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.546711    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.646426    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.746794    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.846874    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: I1229 15:07:07.946659    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:07 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.046478    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.055863    5327 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.146659    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.246785    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.304925    5327 storage_scheduling.go:111] all system priority classes are created successfully or already exist.
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: I1229 15:07:08.346303    5327 healthz.go:261] poststarthook/rbac/bootstrap-roles check failed: readyz
Dec 29 15:07:08 qcloud-host01 kube-apiserver[5327]: [-]poststarthook/rbac/bootstrap-roles failed: not finished

**Comment by pacoxu** [comment]
> `etcd failed: etcd client connection not yet established`

Does etcd pod started correctly?

**Comment by imaxun** [comment]
etcd started normally
