### ISSUE TITLE
Found some FIXME in validatingadmissionpolicy testing file

### ISSUE THREAD

**Issue by dipankardas011** [kubernetes/kubernetes#114726]
https://github.com/kubernetes/kubernetes/blob/7eb9a75bf914428e7579d2497722f71be3ef1812/staging/src/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/admission_test.go#L255

https://github.com/kubernetes/kubernetes/blob/7eb9a75bf914428e7579d2497722f71be3ef1812/staging/src/k8s.io/apiserver/pkg/admission/plugin/validatingadmissionpolicy/admission_test.go#L260

**Comment by dipankardas011** [comment]
Just wanted to know to can i help in resolving the error handling?

**Comment by pacoxu** [comment]
added in #113314 
/cc @cici37 
/sig api-machinery

**Comment by fedebongio** [comment]
/assign @cici37 @jpbetz @tallclair 
@dipankardas011 you are always welcome to help if you want to try to solve this and send a PR

/triage accepted

**Comment by jiahuif** [comment]
/@assign @DangerOnTheRanger @alexzielenski

**Comment by dipankardas011** [comment]
> /assign @cici37 @jpbetz @tallclair 
> @dipankardas011 you are always welcome to help if you want to try to solve this and send a PR
> 
> /triage accepted
> 

Sure will try to solve it ✌️

**Comment by dipankardas011** [comment]
can anyone suggest resources for this Issue as I am new to the testing of admission policy

some guidance will surely help 😄

**Comment by DangerOnTheRanger** [comment]
> can anyone suggest resources for this Issue as I am new to the testing of admission policy
> 
> some guidance will surely help 😄

I think both `panic` calls can simply be replaced with `t.Fatalf` and a more helpful error message. Feel free to raise a PR, I'll take care of reviewing it.

**Comment by dipankardas011** [comment]
> > can anyone suggest resources for this Issue as I am new to the testing of admission policy
> > 
> > some guidance will surely help 😄
> 
> I think both `panic` calls can simply be replaced with `t.Fatalf` and a more helpful error message. Feel free to raise a PR, I'll take care of reviewing it.

Thanks for upfront help
