### ISSUE TITLE
HA for kube-dns

### ISSUE THREAD

**Issue by parikhyash** [kubernetes/kubernetes#11471]
I recently ran into an issue on my cluster because kube-dns unexpectedly went down.

The only error I saw was "2015/07/08 23:18:23 etcdhttp: unexpected error: etcdserver: request timed out"

I'm guessing etcd went down and recovered on its own. However, during this time, I was unable to launch any topologies at all on my cluster which leads me to thinking about some way to make the system more resilient. There are 2 solutions I could think of and wanted to know which one (if any) would be better.

1. Launch the kube-dns RC with replicas=2
 - The service launched using skydns-svc.yaml would listen to both replicas
 - If either of kube2sky or etcd go down, then the other replica could be used
 - However, would there issues regarding consistency across the two etcd containers in different pods? Would the entries across all replicas be the same or are there inconsistencies for a short duration?

2. Replication at the storage layer (multiple etcd's)
 - Modify the skydn-rc.yaml file to have etcd in a separate pod and make more replicas of etcd only (these containers would be in the same pod though).
 - If one etcd goes down, skydns can serve requests from another etcd container.
 - However, if kube2sky goes down, new entries won't be written to etcd. Requests can still be served though.

Also, what is the HA story for skydns?

@ArtfulCoder @thockin

**Comment by thockin** [comment]
The simplest answer (and arguably we should have started there) is to run
N=2 or N=3 DNS servers.  We can add a readiness check that prevents failed
instances from joining the set.

PRs welcome. :)
