### ISSUE TITLE
kube-apiserver error log

### ISSUE THREAD

**Issue by imaxun** [kubernetes/kubernetes#114735]
### What happened?

Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.304807    1146 shared_informer.go:280] Caches are synced for crd-autoregister
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.304845    1146 shared_informer.go:280] Caches are synced for cluster_authentication_trust_controller
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.306885    1146 genericapiserver.go:484] MuxAndDiscoveryComplete has all endpoints registered and discovery information is complete
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.311398    1146 shared_informer.go:280] Caches are synced for node_authorizer
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.339795    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.439507    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.539896    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.640026    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.739992    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.839222    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.939077    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:20 qcloud-host01 kube-apiserver[1146]: I1229 14:46:20.989485    1146 controller.go:132] OpenAPI AggregationController: action for item k8s_internal_local_delegation_chain_0000000000: Nothing (removed from the queue).
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: I1229 14:46:21.039062    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: I1229 14:46:21.139741    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles,poststarthook/scheduling/bootstrap-system-priority-classes check failed: readyz
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/rbac/bootstrap-roles failed: not finished
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: [-]poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: I1229 14:46:21.209294    1146 storage_scheduling.go:111] all system priority classes are created successfully or already exist.
Dec 29 14:46:21 qcloud-host01 kube-apiserver[1146]: I1229 14:46:21.239351    1146 healthz.go:261] poststarthook/rbac/bootstrap-roles check failed: readyz

### What did you expect to happen?

hope to get help

### How can we reproduce it (as minimally and precisely as possible)?

hope to get help

### Anything else we need to know?

hope to get help

### Kubernetes version

kubectl version 1.26

### Cloud provider

qcloud

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug
/kind support

you have a problem with

> [-]poststarthook/rbac/bootstrap-roles 

most of the times this is an installation problem, you should check with the project you are using for installing the cluster
