### ISSUE TITLE
Add a Java EE sample

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/kubernetes#11477]
This will be based upon https://github.com/arun-gupta/kubernetes-java-sample.

I will send a PR for this.

**Comment by arun-gupta** [comment]
Can somebody assign the issue to me?

**Comment by erictune** [comment]
Github won't let us assign it to you.

**Comment by arun-gupta** [comment]
Hmm, do I need to join a team in order to be assignable?

**Comment by erictune** [comment]
I've asked around.  It seems that github only allows assigning issues to members of the GoogleCloudPlatform Organization.  It appears that Googlers can automatically add themselves to this Org, and that kubernetes project committers are also added, but I don't see a way to add you to the Org without making you a committer, which it is a bit soon to do.  Basically, I don't have the permission to add you to the Organization.  

I see that you are with Red Hat, and I definitely would like to add you, but I don't have permission.  I've asked someone who is an admin of the Organization how to add you.

**Comment by arun-gupta** [comment]
Thanks for the update!

Will send the PR in the meanwhile.

**Comment by erictune** [comment]
@arun-gupta you are now assigned to this issue.

**Comment by arun-gupta** [comment]
@erictune thanks, will go through the comments on PR and update it.

**Comment by arun-gupta** [comment]
@erictune I never removed my assignment from this issue. Any idea on what might have happened here?

Waiting for #12614 to be fixed before I can verify the instructions.

**Comment by mbforbes** [comment]
@mikedanese was the assignment removal because of the repo switch?

**Comment by erictune** [comment]
@arun-gupta  can you go to https://github.com/orgs/kubernetes/teams/kubernetes-collaborators and then ask to join that team?  That will allow us to assign you to the issue.

**Comment by mikedanese** [comment]
Likely because of the switch he was unassigned. This is resolved #12110 is merged.

**Comment by arun-gupta** [comment]
thanks @mikedanese, received the invite.
