### ISSUE TITLE
Opinionated label and annotation attachment in kubectl

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11485]
kubectl supports attaching arbitrary labels with --labels, at least on some commands. It should also support general annotation attachment and some specific opinionated labels and annotations, to help users learn recommended conventions, and as a scoping mechanism to increase config reusability.

Example flags could include (exact ones TBD):
- `--app=foo`
- `--tier={fe,cache,be,db}`
- `--env={dev,test,prod}`
- `--deployment=v1`
- `--description="my frontend service"`

**Comment by kargakis** [comment]
@kubernetes/sig-cli-misc @kubernetes/sig-apps-misc

**Comment by rikatz** [comment]
@bgrant0607 Do we still want to move forward with this? If so I can take the subject to next sig-cli meeting.

Thanks!

**Comment by bgrant0607** [comment]
@rikatz I suggest not. Recommended labels have been documented, and kustomize can be used to inject labels and annotations declaratively.

/remove-lifecycle frozen
/close
