### ISSUE TITLE
Monitor pod readiness and other health signals (restarts, etc.) during rolling update

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11484]
Right now, rolling update is oblivious to damage it might do. We should at least automatically pause the rollout when there's an obvious problem.

**Comment by nikhiljindal** [comment]
I can take this up

**Comment by nikhiljindal** [comment]
@ironcladlou is adding support for "readiness" check in rolling update in https://github.com/GoogleCloudPlatform/kubernetes/pull/11942. It waits for the new pods to be ready before bringing the old ones down.
Right now, it just keeps waiting for the new ones to come up. We can expand that to detect an error and return that to the user: https://github.com/GoogleCloudPlatform/kubernetes/pull/11942/files#r36014233, incase new ones dont come up even after a long time.

**Comment by bgrant0607** [comment]
We still need to surface this functionality through kubectl, AIUI.
