### ISSUE TITLE
kubeadm unit test requires root k8s.io/kubernetes/cmd/kubeadm/app/cmd/upgrade: TestEnforceRequirements/Fail_pre-flight_check 

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#114824]
### What happened?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/92316/pull-kubernetes-unit-experimental/1610708038858051584

```
{Failed  === RUN   TestEnforceRequirements/Fail_pre-flight_check
[upgrade/config] Making sure the configuration is correct:
[preflight] Running pre-flight checks.
    common_test.go:113: enforceRequirements returned unexpected error, expected: ERROR CoreDNSUnsupportedPlugins, got [preflight] Some fatal errors occurred:
        	[ERROR IsPrivilegedUser]: user is not running as root
        [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    --- FAIL: TestEnforceRequirements/Fail_pre-flight_check (0.00s)
}
```

### What did you expect to happen?

_unit_ tests should run without root.

This test should be refactored or otherwise removed from `make test`. `make test` should pass as an ordinary user. https://github.com/kubernetes/kubernetes/issues/99881

### How can we reproduce it (as minimally and precisely as possible)?

run `cmd/kubeadm/app/cmd/upgrade` tests as non-root

**Comment by neolit123** [comment]
@BenTheElder thanks for logging the issue.

@chendave this was changed in https://github.com/kubernetes/kubernetes/commit/2121ce17dacdd7d022b05fe6ec12d089dcf14cb4 so this root preflight test must be excluded.
