### ISSUE TITLE
Allow PreScore to return `Skip` status to skip running the corresponding Score extension

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#114827]
### What would you like to be added?

In some scheduler plugins, PreScore is implemented to pre-process state before running Score for each node. In some cases, PreScore can decide that Score shouldn't run at all (e.g., no relevant PodTopologySpread constraints), and so it will be useful to have an explicit way to communicate that.

### Why is this needed?

To potentially improve performance (likely negligible), but this also offer a better API (vs having each plugin communicate a special value internally)

/sig scheduling

**Comment by alculquicondor** [comment]
This is a follow up to #114125

**Comment by kidddddddddddddddddddddd** [comment]
Ummm... Do you need volunteers?

**Comment by alculquicondor** [comment]
/unassign
@sanposhiho is this something you would like to take or mentor on?

**Comment by sanposhiho** [comment]
I can work on the implementation on the framework side.

For each plugin's Skip implementation, we can ask for some volunteers like https://github.com/kubernetes/kubernetes/issues/114399 later.

/assign
/unassign @mwielgus

**Comment by kidddddddddddddddddddddd** [comment]
@sanposhiho Can I try this one?:) I think this change is similar to #114125 and I should be able to handle it. Ignore this if you've already started working, or think I'm wrong.

**Comment by sanposhiho** [comment]
@kidddddddddddddddddddddd 

Exactly, sure please work on the framework implementation side. 👍 Feel free to ping me if any help is needed.

/assign @kidddddddddddddddddddddd

**Comment by sanposhiho** [comment]
Created: https://github.com/kubernetes/kubernetes/issues/115745
