### ISSUE TITLE
[Flake Test] TestCreateHealthcheck

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#114852]
### Which jobs are flaking?

`pull-kubernetes-unit`

### Which tests are flaking?

TestCreateHealthcheck/ok_if_response_time_lower_than_custom_timeout 

### Since when has it been flaking?

From https://storage.googleapis.com/k8s-triage/index.html?test=TestCreateHealthcheck, since 12/23.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Anything else we need to know?

Test Log: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114653/pull-kubernetes-unit/1610998548210388992

### Relevant SIG(s)

/sig api-machinery

**Comment by brianpursley** [comment]
I looked at this today, and here is what I found:

The test has a `ready` chan that is supposed to wait for the connection to be established:
https://github.com/kubernetes/kubernetes/blob/510a85c53a5138babb1650fadd328e6f34baa03b/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory_test.go#L136-L138

The chan is closed when `newETCD3Client()` returns.
https://github.com/kubernetes/kubernetes/blob/510a85c53a5138babb1650fadd328e6f34baa03b/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/factory_test.go#L112-L115

However, in `newETCD3Check()`, it executes additional code after the call to `newETCD3Client()` returns, so even though the `ready` chan is closed, `clientErr` is not set to nil until line 177:
https://github.com/kubernetes/kubernetes/blob/f507bc255382b2e2095351053bc17e74f7100d35/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L159-L179

There is a mutex, but it is not locked until after the call to `newETCD3Client` returns.

Here is the race condition:  If you call the healthcheck func after read chan is closed, but before the mutex is locked, the healthcheck func will see `clientErr` is still set to "etcd client connection not yet established" and return it:
https://github.com/kubernetes/kubernetes/blob/f507bc255382b2e2095351053bc17e74f7100d35/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L209-L211

Thoughts on how to fix this?

Could it be as simple as moving `lock.Lock()` above the call to `newETCD3Client` on line 160?  I think that fixes the race condition, but could end up blocking an initial healthcheck call if `newETCD3Client` takes a long time to return (in the real world).

I thought of a few other approaches involving using a chan to signal when the etcd3 client connection REALLY is established, but I don't know if that would be of general interest or only something that would be used by the unit test.

**Comment by aojea** [comment]
good analysis

> // PollUntil always waits interval before the first run of 'condition'.
> // 'condition' will always be invoked at least once.

so, it will not change the err until 1 second, no?

```
 go wait.PollUntil(time.Second, func() (bool, error) { 
 	newClient, err := newETCD3Client(c.Transport) 
```

maybe we can PollInmidiate or account for that well-known second?

**Comment by liggitt** [comment]
seeing this flake pretty regularly - https://storage.googleapis.com/k8s-triage/index.html?test=TestCreateHealthcheck

**Comment by aojea** [comment]
@liggitt https://github.com/kubernetes/kubernetes/pull/119824
