### ISSUE TITLE
Leaked pod metadata across namespaces on preemption

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#114882]
### What happened?

When kube-scheduler does preemption and the PodDisruptionConditions feature gate is enabled, it might leak the namespace and name of a pod in a different namespace.

### What did you expect to happen?

While debuggability is important, this is too much information to give to an end user. This information could be just in logs, which are only accessible to administrators.

We could print the name of the pod only it's in the same namespace, but I don't think it's worth the complexity.

### How can we reproduce it (as minimally and precisely as possible)?

Have PodDisruptionConditions enabled and generate a case of preemption. The PodDisruption condition message in the preempted pod will have the name of the Pod.

### Kubernetes version

<details>

1.26+
</details>

### Cloud provider

<details>
any
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Huang-Wei** [comment]
@mimowo would you mind using this chance to add the preemptor pod's schedulerName in the message?

**Comment by mimowo** [comment]
> would you mind using this chance to add the preemptor pod's schedulerName in the message?

Yes, I added in the newly open PR, please review: https://github.com/kubernetes/kubernetes/pull/114914

**Comment by denkensk** [comment]
Do we also need to update the message in event?
https://github.com/kubernetes/kubernetes/blob/cf7a3c5bbbebf295a15b37f3e67ae0e2f4c7dd84/pkg/scheduler/framework/preemption/preemption.go#L381-L382

**Comment by mimowo** [comment]
Good question,  WDYT @alculquicondor @liggitt? It was like that since at least 1.19: 
https://github.com/kubernetes/kubernetes/blob/release-1.19/pkg/scheduler/framework/plugins/defaultpreemption/default_preemption.go#L603-L604

**Comment by liggitt** [comment]
> Do we also need to update the message in event?

yes, sounds like we should

**Comment by mimowo** [comment]
> > Do we also need to update the message in event?
> 
> yes, sounds like we should

Cool, I'm going to prepare a dedicated PR as this one might be cherry-picked for more releases, than the condition message PR.

**Comment by ahg-g** [comment]
can we close this?

**Comment by wmgroot** [comment]
This is the equivalent of not being given the name of your accuser in a court of law. :smile: 

Very frustrating for users in multi-tenant environments who are forced to work with the cluster administrators to identify why their pods were preempted.

**Comment by alculquicondor** [comment]
It might be ok for your multitenant use case not to expose this information, but you cannot speak for every user of kubernetes.

> Very frustrating for users in multi-tenant environments who are forced to work with the cluster administrators to identify why their pods were preempted.

Can you actually give more context? Why do users need to know the name of the preemptor? What would it change? The preemption would still happen. If there are some priorities that need to be adjusted, it shouldn't be on the users to set an arbitrary priority without consulting the administrators.

**Comment by alculquicondor** [comment]
/sig auth

As the SIG that suggested we hide this information from end-users.

**Comment by kerthcet** [comment]
One thing I thought weird here is we can preempt the pod but we can't know its name. 🤔

**Comment by grosser** [comment]
+1 for knowing who caused the pre-emption, it makes debugging bad deploys so much harder if we don't know

Also the [code](https://github.com/kubernetes/kubernetes/blame/f0dcf0614036d8c3cd1c9f3b3cf8df4bb1d8e44e/staging/src/k8s.io/client-go/tools/events/event_recorder.go#L88) seems to still have "Related" field set, but in the actual event that's gone, not sure what's up with that.
```
---
involvedObject:
  apiVersion: v1
  kind: Pod
  name: foo
  namespace: kube-system
kind: Event
message: Preempted by a pod on node ip-172-30-123-123.us-west-2.compute.internal
metadata:
  name: foo-tdfdt.177985f84016fce8
  namespace: kube-system
reason: Preempted
reportingComponent: ""
reportingInstance: ""
source:
  component: default-scheduler
type: Normal
```

**Comment by mimowo** [comment]
How about returning preemptor UID instead of name & namespace? It shouldn't leak anything important, unless the UIDs be set by users (can they?). Yet, this would give admins more info for debugging.

**Comment by alculquicondor** [comment]
@liggitt we need some guidance from sig-auth here.

**Comment by grosser** [comment]
uid sounds like a great compromise

**Comment by liggitt** [comment]
uid is certainly better than name/namespace, and is not user-assignable

**Comment by alculquicondor** [comment]
Opened #119866
