### ISSUE TITLE
Gorilla WebSocket has been archived

### ISSUE THREAD

**Issue by fatelei** [kubernetes/kubernetes#114836]
### What would you like to be added?

Replace wesocket package from gorila to
- https://github.com/nhooyr/websocket

### Why is this needed?

gorila websocket has been archived

**Comment by pacoxu** [comment]
/sig architecture
/area code-organization
/retitle Gorilla WebSocket has been archived

https://github.com/kubernetes/kubernetes/blob/293bf70916de8ef61d5f868f53959f1e15b3e091/hack/unwanted-dependencies.json#L17

**Comment by aojea** [comment]
@liggitt already has done an analysis of this IIRC, I think that we only had gorilla dependency for some tests

**Comment by dims** [comment]
Here: https://github.com/kubernetes/kubernetes/pull/114408
