### ISSUE TITLE
two masters not ready because of the below error Unable to register node "node name" with API server: nodes is forbidden: User "system:anonymous" cannot create resource "nodes" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by Mohamed2assem** [kubernetes/kubernetes#114813]
### What happened?

we have setup with three masters node and we got suddenly two masters node went not ready and we can see some issues on the kubelet 
Unable to register node "node name" with API server: nodes is forbidden: User "system:anonymous" cannot create resource "nodes" in API group "" at the cluster scope

kubelet[11429]: E0104 14:08:35.176102   11429 kubelet.go:2243] node "node name" not found

### What did you expect to happen?

the master node be on ready state 

### How can we reproduce it (as minimally and precisely as possible)?

we restart the kubelet and the whole node and it same result 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:28:09Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</details>


### Cloud provider

<details>
on primes setup 
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
The End Of Life Date of v1.20.2 is 2022-02-28. See https://kubernetes.io/releases/patch-releases/.
