### ISSUE TITLE
 Checkpoint Restoration Failing in kubeadm and minikube

### ISSUE THREAD

**Issue by ContainerCheckpointfalse** [kubernetes/kubernetes#114805]
### What happened?

Unable to checkpoint a nginx container even after following all the prereq steps. 

Followed this blog [Forensic container checkpointing in Kubernetes | Kubernetes](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/)

### What did you expect to happen?

Steps taken for enabling checkpoint

Enabled feature gates in all three components of k8s
Checked manifests file .They are enabled
`root@kubemaster:/etc/kubernetes/manifests# grep -E 'feature-gates' *.yaml`

> kube-apiserver.yaml: - --feature-gates=ContainerCheckpoint=true
> kube-controller-manager.yaml: - --feature-gates=ContainerCheckpoint=true
> kube-scheduler.yaml: - --feature-gates=ContainerCheckpoint=true

2)Enabled enable_criu_support and drop_infra_ctr
`root@kubemaster:/etc/crio# grep -E 'enable_criu_support = true|drop_infra_ctr = false' *.conf
`
> drop_infra_ctr = false
> enable_criu_support = true

3)Ensure nodes are using crio 1.25 and k8s 1.25

`root@kubemaster:/# kubectl get no -o wide`

> NAME STATUS ROLES AGE VERSION INTERNAL-IP EXTERNAL-IP OS-IMAGE KERNEL-VERSION CONTAINER-RUNTIME
> kubemaster Ready control-plane 28m v1.25.0 192.168.56.2 Ubuntu 22.04.1 LTS 5.15.0-56-generic cri-o://1.25.0

### How can we reproduce it (as minimally and precisely as possible)?

Steps to replicate

> Spinned up ubuntu 22.04 LTS on virtual box 

`sudo minikube start --force --feature-gates=ContainerCheckpoint=true --install-addons=true  --container-runtime=cri-o --network-plugin=cni --vm-driver=docker --apiserver-ips 127.0.0.1 --apiserver-name localhost`

updated crio.conf file in crio folder and verified

Created nginx pod
`kubectl run webserver --image=nginx -n default`

Tried to checkpoint it

Kubeadm 

```
curl -sk -X POST  "https://localhost:10250/checkpoint/default/webserver/webserver" \
   --key /etc/kubernetes/pki/apiserver-kubelet-client.key \
   --cacert /etc/kubernetes/pki/ca.crt \
   --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt

```

Minikube
`curl -sk -X POST  "https://localhost:10250/checkpoint/default/webserver/webserver" \  --cert ~/.minikube/profiles/minikube/client.crt --key ~/.minikube/profiles/minikube/client.key 
`
Getting the Same error

> checkpointing of default/webserver/webserver failed (rpc error: code = Unknown desc = checkpoint/restore support not available)

Tried similar setup in kubeadm and facing the exact same issue

### Anything else we need to know?

Are there any other pre req? I seem to have covered all of them.

### Kubernetes version

<details>

```console
$ kubectl version
Kubernetes version: 1.25

```

</details>

### Cloud provider

<details>
Cloud being used: bare-metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
22.04.1 LTS(ubuntu/jammy64)
```

</details>

### Install tools

<details>
Installation method: Kubeadm and minikube
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI and version: cri-o v1.25.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI and version: Calico v3.24.0. (for my Kubeadm setup)
</details>

**Comment by ContainerCheckpointfalse** [comment]
cc: @adrianreber Am i missing something here ?

**Comment by adrianreber** [comment]
The error message comes from CRI-O. So it seems the CRIU support in CRI-O was not correctly enabled. Do you have a log from CRI-O? You should see a message like this:
```
DEBU[2023-01-04 10:54:05.655244620Z] Using criu from $PATH: /usr/local/sbin/criu   file="config/config.go:1298"
INFO[2023-01-04 10:54:05.655277912Z] Checkpoint/restore support enabled            file="config/config.go:1068"
```

**Comment by adrianreber** [comment]
That looks correct. Everything looks correct. Looking at the code the error message you get exist only at one location in the code and only happens if the CRIU binary is not found. Your log says something else. So it does not really make sense what is happening here. I never used minikube so maybe it uses another instance of CRI-O. Could that be? 1.25.0 is good enough.

Do you see any other output in your crio log file once Kubernetes is running?

The next problem, if you use CRIU from Ubuntu, they packaged a broken version, so you need to update CRIU to a newer version once you are to solve this initial error.

**Comment by SergeyKanzhelev** [comment]
/triage needs-information
/cc @haircommander 

Can you please try with non-broken version of CRI-O and report back. Thank you!

**Comment by crypticDAGGER** [comment]
I was facing a similar issue when I tried checkpointing with kubeadm . Everything seemed to be installed and configured correctly .
The issue was 
[Failed to create existing container](https://github.com/cri-o/cri-o/issues/5490)
Each time i requested the kubectl api to checkpoint my container the above error would be logged multiple times followed by

> checkpointing of default/webserver/webserver failed (rpc error: code = Unknown desc = checkpoint/restore support not available)

After this workaround [stop all pods and Restart](https://github.com/cri-o/cri-o/issues/5490#issuecomment-999835173), I was able to checkpoint without any issues.
The error isnt related to criu or its usage in k8s i presume.

**Comment by adrianreber** [comment]
@crypticDAGGER thanks for that information

**Comment by ContainerCheckpointfalse** [comment]
@crypticDAGGER Thanks this fixed the issue for me.

**Comment by Carol-code2222** [comment]
I have a question. Can you answer it for me?
When I run the conmmand `curl -sk -X POST "https://localhost:10250/checkpoint/default/nginx/nginx"`  on the node, it needs to add `--key` and `--cert`, but where do I get this certificate?

1. In the official document `https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/`, the `key` and `cert` are `/var/run/kubernetes/client-admin.key` and `/var/run/kubernetes/client-admin.crt`, but the two files do not exist on the node of the Kubernetes cluster.

2. According to your description, 
`curl -sk -X POST "https://localhost:10250/checkpoint/default/webserver/webserver" \
--key /etc/kubernetes/pki/apiserver-kubelet-client.key \
--cacert /etc/kubernetes/pki/ca.crt \
--cert /etc/kubernetes/pki/apiserver-kubelet-client.crt`
On the node, only `/etc/kubernetes/pki/ca.crt` exists, but `/etc/kubernetes/pki/apiserver-kubelet-client.crt` and `/etc/kubernetes/pki/apiserver-kubelet-client.key` do not exist. Correspondingly, `apiserver-kubelet-client.crt` and `apiserver-kubelet-client.key` exist only on the master node.

The Kubernetes version is 1.25.4. Where should I get the key and cert?
