### ISSUE TITLE
container_fs_usage_bytes metrics still has no data on containerd

### ISSUE THREAD

**Issue by vsxen** [kubernetes/kubernetes#114833]
### What happened?

`container_fs_xxx` metrics still has no data on containerd,

Setting `PodAndContainerStatsFromCRI=true` is also not work,but `crictl stats`is ok 

### What did you expect to happen?

The container_fs_usage_bytes metric has data.

### How can we reproduce it (as minimally and precisely as possible)?

init a k8s cluster use kubeadm

### Kubernetes version

<details>

```console
kubectl version 1.24.8
contained 1.5.11
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/assign @qiutongs 

@qiutongs can you please de-dup this issue and suggest a workaround?

**Comment by SergeyKanzhelev** [comment]
Unfortunately this is still the latest update we have: https://github.com/kubernetes/kubernetes/issues/89903#issuecomment-1044978911

@bobbypage in case a switch to CRI metrics will help

/close

**Comment by bobbypage** [comment]
> @bobbypage in case a switch to CRI metrics will help

Yes, long term switch to CRI metrics should address this.

**Comment by vsxen** [comment]
So which k8s version fixes this bug? or use CRI-O?
