### ISSUE TITLE
kubectl --dry-run

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11488]
kubectl should support a --dry-run option for every mutation to show what it would do, without actually doing it

We might need API changes in order to make this high-fidelity. For instance, if we wanted to know what a pod config would look like after admission control populated defaults, we'd need to execute most of the creation path.

**Comment by smarterclayton** [comment]
For generator types commands, I think there is a usability argument that the default when a user specifies `-o *` should be to dry-run (and a user should be allowed to override that with `--dry-run=false`).  I think I'd rather encourage composition of commands (pipe) than every generator command in the system creating objects.  We may also want to clarify dry-run against the server vs dry run against the client - there are lots of places where we want to generate locally to a file or an editor or a pipe command before we want to create it.  

At this point, OpenShift has a few commands that treat -o * as "dry-run" - new-app (complex generator) and export (never expect to send it to the server).  We also have a few that are designed to be compositional in a pipe *always* - process (take a template and turn it into a list of api objects), which never creates the objects for you (you have to pipe to `create -f -`).

I'm somewhat partial to having  `kubectl expose` and `kubectl run` should support the `-o` changing the default of `dry-run` to true, because that's more common and easier than having to set `--dry-run=true` and `-o yaml`.  The counter argument is that `--dry-run` is the preferred action, and `-o` is format only - except that by definition --dry-run using the default output format isn't very useful (you created a service named foo and an rc named bar).

**Comment by jonmoter** [comment]
:+1: for this feature.  In particular, I would like an ability to validate an object definition separate from actually creating the object.

e.g. running `kubectl --validate=true --dry-run -f pod.yml` at the validation step of my deployment pipeline.

**Comment by bgrant0607** [comment]
I agree that the validation use case is important.

I would distinguish --dry-run from --local. The former would still entail contacting the server and returning the result of the mutation. The latter would imply that only local information were used.

**Comment by hurf** [comment]
@bgrant0607 - I'm planning to add a parameter `dryrun` like 'pretty' or 'labelselector' to API requests. Once the server get this parameter, it will do validation to the resource and check if request can pass admission controls, but return success before write to etcd.
I've read the documented about API changing, it lists some principles when changing the api object, but parameters are not mentioned. Is there anything need to be taken special care of when adding a parameter?

**Comment by liggitt** [comment]
We need to be careful about dry-run with admission control... some admission controllers (like quota, specifically), record things to etcd in the process of admitting an object. Also, dry-run wouldn't work with a list of objects intended to be created in order, where later objects reference earlier objects (and those references are validated at create time)

**Comment by smarterclayton** [comment]
We could potentially carry "dry run" down into the admission controller
request path.

However, a query parameter may not be appropriate, instead there's probably
a HTTP header that already covers this. We try not to mix query parameters
and post bodies in many cases.

On Tue, Sep 8, 2015 at 7:47 AM, Jordan Liggitt <notifications@github.com>
wrote:

> We need to be careful about dry-run with admission control... some
> admission controllers (like quota, specifically), record things to etcd in
> the process of admitting an object. Also, dry-run wouldn't work with a list
> of objects intended to be created in order, where later objects reference
> earlier objects (and those references are validated at create time)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/11488#issuecomment-138529638>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by hurf** [comment]
@liggitt - Thanks for advices! I'm trying to make myself thoroughly familar with request handling process. And during this period, I may need more of your help. I think I've replied this message before but unfortunately it's not showed up here:-(

@smarterclayton - Can you provide a link to the code about the HTTP header? Thanks!

**Comment by smarterclayton** [comment]
This feels like a variant of an `Accept` header with a sub parameter -
possibly `Accept: application/json; dry-run` or possibly content-type
`Content-Type: application/json; verify`.

On Tue, Sep 8, 2015 at 8:34 PM, Victor HU <notifications@github.com> wrote:

> @liggitt <https://github.com/liggitt> - Thanks for advices! I'm trying to
> make myself thoroughly familar with request handling process. And during
> this period, I may need more of your help. I think I've replied this
> message before but unfortunately it's not showed up here:-(
>
> @smarterclayton <https://github.com/smarterclayton> - Can you provide a
> link to the code about the HTTP header? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/11488#issuecomment-138739502>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by dcowden** [comment]
+1 for this. My use case is to understand the difference between a stack file and an existing cluster, but this command would be a substitute.

**Comment by janetkuo** [comment]
@kubernetes/kubectl

**Comment by philidem** [comment]
It looks like support for `kubectl --dry-run` has been added. I think this issue can be closed.

**Comment by kargakis** [comment]
We still need to make `dry-run` touch the server, or at least decide that we don't want to.

**Comment by adohe** [comment]
@kargakis you mean move `dry-run` server side?

**Comment by ahmetb** [comment]
@garethr has just released kubeval: https://github.com/garethr/kubeval. From [his email](https://groups.google.com/forum/#!topic/kubernetes-sig-apps/G3MMHzpJisk) to sig-apps mailing list:

```
kubeval my-invalid-rc.yaml a-deployment.yaml 
kubeval -v 1.6.6 my-deployment.yaml 
kubeval --openshift -v 1.5.1 my-deployment.yaml 
```

I am not sure if it validates the values and  other constraints checked on the server-side. Just leaving it here as it might be relevant to the feature discussion. (h/t briangrant for pointing this out).

**Comment by apelisse** [comment]
> However, a query parameter may not be appropriate, instead there's probably
a HTTP header that already covers this. We try not to mix query parameters
and post bodies in many cases.

@smarterclayton Do you remember why you said that? I'm trying to understand ...

**Comment by apelisse** [comment]
This is now beta.
