### ISSUE TITLE
kubeproxy.config.k8s.io/v1alpha1 Breaking Change

### ISSUE THREAD

**Issue by mathewpeterson** [kubernetes/kubernetes#114884]
### What happened?

There appears to be a breaking change to kubeproxy.config.k8s.io/v1alpha1 in PR https://github.com/kubernetes/kubernetes/pull/112133

The schema for kubeproxy.config.k8s.io/v1alpha1 changed by removing the `udpIdleTimeout` without being deprecated. 

We based our manifest on what `kubeadm config print init-defaults --component-configs=KubeProxyConfiguration` provided to us in a previous version of kubeadm (pre 1.26)

When we tried create a new cluster with Kubernetes 1.26 using existing configuration we receive this error from kubeadm:

```
W0106 20:27:24.102630   31333 initconfiguration.go:305] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
W0106 20:27:24.106622   31333 configset.go:177] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: strict decoding error: unknown field "udpIdleTimeout"
```

### What did you expect to happen?

Existing kubeproxy.config.k8s.io/v1alpha1 manifests to be valid regardless of version of kubeadm we use.

### How can we reproduce it (as minimally and precisely as possible)?

Use kubeadm version lower than 1.26 to generate the default manifest for kube-proxy by using the command below:

kubeadm config print init-defaults --component-configs=KubeProxyConfiguration

Then use the same manifest to bootstrap a cluster using kubeadm greater than 1.26 or newer.

### Kubernetes version

<details>

```console
$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
N/A
$ uname -a
N/A

```

</details>

### Install tools

<details>
$ kubeadm version

kubeadm version: &version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:57:06Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
on paper alpha apis have little to no guarantees. yet preferably, removal of fields should be done after incrementing the api version especially if the api is widely spread and in production.

reading briefly the related pr it seems the feature was removed completely, which means the field is no longer needed?

up to sig network to comment / triage.

/sig network

**Comment by mathewpeterson** [comment]
Correct, the field is no longer required and we specifically were not using that setting - it came along when we created our initial configuration file. 

It seems your statement about alpha apis having "little to no guarantees" contradicts the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api)?

**Comment by neolit123** [comment]
> It seems your statement about alpha apis having "little to no guarantees" contradicts the [deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#deprecating-parts-of-the-api)?

fields should only be removed on version increment, like i pointed out. the bigger non-guarantee is:

>> Alpha API versions may be removed in any release without prior deprecation notice

it's important to note the component config apis in k8s should be treated more like ga apis, because of consumption numbers.

**Comment by aojea** [comment]
The deprecation of the userspace proxy was announced and started in 1.23 https://github.com/kubernetes/kubernetes/issues/103860

**Comment by mathewpeterson** [comment]
Sorry, I am not trying to be pedantic and perhaps I am confused on terminology but:

> Alpha API versions may be removed in any release without prior deprecation notice

The _API version_ was not removed, rather just a field.

Either way, thanks to everyone who responded. Hopefully this issue can help shed light for users in the future. 

I believe this issue can be closed now.

**Comment by aojea** [comment]
> The _API version_ was not removed, rather just a field.

we are not doing great with the configuration versioning, but it is more a problem of how component configuration has progressed and it was never fully implemented, causing still issues and inconsistencies between flags vs config per example

https://github.com/kubernetes/enhancements/issues/784
