### ISSUE TITLE
topologySpreadConstraints[*].labelSelector is not correctly validated

### ISSUE THREAD

**Issue by ellistarn** [kubernetes/kubernetes#114932]
### What happened?

```
apiVersion: v1
kind: Pod
metadata:
  name: correctly-invalid
  labels:
    foo: "{bar}"
spec:
  containers:
    - name: pause
      image: "public.ecr.aws/eks-distro/kubernetes/pause:3.2"
---
apiVersion: v1
kind: Pod
metadata:
  name: incorrectly-valid
spec:
  containers:
    - name: pause
      image: "public.ecr.aws/eks-distro/kubernetes/pause:3.2"
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        foo: "{bar}"
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
```
```
kubectl apply -f example.yaml
pod/incorrectly-valid created
The Pod "correctly-invalid" is invalid: metadata.labels: Invalid value: "{bar}": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```

### What did you expect to happen?

The pod named `incorrectly-valid` should be rejected by the API Server.

### How can we reproduce it (as minimally and precisely as possible)?

apiVersion: v1
kind: Pod
metadata:
  name: correctly-invalid
  labels:
    foo: "{bar}"
spec:
  containers:
    - name: pause
      image: "public.ecr.aws/eks-distro/kubernetes/pause:3.2"
---
apiVersion: v1
kind: Pod
metadata:
  name: incorrectly-valid
spec:
  containers:
    - name: pause
      image: "public.ecr.aws/eks-distro/kubernetes/pause:3.2"
  topologySpreadConstraints:
  - labelSelector:
      matchLabels:
        foo: "{bar}"
    maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway

### Kubernetes version

<details>

```console
k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:28:30Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.13-eks-fb459a0", GitCommit:"55bd5d5cb7d32bc35e4e050f536181196fb8c6f7", GitTreeState:"clean", BuildDate:"2022-10-24T20:35:40Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
Thanks for opening this @ellistarn , I think it was fixed by https://github.com/kubernetes/kubernetes/pull/111802 in v1.27

**Comment by ellistarn** [comment]
Beautiful, thank you!
