### ISSUE TITLE
VolumeZone scheduling plugin should handle csi migration

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#114996]
### What happened?

In https://github.com/kubernetes/kubernetes/issues/114268, we discovered that our plan for eventually removing the [VolumeZone](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins/volumezone) scheduling plugin when CSI migration is GA is not possible because the plugin also applies to non-migratable volume types.

However, if we leave the plugin as is, then even migratable PVs will be broken if we remove beta topology labels from Nodes in the future. This is because the plugin does not have any handling for migrated volumes.

### What did you expect to happen?

I suggest we add CSI migration handling to the VolumeZone plugin. I think we just need to detect if the volume is migrated, and if so, skip the VolumeZone processing. For migrated volumes, we translate `PV.Labels` into `PV.NodeAffinity` so they end up getting processed by the [VolumeBinding](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins/volumebinding) plugin.

### How can we reproduce it (as minimally and precisely as possible)?

In a cluster with csi migration for a specific intree volume type enabled,
1. create an intree PV with beta topology labels
2. remove the beta topology label from a node
3. try to schedule a pod using that pv

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
Any that supports csi migration
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by msau42** [comment]
/sig storage
/triage accepted
/priority important-soon

For e2e testing, this needs an environment that is configured with csi migration

**Comment by kidddddddddddddddddddddd** [comment]
Hi,I'd like to work on this issue. I previously wrote `PreFilter` for `volume_zone` plugin, so I'm familiar with it's logic. However I'm not familiar with the whole `CSI` thing, and I may ask you some questions during the work :(

**Comment by msau42** [comment]
> Can't we just translate this for all pvs? Why do we need to detect if the volume is migrated? What's the difference between a migrated pv and a non-migratable pv in this scenario?

I think this is also another alternative solution that could also work, but from https://github.com/kubernetes/kubernetes/issues/114268#issuecomment-1337414393, it may not scalable to do an automatic migration for all the different APIs and controllers that use the node labels. The main difference with CSI migration, is we have a good idea of all the different components that would be impacted and also have reasonable control over those components.

**Comment by kidddddddddddddddddddddd** [comment]
> I think we just need to detect if the volume is migrated, and if so, skip the VolumeZone processing. For migrated volumes, we translate PV.Labels into PV.NodeAffinity so they end up getting processed by the [VolumeBinding](https://github.com/kubernetes/kubernetes/tree/master/pkg/scheduler/framework/plugins/volumebinding) plugin.

A few more questions😂

1.  > detect if the volume is migrated

Will the volumes be migrated before we take a pod off the scheduler queue? If so, how can I detect this. Currently I find a function `IsPVMigratable` in `csi-translation-lib`, but nothing like  `IsPVMigrated`.

2.  > For migrated volumes, we translate PV.Labels into PV.NodeAffinity

Is this translation  done in `volume_zone` plugin or before scheduling?

Here's my understanding:
- For migrated volumes, we translate Topology labels to pv.NodeAffinity and update the pv, then we skip volume_zone(that is,don't compare labels with nodes).
- What about non-migratable volumes, I think we should continue to compare pv.labels with node labels for non-migratable volumes?

3.  I think currently in `volume_zone`, we consider topology label and beta label as different labels. That is ,if we have a pv with `LabelFailureDomainBetaZone` and a node with `LabelTopologyZone`, even if they have different values, `volume_zone` will let it pass the  filter. Maybe we should try to consider two labels as the same in `volume_zone`?

**Comment by msau42** [comment]
For detecting if a PV is migrated, you can use the same method that's used in the VolumeBinding plugin: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/plugins/volumebinding/binder.go#L1129. The only difference is you don't actually need to translate the PV in the VolumeZone plugin since it's already handled by the VolumeBinding plugin.

For non-migratable volumes, I think we can continue with the same VolumeZone logic. For now, we'll rely on users to update their PVs with the GA labels.

**Comment by kidddddddddddddddddddddd** [comment]
Thanks @msau42 ,for your detailed explanation. This is the implementation plan I prepared:
In `volume_zone prefilter`, we check if a pv is migrtable by using `IsPVMigratable`,if so we skip volume_zone since `volume_binding` will translate this pv and handle it later, otherwise we save the label of this pv in state,and compare it with node's label in `filter`.Is that feasible to you?

**Comment by msau42** [comment]
Yup that sounds good to me!

**Comment by kidddddddddddddddddddddd** [comment]
Thanks! I'll try to work on this one. I'll file a pr a few days later and we can talk about the details in there.
In the meantime, I think I previously wrote a bug in `volume_zone` plugin😢, I wonder if you have time to confirm it #115052 

/assign
