### ISSUE TITLE
Python2 still in use

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#114967]
### What happened?

python2 is long deprecated, everything should be on python3, but that doesn't appear to be the case in this repo.

/sig testing

**Comment by daman1807** [comment]
Hi !
I'm new to the community, can I pick this issue?

So far have found the following files using python:

- https://github.com/kubernetes/test-infra/blob/master/gubernator/filters_test.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/gcs_async_test.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/pull_request.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/view_build.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/view_pr.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/view_pr_test.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/github/main_test.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/github/models.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/github/periodic_sync_test.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/third_party/cloudstorage/common.py
- https://github.com/kubernetes/test-infra/blob/master/gubernator/third_party/cloudstorage/storage_api.py
- https://github.com/kubernetes/test-infra/blob/master/scenarios/kubernetes_janitor.py

**Comment by BenTheElder** [comment]
This issue is intended to be scoped to this repo specifically, not test-infra. test-infra has tracked in it's own issues https://github.com/kubernetes/test-infra/issues?q=is%3Aissue+python3+is%3Aclosed

There are files in this repo that need updating, and anyone is welcome to work on this.

**Comment by kidddddddddddddddddddddd** [comment]
I think python files are mainly used in hack. I can help with this one.

```
find ./ -name "*.py"                 
.//staging/src/k8s.io/kubectl/pkg/util/i18n/translations/extract.py
.//hack/boilerplate/test/pass.py
.//hack/boilerplate/test/fail.py
.//hack/boilerplate/boilerplate.py
.//hack/boilerplate/boilerplate_test.py
.//hack/verify-flags-underscore.py
.//hack/verify-publishing-bot.py
```

/assign
