### ISSUE TITLE
Improve coverage of e2e tests requiring a default storage class

### ISSUE THREAD

**Issue by mattcary** [kubernetes/kubernetes#114955]
Since the cloud provider extraction, it's become clear that many if not all of the e2e using a default storage class have been dropped, eg the sig-apps statefulset tests in [gce-cos-master-alpha-features](https://testgrid.k8s.io/google-gce#gce-cos-master-alpha-features). Even though these tests are running on GCE and so have access to PD, since CSI migration the in-tree gce-pd plugin does not function without the PD CSI driver being installed. There is [machinery](https://github.com/kubernetes/kubernetes/blob/release-1.26/test/e2e/storage/csi_volumes.go) to install this driver for storage/ tests, but it's not usable from, for example, the apps/ e2e tests.

Furthermore, the driver mentioned above is over a year out of date so is clearly not maintainable.

We propose to do the following:

* add e2e prow jobs using kind with a default local provisioner storage class, and confirm things like the statefulset tests pass (my particular axe to grind is the stateful set alpha cluster tests but will try to be comprehensive)
* To the existing GCE tests, install the pd csi driver at cluster setup and use the [external driver](https://github.com/kubernetes/kubernetes/tree/release-1.26/test/e2e/storage/external) mechanism for testing. This will be done from cloud-provider-gce which is the right place to maintain current pd csi driver versions anyway (rather than k/k).
* Remove PD CSI from csi_volumes.go.

The first two steps won't cause any disruption of existing tests. The final step will remove coverage of (an old version of) PD CSI from some GCE test grids, but this should be covered by the second step.

I've discussed this with a few folks but please correct what I've misunderstood and gotten wrong!

/assign @mattcary 
/sig storage
/cc @msau42 
/cc @BenTheElder

**Comment by mattcary** [comment]
From @BenTheElder 

> Getting something running probably involves https://github.com/kubernetes-sigs/kind/pull/3023 and we should talk to pohly.

/cc @pohly

**Comment by msau42** [comment]
Plan sounds good to me. We'll want to migrate the existing optional presubmit jobs from using k/k gce cluster to external gcp cluster as part of this: https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-storage/sig-storage-gce-config.yaml

cc @jsafrane if you have any concerns about dropping the built-in pd driver test config: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_volumes.go#L31

**Comment by jsafrane** [comment]
> Remove PD CSI from csi_volumes.go.

How will we test CSI migration? There are tests with pre-provisioned PVs + in-line volumes that we still run downstream (OpenShift) and that cannot be added via an external YAML manifest.

**Comment by mattcary** [comment]
There is no CSI migration for PD CSI, it's on by default from 1.23. and now GA. That's actually the root cause here---since the in-tree gce-pd requires a pd csi driver to be installed, it's been complicated for any GCE job that wants a default storage class.

I'm not proposing changing the CSI volume test framework, only removing GCE PD from it.  OpenShift tests or any other cloud provider won't be affected.

**Comment by msau42** [comment]
@jsafrane to clarify, we're proposing removing the CSI test driver definition, which explicitly installs/uninstalls the CSI driver with every test case: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/csi_volumes.go#L31

The test driver config used for intree/migration (dynamic, preprovisioned, and inline) is here: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/in_tree_volumes.go#L73

**Comment by jsafrane** [comment]
I see, sorry about the noise. It's sad that k/k tests will loose a "real" storage to test with, but there are not so many tests that need a default SC anyway.

**Comment by mattcary** [comment]
k/k already lost the "real" storage -- all tests outside of e2e/storage lost gce-pd with migration & cloud-provider extraction. That will be tested through k8s.io/cloud-provider-gcp eventually.

For most of the e2e tests I think it's overkill to bring up a full gce cluster, a kind cluster should be enough I think?

**Comment by mattcary** [comment]
I've figured out how to make kind work with the mutation detector, see https://github.com/kubernetes-sigs/kind/pull/3123. I'll work on adding this to the jobs that expect a default storage class.
