### ISSUE TITLE
kube-apiserver  http2: server: xxx read: connection reset by peer

### ISSUE THREAD

**Issue by lspjx** [kubernetes/kubernetes#114939]
### What happened?

http2: server: error reading preface from client 192.168.2.13:41264: read tcp 192.168.2.11:6443->192.168.2.13:41264: read: connection reset by peer
http2: server: error reading preface from client 10.224.157.55:57398: read tcp 192.168.2.11:6443->10.224.157.55:57398: read: connection reset by peer
E0109 22:29:07.705196       1 timeout.go:135] post-timeout activity - time-elapsed: 5.618753ms, GET "/version" result: <nil>
http2: server: error reading preface from client 10.224.157.55:37356: read tcp 192.168.2.11:6443->10.224.157.55:37356: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.13:54878: read tcp 192.168.2.11:6443->192.168.2.13:54878: read: connection reset by peer
E0109 23:05:07.717026       1 timeout.go:135] post-timeout activity - time-elapsed: 875.699µs, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.12:50746: read tcp 192.168.2.11:6443->192.168.2.12:50746: read: connection reset by peer
E0109 23:10:37.756434       1 timeout.go:135] post-timeout activity - time-elapsed: 1.343291ms, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.13:42396: read tcp 192.168.2.11:6443->192.168.2.13:42396: read: connection reset by peer
E0109 23:28:07.776469       1 timeout.go:135] post-timeout activity - time-elapsed: 7.118557ms, GET "/version" result: <nil>
E0109 23:35:07.752700       1 timeout.go:135] post-timeout activity - time-elapsed: 109.624µs, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.15:55382: read tcp 192.168.2.11:6443->192.168.2.15:55382: read: connection reset by peer
E0109 23:54:47.680147       1 timeout.go:135] post-timeout activity - time-elapsed: 5.597974ms, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.13:42122: read tcp 192.168.2.11:6443->192.168.2.13:42122: read: connection reset by peer
E0110 00:02:47.766988       1 timeout.go:135] post-timeout activity - time-elapsed: 5.113149ms, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.14:50620: read tcp 192.168.2.11:6443->192.168.2.14:50620: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.15:48050: read tcp 192.168.2.11:6443->192.168.2.15:48050: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.14:55950: read tcp 192.168.2.11:6443->192.168.2.14:55950: read: connection reset by peer
E0110 00:12:17.774643       1 timeout.go:135] post-timeout activity - time-elapsed: 3.862474ms, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.13:52288: read tcp 192.168.2.11:6443->192.168.2.13:52288: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.15:35554: read tcp 192.168.2.11:6443->192.168.2.15:35554: read: connection reset by peer
http2: server: error reading preface from client 10.224.157.55:36238: read tcp 192.168.2.11:6443->10.224.157.55:36238: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.14:47204: read tcp 192.168.2.11:6443->192.168.2.14:47204: read: connection reset by peer
E0110 00:41:37.676166       1 timeout.go:135] post-timeout activity - time-elapsed: 925.528µs, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.15:50462: read tcp 192.168.2.11:6443->192.168.2.15:50462: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.15:53810: read tcp 192.168.2.11:6443->192.168.2.15:53810: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.15:60018: read tcp 192.168.2.11:6443->192.168.2.15:60018: read: connection reset by peer
http2: server: error reading preface from client 10.224.157.55:50628: read tcp 192.168.2.11:6443->10.224.157.55:50628: read: connection reset by peer
E0110 01:06:07.709770       1 timeout.go:135] post-timeout activity - time-elapsed: 3.797188ms, GET "/version" result: <nil>
http2: server: error reading preface from client 192.168.2.14:34996: read tcp 192.168.2.11:6443->192.168.2.14:34996: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.12:35318: read tcp 192.168.2.11:6443->192.168.2.12:35318: read: connection reset by peer
http2: server: error reading preface from client 192.168.2.15:58488: read tcp 192.168.2.11:6443->192.168.2.15:58488: read: connection reset by peer

### What did you expect to happen?

kube-apiserver pod outputs lots of "http2: server: error reading preface from client 192.168.2.15:58488: read tcp 192.168.2.11:6443->192.168.2.15:58488: read: connection reset by peer"

### How can we reproduce it (as minimally and precisely as possible)?

v1.22.8

### Kubernetes version

<details>

```console
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:10:06Z", GoVersion:"go1.16.15", Com
piler:"gc", Platform:"linux/amd64"}Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.8", GitCommit:"7061dbbf75f9f82e8ab21f9be7e8ffcaae8e0d44", GitTreeState:"clean", BuildDate:"2022-03-16T14:04:34Z", GoVersion:"go1.16.15", Com
piler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support

for APIServer error logs, firstly check that apiserver and etcd are ready
- is apiserver serving healthy? https://kubernetes.io/docs/reference/using-api/health-checks/
- is etcd healthy?

Then, check clients and networking
- check if all [clients' version match](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/9) and if there is no[ firewall between clients and server](https://www.infiniroot.com/blog/1051/fixing-monitoring-api-is-not-ready-error-rancher-2-kubernetes-cluster).

**Comment by lspjx** [comment]
> /亲切的支持
> 
> 对于 APIServer 错误日志，首先检查 apiserver 和 etcd 是否准备就绪
> 
> * API Server 服务健康吗？ https://kubernetes.io/docs/reference/using-api/health-checks/
> * 蚀刻健康吗？
> 
> 然后，检查客户端和网络
> 
> * 检查是否全部 [客户端版本匹配](https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/9) 如果没有[ 客户端和服务器之间的防火墙](https://www.infiniroot.com/blog/1051/fixing-monitoring-api-is-not-ready-error-rancher-2-kubernetes-cluster).


check apiserver and etcd service health, firewall closed.

# kubectl get --raw='/readyz?verbose'
[+]ping ok
[+]log ok
[+]etcd ok
[+]informer-sync ok
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/priority-and-fairness-config-consumer ok
[+]poststarthook/priority-and-fairness-filter ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[+]poststarthook/crd-informer-synced ok
[+]poststarthook/bootstrap-controller ok
[+]poststarthook/rbac/bootstrap-roles ok
[+]poststarthook/scheduling/bootstrap-system-priority-classes ok
[+]poststarthook/priority-and-fairness-config-producer ok
[+]poststarthook/start-cluster-authentication-info-controller ok
[+]poststarthook/aggregator-reload-proxy-client-cert ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[+]autoregister-completion ok
[+]poststarthook/apiservice-openapi-controller ok
[+]shutdown ok
readyz check passed

# ./etcdctl  --endpoints=https://192.168.2.11:2379,https://192.168.2.12:2379,https://192.168.2.13:2379   \
> --cacert=/etc/kubernetes/pki/etcd/ca.crt   \
> --cert=/etc/kubernetes/pki/etcd/server.crt  \
> --key=/etc/kubernetes/pki/etcd/server.key \
> endpoint health
https://192.168.2.11:2379 is healthy: successfully committed proposal: took = 21.518036ms
https://192.168.2.13:2379 is healthy: successfully committed proposal: took = 32.778129ms
https://192.168.2.12:2379 is healthy: successfully committed proposal: took = 37.356129ms

# ./etcdctl  --endpoints=https://192.168.2.11:2379,https://192.168.2.12:2379,https://192.168.2.13:2379   \
> --cacert=/etc/kubernetes/pki/etcd/ca.crt   \
> --cert=/etc/kubernetes/pki/etcd/server.crt  \
> --key=/etc/kubernetes/pki/etcd/server.key \
> endpoint status
https://192.168.2.11:2379, 84df052d1edb239e, 3.5.0, 63 MB, false, false, 19, 47991927, 47991927, 
https://192.168.2.12:2379, 8c4354a70811bf52, 3.5.0, 63 MB, true, false, 19, 47991927, 47991927, 
https://192.168.2.13:2379, a0ca49ec04d166bf, 3.5.0, 65 MB, false, false, 19, 47991927, 47991927,

**Comment by porridge** [comment]
"http2: server: error reading preface from client [...] read: connection reset by peer" sounds like a client is connecting to your API server, but by the time the API server gets round to reading the initial bytes that the client should be sending, the client resets the connection.

There does not seem to be anything wrong in the API server. You might want to check why your client is behaving like this.
