### ISSUE TITLE
Failure cluster [dd3d4ece...] net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by brianpursley** [kubernetes/kubernetes#114934]
##### Error text:
```
[FAILED] failed to wait for definition "com.example.crd-publish-openapi-test-multi-to-single-ver.v6alpha1.e2e-test-crd-publish-openapi-393-crd" not to be served anymore: failed to wait for OpenAPI spec validating condition: Get "https://35.230.96.113/openapi/v2": net/http: TLS handshake timeout; lastMsg: 
In [It] at: test/e2e/apimachinery/crd_publish_openapi.go:469 @ 01/07/23 04:26:57.677

```
#### Recent failures:
[1/9/2023, 7:21:38 AM pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114548/pull-kubernetes-e2e-gce/1612424324973596672)
[1/4/2023, 11:25:32 AM pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114678/pull-kubernetes-e2e-gce/1610673771734110208)
[1/4/2023, 3:32:08 AM pr:pull-kubernetes-e2e-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114801/pull-kubernetes-e2e-gce/1610554624673058816)

/kind failing-test
/kind flake

/sig api-machinery

#### See also:
There are other sporadic failures with a similar "TLS handshake timeout" error as shown here:
https://storage.googleapis.com/k8s-triage/index.html?ci=0&pr=1&text=TLS%20handshake%20timeout

```
error: error when deleting "STDIN": Delete "https://35.197.34.50/api/v1/namespaces/kubectl-1446/pods/httpd": net/http: TLS handshake timeout
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114914/pull-kubernetes-e2e-gce/1612375254447951872

```
failed to wait for definition "com.example.crd-publish-openapi-test-multi-to-single-ver.v5.e2e-test-crd-publish-openapi-3454-crd" to be served with the right OpenAPI schema: failed to wait for OpenAPI spec validating condition: Get "https://35.230.38.24/openapi/v2": net/http: TLS handshake timeout; lastMsg:
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114850/pull-kubernetes-e2e-gce/1611006645284900864
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114830/pull-kubernetes-e2e-ubuntu-gce-network-policies/1610985514557509632
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/110838/pull-kubernetes-e2e-gce/1610281231612645376
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114508/pull-kubernetes-e2e-gce/1609890328821633024

```
failed to wait for definition "com.example.crd-publish-openapi-test-multi-to-single-ver.v6alpha1.e2e-test-crd-publish-openapi-3074-crd" to be served with the right OpenAPI schema: failed to wait for OpenAPI spec validating condition: Get "https://35.197.105.7/openapi/v2": net/http: TLS handshake timeout; lastMsg: 
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/14960/14874/pull-kops-e2e-k8s-gce-cilium/1611622759018795008
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/14930/14874/pull-kops-e2e-k8s-gce-cilium/1610034333370814464

```
failed to wait for definition "com.example.crd-publish-openapi-test-multi-ver.v3.e2e-test-crd-publish-openapi-50-crd" to be served with the right OpenAPI schema: failed to wait for OpenAPI spec validating condition: Get "https://api.e2e-e2e-kops-aws-arm64-release.test-cncf-aws.k8s.io/openapi/v2": net/http: TLS handshake timeout; lastMsg:
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/14870/14870/pull-kops-e2e-cni-cilium-eni/1608902630061379584

```
Unable to connect to the server: net/http: TLS handshake timeout
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-e2e-gce/1611048455520653312

```
failed to wait for definition "com.example.crd-publish-openapi-test-multi-to-single-ver.v6alpha1.e2e-test-crd-publish-openapi-3584-crd" to be served with the right OpenAPI schema: failed to wait for OpenAPI spec validating condition: Get "https://34.105.15.206/openapi/v2": net/http: TLS handshake timeout; lastMsg: 
```
* https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/114865/pull-kubernetes-e2e-gce-ubuntu-containerd/1611181266290348032

**Comment by brianpursley** [comment]
Related kubectl issue requesting retry logic for TLS handshake timeout:
https://github.com/kubernetes/kubectl/issues/1270

**Comment by brianpursley** [comment]
I suppose one answer might be that we accept that there will be occasional timeouts related to transient network problems, and therefore this flake is a non-issue, but I wanted to call attention to the linked issue in case there is some interest in making dial more resilient to TLS handshake timeouts.

One thing to note is the TLS handshake timeout occurs after only 10 seconds, whereas the overall connection timeout is set to 30 seconds.

**Comment by apelisse** [comment]
Thanks @brianpursley, that's useful. We can probably do better!

**Comment by cici37** [comment]
/close
We looked at this during bug triage meeting and seems like it's not often. Please feel free to reopen if this flaky is still happening.
