### ISSUE TITLE
Allow PV NodeAffinity to update from beta to GA topology labels

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#114995]
### What happened?

In https://github.com/kubernetes/kubernetes/issues/114268, we realized that non in-tree PVs can be impacted by a future removal of beta topology labels from Nodes if they are supporting the beta topology labels.

### What did you expect to happen?

We should allow users to mutate the PV NodeAffinity to update uses of the beta topology label to the GA label.

### How can we reproduce it (as minimally and precisely as possible)?

Remove beta topology label from a Node, and try to schedule a Pod using a non-migratable PVC with beta topology label in the PV.NodeAffinity.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by haoruan** [comment]
Do we allow users to mutate both non in-tree PVs and in-tree PVs, or only non in-tree PVs?
