### ISSUE TITLE
Increase the update interval of perf counters to 10 seconds

### ISSUE THREAD

**Issue by yungjenhung** [kubernetes/kubernetes#114928]
### What happened?

Perf counters are currently updated every second which doesn't match the default cadvisor collection period as 10 seconds.

https://github.com/kubernetes/kubernetes/blob/eb7fd7f51c166591adbc52eacef3ce1e4d17bf04/pkg/kubelet/winstats/perfcounters.go#L37

### What did you expect to happen?

Increase the update interval of perf counters to 10 seconds to match the house keeping interval of cadvisor.

https://github.com/kubernetes/kubernetes/blob/eb7fd7f51c166591adbc52eacef3ce1e4d17bf04/pkg/kubelet/cadvisor/cadvisor_linux.go#L60

### How can we reproduce it (as minimally and precisely as possible)?

The fresh install of our internal AKS clusters.

### Anything else we need to know?

The perf counter query (pdh!PdhCollectQueryData) is responsible for >20% of CPU time in kubelet process on internal clusters, which can be reduced by lowering the perf counter update interval.

### Kubernetes version

<details>

```console
$ kubectl version
# K8s v1.24.6
```

</details>

### Cloud provider

<details>
Azure Kubernetes Service (AKS)
</details>

### OS version

<details>

Operating System: Windows Server 2019 Datacenter 
OS Build Number: 17763.3770.amd64fre.rs5_release.180914-1434 

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/area cadvisor

Since it is a performance overhead and not a bug per se, I will change the kind of this issue:

/remove-kind bug
/kind feature

@bobbypage I bet there is an issue for this already. Can you comment/dedup?

**Comment by bobbypage** [comment]
I believe the ask here is to increase the `perfCounterUpdatePeriod` which is only used on Windows to fetch stats from windows specific per counters. Windows does not use cAdvisor and instead uses  `kubernetes/pkg/kubelet/winstats` which reads from the perf counters directly.

/cc @jsturtevant @marosset

**Comment by bobbypage** [comment]
(removing cadvisor since it is ask for windows stats)

/remove-area cadvisor

**Comment by jsturtevant** [comment]
> I believe the ask here is to increase the `perfCounterUpdatePeriod` which is only used on Windows to fetch stats from windows specific per counters. Windows does not use cAdvisor and instead uses `kubernetes/pkg/kubelet/winstats` which reads from the perf counters directly.

agreed that is the ask. I don't have any major issue with it but would be worried about change in behavior for existing users.  What are our options for making this configurable?

**Comment by yungjenhung** [comment]
That would be great if making it configurable.

**Comment by jsturtevant** [comment]
It might not be worth the overhead to pass this as configuration through kubelet parameters.  I am unsure what affect it would have on folks who rely on it for current reporting or if it would be ok to bump the querying time.

@yungjenhung if you increase it to 10s do you see a large drop in cpu usage?

**Comment by jsturtevant** [comment]
@marosset might have thoughts as well

**Comment by yungjenhung** [comment]
Based on internal cloud profiling data from thousands of Windows clusters, pdh!PdhCollectQueryData takes 33% CPU usage as of today, 01/20/2023. If the updating interval increases from 1s to 10s, pdh!PdhCollectQueryData usage can be reduced 90% and CPU usage of kubelet can potentially drop 30%.

**Comment by jsturtevant** [comment]
that is a compelling improvement.  I am still concerned about changing the default on folks who might rely on it, I am not sure if it is a valid concern though

**Comment by yungjenhung** [comment]
To understand the impact of changing the interval, what is the purpose for querying those Windows counters?

**Comment by marosset** [comment]
@yungjenhung - Can you share a little bit more information about your setup?
What node size are you using in AKS? 
Are you overprovisioning your nodes?
Do you have any addons running in your AKS cluster? 
Does the drop eventually go down?
Have you seen this issue on Windows Server 2022 too?

We don't see this spike in CPU usage in our clusters provisioned with CAPZ (cluster api provider for azure) so I suspect something else is going on too.
https://perf-dash.k8s.io/#/?jobname=soak-tests-capz-windows-2019&metriccategoryname=E2E&metricname=CPUUsage&Process=kubelet
I'm not opposed to increasing the timeout but currently I think this issue may be environmental.

**Comment by yungjenhung** [comment]
1\ The node size is D32_Flex which has 32 vCPUs and 128 GiB memory. 
2\ The perf counter query usage is the same across all clusters regardless of the cluster is running hot or cold.
3\ azurepolicy is the only addon enabled.
4\ The trending of perf counter query usage is quite stable.
5\ Not applicable at this moment, all clusters are running with Windows Server 2019.

Do you have CPU traces from CAPZ to check the time spent on PdhCollectQueryData? For our internal profiling data, perf counter usage is pretty stable in kubelet, and it's not related to the CPU spike.

**Comment by jsturtevant** [comment]
>  For our internal profiling data, perf counter usage is pretty stable in kubelet, and it's not related to the CPU spike.

I am not sure I understand this statement.  The cpu usage from the the winstats pkg would be attributed to the kubelet since it is the own process.  What is the owning process for `PdhCollectQueryData` usage you are seeing?

**Comment by yungjenhung** [comment]
`PdhCollectQueryData` usage is from kubelet process itself. One thing I misunderstood is that, the `PdhCollectQueryData` usage in kubelet is not stable. Actually, it keeps growing. The usage is almost zero originally, but it grows up to 30+% cpu usage in kubelet. Looking into it...

**Comment by yungjenhung** [comment]
The tool wasn't getting the correct data at the first time. It turns out `PdhCollectQueryData` usage in kubelet is growing from 20% to 30+% across all clusters, and the usage is never close to zero. I will investigate the growing cost of `PdhCollectQueryData`. It'd be great if we can increase the query interval to reduce the cost.
