### ISSUE TITLE
Unable to connect to the server: dial tcp: lookup raw.githubusercontent.com on 10.129.251.125:53: server misbehaving

### ISSUE THREAD

**Issue by Anddiy** [kubernetes/kubernetes#114926]
Hello! Im having some problems with kubectl/kubernetes.

I have a kubernetes cluster running on Rancher, my customer have an internet proxy and racher has been setted to use this proxy, all the U.I are OK and my cluster is active.

Cluster Structure:

```
1 Rancher Node - RKE2 

Custom Cluster created by Rancher U.I 
1 master
4 workers
 ```
OS: RockyLinux
 ```
Linux vmrmmstnodehom01.lnx.ossclaro.srv 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

 ```

So i've tried to install Longhorn with the kubectl command to do it and get this: 

```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.3.2/deploy/longhorn.yaml 
Unable to connect to the server: dial tcp: lookup raw.githubusercontent.com on 10.129.251.125:53: server misbehaving

```

I've defined the customer proxy on RKE2 installation and in rancher installation too, so i don't know if it is a proxy config here, happy to attach in this posts all the logs if necessary, thanks.

**Comment by amartyaa** [comment]
Hey This feels like dns/connectivity issue as your bash is not able to resolve this given url, can you please try  to "curl"  on that url from same cli.

```
curl https://raw.githubusercontent.com/longhorn/longhorn/v1.3.2/deploy/longhorn.yaml 
```

**Comment by aojea** [comment]
you should open the issue in the rancher project

if this turns out to be a kubernetes problem you can always reopen

Thanks

/close
