### ISSUE TITLE
Permission errors at local-up-cluster.sh on /tmp directory

### ISSUE THREAD

**Issue by mhmxs** [kubernetes/kubernetes#115016]
### What happened?

I tried to execute the script to start a cluster and it failed:

```
./hack/local-up-cluster.sh: line 515: /tmp/kube_egress_selector_configuration.yaml: Permission denied
./hack/local-up-cluster.sh: line 533: /tmp/kube-audit-policy-file: Permission denied
```

Update: After some investigation, I have found that I executed the script without `sudo` first (my bad) and it failed with sudo next time.

### What did you expect to happen?

The script starts a cluster without any temp folder-related permission issues.

### How can we reproduce it (as minimally and precisely as possible)?

Run `local-up-cluster.sh` without `sudo` first "accidentally" and then re-execute the command with `sudo`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.0.908+a887a3b4fdebe0-dirty", GitCommit:"a887a3b4fdebe0390c6019b5fc5eb911e8042cec", GitTreeState:"dirty", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-alpha.0.908+a887a3b4fdebe0-dirty", GitCommit:"a887a3b4fdebe0390c6019b5fc5eb911e8042cec", GitTreeState:"dirty", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.11.1482.8c54d842d95"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_END="2023-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"
$ uname -a
Linux nixos 5.15.86 #1-NixOS SMP Sat Dec 31 12:14:48 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mhmxs** [comment]
Thanks @saschagrunert for the quick answer. I can agree (chmod magic isn't the best way to solve this). In this case, I think the documentation needs to be updated, I have followed the docs, which first suggested starting the script without `sudo`. For the second time I executed the script with `sudo` as the documentation suggested: `may need to be run as root. If it reports failures, try this instead`, and then I got the error. I had to spend some time investigating why the earth the script is failing.

WDYT?

https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#starting-the-cluster

**Comment by saschagrunert** [comment]
@mhmxs doe `hack/local-up-cluster.sh` work without being root? If so, then I agree we should make it the default :+1:

**Comment by mhmxs** [comment]
@saschagrunert Exactly the script has several commands with `sudo`. So first execution would need `sudo` except someone prepares everything before executing the script. Once It has been executed as `root` I think no one would be able to re-execute it as a regular user.

**Comment by mhmxs** [comment]
@saschagrunert It doesn't because there is one file with `root` owner.

```
.rw------- root  root  1.5 MB Mon Jan 16 11:36:40 2023 kube-apiserver-audit.log
```

Next time api manager fails:

```
E0116 11:37:23.023960   12336 run.go:74] "command failed" err="ensureLogFile: open /tmp/kube-apiserver-audit.log: permission denied"
```

**Comment by SergeyKanzhelev** [comment]
/assign @mhmxs 

since you are working on a fix
