### ISSUE TITLE
can not read environment variables defined by envfrom in the shell process

### ISSUE THREAD

**Issue by jack-110** [kubernetes/kubernetes#115057]
### What happened?

I try to read environment variables defined by envFromin in the shell process. But it failed.
Then I switch to the bash process, and Ican read the environment variables defined by envFrom.

### What did you expect to happen?

 read environment variables defined by envFromin in the shell process.

### How can we reproduce it (as minimally and precisely as possible)?

**deployment.yaml**     
 containers:
        - envFrom:
          - secretRef:
              name: test-secret

**command in the kubctl**
k exec -it pod-name sh
env // in the shell process

### Anything else we need to know?

I just want to confirm if it's bug in k8s.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.14-eks-fb459a0", GitCommit:"b07006b2e59857b13fe5057a956e86225f0e82b7", GitTreeState:"clean", BuildDate:"2022-10-24T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Could you provide the full manifest that you can apply when replicating this issue @jack-110 ?

**Comment by jack-110** [comment]
sorry, maybe I can't offer you that. It relates to my company private code.
Is there have any difference for the following two ways?
`envFrom:
 - secretRef:
     name: "test-secret"

env
 - name: Node
     value: "test-node"
`

**Comment by Kartik494** [comment]
@jack-110 i have followed the reference given in https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/ 
and able to read environment in shell process .

```
kubectl exec -it envar-demo -- printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=envar-demo
NPM_CONFIG_LOGLEVEL=info
NODE_VERSION=4.4.2
DEMO_GREETING=Hello from the environment
DEMO_FAREWELL=Such a sweet sorrow
KUBERNETES_SERVICE_HOST=10.96.0.1
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_PORT=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
TERM=xterm
HOME=/root
```
