### ISSUE TITLE
Cleanup dead code in the codebase

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#115088]
https://github.com/kubernetes/kubernetes/pull/111654 started here but it got big (shocking!) and the contributor got busy.  There are a lot of potential cleanups in there, though, and I hate wasting work.

I see it as an opportunity for someone to rack up some PRs and net-negative LOCs (the best kind!) - just take over that PR, break it up into a bunch of smaller PRs, and send them our way!

A very eager beaver might automate this, but there's a lot of manually-identified low-hanging fruit, I think.

**Comment by HirazawaUi** [comment]
very willing to oblige

**Comment by dereknola** [comment]
I would like to point out that CRI-Dockerd was in fact using some of the "unused" functions in https://github.com/kubernetes/kubernetes/pull/115103. Just because K8s is not using the function doesn't mean some other repo/project is not.

**Comment by thockin** [comment]
To be crystal clear - we do not support or endorse importing `k8s.io/kubernetes` AT ALL.  We offer no guarantees of stability there.
