### ISSUE TITLE
kubectl edit --server-side ?

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#115089]
Looking AGAIN at the issue with Service ports having an insufficient merge key for client-side `apply`.  The issue also appears in `kubectl edit` but is fixed in server-side `apply`.

Could we possibly do server-side for `kubectl edit`?

**Comment by sftim** [comment]
How about transferring this to `k/kubectl`?

**Comment by thockin** [comment]
https://github.com/kubernetes/kubectl/issues/1350
