### ISSUE TITLE
kubelet/cadvisor metrics are only getting bigger over time

### ISSUE THREAD

**Issue by tomglaza** [kubernetes/kubernetes#115008]
### What happened?

Metrics collected from http://node:10255/metrics/cadvisor endpoints include information on non-existent pods, making them larger and larger.

### What did you expect to happen?

Metrics data collected from endpoints http://node:10255/metrics/cadvisor should only include information on existing/running pods.

### How can we reproduce it (as minimally and precisely as possible)?

```console
$ cat test-pod.yml
---
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: test
      image: almalinux:8
      command: ["/bin/sleep", "100"]
$ kubectl apply -f test-pod.yml
pod/test created
$ crictl ps | grep test
7084cfed5adf2       340c79d7a8cd9c23c7169e0455a2c16e5775c0b4a0590c0a5c522fedd9c123e2       3 seconds ago       Running       test       0       772d9f998e8b4
$ kubectl delete -f test-pod.yml
pod "test" deleted
$ curl -s http://localhost:10255/metrics/cadvisor | grep 7084cfed5adf2 | head -n1
$ curl -s http://localhost:10255/metrics/cadvisor | grep 772d9f998e8b4 | head -n1
container_cpu_load_average_10s{container="POD",id="/pids/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod9e2b2641_45ed_49ff_b2ef_e7ec19797804.slice/crio-772d9f998e8b44622bfdeb0ef0e662c51115d3b49712c9a3d016ce8d252b7be9.scope",image="",name="k8s_POD_test_default_9e2b2641-45ed-49ff-b2ef-e7ec19797804_0",namespace="default",pod="test"} 0 1673520901759
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:20:29Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12", GitCommit:"c6939792865ef0f70f92006081690d77411c8ed5", GitTreeState:"clean", BuildDate:"2022-09-21T12:13:07Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
$ cat /etc/os-release | hean -n2
NAME="AlmaLinux"
VERSION="8.7 (Stone Smilodon)"
$ uname -a
Linux node-1.k8s 4.18.0-425.3.1.el8.x86_64 #1 SMP Tue Nov 8 14:08:25 EST 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```console
$ runc -v
runc version 1.1.4
spec: 1.0.2-dev
go: go1.18.4
libseccomp: 2.5.2
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ crio -v
crio version 1.23.4
Version:          1.23.4
GitCommit:        a6a1e6ebf4c4baca7ca7d57f069a4e0cd89056cd
GitTreeState:     clean
BuildDate:        2022-11-30T13:47:23Z
GoVersion:        go1.17.5
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, seccomp
SeccompEnabled:   true
AppArmorEnabled:  false
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by n4j** [comment]
@tomglaza In the statement `curl -s http://localhost:10255/metrics/cadvisor | grep 772d9f998e8b4 | head -n1`  how did you figure pod id `772d9f998e8b4`?

**Comment by tomglaza** [comment]
@n4j It is in the result of the `crictl ps | grep test` command at the end of the line (you need to scroll to the right).

However, perhaps this is not a problem with `kubernetes/cadvisor` as I initially assumed, because I found an older cluster (same version of kubernetes /1.23.12/, but lower version of cri-o /1.21.7/) and there the problem does not occur.
But it's strange, because it is recommended to have cri-o in the same version as kubernetes.

**Comment by n4j** [comment]
/assign
Let me figure what's going on here

**Comment by tomglaza** [comment]
A small update:
- update cri-o to 1.23.5 with no changes
- downgrade cri-o to 1.22.5 no change
- after downgrading cri-o to 1.21.7 the problem goes away
- using the https://github.com/kubernetes/kubernetes/issues/106957#issuecomment-1123465945 script on one of the machines reduced the size of the reported metrics from 59.2M to 7541k

**Comment by dims** [comment]
@tomglaza are you suspecting that this is only with cri-o?

( cc @mrunalp @haircommander )

**Comment by tomglaza** [comment]
@dims It's hard to say because I only have clusters with cri-o and docker. On docker I haven't seen this problem, and containerd I haven't tried.

**Comment by dims** [comment]
@tomglaza docker underneath uses containerd, so probably safe to rule that out.

**Comment by haircommander** [comment]
@n4j thanks for volunteering to work on this! let me know if there's anything I can do to help :)

**Comment by n4j** [comment]
> @n4j thanks for volunteering to work on this! let me know if there's anything I can do to help :)

Thanks @haircommander, I'll let you know

**Comment by n4j** [comment]
Update my analysis on the root cause of the issue in this [comment](https://github.com/cri-o/cri-o/issues/6349#issuecomment-1407293012)

**Comment by n4j** [comment]
This issue is caused by `cri-o` it would be tracked via https://github.com/cri-o/cri-o/issues/6349

/close
