### ISSUE TITLE
Can kubelet support restart pods/container action that triggered by kubectl.

### ISSUE THREAD

**Issue by minghuiyuan** [kubernetes/kubernetes#115015]
### What would you like to be added?

when kubectl exec command like
```
kubectl restart pod-name container-name -n namespace-name
```
and then kubelet help to restart related the conotainer.

### Why is this needed?

For some network issue and ip monitoring issue, pods' change will lead to the ip change actions, ip change will be one extremely suffering action. especially for doing the maintenance oftenly, just restart containers will save a lot of efforts and time, which is much better than restarting pods.

**Comment by dariodsa** [comment]
Consider ``PersistentVolumes``, if you have issues with them, restarting pod will indicate remount procedure, and it what you want sometimes. Maybe some flag which will indicate restart only of a pods.
