### ISSUE TITLE
Deletecollection failing after 34 seconds

### ISSUE THREAD

**Issue by JohnRusk** [kubernetes/kubernetes#115090]
### What happened?

In a cluster with large enough numbers of objects, it seems to be impossible to clean them up with `deletecollection`.  Because the deletecollection is failing while listing the objects from etcd.  The failure happens after exactly 34 seconds, due to the 34-second max timeout introduced in PR #96901 (cc @tkashem for insight on that PR).

### What did you expect to happen?

The deletecollection should be able to run for longer, and succeed.

I recognise that there are still risks of the API server using too much RAM, if deleting a very large collection due to issue #90743.  But, until _that_ issue is fixed, it seems like allowing `deletecollection` to run for longer might be a good idea.  As far as I can tell, the 34 second timeout does not apply to normal LIST calls, so on that basis I feel it should not apply to the giant unchunked LIST call that happens inside `deletecollection`.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a few hundred thousand objects of some particular type.  (Argo workflowtaskresults happen to be the type I'm looking at while I write this)
2. Call deletecollection. (Optionally passing some kind of fieldSelector, but I don't think that's essential)
3. Observe that a 504 failure code is logged in kube-audit logs, and that a log entry similar to this is logged by the API Server `"List etcd3" key:<some key>,...,limit:0 ... (total time: 34000ms)`  (In practice, the total time may be a little over 34000 ms).
4. As far as I can tell, the delete collection really has failed at this point.  I notice that PR #96901 says that, in general, "The go-routine can keep running, while the timeout logic will return a timeout to the client" but I don't _think_ that's what's happening here.  I think that, because the 34 sec timeout is used in the context of the etcd call, the etcd list call really does fail, and so the code never proceeds to actually deleting anything.

### Kubernetes version

1.22

### Cloud provider

AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tkashem** [comment]
@JohnRusk  the `34s` deadline has been in effect before PR https://github.com/kubernetes/kubernetes/pull/96901 was introduced

https://github.com/kubernetes/kubernetes/blob/9787f46bbf05349ca53cd8b04cd2f7a76771646a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/delete.go#L181-L184

If we remove this `34s` deadline from here, then the delete request will have at most `60s` to complete (default).  
The list call that is failing in your case, is a direct call to the storage, right? 
https://github.com/kubernetes/kubernetes/blob/9787f46bbf05349ca53cd8b04cd2f7a76771646a/staging/src/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1142-L1145

on the contrary, we don't enforce the `34s` timeout for LIST 
https://github.com/kubernetes/kubernetes/blob/9787f46bbf05349ca53cd8b04cd2f7a76771646a/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/get.go#L166

I don't know if it makes sense to remove the `34s` for `DELETECOLLECTION`, @deads2k @wojtek-t can you please chime in here when you have some time?

**Comment by JohnRusk** [comment]
>The list call that is failing in your case, is a direct call to the storage, right?

It reads from etcd, not from API Server Cache.  Is that what you were asking @tkashem?

Looking at the bigger picture,  I think your questions are good ones. Especially in the context of this: https://github.com/kubernetes/kubernetes/issues/90743. In particular, changing the timeouts won't solve all of the problems with DELETECOLLECTION.  My assumption, when logging this issue, is that it might be a quick way to solve just _some_ of them.

**Comment by wojtek-t** [comment]
> I don't know if it makes sense to remove the 34s from DELETECOLLECTION

I think we should remove this - it's effectively a regression that we introduced with the PR.

> should we allow timeout for DELETECOLLECTION to exceed 60s?

That's a good question, and I'm not entirely sure. Maybe we should, but I would do that separately.

In the meantime, I would much more prefer to switch the DeleteCollection implementation to internally use pagination, as it would allow us to
1) not block on full list (and as a result make some progress)
2) would be some preparation towards potentially exposing a Limit option in the API...


/kind regression

**Comment by wojtek-t** [comment]
I suggest the following:

1. @tkashem - can you please take care of reverting the 34s timeout for DeleteCollection calls?
2. Once this is done, let's close this issue and continue operating on https://github.com/kubernetes/kubernetes/issues/90743

**Comment by tkashem** [comment]
@wojtek-t sounds good, thanks!

/assign
