### ISSUE TITLE
Test failing - sig-node - Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup guaranteed container's oom-score-adj should be -998

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#115045]
### Which jobs are failing?

* https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial
* https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Which tests are failing?

E2eNode Suite.[It] [sig-node] Container Manager Misc [Serial] Validate OOM score adjustments [NodeFeature:OOMScoreAdj] once the node is setup guaranteed container's oom-score-adj should be -998[Changes](https://github.com/kubernetes/kubernetes/compare/ca2f095cc...41976c813?)

### Since when has it been failing?

Last passing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1610918350311919616
First failing - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-cgroupv2-containerd-node-e2e-serial/1611099594949660672

Looks related to https://github.com/kubernetes/kubernetes/pull/108912

### Relevant SIG(s)

/sig node

**Comment by harche** [comment]
It seems like its also failing for node e2e serial job that uses crio, https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-serial-cri-o/1614799499333472256

**Comment by bobbypage** [comment]
This is no longer failing https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial&include-filter-by-regex=Validate%20OOM%20score%20adjustments&width=20

<img width="1621" alt="image" src="https://user-images.githubusercontent.com/486583/215925053-11d03b43-3809-481f-985c-3b7c7b7e08ef.png">

after https://github.com/kubernetes/kubernetes/pull/114981 was merged

**Comment by bobbypage** [comment]
Please re-open, but based on testgrid it looks like this is fixed.

/close
