### ISSUE TITLE
`plugin_execution_duration_seconds` in PreEnqueue

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#115083]
/kind feature
/sig scheduling

We don't support [`plugin_execution_duration_seconds`](https://github.com/kubernetes/kubernetes/blob/eabb70833a5649e10ab81f04423ce5cb16aba1b7/pkg/scheduler/metrics/metrics.go#L146) in PreEnqueue. It's worth implementing in PreEnqueue as well because the performance of PreEnqueue is critical for the whole scheduler's throughput.

/assign

**Comment by sanposhiho** [comment]
@Huang-Wei Is it intended that `plugin_execution_duration_seconds` isn't supported in PreEnqueue?

**Comment by Huang-Wei** [comment]
I _was_ thinking `PreEnqueue` is similar to `QueueSort`, which is not part of a standard scheduling flow. Moreover, `SchedulingGates` is pretty lightweight.

However, we may have out-of-tree PreEnqueue plugin in the future, and thus it's not a bad idea to record its execution time to reveal more insights into how these plugins are running. Would you like to work on it?

**Comment by sanposhiho** [comment]
> Would you like to work on it?

Yes, I can work on it. 
Actually, in my company, we're working on utilizing `PreEnqueue` for more effective scheduling. :)

**Comment by Huang-Wei** [comment]
SG. Then I'm going to track this item in #113608, and update the metric in https://github.com/kubernetes/enhancements/issues/3521.

BTW: if your testing env, what is the p95 duration of your PreEnqueue plugin?

**Comment by sanposhiho** [comment]
Thanks.

> if your testing env, what is the p95 duration of your PreEnqueue plugin?

Actually, we haven't even finalized the implementation and thus haven't rolled out the plugin yet.
