### ISSUE TITLE
Volumes cannot be expanded with out-of-tree CSI drivers

### ISSUE THREAD

**Issue by maxerenberg** [kubernetes/kubernetes#115044]
### What happened?

I was trying to add volume expansion support to an out-of-tree CSI driver (https://github.com/apalia/cloudstack-csi-driver), then when I actually tried to expand a volume which I had created, I saw an error message from kube-controller-manager saying "didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC".
After some debugging, I found that the `ProbeExpandableVolumePlugins` function in app/plugins.go does not call `csi.ProbeVolumePlugins()`, like the `ProbeAttachableVolumePlugins` function does. Instead, it creates a list of legacy volume plugins and a few hard-coded ones, but CSI is missing from that list:
https://github.com/kubernetes/kubernetes/blob/c2a7bfd6b4f147b40c3b2132aae003ff21a142bb/cmd/kube-controller-manager/app/plugins.go#L73
Later on, when trying to expand a volume, the `FindPluginBySpec` function in volume/plugins.go will return the error "no volume plugin matched" because CSI is not in its list of plugins.

Was CSI intentionally omitted? The [CSI developer documentation](https://kubernetes-csi.github.io/docs/volume-expansion.html) says that CSI drivers can implement volume expansion, so it seems odd that `ProbeExpandableVolumePlugins` does not include CSI in its list.

### What did you expect to happen?

I expected volumes to be expandable with out-of-tree CSI drivers.

### How can we reproduce it (as minimally and precisely as possible)?

Any out-of-tree CSI driver should do, but I have a fork of the CloudStack CSI driver to which I'm trying to add volume expansion support: https://github.com/maxerenberg/cloudstack-csi-driver

Follow the instructions in the README to deploy a new CSI driver (set allowVolumeExpansion to true when deploying the StorageClass), then create a PersistentVolumeClaim, attach it to a pod, and try to expand it.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
CloudStack v16.0.0
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux Kube2-control-185a20d9b3f 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

</details>

### Install tools

<details>
CloudStack Kubernetes provider (https://github.com/apache/cloudstack-kubernetes-provider)
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker with cri-dockerd (https://github.com/Mirantis/cri-dockerd)
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hkttty2009** [comment]
https://github.com/kubernetes-csi/external-resizer
CSI is usually expanded by external-resizer. 
I took a look at the cloudstack-csi-driver you mentioned, and it doesn't have external-resizer in its deploy yaml. So, I think this CSI may not support expansion yet.

**Comment by maxerenberg** [comment]
I see, thank you for pointing this out. I'll take a deeper look into the external-resizer.
