### ISSUE TITLE
Windows - [sig-node] PreStop should call prestop when killing a pod [Conformance]

### ISSUE THREAD

**Issue by marosset** [kubernetes/kubernetes#115136]
### Which jobs are flaking?

capz-e2e-windows-containerd-1.25

### Which tests are flaking?

[sig-node] PreStop should call prestop when killing a pod [Conformance]

### Since when has it been flaking?

Several months 

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-containerd-windows-1-25/1614649761036505088

### Reason for failure (if possible)

We think this is related to some issues with Calico CNI where the http endpoint cannot be reached due to a race condition between updates writing HNS rules and kubelet making a web-request from within the container.

### Anything else we need to know?

https://kubernetes.slack.com/archives/C0SJ4AFB7/p1649282390166899?thread_ts=1649175001.560109&cid=C0SJ4AFB7 

### Relevant SIG(s)

/sig windows

**Comment by marosset** [comment]
More discussion in https://kubernetes.slack.com/archives/C0SJ4AFB7/p1649282390166899?thread_ts=1649175001.560109&cid=C0SJ4AFB7

**Comment by claudiubelu** [comment]
similar prestop hook failure here: https://github.com/kubernetes/kubernetes/issues/108711#issuecomment-1116286496

**Comment by marosset** [comment]
Related to https://github.com/projectcalico/calico/issues/7332?
