### ISSUE TITLE
[KMSv2] Add `.Compact` method for LRU expire cache with lock

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#115174]
In a separate PR, lets add a `.Compact` method to this cache.  Since the cache keys we use will never repeat, they will only ever get evicted from the cache when it hits max size (meaning on a long lived cluster eventually the KMS cache will always be using 100 MB).

_Originally posted by @enj in https://github.com/kubernetes/kubernetes/pull/113121#discussion_r1073013573_

**Comment by kidddddddddddddddddddddd** [comment]
What do you mean by `compact`,  manually evict some keys regardless of their expiration time?

**Comment by enj** [comment]
/close

We decided against using this cache because it does not have the correct performance characteristics.
