### ISSUE TITLE
Seg Fault in nodeVolumeLimits of scheduler plugin causing panic

### ISSUE THREAD

**Issue by jayantjain93** [kubernetes/kubernetes#115178]
https://github.com/kubernetes/kubernetes/blob/cc68c06f9cb6c70cbb840a8d7b9ca49eb223cb3f/pkg/scheduler/framework/plugins/nodevolumelimits/csi.go#L233

`isCSIMigrationOn` handles cases when csiNode is nil. This is condition is used by cluster-autoscaler internal working. However, the log line refers to `csiNode.Name` causing seg fault

**Comment by alculquicondor** [comment]
cc @Jiawei0227

**Comment by tbak** [comment]
As far as I can tell this issue is only fixed in version 1.27 (by https://github.com/kubernetes/kubernetes/pull/115179). Is there a plan to port it back to releases 1.25 and 1.26 as well?

**Comment by liggitt** [comment]
it has already been picked to 1.25 and 1.26 (https://github.com/kubernetes/kubernetes/pulls?q=is%3Apr+115179+-base%3Amaster+is%3Aclosed) and will be in the next patch releases for those versions

**Comment by tbak** [comment]
@liggitt Great. Thank you for the pointer.
