### ISSUE TITLE
Kubelet will change the allocatable of the extended resource to the value of capacity

### ISSUE THREAD

**Issue by lujinda** [kubernetes/kubernetes#115190]
If I have an extended resource (such as disk iops), I also want to reserve a part of the resource. I hope there is a clearer reflection in node status. It seems impossible now.

https://github.com/kubernetes/kubernetes/blob/17422ff5c1195601cbbee87075171e16334b32c2/pkg/kubelet/cm/node_container_manager_linux.go#L227-L248

https://github.com/kubernetes/kubernetes/blob/17422ff5c1195601cbbee87075171e16334b32c2/pkg/kubelet/nodestatus/setters.go#L344-L356

Can the allocatable of extended resources also be set by the "extended resource controller"?

**Comment by cardyok** [comment]
Is there any further updates on this issue?

**Comment by mythi** [comment]
I'm noticing this behavior too and I find it wrong.

@lujinda @cardyok maybe ping on `#sig-node` Slack to get this triaged and/or commented?

**Comment by mythi** [comment]
@bart0sh would this be something you can help triage?

**Comment by bart0sh** [comment]
Sure, it looks like a valid issue to me.
/triage accepted

**Comment by bart0sh** [comment]
@SergeyKanzhelev can you suggest how to proceed further with this issue?
