### ISSUE TITLE
Consider upgrade to Kustomize latest version to date (4.5.7)

### ISSUE THREAD

**Issue by cazzoo** [kubernetes/kubernetes#115270]
### What happened?

Could you please consider upgrading Kustomize version to latest in order to support latest features, such as remote openapi files.

### What did you expect to happen?

I use Kustomize from argoCD application, it uses Kustomize to patch deployment resources and in my Kustomize file I cannot get the remote openapi file fetch.

### How can we reproduce it (as minimally and precisely as possible)?

Try to use https://github.com/kubernetes-sigs/kustomize/issues/4566 feature from a Kustomization file

### Kubernetes version

<details>

```console
$ kubectl version
1.23.10
```
![image](https://user-images.githubusercontent.com/1876754/214104080-cfc07764-c38b-42b7-b074-7ab95b9e3b5b.png)

</details>

### Cloud provider

<details>
Self-hosted cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
/sig cli
cc @KnVerey

**Comment by KnVerey** [comment]
As your version output screenshot shows, kustomize 4.5.7 is already available in kubectl 1.26. In fact, it was available since 1.25: https://github.com/kubernetes/kubernetes/pull/111606. 

/close

**Comment by cazzoo** [comment]
@KnVerey sorry I meant to update the kustomize version embed with the server, not the cli...

**Comment by KnVerey** [comment]
Kustomize is only embedded in the CLI (kubectl) and is a client-side-only tool.
