### ISSUE TITLE
support default ingress controller like default storageclass

### ISSUE THREAD

**Issue by willzhang** [kubernetes/kubernetes#115221]
### What would you like to be added?

support default ingress controller like default storageclass.

```
root@ubuntu:~# kubectl get ingressclass
NAME                             PROVISIONER              CLASS
ingress-nginx (default)   networking.k8s.io/v1             nginx
apisix-ingress-controller xxxx                             apisix  
```

### Why is this needed?

It is difficult to deploy out-of-the-box applications in the Kubernetes cluster，You can use helm to install applications with one click, but you must perform some additional configuration to access these applications, such as what storage and ingress gateway to use.

eg:

```
helm install wordpress
helm install harbor
helm install gitea
```

if there have a default ingress class, let application auto find a default one. then just access webui URL login.

**Comment by aojea** [comment]
Favoring one ingress implementation will kill the ecosystem, there is a considerable number of good options that people can use.

Also, the scope of ingress (and its evolution gateway-api) is very large , that makes it hard to handle and support in a standard implementation

/close

Thanks for your feedback
