### ISSUE TITLE
Building project (older commits) with Bazel fails

### ISSUE THREAD

**Issue by GareemaRanjan** [kubernetes/kubernetes#115261]
Hi, 

I am a research student at the University of Waterloo. I am trying to understand how to build the project using Bazel. I see that you have stopped using it since 2021. However, I was unable to get any commit working which was using Bazel as well. The commit that I have tried building projects is `a185bafa0c9142779a00fe7d3ba60726d04688c6`. It fails with the following error:

```
ERROR: /new-project/test/conformance/BUILD:40:8: Getting all conformance spec summaries. //test/conformance:list_conformance_specs failed (Exit 1) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
```

Any help would be highly appreciated.

**Comment by BenTheElder** [comment]
I'm sorry but these older releases are not supported anymore https://kubernetes.io/releases/

Even if it were, there's not enough info in this issue. You should probably use a tagged release commit if you pursue this further, but as you already noted the project is not using it anymore.
