### ISSUE TITLE
add integration tests for debug profiles

### ISSUE THREAD

**Issue by sding3** [kubernetes/kubernetes#115287]
@sding3 in a followup PR or in this PR(whichever you prefer), it would be good to add integration tests for all these profiles in here https://github.com/kubernetes/kubernetes/blob/30262e9b14e2369528fd27241adb16fae02f684d/test/cmd/debug.sh#L21

_Originally posted by @ardaguclu in https://github.com/kubernetes/kubernetes/issues/114280#issuecomment-1397966449_

**Comment by ardaguclu** [comment]
This looks duplicate of https://github.com/kubernetes/kubectl/issues/1372. Would you mind using the other one to track the progress and closing this one @sding3 ?
