### ISSUE TITLE
CSI migration race condition can cause unexpected detach and data loss

### ISSUE THREAD

**Issue by mattcary** [kubernetes/kubernetes#115297]
### What happened?

After the cluster was updated to enable PD CSI Driver, there was a race condition where AD Controller (kube-controller-manager) started to [populate the desired state of world](https://github.com/kubernetes/kubernetes/blob/dc2898b20c6bd9602ae1c3b51333e2e4640ed249/pkg/controller/volume/attachdetach/attach_detach_controller.go#L438-L447) BEFORE the PD CSI Driver was up, thus AD Controller gave us the error 

```
Error creating spec for volume "elasticsearch", pod "XXX"/"elasticsearch-0": error performing CSI migration checks and translation for PVC "dXX"/"elasticsearch-elasticsearch-0": in-tree plugin kubernetes.io/gce-pd is migrated on node gke-stage-XXXXX but driver pd.csi.storage.gke.io is not installed.
```

Then AD Controller triggered the disk detach because the disk/volume was not populated in the desired state of world.

Unfortunately the disk was in use during this detach and got corrupted.

### What did you expect to happen?

Since cluster upgrades can cause the controller manager and CSI drivers to start at different times, the AD controller needs to be more conservative when detaching

### How can we reproduce it (as minimally and precisely as possible)?

We have not been able to reproduce this, it came up from a customer.

### Anything else we need to know?

/sig storage
/assign @mattcary

### Kubernetes version

<details>
k8s 1.23, CSI migration enabled
</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by msau42** [comment]
I think there's potentially two changes we should do:
1) for the initial DSW population, we should skip the check that if the csi driver is not installed.
2) we should not skip volumes if an error is returned. If we had some temporary api server error then that would cause volumes to not get added to dsw and similar behavior happen. (https://github.com/kubernetes/kubernetes/blob/dc2898b20c6bd9602ae1c3b51333e2e4640ed249/pkg/controller/volume/attachdetach/attach_detach_controller.go#L446).

cc @gnufied @jingxu97

**Comment by msau42** [comment]
@mattcary for a repro, maybe you can try something like:

1. create a pod with volume and get it running
2. delete the csi driver node daemonset
3. restart kube-controller-manager

**Comment by msau42** [comment]
cc @sunnylovestiramisu

**Comment by mattcary** [comment]
/cc @songjiaxun 

@songjiaxun was trying to repro this, but on GKE with the managed driver which made it complicated.

**Comment by msau42** [comment]
Yeah maybe gce kube-up would be easier for a repro

**Comment by jsafrane** [comment]
If CSINode says that it has migrated GCP PD volume plugin to CSI, then IMO A/D controller should always attach GCP PD volumes to it using CSI, regardless if the CSI driver is present or not. In-tree volume plugin in the kubelet is disabled and can't mount any in-tree volumes anyway.

To flip the migration feature gate / upgrade / downgrade kubelet, the cluster admin must drain the node first to make sure everything is detached. A/D controller should not see change of CSINode migration annotations with any volume attached to it.

**Comment by gnufied** [comment]
Another option could be to process these volumes anyways but add them to DSOW with migration status as "uncertain", so as they can be re-processed later.  But surely it looks like @jsafrane might be easiest unless it has any downsides.

**Comment by mattcary** [comment]
There wasn't a node update in this case---there was a control plane update which restarted the PD CSI driver, and it looks like the CSIDriver resource was updated or changed in some way which raced with the kube-controller-manager restart.

**Comment by sunnylovestiramisu** [comment]
Is there anyway we can know if the csi driver is up and running(like a health check ping) before populating DSW?

**Comment by msau42** [comment]
We use the CSINode registration to determine that. The discussion here I think is concluding that we should not use that as a criteria for adding the volume to DSW. We only need to check that CSI migration is enabled on the node.

**Comment by mattcary** [comment]
+1 we need to be very resilient against races, I think we have to assume a driver is in process of being installed at any point in the AD controller reconcilliation.

**Comment by sunnylovestiramisu** [comment]
Reproduced with the steps:
> for a repro, maybe you can try something like:
> 
> 1. on a cluster with csi migration enabled (control plane + nodes)
> 2. create a pod with intree-volume and get it running
> 3. delete the csi driver node daemonset. verify the driver is removed from CSINode
> 4. restart kube-controller-manager

In /var/log/kube-controller-manager.log

```
E0131 17:50:21.980363       9 attach_detach_controller.go:440] Error creating spec for volume "task-pv-storage", pod "default"/"task-pv-pod": error performing CSI migration checks and translation for PVC "default"/"task-pv-claim": in-tree plugin kubernetes.io/gce-pd is migrated on node .... but driver pd.csi.storage.gke.io is not installed
```

**Comment by sunnylovestiramisu** [comment]
Tested with the [change here](https://github.com/kubernetes/kubernetes/compare/master...sunnylovestiramisu:kubernetes:fixCSIMigrationBug)

and doing the reproduce steps above. The error of ```Error creating spec for volume``` does not show up anymore. But the error message still get logged in the kube-controller-manager.log
