### ISSUE TITLE
kube-apiserver needed 150GB of memory to come up

### ISSUE THREAD

**Issue by allenfm1988** [kubernetes/kubernetes#115206]
Hi team/community,

My team and i recently ran into issues with the kube-apiserver which needed 150GB of memory to come up after an issue with etcd (it got down), api-server was previously running with 40GB of configured memory and actually using less than 16GB, but right after etcd got back up the api-server consumed such huge amount memory in order to start running.

Has anybody faced a situation like me in which api-server consumes huge memory when it starts running after a failure or down?

Here are the cluster components at a high level:

Master nodes (3 nodes):
master001    Ready                      master    693d   v1.19.9
master002    Ready                      master    693d   v1.19.9
master003    Ready                      master    693d   v1.19.9

Worker-minions nodes (417 nodes):
minion001    Ready                      minion    693d   v1.19.9
minion002    Ready                      minion    693d   v1.19.9
minion003    Ready                      minion    693d   v1.19.9
minion004    Ready                      minion    693d   v1.19.9
minion005    Ready                      minion    693d   v1.19.9
minion006    Ready                      minion    693d   v1.19.9
minion007    Ready                      minion    693d   v1.19.9
minion008    Ready                      minion    693d   v1.19.9
...
ingress (3 nodes):
ingress001   Ready                      ingress   693d   v1.19.9
ingress002   Ready                      ingress   693d   v1.19.9
ingress003   Ready                      ingress   693d   v1.19.9

Etcd(5 nodes)

Thank you so much.

**Comment by HirazawaUi** [comment]
v1.19.9 is an non-active branch, this means it is no longer supported,  please use a newer version of kubernetes for testing, FYI. https://kubernetes.io/releases/release/

**Comment by allenfm1988** [comment]
Hi @HirazawaUi,
Do you have by any chance a ticket previously issued that i can take as a reference about a similar situation like the one i'm describing on this ticket?
Thank you.

**Comment by pacoxu** [comment]
There are some apiserver memory leaks issues like https://github.com/kubernetes/kubernetes/issues/96259 and https://github.com/kubernetes/kubernetes/issues/98423.

Either ways below may help:
1. You may try a new version to see if the issue is resolved.
2. Use apiserver profiling to analyze the problem. `debug/pprof/`
3. Check pod numbers or other resources or CRs.

**Comment by kerryeon** [comment]
We had the same problem.
And we found that just **limiting the memory resource** could resolve it like below:

```yaml
# /etc/kubernetes/manifests/kube-apiserver.yaml
...
    resources:
      requests:
        cpu: 250m  # set by default
        memory: 256M
      limits:
        cpu: 2000m
        memory: 1G  # Add it!
```

It is up to the operator to balance performance and memory capacity.
