### ISSUE TITLE
[Problem in update] The following signatures couldn't be verified because the public key is not available: NO_PUBKEY

### ISSUE THREAD

**Issue by kevinadhiguna** [kubernetes/kubernetes#115237]
### What happened?

I tried to update OS (including Kubernetes) and it said :

```
...
Get:17 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8,993 B]
Err:17 https://packages.cloud.google.com/apt kubernetes-xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
...
```

### What did you expect to happen?

No error in updating Kubernetes

### How can we reproduce it (as minimally and precisely as possible)?

Follow steps to install Kubernetes and try to update OS (Ubuntu 22.04)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>
No Cloud Provider
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
# paste output here
Linux user 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kevinadhiguna** [comment]
Was there a scheduled maintenance or an update in APT repository?

**Comment by yuval-k** [comment]
cross ref: https://github.com/kubernetes/release/issues/2862 https://github.com/kubernetes/website/pull/41307
