### ISSUE TITLE
dynamic resource allocation: allow a kubelet-plugin to service allocations from multiple resource-driver controllers

### ISSUE THREAD

**Issue by klueska** [kubernetes/kubernetes#115263]
The goal is to allow one to write a custom controller such as the one below to (e.g.) co-allocate GPUs and RDMA interfaces (using a custom `ResourceClass` and associated `ClaimParameters` object), but allow the "default" kubelet-plugins for these resources to handle the actual device preparation and injection.

<img width="1055" alt="Bildschirmfoto 2023-01-19 um 12 13 43" src="https://user-images.githubusercontent.com/96419/214029367-c5997716-dcb4-4f80-8a76-d54758209fb6.png">

**Note:** An older version of this description was too specific and suggested that we add an extension to the kubelet-plugin API to include an RCP called `WatchConfiguration`. Some of the comments at the beginning of this issue are in reference to that. We have since refined our thinking on how to do achieve the same goal, and those changes are reflected in https://github.com/kubernetes/enhancements/pull/3802

**Comment by bart0sh** [comment]
I like the idea. One question so far:  Is my understanding correct that `WatchConfigurationResponse` is expected to always contain all supported driver names? This would allow to dynamically add and also remove names.

**Comment by klueska** [comment]
Yes, that is how it should be interpreted. Anytime the plugin has a new controller "register" with it, it should update the kubelet with a full list of driver names. This list may grow or shrink over time (but it should always contain at least one entry -- the name of the "default" driver that it is associated with).

**Comment by bart0sh** [comment]
> it should always contain at least one entry -- the name of the "default" driver that it is associated with

From another point of view if plugin decides that for some reason it can't serve claims for the `ResourceClass`es with its default DriverName, it can remove default name from the list. We might want to allow this, but this is a minor detail.

**Comment by klueska** [comment]
Sure. I guess no matter what, the kubelet code should make sure to handle the case of an empty list being returned (though I assume this will almost never be the case).

**Comment by klueska** [comment]
In general, I pictured the kubelet code doing the following to support this:
1. Open a persistent watch on the new WatchConfiguration() call of each registered plugin
2. For each unique "driver name" (across all plugin configurations), maintain a list of all the plugins that should be triggered when a claim comes in that references that driver name
3. Update the code in the following to loop over all plugins associated with a claim referencing a given driver name:
     https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/dra/manager.go#L110...L131
4. Concatenate the set of cdi devices passed back by each plugin into one

**Comment by bart0sh** [comment]
@klueska Can you give an example where we want to dynamically update the list of driver names for the plugin? I mean if plugin can handle different claim classes why wouldn't it just inform kubelet about it once?

**Comment by klueska** [comment]
The idea of making the list dynamic (via a watch) is just to allow new controllers to dynamically register themselves with a plugin after it is  already up and running (without needing to restart it).

The scenario would be:
1. Default GPU driver gets deployed (`gpu.resource.nvidia.com`)
2. Default RDMA driver gets deployed (`net.resource.nvidia.com`)
3. At this point any `ResourceClasses` that reference the `gpu.resource.nvidia.com` driver name will go through the controller associated with the default GPU driver, and any claims it allocates will eventually be serviced by the plugin associated with the default GPU driver.
4. Likewise, any `ResourceClasses` that reference the `net.resource.nvidia.com` driver name will go through the controller associated with the default RDMA driver, and any claims it allocates will eventually be serviced by the plugin associated with the default RDMA driver.
5. Once this is up and running, a new controller with driver name `custom.resource.nvidia.com` gets deployed. To allow its claim allocations to ultimately be serviced by both the default GPU driver's kubelet plugin and the default RDMA driver's kubelet plugin, it "registers" itself with these components so that they can update their lists of associated driver names with the kubelet (how this "registration" happens it out of scope of this feature, but would most likely be via a CRD).
6. At this point any `ResourceClasses` that reference the `custom.resource.nvidia.com` driver name will go through the new custom controller, and any claims it allocates will eventually be serviced by both the plugin associated with the default GPU driver and the plugin associated with the default RDMA driver.

It's not strictly necessary for custom controllers to dynamically "register" themselves with a plugin (e.g. one could supply a static list of supported driver names to a plugin via a command line flag). But I wanted to at least make the API to the kubelet support dynamism so that one would have the option to be more dynamic if they wanted.
