### ISSUE TITLE
[Failing test] ci-kubernetes-verify-master.verify-master

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/kubernetes#115289]
### Which jobs are failing?

[ci-kubernetes-verify-master](https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify-master)

### Which tests are failing?

ci-kubernetes-verify-master.verify-master, commit 674eb36f9

### Since when has it been failing?

1/23 13:38 PST

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

```
unable to identify if etcd is bound to port 2379. unable to find ss or netstat utilities.
+++ [0123 22:26:13] Clean up complete
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-openapi-spec.sh	119s
Verifying verify-pkg-names.sh
+++ Running case: verify.pkg-names 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-pkg-names.sh"
943 skipped lines...
  found dependency code-generator
Done.
+++ exit code: 0
SUCCESS  verify-publishing-bot.py	1s
========================
[0;31mFAILED TESTS
========================
[0;31mhack/make-rules/../../hack/verify-openapi-spec.sh
make: *** [Makefile:128: verify] Error 1
+ EXIT_VALUE=2
+ set +o xtrace
Cleaning up after docker in docker.
================================================================================
Cleaning up after docker
```

### Anything else we need to know?

Around the same time there are failures that appear config or infra related for scalability tests (https://github.com/kubernetes/kubernetes/issues/115284), as well as another failing test from test infra (https://github.com/kubernetes/kubernetes/issues/115288).

### Relevant SIG(s)

/sig testing

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/28485
