### ISSUE TITLE
[Failing test] ci-kubernetes-e2e-gci-gce-scalability failing on startup since 1/23 13:24 PST

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/kubernetes#115284]
### Which jobs are failing?

ci-kubernetes-e2e-gci-gce-scalability

### Which tests are failing?

Testgrid looks a bit odd as `*.Overall` is red while `.Pod` is green and nothing else is run; IMHO it appears that its exiting on a build/infra step.

<img width="432" alt="Screen Shot 2023-01-23 at 3 30 55 PM" src="https://user-images.githubusercontent.com/5643703/214175736-0ed28c26-2391-4fde-9d2d-f322a99a9ae7.png">

### Since when has it been failing?

Last 4 builds, since 1/23 13:24 PST, commit 674eb36f9

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100

### Reason for failure (if possible)

```
Activated service account credentials for: [prow-build@k8s-infra-prow-build.iam.gserviceaccount.com]
+ WRAPPED_COMMAND_PID=[2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1617633965353472000#1:build-log.txt%3A2)8
+ wait 28
+ /workspace/scenarios/kubernetes_e2e.py --check-leaked-resources --cluster=e2e-big '--env=APISERVER_TEST_ARGS=--max-requests-inflight=80 --max-mutating-requests-inflight=0 --profiling --contention-profiling' --env=HEAPSTER_MACHINE_TYPE=e2-standard-8 --extract=ci/latest-fast --extract-ci-bucket=k8s-release-dev --gcp-node-image=gci --gcp-nodes=100 --gcp-project-type=scalability-project --gcp-zone=us-east1-b --provider=gce --metadata-sources=cl2-metadata.json --env=CL2_ENABLE_DNS_PROGRAMMING=true --env=CL2_SCHEDULER_THROUGHPUT_THRESHOLD=0 --env=CL2_ENABLE_API_AVAILABILITY_MEASUREMENT=true --env=CL2_API_AVAILABILITY_PERCENTAGE_THRESHOLD=99.5 --test=false '--test-cmd=$GOPATH/src/k8s.io/perf-tests/run-e2e.sh' --test-cmd-args=cluster-loader2 --test-cmd-args=--experimental-gcp-snapshot-prometheus-disk=true --test-cmd-args=--experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-16176[3](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1617633965353472000#1:build-log.txt%3A3)3965353[4](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1617633965353472000#1:build-log.txt%3A4)72000 --test-cmd-args=--experimental-prometheus-snapshot-to-report-dir=true --test-cmd-args=--nodes=100 --test-cmd-args=--prometheus-scrape-kubelets=true --test-cmd-args=--prometheus-scrape-node-exporter --test-cmd-args=--provider=gce --test-cmd-args=--report-dir=/logs/artifacts --test-cmd-args=--testconfig=testing/load/config.yaml --test-cmd-args=--testconfig=testing/huge-service/config.yaml --test-cmd-args=--testconfig=testing/access-tokens/config.yaml --test-cmd-args=--testoverrides=./testing/experiments/enable_restart_count_check.yaml --test-cmd-args=--testoverrides=./testing/experiments/use_simple_latency_query.yaml --test-cmd-args=--testoverrides=./testing/overrides/load_throughput.yaml --test-cmd-name=ClusterLoaderV2 --timeout=120m --use-logexporter --logexporter-gcs-path=gs://sig-scalability-logs/ci-kubernetes-e2e-gci-gce-scalability/161763396[5](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1617633965353472000#1:build-log.txt%3A5)353472000
/usr/bin/env: 'python': No such file or directory
+ EXIT_VALUE=127
+ set +o xtrace
```

### Relevant SIG(s)

/sig scalability

**Comment by lauralorenz** [comment]
As of now CI Signal considers this blocking tomorrow's release cut (see [slack thread](https://kubernetes.slack.com/archives/CJH2GBF7Y/p1674517338505139)), I appreciate insight from sig scalability folks directly on whether it should remain a blocker for that or not.

cc 1.27 release lead @cici37, sig-scalability leads @marseel, @shyamjvs, @wojtek-t 

thank you!!

**Comment by liggitt** [comment]
This looks like the same issue we rolled back the bootstrap / kubekins image for already - https://kubernetes.slack.com/archives/C09QZ4DQB/p1674253231293259

that fixed presubmits, I wonder if the scale test got stuck on the bad kubekins image

**Comment by liggitt** [comment]
Rollbacks were linked from https://github.com/kubernetes/test-infra/pull/28466#issuecomment-1399029547

**Comment by lauralorenz** [comment]
X-post from various chats but want to cross reference here that while it may be related to the above, the rollback mentioned above was on a PR merged 3 days ago, so either it's not that OR it is but some other configuration downstream that this job uses needs to be updated/bumped/kicked/convinced to be in the same state as that rollback. 

I don't have good context on how to triangulate config changes for this job (it fails at k/k commit 674eb36f92dcea33e47ac07d71d88ebe9f5c4c6d but I suspect that's not the issue) so defer again to sig-scalability for insight here (again most immediately whether this is a blocker for the 1.27 release cut or not).

**Comment by nikhita** [comment]
Created https://github.com/kubernetes/test-infra/pull/28485

**Comment by lauralorenz** [comment]
Testgrid is green for the past 6 runs since 01:03 AM PST, fix was merged 12:40 AM PST, considering this fixed.

/close
