### ISSUE TITLE
kmsv2: add metric for current size of DEK seed cache

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#115275]
Follow-up to https://github.com/kubernetes/kubernetes/issues/111920.

- [ ] Add metrics for cache fill percentage of the seed cache
- [ ] Add [TestEnvelopeCacheLimit](https://github.com/kubernetes/kubernetes/blob/674eb36f92dcea33e47ac07d71d88ebe9f5c4c6d/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope_test.go#L180-L216) unit test back if it's relevant with new cache implementation.

/sig auth
/kind feature

**Comment by aramase** [comment]
ref: https://github.com/kubernetes/kubernetes/pull/113121#pullrequestreview-1270081475

**Comment by aramase** [comment]
This is `v1.28` blocker if https://github.com/kubernetes/kubernetes/issues/117725 is going to be done!

**Comment by aramase** [comment]
If we decide to go ahead this implementation, we need to consider adding a metric for eviction (xref: https://github.com/kubernetes/kubernetes/pull/90650)

**Comment by enj** [comment]
> This is `v1.28` blocker if #117725 is going to be done!

That issue was moved to #118831

**Comment by enj** [comment]
/retitle kmsv2: add metric for current size of DEK seed cache

**Comment by enj** [comment]
We decided that we can keep using the existing LRU cache with a TTL/unbounded size for the DEK seeds.  This issue now tracks adding a metric that emits the current size of that seed cache which will give the cluster operator a sense of how many KMS calls will be required on a restart of the API server.
