### ISSUE TITLE
Remove getting PrevKv for apiserver for most kind of objects

### ISSUE THREAD

**Issue by d3c3mber** [kubernetes/kubernetes#115376]
Details: 
For etcd, whether it is native etcd or other customized version of etcd, if K8s apiserver wants to obtain PrevKv, etcd needs to do a Range operation for every event.
Range for native etcd is operated on local boltdb, it takes time in less than 1s, on the order of ms. But the aggregation of all range operations can take seconds.

Given the below code in etcd3/watcher.go where apiserver is taking all objects of a kind (e.g, Pod, Node, ConfigMap, etc), oldObj is not needed. So in this case, etcd's operation for getting PrevKv can be removed. 

```
// transform transforms an event into a result for user if not filtered.
func (wc *watchChan) transform(e *event) (res *watch.Event) {
	curObj, oldObj, err := wc.prepareObjs(e)
......
	switch {
	case e.isDeleted:
......
	case e.isCreated:
......
	case e.isProgressNotify:
......
	default:
		if wc.acceptAll() {
			res = &watch.Event{
				Type:       watch.Modified,
				Object:     curObj,
			}
			return res
		}
......
}
```

If this is a valid change, I'd like to submit the proposal and change of code, and love to hear your suggesitons, thanks
/sig api-machinery
/sig scalability
cc @wojtek-t

**Comment by wojtek-t** [comment]
> Given the below code in etcd3/watcher.go where apiserver is taking all objects of a kind (e.g, Pod, Node, ConfigMap, etc), oldObj is not needed. So in this case, etcd's operation for getting PrevKv can be removed.

It is still needed for deletions.

**Comment by wojtek-t** [comment]
WithPrevKV() is an option at the watch-level:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L236

You can't set it differently for deletions vs updates.

**Comment by lavalamp** [comment]
I think it is needed for updates so that filters work correctly.

**Comment by logicalhan** [comment]
I'm pretty sure we cannot trivially remove this.

**Comment by d3c3mber** [comment]
thanks very much for your reply :)
let me add more details to the implementation, this may not be a K8s-only change, it also involves changes on the etcd side.

go.etcd.io/etcd/clientv3/op.go
```
// Op represents an Operation that kv can execute.
type Op struct {
.....
	// for watch, put, delete
	prevKV bool
......
}
```

can be changed to 
type Op struct {
.....
	// for put
	prevKVforUpdate bool

	// for delete
	prevKVforUpdate bool
......
}

and for etcd, 
in server/etcdserver/api/v3rpc/watch.go
```
                         needPrevKV := sws.prevKV[wresp.WatchID]
			sws.mu.RUnlock()
			for i := range evs {
				events[i] = &evs[i]
				if needPrevKV && !IsCreateEvent(evs[i]) {
					opt := mvcc.RangeOptions{Rev: evs[i].Kv.ModRevision - 1}
					r, err := sws.watchable.Range(context.TODO(), evs[i].Kv.Key, nil, opt)
					if err == nil && len(r.KVs) != 0 {
						events[i].PrevKv = &(r.KVs[0])
					}
				}
			}
```

may be changed to sth like
```
                         needPrevKVforUpdate := sws.prevKVforUpdate[wresp.WatchID]
                         needPrevKVforDelete := sws.prevKVforUpdate[wresp.WatchID]
			sws.mu.RUnlock()
			for i := range evs {
				events[i] = &evs[i]
				if needPrevKVforUpdate && IsUpdateEvent(evs[i]) {
					opt := mvcc.RangeOptions{Rev: evs[i].Kv.ModRevision - 1}
					r, err := sws.watchable.Range(context.TODO(), evs[i].Kv.Key, nil, opt)
					if err == nil && len(r.KVs) != 0 {
						events[i].PrevKv = &(r.KVs[0])
					}
				}
				if needPrevKVforDelete && IsDeleteEvent(evs[i]) {
					opt := mvcc.RangeOptions{Rev: evs[i].Kv.ModRevision - 1}
					r, err := sws.watchable.Range(context.TODO(), evs[i].Kv.Key, nil, opt)
					if err == nil && len(r.KVs) != 0 {
						events[i].PrevKv = &(r.KVs[0])
					}
				}
			}
```

and in apiserver

```
func (wc *watchChan) startWatching(watchClosedCh chan struct{}) {
	if wc.initialRev == 0 {
		if err := wc.sync(); err != nil {
			klog.Errorf("failed to sync with latest state: %v", err)
			wc.sendError(err)
			return
		}
	}
	opts := []clientv3.OpOption{
		clientv3.WithRev(wc.initialRev + 1),
		clientv3.WithPrevKV(),
		clientv3.WithProgressNotify(),
	}
```
may be changed to sth like:

```
func (wc *watchChan) startWatching(watchClosedCh chan struct{}) {
......
	opts := []clientv3.OpOption{
		clientv3.WithRev(wc.initialRev + 1),
		clientv3.WithPrevKVforDelete(),
		clientv3.WithProgressNotify(),
	}
```

**Comment by d3c3mber** [comment]
the reason is `r, err := sws.watchable.Range(context.TODO(), evs[i].Kv.Key, nil, opt)` in server/etcdserver/api/v3rpc/watch.go is causing latency in watch operation
and for customized version of etcd or other storage that implements etcd interface (say we'd like to store 5million keys, which exceeds etcd's current limit), the range operation may take even more time (to the degree of seconds)

**Comment by lavalamp** [comment]
Filtered watches (label or field selection) must have the prior object in order to tell what to do when the labels / fields being filtered by change. We depend on getting the prior object. We can't change this.

You will have to optimize the DB instead, sorry.

**Comment by d3c3mber** [comment]
> Filtered watches (label or field selection) must have the prior object in order to tell what to do when the labels / fields being filtered by change. We depend on getting the prior object. We can't change this.
@lavalamp Are you referring to watches that go directly to etcd? Apiserver is watching all pods or nodes, and it will fall into the wc.acceptAll() case, would it be ok for apiserver itself to ignore prevKv

**Comment by d3c3mber** [comment]
> ching all pods or nodes, and it will fall into the wc.acceptAll() case, would it be ok for apiserver itself to ignore prevKv



> > Given the below code in etcd3/watcher.go where apiserver is taking all objects of a kind (e.g, Pod, Node, ConfigMap, etc), oldObj is not needed. So in this case, etcd's operation for getting PrevKv can be removed.
> 
> It is still needed for deletions.

@wojtek-t is it OK for deletions that apiserver gets oldObj(prevKv) from watchcache? because for watchcache's indexer, only object key is needed for deletion; and for the construction of watchCacheEvent, use the existing object in watchcache.

**Comment by wojtek-t** [comment]
There is no guarantee that watchcache will be enabled.

**Comment by d3c3mber** [comment]
@wojtek-t  could you please explain more in what scenario watchcache is enabled/disabled, i thought it is turned on for all built-in resources and CRDs where the default is 100, and it is only disabled for event.

**Comment by wojtek-t** [comment]
That's the default configuration, but administrators can enable/disable it differently.
