### ISSUE TITLE
1.25.6 package depends on cri-tools >= 1.26.0

### ISSUE THREAD

**Issue by cbartz** [kubernetes/kubernetes#115392]
I was trying to upgrade a k8s cluster from 1.24.x to 1.25.6 using ``kubeadm``. It failed due to installing ``cri-tools >= 1.26`` (resulting in errors related to https://kubernetes.io/blog/2022/11/18/upcoming-changes-in-kubernetes-1-26/#cri-api-removal because containerd 1.5 is used) which is a dependency for 1.25.6 (but not 1.25.5).
I was able to upgrade to 1.25.5 with no problems, and I think the dependencies for 1.25.6 are wrong.

System: `` Ubuntu 20.04.5 LTS``
Repo: ``https://apt.kubernetes.io/ kubernetes-xenial main`` (resolves to ``https://packages.cloud.google.com/apt``)

Relevant output of ``apt show kubeadm`` 

```
Package: kubeadm
Version: 1.25.6-00
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 43.8 MB
Depends: kubelet (>= 1.19.0), kubectl (>= 1.19.0), kubernetes-cni (>= 1.2.0), cri-tools (>= 1.26.0)
Homepage: https://kubernetes.io
Download-Size: 9230 kB
APT-Sources: https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.

Package: kubeadm
Version: 1.25.5-00
Priority: optional
Section: misc
Maintainer: Kubernetes Authors <kubernetes-dev+release@googlegroups.com>
Installed-Size: 43.8 MB
Depends: kubelet (>= 1.19.0), kubectl (>= 1.19.0), kubernetes-cni (>= 1.1.1), cri-tools (>= 1.25.0)
Homepage: https://kubernetes.io
Download-Size: 9229 kB
APT-Manual-Installed: yes
APT-Sources: https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
Description: Kubernetes Cluster Bootstrapping Tool
 The Kubernetes command line tool for bootstrapping a Kubernetes cluster.

```

**Comment by saschagrunert** [comment]
We reverted that change and the next set of Februar patches should fix that bug.
