### ISSUE TITLE
[Failing test] capg-conformace-main-ci-artifacts

### ISSUE THREAD

**Issue by gracenng** [kubernetes/kubernetes#115361]
### Which jobs are failing?

master-informing
capg-conformace-main-ci-artifacts

### Which tests are failing?

periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts

### Since when has it been failing?

01-26-2023 14:29 PST

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-informing#capg-conformance-main-ci-artifacts

### Relevant SIG(s)

/sig-cluster-api
(provider-gcp)

cc @lauralorenz

**Comment by pacoxu** [comment]
The CI is green now.
```
make: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api-provider-gcp'
kustomize not found, installing
./scripts/ci-conformance.sh: line 215: python: command not found
+ EXIT_VALUE=127
+ set +o xtrace
```

/close
