### ISSUE TITLE
Pod Security Standards vs Service Mesh

### ISSUE THREAD

**Issue by szimonek** [kubernetes/kubernetes#115396]
### What happened?

Pod Security Standards (https://kubernetes.io/docs/concepts/security/pod-security-standards/) went beta at v1.23. Pod Security Standards are direct ascendant of Pod Security Policies which were deprecated in v1.21 and removed in v1.25.

Pod Security Standards  definies three policies: Privileged, Baseline and Restricted. Enforcing Baseline or Restricted policy, would limit allowed capabilities that Pod can use. The problem is that when enforced both policies disallows for NET_ADMIN capability which is required i.e. to run sidecar of Service Mesh like ISTIO (https://istio.io/latest/docs/ops/deployment/requirements/#pod-requirements)

### What did you expect to happen?

I expect that in a Namespace that enforces one of Pod Sscurity Standards policy can exist ISTIO-aware Pods. I'm aware that NET_ADMIN is very powerfull capability, but without it we can't have both of these.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Namespace which enforces Baseline or Restricted policy and allows auto-injecting ISTIO sidecar.
2. Check if Istio sidecar will start.

### Anything else we need to know?

I think there is a need for:
- another Pod Security Standards lighter than Baseline dedidated to Service Meshes
- mechanism for defining custom PSS policies
- PSS annotation(s) that add extensions/exclusions to enforced policy
-

### Kubernetes version

Any version above 1.23
<details>

I'm using Rancher Kuberneter Engine 2:
```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+rke2r1", GitCommit:"b39bf148cd654599a52e867485c02c4f9d28b312", GitTreeState:"clean", BuildDate:"2022-09-21T17:05:47Z", GoVersion:"go1.18.6b7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7+rke2r1", GitCommit:"e6f35974b08862a23e7f4aad8e5d7f7f2de26c15", GitTreeState:"clean", BuildDate:"2022-10-13T18:58:02Z", GoVersion:"go1.18.7b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Irrelevant

### OS version

Irrelevant

### Install tools

Irrelevant

### Container runtime (CRI) and version (if applicable)

Irrelevant

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Irrelevant

**Comment by liggitt** [comment]
/remove-kind bug
/close

> The problem is that when enforced both policies disallows for NET_ADMIN capability which is required i.e. to run sidecar of Service Mesh like ISTIO

This was considered and is a known interaction, but is consistent with disallowing elevated capabilities in low-privilege pods / namespaces.

The recommendation is to run istio in an [ambient mesh](https://istio.io/latest/blog/2022/get-started-ambient/) mode that does not require injecting high-privilege containers into every pod.
