### ISSUE TITLE
Kubelet runs in systemd mode, and `homeDirPath` is "" in `pkg/credentialprovider/config.go`

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#115389]
### What happened?

If kubelet is running in systemd mode and `User` is not configured in `kubele.servcie`, according to the following function：
https://github.com/kubernetes/kubernetes/blob/7b243cef1a81f4a0ac1619f7b9238fcd2bac2b9c/pkg/credentialprovider/config.go#L88-L95

the path order for kubelet to find docker `config.json` or `.dockercfg` is as follows:
```
/var/lib/kubelet/config.json
/var/lib/kubelet/.docker/config.json
/.docker/config.json

/var/lib/kubelet/.dockercfg
/var/lib/kubelet/.dockercfg
/.dockercfg
```
Therefore, the `homeDirPath` variable is "",
https://github.com/kubernetes/kubernetes/blob/7b243cef1a81f4a0ac1619f7b9238fcd2bac2b9c/pkg/credentialprovider/config.go#L64

Should we improve it to get the real user home of kubelet？

### What did you expect to happen?

`homeDirPath` is the real user home directory

### How can we reproduce it (as minimally and precisely as possible)?

Kubelet runs in systemd mode and `User` is not configured in `kubele.servcie`

### Kubernetes version

v1.22.3

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Previously reported at https://github.com/kubernetes/kubernetes/issues/45487#issuecomment-312042754

I think this is better documented than changed, since it is easy to configure a user and existing invocations could rely on the empty envvar lookup behavior at this point
