### ISSUE TITLE
Aggregated Discovery doesn't show aggregated apiservices as Stale before initial health check

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/kubernetes#115303]
### What happened?

[Quote from KEP 3352](https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3352-aggregated-discovery#aggregation):

> A post start hook will be added and the kube-apiserver health check should only pass if the discovery document is ready. Since aggregated api servers may take longer to respond and we do not want to delay cluster startup, the health check will only block on the local api servers (built-ins and CRDs) to have their discovery ready. For api servers that have not been aggregated, their group-versions will be published with an empty resource list and a Stale for Freshness to indicate that they have not synced yet.

This requirement is not met. Explanation in first comment shows we wait for local services to sync before health check, but we do not include aggregated apiservices that had not yet synced as Stale.

/cc @Jefftree @apelisse 
/sig api-machinery

### What did you expect to happen?

Unsynced aggregated APIServices which appear in the initial list for apiserver are included in document before health check with empty resource list and `Stale` freshness.

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

<details>

1.26-1.27
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

N/A

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by alexzielenski** [comment]
I think for this one we almost have all our bases covered. For context, there is a single `AggregatedDiscoveryGroupManager` used by all of apiserver, apiextensions-apiserver, and aggregated-apiserver:

It is attached to genericConfig and the instance is shared by all three genericapiserver instances.

https://github.com/kubernetes/kubernetes/blob/201caf28b270d73c31b4f1f358548b1be608446c/cmd/kube-apiserver/app/server.go#L477-L479

For builtin types, the `genericapiserver` adds its types directly during initialization to the shared `AggregatedDiscoveryGroupManager ` when installing APIs, so there is no need to wait in a post-start hook for builtins:

https://github.com/kubernetes/kubernetes/blob/201caf28b270d73c31b4f1f358548b1be608446c/staging/src/k8s.io/apiserver/pkg/server/genericapiserver.go#L706-L712

For CRDs there is a post-start hook to wait for discovery controller to sync initial list of CRDs. This uses the same `AggregatedDiscoveryGroupManager` instance used by genericapiserver.

https://github.com/kubernetes/kubernetes/blob/60d73ba75148483d150622a4d8b6e122e189ceab/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go#L213

https://github.com/kubernetes/kubernetes/blob/60d73ba75148483d150622a4d8b6e122e189ceab/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go#L250-L255

Aggregated APIServer also uses the same `DiscoveryResourceManager` and is not responsible for syncing any local APIServices.

The only thing missing from this requirement is that aggregated APIServices are not present in the initial document as `Stale`.

**Comment by ardaguclu** [comment]
@alexzielenski please correct me if I'm missing something but isn't the purpose of `dirtyAPIServiceQueue` [field](https://github.com/kubernetes/kubernetes/blob/ed98c1da6d5fd1382a97663038c0fedbc02ebf9f/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go#L85) already adding APIServices as Stale?.

You summarized code navigation pretty well above, I started looking at the issue in case I can fix it, but I couldn't find the bug :)

**Comment by Jefftree** [comment]
Not sure if this was addressed but I'm going to make a pass on this and make sure it's fixed for GA.

/assign
