### ISSUE TITLE
Create equivalent of commit golden `swagger.json` that includes CRDs

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#115351]
We have no way to really detect if the way we generate OpenAPI for CRDs is stable today, I've suggested something here:
https://github.com/kubernetes/kubernetes/pull/114439/files#r1088302582

We have to be careful since the CRDs are not aggregated synchronously so it could be racy.

/wg api-expression
/triage accepted
/cc @alexzielenski @Jefftree

**Comment by Jefftree** [comment]
@apelisse With the caching you're adding for OpenAPI, CRDs should be aggregated synchronously on request right?

I do agree that we should have some kind of golden test data for CRDs. Would probably suggest against dumping it with the swagger.json as I believe there are a number of downstream projects that download it to get the list of k/k built-in types but something in addition to that process in update-openapi-spec.sh seems fine.

**Comment by Jefftree** [comment]
Let's revisit this, not just for golden comparisons but also to have a static set of CRDs perform benchmarking against. I don't think we have a proper fuzzer that passes validation for CRDs, what do you think of using a subset of actual CRDs from other k8s projects (eg: Crossplane)?
