### ISSUE TITLE
AggregatedDiscovery controller does not purge old APIServices from cache

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/kubernetes#115301]
### What happened?

The [cachedResults list](https://github.com/kubernetes/kubernetes/blob/60d73ba75148483d150622a4d8b6e122e189ceab/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go#L81-L83) in apiserver grows infinitely without ever purging serviceKeys which are not referenced by any APIServices.

/sig api-machinery
/cc @Jefftree @apelisse 
/assign

### What did you expect to happen?

a limited size cache

### How can we reproduce it (as minimally and precisely as possible)?

1. Create APIService
2. Change your services Spec.Service field to a new address
3. Repeat step 2 and watch the list grow

### Kubernetes version

<details>

1.26-1.27

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
N/A
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by gdhuper** [comment]
@alexzielenski what do we want to the limit the cache size by?

**Comment by alexzielenski** [comment]
the cache currently doesn't purge `serviceKey`s which are not being used by an `apiService`

**Comment by apelisse** [comment]
> is this still an issue? 
Yes

> should it be resolved before enabling by default?

That's the cache for the downloaded discovery for each apiservice. The list probably doesn't grow very large. Fix is in #116828. Considering the pain of non-aggregated discovery on some users, and the time they have had to wait to get the feature, I'd say the trade-off is that this isn't nearly as bad.

**Comment by alexzielenski** [comment]
It's also worth noting that the cache should only grow for Aggregated APIServices that themselves expose aggregated discovery endpoint. We don't store a cache entry here otherwise. The list doesn't grow unless the aggregated discovery document was successfully fetched.

This is a very rare case and especially at release a minuscule number of people might run into it. And even then it is not likely to be changing the service so often once it is working enough to store a cache entry.
