### ISSUE TITLE
Document address family of listening INET sockets, given config

### ISSUE THREAD

**Issue by sanmai-NL** [kubernetes/kubernetes#115385]
The docs are ambiguous on whether a socket will be limited to either the IPv4 or IPv6 address familiy. 
E.g., https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
 contains 

> `--bind-address` string     Default: 0.0.0.0
> --
>  The IP address on which to listen for the --secure-port port. The associated interface(s) must be reachable by the rest of the cluster, and by CLI/web clients. If blank **or an unspecified address (0.0.0.0 or ::), all interfaces will be used**.

This wording in bold suggests that when `bind-address` is 0.0.0.0, the API server will listen on IPv6 addresses too, potentially. That would be incorrect and prevent limiting the address family from the config (to enforce single-stack). According to a report to me, indeed this incorrect behavior is the case. In any case, the wording is ambiguous.

Moreover, the source code base contains quite a few `0.0.0.0` literals that aren't accompanied by `::`, suggesting that IPv4 is assumed in some paths. Unless ... Kubernetes has this special algorithm that equates either {0.0.0.0} or {::} with {0.0.0.0, ::}.

**Comment by sanmai-NL** [comment]
See: https://sourcegraph.com/github.com/kubernetes/kubernetes@8e642d3d0deab20a153c740b7af727a10aabf88b/-/blob/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go?L468-482

**Comment by aojea** [comment]
> See: https://sourcegraph.com/github.com/kubernetes/kubernetes@8e642d3d0deab20a153c740b7af727a10aabf88b/-/blob/staging/src/k8s.io/apimachinery/pkg/util/net/interface.go?L468-482

that code is used to discover the advertised address if that is not provided, the family of the IP is used for the discovery.

The bind address is passed as is to the listener https://sourcegraph.com/github.com/kubernetes/kubernetes@8e642d3d0deab20a153c740b7af727a10aabf88b/-/blob/staging/src/k8s.io/apiserver/pkg/server/options/serving.go. and in golang, 0.0.0.0 and :: behaves the same, it opens a socket in all the addresses in the host https://github.com/golang/go/issues/9334

The doc is correct

**Comment by sanmai-NL** [comment]
The docs are ambiguous since the behavior rather than being logical,  relies on a Go-based implementation detail.

**Comment by aojea** [comment]
I can't understand why do you consider it ambiguous if that defines exactly what is going to happen.

> relies on a Go-based implementation detail.

yeah, sometimes this happens unfortunately, https://github.com/kubernetes/kubernetes/issues/88458 but we can't do much about it without breaking compatibility, can we?

**Comment by sanmai-NL** [comment]
All interfaces could mean all interfaces for the specified address family, or all interfaces across address families. The latter is bizarre (non-standard and unproductive), but the actual behavior. What Go does and that Kubernetes exposes this behavior to the user without modification should be documented.

**Comment by aojea** [comment]
How do you word it then?

**Comment by sanmai-NL** [comment]
> How do you word it then? 

Can you explain where the difficulty is in reading and interpreting my comments? For me, it can't be any clearer.

`s/all interfaces/all interfaces across address families IPv4 and IPv6/g`

**Comment by aojea** [comment]
> Can you explain where the difficulty is in reading and interpreting my comments? For me, it can't be any clearer.

lol, sorry, now I got it, I was confused because I remembered to change some of them to clarify exactly this 
https://github.com/kubernetes/kubernetes/pull/97245 and I was not realizing this flag was not correct.

It is my fault https://github.com/kubernetes/kubernetes/pull/8683, I honestly don't know why omitted the IP families but you are right, my apologies again @sanmai-NL , it was some kind of frequency illusion or bias.

This is a good first issue for someone that wants to do a contribution to the project, just update this line https://github.com/aojea/kubernetes/blob/05010d23ac7751a17aa26fb5cc011eb4f2127b1e/staging/src/k8s.io/apiserver/pkg/server/options/serving.go#L146

I think `for listening in all interfaces and IP families` is easy to understand is coherent with the other flags

/help
/triage accepted

**Comment by sanmai-NL** [comment]
@aojea 
> for listening in all interfaces and IP families

I suggest then:

> for listening on all interfaces and IP address families

**Comment by jadhaj** [comment]
@aojea Hi,

I see that there are another instances where "for listening in all interfaces and IP families" appear, like in:

https://github.com/kubernetes/kubernetes/blob/09899b986f450e2b6a21aa18e9012da5424eedec/cmd/kubelet/app/options/options.go#L368

I am thinking to include them along with the change on "serving.go" file when submitting a PR

WDYT?
