### ISSUE TITLE
Not possible to tolerate domain loss in TopologySpreadConstraints and keep capacity after addition of minDomains

### ISSUE THREAD

**Issue by guidola** [kubernetes/kubernetes#115320]
### What would you like to be added?

When working with `TopologySpreadConstraints` it used to not be possible to control how pods got placed in the scenario where a node pool had to be scaled up from 0 nodes and, whilst it has not yet scaled to the point where the maximum number of domains that the agent pool can provide is reached, the scheduler will not be aware of them and hence make scheduling decisions contrary to what the developer might expect.

https://github.com/kubernetes/enhancements/pull/3030 solved this by adding `minDomains`. Nonetheless, if one is to use this new setting, while it will be possible to ensure that all require domains are present before making scheduling decisions that might result in domain inbalance, it will degrade the workload's ability to operate in failure conditions. 

To make a clear example, in a scenario where we are working with the `topology.kubernetes.io/zone` or `failure-domain.beta.kubernetes.io/zone` domains. There can be a clear requirement to:

1. Ensure that we have N zone redundancy for the workload
2. Allow the workload to keep up with the required capacity ( be able to scale up, restore lost capacity due to failure ... ) 

In a failure scenario where we are expecting 2 zones to be available but there is a zone failure where we lose the nodes in one of the zones this is how things would play out in my head.

To accomodate (1) we would use `minDomains` as the setting is intended to solve that precise problem. Nonetheless, the moment we do that, we would limit (2) as, per the behaviour of that field, we would only be able to have as many pods as `maxSkew` dictates. 

For example, if we have a deployment which requires a `minReplicas` of 2 and we have `maxSkew` set to `1` and `minDomains` set to 2 so that we can ensure that on the minimum configuration without any scaling there will be zone redundancy, if one of the zones is lost, the second pod will not be able to schedule as the maxSkew would be violated when compared to 0 ( minDomains(2) > 1(current domains after failure), even further if to keep up with the load the deployment needs to scale to further replicas, it would be unable to do so due to that same limitation.

## Some thoughts on it

When thinking about this situation there is no clear way to me to keep up with both requirements plainly thinking in terms of scheduling conditions as allowing one use case seems to block the other completely so there seems at this point to be a trade off between (1) and (2). Where prior to the introduction of the `minDomain` changes (2) was possible but not (1) and now (1) is but (2) is not.

There could be an approach where this would be possible if `TopologySpreadConstraints` could be allowed to evict pods so they get re-scheduled on certain circumstances so to enforce the configured spread but this seems to get complicated when one wants to ensure the same time that the CA will be triggered ( and that the CA will be able to provide the required domain...)

But how can we at the same time ensure that `minDomains` is respected when the scheduler does not have full visibility of the potential existing domains in the cluster nor of any related failures?

### Why is this needed?

In the scenario where a domain is lost due to a failure we want to keep the workload operating at its required capacity. Current implemenation of `minDomains` for `PodTopologySpread` would block that from being possible since it would limit the capacity at the set `skew` rather than the `replicas` set by ie. the `deployment`.

**Comment by sanposhiho** [comment]
Thanks @guidola for bringing this up.

I'm thinking https://github.com/kubernetes/kubernetes/issues/105977 could be one solution; fallback to schedule anyway mode if CA can't create a new Node.

**Comment by guidola** [comment]
Hi @sanposhiho , that indeed looks like it would solve the scheduling problem, were we would be able to keep on scheduling the otherwise unschedulable pods when the `minDomains` constraint is not fulfilled. Nonetheless, I don't see what mechanism would restore the zone redundancy after the failure is resolved.


# Preemption of pods scheduled outside of preference

I can see scenarios where the failure can be rather short like for example `SKU/VmType` capacity issues in the cloud provider. In clusters with a considerable amount of workloads affected by this, restoring the zone redundancy manually after all workloads have moved to a single zone could be a comprehensive endeavour. 

It would be interesting if the eviction/preemption mechanisms would be aware of pods scheduled in breach of their constraints and would try to re-schedule them as to satisfy them. This is definetly `non-trivial` as  it would likely have quite some side effects on scheduling that would need considering as well as adding the ability for the developer to define  wether they want to have this additional preemption on their workloads or not as I would clearly see users having legacy applications with high costs when it comes to termination and re-scheduling would prefer to have greater control over how such restoration to prefered scheduling is performed.

I see around the affinity/spread mechanisms two usual approaches. `ScheduleAnyway` and `DoNotSchedule`. If we were to add a third possible decision as per #105977, it might be interesting to add this around the different scheduling features ( spread, affinity, .. ) and for that new possible Scheduling decision do something as follows.

## How this could look like

* Add an additional Condition to the pod -> Using the already existing `DeploymentConditions` one could add an adittional condition `DeploymentBalanced` that indicates wether the deployment is currently scheduled as per its preferred state.
* If the scheduling action for some scheduling rule is of `DoNotSchedule_BestEffort` then the `PreemptionMechanism` should evaluate (when?) wether this unbalance/divergence can be corrected and perform the necessary eviction.
* Deployments could have a way to indicate wether this want this "correcting" preemption. Potentially thorugh an additional `PreemptionPolicy`  like `PreemptUnbalanced` ( this might not really align with the current meaning of the `PreemptionPolicy` in priority classes so there might be better ways to get this done )

Thoughts? Might be good to move this discussion elsewhere or include into #105977 ?

**Comment by sanposhiho** [comment]
Yes, let's move this discussion to #105977 so that you can draw other people's attentions.

> I don't see what mechanism would restore the zone redundancy after the failure is resolved.

The [descheduler](https://github.com/kubernetes-sigs/descheduler) would be the first option to resolve the re-scheduling issue. Not sure if we really need to implement something for the re-scheduling in the scheduler.
