### ISSUE TITLE
kubelet issues when LocalStorageCapacityIsolationFSQuotaMonitoring is enabled

### ISSUE THREAD

**Issue by alex-matei** [kubernetes/kubernetes#115309]
### What happened?

1. When the flag is enabled quota setup fails on subsequent invocations

Each time quota is applied on a volume, a new random UUID for the pod is generated and this UUID is compared with the previous stored one internally. If it doesn't match then the whole process stops and an error is returned.

2. ConfigMaps and secrets volume update fail and it floods the cluster with error events

ConfigMaps and secrets use emptyDir volumes which try to reapply quotas on every invocation. Since quota setup fails on subsequent invocations an error is logged each time and the process of updating the payloads is stopped. This happens frequently and it floods the cluster with error messages.

```
kube-system   68s         Warning   FailedMount               pod/kube-proxy-nmmnq                                                (combined from similar events): MountVolume.SetUp failed for volume "kube-proxy" : requesting quota on existing directory /mnt/kubelet/pods/e9f869de-fdf4-4728-a969-34abdaf00683/volumes/kubernetes.io~configmap/kube-proxy but different pod f61ddb8b-82cf-480c-910c-9adbcc643bb2 4e06badc-1093-4076-a127-267aa27ebd46
```

3. After kubelet restarts trying to apply quota fails because the folder already has a quota project id associated with it.

```
monitoring    11m         Warning   FailedMount               pod/prometheus-monitoring-kube-prometheus-prometheus-0              MountVolume.SetUp failed for volume "config-out" : assign quota FAILED createProjectID /mnt/kubelet/pods/ea2780a5-66bb-435c-9395-bf3609839123/volumes/kubernetes.io~empty-dir/config-out 0 failed attempt to reassign project ID for /mnt/kubelet/pods/ea2780a5-66bb-435c-9395-bf3609839123/volumes/kubernetes.io~empty-dir/config-out
```

Similar issues: #114506, #112081

**Comment by SergeyKanzhelev** [comment]
/cc @rphillips 

/triage accepted

accepting triage as we are trying to understand whether to proceed with this feature at all.

**Comment by pacoxu** [comment]
If I understand correctly, this should be fixed by https://github.com/kubernetes/kubernetes/pull/112624/ and I have opened cherry-picks for v1.24-v.126. The bug is introduced by https://github.com/kubernetes/kubernetes/pull/107302. This should not be a problem in v1.23 and before. 

@alex-matei  what is the kubelet version that you are using?

**Comment by pacoxu** [comment]
let me do another round of test and add some test ci to cover this asap.

**Comment by alex-matei** [comment]
I think we can close this one, we merged the PRs.

**Comment by pacoxu** [comment]
/close

@rphillips Since the block issue for the feature is fixed, do you think we are ready to promote the feature to beta again? 

Would you like to review https://github.com/kubernetes/enhancements/pull/3821?
