### ISSUE TITLE
Deleting pods that mount volumes from missing config-maps/secrets causes an abnormal deletion time.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#115459]
### What happened?

If you create a pod that mounts a volume from a secret or a config-map and then you delete that pod, it takes an abnormally long time to delete the pod.  

### What did you expect to happen?

I would expect a similar time for deletion from a successful case as an unsuccesful case.

### How can we reproduce it (as minimally and precisely as possible)?

If you have the following yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: config-map-mount
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "sleep", "100" ]
      volumeMounts:
      - mountPath: /clusters-config
        name: clusters-config-volume
  volumes:
    - configMap:
        name: clusters-config-file
      name: clusters-config-volume
```
And you create it with no config-map and delete the pod it takes around 60-75 seconds to delete the pod.  

If you create that config-map/secret it only takes a few seconds to delete the pod.  

Secret example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-example-pod
spec:
  containers:
    - name: secret-test-container
      image: busybox
      command: [ "/bin/sh", "-c", "cat /etc/secret-volume/*" ]
      volumeMounts: 
          - name: secret-volume
            mountPath: /etc/secret-volume 
            readOnly: true 
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret 
  restartPolicy: Never
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.7-eks-4721010", GitCommit:"b77d9473a02fbfa834afa67d677fd12d690b195f", GitTreeState:"clean", BuildDate:"2022-06-27T22:22:16Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

Can reproduce in Kind.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by r0b2g1t** [comment]
I have not observed this behaviour yet, but I will try to reproduce it.

**Comment by r0b2g1t** [comment]
I can confirm the behaviour. Use Kubernetes version 1.25.5.

**Comment by kannon92** [comment]
I am also able to confirm with latest main from a local build.

**Comment by kannon92** [comment]
Thank you for confirming @r0b2g1t!

Since I am running locally I can see logs from Kubelet that look very interesting:

```
**I0201 23:24:12.119802 2649876 kubelet_pods.go:951] "Pod is terminated, but some containers are still running" pod="default/config-map-mount"**
```
For some reason, this code seems to detect that the container is running but its last status is ContainerCreating before I terminate.  

Log comes from here:

```
func (kl *Kubelet) PodResourcesAreReclaimed(pod *v1.Pod, status v1.PodStatus) bool {
	if kl.podWorkers.CouldHaveRunningContainers(pod.UID) {
		// We shouldn't delete pods that still have running containers
		klog.V(3).InfoS("Pod is terminated, but some containers are still running", "pod", klog.KObj(pod))
		return false
	}
```

**Comment by SergeyKanzhelev** [comment]
/triage accepted

@howardjohn, @kannon92 do you know if this is a regression? This may educate the priority better

/priority important-soon
/cc @smarterclayton

**Comment by howardjohn** [comment]
I did not test older versions so I am not sure

**Comment by kannon92** [comment]
I tested 1.24 and latest build.

**Comment by tzneal** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/100219

**Comment by smarterclayton** [comment]
This also sounds like context cancellation of sync - there are lots of reasons a delete takes a while to get processed.  Hooks also can block this.  I’ll create a tracking issue for context cancellation since there are lots of places that have to properly handle the cancellation.

**Comment by tzneal** [comment]
> This also sounds like context cancellation of sync - there are lots of reasons a delete takes a while to get processed. Hooks also can block this. I’ll create a tracking issue for context cancellation since there are lots of places that have to properly handle the cancellation.

It was, I resolved this particular one with https://github.com/kubernetes/kubernetes/pull/115644

**Comment by smarterclayton** [comment]
#113606 is the general umbrella for cancellation
