### ISSUE TITLE
Flaky ClusterCIDR integration test

### ISSUE THREAD

**Issue by danielvegamyhre** [kubernetes/kubernetes#115440]
### Which jobs are flaking?

k8s.io/kubernetes/test/integration/clustercidr

### Which tests are flaking?

TestIPAMMultiCIDRRangeAllocatorClusterCIDRTieBreak

### Since when has it been flaking?

Noticed today 01/31/2023

### Anything else we need to know?

Link: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115349/pull-kubernetes-integration/1620501292214390784

**Comment by aojea** [comment]
Thanks

it was already reverted https://github.com/kubernetes/kubernetes/pull/115428

/close
