### ISSUE TITLE
The graduation HPA container resource metrics to beta

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#115467]
### What would you like to be added?

ref: https://github.com/kubernetes/enhancements/issues/1610

This is what we actually need to do for the graduation to beta:

- [ ] ⚠️ [bug] change HPA controller to ignore `ContainerResource` when it's disabled by the feature gate. 
  - https://github.com/kubernetes/kubernetes/pull/116043
- [ ] 🚀 [enhancement] make a difference in `SuccessfulRescale ` events between the resource metric and the container resource metric.
  - Currently, we cannot distinguish the scaling up event between `type: Resource` and `type: ContainerResource`. Both of them create the event like `memory resource utilization (percentage of request) above target` and we cannot know which is the direct reason.
  - https://github.com/kubernetes/kubernetes/pull/116045
- [ ] 🚀 [enhancement] graduate the feature gate to beta. enabled by default.
  - https://github.com/kubernetes/kubernetes/pull/116046
- [ ] 📔 [test] the tests to confirm the behavior on switching the feature gate
  - https://github.com/kubernetes/kubernetes/pull/116043
- [ ] 👁️ [metrics] tracked in separated issue: https://github.com/kubernetes/kubernetes/issues/115639
  - https://github.com/kubernetes/kubernetes/pull/116010
  - https://github.com/kubernetes/kubernetes/pull/116326

### Why is this needed?

To satisfy the beta graduation criteria.

/assign
/sig autoscaling

**Comment by ParSal123** [comment]
Can I help with that? I'm new, but it looks like the bug (first task) is a good start.

**Comment by sanposhiho** [comment]
Yes. Feel free to take the first one. 
But, note that that change should be done by [01:00 UTC Wednesday 15th March 2023 / 17:00 PDT Tuesday 14th March 2023](https://everytimezone.com/s/c4971746) at latest because `ContainerResource` is planned to get graduated to beta in this release (for now).

**Comment by sanposhiho** [comment]
If it's ok for your bandwidth, please comment /assign then the bot will assign this issue to you.

**Comment by ParSal123** [comment]
Thanks!
Could you help me with where to start?

**Comment by sanposhiho** [comment]
The container resource metrics related logic is around here.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go#L425

**Comment by xiaomudk** [comment]
Is there anyone doing the second task now?

**Comment by sanposhiho** [comment]
@xiaomudk I'm already working on the remaining ones.

**Comment by sanposhiho** [comment]
@ParSal123 Hi, just a reminder, do you still want to work on the first one? or do you want me to take over it? 
It's softly blocking the last `[test] the tests to confirm the behavior on switching the feature gate` implementation.

(I don't want to rush people but we have a clear deadline on this task 🙏 )

**Comment by ParSal123** [comment]
> @ParSal123 Hi, just a reminder, do you still want to work on the first one? or do you want me to take over it? It's softly blocking the last `[test] the tests to confirm the behavior on switching the feature gate` implementation.
> 
> (I don't want to rush people but we have a clear deadline on this task pray )

Hey, I think it would be better if you took over. It's best not to have any surprises here.

**Comment by sanposhiho** [comment]
@ParSal123 Sure, thanks for confirmation. We're looking forward to seeing your contribution in another chance! :)

**Comment by sanposhiho** [comment]
All things are done now.
