### ISSUE TITLE
[Failing Test] gce-cos-master-scalability-100 failing since 1/31 07:41 PT

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#115427]
### Which jobs are failing?

sig-release-master-blocking
gce-cos-master-scalability-100
gce-cos-master-default

### Which tests are failing?

Overall

### Since when has it been failing?

since 1/31 07:41 PT

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100&show-stale-tests=

### Reason for failure (if possible)

Job execution failed: Pod got deleted unexpectedly.

See these jobs in plow:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1620446628521447424
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1620457448886243328
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1620438322549624832
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce/1620456191249354752

### Anything else we need to know?

Test grid cites these code changes:
https://github.com/kubernetes/kubernetes/compare/c2299bc65...eaa5104de?

### Relevant SIG(s)

/sig

**Comment by drewhagen** [comment]
cc @kubernetes/ci-signal

**Comment by drewhagen** [comment]
X-post discussion from slack thread here:
https://kubernetes.slack.com/archives/C09QZ4DQB/p1675186151358239

There may have been ongoing maintenance that has caused pods to be deleted. I'll keep this issue open to monitor a bit longer. I'm curious to see how this currently running build ends up, as it hasn't been passing due to this issue:
https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-cos-master-serial

**Comment by aojea** [comment]
it seems it recovered 
![image](https://user-images.githubusercontent.com/6450081/215980106-1173cb9d-7bf7-4431-a24f-f43db346b0b7.png)

most probably a hiccup on the infra, not related to kubernetes code for sure

Thanks for the signal

/close
