### ISSUE TITLE
Support SetHeader functionality in rest.Interface

### ISSUE THREAD

**Issue by ardaguclu** [kubernetes/kubernetes#115421]
### What would you like to be added?

rest.Interface supports `SetHeader` functionality. Thereby, consumers can use use server side printing for the resources derived from `rest.Interface`.

### Why is this needed?

Currently in order to use server side printing, Accept header should be [set accordingly](https://github.com/kubernetes/kubernetes/blob/2f184814b89a4bfa482b8572e98e969681e2f64c/staging/src/k8s.io/kubectl/pkg/cmd/get/get.go#L427). Builder supports SetHeader functionality, however clients derived from rest.Interface have no option setting headers. In order to use server side printing, it is required to add SetHeader into rest.Interface like some kind of a way to pass user defined headers into [here](https://github.com/kubernetes/kubernetes/blob/08d5565b9b3892032ae98fe1592413e1703c2e3e/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/endpoints.go#L73)?

Discussion: https://kubernetes.slack.com/archives/C0EG7JC6T/p1674210659146119

**Comment by liggitt** [comment]
Header is set on the requests obtained from the rest interface:

`r.Get().SetHeader(..., ...).`

**Comment by ardaguclu** [comment]
But this is not exported to consumers?

**Comment by liggitt** [comment]
I'm not sure what you mean... the rest.Interface provides methods to construct `*rest.Request` objects, and the Request object allows setting headers

**Comment by liggitt** [comment]
if you want to set the accepted type for the entire rest client, that is done at construction time in the passed-in ClientConfigConfig

**Comment by ardaguclu** [comment]
> if you want to set the accepted content type for the entire rest client, that is done at construction time when calling NewRESTClient in the passed-in ClientConfigConfig

Thanks, I definitely mean that. I didn't know that is possible via ClientConfigConfig, do you have any example handy for this.

**Comment by ardaguclu** [comment]
For example, I want to use server side printing for `EndpointsInterface` https://github.com/kubernetes/kubernetes/blob/08d5565b9b3892032ae98fe1592413e1703c2e3e/staging/src/k8s.io/client-go/kubernetes/typed/core/v1/endpoints.go#L39. If I understand correctly, I can do it by setting via construction step

**Comment by liggitt** [comment]
> For example, I want to use server side printing for `EndpointsInterface`

that's not really possible... the return type of that client is `Endpoints`, not metav1.Table as is returned by server-side printing

If you're trying to make server-side printing requests, you need a way to get back a metav1.Table object. Something sort of like this:

```go
endpointsClientConfig := &rest.Config{
  ...
  ContentConfig: rest.ContentConfig{AcceptContentTypes: "application/json;as=Table;v=v1;g=meta.k8s.io"},
  GroupVersion: schema.GroupVersion{Group: "", Version: "v1"},
}
endpointsClient, err := rest.RESTClientFor(endpointsClientConfig)
...
table := &metav1.Table{}
err = endpointsClient.Get().Namespace("mynamespace").Resource("endpoints").Do(context.TODO()).Into(table)
...
```

**Comment by ardaguclu** [comment]
hmm,now it all makes sense. If user wants to use server side printing, he/she has to use builder. Because as you said, we need an `metav1.Table` object. 

Thanks a lot @liggitt for the explanation and spending time on it.

This looks like not an issue, it is designed as is.
/close
