### ISSUE TITLE
["Flaky" Tests/Test Grid Bug] Various sig-release-master-blocking jobs with "Unknown: Build is too old to process"

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#115410]
### Which jobs are flaking?

sig-release-master-blocking
integration-master
gce-cos-master-alpha-features
gce-cos-master-reboot
gce-cos-master-scalability-100

### Which tests are flaking?

None. The "Overall" build results in a (?) result, and says "Unknown: Build is too old to process".

### Since when has it been flaking?

Seemingly since the start of the release. 

### Testgrid link
https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-alpha-features
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-reboot&show-stale-tests=
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100&show-stale-tests=

### Reason for failure (if possible)

A few of these builds may be unique, but the most common theme I see across these builds are lines like these:
```
scp: /var/log/cluster-autoscaler.log*: No such file or directory
scp: /var/log/fluentd.log*: No such file or directory
scp: /var/log/kubelet.cov*: No such file or directory
scp: /var/log/cl2-**: No such file or directory
scp: /var/log/startupscript.log*: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1].
```

### Anything else we need to know?

I'm not sure if this is normal? But the stats on the summary of the test-grid treats these as a flake. So I thought I'd open an issue to discuss whether it's normal or something needs investigating.

Here are some examples of these builds:
[integration-master #1](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1620019838833397760)
[integration-master #2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1619971520048664576)
[integration-master #3](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1619785039204061184)
[gce-cos-master-alpha-features #1](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1620073945975754752)
[gce-cos-master-alpha-features #2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-features/1619943082273280000)
[gce-cos-master-reboot #1](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1620012289031671808)
[gce-cos-master-reboot #2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1619959943492800512)
[gce-cos-master-reboot #3](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-reboot/1619855756129996800)
[gce-cos-master-scalability-100 #1](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1619879667047600128)
[gce-cos-master-scalability-100 #2](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1619813477440819200)
[gce-cos-master-scalability-100 #3](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1619706520834936832)

### Relevant SIG(s)
/sig testing

**Comment by lauralorenz** [comment]
X-posting that there is more context being discussed in this [slack thread](https://kubernetes.slack.com/archives/C09QZ4DQB/p1675117747178039)

**Comment by drewhagen** [comment]
Per the slack thread that Laura posted, we think there is a bug with test grid.
Created issue here:
https://github.com/GoogleCloudPlatform/testgrid/issues/1116

**Comment by drewhagen** [comment]
Still continuing to be an issue
![image](https://user-images.githubusercontent.com/2896571/217336584-2a314eea-d7de-4299-aa54-dadc3492e391.png)

Test grid ticket not picked up yet.

**Comment by BenTheElder** [comment]
was this fixed? https://github.com/GoogleCloudPlatform/testgrid/issues/1116#issuecomment-1462624244 👀 
/triage accepted

**Comment by drewhagen** [comment]
I checked the jobs linked above that regularly ran into this issue.

Since the testgrid ticket has been closed, I am no longer seeing this issue. 👍

**Comment by BenTheElder** [comment]
Great! Thanks all
