### ISSUE TITLE
APF fails when conc. limit is not bigger than hand size X max width

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#115409]
### What happened?

When there is a client that requests long lists and does not read them (before the 1-minute request-handling timeout), and in the relevant priority level the hand size times the max width (which is currently fixed in the code to be 10) exceeds or is not much smaller than the concurrency limit, this client will nearly starve other clients.  This could happen with other sorts of requests, the important thing is that the client does not finish reading the response for a longish time.

### What did you expect to happen?

API Priority and Fairness is supposed to protect clients from each other.
Exactly what should happen in this situation is debatable.

### How can we reproduce it (as minimally and precisely as possible)?

The outline above is pretty succinct.  The flaw should also be clearly evident in the design document (https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/1040-priority-and-fairness).

### Kubernetes version

This flaw has been present from the start.

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs 
/cc @marseel

**Comment by MikeSpreitzer** [comment]
I can think of two approaches to dealing with this problem.

One approach is to make APF identify the problematic client and put it in a jail constructed using APF's ability to create new priority levels and flow schemas.  This begs the question of how to automatically identify just a client.

Another approach is to enforce a constraint on configuration that avoids this situation.  This has two sub-problems: define exactly what the constraint is, and define how it is enforced.

An obvious candidate for the constraint is: ((hand size) + 1) X (max width) <= nominal concurrency limit.  This still begs the question of what to do when the nominal concurrency limit is less than 2 X (hand size).

As for enforcing, remember the following complications.  Part of the configuration comes from the api-server command line, which can vary from server to server and from time to time.  Part of the configuration is mandatory, some is suggested, and some is entirely from users.  Remember also that each priority level's nominal concurrency limit depends on all of their shares --- so each priority level's configuration depends on the shares of all the (non-exempt) others.  So the enforcement to be done is dynamic.  Some filtering could be applied in admission control for user-authored config, but that can not be the end of the story.  The server-supplied config could be automatically adjusted.

Think of it in layers.  The request-handling can be controlled by configuration that has been subjected to dynamic constraints.  This leaves the question of how to let users know whether, where, and how the automatically constrained configuration differs from what the users input and the server documentation says.

Certainly there can be metrics that expose the input configuration and constrained configuration.  External monitors can alert on differences.  But it would be better if the API objects also exposed divergences.

To expose the constrained configuration in API objects would involve adding something in the PriorityLevelConfigurationStatus datatype.  It can not be a scalar Condition because the divergence from the input can vary in magnitude and from server to server.  To express it would require a list of (server ID, constrained configuration) pairs.  This, in turn, begs the question of how to identify servers.  There is a standard form of server ID that is at the beta level of maturity, so that would be the obvious choice when it is not disabled.  When it is disabled, perhaps a randomly generated UUID?

**Comment by lavalamp** [comment]
I think at the moment, to handle this, we instruct admins to direct lists of large collections to their own PLs. And then it is a feature that such requests are done in serial (large lists are very hard on memory and we really can't be doing many at once).

**Comment by andrewsykim** [comment]
> @andrewsykim - do you have a plan for graduating apiserver identity to GA in 1.28? If so, that would solve the second problem.

Not sure yet, I need to re-evaluate the GA graduation criteras, but no reason this isn't possible today since the feature is Beta and enabled by default in 1.26

**Comment by wojtek-t** [comment]
> An obvious candidate for the constraint is: ((hand size) + 1) X (max width) <= nominal concurrency limit. This still begs the question of what to do when the nominal concurrency limit is less than 2 X (hand size).

This is effectively what we did in #118601 [well, almost, becasue maxwidth will always be at least 1, which means that if nominal concurrency limit is smaller than handsize, then we still have this problem. But this part, I'm not sure is important enough to introduce further complications.

So I would suggest that we backport this change to previous releases and once done close this bug.

**Comment by wojtek-t** [comment]
> So I would suggest that we backport this change to previous releases and once done close this bug.

@MikeSpreitzer - based on ^^, can we close it now?

**Comment by cici37** [comment]
/close
We are reviewing it in SIG api-machinery bug triage meeting. Please feel free to reopen the issue if needed. Thanks
