### ISSUE TITLE
podmaster is not keeping controller/scheduler manifests up to date

### ISSUE THREAD

**Issue by onorua** [kubernetes/kubernetes#11549]
according to https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/admin/high-availability
it's recommended to have podmaster instance which is copying manifest files from /srv/kubernetes to /etc/kubernetes/manifests in case elected to be "active" instance. 
It's working for static configurations only, but it doesn't track changes neither of origin nor destination files, which is not obvious and even confusing, "why my changes to scheduler/controller-manager pushed but have no effect". 
I would like to have basic md5/sha checksum of the file and replace destination file if it had been changed.

**Comment by mbforbes** [comment]
+cc @brendandburns

**Comment by roberthbailey** [comment]
@brendandburns Can you take a look at this issue and see if it is still relevant? The HA docs appear to have changed quite a bit since mid-July.

**Comment by mikedanese** [comment]
Pod master is deprecated to be removed. Please use the controller-manager and scheduler --leader-elect flags
