### ISSUE TITLE
client-go: set the default of the 'host' label to an empty string for client metrics

### ISSUE THREAD

**Issue by tkashem** [kubernetes/kubernetes#115461]
### What happened?

the default value of the `host`  label is `none` for all client metrics, see

https://github.com/kubernetes/kubernetes/blob/1f02f43ec6910cbcd46222b16a2f3965458e5e45/staging/src/k8s.io/client-go/rest/request.go#L792-L795

in a query, we want the user to use `{host!=""}` rather than `{host!="none"}`.
in reality, the `RESTClient.base` may never be empty, so the label is never set to `none` in a real cluster?

**Comment by aojea** [comment]
how can you get a metrics with host=none? that request will never work

**Comment by dgrisonnet** [comment]
I guess the intent is more to have the empty string as a sane default rather "none" as it is more intuitive to the users when querying.

> how can you get a metrics with host=none? that request will never work

I don't know how one could end up in that scenario, maybe we would want to log an error when that occurs? Would we even reach that point in code when the request is incomplete?

**Comment by dgrisonnet** [comment]
I don't think so, it was just an oddity I noticed when reviewing https://github.com/kubernetes/kubernetes/pull/108396#discussion_r995590210. Since we don't think we will ever encounter this scenario it might not be worth cleaning up.

**Comment by tkashem** [comment]
> Is this a real problem?

i don't think so, in fact I mention this in the description - `the RESTClient.base may never be empty, so the label is never set to none in a real cluster?`
I am closing it, as we agree that this will never be an issue in real clusters

/close
