### ISSUE TITLE
I disagree.  Being able to observe the key ID hash easily from the API server is incredibly valuable for the operator (to understand rotation and the state of data in etcd).  The plugin is completely under the control of the operator, there is no real risk of OOM here.

### ISSUE THREAD

**Issue by bitcoin274** [kubernetes/kubernetes#115475]
I disagree.  Being able to observe the key ID hash easily from the API server is incredibly valuable for the operator (to understand rotation and the state of data in etcd).  The plugin is completely under the control of the operator, there is no real risk of OOM here.

_Originally posted by @enj in https://github.com/kubernetes/kubernetes/pull/115394#discussion_r1093865297_

**Comment by enj** [comment]
/close

Unclear if this was created by mistake.
