### ISSUE TITLE
[Failing test] build-master-fast

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#115477]
### Which jobs are failing?

master-blocking

- build-master-fast

### Which tests are failing?

- ci-kubernetes-build-fast.Overall

![Screenshot from 2023-02-02 21-49-21](https://user-images.githubusercontent.com/73488906/216381376-362f0cfb-afb0-4818-8d15-596e43a874b3.png)

### Since when has it been failing?

2023-02-02 07:08 PST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#build-master-fast

### Reason for failure (if possible)

`make: *** [Makefile:424: quick-release] Error 1
level=fatal msg="failed to run: running make quick-release: command /usr/bin/make quick-release did not succeed: +++ Docker build command failed for kube-build:build-60807193a1-5-v1.26.0-go1.19.5-bullseye.0\n\nunknown flag: --load\nSee 'docker --help'.\n\nUsage:  docker [OPTIONS] COMMAND\n\nA self-sufficient runtime for containers\n\nCommon Commands:\n  run         Create and run a new container from an image\n  exec        Execute a command in a running container\n  ps          List containers\n  build       Build an image from a Dockerfile\n  pull        Download an image from a registry\n  push        Upload an image to a registry\n  images      List images\n  login       Log in to a registry\n  logout      Log out from a registry\n  search      Search Docker Hub for images\n  version     Show the Docker version information\n  info        Display system-wide information\n\nManagement Commands:\n  builder     Manage builds\n  container   Manage containers\n  context     Manage contexts\n  image       Manage images\n  manifest    Manage Docker image manifests and manifest lists\n  network     Manage networks\n  plugin      Manage plugins\n  system      Manage Docker\n  trust       Manage trust on Docker images\n  volume      Manage volumes\n\nSwarm Commands:\n  swarm       Manage Swarm\n\nCommands:\n  attach      Attach local standard input, output, and error streams to a running container\n  commit      Create a new image from a container's changes\n  cp          Copy files/folders between a container and the local filesystem\n  create      Create a new container\n  diff        Inspect changes to files or directories on a container's filesystem\n  events      Get real time events from the server\n  export      Export a container's filesystem as a tar archive\n  history     Show the history of an image\n  import      Import the contents from a tarball to create a filesystem image\n  inspect     Return low-level information on Docker objects\n  kill        Kill one or more running containers\n  load        Load an image from a tar archive or STDIN\n  logs        Fetch the logs of a container\n  pause       Pause all processes within one or more containers\n  port        List port mappings or a specific mapping for the container\n  rename      Rename a container\n  restart     Restart one or more containers\n  rm          Remove one or more containers\n  rmi         Remove one or more images\n  save        Save one or more images to a tar archive (streamed to STDOUT by default)\n  start       Start one or more stopped containers\n  stats       Display a live stream of container(s) resource usage statistics\n  stop        Stop one or more running containers\n  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE\n  top         Display the running processes of a container\n  unpause     Unpause all processes within one or more containers\n  update      Update configuration of one or more containers\n  wait        Block until one or more containers stop, then print their exit codes\n\nGlobal Options:\n      --config string      Location of client config files (default\n                           \"/root/.docker\")\n  -c, --context string     Name of the context to use to connect to the\n                           daemon (overrides DOCKER_HOST env var and\n                           default context set with \"docker context use\")\n  -D, --debug              Enable debug mode\n  -H, --host list          Daemon socket(s) to connect to\n  -l, --log-level string   Set the logging level (\"debug\", \"info\",\n                           \"warn\", \"error\", \"fatal\") (default \"info\")\n      --tls                Use TLS; implied by --tlsverify\n      --tlscacert string   Trust certs signed only by this CA (default\n                           \"/root/.docker/ca.pem\")\n      --tlscert string     Path to TLS certificate file (default\n                           \"/root/.docker/cert.pem\")\n      --tlskey string      Path to TLS key file (default\n                           \"/root/.docker/key.pem\")\n      --tlsverify          Use TLS and verify the remote\n  -v, --version            Print version information and quit\n\nRun 'docker COMMAND --help' for more information on a command.\n\nFor more help on how to use Docker, head to https://docs.docker.com/go/guides/\n\nTo retry manually, run:\n\nDOCKER_CLI_EXPERIMENTAL=enabled docker buildx build --load -t kube-build:build-60807193a1-5-v1.26.0-go1.19.5-bullseye.0 --pull=false --build-arg=KUBE_CROSS_IMAGE=registry.k8s.io/build-image/kube-cross --build-arg=KUBE_CROSS_VERSION=v1.26.0-go1.19.5-bullseye.0 /home/prow/go/src/github.com/kubernetes/kubernetes/_output/images/kube-build:build-60807193a1-5-v1.26.0-go1.19.5-bullseye.0\n\n!!! [0202 15:58:04] Call tree:\n!!! [0202 15:58:04]  1: build/release.sh:35 kube::build::build_image(...)\nmake: *** [Makefile:424: quick-release] Error 1\n"`

### Relevant SIG(s)

/sig release
cc @kubernetes/ci-signal

**Comment by dims** [comment]
buildx went AWOL in new builds of k8s-ci-builder images from today (please see https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-build-fast/1621163242917203968/build-log.txt for full logs)

confirmed by checking images from yesterday (got the image from here - https://console.cloud.google.com/gcr/images/k8s-staging-releng/global/k8s-ci-builder)

Here's the image from yesterday:
```
[davanum@dev-dsk-davanum-1e-f6a0e82c 16:11] ~ ⟩ IMAGE=gcr.io/k8s-staging-releng/k8s-ci-builder:v20230202-v0.15.0-30-gf7270a77-default
[davanum@dev-dsk-davanum-1e-f6a0e82c 16:11] ~ ⟩ docker run -e DOCKER_IN_DOCKER_ENABLED=true --privileged --rm   --entrypoint=/bin/bash   -it   -v /tmp/docker-graph:/docker-graph   -v $HOME/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes   $IMAGE -c "/bin/sh"
# find . -name *buildx*
./usr/libexec/docker/cli-plugins/docker-buildx
```

Here's the image from today:
```
[davanum@dev-dsk-davanum-1e-f6a0e82c 16:12] ~ ⟩ IMAGE=gcr.io/k8s-staging-releng/k8s-ci-builder:latest-default
[davanum@dev-dsk-davanum-1e-f6a0e82c 16:12] ~ ⟩ docker run -e DOCKER_IN_DOCKER_ENABLED=true --privileged --rm   --entrypoint=/bin/bash   -it   -v /tmp/docker-graph:/docker-graph   -v $HOME/go/src/k8s.io/kubernetes:/go/src/k8s.io/kubernetes   $IMAGE -c "/bin/sh"
# find . -name *buildx*
#
```

Clearly the buildx went missing. Looking at https://github.com/kubernetes/release/commits/master, the go1.20 PR caused all these images to rebuild

**Comment by palnabarun** [comment]
`buildx` seems to be back from leave. 🎉 

```
$ export IMAGE=gcr.io/k8s-staging-releng-test/k8s-ci-builder:v20230202-v0.15.0-34-ga60f818a-default
$ docker run -e DOCKER_IN_DOCKER_ENABLED=true --privileged --rm   --entrypoint=/bin/bash   -it   -v /tmp/docker-graph:/docker-graph   -v $HOME/s/kubernetes/kubernetes:/go/src/k8s.io/kubernetes  $IMAGE -c "/bin/sh"
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
# find . -name *buildx*
./usr/libexec/docker/cli-plugins/docker-buildx
```

**Comment by dims** [comment]
/close

![image](https://user-images.githubusercontent.com/23304/216430527-34d66315-7663-4cfc-a2d7-fc62dfd0b0d8.png)

**Comment by cpanato** [comment]
thanks!
