### ISSUE TITLE
Data Race on the field ''rev''

### ISSUE THREAD

**Issue by UtopiaGitHub** [kubernetes/kubernetes#115534]
### What happened?

During our research on non-blocking concurrency bugs in kubernetes, we discovered a potential Data Race in the program. Specifically，there are two confilicting operations on the field "rev", where

the read operation at：...kubernetes/vendor/go.etcd.io/etcd/client/v3/watch.go:848, and the write operation at：...kubernetes/vendor/go.etcd.io/etcd/client/v3/watch.go:848. In addition, the two statements are excuted many times in the goroutine where the static creation site is: .../kubernetes/vendor/go.etcd.io/etcd/client/v3/watch.go:904.

### What did you expect to happen?

I don't know whether it is accurate, so I 'm looking forward to your reply.

### How can we reproduce it (as minimally and precisely as possible)?

Find the scope of the goroutine through the static creation site。

### Kubernetes version

latest

### Cloud provider

latest

### OS version

Linux Ubuntu20.04

### Install tools

***

### Container runtime (CRI) and version (if applicable)

***

### Related plugins (CNI, CSI, ...) and versions (if applicable)

***

**Comment by pacoxu** [comment]
Do you mean below?
https://github.com/kubernetes/kubernetes/blob/b7ad17978eaba508c560f81bab2fb9d0b256e469/vendor/go.etcd.io/etcd/client/v3/watch.go#L848

https://github.com/kubernetes/kubernetes/blob/b7ad17978eaba508c560f81bab2fb9d0b256e469/vendor/go.etcd.io/etcd/client/v3/watch.go#L904


Can you provide the whole trace/error logs of data race?
