### ISSUE TITLE
Update cli-runtime to Kustomize v5

### ISSUE THREAD

**Issue by stefanprodan** [kubernetes/kubernetes#115547]
### What happened?

Please update the Kustomize packages in cli-runtime to  `sigs.k8s.io/kustomize/api@v0.13.1` and `sigs.k8s.io/kustomize/kyaml@v0.14.0`. Every project that imports both `cli-runtime` and the new `kustomize/api` result in compilation error due to the removal of `DoLegacyResourceSort` which is used in cli-runtime here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/kustomizevisitor.go#L41.

Bumping `sigs.k8s.io/kustomize/api` to `v0.13.1` results in:

```
# k8s.io/cli-runtime/pkg/resource
../../../../pkg/mod/k8s.io/cli-runtime@v0.26.1/pkg/resource/kustomizevisitor.go:41:8:
kOpts.DoLegacyResourceSort undefined (type *krusty.Options has no field or method DoLegacyResourceSort)
```

This issue blocks us from shipping the new features in Kustomize to Flux users, ref: https://github.com/fluxcd/flux2/issues/3564

### What did you expect to happen?

I would expect for the Kustomize API to no ship breaking changes in a minor release, the `DoLegacyResourceSort` was available in `sigs.k8s.io/kustomize/api@v0.12.1`  but removed in `sigs.k8s.io/kustomize/api@v0.13.1`. I really wish Kubernetes would not depend on Kustomize packages...

### How can we reproduce it (as minimally and precisely as possible)?

Bump `sigs.k8s.io/kustomize/api` to `v0.13.1` and run `go vet`.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/kind feature

Updating likely makes sense, but use of matching versions is the expected way to use cli-runtime libraries.

> Every project that imports both `cli-runtime` and the new `kustomize/api` result in compilation error due to the removal of `DoLegacyResourceSort`

Using the version of kustomize specified by the `cli-runtime` go.mod file will avoid compilation errors.

**Comment by XDRAGON2002** [comment]
Hi! I was going through the issue and it seems like that it's just a simple version bump?

If so, being a new contributor to the project could I take this up?

**Comment by natasha41575** [comment]
> I would expect for the Kustomize API to no ship breaking changes in a minor release, the DoLegacyResourceSort was available in sigs.k8s.io/kustomize/api@v0.12.1 but removed in sigs.k8s.io/kustomize/api@v0.13.1. 

 `sigs.k8s.io/kustomize/api` is still v0 series (alpha), so there are no "major" releases, and there can and will be breaking changes in "minor" releases.

> probably so, but @natasha41575 might know better if there were behavior or code changes that would make it non-trivial for Kubernetes to update

You can find [detailed release notes here](https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.13.0).

**Comment by liggitt** [comment]
> `sigs.k8s.io/kustomize/api` is still v0 series (alpha), so there are no "major" releases, and there can and will be breaking changes in "minor" releases.

Specifically, changes in the go API are expected. Behavior changes of invoking `kustomize` against an existing kustomization.yaml file is expected to be backwards compatible.

**Comment by XDRAGON2002** [comment]
So as far as I can tell from the conversation above, it shouldn't be a problem if I bump the versions as requested?

**Comment by odvarkadaniel** [comment]
Hey folks, first of all, sorry for the confusion above this comment...
This is a blocker for a couple of my cards and I see, that there is no movement for a week or so. The PR is up and ready for review.
The method `DoLegacyResourceSort` is deprecated and was in need to get changed here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cli-runtime/pkg/resource/kustomizevisitor.go#L41.

**Comment by stefanprodan** [comment]
Fixed in https://github.com/kubernetes/kubernetes/pull/116598 (scheduled for Kubernetes 1.27)

Thanks @natasha41575
