### ISSUE TITLE
nodeport Port is not displayed

### ISSUE THREAD

**Issue by misteruly** [kubernetes/kubernetes#115568]
### What happened?

**nodeport Port is not displayed**
```
root@k8s-master1:~# kubectl get pod,svc,ep
NAME                              READY   STATUS    RESTARTS   AGE
pod/helloworld-774b4886b7-d957k   1/1     Running   0          8m1s
pod/helloworld-774b4886b7-h8lwf   1/1     Running   0          8m1s

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
service/helloworld   NodePort    10.97.70.128   <none>        8080:32000/TCP   8m
service/kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP          60d

NAME                   ENDPOINTS                                               AGE
endpoints/helloworld   10.244.107.203:8080,10.244.169.159:8080                 8m
endpoints/kubernetes   192.168.1.72:6443,192.168.1.73:6443,192.168.1.74:6443   60d
root@k8s-master1:~# netstat -nltp | grep 32000
root@k8s-master1:~# netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN      25294/calico-node   
tcp        0      0 192.168.1.72:2379       0.0.0.0:*               LISTEN      24482/etcd          
tcp        0      0 127.0.0.1:2379          0.0.0.0:*               LISTEN      24482/etcd          
tcp        0      0 192.168.1.72:2380       0.0.0.0:*               LISTEN      24482/etcd          
tcp        0      0 127.0.0.1:2381          0.0.0.0:*               LISTEN      24482/etcd          
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      24396/kube-controll 
tcp        0      0 0.0.0.0:179             0.0.0.0:*               LISTEN      25442/bird          
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      24446/kube-schedule 
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1112/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1523/sshd           
tcp        0      0 127.0.0.1:17149         0.0.0.0:*               LISTEN      4359/kubelet        
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      4359/kubelet        
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      24708/kube-proxy    
tcp6       0      0 :::10250                :::*                    LISTEN      4359/kubelet        
tcp6       0      0 :::6443                 :::*                    LISTEN      24394/kube-apiserve 
tcp6       0      0 :::10256                :::*                    LISTEN      24708/kube-proxy    
tcp6       0      0 :::22                   :::*                    LISTEN      1523/sshd
```
Port 32000 is not detected on the host

But web is access
![image](https://user-images.githubusercontent.com/31399968/217158520-b18332b9-89bd-4e5e-84d9-7eb5a89a6683.png)

### What did you expect to happen?

The host displays that the port is occupied

### How can we reproduce it (as minimally and precisely as possible)?

upgrade
1.17.9-->1.18.0-->1.19.0-->1.20.0--->1.22.0--->1.23.16

### Kubernetes version

<details>

Kubernetes v1.23.16

</details>

### Cloud provider

<details>

</details>

### OS version

<details>
Ubuntu 18.0.4
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
that works as intended, nodeport with kube-proxy doesn't open a socket, it installs iptables rules to forward the traffic

/close

**Comment by misteruly** [comment]
> that works as intended, nodeport with kube-proxy doesn't open a socket, it installs iptables rules to forward the traffic
> 
> /close

```
[root@k8s-allinone ~]# cat /etc/centos-release
CentOS Linux release 7.8.2003 (Core)
[root@k8s-allinone ~]# kubectl get svc,ep
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/hello-host1   NodePort    10.100.55.54    <none>        8080:30022/TCP   123m
service/helloworld    NodePort    10.109.122.31   <none>        8080:31000/TCP   124m
service/kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP          152m

NAME                    ENDPOINTS             AGE
endpoints/hello-host1   10.233.167.135:8080   123m
endpoints/helloworld    <none>                124m
endpoints/kubernetes    192.168.1.70:6443     152m
[root@k8s-allinone ~]# netstat -nltp | grep 30022
tcp        0      0 0.0.0.0:30022           0.0.0.0:*               LISTEN      26225/kube-proxy
[root@k8s-allinone ~]# kubectl get node -o wide
NAME   STATUS   ROLES                  AGE    VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
node   Ready    control-plane,master   154m   v1.23.16   192.168.1.70   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://23.0.0
[root@k8s-allinone ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
```
Kubernetes v1.23.16 .Then why can centos7 see the port generated by kube-proxy ?

**Comment by aojea** [comment]
> NAME                    ENDPOINTS             AGE
> endpoints/hello-host1   10.233.167.135:8080   123m
> endpoints/helloworld    <none>                124m
> endpoints/kubernetes    192.168.1.70:6443     152m
> [root@k8s-allinone ~]# netstat -nltp | grep 30022
> tcp        0      0 0.0.0.0:30022           0.0.0.0:*               LISTEN      26225/kube-proxy
> [root@k8s-allinone ~]# kubectl get node -o wide
> NAME   STATUS   ROLES                  AGE    VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
> node   Ready    control-plane,master   154m   v1.23.16   192.168.1.70   <none>        CentOS Linux 7 (Core)   3.10.0-1127.el7.x86_64   docker://23.0.0
> [root@k8s-allinone ~]# kubectl version
> Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> Kubernetes v1.23.16 .Then why can centos7 see the port generated by kube-proxy ?


ah , ok ,sorry , kube-proxy had a behavior that opened a socket for each nodeport, that behavior was removed here

https://github.com/kubernetes/kubernetes/pull/108496

You can read in the description the rationale, but the socket was not forwarding traffic if that was your concern
