### ISSUE TITLE
Manage HugePages

### ISSUE THREAD

**Issue by gunjald** [kubernetes/kubernetes#115545]
If swap is disabled then if there is really a case for requesting hugepages? If no data can be swapped out to secondary storage then how a request for hugepages by a pod can help improving the performance?

**Comment by sftim** [comment]
/kind support

I recommend asking this question on [Server Fault](https://serverfault.com/?tags=linux) @gunjald 
This issue tracker isn't the ideal place to learn about Linux hugepages in general.
