### ISSUE TITLE
[Flaky test] gce-cos-master-scalability-100 (APIResponsivenessPrometheusSimple)

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#115589]
### Which jobs are failing?
master-blocking
gce-cos-master-scalability-100

### Which tests failed?
**ClusterLoaderV2.huge-service overall (testing/huge-service/config.yaml)**
**ClusterLoaderV2.huge-service: [step: 11] gathering measurements [01] - APIResponsivenessPrometheusSimple**
![image](https://user-images.githubusercontent.com/2896571/217569995-288dba95-a154-4a6e-9431-e5e1775cab91.png)
#### With others intermittently:
ClusterLoaderV2.load overall (testing/load/config.yaml)ClusterLoaderV2.load: [step: 29] gathering measurements [01] - APIResponsivenessPrometheusSimple
ci-kubernetes-e2e-gci-gce-scalability.Overall
kubetest.ClusterLoaderV2

### When did it fail?
2/7/2023 7:06am,
Then again from 2/8/2023 1:26 am PST - 4:26am PST

### Testgrid link
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100

### Prow links
2/13 10:09am PST - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1625195020225089536
2/7 7:26 PST - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1622974688978276352
2/8 1:26 am PST - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1623251409082257408
2/8 4:26am PST - https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1623296707657732096

### 2/7
High latency observed on scalability tests:
```
{ Failure :0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:endpointslices Subresource: Verb:POST Scope:resource Latency:perc50: 13.888888ms, perc90: 24.428571ms, perc99: 3.667999999s Count:167 SlowCount:5}; expected perc99 <= 1s got: &{Resource:endpoints Subresource: Verb:POST Scope:resource Latency:perc50: 9.795918ms, perc90: 23.591836ms, perc99: 3.661999999s Count:170 SlowCount:5}; expected perc99 <= 1s]]
:0}
```

### Again on 2/8
Same occurrence, with high latency:
```
ClusterLoaderV2: huge-service overall (testing/huge-service/config.yaml)
{ Failure :0 [measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 326ms, perc90: 669.047619ms, perc99: 1.058823529s Count:2182 SlowCount:26}; expected perc99 <= 1s]] :0}
```
```
ClusterLoaderV2: huge-service: [step: 11] gathering measurements [01] - APIResponsivenessPrometheusSimple
{ Failure :0 [measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 326ms, perc90: 669.047619ms, perc99: 1.058823529s Count:2182 SlowCount:26}; expected perc99 <= 1s]] :0}
```
e2e.go: ClusterLoaderV2
```
{  error during /home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-1623296707657732096 --experimental-prometheus-snapshot-to-report-dir=true --nodes=100 --prometheus-scrape-kubelets=true --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/huge-service/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/use_simple_latency_query.yaml --testoverrides=./testing/overrides/load_throughput.yaml: exit status 1}
```

### Again on 2/13
Same occurrence, with high latency:
ClusterLoaderV2: huge-service overall (testing/huge-service/config.yaml)
```
{ Failure :0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 295ms, perc90: 680.473372ms, perc99: 1.124999999s Count:2182 SlowCount:34}; expected perc99 <= 1s]]
:0}
```
ClusterLoaderV2: huge-service: [step: 11] gathering measurements [01] - APIResponsivenessPrometheusSimple
```
{ Failure :0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 295ms, perc90: 680.473372ms, perc99: 1.124999999s Count:2182 SlowCount:34}; expected perc99 <= 1s]]
:0}
```
e2e.go: ClusterLoaderV2
```
{  error during /home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gci-gce-scalability-1625195020225089536 --experimental-prometheus-snapshot-to-report-dir=true --nodes=100 --prometheus-scrape-kubelets=true --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/huge-service/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/use_simple_latency_query.yaml --testoverrides=./testing/overrides/load_throughput.yaml: exit status 1}
```

### Anything else we should know?
There were also high latency tests last on 1/24 with the following build:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1617883613729132544

### Relevant SIG(s)
/sig scalability
cc @kubernetes/ci-signal

**Comment by drewhagen** [comment]
https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100

I'm seeing a build that failed at 2/7/2023 7:06am PST:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/1622974688978276352

**Comment by drewhagen** [comment]
Same failure again yesterday, added to description

**Comment by drewhagen** [comment]
x-posting slack thread: https://kubernetes.slack.com/archives/C09QZTRH7/p1675797131402609

**Comment by drewhagen** [comment]
x-posting slack thread: https://kubernetes.slack.com/archives/C09QZTRH7/p1675797131402609

I will proceed to ask SIG Scalability if these tests can be improved to reduce flakes, but the team doesn't seem all too concerned.

We can probably remove critical-urgent.
/remove-priority critical-urgent
/priority awaiting-more-evidence

**Comment by lauralorenz** [comment]
This job has been green for 10+ runs, and per [previously linked slack thread](https://kubernetes.slack.com/archives/C09QZTRH7/p1675797131402609) with sig-scalability, is not of concern by the team until a stronger pattern of flakiness (3+ in a row) has been observed. We will continue to monitor sig scalability jobs closely but as there is no action intended to be taken on these failures specifically I am closing it.

/close
