### ISSUE TITLE
Server-Side Apply (and fieldmanagement) is missing in client-go/fake

### ISSUE THREAD

**Issue by apelisse** [kubernetes/kubernetes#115598]
Since we already have a few issues about this, I decided to create one more:
https://github.com/kubernetes/client-go/issues/970
https://github.com/kubernetes/client-go/issues/1184
Interesting one: https://github.com/grafana/xk6-kubernetes/pull/81
https://github.com/kubernetes/kubernetes/issues/103816
https://github.com/kubernetes/kubernetes/pull/103821

There are already a few pull-requests that have been pushed to make that happen, current one is waiting on another related pull-request: #115065 
One trick will be to insert the openapi inside the fake test, we can possibly load from file to make it easier.

**Comment by Karthik-K-N** [comment]
@apelisse I would like to work on this, (Previously made an attempt for the same https://github.com/kubernetes/kubernetes/pull/110565)

**Comment by Karthik-K-N** [comment]
Sure, Thank you will wait till then, When I checked now after your code refactoring now we can easily import fieldmanager methods.

**Comment by alvaroaleman** [comment]
@apelisse Would you be able to provide an update as to what the current status is? The original PR linked in the issue got merged. I realize this is quite an involved change, but as of today it isn't possible to unittest code that uses SSA and that IMHO makes it hard to adopt it

**Comment by apelisse** [comment]
I'm still working on this, not making as much progress as I would like but here's the draft: https://github.com/kubernetes/kubernetes/pull/118211

**Comment by apelisse** [comment]
Won't make it to 1.28, planning for next release.

**Comment by EronWright** [comment]
Related:
- [doc: client-go Apply Fake Client: Review of use cases](https://docs.google.com/document/d/1ipi1sZd5rvPvplX_TV74gGOtFWJTf9N0qKnH2-rcI4s/edit)
- https://github.com/kubernetes/kubernetes/issues/99953
- https://github.com/kubernetes-sigs/controller-runtime/issues/2341

**Comment by ecordell** [comment]
https://github.com/kubernetes/kubernetes/pull/125560 added support to the typed kube client fake, but not to the dynamic client. Should this issue remain open to track support in the dynamic client as well?
