### ISSUE TITLE
Pod cgroup cpusets is not getting updated when try to pin the cpus of a container

### ISSUE THREAD

**Issue by pratheeshm** [kubernetes/kubernetes#115541]
### What happened?

Was using the containerd client api to update the cpusets(to use the CPUs 10-23) of the container at runtime.

Container inspection for that particular container showed the CPUs as 10-23

````
"linux": {
            "resources": {
                "devices": [
                    {
                        "allow": false,
                        "access": "rwm"
                    }
                ],
                "memory": {},
                "cpu": {
                    "shares": 10,
                    "cpus": "10-23"
                }
            },
            "cgroupsPath": "/kubepods/burstable/podc16500c3-9dc9-430c-94af-d057f2caac15/a0d6e7602cbd35ef80d0bea4307613b9476b1a2c53f0453edd868d58d7a6f8a2",

````
But when checked in the cgroupsPath of the pod, then  it was showing 0-95(fully available CPUs) for the cpusets

````
root@master2:/sys/fs/cgroup/cpuset/kubepods/burstable/podc16500c3-9dc9-430c-94af-d057f2caac15/a0d6e7602cbd35ef80d0bea4307613b9476b1a2c53f0453edd868d58d7a6f8a2# pwd
/sys/fs/cgroup/cpuset/kubepods/burstable/podc16500c3-9dc9-430c-94af-d057f2caac15/a0d6e7602cbd35ef80d0bea4307613b9476b1a2c53f0453edd868d58d7a6f8a2
root@tb2-smi-blr-s1-c1-master2:/sys/fs/cgroup/cpuset/kubepods/burstable/podc16500c3-9dc9-430c-94af-d057f2caac15/a0d6e7602cbd35ef80d0bea4307613b9476b1a2c53f0453edd868d58d7a6f8a2# 
root@tb2-smi-blr-s1-c1-master2:/sys/fs/cgroup/cpuset/kubepods/burstable/podc16500c3-9dc9-430c-94af-d057f2caac15/a0d6e7602cbd35ef80d0bea4307613b9476b1a2c53f0453edd868d58d7a6f8a2# cat cpuset.cpus
0-95
````

It seems CPU isolation is not happening 

### What did you expect to happen?

Expected cpusets as 10-23 in the cgroup cpusets instead of 0-95

### How can we reproduce it (as minimally and precisely as possible)?

use containerd client api to pin the cpusets of a running container

### Kubernetes version

<details>

```console
kubectl version --output=yaml
clientVersion:
  buildDate: "2022-09-21T13:19:24Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/amd64
kustomizeVersion: v4.5.4
serverVersion:
  buildDate: "2022-09-21T13:12:04Z"
  compiler: gc
  gitCommit: b39bf148cd654599a52e867485c02c4f9d28b312
  gitTreeState: clean
  gitVersion: v1.24.6
  goVersion: go1.18.6
  major: "1"
  minor: "24"
  platform: linux/amd64

```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.6.4
</details>

**Comment by SergeyKanzhelev** [comment]
> Was using the containerd client api to update the cpusets(to use the CPUs 10-23) of the container at runtime.

Can you please elaborate on how this is done specifically?

What are you trying to achieve? Is ti something cpu manager can help with?

/triage needs-information

**Comment by pratheeshm** [comment]
Hi @SergeyKanzhelev 

>Can you please elaborate on how this is done specifically?

Adding the sample code snippet I used to pin the CPU of containers.

````go
containerId:=containerID
ctrs, err := client.Containers(ctx, filter1)
if err != nil {
	panic(err)
}
for _, ctr := range ctrs {
	spec, err := ctr.Spec(ctx)
	if err != nil {
		return err
	}
	opt := containerd.WithSpec(spec, oci.WithCPUs("10-23"))
	if err = ctr.Update(ctx, containerd.UpdateContainerOpts(opt)); err != nil {
		return err
	}
}
````
Reference: 
https://pkg.go.dev/github.com/containerd/containerd@v1.6.4/oci#WithCPUs
https://pkg.go.dev/github.com/containerd/containerd@v1.6.4#WithSpec

>What are you trying to achieve?

Instead of using all the CPUs in a node, I would like to isolate the CPUs for this particular container. My container runtime is containerd. After updating the CPUs, I was able to see the isolated CPUs when I inspected the container. But in the cgroup of that particular container of pod, it was still using all the available CPUs. When I used docker as container runtime in k8s v1.21.0, I was able to isolate the CPUs for a container. Both docker inspect and the cgroup of that container showed only the requested CPUs

> Is it something cpu manager can help with?

I believe it can as the cpusets is handled by the cpu manager.

**Comment by pratheeshm** [comment]
The following code snippet worked for me.   First, we need to update the container spec then we need to update container cgroup resources using the task update.

````go     
    filter := containerId
	ctrs, err := client.Containers(ctx, filter)
	if err != nil {
		log.Error("Failed to query container with filter: ", filter)
		return
	}

	for _, ctr := range ctrs {
		if containerId != ctr.ID() {
			continue
		}
		spec, err := ctr.Spec(ctx)
		if err != nil {
			log.Error("Failed to get the Spec for container with ID: ", containerId)
			continue
		}
		opt := containerd.WithSpec(spec, oci.WithCPUs("10-23"))
		// Update container spec first.
		if err = ctr.Update(ctx, containerd.UpdateContainerOpts(opt)); err != nil {
			log.Error("Failed to update cpuset_cpus container with ID: ", containerId)
			continue
		}
		t, e := ctr.Task(ctx, nil)
		if e != nil {
			log.Error("Error while creating task ", e)
			continue
		}
		// Get the updated spec
		updatedSpec, err := ctr.Spec(ctx)
		if err != nil {
			log.Error("Failed to get the updated spec for container with ID: ", containerId)
			continue
		}
		// Update container cgroup resources using the task update
		if e := t.Update(ctx, containerd.WithResources(updatedSpec.Linux.Resources)); e != nil {
			log.Errorf("Error while updating resources for container id: %s err: %v", containerId, e)
			continue
		} else {
			log.Infof("Updated cpuset_cpus for container id: %s to: %s", containerId, cpuIsolation[cpuAffinityRule])
		}
	}
````

**Comment by ffromani** [comment]
Hi @pratheeshm , happy you have a solution. I would however highlight that changing the settings without passing through cpumanager (effectively racing against cpumanager) is not a supported flow from kubernetes perspective. In other words, any misbehavior noticed while changing the state manually, outside what cpumanager does, can't be considered a cpumanager issue, because cpumanager is designed to be the only controller of these resources.
