### ISSUE TITLE
docs: local/docker recommendations confusing

### ISSUE THREAD

**Issue by wathiede** [kubernetes/kubernetes#11557]
http://kubernetes.io/gettingstarted/ provides a button for 'Local' installation but not 'Local Docker' even though the later is the 'recommended starting point' for local installations elsewhere.

The section 'Local-machine Solutions' on https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides linked from 'Getting Started Guides' on https://github.com/GoogleCloudPlatform/kubernetes states:

```
The local-machine solutions are:

Local Docker-based (recommended starting point)
Vagrant (works on any platform with Vagrant: Linux, MacOS, or Windows.)
No-VM local cluster (Linux only)
```

But the link for 'Local Docker-based' instructions is just an anchor named '#local-solutions'.  I suspect it should point to 'docker.md' in the same directory.

Should there be a button on http://kubernetes.io/gettingstarted/  for 'Local Docker-based'?
Should the 'Local Docker-based' point to docker.md?
Is 'Local Docker-based' the recommend local deployment method?

**Comment by davidopp** [comment]
cc/ @fgrzadkowski

**Comment by davidopp** [comment]
This is marked P1, i.e. release blocker. Should it be?

**Comment by fgrzadkowski** [comment]
I think it's a nice to have. Marking P2.

**Comment by bgrant0607** [comment]
This will be resolved by the minikube work.

cc @vishh @dlorenc

**Comment by dlorenc** [comment]
The minikube work is happening here: https://github.com/kubernetes/minikube

Feel free to follow along :) We're hoping to have something ready to document this quarter.

**Comment by bgrant0607** [comment]
I think this is obsolete
