### ISSUE TITLE
Inappropriate use of method "time.Sleep(time.Second)"

### ISSUE THREAD

**Issue by yanke-xu** [kubernetes/kubernetes#115530]
### What happened?

```
......
135 finished := false
136 wg := sync.WaitGroup{}
137 wg.Add(1)
138 go func() {
139 	    rl.Accept()
140 	    finished = true
141	    wg.Done()
142 }()
143 
144 // Wait some time to make sure it never finished.
145 time.Sleep(time.Second)
146 if finished {
147  	t.Error("Accept should block forever in NeverFake.")
148 }
......
```
where the write operation at：.../kubernetes/staging/src/k8s.io/client-go/util/flowcontrol/throttle_test.go:140
where the read operation at：.../kubernetes/staging/src/k8s.io/client-go/util/flowcontrol/throttle_test.go:146

### What did you expect to happen?

In addition, ‘’time.Sleep()‘’ method cannot ensure the scheduling of goroutines, which can cause data race. Here, we suggest changing to channel or other mandatory waiting.

### How can we reproduce it (as minimally and precisely as possible)?

It is a testing file, just run it.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by qingwave** [comment]
It's okay just use `sleep` to check goroutine works in the test.

**Comment by yanke-xu** [comment]
您好，邮件我已收到，我会及时给您回复，祝好！

**Comment by pacoxu** [comment]
Dup with https://github.com/kubernetes/kubernetes/issues/115530. 
/close
