### ISSUE TITLE
MultiCIDRRangeAllocator requires node reboot to assign ranges

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#115528]
### What happened?

When the `ClusterCIDR` is created *after* a node has booted, addresses are not defined;

```
> kubectl get cc -A
No resources found
> kubectl create -f kubernetes/clustercidr.yaml
clustercidr.networking.k8s.io/default created
> kubectl get cc -A
NAME      PERNODEHOSTBITS   IPV4          IPV6         AGE
default   8                 11.0.0.0/16   1100::/112   5s
> kubectl get node -o json vm-002 | jq .spec
{}
# (reboot node vm-002 ...)
> kubectl get node -o json vm-002 | jq .spec
{
  "podCIDR": "11.0.0.0/24",
  "podCIDRs": [
    "11.0.0.0/24",
    "1100::/120"
  ]
}
```

### What did you expect to happen?

Addresses shall be allocated for all nodes with empty `spec.podCIDRs` when a `ClusterCIDR` is created (*then* they become immutable).

### How can we reproduce it (as minimally and precisely as possible)?

Probably the easiest way is to check the controller:

* Create the controller with MultiCIDRRangeAllocator enabled and configured
* Create a `ClusterCIDR`
* Check the node.spec on the controller
* Reboot it
* Check again

### Anything else we need to know?

I can't see a clean way to start a cluster without this fixed. It the cni-plugin requires spec.podCIDRs to work the node will not become ready until it's rebooted.

As a work-around in my test env I can create a controller that is _not a node_ in the cluster (I think k3s and AWS does like this).

### Kubernetes version

v1.27.0-alpha.1.228+0e3818e02760af

### Cloud provider

None

### OS version

Linux

### Install tools

None

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by uablrek** [comment]
I suppose node reboot can be replaced with `kubelet` restart. But it's still a bug.

**Comment by aojea** [comment]
/assign @sarveshr7 

It is a bug, this may be caused because this controller doesn't reconcile 🤔

**Comment by uablrek** [comment]
It seem to correct itself after ~5min. Still this is too long for nodes to become "ready", even in a newly created cluster.

Nodes _will_ become ready if the CNI-plugin doesn't use the allocated ranges, but that is beside the point (easy to miss in tests though).

**Comment by aojea** [comment]
> It seem to correct itself after ~5min. Still this is too long for nodes to become "ready", even in a newly created cluster.

I submitted https://github.com/kubernetes/kubernetes/pull/115529 to improve the retry logic, it should reconcile faster with it
