### ISSUE TITLE
ImageLocality plugin should consider initContainers when scoring during scheduling

### ISSUE THREAD

**Issue by xiaomudk** [kubernetes/kubernetes#115587]
### What would you like to be added?

We used to only calculate regular containers. However, initContainers should also be counted. 

### Why is this needed?

https://github.com/kubernetes/kubernetes/pull/110382#discussion_r897128424
Because initContainers are also pull request, we need to consider all initContainers when scoring the ImageLocality plugin. WDYT?
@kerthcet  @alculquicondor @Huang-Wei

**Comment by alculquicondor** [comment]
+1

**Comment by kidddddddddddddddddddddd** [comment]
I'd like to implement this one if you're not going to assign yourself :)

**Comment by alculquicondor** [comment]
Feel free to take it

**Comment by kerthcet** [comment]
Maybe let's wait for @xiaomudk response at first, if not, then you can take it for free.

**Comment by xiaomudk** [comment]
Let me give it a try first.

**Comment by xiaomudk** [comment]
Awaiting the outcome of this PR #110382

**Comment by alculquicondor** [comment]
this change should be independent of that discussion.
