### ISSUE TITLE
Mutable Pod scheduling directives when gated

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#115513]
### What would you like to be added?

We introduced PodSchedulingReadiness in https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/3521-pod-scheduling-readiness; 

The main use case for this feature was to enable building external resource controllers (like extended schedulers, dynamic quota managers) to make a decision on when the pod should be eligible for scheduling by kube-scheduler.

This feature proposes to make pod scheduling directives (nodeSelector, affinity) mutable as long as the pod is gated. This is similar to what we did for suspended Job: https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling/2926-job-mutable-scheduling-directives

### Why is this needed?

This allows external resource controllers to not only decide when the pod should be eligible for scheduler, but also where it should land.

/sig scheduling

**Comment by ahg-g** [comment]
One issue brought up by @liggitt was how to ensure that the mutation is compatible with decisions made by policy controllers, and he suggested to restrict the update to constraints that makes the selection more restrictive, like adding affinities.

I think this makes a lot of sense, and it is actually how this feature should be used; for example, given a pod with affinity to A, B or C, the extended resource manager should respect those selections and the decision that it should be able to make is to only limit the selection from this set, not expand it.

**Comment by ahg-g** [comment]
I don't get it, if we only allow updating the affinity to further constraint an existing selection, how are we breaking a decision previously made by a policy webhook? We can constrain this to node selector/affinity since it is easy to apply this restriction, and it is the scheduling directive that actually make sense to update for the use case mentioned in the original post.

**Comment by Huang-Wei** [comment]
> I don't get it, if we only allow updating the affinity to further constraint an existing selection

I misread the word "expansion" you referred to, you meant by allowing adding constraints only. My above example was deleting a constraint.

(I thought of adding a wildcard PodAntiAffinity as a counter-example, but it doesn't fit if it's only applies on node selector / node affinity)

**Comment by Huang-Wei** [comment]
Generally LGTM, some further questions/notes:

- is it allowed to mutate existing nodeSelector/nodeAffinity?
- `nodeSelectorTerms` are ORed but `matchExpressions` are ANDed, so we cannot simply allow addition; instead, it should check whether the mutated constraints are more semantically broader/narrowed
- I cannot think of any possibility of abusing `NotIn`/`DoesNotExist` in an AND context, but just raise here if others can spot some corner case

**Comment by ahg-g** [comment]
Thanks Wei, I detailed in the KEP how to maintain AND semantics for both node affinity and selector. This is sufficient to guarantee a restrictive selection of the nodes.

**Comment by ahg-g** [comment]
Tracked in https://github.com/kubernetes/enhancements/issues/3838
