### ISSUE TITLE
Make kubectl respect XDG base directory specification for caches

### ISSUE THREAD

**Issue by misha-ridge** [kubernetes/kubernetes#115522]
### What would you like to be added?

`kubectl` under Linux keeps `cache` and `http-cache` directories under `~/.kube` by default.

Many Linux application have adopted )XDG base directory specification)[https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html] that specifies, beside other directories, a location for cache files.

I propose to make `kubectl` respect XDG base directory specification for caches. Backward compatibility may be maintained by creating symlinks from `~/.kube` to the cache directory if necessary.

### Why is this needed?

XDG-specified cache directories are typically excluded from backups by default, thus adopting this specification will eliminate hundreds of megabytes of useless backup data per `kubectl` user.

**Comment by ardaguclu** [comment]
As far as I know this is rejected in here https://github.com/kubernetes/enhancements/pull/2111. But you can configure your path with `KUBECACHEDIR` environment variable fixed in here https://github.com/kubernetes/kubectl/issues/1184

I'd prefer closing this as duplicate of linked enhancement proposal

**Comment by misha-ridge** [comment]
That's why I have scoped it to cache only. I understand the problem of moving configuration somewhere else.

**Comment by sftim** [comment]
Is this request specifically for `kubectl` or also for all Kubernetes clients?

If it's just for `kubectl`, we could consider a mechanism to make that use of (eg) `~/.local/cache/kubectl`. If we propose to change all software that speaks Kubernetes, it's probably a nonstarter per https://github.com/kubernetes/kubernetes/issues/115522#issuecomment-1416809674

**Comment by misha-ridge** [comment]
For all of them, oh well, this ship has probably sailed. Every backup application out there should add yet another line to default configuration.

**Comment by misha-ridge** [comment]
Another option to achieve the same result would be to add `CACHEDIR.TAG` as specified here: https://bford.info/cachedir/, some backup programs use it by default, for others it is easy to make a rule "ignore all directories with this file".

**Comment by ogarcia** [comment]
@misha-ridge see https://github.com/kubernetes/kubectl/issues/1044

**Comment by misha-ridge** [comment]
Super, so I'm closing this issue.
