### ISSUE TITLE
kube-proxy IPVS mode configured with method SourceHash and Maglev should evenly distribute connections to all endpoints

### ISSUE THREAD

**Issue by sondinht** [kubernetes/kubernetes#115526]
### What would you like to be added?

# Problem
The current support of the load distribution method `sh` and `mh` in kube-proxy ipvs mode only performs hashing of source IP address to select endpoints. As a result, all connections from a single client (i.e. from a particular source IP) are always forwarded to only one endpoint matching with the hash value of this source IP. If the client opens a vast majority of connections to the k8s cluster, it will result in traffic imbalance as only one endpoint located on one node handles the connections while the remaining endpoints/nodes are idle. 

Here is an example of the problem when using `mh` method for kube-proxy

- Deploy a service with 4 endpoints located on 4 nodes.

```console
~ # kubectl get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP         NODE     NOMINATED NODE   READINESS GATES
alpine-deployment-ffdbfd876-hzff4   1/1     Running   0          2m24s   11.0.2.2   node-002   <none>           <none>
alpine-deployment-ffdbfd876-vrw69   1/1     Running   0          2m24s   11.0.1.2   node-001   <none>           <none>
alpine-deployment-ffdbfd876-w4vh5   1/1     Running   0          2m24s   11.0.4.2   node-004   <none>           <none>
alpine-deployment-ffdbfd876-xgd59   1/1     Running   0          2m24s   11.0.3.2   node-003   <none>           <none>

~ # kubectl get services
NAME             TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
alpine-service   LoadBalancer   12.0.234.80   <pending>     7001:32000/TCP   3m56s
```

- Open 200 connections from a client to node IP of any node (e.g. telnet 192.168.1.1 32000). All connections receive replies from only one single endpoint.

- The distribution printout also shows that all connections are forwarded to the endpoint (e.g. 1.0.4.2:5001 in this example)
```console
TCP  192.168.1.1:32000 mh
  -> 11.0.1.2:5001                Masq    1      0          0
  -> 11.0.2.2:5001                Masq    1      0          0
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.4.2:5001                Masq    1      0          200
```
- Similar issue is seen with `sh` method

```console
TCP  192.168.1.1:32000 sh
  -> 11.0.1.2:5001                Masq    1      0          200
  -> 11.0.2.2:5001                Masq    1      0          0
  -> 11.0.3.2:5001                Masq    1      0          0
  -> 11.0.4.2:5001                Masq    1      0          0
```

### Why is this needed?

Connections from a client should be evenly distributed to all endpoints like `rr` to avoid unbalanced load distribution between cluster nodes and endpoints.

This can be easily done by enabling the source port hash flag that IPVS supports for the methods which performs hashing on both source IP and source port when selecting the target endpoint.

```
 sh - Source Hashing: assigns jobs  to  servers  through  looking  up  a  statically
              assigned  hash  table  by their source IP addresses.  This scheduler has two flags:
              sh-fallback, which enables fallback to a different server if  the  selected  server
              was  unavailable,  and  sh-port,  which  adds  the  source  port number to the hash
              computation.

mh  -  Maglev  Hashing:  assigns  incoming  jobs  based  on Google's Maglev hashing
              algorithm, providing an almost equal share of jobs to each real server and provides
              minimal  disruption. When the set of real servers changes, a connection will likely
              be sent to the same real server as it was before.  This scheduler  has  two  flags:
              mh-fallback,  which  enables  fallback to a different server if the selected server
              was unavailable, and mh-port, which  adds  the  source  port  number  to  the  hash
              computation.
```

**Comment by sondinht** [comment]
This issue was raised based on the discussion of the issue https://github.com/kubernetes/kubernetes/issues/114619#issuecomment-1376218400

**Comment by uablrek** [comment]
triage/accepted
/assign

**Comment by uablrek** [comment]
/triage/accepted

**Comment by uablrek** [comment]
/triage accepted
(damn it!)

**Comment by rbjorklin** [comment]
@sondinht how many backends do your services have? Have you found the [default value](https://github.com/torvalds/linux/blob/v6.1/net/netfilter/ipvs/ip_vs_mh.c#L49-L59) for `MH_TAB_INDEX` to be sufficient?

**Comment by sondinht** [comment]
@rbjorklin Since I only experimented with the `mh` method in a test cluster with a maximum of 10 backends, it’s hard to determine if the default table size of 4096 (2^12) is sufficient. However, `MH_TAB_INDEX` can be fine-tuned by users based on the number of backends they plan to deploy for their services. From my understanding, `kube-proxy` does not currently provide a way to change this size.

It’s true that a larger table size makes the Maglev algorithm more resilient to backend changes. However, as mentioned in the same section, a larger table size also increases the lookup table generation time. This makes table size selection a trade-off that users will need to consider if the default size proves insufficient.
