### ISSUE TITLE
kubectl cp of a tar file fails with invalid tar magic

### ISSUE THREAD

**Issue by vaishali-prophecy** [kubernetes/kubernetes#115573]
Tar file doesn't seem to be corrupt as extracting this tar file works.. but kubectl cp immediately fails with error below - 

tar: invalid tar magic
command terminated with exit code 1

This tar is around 32GB in size and I am guessing this is some misleading error because even if the tar file was invalid, what does kubectl cp have to do with it anyway. Any help in this regard would be highly appreciated.

Note that I have 2 pods in 2 clusters. In one cluster I took backup and copied tar (this same tar) from one pod( say podA) to another  pod (say podB) and then uploaded it to s3.

In second cluster, I was trying to perform restore by downloading this tar from s3 in podB and then run kubectl cp from podB to podA. In this case, kubectl cp fails with above error.

**Comment by vaishali-prophecy** [comment]
@sftim Its an alpine based base image - alpine:3.15.6

**Comment by pacoxu** [comment]
For `kubectl cp` large files, there is https://github.com/kubernetes/kubernetes/issues/60140 but the error message is different.

For `invalid tar magic`, I can only find https://unix.stackexchange.com/questions/249353/invalid-tar-magic-on-openwrt.

**Comment by weeee9** [comment]
Hi @vaishali-prophecy, did you solve the problem?
