### ISSUE TITLE
pull-kubernetes-unit failing

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#115637]
### Which jobs are failing?

 https://prow.k8s.io/?job=pull-kubernetes-unit

reported by @jiahuif here:

https://kubernetes.slack.com/archives/C7J9RP96G/p1675902134074689

### Which tests are failing?

the entire job

### Since when has it been failing?

recently

### Reason for failure (if possible)

prow issue, permission denied on /.gitconfig

### Anything else we need to know?

https://github.com/kubernetes/test-infra/pull/28688#issuecomment-1423427848

### Relevant SIG(s)

/sig testing
/assign

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28695

**Comment by BenTheElder** [comment]
This is probably the only job impacted, because it's unusual that our jobs don't run as root (yeah...)

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/test-infra/pull/28696

**Comment by aramase** [comment]
> This is probably the only job impacted, because it's unusual that our jobs don't run as root (yeah...)

Seeing this issue with `pull-kubernetes-e2e-gce-100-performance` too (ref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115350/pull-kubernetes-e2e-gce-100-performance/1623478660327542784)

**Comment by BenTheElder** [comment]
Interesting, that doesn't quite make sense because `pull-kubernetes-e2e-gce-100-performance` is running as root with elevated permissions (for docker in docker).

**Comment by BenTheElder** [comment]
revert is in, retesting on @aramase's PR to see if we're in the clear

**Comment by BenTheElder** [comment]
```
$ PWD=/home/prow/go/src/k8s.io/perf-tests  git config --global --add safe.directory /home/prow/go/src/k8s.io/perf-tests (runtime: 1.578184ms)
error: could not lock config file /root/.gitconfig: File exists
```

slightly different error with `pull-kubernetes-e2e-gce-100-performance`

**Comment by aramase** [comment]
Looking at the dashboard for `pull-kubernetes-e2e-gce-100-performance`, it seems to be intermittent.

**Comment by BenTheElder** [comment]
Looking green after revert:
https://prow.k8s.io/?job=pull-kubernetes-unit
https://prow.k8s.io/?job=pull-kubernetes-e2e-gce-100-performance
