### ISSUE TITLE
Group operations in docs/api-reference/operations.html by kind

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/kubernetes#11567]
It will be good to create subgroups in docs/api-reference/operations.html, where each subgroup lists all possible operations for a given kind.
Then we can link to, for ex, the subgroup for all possible operations for pods from pods.md

cc @caesarxuchao @bgrant0607

**Comment by bgrant0607** [comment]
Agreed

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
