### ISSUE TITLE
Network policy specifies that access to a namespace failed

### ISSUE THREAD

**Issue by xunmeng-666** [kubernetes/kubernetes#115602]
### Which jobs are failing?

When using network policy to specify address to access a namespace, all pods in the space where the rule is located cannot be accessed through name.namespace.svc.cluster.local.
Kubernetes Version: v1.23.8
Calico Version: v3.23.2
Yaml file:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-test
  namespace: test1
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test2
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test1
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test2
podSelector:
    matchLabels:
      app: ng1

### Which tests are failing?

Namespaces that are not specified for access are accessible. Yaml file：
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-test
  namespace: test1
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test1
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: test2
 podSelector:
    matchLabels:
      app: ng1

### Since when has it been failing?

Failed to specify the namespace to access

### Reason for failure (if possible)

I have tried to specify the IP address and podSelector, which can be accessed.

### Relevant SIG(s)

/sig <network>

**Comment by pacoxu** [comment]
It seems to be a calico support issue, https://github.com/projectcalico/calico/issues/ may be the right place to submit if this can be proved to be a bug.
/kind support
