### ISSUE TITLE
Panic Runtime Error on Kali

### ISSUE THREAD

**Issue by smt1821** [kubernetes/kubernetes#115698]
### What happened?

Trying to run this 
"kubectl config set-credentials system:kube-proxy --client-certificate=kube-proxy.pem --client-key=kube-proxy-key.pem --embed-certs=true --kubeconfig=kube-proxy.kubeconfig
"

### What did you expect to happen?

I need to have kube-proxy.kubeconfig file

### How can we reproduce it (as minimally and precisely as possible)?

kubectl config set-credentials system:kube-proxy --client-certificate=kube-proxy.pem --client-key=kube-proxy-key.pem --embed-certs=true --kubeconfig=kube-proxy.kubeconfig

### Anything else we need to know?

kubectl config set-credentials system:kube-proxy --client-certificate=kube-proxy.pem --client-key=kube-proxy-key.pem --embed-certs=true --kubeconfig=kube-proxy.kubeconfig
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x40f9fc]

goroutine 1 [running]:
reflect.mapiternext(0xc0001ae330?)
        /usr/lib/go-1.18/src/runtime/map.go:1378 +0x19
k8s.io/kubernetes/vendor/github.com/modern-go/reflect2.(*UnsafeMapIterator).UnsafeNext(0x4?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/modern-go/reflect2/unsafe_map.go:136 +0x32
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sortKeysMapEncoder).Encode(0xc0002e1710, 0xc0007930a8, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_map.go:297 +0x31a
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x15cae60?, 0xc0005ae501?, 0xc00043d1b8?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0003ab410, 0x14fc92f?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0003ab560, 0x7fff3f199239?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*placeholderEncoder).Encode(0x15cae60?, 0x824601?, 0xc00043d1b8?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:332 +0x22
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc0003ab800, 0x14c2092?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc0003ab860, 0x1572280?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*sliceEncoder).Encode(0xc0005a2780, 0xc00064cb58, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_slice.go:38 +0x2bd
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structFieldEncoder).Encode(0xc000426420, 0x14c7e51?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:110 +0x56
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*structEncoder).Encode(0xc000426510, 0x0?, 0xc00043d1a0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_struct_encoder.go:158 +0x765
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*OptionalEncoder).Encode(0xc00019c820?, 0x0?, 0x0?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect_optional.go:70 +0xa4
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*onePtrEncoder).Encode(0xc00059a5f0, 0xc00064cb00, 0xc000599ef0?)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:219 +0x82
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*Stream).WriteVal(0xc00043d1a0, {0x164fd00, 0xc00064cb00})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/reflect.go:98 +0x158
k8s.io/kubernetes/vendor/github.com/json-iterator/go.(*frozenConfig).Marshal(0xc00019c820, {0x164fd00, 0xc00064cb00})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/json-iterator/go/config.go:299 +0xc9
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).doEncode(0x14a5cb0?, {0x1a06bb0?, 0xc00064cb00?}, {0x19fdbc0, 0xc0001fbad0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:306 +0x6d
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.(*Serializer).Encode(0xc00033e0f0, {0x1a06bb0, 0xc00064cb00}, {0x19fdbc0, 0xc0001fbad0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:301 +0xfc
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).doEncode(0xc0003b0280, {0x1a06b60?, 0xc00043d140}, {0x19fdbc0, 0xc0001fbad0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:244 +0x8fa
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning.(*codec).Encode(0xc0003b0280, {0x1a06b60, 0xc00043d140}, {0x19fdbc0, 0xc0001fbad0})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/serializer/versioning/versioning.go:184 +0x106
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime.Encode({0x7f511c7291d8, 0xc0003b0280}, {0x1a06b60, 0xc00043d140})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/runtime/codec.go:50 +0x64
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.Write(...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:473
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.WriteToFile({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0001fb650}, 0xc0001fb680, 0xc0001fb6b0, 0xc0001fb6e0, {0x0, ...}, ...}, ...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/loader.go:426 +0xa8
k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd.ModifyConfig({0x1a15da8, 0xc0000a0460}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0xc0001fad50}, 0xc0001fad80, 0xc0001fadb0, ...}, ...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/tools/clientcmd/config.go:294 +0xcf8
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.createAuthInfoOptions.run({{0x1a15da8, 0xc0000a0460}, {0x7fff3f199239, 0x11}, {0x1, {0x7fff3f199260, 0xe}}, {0x1, {0x7fff3f19927c, 0x12}}, ...})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:203 +0x31d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config.newCmdConfigSetAuthInfo.func1(0xc00069d340?, {0x178c86e?, 0x5?, 0x5?})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/config/create_authinfo.go:161 +0xf8
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc00069d340, {0xc0000a0550, 0x5, 0x5})
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:854 +0x663
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d2dc0)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:958 +0x39c
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /build/kubernetes-oULibp/kubernetes-1.20.5+really1.20.2/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:895
main.main()
        _output/local/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1bb

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
lient Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"archive", BuildDate:"2022-04-02T14:49:13Z", GoVersion:"go1.18", Compiler:"gc", Platform:"linux/amd64"}


</details>


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2022.3"
VERSION_ID="2022.3"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

$ uname -a
Linux kali 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig cli auth
/remove-sig network
```
vendor/k8s.io/kubectl/pkg/cmd/config.createAuthInfoOptions.run
```

**Comment by enj** [comment]
The release tag `kubernetes-1.20.5+really1.20.2` looks rather suspect to me.  Can you reproduce the issue using the latest version of `kubectl` from an official release?

**Comment by smt1821** [comment]
> The release tag `kubernetes-1.20.5+really1.20.2` looks rather suspect to me. Can you reproduce the issue using the latest version of `kubectl` from an official release?

I couldnt reproduce the issue with Client Version: v1.26.1

Thanks
