### ISSUE TITLE
[Failing Test] [sig-scalability] gce-cos-master-scalability-100

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#115618]
### Which jobs are failing?

master-blocking

- gce-cos-master-scalability-100

### Which tests are failing?

- ClusterLoaderV2: huge-service overall (testing/huge-service/config.yaml)
- ClusterLoaderV2: huge-service: [step: 11] gathering measurements [01] - APIResponsivenessPrometheusSimple
![Screenshot from 2023-02-08 19-43-47](https://user-images.githubusercontent.com/73882557/217554280-fc1deae4-8f14-4756-911c-c34b1c8e5e0a.png)

### Since when has it been failing?

2023-02-08 09:26:32 +0000 UTC

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-blocking#gce-cos-master-scalability-100

### Reason for failure (if possible)

1. ClusterLoaderV2: huge-service overall (testing/huge-service/config.yaml)
`{ Failure :0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 326ms, perc90: 669.047619ms, perc99: 1.058823529s Count:2182 SlowCount:26}; expected perc99 <= 1s]]
:0}`

2. ClusterLoaderV2: huge-service: [step: 11] gathering measurements [01] - APIResponsivenessPrometheusSimple
`{ Failure :0
[measurement call APIResponsivenessPrometheus - APIResponsivenessPrometheusSimple error: top latency metric: there should be no high-latency requests, but: [got: &{Resource:serviceaccounts Subresource:token Verb:POST Scope:resource Latency:perc50: 326ms, perc90: 669.047619ms, perc99: 1.058823529s Count:2182 SlowCount:26}; expected perc99 <= 1s]]
:0}`

### Relevant SIG(s)

/sig scalability
cc @kubernetes/ci-signal

**Comment by Vyom-Yadav** [comment]
Failing due to similar reasons at https://github.com/kubernetes/kubernetes/issues/115589
/triage duplicate

**Comment by drewhagen** [comment]
Green build as of 5:21am PST. We could track this as flaky for a bit

**Comment by mehabhalodiya** [comment]
It's completely green now; we can close this issue. Thanks!

/close
