### ISSUE TITLE
[Failing Test] build-master

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#115675]
### Which jobs are failing?

master-blocking

- build-master

### Which tests are failing?

Overall build is failing

![Screenshot from 2023-02-10 10-42-47](https://user-images.githubusercontent.com/73882557/218006454-a1598016-f5a8-4cc6-8672-2eb353403734.png)

### Since when has it been failing?

2023-02-09 23:09:58 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#build-master

### Reason for failure (if possible)

`make: *** [Makefile:487: cross] Error 1
!!! [0210 00:35:55] Call tree:
!!! [0210 00:35:55]  1: build/../build/common.sh:484 kube::build::run_build_command_ex(...)
!!! [0210 00:35:55]  2: build/release.sh:36 kube::build::run_build_command(...)
make: *** [Makefile:374: release] Error 1
level=fatal msg="failed to run: running make release: command /usr/bin/make release did not succeed: !!! [0210 00:35:54] Call tree:\n!!! [0210 00:35:54]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\nmake[1]: *** [Makefile:92: all] Error 1\nmake: *** [Makefile:487: cross] Error 1\n!!! [0210 00:35:55] Call tree:\n!!! [0210 00:35:55]  1: build/../build/common.sh:484 kube::build::run_build_command_ex(...)\n!!! [0210 00:35:55]  2: build/release.sh:36 kube::build::run_build_command(...)\nmake: *** [Makefile:374: release] Error 1\n" `

### Relevant SIG(s)

/sig testing

**Comment by MadhavJivrajani** [comment]
looks like the same issue again: https://github.com/kubernetes/kubernetes/issues/115605

```
/tmp.k8s/go-link-466742986/go.o: in function `k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/ec2.(*ModifyCapacityReservationInput).GoString':
[328](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1623887116410818560#1:build-log.txt%3A328)
go.go:(.text+0x207ccb8): relocation truncated to fit: R_ARM_CALL against `runtime.duffcopy'
[329](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1623887116410818560#1:build-log.txt%3A329)
go.go:(.text+0x207ccc4): relocation truncated to fit: R_ARM_CALL against `runtime.duffcopy'
[330](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1623887116410818560#1:build-log.txt%3A330)
/tmp.k8s/go-link-466742986/go.o: in function `k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/ec2.(*ModifyCapacityReservationInput).String':
[331](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1623887116410818560#1:build-log.txt%3A331)
go.go:(.text+0x207cd68): relocation truncated to fit: R_ARM_CALL against `runtime.duffcopy'
[332](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-build/1623887116410818560#1:build-log.txt%3A332)
collect2: error: ld returned 1 exit status
```

/cc @saschagrunert @palnabarun

**Comment by Vyom-Yadav** [comment]
@MadhavJivrajani This would fall under sig-release or sig-testing? couldn't really gather much from logs about this though failure is `command /usr/bin/make release did not succeed` so I guess sig-release then.

**Comment by saschagrunert** [comment]
I'm going to reopen https://github.com/kubernetes/kubernetes/pull/115613 for that, which should work around the issue.

**Comment by MadhavJivrajani** [comment]
@Vyom-Yadav that's correct :)
/remove-sig testing
/sig release

**Comment by saschagrunert** [comment]
The PR does not seem to fix the problem without disabling test cases. Opening a slack discussion and closing the loop: https://kubernetes.slack.com/archives/C2C40FMNF/p1676036766902279

**Comment by Vyom-Yadav** [comment]
Failing again.
/reopen

**Comment by liggitt** [comment]
this is a different error:

```
# k8s.io/kubernetes/cmd/genman
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-gnueabihf-gcc failed: exit status 1
/usr/lib/gcc-cross/arm-linux-gnueabihf/10/../../../../arm-linux-gnueabihf/bin/ld.gold: internal error in arm_branch_common, at ../../gold/arm.cc:4079
collect2: error: ld returned 1 exit status
```

can we spawn a new issue to track rather than reopening the same one and mixing investigations for different issues?

**Comment by Vyom-Yadav** [comment]
Oh just the stack trace for make was the same, my bad, opened https://github.com/kubernetes/kubernetes/issues/116492

/close
