### ISSUE TITLE
[Action Required] Update references from k8s.gcr.io to registry.k8s.io

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes/kubernetes#115631]
With the [change to defaulting](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) to registry.k8s.io as our image registry and the [planned freeze in April](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/), projects within the Kubernetes orgs should update their image references to point to the new address.

NOTE: We can ignore references to staging-k8s.gcr.io, but any other references to k8s.gcr.io _should_ be updated to registry.k8s.io

ref: [[Umbrella Issue] Migrate K8s projects from k8s.gcr.io -> registry.k8s.io](https://github.com/kubernetes/k8s.io/issues/4738)

- [x] [staging/src/k8s.io/apiserver/](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=staging%2Fsrc%2Fk8s.io%2Fapiserver&excludeFiles=&repos=kubernetes/kubernetes) (sig-apimachinery)
- [x] [staging/src/k8s.io/pod-security-admission/](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=staging%2Fsrc%2Fk8s.io%2Fpod-security-admission%2F&excludeFiles=&repos=kubernetes/kubernetes) (sig-auth)
- [x] [test/](https://cs.k8s.io/?q=k8s.gcr.io&i=nope&files=%5Etest%2F&excludeFiles=&repos=kubernetes/kubernetes) (sig-node, they're node related tests)

/kind cleanup
/sig api-machinery
/sig auth
/sig node
/priority important-soon

**Comment by yashsingh74** [comment]
@mrbobbytables Can I help with some of the opened task.
Happy to help.

**Comment by mrbobbytables** [comment]
@yashsingh74 PRs are open for everything already

**Comment by mrbobbytables** [comment]
All PRs merged, going to go ahead and close.
Thanks all!
