### ISSUE TITLE
client-go: if an error occurs during request construction, URL() can return a useless result with no indication of an error

### ISSUE THREAD

**Issue by skitt** [kubernetes/kubernetes#115683]
### What happened?

When constructing a `rest.Request`, _e.g._ to stream I/O from a pod:

```
	req := k8s.CoreV1().RESTClient().Post().Resource("pods").Name(podName).Namespace(podNamespace).SubResource("exec")
	req.VersionedParams(&v1.PodExecOptions{
		Command: command,
		Stdin:   false,
		Stdout:  true,
		Stderr:  true,
		TTY:     true,
	}, scheme.ParameterCodec)
	exec, err := remotecommand.NewSPDYExecutor(config, "POST", req.URL())
```

if `req.err` ends up set, `req.URL()` will still return a result without indicating that something went wrong, resulting in a misleading error further down the line. (In my case, I wasn’t providing the correct scheme; the parameters therefore couldn’t be encoded, and the SPDY upgrade failed with an error saying that at least one of stdin, stdout or stderr had to be provided.)

### What did you expect to happen?

Other operations on `rest.Request` fails as appropriate if `req.err` is not `nil`; I would expect `URL()` to do so too. I realise that means a backwards-incompatible change.

Another solution could be to provide a `req.Error()` (same as on the response).

### How can we reproduce it (as minimally and precisely as possible)?

See above, with any scheme other than client-go’s.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by skitt** [comment]
@aojea is it really the same though? In the case which led to my filing this issue, the call to `req.VersionedParams()` results in an error, which is recorded in `req.err`, but the caller has no way to know that.

The main issue I have with this is that in most code paths, `r.err` does end up being returned, _e.g._ calls to `Do()` etc. But callers using only `URL()` have no way of knowing that the URL they get is unusable.

**Comment by aojea** [comment]
> the call to req.VersionedParams() results in an error, which is recorded in req.err

I didn't understand that from the description sorry

https://github.com/kubernetes/kubernetes/blob/adb75e1fd17b11e6a0256a4984ef9b18957d94ce/staging/src/k8s.io/client-go/1.4/rest/request.go#L443-L495

> The main issue I have with this is that in most code paths, r.err does end up being returned, e.g. calls to Do() etc. But callers using only URL() have no way of knowing that the URL they get is unusable.

I see what you mean now, the methods that execute the request return the error, but if you want to reuse the request instead of executing it, you can't know that value until it is executed

IMHO is a legit demand to use a getter for Error(), the field is there but not accessible , @liggitt WDYT?

**Comment by liggitt** [comment]
a Request#Error() getter seems reasonable
