### ISSUE TITLE
Upgrading kubernetes-cni package from 1.1.1 to 1.2.0 removes and recreates the /opt/cni/bin directory

### ISSUE THREAD

**Issue by emosbaugh** [kubernetes/kubernetes#115629]
### What happened?

Upgrading kubernetes-cni package from 1.1.1 to 1.2.0 removes and recreates the /opt/cni/bin directory.

This removes all CNI plugin binaries from the directory.

When using flannel CNI this causes pods to get stuck in ContainerCreating until flannel pod is deleted and recreated.

See https://github.com/flannel-io/flannel/issues/1721

### What did you expect to happen?

Existing CNI plugin binaries will not get removed when upgrading the kubernetes-cni package.

Unfortunately I'm not familiar enough with CNI to understand if the plugin should be installed in a different directory or Flannel should handle re-installing the binary.

### How can we reproduce it (as minimally and precisely as possible)?

https://gist.github.com/emosbaugh/05f340c2a48b4ab3b2e797ce11b38b74

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
ethan@ethanm-flannel-8:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
gcp
</details>

### OS version

<details>

```console
# On Linux:

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

$ uname -a
Linux ethanm-flannel-8 5.15.0-1027-gcp #34~20.04.1-Ubuntu SMP Mon Jan 9 18:40:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T15:59:57Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Container runtime (CRI) and version (if applicable)

<details>
$ sudo ctr version
Client:
  Version:  1.6.16
  Revision: 31aa4358a36870b21a992d3ad2bef29e1d693bec
  Go version: go1.18.10

Server:
  Version:  1.6.16
  Revision: 31aa4358a36870b21a992d3ad2bef29e1d693bec
  UUID: 03edd341-3443-46a5-923e-ecc6b87db71b
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Flannel 0.21.1
</details>

**Comment by emosbaugh** [comment]
I've reproduced with more relevant kubernetes versions (1.26.0 -> 1.26.1) and updated the gist accordingly.

```
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by cyclinder** [comment]
I noticed that you upgraded kubernetes-cni package via `apt list --installed kubernetes-cni`, right?  Maybe `apt` removes all CNI plugin binaries from the directory.  So I don't think it's related to `kubernets`,

**Comment by chris-sanders** [comment]
I don't think you're reading that correctly.
The upgrade happens here https://gist.github.com/emosbaugh/05f340c2a48b4ab3b2e797ce11b38b74#file-flannel-kubernetes-cni-upgrade-repro-sh-L101

The calls to `apt list` are to demonstrate which version of the package currently exists. I don'e believe `apt list` can install packages Ref: https://manpages.ubuntu.com/manpages/xenial/man8/apt.8.html

If I'm reading it correctly: 
* kubernetes-cni is held to prevent upgrade
* The kubernetes packages are upgraded
* the kubernetes-cni package is printed to show it wasn't upgraded
* the kubernetes-cni package is unheld
* the same upgrade is run
* the kuberntees-cni package is printed to show it now is upgraded

**Comment by emosbaugh** [comment]
Chris is right. I need to force the kubernetes-cni package to be present
prior to the installation of kubelet because apt will choose 1.2.0 based on
the dependencies. Had I installed 3 weeks ago prior to the release of 1.2.0
it would have chosen 1.1.1.

Sent via Superhuman iOS ***@***.***>

**Comment by MikeZappa87** [comment]
Hello, are you referencing some documentation to do this upgrade? If so, can I have a look? It might be a little misleading. Trying to figure out if this is a standing cluster or you are provisioning a new one, looks like this is a standing cluster. 

One thing I need to look into if the flannel network plugin requires the community plugins at all. I don't know off the top of my head some do like Calico. If flannel doesn't need the community plugins, then you don't need to worry about the upgrade any longer. To add some details, the container runtime (cri-o, containerd) requires a single network configuration in the /etc/cni/net.d dir and at least one binary in the /opt/cni/bin directory. Its generated recommended to drain the node prior any upgrades/maintenance. Let me know if you require additional guidance, I am happy to help!

**Comment by emosbaugh** [comment]
Yes. I am referencing this documentation

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#upgrade-kubelet-and-kubectl

I have an existing cluster I installed a while back and the kubernetes-cni package version that was installed as a dependency of kubelet is 1.1.1. In trying to replicated my environment for reproduction, the script I have shared provisions a new cluster, manually installing the 1.1.1 version.

In upgrading the kubelet following the documentation linked above, the kubernetes-cni package gets upgraded to 1.2.0 as that is the latest available as of Jan 16. When that happens, the `/opt/cni/bin` directory gets recreated removing the /opt/cni/bin/flannel binary.

As a workaround, restarting the flannel pods will recreate this binary as it gets created as part of an initContainer.

Unfortunately the drain instructions you are referring to include the `--ignore-daemonsets` flag and the Flannel pods are part of a DaemonSet.

**Comment by MikeZappa87** [comment]
The kubernetes-cni dependency is news to me. I am curious about the backstory to this one. The container runtime also installs the cni binaries as well (at least containerd does) which makes more sense as they have the actual dependency on the CNI binaries and network configuration.

**Comment by aojea** [comment]
> 1. Should the kubelet package have a dependency on the kubernetes-cni package?

this is a legacy things from the time of dockershim and kubenet, that were removed in 1.24

> The kubernetes-cni dependency is news to me.

the package is owned by sig-release, sig-network can not do anything here since there is no dependency on cni

/remove-sig network
/sig release

**Comment by emosbaugh** [comment]
Yes there is a dependency. Thank you for pointing me to the correct sig!

```
$ apt show kubelet | grep -E '(Version|Depends)'
Version: 1.26.1-00
Depends: iptables (>= 1.4.21), kubernetes-cni (>= 1.2.0), iproute2, socat, util-linux, mount, ebtables, ethtool, conntrack
```

**Comment by aojea** [comment]
https://github.com/kubernetes/release/blob/61ad093a15a8c21ddc80565c67a7d2f4bec13a98/packages/deb/bionic/kubernetes-cni/debian/control

**Comment by MikeZappa87** [comment]
Thanks @aojea hopefully sig-release can remove this package

**Comment by chris-sanders** [comment]
I'm not sure if the bot will let me but /remove-lifecycle stale
This seems to be well understood and the sig-release just needs to fix the error.

**Comment by pacoxu** [comment]
> https://github.com/kubernetes/release/blob/61ad093a15a8c21ddc80565c67a7d2f4bec13a98/packages/deb/bionic/kubernetes-cni/debian/control

After https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/, kubepkg related are removed. 

The deps are maintained in below:

https://github.com/kubernetes/release/blob/0dd064ffaf301224efbba3f9f4b7da7c537f9d51/cmd/krel/templates/latest/metadata.yaml#L75-L100

https://github.com/kubernetes/release/blob/0dd064ffaf301224efbba3f9f4b7da7c537f9d51/cmd/krel/templates/latest/kubelet/kubelet.spec#L19-L21
