### ISSUE TITLE
[Failing test] build-master

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#115605]
### Which jobs are failing?

master-blocking

- build-master

### Which tests are failing?

ci-kubernetes-build.Overall

![Screenshot from 2023-02-08 10-13-11](https://user-images.githubusercontent.com/73882557/217435605-8cd1c762-58c3-4f39-bb00-e9167998553f.png)

### Since when has it been failing?

2023-02-07 22:06:39 +0000 UTC

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-blocking#build-master

### Reason for failure (if possible)

`make: *** [Makefile:374: release] Error 1
level=fatal msg="failed to run: running make release: command /usr/bin/make release did not succeed: build/../build/common.sh: line 604: ifconfig: command not found\n!!! [0207 23:28:23] Call tree:\n!!! [0207 23:28:23]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\nmake[1]: *** [Makefile:92: all] Error 1\nmake: *** [Makefile:487: cross] Error 1\n!!! [0207 23:28:25] Call tree:\n!!! [0207 23:28:25]  1: build/../build/common.sh:484 kube::build::run_build_command_ex(...)\n!!! [0207 23:28:25]  2: build/release.sh:36 kube::build::run_build_command(...)\nmake: *** [Makefile:374: release] Error 1\n" `

`ifconfig: command not found`
Looks like the binary is not present in the test environment.

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by BenTheElder** [comment]
/sig release
/remove-sig testing

looks like https://github.com/kubernetes/release/tree/93f301f3037e3f90f4ee281afc8cc13dbeb132fa/images/releng/k8s-ci-builder needs patching

**Comment by BenTheElder** [comment]
I'm about to go offline for the night, probably just needs to add iproute2 package to the apt-get install. I would guess this is because during go1.20 upgrade https://github.com/kubernetes/release/commit/99d0ff022152ee4b45c2c21fa45c3aeed5c95b8b it also went from buster to bullseye (Didn't confirm, but same issue going from buster to bullseye elsewhere, seems likely go1.20 included a newer debian base)

**Comment by MadhavJivrajani** [comment]
Thanks Ben!

**Comment by palnabarun** [comment]
`iproute2` contains only the `ip` utility. `net-tools` package has `ifconfig`.

Long term, we should investigate if we can eliminate using `ifconfig` entirely as `iproute2` is touted as its replacement.

**Comment by aojea** [comment]
> Long term, we should investigate if we can eliminate using `ifconfig` entirely as `iproute2` is touted as its replacement.

you can @palnabarun , do you have a link to the code so I can see if I can PR or suggest how to fix it?

**Comment by palnabarun** [comment]
@aojea -- references to `ifconfig` are across the repositories: https://cs.k8s.io/?q=ifconfig&i=nope&files=&excludeFiles=&repos=

The reference to `ifconfig` in current context is in https://github.com/kubernetes/kubernetes/blob/b7ad17978eaba508c560f81bab2fb9d0b256e469/build/common.sh#L604. There's a check in https://github.com/kubernetes/kubernetes/blob/b7ad17978eaba508c560f81bab2fb9d0b256e469/build/common.sh#L598 which should switch to `ip` if that is present.

**Comment by aojea** [comment]
yeah, so that should work if `ifconfig`doesn't exist

https://github.com/kubernetes/kubernetes/blob/b7ad17978eaba508c560f81bab2fb9d0b256e469/build/common.sh#L597-L605

**Comment by palnabarun** [comment]
Yes, that's because even `iproute2` isn't installed.

**Comment by palnabarun** [comment]
The build failed again.

Investigating:
```
 /usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-gnueabihf-gcc failed: exit status 1
/tmp.k8s/go-link-865684912/go.o: in function `k8s.io/kubernetes/vendor/github.com/aws/aws-sdk-go/service/ec2.(*ModifyCapacityReservationInput).GoString':
go.go:(.text+0x207ca88): relocation truncated to fit: R_ARM_CALL against `runtime.duffcopy'
go.go:(.text+0x207ca94): relocation truncated to fit: R_ARM_CALL against `runtime.duffcopy'
collect2: error: ld returned 1 exit status 
```

**Comment by palnabarun** [comment]
On a first pass, this looks similar to https://github.com/grafana/agent/issues/2894

**Comment by saschagrunert** [comment]
I tried on latest debian with a cross compile toolchain and golang 1.20 and was successful as well. Do we want to try some workaround like:

```
# Selectively pass -mlong-calls when building for 32-bit ARM targets (armv6,
# armv7). This works around an issue where the text segment has gotten big
# enough (>32MB) that "relocation truncated to fit" errors occur.
ifeq ($(GOARCH),arm)
ifeq ($(GOOS),linux)
GO_ENV += CGO_CFLAGS="$(CGO_CFLAGS) -mlong-calls"
endif
endif
```

**Comment by palnabarun** [comment]
I am also thinking to do that. Digging into our toolchain right now.

**Comment by saschagrunert** [comment]
@palnabarun PTAL at https://github.com/kubernetes/kubernetes/pull/115613

**Comment by palnabarun** [comment]
that looks good. let's try that.

**Comment by saschagrunert** [comment]
Hm, looks like b0171f77f magically fixed the relocation problem. Ugh, that's odd and it feels that the issue can occur depending on how we change the source code. :roll_eyes:

**Comment by liggitt** [comment]
> Hm, looks like [b0171f7](https://github.com/kubernetes/kubernetes/commit/b0171f77f68427813efbb478c0ba89f48322d34a) magically fixed the relocation problem. Ugh, that's odd and it feels that the issue can occur depending on how we change the source code

yeah, that reminds me of https://github.com/kubernetes/kubernetes/issues/97685#issuecomment-756355216 where seemingly meaningless code changes fixed a compiler issue

do we have a smaller reproducer to give https://github.com/golang/go/issues/58425 to help with investigation?

**Comment by liggitt** [comment]
hoisting from https://github.com/kubernetes/kubernetes/pull/115613/files#r1101462558

do we have the full expanded `go test` invocation (including all the goflags / gogcflags / goasmflags / goldflags / tags) that was breaking? that would help in giving the go team a reproducer

**Comment by liggitt** [comment]
I'm unable to reproduce locally with the following

```
sudo apt-get install -y gcc-arm-linux-gnueabihf
git checkout b7ad17978eaba508c560f81bab2fb9d0b256e469
make all WHAT="test/e2e_node/e2e_node.test" KUBE_BUILD_PLATFORMS="linux/arm"
```

are we sure this is a go issue, or is it an issue with the in the changed ARM cross-compiler `export CC=${KUBE_LINUX_ARM_CC:-arm-linux-gnueabihf-gcc}` (since the cross-compile env changed versions around the same time as the go bump according to https://github.com/kubernetes/kubernetes/issues/115605#issuecomment-1422088512)

**Comment by saschagrunert** [comment]
Reproducer with a Dockerfile, on k/k b7ad17978ea:

```Dockerfile
FROM debian:latest

RUN apt-get update && \
    apt-get install -y \
        gcc-arm-linux-gnueabihf \
        wget

RUN wget https://go.dev/dl/go1.20.linux-amd64.tar.gz && \
    tar xf *.tar.gz && \
    mv go /usr/local

ENV PATH=$PATH:/usr/local/go/bin
ENV GOARCH=arm
ENV CGO_ENABLED=1
ENV CC=arm-linux-gnueabihf-gcc

COPY . /work
WORKDIR /work
RUN go test -o e2e_node.test k8s.io/kubernetes/test/e2e_node
```

It breaks with go 1.20 but works with go 1.19.5.

**Comment by MadhavJivrajani** [comment]
xref
Seems to be happening again: https://github.com/kubernetes/kubernetes/issues/115675
