### ISSUE TITLE
Ensure version "*" is passed instead of "" for all authz checks

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#115660]
SubjectAccessReview [expects "*"](https://github.com/kubernetes/api/blob/0478a3e95231398d8b380dc2a1905972be8ae1d5/authorization/v1/types.go#L106-L108) (not "") if the version is unspecified. We should audit all authz checks to ensure that "*" is being passed everywhere.

Example of where version is missing: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/approver/sarapprove.go#L64-L73

cc @liggitt

**Comment by liggitt** [comment]
when accepting a SubjectAccessReview API request and turning that into an authorization call, that's another place where it would likely make sense to fill in a `*` if the caller did not supply a version

**Comment by liangyuanpeng** [comment]
@liggitt 

Hi, Just for confirm that,  it is mean just fill version to `*` when the `in.version` is ` `? , Thank any help.

https://github.com/kubernetes/kubernetes/blob/d35da348c60a3c7505419741f2546ff8b0e38454/pkg/registry/authorization/util/helpers.go#L32

**Comment by liggitt** [comment]
> Hi, Just for confirm that, it is mean just fill version to `*` when the `in.version` is ` `? , Thank any help.

yes, as well as look for places where we are constructing `authorization.ResourceAttributes` with blank version fields like https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/certificates/approver/sarapprove.go#L64-L73 and change them to `*`
