### ISSUE TITLE
The PVC is created first, and then the VG is created. Why does the PVC take a long time to change from pending to bound?

### ISSUE THREAD

**Issue by jixiang8320216** [kubernetes/kubernetes#115696]
### What would you like to be added?

When I tested the local storage capabilities of the CSI  Plugin， The VG does not exist. Create a PVC in pending state，Creating a VG，It takes about 2 minutes for a PVC to change from the pending state to the bound state.  According to the node controller log of the local storage, it takes 1.2 minutes for the node controller to receive the VG creation event until the LVM Volume provisioned. No information is found about the apiserver, controller-manager, and scheduler. Therefore, What is the time-consuming logic dealing with in this process?
log：
![image](https://user-images.githubusercontent.com/11434161/218248838-4d9ac95f-e578-411b-ba72-e8e905788e90.png)

### Why is this needed?

The PVC is created first, and then the VG is created. Why does the PVC take a long time to change from pending to bound?

**Comment by jixiang8320216** [comment]
log：
![image](https://user-images.githubusercontent.com/11434161/218249627-5a9f3dcb-d237-44cf-82ad-8fe02ef4e45a.png)
![image](https://user-images.githubusercontent.com/11434161/218249643-54d9a058-1c91-462d-bbc7-ed975bc5367f.png)
![image](https://user-images.githubusercontent.com/11434161/218249655-2e01b7ca-afc0-49ab-bdf5-5986b08c7593.png)
![image](https://user-images.githubusercontent.com/11434161/218249662-da5298b8-4911-4118-b058-1b774d4394ca.png)

**Comment by sftim** [comment]
This looks like a request for help with storage and a CSI driver.
I don't see details about how to reproduce the scenario.


/remove-kind feature
/kind support
