### ISSUE TITLE
gRPC probe semantics prevent their usage for both readiness and liveness

### ISSUE THREAD

**Issue by thibault-da** [kubernetes/kubernetes#115651]
### What happened?

The [gRPC probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) currently in beta will mark the pod as live (resp. ready) only if the [grpc Health Service](https://github.com/grpc/grpc/blob/master/doc/health-checking.md) `Check` RPC returns `SERVING`.
This means that pointing both a liveness probe and a readiness probe at the same health service will result the pod in being restarted if it ever becomes temporarily "not ready" during its lifetime.

### What did you expect to happen?

I would expect the gRPC liveness probe to ignore the content of the response of the `Check` RPC, and consider the pod live as long as the RPC returns a gRPC `OK` status (even if the payload content is `NOT_SERVING`)

### How can we reproduce it (as minimally and precisely as possible)?

Add a liveness and a readiness gRPC probe pointing to the same health endpoint

### Kubernetes version

Any version above 1.24 supporting [gRPC probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe)

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by davidd-da** [comment]
It seems to me the current way gRPC probes are implemented, it is 100% meant for `readiness` and not really for `liveness`.

You could you reuse `grpc.health.v1.Health` and use the `service` parameter to modulate the reply on the server side, but it would be weird and not fit the [use case describe in the documentation](https://github.com/grpc/grpc/blob/master/doc/health-checking.md).

Seems at the moment it would require to have two endpoints/ports and `grpc.health.v1.Health` for `liveness` would always return `SERVING` to show the process is alive.

Note: I am working with @thibault-da

**Comment by SergeyKanzhelev** [comment]
I discussed it at gRPC meetup: https://www.youtube.com/watch?v=-ruuY5F-rE8

The feedback was that the `service` parameter should be used to differentiate liveness and readiness probes.

I think it would be great to update documentation.

/remove-kind bug
/kind documentation
/triage accepted

**Comment by SergeyKanzhelev** [comment]
KEP link: https://github.com/kubernetes/enhancements/issues/2727

**Comment by thibault-da** [comment]
Thanks @SergeyKanzhelev for the answer and pointer. I still do think it is a bit odd to use that parameter to differentiate between liveness and readiness, maybe it's just a naming issue but "liveness" hardly can be considered a "service".

As I mentioned IMO a better way would be for the liveness probe to only consider the gRPC return code (OK = live, anything else = not live). The same way the HTTP probe considers the HTTP code and does not care about the content.

The readiness probe could still do what it is doing now and consider the content of the response payload (`SERVING` == ready, anything else == not ready).

I get the point that the way it is now somehow lets you more easily "hint" to k8s to restart the pod by returning `NOT_SERVING` or something else for whatever service you configure for liveness, but I am not convinced this is a great idea. It's hard to get this right and not accidentally kill your pod for the wrong reasons. And at the same time if you are able to detect that your pod should be killed from within the app you can usually just kill your process directly.

Anyway I understand this is not going to change in the near future, just wanted to add my 2cts on the usability of the feature in case it gets revisited later :)

**Comment by andresvia** [comment]
odd
