### ISSUE TITLE
kubelet client cert is not getting auto-rotated (K8s 1.21)

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#115648]
### What happened?

Deployed Kubernetes on a single node setup (master+worker). The setup was UP, checked Kubelet + certs managed by Kubeadm has a validity of 1yr. Now, changed the date of the system to 30% of the cert's expiry date. 

Ran Kubeadm certs renew all, certs managed by Kubeadm got renewed from the day to the next year on the same date. 
but Kubelet client cert "/var/lib/kubelet/pki" is not auto-rotated still pointing to old certificate. 

Waited for 1day, still didn't get rotate. 

**As mentioned in the k8s official document**
As the expiration of the signed certificate approaches, the kubelet will automatically issue a new certificate signing request, using the Kubernetes API. This can happen at any point **between 30% and 10%**f the time remaining on the certificate. Again, the controller manager will automatically approve the certificate request and attach a signed certificate to the certificate signing request. The kubelet will retrieve the new signed certificate from the Kubernetes API and write that to disk. Then it will update the connections it has to the Kubernetes API to reconnect using the new certificate.

Also tried below setup to manually generate or rotate client certificate.

Call 'kubeadm init phase kubeconfig kubelet' optionally pass -config or other flags if needed. This will generate kubelet.conf with embedded cert and key.
Restart kubelet and wait for it to generate new certs in /var/lib/kubelet/pki
Call 'kubeadm init phase kubelet-finalize all'. This will 'symlink' the kebelet.conf to kubelet cert rotation.
Restart kubelet again.
https://github.com/kubernetes/kubernetes/issues/102556

new certs didn't get generate. 

### What did you expect to happen?

Kubelet certs should get auto-rotate. 

### How can we reproduce it (as minimally and precisely as possible)?

Deploy k8s, and change the date to 30% of the expiry date of the certificate. and wait for kubelet to auto-rotate the client certificate.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}


### Cloud provider

<details>

</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic


$ uname -a
Linux ubuntu18 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sairameshv** [comment]
@akshaysharama Do you observe any unusual behavior/errors in the kubelet logs related to the cert rotations?
If so, pasting the log snippets here helps !!

**Comment by sftim** [comment]
/retitle kubelet client cert is not getting auto-rotated (K8s 1.21)

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

The version you are running is not suported by kubernetes project. Can you try on 1.24+?

Also please include kubelet.log once you have a repro.

**Comment by neolit123** [comment]
/close
missing details for a version in the support window
