### ISSUE TITLE
FailedPostStartHook exited with 137: , message: ""

### ISSUE THREAD

**Issue by kakaNo1** [kubernetes/kubernetes#115680]
### What happened?

yaml:
```
lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - |
            cp -r conf/* ./
            mount -t cifs xxxxx
            mount -t cifs xxxxx
            mount -t cifs xxxxx
```
FailedPostStartHook  Exec lifecycle hook ([/bin/sh -c cp -r conf/* ./ mount -t cifs xxxxx mount -t cifs xxxxx mount -t cifs xxxx ]) for Container "base" in Pod "xxxxxv1cxularxor5changehive.6c92a7cc6af042bb9476312462538f5e_test(617f30ff-da04-42c3-9251-2ca26b918e4c)" failed - error: command '/bin/sh -c cp -r conf/* ./ mount -t cifs xxxx  mount -t cifs xxxx mount -t cifs xxxx ' exited with 137: , message: ""

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

Occasionally, 10 times of operation may fail once

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
openstack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support
1. maybe you use more memory than memory limit of the pod.
2. another possible reason is that the cp and mount timeout for gracefulTerminatedPeriod of the pod.

Just some guesses.

**Comment by kakaNo1** [comment]
hi @pacoxu,
    1,I tested that the required memory is 400M, but I added 4G memory for pod
    2,About timeout, because it happens randomly, I also doubt it, but in my test, these steps are very fast

**Comment by pacoxu** [comment]
1. oom logs can be found in kernel logs or events. If nothing is found, it should not be OOM-related.
2. For timeout, you may try to look into the debug-level kubelet log to see the timestamp of each step.

BTW, 1.20 is end-of-life for community support as well even if this is a bug(it seems to be not a bug according to current information).
/remove-kind bug
