### ISSUE TITLE
kubelet report the error, and cannot create kata pod

### ISSUE THREAD

**Issue by Gezx** [kubernetes/kubernetes#115793]
### What happened?

when I deploy k8s, it occurs the follow errors.
journalctl -xeu kubelet

Feb 15 18:20:29 master kubelet[613371]: Flag --logtostderr has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
Feb 15 18:20:29 master kubelet[613371]: Flag --log-dir has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/2845-deprecate-klog-specific-flags-in-k8s-components
Feb 15 18:20:29 master kubelet[613371]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Feb 15 18:20:29 master kubelet[613371]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Feb 15 18:20:29 master kubelet[613371]: Flag --runtime-request-timeout has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: Flag --feature-gates has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Feb 15 18:20:29 master kubelet[613371]: E0215 18:20:29.559249  613371 cri_stats_provider.go:452] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
Feb 15 18:20:29 master kubelet[613371]: E0215 18:20:29.560078  613371 kubelet.go:1317] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
Feb 15 18:20:29 master kubelet[613371]: E0215 18:20:29.698857  613371 container_manager_linux.go:927] "Unable to get rootfs data from cAdvisor interface" err="unable to find data in memory cache"
Feb 15 18:20:30 master kubelet[613371]: E0215 18:20:30.015028  613371 kubelet.go:2034] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Feb 15 18:20:30 master kubelet[613371]: E0215 18:20:30.141473  613371 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Feb 15 18:20:30 master kubelet[613371]: E0215 18:20:30.368236  613371 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Feb 15 18:20:30 master kubelet[613371]: E0215 18:20:30.798079  613371 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Feb 15 18:20:31 master kubelet[613371]: E0215 18:20:31.598258  613371 kubelet.go:2034] "Skipping pod synchronization" err="container runtime status check may not have completed yet"
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.054064  613371 remote_runtime.go:377] "ListPodSandbox with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\"" filter="&Pod>
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.054122  613371 kuberuntime_sandbox.go:297] "Failed to list pod sandboxes" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.054143  613371 kubelet_pods.go:1124] "Error listing containers" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.054171  613371 kubelet.go:2186] "Failed cleaning pods" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.684354  613371 remote_runtime.go:377] "ListPodSandbox with filter from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\"" filter="nil"
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.684407  613371 kuberuntime_sandbox.go:297] "Failed to list pod sandboxes" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
Feb 15 18:28:42 master kubelet[613371]: E0215 18:28:42.684432  613371 generic.go:205] "GenericPLEG: Unable to retrieve pods" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
~

### What did you expect to happen?

create kata pod

### How can we reproduce it (as minimally and precisely as possible)?

if anyone knows what can cause this condition?

### Kubernetes version

<details>

```console
$ kubectl version
# 1.25.3
```

</details>

### Cloud provider

<details>
1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tzneal** [comment]
Are you running a container runtime (e.g. containerd or CRI-O)? 

I haven't used Kata, but the docs at https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/run-kata-with-k8s.md , it doesn't supply a container runtime and needs either containerd or CRI-O.
