### ISSUE TITLE
dns lookup latency performance downgrade 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#115720]
### What happened?

https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=DNS&metricname=Load_DNSLookupLatency&Metric=DnsLookupLatency

### What did you expect to happen?

performance should not change to be worse.

### How can we reproduce it (as minimally and precisely as possible)?

See the board.
Before
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1601260708442411008/
```
{
  "version": "v1",
  "dataItems": [
    {
      "data": {
        "Perc50": 8.454643,
        "Perc90": 96.07345,
        "Perc99": 252.001007
      },
      "unit": "ms",
      "labels": {
        "Metric": "DnsLookupLatency"
      }
    }
  ]
}
```
After 
https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1601623232627085312/
both are using `registry.k8s.io/coredns/coredns:v1.9.3`
```
{
  "version": "v1",
  "dataItems": [
    {
      "data": {
        "Perc50": 221.257108,
        "Perc90": 488.908472,
        "Perc99": 1472.734184
      },
      "unit": "ms",
      "labels": {
        "Metric": "DnsLookupLatency"
      }
    }
  ]
}

```
### Anything else we need to know?

The change is in Dec 10th.
https://github.com/kubernetes/kubernetes/compare/536e5f0965b...b1d98bd7b34

https://github.com/kubernetes/kubernetes/pulls?q=merged%3A2022-12-09..2022-12-10+dns

- I only find https://github.com/kubernetes/kubernetes/pull/114172 is DNS related. /cc @thockin @aojea 
- sig network prs: https://github.com/kubernetes/kubernetes/pull/114155
- https://github.com/kubernetes/kubernetes/pull/114178
- maybe some other commits there and I cannot find some other related PR(Please check if #114172 is not related)

### Kubernetes version

latest
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

None

### OS version

None

### Install tools

None

### Container runtime (CRI) and version (if applicable)

None

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/pull/114279 was merged hours later.(I am not sure if this is related.)

-     version: 1.9.3
-     version: 1.10.0

**Comment by pacoxu** [comment]
https://perf-dash.k8s.io/#/?jobname=gce-5000Nodes&metriccategoryname=Network&metricname=Load_NetworkLatency&Metric=InClusterNetworkLatency

**Comment by aojea** [comment]
![image](https://user-images.githubusercontent.com/6450081/218442527-d4eadadb-1446-47b5-922d-a68ccfe936ec.png)

I wonder if was because of this https://github.com/kubernetes/kubernetes/pull/114229/files

**Comment by dlapcevic** [comment]
This is a huge regression for DNS lookup latency.

It seems strange that https://github.com/kubernetes/kubernetes/pull/114229 or https://github.com/kubernetes/kubernetes/pull/114181 would impact DNS lookup latency, since it greatly improved network programming latency.

The only thing that I can think of is that the CPU is the bottleneck now, since resyncing iptables is done so frequently.

The CPU increase in https://github.com/kubernetes/kubernetes/pull/114229#issuecomment-1346566684 https://user-images.githubusercontent.com/6450081/207064716-1dc8cab8-1c63-4773-a7a5-37a3221eae30.png is showing a significant increase on 100 node test, but this is 5k, so it might be the issue here.

**Comment by aojea** [comment]
ok, then let me revert https://github.com/kubernetes/kubernetes/pull/114229

**Comment by dlapcevic** [comment]
Thanks @aojea. I guess we should verify how iptables sync-rate affects CPU on 5k, and if that is the reason why increasing the frequency of iptables sync by a factor of 10 causes DNS lookups to be slower.

Are there some alerts or auto generated issues for regressions to DNS?
Apparently it was detected after 2 months.

**Comment by aojea** [comment]
> Are there some alerts or auto generated issues for regressions to DNS?

I don't think there automation in place, but you should ask wojktek or marceel or other sig-scalability members

**Comment by pacoxu** [comment]
#115723 fixed the problem. Should I close this issue? Or do you need to use this issue to track the `dns lookup` slower issue?

**Comment by aojea** [comment]
@danwinship @wojtek-t to summarize and conclude on the discussions of the 2 changes that merged at same time

https://github.com/kubernetes/kubernetes/issues/115720#issuecomment-1427759047

The change that reduced the network programming latency was the reduction of the sync period from 10s to 1s, the trade off is that increase the cpu usage impacting workloads latency

![image](https://user-images.githubusercontent.com/6450081/218683372-9c85fc1e-2757-467c-adb5-593ea7bc984a.png)


![image](https://user-images.githubusercontent.com/6450081/218683060-1c9fbd2a-3efe-41e7-a654-1574460f31d7.png)

Thanks @pacoxu for catching this

/close

**Comment by wojtek-t** [comment]
Thanks for taking care of it @aojea !
