### ISSUE TITLE
kube-controller-manager supports `--client-ca-file` parameter

### ISSUE THREAD

**Issue by kapad** [kubernetes/kubernetes#115725]
On the documentation page for [`kube-controller-manager`](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)

The following doesn't seem correct
```
--client-ca-file string

If set, any request presenting a client certificate signed by one of the authorities in the client-ca-file is authenticated with an identity corresponding to the CommonName of the client certificate.
```

Does the `kube-controller-manager` serve any endpoints? Does it perform any client authentication? 

The documentation seems to be the same as the same option for the `k8s-api-server`.

**Comment by liggitt** [comment]
controller manager serves health and metrics, which use the specified client CA bundle to authenticate presented client certificates in requests

the flag is valid
