### ISSUE TITLE
Promote gRPC probe tests to conformance

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#115780]
- Instructions: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/conformance-tests.md#promoting-tests-to-conformance
- Tests in `test/e2e/common/node/container_probe.go`:
  - should not be restarted with a GRPC liveness probe
  - should be restarted with a GRPC liveness probe

/sig node
/kind cleanup
/priority important-soon
/area tests
/help-wanted
/good-first-issue

KEP: https://github.com/kubernetes/enhancements/issues/2727

**Comment by lanycrost** [comment]
Hi, I want to take this
