### ISSUE TITLE
Kubelet does not try to register again if its Node object is deleted

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#115761]
How to repro:

1. Start kubelet
2. check that the node has been registered
```
kubectl get nodes test-worker
NAME          STATUS   ROLES    AGE   VERSION
test-worker   Ready    <none>   59m   v1.27.0
```
3. delete the node
```
kubectl delete nodes test-worker
node "test-worker" deleted
```

kubelet never recovers, is not able to register again, since it uses a bool that is set to true and never changes

https://github.com/kubernetes/kubernetes/blob/fa294f3e4e0006219d8c5ff39a0d3bc0e5ec6496/pkg/kubelet/kubelet_node_status.go#L51-L76

**Comment by tzneal** [comment]
I had always thought this was intended behavior for some reason, but couldn't find anything documenting why.  Related, 
Node lifecycle documentation https://github.com/kubernetes/kubernetes/issues/115139

**Comment by aojea** [comment]
no idea honestly, it just felt weird that you have to restart kubelet in this case, the lease keeps been renewed 

/cc @thockin

**Comment by tzneal** [comment]
> no idea honestly, it just felt weird that you have to restart kubelet in this case, the lease keeps been renewed

Yeah, I found that one being tracked at https://github.com/kubernetes/kubernetes/issues/109777

**Comment by tzneal** [comment]
This is a duplicate of https://github.com/kubernetes/kubernetes/issues/71398, there's more discussion there.
