### ISSUE TITLE
document use of insecure registry.

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#11578]
There is images documentation in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/images.md

Under the "Using a private registry" section, need to explain that to use an insecure private registry, you need to do certain steps, which are described in this thread: https://groups.google.com/forum/#!topic/google-containers/OZqtdGofHgo

**Comment by erictune** [comment]
xref #11579

**Comment by kargakis** [comment]
@samikhawaja if you want, please open a new issue in https://github.com/kubernetes/website
