### ISSUE TITLE
[Failing test] ci-kubernetes-e2e-gce-scale-performance.Pod

### ISSUE THREAD

**Issue by gracenng** [kubernetes/kubernetes#115792]
### Which jobs are failing?

master-informing
ci-kubernetes-e2e-gce-scale-performance.Pod

### Which tests are failing?

ci-kubernetes-e2e-gce-scale-performance.Pod
<img width="997" alt="image" src="https://user-images.githubusercontent.com/42276283/218947000-07688fd9-7ce0-4ef6-89e5-973252229077.png">

### Since when has it been failing?

02-14 09:03 PST

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

Job execution failed: Pod got deleted unexpectedly

### Relevant SIG(s)

/sig-scalability

**Comment by MadhavJivrajani** [comment]
Seems similar to https://github.com/kubernetes/kubernetes/issues/115767
I think another run should be triggered in ~5 hours from now (unless someone with access re-triggers it manually), I'm hoping things should be good there 🤞🏼

**Comment by Argh4k** [comment]
+1, the job runs at 5 PM GMT every day and takes around 3 hours, so we should see results around 8 PM GMT.

**Comment by lauralorenz** [comment]
The 5PM GMT run was green, and along with the fact that all the other jobs that were affected by the same issue resolved in their periodics re: #115767, I'm going to go ahead and close this one. Thanks @MadhavJivrajani and @Argh4k!

/close
