### ISSUE TITLE
Suppress console window for exec auth command on Windows (or expose a method for the caller to do so)

### ISSUE THREAD

**Issue by philomory** [kubernetes/kubernetes#115705]
If a GUI application is built for Windows which uses this library connect to Kubernetes clusters; and if the user of that application is connecting to a cluster for which authentication is handled via an exec plugin (for example, an EKS cluster); then every time the application needs to refresh its credentials, a console window flashes on screen for as long as it takes the exec plugin to return the credentials.

This behavior can be suppressed by setting setting some Windows-specific `sysProcAttr`s on the `cmd` struct, however, because the command execution is buried deep inside the library code, there's not currently any way for the calling application to do this.

One way to handle this would be to allow the calling application to supply `sysProcAttr` values to use with auth exec commands; alternatively, it might be appropriate to simply handle setting the necessary `sysProcAttr`s within the library itself, when running on Windows (I'm not sure if the current "briefly flash a console window on screen in certain circumstances on a specific platform" behavior is something that needs to be maintained under the aegis of "backwards compatibility"? It seems unlikely).

**Comment by enj** [comment]
xref:


https://github.com/vmware-archive/octant/issues/2143
https://github.com/vmware-archive/octant/pull/2701

**Comment by enj** [comment]
So I dug into this a while back.  IIUC, it is the plugin's responsibility to declare itself as a GUI vs. non GUI app (for Go it is the `-ldflags -H=windowsgui` flags).  We cannot automatically hide the window for all plugins because it is totally valid for the plugin to use a GUI.  Thus I believe the solution here is to re-compile your CLI only plugin as a GUI app so that it does not cause the command prompt to be drawn.

/close

**Comment by philomory** [comment]
> So I dug into this a while back.  IIUC, it is the plugin's responsibility to declare itself as a GUI vs. non GUI app (for Go it is the `-ldflags -H=windowsgui` flags).  We cannot automatically hide the window for all plugins because it is totally valid for the plugin to use a GUI.  Thus I believe the solution here is to re-compile your CLI only plugin as a GUI app so that it does not cause the command prompt to be drawn.
> 
> 
> 
> /close

So, to be clear... end users should recompile the AWS command line tooling as a GUI application? That's the solution?

**Comment by philomory** [comment]
`aws-iam-authenticator` is not used client-side any longer, the exec command for authenticating to an EKS cluster is just `aws eks get-token`. So they'd have to release a "GUI version" of the AWS command line tools.

Also, the suggestion I originally made was never to "automatically hide the window for all plugins"; indeed, an actual GUI plugin would specifically _not be affected_; the specific `sysProcAttrs` I'm describing only cause the operating system to not create a _console_ window displaying the output of a _non-GUI_ application; in other words, it would cause the library to behave on Windows in the same way it already behaves on Linux.
