### ISSUE TITLE
windows kube-proxy: "externalTrafficPolicy: Local" results in no clusterIP entry in windows node

### ISSUE THREAD

**Issue by shettyg** [kubernetes/kubernetes#115783]
I am tracking a changed behavior in networking with kubernetes 1.26. If I create a service of type externalTrafficPolicy: Local, and there are no local endpoints in a node, kube-proxy does not create hns loadbalancers for the clusterIP of that service. 

With kubernetes 1.25, it creates a loadbalancer for clusterIP (but not externalIP). 

This is the relevant log message:
```
"Skipped creating Hns LoadBalancer for cluster ip resources. Reason : all endpoints are terminating" clusterIP="10.114.142.98" nodeport=31336 allEndpointsTerminating=true 
```

Looks like this comes with a result from a new function isAllEndpointsTerminating introduced in kubernetes 1.26.

In Linux, we can still access clusterIP even if there are no local endpoints for the service. Thoughts?

The end result is that in Windows, clients cannot access the clusterIP of such a service with there are no local endpoints.

**Comment by jsturtevant** [comment]
@daschott

**Comment by daschott** [comment]
cc @sbangari @princepereira

**Comment by daschott** [comment]
@shettyg Does this issue occur when there are no local endpoints for a given service?

If there is a local endpoint, then you can reach the service again, right?

**Comment by princepereira** [comment]
@shettyg , Also let us know what is the InternalTrafficPolicy configured ?

**Comment by shettyg** [comment]
>@shettyg Does this issue occur when there are no local endpoints for a given service?

>If there is a local endpoint, then you can reach the service again, right?

That is correct @daschott 

>@shettyg , Also let us know, do you have any InternalTrafficPolicy configured ?

We do not have that configured @princepereira
