### ISSUE TITLE
(Question) Can Node Port Range be seperated by service??

### ISSUE THREAD

**Issue by kimkihoon0515** [kubernetes/kubernetes#115703]
Default range of node port is 30000 ~ 32767 and I just wonder if there's a way to seperate it by service types.
The main concept would be 

A service : 30000 ~ 30100
B service : 30101 ~ 30200
C service : 30201 ~ 30300

**Comment by aojea** [comment]
no, unfortunately the nodeport is a global option for the whole cluster

/close
