### ISSUE TITLE
Switch image in gRPC probe tests to agnhost

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#115781]
- Tests in `test/e2e/common/node/container_probe.go` are using `etcd` image for gRPC probe tests:
  - should not be restarted with a GRPC liveness probe
  - should be restarted with a GRPC liveness probe

We should use `agnhost` image for these tests as it is much smaller size.

/sig node
/kind cleanup
/priority important-soon
/area tests
/help-wanted
/good-first-issue

KEP: https://github.com/kubernetes/enhancements/issues/2727

**Comment by shogohida** [comment]
Hi @SergeyKanzhelev, can I work on this issue? I'm new to Kubernetes and want to contribute!

**Comment by shogohida** [comment]
Should I change `etcd` to `agnhost` in this file?

https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/node/container_probe.go

**Comment by SergeyKanzhelev** [comment]
> Should I change `etcd` to `agnhost` in this file?
> 
> https://github.com/kubernetes/kubernetes/blob/master/test/e2e/common/node/container_probe.go

Yes. Also pass proper parameters to agnhost to enable gRPC endpoint, change ports, and run tests to ensure that this worked.

**Comment by shogohida** [comment]
Thanks for your reply! Will let you know if I have more questions as I work
