### ISSUE TITLE
Remove the getAppArmorFS function

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#115741]
As mentioned https://github.com/kubernetes/kubernetes/pull/110601/files#r1004432225 the return value of `getAppArmorFS` is not being used any longer and the entire method can be removed.

The usage of `appArmorFS` was removed in https://github.com/kubernetes/kubernetes/pull/97966

Now there is no need to have the function `getAppArmorFS` and store it's result at all.

/sig node
/kind cleanup
/good-first-issue
/help-wanted

KEP xref: https://github.com/kubernetes/enhancements/issues/24

**Comment by Cool-Coder174** [comment]
I am having issues submitting the pull request. I removed that portion of the code under pkg/apparmor/Validate.go however this is my first time contributing and would like some help submitting this new updated version..
