### ISSUE TITLE
GKE - Multi cluster services stopped work after DNS zone was removed

### ISSUE THREAD

**Issue by jerckov** [kubernetes/kubernetes#115857]
### What happened?

[MCS](https://cloud.google.com/kubernetes-engine/docs/concepts/multi-cluster-services) mechanism to communicate multiple GKE clusters stopped work in all our clusters since 09.02.2023. We noticed that MCS service account (`service-PROJ_NUMBER@gcp-sa-mcsd.iam.gserviceaccount.com`)  deleted the private DNS zone in Cloud DNS `gke-multi-cluster-service-NUMBER` which was used by that mechanism to resolve cross cluster services domain names `SERVICE_EXPORT_NAME.NAMESPACE.svc.clusterset.local`

Currently communication between clusters works only through auto-generated service resources (`gke-mcs-ik7gi8ughg`)

### What did you expect to happen?

Should be possibility to resolve DNS names `SERVICE_EXPORT_NAME.NAMESPACE.svc.clusterset.local` in MCS mechanism

### How can we reproduce it (as minimally and precisely as possible)?

1. Create two GKE clusters in GCP: first and second
2. Enable MCS mechanism based on https://cloud.google.com/kubernetes-engine/docs/how-to/multi-cluster-services
3. Create in second cluster example `Service` (namespace: `default`)
4. Export `Service` from second cluster by creating `ServiceExport` resource
5. Try to connect to the `Service` from first cluster by `example.default.svc.clusterset.local`

### Kubernetes version

1.24.9-gke.1500

### Cloud provider

GCP

### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

MCS

**Comment by aojea** [comment]
This is a google cloud feature only and the community can not help you here.

Please contact your cloud-provider support with the details, they will help you with your issue

/close
