### ISSUE TITLE
kubelet: Evicted and force deleted pods get their full termination grace period when they should not

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#115819]
### What happened?

When pods are evicted, i.e. with a hard eviction, the grace period is intended to be `0s` (i.e. do not respect the pod's `terminationGracePeriodSeconds`). 

However, currently, evicted pods receive their full termination grace period seconds.

### What did you expect to happen?

The pod is evicted immediately and the termination grace period is not respected 

### How can we reproduce it (as minimally and precisely as possible)?

1. Deploy the following pod which has an ephemeral storage limit of 5Mi and uses `dd` to fill the disk

```
kind: Pod
apiVersion: v1
metadata:
  name: evictdiskpod
  labels:
    pod: evictdiskpod
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    resources:
      limits:
        ephemeral-storage: 5Mi
    command: ["/bin/sh", "-c"]
    args:
      - |
        _term() {
            echo "Caught SIGTERM signal!"
            while true; do sleep 5; done
        }
        trap _term SIGTERM
        sleep 10
        dd if=/dev/zero of=file bs=1M count=10
        echo 'write done'
        while true; do sleep 5; done
```

2. Observe the pod's terminationGracePeriodSeconds was respected when it should've not been

In the logs:

```
# I added a debug print to include grace period here (it is zero)
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688802     275 eviction_manager.go:583] "Evicting pod" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 message="Pod ephemeral local storage usage exceeds the total limit of containers 5Mi. " grace period=0


Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688838     275 pod_workers.go:649] "Pod is being evicted by the kubelet, begin teardown" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688937     275 pod_workers.go:906] "Processing pod event" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 updateType=1
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688965     275 pod_workers.go:1026] "Pod worker has observed request to terminate" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734

# syncTerminatingPod has a grace period of 60 (unexpected since it should've been overridden to zero)

Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.688980     275 kubelet.go:1859] "syncTerminatingPod enter" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689132     275 kubelet.go:1891] "Pod terminating with grace period" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689171     275 kuberuntime_container.go:707] "Killing container with a grace period override" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 containerName="busybox" containerID="containerd://71e017fbdc6de9cafc7aa136e2bb07c5d02891db21eacec0c6d358e46125ef1e" gracePeriod=60
Feb 16 02:13:01 kind-worker kubelet[275]: I0216 02:13:01.689193     275 kuberuntime_container.go:711] "Killing container with a grace period" pod="default/evictdiskpod" podUID=3257107a-73ff-455a-8286-74d350c6d734 containerName="busybox" containerID="containerd://71e017fbdc6de9cafc7aa136e2bb07c5d02891db21eacec0c6d358e46125ef1e" gracePeriod=60
```

Full kubelet logs: https://gist.github.com/bobbypage/7ef6335c5ee69ef8ba363d6edf5854e9

### Anything else we need to know?

1. When pod ephemeral storage eviction is reached  `evictPod` is called with a zero grace period

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/eviction/eviction_manager.go#L535

2. `evictPod` uses killPod and passes the zero grace period

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/eviction/eviction_manager.go#L584-L591

3. Eventually the grace period is set here in pod worker

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/pod_workers.go#L694-L700

4. `calculateEffectiveGracePeriod` is used to calculate the grace period. The `options.PodTerminationGracePeriodSecondsOverride` is set to zero (which originates from the eviction manager). This overrides the pod spec's grace period here (the comment mentions this case is for eviction manager):

https://github.com/kubernetes/kubernetes/blob/908803081fd4554d7cdb17cb77e5490c44ef7ab7/pkg/kubelet/pod_workers.go#L793-L800

5. But... the bug is that right after we check the grace period happened to be zero (`gracePeriod == 0`) and if it is we change it back pod spec's grace period, thus losing the `options.PodTerminationGracePeriodSecondsOverride`

https://github.com/kubernetes/kubernetes/blob/908803081fd4554d7cdb17cb77e5490c44ef7ab7/pkg/kubelet/pod_workers.go#L801-L805

and now the final grace period returned is the pod spec's grace period instead of the overriden grace period from the eviction manager. 

### Kubernetes version

Reproduced in 1.26.0

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by bobbypage** [comment]
We actually have the same issue for force deleted pods which we expect should not respect their termination grace period seconds, but they do currently.

For example:

```
kind: Pod
apiVersion: v1
metadata:
  name: term-pod-sleep
  labels:
    pod: term-pod-sleep
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    image: k8s.gcr.io/e2e-test-images/nginx:1.14-2
    command: ["/bin/sh", "-c"]
    args:
      - |
        _term() {
            echo "Caught SIGTERM signal!"
            while true; do sleep 5; done
        }
        trap _term SIGTERM
        while true; do sleep 5; done
```

```
$ kubectl apply -f ~/kube_workloads/term_pod_sleep.yaml
pod/term-pod-sleep created
```

```
$ kubectl delete pod term-pod-sleep --grace-period=0 --force
Warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
pod "term-pod-sleep" force deleted
```

But in the logs, the full grace period was given:

```
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.510842     271 kubelet.go:2215] "SyncLoop DELETE" source="api" pods="[default/term-pod-sleep]"
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.510888     271 pod_workers.go:639] "Pod is marked for graceful deletion, begin teardown" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.510933     271 pod_workers.go:902] "Processing pod event" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac updateType=1
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.510959     271 pod_workers.go:1019] "Pod worker has observed request to terminate" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.511007     271 kubelet.go:1858] "syncTerminatingPod enter" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.511025     271 kubelet_pods.go:1461] "Generating pod status" pod="default/term-pod-sleep"
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.511091     271 kubelet_pods.go:1471] "Got phase for pod" pod="default/term-pod-sleep" oldPhase=Running phase=Running
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.511206     271 kubelet.go:1888] "Pod terminating with grace period" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac gracePeriod=60
Feb 16 03:26:59 kind-worker kubelet[271]: I0216 03:26:59.511271     271 kuberuntime_container.go:705] "Killing container with a grace period override" pod="default/term-pod-sleep" podUID=e8b2bb66-0794-4761-817f-59d45dd98bac containerName="busybox" containerID="containerd://61bafd7e7e4ecf7f63d1f9b67dfaff151e5221a0e3f936231408215b8cc8aa64" gracePeriod=60
```

Full pods logs - https://gist.github.com/bobbypage/eabc969887095b4a1404eebc430c36c3

**Comment by aojea** [comment]
/cc

nice catch

**Comment by smarterclayton** [comment]
We definitely need to clarify the intended behavior of the various overrides.  I think it should be:

| Scenario | Expected grace period | Runs hooks | Comments |
| --- | --- | --- | --- |
| User deletes in API with delete grace period 1 | minimum | Y | |
| User deletes in API with pod grace period 1 | minimum | Y | |
| Pod is force deleted from API and kubelet observes delete grace period 1 | minimum | Y | We should verify we have a test in API that ensures the intermediate write happens (pretty sure we do) |
| Pod is force deleted from API and kubelet does not observe the immediate write | minimum | Y | |
| Kubelet evicts a pod | minimum | Y | |
| User updates a static pod with a fixed UID | pod | Y | |
| User deletes and then recreates a static pod with a fixed UID | pod | Y | |
| User updates a static pod with a dynamic UID | pod | Y | |
| Kubelet detects a soft admission exclusion for an already running pod | minimum | Y? | |
| Kubelet detects an orphaned runtime pod | minimum | N | We don't know the orphaned pod's spec |

We need to decide how best-effort hooks are. My position would likely be:

> Most hooks and most SIGTERM should exit << 1s (which is our described minimum), and the pod author is the one who designs the hook, so they are responsible for fitting within the shutdown window. So if a pod author writes a slow shutdown hook that is intentional and within their control, so we want the hook to get the bulk of the shutdown window. However, given that termination is granular to the second, the minimum duration for hooks is 1s and the minimum duration for kill is 1. Hooks are best effort, and under the presence of errors we do not guarantee that
a pre-stop hook is executed before the pod is killed, we only guarantee that we make an attempt at least once to
run a hook.

### Minimum with hooks

1. Hook is invoked with 1s minimum shutdown time, at 1s we cancel the invocation
2. Terminate containers is invoked with 1s minimum shutdown time in parallel per container (TERM, 1s, KILL)

If we encounter an error during invocation of a hook under minimum shutdown conditions, we should move immediately to terminating the containers

### Minimum without hooks

1. Terminate containers is invoked with 1s minimum shutdown time in parallel per container

**Comment by rphillips** [comment]
Node Drains also evicts pods via the API. API based Evictions should probably honor the graceful termination. @smarterclayton could you add this scenario to the matrix?

**Comment by smarterclayton** [comment]
An API based eviction is a delete of a pod in either of the first two scenarios, I'll add a comment.  An API based eviction isn't a "node eviction", so I'll also clarify that terminology.

**Comment by tuibeovince** [comment]
out of curiosity, can anyone tell what was the intention of this comment in L699
https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/pod_workers.go#L694-L700
saying that the grace period `will never be zero`

is this by design that it is never expected to be zero? should the specification be updated so that the grace-period argument does not take `0` ?

**Comment by tuibeovince** [comment]
To further support my above inquiry, it appears that gracePeriod is never expected to be `0` because anything less than `1` is set to `1`.

https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/pod_workers.go#L807-L810

Which raises the question of the need for allowing `0` to be an acceptable user-specifiable gracePeriod value. Since "immediate" is considered to be equivalent to to `gracePeriod` being `1`.

**Comment by zcahana** [comment]
> Hooks are best effort, and under the presence of errors we do not guarantee that
a pre-stop hook is executed before the pod is killed, we only guarantee that we make an attempt at least once to
run a hook.

Anecdotally, the pre-stop hook for force delete pods (and possibly, evicted pods) is being executed only as of #115835, which debuted in K8s 1.28.

Prior to that (e.g., in 1.27), the `gracePeriod` variable was being set to `0` by `setTerminationGracePeriod` (because `pod.DeletionGracePeriodSeconds` is 0 on force deletion), and thus the condition for executing the pre-stop hook isn't fullfiled:
https://github.com/kubernetes/kubernetes/blob/1b4df30b3cdfeaba6024e81e559a6cd09a089d65/pkg/kubelet/kuberuntime/kuberuntime_container.go#L721-L731

As of #115835 (e.g., in 1.28), `gracePeriod` is overridden and hence `!= 0`, so pre-stop does execute. 
https://github.com/kubernetes/kubernetes/blob/855e7c48de7388eb330da0f8d9d2394ee818fb8d/pkg/kubelet/kuberuntime/kuberuntime_container.go#L722-L738

Note though, that now the full `terminationGracePeriodSeconds` is applied to the hook execution, even upon force deletion.

**Comment by HirazawaUi** [comment]
> Note though, that now the full `terminationGracePeriodSeconds` is applied to the hook execution, even upon force deletion.

I think this is what #120451 is trying to address.

**Comment by iholder101** [comment]
> To further support my above inquiry, it appears that gracePeriod is never expected to be `0` because anything less than `1` is set to `1`.
> 
> https://github.com/kubernetes/kubernetes/blob/a25834cb5a16bbd6a9295aeb5d1621aa8a4cd407/pkg/kubelet/pod_workers.go#L807-L810
> 
> Which raises the question of the need for allowing `0` to be an acceptable user-specifiable gracePeriod value. Since "immediate" is considered to be equivalent to to `gracePeriod` being `1`.

I'm also interested in understanding the reason for not allowing 0 grace period. This is mentioned again [here](https://github.com/kubernetes/kubernetes/pull/120451#discussion_r1439851789).

Intuitively, I would have thought that we would send 0 grace period to the CRI which would know how to handle it.

**Comment by kwilczynski** [comment]
Related:

- https://github.com/kubernetes/kubernetes/issues/120449
