### ISSUE TITLE
Running update-codegen FAILED

### ISSUE THREAD

**Issue by buaa-learner** [kubernetes/kubernetes#115820]
### Which jobs are failing?

Running update-codegen
go version go1.20 linux/amd64
go: downloading github.com/spf13/pflag v1.0.5
go: downloading k8s.io/klog/v2 v2.80.1
go: downloading k8s.io/gengo v0.0.0-20220902162205-c0856e24416d
go: downloading k8s.io/kube-openapi v0.0.0-20230123231816-1cb3ae25d79a
cmd/defaulter-gen/main.go:47:2: github.com/spf13/pflag@v1.0.5: Get "https://proxy.golang.org/github.com/spf13/pflag/@v/v1.0.5.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/defaulter-gen/args/args.go:23:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/defaulter-gen/args/args.go:24:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/defaulter-gen/main.go:49:2: k8s.io/klog/v2@v2.80.1: Get "https://proxy.golang.org/k8s.io/klog/v2/@v/v2.80.1.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/conversion-gen/generators/conversion.go:29:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/conversion-gen/generators/conversion.go:30:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/conversion-gen/generators/conversion.go:31:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/deepcopy-gen/args/args.go:24:2: k8s.io/gengo@v0.0.0-20220902162205-c0856e24416d: Get "https://proxy.golang.org/k8s.io/gengo/@v/v0.0.0-20220902162205-c0856e24416d.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/openapi-gen/main.go:27:2: k8s.io/kube-openapi@v0.0.0-20230123231816-1cb3ae25d79a: Get "https://proxy.golang.org/k8s.io/kube-openapi/@v/v0.0.0-20230123231816-1cb3ae25d79a.zip": dial tcp 172.217.160.81:443: i/o timeout
cmd/openapi-gen/main.go:28:2: k8s.io/kube-openapi@v0.0.0-20230123231816-1cb3ae25d79a: Get "https://proxy.golang.org/k8s.io/kube-openapi/@v/v0.0.0-20230123231816-1cb3ae25d79a.zip": dial tcp 172.217.160.81:443: i/o timeout
!!! [0216 13:35:11] Call tree:
!!! [0216 13:35:11]  1: /home/jiacheng/kubernetes/hack/update-codegen.sh:1008 codegen::subprojects(...)
Running update-codegen FAILED
make: *** [Makefile:158: update] Error 1

### Which tests are failing?

make update

### Since when has it been failing?

02-16-2023

### Relevant SIG(s)

/sig

**Comment by aojea** [comment]
> et "[https://proxy.golang.org/](https://proxy.golang.org/github.com/spf13/pflag/@v/v1.0.5.zip)

you have problems connecting to `https://proxy.golang.org`, you can disable it or using another one with the `GOPROXY` enviroment variable

**Comment by buaa-learner** [comment]
> 
thanks
