### ISSUE TITLE
Having successfully deleted the pods  using kubectl command in the k8s cluster,  the containers of containerd are still in the Running status, leading to the netns and the ip resources of them cannot be released

### ISSUE THREAD

**Issue by Duanzhiwei** [kubernetes/kubernetes#115822]
### What happened?

Having successfully deleted the pods  using kubectl command in the k8s cluster(1.24.3),  the containers of containerd(1.6.9) are still in the Running status, leading to the netns and the ip resources of them cannot be released

![微信图片_20230216152532](https://user-images.githubusercontent.com/28282292/219296737-805295d0-783a-448c-af9f-4e658158ef9f.jpg)

![微信图片_20230216152605](https://user-images.githubusercontent.com/28282292/219296835-fd7189a9-dace-454e-9136-34e6f31acf65.jpg)

![微信图片_20230216152610](https://user-images.githubusercontent.com/28282292/219296865-91055140-bda9-478a-82f5-c8ae94147fe9.jpg)

### What did you expect to happen?

The container is released normally, and the netns and IP are also released normally

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster of version  1.24.3
choose containerd CRI plugin
choose macvlan CNI plugin
Create a workload(deployment)
kubectl delete pods
kubectl get pod 
ssh $node
crictl ps 

### Kubernetes version

<details>

```console
$ kubectl version
# 1.24.3
```

</details>

### Cloud provider

<details>
Bare metal cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NANE="Kylin Linux Advanced Server"
VERSION="V10 (Sword)"
ID="kylin"
VERSION_ID="V10"
ANSI_COLOR="0;31"
$ uname -a
4.19.90-24.4v2101.ky10.aarch64

```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.6.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
macvlan
</details>

**Comment by tzneal** [comment]
Do you have logs from kubelet and containerd you can attach?

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

Can you please provide kubelet and containerd logs?

**Comment by harche** [comment]
@Duanzhiwei is there a chance you ran into this issue while testing using static pods?
