### ISSUE TITLE
[Failing Test] periodic-conformance-main-k8s-main

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#115894]
### Which jobs are failing?

periodic-conformance-main-k8s-main

### Which tests are failing?

capa-e2e-conformance: [SynchronizedBeforeSuite]

### Since when has it been failing?

since 2/18 09:25 PST

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-informing#periodic-conformance-main-k8s-main

### Reason for failure (if possible)

First run:
```
{Timed out after 300.000s.
Expected
    <bool>: false
to be true failed [FAILED] Timed out after 300.000s.
Expected
    <bool>: false
to be true
In [SynchronizedBeforeSuite] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/shared/aws.go:521 @ 02/19/23 17:34:03.716
}
```
Every next run:
```
{�[1m�[38;5;9mSynchronizedBeforeSuite failed on Ginkgo parallel process #1�[0m
  The first SynchronizedBeforeSuite function running on Ginkgo parallel process
  #1 failed.  This suite will now abort.

 failed [FAILED] �[1m�[38;5;9mSynchronizedBeforeSuite failed on Ginkgo parallel process #1�[0m
  The first SynchronizedBeforeSuite function running on Ginkgo parallel process
  #1 failed.  This suite will now abort.

In [SynchronizedBeforeSuite] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-aws/test/e2e/suites/conformance/conformance_suite_test.go:45 @ 02/19/23 17:34:03.733
}
```

### Anything else we need to know?

Has been consistently failing this weekend, but there was a failure on 2/17 09:23 PST and 2/14 21:22 PST, with green builds following. This could turn into a flake

### Relevant SIG(s)

/sig-testing

**Comment by aojea** [comment]
/remove-sig testing

cluster API jobs are owned by the corresponding projects

https://github.com/kubernetes-sigs/cluster-api-provider-aws

@dims do you know to whom we can redirect this?

**Comment by lauralorenz** [comment]
We have 3 green runs since 9:23 PST 2/21.

In `SynchronizedBeforeSuite`, I also see errors like

```
err=AccessDeniedException: User: arn:aws:iam::705628986737:user/capa-account-2020-02-18-f is not authorized to perform: eks:ListClusters on resource: arn:aws:eks:us-west-2:705628986737:cluster/*
```
as late as the 2/19 run,
then,
```
failed to read "cert-manager.yaml" from provider's repository "cert-manager": failed to get GitHub release v1.11.0: rate limit for github api has been reached. Please wait one hour or get a personal API token and assign it to the GITHUB_TOKEN environment variable
```
then a failure due to a cleanup timeout, before we get back to green.

From this I am speculating that there was some IAM hiccup that is now resolved. I'm moving this to a flake and will close if it stays green.
/remove-kind failing-test
/kind flake

/sig cluster-lifecycle
cc CAPA maintainers @richardcase @Skarlso @Ankitasw @dlipovetsky

**Comment by richardcase** [comment]
We had an issue with one of the AWS accounts that are used for the e2e tests, related to an orphaned role that caused the tests to fail if boskos handed us that account.

This appears to be resolved now.

**Comment by lauralorenz** [comment]
Thank you @richardcase! Since that seems the likely culprit and we are still green, I'll go ahead and close this now.

/close
