### ISSUE TITLE
Kube-proxy does not validate `healthz` state when answering to HC for eTP:Local

### ISSUE THREAD

**Issue by alexanderConstantinescu** [kubernetes/kubernetes#115825]
### What happened?

KEP https://github.com/kubernetes/enhancements/pull/3837 outlined the fact that Kube-proxy today doesn't perform any validation of its `healthz` state when answering to load balancer HCs for eTP:Local services.

This is a potential problem, because if Kube-proxy is unhealthy then it might also not be writing the rules needed to forward traffic to the endpoint on the node. This means that it might indicate to a load balancer that it should forward traffic to the node, simply because the endpoint is scheduled there

### What did you expect to happen?

Kube-proxy should perform the same validation it currently does for eTP:Local services (i.e: validate that the service has an endpoint scheduled and ready on the node) but AND it with its `healthz` state. 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a service of `type: LoadBalancer` + `externalTrafficPolicy: Local`
2. Trigger an issue with Kube-proxy which causes it to fail when writing its rules on the node 
3. Spin up a pod for this service
4. Validate that Kube-proxy continues to indicate to the load balancer that it should send the node traffic, even though it hasn't been able to write the rules required as a consequence of 3. due to 2. 

### Kubernetes version

<details>
all 
</details>

### Cloud provider

<details>
all 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by thockin** [comment]
I've lost track - @alexanderConstantinescu was this covered by on eof your KEPs?  :)

**Comment by aojea** [comment]
> I've lost track - @alexanderConstantinescu was this covered by on eof your KEPs? :)

It says fixed by https://github.com/kubernetes/kubernetes/pull/111661

> Fixes #https://github.com/kubernetes/kubernetes/issues/115825
