### ISSUE TITLE
Sidecar containers implementation steps: uber issue

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#115934]
KEP: https://github.com/kubernetes/enhancements/issues/753

This issue is to discuss and approve the implementation plan to minimize the amount of rebase needed. Issue was discussed at [working group meeting](https://docs.google.com/document/d/1E1guvFJ5KBQIGcjCrQqFywU9_cBQHRtHvjuqcVbCXvU/edit#bookmark=id.x7ms8ybmhtfv).

We plan to split work into three stages:

1. "Before the API change": refactoring needed before implementation - changes that do not change functionality and can be accepted independently from sidecar KEP work. This work will simplify the "the big PR".
2. "With the API change": single PR containing the MVP of sidecar container ("the big PR").
3. "After the API change": changes we propose to postpone to after the "the big PR" will merge.

The goal is to pre-approve what would be OK to implement after "the big PR" will merge.

## Before the API change

- [X] API discussion: fork InitContainers or not: https://github.com/kubernetes/kubernetes/issues/115362
- [X] Pod resources calculation centralization: https://github.com/kubernetes/kubernetes/pull/115367 
- [X] Add total resource used in Pod Status https://github.com/kubernetes/kubernetes/pull/115643
- [x] CI test job for sidecar containers e2e tests - definition in test-infra
- [x] E2e tests: https://github.com/kubernetes/kubernetes/pull/115984, https://github.com/kubernetes/kubernetes/pull/116426/files#r1131345210

## With the API change - single PR

PR: https://github.com/kubernetes/kubernetes/pull/116429
Branch for updates: https://github.com/SergeyKanzhelev/kubernetes/tree/sidecar

- [X] API change - add restartPolicy to Init containers
- [X] API validation - only allow restartPolicy for Init containers 
- [X] Startup: wait for Started, not for completion. Note, this will not allow to implement any initialization logic for sidecar containers. We propose to postpone the lifecycle hooks and probes as a separate steps.
- [X] Reconciling status of Sidecar container with the runtime
- [X] Termination: Pod is terminated even if sidecar is still running
- [x] Resources calculation update
- [x] Restart sidecar on sidecar failure/completion while pod is still running

## After the API change

- [x] Enable probes for sidecar containers https://github.com/kubernetes/kubernetes/pull/119168 & https://github.com/kubernetes/kubernetes/pull/116429
- [x] Enable lifecycle hooks for sidecar containers **same as above**
- [ ] add total resources requested to podstatus https://github.com/kubernetes/kubernetes/pull/115643
- [x] Pod ready state calculation should include sidecar containers TBD: may need a test for it.
- [ ] OOM score adjustment update with tests TBD
- [ ] Topology/CPU managers update TBD
- [ ] Documentation https://github.com/kubernetes/website/pull/41802
- [ ] Blog post before release TBD
- [x] https://github.com/kubernetes/kubernetes/issues/120163

## Further refactoring

- [ ] Initialize "Started" for Init Containers when they have started: https://github.com/kubernetes/kubernetes/issues/115553, https://github.com/kubernetes/kubernetes/issues/115937

@derekwaynecarr @mrunalp @thockin will you be OK with this split of work?

**Comment by gjkim42** [comment]
cc

**Comment by tzneal** [comment]
I think https://github.com/kubernetes/kubernetes/pull/115643 can go in the "Before the API change" section. It's an API change, but separate and independent from the main API change to containers.

**Comment by thockin** [comment]
This sounds plausible to me.

When I, personally, work on an effort of this magnitude, I know that my ability to guess which parts go into which "stage" is low.  I would do those "prefactoring" things you *know* you need, but move quickly into the process of building the feature (second stage), which will inevitably uncover more things you can do to prefactor, or even just peel off independently useful changes which can be reviewed and merged in isolation.  Eventually, you will have that "API change" PR and you'll realize that not much more can be stripped out of it. 

But you won't know when you're done until you start.

So yes, do the obvious "before" parts, but also - start the "during" work ASAP.  Focus on an end-to-end working example - don't make it clean.  Don't write good tests.  Hack.  Add commits for each small step.  Make it work, and keep a "TODO" list of everything you find along the way.  Once you have a demo-able "Look!  It works!" branch, THEN go back and peel things out, send PRs, and rebase the "big branch".  The commits have to accumulate before they can decrease.

**Comment by SergeyKanzhelev** [comment]
> I would do those "prefactoring" things you _know_ you need, but move quickly into the process of building the feature (second stage), which will inevitably uncover more things you can do to prefactor, or even just peel off independently useful changes which can be reviewed and merged in isolation.

this is how it goes now =). More things to prefactor being found

**Comment by adisky** [comment]
cc

**Comment by gjkim42** [comment]
we can close this now as the feature has graduated to beta.

/close
