### ISSUE TITLE
Trace messages from API Server with log verbosity of 0

### ISSUE THREAD

**Issue by george-angel** [kubernetes/kubernetes#115993]
### What happened?

Getting log messages like:

```
kube-apiserver-master-k8s-mczx.c.uw-dev.internal kube-apiserver Trace[2027316592]: ---"About to Encode" 521ms (05:35:39.110)
kube-apiserver-master-k8s-mczx.c.uw-dev.internal kube-apiserver Trace[2027316592]: [535.208261ms] [535.208261ms] END
kube-apiserver-master-k8s-mczx.c.uw-dev.internal kube-apiserver I0223 05:35:39.126843       1 trace.go:205] Trace[149606841]: "Update" url:/apis/kyverno.io/v1/clusterpolicies/disallow-host-ipc-pods,user-agent:kyverno/v0.0.0 (linux/amd64) kubernetes/$Format,audit-id:d53b812e-03a6-4bfa-bc71-4d9f550c0289,client:10.22.20.46,accept:application/json, */*,protocol:HTTP/2.0 (23-Feb-2023 05:35:38.587) (total time: 538ms):
kube-apiserver-master-k8s-mczx.c.uw-dev.internal kube-apiserver Trace[149606841]: ---"Write to database call finished" len:3885,err:<nil> 536ms (05:35:39.125)
kube-apiserver-master-k8s-mczx.c.uw-dev.internal kube-apiserver Trace[149606841]: [538.994261ms] [538.994261ms] END
```

When the API Server is running with `--v=0`

### What did you expect to happen?

Log only "critical events", as stated by: https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-verbosity-level

### How can we reproduce it (as minimally and precisely as possible)?

Running Kubernetes v1.25.5
Kyverno: v1.8.4

Nothing special about our setup that would trigger this afaik.

### Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

GCP, self-managed control-plane.

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3374.2.3
VERSION_ID=3374.2.3
BUILD_ID=2023-01-20-1751
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3374.2.3 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3374.2.3:*:*:*:*:*:*:*"

$ uname -a
Linux master-k8s-6r59.c.uw-dev.internal 5.15.86-flatcar #1 SMP Fri Jan 20 17:26:55 -00 2023 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by logicalhan** [comment]
These are pretty critical, these trace logs are latency based, so they only trigger when you have really slow requests which signal that something is going wrong.

**Comment by dgrisonnet** [comment]
I'd like to revive this discussion since I ran into that recently and can't really understand why we skip log levels here.

> These are pretty critical, these trace logs are latency based, so they only trigger when you have really slow requests which signal that something is going wrong.

@logicalhan slowness can for sure indicate that something is going wrong, but this is a debug information at best. I don't really understand why it is critical to the point that it skips all log levels. In most cases this will be noisy with v=0 and hide all the critical information that are present in the logs with that level set.

If we go according to our [logging conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md#what-method-to-use), it should be level 5 or higher, but I could see them useful at the level 4 since they are key debugging information in case of slowness.

**Comment by dgrisonnet** [comment]
FWIW, there was an effort long ago to move all nested traces to level 4 and higher (https://github.com/kubernetes/utils/pull/177) and I think we should generalize that to all the steps that are above threshold.

**Comment by rossigee** [comment]
Still an issue with lastest 1.28 releases. ([Slack thread](https://kubernetes.slack.com/archives/C2P1JHS2E/p1701132279167519))

Is there any kind of expected 'next action' for fixing this?

**Comment by sttts** [comment]
>  and I think we should generalize that to all the steps that are above threshold.

I have seen many cases where these messages in `--v=2` mode led to diagnosis of problems. I consider these trace message (above the threshold) as warnings of something wrong. In other words: I would not be happy to move them above `--v=2`, but would be totally on-board to disable the output below.

**Comment by dgrisonnet** [comment]
Log level 2 sounds fine by me :+1:
