### ISSUE TITLE
Topology spread constraint not respected when pods scale down

### ISSUE THREAD

**Issue by stmiller14** [kubernetes/kubernetes#115911]
There is a known limitation in this feature that when pods scale down there topology spread may not be even. How does one overcome this limitation to keep there pods spread across multiple availability zones. This can be a huge issue for apps that need to be highly available.

As per documentation:

“There’s no guarantee that the constraints remain satisfied when Pods are removed. For example, scaling down a Deployment may result in imbalanced Pods distribution. You can use Descheduler to rebalance the Pods distribution.”

**Comment by tzneal** [comment]
One option is to use the `RemovePodsViolatingTopologySpreadConstraint` feature of https://github.com/kubernetes-sigs/descheduler

/sig scheduling

**Comment by stmiller14** [comment]
Im not sure if RemovePodsViolatingTopologySpreadConstraint  would help in this scenario.
In a 3 AZ environment with a max skew of 1, ideally it would scale down from 10 pods to 3 (min required) pods with one pod being in each AZ. However I have seen 2-1-0 occasionally which defeats the purpose of the extra AZ. How would RemovePodsViolatingTopologySpreadConstraint help in that case? Would that configuration remove the AZ that has 2 pods and move it to the AZ with 0 pods?

**Comment by tzneal** [comment]
It should, though I haven't tested it.  In that case the there are pods violating the topology spread constraint (max domain has two pods, min domain has zero pods, so the skew is two). For AZ spread, you may also be interested in looking at minDomains which is a beta field in 1.25.

**Comment by stmiller14** [comment]
Ok thanks for the feedback. 
I still feel and Im sure others also that constraints should held regardless of descheduling, scheduling, or deployments. Is this something that can be included in a future version? It would save most users a lot of time to not have to create custom configurations. If one takes the time to create a topology constraint you would assume its respected throughout the lifecycle

**Comment by sftim** [comment]
(Not sure if this counts as a duplicate)

**Comment by damemi** [comment]
Just confirming what @tzneal said, descheduler is meant to be run post scale-down as a rebalancer in this case. It will find that there are 2 zones which are out-of-skew and evict the minimum number of pods that will bring the zones back into skew, assuming the default scheduler.

Otherwise, I think this is a duplicate of #4301 and https://github.com/kubernetes/kubernetes/issues/96748

**Comment by stmiller14** [comment]
After evicting the pod will a new pod be created in the AZ missing a pod? Or will it be left with 1-1-0

**Comment by tzneal** [comment]
If it's a pod controlled by a controller, yes.  E.g. If it's a pod from a deployment, the pod would be evicted, a new pod would be created, and kube-scheduler would then schedule it per the topology spread constraints.

**Comment by damemi** [comment]
@stmiller14 creation and scheduling of a new pod is separate from the descheduler, but the descheduler will effectively trigger a new pod to be created and scheduled in the new zone by evicting one of your replicas.

**Comment by kerthcet** [comment]
/remove-lifecycle stale
I think this is still valid however kube-scheduler can do nothing today.

**Comment by frankh** [comment]
imo this is a very important feature to have

one common use-case is in e.g. AWS requiring at least 1 pod in each AZ at any one time if your load balancer has cross-AZ balancing off (common to reduce cross-AZ traffic costs)

Even if you have maxSkew across zones of 1 and minDomains set to 3 (or however many AZs you use), with min replicas set to 10 you can _still_ end up in situations with empty AZs causing outages

e.g. You have 100 replicas, they get downscaled to 10, there is a relatively high chance if the pods are chosen randomly that one AZ ends up empty, meaning 1/3rd of requests to the ALB fail.

Even with descheduler running to re-balance things it could cause several minutes of downtime.

The only current workarounds are to have an overly conservative combination of something like:
1. minReplicas of _at least_ 6
2. scale down policy must only allow 1 pod at a time to downscale (or <16%)
```  
scaleDown:
    policies:
    - type: Pods
      value: 1
      periodSeconds: 120
```
3. descheduler must run at least once a minute
4. maxSkew must be 1

**Comment by grosser** [comment]
FYI a workaround we are currently using is to set controller.kubernetes.io/pod-deletion-cost annotation to 1,1,1,2,2,2,3,3,3 (for azs a,b,c) so a single row of pods is deleted and constraint stays fulfilled

**Comment by shysank** [comment]
> FYI a workaround we are currently using is to set controller.kubernetes.io/pod-deletion-cost annotation to 1,1,1,2,2,2,3,3,3 (for azs a,b,c) so a single row of pods is deleted and constraint stays fulfilled

@grosser Won't all pods in AZ "a" be deleted because all of them will have the lowest cost of "1". Or do you mean the 1st pod in  all azs will have cost "1", 2nd "2" so on.
