### ISSUE TITLE
kube-proxy IPVS mode: traffic sent from pods to an external LoadBalancer IP is NOT directed to the respective cluster IP instead

### ISSUE THREAD

**Issue by amorozkin** [kubernetes/kubernetes#115931]
### What happened?

According to the [docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/#:~:text=will%20be%20masqueraded%20and-,traffic%20sent%20from%20pods%20to%20an%20external%20LoadBalancer%20IP%20will%20be%20directed%20to%20the%20respective%20cluster%20IP%20instead.,-For%20dual)  

> traffic sent from pods to an external LoadBalancer IP will be directed to the respective cluster IP instead

But in fact it's not the case for kube-proxy running in IPVS mode.

### What did you expect to happen?

This is kind of "breaking change" that IPVS mode brings - **pods running on the nodes, where there are no pods which Loadbalancer IP's related service points to, are capable to access that service by External IP (e.g. Ingresses that are resolved in DNS to LoadBalancer IP)**:
1. only if `ExternalTrafficPolicy` for related service is set to `Cluster`
2. only via SrcNAT loosing their IPs in logs

There are no such limitaions with kube-proxy in `iptables` mode which provide redirection to ClusterIP mentioned above via iptables rules with comments like _"Redirect pods trying to reach external loadbalancer VIP to clusterIP"_

### How can we reproduce it (as minimally and precisely as possible)?

Any installation with kube-proxy in IPVS mode

### Kubernetes version

1.23.4

### Cloud provider

Selfhosted

### OS version

<details>
Ubuntu 20.04.4 LTS
</details>

### Install tools

<details>
Kubespray
</details>

### Container runtime (CRI) and version (if applicable)

 <details>
 containerd://1.6.4
 </details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico CNI
</details>

**Comment by sftim** [comment]
Hmm. If someone makes their own proxier (KPNG, etc), do we expect them to do that interception of traffic or is it optional? Either way, we ought to document what is or isn't expected of the cluster network.

**Comment by uablrek** [comment]
Duplicate of https://github.com/kubernetes/kubernetes/issues/93456, fixed in https://github.com/kubernetes/kubernetes/pull/97081, released in v1.24. Btw v1.23 is not supported.

Please, be aware that access to a loadBalancerIP with `externalTrafficPolicy: Local` from a _POD in main netns_ (hostNetwork: true) will still fail if there are no local endpoints. From other PODs it works.

The doc is somewhat wrong. More accurate may be;

> traffic sent from pods to an external LoadBalancer IP will be distributed in the same way as for cluster IP

**Comment by danwinship** [comment]
> Either way, we ought to document what is or isn't expected of the cluster network.

The official docs don't currently cover "how to implement a network plugin" at all. We probably ought to fix that. But the official unofficial "[how to write a proxy implementation](https://github.com/kubernetes-sigs/kpng/blob/master/doc/service-proxy.md)" doc covers this:

> Note that pods and nodes are allowed to connect to services via load balancer IPs. Ideally, pod-to-load-balancer-IP connections should be "short circuited" to the cluster IP by the service proxy, to ensure that the source IP can be preserved. (If the connection was not short-circuited, then normally the connection would end up SNAT'ed to the node IP before being passed to the load balancer.)
> ...
> (There is a subtle interaction here with the "short circuit" behavior of pod-to-load-balancer traffic: the behavior when a pod connects to a load balancer IP should logically be the same whether the service proxy short circuits it or not. Thus, when a pod connects to an `externalTrafficPolicy: Local` service via its load balancer IP, the connection must succeed _even if the pod is on a node with no endpoints for that service_.)

**Comment by uablrek** [comment]
@amorozkin Can we close this issue with the answer in https://github.com/kubernetes/kubernetes/issues/115931#issuecomment-1439595663 ?

**Comment by wu0407** [comment]
iptable implement code https://github.com/kubernetes/kubernetes/blob/816c97ab8cff8a1c72eccca1026f7820e93e0d25/pkg/proxy/iptables/proxier.go#L1381-L1391

**Comment by uablrek** [comment]
As described in https://github.com/kubernetes/kubernetes/issues/115931#issuecomment-1439595663 this is solved for ipvs in v1.24, so I close this issue.

@wu0407 The code for ipvs is different, but the _function_ is implemented in https://github.com/kubernetes/kubernetes/pull/97081. With the exception for access from a K8s node's main netns.

If we missed something, or you feel there's more that needs to be resolved here please drop a comment and we're happy to re-open this if necessary.

**Comment by wu0407** [comment]
> As described in [#115931 (comment)](https://github.com/kubernetes/kubernetes/issues/115931#issuecomment-1439595663) this is solved for ipvs in v1.24, so I close this issue.
> 
> @wu0407 The code for ipvs is different, but the _function_ is implemented in #97081. With the exception for access from a K8s node's main netns.
> 
> If we missed something, or you feel there's more that needs to be resolved here please drop a comment and we're happy to re-open this if necessary.

According to my understanding, pod access LB ip not redirect to cluster in ipvs mode  according this explain https://github.com/kubernetes/kubernetes/issues/115931#issuecomment-1439595663.
This pr https://github.com/kubernetes/kubernetes/pull/97081 only fix namespace pod access LB ip in Local mode when the node not contain any endpoint.
