### ISSUE TITLE
[Flaking Test] gce-cos-master-serial

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#115945]
### Which jobs are flaking?

master-informing

- gce-cos-master-serial

### Which tests are flaking?

Kubernetes e2e suite.[It] [sig-storage] PersistentVolumes-local Stress with local volumes [Serial] should be able to process many pods and reuse local volumes

### Since when has it been flaking?

2023-02-15 15:12:38 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

### Reason for failure (if possible)

`{ failed [FAILED] persistentvolumes "local-pvt2rz2" not found
In [AfterEach] at: test/e2e/storage/persistent_volumes-local.go:514 @ 02/21/23 18:15:38.461
}`

### Anything else we need to know?

Failed multiple times:
1. [2023-02-15 15:12:38 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1625875725103927296)
2. [2023-02-19 14:12:44 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1627310196499943424)
3. [2023-02-20 23:46:44 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1627817041287188480)
4. [2023-02-21 15:29:44 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1628054357587005440)

### Relevant SIG(s)

/sig storage

**Comment by msau42** [comment]
I think the AfterEach [pv cleanup](https://github.com/kubernetes/kubernetes/blob/173dde2a8c4b67027b6afcaeaf8d7e65cacc62c9/test/e2e/storage/persistent_volumes-local.go#L530-L531) is racing with the test's [PV recycling go-routine](https://github.com/kubernetes/kubernetes/blob/173dde2a8c4b67027b6afcaeaf8d7e65cacc62c9/test/e2e/storage/persistent_volumes-local.go#L507-L514)

AfterEach cleanup:
```
Feb 21 18:15:17.220: INFO: Deleting PersistentVolume "local-pvt2rz2" 
```

Test's PV recycling go routine:
```
STEP: Delete "local-pvt2rz2" and create a new PV for same local volume storage - test/e2e/storage/persistent_volumes-local.go:507 @ 02/21/23 18:15:17.287
Feb 21 18:15:17.339: INFO: Unexpected error: 
    <*errors.StatusError | 0xc0056db360>: {
        ErrStatus: 
            code: 404
            details:
              kind: persistentvolumes
              name: local-pvt2rz2
            message: persistentvolumes "local-pvt2rz2" not found
            metadata: {}
            reason: NotFound
            status: Failure,
    }
```

We're supposed to [wait for the test's PV recycling routine to exit](https://github.com/kubernetes/kubernetes/blob/173dde2a8c4b67027b6afcaeaf8d7e65cacc62c9/test/e2e/storage/persistent_volumes-local.go#L475-L479) before proceeding with cleanup.

@pohly do you know if this is still a valid assumption?

**Comment by pohly** [comment]
The recent Ginkgo changes didn't change anything regarding Go routines. If a test relies on a Go routine to have stopped, it needs to wait for that explicitly.

Note that the `ctx` created for an `It` node automatically gets cancelled when the `It` callback returns. However, that does not necessarily mean that Go routines terminate immediately.

**Comment by lauralorenz** [comment]
Just bumping that this test with this same error as OP is still a common flake as of today.

<img width="2768" alt="Screenshot 2023-03-20 at 3 22 23 PM" src="https://user-images.githubusercontent.com/5643703/226478370-67f76001-69ad-4aac-aa7f-9db24f7fb223.png">

**Comment by drewhagen** [comment]
FYI, these are still flaking. Here are some failures over the last few days:

![Image](https://user-images.githubusercontent.com/2896571/230479589-c17fc318-605f-4120-8f1a-1ea687a800a9.png)

**Comment by Vyom-Yadav** [comment]
![Image](https://github.com/kubernetes/kubernetes/assets/73882557/42f34569-7add-4a18-8ac9-d8337e2ee506)

Just bumping that this is still flaky and failed thrice in a row recently.

**Comment by aojea** [comment]
@onsi  @pohly The test seems to add a DeferCleanup to stop the goroutine mentioned in 

https://github.com/kubernetes/kubernetes/issues/115945#issuecomment-1440719324

From the docs
```
Under the hood DeferCleanup is generating a dynamic AfterEach node and adding it to the running spec. This detail isn't important - you can simply assume that code in DeferCleanup has the identical runtime semantics to code in an AfterEach.
```

Is guaranteed the order and the DeferCleanup will always run before the existing AfterEach block?

**Comment by pohly** [comment]
I believe the order is `It`, then `AfterEach` (first-in-first-out), `DeferCleanup` (first-in-last-out).

**Comment by aojea** [comment]
> I believe the order is `It`, then `AfterEach` (first-in-first-out), `DeferCleanup` (first-in-last-out).

then the order is wrong, because the goroutine should be stopped before AfterEach, that may explain the races

> I'd be happy to submit a PR that does just that.

@onsi please be my guest, tag me and/or patrick for review

**Comment by pohly** [comment]
Certainly we don't need @onsi to fix our tests for us?

**Comment by aojea** [comment]
> Certainly we don't need @onsi to fix our tests for us?

I know, I assumed he wanted to do it just for fun or something ... is the problem of text, you can't read between lines :)

**Comment by onsi** [comment]
lol! i'm happy to do it and contribute.

**Comment by dims** [comment]
LOL @aojea @pohly 

Thanks a ton for all that you do @onsi !

**Comment by onsi** [comment]
PR is here: https://github.com/kubernetes/kubernetes/pull/118524 - I'm not familiar with all the k8s backslash verbs and nouns but let me know if you need me to do anything on the PR to help move it along.

(and/or teach me how this works by telling me what I _should_ do next)
