### ISSUE TITLE
deployment rolling update fail if the pod use a "RWO" volume

### ISSUE THREAD

**Issue by aaron1989041** [kubernetes/kubernetes#115997]
a deployment's pod template use a "RWO" volume and rolling update strategy, during rolling update process, the new version pod can not accquire this "RWO" volume, so the new version pod will not be ready forever, and the rolling update will eventually fail...

**Comment by mlycore** [comment]
This is due to the volume can not be mounted by more than one Pod. Take a look at the PVC/PV status using `kubectl describe`.

**Comment by aaron1989041** [comment]
> 



> This is due to the volume can not be mounted by more than one Pod. Take a look at the PVC/PV status using `kubectl describe`.

thanks for reply mlycore. there's some error and warning messages in pvc/pv status, I wonder if there is some options in deployment manifest to help  avoid this situation,or should I not use a RWO  pvc/pv in deployment in order to use this "rolling update" feature.

**Comment by mlycore** [comment]
> 

Actually I don't think this is a necessary work that is needed to be handled by Deployment controller. This is also not related to if it is a`RWO` volume. 

Imagine that if two Pod shared same volume may cause some data corruption in the rollingupdate procedure. 

Or you can try deploy your application using Statefulset to see if it could sovle your problem.

**Comment by cvvz** [comment]
@aaron1989041 If you use deployment with [RWO](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes)volume, all the Pods will be scheduled to the same Node, and they can access to the same disk at the same time. 

Normally rolling update with RWO volume should not fail. Can you provide the Pod manifest and use `kubectl describe` to get the Pod and PVC events?
