### ISSUE TITLE
when upgrading kubelet, static pods are always killled even no manifest files are changed

### ISSUE THREAD

**Issue by silenceshell** [kubernetes/kubernetes#116080]
### What happened?

we are upgrading kubelet from 1.16 to 1.18, and find that all those static pods are recreated during the upgrading process.

This is because the static pod hash is a calculation of the `pod *api.Pod`, and the pod spec struct is updated when upgrading to 1.18:  `PodSecurityContext.FSGroupChangePolicy` is added.

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/common.go#L59

So kubelet could not find the container by the new pod hash, even no manifest files are changed.

We notice that those non static pods are not restart, as it has been fixed by this PR #57741
Is it possible to calculate the pod hash by the marshal string of pod struct, to avoid this unnecessary restart?

### What did you expect to happen?

If no manifest files are changed, static pods should not be killed when upgrading kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

on a kubernetes 1.16 version
1. deploy a static pod
2. upgrade kubelet to 1.18
3. check whether the static pod is killed or not

### Kubernetes version

<details>

old version
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.6", GitCommit:"72c30166b2105cd7d3350f2c28a219e6abcd79eb", GitTreeState:"clean", BuildDate:"2020-01-18T23:31:31Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-23+f1092e99bdb96f", GitCommit:"f1092e99bdb96f3c87100417fdc97041a85192e0", GitTreeState:"clean", BuildDate:"2022-03-09T06:51:06Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/arm64"}
```

new version
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-480+95ec2f470bb02d-dirty", GitCommit:"95ec2f470bb02d6eeb235f20c4fa5b5e1a20bd30", GitTreeState:"dirty", BuildDate:"2022-10-21T04:00:31Z", GoVersion:"go1.15.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.18-480+95ec2f470bb02d-dirty", GitCommit:"95ec2f470bb02d6eeb235f20c4fa5b5e1a20bd30", GitTreeState:"dirty", BuildDate:"2022-10-21T04:01:47Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
no, on bare metal.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Tencent Linux"
VERSION="2.4"
ID="tlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.4"
PRETTY_NAME="Tencent Linux 2.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tlinux:linux:2"
HOME_URL="https://tlinux.qq.com/"
$ uname -a
Linux tcs-10-0-9-99 4.14.105-19-0019 #1 SMP Fri Jan 15 11:39:34 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker version
Client: Docker Engine - Community
 Version:           19.03.15
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        99e3ed8
 Built:             Sat Jan 30 03:11:43 2021
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.15
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       7435467d1c
  Built:            Wed Jan 11 03:31:35 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.9-2-g7d642d13d
  GitCommit:        7d642d13d3130cb5cad4eccb49ba39c29c33c0bd
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
not related.
</details>

**Comment by liggitt** [comment]
/remove-kind bug
/kind support

In place upgrades of kubelet with running pods are not supported (see https://kubernetes.io/releases/version-skew-policy/#kubelet-1). Kubelet does not guarantee on-disk structures associated with running pods are compatible across versions. Before minor version upgrades, drain API controlled pods and remove static pod manifests. 

The PR you referenced made kubelet less vulnerable to disruptions by API server upgrades, but did not change support for in place upgrades with running containers. 

/close
