### ISSUE TITLE
strange output when "make test"

### ISSUE THREAD

**Issue by buaa-learner** [kubernetes/kubernetes#116029]
**### when run "make test KUBE_TIMEOUT="-timeout=300s", these are some strange output like this :**

I0224 10:54:34.870767   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă 出Ų9ƳC-驉\qÙPŀÌ僦粸 to ResourceManager
I0224 10:54:34.871039   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă ȆźĀŴ恰貭忏u瑒翶88Ǒ.鷶凲Ǳ to ResourceManager
I0224 10:54:34.871076   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă NƁǁǥ+襶ǆoŻn" to ResourceManager
I0224 10:54:34.871102   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă kʨ槍ȩ#< to ResourceManager
I0224 10:54:34.871127   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă ŵ崓j\ to ResourceManager
I0224 10:54:34.871163   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă 陛栍C]Ƹ>h頴 to ResourceManager
I0224 10:54:34.871184   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ ɼ嬘Ħ\哫ɟ屘ļ$ďůė閄缟鎩ƶ to ResourceManager
I0224 10:54:34.871204   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ 輜FȆĈʓzţ硴Ƈg鬩榍 to ResourceManager
I0224 10:54:34.871223   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ ʭ璶蠔塔_Ǹ崽礢)椏ʟɜ蕳`š to ResourceManager
I0224 10:54:34.871245   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ >Ǌƿ喚賀ȜŲ樯槰`恊Ů3¢ƶ to ResourceManager
I0224 10:54:34.871276   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 ʜhPƺ滢縕蠷Ŋ税2U帚)竛#Ȅ to ResourceManager
I0224 10:54:34.871300   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 躆鰺 to ResourceManager
I0224 10:54:34.871373   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 uĞȯ圾O& to ResourceManager
I0224 10:54:34.871428   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 4#F to ResourceManager
I0224 10:54:34.871477   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ Ɍ吞綵槞鳻Èjh坅Y縤滇駟5 to ResourceManager
I0224 10:54:34.871507   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ Íıư³Ƶ悰9âǹȲ裹 to ResourceManager
I0224 10:54:34.871529   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ ĝʘ_显ēŗ罛\E脢憑Ã7.iAÖ紮 to ResourceManager
I0224 10:54:34.871550   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ $ƭƖpY嚝ɜ5 to ResourceManager
I0224 10:54:34.871572   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ  to ResourceManager
I0224 10:54:34.872741   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:34.950537   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă 出Ų9ƳC-驉\qÙPŀÌ僦粸 to ResourceManager
I0224 10:54:34.950669   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă NƁǁǥ+襶ǆoŻn" to ResourceManager
I0224 10:54:34.950767   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă kʨ槍ȩ#< to ResourceManager
I0224 10:54:34.950858   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă ŵ崓j\ to ResourceManager
I0224 10:54:34.950948   11329 handler.go:149] Adding GroupVersion ĴȀơģ&夃M淂Ȑ@ă 陛栍C]Ƹ>h頴 to ResourceManager
I0224 10:54:34.951030   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ ɼ嬘Ħ\哫ɟ屘ļ$ďůė閄缟鎩ƶ to ResourceManager
I0224 10:54:34.951101   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ 輜FȆĈʓzţ硴Ƈg鬩榍 to ResourceManager
I0224 10:54:34.951168   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ ʭ璶蠔塔_Ǹ崽礢)椏ʟɜ蕳`š to ResourceManager
I0224 10:54:34.951259   11329 handler.go:149] Adding GroupVersion 炳;Ƌů茹罀d肼鰿õD3`zȳ諃ɤŊʙ >Ǌƿ喚賀ȜŲ樯槰`恊Ů3¢ƶ to ResourceManager
I0224 10:54:34.970422   11329 handler.go:149] Adding GroupVersion 鷶凲Ǳ.ĴȀơģ&夃M淂Ȑ@ă ȆźĀŴ恰貭忏u瑒翶88Ǒ to ResourceManager
I0224 10:54:34.988722   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 ʜhPƺ滢縕蠷Ŋ税2U帚)竛#Ȅ to ResourceManager
I0224 10:54:34.988805   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 uĞȯ圾O& to ResourceManager
I0224 10:54:34.988880   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 4#F to ResourceManager
I0224 10:54:34.988955   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ Ɍ吞綵槞鳻Èjh坅Y縤滇駟5 to ResourceManager
I0224 10:54:34.988998   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ Íıư³Ƶ悰9âǹȲ裹 to ResourceManager
I0224 10:54:34.989060   11329 handler.go:149] Adding GroupVersion iAÖ紮.őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ ĝʘ_显ēŗ罛\E脢憑Ã7 to ResourceManager
I0224 10:54:34.989142   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ $ƭƖpY嚝ɜ5 to ResourceManager
I0224 10:54:34.989209   11329 handler.go:149] Adding GroupVersion őļ仚Ğ陹筩婜ŦŦ澮g荍啨+ʨ  to ResourceManager
I0224 10:54:34.996475   11329 handler.go:149] Adding GroupVersion 嫿忦čɺƩȦ鏆¬ĥeT霃 躆鰺 to ResourceManager
I0224 10:54:35.194650   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:35.195691   11329 handler.go:149] Adding GroupVersion stable.example.com v1 to ResourceManager
I0224 10:54:35.319141   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0224 10:54:35.319213   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0224 10:54:35.319242   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ȵʭ洒$\' to ResourceManager
I0224 10:54:35.319283   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 壊3囜n繊ŀ槉@ to ResourceManager
I0224 10:54:35.319312   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º Hľȋ?{ə%ĺ誟ǀ還N儮 to ResourceManager
I0224 10:54:35.319336   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º ǭȐÿ to ResourceManager
I0224 10:54:35.319359   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 闀8ǿ滃 to ResourceManager
I0224 10:54:35.319382   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 覒ęȽ鉹鏪_败>ŵx¤蕰 to ResourceManager
I0224 10:54:35.319876   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:35.424314   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:35.428181   11329 handler.go:149] Adding GroupVersion stable.example.com v1 to ResourceManager
I0224 10:54:35.428949   11329 handler.go:149] Adding GroupVersion stable.example.com v1beta1 to ResourceManager
I0224 10:54:35.430081   11329 handler.go:149] Adding GroupVersion stable.example.com v1alpha1 to ResourceManager
--- FAIL: TestLegacyFallbackNoCache (0.14s)
    handler_discovery_test.go:379: 
                Error Trace:    /home/jiacheng/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery_test.go:379
                Error:          Not equal: 
                                expected: []v2beta1.APIGroupDiscovery{v2beta1.APIGroupDiscovery{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"stable.example.com", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Versions:[]v2beta1.APIVersionDiscovery{v2beta1.APIVersionDiscovery{Version:"v1beta1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d950), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1alpha1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d980), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d9b0), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}}}}
                                actual  : []v2beta1.APIGroupDiscovery{v2beta1.APIGroupDiscovery{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"stable.example.com", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Versions:[]v2beta1.APIVersionDiscovery{v2beta1.APIVersionDiscovery{Version:"v1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d890), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1beta1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d8c0), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}, v2beta1.APIVersionDiscovery{Version:"v1alpha1", Resources:[]v2beta1.APIResourceDiscovery{v2beta1.APIResourceDiscovery{Resource:"foos", ResponseKind:(*v1.GroupVersionKind)(0xc00056d8f0), Scope:"Cluster", SingularResource:"foo", Verbs:[]string{"get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"}, ShortNames:[]string(nil), Categories:[]string{"all"}, Subresources:[]v2beta1.APISubresourceDiscovery(nil)}}, Freshness:"Current"}}}}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -30,2 +30,33 @@
                                   Versions: ([]v2beta1.APIVersionDiscovery) (len=3) {
                                +   (v2beta1.APIVersionDiscovery) {
                                +    Version: (string) (len=2) "v1",
                                +    Resources: ([]v2beta1.APIResourceDiscovery) (len=1) {
                                +     (v2beta1.APIResourceDiscovery) {
                                +      Resource: (string) (len=4) "foos",
                                +      ResponseKind: (*v1.GroupVersionKind)({
                                +       Group: (string) (len=18) "stable.example.com",
                                +       Version: (string) (len=2) "v1",
                                +       Kind: (string) (len=3) "Foo"
                                +      }),
                                +      Scope: (v2beta1.ResourceScope) (len=7) "Cluster",
                                +      SingularResource: (string) (len=3) "foo",
                                +      Verbs: ([]string) (len=8) {
                                +       (string) (len=3) "get",
                                +       (string) (len=4) "list",
                                +       (string) (len=5) "watch",
                                +       (string) (len=6) "create",
                                +       (string) (len=6) "update",
                                +       (string) (len=5) "patch",
                                +       (string) (len=6) "delete",
                                +       (string) (len=16) "deletecollection"
                                +      },
                                +      ShortNames: ([]string) <nil>,
                                +      Categories: ([]string) (len=1) {
                                +       (string) (len=3) "all"
                                +      },
                                +      Subresources: ([]v2beta1.APISubresourceDiscovery) <nil>
                                +     }
                                +    },
                                +    Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
                                +   },
                                    (v2beta1.APIVersionDiscovery) {
                                @@ -91,33 +122,2 @@
                                     Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
                                -   },
                                -   (v2beta1.APIVersionDiscovery) {
                                -    Version: (string) (len=2) "v1",
                                -    Resources: ([]v2beta1.APIResourceDiscovery) (len=1) {
                                -     (v2beta1.APIResourceDiscovery) {
                                -      Resource: (string) (len=4) "foos",
                                -      ResponseKind: (*v1.GroupVersionKind)({
                                -       Group: (string) (len=18) "stable.example.com",
                                -       Version: (string) (len=2) "v1",
                                -       Kind: (string) (len=3) "Foo"
                                -      }),
                                -      Scope: (v2beta1.ResourceScope) (len=7) "Cluster",
                                -      SingularResource: (string) (len=3) "foo",
                                -      Verbs: ([]string) (len=8) {
                                -       (string) (len=3) "get",
                                -       (string) (len=4) "list",
                                -       (string) (len=5) "watch",
                                -       (string) (len=6) "create",
                                -       (string) (len=6) "update",
                                -       (string) (len=5) "patch",
                                -       (string) (len=6) "delete",
                                -       (string) (len=16) "deletecollection"
                                -      },
                                -      ShortNames: ([]string) <nil>,
                                -      Categories: ([]string) (len=1) {
                                -       (string) (len=3) "all"
                                -      },
                                -      Subresources: ([]v2beta1.APISubresourceDiscovery) <nil>
                                -     }
                                -    },
                                -    Freshness: (v2beta1.DiscoveryFreshness) (len=7) "Current"
                                    }
                Test:           TestLegacyFallbackNoCache
I0224 10:54:35.563472   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:35.564762   11329 handler.go:149] Adding GroupVersion stable.example.com v1 to ResourceManager
I0224 10:54:35.690503   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0224 10:54:35.690626   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0224 10:54:35.690667   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ȵʭ洒$\' to ResourceManager
I0224 10:54:35.690743   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 壊3囜n繊ŀ槉@ to ResourceManager
I0224 10:54:35.690823   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º Hľȋ?{ə%ĺ誟ǀ還N儮 to ResourceManager
I0224 10:54:35.690915   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º ǭȐÿ to ResourceManager
I0224 10:54:35.690964   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 闀8ǿ滃 to ResourceManager
I0224 10:54:35.691026   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 覒ęȽ鉹鏪_败>ŵx¤蕰 to ResourceManager
I0224 10:54:35.691565   11329 handler_discovery.go:392] Starting ResourceDiscoveryManager
I0224 10:54:35.739837   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0224 10:54:35.740090   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ȵʭ洒$\' to ResourceManager
I0224 10:54:35.740169   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 壊3囜n繊ŀ槉@ to ResourceManager
I0224 10:54:35.740431   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º Hľȋ?{ə%ĺ誟ǀ還N儮 to ResourceManager
I0224 10:54:35.740563   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º ǭȐÿ to ResourceManager
I0224 10:54:35.740623   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 闀8ǿ滃 to ResourceManager
I0224 10:54:35.761335   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0224 10:54:35.794074   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 凣OC瓴业ǯSfĹǳƘ繙e to ResourceManager
I0224 10:54:35.794824   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ɰ薗w2;3 to ResourceManager
I0224 10:54:35.794988   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 ȵʭ洒$\' to ResourceManager
I0224 10:54:35.795240   11329 handler.go:149] Adding GroupVersion 摾Lʉĥ峡拓 壊3囜n繊ŀ槉@ to ResourceManager
I0224 10:54:35.795564   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º Hľȋ?{ə%ĺ誟ǀ還N儮 to ResourceManager
I0224 10:54:35.796027   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º ǭȐÿ to ResourceManager
I0224 10:54:35.796304   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 覒ęȽ鉹鏪_败>ŵx¤蕰 to ResourceManager
I0224 10:54:35.798153   11329 handler.go:149] Adding GroupVersion z,劚ƒqiM7婼<7圾º 闀8ǿ滃 to ResourceManager
E0224 10:54:36.031421   11329 handler_proxy.go:150] error resolving test-ns/bad-service: unresolveable
2023/02/24 10:54:36 http: TLS handshake error from 127.0.0.1:52790: remote error: tls: bad certificate
I0224 10:54:36.411166   11329 server_cert_deprecations.go:68] missing-san.invalid-cert.kubernetes.io: invalid certificate detected connecting to "127.0.0.1": relies on a legacy Common Name field instead of the SAN extension for subject validation
2023/02/24 10:54:36 http: TLS handshake error from 127.0.0.1:45458: remote error: tls: bad certificate
2023/02/24 10:54:36 http: TLS handshake error from 127.0.0.1:54414: remote error: tls: bad certificate
2023/02/24 10:54:42 http: TLS handshake error from 127.0.0.1:51098: tls: failed to verify certificate: x509: certificate signed by unknown authority
FAIL

**Comment by mlycore** [comment]
Please provide the environment information. And it seems like some encoding issue while the logs meet a wrong charset .

**Comment by liggitt** [comment]
I think the failure is a non-deterministic unit test that was fixed recently

the weird output might be due to fuzzing creating testdata, not sure if that's intended or if that can be improved

cc @alexzielenski

**Comment by buaa-learner** [comment]
> I think the failure is a non-deterministic unit test that was fixed recently
> 
> the weird output might be due to fuzzing creating testdata, not sure if that's intended or if that can be improved
> 
> cc @alexzielenski
