### ISSUE TITLE
[Flaky tests] integration-master

### ISSUE THREAD

**Issue by drewhagen** [kubernetes/kubernetes#116061]
⚠**The signal due (2/28) for the v1.27.0-alpha.3 release cut  is less than 3 days away.**
### Which jobs are flaking?
sig-release-master-blocking
integration-master

### Since when has it been flaking?
2/25 00:29 PST

### Testgrid link
https://k8s-testgrid.appspot.com/sig-release-master-blocking#integration-master

#### Prow links
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629518636722950144
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629503537035612160
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629488437184696320
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629458237789048832
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629443138210762752
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629412938861252608
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1629397587930910720

### Reason for failure (if possible)
Intermittent failures in Role Based Access Control
```
{Failed  === RUN   TestRBAC
--- FAIL: TestRBAC (16.14s)
}
```

```
{Failed  === RUN   TestRBAC/case-3
```

### Anything else we need to know?
The logs are long, also there are a lot of errors in the build logs. Please refer to one of the plow links for full context.

### Relevant SIGs

**Comment by liggitt** [comment]
the panic is like this:

```
E0225 16:52:07.362025   82355 runtime.go:77] Observed a panic: FieldManager must be installed to run apply
goroutine 137185 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher.finishRequest.func1.1()
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/finisher/finisher.go:105 +0xa5
panic({0x4399ba0, 0x5a88890})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*applyPatcher).applyPatchToCurrentObject(0xc0002378f0?, {0x5ac56c8?, 0xc009b23b90?}, {0x5aa0fc8?, 0xc0012a45a0?})
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/patch.go:469 +0x449
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*applyPatcher).createNewObject(0xc0039c50e0, {0x5ac56c8, 0xc009b23b90})
```

The commit that failures started on is from #115324 which looks related to field manager construction

I would consider reverting #115324 to see if this resolved the panic for alpha.3

/assign @alexzielenski 
/sig api-machinery
/remove-sig testing
