### ISSUE TITLE
verify openapi-spec failed

### ISSUE THREAD

**Issue by rayowang** [kubernetes/kubernetes#116036]
### Which jobs are failing?

pull-kubernetes-verify 

### Which tests are failing?

verify: openapi-spec

### Since when has it been failing?

{Script Error ScriptError go version go1.20.1 linux/amd64
rm: cannot remove '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/*': No such file or directory
rm: refusing to remove '.' or '..' directory: skipping '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/.'
rm: refusing to remove '.' or '..' directory: skipping '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/..'
/home/prow/go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh}

### Testgrid link

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/115996/pull-kubernetes-verify/1629039996209991680

### Anything else we need to know?

I have run the job many times but failed, and the error is as follows：

When I run hack/update-openapi-spec.sh, the following error still occurs:
hack/../api/openapi-spec for OpenAPI v2\n
+++ [0224 15:45:32] Updating 
    hack/../api/openapi-spec/v3 for OpenAPI v3
rm: refusing to remove '.' or '..' directory: skipping 'hack/../api/openapi-spec/v3/.'
rm: refusing to remove '.' or '..' directory: skipping 'hack/../api/openapi-spec/v3/..'
+++ [0224 15:45:32] Updating OpenAPI spec for group .well-known/openid-configuration
+++ [0224 15:45:32] Updating OpenAPI spec for group api
I would like to ask what is the reason for this? How should it be fixed? thanks

### Relevant SIG(s)

/sig

**Comment by liggitt** [comment]
the linked PR is adding a v2beta2 json openapi file which appears in the diff output

ensure you are generating with latest tags fetched from git to inform which APIs are still served

/close
