### ISSUE TITLE
cannot update pod security admission controller's exemptions 

### ISSUE THREAD

**Issue by Dorsosiv** [kubernetes/kubernetes#116004]
### What happened?

I have Openshift cluster with version 4.11 (K8s v1.24.6)  
In the cluster I get the warning when creating new deployments about PodSecurity.   
Not just this deployment , for any deployment. 
```
│ W0221 10:40:58.250242       1 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "python-container-create-error" must set securityContext.allowPrivile │
│ geEscalation=false), unrestricted capabilities (container "python-container-create-error" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "python-container-create │
│ -error" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "python-container-create-error" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

## My end goal 
Is to exclude a specific namespace from PodSecurity , so I will not get errors about it. But I cannot understand what should I do to set this configuration.

### What did you expect to happen?

I expected to easily find the admission controller and update its configmap or admissionConfiguration to exclude the specific namespace.  

However I do not find such object in my cluster. Plus the resource type is not familiar to my cluster. 

### How can we reproduce it (as minimally and precisely as possible)?

The openshift 4.11 is a new cluster we recently installed. I guess you can do the same and just do not disable PodSecurity during the installation. 

### Anything else we need to know?

I did find this documentation about how to create the configuration for the admission controller https://v1-24.docs.kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller  

But I cannot apply it. 

```
oc apply -f pod-security-admission-controller.yaml 
error: unable to recognize "pod-security-admission-controller.yaml": no matches for kind "AdmissionConfiguration" in version "apiserver.config.k8s.io/v1"

```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"0d10c3f72592addce965b9bb34992eb6fc283a3b", GitTreeState:"clean", BuildDate:"2021-08-31T22:03:33Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.6+5658434", GitCommit:"eddac29feb4bb46b99fb570999324e582d761a66", GitTreeState:"clean", BuildDate:"2022-11-09T10:31:39Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.24) exceeds the supported minor version skew of +/-1

```

</details>

### Cloud provider

<details>
On premise cluster.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="411.86.202211291109-0"
VERSION_ID="4.11"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 411.86.202211291109-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.11/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.11"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.11"
OPENSHIFT_VERSION="4.11"
RHEL_VERSION="8.6"
OSTREE_VERSION="411.86.202211291109-0"

$ uname -a
Linux master1 4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
See the current version of that documentation at https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller

> The above manifest needs to be specified via the --admission-control-config-file to kube-apiserver.

The configuration to exempt a namespace is set when starting the APi server, not via a REST API

/remove-kind bug
/kind support
/close
