### ISSUE TITLE
question of a piece of code on files cmd/kubelet/app server.go about tracing

### ISSUE THREAD

**Issue by charles-chenzz** [kubernetes/kubernetes#116073]
Hi, I am a beginer on K8s and while I reading the source code of kubelet this confuse me
![image](https://user-images.githubusercontent.com/73322208/221466625-ae67c0c7-a039-4bd4-a1d2-008b10629b0d.png)
it's on ``cmd/kubelet/app/server.go`` line 1295,  I only know little about kubelet and tracing, so if anyone know the logic here could you please tell me?

/area kubelet
/sig node

**Comment by mengjiao-liu** [comment]
Are you missing something？
The return value type obtained by `tp` is `TracerProvider`,
`TracerProvider` contains `oteltrace.TracerProvider` interface.
```
// staging/src/k8s.io/component-base/tracing/utils.go:35
// TracerProvider is an OpenTelemetry TracerProvider which can be shut down
type TracerProvider interface {
	oteltrace.TracerProvider
	Shutdown(context.Context) error
}
```

You can ask questions like this on the Slack channel [#sig-instrumentation](https://kubernetes.slack.com/archives/C20HH14P7).

/kind support

**Comment by charles-chenzz** [comment]
> Are you missing something？ The return value type obtained by `tp` is `TracerProvider`, `TracerProvider` contains `oteltrace.TracerProvider` interface.
> 
> ```
> // staging/src/k8s.io/component-base/tracing/utils.go:35
> // TracerProvider is an OpenTelemetry TracerProvider which can be shut down
> type TracerProvider interface {
> 	oteltrace.TracerProvider
> 	Shutdown(context.Context) error
> }
> ```
> 
> You can ask questions like this on the Slack channel [#sig-instrumentation](https://kubernetes.slack.com/archives/C20HH14P7).
> 
> /kind support

tbh I don't know why my ide will appear this error, I check the code and it did contains the interface, maybe it's my go version or ide issues.
btw, I didn't join the sig-instru slack, can you send me a invite or something?

**Comment by mengjiao-liu** [comment]
You can refer to the page: https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md#contact

**Comment by charles-chenzz** [comment]
> Visit [slack.k8s.io](https://slack.k8s.io/) for a workspace invitation And you can refer to the page to join sig-instrumentation: https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md#contact

joined, thanks for the help! btw, pacoxu help me with my first issue, seems like you're the teammate of him haha

**Comment by saschagrunert** [comment]
@charles-chenzz can we close out this issue or is there anything left?

**Comment by charles-chenzz** [comment]
> 

it's done, I forgot to close, sorry
