### ISSUE TITLE
Install and Set Up kubectl on Linux - apt-key retrieval returning 500

### ISSUE THREAD

**Issue by abegosum** [kubernetes/kubernetes#116092]
When following the instructions on "Install and Set Up kubectl on Linux" in the native package management section for apt, curling the gpg key per the instructions results in a 500 error.  The error can also be observed directly in a browser.

```
$ sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
curl: (22) The requested URL returned error: 500
```

**Comment by sftim** [comment]
See work around with new URL here: [kubernetes/k8s.io#4837 (comment)](https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585)

**Comment by abegosum** [comment]
Thanks for the heads up, @sftim !
