### ISSUE TITLE
Topology Aware Hints not working as expected v1.24

### ISSUE THREAD

**Issue by shmuelarditi** [kubernetes/kubernetes#116098]
### What happened?

Hi, we are using kubernetes v1.24,
im trying to implement the new default feature from v1.24 - **Topology Aware Hints** to keep traffic inside the AZ as much as possible, but seems like i cant get this to work..
**my configuration:**
- EKS cluster with around 12 nodes at a time spread evenly across 2 AZ's (us-west-2a, us-west-2b) - 6 nodes per AZ
- a messenger application with 2 replicas spread evenly across the AZ's - 1 replica per az  (can be on each one of the 6 nodes)
- a reciever application with 4 replicas spread evenly across the AZ's - 2 replica per az  (can be on each one of the 6 nodes)
- those 2 applications are scheduled evenly across AZ's thanks to using **topologySpreadConstraints**
```
topologySpreadConstraints
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/instance
            operator: In
            values:
            - {{ .Release.Name }}
```
- Topology Aware Hints activated for both of the applications services by using this annotation:
`service.kubernetes.io/topology-aware-hints: auto`

i can see the hints created succsesfully by the **endpointslice-controller** , but still for some reason the traffic are routed exactly the same as before, no AZ prefference. 

### What did you expect to happen?

expected that the traffic from messenger replica that resides in us-west-2a will be routed by the kube-proxy to any of the 2 recievers that resides in the same AZ, the hints exist perfectly as they should in the endpointslice.

### How can we reproduce it (as minimally and precisely as possible)?

- deploy 2 applications that one of them comunicates with the service name of the other, for example application A send data to application B using the internal dns of kubernetes: <Service-Name>.<Namespace>.svc.cluster.local

- make sure the applications have multiple replicas and they are spread across 2 AZ's or more so every replica will have a replica of the other application within the same AZ. (use topologySpreadConstraints) 

- enable topology aware hints on the application services ussing the required annotation.

- log the traffic and compare the AZ's. 

my 2 python applications are using the kubernetes API to retrieve information about their host machine.
so application A send the node name and the AZ as a messege to Application B.

application B compares the information with it own information and prints if the traffic came from the same AZ or not.
prints are visiable using kubectl logs example of my application logs:

--------------
Pod Information:
ID: 3
Pod name: python-messenger-qa-inter-az-chart-69bb45565-zvsfr
Node name: ip-178-0-27-47.us-west-2.compute.internal
AZ: us-west-2a

My Information:
Pod name: python-reciever-qa-inter-az-chart-798bdf984b-gkqp8
Node name: ip-178-0-7-95.us-west-2.compute.internal
AZ: us-west-2a

**The AZ values match - Traffic Stayed Inside the AZ**
** The Node name values do not match **
178.0.39.149 - - [27/Feb/2023 15:45:17] "POST / HTTP/1.1" 200 -
--------------
Sender Information:
ID: 5
Pod name: python-messenger-qa-inter-az-chart-69bb45565-bf45s
Node name: ip-178-0-96-184.us-west-2.compute.internal
AZ: us-west-2b

My Information:
Pod name: python-reciever-qa-inter-az-chart-798bdf984b-gkqp8
Node name: ip-178-0-7-95.us-west-2.compute.internal
AZ: us-west-2a

** The AZ values do not match **
** The Node name values do not match **
178.0.89.240 - - [27/Feb/2023 15:45:47] "POST / HTTP/1.1" 200 -
-------------- 

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2023-01-04T19:18:50Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.8-eks-ffeb93d", GitCommit:"abb98ec0631dfe573ec5eae40dc48fd8f2017424", GitTreeState:"clean", BuildDate:"2022-11-29T18:45:03Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

AWS

### OS version

ubuntu 22.04

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
BTW you can use GitHub [Markdown](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to mark the preformatted parts of the issue description.

**Comment by sftim** [comment]
In Kubernetes v1.24, topology aware hints are behind a feature gate: https://v1-24.docs.kubernetes.io/docs/concepts/services-networking/topology-aware-hints/
and that feature gate is _not_ enabled by default.

Has your cloud provider enabled that feature gate for your v1.24 cluster?

**Comment by shmuelarditi** [comment]
sig/network

> Most probably duplicate of [#114215 (comment)](https://github.com/kubernetes/kubernetes/issues/114215#issuecomment-1362205406)

i dont think it is, from my experience my hints are not removed from the endpointslices, everything is there, it just doest really work, 

> In Kubernetes v1.24, topology aware hints are behind a feature gate: https://v1-24.docs.kubernetes.io/docs/concepts/services-networking/topology-aware-hints/ and that feature gate is _not_ enabled by default.
> 
> Has your cloud provider enabled that feature gate for your v1.24 cluster?

yes in EKS its and default feature in 1.24 and the endpointslice controller does put hints on my endpoint slices, and labels them managed by: endpoint-slice-controller (something like that)

**Comment by aojea** [comment]
> i dont think it is, from my experience my hints are not removed from the endpointslices, everything is there, it just doest really work,

ok, great, if the hints are showing in the endpointslices then the component that doesn the service forwarding is not following them (most probably)

is eks using kube-proxy? is the feature enabled in kube-proxy? 

I don't think we can help more here than this, if the hints are published is on the service proxy implementation to leverage them

**Comment by shmuelarditi** [comment]
> > i dont think it is, from my experience my hints are not removed from the endpointslices, everything is there, it just doest really work,
> 
> ok, great, if the hints are showing in the endpointslices then the component that doesn the service forwarding is not following them (most probably)
> 
> is eks using kube-proxy? is the feature enabled in kube-proxy?
> 
> I don't think we can help more here than this, if the hints are published is on the service proxy implementation to leverage them

yes, EKS does use kubeproxy 
![image](https://user-images.githubusercontent.com/91881199/221800207-b1840bd2-f39a-4547-a999-a27a0fa481b1.png)

and i can see that my kube-proxy is version 1.21.. thats probebly the cause, ill try upgrading it to at least 1.24 to match the kubernetes version, it should probebly have the functionallity i need  in 1.24. 

thanks alot, i will update in the new few hours.

**Comment by aojea** [comment]
❤️ 

/close
