### ISSUE TITLE
failing test : verify-import-aliases.sh

### ISSUE THREAD

**Issue by buaa-learner** [kubernetes/kubernetes#116007]
after running "hack/make-rules/../../hack/verify-import-aliases.sh", it goes wrong like this:

go version go1.20.1 linux/amd64
cmd/preferredimports/preferredimports.go:37:2: cannot find package "golang.org/x/term" in any of:
        /home/jiacheng/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/golang.org/x/term (from $GOROOT)
        /root/go/src/golang.org/x/term (from $GOPATH)
!!! Please see hack/.import-aliases for the preferred aliases for imports.

**Comment by pacoxu** [comment]
/close 
per https://github.com/kubernetes/kubernetes/pull/116014#issuecomment-1442727735
