### ISSUE TITLE
Makefile:339: vet Error 1 when running verify-govet.sh

### ISSUE THREAD

**Issue by buaa-learner** [kubernetes/kubernetes#116006]
After running "make verify", "verify-govet.sh" failed.
-----------------
FAILED TESTS:
hack/make-rules/../../hack/verify-govet.sh
-----------------
cannot find package "_/home/jiacheng/kubernetes/test/typecheck" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/typecheck (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/typecheck (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/apiserver" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/apiserver (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/apiserver (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/crd" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/crd (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/crd (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/format" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/format (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/format (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/harness" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/harness (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/harness (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/image" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/image (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/image (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/junit" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/junit (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/junit (from $GOPATH)
cannot find package "_/home/jiacheng/kubernetes/test/utils/kubeconfig" in any of:
        /usr/local/go/src/_/home/jiacheng/kubernetes/test/utils/kubeconfig (from $GOROOT)
        /root/go/src/_/home/jiacheng/kubernetes/test/utils/kubeconfig (from $GOPATH)

**Comment by pacoxu** [comment]
/close
per https://github.com/kubernetes/kubernetes/pull/116014#issuecomment-1442727735
