### ISSUE TITLE
Cannot install kubeadm on bare metal due to missing gpg

### ISSUE THREAD

**Issue by PaulsAgileIndex** [kubernetes/kubernetes#116087]
### What happened?

Trying to install kubeadm, kubelet, kubectl on Ubuntu 22.04 but cannot add the `gpg` because it is not available under: `https://packages.cloud.google.com/apt/doc/apt-key.gpg`

```
root@master:~# sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
curl: (22) The requested URL returned error: 500
```

### What did you expect to happen?

That I can add the gpg file to `/etc/apt/keyrings`

### How can we reproduce it (as minimally and precisely as possible)?

Just try to download it form the specified location in the [Kubernetes Doc](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/) :` https://packages.cloud.google.com/apt/doc/apt-key.gpg`

### Kubernetes version

<details>
Cannot install kubeadm, kubelet, kubectl due to missing repository key
```console
$ kubectl version
# 1.26-00
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
# Linux master 5.15.0-1028-aws #32-Ubuntu SMP Mon Jan 9 12:28:07 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by PaulsAgileIndex** [comment]
![MissingGPG](https://user-images.githubusercontent.com/4631850/221553086-3e6ff416-f7b3-45ac-89de-727ac972cf53.png)

**Comment by Stolr** [comment]
Same here :

fatal: []: FAILED! => {"changed": false, "msg": "Failed to download key at https://packages.cloud.google.com/apt/doc/apt-key.gpg: HTTP Error 500: Internal Server Error"}


 It  was pretty random during the week-end and now it is not working at all.

It is impossible to install k8s anymore.

/critical

**Comment by dims** [comment]
See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
