### ISSUE TITLE
Ubuntu install fails due to 500 error downloading: apt-key.gpg

### ISSUE THREAD

**Issue by jefflill** [kubernetes/kubernetes#116068]
### What happened?

I'm seeing HTTP 500 errors trying to download **apt-key.gpg** when following the steps to install Kubernetes on Ubuntu using the package manager.  This stopped working yesterday (Feb 25, 2023).  Here's the entire URL.

https://packages.cloud.google.com/apt/doc/apt-key.gpg

I also tried opening https://packages.cloud.google.com in the browser an navigating down to the file and got a 404 error.

### What did you expect to happen?

I expected this file to download without problem.

### How can we reproduce it (as minimally and precisely as possible)?

Simply try to cURL this file:
```
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg
```
I see this result:
```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 500 (Internal Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/logos/errorpage/error_logo-150x54-2x.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>500.</b> <ins>That’s an error.</ins>
  <p>  <ins>That’s all we know.</ins>
```

### Kubernetes version

<details>

```console
$ kubectl version
1.24.0
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux ubuntu 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nutellinoit** [comment]
I have the same problem

**Comment by jedrekdomanski** [comment]
I have the same problem. I was able to download it today morning Polish time, though. I opened an issue on Stackoverflow before coming here
https://stackoverflow.com/questions/75574752/unable-to-install-apt-google-cloud-public-signing-key-and-kubernetes-apt-reposit

**Comment by matt-harbers** [comment]
Same problem here, as well

**Comment by HirazawaUi** [comment]
/sig release


[release](https://github.com/kubernetes/kubernetes/labels/sig%2Frelease

**Comment by jimbo8098** [comment]
Yep, I'm finding the same here.

```
root@f1922d83ec6c:/src# curl -I https://packages.cloud.google.com/apt/doc/apt-key.gpg
HTTP/2 500
content-length: 1461
content-security-policy: object-src 'none'; script-src 'nonce-OcdWGCTvczANFt1kvhoXaYrzAdA=' 'unsafe-inline'; base-uri 'none'; report-uri https://csp.withgoogle.com/csp/rapture/
content-type: text/html; charset=utf-8
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 0
date: Mon, 27 Feb 2023 11:58:31 GMT
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

I can access https://packages.cloud.google.com and browse through apt then doc, but the result is the same on Chrome.

**Comment by aiproshar** [comment]
I am also facing the same issue. Consistent when trying to access from Compute Engine. Sometimes 404 and mostly 500

To reproduce on GCP:

- region & zone: asia-southeast1-a
- ubuntu-22.04 LTS
- private ip VM with cloud NAT
wget or curl: https://packages.cloud.google.com/apt/doc/apt-key.gpg

**12 hours ago i was able to access from my local machine (outside of that specific region) but failed from GCP VMs. Currently unable to access from both my local machine and Vms.

**Comment by aiproshar** [comment]
![image](https://user-images.githubusercontent.com/24490400/221575420-378b602a-7ca3-4e96-880a-a6030c729e9b.png)

apt-key.gpg and apt-key.gpg.asc throws 500. Later two is seems fine.

**Comment by brianpursley** [comment]
Related to this:

https://groups.google.com/a/kubernetes.io/g/dev/c/gR5xDzzIcW8/m/XPZIPUYEAQAJ?utm_medium=email&utm_source=footer&pli=1

**Comment by dims** [comment]
See work around with new URL here: https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585

**Comment by jedrekdomanski** [comment]
The workaround posted by @dims worked for me.

**Comment by jefflill** [comment]
Looks like the official URL is working again.

**Comment by demmonico** [comment]
Also fixed for me!

**Comment by liggitt** [comment]
closing as resolved
