### ISSUE TITLE
Update batching delay for EndpointSlices uses two flags inconsistently

### ISSUE THREAD

**Issue by dlapcevic** [kubernetes/kubernetes#116011]
### What happened?

There are two flags `endpointSliceChangeMinSyncDelay` and `endpointUpdatesBatchPeriod` that are used to add delay to enqueue multiple subsequent update events to be processed.

References to usage of delay values for `AddAfter()` method of workqueue:
addPod: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpointslice/endpointslice_controller.go#L495
queueServiceForEndpointSlice: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpointslice/endpointslice_controller.go#L484

### What did you expect to happen?

The expected behavior is to use the flags in a consistent way when enqueuing changes to EndpointSlices.
Either both changes to Services/EndpointSlices and changes to Pods should use max(`endpointSliceChangeMinSyncDelay`, `endpointUpdatesBatchPeriod`), or there should be very clear indication why they are not, and why overriding `endpointUpdatesBatchPeriod` to a value between 0 and 1 seconds will not affect delay for changes to Services/EndpointSlices.

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

/sig scalability

### Kubernetes version

-

### Cloud provider

-

**Comment by dlapcevic** [comment]
cc @mborsz @marseel

**Comment by PriyanshuAhlawat** [comment]
hi, I will like to work on this.

**Comment by dlapcevic** [comment]
Thanks for the explanation @robscott.

There are two things I’d like us to consider:

1. Make it simpler to configure.
Perhaps have a single flag for all, with the same default, or completely decouple the two, EndpointSlice and pod(endpoint) update delays.

2. Clarify the effects.
It was slightly confusing to me why it’s set up this way. It would be good to have some kind of justification or guidelines on why it has defaults of 1s for EndpointSlice update and 0 for pod(endpoint) update, and what kind of behavior and scalability impact it has (trade-offs).

I think both of these things should be accessible for K8s users who are interested in improving their EndpointSlice performance.
