### ISSUE TITLE
Resource Quotas: Possibility to not enforce limits.cpu per pod

### ISSUE THREAD

**Issue by scenox** [kubernetes/kubernetes#116063]
### What would you like to be added?

Currently, for cpu (and memory) resources, ResourceQuotas enforce that every (new) pod in that namespace sets a limit for that resource.

There should be a new option for the limits.cpu ResourceQuota at namespace level:
`enforceLimitPerPod: true (default) / false`

If false, it's optional to define limits.cpu for each pod in this namespace. `limits.cpu` of the namespace minus `limits.cpu` of each pod (where defined) should be used to limit CPU usage across all other pods in this namespace.

### Why is this needed?

According to https://kubernetes.io/docs/concepts/policy/resource-quotas/,
you can limit the total sum of compute resources that can be requested in a given namespace. limits.cpu for the namespace ist computed as follows: Across all pods in a non-terminal state, the sum of CPU limits cannot exceed this value.

This is a problem with workloads which have a low base CPU usage with short cpu spikes randomly distributed across pods and time. A lot of assigned CPU is wasted in such case.
For such workload scenarios, it would make more sense to limit only the sum of CPU usage of all pods in the namespace instead of limiting each pod separately.

Example: 
limits.cpu namespace: 8
16 containers with limits.cpu 500m

Each of these containers are limited to 500m CPU which could affect application performance negatively.  If specification of limits.cpu is not enforced in this namespace, each pod could use up to 7.985 CPU If each other pod in the observed timeslot currently has a CPU usage of 1m.

**Comment by pacoxu** [comment]
Did you try `LimitRange` to add some default cpu limit?
https://kubernetes.io/docs/concepts/policy/limit-range/

**Comment by scenox** [comment]
I considered `LimitRange` but I don't think it solves the issue.

Some context:
Cluster operators often use CPU and memory limits per namespace to put a price tag on providing their infrastructure. They don't want to care about the number of pods, the CPU requirements of each pod in the namespace or any other application-specific requirements on this level - they only care about the CPU usage of the namespace and want to limit that.
In the case above with `LimitRange`, the cluster operator would have to define a max limit of 8 CPU per pod and theoretically, each pod could then use 8 CPU which isn't what the cluster operator wants. He wants to limit the CPU usage of the set of all pods in the namespace to 8, which should be possible via `cgroup`.

**Comment by liggitt** [comment]
> He wants to limit the CPU usage of the set of all pods in the namespace to 8, which should be possible via cgroup.

cgroups are local to the node running the pod, but pods in a namespace are not all on the same node. That means real time CPU usage would have to be reported back into the API, observed by other nodes, and cgroup rules updated in response, at high frequency, for this to work. You need some indicator on each pod how the CPU limits should be set to inform the node how to set its cgroups.

**Comment by scenox** [comment]
Why not distributing available CPU to the set of pods on each node relative to the number of pods?
E.g. 
Namespace cpu limit: 8
Pods in namespace: 16
Node A: 12 pods -> cgroup set to 6 CPU for the whole set of 12 pods
Node B: 4 pods: -> cgroup set to 2 CPU for the whole set of 4 pods
