### ISSUE TITLE
Using golang client requires lots of dependencies

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#11606]
While trying to add kubernetes discovery to prometheus (prometheus/prometheus#905) using the golang client, I have to add 613 files & the addition of the kubernetes client has added 6MB to the binary, previously 17MB for all functionality. This has made it quite hard to contribute this functionality to prometheus as it makes reviews hard & the change to the binary size questionable.

I tried to move to straight `http.Client` functionality with just references to the api packages, no client packages, & had this working, but dependencies & binary size didn't change much as the api packages require most of the packages listed below.

Wonder if you have any thoughts on this as it could be a barrier to inclusion in other projects?

This is the full list of packages added to godep via `godep save` after adding the client in:

```
code.google.com/p/go-uuid/uuid                                                     
github.com/GoogleCloudPlatform/kubernetes/pkg/api                                  
github.com/GoogleCloudPlatform/kubernetes/pkg/auth/user                            
github.com/GoogleCloudPlatform/kubernetes/pkg/client                               
github.com/GoogleCloudPlatform/kubernetes/pkg/conversion                           
github.com/GoogleCloudPlatform/kubernetes/pkg/fields                               
github.com/GoogleCloudPlatform/kubernetes/pkg/labels                               
github.com/GoogleCloudPlatform/kubernetes/pkg/probe                                
github.com/GoogleCloudPlatform/kubernetes/pkg/runtime                              
github.com/GoogleCloudPlatform/kubernetes/pkg/types                                
github.com/GoogleCloudPlatform/kubernetes/pkg/util                                 
github.com/GoogleCloudPlatform/kubernetes/pkg/version                              
github.com/GoogleCloudPlatform/kubernetes/pkg/watch                                
github.com/GoogleCloudPlatform/kubernetes/third_party/forked/reflect               
github.com/Sirupsen/logrus                                                         
github.com/davecgh/go-spew/spew                                                                                                                                                               
github.com/docker/docker/pkg/mount                                                 
github.com/docker/libcontainer/cgroups                                             
github.com/docker/libcontainer/configs                                             
github.com/docker/libcontainer/system                                              
github.com/ghodss/yaml                                                             
github.com/golang/glog                                                             
github.com/golang/protobuf/proto                                                   
github.com/google/cadvisor/info/v1                                                 
github.com/google/gofuzz                                                           
github.com/hashicorp/consul/api                                                    
github.com/juju/ratelimit                                                          
github.com/julienschmidt/httprouter                                                
github.com/spf13/pflag                                                             
github.com/syndtr/goleveldb/leveldb                                                
golang.org/x/crypto/ssh                                                            
golang.org/x/net/context                                                           
speter.net/go/exp/math/dec/inf
```

**Comment by thockin** [comment]
Our "client" is not really fit for public use at the moment.  It's too
entangled.

**Comment by jimmidyson** [comment]
Yeah that's what I've found out :) What do you suggest? Even the API packages without the client are too entangled & create only a few less package dependencies.

**Comment by thockin** [comment]
We've started to fix it, but that's the best we have right now.

@lavalamp

**Comment by lavalamp** [comment]
I have a series of changes in mind to make this better over time. I'm starting here: https://github.com/GoogleCloudPlatform/kubernetes/pull/11280

The idea is to get (in the next week or so) a pkg/client/v1 that you can safely import, and then over time fix the massive dependency tree with a little refactoring.

**Comment by jimmidyson** [comment]
@lavalamp That sounds great. I'll keep an eye on what you're doing with that PR & look forward to a safe v1 to import. I'm happy to be a guinea pig if you have something you want someone to try out & feed back.

**Comment by lavalamp** [comment]
Great-- I will probably be paying that PR some more attention starting tomorrow or the day after.

**Comment by jimmidyson** [comment]
@lavalamp I have switched to straight `http.Client` & only kubernetes import is `github.com/GoogleCloudPlatform/kubernetes/pkg/api/v1` & this now only ;) has 452 files added to godeps. This PR (prometheus/prometheus#905) to prometheus, which probably won't be merged until you've completed your refactoring, is a pretty good candidate to use to check that the dependencies have drastically reduced.

**Comment by juliusv** [comment]
:+1: :100: Looking forward to the massive dependency reduction so we can integrate Kubernetes node discovery into Prometheus :)

**Comment by ae6rt** [comment]
Thanks for filing this.  This affects work I want to do as well.

There is another aspect to this issue that warrants recording.  If I depend on 

```
k8s.io/kubernetes/pkg/api/v1
```

for the sole purpose of being able to construct, say, Pod structs in memory in preparation for simple JSON serialization across the wire to the k8s master api-server, I cannot cross compile on my Mac a binary targeted at Linux.  There are compile time errors that prevent this:

On my Mac: 

```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o choreo-linux-amd64
# github.com/docker/libcontainer/cgroups
../../../docker/libcontainer/cgroups/utils.go:259: undefined: units.CustomSize
godep: go exit status 2
make: *** [binaries] Error 1
```

So I either have to build the app itself in a Linux container that has the Godeps I want baked in, or stop depending on the api/v1 package and maintain simple facsimiles of the API types that mirror the real k8s types.  Neither of those choices is at all appealing.

Any thoughts on better workarounds?

Thank you.

**Comment by ae6rt** [comment]
My needs around the raw types is modest.  For now I can simply use a Go text template operating on a template-ized slug of literal JSON text in my code.

**Comment by Raffo** [comment]
Could this https://github.com/golang/build/tree/master/kubernetes solve this issue?

**Comment by grobie** [comment]
Any updates?

**Comment by krmayankk** [comment]
I am interested in this change as well to have an absolute minimal go client for kubernetes. Any udpate is appreciate or if there are other community efforts to make a go client which is simpler, i would like to take a look before reinventing the wheeel

**Comment by Raffo** [comment]
@grobie @krmayankk I would expect an update from the community, but it seems we all need some lighter form of a go library for kubernetes. We can start working on this as it seems that the rest of the community is very busy on working on different topics. As inspiration we have some efforts in prometeus and https://github.com/golang/build/tree/master/kubernetes , but we will probably need to start for scratch.

**Comment by bgrant0607** [comment]
See also #5660

**Comment by timstclair** [comment]
Related issue, flag conflict from dependencies: http://stackoverflow.com/questions/37284423/glog-flag-redefined-error/37307780

**Comment by termie** [comment]
tossing in there that even trivial usages of the api cause cross-compile issues frequently due to changes deep in this gigantic dep tree

**Comment by arschles** [comment]
note that https://godoc.org/k8s.io/client-go exists now, and is a dedicated repository for the go client

**Comment by sparrc** [comment]
@arschles, from what I can tell, that repo still has the same problem. for example, [this code](https://gist.github.com/sparrc/62fa9fd1f2eae9d9dba12855459af982) compiles to a 45MB binary 🙁

**Comment by timoreimann** [comment]
@sparrc the number of dependencies was actually  reduced, at least on a [minimalistic kube client of mine](https://twitter.com/timoreimann/status/776429308244090880).

Unexpectedly, the size of the compiled binary *increased* from 30 to 40 Megs for me at the same time.

**Comment by arschles** [comment]
@sparrc yea, I was only referring to dependency size, which as you already saw is not always correlated

**Comment by smarterclayton** [comment]
I think this has been improved enough to close the issue.  Please open more targeted issues as they come up.
