### ISSUE TITLE
Installing kubeadm - 500 error retrieving apt-key.gpg

### ISSUE THREAD

**Issue by AndrewSav** [kubernetes/kubernetes#116096]
On  <https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/> page for Debian based section a command is given 

```
sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
```

as part of the installation process. This actually results in error 500 from the server. (Started happening within last 24 hours). Does the url needs to be updated in the documentation? If yes what is the new one?

**Comment by dims** [comment]
Please see the email thread - https://groups.google.com/a/kubernetes.io/g/dev/c/gR5xDzzIcW8/m/SK5ARWkGAQAJ

Also see workaroung in the thread or here - https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585
