### ISSUE TITLE
Custom Pod Security Standards 

### ISSUE THREAD

**Issue by saiprasanna7** [kubernetes/kubernetes#116085]
We're using EKS v1/.23 and as we all know that Pod Security Policies are getting depreciated. We're planning to adapt Pod Security Admission by enforcing Pod Security Standards. We'd like to know if we can have our own custom pod security standards. 

The current restricted pod security standard is creating some issues and we need to add exceptions per our requirements.

Is there a way we can leverage existing kubernetes pod security admission to achieve this?

**Comment by sftim** [comment]
> Is there a way we can leverage existing kubernetes pod security admission to achieve this?

No. However, see https://kubernetes.io/docs/concepts/security/pod-security-standards/#alternatives

/kind support

**Comment by sftim** [comment]
@saiprasanna7 the Pod Security Standards are intentionally simple. If you want more complex behaviour, you can:
- use [ValidatingAdmissionPolicy](https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/) (alpha)
- use an external policy engine via an admission webhook
- extend Kubernetes and use your own API server that includes your custom admission control mechanism

**Comment by saiprasanna7** [comment]
hi @sftim , thank you for your suggestions, I'm trying to use Kyverno to add exceptions to pod security standards, it is simple but has its own limitations, but so far I think that suits our requirements, but it would be nice if k8s can provide a way to customize pod security standards as they are inflexible.

**Comment by dims** [comment]
@saiprasanna7 please contact your k8s vendor for guidance.
