### ISSUE TITLE
AppArmor validator: Use up to date host info

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#116003]
This issue is created by this @SergeyKanzhelev's [request](https://github.com/kubernetes/kubernetes/pull/115749#issuecomment-1441305000)

Currently AppArmor validator gets host info only [when Validator object is created](https://github.com/kubernetes/kubernetes/blob/master/pkg/security/apparmor/validate.go#L44).
`Validator.ValidateHost` API [uses cached data](https://github.com/kubernetes/kubernetes/blob/master/pkg/security/apparmor/validate.go#L85).

Would it make sense to do it dynamically every time ValidateHost is called? It would help to get the latest AppArmor status, which can be changed if AppArmor kernel module is loaded or unloaded.

**Comment by SergeyKanzhelev** [comment]
KEP xref: https://github.com/kubernetes/enhancements/issues/24

**Comment by SergeyKanzhelev** [comment]
/kind feature
/triage accepted
/sig security 

(adding sig security as well as they co-own a KEP)

**Comment by kidddddddddddddddddddddd** [comment]
seems like this is only one line change?
```
func (v *validator) ValidateHost() error {
	return validateHost()
}
```

**Comment by bart0sh** [comment]
@kidd
> seems like this is only one line change?

correct

**Comment by SergeyKanzhelev** [comment]
> Would it make sense to do it dynamically every time ValidateHost is called? It would help to get the latest AppArmor status, which can be changed if AppArmor kernel module is loaded or unloaded.

How expensive is this check? The result of it is that we will stop admitting pods when it was disabled? Do we need to do anything about already running Pods?


Ideally we want to update files in this PR to describe this behavior: https://github.com/kubernetes/enhancements/pull/3298 (cc @jan0ski).

@tallclair do you see any issues with this change?

**Comment by j0shgrant** [comment]
> How expensive is this check?

@SergeyKanzhelev - it's just doing a stat+read on `/sys/module/apparmor/parameters/enabled` ([here](https://github.com/opencontainers/runc/blob/6d0261c1ac38ff84b4aea73f02383d6d42ebfdfd/libcontainer/apparmor/apparmor_linux.go#L20-L23)), then checking the first byte read, so overall it's pretty snappy. Probably not a super cache-friendly use case; if your node has apparmor config enabled, presumably you'd want that to kick in _now_, rather than sometime soon whilst another pod might sneak in before then.

**Comment by SergeyKanzhelev** [comment]
> so overall it's pretty snappy.

what is it in terms of time? Any delay on pod admission, especially this unnecessary will not be ideal.

> if your node has apparmor config enabled, presumably you'd want that to kick in _now_

I don't care that much about enable AppArmor scenario - one can restart kubelet after this, should not be a big deal. Disable AppArmor scenario is harder. If it was disabled, we may want to stop admitting. But I'm not sure how immediate this should be.

Also if we covering this scenario, we may need to understand how already running Pods will behave if it's disabled. In both cases - disabled and kubelet is still running. And disabled and kubelet being restarted. Should we re-admit Pods?

**Comment by j0shgrant** [comment]
> what is it in terms of time?

For me, locally, it's ~1.3ms, but that's entirely going to depend on the host its running on. If we can't handle a couple of milliseconds at pod admission, we probably shouldn't do this change at all.

> But I'm not sure how immediate this should be.

If we're going to admit a pod with AppArmor config, whilst AppArmor is enabled for the kubelet, I'd imagine we'd want to uphold that guarantee we're giving by admitting said pod? I'd err on the side of it being immediate, assuming we're okay with the added time spent validating the host.

> Should we re-admit Pods?

If we decide we want to provide this relatively strong guarantee that any running pod is aligned with the host + kubelet's config, I'd argue in favour of re-admission.

**Comment by SergeyKanzhelev** [comment]
> > what is it in terms of time?
> 
> For me, locally, it's ~1.3ms, but that's entirely going to depend on the host its running on. If we can't handle a couple of milliseconds at pod admission, we probably shouldn't do this change at all.

I'm trying to think of other implications. Any dependency on pod startup flow is not ideal. I cannot tell how important it is to pick up the change without the kubelet restart. I'd defer for @tallclair for this.

Mechanics of the change are lgtm

**Comment by bart0sh** [comment]
Thanks for the review! closing.
