### ISSUE TITLE
kubelet.service failed

### ISSUE THREAD

**Issue by Ludovicofu** [kubernetes/kubernetes#116129]
### What happened?

[root@master system]# vim /usr/lib/systemd/system/kubelet.service
[root@master system]# journalctl -xeu kubelet
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.044254   20288 dynamic_cafile_content.go:156] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.375897   20288 server.go:693] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.376289   20288 container_manager_linux.go:281] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.376793   20288 container_manager_linux.go:286] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName:
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.376858   20288 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.376892   20288 container_manager_linux.go:321] "Creating device plugin manager" devicePluginEnabled=true
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.376948   20288 state_mem.go:36] "Initialized new in-memory state store"
Feb 28 04:16:20 master kubelet[20288]: I0228 04:16:20.377085   20288 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat
Feb 28 04:16:20 master kubelet[20288]: W0228 04:16:20.377833   20288 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {/var/run/cri-dockerd.sock /var/run/cri-d
Feb 28 04:16:20 master kubelet[20288]: E0228 04:16:20.378005   20288 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: unable to determine runtime API version: rpc error: c
Feb 28 04:16:20 master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Feb 28 04:16:20 master systemd[1]: Unit kubelet.service entered failed state.
Feb 28 04:16:20 master systemd[1]: kubelet.service failed.
Feb 28 04:16:30 master systemd[1]: kubelet.service holdoff time over, scheduling restart.
Feb 28 04:16:30 master systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished shutting down
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished shutting down.
Feb 28 04:16:30 master systemd[1]: Started kubelet: The Kubernetes Node Agent.
-- Subject: Unit kubelet.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has finished starting up.
-- 
-- The start-up result is done.
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.583494   20350 server.go:198] "Warning: For remote container runtime, --pod-infra-container-image is ignored in kubelet, which should b
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.601505   20350 server.go:446] "Kubelet version" kubeletVersion="v1.23.0"
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.601807   20350 server.go:874] "Client rotation is on, will bootstrap in background"
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.604849   20350 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.605827   20350 dynamic_cafile_content.go:156] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676299   20350 server.go:693] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676572   20350 container_manager_linux.go:281] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676671   20350 container_manager_linux.go:286] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName:
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676705   20350 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676717   20350 container_manager_linux.go:321] "Creating device plugin manager" devicePluginEnabled=true
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676753   20350 state_mem.go:36] "Initialized new in-memory state store"
Feb 28 04:16:30 master kubelet[20350]: I0228 04:16:30.676827   20350 util_unix.go:104] "Using this format as endpoint is deprecated, please consider using full url format." deprecatedFormat
Feb 28 04:16:30 master kubelet[20350]: W0228 04:16:30.677180   20350 clientconn.go:1331] [core] grpc: addrConn.createTransport failed to connect to {/var/run/cri-dockerd.sock /var/run/cri-d
Feb 28 04:16:30 master kubelet[20350]: E0228 04:16:30.677290   20350 server.go:302] "Failed to run kubelet" err="failed to run Kubelet: unable to determine runtime API version: rpc error: c
Feb 28 04:16:30 master systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Feb 28 04:16:30 master systemd[1]: Unit kubelet.service entered failed state.
Feb 28 04:16:30 master systemd[1]: kubelet.service failed.

### What did you expect to happen?

kubelet.service success

### How can we reproduce it (as minimally and precisely as possible)?

emmm....

### Kubernetes version

<details>

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux master 6.2.1-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb 23 18:33:40 EST 2023 x86_64 x86_64 x86_64 GNU/Linux




</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
please use newest versions of containerd or CRI-o
