### ISSUE TITLE
OpenEluer system start firewalld ping pods error after installed k8s

### ISSUE THREAD

**Issue by liyin37** [kubernetes/kubernetes#116169]
### What happened?

[root@master01 ~]# kubectl -n ingress-apisix get po -owide
NAME                                         READY   STATUS             RESTARTS         AGE    IP            NODE       NOMINATED NODE   READINESS GATES
apisix-58666bdbc9-jzr97                      0/1     CrashLoopBackOff   23 (41s ago)     7d5h   10.244.1.24   master02   <none>           <none>
apisix-58666bdbc9-kqfmx                      0/1     Error              23 (5m19s ago)   7d5h   10.244.1.19   master02   <none>           <none>
apisix-58666bdbc9-m59w5                      0/1     CrashLoopBackOff   23 (29s ago)     7d5h   10.244.1.17   master02   <none>           <none>
apisix-dashboard-7f6cdd88bd-c4v8v            0/1     CrashLoopBackOff   24 (2m21s ago)   7d5h   10.244.1.20   master02   <none>           <none>
apisix-etcd-0                                1/1     Running            1 (45m ago)      7d5h   10.244.0.17   master01   <none>           <none>
apisix-etcd-1                                1/1     Running            1 (45m ago)      7d5h   10.244.1.25   master02   <none>           <none>
apisix-etcd-2                                1/1     Running            1 (45m ago)      7d5h   10.244.2.23   master03   <none>           <none>
apisix-ingress-controller-5764b6dcf8-tg72t   0/1     Init:0/1           0                7d5h   10.244.1.26   master02   <none>           <none>
[root@master01 ~]# ping  10.244.1.19 
PING 10.244.1.19 (10.244.1.19) 56(84) 字节的数据。
来自 10.244.1.0 icmp_seq=1 数据包被过滤
来自 10.244.1.0 icmp_seq=2 数据包被过滤
来自 10.244.1.0 icmp_seq=3 数据包被过滤
来自 10.244.1.0 icmp_seq=5 数据包被过滤

### What did you expect to happen?

when I  start the firewalld service
[root@master01 ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
     Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-03-01 17:07:03 CST; 48min ago
       Docs: man:firewalld(1)
   Main PID: 761 (firewalld)
      Tasks: 3 (limit: 47181)
     Memory: 39.9M
     CGroup: /system.slice/firewalld.service
             └─ 761 /usr/bin/python3 -s /usr/sbin/firewalld --nofork --nopid

3月 01 17:07:07 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-67c70ac02184 -o br-67c70ac02184 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:07:08 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:07:10 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:21 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-67c70ac02184 -o br-67c70ac02184 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:21 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:22 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:25 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -t filter -A DOCKER ! -i br-67c70ac02184 -o br-67c70ac02184 -p tcp -d 172.18.0.3 --dport 8443 -j ACCEPT' failed: iptables: No chain/target/match by that name.
3月 01 17:47:25 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i br-67c70ac02184 -o br-67c70ac02184 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:25 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).
3月 01 17:47:26 master01 firewalld[761]: WARNING: COMMAND_FAILED: '/usr/sbin/iptables -w10 -D FORWARD -i docker0 -o docker0 -j DROP' failed: iptables: Bad rule (does a matching rule exist in that chain?).

the open port is blow:
[root@master01 ~]# firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens33
  sources: 
  services: dhcpv6-client mdns ssh
  ports: 22/tcp 53/udp 80/tcp 123/udp 443/tcp 2379-2380/tcp 6443/tcp 7946/tcp 7946/udp 7472/tcp 8472/udp 9100/tcp 10250-10256/tcp 30000-32767/tcp 30000-32767/udp 15010-15014/tcp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 

### How can we reproduce it (as minimally and precisely as possible)?

no

### Anything else we need to know?

no

### Kubernetes version

<details>

```console
[root@master01 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.14", GitCommit:"bccf857df03c5a99a35e34020b3b63055f0c12ec", GitTreeState:"clean", BuildDate:"2022-09-14T22:41:51Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.14", GitCommit:"bccf857df03c5a99a35e34020b3b63055f0c12ec", GitTreeState:"clean", BuildDate:"2022-09-14T22:36:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
vmware system hosts
</details>

### OS version

<details>

```console
# On Linux:
[root@master01 ~]# cat /etc/os-release
NAME="openEuler"
VERSION="22.03 (LTS-SP1)"
ID="openEuler"
VERSION_ID="22.03"
PRETTY_NAME="openEuler 22.03 (LTS-SP1)"
ANSI_COLOR="0;31"
# paste output here
[root@master01 ~]#  uname -a
Linux master01 5.10.0-136.12.0.86.oe2203sp1.x86_64 #1 SMP Tue Dec 27 17:50:15 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
# paste output here

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
we have no experience in OpenEuler and do not use it in any of our CI systems.

https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

**Comment by liyin37** [comment]
I solved，use blow command:
firewall-cmd --permanent --zone=kubernetes_pods --add-source=<POD SUBNET CIDR>
