### ISSUE TITLE
kmsv2: collect metrics and log when a resource decryption call fails

### ISSUE THREAD

**Issue by ritazh** [kubernetes/kubernetes#116194]
Metric:
Today we have the `transformation_operations_total` counter metric that collects "transformation_type", "transformer_prefix", "status" which could be used to alert on decrypt, status is fail. Need to test this and perhaps it's just a documentation thing. If not, we need to add.

Log:
Today we just return error all the way through, we may not be actually logging the resource associated with the decryption call.

**Comment by nikzayn** [comment]
@ritazh I would like to work on this. Can I take this up?
