### ISSUE TITLE
Pod is running, but cannot allocate devices when the pod start before device plugin register right to kubelet

### ISSUE THREAD

**Issue by chaohan1** [kubernetes/kubernetes#116125]
### What happened?

A pod using gpu in our k8s cluster, when we delete kubelet_internal_checkpoint and restart the node where the pod is located. After the node start normally, we find that, the pod is running, but the gpu device is not mounted on the container of pod. If we delete container of the pod, the gpu device mount normally.
I think the reason is that the pod is start befor gpu device register right to kubelet.

### What did you expect to happen?

The pod should not be running when device plugin not register to kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

1. a pod uses device such as gpu;
2. delete kubelet_internal_checkpoint;
3. reboot node;
4. check the device is mounted normally or not;

### Anything else we need to know?

 In the function  allocateContainerResources,  if isDevicePluginResource return false, kubelet will skip device allocation, however, if the device plugin not register right to kubelet and the kubelet_internal_checkpoint is lost, the function isDevicePluginResource will reture false, and generate the problem report.
      `func (m *ManagerImpl) allocateContainerResources(pod *v1.Pod, container *v1.Container, devicesToReuse map[string]sets.String) error {
	podUID := string(pod.UID)
	contName := container.Name
	allocatedDevicesUpdated := false
	// Extended resources are not allowed to be overcommitted.
	// Since device plugin advertises extended resources,
	// therefore Requests must be equal to Limits and iterating
	// over the Limits should be sufficient.
	for k, v := range container.Resources.Limits {
		resource := string(k)
		needed := int(v.Value())
		klog.V(3).Infof("needs %d %s", needed, resource)
		if !m.isDevicePluginResource(resource) {
			continue
		}
		// Updates allocatedDevices to garbage collect any stranded resources
		// before doing the device plugin allocation.
		if !allocatedDevicesUpdated {
			m.UpdateAllocatedDevices()
			allocatedDevicesUpdated = true
		}
		allocDevices, err := m.devicesToAllocate(podUID, contName, resource, needed, devicesToReuse[resource])`

### kbernetes version
<details>

```console
$ kubectl version
[root@master1 test]# kubectl version
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v1.19.4-20220624+f4db2d9438dda779fe1c428dd2236ab11324a4c7", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4-20220919+70739902f480e601089fca048abbf8e0c08c4df8", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
No
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ffromani** [comment]
this seems another occurrence of https://github.com/kubernetes/kubernetes/issues/109595

**Comment by ffromani** [comment]
> this seems another occurrence of #109595

the thing is: deleting the checkpoint file is not supported. The checkpoint file is kubelet private data managed by the kubelet. Once the kubelet state is tampered, the behavior becomes undefined.

I still think #109595 can somehow be related. If removing the checkpoint was meant as a fix to solve the actual problem please file another issue describing the problem itself.

**Comment by ffromani** [comment]
/close

for the reasons described above, I don't think this flow is valid and thus this is a bug.
That said, there _could_ totally be a bug in the recovery flow. Please check the linked issue.
