### ISSUE TITLE
1 node(s) had untolerated taint

### ISSUE THREAD

**Issue by lreis09** [kubernetes/kubernetes#116133]
### What happened?

Hi, i have a problem when i launch a pod the state of the pod is pending.
The command "kubectl describe pods apache-7f6fddb7df-q229r" and the output is " Warning  FailedScheduling  61s (x2 over 6m23s)  default-scheduler  0/1 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.."
Logs of the pod is none, the service kubelet, docker and containerd is running without any errors.
Journalctl not giving me anything.
My OS is Debian 11

### What did you expect to happen?

I expected the state pod is running.
Please help me and thanks for the help.

### How can we reproduce it (as minimally and precisely as possible)?

Install docker and kubernettes by the documentations.

### Kubernetes version

<details>
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.26.1
</details>

### Cloud provider

<details>
Local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux docker 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tzneal** [comment]
The error message is indicating why that pod won't schedule.  

> 1 node(s) had untolerated taint {node-role.kubernetes.io/control-plane: }.

Your pod doesn't have a toleration for the taint on the one node in your cluster, so it won't schedule there. You can either remove the taint on the node, or add a toleration to the pod. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info.

/kind support

**Comment by lreis09** [comment]
I'm sorry but the cluster is not tainted and a toleration is not working.
I'm just running the command "kubectl create deployment apache --image=httpd"
and is stuck pending.

**Comment by tzneal** [comment]
The scheduler is indicating that the one node in your cluster is tainted. Can you run `kubectl describe node`, and see if there is a Taint listed?

**Comment by gregth** [comment]
Hi @lreis09, As @tznel mentioned, the logs indicate that the node has a `node-role.kubernetes.io/control-plane:NoSchedule` taint. 

This is a well-known taint, that indicates the node is a part of K8s control plane, see https://kubernetes.io/docs/reference/labels-annotations-taints/#node-role-kubernetes-io-control-plane-taint. If you describe the node, the taint shall be there.

**Comment by ollyde** [comment]
There's a bug in K8, when making a deployment with node selector, then removing that deployment and selector; the selector will not vanish. Even when the namespace is fully deleted.
