### ISSUE TITLE
When requesting `cpu: "1.2"`, then `kubectl apply` always shows "configured" in output

### ISSUE THREAD

**Issue by dmlundeby** [kubernetes/kubernetes#116135]
### What happened?

When creating a deployment and requesting `cpu`, then there are some cases when the output of `kubectl apply` (when doing it more than once) shows `configured` rather than `unchanged`:

Examples:

* `cpu: "1.2"` (but `"1200m"` works fine)
* `cpu: "1000m"` (but `"1"` works fine)

The error seems to occur when the `cpu` format is not as expected.

~~This is an issue when we request `cpu`, but not when we request `memory`.~~ This is also an issue when requesting `memory`.

### What did you expect to happen?

The output of `kubectl apply` should be:

`"... unchanged"`

### How can we reproduce it (as minimally and precisely as possible)?

deployment.yaml:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:1.36
        resources:
          requests:
            cpu: "1.2"
```

Then, apply the deployment more than once:

```console
$ kubectl apply -f deployment.yaml
deployment.apps/busybox-deployment created
$ kubectl apply -f deployment.yaml
deployment.apps/busybox-deployment configured
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
I've seen this in Minikube and Google Cloud
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
cc @apelisse 

/sig api-machinery

**Comment by apelisse** [comment]
The quantity field can take different forms, is normalized by the apiserver, and always stored (and served) in the same format. If the format you use in your manifest is different from the normalized form, then we will think you change it everytime, there isn't much we can do about that (at least not easily).

Possibly, as long as kubectl uses client-side apply by default and grabs a copy of the object, we could see if the object has changed by diffing the resourceVersion, as opposed to today, we just see if a patch is sent to the server.

Can you elaborate on what problem that causes?

**Comment by sftim** [comment]
Two things that could help here:
- `kubectl` could show which fields were normalized and how:
  ```
  CPU request normalised to "1200m"
  ```
  (for example)
- `kubectl` could use its knowledge of the API to send a fully specified intent that was already normalized client side, and have an option to skip that normalization. Quantity is a good example of where some awareness of the API by the client could help, because the server end treats these values specially.

**Comment by sftim** [comment]
Oh, and:
- how about a plugin, `kubectl normalize`, that works on manifests and apply intents, and normalizes them based on a server's OpenAPI

**Comment by apelisse** [comment]
Wait, you're assuming kubectl knows about the normalization, which it doesn't.

**Comment by dmlundeby** [comment]
Thanks for reacting quickly!

I think the main problem here is consistency. `kubectl diff` shows no difference, while `kubectl apply` tells me some change has happened. This made me concerned - I was told something had changed, but I could not see what it was. I spent quite some time troubleshooting what caused this.

**Comment by sftim** [comment]
If this _is_ a kubectl issue, we can move it to the kubectl issue tracker.

**Comment by dmlundeby** [comment]
Is this something I should decide and/or do?

**Comment by apelisse** [comment]
> Is this something I should decide and/or do?

No, I, myself, can't say if it's a kubectl or  apimachinery problem, or both or neither.
