### ISSUE TITLE
General Validation Cleanup for Jobs

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#116137]
@thockin pointed out in a review that the way we generate selectors for the Job controller is a bit odd.

https://github.com/kubernetes/kubernetes/pull/114930#pullrequestreview-1316052164

/kind cleanup
/sig apps

**Comment by thockin** [comment]
Copying here for simplicty:

Problem 1:  `Validate` calls `generateSelector`  which adds labels.  This is wrong - `Validate` is not supposed to modify objects!  This should be done from `PrepareFor*` hooks instead.  A side-effect of this is that any update operation will set these labels, which seems like a benefit but is hidden in a place I would NEVER think to look.

I would retool all of this.  `PrepareForCreate` should call `generateSelectorIfNeeded`, which checks the `manual` flag and sets the labels.  It's not clear to me whether that should happen from `PrepareForUpdate` or not.  It's easy, but a bit unusual (to set unrelated fields) and low-value (I think).

Problem 2: `Validate` says `if job.Spec.ManualSelector == nil || *job.Spec.ManualSelector == false` - this is wrong.  That field should be recognized as `nil` in pkg/apis/batch/v1/defaults.go and assigned a value.  You should not be nil-checking fields all over the place and inferring their default values.  It seems innocuous on a bool, but imagine an int or string field - you'd have the default value sprinkled all over the codebase.

This could be 2 distinct PRs

**Comment by dejanzele** [comment]
Hi all,

This looks like a good first issue, I'll be more than happy to take a stab at it.

/assign dejanzele

**Comment by thockin** [comment]
The Validate vs. PrepareForCreate part should be straight forward (will need tests).

The defaults parts may require other test cases to be updated so that the field is never nil - not hard but may be a bit tedious. :)

**Comment by dejanzele** [comment]
Hello @thockin,

Sorry for the delay, I finally want to dedicate time to do the cleanup which you have mentioned in a comment above.

I will follow your advice and create 2 separate PRs.

First one I have created is about extracting the `generateSelector` method.
