### ISSUE TITLE
ToC Munger not exactly the same as github bookmarks

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#11614]
Strip disallowed characters such as `=` from heading, prior to converting to bookmark name.

**Comment by mikedanese** [comment]
Can you give an example? the munger strips all chars that match `'[A-Za-z0-9-]'` from bookmarks which should include `=`

**Comment by erictune** [comment]
#11611

**Comment by JanetKuo** [comment]
It should be solved by #11420

**Comment by mikedanese** [comment]
Ya, it should be fixed on github markdown at least. #11611 bookmarks work on github markdown before and after. Was it not working on k8s.io?

**Comment by JanetKuo** [comment]
@mikedanese I found that on k8s.io, the bookmark of `Type = LoadBalancer` should be `#type-loadbalancer` instead of `#type--loadbalacer`

Looks like it works differently on github markdown versus k8s.io

**Comment by bgrant0607** [comment]
@johndmulhausen Any idea whether this is still an issue?
