### ISSUE TITLE
unstable map iteration order causes test to sometimes leave non-GA features disabled

### ISSUE THREAD

**Issue by alexzielenski** [kubernetes/kubernetes#116151]
### What happened?

PR https://github.com/kubernetes/kubernetes/pull/115324 was reverted by #116062 because it (erroneously) relied on OpenAPIV3 feature to be enabled, but `TestPodSecurityGAOnly` would non-deterministically leave the feature disabled after running.

I tracked it down to the fact that this test disables all `PreRelease` or `Beta` features in a loop which iterates over a `map`, which are known to have unstable iteration order:
https://github.com/kubernetes/kubernetes/blob/e55f2a9b54e0f6bd9ed12e50752d7d2545ab0cab/test/integration/auth/podsecurity_test.go#L74-L81

When key `AllBeta` is processed before key `OpenAPIV3`, then `AllBeta` would disable `OpenAPIV3` before `OpenAPIV3`s default value is to be saved.

Normally, `AllBeta` ignores features that have been explicitly set, so it only affects those which fall back on the `Default` value. But this issue does not just affect `OpenAPIV3` but any non-GA feature.

I suggest the loop in `TestPodSecurityGAOnly` be made to skip the special feature keys such as `AllBeta`.

/cc @liggitt 
/cc @apel

### What did you expect to happen?

The value before every feature gate should be restored after running `TestPodSecurityGAOnly`.

### How can we reproduce it (as minimally and precisely as possible)?

This test always fails on my machine (just pasted it into `test/integration/auth/podsecurity_test.go`):

```go
func TestRestoreFeatures(t *testing.T) {
	var targetFeature featuregate.Feature

	// Grab a beta feature form the list to test with
	for k, v := range utilfeature.DefaultMutableFeatureGate.GetAll() {
		if v.PreRelease == featuregate.Beta && v.Default {
			targetFeature = k
			break
		}
	}

	if len(targetFeature) == 0 {
		t.Log("no beta features to test against")
		return
	}

        // see if we iterate the feature map with AllBeta first within a few tries
	for i := 0; i < 10; i++ {
		attemptFunc := func() bool {
			fg := utilfeature.DefaultFeatureGate.DeepCopy()
			originalValue := fg.Enabled(targetFeature)

			func() {
				// Disable all alpha and beta features
				for k, v := range fg.DeepCopy().GetAll() {
					if v.PreRelease == featuregate.Alpha || v.PreRelease == featuregate.Beta {
						defer featuregatetesting.SetFeatureGateDuringTest(t, fg, k, false)()
					}
				}
			}()

			return originalValue != fg.Enabled(targetFeature)
		}

		if attemptFunc() {
			t.Fatal("original value for feature not same as new value after restoration")
			break
		}
	}
}
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Wow, good catch, sorry to make you track down what turned out to be a bug in our test 😞
