### ISSUE TITLE
Kubelet client certificate has a different validity in multi master cluster.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#116193]
### What happened?

Hi, I have tried changing the constant variable CerificateValidity which is 1yr in Kubeadm to 10yrs.

Deployed multinode cluster, in primary cp node, can see kubelet client certificate (/var/lib/kubelet/pki/kubelet-client-current.pem) has a validity of 10yrs but in other node has a validity of 1yr.

In my understanding, kubelet should have 1yr of validity right? as kubeadm is not resposible/manage for kubelet internal certificate. 

### What did you expect to happen?

kubelet should have 1yr of validity in all nodes in cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Change certificate validity constant in kubeadm to 10yrs and deploy kubernetes multinode cluster, and check the validity of kubelet client ceritifcate in all nodes.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a
Linux ubunturms102 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> Deployed multinode cluster, in primary cp node, can see kubelet client certificate (/var/lib/kubelet/pki/kubelet-client-current.pem) has a validity of 10yrs but in other node has a validity of 1yr.

changing the kubeadm cert expiration constant is not recommended. 

during bootstrap. for kubeadm init, kubeadm must sign the kubelet cert manually. for join, it uses the kubelet setting of 1 year. this process is by design.

IIRC, the kubelet setting one year is not customizable.

you can just leave the kubelet to auto rotate certs each year (default) or sign them manually, like "kubeadm init phase kubeconfig kubelet" and then "kubeadm init phase kubelet-finalize"

**Comment by neolit123** [comment]
pleae use slack #kubeadm for further questions
