### ISSUE TITLE
Indexed Jobs with high completion counts kill kubelet's performance

### ISSUE THREAD

**Issue by PaulFurtado** [kubernetes/kubernetes#116159]
### What happened?

An indexed job with 6,000 completions and a parallelism of 20 was run. The majority of those pods landed on a single node. Since kubelet watches all pods that belong to the node, it had to keep those 6,000 pods in memory and loop through them in its control loops. This makes it take unreasonably long for new pods to start up on the node, and causes other node scalability issues.

### What did you expect to happen?

I expect Indexed Jobs to scale one way or another. There seems to be a lot of room for improvement here though.

For starters, I don't think that indexed jobs need to keep pods around in the API for state tracking since the status field of indexed jobs records the completed indexes. If indexed jobs cleaned up pods while actively running, they could scale to infinite numbers of completions without straining the kube API or kubelet.

Additionally, I'd expect kubelet to be able to handle large numbers of Completed pods gracefully. As I understand it, kubelet keeps an eye on completed pods to enable you to do `kubectl logs`, etc to debug why the pod succeeded or failed. In an ideal world, kubelet might have a setting for the maximum number of completed pods to leave on disk (similar to the old max dead containers per pod type settings). With a setting like this, it could leave the pods in the API for the job's state tracking, but stop doing any work on them. Alternatively, maybe a separate control loop could deal with completed pods so that the main kubelet control loop doesn't slow down.

### How can we reproduce it (as minimally and precisely as possible)?

Create an Indexed Job with:
- A container that just runs something like `/bin/true`
- A selector that ties its pods to a single node
- A high number of completions (like 6,000 for example)

After a while, you will notice kubelet slowing to a crawl.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"archive", BuildDate:"2023-02-22T20:50:03Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS (not EKS)
</details>

### OS version

<details>

```console
# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

</details>

### Install tools

<details>
Custom
</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-o 1.23.4
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by PaulFurtado** [comment]
I assigned this to sig/node for starters since I think it is a bug that kubelet performance gets so bad due to the completed pods. The request that indexed jobs track state without relying on completed pods sounds like it would belong to sig/apps, but that is more of a feature request than a bug. sig/scalability could also be interested in this too. Feel free to reassign if you see fit.

**Comment by larryck** [comment]
Like the idea of cleaning up succeeded pods during job running time. And I also think there might be performance problems when delete 6000 or more pods at the same time.

**Comment by sftim** [comment]
It sounds to me as if the issue was that the kube-controller-manager was making new Pods (on behalf of the Job) faster than it could clean up the existing ones.

Maybe the Job controller should limit the total number of Pods (including completed Pods) that it leaves in the API. For example, have no more than ( `parallelism` ×  _e_ ) Pods that are either successful or running. But&hellip; I also think that current Kubernetes already does it better than v1.23 Kubernetes.

**Comment by sftim** [comment]
I also wonder: should the scheduler take the number of _finished_ Pods on a node into account, when picking where to place work? Those finished Pods do impose an overhead.

**Comment by PaulFurtado** [comment]
> It sounds to me as if the issue was that the kube-controller-manager was making new Pods (on behalf of the Job) faster than it could clean up the existing ones.

@sftime That's not what happened here. When you're running an Indexed Job, the job will currently use the completed pods in order to track its state. You actually cannot delete the completed pods or the job will think it needs to rerun the pod for that index.

Put in other words: if you have an Indexed Job with concurrency set to 20 pods and completions set to 6000, all 6000 pods must remain in the API in the completed state until the entire job finishes even though only 20 pods are running at the same time.

One of my suggestions above was to make the indexed job rely on the data in its status field instead of the pods in the API, and add a setting to enable it to cleanup completed pods while the job is running. For indexed jobs to be practical, I think this is critically important, because those completed pods can get cleaned up for so many other reasons (such as a node termination, autoscaling, evictions, etc).

> I also wonder: should the scheduler take the number of _finished_ Pods on a node into account, when picking where to place work?

I don't think it is actually reasonable to do this because of cost. Consider our case where the job was running 20 pods in parallel with 6000 completions: if you capped the completed pods for a node at, say, 100, we would end up needing 60 nodes to run the job because the autoscaler would be scaling up new nodes to accommodate the completed pods.

> Those finished Pods do impose an overhead.

I wonder if the majority of this overhead can be eliminated:
- hanging onto 6,000 pods does eat some memory, but that should only be a problem in very memory constrained environments
- hanging onto those completed containers and their logs inside of the container runtime impacts the runtime and disk usage, but kubelet should be able to clean up these finished containers on disk (while leaving them in the API) once the number of them crosses some threshold. This might disappoint users who are trying to get the logs for these completed containers, but it's very similar to a pod eviction scenario: the node needs to protect itself
- kubelet itself slowing to a crawl when it is watching 6,000 pods feels like a solvable problem: it must be doing unnecessary work for the completed pods or have some quadratic behavior. Even if whatever it is doing is actually necessary, I feel like kubelet can deal with the finished pods on a separate thread to avoid impacting the active ones.

**Comment by larryck** [comment]
What about ”NonIndexed“ Jobs？I think they may have the same problem.

**Comment by sftim** [comment]
> When you're running an Indexed Job, the job will currently use the completed pods in order to track its state. You actually cannot delete the completed pods or the job will think it needs to rerun the pod for that index.

https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods describes a mechanism to allow Kubernetes to track Pods for a Job _without_ lingering. And that KEP is implemented (although the KEP metadata are stale).

If a non-indexed job causes a performance challenge, our top workaround that is to make the job indexed. We might still be able to tune the kubelet's performance, and make further changes to avoid so many completed Pods being associated with one node.

**Comment by liggitt** [comment]
> When you're running an Indexed Job, the job will currently use the completed pods in order to track its state. You actually cannot delete the completed pods or the job will think it needs to rerun the pod for that index.

@alculquicondor is that accurate? I thought that was resolved with JobTrackingWithFinalizers (which was beta in 1.23)

**Comment by alculquicondor** [comment]
Please upgrade to 1.25, or enable JobTrackingWithFinalizers if you have access to the control plane configuration.

While the feature was beta in 1.23, it was disabled by default after we found some bugs.

> What about ”NonIndexed“ Jobs？I think they may have the same problem.

Correct, this is independent of the completionMode. But Indexed Jobs are actually faster to process with finalizers.

/close

**Comment by alculquicondor** [comment]
/reopen

I guess there is still room for improvement in kubelet, as the pods would not be removed immediately, even with JobTrackingWithFinalizers.

Another thing you can do on your side (if you have access to the control plane configuration) is reduce the terminated-pod-gc-threshold in kube-controller-manager, after enabling JobTrackingWithFinalizers.

**Comment by SergeyKanzhelev** [comment]
/cc @harche 

This will be a good test case for Evented PLEG KEP as well.
