### ISSUE TITLE
Trouble fetching APT signing key for Google package repository

### ISSUE THREAD

**Issue by dikshanthasbe** [kubernetes/kubernetes#116100]
Below command showing error 500...
sudo curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg

**Comment by sftim** [comment]
> @dikshanthasbe Please see work around with new URL here: [kubernetes/k8s.io#4837 (comment)](https://github.com/kubernetes/k8s.io/pull/4837#issuecomment-1446426585)

/triage duplicate
