### ISSUE TITLE
[Flake] goroutine leak detection flaking

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#116196]
``` 
E0301 22:07:04.127341   82193 etcd.go:212] "EtcdMain goroutine check" err=<
	found unexpected goroutines:
	[Goroutine 11523 in state sleep, with time.Sleep on top of the stack:
	goroutine 11523 [sleep]:
	time.Sleep(0x1a13b8600)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.1.linux.amd64/src/runtime/time.go:195 +0x135
	k8s.io/kubernetes/vendor/k8s.io/utils/clock.RealClock.Sleep(...)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/utils/clock/clock.go:135
	k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease.(*controller).backoffEnsureLease(0xc0083845a0)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease/controller.go:148 +0x95
	k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease.(*controller).sync(0xc0083845a0)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease/controller.go:119 +0xf6
	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00925dec8?)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x3e
	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc008b8cf80?, {0x5a3bfe0, 0xc00264ef60}, 0x1, 0xc007a53da0)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0xb6
	k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x47d105?, 0x2540be400, 0x3fa47ae147ae147b, 0x90?, 0xc004b16600?)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x89
	k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease.(*controller).Run(0xc000d6eb40?, 0xc007a53da0?)
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/component-helpers/apimachinery/lease/controller.go:100 +0x57
	created by k8s.io/kubernetes/pkg/controlplane.completedConfig.New.func2
		/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/pkg/controlplane/instance.go:512 +0x1d3
	
	]
```

looks like these started getting sporadically caught with the new detection in https://github.com/kubernetes/kubernetes/pull/115456

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=found%20unexpected%20goroutines

/cc @pohly
/sig testing api-machinery

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/116052#issuecomment-1451033696_

**Comment by pohly** [comment]
At first glance this looks like a real leak. Before https://github.com/kubernetes/kubernetes/pull/115456, a few leaked goroutines were okay. Now it's very strict.

I'll check in more detail later.

**Comment by pohly** [comment]
The lease controller is sleeping without considering the stop channel:
https://github.com/kubernetes/kubernetes/blob/b6d102d634d357600bc0fcb076395c88caef6acb/staging/src/k8s.io/component-helpers/apimachinery/lease/controller.go#L147-L148

This could be fixed by passing the `stopCh` through the functions, but really the right approach is to change the API to take a `ctx` and pass that through. Then that code can be converted to contextual logging, either now or in the future.

I'm leaning towards touching it only once:
- `stopCh` -> `ctx`
- stop everything once `ctx` is canceled
- use contextual logging

But the API change has implications in other places?

**Comment by pohly** [comment]
/reopen

Let's check in a few days that it's really gone...

**Comment by pohly** [comment]
No more failures in the last five days since the PR merged. Seems to have worked.

/close
