### ISSUE TITLE
Need assistance for watching resources on remote OCP cluster.

### ISSUE THREAD

**Issue by pdumbre** [kubernetes/kubernetes#116250]
As a requirement, we need to keep track of resources created on remote OCP cluster from local ocp cluster..so need to understand if thats possible.

**Comment by tzneal** [comment]
Hi, this seems like a support request.  

Please see: https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md 

You should be able to access the API using a client from anywhere that you can hit the API server endpoint.

/kind support
/close
