### ISSUE TITLE
Let K8s workload(deployment,sts,etc.) support In-place Pod Vertical Scaling feature

### ISSUE THREAD

**Issue by FengyunPan2** [kubernetes/kubernetes#116214]
### What would you like to be added?

Let K8s workload(deployment,sts,etc.) support In-place Pod Vertical Scaling feature,
we can update all the pods of workloa, or rolling update them,.

### Why is this needed?

We usually need to update all pods of the workload, not a pod.

If kubelet evict the pod or rescheduler the pod, pod would be restored to the original containers.resources.xxx, that's terrible.

**Comment by FengyunPan2** [comment]
/sig apps

/assign @vinaykul

@vinaykul can you please take a look.

**Comment by FengyunPan2** [comment]
From https://github.com/kubernetes/kubernetes/pull/102884

**Comment by wu0407** [comment]
https://github.com/kubernetes/kubernetes/issues/9043

**Comment by wenzhaojie** [comment]
@vinaykul I am interested in this issue too. Could you please tell me about it? Thanks!

**Comment by LavenderQAQ** [comment]
@FengyunPan2 I will prepare in [OpenKruise Workload](https://github.com/openkruise/kruise/issues/1212) to achieve some workload, and submit KEP after fully prepared.

**Comment by GreyBalloonYU** [comment]
Has this feature been developed yet? I can't wait to use it!
