### ISSUE TITLE
test cleanup needed: cloud-provider/controllers/service/controller_test.go

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#116260]
Similar to #114511

Table-driven tests are awesome, but they can be very verbose and obscure what's actually being tested in each case.

I started on cleaning up staging/src/k8s.io/cloud-provider/controllers/service/controller_test.go, but I only did two tests - there are more.  This is a good opportunity for someone to read some code, so some cleanup, and score a PR or two towards org membership or similar :)

https://github.com/kubernetes/kubernetes/pull/116259

I did: 

https://github.com/kubernetes/kubernetes/commit/3d63aed2dca23bfec17c174b32b63c0be511fe85

after that, it was obvious we have redundant test cases:

https://github.com/kubernetes/kubernetes/commit/b5e4bbb132d0d6c4079e5c98a3bb8ab6e88be381

**Comment by czybjtu** [comment]
hi, I want to be in charge of cleaning up `staging/src/k8s.io/cloud-provider/controllers/node/node_controller_test.go` and `staging/src/k8s.io/cloud-provider/controllers/nodelifecycle/node_lifecycle_controller_test.go`.
Do I need to create a new issue to track this?

**Comment by thockin** [comment]
In general, no, not for something like this.  That said, start small and
make sure you're on the right track by getting review early.

**Comment by mowangdk** [comment]
@thockin I would like to take this.

**Comment by mowangdk** [comment]
@thockin I looked at the code in staging/src/k8s.io/cloud-provider/controllers/service/controller_test.go. I don't know if I understand it correctly. The node helper func is already written on your pr(but in draft?), I just need to add other helper func, I don't need to rewrite the node helper func again?

**Comment by thockin** [comment]
If you want to start with my commits as a base, you can start to use them
in the rest of the file

**Comment by mowangdk** [comment]
> If you want to start with my commits as a base, you can start to use them in the rest of the file

Okay, I'll bring some of the changes from your PR into mine
