### ISSUE TITLE
Provide the checksum files separately for kubernetes cli 

### ISSUE THREAD

**Issue by patrickdung** [kubernetes/kubernetes#116268]
### What would you like to be added?

It is not a bug.. so I put it in this category.

I would like to see the checksum files are provided separately for the Kubernetes cli 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md#client-binaries

Then you can use programs to compare the binary and the checksum more easily.
Currently the checksums are provided as a HTML table (next to the binary).

Thanks.

### Why is this needed?

Then you can use programs (scripts, ansible, etc.) to compare the binary and the checksum more easily.

**Comment by nikzayn** [comment]
@patrickdung I would like to take this up. Can you brief me a bit more about this issue?

**Comment by patrickdung** [comment]
@nikzayn 

Currently, if you browse 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.26.md#client-binaries to download the kubectl binary
On the left hand side is the URL for the binaries.
On the right hand side is the sha512 checksum.
![image](https://user-images.githubusercontent.com/38665827/222893692-e447915e-eb29-466e-a652-11132c40b59b.png)

What I suggest is to provide the checksum files separately.
Examples:
https://github.com/helm/helm/releases/tag/v3.11.1
They provide the checksum file separately, like:
https://get.helm.sh/helm-v3.11.1-darwin-amd64.tar.gz.sha256sum

**Comment by nikzayn** [comment]
@patrickdung I have raised a PR related to this issue. Please have a look so I can clean it up if there were any issues. Here's the link for the same: [116307](https://github.com/kubernetes/kubernetes/pull/116307 )

**Comment by saschagrunert** [comment]
@patrickdung have you checked out https://www.downloadkubernetes.com ? 

We provide checksums for certain files, for example https://dl.k8s.io/v1.28.1/bin/darwin/amd64/kubectl.sha256

**Comment by patrickdung** [comment]
@saschagrunert 

ok, would the URL 'https://www.downloadkubernetes.com/' be put on the github release notes? Besides that, I haven't heard of https://www.downloadkubernetes.com/
Is it an official site?

But the checksum like https://dl.k8s.io/v1.28.1/bin/darwin/amd64/kubectl.sha256 is ok.

**Comment by saschagrunert** [comment]
@patrickdung we're planning to integrate the domain into the official kubernetes website, per https://github.com/kubernetes-sigs/downloadkubernetes/issues/82

Yes, the project is part of kubernetes-sigs, so it's an officially supported website.

**Comment by pacoxu** [comment]
It sounds like this can be closed.
/close

Further, we may track it at https://github.com/kubernetes-sigs/downloadkubernetes/issues/82.

Feel free to reopen if I close it wrongly.
