### ISSUE TITLE
VPA panics in standalone kubelets

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#116262]
1. Start a standalone kubelet (not registered to an API server)

2. Manager construction short-circuits `Start()` here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L186-L192

3. VPA state is never initialized here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L195-L200

4. All pod syncs then panic on this line:

https://github.com/kubernetes/kubernetes/blob/a1b12e49eac237a37939642d0c3395008b9ab380/pkg/kubelet/kubelet.go#L2412

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x3b5f21f]
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc00073c400, {0xc001816c00?, 0x27, 0x40})
  pkg/kubelet/kubelet.go:2412 +0x4df
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/102884#issuecomment-1454089210_

cc @thockin @vinaykul
/sig node
/kind bug
/priority important-soon

**Comment by liggitt** [comment]
also, if VPA state cannot be constructed here:

https://github.com/kubernetes/kubernetes/blob/253ab3eda71f250ad6692bb16f035cebaf0651c9/pkg/kubelet/status/status_manager.go#L195-L200

logging an error, setting state to nil, and continuing means every use of `checkpointState := kl.statusManager.State()` in the pod sync loop is a potential NPE

**Comment by liggitt** [comment]
This is still happening in standalone alpha kubelets… the sync got further but is still panicking at a different spot

**Comment by liggitt** [comment]
Panic moved to here:

https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L729

```
E0311 18:06:24.809627 2835 runtime.go:79] Observed a panic: \"invalid memory address or nil pointer dereference\" (runtime error: invalid memory address or nil pointer dereference)
goroutine 726 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3b84fe0?, 0x6a1f980})
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xb?})
vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3b84fe0, 0x6a1f980})
/usr/local/go/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).doPodResizeAction(0xc000ac5800, 0xc001021680, 0xc000056028?, {0x0, 0x0, {0xc000f4f540, 0x40}, 0x0, 0x0, {0x6a91fb0, ...}, ...}, ...)
pkg/kubelet/kuberuntime/kuberuntime_manager.go:729 +0x7a5
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc000ac5800, {0x4a017f8, 0xc000056028}, 0xc001021680, 0xc0010550e0, {0x6a91fb0, 0x0, 0x0}, 0xc000723db0)
pkg/kubelet/kuberuntime/kuberuntime_manager.go:1218 +0x2d38
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncPod(0xc0006f2400, {0x4a017c0?, 0xc0017901e0?}, 0x0, 0xc001021680, 0x0, 0xc0010550e0)
pkg/kubelet/kubelet.go:1847 +0x1dbd
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop.func1(0xc001ef3f10, 0xc0005f2be0, 0xc001021680, 0xc000c47ed8, 0xc000c47e0e)
pkg/kubelet/pod_workers.go:950 +0x283
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).managePodLoop(0x0?, 0x0?)
pkg/kubelet/pod_workers.go:955 +0x394
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
pkg/kubelet/pod_workers.go:750 +0x45
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
pkg/kubelet/pod_workers.go:748 +0x18ca
```

**Comment by vinaykul** [comment]
Can you please share the commit-id on whic this is happening? And any kubelet logs surrounding the crash? 

With latest master (commit-id ead7d66ee12656cfb7c633dd42a87f8d9cfaa469) , I see a different crash (another nil client access from initial glance). 
https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/volumemanager/reconciler/reconstruct_new.go#L183L183

But my local cluster code hacks kubeDeps.KubeClient = nil before NewMainKubelet(...) so it is different from your CI env.

```golang
I0312 00:33:01.239905 1986312 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
I0312 00:33:01.240183 1986312 volume_manager.go:282] "The desired_state_of_world populator starts"
I0312 00:33:01.240200 1986312 volume_manager.go:284] "Starting Kubelet Volume Manager"
I0312 00:33:01.240239 1986312 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
I0312 00:33:01.240424 1986312 reconstruct_new.go:136] "Volume is marked as uncertain and added into the actual state" pod="" podName=284f6bd2-9cf9-4998-90b2-2c9bcdaf2670 volumeName=kubernetes.io/configmap/284f6bd2-9cf9-4998-90b2-2c9bcdaf2670-config-volume seLinuxMountContext=""
I0312 00:33:01.240463 1986312 reconstruct_new.go:136] "Volume is marked as uncertain and added into the actual state" pod="" podName=284f6bd2-9cf9-4998-90b2-2c9bcdaf2670 volumeName=kubernetes.io/projected/284f6bd2-9cf9-4998-90b2-2c9bcdaf2670-kube-api-access-6ttjc seLinuxMountContext=""
I0312 00:33:01.240477 1986312 reconstruct_new.go:103] "Volume reconstruction finished"
I0312 00:33:01.240481 1986312 reconciler_new.go:29] "Reconciler: start to sync state"
E0312 00:33:01.240532 1986312 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 180 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x314d600?, 0x5f46a00})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x7c
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x38d9f20?})
	vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x78
panic({0x314d600, 0x5f46a00})
	/root/go/src/k8s.io/master_k8s/_output/local/.gimme/versions/go1.20.2.linux.arm64/src/runtime/panic.go:884 +0x1f4
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).updateReconstructedDevicePaths(0x4000a7cd80)
	pkg/kubelet/volumemanager/reconciler/reconstruct_new.go:183 +0x78
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).reconcileNew(0x4000a7cd80)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:60 +0x8c
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x40001d6850?)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:157 +0x40
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x3fa0ea0, 0x4000886870}, 0x1, 0x40001661e0)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:158 +0x90
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x4000a7cd80?, 0x5f5e100, 0x0, 0x0?, 0x4000a9c701?)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:135 +0x80
k8s.io/apimachinery/pkg/util/wait.Until(...)
	vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:92
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).runNew(0x4000a7cd80, 0x3a286d3?)
	pkg/kubelet/volumemanager/reconciler/reconciler_new.go:30 +0x98
k8s.io/kubernetes/pkg/kubelet/volumemanager/reconciler.(*reconciler).Run(0x40002a1b00?, 0x0?)
	pkg/kubelet/volumemanager/reconciler/reconciler_common.go:150 +0x58
created by k8s.io/kubernetes/pkg/kubelet/volumemanager.(*volumeManager).Run
	pkg/kubelet/volumemanager/volume_manager.go:285 +0x258
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x2aa9af8]
```

To unblock CI, I will do a defensive fix (skip`computePodResizeAction` and `doPodResizeAction` for static pods) but I want to understand why this is even getting to `doPodResizeAction`.

**Comment by liggitt** [comment]
the latest run I have was on bbe0eb759533a1b2807796481a2509f50272bbaf and failed on that line at https://github.com/kubernetes/kubernetes/blob/bbe0eb759533a1b2807796481a2509f50272bbaf/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L729

**Comment by liggitt** [comment]
no kubelet logs of interest I see, logs seem pretty normal for a standalone kubelet, just that panic and process exit

**Comment by liggitt** [comment]
the panic I saw wasn't on Windows, it was on Linux, but while spelunking, I saw another possible panic. On Windows, NewPodContainerManager() returns:

https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/cm/container_manager_windows.go#L183-L185

which implements `GetPodCgroupConfig` to return nil,nil:

https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/cm/container_manager_stub.go#L98-L100

which means currentPodMemoryConfig will be nil here:

https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L723-L729

**Comment by liggitt** [comment]
> I want to understand why this is even getting to doPodResizeAction.

that certainly is surprising and suggests that something in computePodResizeAction may not be correct in standalone cases or for static pods

**Comment by liggitt** [comment]
> I will do a defensive fix (skipcomputePodResizeAction and doPodResizeAction for static pods)

I don't really know if making exceptions for static pods is correct when running against an API server where we're reporting status of used resources. @smarterclayton, would you expect an updated manifest that changes resources to be handled by VPA?

**Comment by vinaykul** [comment]
> > I want to understand why this is even getting to doPodResizeAction.
> 
> that certainly is surprising and suggests that something in computePodResizeAction may not be correct in standalone cases or for static pods

Yes, that's what I want to get to the bottom of.

I suspect that for some reason, computePodResizeAction incorrectly determined that a resize is necessary for a best effort pod or burstable w/o CPU limits pod (which resulted in NP access due to https://github.com/kubernetes/kubernetes/blob/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/cm/helpers_linux.go#L167L189 )

`computePodResizeAction` is a pretty complex function that needs to correctly account for various states a container may be in (not running, restarting etc) and I need a repro to ensure any fix I make actually works as intended.

**Comment by vinaykul** [comment]
> > I will do a defensive fix (skipcomputePodResizeAction and doPodResizeAction for static pods)
> 
> I don't really know if making exceptions for static pods is correct when running against an API server where we're reporting status of used resources. @smarterclayton, would you expect an updated manifest that changes resources to be handled by VPA?

When I tried this last time by updating the manifest resources and saving it (just out of curiosity) , I found that pod was restarted (not patched - which triggers the resize workflow). But I don't know if it should be officially supported.

**Comment by vinaykul** [comment]
I don't have a repro (attempted testing it without skipping computePodResizeAction / doPodResizeAction for static pods) in local cluster + kubeletonly with either best effort static pod or burstable static pod with cpu requests specified. 

Do you have the pod yaml that caused this issue in your env?

**Comment by liggitt** [comment]
not offhand, I'd have to spin up a cluster manually and try to binary search the static manifests we use to isolate it, and I have negative time to dig with code freeze reviews :-/

**Comment by smarterclayton** [comment]
> . @smarterclayton, would you expect an updated manifest that changes resources to be handled by VPA?

If you mean, when VPA points at a mirror pod can it change spec?  No, generally.  If you mean, should static pod consumed resources be visible via the API?  Yes.

**Comment by liggitt** [comment]
> If you mean, when VPA points at a mirror pod can it change spec? No, generally.

From what we can tell, *something* in the VPA path (`computePodResizeAction `) thought a static pod's resources needed to trigger the resize code path.

I don't know enough about static pod handling to know if that is a category error and VPA should *never* expect to resize resources used by static pods. That's what part of the proposed fix in https://github.com/kubernetes/kubernetes/pull/116504 does - excludes static pods from being considered by VPA.

For a kubelet running against an API server, would you expect manifest-driven pods to be able to make use of resize functionality? If so, a blanket exclusion of static pods from that code path doesn't seem correct.

**Comment by vinaykul** [comment]
> > . @smarterclayton, would you expect an updated manifest that changes resources to be handled by VPA?
> 
> If you mean, when VPA points at a mirror pod can it change spec? No, generally. If you mean, should static pod consumed resources be visible via the API? Yes.

I think the implementation can support resizing static pods via patch to its mirror. There is some bug in the pod update -> pod worker sync handoff where the resize update is lost. IMHO, we should allow resizing static pods as well via its mirror. (Standalone kubelet is a different story - the current implementation terminates and adds new pod). We just haven't considered this scenario and it needs a bit of work (mainly to develop solid e2e test cases for mirror pod resize and standalone scenario). This is something I'd want to take the time to fix the right way in 1.28, so my preference is to make a defensive fix for v1.27 (aka we don't support static pod resizing for 1.27 alpha) rather than trying to wing it.

**Comment by vinaykul** [comment]
In HandlePodUpdates, static pods are processed by handleMirrorPod:
https://github.com/kubernetes/kubernetes/blob/fcf5d23e6818ccfbc92f332af82f31661f8d4f88/pkg/kubelet/kubelet.go#L2491-L2502
which dispatches SyncPodUpdate for the original pod, and not the updated mirror pod.
https://github.com/kubernetes/kubernetes/blob/fcf5d23e6818ccfbc92f332af82f31661f8d4f88/pkg/kubelet/kubelet.go#L2412-L2420

For normal pods, SyncPodUpdate is invoked for the updated pods. This is the reason (bug) I didn't see resize updates come through in SyncPod().

I don't know how long the code has been this way, but I'm hesitant and risk-averse to just swap out `pod` with `mirrorPod` it up so close to code freeze. This is why I feel it is best to disable static pods for resize at this time and do it right in 1.28

**Comment by vinaykul** [comment]
Tracking issue https://github.com/kubernetes/kubernetes/issues/116597 where the repro steps try updating container image of a static pod (no involvement of in-place resize feature)

**Comment by bobbypage** [comment]
I was able to repro the panic with standalone mode in node e2e:

```
E0314 22:40:45.433285    1490 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 385 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x3a3c560?, 0x688f790})
    vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x99
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0?})
    vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x3a3c560, 0x688f790})
    /go/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.20.2.linux.amd64/src/runtime/panic.go:884 +0x213
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).doPodResizeAction(0xc000ce0480, 0xc001067200, 0xc000993fb0?, {0x0, 0x0, {0xc000cfe3c0, 0x40}, 0x0, 0x0, {0x690b7e0, ...}, ...}, ...)
    pkg/kubelet/kuberuntime/kuberuntime_manager.go:734 +0x7a5
k8s.io/kubernetes/pkg/kubelet/kuberuntime.(*kubeGenericRuntimeManager).SyncPod(0xc000ce0480, {0x48bf718, 0xc000993fb0}, 0xc001067200, 0xc0010107e0, {0x690b7e0, 0x0, 0x0}, 0xc0003dc500)
    pkg/kubelet/kuberuntime/kuberuntime_manager.go:1223 +0x2d38
k8s.io/kubernetes/pkg/kubelet.(*Kubelet).SyncPod(0xc00053b400, {0xc001001580?, 0x6?}, 0x0, 0xc001067200, 0x0, 0xc0010107e0)
    pkg/kubelet/kubelet.go:1865 +0x25de
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop.func1({0x0, {0x0, {0xc0fc5bdb191136ad, 0x27796a748, 0x68dac00}, 0xc001067200, 0x0, 0x0, 0x0}}, 0xc00052e5a0, ...)
    pkg/kubelet/pod_workers.go:1241 +0x1d1
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).podWorkerLoop(0xc001001580?, {0xc001001580, 0x20}, 0x82e71986708e9901?)
    pkg/kubelet/pod_workers.go:1246 +0x48d
k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod.func1()
    pkg/kubelet/pod_workers.go:920 +0x125
created by k8s.io/kubernetes/pkg/kubelet.(*podWorkers).UpdatePod
    pkg/kubelet/pod_workers.go:915 +0x2393
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x3303365]
```

I built on top @SergeyKanzhelev standalone PR - https://github.com/kubernetes/kubernetes/pull/116551

Here's my branch: https://github.com/bobbypage/kubernetes/tree/standaloneMode

I ran the test and enabled all alpha features.
* Invocation: https://gist.github.com/bobbypage/21e72ae83e57a96adcfea8e56d285ec7
* Build log: https://gist.github.com/43c670895571bedc6e06bb4782f090d9
* Kubelet log: https://gist.github.com/dae3ab7aab4a1459dd53c3525f51af94

**Comment by bobbypage** [comment]
I will patch in the https://github.com/kubernetes/kubernetes/pull/116504 locally and verify that it results in the test passing.

**Comment by bobbypage** [comment]
I patched in https://github.com/kubernetes/kubernetes/pull/116504 and verified that the panic is fixed. With  https://github.com/kubernetes/kubernetes/pull/116504 patched in:

* build log: https://gist.github.com/3ff87d48f2ee5117e8909c7632b3fcbf
* kubelet log: https://gist.github.com/a4a35ef5d03a0d8be11659ad04cd43b0
