### ISSUE TITLE
Issue with k8s.io/zh-cn/docs/reference/command-line-tools-reference/kubelet/

### ISSUE THREAD

**Issue by lipeng8** [kubernetes/kubernetes#116228]
Kubelet how to enable cAdvisor to collect network metric data for each container, instead of only pod pause containers

**Comment by sftim** [comment]
I think this is a request for help using Kubernetes. However, GitHub is not the right place for support requests.

If you're looking for help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by pacoxu** [comment]
Is this a bug? 

https://github.com/kubernetes/kubernetes/blob/4f303d123659fb3aac2108f8439c7f43dde438b5/pkg/kubelet/cadvisor/cadvisor_linux.go#L84-L97

Here is the list of included cadvisormetrics in kubelet. 

/cc @bobbypage 

If this is not included above, you have to run cadvisor standalone and see if metrics are being reported (with flags to enable that).

**Comment by neolit123** [comment]
> Kubelet how to enable cAdvisor to collect network metric data for each container, instead of only pod pause containers

old issue, but try asking in #sig-node on k8s slack.
if they say there is a bug or missing feature reopen this ticket and retitle it.

/close
/sig node
