### ISSUE TITLE
pod with only startupProbe cannot be ready right now when startupProbe succeeded

### ISSUE THREAD

**Issue by liuhougang** [kubernetes/kubernetes#116238]
### What happened?

pod (only one container) with only startupProbe(without readinessProbe/livenessProbe) cannot be ready right now when startupProbe succeeded like below (it change to ready after 1 min since startupProbe succeeded ):

```
startupProbe:
          failureThreshold: 30
          httpGet:
            path: /eeadb7c9-3ee0-4136-a1be-051d754614ba/lab
            port: 8888
          initialDelaySeconds: 1
          periodSeconds: 2
          successThreshold: 2
```

### What did you expect to happen?

just like a pod without any Probe which changes to ready right now when container started; I expect that the pod with only startupProbe can change to Ready soon after startupProbe succeeded 

### How can we reproduce it (as minimally and precisely as possible)?

it can reproduce every time in my k8s（1.19）

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.10", GitCommit:"98d5dc5d36d34a7ee13368a7893dcb400ec4e566", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.10-r0-CCE22.3.1.B012", GitCommit:"cf078ac3913556bdf46374341f51a4e0fc654113", GitTreeState:"clean", BuildDate:"2022-03-26T10:12:19Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
minikube
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
1.19 is end of life for a long time.
Can this be reproduced easily in latest versions?  See https://kubernetes.io/releases/patch-releases/#detailed-release-history-for-active-branches.

**Comment by pacoxu** [comment]
And it is similar to https://github.com/kubernetes/kubernetes/issues/109802#issuecomment-1118675506.

**Comment by liuhougang** [comment]
> And it is similar to [#109802 (comment)](https://github.com/kubernetes/kubernetes/issues/109802#issuecomment-1118675506).

thanks, I think it is same issume
