### ISSUE TITLE
kubectl drain improvements

### ISSUE THREAD

**Issue by adilGhaffarDev** [kubernetes/kubernetes#116210]
### What would you like to be added?

kubedrain has "onPodDeletedOrEvicted" callback that can be used in custom controllers. It would be very helpful if we add more callbacks that can give more granular control over monitoring, like "onPodDeletionOrEvicitionStarted" and "onPodDeletionOrEvictionFailed".

### Why is this needed?

It would help monitor the draining of nodes on a more granular level. Sometimes while draining, if the pod is stuck during the eviction or deletion of node, there is not much information that custom controllers can get from kubedrain, with the above-mentioned callbacks custom controllers will know which pod is evicting or if it failed during the eviction process.

**Comment by SergeyKanzhelev** [comment]
What is the custom controllers in your scenario? Can you elaborate on what you want to achieve with more details.

Is this is kubectl improvement, the best sig to involve is sig cli.

/sig cli

**Comment by SergeyKanzhelev** [comment]
/remove-sig node

please re-apply the sig node if this will end up being a request to sig node

**Comment by adilGhaffarDev** [comment]
> What is the custom controllers in your scenario? Can you elaborate on what you want to achieve with more details.

In our case we have machine_controller.go in CAPI (https://github.com/kubernetes-sigs/cluster-api/blob/9dc69be55dfec51c58838645a89075f379e1fc1f/internal/controllers/machine/machine_controller.go#L609). Sometimes while draining, if the pod or volume is stuck during the eviction, there is not much information that we get from kubedrain.Helper. It would be much easier for the controller to report these kinds of issues with more granular callbacks like "onPodDeletionOrEvicitionStarted" and "onPodDeletionOrEvictionFailed" on kubedrain.Helper.

**Comment by adilGhaffarDev** [comment]
/assign
Assigning this to myself, I have discussed this issue in sig-cli community meeting and they have given green light for this improvement.
