### ISSUE TITLE
[Flake] Test_newReadyRacy flaking

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#116225]
https://github.com/kubernetes/kubernetes/pull/116024 added a test that is flaking at a ~3% failure rate with `stress`:

```
go test -race -c k8s.io/apiserver/pkg/storage/cacher
stress ./cacher.test -test.run Test_newReadyRacy
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/116024#discussion_r1123420776_
            
/sig api-machinery
/assign @aojea
/cc @wojtek-t
/kind failing-test

**Comment by wojtek-t** [comment]
@aojea - all the failures I've seen weren't failures, but rather timeouts.

I wasn't able to reproduce it either by running the test itself, but I know what the potential failure is here:
- the `ready.set(true)` and `ready.set(false)` goroutines are somehow finishing
- the last one that is called is `ready.set(false)`
- 1+ of  `ready.wait()` goroutine is starting after that

In this case the last will never finish.

The fix is in https://github.com/kubernetes/kubernetes/pull/116251

**Comment by liggitt** [comment]
not sure if it's related, but TestGetCurrentResourceVersionFromStorage in the same package is also flaking:

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=k8s.io%2Fapiserver%2Fpkg%2Fstorage%2Fcacher

```
{Failed  === RUN   TestGetCurrentResourceVersionFromStorage
panic: Object 'Kind' is missing in '{"name":"pod-1","namespace":"ns","creationTimestamp":null,"Spec":{"RestartPolicy":"","TerminationGracePeriodSeconds":null,"ActiveDeadlineSeconds":null,"NodeSelector":null,"ServiceAccountName":"","NodeName":"","Hostname":"","Subdomain":"","SchedulerName":""},"Status":{"Phase":"","Conditions":null,"Message":"","Reason":"","HostIP":"","PodIP":"","StartTime":null}}
'

goroutine 29741 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.decodeObj({0x2f257b0?, 0xc000142500}, {0x2f28fb0, 0x3fbed20}, {0xc003718900, 0x16c, 0x180}, 0x0?)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:458 +0x2af
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).prepareObjs(0xc0002061c0, 0xc0034d4ff0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:426 +0x2aa
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).transform(0xc0002061c0, 0xc0034d4ff0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:318 +0x65
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).processEvent(0xc0002061c0, 0xc0003281b0)
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:283 +0x1c5
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3.(*watchChan).run
	/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/storage/etcd3/watcher.go:161 +0x236
```

**Comment by wojtek-t** [comment]
that's a different thing for sure.

@p0lyn0mial - can you please take a look at it - it's a newly added test from yesterday

**Comment by wojtek-t** [comment]
Spinned of https://github.com/kubernetes/kubernetes/issues/116292 for the other issue mentioned by Jordan.
