### ISSUE TITLE
Scheduler crashes with fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by enisoc** [kubernetes/kubernetes#116226]
### What happened?

While performing stress tests that add many Nodes (~10) at the same time to a cluster with many Pods (>1000) that were previously unschedulable, the scheduler crashes with the following error and stack trace:

```
fatal error: concurrent map iteration and map write

goroutine 455300 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1.(*ObjectMeta).DeepCopyInto(0xc00a8d1420, 0xc019de6420)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/apis/meta/v1/zz_generated.deepcopy.go:684 +0x396
k8s.io/api/core/v1.(*Pod).DeepCopyInto(0xc00a8d1400, 0xc019de6400)
        /go/pkg/mod/k8s.io/api@v0.25.1/core/v1/zz_generated.deepcopy.go:3307 +0xc5
k8s.io/api/core/v1.(*Pod).DeepCopy(...)
        /go/pkg/mod/k8s.io/api@v0.25.1/core/v1/zz_generated.deepcopy.go:3319
k8s.io/kubernetes/pkg/scheduler/internal/queue.isPodUpdated.func1(0xc00a8d1400?)
        /go/pkg/mod/k8s.io/kubernetes@v1.25.1/pkg/scheduler/internal/queue/scheduling_queue.go:510 +0x45
k8s.io/kubernetes/pkg/scheduler/internal/queue.isPodUpdated(0xc015a6b940?, 0xc029d29000?)
        /go/pkg/mod/k8s.io/kubernetes@v1.25.1/pkg/scheduler/internal/queue/scheduling_queue.go:518 +0x43
k8s.io/kubernetes/pkg/scheduler/internal/queue.(*PriorityQueue).Update(0xc025f808c0, 0xc029d29000, 0x8?)
        /go/pkg/mod/k8s.io/kubernetes@v1.25.1/pkg/scheduler/internal/queue/scheduling_queue.go:550 +0x34e
k8s.io/kubernetes/pkg/scheduler.(*Scheduler).updatePodInSchedulingQueue(0xc0487961b0, {0x4f42960?, 0xc029d29000}, {0x4f42960?, 0xc00a8d1400})
        /go/pkg/mod/k8s.io/kubernetes@v1.25.1/pkg/scheduler/eventhandlers.go:138 +0x214
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnUpdate(...)
        /go/pkg/mod/k8s.io/client-go@v0.25.1/tools/cache/controller.go:239
k8s.io/client-go/tools/cache.FilteringResourceEventHandler.OnUpdate({0xc038be9c00?, {0x5849e10?, 0xc009df9ba8?}}, {0x4f42960, 0xc029d29000}, {0x4f42960, 0xc00a8d1400})
        /go/pkg/mod/k8s.io/client-go@v0.25.1/tools/cache/controller.go:274 +0xe2
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /go/pkg/mod/k8s.io/client-go@v0.25.1/tools/cache/shared_informer.go:816 +0xf7
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:157 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0012d6f38?, {0x581b8a0, 0xc026f291a0}, 0x1, 0xc01f5bee40)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:158 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x50?, 0xc0012d6fd0?)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:135 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:92
k8s.io/client-go/tools/cache.(*processorListener).run(0xc01d4cc880?)
        /go/pkg/mod/k8s.io/client-go@v0.25.1/tools/cache/shared_informer.go:812 +0x6b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:75 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/util/wait/wait.go:73 +0x85
```

### What did you expect to happen?

The scheduler should not crash.

### How can we reproduce it (as minimally and precisely as possible)?

I don't have a small reproduction because it only happens when the scheduler is under sudden stress. However, I have a simulated data set locally (dumped from production, so I can't share) that I can load into a fake apiserver ([kube-scheduler-simulator](https://github.com/kubernetes-sigs/kube-scheduler-simulator)) and I confirmed that this same crash happens every time for that data set.

The crash still happens if I build kube-scheduler-simulator with all k8s module dependencies updated from v1.25.1 to v1.25.6 or v1.26.1.

However, the crash no longer happens if I build the scheduler with the following patch:

https://github.com/enisoc/kubernetes/commit/a11654cae453caa8fa25bb3e088b52967f967017

This patch is probably not the right long-term fix, but it may help point the way to the root cause.

### Kubernetes version

Tested on v1.25.1, v1.25.6, and v1.26.1.

### Cloud provider

N/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sanposhiho** [comment]
@enisoc Can you share the full stack trace? I'm guessing the above one is part of it. There should be two goroutines at that moment; one is writing something on map, another is iterating map.

**Comment by sanposhiho** [comment]
/go/pkg/mod/k8s.io/apimachinery@v0.25.1/pkg/apis/meta/v1/zz_generated.deepcopy.go:684 is iteration of Pod's annotation. 
So, the problem is who writes something on annotation.

**Comment by sanposhiho** [comment]
Wait, just realized the simulator actually writes the annotation without `pod.DeepCopy`. 🤦

@enisoc Could you try to add `pod = pod.DeepCopy()` around here↓ and check if the crush still happens or not?
https://github.com/kubernetes-sigs/kube-scheduler-simulator/blob/720698d6295e1db1e4267667da6cab77b424dece/simulator/scheduler/plugin/resultstore/store.go#L153

**Comment by enisoc** [comment]
@sanposhiho You were right! Adding that change in the simulator fixes it. I'll close this and move the discussion to the simulator repo. Thanks!
