### ISSUE TITLE
HPA condition "ScalingLimited" can have a wrong value "TooFewReplicas" while it should not

### ISSUE THREAD

**Issue by pfrayer** [kubernetes/kubernetes#116387]
### What happened?

This is the same issue as #79773

The `HorizontalPodAutoscaler` condition `ScalingLimited`  can have an incoherent status even if the `currentReplicas`/`desiredReplicas` is within the range of requested `minReplicas`/`maxReplicas`:

```
$  kubectl describe hpa my-hpa
...
Min replicas:                                             1
Max replicas:                                            3
Deployment pods:    1 current / 1 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from memory resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas      the desired replica count is less than the minimum replica count
```

Here the `TooFewReplicas` has no sense: the `minReplicas` is `1` and the `current/desiredReplicas` is also 1.

### What did you expect to happen?

When the `current/desiredReplicas` number is within the `minReplicas`/`maxReplicas` range, the `ScalingLimited` condition should be `False` with the `DesiredWithinRange` reason:

```
ScalingLimited  False    DesiredWithinRange  the desired count is within the acceptable range
```

### How can we reproduce it (as minimally and precisely as possible)?

1. Spawn an HPA, with whatever working configurations
2. All the conditions are correct
3. Update the HPA and only lower the `minReplicas` value. The `ReplicaSet` will be scaled down, same for the  `current/desiredReplicas`
4. Then the `ScalingLimited` show this bad status, `TooFewReplicas` for reason `the desired replica count is less than the minimum replica count`

With real outputs:
Step 1 & 2: HPA is spawned, everything is OK
```
Min replicas:                                             3
Max replicas:                                            5
Deployment pods:    3 current / 3 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
```
Step 3: patch the HPA (here `minReplicas` → from `3` to `2`)
While the `ReplicaSet` isn't actually scaled down, the `ScalingLimited` is still OK:
```
Min replicas:                                             2
Max replicas:                                            5
Deployment pods:    3 current / 3 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  False   DesiredWithinRange  the desired count is within the acceptable range
```
Step 4: the `ReplicaSet` is scaled down to `2`, then the `ScalingLimited` condition has a bad status:
```
Min replicas:                                             2
Max replicas:                                            5
Deployment pods:    2 current / 2 desired
Conditions:
  Type            Status  Reason              Message
  ----            ------  ------              -------
  AbleToScale     True    ReadyForNewScale    recommended size matches current size
  ScalingActive   True    ValidMetricFound    the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    ScalingLimited      the desired replica count is less than the minimum replica count
```

### Anything else we need to know?

This issues doesn't happen all the time. Sometimes lowering the `minReplicas` cause the issue, sometimes not.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.24.7
Server Version: v1.24.7
```

</details>

### Cloud provider

<details>
</details>

**Comment by xiaomudk** [comment]
I have checked the code, and there should not be a "TooFewReplicas" error when "minimumAllowedReplicas" is equal to "scaleDownLimit".
```
		scaleDownLimit := calculateScaleDownLimitWithBehaviors(args.CurrentReplicas, a.scaleUpEvents[args.Key], a.scaleDownEvents[args.Key], args.ScaleDownBehavior)

		if scaleDownLimit > args.CurrentReplicas {
			// We shouldn't scale down further until the scaleDownEvents will be cleaned up
			scaleDownLimit = args.CurrentReplicas
		}
		minimumAllowedReplicas := args.MinReplicas
		if minimumAllowedReplicas < scaleDownLimit {
			minimumAllowedReplicas = scaleDownLimit
			possibleLimitingReason = "ScaleDownLimit"
			possibleLimitingMessage = "the desired replica count is decreasing faster than the maximum scale rate"
		} else {
			possibleLimitingMessage = "the desired replica count is less than the minimum replica count"
			possibleLimitingReason = "TooFewReplicas"
		}
```
I can try to fix it.

**Comment by xgp01** [comment]
> I have checked the code, and there should not be a "TooFewReplicas" error when "minimumAllowedReplicas" is equal to "scaleDownLimit".
> 
> ```
> 		scaleDownLimit := calculateScaleDownLimitWithBehaviors(args.CurrentReplicas, a.scaleUpEvents[args.Key], a.scaleDownEvents[args.Key], args.ScaleDownBehavior)
> 
> 		if scaleDownLimit > args.CurrentReplicas {
> 			// We shouldn't scale down further until the scaleDownEvents will be cleaned up
> 			scaleDownLimit = args.CurrentReplicas
> 		}
> 		minimumAllowedReplicas := args.MinReplicas
> 		if minimumAllowedReplicas < scaleDownLimit {
> 			minimumAllowedReplicas = scaleDownLimit
> 			possibleLimitingReason = "ScaleDownLimit"
> 			possibleLimitingMessage = "the desired replica count is decreasing faster than the maximum scale rate"
> 		} else {
> 			possibleLimitingMessage = "the desired replica count is less than the minimum replica count"
> 			possibleLimitingReason = "TooFewReplicas"
> 		}
> ```
> 
> I can try to fix it.

@xiaomudk Are you already working on it? I'd like to try this if you don't want to do it anymore.

**Comment by xiaomudk** [comment]
@xgp01 I'm already working on it.

**Comment by krisiye** [comment]
Any update on this?  Also any more info on what versions are affected? I am currently testing with k8s 1.23 and continue to see this issue. This does not seem to block any HPA-related scale up/down but the `ScalingLimited` status is confusing:


`
Name:                                                  test-scaling
Namespace:                                             test-scaling
Labels:                                                app.kubernetes.io/managed-by=Helm
Annotations:                                           meta.helm.sh/release-name: test-scaling
                                                       meta.helm.sh/release-namespace: test-scaling
CreationTimestamp:                                     Tue, 11 Oct 2022 17:00:30 -0400
Reference:                                             Deployment/test-scaling
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  0% (5m) / 50%
Min replicas:                                          3
Max replicas:                                          6
Deployment pods:                                       3 current / 3 desired
Conditions:
  Type            Status  Reason            Message
  ----            ------  ------            -------
  AbleToScale     True    ReadyForNewScale  recommended size matches current size
  ScalingActive   True    ValidMetricFound  the HPA was able to successfully calculate a replica count from cpu resource utilization (percentage of request)
  ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count
Events:           <none>
`

**Comment by NikitaCloudRuntime** [comment]
@xiaomudk Hi :)
Could you please let others know if you have a chance to work on this issue?
We ran into the same issue with k8s 1.25, due to it we cannot set the correct alerts when the HPA controller fails to scale workloads

**Comment by xiaomudk** [comment]
@krisiye @NikitaCloudRuntime Sorry to keep you waiting, I will fix it as soon as possible this week.

**Comment by xiaomudk** [comment]
@NikitaCloudRuntime  @krisiye @pfrayer 
I checked the code carefully. The reason ScalingLimited is True is that the result returned by stabilizeRecommendationWithBehaviors is smaller than desiredReplicas. The result of stabilizeRecommendationWithBehaviors depends on the configuration of the parameter StabilizationWindowSeconds. Its default value is 300s.
```
	stabilizedRecommendation, reason, message := a.stabilizeRecommendationWithBehaviors(normalizationArg)
	normalizationArg.DesiredReplicas = stabilizedRecommendation
	if stabilizedRecommendation != prenormalizedDesiredReplicas {
		// "ScaleUpStabilized" || "ScaleDownStabilized"
		setCondition(hpa, autoscalingv2.AbleToScale, v1.ConditionTrue, reason, message)
	} else {
		setCondition(hpa, autoscalingv2.AbleToScale, v1.ConditionTrue, "ReadyForNewScale", "recommended size matches current size")
	}
	desiredReplicas, reason, message := a.convertDesiredReplicasWithBehaviorRate(normalizationArg)
	if desiredReplicas == stabilizedRecommendation {       // Please note this judgment condition
		setCondition(hpa, autoscalingv2.ScalingLimited, v1.ConditionFalse, reason, message)
	} else {
		setCondition(hpa, autoscalingv2.ScalingLimited, v1.ConditionTrue, reason, message)
	}
```

I need some more information to proceed:
1. The specific time of the event
2. Modify StabilizationWindowSeconds to be shorter. Will similar situations occur?

**Comment by simpliatanu** [comment]
I wonder if this bug was ever addressed, if not, does "ScalingLimited  True    TooFewReplicas    the desired replica count is less than the minimum replica count" means hpa is not working?? or it is just a wrong message..

**Comment by antoinedeschenes** [comment]
I still see this happening on any HPA that has hit the minimum replica count. 

It looks like it happens when the metrics are below target and it tries to downscale further, but minReplicas is higher than the calculated desired target. You'll still see desiredReplicas==minReplicas in the HPA status though.
