### ISSUE TITLE
[Flake] "OpenAPI config must not be nil" flake in 	k8s.io/kubernetes/test/integration/apiserver tests

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#116304]
### Which jobs are flaking?

pull-kubernetes-integration

https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=TestChangeCRD

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=OpenAPI%20config%20must%20not%20be%20nil

### Which tests are flaking?

TestChangeCRD

### Since when has it been flaking?

March 2nd

### Reason for failure (if possible)

```
apiserver_test.go:1230: failed to create server: unable to get openapi models: OpenAPI config must not be nil
```

### Relevant SIG(s)

/sig api-machinery
/assign @alexzielenski

**Comment by alexzielenski** [comment]
I'm thinking this might be a red herring from my WIP PR #114998. Every test failure I've clicked on https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=OpenAPI%20config%20must%20not%20be%20nil#691610cce27a9a9c3fbc brings me to that PR's test history.

`OpenAPI config must not be nil` error message is not in the current codebase and it is added by that PR. I am currently in process of fixing the integration tests of that PR.

**Comment by liggitt** [comment]
oh, I saw that test fail in unrelated PRs (like https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116109/pull-kubernetes-integration/1632733572446031872) and jumped to triage, not realizing the failures in other PRs were not the "OpenAPI config must not be nil" error

**Comment by apelisse** [comment]
Should we close this or is there still an error?

**Comment by liggitt** [comment]
I think @alexzielenski is right and this failure was on his unmerged PR

/close
