### ISSUE TITLE
Allow StorageClass AllowedTopologies to update from beta to GA topology labels

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#116344]
### What happened?

In https://github.com/kubernetes/kubernetes/issues/114268, we realized that non in-tree StorageClass can be impacted by a future removal of beta topology labels from Nodes if they are supporting the beta topology labels.

### What did you expect to happen?

We should allow users to mutate the StorageClass.AllowedTopologies to update uses of the beta topology label to the GA label.

### How can we reproduce it (as minimally and precisely as possible)?

Remove beta topology label from a Node, and try to schedule a Pod using a non-migratable PVC with beta topology label in the StorageClass.AllowedTopologies

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by msau42** [comment]
@haoruan is this something you would be interested in fixing?

**Comment by haoruan** [comment]
Of course!
/assign

**Comment by haoruan** [comment]
Sounds like the field is already mutable, no checking to this field:
https://github.com/kubernetes/kubernetes/blob/e390791e5fdddd6d17504ea200e0a86f12cc0525/pkg/apis/storage/validation/validation.go#L65-L81

**Comment by msau42** [comment]
Thanks for checking! Will consider this done.
/close
