### ISSUE TITLE
Failure cluster [0991d7dd...] scheduler perf test failed since 3/7

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116359]
### Failure cluster [0991d7dded0bd24757a9](https://go.k8s.io/triage#0991d7dded0bd24757a9)
https://perf-dash.k8s.io/#/?jobname=scheduler-perf-benchmark&metriccategoryname=Scheduler&metricname=BenchmarkResults&benchmark=BenchmarkPerfScheduling%2FSchedulingCSIPVs%2F500Nodes-8&metricName=time

##### Error text:
```
Failed
goos: linux
goarch: amd64
pkg: k8s.io/kubernetes/test/integration/scheduler_perf
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
BenchmarkPerfScheduling
BenchmarkPerfScheduling/SchedulingBasic
BenchmarkPerfScheduling/SchedulingBasic/500Nodes
    scheduler_perf_test.go:1064: creating 500 pods in namespace "namespace-1"
    scheduler_perf_test.go:1089: namespace: namespace-1, pods: want 500, got 60
    scheduler_perf_test.go:1089: namespace: namespace-1, pods: want 500, got 421
    scheduler_perf_test.go:1086: scheduling succeed
    scheduler_perf_test.go:1064: creating 1000 pods in namespace "namespace-2"
    scheduler_perf_test.go:1089: namespace: namespace-2, pods: want 1000, got 151
    scheduler_perf_test.go:1089: namespace: namespace-2, pods: want 1000, got 509
    scheduler_perf_test.go:1089: namespace: namespace-2, pods: want 1000, got 864
    scheduler_perf_test.go:1086: scheduling succeed
BenchmarkPerfScheduling/SchedulingBasic/500Nodes-8         	       1	       307.7 SchedulingThroughput/Average	       350.0 SchedulingThroughput/Perc50	       352.0 SchedulingThroughput/Perc90	       352.0 SchedulingThroughput/Perc95	       352.0 SchedulingThroughput/Perc99	         2.160 scheduler_framework_extension_point_duration_ms/Average	         2.061 scheduler_framework_extension_point_duration_ms/Perc50	         3.186 scheduler_framework_extension_point_duration_ms/Perc90	         4.935 scheduler_framework_extension_point_duration_ms/Perc95	         7.680 scheduler_framework_exte
```
#### Recent failures:
[2023/3/8 03:29:53 ci-benchmark-scheduler-perf-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633187749177593856)
[2023/3/8 00:59:00 ci-benchmark-scheduler-perf-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633149748166791168)
[2023/3/7 22:28:07 ci-benchmark-scheduler-perf-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633111748267479040)
[2023/3/7 19:57:45 ci-benchmark-scheduler-perf-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633073998180913152)
[2023/3/7 17:27:56 ci-benchmark-scheduler-perf-master](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633036249050648576)

/kind failing-test

/sig scheduling

**Comment by pacoxu** [comment]
The goleak check was added in https://github.com/kubernetes/kubernetes/pull/115425.

**Comment by Huang-Wei** [comment]
cc @pohly

**Comment by alculquicondor** [comment]
cc @sanposhiho

**Comment by pohly** [comment]
At least https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633187749177593856 didn't fail with  a goroutine leak. It failed because of:

```
panic: feature "CSIMigrationAWS" is not registered in FeatureGate "k8s.io/apiserver/pkg/util/feature/feature_gate.go:28"
```

**Comment by Huang-Wei** [comment]
Good to see it's not a regression. Let me raise a PR to see whether `CSIMigrationAWS` is the only culprit.

**Comment by alculquicondor** [comment]
Even if it's not the only culprit, I wouldn't think this is a regression, but rather a consequence of the fact that we didn't use goleak before.

**Comment by Huang-Wei** [comment]
it's just co-incidental #115838 get merged with the same timing of the goleak check. In other words, the scheduler perf test would also fail if the goleak PR doesn't go in.

**Comment by alculquicondor** [comment]
> At least https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-benchmark-scheduler-perf-master/1633187749177593856 didn't fail with a goroutine leak. It failed because of:
> 
> ```
> panic: feature "CSIMigrationAWS" is not registered in FeatureGate "k8s.io/apiserver/pkg/util/feature/feature_gate.go:28"
> ```

This can be solved by removing this line
https://github.com/kubernetes/kubernetes/blob/713ded736824d669d9fae9ac4a29b1ec18d66446/test/integration/scheduler_perf/config/performance-config.yaml#L101
