### ISSUE TITLE
Allow Job to update to GA topology labels

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#116346]
### What happened?

While we were fixing PVs to allow updating topology labels from beta to GA in https://github.com/kubernetes/kubernetes/pull/115391, we noticed that Job [allows Affinity updates](https://github.com/kubernetes/kubernetes/blob/0ebf9a3a1be6d0757b1d60b860ed226e2d4d1abc/pkg/apis/batch/validation/validation.go#L392-L405), but not other label key references like Pod.spec.nodeSelector and topologyKey.

### What did you expect to happen?

Evaluate if Job should be allowed to update those fields or at least update from the beta to GA topology labels.

All the other workload controllers: Deployment, ReplicaSet, StatefulSet, DaemonSet allow template updates.

### How can we reproduce it (as minimally and precisely as possible)?

Remove the beta topology label from Node

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by msau42** [comment]
/sig apps
/wg batch

cc @alculquicondor @ahg-g @haoruan

**Comment by alculquicondor** [comment]
An important difference between Job and the rest of the workload APIs is that Pods run to completion. This implies that Pods should never be recreated. If you want to change a template, you should be creating a new Job.

The exception is when a Job is suspended state, where some fields can change, which is the code that you pointed at.

But we have been going with the assumption that a Job doesn't run over more than two major releases upgrades https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods#jobs-with-legacy-tracking. Another justification to this is that Job pods run in kubelets, which can't be more than 2 vesions old than the control plane.

**Comment by haoruan** [comment]
Is that possible a Job was created with old template then in the pending state because of the topology label mismatch, and maybe we can allow user to update those fields to schedule the job in the right node instead of recreating it?

**Comment by alculquicondor** [comment]
A Job whose pods were never scheduled for 2 or more releases? It sounds like the user didn't care about that job in the first place.
