### ISSUE TITLE
hack/verify-mocks.sh Append `sudo` to a `git worktree remove` command

### ISSUE THREAD

**Issue by samruddhikhandale** [kubernetes/kubernetes#116338]
### What happened?

Hi 👋 

I have been working with @craiglpeters on adding a dev container to this repo - https://github.com/kubernetes/kubernetes/issues/113019

With the dev config, when we run `make verify` then, we are having a test failure for `hack/verify-mocks.sh`. It fails at [this line](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-mocks.sh#L36) with following error msg 👇 

<img width="682" alt="image" src="https://user-images.githubusercontent.com/24955913/223525066-f9a5f951-5217-469a-83c8-8888ada67440.png">

The dev config uses a `vscode` remote user, I wonder if that's the cause of this test failure.

### What did you expect to happen?

I expect `make verify` to succeed with the dev config. Hence, can we update the [current hack/verify-mocks.sh file](https://github.com/kubernetes/kubernetes/blob/master/hack/verify-mocks.sh#) and append `sudo` to it ? This fixes the test

Current - 
> kube::util::trap_add "git worktree remove -f ${_tmpdir}" EXIT

Proposed -
> kube::util::trap_add "sudo git worktree remove -f ${_tmpdir}" EXIT

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by XDRAGON2002** [comment]
Hey @samruddhikhandale could I take this up? Sounds like a small enough issue.

**Comment by nikhita** [comment]
I don't think we should be adding `sudo`. Also see related slack discussion [here](https://kubernetes.slack.com/archives/C1TU9EB9S/p1678216623324089).

**Comment by samruddhikhandale** [comment]
Closing as no longer needed! Thanks.

**Comment by marthinal** [comment]
I had the same error locally from my mac. The problem is when trying to remove the worktree from /private. See this example:

```
% git worktree list
/Users/marthinal/go/src/k8s.io/kubernetes                                                 330b5a2b8db [master]
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.atu6W8xJ  fe05ee9f534 (detached HEAD)
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.Izy4n9jB  c242a003682 (detached HEAD)
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.sU7P0tTo  c242a003682 (detached HEAD)
/Users/marthinal/projects/testworktree                                                    330b5a2b8db [mango]

% git worktree remove -f /Users/marthinal/projects/testworktree 

% git worktree list                                             
/Users/marthinal/go/src/k8s.io/kubernetes                                                 330b5a2b8db [master]
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.atu6W8xJ  fe05ee9f534 (detached HEAD)
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.Izy4n9jB  c242a003682 (detached HEAD)
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.sU7P0tTo  c242a003682 (detached HEAD)

% git worktree remove -f /private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.atu6W8xJ
error: failed to delete '/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.atu6W8xJ': Permission denied
```

Running hack/verify-mocks.sh again... The worktree has been removed BUT the temp dir is still there

```
staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmclient/interface.go
staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmsizeclient/interface.go
staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmssclient/interface.go
staging/src/k8s.io/legacy-cloud-providers/azure/clients/vmssvmclient/interface.go
test/e2e/storage/drivers/csi-test/driver/driver.go
go: downloading github.com/container-storage-interface/spec v1.7.0
error: failed to delete '/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.rBiKblhB': Permission denied

% git worktree list
/Users/marthinal/go/src/k8s.io/kubernetes                                                 330b5a2b8db [master]
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.Izy4n9jB  c242a003682 (detached HEAD)
/private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.sU7P0tTo  c242a003682 (detached HEAD)

% ls /private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.rBiKblhB
OWNERS		OWNERS_ALIASES	_output		api		build		pkg		vendor
```

**Comment by BenTheElder** [comment]
see https://github.com/kubernetes/kubernetes/pull/117273 and https://github.com/kubernetes/kubernetes/pull/117526

we had a similar issue recently as well https://github.com/kubernetes/kubernetes/pull/117510
