### ISSUE TITLE
de-deprecate Topology-aware traffic routing with topology keys

### ISSUE THREAD

**Issue by azelezni** [kubernetes/kubernetes#116300]
Currently there is no way to control/configure topology hints expect using Topology Aware Hints with annotation `service.kubernetes.io/topology-aware-hints: auto`.
From my limited experience with this feature, it just doesn't work, I had a very simple setup, 3 pods each in different AZ, service with topology-aware-hints set to auto, I would expect the endpointslice to have hints configured per AZ, but no, I had to scale up to 8 replicas until the controller decided it's ok to add topology hints.

The main issue stems from the fact that I have to have a proportinal number of pods in a service based on the number of nodes (allocatable CPU) in my cluster per zone.
Well, this only takes into account 1 perticular usecase, where your service is expected to recive traffic from the entire cluster.
But it most situations (at least in my experience) this is hardley the case, what about static workloads? what about workloads that are restriceted to a subset of nodes (GPU for example)? what if my scaling metrics is not CPU (we don't have any scaling based on CPU)?

With the previous service `topologyKeys` at least I had the option to configure topology based on usecase, even if it was limited, it was something, currently I'm at the mercy of the controller.

So at the current state I'm left with very few options, and honestly it looks like downgrading to 1.21 would be easier.

I know there is a discussion around this issue ([here](https://github.com/kubernetes/kubernetes/issues/113731), [here](https://github.com/kubernetes/enhancements/pull/3293)), however until everything is decided upon and released we are paying for data transfer simply because the current feature is broken.

Please bring back Topology-aware traffic routing with topology keys as-is to allows us some level of control.

**Comment by thockin** [comment]
https://github.com/kubernetes/enhancements/pull/3765#pullrequestreview-1284017981

We're not going back to open-coded topology keys - we can achieve the same effect with more implementation flexibility.

**Comment by thockin** [comment]
Sorry to be unclear.

The KEP discussion I linked describes how we can recapture this use-case.
The current codebase does not have it, it's a net new heuristic.

I know that isn't satisfying, and I am sorry for that. Clearly we were
wrong to assume silence was agreement, as we deprecated the old way quite a
while ago.

Topology keys was too manual, and made a guarantee that we were not
enthusiastic about supporting long-term. I have a deeply held belief that
asking users to specify this manually means we have failed to do the right
thing. The current heuristic isn't for your use-case, so we need to revise
the heuristic.

If you have time - that's how to help.

**Comment by azelezni** [comment]
So to summarize, our current options are:
1. Downgrade to 1.22 (1.21 ?)
2. Run all my workloads in a single AZ and hope it won't fail
3. Constantly run hundreds of replicas to make sure hints are available
4. Continue paying for data transfer until a new solution is deemed worthy

> I have a deeply held belief that
asking users to specify this manually means we have failed to do the right
thing.

I don't understand how this is any different from other components like cluster-autoscaler, topologySpreadConstraints, etc..., what's wrong with asking user to config manually? we have tools like Helm/Kustomize to take care of stuff like this.
The desicion to take away all user controls, and let the controller decide what's best for us is a bit extreme.

**Comment by thockin** [comment]
Even if I wanted to bring that API back, I couldn't do it until 1.28.  I'd prefer to implement the equivalent behavior in the newer framework, which leaves more room for implementations, and get THAT into 1.28.
