### ISSUE TITLE
Kernel Panic with kubernetes 

### ISSUE THREAD

**Issue by etavene** [kubernetes/kubernetes#116382]
### What happened?

I am not sure this is the right forum to report this bug. I have Kuberenetes running and suddenly kernel panicked and system got rebooted. But the kernel panic is happened when container run time is initiated. I am not sure this is bug related to container run time or underlying OS. The kernel is shown as below 

32789 Mar  3 15:04:11 localhost kernel: [610610.258875] general protection fault: 0000 [#1] SMP NOPTI
32790 Mar  3 15:04:11 localhost kernel: [610610.264499] CPU: 2 PID: 7140 Comm: runc:[2:INIT] Tainted: G           O      4.19.81-
32791 Mar  3 15:04:11 localhost kernel: [610610.274195] Hardware name: Default string Default string/Default string, BIOS 1.0.04 07/14/2021
32792 Mar  3 15:04:11 localhost kernel: [610610.283118] RIP: 0010:__dec_node_state+0x13/0x60
32793 Mar  3 15:04:11 localhost kernel: [610610.287952] Code: 48 03 3c d5 80 a7 f6 86 e9 7a ff ff ff 66 2e 0f 1f 84 00 00 00 00 00 48 8b 8f c0 35 00 00 89 f6       b8 ff ff ff ff 48 8d 54 31 01 <65> 0f c0 02 65 44 8a 01 83 e8 01 41 0f be c8 0f be c0 f7 d9 39 c8
32794 Mar  3 15:04:11 localhost kernel: [610610.306935] RSP: 0018:ffffb97468d57b80 EFLAGS: 00010212
32795 Mar  3 15:04:11 localhost kernel: [610610.312378] RAX: 00000000ffffffff RBX: ffffe17d4bbcd640 RCX: 0200000000040068
32796 Mar  3 15:04:11 localhost kernel: [610610.319730] RDX: 0200000000040069 RSI: 0000000000000000 RDI: ffffe17d4bbcd640
32797 Mar  3 15:04:11 localhost kernel: [610610.327082] RBP: 80000002ef359045 R08: 0000000000000048 R09: 00000000001e9c20
32798 Mar  3 15:04:11 localhost kernel: [610610.334435] R10: 0000000000000000 R11: 0000000000000000 R12: 000055aa07049000
32799 Mar  3 15:04:11 localhost kernel: [610610.341786] R13: ffffb97468d57ca0 R14: 000055aa0704a000 R15: ffffe17d4bbcd640
32800 Mar  3 15:04:11 localhost kernel: [610610.349141] FS:  0000000000000000(0000) GS:ffff953421a80000(0000) knlGS:0000000000000000
32801 Mar  3 15:04:11 localhost kernel: [610610.357447] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
32802 Mar  3 15:04:11 localhost kernel: [610610.363410] CR2: 000000c000177000 CR3: 000000032e712000 CR4: 00000000003406e0
32803 Mar  3 15:04:11 localhost kernel: [610610.370762] Call Trace:
32804 Mar  3 15:04:11 localhost kernel: [610610.373434]  ? unmap_page_range+0x4d1/0x830
32805 Mar  3 15:04:11 localhost kernel: [610610.377835]  ? unmap_vmas+0x7a/0xb0
32806 Mar  3 15:04:11 localhost kernel: [610610.381540]  ? exit_mmap+0x9b/0x170
32807 Mar  3 15:04:11 localhost kernel: [610610.385250]  ? mmput+0x29/0xd0
32808 Mar  3 15:04:11 localhost kernel: [610610.388525]  ? flush_old_exec+0x253/0x670
32809 Mar  3 15:04:11 localhost kernel: [610610.392753]  ? load_elf_binary+0x343/0x1770
32810 Mar  3 15:04:11 localhost kernel: [610610.397152]  ? get_user_pages_remote+0x132/0x1f0
32811 Mar  3 15:04:11 localhost kernel: [610610.401988]  ? search_binary_handler+0x85/0x1b0
32812 Mar  3 15:04:11 localhost kernel: [610610.406736]  ? __do_execve_file.isra.41+0x552/0x7f0
32813 Mar  3 15:04:11 localhost kernel: [610610.411833]  ? __audit_getname+0x40/0xa0
32814 Mar  3 15:04:11 localhost kernel: [610610.415972]  ? __x64_sys_execve+0x2f/0x40
32815 Mar  3 15:04:11 localhost kernel: [610610.420201]  ? do_syscall_64+0x3d/0xf0
32816 Mar  3 15:04:11 localhost kernel: [610610.424168]  ? entry_SYSCALL_64_after_hwframe+0x44/0xa9
32817 Mar  3 15:04:11 localhost kernel: [610610.429608] Modules linked in: 8021q ip_vs_sh ip_vs_wrr ip_vs_rr linux_user_bde(O) nltr(O) pcie_proxy(O) devmem(O      ) fld_linux(O) os_linux(O) ll_pcie(O) linux_kernel_bde(O) cpld(O) iTCO_wdt iTCO_vendor_support [last unloaded: linux_user_bde]
32818 Mar  3 15:04:11 localhost kernel: [610610.451242] ---[ end trace 3b0f1e0533ac784e ]---
32819 Mar  3 15:04:11 localhost kernel: [610610.456095] RIP: 0010:__dec_node_state+0x13/0x60
32820 Mar  3 15:04:11 localhost kernel: [610610.460945] Code: 48 03 3c d5 80 a7 f6 86 e9 7a ff ff ff 66 2e 0f 1f 84 00 00 00 00 00 48 8b 8f c0 35 00 00 89 f6       b8 ff ff ff ff 48 8d 54 31 01 <65> 0f c0 02 65 44 8a 01 83 e8 01 41 0f be c8 0f be c0 f7 d9 39 c8
32821 Mar  3 15:04:11 localhost kernel: [610610.479960] RSP: 0018:ffffb97468d57b80 EFLAGS: 00010212
32822 Mar  3 15:04:11 localhost kernel: [610610.485421] RAX: 00000000ffffffff RBX: ffffe17d4bbcd640 RCX: 0200000000040068
32823 Mar  3 15:04:11 localhost kernel: [610610.492783] RDX: 0200000000040069 RSI: 0000000000000000 RDI: ffffe17d4bbcd640
32824 Mar  3 15:04:11 localhost kernel: [610610.500148] RBP: 80000002ef359045 R08: 0000000000000048 R09: 00000000001e9c20
32825 Mar  3 15:04:11 localhost kernel: [610610.507510] R10: 0000000000000000 R11: 0000000000000000 R12: 000055aa07049000
32826 Mar  3 15:04:11 localhost kernel: [610610.514875] R13: ffffb97468d57ca0 R14: 000055aa0704a000 R15: ffffe17d4bbcd640
32827 Mar  3 15:04:11 localhost kernel: [610610.522237] FS:  0000000000000000(0000) GS:ffff953421a80000(0000) knlGS:0000000000000000
32828 Mar  3 15:04:11 localhost kernel: [610610.530558] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
32829 Mar  3 15:04:11 localhost kernel: [610610.536532] CR2: 000000c000177000 CR3: 000000032e712000 CR4: 00000000003406e0
32830 Mar  3 15:04:11 localhost kernel: [610610.543894] Kernel panic - not syncing: Fatal exception 

### What did you expect to happen?

No kernel Panic

### How can we reproduce it (as minimally and precisely as possible)?

one Kuberenetes cronjob is getting triggered periodically, which is triggering the following event in audit.log. During this time the panic observed. There is no load on the system when the panic happened. 
 
audit/audit.log.1:134614:type=SYSCALL msg=audit(1678147246.635:233): arch=c000003e syscall=170 success=yes exit=0 a0=c00024b0d8 a1=9 a2=0 a3=0 items=0 ppid=11414 pid=11433 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="runc:[2:INIT]" exe="/" subj==unconfined key="system-locale"

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd

</details>

### Cloud provider

<details>

</details>
Bare metal 

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
# paste output here
Linux localhost 4.19.81 #1 SMP Fri Feb 24 06:20:50 UTC 2023 x86_64 GNU/Linu

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
x
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
Docker version 20.10.8, build 3967b7d
runc version 
runc version 1.0.1
commit: v1.0.1-0-g4144b63
spec: 1.0.2-dev
go: go1.15.14
libseccomp: 2.3.3

containerd containerd.io 1.4.9

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>
calico 3.19.2

**Comment by sftim** [comment]
/close not-planned

Kubernetes v1.21 is out of support, and the Linux kernel is responsible for not crashing.
