### ISSUE TITLE
service account creation with restricted RBAC not working

### ISSUE THREAD

**Issue by gowrisankar22** [kubernetes/kubernetes#116358]
### What happened?

Hi, 
I have a following role and rolebinding definition. I want to allow the service account creation only with specific resource names. 

Example: I should able to create  service account using `dev-blue` with the name `dev-green` and vice versa.
If I am trying to create a service account with any other names it should fail but at the moment  i am unable create service account using `dev-blue` with the name `dev-green` and vice versa.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: main-role
  namespace: dev
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  resourceNames:
  - dev-blue
  - dev-green
  ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rolebinding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: dev-green
    namespace: dev
  - kind: ServiceAccount
    name: dev-blue
    namespace: dev
  ---
  ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-blue
  namespace: dev
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-blue
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: dev-blue
type: kubernetes.io/service-account-token
  ```

### What did you expect to happen?

 I should able to create  service account using `dev-blue` with the name `dev-green` and vice versa.

### How can we reproduce it (as minimally and precisely as possible)?

1. apply the role and role binding
2. try to create a service account with the name dev-green using service account dev-blue.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
All
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Can you provide a manifest for the ServiceAccount you're trying to create, and the error response that you see (ideally: at the HTTP level) when the API server refuses to do so?

**Comment by gowrisankar22** [comment]
@sftim looks like this is a limitation. I will close the this
https://kubernetes.io/docs/reference/access-authn-authz/rbac/

```
Note: You cannot restrict create or deletecollection requests by their resource name. For create, this limitation is because the name of the new object may not be known at authorization time. If you restrict list or watch by resourceName, clients must include a metadata.name field selector in their list or watch request that matches the specified resourceName in order to be authorized. For example, kubectl get configmaps --field-selector=metadata.name=my-configmap
```

**Comment by sftim** [comment]
Good news though: Kubernetes v1.27 may allow that kind of restriction, via ValidatingAdmisisonPolicy.

**Comment by gowrisankar22** [comment]
@sftim but `ValidatingAdmisisonPolicy` will be clusterwide but in my case i want to restrict within the namespace boundary.
