### ISSUE TITLE
Edge case - job pods nearing completion being evicted even though protected by PodDisruptionBudget

### ISSUE THREAD

**Issue by alangibson01** [kubernetes/kubernetes#116308]
### What happened?

I believe I've come across an edge case in evictions which can cause job pods to be evicted and replaced even though they complete without error.

Here's the scenario:

- Create a job with `completions` and `parallelism` both set to 3.
- Add a PodDisruptionBudget in place for this job's pods, with `minAvailable` set to 3.
- All three pods are created and run successfully without crashing or hitting an `activeDeadlineSeconds` deadline.
- Just around the time the pods are about to complete their work and move from `Running` to `Completed`, one of them is selected for eviction by the [Descheduler](https://github.com/kubernetes-sigs/descheduler)
- The eviction is successful, and results in a replacement pod being created.

In terms of frequency, we don't see this problem often - perhaps a couple of times over hundreds of jobs - but it is a persistent issue that we've seen over months.

### What did you expect to happen?

I would expect a replacement pod not to have been created, as all three pods appear to have completed successfully, and the PodDisruptionBudget should protect them from a descheduler-triggered eviction.

### How can we reproduce it (as minimally and precisely as possible)?

I've come up with a crude reproducible testcase that shows the problem roughly 4 out of 5 times against a [kind](https://kind.sigs.k8s.io) cluster. It's automated in the shell script below. Obviously I don't have the descheduler running in that kind cluster, so I have a repeated loop of eviction attempts (via the [kubectl-evict plugin](https://github.com/ueokande/kubectl-evict)) which I think exhibits the same behaviour as a descheduler-initiated eviction attempt happening at the appropriate point to trigger to issue.

```
#!/usr/bin/env bash

kubectl --context kind create ns troubleshooting
kubectl --context kind -n troubleshooting delete job/my-test-job pdb/my-test-job-pdb

cat << EOF | kubectl --context kind -n troubleshooting apply -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: my-test-job
spec:
  completions: 3
  parallelism: 3
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: my-test-job
    spec:
      containers:
        - name: alpine
          image: alpine:3.14
          command: ["sleep", "1m"]
          resources:
            requests:
              cpu: 0m
              memory: 16Mi
            limits:
              memory: 16Mi
      restartPolicy: Never
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-test-job-pdb
spec:
  selector:
    matchLabels:
      app: my-test-job
  minAvailable: 3
EOF

# Wait about a minute for the job to complete
echo "Waiting for job to near completion"
sleep 60

# Pick a pod to evict
podToEvict=$(kubectl --context kind -n troubleshooting get pods | tail -n1 | awk '{ print $1 }')
echo "Will evict $podToEvict"

# Repeatedly try to evict in an attempt to hit the window of the problem
while true; do
  kubectl evict --context kind -n troubleshooting pod/$podToEvict
  result=$?
  if [[ "$result" = "0" ]]; then
    exit
  fi
done
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-19T15:39:43Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None - reproduces in a local kind cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_ID="22.10"
VERSION="22.10 (Kinetic Kudu)"
VERSION_CODENAME=kinetic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=kinetic
LOGO=ubuntu-logo
$ uname -a
Linux agi10-HP-Z440-Workstation 5.19.0-35-generic #36-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 3 18:36:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
# Install the kubectl-evict plugin for use in the testcase
go install github.com/ueokande/kubectl-evict@latest
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
do PDBs support Jobs? they don't implement /scale, which is how PDB knows how many pods are expected

**Comment by liggitt** [comment]
I guess it only works with a numeric minAvailable... a percentage-based minAvailable or a maxAvailable PDB would not work with a job

**Comment by mimowo** [comment]
Appears related to [#115844](https://github.com/kubernetes/kubernetes/issues/115844). 
cc @kannon92

**Comment by kannon92** [comment]
/assign @kannon92 

I will look into this and see if #115844 can resolve this.

**Comment by kannon92** [comment]
Hello, I got around to try and reproduce this.  

I'm unclear with what is expected behavior here.  

When I try and reproduce this, I see the following logs:

```
Will evict my-test-job-xxgr8
Error: Cannot evict pod as it would violate the pod's disruption budget.
Error: Cannot evict pod as it would violate the pod's disruption budget.
Error: Cannot evict pod as it would violate the pod's disruption budget.
pod default/my-test-job-xxgr8 evicted
```

I do not see a new pod being created if the pod is marked as completed.  I do see that we evict when the pod is completed.  

If I start the evicting long after the pods all complete, eviction just happens without any error.

I am using Kubernetes 1.25.0.

**Comment by alangibson01** [comment]
Thanks for looking at this.

In this particular use case, it looks to me that while all three pods are still in the "running" state, the pod disruption budget prevents any of them from being evicted, which is what I would expect.

However, there appears to be a short time window around when a pod is transitioning to the "completed" state, where it is possible for that pod to be terminated and a new pod to be created. I wouldn't have expected it to be possible to evict a pod which has finished running.

That's the part I don't expect - in the example I supplied, `completions` for the owning job is set to 3 and when a new pod is created then it leads to having more 4 pods end up in the completed state, rather than 3.

I hope that clears things up.

**Comment by kannon92** [comment]
Could you try a later version of kubernetes and see if you can replicate?  I didn’t see this behavior when I tested.  I’d see an eviction but no creation

**Comment by alangibson01** [comment]
Thanks again! I've just checked and this reproduces in v1.22, v1.23 and v1.24 but not in v1.25.

I'll close this issue now.
