### ISSUE TITLE
Failure cluster [cd845a0b...] Kubernetes e2e suite: [It] [sig-storage] PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted.

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116357]
### Failure cluster [cd845a0bb31aa9c849f7](https://go.k8s.io/triage#cd845a0bb31aa9c849f7)
The test flakes more recently.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/2010320/223633230-55cc231e-c4e9-4d63-9148-1eb8d9218015.png">

##### Error text:
```
error during ./hack/ginkgo-e2e.sh --ginkgo.skip=\[Driver:.gcepd\]|\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\]|csi-hostpath-v0 --minStartupPods=8 --report-dir=/workspace/_artifacts --disable-log-dump=true (interrupted): exit status 1
```
#### Recent failures:
[2023/3/8 04:38:02 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1633205365690601472)
[2023/3/8 03:53:05 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1633194041027858432)
[2023/3/8 03:08:01 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1633182716130234368)
[2023/3/8 02:27:01 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1633172397592940544)
[2023/3/8 01:43:02 ci-kubernetes-e2e-gci-gce-alpha-enabled-default](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1633161325280497664)

> { failed [FAILED] pv "nfs-rrjws" phase did not become Available: PersistentVolume nfs-rrjws not in phase Available within 3m0s
In [It] at: test/e2e/storage/persistent_volumes.go:295 @ 03/07/23 20:06:41.084
}

/kind failing-test

/kind flake
/sig  node storage

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-triage/index.html#46618d138903e88accff

this link maybe more accurate.

**Comment by aojea** [comment]
This is permanent failing in the alpha job https://testgrid.k8s.io/google-gce#gci-gce-alpha-enabled-default

@msau42 can we check the problem or triage it in sig-storage?

it seems that the phase nevers moves to "available" 

```
May  2 08:35:19.357: INFO: Unexpected error: 
    <*fmt.wrapError | 0xc002cfc480>: 
    pv "nfs-pjmfs" phase did not become Available: PersistentVolume nfs-pjmfs not in phase Available within 3m0s
    {
        msg: "pv \"nfs-pjmfs\" phase did not become Available: PersistentVolume nfs-pjmfs not in phase Available within 3m0s",
        err: <*errors.errorString | 0xc001064440>{
            s: "PersistentVolume nfs-pjmfs not in phase Available within 3m0s",
        },
```

**Comment by msau42** [comment]
Looks like starting the recycle operation failed:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1653418759605456896/artifacts/bootstrap-e2e-master/kube-controller-manager.log
```
I0502 15:38:29.078113       9 recycler_client.go:68] cannot start watcher for pod default/recycler-for-nfs-w8ds7: the server rejected our request due to an error in our request (get events)
I0502 15:38:29.078156       9 pv_controller.go:926] "persistentvolume-binder: Updating updateVolumePhaseWithEvent" volumeName="nfs-w8ds7" setPhase=Failed
I0502 15:38:29.078169       9 pv_controller.go:896] "persistentvolume-binder: Updating PersistentVolume" volumeName="nfs-w8ds7" setPhase=Failed
```

**Comment by liggitt** [comment]
is the client used in the test built from HEAD or in an image that may be old?

this looks relevant:
```
	// owner: @p0lyn0mial
	// alpha: v1.27
	//
	// Allow the API server to stream individual items instead of chunking
	WatchList featuregate.Feature = "WatchList"
```

cc @p0lyn0mial @wojtek-t

**Comment by msau42** [comment]
This client is in kube-controller-manager so it should be from head.

**Comment by msau42** [comment]
More debugging here:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1683046925965519

Looks like it is related to the `WatchList` feature and it's triggered by `resourceVersion == 0`

**Comment by p0lyn0mial** [comment]
So, [the test grid](https://testgrid.k8s.io/google-gce#gci-gce-alpha-enabled-default) looks better since yesterday. 

The test (`PersistentVolumes NFS when invoking the Recycle reclaim policy should test that a PV becomes Available and is clean after the PVC is deleted`) that was previously permanently failing is green now.

There are some sporadic failures for the whole job but I don't think they are related to the previous issue.
Are we okay with closing this issue ?

**Comment by msau42** [comment]
yup that looks good to me thanks!
/close
