### ISSUE TITLE
failed to pull image registry.k8s.io | Freshly installation - cluster creation is failing 

### ISSUE THREAD

**Issue by heisnamsanjay** [kubernetes/kubernetes#116316]
### What happened?

Install on a Server where there is a proxy to connect to the internet :

export the proxy - HTTP_PROXY and HTTPS_PROXY correctly and can curl to any links that are working 

runtime environment: containers

unable to initialize and completely stuck - unable to create clusters

sudo kubeadm init --pod-network-cidr=10.10.0.0/16 --control-plane-endpoint=16.32.12.201 --ignore-preflight-errors=CPU --cri-socket /run/containerd/containerd.sock --kubernetes-version=v1.26.2 --v=5 --upload-certs
W0306 16:50:47.510858 1955195 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/run/containerd/containerd.sock". Please update your configuration!
I0306 16:50:47.511685 1955195 interface.go:432] Looking for default routes with IPv4 addresses
I0306 16:50:47.511724 1955195 interface.go:437] Default route transits interface "ens160"
I0306 16:50:47.512017 1955195 interface.go:209] Interface ens160 is up
I0306 16:50:47.512277 1955195 interface.go:257] Interface "ens160" has 2 addresses :[16.32.12.201/23 fe80::250:56ff:fea1:560c/64].
I0306 16:50:47.512321 1955195 interface.go:224] Checking addr  16.32.12.201/23.
I0306 16:50:47.512345 1955195 interface.go:231] IP found 16.32.12.201
I0306 16:50:47.512379 1955195 interface.go:263] Found valid IPv4 address 16.32.12.201 for interface "ens160".
I0306 16:50:47.512410 1955195 interface.go:443] Found active IP 16.32.12.201 
I0306 16:50:47.512463 1955195 kubelet.go:196] the value of KubeletConfiguration.cgroupDriver is empty; setting it to "systemd"
[init] Using Kubernetes version: v1.26.2
[preflight] Running pre-flight checks
I0306 16:50:47.573862 1955195 checks.go:568] validating Kubernetes and kubeadm version
I0306 16:50:47.574012 1955195 checks.go:168] validating if the firewall is enabled and active
I0306 16:50:47.603109 1955195 checks.go:203] validating availability of port 6443
I0306 16:50:47.604955 1955195 checks.go:203] validating availability of port 10259
I0306 16:50:47.605130 1955195 checks.go:203] validating availability of port 10257
I0306 16:50:47.605308 1955195 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-apiserver.yaml
I0306 16:50:47.605457 1955195 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-controller-manager.yaml
I0306 16:50:47.605515 1955195 checks.go:280] validating the existence of file /etc/kubernetes/manifests/kube-scheduler.yaml
I0306 16:50:47.605599 1955195 checks.go:280] validating the existence of file /etc/kubernetes/manifests/etcd.yaml
I0306 16:50:47.605650 1955195 checks.go:430] validating if the connectivity type is via proxy or direct
	[WARNING HTTPProxy]: Connection to "https://16.32.12.201" uses proxy "http://web-proxy.houston.softwaregrp.net:8080". If that is not intended, adjust your proxy settings
I0306 16:50:47.606013 1955195 checks.go:469] validating http connectivity to first IP address in the CIDR
	[WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://web-proxy.houston.softwaregrp.net:8080". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
I0306 16:50:47.606222 1955195 checks.go:469] validating http connectivity to first IP address in the CIDR
	[WARNING HTTPProxyCIDR]: connection to "10.10.0.0/16" uses proxy "http://web-proxy.houston.softwaregrp.net:8080". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
I0306 16:50:47.606412 1955195 checks.go:104] validating the container runtime
I0306 16:50:47.694063 1955195 checks.go:329] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0306 16:50:47.694353 1955195 checks.go:329] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0306 16:50:47.694457 1955195 checks.go:644] validating whether swap is enabled or not
I0306 16:50:47.694587 1955195 checks.go:370] validating the presence of executable crictl
I0306 16:50:47.694703 1955195 checks.go:370] validating the presence of executable conntrack
I0306 16:50:47.694773 1955195 checks.go:370] validating the presence of executable ip
I0306 16:50:47.694826 1955195 checks.go:370] validating the presence of executable iptables
I0306 16:50:47.694880 1955195 checks.go:370] validating the presence of executable mount
I0306 16:50:47.694966 1955195 checks.go:370] validating the presence of executable nsenter
I0306 16:50:47.695023 1955195 checks.go:370] validating the presence of executable ebtables
I0306 16:50:47.695073 1955195 checks.go:370] validating the presence of executable ethtool
I0306 16:50:47.695116 1955195 checks.go:370] validating the presence of executable socat
I0306 16:50:47.695166 1955195 checks.go:370] validating the presence of executable tc
I0306 16:50:47.695210 1955195 checks.go:370] validating the presence of executable touch
I0306 16:50:47.695294 1955195 checks.go:516] running all checks
I0306 16:50:47.734352 1955195 checks.go:401] checking whether the given node name is valid and reachable using net.LookupHost
I0306 16:50:47.735011 1955195 checks.go:610] validating kubelet version
I0306 16:50:47.940787 1955195 checks.go:130] validating if the "kubelet" service is enabled and active
I0306 16:50:47.995422 1955195 checks.go:203] validating availability of port 10250
I0306 16:50:47.995790 1955195 checks.go:203] validating availability of port 2379
I0306 16:50:47.995997 1955195 checks.go:203] validating availability of port 2380
I0306 16:50:47.996101 1955195 checks.go:243] validating the existence and emptiness of directory /var/lib/etcd
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
I0306 16:50:47.996809 1955195 checks.go:832] using image pull policy: IfNotPresent
I0306 16:50:48.089863 1955195 checks.go:849] pulling: registry.k8s.io/kube-apiserver:v1.26.2
I0306 16:50:49.168692 1955195 checks.go:849] pulling: registry.k8s.io/kube-controller-manager:v1.26.2
I0306 16:50:50.249908 1955195 checks.go:849] pulling: registry.k8s.io/kube-scheduler:v1.26.2
I0306 16:50:51.376856 1955195 checks.go:849] pulling: registry.k8s.io/kube-proxy:v1.26.2
I0306 16:50:52.541933 1955195 checks.go:849] pulling: registry.k8s.io/pause:3.9
I0306 16:50:53.699463 1955195 checks.go:849] pulling: registry.k8s.io/etcd:3.5.6-0
I0306 16:50:54.880139 1955195 checks.go:849] pulling: registry.k8s.io/coredns/coredns:v1.9.3
[preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.26.2: output: E0306 16:50:49.085582 1955380 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-apiserver/manifests/v1.26.2\": EOF" image="registry.k8s.io/kube-apiserver:v1.26.2"
time="2023-03-06T16:50:49-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-apiserver:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-apiserver:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-apiserver/manifests/v1.26.2\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-controller-manager:v1.26.2: output: E0306 16:50:50.157162 1955452 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-controller-manager/manifests/v1.26.2\": EOF" image="registry.k8s.io/kube-controller-manager:v1.26.2"
time="2023-03-06T16:50:50-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-controller-manager:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-controller-manager:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-controller-manager/manifests/v1.26.2\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-scheduler:v1.26.2: output: E0306 16:50:51.278079 1955518 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-scheduler/manifests/v1.26.2\": EOF" image="registry.k8s.io/kube-scheduler:v1.26.2"
time="2023-03-06T16:50:51-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-scheduler:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-scheduler:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-scheduler/manifests/v1.26.2\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/kube-proxy:v1.26.2: output: E0306 16:50:52.454204 1955664 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-proxy/manifests/v1.26.2\": EOF" image="registry.k8s.io/kube-proxy:v1.26.2"
time="2023-03-06T16:50:52-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/kube-proxy:v1.26.2\": failed to resolve reference \"registry.k8s.io/kube-proxy:v1.26.2\": failed to do request: Head \"https://registry.k8s.io/v2/kube-proxy/manifests/v1.26.2\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/pause:3.9: output: E0306 16:50:53.599460 1955741 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to resolve reference \"registry.k8s.io/pause:3.9\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.9\": EOF" image="registry.k8s.io/pause:3.9"
time="2023-03-06T16:50:53-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/pause:3.9\": failed to resolve reference \"registry.k8s.io/pause:3.9\": failed to do request: Head \"https://registry.k8s.io/v2/pause/manifests/3.9\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/etcd:3.5.6-0: output: E0306 16:50:54.775681 1955886 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/etcd:3.5.6-0\": failed to resolve reference \"registry.k8s.io/etcd:3.5.6-0\": failed to do request: Head \"https://registry.k8s.io/v2/etcd/manifests/3.5.6-0\": EOF" image="registry.k8s.io/etcd:3.5.6-0"
time="2023-03-06T16:50:54-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/etcd:3.5.6-0\": failed to resolve reference \"registry.k8s.io/etcd:3.5.6-0\": failed to do request: Head \"https://registry.k8s.io/v2/etcd/manifests/3.5.6-0\": EOF"
, error: exit status 1
	[ERROR ImagePull]: failed to pull image registry.k8s.io/coredns/coredns:v1.9.3: output: E0306 16:50:55.895795 1955955 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.9.3\": EOF" image="registry.k8s.io/coredns/coredns:v1.9.3"
time="2023-03-06T16:50:55-06:00" level=fatal msg="pulling image: rpc error: code = Unknown desc = failed to pull and unpack image \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to resolve reference \"registry.k8s.io/coredns/coredns:v1.9.3\": failed to do request: Head \"https://registry.k8s.io/v2/coredns/coredns/manifests/v1.9.3\": EOF"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
error execution phase preflight
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:260
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:446
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
	cmd/kubeadm/app/cmd/phases/workflow/runner.go:232
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdInit.func1
	cmd/kubeadm/app/cmd/init.go:112
github.com/spf13/cobra.(*Command).execute
	vendor/github.com/spf13/cobra/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
	vendor/github.com/spf13/cobra/command.go:1040
github.com/spf13/cobra.(*Command).Execute
	vendor/github.com/spf13/cobra/command.go:968
k8s.io/kubernetes/cmd/kubeadm/app.Run
	cmd/kubeadm/app/kubeadm.go:50
main.main
	cmd/kubeadm/kubeadm.go:25
runtime.main
	/usr/local/go/src/runtime/proc.go:250
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1594
k8s-master1 $ 

### What did you expect to happen?

Unable to pull images even after the proxy are exported and update the proxy details under /etc/environment file

### How can we reproduce it (as minimally and precisely as possible)?

Not sure if I can reproduce it, I hope if the proxy settings  are not configured correctly - it might create the same problem as what it is facing now

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:39:03Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?
k8s-master1 $ 
```

</details>

### Cloud provider

<details>
NA

</details>

### OS version

cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Install tools

<details>
NA
</details>

### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubeadm/issues/182#issuecomment-1137419094

/kind support

**Comment by mengjiao-liu** [comment]
In my environment, I can normally pull the corresponding images, so I think it is also the proxy config problem.

**Comment by heisnamsanjay** [comment]
I dont understand what are the relevant proxy config step - that I need to do. I have installed lower version 1.22/1.23 in the past on the same nodes, so the only setting I need to do is to export the proxy from the shell plus I updated /etc/environment only. 

Could you recommend some of the steps that I can take care for such proxy configuration

**Comment by heisnamsanjay** [comment]
https://github.com/kubernetes/kubeadm/issues/182#issuecomment-1137419094


by setting HTTP_PROXY &/ HTTPS_PROXY in /etc./environment or exporting it directly you are setting the proxy for the processes that you will run under your shell process.
kubeadm is using containerd service to download the images therefore you need to set the systemctl env

sudo systemctl set-environment HTTP_PROXY=127.0.0.1:1080
sudo systemctl set-environment HTTPS_PROXY=127.0.0.1:1080
sudo systemctl restart containerd.service
then you can pull the packages with

sudo kubeadm config images pull



Thank you All (:

**Comment by dryleaf** [comment]
Any updates on this issue?

**Comment by heisnamsanjay** [comment]
I think this is fixed --> Please check the inputs that I gave, I followed them and it worked for me
