### ISSUE TITLE
Node controller should delete pods assigned to deleted nodes

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#11631]
Forked from https://github.com/GoogleCloudPlatform/kubernetes/issues/1366#issuecomment-123096872.

**Comment by bgrant0607** [comment]
cc @gmarek @davidopp, since we were just discussing this

**Comment by gmarek** [comment]
I'm assigning myself to it for now, so I won't forget about this. I'll try to fix this next week if I won't get anything more important.

**Comment by roberthbailey** [comment]
I found this issue title a bit confusing, but after reading through the linked issue's comments, it appears to mean that we shouldn't have pods assigned to nodes that don't exist in etcd. 

In particular, this doesn't have to do with nodes deleted from the cloud provider: we already have logic to catch that case (["delete the node **and all pods scheduled on the node**"](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/nodecontroller/nodecontroller.go#L402-L420), emphasis added), and it sounds like that logic needs to be made a bit more generic. We should be able to remove the `deletePods` call from that case and rely on this new behavior (reconciler?) to handle it properly.

**Comment by gmarek** [comment]
@roberthbailey - I believe you're right. The problem we have is that NodeController do not react on Node Deletion. I'll write a PR that adds this.

**Comment by gmarek** [comment]
Related to #6052

**Comment by bgrant0607** [comment]
cc @nikhiljindal

**Comment by timothysc** [comment]
cc @jayunit100

**Comment by smarterclayton** [comment]
Pod graceful deletion also needs to be part of this - it's blocked from being correct (and possibly delivered) until this particular controller.  Because graceful deletion cleanup is a primary responsibility of the kubelet, when nodes die there needs to be a loop that ensures the pod is eventually deleted from etcd within some multiple of the user's requested grace period.  Also, during namespace deletion an unresponsive node can block completion (unless we switch to an all at once deletion via a recursive tree delete).

**Comment by smarterclayton** [comment]
Comment about invariants graceful adds https://github.com/GoogleCloudPlatform/kubernetes/pull/12055#issuecomment-126718014

**Comment by smarterclayton** [comment]
The fix doesn't fully close this issue - if the node controller crashes before delete node completes pods will be left behind.  We still have to have something to maintain the invariant

**Comment by davidopp** [comment]
That's a great point.

I guess possible solutions are
* delete the pods from the "delete node" REST handler, instead of in node controller
* periodically scan all pods in the system an delete the ones whose node does not exist

**Comment by smarterclayton** [comment]
The latter is being discussed in a similar issue - I hit most of this while
testing graceful deletion and the decision to not use TTL means we need to
watch pods as well anyway for some edge cases.

On Aug 6, 2015, at 10:31 PM, David Oppenheimer <notifications@github.com>
wrote:

That's a great point.

I guess possible solutions are

   - delete the pods from the "delete node" REST handler, instead of in
   node controller
   - periodically scan all pods in the system an delete the ones whose node
   does not exist

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11631#issuecomment-128518659>
.

**Comment by davidopp** [comment]
Ah, I guess you're talking about #12055 and #9165 (and related to #7660).

I wonder if we should revert #12277 to keep the system simpler, since the daemon you're talking about could handle this fully anyway.

**Comment by smarterclayton** [comment]
I merged Dawns changes into mine - it doesn't make the system worse I don't
think (but I agree we should reduce the complexity of node controller when
we introduce the other controller).

On Fri, Aug 7, 2015 at 2:59 AM, David Oppenheimer <notifications@github.com>
wrote:

> Ah, I guess you're talking about #12055
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/12055> and #9165
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/9165> (and
> related to #7660
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/7660>).
>
> I wonder if we should revert #12277
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/12277> to keep
> the system simpler, since the daemon you're talking about could handle this
> fully anyway.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/11631#issuecomment-128616880>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by nikhiljindal** [comment]
Its clear that NodeController cant ensure that all pods assigned to deleted nodes are deleted.
We are discussing the GC controller in https://github.com/GoogleCloudPlatform/kubernetes/issues/7660 which will clear such pods.

Should we close this issue?

**Comment by jdef** [comment]
xref https://github.com/mesosphere/kubernetes-mesos/issues/43

**Comment by gmarek** [comment]
@smarterclayton - do you think it's fully solved now?

**Comment by smarterclayton** [comment]
The iterative part (node controller side, yes).  But not when an end user
deletes a node in the absence of a could provider.  That's dependent on a
GC, but we have a separate issue to track that (right?)

On Aug 31, 2015, at 7:14 AM, Marek Grabowski <notifications@github.com>
wrote:

@smarterclayton <https://github.com/smarterclayton> - do you think it's
fully solved now?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/11631#issuecomment-136337215>
.

**Comment by gmarek** [comment]
What do you mean by 'not when end user deletes a node in the absence of a cloud provider'? IIRC NodeController removed Pods from explicitly deleted Nodes, as long as it wasn't recently restarted.

**Comment by smarterclayton** [comment]
If node controller is restarted after a user deletes a node it won't clean
the pods off, and then when it starts up again it doesn't know that the
node ever existed.

On Mon, Aug 31, 2015 at 10:47 AM, Marek Grabowski <notifications@github.com>
wrote:

> What do you mean by 'not when end user deletes a node in the absence of a
> cloud provider'? IIRC NodeController removed Pods from explicitly deleted
> Nodes, as long as it wasn't recently restarted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/11631#issuecomment-136376456>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by gmarek** [comment]
Right, that part is true. I just didn't understood how it relates to existence of a cloud provider. I don't know anything about an issue for GC. @bgrant0607 ?

**Comment by smarterclayton** [comment]
That's https://github.com/kubernetes/kubernetes/issues/7660

**Comment by gmarek** [comment]
I believe that we should close this in favor of #7660 then.

**Comment by davidopp** [comment]
#7660 didn't start out as being about deleting pods on deleted nodes (it was just about GCing dead pods in general), but it seems to have meandered into that territory, so I agree we should close this one.
