### ISSUE TITLE
Top flake in integration test: TestChangeCRD

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116364]
### Which jobs are flaking?

TestChangeCRD 

      "k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration TestChangeCRD": 37,
https://storage.googleapis.com/k8s-metrics/flakes-latest.json

### Which tests are flaking?

https://github.com/kubernetes/kubernetes/blob/e390791e5fdddd6d17504ea200e0a86f12cc0525/staging/src/k8s.io/apiextensions-apiserver/test/integration/change_test.go#L143

### Since when has it been flaking?

Recently, not sure the date.

### Testgrid link

https://storage.googleapis.com/k8s-metrics/flakes-latest.json

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116354/pull-kubernetes-integration/1633336232408780800

### Relevant SIG(s)

/sig api-machinery

**Comment by liggitt** [comment]
also flaking in https://testgrid.k8s.io/sig-release-master-blocking#integration-master&width=20

weirdly, this doesn't show up at all in https://storage.googleapis.com/k8s-triage/index.html?test=k8s.io%2Fapiextensions-apiserver%2Ftest%2Fintegration

**Comment by liggitt** [comment]
cc @alexzielenski 

I can't tell if this is related to the openapi change or not

**Comment by liggitt** [comment]
Actually, I think this is an issue either with the test or with watch behavior, not sure which. The test starts 10 watches, lets them run, then waits for them to exit cleanly, and instead, they are getting watch errors.

I can't tell if the watch errors are expected or not, or if server or watch client behavior changed here or not. Opened https://github.com/kubernetes/kubernetes/pull/116380 to debug further

**Comment by liggitt** [comment]
#115402 and https://github.com/kubernetes/kubernetes/pull/110960 stand out as a recent change to watching

**Comment by liggitt** [comment]
cc @wojtek-t @p0lyn0mial on whether the watching changes in https://github.com/kubernetes/kubernetes/pull/110960 could explain this integration test getting watch errors it didn't previously get

**Comment by liggitt** [comment]
#114925 also stands out

**Comment by liggitt** [comment]
@sttts @tkashem, would #114925 explain this integration test getting watch errors it didn't previously get?

**Comment by tkashem** [comment]
the filter is enabled only when the server run option `ShutdownWatchTerminationGracePeriod` has a positive time duration (the default is zero). I searched the k/k repo, only the unit tests in `apiserver/pkg/server/` enables this filter:

https://github.com/kubernetes/kubernetes/blob/713ded736824d669d9fae9ac4a29b1ec18d66446/staging/src/k8s.io/apiserver/pkg/server/genericapiserver_graceful_termination_test.go#L1010

I did a quick scan of the logs, did not see any graceful termination activity either. I will take a deeper look at the logs

**Comment by liggitt** [comment]
> the filter is enabled only when the server run option `ShutdownWatchTerminationGracePeriod` has a positive time duration (the default is zero). I searched the k/k repo, only the unit tests in `apiserver/pkg/server/` enables this filter:

and all merged changes were limited to that filter?

**Comment by pohly** [comment]
> weirdly, this doesn't show up at all in https://storage.googleapis.com/k8s-triage/index.html?test=k8s.io%2Fapiextensions-apiserver%2Ftest%2Fintegration

This is a Go test, so the entire test output is treated as the failure message. That output is very different from one failure to the other, so in triage we probably have x different "clusters" with one failure in each, instead of one cluster with x failures. I don't know what triage does with such small clusters.

**Comment by tkashem** [comment]
we have changes in handlers/watch.go:
https://github.com/kubernetes/kubernetes/pull/114925/commits/697d96710856f96329a79a2574e109abd2f1626a

only the the filter adds to the request context, I just searched the code base, did not find any other call site for `WithServerShutdownSignal`

by default, `case <-s.ServerShuttingDownCh:` should block (on a nil channel)

If the test is receiving an event, it implies that the following case is executing, right?
https://github.com/kubernetes/kubernetes/blob/713ded736824d669d9fae9ac4a29b1ec18d66446/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/watch.go#L254

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/112152 ??

**Comment by jiahuif** [comment]
Thank you all for deflaking.
