### ISSUE TITLE
When TopologyManagerPolicy is None, there is no need to discover the NUMA topology.

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#116391]
Follow up from: https://github.com/kubernetes/kubernetes/pull/116093/files#r1128138681 See details there.

When `TopologyManagerPolicy` is `None`, there is no need to discover the NUMA topology.

/sig node
/priority backlog
/kind feature
/help-wanted

**Comment by nikzayn** [comment]
@SergeyKanzhelev I would like to take this up.

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev I would like to take this up also can I get more brief information about it?
> 
> code review comments from @liggitt asking that inside the NewManager() implementation, we need to skip **NewPolicyOptions** and **NewNUMAInfo** but when the NumaTopology comes kubelet issue also comes.
> 
> I need some more information to start with this!

When there is no topology manger policy specified, NewManager should be a no-op. Just skip all checks.

**Comment by ffromani** [comment]
> > @SergeyKanzhelev I would like to take this up also can I get more brief information about it?
> > code review comments from @liggitt asking that inside the NewManager() implementation, we need to skip **NewPolicyOptions** and **NewNUMAInfo** but when the NumaTopology comes kubelet issue also comes.
> > I need some more information to start with this!
> 
> When there is no topology manger policy specified, NewManager should be a no-op. Just skip all checks.

Exactly. Just to add: we may need few iterations over the change to get a clean flow in the `NewManager` call.
