### ISSUE TITLE
Cannot bind multiple addresses

### ISSUE THREAD

**Issue by vladimirtiukhtin** [kubernetes/kubernetes#116328]
I can add many --bind-address to kube-apiserver, but only the last one has affect. Providing a comma-separated list to a singe --bind-address option makes the service crash

**Comment by liggitt** [comment]
in the https://github.com/spf13/cobra CLI framework, for flags which do not support accumulating multiple values, the last instance controls the accepted value

you are correct that multiple bind addresses are not supported

/kind support
/close
