### ISSUE TITLE
e2e needed: Service port on other protocol should fail

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#116314]
see https://github.com/cilium/cilium/issues/9207

* A pod listens on port N, on both TCP and UDP.
* A service forwards to port N, *only* TCP.
* Accessing the service via UDP should fail.

**Comment by thockin** [comment]
cc @aojea

**Comment by aojea** [comment]
/assign 

this was caught with hostPort https://github.com/cilium/cilium/issues/21060 , but we should have one for Services
