### ISSUE TITLE
memory pressure during kubeadm init with cgroup V2 , failed result after crashloop 

### ISSUE THREAD

**Issue by dscaravaggi** [kubernetes/kubernetes#116480]
### What happened?

Hi all,
in a test lab with constrained resorces and a bunch of old XEON server
kubeadm init was starting evicting pods and crash loop

I did not succeded installing a cluster, while on the same time K3s was up and running

after 6 hours trobleshooting I revert Linux kernel to cgroup V1

`Debian bullseye - SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
GRUB_CMDLINE_LINUX_DEFAULT="systemd.unified_cgroup_hierarchy=0 quiet" 
`

Is the any additional setup or tunable in order to run  with v2, or other settings in systemd unit service of containerd ?

thanks a lot
Diego 

### What did you expect to happen?

create the cluster as reported in Getting Started

### How can we reproduce it (as minimally and precisely as possible)?

instal Linux Debian from apt with stock containerd 1.4.13
and after follow the getting started guide  

use old hardware and 2GB assigned to VM

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.26.2

</details>

### Cloud provider

<details>
ON PREMISES
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
# paste output here
Linux k8s-lab-01ctl 5.10.0-20-cloud-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
crictl version v1.26.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni calico
</details>

**Comment by dscaravaggi** [comment]
I checked sigs in the official supported OVA for kuberantes:
there is a difference in ubuntu 22.04 LTS and debian bullseye

- https://ubuntu.pkgs.org/22.04/ubuntu-universe-amd64/cgroup-tools_2.0-2_amd64.deb.html
- https://packages.debian.org/bullseye/cgroup-tools  (0.41-11) libcgroup V1 

I suppose that bullseye WILL require V1 settings untill v2 is not fully deployed 
(cgroup V2 is in debian testing unstable / branch)

**Comment by SergeyKanzhelev** [comment]
is the issue is that kubeadm failed to create a cluster? Kubelet may have misconfigured cgroup setting with the whatever runtime is used. But I am not clear if this is created by kubeadm.

/area kubeadm

not sure if this is kubeadm or sig node issue

/triage needs-information

**Comment by SergeyKanzhelev** [comment]
kubelet config and command line arguments as well as runtime configuration may help troubleshoot

**Comment by dscaravaggi** [comment]
> kubelet config and command line arguments as well as runtime configuration may help troubleshoot

containerd was installed esctra-debian-pkg by curl
containerd github.com/containerd/containerd v1.6.19 1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f

kubelet |  1.26.2-00 | https://apt.kubernetes.io kubernetes-xenial/main amd64 Packages
apt install kubelet=1.26.2-00 kubeadm=1.26.2-00 kubectl=1.26.2-00
kubeadm init --config kubeadmconfig.yaml

in the attached tar  

-  cp /etc/kubernetes/kubelet.conf kubelet_redacted.txt
-  containerd config dump >  containerd-config-dump.txt
-  kubeadmconfig.yaml
-  kubectl cluster-info dump > /tmp/cluster-info-dump.txt


[inc-116480.tar.gz](https://github.com/kubernetes/kubernetes/files/11049342/inc-116480.tar.gz)

**Comment by dscaravaggi** [comment]
at the end, I think I found the bug in my installation sequence
I scratched a new vm from _debian-11.6.0-amd64-netinst.iso_ cd-rom
and after I followed exactly same sequence of commands reported in the cloud init of https://github.com/kubernetes-sigs/image-builder/tree/v0.1.14/images/capi/packer 

```bash
containerd config default |  tee /etc/containerd/config.toml
sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
```

this 2 commands are required in order to get cgroup V2 fully oprtational 

thanks to: https://www.techrepublic.com/article/install-containerd-ubuntu/ 

the containerd containerd/config.toml should be documented **better** in the install guide (https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd)

and also the proof of cgroup v2 should be verified as output in:
  `containerd config dump | fgrep -i systemd`
  
in any case @SergeyKanzhelev thanks a lot for your help, I think we can close this investigation

```bash
NAMESPACE     NAME                                      READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-57b57c56f-l22t8   1/1     Running   0          23m
kube-system   calico-node-smrnk                         1/1     Running   0          23m
kube-system   coredns-787d4945fb-4k2hv                  1/1     Running   0          28m
kube-system   coredns-787d4945fb-zqdhx                  1/1     Running   0          28m
kube-system   etcd-scratch-deb                          1/1     Running   0          28m
kube-system   kube-apiserver-scratch-deb                1/1     Running   0          28m
kube-system   kube-controller-manager-scratch-deb       1/1     Running   0          28m
kube-system   kube-proxy-qzjvm                          1/1     Running   0          28m
kube-system   kube-scheduler-scratch-deb                1/1     Running   0          28m
```

**Comment by dscaravaggi** [comment]
After re-reading the guide...

![image](https://user-images.githubusercontent.com/9715775/227264755-c8b6b619-b51e-42b7-b89b-36f679be46f4.png)

**Comment by dscaravaggi** [comment]
can be closed
