### ISSUE TITLE
events.k8s.io/v1 api does not have changes in place mentioned in the Deprecated API Migration Guide

### ISSUE THREAD

**Issue by wanlonghenry** [kubernetes/kubernetes#116444]
### What happened?

From the Deprecated API Migration Guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/,  since v1.19, the events.k8s.io/v1 has been using the new reportingController and reportingInstance to replace the decrecated source.component and source.host. But when I checked the Kube events in a cluster with version 1.26.0, those new fields are empty and the supposed to be deprecated fields have not been renamed.

### What did you expect to happen?

Seeing the values in the new fields like reportingController and reportingInstance

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an Kubernetes cluster with version 1.26.0
2. Generate some Kube events
3. Check the Kube events details for the field of reportingController, reportingInstance, source.component, source.host

### Kubernetes version

<details>

Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-11T00:15:47Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
I have also encountered this issue in my local 1.26.0 Kubernetes cluster, which does not align with the deprecation guide described in https://kubernetes.io/docs/reference/using-api/deprecation-guide/#event-v125. I believe I can investigate this further

**Comment by wanlonghenry** [comment]
@HirazawaUi  Thank you for making the PR to fix this! Also added a comment in the PR for the doc update.
