### ISSUE TITLE
Performance degradation in scheduler with additional metrics for tracking go-routines

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#116427]
### What happened?

We observed degradation in scheduling throughput, putting it under 100 pods/s

pprof points to https://github.com/kubernetes/kubernetes/pull/112003/files#diff-bdc8ab11c11340bf2786fe2a0a3900856fa6d098c0c217ba6b25de33ca22a506R58-R59

![image](https://user-images.githubusercontent.com/1299064/224100503-708cb729-6a4c-48fe-b634-66421dd8e180.png)

/sig scheduling
/kind regression

### What did you expect to happen?

100 pods/s

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

<details>

```console
1.26
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
/assign @mborsz 

cc @sanposhiho

**Comment by sanposhiho** [comment]
Oh.. sorry for the degradation and thanks @alculquicondor @mborsz for working on this. 🙇 

This time, as goroutine metric is called every time goroutine is created, we observed the clear performance degradation.
But, there are actually many other metrics which is stored directly by calling `WithLabelValues` everytime.
So, for the future direction, is it better for the performance to move all other metrics to store via [`MetricAsyncRecorder`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metric_recorder.go)? (like `PluginExecutionDuration` metric)

**Comment by alculquicondor** [comment]
No need to be sorry. Just tagging you as FYI so that we are aware of this kind of performance penalties in future reviews :)

**Comment by alculquicondor** [comment]
> So, for the future direction, is it better (slightly?) for the performance to move all other metrics to store via [`MetricAsyncRecorder`](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/metrics/metric_recorder.go)? (like `PluginExecutionDuration` metric)

No, this code is too complex to be worth it. The rest of the metrics usage doesn't show up in pprofs, so no need to optimize further for now. We just need to be diligent not to call `WithLabelValues` within critical routines when they all share the same values.

**Comment by sanposhiho** [comment]
> We just need to be diligent not to call WithLabelValues within critical routines when they all share the same values.

👍
