### ISSUE TITLE
InitContainers tests fail in CRI-O jobs

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#116418]
### Which jobs are failing?

- ci-crio-cgroupv1-node-e2e-conformance
- ci-crio-cgroupv2-node-e2e-conformance

### Which tests are failing?

- [It] [sig-node] InitContainers [NodeConformance] should not launch regular containers if an init container fails expand_more
- [It] [sig-node] InitContainers [NodeConformance] should not launch regular containers if an init container fails expand_more 

### Since when has it been failing?

Since the merge of https://github.com/kubernetes/kubernetes/pull/115984

### Testgrid link

https://testgrid.k8s.io/sig-node-release-blocking

### Reason for failure (if possible)

I think it's a SELinux issue which prevents writing to the hostpath.

### Anything else we need to know?

From the kernel logs:

```
Mar 09 13:59:04 tmp-node-e2e-45fde66f-fedora-coreos-37-20230218-3-0-gcp-x86-64 kernel: audit: type=1400 audit(1678370344.407:1971): avc:  denied  { write } for  pid=22493 comm="sh" name="init-container-3336600979" dev="tmpfs" ino=433 scontext=system_u:system_r:container_t:s0:c334,c795 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0
Mar 09 13:59:04 tmp-node-e2e-45fde66f-fedora-coreos-37-20230218-3-0-gcp-x86-64 kernel: audit: type=1300 audit(1678370344.407:1971): arch=c000003e syscall=2 success=no exit=-13 a0=1e93ad8 a1=441 a2=1b6 a3=0 items=0 ppid=22482 pid=22493 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sh" exe="/bin/sh" subj=system_u:system_r:container_t:s0:c334,c795 key=(null)
Mar 09 13:59:04 tmp-node-e2e-45fde66f-fedora-coreos-37-20230218-3-0-gcp-x86-64 kernel: audit: type=1327 audit(1678370344.407:1971): proctitle=7368002D63006563686F206064617465202B2573602027726567756C61722D31205374617274696E6727203E3E202F7368617265642F6F75747075743B206563686F206064617465202B2573602027726567756C61722D312044656C6179696E67203127203E3E202F7368617265642F6F75747075743B20736C65657020313B
Mar 09 13:59:04 tmp-node-e2e-45fde66f-fedora-coreos-37-20230218-3-0-gcp-x86-64 kernel: audit: type=1400 audit(1678370344.408:1972): avc:  denied  { write } for  pid=22493 comm="sh" name="init-container-3336600979" dev="tmpfs" ino=433 scontext=system_u:system_r:container_t:s0:c334,c795 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0
```

### Relevant SIG(s)

/sig node

**Comment by harche** [comment]
Does that new path need to be added here? https://github.com/cri-o/cri-o/blob/f85542573ffd2c13a998a1d7d5d3f4b51b49c92c/scripts/node_e2e_installer#L23

**Comment by saschagrunert** [comment]
No I think we have to change and recompile our custom selinux module: https://console.cloud.google.com/storage/browser/_details/cri-o/selinux/kubelet-e2e.te;tab=live_object?project=cncf-crio-staging

**Comment by harche** [comment]
cc @SergeyKanzhelev @haircommander

**Comment by SergeyKanzhelev** [comment]
cc @tzneal

**Comment by SergeyKanzhelev** [comment]
> I'm going to update the module to approach a fix, but we may encounter more issues.
> 
> _Edit: Done_

Is there anything else needed to be done? This is a new approach we are trying to test the containers lifecycle. Thank you for raising this

**Comment by tzneal** [comment]
I submitted a fix at https://github.com/kubernetes/kubernetes/pull/116398 , works on the PR tests but not sure how to verify against the real testing infra.

**Comment by harche** [comment]
@tzneal fired a job https://github.com/kubernetes/kubernetes/pull/116398#issuecomment-1462715252

**Comment by tzneal** [comment]
Great, didn't know that was possible! 💡

**Comment by tzneal** [comment]
Tests passed, https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116398/pull-kubernetes-node-crio-e2e/1633925899009134592/

**Comment by saschagrunert** [comment]
We have two green runs now:

- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-conformance/1634099923353866240
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv2-node-e2e-conformance/1634084068666642432
