### ISSUE TITLE
Whether to support the session persistence function at the pod level

### ISSUE THREAD

**Issue by xigua88-66** [kubernetes/kubernetes#116496]
### What would you like to be added?

We are using k8s for cluster management of multiple GPU servers (multiple GPU cards), and the same AI model will be deployed on each GPU machine and provide services. However, a complete use of some AI services requires multiple http requests to complete. We hope that these HTTP requests all run on the same pod, because the data needs to be loaded into the GPU, otherwise other GPU servers or received requests will lack data and the call will fail.

In addition to using ClientIP for session persistence in sessionAffinity, does it support custom session persistence functions, such as defining a group of HTTP requests that need to be forwarded to the same pod?

### Why is this needed?

Customize http request distribution

**Comment by LuBingtan** [comment]
It seems that [Istio ConsistentHashLB](https://istio.io/latest/docs/reference/config/networking/destination-rule/#LoadBalancerSettings-ConsistentHashLB) is just what you are looking for.

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes-sigs/gateway-api/issues/1619

**Comment by neolit123** [comment]
/close
/kind support

please reopen if needed.
