### ISSUE TITLE
proto: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [kubernetes/kubernetes#116497]
### What happened?

Fixed inconsistency and also potential data race in proto/table_unmarshal.go:
u.reqFields is read/written 4 times in proto/table_unmarshal.go; 3 out of 4 times it is protected by u.lock.Lock(); 1 out of 4 times it is read without a Lock, which is in func unmarshal() on L260.
A data race may happen when unmarshal() and other func like computeUnmarshalInfo() are called in parallel.

In order to avoid potential data race here, I use u.lock.RLock(); defer u.lock.RUnlock() to make sure that all usages of items is in critical section.

I don't know whether it is accurate, so I 'm looking forward to your reply.

### What did you expect to happen?

Data Race

### How can we reproduce it (as minimally and precisely as possible)?

A data race may happen when unmarshal() and other func like computeUnmarshalInfo() are called in parallel.

### Kubernetes version

Nil

### Cloud provider

Nil

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nikzayn** [comment]
@UtopiaGitHub I would like to take this up after triage/accepted.

+1 for the docs, so far the best documented issue which I found and thanks for revising this concept.

**Comment by UtopiaGitHub** [comment]
I made the comment in the PR (https://github.com/kubernetes/kubernetes/pull/116596).  But I think what we should protect is the field `u.reqFields` where the operation at vendor/github.com/gogo/protobuf/proto/table_unmarshal.go:L260. Thus, the `u.lock.RLock()` and `defer u.lock.RUnlock()` should be added there.

**Comment by nikzayn** [comment]
@UtopiaGitHub I am not able to see comments on PR (https://github.com/kubernetes/kubernetes/pull/116596)

**Comment by pacoxu** [comment]
See https://github.com/kubernetes/kubernetes/pull/116596#issuecomment-1533077675

> please fix in https://github.com/gogo/protobuf/ and then propose an update to the copy we have in vendor/ directory

The problem should be fixed in `gogo/protobuf` and update the dependency in this repo to include the fix.

/close
