### ISSUE TITLE
A restart Never static pod does not recreate mirror pod when it is deleted

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kubernetes#116483]
### What happened?

We have never fully clarified the behavior of restart=Never mirror pods, but they currently behave in surprising ways.  At minimum, the following questions should be answered and documented:

1. Should the mirror pod be recreated if the kubelet detects it is missing?
2. Should a terminal mirror pod block re-execution of a restart=Never static pod on kubelet restart?

/sig node

### What did you expect to happen?

Uncertain

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a restartPolicy=Never static pod
2. wait for it to reach completion via mirror pod
3. Delete the mirror pod
4. Restart kubelet

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/sig node

static pods will benefit of a nice doc with an state machine diagram 😉

**Comment by smarterclayton** [comment]
I've got a state diagram deck incoming to complement these bugs

**Comment by sftim** [comment]
> I've got a state diagram deck incoming to complement these bugs

[Mermaid](https://www.k8s.dev/blog/2021/12/01/improve-your-documentation-with-mermaid.js-diagrams/) versions welcome, especially for the K8s docs
