### ISSUE TITLE
Kubernetes does not pull all the images from given custom registry

### ISSUE THREAD

**Issue by rishithaminol** [kubernetes/kubernetes#116468]
### What happened?

I have been setting up an airgap installation setup for Kubernetes using kubeadm. I have configured a custom nexus docker repository inside my own network. The issue here is all the containers are pulled as planned but only one container is pulled from an outside registry (Froom the Internet) at the time of `kubeadm init`. The following `docker image ls` output is taken opening the outbound to the internet. But if the outbound to the Internet is disabled `kubeadm init` makes errors and docker says `registry.k8s.io` is unreachable.

The issue I face here is calling an extra registry even if I configured it from `--image-repository="hello.worldzz.xyz:5001"`

Another issue I see here is using pause image multiple times. You can see it on `docker image ls` output below.

This is the command used for initialize the kubelet.

```
kubeadm init --apiserver-advertise-address="10.200.2.6"        \
             --node-name "provis-tf-master01"        \
             --apiserver-cert-extra-sans="hello.worldzz.xyz"  \
             --pod-network-cidr=192.168.0.0/16        \
             --image-repository="hello.worldzz.xyz:5001"        \
             --cri-socket unix:///var/run/cri-dockerd.sock \
             --kubernetes-version 1.24.4 \
             --config ./config.yaml \
             --v=5
```

Extra information needed for anyone.

```
docker registry: hello.worldzz.xyz:5001
kubernetes version: 1.24.11
kubelet version: 1.24.11
kubectl version: 1.24.11
containerization engine: Docker
Operating system: Almalinux 8.7
```

`docker image ls` output
![Screenshot at 2023-03-10 18-59-48](https://user-images.githubusercontent.com/12764759/224330665-4ab2692d-951d-455f-a09c-e95035217530.png)

### What did you expect to happen?

Kubernetes should stop accessing internet when we tell it not to go for Internet

### How can we reproduce it (as minimally and precisely as possible)?

Setup private registry and see

### Kubernetes version

1.24.11

### Cloud provider

No one. It's bare metal

### OS version

Almalinux 8.7

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

cri-docker:0.3.0-3.el8

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico:3.25.0

**Comment by dims** [comment]
@rishithaminol please open an issue with cri-docker, that's the one pulling this pause image. 

for plain old containerd (no docker), there is a `config.toml` file where one can specify the pause image. you will have to figure out where/how cri-dockerd/docker/containerd has the configuration.

/close
