### ISSUE TITLE
[Failing Test] build-master

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#116492]
### Which jobs are failing?

master-blocking

- build-master

### Which tests are failing?

Overall build is failing

![Screenshot from 2023-03-11 09-54-33](https://user-images.githubusercontent.com/73882557/224464710-6ad3dae9-5313-488f-ac73-9de54daa5fd4.png)

### Since when has it been failing?

03-11 02:50 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#build-master

### Reason for failure (if possible)

```
# k8s.io/kubernetes/cmd/genman
/usr/local/go/pkg/tool/linux_amd64/link: running arm-linux-gnueabihf-gcc failed: exit status 1
/usr/lib/gcc-cross/arm-linux-gnueabihf/10/../../../../arm-linux-gnueabihf/bin/ld.gold: internal error in arm_branch_common, at ../../gold/arm.cc:4079
collect2: error: ld returned 1 exit status
```

```
make: *** [Makefile:374: release] Error 1
level=fatal msg="failed to run: running make release: command /usr/bin/make release did not succeed: !!! [0311 03:23:27] Call tree:\n!!! [0311 03:23:27]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)\nmake[1]: *** [Makefile:92: all] Error 1\nmake: *** [Makefile:487: cross] Error 1\n!!! [0311 03:23:28] Call tree:\n!!! [0311 03:23:28]  1: build/../build/common.sh:484 kube::build::run_build_command_ex(...)\n!!! [0311 03:23:28]  2: build/release.sh:36 kube::build::run_build_command(...)\nmake: *** [Makefile:374: release] Error 1\n" 
```

### Relevant SIG(s)

/sig release

**Comment by liggitt** [comment]
this doesn't align exactly with the switch to go1.20.2, but given https://github.com/golang/go/issues/58425#issuecomment-1426346686 that would still be the first place I would recommend looking

1. get a reproducer that clones kubernetes, checks out one of the commits that is failing to build, and does an arm cross-build of the genman binary
2. if that fails, try the build with `GOEXPERIMENT="nounified"`
3. report an issue to https://github.com/golang/go/issues, referencing https://github.com/golang/go/issues/58425#issuecomment-1426346686 and tagging @thanm

**Comment by dims** [comment]
`linux/arm` is still biting us :( So i'd like to propose just removing the platform until we pursue what @liggitt has laid out above

```
[davanum@c889f3bd53ed 06:40] ~/Downloads ⟩ rg "linux/arm: build"
build-log.txt
73:+++ [0310 21:24:14] linux/arm: build started
85:+++ [0310 21:46:46] linux/arm: build finished
134:+++ [0310 21:46:57] linux/arm: build started
140:+++ [0310 21:47:04] linux/arm: build finished
177:+++ [0310 21:49:22] linux/arm: build started
181:+++ [0310 21:51:55] linux/arm: build finished
234:+++ [0310 21:54:56] linux/arm: build started
```

**Comment by dims** [comment]
Let's please land this: https://github.com/kubernetes/kubernetes/pull/115742

**Comment by saschagrunert** [comment]
Tests are green again. I assume we want to follow-up on https://github.com/kubernetes/kubernetes/issues/116492#issuecomment-1464822656 via https://github.com/golang/go/issues/58425#issuecomment-1426346686
