### ISSUE TITLE
triage unit and integration test failures

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#116402]
### What would you like to be added?

TestChangeCRD, an integration test, [flaked a lot](https://github.com/kubernetes/kubernetes/issues/116364) recently. This showed up in https://storage.googleapis.com/k8s-metrics/flakes-latest.json but not in https://storage.googleapis.com/k8s-triage/index.html.

From https://github.com/kubernetes/kubernetes/issues/116364#issuecomment-1460580749:
> This is a Go test, so the entire test output is treated as the failure message. That output is very different from one failure to the other, so in triage we probably have x different "clusters" with one failure in each, instead of one cluster with x failures. I don't know what triage does with such small clusters.

We should find a way to extract failures from the test output and then store that as failure message in the JUnit file. The test output becomes the stderr that spyglass only shows when clicking on that link.

### Why is this needed?

- enables correlating similar unit and integration test failures
- less data to be stored and processed for triaging
- optional: better highlighting of failures in spyglass

/cc @aojea 
/sig testing

**Comment by pohly** [comment]
Here's an example:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116354/pull-kubernetes-integration/1633336232408780800

```
k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/test/integration: TestChangeCRD

{Failed  === RUN   TestChangeCRD
    testserver.go:250: Resolved testserver package path to: "/home/prow/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiextensions-apiserver/pkg/cmd/server/testing"
    testserver.go:139: runtime-config=map[api/all:true]
    testserver.go:140: Starting apiextensions-apiserver on port 34503...
I0308 06:04:08.847174   90307 serving.go:342] Generated self-signed cert (/tmp/apiextensions-apiserver1116080805/apiserver.crt, /tmp/apiextensions-apiserver1116080805/apiserver.key)
I0308 06:04:09.752032   90307 plugins.go:161] Loaded 1 validating admission controller(s) successfully in the following order: ValidatingAdmissionPolicy.
W0308 06:04:09.752412   90307 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0308 06:04:09.752443   90307 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0308 06:04:09.752508   90307 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
W0308 06:04:09.758196   90307 genericapiserver.go:752] Skipping API apiextensions.k8s.io/v1beta1 because it has no resources.
W0308 06:04:09.758394   90307 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
    testserver.go:161: Waiting for /healthz to be ok...
...
E0308 06:04:13.470429   90307 watcher.go:219] watch chan error: rpc error: code = Canceled desc = context canceled
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc000f177c0)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc000f179a0)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc001a09b80)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc00111fea0)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc001a09cc0)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc000f17a40)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc0016d8000)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc000ebf9a0)}
    change_test.go:143: unexpected watch event: watch.Event{Type:"ERROR", Object:(*v1.Status)(0xc000ebfae0)}
W0308 06:04:14.192020   90307 reflector.go:492] k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.1.2.3:12345: connect: connection refused
E0308 06:04:14.192115   90307 reflector.go:141] k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "http://127.1.2.3:12345/api/v1/services?limit=500&resourceVersion=0": dial tcp 127.1.2.3:12345: connect: connection refused
```

Note that spyglass is unable to pick out the failure. Even a human may have difficulties spotting it.

The problem is that `testing.T.Error` is just producing normal log output and marks the test as failed. Adding some special marker to that log message (like "FAIL") is the responsibility of the caller. This is not done consistently, if it is done at all.

**Comment by pohly** [comment]
Here's a potential solution:
- Add Error[f]/Fatal[f] wrappers in k/k/test/utils/ktesting which add `[FAILED]` as message prefix.
- Replace all existing calls with that.
- Forbid the use of testing.T/B.Error through forbidigo (work in progress).
- In https://github.com/kubernetes/kubernetes/blob/master/cmd/prune-junit-xml/prunexml.go, extract `[FAILED]` messages, testify failures and (optionally) Gomega failures as the failure of a test and move the rest of the output into Stderr.

**Comment by pohly** [comment]
Alternative: write a linter which requires `[FAILED]` to be the common prefix of all error messages.

The wrapper approach might make it harder for "go vet" to detect incorrect `t.Fatalf` calls in goroutines. We had broken code like that in staging. If we use wrappers, we need to verify that this check still works.

**Comment by aojea** [comment]
> The problem is that `testing.T.Error` is just producing normal log output and marks the test as failed. Adding some special marker to that log message (like "FAIL") is the responsibility of the caller. This is not done consistently, if it is done at all.

maybe we can discuss this with golang community, it seems like a really nice and important feature to be able to differentiate between the logging and the failure message

**Comment by pohly** [comment]
`go test -failure-prefix="[FAILED] "` - yes, that would be nice.

**Comment by aojea** [comment]
> `go test -failure-prefix="[FAILED] "` - yes, that would be nice.

should I or are you going to open the issue in golang/go?

**Comment by pohly** [comment]
I posted about it here: https://groups.google.com/g/golang-nuts/c/fQrZ1lKRWzo

**Comment by pohly** [comment]
If there's no comment, I can create an issue.

**Comment by liggitt** [comment]
hrmm... I thought we were using json output from tests, which spit out structured data with failure indicators. Is that just for unit tests?

**Comment by pohly** [comment]
We get JUnit XML with separate failure + log output only for E2E tests with Ginkgo.

You are right, there is a `-json` in https://github.com/kubernetes/kubernetes/blob/c67953a2d0255c8c4f5e315b93f28ab599c428e5/hack/make-rules/test.sh#L148.

However, in a `go test` there is no difference between failure and test output, so even with JSON instead of text as intermediate format we get too much text as failure.

**Comment by liggitt** [comment]
I would expect us to use json format for test output, rather than ask go to add text prefixing

**Comment by BenTheElder** [comment]
Yeah, I thought we were wrapping unit tests with gotestsum to emit json => junit.

**Comment by pohly** [comment]
JSON doesn't help. There's no indication there either that a certain output is a test failure. That's because `t.Error` = `t.Log + t.Fail`.

```console
$ cat test/test_test.go
package test

import "testing"

func TestLog(t *testing.T) {
	t.Log("Hello world!")
	t.Error("Huh, what's this?")
}

$ go test ./test
--- FAIL: TestLog (0.00s)
    test_test.go:6: Hello world!
    test_test.go:7: Huh, what's this?
FAIL
FAIL	k8s.io/kubernetes/test	0.003s
FAIL

$ go test -json ./test
{"Time":"2023-03-10T08:19:24.595561773+01:00","Action":"run","Package":"k8s.io/kubernetes/test","Test":"TestLog"}
{"Time":"2023-03-10T08:19:24.595722808+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Test":"TestLog","Output":"=== RUN   TestLog\n"}
{"Time":"2023-03-10T08:19:24.595743855+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Test":"TestLog","Output":"    test_test.go:6: Hello world!\n"}
{"Time":"2023-03-10T08:19:24.59575475+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Test":"TestLog","Output":"    test_test.go:7: Huh, what's this?\n"}
{"Time":"2023-03-10T08:19:24.595791388+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Test":"TestLog","Output":"--- FAIL: TestLog (0.00s)\n"}
{"Time":"2023-03-10T08:19:24.59580443+01:00","Action":"fail","Package":"k8s.io/kubernetes/test","Test":"TestLog","Elapsed":0}
{"Time":"2023-03-10T08:19:24.595817364+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Output":"FAIL\n"}
{"Time":"2023-03-10T08:19:24.595975533+01:00","Action":"output","Package":"k8s.io/kubernetes/test","Output":"FAIL\tk8s.io/kubernetes/test\t0.003s\n"}
{"Time":"2023-03-10T08:19:24.596021059+01:00","Action":"fail","Package":"k8s.io/kubernetes/test","Elapsed":0.003}
```

**Comment by pohly** [comment]
In JSON, an additional tag instead of a text prefix could be used. But that still means that a new feature in Go is needed.

**Comment by liggitt** [comment]
in your json example, we have this:

> {"Time":"2023-03-10T08:19:24.59580443+01:00","Action":"fail","Package":"k8s.io/kubernetes/test","Test":"TestLog","Elapsed":0}

That indicates in a structured way that the TestLog test specifically failed. Is that not enough for our analysis to treat that as a failure of that test?

**Comment by pohly** [comment]
It is enough to treat the test as failed. But what should we then use as failure message?

Currently it is the entire output of the test. That's too much (costs!) and breaks finding similar failures.

**Comment by pohly** [comment]
What you see in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116354/pull-kubernetes-integration/1633336232408780800 is what we currently use as failure messages.

Compare that against E2E failures, e.g. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-cos-k8sstable3-default/1634073499108642816

**Comment by pohly** [comment]
/remove-lifecycle rotten

I still think that this could be enhanced. I just ran into failure messages again where the actual failure got pruned and/or was hard to find in a sea of log output.

**Comment by pohly** [comment]
/remove-lifecycle rotten

I am working on a `ktesting.TContext` which wraps the underlying testing.T or testing.B. It also works as wrapper around Ginkgo, so integration and E2E tests can use the same helpers, as long as those helpers use `ktesting.TContext`.

One aspect of this `ktesting.TContext` is that `Error[f]` and `Fatal[f]` log output gets a `[FATAL] ERROR` prefix. This then can get picked up by [junitxml](https://github.com/kubernetes/kubernetes/tree/master/third_party/forked/gotestsum/junitxml) similar to the change in [shell2junit](https://github.com/kubernetes/kubernetes/commit/dbbb21469f46758d912fea115f62a795d84c685f).
