### ISSUE TITLE
dynamic resource allocation: kubelet restart after NodePrepareResource and before checkpointing will cause not calling NodeUnprepareResource

### ISSUE THREAD

**Issue by moshe010** [kubernetes/kubernetes#116411]
### What happened?

1. Create Pod with Dynamic Resource
2. kubelet is restarted between NodePrepareResource  grpc all and before we checkpoint
3. Delete Pod with Dynamic Resource

Kubelet will not call NodeUnprepareResource grpc to the DRA plugin

### What did you expect to happen?

kubelet should call NodeUnprepareResource in such case. 

### How can we reproduce it (as minimally and precisely as possible)?

It was pointed out during code review of https://github.com/kubernetes/kubernetes/pull/115912. 

### Kubernetes version

<details>
https://github.com/kubernetes/kubernetes/pull/115912
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# Linux cloud-dev-42 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by klueska** [comment]
What do you think of the following possible solution:
1. Create and checkpoint a `claimInfo()` with minimal information *before* calling `NodePrepareResource()`.
2. Fill the `claimInfo()` with the rest of its info and checkpoint it again *after* `NodePrepareResource()` if it succeeds.
3. Delete and checkpoint the `claimInfo()` *after* `NodePrepareResource()` if it fails.
4. When restoring the checkpoint after kubelet startup, for any empty `claimInfo()` objects, spawn off a goroutine to populate it with a call to `NodePrepareResource()`. Spin on this "forever" until it succeeds.
5. In `NodeUnprepareResources()` error out if we ever encounter an empty `claimInfo()`.

We would need to make sure we have a way to stop calling `NodePrepareResource()` in the gorouting at some point (i.e. if/when the plugin responsible for it deregisters), but I think something like this should work.

**Comment by moshe010** [comment]
in the step 4 you need to get the resource claim so we will have the ResourceHandle.

I think we can also do the claiminfo filling on demand if we will remove cdiDevice from the NodeUnprepareResources.
(I know that cdiDevice is for stateless plugin, but let assume we don't need to support stateless plugins and all of them are stateful) 
now we don't need to pass cdiDevice to NodeUnprepareResources so we don't need to call NodePrepareResources which was awkward.

regarding the pod resources api we can do on demand NodePrepareResources  to get the cdi devices if the claiminfo missing cdi devices.

**Comment by SergeyKanzhelev** [comment]
> /priority important-soon

@klueska is it a regression? Is it something for 1.27?

**Comment by klueska** [comment]
No. Not a regression. I asked @moshe010 to create this issue in addition to the TODO we put in the code. There is a (very unlikely) race condition in the checkpointing code that we should follow up with in a patch release (i.e. non-blocking for 1.27).

**Comment by bart0sh** [comment]
@moshe010 Isn't this issue fixed by https://github.com/kubernetes/kubernetes/pull/120550 ? Please, consider closing the issue if this is the case.

**Comment by moshe010** [comment]
fixed by https://github.com/kubernetes/kubernetes/pull/120550

**Comment by bart0sh** [comment]
@moshe010 ok. Can you elaborate a little bit? Are you still able to repro it?

**Comment by moshe010** [comment]
@bart0sh yes This issue raised by Kevin as part of review in on the checkpoint PR [1]. 

The issue is that first we put that data in the cache (but not checkpoint) and after that we do the NodePrepareResource grpc and at the end with checkpoint the data.

So theoretically if we would have restart when kubelet when that data is in the cache and NodePrepareResource is called but we haven't checkpoint it to the file we would never be able to clean the resource with NodeUnprepareResource  (because it is not in checkpoint and on restart kubelet will read the checkpoint)

looking on the current code it seem that it make this issue even worse.
This due to the batch change. 
So in [1] we did one call of NodePrepareResource  and after that sync to checkpoint
and it the current code we do the sync to checkpoint after we call all the NodePrepareResource so the time is longer now. 

regarding repo I never tried it was a concern that raise by Kevin which make sense we should handle it. 

[1]- https://github.com/kubernetes/kubernetes/pull/115912

**Comment by ndixita** [comment]
/priority backlog

Since DRA is alpha feature, it needn't be marked as important-soon.

**Comment by bart0sh** [comment]
@moshe010 @klueska Can you look if https://github.com/kubernetes/kubernetes/pull/124323 makes the situation better? It doesn't add `ClaimInfo` objects to the cache until `PrepareResources` succeeds.

We can go even further by moving checkponting to all APIs that modify cache (claimInfoCache.add, claimInfoCache.delete etc). WDYT?

**Comment by bart0sh** [comment]
Fixed by https://github.com/kubernetes/kubernetes/pull/124323
/close
