### ISSUE TITLE
how to manage capacity of pv,pvc when storage is nfs ?

### ISSUE THREAD

**Issue by linpanru** [kubernetes/kubernetes#116457]
i use nfs as my k8s cluster storage ,and i want to know how to manage the capacity of pv，pvc

**Comment by HirazawaUi** [comment]
here are some examples available for your reference at https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs

**Comment by linpanru** [comment]
> i use nfs as my k8s cluster storage ,and i want to know how to manage the capacity of pv，pvc

i mean when i apply a capacity is 100000G even more pvc , it always success, but nfs-server don not have enough capcity, so how can i real manage the capacity when i user nfs as k8s storage

> /kind support

what is kind support ?can you talk about it in detail？thanks

**Comment by linpanru** [comment]
> 

but i don not see anything about capacity of pv pvc , I mean sometime i apply a so big pv pvc to nfs server ,and nfs server don not have enough capacity , but finally ,it success ,so how can i really manage capacity of pv pvc on nfs ? thanks

**Comment by linpanru** [comment]
> here are some examples available for your reference at https://github.com/kubernetes/examples/tree/master/staging/volumes/nfs

but i don not see anything about capacity of pv pvc , I mean sometime i apply a so big pv pvc to nfs server ,and nfs server don not have enough capacity , but finally ,it success ,so how can i really manage capacity of pv pvc on nfs ? thanks

**Comment by linpanru** [comment]
> /sig storage
