### ISSUE TITLE
Test case "[sig-cluster-lifecycle] [Feature:BootstrapTokens] [It] should delete the signed bootstrap tokens from clusterInfo ConfigMap when bootstrap token is deleted" valid only where kubeadm used

### ISSUE THREAD

**Issue by sultetveny** [kubernetes/kubernetes#116467]
### What happened?

Executing the following CNTT test failed: _[sig-cluster-lifecycle] [Feature:BootstrapTokens] [It] should delete the signed bootstrap tokens from clusterInfo ConfigMap when bootstrap token is deleted_

```
podman run -it --env-file ~/opnfv/env \
-v ~/opnfv/ca.pem:/home/opnfv/functest/ca.pem:Z \
-v ~/opnfv/config:/root/.kube/config:Z \
-v ~/opnfv/results:/home/opnfv/functest/results:Z \
-v ~/opnfv/repositories.yml:/home/opnfv/functest/repositories.yml:Z \
-v ~/opnfv/cluster-admin.pem:/home/opnfv/functest/cluster-admin.pem:Z \
-v ~/opnfv/cluster-admin-key.pem:/home/opnfv/functest/cluster-admin-key.pem:Z \
opnfv/functest-kubernetes-smoke:v1.23 /bin/bash


# within the container
/usr/local/bin/e2e.test \
--stderrthreshold=0 \
--test.timeout=24h0m0s \
--ginkgo.seed=1669123393 \
--ginkgo.noColor \
--ginkgo.slowSpecThreshold=5.00000 \
-kubeconfig /root/.kube/config \
-provider local \
-report-dir /home/opnfv/functest/results/focus/ \
-ginkgo.focus "should delete the signed bootstrap tokens from clusterInfo ConfigMap when bootstrap token is deleted" \
-non-blocking-taints is_control,is_edge \
-disable-log-dump false
```

From the log:
_Mar 10 12:48:55.386: FAIL: Failed to get cluster-info configMap: configmaps "cluster-info" not found_

Log file attached
[log.txt](https://github.com/kubernetes/kubernetes/files/10942474/log.txt)

As it try to find the 'cluster-info' configMap it seems this TC applicable only on K8S cluster where kubeadm used. Is this intentional?

### What did you expect to happen?

Expected the TC will pass.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:49:13Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.15", GitCommit:"b84cb8ab29366daa1bba65bc67f54de2f6c34848", GitTreeState:"clean", BuildDate:"2022-12-08T10:42:57Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>
Openstack

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux cbis-sut1-control-01 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> As it try to find the 'cluster-info' configMap it seems this TC applicable only on K8S cluster where kubeadm used. Is this intentional?

yes, all the tests under e2e_kubeadm are targeting kubeadm clusters. you are not supposed to run them on anything else.

/kind support

**Comment by neolit123** [comment]
/remove-kind bug

please close if this answers your quetions.

**Comment by neolit123** [comment]
> /usr/local/bin/e2e.test \

this is odd, because if you build the k8s e2e suite it will not include e2e_kubeadm. e2e_kubeadm is built separately.
double check your build process of the e2e suite binary

**Comment by sultetveny** [comment]
@neolit123 I guess I've to ask the OPNFV about it, as the image is built by them: [opnfv/functest-kubernetes-smoke:v1.23](https://hub.docker.com/layers/opnfv/functest-kubernetes-smoke/v1.23/images/sha256-3cdf63c61b95868fc463094123d89dbb001bafe93f2db1502cdfd560ff293867?context=explore).
Also in the list of available/recommended test suite (sig_cluster_lifecycle) not mentioned it's applicable on kubeadm cluster only:
[TCs](https://github.com/opnfv/functest-kubernetes/blob/stable/v1.23/ansible/site.yml)

**Comment by neolit123** [comment]
i think i misunderstood the problem. the sig-cluster-lifecycle tests are valid to be part of the main suite as bootstrap tokens are a k8s wide feature, i.e not only kubeadm uses them.

but if your cluster doesn't have the token usage you must skip the tests. one reason they are not part of k8s conformance and same for other non conformance tests.

in most cases you shouldn't run the whole suite.

**Comment by sultetveny** [comment]
@neolit123 : I see, thank you for the information.
