### ISSUE TITLE
[dual-stack]support service ipFamilies update event in service controller

### ISSUE THREAD

**Issue by BraceCY** [kubernetes/kubernetes#116495]
### What would you like to be added?

Currently, when loadbalancer service's ipFammilies updated，service controller will ignore this event. That means cloud provider can't update ipv4/ipv6 backend.
So, I'm thinking service controller need add watching 'service's ipFammilies updated' event, It'd be important for cloud provider update dual-stack backend.

code at :https://github.com/kubernetes/cloud-provider/blob/fa271f103b481b342ed5eefd9cde68c30bf3b114/controllers/service/controller.go#L526

### Why is this needed?

Our load balancer supports dual-stack. When the services in the cluster are updated from IPv4 to IPv6(same ipv6->ipv4、ipv4->ipv4/ipv6), it is expected that the cloud provider can perceive this event and update the IPv4/IPv6 address to the backend of the load balancer.

/sig cloud-provider
/area cloudprovider

**Comment by aojea** [comment]
yeah, that is right, the logic need to be adapted

/kind bug
/sig network
/sig cloud-provider
