### ISSUE TITLE
[Failing Test] capz-windows-containerd-master

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#116474]
### Which jobs are failing?

master-informing:

- capz-windows-containerd-master

### Which tests are failing?

capz-e2e.[It] Conformance Tests conformance-tests

![Screenshot from 2023-03-10 20-35-25](https://user-images.githubusercontent.com/73882557/224350503-1383d084-aeee-4262-a0c8-2811eceb867b.png)

### Since when has it been failing?

2023-03-10 04:56:51 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-containerd-master

### Reason for failure (if possible)

```
{Timed out after 1500.001s.
Timed out waiting for 2 nodes to be created for MachineDeployment capz-conf-3vp7iv/capz-conf-3vp7iv-md-win
Expected
    <int>: 0
to equal
    <int>: 2 failed [FAILED] Timed out after 1500.001s.
Timed out waiting for 2 nodes to be created for MachineDeployment capz-conf-3vp7iv/capz-conf-3vp7iv-md-win
Expected
    <int>: 0
to equal
    <int>: 2
In [It] at: /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.3.5/framework/machinedeployment_helpers.go:131 @ 03/10/23 05:48:53.698
}
```

### Relevant SIG(s)

/sig testing

**Comment by jsturtevant** [comment]
no major change between passing test on 3/9 17:55 PST and failing test on 3/9 20:56 PST

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1634010079642521600/build-log.txt
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1634055631457488896/build-log.txt

https://github.com/kubernetes/kubernetes/compare/45b96eae989efe...33d9543ceb09a9

**Comment by jsturtevant** [comment]
kubelet logs confirm this:

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-containerd-windows/1634055631457488896/artifacts/clusters/capz-conf-3vp7iv/machines/capz-conf-3vp7iv-md-win-756d798cb6-hhn9w/kubelet.log

```
E0310 05:48:07.311161    3308 pod_workers.go:1256] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"cloud-node-manager\" with ImagePullBackOff: \"Back-off pulling image \\\"capzci.azurecr.io/azure-cloud-node-manager:598fde3\\\"\"" pod="kube-system/cloud-node-manager-windows-rsnrs" podUID=e2fc8b20-9bb3-46c2-bee7-8f3451ea3d84
```

**Comment by jsturtevant** [comment]
looks to be related to bumping capz to 1.8 which uses the cloud-provider oot image:

caused by upgrading to 1.8 capz https://github.com/kubernetes/test-infra/commit/1552ce8ac208770c1076d63641f1b48ee74a547c in combination with using OOT https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3105

**Comment by jsturtevant** [comment]
This looks to be affecting our release jobs as well: 

https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-1.26
https://testgrid.k8s.io/sig-windows-signal#capz-e2e-windows-containerd-1.25

**Comment by jsturtevant** [comment]
looks like the image being built is linux only and is being pulled by windows. When setting up the snapshot in containerd it is failing (as it is missing files required by windows)

**Comment by jsturtevant** [comment]
For the passing test the image is multi-arch manifest, so the windows image pulls properly

**Comment by jsturtevant** [comment]
There is a missing env `TEST_WINDOWS` in the [prowconfig](https://prow.k8s.io/prowjob?prowjob=efa2120c-beff-11ed-9d91-c209e83e3776) see https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/0f497f833a710ad2ad720124f2dd3003da9326e8/scripts/ci-build-azure-ccm.sh#LL64C3-L64C3
