### ISSUE TITLE
kubelet should avoid sending operationExecutor.MountVolume request to CSI driver when there is still pending operationExecutor.UnmountVolume request for the same volume ID

### ISSUE THREAD

**Issue by yanxiucai** [kubernetes/kubernetes#116403]
### What happened?

kubelet sends operationExecutor.MountVolume request to CSI driver even when there is still pending operationExecutor.UnmountVolume request for the same volume ID

### What did you expect to happen?

kubelet only sends operationExecutor.MountVolume request to CSI driver when there is no pending operationExecutor.UnmountVolume request for the same volume ID

### How can we reproduce it (as minimally and precisely as possible)?

Reproduce steps:
1. Install CSI driver on  OpenShift4.12 cluster, for example https://github.com/dell/csi-baremetal
2. Create a StatefulSet with 1 replicas using PVC with CSI StorageClass and set nodeAffinity to specified node.  Check the pod is in Running state and Volume in PUBLISHED state.
3. Power off the node 
4. Mark the node as unschedulable by _kubectl cordon <node_name>_
5. Remove pods in the Terminating state by _kubectl get pods -A -o wide | grep -i <node name> |  awk '{if ($4 == "Terminating") system ("kubectl -n " $1 " delete pods " $2  " --grace-period=0 " " --force ")}'_
7. Drain the node by  _kubectl drain <node name> --force --delete-local-data --ignore-daemonsets_
8. Remove Node From Cluster by _kubectl delete node <node name>_
9. Power on the node, the node will automatically rejoin the OpenShift cluster and be recognized by CSI.
After above steps,  the StatefulSet pod is scheduled to the node again but stuck at ContainerCreating. 

Please refer this for the detail reproduce log
[kubelet_volume_request_issue.txt](https://github.com/kubernetes/kubernetes/files/10929526/kubelet_volume_request_issue.txt)
Also the kubelet log after the node was power on again
[kubelet_log_after_node_powerup_grep_volume.txt](https://github.com/kubernetes/kubernetes/files/10929543/kubelet_log_after_node_powerup_grep_volume.txt)
CSI node service log 
[csi-baremetal-node-6q5ph_log_grep_volume.txt](https://github.com/kubernetes/kubernetes/files/10929552/csi-baremetal-node-6q5ph_log_grep_volume.txt)

### Anything else we need to know?

RCA for this issue:
When we power off the node then drain and remove the node, all the volume mount point on this node will be removed.
After node was brought back, kubetlet synced pod volume automatically and then tried to unmount volume, this action failed because CSI node service pod was not up yet. And it kept retry, but the durationBeforeRetry kept double from 500ms, 1s, 2s, ..., 32s ....
Later when StatefulSet pod came up , kubelet tried to mount the volume for the pod. At that time the CSI node service pod was up to.
CSI node service pod first received the mountvolume request, and start to call  NodePublishVolume function but NodePublishVolume failed due to the global mountpoint was gone, it is not a block device. Then this volume ran into the unexpected state, in ttps://github.com/dell/csi-baremetal we set it as FAILED state. 
After that CSI node service received the unmountvolume request again, but the volume was in FAILED state hence it failed again.
Then kubelet kept retry mountvolume and unmountvolume request but all this return failed as volume was in FAILED state.

Here I think kubelet should wait for unmount success return by CSI drive before sending  mount request to CSI driver for the same volume.  
 

### Kubernetes version

<details>

```console
[root@servicenode ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"b153f088ddd8c1289f7a62e9ff64e26894ca4530", GitTreeState:"clean", BuildDate:"2022-03-01T21:15:46Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4+a34b9e9", GitCommit:"b6d1f054747e9886f61dd85316deac3415e2726f", GitTreeState:"clean", BuildDate:"2023-01-10T15:55:28Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
[root@servicenode ~]# oc version
Client Version: 4.6.56
Server Version: 4.12.4
Kubernetes Version: v1.25.4+a34b9e9



```

</details>

### Cloud provider

<details>
RedHat OpenShift4.12
</details>

### OS version

<details>

```console
# On Linux:
[root@servicenode ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[root@servicenode ~]#
[root@servicenode ~]# uname -a
Linux servicenode 4.18.0-348.el8.x86_64 #1 SMP Tue Oct 19 15:14:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
https://github.com/dell/csi-baremetal
</details>

**Comment by jsafrane** [comment]
Sorry for a very late reply. Looking at kubelet logs (thanks!), I can see that kubelet _correctly_ called `NodeUnpublishVolume` for the volume of the old (deleted) Pod, but the driver refused to unmount and returned an error code. It's driver's failure. It must be idempotent, if the volume is not mounted, it must return success.

The next issue is that kubelet calls `NodePublishVolume` for the volume of the new pod directly, without fixing the global mount by calling `NodeStageVolume` first. This has been fixed as part of https://github.com/kubernetes/enhancements/issues/3756 and it will be beta / on-by-default in Kubernetes 1.28.

At least with the current master (almost Kubernetes 1.28), a CSI driver gets `NodeUnpublishVolume` for the old pod and `NodeStageVolume` and `NodePublishVolume` for the volume + the new Pod. Now it's up to the driver to clean any state it has for the old mount + fix the global mount / staging dir + (bind-?) mount it into the new pod.
