### ISSUE TITLE
NodeSelectorAsSelector needs to be fixed

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#116419]
Spotted by @liggitt 

https://github.com/kubernetes/kubernetes/commit/7093b10416f6073f3e0531b8cc1d71aa5d9ed3d2#r103711882

https://github.com/kubernetes/kubernetes/commit/7093b10416f6073f3e0531b8cc1d71aa5d9ed3d2#r103711822

The function needs to be fixed based on Jordan comments before moving the feature to beta.

This issue is a blocker for graduating the feature.

https://github.com/kubernetes/kubernetes/blob/20e44913853fba580997cacad594e5274613bd2d/pkg/apis/core/v1/helper/helpers.go#L397-L431

/sig network
/kind bug
/assign @sarveshr7

**Comment by liggitt** [comment]
if this can't be fixed quickly (e.g. in time for 1.27), please move the function to the multi-cidr package and unexport it so no one else starts using the buggy helper method in the meantime

**Comment by aojea** [comment]
we should remove it from helper and make it local, it doesn't make sense to export it if is only used there
https://grep.app/search?q=NodeSelectorAsSelector

**Comment by thockin** [comment]
Should we triage-accept this?

**Comment by aojea** [comment]
> Should we triage-accept this?

this is blocked on the go/no-go decision of the previously called ClusterCIDR KEP and now NodeIPAMConfig 

https://github.com/kubernetes/enhancements/pull/4174

please @danwinship @thockin we need to decide if we want to make it or remove it

**Comment by danwinship** [comment]
> this is blocked on the go/no-go decision of the previously called ClusterCIDR KEP and now NodeIPAMConfig

that's no longer in-tree... I'm not sure what happened with the code mentioned here?

**Comment by uablrek** [comment]
> that's no longer in-tree... I'm not sure what happened with the code mentioned here?

Moved to https://github.com/kubernetes-sigs/node-ipam-controller I suppose. Anyway, this is no longer a K8s issue, closing ...

/close
