### ISSUE TITLE
[Failing test] ci-crio-cgroupv1-node-e2e-conformance

### ISSUE THREAD

**Issue by lauralorenz** [kubernetes/kubernetes#116446]
### Which jobs are failing?

ci-crio-cgroupv1-node-e2e-conformance on master-informing

### Which tests are failing?

E2eNode Suite.[It] [sig-node] InitContainers [NodeConformance] should not launch regular containers if an init container fails
E2eNode Suite.[It] [sig-node] InitContainers [NodeConformance] should launch init container serially before a regular container

### Since when has it been failing?

3/8 16:38 PST, k/k commit 7fe0fb7fb
<img width="2534" alt="Screenshot 2023-03-09 at 3 23 58 PM" src="https://user-images.githubusercontent.com/5643703/224183230-89b2543e-3f37-4f85-8250-f972443d0593.png">

### Testgrid link

https://k8s-testgrid.appspot.com/sig-release-master-informing#ci-crio-cgroupv1-node-e2e-conformance

### Reason for failure (if possible)

```
{ failed [FAILED] reading output file: open /tmp/init-container-3483531487/output: no such file or directory
In [It] at: test/e2e_node/init_containers_test.go:266 @ 03/09/23 00:53:58.443
}
```

### Anything else we need to know?

Root cause already identified by SIG-Node ([slack ref](https://kubernetes.slack.com/archives/C0BP8PW9G/p1678332084366879)), fix is TBD in https://github.com/kubernetes/kubernetes/pull/116398.

### Relevant SIG(s)

/sig node

**Comment by mengjiao-liu** [comment]
Duplicate issue: https://github.com/kubernetes/kubernetes/issues/116418

**Comment by saschagrunert** [comment]
Yep, let's track the issue in https://github.com/kubernetes/kubernetes/issues/116418
