### ISSUE TITLE
Add record information on the 'service' of k8s

### ISSUE THREAD

**Issue by opencmit2** [kubernetes/kubernetes#116528]
### What would you like to be added?
In the production environment, the backend pod is accessed through the "service" of the k8s. When the backend pod is accessed through the "service", the logs of the backend pod can also be viewed on the "service". But I don't know which pod log it is. In fact, it's not the 'service''s own log. You should add the record information to the "service" of K8S. For example, only record which access accessed which pod, so that the pod accessed through the 'service' can be quickly located.

I have verified that this is the case. When accessing multiple pods on the backend through the 'service' of the k8s, you can't see which pods are accessed through the 'service' of the k8s. What you see is only the log information of a bunch of pods
### Why is this needed?

I need to know which pod to find the corresponding record from the ’service‘ to facilitate production business troubleshooting

**Comment by aojea** [comment]
/remove-kind feature
/kind support

can you be more specific ?

what  ` On the K8S production link` means?

**Comment by opencmit2** [comment]
> 

In the production environment, access the backend pod through the 'service' of the k8s. ' Service 'can't see any information about which pod to access. If there are many pods, I need to find an access log, which is troublesome. I need to find the pod separately

**Comment by opencmit2** [comment]
> /remove-kind feature /kind support
> 
> can you be more specific ?
> 
> what ` On the K8S production link` means?

means:
  In the production environment, the backend pod is accessed through the "service" of the k8s. When the backend pod is accessed through the "service", the logs of the backend pod can be viewed on the "service". But I don't know which pod log it is. You should add the record information to the "service" of K8S. For example, only record which access accessed which pod, so that the pod accessed through 'service' can be quickly located.

**Comment by thockin** [comment]
The service abstraction doesn't have a log.  For many implementations, there is no user-space component to do the logging, and even if there was, there would be a distinct log per node.

I think I get what you are asking for, but this is, at best, an implementation-specific thing.
