### ISSUE TITLE
Heapster can not connect due to invalid certificate

### ISSUE THREAD

**Issue by AlexeyKupershtokh** [kubernetes/kubernetes#11654]
I'm using the v1.0.1 pre-release.

I've created a single machine cluster (v0.19.3) using the ```KUBERNETES_PROVIDER=ubuntu ./kube-up.sh``` command. It started normally.
Then I tried to start the Heapster on the "cluster":
```
wicked@w:~/docker/kubernetes $ kubectl create -f cluster/addons/cluster-monitoring/influxdb --namespace=kube-system
services/monitoring-grafana
replicationcontrollers/monitoring-heapster-v5
services/monitoring-heapster
replicationcontrollers/monitoring-influx-grafana-v1
services/monitoring-influxdb
```
It has created 5 docker containers running:
```
a8b397bb47d1        gcr.io/google_containers/heapster_grafana:v0.7                                    "/kuisp -p 8080 -c /   9 minutes ago       Up 9 minutes                                                         k8s_grafana.7ff9ddef_monitoring-influx-grafana-v1-xumof_kube-system_efec7e43-2f69-11e5-9ca4-005056010186_d3fc3378           
78ce40555bb7        gcr.io/google_containers/heapster_influxdb:v0.3                                   "/run.sh"              9 minutes ago       Up 9 minutes                                                         k8s_influxdb.787acd0e_monitoring-influx-grafana-v1-xumof_kube-system_efec7e43-2f69-11e5-9ca4-005056010186_03ef2fc5          
5bf518831100        gcr.io/google_containers/heapster:v0.16.0                                         "/heapster --source=   9 minutes ago       Up 9 minutes                                                         k8s_heapster.8972800b_monitoring-heapster-v5-jy7o5_kube-system_efd4cc8c-2f69-11e5-9ca4-005056010186_4f1014d0                
c5d90b64aca7        gcr.io/google_containers/pause:0.8.0                                              "/pause"               9 minutes ago       Up 9 minutes        0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp   k8s_POD.fc880c63_monitoring-influx-grafana-v1-xumof_kube-system_efec7e43-2f69-11e5-9ca4-005056010186_46d51def               
c63dbddfd38d        gcr.io/google_containers/pause:0.8.0                                              "/pause"               9 minutes ago       Up 9 minutes                                                         k8s_POD.e4cc795_monitoring-heapster-v5-jy7o5_kube-system_efd4cc8c-2f69-11e5-9ca4-005056010186_a34b8057                      
```
But the heapster container repeatedly reports an error:
```
E0721 05:48:45.733960       1 reflector.go:136] Failed to list *api.Node: Get https://192.168.0.2:443/api/v1/nodes: x509: failed to load system roots and no roots provided
E0721 05:48:45.954969       1 reflector.go:136] Failed to list *api.Pod: Get https://192.168.0.2:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: failed to load system roots and no roots provided
E0721 05:48:46.385188       1 reflector.go:136] Failed to list *api.Namespace: Get https://192.168.0.2:443/api/v1/namespaces: x509: failed to load system roots and no roots provided
```

**Comment by AlexeyKupershtokh** [comment]
Seems to be a duplicate of https://github.com/GoogleCloudPlatform/heapster/issues/422

**Comment by AlexeyKupershtokh** [comment]
If I install Heapster according to Heapster's documentation it does not work the same way.

**Comment by vishh** [comment]
Have you [setup Service Accounts](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/service-accounts-admin.md) in your kubernetes cluster? If not, can you try running heapster with auth disabled as explained [here](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/source-configuration.md)

**Comment by AlexeyKupershtokh** [comment]
@vishh sounds good from the point of view that it performs a reguar http-connection. I think this will help me, but in general this is more like avoiding to fix issues with the certificate and with documentation.

**Comment by vishh** [comment]
Agreed. Kubernetes security config has changes quite a bit over the last
few months. But it should be more stable moving forward. Better
documentation underway.

**Comment by AlexeyKupershtokh** [comment]
I've played a bit with the container.
Actually it starts with the following messages:
```
wicked@battler-01:~$ docker exec -it 332bc1c82892 /heapster "--source=kubernetes:http://kubernetes-ro?useServiceAccount=true&auth=&insecure=true" "--sink=influxdb:http://monitoring-influxdb:80"
I0723 00:14:46.403805      55 heapster.go:52] /heapster --source=kubernetes:http://kubernetes-ro?useServiceAccount=true&auth=&insecure=true --sink=influxdb:http://monitoring-influxdb:80
I0723 00:14:46.404415      55 heapster.go:53] Heapster version 0.16.0
E0723 00:14:46.405312      55 helper.go:247] expected to load root ca config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I0723 00:14:46.406180      55 kube_factory.go:169] Using Kubernetes client with master "https://192.168.0.2:443" and version "v1"
I0723 00:14:46.416792      55 kube_factory.go:170] Using kubelet port 10255
E0723 00:14:46.416697      55 reflector.go:136] Failed to list *api.Node: Get https://192.168.0.2:443/api/v1/nodes: x509: failed to load system roots and no roots provided
E0723 00:14:46.436944      55 reflector.go:136] Failed to list *api.Pod: Get https://192.168.0.2:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: failed to load system roots and no roots provided
```
I copied a base64_decoded certificate from my ~/.kube/config, but it didn't help a lot because of ips mismatch:
```
I0723 00:30:49.693451       1 heapster.go:52] /heapster --source=kubernetes:http://kubernetes-ro?useServiceAccount=true&auth=&insecure=true --sink=influxdb:http://monitoring-influxdb:80
I0723 00:30:49.693690       1 heapster.go:53] Heapster version 0.16.0
I0723 00:30:49.695987       1 kube_factory.go:169] Using Kubernetes client with master "https://192.168.0.2:443" and version "v1"
I0723 00:30:49.696010       1 kube_factory.go:170] Using kubelet port 10255
E0723 00:30:49.720956       1 reflector.go:136] Failed to list *api.Pod: Get https://192.168.0.2:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: certificate is valid for 192.168.3.49, not 192.168.0.2
E0723 00:30:49.725511       1 reflector.go:136] Failed to list *api.Node: Get https://192.168.0.2:443/api/v1/nodes: x509: certificate is valid for 192.168.3.49, not 192.168.0.2
E0723 00:30:49.744039       1 kube_events.go:96] Failed to load events: Get https://192.168.0.2:443/api/v1/events: x509: certificate is valid for 192.168.3.49, not 192.168.0.2
```

**Comment by AlexeyKupershtokh** [comment]
I've also tried to use a service account.
As far as I understood it should have been sufficient to edit deploy/kube-config/influxdb/heapster-controller.json and add ```"serviceAccount": "heapster"``` into the container's spec. Then I re-created the RC but the ca.crt file didn't come up. Does this approach working on the cluster v0.19.3 ?

**Comment by philk** [comment]
I had a similar problem with kube-dns not being able to connect to the master. Adding `--client-ca-file=/etc/kubernetes/certs/ca.crt` to kube-apiserver then deleting the default-token (`kubectl get secret`) and letting it get recreated fixed the issue for me. Note that I'm on 1.0.1 and YMMV.

**Comment by AlexeyKupershtokh** [comment]
@philk Thank you for a starting point. It seems that I've resolved the issue with the ca.crt.
Details are in comments in another issue:
1) https://github.com/GoogleCloudPlatform/heapster/issues/429#issuecomment-125653775
2) https://github.com/GoogleCloudPlatform/heapster/issues/429#issuecomment-125798911

Now I'm getting another error though:
```
E0729 01:28:14.393329       1 reflector.go:136] Failed to list *api.Node:
the server has asked for the client to provide credentials (get nodes)
E0729 01:28:14.395981       1 reflector.go:136] Failed to list *api.Namespace:
the server has asked for the client to provide credentials (get namespaces)
E0729 01:28:14.397820       1 reflector.go:136] Failed to list *api.Pod:
the server has asked for the client to provide credentials (get pods)
```

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
