### ISSUE TITLE
systemd: loop variables captured by 'func' literals in 'go' statements

### ISSUE THREAD

**Issue by yanke-xu** [kubernetes/kubernetes#116505]
### What happened?

```
for _, tc := range tests {
    t.Run(tc.desc, func(t *testing.T) {
        ......
	go func() {
	    select {
            case res := <-outChan:
	         assert.Equal(t, tc.shutdownActive, res)
		 done <- true
	    case <-time.After(5 * time.Second):
		 t.Errorf("Timed out waiting for shutdown message")
		 done <- true
	    }
	}()
        ......
    })
}

```

**tc.shutdownActive** is captured by 'func' literals in 'go' statements(Line177), it may cause a data race. 
I use t.Run(..., tc.tc.shutdownActive){...}() or t.Run() {...}(tc) to avoid it .
I don't know whether it is accurate, so I 'm looking forward to your reply.

### What did you expect to happen?

Data Race

### How can we reproduce it (as minimally and precisely as possible)?

Nil

### Kubernetes version

<details>
Nil
</details>

### Cloud provider

<details>
Nil
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by UtopiaGitHub** [comment]
Target file: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/nodeshutdown/systemd/inhibit_linux_test.go

**Comment by SergeyKanzhelev** [comment]
@UtopiaGitHub have you observed any test failures or this is found by code analysis?

**Comment by UtopiaGitHub** [comment]
@SergeyKanzhelev Yes, it is  found by code analysis.

**Comment by UtopiaGitHub** [comment]
Based on the current code, its use seems to be incorrect and a case of data races.

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind failing-test

since it is not a product bug, but the test issue

**Comment by mmiranda96** [comment]
Although each test case calls a goroutine, tests run serially and block on the goroutine return, so it doesn't look like it could cause an issue. However, to be safe we can create a local copy of `tc` inside the loop. I'll send a PR briefly.

**Comment by mmiranda96** [comment]
Created #116994 to address this.
