### ISSUE TITLE
kmsv2: flaky `TestEncryptError`

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#116538]
### Which jobs are flaking?

`pull-kubernetes-unit`

### Which tests are flaking?

`k8s.io/kubernetes/vendor/k8s.io/kms/pkg/hierarchy: TestEncryptError`

### Since when has it been flaking?

March 9th

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestEncryptError&job=pull-kubernetes-unit

### Reason for failure (if possible)

```
{Failed  === RUN   TestEncryptError
    hierarchy_test.go:364: Encrypt() error = <nil>, want non-nil
--- FAIL: TestEncryptError (0.00s)
}
```

### Relevant SIG(s)

/sig auth

**Comment by enj** [comment]
All of this code was deleted in #116630

cc @aramase 

/close
