### ISSUE TITLE
Access file /sys/fs/cgroup/systemd/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod<poid>.slice/crio-<containerid>/cgroup.procs from kubernetes commands or API

### ISSUE THREAD

**Issue by coolninja1504** [kubernetes/kubernetes#116534]
Hi All,
The file /sys/fs/cgroup/systemd/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod<pod_id>.slice/crio-<container_id>/cgroup.procs on the worker lists the  pids of process running inside the container at init time.
I want to access this file without going onto the worker node .
Is there any kubernetes command or api with which I can read the contents of this file, .
Thanks ,
Ashish

**Comment by sftim** [comment]
Thanks for the query
/kind support

**Comment by pacoxu** [comment]
This can be got from `metrics/cadvisor`.

```
 kubectl get --raw "/api/v1/nodes/daocloud/proxy/metrics/cadvisor" | grep -i process
# HELP container_processes Number of processes running inside the container.
# TYPE container_processes gauge
container_processes{container="",id="/",image="",name="",namespace="",pod=""} 180 1694072567500
container_processes{container="",id="/k8s.io/20ea6bf7e68b7f5eccda9ec6be7643d177efd69b6332d29bb1dbddc7907b0f06",image="registry.k8s.io/e2e-test-images/volume/nfs:1.3",name="20ea6bf7e68b7f5eccda9ec6be7643d177efd69b6332d29bb1dbddc7907b0f06",namespace="",pod=""} 5 1694072565809
```

https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2371-cri-pod-container-stats#current-fulfiller-of-metrics-endpoints--future-proposal

With CRI :

https://github.com/kubernetes/kubernetes/blob/4f303d123659fb3aac2108f8439c7f43dde438b5/pkg/kubelet/stats/cri_stats_provider_linux.go#L92-L99

/sig node instrumentation

**Comment by dgrisonnet** [comment]
Closing since the information can already be found in metrics.

Feel free to reopen if that doesn't answer your request.

/close
