### ISSUE TITLE
kubelet cannot provide pod monitoring data for a namespace

### ISSUE THREAD

**Issue by JokerDevops** [kubernetes/kubernetes#116541]
### What happened?

I use three namespaces test1 test2 test3. The deployment resource objects are created in each of the three namespaces. The kubelet node can provide monitoring data of the test1 and test2 namespaces, but cannot provide cpu monitoring data of pod in the test3 namespace

### What did you expect to happen?

You can provide monitoring data such as cpu in all namespaces

### How can we reproduce it (as minimally and precisely as possible)?

kubectl apply -f test1.yaml
kubectl apply -f test2.yaml
kubectl apply -f test3.yaml

### Kubernetes version

<details>

```console
$ kubectl version
 1.23
```

</details>

### Cloud provider

<details>
kube-controller-manager
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
> `kubectl apply -f test1.yaml`
> `kubectl apply -f test2.yaml`
> `kubectl apply -f test3.yaml`

I get an error: 
> ```
> error: the path "test1.yaml" does not exist
> ```

Where can we find these manifests? Also, what error do you see having run the 3 commands?

/triage needs-information

**Comment by JokerDevops** [comment]
@sftim  I can't get metrics data for pods in the buildkit namespace through the /metrics/cadvisor interface of the kubelet.

**Comment by JokerDevops** [comment]
It may be related to the kubelet cAdvisor service.

**Comment by pacoxu** [comment]
I tried the pods yaml. The buildkit cannot run on my cri-o node. 
> time="2023-09-07T15:56:42+08:00" level=warning msg="skipping device /dev/char/10:200 for systemd: stat /sys/dev/char/10:200: no such file or directory"

I wondered if that three pods are in running state or not. If all pods are running, this sounds like a cadvisor problem. 

- Alter way: After v1.26, https://github.com/kubernetes/enhancements/issues/2371 provides another way to get container status from CRI instead of cadvisor. Would you try to upgrade and enable the FG?
