### ISSUE TITLE
Convert net.IP to netip.Addr

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#116532]
### What would you like to be added?

Do we have a plan to convert `net.IP` to `netip.Addr` in our code base ?

/sig-network
/kind feature

### Why is this needed?

`netip.addr` means less overhead, more efficient...

**Comment by aojea** [comment]
duplicate of https://github.com/kubernetes/kubernetes/issues/106161

**Comment by cyclinder** [comment]
> duplicate of #106161

oh.. I forgot this

/close
