### ISSUE TITLE
Kubelet doc.go

### ISSUE THREAD

**Issue by AnanyaKumar** [kubernetes/kubernetes#11663]
I think we should write doc.go files for packages in Kubelet, like we do for the rest of Kubernetes. In some cases, it's not obvious what the code in a package does (for example, without spending some time reading the code, it's not clear what kind of "container" files are in kubelet/container - some "container" source files are outside the folder). In some cases, I think the doc.go files need to be expanded upon (kubelet/types/types.go says "Common types in the Kubelet.", but there's also a kubelet/types.go file).

I think having clear doc files will help structure the code better - contributors will know how they should organize their code when introducing a feature.

**Comment by mbforbes** [comment]
We'd love this! Any chance you would be willing to send a PR or two? :-)

**Comment by resouer** [comment]
I assume this to be very helpful and easy to fix, but seems not progress? 

I'd like to help if needed. @mbforbes @AnanyaKumar
