### ISSUE TITLE
Refactoring Kubelet Source Tree

### ISSUE THREAD

**Issue by AnanyaKumar** [kubernetes/kubernetes#11662]
I started working on the Kubelet recently, and I think we need to refactor the way the files and directories are organized. For example, there are a bunch of utilities functions scattered around in various files in the main kubelet package, which can be better aggregated into relevant packages. Besides being messy and confusing, having utilities lying around in the main kubelet package also seems prone to cyclic dependencies (kubelet.go uses kubelet/subpackageA, but kubelet/subpackageA/pods.go might want to use kubelet/types.go). There are many other issues, for example there's a kubelet/util.go and kubelet/util/format.go, both of which mostly contain functions that extract information from pods.

Refactoring all the files in one pass is very tedious, but I think it's useful to lay out a directory structure we're aiming for. As we add features to the Kubelet, we can extract functions with a desired directory structure in mind. For example, in my current project, I’m adding functions which extract information from a pod, so I’m trying to aggregate “pod information” functions into a package.

Here’s a proposed structure:

container
- generic
- docker
- rkt

pod
- podinfo
- podworkers

managers
- disk
- image
- pod
- container
- volume
- status

statistics
- cadvisor
- prometheus

setup
- envvars
- config

types

mirrorclient

network

oom

healthcheck
- prober.go

run
- runonce.go
- runtime_hooks.go

server

lifecycle

leaky

I believe this handles most files except kubelet/util.go and kubelet/util/format.go. There are 5 functions between these 2 files:

util.go:
canRunPod (move to pod/podinfo)
allowHostNetwork (move to pod/podinfo)
CapacityFromMachineInfo (I'm not sure where to put this)

util/format.go has 2 functions that format pod information, and can go to either pod/format.go, or a new package format in kubelet (if we think we might want to format other objects in the future).

I think the proposed structure better organizes the Kubelet code by functionality. Also, since most code is in it's own package (as opposed to having a giant kubelet package with lots of files), cyclic dependencies won't pose a problem, and it's easier to identify the file a function is defined in. Any thoughts?

**Comment by AnanyaKumar** [comment]
@vmarmol

**Comment by vmarmol** [comment]
@dchen1107 @yujuhong 

Split looks pretty good, thanks for coming up with the proposal @AnanyaKumar!

**Comment by vmarmol** [comment]
@yifan-gu

**Comment by yujuhong** [comment]
There has been a lot of backlog of PRs since the code freeze. IMO, we should postpone on refactoring like this until we get those PRs in to avoid major rebases :-)


> run
> 
> runonce.go
> runtime_hooks.go

I am not sure if there is enough similarity to put runonce.go and runtime_hooks.go into one package.


> util/format.go has 2 functions that format pod information, and can go to either pod/format.go, or a new package format in kubelet (if we think we might want to format other objects in the future).

I vote for keeping util/format.go in a separate package that does not depends on any kubelet packages. The intent of this file is to unite the logging format for most (if not all) kubelet code, and this is the only way to avoid cyclic dependencies.

> mirrorclient

mirror client needs to go with the pod_manager.go since pod_manager is the only consumer of this file.

 

> cadvisor

I am not sure whether we should lump cadvisor with prometheus just because kubelet relies on cadvisor for more than stats, but I don't object.

**Comment by gmarek** [comment]
cc @bgrant0607 as he was proposing code restructure some time ago.

**Comment by timstclair** [comment]
Old issue, but @pmorie made some recent progress on this. https://github.com/kubernetes/kubernetes/pull/25028

**Comment by techtonik** [comment]
What is the progress on there? Is it still actual or maybe should be reticketed?
