### ISSUE TITLE
If k8s support update resource on the fly

### ISSUE THREAD

**Issue by linhil** [kubernetes/kubernetes#116636]
### What would you like to be added?

Features of in-place update resource in K8s.

### Why is this needed?

Adjust the pod resource on the fly is essential for lots of applications

Does K8s support in-place autoscaling, which means update cpu resource on the fly. I want to change the cpu utilization of a pod without any termination(restarting or evcting).

I have look for this anwser for a long time. I see that the [enhancement](https://github.com/kubernetes/kubernetes/pull/102884) in K8s mentioning it is achieved in K8s, but when I asked this issue in slack of sig-autoscaling, they told me it is not achieved now as in the [PR](https://github.com/kubernetes/enhancements/issues/1287), and it waits for other components(like kubelet or CRI) to supports auto-scaling on the fly.

Now I can’t tell whether K8s supports in-place autoscaling or not. Who can tell me the exact answer？
Thanks a lot!

**Comment by sftim** [comment]
/kind support

https://github.com/kubernetes/enhancements/issues/1287 captures the state of that enhancement.

You can also view details in https://www.k8s.dev/resources/keps/

**Comment by sftim** [comment]
>  they told me it is not achieved now

This was a true statement

**Comment by linhil** [comment]
> 

Can kubernetes/enhancements # 1287 work normally? If this can run normally, I think it has implemented in-place update. My understanding is that the function can be implemented now, but it has not been merged into a K8s version that can be released. Am I right?

If not, what is the reason why in-place update cannot be performed at present.

Thank you!

**Comment by linhil** [comment]
> > they told me it is not achieved now
> 
> This was a true statement

Can kubernetes/enhancements # 1287 work normally? If this can run normally, I think this KEP has implemented in-place updates. My understanding is that the function can be implemented now, but it has not been merged into a K8s version that can be released. Am I right?

If not, what is the reason why in-place update cannot be performed at present？

Thanks！

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

If you're looking for more help, check [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

/close
