### ISSUE TITLE
Pod pending in PodInitializing state after Init container OOMKilled

### ISSUE THREAD

**Issue by EladProject** [kubernetes/kubernetes#116676]
### What happened?

We recently upgraded to 1.23 (from 1.22) and started to experience sporadic issues of stuck pods.
This seems to happen when one of the Init containers of a pod exits with Reason OOMKilled (and Exit State: 0)
We have restartPolicy set to 'Never'

### What did you expect to happen?

Pod will be evicted

### How can we reproduce it (as minimally and precisely as possible)?

As said. The issue is sporadic and happens when there is a high memory load on the node (but not always).

### Anything else we need to know?

Here is a sanitized pod description of a stuck pod:
`Name:         wf-3365-1282933487
Namespace:    default
Priority:     0
Node:         gke--producti-m128-c16-sa-work-e7608549-fq5h/10.132.0.139
Start Time:   Tue, 14 Mar 2023 23:42:54 +0200
Labels:       workflows.argoproj.io/completed=false
  workflows.argoproj.io/workflow=wf-3365
Annotations:  kubectl.kubernetes.io/default-container: main
                kubernetes.io/limit-ranger:
                  LimitRanger plugin set: cpu request for container wait; cpu request for container main; cpu request for init container init; cpu request f...
                workflows.argoproj.io/node-id: wf-3365-1282933487
                workflows.argoproj.io/node-name: wf-3365(0)[0].wf-step0(0)
Status:       Pending
IP:           10.4.29.112
IPs:
  IP:           10.4.29.112
Controlled By:  Workflow/wf-3365
Init Containers:
  init:
    Container ID:  containerd://c9877...
    Image:         quay.io/argoproj/argoexec:v3.4.4
    Image ID:      quay.io/argoproj/argoexec@sha256:...
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      init
      --loglevel
      info
      --log-format
      text
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 14 Mar 2023 23:42:55 +0200
      Finished:     Tue, 14 Mar 2023 23:42:55 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment:
      ARGO_POD_NAME:                      wf-3365-1282933487 (v1:metadata.name)
      ARGO_POD_UID:                        (v1:metadata.uid)
      GODEBUG:                            x509ignoreCN=0
      ARGO_WORKFLOW_NAME:                 wf-3365
      ARGO_CONTAINER_NAME:                init
      ARGO_TEMPLATE:                      ...
      ARGO_NODE_ID:                       wf-3365-1282933487
      ARGO_INCLUDE_SCRIPT_OUTPUT:         false
      ARGO_DEADLINE:                      2023-03-16T21:42:53Z
      ARGO_PROGRESS_FILE:                 /var/run/argo/progress
      ARGO_PROGRESS_PATCH_TICK_DURATION:  1m0s
      ARGO_PROGRESS_FILE_TICK_DURATION:   3s
    Mounts:
      ...
  preparedata:
    Container ID:  containerd://9f26...
    Image:         google/cloud-sdk:latest
    Image ID:      docker.io/google/cloud-sdk@...
    Port:          <none>
    Host Port:     <none>
    Command:
      bash
      -c
    Args:
      ... A bunch of shell commands
    
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    0
      Started:      Tue, 14 Mar 2023 23:42:59 +0200
      Finished:     Tue, 14 Mar 2023 23:43:58 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment:
      ARGO_CONTAINER_NAME:                preparedata
      ARGO_TEMPLATE:                      ...
      ARGO_NODE_ID:                       wf-3365-1282933487
      ARGO_INCLUDE_SCRIPT_OUTPUT:         false
      ARGO_DEADLINE:                      2023-03-16T21:42:53Z
      ARGO_PROGRESS_FILE:                 /var/run/argo/progress
      ARGO_PROGRESS_PATCH_TICK_DURATION:  1m0s
      ARGO_PROGRESS_FILE_TICK_DURATION:   3s
    Mounts:
      ...
Containers:
  wait:
    Container ID:
    Image:         quay.io/argoproj/argoexec:v3.4.4
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      argoexec
      wait
      --loglevel
      info
      --log-format
      text
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:  100m
    Environment:
      ARGO_POD_NAME:                      wf-3365-1282933487 (v1:metadata.name)
      ARGO_POD_UID:                        (v1:metadata.uid)
      GODEBUG:                            x509ignoreCN=0
      ARGO_WORKFLOW_NAME:                 wf-3365
      ARGO_CONTAINER_NAME:                wait
      ARGO_TEMPLATE:                      ...
      ARGO_NODE_ID:                       wf-3365-1282933487
      ARGO_INCLUDE_SCRIPT_OUTPUT:         false
      ARGO_DEADLINE:                      2023-03-16T21:42:53Z
      ARGO_PROGRESS_FILE:                 /var/run/argo/progress
      ARGO_PROGRESS_PATCH_TICK_DURATION:  1m0s
      ARGO_PROGRESS_FILE_TICK_DURATION:   3s
    Mounts:
      ...
  main:
    Container ID:
    Image:         eu.gcr.io/...
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /var/run/argo/argoexec
      emissary
      --loglevel
      info
      --log-format
      text
      --
      sh
      -c
    Args:
      ...
    
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     100m
      memory:  020Gi
    Environment Variables from:
      cr-configmap  ConfigMap  Optional: false
    Environment:
      CLIENT_ID:                          ...
      CLIENT_SECRET:                      ...
      CLIENT:                             Machine
      TENANT:                             Production
      SERVER_URL:                         ...
      SERVICE_ACCOUNT:                    ...
      GCS_AUTH_FILE:                      ...
      CREATED_BY_WORKFLOW:                wf-3365
      GOOGLE_APPLICATION_CREDENTIALS:     ...
      DATA_ACCESS:                        test
      POD_NAME:                           wf-3365-1282933487
      CURRENT_RETRY:                      0
      ARGO_CONTAINER_NAME:                main
      ARGO_TEMPLATE:                      ...
      ARGO_NODE_ID:                       wf-3365-1282933487
      ARGO_INCLUDE_SCRIPT_OUTPUT:         false
      ARGO_DEADLINE:                      2023-03-16T21:42:53Z
      ARGO_PROGRESS_FILE:                 /var/run/argo/progress
      ARGO_PROGRESS_PATCH_TICK_DURATION:  1m0s
      ARGO_PROGRESS_FILE_TICK_DURATION:   3s
    Mounts:
      ...
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  var-run-argo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  tmp-dir-argo:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  el-vol:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  storage-credentials:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  storage-secrets
    Optional:    false
  storage-secrets:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  storage-secrets
    Optional:    false
  kube-api-access-pdhls:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              nodetype=WORKFLOW
Tolerations:                 WORKFLOW=BASIC:NoSchedule
  node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
  node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
`

I see a lot of these messages in the log:
`
No ready sandbox for pod can be found. Need to start a new one" pod="default/wf-3365-1282933487
`

### Kubernetes version

1.23.14-gke.1800

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by charles-chenzz** [comment]
so you mean when there is a high memory load on the node(at the same time init containers failed to init), and kubelet didn't evited the pod and the pod stuck at Initializing ?

/sig node

**Comment by charles-chenzz** [comment]
> 

I wander if there's any chance that it's caused by the restartPolicy? since if container failed to init, kubelet should restart it at the same time the node get high memory load, it get collided. and restartPolicy=Never make it can't restart so the pod can't be evited and container inside the pod can't created

**Comment by saschagrunert** [comment]
So the state of the init container is `Terminated (Reason: OOMKilled)` and of the standard container is `Waiting (Reason: PodInitializing)` which seems sane to me. The overall status os the pod is also `Init:OOMKilled`, which seems to be correct. As @charles-chenzz mentioned since the restart policy is set to never we will not evict the pod. Is there anything I'm missing here?

**Comment by EladProject** [comment]
Isn't the overall status of the pod (from the pod description I pasted): "Pending"?
Why is the Exit Code of the preparedata Init container 0? I believe this is the source of the issue.
Most of the time, the Exit Code of an OOMKilled init container is 137, in which the pod is terminated. But sometimes, as in this case, it is not.
I think (and I'm not a kubernetes expert) that this edge case is where the container is terminated for OOM after the main task is finished (successfully), possibly the container is killed because of memory pressure on the node (due to no fault of the container itself).
But nevertheless, the pod is pending indefinitely, which is problematic for us since Argo won't restart it.

**Comment by saschagrunert** [comment]
@EladProject I'm using CRI-O 1.26.2 and Kubernetes fe91bc257b5 and the status is `Failed` with the following manifest:

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  restartPolicy: Never
  initContainers:
    - name: init
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command: ["sh", "-c", "sleep 3 && dd if=/dev/zero of=/dev/null bs=20M"]
      resources:
        requests:
          memory: 15Mi
        limits:
          memory: 15Mi
  containers:
    - name: ctr
      image: registry.k8s.io/e2e-test-images/busybox:1.29-4
      command: ["sh", "-c", "echo done"]
      resources:
        requests:
          memory: 15Mi
        limits:
          memory: 15Mi
```

Depending on the runtime and Kubernetes version combination it may lead to a different result.

**Comment by EladProject** [comment]
As I mentioned, the scenario I encountered is sporadic. The majority of the time when one of the Init containers is stopped with OOMKilled, its Exit Code is 137 and everything is fine (the container is marked as failed).
I can try to upgrade to 1.26, but I didn't see anything in the release note that seems to be related to this.
There was a change in 1.23 (the version from which we started to see this issue more frequently) that may be related to this: https://github.com/kubernetes/kubernetes/pull/104650

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

since we need more clear steps to repro and do it on 1.26

**Comment by bobbypage** [comment]
I also was unable to repro this on v1.26.3 with containerd 1.6.18.

**Comment by ruiwen-zhao** [comment]
So the bug here is that, when an init container gets OOM killed but the init process exits with 0, the state of the init container is correctly set as `Terminated`, but the pod status is incorrectly set as `Pending`.

What should happen is that the pod status is set to `Failed`, so that pod GC can do its work to cleanup failed pods.

**Comment by yonirab** [comment]
@ruiwen-zhao Any further news on this?

**Comment by ruiwen-zhao** [comment]
> @ruiwen-zhao Any further news on this?

Created a PR https://github.com/kubernetes/kubernetes/pull/117712 to fix this issue.

**Comment by ruiwen-zhao** [comment]
Actually, I can only repro this issue on 1.26 (with containerd 1.6.18 and 1.7.0), but cannot repro it on 1.27.1 (with containerd 1.7.0 and 1.6.9.)

On 1.27.1, the exit code of the init container is set correctly to 137

```
Status:       Failed
...
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    137

```
, whereas on 1.26, the exit code is incorrectly set to 0:

```
Status:       Pending
...
Init Containers:
...
    State:          Terminated
      Reason:       OOMKilled
      Exit Code:    0
```

So @yonirab and @EladProject - can you try 1.27 and see if you still have the same issue?

**Comment by AnishShah** [comment]
sig-node CI Meeting:

This issue doesn't occur in 1.27.

/close

**Comment by LastNight1997** [comment]
@ruiwen-zhao I can still repro this issue on k8s 1.28 with containerd 1.6.9 or containerd 1.6.28 , runc 1.1.12 or runc 1.0.3. So I think k8s haven't fix this issue , and for your test (cannot repro it on 1.27.1 (with containerd 1.7.0 and 1.6.9.)), I suspect it may related to the ociRuntime you used. Did you use others runtime like kata?
