### ISSUE TITLE
ImageLocality scored is inaccurate during 4 minutes after scheduler startup

### ISSUE THREAD

**Issue by wu0407** [kubernetes/kubernetes#116673]
### What happened?

The 8 of 10 nodes has same image that size is 4.09GB，but the score of ImageLocality is inconsistent during 4 minutes after 
scheduler startup. After 4 minutes, their scores are consistent.

the pod `bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq` and `ham-35878-202303152300-1-tklj4` use same image and only one container in pod.

```
node             has image
10.10.33.53   true
10.10.33.54   true
10.10.33.55   true
10.10.33.56   true
10.10.33.57   true
10.10.33.58   true
10.10.33.59   true
10.10.33.60   true
10.10.33.61   false
10.10.33.62  false
```

```
Log file created at: 2023/03/15 22:58:50
I0315 23:00:05.312827  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.57" score=100
I0315 23:00:05.312832  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.58" score=22
I0315 23:00:05.312837  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.61" score=0
I0315 23:00:05.312843  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.62" score=0
I0315 23:00:05.312848  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.56" score=47
I0315 23:00:05.312854  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.60" score=97
I0315 23:00:05.312859  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.54" score=100
I0315 23:00:05.312864  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.59" score=100
I0315 23:00:05.312869  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.53" score=100
I0315 23:00:05.312874  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-25146-2023031522-1-tzvwq" plugin="ImageLocality" node="10.10.33.55" score=100

```

after 4minite
```
I0315 23:02:14.037872  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.58" score=100
I0315 23:02:14.037877  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.56" score=100
I0315 23:02:14.037882  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.57" score=100
I0315 23:02:14.037887  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.61" score=0
I0315 23:02:14.037892  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.62" score=0
I0315 23:02:14.037897  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.60" score=100
I0315 23:02:14.037902  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.54" score=100
I0315 23:02:14.037907  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.59" score=100
I0315 23:02:14.037914  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.53" score=100
I0315 23:02:14.037919  241226 generic_scheduler.go:434] "Plugin scored node for pod" pod="bigdata-hanoi-default/ham-35878-202303152300-1-tklj4" plugin="ImageLocality" node="10.10.33.55" score=100
```

### What did you expect to happen?

ImageLocality score is alaway consistent

### How can we reproduce it (as minimally and precisely as possible)?

1. pull 4G image in some nodes
2. wait all node status containt that image
3. restart schedure and create pod that use 4G image
4. check the  scheduler log

### Anything else we need to know?

maybe reason is  get node info from snapshot https://github.com/kubernetes/kubernetes/blob/500bcf6c2b6f541afac3fbec1e05f5c315660fd6/pkg/scheduler/framework/plugins/imagelocality/image_locality.go#L55-L66

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:57:43Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by olderTaoist** [comment]
can you show me your kube-scheduler config?

**Comment by wu0407** [comment]
```
use default config

# ps aux |grep kube-scheduler
root       20281  0.0  0.0 112720  2348 pts/0    S+   18:58   0:00 grep --color=auto kube-scheduler
root      241226  0.3  1.0 755832 83952 ?        Ssl  Mar15   4:22 /usr/local/bin/kube-scheduler --kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig --authentication-kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig --authorization-kubeconfig=/etc/kubernetes/kube-scheduler.kubeconfig --leader-elect=true --v=10 --log-dir=/data/log/kubernetes/ --logtostderr=false
```

**Comment by sftim** [comment]
I'm not sure if this is a bug, or whether @wu0407 you're requesting an improvement we've not previously considered making.

AIUI, image locality is a hint to scheduling rather than a conformance failure / test failure if we don't heed it.

**Comment by olderTaoist** [comment]
i reproduce it in my environment(image exist in kubernetes1.23.8-worker、kubernetes1.23.8-worker2 )：

when the begin starting of kube-scheduler：
`I0323 19:08:50.769445   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker3" score=99
I0323 19:08:50.769459   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker" score=99
I0323 19:08:50.769466   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker2" score=99
I0323 19:08:50.769473   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="ImageLocality" node="kubernetes1.23.8-worker3" score=0
I0323 19:08:50.769480   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="ImageLocality" node="kubernetes1.23.8-worker" score=3
I0323 19:08:50.769487   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-0" plugin="ImageLocality" node="kubernetes1.23.8-worker2" score=0`

after 4 minite：
`I0323 19:12:35.585837   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker2" score=99
I0323 19:12:35.585851   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker" score=99
I0323 19:12:35.585872   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="NodeResourcesBalancedAllocation" node="kubernetes1.23.8-worker3" score=99
I0323 19:12:35.585884   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="ImageLocality" node="kubernetes1.23.8-worker2" score=3
I0323 19:12:35.585894   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="ImageLocality" node="kubernetes1.23.8-worker" score=3
I0323 19:12:35.585905   71598 generic_scheduler.go:434] "Plugin scored node for pod" pod="default/web-1-0" plugin="ImageLocality" node="kubernetes1.23.8-worker3" score=0`

/assign
