### ISSUE TITLE
ServiceAccount not getting deleted as a child resource

### ISSUE THREAD

**Issue by edwardzjl** [kubernetes/kubernetes#116632]
### What happened?

When I create ServiceAccount as a child resource of other resources, and delete the parent resource, the ServiceAccount did not get deleted.

To illustrate I made a small demo based on [this official blog](https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/#owner-references):

A parent ConfigMap:

```console
$ cat <<EOF | kubectl create -f -
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: mymap-parent
> EOF
configmap/mymap-parent created
```
Get the uid of the parent ConfigMap:

```console
$ CM_UID=$(kubectl get configmap mymap-parent -o jsonpath="{.metadata.uid}")
```

A child ConfigMap:

```console
$ cat <<EOF | kubectl create -f -
> apiVersion: v1
> kind: ConfigMap
> metadata:
>   name: mymap-child
>   ownerReferences:
>   - apiVersion: v1
>     kind: ConfigMap
>     name: mymap-parent
>     uid: $CM_UID
> EOF
configmap/mymap-child created
```

A child ServiceAccount:

```console
$ cat <<EOF | kubectl create -f -
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: mysa-child
>   ownerReferences:
>   - apiVersion: v1
>     kind: ConfigMap
>     name: mymap-parent
>     uid: $CM_UID
> EOF
serviceaccount/mysa-child created
```

List the ConfigMaps:

```console
$ kubectl get cm
NAME                                DATA   AGE
mymap-child                         0      3m16s
mymap-parent                        0      3m25s
```

List the ServiceAccounts:

```console
$ kubectl get sa
NAME         SECRETS   AGE
default      0         25d
mysa-child   0         4m41s
```

Delete the parent ConfigMap:

```console
$ kubectl delete cm mymap-parent
configmap "mymap-parent" deleted
```

The child ConfigMap got correctly deleted:

```console
$ kubectl get cm
NAME                                DATA   AGE
```

But the child ServiceAccount was not:

```console
$ kubectl get sa
NAME         SECRETS   AGE
default      0         25d
mysa-child   0         4m41s
```

### What did you expect to happen?

The ServiceAccount get deleted with the parent resource.

### How can we reproduce it (as minimally and precisely as possible)?

```sh
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: mymap-parent
EOF
CM_UID=$(kubectl get configmap mymap-parent -o jsonpath="{.metadata.uid}")

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: mymap-child
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: mymap-parent
    uid: $CM_UID
EOF

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysa-child
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: mymap-parent
    uid: $CM_UID
EOF
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None, it's a self host kubernetes
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux gpt-ms1 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
$ containerd --version
containerd github.com/containerd/containerd v1.6.10 770bd0108c32f3fb5c73ae1264f7e503fe7b2661
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by hysyeah** [comment]
@edwardzjl Which version of k8s do you use

**Comment by hysyeah** [comment]
\assign

**Comment by hysyeah** [comment]
`kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}`

this issue may fixed in newer k8s version

**Comment by edwardzjl** [comment]
> `kubectl version WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short. Use --output=yaml|json to get the full version. Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"} Kustomize Version: v4.5.7 Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}`
> 
> this issue may be fixed in newer k8s version

The kubectl version warning is not a problem, I just followed the issue template to paste this information.

The issue is about resource deletion, especially ServiceAccount as a child resource, not getting deleted.

**Comment by hysyeah** [comment]
I tried with the above steps, and found ServiceAccount is deleted when i delete cm mymap-parent

**Comment by edwardzjl** [comment]
> I tried with the above steps, and found ServiceAccount is deleted when i delete cm mymap-parent

That's weird, I have 2 k8s clusters and they both have the same behaviour: not deleting child ServiceAccount.

Do you have any idea where I should look into?

**Comment by hysyeah** [comment]
you  can try with `k delete cm mymap-parent --v=9` to see whether　Deletion policy is Backgroud ,then you  also can k8s events.

` Request Body: {"propagationPolicy":"Background"}`

**Comment by edwardzjl** [comment]
Thanks for the suggestion, here's the output: (I masked the apiserver host and port)

```console
$ kubectl delete cm mymap-parent --v=9
I0317 13:47:40.182034   40290 loader.go:374] Config loaded from file:  ~/.kube/config
I0317 13:47:40.191538   40290 request.go:1154] Request Body: {"propagationPolicy":"Background"}
I0317 13:47:40.191655   40290 round_trippers.go:466] curl -v -XDELETE  -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.25.4 (linux/amd64) kubernetes/872a965" 'https://api-server:port/api/v1/namespaces/default/configmaps/mymap-parent'
I0317 13:47:40.201964   40290 round_trippers.go:510] HTTP Trace: Dial to tcp:api-server:port succeed
I0317 13:47:40.309039   40290 round_trippers.go:553] DELETE https://api-server:port/api/v1/namespaces/default/configmaps/mymap-parent 200 OK in 117 milliseconds
I0317 13:47:40.309072   40290 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 10 ms TLSHandshake 27 ms ServerProcessing 79 ms Duration 117 ms
I0317 13:47:40.309078   40290 round_trippers.go:577] Response Headers:
I0317 13:47:40.309085   40290 round_trippers.go:580]     Date: Fri, 17 Mar 2023 05:47:15 GMT
I0317 13:47:40.309089   40290 round_trippers.go:580]     Audit-Id: ce194833-0b68-4684-9d87-011ce9e150b4
I0317 13:47:40.309094   40290 round_trippers.go:580]     Cache-Control: no-cache, private
I0317 13:47:40.309099   40290 round_trippers.go:580]     Content-Type: application/json
I0317 13:47:40.309103   40290 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 1d71e9c3-a8c2-4af5-b773-ec0020cd3ef1
I0317 13:47:40.309111   40290 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 50fafbbd-cdbf-4b2b-a055-377e36c027b6
I0317 13:47:40.309117   40290 round_trippers.go:580]     Content-Length: 168
I0317 13:47:40.309158   40290 request.go:1154] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Success","details":{"name":"mymap-parent","kind":"configmaps","uid":"4211108b-097f-4174-8850-167a7bed8cc2"}}
configmap "mymap-parent" deleted
I0317 13:47:40.309470   40290 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json" -H "User-Agent: kubectl/v1.25.4 (linux/amd64) kubernetes/872a965" 'https://api-server:port/api/v1/namespaces/default/configmaps/mymap-parent'
I0317 13:47:40.321969   40290 round_trippers.go:553] GET https://api-server:port/api/v1/namespaces/default/configmaps/mymap-parent 404 Not Found in 12 milliseconds
I0317 13:47:40.322016   40290 round_trippers.go:570] HTTP Statistics: GetConnection 0 ms ServerProcessing 12 ms Duration 12 ms
I0317 13:47:40.322023   40290 round_trippers.go:577] Response Headers:
I0317 13:47:40.322030   40290 round_trippers.go:580]     Cache-Control: no-cache, private
I0317 13:47:40.322035   40290 round_trippers.go:580]     Content-Type: application/json
I0317 13:47:40.322039   40290 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 1d71e9c3-a8c2-4af5-b773-ec0020cd3ef1
I0317 13:47:40.322044   40290 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: 50fafbbd-cdbf-4b2b-a055-377e36c027b6
I0317 13:47:40.322049   40290 round_trippers.go:580]     Content-Length: 204
I0317 13:47:40.322053   40290 round_trippers.go:580]     Date: Fri, 17 Mar 2023 05:47:15 GMT
I0317 13:47:40.322059   40290 round_trippers.go:580]     Audit-Id: a697d8ab-a43b-4831-9062-03cef88951ce
I0317 13:47:40.322094   40290 request.go:1154] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"configmaps \"mymap-parent\" not found","reason":"NotFound","details":{"name":"mymap-parent","kind":"configmaps"},"code":404}
```

And the events:

```console
$ kubectl get events
LAST SEEN   TYPE      REASON                     OBJECT                           MESSAGE
47m         Warning   OwnerRefInvalidNamespace   profile/ksa.default.mysa-child   ownerRef [v1/ConfigMap, namespace: , name: mymap-parent, uid: 529e7cc5-e3cb-49a1-99e6-22b26a04d84c] does not exist in namespace ""
```

I found [this related document](https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/) saying:

> In v1.20+, if the garbage collector detects an invalid cross-namespace ownerReference, or a cluster-scoped dependent with an ownerReference referencing a namespaced kind, a warning Event with a reason of OwnerRefInvalidNamespace and an involvedObject of the invalid dependent is reported. You can check for that kind of Event by running kubectl get events -A --field-selector=reason=OwnerRefInvalidNamespace.

Looking into the `OBJECT` column of that event I found that the `profile/ksa.default.mysa-child` is a calico Custom Resource:

```console
$ kubectl get profile/ksa.default.mysa-child -o yaml
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  creationTimestamp: "2023-03-17T06:10:30Z"
  name: ksa.default.mysa-child
  resourceVersion: /18750505
  uid: 10e5e683-c04c-4716-8ce6-27e23dd6df01
spec:
  labelsToApply:
    pcsa.projectcalico.org/name: mysa-child
```

So I guess this cluster-scoped resouce blocks the deletion of the ServiceAccount.

Closing this issue as it's not a kubernetes problem. Thank you very much for the help!

**Comment by edwardzjl** [comment]
Sorry to reopen the issue, but I'm still not clear.

The `profile/ksa.default.mysa-child` does not have a `ownerReferences` field. Instead it has the same uid as the ServiceAccount:

```console
$ kubectl get sa mysa-child -o yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-03-17T06:43:37Z"
  name: mysa-child
  namespace: default
  ownerReferences:
  - apiVersion: v1
    kind: ConfigMap
    name: mymap-parent
    uid: 00be8530-aa30-4ff5-a7a5-a6b55892bfc7
  resourceVersion: "18769347"
  uid: 965967ae-a944-4e69-95c8-46fdb4d8327a

$ kubectl get profile/ksa.default.mysa-child -o yaml
apiVersion: projectcalico.org/v3
kind: Profile
metadata:
  creationTimestamp: "2023-03-17T06:43:37Z"
  name: ksa.default.mysa-child
  resourceVersion: /18769347
  uid: 965967ae-a944-4e69-95c8-46fdb4d8327a
spec:
  labelsToApply:
    pcsa.projectcalico.org/name: mysa-child
```

But it seems that the garbage collector tries to gc the `profile/ksa.default.mysa-child` as a child resource of the parent ConfigMap?

**Comment by liggitt** [comment]
I saw the comment about the calico API server reusing the same UID for two different objects at https://github.com/projectcalico/calico/issues/5715#issuecomment-1473676706

That is will definitely break the garbage collector, sometimes flakily depending on which object was observed first. 

Closing this since that seems like the cause of this flake. 

/close
