### ISSUE TITLE
[Question] Any notification or event can be received when the NetworkPolicy effectively applied?

### ISSUE THREAD

**Issue by fujitatomoya** [kubernetes/kubernetes#116608]
[issue/trouble shooting](https://github.com/kubernetes/community/tree/master/communication#issues--troubleshooting) led me to post the issue here.

### Description

It was not clear that how application (application uses k8s api) can know the NetworkPolicy applied to pods effectively.
Is there any ways or best practice for this, to receive the event or notification that tells that NetworkPolicy applied to pods effectively?

**Comment by neolit123** [comment]
please see
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
