### ISSUE TITLE
ValidateKubeletConfiguration does not validate the ResolverConfig option

### ISSUE THREAD

**Issue by claudiubelu** [kubernetes/kubernetes#116625]
### What happened?

The ``--resolv-conf`` kubelet flag is not being validated by the ``ValidateKubeletConfiguration`` [1] (e.g.: the given file may not exist), which can lead to Pod DNS Policies no applying properly for the Pods spawned on the node.

[1] https://github.com/kubernetes/kubernetes/blob/758b4641522ec279af99d218dba3deeca867b194/pkg/kubelet/apis/config/validation/validation.go#L43

### What did you expect to happen?

Kubelet should fail fast if the set ``--resolv-conf`` flag is invalid.

### How can we reproduce it (as minimally and precisely as possible)?

Start Kubelet with an invalid flag.

### Anything else we need to know?

Problem raised in the comment: https://github.com/kubernetes/kubernetes/pull/110566/files#r1136100726

### Kubernetes version

Kubernetes v1.27 and older.

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by SergeyKanzhelev** [comment]
is it a behavior introduced in 1.27 or it existed before (looking at affected versions section)?
