### ISSUE TITLE
Failure cluster [ee841810...] ci-kubernetes-kubemark-500-gce failed after code freeze

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116646]
### Failure cluster [ee841810df62a739a098](https://go.k8s.io/triage#ee841810df62a739a098)

> Updated [https://www.googleapis.com/compute/v1/projects/k8s-infra-e2e-boskos-scale-21/zones/us-central1-f/instances/kubemark-500-master].
> Failed to execute 'sudo /bin/bash /home/kubernetes/bin/kube-master-internal-route.sh' on kubemark-500-master despite 5 attempts
> Last attempt failed with: /bin/bash: /home/kubernetes/bin/kube-master-internal-route.sh: No such file or directory
> Creating nodes.
> /home/prow/go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 1552: WINDOWS_CONTAINER_RUNTIME: unbound variable
> /home/prow/go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 1552: WINDOWS_ENABLE_HYPERV: unbound variable
> /home/prow/go/src/k8s.io/kubernetes/kubernetes/cluster/../cluster/../cluster/gce/util.sh: line 1552: ENABLE_AUTH_PROVIDER_GCP: unbound variable
> Using subnet kubemark-500-custom-subnet
> 

##### Error text:
```
error during test/kubemark/start-kubemark.sh: exit status 1
```
#### Recent failures:
[2023/3/15 14:36:24 ci-kubernetes-kubemark-500-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1635892108143366144)
[2023/3/15 14:15:13 ci-kubernetes-kubemark-high-density-100-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-high-density-100-gce/1635886820132655104)
[2023/3/15 13:36:12 ci-kubernetes-kubemark-500-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1635877004903452672)
[2023/3/15 13:05:06 ci-kubernetes-kubemark-100-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-100-gce/1635869204622086144)
[2023/3/15 12:35:05 ci-kubernetes-kubemark-500-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce/1635861654866497536)

/kind failing-test

**Comment by pacoxu** [comment]
hollow node not ready.

> replicationcontroller/hollow-node created
> Created secrets, configMaps, replication-controllers required for hollow-nodes.
> Waiting for all hollow-nodes to become Running......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
> [0;31m Timeout waiting for all hollow-nodes to become Running. [0m
> Found only 1 ready hollow-nodes while waiting for 500.
>

**Comment by mborsz** [comment]
I think it should be fixed with https://github.com/kubernetes/kubernetes/pull/116645

**Comment by pacoxu** [comment]
> I think it should be fixed with https://github.com/kubernetes/kubernetes/pull/116645

/close

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-kubemark-500-gce
is green.
