### ISSUE TITLE
Can we release a simple kubectl image

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#116667]
Would it be possible to build a binary image of just kubectl with each release?  I keep finding things that I could solve with a sidecar container and a shell script around kubectl, but (AFAICT) we don't produce such a thing.  I know it's unpleasant to produce and support images with shells in them, so I am looking for thoughts on what the best path might be.  If we had a base-image with kubectl and nothing else it would be a good start.

**Comment by dims** [comment]
@thockin what arch(es) should we do this for?

**Comment by thockin** [comment]
I don't see why we wouldn't do all (if we expect people to use this as a
sidecar) but I only care about linux amd64, personally.

**Comment by sftim** [comment]
> base-image with kubectl and nothing else

Tricky to do that on Windows, I suspect. Maybe it's possible. For Linux it'd work fine.

**Comment by BenTheElder** [comment]
> base-image with kubectl and nothing else

tzdata / ca certs bundle / nsswitch.conf will also be wanted

**Comment by thockin** [comment]
For some reason, I thought this was done, but I don't see any images pushed.  Did I imagine this getting done?

**Comment by thockin** [comment]
Nevermind - images started pushing with 1.28

registry.k8s.io/kubernetes/kubectl:v1.28.0-alpha.1
