### ISSUE TITLE
Kubernetes e2e suite: [It] [sig-cli] Kubectl client kubectl subresource flag GET on status subresource of built-in type (node) returns identical info as GET on the built-in type expand_less

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#116614]
### Which jobs are flaking?

Example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/116611/pull-kubernetes-e2e-gce/1635729618159800320/

@MadhavJivrajani this PR seems to be flaking: https://github.com/kubernetes/kubernetes/pull/116590

comparing age of a node from the output of two commands: https://github.com/kubernetes/kubernetes/blob/9c2d28f7d55a5210d02b9a3c7dc6449b9e125340/test/e2e/kubectl/kubectl.go#L1989-L1993

### Which tests are flaking?

Kubernetes e2e suite: [It] [sig-cli] Kubectl client kubectl subresource flag GET on status subresource of built-in type (node) returns identical info as GET on the built-in type expand_less

### Since when has it been flaking?

5 hours back

### Relevant SIG(s)

/sig cli

**Comment by aojea** [comment]
it seems that is comparing subresources and there is something there that changes over time

```
I0314 20:18:33.796]   [FAILED] Expected
I0314 20:18:33.796]       <string>: "...  3m22s   v..."
I0314 20:18:33.796]   to equal               |
I0314 20:18:33.796]       <string>: "...  3m23s   v..."
I0314 20:18:33.796]   In [It] at: test/e2e/kubectl/kubectl.go:1993 @ 03/14/23 20:18:20.171
```

As Sergey correctly points out is the Age
```
kubectl get nodes multi-worker --subresource=status
NAME           STATUS   ROLES    AGE     VERSION
multi-worker   Ready    <none>   6h42m   v1.27.0-alpha.3.585+6c0f88aea74dfc-dirty
```

```
kubectl get nodes multi-worker --subresource=status
NAME           STATUS   ROLES    AGE     VERSION
multi-worker   Ready    <none>   6h42m   v1.27.0-alpha.3.585+6c0f88aea74dfc-dirty
```

The test can not assume the executions will be done in the same second
