### ISSUE TITLE
[Failing Test] kubeadm-kinder-upgrade-1-26-latest,kubeadm-kinder-latest

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#116650]
### Which jobs are failing?

master-informing

- kubeadm-kinder-upgrade-1-26-latest
- kubeadm-kinder-latest

### Which tests are failing?

`Kubernetes e2e suite: [It] [sig-api-machinery] CustomResourcePublishOpenAPI [Privileged:ClusterAdmin] works for CRD with validation schema [Conformance]`

### Since when has it been failing?

03-15 04:46 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-1-26-latest

### Reason for failure (if possible)

```
{ failed [FAILED] kubectl explain e2e-test-crd-publish-openapi-6480-crds.spec.bars result {KIND:     e2e-test-crd-publish-openapi-6480-crd
VERSION:  crd-publish-openapi-test-foo.example.com/v1

RESOURCE: bars <[]Object>

DESCRIPTION:
     List of Bars and their specs.

FIELDS:
   age	<string>
     Age of Bar.

   bazs	<[]string>
     List of Bazs.

   feeling	<string>
     Whether Bar is feeling great.

   name	<string> -required-
     Name of Bar.

} doesn't match pattern {(?s)FIELD:.*bars.*<\[\]Object>.*DESCRIPTION:.*List of Bars and their specs.*FIELDS:.*bazs.*<\[\]string>.*List of Bazs.*name.*<string>.*Name of Bar}
In [It] at: test/e2e/apimachinery/crd_publish_openapi.go:133 @ 03/15/23 13:53:06.423
}
```

### Relevant SIG(s)

/sig api-machinery

**Comment by aojea** [comment]
this is a conformance test, so something has to happen with this specific environment, or it should be failing in all jobs
The fact that the job name has upgrade in the name indicates that there can be some skew problem, @neolit123 @fabriziopandini which e2e test run this job and against which version?

**Comment by aojea** [comment]
Confirmed this is passing in other jobs
https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel&include-filter-by-regex=CustomResourcePublishOpenAPI

https://testgrid.k8s.io/sig-release-master-blocking#gce-cos-master-default&include-filter-by-regex=CustomResourcePublishOpenAPI

This is related to this specific job

**Comment by pacoxu** [comment]
Can we add `--output plaintext-openapiv2` to the conformance test?
- I tried a fix like https://github.com/kubernetes/kubernetes/pull/116657/files.
