### ISSUE TITLE
What is the relationship between HPA/VPA and K8s-scheduler?

### ISSUE THREAD

**Issue by linhil** [kubernetes/kubernetes#116699]
What is the relationship between HPA/VPA and K8s-scheduler?

I’m wondering that if a HPA(horizontal pod auto-scaler) or VPA(vertical pod auto-scaler) works, how does these two component call and interact with K8s-scheduler?

I think it is a little intricated, If the dependency between HPA/VPA and scheduler is difficult to express, is there any specific document that can be learned from？

Thanks a lot!

**Comment by charles-chenzz** [comment]
/kind support

I think HPA/VPA is more like a strategy about scaling up and down, it's about pod's number. and scheduler is like bind the pod to the place where it should be

**Comment by linhil** [comment]
> /kind support
> 
> I think HPA/VPA is more like a strategy about scaling up and down, it's about pod's number or resource. and scheduler is like bind the pod to the place where it should be

Yes, I know it. does HPA/VPA implemeted in K8s depends on scheduler to work? and how does they interact with each other?

**Comment by charles-chenzz** [comment]
> > /kind support
> > I think HPA/VPA is more like a strategy about scaling up and down, it's about pod's number or resource. and scheduler is like bind the pod to the place where it should be
> 
> Yes, I know it. does HPA/VPA implemeted in K8s depends on scheduler to work? and how does they interact with each other?

I think HPA/VPA is on the level of controller, related to replicaset/ deployment. it's like reconile, if you set up a HPA/VPA, the controller monitor and detect the state need to be scale up/down, then it create the pod or request more resource, then the scheduler detect it then start scheduling

**Comment by linhil** [comment]
> 



> > > /kind support
> > > I think HPA/VPA is more like a strategy about scaling up and down, it's about pod's number or resource. and scheduler is like bind the pod to the place where it should be
> > 
> > 
> > Yes, I know it. does HPA/VPA implemeted in K8s depends on scheduler to work? and how does they interact with each other?
> 
> I think HPA/VPA is on the level of controller, related to replicaset/ deployment. it's like reconile, if you set up a HPA/VPA, the controller monitor and detect the state need to be scale up/down, then it create the pod or request more resource, then the scheduler detect it then start scheduling. and I think it's more depend on kubelet since only kubelet directly create/delete pod

Thank you for your reply! I have another question, how does replicaset/ deployment interact or work with kube-scheduler?

**Comment by charles-chenzz** [comment]
replicaset/deployment is on the level of controller-manager right? it create the replicaset / deployment and tell api-server, then scheduler base on  predicate/ priority strategy to shedule and tell api-server where the pod should go. then the kubelet get info from api-server and know that there's a pod need to run on its node then it start working. what I say is the step of it but in fact (in the source code) it's more complicated.

**Comment by linhil** [comment]
> replicaset/deployment is on the level of controller-manager right

Thank you for your reply, and I think I need to learn some basic knowledge about K8s.

**Comment by sftim** [comment]
GitHub is not the right place for support requests.

For help, try [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
/close
