### ISSUE TITLE
Openshift origin example not working

### ISSUE THREAD

**Issue by hingstarne** [kubernetes/kubernetes#11661]
Hi all,
due to a change in the cli usage of the openshift command the part
https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/openshift-origin/README.md#step-4-bundle-the-configuration-into-a-secret
does not work anymore.

**Comment by Smana** [comment]
I have the same issue there.
Thanks

**Comment by Smana** [comment]
@hingstarne please let me know if you figure out a workaround.

**Comment by bgrant0607** [comment]
Cc @derekwaynecarr

**Comment by hingstarne** [comment]
@Smana 
i assume 
docker run -i -t --privileged -e="OPENSHIFTCONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin ex bundle-secret openshift-config -f /config &> ${OPENSHIFT_EXAMPLE}/secret.json

should be 
docker run -i -t --privileged -e="OPENSHIFTCONFIG=/config/admin.kubeconfig" -v ${OPENSHIFT_CONFIG}:/config openshift/origin secret add openshift-config /config -0 json &> ${OPENSHIFT_EXAMPLE}/secret.json

I will try that and make a pr for it

**Comment by Smana** [comment]
Thanks @hingstarne 
Unfortunately i got that : 
```
cat ${OPENSHIFT_EXAMPLE}/secret.json
Error: unknown command "secrets"
Run 'openshift help' for usage.
```

**Comment by hingstarne** [comment]
sorry i forgot the cli between
openshift/origin cli secrets new openshift-config /config -0 json

but for some reason when i run it without docker ( with the released binaries it works ) but from within the docker container it always complain about nno servers defined at least for me

**Comment by Smana** [comment]
@hingstarne 
```
cat ${OPENSHIFT_EXAMPLE}/secret.json
Error: unknown shorthand flag: '0' in -0
Run 'openshift help' for usage
```

**Comment by bgrant0607** [comment]
That should be `-o` (lowercase o)

**Comment by bgrant0607** [comment]
`ex bundle-secret` was the pre-GA experimental command. Try openshift/origin cli help secrets and/or take a look at the CLI reference:
https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html#advanced-commands

**Comment by hingstarne** [comment]
bin/openshift cli secrets new openshift-config examples/openshift-origin/config -o json
```
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "openshift-config",
        "creationTimestamp": null
    },
    "data": {
        "admin.crt": "LS0tLS1CR....
```

**Comment by derekwaynecarr** [comment]
@stevekuznetsov can assist here.  

He has a PR that was still pending here
https://github.com/GoogleCloudPlatform/kubernetes/pull/9938

If you work from that example I think the CLI has no issue, but web console was broke with removal of v1beta3 in Kube.  

I believe we are in the works of fixing that but since I have been traveling I don't know latest state.

**Comment by hingstarne** [comment]
@Smana 
docker run -i -t --privileged -e KUBECONFIG=/kubeconfig -v ${HOME}/.kube/config:/kubeconfig -v ${OPENSHIFT_CONFIG}:/config openshift/origin cli secrets new openshift-config /config -o json &> ${OPENSHIFT_EXAMPLE}/secret.json
This worked for me ...
At least openshift was started and i could access the ui with it

**Comment by Smana** [comment]
Hello,
Thank you all for your help :)
I have a related issue but i'll open a new one:
Openshift origin / kubernetes with NodePort

**Comment by tenfourty** [comment]
Hi All - I've been messing around with this and have blogged what I think is a working solution - it's based on @derekwaynecarr's original example we are talking about in this issue but I've made some changes to use my local kubectl <http://www.tenfourty.com/2015/07/28/how-to-run-openshift-v3-on-an-existing-kubernetes-cluster/>

**Comment by stevekuznetsov** [comment]
You are missing some sections that will mean you're cluster is not
functional. Please look at #9938.

**Comment by tenfourty** [comment]
@stevekuznetsov that is cool - I'll update my example with your work - adding etcd as a standalone pod was the next thing I was going to do anyway.
Also commented on #9938.

**Comment by Smana** [comment]
thanks for your link @tenfourty 
Unfortunately it won't fix my problem : 
i've my openshift pod running but it doesn't seem to be able to request kubernectes api.
The ip address is reachable but maybe some configuration parameters are missing.

To be honest i don't know where to look. That's why i need your help guys :)

**Comment by stevekuznetsov** [comment]
@Smana Disregard that link, the up-to-date directions are in the README in #9938. What errors are you seeing requesting the Kubernetes API?

**Comment by Smana** [comment]
Oups i posted in the wrong issue, my opened issue is :
https://github.com/GoogleCloudPlatform/kubernetes/issues/11869

I thougt i've closed that one

**Comment by anguslees** [comment]
(@mbforbes: openshift != openstack)

**Comment by stevekuznetsov** [comment]
I believe this is resolved - the PR (#9938) merged quite a while ago.

**Comment by Smana** [comment]
My opened issue #11869 is still opened and it is not solved given my latest tests.

**Comment by stevekuznetsov** [comment]
@Smana That issue can remain open, then. This one has been resolved.

**Comment by Smana** [comment]
Ok thank you
