### ISSUE TITLE
What will happen if I adjust hte cgroup parameter when the pod has been assigned to a resource request/limit 

### ISSUE THREAD

**Issue by xfyan0408** [kubernetes/kubernetes#116698]
I want to ask if I change the CPU and memory size of a Pod at runtime, will it be detected by kubelet and forced to return to the set limit and request?

That is, if I set the both of CPU limit and request to 1000m, and I change pod’s CPU resource to 500m through cgroup at runtime, will this be forced back to 1000m by some mechanism of K8s?

Thanks a lot!

**Comment by pacoxu** [comment]
/kind support
/sig node
As I know, kubelet only set cgroup during pod creation/startup or resource limit changes after VPA is available.

**Comment by pranav-pandey0804** [comment]
hi @xfyan0408  hope you found the solution,
If not then You might want to seek help on [Server Fault](https://serverfault.com/questions/tagged/kubernetes), or post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes forum](https://discuss.kubernetes.io/). These are better places for support requests than GitHub.

**Comment by pranav-pandey0804** [comment]
@xfyan0408 Please close the issue, thanks!
