### ISSUE TITLE
Pod template tracking uses fixed, non-prefixed label keys

### ISSUE THREAD

**Issue by sftim** [kubernetes/kubernetes#116644]
### What happened?

Per https://github.com/kubernetes/kubernetes/pull/114930#issuecomment-1469940664, the `pod-template-hash` label is a private one (reserved for cluster operators). It should be something more like `kubernetes.io/pod-template-hash` or maybe `kubernetes.io/pod-template-hash-sha256`.

### How can we reproduce it?

(for example)
Deploy a Kubernetes cluster that includes CoreDNS running as a Deployment.

/sig apps

https://kubernetes.io/docs/reference/labels-annotations-taints/ lists all the registered label and annotation keys for the Kubernetes project.

**Comment by sftim** [comment]
This one won't be easy to migrate. If we make the change, we should allow a long transition period.

**Comment by kidddddddddddddddddddddd** [comment]
I'm interested in this one, can I have a try? :)

**Comment by kannon92** [comment]
Go ahead! I think we are in a code freeze but that shouldn’t stop you from taking the issue. Just not sure if it will be merged in the current release.

**Comment by sftim** [comment]
/remove-lifecycle stale

Still ought to get fixed IMO

**Comment by sftim** [comment]
(can we at least triage it?)
