### ISSUE TITLE
race condition on iptable switching node to NodeNotReady (v1.0.1)

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#11667]
Kubelet log :
Jul 21 11:54:28 internal-minion-001 kubelet[5301]: E0721 11:54:28.729442    5301 kubelet.go:1959] Error on adding ip table rules: exit status 4
Jul 21 11:54:30 internal-minion-001 kubelet[5301]: I0721 11:54:30.150103    5301 kubelet.go:1942] Recording NodeNotReady event message for node internal-minion-001

Env informations : 
11 nodes n1-highmem-2 ~100 pods 
nodes are coreos powered - master is the one installed via kube-up

kube-proxy is running ~ 20% cpu majority of the time on each node.

I've managed to wipe etcd db to have a clear & clean install for 1.0.1

**Comment by thockin** [comment]
@bnprss Sorry I missed this before - what cloud and OS?

**Comment by bnprss** [comment]
@thockin 
Cloud provider : GCE
Master node: debian as provided by kube-up script
Nodes : coreos (ens4v1 network interface instead of eth0)

I see my issue need more informations that ticket was related to https://github.com/kubernetes/kubernetes/pull/11810

And caused by kubelet iptables calls blocked by kube-proxy updatating xtables.

**Comment by thockin** [comment]
Great, hopefully this is all fixed at once, then.
