### ISSUE TITLE
Kube-APIServer entering failed state on startup after upgrade to V1.0.1

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#11674]
I tried upgrading from v0.21.1 to v1.0.1 today but hit a roadblock when starting the master node.

Using CoreOS 

#### Upgrade Process: 
1. Update cloudconfig files to download v1.0.1
2. Shut down all nodes
3. Turn on each node one at a time starting with master 

#### Logs from starting the apiserver:
```
I0721 18:00:19.530662    5393 plugins.go:69] No cloud provider specified.
I0721 18:00:19.531147    5393 master.go:273] Node port range unspecified. Defaulting to 30000-32767.
[restful] 2015/07/21 18:00:19 log.go:30: [restful/swagger] listing is available at https://10.128.63.120:6443/swaggerapi/
[restful] 2015/07/21 18:00:19 log.go:30: [restful/swagger] https://10.128.63.120:6443/swaggerui/ is mapped to folder /swagger-ui/
F0721 18:00:19.574221    5393 controller.go:80] Unable to perform initial IP allocation check: unable to refresh the service IP block: no kind "Service" is registered for version "v1beta3"
```

**Comment by esecules** [comment]
I have since reverted back to v0.21.1 because I can't afford the extended downtime.

**Comment by bnprss** [comment]
get same error upgrade from < 1.0.0 to 1.0.0 or 1.0.1.
resolved by deleting etcd history. Yes whole db, no more running ns, pods, rc, svcs. There is no more v1beta3 api on v1.0.0 or 1.0.1 but no upgrade path that convert old apis definition to new ones.

**Comment by bprashanth** [comment]
@bgrant0607 @nikhiljindal

**Comment by esecules** [comment]
so as of v1 I have to rewrite all my service and rc json files to change from v1beta3 to v1? Is there documentation on what has changed between those API versions?

**Comment by nikhiljindal** [comment]
@bnprss We have a script to help you update your etcd objects from v1beta3 to v1: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/update-storage-objects.sh. You need to run that script on a cluster, which supports both the old and new api versions.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/cluster-management.md#upgrading-to-a-different-api-version has the generic steps for updgrading your cluster to use a new api version.

**Comment by nikhiljindal** [comment]
@esecules https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/api.md#v1-conversion-tips-from-v1beta3 lists the differences between v1 and v1beta3.

We have built a tool to help you convert your configs to the new version. https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/cluster-management.md#switching-your-config-files-to-a-new-api-version has details on that.

**Comment by fzu-huang** [comment]
i think  maybe  you  should clear you data in etcd.  shut down all kube* processes.and exec:
./etcdctl rm --resurcive /registry

then start kubernetes Master and Slavers.
GL : )

**Comment by mbforbes** [comment]
@esecules any update? Did the above steps help?

**Comment by esecules** [comment]
I tried updating to 1.0.3, and got all the kube* services up. But service name resolution is broken. for instance kubectl get services says redis has the IP 10.100.250.120, but when I ping it, i get the service name resolving to  10.100.209.170 and the pings are all dropped

**Comment by esecules** [comment]
My kube2sky needs updating, thats it. They were resolving to stale DNS entries.
