### ISSUE TITLE
Investigate if mirror pod spec updates are propagated correctly on static pod manifest recreates

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#116725]
### What happened?

In the debugging of the [mirror pod test](https://github.com/kubernetes/kubernetes/blob/6b9a381/test/e2e_node/mirror_pod_test.go#L155-L199) as part https://github.com/kubernetes/kubernetes/pull/115331 test  `should successfully recreate when file is removed and recreated [NodeConformance]`, we found after the e2e recreates the pod manifest, in some cases the mirror pod is [recreated here](https://github.com/kubernetes/kubernetes/blob/6b9a381/pkg/kubelet/kubelet.go#L1784-L1813) while in other cases it is not.

There was some concern that if the static pod manifest is changed, the static pod's spec may have not been propagated successfully to the mirror pod and only the status would be updated.  

We need to followup to investigate if this is the case. One option might be to add a new e2e test that follows the existing one, but also changes the static pod manifest on recreate, and then verifies the spec is always updated correctly to verify that spec is updated with latest manifest.

### What did you expect to happen?

When recreating a static pod with uid reuse and the static pod manifest changing, the mirror pod's spec is always successfully updated and reflects the latest static pod's manifest.  

### How can we reproduce it (as minimally and precisely as possible)?

TBD, need to reproduce. 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mimowo** [comment]
@bobbypage please take a look at the closely related issue about the flaky test I created. I attach some logs from my experiments there: https://github.com/kubernetes/kubernetes/issues/116714

**Comment by SergeyKanzhelev** [comment]
Is it a dup of https://github.com/kubernetes/kubernetes/issues/116597?

**Comment by SergeyKanzhelev** [comment]
/triage accepted

is it a regression from 1.27 or something old?

**Comment by bobbypage** [comment]
This is not a regression, more of a bug fix / investigation.

**Comment by bobbypage** [comment]
this seems very similar to https://github.com/kubernetes/kubernetes/issues/116597 actually, thanks for pointer.
