### ISSUE TITLE
High cpu usage of metrics.(*attachDetachStateCollector).Collect

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#116710]
### What happened?

I noticed that kube-controller-manager is consuming visible amount of CPU in completely idle 5k node cluster (~7 cores/s) while for comparison kube-apiserver was using much less that time.

I fetched pprof and noticed that we are burning significant in metrics.(*attachDetachStateCollector).CollectWithStability:![image](https://user-images.githubusercontent.com/2559168/225871722-503ba2e7-2611-4ec7-b05b-b2ef90b55699.png)

Going further, most of the cpu is used for fmt.Errorf for formatting *v1.Volume in line 160: https://github.com/kubernetes/kubernetes/blob/8f94681cd294aa8cfd3407b8191f6c70214973a4/staging/src/k8s.io/csi-translation-lib/translate.go#L145-L164 which is never actually used by the caller https://github.com/kubernetes/kubernetes/blob/8f94681cd294aa8cfd3407b8191f6c70214973a4/pkg/volume/csimigration/plugin_manager.go#L112-L125

### What did you expect to happen?

We do not use significant cpu for preparing error messages that are then ignored.

### How can we reproduce it (as minimally and precisely as possible)?

pprof cluster with some pods and volumes.

### Kubernetes version

<details>
1.26.1
</details>

### Cloud provider

<details>
gke, any?
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mborsz** [comment]
A trivial fix would be actually to change GetInTreePluginNameFromSpec to write only PV/Volume names instead of entire specs in error message.

**Comment by kidddddddddddddddddddddd** [comment]
/assign
In scheduler we use this function to check if we can translate the in-tree PV to CSI, I think we also only need the name of the pv.
I'll create a pr for this one line change.

**Comment by neolit123** [comment]
/sig storage Instrumentation
?
