### ISSUE TITLE
Define ownership of controller/nodelifecycle

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#116771]
/kind cleanup
/kind documentation

/sig scheduling
/sig node
/sig apps

The ownership of controller/nodelifecycle is unclear.

The [OWNERS file of pkg/controller/nodelifecycle](https://github.com/kubernetes/kubernetes/blob/15894cfc85cab64df081bb753b8ccf32a243da68/pkg/controller/nodelifecycle/OWNERS) currently has some individual names and no labels, although it gets a sig/apps label from the parent pkg/controller OWNERS.

This controller has the following functionality:
- Add taints based on health of the node (from conditions)
- Evict Pods based on NoExecute taints.

The candidates for long term ownership are:
1. Scheduling: The ones who introduced it and overall maintain taints and tolerations.
2. Node: Because it's called "node lifecycle", although this could be a misnomer.
3. Apps: Due to implications to the lifecycle of applications and because they are the main shepherds of kcm.

I think it makes the most sense under scheduling, but wanted to gather all stakeholder's feedback.

**Comment by alculquicondor** [comment]
cc @k82cn as original author

**Comment by yuanchen8911** [comment]
Thanks, @ahg-g! It would be nice to sort out the ownership. It sounds reasonable for sig-scheduling to own it.  /cc @Huang-Wei

**Comment by alculquicondor** [comment]
Outcome from SIG meeting:

As https://github.com/kubernetes/enhancements/pull/3901 already identified, this controller actually has 2 functionalities. From a technical standpoint, the following ownership makes sense to SIG Scheduling leads:
- Setting taints based on Node conditions -> SIG Node
- Evicting pods that don't tolerate NoExecute taints -> SIG Scheduling
This can be done even before https://github.com/kubernetes/enhancements/pull/3901 is implemented, as the taint functionality has its own folder.

I'll create a PR based on the above. But @kubernetes/sig-node-leads and @kubernetes/sig-apps-leads, please raise any concerns.

**Comment by smarterclayton** [comment]
+1 on the proposal - I believe if we were to assign responsibility to who owns node level invariants that apply to workloads, it would be sig-node (they *generally* own node + pod).  pod-safety, for instance, I considered owned by sig-node even though it touches storage, apps, api-machinery, and scheduling because the node owns the pod at the time safety is imposed.
