### ISSUE TITLE
If it is "Not-Applicable" for external IP point to have a value, then `kubectl get services` should display 'N/A' instead of '<none>' 

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/kubernetes#116734]
### What happened?

I am trying to learn k8s and following along in the official tutorials
https://kubernetes.io/docs/tutorials/kubernetes-basics/expose/expose-interactive/

Why is the endpoint empty? The tutorial says that

> We have now a running Service called kubernetes-bootcamp. Here we see
> that the Service received a unique cluster-IP, an internal port and an
> **external-IP (the IP of the Node)**

I only see `<none>` . 

_"External-IP is `<none>` when there is no load balancer" (Sander Van Vugt)_

If it is "Not-Applicable" for external IP point to have a value, then `kubectl get services` should display 'N/A' instead of '`<none>`'. Having `<none>` tells me that something went wrong or was incomplete. 

```
    $ kubectl expose deployment/kubernetes-bootcamp --type="NodePort" --port 8080
    service/kubernetes-bootcamp exposed
    
    $ kubectl get services
    NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
    kubernetes            ClusterIP   10.96.0.1      <none>        443/TCP          9m13s
    kubernetes-bootcamp   NodePort    10.101.46.87   <none>        8080:30568/TCP   7m49s
    
    $ kubectl describe services/kubernetes-bootcamp
    Name:                     kubernetes-bootcamp
    Namespace:                default
    Labels:                   app=kubernetes-bootcamp
    Annotations:              <none>
    Selector:                 app=kubernetes-bootcamp
    Type:                     NodePort
    IP Families:              <none>
    IP:                       10.101.46.87
    IPs:                      10.101.46.87
    Port:                     <unset>  8080/TCP
    TargetPort:               8080/TCP
    NodePort:                 <unset>  30568/TCP
    Endpoints:                172.18.0.4:8080
    Session Affinity:         None
    External Traffic Policy:  Cluster
    Events:                   <none>
  
    
    $ kubectl get services
    NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
    kubernetes            ClusterIP   10.96.0.1      <none>        443/TCP          9m13s
    kubernetes-bootcamp   NodePort    10.101.46.87   **<none>**        8080:30568/TCP   7m49s
```

 

### What did you expect to happen?

Endpoint should either have a value or say N/A
Having `<none>` tells me that something went wrong or was incomplete.

### How can we reproduce it (as minimally and precisely as possible)?

see above.

### Anything else we need to know?

issue reported here https://stackoverflow.com/questions/75727590/why-is-the-service-endpoint-empty-is-it-a-bug-in-the-official-tutorial

### Kubernetes version

<details>

any version

</details>

### Cloud provider

<details>
any provider. tutorials on k8s.io website
</details>

### OS version

<details>

any OS

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> If it is "Not-Applicable" for external IP point to have a value, then `kubectl get services` should display 'N/A' instead of '`<none>`'. Having `<none>` tells me that something went wrong or was incomplete.

This seems an interpretation problem, I don't see why `<none>` means something is wrong , is just that value is empty

Tagging sig cli since they know more about the conventions of the UX tools
/sig cli

**Comment by uablrek** [comment]
You _can_ set `externalIP` for a clusterIP service, e.g. 
```yaml
apiVersion: v1
kind: Service
metadata:
  name: netdebug4
spec:
  selector:
    vmService: vmcalicobridge2
  ports:
    - protocol: TCP
      port: 22
  externalIPs:
    - 1.2.3.4
```
So "N/A" would be wrong IMO. It _is_ applicable, you just haven't set any extenal IPs (there can be many).
