### ISSUE TITLE
kubectl proxy shouldn't buffer watch notifications

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#11678]
If this is by design, we should do a better job of surfacing it in the cluster documentation. Since most other read operations work it's only natural that someone will deploy a kubectl sidecar to watch apiserver resources and it's really hard to notice this is the case, because list works. @lavalamp

**Comment by lavalamp** [comment]
You mean watches don't go through the kubectl proxy? Why not? Timeout set wrong?

**Comment by bprashanth** [comment]
I haven't dug, will do so when I have the time. It's not a timeout, i just don't see any events (even with the bare /watch url, works with localhost:8080 not 8001, but list works through 8001). I'll update when I gather more information, just making sure it wasn't by design.

**Comment by lavalamp** [comment]
Yeah, definitely not by design.

**Comment by bprashanth** [comment]
Hmm, this seems to be specific to services and endpoints

**Comment by bprashanth** [comment]
This is reproducible for any resource small enough to fit in the default reverse proxy buffer (just didn't repro with /pods because pods are big and services/endpoints are not).

**Comment by liggitt** [comment]
the proxy sets a default flushInterval of 200ms now... is this resolved?

**Comment by liggitt** [comment]
it now flushes every 100ms, so watch events under the buffer size don't get stuck in the buffer
