### ISSUE TITLE
"Error: no command specified" when restating a container checkpointed by kubelet checkpoint api 

### ISSUE THREAD

**Issue by abdelghanimeliani** [kubernetes/kubernetes#116744]
### What happened?

I am trying to use the [kubelet checkpoint api](https://kubernetes.io/docs/reference/node/kubelet-checkpoint-api/) to checkpoint some containers and restore them in other nodes .

First i create the container using [this counter image](quay.io/adrianreber/counter:blog) with this yaml configuration file 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: counters
spec:
  containers:
  - name: counter
    image: quay.io/adrianreber/counter:blog
```
The pod starts successfully as shown 

![image](https://user-images.githubusercontent.com/62490938/226189119-afcd8374-67a5-4942-a720-526c425d314d.png)

The i uses the kubelet checkpoint api to request a checkpoint for the counter container which is inside the counters pod inside the default namespace 

```sh
curl -sk -X POST  "https://localhost:10250/checkpoint/default/counters/counter" \
  --key /etc/kubernetes/pki/apiserver-kubelet-client.key \
  --cacert /etc/kubernetes/pki/ca.crt \
  --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt
```

the response was 
```
{"items":["/var/lib/kubelet/checkpoints/checkpoint-counters_default-counter-2023-03-19T13:22:12Z.tar"]}
```
that's prouve that the checkpoint was created 
![image](https://user-images.githubusercontent.com/62490938/226189640-cc284c57-3c3a-41fc-b004-06a56f3c7420.png)

i tryed to use buildah to build a new image from the checkpoint so i ceated a Dockerfime confains 
```Dockerfile
FROM scratch
ADD counter.tar .
```
and i lanced this command after changing the name of the checkpont to counter.tar

```sh
buildah bud \
  --annotation=io.kubernetes.cri-o.annotations.checkpoint.name=webserver \
  -t restore-webserver:latest \
  Dockerfile .
```
i pushed this image to dockerhub, you can acces ti via [this link](https://hub.docker.com/repository/docker/abdelghanimeliani/restore-counter/general) 
and also via [this link](https://quay.io/repository/abdelghanimeliani/restore-counter?tab=tags)

Now , i created a new pod config file to restore the counter container
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: counters-form-checkpoint
spec:
  containers:
  - name: counter
    image: docker.io/abdelghanimeliani/restore-counter
```

the pod blocks in the * ImagePullBackOff* state 

![image](https://user-images.githubusercontent.com/62490938/226190532-513b1c82-4596-4c42-bed7-eaa462e91b3f.png)

when i desribe the pod i got this from kubelet
![image](https://user-images.githubusercontent.com/62490938/226217782-123599c8-02c5-4a3d-8d76-980b1bcf0ff0.png)

### What did you expect to happen?

i expect that he counter image restore from the last state before the checkpoint 

### How can we reproduce it (as minimally and precisely as possible)?

i don't know exactly where is the problme but i think that something is wrong with the checkpoint it self , i tried to load a new image from the same checkpoint with the docker load and i got this :

![image](https://user-images.githubusercontent.com/62490938/226218563-af3c1e6b-fc04-40d2-85e1-ca95ae0dd2f8.png)

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
im using kubernetes in my local pc with one master node and three workers configured with kubeadm
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
 Linux kubemaster 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kubelet=1.25.0-00 kubeadm=1.25.0-00 kubectl=1.25.0-00
</details>

### Container runtime (CRI) and version (if applicable)

<details>
crio  1.25.0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
calico v3.24.0
</details>

**Comment by pacoxu** [comment]
The pod failed for `Error: no command specified`. I am afraid that the command(entry point) of the pod(image) is not specified properly.

**Comment by abdelghanimeliani** [comment]
@pacoxu but i didn't specify any command when i run my initial container and it worked .
i had the same error with two different images the second one is nginx

**Comment by pacoxu** [comment]
> @pacoxu but i didn't specify any command when i run my initial container and it worked . i had the same error with two different images the second one is nginx

I would use something like `sleep 3600` or `sleep infinity` to debug things.

**Comment by abdelghanimeliani** [comment]
> > @pacoxu but i didn't specify any command when i run my initial container and it worked . i had the same error with two different images the second one is nginx
> 
> I would use something like `sleep 3600` or `sleep infinity` to debug things.

i already did this and i got **kubelet  Error: container create failed: time="2023-03-21T13:49:18Z" level=error msg="container_linux.go:380: starting container process caused: exec: \"sleep\": executable file not found in $PATH"**

**Comment by abdelghanimeliani** [comment]
@pacoxu , you can notice also that the new image (created from the checkpoint) is smaller than the original one and i think that is not normal .

![image](https://user-images.githubusercontent.com/62490938/226628645-ab9ca4e8-9999-4b6c-9fb9-f5fbdb55404f.png)

**Comment by adrianreber** [comment]
This is a CRI-O issue. Please see the CRI-O discussion you started for details.

**Comment by abdelghanimeliani** [comment]
> This is a CRI-O issue. Please see the CRI-O discussion you started for details.

okey , i will cloose this issue since it's a CRI-O issue and contenue in this [CRI-O discution](https://github.com/cri-o/cri-o/discussions/6749)
