### ISSUE TITLE
poll deprecation notices point to non-existent PollWithContextTimeout

### ISSUE THREAD

**Issue by skitt** [kubernetes/kubernetes#116712]
### What happened?

I noticed that all the old `apimachinery/pkg/util/wait` `Poll…` functions have been deprecated, pointing to `PollWithContextTimeout`; but that function doesn’t exist, and doesn’t appear in https://github.com/kubernetes/kubernetes/pull/107826 which introduced the change.

### What did you expect to happen?

I expect `PollWithContextTimeout` to exist, or the deprecation notices to point to another function.

The only similar candidate is `PollUntilContextTimeout`, but its documentation says

> All other behavior is identical to PollWithContextTimeout.

which suggests that `PollWithContextTimeout` is different.

### How can we reproduce it (as minimally and precisely as possible)?

See the notice on https://pkg.go.dev/k8s.io/apimachinery@v0.27.0-beta.0/pkg/util/wait#PollImmediate and try to find the replacement function.

### Kubernetes version

1.27.0-beta.0

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kidddddddddddddddddddddd** [comment]
+1. I encountered this issue as well when I was trying to use `PollImmediateUntil`.

**Comment by jiahuif** [comment]
This problem seems to be caused by changes requested during reviews there https://github.com/kubernetes/kubernetes/pull/107826 

The statement in the comment of `PollUntilContextTimeout`, "All other behavior is identical to PollWithContextTimeout." is probably wrong. From the context I guess you meant to compare the new function to one of the old deprecated ones. @smarterclayton, could you confirm?

/unassign
/cc
/assign @smarterclayton

**Comment by alculquicondor** [comment]
cc @aojea as reviewer of the PR

**Comment by aojea** [comment]
> cc @aojea as reviewer of the PR

it seems a naming problem, Clayton had to refactor the PR multiple times, wait for him to confirm

**Comment by kerthcet** [comment]
> Bumped into this as well. Any guidance for us, @smarterclayton ?

I think this is solved with the master codebase.
