### ISSUE TITLE
[Failing Test] verify-master

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#116703]
### Which jobs are failing?

master-blocking

- verify-master

### Which tests are failing?

`verify.openapi-spec`

### Since when has it been failing?

03-17 06:33 IST

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

```
{Script Error ScriptError go version go1.20.2 linux/amd64
rm: cannot remove '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/*': No such file or directory
rm: refusing to remove '.' or '..' directory: skipping '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/.'
rm: refusing to remove '.' or '..' directory: skipping '/home/prow/go/src/k8s.io/kubernetes/hack/../api/openapi-spec/v3/..'
/home/prow/go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh}
```

### Relevant SIG(s)

/sig api-machinery

**Comment by pacoxu** [comment]
/home/prow/go/src/k8s.io/kubernetes/api/openapi-spec is out of date. Please run hack/update-openapi-spec.sh}

- I opened https://github.com/kubernetes/kubernetes/pull/116705
