### ISSUE TITLE
"Programmer error" is logged often during tests [kubelet_working_pods metric, SyncKnownPods]

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#116715]
### What happened?

The following log line is often (~30times) logged during our tests in `pull-kubernetes-node-e2e-containerd`:
`"Programmer error, did not report a kubelet_working_pods metric for a value returned by SyncKnownPods" counts=map[{State:sync Orphan:false HasConfig:false Static:false}:1]`.

This suggests a possible bug as it was assumed to do not happen.

### What did you expect to happen?

No log line saying `Programmer error`.

### How can we reproduce it (as minimally and precisely as possible)?

Look at artifacts of all (or almost all) builds of: https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-node-e2e-containerd

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
Reproducible in tests
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mimowo** [comment]
/sig node
FYI @bobbypage @smarterclayton

**Comment by SergeyKanzhelev** [comment]
/triage accepted

since it's a new error, it is a regression. So adding a corresponding priority

/priority important-soon

**Comment by SergeyKanzhelev** [comment]
@bobbypage are you working on this? Should I assign bug to you?

**Comment by bobbypage** [comment]
Yes, I'm taking a look at this.

/assign

**Comment by smarterclayton** [comment]
This is a metrics only error (we don’t report a fraction of metrics) and has no functional impact.

**Comment by bobbypage** [comment]
That makes sense, but is it expected that this is a valid static in first place? `State:sync Orphan:false HasConfig:false Static:false`. 

My assumption was that if static is false, (i.e. API pod) then we should have a config?

**Comment by bobbypage** [comment]
I took a closer look at the logs, it seems that this is happening when we enter `HandlePodCleanups` while a static pod is being synced which has UID reuse and another pod which has the same full name did not terminate yet. 

In this case, we block the static pod from starting i.e. (`canStart`) returns false:
 https://github.com/kubernetes/kubernetes/blob/c3e7eca7fd38454200819b60e58144d5727f1bbc/pkg/kubelet/pod_workers.go#L1007-L1019. 

Because the pod can't start, we don't set `startedAt`: https://github.com/kubernetes/kubernetes/blob/c3e7eca7fd38454200819b60e58144d5727f1bbc/pkg/kubelet/pod_workers.go#L1168-L1169

which means that when we log metrics there is no `activeUpdate` set and thus `HasConfig` or `Static` are both defaulted to false:

https://github.com/kubernetes/kubernetes/blob/c3e7eca7fd38454200819b60e58144d5727f1bbc/pkg/kubelet/pod_workers.go#L1548-L1551

```
I0317 23:51:13.624575    1191 pod_workers.go:770] "Pod is being synced for the first time" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 updateType="create"
I0317 23:51:13.624589    1191 pod_workers.go:958] "Notifying pod of pending update" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 workType="sync"
I0317 23:51:13.624628    1191 pod_workers.go:1163] "Pod cannot start yet" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3

>>> (my debug log when !sync.HasConfig && !sync.Static && !sync.Orphan):

I0317 23:51:13.666965    1191 kubelet_pods.go:1217] "bobbypage Programmer error" uid=45f2f5c9d4e1aaa82bf8d63ce6d263f3


I0317 23:51:13.725832    1191 kubelet.go:2182] "Pod has been deleted and must be killed" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3
I0317 23:51:13.725856    1191 pod_workers.go:862] "Pod is being removed by the kubelet, begin teardown" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 updateType="kill"
I0317 23:51:13.725868    1191 pod_workers.go:958] "Notifying pod of pending update" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 workType="terminating"
I0317 23:51:13.725899    1191 pod_workers.go:965] "Cancelling current pod sync" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 workType="terminating"
I0317 23:51:13.726117    1191 pod_workers.go:1159] "Pod cannot start ever" pod="mirror-pod-with-grace-period-6069/graceful-pod-064da8be-e57f-42e4-9492-be5f17dd70c2-tmp-node-e2e-f278af70-cos-stable-101-17162-127-33" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3 updateType="terminating"
I0317 23:51:13.726147    1191 pod_workers.go:946] "Pod worker has stopped" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3
I0317 23:51:15.663553    1191 pod_workers.go:1609] "Pod has been terminated and is no longer known to the kubelet, remove all history" podUID=45f2f5c9d4e1aaa82bf8d63ce6d263f3
```

**Comment by bobbypage** [comment]
Based on the above, it looks like this case is expected, in that case, maybe the simplest option is to simply drop the `Programmer error` log statement since by design we only want to into account a subset of the states for the metrics?
