### ISSUE TITLE
Sandboxes creation fails with "Unexpected resolver config value" if resolverConfig != "Host" - Windows

### ISSUE THREAD

**Issue by ibabou** [kubernetes/kubernetes#116782]
### What happened?

When a --resolv-conf (DNS resolver config) is passed to kubelet on a Windows node, the config content is used as part of sandbox initialization (through getHostDNSConfig()). Now with the recent changes ([here](https://github.com/kubernetes/kubernetes/commit/f335812719cfa5d5fb235320fb63af3669ffdcb1)), it seems now to fail with an error like:

`
E0315 10:22:16.244956    4764 pod_workers.go:1256] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8_img-puller-3842(5abbdf2b-b40a-459d-9033-4fec6efe9aba)\" with CreatePodSandboxError: \"Failed to generate sandbox config for pod \\\"img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8_img-puller-3842(5abbdf2b-b40a-459d-9033-4fec6efe9aba)\\\": Unexpected resolver config value: \\\"C:\\\\etc\\\\kubernetes\\\\cni\\\\hostdns.conf\\\". Expected \\\"\\\" or \\\"Host\\\".\"" pod="img-puller-3842/img-pull-registry.k8s.io-e2e-test-images-httpd-2.4.38-4-kkkt8" podUID=5abbdf2b-b40a-459d-9033-4fec6efe9aba
`

This is showing on all the runs of GCE testgrid (latest): [here](https://testgrid.k8s.io/sig-windows-gce#gce-windows-2019-containerd-master&show-stale-tests=)

### What did you expect to happen?

Reading/using the passed resolv config on Windows

### How can we reproduce it (as minimally and precisely as possible)?

Run a Windows pool with DNS resolv config being set as part of kubelet params.

### Kubernetes version

1.27 alpha.3 1.27 beta.0 master

### Cloud provider

<details>
GCE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/priority criticial-urgent

as this is likely a release blocking

**Comment by claudiubelu** [comment]
Hmm, so you're setting the ``--resolv-conf`` kubelet flag to ``C:\etc\kubernetes\cni\hostdns.conf`` flag, consuming that file. Right now, we're expecting that flag to be either an empty string ``""`` or ``Host``, and kubeadm also sets that flag to ``""`` [1].

This PR https://github.com/kubernetes/kubernetes/pull/110566 introduced the capability to read the DNS config options from the Windows host registries while removing the capability to read from a file, introducing a regression. I've sent a PR addressing this issue: https://github.com/kubernetes/kubernetes/pull/116800

[1] https://github.com/kubernetes/kubernetes/blob/c9ff2866682432075da1a961bc5c3f681b34c8ea/cmd/kubeadm/app/componentconfigs/kubelet_windows.go#L73

**Comment by jsturtevant** [comment]
Was the file `C:\etc\kubernetes\cni\hostdns.conf` changing the behavior of the node?

**Comment by ibabou** [comment]
Yeah, what used on GCE/GKE, seems to be a Linux-like conf, eg:

`
> cat C:\etc\kubernetes\cni\hostdns.conf
nameserver 10.128.0.1
search c.<project_name>.internal google.internal
`

We haven't tried to remove from kubelet to see the behavior.

**Comment by cici37** [comment]
This Issue/PR has been marked as release blocker. Please have the fix merged by eod today otherwise the feature has to be reverted. For the Issue/PR owner: please have a revert/feature disable PR open today in case the fix failed to get in. Thank you! See the [announcement here](https://groups.google.com/a/kubernetes.io/g/dev/c/yzSvdfk8mo8)

-- Kubernetes 1.27 release manager

**Comment by marosset** [comment]
@cici37 I opened up a revert PR in case this PR does not merge by code freeze.

**Comment by ibabou** [comment]
Thanks @claudiubelu/@marosset for the resolution! both 2019 and 2022 grids seems to be back to green now!

**Comment by marosset** [comment]
> Thanks @claudiubelu/@marosset for the resolution! both 2019 and 2022 grids seems to be back to green now!

Thanks for confirming!

I opened https://github.com/kubernetes/website/issues/40228 to ensure k8s.io gets updated too
