### ISSUE TITLE
Unable to build local cluster

### ISSUE THREAD

**Issue by MrZLeo** [kubernetes/kubernetes#116716]
### What happened?

I want to build 1.26 Kubernetes in my fedora linux, but get this error:

```
$ sudo -E ./hack/local-up-cluster.sh
make: Entering directory '/home/fedora/go/src/k8s.io/kubernetes'
go version go1.19.7 linux/amd64
+++ [0314 09:56:23] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubectl (static)
    k8s.io/kubernetes/cmd/kube-apiserver (static)
    k8s.io/kubernetes/cmd/kube-controller-manager (static)
    k8s.io/kubernetes/cmd/cloud-controller-manager (non-static)
    k8s.io/kubernetes/cmd/kubelet (non-static)
    k8s.io/kubernetes/cmd/kube-proxy (static)
    k8s.io/kubernetes/cmd/kube-scheduler (static)
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
	Use -buildvcs=false to disable VCS stamping.
!!! [0314 09:56:25] Call tree:
!!! [0314 09:56:25]  1: /home/fedora/go/src/k8s.io/kubernetes/hack/lib/golang.sh:758 kube::golang::build_some_binaries(...)
!!! [0314 09:56:25]  2: /home/fedora/go/src/k8s.io/kubernetes/hack/lib/golang.sh:928 kube::golang::build_binaries_for_platform(...)
!!! [0314 09:56:25]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0314 09:56:25] Call tree:
!!! [0314 09:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0314 09:56:25] Call tree:
!!! [0314 09:56:25]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [Makefile:92: all] Error 1
make: Leaving directory '/home/fedora/go/src/k8s.io/kubernetes'
```

### What did you expect to happen?

build successfully

### How can we reproduce it (as minimally and precisely as possible)?

Just follow the [build step](https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md).

### Kubernetes version

<details>
Kubernetes version: 1.26
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME=Fedora
VERSION="34 (Cloud Edition)"
ID=fedora
VERSION_ID=34
VERSION_CODENAME=""
PLATFORM_ID="platform:f34"
PRETTY_NAME="Fedora 34 (Cloud Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:34"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f34/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=34
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=34
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Cloud Edition"
VARIANT_ID=cloud
$ uname -a
Linux ip-172-31-29-108.ec2.internal 5.17.12-100.fc34.x86_64 #1 SMP PREEMPT Mon May 30 17:47:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-o 1.26
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
/sig contributor-experience
I guess

**Comment by sftim** [comment]
Does https://www.kubernetes.dev/docs/onboarding/05-development/ help?

**Comment by BenTheElder** [comment]
This isn't local-up-cluster specific, looks like go <> git is broken here?

How did you setup the clone of the repo? https://github.com/kubernetes/community/pull/7194 may be related

**Comment by MrZLeo** [comment]
> This isn't local-up-cluster specific, looks like go <> git is broken here?
> 
> How did you setup the clone of the repo? [kubernetes/community#7194](https://github.com/kubernetes/community/pull/7194) may be related

Yes, I think so. But I actually pull all code into local. If I compile it with `make` in normal user, everything works, once I use `sudo`, it fail. In order to avoid environment problem, I use `sudo -E`, but it didn't work.

**Comment by MrZLeo** [comment]
> Does https://www.kubernetes.dev/docs/onboarding/05-development/ help?

I don't think so :(

**Comment by ruquanzhao** [comment]
I also encountered this problem.
In my case, the reason is that owner of `.git` is different from the current user.

Related golang issues: https://github.com/golang/go/issues/53532

**Comment by BenTheElder** [comment]
Yes, that would do it. See also https://git-scm.com/docs/git-config/2.35.2

**Comment by MrZLeo** [comment]
It solved my problem! Thanks very much :)

**Comment by MikeSpreitzer** [comment]
Does every contributor now have to get this error and search the issues to find this resolution?  Couldn't we make this easier on contributors?
