### ISSUE TITLE
Scheduler: Make sure handlers have synced before scheduling

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#116717]
### What would you like to be added?

Make sure handlers have finished syncing before the scheduling cycles start.

Ref: https://github.com/kubernetes/kubernetes/issues/113763#issuecomment-1472858978

/sig scheduling
/good-first-issue

### Why is this needed?

In a highly used cluster, we don't want to start scheduling pods before all the pods have been loaded into the scheduler cache, or we could end up in a bad state.

**Comment by alculquicondor** [comment]
Note that we are in code-freeze, but I'm leaving this issue open before I forget :)

**Comment by charles-chenzz** [comment]
> Note that we are in code-freeze, but I'm leaving this issue open before I forget :)

could you provide more detail about how to solve this issue? cause I want to know whether I could take this issue

**Comment by alculquicondor** [comment]
There is a sample in https://github.com/kubernetes/kubernetes/issues/113763#issuecomment-1472858978

Here's where the scheduler waits for the cache in the informer (client) to sync https://github.com/kubernetes/kubernetes/blob/8b2dae57d4169e7801c870aa86f5644085518c57/cmd/kube-scheduler/app/server.go#L205

We need to also wait for the event handlers to finish processing.

**Comment by charles-chenzz** [comment]
> There is a sample in [#113763 (comment)](https://github.com/kubernetes/kubernetes/issues/113763#issuecomment-1472858978)
> 
> Here's where the scheduler waits for the cache in the informer (client) to sync
> 
> https://github.com/kubernetes/kubernetes/blob/8b2dae57d4169e7801c870aa86f5644085518c57/cmd/kube-scheduler/app/server.go#L205
> 
> We need to also wait for the event handlers to finish processing.

thanks for the tips, I will check [#113763 (comment)](https://github.com/kubernetes/kubernetes/issues/113763#issuecomment-1472858978) to see if I can take it

**Comment by charles-chenzz** [comment]
I check the code and issues but still have some detail question: 
[kubernetes/cmd/kube-scheduler/app/server.go](https://github.com/kubernetes/kubernetes/blob/8b2dae57d4169e7801c870aa86f5644085518c57/cmd/kube-scheduler/app/server.go#L205)
 cc.InformerFactory.WaitForCacheSync(ctx.Done())
 
we should handle it on the inside of WaitForCacheSync() and wrap it like the sample on [#113763 (comment)](https://github.com/kubernetes/kubernetes/issues/113763#issuecomment-1472858978)

[kubernetes/staging/src/k8s.io/client-go/tools/cache/share_informer.go]
```
func (s *sharedIndexInformer) HasSynced() bool {
	s.startedLock.Lock()
	defer s.startedLock.Unlock()

	if s.controller == nil {
		return false
	}
	return s.controller.HasSynced()
}

but maybe I get it wrong, can you give me some help if I take this issues? I think it will be a challenge for me and I will learn a from by solving this issue.

**Comment by czybjtu** [comment]
I'd like to work on it if you haven't started. @charles-chenzz

**Comment by charles-chenzz** [comment]
I took a look at it last night and don't have a very clear mind on how to work it out. If you have idea and like to work on it just take it. @czybjtu

**Comment by charles-chenzz** [comment]
I think the HasSynced here is cache, this issues need to make sure we wait for the event handlers to finish synced

**Comment by kidddddddddddddddddddddd** [comment]
I think it's to make sure every `ResourceEventHandler` is synced after we `AddEventHandler` for the scheduler.
/assign
