### ISSUE TITLE
pod describes events Message more detail

### ISSUE THREAD

**Issue by zyy4676** [kubernetes/kubernetes#116713]
### What would you like to be added?

**I hope  able to add command arguments to give the list of nodes that do not meet the tag/memory /CPU.**

--------------------------------------------------------------------------------------------------
  Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  7m51s  default-scheduler  0/20 nodes are available: 13 node(s) didn't match Pod's node affinity, 7 Insufficient memory.
  Warning  FailedScheduling  7m51s  default-scheduler  0/20 nodes are available: 13 node(s) didn't match Pod's node affinity, 7 Insufficient memory. 

### Why is this needed?

This message "0/20 nodes are available: 13 node(s) didn't match Pod's node affinity, 7 Insufficient memory. "  I know matter in memory or lable，but I don‘t konw  node list, I don't know which node need to process。SO If  give a list of labels that don't fit I'll adjust the labels （also add command parameters for more details）

**Comment by sftim** [comment]
Perhaps one day a kubectl plugin - even a third party plugin - could help users understand why a Pod can't be scheduled?

This might need help from the scheduler, though.

**Comment by pacoxu** [comment]
/sig scheduling
Actually, you can configure a lower log level of kube scheduler to see all scores and information from scheduler log.
- there are some discussions in https://github.com/kubernetes/kubernetes/issues/101820#issuecomment-865332878

**Comment by alculquicondor** [comment]
We can't put all detail in the Event message. They have a size limit.

Best you can do is look at logs or work on metrics improvements such as #110643

/close
