### ISSUE TITLE
 creating a cluster with aws ec2 instances . while connecting worker node to master node getting an error.

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#116740]
### What happened?

worker node is not being able to connect to the master node 
...............................................................................................................................................................................................................

[root@worker ~]# kubeadm join 172.31.28.51:6443 --token bhdi0o.gd8qkwlpsxx7wqdr         --discovery-token-ca-cert-hash sha256:7c0fbf2b913d1392c82274adb2cdd0d874df2f6bd77d1cd067c322da042a333e
[preflight] Running pre-flight checks
	[WARNING FileExisting-tc]: tc not found in system path
	[WARNING Hostname]: hostname "worker" could not be reached
	[WARNING Hostname]: hostname "worker": lookup worker on 172.31.0.2:53: no such host
**error execution phase preflight: couldn't validate the identity of the API Server: Get "https://172.31.28.51:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s": dial tcp 172.31.28.51:6443: connect: connection refused
To see the stack trace of this error execute with --v=5 or higher**

### What did you expect to happen?

Connecting worker node with master node.

### How can we reproduce it (as minimally and precisely as possible)?

Checking with the error message.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details> 

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by charles-chenzz** [comment]
/sig node

did you set up this host? ``[WARNING Hostname]: hostname "worker": lookup worker on 172.31.0.2:53: no such host``

**Comment by neolit123** [comment]
please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

try asking on slack in #kubeadm or #kubernetes-users.

/close
/kind support
