### ISSUE TITLE
[Flaky] autoscaling-vpa-full: OOMing pods under VPA have memory requests growing with OOMs

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#116787]
### Failure cluster [c13cec55d92289cb04ba](https://go.k8s.io/triage#c13cec55d92289cb04ba)
https://testgrid.k8s.io/sig-autoscaling-vpa#autoscaling-vpa-full

Top flake for this grid
1.  OOMing pods under VPA have memory requests growing with OOMs
2. Pods under VPA have cpu requests growing with usage 
##### Error text:
```
Mar 20 06:16:25.274: Unexpected error:
    <*errors.StatusError | 0xc0006ecc80>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "the server could not find the requested resource (post verticalpodautoscalers.autoscaling.k8s.io)",
            Reason: "NotFound",
            Details: {
                Name: "",
                Group: "autoscaling.k8s.io",
                Kind: "verticalpodautoscalers",
                UID: "",
                Causes: [
                    {
                        Type: "UnexpectedServerResponse",
                        Message: "404 page not found",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    the server could not find the requested resource (post verticalpodautoscalers.autoscaling.k8s.io)
occurred
/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/e2e/v1/full_vpa.go:285
command-line-arguments.glob..func10.1()
	/go/src/k8s.io/autoscaler/vertical-pod-autoscaler/e2e/v1/full_vpa.go:285 +0x3c3
There were additional failures detected after the initial failure:
[PANICKED]
Test Panicked
In [DeferCleanup (Each)] at: /usr/local/go/src/runtime/panic.go:260

runtime error: inval
```
#### Recent failures:
[2023/3/21 04:02:10 ci-kubernetes-e2e-autoscaling-vpa-full](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1637907362197016576)
[2023/3/20 15:57:53 ci-kubernetes-e2e-autoscaling-vpa-admission-controller](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-admission-controller/1637725109512835072)
[2023/3/20 13:57:53 ci-kubernetes-e2e-autoscaling-vpa-full](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-full/1637694910364651520)
[2023/3/14 20:22:09 ci-kubernetes-e2e-autoscaling-vpa-actuation](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-autoscaling-vpa-actuation/1635617286226186240)

/kind flake

/sig autoscaling
/cc @vinaykul

**Comment by pbetkier** [comment]
This test is no longer flaky, right?

**Comment by pacoxu** [comment]
> This test is no longer flaky, right?

Sorry for the late reply. Yes. not flake from 07-09 to now.
/close
