### ISSUE TITLE
Trying to create an object that already exists can fail with non "AlreadyExists" errors (e.g. validation)

### ISSUE THREAD

**Issue by wujunwei** [kubernetes/kubernetes#116747]
### What happened?

When I cerate a service which already exist,I got 422 and error message `The Service "my-service" is invalid: spec.ports[0].nodePort: Invalid value: 30123: provided port is already allocated`.

### What did you expect to happen?

I hope to get HTTP code 409 which means resource is already existed.

### How can we reproduce it (as minimally and precisely as possible)?

Supose we have a yaml as follows:
```yaml
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30123

```

execute :
```
kubectl create -f  service.yaml -v9
```

execute again :
```
kubectl create -f  service.yaml -v9
```

we can get result 
```json
{
"kind":"Status",
"apiVersion":"v1",
"status":"Failure",
"message":"Service \"my-service\" is invalid:spec.ports[0].nodePort: Invalid value: 30123: provided port is already allocated",
"reason":"Invalid",
"details":{
  "name":"myservice",
  "kind":"Service",
  "causes":
     [
       {
         "reason":"FieldValueInvalid",
         "message":"Invalid value: 30123: provided port is already allocated","field":"spec.ports[0].nodePort" 
       }
      ]
  },
"code":422
}
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDat
e:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDat
e:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/assign @thockin @khenidak 
/sig network

Let's see the different operations and its results 
- `kubectl create -f  service.yaml -v9` you do a POST -- returns 422
- `kubectl apply -f  service.yaml -v9` you do a PATCH -- returns 200 OK
- `kubectl replace -f  service.yaml -v9` you do a PUT -- returns 200 OK

```
[6.5.8](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.8).  409 Conflict

   The 409 (Conflict) status code indicates that the request could not
   be completed due to a conflict with the current state of the target
   resource.  This code is used in situations where the user might be
   able to resolve the conflict and resubmit the request.  The server
   SHOULD generate a payload that includes enough information for a user
   to recognize the source of the conflict.

   Conflicts are most likely to occur in response to a PUT request.  For
   example, if versioning were being used and the representation being
   PUT included changes to a resource that conflict with those made by
   an earlier (third-party) request, the origin server might use a 409
   response to indicate that it can't complete the request.  In this
   case, the response representation would likely contain information
   useful for merging the differences based on the revision history.
```

you are trying to recreate the resources, not to update it, update works ok.
I feel that this status code is correct, but my knowledge in this area is limited

/cc @liggitt @thockin @khenidak

**Comment by wujunwei** [comment]
@aojea   But if I change `nodePort: 30123` to another port, it will return 409 as expected.  obviously，it verify whether it is legal before verifying whether it exists.

**Comment by wujunwei** [comment]
What really matters is that reason is `FieldValueInvalid` not `AlreadyExists`, Is this intentional?

**Comment by wujunwei** [comment]
Some  clients like [fabric8io/kubernetes-client](https://github.com/fabric8io/kubernetes-client)  will offer function like createOrReplace which will call create (post)first ,then judge whether the HTTP code  equal 409 (HTTP_CONFLICT), if so call replace(put). Like codes below
https://github.com/fabric8io/kubernetes-client/blob/43531077d3d67d3b4fd300e2e4e0b0e4b231229c/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/internal/CreateOrReplaceHelper.java#L42-L66

It  will go wrong In the above scenario,because the apiserver return `422`.

**Comment by lavalamp** [comment]
Actually creating an object has to be a last step, and that's the only point at which we find out if the name is reserved. If something turns up wrong before we get to that step, we can't even attempt to store the object to find that it already exists.

You might think that we could just check if the object exists to begin with, but the case above is still possible in a race.

For better behavior, use SSA -- it probably will do what you were hoping for.

**Comment by wujunwei** [comment]
> For better behavior, use SSA -- it probably will do what you were hoping for.
Could you please give me an example about how to implement this function (judge whether it existed, then create or update) by SSA(server-side-apply?).

**Comment by wujunwei** [comment]
> For better behavior, use SSA -- it probably will do what you were hoping for.

Yes，server-side-apply can satisfy my needs.

**Comment by cici37** [comment]
/triage accepted
/close
Please feel free to reopen it if needed.
