### ISSUE TITLE
E2eNode Suite.[It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#116872]
### Which jobs are failing?

E2eNode Suite.[It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
 
https://testgrid.k8s.io/sig-node-release-blocking#node-kubelet-serial-containerd&width=20 

Perma failure here:
E2eNode Suite.[It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully
https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio 

### Which tests are failing?

E2eNode Suite.[It] [sig-node] MirrorPodWithGracePeriod when create a mirror pod and the container runtime is temporarily down during pod termination [NodeConformance] [Serial] [Disruptive] the mirror pod should terminate successfully

### Since when has it been failing?

Since it was created at https://github.com/kubernetes/kubernetes/pull/113145/ 

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio 

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/cc @saschagrunert 
/cc @haircommander 

is there anything specific to CRI-O that will make test fail

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

seeing this in the wild

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv1 
failed for this in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-kubelet-serial-crio-cgroupv1/1664285557024362496 as well

**Comment by saschagrunert** [comment]
Having a fix in mind in https://github.com/kubernetes/kubernetes/pull/119197
