### ISSUE TITLE
helm upgrade causing downtime (Manifest yaml)

### ISSUE THREAD

**Issue by HenriqueG123** [kubernetes/kubernetes#116859]
### What happened?

I have a project with 300 pods, however when upgrading using helm it deletes all pods not respecting the rollingupdate defined in deployment.yml

### What did you expect to happen?

Project update respected the rollingupdate not causing downtime

### How can we reproduce it (as minimally and precisely as possible)?

I have a template and use the command helm upgrade -i APP_NAME ./template

### Kubernetes version

<details>
Kubernetes V 1.21
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HenriqueG123** [comment]
helm upgrade -i $APP_NAME --set-string timestamp=$timestamp ./template/ --kubeconfig=./template/config-cluster

NAME: myapp
LAST DEPLOYED: Fri Mar 17 6:40:45 2023
NAMESPACE: default
STATUS: deployed
REVISION: 10
TEST SUITE: None

300 pods are deleted and 300 are created simultaneously, with that we have a downtime

My template
strategy:
rollingUpdate:
maxSurge: 20%
maxUnavailable: 10%
type: RollingUpdate

Is there any way to do the helm upgrade without deleting everything at once?

Output of helm version:
version.BuildInfo{Version:"v3.11.2", GitCommit:"912ebc1cd10d38d340f048efaf0abda047c3468e", GitTreeState:"clean", GoVersion:"go1.18.10"}

**Comment by pacoxu** [comment]
I am afraid that https://github.com/helm/helm/issues/ may be the right place to open this issue.

**Comment by pacoxu** [comment]
/kind support

/remove-kind bug

To investigate further, you can enable debug-level logging for Helm or other components to identify the issue. Based on the current information provided, it is unclear whether this is a bug in Kubernetes.

**Comment by Noksa** [comment]
Check this https://github.com/helm/helm/issues/11917#issuecomment-1483918853

**Comment by HenriqueG123** [comment]
@Noksa, I don't even know how to thank such wisdom, perfect identification and solving the problem, immense gratitude.
