### ISSUE TITLE
support PreBind for scheduling extender

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#116888]
### What would you like to be added?

Add PreBind and Unreserve verbs to scheduling extender.  The logics of Bind operation could be moved to the Prebind method of extenders. If there are any problem during the prebind/bind stages, the Unreserve method of successful extenders will be called.

### Why is this needed?

For now, only one scheduling extender could enable bindVerb and perform binding operations. However, we have multiple extenders which all need to do something, such as updating annotations, just before binding in the bind method.

For example, ExtenderFoo is for extended resource exmaple.com/foo, and ExtenderBar for example.com/bar.

1. For pods requesting no exmaple.com/foo neither exmaple.com/bar, none of ExtenderFoo/ExtenderBar will be called.
2. For pods requesting exmaple.com/foo or exmaple.com/bar, ExtenderFoo or ExtenderBar will be called.
3. BUT if ExtenderFoo and ExtenderBar both needs some operation during Binding, it's NOT possible now， because configuring multiple Bind hooks for extenders is not possible
4. Furthermore, in our cluster, there are some pods requesting both exmaple.com/foo and exmaple.com/bar.

One possible solution is to rewrite our extenders with scheduling framework. But this needs lots of effort. And some customers use their own schedulers and their schedulers can integrate with our extenders easily, and no need to share the code with them.

**Comment by alculquicondor** [comment]
For your particular use case, I believe this works, and it's probably better, as it provides atomicity:

You can setup a mutating webhook for the `pods/binding` resource. The webhook can maintain a pod lister to obtain the pod resources. Then, it can add the annotations to the Binding resource.

The API server is already capable of copying annotations from the Binding resource into the Pod https://github.com/kubernetes/kubernetes/blob/d2be69ac11346d2a0fab8c3c168c4255db99c56f/pkg/registry/core/pod/storage/storage.go#L202-L205

**Comment by borgerli** [comment]
@alculquicondor  Thanks for suggestions. A question is that how our extender could told the annotations to the webhook. These annoations are related to some decision (about custom resource) made by extenders, and  not known until target node is selected before binding.

Regarding performance, extenders are a accepable choise for us, which have been working well in our prodcution clusters, even large one with more than 2000 nodes. 

Scheduling extenders are really flexible and easy to use, and used in our clusters in large scales. Migrating these extenders to scheduing framework is not feasible in short time.

I totally agree that compared with scheduling framekwork, there are many drawbacks with extenders. For new requirements on scheduling, scheduling framework should be the choise. But IMHO, scheduling extenders still have its value, and it would be better to make it an option, than just deprecate it, especially there are so many legacies.

**Comment by kerthcet** [comment]
> Scheduling extenders are really flexible and easy to use, and used in our clusters in large scales. Migrating these extenders to scheduing framework is not feasible in short time.

If the community would like to deprecate the extender, it will go through several releases for buffering.

From a high level perspective, I think we need some alternatives before removing the Extender, scheduling framework is something we encouraged, but not all, same to @borgerli we also have similar problems when collaborating with our customers, who have their own plugins. We need a mechanism like go plugins, wasm support etc., no need to build the scheduler from source code, but can be embedded easily.

**Comment by alculquicondor** [comment]
> A question is that how our extender could told the annotations to the webhook. These annoations are related to some decision (about custom resource) made by extenders, and not known until target node is selected before binding.

Since the webhook would be for the pods/binding subresource, you would receive a [Binding object](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/binding-v1/) that has the pod and node name. You can inject the annotations in the Binding object itself and the API server would copy them into the Pod. IIUC, this is exactly what you want.

> Regarding performance, extenders are a accepable choise for us, which have been working well in our prodcution clusters, even large one with more than 2000 nodes.

Then a webhook should work equally fine for you.

**Comment by borgerli** [comment]
> > A question is that how our extender could told the annotations to the webhook. These annoations are related to some decision (about custom resource) made by extenders, and not known until target node is selected before binding.
> 
> Since the webhook would be for the pods/binding subresource, you would receive a [Binding object](https://kubernetes.io/docs/reference/kubernetes-api/cluster-resources/binding-v1/) that has the pod and node name. You can inject the annotations in the Binding object itself and the API server would copy them into the Pod. IIUC, this is exactly what you want.
> 

Except the Bind method of an extender, is there any other point in extender which can receive a Binding object? Please note, I can not use Bind in my extender, as stated at beginning.

**Comment by alculquicondor** [comment]
Note that I'm not talking about scheduler extenders, I'm talking about regular admission webhooks https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/

You can add as many admission webhooks for the pods/binding subresource as you want.
