### ISSUE TITLE
`imagePullPolicy: Always` may pull stale image based off stale image digest resolution

### ISSUE THREAD

**Issue by ericdriggs** [kubernetes/kubernetes#116867]
### What happened?

I'm running api test jobs using a cron trigger, which requires use of a fixed tag, e.g. master/main/latest

When running tests which have been recently modified, frequently a stale image is run, which may be several hours old. 

I've ruled out the local docker registry since the contents for the tag and latest sha match exactly.

Issue seems related to this behavior:
`Every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image digest. If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved digest, and uses that image to launch the container.`
https://v1-22.docs.kubernetes.io/docs/concepts/containers/images/#image-pull-policy

Although the container image registry can resolve a name to an image digest, that image digest is no longer the latest version. Essentially there's caching which can't be overriden, making cron triggers unreliable for mutable image tags.

Preferred behavior would be either 
1. a new ImagePullPolicy, e.g. `AlwaysNoCache` which will always resolve latest image digest 
OR
2. update behavior for `Always` to never use cached image digest and just rely on cached digest for `IfNotPresent`

see also:
https://stackoverflow.com/questions/71769218/kubernetes-imagepullpolicyalways-behavior-change

### What did you expect to happen?

Latest image for tag in image repository to be pulled

### How can we reproduce it (as minimally and precisely as possible)?

Create image using mutable tag, e.g. latest which prints creation timestamp/sha
Create job which reference image using latest tag
run job in cron trigger
update tag for image
run job.
see stale version run

### Kubernetes version

1.22

### Cloud provider

AWS

**Comment by BenTheElder** [comment]
> Every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image digest.

This part of the described documented behavior means resolving the name:tag => digest.
If the tag is updated it points to a new digest and querying this is what's described here.

> If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved digest, and uses that image to launch the container.

So it would be a bug to not follow the `:latest` tag

The same docs page for 1.22 later notes:

> To make sure the Pod always uses the same version of a container image, you can specify the image's digest; replace <image-name>:<tag> with <image-name>@<digest> (for example, image@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2).

Which would avoid any re-resolution of the image reference to a digest.

The only part that should be cached here is the downloading of content that is identified by hash.

It's possible there's a bug in resolving the image reference to digest but:


1. Kubernetes 1.22 is not supported anymore (https://kubernetes.io/releases/); Are you able to reproduce on a currently supported version?
2. For anyone triaging issues in SIG Node currently to potentially respond to this, it would be helpful to know more about the broken environment and how to reproduce.



/sig node

**Comment by smarterclayton** [comment]
Any chance the registry couldn’t be accessed? 

The cache should be preventing failures to restart the pod when the registry is down, but the behavior described sounds like a bug given historical behavior.

**Comment by ericdriggs** [comment]
I'm using :master tag (equivalent to :latest) with pull policy Always.
The docker registry is accessible and I verified that it's immediately up to date after I update the tag.

**Comment by smarterclayton** [comment]
Ok, so with “:master” and pullPolicy Always on 1.22 and an available registry you see the digest be “out of date”.  Definitely not expected, is there anything in the kubelet or container runtime log showing that :master was read and *not* resolved to the latest?

**Comment by ericdriggs** [comment]
@smarterclayton 
Let me work with devops internally to try to answer that.

**Comment by BenTheElder** [comment]
> The cache behavior for “:latest” (with any policy except “Always”) is special and should be preventing failures to restart the pod when the registry is down, but the behavior described sounds like a bug given historical behavior (and note: it’s been a while since i touched this code so it may have changed since then).

I'm pretty sure we just default the imagePullPolicy to Always if the tag is :latest and no policy is specified. It's a bit unusual in our APIs IMHO but been a while since I've looked as well

**Comment by pacoxu** [comment]
There is a similar feature request in https://github.com/kubernetes/kubernetes/issues/111822.

**Comment by sftim** [comment]
How much of this behavior is delegated to / the responsibility of the container runtime?

**Comment by sftim** [comment]
For tidiness
/retitle `imagePullPolicy: Always` may pull stale image based off stale image digest resolution

**Comment by SergeyKanzhelev** [comment]
/remove-kind bug
/kind feature

/cc @xmcqueen 

Does this have the same behavior with Container d or CRI-O? Dockershim and 1.22 are out of support

**Comment by pacoxu** [comment]
> Ok, so with “:master” and pullPolicy Always on 1.22 and an available registry you see the digest be “out of date”. Definitely not expected, is there anything in the kubelet or container runtime log showing that :master was read and _not_ resolved to the latest?

@ericdriggs any update for Clayton's questions?

**Comment by ericdriggs** [comment]
@pacoxu @smarterclayton 

I'm seeing stale tag resolution for both:
* spinnaker pipeline cron trigger
* k8 cron job using master tag

With devops help, I've implemented a workaround for this cron use case in spinnaker, where the webhook tag parameter is being baked into the k8 cron job so that I can rely on deterministic sha tags.

The new workflow is git commit -> webhook with sha/tag parameter-> bake/deploy cron with parameter sha/tag -> cron schedule using baked sha/tag

Not sure precisely how I can use kubectl to determine which image sha is being resolved. Happy to try it out if you can help me with the commands.

**Comment by mmiranda96** [comment]
@ericdriggs could you confirm the following?
- Latest Kubernetes version used to test
- Container runtime (CRI-O, containerd, etc.) and version

As mentioned in previous comments, 1.22 is out of support, I recommend to test with something newer like 1.25 or newer.

/triage needs-information

**Comment by ericdriggs** [comment]
@mmiranda96 
I've escalated to devops to see if there's a schedule for upgrading our kubernetes version.

Below is the output for kubectl version. Let me know if there are other commands which would be useful to provide additional version info.

% kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.3",
    "gitCommit": "9e644106593f3f4aa98f8a84b23db5fa378900bd",
    "gitTreeState": "clean",
    "buildDate": "2023-03-15T13:33:11Z",
    "goVersion": "go1.19.7",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "22+",
    "gitVersion": "v1.22.17-eks-48e63af",
    "gitCommit": "47b89ea2caa1f7958bc6539d6865820c86b4bf60",
    "gitTreeState": "clean",
    "buildDate": "2023-01-24T09:34:06Z",
    "goVersion": "go1.16.15",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

**Comment by georgejdli** [comment]
I'm seeing the same stale image digest resolution issue on AKS 

```
root@aks-agentpool-<id>:/# containerd -v
containerd github.com/containerd/containerd 1.7.1+azure-1 1677a17964311325ed1c31e2c0a3589ce6d5c30d
```

k8s deployment
```
imagePullPolicy: Always
```

kubectl version --output=json
```
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.1",
    "gitCommit": "4c9411232e10168d7b050c49a1b59f6df9d7ea4b",
    "gitTreeState": "clean",
    "buildDate": "2023-04-14T13:14:41Z",
    "goVersion": "go1.20.3",
    "compiler": "gc",
    "platform": "darwin/arm64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.3",
    "gitCommit": "f18584a06fc476806da2e340e2eed960659871e8",
    "gitTreeState": "clean",
    "buildDate": "2023-06-12T18:45:20Z",
    "goVersion": "go1.19.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

In my case I'm using ACR to import a docker image hosted on docker.io. 
One particular tag seems to have been updated to a new digest in the ACR but kubernetes tries to pull the image with the old digest and fails (no longer exists in my ACR).

ACR Tag resolution:
[6.2.6-v6] -> sha256:aee203bcb37066d362f53b886e4044a23ff3ae2811f34eae9cc0963b6eea37a6

AKS stale Tag resolution:
[6.2.6-v6] -> sha256:580cd2320a9b7c4e9ed9147620f7070370ad2cc53a6f26199142b06ac3acde28

And I end up getting an image pull error because the stale digest no longer exists in my ACR:
```
sha256:580cd2320a9b7c4e9ed9147620f7070370ad2cc53a6f26199142b06ac3acde28 not found: not found
```

**Comment by SergeyKanzhelev** [comment]
Please also check if there are any mirrors configured that might have cached a previous version of an image

**Comment by prapanw** [comment]
Facing the same issue on K8s version 1.28.3 with containerd runtime.

Container fails to create. The error points to the digest SHA that no longer exists in the ACR account. Is there a way to remove the cached image on kubernetes?

**Comment by bqbn** [comment]
We're running Kubernetes v1.26.13-gke.1144000, and we're experiencing the same issue.

In our case, the tag is called `prototype`, and the `imagePullPolicy` is set to `Always`. However, the pod doesn't always pull the latest digest of the tag. After a release, we often see a bunch of new pods running images with two different digests: the latest and the second to the lastest. We use [Docker Hub](https://hub.docker.com/) as our registry.

**Comment by AnishShah** [comment]
/remove-kind bug
/kind documentation

There are many situations that can be true. We should add a troubleshooting docs to help customers debug why image digest resolution failed.

**Comment by ericdriggs** [comment]
/add-kind bug

This is a bug. imagePullPolicy Always should not return images which are many hours stale.

**Comment by ericdriggs** [comment]
@AnishShah 
This is a bug, not a documentation issue
imagePullPolicy Always should not return images which are many hours stale.
image digest resolution is not failing -- it is suffering from read skew / stale cache.
No way exists currently in k8 to reliably read the current version of a mutable image.

**Comment by SergeyKanzhelev** [comment]
> @AnishShah This is a bug, not a documentation issue imagePullPolicy Always should not return images which are many hours stale. image digest resolution is not failing -- it is suffering from read skew / stale cache. No way exists currently in k8 to reliably read the current version of a mutable image.

The reason to mark it as a documentation issue is that in most cases, the root cause for this behavior is not the kubelet. It either a runtime issue, a mirror, or registry problem. If registry was not avaialble, container runtime may fallback to the previous latest tag. If mirror lagging behind, there is no mechanism from container runtime to get the latest from the real registry.

If you see a specific bug in kubelet that needs to be fixed, please provide more details on steps to repro and logs.

**Comment by buddhamangler-cbre** [comment]
> > @AnishShah This is a bug, not a documentation issue imagePullPolicy Always should not return images which are many hours stale. image digest resolution is not failing -- it is suffering from read skew / stale cache. No way exists currently in k8 to reliably read the current version of a mutable image.
> 
> The reason to mark it as a documentation issue is that in most cases, the root cause for this behavior is not the kubelet. It either a runtime issue, a mirror, or registry problem. If registry was not avaialble, container runtime may fallback to the previous latest tag. If mirror lagging behind, there is no mechanism from container runtime to get the latest from the real registry.
> 
> If you see a specific bug in kubelet that needs to be fixed, please provide more details on steps to repro and logs.

Is this the desired behavior though? I get the need to document the CURRENT behavior, what is in question here is what SHOULD the behavior be or what options SHOULD be available to control this.  We often pin to a static tag, not necessarily 'latest', sometimes a major tag such as 'v1'. If we update this tag in our docker repo, and kube cannot reach the registry I think it's a fair point to bring up that blindly using the cached image MIGHT not be the desired behavior.

Do you agree?

**Comment by SergeyKanzhelev** [comment]
> @SergeyKanzhelev Stale images are served regardless if the registry is available or not. This is a caching expiration design issue, not a registry availability issue.

@ericdriggs can you clarify your situation? As you know cache invalidation is the hardest Computer Science problem.

Is it cache invalidation on container runtime (what are you using?), on mirror that you set up? Or you believe it is on kubelet? I don't think kubelet has any logic around caching labels this is why I am saying it is likely a documentation issue for kubernetes

**Comment by bqbn** [comment]
In our experience, the Docker Hub registry has consistently been online and available whenever we do releases. However, we almost always find ourselves with a bunch of new pods running the latest two digests of the same tag. We happen to have another environment where the tag we deploy is called `master-xxxxx`, where `xxxxx` is the digest of the image. In this environment, we never encounter the same issue as in the environment where we deploy the static tag called `prototype`.

The description of the `Always` policy currently says [1](https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy),

> every time the kubelet launches a container, ... ... 
> **otherwise, the kubelet pulls the image with the resolved digest**, and uses that image to launch the container.

However, the reality is that in one environment, kubelets on some instances were able to resolve the tag to the latest digest, while kubelets on other instances weren't. At the same time,  in the environment where `master-xxxxx` tags are deployed, all kubelets are able to resolve the tag to the latest digest **every time**.

The two environments mentioned above are deployed onto the GKE platform and onto the same Kubernetes cluster (different namespaces), and they use `Containerd` as the container runtime.

I suppose one could still argue that this kind of inconsistent behavior of kubelet is not a bug but due to other factors. However, I think from most users' perspective, `Always` means **always** pulling the latest digest of a tag. The kubelet, on the other hand, as the controller and invoker of the container runtime, should deliver that image despite whether the runtime does caching or not.

**Comment by ericdriggs** [comment]
@SergeyKanzhelev 

> If you see a specific bug in kubelet that needs to be fixed, please provide more details on steps to repro and logs.

Initial post documented how to reproduce. Repro is very consistent.

`How can we reproduce it (as minimally and precisely as possible)?
Create image using mutable tag, e.g. latest which prints creation timestamp/sha
Create job which reference image using latest tag
run job in cron trigger
update tag for image
run job.
see stale version run`

> Is it cache invalidation on container runtime (what are you using?), on mirror that you set up? Or you believe it is on kubelet? I don't think kubelet has any logic around caching labels this is why I am saying it is likely a documentation issue for kubernetes

The caching bug is described in the documentation.

`Always
every time the kubelet launches a container, the kubelet queries the container image registry to resolve the name to an image [digest](https://docs.docker.com/engine/reference/commandline/pull/#pull-an-image-by-digest-immutable-identifier). If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image; otherwise, the kubelet pulls the image with the resolved digest, and uses that image to launch the container.`

https://kubernetes.io/docs/concepts/containers/images/#image-pull-policy

**If the kubelet has a container image with that exact digest cached locally, the kubelet uses its cached image.**

No way exists to force that update.

**Comment by SergeyKanzhelev** [comment]
@ericdriggs this is another inconsistency in the documentation. If you look at code, this will always return true for `Always` images:

https://github.com/kubernetes/kubernetes/blob/bb838fde5bb9df4becb9fd267c84759be9f5400f/pkg/kubelet/images/image_manager.go#L139

And then it will go to the actual call to the container runtime almost unconditionally:

https://github.com/kubernetes/kubernetes/blob/bb838fde5bb9df4becb9fd267c84759be9f5400f/pkg/kubelet/images/image_manager.go#L160

As I said it may be the container runtime behavior issue. And this is why I am asking for more details on the repro. Either logs from container runtime or registry telemetry, anything that will tell which layer has failed to refresh the cache would help.

**Comment by ericdriggs** [comment]
@SergeyKanzhelev 
We use a corporate instance of artifactory for our docker images. 
When the image is published, it tags <branch> and <branch>-<sha>
Immediately after the mutable tag has been updated, browsing artifactory, I can see <branch> and <branch>-<sha> tags share identical timestamps. 
Similarly when I run docker pull locally using the mutable tag immediately after publish, I can verify it pulls the latest image, since the sha is baked into the image.
However, when I run using k8/spinnaker, the stale image is pulled if we've run the pipeline recently.

**Comment by haircommander** [comment]
> The reason to mark it as a documentation issue is that in most cases, the root cause for this behavior is not the kubelet. It either a runtime issue, a mirror, or registry problem. If registry was not avaialble, container runtime may fallback to the previous latest tag. If mirror lagging behind, there is no mechanism from container runtime to get the latest from the real registry.

This is a good point and I think continues to be relevant here. From what I can tell, the kubelet is correctly telling the runtime to pull always. If you believe there are cases where the runtime is incorrectly falling back to a cached image, then that's a bug in the runtime. If there are cases where the registry doesn't update a cached image, then that's a registry bug. The kubelet does no digest resolution and shouldn't be involved here (past asking the runtime to get the latest).
