### ISSUE TITLE
Relicaset is still running, even after deployment is deleted

### ISSUE THREAD

**Issue by Ishujeet** [kubernetes/kubernetes#116804]
### What happened?

Replicaset is not getting deleted, even after deployment is deleted from cluster.

### What did you expect to happen?

Replicaset should be deleted after deployment deletion.

### How can we reproduce it (as minimally and precisely as possible)?

Unable to reproduce.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"57fbbcc2804848b95cad5519f5ec9d6355430db9", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:38Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Azure Kubernetes Service
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sushant-kapoor17** [comment]
Hello @Ishujeet , 

To begin with, I would like to request you to please either downgrade your `kubectl client version` to stay closer to the `server version(v1.24.9)` or please look to upgrade the kubernetes cluster version closer to v1.26(not sure how feasible it is for you to upgrade the cluster version). My guess is the former option is the quickest in your case. 
There have been significant changes in v1.25 and v1.26 and as per recommendation client/server should at most be +/-1 version apart, which is unfortunately not the case in your setup.

Additionally, this looks like an issue with something that went wrong within your cluster. To understand, what went wrong, I would like to request you to look at the kubelet and kube-controller-manager logs in your cluster and notice any errors which occured during this particular timestamp. Here's a link on how to get [kubelet logs](https://learn.microsoft.com/en-us/azure/aks/kubelet-logs) in AKS.

It would be great, if you can post what commands were executed , which led to this behavior. And, if possible, once kubectl client version is +/-1 with the server version, can you please confirm here, if this behavior still persists.

Thanks

**Comment by benzaidfoued** [comment]
Hey @Ishujeet ,

Could you please share more details regarding that replicaSet and the deployment method that you are using ( helmchart, GitOps...ext ), and will be very helpful if you can attach kubelet and api logs .

Thanks .

**Comment by Ishujeet** [comment]
Hi @benzaidfoued 
We found the issue it is due to some crds in our cluster which has `conversion` in their definition which is causing the issue.

**Comment by benzaidfoued** [comment]
Okay, Thanks
