### ISSUE TITLE
[InPlacePodVerticalScaling] ResizePolicy field is not being validated

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#116854]
### What happened?

https://github.com/kubernetes/kubernetes/pull/102884#discussion_r1144672887

The newly added field `ResizePolicy` field is not being validated.

@vinaykul @liggitt 

### What did you expect to happen?

`ResizePolicy` field should be validated.

### How can we reproduce it (as minimally and precisely as possible)?

We can create a pod with invalid `ResizePolicy` to reproduce this.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
I'll try this for v1.27 if you don't mind.

**Comment by vinaykul** [comment]
Nice catch! Sorry my bad, this probably got Please review fix: https://github.com/kubernetes/kubernetes/pull/116857

This likely got dropped either during port-over of the [original PR](https://github.com/kubernetes/kubernetes/pull/92127/files#diff-c713e8919642d873fdf48fe8fb6d43e5cb2f53fd601066ff53580ea655948f0dR2797) or during bad rebase. I should not have left the [resize policy e2e tests for beta](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#beta). 

Gotta run to get my kid prepped, dr. appt and then school drop. So I'll try and add an E2E test for this later today. please hold for e2e test (but we should fix this in 1.27)

**Comment by vinaykul** [comment]
@gjkim42 I realized you were working on a fix as well only after I sent my fix out and was catching up on emails at doc office (rushed morning). I didn't mean to step over your effort to fix it, sorry about that.

**Comment by gjkim42** [comment]
I am completely fine with that. Thanks for the fix :)
