### ISSUE TITLE
The test is not starting: https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu 

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#116873]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu not even starting

### Which tests are failing?

Seems like test configuration issue

### Since when has it been failing?

Unknown

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
I've found several errors that seems to indicate the job is not well configured

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1638836808764624896/artifacts/bootstrap-e2e-master/kube-master-installation.log
```
23T09:39:54.551529449Z","bootstrap_status":{"step_name":"LoadDockerImages","status":"STARTED","status_reason":"","latency":null}}
Mar 23 09:39:54.553267 bootstrap-e2e-master configure.sh[1042]: Start loading kube-system docker images
Mar 23 09:39:54.553370 bootstrap-e2e-master configure.sh[1042]: Try to load docker image file /home/kubernetes/kube-docker-files/kube-apiserver.tar
Mar 23 09:39:54.942341 bootstrap-e2e-master configure.sh[1042]: timeout: failed to run command ‘/home/containerd/usr/local/bin/ctr’: No such file or directory
Mar 23 09:39:59.946169 bootstrap-e2e-master configure.sh[1042]: timeout: failed to run command ‘/home/containerd/usr/local/bin/ctr’: No such file or directory
Mar 23 09:40:04.949339 bootstrap-e2e-master configure.sh[1042]: timeout: failed to run command ‘/home/containerd/usr/local/bin/ctr’: No such file or directory
Mar 23 09:40:09.952613 bootstrap-e2e-master configure.sh[1042]: timeout: failed to run command ‘/home/containerd/usr/local/bin/ctr’: No such file or directory
Mar 23 09:40:14.955912 bootstrap-e2e-master configure.sh[1042]: timeout: failed to run command ‘/home/containerd/usr/local/bin/ctr’: No such file or directory
Mar 23 09:40:14.956407 bootstrap-e2e-master configure.sh[1042]: Fail to load docker image file /home/kubernetes/kube-docker-files/kube-apiserver.tar using /home/containerd/usr/local/bin/ctr -n=k8s.io images import after 5 retries. Exit!!
Mar 23 09:40:14.961330 bootstrap-e2e-master configure.sh[1042]: [cloud.kubernetes.monitoring.proto.SerialportLog] {"cluster_hash":"get-metadata-value-error","vm_instance_name":"bootstrap-e2e-master","boot_id":"58756f83b4724e5c98405a70eb48dd9b","timestamp":"2023-03-23T09:40:14.957766570Z","bootstrap_status":{"step_name":"LoadDockerImages","status":"ERROR","status_reason":"encountered non-zero exit code","latency":"20.4062s"}}
Mar 23 09:40:14.961782 bootstrap-e2e-master systemd[1]: kube-master-installation.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 09:40:14.961882 bootstrap-e2e-master systemd[1]: kube-master-installation.service: Failed with result 'exit-code'.
Mar 23 09:40:14.962356 bootstrap-e2e-master systemd[1]: Failed to start Download and install k8s binaries and configurations.
```
 
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1638836808764624896/artifacts/bootstrap-e2e-master/kube-master-configuration.log

```
-- Logs begin at Thu 2023-03-23 09:39:16 UTC, end at Thu 2023-03-23 09:45:38 UTC. --
Mar 23 09:40:14.963636 bootstrap-e2e-master systemd[1]: Starting Configure kubernetes master...
Mar 23 09:40:14.967216 bootstrap-e2e-master chmod[1209]: chmod: cannot access '/home/kubernetes/bin/configure-helper.sh': No such file or directory
Mar 23 09:40:14.967587 bootstrap-e2e-master systemd[1]: kube-master-configuration.service: Control process exited, code=exited status=1
Mar 23 09:40:14.967662 bootstrap-e2e-master systemd[1]: kube-master-configuration.service: Failed with result 'exit-code'.
Mar 23 09:40:14.968087 bootstrap-e2e-master systemd[1]: Failed to start Configure kubernetes master.
Mar 23 09:40:14.968267 bootstrap-e2e-master systemd[1]: kube-master-configuration.service: Consumed 1ms CPU time
```

**Comment by akhilerm** [comment]
There is failure in the containerd installation also
```
Mar 24 04:48:16.209019 bootstrap-e2e-master configure.sh[1009]: + '[' x86_64 == aarch64 ']'
Mar 24 04:48:16.209506 bootstrap-e2e-master configure.sh[1009]: ++ set +x
Mar 24 04:48:16.209612 bootstrap-e2e-master configure.sh[1009]: /home/containerd/configure.sh: line 148: HEADERS[@]: unbound variable
Mar 24 04:48:16.209860 bootstrap-e2e-master configure.sh[1009]: + version=
Mar 24 04:48:16.210240 bootstrap-e2e-master systemd[1]: containerd-installation.service: Main process exited, code=exited, status=1/FAILURE
Mar 24 04:48:16.210331 bootstrap-e2e-master systemd[1]: containerd-installation.service: Failed with result 'exit-code'.
Mar 24 04:48:16.210868 bootstrap-e2e-master systemd[1]: Failed to start Download and install containerd binaries and configurations..
Mar 24 04:48:16.211068 bootstrap-e2e-master systemd[1]: containerd-installation.service: Consumed 210ms CPU time
```

Ref: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1639125967169392640/artifacts/bootstrap-e2e-master/containerd-installation.log

**Comment by akhilerm** [comment]
Debugged the issue.  Cause: The master node on the cluster for ubuntu tests is using `cos-85-13310-1308-1` image which ships with an older version of bash (4.3), which does not support variable expansion of array for an unbound variable (this feature is present in later versions of bash). Because of this, the `HEADERS` array variable is giving an error.  

@SergeyKanzhelev Do we have plans to update the cos-85 to a later version for the tests. Also since its the master node, I am not sure if there are any tests we run on the master, since the tests is specifically for testing containerd on ubuntu.

**Comment by akhilerm** [comment]
`cos-93` has bash version 4.4; from this version onwards we should not face [the issue](https://git.savannah.gnu.org/cgit/bash.git/tree/CHANGES?id=3ba697465bc74fab513a26dea700cc82e9f4724e#n878).

**Comment by dims** [comment]
@akhilerm go ahead and bump the image for this test to newer cos:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/containerd.yaml#L137

Use the ones from here:
https://cs.k8s.io/?q=cos-97&i=nope&files=&excludeFiles=&repos=kubernetes/kubernetes

**Comment by dims** [comment]
Also add some defensive code for bash version check in another PR please, so that we fail early.

**Comment by akhilerm** [comment]
@dims, I had bumped the version in https://github.com/kubernetes/test-infra/pull/29146 to cos93. 

I am not sure if we should bump to cos97 as there have been some cgroupv1/v2 changes that went into cos97. Ref : [sig-node](https://kubernetes.slack.com/archives/C0BP8PW9G/p1668564175297989?thread_ts=1668511893.118389&cid=C0BP8PW9G) slack message

Also, about adding the code to fail fast, do you mean to add it in the [containerd-installation](https://github.com/containerd/containerd/blob/main/contrib/gce/configure.sh#L147) script or in the test-infra job yaml

**Comment by aojea** [comment]
/reopen

let's wait until it runs and we have confirmation

**Comment by dims** [comment]
green now!

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/23304/227817557-341f776c-f828-44fe-93f8-a99154741fff.png">


/close
