### ISSUE TITLE
Deployment rolling update stucked with pod anti-affinity

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#116891]
### What happened?

Use case: only have 3 nodes available in cluster, a deployment with pod anti-affinity yaml like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

After applied, the pods running ok.
But if the image changed to `nginx:1.8.1`, then apply again, the newly created pod will be pending, with event like this:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  25m   default-scheduler  0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules.
  Warning  FailedScheduling  23m   default-scheduler  0/3 nodes are available: 3 node(s) didn't match pod affinity/anti-affinity, 3 node(s) didn't satisfy existing pods anti-affinity rules.
```

### What did you expect to happen?

Expect to roll update deployment pods to desired state without stuck (pending).

### How can we reproduce it (as minimally and precisely as possible)?

See description above.

### Anything else we need to know?

Tested other workloads statefulset and daemonset, they both work ok in this senario.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.30", GitCommit:"6dae75a9b67fe05b7e32a3fab18ac09724074f9b", GitTreeState:"clean", BuildDate:"2022-10-08T04:01:30Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

**Comment by aojea** [comment]
/sig scheduling
/sig apps

don't know who handles this, seems like a deadlock situation but I don't know if is expected

**Comment by kidddddddddddddddddddddd** [comment]
Thanks @sushant-kapoor17 for you detailed explanation!!!
We got a same issue about this a few days ago #116827, seems like many users are having trouble with this lol 😂

**Comment by astraw99** [comment]
@sushant-kapoor17 Thanks for your solution, it did solve the issue.
The default value for `maxSurge` and `maxUnavailable` are both 25%, so lead to this issue.
