### ISSUE TITLE
In HPA behaviours is mandatory to scale down the pods in kubernetes

### ISSUE THREAD

**Issue by gudipudipradeep** [kubernetes/kubernetes#116882]
### What happened?

As per my knowledge kubernetes automatically scale down or scale up the pods based on hpa conifguration metrics like cpu and memory utilization percentage

### What did you expect to happen?

As per my knowledge kubernetes automatically scale down or scale up the pods based on hpa conifguration metrics like cpu and memory utilization percentage.
behaviours is feature to customized the scale up or down the behavior based on the needs other wise kubernetes default will take care.

### How can we reproduce it (as minimally and precisely as possible)?

HPA configuration without behaviours property

### Kubernetes version

<details>

```console
1.25
```

</details>

### Cloud provider

<details>
Unable to scale down the pods. Is behaviours is mandatory for HPA configuration to scale down..? AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pbetkier** [comment]
Behavior section of HPA object configuration may be defined to tune the scale down and scale up behavior, e.g. don't scale down faster than 50% per minute. If not defined the default behaviors are used as described in https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/;#default-behavior.

/close
