### ISSUE TITLE
Why only partial compilation succeeded

### ISSUE THREAD

**Issue by opencmit2** [kubernetes/kubernetes#116962]
### Which jobs are failing?

"When I compile apiserver.go and kubelet for kubernetes-1.26 using Go1.19, I report an error. I can successfully compile kubelctl, kubeadm, and kube-proxy. However, errors may occur when compiling kubelet or kube-apiserver.Why is it only partially successful?"? The screenshot is as follows:
![image](https://user-images.githubusercontent.com/112474703/228240672-b0839a31-73eb-40a5-82e8-f872678d17c5.png)

### Which tests are failing?

kubelet or kube-apiserver

### Since when has it been failing?

Always failed

### Relevant SIG(s)

/sig

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/volume/util/hostutil/hostutil_windows.go#L34-L37

https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/volume/util/hostutil/hostutil_windows.go#L96

I cannot repro it on Mac with `GOOS=windows GOARCH=amd64 go build ./kubelet.go`.

Can you provide the whole `hostutil_windows.go` file here?  Have you changed anything on the release-1.26 branch?

BTW, for error messages, using `>` or ``` code block would be better than a screenshot.

**Comment by opencmit2** [comment]
> https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/volume/util/hostutil/hostutil_windows.go#L34-L37
> 
> https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/volume/util/hostutil/hostutil_windows.go#L96
> 
> I cannot repro it on Mac with `GOOS=windows GOARCH=amd64 go build ./kubelet.go`.
> 
> Can you provide the whole `hostutil_windows.go` file here? Have you changed anything on the release-1.26 branch?
> 
> BTW, for error messages, using `>` or ``` code block would be better than a screenshot.


![image](https://user-images.githubusercontent.com/112474703/228598925-8e04e74e-402f-4083-81d8-9d13e361b541.png)


![image](https://user-images.githubusercontent.com/112474703/228598776-30da8ae4-1aa6-48f9-b66f-f5785a4b5ef7.png)
