### ISSUE TITLE
[Failing test] verify-master

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#116951]
### Which jobs are failing?

master-blocking

- verify-master

### Which tests are failing?

- verify-vendor
![Screenshot from 2023-03-27 22-08-51](https://user-images.githubusercontent.com/73488906/228007368-2a90a376-4f5f-4851-b5da-4f5ff7cd655d.png)

### Since when has it been failing?

2023-03-27 02:51 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#verify-master

### Reason for failure (if possible)

```
hack/update-vendor.sh
go version go1.20.2 linux/amd64
All pinned versions of checked dependencies match their preferred version.
Removing /home/prow/go/src/k8s.io/kubernetes/_tmp/kube-vendor.DK6Qay
+++ exit code: 1
+++ error: 1
[0;31mFAILED   verify-vendor.sh	80s
Verifying verify-yamlfmt.sh
+++ Running case: verify.yamlfmt 
+++ working dir: /home/prow/go/src/k8s.io/kubernetes
+++ command: bash "hack/make-rules/../../hack/verify-yamlfmt.sh"
```

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by dims** [comment]
Fix is in https://github.com/kubernetes/kubernetes/pull/116948

**Comment by mehabhalodiya** [comment]
The fix hit our dashboard, thanks all for your heads up!

/close
