### ISSUE TITLE
[Flaking Test] ci-kubernetes-unit-eks-canary/TestLazyThroughput on EKS build cluster

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#116990]
### Which jobs are flaking?

Unit tests on the new EKS-based Prow build cluster are flaking. The job in question is `ci-kubernetes-unit-eks-canary`:

* https://prow.k8s.io/?job=ci-kubernetes-unit-eks-canary
* https://testgrid.k8s.io/sig-k8s-infra-canaries#ci-kubernetes-unit-eks-canary
* https://github.com/kubernetes/test-infra/blob/63c2b9eccf413b9227a85e0448cc59e714bec1d8/config/jobs/kubernetes/sig-k8s-infra/periodics.yaml#L31-L66

### Which tests are flaking?

The test that flakes is `k8s.io/kubernetes/vendor/k8s.io/client-go/tools/cache/synctrack.TestLazyThroughput`. There are other tests that flake, but those are rare, and this concrete one (`TestLazyThroughput`) is the most common case why this job flakes.

### Since when has it been flaking?

N/A - we observed this flake since we started running test on EKS-based build cluster.

### Testgrid link

https://testgrid.k8s.io/sig-k8s-infra-canaries#ci-kubernetes-unit-eks-canary

### Anything else we need to know?

This is a new EKS-based cluster that we want to migrate some tests to: https://github.com/kubernetes/k8s.io/tree/main/infra/aws/terraform/prow-build-cluster

The cluster currently has 20 nodes based on `r5d.4xlarge` instances. Those instances have 16 vCPUs and 128 GB RAM which should more than enough. At the time this test runs, it's usually the only test on the node that's running. Resource consumption on the node is pretty low, for example:

```
NAME                                         CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
ip-10-1-183-69.us-east-2.compute.internal    959m         6%     1462Mi          1%
```

There's a lot more of details in the following Slack thread: https://kubernetes.slack.com/archives/CCK68P2Q2/p1680095193152329

### Relevant SIG(s)

/sig k8s-infra
/sig apimachinery

**Comment by lavalamp** [comment]
Test: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/cache/synctrack/lazy_test.go#L62

This test has a 3x safety margin built in, I couldn't make it bigger or it would fail to catch actual regressions.

The test essentially sleeps for 11ms 100 times and fails if that takes longer than 3s. I was unable to make it fail with stress / race when I wrote it (and this was on a VM) -- my first thought is there must be something wrong with the environment beyond just busy-ness.

**Comment by dims** [comment]
slack thread: 
https://kubernetes.slack.com/archives/CCK68P2Q2/p1680105394881219?thread_ts=1680095193.152329&cid=CCK68P2Q2

Interesting observation from @tzneal - `GOMAXPROCS isn’t cgroups aware, there’s an existing issue on the Go rep`:
https://github.com/golang/go/issues/33803

**Comment by dims** [comment]
xref: https://github.com/kubernetes/test-infra/pull/29181

**Comment by tzneal** [comment]
It appears that GOMAXPROCS was the issue, I created https://github.com/kubernetes/test-infra/issues/29183 to look at detecting the correct value from `make test`.  Good to close this issue as resolved?

**Comment by dims** [comment]
/close

@tzneal i am gonna move that back here to k/k repo. i have an idea.
