### ISSUE TITLE
sig-node-containerd#image-validation-cos-e2e is failing

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/kubernetes#116944]
### Which jobs are failing?

Jobs in https://testgrid.k8s.io/sig-node-containerd#image-validation-cos-e2e are failing continuously since a long time

### Which tests are failing?

The `kubetest.Up` row is in failing. The 5 node cluster that is needed for test is not coming into Ready state.

### Since when has it been failing?

Not sure, testgrid does not show any recent passing for these tests.

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#image-validation-cos-e2e

### Reason for failure (if possible)

When inspected the [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-cos-containerd-e2e-cos-gce/1640269880894689280/artifacts/bootstrap-e2e-minion-group-jm70/kube-container-runtime-monitor.log) found that the test uses cos89 image which has containerd 1.4 which does not support CRI API v1. 

### Anything else we need to know?

Upgrading to a later version of cos should ideally solve the issue. cos97 would work, but that would need corresponding changes in the node-args and kubelet flags as systemd cgroup driver also will have to be enabled. 

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
@mmiranda96 let's make this one green first and then have a test matrix to understand whether we need it at all.

**Comment by mmiranda96** [comment]
Reopening since we need to update cgroups driver.
/reopen

**Comment by akhilerm** [comment]
@mmiranda96 I can take up the cgroup driver updates.

**Comment by akhilerm** [comment]
/close 

As tests already has the cgroup driver updated as per https://github.com/kubernetes/test-infra/pull/29199#issuecomment-1507796208
