### ISSUE TITLE
Use gomega Eventually in scheduler integration tests 

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#116956]
### What would you like to be added?

gomega Eventually should be used in waiting for conditions both in integration tests or e2e tests. Something like `gomega.NewGomegaWithT(b).Eventually(...).Should(gomega.BeEmpty())`. 

Tracked the suggestion here https://github.com/kubernetes/kubernetes/pull/116634#discussion_r1150141099

/sig testing
/sig scheduling

### Why is this needed?

Clearer logging for debugging.

**Comment by AxeZhan** [comment]
I can help with this one. After #116634 got merged?

**Comment by kerthcet** [comment]
Plz go ahead.

**Comment by kerthcet** [comment]
Is this still valid because I say you reverted the replacement in https://github.com/kubernetes/kubernetes/pull/118202 @pohly

**Comment by pohly** [comment]
/close

I still think `gomega.Eventually` is better, but the arguments in favor of it don't seem to be enough to overcome the inertia ("we are not using gomega in integration tests, let's not start using it").
