### ISSUE TITLE
Investigating detecting GOMAXPROCS based on cgroup values

### ISSUE THREAD

**Issue by tzneal** [kubernetes/kubernetes#116997]
**What would you like to be added**:

`make test` should detect the appropriate GOMAXPROCS based off of the cpu limit supplied to the pod.  

**Why is this needed**:

If not, test failures can occur (e.g. https://github.com/kubernetes/kubernetes/issues/116990) where GOMAXPROCS defaults to the number of cpus on the machine, while the cpu limit is actually far less.  Too many compile/test processes launch, and any timing tests can become flaky. The end result is that running the test jobs on a node with more CPUs can make it flaky when running the test on a node with fewer CPUs cleanly passes.

It's possible to set GOMAXPROCS=cpu limits in test jobs to avoid this, but it would be nicer if `make test` would autodiscover and set GOMAXPROCS appropriately.

**Comment by howardjohn** [comment]
This is already done, which is great, but for some more info I did some benchmarking of setting GOMAXPROCs vs not: https://blog.howardjohn.info/posts/go-build-times/#scaling-cpu

Pretty substantially better in some cases
