### ISSUE TITLE
HPA to support AND operation

### ISSUE THREAD

**Issue by kevinteng525** [kubernetes/kubernetes#116908]
Currently, HPA only supports metrics with an OR relationship, meaning that if any one metric exceeds the threshold, scaling up will occur. Scaling down will only occur if all metrics are below the threshold. 

## Support request
I have a requirement where I only want to scale up if both TPS and CPU exceed the threshold. 
Since if only the CPU exceeds the threshold, it may be due to a memory leak, and scaling up will not help to solve the underlying issue. Also if only TPS exceeds the threshold, it means current replicas are able to serve the increased traffic and no need to scale up either.

So would like to ask if anyone has a similar requirement and how you have addressed it. I have tried using PromQL with ‘and’ operators, such as `avg(cpuUsage{_namespace_="perfmon", pool="r1obfsvc"}) > 27 and avg(tps{_namespace_="perfmon", pool="r1obfsvc"}) > 80`. However, the problem with this approach is that when both the CPU and TPS are below threshold, 27 and 80, the query will not return any data, making it impossible for the HPA to carry out a scale down operation.

**Comment by pbetkier** [comment]
It's the first time I see this requirement, we would probably need more traction to extend the API for OR/AND setting.

In the meantime, have you tried https://www.google.com/search?q=prometheus+zero+if+no+data? I'm not a strong Prometheus but this looks promising as a mitigation for you.
