### ISSUE TITLE
[Flaky] TestMetadataSharedInformerFactory

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#117013]
### Which jobs are flaking?

pull-kubernetes-unit

### Which tests are flaking?

`k8s.io/kubernetes/vendor/k8s.io/client-go/metadata/metadatainformer TestMetadataSharedInformerFactory`

### Since when has it been flaking?

March 21st

### Reason for failure (if possible)

```
{Failed  === RUN   TestMetadataSharedInformerFactory/scenario_1:_test_if_adding_an_object_triggers_AddFunc
W0330 02:01:54.153738   77084 mutation_detector.go:53] Mutation detector is enabled, this will result in memory leakage.
I0330 02:01:54.154432   77084 reflector.go:287] Starting reflector *v1.PartialObjectMetadata (0s) from k8s.io/client-go/metadata/metadatainformer/informer.go:106
I0330 02:01:54.154533   77084 reflector.go:323] Listing and watching *v1.PartialObjectMetadata from k8s.io/client-go/metadata/metadatainformer/informer.go:106
I0330 02:01:54.155280   77084 shared_informer.go:341] caches populated
    informer_test.go:153: tested informer haven't received an object, waited 3s
I0330 02:01:57.154364   77084 watch.go:183] Stopping fake watcher.
I0330 02:01:57.154467   77084 reflector.go:293] Stopping reflector *v1.PartialObjectMetadata (0s) from k8s.io/client-go/metadata/metadatainformer/informer.go:106
    --- FAIL: TestMetadataSharedInformerFactory/scenario_1:_test_if_adding_an_object_triggers_AddFunc (3.00s)
}
```

### Relevant SIG(s)

/sig cli

**Comment by alculquicondor** [comment]
@KnVerey @soltysh

**Comment by KnVerey** [comment]
/sig api-machinery
Since this is in client-go

**Comment by alculquicondor** [comment]
escalating as we are approaching the release @fedebongio

**Comment by apelisse** [comment]
Can't seem to reproduce it here:
```
> go test -count=500 -run=TestMetadataSharedInformerFactory/scenario_1 ./vendor/k8s.io/client-go/metadata/metadatainformer
ok  	k8s.io/client-go/metadata/metadatainformer	51.194s
```

**Comment by lavalamp** [comment]
turn on -race and use stress?

I don't think we changed anything with this code recently, so I'm not optimistic

**Comment by alculquicondor** [comment]
https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestMetadataSharedInformerFactory&job=pull-kubernetes-unit

**Comment by lavalamp** [comment]
Are all the failures on the pulls and not on main? Because the first failure I glanced at came from here and there's pretty obvious and non concerning thing changing: https://github.com/kubernetes/kubernetes/pull/117066/files#diff-41a847f1f10358c7a09d3fcb1e4a6b94ef57d43cca668bc1373196df1579c754 Also many other tests failed too

**Comment by alculquicondor** [comment]
It seems that in CI it only failed once https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestMetadataSharedInformerFactory&job=ci-kubernetes-unit

**Comment by apelisse** [comment]
I'm running:
```
go test -race -count=5000 -run=TestMetadataSharedInformerFactory/scenario_1 ./vendor/k8s.io/client-go/metadata/metadatainformer
```
in 14 windows at the same time, we'll see if 5 minutes. If it still fails, I should maybe run more tests, maybe another test is messing up that test.

**Comment by apelisse** [comment]
It passed, that's 70000 passes without a fail :-). I'm now trying to run all the tests in that binary.

**Comment by apelisse** [comment]
Ran the whole binary 7000 times, never failed...

**Comment by aojea** [comment]
the graph show this is no longer a problem

https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=pull-kubernetes-unit&test=TestMetadataSharedInformerFactory

/close
