### ISSUE TITLE
In-tree vSphere volumes are not detached after KCM restart

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#117091]
### What happened?

I am enabling CSI migration on a vSphere cluster. A node was fully drained, all its Pods are deleted, but just before KCM detaches in-tree vSphere volume volumes from it, KCM restarts. A new KCM starts, sees attached volumes in `node.status.volumesAttached` that are not needed by any Pod on the node and calls vSphere in-tree volume plugin `Detach()`.

The in-tree vSphere volume plugin + cloud provider marks the volume as detached right away, without reaching to vCenter API. The volume remains attached forever.

I don't think it's related to CSI migration, IMO a regular node drain + KCM restart at the same time can cause the same issue.

KCM logs:

```
I0404 14:58:42.423920       1 operation_generator.go:1637] Verified volume is safe to detach for volume "nil" (UniqueName: "kubernetes.io/vsphere-volume/[WorkloadDatastore] 8b577f5f-ea23-1e5e-bac9-0693938623e5/_029e/_0040/7f718f6c06a84cff86e254dfcd150be1.vmdk") on node "jsafrane-rdpmz-worker-ps6qk" 
I0404 14:58:42.423986       1 nodemanager.go:359] No VM found for node "jsafrane-rdpmz-worker-ps6qk". Initiating rediscovery.
E0404 14:58:42.434007       1 nodemanager.go:362] Error "No VM found" node info for node "jsafrane-rdpmz-worker-ps6qk" not found
I0404 14:58:42.434051       1 nodemanager.go:395] node info for node "jsafrane-rdpmz-worker-ps6qk" not found
E0404 14:58:42.434074       1 vsphere.go:651] Cannot find node "jsafrane-rdpmz-worker-ps6qk" in cache. Node not found!!!
E0404 14:58:42.434101       1 attacher.go:287] Error checking if volume ("[WorkloadDatastore] 8b577f5f-ea23-1e5e-bac9-0693938623e5/_029e/_0040/7f718f6c06a84cff86e254dfcd150be1.vmdk") is already attached to current node ("jsafrane-rdpmz-worker-ps6qk"). Will continue and try detach anyway. err=No VM found
I0404 14:58:42.434114       1 nodemanager.go:359] No VM found for node "jsafrane-rdpmz-worker-ps6qk". Initiating rediscovery.
E0404 14:58:42.434127       1 nodemanager.go:362] Error "No VM found" node info for node "jsafrane-rdpmz-worker-ps6qk" not found
I0404 14:58:42.434130       1 nodemanager.go:395] node info for node "jsafrane-rdpmz-worker-ps6qk" not found
E0404 14:58:42.434133       1 vsphere.go:651] Cannot find node "jsafrane-rdpmz-worker-ps6qk" in cache. Node not found!!!
I0404 14:58:42.434138       1 vsphere.go:1020] Node "jsafrane-rdpmz-worker-ps6qk" does not exist, disk [WorkloadDatastore] 8b577f5f-ea23-1e5e-bac9-0693938623e5/_029e/_0040/7f718f6c06a84cff86e254dfcd150be1.vmdk is already detached from node.
I0404 14:58:42.434160       1 operation_generator.go:513] DetachVolume.Detach succeeded for volume "nil" (UniqueName: "kubernetes.io/vsphere-volume/[WorkloadDatastore] 8b577f5f-ea23-1e5e-bac9-0693938623e5/_029e/_0040/7f718f6c06a84cff86e254dfcd150be1.vmdk") on node "jsafrane-rdpmz-worker-ps6qk" 
```

The in-tree cloud provider has a [node informer](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/legacy-cloud-providers/vsphere/vsphere.go#L1547) and [maintains a list of nodes](https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/staging/src/k8s.io/legacy-cloud-providers/vsphere/nodemanager.go#L290) from it. It apparently has not processed all nodes at the time A/D controller tries to detach the node.

### What did you expect to happen?

The in-tree vSphere volume plugin + cloud provider detaches the volume in vCenter.

### How can we reproduce it (as minimally and precisely as possible)?

That's really tricky, it's very hard / impossible to reproduce on a real cluster. I had to inject errors to Detach() in-tree volume call, so they fail until KCM is restarted. Newly started KCM would detach the volume just fine (no error would be injected there), but marks the volume as detached right away.

### Anything else we need to know?

For the record (and search-ability), the CSI driver that tries to attach the volume to another node complains either:

```
Warning  FailedAttachVolume  26m (x10 over 31m)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-24d840d4-89eb-4619-945d-fce26be85015" : rpc error: code = Internal desc = failed to set keepAfterDeleteVm control flag for VolumeID "76f9905e-22ff-443d-bf8e-1af270ab5b46"
```

Or:

```
LocalizedMessage: (string) (len=32) \"The resource 'volume' is in use.\"\n})\n". opId: "1bb54dd7"
```

cc @xing-yang @jingxu97 @msau42 @gnufied @divyenpatel

It could be somewhat related to https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/2165, however, not all cases of https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/2165 can be related to KCM restart. As I mentioned above, it's very hard/impossible to synchronize KCM restart with draining a node in a real cluster.

### Kubernetes version

<details>

```console
$ kubectl version
v1.25.0-2788+f8ead88c8cbfa0-dirty
```

</details>

### Cloud provider

<details>
vSphere 7.0.3
</details>

### OS version

<details>

```console
Red Hat Enterprise Linux CoreOS 412.86.202303312131-0 (Ootpa)
```

</details>

### Install tools

<details>
OpenShift
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsafrane** [comment]
Tried just moving a Pod between nodes + restarting KCM when the volume is still attached to the old node. In-tree volume plugin on the new node says:

```
  Warning  FailedAttachVolume  66s (x3 over 67s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-24d840d4-89eb-4619-945d-fce26be85015" : No VM found
  Warning  FailedAttachVolume  8s (x2 over 38s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-24d840d4-89eb-4619-945d-fce26be85015" : Failed to add disk scsi0:1.
```

**Comment by xing-yang** [comment]
What CSI driver version and K8s version are you testing with?

**Comment by jsafrane** [comment]
Kubernetes is 1.25 and CSI driver is 2.7, still, I think it's not releated to the CSI driver, it's KCM who marks the in-tree volume as detached due to not populated node cache.

**Comment by jsafrane** [comment]
I found an easier way how to reproduce this without extra code in KCM:

1. Run a StatefulSet with 1 Pod that uses 1 PVC.
2. Cordon the node where the Pod runs.
3. Scale down kube-controller-manager to zero (not really possible for me) *or* kill all kube-controller-manager Pods. This will cause new KCM processes to wait for leader election. In my env. this gives me ~30 seconds for the next step.
4.  Delete the Pod. A new one will be scheduled on a different node (because the current node is cordoned) + there is no KCM running at this time that would detach the volume from the old node.
5. New KCM wins its leader election, sees a volume attached to a node where it is not needed -> it calls `Detach()` of the volume plugin. VSphere cloud provider does not have its caches populated yet (= this bug) -> the volume is not detached, but `Detach()` returns success.

**Comment by jsafrane** [comment]
@gnufied, dangling attach does not help here. The volume is still attached to the old node even after ~10 minutes.

`AttachVolume.Attach` fails with `Failed to add disk scsi0:1` and not with `DanglingAttachError`.
