### ISSUE TITLE
Remove SeccompProfilePath

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#117045]
Look for "// TODO: Deprecated, remove after we switch to Seccomp field". Fix it. See https://github.com/kubernetes/kubernetes/pull/115898 as example.

/cc @saschagrunert 

/help
/good-first-issue
/sig node

add @saschagrunert as a reviewer when sending a PR.

(issue is a follow up from https://github.com/kubernetes/kubernetes/pull/117020/files#r1154025906)

**Comment by charles-chenzz** [comment]
I will start to look at it and fix part of them

/assign

**Comment by vamshi1188** [comment]
// Set Seccomp.
synthesized.Seccomp, err = m.getSeccompProfile(pod.Annotations, container.Name, pod.Spec.SecurityContext, container.SecurityContext, m.seccompDefault)
if err != nil {
    return nil, err
}

// Set ApparmorProfile.
synthesized.ApparmorProfile = apparmor.GetProfileNameFromPodAnnotations(pod.Annotations, container.Name)

**Comment by tmrpavan** [comment]
I would like to work on this issue. Can you assign this to me?

/assign

**Comment by ashutosh887** [comment]
Should I work on this Issue?
/assign

**Comment by shivam-m-7** [comment]
Should I work on this Issue?
/assign

**Comment by sherifhmdy** [comment]
@shivam-m-7 I believe there is someone working on this now, and in approving phase, so it's kinda done.

**Comment by Abhi-y2003** [comment]
Hey, I would like to work on this. 
Can you assign it to me.

**Comment by Aakash-chouksey** [comment]
i got it!!
/assign
