### ISSUE TITLE
Possible bug in kubelet garbage collector for containerd sandbox created via runpodsandbox API

### ISSUE THREAD

**Issue by yingjun8** [kubernetes/kubernetes#117087]
### What happened?

I am attempting to perform secondary development on containerd on a node where kubelet is deployed. After calling runpodsandbox to create a sandbox, I noticed that it was immediately garbage collected by kubelet. Upon adding some logging, I found that kubelet was passing an empty filter parameter to getKubeletSandboxes and getKubeletContainers. Is this behavior reasonable? Should a LabelSelector be added to avoid erroneous deletion of containers that are not managed by kubelet?

### What did you expect to happen?

I expect kubelet not to delete containers that are not created by itself in the sandbox.

### How can we reproduce it (as minimally and precisely as possible)?

Add Kubernetes-related labels to the filter parameter when calling getKubeletSandboxes and getKubeletContainers to differentiate them.

### Kubernetes version

GitVersion:"v1.18.6-561"

### Cloud provider

Aliyun

**Comment by hasan4791** [comment]
Thats the expected behaviour from the kubelet's garbage collection.

**Comment by yingjun8** [comment]
Assuming that there is an agent similar to kubelet on the node that also operates cri, then the sandbox and container created by this agent will also  garbage collected by kubelet?

**Comment by yingjun8** [comment]
A possible way to fix this problem

`// when we create pod, patch a new label to claim created by kubelet
func newPodLabels(pod *v1.Pod) map[string]string {
	labels := map[string]string{}

	// Get labels from v1.Pod
	for k, v := range pod.Labels {
		// Sandbox can't be started with DOCKER_VM mode.
		if k == sigmak8sapi.LabelHostDNS || k == sigmak8sapi.LabelServerType {
			continue
		}
		labels[k] = v
	}

	labels[types.KubernetesPodNameLabel] = pod.Name
	labels[types.KubernetesPodNamespaceLabel] = pod.Namespace
	labels[types.KubernetesPodUIDLabel] = string(pod.UID)
	labels["io.kubernetes.pod"] = "kubelet"

	return labels
}`

`const KubernetesPod = "io.kubernetes.pod"

// getKubeletSandboxes lists all (or just the running) sandboxes managed by kubelet.
func (m *kubeGenericRuntimeManager) getKubeletSandboxes(all bool) ([]*runtimeapi.PodSandbox, error) {
	var filter *runtimeapi.PodSandboxFilter
	if !all {
		readyState := runtimeapi.PodSandboxState_SANDBOX_READY
		filter = &runtimeapi.PodSandboxFilter{
			LabelSelector: map[string]string{
				KubernetesPod: "kubelet",
			},
			State: &runtimeapi.PodSandboxStateValue{
				State: readyState,
			},
		}
	}

	resp, err := m.runtimeService.ListPodSandbox(filter)
	if err != nil {
		klog.Errorf("ListPodSandbox failed: %v", err)
		return nil, err
	}

	return resp, nil
}`

**Comment by yingjun8** [comment]
A possible way to fix this problem

`func newPodLabels(pod *v1.Pod) map[string]string {
	labels := map[string]string{}

	// Get labels from v1.Pod
	for k, v := range pod.Labels {
		// Sandbox can't be started with DOCKER_VM mode.
		if k == sigmak8sapi.LabelHostDNS || k == sigmak8sapi.LabelServerType {
			continue
		}
		labels[k] = v
	}

	labels[types.KubernetesPodNameLabel] = pod.Name
	labels[types.KubernetesPodNamespaceLabel] = pod.Namespace
	labels[types.KubernetesPodUIDLabel] = string(pod.UID)
	labels["io.kubernetes.pod"] = "kubelet"

	return labels
}`

`const KubernetesPod = "io.kubernetes.pod"

func (m *kubeGenericRuntimeManager) getKubeletSandboxes(all bool) ([]*runtimeapi.PodSandbox, error) {
	var filter *runtimeapi.PodSandboxFilter
	if !all {
		readyState := runtimeapi.PodSandboxState_SANDBOX_READY
		filter = &runtimeapi.PodSandboxFilter{
			LabelSelector: map[string]string{
				KubernetesPod: "kubelet",
			},
			State: &runtimeapi.PodSandboxStateValue{
				State: readyState,
			},
		}
	}

	resp, err := m.runtimeService.ListPodSandbox(filter)
	if err != nil {
		klog.Errorf("ListPodSandbox failed: %v", err)
		return nil, err
	}

	return resp, nil
}`

**Comment by yingjun8** [comment]
A possible way to fix this problem

`func newPodLabels(pod *v1.Pod) map[string]string {
	labels := map[string]string{}
	for k, v := range pod.Labels {
		if k == sigmak8sapi.LabelHostDNS || k == sigmak8sapi.LabelServerType {
			continue
		}
		labels[k] = v
	}

	labels[types.KubernetesPodNameLabel] = pod.Name
	labels[types.KubernetesPodNamespaceLabel] = pod.Namespace
	labels[types.KubernetesPodUIDLabel] = string(pod.UID)
	labels["io.kubernetes.pod"] = "kubelet"

	return labels
}`

**Comment by yingjun8** [comment]
A possible way to fix this problem
`
func newPodLabels(pod *v1.Pod) map[string]string {
	labels := map[string]string{}
	for k, v := range pod.Labels {
		if k == sigmak8sapi.LabelHostDNS || k == sigmak8sapi.LabelServerType {
			continue
		}
		labels[k] = v
	}

	labels[types.KubernetesPodNameLabel] = pod.Name
	labels[types.KubernetesPodNamespaceLabel] = pod.Namespace
	labels[types.KubernetesPodUIDLabel] = string(pod.UID)
	labels["io.kubernetes.pod"] = "kubelet"

	return labels
}

`

**Comment by yingjun8** [comment]
A possible way to fix this problem

![image](https://user-images.githubusercontent.com/87511604/230816490-cf61d296-d06c-462c-86a4-26c194ce6cab.png)

![image](https://user-images.githubusercontent.com/87511604/230816530-9fce3a84-aaa1-4412-a935-c2d8df116353.png)

**Comment by pacoxu** [comment]
> GitVersion:"v1.18.6-561"

The version is too old that is end-of-life in community support. Have you tried it in newer versions? (probably the same)

> > Thats the expected behaviour from the kubelet's garbage collection.
> 
> Assuming that there is an agent similar to kubelet on the node that also operates cri, then the sandbox and container created by this agent will also garbage collected by kubelet?

It seems to be a feature request to add a cri label to the sandbox.

**Comment by yingjun8** [comment]
> > GitVersion:"v1.18.6-561"
> 
> The version is too old that is end-of-life in community support. Have you tried it in newer versions? (probably the same)
> 
> > > Thats the expected behaviour from the kubelet's garbage collection.
> > 
> > 
> > Assuming that there is an agent similar to kubelet on the node that also operates cri, then the sandbox and container created by this agent will also garbage collected by kubelet?
> 
> It seems to be a feature request to add a cri label to the sandbox.

I have seen the latest version of the Kubelet and there have been no additions to the filter when list the PodSandboxes and Containers through CRI. This means that Kubelet will manage all PodSandboxes and Containers on a node. If any other CRI caller create  podSandboxes or container. Kubelet's logic such as garbage collection will have unintended consequences.

Additionally, the current method of modifying the code may cause issues when upgrading Kubelet. What I mean is that when Kubelet calls CRI such as ListPodSandbox, it should only be retrieving the PodSandboxes that were created by Kubelet itself, instead of querying all PodSandboxes, even those not created by Kubelet.

**Comment by mmiranda96** [comment]
It looks like this is expected behavior. containerd supports different namespaces, a potential workaround is to create non-k8s containers under a different namespace to avoid kubelet from GC'ing them.

/cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
See documentation on namespaces: https://github.com/containerd/containerd/blob/main/docs/namespaces.md

/kind documentation
/remove-kind bug

We may improve documentation. Not sure if there is a good place for this. @sftim is there any page that may be talking about kubelet owning containers in that namespace?
