### ISSUE TITLE
When a pod's emptyDir exceeds the resource limit, the pod will restart and enter the ContainerStatusUnknown state.

### ISSUE THREAD

**Issue by HirazawaUi** [kubernetes/kubernetes#117010]
### What happened?

When a pod's emptyDir exceeds the resource limit, the pod will restart and enter the ContainerStatusUnknown state.

### What did you expect to happen?

After the emptyDir of the pod exceeds the resource limit, the pod should enter the error state, should not restart and enter the ContainerStatusUnknown state 

### How can we reproduce it (as minimally and precisely as possible)?

step1
```
$ kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
    - name: centos
      image: centos:7
      imagePullPolicy: IfNotPresent
      command:
        - "/bin/bash"
        - "-c"
        - "sleep 1000000"
      volumeMounts:
        - mountPath: /data
          name: tm
      resources:
        limits:
          ephemeral-storage: 100M
  volumes:
    - name: tm
      emptyDir: {}
  restartPolicy: Always
EOF
```
step2

```
$ kubectl exec centos /usr/bin/dd if=/dev/zero of=/data/test bs=1M count=150
```

The status of the pod will show that the pod restarts and enters the ContainerStatusUnknown state

```
$ kubectl get pods  -w
NAME     READY   STATUS    RESTARTS   AGE
centos   1/1     Running   0          11s
centos   1/1     Running   0          77s
centos   0/1     ContainerCreating   1          79s
centos   0/1     ContainerStatusUnknown   1          79s
```

### Anything else we need to know?

I tried to reproduce #116986 and accidentally discovered an error that doesn't always occur,  requires repeated attempts to see it

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux instance-1 5.10.0-21-cloud-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd --version
containerd github.com/containerd/containerd v1.7.0 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ls-2018** [comment]
issues/117010 is the manifestation of the bug in a newer version. I have written the method of recurrence in issues/116986
 
 - https://github.com/kubernetes/kubernetes/issues/116986
