### ISSUE TITLE
Here need continue

### ISSUE THREAD

**Issue by xxwwbb3** [kubernetes/kubernetes#117027]
https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/apis/storage/validation/validation.go#L393

**Comment by pacoxu** [comment]
It seems to be valid to add `continue` here. Would you like to open a pull request for it? 
- this is like a cleanup, as the set insert will skip and the validation will do twice.

`Issues` is used to track bugs. I suggest you open a PR for that if you like.

**Comment by charles-chenzz** [comment]
/sig storage

could you be more specify that why here need continue?

**Comment by charles-chenzz** [comment]
> It seems to be valid to add `continue` here. Would you like to open a pull request for it?
> 
> * this is like a cleanup, as the set insert will skip and the validation will do twice.
> 
> `Issues` is used to track bugs. I suggest you open a PR for that if you like.

I think adding ``continue`` here sounds reasonable, cus if ``.Has(key)`` == true and we didn't skip, it will insert set twice I believe? wasn't notice that at first glance. However, I can file a PR now

**Comment by xing-yang** [comment]
Please feel free to submit a PR.
