### ISSUE TITLE
containerLogMaxSize only works as a CLI option to kubelet

### ISSUE THREAD

**Issue by hq6** [kubernetes/kubernetes#117092]
### What happened?

Adding `"containerLogMaxSize": "100Mi"` to kubelet-config had no effect. 
The containerLogMaxSize remained at 10Mi.

On the other hand, adding ` --container-log-max-size="100Mi"` to the command line produced a warning in the log file, but did seem to work:

```
Flag --container-log-max-size has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
```

### What did you expect to happen?

Either adding adding `"containerLogMaxSize": "100Mi"` to kubelet-config would actually set the container max size, or there would be no deprecation warning when using the CLI option.

### How can we reproduce it (as minimally and precisely as possible)?

1. Use eksctl to create a minimal EKS cluster.
2. ssh into one of the worker nodes.
3. Edit the file `/etc/kubernetes/kubelet/kubelet-config.json` to include the following line:
```
  "containerLogMaxSize": "100Mi"
```
4. Run the following
```
systemctl daemon-reload
systemctl restart containerd
systemctl restart kubelet
```
5. Run the following command
```
journalctl -u kubelet | grep FLAG | grep container-log-max
```
6. Observe the output contains the following:
```
FLAG: --container-log-max-size="10Mi"
```

### Anything else we need to know?

I have already looked at this issue and changed the container runtime to containerd:

https://github.com/kubernetes/kubernetes/issues/106855

### Kubernetes version

```
kubelet --version
Kubernetes v1.22.12-eks-ba74326
```

### Cloud provider

Amazon

### OS version

```
cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"

uname -a
Linux <redacted>.us-west-2.compute.internal 5.4.204-113.362.amzn2.x86_64 #1 SMP Wed Jul 13 21:34:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
The v1.22 version of K8s is no longer supported, please use the K8s within the supported version range to retest

**Comment by arnoldyahad** [comment]
Hey, @hq6  @HirazawaUi  
This still happens on EKS 1.24:

grepping as @hq6 showed above the actual flag:
```
journalctl -u kubelet | grep FLAG | grep container-log-max
Aug 03 13:16:23 ip-10-111-111-174.ec2.internalec2.info kubelet[3503]: I0803 13:16:23.007629    3503 flags.go:64] FLAG: --container-log-max-files="5"
Aug 03 13:16:23 ip-10-111-111-174.ec2.internalec2.info kubelet[3503]: I0803 13:16:23.007637    3503 flags.go:64] FLAG: --container-log-max-size="10Mi"
```

although in the configuration:
```
cat /etc/kubernetes/kubelet/kubelet-config.json | grep LogMax
  "containerLogMaxFiles": 10,
  "containerLogMaxSize": "100Mi",
```

so i guess this is not only the MaxSize but also Maxfiles.

**Comment by HirazawaUi** [comment]
> ```
> Aug 03 13:16:23 ip-10-111-111-174.ec2.internalec2.info kubelet[3503]: I0803 13:16:23.007637    3503 flags.go:64] FLAG: --container-log-max-size="10Mi"
> ```

The log shows only the value of the flag, which is the default value in the flag, but it does not actually work

Use the following method to get the correct configuration
```
 ~ sudo curl -k --key /var/run/kubernetes/client-kube-apiserver.key --cert /var/run/kubernetes/client-kube-apiserver.crt https://127.0.0.1:10250/configz | jq .kubeletconfig | grep containerLogMax
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2640  100  2640    0     0   223k      0 --:--:-- --:--:-- --:--:--  234k
  "containerLogMaxSize": "100Mi",
  "containerLogMaxFiles": 50,
```

**Comment by tzneal** [comment]
I just tried this with 1.26 and can't reproduce the issue.

```
$ grep -i log /etc/kubernetes/kubelet/kubelet-config.json
  "containerLogMaxSize": "100Mi",

$ kubectl get --raw "/api/v1/nodes/i-01d849253956f8f2d.us-west-2.compute.internal/proxy/configz" | jq .kubeletconfig.containerLogMaxSize
"100Mi"

```

**Comment by ndixita** [comment]
/close 
Since this is not reproducible, we are closing this. Please re-open if the issue occurs again.
