### ISSUE TITLE
Failure to start liveness probe on Windows should be treated like a failed liveness probe

### ISSUE THREAD

**Issue by fschmied** [kubernetes/kubernetes#117086]
### What happened?

We encountered an issue in our Azure Kubernetes Services clusters on Kubernetes 1.24.9 where, on Windows nodes, Pods came into a state where their liveness probes could no longer be started. Each start of the probe would result in the following error:

> Liveness probe errored: rpc error: code = Unknown desc = failed to exec in container: failed to start exec "d6b7[...]": hcs::System::CreateProcess 05f[...]: The RPC server is unavailable.: unknown

The original reasons of the problem and a memory leak it caused in Windows HCS are discussed elsewhere (e.g., in https://github.com/Azure/AKS/issues/3262 and https://github.com/microsoft/hcsshim/issues/1680), but I'd like to discuss a different issue here: Kubernetes did not treat these _failures to start the liveness probes_ the same way it treats _failed liveness probes_. And I think it should have, because this way, we had to monitor and restart the Pods ourselves.

### What did you expect to happen?

I would expect that Kubernetes treats a _failure to start a liveness probe_ the same way it treats a _failed liveness probe_. I.e., consider the Pod unhealthy and restart it. This would contribute to the self-healing of the system.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately, I do not have a simple repro for this issue. One needs to, on a Windows node:
* have a Pod with a command liveness probe,
* get the Pod into a state where the _CExecSvc_ within the container can no longer respond to the containerd instructions to create the process (=> _"The RPC server is unavailable"_),
* then observe how the Pod is not considered unhealthy and restarted as it would be if the liveness probe _failed_.

### Anything else we need to know?

It might be the error is in _hcshim_ or _containerd_ rather than the parts of Kubernetes covered in this repository.  If so, please do tell me and I will raise the issue in the correct repository.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.9", GitCommit:"57fbbcc2804848b95cad5519f5ec9d6355430db9", GitTreeState:"clean", BuildDate:"2023-02-08T17:22:38Z", GoVersion:"go1.18.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure Kubernetes Services
</details>

### OS version

<details>

```console
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                                   OSArchitecture  Version
17763        Microsoft Windows Server 2019 Datacenter  64-bit          10.0.17763
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
C:\C\a2ca249c0ea389d7fdd5aa905759d2e44860eeda13f8348968e78dfd6a51dfad>crictl version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.6.14+azure
RuntimeApiVersion:  v1alpha2
```
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by fschmied** [comment]
From other issues related to liveness probes, I'm guessing sig-node. Also, this might be a Windows issue, so sig-windows, too.

/sig node
/sig windows

**Comment by SergeyKanzhelev** [comment]
Is it a dup of https://github.com/kubernetes/kubernetes/issues/106682? Are you configuring exec probes?

/triage needs-information

**Comment by fschmied** [comment]
@SergeyKanzhelev Thanks for referencing that other issue, I hadn't seen it. I'm not acquainted with the inner workings well enough to know if this problem here is caused by the same error handling code paths analyzed there, but the two issues look very similar. Yes, this issue here is also about command probes.

One major difference here is that it's a condition that we, as the Kubernetes users, cannot fix. We're not configuring an invalid probe, but the (Windows containers) system stops being able to run our correctly configured probes for some reason. And it's not even our Pod, but one of AKS's. So just warning wouldn't be enough, we really need the restart so the system can heal.

I'll add a corresponding comment to the other issue. Should we close this one, then, or keep it open as it has a slightly different scope?

**Comment by SergeyKanzhelev** [comment]
/retitle Failure to start liveness probe on Windows should be treated like a failed liveness probe 

reflecting the difference with the other probe-related issue linked above. SIG Windows, do you know the reason probe would not even execute? Should this be treated as failure on Windows?

**Comment by jsturtevant** [comment]
If the liveness cannot start, then I agree it should be treated as an error.  It sounds like the underlying cause was fixed in hcsshim but could potentially happen in other scenarios.  seems like https://github.com/kubernetes/kubernetes/issues/106682 would be partially fix this.

**Comment by SergeyKanzhelev** [comment]
older report of this: https://github.com/kubernetes/kubernetes/issues/106682

fixing this we need to design carefully so we will not break existing workloads.

**Comment by SergeyKanzhelev** [comment]
/close 

in favor of https://github.com/kubernetes/kubernetes/issues/106682 as this is now non-Windows specific issue
