### ISSUE TITLE
InitContainer will be removed by containerGC when exited containers exceeds the maximum-dead-containers.

### ISSUE THREAD

**Issue by payall4u** [kubernetes/kubernetes#117005]
### What happened?

When the kubelet start with `--maximum-dead-containers`, containerGC will delete the earliest excess containers. Init container and pod container are treated equally. It may delete init container rather which created earlier then pod container.

One case is **Istio**. Init containers are crucial and should not be start repeatedly (although it is necessary to ensure reentrancy in init containers). Therefore, we should consider optimizing the logic of containerGC to clean up regular containers first and then init containers.

### What did you expect to happen?

When the number exited containers exceeds the maximum-dead-containers, containerGC will delete common container first rather then init container.

### How can we reproduce it (as minimally and precisely as possible)?

- Start kubelet with args `--maximum-dead-containers=10`
- Start a Pod A with init container
- Create job with more then 10 pod.
- Wait a minate (ContainerGC period)
- Kill container of Pod A

The init container of Pod A will recreate.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.4", GitCommit:"b7843f18423d5d0db1496340396f7b1459b69016", GitTreeState:"clean", BuildDate:"2023-03-08T11:32:25Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.4", GitCommit:"b7843f18423d5d0db1496340396f7b1459b69016", GitTreeState:"clean", BuildDate:"2023-03-08T11:25:01Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

nil

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="TencentOS Server"
VERSION="3.1 (Final)"
ID="tencentos"
ID_LIKE="rhel fedora centos"
VERSION_ID="3.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="TencentOS Server 3.1 (Final)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tencentos:tencentos:3"
HOME_URL="https://cloud.tencent.com/product/ts"

TENCENT_SUPPORT_PRODUCT="tencentos"
TENCENT_SUPPORT_PRODUCT_VERSION="3"
NAME_ORIG="TencentOS Server"

$ uname -a
Linux VM-2-7-centos 5.4.119-19-0013_plus #1 SMP Mon Jan 16 10:26:09 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
@payall4u can you please provide reproducer with steps. It is not very clear from the description what is the behavior and whether it is a bug in GC or the bug in kubelet restart logic.

Also the flag is deprecated, would switching to other flags solve the issue?

> `fs.MarkDeprecated("maximum-dead-containers", "Use --eviction-hard or --eviction-soft instead. Will be removed in a future version.")`
