### ISSUE TITLE
forbidden: User \"system:anonymous\" cannot get path \"/metrics\“

### ISSUE THREAD

**Issue by jihwong** [kubernetes/kubernetes#117035]
### What happened?

I have issued a set of administrator certificates. But the controller-manager and scheduler cannot recognize it

```
~# curl -k -I --cert admin.crt --key admin.key https://xxxx:6443/metrics --noproxy "*"
HTTP/2 200 
audit-id: 368a192d-d760-4a34-ba79-79bc2922dbe3
cache-control: no-cache, private
content-type: text/plain; version=0.0.4; charset=utf-8
x-kubernetes-pf-flowschema-uid: d7dabe8b-a602-4ffb-afe6-767e1c2c9e7d
x-kubernetes-pf-prioritylevel-uid: 1d25a6fd-c92e-4850-bd06-48a4c1b8d440

~# curl -k  --cert admin.crt --key admin.key https://xxxx:10257/metrics --noproxy "*"
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/metrics\"",
  "reason": "Forbidden",
  "details": {},
  "code": 403
}
```

### What did you expect to happen?

How should I access controller manager or scheduler？

### How can we reproduce it (as minimally and precisely as possible)?

Use a certificate or jwtToken to access the secure port of the controller manager.

### Kubernetes version

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

### Cloud provider

Local host

### OS version

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
$ uname -a
Linux pls-k8s-99 5.10.100-0510100-generic #202202110438 SMP Fri Feb 11 10:44:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

### Install tools

Binary 

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
To get apiserver metrics, `kubectl get --raw /metrics` should work as well.
For kubelet metrics, we can use `curl -k --key /etc/kubernetes/pki/apiserver-kubelet-client.key --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt https://127.0.0.1:10250/metrics` for kubeadm installed cluster.

Or I prefer to think you are using the wrong key/cert path.

**Comment by jihwong** [comment]
> 要获取 apiserver 指标，`kubectl get --raw /metrics`应该也能正常工作。 对于 kubelet 指标，我们可以使用`curl -k --key /etc/kubernetes/pki/apiserver-kubelet-client.key --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt https://127.0.0.1:10250/metrics`kubeadm 安装的集群。
> 
> 或者我更愿意认为您使用了错误的密钥/证书路径。
I need to get metrics data for controller manager and scheduler. But I don't know how to access the controller manager and scheduler of HTTPS

**Comment by neolit123** [comment]
/close
/kind support

please try asking for help on the support channels
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

also #sig-auth on k8s slack

**Comment by liangjingtao11** [comment]
@jihwong  Hi，I also encountered the same problem, do you know how to get metrics now?
