### ISSUE TITLE
Command read bug in protobuf generation

### ISSUE THREAD

**Issue by Eikykun** [kubernetes/kubernetes#117080]
### What happened?

We tried to run command  `protoc --gogo_out=plugins=grpc:. xxx/xxx/proto-file.proto` to generate `.pb.go` file. But the `plugins=grpc` option in the command seems to have not been effective. 

Perhaps it was [this](https://github.com/kubernetes/code-generator/commit/f1858f000552ce80a57a902df7f965431c6bdd48) commit that caused the issue. `paths=source_relative` used to replace all params.

### What did you expect to happen?

If the file path contains '/', other options should also take effect.

### How can we reproduce it (as minimally and precisely as possible)?

Run command like `protoc --gogo_out=plugins=grpc:. xxx/xxx/proto-file.proto` which contains request parameter and proto file path.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexzielenski** [comment]
@Eikykun is this issue still affecting you on the current release?

**Comment by Eikykun** [comment]
> @Eikykun is this issue still affecting you on the current release?
Yes, but I have no time to fix it. 
https://github.com/kubernetes/code-generator/blob/master/cmd/go-to-protobuf/protoc-gen-gogo/main.go#L37-L43

**Comment by cici37** [comment]
Thanks Fulvio for taking this :)

/triage accepted

**Comment by fulviodenza** [comment]
Hi I'll implement this as agreed at the bi-weekly meeting @cici37
