### ISSUE TITLE
remove RBAC rules allowing for creation and update of endpoints by the kubescheduler

### ISSUE THREAD

**Issue by knelasevero** [kubernetes/kubernetes#117089]
### What would you like to be added?

Not added, but removed:

Looking at this comment: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L551
this should be removed once the migration to lease in leader-election was done. Can this be removed already? I mean, the following 2 lines: https://github.com/kubernetes/kubernetes/blob/master/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L551-L553

### Why is this needed?

Security folks internally were asking if we could get rid of this upstream if it is not needed anymore (if this "migration to lease in leader-election"  was fully done)

**Comment by sathyanarays** [comment]
Support for endpoints and configmap based leader election has been removed with this PR: https://github.com/kubernetes/kubernetes/pull/106852

Validation to error out leader elections configuration for resource lock type other than "lease" has been implemented in https://github.com/kubernetes/kubernetes/pull/114055

With this, it looks safe to remove the two lines mentioned in this issue.
