### ISSUE TITLE
MountVolume.SetUp of emptyDir with sizeLimit fails on subsequent calls (fsquota)

### ISSUE THREAD

**Issue by alex-matei** [kubernetes/kubernetes#117098]
### What happened?

When sizeLimit is specified subsequent invocations will fail with the message:

```
MountVolume.SetUp failed for volume "home" : requesting quota of different size: old -1 new 2Gi
```

### What did you expect to happen?

No error should be raised.

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod with emptyDir and sizeLimit with FSQuotaMonitoring enabled, MountVolume.SetUp is called again only if the first iteration takes longer then the actual reconciler loop interval (100ms). 

### Kubernetes version

<details>

version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.0-beta.0.87+330b5a2b8dbd68", GitCommit:"330b5a2b8dbd681811cb8235947557c99dd8e593", GitTreeState:"clean", BuildDate:"2023-04-10T09:05:56Z", GoVersion:"go1.20.2", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>

Self-managed cluster in Azure

</details>

### OS version

<details>

NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.1"

Linux test-master-0 6.3.0-rc3 #1 SMP PREEMPT_DYNAMIC Thu Apr  6 20:44:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Container runtime (CRI) and version (if applicable)

<details>

Containerd 1.6.15

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

CNI: CANAL 3.24.1

</details>

**Comment by Aisuko** [comment]
May you please share more information?  Which version of Kubernetes you are using? OS version etc.

**Comment by alex-matei** [comment]
The problem occurs with the latest master branch, I updated the initial post with versions.

**Comment by Aisuko** [comment]
Thank you.
