### ISSUE TITLE
Incorrect logging from port-forward error

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#117076]
### What happened?

I got an error like

```
 error forwarding port 15008 to pod ef373fd9bb0eace525a5232b56196e8fd7144228d6c533fb645d206a134e8245, uid : network namespace for sandbox "ef373fd9bb0eace525a5232b56196e8fd7144228d6c533fb645d206a134e8245" is closed
```

### What did you expect to happen?

My error is formated like 

```
 error forwarding port 15008 to pod SOME_POD_NAME, uid SOME_UID: network namespace for sandbox "ef373fd9bb0eace525a5232b56196e8fd7144228d6c533fb645d206a134e8245" is closed
```

However, at the callsite we don't set the UID and we set "Pod Name" to the sandbox ID: https://github.com/kubernetes/kubernetes/blame/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/kubelet/cri/streaming/server.go#L351-L361

### How can we reproduce it (as minimally and precisely as possible)?

Have a failed port-forward

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
this seems to be resolved based on this comment: https://github.com/containerd/containerd/pull/8591#issuecomment-1901966169

/close
