### ISSUE TITLE
This statement will always be ture

### ISSUE THREAD

**Issue by HuangJie1990** [kubernetes/kubernetes#117026]
https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/apis/networking/validation/validation.go#L602

**Comment by HirazawaUi** [comment]
It looks like you are correct. Please feel free to submit a pull request to fix it. For information on contribute, please refer to: https://github.com/kubernetes/community/blob/master/contributors/guide/README.md

**Comment by mouuii** [comment]
https://github.com/kubernetes/kubernetes/pull/117043

**Comment by aojea** [comment]
when reporting issues please give more context to explain it, in this case `params.Scope` it is required so it never can be nil in this comparison

https://github.com/kubernetes/kubernetes/blob/d89d5ab2680bc74fe4487ad71e514f4e0812d9ce/pkg/apis/networking/validation/validation.go#L597-L600

**Comment by thockin** [comment]
Who wants to fix this?  This whole block is suspect - it checks `Namespace` for nil later, too.

**Comment by mouuii** [comment]
I'm working on it !
