### ISSUE TITLE
Can nodeselector schedule based on in / not in option selection enable affinity / anti - affinity

### ISSUE THREAD

**Issue by davidwalter0** [kubernetes/kubernetes#11707]
Can nodeselector schedule based on in / not in options?
It seems like this might enable affinity / anti - affinity?

Currently it looks like labelSelector allows set based rules and more than one predicate
from : docs/user-guide/labels.md 

LIST and WATCH operations may specify label selectors to filter the sets of objects returned using a query parameter. Both requirements are permitted:

   * _equality-based_ requirements: `?labelSelector=key1%3Dvalue1,key2%3Dvalue2`
   * _set-based_ requirements: `?labelSelector=key+in+%28value1%2Cvalue2%29%2Ckey2+notin+%28value3%29`

If nodeselector had the same functionality it would enable anti-affinity/affinity placement.

If the scheduler attempted to schedule 2 instances of the application wouldn't be scheduled to the same node, because of fault tolerance or resource constraints.

apiVersion: v1
kind: Pod
metadata:
  name: big-app
  labels:
    env: test
spec:
  containers:
  - name: big-app
    image: big-app
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
    pods: not in [ cpu-app, big-app ]?

**Comment by vishh** [comment]
cc @bprashanth

**Comment by davidopp** [comment]
The master tracking issue we're using for these kinds of suggestions is #367.

**Comment by bprashanth** [comment]
> If the scheduler attempted to schedule 2 instances of the application wouldn't be scheduled to the same node, because of fault tolerance or resource constraints.

the scheduler should do this if you create your name:big-app service before the pods (other resource utilization node metrics staying the same).

**Comment by davidopp** [comment]
Oh, I was assuming @davidwalter0 wanted hard constraints. If best-effort is acceptable then I agree with what @bprashanth said

**Comment by bgrant0607** [comment]
There is work underway to extend nodeSelector, but the others are correct that anti-affinity must be addressed via other means

**Comment by davidwalter0** [comment]
Just to clarify, in case my merging the two use cases caused confusion, I was thinking of hard affinity / anti affinity constraints.

[Apologies for the additional confusion of overloading the term node here for k8s node and numa node ]

For example, 2 instances of the same application we may want to that want numa node binding [ as we've seen some cases of > 20% perf improvment ] let's call them numa0 and numa1, Optionally they could be scheduled on the same k8s node, but 2 instances of numa0 shouldn't be scheduled to the same node.  In this case the affinity rule is an ok to schedule numa0-rc with numa1-rc, but if these consume all compute / memory on one numa-node, then 2 instances of numa0-rc shouldn't be colocated on the same k8s minion/node.

If the application isn't visibly consuming sufficient resource during a startup phase, then resource constraints couldn't know based on the memory or cpu resource requirements, unless NUMA affinity were a resource constraint.

Similarly, but for fault tolerant reasons, to guarantee that 2 instances of a persistence engine don't schedule to the same k8s node, an anti affinity option would be helpful.

**Comment by bgrant0607** [comment]
See #9560
