### ISSUE TITLE
Provide a multiplication method for the resource.Quantity

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes/kubernetes#117044]
### What would you like to be added?

I'd like to add a multiplication method for the resource.Quantity.

### Why is this needed?

Currently, the resource package provides helper methods to calculate Quantity, such as `Add` and `Sub`:

- https://github.com/kubernetes/apimachinery/blob/8d1258da8f386b809d312cdda316366d5612f54e/pkg/api/resource/quantity.go#L565-L567
- https://github.com/kubernetes/apimachinery/blob/8d1258da8f386b809d312cdda316366d5612f54e/pkg/api/resource/quantity.go#L582-L584

Batch workloads often replicate the same PodTemplate, and controllers calculate the resources needed for all containers.

In that case, It is inconvenient to call the `Add` function as many times as podTemplate, so I would like to create a helper function for multiplication.

**Comment by yshsaxena** [comment]
Hi @tenzen-y, I want to work on this issue, can you please assign it to me?

**Comment by kannon92** [comment]
Do you have an example of usage for these utilities? Just curious?

**Comment by yshsaxena** [comment]
Hi, @tenzen-y may i take this up?

**Comment by tenzen-y** [comment]
> Hi, @tenzen-y may i take this up?

I took this one, and working on this now.
