### ISSUE TITLE
DRA resource driver API: batching Pod resource claims for allocation, deallocation, resource preparation and unpreparation

### ISSUE THREAD

**Issue by byako** [kubernetes/kubernetes#117104]
### What would you like to be added?

API for resource driver Allocate and Deallocate calls should handle list of resource claim allocations like the NodePrepareResource and NodeUnprepareResources do, and DRA helper code should send all resource claims that belong to the same pod scheduling context in the same list for allocation and deallocation.

API for resource driver preparation and unpreparation of resources should also batch all the resource claims that can be prepared and unprepared at the same time by given driver based on the Pod being handled by kubelet.

### Why is this needed?

At the moment resource driver has no easy means to know all resource claims of the Pod when the Pod is being scheduled, the allocate call handles one claim at a time, which makes optimizations of resources during allocation sub-optimal and more complicated - resource driver has to keep track of what resource claims are part of particular Pod scheduling context to judge which of the previously allocated resource claims could have been sent for resource preparations, and which were not and thus can still be adjusted for resource optimization. 
In kubelet plugin as well, preparation of resource can sometimes be setting the actual HW in a state when no more additional changes can be done until previous changes are undone, making preparation of future  requests impossible, and at the moment there has to be additional logic in resource-driver kubelet-plugin forecasting which resource claims could be coming in consecutive calls to batch-prepare resources.

**Comment by pohly** [comment]
The controller changes are limited to the interface in k8s.io/dynamic-resource-allocation/controller, which we can change.

The kubelet gRPC API change is harder. We shouldn't do another hard API break in 1.28. We could add `k8s.io/kubelet/pkg/apis/dra/v1alpha3` and then support both that and `v1alpha2` in parallel in kubelet.

@bart0sh: have you considered how to do this? I remember that we discussed the controller side. I don't remember any discussion around the kubelet API.

**Comment by bart0sh** [comment]
As for Kubelet APIs it's an optional requirement, I'd simply not do it, considering the overhead of supporting 2 alpha versions.

**Comment by bart0sh** [comment]
I thought that this description implies that this requirement is optional:

> API for resource driver preparation and unpreparation of resources could also batch the resource claims that can be prepared and unprepared at the same time.

**Comment by byako** [comment]
I see, apologies, that was my phrasing mistake. The problem is there at least for our use case with the kubelet plugin needing to prepare all claims for given pod that have matching driver name at the same time, and I would like to solve it ultimately.

Would we need to bump the API version and maintain two alpha versions if we extended the API without breaking compatibility like I suggested above?

**Comment by byako** [comment]
* Updated phrasing in issue description

**Comment by bart0sh** [comment]
I somehow thought that if Controller has enough information, Kubelet plugin can also have it and we don't need to change its API. We need to discuss it further, but I'm not against changing the Kubelet API as well. It will be more consistent and easier for plugin writers, I guess.

Yes, we'd need to bump the API version as was suggested above. Let's discuss it on the next meeting.
