### ISSUE TITLE
[scheduling] movePodsToActiveOrBackoffQueue moves wrong pods to active or backoff queue

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#117179]
### What happened?

In movePodsToActiveOrBackoffQueue function, we will move pods in podInfoList to Active or Backoff queue, and then we set moveRequestCycle as current schedulingCycle. Setting moveRequestCycle will reschedule the pod currently being scheduled.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L770

Sometimes, when AssignedPodAdded is triggered, we will call movePodsToActiveOrBackoffQueue, event if the pod currently being scheduled is unrelated to the newly assignedPod, it will be recheduled.
https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L712

### What did you expect to happen?

Should we reschedule the current pod only when the currently scheduled pod is related to an event?

### How can we reproduce it (as minimally and precisely as possible)?

Submit a pod with nodename when scheduler is scheduling another pod.

### Kubernetes version

1.20-1.27

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ahg-g** [comment]
The pod currently being attempted to schedule will either be added to the backoff or the unschedulable queue if the attempt fails: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/internal/queue/scheduling_queue.go#L519

Are you suggesting that it should always be added to unschedulablePods? if so, that doesn't sound right because the cluster state changed in a way that may make it schedulable and we should attempt it again.

**Comment by KunWuLuan** [comment]
Hi, thanks for your time! @ahg-g  

> Are you suggesting that it should always be added to unschedulablePods? if so, that doesn't sound right because the cluster state changed in a way that may make it schedulable and we should attempt it again.

No, I am talking about another case. 
For example, one pod A is in scheduling cycle and another pod B is bound to a node this time. Then the scheduler will get a `assignedPodAdded` event, this event will trigger `movePodsToActiveOrBackoffQueue`:
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/pkg/scheduler/internal/queue/scheduling_queue.go#L710-L714
and in movePodsToActiveOrBackoffQueue we will always set `p.moveRequestCycle = p.schedulingCycle`:
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/pkg/scheduler/internal/queue/scheduling_queue.go#L768-L801
Even `p.getUnschedulablePodsWithMatchingAffinityTerm(pod)` return empty set, we set `p.moveRequestCycle = p.schedulingCycle`, which will reschedule pod A. And in most time we are not have to reschedule it. 
Maybe we should do some check when we set `p.moveRequestCycle = p.schedulingCycle`. WDYT?
I don't know if I explain it clearly. Please ask me if you have any question.

**Comment by ahg-g** [comment]
In the scenario you mentioned pod A will end up in one of two states: 
1. if the scheduling cycle matched it with a node, it will be bound to the node
2. if the scheduling cycle failed to find a matching node, it will be placed in the backoff queue

I don't understand what you mean by "which will reschedule pod A", is it different from the behavior I am describing above?

**Comment by KunWuLuan** [comment]
> I don't understand what you mean by "which will reschedule pod A", is it different from the behavior I am describing above?

I mean, some event won't make pod schedulable, maybe we need to check it before set `moveRequestCycle`. Like:

```
if isEventMayMakeCurrentPodSchedulable() {
 	p.moveRequestCycle = p.schedulingCycle 
}
```

**Comment by kerthcet** [comment]
We have queueingHint now which helps to determine whether worth to requeue, close. Reopen if not as your expected.
/close
