### ISSUE TITLE
Debug container copy operation fails on POD priority error

### ISSUE THREAD

**Issue by rdavyd** [kubernetes/kubernetes#117135]
### What happened?

When trying to debug POD with copy operation, it fails with error ` the integer value of priority (1000) must not be provided in pod spec; priority admission controller computed 10000 from the given PriorityClass name`. However the actual value of priority class name matches POD priority. Admission controller uses incorrect priority and operation is blocked.
```bash
$ kubectl debug -it mysql-logprocessor-54d88d9c7-fkpl7 --image=nicolaka/netshoot:v0.9 --share-processes --copy-to=test-mysql
Defaulting debug container name to debugger-jwkfp.
Error from server (Forbidden): pods "test-mysql" is forbidden: the integer value of priority (1000) must not be provided in pod spec; priority admission controller computed 10000 from the given PriorityClass name
$
$ kubectl get pod mysql-logprocessor-54d88d9c7-fkpl7 -oyaml | grep priority
  priority: 1000
  priorityClassName: mgg-generic-svc
$
$ kubectl get pc
NAME                      VALUE        GLOBAL-DEFAULT   AGE
k8s-cluster-critical      1000000000   false            2y160d
mgg-generic-batch         10000        true             343d
mgg-generic-ds            20000        false            294d
mgg-generic-svc           1000         false            343d
system-cluster-critical   2000000000   false            2y160d
system-node-critical      2000001000   false            2y160d
$
```

### What did you expect to happen?

Operation should succeed

### How can we reproduce it (as minimally and precisely as possible)?

Should be straightforwardly reproducible.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
On prem, installed via kubespray
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
Containerd 1.6.15
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BILLKOLOS** [comment]
apiVersion: v1
kind: Pod
metadata:
  name: mysql-logprocessor-54d88d9c7-fkpl7
spec:
  containers:
  - name: mysql-logprocessor
    image: <image-name>
    # other container specs
  priorityClassName: mgg-generic-svc

**Comment by ardaguclu** [comment]
I'm not sure I fully understand the problem, because `--copy-to` does not use ephemeral containers. It forces to copying pod as opposed to default behavior which uses ephemeral containers(without `--copy-to` flag).

**Comment by liggitt** [comment]
It looks like the command creating the debug container is copying the priority (1000) and not the priority class, so the cluster default priority class is injected.

**Comment by liggitt** [comment]
DeepCopy *does* copy priorityClassName. Non-pointer fields in PodSpec are copied here: https://github.com/kubernetes/kubernetes/blob/565fd4116df866a642e245d6ef9c2fe94448b265/staging/src/k8s.io/api/core/v1/zz_generated.deepcopy.go#L3915

**Comment by iyear** [comment]
My bad, get it.

**Comment by liggitt** [comment]
can you capture what the debug command is actually sending when trying to create the pod? adding --v=10 will capture the request body

**Comment by rdavyd** [comment]
@liggitt Found the issue. Cluster has admissioncontroller (kyverno) with policy that sets different priorityclasses for deployment and standalone PODs. As priority field gets copied it conflicts with priority class which is changed by kyverno.
Many thanks for support!

**Comment by liggitt** [comment]
Huh. That's worth a bug report to them… if they're stomping the priorityClassName they should also be clearing the priority
