### ISSUE TITLE
Upgrades work

### ISSUE THREAD

**Issue by anthony-sarkis** [kubernetes/kubernetes#117175]
### What would you like to be added?

A reliable default process to update between versions.

### Why is this needed?

Our last two upgrades, including an upgrade from 1.24.x to a 1.24.y k8s failed badly.
The first was an issue with deprecation and the second it just randomly hung and entered a failed state without any clear reason in logs.

Especially in the context of usage within platforms like Azure, where tools like the admin thing are not easily accessible or feel like an anti-pattern to the structure of Azure.

**Comment by pacoxu** [comment]
However, we don't remove deprecations in minor version releases. So this should not happen during 1.24.x to a 1.24.y. So can you point out what feature failed with deprecation?

BTW, what tools are you using to upgrade? If kubeadm, we may alter it to https://github.com/kubernetes/kubeadm if this is a dedicated bug. `randomly hung and entered a failed state` is not clear to me and we cannot move on to fix it as we don't know the reason.

**Comment by anthony-sarkis** [comment]
@pacoxu 

Azure UI

Somewhere between k8s, azure, etc it is not clear (at least to me) where to access useful logs when doing an upgrade, so all we get is the useless for debugging string of "failed".

If it helps it was also slow to drain the pods, the draining process also seemed to hang.

Given the above this could be more of an azure issue, but given how popular using k8s is through cloud providers, there should be some kind of default expected logging available in the upgrade case.

If there's a practical way to pass this to the right team at Azure (if that's the right course) that's great. My point of making this ticket, given that it happened twice to us, was more to raise our small vote that the upgrade process needs more 1st class attention. I was kind of assuming given that 1.25 is already out the upgrade bug either is already fixed or not relevant, but that there needs to be a stronger mentality of upgrades working and of passing through upgrade errors in a stronger way.

**Comment by pacoxu** [comment]
please contact azure support. this is the core k8s issue tracker.

also check
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

I am afraid that we should close this as this cannot indict a core k8s issue. Feel free to reopen if this can be proved to be a kube bug or a clear feature request.
/close
