### ISSUE TITLE
PV recycler fails if too many files in top-level directory

### ISSUE THREAD

**Issue by defo89** [kubernetes/kubernetes#117189]
### What happened?

PV recycler pod fails to remove files if there are `>67567` files in the directory. 

Error in the pod logs:
```
› kl recycler-for-pv-040
2023-04-10T08:17:49.426784970Z /bin/sh: 1: rm: Argument list too long
```

Apparently one hits ARG_MAX due to too long command line. 
https://stackoverflow.com/questions/11289551/argument-list-too-long-error-for-rm-cp-mv-commands

### What did you expect to happen?

PV is recycled successfully

### How can we reproduce it (as minimally and precisely as possible)?

Claim and NFS pv, create `>67567` files.

```
for i in {001..67568}
do
    echo hello > "/tmp/test/file${i}.txt"
done

# rm /tmp/test/*
-bash: /usr/bin/rm: Argument list too long
```

### Anything else we need to know?

In my testing I have provided my template and replaced the [current command](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/plugins.go#L1068) 

```
test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z "$(ls -A /scrub)" || exit 1
```

with:
```
test -e /scrub && find /scrub -mindepth 1 -delete && test -z "$(ls -A /scrub)" || exit 1
```

and recycle was successful. 

Maybe I am missing something but the `find -delete` was able to clean up everything (files, folders) and we also need to exclude the `/scrub` folder name.

`debian-base:v2.0.0` already has the `find` command, no changes to image needed.

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Bare metal
</details>

### OS version

<details>

```console
# cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3374.2.5
VERSION_ID=3374.2.5
BUILD_ID=2023-03-06-2322
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3374.2.5 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3374.2.5:*:*:*:*:*:*:*"

# uname -a
Linux minion123 5.15.92-flatcar #1 SMP Mon Mar 6 22:46:16 -00 2023 x86_64 Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz GenuineIntel GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NFS Persistent Volume
</details>

**Comment by defo89** [comment]
I can prep a PR if we are happy with using `find` command.

**Comment by xing-yang** [comment]
@defo89 Feel free to submit a PR.

**Comment by defo89** [comment]
updated the issue as per https://github.com/kubernetes/kubernetes/pull/117283#discussion_r1178449386
