### ISSUE TITLE
Error messages should include values tried (e.g. Node Selectors)

### ISSUE THREAD

**Issue by anthony-sarkis** [kubernetes/kubernetes#117176]
### What would you like to be added?

If a node selector fails and it cannot assign, then it should log as part of the message the value set tried.
This way it is clear what is a key value pair issue and what is a more general config issue.

### Why is this needed?

It is currently very hard to know if something is failing due to some overall config issue, out of bounds issue, or key:value pair matching issue. This can lead to hard-to-diagnose bugs. The standard in most software contexts is to include the values or values attempted, for example in python trying to import a package it will say it won't exist, or in js it will say ABC is undefined ,etc. etc. etc.  

https://github.com/kubernetes/kubernetes/issues/117176#issuecomment-1502058841
![image](https://github.com/kubernetes/kubernetes/assets/18080164/23e03f73-cb4c-4244-9757-8868e7c7f584)

**Comment by pacoxu** [comment]
Are you referring to the pod that cannot be scheduled because of node selectors? If yes, have you checked the pod event log? Does it provide any useful information?

Could you please provide more details about the issue? An example would greatly assist us in understanding.

**Comment by anthony-sarkis** [comment]
> Are you referring to the pod that cannot be scheduled because of node selectors?

Yes.

Here's an example of what we got:

![image](https://user-images.githubusercontent.com/18080164/230951829-3ccfc34b-66e4-49d2-80cb-ffeb5b919411.png)

So it shows it's not schedulable, but without well understanding how the rest of the process was setup, it's not clear what label is actually missing. 

So the expected thing in this error message is to also add the variable missing, e.g. "attempted to match on {ABC} tag"

Super bonus points if you could also place the available tags it tried to match against, like "available tags are [{xyz}, {123}]

**Comment by ffromani** [comment]
> ### What would you like to be added?
> 
> If a node selector fails and it cannot assign, then it should log as part of the message the value set tried. This way it is clear what is a key value pair issue and what is a more general config issue.
> ### Why is this needed?
> 
> It is currently very hard to know if something is failing due to some overall config issue, out of bounds issue, or key:value pair matching issue. This can lead to hard-to-diagnose bugs. The standard in most software contexts is to include the values or values attempted, for example in python trying to import a package it will say it won't exist, or in js it will say ABC is undefined ,etc. etc. etc.

Hi! this would be a nice enhancement. I wonder how more detailed error message would scale though. If we add per-node reject reason, the messages can quickly grow quite big even with "small" clusters with 20-30 nodes.
IMO Ideally the detailed reject reasons shoudl sit somewhere else: the events/conditions messages are best served as smuuaries, but I don't have good suggestions about where to put the detailed messages.

**Comment by kerthcet** [comment]
As @ffromani mentioned, the messages will grow too big if we include the details in the status, that's way we use the summarized messages. I think detailed logs will be a better choice as event is usually used to notify the status transition.

**Comment by kerthcet** [comment]
However in a big cluster, the logs can still be noisy.
