### ISSUE TITLE
Can not convert custom resource to the new storage api version

### ISSUE THREAD

**Issue by mariapoliss** [kubernetes/kubernetes#117148]
I created my own Custom Resource Definition. Let\`s call it `logging.customresource.com`. It has v1 and I created custom resource `logging1`.
I need to update this CRD and add v2 as storage version. Some of the properties changed its\` names in v2 and the old names removed from this new version.
I deployed conversion webhook and configured it in `logging.customresource.com` configuration. But conversion webhook does not change and save the actual custom resource `logging1` to the storage version. It allows only get the resource to my or other requests to this resource, as I understood.

I would like to make it clear: if I want to mark v1 as deprecated and stop to support it soon, I need to make upgrade of the `logging1`.

According to documentation

> If the storage version changes, existing objects are never converted automatically.

What are the ways to convert resource? I mean saving resource to etcd with the last storage version.

But when I try to modify it, `apiVersion=v2` was saved (I checked it in etcd), but the new properties did not apply and the old values are lost. And even if `logging1` has `apiVersion=v2`, I can not add new properties. It is just ignored without errors.

In the section `Upgrade existing objects to a new stored version` in option 2 said:

> Write an upgrade procedure to list all existing objects and write them with the same content. This forces the backend to write objects in the current storage version

What does `upgrade procedure` mean?
Do I need to delete `logging1` of version v1 and then recreate it with v2 or how to make work the existing custom resource but with the last api version? And maybe it is better to watch CRD `logging.customresource.com` and when storage version changed, I need to recreate custom resource (if I would like to support only v2)?

Also there was a comment https://github.com/kubernetes/website/issues/27534#issuecomment-819236827 and good question about describing what happens in different cases with or without conversion webhook, but it is not described in documentation yet unfortunately.

Documentation link: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version

**Comment by apelisse** [comment]
is the conversion from v1 to v2 round-trippable? If you take an object in v2 with all its fields set, convert it to v1 and back to v2, will it drop some fields?

**Comment by mariapoliss** [comment]
No. v2 has fields that have not analogue in v1.
Yes, fields will be removed after v2 to v1 converting.

**Comment by apelisse** [comment]
Then that's not a valid conversion. Conversions are supposed to be round-trippable.
