### ISSUE TITLE
kustomize build allows keys with slashes in ConfigMap, but validation at apply runtime causes an error

### ISSUE THREAD

**Issue by takuyaymd** [kubernetes/kubernetes#117145]
### What happened?

When `kubectl kustomize` executed based on such a kustomization.yaml, ConfigMapGenerator can generate ConfigMaps with slashes in the Keys.

```
# kustomization.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
- name: multiple-files-with-slashes
  files:
    - path/to/dir/config.yaml=files/config.yaml
```

```
# Generated ConfigMaps
---
apiVersion: v1
data:
  path/to/dir/config.yaml: |
  key=value
```

However, the resulting built manifest file cannot be Applied (`kubectl apply -k`).
This is because of this error.
```
 a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

Which of these behaviors is correct?
Personally, I would greatly appreciate it if slashes were allowed in the ConfigMap's Key.
This is because a single volume can contain a group of files in a tree structures.

If that is not allowed, then I think the same validation rules should be applied in each Build function of ConfigMapGenerator  of Kustomize as in Apply. 

### What did you expect to happen?

Can apply ConfigMap with key names containing slashes, or kustomize build fails due to validation.

### How can we reproduce it (as minimally and precisely as possible)?

Create the `files/config.yaml` file and `kutomization.yaml` listed in the example, and execute build `kubectl kuztomize` and apply `kubectl apply -k `.

### Kubernetes version

<details>

```console
$ kubectl version
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.24.4
Kustomize Version: v4.5.4
Server Version: v1.24.4
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
/sig cli
</details>

**Comment by Aisuko** [comment]
I hit the same issue before, I prefer to append validation to `kutomize`.

**Comment by thiennn-neji** [comment]
Also have the same issue here. I prefer to manage only 1 configMap (which preserves the dir tree) rather than mount multiple configMaps.

**Comment by brianpursley** [comment]
This issue might get better traction if you open it over at the [kubernetes-sigs/kustomize](https://github.com/kubernetes-sigs/kustomize) repo.
