### ISSUE TITLE
cluster-info returs error 

### ISSUE THREAD

**Issue by subhankar-banerjee** [kubernetes/kubernetes#117188]
### What would you like to be added?

when I am running this command getting error ---

rke@host-machine rke-k8s]$ kubectl get cluster-info
error: the server doesn't have a resource type "cluster-info"

but when I am running kubectl get nodes I am able to see the node list ..

kubectl version :  v4.5.7
rke version v1.4.4

is that something I am missing 

### Why is this needed?

I need to know the cluster status

**Comment by pacoxu** [comment]
See https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#cluster-info.
Please try below
```
kubectl cluster-info
or
kubectl cluster-info dump
```


/close
/kind support
/remove-kind feature

**Comment by subhankar-banerjee** [comment]
yes , that was typo ... updated kubectl version
