### ISSUE TITLE
Don't get any response from cmd in kubernetes

### ISSUE THREAD

**Issue by Jack19960220** [kubernetes/kubernetes#117190]
### What happened?

what I did:
1 I create a docker container to install visual studio 2019, everything is working in docker.
2. When I used the container to the kubernetes, I used the following command, but no any response(no error or no successful)
3. My docker version is lower than kubernetes, I guess that it may be caused by Version incompatibility.
4. I used local kubernetes, the command as following:
`"C:\Program Files\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"`

### What did you expect to happen?

The cmd should have some response from the cmd.

### How can we reproduce it (as minimally and precisely as possible)?

1. create a docker container
2. use the container in kubernetes

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
@Jack19960220, GitHub is not the right place for support requests.

If you're looking for help with containers, I recommend you start out by reading https://www.cnet.com/tech/computing/how-to-ask-for-tech-help-assitance/ (sic)

That done, you could ask people on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) for advice, or try other online forums.
