### ISSUE TITLE
Endpoint / Endpointslice objects become stuck in state where IP condition differs (not ready vs ready)

### ISSUE THREAD

**Issue by ericdstein** [kubernetes/kubernetes#117193]
### What happened?

We recently upgraded kubernetes from 1.20.12 to 1.24.10 . We now periodically experience an issue where services will "disconnect" from their endpoint, even though there were no changes to the status of the pod it references, or the node the pod is on. The issue can occur with one or more services and it always starts at the same time for all services it affects. Usually all these services have the same selector. However, it doesn't always affect all the services with that selector. For example, we could have 5 services with the same selector and only 3 of them stop working.

After this "disconnect", the endpoint object for the service shows the pod ip in NotReadyAddresses while the endpointslice object shows the ip with condition being ready. **It gets stuck in this state until we either delete the pod or endpoint or restart controller manager.**

service:
```
Name:                     postgres-psql-0
Namespace:                default
Labels:                   agent-modtime=2020_07_15T13D34D53Z
                          agent-size=354
Annotations:              <none>
Selector:                 statefulset.kubernetes.io/pod-name=postgres-0
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.105.223.13
IPs:                      10.105.223.13
Port:                     psql  5432/TCP
TargetPort:               5432/TCP
NodePort:                 psql  30432/TCP
Endpoints:
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

endpoint
```
Name:         postgres-psql-0
Namespace:    default
Labels:       agent-modtime=2020_07_15T13D34D53Z
              agent-size=354
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2023-04-08T22:11:15Z
Subsets:
  Addresses:          <none>
  NotReadyAddresses:  10.244.2.32
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    psql  5432  TCP

Events:  <none>
```

endpointslice
```
Name:         postgres-psql-0-6r7jm
Namespace:    default
Labels:       endpointslice.kubernetes.io/managed-by=endpointslice-controller.k8s.io
              kubernetes.io/service-name=postgres-psql-0
              agent-modtime=2020_07_15T13D34D53Z
              agent-size=354
Annotations:  <none>
AddressType:  IPv4
Ports:
  Name  Port  Protocol
  ----  ----  --------
  psql  5432  TCP
Endpoints:
  - Addresses:  10.244.2.32
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/postgres-0
    NodeName:   node0002
    Zone:       <unset>
Events:         <none>
```

Controller manager logs
```
08 02:58:24.319863       1 shared_informer.go:262] Caches are synced for certificate-csrsigning-kubelet-client
I0408 02:58:24.319934       1 shared_informer.go:262] Caches are synced for certificate-csrsigning-kubelet-serving
I0408 02:58:24.321346       1 shared_informer.go:262] Caches are synced for certificate-csrsigning-legacy-unknown
I0408 02:58:24.321445       1 shared_informer.go:262] Caches are synced for certificate-csrsigning-kube-apiserver-client
I0408 02:58:24.323917       1 shared_informer.go:262] Caches are synced for resource quota
I0408 02:58:24.328084       1 shared_informer.go:262] Caches are synced for daemon sets
I0408 02:58:24.364238       1 shared_informer.go:262] Caches are synced for resource quota
I0408 02:58:24.748179       1 shared_informer.go:262] Caches are synced for garbage collector
I0408 02:58:24.748232       1 garbagecollector.go:158] Garbage collector: all resource monitors have synced. Proceeding to collect garbage
I0408 02:58:24.767101       1 shared_informer.go:262] Caches are synced for garbage collector
W0408 03:56:01.896633       1 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:134: watch of *v1.Event ended with: Internal error occurred: etcdserver: no leader
W0408 04:34:25.271161       1 endpointslice_controller.go:302] Error syncing endpoint slices for service "default/postgres-psql-0", retrying. Error: EndpointSlice informer cache is out of date
W0408 06:08:02.422550       1 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:134: watch of *v1.Event ended with: Internal error occurred: etcdserver: no leader
W0408 06:09:02.005170       1 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:134: watch of *v1.Event ended with: Internal error occurred: etcdserver: no leader
W0408 08:23:02.357299       1 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:134: watch of *v1.Event ended with: Internal error occurred: etcdserver: no leader
```

Despite the repeated `etcdserver: no leader` messages in the logs above, there is no indication that etcd cluster lost it's leader. We do, however, experience a high number of leader changes due to the nature of our clusters. But this has always been the case.

### What did you expect to happen?

Given a pod that is running and healthy and that is on a node that is ready, I'd expect all services with selector matching labels defined for the pod to remain "connected" to it's endpoints.

### How can we reproduce it (as minimally and precisely as possible)?

We are unable to reproduce.

### Anything else we need to know?

We run many 3 node clusters. We only see this on a random subset of them at random times. Not on all of them. We notice this most after server maintenance where a server is rebooted. But this has occurred during periods of stability.

We understand that we may have skipped too many versions. We've upgraded this way for several years without issue and will look at reducing the jump in future upgrades. But this issue doesn't occur immediately after the upgrade and doesn't occur in all of our clusters.

During the upgrade, we perform a rolling upgrade of each VM in a cluster by **replacing** it with a VM baked with the upgraded control plane and related components. The complete cluster upgrade is completed in a few hours. Data in etcd, however, is persisted through the upgrade.

At this time it's seems to be limited to services related to our postgres cluster running in each k8s cluster. We use spilio for HA and recently noticed that this makes patch requests to endpoint objects. Nothing has changed with these postgres clusters for at least the last 6 months and we didn't experience an issue prior to upgrading k8s.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
VM on bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -a
Linux <hostname>.stores.target.com 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

- kube-apiserver-amd64:v1.24.10
- kube-scheduler-amd64:v1.24.10
- kube-controller-manager-amd64:v1.24.10
- kube-proxy-amd64:v1.24.10
- flannel:v0.19.0-amd64
- etcd:v3.4.22
- flannel-cni-plugin:v1.1.0

</details>

**Comment by aojea** [comment]
/sig network
/cc @szuecs @aojea 

updating from the slack thread

> But to rule this out, we were wondering about [spilio directly patching endpoint objects](https://github.com/zalando/spilo/blob/bb02a3a0a9da730de7a2da7da10a08b500fa7eed/postgres-appliance/scripts/callback_role.py#L66) and with the focus on endpointslices in later versions of k8s, if there's potential for that to causing things to be out of sync or reference versions to change unexpectedly.

**Comment by robscott** [comment]
>We are unable to reproduce.

To clarify, does that mean this is no longer happening for you?

>But to rule this out, we were wondering about [spilio directly patching endpoint objects](https://github.com/zalando/spilo/blob/bb02a3a0a9da730de7a2da7da10a08b500fa7eed/postgres-appliance/scripts/callback_role.py#L66) and with the focus on endpointslices in later versions of k8s, if there's potential for that to causing things to be out of sync or reference versions to change unexpectedly.

If this is patching EndpointSlices that are managed by one of our EndpointSlice controllers (either the main one or the mirroring one) it would be problematic and represent an unsupported state. The code linked is patching Endpoints resources, but it's not clear to me if those Endpoints are managed by the Endpoints controller or entirely custom.

**Comment by aojea** [comment]
/close

no answer for several months

**Comment by databus23** [comment]
We are experiencing this exact issue on multiple clusters on 1.28.8
On daily basis we have `endpoints` with pods being stuck in `notReadyAddresses` although the pod is ready and the `endpointslice` correctly lists the pod as an active endpoint.

This seems to be triggered when a pods readiness probe fails briefly. Somehow this looks like the endpoint controller misses the the update when the pod is ready again and keeps the pod as unready indefinitely.

**Comment by robscott** [comment]
>On daily basis we have endpoints with pods being stuck in notReadyAddresses although the pod is ready and the endpointslice correctly lists the pod as an active endpoint.

@databus23 To clarify, you're saying that EndpointSlices are accurate and this problem is limited to Endpoints? Do you have anything that's still reading from the Endpoints API? In my experience, the vast majority of controllers and workloads have moved to reading from EndpointSlices now. The Endpoints controller has [not meaningfully changed in a long time](https://github.com/kubernetes/kubernetes/commits/master/pkg/controller/endpoint), so this may be a very old bug. Have you found a way to reliably recreate the issue?

**Comment by databus23** [comment]
> To clarify, you're saying that EndpointSlices are accurate and this problem is limited to Endpoints?

Correct.

> Do you have anything that's still reading from the Endpoints API? In my experience, the vast majority of controllers and workloads have moved to reading from EndpointSlices now.

I agree. We noticed this because some payload in our cluster is using https://github.com/airshipit/kubernetes-entrypoint which still relys on endpoints. 

> Have you found a way to reliably recreate the issue?

Unfortunately not but it keeps happening multiple time a day in random clusters across our infrastructure now that we keep looking for it.

**Comment by aojea** [comment]
> Unfortunately not, but now that we started looking for it, it keeps happening multiple time a day in random clusters across our infrastructure.

then please try to enable logs with verbosity, at least 2,  in the cloud controller manager, and upload the logs indicating the name and namespace of the pod impacted

**Comment by aojea** [comment]
/reopen

It seems another user is reporting a similar behavior https://kubernetes.slack.com/archives/C09QYUH5W/p1718270971868209 , 
we need a reproducer or the logs of the kube-controller-manager with enough verbosity

**Comment by databus23** [comment]
We have been running our controller-manager with ` --vmodule=endpoint*=5` and this is what is logged by any of the endpoint related controllers today when the `endpoints` for the `mariadb-designate` went "stale" and 13:40:


```
I0616 13:39:27.964577      11 endpointslice_controller.go:356] "About to update endpoint slices for service" key="monsoon3/designate-mariadb"
I0616 13:39:27.964634      11 endpoints_controller.go:397] "About to update endpoints for service" service="monsoon3/designate-mariadb"
I0616 13:39:27.964825      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964844      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964946      11 endpoints_controller.go:523] "Update endpoints" service="monsoon3/designate-mariadb" readyEndpoints=0 notreadyEndpoints=2
I0616 13:39:27.980731      11 endpoints_controller.go:363] "Finished syncing service endpoints" service="monsoon3/designate-mariadb" startTime="16.133311ms"
I0616 13:39:27.980763      11 endpoints_controller.go:397] "About to update endpoints for service" service="monsoon3/designate-mariadb"
I0616 13:39:27.980960      11 endpoints_controller.go:490] "endpoints are equal, skipping update" service="monsoon3/designate-mariadb"
I0616 13:39:27.980977      11 endpoints_controller.go:363] "Finished syncing service endpoints" service="monsoon3/designate-mariadb" startTime="215.29µs"
I0616 13:39:27.981471      11 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="monsoon3/designate-mariadb" elapsedTime="16.899332ms"
I0616 13:39:27.981536      11 endpointslice_controller.go:356] "About to update endpoint slices for service" key="monsoon3/designate-mariadb"
I0616 13:39:27.981826      11 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="monsoon3/designate-mariadb" elapsedTime="292.561µs"
I0616 13:39:27.981872      11 endpointslice_controller.go:310] "Error syncing endpoint slices for service, retrying" key="monsoon3/designate-mariadb" err="EndpointSlice informer cache is out of date"
I0616 13:39:27.981971      11 endpointslicemirroring_controller.go:285] "syncEndpoints" key="monsoon3/designate-mariadb"
I0616 13:39:27.982002      11 endpointslicemirroring_controller.go:320] "Service now has selector, cleaning up any mirrored EndpointSlices" service="monsoon3/designate-mariadb"
I0616 13:39:27.982128      11 endpointslicemirroring_controller.go:282] "Finished syncing EndpointSlices for Endpoints" key="monsoon3/designate-mariadb" elapsedTime="147.01µs"
I0616 13:39:28.982099      11 endpointslice_controller.go:356] "About to update endpoint slices for service" key="monsoon3/designate-mariadb"
I0616 13:39:28.990694      11 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="monsoon3/designate-mariadb" elapsedTime="8.606036ms"
I0616 13:39:29.990876      11 endpointslice_controller.go:356] "About to update endpoint slices for service" key="monsoon3/designate-mariadb"
I0616 13:39:29.991452      11 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="monsoon3/designate-mariadb" elapsedTime="591.083µs"
```

Nothing else has been logged by the endpoint controllers for the next two hours.


the endpoints objects looks like this:

```
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2024-06-16T13:39:27Z"
  creationTimestamp: "2017-11-29T13:06:59Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    component: designate
    system: openstack
    type: database
  name: designate-mariadb
  namespace: monsoon3
  resourceVersion: "4081819282"
  uid: 2ed3fd93-d506-11e7-b370-f6de332e7f3d
subsets:
- notReadyAddresses:
  - ip: 100.90.18.2
    nodeName: minion-89baa8458613
    targetRef:
      kind: Pod
      name: designate-mariadb-7cd8cbf777-hfknw
      namespace: monsoon3
      uid: ed76ec1f-37b9-4ae3-beb3-571539440ad7
  ports:
  - name: designate-mariadb
    port: 3306
    protocol: TCP
  - name: readiness
    port: 8080
    protocol: TCP
```

end endpoint slice look like this:

```
apiVersion: v1
items:
- addressType: IPv4
  apiVersion: discovery.k8s.io/v1
  endpoints:
  - addresses:
    - 100.90.18.2
    conditions:
      ready: true
      serving: true
      terminating: false
    nodeName: minion-89baa8458613
    targetRef:
      kind: Pod
      name: designate-mariadb-7cd8cbf777-hfknw
      namespace: monsoon3
      uid: ed76ec1f-37b9-4ae3-beb3-571539440ad7
    zone: eu-nl-1a
  kind: EndpointSlice
  metadata:
    creationTimestamp: "2021-11-08T12:33:13Z"
    generateName: designate-mariadb-
    generation: 241
    labels:
      app.kubernetes.io/managed-by: Helm
      component: designate
      endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
      kubernetes.io/service-name: designate-mariadb
      system: openstack
      type: database
    name: designate-mariadb-k8kbr
    namespace: monsoon3
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Service
      name: designate-mariadb
      uid: 2eceaa23-d506-11e7-b370-f6de332e7f3d
    resourceVersion: "4081819343"
    uid: 7a06346a-3640-4132-bc68-b2d5154e95d5
  ports:
  - name: readiness
    port: 8080
    protocol: TCP
  - name: designate-mariadb
    port: 3306
    protocol: TCP
kind: List
metadata:
  resourceVersion: ""
```

**Comment by aojea** [comment]
>   creationTimestamp: "2017-11-29T13:06:59Z"
>    creationTimestamp: "2021-11-08T12:33:13Z"

heh, congratulations, really stable environment 

```
I0616 13:39:27.964825      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964844      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964946      11 endpoints_controller.go:523] "Update endpoints" service="monsoon3/designate-mariadb" readyEndpoints=0 notreadyEndpoints=2
I0616 13:39:27.980731 
I0616 13:39:27.980960      11 endpoints_controller.go:490] "endpoints are equal, skipping update" service="monsoon3/designate-mariadb"
```

hmm, *notreadyEndpoints=2* 🤔  , there is only one endpoint address , and the controlles detects two notReadyAddresses and that there are not change on the Endpoints ...


> I0616 13:39:27.981872      11 endpointslice_controller.go:310] "Error syncing endpoint slices for service, retrying" key="monsoon3/designate-mariadb" err="EndpointSlice informer cache is out of date"

@robscott one hypothesis is that the endpoints controller does not handle well the cache out of date problem, so it gets an old version from the cache and skips the update of the readiness probe, never retrying again ... does it makes sense?
However, the solution the endpointslice controller needs a considerable amoutnt of work https://github.com/kubernetes/kubernetes/pull/99345

@databus23 the [endpoint controller has an option ](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) to batch updates that can help, are you setting it? if not you can set it to 3 seconds per example , that should mitigate this problem

```

--endpoint-updates-batch-period duration
--
  | The length of endpoint updates batching period. Processing of pod changes will be delayed by this duration to join them with potential upcoming updates and reduce the overall number of endpoints updates. Larger number = higher endpoint programming latency, but lower number of endpoints revision generated
```

**Comment by databus23** [comment]
> the [endpoint controller has an option ](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/)to batch updates that can help, are you setting it? if not you can set it to 3 seconds per example , that should mitigate this problem

We are not yet. We can certainly try it but I don't understand why you are so sure that this should help mitigate the issue.

**Comment by aojea** [comment]
> We are not yet. We can certainly try it but I don't understand why you are so sure that this should help mitigate the issue.

because I'm assuming that there two events that happen fast, one is pod not ready and the second one is pod ready, however, the controller gets the data from the cache and it always see the Pod is as not ready, so I assume the problem is the cache is not updated on time ... if you add a small delay to process the events, one second should be enough, the cache will be updated with the correct state at the moment of reconcilation

> I0616 13:39:27.964825      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964844      11 endpoints_controller.go:605] "Pod is out of service" pod="monsoon3/designate-mariadb-7cd8cbf777-hfknw"
I0616 13:39:27.964946      11 endpoints_controller.go:523] "Update endpoints" service="monsoon3/designate-mariadb" readyEndpoints=0 notreadyEndpoints=2

**Comment by aojea** [comment]
/close

fixed by https://github.com/kubernetes/kubernetes/pull/125675
