### ISSUE TITLE
kube-controller-manager: resource leak

### ISSUE THREAD

**Issue by veshij** [kubernetes/kubernetes#117123]
### What happened?

In our environment we have a namespace with ~3k deployments and ~10k pods in it.
Most of the deployments are updated simultaneously. We observed that during this mass-rollout time kube-controller manager in some situations starts to consume more than 100GB of memory and significant amount of CPU.
<img width="879" alt="Screenshot 2023-04-05 at 1 56 19 PM" src="https://user-images.githubusercontent.com/6113489/230209681-18137f90-172c-4d7b-ae0f-480ab43b9f24.png">

Collected cpu and memory profiles (attached) point that significant amount of time is spent in https://sourcegraph.com/github.com/kubernetes/client-go@04ef61f72b7bc5ae6efef4e4dc0001746637fdb3/-/blob/tools/cache/thread_safe_store.go?L281

Our assumption is that it leads to unbounded growth of https://sourcegraph.com/github.com/kubernetes/client-go@04ef61f72b7bc5ae6efef4e4dc0001746637fdb3/-/blob/tools/cache/shared_informer.go?L872-877
which is called from https://sourcegraph.com/github.com/kubernetes/client-go@04ef61f/-/blob/tools/cache/listers.go?L60

![cpu](https://user-images.githubusercontent.com/6113489/230208662-e6f626aa-42dc-4458-83f4-aeefeb6ae2f2.svg) ![mem](https://user-images.githubusercontent.com/6113489/230208670-e67de67e-d761-48da-b465-a039b8828250.svg)

### What did you expect to happen?

No exponential memory growth is expected.

### How can we reproduce it (as minimally and precisely as possible)?

Create 3k deployments with 10k pods in a single namespace, update deployments simultaneously.

### Anything else we need to know?

It looks like most of the time is spent in map lookups in https://sourcegraph.com/github.com/kubernetes/client-go@04ef61f72b7bc5ae6efef4e4dc0001746637fdb3/-/blob/tools/cache/thread_safe_store.go?L292

### Kubernetes version

<details>

```console
$ kubectl version
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.8-dbx1
Kustomize Version: v4.5.7
Server Version: v1.25.8-dbx1
```

</details>

### Cloud provider

<details>
on-prem
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

</details>

**Comment by veshij** [comment]
I've a draft change which improves thread_safe_map.Index() performance https://github.com/kubernetes/kubernetes/pull/117122, but want to know what do you think about this issue before publishing that PR.

**Comment by wzshiming** [comment]
I am going to try to reproduce it use the [latest kwokctl](https://github.com/kubernetes-sigs/kwok)

``` bash
kwokctl create cluster  --prometheus-port 9090
```

``` bash
docker run -d --name=grafana -p 3000:3000 docker.io/grafana/grafana:8.5.2
```

    1. Open your web browser and go to http://localhost:3000
    2. On the login page, enter admin for username and password
    3. Add Prometheus Datasource http://host.docker.internal:9090 on Grafana
    4. Import via grafana.com code 16248 on Grafana


``` bash
for i in {1..1000};do
  kubectl apply -f - <<EOF
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    kwok.x-k8s.io/node: fake
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: kwok-node-$i
    kubernetes.io/os: linux
    kubernetes.io/role: agent
    node-role.kubernetes.io/agent: ""
    type: kwok
  name: kwok-node-$i
status:
  allocatable:
    cpu: 32
    memory: 256Gi
    pods: 110
  capacity:
    cpu: 32
    memory: 256Gi
    pods: 110
  nodeInfo:
    architecture: amd64
    bootID: ""
    containerRuntimeVersion: ""
    kernelVersion: ""
    kubeProxyVersion: fake
    kubeletVersion: fake
    machineID: ""
    operatingSystem: linux
    osImage: ""
    systemUUID: ""
  phase: Running
EOF
done

for i in {1..10000};do
  kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-$i
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fake-pod-$i
  template:
    metadata:
      labels:
        app: fake-pod-$i
    spec:
      containers:
        - name: fake-container
          image: fake-image
EOF
done
```

``` bash
kubectl label deploy --all status=1
```

**Comment by veshij** [comment]
Cluster in total runs 30+k pods, multiple deployments could be active around the same time. Hard to say how much other replicasets/pods do contribute to the issue. This behavior is triggered not in 100% of cases, likely when load hits some threshold.

**Comment by liggitt** [comment]
the graph doesn't look like a leak, since the memory use does decrease after a period of time... is the issue actually a leak or just higher than expected short-term memory use?

**Comment by pacoxu** [comment]
> the graph doesn't look like a leak, since the memory use does decrease after a period of time... is the issue actually a leak or just higher than expected short-term memory use?

This is more like a relist after failed watch. We have a similar issue in clusterpedia（a multi-cluster search engine that needs to collect realtime data from kubeapiservers） when it restart（or watch failed）the list api for many resources will make a large memory cosuming in a sudden and the memory would be low if the watch works fine. Not sure if it is the case.

**Comment by veshij** [comment]
It's probably not a leak by definition, it eventually releases memory (if not killed by OOM), so it's "higher than expected short-term memory use".

**Comment by alexzielenski** [comment]
I think this might be sig/apps now that the bug is traced to PDB

/remove-sig api-machinery
/sig apps
