### ISSUE TITLE
Traffic is getting send to unready pod in kubernetes

### ISSUE THREAD

**Issue by ayush-ia** [kubernetes/kubernetes#117270]
### What happened?

We have added readiness probe and the container is in unready state until it is fully loaded but in case of horizontal autoscaling a new pod which is in unready state starts getting traffic due to which request are failing. We are using nginx ingress controller for loadbalancing and service type is of ClusterI
![pod3](https://user-images.githubusercontent.com/47336531/231657859-48b9d36f-ed2c-4990-bb08-b2359a3e3a3e.jpg)

### What did you expect to happen?

Traffic should be only send to ready pods

### How can we reproduce it (as minimally and precisely as possible)?

Setup AKS cluster, create a test pod with readiness probe and service type: ClusterIP and enable horizontal autoscaling and test by adding load

### Kubernetes version

<details>

```console
$ kubectl version
v1.25.4
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
BuildNumber  Caption                          OSArchitecture  Version
19045        Microsoft Windows 10 Enterprise  64-bit          10.0.19045

</details>


### Install tools

<details>
Ngnix Ingress Controller for loadbalancing
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug

there are many moving parts in this issue without a clear description and relation between them

**Comment by shaneutt** [comment]
@ayush-ia we talked about this one in the SIG Network meeting today: since we haven't hard back from you on this one in some time, we're going to consider this closed for the time being. However, if you still have problems here please feel free to drop a new comment and we can continue the discussion as needed.

/close
