### ISSUE TITLE
hack/verify-mocks.sh fails on cleanup

### ISSUE THREAD

**Issue by marthinal** [kubernetes/kubernetes#117272]
### What happened?

I get a permission denied error when running hack/verify-mocks.sh from my macOS Monterey (Silicon).  #116338 is basically the same problem BUT with Linux. 

"go install" is adding some files to the cache and because of the permissions I can't delete them. This is an example:

```
% ls -l /private/var/folders/g3/73rql5xd5t7cxt63gwkf04n00000gn/T/verify-mocks.sh.XXXXXX.h6yL2P2F/_output/local/go/cache/mod/golang.org/x/tools@v0.6.0/go/analysis/passes/tests/testdata/src/a
total 32
-r--r--r--  1 marthinal  staff    25 Apr 12 15:30 a.go
-r--r--r--  1 marthinal  staff  3562 Apr 12 15:30 a_test.go
-r--r--r--  1 marthinal  staff   155 Apr 12 15:30 ax_test.go
-r--r--r--  1 marthinal  staff  3794 Apr 12 15:30 go118_test.go
```

The problem can be fixed by running "go clean -modcache" from the cleanup function. 

### What did you expect to happen?

The test must pass.

### How can we reproduce it (as minimally and precisely as possible)?

Execute "make verify" from  macOS M1. BUT in [this issue](https://github.com/kubernetes/kubernetes/issues/116338)  they are using Linux. 

Here is the error:
<img width="1556" alt="Screenshot 2023-04-13 at 07 46 15" src="https://user-images.githubusercontent.com/2011140/231665828-a6ef24bb-31ce-4edd-89d5-0c5f4adcc278.png">

After running "go clean -modcache" from the cleanup function:
<img width="1638" alt="Screenshot 2023-04-13 at 07 52 21" src="https://user-images.githubusercontent.com/2011140/231665989-b69ad016-d8f3-4e4f-b74f-4c82e6c58a39.png">

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:25Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
macOS Monterey 12.6.4 (Apple Silicon)
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by marthinal** [comment]
PR https://github.com/kubernetes/kubernetes/pull/117273

**Comment by BenTheElder** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/117510

**Comment by thockin** [comment]
This MUST have worked correctly at some point or it should not have merged...

**Comment by BenTheElder** [comment]
Tim and I looked some more -- this will be fixed in https://github.com/kubernetes/kubernetes/pull/117526
/assign
