### ISSUE TITLE
[kube-proxy] In IPVS mode, TCP connection lost when node recover to ready

### ISSUE THREAD

**Issue by leonstack** [kubernetes/kubernetes#117205]
### What happened?

1. Client connects to a workload(contains PodA, PodB) by clusterIP, and actually connect to PodA 
2. When the Node which PodA belong to become to ‘not ready’ because of some reasons(for example etcd unstable, kubelet is down), but the network is healthy.
3. Then the ipvsadm -ln shows the forward rule to PodA is set weight to 0, and the TCP connection still working
4. But when the Node recover to 'ready' status, the TCP connection for PodA was removed because the kube-proxy remove the PodA from IPVS, and add the PodA to IPVS immediately.

### What did you expect to happen?

If there is TCP connection for PodA, when the node recover to 'ready' status, kube-proxy should just update the weight to 1, not remove it from IPVS

### How can we reproduce it (as minimally and precisely as possible)?

1. Client connect to a workload by clusterIP.
2. stop kubelet serivce on a node which workload belong to.
3. when the node become to 'not ready' stauts, start kubelet.
4. when the node become to 'ready' status, check the client connection to clusterIP.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-27T13:35:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.15", GitCommit:"58178e7f7aab455bc8de88d3bdd314b64141e7ee", GitTreeState:"clean", BuildDate:"2021-09-27T13:35:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux tos-126-36 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by danwinship** [comment]
/triage accepted
/cc @uablrek 

So I've never looked at the ipvs graceful termination code before, but it seems to do this intentionally? When adding a "new" endpoint that is already in the graceful delete list, proxier.go calls `proxier.gracefuldeleteManager.MoveRSOutofGracefulDeleteList`, which calls `m.ipvs.DeleteRealServer` and removes the endpoint from the list. Then proxier.go creates a new endpoint.

Maybe this is just a dumb mistake, but there's an explicit comment explaining this behavior ("`// check if newEndpoint is in gracefulDelete list, if true, delete this ep immediately`") so it seems pretty intentional... maybe there's some reason why setting the weight back to 1 instead of 0 doesn't work? Lars? Anyone?

If not, it seems simple enough to fix: `MoveRSOutofGracefulDeleteList` should just be basically the inverse of `GracefulDeleteRS`.

**Comment by uablrek** [comment]
I think the "shutdown" in graceful shutdown is taken literally. The POD is supposed to terminate. If it comes back to ready, some error is assumed and the endpoint is removed/reinserted just in case.

But to make a POD not-ready for a while, for example on an overload, is a valid use-case. IMO the weight should be restored.

How does proxy-mode=iptables handle this? I suppose it just update the iptables load-balancing, and the conntracker make sure existing connections are unaffected. If so, that is another reason for ipvs to behave in a similar way.

**Comment by uablrek** [comment]
@andrewsykim May know more

**Comment by sondinht** [comment]
If keeping the sysctl parameter below disabled as its default value, ipvs retains existing connections even if the ipvs entries associated with the connections are removed in this particular case.

```
expire_nodest_conn - BOOLEAN
        0 - disabled (default)
        not 0 - enabled

        The default value is 0, the load balancer will silently drop
        packets when its destination server is not available. It may
        be useful, when user-space monitoring program deletes the
        destination server (because of server overload or wrong
        detection) and add back the server later, and the connections
        to the server can continue.

        If this feature is enabled, the load balancer will expire the
        connection immediately when a packet arrives and its
        destination server is not available, then the client program
        will be notified that the connection is closed. This is
        equivalent to the feature some people requires to flush
        connections when its destination is not available.
```

The parameter is however set to 1 explicitly in the ipvs proxier for some reasons. 

```go
	// Set the expire_nodest_conn sysctl we need for
	if err := utilproxy.EnsureSysctl(sysctl, sysctlExpireNoDestConn, 1); err != nil {
		return nil, err
	}
```
It can be disabled to support this use-case in the same way that iptables proxy-mode behaves. Though, I'm not sure if the change conflicts with any other use-cases.

**Comment by uablrek** [comment]
@sondinht That is another use-case. The set to 1 is correct. When a server drops out the client want's to know. This is about weight. It is set to 0 when a pod is not-ready, and when the pod becomes ready again the endpoint is removed/reinserted instead of simply setting weight=1, which is likely the correct action.

**Comment by uablrek** [comment]
Related https://github.com/kubernetes/kubernetes/issues/108319

**Comment by uablrek** [comment]
I can't recreate this problem on latest K8s (v1.28.0-alpha.0.466+8ae8e775607508)

**Comment by uablrek** [comment]
This problem doesn't seem to exist in recent K8s version. I have tested:
1. Send _continuous_ TCP traffic via a service
2. stop kubelet
3. Wait until weight=0 for endpoints on that node
4. Restart kubelet
5. Wait until weight=1 for endpoints on that node

The connections to pods on the node (the ones that got weight 0/1) were not affected at all.

Please verify this problem on K8s v1.27.1

**Comment by uablrek** [comment]
I also tested the much simpler case where a POD becomes not-ready and the back to ready, which is more "normal" than to stop kubelet. That also works fine.

**Comment by uablrek** [comment]
Ping @leonstack were you able to reproduce this in the latest k8s versions?

If not, we assume this is solved and will close the issue.

**Comment by danwinship** [comment]
/close
per previous comment; this seems to be fixed in current releases
