### ISSUE TITLE
☂️ Compatibility test suite for scheduler framework (out-of-tree plugins)

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#117215]
## Background

Scheduler framework provides extension hooks to scheduler plugins. k/k usually does a good job to ensure all in-tree plugins adheres to framework changes in each release, but it's not always the case for out-of-tree plugins. For example, https://github.com/kubernetes/kubernetes/pull/115583#issuecomment-1502637388 reveals a case that we wanted to make in-tree plugin more efficient, but mistakenly breaks the compatibility of out-of-tree plugins. Per suggestion in https://github.com/kubernetes/kubernetes/pull/117194#issuecomment-1503223500, this umbrella issue is created to ensure adequate test coverage of potential paths on each extension point that out-of-tree plugins may exercise.

Note: when composing tests, think loud on other patterns of using a particular extension point.

```[tasklist]
# Compatibility test suite for scheduler framework (out-of-tree plugins)
- [ ] PreEnqueue - plugin A registered as PreEnqueue plugins. In the first 2 runs, plugin A failed an incoming Pod, and thus the incoming Pod gets put into backoffQ. Then verify if plugin A gets called again when backoff timer expired.
- [ ] ...
```

**Comment by alculquicondor** [comment]
Each of the tests we add should have a deliberation. We shouldn't simply accept the way an out-of-tree plugin is using the scheduling framework if we have to sacrifice in-tree plugins performance or if it significantly adds maintenance burden.

That said, I'm in favor of the test for https://github.com/kubernetes/kubernetes/pull/115583#issuecomment-1502637388

**Comment by Huang-Wei** [comment]
Yes, before working on a PR, each upcoming test needs to describe the intention specifically under this issue.

**Comment by sanposhiho** [comment]
Not sure if it's the right place to mention, but I recently feel we need to have the performance test (in scheduler_perf or `Benchmark_XXX`) to ensure no performance degradation on enqueueing in various scenario, given we already have PreEnqueue, and we'll have wise-enqueueing via [my proposal](https://github.com/kubernetes/kubernetes/issues/114297) or [pohly's one](https://github.com/kubernetes/kubernetes/pull/117561).

**Comment by Huang-Wei** [comment]
A function level BenchmarkXYZ test may not be able to test an e2e flow. We can craft new tests in scheduler_perf to cover 1) basic scenario that not involves in-flight pod, and 2) scenario that involves in-flight pod (e.g., DRA specific [one](https://github.com/kubernetes/kubernetes/pull/116207)). Then with the results of 1) and 2), it can give us more clues how to proceed.

**Comment by kerthcet** [comment]
> Per suggestion in https://github.com/kubernetes/kubernetes/pull/117194#issuecomment-1503223500, this umbrella issue is created to track potential paths of out-of-tree plugins exercising each scheduler extension point.

Poor points, shouldn't this be ensured in scheduler-plugins repo, in kubernetes, we can fake new plugins in tests to make sure this not happen.

**Comment by Huang-Wei** [comment]
> Poor points, shouldn't this be ensured in scheduler-plugins repo, in kubernetes, we can fake new plugins in tests to make sure this not happen.

That's really the intent. By "out-of-tree plugins", I meant a mock plugin to simulate how out-of-tree plugins may exercise the extension points, not a particular out-of-tree plugin. Reworded a bit to avoid confusion.

**Comment by kerthcet** [comment]
/remove-lifecycle rotten
still make sense

**Comment by sanposhiho** [comment]
/unassign

Someone else feel free to pick it up instead of me. I think I cannot be back to this one soon.
Will re`/assign @sanposhiho` once I can back.
