### ISSUE TITLE
Documentation for Adding windows node in kubernetes 

### ISSUE THREAD

**Issue by Sameer-Italiya** [kubernetes/kubernetes#117207]
I have created an on-prem Kubernetes 1.24 cluster using kubeadm in Ubuntu 18.04 as a master node. I want to add windows server 2019 as a worker node in the Kubernetes cluster.

Can we have official straightforward documentation for adding a Windows node using kubeadm for Kubernetes version 1.24?

If not then what will be the reason that Kubernetes cluster creation with Windows node documentation is not available?

**Comment by neolit123** [comment]
Duplicated by https://github.com/kubernetes/website/issues/34476

/close
