### ISSUE TITLE
cloud provider updating load balancer before registering the node

### ISSUE THREAD

**Issue by kmala** [kubernetes/kubernetes#117375]
### What happened?

After [this](https://github.com/kubernetes/kubernetes/pull/109706) change , the cloud provider controller is calling the update load balancer before the node controller registers the node with the cloud provider.

### What did you expect to happen?

The cloud provider controller shouldn't call update load balancer for the nodes which are not yet registered to the cloud provider or we need to call updateloadbalancer once the node is registered with the lb.

### How can we reproduce it (as minimally and precisely as possible)?

Create a LB service with externalTrafficPolicy=Local. Once the lb is provisioned, add a new node and it won't be registered to the LB.

### Kubernetes version

<details>

```console
$ kubectl version
# WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexanderConstantinescu** [comment]
Filed a PR which should fix the issue. The AWS controller isn't erroring when syncing nodes which are missing the providerID, as reported in the original issue. Would it have done that: the Node sync would have been retried until the providerID was set. 

Given this: I've added the providerID as a predicate when syncing Nodes. This will enforce that it is always set when the cloud-provider code gets invoked and we always trigger a new sync once the providerID gets set.

**Comment by kmala** [comment]
Thanks for the PR with the fix and if we want the cloud provider to error out in such scenarios, then I think it would make sense to update the comments for the method in the interface such that we are setting the right expectations for the providers who are going to implement the interface
