### ISSUE TITLE
main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/hack/tools/ncpu

### ISSUE THREAD

**Issue by TommyStarK** [kubernetes/kubernetes#117362]
### What happened?

I am not able to run tests through make rules if the repo isn't located under `$GOPATH/src/k8s.io`.

```bash
❯ make test GOFLAGS="-v -failfast -count=1" KUBE_COVER="y" WHAT=./pkg/kubelet/kuberuntime
main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/hack/tools/ncpu
!!! [0414 17:10:00] Call tree:
!!! [0414 17:10:00]  1: hack/make-rules/test.sh:24 kube::golang::setup_env(...)
make: *** [Makefile:184: test] Error
```

### What did you expect to happen?

Run unit tests for `pkg/kubelet/kuberuntime`.

### How can we reproduce it (as minimally and precisely as possible)?

```bash
❯ pwd
/Users/thomasmilox/perso/kubernetes

❯ go version
go version go1.20.3 darwin/amd64

❯ make test GOFLAGS="-v -failfast -count=1" KUBE_COVER="y" WHAT=./pkg/kubelet/kuberuntime
main module (k8s.io/kubernetes) does not contain package k8s.io/kubernetes/hack/tools/ncpu
!!! [0414 17:10:00] Call tree:
!!! [0414 17:10:00]  1: hack/make-rules/test.sh:24 kube::golang::setup_env(...)
make: *** [Makefile:184: test] Error
```

### Anything else we need to know?

To solve the issue I had to:

```bash
❯ go get k8s.io/kubernetes/hack/tools/ncpu

❯ cd `find $GOPATH -type d -name "ncpu"`

❯ go install .
```

https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L561-L567

It seems to happen on my setup because of my fork not being located under `$GOPATH/src/k8s.io`.

Is this worth opening a PR to document it  (in development guide for example) ? or we want to enforce people working under `$GOPATH/src/k8s.io` ?

### Kubernetes version

<img width="326" alt="Screenshot 2023-04-15 at 16 00 17" src="https://user-images.githubusercontent.com/9576370/232228961-2cdf12de-99a6-4b95-9b4f-b93b5adc6f3a.png">

### Cloud provider

NONE

### OS version

```bash
❯ uname -a
Darwin Thomass-MBP 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64 i386 Darwin
```

### Install tools

NONE

### Container runtime (CRI) and version (if applicable)

NONE

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NONE

**Comment by BenTheElder** [comment]
> I am not able to run tests through make rules if the repo isn't located under $GOPATH/src/k8s.io.

So, this is generally not well supported and many tools still need GOPATH mode.

However the issues is this script needs to setup the go env cc @dims

**Comment by BenTheElder** [comment]
We usually fake a GOPATH containing the repo with symlink trickery if there isn't one available, however I'd recommend operating under GOPATH for developing kubernetes still and AFAIK we still document this in the developer setup guides.

**Comment by TommyStarK** [comment]
Just so you know when working under `$GOPATH/src/k8s.io` this script works as intended and installs correctly `ncpu`. I opened the issue because the main readme mentions that to build kubernetes the first step is to be `mkdir -p $GOPTATH/src/k8s.io`,  however (unless I missed it) this is not mentioned again in the development guide.
This is my case when I decided to started to contribute I followed the guides for setting up dev env and running test but I did not place my fork under GOPATH.
I was thinking to provide a solution for people not working under GOPATH then I thought GOPATH could be an heavy suggestion to avoid any other issues.

if not working under GOPATH here is the fix:
```bash
❯ go get k8s.io/kubernetes/hack/tools/ncpu

❯ cd `find $GOPATH -type d -name "ncpu"`

❯ go install .
```

**Comment by BenTheElder** [comment]
> I was thinking to provide a solution for people not working under GOPATH then I thought GOPATH could be an heavy suggestion to avoid any other issues.

It is a heavy suggestion, my point is just that it has been developed in gopath for so long and many things still have GOPATH dependencies that I'd recommend that you still clone it under GOPATH, aside from this particular bug needing fixing.

You don't need to install this ncpu tool system wide, the fix will be enabling these scripts to setup fake GOPATH properly, which we do in other scripts to enable working without a real GOPATH.

**Comment by BenTheElder** [comment]
/assign

This is strange, I actually can't reproduce it using a copy of kubernetes cloned outside of my GOPATH (I made another clone to $HOME/kubernetes and then ran `make test GOFLAGS="-v -failfast -count=1" KUBE_COVER="y" WHAT=./pkg/kubelet/kuberuntime`, with go1.20.2 on macOS

The script is already setting up a fake gopath just above installing ncpu.

@TommyStarK anything else you can think of about this environment?

Does this still reproduce at HEAD for you? If so, maybe share `go env` here?

**Comment by BenTheElder** [comment]
I did find a different issue that seems related to the ncpu change though https://github.com/kubernetes/kubernetes/pull/117510

**Comment by pohly** [comment]
I was about to say that Go workspace mode should fix such issues, but then remembered that `hack/tools` probably will not be included in the unified workspace because its dependencies need to be separated from those for Kubernetes.

What should work is `(cd hack/tools && go install ./ncpu)` instead of `go install k8s.io/kubernetes/hack/tools/ncpu`.

**Comment by TommyStarK** [comment]
@BenTheElder yes it does reproduce at HEAD for me.

Here my go env:

```bash
❯ go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/thomasmilox/Library/Caches/go-build"
GOENV="/Users/thomasmilox/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/thomasmilox/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/thomasmilox/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.20.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.20.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.20.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="cc"
CXX="c++"
CGO_ENABLED="1"
GOMOD="/Users/thomasmilox/perso/kubernetes/go.mod"
GOWORK="/Users/thomasmilox/perso/go.work"
CGO_CFLAGS="-O2 -g"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-O2 -g"
CGO_FFLAGS="-O2 -g"
CGO_LDFLAGS="-O2 -g"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/7t/rjwhwzfx36d85s9njc1x4s000000gn/T/go-build2147507421=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

I also have a go workspace:

```bash
❯ cat ../go.work
go 1.20

use (
	./kubernetes
	./warp
)
```

**Comment by TommyStarK** [comment]
@pohly `(cd hack/tools && go install ./ncpu)` did not work for me, this is why I ended with:

```go get k8s.io/kubernetes/hack/tools/ncpu && cd `find $GOPATH -type d -name "ncpu"` && go install .```

When removing `ncpu` from `$GOPATH/bin`, this is what I get:

<img width="724" alt="Screenshot 2023-04-21 at 11 56 49" src="https://user-images.githubusercontent.com/9576370/233608012-b88fb591-512f-4252-9961-2b8fc7d72e2e.png">

**Comment by pohly** [comment]
The `main module (k8s.io/kubernetes) does not contain` is odd. It should talk about k8s.io/kubernetes/tools, which has its own go.mod. I'm out of ideas.

**Comment by pohly** [comment]
Just noticed this:
> GOMOD="/Users/thomasmilox/perso/kubernetes/go.mod"
> GOWORK="/Users/thomasmilox/perso/go.work"

The `cd` trick relies on not overriding GOMOD.

Also, don't set GOWORK. A lot of tools invoked during `make` currently break when that is enabled.

**Comment by TommyStarK** [comment]
I did not set GOMOD intentionally but GOWORK yes. I think I got it, this is probably why Ben isn't able to reproduce it. I made a symlink from my fork towards GOPATH it avoids make rules to break. I wanted to raise an issue but now it seems only related to my particular setup. Do you want me to go ahead and close this issue ?

**Comment by BenTheElder** [comment]
I think we actually have this working just not with go.work.

The scripts wrapping ncpu do cd to the module and set up fake gopath etc, if you spot anywhere else something like this happens without go.work please file another issue, despite my suggestion to clone in gopath I've done a pass and I can't find anywhere we aren't do golang::setup_env and we depend on that for other purposes now like ensuring the correct go version automatically if the host doesn't have it.

thanks, I think we can close this now
