### ISSUE TITLE
the same device is mounted twice and generates two different globalmountpath

### ISSUE THREAD

**Issue by Chaunceyctx** [kubernetes/kubernetes#117336]
### What happened?

when I upgrade k8s version from 1.23.14 to 1.25.5, I meet a problem. The same device /dev/sda is mounted twice and generates two different global mount path. As shown below:
![image](https://user-images.githubusercontent.com/29896262/231974658-82ab336d-da46-460a-ad18-59a9b9ed4415.png)
Because of changes to global mount path https://github.com/kubernetes/kubernetes/pull/107065, I believe that 1.25 kubelet would cause pod to perform the volume mount process , thus doing the mount device operation again. I checked the relevant changelog https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md and issue https://github.com/kubernetes/kubernetes/issues/105899#issuecomment-951778471. They stated that "Nodes must be drained before updating the kubelet ".

But can we work out a smooth upgrade solution, as my pr shows https://github.com/kubernetes/kubernetes/commit/91e9b958a305976c0db142e5c0b32790d7b7051a

### What did you expect to happen?

upgrade smoothly rather than node drained

### How can we reproduce it (as minimally and precisely as possible)?

upgrade 1.23.15 -> 1.25.5

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Chaunceyctx** [comment]
/sig storage
@jsafrane @andyzhangx @saikat-royc

**Comment by jsafrane** [comment]
IMO, draining of nodes has been always required during minor version upgrade, see https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/. It may have worked in the past without draining, but it was never guaranteed.

**Comment by Chaunceyctx** [comment]
> 

Let me cc... So we are always supposed to drain node before any version upgrade?

**Comment by Chaunceyctx** [comment]
> IMO, draining of nodes has been always required during minor version upgrade, see https://kubernetes.io/docs/tasks/administer-cluster/cluster-upgrade/. It may have worked in the past without draining, but it was never guaranteed.

let me cc... So we are always supposed to drain node before any version upgrade?

**Comment by cvvz** [comment]
I think drain node is necessary, if the cluster is deployed by cloud provider, drain node would be one of the standard steps, take aks as an example: https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster?tabs=azure-cli#:~:text=With%20a%20list,and%20zone%20balance.

**Comment by Chaunceyctx** [comment]
fine, /close this issue
