### ISSUE TITLE
Doc page for generic Controller+Watch pattern.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#11730]
I've been looking more at the way ReplicationControllers use the cache and the controller framework, and have put together a very rough draft of how the controller watch pattern works, along side a simple exersize people can follow along with etcdctl.

http://jayunit100.blogspot.com/2015/07/looking-at-controller-watch-pattern-in.html

This is pretty raw but I will clean it up and submit a PR with a high level description of the watch pattern unless another doc already is planning on doing this.  Just thought I'd create an Issue for this as a placeholder, **the bottom line is simply that it will be nice to have a doc page for the controller+watch pattern that can be referenced from the replication_controller.go and endpoints_controller.go files.**

**Comment by vishh** [comment]
cc @lavalamp
