### ISSUE TITLE
Upgrade etcd to 3.5.8

### ISSUE THREAD

**Issue by kkkkun** [kubernetes/kubernetes#117341]
### What would you like to be added?

Upgrade etcd to 3.5.8 tracking 

- [x] update build etcd image to 3.5.8-0 https://github.com/kubernetes/kubernetes/pull/117332
- [x] update etcd version to 3.5.8 https://github.com/kubernetes/kubernetes/pull/117335
- [x] upgrade etcd deps to v3.5.8  https://github.com/kubernetes/kubernetes/pull/117342
- [x] update image promotion for etcd 3.5.8-0 https://github.com/kubernetes/k8s.io/pull/5157

### Why is this needed?

Update etcd to version 3.5.8 See release: [v3.5.8](https://github.com/etcd-io/etcd/releases/tag/v3.5.8).

**Comment by thockin** [comment]
Why is this sig-network?

**Comment by pacoxu** [comment]
/remove-sig network

> Why is this sig-network?

I mistakenly added it as I thought it is coredns. Sorry for the noise.

**Comment by kkkkun** [comment]
Cool. The tasks are finished.  Thanks @pacoxu 
/close
