### ISSUE TITLE
e2e test to validate the metrics on the apiserver

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#117374]
>   Not sure how we would catch this via static analysis, but I think it would be easy enough to write a new e2e (in a separate PR) that checks the complete set of metrics registered against the API server (so that list would be updated every time someone added something new).

_Originally posted by @enj in https://github.com/kubernetes/kubernetes/pull/117295#discussion_r1167071204_

Taking the integration test from https://github.com/kubernetes/kubernetes/pull/117295/ as example, the test:
1. will have a list with the existing metrics as input
2.  will run an apiserver
3. query the metrics from the /metrics endpoint
4. the returned metrics and the existing metrics received as input have to match

/sig api-machinery
/sig instrumentation

/help

**Comment by iyear** [comment]
A question: IMO, this is similar to https://github.com/kubernetes/kubernetes/blob/054c489d00c59c259bec7d27c2fee3969c6d93f6/test/integration/metrics/metrics_test.go#L79-L105 ?

But to detect all metrics, we have to send all possible requests to get the metrics exported.

**Comment by enj** [comment]
I would expect all metrics to be registered before the server reports healthy (making other requests should not be required).

Also, this same test applies to kubelet, controller manager, scheduler, etc.  They all have a metrics endpoint.

**Comment by TommyStarK** [comment]
I am not promising anything but I'd like to give it a try even if I have no idea where to start and I am scared of k8s e2e tests 😅. If you don't mind I am going to assign myself, if someone comes with a PR faster, fair enough I need to try to learn :)

/assign

**Comment by logicalhan** [comment]
> I would expect all metrics to be registered before the server reports healthy (making other requests should not be required).

By "registered", I'm interpreting you to mean that registered metrics should be emitted by the binary. If so, this is not a valid assumption. Take for instance, our deprecated api metric, which logs each occurance of a deprecated API usage. If no deprecated APIs are hit, this metric simply won't appear for scrape. 

Because of this nuance, I'm not sure that an e2e test to verify all registered metrics actually show up is a valid request.

**Comment by logicalhan** [comment]
> If I do understand what you explained @logicalhan, registering metrics, booting the apiserver within an e2e test isn't going to validate metrics are actually showing up unless we hit the API ? to be able to validate metrics are properly emitted we must send request towards the api (in a logical and thoughtful manner to ensure that the targeted metrics have been recorded and emitted correctly). Did I understand correctly ?


Metrics will not show up unless they actually have measured something. Metrics are lazily instantiated, which means if the thing which they are measuring has not yet happened, the metric will not show up in the /metrics endpoint.

**Comment by TommyStarK** [comment]
ok understood thank you. I assume during the run of e2e tests for the apiserver, requests are to be sent to the server and thus some things measured by these metrics happen. We might be able to verify that these metrics show up in the /metrics endpoint. It won't cover all metrics but at least a part of them

**Comment by logicalhan** [comment]
> ok understood thank you. I assume during the run of e2e tests for the apiserver, requests are to be sent to the server and thus some things measured by these metrics happen. 

You can't be guaranteed that those things happen though, and therefore this test will be at best flaky.

**Comment by TommyStarK** [comment]
ok perfectly clear. As of now I am not sure this is a good first issue for a new contributor like me unless there is a well defined strategy to validate those metrics and we can guarantee the things we want to measure did happen

**Comment by Adaminite** [comment]
@aojea Is there anyone currently working on this issue? Also, is this still a good issue for new contributors?

**Comment by logicalhan** [comment]
I don't really think this is feasible due to the lazy instantiation of metrics.

**Comment by logicalhan** [comment]
/close

(due to infeasibility)

**Comment by aojea** [comment]
> @aojea Is there anyone currently working on this issue? Also, is this still a good issue for new contributors?

nobody working on it, it can be a good issues for new contributors, but you should expect some work to understand how e2e tests works and how to better test this feature
