### ISSUE TITLE
Scheduler did not receive scheduled pods add events

### ISSUE THREAD

**Issue by xrmzju** [kubernetes/kubernetes#117497]
### What happened?

1. I have a not got a lot of pod crash into ContainerStatusUnknown state for kubelet admit failed in resource admit 
``` 
samkdeploy-59874db686-p75s2                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-p7fv5                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-pbblr                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-pbd8j                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-pxbpc                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-q8pdc                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qd5vp                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qn4jf                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qn7tg                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qnfgt                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qnjwp                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-qtfsg                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-r42rq                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-r442v                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-r6hpm                                       0/1     ContainerStatusUnknown   0             19h
samkdeploy-59874db686-r842f                                       0/1     ContainerStatusUnknown   0             19h
```
2.  Dump the scheduler cache and check the pod on the node, found one of the pod missed in the cache.
3.  check the scheduler log, it reports update cache failed. and we can see after the pod bound success, it received a update event for pod directly [L206](https://github.com/kubernetes/kubernetes/blob/0afa60086a0fc0b5bf6386e16732a373ad9a10b6/pkg/scheduler/eventhandlers.go#L206), instead of a scheduled pod add event,  because pod  is not added to scheduler cache, so cannot be updated, thus pod never got a chance to add to cache.
``` 
I0419 11:36:09.601732       1 default_binder.go:52] "Attempting to bind pod to node" pod="default/sts-web-0" node="node1"
I0419 11:36:09.618153       1 cache.go:831] Couldn't expire cache for pod default/sts-web-0. Binding is still in progress.
I0419 11:36:09.627435       1 round_trippers.go:454] POST https://kubernetes-apiserver:6443/api/v1/namespaces/default/pods/sts-web-0/binding 201 Created in 14 milliseconds
I0419 11:36:09.628955       1 cache.go:389] Finished binding for pod af74836a-673c-4797-b27e-42d5c4370a82. Can be expired.
I0419 11:36:09.629007       1 scheduler.go:758] "Successfully bound pod to node" pod="default/sts-web-0" node="node1" evaluatedNodes=5 feasibleNodes=1
**I0419 11:36:09.629303       1 eventhandlers.go:232] Update event for scheduled pod default/sts-web-0**
E0419 11:36:09.630274       1 eventhandlers.go:239] "Scheduler cache UpdatePod failed" err="pod af74836a-673c-4797-b27e-42d5c4370a82 is not added to scheduler cache, so cannot be updated" oldPod="default/sts-web-0" newPod="default/sts-web-0"
I0419 11:36:09.648846       1 eventhandlers.go:232] Update event for scheduled pod default/sts-web-0
E0419 11:36:09.650159       1 eventhandlers.go:239] "Scheduler cache UpdatePod failed" err="pod af74836a-673c-4797-b27e-42d5c4370a82 is not added to scheduler cache, so cannot be updated" oldPod="default/sts-web-0" newPod="default/sts-web-0"
I0419 11:36:09.656015       1 eventhandlers.go:232] Update event for scheduled pod default/sts-web-0
E0419 11:36:09.656062       1 eventhandlers.go:239] "Scheduler cache UpdatePod failed" err="pod af74836a-673c-4797-b27e-42d5c4370a82 is not added to scheduler cache, so cannot be updated" oldPod="default/sts-web-0" newPod="default/sts-web-0"
```

### What did you expect to happen?

1. It is possible for pods to be successfully added to the scheduler cache.
2. If we miss the pod's add event, we should have a mechanism in place to ensure that successfully scheduled pods are added to the cache.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure yet

### Kubernetes version

v1.22.5

### Cloud provider

No

### OS version

linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by AxeZhan** [comment]
> It is possible for pods to be successfully added to the scheduler cache.

Do you have the log why this pod is **not** added to scheduler cache?

**Comment by ahg-g** [comment]
1.22 is out of support unfortunately, any chance you can test again on a new version?

This being a statefulset (meaning the pods will have the exact same name) raises some concerns. Any idea if those pods where deleted and recreated when the problem was observed?

Note that in https://github.com/kubernetes/kubernetes/issues/105261 we added some checks on uid to ensure that the exact pod is being bound, this could be related.

**Comment by xrmzju** [comment]
> > It is possible for pods to be successfully added to the scheduler cache.
> 
> Do you have the log why this pod is **not** added to scheduler cache?

the root cause is no add event bumped in the scheduler log, so there is no log why this pod is not added to scheduler cache, only logs why update cache failed.

**Comment by xrmzju** [comment]
> 1.22 is out of support unfortunately, any chance you can test again on a new version?

regrettably, I have been unsuccessful in my attempts to replicate it in my current environment. However, it has occurred sporadically over the past several months.
> This being a statefulset (meaning the pods will have the exact same name) raises some concerns. Any idea if those pods where deleted and recreated when the problem was observed?
> 
> Note that in #105261 we added some checks on uid to ensure that the exact pod is being bound, this could be related.

I already checked the audit log of kube-apiserver and did not see any deleting events with the same stateful pod. so i don't think it's the same issue.  i'll continue to dig into the problem, and my another thought is: currently, the accuracy of the scheduler cache relies solely on the informer events. Do you think we should implement an additional method, such as periodic rsync, to guarantee the integrity of the scheduler cache?

**Comment by ahg-g** [comment]
>  I have been unsuccessful in my attempts to replicate it in my current environment. However, it has occurred sporadically over the past several months.

happened sporadically on newer k8s versions or only on 1.22?

>  the accuracy of the scheduler cache relies solely on the informer events. Do you think we should implement an additional method, such as periodic rsync, to guarantee the integrity of the scheduler cache?

Not really, we should be receiving an add event for sure, if we are not receiving that, something is wrong for sure.

**Comment by olderTaoist** [comment]
> I already checked the audit log of kube-apiserver and did not see any deleting events with the same stateful pod. so i don't think it's the same issue. i'll continue to dig into the problem, and my another thought is: currently, the accuracy of the scheduler cache relies solely on the informer events. Do you think we should implement an additional method, such as periodic rsync, to guarantee the integrity of the scheduler cache?

the resync period is set zero [L310](https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-scheduler/app/options/options.go#L310)，besides Informer resync just trigger update event。

**Comment by ingvagabund** [comment]
We have a case where a scheduler cache keeps duplicates of the same pod with different UIDs. The pod is owned by a stateful set. Cache dumped in the scheduler logs (after changing the node, pod and ns names):
```
        Node name: A
        name: POD, namespace: NS, uid: 3d429642-b551-4bcc-9ba1-5bba1f8e25d0, phase: Pending, nominated node:
        Node name: B
        name: POD, namespace: NS, uid: c3070d97-cfde-4209-a088-cf21c55b7e93, phase: Pending, nominated node:
        Node name: C
        name: POD, namespace: NS, uid: eae48425-e68f-45c0-83f6-a637f781c3ea, phase: Pending, nominated node:
        Node name: D
        name: POD, namespace: NS, uid: c2362726-16ca-4dea-a7ae-561ced077764, phase: Pending, nominated node:
        Node name: E
        name: POD, namespace: NS, uid: 3b253d53-3fc3-4a55-b330-be7596536335, phase: Pending, nominated node:
```
The pending pod NS/POD exists in a cluster. Yet, it is not scheduled due to insufficient resources which are claimed by other duplicates pods (probably again owned by SS? can't prove it for now) which are no longer present in the cluster. Is it possible that a stateful set pod gets updated, the uid changes but no delete event is generated for the older uid? Thus, leaving non-existing pending pods indefinitely until a scheduler instance restarts?

**Comment by lance5890** [comment]
> > 1.22 is out of support unfortunately, any chance you can test again on a new version?
> 
> regrettably, I have been unsuccessful in my attempts to replicate it in my current environment. However, it has occurred sporadically over the past several months.
> 
> > This being a statefulset (meaning the pods will have the exact same name) raises some concerns. Any idea if those pods where deleted and recreated when the problem was observed?
> > Note that in #105261 we added some checks on uid to ensure that the exact pod is being bound, this could be related.
> 
> I already checked the audit log of kube-apiserver and did not see any deleting events with the same stateful pod. so i don't think it's the same issue. i'll continue to dig into the problem, and my another thought is: currently, the accuracy of the scheduler cache relies solely on the informer events. Do you think we should implement an additional method, such as periodic rsync, to guarantee the integrity of the scheduler cache?

Do u have any other schedulers, other than the default-scheduler, if so, the default-scheduler will not get these create events
