### ISSUE TITLE
how can we get  lastOpTimestamp field in the ObjectMeta to show the resource operation

### ISSUE THREAD

**Issue by someview** [kubernetes/kubernetes#117432]
### What would you like to be added?

current ObjectMeta:

CreationTimestamp Time `json:"creationTimestamp,omitempty" protobuf:"bytes,8,opt,name=creationTimestamp"`

// DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This
// field is set by the server when a graceful deletion is requested by the user, and is not
// directly settable by a client. The resource is expected to be deleted (no longer visible
// from resource lists, and not reachable by name) after the time in this field, once the
// finalizers list is empty. As long as the finalizers list contains items, deletion is blocked.
// Once the deletionTimestamp is set, this value may not be unset or be set further into the
// future, although it may be shortened or the resource may be deleted prior to this time.
// For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react
// by sending a graceful termination signal to the containers in the pod. After that 30 seconds,
// the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup,
// remove the pod from the API. In the presence of network partitions, this object may still
// exist after this timestamp, until an administrator or automated process can determine the
// resource is fully terminated.
// If not set, graceful deletion of the object has not been requested.
//
// Populated by the system when a graceful deletion is requested.
// Read-only.
// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
// +optional
DeletionTimestamp *Time `json:"deletionTimestamp,omitempty" protobuf:"bytes,9,opt,name=deletionTimestamp"`
```

There seems no fields to indicate add event timestamp or  modified event timestamp. How can we get lastOpTimestamp on the resource,eg: endpoints of some service.

### Why is this needed?

We want to know the last operation time on a source ,not updatetime, createtime, deletetimetime, but just opTime and optype to
express this.
```
// ObejctMeta {
    lastOpTime time.time
}
```

**Comment by smarterclayton** [comment]
This is a very old decision not to include last modification time - see [Add mtime to ObjectMeta](https://github.com/kubernetes/kubernetes/issues/12430) for more context.

**Comment by fengyeall111** [comment]
> This is a very old decision not to include last modification time - see [Add mtime to ObjectMeta](https://github.com/kubernetes/kubernetes/issues/12430) for more context. Using server side apply you should see the changes. Using a webhook you can record this info in your own system. Using audit logs you can see all changes and who made them.
> 
> I think we are unlikely to add modified time directly to objects, so please comment on whether the alternates satisfy your use case.

In some cases we need this field.eg: 
-  a api-server proxy service to offer some api,using watcher to get source and store it  locally
-  other service visiting the proxy to get latest endpoints
 It is possible that data may be inconsistent between different proxy pod. So how can the service get the lastest information about some source by different proxy pod ? a mtime filed can resolve this.
Now, the objectMeata has a managerfileds filed.But actually, user may just care the last mtime , not all workflow

**Comment by fengyeall111** [comment]
Now in our project ，in k8s , chain like this: serviceA->apiproxy-> apiserver ，serviceA get real endpoints records, so it can decide 
visit one of them.However,apiproxy is a deployment application. for serviceA, it's can get different endpoints record since apiproxy may hva not consist data. If the source has a field updatetime or version,the problem will be solved.

**Comment by alexzielenski** [comment]
> If the source has a field updatetime or version,the problem will be solved.

If a version that changes with updates is all you need, `ResourceVersion` field may solve the issue for you. We are very unlikely to add modification time. I am closing this issue as unplanned since we don't have more details about why the alternatives linked by @smarterclayton don't work four specific use case. Feel free to re-open if you have a concrete example where adding this field required to solve the problem.

/triage accepted
/close
