### ISSUE TITLE
Are there any documents available on HPA benchmarking?

### ISSUE THREAD

**Issue by jwcesign** [kubernetes/kubernetes#117454]
### Asking for help? Comment out what you need so we can get more information to help you!

Cluster information:
* Kubernetes version: v1.25.0
* Cloud being used: (put bare-metal if not on a public cloud) bare-metal
* Installation method: kind
* Host OS: Ubuntu 20.04
* CNI and version: none
* CRI and version: none

I want to ask if there are any docs showing the benchmark of HPA.
For example:
* If there are 1k/10k/20k pods, how fast is it for scaling up/down?
* How much the memory/CPU will be cost for HPA calculation if there are 1k/10k/20k pods?

**Comment by jwcesign** [comment]
cc @bart0sh

**Comment by pbetkier** [comment]
There are no docs that I'm aware of.

What do you mean by "how fast is it for scaling up/down"? Unless HPA controller is overloaded (and you can read a bit on scalability limits [here](https://cloud.google.com/kubernetes-engine/docs/concepts/horizontalpodautoscaler#scalability), they should apply to non-GKE as well) then each HPA is processed every 15s. So if the metrics justify change of scale (e.g. for CPU/memory it's coming from metrics-server that operates on 30s windows) then after max. 15s the scale target (e.g. Deployment) will get rescaled through API server. Then it's about Pod scheduling and Pod actually starting and ready to serve.

If you can describe what you need this benchmark for then maybe I can help more.

**Comment by jwcesign** [comment]
Hi, thanks for replying @pbetkier 

The benchmark that I am looking for is:
* What are the CPU and memory costs for calculating and scaling with varying numbers of metrics (such as 20,000 pods)?

**Comment by pbetkier** [comment]
Oh I see. I'm pretty sure there are no such benchmarks.
