### ISSUE TITLE
Removing "Try our interactive tutorial." from base readme page 

### ISSUE THREAD

**Issue by tripathysagar** [kubernetes/kubernetes#117460]
Hello,

Upon visiting the [readme](https://github.com/kubernetes/kubernetes#to-start-using-k8s). There is a link for interactive tutorial which is being inactive. Error from (k8 page)[https://kubernetes.io/docs/tutorials/kubernetes-basics/] is 
![image](https://user-images.githubusercontent.com/54429599/233017144-2e478190-2ac8-4041-8597-342375262f8a.png)

We have to remove the page link.

**Comment by tripathysagar** [comment]
label:sig/docs

**Comment by BenTheElder** [comment]
Per https://kubernetes.slack.com/archives/C1J0BPD2M/p1681918348468789 let's delete this reference for now and we can add something later potentially following https://github.com/kubernetes/website/discussions/38878

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/kubernetes/pull/117484
