### ISSUE TITLE
Debugging Profile dosen't work well with PSA

### ISSUE THREAD

**Issue by mochizuki875** [kubernetes/kubernetes#117405]
### What happened?

I attempted to use `Ephemeral Container`(`kubectl debug`) with `PodSecurity Admission`, but it failed.(related #117130)   
And I found [kubectl debug option](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#debugging-profiles) `--profile`, so I tried again with it.  
But it was not work well.  

### What did you expect to happen?

Success to use `Ephemeral Container` with restriction of `PodSecurity Admission`.

### How can we reproduce it (as minimally and precisely as possible)?

First, create `Namespace` with restriction of `PodSecurity Admission`.  
In this case, set `pod-security.kubernetes.io/enforce: restricted`.

<details>

`psa-ns.yaml`

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: psa-ns
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: v1.27
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: v1.27
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: v1.27
```

</details>

```concole
$ kubectl apply -f psa-ns.yaml
```

Create the `Pod` that comply with the restrict policy.

<details>

`ubuntu-restricted.yaml`

```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu-restricted
  namespace: psa-ns
spec:
  containers:
  - image: ghcr.io/mochizuki875/ubuntu:22.04-runas
    name: ubuntu
    securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        capabilities:
          drop: 
          - "ALL"
          add:
          - "NET_BIND_SERVICE"
        seccompProfile:
            type: RuntimeDefault
```

The image `ghcr.io/mochizuki875/ubuntu:22.04-runas` is created by this `Dockerfile`.
```Dockerfile
FROM ubuntu:22.04
RUN useradd -m -u 1000 user01
USER user01
WORKDIR /home/user01
CMD ["/bin/sh", "-c", "while :; do sleep 10; done"]
```

</details>

```concole
$ kubectl apply -f ubuntu-restricted.yaml
pod/ubuntu-restricted created

$ kubectl get po -n psa-ns 
NAME                READY   STATUS    RESTARTS   AGE
ubuntu-restricted   1/1     Running   0          36s
```

Run `kubectl debug` without `--profile`.
```console
$ kubectl -n psa-ns debug -it ubuntu-restricted  --image=busybox:1.28 --target=ubuntu
Targeting container "ubuntu". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-kdcf9.
Error from server (Forbidden): pods "ubuntu-restricted" is forbidden: violates PodSecurity "restricted:v1.27": allowPrivilegeEscalation != false (container "debugger-kdcf9" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "debugger-kdcf9" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "debugger-kdcf9" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "debugger-kdcf9" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

Run `kubectl debug` with `--profile=restricted`.  
The number of errors has decreased by using `--profile=restricted`, but it still fails.
```console
$ kubectl -n psa-ns debug -it ubuntu-restricted  --image=busybox:1.28 --target=ubuntu --profile=restricted
Targeting container "ubuntu". If you don't see processes from this container it may be because the container runtime doesn't support this feature.
Defaulting debug container name to debugger-s57zc.
Error from server (Forbidden): pods "ubuntu-restricted" is forbidden: violates PodSecurity "restricted:v1.27": allowPrivilegeEscalation != false (container "debugger-s57zc" must set securityContext.allowPrivilegeEscalation=false), seccompProfile (pod or container "debugger-s57zc" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

### Anything else we need to know?

- [kubectl debug: allow users to specify debugging profile](https://github.com/kubernetes/kubectl/issues/1108)
- #114280
- #117130 

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none(on premise)
</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


$ uname -a
Linux ubuntu-server01 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```console
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:20:04Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
# containerd --version
containerd containerd.io 1.6.20 2806fc1057397dbaeefbea0e4e17bddfbd388f38
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
You can't add an ephemeral container that's able to debug a peer container in a namespace that is enforcing the _restricted_ Pod security standard.

I don't think that's a bug though. That's more a facet of the limitations that come with using _restricted_.

For now (another contributor is welcome to revert this):
/remove-kind bug

**Comment by sftim** [comment]
Relevant to https://github.com/kubernetes/kubernetes/pull/114280

**Comment by mochizuki875** [comment]
@sftim 
Thanks your reply.

> You can't add an ephemeral container that's able to debug a peer container in a namespace that is enforcing the restricted Pod security standard.

OK.  
To accommodate this, I used [kubectl debug option](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#debugging-profiles) `--profile`, but it dose't work well...  
Isn't this a bug?

I understand that `--profile restricted`  makes Ephemeral Container comply with the restricted policy.( #114280 )  
Is this wrong?

**Comment by mochizuki875** [comment]
I found that the restricted profile is defined here and apply to container.  
 
 https://github.com/kubernetes/kubernetes/blob/8bba479f03fd27f1a54fcd1e02347c1a5b98b30c/staging/src/k8s.io/kubectl/pkg/cmd/debug/profiles.go#L170-L189
 
 
 But, it seems that the following fields specified in [Pod Security Standard 's restricted policy](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) are not configured. 
 
 - `securityContext.allowPrivilegeEscalation`
 - `spec.securityContext.seccompProfile`
 
 I tried adding the logic to configure the above as a test, and it seems to work fine.
