### ISSUE TITLE
Infinite Loop in nodeipam rangeAllocator

### ISSUE THREAD

**Issue by learnitall** [kubernetes/kubernetes#117487]
### What happened?

I was performing a scale test with [kwok](github.com/kubernetes-sigs/kwok) by creating a lot of kwok nodes, waiting until they were ready, and then deleting them right after. I noticed that after the test was done, my laptop's CPU usage was sitting very high. After looking through the kubernetes-apiserver logs, I came across an infinite loop in the node IPAM rangeAllocator. Essentially, if a node is sitting in the rangeAllocator's `nodeCIDRUpdateChannel` work queue and deleted before the work item is consumed, the node will forever sit in the work queue. Here is the flow:

1. A worker pulls a node from the work queue [range_allocator.go#L196](https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L196):

```go
func (r *rangeAllocator) worker(ctx context.Context) {
	logger := klog.FromContext(ctx)
	for {
		select {
		case workItem, ok := <-r.nodeCIDRUpdateChannel:
```

2. The worker calls [updateCIDRsAllocation](https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L338) with the node. If the method returns an error, the node is placed back into the work queue [range_allocator.go#L201](https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L201):

```go
			if err := r.updateCIDRsAllocation(logger, workItem); err != nil {
				// Requeue the failed node for update again.
				r.nodeCIDRUpdateChannel <- workItem
			}
```

3. `updateCIDRsAllocation` makes a call to the rangeAllocator's NodeLister to get a reference to the node [range_allocater.go#L343](https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L343):

```go
	node, err = r.nodeLister.Get(data.nodeName)
	if err != nil {
		logger.Error(err, "Failed while getting node for updating Node.Spec.PodCIDRs", "node", klog.KRef("", data.nodeName))
		return err
	}
```

If the node is not populated in the nodeLister, then an error is returned from `updateCIDRsAllocation` and the node is put back into `nodeCIDRUpdateChannel` by the worker. The same node can be consumed again by the worker. If the node is never added to the nodeLister, the node will persist in the work queue forever.

This will cause a spike in CPU usage because the worker will continue to try and consume the node as fast as possible since there is no delay in processing items from the work queue. Additionally, this will spam log files, as each time the worker fails to process the missing node, an error log is produced.

I think that this could be fixed with a little patch that checks if the err returned from `nodeLister.Get` is a `NewNotFound` error, something like:

```diff
diff --git a/pkg/controller/nodeipam/ipam/range_allocator.go b/pkg/controller/nodeipam/ipam/range_allocator.go
index 47bd392e234..dbdbc0da0ee 100644
--- a/pkg/controller/nodeipam/ipam/range_allocator.go
+++ b/pkg/controller/nodeipam/ipam/range_allocator.go
@@ -342,6 +342,13 @@ func (r *rangeAllocator) updateCIDRsAllocation(logger klog.Logger, data nodeRese
        cidrsString := ipnetToStringList(data.allocatedCIDRs)
        node, err = r.nodeLister.Get(data.nodeName)
        if err != nil {
+               if apierrors.IsNotFound(err) {
+                       logger.V(4).Info("Cannot find node but it is still in the CIDR allocation work queue, dropping", "nodeName", data.nodeName)
+                       r.removeNodeFromProcessing(data.nodeName)
+
+                       return nil
+               }
+
                logger.Error(err, "Failed while getting node for updating Node.Spec.PodCIDRs", "node", klog.KRef("", data.nodeName))
                return err
        }
```

### What did you expect to happen?

After a node is deleted from the cluster, the node ipam rangeAllocator drops the node from its updateCIDR work queue.

### How can we reproduce it (as minimally and precisely as possible)?

Recreating this using an actual cluster is a bit tricky, but it is simple to create a quick go program to reproduce the issue. Placing this in a new directory under the source tree and running it will reproduce the issue:

```go
package main

import (
	"context"
	"net"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/informers"
	"k8s.io/client-go/kubernetes/fake"
	"k8s.io/klog/v2"
	"k8s.io/kubernetes/pkg/controller"
	"k8s.io/kubernetes/pkg/controller/nodeipam/ipam"
	netutils "k8s.io/utils/net"
)

func main() {
	ctx := context.Background()
	logger := klog.FromContext(ctx)

	// Create a fake node.
	node := &v1.Node{
		ObjectMeta: metav1.ObjectMeta{
			Name: "node0",
		},
	}

	// Create a fake clientset.
	clientset := fake.NewSimpleClientset()
	fakeNodeHandler := clientset.CoreV1().Nodes()

	// Start an informer and run it to get a cache sync.
	informerFactory := informers.NewSharedInformerFactory(clientset, controller.NoResyncPeriodFunc())
	fakeNodeInformer := informerFactory.Core().V1().Nodes()
	go fakeNodeInformer.Informer().Run(make(<-chan struct{}))

	// Now create the new range allocator
	allocatorParams := ipam.CIDRAllocatorParams{
		ClusterCIDRs: func() []*net.IPNet {
			_, clusterCIDRv4, _ := netutils.ParseCIDRSloppy("10.10.0.0/16")
			return []*net.IPNet{clusterCIDRv4}
		}(),
		ServiceCIDR:          nil,
		SecondaryServiceCIDR: nil,
		NodeCIDRMaskSizes:    []int{24},
	}

	ra, err := ipam.NewCIDRRangeAllocator(logger, clientset, fakeNodeInformer, allocatorParams, nil)
	if err != nil {
		panic(err)
	}

	// Create our fake node and add a new allocation request for our fake node.
	// This would happen for a node which is created after the call to NewCIDRRangeAllocator,
	// see: https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L132
	fakeNodeHandler.Create(context.TODO(), node, metav1.CreateOptions{})
	if err := ra.AllocateOrOccupyCIDR(logger, node); err != nil {
		panic(err)
	}

	// Delete the node and then start the ra. The fake node still persists in the ra's work queue.
	// This would simulate a situation where:
	// 1. A bunch of new nodes are added and the ra's work queue is back-logged.
	// 2. Before a worker for the ra can handle a newly added node in the queue, the node is deleted.
	// When a node is deleted, it isn't removed from the work queue. For reference, when a node is
	// deleted, this function is called: https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/controller/nodeipam/ipam/range_allocator.go#L290
	if err := fakeNodeHandler.Delete(context.TODO(), "node0", metav1.DeleteOptions{}); err != nil {
		panic(err)
	}

	// Now start the range allocator and observe the infinite logs for node0.
	ra.Run(ctx)
}
```

### Kubernetes version

The above code for reproducing the issue was written for v1.27.1.

### Cloud provider

n/a

### OS version

n/a

### Install tools

n/a

### Container runtime (CRI) and version (if applicable)

n/a

### Related plugins (CNI, CSI, ...) and versions (if applicable)

n/a

**Comment by thockin** [comment]
@sarveshr7 @aojea

**Comment by shaneutt** [comment]
ping @aojea after discussing in the SIG Network sync today: at least one relevant controller has been refactored so far.

/triage accepted

**Comment by aojea** [comment]
@learnitall or anybody interested, if we want to solve this I prefer to move the controller to use worqueue and abandon the channels, I did the same for the other controller that inherited this architecture with channels
 https://github.com/kubernetes/kubernetes/pull/115529

/help

**Comment by MirrorShih** [comment]
I'm interested, I can help to fix this.
