### ISSUE TITLE
util_window_test.go doesn't import os/net

### ISSUE THREAD

**Issue by tukwila** [kubernetes/kubernetes#117498]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648849344847155200

### Which tests are failing?

``` 
# k8s.io/kubernetes/pkg/kubelet/util [k8s.io/kubernetes/pkg/kubelet/util.test]
pkg\kubelet\util\util_windows_test.go:211:12: undefined: os
pkg\kubelet\util\util_windows_test.go:230:2: undefined: os
pkg\kubelet\util\util_windows_test.go:231:13: undefined: net
pkg\kubelet\util\util_windows_test.go:233:17: undefined: net
✓  pkg/kubelet/userns (393ms)
WARN invalid TestEvent: FAIL	k8s.io/kubernetes/pkg/kubelet/util [build failed]
bad output from test2json: FAIL	k8s.io/kubernetes/pkg/kubelet/util [build failed]
``` 

### Since when has it been failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648849344847155200
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648668147974148096
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1648305599462510592
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1647943079375671296
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit-windows-master/1647580687638728704

### Testgrid link

https://testgrid.k8s.io/sig-windows-signal#windows-unit-master

### Relevant SIG(s)

/sig windows
/kind failing-test

**Comment by tukwila** [comment]
@jayunit100 @jsturtevant @marosset i think this problem can be fixed when it imports os/net in kubernetes/pkg/kubelet/util/util_windows_test.go. Am i right?  

import (
	"fmt"
	"math/rand"
	"reflect"
	"runtime"
	"sync"
	"testing"
	"time"
	"os"
	"net"

	winio "github.com/Microsoft/go-winio"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

**Comment by iyear** [comment]
I also found some other unit test bugs in CI, such as running linux-related tests under windows.

I will try to fix them.

/assign

**Comment by claudiubelu** [comment]
Thanks for opening the issue! I didn't notice the failure through the testgrid dashboard. I've sent a PR here: https://github.com/kubernetes/kubernetes/pull/117616 . While fixing this issue, I noticed there's one unit test that was failing, so that PR also addresses that as well.
