### ISSUE TITLE
kubectl drain --once

### ISSUE THREAD

**Issue by grosser** [kubernetes/kubernetes#117492]
I want `drain` to try each pod exactly once.

Examples:
- allow to control drain from outside of kubectl by having an external timer that for example restarts drain every x minutes
- allow evicting all pods once when a node needs to be shutdown immediately
- allow unit-testing what drain does by running it once and then testing the cluster state

**Comment by mpuckett159** [comment]
/triage needs-information

https://kubernetes.io/images/docs/kubectl_drain.svg
This workflow document illustrates the process that kubectl drain uses to drain a node. According to this doc drain only tries to delete each pod once. Do you mean that you do not wish the node to be cordoned during the drain process?

**Comment by grosser** [comment]
image is wrong, it retries when a PDB blocks eviction

```
kubectl drain ip-1.2.3.4.us-west-2.compute.internal --ignore-daemonsets --delete-emptydir-data
error when evicting pods/"truth-service-app-server-5fdb448964-878vz" -n "truth-service" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
pod/app-server-85d6d9547f-4hrkb evicted
evicting pod truth-service/truth-service-app-server-5fdb448964-878vz
error when evicting pods/"truth-service-app-server-5fdb448964-878vz" -n "truth-service" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
...
```

**Comment by mpuckett159** [comment]
Ah yeah when PDB is involved it's different. Can you set a timeout of 1 second? That will effectively be "try it once" I believe.

**Comment by grosser** [comment]
yeah true that should be good enough
