### ISSUE TITLE
Persistent services, replication controllers and pods

### ISSUE THREAD

**Issue by F21** [kubernetes/kubernetes#11744]
I am currently running kubernetes on top of mesos in a development cluster using some VMs. One of the things I am interested in is persistent services, replication controllers and pods. 

Currently, if I deploy a service, replication controller or pod and reboot the whole cluster, all my deployments are lost. I would need to run `kubectl create ...` to recreate them.

That means, if a kubenetes cluster loses power, there needs to be some mechanism to recreate those pods, services and rcs when it comes back up.

Are there any plans to put those things into long term persistence so that when the whole cluster is restarted, the pods, rcs and services can automatically come back up?

I think this would also be quite useful to allow upgrade the scheduler and the various components easily.

xref https://github.com/mesosphere/kubernetes-mesos/issues/446

**Comment by vishh** [comment]
Replicating the master is an ongoing effort. Take a look at #473

**Comment by karlkfi** [comment]
IIRC Mesos defaults to keeping it's state in `/tmp`, which doesn't survive restarts on some OSes. You may need to configure that location to be somewhere else. It should auto-reschedule running tasks after a restart. Tho it also kinda depends on how you're starting up the k8s core components. They'll either need to be in Marathon or set up in upstart (or similar) to come up on boot.

**Comment by jdef** [comment]
The k8s-mesos cluster state is stored in etcd, just as in stock k8s. The mesos state that's stored in /tmp by default is for the mesos task sandbox. Cluster deployment state is not saved there.
