### ISSUE TITLE
LocationOfOrigin shows up unexpectedly

### ISSUE THREAD

**Issue by howardjohn** [kubernetes/kubernetes#117567]
### What happened?

yaml.Marshal a kubeconfig, as done in the example tests here https://pkg.go.dev/k8s.io/client-go/tools/clientcmd/api

### What did you expect to happen?

LocationOfOrigin is not seen in output, as comment says "never serialized."

### How can we reproduce it (as minimally and precisely as possible)?

Click "run example"

### Anything else we need to know?

`kubectl config view` doesn't suffer from this as it does some conversion

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by deads2k** [comment]
https://pkg.go.dev/k8s.io/client-go/tools/clientcmd/api is what's known as internal type.  It is not intended to be serialized by code.  The serialization version is in https://pkg.go.dev/k8s.io/client-go/tools/clientcmd/api/v1 and does not have this field.

I could get behind removing all json tags from the internal version, but I wouldn't refine tags that shouldn't be used.
