### ISSUE TITLE
node.kubernetes.io/exclude-disruption label doesn't work

### ISSUE THREAD

**Issue by smilewhxlucky** [kubernetes/kubernetes#117518]
### What happened?

After setting the label 【node.kubernetes.io/exclude-disruption】for vk node. when the node is not ready, the pod on it is still evicted.

### What did you expect to happen?

The pod on the vk node is not evicted.

### How can we reproduce it (as minimally and precisely as possible)?

1. label vk node node.kubernetes.io/exclude-disruption=true
2. deploy pod on the vk node
3. stop vk
4. check if the pod is evicted

### Kubernetes version

<details>

```console
$ kubectl version v1.22.5
# paste output here
```

</details>

### Cloud provider

...

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig architecture

> NodeDisruptionExclusion: Enable use of the Node label `node.kubernetes.io/exclude-disruption` which prevents nodes from being evacuated during zone failures.

https://github.com/kubernetes/kubernetes/blob/08755fe2490beb91b5c2866c3413dec043fd72f9/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L722-L728

This seems to take effects only for zone.

/cc @smarterclayton

**Comment by pacoxu** [comment]
BTW, I think we should add some introductions in https://kubernetes.io/docs/reference/labels-annotations-taints/.

**Comment by smilewhxlucky** [comment]
@pacoxu 
What is the applicable scene of the node.kubernetes.io/exclude-disruption label?
If a node has this label, the node will be excluded when calculating the availability zone status。However, the node is counted in the expulsion

**Comment by smilewhxlucky** [comment]
I don't know which scenario the node.kubernetes.io/exclude-disruption  label applies to.

**Comment by pacoxu** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates-removed/

> Enable use of the Node label node.kubernetes.io/exclude-disruption which prevents nodes from being evacuated during zone failures.

As I know, this takes effect when you are using PartialDisruption or FullDisruption. kube-controller manager will calculate the zone status and the label  `node.kubernetes.io/exclude-disruption` will help to prevent it from being evacuated. It will affect whether it's time to stop evictions.
