### ISSUE TITLE
Use of a third party library maintained by a Sanctioned Entity

### ISSUE THREAD

**Issue by RichardoC** [kubernetes/kubernetes#117553]
### What happened?

The [easyjson](https://github.com/mailru/easyjson) library is maintained by Mail.ru. This is owned by VK, which is owned by Gazprom Media, and thus is subject to EU and [USA Sanctions](https://sanctionssearch.ofac.treas.gov/Details.aspx?id=20296) 

This is a dependancy via [https://github.com/go-openapi/swag](https://github.com/go-openapi/swag/issues/68) which is used by the client-go library.

I suspect Kubernetes want to either fork easyjson, or migrate to a library that isn't maintained by a sanctioned entity.

I did attempt to report this via the process documented at <https://kubernetes.io/security> but didn't get a response for weeks.

### What did you expect to happen?

Kubernetes to rely on libraries that aren't maintained by entities subject to U.S.A. and E.U. sanctions

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Anything else we need to know?

N/A

### Kubernetes version

<details>

All modern versions, this appears in the go.mod of Kubernetes 1.15+

</details>

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by RichardoC** [comment]
/sig api-machinery given client-go relies on this.

**Comment by RichardoC** [comment]
/sig api-machinery 


Since client-go relies on this.

**Comment by dims** [comment]
What a tangled web we weave

![image](https://user-images.githubusercontent.com/23304/234050847-27a83cdc-24d3-4adc-b7cf-70fcf11a81b1.png)

**Comment by dims** [comment]
Also, @RichardoC please open an issue in https://github.com/cncf/foundation asking CNCF to put together a guidance for $TITLE and then we can follow that guidance in all projects. We should not be doing a one of thing just for k8s.

For example, i have one there https://github.com/cncf/foundation/issues/290

**Comment by BenTheElder** [comment]
x-ref: https://github.com/mailru/easyjson/issues/385

**Comment by BenTheElder** [comment]
https://github.com/cncf/foundation/issues/550#issuecomment-1522430333

Given CNCF guidance that this is not a problem, I don't think we'll be trying to remove this dependency, we'd have to convince all of the projects through which we transitively depend on this to also switch, which looks non-trivial in this case https://github.com/kubernetes/kubernetes/issues/117553#issuecomment-1520433492

We pin all dependencies and check the sources into vendor and build from those, reviewing the source code changes on dependency update PRs (more on that in the linked comment above).

If a package is unmaintained and lacking fixes, then we may attempt to remove it for that reason, but we don't appear to have any other known-issues here.

**Comment by dims** [comment]
https://github.com/mailru/easyjson seems to be unmaintained as well ... so more reason to at least track it
