### ISSUE TITLE
Stop the watcher when error occurs in TestInformerWatcherDeletedFinalStateUnknown

### ISSUE THREAD

**Issue by Mskxn** [kubernetes/kubernetes#117533]
### What happened?

In `TestInformerWatcherDeletedFinalStateUnknown`, when timeout or other error occurs, `t.fatal` is called. 
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/staging/src/k8s.io/client-go/tools/watch/informerwatcher_test.go#L320-L334
This will make current routine terminated and miss the `w.Stop`,
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/staging/src/k8s.io/client-go/tools/watch/informerwatcher_test.go#L351
 which will lead to some leak routines. For example, this routine will block at waiting for `StopChan`
https://github.com/kubernetes/kubernetes/blob/b1f901acf44f8adf69759db434690c2a8bdd616b/staging/src/k8s.io/client-go/tools/watch/informerwatcher.go#L143-L147

### What did you expect to happen?

No leak

### How can we reproduce it (as minimally and precisely as possible)?

make any of these errors happen

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nikzayn** [comment]
@Mskxn I would like to take this up!
