### ISSUE TITLE
remove KubeSchedulerConfiguration v1beta3

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#117556]
We've already got KubeSchedulerConfiguration v1. 
Thus, we can start to remove/deprecate the beta versions (v1beta2, v1beta3).

We have the deprecation notice of v1beta2 on the website. So, we can remove v1beta2 soon.
> Note: KubeSchedulerConfiguration [v1beta2](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta2/) is deprecated in v1.25 and will be removed in v1.26. Please migrate KubeSchedulerConfiguration to [v1beta3](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta3/) or [v1](https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1/) before upgrading Kubernetes to v1.25.
https://kubernetes.io/docs/reference/scheduling/config/

Regarding v1beta3, we ~~need to announce the deprecation in v1.28~~ already announced the deprecation of v1beta3 in the log ([ref](https://github.com/kubernetes/kubernetes/issues/117556#issuecomment-1520549594)), and we can remove it in v1.29.

/assign
/kind cleanup
/sig scheduling

**Comment by alculquicondor** [comment]
It's time :smiley: 
https://github.com/kubernetes/kubernetes/blob/1def77f05cf701439f027fb24b229d9696971323/cmd/kube-scheduler/app/options/configfile.go#L56-L59

**Comment by sanposhiho** [comment]
Great, I didn't notice v1beta3 has also been deprecated.
So, as log-ed, I'll work on removing v1beta2 in this release, and will remove v1beta3 in next release (v1.29).

**Comment by alculquicondor** [comment]
Thanks!

**Comment by kerthcet** [comment]
We do have a PR here https://github.com/kubernetes/kubernetes/pull/112038, but closed as not planned before.

**Comment by sanposhiho** [comment]
Cool, I didn't know that.
I'm happy to leave v1beta2 removal to @SataQiu if they wants. Otherwise I'll take over.

**Comment by SataQiu** [comment]
I have reopened #117649 to remove `v1beta2` API :)

**Comment by alculquicondor** [comment]
/retitle remove KubeSchedulerConfiguration v1beta3

We can do it in v1.29

**Comment by kerthcet** [comment]
We have removed the v1beta3, so close this issue.
/close
