### ISSUE TITLE
client-go/kubectl rejects discovery API responses with charset encoding info

### ISSUE THREAD

**Issue by erwinvaneyk** [kubernetes/kubernetes#117562]
We are using `client-go` (and `kubectl`) to interact with Kubernetes clusters behind a couple of proxy layers. One of these proxies completes the `Content-Type` headers to include character encoding details.

This was working fine until recently, when client-go/kubectl have started to fail when interacting with the discovery API. It seems that a recent change has made kubectl more restrictive of the content-type that it expects. I suspect that it is related to this commit: https://github.com/kubernetes/client-go/commit/25d5761bfa0603c77cf5efefb14fd2e63a03a773

For example, this is an error from a kubectl command:
```
...
E0422 16:28:02.626222   86629 memcache.go:265] couldn't get current server API group list: Unknown discovery response content-type: application/json; charset=utf-8
I0422 16:28:02.626258   86629 cached_discovery.go:120] skipped caching discovery info due to Unknown discovery response content-type: application/json; charset=utf-8
I0422 16:28:02.626346   86629 shortcut.go:100] Error loading discovery information: Unknown discovery response content-type: application/json; charset=utf-8
...
```

We can of course try to fix it on our end, removing that charset information. However, it is a valid content-type and the way kubectl is handling the content-type there seems like it is relying on implementation details of kube-apiserver (that it does not add metadata to the content-type). I propose to fix this issue in `kubectl`, by properly parsing and handling the content-type.

**Comment by apelisse** [comment]
Yep, the string comparison for the content-type is flimsy, let's address that. Thanks for the report!

**Comment by seans3** [comment]
The fix is being cherry-picked back to: 

`v1.27` : https://github.com/kubernetes/kubernetes/pull/117637
`v1.26`: https://github.com/kubernetes/kubernetes/pull/117638
