### ISSUE TITLE
jsonpath parser issue

### ISSUE THREAD

**Issue by Icarus9913** [kubernetes/kubernetes#117579]
### What happened?

I defined a CRD and custom its PrinterColumns but got no data. I checked the JSONPath with the Online Evaluator successfully. So I'm not sure whether there's a bug in kubernetes JSONPath parser. 

And I also write down a unit test following the [jsonpath_test.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/jsonpath/jsonpath_test.go) but failed.

This is my json:
```json
{
    "spec": {
        "first": {
            "second": {
                "a/b": "data",
		"person.name": "icarus",
		"a.com/b.com": "result"
            }
        }
    }
}
```

And with the JSONPath:
```shell
$.spec.first.second.['a/b']
$.spec.first.second.['person.name']
$.spec.first.second.['a.com/b.com']
```

### What did you expect to happen?

I expect to use JSONPath `$.spec.first.second.['a.com/b.com']` to get response `result`

### How can we reproduce it (as minimally and precisely as possible)?

just following the json path unit test [jsonpath_test.go](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/util/jsonpath/jsonpath_test.go)

```go
func TestJSONInputDemo(t *testing.T) {
	var pointsJSON = []byte(`{
    "spec": {
        "first": {
            "second": {
                "a/b": "data",
				"person.name": "icarus",
				"a.com/b.com": "result"
            }
        }
    }
}`)
	var pointsData interface{}
	err := json.Unmarshal(pointsJSON, &pointsData)
	if err != nil {
		t.Error(err)
	}
	pointsTests := []jsonpathTest{
		{"test1", "{$.spec.first.second.a/b}", pointsData, "data", false},
		{"test2", "{$.spec.first.second.['person.name']}", pointsData, "icarus", false},
		{"test3", "{$.spec.first.second.['a.com/b.com']}", pointsData, "result", false},
	}
	testJSONPath(pointsTests, false, t)
}

```

### Kubernetes version

<details>

```console
$ kubectl version

master branch
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by iyear** [comment]
It looks like k8s jsonpath has some differences from online executors: https://github.com/kubernetes/kubernetes/issues/23386

After testing, the following tests works:
```go
pointsTests := []jsonpathTest{
	{"test1", "{$.spec.first.second.a/b}", pointsData, "data", false},
	{"test2", `{$.spec.first.second.person\.name}`, pointsData, "icarus", false},
	{"test3", `{$.spec.first.second.a\.com/b\.com}`, pointsData, "result", false},
}
```

**Comment by Icarus9913** [comment]
OK, Alright.
The Escape character solves it.

**Comment by Icarus9913** [comment]
Should I close this issue?
