### ISSUE TITLE
Feature request: mounting GCE-Disk directories (or even files) into containers paths

### ISSUE THREAD

**Issue by hernanliendo** [kubernetes/kubernetes#11756]
Hi,

**[here](https://groups.google.com/forum/#!msg/google-containers/xbxug7cEjWY/7srDOtsNyAgJ)** we were talking about the possibility of having a way to **mount GCE Disks paths, being files or directories, to internal containers paths.**

For containers living in the same or other cluster and the same or other pod:
- mount gceDisk1/gcePath**1**/ to container**A** internal path
- mount gceDisk1/gcePath**2**/ to container**B** internal path
### Some use examples of this approach could be:
- In case of using the [nginx](https://registry.hub.docker.com/_/nginx/) image, mounting a different **file** for image path **/etc/nginx/nginx.conf**, altering its configuration without having to create a Dockerfile
- In case of using [mysql](https://registry.hub.docker.com/_/mysql/) image,  mounting a different **directory** for image path **/etc/mysql/conf.d**, altering its configuration without having to create a Dockerfile

In my opinion it's a great advantage to change default images behaviors altering its paths by Kubernetes spec files instead of having to rebuild the image by Dockerfile, tagging and publishing..

Hernan

**Comment by vishh** [comment]
cc @thockin

**Comment by thockin** [comment]
It's been brought up before but left on the table.  It's not a bad idea,
but will need some careful thought around the Cleaner logic required to get
it right.
