### ISSUE TITLE
Failed to run "post-kubernetes-push-image-etcd"

### ISSUE THREAD

**Issue by kkkkun** [kubernetes/kubernetes#117557]
### What happened?

Failed to run `post-kubernetes-push-image-etcd` .
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1649533793343639552

Is it expect? Should we make  arm etcd image? 

### What did you expect to happen?

`post-kubernetes-push-image-etcd`  runs successfully.

### How can we reproduce it (as minimally and precisely as possible)?

   https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd/1649533793343639552

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xmudrii** [comment]
One option that I see is that we completely remove arm-based etcd image which is in line with what we did for Kubernetes. I think it would be as simple as dropping arm from [Makefile](https://github.com/kubernetes/kubernetes/blob/b35ffd1dcb1e2a745fe7b1337f244efdcdd0cdca/cluster/images/etcd/Makefile#L54), but I might be mistaken.

**Comment by kkkkun** [comment]
> One option that I see is that we completely remove arm-based etcd image which is in line with what we did for Kubernetes. I think it would be as simple as dropping arm from [Makefile](https://github.com/kubernetes/kubernetes/blob/b35ffd1dcb1e2a745fe7b1337f244efdcdd0cdca/cluster/images/etcd/Makefile#L54), but I might be mistaken.

Would kubernetes support `arm arm64 ppc64le s390x` in the futures?  Only support `amd64` ？

**Comment by BenTheElder** [comment]
Are we sure arm32 is the reason the build failed?

**Comment by pacoxu** [comment]
```
ifeq (arm,arm)
/bin/sh: syntax error: unexpected word (expecting ")")
make[1]: *** [Makefile:133: build] Error 2
make[1]: Leaving directory '/workspace/cluster/images/etcd'
make: *** [Makefile:215: sub-push-image-linux-arm] Error 2
ERROR
ERROR: build step 0 "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20221007-69e0da97ef" failed: step exited with non-zero status: 2
```
I prefer to think that https://github.com/kubernetes/kubernetes/pull/117560 should fix the issue.

**Comment by kkkkun** [comment]
Jobs https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-image-etcd run successfully. 

/close
