### ISSUE TITLE
Missing Kubernetes images in GCR, should be pushed on release

### ISSUE THREAD

**Issue by erimatnor** [kubernetes/kubernetes#11751]
These docs says that one can pull Kubernetes images for each release from GCR:

https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.1/docs/getting-started-guides/scratch.md

However, release images seem to be missing in GCR:

```
docker pull gcr.io/google_containers/kube-apiserver:v1.0.0
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag v1.0.0 not found in repository gcr.io/google_containers/kube-apiserver

docker pull gcr.io/google_containers/kube-apiserver:v1.0.1
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag v1.0.1 not found in repository gcr.io/google_containers/kube-apiserver

docker pull gcr.io/google_containers/kube-apiserver:1.0.1
Pulling repository gcr.io/google_containers/kube-apiserver
FATA[0000] Tag 1.0.1 not found in repository gcr.io/google_containers/kube-apiserver
```

**Comment by vishh** [comment]
cc @brendandburns @zmerlynn

**Comment by roberthbailey** [comment]
Assigning to @brendandburns since he built the 1.0.1 release.

**Comment by erimatnor** [comment]
Any update on this? @brendandburns 

Also, would it be possible to provide Docker images for Kubelet?

**Comment by brendandburns** [comment]
@erimatnor please try the gcr.io/google_containers/hyperkube:v1.0.1 image.

That is an all-in-one binary that has all of the components compiled in.

You can run it:

`docker run gcr.io/google_containers/hyperkube:v1.0.1 kubelet ...`

`docker run gcr.io/google_containers/hyperkube:v1.0.1 apiserver ...`

I'll update the docs.

**Comment by philk** [comment]
The entrypoint on these is wrong for that to work. Needs to be:

`docker run gcr.io/google_containers/hyperkube:v1.0.1 /hyperkube apiserver`

**Comment by devurandom** [comment]
The `release-1.0` docs (i.e. https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/getting-started-guides/scratch.md) are still broken.

**Comment by philk** [comment]
The 1.0.2 and 1.0.3 images are unavailable currently. Is this just not the recommended way to run the various components or is it a build system issue? I notice they're labeled "Pre-release" in github releases but that seems weird for a 1.0.x release based on versioning.md

**Comment by brendandburns** [comment]
Generally we wait until we have finished Google Container Engine stability testing before marking a release as "stable" (and I likewise hold off publishing the images until then)

**Comment by brendandburns** [comment]
(though I can push them early if that is useful)

**Comment by philk** [comment]
I'd say once they're a release (even a pre-release) in Github they should exist. Since there isn't a `latest` tag there's no danger of someone pulling in the wrong image accidentally.

**Comment by brendandburns** [comment]
now pushed.

**Comment by philk** [comment]
Awesome, thanks!

**Comment by someword** [comment]
Is it possible to have images pushed to gcr.io for any release or pre-release that shows up on https://github.com/kubernetes/kubernetes/releases.   The pre compiled binaries are available and it would be nice if the analog hyperkube image was available as well.

**Comment by ihmccreery** [comment]
> I'd say once they're a release (even a pre-release) in Github they should exist. Since there isn't a latest tag there's no danger of someone pulling in the wrong image accidentally.

Agreed @philik.  I'm reopening this to be part of our release process, which it currently is not.

**Comment by ihmccreery** [comment]
We should also update docs accordingly; see #16442.

**Comment by thockin** [comment]
we might want to carry something like a "latest" tag so that docs don't need to be updated.  Maybe "HEAD_latest" and make sure that HEAD is replaced with "v1.0" in release branches

**Comment by ihmccreery** [comment]
@quinton-hoole I'm assigning this to you as the release-oncall.  Let me know if you need help.  We're consistently not pushing images as part of our releases, and that needs to be fixed ASAP.

**Comment by quinton-hoole** [comment]
Given that this has remained unresolved for several months, I'm having a hard time understanding why it's suddenly P0, given that we did not block the release of v1.1 on this.  Reducing to P1.

**Comment by skevy** [comment]
Any updates on this? I have a kubernetes cluster deployed using the CoreOS walkthrough (https://coreos.com/kubernetes/docs/latest/getting-started.html), and it would be great to be able to run the latest version.

**Comment by so0k** [comment]
@skevy - it seems v1.1.2 is still flagged as latest stable release...

As mentioned by @brendandburns:
> Generally we wait until we have finished Google Container Engine stability testing before marking a release as "stable" (and I likewise hold off publishing the images until then)

see:
```bash
curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt
```
which currently returns: `v1.1.2`, so we can pull this hyperkube tag:

```bash
docker pull gcr.io/google_containers/hyperkube:v1.1.2
```
and this works, without issue..

If you want v1.1.3 - you'd have to pull the images in tar form. Either via the Kubernetes release archive as explained in the [official guide](http://kubernetes.io/v1.1/docs/getting-started-guides/scratch.html#downloading-and-extracting-kubernetes-binaries), or from the kubernetes releases bucket on google cloud storage (https://storage.googleapis.com/kubernetes-release).

Then `docker load` them in the same way the [kube-up.sh](https://github.com/mikedanese/kubernetes/blob/4ace8280a0bbd50b93e7514ea662de7719e5dc8f/cluster/common.sh#L363) script does:

```
tag=1.1.3
docker_wrapped_binaries=(
   "kube-apiserver"
   "kube-controller-manager"
   "kube-scheduler"
   #"kube-proxy"
)
temp_dir="$(mktemp -d -t 'kube-server-XXXX')"

for binary in "${docker_wrapped_binaries[@]}"; do
  docker_tag="$(curl -sL https://storage.googleapis.com/kubernetes-release/release/v${tag}/bin/linux/amd64/${binary}.docker_tag)"
  (
    echo "downloading ${binary} ${docker_tag}"
    curl -Lo ${temp_dir}/${binary}.tar https://storage.googleapis.com/kubernetes-release/release/v${tag}/bin/linux/amd64/${binary}.tar
    echo "loading docker image"
    docker load -i ${temp_dir}/${binary}.tar
    echo "tagging docker image as ${binary} ${tag}"
    docker tag -f "gcr.io/google_containers/${binary}:${docker_tag}" "${binary}:${tag}"
  )
done

echo "cleaning up temp dir"
rm -rf "${temp_dir}"
```
**Note**: There is no `kube-proxy` image on the cloud storage drive

It seems the individual docker wrapped binaries are pushed to `gcr.io/google_containers` tagged with their md5, not the version tag... and the latest images are 6 months old - see:

```
docker pull -a gcr.io/google_containers/kube-apiserver
```

which shows a 6 months old image...

**Comment by roberthbailey** [comment]
@ihmccreery - did you forget to update stable.txt when marking 1.1.3 as the latest release in github?

**Comment by skevy** [comment]
@so0k thanks so much for the info. It's funny...I tried pulling `gcr.io/google_containers/hyperkube:1.1.1` -- notice the lack of the "v". I'm an idiot.

Thanks for the thorough response!

**Comment by skevy** [comment]
1.1.2 is fine for me at the moment...that's a far cry from the 1.0.7 that's used in the coreos tutorial. You guys have added so much great stuff!

**Comment by ihmccreery** [comment]
@roberthbailey *sigh* Yes.  I have a `TODO` to myself to update the docs, but am waiting on #17777.  And since it's not in the docs, I didn't do it.  Will do today.

**Comment by so0k** [comment]
@ihmccreery @fgrzadkowski - stable is now updated to v1.1.3 but the hyperkube image isn't there?

```bash
 stable="$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)"
docker pull gcr.io/google_containers/hyperkube:$stable
Pulling repository gcr.io/google_containers/hyperkube
Tag v1.1.3 not found in repository gcr.io/google_containers/hyperkube
```

**Comment by mikedanese** [comment]
@so0k that's what this issue addresses. We don't and haven't ever pushed release images to gcr.io as part of the release process. If there are images in gcr.io, they were pushed there as one offs. 

> Missing Kubernetes images in GCR, should be pushed on release

This issue will be closed when we start pushing releases to gcr.io.

**Comment by pieterlange** [comment]
I was just trying if v1.1.7 fixed the EBS cache issue (#18559), but the latest docker images still seem to be missing in GCR (latest is v1.1.4)

@ihmccreery @david-mcmahon could you update gcr.io to also have v1.1.7? I understand this should be fixed per v1.2.0 so this should be one of the last manual pushes. Thanks

**Comment by ihmccreery** [comment]
@pieterlange I've pushed v1.1.7; sorry about the delay.  We push manually for release-1.1, but that will be fixed in v1.2.

**Comment by wazoo** [comment]
Its nearly impossible to figure out what versions are on GCE, this project really needs some sort of interop matrix or available versions portion of the docs (if its there I can't find it).

**Comment by mikedanese** [comment]
If you like json:

https://gcr.io/v2/google-containers/tags/list
https://gcr.io/v2/google-containers/hyperkube/tags/list

**Comment by RRAlex** [comment]
Just for the record, 1.7.6 & 1.7.7 have not been pushed, while 1.8.0 was.
