### ISSUE TITLE
get.k8s.io tar.gz signature

### ISSUE THREAD

**Issue by davidwalter0** [kubernetes/kubernetes#11767]
Does it make sense to sign the kubernetes release tarballs?

**Comment by vishh** [comment]
cc @brendandburns @zmerlynn

**Comment by zmerlynn** [comment]
We're pretty close to this point. We publish md5/sha1 both on github and in the GCS bucket right next to the download, and on the GCE/GKE deployment we actually verify those hashes, so it's really not far off. I don't think a crypto-secure signature buys us much beyond that, TBH.

**Comment by davidwalter0** [comment]
Would something like this work?


diff --git a/cluster/get-kube.sh b/cluster/get-kube.sh
index bd63824..2b49a98 100755
--- a/cluster/get-kube.sh
+++ b/cluster/get-kube.sh
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-# Copyright 2014 The Kubernetes Authors All rights reserved.
+# Copyright 2014 Google Inc. All rights reserved.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
 # you may not use this file except in compliance with the License.
@@ -39,6 +39,9 @@
 #
 #  Set KUBERNETES_SKIP_DOWNLOAD to non-empty to skip downloading a release.
 #  Set KUBERNETES_SKIP_CONFIRM to skip the installation confirmation prompt.
+#  Set KUBERNETES_SKIP_CLUSTER_CREATE to stop after download
+#  Set KUBERNETES_VERSION to specify a version to download
+
 set -o errexit
 set -o nounset
 set -o pipefail
@@ -48,10 +51,8 @@ function create_cluster {
   (
     cd kubernetes
     ./cluster/kube-up.sh
-    echo "Kubernetes binaries at ${PWD}/cluster/"
-    if [[ ":$PATH:" != *":${PWD}/cluster:"* ]]; then
-      echo "You may want to add this directory to your PATH in \$HOME/.profile"
-    fi
+    echo "Kubernetes binaries at ${PWD}/kubernetes/cluster/"
+    echo "You may want to add this directory to your PATH in \$HOME/.profile"
 
     echo "Installation successful!"
   )
@@ -68,13 +69,22 @@ function get_latest_version_number {
     wget -qO- ${latest_url}
   elif [[ $(which curl) ]]; then
     curl -Ss ${latest_url}
-  else
-    echo "Couldn't find curl or wget.  Bailing out."
-    exit 4
   fi
 }
 
-release=$(get_latest_version_number)
+release="${KUBERNETES_VERSION-}"
+for arg in ${*}; do
+    case ${arg} in
+        --release=*)
+            release=${arg#--release=}
+            ;;
+    esac
+done
+
+if (( ! ${#release} )); then
+    release=$(get_latest_version_number)
+fi
+
 release_url=https://storage.googleapis.com/kubernetes-release/release/${release}/kubernetes.tar.gz
 
 uname=$(uname)
@@ -103,7 +113,7 @@ else
   exit 3
 fi
 
-file=kubernetes.tar.gz
+file=kubernetes-${release}.tar.gz
 
 echo "Downloading kubernetes release ${release} to ${PWD}/kubernetes.tar.gz"
 if [[ -n "${KUBERNETES_SKIP_CONFIRM-}" ]]; then
@@ -115,17 +125,55 @@ if [[ -n "${KUBERNETES_SKIP_CONFIRM-}" ]]; then
   fi
 fi
 
-if [[ $(which wget) ]]; then
-  wget -O ${file} ${release_url}
-elif [[ $(which curl) ]]; then
-  curl -L -o ${file} ${release_url}
-else
-  echo "Couldn't find curl or wget.  Bailing out."
-  exit 1
-fi
+function download
+{
+    success=
+    if [[ $(which sha1sum) ]]; then
+        ext=sha1
+    elif [[ $(which md5sum) ]]; then
+        ext=md5
+    fi
+
+    if [[ $(which wget) ]]; then
+        if [[ ${ext} ]]; then
+            wget -O ${file}.${ext} ${release_url}.${ext} || ext=""
+        fi
+        wget -O ${file} ${release_url} && success=1
+    elif [[ $(which curl) ]]; then
+        if [[ ${ext} ]]; then
+            curl -L -o ${file}.${ext} ${release_url}.${ext} && success=1
+        fi
+        curl -L -o ${file} ${release_url} || ext=""
+    else
+        echo "Couldn't find curl or wget.  Bailing out."
+    fi
+    if [[ ${success} ]]; then 
+        case ${ext} in
+            sha1)
+                if ! echo $(cat  kubernetes.tar.gz.sha1) ${file} | sha1sum -c - ; then
+                    echo sha checksum validation failed
+                fi
+                ;;
+            md5)
+                if ! echo $(cat  kubernetes.tar.gz.md5) ${file} | md5sum -c - ; then
+                    echo md5 checksum validation failed
+                fi
+                ;;
+        esac
+        rm -f ${file}.${ext}
+    fi
+}
+
+download
 
 echo "Unpacking kubernetes release ${release}"
 tar -xzf ${file}
-rm ${file}
+
+rm -f ${file} 
+
+if [[ ${KUBERNETES_SKIP_CLUSTER_CREATE-} ]] ; then
+   echo "Skipping cluster create"
+   exit 0
+fi
 
 create_cluster
