### ISSUE TITLE
Volumes (glusterfs not removed as mentioned in official documentation for v1.27.x)

### ISSUE THREAD

**Issue by lirtistan** [kubernetes/kubernetes#117699]
Hi,

i installed a fresh k8s inside a little VM, just for gambling with possible storage solutions and i stumbled over this...

![k8s-v1 27 x-glusterfs-inside-docs](https://user-images.githubusercontent.com/54737363/235415535-ed9318e0-0f3c-4119-9812-87edf7f3ab3b.png)

```bash
root@web1:~# kubectl explain --recursive=true persistentvolumes.spec.glusterfs
KIND:       PersistentVolume
VERSION:    v1

FIELD: glusterfs <GlusterfsPersistentVolumeSource>

DESCRIPTION:
    glusterfs represents a Glusterfs volume that is attached to a host and
    exposed to the pod. Provisioned by an admin. More info:
    https://examples.k8s.io/volumes/glusterfs/README.md
    Represents a Glusterfs mount that lasts the lifetime of a pod. Glusterfs
    volumes do not support ownership management or SELinux relabeling.
    
FIELDS:
  endpoints	<string> -required-
  endpointsNamespace	<string>
  path	<string> -required-
  readOnly	<boolean>

root@web1:~# kubectl get nodes -o wide
NAME      STATUS   ROLES           AGE    VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
cluster   Ready    control-plane   170d   v1.27.1   192.168.1.254   <none>        Ubuntu 22.04.2 LTS   5.15.0-71-generic   containerd://1.6.20
root@web1:~# dpkg -l | grep kube
hi  kubeadm                         1.27.1-00                               amd64        Kubernetes Cluster Bootstrapping Tool
hi  kubectl                         1.27.1-00                               amd64        Kubernetes Command Line Tool
hi  kubelet                         1.27.1-00                               amd64        Kubernetes Node Agent
hi  kubernetes-cni                  1.2.0-00                                amd64        Kubernetes CNI
```

..so iam not sure if this was intentionally, but the resource still is available in the PV resource.

**Comment by lirtistan** [comment]
```bash
root@web1:~# kubectl get pod -n kube-system kube-apiserver-cluster -o json | jq ".spec.containers[].image"
"registry.k8s.io/kube-apiserver:v1.27.1"
```
Oh and just to ensure the kube-apiserver image is not outdated.

**Comment by liggitt** [comment]
The API field still exists (and will not be removed), but the implementation of volume plugin support for glusterfs is removed.

**Comment by Shubham82** [comment]
> The API field still exists (and will not be removed)

Hi @liggitt thanks for the information, but could you please tell me the reason to did so?

**Comment by lirtistan** [comment]
That whould be also my question!?

**Comment by liggitt** [comment]
Several reasons:
1. [Deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#fields-of-rest-resources) says we don't delete GA fields from GA API type definitions
2. Dropping the field could turn existing stored API objects invalid. PersistentVolumes are required to specify a volume source. An existing stored PV object with a `glusterfs` volume source would become invalid if the glusterfs field was dropped (it would be seen as a PV with no volume source specified) and would fail update validation, which could prevent removal of finalizers and deletion of the API object.
3. An out-of-tree CSI plugin could be developed to implement glusterfs storage, translating data in the existing glusterfs fields into CSI volumes

**Comment by Shubham82** [comment]
> Several reasons:
> 
> [Deprecation policy](https://kubernetes.io/docs/reference/using-api/deprecation-policy/#fields-of-rest-resources) says we don't delete GA fields from GA API type definitions
> Dropping the field could turn existing stored API objects invalid. PersistentVolumes are required to specify a volume source. An existing stored PV object with a glusterfs volume source would become invalid if the glusterfs field was dropped (it would be seen as a PV with no volume source specified) and would fail update validation, which could prevent removal of finalizers and deletion of the API object.
> An out-of-tree CSI plugin could be developed to implement glusterfs storage, translating data in the existing glusterfs fields into CSI volumes

Thanks @liggitt for the explanation.
