### ISSUE TITLE
Pluggability of Service Account Authn and Authz

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#11763]
I think we want to support the following:
- when the service account controller makes a service account, it delegates creation of a credential to a  plugin. 
  - when the service account controller makes a service account, it delegates creation of policy for that new service account to a plugin. 
  - in both cases, compiled-in plugin is fine.  E.g. in the style of authorizer.Authorizer and authenticator.Request.
  - in both cases, default one would work the way things work now, but users could substitute a different one.  

x-ref: #11687 #11626

**Comment by erictune** [comment]
@liggitt @deads2k

**Comment by deads2k** [comment]
> when the service account controller makes a service account, it delegates creation of a credential to a plugin.

Are you comfortable limiting SA credentials to tokens or do we want to try to support other mechanisms?  The predictable structure of exactly how an SA authenticates and how it gets auto-mounted into your pod makes it easy to write portable images that expect those features.  There are arguments for allowing things like cert-auth for SAs, but I think we should consider whether they outweigh the benefits of predictability.

**Comment by deads2k** [comment]
> when the service account controller makes a service account, it delegates creation of policy for that new service account to a plugin.

Do you see this as akin to an initializer?  It seems like it would be a good fit there.  There were definitely cases where we wanted this sort of a feature for service accounts in particular.

**Comment by uruddarraju** [comment]
How about a union of authorizers, similar to what we have with authenticators ?

**Comment by erictune** [comment]
Yes to union of authorizers.
See comment here https://github.com/kubernetes/kubernetes/issues/11626#issuecomment-134385069

**Comment by liggitt** [comment]
authorization union is supported. pluggable service account auth is likely to go more in the direction of container identity - see https://github.com/kubernetes/community/tree/master/wg-container-identity
