### ISSUE TITLE
topologySpreadConstraints: Proposal to add whenUnsatisfiable: PreemptOrSchedule

### ISSUE THREAD

**Issue by ssanders1449** [kubernetes/kubernetes#117634]
Right now, topologySpreadConstraints have only two possible behaviors when the constraint can not be satisfied: DoNotSchedule or ScheduleAnyway

However, these behaviors do not consider the possibilty that there may be lower priority pods which can be preempted in order to satisfy the constraint.

I propose adding a third value to 'whenUnsatisfiable' - let's name it PreemptOrSchedule. This will first try to preempt lower priority pods to allow the constraint to be satisfied, but it can't find pods to preempt, it will schedule the current pod anyway.

A typical use case is when we create negative priority 'headroom' pods whose only purpose is to reserve space in the cluster to allow for faster autoscaling.

Consider the case where we have a topologySpreadConstraint with maxSkew:1 to balance across two availabilty zones. Zone A has 5 pods and Zone B has 6. We now want to schedule another pod. Zone A does not have enough free space, while Zone B does have free space. There are two scenarios:
1) Zone A has some negative priority 'headroom' pods which could be preempted to free space
2) Zone A does not have any more pods that can be preempted (e.g. They all have already been preempted and are Pending waiting for the cluster autoscaler)

With whenUnsatisfiable:ScheduleAnyway, the new pod will be scheduled on Zone B even though we have plenty of 'headroom' on Zone A.

With whenUnsatisfiable:DoNotSchedule scenario 1 will indeed preempt the headroom pods in Zone A in order to schedule the new pod. However, for scenario 2, it leaves the new pod Pending and we will need to wait for the cluster autoscaler to add resources.

What I would like is an option where in scenario 1,  we will preempt the headroom pods in order to satisfy the constraint. However, in scenario 2, I would rather have the pod scheduled anyway and not need to wait for the cluster autoscaler

**Comment by ssanders1449** [comment]
/sig/scheduling

**Comment by ahg-g** [comment]
This is related https://github.com/kubernetes/kubernetes/issues/105977

**Comment by kerthcet** [comment]
Can we communicate about this in that thread and close this one? Reasonable? @ssanders1449

**Comment by ssanders1449** [comment]
> Can we communicate about this in that thread and close this one? Reasonable? @ssanders1449

Yes
