### ISSUE TITLE
[runc][1.1.6] Adding misc controller to cgroup v1 makes kubelet sad

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#117647]
Tracking issue for https://github.com/opencontainers/runc/issues/3849

When using runc 1.1.6 - kubelet, systemd, and dbus-broker consumes excessive CPU and memory resources.

Previous issue - https://github.com/kubernetes/kubernetes/issues/112124
Previous fix - https://github.com/opencontainers/runc/pull/3823

TL;DR see table:
```
Linux 5.10, cgroup v1 - not affected
Linux 5.15, cgroup v1 - affected
Linux 5.15, cgroup v1 - affected
Linux 5.15, cgroup v2 - not affected
```

**Comment by dims** [comment]
/sig node

cc @kolyshkin @SergeyKanzhelev @rphillips  @danielcb

**Comment by bcressey** [comment]
The previous issue seems to have affected cri-o, or at least containerd is not called out. We observed this behavior on Bottlerocket, which uses containerd. That might account for the difference.

**Comment by kolyshkin** [comment]
As explained in other places, I think the reason is runc/libcontainer vendored should also be aware of misc controller.

So, the fix is to bump runc/libcontainer to 1.1.6. The PRs are:
* https://github.com/kubernetes/kubernetes/pull/117241
* https://github.com/kubernetes/kubernetes/pull/117242
* https://github.com/kubernetes/kubernetes/pull/117681
* https://github.com/kubernetes/kubernetes/pull/117682

The alternative is to modify runc/libcontainer to also remove any unknown controllers.

**Comment by mmerkes** [comment]
> The alternative is to modify runc/libcontainer to also remove any unknown controllers.

This an issue we might see again? Seems like something to consider if there's going to be a risk that this need to be done again, not to mention new fun places where this incompatibility to pop up in other package/applications.

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/117647

**Comment by liggitt** [comment]
does this mean we should revert https://github.com/kubernetes/kubernetes/pull/117241 and https://github.com/kubernetes/kubernetes/pull/117242 until this is resolved?

**Comment by liggitt** [comment]
do we have a reproducer / test, so we can confirm master and release-1.27 fix this issue before backporting to 1.26, 1.25, 1.24?

**Comment by mmerkes** [comment]
Steps to reproduce are in [the runc tracking issue](https://github.com/opencontainers/runc/issues/3849).

**Comment by liggitt** [comment]
> Steps to reproduce are in [the runc tracking issue](https://github.com/opencontainers/runc/issues/3849).

is there a kubernetes test showing https://github.com/kubernetes/kubernetes/pull/117691 / https://github.com/kubernetes/kubernetes/pull/117682 resolve the issue? wanting to make sure that dep bump is sufficient

**Comment by saschagrunert** [comment]
Is this issue still relevant?

**Comment by BenTheElder** [comment]
We just solved the implications for KIND in CI last night.

For end users we probably at least need to document this situation better? Until v1 isn't supported

**Comment by BenTheElder** [comment]
And the project itself will have to watch this for future upgrades in CI clusters.

**Comment by dims** [comment]
/close

https://github.com/opencontainers/runc/issues/3849#issuecomment-1544519250
