### ISSUE TITLE
Unprofessional code depending on unspecified behavior

### ISSUE THREAD

**Issue by go101** [kubernetes/kubernetes#117606]
### What happened?

https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/cilium/ebpf/internal/btf/types.go#L603-L604

### What did you expect to happen?

```Go
func copyType(typ Type, transform func(Type) (Type, error)) (Type, error) {
	copies := make(copier)
	err := copies.copy(&typ, transform)
	return typ, err
}
```

see more: https://github.com/golang/go/issues/58233#issuecomment-1499471060

### How can we reproduce it (as minimally and precisely as possible)?

The behavior might be changed in future Go toolchain versions.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by BenTheElder** [comment]
I'm not sure if we're actually using this code, but even if we are you should report it to the source repo, which would be https://github.com/cilium/ebpf

We can update vendor only when the source repo is updated.

**Comment by BenTheElder** [comment]
I see, in the linked issue this has been removed from the upstream library ini this particular case.

We have some PRs open to update the library, but there's been other issues with changes to that library, so they're not in yet. https://github.com/kubernetes/kubernetes/pull/117457

Have bugs been filed with the other libraries?

**Comment by BenTheElder** [comment]
Thanks.

Re updating: see above. There are PRs to update it but there's other problematic code in this package. We're evaluating if we should even have this dependency or else if we can work with the owners to resolve some other issues (like registering a signal handler in package init ...)

**Comment by neolit123** [comment]
> The cilium/ebpf version got updated with this PR: #117253
> 
> Seems like this issue can get closed.

/close
