### ISSUE TITLE
Kubernetes frontend services should allow to manage Cloud DNS entries

### ISSUE THREAD

**Issue by pkern** [kubernetes/kubernetes#11760]
In kind of the same vein as #10323 Kubernetes should allow for a service to repoint a Google Cloud DNS entry to the (newly created) loadbalancer's IP to make the entrypoint publically accessible.

**Comment by vishh** [comment]
cc @thockin

**Comment by thockin** [comment]
I agree with the goal.  I am not sure if it is an attribute of Service or
an orthogonal concept, e.g a Name object.  something like this is
definitely in the cards, though.

**Comment by coleca** [comment]
Support for alternate services as well such as Route53 would be very desirable.  At least for the natively supported providers, similar to the "magic" that happens with spinning up load balancers.

**Comment by gtaylor** [comment]
In the meantime, does anyone have suggestions for how to accomplish this (with Google Cloud DNS in particular)?

**Comment by justinsb** [comment]
dns-controller does this.  It is currently part of kops.  If there is interest I could propose it for incubation as a top-level project.  Right now it is nestled under kops: https://github.com/kubernetes/kops/tree/master/dns-controller

**Comment by thockin** [comment]
ExternalDNS is a standalone project now.
