### ISSUE TITLE
when the memory usage is greater than 80%， node is marked  ” Ready,SchedulingDisabled “

### ISSUE THREAD

**Issue by iswangyi** [kubernetes/kubernetes#117609]
### What happened?

kubectl top node get the memory usage greater than 80%, the node marked Ready,SchedulingDisabled,  but kubelet only config
--eviction-hard=memory.available<10%.  

The describe node  results  conditions  don't have any pressure

Other clusters don't have a similar situation even if it at 90%

[app@k8s-master-1 ~]$ kubectl get node
NAME            STATUS                     ROLES                      AGE    VERSION
192.168.0.100   Ready                      controlplane,etcd,worker   199d   v1.12.6
192.168.0.103   Ready                      worker                     199d   v1.12.6
192.168.0.105   Ready,SchedulingDisabled   controlplane,etcd,worker   199d   v1.12.6
192.168.0.107   Ready,SchedulingDisabled   worker                     199d   v1.12.6
192.168.0.99    Ready                      controlplane,etcd,worker   199d   v1.12.6
192.168.1.32    Ready                      worker                     199d   v1.12.6
192.168.1.34    Ready                      worker                     86d    v1.12.6
192.168.1.36    Ready                      worker                     79d    v1.12.6
192.168.1.37    Ready,SchedulingDisabled   worker                     56d    v1.12.6
192.168.1.38    Ready,SchedulingDisabled   worker                     6d5h   v1.12.6

[app@k8s-master-1 ~]$ kubectl top node
NAME            CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
192.168.0.100   742m         18%    10374Mi         36%       
192.168.0.103   789m         19%    23894Mi         82%       
192.168.0.105   731m         18%    24701Mi         85%       
192.168.0.107   579m         14%    25207Mi         87%       
192.168.0.99    1978m        49%    20855Mi         72%       
192.168.1.32    487m         6%     40888Mi         71%       
192.168.1.34    368m         4%     40744Mi         71%       
192.168.1.36    599m         7%     36460Mi         64%       
192.168.1.37    738m         9%     49860Mi         87%       
192.168.1.38    444m         5%     50537Mi         88%       

root      19558  2.9  0.2 1523872 146992 ?      Ssl  Apr20 267:36 kubelet --enforce-node-allocatable= --network-plugin=cni --allow-privileged=true --anonymous-auth=false --v=2 --cluster-domain=cluster.local --hostname-override=192.168.1.38 --cgroups-per-qos=True --cni-conf-dir=/etc/cni/net.d --cloud-provider= --cluster-dns=10.200.0.10 --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --event-qps=0 --make-iptables-util-chains=true --authentication-token-webhook=true --pod-infra-container-image=hub.onlinesign.com/rancher/pause-amd64:3.1 --volume-plugin-dir=/var/lib/kubelet/volumeplugins --streaming-connection-idle-timeout=30m --max-pods=255 --read-only-port=0 --resolv-conf=/etc/resolv.conf --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --fail-swap-on=false --root-dir=/var/lib/kubelet --eviction-hard=memory.available<10% --address=0.0.0.0 --cni-bin-dir=/opt/cni/bin --cgroup-driver=cgroupfs

192.168.1.38    Ready,SchedulingDisabled   worker                     6d5h   v1.12.6   192.168.1.38    <none>        CentOS Linux 7 (Core)   3.10.0-957.21.3.el7.x86_64    docker://18.9.3

[app@k8s-node-7 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:          63240       41215         369           7       21655       21321
Swap:             0           0           0

[app@k8s-node-7 ~]$ cat /proc/meminfo 
MemTotal:       64758128 kB
MemFree:          373308 kB
MemAvailable:   21831876 kB
Buffers:          137720 kB
Cached:         19890760 kB
SwapCached:            0 kB
Active:         51719088 kB
Inactive:        9704732 kB
Active(anon):   41397988 kB
Inactive(anon):     4752 kB
Active(file):   10321100 kB
Inactive(file):  9699980 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               980 kB
Writeback:             0 kB
AnonPages:      41395352 kB
Mapped:           551196 kB
Shmem:              7400 kB
Slab:            2150792 kB
SReclaimable:    1965316 kB
SUnreclaim:       185476 kB
KernelStack:       88128 kB
PageTables:       125036 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    32379064 kB
Committed_AS:   43573232 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      120176 kB
VmallocChunk:   34359485364 kB
HardwareCorrupted:     0 kB
AnonHugePages:  19132416 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:      299708 kB
DirectMap2M:    23799808 kB
DirectMap1G:    44040192 kB

[app@k8s-master-1 ~]$ kubectl describe node 192.168.1.38
Name:               192.168.1.38
Roles:              worker
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/hostname=192.168.1.38
                    node-role.kubernetes.io/worker=true
Annotations:        node.alpha.kubernetes.io/ttl: 0
                    projectcalico.org/IPv4Address: 192.168.1.38/24
                    rke.cattle.io/external-ip: 192.168.1.38
                    rke.cattle.io/internal-ip: 192.168.1.38
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 20 Apr 2023 11:23:11 +0800
Taints:             node.kubernetes.io/unschedulable:NoSchedule
Unschedulable:      true
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  OutOfDisk        False   Wed, 26 Apr 2023 16:29:47 +0800   Thu, 20 Apr 2023 11:23:11 +0800   KubeletHasSufficientDisk     kubelet has sufficient disk space available
  MemoryPressure   False   Wed, 26 Apr 2023 16:29:47 +0800   Thu, 20 Apr 2023 11:23:11 +0800   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Wed, 26 Apr 2023 16:29:47 +0800   Thu, 20 Apr 2023 11:23:11 +0800   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Wed, 26 Apr 2023 16:29:47 +0800   Thu, 20 Apr 2023 11:23:11 +0800   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Wed, 26 Apr 2023 16:29:47 +0800   Thu, 20 Apr 2023 11:23:21 +0800   KubeletReady                 kubelet is posting ready status
Addresses:
  InternalIP:  192.168.1.38
  Hostname:    192.168.1.38
Capacity:
 cpu:                8
 ephemeral-storage:  206289972Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             64758128Ki
 pods:               255
Allocatable:
 cpu:                8
 ephemeral-storage:  206289972Ki
 hugepages-1Gi:      0
 hugepages-2Mi:      0
 memory:             59681090666
 pods:               255
System Info:
 Machine ID:                 3e608929fbd39b959f388bf468c9f0b1
 System UUID:                38488DF0-49AB-4534-A143-A2B6FB4A6188
 Boot ID:                    5977da43-331a-4101-b068-10cdde1c186e
 Kernel Version:             3.10.0-957.21.3.el7.x86_64
 OS Image:                   CentOS Linux 7 (Core)
 Operating System:           linux
 Architecture:               amd64
 Container Runtime Version:  docker://18.9.3
 Kubelet Version:            v1.12.6
 Kube-Proxy Version:         v1.12.6
PodCIDR:                     10.100.9.0/24
Non-terminated Pods:         (26 in total)
  Namespace                  Name                                        CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                  ----                                        ------------  ----------  ---------------  -------------  ---
  data-storage               fluent-bit-q6qhc                            0 (0%)        0 (0%)      0 (0%)           0 (0%)         6d5h

Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                2665m (33%)    60 (750%)
  memory             27115Mi (47%)  78000Mi (137%)
  ephemeral-storage  0 (0%)         0 (0%)
Events:              <none>

### What did you expect to happen?

when node marked Ready,SchedulingDisabled， conditions recored why

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/55943762/234520561-53c8a0a6-b3cb-43ba-b000-62b5baf7f240.png)

No similar problems were found in other environments

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-05-07T08:57:33Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

aliyun

### OS version

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

### Install tools

RKE

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by iswangyi** [comment]
exec this shell script  https://kubernetes.io/examples/admin/resource/memory-available.sh

[app@k8s-node-7 ~]$ sh /tmp/mem.sh 
memory.capacity_in_bytes 66312323072
memory.usage_in_bytes 62897803264
memory.total_inactive_file 9986838528
memory.working_set 52910964736
memory.available_in_bytes 13401358336
memory.available_in_kb 13087264
memory.available_in_mb 12780

**Comment by pacoxu** [comment]
Can you confirm that the node is marked as un-schedulable by kubelet or some other components?

btw, 1.12(eof at 2019-07-08) is too old for kubernetes community support.  See https://kubernetes.io/releases/patch-releases/

**Comment by iswangyi** [comment]
> Can you confirm that the node is marked as un-schedulable by kubelet or some other components?
> 
> * MemoryPressure and DiskPressure are false here which indicts that the taint may not be caused by the memory usage 80%.
> 
> btw, 1.12(eof at 2019-07-08) is too old for kubernetes community support. See https://kubernetes.io/releases/patch-releases/


Thanks. @pacoxu 

When I finish executing the "kubectl undron node" command, the kubelet has the following logs. But did not see why. Are there other components that would mark node as un-schedulable?

 
`{"log":"I0426 02:33:44.879788   19558 kubelet_node_status.go:429] Recording NodeSchedulable event message for node 192.168.1.38\n","stream":"stderr","time":"2023-04-26T02:33:44.879860406Z"}

{"log":"I0426 02:35:05.024442   19558 kubelet_node_status.go:429] Recording NodeNotSchedulable event message for node 192.168.1.38\n","stream":"stderr","time":"2023-04-26T02:35:05.024510098Z"}`

**Comment by pacoxu** [comment]
Current information still cannot conclude that the node is marked by kubelet: Check the kubelet log or node event.
You may check the apiserver log for node status updates, or audio log. And check if there are other components did this.

**Comment by pacoxu** [comment]
/triage needs-information
/remove-kind bug
Before we can prove this is a bug, I prefer to not tag it as a bug

**Comment by neolit123** [comment]
missing additional information.
please reopen if needed and if the information is provided.

/close
