### ISSUE TITLE
Type checking in ValidatingAdmissionPolicy does not support authorizer variable

### ISSUE THREAD

**Issue by cici37** [kubernetes/kubernetes#117601]
### What happened?

The type checking in ValidatingAdmissionPolicy does not recognize authorizer related variables and report it as warning in status.

### What did you expect to happen?

authorizer check should be supported by type checking

### How can we reproduce it (as minimally and precisely as possible)?

Create a ValidatingAdmissionPolicy with authorizer expression added into Validations, apply it and check the status.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jiahuif** [comment]
/close
fixed by https://github.com/kubernetes/kubernetes/pull/118540
