### ISSUE TITLE
TestKMSv2Healthz flake

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#117646]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/117614/pull-kubernetes-integration/1651530152728858624

### Which tests are flaking?

{Failed  === RUN   TestKMSv2Healthz
--- FAIL: TestKMSv2Healthz (167.38s)

also shown in https://storage.googleapis.com/k8s-metrics/flakes-latest.json
      "k8s.io/kubernetes/test/integration/controlplane/transformation TestKMSv2Healthz": 1,

### Since when has it been flaking?

Not sure

### Reason for failure (if possible)

```
E0427 10:46:16.817671   85838 controller.go:259] unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8, ::1/128)
I0427 10:46:16.911127   85838 transformation_test.go:108] Started kube-apiserver https://127.0.0.1:34851
    transformation_test.go:560: expected server check "/kms-providers" to be unhealthy with message "internal server error: kms-provider-0: rpc error: code = FailedPrecondition desc = failed precondition - key disabled" but it is not: ok
    transformation_test.go:560: expected server check "/kms-providers" to be unhealthy with message "internal server error: kms-provider-0: rpc error: code = FailedPrecondition desc = failed precondition - key disabled" but it is not: ok
```

### Relevant SIG(s)

/sig auth

**Comment by aramase** [comment]
/assign @nilekhc 
/triage accepted

- Use `1*time.Second` for poll interval
- Change the poll timeout to 5m
- Update the poll error check (check if not nil)
