### ISSUE TITLE
Custom token for kubernetes.io/service-account-token - does not work when used

### ISSUE THREAD

**Issue by tdevopsottawa** [kubernetes/kubernetes#117679]
### What happened?

I'm trying to create a kubernetes ServiceAccount but using a custom token instead of having an autogenerated one.

This is the code I'm using
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: test-sa-token
  annotations:
    kubernetes.io/service-account.name: test-sa
type: kubernetes.io/service-account-token
data:
  token: VE9LRU5IRVJF
```
  
(note - I didn't redact the token as it's all just local tests and it's not a meaningful secret. VE9LRU5IRVJF is literally just "TOKENHERE" base64 encoded).

Creating the service account works, but everytime I try to use it for something, it fails to authenticate to kubernetes. If I remove the data: token: block from the code (thus allowing kubernetes to autogenerate the token) the whole stack works perfectly fine, so the problem is that it's rejecting my custom token for whatever reason.

### What did you expect to happen?

That the service account will work with a custom token.

### How can we reproduce it (as minimally and precisely as possible)?

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: test-sa-token
  annotations:
    kubernetes.io/service-account.name: test-sa
type: kubernetes.io/service-account-token
data:
  token: VE9LRU5IRVJF
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-cluster-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-cluster-role
subjects:
- kind: ServiceAccount
  name: test-sa
```

### Anything else we need to know?

I need to be able to create the token independently completely outside of kubernetes - ie. any solution that involves running a kubectl command to create the token is not acceptable.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-27T22:54:20Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

Azure Kubernetes Service

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
BuildNumber  Caption                    OSArchitecture  Version
22621        Microsoft Windows 11 Home  64-bit          10.0.22621

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
/remove-kind bug
/kind support

you cannot set an arbitrary token in the secret, only the ones generated by kubernetes will work. The tokens are signed JWTs, and must be the correct format and have the correct signature to be usable to authenticate.
