### ISSUE TITLE
kubelet is vulnerable to concurrent sort and can violate safety guarantees [v1.21.x]

### ISSUE THREAD

**Issue by zhouhaibing089** [kubernetes/kubernetes#117694]
### What happened?

From time to time (with a very low chance), we see that some of our pods couldn't start, and failed with message like below:

```console
$ kubectl get pod goapp
NAME    READY   STATUS   RESTARTS   AGE
goapp   29/30   Error    9          118s
$ kubectl logs goapp -c p1251
2023/04/29 23:31:32 listen tcp :1251: bind: address already in use
``` 

And when I go to the host, I can see that there is already a container running for `p1251`, but kubelet tried to create another one regardless. (This violates the safety guarantee that kubelet should never try to launch two running instances for a single container spec in pod).

```console
$ docker ps -a | grep goapp_default | grep p1251
0207c985fa7c        731e2216ed4e             "/usr/local/bin/goap…"   19 seconds ago      Exited (1) 18 seconds ago                          k8s_p1251_goapp_default_c19bc8c4-6d62-4146-864e-b240015a0b36_6
c50f265a3b7c        731e2216ed4e             "/usr/local/bin/goap…"   3 minutes ago       Up 3 minutes
```

Given the container `p1251` already started 3 minutes ago, it is unexpected to see new containers coming up (though they can't because the specific port is already in-use). 

### What did you expect to happen?

I expect the pod should be Running without issues.

### How can we reproduce it (as minimally and precisely as possible)?

I have a detailed step-by-step guide for this - https://github.com/zhouhaibing089/blog/issues/40. (To reproduce this successfully, it might be required to run multiple times).

To add the steps here, too:

1. Launch v1.21.14 cluster via minikube:

```console
$ minikube start --driver=virtualbox --cpus=4 --memory=8g --kubernetes-version=v1.21.14
```

2. Apply the pod specs from https://github.com/zhouhaibing089/goapp/tree/master/pods

### Kubernetes version

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1
```

### Cloud provider

None.

But I have seen the same in aws.

### OS version

From minikube

```console
$ cat /etc/os-release
NAME=Buildroot
VERSION=2021.02.12-1-g60d41a4-dirty
ID=buildroot
VERSION_ID=2021.02.12
PRETTY_NAME="Buildroot 2021.02.12"
$ uname -a
Linux minikube 5.10.57 #1 SMP Sat Apr 29 21:22:40 UTC 2023 x86_64 GNU/Linux
```

### Install tools

minikube

### Container runtime (CRI) and version (if applicable)

dockershim

### Related plugins (CNI, CSI, ...) and versions (if applicable)

None.

**Comment by zhouhaibing089** [comment]
There is a [thread][1] on slack related to this as well.

To capture some observations here as well. When the problem ocurred:

## Observed container status from `GetPodStatus`.

```
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.710928  677879 kuberuntime_manager.go:1033] "GetPodStatus" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1263" state=running id="f0a214890680f26e6aca4997ee72c8bd582facb149a4f268890d9f0b0aadf0a0"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.710944  677879 kuberuntime_manager.go:1033] "GetPodStatus" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1262" state=running id="b98bc7769f3f62998e69108a2033dd06bac078eb391642781b05b9c8751e2378"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.710948  677879 kuberuntime_manager.go:1033] "GetPodStatus" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1261" state=exited id="9aed63a77f351e94f279d46249c2bf1ec690f465f6ccb29cb429d8d789049137"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.710953  677879 kuberuntime_manager.go:1033] "GetPodStatus" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1260" state=exited id="96c471afbb6485533bb9167e0a3a218b41aa9a727ebdd33dcdbb68e53be489d6"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.710958  677879 kuberuntime_manager.go:1033] "GetPodStatus" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1259" state=running id="50359e9b9a84b2a9dcb2dad1483acb4702e09ca83b8931cbcc2f0d8096c1f09d"
```

## Observed container staus in `managePodLoop`

```
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711204  677879 pod_workers.go:176] "managePodLoop" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1263" state=running id="f0a214890680f26e6aca4997ee72c8bd582facb149a4f268890d9f0b0aadf0a0"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711213  677879 pod_workers.go:176] "managePodLoop" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1262" state=running id="b98bc7769f3f62998e69108a2033dd06bac078eb391642781b05b9c8751e2378"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711217  677879 pod_workers.go:176] "managePodLoop" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1261" state=exited id="9aed63a77f351e94f279d46249c2bf1ec690f465f6ccb29cb429d8d789049137"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711222  677879 pod_workers.go:176] "managePodLoop" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1260" state=exited id="96c471afbb6485533bb9167e0a3a218b41aa9a727ebdd33dcdbb68e53be489d6"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711227  677879 pod_workers.go:176] "managePodLoop" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1259" state=running id="50359e9b9a84b2a9dcb2dad1483acb4702e09ca83b8931cbcc2f0d8096c1f09d"
```

## Observed container status in `computePodActions`

```
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711608  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1263" state=running id="f0a214890680f26e6aca4997ee72c8bd582facb149a4f268890d9f0b0aadf0a0"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711624  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1263" state=running id="f0a214890680f26e6aca4997ee72c8bd582facb149a4f268890d9f0b0aadf0a0"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711629  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1261" state=exited id="9aed63a77f351e94f279d46249c2bf1ec690f465f6ccb29cb429d8d789049137"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711637  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1260" state=exited id="96c471afbb6485533bb9167e0a3a218b41aa9a727ebdd33dcdbb68e53be489d6"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711641  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1259" state=running id="50359e9b9a84b2a9dcb2dad1483acb4702e09ca83b8931cbcc2f0d8096c1f09d"
Apr 30 06:39:44 minikube kubelet[677879]: I0430 06:39:44.711645  677879 kuberuntime_manager.go:610] "computePodActions" podUID=789c818d-5686-49a3-b0c2-d3061c93be7c containerName="p1258" state=running id="f0104d7b4bd82df359c245fa617936698c619bf9d1ffcd3ed41d16bb803e509f"
```

For some reason, the containerStatus as seen in `computePodActions` is different from what is observed in `managePodLoop`. It has been updated somehow (which is unexpected).

[1]: https://kubernetes.slack.com/archives/C0BP8PW9G/p1682626134354939

**Comment by zhouhaibing089** [comment]
By purely analysis, this is mostly like due to a concurrent sort in https://github.com/kubernetes/kubernetes/blob/57a3aa3f13699cf3db9c52d228c18db94fa81876/pkg/kubelet/kubelet_pods.go#L1764.

The function chain is like this:

`convertToAPIContainerStatuses` <- `convertStatusToAPIStatus` <- `generateAPIPodStatus`.

However, `generateAPIPodStatus` might be executed concurrently from:

1. `kubelet.syncPod` <- `kubelet.syncCh`

https://github.com/kubernetes/kubernetes/blob/57a3aa3f13699cf3db9c52d228c18db94fa81876/pkg/kubelet/kubelet.go#L1524

2. `kubelet.cleanUpContainersInPod` <- `kubelet.plegCh`.

https://github.com/kubernetes/kubernetes/blob/57a3aa3f13699cf3db9c52d228c18db94fa81876/pkg/kubelet/kubelet.go#L2245

**Comment by aojea** [comment]
1.21 is EOL, you should report the issue with one of the supported versions https://kubernetes.io/releases/

**Comment by zhouhaibing089** [comment]
Yeah, I'm aware of that, but I figured it out it might still be useful for others who still runs v1.21.x. I don't expect a fix from community. But it would be great if people can find this.

**Comment by zhouhaibing089** [comment]
I also think it is not a bad idea to reflect and try to learn from the past. For instance, there is no need to sort in `generateAPIPodStatus` at all (which the HEAD still does) becasue it is already sorted in podcache.

**Comment by zhouhaibing089** [comment]
For people who wonder what a fix might look like, please take a look https://github.com/zhouhaibing089/kubernetes/commit/94e61f625d00d1d8c1414fd7d4a573425fa847b5.

/close

**Comment by aojea** [comment]
> I also think it is not a bad idea to reflect and try to learn from the past. For instance, there is no need to sort in `generateAPIPodStatus` at all (which the HEAD still does) becasue it is already sorted in podcache.

patches are welcome :)

**Comment by zhouhaibing089** [comment]
Looks like I just repeated the investigation someone already did before. See https://github.com/kubernetes/kubernetes/pull/90216.

**Comment by zhouhaibing089** [comment]
> patches are welcome :)

Filed https://github.com/kubernetes/kubernetes/pull/117695
