### ISSUE TITLE
kube-scheduler started but streamwatcher error

### ISSUE THREAD

**Issue by seaurching** [kubernetes/kubernetes#117640]
### What happened?

Scheduler started normally, but there has a lot of errors in stderr console.Here is the error log
```
Apr 27 10:45:55 12-0-65-8.xpaas.lenovo.com systemd[1]: Started Kubernetes Scheduler.
………………
Apr 27 10:45:57 12-0-65-8.xpaas.lenovo.com kube-scheduler[55182]: I0427 10:45:57.251171   55182 tlsconfig.go:178] "Loaded client CA" index=1 certName="client-ca::kube-system::extension-apiserver-authentication::client-ca-file,client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file" certDetail="\"kubernetes\" [] groups=[lenovo] issuer=\"<self>\" (2023-04-25 05:06:00 +0000 UTC to 2083-04-10 05:06:00 +0000 UTC (now=2023-04-27 02:45:57.251133192 +0000 UTC))"
………………
Apr 27 10:46:00 12-0-65-8.xpaas.lenovo.com kube-scheduler[55182]: I0427 10:46:00.008574   55182 streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 27 10:46:00 12-0-65-8.xpaas.lenovo.com kube-scheduler[55182]: I0427 10:46:00.009167   55182 streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF
Apr 27 10:46:00 12-0-65-8.xpaas.lenovo.com kube-scheduler[55182]: I0427 10:46:00.009532   55182 streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF
```
The error log `streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF`  show in console

### What did you expect to happen?

Apr 27 10:46:00 12-0-65-8.xpaas.lenovo.com kube-scheduler[55182]: I0427 10:46:00.009167   55182 streamwatcher.go:111] Unexpected EOF during watch stream event decoding: unexpected EOF

A lot of above message show in console, how to remove it?

### How can we reproduce it (as minimally and precisely as possible)?

start cluster with below

[centos@12-0-65-8.xpaas.lenovo.com:/home/centos]
$ ps -ef|grep kube-scheduler
root      55182      1  3 10:45 ?        00:00:15 /data/server/k8smaster/bin/kube-scheduler --bind-address=0.0.0.0 --secure-port=10259--authentication-kubeconfig=/data/server/certs/kube-scheduler/kube-scheduler.kubeconfig --authorization-kubeconfig=/data/server/certs/kube-scheduler/kube-scheduler.kubeconfig --kubeconfig=/data/server/certs/kube-scheduler/kube-scheduler.kubeconfig --leader-elect=true --v=2
centos    55223  23523  0 10:52 pts/1    00:00:00 grep --color=auto kube-scheduler

[centos@12-0-65-8.xpaas.lenovo.com:/home/centos]
$ ps -ef|grep kube-controller
root      54938      1  0 10:27 ?        00:00:07 /data/server/k8smaster/bin/kube-controller-manager --bind-address=0.0.0.0 --allocate-node-cidrs=true --cluster-cidr=172.19.16.0/20 --cluster-name=kubernetes --cluster-signing-cert-file=/data/server/certs/ca.pem --cluster-signing-key-file=/data/server/certs/ca-key.pem --kubeconfig=/data/server/certs/kube-controller-manager/kube-controller-manager.kubeconfig --leader-elect=True --node-cidr-mask-size=24 --root-ca-file=/data/server/certs/ca.pem --service-account-private-key-file=/data/server/certs/ca-key.pem --service-cluster-ip-range=172.19.0.0/22 --use-service-account-credentials=true --secure-port=10257 --v=2
centos    55226  23523  0 10:52 pts/1    00:00:00 grep --color=auto kube-controller

[centos@12-0-65-8.xpaas.lenovo.com:/home/centos]
$ ps -ef|grep kube-apiserver
root      54530      1  5 09:37 ?        00:03:55 /data/server/k8smaster/bin/kube-apiserver --advertise-address=0.0.0.0 --etcd-cafile=/data/server/certs/ca.pem --etcd-certfile=/data/server/certs/kubernetes/kubernetes.pem --etcd-keyfile=/data/server/certs/kubernetes/kubernetes-key.pem --etcd-servers=https://12.0.65.145:2379,https://12.0.65.78:2379,https://12.0.65.8:2379 --bind-address=0.0.0.0 --anonymous-auth=false --secure-port=443 --authorization-mode=Node,RBAC --enable-bootstrap-token-auth=true --service-cluster-ip-range=172.19.0.0/22 --tls-cert-file=/data/server/certs/kubernetes/kubernetes.pem --tls-private-key-file=/data/server/certs/kubernetes/kubernetes-key.pem --client-ca-file=/data/server/certs/ca.pem --kubelet-client-certificate=/data/server/certs/kubernetes/kubernetes.pem --kubelet-client-key=/data/server/certs/kubernetes/kubernetes-key.pem --service-account-key-file=/data/server/certs/ca-key.pem --service-account-signing-key-file=/data/server/certs/ca-key.pem --service-account-issuer=master-api.xpaas.lenovo.com --allow-privileged=true --apiserver-count=3 --requestheader-client-ca-file=/data/server/certs/ca.pem --requestheader-allowed-names=aggregator --enable-aggregator-routing=true --enable-admission-plugins=NodeRestriction --proxy-client-cert-file=/data/server/k8smaster/plugin/metrics-server/metrics-server.pem --proxy-client-key-file=/data/server/k8smaster/plugin/metrics-server/metrics-server-key.pem --v=2
centos    55229  23523  0 10:52 pts/1    00:00:00 grep --color=auto kube-apiserver

### Kubernetes version

<details>

```console
$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-dirty", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"dirty", BuildDate:"2023-04-19T05:51:50Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-04-25T04:52:39Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
self managed openstack
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"


[centos@12-0-65-8.xpaas.lenovo.com:/home/centos]
$ uname -a
Linux 12-0-65-8.xpaas.lenovo.com 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker-ce
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
is your apiserver working correctly?

**Comment by seaurching** [comment]
> is your apiserver working correctly?

Yes, working correctly. Use `kubectl get cs` or `kubectl get lease` show components status and controller- manager‘s leader

**Comment by seaurching** [comment]
## The scheduler leader's log is nomarl
![image](https://user-images.githubusercontent.com/7349963/236409657-21d02482-0320-40f2-bf4b-025088fda5c5.png)
![image](https://user-images.githubusercontent.com/7349963/236409788-57e32333-f35d-4390-8082-29e6425f1d71.png)
## The other scheduler log have errors show streamwatcher
![Uploading image.png…]()

**Comment by pacoxu** [comment]
Is this issue fixed? Any update?

BTW, 1.23 is end of life in community.

The scheduler in 145 is a leader and works well. You may need to check the other scheduler kube config. Different scheduler may connect with different apiserver. `kubectl get cs` only shows the connected apiserver status. 
`kubectl get endpoints  kubernetes` may show all registered healthy apiserver endpoint.
