### ISSUE TITLE
Our docs need more diagrams

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11764]
We have lots of presentations with good diagrams. We need similar diagrams on the site in order to help new users understand the basic concepts and the system.

cc @kmerker

**Comment by bgrant0607** [comment]
Are we making any progress on this?

**Comment by RichieEscarez** [comment]
I'll start on this next week.

**Comment by bgrant0607** [comment]
Here's another example:
http://technosophos.com/2015/09/15/a-visual-guide-to-kubernetes.html

**Comment by bgrant0607** [comment]
I assume nothing is happening on this. Punting to 1.2.

**Comment by RichieEscarez** [comment]
Thanks. @MikeJeffrey and I recently decided that we could not contain this for v1.1. At this point, there has only been a couple discussions about how to generate the set of graphics that we need to cover our concepts and that can be shared between GKE and k8s. We decided that the new graphics should based on the current set of GKE icons and show the progression for an individual app to a multi-node cluster (perhaps it should extend to multiple clusters). Once all the sharable graphics are created and available, they can then be injected into the docs.

**Comment by pikeas** [comment]
Would love to see links to some of those presentations (here or in docs)!

**Comment by bgrant0607** [comment]
cc @mansoorj

**Comment by bgrant0607** [comment]
Screenshots and ASCII animations would be great, too. Or maybe change the background color of the inline quoted regions to make them pop out more.

**Comment by bgrant0607** [comment]
My most recent presentation has lots of diagrams that would be useful (many of which have appeared in previous presentations by others):
http://www.slideshare.net/BrianGrant11/wso2con-us-2015-kubernetes-a-platform-for-automating-deployment-scaling-and-operations

**Comment by janetkuo** [comment]
Closing this as a dup of https://github.com/kubernetes/kubernetes.github.io/issues/84
