### ISSUE TITLE
doc broken link - pods.html

### ISSUE THREAD

**Issue by jmccormick2001** [kubernetes/kubernetes#11772]
http://kubernetes.io/v1.0/docs/user-guide/pods.html

At the bottom of that page, the following link is used for the text 'Pod API' and is broken on July 23....

https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/v1.0.1/docs/api-reference/definitions.html#_v1_pod

**Comment by vishh** [comment]
cc @lavalamp

**Comment by lavalamp** [comment]
@krousey @nikhiljindal Seems like we should rewrite these links when we export to gh_pages?

**Comment by JanetKuo** [comment]
[ReplicationController API object](https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/v1.0.1/docs/api-reference/definitions.html#_v1_replicationcontroller) in [Replication Controller page](http://kubernetes.io/v1.0/docs/user-guide/replication-controller.html#api-object) and [Service API object](https://htmlpreview.github.io/?https://github.com/GoogleCloudPlatform/kubernetes/v1.0.1/docs/api-reference/definitions.html#_v1_service) in [Service page](http://kubernetes.io/v1.0/docs/user-guide/services.html#api-object) are broken too.

**Comment by nikhiljindal** [comment]
Yes @lavalamp is right.
We should rewrite these links before exposting to gh_pages. Instead of using htmlpreview, these should be pointing to kubernetes.io.
https://github.com/kubernetes/kubernetes/issues/13149 tracks that issue. Closing this one in favor of that.
