### ISSUE TITLE
Scheduler/Kubelet Responsibilities

### ISSUE THREAD

**Issue by AnanyaKumar** [kubernetes/kubernetes#11774]
There are a couple of functions in plugin/scheduler which I don't think belong there. For example:

CheckPodsExceedingCapacity
PodFitsResources

If fact, the kubelet calls CheckPodsExceedingCapacity in the scheduler. I don't think the Kubelet should depend on functions in scheduler. I think these functions belong in the Kubelet - the scheduler could have separate versions of them if it needs to approximate whether a pod fits.

**Comment by bprashanth** [comment]
This is more about where those functions are placed then whether they should be shared. 

Using the same function in both places makes things easier to reason about. The kubelet should safe guard itself from overcommit, and the scheduler should do its best to avoid putting the kubelet under duress. Having a cluster wide understanding of where we draw the line is important.

**Comment by AnanyaKumar** [comment]
Yup, it's more about where the functions are placed. My understanding is that the scheduler is meant to be pluggable, so the functions should ideally be moved.
