### ISSUE TITLE
Promote and move kubernetes/kubernetes jobs to new Prow build cluster (eks-prow-build-cluster)

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/kubernetes#117749]
This is a tracking issue for promoting and moving kubernetes/kubernetes jobs to new Prow build cluster running on AWS (eks-prow-build-cluster).

## Candidates

_Candidates are canary jobs that have satisfying success rate. Those canary jobs can replace existing jobs running in old build clusters_

* [x] [ci-kubernetes-kind-e2e-parallel-eks-canary](https://prow.k8s.io/?job=ci-kubernetes-kind-e2e-parallel-eks-canary): 47 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-integration-master-eks-canary](https://prow.k8s.io/?job=ci-kubernetes-integration-master-eks-canary): 46 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-verify-master-eks-canary](https://prow.k8s.io/?job=ci-kubernetes-verify-master-eks-canary): 40 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-e2e-kubeadm-kinder-eks-canary-1-27](https://prow.k8s.io/?job=ci-kubernetes-e2e-kubeadm-kinder-eks-canary-1-27): 46 success, 1 failure (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-integration-master-eks-canary-1-27](https://prow.k8s.io/?job=ci-kubernetes-integration-master-eks-canary-1-27): 24 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-verify-master-eks-canary-1-27](https://prow.k8s.io/?job=ci-kubernetes-verify-master-eks-canary-1-27): 24 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-kind-ipv6-e2e-parallel-eks-canary-1-27](https://prow.k8s.io/?job=ci-kubernetes-kind-ipv6-e2e-parallel-eks-canary-1-27): 23 success, 0 failures (https://github.com/kubernetes/test-infra/pull/29410)
* [x] [ci-kubernetes-kind-e2e-parallel-eks-canary-1-27](https://prow.k8s.io/?job=ci-kubernetes-kind-e2e-parallel-eks-canary-1-27): 22 success, 1 failure (https://github.com/kubernetes/test-infra/pull/29410)

## Next

_Next are jobs running in old build clusters that should get their canary jobs to verify that those jobs are working in the new cluster_

* [ ]

## Needs investigation

_Needs investigation are canary jobs that do not have satisfying success rate_

* [ ] [ci-kubernetes-kind-e2e-json-logging-eks-canary](https://prow.k8s.io/?job=ci-kubernetes-kind-e2e-json-logging-eks-canary): 46 success, 1 failure
* [ ] [ci-kubernetes-unit-eks-canary](https://prow.k8s.io/?job=ci-kubernetes-unit-eks-canary): 47 success, 0 failures
* [ ] [ci-benchmark-scheduler-perf-master-eks-canary](https://prow.k8s.io/?job=ci-benchmark-scheduler-perf-master-eks-canary): 0 success, 19 failures
* [ ] [periodic-cluster-api-provider-aws-e2e-eks-canary](https://prow.k8s.io/?job=periodic-cluster-api-provider-aws-e2e-eks-canary): 0 success, 2 failures

/sig k8s-infra
/area infra
/area infra/aws
/priority important-soon
/triage accepted
cc @dims @ameukam @jeefy @pkprzekwas

**Comment by aojea** [comment]
❤️ 💪 
/cc

**Comment by xmudrii** [comment]
Here's the PR to promote first batch of jobs: https://github.com/kubernetes/test-infra/pull/29410

**Comment by BenTheElder** [comment]
A note for migrating KIND jobs:

We are somewhat sensitive to the underlying OS/Kernel so we need to make sure that we don't for example migrate all kubernetes-sigs/kind presubmit jobs to the new cluster and not the kubernetes/kubernetes equivalent, we should have both the GKE cluster and the EKS cluster in presubmit in KIND on at least Kubernetes @ HEAD so we catch any fun kernel / cgroups / runc related issues before merging them and breaking other Kubernetes CI.


This is great to see :-)

**Comment by BenTheElder** [comment]
We should also look at migrating jobs which are not running on community build clusters yet, e.g. in most sig subprojects their lint and unit test jobs should be ready for migrating.

Moving jobs from the "default" legacy google.com cluster will help narrow the scope of migrating the remainder of Prow outside of google.com and make it easier to determine if we can fit the rest on kubernetes.io GCP with a direct lift and shift or if we need to continue mitigating their costs (e.g. most of these do not have requests/limits so that cluster cannot auto-scale and runs at a large fixed scale, but fixing that is high-effort).

**Comment by xmudrii** [comment]
> we should have both the GKE cluster and the EKS cluster in presubmit in KIND on at least Kubernetes @ HEAD so we catch any fun kernel / cgroups / runc related issues before merging them and breaking other Kubernetes CI.

I can change the PR so that we leave current kind canary jobs, just rename them to drop the canary suffix. @BenTheElder would that work?

> We should also look at migrating jobs which are not running on community build clusters yet, e.g. in most sig subprojects their lint and unit test jobs should be ready for migrating.

+1

> Moving jobs from the "default" legacy google.com cluster will help narrow the scope of migrating the remainder of Prow outside of google.com and make it easier to determine if we can fit the rest on kubernetes.io GCP with a direct lift and shift or if we need to continue mitigating their costs (e.g. most of these do not have requests/limits so that cluster cannot auto-scale and runs at a large fixed scale, but fixing that is high-effort).

@BenTheElder I'm not sure I fully understand this part. Is your idea that we focus on jobs running in the legacy google.com cluster, and then see about migrating jobs away from the community GKE cluster? I'm worried about the part related to requests/limits, but we can discuss how to solve that.

**Comment by BenTheElder** [comment]
> I can change the PR so that we leave current kind canary jobs, just rename them to drop the canary suffix. @BenTheElder would that work?

I think we just need coverage of both clusters in KIND repo-presubmit just in case.

> @BenTheElder I'm not sure I fully understand this part. Is your idea that we focus on jobs running in the legacy google.com cluster, and then see about migrating jobs away from the community GKE cluster? I'm worried about the part related to requests/limits, but we can discuss how to solve that.

The current list of jobs looks largely like jobs that are release/PR blocking and on the community cluster, I'm saying I think we can also migrate a lot of jobs that are on the legacy cluster. It won't drive down the kubernetes.io bill, but we're in OK shape there and an upcoming hurdle is finishing the migration now that the bill is in better shape.

So not so much a focus, as we should also include those.

I think a _lot_ of those jobs would be good candidates, a ton of sig project jobs should be suitable for migrating as they're not depending on external cloud resources similar to the current kubernetes/kubernetes focused list.

E.G. test-infra's own jobs would be good candidates

**Comment by xmudrii** [comment]
> The current list of jobs looks largely like jobs that are release/PR blocking and on the community cluster, I'm saying I think we can also migrate a lot of jobs that are on the legacy cluster. It won't drive down the kubernetes.io bill, but we're in OK shape there and an upcoming hurdle is finishing the migration now that the bill is in better shape.

I agree with that. Let me see in the upcoming days and try to come up with some list or something like that. I'll keep this issue updated.

**Comment by BenTheElder** [comment]
FWIW: I don't think we need checklist for the rest of the organization.

I think we should make a call to action to SIGs (dev@?) asking them to evaluate if they can migrate their jobs meeting an established criteria (such as not needing external GCE resources) to help us load balance the clusters and outlining the simple approach to flip the `cluster` field on their jobs. 

We can shard out filing PRs like that and let subproject owners review and approve those config updates.

**Comment by xmudrii** [comment]
This issue went quickly out of date and I don't think it makes sense to keep it updated for now. If needed, I'll create a new issue to track migration efforts.
/close
