### ISSUE TITLE
Deletion of pod with prestop hook takes longer than expected.

### ISSUE THREAD

**Issue by payall4u** [kubernetes/kubernetes#117798]
### What happened?

Deletion of pod with prestop hook takes longer than expected.

The logic of deleting a Pod is implemented through the `kubelet.killPod(pod, gracePeriodOverride)`, which is responsible for deleting all the of the pod container, including concurrently executing `PrestopHook` and `StopContainer`, as well as finally stopping the Sandbox. 

Initially, the `gracePeriodOverride` parameter was only used to override the graceful shutdown duration of `StopContainer` in the CRI interface. Only in some special cases (such as eviction, shutdown node, etc.) would this parameter be used. 

If the timeout parameter in StopContainer was not overridden, it would be `timeout = max(2s, pod.spec.TerminationGracePeriodSeconds - PrestopHookPeriod)`. 

After kubelet 1.22, `pod.spec.TerminationGracePeriodSeconds` is passed as a parameter to `kubelet.killPod` when calling kubelet.killPod, causing `StopContainer` to continue to use the full graceful shutdown duration of the pod instead of the remaining duration.
https://github.com/kubernetes/kubernetes/blob/dea1312e03a0d6b7bc73ff21fa243cccea419c76/pkg/kubelet/pod_workers.go#LL907C26-L907C26

**_This means that in kubelet 1.20 and below, assuming the pod.spec.TerminationGracePeriodSeconds is set to 120 seconds and the prestop executes a sleep for 50 seconds, the time left for `StopContainer` is 70 seconds. But in kubelet 1.22 and above, assuming the pod.spec.TerminationGracePeriodSeconds is set to 120 seconds and the prestop executes a sleep for 50 seconds, the graceful shutdown time left for the container is still 120 seconds._** 

This conflicts with the docs https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#hook-handler-execution.

### What did you expect to happen?

I want to know whether it is a code problem or a document problem. 

And may I submit a PR for this.

### How can we reproduce it (as minimally and precisely as possible)?

1. Change kubelet parameter --v=4.
2. Create pod as following.
3. `kubectl delete pod <pod name>`

``` yaml
spec:
  containers:
  - command:
    - sleep
    - "10000"
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    lifecycle:
      preStop:
        exec:
          command:
          - sleep
          - "10"
    name: sleep
  terminationGracePeriodSeconds: 20
```

We'll got
```
kuberuntime_container.go:608] "PreStop hook completed" pod="default/sleepy-7bc4895794-4fc9t" podUID=e2a303a5-692d-4f66-8884-7fe6357dcd84 containerName="sleep" contain
erID="containerd://d0db8e27f4d65d4c84f4c30cf229c3f7c31668f893f7282bba7210f4ed3a9f8f"
kuberuntime_container.go:705] "Killing container with a grace period override" pod="default/sleepy-7bc4895794-4fc9t" podUID=e2a303a5-692d-4f66-8884-7fe6357dcd84 conta
inerName="sleep" containerID="containerd://d0db8e27f4d65d4c84f4c30cf229c3f7c31668f893f7282bba7210f4ed3a9f8f" gracePeriod=20
kuberuntime_container.go:709] "Killing container with a grace period" pod="default/sleepy-7bc4895794-4fc9t" podUID=e2a303a5-692d-4f66-8884-7fe6357dcd84 containerName=
"sleep" containerID="containerd://d0db8e27f4d65d4c84f4c30cf229c3f7c31668f893f7282bba7210f4ed3a9f8f" gracePeriod=20
```

### Kubernetes version

<details>

```console
$ kubelet --version
1.22.5
```
or
```console
$ kubelet --version
1.26.1
```
</details>

### Cloud provider

<details>

</details>

### OS version

nop

### Install tools

nop

### Container runtime (CRI) and version (if applicable)

containerd 1.6.9/1.4.3

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by payall4u** [comment]
From https://github.com/kubernetes/kubernetes/pull/102344

**Comment by kannon92** [comment]
Would this be related too https://github.com/kubernetes/kubernetes/issues/113606?

**Comment by payall4u** [comment]
> Would this be related too #113606?

Maybe not. Issue #113606 is probably about the problem of long running operations affecting others. But this issue is about whether `pod.spec.TerminationGracePeriodSeconds` should include the cost of PreStopHook.

**Comment by SergeyKanzhelev** [comment]
@bobbypage is it known issue?

/triage accepted

the issue seems to have enough details

**Comment by ReigenDing** [comment]
Could I try to fix this? @payall4u

**Comment by Chaunceyctx** [comment]
https://github.com/kubernetes/kubernetes/pull/115835 this pr will fix this issue. FYI, this issue can be closed

**Comment by HirazawaUi** [comment]
Also think https://github.com/kubernetes/kubernetes/pull/115835 has addressed this issue, if there are any other thoughts please reopen this issue
