### ISSUE TITLE
Passing a non-pluralized resource to SelfSubjectAccessReview() does not error

### ISSUE THREAD

**Issue by shashankram** [kubernetes/kubernetes#117732]
### What happened?

While using the `SelfSubjectAccessReview` API, passing a non-pluralized resource `Pod` instead of the expected `pods` did not return an error, and instead returned the following ambiguous response: 
`{Allowed:false Denied:false Reason: EvaluationError:}`

### What did you expect to happen?

The API response should indicate an error or reason if the input is invalid.

### How can we reproduce it (as minimally and precisely as possible)?

Pass the resource as `Pod` instead of `pods` as the `Resource` in the API call.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2023-01-18T15:28:44Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
The authorization system treats the queried resources as opaque and simply matches them to granted permissions. The resources queried for authorization are not required to correspond to resources served by kube-apiserver.

**Comment by liggitt** [comment]
Sure, PRs to clarify API docs (or other usage docs on kubernetes.io) are welcome. Feel free to tag me or @deads2k for review
