### ISSUE TITLE
node.status.nodeInfo.kubeProxyVersion is a lie

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#117756]
`v1.Node` has a field `.status.nodeInfo.kubeProxyVersion`, about which [the API docs](https://github.com/kubernetes/kubernetes/blob/v1.27.0/staging/src/k8s.io/api/core/v1/types.go#L5250) say:

```
// KubeProxy Version reported by the node.
KubeProxyVersion string `json:"kubeProxyVersion" protobuf:"bytes,8,opt,name=kubeProxyVersion"`
```

but the field is [set by kubelet](https://github.com/kubernetes/kubernetes/blob/v1.27.0/pkg/kubelet/nodestatus/setters.go#L401), which does not actually know the kube-proxy version:

```
node.Status.NodeInfo.KubeletVersion = version.Get().String()
// TODO: kube-proxy might be different version from kubelet in the future
node.Status.NodeInfo.KubeProxyVersion = version.Get().String()
```

Not only is it possible that the kube-proxy version is different from the kubelet version, it's also possible that kube-proxy isn't even running on the machine.

This field should be marked as deprecated. Ideally kubelet would stop setting it but that might be considered an API break? If kubelet is going to continue setting it, then the API docs and the kubelet source should both be updated to indicate that the field is just an alias for `kubeletVersion` and does not actually indicate the kube-proxy version, and will be set even if kube-proxy is not running.

(Noticed by @liggitt)

/sig node
/sig network

**Comment by aojea** [comment]
> This field should be marked as deprecated. Ideally kubelet would stop setting it but that might be considered an API break?

https://grep.app/search?q=KubeProxyVersion

puff this is there since forever https://github.com/kubernetes/kubernetes/commit/086bb1ac0930398ca98c708cd971636fa2800f04

maybe we should just stop setting it in kubelet, it is better no information than wrong information, no?

/cc @thockin

**Comment by nikzayn** [comment]
Do let me know when I can start working on this after the confirmation @aojea

**Comment by thockin** [comment]
Yeah this is ancient history - I'd be OK to stop setting it, guarded by a
flag so users can fast-disable this change if they need.

**Comment by HirazawaUi** [comment]
@thockin I am willing to work on this, if there is any situation, please feel free to unassign
/assign

**Comment by danwinship** [comment]
@thockin: "guarded by a flag so users can fast-disable this change if they need". So a feature gate? Or do you mean a kubelet command-line/config flag that would stay around forever?

**Comment by HirazawaUi** [comment]
If a KEP is needed to complete the issue, I can create it, or is there still a need to continue the discussion?

**Comment by shaneutt** [comment]
We discussed this on the SIG Network sync today: there's a growing opinion that we should in fact set this as deprecated and then do the hard work of finding all the places using it and getting them off in time.

/triage accepted

Please move forward with this and let us know how we can be of assistance! :vulcan_salute:

**Comment by dcbw** [comment]
GCE cloud provider uses this to detect whether or not the node supports GCE health checks, which of course doesn't depend on kube-proxy but can be implemented by anything. We implement this for ovn-kubernetes becuase it's required for correct operation of the GCE LB in some cases.

https://github.com/kubernetes/cloud-provider-gcp/blob/56834ccf31b1eb41a3ca8f8dab2413007dd297fc/providers/gce/gce_healthchecks.go#L291

So some plan is needed to move GCE CP off this too.

**Comment by HirazawaUi** [comment]
Okay, I'll start research on it

**Comment by HirazawaUi** [comment]
This is my first time using KEP and I have written a draft ahead of time if anyone can review it and give suggestions and if all goes well, I will create a KEP based on it. 
https://docs.google.com/document/d/1YQAmJYt1Be_Xq5Su_RTht2lP-2s-LQ4HknsePQo7CC0/edit?usp=sharing

**Comment by danwinship** [comment]
@HirazawaUi I just skimmed it but overall it looks right (or at least, "ready to review"). Can you file a KEP? (First create a tracking issue in https://github.com/kubernetes/enhancements, then create a PR with the KEP text using the issue number as the KEP number.)
