### ISSUE TITLE
Unexpected Running state for DaemonSet Pods on NotReady worker nodes

### ISSUE THREAD

**Issue by keisukesakasai** [kubernetes/kubernetes#117769]
### What happened?

DaemonSet-created Pods remain in the Running state even when the worker node is in a NotReady state.

### What did you expect to happen?

A Pod is completely terminated.

### Summary
- Deploy a DaemonSet
- Confirm that all pods are in the ```Running``` state
- Shut down one worker node
- Verify that the shut down worker node is in the ```NotReady``` state
- After 5 minutes (with tolerationSeconds=300), confirm that the pod on the shut down worker node remain in the ```Running``` state

<details>

### Reproduce

Deploy a DaemonSet.
```yaml:daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ds
spec:
  selector:
    matchLabels:
      app: nginx-ds
  template:
    metadata:
      labels:
        app: nginx-ds
    spec:
      containers:
      - name: nginx
        image: nginx:1.24.0
```

Confirm that all pods are in the ```Running``` state
```console
$ k get po -owide
NAME             READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
nginx-ds-lf8z4   1/1     Running   0          40s   10.244.0.3   minikube       <none>           <none>
nginx-ds-lmcsx   1/1     Running   0          40s   10.244.1.2   minikube-m02   <none>           <none>
nginx-ds-mtfqf   1/1     Running   0          40s   10.244.2.2   minikube-m03   <none>           <none>
nginx-ds-pcr56   1/1     Running   0          40s   10.244.3.2   minikube-m04   <none>           <none>
```

Shutdown the worker node where the Pod is running.(In this case ```minikube-m02```)
```console
docker@minikube-m02:~$ sudo shutdown now
```
And the status of ```minikube-m02``` becomes NotReady.
```console
$ k get node
NAME           STATUS     ROLES           AGE     VERSION
minikube       Ready      control-plane   8m42s   v1.27.0
minikube-m02   NotReady   <none>          8m9s    v1.27.0
minikube-m03   Ready      <none>          7m40s   v1.27.0
minikube-m04   Ready      <none>          7m15s   v1.27.0
```

After 5 minutes (with tolerationSeconds=300, default), the pod (```nginx-ds-lmcsx```) on the shut down worker node remain in the ```Running``` state
```console
$ k get po -owide
NAME             READY   STATUS    RESTARTS   AGE   IP           NODE           NOMINATED NODE   READINESS GATES
nginx-ds-lf8z4   1/1     Running   0          10m   10.244.0.3   minikube       <none>           <none>
nginx-ds-lmcsx   1/1     Running   0          10m   10.244.1.2   minikube-m02   <none>           <none>
nginx-ds-mtfqf   1/1     Running   0          10m   10.244.2.2   minikube-m03   <none>           <none>
nginx-ds-pcr56   1/1     Running   0          10m   10.244.3.2   minikube-m04   <none>           <none>
```

And, ```nginx-ds-lmcsx``` Pod remains in the Running state, but as expected, commands such as exec do not work.
```console
$ k iexec nginx-ds-lmcsx
FATA[0018] unable to stream shell process: error dialing backend: dial tcp 192.168.49.3:10250: connect: no route to host

$ k iexec nginx-ds-mtfqf
#
```
</details>

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:10:18Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.0", GitCommit:"1b4df30b3cdfeaba6024e81e559a6cd09a089d65", GitTreeState:"clean", BuildDate:"2023-04-11T17:04:24Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none(on premise)
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux azure-vm-kubernetes 5.15.0-1029-azure #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

```sh
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```
# containerd --version
containerd containerd.io 1.6.8 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6

# runc --version
runc version 1.1.4
commit: v1.1.4-0-g5fd4c4d
spec: 1.0.2-dev
go: go1.17.13
libseccomp: 2.5.1
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

```
none
```

</details>

**Comment by iyear** [comment]
> [DaemonSet](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) pods are created with `NoExecute` tolerations for the following taints with no `tolerationSeconds`:
> - `node.kubernetes.io/unreachable`
> - `node.kubernetes.io/not-ready`
> This ensures that DaemonSet pods are never evicted due to these problems.

https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations

Does this fit the scenario you describe?

**Comment by keisukesakasai** [comment]
Hi @iyear, Thank you for your reply!

Yes, I understand that specification.

From a user's perspective, the Running status of pods on a not ready node seems to be misleading...Therefore, I feel that it would be expected for the Pod's status to be Terminating(similar to the behavior of deployment pods).

However, this might cause the pod to be recreated when the node becomes ready again, which might contradict the following specification:

"This ensures that DaemonSet pods are never evicted due to these problems."
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

For example, if the appearance of the status was PENDING, it might be more intuitive from a user's perspective.

**Comment by keisukesakasai** [comment]
Oops,I accidentally closed it.

**Comment by rahulbansod519** [comment]
Kubernetes periodically checks the node's status, and it may take some time for the control plane to detect that the node is in a NotReady state. During this time gap, it's possible for the pods to remain in the Running state until Kubernetes detects the issue and attempts to reschedule them

**Comment by keisukesakasai** [comment]
Hi @rahulbansod519 !

As we discussed above, DaemonSet pods are never evicted from the Node, so they continue to remain in the Running state even when the Node is NotReady.
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions

**Comment by keisukesakasai** [comment]
When I examine the pod condition of a DaemonSet pod on a NotReady node, I notice that 'Ready' is set to 'False'. However, 'ContainerReady' still remains in the 'Running' state, which seems to be misleading...
Pod conditions: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions

```console
$ k get no
NAME           STATUS     ROLES           AGE     VERSION
minikube       Ready      control-plane   5d17h   v1.27.0
minikube-m02   NotReady   <none>          14m     v1.27.0
minikube-m03   Ready      <none>          14m     v1.27.0
minikube-m04   Ready      <none>          14m     v1.27.0

$ k get po -owide | grep minikube-m02
nginx-ds-kgxsk   1/1     Running   1 (17m ago)   28m     10.244.1.2   minikube-m02   <none>           <none>

$ k describe po nginx-ds-kgxsk | grep Conditions: -A 5
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   True
  PodScheduled      True
```

**Comment by david972** [comment]
we currently have the same behaviour. even worst still running if the node is gone
kubernetes version : v1.28.1
