### ISSUE TITLE
Kube-ui unable to start 

### ISSUE THREAD

**Issue by mahesh3267** [kubernetes/kubernetes#11775]
Hi all, 

Myself configured kubernetes on baremetal ubuntu server, followed https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu.md. Having trouble to start the kube-ui controller, looks like my docker image is not able to pull the images. Please suggest.

```
root@server:/opt/kubernetes/cluster# kubectl get pods --all-namespaces
NAMESPACE     NAME               READY     STATUS                                                                  RESTARTS   AGE
kube-system   kube-ui-v1-ev5z1   0/1       Image: gcr.io/google_containers/kube-ui:v1.1 is not ready on the node   0          5m
root@server:/opt/kubernetes/cluster# docker pull gcr.io/google_containers/kube-ui:v1.1
Error response from daemon: invalid registry endpoint https://gcr.io/v0/: unable to ping registry endpoint https://gcr.io/v0/
v2 ping attempt failed with error: Get https://gcr.io/v2/: EOF
 v1 ping attempt failed with error: Get https://gcr.io/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry gcr.io` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/gcr.io/ca.crt
```

**Comment by vishh** [comment]
cc @brendandburns

**Comment by davidwalter0** [comment]
Are there instructions for installing gcr.io's certificate for docker?
A work around is to add

     --insecure-registry gcr.io

to the docker daemon's command. 

depending on your configuration this might be an option sourced from /etc/default/docker and requires a restart of the docker daemon to activate.

**Comment by mahesh3267** [comment]
Hi David, 

Thanks for your update. 

Myself had an issue in network level, was causing the issue. now we are able to pull the images. but still having trouble with docker webui access. Getting following error while browsing. 
```
Error: 'dial tcp 172.17.0.4:8080: i/o timeout'
Trying to reach: 'http://172.17.0.4:8080/'
```

**Comment by preillyme** [comment]
@mahesh3267 are you still seeing this issue?

**Comment by mahesh3267** [comment]
Hi Preilyme, 

Thanks for your update, yes still iam getting the following error , when i browse kube-ui.

```
Error: 'dial tcp 172.17.0.3:8080: i/o timeout'
Trying to reach: 'http://172.17.0.3:8080/'
```
```
root@server:/opt/kubernetes/cluster/ubuntu# kubectl get nodes
NAME             LABELS                                  STATUS
192.168.56.101   kubernetes.io/hostname=192.168.56.101   Ready
192.168.56.102   kubernetes.io/hostname=192.168.56.102   Ready
192.168.56.103   kubernetes.io/hostname=192.168.56.103   Ready
192.168.56.104   kubernetes.io/hostname=192.168.56.104   Ready
root@server:/opt/kubernetes/cluster/ubuntu# kubectl get pods --all-namespaces
NAMESPACE     NAME               READY     STATUS    RESTARTS   AGE
kube-system   kube-ui-v1-qq21m   1/1       Running   0          2m
root@server:/opt/kubernetes/cluster/ubuntu# kubectl get services --all-namespaces
NAMESPACE     NAME         LABELS                                                                         SELECTOR          IP(S)          PORT(S)
default       kubernetes   component=apiserver,provider=kubernetes                                        <none>            192.168.3.1    443/TCP
kube-system   kube-ui      k8s-app=kube-ui,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeUI   k8s-app=kube-ui   192.168.3.49   80/TCP
```

**Comment by linfan** [comment]
+1
I'm using CoreOS, and getting same issue, just a hint here it maybe related to flannel network:
https://groups.google.com/forum/#!topic/google-containers/KJ7grYHAreU

```
Error: 'dial tcp 172.17.0.16:8080: i/o timeout'
Trying to reach: 'http://172.17.0.16:8080/'
```

```
$ sudo kubectl get pod,rc,service --namespace=kube-system
NAME                READY     STATUS    RESTARTS   AGE
kube-dns-v8-luq63   4/4       Running   0          18h
kube-ui-v1-4uvwk    1/1       Running   0          14m
CONTROLLER    CONTAINER(S)   IMAGE(S)                                         SELECTOR                      REPLICAS
kube-dns-v8   etcd           gcr.io/google_containers/etcd:2.0.9              k8s-app=kube-dns,version=v8   1
              kube2sky       gcr.io/google_containers/kube2sky:1.11
              skydns         gcr.io/google_containers/skydns:2015-03-11-001
              healthz        gcr.io/google_containers/exechealthz:1.0
kube-ui-v1    kube-ui        gcr.io/google_containers/kube-ui:v1.1            k8s-app=kube-ui,version=v1    1
NAME       LABELS                                                                           SELECTOR           IP(S)            PORT(S)
kube-dns   k8s-app=kube-dns,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeDNS   k8s-app=kube-dns   10.100.0.10      53/UDP
                                                                                                                                53/TCP
kube-ui    k8s-app=kube-ui,kubernetes.io/cluster-service=true,kubernetes.io/name=KubeUI     k8s-app=kube-ui    10.100.247.239   80/TCP
```

**Comment by bgrant0607** [comment]
Please repost your question to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.

Before posting a new question, please search stackoverflow for answers to similar questions, and also familiarize yourself with:
  * [the user guide](http://kubernetes.io/v1.0/)
  * [the troubleshooting guide](http://kubernetes.io/v1.0/docs/troubleshooting.html)

Again, thanks for using Kubernetes.

The Kubernetes Team

**Comment by thuey** [comment]
I'm having the same followup issue:
```
Error: 'dial tcp 172.17.0.4:8080: i/o timeout'
Trying to reach: 'http://172.17.0.4:8080/'
```
Was a SO post ever created? Or a solution found?
