### ISSUE TITLE
error: unable to upgrade connection: error dialing backend: unknown scheme: ws

### ISSUE THREAD

**Issue by luomengY** [kubernetes/kubernetes#117754]
### What happened?

error: unable to upgrade connection: error dialing backend: unknown scheme: ws

### What did you expect to happen?

"kubectl exec -it eureka-0 bash" error: "error: unable to upgrade connection: error dialing backend: unknown scheme: ws", the container engine is isulad.

### How can we reproduce it (as minimally and precisely as possible)?

k8s v1.25.9
isulad 2.1.1
cmd:
kubectl exec -it -n kube-system kube-proxy-45bbb /bin/sh

### Kubernetes version

k8s v1.25.9
isulad 2.1.1

### Cloud provider

null

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by luomengY** [comment]
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

Linux bigdata.master 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aojea** [comment]
/sig api-machinery

@luomengY you have to provide  more details, run the  kubectl command with `-v7`per example to have more detaiils of the failure.

Also, describe better your environment, is a vanilla kubernetes cluster? what is `isulad`?

**Comment by luomengY** [comment]
Isulad is like docker container solution, project address is: https://gitee.com/openeuler/iSulad.
My k8s cluster is installed on centos-7.6.How does kubectl switch SPDY to websocket?
The error log details are as follows:
[root@bigdata ~]# kubectl exec -it -n kube-system kube-proxy-45bbb  -v7  /bin/sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
I0503 23:25:55.872652   31744 loader.go:374] Config loaded from file:  /root/.kube/config
I0503 23:25:55.910138   31744 round_trippers.go:463] GET https://121.4.115.5:6443/api/v1/namespaces/kube-system/pods/kube-proxy-45bbb
I0503 23:25:55.910159   31744 round_trippers.go:469] Request Headers:
I0503 23:25:55.910173   31744 round_trippers.go:473]     Accept: application/json, */*
I0503 23:25:55.910182   31744 round_trippers.go:473]     User-Agent: kubectl/v1.25.9 (linux/amd64) kubernetes/a1a87a0
I0503 23:25:55.935196   31744 round_trippers.go:574] Response Status: 200 OK in 24 milliseconds
I0503 23:25:55.937477   31744 podcmd.go:88] Defaulting container name to kube-proxy
I0503 23:25:55.937823   31744 round_trippers.go:463] POST https://121.4.115.5:6443/api/v1/namespaces/kube-system/pods/kube-proxy-45bbb/exec?command=%2Fbin%2Fsh&container=kube-proxy&stdin=true&stdout=true&tty=true
      I0503 23:25:55.937831   31744 round_trippers.go:469] Request Headers:
                                                                           I0503 23:25:55.937840   31744 round_trippers.go:473]     X-Stream-Protocol-Version: v4.channel.k8s.io
                                                                         I0503 23:25:55.937847   31744 round_trippers.go:473]     X-Stream-Protocol-Version: v3.channel.k8s.io
                                                                       I0503 23:25:55.937853   31744 round_trippers.go:473]     X-Stream-Protocol-Version: v2.channel.k8s.io
                                                                     I0503 23:25:55.937860   31744 round_trippers.go:473]     X-Stream-Protocol-Version: channel.k8s.io
                                                                I0503 23:25:55.937866   31744 round_trippers.go:473]     User-Agent: kubectl/v1.25.9 (linux/amd64) kubernetes/a1a87a0
                                                                              I0503 23:25:55.974300   31744 round_trippers.go:574] Response Status: 500 Internal Server Error in 36 milliseconds
                                                                                         error: unable to upgrade connection: error dialing backend: unknown scheme: ws

**Comment by aojea** [comment]
> Isulad is like docker container solution,

ok, so you say you are not using crio or containerd as backend, this Isulad project that implements the CRI API https://gitee.com/openeuler/iSulad#cri

If that projects doesn't implement the streaming expected for those CRI commands of exec, attach and port-foward https://github.com/containerd/containerd/tree/bed2bef9ad77e314d7734ce8ba439479eeb0647e/pkg/cri/streaming

that may explain why the command fails.

You can test directly in the node using the  `crictl` https://github.com/kubernetes-sigs/cri-tools to exec into a pod, if that fails locally in a node, then you should open a bug with iSulad.

What  is really wrong is the error message

> error: unable to upgrade connection: error dialing backend: unknown scheme: ws

we have to dig that up, but please confirm first that Isulad supports these features

/cc @seans3

**Comment by luomengY** [comment]
Currently iSulad CRI exec uses websocket, kubectl uses SPDY by default, now api-server also supports websocket, now we just need to switch kubectl from SPDY to websoket, the problem now is that we don't know how to switch. Making that someone had mentioned the problem: https://github.com/kubernetes/kubernetes/issues/89163

**Comment by aojea** [comment]
> kubectl from SPDY to websoket

that is going to be implemented hopefully this relase , @seans3 is going to write the KEP to do it

**Comment by luomengY** [comment]
very thankful!

**Comment by fedebongio** [comment]
@seans3 was this one solved?

**Comment by seans3** [comment]
@luomengY

In order to take advantage of the new WebSockets functionality in the API Server, your client needs to communicate with version 1.29 (if the feature flag for WebSockets is enabled) or 1.30 (where the WebSockets functionality is default) for `exec`, `cp`, and `attach`. Your client must negotiate remote command subprotocol `v5.channel.k8s.io`. Please have a look at how this is accomplished in `kubectl`: 

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/remotecommand/websocket.go#L119

/close
