### ISSUE TITLE
[FG:InPlacePodVerticalScaling] Scheduler should use max(Spec.Resources.Requests, Status.Resources.Requests) instead of Status.AllocatedResources

### ISSUE THREAD

**Issue by vinaykul** [kubernetes/kubernetes#117765]
### What happened?

Current implementation of in-place pod resize looks at max(Spec.Resources, Status.Resources) which works well when resources are being increased, and works well when resources are being decreased assuming that the decrease request is based on observed lower usage, and the new lowered resources does not exceed current usage.

https://github.com/kubernetes/kubernetes/blob/d86b74b0176c6fa22ba2559ace961fa25c6e98cf/pkg/api/v1/resource/helpers.go#L64-L73

However, a bad actor can game the system by requesting resize to resources lower than current usage, and kubelet grants it not knowing that runtime cannot enforce it, and scheduler may schedule pods to an oversubscribed node. A simple way to avoid this is to use Status.Resources.Requests instead of Status.AllocatedResources.

This also means that containerd and other runtimes need to be at a version that supports the feature so that users get the correct signals (avoid 'forever InProgress')

### What did you expect to happen?

When desired resources are lowered and kubelet admits it and sets status to InProgress, scheduler should schedule new pods against resources that are actually available. Bad actors should not be allowed to game the system.

### How can we reproduce it (as minimally and precisely as possible)?

Resize a running pod by decreasing its memory below current usage.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.27.0
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by vinaykul** [comment]
This issue came up during a discussion with Jordan.
/sig node
/cc @vinaykul @liggitt

**Comment by SergeyKanzhelev** [comment]
/remove-lifecycle stale

seems to still be relevant

**Comment by tallclair** [comment]
Should this still consider allocated resources too? In other words, should it be `max(spec.resources, status.resources)`, or `max(spec.resources, status.allocatedResources, status.resources)`?

I think the same logic also applies for ResourceQuota, but we should audit everywhere this function is used to see if the same logic is desired there.

**Comment by tallclair** [comment]
Vivek isn't an org member (yet!), but will be working on this.

/assign

**Comment by tallclair** [comment]
Actually, I'll be taking this as a subtask of https://github.com/kubernetes/kubernetes/issues/128065
