### ISSUE TITLE
Consume zero-sized chunked body before hijacking the connection on SPDY upgrade

### ISSUE THREAD

**Issue by timofurrer** [kubernetes/kubernetes#117722]
### What happened?

We recently faced some [some problems](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/issues/393) when using our Kube API proxy with various Kubernetes distributions. 

Long story short, the error turned out to be that in our proxy we've sent an attach request like the following to the Kube API server (simplified):

```
POST /api/v1/namespaces/default/pods/tmp/attach? HTTP 1.1
Connection: Upgrade
Upgrade: SPDY/3.1
Transfer-Encoding: chunked

0

```

The reason for this is that the go standard library writes requests with a body where it cannot determine the size as "chunked" and automatically adds the `Transfer-Encoding: chunked` header - so that's why the request was proxied like illustrated above.

And this is actually a problem because on the server side the handler [upgrades the connection](https://github.com/kubernetes/kubernetes/blob/f51dad586ddc1a02b4fcc4e3974092ad78b630a7/staging/src/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go#LL86C9-L86C9) by sending the proper `101` response and "correctly" hijacking it - however it never consumed that empty chunk (`0 CR LF CR LF`) which is still readable.
This leads to those bytes being interpreted as malformed SPDY frames.

This is clearly solvable on the client side (our proxy) - which we did.

However, it would be nice if that empty chunked data would be consumed correctly before hijacking the connection for SPDY communication.

The question here is also if the HTTP body on an upgrade request could already contain data for the upgraded protocol - the RFC is pretty vague about this, but [hints](https://www.rfc-editor.org/rfc/rfc9110.html#name-upgrade:~:text=The%20capabilities%20and,to%20be%20repeated) that it's okay.

Weirdly enough this error was sporadic for us for different Kubernetes versions with different CRIs etc - so I kind of assume that some parts of the chain (maybe even only sometimes) consume that body and all works. It could also be that it works for some because one part of that chain doesn't hijack correctly - meaning they don't use the returned buffer with potentially unprocessed client data - so it may work sometimes and sometimes it doesn't - because chances are high that these `0 CR LF CR LF` end up in that buffer.

### What did you expect to happen?

A connection upgrade works even if that request contains a zero-sized chunk body.

### How can we reproduce it (as minimally and precisely as possible)?

n/a

### Anything else we need to know?

There is a larger write up of the exact problem we've faced [here](https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/issues/393).

### Kubernetes version

any

### Cloud provider

n/a

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by timofurrer** [comment]
I suppose this becomes less important now because of the websocket support. The request for websockets looks different and it shouldn't be affected by this (although I didn't verify).

**Comment by timofurrer** [comment]
@fedebongio I don't know what your workflow usually looks like - in this case the issue still persists, but it's probably a `#wontfix` ...

**Comment by seans3** [comment]
@timofurrer Thanks for bringing this issue to our attention. Since we have invested in transitioning to WebSockets for upgrading connections, and since SPDY has been deprecated for eight years, we only plan to fix critical SPDY issues. It sounds like you've addressed this issue with your client (the `kubectl` client does not send anything in the body when upgrading the connection). I'm going to close this issue. If you would like to petition to address this issue, I would suggest attending the SIG API Machinery bi-weekly meeting to discuss this issue with the SIG leadership.

/close
