### ISSUE TITLE
Better mechanism to decide Retry-After header

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#117734]
### What would you like to be added?

Make the value for Retry-After header of APF-rejected responses dynamic or user-adjustable instead of being constant 1

### Why is this needed?

When `kube-apiserver` APF rejects a request, it sets the HTTP response header with `Retry-After` of value 1 (ie. retry in 1 second). There was a TODO in https://github.com/kubernetes/apiserver/blob/master/pkg/server/filters/maxinflight.go#L38 to improve this since many years ago. 

Retry-After being 1 seems less reasonable to many cases when the kube-apiserver is heavily overloaded. 

As suggested in the TODO:

* one naive way to improve this is simply making it user-adjustable . 
* alternatively, it can be dynamic by recording count of 429s in past X mins and decide the Retry-After value up to what users have specified. The implementation needs more thoughts if we think the naive one is not good enough.

**Comment by aojea** [comment]
I think that this has been discussed more times in another context but I can't find the history

/sig api-machinery
/cc @MikeSpreitzer @wojtek-t

**Comment by linxiulei** [comment]
It should be closed by https://github.com/kubernetes/kubernetes/pull/117547
