### ISSUE TITLE
Make net.ipv4.tcp_keepalive_time a safe sysctl

### ISSUE THREAD

**Issue by JKrehling** [kubernetes/kubernetes#117873]
### What would you like to be added?

net.ipv4.tcp_keepalive_time is namespaced and it is used by several java clients for configuring the tcp behaviour. 

### Why is this needed?

1. It would be helpful to be able to configure this for applications without needing to modify the kubelet args. Notable for services with long running connections like elasticsearch   
Notably https://github.com/elastic/elasticsearch/issues/65213

2.  if kube-proxy is configured in IPVS mode which may kill long running connections if keep alives are not present  so having it readily configurable would be nice

**Comment by pacoxu** [comment]
https://github.com/torvalds/linux/commit/13b287e8d1cad951634389f85b8c9b816bd3bb1e 
Does this mean this sysctl has been changed to namespace since Linux kernel v4.5?

**Comment by aojea** [comment]
tuning the kernel settings for solving the idle connection problem is more complex than setting the tcp_keepalive option https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/

The best approach is to handle the logic at the application level, per example, kubernetes enables http2 ping frames for solving this problem https://github.com/kubernetes/kubernetes/pull/95981

**Comment by JKrehling** [comment]
I'm not sure if the above cloudflare situation will be similar to mine where the connections are left idle intentionally by the client. 

I believe these are namespaced as well so even the above doc recommends customizing them as needed though I agree it will not solve every problem it might make finding them easier if we don't have to rebuild the nodes.  

net.ipv4.tcp_keepalive_intvl 
net.ipv4.tcp_keepalive_probes

**Comment by thockin** [comment]
I think there are 2 issues here.  If this is actually safe, we should probably enable it (and all related sysctls that are safe).  @bobbypage to route?  Whether or not this solves @JKrehling issues for real, is a different question.  If people tweak these and it's safe to do so, we should let people do it.

**Comment by bobbypage** [comment]
> I think there are 2 issues here. If this is actually safe, we should probably enable it (and all related sysctls that are safe). @bobbypage to route? Whats the rule / process for this?

In general, we evaluate each sysctl one by one to understand if it's truly safe, i.e. can't impact the node or any other pods on the node. Most of the networking sysctls is namespaced as @pacoxu mentioned in https://github.com/kubernetes/kubernetes/issues/117873#issuecomment-1539275316, but we still need to ensure that setting this sysctl can't affected any other pods or node.

**Comment by JKrehling** [comment]
Thanks,  I was able to build a test cluster to test this. 
With springboot 3 https://github.com/spring-projects/spring-boot/pull/32051
and the sysctl settings set to 300s, allowed with the kubelet unsafe ctl flag 

![image](https://github.com/kubernetes/kubernetes/assets/25485833/b6909687-264c-48f9-880d-976e7c74f26a)

IPVS kube-config mode no longer kills my connections and the resets stop.  Other pods still maintain the default value 

k exec -it <pod1 on worker1> -- sysctl net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_time = 300
k exec -it <pod2 on worker1> -- sysctl net.ipv4.tcp_keepalive_time
net.ipv4.tcp_keepalive_time = 7200

**Comment by cyclinder** [comment]
Thanks @bobbypage, I will working on this.

**Comment by thockin** [comment]
/triage accepted

@cyclinder are you still working on this?

**Comment by cyclinder** [comment]
@thockin Sorry for the delay, Busy with work lately, I'll open a PR for this in a few days.
