### ISSUE TITLE
update pod spec in framework.PreBindPlugin

### ISSUE THREAD

**Issue by VincentYuan-hub** [kubernetes/kubernetes#117854]
### What happened?

i want to update pod spec in framework.PreBindPlugin
however, it is forbidden. 
<img width="1210" alt="3e3b0e00002a20d9e0eafd1aa6a8737" src="https://user-images.githubusercontent.com/41802365/236726412-76d11904-cae3-448b-aab1-0dfc1628a01d.png">

i think it should work. because, it it behaviour before bind node. the container had not stared

### What did you expect to happen?

it wont show error

### How can we reproduce it (as minimally and precisely as possible)?

1

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/sig scheduling

however, `GpuScheduling` is not in the default kube-scheduler. I think you may raise the issue in the wrong project.

**Comment by VincentYuan-hub** [comment]
> /sig scheduling
> 
> As the error shows, only several attributes can be changed after creation. Pod scheduling is after pod creation.
> 
> This is by design:
> 
> https://github.com/kubernetes/kubernetes/blob/6aa68d6a8b48c88348d4acd4e39f864b4634270b/pkg/apis/core/validation/validation.go#L4567-L4581
> 
> You may put the info in metada.labels/annotations in the PreBindPlugin. Or you should use webhook to update pod at pod creating process.

Thank for you response. 

In this situation, I want to add nvidia gpu code (NVIDIA_VISIBLE_DEVICES) to env. it can enabling GPUs in the container runtime .  Putting label/annotations will work. I can use annotations and env like this

`
- name: NVIDIA_VISIBLE_DEVICES
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['NVIDIA_VISIBLE_DEVICES']
`

I just wonder the container had not stared berfore i bind. it should have opportunity to change. 
 Is that the reason why I bring up issues. eg: It still can add nodeName in spec. It should check if the pod had been created.

In fact. it does not have any document to get which field can't update.

**Comment by pacoxu** [comment]
/remove-kind bug

The doc can be found in https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement.

**Comment by VincentYuan-hub** [comment]
> 

Thanks, it is not obvious and Env is not included.

**Comment by VincentYuan-hub** [comment]
> /remove-kind bug
> 
> The doc can be found in https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement. (Probably not that obvious.)


Thanks, it is not obvious and Env is not included.

**Comment by kerthcet** [comment]
> In fact. it does not have any document to get which field can't update

Kubernetes is build as declarative api, what you create is what you want, mutable fields will break this contract. I think we can close it now. Reopen if you think necessary.
/close
