### ISSUE TITLE
kube-apiserver process memory utilization is getting high frequently

### ISSUE THREAD

**Issue by 001Sam100** [kubernetes/kubernetes#117840]
Hi Team,

I'm using on-premises Kubernetes cluster with v1.23.1 version. Recently, started facing high memory utilization of kube-apiserver process and resultant master node is going in hang mode frequently.

NAME                 STATUS    MESSAGE                         ERROR
controller-manager   Healthy   ok
scheduler            Healthy   ok
etcd-2               Healthy   {"health":"true","reason":""}
etcd-1               Healthy   {"health":"true","reason":""}
etcd-0               Healthy   {"health":"true","reason":""}

etcd Version: 3.5.6
Git SHA: cecbe35ce
Go Version: go1.16.15
Go OS/Arch: linux/amd64

May 06 08:15:18 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:18.777-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"152.927291ms","expected-duration":"100ms","prefix":"","request":"header:<ID:4281102368606622801 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/minions/k5sworker10\" mod_revision:544574775 > success:<request_put:<key:\"/registry/minions/k5sworker10\" value_size:16385 >> failure:<request_range:<key:\"/registry/minions/k5sworker10\" > >>","response":"size:22"}
May 06 08:15:19 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:19.679-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"114.120258ms","expected-duration":"100ms","prefix":"","request":"header:<ID:7410822634824759847 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/horizontalpodautoscalers/test/test-oap-communication-service\" mod_revision:544574694 > success:<request_put:<key:\"/registry/horizontalpodautoscalers/test/test-oap-communication-service\" value_size:2581 >> failure:<>>","response":"size:22"}
May 06 08:15:21 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:21.498-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"125.445372ms","expected-duration":"100ms","prefix":"","request":"header:<ID:4281102368606622875 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/leases/csi-ceph/external-snapshotter-leader-rbd-csi-ceph-com\" mod_revision:544574892 > success:<request_put:<key:\"/registry/leases/csi-ceph/external-snapshotter-leader-rbd-csi-ceph-com\" value_size:439 >> failure:<request_range:<key:\"/registry/leases/csi-ceph/external-snapshotter-leader-rbd-csi-ceph-com\" > >>","response":"size:22"}
May 06 08:15:22 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:22.131-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"125.946981ms","expected-duration":"100ms","prefix":"","request":"header:<ID:17084554637774870482 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/leases/csi-ceph/rbd.csi.ceph.com-csi-ceph\" mod_revision:544574965 > success:<request_put:<key:\"/registry/leases/csi-ceph/rbd.csi.ceph.com-csi-ceph\" value_size:451 >> failure:<>>","response":"size:22"}
May 06 08:15:22 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:22.526-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"101.03481ms","expected-duration":"100ms","prefix":"","request":"header:<ID:7410822634824759925 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/configmaps/ingress-nginx/ingress-controller-leader\" mod_revision:544574871 > success:<request_put:<key:\"/registry/configmaps/ingress-nginx/ingress-controller-leader\" value_size:519 >> failure:<>>","response":"size:22"}
May 06 08:15:24 k5smaster3 etcd[138882]: {"level":"warn","ts":"2023-05-06T08:15:24.299-0500","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"173.928588ms","expected-duration":"100ms","prefix":"","request":"header:<ID:17084554637774870539 username:\"etcd-node-k5smaster1\" auth_revision:1 > txn:<compare:<target:MOD key:\"/registry/leases/kube-node-lease/k5sworker4\" mod_revision:544574857 > success:<request_put:<key:\"/registry/leases/kube-node-lease/k5sworker4\" value_size:486 >> failure:<>>","response":"size:22"}

**Comment by 001Sam100** [comment]
Any help would be really appreciated.

**Comment by pacoxu** [comment]
You may follow https://github.com/kubernetes/kubernetes/issues/98423#issuecomment-767635382 to check the memory.

**Comment by neolit123** [comment]
sorry, for not getting a reply but 1.23 is out of support.
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
