### ISSUE TITLE
Where can I find the `key_id` returned by the `EncryptRequest` procedure call and the `key_id` returned by the `Status` ?

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes/kubernetes#117889]
In https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/ : 

**The API server considers the key_id returned from the Status procedure call to be authoritative. Thus, a change to this value signals to the API server that the remote KEK has changed, and data encrypted with the old KEK should be marked stale when a no-op write is performed (as described below). If an EncryptRequest procedure call returns a key_id that is different from Status, the response is thrown away and the plugin is considered unhealthy. Thus implementations must guarantee that the key_id returned from Status will be the same as the one returned by EncryptRequest. Furthermore, plugins must ensure that the key_id is stable and does not flip-flop between values (i.e. during a remote KEK rotation)**

The `StatusResponse struct` https://github.com/kubernetes/kms/blob/master/apis/v2/api.pb.go#L73 has a field `KeyId` , but the `EncryptRequest struct` has `Uid` field

Where can I find the `key_id` returned by the `EncryptRequest` procedure call, in order to compare this `key_id` with the one returned by the `Status` ? 

By the way, with : 

    func (s *Server) getStatus(ctx context.Context, req *kms.StatusRequest) (*kms.StatusResponse) {
            resp, _ := s.Status(ctx, req)
            return resp
    }
    
    
    func (s *Server) Encrypt(ctx context.Context, req *kms.EncryptRequest) (*kms.EncryptResponse) {
    
            UId := req.Uid
            log.Println("UId-EncryptRequest: ", UId)
    
            statusReq := s.StatusRequest{
                    XXX_NoUnkeyedLiteral: {},
                    XXX_unrecognized: []byte,
                    XXX_sizecache: 10,
            }
    
            statusKId, _ := s.Status(ctx, statusReq)
    
            if (statusKId.KeyId != UId ) {
                    log.Printf("Watch out!")
                    return nil 
            }
    
            resp := s.Encrypt(ctx, req)
            log.Printf("Encrypt-resp: ", resp)
            return resp
    }

I get this other error `s.StatusRequest is not a type` : 

    root@k8s-eu-1-master:~/kms/apis/v2/api# go run ./server/main.go 
    # command-line-arguments
    server/main.go:58:24: s.StatusRequest is not a type
    server/main.go:59:39: missing type in composite literal

but here the StatusRequest struct type is defined : https://github.com/kubernetes/kms/blob/a38ec9832062d14d72f0f4cee8d6904a8be5fbee/apis/v2/api.pb.go#L43

**Comment by enj** [comment]
I am going to close this as we are discussing this on Kube slack at `#sig-auth-kms-dev`

/close
