### ISSUE TITLE
Configure which Workload APIs have default spreading

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#117887]
### What would you like to be added?

Add a configuration option the PodTopologySpread plugin to decide which APIs to take into account for spreading.
Currently, the implicit list contains: ReplicaSet, ReplicationController, StatefulSet and Service.

/sig scheduling

### Why is this needed?

The ability to disable spreading for some workload APIs can lead to better resource utilization.

In particular, by disabling support for Services, [Jobs that require a headless Service](https://kubernetes.io/docs/tasks/job/job-with-pod-to-pod-communication/) wouldn't be affected by spreading.

**Comment by ahg-g** [comment]
Exclude semantics would probably be useful: I want to spread services, but not jobs fronted by headless services.

**Comment by alculquicondor** [comment]
but most Services would be backed by ReplicaSets. So just excluding Services might be enough.

**Comment by kerthcet** [comment]
Seems the capacity of original selector spread plugin?

**Comment by Wel112** [comment]
Open this link it's isssue ,the original reasoning to include Services in default spread was to be generic,accept it by applying the triage/accepted ,run it

**Comment by alculquicondor** [comment]
But now there is an explicit topology spreading API.
If a set of Pods that are not using RS or SS need spreading, they can set a topology rule.
In other words, there is less motivation now for blindly spreading Services.
