### ISSUE TITLE
show update time in configmap or secret

### ISSUE THREAD

**Issue by jainpratik163** [kubernetes/kubernetes#117847]
### What would you like to be added?

whenever we are updating anything in secret or configmap , we are not able to find when it is updated .
only we see creation time.

if this feature is already there please tell how we can find.

### Why is this needed?

if we have this feature then it will be helpful for auditing , when CM/secret are lastly updated.

**Comment by pacoxu** [comment]
> This was effectively already requested in https://github.com/kubernetes/kubernetes/issues/73548, and effectively already exists as .metadata.managedFields[*].time

See https://github.com/kubernetes/kubernetes/issues/109522#issuecomment-1101701685

**Comment by Shubham82** [comment]
Thanks, @pacoxu
I'm closing this issue, as mentioned in the above comment it already exists in k8s.
@jainpratik163, Please reopen the issue if you will have any further doubts.
