### ISSUE TITLE
logcheck doesn't work with dockerized build

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/kubernetes#117831]
### What happened?

This is a subset of "make verify doesn't work under build/run.sh anymore" xref: https://github.com/kubernetes/kubernetes/issues/117821

In two places we assume the path for "local builds"
https://github.com/kubernetes/kubernetes/blob/ace6a79372113b8d850a58cdba740cdef4bc10ee/hack/golangci.yaml#L42

https://github.com/kubernetes/kubernetes/blob/ace6a79372113b8d850a58cdba740cdef4bc10ee/hack/golangci-strict.yaml#L41

But when dockerized it will be at `_output/dockerized/bin/logcheck.so`

### What did you expect to happen?

`build/run.sh make verify WHAT=golangci-lint` should work.

### How can we reproduce it (as minimally and precisely as possible)?

`build/run.sh make verify WHAT=golangci-lint`

**Comment by BenTheElder** [comment]
I'm not sure what the cleanest solution is here. Maybe a symlink in a fixed location that we update to point to whichever we just built ...

**Comment by BenTheElder** [comment]
cc @pohly

**Comment by pohly** [comment]
Can we set env variables as part of `build/run.sh`? golangci-lint doesn't support a search path for plugins yet, but perhaps that can be added.

**Comment by BenTheElder** [comment]
> Can we set env variables as part of build/run.sh? golangci-lint doesn't support a search path for plugins yet, but perhaps that can be added.

Bit of a blunt instrument but we could do that. Another blunt approach would be picking some unused path under _output to add a symlink to either I guess.

**Comment by BenTheElder** [comment]
It would be really nice if we could just pass searchpaths for the plugins instead of having to pass a complete path.

**Comment by BenTheElder** [comment]
https://github.com/golangci/golangci-lint/pull/1572 relative paths are resolved relative to the config file, so you can indirectly change a root path on a fixed file by using different config paths and not have to edit the file contents ... we could use two symlinks in _output to the actual config file.

Still not ideal.

**Comment by BenTheElder** [comment]
This is one of the few remaining verify scripts that doesnt work on mac or otherwise dockerized.

**Comment by pohly** [comment]
Let's fix this by making the path absolute in a temporary copy of the golangci-lint config file: https://github.com/kubernetes/kubernetes/pull/121501

Syncing .git is relevant for testing PRs, but it seems that https://github.com/kubernetes/kubernetes/pull/117827 already ensured that it is available.
