### ISSUE TITLE
build/run.sh does not work with podman

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#117816]
### What happened?

I tried to `build/run.sh make` on my Intel MacOS 12.6 machine, where I have podman installed and symlinked to "docker" in a directory on my path.  Commands that invoke "docker" work as expected.  I am not using Docker because of license and payment issues.  But `build/common.sh` insists that Docker's socket exists, even though podman uses a different socket.

### What did you expect to happen?

I expected to be able to `build.run.sh` with a functioning "docker" command on my `$PATH`.

### How can we reproduce it (as minimally and precisely as possible)?

I think the above description is pretty minimal.

### Kubernetes version

<details>

Current source

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
$ uname -a
Darwin mjs12 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64
```

</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by BenTheElder** [comment]
See previously: https://github.com/kubernetes/kubernetes/issues/79048#issuecomment-502847403

And this thread in slack.k8s.io: https://kubernetes.slack.com/archives/C09R23FHP/p1683305137427389

We don't support podman for building Kubernetes. Docker is open source and can be run without any license/payment, and podman is NOT docker and is NOT fully docker compatible.

**Comment by BenTheElder** [comment]
This check is there to prevent users filing bugs about podman not working (like https://github.com/kubernetes/kubernetes/issues/99025) when it's not supported to begin with. The build depends on docker.

/sig release

cc @dims @cblecker @thockin (fellow hack/ and build/ maintainers)

**Comment by dims** [comment]
Sorry nope, we won't be able to support podman, we can accept patches if filed, but we won't continue to guarantee that it will work going forward either.

**Comment by saschagrunert** [comment]
I'm going to close this one since I don't see much room for a resolution.
