### ISSUE TITLE
kubelet sync node status more frequently when node not ready

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#117801]
### What would you like to be added?

When kubelet  firstly startup and registrated, a CNI pod will be assigned to this node.  After the CNI pod finished initialization, the node should be `Ready` to run Pod.

Kubelet updates it status to apiserver periodically, as specified by --node-status-update-frequency. The default value is 10s. The latency will be 10s. It is not user-friendly for auto-scaling scenario.

If kubelet sync node status more frequently when node not ready, it can help to reduce the latency.

### Why is this needed?

Kubelet sync node status more frequently when node not ready, it will reduce the node `Ready` latency. Auto-scaling will benefit from it.

/sig node

**Comment by aojea** [comment]
this is already implemented, on startup it has a loop to improve the node startup latency

https://github.com/kubernetes/kubernetes/blob/7e25f1232a9f89875641431ae011c916f0376c57/pkg/kubelet/kubelet.go#L2827-L2846
