### ISSUE TITLE
deep copy generator can't handle recursive structs

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#11780]
assigning to @fgrzadkowski for possible re-assignment.  (or I can do it...)

**Comment by fgrzadkowski** [comment]
Re-assigning to @wojtek-t who is the author of this code.

**Comment by wojtek-t** [comment]
This will be fixed once we migrate to the new generated based on the framework. Should happen relatively soon.

**Comment by wojtek-t** [comment]
This should be fixed in the new generator.
