### ISSUE TITLE
Add a new metric `rollingUpdateDuration` to statefulset for measuring

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#117928]
### What would you like to be added?

A new metric `rollingUpdateDuration` in Statefulset controller, which helps to figure out how long it takes for rolling update.

### Why is this needed?

The new metric helps us to evaluate the consuming time during statefulset rolling update, we can optimize it based on the result like setting the `maxUnavailable` great than 1 if possible.

xref: part of https://github.com/kubernetes/enhancements/pull/3997

**Comment by nikzayn** [comment]
I would like to take this up.

/assign

**Comment by kerthcet** [comment]
cc @smarterclayton is this reasonable?

**Comment by kerthcet** [comment]
One thing makes it a little tricky is the rollingUpdateDuraion will increase as long as we scale the replicas.

**Comment by ppbits** [comment]
Adding @soltysh for opinion
cc @ritazh

**Comment by kerthcet** [comment]
Close as discussed here. https://github.com/kubernetes/kubernetes/pull/120074#issuecomment-1695466872
/close
