### ISSUE TITLE
When a pod completes, every pending pod is added back to active/backoff

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#117951]
### What happened?

When a pod completes, the scheduler moves all the pending pods back into the active/backoff.

In a busy cluster with multiple nodepools, this is not appropriate, as pods could get starved.

### What did you expect to happen?

https://github.com/kubernetes/kubernetes/blob/02659772cb2662600fb1273654bdb05921ae246e/pkg/scheduler/eventhandlers.go#L236

Here we could possibly run the pre-checks of the node where the pod was scheduled, like here:

https://github.com/kubernetes/kubernetes/blob/02659772cb2662600fb1273654bdb05921ae246e/pkg/scheduler/eventhandlers.go#L72

### How can we reproduce it (as minimally and precisely as possible)?

- Have 2 nodes, A and B
- Create 2 pods every second, that terminate in 1s, with high priority with node affinity to A
- Create a steady stream of pods that terminate in 1s, every 10s with low priority with node affinity to B

Observe how pods in a nodepool that target node B have higher latency to scheduling, even though there is enough capacity.

### Kubernetes version

Any

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
/sig scheduling
/sig scalability
cc @tosi3k

**Comment by alculquicondor** [comment]
This is actually not trivial.

For example, if an unschedulable Pod A has antiaffinity to a Pod B currently running in a zone, and the Pod B terminates, the Pod A could become schedulable, even if it doesn't fit in the node where Pod B was.

**Comment by alculquicondor** [comment]
cc @sanposhiho

**Comment by sanposhiho** [comment]
This should be solved by https://github.com/kubernetes/kubernetes/issues/114297.

**Comment by kerthcet** [comment]
I think we can close now since we have queueingHint for fine-gained requeueing.
/close
