### ISSUE TITLE
Publish the pod index as a label and annotation for Statefulset and indexed Job

### ISSUE THREAD

**Issue by ahg-g** [kubernetes/kubernetes#117986]
### What would you like to be added?

Currently the only way for a statefulset pod to identify its own index is by parsing the pod name, this is not convenient, it is easier if we set that as an annotation that users can set as an env var using the downward api. We already do this for Indexed Job.

Also, for both Indexed Job and StatefulSet it is useful to have the index set as a label as well so that it is simpler for filtering and selection.

### Why is this needed?

Setting the index as an annotation makes it easier to plumb that as an env var using the downward api.

Setting the index as a label allows for filtering and selecting the pods based on their index.

/sig apps

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/pull/68719 got very close for annotation.

There has been a lot of interest in this.  I think if we added the annotation to all pods it would be ok, and I've seen more examples of reasons people would need labels (so you can target traffic to the first instance of a set of copies of stateful sets), so having a way to give a name for the label we'd inject (i'm hesitant to auto-inject the label) would also be interesting.

I think we should do a quick KEP and get it on the sig-apps radar.  I think the annotation is unobjectionable because it's namespaced, but the label deserves some discussion on use case.

**Comment by smarterclayton** [comment]
https://github.com/kubernetes/kubernetes/issues/30427 is the canonical historical one.

**Comment by ahg-g** [comment]
what do you mean by "the annotation ... is namespaced"? and what is the concern with exposing the index as a label on the pods?

**Comment by ahg-g** [comment]
ok, by namespace you are referring to prefix domain we use for the annotation/label.

**Comment by sftim** [comment]
I think we could use a **label** to meet all the use cases listed so far. Are there any where an annotation is needed?
 
If we have a Job that is somehow defined not to be resized, we might also want to annotate the Pods for that Job with the total number of Pods (or maybe with the index of the last Pod). I wouldn't add that annotation for anything with scaling available, as it's likely to get expensive. An out-of-tree mechanism could put that in if people like lots of metadata writes.

**Comment by ahg-g** [comment]
I agree that label is probable good enough for all cases. 

I was discussing with @smarterclayton offline whether or not this needs a KEP; there are couple of open questions:

> can injecting a new label on all sts break existing workloads (it may force a redeploy?)

There are a couple of options:

1. Inject the label on newly created pods, so an existing statefulset/job may include pods with the label injected and some without. This is not an issue for the downward API because the user needs to recreate the statefulset anyway to make use of the label as an env var for example, but it will be surprising if the label is used for selection.

2. Inject the label only on newly created StatefulSet/Jobs, we can track this by annotating sts/jobs. The problem however is in cluster downgrades, which will cause the same issue in point 1.

3. Force redeploy, we shouldn't go this route because it is disruptive.

@soltysh any thoughts on this?

**Comment by sftim** [comment]
If people really want to have a different label key, they can make a controller that watches for the official label and their own label, and reconcile the two.

Labelling existing StatefulSet Pods shouldn't cause a redeploy / we can implement this so it doesn't. Setting metadata doesn't cause container or Pod replacement.

**Comment by smarterclayton** [comment]
I will note that labels are primarily used for serving, and batch jobs are rarely served, so while I think a reasonable starting point is autoinjection of a known label, I'm not confident the requirements directly translate.  Experience from batch only is indicative, but not automatic.  Agree if we can prevent visible impact to users it seems consistent with recent direction.

So requirements:

1. Adding the label (if automatic) can't be disruptive to existing workloads
2. Adding the label (if automatic) may have to deal with validation limits (i.e. if the created pod hits a limit)
3. We can always add the ability to change the label later (if automatic), we can't undo the requirement to add the label

An advantage of always adding the label is it makes the feature more relevant to existing workloads.

**Comment by sftim** [comment]
Index labels might let us do things like:
```shell
# unimplemented and untested
kubectl get pod -l 'batch.kubernetes.example/job-index gt 42' -o name | xargs something
```

**Comment by sftim** [comment]
I think a KEP would be good to capture user stories (but is more effort).

**Comment by smarterclayton** [comment]
Adding something like this is a KEP anyway.

**Comment by danielvegamyhre** [comment]
/assign

Discussed this with @ahg-g offline, I can work on a KEP for this.

**Comment by ahg-g** [comment]
This is tracked in https://github.com/kubernetes/enhancements/issues/4017

**Comment by brightchen** [comment]
what's the status of this feature. My project requires this feature. If it hasn't implement, is there are walk-around? Can I have a initContainers add label?  I tried following but get error: "Error from server (BadRequest): container "test-main" in pod "pod-with-label" is waiting to start: PodInitializing"

apiVersion: v1
kind: Pod
metadata:
  name: pod-with-label
spec:
  containers:
  - name: test-main
    image: alpine:latest
  initContainers:
  - name: set-label
    image: bitnami/kubectl:latest
    command: ['sh', '-c', 'kubectl label pod pod-with-label my-label=my-value']

**Comment by danielvegamyhre** [comment]
> what's the status of this feature. My project requires this feature. If it hasn't implement, is there are walk-around? Can I have a initContainers add label? I tried following but get error: "Error from server (BadRequest): container "test-main" in pod "pod-with-label" is waiting to start: PodInitializing"
> 
> apiVersion: v1 kind: Pod metadata: name: pod-with-label spec: containers:
> 
> * name: test-main
>   image: alpine:latest
>   initContainers:
> * name: set-label
>   image: bitnami/kubectl:latest
>   command: ['sh', '-c', 'kubectl label pod pod-with-label my-label=my-value']

It is beta in 1.28.
