### ISSUE TITLE
Remove very old etcd versions from the bundled versions list

### ISSUE THREAD

**Issue by jpbetz** [kubernetes/kubernetes#117906]
We should start retiring old etcd versions from the etcd migrator's [bundled versions list](https://github.com/kubernetes/kubernetes/blob/a5575425b039bf7c15dfaa9a7acf257fdc4fde3f/cluster/images/etcd/Makefile#L29) so that we can actually obsolete this when [etcd storage versioning](https://github.com/etcd-io/etcd/issues/13168) is implemented.

We'd need a reasonable policy on what stays and what is removed. Maybe look to the supported etcd minor versions?

Note that even if we remove bundled versions, an older version of the migrator can still be used to catch up.

/sig api-machinery

/help

**Comment by kkkkun** [comment]
According https://github.com/kubernetes/kubernetes/pull/117332#discussion_r1167300954,  current clientV3 only support etcd `3.4.x` and `3.5.x`

**Comment by kkkkun** [comment]
https://github.com/kubernetes/kubernetes/pull/117921 is merged.

/close
