### ISSUE TITLE
Pod created many times when node is OutOfcpu

### ISSUE THREAD

**Issue by katapultcloud** [kubernetes/kubernetes#117978]
### What happened?

A deployment with a single pod is scheduled multiple times with OutOfcpu error. The cluster starts with a single node, but ends up autoscaling to 3 (max nodes in the pool), with all pods hanging.

```
$ kubectl get deploy 
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
scheduler     1/1     1            1           4h3m
$ kubectl get rs
NAME                     DESIRED   CURRENT   READY   AGE
scheduler-65fd44c9b7     1         1         1       4h5m
```

```
$ kubectl get pod
NAME                         READY   STATUS     RESTARTS   AGE
scheduler-65fd44c9b7-2sj9j   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-2x5jc   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-4l8ph   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-4sbq2   0/1     OutOfcpu   0          141m
scheduler-65fd44c9b7-4vbvt   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-4zgql   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-566hn   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-58mhw   0/1     OutOfcpu   0          141m
scheduler-65fd44c9b7-5rpjr   1/1     Running    0          141m
scheduler-65fd44c9b7-676ln   0/1     OutOfcpu   0          142m
scheduler-65fd44c9b7-69hzl   0/1     OutOfcpu   0          141m
scheduler-65fd44c9b7-6hwcb   0/1     OutOfcpu   0          141m
scheduler-65fd44c9b7-6pdx5   0/1     OutOfcpu   0          141m
scheduler-65fd44c9b7-77f57   0/1     OutOfcpu   0          142m
many more times 
...
```

```
$ kubectl get node
NAME                                    STATUS   ROLES    AGE    VERSION
gke-cluster-299-pool-01-825d0b86-9lqf   Ready    <none>   144m   v1.26.3-gke.1000
gke-cluster-299-pool-01-825d0b86-g25p   Ready    <none>   142m   v1.26.3-gke.1000
gke-cluster-299-pool-01-825d0b86-sd5r   Ready    <none>   4h6m   v1.26.3-gke.1000
```

### What did you expect to happen?

Deployment with a single running replica. Possibly single pod waiting to be scheduled on a new autoscaled node.

### How can we reproduce it (as minimally and precisely as possible)?

Hit and miss this one. But deploy a single zone GKE cluster with a single node and create a deployment with set resource limits exceeding node resources.

### Anything else we need to know?

Related issue https://github.com/kubernetes/kubernetes/issues/106419

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.3-gke.1000
```

</details>

### Cloud provider

<details>
GCP
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
/sig scheduling
(tentatively)

Can you share the allocatable of the node where the pod is eventually scheduled? And the resource requests of the Pod.

**Comment by alculquicondor** [comment]
Also, can you check if this applies to you? https://github.com/kubernetes/kubernetes/issues/115325#issuecomment-1531931241

**Comment by kerthcet** [comment]
> a single node and create a deployment with set resource limits exceeding node resources

So you're saying the pod requests exceeds the node allocable resources. Seems more related to autoscaler rather than scheduler, IIRC, autoscaler will do dry run to accommodate for the pod.

**Comment by torbendury** [comment]
Also seeing this on `v1.27.3-gke.100`. We didn't safely reproduce the issue yet, but "now and then" we experience this. Quite strange that the Pods with status `OutOfCpu` are not automatically being deleted after the expected replica is successfully created.

**Comment by alculquicondor** [comment]
Also a Deployment? IIRC, the Deployment controller doesn't delete Failed pods.
They would eventually be deleted by the garbage collector.

Are you able to verify if this is affecting you? https://github.com/kubernetes/kubernetes/issues/115325#issuecomment-1531931241

**Comment by sushain97** [comment]
I'm experiencing a similar situation, also with `nodeName`:

```
k3s version v1.27.7+k3s2 (575bce76)
go version go1.20.10
```

Hundreds of pods are created and eventually cause the server to crawl to a standstill until I manually delete failed pods with `kubectl delete -A pod --field-selector=status.phase=Failed`.

This happens with `OutOfcpu` and `OutOfmemory`

**Comment by alculquicondor** [comment]
> Hundreds of pods are created and eventually cause the server to crawl to a standstill

It sound like you should adjust `terminated-pod-gc-threshold` to something much lower than the default of 12500

**Comment by sushain97** [comment]
@alculquicondor thanks for the suggestion! I'll try that out today.
