### ISSUE TITLE
unable to create any rc with volumes on mesos-cubernetes

### ISSUE THREAD

**Issue by loky9000** [kubernetes/kubernetes#11796]
I configured mesos-cubernetes according to https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/mesos.md

but when i try to create pod with volumes it won't work
for example https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/mysql.yaml
Task starting on mesos 
https://www.dropbox.com/s/8ln1187e7m7ldil/Screenshot%202015-07-24%2007.40.31.png?dl=0

Task stay in STARTING status couple of minutes and than goes to LOST state

https://www.dropbox.com/s/nivv6e3p840mrxv/Screenshot%202015-07-24%2010.43.35.png?dl=0 

but i see errors in stderr logs 
kubelet.go:1190] Unable to mount volumes for pod "mysql_default": metadata: GCE metadata "instance/zone" not defined; skipping pod

**Comment by thockin** [comment]
Can you maybe tell us what the errors are?  it would help.

**Comment by loky9000** [comment]
error added

**Comment by karlkfi** [comment]
I'm not sure I have the latest status on this, but last I checked volumes were not yet supported with the mesos provider. The reason is simply that [persistent volumes](https://issues.apache.org/jira/browse/MESOS-1554) were only recently added to Mesos in v0.24.0, which afaik is not released yet.

That said, you'd need to share the actual task logs (like task stderr and k8s scheduler/executor logs) to determine why exactly the task failed.

**Comment by sttts** [comment]
We have smoke tested the secret and empty volume, but not gce disks. But I think they should work even without persistent volume support of Mesos as they only access scsi disks on the local slaves with specific gce names.

@loky9000 Can you increase the executor log level to at least 5 (--executor-logv=5 or more at the scheduler command line)? In the sandbox of the task you should be able to see the log output. That will probably give us a better hint why it doesn't work.

**Comment by loky9000** [comment]
12725 kubelet.go:1423] Desired pods: mysql_default
I0727 18:57:09.015930   12725 volumes.go:96] Used volume plugin "kubernetes.io/gce-pd" for (volume.Spec){Name:(string)mysql-persistent-storage VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource){PDName:(string)mysql-disk FSType:(string)ext4 Partition:(int)0 ReadOnly:(bool)false} AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>} PersistentVolumeSource:(api.PersistentVolumeSource){GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> HostPath:(*api.HostPathVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil>}}
I0727 18:57:09.016051   12725 gce_pd.go:191] PersistentDisk set up: /tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/pods/3618250c-3491-11e5-9274-22000aea0129/volumes/kubernetes.io~gce-pd/mysql-persistent-storage false stat /tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/pods/3618250c-3491-11e5-9274-22000aea0129/volumes/kubernetes.io~gce-pd/mysql-persistent-storage: no such file or directory
I0727 18:57:09.016094   12725 gce_util.go:56] AttachAndMountDisk(pd, "/tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/plugins/kubernetes.io/gce-pd/mounts/mysql-disk") where pd is &gce_pd.gcePersistentDisk{volName:"mysql-persistent-storage", podUID:"3618250c-3491-11e5-9274-22000aea0129", pdName:"mysql-disk", fsType:"ext4", partition:"", readOnly:false, manager:(*gce_pd.GCEDiskUtil)(0x2a5ee50), mounter:(*mount.Mounter)(0x2a5ee50), diskMounter:(*gce_pd.gceSafeFormatAndMount)(0xc2091b6600), plugin:(*gce_pd.gcePersistentDiskPlugin)(0xc2084d7860), legacyMode:false}
E0727 18:57:09.017435   12725 kubelet.go:1190] Unable to mount volumes for pod "mysql_default": metadata: GCE metadata "instance/zone" not defined; skipping pod
I0727 18:57:09.017469   12725 kubelet.go:2245] Generating status for "mysql_default"
I0727 18:57:09.020962   12725 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysql", UID:"3618250c-3491-11e5-9274-22000aea0129", APIVersion:"v1", ResourceVersion:"427", FieldPath:""}): reason: 'failedMount' Unable to mount volumes for pod "mysql_default": metadata: GCE metadata "instance/zone" not defined
I0727 18:57:09.021565   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:09.021679   12725 status_manager.go:129] Ignoring same status for pod "mysql_default", status: {Phase:Pending Conditions:[{Type:Ready Status:False}] Message: Reason: HostIP:10.183.211.227 PodIP: StartTime:2015-07-27 18:56:39.007573016 +0000 UTC ContainerStatuses:[{Name:mysql State:{Waiting:0xc208fd3890 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:mysql:5.7 ImageID: ContainerID:}]}
E0727 18:57:09.021742   12725 pod_workers.go:111] Error syncing pod 3618250c-3491-11e5-9274-22000aea0129, skipping: metadata: GCE metadata "instance/zone" not defined
I0727 18:57:09.021918   12725 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysql", UID:"3618250c-3491-11e5-9274-22000aea0129", APIVersion:"v1", ResourceVersion:"427", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: metadata: GCE metadata "instance/zone" not defined
I0727 18:57:09.136603   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:10.140204   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:11.144019   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:12.147885   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:13.151957   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:14.156573   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:15.159739   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:16.165222   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:17.169181   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:18.173885   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:19.015774   12725 kubelet.go:1755] Periodic sync

**Comment by loky9000** [comment]
12725 kubelet.go:1423] Desired pods: mysql_default
I0727 18:57:09.015930   12725 volumes.go:96] Used volume plugin "kubernetes.io/gce-pd" for (volume.Spec){Name:(string)mysql-persistent-storage VolumeSource:(api.VolumeSource){HostPath:(*api.HostPathVolumeSource)<nil> EmptyDir:(*api.EmptyDirVolumeSource)<nil> GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource){PDName:(string)mysql-disk FSType:(string)ext4 Partition:(int)0 ReadOnly:(bool)false} AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> GitRepo:(*api.GitRepoVolumeSource)<nil> Secret:(*api.SecretVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> PersistentVolumeClaim:(*api.PersistentVolumeClaimVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil>} PersistentVolumeSource:(api.PersistentVolumeSource){GCEPersistentDisk:(*api.GCEPersistentDiskVolumeSource)<nil> AWSElasticBlockStore:(*api.AWSElasticBlockStoreVolumeSource)<nil> HostPath:(*api.HostPathVolumeSource)<nil> Glusterfs:(*api.GlusterfsVolumeSource)<nil> NFS:(*api.NFSVolumeSource)<nil> RBD:(*api.RBDVolumeSource)<nil> ISCSI:(*api.ISCSIVolumeSource)<nil>}}
I0727 18:57:09.016051   12725 gce_pd.go:191] PersistentDisk set up: /tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/pods/3618250c-3491-11e5-9274-22000aea0129/volumes/kubernetes.io~gce-pd/mysql-persistent-storage false stat /tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/pods/3618250c-3491-11e5-9274-22000aea0129/volumes/kubernetes.io~gce-pd/mysql-persistent-storage: no such file or directory
I0727 18:57:09.016094   12725 gce_util.go:56] AttachAndMountDisk(pd, "/tmp/mesos/slaves/20150727-141402-984891658-5050-2438-S0/frameworks/20150727-141402-984891658-5050-2438-0001/executors/aa7e5780b083864b_k8sm-executor/runs/0a5a876c-7f81-4da2-b3b1-866f1750d942/plugins/kubernetes.io/gce-pd/mounts/mysql-disk") where pd is &gce_pd.gcePersistentDisk{volName:"mysql-persistent-storage", podUID:"3618250c-3491-11e5-9274-22000aea0129", pdName:"mysql-disk", fsType:"ext4", partition:"", readOnly:false, manager:(*gce_pd.GCEDiskUtil)(0x2a5ee50), mounter:(*mount.Mounter)(0x2a5ee50), diskMounter:(*gce_pd.gceSafeFormatAndMount)(0xc2091b6600), plugin:(*gce_pd.gcePersistentDiskPlugin)(0xc2084d7860), legacyMode:false}
E0727 18:57:09.017435   12725 kubelet.go:1190] Unable to mount volumes for pod "mysql_default": metadata: GCE metadata "instance/zone" not defined; skipping pod
I0727 18:57:09.017469   12725 kubelet.go:2245] Generating status for "mysql_default"
I0727 18:57:09.020962   12725 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysql", UID:"3618250c-3491-11e5-9274-22000aea0129", APIVersion:"v1", ResourceVersion:"427", FieldPath:""}): reason: 'failedMount' Unable to mount volumes for pod "mysql_default": metadata: GCE metadata "instance/zone" not defined
I0727 18:57:09.021565   12725 kubelet.go:2178] pod waiting > 0, pending
I0727 18:57:09.021679   12725 status_manager.go:129] Ignoring same status for pod "mysql_default", status: {Phase:Pending Conditions:[{Type:Ready Status:False}] Message: Reason: HostIP:10.183.211.227 PodIP: StartTime:2015-07-27 18:56:39.007573016 +0000 UTC ContainerStatuses:[{Name:mysql State:{Waiting:0xc208fd3890 Running:<nil> Terminated:<nil>} LastTerminationState:{Waiting:<nil> Running:<nil> Terminated:<nil>} Ready:false RestartCount:0 Image:mysql:5.7 ImageID: ContainerID:}]}
E0727 18:57:09.021742   12725 pod_workers.go:111] Error syncing pod 3618250c-3491-11e5-9274-22000aea0129, skipping: metadata: GCE metadata "instance/zone" not defined
I0727 18:57:09.021918   12725 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"mysql", UID:"3618250c-3491-11e5-9274-22000aea0129", APIVersion:"v1", ResourceVersion:"427", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: metadata: GCE metadata "instance/zone" not defined

**Comment by sttts** [comment]
@loky9000 thanks for the logs. I took a look at the relevant code. It heavily depends on the gce cloud provider. I am not sure whether it can run autonomously next to the Mesos cloud provider. Maybe @thockin can comment on that.

**Comment by loky9000** [comment]
can i use aws storages instead?

**Comment by sttts** [comment]
same as for gce. If you are lucky it works. It also depends on the aws cloud provider.

**Comment by jdef** [comment]
at one point we had discussed the possibility of a hierarchical cloud provider so that you could stack, for example, the mesos provider on top of the gce provider; the goal being to leverage additional gce capabilities while running a k8s-mesos cluster.

it's not clear at this point in time how reasonable such an approach might be. the cloud provider API encompasses a wide range of functionality which would complicate "stacking" providers. that said, we should spend some effort investigating an approach to enable infra-specific capabilities (like gce storage) when using the mesos provider.

**Comment by jdef** [comment]
closing this out since because the user story is unsupported at this time
