### ISSUE TITLE
pod_scheduling_durating_seconds includes the time a Pod fails PreEnqueue

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#117979]
### What happened?

`pod_scheduling_durating_seconds` is recording the time that a Pod is gated.

We use the timestamp when the scheduler inserts the pod into the queue: https://github.com/kubernetes/kubernetes/blob/84c8abfb8bf900ce36f7ebfbc52794bad972d8cc/pkg/scheduler/internal/queue/scheduling_queue.go#L402

### What did you expect to happen?

The period of time when a Pod fails PreEnque (like being gated) shouldn't be accounted in the pod_scheduling_duration_seconds.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Pod with scheduling gates.
Wait some time before removing the gate.
Observe the `pod_scheduling_duration_seconds` metric

### Kubernetes version

<details>

```console
1.26+
```

</details>

### Cloud provider

<details>
Any
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Huang-Wei** [comment]
@helayoty would you want to take a stab on this issue?

**Comment by helayoty** [comment]
> @helayoty would you want to take a stab on this issue?

Yup, I can give it a shot.

/assign helayoty

**Comment by helayoty** [comment]
@alculquicondor , as we discussed, we can address this issue with different solutions:
1. Reset the pod timestamp to the current time `pInfo.Timestamp = time.Now()` [here](https://github.com/kubernetes/kubernetes/blob/84c8abfb8bf900ce36f7ebfbc52794bad972d8cc/pkg/scheduler/internal/queue/scheduling_queue.go#L385), so the gated time is substituted.
2. Unset timestamp `pInfo.Timestamp = time.Time{}`.
3.  Use a pointer to the timestamp and interpret `nil` as the newest timestamp, so the pod will go to the back of the queue.

I'll go ahead and implement solution no. 3, wdyt?

**Comment by alculquicondor** [comment]
sgtm. Any concerns @Huang-Wei ?

**Comment by Huang-Wei** [comment]
I think it should be option 1 + 3, and pInfo.**Timestamp** should be pInfo.**InitialAttemptTimestamp**, right? as `pod_scheduling_duration_seconds` records the time based on [InitialAttemptTimestamp](https://github.com/kubernetes/kubernetes/blob/7be3f8e43f73422ac622f12b9894814997b7d37a/pkg/scheduler/schedule_one.go#L253):

```diff
diff --git a/pkg/scheduler/internal/queue/scheduling_queue.go b/pkg/scheduler/internal/queue/scheduling_queue.go
index 37f8642d01d..5664a696e6c 100644
--- a/pkg/scheduler/internal/queue/scheduling_queue.go
+++ b/pkg/scheduler/internal/queue/scheduling_queue.go
@@ -386,6 +386,10 @@ func (p *PriorityQueue) addToActiveQ(pInfo *framework.QueuedPodInfo) (bool, erro
 		p.unschedulablePods.addOrUpdate(pInfo)
 		return false, nil
 	}
+	// If it's the first time a Pod passed PreEnqueue, reset pInfo.InitialAttemptTimestamp.
+	if pInfo.InitialAttemptTimestamp == nil {
+		pInfo.InitialAttemptTimestamp = time.Now()
+	}
 	if err := p.activeQ.Add(pInfo); err != nil {
 		klog.ErrorS(err, "Error adding pod to the active queue", "pod", klog.KObj(pInfo.Pod))
 		return false, err

```

**Comment by Huang-Wei** [comment]
@alculquicondor I think we should revisit this issue, in terms of its assumption:

> The period of time when a Pod fails PreEnque (like being gated) shouldn't be accounted in the pod_scheduling_duration_seconds.

So is it reasonable to always exclude time spent in PreEnqueue from `pod_scheduling_duration_seconds`? Note that PreEnqueue != SchedulingGates, `SchedulingGates` is one of the PreEnqueue's usecases. In other words, some user of PreEnqueue may want to include the time spent in PreEnqueue.

**Comment by Huang-Wei** [comment]
> `pod_scheduling_duration_seconds` is a signal that cluster providers can use to build SLOs.
> 
> The time spent before passing PreEnqueue is not under control of kube-scheduler, so considering it would not allow to build an SLO.

True, but comparing to state that metric X can or cannot be used to build SLO (which is hard IMO), I'm in favor of giving suggestion on SLI/SLO's semantic definition, for example: the official SLI definition of [pod_startup_latency](https://github.com/kubernetes/community/blob/master/sig-scalability/slos/pod_startup_latency.md) has a footnote clearly explaining its definition:

> By schedulable pod we mean a pod that has to be immediately (without actions from any other components) schedulable in the cluster without causing any preemption.

So if a pod is gated, it's not "immediately schedulable", and hence doesn't fall into the definition of pod_startup_latency.

**Comment by alculquicondor** [comment]
> So if a pod is gated, it's not "immediately schedulable", and hence doesn't fall into the definition of pod_startup_latency.

That is true, but there is no way today to exclude those pods from the metric, or separate the time.

Maybe we need an extra metric, but I think the new metric could be the one that includes the time guarded in PreEnqueue. It should probably be part of the KEP. The old metric is already stable, so we can't add labels. And it might already be in use for SLOs.

**Comment by Huang-Wei** [comment]
> That is true, but there is no way today to exclude those pods from the metric, or separate the time.

I think we should be working on that. And treat it as part of GA requirement for PodSchedulingReadiness.

**Comment by kerthcet** [comment]
An edge(maybe not edge) case is a pod's scheduling attempts is 0 but the `pod_scheduling_duration_seconds` is a long time, so prefer not to account for the waiting time when gated. 
For users not using PreEnqueue,  they will not be impacted, but for users using PreEnqueue, it's a break change for it increases the duration time. 
And we can add a new metric like `pod_in_scheduler_duration_seconds` to measure how long a pod stays in a scheduler.

**Comment by Huang-Wei** [comment]
I thought of "attempts", it's just I'm not sure it's a good idea to rely on "attempts" to define a SLI/SLO, b/c "attempts" is obtained from the in-memory `PodInfo` object and in a HA config env, it's _only_ updated by the primary scheduler instance. In other words, the value is inaccurate when the lease owner switches.

**Comment by helayoty** [comment]
@Huang-Wei @alculquicondor do we have a conclusion? Should we move on with the solution or remove this issue and the linked PR from the current release?

**Comment by alculquicondor** [comment]
I would like to move forward with this proposal. @Huang-Wei ?

**Comment by Huang-Wei** [comment]
To move it forward, I think we should add new metric(s) to _explicitly_ tell it's including or excluding the time spent on PreEnqueue.

**Comment by moficodes** [comment]
@helayoty @alculquicondor @Huang-Wei 

1.28 Bug Triage Shadow here.

Just checking-in, if this is still on track for the 1.28 release?

**Comment by alculquicondor** [comment]
We don't have a conclusion yet, but as a bug, it should qualify for changes after the freezes.
