### ISSUE TITLE
client-go failed to list and watch because the server was unable to return a response in the time allotted

### ISSUE THREAD

**Issue by qpzmtyv** [kubernetes/kubernetes#117925]
### What happened?

Hello all.
In my environment, (k8s version 1.24.4, 6 master nodes, 800 worker nodes, one hundred thousands custom resources(my crd) . if I create or update many custom resources concurrently, for example, update ten thousands custom resources at the same time, the kube-apiserver will run under high load, and all the client-go that list and watch my crd may stuck with error log below:

{"log":"W0511 07:00:24.551387       1 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:136: failed to list *v1.VirtualMachine: the server was unable to return a response in the time allotted, but may still be processing the request (get virtualmachines.flvmm.ctyun.cn)\n","stream":"stderr","time":"2023-05-11T07:00:24.551535701Z"}
{"log":"I0511 07:00:24.551534       1 trace.go:205] Trace[1854069548]: \"Reflector ListAndWatch\" name:vendor/k8s.io/client-go/informers/factory.go:136 (11-May-2023 06:44:28.305) (total time: 956245ms):\n","stream":"stderr","time":"2023-05-11T07:00:24.551643752Z"}
{"log":"Trace[1854069548]: ---\"Objects listed\" error:the server was unable to return a response in the time allotted, but may still be processing the request (get virtualmachines.flvmm.ctyun.cn) 956245ms (07:00:24.551)\n","stream":"stderr","time":"2023-05-11T07:00:24.551661658Z"}
{"log":"Trace[1854069548]: [15m56.245646421s] [15m56.245646421s] END\n","stream":"stderr","time":"2023-05-11T07:00:24.551666325Z"}
{"log":"E0511 07:00:24.551565       1 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:136: Failed to watch *v1.VirtualMachine: failed to list *v1.VirtualMachine: the server was unable to return a response in the time allotted, but may still be processing the request (get virtualmachines.flvmm.ctyun.cn)\n","stream":"stderr","time":"2023-05-11T07:00:24.551669321Z"}

Can anyone help to solve this problem, or get some suggest?
Are there any params that can be adjusted to optimize this issue?

 

### What did you expect to happen?

see above

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Kubernetes version

1.24.4

### Cloud provider

none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by qpzmtyv** [comment]
hello all. I check the log again and find the first error log is :

W0516 17:14:50.960196    1958 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:136: watch of *v1.VirtualMachine ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0516 17:14:50.960220    1958 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:136: watch of *v1.ConfigMap ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0516 17:14:50.960246    1958 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:136: watch of *v1.VirtualMachine ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0516 17:14:50.960270    1958 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:136: watch of *v1.VirtualMachine ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0516 17:14:50.960294    1958 reflector.go:442] vendor/k8s.io/client-go/informers/factory.go:136: watch of *v1.Pod ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
W0516 17:14:50.960315    1958 vm_manager.go:2571] syncNodeGetPodStats Patch Node error:%vPatch "https://lb-apiserver.kubernetes.local:1234/api/v1/nodes/cc-zjjh6b-x86-compute-e09-721": http2: client connection lost
W0516 17:25:34.887606    1958 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:136: failed to list *v1.VirtualMachine: the server was unable to return a response in the time allotted, but may still be processing the request (get virtualmachines.flvmm.ctyun.cn)
I0516 17:25:34.887664    1958 trace.go:205] Trace[25697986]: "Reflector ListAndWatch" name:vendor/k8s.io/client-go/informers/factory.go:136 (16-May-2023 17:14:51.848) (total time: 643038ms):

Can anyone help?

**Comment by aojea** [comment]
the connection to your frontend `virtualmachines.flvmm.ctyun.cn`  is not working, 

> Patch "https://lb-apiserver.kubernetes.local:1234/api/v1/nodes/cc-zjjh6b-x86-compute-e09-721": http2: client connection lost

**Comment by alexzielenski** [comment]
@qpzmtyv did the suggestion from @aojea not help you?

Closing since this issue seems to have gone stale. Please re-open if you feel we can help you further.
/close
