### ISSUE TITLE
replace references of https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io

### ISSUE THREAD

**Issue by rjsadow** [kubernetes/kubernetes#117949]
### What happened?

There are still references to https://storage.googleapis.com/kubernetes-release instead of https://dl.k8s.io/

dl.k8s.io is the correct advertised download host and will eventually move to be fastly shielding a fully community-owned bucket

ref: https://github.com/kubernetes/k8s.io/issues/2396

### What did you expect to happen?

Replace https://storage.googleapis.com/kubernetes-release with https://dl.k8s.io/

Also replace any gs://kubernetes-release references with using https://dl.k8s.io/ if applicable.

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nikzayn** [comment]
@rjsadow I would like to take this up!

**Comment by rjsadow** [comment]
> @rjsadow I would like to take this up!

Hey @nikzayn! Thanks so much for your interest, there's currently a PR out for review to resolve this issue https://github.com/kubernetes/kubernetes/pull/117950. But, there's a LOT more opprotunity in other projects/repo's to help this larger effort. Feel free to look for a repo that doesn't currently have a pr/issue assigned to it here https://github.com/kubernetes/k8s.io/issues/2396#issuecomment-1543696438

**Comment by nikzayn** [comment]
Sure no worries @rjsadow. Thanks for the guidance!

**Comment by rjsadow** [comment]
ChANGELOG references will not be updated at this time.
