### ISSUE TITLE
kubernetes 1.27 armhf packages not available

### ISSUE THREAD

**Issue by grunlab** [kubernetes/kubernetes#117996]
kubernetes 1.27 packages for armhf are currently not available:
https://packages.cloud.google.com/apt/dists/kubernetes-xenial/main/binary-armhf/Packages

Could you please make them available ?

Thank you

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/issues/115738 
arm support is dropped in v1.27.

**Comment by grunlab** [comment]
Oh damn, that's really a shame. Is it still possible to challenge/review this decision?

Until now, building a fully operational k8s cluster on armhf was OK as most of the surrounding projects are still supporting armhf architecture :
- weave-net
- metrics-server
- kubernetes-dashboard
- kube-state-metrics
- metallb
- traefik
- ...

Please, reconsider this decision.
