### ISSUE TITLE
Provide default readiness behavior

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#11797]
https://stackoverflow.com/questions/31574038/how-can-i-ensure-graceful-scaling-in-kubernetes/31602660#31602660

Makes me wonder if we can do better - for pods without readiness checks, could we offer a more graceful shutdown?  For example, when an RC is about to delete a pod, do the opposite of a binding, which would set the pod "unready", which would trigger Services to update their sets.  After a timeout (user configurable?  1 second default?) the pod object would actually be deleted.

**Comment by ArtfulCoder** [comment]
i agree that the stack-overflow question is valid and the kubernetes default behavior should be to:
1. unbind the pod from services
2. delete the pod ip from DNS if it is headless service

we shouldn't need to rely on healthcheck or pre-stop hook implementations..

**Comment by thockin** [comment]
I think Brendan's answer is correct, and we should endorse that model in
our examples.  I wonder if a "dumb" grace period might *also* be useful.

**Comment by bgrant0607-nocc** [comment]
cc @smarterclayton @dchen1107

**Comment by bgrant0607-nocc** [comment]
We need to finish the implementation of graceful termination.

**Comment by smarterclayton** [comment]
It's on my list this week.

On Jul 26, 2015, at 7:12 PM, Brian Grant <notifications@github.com> wrote:

We need to finish the implementation of graceful termination.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11797#issuecomment-125047328>
.

**Comment by bgrant0607** [comment]
See also #6804

**Comment by bgrant0607** [comment]
Renaming issue to "provide default readiness behavior".

**Comment by bgrant0607** [comment]
We may also need to fix initial readiness behavior. For instance, I don't know whether we have fixed the problem that readiness is delayed for pods with liveness probes with initial delays.

**Comment by smarterclayton** [comment]
I don't believe so.

On Aug 5, 2015, at 8:36 PM, Brian Grant <notifications@github.com> wrote:

We may also need to fix initial readiness behavior. For instance, I don't
know whether we have fixed the problem that readiness is delayed for pods
with liveness probes with initial delays.

—
Reply to this email directly or view it on GitHub
<https://github.com/GoogleCloudPlatform/kubernetes/issues/11797#issuecomment-128193863>
.

**Comment by bgrant0607** [comment]
See also #11234.

cc @yujuhong

**Comment by bgrant0607** [comment]
Graceful termination is in progress: #9165.

**Comment by thockin** [comment]
Shoiuld we close this now?

**Comment by bgrant0607** [comment]
I'm not sure it is fully resolved by graceful termination. cc @smarterclayton 

Also, that might still get reverted.

**Comment by smarterclayton** [comment]
Graceful attempt 3 is #12963

**Comment by dchen1107** [comment]
Graceful termination pr is merged, and setting initial readiness for container without readiness probe is captured separately by #11234. I am closing this one.
