### ISSUE TITLE
no endpoint created  for service 

### ISSUE THREAD

**Issue by loky9000** [kubernetes/kubernetes#11795]
HI
I've just a begin to play  with kubernetes and tried to create couple rc+service from yours examples. https://github.com/GoogleCloudPlatform/kubernetes/tree/master/examples/celery-rabbitmq
but i faced that flower-service not expose any endpoint after create

```console
kubectl  describe svc flower-service
Name:			flower-service
Namespace:		default
Labels:			name=flower
Selector:		app=taskQueue,component=flower
Type:			LoadBalancer
IP:			10.10.10.115
Port:			main	5555/TCP
NodePort:		main	30693/TCP
Endpoints:		<none>
Session Affinity:	None
No events. 
```

It's ok for rabbitmq-service but endpoint has port 31000 which not described in service definition 
```
kubectl --server=10.180.228.105:8888 describe svc rabbitmq-service
Name:			rabbitmq-service
Namespace:		default
Labels:			name=rabbitmq
Selector:		app=taskQueue,component=rabbitmq
Type:			ClusterIP
IP:			10.10.10.159
Port:			<unnamed>	5672/TCP
Endpoints:		10.235.129.14:31000
Session Affinity:	None
No events.
```

How it's posible? This is expected behaviour ?

**Comment by thockin** [comment]
http://kubernetes.io/v1.0/docs/user-guide/debugging-services.html

The likely culprit is that your Service's selector doesn't match any
Pod's labels.

**Comment by loky9000** [comment]
flower-controller
 apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: flower
  name: flower-controller
spec:
  replicas: 1
  selector:
    component: flower
  template:
    metadata:
      labels:
        app: taskQueue
        component: flower
    spec:
      containers:
      - image: endocode/flower
        name: flower
        resources:
          limits:
            cpu: 100m

flower-service

apiVersion: v1
kind: Service
metadata:
  labels:
    name: flower
  name: flower-service
spec:
  ports:
  - port: 5555
  selector:
    app: taskQueue
    component: flower
  type: LoadBalancer

as you can see service selector match to rc labels

**Comment by thockin** [comment]
I mis-parsed the original message, sorry.

Are these the full specs?  The port should be assumed to be 5555 since not targetPort is specified.

What kubernetes version, what OS, what cloud, and what process did you use to make this happen?

**Comment by loky9000** [comment]
Kubernetes v1.0.1
Ubuntu14.04
Mesos 0.22.0
service created by kubectl  
nothing change with targetPort  
kubectl expose create endpoint for pod but not rc

**Comment by thockin** [comment]
If I recall, you are using Mesos, so normal rules about endpoints and ports
do not apply.  That said,
http://kubernetes.io/v1.0/docs/user-guide/debugging-services.html still
applies mostly - did you try following that?

**Comment by loky9000** [comment]
endpoints creates for pod  but target port wrong

$kubectl   expose pod  mysql --port=3306 --target-port=3306
NAME      LABELS       SELECTOR     IP(S)     PORT(S)
mysql     name=mysql   name=mysql             3306/TCP
$ kubectl   describe svc mysql
Name:			mysql
Namespace:		default
Labels:			name=mysql
Selector:		name=mysql
Type:			ClusterIP
IP:			10.10.10.206
Port:			<unnamed>	3306/TCP
Endpoints:		10.183.211.227:31000
Session Affinity:	None
No events

**Comment by thockin** [comment]
Again, Mesos does different things with the ports.  What is the actual
problem you are experiencing?

**Comment by loky9000** [comment]
i want to expose custom port  for service  not random. why --target-port=3306 ignored?

**Comment by thockin** [comment]
Mesos maps all pod ports to host ports.  That's not something you can
control.  Is something actually not working?

**Comment by loky9000** [comment]
endpoint creating it something mysterious.
We have a pod:
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
    - resources:
        limits :
          cpu: 0.5
      image: mysql:5.7
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          # change this
          value: 1qaz2wsx
      ports:
      - containerPort: 5555
        name: flower

describe  pod mysql
Name:				mysql
Namespace:			default
Image(s):			mysql:5.7
Node:				/
Labels:				name=mysql
Status:				Pending
Reason:
Message:
IP:
Replication Controllers:	<none>
Containers:
  mysql:
    Image:	mysql:5.7
    Limits:
      cpu:		500m
    State:		Waiting
    Ready:		False
    Restart Count:	0

Lets try to expose that pod

kubectl --server=10.234.1.41:8888 expose pod mysql --port=3306 --target-port=3306
NAME      LABELS       SELECTOR     IP(S)     PORT(S)
mysql     name=mysql   name=mysql             3306/TCP

looks good but... 
kubectl --server=10.234.1.41:8888 describe svc  mysql
Name:			mysql
Namespace:		default
Labels:			name=mysql
Selector:		name=mysql
Type:			ClusterIP
IP:			10.10.10.241
Port:			<unnamed>	3306/TCP
Endpoints:		<none>
Session Affinity:	None
No events.

no endpoints created for this time and no ports listen on mesos slave where mysql docker container placed - so no access from external to mysql service on pod.

**Comment by thockin** [comment]
@karlkfi

**Comment by loky9000** [comment]
>Mesos maps all pod ports to host ports.  That's not something you can
control.  Is something actually not working?

Currently i have two pods  mysql and tomcat 
and i can't access  from tomcat container to mysql 3306 port via localhost:3306 like described here: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/admin/networking.md

**Comment by loky9000** [comment]
and another thing:
endpoints on all mesos slaves point on port 31000 maybe it's some mesos restriction 
```
kubectl --server=10.234.1.41:8888 get endpoints --namespace=kube-system
NAME       ENDPOINTS
kube-ui    10.182.203.143:31000
ubuntu@ip-10-234-1-41:/opt/kubernetes/repo$ kubectl --server=10.234.1.41:8888 get endpoints
NAME             ENDPOINTS
k8sm-scheduler   10.234.1.41:10251
kubernetes       10.234.1.41:6443
mysql            10.91.176.3:31000
tomcat           10.180.202.211:31000
```

**Comment by karlkfi** [comment]
Not all of the examples have been tested on Kubernetes-Mesos. 
It looks like you're missing a requires port name (a mesos-specific requirement). I don't know the exact reason for that, but it's documented on the mesos/contrib known issues page: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/contrib/mesos/docs/issues.md

@jdef may have more details on why. 

Let us know if that solves the issue.

**Comment by jdef** [comment]
@loky9000 which endpoint-controller are you using?

k8s-mesos implements some workarounds for people that have default docker networking (non-cluster-routable IPs for containers). as part of these workarounds, for each pod instance we allocate a host port for each pod port and create endpoints such that they map to the hostIP:hostPort of the pod, instead of the k8s default (podIP:podPort). connections to the allocated hostPort are proxied to the podPort by docker.

31000 looks like a port that the scheduler is allocating from a mesos resource offer (that's the beginning of the default "ports" resource range for slaves). if you try to create a pod with a pod.spec.container.port that uses a hostPort value outside of the range of the resource offers in the mesos cluster (the "ports" resources configured on your slaves), the pod will never be scheduled because the scheduler will never receive an offer that satisfies the hostPort requirements of the pod spec.

service ports, as karl mentioned (and linked to via issues.md) currently require some special treatment by the end user (try defining a name for each service.spec.port).

**Comment by jdef** [comment]
could be related to https://github.com/mesosphere/kubernetes-mesos/issues/322

**Comment by thockin** [comment]
Is this still valid, or should it be closed?

**Comment by jdef** [comment]
Needs more information from @loky9000. It sounds like you are trying to run two pods, and with the expectation that they'll communicate through localhost:xyz-mapped addresses, which will never work because that's not how k8s networking works. Only containers within the same pod can use localhost:xyz. I have no idea how you're setting up kubedns.

This has been sitting a while. Closing out for now, please re-open if you have additional context/details to provide.

**Comment by bryceroche** [comment]
> http://kubernetes.io/v1.0/docs/user-guide/debugging-services.html The likely culprit is that your Service's selector doesn't match any Pod's labels.



Thank you!!!  :D
