### ISSUE TITLE
Network policies only take effect when pods are assigned to the same node

### ISSUE THREAD

**Issue by AbelHugh** [kubernetes/kubernetes#118039]
### What happened?

I configured it according to the network policy demonstrated in the official document, and found that sometimes it takes effect and sometimes it does not. After investigation, I finally found that this example only takes effect when busybox and nginx are assigned to the same node, and it does not take effect if they are not on the same node.

url: https://kubernetes.io/docs/tasks/administer-cluster/declare-network-policy/

As shown in the figure, the first part is completely done according to the demonstration of the official document, just to keep the busybox container without '--rm', which can be seen through the command 'kubectl get pod, node -o wide', the first part busybox and nginx are always on the 'worker-130' node, and the expected result is correct. However, in the second part, I forcibly dispatched nginx to 'worker-131' and immediately lost the connection.

![image](https://github.com/kubernetes/kubernetes/assets/71317399/12d5c07a-ec8a-4f07-b20a-a8c096683d49)

### What did you expect to happen?

Network policies should not only take effect when the test container and the container under test are on the same node.

### How can we reproduce it (as minimally and precisely as possible)?

There are screenshots above

### Kubernetes version

1.24.4

### OS version

Ubuntu 20.04.5

### Install tools

kubeadm

### Container runtime (CRI) and version (if applicable)

runtime: containerd 1.6.16

### Related plugins (CNI, CSI, ...) and versions (if applicable)

cni: calico 3.24.1

**Comment by HirazawaUi** [comment]
Network policies are implemented by the network plugin, you should create a issue in the calico project
Refer to the link: https://github.com/projectcalico/calico/issues

**Comment by caseydavenport** [comment]
Based on the description, if I had to guess I would say this is a NAT issue. Something on the host is likely SNAT'ing the traffic so that the destination node doesn't recognize it's coming from a pod that should be allowed by the NP.

@AbelHugh I'd check to see if there are any NAT / MASQ rules on the source node being hit by this traffic and if so, why

**Comment by thockin** [comment]
Any update here, @AbelHugh ?
