### ISSUE TITLE
verify-typecheck checks binaries that don't actually get built

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#118020]
In #118017 I tried to reorganize the kube-proxy build a bit, and ran into the problem that verify-typecheck failed because `cmd/kube-proxy` was no longer buildable on darwin/amd64 and darwin/arm64. This was surprising because we don't build kube-proxy on OS X.

It seems like verify-typecheck ought to be taking `KUBE_SUPPORTED_*_PLATFORMS` / `KUBE_*_TARGETS` from `hack/lib/golang.sh` into account when deciding what to check. There's no reason to be checking the OS X type compatibility of binaries that we don't build on OS X.

**Comment by BenTheElder** [comment]
/remove-sig network
/sig testing

> It seems like verify-typecheck ought to be taking KUBE_SUPPORTED_*_PLATFORMS / KUBE_*_TARGETS from hack/lib/golang.sh into account when deciding what to check. 

Agree, we need to plumb this through.

We should also consider plumbing through static vs non-static and cgo enable/disable while we're at it.

The goal is to be a low-fidelity cross-build to catch most code errors that would break the full `make release` without actually having to run the computationally expensive cross build, but there's some mismatch ...
