### ISSUE TITLE
Cancel volume operations when pod is deleted

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#118058]
### What happened?

A pod was created with fsgroup and a very large CSI volume that ended up taking 40 hours to finish applying fsgroup. We realized the issue and tried to redeploy the pod with `fsGroupChangePolicy: OnRootMismatch`.  However, because the CSI volume is DeviceMountable, the volume operations are serialized per volume. So the new pod mount was waiting for the first pod mount to finish before proceeding. Our only option to speed this up was to restart kubelet so that the go routines would be cleared.

```
# First pod with recursive fsgroup policy
[I0515 08:03:03.088181 3067 reconciler.go:254] "operationExecutor.MountVolume started for volume \"pvc-01ce8478-4b29-45bf-a706-fdec57daab68\"
[I0515 08:03:03.697184 3067 operation_generator.go:658] "MountVolume.MountDevice succeeded for volume \"pvc-01ce8478-4b29-45bf-a706-fdec57daab68\" 
[W0515 08:03:33.707310 3067 volume_linux.go:49] Setting volume ownership for /var/lib/kubelet/pods/4e706e27-0a9b-4deb-b65f-3663d5f86919/volumes/kubernetes.io~csi/pvc-01ce8478-4b29-45bf-a706-fdec57daab68/mount and fsGroup set. If the volume has a lot of files then setting volume ownership could be slow, see https://github.com/kubernetes/kubernetes/issues/69699

# 1st pod was deleted and 2nd pod created in between these times

# Finally finished fsgroup for the first pod
[I0516 21:22:41.969724 3067 operation_generator.go:703] "MountVolume.SetUp succeeded for volume \"pvc-01ce8478-4b29-45bf-a706-fdec57daab68\" 

# Tear down 1st pod which has been long gone
[I0516 21:22:42.044686 3067 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"sandboxing\" 
[I0516 21:22:42.107209 3067 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "pvc-01ce8478-4b29-45bf-a706-fdec57daab68"

# 2nd pod can finally mount
[I0516 21:22:42.145442 3067 reconciler.go:254] "operationExecutor.MountVolume started for volume \"pvc-01ce8478-4b29-45bf-a706-fdec57daab68\" 
[I0516 21:22:42.152939 3067 operation_generator.go:703] "MountVolume.SetUp succeeded for volume \"pvc-01ce8478-4b29-45bf-a706-fdec57daab68\"
```

### What did you expect to happen?

I think there's a couple of things we can do to improve the experience:
- Create a pod event for fsgroup taking a long time. We only have a kubelet log message today
- Periodically update the event + log instead of once after 30 seconds
- Add the ability to cancel the MountVolume go routine when a Pod is removed 

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod with default `fsGroupChangePolicy` and volume with lots of files
2. Delete the pod and create a new pod with `fsGroupChangePolicy: OnRootMismatch` and scheduled on the same node as the first pod
3. The 2nd pod will not be able to mount until the first fsgroup processing is complete. 

### Kubernetes version

<details>

```console
$ kubectl version
1.24.10
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by devilcrises** [comment]
Hello @msau42 
can you check my logic 
func (kl *Kubelet) mountVolume(pod *v1.Pod, volume *v1.Volume, podVolume *kubecontainer.VolumeMount, mountPath string) error {
	klog.V(3).InfoS("Performing mountVolume", "pod", klog.KObj(pod), "volume", volume.Name, "mountPath", mountPath)
	const mountTimeout = 30 * time.Second
	// Create a context with a timeout for the mount operation
	ctx, cancel := context.WithTimeout(context.Background(), mountTimeout)
	defer cancel()

	// Mount the volume using the CSI driver
	err := kl.mountDevice(ctx, volume, pod, podVolume, mountPath)
	if err != nil {
		klog.ErrorS(err, "MountVolume.MountDevice failed", "pod", klog.KObj(pod), "volume", volume.Name)
		return err
	}

	// Add event and log for long-running fsgroup processing
	kl.recorder.Eventf(pod, v1.EventTypeWarning, "FsGroupProcessing", "Filesystem group processing is taking a long time")

	// Periodically update the event and log while fsgroup processing is in progress
	startTime := time.Now()
	ticker := time.NewTicker(10 * time.Second)
	defer ticker.Stop()
	for {
		select {
		case <-ctx.Done():
			klog.ErrorS(ctx.Err(), "MountVolume.MountDevice context done", "pod", klog.KObj(pod), "volume", volume.Name)
			return ctx.Err()
		case <-ticker.C:
			kl.recorder.Eventf(pod, v1.EventTypeWarning, "FsGroupProcessing", "Filesystem group processing is still in progress")
			if time.Since(startTime) > 30*time.Second {
				klog.V(4).InfoS("Filesystem group processing is still in progress", "pod", pod.Name)
				kl.recorder.Eventf(pod, v1.EventTypeWarning, "FsGroupProcessing", "Filesystem group processing is still in progress")
			}
		default:
			// Continue with the mount operation
		}

		// Check if the fsgroup processing is completed
		if kl.isFsGroupProcessingComplete(pod) {
			break
		}

		time.Sleep(100 * time.Millisecond) // Sleep before the next iteration
	}
	return nil
}

**Comment by msau42** [comment]
Hi @devilcrises thanks for your interest. I think the cancellation part is going to be non-trivial because it needs to work with the operationexecutor. Maybe to begin with, focusing on the event generation would be easier. Do you have an environment where you can test out your change?

**Comment by wackxu** [comment]
I want to help fix this
/assign
