### ISSUE TITLE
unrecognized feature-gate key: UserNamespacesStatelessPodsSupport

### ISSUE THREAD

**Issue by gr0l0rg** [kubernetes/kubernetes#118074]
### What happened?

I cannot use the user namespaces feature that is enabled by the feature gate `UserNamespacesStatelessPodsSupport` as mentioned in https://kubernetes.io/blog/2022/10/03/userns-alpha/

I tried kubeadm with the flag `--feature-gates=UserNamespacesStatelessPodsSupport=true` but I got the error
`unrecognized feature-gate key: UserNamespacesStatelessPodsSupport`

### What did you expect to happen?

`kubeadm init` proceeds successfully

### How can we reproduce it (as minimally and precisely as possible)?

`kubeadm init --feature-gates=UserNamespacesStatelessPodsSupport=true`

### Kubernetes version

1.27

### Cloud provider

Hetzner

### OS version

Ubuntu 22.04

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/kind support
/close

please see my response here
https://github.com/kubernetes/kubeadm/issues/2879#issuecomment-1551843243
