### ISSUE TITLE
lots of pending pods lead to memory surge of kube-scheduler

### ISSUE THREAD

**Issue by Chaunceyctx** [kubernetes/kubernetes#118059]
### What happened?

Hi. I am using k8s 1.21 for stress test. When node resource is not sufficient and some taints which pods cannot tolerate are added on the node, I create 20K pods by shell command. As you can see, 20K pods are in pending status. At the same time, memory usage of kube-scheduler increases gradually and reach a high level.
```
I0517 08:45:21.825644       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="kube-system/coredns-7b4cbd69c-vfgg5" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.825911       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-q6tmx" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826077       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-886dr" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826216       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-jkznv" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826348       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-q4dt7" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826460       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-gqx47" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826584       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-jxx8f" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826672       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-b7crx" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826772       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-l4hb9" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.826905       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-7dlms" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827073       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-f676w" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827191       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-nkfwt" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827290       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-4mwtx" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827393       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-hqj9q" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827486       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-58fb7" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827578       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-wvr2w" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827671       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-gfqnb" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827778       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-kmrkb" err="0/2 nodes are available: 2 Insufficient memory."
I0517 08:45:21.827878       8 factory.go:339] "Unable to schedule pod; no fit; waiting" pod="default/test-kube-scheduler-75c5dcb45-pzh49" err="0/2 nodes are available: 2 Insufficient memory."
```
```
CONTAINER ID        NAME                                                                                            CPU %               MEM USAGE / LIMIT    MEM %               NET I/O             BLOCK I/O           PIDS
81f0104257f0        k8s_kube-scheduler_kube-scheduler-172.x.0.x_kube-system_4xxxbxxx9xf7xxxxxxexxx7xfxxxxxxex9_0   0.20%               9.791GiB / 14.68GiB   66.70%              0B / 0B             31.4GB / 0B          15

```
After analysing goroutine profile and memory profile of kube-scheduler，I find so many goroutine are stuck in 
`recordToSink` function to get `e.mu` lock.
https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#LL175C8-L175C8

And this lock is hold by `finishSeries` function https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L147

```
goroutine.pprof
goroutine 177 [select]:
net/http.(*Client).Do(...)
        net/http/client.go:585
k8s.io/client-go/rest.(*Request).request(0xc03ca7c690, 0x555b6466b2e8, 0xc00012e018, 0xc03e34b770, 0x0, 0x0)
        k8s.io/client-go@0.21.11/rest/request.go:906 +0x54d
k8s.io/client-go/rest.(*Request).Do(0xc03ca7c690, 0x55500066b2e8, 0xc00012e018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        k8s.io/client-go@0.21.11/rest/request.go:980 +0xf1
k8s.io/client-go/kubernetes/typed/events/v1.(*events).Patch(0xc00000bc20, 0x555b0006b2e8, 0xc00000e018, 0xc02e610080, 0x36, 0x500000092b40, 0x26, 0xc03e0781e0, 0x47, 0x50, ...)
        k8s.io/client-go@0.21.11/kubernetes/typed/events/v1/event.go:179 +0x25f
k8s.io/client-go/tools/events.(*EventSinkImpl).Patch(0xc000000690, 0xc019a42280, 0xc03e0781e0, 0x47, 0x50, 0x0, 0x0, 0x0)
        k8s.io/client-go@0.21.11/tools/events/event_broadcaster.go:102 +0x189
k8s.io/client-go/tools/events.recordEvent(0x555b64666770, 0xc00000090, 0xc019a42280, 0xc10000881b0007e, 0x7b2d197a5579)
        k8s.io/client-go@0.21.11/tools/events/event_broadcaster.go:231 +0x872
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).finishSeries(0xc000479b90)
        k8s.io/client-go@0.21.11/tools/events/event_broadcaster.go:151 +0x1c5
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000314f10)
        k8s.io/apimachinery@0.21.11/pkg/util/wait/wait.go:155 +0x62
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000314f10, 0x550004624908, 0xc00059c000, 0x1, 0xc0004c64e0)
        k8s.io/apimachinery@0.21.11/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000314f10, 0x53d1ac1000, 0x0, 0x1, 0xc0004c64e0)
        k8s.io/apimachinery@0.21.11/pkg/util/wait/wait.go:133 +0x9a
k8s.io/apimachinery/pkg/util/wait.Until(0xc000314f10, 0x53d1ac1000, 0xc0004c64e0)
        k8s.io/apimachinery@0.21.11/pkg/util/wait/wait.go:90 +0x4f
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).StartRecordingToSink
        k8s.io/client-go@0.21.11/tools/events/event_broadcaster.go:329 +0xf5

...

goroutine 50638837 [semacquire, 6 minutes]:
sync.runtime_SemacquireMutex(0xc000479b9c, 0x0, 0x1)
        runtime/sema.go:71 +0x49
sync.(*Mutex).lockSlow(0xc000479b98)
        sync/mutex.go:138 +0x10f
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink.func1(0xc000000b90, 0xc00002a780, 0x000b6467cf78, 0x000b65520010)
        k8s.io/client-go@v0.21.11/tools/events/event_broadcaster.go:196 +0x299
created by k8s.io/client-go/tools/events.(*eventBroadcasterImpl).recordToSink
        k8s.io/client-go@v0.21.11/tools/events/event_broadcaster.go:171 +0x6a

```
So we need to take some optimized measures to handle this problem.

### What did you expect to happen?

memory usage of kube-scheduler increase a little and almost has no impact on stability of cluster 

### How can we reproduce it (as minimally and precisely as possible)?

1. node resource is not sufficient and some taints which pods cannot tolerate are added on the node
2. create so many pods.

### Kubernetes version

k8s 1.21.10

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Chaunceyctx** [comment]
@liggitt @Huang-Wei

**Comment by HirazawaUi** [comment]
Version 1.21.10 is too old and is no longer supported
Is it convenient for you to re-test with the latest version (or a version within the support period)?
Please refer to: https://kubernetes.io/releases/patch-releases/#support-period

**Comment by Chaunceyctx** [comment]
> Version 1.21.10 is too old and is no longer supported Is it convenient for you to re-test with the latest version (or a version within the support period)? Please refer to: https://kubernetes.io/releases/patch-releases/#support-period


All versions of k8s have this problem. Because when [eventBroadcaster.](https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L70) is hold by any function like 'refreshExistingEventSeries' or 'finishSeries' and event 
 patch /create request send from these two functions is subjected to the flowcontrol, lots of 'recordToSink' goroutine will be stuck because of  https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L175. Finally, memory usage of kube-scheduler increases gradually and reach a high level

**Comment by Chaunceyctx** [comment]
@Huang-Wei @liggitt PTAL.

**Comment by Huang-Wei** [comment]
> All versions of k8s have this problem. Because when [eventBroadcaster.](https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L70) is hold by any function like 'refreshExistingEventSeries' or 'finishSeries' and event patch /create request send from these two functions is subjected to the flowcontrol

Could you provide the qps settings of your setup, including both API Server and scheduler?

**Comment by Chaunceyctx** [comment]
> > All versions of k8s have this problem. Because when [eventBroadcaster.](https://github.com/kubernetes/kubernetes/blob/2d742bb8ab638f3ffde7fe7d34753ab5ff322798/staging/src/k8s.io/client-go/tools/events/event_broadcaster.go#L70) is hold by any function like 'refreshExistingEventSeries' or 'finishSeries' and event patch /create request send from these two functions is subjected to the flowcontrol
> 
> Could you provide the qps settings of your setup, including both API Server and scheduler?

kube-scheduler: --kube-api-qps=100
kube-apiserver: --max-mutating-requests-inflight=200 --max-requests-inflight=400

**Comment by Chaunceyctx** [comment]
@Huang-Wei 
maybe we need to make a trade-off between losing events and memory surge？
