### ISSUE TITLE
Split /healthz into /livez & /readyz for kube-scheduler

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#118011]
### What would you like to be added?

Quoted from @wojtek-t 's [comment](https://github.com/kubernetes/kubernetes/pull/115754#discussion_r1192068894)

Splitting healthz/ into livez/ and readyz/ 

### Why is this needed?

```
I agree that splitting into livez/ and readyz/ is what we need here:

* livez/ inherits the existing behavior of healthz/ [it just becomes true once the component starts]
* readyz/ is failing when the component isn't initialized (i.e. it's only true after informers are already synced)

Now what we get is:

* non-leader with delayed caching will always be non-ready
* non-leader without delayed caching will be ready as soon as its cache initializes
* leader currently initializing can be distinguished from non-leader using the leader-election metrics

```

**Comment by HirazawaUi** [comment]
I read all the content of the PR #115754 comment and am willing to work on this issue
Do we need to continue some discussion for this issue

**Comment by linxiulei** [comment]
Hi @HirazawaUi , thanks for offering your help. But I was working in progress before knowing you can work on this. However, please feel free to contribute the similar issue https://github.com/kubernetes/kubernetes/issues/118158
