### ISSUE TITLE
Health tests inside a container

### ISSUE THREAD

**Issue by zv86** [kubernetes/kubernetes#11809]
This is a feature request
Is there a chance to develop an ability to test issues related to the apps, services that run inside a container not only by process, but also test the container in a smart way, e.g. check if there are problems related to connectivity to a 3rd party that connected to the container.

**Comment by thockin** [comment]
There are several ways (probes) that you can signal liveness to the
system.  How you implement that is up to you.  For example we have
gcr.io/google_containers/exechealthz:1.0 which runs a command and exposes
the results on healthz.  You could use this technique to do your 3rd party
connectivity testing.

**Comment by mbforbes** [comment]
I think the guide you're looking for is
https://github.com/kubernetes/kubernetes/tree/master/docs/user-guide/liveness

@zv86 I'm going to close this issue assuming that solves your problem, but please feel free to re-open if you have further questions!
