### ISSUE TITLE
kube-proxy: remove log warning about not using config file

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#118090]
### What would you like to be added?

remove log warning about not using config file

### Why is this needed?

Currently, kube-proxy can be configured via both CLI flags and config file. and config file can override flags. In the future, all flags will be deprecated and use the config file instead. But now the config file is still at the alpha level, so we shouldn't be warning people to stop using flags if there is no config file present.

refer to https://github.com/kubernetes/kubernetes/pull/117800#discussion_r1196774106

**Comment by aojea** [comment]
> But now the config file is still at the alpha level, so we shouldn't be warning people to stop using flags.

just append this "... if there is no config file present"

**Comment by shaneutt** [comment]
Ah looks like @TommyStarK has already started, thank you!

/assign @TommyStarK
