### ISSUE TITLE
Helm upgrade fails after upgrade hpa api version to autoscaling/v2

### ISSUE THREAD

**Issue by varunvijayagopal** [kubernetes/kubernetes#118127]
### What happened?

We recently upgraded api version of hpa to autoscaling/v2 from autoscaling/v2beta2. After the helm upgrade fails when one of the metric target value comes as unknown ?

is invalid: spec.metrics[0].object.target.value: Invalid value: resource.Quantity{i:resource.int64Amount
{value:0, scale:0}
, d:resource.infDecAmount
{Dec:(*inf.Dec)(nil)}
, s:"0", Format:"DecimalSI"}: must be positive

We use istio_requests_total for scaling . However this metric comes into picture only when we try to hit endpoint of service .
/stats/proemetheus endpoint doesn't give this metric by default . 
Since we use this for hpa , it comes as UNKNOWN till that service is accessed .

Is there any validation added as part of autoscaling/v2 ?
Is there a way to make it as 0 or some default value instead of UNKNOWN ?
Also we use memory as another metric , however when hpa fails to find one metric both target values comes as unknown

### What did you expect to happen?

upgrade should success or an option to provide default 
hpa should scale based on metric avaialable

### How can we reproduce it (as minimally and precisely as possible)?

Create a hpa with a metric which doesn't exist 
Try to upgrade that service using helm 

### Kubernetes version

1.24.9

### Cloud provider

<details>
Azure
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
It seems to be related to https://github.com/kubernetes/kubernetes/issues/107038

**Comment by pbetkier** [comment]
This is likely #87733, if that's the case then it's not related to the metric being UNKNOWN. Note [the workaround](https://github.com/kubernetes/kubernetes/issues/87733#issuecomment-1365718846) described there and see if it helps.
