### ISSUE TITLE
Create a kubectl overview page for the user guide

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11814]
Something like:
https://docs.openshift.org/latest/cli_reference/basic_cli_operations.html

cc @jlowdermilk @deads2k @caesarxuchao

**Comment by bgrant0607** [comment]
cc @brendandburns @RichieEscarez

**Comment by hurf** [comment]
@hw-qiaolei - Can you please look at this issue since you're recently working on documentation?

**Comment by hw-qiaolei** [comment]
@hurf thanks for the reminder. I will take care of it.
