### ISSUE TITLE
APIServices can be deleted at the apiserver startup

### ISSUE THREAD

**Issue by mborsz** [kubernetes/kubernetes#118103]
### What happened?

Initially reported at 1.24.10, but it seems to be present in master as well:

We observe that a part of apiservices objects have been removed by "system:apiserver" right after the kubernetes upgrade.

It looks like there is race between "autoregister controller" [1] deleting apiservices and "crd-autoregister controller" populating a map of desired apiservices, i.e. in logs we see:
```
INFO 2023-05-16T14:21:35.070841Z Starting autoregister controller
INFO 2023-05-16T14:21:35.070858Z Waiting for caches to sync for autoregister controller
INFO 2023-05-16T14:21:35.071116Z Starting crd-autoregister controller
INFO 2023-05-16T14:21:35.071128Z Waiting for caches to sync for crd-autoregister
INFO 2023-05-16T14:21:35.270943Z Caches are synced for autoregister controller
INFO 2023-05-16T14:21:35.471323Z Caches are synced for crd-autoregister
```

The unwanted APIServices delete happened at 14:21:35.438 GMT so between crd-autoregister sync and autoregister controller.

It looks like we attempt to wait with "autoregister controller" for crd-autoregister to initialize here: https://github.com/kubernetes/kubernetes/blob/5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02/cmd/kube-apiserver/app/aggregator.go#L148-L154

but for some reason we don't enter the if branch.

@liggitt tried adding this diff at HEAD:
```
diff --git a/cmd/kube-apiserver/app/aggregator.go b/cmd/kube-apiserver/app/aggregator.go
index 397c151e66a..8b755ab3179 100644
--- a/cmd/kube-apiserver/app/aggregator.go
+++ b/cmd/kube-apiserver/app/aggregator.go
@@ -148,7 +148,11 @@ func createAggregatorServer(aggregatorConfig *aggregatorapiserver.Config, delega
 			// this prevents the autoregistration controller's initial sync from deleting APIServices for CRDs that still exist.
 			// we only need to do this if CRDs are enabled on this server.  We can't use discovery because we are the source for discovery.
 			if aggregatorConfig.GenericConfig.MergedResourceConfig.ResourceEnabled(apiextensionsv1.SchemeGroupVersion.WithResource("customresourcedefinitions")) {
+				klog.Infof("waiting for initial CRD sync...")
 				crdRegistrationController.WaitForInitialSync()
+				klog.Infof("initial CRD sync complete...")
+			} else {
+				klog.Infof("CRD API not enabled, starting APIService registration without waiting for initial CRD sync")
 			}
 			autoRegistrationController.Run(5, context.StopCh)
 		}()
```
and then started a default cluster with local-up-cluster gave:
```
I0518 08:31:16.826743   94479 aggregator.go:155] CRD API not enabled, starting APIService registration without waiting for initial CRD sync
```

which suggest we have a bug in master and the bug is around the "customresourcedefinitions if"

### What did you expect to happen?

APIServices are not deleted, there is no race between crd-autoregister and autoregister controllers

### How can we reproduce it (as minimally and precisely as possible)?

Restart apiserver with apiservices from crds?

Add a patch proposed by liggit@ and watch the initialization race.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
1.24.10 but also seems to be present in master
</details>

### Cloud provider

<details>
gce/local-up-cluster
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
There are 3 config sources, one for kube-apiserver, one for kube-aggregator, and one for apiextensions-apiserver:

```
git grep -A 10 'func DefaultAPIResourceConfigSource()'
pkg/controlplane/instance.go:func DefaultAPIResourceConfigSource() *serverstorage.ResourceConfig {
pkg/controlplane/instance.go-   ret := serverstorage.NewResourceConfig()
pkg/controlplane/instance.go-   // NOTE: GroupVersions listed here will be enabled by default. Don't put alpha versions in the list.
pkg/controlplane/instance.go-   ret.EnableVersions(
pkg/controlplane/instance.go-           admissionregistrationv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           apiv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           appsv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           authenticationv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           authorizationapiv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           autoscalingapiv1.SchemeGroupVersion,
pkg/controlplane/instance.go-           autoscalingapiv2.SchemeGroupVersion,
--
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:func DefaultAPIResourceConfigSource() *serverstorage.ResourceConfig {
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-  ret := serverstorage.NewResourceConfig()
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-  // NOTE: GroupVersions listed here will be enabled by default. Don't put alpha versions in the list.
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-  ret.EnableVersions(
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-          v1beta1.SchemeGroupVersion,
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-          v1.SchemeGroupVersion,
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-  )
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-  return ret
staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go-}
--
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go:func DefaultAPIResourceConfigSource() *serverstorage.ResourceConfig {
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-  ret := serverstorage.NewResourceConfig()
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-  // NOTE: GroupVersions listed here will be enabled by default. Don't put alpha versions in the list.
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-  ret.EnableVersions(
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-          v1.SchemeGroupVersion,
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-          v1beta1.SchemeGroupVersion,
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-  )
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-  return ret
staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go-}

```

The one kube-aggregator is checking is its own:

```
git grep -A 5 'APIEnablement.ApplyTo(' -- cmd/kube-apiserver
cmd/kube-apiserver/app/aggregator.go:   if err := commandOptions.APIEnablement.ApplyTo(
cmd/kube-apiserver/app/aggregator.go-           &genericConfig,
cmd/kube-apiserver/app/aggregator.go-           aggregatorapiserver.DefaultAPIResourceConfigSource(),
cmd/kube-apiserver/app/aggregator.go-           aggregatorscheme.Scheme); err != nil {
cmd/kube-apiserver/app/aggregator.go-           return nil, err
cmd/kube-apiserver/app/aggregator.go-   }
--
cmd/kube-apiserver/app/apiextensions.go:        if err := commandOptions.APIEnablement.ApplyTo(
cmd/kube-apiserver/app/apiextensions.go-                &genericConfig,
cmd/kube-apiserver/app/apiextensions.go-                apiextensionsapiserver.DefaultAPIResourceConfigSource(),
cmd/kube-apiserver/app/apiextensions.go-                apiextensionsapiserver.Scheme); err != nil {
cmd/kube-apiserver/app/apiextensions.go-                return nil, err
cmd/kube-apiserver/app/apiextensions.go-        }
--
cmd/kube-apiserver/app/server.go:       if lastErr = s.APIEnablement.ApplyTo(genericConfig, controlplane.DefaultAPIResourceConfigSource(), legacyscheme.Scheme); lastErr != nil {
cmd/kube-apiserver/app/server.go-               return
cmd/kube-apiserver/app/server.go-       }
cmd/kube-apiserver/app/server.go-       if lastErr = s.EgressSelector.ApplyTo(genericConfig); lastErr != nil {
cmd/kube-apiserver/app/server.go-               return
cmd/kube-apiserver/app/server.go-       }
```

so the kube-aggregator enablement config only knows about enabled apiregistration.k8s.io APIs by default, not about any others

**Comment by mborsz** [comment]
Personally I think this check may be problematic:
* https://github.com/kubernetes/kubernetes/blob/5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02/staging/src/k8s.io/apiserver/pkg/server/resourceconfig/helpers.go#L136-L139

Given that `registry` at that point is `aggregatorscheme.Scheme` [1] I suspect that `--runtime-config=api/all=false,apiextensions.k8s.io/v1=true` we use may be problematic as it will disable all apis, but allow apiextensions.k8s.io only if it's present in aggregatorscheme.Scheme which seems to contain only `apiregistration.k8s.io` resource types.

[1] https://github.com/kubernetes/kubernetes/blob/5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02/cmd/kube-apiserver/app/aggregator.go#L100-L106

**Comment by liggitt** [comment]
Further, the APIEnablement.ApplyTo method filters out groups/versions specified in runtime-config which are unknown to the provided scheme, so even if we collapsed the API-enablement sources to use a common one with types from all subsystems, calling APIEnablement.ApplyTo with three different schemes wouldn't apply the runtime-config flag options correctly.

I think the right solution is to check for enablement using the apiextension server's resource-enablement config. Opening a fix now

/assign

**Comment by liggitt** [comment]
fix open in https://github.com/kubernetes/kubernetes/pull/118104 for review... working on a test now then will open backports

**Comment by liggitt** [comment]
looks like this hasn't worked properly since 1.11 when that check got added :-/

https://github.com/kubernetes/kubernetes/commit/a68c57155e728b2782408cbab88ecee0444a4ba8#diff-1922a41e9579a1e7c3cc0015e6525b3d017eb6c576d02d9854b9d6dcc4fa580d

**Comment by ardaguclu** [comment]
What can be the most common consequence of this problem?.
