### ISSUE TITLE
github.com/golang/protobuf deprecated

### ISSUE THREAD

**Issue by ohDaddyPlease** [kubernetes/kubernetes#118135]
### What would you like to be added?

I suggest replacing gogo/protobuf and golang/protobuf with google/protobuf

### Why is this needed?

https://github.com/golang/protobuf/pull/1306 deprecates github.com/golang/protobuf in favour of google.golang.org/protobuf

**Comment by BenTheElder** [comment]
see also: https://github.com/kubernetes/kubernetes/issues/96564

**Comment by cici37** [comment]
/cc @liggitt 
Not quite sure if the replacement has been planned? :)
/triage accepted

**Comment by liggitt** [comment]
/close
in favor of https://github.com/kubernetes/kubernetes/issues/96564
