### ISSUE TITLE
use ipsets in iptables proxier

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#118110]
### What would you like to be added?

The IPVS proxy mode leverages IPSets to significantly decrease the number of iptable rules. Currently, IPTables proxier doesn't use IPSets and can benefit from them.

[there is a kep for nftables proxy mode](https://github.com/kubernetes/enhancements/pull/3824) which might replace iptables and ipvs proxier with nftables, [but that might take time](https://github.com/kubernetes/enhancements/pull/3824#discussion_r1096604360).

### Why is this needed?

Taking an example from the current IPTables proxier, the following rule will be written **n times** _(n being the number of cluster IPs)_. We can replace the n rules with a single one, IPSets with specialized data structures can efficiently match against the set which will significantly increase the packet throughput.

https://github.com/kubernetes/kubernetes/blob/bb67eb5bd237334d6d0343aa382b351002653404/pkg/proxy/iptables/proxier.go#L1076-L1083

[EDIT]
Performance won't increase significantly for clusters with few but long-lived connections as conntrack will kick in after the connection/flow is established bypassing all proxy rules.

[EDIT-2]
This has been raised before(but not discussed) https://github.com/kubernetes/kubernetes/pull/108460#discussion_r960895453

**Comment by daman1807** [comment]
I can benchmark the difference in throughput, by replacing one type of rule with an IPSet.

**Comment by devilcrises** [comment]
Hey @daman1807 
we can add this for #118110 below issuse which you mention 
if !longLivedConnections {
	proxier.natRules.Write(
		"-A", string(kubeServicesChain),
		"-m", "comment", "--comment", fmt.Sprintf(`"%s cluster IP"`, svcPortNameString),
		"-m", protocol, "-p", protocol,
		"-m", "set", "--match-set", "ipset_name", "dst", // Add this line to use IPSets
		"--dport", strconv.Itoa(svcInfo.Port()),
		"-j", string(internalTrafficChain))
} else {
	proxier.natRules.Write(
		"-A", string(kubeServicesChain),
		"-m", "comment", "--comment", fmt.Sprintf(`"%s cluster IP"`, svcPortNameString),
		"-m", "conntrack", "--ctstate", "RELATED,ESTABLISHED",
		"-j", string(internalTrafficChain))
}


In this basically  if !longLivedConnections to check if the cluster has few but long-lived connections. If it doesn't meet this condition, it will use the IPSets-based approach mentioned earlier. However, if the condition is met, it will bypass the proxy rules for established connections using the conntrack module.

**Comment by danwinship** [comment]
This would definitely help with some scaling problems in iptables.

But it would have to be rolled out slowly to ensure that we didn't have any regressions, which means that it wouldn't become GA until after the nftables proxy was at least alpha and maybe beta, at which point performance improvements to iptables are much less interesting.

So I'm not sure is something worth fixing at this point.

**Comment by aroradaman** [comment]
@shaneutt I would love to work on this if sig-network accepts this.

**Comment by shaneutt** [comment]
@aroradaman we discussed this one in the SIG Network meeting today: Your energy and efforts to help out lately have been very notable, thank you for jumping in! We really appreciate you helping to identify this area for improvement, but in discussion today we felt that there might not be enough of a return on time investment for this one to justify moving it forward. Hopefully that's understandable, but if you have questions or concerns about this please do let us know. The energy you have for diving in and helping to find areas of improvement is really cool, I'm gonna be on the lookout for things that you may find interesting and I can let you know, feel free to reach out to me on Slack any time as well!

**Comment by aroradaman** [comment]
@shaneutt happy to contribute!

closing this for now.
/close
