### ISSUE TITLE
conversion generator doesn't tolerate one-way custom conversions

### ISSUE THREAD

**Issue by bparees** [kubernetes/kubernetes#11817]
I recently had reason to create a one way conversion (support multiple formats for external api values, but always convert to a standard internal api value).

it turns out the conversion generator logic does not properly recognize a conversion if only a one way conversion exists, you need to define conversions in both directions or it does not get used properly, forcing you to define a dummy conversion in the other direction.

**Comment by thockin** [comment]
Can you provide a bit more detail?  The assumption is that all API versions
can round-trip to all other versions, though semantically equivalent values
might be canonicalized (though you'll have to fix the fuzz test).

**Comment by bparees** [comment]
The scenario in this case is that we had some constants defined that are part of the api (values for type fields on our objects).

Originally we spec'd that the values should be lowercase.  So that affectively became part of our api (lowercase constant values).

Later we decided to switch to CamelCase.  So our internal api now assumes the values are CamelCase.  To keep the api compatible, I introduced a conversion that will convert either format into CamelCase when going from the external api to the internal api.

There's no need to do a conversion in the other direction (internal api to external api), we're content to just present the CamelCase value externally.  Technically I suppose that is a non-compatible change if someone had written an external client that assumed lowercase values, but that wasn't a concern for us, and really there would be no way to demux the different formats without introducing more metadata in the internal api that tracked the original format.

So strictly speaking yes, what i've created does not roundtrip (external to internal) if you start with a lowercase value, you end up with a CamelCase value after the roundtrip.

So if we don't want to tolerate people creating conversions like that, I can see a justification to close this, but it was pretty surprising behavior that took a while to understand (why the conversion wasn't getting generated/called).

@deads2k fyi.

**Comment by mikedanese** [comment]
@bgrant0607

**Comment by thockin** [comment]
Yeah, in a stable API you should round-trip properly, which means assigning
two enumerators with the same meaning.  In a pre-stable API you might get
away with renaming the enumerator and normalizing the value, but at that
point you own the client.
