### ISSUE TITLE
Allow framework plugins to be closed

### ISSUE THREAD

**Issue by codefromthecrypt** [kubernetes/kubernetes#118147]
### What would you like to be added?

I would like `framework.Plugin` implementations, specifically scheduler plugins to be when the scheduler is being stopped. It could implement this by a type assertion on `io.Closer`, so that old schedulers don't have to implement it.

### Why is this needed?

For example, wasm plugins internally use mapped memory and it would be good to cleanly unmap them.

Without this we could use finalizers, but doing that has problems including [some overhead](https://lemire.me/blog/2023/05/19/the-absurd-cost-of-finalizers-in-go/).

**Comment by kerthcet** [comment]
@codefromthecrypt do you have any examples for this?

**Comment by codefromthecrypt** [comment]
@kerthcet yep. The wasm runtime wazero internally has a compilation code cache which includes mmapped modules. https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/6/files#diff-1bdb059cf97778a163c3746f2f5a0d27cf6f1d114652a534db91b810173624bcR132-R138
