### ISSUE TITLE
Improve exponential backoff in reflector

### ISSUE THREAD

**Issue by marseel** [kubernetes/kubernetes#118129]
Currently, reflector uses two backoff managers: 
https://github.com/kubernetes/client-go/blob/2a5f18df73b70cb85c26a3785b06162f3d513cf5/tools/cache/reflector.go#L223
One is used for initial list call and other for watch call. 

Imagine following scenaraion when k8s apiserver is under very heavy load:
1. At the beginning, reflector spams k8s apiserver (with exponential backoff) with `List` calls until one of them succeeds (due to APF throtling and receiving `429`)
2. Reflector tries to run `Watch` request and uses separate backoffManager - so again spams k8s apiserver with `Watch` requests
3. If Watch does not succeed during Etcd compaction window (2.5 - 5 minutes usually) at some point it will receive `resourceVersionTooOld` and go back to point 1, spamming k8s apiserver again with List calls (because first backoffManager for List got reseted after 2 minutes of retries for Watch requests)

I propose we combine these two backoff managers into one. 
If we combine these two backoffManagers into one, it will work like this:
- At the beginning, reflector spams k8s apiserver (still with exponential backoff) with `List` calls until one of them succeeds
- Tries to make first watch call instantly (as there is no backoff on this path)
- If it fails, it will makre retries every (30, 60)s
- If watch request fails all the times during Etcd compaction window it will go back to List call, but already being throttled with (30, 60)s window. 

/sig scalability

**Comment by mborsz** [comment]
I think the proposed solution makes sense to me. Probably before we start, we should to understand why we ended up with two back off managers by looking into PRs touching them. Maybe the code authors had some specific case in mind.

**Comment by wojtek-t** [comment]
@tkashem @MikeSpreitzer for thoughts too

I agree it makes sense, but I don't know the historical context here.
