### ISSUE TITLE
`kubectl create deployment` with a specific service-account (flag)

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#118142]
Relaying for a customer, but it seems reasonable to me.

Could we get a `--service-account` flag on `kubectl create deployment` ?  It's not terribly common to use multiple SAs, but I am seeing it more and more, and it makes me happy.

**Comment by mpuckett159** [comment]
/close

Please see the [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-cli/kubectl-conventions.md#create-commands) for a more detailed explanation. To summarize, create commands are meant to be very minimal commands that are only for trying out kubernetes. More complete/customized resource creations should be done using apply. Adding more flags than are minimally necessary for the resource is out of scope for this particular command.
