### ISSUE TITLE
Etcd cannot running by static pod after kubeadm renew certs all

### ISSUE THREAD

**Issue by prometheus-tao** [kubernetes/kubernetes#118216]
### What happened?

Kubernetes cluster present x509 errors about certs expired, Then restart the kube-apiserver, kube-controller-manager, kube-scheduler and etcd after execute "kubeadm alpha certs renew all " command successfully at one master node, Copy apiserver*, front* and etcd certs file to other two master node, Restart component the same , So that etcd and kube* container cannot running, See log file found many erros as follow.

CERTIFICATE                EXPIRES                  RESIDUAL TIME   CERTIFICATE AUTHORITY   EXTERNALLY MANAGED
admin.conf                 May 23, 2024 01:45 UTC   364d                                    no
apiserver                  May 23, 2024 01:45 UTC   364d            ca                      no
apiserver-etcd-client      May 23, 2024 01:45 UTC   364d            etcd-ca                 no
apiserver-kubelet-client   May 23, 2024 01:45 UTC   364d            ca                      no
controller-manager.conf    May 23, 2024 01:45 UTC   364d                                    no
etcd-healthcheck-client    May 23, 2024 01:45 UTC   364d            etcd-ca                 no
etcd-peer                  May 23, 2024 01:45 UTC   364d            etcd-ca                 no
etcd-server                May 23, 2024 01:45 UTC   364d            etcd-ca                 no
front-proxy-client         May 23, 2024 01:45 UTC   364d            front-proxy-ca          no
scheduler.conf             May 23, 2024 01:45 UTC   364d                                    no

CERTIFICATE AUTHORITY   EXPIRES                  RESIDUAL TIME   EXTERNALLY MANAGED
ca                      May 20, 2032 10:20 UTC   8y              no
etcd-ca                 May 20, 2032 10:20 UTC   8y              no
front-proxy-ca          May 20, 2032 10:20 UTC   8y              no

[master node]  192.16.0.1 etcd log
2023-05-24 02:17:33.760448 I | embed: rejected connection from "192.16.0.3:41464" (error "tls: \"192.16.0.3\" does not match any of DNSNames [\"host1\" \"localhost\"]", ServerName "", IPAddresses ["192.16.0.1" "127.0.0.1" "::1"], DNSNames ["host1" "localhost"])
2023-05-24 02:17:37.498451 I | embed: rejected connection from "192.16.0.2:36448" (error "tls: \"192.16.0.2\" does not match any of DNSNames [\"host1\" \"localhost\"]", ServerName "", IPAddresses ["192.16.0.1" "127.0.0.1" "::1"], DNSNames ["host1" "localhost"])
2023-05-24 02:17:36.357622 W | rafthttp: health check for peer c6198c3c2a184417 could not connect: x509: certificate is valid for 192.16.0.1, 127.0.0.1, ::1, not 192.16.0.3
2023-05-24 02:17:36.359115 W | rafthttp: health check for peer cde1c9316d25ba89 could not connect: x509: certificate is valid for 192.16.0.1, 127.0.0.1, ::1, not 192.16.0.2
2023-05-24 02:17:51.359023 W | rafthttp: health check for peer c6198c3c2a184417 could not connect: dial tcp 192.16.0.3:2380: connect: connection refused
2023-05-24 02:17:51.359663 W | rafthttp: health check for peer cde1c9316d25ba89 could not connect: dial tcp 192.16.0.2:2380: connect: connection refused

[etcd pod yaml]
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/etcd.advertise-client-urls: https://192.16.0.1:2379
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://192.16.0.1:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://192.16.0.1:2380
    - --initial-cluster=host1=https://192.16.0.1:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://192.16.0.1:2379
    - --listen-metrics-urls=http://127.0.0.1:2381
    - --listen-peer-urls=https://192.16.0.1:2380
    - --name=host1
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: etcd:3.4.3-0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /health
        port: 2381
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
	- mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}

### What did you expect to happen?

All component container can be normal running and cluster recovery

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm alpha certs renew all on master node

### Kubernetes version

<details>

```console
$ kubectl version
# v1.18.20
```

</details>
Kubernetes: v1.18.20
Etcd:  3.4.3

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
CentOS Linux 7 (Core)  5.4.210-1.el7.elrepo.x86_64

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>
Docker v1.20.17

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
1.18 has not been in support for a long time.

a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by prometheus-tao** [comment]
@neolit123 ok, thanks!
