### ISSUE TITLE
GPG Key error in Debian 11

### ISSUE THREAD

**Issue by arkabase** [kubernetes/kubernetes#118238]
### What happened?

After installing apt-key.gpg file and declared kubernetes repository in apt source file, then updating apt I get the following error :

The key(s) in the keyring /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg are ignored as the file has an unsupported filetype

and the package can't be installed because the repo is disabled by security.

### What did you expect to happen?

The kubernetes repository is updated in apt and the kubectl package can be installed.

### How can we reproduce it (as minimally and precisely as possible)?

In Debian 11 minimal distribution : 

```console
$ sudo apt update
$ sudo apt install ca-certificates curl apt-transport-https
$ sudo curl -fsSLo /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
$ echo "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
$ sudo apt update
```

### Kubernetes version

<details>

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux infra-test1 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@arkabase please see discussion(s) in https://github.com/kubernetes/release/issues/2862

/close
