### ISSUE TITLE
kubectl patch command issue when passing from command line

### ISSUE THREAD

**Issue by noorinshaikh** [kubernetes/kubernetes#118246]
### What happened?

I am trying to patch to a configmap but am facing issues with the same. I have tried recommendations from other posts but havent been able to fix the same. Find below what I have tried and the error I get:

1)
kubectl patch configmap dec --namespace=namespace1 --patch {"data": {"config": {"staticPasswords": {"email": "xyz@example.com","hash": "1234"}}}} 
zsh: parse error near `}'

2)
kubectl patch --type=json configmap dec --namespace=namespace1 --patch '{"data": {"config": {"staticPasswords": {"email": "xyz@example.com","hash": "1234"}}}}'
Error from server (BadRequest): json: cannot unmarshal object into Go value of type jsonpatch.Patch

3)
kubectl patch configmap dec --namespace=namespace1 --patch 'data:\n config:\n  staticPasswords:\n   - email: xyz@example.com\n    hash: 1234'
error: unable to parse "data:\\n configl:\\n  staticPasswords:\\n   - email: xyz@example.com\\n    hash: 1234": yaml: mapping values are not allowed in this context
 

### What did you expect to happen?

The configmap should have successfully patched and appended the json data

### How can we reproduce it (as minimally and precisely as possible)?

run the below commands on a unix system:
kubectl patch configmap dec --namespace=namespace1 --patch {"data": {"config": {"staticPasswords": {"email": "xyz@example.com","hash": "1234"}}}}

kubectl patch --type=json configmap dec --namespace=namespace1 --patch '{"data": {"config": {"staticPasswords": {"email": "xyz@example.com","hash": "1234"}}}}'

kubectl patch configmap dec --namespace=namespace1 --patch 'data:\n config:\n  staticPasswords:\n   - email: xyz@example.com\n    hash: 1234'

### Kubernetes version

<details>

```console
kubectl version  
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.16", GitCommit:"60e5135f758b6e43d0523b3277e8d34b4ab3801f", GitTreeState:"clean", BuildDate:"2023-01-18T16:01:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.17-eks-0a21954", GitCommit:"cd5c12c51b0899612375453f7a7c2e7b6563f5e9", GitTreeState:"clean", BuildDate:"2023-04-15T00:32:27Z", GoVersion:"go1.19.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console

$ uname -a
noorins@noorinsBMD6R symphony % uname -a
Darwin noorinsBMD6R.vmware.com 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64 x86_64

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by noorinshaikh** [comment]
sig/cli

**Comment by T-Lakshmi** [comment]
Hi @noorinshaikh,

See Blog post https://kubernetes.io/blog/2021/05/14/using-finalizers-to-control-deletion/#understanding-finalizers which is having example of patch configmap and check where you are doing wrong.

I hope that will be helpful to you.

**Comment by iyear** [comment]
ConfigMap data is a key-value struct, so you can't patch a nested JSON data. Also you should escape quotes in JSON value.

Try:
```shell
$ k patch cm dec --patch '{"data": {"config": "{\"staticPasswords\": {\"email\": \"xyz@example.com\",\"hash\": \"1234\"}}"}}'
configmap/dec patched
$ k get cm dec -o yaml
apiVersion: v1
data:
  config: '{"staticPasswords": {"email": "xyz@example.com","hash": "1234"}}'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-25T05:59:36Z"
  name: dec
  namespace: default
  resourceVersion: "1424"
  uid: 474eb9c7-f52b-4e59-a4b5-59dbafe8343a
```

/remove-kind bug
/kind support

**Comment by noorinshaikh** [comment]
@iyear Thanks for the response, 
However I need it to append something like this:

**Before patch:**
```
apiVersion: v1
data:
  config: |
    issuer: xxxxx
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:4444
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: user@example.com
      hash: 1234
      username: user1
      userID: "1"
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: IIIIIID
      redirectURIs: ["/login/xyz"]
      name: 'Dec Login App'
      secretEnv: CLIENT_SECRET
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: dec
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-11-29T03:11"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: dec
  namespace: auth
  resourceVersion: "98765"
  uid: a9665139-35a5-4567-91bg-1db9eb431def
```

**Patch data:**
```
data:
  config: |
    - email: user2@example.com
      hash: 12345
      username: user2
```
**After patch:**

```
apiVersion: v1
data:
  config: |
    issuer: xxxxx
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:4444
    logger:
      level: "debug"
      format: text
    oauth2:
      skipApprovalScreen: true
    enablePasswordDB: true
    staticPasswords:
    - email: user@example.com
      hash: 1234
      username: user1
      userID: "1"
    - email: user2@example.com
      hash: 12345
      username: user2
    staticClients:
    # https://github.com/dexidp/dex/pull/1664
    - idEnv: IIIIIID
      redirectURIs: ["/login/xyz"]
      name: 'Dec Login App'
      secretEnv: CLIENT_SECRET
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: dec
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-11-29T03:11"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: dec
  namespace: auth
  resourceVersion: "98765"
  uid: a9665139-35a5-4567-91bg-1db9eb431def

```
