### ISSUE TITLE
Kubernetes List Api ResourceVersion changes for consecutive same request

### ISSUE THREAD

**Issue by maheshwariST** [kubernetes/kubernetes#118239]
When I call a Kubernetes List Api (consecutively two times without any changes in the cluster) with `watch=null` for all namespaces for any resource with `resourceVersion = null`, I notice that the response for the first time has a list ResourceVersion (along with individual item ResourceVersion). The response for the second time has a **different** list ResourceVersion (along with individual item ResourceVersion, which are the **same** as the first version). 

For instance, the response of running `curl {base_url}/apis/apps/v1/deployments` command twice is different only in the list metadata ResourceVersion.
I expected the list ResourceVersion to be the same as the last time if the list ResourceVersion for any individual items is not changed.

Would you happen to know if this is expected? I wanted to store the cluster state in a DB and update the cluster only when the list ResourceVersion is different.
Because of the described behavior, I need to store the ResourceVersion for each item in the list and update the cluster when anything in this set has changed.

Do you know if the resourceVersion for the list is only helpful for watching events and cannot be used for my use case?

**Comment by MadhavJivrajani** [comment]
@maheshwariST - the `resourceVersion` of the `list` represents the storage version of the backing store `etcd`, and this is updated whenever the storage is updated in *any* way, meaning that it does not just have to be updates to items of the `list`. This is more or less an implementation detail. For your use case, have you considered the [`watch`](https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes) operation? This will give you a stream of notifications whenever a collection of items that is of interest to you, goes through a change (i.e you don't have to maintain the set anymore). The client-go library also provides wrapper functions and reaction function for when you receive `ADDED`, `MODIFIED`, `DELETE` events from the watch.

**Comment by dinhxuanvu** [comment]
I think Madhav has said it all. I personally don't think watching `resourceVersion` on a list object instead of individual object itself to determine of the individual object has changed is a good idea. You may as well set up an informer to watch that particular object type and take action according when new object is created or existing one is modified.

**Comment by maheshwariST** [comment]
@MadhavJivrajani, thanks for the info. I'm now using the watch operaiton. I will close the ticket.

**Comment by MadhavJivrajani** [comment]
👍
/kind support
