### ISSUE TITLE
Kubectl is hanging intermittently and recovering itself after few seconds

### ISSUE THREAD

**Issue by chittu11** [kubernetes/kubernetes#118291]
We are seeing our K8 clusters kubelet is hanging and its recovering itself after few seconds. and it's breaking running workflows.
seeing this after upgrading our clusters from 1.18 to latest version(v1.25.2).

Do we have any known bug in this version related to this NW related issues? I moved contol-plane VM to another ESX  host thought of ESX related issue but still its happening.

Not seeing any error recorded for it in etcd nor in API logs:

K8 Version:

v1.25.2

Thank you
CS

**Comment by DP19** [comment]
@chittu11 did you upgrade straight from 1.18 to 1.25?

**Comment by chittu11** [comment]
No @DP19 . we built new cluster and migrated worker loads from older cluster to new

**Comment by DP19** [comment]
@chittu11 the title says kubectl but your description says kubelet; which is it? Both?

**Comment by chittu11** [comment]
Kubectl is hanging? I cant query anything when it gets struck. but kubelet service is running interestingly

**Comment by DP19** [comment]
@chittu11 

It may be helpful to run kubectl with a very verbose logging level to see what it's doing (`-v=9`)

With some of the newer versions I have noticed it does take a while on the first run to fill it's discovery cache if you have a lot of api-resources in your cluster. This should only happen every 6 hours. 

You can also grab a blocking profile to see what it's waiting on by running a kubectl command and adding in `--profile=blocking --profile-output=profile.pprof`

Then you can analyze the output with `go tool pprof profile.pprof` then typing `web` to open up a browser with a flowchart of where it's spending it's time being blocked in goroutines

**Comment by ardaguclu** [comment]
This seems like a infra related issue and I'm not sure that it still happens. I'm closing this for now and if problem continues, feel free to re-open it;

/close
