### ISSUE TITLE
Cronjob status.lastSuccessfulTime not populated by a manually triggered job

### ISSUE THREAD

**Issue by ThomasRasmussen** [kubernetes/kubernetes#118276]
### What happened?

Given a cronjob created with a scedule of "0 6 * * *" that failed at last run (status.lastSuccessfulTime is now "before" status.lastScheduleTime). 

Then I trigger the cronjob by hand `kubectl create job --from=cronjob/my-cronjob my-cronjob-manual-1234`and this jobs ends successfully. However status.lastSuccessfulTime is not updated, thus making it difficult to monitor failed cronjobs. 

### What did you expect to happen?

status.lastSuccessfulTime should be updated with a timestamp of the succeeded job endTime

### How can we reproduce it (as minimally and precisely as possible)?

Install the attached files:
```
kubectl apply -f configmap-ok.yaml
kubectl apply -f cronjob_test.yaml
```
Wait until cronjob has actually trigged, test with
```
kubectl get cronjob -o jsonpath='{.items[*].status}' | jq
```
to see that lastScheduleTime and lastSuccessfulTime are populated ok (as expected).
Then apply the fail config-map, now the job will not complete OK:
```
kubectl apply -f configmap-fail.yaml
```
Again wait until cronjob has trigged automatically, observe 
```
kubectl get cronjob -o jsonpath='{.items[*].status}' | jq
```
to see that lastScheduleTime is updated but lastSuccessfulTime is not.

Then apply the "OK" configmap and then create the job by hand:
```
kubectl apply -f configmap-ok.yaml
kubectl create job --from=cronjob/test-cronjob test-cronjob-manual-$(date +%s)
```
when the job has finished and completed ok, observe that lastSuccessfulTime is still not updated.
```
kubectl get cronjob -o jsonpath='{.items[*].status}'
```
Wait until next schedule and observe that the field is now updated.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Tested on kind cluster on Mac
</details>

### OS version

<details>

```console
$ sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66

$ uname -a
Darwin tr.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

$ docker version
Client:
 Cloud integration: v1.0.31
 Version:           23.0.5
 API version:       1.42
 Go version:        go1.19.8
 Git commit:        bc4487a
 Built:             Wed Apr 26 16:12:52 2023
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.19.0 (106363)
 Engine:
  Version:          23.0.5
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.8
  Git commit:       94d3ad6
  Built:            Wed Apr 26 16:17:45 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

$ kind version
kind v0.17.0 go1.19.3 darwin/amd64
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

[configmap-ok.txt](https://github.com/kubernetes/kubernetes/files/11572585/configmap-ok.txt)
[configmap-fail.txt](https://github.com/kubernetes/kubernetes/files/11572591/configmap-fail.txt)
[cronjob_test.txt](https://github.com/kubernetes/kubernetes/files/11572599/cronjob_test.txt)

**Comment by ThomasRasmussen** [comment]
Had to upload the files as .txt files as github wouldn't accept .yaml or .yml files

**Comment by pacoxu** [comment]
When I tried without the `manually-` prefix in the job name, the status is updated. 
```
kubectl create job --from=cronjob/test-cronjob test-cronjob-$(date +%s)
```

/sig apps
/area job
not sure if this is a bug or an expected behavior.

**Comment by ThomasRasmussen** [comment]
@pacoxu  I have just tested in my kind cluster and neither with the same naming pattern as the normal jobs (which apparently isn't epoch) or with epoch -  this will not trigger a update of the field.

I have also tested it on another cluster (rke2 based) and here I'm not able to get the field updated no matter which naming pattern I use.


```
$ kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "25",
    "gitVersion": "v1.25.9",
    "gitCommit": "a1a87a0a2bcd605820920c6b0e618a8ab7d117d4",
    "gitTreeState": "clean",
    "buildDate": "2023-04-12T12:16:51Z",
    "goVersion": "go1.19.8",
    "compiler": "gc",
    "platform": "darwin/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "26",
    "gitVersion": "v1.26.3+rke2r1",
    "gitCommit": "9e644106593f3f4aa98f8a84b23db5fa378900bd",
    "gitTreeState": "clean",
    "buildDate": "2023-03-17T20:37:48Z",
    "goVersion": "go1.19.7 X:boringcrypto",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

**Comment by pacoxu** [comment]
Sorry for the mistake. I can repro the problem you have and not related to the prefix.
/cc @soltysh
