### ISSUE TITLE
[Failing test] pull-kubernetes-kind-dra multiple failures

### ISSUE THREAD

**Issue by mengjiao-liu** [kubernetes/kubernetes#118201]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kind-dra/1659956139929899008
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-kind-dra/1660562399301734400
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/118012/pull-kubernetes-kind-dra/1660846776401268736
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/118134/pull-kubernetes-kind-dra/1660710535479431168
...

### Which tests are failing?

pull-kubernetes-kind-dra

### Since when has it been failing?

5-21 00:17 CST

### Testgrid link

https://testgrid.k8s.io/sig-node-presubmits#pr-crio-dra

### Relevant SIG(s)

/sig testing
/sig node

**Comment by BenTheElder** [comment]
We're going to get DRA unforked on the containerd version shortly. KIND is unblocked to upgrade by default now.

https://github.com/kubernetes-sigs/kind/pull/3250 going in shortly then DRA follow-ups.

**Comment by BenTheElder** [comment]
/close
multiple green runs since merging the updates
