### ISSUE TITLE
[HELP] Where is the method NewServer in the kubelet/cri/streaming/server.go called?

### ISSUE THREAD

**Issue by Chamberlain1998** [kubernetes/kubernetes#118224]
### What happened?
I'm trying to view the code for **cri streaming servers**. But except its test file, I couldn't find where the streaming server was initialized by calling method ```NewServer(config Config, runtime Runtime) (Server, error)``` throughout the project . 

Can anyone be so nice to provide some information on this part? Please!

file link of kubelet/cri/streaming/server.go: 
https://github.com/kubernetes/kubernetes/blob/0bff705acd8982e34b937116eb2016c9d6e4c4a6/pkg/kubelet/cri/streaming/server.go#LL109C11-L109C11

### What did you expect to happen?
The method NewServer() should be called to initialize the streaming server and serve restful request

![image](https://github.com/kubernetes/kubernetes/assets/31801985/c044c638-91d5-4f1f-9ebc-cbcaf8290621)

![59726BED-8A33-4889-B1D5-E9D35E36EEF9](https://github.com/kubernetes/kubernetes/assets/31801985/9419bb60-9399-4a56-baee-989f1fb796ad)

**Comment by aojea** [comment]
IIRC this is now handled from the container runtimes only,  the ones that "stream" to the Pods, since the dockershim removal kubelet no longer does it

https://github.com/containerd/containerd/blob/5997a6589686479e0bf7074218bd7bddf09d2d8f/pkg/cri/streaming/server.go#L123
https://github.com/cri-o/cri-o/blob/9e06243da59dba150ed12620f680d1a3ea4008ec/server/streaming/streaming.go#L110

**Comment by pacoxu** [comment]
/sig node

> IIRC this is now handled from the container runtimes only, the ones that "stream" to the Pods, since the dockershim removal kubelet no longer does it

/kind cleanup

**Comment by saschagrunert** [comment]
It would be handy to have the implementation as part of the staging repos for re-using them in the runtimes. How about doing that in https://github.com/kubernetes/kubernetes/pull/118253?

**Comment by saschagrunert** [comment]
Let's close this issue for now with the merge of https://github.com/kubernetes/kubernetes/pull/118253. Feel free to reopen if I'm missing anything.
