### ISSUE TITLE
K8s Kubelet Checkpoint API

### ISSUE THREAD

**Issue by TahaW863** [kubernetes/kubernetes#118213]
### What happened?

According to the documentation, if you add the enable the feature in the config files of the following: 
```
------         5/22/2023  11:03 PM           3384 kube-controller-manager.yaml
------         5/22/2023  11:03 PM           1440 kube-scheduler.yaml
------         5/22/2023  11:03 PM           3825 kube-apiserver.yaml
```
The Kubelet API should provide a new path for checkpoint. I'm using the latest K8s and i checked the logs after changing the files. However, the endpoint still haven't registered and keeps saying 404. Moreover, I used _podman_ and the checkpointing works fine. I want to use Kubelet because its more convenient.
I spent two days trying to figure it out, but i'm out of juice now. Again i passed
```
- --feature-gates=ContainerCheckpoint=true
```

### What did you expect to happen?

To have Kubelet API checkpoint enabled

### How can we reproduce it (as minimally and precisely as possible)?

Docker Desktop, K8s enabled. Change the config files on this path
```
\\wsl.localhost\docker-desktop-data\mnt\wsl\docker-desktop-data\version-pack-data\community\kubeadm\manifests
```

### Kubernetes version

kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Localhost

### OS version

Windows

### Install tools

Docker, K8s

### Container runtime (CRI) and version (if applicable)

Docker latest

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

@TahaW863  can you please double check on versions:

- You said you are using latest k8s, but referring to 1.25. Is it 1.25?
- Container runtime - are you using Docker as cri-dockerd? Or it is not a docker? cri-dockerd doesn't support windows. But the path and kubectl in the issue refer to Windows
- Please also specify the version of runtime. Containerd does not support checkpointing thru CRI.

**Comment by TahaW863** [comment]
@SergeyKanzhelev 
The latest supported version of k8s on Docker which's 1.25.9
```
PS C:\Users\Taha.jo> kubectl get nodes
NAME             STATUS   ROLES           AGE   VERSION
docker-desktop   Ready    control-plane   39h   v1.25.9
```
--------------
Its Docker Desktop. So docker runtime. 
The paths are wsl paths to the location where Docker will place the k8s configurations. I changed them before to enable the feature and they were restarted by K8s. However, the Checkpoint endpoint wasn't registered when i opened the 
```
PS C:\Users\Taha.jo\Desktop> kubectl proxy
Starting to serve on 127.0.0.1:8001
```

**Comment by rst0git** [comment]
> Its Docker Desktop. So docker runtime.

CRI-O is the only runtime currently that supports the checkpoint API. The following blog post contains more information: https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/
