### ISSUE TITLE
When I used containerd as k8s, I had a problem adding containerd to an existing cluster. When I changed the storage path of Containerd to k8s, I failed to add the storage path of Containerd to k8s. K8s showed no docker driver.

### ISSUE THREAD

**Issue by YZPAWE** [kubernetes/kubernetes#118275]
### What happened?

When I used containerd as k8s, I had a problem adding containerd to an existing cluster. When I changed the storage path of Containerd to k8s, I failed to add the storage path of Containerd to k8s. K8s showed no docker driver.
![image](https://github.com/kubernetes/kubernetes/assets/98373143/2443c0b7-f750-4aa7-8635-fb0e74f121ef)
Here's the configuration file for containerd, and I changed a few things
![image](https://github.com/kubernetes/kubernetes/assets/98373143/4bf4ca28-bddf-4d2c-9ee3-65bee6457f8b)
这是crictl.yaml文件
![image](https://github.com/kubernetes/kubernetes/assets/98373143/e7c569bb-9cb0-4033-b75f-c55da1fa66a1)
Note: I am using kubeadm token create --print-join-command to generate a new tokenj to join the cluster

### What did you expect to happen?

You are added to the k8s cluster successfully. Procedure

### How can we reproduce it (as minimally and precisely as possible)?

Add the storage path of containerd to the cluster and try again

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
![image](https://github.com/kubernetes/kubernetes/assets/98373143/68a61958-ab64-4c6a-8916-a9cee3da6dff)

</details>

### Cloud provider

<details>
1
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
You are using kubeadm v1.21 and the default cri socket is docker at that time.
You can use `--cri-socket` to specify the cri socket for `kubeadm join`.
