### ISSUE TITLE
nodeIP parameter is not implemented 

### ISSUE THREAD

**Issue by lev-stas** [kubernetes/kubernetes#118265]
### What happened?

Hi! I have a cluster with nodes which have two network interfaces. eth0 with public IP address and eth1 with private one. After cluster initialization public IP addresses were assigned to all nodes as InternalIP. But I want to use local address as InternalIP for my cluster. 
I am trying to define nodeIP parameter in kubelet config.yaml file like this 
```
...
clusterDNS:
- 10.96.0.10
nodeIP: 10.114.0.3
clusterDomain: cluster.local
...
```
but after restart ok kubelet, node address hasn't been changed in `kubectl get nodes -o wide` output. I have also tried another spelling  **nodeIp**, as far as I haven't get in documentation how I can specify this parameter in yaml config file. After that I tried to add `--node-ip=10.114.0.2` option to kubelet.service file. And again, it doesn't work.  

### What did you expect to happen?

I expect that internal address of node will be assigned to local IP address on eht1 interface

### How can we reproduce it (as minimally and precisely as possible)?

add nodeIP parameter to kubelet config.yaml file like this

```
...
clusterDNS:
- 10.96.0.10
nodeIP: 10.114.0.3
clusterDomain: cluster.local
...
```

### Anything else we need to know?

The cluster deployed as self-managed cloud based. It means that I deploy it on ordinary droplets in Digital Ocean

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.26.2
Kustomize Version: v4.5.7
Server Version: v1.26.5
```

</details>

### Cloud provider

<details>
self managed cluster in Digital Ocean
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

$ uname -a
Linux do-k8s-01 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.7.1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
cni-plugins-linux-amd64-v1.3.0
</details>

**Comment by aojea** [comment]
If you are using a cloud-provider for the kubelet then that cloud-provider is the component that is writing the node addresses on the Node object

**Comment by lev-stas** [comment]
My cloud provider, actually, provides only my droplets, not any part of kubernetes cluster. I mange Kubernetes by myself. And kubelet service is running on my droplet. So, I can modify it as needed.

**Comment by dims** [comment]
Aren't you using the digital ocean cloud controller manager @lev-stas ? https://github.com/digitalocean/digitalocean-cloud-controller-manager/tree/master/docs/controllers/node/examples

**Comment by lev-stas** [comment]
No, I don't use it. Probably i should do. But I wonder is it possible to set necessary interface without any external cloud-provider tool. If I have baremetall server with two interfaces, I should be able to choose what I am going to use.

**Comment by BenTheElder** [comment]
> My cloud provider, actually, provides only my droplets, not any part of kubernetes cluster.

Two different "cloud provider"s 🙃 

@aojea means the Kubernetes concept of a component that integrates against the platform APIs (e.g. for IPAM)

As opposed to "digital ocean" the platform, "cloud-provider-digital-ocean" or similar (the controller that integrates kubernetes against DO, e.g. the one linked above by dims).

I think there are some older issues talking about the limited ability to set node IPs via flags versus some external process applying a PATCH to the node object.

**Comment by neolit123** [comment]
>  I have also tried another spelling nodeIp, as far as I haven't get in documentation how I can specify this parameter in yaml config file.

there is no nodeIP field in the kubelet config, it's only a CLI flag.
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

this comment explains what the reason is:
https://github.com/kubernetes/kubernetes/blob/86fec81606b579cc478a30656c29ddb400a72dc6/cmd/kubelet/app/options/options.go#L46

>  After that I tried to add --node-ip=10.114.0.2 option to kubelet.service file. And again, it doesn't work.
> but after restart ok kubelet, node address hasn't been changed in

passing the flag should work, but only on the initial node creation, IIRC.
after you have created the node object kubelet restarts with mutating CLI flags or config will arguably not change the node IP.

there are missing design docs here too.

related recent proposal:
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3983-drop-in-configuration

cc @yuqi-zhang @haircommander
this is a real world problem related to the kubelet node-local / instance specific config.

/sig node
/kind feature

**Comment by haircommander** [comment]
>  this is a real world problem related to the kubelet node-local / instance specific config.

in this case, KEP 3983 as it's currently scoped won't help. We don't plan on converting any flags to be config fields, only adding support for a drop-in config directory

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

two issues:
- support of the field in the config - can be taken separately as a feature
- Applying the new filed to the existing node object - I think it is not expected either and node object needs to be removed and re-created to pick up the new IP configuration.

**Comment by chenk008** [comment]
@SergeyKanzhelev  should we reopen this issue to support nodeIP in kubelet config?
