### ISSUE TITLE
[Flaky test] gce-master-scale-correctness

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#118295]
### Which jobs are failing?

master-informing
- gce-master-scale-correctness

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-network] Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow]

![Screenshot from 2023-06-14 13-16-46](https://github.com/kubernetes/kubernetes/assets/73488906/6c482069-9f10-4a24-bf7d-5afa11cd6459)

### Since when has it been failing?

2023-05-24 10:01 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness

### Reason for failure (if possible)

Kubernetes e2e suite: [It] [sig-network] Services GCE [Slow] should be able to create and tear down a standard-tier load balancer [Slow] 
```
{ failed [FAILED] timed out waiting for service "net-tiers-svc" to have a new ingress IP: timed out waiting for the condition In [It] at: test/e2e/network/network_tiers.go:150 @ 06/12/23 18:27:38.261 }
```

### Relevant SIG(s)

/sig scalability
cc @kubernetes/ci-signal

**Comment by aojea** [comment]
Ok, checking job https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1662141821972647936

Download controller-manager logs

```
 gsutil cp gs://k8s-infra-scalability-tests-logs/ci-kubernetes-e2e-gce-scale-correctness/1662141821972647936/gce-scale-cluster-master/kube-controller-manager.log .
```


There are these errors already reported in  https://github.com/kubernetes/test-infra/issues/29500 but that doesn't seem the problem

```
E0526 18:28:45.259885      11 cloud_cidr_allocator.go:178] "Error updating CIDR" err="failed to patch node CIDR: Node \"gce-scale-cluster-master\" is invalid: spec.podCIDRs: Invalid value: []string{\"10.64.0.0/24\", \"10.40.0.2/32\"}: may specify no more than one CIDR for each IP family" workItem="gce-scale-cluster-master"                                                                     I0526 18:28:45.259903      11 cloud_cidr_allocator.go:180] "Retrying update on next period" workItem="gce-scale-cluster-master" timeout="6.708110413s" 

```


This is weird
```
I0526 18:16:26.976746      11 gce_loadbalancer_external.go:1140] deleteWrongNetworkTieredResources:(a3dbab379faef4c15b7afbae888142a8(services-6614/net-tiers-svc)): Network tiers do not match; existing forwarding rule: "Standard", desired: "Premium". Deleting the forwarding rule 

```

@swetharepakula @panslava @cezarygerard does this ring a bell? ^^

**Comment by pacoxu** [comment]
It seems to be a flake which is passed in the last run.

**Comment by mehabhalodiya** [comment]
Yes, I see the last run Green; so closing this as of now!
Will re-open it if this will be a `1.28.0-alpha.1` release blocker.

**Comment by Vyom-Yadav** [comment]
This seems like a flaky test. It has failed multiple times:

- [2023-04-16 17:03:13 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1647646371211120640)
- [2023-05-24 17:01:05 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1661417038481985536)
- [2023-05-26 17:01:06 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1662141821972647936)
- [2023-06-06 17:01:48 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1666128263891652608)
- [2023-06-12 17:01:55 +0000 UTC](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1668302621766586368)

**Comment by aojea** [comment]
The load balancer tkes a lot of time to be provisioned and the test times out

I'm going to bump the ingress-gce version used on the test because is too old and has some performance improvements that can solve this issue

**Comment by Vyom-Yadav** [comment]
@aojea It failed again: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-correctness/1669752140588912640

**Comment by aojea** [comment]
So, the problem is that the time to acquire the IP takes too much, the test times out at `18:39:29`

```
Jun 16 18:39:29.838: INFO: Unexpected error: 
    <*fmt.wrapError | 0xc00d80c0e0>: 
    timed out waiting for service "net-tiers-svc" to have a new ingress IP: timed out waiting for the condition
```

and the IP is added at `18:45:31`

```
I0616 18:18:07.199974      11 gce_loadbalancer_external.go:1140] deleteWrongNetworkTieredResources:(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Network tiers do not match; existing forwarding rule: "Standard", desired: "Premium". Deleting the forwarding rule
I0616 18:29:18.674978      11 gce_loadbalancer_external.go:105] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Forwarding rule af1af05c3c58a42f693f62c86a65e3bc doesn't exist.
I0616 18:29:20.212066      11 gce_loadbalancer_external.go:168] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Ensured IP address 34.73.20.98 (tier: Premium).
I0616 18:29:20.411549      11 gce_loadbalancer_external.go:196] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Updating firewall.
I0616 18:29:24.565250      11 gce_loadbalancer_external.go:200] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Updated firewall.
I0616 18:29:25.020335      11 gce_loadbalancer_external.go:534] ensureTargetPoolAndHealthCheck(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Updated target pool (with 5001 hosts).
I0616 18:29:25.215514      11 gce_loadbalancer_external.go:275] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Creating forwarding rule, IP 34.73.20.98 (tier: Premium).
I0616 18:45:29.555212      11 gce_loadbalancer_external.go:284] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Created forwarding rule, IP 34.73.20.98.
I0616 18:45:31.095264      11 gce_loadbalancer_external.go:144] ensureExternalLoadBalancer(af1af05c3c58a42f693f62c86a65e3bc(services-9616/net-tiers-svc)): Released static IP 34.73.20.98.
I0616 18:45:31.095321      11 controller.go:947] Patching status for service services-9616/net-tiers-svc
I0616 18:45:31.095455      11 event.go:307] "Event occurred" object="services-9616/net-tiers-svc" fieldPath="" kind="Service" apiVersion="v1" type="Normal" reason="EnsuredLoadBalancer" message="Ensured load balancer"
I0616 18:46:37.858255      11 controller.go:921] Removing finalizer from service services-9616/net-tiers-svc
I0616 18:46:37.863405      11 controller.go:947] Patching status for service services-9616/net-tiers-svc
```

@swetharepakula @wojtek-t @cezarygerard @panslava IIUIC this depends on the underlay infra, what do we want to do with this, bump the timeout of the LB?

https://github.com/kubernetes/kubernetes/blob/1ff1a26426fedbb929bc966cebb9f90995e52725/test/e2e/framework/service/const.go#L57

**Comment by Vyom-Yadav** [comment]
Update on the state of failures. The failures are becoming more frequent:



![Image](https://github.com/kubernetes/kubernetes/assets/73882557/a69e1ab9-7595-4010-b65f-57ad239ec4ab)

**Comment by swetharepakula** [comment]
Unfortunately I think bumping the timeout is our only option.

**Comment by aojea** [comment]
> Unfortunately I think bumping the timeout is our only option.

@swetharepakula can you send a PR to move to 1 hours and add a comment referencing this issue?

**Comment by swetharepakula** [comment]
Just created https://github.com/kubernetes/kubernetes/pull/118889

**Comment by pacoxu** [comment]
CI is green since 06-27.
/close
