### ISSUE TITLE
cpu_manager_state is not updated when pod is deleted

### ISSUE THREAD

**Issue by dykhliww** [kubernetes/kubernetes#118375]
### What happened?

Set the cpu management static policy on the node and create a pod. When Pods are scheduled to the node, the cpu_manager_state file records the cpuset used by the container in the pod, but when the pod is removed, The cpu_manager_state file will still have cpuset information for pod that has been deleted. Why hasn't cpu_manager_state been updated?

### What did you expect to happen?

When the pod is deleted, cpu_manager_state file is updated.

### How can we reproduce it (as minimally and precisely as possible)?

Set the cpu manager static policy on the node and create a guaranteed pod, let's the pod is schedulerd the node by nodeSelector. Check the entries of the cpu_manager_state file. If there is a cpuset of the pod, delete the pod and check whether the entries of the deleted pod in the cpu_manager_state file are also deleted.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
kubernetes is v1.25.7.

### Cloud provider

<details>

</details>
one phycical node

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
check the CPU management policy
[cpu-manager-policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#changing-the-cpu-manager-policy)

**Comment by ffromani** [comment]
hi! the state file is not updated when pods are deleted, but 1. at pod admission time 2. periodically, by the cpumanager reconciliation loop. CPUs assigned to deleted pods are reclaimed when admission for new pods is attempted.

In general is discouraged to read data from the cpumanager state file. It's private data from the kubelet, not a public API. If you need introspection capabilities, please consider the [podresources API](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources).

**Comment by SergeyKanzhelev** [comment]
/close

as per @ffromani 's explanaition

**Comment by ZhangShuaiyi** [comment]
@SergeyKanzhelev  @ffromani 
I think this is a duplicate of this: https://github.com/kubernetes/kubernetes/issues/107074
When a Pod is deleted, we do not clean up `manager.pendingAdmissionPod`.  Cpumanager's reconciliation loop may not work when `manager.pendingAdmissionPod` is a dedicated pod. Until a new pod is created to update `manager.pendingAdmissionPod`.
