### ISSUE TITLE
[Failing Test] capz-windows-master

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#118300]
### Which jobs are failing?

master-informing
- capz-windows-master

### Which tests are failing?

- Kubernetes e2e suite.[It] [sig-apps] CronJob should delete successful finished jobs with limit of one successful job
- Kubernetes e2e suite.[It] [sig-apps] CronJob should remove from active list jobs that have been deleted
- Kubernetes e2e suite.[It] [sig-apps] Job should delete a job [Conformance]
- Kubernetes e2e suite.[It] [sig-apps] ReplicationController should test the lifecycle of a ReplicationController [Conformance]
- Kubernetes e2e suite.[It] [sig-cli] Kubectl client Update Demo should create and stop a replication controller [Conformance]
- Kubernetes e2e suite.[It] [sig-cli] Kubectl client Update Demo should scale a replication controller [Conformance]
- Kubernetes e2e suite.[It] [sig-network] EndpointSlice should create and delete Endpoints and EndpointSlices for a Service with a selector specified [Conformance]
- Kubernetes e2e suite.[It] [sig-network] Proxy version v1 should proxy through a service and a pod [Conformance]
- Kubernetes e2e suite.[It] [sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance]
- Kubernetes e2e suite.[It] [sig-network] Services should be able to change the type from NodePort to ExternalName [Conformance]
- capz-e2e.[It] Conformance Tests conformance-tests
- ci-kubernetes-e2e-capz-master-windows.Overall

![Screenshot from 2023-05-28 12-18-46](https://github.com/kubernetes/kubernetes/assets/73488906/2a129f3d-8572-488a-8275-8148956b8697)

### Since when has it been failing?

2023-05-27 14:00 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master

### Reason for failure (if possible)

- capz-e2e: [It] Conformance Tests conformance-tests
```
{Unexpected error:
    <*errors.withStack | 0xc0029974a0>: 
    Unable to run conformance tests: error container run failed with exit code 1
    {
        error: <*errors.withMessage | 0xc002b8a820>{
            cause: <*errors.errorString | 0xc0034de9e0>{
                s: "error container run failed with exit code 1",
            },
            msg: "Unable to run conformance tests",
        },
        stack: [0x36d7c1c, 0x39a9be7, 0x1a2a53b, 0x1a3ecf8, 0x15a0841],
    }
occurred failed [FAILED] Unexpected error:
    <*errors.withStack | 0xc0029974a0>: 
    Unable to run conformance tests: error container run failed with exit code 1
    {
        error: <*errors.withMessage | 0xc002b8a820>{
            cause: <*errors.errorString | 0xc0034de9e0>{
                s: "error container run failed with exit code 1",
            },
            msg: "Unable to run conformance tests",
        },
        stack: [0x36d7c1c, 0x39a9be7, 0x1a2a53b, 0x1a3ecf8, 0x15a0841],
    }
occurred
In [It] at: /home/prow/go/src/sigs.k8s.io/cluster-api-provider-azure/test/e2e/conformance_test.go:211 @ 05/28/23 04:14:16.089
}
```

- Kubernetes e2e suite: [It] [sig-cli] Kubectl client Update Demo should scale a replication controller [Conformance] 
```
{ failed [FAILED] Pods left unterminated after stop:
update-demo-nautilus-czj4v
update-demo-nautilus-d9jnn
In [It] at: test/e2e/kubectl/kubectl.go:228 @ 05/28/23 03:25:56.327
}
```

- Kubernetes e2e suite: [It] [sig-network] Services should be able to change the type from ClusterIP to ExternalName [Conformance] 
```
{ failed [FAILED] DeferCleanup callback returned error: error while waiting for pods to become inactive externalsvc: there are 2 active pods. E.g. "externalsvc-8g2bp" on node "capz-conf-pv9n9"
In [DeferCleanup (Each)] at: test/e2e/network/service.go:1510 @ 05/28/23 04:14:14.051
}
```

- Kubernetes e2e suite: [It] [sig-apps] CronJob should remove from active list jobs that have been deleted 
```
{ failed [FAILED] error while waiting for pods gone forbid-28087419: there are 1 pods left. E.g. "forbid-28087419-6gqj4" on node "capz-conf-pv9n9"
In [It] at: test/e2e/apps/cronjob.go:260 @ 05/28/23 04:04:06.761
}
```

- Kubernetes e2e suite: [It] [sig-apps] CronJob should delete successful finished jobs with limit of one successful job 
```
{ failed [FAILED] Failed to ensure that pods for job does not exists anymore in namespace cronjob-1808: timed out waiting for the condition
In [It] at: test/e2e/apps/cronjob.go:519 @ 05/28/23 04:01:10.105
}
```

- Kubernetes e2e suite: [It] [sig-network] EndpointSlice should create and delete Endpoints and EndpointSlices for a Service with a selector specified [Conformance] 
```
{ failed [FAILED] EndpointSlice resource not deleted after Service endpointslice-3354/example-empty-selector was deleted: timed out waiting for the condition
In [It] at: test/e2e/network/endpointslice.go:195 @ 05/28/23 03:50:18.864
}
```

### Relevant SIG(s)

/sig windows
/sig apps
/sig cli
/sig network
cc @kubernetes/ci-signal

**Comment by aojea** [comment]
all the errors mention problems with the pod status, this seems an environment specific problems, or either windows or capz

**Comment by mehabhalodiya** [comment]
@marosset @jayunit100 @claudiubelu @jsturtevant can you please confirm if this is a blocker or not for (30th May) today's `1.28.0-alpha.1` release ASAP? Thank you!

**Comment by jayunit100** [comment]
The errors seem related to "how fast the pods are being created/ deleted" .... 

looking at things like https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1662927289349836800/artifacts/clusters/capz-conf-cqth0o/machines/capz-conf-cqth0o-md-win-6547bc8449xclg86-s42cl/kubelet.log 
```
E0528 22:14:53.479923    4012 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" 
for \"app\" with CrashLoopBackOff: 

\"back-off 5m0s restarting failed container=app pod=img-pull-registry.k8s.io-e2e-test-images-busybox-1.29-4-77lqb_img-puller-9879(e4a76d26-0c38-4443-a0e5-44a61e68750b)\"" pod="img-puller-9879/img-pull-registry.k8s.io-e2e-test-images-busybox-1.29-4-77lqb" podUID="e4a76d26-0c38-4443-a0e5-44a61e68750b"
```

and this, where, somehow the pod wasn't deleted fast enough... 

```
I0527 21:40:45.694041    4056 kubelet.go:2425] "SyncLoop DELETE" source="api" pods=["deployment-9995/webserver-deployment-7b75d79cf5-djvd5"]
I0527 21:40:45.699554    4056 kubelet.go:2419] "SyncLoop REMOVE" source="api" pods=["deployment-9995/webserver-deployment-7b75d79cf5-djvd5"]
I0527 21:40:45.735046    4056 kubelet.go:2425] "SyncLoop DELETE" source="api" pods=["services-8990/externalsvc-jtjl2"]
I0527 21:40:45.735046    4056 kuberuntime_container.go:742] "Killing container with a grace period" pod="services-8990/externalsvc-jtjl2" podUID="7e79218d-0d0c-40c5-bb21-209d9e0c51eb" containerName="externalsvc" containerID="containerd://d622712139f52c31b5e6b67a0379974f74951a8b8f3e8252df0e4877f89caced" gracePeriod=1
I0527 21:40:45.739054    4056 kubelet.go:2416] "SyncLoop UPDATE" source="api" pods=["init-container-541/pod-init-6e9d4a34-c6b0-423c-afe0-880434804036"]
E0527 21:40:45.747545    4056 event.go:280] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"externalsvc-jtjl2.17631dfa23204dc8", GenerateName:"", Namespace:"services-8990", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"services-8990", Name:"externalsvc-jtjl2", UID:"7e79218d-0d0c-40c5-bb21-209d9e0c51eb", APIVersion:"v1", ResourceVersion:"5955", FieldPath:"spec.containers{externalsvc}"}, Reason:"Killing", Message:"Stopping container externalsvc", Source:v1.EventSource{Component:"kubelet", Host:"capz-conf-jttlm"}, FirstTimestamp:time.Date(2023, time.May, 27, 21, 40, 45, 735046600, time.Local), LastTimestamp:time.Date(2023, time.May, 27, 21, 40, 45, 735046600, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"kubelet", ReportingInstance:"capz-conf-jttlm"}': 'events "externalsvc-jtjl2.17631dfa23204dc8" is forbidden: unable to create new content in namespace services-8990 because it is being terminated' (will not retry!)
```

**Comment by jayunit100** [comment]
Aggregated some data on this.  Dont see anything other then slow pod deletions as the problem.  I doubt this is related to code changes in 1.27 to 1.28, so im going to say unblock the release and ill follow on w/ sig windows on this today!
```
| Test Case                                   | Result | Pod Duration | Deletion Evidence                                    | Failure Description                                                                                           |
|--------------------------------------------|--------|--------------|------------------------------------------------------|---------------------------------------------------------------------------------------------------------------|
| Kubectl client update Demo - RC             | Failed | 1:30 minutes | Pod update-demo-nautilus-ggblv was not terminated    | Pods left unterminated after stop: update-demo-nautilus-ggblv, update-demo-nautilus-pm7s5 (failed to terminate) |
| Service should be able to change the type   | Failed | 22 minutes   | Pod service-test-9cd7cb9f5-bp9kq was not deleted    | Failed to delete the pod (service-test-9cd7cb9f5-bp9kq) associated with the service when changing its type   |
| CronJob - Delete successful finished jobs   | Failed | 0 minutes    | -                                                    | Failed to ensure that pods for the job do not exist anymore in the namespace (timed out waiting for the condition) |
```

**Comment by aravindhp** [comment]
There are also DNS resolutiom failures in the [kubelet.log](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows/1662927289349836800/artifacts/clusters/capz-conf-cqth0o/machines/capz-conf-cqth0o-md-win-6547bc8449xclg86-s42cl/kubelet.log) but they could be intermittent:
```
<snip>
csi/azuredisk-csi:v1.27.1": failed to resolve reference "mcr.microsoft.com/oss/kubernetes-csi/azuredisk-csi:v1.27.1": failed to do request: Head "https://mcr.microsoft.com/v2/oss/kubernetes-csi/azuredisk-csi/manifests/v1.27.1": dial tcp: lookup mcr.microsoft.com: no such host
<snip>
E0528 21:24:40.533166    4452 reflector.go:149] object-"calico-system"/"calico-static-rules": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get "https://capz-conf-cqth0o-365a3225.northeurope.cloudapp.azure.com:6443/api/v1/namespaces/calico-system/configmaps?fieldSelector=metadata.name%3Dcalico-static-rules&resourceVersion=1704": dial tcp: lookup capz-conf-cqth0o-365a3225.northeurope.cloudapp.azure.com: no such host
<snip>
```

**Comment by jayunit100** [comment]
I interleaved the logs just to see the timestamps of all failures aggregated and ... there's continously crash looping occurring on the image puller busy box pod 

https://gist.github.com/jayunit100/03d0680aa8641508f1fda27629418046

Feels like that is pervasive through the test and maybe part of the root issue

**Comment by jsturtevant** [comment]
We've identified that this was due to calico version being upgraded on the Linux control plane nodes (https://kubernetes.slack.com/archives/CEX9HENG7/p1685555851875059), This should be resolved via https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3369 and https://github.com/Azure/azure-capi-cli-extension/pull/196 which pin the version to a known working version.

**Comment by jsturtevant** [comment]
we are green on capz-windows-master

![image](https://github.com/kubernetes/kubernetes/assets/648372/7b3f0900-f780-4354-93b9-196efda35ce9)

/close
