### ISSUE TITLE
transport: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [kubernetes/kubernetes#118332]
### What happened?

Fixed inconsistency and also potential data race in transport/http2_client.go: 
t.prevGoAwayID is read/written many times in transport/http2_client.go; 3 of 4 times it is protected by t.mu.Lock(); 1 out of 4 times it is read without a Lock, which is in func handleGoAway() on L1216.
A data race may happen when the func handleGoAway() and other func are called in parallel. 

### What did you expect to happen?

Adding a lock (t.mu.RLock()) to protect the access t.prevGoAwayID.

### How can we reproduce it (as minimally and precisely as possible)?

Code analysis.

### Anything else we need to know?

nil

### Kubernetes version

<details>

```console
V1.26.0
```
</details>

### Cloud provider

<details>
nil
</details>

### OS version

<details>

```console
Ubuntu 20.04
```

</details>

### Install tools

<details>
nil
</details>

### Container runtime (CRI) and version (if applicable)

<details>
nil
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
nil
</details>

**Comment by pacoxu** [comment]
This should be fixed in grpc-go and you should open an issue or pr to
https://github.com/grpc/grpc-go.

/close
after fixed in golang, we can just update the go.mod to include the fix.
