### ISSUE TITLE
[Failing Test] gce-master-scale-performance

### ISSUE THREAD

**Issue by mehabhalodiya** [kubernetes/kubernetes#118305]
### Which jobs are failing?

master-informing
- gce-master-scale-performance

### Which tests are failing?

- ci-kubernetes-e2e-gce-scale-performance.Overall [Changes](https://github.com/kubernetes/kubernetes/compare/ffc034640...d05b79c83?)
- ci-kubernetes-e2e-gce-scale-performance.Pod [Changes](https://github.com/kubernetes/kubernetes/compare/ffc034640...d05b79c83?)

![Screenshot from 2023-05-29 07-53-35](https://github.com/kubernetes/kubernetes/assets/73488906/91128b99-5095-411a-9ad0-746bc37a1940)

### Since when has it been failing?

2023-05-27 10:03 PDT

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

Not described on the Prow dashboard

### Relevant SIG(s)

/sig scalability
cc @kubernetes/ci-signal

**Comment by MadhavJivrajani** [comment]
The lack of build logs leads to me to believe this was a transient failure (maybe an infra issue?), we should wait for the next run which should happen in ~9.5 hours from now (17:01 UTC) to get a better signal.

**Comment by wojtek-t** [comment]
Yeah - it doesn't even seem like a test failure, rather some infra issue.

The next run is running now:
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gce-scale-performance/1663229036043702272

It seems ok for now, so hopefully it will pass and if so that would clearly be a "go" signal.

**Comment by mehabhalodiya** [comment]
Thanks all for your heads up; I see the latest run is Green.
