### ISSUE TITLE
Issue for Aggregated Discovery for Beta (v1.27) 

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118361]
In Kubernetes 1.26, Kubernetes Enhancement Proposal, KEP-3352[1]: Aggregated Discovery, enhanced the discovery mechanism and supported aggregated discovery optimizing response for discovery api. 

To support this KEP, Changes were made to both API server and client to support aggregated discovery mechanism. This feature was available alpha in Kubernetes 1.26 behind a feature flag, `AggregatedDiscoveryEndpoint`. 

In Kubernetes 1.27, aggregated discovery endpoint was promoted to beta and enabled by default[2]. Here is a class of problems that ended up getting triggered.

GOOD NEWS!! is that it is already fixed by https://github.com/kubernetes/kubernetes/pull/116603 in 1.27 and a cherry pick https://github.com/kubernetes/kubernetes/pull/116666 in 1.26

For example, With Prometheus adapter, we saw issues across repositories:

- https://github.com/helm/helm/issues/12061#issuecomment-1537935360
- https://github.com/vmware-tanzu/sonobuoy/issues/1910#issue-1690940687
- https://github.com/rook/rook/issues/12114#issuecomment-1518609858

One signature of this is following in the traceback:

```
k8s.io/client-go/discovery.convertAPIResource(...)
  /go/pkg/mod/k8s.io/client-go@v0.26.2/discovery/aggregated_discovery.go:88
```

**Comment by dims** [comment]
Searching for that method signature:
https://github.com/search?type=issues&q=%22discovery.convertAPIResource%22+%22aggregated_discovery.go%3A88%22&s=updated&o=desc&p=2

Currently shows the following:
- https://github.com/aws/amazon-vpc-resource-controller-k8s/issues/238
- https://github.com/hashicorp/terraform-provider-helm/issues/1140
- https://github.com/resmoio/kubernetes-event-exporter/issues/91
- https://github.com/elastic/cloud-on-k8s/issues/6848
- https://github.com/rabbitmq/cluster-operator/issues/1351
- https://github.com/metallb/metallb/issues/1893
- https://github.com/cert-manager/cert-manager/issues/6033
- https://github.com/cilium/cilium/issues/25280
- https://github.com/kubernetes/kubernetes/issues/117466
- https://github.com/siderolabs/talos/issues/7110

**Comment by dims** [comment]
Components that do generate custom metrics (grepping through sources!):

- [prometheus-adapter](https://github.com/search?type=code&q=repo%3Akubernetes-sigs%2Fprometheus-adapter+custom.metrics.k8s.io)
- [knative-serving](https://github.com/search?type=code&q=%22custom.metrics.k8s.io%22+org%3Aknative)
- [keptn](https://github.com/search?q=repo%3Akeptn%2Flifecycle-toolkit-charts%20v1beta2.custom.metrics.k8s.io&type=code)
- [k8s-stackdriver](https://github.com/search?q=repo%3AGoogleCloudPlatform%2Fk8s-stackdriver+v1beta2.custom.metrics.k8s.io&type=code)

etc..

**Comment by orsenthil** [comment]
Thanks, @dims. Any custom server, sending nil GVK could trigger this bug. 

So far have seen it through custom metrics via promethus-adapter.

**Comment by Jefftree** [comment]
Thanks for tracking this @dims!

/cc
/triage accepted

**Comment by jdn5126** [comment]
For those searching in the future, the impacted `client-go` versions are:
0.26.0 - 0.26.3 and 0.27.0 - 0.27.1

The fixed versions are:
0.26.4+ and 0.27.2+

As well as updating `client-go`, make sure that your other dependencies do not pull in any of the affected versions.

**Comment by dims** [comment]
/close

i think that's about it for now..
