### ISSUE TITLE
kubectl apply command application YAML information is inconsistent with the actual use of K8S

### ISSUE THREAD

**Issue by lipeng8** [kubernetes/kubernetes#118367]
### What happened?

kubectl apply command application YAML information is inconsistent with the actual use of K8S

### What did you expect to happen?

The application information used by k8s should be consistent with the yaml definition information declared by the kubectl apply command

### How can we reproduce it (as minimally and precisely as possible)?

Environmental information：
yaml information:
I deployed an nginx with a deployment controller(You can see that kind of regular deployment YAML everywhere)
Next
I added a new environment variable uu to the container of the deployment controller via the kubectl edit deploy command
![image](https://github.com/kubernetes/kubernetes/assets/38911604/9154a91a-6d43-4fab-a30b-2c927a5c6b71)
I updated the yaml k8s console again via the kubectl apply command, saying that deployment has been updated, but the environment variable has not been removed

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
![image](https://github.com/kubernetes/kubernetes/assets/38911604/d7538612-d5f8-4bb5-a423-83c3c83db948)

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lipeng8** [comment]
Environmental information：
![image](https://github.com/kubernetes/kubernetes/assets/38911604/f4aafbaa-8a49-4c3a-a101-0fe0e9c51ffc)

**Comment by lipeng8** [comment]
My original yaml file did not have a uu environment variable defined, in theory, when I updated with the kubectl apply command, k8s should remove this environment variable, but it didn't

**Comment by lipeng8** [comment]
My original yaml file did not have a uu environment variable defined, in theory, when I updated with the kubectl apply command, k8s should remove this environment variable, but it didn't

**Comment by lipeng8** [comment]
My original yaml file did not have a uu environment variable defined, in theory, when I updated with the kubectl apply command, k8s should remove this environment variable, but it didn't

**Comment by tamilselvan1102** [comment]
Kubernetes is designed in such a way that any changes to the pod should be redeployed through the config. If you go messing with pods that have already been deployed you can end up with weird clusters that are hard to debug.

If you really want to you can run additional commands in your running pod using kubectl exec, but this is only recommended for debug purposes.

> kubectl exec -it <pod_name> export VARIABLENAME=< thing>

**Comment by lipeng8** [comment]
I understand that this is not contrary to the design of the k8s

**Comment by lipeng8** [comment]
I really did this by adding some environment variables to the controller container through a specific tag through a webhook, which is an environment variable that is not defined by yaml, and there is a webhook program to add it

**Comment by lipeng8** [comment]
I just reproduced the problem by kubectl edit

**Comment by lipeng8** [comment]
In response to this, I have a question, why I use a complete yaml of an application to deploy k8s using kubectl apply, and the full update is not performed according to the yaml configuration

**Comment by lipeng8** [comment]
And I have some definitions of volumemounts, and k8s will remove it on update if it's not in the yaml used by kubectl apply, so I think it's a bug

**Comment by tamilselvan1102** [comment]
Environment for Linux process is established on **process startup,** and there are certainly no kube tools that can achieve such goal. 
Usually you have to restart a process for it to notice the changed environment variables and the easiest way to do that is restart the pod.

**Comment by mochizuki875** [comment]
Hi @lipeng8
I think it's due to difference between managers of `kubectl edit` and `kubectl apply` in `managedFields` and it's intentional.

After create `Deployment` by `kubectl apply` and add a new environment variable by `kubectl edit`, please check the `managedFields` of `Deployment`.
There should be three items including `manager`:
- `kube-controller-manager`
- `kubectl-edit`
- `kubectl-client-side-apply`

Each item presents which field is managed by which manager.
Then, check the item of `manager: kubectl-edit` and `f:env:` field will be found.

```yaml
$ kubectl get deploy nginx-deployment -oyaml --show-managed-fields

  managedFields:
  ...
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:template:
          f:spec:
            f:containers:
              k:{"name":"nginx"}:
                f:env:
                  .: {}
                  k:{"name":"uu"}:
                    .: {}
                    f:name: {}
                    f:value: {}
    manager: kubectl-edit
    operation: Update
```

This means the `.spec.template.spec.containers[?(@.name=="nginx")].env` field is managed by `kubectl-edit`.
So, even if we delete this field by `kubectl apply`, it will remain.

rf: [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/)
