### ISSUE TITLE
proto: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by yanke-xu** [kubernetes/kubernetes#118336]
### What happened?

It seems the same root reason with the issue#116497. There are two conflicting operations, and a data race may happen when the two functions which the two operations are located are called in parallel.

### What did you expect to happen?

Adding the related lock to protect the access to "fields".

### How can we reproduce it (as minimally and precisely as possible)?

Code analysis.

### Anything else we need to know?

nil

### Kubernetes version

<details>

```console
V1.26.0
```

</details>

### Cloud provider

<details>
nil
</details>

### OS version

<details>
nil
</details>

### Install tools

<details>
nil
</details>

### Container runtime (CRI) and version (if applicable)

<details>
nil
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
nil
</details>

**Comment by pacoxu** [comment]
Similar to #116497. please fix in https://github.com/gogo/protobuf/ and then propose an update to the copy we have in vendor/ directory

The problem should be fixed in gogo/protobuf and update the dependency in this repo to include the fix.

/close
