### ISSUE TITLE
Authenticated field in api/authentication/v1beta1TokenReviewStatus object is omitempty when it is needed to be false

### ISSUE THREAD

**Issue by sw9719** [kubernetes/kubernetes#118313]
### What happened?

Since the field is bool and its tag has 'omitempty', it is impossible to set it to false and perform JSON marshalling. For example, when sending [response](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication) to KubeAPI server from a webhook-token service, if the user is not authorized, 'Authenticated' should be false, but the tag prevents serialization of the field into JSON string.

### What did you expect to happen?

Either 'omitempty' be removed or set Authenticated as *bool instead of bool

### How can we reproduce it (as minimally and precisely as possible)?

Status := v1beta1.TokenReviewStatus{Authenticated: false, User: v1beta1.UserInfo{Username: "test"}}
StrStatus = json.Marshal(Status)
fmt.Println(StrStatus)                    // Authenticated field is omitted due to omitempty

### Anything else we need to know?

k8s.io/api/authentication.k8s.io/v1 also has the same issue

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

M/A

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
When absent, the field is treated as false
