### ISSUE TITLE
Pod readiness probe does not start when setting periodSeconds: 3600

### ISSUE THREAD

**Issue by plutarcian** [kubernetes/kubernetes#118396]
### What happened?

When configuring the readiness probe for the container in the pod and setting the periodSeconds: 3600 the probe does not seem to run. 

          readinessProbe:
            exec:
              command:
                - bash
                - /opt/readyprobe.sh
            initialDelaySeconds: 90
            periodSeconds: 3600
            timeoutSeconds: 600
            failureThreshold: 2

It can take up to 40 minutes for the pod to report as ready.

Note: this pod is part of a stateful set.
Note: sometimes the system does behave as expected . however everytime a new node is provisioned, the issue starts happening again

### What did you expect to happen?

readyiness probe should start after 90 seconds evertime pod is scheduled

### How can we reproduce it (as minimally and precisely as possible)?

setup a stateful set with at least one pod and container running and readiness probe set as follows
          readinessProbe:
            exec:
              command:
                - bash
                - /opt/readyprobe.sh
            initialDelaySeconds: 90
            periodSeconds: 3600
            timeoutSeconds: 600
            failureThreshold: 2

### Anything else we need to know?

This is in aws eks. The node get allocated via aws autoscaler. setting up the pod triggers a scale up to provision a new node

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:16:51Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.9-eks-0a21954", GitCommit:"eb82cd845d007ae98d215744675dcf7ff024a5a3", GitTreeState:"clean", BuildDate:"2023-04-15T00:37:59Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
AWS EKS VERSION 1.25
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
does not run every 3600 seconds?

**Comment by levikobi** [comment]
What you're saying makes sense. I've looked at the code and apparently the workers which are responsible for probing are entring into sleep for a random time up to the specified periodSeconds, if the time elapsed since kubelet restarted is less than the periodSeconds. This matches exactly with what you said about the provisioning of new nodes.

I geuss this mechanism was implemented as some sort of a jitter, in an attempt to avoid all probes starting at the same time.

We can maybe think of a more suitable implementation of a jitter, to avoid edge cases such as this.
I would love to work on it if the maintainers are cool with it.

**Comment by plutarcian** [comment]
Thanks for getting back @levikobi and coming up with a solution  . Good to know that I was not going crazy :)

In the meantime, should I see if I can make do with a shorter periodSeconds? Our readiness probe runs some checks on the network so I'm not too keen to have it run too often. I have configured a liveliness probe to handle any stability issues.

**Comment by sathyanarays** [comment]
Does this issue happen because it takes more than `initialDelayInSeconds` (which is 90 in the above examples) to provision the node? @plutarcian , is it possible to test out by setting an `initialDelayInSeconds` to a `1.5 * average node provisioning time in seconds` and test?

**Comment by plutarcian** [comment]
@sathyanarays as levikobi already identified above, the bug only happens on a new node ( or maybe a node were kublet has restarted ). It waits a random number upto the periodSeconds defined if the node uptime is less than the periodSeconds defined.
That is , in my example, if the node is less than 1 hour old, it will wait upto an hour before kicking off the first ready probe.
If we restart the pod AFTER the node has been up for an hour ( in this example ), everything works fine. If we restart before that 1 hour.( e.g. pod randomly comes online after 40 min and we restart it), the bug reappears.

I dont think the time taken for the node to come up plays a role here as restarting after 40 min also produces the same issue

**Comment by levikobi** [comment]
I noticed there is actually more to it than that. Even if we start a workload on existing node, and periodSeconds > initialDelaySeconds, the first request will be sent after periodSeconds elapsed, and not after initialDelaySeconds.

**Comment by plutarcian** [comment]
I don't think that's the case.
I have deployed the same configuration on n already warmed up node.
Readiness probe fires as configured ( 90 secs ) and not as per
periodSeconds ( 3600 secs ). Only new nodes have this issue

**Comment by sathyanarays** [comment]
Did you try giving a larger `initialDelaySeconds` (say 5 minutes) and see if the issue still happens?

**Comment by plutarcian** [comment]
No i havent had the chance to try it. Will post here when I do
Thanks

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

Would be great if you can summarize the issue - yaml and outcome. I think this is because of a jitter logic and this definitely can be improved.
