### ISSUE TITLE
error on execution phase wait-control-plane: couldn't initialize a Kubernetes cluster on Ubuntu 22.04.02 LTS

### ISSUE THREAD

**Issue by bennyzx** [kubernetes/kubernetes#118372]
### What happened?

root@control:/home/bennyzhou# journalctl -xeu kubelet
Jun 01 07:37:02 control kubelet[8234]: I0601 07:37:02.821839    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:02 control kubelet[8234]: E0601 07:37:02.822745    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:07 control kubelet[8234]: W0601 07:37:07.040337    8234 reflector.go:533] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Node: Get "https://10.211.55.50:6443/api/v1/nodes>
Jun 01 07:37:07 control kubelet[8234]: E0601 07:37:07.040607    8234 reflector.go:148] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Node: failed to list *v1.Node: Get "https://10.2>
Jun 01 07:37:07 control kubelet[8234]: E0601 07:37:07.758329    8234 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.176>
Jun 01 07:37:07 control kubelet[8234]: E0601 07:37:07.871793    8234 eviction_manager.go:262] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"control\" not found"
Jun 01 07:37:09 control kubelet[8234]: E0601 07:37:09.482528    8234 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://10.211.55.50:6443/apis/coordination.k8s.io/v1/namespac>
Jun 01 07:37:09 control kubelet[8234]: I0601 07:37:09.828375    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:09 control kubelet[8234]: E0601 07:37:09.829305    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:13 control kubelet[8234]: E0601 07:37:13.809011    8234 certificate_manager.go:562] kubernetes.io/kube-apiserver-client-kubelet: Failed while requesting a signed certificate from the control p>
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.484641    8234 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://10.211.55.50:6443/apis/coordination.k8s.io/v1/namespac>
Jun 01 07:37:16 control kubelet[8234]: I0601 07:37:16.833495    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.834553    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.862914    8234 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox >
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.863110    8234 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox image>
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.863171    8234 kuberuntime_manager.go:1122] "CreatePodSandbox for pod failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox imag>
Jun 01 07:37:16 control kubelet[8234]: E0601 07:37:16.863484    8234 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"etcd-control_kube-system(a5e71f6b699a8ec45d>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.686950    8234 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox >
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.687181    8234 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox image>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.687236    8234 kuberuntime_manager.go:1122] "CreatePodSandbox for pod failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox imag>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.687394    8234 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-scheduler-control_kube-system(098911cf>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.759230    8234 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.176>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.759365    8234 event.go:228] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.1764>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.759588    8234 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.176>
Jun 01 07:37:17 control kubelet[8234]: E0601 07:37:17.873381    8234 eviction_manager.go:262] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"control\" not found"
Jun 01 07:37:20 control kubelet[8234]: E0601 07:37:20.030755    8234 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox >
Jun 01 07:37:20 control kubelet[8234]: E0601 07:37:20.030944    8234 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox image>
Jun 01 07:37:20 control kubelet[8234]: E0601 07:37:20.030998    8234 kuberuntime_manager.go:1122] "CreatePodSandbox for pod failed" err="rpc error: code = DeadlineExceeded desc = failed to get sandbox imag>
Jun 01 07:37:20 control kubelet[8234]: E0601 07:37:20.031172    8234 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-controller-manager-control_kube-system>
Jun 01 07:37:21 control kubelet[8234]: E0601 07:37:21.698451    8234 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"r>
Jun 01 07:37:21 control kubelet[8234]: E0601 07:37:21.698724    8234 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to get sandbox image \"regist>
Jun 01 07:37:21 control kubelet[8234]: E0601 07:37:21.698854    8234 kuberuntime_manager.go:1122] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to get sandbox image \"regis>
Jun 01 07:37:21 control kubelet[8234]: E0601 07:37:21.699219    8234 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"kube-apiserver-control_kube-system(b0cd3209>
Jun 01 07:37:23 control kubelet[8234]: E0601 07:37:23.487556    8234 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://10.211.55.50:6443/apis/coordination.k8s.io/v1/namespac>
Jun 01 07:37:23 control kubelet[8234]: E0601 07:37:23.670772    8234 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.176>
Jun 01 07:37:23 control kubelet[8234]: I0601 07:37:23.838852    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:23 control kubelet[8234]: E0601 07:37:23.840241    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:27 control kubelet[8234]: E0601 07:37:27.876695    8234 eviction_manager.go:262] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"control\" not found"
Jun 01 07:37:30 control kubelet[8234]: E0601 07:37:30.492859    8234 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://10.211.55.50:6443/apis/coordination.k8s.io/v1/namespac>
Jun 01 07:37:30 control kubelet[8234]: I0601 07:37:30.846654    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:30 control kubelet[8234]: E0601 07:37:30.848518    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:31 control kubelet[8234]: W0601 07:37:31.563846    8234 reflector.go:533] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.RuntimeClass: Get "https://10.211.55.50:6443/apis>
Jun 01 07:37:31 control kubelet[8234]: E0601 07:37:31.564908    8234 reflector.go:148] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: G>
Jun 01 07:37:33 control kubelet[8234]: E0601 07:37:33.672581    8234 event.go:289] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"control.176>
Jun 01 07:37:35 control kubelet[8234]: W0601 07:37:35.649160    8234 reflector.go:533] vendor/k8s.io/client-go/informers/factory.go:150: failed to list *v1.Service: Get "https://10.211.55.50:6443/api/v1/se>
Jun 01 07:37:35 control kubelet[8234]: E0601 07:37:35.649398    8234 reflector.go:148] vendor/k8s.io/client-go/informers/factory.go:150: Failed to watch *v1.Service: failed to list *v1.Service: Get "https:>
Jun 01 07:37:37 control kubelet[8234]: E0601 07:37:37.497988    8234 controller.go:146] "Failed to ensure lease exists, will retry" err="Get \"https://10.211.55.50:6443/apis/coordination.k8s.io/v1/namespac>
Jun 01 07:37:37 control kubelet[8234]: I0601 07:37:37.857378    8234 kubelet_node_status.go:70] "Attempting to register node" node="control"
Jun 01 07:37:37 control kubelet[8234]: E0601 07:37:37.858791    8234 kubelet_node_status.go:92] "Unable to register node with API server" err="Post \"https://10.211.55.50:6443/api/v1/nodes\": dial tcp 10.2>
Jun 01 07:37:37 control kubelet[8234]: E0601 07:37:37.878730    8234 eviction_manager.go:262] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"control\" not found"
lines 982-1031/1031 (END)

### What did you expect to happen?

<img width="1476" alt="Kubernetes Contro" src="https://github.com/kubernetes/kubernetes/assets/5841845/48210ece-56d3-45a1-8df5-33084235da1a">

### How can we reproduce it (as minimally and precisely as possible)?

kubeadm init \
--image-repository=registry.aliyuncs.com/google_containers \
--apiserver-advertise-address=10.211.55.50 \
--service-cidr=10.96.0.0/16 \
--pod-network-cidr=10.222.0.0/16 \
--control-plane-endpoint=10.211.55.50:6443 \
--ignore-preflight-errors=all --v=6

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
clientVersion:
  buildDate: "2023-05-17T14:20:07Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/arm64
kustomizeVersion: v5.0.1
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

<details>

```
On-premise 
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
root@control:/home/bennyzhou# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
# paste output here
Linux control 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:50 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

```console
# Containerd 1.7.1
Client:
  Version:  v1.7.1
  Revision: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
  Go version: go1.20.4

Server:
  Version:  v1.7.1
  Revision: 1677a17964311325ed1c31e2c0a3589ce6d5c30d
  UUID: 2ae40b7b-3777-4d55-ac25-882f9146ed42
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
