### ISSUE TITLE
Restart kubelets in a gke test

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#11834]
Forked off from disucssion on https://github.com/GoogleCloudPlatform/kubernetes/pull/11339. That restart test needs to ssh into the master to restart all the master components, but we need something similar that restarts just the kubelet on the nodes on gke (since master ssh isn't allowed on gke). 

@mbforbes

**Comment by mbforbes** [comment]
Thank you for opening!

Yes, this would be great to minimize creeping GCE/GKE divergence.

To be clear, we're talking about `test/e2e/daemon_restart.go`.
