### ISSUE TITLE
A potential data race in packages.go

### ISSUE THREAD

**Issue by lobottt** [kubernetes/kubernetes#118337]
### What happened?

I discovered a potential data race in the program based on code analysis. Specifically, there is a write operation on the field "pathList", where the write operation at：packages/packages.go:782. In addition, the statement is executed many times in the goroutine where the static creation site is: typecheck/main.go:288. It is the same with field "EmbedFiles" and "EmbedPatterns". 

### What did you expect to happen?

data race 

### How can we reproduce it (as minimally and precisely as possible)?

nil

### Anything else we need to know?

nil

### Kubernetes version

<details>
v1.26.0
</details>

### Cloud provider

<details>
nil
</details>

### OS version

<details>
nil
</details>

### Install tools

<details>
nil
</details>

### Container runtime (CRI) and version (if applicable)

<details>
nil
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
nil
</details>

**Comment by pacoxu** [comment]
This should be fixed in golang and you should open an issue or pr to
https://github.com/golang/tools or https://pkg.go.dev/golang.org/x/tools.

/close
after fixing in golang, we can just update the dependency in `go.mod` and vendor to include the fix.
