### ISSUE TITLE
Support building darwin/arm64 binaries for kubernetes control-plane components

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#118359]
### What would you like to be added?

I understand there is no darwin kubelet (yet). However, it'd be super helpful if we can support building darwin/arm64 binaries for for control-plane components: apiserver, controller-manager and scheduler.

### Why is this needed?

An immediate beneficiary will be project [kwok](https://kwok.sigs.k8s.io/), which enables you to spin up a bare bone control plane in seconds. In its binary mode, it downloads binaries from dl.k8s.io, but no luck with darwin/arm64 :(

Ref issue: https://github.com/kubernetes-sigs/kwok/issues/591

**Comment by Huang-Wei** [comment]
/sig release

cc @xmudrii, feel free to re-sig if needed.

**Comment by BenTheElder** [comment]
Hmmm ... we don't support these for windows either and won't be testing it.

kwok can custom build, but I'm not sure we should be shipping these for releases.

We haven't permitting other new platforms without a KEP and support for testing etc (we have no macOS CI and currently only ship the client binary)

**Comment by dims** [comment]
@Huang-Wei that's the right thing to do! thanks.

**Comment by saschagrunert** [comment]
Adding new binaries also increases the resource usage on our side (build time, storage, traffic), so we have to be careful about the reasons. Thank you for the request @Huang-Wei, feel free to close this one if there is nothing else we can do for you here.
