### ISSUE TITLE
[FG:InPlacePodVerticalScaling]  K8s fails to throttle pod so that it follows resized CPU limit

### ISSUE THREAD

**Issue by netcamo** [kubernetes/kubernetes#118371]
### What happened?

I have a pod which initially has 0.5 CPU limit. I then resize it to follow 1.5 CPU limit and pod starts to use more resources until 1.5CPU. Problem arises when I resize pod CPU limit back to 0.5CPU.  Instead of throttling the pod, kubernetes doesn't do anything and pod continues to use up to 1.5CPU resource.

I have followed instructions [here](https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) to resize limits of pods. I am monitoring it using metrics server and I can see that new limits are applied but when you increase limit and then decrease it, kubernetes  fails to throttle pod so that it follows new decreased limit.
 

### What did you expect to happen?

I expected kubernetes to throttle the pod so that it doesn't use more than 0.5CPU but all I observe is that it is using more CPU Resource than limit. 

### How can we reproduce it (as minimally and precisely as possible)?

you can use any pod stressing the CPU (for example  image:polinux/stress) and try to increase CPU resource limit and then decrease it.

test.yml:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: stress-test
spec:
  containers:
  - name: pod-demo
    image: polinux/stress
    resources:
      limits:
        memory: "600Mi"
        cpu: 0.2
      requests:
        memory: "600Mi"
        cpu: 0.1 
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "256M", "-c", "2", "--vm-hang", "1"]
```
Create a namespace `stress-test` :
``` kubectl create namespace stress-test```

Apply the yaml file:
```kubectl apply -f test.yml```

Resize to increase the CPU limit:
```kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"800m", "memory":"600Mi"}}}]}}'```

After 1/2 minute resize to decrease the CPU limit:
```kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"200m", "memory":"600Mi"}}}]}}'```

Check the CPU resource usage and you will notice that it still follows the increased limit even though limit has been applied to the pod:

![image](https://github.com/kubernetes/kubernetes/assets/29693744/5ffd400b-2140-4e3b-8a9b-90970163543e)

### Kubernetes version

<details>

```console
clientVersion:
  buildDate: "2023-05-17T14:13:27Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: darwin/arm64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-11T17:04:24Z"
  compiler: gc
  gitCommit: 1b4df30b3cdfeaba6024e81e559a6cd09a089d65
  gitTreeState: clean
  gitVersion: v1.27.0
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/arm64
```

</details>

### Cloud provider

<details>
I have tried it locally
</details>

### OS version

<details>

```console
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
```

</details>

**Comment by wenzhaojie** [comment]
How do you enable the feature gate? Could you please tell me the procedure of enabling this alpha feature? Do you config it for all the parts of kubernetes？

**Comment by netcamo** [comment]
Hi @wenzhaojie,

I started minikube with following parameters: `minikube start --driver=docker --memory=5g --feature-gates=InPlacePodVerticalScaling=true --kubernetes-version=v1.27.0`

References :
 [In Place pod resize alpha - Kubernetes blog](https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/)
[Medium Blog - Trying out the new in place pod resource resizing](https://medium.com/@karla.saur/trying-out-the-new-in-place-pod-resource-resizing-68a0b3c42b72)

**Comment by SergeyKanzhelev** [comment]
@netcamo can you confirm that the new CPU limit took an effect and you see the proper values when describing pod by kubectl and if you can check the cpu limits on cgroups - would be great.

/triage needs-information

/cc @vinaykul

**Comment by netcamo** [comment]
@SergeyKanzhelev  


1. Yes the new CPU took an effect 
![image](https://github.com/kubernetes/kubernetes/assets/29693744/fa827a8f-c615-4e9e-a203-63cdaa1f727b)

2. It uses cgroup v2 so I checked  `cpu.max `and got `80000 100000` :
![image](https://github.com/kubernetes/kubernetes/assets/29693744/6b59a4e2-a2a8-4a39-af53-534c39367b83)

**Comment by SergeyKanzhelev** [comment]
@netcamo so the new limits weren't applied to the cgroups?

Do you have a stable repro for this? Or it happens randomly? Will it be applied if you wait longer?

**Comment by netcamo** [comment]
@SergeyKanzhelev  Hi, It always happens  whenever I try the reproduction (instructions above) and also in other similar cases. 

It doesn't apply as long as pod is using resources above limit. However in case the pod starts using less resources than new limit  (for example it finished the task that was using a lot of CPU) then it won't exceed it anymore.

**Comment by SergeyKanzhelev** [comment]
@netcamo would you be able to share the kubelet.log so we can check if there were any errors reported.

**Comment by netcamo** [comment]
[kubelet.log](https://github.com/kubernetes/kubernetes/files/11904845/kubelet.log)

**Comment by SergeyKanzhelev** [comment]
@vinaykul do you have time to take a look at this and see if this is an issue?

**Comment by vinaykul** [comment]
@SergeyKanzhelev No I don't have cycles to investigate as I recently started a new role. But taking a quick look at the attached kubelet log, it is not getting far enough where I expect to see a possible failure logged. Instead we have this...

```bash
Jun 29 10:14:52 minikube kubelet[1852]: E0629 10:14:52.732806    1852 status_manager.go:193] "Could not initialize pod allocation checkpoint manager, please drain node and remove policy state file" err="could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file \"/var/lib/kubelet/pod_status_manager_state\" before restarting Kubelet"
Jun 29 10:14:52 minikube kubelet[1852]: panic: could not restore state from checkpoint: checkpoint is corrupted, please drain this node and delete pod allocation checkpoint file "/var/lib/kubelet/pod_status_manager_state" before restarting Kubelet
Jun 29 10:14:52 minikube kubelet[1852]: goroutine 201 [running]:
Jun 29 10:14:52 minikube kubelet[1852]: k8s.io/kubernetes/pkg/kubelet/status.(*manager).Start(0xc000b739e0)
Jun 29 10:14:52 minikube kubelet[1852]:         pkg/kubelet/status/status_manager.go:194 +0x2b7
Jun 29 10:14:52 minikube kubelet[1852]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000746000, 0xc000b84660?)
Jun 29 10:14:52 minikube kubelet[1852]:         pkg/kubelet/kubelet.go:1589 +0x770
Jun 29 10:14:52 minikube kubelet[1852]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Jun 29 10:14:52 minikube kubelet[1852]:         cmd/kubelet/app/server.go:1175 +0xb8
Jun 29 10:14:52 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 29 10:14:52 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 29 10:14:53 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 5.
Jun 29 10:14:53 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 29 10:14:53 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
```

... likely crashing due to corrupted checkpoint - likely https://github.com/kubernetes/kubernetes/issues/117589 for which there is a proposed fix in PR https://github.com/kubernetes/kubernetes/pull/117615 ( Please review that PR. If @bart0sh has no concerns, we should merge it)

As for the issue described here, I have seen cgroup limit update failure with memory if you attempt to set it lower than usage. I didn't expect that case for CPU but it is possible as I felt it was a reclaimable resource.

@mrunalp @bobbypage Do you happen to know this detail? Should we expect failure setting CPU limits when usage exceed proposed limits?

**Comment by HirazawaUi** [comment]
I can't reproduce this issue, you can check if my process is different from yours.

Create pod
```
➜  ~ cat pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: stress-test
spec:
  containers:
  - name: pod-demo
    image: polinux/stress
    resources:
      limits:
        memory: "600Mi"
        cpu: 0.2
      requests:
        memory: "600Mi"
        cpu: 0.1
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "256M", "-c", "2", "--vm-hang", "1"]
➜  ~ kubectl apply -f pod.yml
pod/pod-demo created
```
Check cgroup configuration
```
➜  ~ kubectl get pods -n stress-test  -oyaml | grep uid
    uid: e5090cc3-8d82-4bd2-9213-7e8df96cfe9b
➜  ~
➜  ~ cat /sys/fs/cgroup/kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b/cpu.max
20000 100000
➜  ~ systemd-cgtop
CGroup                                                                     Tasks   %CPU   Memory  Input/s Output/s                                                                                                                
kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b                  5      19.8    257.2M        -        -
```
Resize to increase the CPU limit:
```
➜  ~ kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"800m", "memory":"600Mi"}}}]}}'
pod/pod-demo patched
➜  ~ cat /sys/fs/cgroup/kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b/cpu.max
80000 100000
➜  ~ systemd-cgtop
CGroup                                                                 Tasks   %CPU   Memory  Input/s Output/s
kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b             5       79.5   257.2M        -        -
```
Resize to decrease the CPU limit:
```
➜  ~ kubectl -n stress-test patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"200m", "memory":"600Mi"}}}]}}'
pod/pod-demo patched
➜  ~ cat /sys/fs/cgroup/kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b/cpu.max
20000 100000
➜  ~ systemd-cgtop
CGroup                                                               Tasks   %CPU   Memory  Input/s Output/s
kubepods/burstable/pode5090cc3-8d82-4bd2-9213-7e8df96cfe9b           5       19.4   257.4M        -        -
```
I started the cluster based on the master branch. Can you try it on the latest version to see if you can reproduce this issue?

**Comment by pacoxu** [comment]
This may need more information as it seems to be not reproducible. 

@netcamo can you reproduce it in another cluster? You seems to run a minikube on Mac.

**Comment by SergeyKanzhelev** [comment]
/retitle [FG:InPlacePodVerticalScaling]  K8s fails to throttle pod so that it follows resized CPU limit

KEP xref: https://github.com/kubernetes/enhancements/issues/1287

**Comment by iholder101** [comment]
Tried to reproduce with the same pod as @HirazawaUi using a kind cluster. Couldn't reproduce as well.
```shell
> k get pods -oyaml | grep uid
    uid: 66fef43a-13b1-4c2b-9864-dbec531b619f

> cat /sys/fs/cgroup/system.slice/docker-155fe2ed6d0395429f29913b5da4430e78cf39f2d41a223d5687a4986284a092.scope/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-burstable.slice/kubelet-kubepods-burstable-pod66fef43a_13b1_4c2b_9864_dbec531b619f.slice/cpu.max
20000 100000

> k patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"800m", "memory":"600Mi"}}}]}}'
pod/pod-demo patched

> cat /sys/fs/cgroup/system.slice/docker-155fe2ed6d0395429f29913b5da4430e78cf39f2d41a223d5687a4986284a092.scope/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-burstable.slice/kubelet-kubepods-burstable-pod66fef43a_13b1_4c2b_9864_dbec531b619f.slice/cpu.max
80000 100000

> k patch pod pod-demo --patch '{"spec":{"containers":[{"name":"pod-demo", "resources":{"requests":{"cpu":"100m","memory":"600Mi"} ,"limits":{"cpu":"200m", "memory":"600Mi"}}}]}}'
pod/pod-demo patched

> cat /sys/fs/cgroup/system.slice/docker-155fe2ed6d0395429f29913b5da4430e78cf39f2d41a223d5687a4986284a092.scope/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-burstable.slice/kubelet-kubepods-burstable-pod66fef43a_13b1_4c2b_9864_dbec531b619f.slice/cpu.max
20000 100000
```

**Comment by netcamo** [comment]
Hi,

I have tried it on v1.29 and still getting the same result.  As you can see from the screenshot CPU limit has been patched to 200 but actual usage is 800 (400%)

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/79572915-eec7-47a9-a66d-90dc80e1bb42">

<img width="369" alt="image" src="https://github.com/user-attachments/assets/9d8e17cd-1357-43b2-9fbb-c76a5c2c3064">


Please let me know if there is something that I am missing.

@pacoxu @iholder101  @HirazawaUi

**Comment by hshiina** [comment]
Although I’m not familiar with minikube, it looks that the minikube docker driver uses `cri-dockerd` that may not fully support `InPlacePodVerticalScaling`. This looks like the same situation described at the first item in the [known issues](https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/#known-issues).  At a glance, `cri-dockerd` does not set `Resources` to `ContainerStatus` ([code](https://github.com/Mirantis/cri-dockerd/blob/ebd9de065ad5e5b933cd4a102550125383416efb/core/container_status.go#L122)) while `containerd` sets it ([code](https://github.com/containerd/containerd/blob/7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c/pkg/cri/server/container_status.go#L123)).

Could you please try a different value from the initial value at decreasing the CPU limits?

**Comment by esotsal** [comment]
> Could you please try a different value from the initial value at decreasing the CPU limits?

Resizing to a different value from the initial value it works. Tested with minikube v1.34.0 on Ubuntu 24.04 using Kubernetes v1.27.0 ( and Kubernetes v1.31.0) on Docker 27.2.0.

It didn't work only when trying to resize to initial value.

Checking logs i see that kuberuntime_manager  doesn't catch an error during GetPodStatus, this might explain the inconsistency seen which is a bug and needs to be fixed, independent on the root cause which might be what @hshiina  has indicated in cri-dockerd )

![image](https://github.com/user-attachments/assets/2ceb5eaf-72a7-4888-ab57-2afdff0ffcf9)

I believe that we might need to propagate also this error up to catch them instead of quietly ignoring as proposed in  https://github.com/kubernetes/kubernetes/pull/127300#event-14651416524  ?  What do you think @hshiina  and @tallclair  ?

**Comment by esotsal** [comment]
@netcamo i propose to update the title to 

> [FG:InPlacePodVerticalScaling] K8s fails to throttle pod so that it follows resized CPU limit **on minikube cri-dockerd**

**Comment by esotsal** [comment]
Will try to create a PR to fix this . added high priority considering minikube is important for many people, including my self :-)

**Comment by esotsal** [comment]
> [Changing the runtime](https://minikube.sigs.k8s.io/docs/handbook/config/#runtime-configuration) with `--container-runtime=containerd` may be one of solutions.

That’s a great idea!

**Comment by esotsal** [comment]
> > [Changing the runtime](https://minikube.sigs.k8s.io/docs/handbook/config/#runtime-configuration) with `--container-runtime=containerd` may be one of solutions.
> 
> That’s a great idea will check it tomorrow. If it works we can update the docs mentioning this. @netcamo what do you think ?

It works fine minikube, using container-runtime=containerd thanks @hshiina.

**Comment by esotsal** [comment]
@netcamo , i have broadcasted the issue in cri-dockerd K8s slack ( [here](https://kubernetes.slack.com/archives/C05JN34UHRP/p1729155015391839) ) to take a look and potentially add support which will fix the issue.  There is not much which can be done from Kubelet side to fix this, Kubelet should be agnostic to the CRI implementation.

area/provider/docker

**Comment by esotsal** [comment]
@haircommander @SergeyKanzhelev @tallclair i propose to close this issue . I will create an issue to cri-dockerd not to be forgotten. What do you think ?

**Comment by SergeyKanzhelev** [comment]
@esotsal thank you for following up. Is there any clarification on CRI API needed to make it clear that those are required?

**Comment by esotsal** [comment]
> @esotsal thank you for following up. Is there any clarification on CRI API needed to make it clear that those are required?

You are welcome, I believe answer is yes, because it is clarified on cri-api v1

- [cri-api/pkg/apis/runtime/v1/api.proto](https://github.com/kubernetes/cri-api/blob/master/pkg/apis/runtime/v1/api.proto#L1315-L1316) 
- [v1.25 release notes](https://github.com/kubernetes/cri-api/tree/8133eb4e68917d1d8d79afc9dedadc72fa2e5e51?tab=readme-ov-file#v125) referring to [111645](https://github.com/kubernetes/kubernetes/pull/111645)

**Comment by esotsal** [comment]
@tallclair and @SergeyKanzhelev should we close this issue WDYT ?
