### ISSUE TITLE
Informer HasSynced always been false

### ISSUE THREAD

**Issue by sologgfun** [kubernetes/kubernetes#118482]
### What happened?

1. In this way , nodeHasSyncedFn always be `false`
```
kubeInformers := informers.NewSharedInformerFactoryWithOptions(kubeDeps.KubeClient, 0, informers.WithTweakListOptions(func(options *metav1.ListOptions) {
			options.FieldSelector = fields.Set{metav1.ObjectNameField: string(kubelet.NodeName)}.String()
		}))
nodeHasSyncedFn := func() bool {
	return kubeInformers.Core().V1().Nodes().Informer().HasSynced()
}
kubeInformers.Start(wait.NeverStop)
for !nodeHasSyncedFn() {
	time.Sleep(100 * time.Millisecond)
}
klog.InfoS("Attempting to sync node with API server")
```

2. Another way, nodeHasSyncedFn become `true`
```
kubeInformers := informers.NewSharedInformerFactoryWithOptions(kubeDeps.KubeClient, 0, informers.WithTweakListOptions(func(options *metav1.ListOptions) {
			options.FieldSelector = fields.Set{metav1.ObjectNameField: string(kubelet.NodeName)}.String()
		}))
nodeHasSynced := kubeInformers.Core().V1().Nodes().Informer()
nodeHasSyncedFn := func() bool {
	return nodeHasSynced.HasSynced()
}
kubeInformers.Start(wait.NeverStop)
for !nodeHasSyncedFn() {
	time.Sleep(100 * time.Millisecond)
}
klog.InfoS("Attempting to sync node with API server")
```

The only different is variable  `nodeHasSynced`.

### What did you expect to happen?

In the both way `nodeHasSyncedFn` should be true.

### How can we reproduce it (as minimally and precisely as possible)?

it`s easy to reproduce. Just paste the code.

### Anything else we need to know?

The first way is copy from kubelet. I don't know why this code doesn't work?
<img width="1293" alt="image" src="https://github.com/kubernetes/kubernetes/assets/13819034/3a1fd25a-3796-4c09-880b-ba53f8d56f2c">

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
v1.25.9
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
I don't fully understand this request, can you elaborate? 
is this a problem on the kubelet or in your local code?

**Comment by sologgfun** [comment]
> I don't fully understand this request, can you elaborate? is this a problem on the kubelet or in your local code?

It`s local code. My question is why the HasSynced()  in first code snippet not be true?
By the way, the first code snippet is copy from kubelet. So there shouldn't be a problem with the first string of code.

**Comment by aojea** [comment]
/kind support
/remove-area kubelet

I think that depends more things on how do you initialize your informers, ... 

> By the way, the first code snippet is copy from kubelet

that is not saying much, kubelet does more things before 🤷 

I think that this is a better question for any of the support channels as it seems more specific to how to use informers than a real bug in the code https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md?plain=1

/close
