### ISSUE TITLE
pull-kubernetes-node-e2e-containerd-dra failing

### ISSUE THREAD

**Issue by Jefftree** [kubernetes/kubernetes#118412]
### Which jobs are failing?

pull-kubernetes-node-e2e-containerd-dra

### Which tests are failing?

The job seems to have some infra related issue

### Since when has it been failing?

Not sure, can't see the full test history

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-containerd-dra

### Relevant SIG(s)

/sig node

**Comment by charles-chenzz** [comment]
https://github.com/kubernetes/kubernetes/pull/118436
guess it's the same problem

**Comment by SergeyKanzhelev** [comment]
this was switched to CRI-O

/close
