### ISSUE TITLE
[sig-release] periodic-release-verify-packages-debs failing consistently

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118449]
test grid:
https://prow.k8s.io/?job=periodic-release-verify-packages-debs

```
Err:11 http://deb.debian.org/debian stretch/main amd64 Packages
  404  Not Found
Err:13 http://deb.debian.org/debian stretch-updates/main amd64 Packages
  404  Not Found
Ign:14 http://deb.debian.org/debian stretch-updates/main all Packages
Fetched 75.4 kB in 0s (83.2 kB/s)
Reading package lists...
W: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
W: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
W: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.
E: Failed to fetch http://deb.debian.org/debian/dists/stretch/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
Makefile:29: recipe for target 'verify-published-debs' failed
make: *** [verify-published-debs] Error 100
```

Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by saschagrunert** [comment]
cc @kubernetes/release-managers 

Do we want to keep this job and fix it, or do something different considering the debs/rpms efforts?

**Comment by xmudrii** [comment]
@saschagrunert I think we should keep this job as long as we build packages for Google infra (those are using different specs then packages for OBS).

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/test-infra/pull/29697 fixed it for debs: https://prow.k8s.io/?job=periodic-release-verify-packages-debs

The corresponding RPM job is also faster now: https://prow.k8s.io/?job=periodic-release-verify-packages-rpms
