### ISSUE TITLE
kube-controller-manager should not cache managedFields

### ISSUE THREAD

**Issue by linxiulei** [kubernetes/kubernetes#118454]
### What would you like to be added?

Remove [`managedFields`](https://github.com/kubernetes/apimachinery/blob/v0.27.2/pkg/apis/meta/v1/types.go#L271) from the cached used by controllers in `kube-controller-manager`. If feasible, this work will be applied to other components having similar use patterns but have no use of `managedFields` at all.

### Why is this needed?

Roughly the content in `managedFields` is a copy of whole object so it takes roughly 40% of total object size, which is a significant memory overhead. Removing it for controllers can improve memory efficiency

**Comment by wojtek-t** [comment]
@apelisse @alexzielenski - FYI

/sig api-machinery

**Comment by apelisse** [comment]
As mentioned, happy to do it from place to place if it helps, don't count on it too much since we might have to add it back if someone wants to use the extract-model.

**Comment by linxiulei** [comment]
Thanks @apelisse. Yeah, understandable but for the moment the optimization is quite appealing so it'd be great to do it.

Sorry for asking - What is the extract-model?

**Comment by apelisse** [comment]
Thanks for asking: https://kubernetes.io/blog/2021/08/06/server-side-apply-ga/#using-server-side-apply-in-a-controller
