### ISSUE TITLE
Pod graceful deletion hangs if the kubelet already rejected that pod at admission time

### ISSUE THREAD

**Issue by bobbypage** [kubernetes/kubernetes#118472]
### What happened?

We observed the following series of events:

1) Pod is created with some attributes that later result in the pod being rejected at kubelet admission time
2) The pod is scheduled to a node
3) The pod is gracefully deleted by a controller, i.e. a deletion timestamp is set on the pod
4) The pod is rejected at kubelet admission time
5) The pod never gets deleted and is stuck: despite having the deletion timestamp set. It seems that kubelet does not issue the final force delete for the pod.

This is problematic in many scenarios, but one specific case it was hit was when the pod is backed by a daemonset controller. This issue manifested in way where since the pod never got deleted in step 5 above, the daemonset controller did not create a new pod to run the on the node and thus node was was not running a replica of the daemonset controller pod.

This seems to a be regression in k8s 1.27, I was not able to repro this behavior in 1.26.

### What did you expect to happen?

It is expected at during the series of events above, after the pod is failed at kubelet admission time, since the pod has a deletion timestamp set, the kubelet should forcefully delete the pod. The pod should not hang in deletion forever. 

### How can we reproduce it (as minimally and precisely as possible)?

Create a 1.27 kind cluster:

```
kind delete cluster


kind_config="$(cat << EOF
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: ipv4
nodes:
# the control plane node
- role: control-plane
- role: worker
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        v: "4"
        read-only-port: "10255"
EOF
)"

kind create cluster --config <(printf '%s\n' "${kind_config}") --image  kindest/node:v1.27.1@sha256:b7d12ed662b873bd8510879c1846e87c7e676a79fefc93e17b2a52989d3ff42b
```

Stop kubelet
```
$ docker exec -it kind-worker /bin/bash
root@kind-worker:/# systemctl stop kubelet
```

Create a pod bound to the node which will trigger a admission error. The below node selector label does not exist, so we expect that the pod should be rejected in admission.

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleep-2
spec:
  nodeSelector:
    this-label: does-not-exist
  nodeName: "kind-worker"
  containers:
  - name: ubuntu
    image:  gcr.io/google-containers/ubuntu:14.04
    command: ["/bin/sleep"]
    args: ["infinity"]
    resources:
      requests:
        cpu: "1"
        memory: "10Mi"
      limits:
        cpu: "1"
        memory: "10Mi"
```

While kubelet is down issue a graceful deletion to set a deletion timestamp on the pod

```
kubectl delete pod ubuntu-sleep-2
```

Verify deletion timestamp is set (pod is pending)

```
$ k get pod ubuntu-sleep-2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"ubuntu-sleep-2","namespace":"default"},"spec":{"containers":[{"args":["infinity"],"command":["/bin/sleep"],"image":"gcr.io/google-containers/ubuntu:14.04","name":"ubuntu","resources":{"limits":{"cpu":"1","memory":"10Mi"},"requests":{"cpu":"1","memory":"10Mi"}}}],"nodeName":"kind-worker","nodeSelector":{"cloud.google.com/gke-nodepool":"default-pool"}}}
  creationTimestamp: "2023-06-05T18:44:09Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2023-06-05T18:44:58Z" <---- deletion timestamp is set
  name: ubuntu-sleep-2
  namespace: default
  resourceVersion: "570"
  uid: 5a8cbd76-f425-46a3-bffb-4cc4eec12557
spec:
  containers:
  - args:
    - infinity
    command:
    - /bin/sleep
    image: gcr.io/google-containers/ubuntu:14.04
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        cpu: "1"
        memory: 10Mi
      requests:
        cpu: "1"
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5c69j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5c69j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  phase: Pending
  qosClass: Guaranteed
```

Start kubelet
```
$ docker exec -it kind-worker /bin/bash
root@kind-worker:/# systemctl start kubelet
```

Observe pod status, the pod is now in failed phase (as expected).
```

$ k get pod ubuntu-sleep-2 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"ubuntu-sleep-2","namespace":"default"},"spec":{"containers":[{"args":["infinity"],"command":["/bin/sleep"],"image":"gcr.io/google-containers/ubuntu:14.04","name":"ubuntu","resources":{"limits":{"cpu":"1","memory":"10Mi"},"requests":{"cpu":"1","memory":"10Mi"}}}],"nodeName":"kind-worker","nodeSelector":{"cloud.google.com/gke-nodepool":"default-pool"}}}
  creationTimestamp: "2023-06-05T18:44:09Z"
  deletionGracePeriodSeconds: 30
  deletionTimestamp: "2023-06-05T18:44:58Z"
  name: ubuntu-sleep-2
  namespace: default
  resourceVersion: "653"
  uid: 5a8cbd76-f425-46a3-bffb-4cc4eec12557
spec:
  containers:
  - args:
    - infinity
    command:
    - /bin/sleep
    image: gcr.io/google-containers/ubuntu:14.04
    imagePullPolicy: IfNotPresent
    name: ubuntu
    resources:
      limits:
        cpu: "1"
        memory: 10Mi
      requests:
        cpu: "1"
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5c69j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-worker
  nodeSelector:
    cloud.google.com/gke-nodepool: default-pool
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5c69j
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  message: 'Pod was rejected: Predicate NodeAffinity failed'
  phase: Failed
  reason: NodeAffinity
  startTime: "2023-06-05T18:44:52Z"

```

However, the `kubectl delete pod` hangs, the pod is never force deleted by kubelet.

### Kubernetes version

1.27

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by bobbypage** [comment]
cc @alculquicondor @mimowo

**Comment by bobbypage** [comment]
The kubelet logs have the following in the above repro:

```
2902:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.336907     643 config.go:398] "Receiving a new pod" pod="default/ubuntu-sleep-2"
2905:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.337057     643 kubelet.go:2343] "SyncLoop ADD" source="api" pods=[default/ubuntu-sleep-2 kube-system/kindnet-rc2cn kube-system/kube-proxy-dfdkl]
2926:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.337680     643 predicate.go:129] "Predicate failed on Pod" pod="default/ubuntu-sleep-2" err="Predicate NodeAffinity failed"
2932:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.337837     643 event.go:307] "Event occurred" object="default/ubuntu-sleep-2" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="NodeAffinity" message="Predicate NodeAffinity failed"
2960:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.341646     643 desired_state_of_world_populator.go:309] "Added volume to desired state" pod="default/ubuntu-sleep-2" volumeName="kube-api-access-xhzq2" volumeSpecName="kube-api-access-xhzq2"
2981:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.354551     643 reconciler_common.go:258] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-xhzq2\" (UniqueName: \"kubernetes.io/projected/9c221c92-7864-46d0-8f9c-a780b49941b3-kube-api-access-xhzq2\") pod \"ubuntu-sleep-2\" (UID: \"9c221c92-7864-46d0-8f9c-a780b49941b3\") " pod="default/ubuntu-sleep-2"
2986:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.358933     643 status_manager.go:830] "Patch status for pod" pod="default/ubuntu-sleep-2" podUID=9c221c92-7864-46d0-8f9c-a780b49941b3 patch="{\"metadata\":{\"uid\":\"9c221c92-7864-46d0-8f9c-a780b49941b3\"},\"status\":{\"qosClass\":null,\"startTime\":\"2023-06-05T18:57:08Z\"}}"
2988:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.359177     643 status_manager.go:839] "Status for pod updated successfully" pod="default/ubuntu-sleep-2" statusVersion=1 status={Phase:Pending Conditions:[] Message: Reason: NominatedNodeName: HostIP: PodIP: PodIPs:[] StartTime:2023-06-05 18:57:08 +0000 UTC InitContainerStatuses:[] ContainerStatuses:[] QOSClass: EphemeralContainerStatuses:[] Resize:}
2989:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.359329     643 pod_startup_latency_tracker.go:162] "Mark when the pod was running for the first time" pod="default/ubuntu-sleep-2" rv="590"
2990:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.359366     643 status_manager.go:893] "Delaying pod deletion as the phase is non-terminal" phase=Failed pod="default/ubuntu-sleep-2" podUID=9c221c92-7864-46d0-8f9c-a780b49941b3
2991:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.359451     643 kubelet.go:2356] "SyncLoop RECONCILE" source="api" pods=[default/ubuntu-sleep-2]
2999:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.455355     643 reconciler_common.go:220] "Starting operationExecutor.MountVolume for volume \"kube-api-access-xhzq2\" (UniqueName: \"kubernetes.io/projected/9c221c92-7864-46d0-8f9c-a780b49941b3-kube-api-access-xhzq2\") pod \"ubuntu-sleep-2\" (UID: \"9c221c92-7864-46d0-8f9c-a780b49941b3\") " pod="default/ubuntu-sleep-2"
3000:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.455452     643 reconciler_common.go:231] "operationExecutor.MountVolume started for volume \"kube-api-access-xhzq2\" (UniqueName: \"kubernetes.io/projected/9c221c92-7864-46d0-8f9c-a780b49941b3-kube-api-access-xhzq2\") pod \"ubuntu-sleep-2\" (UID: \"9c221c92-7864-46d0-8f9c-a780b49941b3\") " pod="default/ubuntu-sleep-2"
3007:Jun 05 18:57:08 kind-worker kubelet[643]: I0605 18:57:08.455758     643 projected.go:189] Setting up volume kube-api-access-xhzq2 for pod 9c221c92-7864-46d0-8f9c-a780b49941b3 at /var/lib/kubelet/pods/9c221c92-7864-46d0-8f9c-a780b49941b3/volumes/kubernetes.io~projected/kube-api-access-xhzq2
3018:Jun 05 18:57:08 kind-worker kubelet[643]: E0605 18:57:08.465593     643 projected.go:198] Error preparing data for projected volume kube-api-access-xhzq2 for pod default/ubuntu-sleep-2: object "default"/"kube-root-ca.crt" not registered
3019:Jun 05 18:57:08 kind-worker kubelet[643]: E0605 18:57:08.465681     643 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/projected/9c221c92-7864-46d0-8f9c-a780b49941b3-kube-api-access-xhzq2 podName:9c221c92-7864-46d0-8f9c-a780b49941b3 nodeName:}" failed. No retries permitted until 2023-06-05 18:57:08.96565382 +0000 UTC m=+1.698244535 (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "kube-api-access-xhzq2" (UniqueName: "kubernetes.io/projected/9c221c92-7864-46d0-8f9c-a780b49941b3-kube-api-access-xhzq2") pod "ubuntu-sleep-2" (UID: "9c221c92-7864-46d0-8f9c-a780b49941b3") : object "default"/"kube-root-ca.crt" not registered
```


and there is no log about the pod being deleted by the status manager. Full kubelet logs - https://gist.github.com/bobbypage/db2fe87a9cb7bc35fa3545e03808f424

**Comment by alculquicondor** [comment]
But this is the same problem as #117018

The DS controller should react to a Pod in a terminal phase and create a replacement Pod. I agree, if we fix kubelet, it's a non-issue, but the DS controller is not behaving correctly.

**Comment by mimowo** [comment]
In this scenario the pod already has a `deletionTimestamp`, so DS ignores it waiting for it to complete (which would normally happen if Kubelet works ok): https://github.com/kubernetes/kubernetes/blame/master/pkg/controller/daemon/daemon_controller.go#L822. 

Not sure what is the expected behavior of DS here. 

I guess DS could look at what is the expected `deletionTimestamp` (like a minute or two), and if exceeded substantially then force-delete the pod itself.

**Comment by smarterclayton** [comment]
A pod that has been rejected due to admission should be continually readded to the pod worker by HandlePodCleanups until it succeeds at being terminated.  That's because the pod is not in the desired set.  Is HandlePodCleanups not adding it it in "Kill" state to the pod worker?

**Comment by bobbypage** [comment]
> A pod that has been rejected due to admission should be continually readded to the pod worker by HandlePodCleanups until it succeeds at being terminated. That's because the pod is not in the desired set. Is HandlePodCleanups not adding it it in "Kill" state to the pod worker?

I took a closer look at this and `HandlePodCleanups` is not handling this case. This is because the pod has been rejected at kubelet admission time, so a pod worker has not started for it. Additionally, the pod is not visible in the runtime, so it's not an orphan pod either. 

The main reason is because the pod has never started, so there is no pod worker driving it. The pod is returned from the desired state, pod manager (as part of `allPods` [here](https://github.com/kubernetes/kubernetes/blob/7cd51541cdc1fab211e22011e76052b997f5ce16/pkg/kubelet/kubelet_pods.go#L1017). However, the pod is correctly filtered out as part of `SyncKnownPods` because there is no pod worker driving it. And since the pod is not part of `activePods` and it's not an orphan pod (since it doesn't exist in runtime because we haven't started it), we end up not do anything with it in `HandlePodCleanups`.

**Comment by smarterclayton** [comment]
> This is because the pod has been rejected at kubelet admission time, so a pod worker has not started for it

Should it be?  I think right now our answer is no - but if we moved admission closer to the pod worker, we'd say yes?  Pros and cons?  We start pod workers for terminating a pod - is rejecting a pod a type of rejection?  

For the short term, why wouldn't HandlePodCleanups manage this case?  It's the "resync" action, and so it's nominally responsible for forcing all other components (pod worker, status manager, runtime) to return to state.  Should it dispatch a TerminatePod call for these rejected pods that are not yet deleted, not known to the pod worker, and not known to the status manager?

**Comment by bobbypage** [comment]
> Should it be? I think right now our answer is no - but if we moved admission closer to the pod worker, we'd say yes? Pros and cons? We start pod workers for terminating a pod - is rejecting a pod a type of rejection?

Long term this might be the best option - having every path go through pod worker and the regular pod termination (i.e. `syncTerminating/syncTerminatedPod` instead of special casing special situations like admission rejection, may be simpler to reason about.

> For the short term, why wouldn't HandlePodCleanups manage this case? It's the "resync" action for the kubelet as controller, and so it's nominally responsible for forcing all other components (pod worker, status manager, runtime) to return to state. Should it dispatch a TerminatePod call for these rejected pods that are not yet deleted, not known to the pod worker, and not known to the status manager?

Adding this to `HandlePodCleanups` is definitely one option and I think we could expand it to cover this case. Me and @mimowo were also considering two other options:

1. Call `TerminatePod` during kubelet rejection. I think it should be fine overall, but has a risk that after a kubelet restart, if a previous pod was still in runtime and it's running, could lead to the pod being deleted by status manager before the orphaned pod is terminated. https://github.com/kubernetes/kubernetes/pull/118599
2. Call `syncPodKill` by pod worker during kubelet rejection. It should go through pod worker and check that all containers are terminated, so it should avoid issue of the first approach. https://github.com/kubernetes/kubernetes/pull/118614

It sounds like option 2 or adding this HandlePodCleanups is the optimal paths forward. Curious to get your thoughts on the options here.

**Comment by mimowo** [comment]
> `Should it dispatch a TerminatePod call for these rejected pods that are not yet deleted, not known to the pod worker, and not known to the status manager?`

Rejected pods are known to the status manager as their status is added in the `rejectPod` function. So the condition would need to be `terminal phase && unknown to pod workers`.

**Comment by didovesei** [comment]
Hi, are there any workarounds in 1.27?

**Comment by alculquicondor** [comment]
The latest version of GKE contains a mitigation for this issue when it's related to Spot VM preemptions. It's still rolling out in some regions/zones. Please ensure you are in the latest patch version available in GKE.

**Comment by mimowo** [comment]
> Hi, are there any workarounds in 1.27?

The fix was cherry-picked for the 1.27 branch in https://github.com/kubernetes/kubernetes/pull/118841, so it should be included in 1.27.4.

**Comment by Stono** [comment]
@alculquicondor ; we're on the latest patch (`1.27.3-gke.1700`) and we see this.

**Comment by alculquicondor** [comment]
Can you clarify what you observe? We fixed a few different things that were related. Some of the fixes should be available in 1.27.3 and the last one in 1.27.4.

**Comment by alculquicondor** [comment]
That sounds unrelated to this issue.
Pod failures (even if uncommon) are expected in a distributed system such as kubernetes. What's important is that the system should recover. This usually means that a replacement pod is created.
In your case, was a replacement pod not created? (for Pods backed by Daemonset, StatefulSet, Job, Deployment).

Nevertheless, just the error message you describe sounds more like #115325, not this issue.

**Comment by adecchi-2inno** [comment]
I am getting `outofcpu` at 1.27.4-gke.900  running at GCP.
