### ISSUE TITLE
DRA: Kubelet doesn't report anything when it fails to prepare dynamic resources

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#118468]
### What happened?

When `PrepareResource` API fails there is no way to understand what happens because error is not reported.

### What did you expect to happen?

Error should be either logged or, better event should be recorded, so user would see it in the `kubelet describe pod` output.

### How can we reproduce it (as minimally and precisely as possible)?

1. Apply this patch to the kubernetes sources:
```
diff --git a/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml b/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
index 13b177c8426..c494a54b287 100644
--- a/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
+++ b/test/e2e/dra/test-driver/deploy/example/pod-inline.yaml
@@ -28,6 +28,7 @@ kind: Pod
 metadata:
   name: test-inline-claim
 spec:
+  nodeName: 127.0.0.1
   restartPolicy: Never
   containers:
   - name: with-resource
```

2. Create a pod: ```kubectl apply -f test/e2e/dra/test-driver/deploy/example/pod-inline.yaml```
3. Get the pod details: 
```
kubectl.sh describe pod test-inline-claim 
Using image: cos-97-16919-294-27 from project: cos-cloud as master image
Using image: cos-97-16919-294-27 from project: cos-cloud as node image
Name:             test-inline-claim
Namespace:        default
Priority:         0
Service Account:  default
Node:             127.0.0.1/127.0.0.1
Start Time:       Mon, 05 Jun 2023 18:50:16 +0300
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Containers:
  with-resource:
    Container ID:  
    Image:         registry.k8s.io/e2e-test-images/busybox:1.29-2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      set && mount && ls -la /dev/
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7snqh (ro)
  without-resource:
    Container ID:  
    Image:         registry.k8s.io/e2e-test-images/busybox:1.29-2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      set && mount && ls -la /dev/
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7snqh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-7snqh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```
4. There is not mentioning why pod is in pending state.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.0.949+9e4f74592c9037-dirty", GitCommit:"9e4f74592c90373a81a04392e165a63230851df9", GitTreeState:"dirty", BuildDate:"2023-05-16T08:40:17Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```
</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>
```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux devel 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pohly** [comment]
> Error should be either logged or, better event should be recorded, so user would see it in the kubelet describe pod output.

Logging is not enough, users don't have access to kubelet logs. Let's generate an event.

I don't know whether we should have a well-defined condition for this. Thoughts anyone?

**Comment by alculquicondor** [comment]
+1 on a condition.

**Comment by pohly** [comment]
From https://github.com/kubernetes/kubernetes/pull/118209#issuecomment-1577138274:
> FYI on the topic of conditions: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3085-pod-conditions-for-starting-completition-of-sandbox-creation. I suggest you sync with the authors of the KEP.

**Comment by pohly** [comment]
In https://github.com/kubernetes/enhancements/pull/4063 I am proposing `ResourceClaimsReady` as new pod condition.

**Comment by SergeyKanzhelev** [comment]
/triage accepted
/priority important-soon

Is it a bug or a feature? Will it be tracked as a part of the enhancement work? If so we can close this one

**Comment by bart0sh** [comment]
@pohly @alculquicondor 
> I don't know whether we should have a well-defined condition for this. 

Can you explain why do you prefer a condition over an event?

**Comment by pohly** [comment]
> Is it a bug or a feature?

Depends on expectations :sweat_smile: 

The [KEP says](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-allocation#managing-resources): `Instead, a suitable event must be emitted which explains the problem`.

I expected this to be done already as part of the initial implementation, which would make this a bug. But one can also argue that this particular part had been deferred until later, which makes this a feature.

> Will it be tracked as a part of the enhancement work? If so we can close this one

We are using separate issues to track individual aspects of the enhancement work, so let's keep this open.

> Can you explain why do you prefer a condition over an event?

Let's focus on adding the event in this issue and discuss the condition in https://github.com/kubernetes/enhancements/pull/4063#discussion_r1221066242
