### ISSUE TITLE
[sig/auto-scaling] Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118447]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
| [ci-kubernetes-e2e-gci-gce-autoscaling-migs](https://testgrid.k8s.io/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling-migs) |   389 |
| [ci-kubernetes-e2e-gci-gce-autoscaling](https://testgrid.k8s.io/sig-autoscaling-cluster-autoscaler#gci-gce-autoscaling) |  388 |

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by dims** [comment]
cc @mwielgus @gjtempleton

**Comment by pbetkier** [comment]
This is cluster autoscaling.
