### ISSUE TITLE
[sig-windows] Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118445]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
| ci-kubernetes-e2e-windows-containerd-gce-1-24 |  401 |                                           
| ci-kubernetes-e2e-windows-containerd-gce-master |  401 |                                             
| ci-kubernetes-e2e-windows-win2022-containerd-gce-master |  361 |                                            
| ci-kubernetes-e2e-azure-disk-windows-containerd-1-25 |   290 |                                            
| ci-kubernetes-e2e-capz-master-windows-service-proxy |  117  |                                           
| ci-kubernetes-e2e-capz-master-windows-hyperv |   90   |                                           
| ci-kubernetes-e2e-capz-containerd-windows-serial-slow-1-25 |   55   |                                           
| pull-kubernetes-e2e-capz-windows-alpha-features |  53   |                                           
| ci-kubernetes-e2e-azure-file-windows-containerd |  42 |                                             
| ci-gce-pd-csi-driver-latest-k8s-master-windows-2019 |  32  |                           

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by marosset** [comment]
Ack - I'll take a look at these
