### ISSUE TITLE
[sig-release] build-packages-debs failing consistently

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118448]
https://testgrid.k8s.io/sig-release-releng-informing#build-packages-debs

```
noop
 fakeroot debian/rules binary
mkdir -p usr/bin
curl --fail -sSL --retry 5 \
	-o usr/bin/kubelet \
	"https://dl.k8s.io/v1.27.2/bin/linux/arm/kubelet"
curl: (22) The requested URL returned error: 404 
make: *** [debian/rules:12: binary] Error 22
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

```

Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by saschagrunert** [comment]
cc @kubernetes/release-managers 

Do we want to keep this job and fix it, or do something different considering the debs/rpms efforts?

**Comment by xmudrii** [comment]
@saschagrunert I think we should keep this job as long as we build packages for Google infra (those are using different specs then packages for OBS).

**Comment by saschagrunert** [comment]
https://github.com/kubernetes/release/pull/3106 fixed it: https://prow.k8s.io/?job=ci-release-build-packages-debs
