### ISSUE TITLE
[sig-node] Fix or reduce frequency or switch off perma-failing jobs

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#118441]
Data as of June 3rd, 9:00 PM Eastern. Latest data can be found here:
http://storage.googleapis.com/k8s-metrics/failures-latest.json

| CI Job | Days Failed |
| --- | --- |
|[ci-cri-containerd-node-e2e-features](https://testgrid.k8s.io/sig-node-containerd#node-e2e-features) | 37 |                                             
|[ci-cri-containerd-node-e2e-unlabelled](https://testgrid.k8s.io/sig-node-containerd#node-e2e-unlabelled) | 38 |                                              
|[ci-crio-cgroupv1-node-e2e-eviction](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-eviction) | 541 |                                             
|[ci-crio-cgroupv1-node-e2e-flaky](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky) | 504 |                                             
|[ci-kubernetes-e2e-node-canary](https://testgrid.k8s.io/sig-testing-canaries#node) | 676 |                                            
|[ci-kubernetes-node-arm64-ubuntu-serial](https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial) | 8 |                                             
|[ci-kubernetes-node-kubelet-containerd-performance-test](https://testgrid.k8s.io/sig-node-containerd#node-kubelet-containerd-performance-test) | 38 |                                              
|[pull-kubernetes-node-e2e-containerd-dra](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-containerd-dra) | 3 |                                             
|[pull-kubernetes-node-kubelet-serial-containerd](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-containerd) | 39 |                                              
|[pull-kubernetes-node-kubelet-serial-cpu-manager](https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager) | 1192 |                                              
|[pull-kubernetes-node-kubelet-serial-crio-cgroupv1](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv1) | 342 |                                             
|[pull-kubernetes-node-kubelet-serial-crio-cgroupv2](https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-serial-crio-cgroupv2) | 384 |                                             
|[pull-kubernetes-node-kubelet-serial-pod-disruption-conditions](https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-e2e-pod-disruption-conditions) | 201 |                                             
|[pull-kubernetes-node-kubelet-serial-cpu-manager](https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager) | 677 |   
|[ci-kubernetes-node-kubelet-serial-cri-o](https://testgrid.k8s.io/sig-node-cri-o#node-kubelet-serial-crio)|   87 |

Additional Context:
https://github.com/kubernetes/test-infra/issues/18600

**Comment by dims** [comment]
cc @SergeyKanzhelev @mrunalp @derekwaynecarr @dchen1107

**Comment by pacoxu** [comment]
`ci-cri-containerd-node-e2e-features` 、`ci-cri-containerd-node-e2e-unlabelled` 、 `ci-kubernetes-node-kubelet-containerd-performance-test` are similar.

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test can not show recent jobs. And in history, some jobs are ABORTED after 2 days of hanging.

The running job is no response for a long period like: 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-kubelet-containerd-performance-test/1665741169050521600/

I suspect those jobs failure are related to the CI platform, and not sure who can take a look on those ABORTED long-hanging jobs.

**Comment by bart0sh** [comment]
`pull-kubernetes-node-e2e-containerd-dra` has been replaced by `pull-kubernetes-node-e2e-crio-dra` and fixed: https://k8s-testgrid.appspot.com/sig-node-presubmits#pr-node-kubelet-crio-dra

**Comment by ffromani** [comment]
some node jobs, like `pull-kubernetes-node-kubelet-serial-cpu-manager ` fail with an error like
```
 W0613 07:35:00.600]   [FAILED] Unexpected error:
W0613 07:35:00.600]       <*fmt.wrapError | 0xc000080380>: 
W0613 07:35:00.600]       validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/containerd/containerd.sock": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService
W0613 07:35:00.600]       {
W0613 07:35:00.600]           msg: "validate service connection: validate CRI v1 runtime API for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService",
W0613 07:35:00.600]           err: <*fmt.wrapError | 0xc000080340>{
W0613 07:35:00.600]               msg: "validate CRI v1 runtime API for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService",
W0613 07:35:00.601]               err: <*status.Error | 0xc000ba6230>{
W0613 07:35:00.601]                   s: {
W0613 07:35:00.601]                       s: {
W0613 07:35:00.601]                           state: {
W0613 07:35:00.601]                               NoUnkeyedLiterals: {}, 
```

AFAIR container images running on CI are based on ubuntu. Lately (didn't get to the root cause) `containerd` packages on debian/ubuntu come with the CRI plugin **disabled** by default. This would be compatible with the error above.

Can we check the `containerd` config on the images/CI? I can do myself but I'd need a refresher of the steps :)

**Comment by ffromani** [comment]
xref: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/118021/pull-kubernetes-node-kubelet-serial-cpu-manager/1668519013010903040/

**Comment by pacoxu** [comment]
> some node jobs, like `pull-kubernetes-node-kubelet-serial-cpu-manager ` fail with an error like
>
> Can we check the `containerd` config on the images/CI? I can do myself but I'd need a refresher of the steps :)

See https://github.com/kubernetes/test-infra/issues/29694. The containerd is too old in the base os image.

**Comment by chendave** [comment]
@dims @SergeyKanzhelev Just a note that `kubelet-gce-e2e-arm64-ubuntu-serial` is back to normal, https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial, 

several e2e are failing, mostly dra related, but this is different story, I will take time to investigate into that, hopefully, start from next month? anyone else help on this is welcome!

/cc @ike-ma

**Comment by dims** [comment]
thanks @chendave !

**Comment by bart0sh** [comment]
@chendave @dims 
> several e2e are failing, mostly dra related

Only one DRA job is failing continuously out of 4: https://k8s-testgrid.appspot.com/sig-node-dynamic-resource-allocation#Summary
There is a possible fix for it, PTAL: https://github.com/kubernetes/test-infra/pull/29771

**Comment by bart0sh** [comment]
> several e2e are failing, mostly dra related

Let's exclude DRA tests from `kubelet-gce-e2e-arm64-ubuntu-serial`: https://github.com/kubernetes/test-infra/pull/29816

**Comment by bart0sh** [comment]
- https://github.com/kubernetes/kubernetes/issues/118660 partly fixed `kubelet-gce-e2e-arm64-ubuntu-serial`
- yet another attempt to fix `containerd-node-e2e-serial` jobs: https://github.com/kubernetes/kubernetes/pull/118685

**Comment by ffromani** [comment]
> @swatisehgal @ffromani there is only one test case left that fails [kubelet-gce-e2e-arm64-ubuntu-serial](https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial): `Device Manager: With sample device plugin [Serial] [Disruptive] should deploy pod consuming devices first but fail with admission error after kubelet restart in case device plugin hasn't re-registered`. Is this being worked on?

yes (albeit with low capacity). We'll start checking the logs because we (at least I) don't have easy access to arm64 machines.

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky is not flaky now. (#119035 is merged as well.)

**Comment by bart0sh** [comment]
@dims Do you happen to know why cpu-manager job presents twice in the list with different counters?
- [pull-kubernetes-node-kubelet-serial-cpu-manager](https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager)  1192
- [pull-kubernetes-node-kubelet-serial-cpu-manager](https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-serial-gce-e2e-cpu-manager) 677

**Comment by bart0sh** [comment]
@dims can you mark in progress and resolved jobs (with may be pointers to the issues and PRs) in the description? It would be easier for devs to pick up unresolved ones.

**Comment by bart0sh** [comment]
[ci-kubernetes-e2e-node-canary](https://testgrid.k8s.io/sig-testing-canaries#node) succeeded:
```
Ran 215 of 544 Specs in 1955.306 seconds
SUCCESS! -- 215 Passed | 0 Failed | 0 Pending | 329 Skipped
```

**Comment by bart0sh** [comment]
Updated stats:

$ curl -s https://storage.googleapis.com/k8s-metrics/failures-latest.json | jq -r 'keys[] as $k | "- \($k): \(.[$k] | .failing_days)"' |grep node |sort -rnk3
- pr:pull-kubernetes-node-kubelet-serial-cpu-manager: 1288
- pull-kubernetes-node-kubelet-serial-cpu-manager: 773
- pr:pull-kubernetes-node-e2e-containerd-features-kubetest2: 682
- ci-crio-cgroupv1-node-e2e-eviction: 637
- pr:pull-kubernetes-node-e2e-containerd-alpha-features: 527
- ci-kubernetes-node-kubelet-serial-cri-o: 183
- ci-kubernetes-node-kubelet-containerd-performance-test: 134
- ci-cri-containerd-node-e2e-unlabelled: 134
- ci-cri-containerd-node-e2e-features: 133
- ci-cgroupv1-containerd-node-e2e-ec2-eks: 65
- ci-cgroupv1-containerd-node-arm64-e2e-ec2-eks: 54
- pr:pull-kubernetes-node-kubelet-serial-containerd: 36
- pr:pull-kubernetes-node-kubelet-serial-containerd-alpha-features: 2

**Comment by pacoxu** [comment]
> ➜  ~ curl -s https://storage.googleapis.com/k8s-metrics/failures-latest.json| jq -r 'to_entries | sort_by(.value.failing_days) | .[] | "\(.key): \(.value.failing_days)"' |grep node |sort -rnk3

```
ci-kubernetes-node-kubelet-serial-cri-o: 249
ci-benchmark-nodelocal-dns-master: 35
```

Can we close this as only a few is in progress?

**Comment by bart0sh** [comment]
I think we're done with this issue:
```
[ -z $(curl -s https://storage.googleapis.com/k8s-metrics/failures-latest.json | jq -r 'keys[] as $k | "- ($k): (.[$k] | .failing_days)"' |grep node |sort -rnk3) ] && echo done
done
```

@dims can you close it?

**Comment by dims** [comment]
thanks @bart0sh 

/close
