### ISSUE TITLE
Informer watching fails with goroutine hanging after a while

### ISSUE THREAD

**Issue by whitewindmills** [kubernetes/kubernetes#118525]
### What happened?

We created informers to watch resources. But after a few days of normally running, we can't receive any events when the resource `clusterresourcebindings` changes(other resources and apiserver are normal). We found out that the corresponding goroutine has been hung for a long time:
![0880c4c80710a6cef812](https://github.com/kubernetes/kubernetes/assets/89241565/65b3134b-00c0-4d84-af13-84c9bc3c634c)

> 

### What did you expect to happen?

We can receive events when the resource `clusterresourcebindings` changes.

### How can we reproduce it (as minimally and precisely as possible)?

unknown

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%H$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.5-1866+83acf0ef051cbe-dirty", GitCommit:"83acf0ef051cbe34d3e3292653c5f2c85eed3b7c", GitTreeState:"dirty", BuildDate:"2023-04-28T10:39:57Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"

```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
This stack trace is from a type generated in a different project with karmada-io/karmada

I suggest you open the bug there and come back if this is really an informer problem, but it seems more related to karmada

/close

**Comment by whitewindmills** [comment]
@aojea 
I can't confirm the cause of the problem, but it doesn't seem to be related to karmada because `clusterresourcebindings` informer clinet is generated by informer-gen.
