### ISSUE TITLE
GPU and non-GPU deployments are with "CrashLoopBackOff" Error

### ISSUE THREAD

**Issue by SaurabhGIT77** [kubernetes/kubernetes#118589]
### Which jobs are failing?

I have encountered continous "CrashLoopBackOff" Errors when launching  GPU Deployments

However now i see that even non-GPU  deployments also i cannot launch  except NGINX

NGINX deployment is running without issues.

### Which tests are failing?

`GPU Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-deployment-case-cuda
  namespace: zal-app-deployments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-app
  template:
    metadata:
      labels:
        app: gpu-app
      #annotations:
      #  device.alpha.kubernetes.io/gpu-index: "1"  # Specify the GPU index you want to use
    spec:
  #    tolerations:
  #    - key: "node-role.kubernetes.io/master"
  #      operator: "Exists"
  #      effect: "NoSchedule"
  #    - key: "node.kubernetes.io/disk-pressure"
  #      operator: "Exists"
  #      effect: "NoSchedule"
      containers:
      - name: gpu-container
        #image: <private-registry>:10.1-runtime-ubi8
        image: <private-registry>:latest
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
            nvidia.com/gpu: 1
          requests:
            cpu: 500m
            memory: 250Mi
            nvidia.com/gpu: 1
`

################################################################################################

`Non-GPU Deployment:
 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: my-app-deployment
   namespace: zal-app-deployments
 spec:
   replicas: 1
   selector:
     matchLabels:
       app: my-app
   template:
     metadata:
       labels:
         app: my-app
     spec:
       containers:
         - name: my-app
           image: <private-registry>/nginx:latest ---> working
           image: <Private-registry>/rhel7:latest ---> not - working
           ports:
             - containerPort: 80

`

### Since when has it been failing?

Recently

### Reason for failure (if possible)

As per one of the recommendation i have tried below recommendation but still it fails with "CrashLoopBackOff"

`$  cat /etc/modprobe.d/nvidia-gsp.conf
options nvidia NVreg_EnableGpuFirmware=0`

I even have encountered the error:

`Low on ephermal storage` but after sometime it successfully pulled the image and again failed.

### Anything else we need to know?

Few details about my environment:

this is a 2-node Kubernetes cluster (1 master and 2 node)

Kubernetes Version : V1.20  (I reason for running an old version is because of LSF kubernetes connector which supports only on V1.20 and we cannot upgrade it)

Containerd:  containerd.io 1.6.6

Calico:  V3.20  (For POD networking)

Please help me on this as i need to get these deplpyments up and running soon

awaiting for your responses

### Relevant SIG(s)

/sig

**Comment by SaurabhGIT77** [comment]
Nvidia GPU version: Tesla V100 SXM2 16GB

GPU Driver version: 525.60.13

CUDA Version: 12.0

nvidia-container-runtime : 
runc version 1.1.2
commit: v1.1.2-0-ga916309
spec: 1.0.2-dev
go: go1.17.11
libseccomp: 2.3.1

**Comment by tzneal** [comment]
1.20 is End of Life. 

I suspect this is related to something about your particular configuration.  If you are running out of ephemeral storage, you should increase the size of the disk on your nodes.  You should also look at the logs of your pods, there may be information there that indicates why they are crashing. See https://kubernetes.io/docs/concepts/cluster-administration/logging/ for information about getting logs.

You can also run `kubectl describe pod pod-name` to see the events registered against the pod which might be informative.

/kind support
