### ISSUE TITLE
Prometheus auto discovery

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#11858]
The current Prometheus config in contrib requires up front configuration via env vars to select which service to scrape metrics for. I've submitted a PR to Prometheus for initial kubernetes discovery of nodes & services to scrape - https://github.com/prometheus/prometheus/pull/905. 

Nodes & services are watched & scraped metrics are labeled using the kubernetes labels to make it easy to reuse kubernetes labels across both systems. Nodes are automatically scraped so api server, kubelet & container cgroup metrics are ingested into Prometheus.

Discovery of services to scrape is done by watching services & checking that appropriate annotations (`prometheus.io/*`) are set to start scraping the service endpoints, which are also watched as they come & go. Again, metrics are labeled using the kubernetes labels. This gives clusters automatic ingestion of their application metrics of they expose Prometheus formatted metrics (pretty easy to do with the various Prometheus exporters available).

I'm waiting on a review of the Prometheus PR but was wondering if this is something the kubernetes community would be interested in. If so, I'd love to hear what people would like to see, either on this issue or on the Prometheus PR linked above.

**Comment by lavalamp** [comment]
Please make a parallel PR here, they sound like good improvements!

**Comment by jimmidyson** [comment]
While waiting on the PR to Prometheus be merged (next few days), I've been looking at how the metrics are exposed from Kubernetes.

Kubernetes currently embeds cadvisor & lets that register the container metrics with prometheus. Problem is that cadvisor doesn't know about any kubernetes metadata, just docker metadata, so the name label on the metric comes through with the name of the docker container. That is constructed from kubernetes metadata so contains everything relevant (namespace, pod name, container name), but in a hard to consume format after ingestion into prometheus. For example, a metric comes through with the name label same as the docker container name: name="k8s_router.e88e294e_router-1-yh1ra_default_da78f10a-3f90-11e5-8968-54ee7527188d_32bed9d3". This could be done with metric relabelling in Prometheus but that is going to be highly inefficient as it would have to target every individual metric after scrape, before storage. Metric

Do you have any suggestions on how to handle this? I'd like to be able to rewrite the cadvisor metrics before they're exposed in the prometheus handler but can't see any way to do that.

I can work on a PR but really not quite sure what the best approach is.

**Comment by vishh** [comment]
#12483 We can update the kubelet to export pod and node metrics, which can also be exported to prometheus.

**Comment by jimmidyson** [comment]
Kubernetes metadata will be added to Prometheus metrics via #15612.

**Comment by jimmidyson** [comment]
Prometheus now does discovery of nodes, etc from the Kubernetes API server so once #15612 is merged we can close this.

**Comment by mattthias** [comment]
@jimmidyson  It looks like https://github.com/kubernetes/kubernetes/pull/15612 is merged now.
