### ISSUE TITLE
Metadata of immutable secrets cannot be changed when the `.data` has a key with empty value

### ISSUE THREAD

**Issue by dimityrmirchev** [kubernetes/kubernetes#118588]
### What happened?

I have created the following secret in my cluster.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
immutable: true
data:
  "foo": ""
  "one": dHdvCg==
```

When I add labels to my secret and try to apply it in the cluster I get the following error 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test
  labels:
    "foo": "bar"
immutable: true
data:
  "foo": ""
  "one": dHdvCg==

```

```bash
$ k apply -f secret.yaml
The Secret "test" is invalid: data: Forbidden: field is immutable when `immutable` is set
```

This also happens when I use `kubectl edit` or using the `controller-runtime` go client.

Not sure why, but `kubectl label` works.
```bash
$ k label secret test foo=bar
secret/test labeled
```

### What did you expect to happen?

I expect that the secret can be updated with the new labels since the `data` is not actually changed.

### How can we reproduce it (as minimally and precisely as possible)?

Steps explained above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-30T06:34:50Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
That issue has been resolved and I think it's time close it

/close
