### ISSUE TITLE
managed-nfs-storage": unexpected error getting claim reference: selfLink was empty, can't make reference

### ISSUE THREAD

**Issue by chenxb0715** [kubernetes/kubernetes#118582]
### What would you like to be added?

I usede  k8s version is  1.25.4 .  when I  start  nfs-client-provisioner  ,It is error, and the error log is：managed-nfs-storage": unexpected error getting claim reference: selfLink was empty, can't make reference 。 if I added parameters - --feature-gates=RemoveSelfLink=false  to kube-apiserver  command , the service hung up

### Why is this needed?

I can't use nfs   storgeclass   in k8s version is  1.25.4

**Comment by tamilselvan1102** [comment]
Refer here, you may get an idea 
https://github.com/kubernetes/enhancements/issues/1164

**Comment by tamilselvan1102** [comment]
In k8s 1.20 they have removed selfLink as per [release notes](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.20.md).

Adding selfLink manually does not help, as that is removed by API server immediately.

**Comment by alexzielenski** [comment]
As @tamilselvan1102 says, `selfLink` was deprecated. Closing since this seems to be an issue with a third party project. If you think this is in error, feel free to re-open

/triage accepted
/close
