### ISSUE TITLE
PV stuck at release status after pod and PVC is deleted

### ISSUE THREAD

**Issue by ruanyulin2017** [kubernetes/kubernetes#118562]
### Description
I have a pod use a PVC, and the PV is provided by `ceph-csi`. 
1、Delete the pod and PVC, the volume fail to detach and the `kubelet` kept trying to detach the volume.
2、A few minutes later (6 mins), `attach-detach-controller` force detach the volume, and the volume has been removed from `node.status.volumesAttached`
3、Restart the `kubelet`, the volume has been removed from `node.status.volumesInUse`, and `kubelet` stop trying detach the volume.  4、The PV stuck in `release` status

### Kubernetes version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.19", GitCommit:"ac0cc736d0018d817c763083945e4db863168d12", GitTreeState:"clean", BuildDate:"2021-05-12T11:29:07Z", GoVersion:"go
1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.19", GitCommit:"ac0cc736d0018d817c763083945e4db863168d12", GitTreeState:"clean", BuildDate:"2021-05-12T11:21:54Z", GoVersion:"go
1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

we reproduce it:
1、Create a PVC which use a out-tree csi
2、Create a pod which use the PVC
3、Delete the pod and PVC
4、Make the detach operation fail
5、After the `attach-detach-controller` force detach the volume, restart the `kubelet`

**Comment by xing-yang** [comment]
@ruanyulin2017, did you open an issue in ceph-csi for them to take a look first?
