### ISSUE TITLE
Can we have multiple managers which points to different configs in the same controller? Is that supported?

### ISSUE THREAD

**Issue by Kiruthika-Jayabalan** [kubernetes/kubernetes#118584]
### What would you like to be added?

Usecase to have multiple managers in the same controller

### Why is this needed?

Usecase to have multiple managers in the same controller

**Comment by AmarNathChary** [comment]
hey @Kiruthika-Jayabalan  can u please describe the issue more clearly

**Comment by AmarNathChary** [comment]
If u are looking for this.
> Can we have multiple managers which points to different configs in the same controller? Is that supported?

It is possible to have multiple managers within the same controller, each pointing to different configurations. This approach allows you to handle different resources or perform various operations based on the specific configurations assigned to each manager.

**Comment by neolit123** [comment]
/close

please reopen once you add the missing information.
