### ISSUE TITLE
Configuring Projected volume with pod is always in CrashLoopBackoff State

### ISSUE THREAD

**Issue by niranjandarshann** [kubernetes/kubernetes#118526]
Page related to the issue:  https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secrets-nondefault-permission-mode
When i am creating a projected volume having two secrets mysecret and mysecret1 at the location /project-volume/my-guide/my-username and /project-volume/my-guide/my-password the secret get created perfectly and when i create a pod it get created but remain in CrashLoopBackoff State.
Whether i am missing any thing or is there any problem with the file.

I am attaching the whole process i do:

**File Location**

![secrets file path](https://github.com/kubernetes/kubernetes/assets/124760321/b2d96767-4e7b-4d0d-a591-fb8d7a18dcee)

**Created Secrets**

![Created secrets](https://github.com/kubernetes/kubernetes/assets/124760321/7012d761-4ec5-4728-9c7b-f9e90ff0b2f8)

**Yaml file of Pod**

![Pod yaml file (podproj.yaml)](https://github.com/kubernetes/kubernetes/assets/124760321/cb4dbd29-1401-49a2-81b8-a07ebe447af5)

**Final Output**

![final output](https://github.com/kubernetes/kubernetes/assets/124760321/ab299f7e-ffa3-4f07-b372-d639b740fd66)

Your opinion and help means a lot to me. 

**Proposed solution :**
The pods should go in Ready state.

**Comment by niranjandarshann** [comment]
I am attaching the description of the pods volume-test.
![description of pods](https://github.com/kubernetes/kubernetes/assets/124760321/151f9b67-be5d-4fbc-844e-8f9262b5813c)

**Comment by killshotrevival** [comment]
Hey @niranjandarshann , I believe the issue is not with the volumes, but with the image, you are using, busy box as the image, but as there is no process that keeps the container running, the pod is completing, as you can see in your first screenshot, and after that it is going to crashloopback state. 

To keep a container running you can try something like:
```
  - name: container-test
    image: busy box
    command: ["sleep", "3600"]
```

This will start a sleep process in your busybox, that will keep the container running for 1 hr. Hope this help 😃

**Comment by niranjandarshann** [comment]
> Hey @niranjandarshann , I believe the issue is not with the volumes, but with the image, you are using, busy box as the image, but as there is no process that keeps the container running, the pod is completing, as you can see in your first screenshot, and after that it is going to crashloopback state.
> 
> To keep a container running you can try something like:
> 
> ```
>   - name: container-test
>     image: busybox
>     command: ["sleep", "3600"]
> ```
> 
> This will start a sleep process in your busybox, that will keep the container running for 1 hr. Hope this help smiley

@killshotrevival Thank you for your support now the pod is running by adding command labels in my yaml file.

**Comment by niranjandarshann** [comment]
closing the issue marking it as resolved 
/close
