### ISSUE TITLE
Hardware interrupts are occurring at 0.3% on all CPUs.

### ISSUE THREAD

**Issue by skchoi1234** [kubernetes/kubernetes#118663]
### What happened?

After upgrading kubernetes version to 1.26.5, hardware interrupts on all CPUs are eating up 0.3%.

kubelet-config.yaml
--------------------
kubeletCgroups: /system.slice/kubelet.service
clusterDomain: cluster.local
protectKernelDefaults: true
rotateCertificates: true
clusterDNS:
- 169.254.25.10
systemReservedCgroup: /system.slice
systemReserved:
  cpu: 500m
  memory: 512Mi
resolvConf: "/run/systemd/resolve/resolv.conf"
eventRecordQPS: 5
shutdownGracePeriod: 30s
shutdownGracePeriodCriticalPods: 10s
kubeReserved:
  cpu: 500m
  memory: 512Mi
cpuManagerPolicy: static
CPUManagerPolicyOptions:
  full-pcpus-only: true
topologyManagerPolicy: "single-numa-node"
memoryManagerPolicy: "Static"
reservedMemory:
  - numaNode: 0
    limits:
      memory: 1124Mi
------------------------

CPUManage is True. and full-pcpus-only: true, topologyManagerPolicy: "single-numa-node"
because our pod use dpdk/numa.

### What did you expect to happen?

I don't want hardware interrupts to occur as they did in the previous version (1.23.5).

### How can we reproduce it (as minimally and precisely as possible)?

This is what I get when I install kubernetes 1.26.5 with kubespray, of course...CPUManage, etc. set to true.

### Kubernetes version

<details>

```console
$ kubectl version
kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:14:46Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
baremetal  ubunut linux 
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux 5gcf-v4-primary 5.15.0-1032-realtime #35-Ubuntu SMP PREEMPT_RT Tue Jan 24 11:45:03 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubespray
</details>

### Container runtime (CRI) and version (if applicable)

<details>
crio. 1.26.3
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
   - multus cni : v3.9.3
   - calico : v3.25.1
   - SR-IOV cni :  v2.6.3
   - SR-IOV  device plugin v3.5.1
   - dpdk : 22.11.1
</details>

**Comment by pacoxu** [comment]
Any details about the hardware interrupts?
Is there any error log in kubelet?

**Comment by skchoi1234** [comment]
The kubelet isn't throwing any warnings or errors, so maybe it has
something to do with the OS kernel?  Our system is using kernel version
"Linux 5gcf-v4-primary 5.15.0-1032-realtime #35-Ubuntu " for DPDK.

2023년 6월 15일 (목) 오전 10:35, Paco Xu ***@***.***>님이 작성:

**Comment by pacoxu** [comment]
/kind support
It is a kernel or hardware issue, not a kubernetes issue.

Probably, you should use [kdump](https://en.wikipedia.org/wiki/Kdump_(Linux)) to get the kernel crash root cause or connect the hardware to investigate it.

**Comment by skchoi1234** [comment]
First of all, thank you for your response.
However, when I checked the hw interrupt after OS installation and Kernel
Upgrade installation, there was no problem (i.e..hw interrupt is 0%).
However. after installing kubernetes, hw interrupt is taking up a certain
percentage (0.3~0.7%) on all nodes.

2023년 6월 24일 (토) 오후 4:54, Paco Xu ***@***.***>님이 작성:

**Comment by pacoxu** [comment]
/triage needs-information
The information is still not enough to do a further investigation from my side.

**Comment by skchoi1234** [comment]
What more information do you need?

2023년 6월 24일 (토) 오후 9:04, Paco Xu ***@***.***>님이 작성:

**Comment by skchoi1234** [comment]
After changing the Calico version from 1.25.1 to 1.24.5, the occurrence of
hw interrupts decreased significantly.  It still happens occasionally, but
I need to test this a bit more.

2023년 6월 24일 (토) 오후 9:08, 최승권 ***@***.***>님이 작성:

**Comment by pacoxu** [comment]
What you have provided so far are all symptoms, and it is impossible for people to locate the root of the problem unless this is some known issue. However, I cannot search out similar symptoms across Kubernetes and Calico issues. I prefer that you should contact the Hardware provider to check what happened.

BTW, the Kubernetes GitHub issue is used to track proven kubernetes bugs or features/CI failures.
To get some support or QA,  https://discuss.kubernetes.io/, and Slack may be better places for that.

**Comment by SergeyKanzhelev** [comment]
+1 to what @pacoxu saying. @skchoi1234 maybe you can provide more information on how you measure hardware interrupts and maybe provide kdump as suggested in https://github.com/kubernetes/kubernetes/issues/118663#issuecomment-1605301819.

/sig network

SIG network, is there any known issues with Calico and interrupts?

**Comment by skchoi1234** [comment]
This issue was resolved by changing the kernel version. I changed the
kernel version (5.15.0-1032-realtime) to the default kernel version
(5.15.0-76-generic) of ubuntu 22.04 for dpdk and installed kubernetes, and
the hw interrupt issue did not occur.

2023년 6월 29일 (목) 오전 2:34, Sergey Kanzhelev ***@***.***>님이 작성:
