### ISSUE TITLE
sig-node-containerd#cos-cgroupv1/v2-containerd-node-e2e-serial are failing

### ISSUE THREAD

**Issue by akhilerm** [kubernetes/kubernetes#118660]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e-serial

### Which tests are failing?

sig-node : DRA related tests are failing

```
 [sig-node] DRA [Feature:DynamicResourceAllocation][NodeFeature:DynamicResourceAllocation] Resource Kubelet Plugin [Serial] must register after plugin restart
``` 
and 2 other DRA related tests.

### Since when has it been failing?

Both jobs started failing on 7th June

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-node-e2e-serial

### Reason for failure (if possible)

As per the logs DRA plugin is not getting registered to kubelet

```
"kubelet plugin/registrar: handling request failed" err="failed registration process: RegisterPlugin error -- no handler registered for plugin type: DRAPlugin at socket /var/lib/kubelet/plugins_registry/test-driver.cdi.k8s.io-reg.sock" node="tmp-node-e2e-7cd1fcd8-cos-stable-105-17412-101-24" requestID=14 request="&RegistrationStatus{PluginRegistered:false,Error:RegisterPlugin error -- no handler registered for plugin type: DRAPlugin at socket /var/lib/kubelet/plugins_registry/test-driver.cdi.k8s.io-reg.sock,}"
```

### Anything else we need to know?

Jobs started failing after merging https://github.com/kubernetes/kubernetes/pull/118044. 

As per https://github.com/kubernetes/test-infra/pull/29681, CDI is not available out of the box for containerd which may be the reason for failure of the jobs. 

### Relevant SIG(s)

/sig node

**Comment by bart0sh** [comment]
Looks like I shouldn't have labeled DRA Node tests as NodeFeature. However, re-labeling it NodeAlphaFeature would not work either - `pull-kubernetes-node-e2e-containerd-alpha-features` would start to fail.
I'm going to remove `NodeFeature label`. This should help.

**Comment by bobbypage** [comment]
Not fixed yet, pending https://github.com/kubernetes/kubernetes/pull/118685
