### ISSUE TITLE
Parse bool env yaml to string

### ISSUE THREAD

**Issue by Vacant2333** [kubernetes/kubernetes#118649]
### What would you like to be added?

When I add an environment variable to the deployment, I want its value to be "true". However, to achieve this, I have to add double quotes in the YAML file. If I don't do this, the following error will occur. I believe this error is unnecessary. Although YAML can parse it as a boolean, the environment variable can only be a string type. Can we add a feature where if the value of the environment variable in the YAML is true/false (boolean type rather than string), it gets parsed as "true"/"false", instead of resulting in a direct error?
![image](https://github.com/kubernetes/kubernetes/assets/19872346/f47aa6d7-55b0-4ca4-a3c4-fa17c7a9539d)
![image](https://github.com/kubernetes/kubernetes/assets/19872346/1053ca5e-3b8c-4e42-b66d-4407b0c393cc)
And I believe this feature is necessary. If possible, I would like to implement it myself.

### Why is this needed?

This would help avoid errors when users set environment variables without using double quotes.

**Comment by tamilselvan1102** [comment]
spec.container.env.value is defined as string. see here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#envvar-v1-core
You'd have to cast/convert/coerse to boolean in your container when using this value

**Comment by Vacant2333** [comment]
> spec.container.env.value is defined as string. see here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.23/#envvar-v1-core You'd have to cast/convert/coerse to boolean in your container when using this value

yes i know that, but it will parse to bool  in yaml, and then this bool value will throw a error because env.value must be a string,

**Comment by tamilselvan1102** [comment]
Try escaping the value. The below will work

- name: BOOLEAN_DEMO
  value: "'true'"

**Comment by Vacant2333** [comment]
> Try escaping the value. The below will work
> 
> * name: BOOLEAN_DEMO
>   value: "'true'"

yes it will works, but we know that the env must be string, so we may can parse it automaticly

**Comment by shani34** [comment]
Hi, can someone please assign this issue to me.

**Comment by Vacant2333** [comment]
i would be happy to make this issue

**Comment by tamilselvan1102** [comment]
/ assign @shani34

**Comment by tamilselvan1102** [comment]
@shani34 
You can assign your self by using [/assign] label

**Comment by shani34** [comment]
Thanks everyone, will start working on it

**Comment by shani34** [comment]
Hi, can someone please help me reproducing/debugging this issue on code level......i tried but i am unable to find.

**Comment by liggitt** [comment]
The yaml → json translation happens client-side without access to the schema, and is done in an untyped way. That means for ambiguous values like `true`, you need to quote them if you want them to be sent to the server as a string

/close
