### ISSUE TITLE
Make PauseVersion configurable

### ISSUE THREAD

**Issue by yongxiu** [kubernetes/kubernetes#118643]
### What would you like to be added?

Currently pause image tag is hard coded in https://github.com/kubernetes/kubernetes/blob/3d27dee047a87527735bf74cfcc6b8ff8875f66c/cmd/kubeadm/app/constants/constants.go#LL420C2-L420C14

But we want change it to another tag during running kubeadm

Add a new filed just like `KubernetesVersion` in ClusterConfiguration, so we can customize the Pause image tag without changing the source code.

### Why is this needed?

This is usually fine since kubeadm will fail to pull the image if registry server returned not found, kubeadm will proceed, however if registry server is not responding in time, kubeadm will stuck there forever.

**Comment by neolit123** [comment]
this has been discussed in the past, but it was rejected.
https://github.com/kubernetes/kubeadm/issues/2020

long term kubeadm may stop managing pause.

/close
