### ISSUE TITLE
HPA doesnot support dynamic memory calculation

### ISSUE THREAD

**Issue by AboobakerSiddiq** [kubernetes/kubernetes#118676]
### What would you like to be added?

Dynamic calculation of memory utilization in percentage for Horizontal Pod Autoscaler

### Why is this needed?

The proposed addition is to enable the dynamic calculation of memory utilization in percentage for the Horizontal Pod Autoscaler (HPA) in Kubernetes. Currently, the HPA only supports autoscaling based on a static memory value, which may not accurately reflect the overall memory usage of the pods. By introducing dynamic calculation of memory utilization as a percentage, the HPA will be able to scale pods more effectively based on the actual memory demands of the application.

The need for dynamic calculation of memory utilization in percentage arises from the desire to optimize resource allocation in Kubernetes clusters. Memory is a critical resource for containerized applications, and scaling based on a fixed memory value can lead to either underutilization or overutilization of resources.

By calculating memory utilization dynamically as a percentage, the HPA can adapt to changing workload patterns and adjust the number of pods accordingly. This ensures that the application remains responsive and efficient, as the autoscaler takes into account the overall memory consumption of the pods in relation to their allocated resources.

With this enhancement, Kubernetes users will have a more accurate and flexible approach to autoscaling, allowing them to effectively manage memory resources and ensure optimal performance of their applications.

**Comment by zijiwork** [comment]
I am in favor of ，By introducing dynamic memory calculation as a percentage, HPA would become more responsive to the actual memory needs of applications. This would allow for more accurate and efficient scaling of Pods based on their real-time memory utilization. It's a cr ucial step towards Optimizing resource allocation in Kubernetes clusters.

**Comment by Horiodino** [comment]
hey guys I would like to work on it, can I.
