### ISSUE TITLE
SONiC support

### ISSUE THREAD

**Issue by mmaymann** [kubernetes/kubernetes#118609]
Support SONiC devices to create a CloudNative approach handling network equipment:
SONiC hardware = K8s nodes
SONiC containers = K8s containers
SONiC apps = K8s apps
SONiC port acl= K8s policies

https://github.com/sonic-net/SONiC

**Comment by aojea** [comment]
It seems that this is a request for the SONIC project https://github.com/sonic-net/SONiC. not for Kubernetes
I know @MikeZappa87 was poking around this topic, maybe he can share some information, but I'm going to close the issue to not give false expectactions

Thanks

/close
