### ISSUE TITLE
kubectl fail to get pod log when docker use log driver "local-dirver"

### ISSUE THREAD

**Issue by tufeigunchu** [kubernetes/kubernetes#118682]
### What happened?

In /etc/docker/daemon.json, I set "log-driver": "local", then deploy kubenetes v1.25. But it can't get pod log. 
If I use default json driver for logging, it works.

### What did you expect to happen?

Why not support "local-driver" any more? I beleive kubernetes 1.20 supports it.

### How can we reproduce it (as minimally and precisely as possible)?

Let docker use "local-driver", then deploy kubernetes v1.24 or above.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"archive", BuildDate:"2023-06-13T08:23:19Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T12:08:36Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
local
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ uname -a
Linux k8s 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
rke
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tufeigunchu** [comment]
kubelet says
E0615 09:37:16.733665    7133 container_log_manager.go:251] "Container log doesn't exist, reopen container log failed" err="rpc error: code = Unknown desc = docker does not support reopening container log files" containerID="7947cf030eb907d9c3c28ef209cc79f6b4380d1e9c486102a5377e5966004727" path="/var/log/pods/kube-system_coredns-dfb7f8fd4-pzpjh_3ec4675d-d2db-4a61-a882-af05b8b75b2b/coredns/0.log"
E0615 09:37:16.734952    7133 remote_runtime.go:1168] "ReopenContainerLog from runtime service failed" err="rpc error: code = Unknown desc = docker does not support reopening container log files" containerID="da6192141bd7d52a05275d830a4546da42252e8088bfa95975667afae0fa6709"
E0615 09:37:16.734973    7133 container_log_manager.go:251] "Container log doesn't exist, reopen container log failed" err="rpc error: code = Unknown desc = docker does not support reopening container log files" containerID="da6192141bd7d52a05275d830a4546da42252e8088bfa95975667afae0fa6709" path="/var/log/pods/kube-system_calico-node-stv7k_3d80cff5-9c17-4336-b220-b1f83d76efef/calico-node/0.log"

**Comment by tufeigunchu** [comment]
kubectl logs -n kube-system     calico-node-stv7k
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
failed to try resolving symlinks in path "/var/log/pods/kube-system_calico-node-stv7k_3d80cff5-9c17-4336-b220-b1f83d76efef/calico-node/0.log": lstat /var/log/pods/kube-system_calico-node-stv7k_3d80cff5-9c17-4336-b220-b1f83d76efef/calico-node/0.log: no such file or directory

**Comment by SataQiu** [comment]
/sig node

FYI: https://kubernetes.io/blog/2022/02/17/dockershim-faq/
Since v1.24, the dockershim has been removed from Kubernetes, you'd better migrate to containerd for better performance and less overhead.

**Comment by pacoxu** [comment]
For v1.25, the cri code is in https://github.com/Mirantis/cri-dockerd/issues. Not sure if you should move this issue to that project.

**Comment by SergeyKanzhelev** [comment]
/close

this should be cri-dockerd issue. I'm not familiar with "local" driver. Maybe it doesn't store files in the location kubelet expects?
