### ISSUE TITLE
Report duplicated entries of errors in k8s v1.26.4

### ISSUE THREAD

**Issue by fuxiaoting** [kubernetes/kubernetes#118632]
### What happened?

It report duplicated errors when run kubectl failed.
`root@d4da4821-1f06-4d7e-604d-7dff9712f8e4:/tmp/build/5f4c2eb5# kubectl get all
W0524 07:31:19.522712    1807 loader.go:222] Config not found: /root/.kube/config
E0524 07:31:19.526502    1807 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0524 07:31:19.527115    1807 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0524 07:31:19.528664    1807 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0524 07:31:19.530175    1807 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
E0524 07:31:19.531578    1807 memcache.go:265] couldn't get current server API group list: Get "http://localhost:8080/api?timeout=32s": dial tcp 127.0.0.1:8080: connect: connection refused
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@d4da4821-1f06-4d7e-604d-7dff9712f8e4:/tmp/build/5f4c2eb5# kubectl version
W0524 07:48:36.530178    1824 loader.go:222] Config not found: /root/.kube/config
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"clean", BuildDate:"2023-04-12T12:13:53Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?`

### What did you expect to happen?

Only one entry of error shows there.

### How can we reproduce it (as minimally and precisely as possible)?

Deploy a cluster with kubernetes v1.26.5
And did not set kubeconfig file to execute kubectl command. e.g: kubectl get all

### Kubernetes version

<details>
kubernetes version is v1.26.4
```console
$ kubectl version
# root@d4da4821-1f06-4d7e-604d-7dff9712f8e4:/tmp/build/5f4c2eb5# kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4", GitCommit:"f89670c3aa4059d6999cb42e23ccb4f0b9a03979", GitTreeState:"clean", BuildDate:"2023-04-12T12:13:53Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
`
```

</details>

### Cloud provider

<details>
We use our own provider.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
Getting kubectl to run really depends on how you installed it. Basically, if you install and have a proper config file, it should always work. So, either an old file from a previous installation is there or something silly like that (although usually difficult to spot).

**Comment by tamilselvan1102** [comment]
Try below steps may solve your problem
mkdir ~/.kube
vim ~/.kube/config
and copy the config file from mster node to nodes config file

**Comment by fuxiaoting** [comment]
> Try below steps may solve your problem mkdir ~/.kube vim ~/.kube/config and copy the config file from mster node to nodes config file

Thanks for the quick response.
Yeah I see it should use the config file. 
This case is a negative one, just want to check the error handling.

For previous release, this error will only report one entry. But now it reported several duplicated error message.

**Comment by tamilselvan1102** [comment]
As per code, it showing the error for each  kube config file. 
 https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#LL220C44-L220C44

**Comment by fuxiaoting** [comment]
> As per code, it showing the error for each kube config file if unable to load the configurations from that. https://github.com/kubernetes/client-go/blob/master/tools/clientcmd/loader.go#LL220C44-L220C44

Thanks. So is it by design? Changed in k8s v1.26?

**Comment by liggitt** [comment]
cc @seans3
