### ISSUE TITLE
Helm upgrade points to old service account and fails with missing token

### ISSUE THREAD

**Issue by TahjidAshfaque** [kubernetes/kubernetes#118670]
### What happened?

We have a application that generates a service account using the following yaml file:

{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace (.Values.serviceAccountName | default "service-account")) }} apiVersion: v1 kind: ServiceAccount metadata: labels: app.kubernetes.io/instance: instancename name: {{ .Values.serviceAccountName | default "service-account" }} namespace: {{ .Release.Namespace }} {{- end }} 

When we do helm install the first time it works without any issues. But when we try to do helm upgrade, it gets stuck in the containercreating stage with the following message
 Warning  FailedMount  5s (x5 over 13s)  kubelet            MountVolume.SetUp failed fo │ │ r volume "service-account-token-xxxxx" : secret "service-account-token-xxxxx" not found

The old pod keeps running without any problem. This only happens with helm upgrade, running helm uninstall and helm install fixes the issue. I would appreciate any help or suggestions. Please feel free to ask for any more information you might need.

### What did you expect to happen?

The 2nd pod would start successfully and move to ready state and the original pod would be terminated

### How can we reproduce it (as minimally and precisely as possible)?

service_account.yaml
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace (.Values.serviceAccountName | default "service-account")) }} apiVersion: v1 kind: ServiceAccount metadata: labels: app.kubernetes.io/instance: instancename name: {{ .Values.serviceAccountName | default "service-account" }} namespace: {{ .Release.Namespace }} {{- end }} 

Run helm install 
Then once the pod is up and running do helm upgrade

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T12:52:44Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
wsl
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                          OSArchitecture  Version
19045        Microsoft Windows 10 Enterprise  64-bit          10.0.19045

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/kind support

Is this a helm issue? If this is a kuberentes issue, the issue should be reproduced by kube alone, and the current description does not prove it is a kube bug.

**Comment by TahjidAshfaque** [comment]
Thank you, this was a helm issue and we have found the solution.

**Comment by Shubham82** [comment]
Thanks @TahjidAshfaque for the confirmation.

Closing this issue as it is related to the helm, not k8s.

/close
