### ISSUE TITLE
k8s机器每次开机，kubelet服务都是失败状态，也设置了开机自启服务的，详情见下图

### ISSUE THREAD

**Issue by pgin1234** [kubernetes/kubernetes#118607]
### What happened?

-- Logs begin at 日 2023-06-11 11:33:35 CST, end at 日 2023-06-11 12:45:21 CST. --
6月 11 11:36:26 master1 systemd[1]: Dependency failed for Kubernetes Kubelet.                    #这是kubelet日志错误信息
-- Subject: Unit kubelet.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit kubelet.service has failed.
-- 
-- The result is dependency.
6月 11 11:36:26 master1 systemd[1]: Job kubelet.service/start failed with result 'dependency'.
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]# kubectl get nodes
NAME      STATUS     ROLES    AGE   VERSION
master1   NotReady   <none>   34h   v1.27.2
master2   NotReady   <none>   34h   v1.27.2
master3   Ready      <none>   34h   v1.27.2
node1     Ready      <none>   34h   v1.27.2
node2     Ready      <none>   34h   v1.27.2
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://github.com/kubernetes/kubernetes

6月 11 11:36:26 master1 systemd[1]: Dependency failed for Kubernetes Kubelet.                  #这是kubelet日志错误信息
6月 11 11:36:26 master1 systemd[1]: Job kubelet.service/start failed with result 'dependency'.
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]# 
[root@master1 ~]#

### What did you expect to happen?

不要每次开机，kubelet服务都是失败状态

### How can we reproduce it (as minimally and precisely as possible)?

看看怎么优化

### Anything else we need to know?

无

### Kubernetes version

[root@master1 ~]# kubectl get nodes
NAME      STATUS     ROLES    AGE   VERSION
master1   NotReady   <none>   34h   v1.27.2
master2   NotReady   <none>   34h   v1.27.2
master3   Ready      <none>   34h   v1.27.2
node1     Ready      <none>   34h   v1.27.2
node2     Ready      <none>   34h   v1.27.2
[root@master1 ~]#

版本是1.27.2

### Cloud provider

<details>

</details>

### OS version

centos7.9

### Install tools

二进制安装的

### Container runtime (CRI) and version (if applicable)

containerd

**Comment by kkkkun** [comment]
Firstly, you should use English.
And then,  the issue already is tracing by https://github.com/kubernetes/kubernetes/issues/117589

**Comment by pgin1234** [comment]
> 在这个问题上没有签名标签。请使用以下命令之一添加适当的标签：
> 
> * `/sig <group-name>`
> * `/wg <group-name>`
> * `/committee <group-name>`
> 
> 请参阅[组列表](https://git.k8s.io/community/sig-list.md)以获取可用的 SIG、工作组和委员会的列表。

请问，具体怎么操作恢复？使kubelet开机正常启动？

**Comment by wenzhaojie** [comment]
@pgin1234 Is this problem solved now, I can still reproduce this problem in the official version of 1.28
