### ISSUE TITLE
Allow nodes to declare failure probability/SLA

### ISSUE THREAD

**Issue by helayoty** [kubernetes/kubernetes#118669]
### What would you like to be added?

- Add a configuration option to the nodes to declare a failure probability (SLA).
- Allow the workloads to configure the minimum failure probability they need to be able to run. 

/sig scheduling

### Why is this needed?

The idea started to form while implementing the placement-policy schedule plugin ([repo](https://github.com/Azure/placement-policy-scheduler-plugins)) and the need to run on mixed nodes with different availability. Introducing the ability to configure the SLA on nodes and some workloads APIs can lead to better resource management and stabilization.

// @khenidak

**Comment by soltysh** [comment]
@alculquicondor @mimowo since this is somewhat related to batch wg

**Comment by sftim** [comment]
This'd also be relevant to SIG Autoscaling (if a workload requires a low-failure-probability node, don't provision a node with a higher probability of failure.

**Comment by alculquicondor** [comment]
immediate reaction: why not build a controller that adds taints based on the status of a node?

Maybe we require an enhancement to the tolerations API to support comparison operators (like `<` or `>`).

**Comment by helayoty** [comment]
fyi @kubernetes/sig-autoscaling-leads , @kubernetes/sig-scheduling-leads , @kubernetes/sig-node-leads , @kubernetes/sig-architecture-leads, we are discussing this topic in the upcoming `sig-scheduling` [meeting](https://www.google.com/url?q=https://docs.google.com/document/d/13mwye7nvrmV11q9_Eg77z-1w3X7Q1GTbslpml4J7F3A/edit&sa=D&source=calendar&usd=2&usg=AOvVaw06NLmPh3bexZFhSUaumHxt), Thursday, October 5th, 10 am PST.

// @khenidak

**Comment by helayoty** [comment]
> fyi [@kubernetes/sig-autoscaling-leads](https://github.com/orgs/kubernetes/teams/sig-autoscaling-leads) , [@kubernetes/sig-scheduling-leads](https://github.com/orgs/kubernetes/teams/sig-scheduling-leads) , [@kubernetes/sig-node-leads](https://github.com/orgs/kubernetes/teams/sig-node-leads) , [@kubernetes/sig-architecture-leads](https://github.com/orgs/kubernetes/teams/sig-architecture-leads), we are discussing this topic in the upcoming `sig-scheduling` [meeting](https://www.google.com/url?q=https://docs.google.com/document/d/13mwye7nvrmV11q9_Eg77z-1w3X7Q1GTbslpml4J7F3A/edit&sa=D&source=calendar&usd=2&usg=AOvVaw06NLmPh3bexZFhSUaumHxt), Thursday, October 5th, 10 am PST.
> 
> // [@khenidak](https://github.com/khenidak)

@alculquicondor @kubernetes/sig-scheduling-misc 

Based on the [conversation](https://youtu.be/KHb8Mi8FDmA?si=xK8uxTtH29JIodyd&t=597), here is the summary of the investigation on why NodeAffinity isn’t sufficient for this use‑case:

For the “node SLA / failure‑probability” use‑case, NodeAffinity can express minimum or exact SLA thresholds via label comparisons, but it’s not sufficient for the operational goals here:
- Affinity is per‑pod and doesn’t provide a safe cluster‑default to keep most workloads off low‑SLA nodes; taints do.
- Affinity has no eviction semantics when node conditions change (e.g., spot/preemptible reclamation or SLA downgrade). Taints with NoExecute can evict pods that shouldn’t remain.
- Taints centralize policy on the node, and workloads opt‑in with a toleration — consistent with other reliability/risk taints.

From a scheduling perspective, adding comparison operators (e.g., Lt, Le, Eq, Ge, Gt) to Tolerations only changes the match logic in the existing TaintToleration filter; it does not alter the scheduling algorithm or control flow.

https://github.com/kubernetes/kubernetes/blob/f003bd2de38227820431bae632ade3111dbb1072/pkg/scheduler/framework/plugins/tainttoleration/taint_toleration.go#L114-L120

Therefore, I propose a feature to extend Toleration operators to support numeric comparisons so pods can opt‑in to nodes based on SLA values published as taints (e.g., node.kubernetes.io/sla=950). This keeps the safety model of taints while enabling threshold‑based placement.
The proposed enhancement would only require updating the matching logic in `FindMatchingUntoleratedTaint` to support numeric comparisons, without changing the broader scheduling architecture.

https://github.com/kubernetes/kubernetes/blob/f003bd2de38227820431bae632ade3111dbb1072/staging/src/k8s.io/component-helpers/scheduling/corev1/helpers.go#L74-L86

**Comment by helayoty** [comment]
> immediate reaction: why not build a controller that adds taints based on the status of a node?
> 
> Maybe we require an enhancement to the tolerations API to support comparison operators (like `<` or `>`).

A KEP has been drafted to address this issue here:
https://github.com/kubernetes/enhancements/pull/5473
