### ISSUE TITLE
wait.PollUntilContextTimeout with immediate=true does not invoke condition function at least once

### ISSUE THREAD

**Issue by tatsuhiro-t** [kubernetes/kubernetes#118671]
### What happened?

Calling wait.PollUntilContextTimeout with immediate=true does not invoke the passed condition function if context has already been cancelled.

### What did you expect to happen?

wait.PollUntilContextTimeout with immediate=true should invoke the passed condition function at least once even if context has already been cancelled as wait.PollUntilContextCancel documentation says:

> If immediate is true, condition will be invoked before waiting and guarantees that condition is invoked at least once, regardless of whether the context has been cancelled.

Note that wait.PollUntilContextTimeout wraps wait.PollUntilContextCancel, so the above should be applied to wait.PollUntilContextTimeout as well.

### How can we reproduce it (as minimally and precisely as possible)?

```go
package main

import (
        "context"
        "time"

        "k8s.io/apimachinery/pkg/util/wait"
)

func main() {
        err := wait.PollUntilContextTimeout(context.Background(), time.Second, 0, true, func(context.Context) (bool, error) {
                return true, nil
        })
        if err != nil {
                panic(err)
        }
}
```

This program panics because context ctx.Err is checked before invoking the passed function.

### Anything else we need to know?

The deprecated wait.PollImmediateWithContext does not have this kind of issue.
If wait.PollUntilContextTimeout is the replacement of wait.PollImmediateWithContext, it should exhibit the same behavior.

### Kubernetes version

k8s v1.27.2
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tatsuhiro-t** [comment]
Test_loopConditionUntilContext_semantic also has an issue that immediate and sliding are not tested as expected.
immediate and sliding are loop variable, but they are not used in the test.  The ones that are used are in testcase struct which are always false.

**Comment by aojea** [comment]
ok, it seems this would do it https://github.com/kubernetes/kubernetes/pull/118686
