### ISSUE TITLE
pod/container is "Exited" state, still corresponding pause container holding the IP address.

### ISSUE THREAD

**Issue by HalaharviPedda** [kubernetes/kubernetes#118684]
### What happened?

We can see pause container of the Exited pod still holding Ip adress.

$:~> sudo crictl ps -a | grep ft-

7b59ba5f78776       2a9799d12b5b7       4 weeks ago         **Exited**              bind-named                                 0                   **6fb4e29f02f46**       ft-675bc886f6-fcbnl

a4a4ec154a90b       2a9799d12b5b7       4 weeks ago         **Exited**              ft                                         0                   **6fb4e29f02f46**       ft-675bc886f6-fcbnl

d65c689c545da       2a9799d12b5b7       4 weeks ago         **Exited**              bind-configuration                         0                   **6fb4e29f02f46**       ft-675bc886f6-fcbnl
$:~>

 
$:~> ps -ef | grep **6fb4e29f02f46**

root      79792      1  0 May08 ?        00:27:45 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 
6fb4e29f02f46e1f848b8f1bfb8f5a04a3f883bd7f11acf7e81d049d22a8e946 -address /run/containerd/containerd.sock

eccd     133978 114054  0 15:05 pts/1    00:00:00 grep --color=auto 6fb4e29f02f46
$:~>

$:~> ps -ef | grep 79792
eccd       2120 114054  0 15:06 pts/1    00:00:00 grep --color=auto 79792

root      79792      1  0 May08 ?        00:27:46 /usr/local/bin/containerd-shim-runc-v2 -namespace k8s.io -id 6fb4e29f02f46e1f848b8f1bfb8f5a04a3f883bd7f11acf7e81d049d22a8e946 -address /run/containerd/containerd.sock

65535     **79828**  79792  0 May08 ?        00:00:00 /pause
$:~>

$:~> sudo nsenter -t **79828** -n
Directory: /home/eccd
Thu Jun  8 15:08:01 EEST 2023
control-plane-fijodellr640-bmcn-ci002:/home/eccd #
control-plane-fijodellr640-bmcn-ci002:/home/eccd # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
6: eth1@if84717: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default
    link/ether 0a:58:0a:11:0d:67 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet **10.17.13.103/24** brd 10.17.13.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 2001:1b70:8298:2ba5:858:aff:fe11:d67/64 scope global dynamic mngtmpaddr
       valid_lft 2591994sec preferred_lft 604794sec
    inet6 fe80::e8c2:43ff:fe93:755e/64 scope link
       valid_lft forever preferred_lft forever
7: adcAccess2@if84718: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default
    link/ether 0a:58:0a:11:0d:68 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet **10.17.13.104/24** brd 10.17.13.255 scope global adcAccess2
       valid_lft forever preferred_lft forever
    inet6 2001:1b70:8298:2ba5:858:aff:fe11:d68/64 scope global dynamic mngtmpaddr
       valid_lft 2591994sec preferred_lft 604794sec
    inet6 fe80::464:52ff:fe1f:90e3/64 scope link
       valid_lft forever preferred_lft forever

### What did you expect to happen?

When POD exited , expect to clean all the containers including pause ( so that network namespace will be released intern Ip address)

### How can we reproduce it (as minimally and precisely as possible)?

No exact steps , 
~30 automatic jobs running three times per hour, running some traffic and deleting the environment. Each environment consists of 11pods. So a few times per hours there is a burst of installing a lot of pods and after some time the pods are deleted

### Kubernetes version

<details>
k8s 1.25

### Cloud provider

No

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
For IP gc, I would look into the CNI first.

**Comment by HalaharviPedda** [comment]
> 

Hi @aojea  , Normal k8s only . Yes POD is having secondary network and it has 2 interfaces.

**Comment by aojea** [comment]
> > 
> 
> Hi @aojea , Normal k8s only . Yes POD is having secondary network and it has 2 interfaces.

if it has 2 interfaces this has to be configured by multus or some specific cni, you should report this problem on the corresponding CNI project

/close
