### ISSUE TITLE
[kube-proxy/ipvs] Make a scheduler configurable for each Service

### ISSUE THREAD

**Issue by vasiliev-a-a** [kubernetes/kubernetes#118784]
### What would you like to be added?

Hello.
I think in would be useful to introduce an annotation for the Service resource, which will make possible to override the IPVS scheduler configured into kube-proxy configuration for individual Service resource.
Something like:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    <pick-the-name>: rr | sh | mh | ...
spec:
  ...
```

### Why is this needed?

At the moment every Virtual Server is created with a scheduler defined in the kube-proxy configuration. But there are different application with different needs.

PS. Sorry for my English, able to read\understand but rarely speaking\writing.

**Comment by aojea** [comment]
I do not think we want to leak these details to the Service object, there are multiple implementations of Services and this will be hard to scale.

**Comment by vasiliev-a-a** [comment]
> I do not think we want to leak these details to the Service object, there are multiple implementations of Services and this will be hard to scale.

I assume that the annotation will be respected only by the kube-proxy and only if it runs in IPVS mode. 
As i see it, this is the same idea as for Ingresses - there are annotations that are specific to a particular implementation.

**Comment by aojea** [comment]
> I assume that the annotation will be respected only by the kube-proxy and only if it runs in IPVS mode.

oh, I see, so you want to modify the ipvs kube-proxy implementation to read this special annotation , got it.

just curious, is there any strong use case to have different algorithm per Service? or is just nice to have

**Comment by vasiliev-a-a** [comment]
> just curious, is there any strong use case to have different algorithm per Service? or is just nice to have

As i mentioned, there are different services with different needs.

For example, an FTP server in passive mode: the only way to ensure that control and data streams will hit the same server is to use 'sh' algorithm (since kube-proxy does not implement 'fw' Virtual Servers). Same with SIP session and RTP streams.

At the same time, the RESTful services, or DNS servers work fine with 'rr' or 'mh' algorithms.

**Comment by aojea** [comment]
> For example, an FTP server in passive mode: the only way to ensure that control and data streams will hit the same server is to use 'sh' algorithm (since kube-proxy does not implement 'fw' Virtual Servers). Same with SIP session and RTP stream

ok, so the problem you are trying to solve is the stickiness, you know that you can set  `service.spec.sessionAffinity` to "ClientIP", right?

**Comment by vasiliev-a-a** [comment]
> ok, so the problem you are trying to solve is the stickiness, you know that you can set `service.spec.sessionAffinity` to "ClientIP", right?

Let me show an example. Suppose, i have a multiport Service with three backends like this:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  externalTrafficPolicy: Local
  ports:
  - name: port1
    port: 8181
    targetPort: http
  - name: port2
    port: 8182
    targetPort: http
  - name: port3
    port: 8183
    targetPort: http
  - name: port4
    port: 8184
    targetPort: http
  - name: port5
    port: 8185
    targetPort: http
  selector:
    application: http-echo
    enabled: "true"
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
```
kube-proxy in IPVS mode and 'mh' scheduler implements it as follows
```
TCP  10.10.10.178:8181 mh (mh-port) persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8182 mh (mh-port) persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8183 mh (mh-port) persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8184 mh (mh-port) persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8185 mh (mh-port) persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
```
i.e. kube-proxy creates a Virtual Server per single port, and maintains individual bucket for hashing.

So when i run on a client `for i in 8181 8182 8183 8184 8185 ; do curl http://10.10.10.178:$i | grep http-echo- ; done`
it got hashed to different backends:
```
...
TCP 04:52  ASSURED     172.16.1.213:0     10.10.10.178:8185  10.10.3.220:8080
TCP 04:52  ASSURED     172.16.1.213:0     10.10.10.178:8184  10.10.0.89:8080
TCP 04:52  ASSURED     172.16.1.213:0     10.10.10.178:8183  10.10.3.220:8080
TCP 04:51  ASSURED     172.16.1.213:0     10.10.10.178:8182  10.10.0.89:8080
TCP 04:51  ASSURED     172.16.1.213:0     10.10.10.178:8181  10.10.3.184:8080
...
```
of course these calculations are persistent individually. But my goal is to forward a single client to the same backend - this can be achieved only with 'sh' algorithm.
```
TCP  10.10.10.178:8181 sh persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8182 sh persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8183 sh persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8184 sh persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
TCP  10.10.10.178:8185 sh persistent 300
  -> 10.10.0.89:8080              Masq    1      0          0
  -> 10.10.3.184:8080             Masq    1      0          0
  -> 10.10.3.220:8080             Masq    1      0          0
```
```
...
TCP 03:57  ASSURED     172.16.1.213:0     10.10.10.178:8185  10.10.3.220:8080
TCP 03:57  ASSURED     172.16.1.213:0     10.10.10.178:8184  10.10.3.220:8080
TCP 03:57  ASSURED     172.16.1.213:0     10.10.10.178:8183  10.10.3.220:8080
TCP 03:57  ASSURED     172.16.1.213:0     10.10.10.178:8182  10.10.3.220:8080
TCP 03:57  ASSURED     172.16.1.213:0     10.10.10.178:8181  10.10.3.220:8080
...
```

I would be nice to have an option to pick the right tool - for some Service stickiness, for others more even distribution.

**Comment by aojea** [comment]
I see, so this was discussed in several places:

This for multiport affintiy https://github.com/kubernetes/kubernetes/issues/103000
This for implementing forwarding multiple port ranges to backends https://github.com/kubernetes/kubernetes/issues/23864

Ideally we should have a good general answer for this since is a recurring request, but unfortunately we don't have it.

For the IPVS specific implementation, we are trying to not have different behaviors on the proxies in-tree to make it easier to maintain, regarding the ipvs proxy, it lacks of maintainers for a long time and AFAIK only @uablrek is keeping it healthy these days. Adding new annotations. and supporting specific annotations sounds a bit complicated in current state

**Comment by uablrek** [comment]
### Historic notes

This has been proposed several times before, i.e. when proxy-mode=ipvs was [presented in a blog post](https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/)

> In the future, we can implement Service specific scheduler (potentially via annotation), which has higher priority and overwrites the value.

First proposed in https://github.com/kubernetes/kubernetes/issues/58329 (2018), then again (by me) in https://github.com/kubernetes/kubernetes/issues/75502 (2019). Also implemented twice in https://github.com/kubernetes/kubernetes/pull/75556 and https://github.com/kubernetes/kubernetes/pull/77006.

The final verdict in https://github.com/kubernetes/kubernetes/issues/75502#issuecomment-536249504:

> Conclusion; To ensure that the needed functions is supported (e.g modules loaded) is too complex and the added value is to small to make it worth it.

In the current ipvs proxier any scheduler can be specified and a [validated with a test](https://github.com/kubernetes/kubernetes/pull/114878) (no module checks!), but to make that test for individual services may be a bit tricky. Please read the comments in https://github.com/kubernetes/kubernetes/pull/75556 which has a lot of arguments that are still valid, and a few [gotcha's](https://github.com/kubernetes/kubernetes/pull/75556#issuecomment-519995016).

.

**Comment by vasiliev-a-a** [comment]
Well, since there are many difficulties, i leave it up to maintainers to decide whether to keep this topic or close.
I will give a tray to the kube-router project. It seems that their implementation supports per Service scheduler.
Thanks.

**Comment by uablrek** [comment]
This has been discussed, and rejected before (https://github.com/kubernetes/kubernetes/issues/75502#issuecomment-536249504). There is a strong will in sig/network to _not_ extend the functionality of K8s services further, and there is also a proposal to replace the iptables _and_ ipvs proxiers with a more modern [nftables based proxier](https://github.com/kubernetes/enhancements/pull/3824).

Because of this I close this issue. If sig/network would have a different opinion, please reopen. This is not hard to implement.

/close

As a side note: For external traffic there is a shift from services towards the [Gateway API](https://gateway-api.sigs.k8s.io/). It may be possible to use it to support different schedulers for ipvs load-balancing.
