### ISSUE TITLE
Not able join worker node to master node upgraded from v1.25.9 to v1.27.1

### ISSUE THREAD

**Issue by MVD92** [kubernetes/kubernetes#118726]
### What happened?
Recently, I have upgraded cluster from v1.25.9 to v1.27.1 with CRI-O. While joining new node to M1 using kubeadm, Kubelet.crt is not getting generated which in turn is resulting in auto-restart of kubelet service and the node is not able to join the cluster.

### The error is as follows:
Unfortunately, an error has occurred:
timed out waiting for the condition

This error is likely caused by:
- The kubelet is not running
- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
- 'systemctl status kubelet'
- 'journalctl -xeu kubelet'

I have set systemd cgroup in both config.yaml & crio.conf.

### OS version:
CentOS 7

**Comment by aojea** [comment]
>  While joining new node to M1

this description is not giving much information if this is a bug or a configuration problem, also it not clear that "node to M1" means

If you feel there is a bug please try to diagnose better the problem and indicate the logs and components that may be causing the bug.

If this is a support question then is better to close the issue and use other channels

/kind support

**Comment by MVD92** [comment]
> > While joining new node to M1
> 
> this description is not giving much information if this is a bug or a configuration problem, also it not clear that "node to M1" means
> 
> If you feel there is a bug please try to diagnose better the problem and indicate the logs and components that may be causing the bug.
> 
> If this is a support question then is better to close the issue and use other channels
> 
> /kind support
Sorry for lack of information, it would be better if you please ask me what details do you need & by "node to M1" I meant joining worker node to master 1 node, I have three master nodes in the cluster. I am trying to join first worker node, I have installed necessary crio & k8s binaries.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
