### ISSUE TITLE
client-go leader election can not be cancel

### ISSUE THREAD

**Issue by Bryce-huang** [kubernetes/kubernetes#118790]
### What happened?

The leader election of client-go cannot be terminated, even if I use ctx.done() or the cancel function in context.WithCancel(context.Background()), the running elector.Run(ctx) will never be stopped

### What did you expect to happen?

After I use ctx.Done() or the cancel function, the elected Run() should exit

### How can we reproduce it (as minimally and precisely as possible)?

this is my code:

```go
package main

import (
	"context"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/tools/leaderelection"
	"k8s.io/client-go/tools/leaderelection/resourcelock"
	"k8s.io/client-go/tools/record"
	"log"
	"time"
)

func main() {

	conf := "/home/bryce/.kube/config"

	config, err := clientcmd.BuildConfigFromFlags("", conf)
	if err != nil {
		log.Fatal(err)
	}

	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		log.Fatal(err)
	}

	lock, err := resourcelock.New(resourcelock.ConfigMapsLeasesResourceLock, "default", "xxxxxx", clientset.CoreV1(), clientset.CoordinationV1(), resourcelock.ResourceLockConfig{
		Identity: "xxxx",
		EventRecorder: &record.FakeRecorder{
			Events:        make(chan string),
			IncludeObject: false,
		},
	})
	if err != nil {
		log.Fatal(err)
	}
	elector, err := leaderelection.NewLeaderElector(leaderelection.LeaderElectionConfig{
		Lock:          lock,
		LeaseDuration: time.Second * 30,
		RenewDeadline: time.Second * 20,
		RetryPeriod:   time.Second * 5,
		Callbacks: leaderelection.LeaderCallbacks{
			OnStartedLeading: func(ctx context.Context) {
				log.Println("gain")
			},
			OnStoppedLeading: func() {
				log.Println("loss")

			},
			OnNewLeader: func(identity string) {
				if identity == "xxxx" {
					log.Println("no change")

				} else {
					log.Println("change the leader")
				}
			},
		},
		WatchDog:        nil,
		ReleaseOnCancel: false,
		Name:            "my-lock",
	})
	if err != nil {
		log.Fatal(err)
	}
	ctx, cancelFunc := context.WithCancel(context.Background())
	go func(ctx2 context.Context) {
		elector.Run(ctx2)
		log.Println("already end")

	}(ctx)

	time.Sleep(10 * time.Second)

	ctx.Done()
	cancelFunc()
	log.Println("already send")

	time.Sleep(time.Minute)
}

```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:03:40Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
kind with docker 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux bryce-KLVL-WXX9 5.19.0-45-generic #46~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Bryce-huang** [comment]
resourcelock.New will cause this issue

**Comment by mooyy123** [comment]
> resourceslock.New（ConfigMapsLeasesResourceLock ）会导致这个问题

remove `ctx.Done()`

**Comment by hiroyaonoe** [comment]
I think the reason is that the context is not propagated here.
https://github.com/kubernetes/kubernetes/blob/e298e92115439916320eed0dee26b7c4d8d9a5f6/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L307

/assign @hiroyaonoe

**Comment by aojea** [comment]
> I think the reason is that the context is not propagated here.

if you cancel that operation it will be worse, because the leader will not be able to release the Lease and the others will have to wait until it expires

https://github.com/kubernetes/kubernetes/blob/e298e92115439916320eed0dee26b7c4d8d9a5f6/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L295

**Comment by hiroyaonoe** [comment]
That is true. My apologies.

I reproduced this issue in a kind environment.
When I ran the above code, indeed, elector.Run(ctx) did not terminate.
But the cause is FakeRecorder.Events does not have a buffer and RecordEvent is blocking in the following part.
https://github.com/kubernetes/kubernetes/blob/63351cce1c1099c64c6c55d540b1e65e947632ad/staging/src/k8s.io/client-go/tools/leaderelection/leaderelection.go#L258

In fact, when I changed the code as follows, elector.Run(ctx) terminated.

before
```go
	lock, err := resourcelock.New(resourcelock.ConfigMapsLeasesResourceLock, "default", "xxxxxx", clientset.CoreV1(), clientset.CoordinationV1(), resourcelock.ResourceLockConfig{
		Identity: "xxxx",
		EventRecorder: &record.FakeRecorder{
			Events:        make(chan string), 
			IncludeObject: false,
		},
	})
```

after
```go
	lock, err := resourcelock.New(resourcelock.ConfigMapsLeasesResourceLock, "default", "xxxxxx", clientset.CoreV1(), clientset.CoordinationV1(), resourcelock.ResourceLockConfig{
		Identity: "xxxx",
		EventRecorder: &record.FakeRecorder{
			Events:        make(chan string, 100), // buffers
			IncludeObject: false,
		},
	})
```

To address this issue, we need to propagate the context to FakeRecorder, but FakeRecorder is simply for testing. Should we modify it?

**Comment by BenTheElder** [comment]
@aojea WDYT re: https://github.com/kubernetes/kubernetes/issues/118790#issuecomment-1680911302

**Comment by aojea** [comment]
> To address this issue, we need to propagate the context to FakeRecorder, but FakeRecorder is simply for testing. Should we modify it?

FakeRecorder is for testing, does this have with the normal event recorder?

**Comment by hiroyaonoe** [comment]
The normal event recorder seems to drop events when ctx is canceled and the event broadcaster is shutdowned.
https://github.com/kubernetes/client-go/blob/51f5488cb9457b74409d97a65381047b6a9e7447/tools/record/event.go#L457-L462
This issue is related only to FakeRecorder.

**Comment by aojea** [comment]
> This issue is related only to FakeRecorder.

do we need to support these for tests? any use case? otherwise we should close

**Comment by hiroyaonoe** [comment]
I don't think we need to support this since we can avoid it by just adding channel buffers or popping events from channel.

**Comment by aojea** [comment]
> I don't think we need to support this since we can avoid it by just adding channel buffers or popping events from channel.

/close

Thanks for the discussion
