### ISSUE TITLE
Bump cadvisor to include https://github.com/google/cadvisor/pull/3301

### ISSUE THREAD

**Issue by harche** [kubernetes/kubernetes#118796]
### What happened?

Kubernetes needs to be updated with the cadvisor version that has the fix for https://github.com/google/cadvisor/pull/3301

### What did you expect to happen?

cadvisor with the fix https://github.com/google/cadvisor/pull/3301 is vendored in

### How can we reproduce it (as minimally and precisely as possible)?

N/A

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by carlory** [comment]
@harche Is it fixed?

**Comment by harche** [comment]
Yes, k8s has been bumped with the required cadvisor release.
