### ISSUE TITLE
Restore Kubernetes API service endpoint during HA rolling restarts

### ISSUE THREAD

**Issue by rtheis** [kubernetes/kubernetes#118777]
### What happened?

I think that https://github.com/kubernetes/kubernetes/issues/115804 via https://github.com/kubernetes/kubernetes/pull/116685 have introduced a regression for HA Kubernetes API server configurations behind a proxy and/or load balancer.  Such configurations may only have a single Kubernetes API server endpoint that should not be removed during a rolling restart of the Kubernetes API server.

**Example:**
```
$  kubectl get endpoints kubernetes --no-headers
kubernetes   172.20.0.1:2040   48m
```

### What did you expect to happen?

`kubectl get endpoints kubernetes --no-headers` will remain unchanged throughout the HA rolling restart of the Kubernetes API server.

### How can we reproduce it (as minimally and precisely as possible)?

Run the following script during an HA rolling restart of the Kubernetes API server:

```
while true; do date && kubectl get endpoints kubernetes --no-headers; sleep 1; done
```

You will see `kubectl get endpoints kubernetes --no-headers` return `kubernetes   <none>` several times during this rollout.

### Anything else we need to know?

Nothing

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-alpha.2+IKS", GitCommit:"1552e53a83745274f7db4b12fc539bd09ed88b09", GitTreeState:"clean", BuildDate:"2023-06-14T21:47:51Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
IBM
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
[IBM Cloud Kubernetes Service](https://cloud.ibm.com/docs/containers)
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by jiahuif** [comment]
/assign @aojea 
/assign @wojtek-t 
Could you take a look at this? Thank you.
/triage accepted

**Comment by aojea** [comment]
>  Such configurations may only have a single Kubernetes API server endpoint that should not be removed during a rolling restart of the Kubernetes API server.

The endpoint should only be present when the apiserver is ready to serve traffic, the HA setup, assuming a loadbalancer,  should poll the apiserver /healthz endpoint before sending traffic to the apiserver.

The problem is that if the endpoint exist but there is no apiserver it will be blackholing traffic (that was the bug)

Is not the problem here that the rolling update is not well synchronized, leaving a time window where there is no apiserver ready ?

tagging @deads2k as he is very experienced in this area too

**Comment by rtheis** [comment]
@aojea from an HA availability perspective, I did not see any problems that would justify removing the endpoint.

**Comment by aojea** [comment]
>  I did not see any problems that would justify removing the endpoint.

dropping traffic is not a problem?

https://github.com/kubernetes/kubernetes/issues/115804

> If the IP isn't removed from the k8s endpoints object, clients (using in-cluster API mode) will try to continue talking/connecting to that instance even after the apiserver is dead. There are at least two issues with this:

> Causes confusing i/o timeout and connection refused errors for clients, instead of a cleaner no route to host error

**Comment by rtheis** [comment]
@aojea dropping traffic is a problem but our Kubernetes API server configuration is HA and traffic is not being dropped.  The problem that we are seeing now is the in cluster applications using the kubernetes service will hit errors during the rollout because the endpoint is being removed 3 times during the rollout (once per API server).  There's really no reason to remove it.

**Comment by rtheis** [comment]
@aojea I repeated my test on 1.26 where the endpoint is not removed, and traffic is not dropped for the kubernetes service during an HA rolling restart.

**Comment by rtheis** [comment]
Hi folks, are there any updates on this issue?

**Comment by aojea** [comment]
the apiserver, when shutting down should remove its endpoint and add it back once it is ready again after restart, that is the expected behavior

**Comment by rtheis** [comment]
@aojea I'm not sure how to interpret your response with respect to this issue.  The behavior changed for the worse for the use case that I described.  Is there something that we should be doing to handle this change for our use case?

**Comment by aojea** [comment]
> Is there something that we should be doing to handle this change for our use case?

How do you implement ha? Haproxy or some sort of load balancer?

**Comment by aojea** [comment]
The point is that anything that implements HA in front of the apiservers , haproxy, routing anycast, keepalived + whatever, ... has to take into consideration the /healthz endpoint of the corresponding apiserver/backend, if the backend is not ready/healthy then the HA implementation must not forward traffic to it

**Comment by rtheis** [comment]
@aojea agreed and we do that.  We use haproxy in conjunction with other tools to manage this.  Having Kubernetes remove the endpoint impacts our design and would appreciate at least an option to maintain the original behavior.

**Comment by aojea** [comment]
> We use haproxy in conjunction with other tools to manage this. Having Kubernetes remove the endpoint impacts our design and would appreciate at least an option to maintain the original behavior

but the endpoint is only removed when the healthz endpoint does not reply, so your haproxy should be removing it out of rotation and not forwarding traffic to it, that is the part I do not understand, sending traffic to that endpoint is invalid because that backend is no longer present

**Comment by aojea** [comment]
do they have something like this? (I copy pasted from internet, just highlight they need to set the health checks)

```
backend apiserver
  option httpchk

  http-check connect
  http-check send meth GET uri /health
  http-check expect status 200

  server server1 endpoint1:443 check
  server server2 endpoint2:443 check
  server server3 endpoint3:443 check
```

**Comment by aojea** [comment]
wait 

>. this still happens but we now also temporarily lose the endpoint thus preventing in cluster components from reaching haproxy

> in-cluster component ---> default/kubernetes service --->  haproxy 172.20.0.1:2040 

this is confusing , how do you inject service -> haproxy in between? it is service -> endpoints

**Comment by bradbehle** [comment]
Yes, the `default/kubernetes` clusterIP service only endpoint is 172.20.0.1:2040.  And that IP and port 2040 is where our local haproxy is listening on each worker (we implement that as a static pod on each worker).  Here's the actual output from a cluster:

[classic-iks-cluster-output.txt](https://github.com/kubernetes/kubernetes/files/12285060/classic-iks-cluster-output.txt)

For the sake of this discussion, I don't think the details of what the haproxy (pod) on each worker is actually pointing to, but if it is needed I can get into more details.  The haproxy configuration does use a health check so it only sends traffic to the backend apiserver instances (pods) that are responding, but I think that also is besides the point.  The point I think is that we set the kubernetes clusterIP service to point to a single endpoint IP:Port:

```
bradbehle@Brads-MacBook-Pro ~ % kubectl get services
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   172.21.0.1   <none>        443/TCP   26m
bradbehle@Brads-MacBook-Pro ~ % kubectl get endpoints kubernetes -o wide
NAME         ENDPOINTS         AGE
kubernetes   172.20.0.1:2040   25m
bradbehle@Brads-MacBook-Pro ~ % 
```

and that endpoint:port takes care of making sure to only send traffic to apiservers that are up and running.  This was all working fine in k8s 1.27 and earlier.  But now in k8s 1.28, it seems that when only one of the three apiserver instances for this cluster is restarted, that endpoint is (temporarily) removed from the service, which prevents the service from routing to the endpoint which is still able to route traffic to the other two apiserver instances.  That is a serious problem for us because it prevents components in the cluster from connecting to our apiserver even when it has 2 valid instances that are running and can be health checked successfully.

**Comment by aojea** [comment]
who creates this endpoint `endpoint is 172.20.0.1:2040` ?

The apiserver has an endpoint reconciler that is configurable, by default is the `Lease` controller
```
--endpoint-reconciler-type string     Default: "lease"
```

this reconciler updates the Endpoint object with the IPs of each apiserver, this does not seems to be your use case, so you may be creating it yourself?

if that is the case you have to use `--endpoint-reconciler-type none`

**Comment by rtheis** [comment]
@aojea we have `--endpoint-reconciler-type lease` which I think means all three Kubernetes API servers are creating the same endpoint.  That would explain why I see the endpoint get recreated soon after one of the API servers deletes it.  Given this, it sounds like we should be using `--endpoint-reconciler-type none` and creating the endpoint ourselves.  I'll give this a try.

**Comment by rtheis** [comment]
@aojea after changing our cluster deployment configuration to use `--endpoint-reconciler-type none` and to create the endpoint and endpointslice ourselves, we no longer hit the reported issue.  Thank you for your assistance.
