### ISSUE TITLE
topologySpreadConstraint spanning multiple namespaces

### ISSUE THREAD

**Issue by dene14** [kubernetes/kubernetes#118749]
### What would you like to be added?

I desperately need a way to spread similar prods from different namespaces evenly across clusters nodes.

Right now official docummentation for topologySpreadConstraints explicitly states this:
> Only the Pods holding the same namespace as the incoming Pod can be matching candidates.

I also taken into consideration cluster-wide topologySpreadConstraints, but they seems not covering my case as well, as pods should belong to the same controlling entity (Deployment, Statefulset, Service).

### Why is this needed?

I'm responsible for big enough cluster with hundreds instances of cloud native application that consists of 20+ microservices. Since application may spin up worker pods for data processing pod names are clashing quite often, that's why I have to use namespaces, easy garbage collecting upon removal is another reason.

Application is quite big, so we use resource overprovisioning quite heavily, however, when some nodes getting too many instances of a few specific microservice, it can be easily overloaded. Having global (as opposed to namespaced) topologySpreadConstraints would allow us to optimize capacity requirements a lot.

I'm happy to provide any additional information upon request. Also, any workaround for my use-case is extremely welcome.

Thanks!

**Comment by sftim** [comment]
Kubernetes has an extension point that may help: you can [write your own scheduler](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/), and you can either start from scratch or use the [extension points](https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/#extension-points) that the existing scheduler provides.

If you want this change to happen in-tree @dene14, you should add some context about why you recommend that approach.

To read more about real-world experience with a custom scheduler, visit https://kubernetes.io/blog/2020/12/21/writing-crl-scheduler/

**Comment by dene14** [comment]
@sftim I've describe the use case that I'm having, I don't quite understand what details are missing, could you please elaborate?

I've explored custom scheduler and scheduler extension plugins approach, it sounds like a huge overkill for what I'm trying to solve. topologySpreadConstraint has all the functionality needed, except it's namespaced.

**Comment by AxeZhan** [comment]
I think the key here is how can we define `similar pods` ? I don't think we can remove the ns constrain directly, but I think you can bring this to sig/scheduling slack channel to raise a discussion.

**Comment by sftim** [comment]
> @sftim I've describe the use case that I'm having, I don't quite understand what details are missing, could you please elaborate?

You can solve this by writing your own code; if just one person has this request, then we can keep Kubernetes simple by allowing that one person to solve it themselves (outside of Kubernetes). Why is this improvement important enough that the Kubernetes project should write that code and make it part of Kubernetes' core?

I know that _you_ are desperate to have this improvement made @dene14 - can you show that there are other people who also want this specific improvement?

**Comment by dougbyrne** [comment]
Hi, I usually refrain from posting a me-too, but the last comment is asking for examples of other interested parties.

For our use case, we are looking to balance instances of our application across AWS AZs. We run each instance of the app in its own namespace. We want to balance the usage of a few AZs primarily to avoid resource exhaustion in that AZ.

We are looking at other areas where this could be addressed, for example within karpenter. That said, we would use this feature if available.

**Comment by hiteshcj** [comment]
Hi,

Same ask and our use case is similar to @dougbyrne . Same application is deployed in multiple namespaces and we want to distribute PODs of high CPU consuming app to be distributed across available cluster nodes.

**Comment by lauraseidler** [comment]
Hi, 

I'll also add my 2ct here, we also have a couple of use cases for this:

- same as @hiteshcj, we deploy the same application to multiple namespaces, and would like to distribute pods of the same "component" even across namespaces
- in some cases, we want to do the opposite and _co-locate_ the same components across namespaces (e.g. because we know they use the same image that is expensive to pull, and pulling that image only on a few nodes as opposed to many nodes saves resources)
- ideally, we'd like to not mix spread constraints and (anti)affinities too much to reduce complexity, and we are currently stuck using (anti)affinities to realize the above use cases, as they support multiple namespaces

**Comment by sftim** [comment]
If folks want this, the best way to track that is to add a :+1: reaction to the issue description.

**Comment by ingvagabund** [comment]
The issue was closed due to inactivity. Is this something community is still interested in? There's over 20 thumps up. Would it make sense to reopen this?
