### ISSUE TITLE
use SnapshotSharedLister().NodeInfos().Get(name) in binding cycle may cause scheduler panic

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#118783]
### What happened?

scheduler panic when use SnapshotSharedLister().NodeInfos().Get in binding cycle

### What did you expect to happen?

not panic

### How can we reproduce it (as minimally and precisely as possible)?

- add a custom bind plugin, use SnapshotSharedLister().NodeInfos().Get(name) in its prebind or bind func.
- create some pods waiting to be scheduled
- do some node add、delete operation during pod scheduling

scheduler may panic cuased by concurrent map write and read

### Kubernetes version

<details>

```console
$ kubectl version
1.20
# paste output here
```

</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SataQiu** [comment]
https://github.com/kubernetes/kubernetes/blob/ba6d2674ca6b7b4992189bba1516062004f05ed3/pkg/scheduler/framework/interface.go#L601-L608


Given the above comments, I don't think you should use it in binding cycle.
