### ISSUE TITLE
Debug endpoint to dump currently executing requests

### ISSUE THREAD

**Issue by natherz97** [kubernetes/kubernetes#118746]
### What would you like to be added?

The currently available debug endpoints for APF are for dump_priority_levels, dump_queues, and dump_requests. These commands provide useful information primarily about the state of APF queues, including the the FlowDistinguisher, ArriveTime, UserName, Verb, and APIPath of requests waiting in queues. To help debug APF-related issues, it would be valuable to provide similar information about requests which have been dispatched by APF and are currently occupying 1 or more seats. The existing commands for dump_priority_levels and dump_queues give a count for the number of executing requests per PriorityLevelConfiguration or queue but there is not enough information available to identify which requests those are without also using information available from audit or apiserver logs.

### Why is this needed?

This new debug command, which could be called something like dump_executing_requests, could assist with live-debugging of APF issues. Situations where this would be useful:
1. General APF debugging to see which problematic requests are using a majority of seats per PriorityLevelConfiguration. This would aid in live-debugging in situations where the given request type is not included in the cluster's audit policy or if verbose apiserver logging is not enabled. Situations where a relatively low number of requests use a large number of seats could be debugged quicker (for example if listing 100k+ event objects is taking around 60 seconds).
2. APF issues with stuck requests. For example, this previous issue with broken CRD could've been quickly reproduced if we knew which watch request was stuck executing, https://github.com/kubernetes/kubernetes/issues/109603. A related issue that is still possible is issuing a watch request against a resource with an uninitialized watch-cache and this request will occupy an inflight request until the client drops the request or the watch-cache initializes. The audit event for the watch request will not be available until the request completes. To see which watch request is stuck, we would have to check apiserver logs at verbosity 3+ for requests which were dispatched but never completed.

**Comment by shyamjvs** [comment]
/sig api-machinery

cc @wojtek-t @tkashem @MikeSpreitzer

**Comment by MikeSpreitzer** [comment]
I think this makes sense.

**Comment by MikeSpreitzer** [comment]
I suspect it will be easier (more regular) if it built on #118955 .

**Comment by MikeSpreitzer** [comment]
There are a few different ways that we could update the interface here.

1. Leave `/debug/api_priority_and_fairness/dump_requests` unchanged, and add another debug endpoint, say `/debug/api_priority_and_fairness/dump_executing_requests`, that lists the executing requests.
2. Rename `/debug/api_priority_and_fairness/dump_waiting_requests` to `/debug/api_priority_and_fairness/dump_requests` and add `/debug/api_priority_and_fairness/dump_waiting_requests`.
3. Make `/debug/api_priority_and_fairness/dump_requests` list the executing requests as well as the waiting ones.
4. Make `/debug/api_priority_and_fairness/dump_requests` optionally accept additional query parameter(s) that control inclusion of waiting, inclusion of executing requests --- possibly defaulting to the current behavior.  For example, one query parameter might be `include_waiting`, accepting `true` or `false` and defaulting to `true`, while another would be `include_executing`, accepting `true` or `false` and defaulting to `false`.

**Comment by MikeSpreitzer** [comment]
@prateekgogia

**Comment by MikeSpreitzer** [comment]
@clemclx
