### ISSUE TITLE
digestConfigObjects is not critical of the given objects

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#118780]
### What happened?

In thinking about evolution scenarios, I realized that `digestConfigObjects` at https://github.com/kubernetes/apiserver/blob/2b176f025d6c5ce699f7361fe8fc04ce4b3cb2d3/pkg/util/flowcontrol/apf_controller.go#L541 should cast a skeptical eye --- that is, filter by validity --- the given objects.  It is possible for a server of a different release to store an object that will confuse the server interpreting the object.

### What did you expect to happen?

I expect servers to not crash even when run among a mixed population of servers.

### How can we reproduce it (as minimally and precisely as possible)?

Read the code and see how the given objects are uncritically incorporated into the data structure.  The only filtering done now is to omit a FlowSchema that refers to a non-existent priority level.

### Kubernetes version

<details>

Latest code and it has been this way all along.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by MikeSpreitzer** [comment]
@wojtek-t 
@deads2k 
@tkashem

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by BenTheElder** [comment]
Is this still valid?

**Comment by MikeSpreitzer** [comment]
No.
