### ISSUE TITLE
kubectl debug --profile=restricted do not set AllowPrivilegeEscalation or SeccompProfile for EphemeralContainer

### ISSUE THREAD

**Issue by ybelMekk** [kubernetes/kubernetes#118791]
### What happened?

Ive started to use the `kubectl debug` command recently and i found that trying to debug in a Pod Security Admission cluster/namespace, where `restricted` profile is labeled, the `kubectl debug` command dont return an ephemeral container with propper security context set, when using flag `profile=restricted`.  

From my investigation I can only find in the ephemeral container spec: 
`RunAsNonRoot` set to __true__ and `Capability.Drop` set to __ALL__.

It could be a issue with the version skew for cluster and client but i dont understand how the creation of a container with defined security context could differ? 

I tried with a local cluster and the +-1 version skew, same result.

### What did you expect to happen?

pod spec:

```console
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
spec:
  containers:
  - image: nginx:latest
    name: my-container
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
```

```bash
kubectl debug -it my-pod --image="cgr.dev/chainguard/busybox:latest" --profile=restricted -- sh
```

```bash
kubectl describe po my-pod
```

got:

```console
 ephemeralContainers:
  - command:
     - sh
     image: cgr.dev/chainguard/busybox:latest
      imagePullPolicy: Always
      name: debugger-628sx
      resources: {}
      securityContext:
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
```

want:

```console
 ephemeralContainers:
  - command:
     - sh
     image: cgr.dev/chainguard/busybox:latest
      imagePullPolicy: Always
      name: debugger-628sx
      resources: {}
      securityContext:
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
          - ALL
        runAsNonRoot: true
      stdin: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      tty: true
```

### How can we reproduce it (as minimally and precisely as possible)?

kubectl debug -it my-pod --image="cgr.dev/chainguard/busybox:latest"  --profile=restricted -- sh 

```console
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

kubectl debug -it my-pod --image="cgr.dev/chainguard/busybox:latest"  --profile=restricted -- sh 

```console
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.12-gke.500
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
```

Either way, it dosent give the security context I would expect. Fast glance in the source code, [here](https://github.com/kubernetes/kubernetes/blob/3e2840400880d7e698fdb390a9cb8eef08464ce9/staging/src/k8s.io/kubectl/pkg/cmd/debug/profiles.go#L170) i cant find any suspect..

### Kubernetes version

<details>

```console
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.24.12-gke.500
WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mochizuki875** [comment]
Hi, it seems to have been fixed and merged.
Planed to release in v1.28.

#117405
#117543

**Comment by ybelMekk** [comment]
@mochizuki875, sry for not checking coming release info before writing this issue. thanks

**Comment by ybelMekk** [comment]
already fixed.
