### ISSUE TITLE
Value of containerRuntimeEndpoint in configuration file ignored by kubelet

### ISSUE THREAD

**Issue by mbert** [kubernetes/kubernetes#118787]
### What happened?

The `containerRuntimeEndpoint` setting is supposed to make the `--container-runtime-endpoint` CLI option unnecessary when running `kubelet --config=/path/to/config`, but the value is ignored, so that the CLI option is still necessary.

### What did you expect to happen?

The `containerRuntimeEndpoint` setting should be used by `kubelet`.

### How can we reproduce it (as minimally and precisely as possible)?

```
# cat /etc/systemd/system/kubelet.service.d/kubelet.conf
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
address: 127.0.0.1
containerRuntimeEndpoint: unix:///var/run/containerd/containerd.sock
staticPodPath: /etc/kubernetes/manifests
# /usr/bin/kubelet --config=/etc/systemd/system/kubelet.service.d/kubelet.conf
E0620 11:27:45.374609    6249 run.go:74] "command failed" err="failed to validate kubelet flags: the container runtime endpoint address was not specified or empty, use --container-runtime-endpoint to set"
```

### Anything else we need to know?

```
# kubelet --version
Kubernetes v1.26.3
```

### Kubernetes version

<details>

```console
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

</details>

### Cloud provider

None, local VM.

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Oracle Linux Server"
VERSION="8.8"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Oracle Linux Server 8.8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:8:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://github.com/oracle/oracle-linux"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.8
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.8
$ uname -a
Linux kubernetes-master-1.dc.dermalog.hh 5.15.0-102.110.5.1.el8uek.x86_64 #2 SMP Sat Jun 10 18:15:29 PDT 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
```
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```
</details>

### Container runtime (CRI) and version (if applicable)

<details>
```
containerd containerd.io 1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8
```
</details>

**Comment by neolit123** [comment]
@mbert please include the kubelet --version in the description

**Comment by mbert** [comment]
> @mbert please include the kubelet --version in the description
> 
> we discovered that this does not happen in 1.27.x (cc @pacoxu )

I have updated the description, thank you for reminding ;)

**Comment by chenyw1990** [comment]
The reason for the error is because of the following validate check

https://github.com/kubernetes/kubernetes/blob/1e1863fabd22ce3bb9ec8cee4d231b64466184a9/cmd/kubelet/app/server.go#L192-L195

https://github.com/kubernetes/kubernetes/blob/1e1863fabd22ce3bb9ec8cee4d231b64466184a9/cmd/kubelet/app/options/options.go#L196-L201

this code has been deleted in pull request #114017

I will merge #114017 to v1.26 branch to fix this bug

**Comment by neolit123** [comment]
> I will merge https://github.com/kubernetes/kubernetes/pull/112136 to v1.26 branch to fix this bug

@pacoxu this is your PR, BTW ^

unclear to me what is the right action, but if the config field is not working it means that this is a blocking bug. ideally, we should backport a fix to all supported branches - 1.26, 125, 1.24.

https://kubernetes.io/releases/

cc @adisky @mrunalp

**Comment by chenyw1990** [comment]
@neolit123 @pacoxu

This may not be a bug, in v1.26 version, kubelet-config does not support containerRuntimeEndpoint and imageServiceEndpoint,  so --container-runtime-endpoint is a parameter that must be set
ref： https://v1-26.docs.kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/

containerRuntimeEndpoint is a new feature in v1.27 #112136
https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration

**Comment by pacoxu** [comment]
> containerRuntimeEndpoint is a new feature in v1.27 #112136
> https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration

Do we need to update the document to clarify that this is supported since v1.27?😓 https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster.

**Comment by neolit123** [comment]
> > containerRuntimeEndpoint is a new feature in v1.27 #112136
> > https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration
> 
> Do we need to update the document to clarify that this is supported since v1.27?😓 https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster.

you can just pr the change as a note and see how it goes.

usually the reply is that the docs are versioned and version  mentions in sentences are not needed. given the kubelet api is iterative (not like kubeadm, where we only push changes in new versions)  users might be indeed confused.
