### ISSUE TITLE
[Failing Test] capg-conformance-main-ci-artifacts

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#118718]
### Which jobs are failing?

master-informing

- capg-conformance-main-ci-artifacts

### Which tests are failing?

`periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts.Overall`

![Screenshot from 2023-06-17 09-59-04](https://github.com/kubernetes/kubernetes/assets/73882557/3cbb49f1-85d0-4ea4-92c1-f7495f1ad753)

### Since when has it been failing?

2023-06-15 23:27:58 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts

### Reason for failure (if possible)

`
googlecompute.ubuntu-1804: Error getting source image for instance creation: Could not find image, ubuntu-1804-lts, in projects, [k8s-jkns-gce-slow-1-4 almalinux-cloud centos-cloud cloud-hpc-image-public cos-cloud coreos-cloud debian-cloud fedora-cloud freebsd-org-cloud-dev rhel-cloud rhel-sap-cloud rocky-linux-cloud suse-cloud suse-sap-cloud suse-byos-cloud ubuntu-os-cloud windows-cloud windows-sql-cloud gce-nvme google-containers opensuse-cloud ubuntu-os-pro-cloud ml-images]
`

### Relevant SIG(s)

/sig testing
cc @kubernetes/ci-signal

**Comment by dims** [comment]
Looks like the 1804 image has been deleted from `ubuntu-os-cloud` project. This invalidates the configuration in image-builder:
https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/packer/gce/ubuntu-1804.json

Someone needs to file a PR in https://github.com/kubernetes-sigs/image-builder to cleanup references to ubuntu 18.04. Please open an issue in that project.

```
davanum@cloudshell:~ (kubernetes-public)$ gcloud compute images list --filter ubuntu-1804-lts                                                                                                
Listed 0 items.
```

```
davanum@cloudshell:~ (kubernetes-public)$ gcloud compute images list --filter ubuntu-2004-lts
NAME: ubuntu-2004-focal-arm64-v20230616
PROJECT: ubuntu-os-cloud
FAMILY: ubuntu-2004-lts-arm64
DEPRECATED: 
STATUS: READY

NAME: ubuntu-2004-focal-v20230616
PROJECT: ubuntu-os-cloud
FAMILY: ubuntu-2004-lts
DEPRECATED: 
STATUS: READY
```

**Comment by AverageMarcus** [comment]
The failing test is triggered from [cluster-api-provider-gcp](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/scripts/ci-conformance.sh) and would need to remove the references to ubuntu-18.04 to fix the tests. Updates to image-builder, while still needed (thank you for the issue 😄), wont have any effect on this issue.

**Comment by AverageMarcus** [comment]
FYI: We've now removed it from image-builder for GCP. (See https://github.com/kubernetes-sigs/image-builder/pull/1200)

**Comment by ameukam** [comment]
Fix for the failing test: https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/966

Latest run is green: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts/1674379747699724288

**Comment by cpanato** [comment]
fixed here https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/966

all green https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts

/assign
/close
