### ISSUE TITLE
Support rollover

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/kubernetes#11874]
Forked from #1353. Needed for Deployment #1743.

Rollover is a generalization of rolling update, where one replaces N replication controllers with one new one.

Scenarios:
* rolling update, pause in middle, create a patched image, perform a rolling update to replace the original image and the botched image
* Deployment: change desired state and kick off rolling update, then change desired state again before it finishes

cc @nikhiljindal

**Comment by nikhiljindal** [comment]
cc @ironcladlou

**Comment by bgrant0607** [comment]
@nikhiljindal Is this done?

**Comment by nikhiljindal** [comment]
Yes. Deployment controller handles this, but there is not test for it. Keeping the bug open till we add a test.

cc @janetkuo

**Comment by janetkuo** [comment]
#18125 adds e2e test for it.
