### ISSUE TITLE
Utilizing host kernel routing table in kubernetes

### ISSUE THREAD

**Issue by tchauhan362** [kubernetes/kubernetes#118728]
What would you like to be added?

As I know there is an parameter called routingViaHost in network operator in Openshift Container Platform. This is basically used to force OVN-Kubernetes to utilize the host kernel routing table and not use the OVN-Kubernetes routing table. 

I am looking for the same solution at Kubernetes level and where it can be controlled. 

### Why is this needed
I think this would be good feature to have at Kubernetes layer for situations where a port is defined and exposed on one node and a different node in the same cluster try to access data over same port. Without this feature, the packets can easily reach the said port but the replies would vanish which will cause a timeout and there is no way one can know where the replies are actually going to. It would make connections between applications on different nodes and networks very difficult.

/sig network

**Comment by aojea** [comment]
Kubernetes,with the default implementations, kube-proxy and cni standard plugins, always use the host network.

The other optimization or network related configurations are options of the cni plugins that implement the kubernetes network model, that are independent projects

/kind support
/close
