### ISSUE TITLE
AWS: Switch to use instance-ids as node name

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11883]
This will fix a lot of problems with non-kube-up setups, and is also generally more robust/correct.

Last time I tried this there was a problem with kubectl exec / logs, which still require the NodeName to be resolvable (and have a valid matching SSL cert).  There wasn't enough time to fix that for v1.

**Comment by roberthbailey** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/42196.

**Comment by justinsb** [comment]
Sadly not @roberthbailey .  Now that node names are no longer required to be resolvable, this is doable in the cloudprovider I believe, though still would be a non-trivial piece of work.

One big problem we have today is that node names are not unique; because they derive from the IP if you're in a small subnet reuse _does_ happen.

**Comment by mrIncompetent** [comment]
Maybe using an Instance-Tag would be more helpful? As this would enable the user to utilize the `--hostname-override` flag, so the name can be freely chosen by the user.
If the tag is not set, the instance id should be chosen.

@justinsb

**Comment by alexef** [comment]
@justinsb @mrIncompetent `--hostname-override` has no effect when cloud-provider=aws

This is also a problem from us.

**Comment by discordianfish** [comment]
And it's undocumented. I'm frankly suprised about the shape of the AWS cloud provider integration and it's documentation right now. I've spend more than a day debugging why it removes my instances.

**Comment by justinsb** [comment]
@discordianfish grab a mop :-)

**Comment by discordianfish** [comment]
@justinsb Don't get me wrong but as someone building kubernetes clusters for people, I can't possibly fix all issues I touch. I try my best to fill issues and fix blockers myself but I can't just mop up all the things and frankly wish this would be something AWS spends some resources on.

**Comment by justinsb** [comment]
Fair enough - the general ask is not that you fix the issue, but just move it forward (e.g. here the issue is tagging).  We discussed on slack, and we found where the docs got moved to; we talked about the additional tag format that isn't in there.  That's some progress at least :-)

**Comment by DanyC97** [comment]
@justinsb any progress on this by any chance ?
