### ISSUE TITLE
why the parameter --service-cluster-ip-range defined in both kube-apiserver and kube-controller-manager ? 

### ISSUE THREAD

**Issue by liuyanzhen34** [kubernetes/kubernetes#118854]
I am very confused why there is the same parameter **--service-cluster-ip-range**  in both kube-apiserver and kube-controller-manager to set the range of clusterIP. Why is it not defined in one of them? thank you .

**Comment by aojea** [comment]
the one in the apiserver defines the range used to allocate ClusterIPs for services
The one in the kube-controller-manager is used to avoid overlapping the Service cidr with the node ipam cidrs, 

This doc has a longer history and discussion about these two networks https://docs.google.com/document/d/1Dx7Qu5rHGaqoWue-JmlwYO9g_kgOaQzwaeggUsLooKo/edit#heading=h.rkh0f6t1c3vc

/kind support
/close
