### ISSUE TITLE
PodGC unit tests do not actually test addition of any conditions.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#118826]
### What would you like to be added?

We should enhance the podgc_controller_test.go to verify that adding `DisruptionCondition` is unit-testable.

We originally thought that this would only be possible with finalizers but there looks to be other options.  

We could follow examples from https://github.com/kubernetes/cloud-provider-gcp/blob/d716fdd45233c59b10fb76d5b72964cb8ec6d398/cmd/gcp-controller-manager/node_csr_approver_test.go#L1649.  

### Why is this needed?

In podgc, if we discover an orphaned pod (pod on a missing node), we add a DisruptionCondition to the pod.  

We only test this behavior in the integration tests because we previously rely on finalizers to halt the deletion so we can avoid flaky tests.

**Comment by lauchokyip** [comment]
Will take a look 👍🏻 

/assign

**Comment by UriZafrir** [comment]
newbie question please, I couldn't find the file podgc_controller_test.go in the codebase or the PRs. Where can I read it?

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podgc/gc_controller_test.go

**Comment by lauchokyip** [comment]
Working on it now!

**Comment by kannon92** [comment]
https://github.com/lauchokyip Has done very good work with this so I’m not sure we will be able to accept other PRs.  We are waiting for an approval on the PR

**Comment by kushalShukla-web** [comment]
is this issue still open

**Comment by kannon92** [comment]
> Is the issue still open or awaiting for the approval on the pr?

The issue is waiting for approval.  I removed the tags to reflect that is is almost done.
