### ISSUE TITLE
SSH tunnels fail without a cloud provider 

### ISSUE THREAD

**Issue by wingedkiwi** [kubernetes/kubernetes#11888]
When I set the flags `--ssh-keyfile` and `--ssh-user` on the `kube-apiserver`, I get the following error:
`Failed to load SSH Tunnels: Couldn't find external address`

It seems like the kube-apiserver looks for NodeExternalIP and fails, if it doesn't find it. When not using a cloud provider the ExternalIP is not set and only the LegacyHostIP is present.

From what I see, there is two ways to solve it:
  1. kube-apiserver should fallback on using the LegacyHostIP when ExternalIP is not present.
  2. Allow a way to specify ExternalIP / InternalIP for the kubelet to use when a cloud provider is not present.

The code line of matter seems to be here:
https://github.com/GoogleCloudPlatform/kubernetes/blob/7cc1855c27ac6a88b863d69fdd2d103613332313/pkg/master/master.go#L814

**Comment by wingedkiwi** [comment]
Added pull request that implements a simple fallback to LegacyHostIP.

**Comment by gosharplite** [comment]
Since #11892 has been merged, shouldn't this issue be closed?

**Comment by roberthbailey** [comment]
Looks like it.
