### ISSUE TITLE
default value for svc ipFamilyPolicy not right

### ISSUE THREAD

**Issue by yuansmin** [kubernetes/kubernetes#118897]
### What happened?

I created a headless service without selector, then apiserver set default value for svc.spec.ipFamilyPolicy=“RequireDualStack”, but my cluster is single stack. 

svc after created
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-27T08:19:23Z"
  name: test-headless
  namespace: default
  resourceVersion: "331503"
  uid: 30b14581-008b-49bf-81c2-f7ffa9e38953
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

### What did you expect to happen?

according to the [KEP](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack/#type-headless-services) it says default value for this case should be “PreferDualStack”

### How can we reproduce it (as minimally and precisely as possible)?

```
echo """apiVersion: v1
kind: Service
metadata:
  name: test-headless 
spec:
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP""" | kubectl create -f -
```

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7, GitCommit:"fc781087bc9131430285ab0ae770bcecc155a782", GitTreeState:"clean", BuildDate:"2022-11-03T02:41:56Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.7", GitCommit:"fc781087bc9131430285ab0ae770bcecc155a782", GitTreeState:"clean", BuildDate:"2022-11-03T03:34:48Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by yuansmin** [comment]
@aojea

**Comment by aojea** [comment]
I've verified the behavior in another cluster, it sets Require instead of Prefer

/sig network
/cc @khenidak @thockin @uablrek 

Related conversation https://kubernetes.slack.com/archives/C09QYUH5W/p1687765746243329

additional consequence

> my cluster is SingleStack, it raised spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services when I set the svc.spec.selector ,modify other fields is ok

**Comment by thockin** [comment]
I think the KEP is wrong.  A headless, selectorless Service: a) has no clusterIP (so IP family doesn't matter); and b) has user-defined endpoints (so we *can't* have an opinion about IP Family).  This case is handled specially in the registry code:

```
    if service.Spec.ClusterIP == api.ClusterIPNone {
        // Headless.
        if len(service.Spec.Selector) == 0 { 
            // Headless + selectorless is a special-case.
            //                                                                                                                                              
            // At this stage we don't know what kind of endpoints (specifically
            // their IPFamilies) the user has assigned to this selectorless
            // service. We assume it has dual-stack and we default it to
            // RequireDualStack on any cluster (single- or dual-stack
            // configured).
            service.Spec.IPFamilyPolicy = &requireDualStack
            service.Spec.IPFamilies = []api.IPFamily{r.primaryIPFamily, otherFamily(r.primaryIPFamily)}
        } else {
```

We made a decision to change to Require at some point, but I don't recall why.  

I suppose that COULD be "Prefer" instead of "Require", but the semantic is the same - we're going to set IPFamilies to have both values.  Is that worth changing at this point?  

> my cluster is SingleStack, it raised spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services

I can't repro that.

```
$ # prove that my cluster is single-stack

$ cat /tmp/s2.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-require-dual
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    foo: bar
  ipFamilyPolicy: RequireDualStack
  ports:
  - port: 80
    targetPort: 9376

$ k create -f /tmp/s2.yaml
The Service "test-require-dual" is invalid: spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services

$ # prove that headless-selectorless is OK

$ cat /tmp/s1.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-headless-selectorless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    targetPort: 9376
  selector: {}

$ k create -f /tmp/s1.yaml
service/test-headless-selectorless created

$ k get -o yaml svc test-headless-selectorless
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-06-27T20:29:36Z"
  name: test-headless-selectorless
  namespace: default
  resourceVersion: "29361609"
  uid: 2b237780-002a-43c0-993e-73beb47fcfd5
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: RequireDualStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9376
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by yuansmin** [comment]
> my cluster is SingleStack, it raised spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services

@thockin this happend when I modify the created svc `test-headless`, I added selector for it. and I guess this is just as expected

**Comment by thockin** [comment]
Yeah, that's probably expected.

**Comment by thockin** [comment]
Followup from sig-net call.

We *could* change this case to "Prefer" instead of "Require", but I think it will still fail validation in the case of "Prefer" + both families set + single-stack cluster.  Fixing that to change families back to single is a mess because we don't really know the intention.  MAYBE we could change it to allow this case ("Prefer" + both families set + single-stack cluster) without an error.

I'd have to think really hard about the implications of this - if it was easy(ish) code to change and low-risk, I'd be OK with it, I think.

I don't have to dig into this in the near future, but if someone wants to evaluate the code-complexity, I'd be good to look at it.

**Comment by khenidak** [comment]
it goes back to service apis :-) sigh. I do believe the current behavior while _looking_ funky works for all types of clusters.

**Comment by thockin** [comment]
It seems like there's not much reason to change this from Require to Prefer.  I'd be OK with that, if someone really wanted to pursue it and prove it is safe, but I don't think it's a "bug" per se.
