### ISSUE TITLE
Mark KMS v1beta1 as deprecated with no further fixes

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#118839]

**Comment by zelenushechka** [comment]
Hey @enj, I'm Anhelina from the Bug Triage Release team 1.28 👋. I wanted to reach out to discuss its progress and ensure it's on track for the v1.28 release, considering the Code Freeze is coming up on [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496). Could you please provide an update on the current status of the issue? Is it still planned for the v1.28 release? We are currently in Week 7, and the Code Freeze will be in effect by Week 9. If there's anything I can do to assist in resolving this issue, please let me know:)

**Comment by sftim** [comment]
/retitle  Mark KMS v1beta1 as deprecated with no further fixes

/kind deprecation

**Comment by sftim** [comment]
/sig security
(also relevant)
