### ISSUE TITLE
kmsv2: use gRPC decoding buffer for encrypted object

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#118835]
This issue refers to the `Marshal` and `Unmarshal` code:

https://github.com/kubernetes/kubernetes/blob/c2fb8057b2b9ad0b278c8f7412a3ec50787dd7e4/staging/src/k8s.io/apiserver/pkg/storage/value/encrypt/envelope/kmsv2/envelope.go#L251-L257

We will likely need a struct the encapsulates `proto.NewBuffer` and `EncryptedObject` re-use, probably with one or more `sync.Pool`s.

The benchmarks from #118828 should be used to validate the changes.

**Comment by enj** [comment]
@mikedanese got an example of the new API in use?

**Comment by mikedanese** [comment]
I realized after looking at the PR that you were using "golang/gogo/protobuf/proto".Buffer, not "golang/protobuf/proto".Buffer. I'm not sure the comment still applies but... new proto API would look like:

```go
import (
  "google.golang.org/protobuf/proto"
)

var marshaler proto.MarshalOptions

func foo(m proto.Message) {
  ...
  buf := pool.Get()
  out, err := marshaler.MarshalAppend(buf, m) 
  ...
}
```

I don't think you need any gogo features here, FWIW.

**Comment by enj** [comment]
Closing per https://github.com/kubernetes/kubernetes/pull/119167#issuecomment-1924647423
