### ISSUE TITLE
AWS: Figure out workaround for non-atomic tag creation

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11882]
Because we create tags non-atomically on AWS, there is often/always a window in which things can be in inconsistent states, where we have created the resource but not tagged it.  The consequence could be resource leakage, or (more rarely) infinite loops (see e.g. #11324).

We may be able to find a procedure, for example by searching for untagged resources and trying to recover from failed creates.  But this is hard because we don't want to go around deleting/claiming a user's non-k8s resources.

Retrying tagging will also help (#11029), but we still have a problem if we crash before we are able to tag the resource.

**Comment by evanphx** [comment]
@justinsb I'm happy to work on this issue. I'm looking through the code and it appears that the only resource that even has a tag applied is the security group. Is that correct or am I missing where/how the tag is applied to other resources?

Secondly, should the tags be applied to other resources and just haven't been done so yet? Or if only security groups have the tag, perhaps tags should not be used, which would eliminate the issue all together.

**Comment by roberthbailey** [comment]
Obsoleted by https://github.com/kubernetes/kubernetes/pull/42196.

**Comment by justinsb** [comment]
Sadly not @roberthbailey - it's a problem in the AWS API itself, so affects our creation of ELBs, EBS volumes, security groups etc.  We have code to push it way down into the long tail, but it remains an issue.

**Comment by roberthbailey** [comment]
Ah, so it's an aws cloud provider issue rather than an aws kube-up issue.
