### ISSUE TITLE
Kubernetes COREDNS Timeout

### ISSUE THREAD

**Issue by jaidatt-bhadsawale-dsw** [kubernetes/kubernetes#118824]
### What happened?

We created a kubernetes cluster on azure rhel 8.8 VMs. I exec inside a pod and do nslookup google.com, sometimes it works but sometimes it shows `"connection timed out; no servers could be reached"`
![image](https://github.com/kubernetes/kubernetes/assets/110471490/973fd611-b121-4cf4-a602-f9198e13f6c0)
This is my coredns config:
![image](https://github.com/kubernetes/kubernetes/assets/110471490/7b727bf8-ea26-480b-aa3e-3fca7b034b48)
The Applications inside pod uses kubernetes coredns to access the internet to download the files , since it is getting timeout applications are not able to download files properly it get's stuck.

### What did you expect to happen?

Whenever application connect to internet using coredns, timeout should not occur.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure.

### Kubernetes version

<details>

```console
$ kubectl version

Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5", GitCommit:"890a139214b4de1f01543d15003b5bda71aae9c7", GitTreeState:"clean", BuildDate:"2023-05-17T14:08:49Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

``
</details>

### Cloud provider

<details>
Azure 
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.7 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.7 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"


</details>


### Install tools

_No response_

### Container runtime (CRI) and version (if applicable)

cri-o://1.26.0


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico 
"cniVersion": "0.3.1"
</details>

**Comment by aojea** [comment]
/kind support

For support questions better use other channels like slack or discord, github issues are for code bugs and this seems more an environmental problem

You can also try to use the existing docs to troubleshoot this further
https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/

Thanks

/close
