### ISSUE TITLE
the log printing is incorrect and misleading.

### ISSUE THREAD

**Issue by bichengpeng** [kubernetes/kubernetes#118892]
https://github.com/kubernetes/kubernetes/blob/9d50c0a025273e82856af69f0e4f7cb420e65cd9/pkg/controller/util/node/controller_utils.go#L123C2-L123C2

**Comment by AmarNathChary** [comment]
hey @bichengpeng can you please explain something more on this issue? it seems like there is nothing incorrect.

**Comment by SergeyKanzhelev** [comment]
/close

please re-open with explanation on why it is misleading
