### ISSUE TITLE
Modify the kube-proxy `--hostname-override` option is invalid

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#118860]
### What happened?

kube-proxy is static pod, Modify the kube-proxy `--hostname-override`, but checking through `kubectl` shows that kube-proxy pod is still the name of the host

### What did you expect to happen?

kube-proxy pod name suffix is  `--hostname-override`

### How can we reproduce it (as minimally and precisely as possible)?

Modify the kube-proxy `--hostname-override` option

### Kubernetes version

<details>

```console
$ kubectl version
1.22.3
# paste output here
```

</details>

### Cloud provider

<details>
No
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
**--hostname-override : If non-empty, will use this string as identification instead of the actual hostname.**

It will not change hostname, only identification  get updated.

**Comment by tamilselvan1102** [comment]
Ref: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

**Comment by aojea** [comment]
> kube-proxy is static pod

kube-proxy is a binary, it can be deployed as a static pod, daemonset or as an independent application with systemd, 

> Modify the kube-proxy --hostname-override, but checking through kubectl shows that kube-proxy pod is still the name of the host

it was added here https://github.com/kubernetes/kubernetes/pull/69340 to solve some problems that are described in the linked PR

This is working as intended

/close

Thanks
