### ISSUE TITLE
Create struct for authn config and re-wire OIDC flags to use it

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#118832]
/sig auth
/assign @aramase 
/triage accepted
/milestone v1.28

**Comment by zelenushechka** [comment]
Hey, I'm Anhelina from the Bug Triage Release team 1.28 :wave:. I wanted to reach out to discuss its progress and ensure it's on track for the v1.28 release, considering the Code Freeze is coming up on [01:00 UTC Wednesday 19th July 2023 / 18:00 PDT Tuesday 18th July 2023](https://everytimezone.com/s/72ee8496). Could you please provide an update on the current status of the issue? Is it still planned for the v1.28 release? We are currently in Week 7, and the Code Freeze will be in effect by Week 9. If there's anything I can do to assist in resolving this issue, please let me know:)

**Comment by aramase** [comment]
@zelenushechka Thanks for the ping! Yes, this is planned for `v1.28` release.

**Comment by zelenushechka** [comment]
Week 9 update: Code Freeze is approaching!

Hey! We are currently in Week 9, and Code Freeze is just over a week away. It will begin at 01:00 UTC on Wednesday, 19th July 2023 / 18:00 PDT on Tuesday, 18th July 2023. Please ensure all necessary submissions are made before the deadline. Let me know if you need any assistance. :)
