### ISSUE TITLE
successfulJobsHistoryLimit and failedJobsHistoryLimit make pods orphan

### ISSUE THREAD

**Issue by mcantinqc** [kubernetes/kubernetes#118834]
### What happened?

On Kubernetes 1.22.x successfulJobsHistoryLimit and failedJobsHistoryLimit, so the parameter ttlSecondsAfterFinished doesn't exist. On any newer version, every pods are keep even if the job is deleted.

I know there a note on the documentation, but I still think that was a bug.

### What did you expect to happen?

Pods are supposed to be delete when associate job is deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Any cronjob on Kubernetes 1.23,.x or newer.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.2-eks-c12679a", GitCommit:"002c6bc4e142b1f48b9405140e559194a094dcff", GitTreeState:"clean", BuildDate:"2023-05-22T20:23:13Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by azN2** [comment]
+1, on 1.24 and 1.27
