### ISSUE TITLE
AWS: CloudFormation / other scripts must set KubernetesCluster tags

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11884]
AWS uses a KubernetesCluster tag to track which resources are part of a particular k8s cluster (I think GCE uses projects for this).

We need to document exactly the requirements here, and also make sure e.g. the CoreOS cloudformation approach is tagging correctly.

**Comment by pires** [comment]
AFAIK no one has maintained CloudFormation files in a while and I am looking for them to become deprecated with #9178.

**Comment by justinsb** [comment]
I think that is probably right @pires (though @philips may be able to corral someone into taking up the maintenance).  The problem is that there is so much logic in bash & salt that it is a lot of work for CloudFormation templates to keep up.

I am conducting a small experiment to see what happens if we rewrite the bash logic in go.  The hope is that it could then:

1) give a similar "it just works" experience to what we have today
2) have it do better at doing incremental changes (which also serve as problem detection)
3) share common code with other platforms
4) "dry-run" and produce bash commands, which people could review and then run manually
5) maybe even render to CloudFormation

A total experiment right now, but I'm having fun so far...

**Comment by pires** [comment]
@justinsb I'm all in for that and I was hoping for the [reworked Kubernetes CLI](https://github.com/kubernetes/kubernetes/issues/5472) to _land_ before jumping into implementing the CoreOS provider for it.

**Comment by justinsb** [comment]
@pires thanks for the link.  I posted a similar blurb there to try to coordinate efforts.

Also I meant to include a link: https://github.com/justinsb/contrib/tree/installer/installer

Doesn't actually deploy anything yet, but I'm not trying to keep it a secret!

**Comment by jimmycuadra** [comment]
For those of us doing custom deployments on AWS, what resources need to have this tag and what behavior of which k8s components does it affect?

**Comment by zilman** [comment]
> aws.go:546] Zone not specified in configuration file; querying AWS metadata service
aws.go:676] Tag "KubernetesCluster" not found; Kuberentes may behave unexpectedly.
aws.go:683] AWS cloud - no tag filtering

It looks like the tags it wants are:
- KubernetesCluster = `<name>`
- aws:autoscaling:groupName = `<example: kubernetes-minion-group-us-west-2a>`

- Role = kubernetes-`{master,minion}`
- Name = kubernetes-`{master,minion}`

I think (and hope) the last two are optional. 

Despite being somewhat self explanatory this should really be better documented. 

My take is you want a name to differentiate the nodes of different clusters, and you want to hint to the master what the ASG of the minions is called, despite it being inferable if it just scans for the first tag...

**Comment by jimmycuadra** [comment]
Sounds like all of those tags are not useful if each cluster is in a different VPC (which they are for us.)

**Comment by zilman** [comment]
Actually, I did find a [note](https://github.com/kubernetes/kubernetes/blob/master/docs/design/aws_under_the_hood.md#tagging) on this just now.

> you must pick a unique cluster-id value, and ensure that all AWS resources have a tag with Name=KubernetesCluster,Value=`<clusterid>`

So you only need this one. kube-up.sh sets it by default to 'kubernetes'. If you only have one cluster per VPC I suppose they can all have the same name. Hmm.

**Comment by justinsb** [comment]
This is now documented (https://github.com/kubernetes/kubernetes/blob/70a8ea5817ec412ae9f647a060cb93c55ac0e311/docs/design/aws_under_the_hood.md), and we aren't making further changes to kube-up (users should probably be using kops instead).  Closing.

**Comment by jimmycuadra** [comment]
I still don't understand what the consequence of not using those tags in a custom deployment is. The document states:

> ** Important: ** If you choose not to use kube-up, you must pick a unique cluster-id value, and ensure that all AWS resources have a tag with Name=KubernetesCluster,Value=<clusterid>.

but it doesn't say why.

Since our clusters are in separate VPCs, this is the only thing that might affect us:

> Within the AWS cloud provider logic, we filter requests to the AWS APIs to match resources with our cluster tag. By filtering the requests, we ensure that we see only our own AWS objects.

but I don't really understand what that means. Could we add some more information to that to explain where this "cloud provider logic" is implemented, what exactly it does, how it is observing AWS API requests, and what the implications of filtering those requests or not are?
