### ISSUE TITLE
Missing migration to Pod Security Admission information

### ISSUE THREAD

**Issue by LyKos4** [kubernetes/kubernetes#118924]
### What happened?

https://github.com/kubernetes/kubernetes/blob/master/docs/tasks/configure-pod-container/migrate-from-psp missing file 

### What did you expect to happen?

To get the instructions for migration to Pod Security Admission 

### How can we reproduce it (as minimally and precisely as possible)?

just check repo

### Anything else we need to know?

Mentioned in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#changelog-since-v1240 

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
Mentioned missing link is not there in https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.25.md#changelog-since-v1240 page.

**PodSecurityPolicy** page: https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/

**Comment by LyKos4** [comment]
link: https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp/

**Comment by tamilselvan1102** [comment]
i am not find any error link in this page
