### ISSUE TITLE
how to manual rotation ca cert for k8s binary deployment

### ISSUE THREAD

**Issue by ingla9988** [kubernetes/kubernetes#118925]
### What happened?

My k8s is deployed in binary
how to manual rotation ca cert？I tried many times and failed
thank you

### What did you expect to happen?

manual rotation ca is successful

### How can we reproduce it (as minimally and precisely as possible)?

manual rotation ca cert  in k8s

### Kubernetes version

k8s 1.13

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
Please refer: [manual-rotation-of-ca-certificates](https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/)

**Comment by tamilselvan1102** [comment]
/language en
[manual-rotation-of-ca-certificates](https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/) page you can see 12 steps, Please trace which step it is failing.

**Comment by neolit123** [comment]
> Please refer: [manual-rotation-of-ca-certificates](https://kubernetes.io/docs/tasks/tls/manual-rotation-of-ca-certificates/)

yes, that is the place to check. also please ask questions in #kubernetes-users on k8s slack.

/close
/kind support

**Comment by ingla9988** [comment]
2. Update the --root-ca-file flag for the [kube-controller-manager](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/) to include both old and new CA, then restart the kube-controller-manager.

 old and new ca.key  need to be configured together？
