### ISSUE TITLE
[Flaky test][sig-node] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#118968]
### Which jobs are flaking?

[sig-node] Topology Manager [Serial] [NodeFeature:TopologyManager] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite

We saw the failure occasionally on arm64, pls see: https://github.com/kubernetes/kubernetes/pull/118919

> [sig-node] Topology Manager [Serial] [NodeFeature:TopologyManager] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite
test/e2e_node/topology_manager_test.go:861
  STEP: Creating a kubernetes client @ 06/28/23 00:10:44.522
  STEP: Building a namespace api object, basename topology-manager-test @ 06/28/23 00:10:44.522
  Jun 28 00:10:44.524: INFO: Skipping waiting for service account
  STEP: by configuring Topology Manager policy to single-numa-node @ 06/28/23 00:10:44.534
  Jun 28 00:10:44.534: INFO: Configuring topology Manager policy to single-numa-node
  Jun 28 00:10:44.534: INFO: failed to find any VF device from [{0000:00:00.0 -1 false false} {0000:00:01.0 -1 false false} {0000:00:04.0 0 false false} {0000:00:05.0 -1 false false}]
  Jun 28 00:10:44.534: INFO: New kubelet config is {{ } %!s(bool=true) /tmp/node-e2e-20230627T232107/static-pods2504443847 {1m0s} {10s} {20s}  map[] 0.0.0.0 %!s(int32=10250) %!s(int32=10255) /usr/libexec/kubernetes/kubelet-plugins/volume/exec/  /var/lib/kubelet/pki/kubelet.crt /var/lib/kubelet/pki/kubelet.key []  %!s(bool=false) %!s(bool=false) {{} {%!s(bool=false) {2m0s}} {%!s(bool=true)}} {AlwaysAllow {{5m0s} {30s}}} %!s(int32=5) %!s(int32=10) %!s(int32=50) %!s(int32=100) %!s(bool=true) %!s(bool=false) %!s(int32=10248) 127.0.0.1 %!s(int32=-999) cluster.local [] {4h0m0s} {10s} {5m0s} %!s(int32=40) {2m0s} %!s(int32=85) %!s(int32=80) {10s} /kubelet.slice  / %!s(bool=true) systemd static map[] {1s} None single-numa-node container map[] map[] {2m0s} promiscuous-bridge %!s(int32=110) 10.100.0.0/24 %!s(int64=-1) /etc/resolv.conf %!s(bool=false) %!s(bool=true) {100ms} %!s(int64=1000000) %!s(int32=50) application/vnd.kubernetes.protobuf %!s(int32=50) %!s(int32=100) %!s(bool=false) %!s(*int32=<nil>) map[memory.available:250Mi nodefs.available:10% nodefs.inodesFree:5%] map[] map[] {30s} %!s(int32=0) map[nodefs.available:5% nodefs.inodesFree:5%] %!s(int32=0) %!s(bool=true) %!s(bool=false) %!s(bool=true) %!s(int32=14) %!s(int32=15) map[DisableKubeletCloudCredentialProviders:%!s(bool=true)] %!s(bool=true) {} 10Mi %!s(int32=5) Watch [] %!s(bool=true) map[] map[cpu:200m]   [pods]   {text 5s %!s(v1.VerbosityLevel=4) [] {{%!s(bool=false) {{{%!s(int64=0) %!s(resource.Scale=0)} {%!s(*inf.Dec=<nil>)} 0 DecimalSI}}}}} %!s(bool=true) %!s(bool=false) {0s} {0s} [] [] %!s(bool=true) %!s(bool=true) %!s(bool=false) %!s(*float64=0x4001977560) [] %!s(bool=true) %!s(*v1.TracingConfiguration=<nil>) %!s(bool=true) unix:///run/containerd/containerd.sock }
  STEP: Stopping the kubelet @ 06/28/23 00:10:44.534
  Jun 28 00:10:44.546: INFO: Get running kubelet with systemctl:   UNIT                            LOAD   ACTIVE SUB     DESCRIPTION
    kubelet-20230627T232107.service loaded active running /tmp/node-e2e-20230627T232107/kubelet --kubeconfig /tmp/node-e2e-20230627T232107/kubeconfig --root-dir /var/lib/kubelet --v 4 --hostname-override i-0f1d9bf08a330dd96 --container-runtime-endpoint unix:///run/containerd/containerd.sock --config /tmp/node-e2e-20230627T232107/kubelet-config --kernel-memcg-notification=true --feature-gates=DisableKubeletCloudCredentialProviders=true --image-credential-provider-config=/tmp/node-e2e-20230627T232107/credential-provider.yaml --image-credential-provider-bin-dir=/tmp/node-e2e-20230627T232107 --cluster-domain=cluster.local --cgroup-driver=systemd --cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service

>  LOAD   = Reflects whether the unit definition was properly loaded.
  ACTIVE = The high-level unit activation state, i.e. generalization of SUB.
  SUB    = The low-level unit activation state, values depend on unit type.
  1 loaded units listed.
  , kubelet-20230627T232107
  W0628 00:10:44.598698    2723 util.go:496] Health check on "http://127.0.0.1:10248/healthz" failed, error=Head "http://127.0.0.1:10248/healthz": read tcp 127.0.0.1:59126->127.0.0.1:10248: read: connection reset by peer
  STEP: Starting the kubelet @ 06/28/23 00:10:44.603
  W0628 00:10:44.632245    2723 util.go:496] Health check on "http://127.0.0.1:10248/healthz" failed, error=Head "http://127.0.0.1:10248/healthz": dial tcp 127.0.0.1:10248: connect: connection refused
  STEP: checking node CPU capacity (4) and allocatable CPUs (3) @ 06/28/23 00:10:49.638
  STEP: running a non-Gu pod @ 06/28/23 00:10:49.638
  STEP: checking if the expected cpuset was assigned @ 06/28/23 00:10:51.65
  Jun 28 00:10:51.660: INFO: Unexpected error: expected log not found in container [non-gu-container] of pod [non-gu-pod]: 
      <*errors.errorString | 0x40014038d0>: 
      failed to match regexp "^0-3\n$" in output "0,3\n"
      {
          s: "failed to match regexp \"^0-3\\n$\" in output \"0,3\\n\"",
      }
  [FAILED] in [It] - test/e2e_node/cpu_manager_test.go:275 @ 06/28/23 00:10:51.661

A different error msg with arm64  on ubuntu18.04

> [FAILED] expected log not found in container [gu-container] of pod [gu-pod]: failed to match regexp "^1,29,57,85\n$" in output "28,56\n"
In [It] at: /go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e_node/cpu_manager_test.go:388 @ 06/28/23 14:35:53.953

### Which tests are flaking?

[sig-node] Topology Manager [Serial] [NodeFeature:TopologyManager] With kubeconfig updated to static CPU Manager policy run the Topology Manager tests run Topology Manager policy test suite

### Since when has it been flaking?

the could be found occasionally on arm64, and I double the issue exists for quite a long time.

### Relevant SIG(s)

/sig node

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

cpumanager is a GA component, we should cut down flakes

**Comment by chendave** [comment]
/cc @ruquanzhao 

Can you pls take a look at this when you get a chance?

**Comment by ffromani** [comment]
I'm not sure there is a simple fix. I tend to believe the root cause is the cpumanager tests have too many assumptions about the CPU layout hardcoded and they finally reached the breaking point.  If this is true, it means we will require a massive rewriter of the cpumanager e2e tests.

**Comment by chendave** [comment]
> I tend to believe the root cause is the cpumanager tests have too many assumptions about the CPU layout hardcoded and they finally reached the breaking point. 

Yes, I think @ruquanzhao has already find something on arm64, typically, for some old arm64 server, the assumption is not always true.

> If this is true, it means we will require a massive rewriter of the cpumanager e2e tests.

we'll evacuate if  we can rewrite the e2e by ourselves, otherwise we will ask for help from others.

**Comment by ruquanzhao** [comment]
@ffromani 
I found the root cause of this issue. The e2e-node test doesn't consider CPUs that there are more than 3 threads in one core (usually 4 threads). https://github.com/kubernetes/kubernetes/pull/119614 (WIP)fixes one step of the test. 
If we are going to rewrite the whole test, I am willing to take this.

**Comment by ffromani** [comment]
> @ffromani I found the root cause of this issue. The e2e-node test doesn't consider CPUs that there are more than 3 threads in one core (usually 4 threads). #119614 (WIP)fixes one step of the test. If we are going to rewrite the whole test, I am willing to take this.

I think the project will significantly benefit of a massive rewrite of that e2e suite but, despite my best intentions, I keep postponing this effort and I can't commit to that anytime soon, unfortunately. I'll review that PR ASAP: if a simple fix is possible, I'm all for it (but a rewrite is more and more due anyway)

**Comment by esotsal** [comment]
According to [1](https://storage.googleapis.com/k8s-triage/index.html?pr=1&test=With%20kubeconfig%20updated%20to%20static%20CPU%20Manager%20policy%20run%20the%20Topology%20Manager%20tests%20run%20Topology%20Manager%20policy%20test%20suite), related test has failed 1% from 21st August 2024 but for different reason. I agree with the comment from @ffromani , and i think https://github.com/kubernetes/kubernetes/issues/100145 to improve e2e suite for CPU Manager cover this case here as well, so still very much relevant. Perhaps we could close this issue and use 100145 one instead ?

**Comment by kannon92** [comment]
sounds good to me.

/close
