### ISSUE TITLE
NCC-E003660-UCG: Weaknesses in Pod Security Standards Restricted Profile

### ISSUE THREAD

**Issue by reylejano** [kubernetes/kubernetes#118987]
### NCC-E003660-UCG: Weaknesses in Pod Security Standards Restricted Profile
This issue was reported in the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Description**
The Pod Security Standards “Restricted” profile builds atop the “Baseline” profile, primarily
by ensuring that pods cannot run as root, that they cannot run with capabilities other than
`NET_BIND_SERVICE`, and that they must enable a seccomp profile. However, while the
profile requires that all variants of `runAsUser` must be nonzero, it does not similarly require
that `runAsGroup` must also be nonzero. Due to this, it may be possible for a pod running
with GID 0 to access sensitive resources that are group owned by root and user-group, but
not world-readable or -writable.

Additionally, the seccomp requirements enable the selection of a `type: Localhost` for
`seccompProfile`. While this requires that the `seccompProfile.localhostProfile` field is
set to an existing relative path from `/var/lib/kubelet`, this can pose a risk in the event
that a cluster is configured with multiple tailored and lax localhost seccomp profiles, as a
user with access to create pods could opt into a weaker seccomp profile than that of the
`RuntimeDefault` profile.

**Recommendation**
Introduce additional requirements to the “Restricted” profile to restrict group configuration
An example from the report is:

> **Running as Non-root group**
> Containers must not set runAsGroup to 0
> **Restricted Fields**
> - spec.securityContext.runAsGroup
> - spec.containers[*].securityContext.runAsGroup
> - spec.initContainers[*].securityContext.runAsGroup
> - spec.ephemeralContainers[*].securityContext.runAsGroup
> **Allowed Values**
> - any non-zero value
> - undefined/null

Additionally, document that users should be careful not to expose seccomp profiles weaker
than RuntimeDefault , or that they should use a custom admission controller to restrict the
seccomp profiles that may be used by given containers or within a given namespace.
Lastly, consider introducing a mutating variant of the Pod Security Standards admission
controller that will override unset fields such as `allowPrivilegeEscalation`, `capabilities`, `runAsNonRoot`, `seccompProfile`, and `runAs(User|Group)` with secure defaults that will then still be validated by the validating Pod Security Standards admission controller. This may make it simpler to ease adoption of Restricted profiles, from Baseline
or in general.

**Anything else we need to know?**
See umbrella issue [#118980](https://github.com/kubernetes/kubernetes/issues/118980) for current status of all issues created from these findings.
The vendor gave this issue an ID of NCC-E003660-UCG and it was finding 4 of the report under the Security Architecture Review section.
The vendor considers this issue Low Risk.
To view the original finding, begin on page 16 of the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Test Environment**
Kubernetes 1.24.3

**Comment by liggitt** [comment]
> consider introducing a mutating variant of the Pod Security Standards admission
controller that will override unset fields such as allowPrivilegeEscalation, capabilities, runAsNonRoot, seccompProfile, and runAs(User|Group) with secure defaults that will then still be validated by the validating Pod Security Standards admission controller.

This aspect was considered and rejected during development of the Pod Security Admission feature. In practice, unilaterally changing the execution environment of a container more often breaks the process execution in difficult to diagnose ways at runtime.

**Comment by liggitt** [comment]
dropping the label so this shows up in storage / node scrubs

**Comment by msau42** [comment]
The main impacts if the Pod uses volumes are:
1) fsgroup would be required for storage types that support fsgroup
2) If the storage type doesn't support fsgroup, then the user needs to adjust the allowable users/groups on the storage backend
3) The user may need to add supplemental groups to the Pod if they can't get the fsgroup or volume owner to match the gid.

**Comment by xing-yang** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
I think that Restricted policy allowing GID 0 is bad. We should restrict `runAsGroup` the same way as `runAsUser` + restrict `fsGroup` the same, i.e. not allow 0. Both have `nil` as the default value, someone must have explicitly set them to `0`.

Setting either of them explicitly to `0` odd, but possible. We could warn about it for a release or two before we introduce hard validation.

**Comment by jCOTINEAU** [comment]
Hello everyone, we found out from Openshift documentation (see [here](https://docs.openshift.com/container-platform/4.15/openshift_images/create-images.html#use-uid_create-images)) that in order to Support application running with Any UID, the solution was put group root permissions.

What then would be the way to support running Any UID applications ? setting up broad permissions on the FS directly ?
