### ISSUE TITLE
The rbd image in the e2e test was not found

### ISSUE THREAD

**Issue by HirazawaUi** [kubernetes/kubernetes#118979]
### What happened?

The registry.k8s.io/e2e-test-images/volume/rbd:1.0.6 image defined in the e2e test was not found
https://github.com/kubernetes/kubernetes/blob/94f664a16664dc7c45706c0a89b64d6f6e1d5fa6/test/utils/image/manifest.go#L272

### What did you expect to happen?

image can be pull successfully

### How can we reproduce it (as minimally and precisely as possible)?

Use docker to pull the image
```
docker pull registry.k8s.io/e2e-test-images/volume/rbd:1.0.6
Error response from daemon: manifest for registry.k8s.io/e2e-test-images/volume/rbd:1.0.6 not found: manifest unknown: Failed to fetch "1.0.6"
```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
Not promoted?
https://github.com/kubernetes/k8s.io/blob/75dfac7c94e2511a8a16a3be0ced864bf796b977/k8s.gcr.io/images/k8s-staging-e2e-test-images/images.yaml#L166-L169

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/post-kubernetes-push-e2e-volume-rbd-test-images 
failed.

/assign

**Comment by mkumatag** [comment]
This is long ago, even prow job ui will not show an option to rerun.. may be a dummy PR to repo might be helpful.
> After #117103 is merged, the built failed. This need a re-run by CI admins.

**Comment by xing-yang** [comment]
@humblec Do we still need this image to test rbd?  We have deprecated the in-tree plugin, right?

**Comment by humblec** [comment]
@xing-yang regardless of the current state, its good to keep the image in the CI as it has a reference.. we will check why `prow` timeout still happens and somehow try to make the available in the backend.. 

cc @mkumatag

**Comment by mkumatag** [comment]
may be I can try building locally outside the cloud build environment and push to staging meanwhile(this recalls me how we use to handle these images initially 😞)

**Comment by mkumatag** [comment]
@humblec I don't see any code change went into [volume/rbd](https://github.com/kubernetes/kubernetes/commits/master/test/images/volume/rbd) post this merge - https://github.com/kubernetes/test-infra/pull/30202

May be you can try your luck one more time making some changes in the repo to trigger the cloud build, worst case I will try building it locally if nothing happens!
