### ISSUE TITLE
Kubernetes certificate is expired and manual rotation is failing.

### ISSUE THREAD

**Issue by akshaysharama** [kubernetes/kubernetes#118944]
### What happened?

Hi, 

In my system, Kubernetes is running for the past 1yr, and two days back certificate got expired, not able to access the k8s cluster.

I tried the following setups to renew the certificate.

As ca.crt is expired, renewed using creating single root ca.
steps:
./easyrsa init-pki
./easyrsa --batch "--req-cn=kubernetes" build-ca nopass
./easyrsa --subject-alt-name="IP:$masterIP,""IP:10.233.0.0,""IP:10.233.0.1,""IP:127.0.0.1,""DNS:ubuntu18,""DNS:localhost,""DNS:kubernetes,""DNS:kubernetes.default,""DNS:kubernetes.default.svc,""DNS:kubernetes.default.svc.cluster,""DNS:kubernetes.default.svc.cluster.local" --days=10000 build-server-full server nopass

Note: ubuntu18 is the node-name.

sudo cp ca.crt /etc/kubernetes/pki/
sudo cp ca.key /etc/kubernetes/pki/
sudo mv server.key apiserver.key
sudo cp apiserver.key /etc/kubernetes/ssl/
sudo mv server.crt apiserver.crt
sudo cp apiserver.crt /etc/kubernetes/ssl/
sudo update-ca-certificates

sudo kubeadm certs renew all
`

 [ renew] Reading configuration from the cluster...
[renew] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[renew] Error reading configuration from the Cluster. Falling back to default configuration

certificate embedded in the kubeconfig file for the admin to use and for kubeadm itself renewed
certificate for serving the Kubernetes API renewed
MISSING! certificate the apiserver uses to access etcd
certificate for the API server to connect to kubelet renewed
certificate embedded in the kubeconfig file for the controller manager to use renewed
MISSING! certificate for liveness probes to healthcheck etcd
MISSING! certificate for etcd nodes to communicate with each other
MISSING! certificate for serving etcd
W0509 21:34:49.679054   32697 certs.go:489] WARNING: could not validate bounds for certificate front-proxy CA: the certificate has expired: NotBefore: some date, NotAfter: some date
W0509 21:34:49.679234   32697 certs.go:489] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate has expired: NotBefore: some date, NotAfter: some date
certificate for the front proxy client renewed
certificate embedded in the kubeconfig file for the scheduler manager to use renewed

Done renewing certificates. You must restart the kube-apiserver, kube-controller-manager, kube-scheduler and etcd, so that they can use the new certificates.
`

sudo kubeadm kubeconfig user --config /etc/kubernetes/kubeadm-config.yaml --org system:nodes --client-name system:node:ubuntu18 > kubelet.conf
sudo rm -rf /var/lib/kubelet/pki/kubelet-client-some-date.pem
sudo service kubelet restart

sudo mv ~/.kube/config ~/.kube/config.old
sudo cp -i /etc/kubernetes/admin.conf ~/.kube/config  

sudo kubectl delete po api-server, controller, scheduler and docker restart etcd.

After this kubectl and everything started working, deletion of the pod got successful but pod is not scheduling back.

Did I miss anything? I haven't created front-proxy.ca as we don't have external apiserver extension, do we still need it?

ERROR IN KUBELET

`
err="error getting ClusterInformation: Get \"https://10.233.0.1:443/apis/crd.projectcalico.org/v1/clusterinformations/default\": x509: certificate signed
ntime service failed" err="rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"coredns-6887969bb-cj6t8_kube-system\" network: erro
 before removing" err="rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"coredns-6887969bb-cj6t8_kube-system\" network: error geT..
`

### What did you expect to happen?

Renew of k8s should work.

### How can we reproduce it (as minimally and precisely as possible)?

change the date to next date of k8s certs expiry.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ uname -a

Linux ubuntu18 4.15.0-202-generic #213-Ubuntu SMP Thu Jan 5 19:19:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by SergeyKanzhelev** [comment]
/sig network

/remove-sig node

this looks like cni failure and needs to be investigated with sig network first.

**Comment by SergeyKanzhelev** [comment]
Also please try it on supported version of k8s. 1.21 is out of support. Please list the CNI versions and configuration.

**Comment by akshaysharama** [comment]
Hi @SergeyKanzhelev, 

after performing the above setups, I deleted all pods, in the default namespace and kube-system as well. after that only control plane pods got scheduled, no pods in default namespace or no calico, coredns pods got scheduled. even docker containers are not running. 

 "name": "cni0",
  "cniVersion":"0.3.1",

`
vmauser@ubuntu18:/etc/cni/net.d$ sudo cat calico.conflist.template
{
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "datastore_type": "kubernetes",
      "nodename": "__KUBERNETES_NODE_NAME__",
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["10.233.64.0/18"]
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "__KUBECONFIG_FILEPATH__"
      }
    },
    {
      "type":"portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type":"bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    }
  ]
}
`

`
vmauser@ubuntu18:/etc/cni/net.d$ sudo cat calico-kubeconfig
# Kubeconfig file for Calico CNI plugin. Installed by calico/node.
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: https://10.233.0.1:443
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EWXlPREl6TVRjeU9Gb1hEVE16TURZeU5USXpNVGN5T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTllSCnRwVzVNRTR3emxYbDNFNVpoZWxZRVRKZGNBa0hjSkQ0S2FGZDRYYWxGUWdvcG9lSHd6Y01LK20zb0xVUG9QUHEKc0NWN0czaG9XbGJtMFpCdk9iK3VSRjRNcUdHZy9rN0Q0bGE3cW5zMEwrcTZkYXpXdDM0b2NIbzgxMTBhUzlRSwp3dDNPUFZZTkJJYnE2ZHlnNE1SWkl1L3o2RmwyTi8xMU9VMkt0QldHOHJBbDNsKzZYMFJ6VmFLd3kzRmJERU5kCkEwN2EvUEFFc09ZUmFHRlU1YmRyS3Zic2FUU2M0dXRKS1dOeExWWm9BTHlxUEtUZzdaMlNEQzZsVkNkeitNS3UKVXI3WTlHa2Jjd1dIWko1THV0c2lub3Q1ZkRJM3pzblhmL3lTaEYwVjJWM05YV2tqOSs0cndoVTZRU1ZER3IrVwpKSnM5RFdzQ3B6WHRxMlRpenpjQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNMUpJdGRwQll2SlUzcFJMTUJnVmhSbWZnSERNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBeVMwMWhqMUpqaTRyRVh0QytMYkN1MTJjc1ppNU82a3lBUk8yVWpCcG5vYXNiWGVqdwo2U2NBWURCanZNTHYraUtXMG1yMllIb29JZGFCbzVWM2NQWjd6VmhRYVNramZQWTUzSGlyeEsyMVhXVVZsQ0FtCkNXWW9zclNkTXVjdm1EYVhjNU1GTkVQRExEZ3d2cHZEcHExenkyNjliU29pTXVEemFvN1gxZXJNQjhBTEs0b0kKYjdpSnFBeHN5RGg1QW53WUpQSnNxUithV1VONFVWK1JyQ3lXUDlKOXJaS0FYM0x6K2ZMME5SbWszcXUrajdpRgowVmx5ZmxzYmhTaVdmT3JKRmZTVVpFQlNSK0ZLL0pRZWN5dTRkK3hSamZwU3ZBdnBObU1XNkN2QVc0bDJwSGI3CmladTZiWTV6ZTVJMXBlTVhleXJTQW5PZzRBU1k1MURSQTRLSAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
users:
- name: calico
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il9WcmN4aWY1MUVHY0pEYmk3TDczam95YV9aNWNRcTM2MVA0VERGOXFVSkUifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE5NTM5MDg1LCJpYXQiOjE2ODgwMDMwODUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInBvZCI6eyJuYW1lIjoiY2FsaWNvLW5vZGUtcHRkZDgiLCJ1aWQiOiJhM2Q5ZGZmYy0zNmQ1LTQ3NjctOGQxZi0yMmQ3OGM5YjFiZDIifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNhbGljby1ub2RlIiwidWlkIjoiNGQ2ZmRmNDctOWI1NC00ZGYwLWJiZTQtMDIzNGU4NWU2ZWU0In0sIndhcm5hZnRlciI6MTY4ODAwNjY5Mn0sIm5iZiI6MTY4ODAwMzA4NSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmNhbGljby1ub2RlIn0.UUtjTTfQKx3Tyr296_X9UJEHiTeHXJxnE5Dkk0epHDU5DSPACuOHW8pTkhCreJu_lqFwUUHBu1ugZjoke87GtVKcZmOesIpDf7wAqlJebQ7oOYiPih4EV58gZ_5y_a3X7fgufkITpBNlvG-8Dr5KdYIvmKpez_F9_Jd2nsiWmrUqqbBLg--KxB4mEpcZXhqIBy3NMXAkfxYUgFbKvowkaxmVRB9ISh3qBL9WA9qMTgyour6J3hCPwWUt70zZbZoi_dki2UB3eiA4LBoulhW7r331XQ9HZFKW2BupMGJFDB_PAHw7ppbAQTlvW8xulhH-a7S_aE9U3UjMXHZwXc-fUg
contexts:
- name: calico-context
  context:
    cluster: local
    user: calico
`

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
