### ISSUE TITLE
When publishNotReadyAddresses is set to true, Services route traffic to not-ready Pods anyway

### ISSUE THREAD

**Issue by drivera-armedia** [kubernetes/kubernetes#118952]
### What happened?

When creating a set of pods behind a service facade (with **_publishNotReadyAddresses=true_**), from which only one pod is marked as ready (albeit they're all running), traffic hitting the service IP gets routed to all pods, not just the ready one(s).

It's possible this is a side-effect of hard-wiring the _**ready**_ attribute in _EndpointSlice_ to _**true**_ (as documented [here](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready)).

It seems to me that traffic should only be routed to the pods if _**both**_ _ready_ and _serving_ are _**true**_. The observed behavior contradicts the [documentation of the publishNotReadyAddresses flag](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

### What did you expect to happen?

Service traffic to only be routed to pods in Ready status.

### How can we reproduce it (as minimally and precisely as possible)?

1) create a stateful set or deployment whose pods will randomly mark themselves as ready, and those marked as ready will listen on a given port (using **_nc -kl 8000_** or **_python3 -m http.server_**)
2) create a service that will route traffic to those pods, and set _publishNotReadyAddresses=true_
3) attempt to access the service's IP + Port repeatedly, observe how "connection refused" errors occur sporadically, evidencing that traffic is being routed to pods that aren't listening.

### Anything else we need to know?

The pods' startup and liveness probes are successful, but only one of the pods' readiness probe succeeds. Regardless, traffic is attempted to be served out to all pods.

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.10-eks-c12679a", GitCommit:"bbfa7e393476eb418f98a8c785721a006ba830cd", GitTreeState:"clean", BuildDate:"2023-05-22T20:31:17Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Amazon EKS v1.25.10-eks-c12679a, also standalone K8s v1.27.3
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux k8s-server 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
K8s v1.27.3
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:51:00 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:51:00 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> It seems to me that traffic should only be routed to the pods if both ready and serving are true. The observed behavior contradicts the [documentation of the publishNotReadyAddresses flag](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

I can't find that statement in the linked doc, but this is working as expected, that option override the readiness of the pods https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready so all pods will receive traffic

/remove-kind bug
/kind support

**Comment by drivera-armedia** [comment]
> I can't find that statement in the linked doc, but this is working as expected, that option override the readiness of the pods https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#ready so all pods will receive traffic
> 
> /remove-kind bug /kind support

The docs (or, rather, lack of docs to the contrary) suggest that this flag's effects only impact the DNS portion (i.e. being able to look up unready pods via cluster DNS). Nowhere in the docs is there a warning that enabling this flag will cause Service traffic to be routed to unready pods, nor is it suggested anywhere.

If this is by design, then it should be plainly stated wherever this flag is documented, for clarity. If we really want to thread thinly, the flag should then be named something more descriptive of all its effects, for example "routeNotReadyAddresses", or "publishAndRouteNotReadyAddresses".

My point is this:  EndpointSlice has the _ready_ and the _serving_ flags separate precisely because _publishNotReadyAddresses_ hardwires _ready_ to _true_. Per the docs this was done for vertical compatibility. It also seems to be the case that the _serving_ flag more tightly mirrors a pod's actual READY status, in spite of the value of _publishNotReadyAddresses_.

Thus, adding the _serving_ flag, but not using it to help inform service routing decisions seems like an odd approach.

In the end, don't you want services to route traffic to pods that are both ready to serve, _**and**_ serving traffic?

Cheers.

**Comment by drivera-armedia** [comment]
I've found a workaround involving using two separate services: a headless service with _publishNotReadyAddresses_ set to **true** (named _**myservicename-dns**_), to resolve the issue of "availability of DNS names" as early as possible during parallel pod bootup, and a "normal" service with _publishNotReadyAddresses_ set to **false** (named _**myservicename**_) to avoid the routing pains I mentioned above.

Thus, for pod lookup I can safely use _pod-name-0.myservicename-dns_ and have the lookup succeed, and reach the pod correctly, while for actually consuming the services I can use _myservicename_, and be confident that traffic won't be routed/proxied to unready pods.

While this is a viable workaround, I still find it somewhat unelegant, since I still think the service infrastructure should only route traffic to endpoints (slices, really) that are marked as _**both**_ ready _**and**_ serving.

But that's just my opinion, which is worth as much as you paid to ready it :)

I'll live with this approach for now.

Cheers!
