### ISSUE TITLE
APF metric request_concurrency_limit is redundant and badly described

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubernetes/kubernetes#118957]
### What happened?

In https://kubernetes.slack.com/archives/C01G8RY7XD3/p1686626782936059 @JohnRusk asked the following question.

> is apiserver_flowcontrol_request_concurrency_limit measured in seats or requests, and does it include any adjustments that have been made as a result of borrowing?

While the user-facing documentation answers this question clearly enough, John was reading the HELP string in the Prometheus scrapes.  That thing only says the following.

> Shared concurrency limit in the API Priority and Fairness subsystem

### What did you expect to happen?

The metric HELP strings should be clear enough.

### How can we reproduce it (as minimally and precisely as possible)?

Scrape or read the code (`staging/src/k8s.io/apiserver/pkg/util/flowcontrol/metrics/metrics.go`).

### Kubernetes version

<details>

This problem started when we generalized to allow width other than 1 and got worse when we introduced borrowing.

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by MikeSpreitzer** [comment]
@kubernetes/sig-api-machinery-bugs

**Comment by MikeSpreitzer** [comment]
Actually, this metric should be removed.  It is a duplicate of `apiserver_flowcontrol_nominal_limit_seats` but with an inferior name.

**Comment by MikeSpreitzer** [comment]
@MikeSpreitzer

**Comment by JohnRusk** [comment]
Looks good @MikeSpreitzer. (Sorry I never got around to making this issue myself. Have been super busy. And your wording is better anyway :-) )

**Comment by jiahuif** [comment]
/triage accepted
Thank you.
