### ISSUE TITLE
NET_RAW isn't added to ephemeral container via netadmin debugging profile

### ISSUE THREAD

**Issue by tonyaw** [kubernetes/kubernetes#118962]
### What happened?

I assume netadmin debugging profile is for network debugging purpose, but it only adds NET_ADMIN capability to ephemeral container, and no NET_RAW capability.
Only with NET_ADMIN, even ping command can't be run:
[root@foss-ssc-11 ping_cap]# kubectl exec -ti ephemeral-demo-6d9cf75845-j4dbp bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
test@ephemeral-demo-6d9cf75845-j4dbp:/$ capsh --print
Current: =
Bounding set =cap_net_admin
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=504(test) euid=504(test)
gid=1000(test)
groups=
Guessed mode: UNCERTAIN (0)
test@ephemeral-demo-6d9cf75845-j4dbp:/$ ping 127.0.0.1
bash: /usr/bin/ping: Operation not permitted
test@ephemeral-demo-6d9cf75845-j4dbp:/$  

### What did you expect to happen?

NET_RAW capability shall be added if netadmin debugging profile is used.

It is not a problem if container runtime is containerd, as NET_RAW is one of default capability, but it is an issue for CRIO, as NET_RAW isn't a default capability.
To keep it safe, Kubernetes shouldn't rely on container run time default capability, and always add NET_RAW when netadmin debugging profile is used.

### How can we reproduce it (as minimally and precisely as possible)?

With crio as container runtime, create a ephemeral container via netadmin debugging profile.
command ping shall be fail to run inside the ephemeral container.

### Kubernetes version

<details>

```console
[root@foss-ssc-11 ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
[root@foss-ssc-11 ~]#
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig node network

> but it is an issue for CRIO, as NET_RAW isn't a default capability.

cc @saschagrunert

**Comment by saschagrunert** [comment]
It looks like the main intention of the netadmin profile is to be network administrator. From the KEP:

> netadmin | Network Administrator privileges.

I think we have to update the enhancement when agreeing to add `CAP_NET_RAW`: https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#profile-netadmin

**Comment by tonyaw** [comment]
@saschagrunert , Thanks for your info.
By design, could you please help to share what operations are expected to run by network administrator only with NET_ADMIN?

**Comment by uablrek** [comment]
This is not a sig/network issue
/remove-sig network

**Comment by mochizuki875** [comment]
As described [here](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cli/1441-kubectl-debug#profile-netadmin), I think `netadmin` profile intends to debug something related to network.

> This profile offers elevated privileges for network debugging.

Unless `CAP_NET_RAW`, we can't use any program which use RAW and PACKET sockets like `tcpdump` so I also think it is oversight.
Same discussed [here](https://github.com/kubernetes/enhancements/issues/1441#issuecomment-1483047759) and I try to fix it now(#118647).

By the way, `netadmin` profile in case of Node add `privileged` so it seems all Capability(including `CAP_NET_ADMIN` and `CAP_NET_RAW`) have already been added.
I'm wondering adding privileged to `netadmin` profile is neccesary...
Is there any reason?

I couldn't find out it from that PR(#115712).

When it become clear, I'll update KEP and continue to work #118647.

**Comment by mochizuki875** [comment]
> By the way, netadmin profile in case of Node add privileged so it seems all Capability(including CAP_NET_ADMIN and CAP_NET_RAW) have already been added.
I'm wondering adding privileged to netadmin profile is neccesary...
Is there any reason?

If no reason, I'll create PR to update Profile: netadmin section of [KEP-1441: kubectl debug](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1441-kubectl-debug/README.md) as below:

```markdown
#### Profile: netadmin

| Journey             | Debug Container Behavior                                                   |
| ------------------- | -------------------------------------------------------------------------- |
| Node                | sets `NET_ADMIN` and `CAP_NET_RAW`; uses host namespaces                   |
| Pod Copy            | sets `NET_ADMIN` and `CAP_NET_RAW` on debugging container                  |
| Ephemeral Container | sets `NET_ADMIN` and `CAP_NET_RAW` on ephemeral container                  |
```

**Comment by verb** [comment]
I think adding `NET_RAW` fits with the spirit of the netadmin profile. The intention was to provide "network administrator" permissions, not specifically `NET_ADMIN`.
