### ISSUE TITLE
NCC-E003660-PA6: Additive Access Controls

### ISSUE THREAD

**Issue by reylejano** [kubernetes/kubernetes#118982]
### NCC-E003660-PA6: Additive Access Controls
This issue was reported in the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Description**
In Kubernetes, authorization is handled at the API level based on the authorization modes
the API server is configured with. The main user-facing Kubernetes authorization mode,
`RBAC`, provides a role-based access control (RBAC) system that maps principals to
operations related to resources across single namespaces or entire clusters based on
whether the Roles and/or RoleBindings are Cluster-level. However, the Kubernetes RBAC
model does not support Deny rules, instead only identifying whether a user has a
permission to access a given resource in a given way. Due to this, the model can be
considered to “fail open” in the event that a principal is, through generic or over-broad role
definitions, granted unintended permissions. 

The Kubernetes’ authorization model is structured such that it will sequentially try all configured authorization modes until one returns an explicit `DecisionAllow` or `DecisionDeny`, or return an error in the event that they all return `DecisionNoOpinion`. [Link to reference](https://github.com/kubernetes/kubernetes/blob/v1.24.3/plugin/pkg/auth/authorizer/rbac/rbac.go#L126). While this model can be used similarly to
Kubernetes’ admission controller model, in which an allowed Boolean is used and for
which any failed validation will result in an overall error, in practice, internal authorizers
such as Node and RBAC can only return DecisionNoOpinion on failure, not DecisionDeny ,
preventing them from fully rejecting accesses.

**Recommendation**
Consider enhancing the current RBAC authorization mode or introducing a new RBAC mode
with support for explicit Deny rules that return `DecisionDeny`.

Additionally, support the ability to configure authorization such that all configured
authorization modes must allow an access attempt before it is processed. Furthermore,
consider implementing a mechanism for an authorization mode to subquery other
authorization modes. Lastly, consider embedding authentication metadata to authorization
modes, enabling increased or decreased access based on the context of the user.

**Anything else we need to know?**
See umbrella issue [#118980](https://github.com/kubernetes/kubernetes/issues/118980) for current status of all issues created from these findings.
The vendor gave this issue an ID of NCC-E003660-PA6 and it was finding 1 of the report under the Security Architecture Review section.
The vendor considers this issue Medium Risk.
To view the original finding, begin on page 11 of the [Kubernetes 1.24 Security Audit Report](https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2021-2022/findings/Kubernetes%20v1.24%20Final%20Report.pdf)

**Test Environment**
Kubernetes 1.24.3

**Comment by nilekhc** [comment]
@liggitt Could you please summarize the conversation from the meeting if any?

**Comment by liggitt** [comment]
> @liggitt Could you please summarize the conversation from the meeting if any?

Sorry, this dropped off my radar. Thanks for the comment, @luxas, which bumped it up.


Of the recommendations, three are declined and one is already possible:

> Consider enhancing the current RBAC authorization mode or introducing a new RBAC mode with support for explicit Deny rules that return DecisionDeny.

This was previously requested and declined in https://github.com/kubernetes/kubernetes/issues/85963#issuecomment-708403412

> Additionally, support the ability to configure authorization such that all configured authorization modes must allow an access attempt before it is processed.

This was discussed in the August 2nd sig-auth meeting. This would break composability of authorizers. If a cluster administrator wants a single authoritative authorizer and wants to make it aware of all other authorization modes, delegating to a webhook that behaves the way they want and returns a single authoritative answer would allow that.

> Furthermore, consider implementing a mechanism for an authorization mode to subquery other authorization modes.

We do not plan to expand the authz API surface to expose individual authorizer implementations.

> Lastly, consider embedding authentication metadata to authorization modes, enabling increased or decreased access based on the context of the user.

Authentication metadata included in the `extra` fields of the authenticated user info is already propagated to the authorizer and can be used to make authorization decisions.
