### ISSUE TITLE
meaning of sync_proxy_rules_iptables_total given MinimizeIPTablesRestore

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#118978]
The `sync_proxy_rules_iptables_total` metric is defined as "Number of proxy iptables rules programmed".

In the past, that effectively meant "the total number of rules in iptables that kube-proxy owns". But post-`MinimizeIPTablesRestore`, it now ends up being "the number of iptables rules that changed in the last sync". (FWIW this is only a change for the `nat` half of the metric; currently we always rewrite all `filter` rules, even in a partial sync, so the `filter` half of the metric is still "correct".)

There are arguments for either meaning, but I think the traditional ("total number of rules in iptables that kube-proxy owns") is more useful?

One possibility would be to only set the metric during full syncs, but in that case we might go a very long time without updating it, and it would get out of date.

Another possibility would be that instead of setting that metric from the `iptables-restore` _input_, we could set it from the `iptables-save` _output_. This would mean that it would always lag by (at least) one sync (since it would be set based on the rules we are replacing rather than the rules we are creating) but that would at least be more up-to-date than waiting for the next full resync. (In `largeClusterMode`, it would lag a bit more, only getting updated once every `syncPeriod` (default 30s).)

If we think it's important to have it always be up-to-date then we could try to figure out some way to calculate the right value during a partial update... in that case we'd have to run through the code that currently gets bypassed during a partial update, and have it decide what rules are needed, but not actually try to write them.

/sig network

**Comment by aojea** [comment]
The comment sounds more accurate `IptablesRulesTotal is the number of iptables rules that the iptables proxy installs. `

https://github.com/kubernetes/kubernetes/blob/d27439701f6cc83f992eda73b4797fa1af8fe7f7/pkg/proxy/metrics/metrics.go#L163-L172


As the tables it installs at that point in time

**Comment by danwinship** [comment]
But is that definition actually useful to anyone given `MinimizeIPTablesRestore`?

Knowing how many rules kube-proxy is responsible for total seems useful. Knowing how many rules it wrote in the last sync doesn't seem all that useful, given that we already have another metric for "how long the last sync took".

**Comment by aojea** [comment]
" sync_proxy_rules_iptables_total / how long the last sync took " =  netfilter throughput performance "rules/second" ... makes sense?

**Comment by shaneutt** [comment]
We discussed this in the SIG Network sync today: despite feeling there may be some value to the new way this works, we want to make sure we don't change this on users without proper warning. We're going to go back to the previous meaning for the time being and consider adding the other meaning if wanted.

/triage accepted
