### ISSUE TITLE
Copying contents in subdirectory- ConfigMap, Volumes

### ISSUE THREAD

**Issue by reshmagcp** [kubernetes/kubernetes#119043]
I have a kind: Deployment  as below where I am mounting **rs-config.yaml** ConfigMap(which contains a ss.yml file) as volume. With the below configuration I am able to get the ss.yml file in the specified  **mountPath: C:\....\....\....\....\App_Data\**
Apart from ss.yml I need another directory named DATA in the same path(C:\....\....\....\....\App_Data\) for which I used the subPath. With the below code I am able to get DATA directory but the contents in the DATA directory are not getting completely copied(subdirectories and some files are missing which are required for our application to be up). 

 _- name: volume-rs
          configMap:
            name: rs-config
            items:
            - key: ss.yml
              path: remote/AppData/
  containers:
        - name: remote
          image: registry_name
          volumeMounts:
          - name: volume-rs
            mountPath: C:\....\....\....\....\App_Data\ss.yml
            subPath: remote/AppData/_

Can anyone suggest a workaround for this? Any help would be grateful. Thanks in advance.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
