### ISSUE TITLE
kube-scheduler not able to customise

### ISSUE THREAD

**Issue by Aadarsh-Verma** [kubernetes/kubernetes#119069]
### What happened?

I want to understand and customise the kube-scheduler scoring mechanism
My goal is once a list of feasible nodes is fetched a node where the most CPU is available should get selected
I have written the below yaml for establishing this
apiVersion: [kubescheduler.config.k8s.io/v1beta2](http://kubescheduler.config.k8s.io/v1beta2)
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
profiles:
- schedulerName: kube-scheduler
  pluginConfig:
  - args:
      scoringStrategy:
        resources:
        - name: cpu
          weight: 9
        - name: memory
          weight: 1
        type: LeastAllocated
    name: NodeResourcesFit
- schedulerName: default-scheduler
  plugins:
    score:
      enabled:
      - name: NodeResourcesFit
        weight: 1300
      - name: NodeResourcesBalancedAllocation
        weight: 1350
I want to understand how NodeResourcesFit calculates the least allocated  resource also
how does  NodeResourcesBalancedAllocation  works
also my ultimate goal is to schedule pods based on CPU availability

### What did you expect to happen?

kube-scheduler working fine

### How can we reproduce it (as minimally and precisely as possible)?

kubernetes version 1.24

### Kubernetes version

1.24

### Cloud provider

<details>

</details>
NA

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
NA

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
What is the problem you are facing?

You mention that you want to prioritize lowest amount of CPU specifically, but you also have a configuration for `NodeResourcesBalancedAllocation`, which sounds counter-intuitive.

`scoringStrategy:` seems to be empty?

**Comment by Aadarsh-Verma** [comment]
`apiVersion: kubescheduler.config.k8s.io/v1beta2
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: "/var/lib/kubernetes/kube-scheduler.kubeconfig"
leaderElection:
  leaderElect: true
profiles:
- schedulerName: default-scheduler
  pluginConfig:
  - args:
      scoringStrategy:
        resources:
        - name: cpu
          weight: 100
        - name: memory
          weight: 1
        type: LeastAllocated
    name: NodeResourcesFit
  plugins:
    score:
      enabled:
      - name: NodeResourcesFit
        weight: 130000000
      disabled:
      - name: "*"`
      
      this is my updated config 
  Still I can see that it's not selecting the nodes with the lowest cpu utilization

**Comment by alculquicondor** [comment]
It's hard to see what's the yaml. Please use three ticks ``` to enclose your code

Also, a weight of around 10 should be enough to overcome the other plugins.

**Comment by Aadarsh-Verma** [comment]
updated the config Please check again @alculquicondor

**Comment by alculquicondor** [comment]
> I want to know the exact weights and plugins and the scheduling process in detail

You can start here, although it doesn't go into much detail
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scheduling/scheduling_code_hierarchy_overview.md

**Comment by alculquicondor** [comment]
I don't see any problems in your configuration, other than the weight for NodeResourcesFit seems unnecessarily high. I'm not sure if such weight could be cause overflowing. Try a weight of 10.

Otherwise, can you describe a bit of your nodes and pods? what is the allocatable and usage for a Node at the time of scheduling. What resources is your pod requesting.

**Comment by alculquicondor** [comment]
I would also suggest running the scheduler with `-v=2`. This will ouput the final configuration that scheduler is using in the logs. Maybe this can shed some light on what could be wrong.
