### ISSUE TITLE
Release v1.0.x versions of hyperkube image

### ISSUE THREAD

**Issue by bhouse** [kubernetes/kubernetes#11902]
I'm running the master node processes (`apiserver`, `controller-manager`, and `scheduler`) via the [hyperkube](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/cluster/images/hyperkube) container image. Currently I'm using `v0.21.2` but would like to upgrade to `v1.0.x`, but the images aren't available in `gcr.io/google_containers/hyperkube`:

```shell
➜  ~  docker pull -a gcr.io/google_containers/hyperkube
Pulling repository gcr.io/google_containers/hyperkube
...
Status: Image is up to date for gcr.io/google_containers/hyperkube
➜  ~  docker images | grep hyperkube
gcr.io/google_containers/hyperkube                                      v0.21.2                            f1f0bba2640f        13 days ago         217.1 MB
gcr.io/google_containers/hyperkube                                      v0.19.3                            254732241d07        2 weeks ago         207.8 MB
gcr.io/google_containers/hyperkube                                      v0.18.2                            d522ee56957b        6 weeks ago         207.2 MB
gcr.io/google_containers/hyperkube                                      v0.17.0                            ef8f7b8d1a29        9 weeks ago         197.8 MB
gcr.io/google_containers/hyperkube                                      v0.16.2                            cc81cf40a8bb        10 weeks ago        193.9 MB
gcr.io/google_containers/hyperkube                                      v0.16.1                            5f290ee2bb8a        12 weeks ago        191.1 MB
gcr.io/google_containers/hyperkube                                      v0.15.0                            867d278e4eb4        3 months ago        188.7 MB
gcr.io/google_containers/hyperkube                                      v0.14.2                            fe0b881108c3        3 months ago        185.2 MB
gcr.io/google_containers/hyperkube                                      v0.14.1                            d71f514edd93        3 months ago        185.2 MB
gcr.io/google_containers/hyperkube                                      dev                                d793ed9ec1a0        3 months ago        185.2 MB
gcr.io/google_containers/hyperkube                                      0.14.1                             13eaef725684        3 months ago        185.2 MB
```

I ran into the same issue with the v0.21.x release and asked about it in IRC. @brendandburns was able to push new images very quickly. Can this be part of the normal release process?

Thanks!

**Comment by dchen1107** [comment]
Pushing release images should be part of normal release process.

**Comment by galan** [comment]
Run into same issues, the documentation still refers to the 0.21.1 release: http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html

**Comment by jgeiger** [comment]
The image exists per https://github.com/GoogleCloudPlatform/kubernetes/issues/11751#issuecomment-126504358

I was just able to download it.

**Comment by mbforbes** [comment]
+cc @brendandburns @zmerlynn

**Comment by chrisleck** [comment]
Instructions at http://kubernetes.io/v1.0/docs/getting-started-guides/docker.html are still out of date.

**Comment by bgrant0607** [comment]
Assigned to @quinton-hoole to decide what to do and assign or punt.

**Comment by quinton-hoole** [comment]
@bgrant0607 Yes, I think that we need to solve this general problem (for all images that form part of a release).  I think it's too late for v1.1 though, and probably falls into the 1.2 technical debt bucket.

**Comment by vyshane** [comment]
Can we have a push for `gcr.io/google_containers/hyperkube:v1.0.7`?

**Comment by quinton-hoole** [comment]
Yes, my apologies for this having dragged on. @ihmccreery can you push this as part of the 1.0.7 release please?

**Comment by ihmccreery** [comment]
Should be good to go!  Reopening #11751 to make this part of our release process.
