### ISSUE TITLE
Query about operation of EndpointSlice controller

### ISSUE THREAD

**Issue by gaurang101197** [kubernetes/kubernetes#119020]
Source: [service](https://kubernetes.io/docs/concepts/services-networking/service/#endpointslices)
> By default, Kubernetes makes a new EndpointSlice once the existing EndpointSlices all contain at least 100 endpoints. Kubernetes does not make the new EndpointSlice until an extra endpoint needs to be added.

source: [endpoint-slices](https://kubernetes.io/docs/concepts/services-networking/endpoint-slices/#distribution-of-endpointslices)
> if there are 10 new endpoints to add and 2 EndpointSlices with room for 5 more endpoints each, this approach will create a new EndpointSlice instead of filling up the 2 existing EndpointSlices. In other words, a single EndpointSlice creation is preferrable to multiple EndpointSlice updates.

Is not above two quotes from k8s's official documents contradicting ?

**Comment by aojea** [comment]
I think the quotes are under some context, that is important 

> Your Kubernetes cluster tracks how many endpoints each EndpointSlice represents. If there are so many endpoints for a Service that a threshold is reached, then Kubernetes adds another empty EndpointSlice and stores new endpoint information there. By default, Kubernetes makes a new EndpointSlice once the existing EndpointSlices all contain at least 100 endpoints. Kubernetes does not make the new EndpointSlice until an extra endpoint needs to be added.


> The control plane tries to fill EndpointSlices as full as possible, but does not actively rebalance them. The logic is fairly straightforward:
> 
> Iterate through existing EndpointSlices, remove endpoints that are no longer desired and update matching endpoints that have changed.
> Iterate through EndpointSlices that have been modified in the first step and fill them up with any new endpoints needed.
> If there's still new endpoints left to add, try to fit them into a previously unchanged slice and/or create new ones.
> Importantly, the third step prioritizes limiting EndpointSlice updates over a perfectly full distribution of EndpointSlices. As an example, if there are 10 new endpoints to add and 2 EndpointSlices with room for 5 more endpoints each, this approach will create a new EndpointSlice instead of filling up the 2 existing EndpointSlices. In other words, a single EndpointSlice creation is preferrable to multiple EndpointSlice updates.

**Comment by neolit123** [comment]
if you have more questions please log this ticket in kubernetes/website.
/close
