### ISSUE TITLE
NodeLocalDNS not working with custom hosts

### ISSUE THREAD

**Issue by chmodrs** [kubernetes/kubernetes#119051]
### What happened?

In EKS 1.22, after installing nodelocaldns, in-cluster DNS and external DNS works normally, but custom hosts stored in coredns configmap, stop working.

### What did you expect to happen?

I expect that even with nodelocaldns, custom hosts continue to work normally.

### How can we reproduce it (as minimally and precisely as possible)?

1. Configure custom hosts in coredns configmap

```
# kubectl edit configmap coredns -n kube-system

hosts custom.hosts mydns.rtm {
        8.8.4.4 mydns.rtm
        fallthrough
       }

```

2. Ping mydns.rtm

```
# kubectl exec -it nginx2-55764b6d95-dvvdh -- ping mydns.rtm
PING mydns.rtm (8.8.4.4): 56 data bytes
64 bytes from 8.8.4.4: seq=0 ttl=105 time=2.401 ms
64 bytes from 8.8.4.4: seq=1 ttl=105 time=1.158 ms
64 bytes from 8.8.4.4: seq=2 ttl=105 time=1.286 ms
```

3. Download nodelocaldns manifests and replace values.

```
#!/bin/sh

echo "Downloading nodelocaldns"
wget https://raw.githubusercontent.com/kubernetes/kubernetes/v1.22.17/cluster/addons/dns/nodelocaldns/nodelocaldns.yaml -O manifests/nodelocaldns.yaml

echo "replacing values"
sed -i '' -e 's/__PILLAR__DNS__DOMAIN__/cluster.local/g' manifests/nodelocaldns.yaml
sed -i '' -e 's/__PILLAR__DNS__SERVER__/172.20.0.10/g' manifests/nodelocaldns.yaml ### kubectl -n kube-system get service kube-dns
sed -i '' -e 's/__PILLAR__LOCAL__DNS__/169.254.20.10/g' manifests/nodelocaldns.yaml ### default nodelocadns ip address
```

5. Apply manifests.

`# kubectl apply -f manifests/nodelocaldns.yaml`

6. Stop to working

```
# kubectl exec -it nginx2-55764b6d95-dvvdh -- ping mydns.rtm
ping: bad address 'mydns.rtm'
command terminated with exit code 1
```

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.17-eks-c12679a", GitCommit:"786577566fad3d67e4a3af4584c70706c25b6b90", GitTreeState:"clean", BuildDate:"2023-05-22T20:32:54Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.22) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
AWS eks 1.22
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
/area dns
/sig network
https://github.com/kubernetes/dns/issues may be the right place to submit the issue.

As I know, you can edit nodelocaldns configmap to add `hosts` after 1.17.0 https://github.com/kubernetes/dns/pull/422.

**Comment by shaneutt** [comment]
We'll need someone to drive this forward, I'm going to hang on to it for a second to remind myself to find someone.

/assign @shaneutt

**Comment by shaneutt** [comment]
https://github.com/kubernetes/dns/issues/592 has been created so this should be OK to close in favor of that one.

/close
