### ISSUE TITLE
e2e tests should label kubernetes.io/os

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#119022]
This issue may require us to add node labels to a bunch of test pods .... if we decide we want to do go forward w it.  I think its valuable for mixed OS type clusters (arm,amd,win...) but this example stems from a windows test we saw faik today.

Open to ideas on what the right thing to do it wrt labeling our pods w nodeSelector constraints .... goal being that it's easy to certify e2es on clusters w non standard node pools.

### What happened?

I think this issue specifically effects our ability to test EKS clusters with windows... but i think it might be a general improvement we can make to the e2es to make them self-consistent.

It appears you can make pods when running tests such as this one https://github.com/kubernetes/kubernetes/blob/master/test/e2e/network/service.go#L1116C13-L1116C51, that some pods arent labelled.  

In the case i care about im seeing that `node-os-distro` isnt percolating to result in 

```
nodeSelector:
  kubernetes.io/os: windows
  kubernetes.io/arch: amd64
```

And because of this, it turns out that when running e2es on mixed WL clusters (one linux node, one windows node) , you run into a situation where 
- some pods schedule (bc they default on linux) 
- and others land on windows nodes, and then fail to come up b/c some providers (like EKS) want to see a 
```
nodeSelector:
  kubernetes.io/os: windows
  kubernetes.io/arch: amd64 
```
(this results i think in adding a vpc.amazonaws.com/PrivateIPv4Address... annotation which then enables EKS CNI to do its thing).... 

## For our EKS friends

... until we make this improvement to the e2es, is there a workaround, we think, to make EKS CNI happy even if a pod that lands on a windows node isnt specifically annotated https://github.com/aws/containers-roadmap/issues/463 ? 

### What did you expect to happen?

I would expect that pods are labelled  based on the `node-os-distro` that we send them when running the e2e tests.

### How can we reproduce it (as minimally and precisely as possible)?

run the e2e tesets with node-os-distro=windows on EKS clusters, and then observe that some pods in the K8s sig-network tests dont get created properly... 

```
services-8729   up-down-1-242pg            0/1     ContainerCreating   0          40s   <none>           ip-192-168-56-14.ap-south-1.compute.internal    <none>           <none>
services-8729   up-down-1-5mvj9            1/1     Running             0          40s   192.168.42.158   ip-192-168-56-223.ap-south-1.compute.internal   <none>           <none>
services-8729   up-down-1-dxjjx            0/1     ContainerCreating   0          40s   <none>           ip-192-168-56-14.ap-south-1.compute.internal    <none>           <none>
services-8729   up-down-1-f557b            1/1     Running             0          40s   192.168.51.197   ip-192-168-56-223.ap-south-1.compute.internal   <none>           <none>

```

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
not all the images can run in all platforms, `agnhost` ones can, but there maybe some tests using other ones, we need to be careful to change only the ones that support those platforms

**Comment by jayunit100** [comment]
in terms of being careful though, what's the concern? 

in case that we say, use "Cassandra" as an image in an e2e test:
- It is guaranteed to fail in windows nodes
- If someone specifies "node-os-distro=windows" then it should only really try to test itself on windows nodes

Thus, if that Cassandra image were to fail after instituting this change, it would mean that the previous tests were "false positive" results due to heterogenous clusters (similar to heterogenous test results we used to get in cases where UDP didn't work on loopback, and 50% of tests would flake until).  

So it seems like no matter how careful we are - being more explicit about the honoring the nodeSelector for node-os-distro will give either more accurate tests, or tests which pass more uniformly on all mixed nodes clusters, or in the worst case: simply reduce variability in test results by causing mixed-os related test failures to become 100% passing or failing as opposed to flakey passes.
