### ISSUE TITLE
Export `loadConfigFromFile` as a public function `LoadConfigFromFile` 

### ISSUE THREAD

**Issue by vadasambar** [kubernetes/kubernetes#119056]
### What would you like to be added?

I want `loadConfigFromFile` to be exported as a public function `LoadConfigFromFile` 
https://github.com/kubernetes/kubernetes/blob/746b88c6ff442185589640885228ef100811083a/cmd/kube-scheduler/app/options/configfile.go#L33-L40
 

### Why is this needed?

* [Kubernetes cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) imports scheduler code and runs scheduler simulations for `Pending` pods to decide which nodegroup should be scaled up. 
* consider this case:
  1. a user is running a scheduler with custom scheduler config
  2. the user wants cluster-autoscaler to run scheduler simulations based on the custom scheduler config
 
For ii default scheduler config is used in cluster-autoscaler scheduler simulations. Right now, it is not possible to use custom scheduler config for cluster-autoscaler scheduler simulations  but I am working on a PR (https://github.com/kubernetes/autoscaler/pull/5708) to support this feature. For this feature, I need to parse scheduler config. [I have custom code based on `loadConfigFromFile`](https://github.com/kubernetes/autoscaler/pull/5708/files#diff-03046c2a86c17ed94a0d62f14449afb658d5a297113cbf894f3a1150858d0203R122-R141). It would help if we can have  `loadConfigFromFile` exported as `LoadConfigFromFile` (just like [`ValidateSchedulerConfiguration`](https://github.com/kubernetes/kubernetes/blob/746b88c6ff442185589640885228ef100811083a/pkg/scheduler/apis/config/validation/validation.go#L40)) so that programs which need to parse scheduler config can use the exported `LoadConfigFromFile` function directly instead of writing custom code.

**Comment by vadasambar** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/119057

**Comment by alculquicondor** [comment]
@x13n 
wdyt?
