### ISSUE TITLE
Component CLI help does not list which feature gates are relevant

### ISSUE THREAD

**Issue by nnlkcncff** [kubernetes/kubernetes#119132]
According to the documentation the feature gate "NodeOutOfServiceVolumeDetach" exists not only for kube-controller-manager, but for its activation you need to enable it only for kube-controller-manager. Is it necessary to activate it for kubelet, kube-apiserver, kube-proxy, kube-scheduler?

https://kubernetes.io/docs/concepts/architecture/nodes/#non-graceful-node-shutdown
If the NodeOutOfServiceVolumeDetachfeature gate is enabled on kube-controller-manager, and a Node is marked out-of-service with this taint, the pods on the node will be forcefully deleted if there are no matching tolerations on it and volume detach operations for the pods terminating on the node will happen immediately.

<br>

It's the same situation for "NodeSwap" feature gate.

https://kubernetes.io/docs/concepts/architecture/nodes/#swap-memory
To enable swap on a node, the NodeSwap feature gate must be enabled on the kubelet, and the --fail-swap-on command line flag or failSwapOn configuration setting must be set to false.

<br>

After analyzing it, its became clear that in the documentation the feature gate list is common to all control plane components, and the same list is found in output with `--help` parameter for each component. It's confusing.

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/

**Comment by neolit123** [comment]
> The gates were maintained in a single file in the upstream source code at that time (now scattered into several files), and that module (pkg/features) is shared by all components.

a couple of locations:
https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go
https://github.com/kubernetes/apiserver/blob/master/pkg/features/kube_features.go

one option would be to add labels in comments above FGs, that enumerate which components the FG applies to - e.g.:
```
// components: kube-apiserver,kubelet
```

that would mean someone needs to go through all the FGs and find their usage in component code.
this falls under sig-arch, as the umbrella owner of k8s features.

/sig architecture
/kind documentation feature

@nnlkcncff if you want more feedback you can ask in #sig-architecture on k8s slack.
or add it as agenda for the zoom meeting:
https://github.com/kubernetes/community/tree/master/sig-architecture#meetings

**Comment by nnlkcncff** [comment]
Based on your response, I assume that if the labels in the comments above feature gates are added, they will appear in the documentation afterward. But I don't understand is it expected that I could be a person who should go through all the FGs and find their usage in component code? I'm not sure that I'm the right person for this, but maybe I could give it a try.

Anyway, I want accurate documentation and to participate somehow, so I've done some analysis and ask you to pay attention at points 4, (maybe 6), 8 and 9 — maybe there is something wrong.

I, on the other hand, thanks to you, see a starting point in the source code from which I can begin my documentation of the relationship of components and feature flags.

> P.S. Please let me know explicitly if this should have been written in `#sig-architecture` or if I got it right, because right now I don't need more feedback, all I want to do is provide feedback.

<br>

It turned out that the code of all kubernetes components can be found in "https://github.com/kubernetes/kubernetes" repo, other repos are synced from it, in particular these ones:
 - https://github.com/kubernetes/component-base
 - https://github.com/kubernetes/api
 - https://github.com/kubernetes/apiserver
 - https://github.com/kubernetes/apiextensions-apiserver
 - https://github.com/kubernetes/controller-manager
 - https://github.com/kubernetes/kube-controller-manager
 - https://github.com/kubernetes/kube-scheduler
 - https://github.com/kubernetes/kubelet
 - https://github.com/kubernetes/kube-proxy

> Maybe you should consider using `git submodule` function for this kind of arrangement, but the main topic not about it, I just noticed this.

<br>

Because of that I swept through all the files in the main repo and found the ones related to feature gates — they don't exist for every component. I then compared them all by the feature gates they contain and checked every feature gate that isn't mentioned in the biggest file (which looks like the former main one):

 1. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/logs/api/v1/kube_features.go (this file contains only these FGs, it seems to be OK)
	- ContextualLogging (mentioned in the docs)
	- LoggingAlphaOptions (mentioned in the docs)
	- LoggingBetaOptions (mentioned in the docs)
 2. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/features/kube_features.go (this file contains only this FG, it seems to be OK)
	- ComponentSLIs (mentioned in the docs)
 3. https://github.com/kubernetes/kubernetes/blob/master/pkg/features/kube_features.go (the main file)
 4. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/features/kube_features.go **(this file contains other FGs too, which are in the main file for a reason "inherited features from generic apiserver, relisted here to get a conflict if it is changed  unintentionally on either side", maybe the following FGs should be listed too)**
	- APIServerIdentity (mentioned in the docs)
	- APIServerTracing (mentioned in the docs)
	- EfficientWatchResumption (mentioned in the docs, GA)
	- KMSv1 **(not mentioned in the docs)**
	- KMSv2 (mentioned in the docs)
	- RemainingItemCount (mentioned in the docs)
	- RemoveSelfLink (mentioned in the docs, GA)
	- StorageVersionAPI (mentioned in the docs)
	- StorageVersionHash (mentioned in the docs)
	- WatchBookmark (mentioned in the docs, GA)
	- WatchList (mentioned in the docs)
 5. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go (no FGs in this file, seems to be OK)
 6. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/controller-manager/pkg/features/kube_features.go **(all FGs from this file are mentioned in the main file)**

<br>

Also I checked every active feature gate from [the actual documentation](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/), which aren't found in any file:

 7. NetworkPolicyStatus (mentioned in the docs as Alpha, as removed in [the changelog v1.28](https://github.com/kubernetes/kubernetes/blob/986171d388e3b18a3ee2a2ef88683a1fb81d21b9/CHANGELOG/CHANGELOG-1.28.md?plain=1#L575), it seems to be OK)

 8. PodHasNetworkCondition **(mentioned in the docs as Alpha, found only in Markdown files, but not in the main file)**
 9. StableLoadBalancerNodeGet **(mentioned in the docs as Beta, found only in Markdown files, but not in the main file; there isn't any info about Alpha in docs)**
 10. UserNamespacesStatelessPodsSupport (mentioned in the docs as Alpha, renamed to "UserNamespacesSupport" according to [the changelog v1.28](https://github.com/kubernetes/kubernetes/blob/986171d388e3b18a3ee2a2ef88683a1fb81d21b9/CHANGELOG/CHANGELOG-1.28.md?plain=1#L575), it seems to be OK)
