### ISSUE TITLE
apiserver: rate-limit event reports

### ISSUE THREAD

**Issue by lavalamp** [kubernetes/kubernetes#11912]
Rogue kubelets can make N failure events (e.g., out of disk, can't mount secret, can't garbage collect) every poll loop, which can completely overload a kube-apiserver. We should rate limit these.

**Comment by dchen1107** [comment]
Marked it as V1.1-candidate for now. We might need this even sooner.

**Comment by dchen1107** [comment]
cc/ @saad-ali

**Comment by fabioy** [comment]
I think we'll need this sooner. Bad nodes can now overwhelm the master and cause it to start failing (OOM, etc).

**Comment by derekwaynecarr** [comment]
Are we going to rate limit how frequently Kubelet sends events or how many events the apiserver will consume or both?  Just worry that if we do it in the latter only that we will end up missing other valid events.

**Comment by fabioy** [comment]
We could start with a coalescing of duplicate events and see if that helps. A short wait (1-2 sec) to dedup multiple events could help. A more comprehensive rate-limiter would probably require some sort of back-off protocol between the master and nodes to avoid dropping important events.

**Comment by bprashanth** [comment]
The kubelet should be using a 5qps connection to talk to the apiserver

**Comment by abrutus** [comment]
+1 I started an RC that had a secret that was not previously created. This created a myriad of failed events, nodes ran out of space, and it effectively DOSed the API server. I was unable to issue any kubectl command because of this.

**Comment by jiangyaoguo** [comment]
Now we have made duplicate events comprehensive in event client. We can add rate limit for event recorder and set 5qps in kubelet.  @fabioy @bprashanth

**Comment by jiangyaoguo** [comment]
@lavalamp  I agree with @fabioy that don't update event immediately when receive duplicate events. We can wait for a short time for possible incoming duplicate events in kubelet.
