### ISSUE TITLE
[Failing Test] gce-master-scale-performance

### ISSUE THREAD

**Issue by mansikulkarni96** [kubernetes/kubernetes#119121]
### Which jobs are failing?

master-informing
gce-master-scale-performance

### Which tests are failing?

ClusterLoaderV2.load overall (testing/load/config.yaml)[Changes](https://github.com/kubernetes/kubernetes/compare/8f79a3d91...ce7fd466a?)
ClusterLoaderV2.load: [step: 07] Waiting for 'create objects' to be completed [00] -[Changes](https://github.com/kubernetes/kubernetes/compare/8f79a3d91...ce7fd466a?)
ClusterLoaderV2.load: [step: 22] Waiting for 'scale and update objects' to be completed [00] -[Changes](https://github.com/kubernetes/kubernetes/compare/8f79a3d91...ce7fd466a?)
ci-kubernetes-e2e-gce-scale-performance.Overall[Changes](https://github.com/kubernetes/kubernetes/compare/8f79a3d91...ce7fd466a?)
kubetest.ClusterLoaderV2[Changes](https://github.com/kubernetes/kubernetes/compare/8f79a3d91...ce7fd466a?)
<img width="1106" alt="Screenshot 2023-07-05 at 11 54 21 PM" src="https://github.com/kubernetes/kubernetes/assets/35242579/5433118d-f3bb-4da0-bf6d-a6f738053681">

### Since when has it been failing?

13:03 EDT 07/05/2023

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance

### Reason for failure (if possible)

ClusterLoaderV2: load overall (testing/load/config.yaml) 
`{ Failure :0 [measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 6 objects timed out: StatefulSets: test-jfqtza-3/medium-statefulset-0, test-jfqtza-14/medium-statefulset-0, test-jfqtza-26/medium-statefulset-0, test-jfqtza-29/small-statefulset-0, test-jfqtza-36/medium-statefulset-0, test-jfqtza-37/medium-statefulset-0 measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 6 objects timed out: StatefulSets: test-jfqtza-3/medium-statefulset-0, test-jfqtza-14/medium-statefulset-0, test-jfqtza-26/medium-statefulset-0, test-jfqtza-29/small-statefulset-0, test-jfqtza-36/medium-statefulset-0, test-jfqtza-37/medium-statefulset-0] :0} `
ClusterLoaderV2: load: [step: 07] Waiting for 'create objects' to be completed [00]
`{ Failure :0 [measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 6 objects timed out: StatefulSets: test-jfqtza-3/medium-statefulset-0, test-jfqtza-14/medium-statefulset-0, test-jfqtza-26/medium-statefulset-0, test-jfqtza-29/small-statefulset-0, test-jfqtza-36/medium-statefulset-0, test-jfqtza-37/medium-statefulset-0] :0}`
ClusterLoaderV2: load: [step: 22] Waiting for 'scale and update objects' to be completed [00] 
`{ Failure :0 [measurement call WaitForControlledPodsRunning - WaitForRunningStatefulSets error: 6 objects timed out: StatefulSets: test-jfqtza-3/medium-statefulset-0, test-jfqtza-14/medium-statefulset-0, test-jfqtza-26/medium-statefulset-0, test-jfqtza-29/small-statefulset-0, test-jfqtza-36/medium-statefulset-0, test-jfqtza-37/medium-statefulset-0] :0} `
e2e.go: ClusterLoaderV2 
`{  error during /home/prow/go/src/k8s.io/perf-tests/run-e2e.sh cluster-loader2 --experimental-gcp-snapshot-prometheus-disk=true --experimental-prometheus-disk-snapshot-name=ci-kubernetes-e2e-gce-scale-performance-1676637440141430784 --experimental-prometheus-snapshot-to-report-dir=true --nodes=5000 --prometheus-scrape-node-exporter --provider=gce --report-dir=/logs/artifacts --testconfig=testing/load/config.yaml --testconfig=testing/huge-service/config.yaml --testconfig=testing/access-tokens/config.yaml --testoverrides=./testing/experiments/enable_restart_count_check.yaml --testoverrides=./testing/experiments/ignore_known_gce_container_restarts.yaml --testoverrides=./testing/overrides/5000_nodes.yaml: exit status 1} `

### Relevant SIG(s)

/sig scalability
cc: @kubernetes/ci-signal

**Comment by aojea** [comment]
the subsequent run succeed and the last two runs are failing because of 

> 2023/07/06 08:24:13 main.go:328: Something went wrong: failed to prepare test environment: --provider=gce boskos failed to acquire project: resources not found

**Comment by mehabhalodiya** [comment]
@marseel @wojtek-t @shyamjvs can you please confirm if this is a blocker or not for (6th July) today's `1.28.0-alpha.4` release ASAP? Thank you!

**Comment by wojtek-t** [comment]
As confirmed on slack - definitely not a blocker.

**Comment by aojea** [comment]
last run worked https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance, if we have 3 consecutive greens and no failure I think we can close and reopen next time it happens
