### ISSUE TITLE
do cleanupPodUpdates if pod worker panic

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#119188]
### What happened?

pod will not be updated if pod worker panic occurred even there are new pod update event

### What did you expect to happen?

setup new pod worker if old pod worker panic when new pod event exist

### How can we reproduce it (as minimally and precisely as possible)?

1. make pod worker panic for specified pod (e.g. [panic occurred caused by some bug](https://github.com/kubernetes/kubernetes/pull/116504) )
2. update the specified pod
3. nothing happen to respond the update event

### Anything else we need to know?

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L947-L953
```
go func() {
			// TODO: this should be a wait.Until with backoff to handle panics, and
			// accept a context for shutdown
			defer runtime.HandleCrash()
                        defer cleanupPodUpdates(uid)
			defer klog.V(3).InfoS("Pod worker has stopped", "podUID", uid)
			p.podWorkerLoop(uid, outCh)
		}()
```

should call `cleanupPodUpdates` in defer

### Kubernetes version

<details>

```console
$ kubectl version
# master
```
</details>

### Cloud provider

<details>
NONE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by charles-chenzz** [comment]
can you be more specify on how you reproduce this bug? I want to reproduce it on my local to see what happen

**Comment by likakuli** [comment]
1. can use the version which not fixed this bug and create a pod without memory limit
2. then try to resize the pod
3. you will find there is a panic log in kubelet log

**Comment by likakuli** [comment]
sorry, my mistake. I just want to give a example how to make worker panic to trigger this issue. 
https://github.com/kubernetes/kubernetes/pull/116504 can trigger this, but not the only one which can trigger this issue. or there should be no handlecrash() here.

**Comment by likakuli** [comment]
it's different problem. what i care is when worker panic, kubelet should have a way to continue work. the reason why panic may be not only one.

**Comment by aojea** [comment]
> it's different problem. what i care is when worker panic, kubelet should have a way to continue work. the reason why panic may be not only one and my focus is not who cause the worker panic here.

heh, sorry, got it now , I think that it makes sense to handle the panic better , you should check with sig-node members but the fact that there is a TODO in that code sounds like is a really nice to have thing

**Comment by likakuli** [comment]
since kubelet will panic directly for currently master version when panic happened, close this issue.
