### ISSUE TITLE
What is the plan to support pod eviction on Windows

### ISSUE THREAD

**Issue by AbelHu** [kubernetes/kubernetes#119184]
### What happened?

In [Command line options for the kubelet](https://kubernetes.io/docs/concepts/windows/intro/#kubelet-compatibility), it mentions that pod eviction is not supported on Windows
Some kubelet command line options behave differently on Windows, as described below:
- Eviction by using --eviction-hard and --eviction-soft are not implemented

### What did you expect to happen?

Support pod eviction on Windows

### How can we reproduce it (as minimally and precisely as possible)?

No repro step since it is the limitation.

### Kubernetes version

All versions

### Cloud provider

All clouds

### OS version

Windows

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsturtevant** [comment]
We do support some types of eviction around PDB: https://testgrid.k8s.io/sig-windows-signal#capz-windows-containerd-nightly-master&include-filter-by-regex=Disruption

**Comment by jsturtevant** [comment]
Looking into this some of these do seem to work, the [Node Conditions](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#node-conditions) which maps [eviction signals](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#eviction-signals)

- DiskPresure - does work https://github.com/kubernetes/kubernetes/issues/103032#issuecomment-1099607903 Though there is a bug https://github.com/kubernetes/kubernetes/issues/116020
- PID Pressure - uses avaliable PIDS which is linux metric. So I don't know if this one makes sense (though maybe there is something else in Windows that could make sense)
- MemoryPresure - It was a long time ago but testing didn't show that memory pressure alert showed https://github.com/kubernetes/kubernetes/issues/73417#issuecomment-465466288. Might need to retest this to see if anything has changed

@AbelHu Do you have more info on what you would specifically like to see for this request?

**Comment by marosset** [comment]
Let's try and prioritize investigations for memory pressure eviction for v1.29

**Comment by zelenushechka** [comment]
Hello @marosset @AbelHu ! 👋🏼
Bug triage for the 1.29 release cycle is here!
This issue hasn't been updated for a long time, so I wanted to check what the status is. The code freeze will start ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751)), which is about 2 weeks from now. And while there is still plenty of time, we want to make sure that every PR has a chance to be merged on time.

As the issue is tagged for 1.29, is it still planned for that release?

**Comment by zelenushechka** [comment]
Hello @marosset and @AbelHu. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and I want to ensure that each PR has a chance to be merged and issues can be addressed.
Is this issue still targeting the 1.29 release?

**Comment by marosset** [comment]
I'm working on memory-based pod eviction on Windows now

**Comment by marosset** [comment]
/remove-lifecycle rotten
We have a PR open for memory based eviction on Windows and this is still being worked on

**Comment by vaibhav2107** [comment]
> We have a PR open for memory based eviction on Windows and this is still being worked on
@marosset Is this the PR you are talking about ? If this is the one and as it is merged now, so is this issue fixed by that PR ?

**Comment by jsturtevant** [comment]
This adds memory eviction support: https://github.com/kubernetes/kubernetes/pull/122922
/close
