### ISSUE TITLE
controller_util_test.go does not follow similar patterns as other unit tests in the repo.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#119133]
### What would you like to be added?

During implementation of KEP 3393 (PodReplacementPolicy for Jobs) we found that the unit tests of [controller_util_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils_test.go) do not follow common patterns established in k/k.  

1) The tests are not written using table driven design (https://dave.cheney.net/2019/05/07/prefer-table-driven-tests).

2) The tests use `Differences` rather than `Cmp.Diff`.

This probably should be done as two separate PRs but wanted to highlight some areas that could use some cleanup. 

### Why is this needed?

https://github.com/kubernetes/kubernetes/pull/117015#discussion_r1254470573

Not using `Cmp.Diff` means that we don't see diffs in the unit tests that makes this difficult.  

And not using table driven tests makes it difficult to add new test cases as it usually is brought up during review that we should use a table-driven test but the entire file does not obey this format.

**Comment by kaisoz** [comment]
I'd like to work on it 😊 

/assign

**Comment by xuexu6666** [comment]
@kaisoz 

Looks like this need two PRs. 

1. The tests are not written using table driven design (https://dave.cheney.net/2019/05/07/prefer-table-driven-tests).
2. The tests use Differences rather than Cmp.Diff.

I think I can work on the 2nd one and leave the 1st one to you. Sounds good?

**Comment by xuexu6666** [comment]
@kannon92 

By looking through the [gc_controller_test.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podgc/gc_controller_test.go), I found the main function to comapre the results have already used cmp.Diff. Can you elaborate more on which part you expect to use cmp.Diff?

func verifyDeletedAndPatchedPods(t *testing.T, client *fake.Clientset, wantDeletedPodNames, wantPatchedPodNames sets.String) {
	t.Helper()
	deletedPodNames := getDeletedPodNames(client)
	if diff := **cmp.Diff**(wantDeletedPodNames, deletedPodNames); diff != "" {
		t.Errorf("Deleted pod names (-want,+got):\n%s", diff)
	}
	patchedPodNames := getPatchedPodNames(client)
	if diff := **cmp.Diff**(wantPatchedPodNames, patchedPodNames); diff != "" {
		t.Errorf("Patched pod names (-want,+got):\n%s", diff)
	}
}

**Comment by kannon92** [comment]
I am really sorry about this.  Too much multitasking!!

I meant https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils_test.go not gc_controller_test.go.

**Comment by kaisoz** [comment]
Hey @xuexu6666 ! Sorry, I didn't see this before. 

No problem at all, but consider that one change depends on the other, and since my task implies a big refactor, there might be conflicts when merging your PR... That's why I see two possible scenarios happening:

- Your PR gets merged before I raise mine: Then fine, I'll rebase your changes and adapt my code 😊 
- Mine is ready before yours is merged: In this case, I propose you commit your changes to my PR. Both of us will appear as coauthors of the change

Getting a PR merged in the Kubernetes project takes quite some time (trust me, I talk by experience and @kannon92 can confirm 😆 ) 

WDYT?

**Comment by xuexu6666** [comment]
@kaisoz Let's see how it goes. We can always rebase the code change to adapt new.

**Comment by xuexu6666** [comment]
@kaisoz btw, did you already begin to work on task 1? If not, I may just go ahead and work on it right away since I have already dig into it.

**Comment by kaisoz** [comment]
@xuexu6666 yes, I already started 😊 And If you ask me, better to keep it this way so we both have an opportunity to have a contribution

**Comment by xuexu6666** [comment]
@kaisoz cool. Sounds good.

**Comment by biswajit-9776** [comment]
Hi @kannon92, if this issue needs to be worked on any further, please assign me for the same.

**Comment by kannon92** [comment]
@kaisoz has a PR up that will solve the second part of this issue.
