### ISSUE TITLE
Unable to deploy cluster on machine.

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#11916]
Hi,
I'm trying to deploy the kubernetes cluster on a openstack instance( in a virtual environment). I have used the internal IP for the configuration but this is what I'm facing.

root@master:/home/ubuntu/kubernetes/cluster# ssh-agent >agent.sh
root@master:/home/ubuntu/kubernetes/cluster# source agent.sh
Agent pid 1440
root@master:/home/ubuntu/kubernetes/cluster# ssh-add /home/ubuntu/kubernetes/cluster/key
Identity added: /home/ubuntu/kubernetes/cluster/key (/home/ubuntu/kubernetes/cluster/key)

root@master:/home/ubuntu/kubernetes/cluster# vi ubuntu/config-default.sh
root@master:/home/ubuntu/kubernetes/cluster# KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
... calling kube-up
Deploying master and minion on machine 20.20.0.158

Permission denied (publickey).

root@master:/home/ubuntu/kubernetes/cluster# sudo KUBERNETES_PROVIDER=ubuntu ./kube-up.sh
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Could not find or add an SSH identity.
Please start ssh-agent, add your identity, and retry.

I have created the key, modified to 600 permission, identity agent was created and added as you can see above. I'm at loss as to why it says permission denied.

**Comment by Naresht-vedams** [comment]
Run this below commands
`eval "$(ssh-agent)"`
`ssh-add admin-key.pem`

**Comment by mbforbes** [comment]
@adyanthaya17 did https://github.com/kubernetes/kubernetes/issues/11916#issuecomment-126578795 solve your problem?

**Comment by mbforbes** [comment]
Preemptively closing, but please re-open if your problem persists?

**Comment by rajnemani** [comment]
I still have this issue.  I am trying to setup both master and minion on a ubuntu VM following this 
http://kubernetes.io/v1.0/docs/getting-started-guides/ubuntu.html
getting stuck here

user@raj-hackfest-2:~/kubernetes/cluster$ KUBERNETES_PROVIDER=ubuntu ./kube-up.sh 
... Starting cluster using provider: ubuntu
... calling verify-prereqs
Identity added: /home/user/.ssh/id_rsa (/home/user/.ssh/id_rsa)
... calling kube-up
Deploying master and minion on machine <PUBLIC IP of the machine>

Permission denied (publickey).

any help is appreciated.

**Comment by wapolinar** [comment]
The SSH client is trying to make a connection to the master and the nodes by using the ssh key of the current user. SSH is used even when the master is localhost!

This requires the public key of the current user to be in the authorized_keys file of the user that is mentioned in the "export nodes" statement. In the case of the ubuntu guide, the user name is "vcap" and the file would be /home/vcap/.ssh/authorized_keys. Include the pubkey (e.g., id_rsa.pub) to the authorized_keys file and the command should execute without problems.
