### ISSUE TITLE
The hack/update-translations.sh script execution error

### ISSUE THREAD

**Issue by Fish-pro** [kubernetes/kubernetes#119120]
### What happened?

The following error was reported when the script was executed to export the translation template

```shell
➜  kubernetes git:(master) ✗ hack/update-translations.sh -x
Extracting strings to POT
panic: staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go:127:28: expected ';', found '[' (and 1 more errors)

goroutine 1 [running]:
main.processSingleGoSource(0xc0000b0080, {0x7ffeefbfe11f, 0x31})
        /Users/york/go/pkg/mod/github.com/gosexy/gettext@v0.0.0-20160830220431-74466a0a0c4a/go-xgettext/main.go:232 +0x105
main.processFiles({0xc0000a0310, 0x60, 0xc00009fc00})
        /Users/york/go/pkg/mod/github.com/gosexy/gettext@v0.0.0-20160830220431-74466a0a0c4a/go-xgettext/main.go:215 +0xae
main.main()
        /Users/york/go/pkg/mod/github.com/gosexy/gettext@v0.0.0-20160830220431-74466a0a0c4a/go-xgettext/main.go:344 +0xce
➜  kubernetes git:(master) ✗ 
```

Execute prompt error problem code location

https://github.com/kubernetes/kubernetes/blob/cd32adebd9d52ae46827054350c17de085a4eb23/staging/src/k8s.io/kubectl/pkg/cmd/apply/apply.go#L127

### What did you expect to happen?

The.pot file was successfully executed and exported

### How can we reproduce it (as minimally and precisely as possible)?

gettext extracts adaptation problems

### Kubernetes version

<details>

```console
$ git branch
*master
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
I run on the current master branch. And no err to me.

- We prefer to use the generic set now. What golang version are used in your local env?

**Comment by Fish-pro** [comment]
> I run on the current master branch. And no err to me.
> 
> * We prefer to use the generic set now. What golang version are used in your local env?

@pacoxu Thanks for reply，here is my version of go
```
➜  kubernetes git:(master) go version
go version go1.20 darwin/amd64

```

**Comment by carlory** [comment]
I can not reproduce this issue too. 

```
(⎈|kind-firefly:N/A)➜  kubernetes git:(master) ✗ go version
go version go1.20.5 darwin/arm64
(⎈|kind-firefly:N/A)➜  kubernetes git:(master) ✗ hack/update-translations.sh -x
Extracting strings to POT
```

**Comment by z1cheng** [comment]
@Fish-pro You can try deleting and re-cloning the whole repo, maybe just because of the local cache :)

**Comment by Fish-pro** [comment]
@carlory @z1cheng Thanks~. I'll try again

**Comment by Fish-pro** [comment]
The problem is with the go-xgettext version. After upgrading to the latest version, the script is executed successfully
