### ISSUE TITLE
kubelet applies defaults to Pods and causes could not process manifest file

### ISSUE THREAD

**Issue by YTGhost** [kubernetes/kubernetes#119135]
### What happened?

When I put a Pod yaml file without `metadata.name` in `/etc/kubernetes/manifests`, started the kubelet and hoped it would create the corresponding staticPod for me, I got the following error, which also caused the staticPod to not be created.

```
Jul 06 22:46:02 cloud kubelet[2930835]: E0706 22:46:02.905289 2930835 file.go:187] "Could not process manifest file" err="invalid pod: [metadata.name: Invalid value: \"-cloud\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]" path="/etc/kubernetes/manifests/yurthub.yaml"
```

I then read the kubelet code and quickly found the problem. When kubelet tries to decode the pod yaml file, it will apply default values and validate the pod. The function to apply the defaults is in `pkg/kubelet/config/common.go L56`.

In this function, the `metadata.name` is set.

```go
pod.Name = generatePodName(pod.Name, nodeName)

// Generate a pod name that is unique among nodes by appending the nodeName.
func generatePodName(name string, nodeName types.NodeName) string {
	return fmt.Sprintf("%s-%s", name, strings.ToLower(string(nodeName)))
}
```

This causes an error when `metadata.name` is not set, because it causes the '-' character to be at the front.

I think kubelet should circumvent this error, because `metadata.name` is optional, It is possible for this field not to be set.

### What did you expect to happen?

When Pod's `metadata.name` is not set, the '-' character at the start should be avoided, as it will cause an error.

### How can we reproduce it (as minimally and precisely as possible)?

Prepare a Pod yaml file without `metadata.name` and set it into `/etc/kubernetes/manifests`.

### Anything else we need to know?

If the maintainers think this circumvention change is necessary, I'm happy to contribute code to the kubelet!

### Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Alibaba Cloud Linux"
VERSION="3 (Soaring Falcon)"
ID="alinux"
ID_LIKE="rhel fedora centos anolis"
VERSION_ID="3"
PLATFORM_ID="platform:al8"
PRETTY_NAME="Alibaba Cloud Linux 3 (Soaring Falcon)"
ANSI_COLOR="0;31"
HOME_URL="https://www.aliyun.com/"
$ uname -a
Linux cloud 5.10.134-14.al8.x86_64 #1 SMP Thu Apr 27 16:46:29 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>
using kubeadm
</details>


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by daniel-hutao** [comment]
I would like to open a PR to fix this issue, can I be assigned?

**Comment by YTGhost** [comment]
> I would like to open a PR to fix this issue, can I be assigned?

If the maintainer thinks this should be fixed, I want it fixed by myself:)

**Comment by daniel-hutao** [comment]
OK

**Comment by aojea** [comment]
I do not know if a pod without name should be considered valid

Please discuss with sig-node before doing anything to understand what is a valid solution for this problem

/cc @SergeyKanzhelev @bobbypage

**Comment by SergeyKanzhelev** [comment]
names are needed for the Pod. I think the correct fix for this issue will be to add validation for static Pods to have a name. This validation is OK to add since Pods without names are not working anyways because of this bug.

**Comment by YTGhost** [comment]
> names are needed for the Pod. I think the correct fix for this issue will be to add validation for static Pods to have a name. This validation is OK to add since Pods without names are not working anyways because of this bug.

@SergeyKanzhelev Okay, I will submit a PR to add validation for static Pods to have a name.

**Comment by YTGhost** [comment]
> names are needed for the Pod. I think the correct fix for this issue will be to add validation for static Pods to have a name. This validation is OK to add since Pods without names are not working anyways because of this bug.

@SergeyKanzhelev Hey, I found out that kubelet will apply default value first and then validate the pod. Do you mean to let me add a single validation for static Pods to have a name before applying default value?

**Comment by DivineHell** [comment]
> names are needed for the Pod. I think the correct fix for this issue will be to add validation for static Pods to have a name. This validation is OK to add since Pods without names are not working anyways because of this bug.

hi @SergeyKanzhelev  and @YTGhost,

If modified according to this logic, it seems that the current code is fine.

Current logic:
1.  it will use the old pod.Name to generate the new pod.Name
pkg/kubelet/config/common.go:
`func applyDefaults(pod *api.Pod, source string, isFile bool, nodeName types.NodeName) error {
        ...
	pod.Name = generatePodName(pod.Name, nodeName)`
2. Next, in ValidatePodCreate, it will validate pod name. The pod.Name is already to new pod.Name
k8s.io/apimachinery/pkg/api/validation/objectmeta.go:
`func ValidateObjectMetaAccessor(meta metav1.Object, requiresNamespace bool, nameFn ValidateNameFunc, fldPath *field.Path) field.ErrorList {
        ...
	if len(meta.GetName()) == 0 {
		allErrs = append(allErrs, field.Required(fldPath.Child("name"), "name or generateName is required"))
	} else {
		for _, msg := range nameFn(meta.GetName(), false) {
			allErrs = append(allErrs, field.Invalid(fldPath.Child("name"), meta.GetName(), msg))
		}
	}`
3. In this case, the original pod does not have a name and will also be recognized. It's just that it's identified with a validation prefixed with "-".

The logic of the current validation will recognize the pod without a name. In this way, is it necessary to improve the error information?
