### ISSUE TITLE
Issue while trying to bring up a local cluster using hack/local-up-cluster.sh

### ISSUE THREAD

**Issue by mansi1597** [kubernetes/kubernetes#119245]
### What happened?

I am trying to bring up a local cluster to test e2e tests. I am facing following error: time out on waiting 127.0.0.1 exist

I am running this script inside WSL2 Ubuntu.

mansi:~/go/src/k8s.io/kubernetes$ sudo env "PATH=$PATH" hack/local-up-cluster.sh
make: Entering directory '/home/mansi/go/src/k8s.io/kubernetes'
+++ [0712 11:27:23] Setting GOMAXPROCS: 8
+++ [0712 11:27:24] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kubectl (static)
    k8s.io/kubernetes/cmd/kube-apiserver (static)
    k8s.io/kubernetes/cmd/kube-controller-manager (static)
    k8s.io/kubernetes/cmd/cloud-controller-manager (non-static)
    k8s.io/kubernetes/cmd/kubelet (non-static)
    k8s.io/kubernetes/cmd/kube-proxy (static)
    k8s.io/kubernetes/cmd/kube-scheduler (static)
make: Leaving directory '/home/mansi/go/src/k8s.io/kubernetes'
API SERVER secure port is free, proceeding...
Detected host and ready to start services.  Doing some housekeeping first...
Using GO_OUT /home/mansi/go/src/k8s.io/kubernetes/_output/local/bin/linux/amd64
Starting services now!
Starting etcd
etcd --advertise-client-urls http://127.0.0.1:2379 --data-dir /tmp/tmp.lyraK3o1Kl --listen-client-urls http://127.0.0.1:2379 --log-level=warn 2> "/tmp/etcd.log" >/dev/null
Waiting for etcd to come up.
+++ [0712 11:27:54] On try 2, etcd: : {"health":"true","reason":""}
{"header":{"cluster_id":"14841639068965178418","member_id":"10276657743932975437","revision":"2","raft_term":"2"}}..+....+..+.+...+++++
2023/07/12 11:27:58 [INFO] generate received request
2023/07/12 11:27:58 [INFO] received CSR
2023/07/12 11:27:58 [INFO] generating key: rsa-2048
2023/07/12 11:27:58 [INFO] encoded CSR
2023/07/12 11:27:58 [INFO] signed certificate with serial number <>
2023/07/12 11:27:58 [INFO] generate received request
2023/07/12 11:27:58 [INFO] received CSR
2023/07/12 11:27:58 [INFO] generating key: rsa-2048
2023/07/12 11:27:59 [INFO] encoded CSR
2023/07/12 11:27:59 [INFO] signed certificate with serial number <>
2023/07/12 11:27:59 [INFO] generate received request
2023/07/12 11:27:59 [INFO] received CSR
2023/07/12 11:27:59 [INFO] generating key: rsa-2048
2023/07/12 11:27:59 [INFO] encoded CSR
2023/07/12 11:27:59 [INFO] signed certificate with serial number <>
2023/07/12 11:27:59 [INFO] generate received request
2023/07/12 11:27:59 [INFO] received CSR
2023/07/12 11:27:59 [INFO] generating key: rsa-2048
2023/07/12 11:28:00 [INFO] encoded CSR
2023/07/12 11:28:00 [INFO] signed certificate with serial number <>
Waiting for apiserver to come up
+++ [0712 11:28:04] On try 5, apiserver: : ok
clusterrolebinding.rbac.authorization.k8s.io/kube-apiserver-kubelet-admin created
clusterrolebinding.rbac.authorization.k8s.io/kubelet-csr created
Cluster "local-up-cluster" set.
use 'kubectl --kubeconfig=/var/run/kubernetes/admin-kube-aggregator.kubeconfig' to use the aggregated API server
serviceaccount/coredns created
clusterrole.rbac.authorization.k8s.io/system:coredns created
clusterrolebinding.rbac.authorization.k8s.io/system:coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
coredns addon successfully deployed.
Checking CNI Installation at /opt/cni/bin
WARNING : The kubelet is configured to not fail even if swap is enabled; production deployments should disable swap unless testing NodeSwap feature.
2023/07/12 11:28:06 [INFO] generate received request
2023/07/12 11:28:06 [INFO] received CSR
2023/07/12 11:28:06 [INFO] generating key: rsa-2048
2023/07/12 11:28:06 [INFO] encoded CSR
2023/07/12 11:28:06 [INFO] signed certificate with serial number <>
kubelet ( 28006 ) is running.
wait kubelet ready
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
No resources found
**time out on waiting 127.0.0.1 exist**
Cleaning up...

### What did you expect to happen?

Expected localcluster to come up with 1 node

### How can we reproduce it (as minimally and precisely as possible)?

Clone kubernetes and setup development environment.
run /go/src/k8s.io/kubernetes$ sudo env "PATH=$PATH" hack/local-up-cluster.sh

### Kubernetes version

1.27.0

### Cloud provider

local

### OS version

WSL2 Ubuntu

**Comment by saschagrunert** [comment]
Hey @mansi1597, do you have a container runtime (CRI-O/containerd) up and running on the node?

Can you share the kubelet logs from `/tmp/kubelet.log`?

**Comment by mansi1597** [comment]
Hi @saschagrunert, Thanks for the reply. My containerd configuration was not correct. It worked now.
 Thanks

**Comment by ilyazr** [comment]
@mansi1597 Hi! I have a similar problem. Can you share correct configuration for containerd?

**Comment by darkin424** [comment]
Hey i faced same issue have reached but couldn't find any solution! Can you share the what helped with Containerd?

**Comment by bouaouda-achraf** [comment]
- check if your containerd service is running properly 
- check  env var CONTAINER_RUNTIME_ENDPOINT 
ref https://github.com/kubernetes/community/blob/master/contributors/devel/running-locally.md#starting-the-cluster
