### ISSUE TITLE
No resources found in namespace

### ISSUE THREAD

**Issue by cedvict** [kubernetes/kubernetes#119221]
### What happened?

Hello guys

I have an error when I request the kubernetes api.
I installed ELK components on the cluster when I query the cluster to see the objects created I get "No resources found in elastic-system namespace"

![image](https://github.com/kubernetes/kubernetes/assets/8941921/7bb6c872-69c4-4aa4-a402-74e83465ff06)

### What did you expect to happen?

![image](https://github.com/kubernetes/kubernetes/assets/8941921/ec245884-c028-46ec-9ed9-74f1374ab49c)

### How can we reproduce it (as minimally and precisely as possible)?

I had to install ELK and delete for a configuration defect and I recreated. At the first creation, I did not check if the objects were visible in the namespace or not

### Kubernetes version

<details>

```console
$ kubectl version --short
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.27.3
```

</details>

### Cloud provider

<details>
on premise
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
# Linux kubevm01.uman.test 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
crossplane
certmanager
nginx ingress controller

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
Calico v3.26.1
</details>

**Comment by tamilselvan1102** [comment]
You can check the resources by running this command:
kubectl -n elastic-system get all

**Comment by cedvict** [comment]
Already check using this command kubectl -n elastic-system get all. I always get no resources found in elastic-system namespace.

**Comment by cedvict** [comment]
Thanks @tamilselvan1102 for your time. The error comes from operator eck operator
