### ISSUE TITLE
kubelet could not perceive volume force detached&attached for the same node causes globalmount io error

### ISSUE THREAD

**Issue by 249043822** [kubernetes/kubernetes#119273]
### What happened?

this case is as follows:
1.  create a statefulset with terminationGracePeriod:0 and node selector: minion-0
2.  disconnect network from minion-0 to master
3.  minion-0 became not ready and after several minutes,  the pod was deleted, and the pv was detached from minion-0
4.  recover the network
5.  minion-0 became ready, and the pod was scheduled to minion-0 again, and at the same time, kubelet received old pod removed
6.  the pv was attached to minion-0 again, the kubelet umount volume for old pod, and mount volume for new pod, as the new pod use the same volume, kubelet did not call umountDevice and also did not call mountDevice
7. but as the volume was detached before,  the globalmount now is abnormal,   the kubelet could not sense this change

/cc @gnufied @jingxu97 @jsafrane 

### What did you expect to happen?

kubelet could call mountDevice again even the asw show the volume device is `DeviceGlobalMounted ` while volume detached&attached before

### How can we reproduce it (as minimally and precisely as possible)?

above

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2023-06-28T13:46:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"archive", BuildDate:"2023-06-28T13:46:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsafrane** [comment]
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", 

1.22 is not a supported release.

> 1. create a statefulset with terminationGracePeriod:0 and node selector: minion-0
> 2. disconnect network from minion-0 to master
> 3. minion-0 became not ready and after several minutes, the pod was deleted, and the pv was detached from minion-0

Who deletes the pod? I've been waiting for an hour and I don't see anything deleted.

If you force-delete a pod manually or via 3rd party controller / mechanism, you must count with the consequences. In this case, it causes inconsistency between kubelet (that can't read the API server and thinks that the volume is attached) and KCM (that sees the pod deleted and detaches the volume). The easiest way to fix the inconsistency is to reboot the node.

> /assign

Please do not assign issues to random people without their agreement. It gives impression that someone is working on them, while nobody really is. Someone else might pick an unassigned issue and fix it instead.

/unassign @jsafrane 
/unassign @gnufied 
/unassign @jingxu97

**Comment by 249043822** [comment]
minion not ready, the nodelifecyclecontroller will delete the pods on the node base on taintsmanager to trigger pods migration

**Comment by jsafrane** [comment]
Does nodelifecyclecontroller force-delete pods? I thought it was only when the node is tainted with `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` and it should be set only when the node is down. At least in Kubernetes 1.24 and newer.

**Comment by 249043822** [comment]
> Does nodelifecyclecontroller force-delete pods? I thought it was only when the node is tainted with `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` and it should be set only when the node is down. At least in Kubernetes 1.24 and newer.

Yea, because the sts set terminationGracePeriod:0, it's same with force-delete

**Comment by jsafrane** [comment]
Sorry, I missed you response.

> Yea, because the sts set terminationGracePeriod:0, it's same with force-delete

You're right, with  `pod.spec.terminationGracePeriod: 0` the pod gets force deleted without unmount confirmation from kubelet. That's unexpected and bad. Even with 1 second of `terminationGracePeriod`, the Pod is not deleted until all its volumes are unmounted, with 0 it's just force deleted without unmounts, potentially corrupting data on mounted volumes. I'd suggest using nozero `terminationGracePeriod` if you prefer your data not corrupted.

And on the positive side, even with force-deleted pods, [NewVolumeManagerReconstruction](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/3756-volume-reconstruction) feature should ensure that UnmountDevice / MountDevice is called at step 6. in the issue description. It's beta and on-by-default in Kubernetes 1.28, I'm hesitant to backport such a change lot of code to older release - it's quite lot of code and I've broken 1.27 once already.

There are [attempts to fix a similar issue](https://github.com/kubernetes/kubernetes/pull/119827) in the old volume code and backport it.

**Comment by jsafrane** [comment]
/close

I'm closing this one, either use NewVolumeManagerReconstruction or follow up in https://github.com/kubernetes/kubernetes/pull/119827
