### ISSUE TITLE
NPD jobs are failing: "No URLs matched: gs://node-problem-detector-staging/ci/ci.env"

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#119210]
### Which jobs are failing?

Several NPD CI jobs are failing:

Job name | Config source | Testgrid link
----|----|----
`ci-npd-e2e-kubernetes-gce-gci` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L127) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci
`ci-npd-e2e-kubernetes-gce-gci-custom-flags` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L172) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-gci-custom-flags
`ci-npd-e2e-kubernetes-gce-ubuntu` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L217) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-ubuntu
`ci-npd-e2e-kubernetes-gce-ubuntu-custom-flags` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L262) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-kubernetes-gce-ubuntu-custom-flags
`ci-npd-e2e-node` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L73) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-e2e-node

### Which tests are failing?

These jobs fail to build, these are the logs in all cases:
```
Activated service account credentials for: [prow-build@k8s-infra-prow-build.iam.gserviceaccount.com]
+ WRAPPED_COMMAND_PID=28
+ wait 28
+ bash -c './test/build.sh get-ci-env && source ci.env && /workspace/scenarios/kubernetes_e2e.py --cluster= --extract=ci/latest --provider=gce --gcp-node-image=gci --gcp-zone=us-west1-b --ginkgo-parallel=30 --test_args=--ginkgo.focus=NodeProblemDetector --timeout=60m'
CommandException: No URLs matched: gs://node-problem-detector-staging/ci/ci.env
+ EXIT_VALUE=1
+ set +o xtrace
```

### Since when has it been failing?

2023-07-08 ~05:20 AM PDT.

In the case of jobs `ci-npd-e2e-kubernetes-gce-ubuntu`, `ci-npd-e2e-kubernetes-gce-ubuntu-custom-flags`, and `ci-npd-e2e-node`, they were failing before. However, they switched to the same error as the other jobs recently.

### Anything else we need to know?

These jobs were recently migrated from the default cluster to EKS, but it caused them to fail. Therefore, they were changed back in https://github.com/kubernetes/test-infra/pull/30000. I don't think the "rollback" is the culprit, as it was merged on 2023-07-05 and tests started failing 3 days after that.

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/close

caused by https://github.com/kubernetes/kubernetes/issues/119211
