### ISSUE TITLE
Default load balancing when using NodePort services

### ISSUE THREAD

**Issue by martinstraesser** [kubernetes/kubernetes#119228]
### What happened?

/sig network
/kind support

I am trying to understand how Kubernetes does load balancing when using NodePort services (I am explicitely not referring to cloud provider load balancers). I created the following setup:

- 5 worker nodes ( `worker1`, `worker2`, `worker3`, `worker4`, `worker5` )
- 1 master node ( `master` )

I created a deployment with 5 replica pods, scheduled in a way that each of the worker nodes hosts 1 pod. I use a NodePort service (port `30500`) to expose the pods for external requests. I now send requests from an external device to the master node ( `master:30500` )

### What did you expect to happen?

From the [source code](https://github.com/kubernetes/kubernetes/blob/0ae9aaacfa217b18652f34d6ef29f08a15851b0a/pkg/proxy/ipvs/proxier.go#L87) and other websites, I expected round-robin load balancing. 

I tested different load intensities (requests per second). The result was always the same: the pod that processes the request seemed to be selected randomly.  My question is why and is it intended behavior?

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce just use any kind of container that is able to process load requests, deploy multiple replicas on different nodes and send requests from an external device.

### Kubernetes version

<details>
Kubernetes version v1.27.2

</details>

### Cloud provider

<details>
None, bare-metal
</details>

### OS version

<details>

Ubuntu 18.04

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel
</details>

**Comment by aojea** [comment]
> I tested different load intensities (requests per second). The result was always the same: the pod that processes the request seemed to be selected randomly. My question is why and is it intended behavior?

it is the expected behavior https://github.com/kubernetes/kubernetes/issues/37932#issuecomment-264950788 , however, this may vary depending on the Services proxy implementation, ipvs has much reacher features per example to choose the LB algorithm, but IIRC those knobs are not exposed

Cilium uses random too https://gist.github.com/aojea/5f82db3ba5f1efd59bb73f4b28614a6a

/close

**Comment by martinstraesser** [comment]
Thanks for the references and clarification!

**Comment by aojea** [comment]
feel free to reopen if you have more questions or something is unclear, but I think that this covers it ;)
