### ISSUE TITLE
No kubelet_volume* in kubelet metrics

### ISSUE THREAD

**Issue by LynnWonder** [kubernetes/kubernetes#119275]
### What happened?

![image](https://github.com/kubernetes/kubernetes/assets/37785330/9a52c1b7-45db-428c-8c47-9b6b58d73b7c)
There are no metrics like kubelet_volume_stats_available_bytes in kubelet metrics

### What did you expect to happen?

metrics like kubelet_volume_stats_available_bytes should be available in /10250/metrics.

### How can we reproduce it (as minimally and precisely as possible)?

Kubernetes v1.19.16

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by tamilselvan1102** [comment]
metrics-server only provides node and pod level metrics

**Comment by LynnWonder** [comment]
@tamilselvan1102 fyi https://github.com/kubernetes/kubernetes/blob/v1.19.16/pkg/kubelet/metrics/metrics.go#L51
