### ISSUE TITLE
Add net.ipv4.tcp_fin_timeout, net.ipv4.tcp_keepalive_intvl, net.ipv4.tcp_keepalive_probes as safe sysctl

### ISSUE THREAD

**Issue by leeparayno** [kubernetes/kubernetes#119263]
### What would you like to be added?

Add the following to be safe sysctls:

net.ipv4.tcp_fin_timeout
net.ipv4.tcp_keepalive_intvl
net.ipv4.tcp_keepalive_probes

These are related settings to net.ipv4.tcp_keepalive_time that was enabled in https://github.com/kubernetes/kubernetes/issues/117873

### Why is this needed?

These are related ipv4 TCP settings for tuning network connections between a client and a pod.

**Comment by HirazawaUi** [comment]
May you help provide some tests to ensure that setting this sysctl can't affect any other pods or the node.
/sig nodes

**Comment by HirazawaUi** [comment]
sig/node

**Comment by vsxen** [comment]
I adjusted it with the  `tuning`  plugin.
https://www.cni.dev/plugins/current/meta/tuning/

**Comment by leeparayno** [comment]
@HirazawaUi Would this change apply at the node level or the pod level? I assumed it would be at the pod level, and should not affect any other pods--however Kubernetes does not natively have any limits on network connections that I am aware of--but only the pod with the changed net settings would be affected.

**Comment by HirazawaUi** [comment]
> @HirazawaUi Would this change apply at the node level or the pod level? I assumed it would be at the pod level, and should not affect any other pods--however Kubernetes does not natively have any limits on network connections that I am aware of--but only the pod with the changed net settings would be affected.

To verify that a sysctl has an effect on other pods, we need to verify that it's a namespace sysctl.

**Comment by HirazawaUi** [comment]
Here's a simple test

Use net.ipv4.tcp_fin_timeout sysctl to create a container
```
sudo docker run --rm --sysctl=net.ipv4.tcp_fin_timeout=35 -it busybox /bin/sh
/ # cat /proc/sys/net/ipv4/tcp_fin_timeout
35
```
check if it set on the host  => It is the default value on host
```
➜  ~ cat /proc/sys/net/ipv4/tcp_fin_timeout
60
```
run another container attach to the network namespace of the one where the sysctl is set => results in sysctl being set
```
➜  ~ sudo docker run --rm --net container:6c24a27f52cb busybox cat /proc/sys/net/ipv4/tcp_fin_timeout
35
```
Verify in another container under a different network namespace that it is not set =>  It is the default value
```
➜  ~ sudo docker run --rm busybox cat /proc/sys/net/ipv4/tcp_fin_timeout
60
```

**Comment by HirazawaUi** [comment]
I likewise verified `net.ipv4.tcp_keepalive_intvl` and `net.ipv4.tcp_keepalive_probes`, which are also namespaced sysctl, and I believe we can add them to the safe sysctl

/assign

**Comment by HirazawaUi** [comment]
Probably need to wait for #118846 to finish before start working on it
