### ISSUE TITLE
NPD jobs are failing: "failed to push gcr.io/node-problem-detector-staging/ci/node-problem-detector [...] 403 Forbidden"

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#119211]
### Which jobs are failing?

Job name | Config source | Testgrid (or job history) link
----|----|----
`ci-npd-build` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-ci.yaml#L2) | https://testgrid.k8s.io/sig-node-node-problem-detector#ci-npd-build
`pull-npd-e2e-test` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-presubmits.yaml#L214) | https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-npd-e2e-test
`pull-npd-e2e-node` | [Source](https://github.com/kubernetes/test-infra/blob/68864df0573a1c439ef610d32a051b766f6bd6b1/config/jobs/kubernetes/node-problem-detector/node-problem-detector-presubmits.yaml#L70) | https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-npd-e2e-node

### Which tests are failing?

Jobs fail to start. The container image is built but it fails on push with the following error:
```
#33 pushing layers
#33 ...
#34 [auth] node-problem-detector-staging/ci/node-problem-detector:pull,push token for gcr.io
#34 DONE 0.0s
#33 exporting to image
#33 pushing layers 1.4s done
#33 ERROR: failed to push gcr.io/node-problem-detector-staging/ci/node-problem-detector:v0.8.13-44-g5558643-20230710.1614: failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
------
 > exporting to image:
------
ERROR: failed to solve: failed to push gcr.io/node-problem-detector-staging/ci/node-problem-detector:v0.8.13-44-g5558643-20230710.1614: failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden
make: *** [Makefile:270: push-container] Error 1
```

### Since when has it been failing?

2023-07-04 ~12:40 PDT (CI job first was in 2023-07-01 ~06:30 PDT)

### Reason for failure (if possible)

Jobs were migrated to EKS in https://github.com/kubernetes/test-infra/pull/29751, it seems that this is the culprit.

### Relevant SIG(s)

/sig node

**Comment by mmiranda96** [comment]
I have 2 potential solutions to this issue, asked for a bit more context on [Slack sig-testing](https://kubernetes.slack.com/archives/C09QZ4DQB/p1689010092557149):
1. Revert to using the previous GCP cluster.
2. Fix the permission issue in EKS.

@rjsadow @Vyom-Yadav @pacoxu do you have any context on this?

**Comment by xmudrii** [comment]
@rjsadow We don't want to migrate jobs depending on any GCP resource. It doesn't make much sense to, let's say, push an image from EKS to GKE. Running it on EKS would mean higher bandwidth/traffic charges because of transferring data (in this case images) to GKE, and that's usually much more expensive than just running the job on GCP and uploading from there. That said, I believe those jobs should be reverted back to the GKE cluster.

**Comment by rjsadow** [comment]
Of course! That makes a lot of sense. Thank you as always :smile:

**Comment by mmiranda96** [comment]
Job `pull-npd-e2e-node` is still failing. It seems that the service account in cluster `k8s-infra-prow-build` doesn't have permission to push to bucket `gs://node-problem-detector-staging`. We probably want to grant it permissions, since other jobs depend on it (like `ci-npd-build`).

**Comment by mmiranda96** [comment]
Checked the logs, the error is still the same. I dug up a bit more on the test script.

The test script uses GCP projects for two things:
- Upload env configuration and tar files to GCS bucket, with a TTL of 7 days.
- Upload container images to GCR registry (under subdirectories `pr` or `ci`, depending on the job)

The current setup is:
- Project `node-problem-detector-staging` (currently used by PR/CI jobs):
    - GCR registry (`gcr.io/node-problem-detector-staging`) has the two directories (screenshot 1)
    - GCS bucket (`gs://node-problem-detector-staging`) exists and should hold tar/env files (none exist due to the 7-day TTL)
- Project `k8s-staging-npd` (unsure what it's used for):
    - GCR registry (`gcr.io/k8s-npd-staging/node-problem-detector`) has no nested directories, it only contains images (screenshot 2)
    - GCS bucket (`gs://k8s-staging-npd`) is the same as the previous: exists and should hold tar/env files (none exist due to the 7-day TTL)

I'm unaware what's the use case of the current images hosted in `gcr.io/k8s-staging-npd`. But if possible, I would argue that we can use that project for the original use case of `node-problem-detector-staging`: hosting PR and CI images. Similarly, we can use the project bucket to store tar/env files.

@Random-Liu is there a reason why we have two different buckets? I noticed that prod binaries are released in `gcr.io/kubernetes-release/node-problem-detector`.

**Comment by MartinForReal** [comment]
I think we should put all images in k8s-staging-npd because repo is allocated in https://github.com/kubernetes/k8s.io/blob/71e636f5a165d2d29d86331a41709346b20f10eb/infra/aws/terraform/registry.k8s.io/README.md?plain=1#L4

**Comment by MartinForReal** [comment]
Can we switch back to gce?

**Comment by mmiranda96** [comment]
We're using a new GCP project. To unblock, I'll revert to the original project and ensure everything else is ready before using the new GCP project.

**Comment by mmiranda96** [comment]
I reverted to use default cluster on some jobs in https://github.com/kubernetes/test-infra/pull/30262. Meanwhile, I'll keep investigating to see which permissions are missing and how can we grant them.

**Comment by BenTheElder** [comment]
> [...] We don't want to migrate jobs depending on any GCP resource. [...]

To the EKS cluster that is, however it may be reasonable to go ahead and migrate to the community GKE cluster and we eventually intend all jobs to migrate out of the legacy cluster(s).

**Comment by BenTheElder** [comment]
We've been prioritizing jobs that are cloud independent to identify the scope of what remains and ramp up usage of the AWS resources, but it's totally expected that not all jobs can run on AWS and the other k8s infra cluster should be fine.

**Comment by SergeyKanzhelev** [comment]
@mmiranda96 what is left in this bug? Jobs seems to be passing now

**Comment by SD-13** [comment]
@mmiranda96 wanted to know the current status of this issue. Can we now move jobs to the `k8s-infra-prow-build` cluster?

**Comment by wangzhen127** [comment]
I will update the config after https://github.com/kubernetes/node-problem-detector/pull/882 is merged.

**Comment by wangzhen127** [comment]
Looks like we still have the `403 Forbidden` issue. I wonder why `ci-npd-e2e-kubernetes-gce-gci` can use `k8s-infra-prow-build`?

**Comment by wangzhen127** [comment]
This is fixed.
/close

**Comment by BenTheElder** [comment]
I don't think this was really fixed though, because these jobs are back in `cluster: default` which is subject to removal in August.

https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU

**Comment by BenTheElder** [comment]
To push staging builds:
https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io#managing-kubernetes-container-registries

**Comment by wangzhen127** [comment]
You are correct. I was confused.
/reopen

**Comment by BenTheElder** [comment]
https://github.com/kubernetes/node-problem-detector/pull/925

the remainder in https://github.com/kubernetes/node-problem-detector/issues/920
