### ISSUE TITLE
Should kube proxy should delete its rules when being gracefully deleted ? 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#119265]
### What happened?

I was replacing kube proxy w/ antrea proxy, our kube proxy replacement.  I found something interesting.... All these rules, 

```
-A KUBE-SVC-SAL3JMSY3XQSA64S -m comment --comment "tkg-system/tkr-resolver-cluster-webhook-service -> 100.96.1.15:9443" -j KUBE-SEP-APPCGWWBW4GQN2HK                                                                                                                 
-A KUBE-SVC-SZBZVVMNBX2D3VFK ! -s 100.96.0.0/11 -d 100.68.215.151/32 -p tcp -m comment --comment "capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-webhook-service cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ                                              -A KUBE-SVC-SZBZVVMNBX2D3VFK -m comment --comment "capi-kubeadm-bootstrap-system/capi-kubeadm-bootstrap-webhook-service -> 100.96.1.8:9443" -j KUBE-SEP-Z5LDPDXWJ7G5IJIQ                                                                                             -A KUBE-SVC-TCOU7JCQXEZGVUNU ! -s 100.96.0.0/11 -d 100.64.0.10/32 -p udp -m comment --comment "kube-system/kube-dns:dns cluster IP" -m udp --dport 53 -j KUBE-MARK-MASQ                                                                                              
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns -> 100.96.0.3:53" -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-ONT5M3GKZCUX63CA                                                                                    -A KUBE-SVC-TCOU7JCQXEZGVUNU -m comment --comment "kube-system/kube-dns:dns -> 100.96.0.4:53" -j KUBE-SEP-X6Z4D2PLM3E4AFD7                                                                                                                                           -A KUBE-SVC-XI3EV6PAOLGPKNCY ! -s 100.96.0.0/11 -d 100.68.64.20/32 -p tcp -m comment --comment "tkg-system/tkr-conversion-webhook-service cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ                                                                           
-A KUBE-SVC-XI3EV6PAOLGPKNCY -m comment --comment "tkg-system/tkr-conversion-webhook-service -> 100.96.1.14:9443" -j KUBE-SEP-EMM6VPN6RQ4BTZVT                                                                                                                       -A KUBE-SVC-Z4ANX4WAEWEBLCTM ! -s 100.96.0.0/11 -d 100.70.166.34/32 -p tcp -m comment --comment "kube-system/metrics-server:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ                                                                                   -A KUBE-SVC-Z4ANX4WAEWEBLCTM -m comment --comment "kube-system/metrics-server:https -> 100.96.1.4:4443" -j KUBE-SEP-FY6XAK6CPXJEDB4L                                                                                                                                 
-A KUBE-SVC-ZUD4L6KQKCHD52W4 ! -s 100.96.0.0/11 -d 100.71.102.80/32 -p tcp -m comment --comment "cert-manager/cert-manager-webhook:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ                                                                            -A KUBE-SVC-ZUD4L6KQKCHD52W4 -m comment --comment "cert-manager/cert-manager-webhook:https -> 100.96.1.5:10250" -j KUBE-SEP-WTGQJIGDMYOJ6KTB     
```

Were still floating around in my cluster.  The problem with this is that i think in the datapath for a linux VM, openvswitch is "After" the IPtables stuff.  So... that means if your replacing kube proxy running in iptables mode w/ another technology, the old service IPs will still be forwarded to potentially old pods that dont exist anymore. 

### What did you expect to happen?

Kube proxy would gracefully  clean up after itself when exiting.  After all, anyone deleting kube proxy is probably doing so with the intent of having at least one pod in their cluster change its IP after a while.  

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster w/ kubeadm and standard kube proxy. 
Delete the kube proxy.
Check `iptables-save` in a node, and youll see all the rules.

### Anything else we need to know?

Maybe as a medium solution we could just have kube proxy delete things that are specific to pod IPs. 
\

This is probably all overkill but i figured i should write this issue up in case others hit the same thing when trying to swap out kube proxy for another service proxy in a running cluster.  The TIL for me is the fact that iptables comes earlier in the datapath for processing network stuffs than OVS

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
we have the cleanup flags for that

https://github.com/kubernetes/kubernetes/blob/be13c6a884248c40cb3a50a24a622b4403138444/cmd/kube-proxy/app/server.go#L162

> After all, anyone deleting kube proxy is probably doing so with the intent of having at least one pod in their cluster change its IP after a while.

how do you know if is being deleted and never going to be started or just restarted/upgraded

**Comment by khenidak** [comment]
in all fairness we need to document the two steps dance that folks needs to do to clear things before moving away from `kube-proxy` e.g. update proxy deployment (to run with `--cleanup` across all nods) then deploy whatever replacement.

**Comment by jayunit100** [comment]
Ohhh or maybe cleanup by default ? Why wouldn't you want to cleanup on exit ?

**Comment by jayunit100** [comment]
Am ok closing this if it's a won't fix or we can triage it as a docs issue ? 

But one last question: is there a good reason not to cleanup the rules on exiting ?

**Comment by aojea** [comment]
> But one last question: is there a good reason not to cleanup the rules on exiting ?

you break existing connections and zero disruption upgrades per example, imagine you upgrade your kube-proxy , if you delete all the rules on exit until it restarts and reprogram all the rules all new traffic to the Services will be dropped

**Comment by shaneutt** [comment]
We talked about this one at the SIG Network meeting today, most of the discussion was that we _don't_ want to do cleanup automatically for the reasons Antonio is talking about above.

/assign @shaneutt

**Comment by MikeZappa87** [comment]
@jayunit100 can you run the kubeadm and skip the kube-proxy installation? That prevents the issue from happening.

**Comment by shaneutt** [comment]
@jayunit100 the suggestion from @MikeZappa87 above seems to make the most sense to me: rather than even worrying about cleanup, just never create the problem? Let us know if that's tenable for you and if you feel it's OK for us to close this with either the `--skip-phases` solution or the `--cleanup` solution, or if you think there's more we need to discuss here?

**Comment by robscott** [comment]
Discussed at sig-network today, I think we can close this one out, we don't want to do cleanup on shutdown. 

/close
