### ISSUE TITLE
Running cluster/kubectl requires gcloud to be installed now

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#119257]
### What happened?

[redacted kubernetes-kevin]$ cluster/kubectl.sh
cluster/../cluster/../cluster/gce/util.sh: line 60: gcloud: command not found

### What did you expect to happen?

In a previous release I was able to use this command without any issue.  It seems that gcloud is now a requirement to use the script as is.  

### How can we reproduce it (as minimally and precisely as possible)?

If you try to use cluster/kubectl.sh without gcloud installed, you will get this error.  

### Anything else we need to know?

The `local-up-cluster.sh` says to use cluster/kubectl.sh but if you go to cluster/kubectl.sh:

```
# Stop the bleeding, turn off the warning until we fix token gen.
# echo "-=-=-=-=-=-=-=-=-=-="
# echo "NOTE:"
# echo "kubectl.sh is deprecated and will be removed soon."
# echo "please replace all usage with calls to the kubectl"
# echo "binary and ensure that it is in your PATH."
# echo ""
# echo "Please see 'kubectl help config' for more details"
# echo "about configuring kubectl for your cluster."
# echo "-=-=-=-=-=-=-=-=-=-="
```
It seems that kubectl via cluster/kubectl.sh is deprecated but the common way of running Kubernetes development environment suggests it.  I am able to get this to work if I just use my kubectl cli but not sure if that is expected behavior or not.  

### Kubernetes version

<details>
latest main from build
</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
Linux ip-172-31-93-184.ec2.internal 5.10.173-154.642.amzn2.x86_64 #1 SMP Wed Mar 15 00:26:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>


### Install tools

<details>
NA
</details>


### Container runtime (CRI) and version (if applicable)

<details>
NA
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
NA
</details>

**Comment by BenTheElder** [comment]
`cluster/` is pretty much only used with GCE for the purposes of testing Kubernetes and is [officially deprecated](https://github.com/kubernetes/kubernetes/tree/master/cluster#cluster-configuration), can you elaborate on how you're intending to use this without gcloud?

gcloud is necessary for the auth plugin, since auth plugins moved out of tree.

**Comment by kannon92** [comment]
I mostly just use this script because I thought this was the way you use it when you build K8 locally.  

https://github.com/kubernetes/kubernetes/blob/da2d500c80968aacf4dfa9e32f5e6ccc06dc33c7/hack/local-up-cluster.sh#L1065

This pops up when you run `hack/local-up-cluster.sh` and I figured this was the way to run k8 locally.  

I saw that cluster/ is deprecated and it looks like you can just point your `kubectl` cli to the kubeconfig that points to the local build of k8s.  

Maybe that should be in the bash popup as I was using `cluster/kubectl.sh` for the last release without any issue but didn't even realize it was deprecated.

**Comment by BenTheElder** [comment]
> This pops up when you run hack/local-up-cluster.sh and I figured this was the way to run k8 locally.

ahhhh cc @dims 🙃

**Comment by dims** [comment]
please just use your kubectl cli :)

**Comment by kannon92** [comment]
> please just use your kubectl cli :)

Added a note to say that in the bash output:

https://github.com/kubernetes/kubernetes/pull/119266
