### ISSUE TITLE
1.30 - [kep-3751]  Finalizer Management Change

### ISSUE THREAD

**Issue by sunnylovestiramisu** [kubernetes/kubernetes#119298]
### What would you like to be added?

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e776b8fa-7fff-5a33-682c-79ecb0343e5e"><div dir="ltr" style="margin-left:0pt;" align="left">

Tasks
--

1. Check finalizers for delete VolumeAttributesClass
2. Creating PVC with VolumeAttributesClass
* Vac_admission_controller adding finalizer to VAC for protection
3. Updating PVC with VolumeAttributesClass
* Vac_admission_controller adding finalizer to VAC for protection
4. Deleting PVC with VolumeAttributesClass
* Vac_protection_controller for deletion
5. Unbound PV created with a VolumeAttributesClass
* Vac_admission_controller adding finalizer to VAC for protection
6. Deleting a PV with a VolumeAttributesClass
* Vac_protection_controller for deletion
</div></b>

### Why is this needed?

Task tracking for kep-3751 https://github.com/kubernetes/enhancements/pull/3780

Task board: https://github.com/orgs/kubernetes-csi/projects/72/views/1

**Comment by sunnylovestiramisu** [comment]
Since the PR for https://github.com/kubernetes/kubernetes/issues/119297 is in a good shape, I will start working on this based on the change.

**Comment by carlory** [comment]
Hi @msau42, @sunnylovestiramisu, I have a question about this feature. Do we really need the protection for VAC resources? 

Currently, we only protect the PV/PVC resources from being deleted via the `StorageObjectInUseProtection` admission plugin. It makes sure that existing workloads run as expected and do not get affected by the deletion of the PV/PVC resources unless workloads are also deleted.

However, deleting a VAC resource won't affect any existing workloads. PV/PVC can be deleted regardless of whether VAC exists. So why we need to protect VAC resources? 

BTW, the StorageClass resource are not protected as well.

**Comment by sunnylovestiramisu** [comment]
@carlory I was thinking because VAC has certain params, if it is deleted and you only looked at the name of the VAC in PV/PVC, you do not really know what did VAC set.

But for StorageClass, the parameters are mostly preserved?

**Comment by carlory** [comment]
Based on the issue triage meeting on [Feb 7, 2024](https://docs.google.com/document/d/1n-dXXvCbHsPfO1yrKwT1qoC80KhsxHYKbRdChdzqeXY/edit), we need to have a detailed proposal before implementing it.

**Comment by sunnylovestiramisu** [comment]
The open question is that can we put this in the resizer.
