### ISSUE TITLE
Error in kubectl events command

### ISSUE THREAD

**Issue by abidmunirmalik** [kubernetes/kubernetes#119282]
### What happened?

```
$ kubectl events --help
Display events
...
Usage:
  kubectl events
[(-o|--output=)json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file]
[--for TYPE/NAME] [--watch] [--event=Normal,Warning] [options]
```
The  `[--event=Normal,Warning] `seems to be wrong, should be `--types `instead of `--event`

### What did you expect to happen?

```
$ kubectl events --for namespace/kube-system  --types=Normal
No events found in default namespace.
```

### How can we reproduce it (as minimally and precisely as possible)?

```
$ kubectl events --for namespace/kube-system  --event=Normal
error: unknown flag: --event
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.26.3
```

</details>

### Cloud provider

<details>
I am running local Kubernetes cluster using **kind**.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
MacOS
$ uname -a
Darwin NCRALABMALIK-M1 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
Docker Desktop for Mac
Kind Kubernetes Cluster
</details>

### Container runtime (CRI) and version (if applicable)

<details>
Docker
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
kindnet
</details>

**Comment by abidmunirmalik** [comment]
Yes Sir!

Abid

**Comment by MeowChan27** [comment]
Hello, can i work on this as my first contribution pls ?

**Comment by abidmunirmalik** [comment]
@MeowChan27 - How unethical it is that you are assigning an issue that you have not pointed out. 
It is much better that you find a issue and repot it and then assign it.

Please go ahead and unassign it, I will assign it and will work on it.

CC @ardaguclu

**Comment by ardaguclu** [comment]
@abidmunirmalik As you opened issue and said that you are planning to work on this, you fully deserve to work on that issue.
I'm sorry that I did not check the assignee and approved the PR fixing this.

@MeowChan27 next time, I highly suggest that check if there is assignee or not and only start work on it, only if there is noone.

**Comment by MeowChan27** [comment]
@abidmunirmalik Oh sorry I though you said 'please assign yourself and work on it'. I cancel my PR. 
I am really sorry.
