### ISSUE TITLE
pod force kill(`--force --grace-period=0`) do not send a SIGKILL to the container immediately

### ISSUE THREAD

**Issue by flavono123** [kubernetes/kubernetes#119276]
### What happened?

run `kubectl delete po [pod] --grace-period 0 --force` to kill the pod and its containers immediately but didn't.

### What did you expect to happen?

`kubectl delete po [pod] --grace-period 0 --force`  should kill the pod and also its containers immediately, even they do graceful termination things.

### How can we reproduce it (as minimally and precisely as possible)?

- run a pod whose container has graceful termination feature and trigger that(like remain some sessions)
- kill the pod with `kubectl delete po [pod] --grace-period 0 --force`.
- the pod is deleted immediately but the container is not
  - can see the container in the node like `crictl ps`
  - or the conatiner's logs, strace for pid whatever you can.

(* i can upload more specific commands and logs if you needed)

### Anything else we need to know?

FYI.
- without `--force`, it works properly so we use this for "force(=immediately =no graceful)" terminations.
  - `--grace-period=1`  send a SIGKILL after 1 sec.
  - `--grace-period=0`(**without `--force`**) send a SIGKILL immediately.

### Kubernetes version

<details>
tested in two clusters(only server versions).
- v1.24.14-eks-c12679a
- v1.24.15-eks-a5565ad
```console
$ kubectl version
# Cluster 1
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.14-eks-c12679a", GitCommit:"05d192f0de17608d98e17761ad3cffa9a6407f2f", GitTreeState:"clean", BuildDate:"2023-05-22T23:41:27Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

# Cluster 2
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.15-eks-a5565ad", GitCommit:"af0b16a331376384fe84445fe2f8d4cb468b4148", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:37Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS

tested nodes(kubelet) versions

- for cluster1

```
Kubelet version
v1.24.13-eks-0a21954
```

- for cluster 2

```
Kubelet version
v1.24.10-eks-48e63af
```
</details>

### OS version

<details>

```console
# for cluster 1's node
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-10-1-223-148.us-west-2.compute.internal 5.10.184-175.731.amzn2.x86_64 #1 SMP Tue Jun 27 21:48:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# for cluster 2's node
$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
$ uname -a
Linux ip-192-168-172-52.ap-northeast-2.compute.internal 5.10.167-147.601.amzn2.x86_64 #1 SMP Tue Feb 14 21:50:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
afaik, AWS EKS web console + terraform
</details>

### Container runtime (CRI) and version (if applicable)

<details>

- for cluster1's node: containerd://1.6.6
- for cluster2's node: containerd://1.6.19

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
nothing i think
</details>

**Comment by flavono123** [comment]
i think i just found a concern on it in the help messages of `kubectl`:

```sh
 Some resources, such as pods, support graceful deletion. These resources define a default period before they are forcibly terminated (the grace period) but you may override that value with the --grace-period flag, or pass --now to set a grace-period of 1. Because these resources often represent entities in the cluster, deletion may not be acknowledged immediately. If the node hosting a pod is down or cannot reach the API server, termination may take significantly longer than the grace period. To force delete a resource, you must specify the --force flag. Note: only a subset of resources support graceful deletion. In absence of the support, the --grace-period flag is ignored.
```

Is this behavior intended?

**Comment by aojea** [comment]
/sig node

@smarterclayton I remember you were doing something about this behavior and there are several past issues about this opened by you, so tagging you for historical context https://github.com/kubernetes/kubernetes/issues/37637

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

@flavono123 can you please share the kubelet.log when the issue happening. If you can collect three of them with different combination of graceful period and `force` as decribed in the bug - it will help for sure.
