### ISSUE TITLE
Two new conformance tests don't cleanup their CRs (since K8s v1.27)

### ISSUE THREAD

**Issue by dguendisch** [kubernetes/kubernetes#119259]
### What happened?

These two conformance tests [1](https://github.com/kubernetes/kubernetes/blob/v1.27.3/test/e2e/apimachinery/field_validation.go#L168) and [2](https://github.com/kubernetes/kubernetes/blob/v1.27.3/test/e2e/apimachinery/field_validation.go#L286) are creating CRs `mytest` with some dummy finalizer `test-finalizer` in the target cluster.
Naturally these CRs cannot be cleaned up later without forcefully finalizing them.

cc @rfranzke @hendrikKahl

### What did you expect to happen?

It would be nice to not "pollute" the target cluster with resources that require forceful deletion/finalization.
I noticed that other similar tests, e.g. https://github.com/kubernetes/kubernetes/blob/v1.27.3/test/e2e/apimachinery/apply.go#L716 are explicitly removing such dummy finalizers after the test.

### How can we reproduce it (as minimally and precisely as possible)?

Run the above named two tests against any v1.27 cluster and see how the test CRs cannot be gracefully deleted.

### Kubernetes version

v1.27

### Cloud provider

All cloudproviders including KinD.

### OS version

n/a

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/assign @kevindelgado 

this was introduced here https://github.com/kubernetes/kubernetes/pull/115271

> /sig testing

testing does not owns the tests, it owns the overall infrastructure and policies, each sigs own their own tests

/sig api-machinery

**Comment by jiahuif** [comment]
cc @benluddy 
/unassign @kevindelgado
(not working on it, unassigning)
/assign @apelisse 
/triage accepted

**Comment by benluddy** [comment]
https://github.com/kubernetes/kubernetes/pull/118947

**Comment by cici37** [comment]
/close
please feel free to reopen if needed. Thanks :)
