### ISSUE TITLE
Deleting deployment is not deleting underlying replicaset and pods

### ISSUE THREAD

**Issue by devops-newbee** [kubernetes/kubernetes#119364]
### What happened?

Hello All, I recently updated eks cluster from 1.24 to 1.25. After upgrading It was noticed that deleting deployments is not deleting the underlying replicasets and pods. 
I have to delete all three individually. I have 2 other cluster whcih are on 1.24 and they DOESNOT show the same behavior. Deleting the pods on them deletes all underlying entities.
My jumphost kubectl version is 1.24(we have different jumphost for all 3 environments).

Issue can be easily reproduced by creating a sample nginx deployment.
kubectl create deployment nging-test --image=nginx

 

### What did you expect to happen?

Expected behavior is that all underlying objects should be deleted.

### How can we reproduce it (as minimally and precisely as possible)?

deploy a simple deployment like : kubectl create deployment nginx-test --image=nginx

### Kubernetes version

client version: 1.24
server version : 1.25

### Cloud provider

AWS

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by devops-newbee** [comment]
OS version 
Jumphost OS version : 
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

**Comment by devops-newbee** [comment]
XXXXX@ip-XX-XXX-XX-XX ~ $ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.11-eks-a5565ad", GitCommit:"df109513ba589adaee235b4e658476275d1fde31", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:00Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
XXXXX@ip-XX-XX-XX-XX ~ $

**Comment by devops-newbee** [comment]
`1) Situation before nginx-test deployment: 

XX-XX@XX-XX-XX-XX ~ $ kubectl get deploy
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
cross-efs-test    1/1     1            1           10d
tigera-operator   1/1     1            1           27d
vpa-recommender   1/1     1            1           158d
vpa-updater       1/1     1            1           158d
XX-XX@XX-XX-XX-XX ~ $ kubectl get rs
NAME                         DESIRED   CURRENT   READY   AGE
cross-efs-test-7fc66f8b6     1         1         1       10d
tigera-operator-59f5969d6    1         1         1       27d
vpa-recommender-7b5db9d77c   1         1         1       158d
vpa-updater-74459cfbfd       1         1         1       158d
XX-XX@XX-XX-XX-XX ~ $ kubectl get pods
NAME                                READY   STATUS    RESTARTS           AGE
cross-efs-test-7fc66f8b6-mg465      1/1     Running   0                  2d21h
nginx-deployment-7b966b75bd-b66fl   1/1     Running   0                  2d21h
tigera-operator-59f5969d6-qttbb     1/1     Running   0                  3d22h
vpa-recommender-7b5db9d77c-kn8z8    1/1     Running   1018 (3m33s ago)   3d22h
vpa-updater-74459cfbfd-xjq6t        1/1     Running   1020 (104s ago)    3d22h
XX-XX@XX-XX-XX-XX ~ $

2) Situation after nginx-test deployment: 

XX-XX@XX-XX-XX-XX ~ $ kubectl create deployment nginx-test --image=nginx
deployment.apps/nginx-test created
XX-XX@XX-XX-XX-XX ~ $ kubectl get deploy
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
cross-efs-test    1/1     1            1           10d
nginx-test        1/1     1            1           5s
tigera-operator   1/1     1            1           27d
vpa-recommender   1/1     1            1           158d
vpa-updater       1/1     1            1           158d
XX-XX@XX-XX-XX-XX ~ $ kubectl get rs
NAME                         DESIRED   CURRENT   READY   AGE
cross-efs-test-7fc66f8b6     1         1         1       10d
nginx-test-5c656c7f9         1         1         1       13s
tigera-operator-59f5969d6    1         1         1       27d
vpa-recommender-7b5db9d77c   1         1         1       158d
vpa-updater-74459cfbfd       1         1         1       158d
XX-XX@XX-XX-XX-XX ~ $ kubectl get pods
NAME                                READY   STATUS    RESTARTS           AGE
cross-efs-test-7fc66f8b6-mg465      1/1     Running   0                  2d21h
nginx-deployment-7b966b75bd-b66fl   1/1     Running   0                  2d21h
nginx-test-5c656c7f9-9cvv2          1/1     Running   0                  18s
tigera-operator-59f5969d6-qttbb     1/1     Running   0                  3d22h
vpa-recommender-7b5db9d77c-kn8z8    1/1     Running   1019 (74s ago)     3d22h
vpa-updater-74459cfbfd-xjq6t        1/1     Running   1020 (4m55s ago)   3d22h
XX-XX@XX-XX-XX-XX ~ $

3) When tyring to delete the deployment :
XX-XX@XX-XX-XX-XX ~ $ kubectl delete deployment nginx-test
deployment.apps "nginx-test" deleted
XX-XX@XX-XX-XX-XX ~ $ kubectl get rs
NAME                         DESIRED   CURRENT   READY   AGE
cross-efs-test-7fc66f8b6     1         1         1       10d
nginx-test-5c656c7f9         1         1         1       2m18s
tigera-operator-59f5969d6    1         1         1       27d
vpa-recommender-7b5db9d77c   1         1         1       158d
vpa-updater-74459cfbfd       1         1         1       158d
XX-XX@XX-XX-XX-XX ~ $ kubectl get pods
NAME                                READY   STATUS    RESTARTS           AGE
cross-efs-test-7fc66f8b6-mg465      1/1     Running   0                  2d21h
nginx-deployment-7b966b75bd-b66fl   1/1     Running   0                  2d21h
nginx-test-5c656c7f9-9cvv2          1/1     Running   0                  2m22s
tigera-operator-59f5969d6-qttbb     1/1     Running   0                  3d22h
vpa-recommender-7b5db9d77c-kn8z8    1/1     Running   1019 (3m18s ago)   3d22h
vpa-updater-74459cfbfd-xjq6t        1/1     Running   1021 (89s ago)     3d22h
XX-XX@XX-XX-XX-XX ~ $ kubectl get deploy
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
cross-efs-test    1/1     1            1           10d
tigera-operator   1/1     1            1           27d
vpa-recommender   1/1     1            1           158d
vpa-updater       1/1     1            1           158d
XX-XX@XX-XX-XX-XX ~ $`

**Comment by devops-newbee** [comment]
Hello Colleagues, Can this issue be looked into. We are now running our LAB cluster on different version and TST and PRD on different k8s version which is not an ideal state for us. We paused to upgrade the TST and PRD because of this issue.

**Comment by utkarsh-singh1** [comment]
Hi @devops-newbee, I have not faced any problem,

But can you post screenshot of 

`kubectl describe deployment deployment-name`

`kubectl describe pods pods-name`

`kubectl describe rs replica-set-name`

**Comment by devops-newbee** [comment]
Hello utkarsh-singh1, Please find the details. screen shot wont be possible for me.
[githubshare.txt](https://github.com/kubernetes/kubernetes/files/12080119/githubshare.txt)

**Comment by devops-newbee** [comment]
Any suggestion here?

**Comment by atiratree** [comment]
Since the owner references are untouched, garbage collector is most likely down: I would suggest to inspect
- your KCM log to undestand why GC is halted
- `garbagecollector_controller_resources_sync_error_total` metric to see how often is GC failing to sync
