### ISSUE TITLE
scheduler: Add ctx param and error return to EnqueueExtensions.EventsToRegister()

### ISSUE THREAD

**Issue by codefromthecrypt** [kubernetes/kubernetes#119323]
### What would you like to be added?

The scheduling framework `EnqueueExtensions.EventsToRegister()` has recently been changed to return `[]ClusterEventWithHint` instead of `ClusterEvent[]`. Since we've broken API anyway, it seems fitting to add a ctx param and error return to it.

So, change

```
EventsToRegister() []ClusterEventWithHint
```

to

```
EventsToRegister(context.Context) ([]ClusterEventWithHint, error)
```

### context parameter

The primary motivation is to be able to use contextual values, such as [logging](https://github.com/kubernetes/kubernetes/pull/116884). This is particularly important in WebAssembly where tracing, debug or custom config can be passed contextually to the underlying runtime. `EventsToRegister()` is currently the only plugin extension widely used and missing context,

### error return

The primary motivation of this is to allow coherent behavior on error, or to prevent panics. It is true that a native scheduler plugin is unlikely to err or panic creating the list of functions. However, when implemented in WebAssembly, there could be errors invoking the function in the guest VM, and currently, we have to deal with these in an undefined fashion.

**Comment by sanposhiho** [comment]
/triage accepted

@kubernetes/sig-scheduling-leads Any concern here?

**Comment by alculquicondor** [comment]
As mentioned in the other thread, I prefer we don't add a context, but just a logger, for performance reasons: it is expensive to get the logger from the context in such a critical path.

Do you need a context for wasm or is a logger enough?

**Comment by codefromthecrypt** [comment]
> Do you need a context for wasm or is a logger enough?

it is the other way around, context is more important than logger. Which benchmark are you looking at about the cost of that parameter? Can we improve something else to buy that back?

**Comment by sanposhiho** [comment]
It feels like we need to distinguish the topics, to have ctx in EventToRegister and to have ctx in QueueingHintFn.

The former, which is proposed at the top of this issue, I don't think we need to be very careful about the performance since EventToRegister is called only once and that's when the scheduler is being initialized.

The latter, which is asked in https://github.com/kubernetes/kubernetes/pull/119155#discussion_r1263484074, yes, we need to be careful of the performance for this one. Maybe we need to have a performance test via scheduler_perf, see if ctx visibly slows down the performance, and if it does, we need to figure out how we can improve something to have ctx (or the fact we cannot have any improvements to do).

**Comment by googs1025** [comment]
Is there any update on this issue? Has it been accepted? If it has been accepted, I am willing to try it.

**Comment by alculquicondor** [comment]
Is this still needed, @codefromthecrypt?

**Comment by sanposhiho** [comment]
Yes, we still want to get ctx in params and error in return values.
https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/blob/main/scheduler/plugin/plugin.go#L152-L189

I know this usecase is rare though, we have to get registered events from wasm module side, which needs `ctx` for communication with wasm (I mean, we know we can create a new ctx in it, but better to use propagated ctx for logging / tracing, generally speaking), and error for some wrong paths.

**Comment by googs1025** [comment]
Sounds good, I'd like to try it out.
/assign

**Comment by sanposhiho** [comment]
@alculquicondor Do you think [your concern raised above](https://github.com/kubernetes/kubernetes/issues/119323#issuecomment-1635901912) is still relevant? 
My point for it is -
> I don't think we need to be very careful about the performance since EventToRegister is called only once and that's when the scheduler is being initialized.
https://github.com/kubernetes/kubernetes/issues/119323#issuecomment-1636676186
