### ISSUE TITLE
Audit comments in types.go

### ISSUE THREAD

**Issue by caesarxuchao** [kubernetes/kubernetes#11933]
- # 10933 removes the description tag in types.go, the description of fields are merged with other comments as the new description. Some of these comments don't read as a sentence after the merge. Because our api-reference [docs](http://kubernetes.io/v1.0/docs/api-reference/definitions.html) use these descriptions, we need to fix them before #10933.
- # 10933 detects these [structs](https://github.com/GoogleCloudPlatform/kubernetes/pull/10933#issuecomment-125270576) don't have any description. We need to add description for them.

@andronat @nikhiljindal @bgrant0607

**Comment by andronat** [comment]
Just reposting the list of missing documentation here:

```
Missing documentation for the struct itself: ComponentCondition
Missing documentation for the struct itself: ComponentStatusList
Missing documentation for the struct itself: ConditionStatus
Missing documentation for the struct itself: ContainerStateRunning
Missing documentation for the struct itself: ContainerStateTerminated
Missing documentation for the struct itself: ContainerStateWaiting
Missing documentation for the struct itself: ContainerStatus
Missing documentation for the struct itself: EmptyDirVolumeSource
Missing documentation for the struct itself: EventSource
Missing documentation for the struct itself: FinalizerName
Missing documentation for the struct itself: NamespacePhase
Missing documentation for the struct itself: NodeAddress
Missing documentation for the struct itself: NodeAddressType
Missing documentation for the struct itself: NodeCondition
Missing documentation for the struct itself: NodeConditionType
Missing documentation for the struct itself: NodePhase
Missing documentation for the struct itself: PersistentVolume
Missing documentation for the struct itself: PersistentVolumeAccessMode
Missing documentation for the struct itself: PersistentVolumeClaimList
Missing documentation for the struct itself: PersistentVolumeClaimPhase
Missing documentation for the struct itself: PersistentVolumeClaimStatus
Missing documentation for the struct itself: PersistentVolumeClaimVolumeSource
Missing documentation for the struct itself: PersistentVolumeList
Missing documentation for the struct itself: PersistentVolumePhase
Missing documentation for the struct itself: PersistentVolumeSpec
Missing documentation for the struct itself: PersistentVolumeStatus
Missing documentation for the struct itself: PodCondition
Missing documentation for the struct itself: SecretList
Missing documentation for the struct itself: SecretType
Missing documentation for the struct itself: SerializedReference
Missing documentation for the struct itself: ServicePort
API file: ./pkg/api/v1/types.go is missing: 31 descriptions
```

**Comment by caesarxuchao** [comment]
@andronat, do you plan to help audit the comments?

**Comment by andronat** [comment]
Yes I could most certainly help! But my knowledge on what those structs are doing is quite limited so I am not sure how much of a help I can be :/

**Comment by caesarxuchao** [comment]
Thank you! We can ask other people for help for those structs that we don't know.

**Comment by andronat** [comment]
I will try to fix the first 20 for the beginning: `TypeMeta` -> `GCEPersistentDiskVolumeSource`. As far as I can tell there are 114 structs in `v1/types.go`.

**Comment by caesarxuchao** [comment]
Thank you. Could you send a WIP PR when the first 20 is done so that we can give feedback quicker?

**Comment by andronat** [comment]
I think I can't create a PR on my PR :/. I will update this issue when I am done.

**Comment by caesarxuchao** [comment]
maybe you can make it another commit in #10933?

**Comment by andronat** [comment]
Yes, this is a good idea.

**Comment by andronat** [comment]
Audit is here: ae54c4b

**Comment by smarterclayton** [comment]
Closing due to age, reopen if this is important.
