### ISSUE TITLE
AWS: We should consider updating/reusing cluster-autoscaler to support AWS

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11935]
We have an autoscaling group for the minions; we should consider enabling auto-scaling based e.g. on CPU or a custom metric we publish.

**Comment by erictune** [comment]
A group of us have been discussing node autoscaling this week, including @bgrant0607 @vmarmol @davidopp @jszczepkowski @piosz @gmarek @mwielgus @wojtek-t (probably forgetting some people)

**Comment by erictune** [comment]
One thing we talked about was maybe layering the system like this:
- Pod horizontal autoscaler scales up pod count using CPU as a signal, and maybe later custom metrics, such as http request rate, http latency, etc.
- Node (horizontal) autoscaler adds nodes when pods are pending due to the scheduler not being able to find a place in the cluster for the pod (failed PodFitsResources check in scheduler).  This assumes that pods set reasonable CPU and memory limits.
So, the Node autoscaler wouldn't directly look at CPU, but indirectly hears about it due to pods being pending.

**Comment by justinsb** [comment]
That makes a lot of sense to me.  I would love to be involved in any discussions.

AWS auto-scaling-groups (and I believe Google MIGs via autoscalers) allow for a quick-and-dirty version of this.  Your approach is infinitely better, though I suspect will take a little longer!

The fact that the scheduler will avoid overloading the cluster makes auto-scaling externally much less useful, so we would be in custom metric territory.  Even then, I think that having the master node manage the instances will be a much better experience.

Maybe we could promote this interface out of aws (currently used only for e2e tests):
https://github.com/GoogleCloudPlatform/kubernetes/blob/8d5a6b063c68b50e9e2e481c04c4cfec4fa57bde/pkg/cloudprovider/aws/aws.go#L147-L154

**Comment by ecowan** [comment]
Hi everyone, I too am very interested in seeing progress on this front. I would really appreciate it if someone could point me to any resources / pull requests that have been done. Thanks!

**Comment by satheessh** [comment]
+1

**Comment by rafaljanicki** [comment]
+1

**Comment by valery-zhurbenko** [comment]
+1

**Comment by piosz** [comment]
If anyone from would like to integrate Kubernetes with AWS autoscaler I'm happy to share our experience with integrating Kubernetes with GCE autoscaler.

cc @fgrzadkowski @mwielgus

**Comment by sstarcher** [comment]
@piosz I would be interested in hearing your experience with Kubernetes GCE autoscaler and I may be interested in helping with this feature.

**Comment by miguelfrde** [comment]
@piosz I would be interested on hearing about your experience and helping with this feature as well.

**Comment by jimmycuadra** [comment]
@piosz Yes, please! Very interested in this.

**Comment by dengshuan** [comment]
Any schedules about this feature? Or is there any more detailed discussion about this?

**Comment by mwielgus** [comment]
For 1.3 we have a plan to revisit cluster autoscaling in Kubernetes and make it more user-friendly. At this moment we are discussing our 1.3 priorities and project assignments internally at Google. We will let you once we reach some agreement regarding the possible scope of the improvement that can be delivered by Google and integration plans for other cloud providers (we will definitely need community help there).

**Comment by sstarcher** [comment]
Our current AWS scaling strategy for Kubernetes currently has 3 parts
* Scale add instances on `Pending` pods
* Remove instances not running pods
* A changed to the scheduler to pack our load instead of spreading our load

**Comment by justinsb** [comment]
Pulling across tags from closed #23480

**Comment by herry13** [comment]
@sstarcher May I add another strategy, which is the opposite of the 3rd:
- A changed to the scheduler to spread our existing load to support N+1 fault tolerance

**Comment by sstarcher** [comment]
@herry13 do you mean in the situation that a server goes down you can automatically reschedule any failed pods without waiting for a server to come back?

**Comment by herry13** [comment]
@sstarcher Yes, that's one of the scenarios. Another one is when we create a pod whose policy is **containers must be put on 3 VMs**, while we currently only have 2 VMs. Thus, we need an auto scaling capability so that a new VM should be added to the cluster in order to satisfy the policy.

**Comment by davidopp** [comment]
> Another one is when we create a pod whose policy is containers must be put on 3 VMs

How do you express this requirement to Kubernetes?

**Comment by dmcnaught** [comment]
@davidopp - it would be part of the deployment spec: http://kubernetes.io/docs/user-guide/deployments/

**Comment by herry13** [comment]
@davidopp @dmcnaught yes, I agree that it should be part of the deployment spec. For me, the pod should have a particular lifecycle whose one of the states is **violating-policy**. If the pod is at this state, the scheduler should re-schedule the pod, which may trigger a creation of one or more VMs.

I will be happy to help you guys to develop this kind of autoscaling capability.

**Comment by bgrant0607** [comment]
@herry13 I assume the requirement of 3 VMs is for availability? 

That sounds like it could be expressed using anti-affinity:
https://github.com/kubernetes/kubernetes/blob/master/docs/design/podaffinity.md
or disruption budget:
https://github.com/kubernetes/kubernetes/issues/12611

As for killing scheduled pods so they can be replaced and scheduled elsewhere, that's related to rescheduling:
https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/rescheduler.md

**Comment by gugahoi** [comment]
+1

**Comment by andrechr** [comment]
+1

**Comment by Smana** [comment]
+1

**Comment by darkhuwk** [comment]
+1

**Comment by jimmycuadra** [comment]
Please stop commenting "+1". Do you all not notice that every such comment is being marked with thumbs down? If you want to follow this issue, click the subscribe button on the right. If you want to express your support of the idea, add a reaction to the original post.

**Comment by ryancox** [comment]
The [cluster autoscaler](https://github.com/kubernetes/contrib/tree/master/cluster-autoscaler) in contrib is a big step toward this. It is GCE only right now bye the looks looks of [this](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cluster_autoscaler.go#L71):

```gogceManager, err := gce.CreateGceManager(migConfigs)
	if err != nil {
		glog.Fatalf("Failed to create GCE Manager: %v", err)
	}```

But it uses the cloudprovider apis, so is a big step towards AWS

**Comment by lattwood** [comment]
One project that may serve as inspiration is supergiant- they do "right sizing" of autoscaling nodes based on the pods it's unable to schedule: https://github.com/supergiant/supergiant

**Comment by fgrzadkowski** [comment]
I believe that cluster autoscaler for GCE is now working, so we should start thinking about porting it to other cloud providers.

@mwielgus Can you look into this in some free cycles? How hard would it be?

Who would be willing to own this? We're happy to share ideas/concepts behind GCE implementation, but I don't we should actually drive the AWS implementation. Someone from the community?

Removing 1.3 milestone & renaming to better describe the current plan (reuse cluster autoscaler controller)

**Comment by pbitty** [comment]
@fgrzadkowski I am interested in contributing a first iteration of the AWS implementation.  We are working on getting production workloads onto Kubernetes at wattpad.com, and getting autoscaling working is my current task.  If no one is working on it, could I submit a PR early next week for some feedback?

**Comment by pbitty** [comment]
I've studied the current version a bit, and my initial plan is to leverage Autoscaling Groups to control the launching and termination of instances.  It looks to me like both the controls for the GCE MIGs, and the AWS ASGs could be put behind a common interface.

**Comment by fgrzadkowski** [comment]
@pbitty It would be great if you could work on the AWS support for this feature! How about having a VC some time next week to discuss details?

**Comment by justinsb** [comment]
If you do a hangout let me know and I'll see if I can join.  Also you can discuss your plans in slack in sig-aws if you want :-)

**Comment by pbitty** [comment]
@fgrzadkowski @justinsb Sounds great!  I am generally available for a hangout  Mon-Wed 11:00-17:00 ET.  I'll also hop on #sig-aws on Slack tomorrow.

**Comment by apobbati** [comment]
@pbitty Have you made any progress on this issue? I'd like to help anyway i can.

**Comment by philk** [comment]
#1377 might be what you're looking for

**Comment by bjoernhaeuser** [comment]
@philk I think the mentioned PR is not what we are looking for. Is there a typo or similar?

**Comment by andrewsykim** [comment]
https://github.com/kubernetes/contrib/issues/1311 is probably the link you are looking for. It references other PRs that have been opened regarding cluster autoscaler for AWS

**Comment by philk** [comment]
Oh, yeah I was on mobile and didn't realize which repo I was in kubernetes/contrib#1377 was what I meant. (Though 1311 above is useful too)

**Comment by aliakhtar** [comment]
What's the status on this feature? I came across this blog: http://blog.kubernetes.io/2016/07/autoscaling-in-kubernetes.html which said AWS auto scaling would be coming in 1.3. The current stable version is 1.3.6, but I can't find any info on this.

The AWS getting started doc says the max / desired instances in the AWS auto scaling group can be set, but do the new AWS instances auto register themselves?

**Comment by fgrzadkowski** [comment]
This blogpost was released after 1.3 and said that AWS support will be ready soon. AFAIK it's already the case.

@mwielgus Can you please verify? Are there instructions how to set it up? Have we released the image? Does it require kubernetes 1.4 or is it just starting different add-on?

**Comment by andrewsykim** [comment]
There's a README [here](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/aws/README.md). I don't think an official image was made so you would have to fork the contrib repo and build/push the image yourself for now.

**Comment by btdlin** [comment]
New to the thread, trying to set up auto-scaling with k8s in aws. Is this supported now? I check the [README](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/aws/README.md), but not sure exactly what needs to be done to build/push the image. Any update would be really appreciated. Thanks.

**Comment by andrewsykim** [comment]
@btdlin you have to build your own docker image on whatever revision we started supporting cluster autoscaler on AWS and push it to your own registry. If you don't want to do that my company has published a public image for our own use cases which has AWS support on it `wattpad/cluster-autoscaler:v1.1`.

**Comment by jimmycuadra** [comment]
Is there going to be an official image for the autoscaler? Why make people build it for themselves?

**Comment by btdlin** [comment]
Thanks @andrewsykim . Looks like [v1.4](https://github.com/kubernetes/kubernetes/releases/tag/v1.4.0) just released a few hours ago, do we know if autoscaler in aws is included in v1.4?

**Comment by andrewsykim** [comment]
@jimmycuadra yes I believe there will be an official docker image already, we just didn't know if it the published one supported aws as a cloud provider so we built our own.

**Comment by fgrzadkowski** [comment]
@mwielgus Can we make sure that cluster autoscaler image is released to an official repo? And I think we should close this issue now, as we support AWS :)

**Comment by danbeaulieu** [comment]
@fgrzadkowski Hi, I am very much interested in this feature but I find the lack of documentation to be an issue. The [README](https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/aws/README.md) leaves a bit to be desired.

- How are instances scaled in? ie is there any Rhyme or reason to which is picked
- Is it possible to have heterogeneous instance types in the cluster?
- By what metrics can I use to scale? CPU usage? container count? etc

I am a heavy AWS user but new to Kubernetes if that helps understand the audience.

**Comment by jimmycuadra** [comment]
Once there is an official image for it, let's make sure the docs for the autoscaler mention where it is!

**Comment by fgrzadkowski** [comment]
We already have a PR inflight for better documentation - https://github.com/kubernetes/contrib/pull/1731 

@mwielgus I think that to improve documentation we will also need:
* point from AWS and GCE readme files to the main one.
* upgrade official docs for cluster autoscaling (http://kubernetes.io/docs/admin/cluster-management/#cluster-autoscaling) to say that we also support AWS.

@mwielgus Can we close this issue as fixed?

**Comment by andyxning** [comment]
@erictune @sstarcher Does monitor the `Pending` pods means that we can use the `InsufficientCPU` or `InsufficientMemory` event to get the same result and based on these events we can add new nodes to the cluster. 

These two type events will be emit when pods can not be scheduled when the required resource(CPU/Memory) can not be fulfilled.

**Comment by fgrzadkowski** [comment]
Quick comments - events where not designed to be the API that other components should depend on. That's why we added `Scheduled` pod condition with reason `Unschedulable`.

**Comment by andyxning** [comment]
@fgrzadkowski IIUC, you mean that event is not reliable and event is not designed to be depended on for usage like this. The most reliable way is to querying pod info and checking for `Scheduled` value of a pod spec.

**Comment by fgrzadkowski** [comment]
Scheduler will emit events, but they are not considered to be part of the api for other components. 

Yes, you should just check pod condition, which is part of PodStatus.

**Comment by motymichaely** [comment]
Hey team, Is there any k8s version aimed for the this feature to be released? Any suggestions for implementing this with AWS ASG + custom metrics?

**Comment by mwielgus** [comment]
The current version of Cluster Autoscaler  (0.4.0) supports AWS ASG. Closing the issue.

**Comment by mwielgus** [comment]
BTW, Cluster Autoscaler is not driven by metrics but rather by the real need for a new node because some pods cannot schedule.
