### ISSUE TITLE
AWS: We should lock down the IAM policies (further)

### ISSUE THREAD

**Issue by justinsb** [kubernetes/kubernetes#11936]
For example, the master currently has blanket permissions on ec2, and the minion has write access to the s3 bucket, but only needs read access.

This may entail giving objects we create a prefix to enable stricter policies.

**Comment by erictune** [comment]
why is the prefix needed?

**Comment by justinsb** [comment]
Not sure whether it's the only way, but the idea would be to do something like we do for S3, where we restrict access to certain buckets by name-prefix: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cluster/aws/templates/iam/kubernetes-master-policy.json

It looks like AWS expanded the list of "matchers" recently, so it might be we can match on tags or VPC also.  This would be much cleaner, I think.

This was more a "we should think about locking the policy down a lot more" than "we have to use prefixes"!  And that came out of the AWS doc I'm writing, which I've had a bunch of people bring up as something that needs improvement.  I'm trying to make sure that the AWS doc links to issues wherever something isn't 100%.

**Comment by justinsb** [comment]
We're not going to be making further changes in kube-up, and we have an active issue in kops to figure out further lock-down: https://github.com/kubernetes/kops/issues/376.  Closing.
