### ISSUE TITLE
[Proposal] k-proxy support zero trust network

### ISSUE THREAD

**Issue by wangfakang** [kubernetes/kubernetes#119358]
### What would you like to be added?

Motivation
===========

Due to business security requirements, developers need to switch the TCP/HTTP services exposed by service to TLS/HTTPS without any impact. However, the current k-proxy does not provide this capability by default. Although ServiceMesh enhances the functionality of Kubernetes Service in the field of service (including governance, security, observability, etc.), it is quite heavy to introduce an additional sidecar if users only focus on security-related capabilities. As mentioned on Istio's official blog:“_Even if a workload just needs simple transport security, administrators still need to pay the operational cost of deploying and maintaining a sidecar_.”

Other issue related: 
* https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-989434131
* https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-1080267041
* https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-1090151570

Alternatives
===========

* enable sidecar Mesh TLS/mTLS 
* enable node Mesh, such as ambient's ztunnel TLS/mTLS or L4 policy
* etc

Proposal
===========

Integrating the universal network security capabilities of zero trust network into the k-proxy or other independent components, allows users of k8s to use it out of the box. The k-proxy/Daemonset with zero trust network architecture is as follows:
![image](https://github.com/kubernetes/kubernetes/assets/8215757/b4f69a7e-59fe-4901-b188-7751963e737b)

Expand the scope of k-proxy(or other independent components)：
* define service route
* TLS、mTLS termination: TLS/mTLS can be transparently enabled for services between nodes and nodes, providing a secure network channel
* L4/L7 authorization policy: Enhance the security access granularity control of service

Limitations
===========
*  headless service will be bypassing k-proxy

### Why is this needed?

* Some users of k8s due to business security requirements, all services need to provide HTTPS, such as: 
   * https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-989434131
   * https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-1080267041
   * https://github.com/kubernetes/kubernetes/issues/106870#issuecomment-1090151570
*  It is quite heavy to introduce an additional sidecar(service mesh) if users only focus on security-related capabilities 
* Zero trust network is a general security capability and should be part of K8s network, such as k-proxy

**Comment by wangfakang** [comment]
> > Expand the scope of k-proxy(or other independent components)：
> 
> I do not think that we are going to increase the scope of k-proxy to create a service mesh, there are already alternatives that handle this better

@aojea Thanks for your reply. As mentioned in the `Why is this needed?
` section of the proposal above: _It is quite heavy to introduce an additional sidecar (service mesh) if users only focus on security related capabilities._
Although node mesh (such as ztunnel) arch reduces complexity compared to sidecar, but it may serially pass through two daemonsetses on the traffic path. So, I propose whether the basic security capability can be part of the K8s network, so that it is optimal for users both in terms of traffic path and out-of-the-box experience.

**Comment by thockin** [comment]
> Although node mesh (such as ztunnel) arch reduces complexity compared to sidecar, but it may serially pass through two daemonsetses on the traffic path

Your drawing shows traffic passing through 2 proxies, too.  I don't see how you can offload the transport security without having 2 actors.   That's literally the ztunnel design (which is basically another form of overlay network).

IMO this is outside the purvey of k8s core.  We are not going to put kube-proxy (in userspace) on the traffic path for all service traffic - there are other projects which are built exactly for this.

**Comment by wangfakang** [comment]
> > Although node mesh (such as ztunnel) arch reduces complexity compared to sidecar, but it may serially pass through two daemonsetses on the traffic path
> 
> Your drawing shows traffic passing through 2 proxies, too. I don't see how you can offload the transport security without having 2 actors. That's literally the ztunnel design (which is basically another form of overlay network).
> 

Sorry, maybe I didn't express clearly. The two proxy scenarios mentioned above are within the scope of a single node, such as `k-proxy(in userspace) ---> Zero trust network daemonset(e.g ztunnel etc)`. 

> IMO this is outside the purvey of k8s core. We are not going to put kube-proxy (in userspace) on the traffic path for all service traffic - there are other projects which are built exactly for this.

Yeah. It may not necessarily be k-proxy, but I'm wondering if this could become part of the k8s network standard.

**Comment by thockin** [comment]
Kube-proxy doesn't actually touch traffic.

**Comment by wangfakang** [comment]
> Kube-proxy doesn't actually touch traffic.

Yes, but the above mode could be allows L3 routing or load balancing and network security to be handled within a Daemonset.

**Comment by thockin** [comment]
Maybe I am still missing your point.  That can already be done with something like a ztunnel. As far as I can tell, you are advocating for ztunnel ;)

**Comment by wangfakang** [comment]
> Maybe I am still missing your point. That can already be done with something like a ztunnel. As far as I can tell, you are advocating for ztunnel ;)

Yeah, the node-mesh(e.g ztunnel etc) architecture can solve the above problems, so my question is whether it may become a part of the k8s network standard.

**Comment by wangfakang** [comment]
> I think that whole space is still young and being explored. Over-standardizing too soon
will kill innovation. The GAMMA project provides some API support for meshy things, but
architecturally, let's let things play out for a while.

Yeah, I couldn't agree more! and looking forward to the early stabilization of this architecture.
Thanks.
