### ISSUE TITLE
kubernetes-ui: Dashboard gauges don't display if cluster contains nodes without persistent filesystems

### ISSUE THREAD

**Issue by cameronbrunner** [kubernetes/kubernetes#11930]
In my test cluster with 2 minions where one does not have any permanent storage (running CoreOS with a RAM only file system) the UI gauges for all nodes fail to render leaving a Kubernetes Dashboard with an empty white 'content' pane.  The The exception I received in chrome was:

```
TypeError: Cannot read property 'length' of undefined
    at maxMemCpuInfo (app.js:919)
    at app.js:840
    at Qn (base.js:22)
    at Function.ke (base.js:22)
    at $scope.getData.k8sApi.getMinions.success.angular.bind.$q.all.then.$scope.loading (app.js:837)
    at u (base.js:6)
    at base.js:6
    at $.$eval (base.js:7)
    at $.$digest (base.js:7)
    at $.$apply (base.js:7)
```

The line throwing the exception is:
```
      for (var i = 0; i < fsDataArray.length; i++) {
```

This appears to be caused by the 'filesystemData' attribute returned by cadvisor being null.  I was able to resolve the issue by creating a disk backed root overlay on my RAM only node.

**Comment by dysinger** [comment]
+1 - I was wondering what the heck happened to the UI guages - I'm using the kube-aws tool on the coreos site to launch a cloudformation of coreos+kubernetes.   No dashboard guages.

**Comment by roberthbailey** [comment]
Moving to the kube-ui project (https://github.com/kubernetes/kube-ui/issues/52).
