### ISSUE TITLE
GKE: metric server crashlooping

### ISSUE THREAD

**Issue by lucagervasi** [kubernetes/kubernetes#119320]
### What happened?

Hi,

I have several (<10) gke clusters, all but one are all in the same condition and I can't figure out what and why is it happening. I hope to find someone that managed to solve the same issue :)

Some time ago, i noticed that our HPA stopped working, having no way to read metrics from pods. Long story short, our pod named "metrics-server-v0.5.2-*" crashloops outputting a stack trace like this one: https://nopaste.net/aA5rwAeBWI and this one: https://nopaste.net/3uQsD6EDfA .

I tried to restart the deployment, without any success. What I don't understand is why one of the clusters (the oldest to be created) is working...

From r/googlecloud it seems aknowledged that is not specifically tied to our workloads and is probably a kubernetes issue (or gke).

All the clusters are updated to the same version: v1.24.12-gke.500 and have been created by terraform resources.

Do any of you have any pointer?

Thanks.

### What did you expect to happen?

HPA should be able to scrape metrics from its endpoint and the metrics should be usable from the hpa itself to compute the optimal scale of the workload.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.12-gke.500", GitCommit:"fa2714567d7451b5e32541c10119d1246730c197", GitTreeState:"clean", BuildDate:"2023-03-23T11:35:05Z", GoVersion:"go1.19.7 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>
Google Cloud Platform
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
VERSION             OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
 v1.24.12-gke.500  Container-Optimized OS from Google   5.10.162+        containerd://1.6.18
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
You should open a support case with Google Cloud, it seems to be a GKE specific problem

/kind support
/close
