### ISSUE TITLE
Kubeadm certs renew needs to support `validity-period` flag

### ISSUE THREAD

**Issue by astraw99** [kubernetes/kubernetes#119350]
### What happened?

Currently, after kubeadm certs expired, we can use `kubeadm certs renew all` to renew the related certs.
But the default renew validity-period is 1 year, defined by:
https://github.com/kubernetes/kubernetes/blob/900237fada63a88b0b1dbb5f8a20ae73b959df12/cmd/kubeadm/app/constants/constants.go#L49

Used by:
https://github.com/kubernetes/kubernetes/blob/900237fada63a88b0b1dbb5f8a20ae73b959df12/cmd/kubeadm/app/util/pkiutil/pki_helpers.go#L653

Need to support `validity-period` flag to allow user to pass.

### What did you expect to happen?

Support `validity-period` flag to allow user to pass.

### How can we reproduce it (as minimally and precisely as possible)?

Use kubeadm to init a cluster, then exec `kubeadm certs renew all`, then will see the validity-period of the renewed certs is 1 year.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> Need to support `validity-period` flag to allow user to pass.

this has been discussed many times. we don't want users to configure long term insecure certificates with kubeadm.

1 year is recommended. if you wish custom validity you can use "kubeadm certs generate-csr".

/close
/area kubeadm
/sig cluster-lifecycle

**Comment by astraw99** [comment]
Got it, thanks.
