### ISSUE TITLE
Resource(CPU, memory, device, topology) managers don't consider restartable init containers

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#119442]
### What happened?

Resource(CPU, memory, topology) managers don't consider restartable init containers.

- [ ] CPU manager: https://github.com/kubernetes/kubernetes/pull/119447
- [ ] Memory manager: https://github.com/kubernetes/kubernetes/pull/120715
- [ ] Device manager: https://github.com/kubernetes/kubernetes/pull/120461
- [ ] Topology manager:

---

When cpu-manager-policy is static and you create a guaranteed pod with a restartable init container,
a restartable init container shares its static CPUs with a regular container.

### What did you expect to happen?

A restartable init container should not share its CPU requirement with the regular containers.

### How can we reproduce it (as minimally and precisely as possible)?

```
$ cat <<EOF | kubectl apply -f - 
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  initContainers:
  - name: init-1
    image: ubuntu
    command:
    - sh
    - -c
    - |
      grep Cpus_allowed_list /proc/self/status | cut -f2
    volumeMounts:
    - name: shared
      mountPath: /tmp/shared
    resources:
      limits:
        cpu: 8
        memory: 100Mi
  - name: restartable-init-2
    image: ubuntu
    command:
    - sh
    - -c
    - |
      grep Cpus_allowed_list /proc/self/status | cut -f2
      sleep 300s
    volumeMounts:
    - name: shared
      mountPath: /tmp/shared
    resources:
      limits:
        cpu: 4
        memory: 200Mi
    restartPolicy: Always
  containers:
  - name: regular-3
    image: ubuntu
    command:
    - sh
    - -c
    - |
      grep Cpus_allowed_list /proc/self/status | cut -f2
      sleep 300s
    resources:
      limits:
        cpu: 4
        memory: 300Mi
    volumeMounts:
    - name: shared
      mountPath: /tmp/shared
  terminationGracePeriodSeconds: 1
  volumes:
  - name: shared
    emptyDir: {}
  restartPolicy: Never
EOF
pod/test created
...
$ kubectl logs test -c init-1
0-3,6-9
$ kubectl logs test -c restartable-init-2
0-1,6-7  # init container and restartalbe init container can share the CPUs, as "init-1" is already terminated and will not restart.
$ kubectl logs test -c regular-3         
0-1,6-7  # restartable init container and regular container should not share the CPUs, as they should run together.
```

/sig node
/kind bug
/assign

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by gjkim42** [comment]
cc @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
/triage accepted

likely will be fixed in 1.29

**Comment by SergeyKanzhelev** [comment]
there is also memorymanager logic here:

https://github.com/kubernetes/kubernetes/blob/c7f79bc2683f6cdedf0081aff259474c881ed166/pkg/kubelet/cm/memorymanager/memory_manager.go#L206-L213

In general, all `AddContainer` calls needs to be reviewed.

**Comment by gjkim42** [comment]
https://github.com/kubernetes/kubernetes/blob/c7f79bc2683f6cdedf0081aff259474c881ed166/pkg/kubelet/cm/devicemanager/manager.go#L334-L345

yes, device manager as well.

**Comment by gjkim42** [comment]
/retitle Resource(CPU, memory, topology) managers don't consider restartable init containers

**Comment by gjkim42** [comment]
@ffromani 
Are you working on the device manager part? If not, I'll take a look at that as well as it looks critical as you said.
https://github.com/kubernetes/kubernetes/pull/119447#issuecomment-1645161004

**Comment by ffromani** [comment]
@gjkim42 not yet working on that, feel free to take, I can review. Otherwise I plan to start working on this area late this week or early next week.

**Comment by gjkim42** [comment]
I'll try it this week and let you know.

**Comment by SergeyKanzhelev** [comment]
this is fixed

/close

@gjkim42 please reopen if anything is left
