### ISSUE TITLE
Node not ready for ~10min - no log by kubelet

### ISSUE THREAD

**Issue by modzilla99** [kubernetes/kubernetes#119438]
### What happened?

Sometimes nodes suddenly transition into NotReady and don't seem to work for no apparent reason. Within that time (about 10min last time) the kubelet does not log anything, but the kube-proxy logs `iptables ChainExists` a bunch of times, until the nodes back up.

### What did you expect to happen?

The node to be Ready the whole time

### How can we reproduce it (as minimally and precisely as possible)?

I do not know.

### Anything else we need to know?

[kube-proxy.log](https://github.com/kubernetes/kubernetes/files/12094879/kube-proxy.log)
[kubelet.log](https://github.com/kubernetes/kubernetes/files/12094884/kubelet.log)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"archive", BuildDate:"2023-06-15T00:00:00Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:23:26Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
OpenStack
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36.20220723.3.1 (CoreOS)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora CoreOS 36.20220723.3.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='36.20220723.3.1'
DEFAULT_HOSTNAME=localhost
$ uname -a
Linux prod-worker-64-u46ugwbo5zil-node-14 5.18.13-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jul 22 14:03:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>
Magnum?
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd-v1.6.6</br>
cgroupsv1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel:v0.19.0
cinder-csi-plugin:v1.24.0
</details>

**Comment by HirazawaUi** [comment]
Can you provide `kubectl get event` and `kubectl describe node` output?
/sig node
/triage needs-information

**Comment by SergeyKanzhelev** [comment]
is kubelet process even alive during this time? What condition the node has to become not ready?

**Comment by modzilla99** [comment]
> Can you provide `kubectl get event` and `kubectl describe node` output? /sig node /triage needs-information

Unfortunately I cannot provide you that information, when I was informed by my colleague, the information weren't present anymore. But I'll do that if and when it happens again

**Comment by modzilla99** [comment]
> is kubelet process even alive during this time? What condition the node has to become not ready?

I'm not sure, sorry!

**Comment by dipankardas011** [comment]
@modzilla99 can you check the logs of kubelet by directly ssh into the nodes?

**Comment by aojea** [comment]
That node seems to have serious resource problems causing network issues and failing to communicate with the apiserver, most probably is not ready because is not updating the lease on time and the node lifecycle controller sets it notReady

> Jul 18 13:33:49 prod-worker-64-u46ugwbo5zil-node-14 kubelet[3837]: E0718 13:27:45.692545    3837 kubelet_node_status.go:460] "Error updating node status, will retry" err="error getting node \"prod-worker-64-u46ugwbo5zil-node-14\": context deadline exceeded"


> Jul 18 13:27:12 prod-worker-64-u46ugwbo5zil-node-14 kube-proxy[3924]: I0718 13:27:08.820615       1 proxier.go:820] "SyncProxyRules complete" elapsed="4m11.079021411s"

**Comment by modzilla99** [comment]
> That node seems to have serious resource problems causing network issues and failing to communicate with the apiserver, most probably is not ready because is not updating the lease on time and the node lifecycle controller sets it notReady

This seems to be pretty likely. It hasn't happened since, so I'll close this issue for now and reopen it needed. Thanks!
