### ISSUE TITLE
Resource validation not happening for statefulset but it is present for deployment 

### ISSUE THREAD

**Issue by ankit21990** [kubernetes/kubernetes#119435]
When we give request greater than limits, then kubectl apply gives below error incase of deployment

Deployment: Deployment.apps "eric-bss-em-fm-rizserver" is invalid: spec.template.spec.containers[2].resources.requests: Invalid value: "5Gi": must be less than or equal to memory limit.

But incase of statefulset, kubectl accepts invalid statefulset. Error should come up like deployment.

Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"d17655dc06fd0851903be58a7c77456043dbfed6", GitTreeState:"clean", BuildDate:"2022-12-30T14:05:08Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"d17655dc06fd0851903be58a7c77456043dbfed6", GitTreeState:"clean", BuildDate:"2022-12-30T13:53:20Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ankit21990** [comment]
We want kubectl to fail for statefulset just like deployment when we give request value greater than limits.

Deployment: Deployment.apps "eric-bss-em-fm-rizserver" is invalid: spec.template.spec.containers[2].resources.requests: Invalid value: "5Gi": must be less than or equal to memory limit.

But for statefulset, no such error when we give requests greater than limits. We see warnings in statefulset description. Ideally kubectl command should not accept this config (request > limits) for statefulset.

**Comment by gautamsoni17990** [comment]
I am also facing same error in case of helm installation.

Suppose in my helm chart I am using multiple deployment and statefulset. In case of requests higher than limits in sts my helm chart should be failed but its installed without any error
