### ISSUE TITLE
Need assistance with installing Kubeadm on RHEL 9.2 Linux server

### ISSUE THREAD

**Issue by shivkumarpatil** [kubernetes/kubernetes#119482]
I am unable to install kubeadm on RHEL 9.2 Linux Server.

Please suggest me how can i install kubeadm.

**Comment by sftim** [comment]
**GitHub is not the right place for support requests.**

For help with setting up Kubernetes, try asking on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by ahmed82** [comment]
Check out that link  [Getting Started with Kubernetes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_kubernetes/index
)  By Red Hat : https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html-single/getting_started_with_kubernetes/index

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
