### ISSUE TITLE
[ARM] Probing container should *not* be restarted with a /healthz http liveness probe

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119455]
##### Error text:
```
[FAILED] pod container-probe-5827/test-webserver-02707b37-db67-4667-84fe-9b8698ea540e - expected number of restarts: 0, found restarts: 2. Pod status: &PodStatus{Phase:Running,Conditions:[]PodCondition{PodCondition{Type:Initialized,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2023-07-13 08:40:47 +0000 UTC,Reason:,Message:,},PodCondition{Type:Ready,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2023-07-13 08:43:21 +0000 UTC,Reason:,Message:,},PodCondition{Type:ContainersReady,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2023-07-13 08:43:21 +0000 UTC,Reason:,Message:,},PodCondition{Type:PodScheduled,Status:True,LastProbeTime:0001-01-01 00:00:00 +0000 UTC,LastTransitionTime:2023-07-13 08:40:47 +0000 UTC,Reason:,Message:,},},Message:,Reason:,HostIP:172.31.33.122,PodIP:10.22.1.26,StartTime:2023-07-13 08:40:47 +0000 UTC,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:test-webserver,State:ContainerState{Waiting:nil,Running:&ContainerStateRunning{StartedAt:2023-07-13 08:43:21 +0000 UTC,},Terminated:nil,},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:2,Signal:0,Reason:Error,Message:,StartedAt:2023-07-13 08:42:00 +0000 UTC,FinishedAt:2023-07-13 08:43:03 +0000 UTC,ContainerID:containerd://ac0bfa0fb1e83a6bec13c381b03ea4f8ace81e5689ba91d46d843f23d3e0c2a5,},},Ready:true,RestartCount:2,Image:registry.k8s.io/e2e-test-images/agnhost:2.45,
```
#### Recent failures:
[2023/7/20 03:50:32 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1681753010989961216)
[2023/7/19 21:50:35 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1681662412819795968)
[2023/7/19 15:50:37 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1681571814989369344)
[2023/7/19 09:49:37 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1681480965479731200)
[2023/7/19 03:49:32 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1681390367271817216)

/kind failing-test

/sig node

/cc @chendave

**Comment by chendave** [comment]
thanks @pacoxu ,  yes, arm CI needs take some time to stabilize.

/cc @dims 
/cc @ruquanzhao

**Comment by pacoxu** [comment]
Several other failures can be found in https://storage.googleapis.com/k8s-triage/index.html?job=ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks.

- E2eNode Suite [It] [sig-storage] Projected downwardAPI should update annotations on modification [NodeConformance] [Conformance]:  failure case is: https://storage.googleapis.com/k8s-triage/index.html#f827780110fc4eb0702e.

**Comment by dims** [comment]
@ruquanzhao nice catch! fixing in https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/81

cc @tzneal @cartermckinnon

**Comment by dims** [comment]
@ruquanzhao started a couple of runs, let's watch them - https://prow.k8s.io/?job=ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks

**Comment by dims** [comment]
finally got it working https://testgrid.k8s.io/sig-node-containerd#cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks

needed another one! https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/83

**Comment by pacoxu** [comment]
> finally got it working https://testgrid.k8s.io/sig-node-containerd#cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks
> 
> needed another one! [kubernetes-sigs/provider-aws-test-infra#83](https://github.com/kubernetes-sigs/provider-aws-test-infra/pull/83)

`Probing container` tests are passed now. 
@dims @ruquanzhao  Thanks.

---

Three test cases below keep failing: 

- E2eNode Suite: [It] [sig-node] Security Context [NodeConformance][LinuxOnly] Container PID namespace sharing containers in pods using isolated PID namespaces should all receive PID 1 expand_more1m26s 
- E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api expand_more3m19s 
- E2eNode Suite: [It] [sig-node] Security Context [NodeConformance][LinuxOnly] Container PID namespace sharing processes in containers sharing a pod namespace should be able to see each other

**Comment by pacoxu** [comment]
/close
as the failing-test cases that is descripted in this issue are fixed.

**Comment by chendave** [comment]
thanks @pacoxu !  pls keep us noted for all arm related failures.
