### ISSUE TITLE
Performance degradation on scoring

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#119440]
### What happened?

/sig scheduling
/kind regression

#118606 caused a performance degradation in the 5k nodes scalability tests
![image](https://github.com/kubernetes/kubernetes/assets/1299064/3d8c8fa0-7fae-4317-bc17-8b26ddeadbf9)

The PR changed how to split the load among parallel threads. Previously, we would parallelize over the number of nodes. The PR does it over the number of plugins, which is much smaller.

### What did you expect to happen?

Performance to improve or remain the same

### How can we reproduce it (as minimally and precisely as possible)?

https://perf-dash.k8s.io/#/?jobname=kubemark-5000Nodes-scheduler&metriccategoryname=Scheduler&metricname=SchedulingLatency&Operation=Score&TestName=pod-anti-affinity

### Kubernetes version

1.28

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alculquicondor** [comment]
Depending on how many cores you have available, you might just overload the routines.

I think it's better to revert the parallizer over plugins while keeping the change from map to slice. Although I don't expect a major impact for the latter. You might want to run a profiler for the benchmark with a higher number of nodes.

**Comment by AxeZhan** [comment]
I'll create a revert version first :)

**Comment by kerthcet** [comment]
Let's revert this first since we reached the code freeze.

**Comment by sanposhiho** [comment]
Sorry for causing this trouble and thanks everyone for a prompt action 🙏
