### ISSUE TITLE
api: Finalizer name format is not enforced for custom resources

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/kubernetes#119445]
### What happened?

A client is allowed to add custom finalizers to Custom Resources with a finalizer name that's not fully qualified (e.g. `example` or `example.com`).

However they're prevented from doing the same on builtin resource types, returning the following error:

    Invalid value: "finalizers.compute.linkedin.com": name is neither a standard finalizer name nor is it fully qualified

### What did you expect to happen?

Per [Custom Resource Definition docs](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers:~:text=Identifiers%20of%20custom%20finalizers%20consist%20of%20a%20domain%20name%2C%20a%20forward%20slash%20and%20the%20name%20of%20the%20finalizer), custom finalizer names are expected to be in format "consist of a domain name, a forward slash and the name of the finalizer" (e.g. `foo.bar/name`).

Therefore, I expected the enforcement to be the same for CRs and builtin types.

### How can we reproduce it (as minimally and precisely as possible)?

1. have a custom resource on the cluster
2. `kubectl edit` it to add `finalizers: [example.com]`
3. observe the edit does not fail
4. do the same on a builtin resource (e.g. Namespace or Pod), observe it fails

### Kubernetes version

Reproducible at least starting from 1.21 and still on latest versions.

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:38Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-05-12T19:05:23Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Cloud provider

<details>N/A kind cluster
</details>

### OS version

<details>N/A - kind cluster accessed via macOS
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by nayihz** [comment]
There is no validation of finalizer  in `(a customResourceValidator) ValidateUpdate()` and `ValidateObjectMetaAccessorUpdate`.
Please unassign me if you guys have started to work on it. 
/assign

**Comment by liggitt** [comment]
> There is no validation of finalizer in `(a customResourceValidator) ValidateUpdate()` and `ValidateObjectMetaAccessorUpdate`.

it is called from here on custom resources:

https://github.com/kubernetes/kubernetes/blob/4e8908d56671c1bae588151d1d2fcbd4fa56b049/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L103-L149

https://github.com/kubernetes/kubernetes/blob/4e8908d56671c1bae588151d1d2fcbd4fa56b049/staging/src/k8s.io/apiserver/pkg/registry/rest/update.go#L87-L97

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L155-L191

**Comment by nayihz** [comment]
`ValidateFinalizers` lacks validation for finalizer name.
```go
if len(strings.Split(stringValue, "/")) == 1 {
	if !IsStandardFinalizerName(stringValue) {
		return append(allErrs, field.Invalid(fldPath, stringValue, "name is neither a standard finalizer name nor is it fully qualified"))
        }
}
```
