### ISSUE TITLE
container runtime and kubeadm init not working unbuntu 22.04:  error execution phase preflight: [preflight] Some fatal errors occurred:

### ISSUE THREAD

**Issue by henzbnzr** [kubernetes/kubernetes#119439]
### What happened?

while installing k8 cluster through ubuntu on oracle vm found this issue.
docker engine is working :[Version:  20.10.13] kubeadm,kubectl,kubelet  successfully working.
The issue occured when executing" kubeadm init --apiserver-advertise-address=192.168.100.42"

### What did you expect to happen?

cluster up after kubadm init command

### How can we reproduce it (as minimally and precisely as possible)?

all setup is ready,
kubadm init always unsuccessful,

### Anything else we need to know?

nil

### Kubernetes version

```console
$ kubectl version:1.27.3-00

# paste output here
```[init] Using Kubernetes version: v1.27.3
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR CRI]: container runtime is not running: output: time="2023-07-19T12:25:38Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/containerd/containerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher


</details>


### Cloud provider

virtual box oracle new version 6


### OS version

<details>

```console putty
# On Linux:
$ cat /etc/os-release

root@masternode-cluster:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


$ uname -a


Linux masternode-cluster 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                                    OSArchitecture  Version
22621        Microsoft Windows 11 Home Single Language  64-bit          10.0.22621

</details>


### Install tools

virtaul box oracle 


### Container runtime (CRI) and version (if applicable)

<details>

</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

installing K8 on ubuntu virtual box three vm model.
kubeadm init always failure.
couldnt able to join wnodes

**Comment by HirazawaUi** [comment]
Can you provide the error output for `kubeadm init`?
/remove-kind bug
/kind support

**Comment by henzbnzr** [comment]
root@masternode-cluster:~# kubeadm init --apiserver-advertise-address=192.168.100.42
[init] Using Kubernetes version: v1.27.3
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-6443]: Port 6443 is in use
        [ERROR Port-10259]: Port 10259 is in use
        [ERROR Port-10257]: Port 10257 is in use
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
        [ERROR FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
        [ERROR Port-10250]: Port 10250 is in use
        [ERROR DirAvailable--var-lib-etcd]: /var/lib/etcd is not empty
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Comment by HirazawaUi** [comment]
The reason for the error is that you have run `kubeadm init before`, so you need to executed the cleanup first, ref: [tear-down](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#tear-down)

**Comment by henzbnzr** [comment]
I suspect the problem that , i am using laptop with 8G ram which sharing 4G to master .
would it be problem as kubelet service still not loaded, seems fluctuating
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: active (running) since Wed 2023-07-19 15:51:02 UTC; 2ms ago
       Docs: https://kubernetes.io/docs/home/
   Main PID: 2741 (kubelet)
      Tasks: 1 (limit: 4556)
     Memory: 36.0K
        CPU: 351us
     CGroup: /system.slice/kubelet.service
             └─2741 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml

Jul 19 15:51:02 master-node systemd[1]: Started kubelet: The Kubernetes Node Agent.
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-07-19 15:51:02 UTC; 6s ago
       Docs: https://kubernetes.io/docs/home/
    Process: 2741 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2741 (code=exited, status=1/FAILURE)
        CPU: 82ms
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-07-19 15:51:13 UTC; 2s ago
       Docs: https://kubernetes.io/docs/home/
    Process: 2751 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2751 (code=exited, status=1/FAILURE)
        CPU: 73ms
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-07-19 15:51:13 UTC; 6s ago
       Docs: https://kubernetes.io/docs/home/
    Process: 2751 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2751 (code=exited, status=1/FAILURE)
        CPU: 73ms
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-07-19 15:51:23 UTC; 876ms ago
       Docs: https://kubernetes.io/docs/home/
    Process: 2763 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2763 (code=exited, status=1/FAILURE)
        CPU: 74ms
root@master-node:~# systemctl status  kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Wed 2023-07-19 15:51:23 UTC; 3s ago
       Docs: https://kubernetes.io/docs/home/
    Process: 2763 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS (code=exited, status=1/FAILURE)
   Main PID: 2763 (code=exited, status=1/FAILURE)
        CPU: 74ms
root@master-node:~#
