### ISSUE TITLE
In case of node reboot, pod running on that node goes to "Unknown" state, as kubelet fails to attach the PVC associated

### ISSUE THREAD

**Issue by akankshapanse** [kubernetes/kubernetes#119401]
### What happened?

Given a Kubernetes cluster with Windows worker nodes and a vSphere CSI driver installed, when a worker node is rebooted, pod, running on the restarting node, goes to "Unknown" state from a "Running" state, and remains in same "Unknown" state forever.
The error seen in corresponding pod description for both of the above cases is as shown below:

```
  Warning  FailedMount  9m11s (x2131 over 3d)  kubelet  MountVolume.MountDevice failed for volume "pvc-X-X-X-X-X" : kubernetes.io/csi: attacher.MountDevice failed to create dir "\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\csi.vsphere.vmware.com\\XXXXX\\globalmount":  mkdir \var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\XXXXX\globalmount: Cannot create a file when that file already exists.
  Warning  FailedMount  3m42s (x1495 over 3d)  kubelet  Unable to attach or mount volumes: unmounted volumes=[<abc>], unattached volumes=[<abc> kube-api-access-8dqhl]: timed out waiting for the condition
```

If the pod in this state is deleted forcefully and gets rescheduled on same node, it does not enter "Running" state but remains in "ContainerCreating" state forever with same error in pod description as above case.

The error above states that during `MountDevice()` in `csi_attacher.go`, kubelet fails to create staging target path directory as the directory already exists.

Before the change done by PR https://github.com/kubernetes/kubernetes/pull/88759, kubelet was checking if staging target directory is present and mounted already, but the check was removed considering that mount point related checks should be done at CSI driver level, not generally at kubelet level. 

However, in cases of node shutdown/reboot, unmount and removal of the staging target path directory may not be possible or may fail for various reasons, which would leave the staging directory created on that node as it is. So, when the pod gets re-scheduled on that same node, and kubelet tries to create the directory again, it fails at https://github.com/kubernetes/kubernetes/blob/a8b90c9008609913c3b9b8f5b146e68d9ec8146f/pkg/volume/csi/csi_attacher.go#L342.

Similar code exists in `SetUpAt()` in `csi_mounter.go` ( https://github.com/kubernetes/kubernetes/blob/a8b90c9008609913c3b9b8f5b146e68d9ec8146f/pkg/volume/csi/csi_mounter.go#L211 ), that can also lead to same issue before NodePublishVolume().

The issue was seen originally in context of Windows worker node. However, the kubelet code is common regardless of OS flavors. Thus, the issue can be seen in case of Linux worker node as well.

### What did you expect to happen?

kubelet should handle node reboot/restart like cases, where the staging target path directory for the PVC can be already present on the node and let the corresponding CSI driver handle the further processing on that target directory in `NodeStageVolume()` and `NodePublishVolume()`, similar to earlier commit done for another issue (Reference: https://github.com/kubernetes/kubernetes/pull/88569/files#diff-227f84916ffb93ece42ccaec840af8ea265714440c15c45f42b08d6a427a57bfR319).

### How can we reproduce it (as minimally and precisely as possible)?

Node reboot or restart or poweroff-on scenario to be executed 

### Kubernetes version

v1.24.7

### Cloud provider

On-premise datacenter

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

CSI plugin: vSphere CSI driver with latest source code

**Comment by xing-yang** [comment]
@akankshapanse Can you add a check here to see if the error code suggests the file exists and if so, continue? 
https://github.com/kubernetes/kubernetes/blob/a8b90c9008609913c3b9b8f5b146e68d9ec8146f/pkg/volume/csi/csi_attacher.go#L342

**Comment by xing-yang** [comment]
@akankshapanse Any luck testing the fix?  Also the function mkdir may return success on linux vs error on windows when the dir already exists.

**Comment by akankshapanse** [comment]
> @akankshapanse Any luck testing the fix? Also the function mkdir may return success on linux vs error on windows when the dir already exists.

not yet.
Considering different behavior of the function mkdir, we can explicitly check for presence of the directory first and if not found, call mkdir to create it. Does that make sense ?

**Comment by akankshapanse** [comment]
> > @akankshapanse Any luck testing the fix? Also the function mkdir may return success on linux vs error on windows when the dir already exists.
> 
> not yet. Considering different behavior of the function mkdir, we can explicitly check for presence of the directory first and if not found, call mkdir to create it. Does that make sense ?

@xing-yang I could test the fix locally where I check for path existence before creating the directory in kubelet and now the control gets passed to corresponding CSI driver to handle the case. Will raise PR with the changes soon.

**Comment by akankshapanse** [comment]
@msau42 can you please tell whether this issue looks related to https://github.com/kubernetes/kubernetes/issues/115148 ?

**Comment by jsafrane** [comment]
I don't have resources (i.e. Windows nodes) to debug the issue, but `MkdirAll` already checks if the target exists and returns no error, even on Windows: https://cs.opensource.google/go/go/+/refs/tags/go1.20.7:src/os/path.go;l=18-26

It seems that Windows has a different `Mount` semantics, it creates the parent dir (`\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\XXXXX\`) and then creates a `global` link there, not a directory. There are traces of this behavior in vSphere in-tree volume code:
https://github.com/kubernetes/kubernetes/blob/0a37f09c32bca1c7b1217d293f9bec63c4af6de1/pkg/volume/vsphere_volume/vsphere_volume.go#L240-L249

CSI spec [says](https://github.com/container-storage-interface/spec/blob/98031ee88670956fd20b2333250ac6e03dc85222/csi.proto#L1320C1-L1327) that:

>   // The path to which the volume MAY be staged. It MUST be an
  // absolute path in the root filesystem of the process serving this
  // request, and MUST be a directory. The CO SHALL ensure that there
  // is only one `staging_target_path` per volume. The CO SHALL ensure
  // that the path is directory and that the process serving the
  // request has `read` and `write` permission to that directory. The
  // CO SHALL be responsible for creating the directory if it does not
  // exist.

It IMHO does not allow the CSI driver to replace the directory with a link, at least not in NodeStage.  Just reading the spec with almost no Windows knowledge, I'd expect that drivers put a link to the device root dir into the `global` directory, e.g. as `\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\XXXXX\global\link`. What other CSI drivers do on Windows? Shall we rephrase the spec for Windows and then fix kubelet?

NodePublish can be a different story, because it's created by the driver and Kubernetes should create only the parent dir:

>   // The path to which the volume will be published. It MUST be an
  // absolute path in the root filesystem of the process serving this
  // request. The CO SHALL ensure uniqueness of target_path per volume.
  // The CO SHALL ensure that the parent directory of this path exists
  // and that the process serving the request has `read` and `write`
  // permissions to that parent directory.
  // For volumes with an access type of block, the SP SHALL place the
  // block device at target_path.
  // For volumes with an access type of mount, the SP SHALL place the
  // mounted directory at target_path.
  // Creation of target_path is the responsibility of the SP.

Here it's pretty clear, kubelet must `MkdirAll` the parent dir and it already works the same on Linux and on Windows, i.e. does nothing when the directory already exists. The driver should "place the mounted directory" there, so if "mount" means "link" on Windows, then kubelet is IMO fine with that.

**Comment by msau42** [comment]
cc @mauriciopoppe

**Comment by akankshapanse** [comment]
`It seems that Windows has a different Mount semantics, it creates the parent dir (\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\XXXXX\) and then creates a global link there, not a directory. There are traces of this behavior in vSphere in-tree volume code:`
vSphere in-tree volume code points to NodePublishVolume() case at SetUpAt() function, not NodeStageVolume().

`It IMHO does not allow the CSI driver to replace the directory with a link, at least not in NodeStage. Just reading the spec with almost no Windows knowledge, I'd expect that drivers put a link to the device root dir into the global directory, e.g. as \var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\XXXXX\global\link. What other CSI drivers do on Windows? Shall we rephrase the spec for Windows and then fix kubelet?`
Along with vSphere CSI driver, I also checked Azure disk CSI driver and Google compute-persistent-disk-csi-driver, where in NodeStageVolume(), we expect the staging target directory (\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\<PV/PVC ID>\globalmount) to be already created by kubelet and later it formats and **mounts** the device at the path. There is no symlink created here. Not sure if csi proxy MountVolume() method also creates symlink inside, instead of actual mount.
However, on the local setup where the issue has been reproduced, I found this pre-created staging directory has both directory and symlink mode marked.

https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver/blob/6145c8f405d14541ae4b8923f46e3b4d072cb6a1/pkg/mount-manager/safe-mounter-v1_windows.go#L271

`Here it's pretty clear, kubelet must MkdirAll the parent dir and it already works the same on Linux and on Windows, i.e. does nothing when the directory already exists. The driver should "place the mounted directory" there, so if "mount" means "link" on Windows, then kubelet is IMO fine with that.`
Yes. For NodePublishVolume() case, in windows, we do create a symlink inside parent directory. However for parent directory, we may face the same issue if not cleaned up successfully in the volume tear down before.

**Comment by akankshapanse** [comment]
@jsafrane @mauriciopoppe @msau42 another query regarding this bug - till the time this issue gets fixed, if a user comes across this scenario due to abrupt shutdown/reboot of worker node or any other case, how can one recover or workaround from this issue?

**Comment by akankshapanse** [comment]
> > Along with vSphere CSI driver, I also checked Azure disk CSI driver and Google compute-persistent-disk-csi-driver, where in NodeStageVolume(), we expect the staging target directory (\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com<PV/PVC ID>\globalmount) to be already created by kubelet and later it formats and mounts the device at the path. There is no symlink created here.
> 
> Question is, what is `global/` on the filesystem. Because MkdirAll calls `IsDir()` and most probably gets `false` or error. Can you please debug where exactly MkdirAll returns error? That part should be fixed.

As you suggested, I debugged further to know exact place where os.MkdirAll returns the failure and as you mentioned correctly, it failed at IsDir() call https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/os/path.go;drc=2291cae2af659876e93a3e1f95c708abb1475d02;l=53 since the filemode returned here is "Symbolic Link", not "Directory". Hence the function returned original error by MkDir() function, instead of succeeding for already existing directory path.
Also, as per https://en.wikipedia.org/wiki/NTFS_volume_mount_point NTFS mount points are implemented as reparse-point (similar to symlink) and do not represent actual directory. So, for windows worker nodes, in os.MkdirAll(), we should not check for presence of directory, rather a symlink. 

As you said previously, I agree that CSI spec should be reworded to consider Windows case.

Considering the mount point behavior on Windows, CSI drivers supporting windows are taking care of the symlink check correctly in IsLikelyMountPoint() function calls. Hence if kubelet checks for path already present and skips the handling to CSI drivers as done via https://github.com/kubernetes/kubernetes/pull/119735, things can work correctly.

However, what I observed on setup with issue reproduced is, "dir" command run on the corresponding windows worker node shows the staging dir path filemode as "directory + symlink". May be this could be false-positive.

`
PS C:\var\lib\kubelet\plugins\kubernetes.io\csi\csi.vsphere.vmware.com\<volumeID-hash>
8a> dir
    b1c2b36d65ba28a

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----l        7/29/2023  11:08 PM                globalmount   <<< d=directory, l=symlink/reparse-point
-a----        7/29/2023  11:08 PM             94 vol_data.json
`

Please let me know your comments.

**Comment by akankshapanse** [comment]
closing the issue as the fix done via https://github.com/kubernetes/kubernetes/pull/119735
