### ISSUE TITLE
incorrect removal of components due to incorrect work of finalizers

### ISSUE THREAD

**Issue by Nello-Angelo** [kubernetes/kubernetes#119450]
### What happened?

Always when i try to delete chart of [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) the finalizers cant finish correct and because of that i cant delete namespace with victoria metrics components 

and that happend with different components of kubernetes

![Screenshot_5](https://github.com/kubernetes/kubernetes/assets/82488489/5ce38598-52a9-4b31-b394-d6640f6112b9)

### What did you expect to happen?

removal components of chart 

### How can we reproduce it (as minimally and precisely as possible)?

install chart of [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and delete via lens and helm

### Anything else we need to know?

[victoria-metrics-stack.zip](https://github.com/kubernetes/kubernetes/files/12100243/victoria-metrics-stack.zip)

### Kubernetes version

kubernetes 1.25.8

### Cloud provider

<details>

</details>

### OS version

Debian GNU/Linux 11 (bullseye)
Kernel version 5.10.0-21-amd64

### Install tools

helm

### Container runtime (CRI) and version (if applicable)

containerd

### Related plugins (CNI, CSI, ...) and versions (if applicable)

calico

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
