### ISSUE TITLE
Pod status phase coming "Succeeded" when "no space left on device"

### ISSUE THREAD

**Issue by RATANAJANGIR** [kubernetes/kubernetes#119481]
### What happened?

Hi I need help here,
I am running "argo submit workflow.yaml  ........" command.
Here when pod is running phase issue is came with "no space left on device" after that pod phase is succeeded and here few logs of command get displayed from "workflow.yaml" argo workflow template.

here is full logs of pod

`time="2023-07-18T13:10:20.175Z" level=error msg="unable to decode or infer timestamp from log line: parsing time \"failed\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"failed\" as \"2006\"" namespace=dpsworkflow podName=edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803 workflow=edp-airflow-app-feature-upgrade-packages-workflow-180723130647
edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803: Warning: Platform requested deprecated API '0.3'
edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803: Warning: CNB_PLATFORM_API is unset; using Platform API version '0.3'
edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803: CNB_PLATFORM_API should be set to avoid breaking changes when upgrading the lifecycle
edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803: failed to watch file "/var/log/pods/dpsworkflow_edp-airflow-app-feature-upgrade-packages-workflow-180723130647-dps-buildpack-3787918803_1f6aa596-715d-4af7-8356-1935bf145a42/main/0.log": no space left on device
Finishing: Branches
`

### What did you expect to happen?

I am expecting pod in failed status phase

### How can we reproduce it (as minimally and precisely as possible)?

when doing restart is working

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: "v1.25.0"
Kustomize Version: v4.5.7
Server Version: "v1.24.9+vmware.1"
```

</details>

### Cloud provider

<details>
on-premises data centers
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
Have you tried opening this up on [argo-workflows](https://github.com/argoproj/argo-workflows)?

**Comment by RATANAJANGIR** [comment]
@kannon92 yes https://github.com/argoproj/argo-workflows/issues/11411

**Comment by kannon92** [comment]
Sorry I don’t have an idea about Argo. They did respond to your issue so I think we should close this issue.

/close
