### ISSUE TITLE
The [client certificate used by] kubelet can view all node and pod resources

### ISSUE THREAD

**Issue by sunnoy** [kubernetes/kubernetes#119470]
### What would you like to be added?

In the current node authentication mode, the client certificate used by kubelet can view all node and pod resources. Once the node is compromised, the cluster information will be leaked.

### Why is this needed?

using kubelet's client can only view resources belonging to its own node

**Comment by sftim** [comment]
/retitle The [client certificate used by] kubelet can view all node and pod resources

**Comment by stlaz** [comment]
This work requires a KEP - see the "Needs KEP" document - https://docs.google.com/document/d/1sY8fRyRtk4eG9R439z5ao5i9bFuuxilS03XaNlqoni0.

This was discussed on sig-auth meeting previously and there is currently no bandwidth to handle the request.
