### ISSUE TITLE
Mark releases as latest based on kubernetes versions and not release order

### ISSUE THREAD

**Issue by danilapog** [kubernetes/kubernetes#119474]
### What would you like to be added?

Hello!
Mark releases as latest based on kubernetes versions and not release time

### Why is this needed?

I have a ci process that validates kubernetes manifests and checks for deprecated or removed apis. The check is always via pluto and the target version is taken from this repository via the github-api from release marked as latest. Now I noticed that the latest labels are affixed to the latest released version by time, and not to minor/major releases

What exactly i mean:

Now i see, that release **1.24.16** market as latest, but more logical mark as latest **1.27.4**

**Comment by sftim** [comment]
If we'd like to write tests, we can compare info from https://github.com/kubernetes/website/blob/main/data/releases/schedule.yaml to the info from GitHub's API.

**Comment by danilapog** [comment]
Okay, this seems to be a duplicate of **[this #119472 issue.]**(https://github.com/kubernetes/kubernetes/issues/119472)
I think it can be closed.
@sftim Thanks you for the quick response!
