### ISSUE TITLE
NodeLogQuery tests don't seem to be running anywhere

### ISSUE THREAD

**Issue by haircommander** [kubernetes/kubernetes#119576]
Test failures for the NodeLogQuery tests were discovered when integrating 1.28 into [openshift](https://github.com/openshift/kubernetes/pull/1646)

https://github.com/kubernetes/kubernetes/pull/119571 fixes these issues, but I can't seem to find evidence they were running anywhere in the first place. 

Opening this to track that as requested https://github.com/kubernetes/kubernetes/pull/119571#pullrequestreview-1546437473 cc @SergeyKanzhelev

**Comment by kannon92** [comment]
Just curious, any idea where someone would add these?

**Comment by aravindhp** [comment]
@marosset has added this to [ci-kubernetes-e2e-capz-master-windows-alpha](https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-capz-master-windows-alpha) but we need to some more work to get it working against Windows nodes.

Ref: https://github.com/kubernetes-sigs/windows-testing/pull/385

**Comment by aravindhp** [comment]
/close

The NodeLogQuery tests are now running as a daily periodic: [capz-master-windows-alpha-nodelogquery](https://testgrid.k8s.io/sig-windows-master-release#capz-master-windows-alpha-nodelogquery)
