### ISSUE TITLE
Kubelet panic when allocates device for pods.

### ISSUE THREAD

**Issue by payall4u** [kubernetes/kubernetes#119560]
### What happened?

It is suspected to be a concurrent bug of kubelet.

When we delete the last pod that requires GPU on the node and create two or more pods that require GPU at the same time, kubelet may panic on `allocateContainerResources` as following.

I think it's a concurrency issue.

1. Create a pod with GPU request, then kubelet will allocate resource for it. Kubelet try call device plugin to choose preferred device for it. **It will unlock the mutex!.** https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L984-L1006
2. Then we delete the last pod that requires GPU.
3. Create the second pod with GPU request, kubelet will allocate resource for it also. Kubelet will call `UpdateAllocatedDevices` to recalculate device (delete allocated device if pod deleted). It will update the **allocatedDevices** map of ManagerImpl, because of mutex is unlock by step 1. https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/cm/devicemanager/manager.go#L519-L543
4.  Kubelet continues with the first pod. If **allocatedDevices** has changed and GPU device is nil, kubelet will panic in the closure allocateRemainingFrom.

```
Jul 25 16:39:40 VM-253-55-tencentos kubelet[2957693]: W0725 16:39:40.980267 2957693 http2_server.go:568] [transport] transport: http2Server.HandleStreams failed to read frame: read unix /var/lib/kubelet/pod-resources/4246784729->@: read: connection reset by peer
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: panic: assignment to entry in nil map
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: goroutine 409 [running]:
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert(...)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: vendor/k8s.io/apimachinery/pkg/util/sets/string.go:51
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate.fun
c1(0xc001e8a540?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:720 +0x2d2
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate(0xc
0004520e0, {0xc002e00d50, 0x24}, {0xc004610db8, 0x7}, {0xc004610f10, 0xe}, 0x8, 0x200?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:784 +0x101b
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).allocateContainerReso
urces(0xc0004520e0, 0xc000bff9e0?, 0xc002e00d50?, 0x24?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:924 +0x347
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).Allocate(0xc0004520e0
, 0xc004194400, 0xc003902420)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/devicemanager/manager.go:400 +0x1f0
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).allocateAlignedResources(
0x4607040?, 0xc003902580?, 0x50?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope.go:145 +0x79
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*scope).admitPolicyNone(0x7f4693e
a23c8?, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope.go:133 +0x22c
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*containerScope).Admit(0xc000235e
a0, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/scope_container.go:49 +0x90
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet/cm/topologymanager.(*manager).Admit(0xc000793e70, 0xc
00099bee0)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/cm/topologymanager/topology_manager.go:203 +0xaa
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).canAdmitPod(0xc000bd1800, {0xc002c7d0e0, 0
xe, 0x13}, 0xc004194400)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:1995 +0x143
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).HandlePodAdditions(0xc000bd1800, {0xc0018c
4788?, 0x1, 0x1})
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2300 +0x29d
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoopIteration(0xc000bd1800, 0xc0002b61
20, {0x4dc8168, 0xc000bd1800}, 0xc001eea000, 0xc001eea060, 0xc0011d65a0)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2114 +0xb9b
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).syncLoop(0xc000bd1800, 0xc000056960?, {0x4
dc8168, 0xc000bd1800})
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:2057 +0x2f7
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: k8s.io/kubernetes/pkg/kubelet.(*Kubelet).Run(0xc000bd1800, 0x0?)
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: pkg/kubelet/kubelet.go:1461 +0x6d7
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: created by k8s.io/kubernetes/cmd/kubelet/app.startKubelet
Jul 24 14:41:09 VM-253-55-tencentos kubelet[2944746]: cmd/kubelet/app/server.go:1188 +0xaa
```

### What did you expect to happen?

Don't panic.

### How can we reproduce it (as minimally and precisely as possible)?

Delete the last pod that requires GPU on the node and create two or more pods that require GPU at the same time.

### Kubernetes version

<details>

```console
$ kubelet --version
Kubernetes v1.24.4
```

</details>

### Cloud provider

<details>
external
</details>

### OS version

<details>

```console
NAME="TencentOS Server"
VERSION="2.4"
ID="tencentos"
ID_LIKE="rhel fedora centos tlinux"
VERSION_ID="2.4"
PRETTY_NAME="TencentOS Server 2.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tencentos:tencentos:2"
HOME_URL="https://cloud.tencent.com/product/ts"
```
</details>

### Install tools

NOOP

### Container runtime (CRI) and version (if applicable)

<details>
Containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

NOOP

**Comment by gjkim42** [comment]
Is this reproduced in the master branch?

**Comment by payall4u** [comment]
It is possible from the code. I will try to reproduce it later.

**Comment by gjkim42** [comment]
/cc @klueska @ffromani 

Could you take a look? The issue scenario looks real to me.

**Comment by ffromani** [comment]
hi, this looks legit, but OTOH a key assumption in the resource management allocation is that all the pods are admitted serially (e.g. NOT concurrently) one after the another. In other words, a key assumption is we never try allocating resources while another allocation is ongoing, e.g. not completed.
So is not obvious to me which flows are conflicting.

**Comment by ffromani** [comment]
/triage accepted
/priority important-soon

I think the issue described here is real but I'm not sure how often it appears. Panics are always bad, but how often do we know  this is happening? Let's start with `important-soon` as priority

**Comment by payall4u** [comment]
> hi, this looks legit, but OTOH a key assumption in the resource management allocation is that all the pods are admitted serially (e.g. NOT concurrently) one after the another. In other words, a key assumption is we never try allocating resources while another allocation is ongoing, e.g. not completed. So is not obvious to me which flows are conflicting.
> 
> [EDIT] could still be `UpdateAllocatedDevices` if there is a client accessing the podresources API: https://github.com/kubernetes/kubernetes/blob/v1.28.0-beta.0/pkg/kubelet/apis/podresources/server_v1.go#L58

Sure. Kubelet will allocate resources to pods when admitting. Admit is sequential. As long as it is not re allocate, the problem will not occur.

**Comment by payall4u** [comment]
I deployed the dcgm exporter and it does call the interface of podresources.

**Comment by fanzhangio** [comment]
This is a genuine and reproducible issue.
We have observed the kubelet crashing due to such a panic when inserting a device into a map (`allocatedDevices`):
```
Sep 06 17:15:16 Node-2 kubelet[1346544]: I0906 17:15:16.770316 1346544 scope.go:110] "RemoveContainer" containerID="7785bfb25d434c94d6421ee368e2fa0c1a86a2da5c848ee4b098a3d80bbf1433"
Sep 06 17:15:18 Node-2 kubelet[1346544]: I0906 17:15:18.322030 1346544 endpoint.go:112] "State pushed for device plugin" resourceName="<NVIDIA GPU Resource Type A>" resourceCapacity=4
Sep 06 17:15:18 Node-2 kubelet[1346544]: I0906 17:15:18.322123 1346544 endpoint.go:112] "State pushed for device plugin" resourceName="<NVIDIA GPU Resource Type B>" resourceCapacity=4
Sep 06 17:15:18 Node-2 kubelet[1346544]: I0906 17:15:18.322185 1346544 endpoint.go:112] "State pushed for device plugin" resourceName="<NVIDIA GPU Resource Type C>" resourceCapacity=1
Sep 06 17:15:18 Node-2 kubelet[1346544]: panic: assignment to entry in nil map
Sep 06 17:15:18 Node-2 kubelet[1346544]: goroutine 268 [running]:
Sep 06 17:15:18 Node-2 kubelet[1346544]: k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets.String.Insert(0x3f0f180, {0xc000bf6f28, 0x1, 0x1a})
Sep 06 17:15:18 Node-2 kubelet[1346544]:         /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/sets/string.go:51 +0x67
Sep 06 17:15:18 Node-2 kubelet[1346544]: k8s.io/kubernetes/pkg/kubelet/cm/devicemanager.(*ManagerImpl).devicesToAllocate.func1(0xc00134a720)
```
In our observation, right after delting the pod, the podresources API was called. This removed the state of `allocatedDevices` for the GPU resource. This happened when the `UpdateAllocatedDevices` was called as soon as the mutex got unlocked in the `callGetPreferredAllocationIfAvailable`.
Moreover, such a race seems being triggered when Device Plugin periodically calls podresources API.

**Comment by ffromani** [comment]
> In our observation, right after deleting the pod, the podresources API was called. This removed the state of `allocatedDevices` for the GPU resource. This happened when the `UpdateAllocatedDevices` was called as soon as the mutex got unlocked in the `callGetPreferredAllocationIfAvailable`. Moreover, such a race seems being triggered when Device Plugin periodically calls podresources API.

Matches other findings. The podresources endpoint intentionally triggers `UpdateAllocatedDevices` to report the current up to date allocation; otherwise the device manager would clean up lazily the allocation state when a new admission is attempted.
We will work on a fix.

**Comment by sidewinder12s** [comment]
Just to add we've also seen this a few times on 1.23 and 1.24 clusters in EKS with the nvidia-device-plugin + DCGM-Exporter

**Comment by payall4u** [comment]
This looks like a real problem. I added unit tests to verify that the PR works.

**Comment by SergeyKanzhelev** [comment]
not taking for 1.29, but may consider for a cherry-pick later. Depending on the fix complexity

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

because low capacity
