### ISSUE TITLE
Terraform Plugins stored in Persistent Volume are loaded into pod memory during execution

### ISSUE THREAD

**Issue by haricharan03** [kubernetes/kubernetes#119580]
### What happened?
Tested this issue on Google Kubernetes Engine and minikube setup.
In **Google Kubernetes Engine(GKE)**

1. Executing terraform init, terraform plan, terraform apply, terraform destroy commands in kubernetes pod. 
2. Cache directory is created in Persistent Volume for storing the terraform plugins.
3. Plugins/Binaries downloaded during terraform execution are stored in Persistent Volume but they are getting loaded into pod memory(occupying RAM).
4. Even after terraform execution is completed plugins are not getting cleared from pod memory.(The occupied memory is not getting cleared)
5. We are using PV especially to store terraform plugins instead of downloading them into pod but even then they are getting  copied into pod memory while terraform execution.

Example : While provisioning the AWS terraform template, we are caching the plugins using "TF_PLUGIN_CACHE_DIR", the plugin with size of 400MB is getting downloaded in the specified cache directory(Cache directory path is inside the pod but it is mounted to an external storage using persistent volume(PV)) when terraform init is performed.In this case it is not occupying any pod memory as we have mounted the plugin-cache directory path to an external storage.But when we perform terraform plan, terraform apply, terraform destroy those plugins from the cache directory are getting loaded into the pod-memory results in the occupying of additional 400MB space.

6. The occupied memory is getting cleared only after removing the plugins from the plugin-cache directory.
Note: We are using external storage (Persistent Volume) to store the plugin-cache, they are not getting stored inside the pod.

**In Minikube setup**

1. Executing terraform init, terraform plan, terraform apply, terraform destroy commands in kubernetes pod. And cache directory is created in Persistent Volume for storing the terraform plugins.
2. Plugins/Binaries downloaded during terraform execution are stored in Persistent Volume which is mounted to path in kubernetes pod but while executing of terraform commands ,plugins are also loaded into pod memory.
3. Even after execution is completed the loaded plugins are not getting cleared from the pod memory.(The occupied memory is not getting cleared)
4. But once we delete the pod and run terraform commands now terraform plugins are not getting loaded into memory.Plugins are directly used from cache.

**Important**: When terraform plugins are added during pod runtime, they are getting loaded into pod memory. But once pod is deleted and plugin is available in cache directory before pod start, now if we execute terraform commands plugins are not getting loaded into memory.This is happening in minikube setup, but in GKE cluster in both the scenarios (during runtime and after pod start) plugins are loaded into pod memory.

Minikube Kubernetes Version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:38:05Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}

![image](https://github.com/kubernetes/kubernetes/assets/30903879/590fcd6c-31be-41ea-911a-4ccd20f81faa)

### What did you expect to happen?

1. We are running the terraform commands inside a Kubernetes pod with Linux environment.
2. Plugins/Binaries downloaded during terraform execution are stored in Persistent Volume
3. When terraform init, terraform plan, terraform apply are executed inside a Kubernetes pod, plugins should be stored and used from Persistent Volume but should not be loaded into pod memory.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up a Kubernetes cluster containing a pod with linux_amd64 and GO installed inside it.
2. Create a plugin cache dir (TF_PLUGIN_CACHE_DIR) inside a pod for storing the plugins.
3. Create a Persistence Volume with an external storage and mount it to plugin cache dir inside the pod.
8. Perform terraform init, terraform plan, terraform apply, terraform destroy to any terraform template (AWS for example)
9. Check the pod memory spike. Also even after execution got completed pod memory occupied is not getting cleared.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.5-gke.1200", GitCommit:"4eb57372b0f0ac0023caca078161b75185febeef", GitTreeState:"clean", BuildDate:"2023-06-01T19:55:11Z", GoVersion:"go1.19.9 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>

</details>
Google Cloud (Cluster created in Google Kubernetes Engine)

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>
1. Install Terraform with version 1.0.9
2. Create Persistent Volume and attach to the pod
3. Add TF_PLUGIN_CACHE_DIR (for storing terraform plugins) as environment variable in deployment file and point it to Persistent Volume Path. 
Here is the example how environment variable is defined
env:
    - name: TF_PLUGIN_CACHE_DIR
       value: /pv

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by mmiranda96** [comment]
Can this be reproduced without Terraform? If not, it seems that this might be an issue directly with Terraform.

/triage needs-information

**Comment by xing-yang** [comment]
It does not look like this is a storage issue.

/remove-sig storage
