### ISSUE TITLE
[Arm][NodeConformance][LinuxOnly] Container PID namespace sharing containers in pods using isolated PID namespaces should all receive PID 1

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119584]
### Failure cluster [ca29f4c94657ec191829](https://go.k8s.io/triage#ca29f4c94657ec191829)
After https://github.com/kubernetes/kubernetes/issues/119455 is fixed, there are still several failing cases. This one is one of them.

##### Error text:
```
[FAILED] Timed out after 300.000s.
expected pod to be running and ready, got instead:
    <*v1.Pod | 0x4000f56900>: 
        metadata:
          creationTimestamp: "2023-07-16T20:00:08Z"
          managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:spec:
                f:containers:
                  k:{"name":"test-container-1"}:
                    .: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                  k:{"name":"test-container-2"}:
                    .: {}
                    f:args: {}
                    f:command: {}
                    f:image: {}
                    f:imagePullPolicy: {}
                    f:name: {}
                    f:resources: {}
                    f:terminationMessagePath: {}
                    f:terminationMessagePolicy: {}
                f:dnsPolicy: {}
                f:enableServiceLinks: {}
                f:nodeName: {}
                f:restartPolicy: {}
                f:schedulerName: {}
                f:securityContext: {}
                f:terminationGracePeriodSeconds: {}
            manager: e2e_node.test
            operation: Update
            time: "2023-07-16T20:00:08Z"
          - apiVersion: v1
            fieldsType: 
```
#### Recent failures:
[2023/7/26 05:09:09 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1683947081120616448)
[2023/7/26 04:29:00 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1683936996067643392)
[2023/7/25 23:53:18 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1683867591648481280)
[2023/7/25 23:53:17 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1683867573147406336)
[2023/7/25 20:28:30 ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks/1683816082214752256)

/kind failing-test
/sig node

/cc @chendave @ruquanzhao @dims

**Comment by tzneal** [comment]
Super weird, still looking but `/bin/top` appears to be segfaulting.

```
Jul 27 02:18:38 ip-172-31-62-17.us-west-2.compute.internal systemd-coredump[147579]: Process 147565 (top) of user 0 dumped core.

                                                                                     Module /bin/top from rpm procps-ng-3.3.17-1.amzn2023.0.2.aarch64
                                                                                     Stack trace of thread 1:
                                                                                     #0  0x000000000040030c n/a (/bin/top + 0x30c)
                                                                                     #1  0x00000000004bda20 n/a (/bin/top + 0xbda20)
                                                                                     #2  0x00000000004b903c n/a (/bin/top + 0xb903c)
                                                                                     #3  0x0000000000400798 n/a (/bin/top + 0x798)
                                                                                     ELF object binary architecture: AARCH64
```

**Comment by tzneal** [comment]
Switching from `busybox:1.29-4` to `busybox:1.36` eliminated the segfault and the test passes.  The `top` binary from the 1.29-4 container works fine on this system outside of the pod, and works fine using a container manually started with `ctr run --cni --tty --rm registry.k8s.io/e2e-test-images/busybox:1.29-4 mybusybox`.

**Comment by dims** [comment]
HUH!!! wow.
