### ISSUE TITLE
The Google search results on kubernetes.io are all returned with the site title "Kubernetes by Google"

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#11953]
Each page that we host on Kubernetes.io should include the 'title' tags and contain individual page titles, otherwise by default the site title (Kubernetes by Google) is shown as the title of each page that is returned in the "search results".
![image](https://cloud.githubusercontent.com/assets/11762685/8943994/c91d016a-3532-11e5-8ab0-71eecba796a4.png)

Google CSE will slowly regenerate titles as more searches occur (details here: https://support.google.com/webmasters/answer/35624?hl=en), so eventually, titles in search results will change/be optimized, but we can avoid the delay and immediately improve results by including the "title: xyz" front matter.

To avoid all/most of the search results from showing the site title, we must automate and include the following into the front matter. We currently add the ```layout: docwithnav``` frontmatter and need to add to that the ```title: xyx``` line:

for example:
```
---
layout: docwithnav
title: Specific Page Title Systematically Inserted Here
---
```

As part of the markdown file (*.md) processing before copying files from master into gh-pages, can an additional processing step be created and added so that the ```title: xyx``` line is added to the front matter, where "xyz" is the first "h1" tag (or #, *, or any other top level markdown header tag) in the markdown file?

Example:

```
---
layout: docwithnav
title: What is Kubernetes?
---
<!-- BEGIN MUNGE: UNVERSIONED_WARNING -->


<!-- END MUNGE: UNVERSIONED_WARNING -->

# What is Kubernetes? 

Kubernetes is an open-source platform for automating deployment, scaling, and operations of application containers across clusters of hosts. 
.......
```

**Comment by RichieEscarez** [comment]
@krousey

**Comment by thockin** [comment]
@krousey: Do you have time to take this one?

**Comment by krousey** [comment]
@thockin I should be able to do this today.

**Comment by krousey** [comment]
I just spot checked a search. It seems the titles are fixed now.
