### ISSUE TITLE
Pod volume configuration miss match between config map and secrets

### ISSUE THREAD

**Issue by sjanorkar** [kubernetes/kubernetes#119581]
### What happened?

Configuration of specifying the `ConfigMap` and `Secret` as a volume for `Pod` are not consistent with each other.
In K8S Pod key to specify a `ConfigMap` in volumes is `name`, but key to specify a `Secret`  name is `secretName`. 

As all the other configuration to set a volume as ConfigMap and Secret are same, the key name should be same as well to avoid confusion. 

### What did you expect to happen?

While setting the `Secret` as volume in `Pod`, change the key of Secret to `name` from `secretName`

AS IS:
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: secret-vol
spec:
  volumes:
    - name: secret-vol 
      secret:
         secretName: test-secret
  containers:
  - image: nginx
    name: nginx
```

TO BE:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: secret-vol
spec:
  volumes:
    - name: secret-vol 
      secret:
         name: test-secret
  containers:
  - image: nginx
    name: nginx
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod with `Secret` as volume.

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: secret-vol
spec:
  volumes:
    - name: secret-vol
      secret:
         secretName: test-secret
  containers:
  - image: nginx
    name: nginx
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:41:42Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.10", GitCommit:"e770bdbb87cccdc2daa790ecd69f40cf4df3cc9d", GitTreeState:"clean", BuildDate:"2023-05-17T14:06:35Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NA
$ uname -a
NA

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
NA
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dipankardas011** [comment]
@sjanorkar the pod manifest in Issue desc is incorrect
please correct it the `volumes` is a array type

**Comment by dipankardas011** [comment]
yes when providing secret type why to give it secretName? instead we can use name like we use configMap

but I personally feel its not a kind/bug

**Comment by dipankardas011** [comment]
may be for that you may have to raise KEP

**Comment by sjanorkar** [comment]
@dipankardas011 Thanks for the comments. I have already corrected the pod specs.

**Comment by dipankardas011** [comment]
> @dipankardas011 Thanks for the comments. I have already corrected the pod specs.

nice

**Comment by jiahuif** [comment]
/assign @liggitt 
For any suggestions. Thank you.
/triage accepted

**Comment by liggitt** [comment]
> In K8S Pod key to specify a `ConfigMap` in volumes is `name`, but key to specify a `Secret` name is `secretName`.

the inconsistency is unfortunate, but as this is a stable API, renaming the field would not be backwards compatible

/remove-kind bug
/close

**Comment by sjanorkar** [comment]
> @liggitt: Closing this issue.
> 
> In response to [this](https://github.com/kubernetes/kubernetes/issues/119581#issuecomment-1664370106):
> 
> > > In K8S Pod key to specify a `ConfigMap` in volumes is `name`, but key to specify a `Secret` name is `secretName`.
> > 
> > 
> > the inconsistency is unfortunate, but as this is a stable API, renaming the field would not be backwards compatible
> > /remove-kind bug
> > /close
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

Why not deprecate the old `secretName` field and introduce new `name` field? 
This way user can use either `secretName` or `name` field. I think this would solve backward compatibility issue.

Everyone here acknowledge here that it's bad user experience.

**Comment by liggitt** [comment]
Putting the same data in two fields leads to compatibility problems as well. 

Existing readers require the data to be in the old field. When writing to the new field, the old field couldn't be left blank or those clients would break, so writers would either have to set both fields, or the data would have to be automatically copied to the old field, populating two fields for readers.

Automatic copying leads to problems when both fields are specified but with different values. An old api client intending to update this field (by reading/modifying/writing) would not be aware of the new field, so would send updates with mismatched values in the old and new fields. The server would have to honor the older field's value for compatibility.

This means that clients aware of the new field would have to write both the old and new field to be sure that the value was honored. This would be even more confusing and less user friendly than the existing inconsistency.

I agree the inconsistency is not ideal, but it is not worth the complexity of adding a second field to correct, especially since that leads to even more confusing behavior. 

/close
