### ISSUE TITLE
E2E framework imports 200+ Kubernetes E2E Specs

### ISSUE THREAD

**Issue by csuzhangxc** [kubernetes/kubernetes#119504]
### What happened?

```go
package main

import (
	"os"
	"testing"

	"github.com/onsi/ginkgo"
	_ "k8s.io/kubernetes/test/e2e/framework/statefulset"
       // any of the bellow lines will cause the same problem
	// _ "k8s.io/kubernetes/test/e2e/framework/manifest"
	// _ "k8s.io/kubernetes/test/e2e/common"
)

func TestMain(m *testing.M) {
	os.Exit(m.Run())
}

func TestE2E(t *testing.T) {
	var r []ginkgo.Reporter
	ginkgo.RunSpecsWithDefaultAndCustomReporters(t, "Kubernetes e2e suite", r)
}
```

run the above code will run 200+ Kubernetes ginkgo Specs

```
...
------------------------------
[sig-node] Downward API 
  should provide container's limits.cpu/memory and requests.cpu/memory as env vars [NodeConformance] [Conformance]
  /home/ubuntu/go/pkg/mod/k8s.io/kubernetes@v1.24.0/test/e2e/framework/framework.go:652
•
------------------------------
[sig-node] Downward API 
  should provide default limits.cpu/memory from node allocatable [NodeConformance] [Conformance]
  /home/ubuntu/go/pkg/mod/k8s.io/kubernetes@v1.24.0/test/e2e/framework/framework.go:652
•
------------------------------
[sig-node] Downward API 
  should provide pod UID as env vars [NodeConformance] [Conformance]
  /home/ubuntu/go/pkg/mod/k8s.io/kubernetes@v1.24.0/test/e2e/framework/framework.go:652
•
Ran 233 of 233 Specs in *** seconds
```

This may be caused by https://github.com/kubernetes/kubernetes/commit/b03e27af1bd16838c0707fb62911a5d8f72a1635#diff-17b42fedf4ec6da56312a671925ebb19db3879bf70d001ccf24be6019e60822aR31

### What did you expect to happen?

no Kubernetes E2E Specs imported and only run my own Specs.

### How can we reproduce it (as minimally and precisely as possible)?

see above code

### Kubernetes version

<details>
v1.24.0+
```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by csuzhangxc** [comment]
ref #108581

**Comment by gjkim42** [comment]
> ```go
> 	_ "k8s.io/kubernetes/test/e2e/framework/statefulset"
> ```

https://github.com/kubernetes/kubernetes#to-start-using-k8s

> To use Kubernetes code as a library in other applications, see the [list of published components](https://git.k8s.io/kubernetes/staging/README.md).
> Use of the `k8s.io/kubernetes` module or `k8s.io/kubernetes/...` packages as libraries is not supported.

Importing `k8s.io/kubernetes/test` as a library is not supported by Kubernetes.

**Comment by aojea** [comment]
> Importing `k8s.io/kubernetes/test` as a library is not supported by Kubernetes.

this is right, this is not supported on purpose 

/close
