### ISSUE TITLE
Kubernetes PostStartHook doesn't show events since 1.25

### ISSUE THREAD

**Issue by JJotah** [kubernetes/kubernetes#119541]
### What happened?

We upgrade from 1.25 to 1.26 and after that every lifecycle hook doesn't show the error on 
```bash 
kubectl describe pod PODNAME 
```
on Older versions like 1.23 and 1.25 I can see the error 

```bash
Warning  FailedPostStartHook  1s    kubelet            Exec lifecycle hook ([/bin/sh -c badcommand > /usr/share/message]) for Container "lifecycle-demo-container" in Pod "lifecycle-demo_default(2ec31ecb-bf4f-4e1c-bf5d-e25f7e49dd4b)" failed - error: command '/bin/sh -c badcommand > /usr/share/message' exited with 127: /bin/sh: 1: badcommand: not found
```

But on new kubernetes versions the same pod shows as 

```bash
Warning  FailedPostStartHook  2s (x2 over 4s)  kubelet            PostStartHook failed
```

### What did you expect to happen?

Same as older versions

### How can we reproduce it (as minimally and precisely as possible)?

Deploy this definition on new versions

```bash
apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
      preStop:
        exec:
          command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
```

### Kubernetes version

<details>

```console
1.27.3
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xgp01** [comment]
https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/kubelet/kuberuntime/kuberuntime_container.go#L289

I think you r looking for this. @JJotah

**Comment by JJotah** [comment]
> https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/kubelet/kuberuntime/kuberuntime_container.go#L289-L290
> 
> I think you r looking for this. @JJotah

Yeah but is not working correctly the same pod in other versions are showing up the events

```golang
v1.EventTypeWarning, events.FailedPostStartHook
```

**Comment by pacoxu** [comment]
This change is in https://github.com/kubernetes/kubernetes/pull/86139/files#diff-d86ffc24d8e4c9deafd3e39e8f4ee3546ee46a31dcea8ea6526443b3f4bffa28L284.

I remember the failure message can be found on the kubelet log.

**Comment by ndixita** [comment]
This is expected as we do not want to expose any sensitive information that may be part of the error message.

**Comment by dtantsur** [comment]
Hi folks! Does it mean that PostStartHooks are impossible to debug without root access to control plane? Could you please update https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#debugging-hook-handlers then? (And, honestly, think if this feature is even useful in this form.)
