### ISSUE TITLE
[ARM] when querying /stats/summary should report resource usage through the stats api 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119585]
### Which jobs are failing?

ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks

https://storage.googleapis.com/k8s-triage/index.html?test=stats%2Fsummary

### Which tests are failing?

E2eNode Suite: [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api 

{ 
failed [FAILED] 
Timed out after 180.001s. 
Expected     <string>: 
Summary to match fields: 
{ .Node.SystemContainers: 	missing expected element runtime } 
In [It] 
at: test/e2e_node/summary_test.go:336 @ 07/26/23 05:48:05.248 
}

### Since when has it been failing?

arm test since begining

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-cgroupv1-containerd-node-arm64-al2023-e2e-ec2-eks

### Reason for failure (if possible)

cadvisor on arm?

### Anything else we need to know?

```
2649 flags.go:64] FLAG: --container-hints="/etc/cadvisor/container_hints.json"
--log-cadvisor-usage="false"
--storage-driver-db="cadvisor"
manager_no_libpfm.go:29] cAdvisor is build without cgo and/or libpfm support. Perf event counters are not available.
```

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
/assign @upodroid @tzneal 

it may be ec2 related, not arm related. We need to fix arm tests on gce to validate (failing currently).

**Comment by tzneal** [comment]
Should be fixed, but I'm watching https://testgrid.k8s.io/sig-node-ec2#ci-cgroupv2-containerd-node-al2023-e2e-ec2-eks&width=90 and will re-open if not.

**Comment by tzneal** [comment]
Test is passing now, good to leave closed.
