### ISSUE TITLE
[FR]: implement fsUser option for securityContext

### ISSUE THREAD

**Issue by xhejtman** [kubernetes/kubernetes#119507]
Hello,

currently, it seems not to be possible to project secrets or configmaps to files with strict permissions to containers.

Some applications such as `sshd` require strict permissions on some files like `~/.ssh/authorized_keys`, mainly, it requires that this file is owned by the user. For the `sshd` there is an option to bypass this restriction `StrictModes`. However, there are different like `psql` that is able to use `~/.pgpass` only with the correct permissions. Operators like cloudnative-pg create a secret that could be projected to `~/.pgpass`, but owner cannot be set thus `psql` refuses to use it.

I think it would be great, if `fsUser` option could be implemented or some other option that could be used to specify the owner of projected secrets/configmaps.

**Comment by colearendt** [comment]
Totally agree. This is super important in order to handle such permission-sensitive services. Especially in a "minimum access" context where the container is not running as root or (worse?) the filesystem is read only. That is where this issue shows up the most.

**Comment by stlaz** [comment]
/close
in favour of https://github.com/kubernetes/kubernetes/issues/81089
