### ISSUE TITLE
1.28 Release Notes: "Known Issues"

### ISSUE THREAD

**Issue by sanchita-07** [kubernetes/kubernetes#119523]
This issue is a bucket placeholder for collaborating on the "Known Issues" additions for the 1.28 Release Notes. If you know of issues or API changes that are going out in 1.28, please comment here so that we can coordinate incorporating information about these changes in the Release Notes.

/assign @kubernetes/release-team-release-notes 

/sig release
/milestone v1.28

**Comment by furkatgofurov7** [comment]
@sanchita-07 hey, Bug Triage for v1.28 here.

This is milestoned with 1.28, is there an ongoing effort to close out this issue?

**Comment by sanchita-07** [comment]
We shall close this issue when the v1.28 is released.
ref :  [v1.24 Release Notes : "Known Issues"](https://github.com/kubernetes/kubernetes/issues/109027)

**Comment by dims** [comment]
one known issue if we don't get a fix in time ... https://github.com/kubernetes/kubernetes/issues/119864

**Comment by furkatgofurov7** [comment]
@sanchita-07 I believe this can be closed now as 1.28 is already out?

**Comment by furkatgofurov7** [comment]
Please re-open if this is still needed

/close
