### ISSUE TITLE
After upgrading to version v1.27.3 `Adding GroupVersion` is repeated in the api-server log

### ISSUE THREAD

**Issue by hickersonj** [kubernetes/kubernetes#119546]
### What happened?

I upgraded k3s from `v1.26.2+k3s1` to `v1.27.3+k3s1` and noticed a log message `Adding GroupVersion` is repeated in the k3s.log. I also see this message when deploying a container that uses apiserver aggregation, such as `kubevirt` in other distros such as `minikube` in the api-server log.

### What did you expect to happen?

The message should not repeated in the logs.  This causes a nuisance and the logs eventually are rotated.

### How can we reproduce it (as minimally and precisely as possible)?

Upgrade kubernetes to `v1.27.3` and install a container that uses uses apiserver aggregation such as `calico` or `kubevirt`.  

### Anything else we need to know?

For reference the original issue was reported here:
https://github.com/k3s-io/k3s/issues/8038

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:47:40Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
$ uname -a
Linux build 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Jefftree** [comment]
Thanks for raising this, opened https://github.com/kubernetes/kubernetes/pull/119825 as a potential fix.
