### ISSUE TITLE
Namespace stuck in Terminating when deleted if ApiService doesn't implement Aggregated Discovery

### ISSUE THREAD

**Issue by markmandel** [kubernetes/kubernetes#119662]
### What happened?

We implement a manual `APIService` API Extension in [Agones](https://github.com/googleforgames/agones).

Definition:
https://github.com/googleforgames/agones/blob/main/install/helm/agones/templates/service/allocation.yaml

Code for handling web requests:
https://github.com/googleforgames/agones/blob/main/pkg/util/apiserver/apiserver.go

The code is extremely lightweight as we only have no need for storage, and only accept CREATE requests at this time.

This issue was first reported by one of our users in May, but we only were able to reproduce it ourselves once we were on 1.27.x: https://github.com/googleforgames/agones/issues/3172

Testing on Kubernetes 1.27.x we noticed that when attempting to delete Namespaces, they would get stuck in termination with the following description:

```
❯ kubectl describe ns 1690585578
Name:         1690585578
Labels:       kubernetes.io/metadata.name=1690585578
              owner=e2e-test
Annotations:  <none>
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Fri, 28 Jul 2023 16:07:44 -0700  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: allocation.agones.dev/v1: stale GroupVersion discovery: allocation.agones.dev/v1
  NamespaceDeletionGroupVersionParsingFailure  False   Fri, 28 Jul 2023 16:07:46 -0700  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Fri, 28 Jul 2023 16:08:56 -0700  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    False   Fri, 28 Jul 2023 16:08:56 -0700  ContentRemoved          All content successfully removed
  NamespaceFinalizersRemaining                 False   Fri, 28 Jul 2023 16:08:56 -0700  ContentHasNoFinalizers  All content-preserving finalizers finished
```

So far, I've not found a way to delete the Namespace.

Looking through the log for the webserver, i can see requests for `/apis` and the new Aggregated Discovery feature (`Accept:  "application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList"`), but we return a 404 to that response, since it's not implemented.

Looking through the code I can find (https://github.com/kubernetes/kubernetes/blob/v1.27.3/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go) it seems that any response other than `http.StatusOK` would result in this issue -- which is breaking backward compatibility within `APIService` to assume that this API surface is implemented in some way.

### What did you expect to happen?

Namespaces would terminate as per normal.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Agones on a cluster (https://agones.dev/site/docs/installation/install-agones/)
2. `kubectl create ns foo`
3. `kubectl delete ns foo`
4. Watch as the ns gets stuck in Terminating.

### Anything else we need to know?

If I had a magic wand, I'd love a reference of all the API's that get called against an APIService and what their expected results should be.

So far it's a combo of using `kubectl proxy` and looking at the k8s API responses, crawling through code, and reading apiserver logs to try and reverse engineer this work.

### Kubernetes version

<details>

```console
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2-gke.1200", GitCommit:"5319597f0ffe6e93e83a51e280d81fb2028bf4a0", GitTreeState:"clean", BuildDate:"2023-06-01T19:54:16Z", GoVersion:"go1.20.4 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Google Kubernetes Engine
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux trixie/sid"
NAME="Debian GNU/Linux"
VERSION_CODENAME=trixie
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux markmandel 6.3.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by markmandel** [comment]
Something else I also just noticed -- there are no errors or events that pertain to this issue attached to the `APIService` either, which would be useful for debugging if it were.

```
❯ kubectl describe apiservices.apiregistration.k8s.io v1.allocation.agones.dev
Name:         v1.allocation.agones.dev
Namespace:
Labels:       app=agones
              app.kubernetes.io/managed-by=Helm
              chart=agones-1.34.0-dev
              component=controller
              heritage=Helm
              release=agones
Annotations:  meta.helm.sh/release-name: agones
              meta.helm.sh/release-namespace: agones-system
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2023-07-28T19:38:30Z
  Resource Version:    155113
  UID:                 03ae8a3a-0100-498e-8429-b09d326f912f
Spec:
  Ca Bundle:               LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNRENDQWhpZ0F3SUJBZ0lSQUk5cFB2R3B4QTA5OFUrbm9VeklxWTh3RFFZSktvWklodmNOQVFFTEJRQXcKSWpFZ01CNEdBMVVFQXhNWFlXUnRhWE56YVc5dUxXTnZiblJ5YjJ4c1pYSXRZMkV3SGhjTk1qTXdOekk0TWpNeApNRFF4V2hjTk16TXdOekkxTWpNeE1EUXhXakFpTVNBd0hnWURWUVFERXhkaFpHMXBjM05wYjI0dFkyOXVkSEp2CmJHeGxjaTFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk83Y3RpREdvN0EKblYzNkdPblkxNW9heTZxNW85QzRxdW9NMVNjeHV3RjNJNFZBTDE2eXJlaFR6UTd0UHdrUUtRSHE4dHRUQXduQgp2NW9Gd25sZmk0UkZkQ3AxcGpMTkRtL3RtaG5IY05yT0czQTQxTUgxaFNralJ1eVJhR2NjbzZVdG9WbUg2d3hpClk3SG50SDRmSEdoVHUrWllFN3YyaU1vTnpkSkpjVy94aGtLUlNaaVk5SGV6TmJUUzNRNS9SQ0I5cEkzMXphYkIKZHkrTjNQMWl3aHc0MHg2MDRsWURIbzRUeTJ5SktkWjhvVjljZ3lPYUgyVDRBKzlZWUkyNFhEZktmcHd0cDU1VApTWlRFVXV1dGN4aVpGQXhwNmZudWo0QytRUC9LdTVNSS9lYnY4bm9iKzUyeGJVdkpyZUNQcHk3Ky9xZkVTbloyCnhEbFd4YWtvVFVjQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0cKQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlFSeTYzbgpxOXU4WlpzU09BelIwTDhySXd6L1BEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUMlRPNnNreDFyUHVMQWJtClBiaENaYnVYd3g0dVZpK3VkSW53Sm51a0lRSXRlU0twZVl1bHJlVHpOQ0dvWTBkS1NGNjg2OFl0VmpxMElIaXcKenVVV1BDMUMwcFJndXBaclRJMlc1TnF0U3FOdkV4ZWwzQzNWT2hhd2M0S2IrWUtQZ0ZiQjhZTkNJR0xyTVU5bQpjWFJOMTRDMlltd3RWV3loQnQ2eW1WWTlUdW1JZUR4UXZwMkx5UmE0MkJQbCtQQitYMDFpZHVaQUpmMThQdjhYCjgrdnNnR1BXd3kxR2cvbkNUTkR5VlRiVGRhMThIUExNNnlNRUs1RGtvdTVJSllHLzVZQjFFdG9jc1FjUXFLYXIKSWtPTVVRd1YvZ093bEgrRWhPQUxaZjI3dUpQTkNWbDVYQlRMcXJPMmR2cmEzQktNalErZE1HdEpkdHU2b0huNAp3TDI5b1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  Group:                   allocation.agones.dev
  Group Priority Minimum:  1000
  Service:
    Name:            agones-controller-service
    Namespace:       agones-system
    Port:            443
  Version:           v1
  Version Priority:  15
Status:
  Conditions:
    Last Transition Time:  2023-07-28T23:10:57Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
```

**Comment by Jefftree** [comment]
Will edit this comment as we go, but just writing down some useful notes:

- agones should support the `/apis` endpoint: https://github.com/googleforgames/agones/blob/main/pkg/util/apiserver/apiserver.go#L130 so it's weird that a 404 is required
- Aggregated Discovery is fully backwards compatible with previous versions. A fallback https://github.com/kubernetes/kubernetes/blob/v1.27.3/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go#L231-L233 is implemented so not supporting aggregated discovery on an APIService will fall back to the old behavior (without the `Accept:  "application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList"` accept header)
- The issue brought up https://github.com/googleforgames/agones/issues/3172 is on v1.26.5 in which aggregated discovery is disabled (only enabled for 1.27+)

**Comment by liggitt** [comment]
> * Aggregated Discovery is fully backwards compatible with previous versions. A fallback https://github.com/kubernetes/kubernetes/blob/v1.27.3/staging/src/k8s.io/kube-aggregator/pkg/apiserver/handler_discovery.go#L231-L233 is implemented so not supporting aggregated discovery on an APIService will fall back to the old behavior (without the `Accept:  "application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList"` accept header)

That assumes the aggregated server will respond with a NotAcceptable status code... ways we could make that stronger / more compatible:
1. double check the response content-type
2. send a single request to `/apis` that indicates it accepts BOTH `application/json` and `application/json;g=apidiscovery.k8s.io;v=v2beta1;as=APIGroupDiscoveryList`, and use the content-type in the returned data to decide whether to go down the aggregated or normal discovery path


 ideally, it would make a single request that indicated it accepted

**Comment by markmandel** [comment]
Thanks to an offline chat with @Jefftree - can confirm that returning `HTTP: 406` from `/apis` resolved the issue!

Long term we'll look at implementing Aggregate Discovery, but this at least gets us past the initial hurdle. Thanks for the support!

**Comment by liggitt** [comment]
> Thanks to an offline chat with @Jefftree - can confirm that returning `HTTP: 406` from `/apis` resolved the issue!

to be clear, this is returning a 406 to requests that don't accept `application/json`, right?

**Comment by markmandel** [comment]
Honestly, I just did this:

```
	// We don't currently support a root /apis, but since Aggregate Discovery expects
	// a 406, let's give it what it wants, otherwise namespaces don't successfully terminate.
	mux.HandleFunc("/apis", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotAcceptable)
		w.Header().Set(ContentTypeHeader, k8sruntime.ContentTypeJSON)
	})
```

On Agones while we return results on `/apis/{groupversion}` and below, we've never actually implemented a response to root level `/apis` ever, and up until this point haven't had a need to.

**Comment by liggitt** [comment]
ah, right... the non-aggregated discovery calls directly to `/apis/$group/$version`

@Jefftree to be actually compatible, I think the "success case" for aggregated discovery should check that the status code is `200` and the returned content-type is aggregated discovery json, and if either of those are false, it should fall back to non-aggregated discovery.

**Comment by Jefftree** [comment]
> ah, right... the non-aggregated discovery calls directly to `/apis/$group/$version`
> 
> @Jefftree to be actually compatible, I think the "success case" for aggregated discovery should check that the status code is `200` and the returned content-type is aggregated discovery json, and if either of those are false, it should fall back to non-aggregated discovery.

Yeah I agree, we made a couple assumptions based on the sample apiserver that could be improved for stronger compatibility guarantees. Will look into sending a PR for this once code freeze is over.

/triage accepted
/assign

**Comment by markmandel** [comment]
Thanks for the quick response - sounds like a reasonable fix to me (for what that's worth 😃).

I'm definitely here for odd K8s bug reports 😁

**Comment by liggitt** [comment]
@Jefftree do you have an ETA for a fix implementing https://github.com/kubernetes/kubernetes/issues/119662#issuecomment-1659257581 ?

**Comment by derekxia1988** [comment]
I am using kubernetes 1.28.2, and as PR #120359 says, this bug is fixed on version 1.28.2, but I still have exactly the same namespace termination issue.

**Comment by liggitt** [comment]
@derekxia1988, this issue tracks issues with deleting namespaces when an aggregated server does not implement aggregated discovery but it otherwise healthy. Even with this issue fixed, an aggregated server that is unhealthy will still block deletion, because *no* discovery requests succeed. The symptoms would be very similar.

What API group/version is namespace deletion reporting having a problem with in your cluster? If you request it directly with `kubectl get --raw /apis/$group/$version`, do you get a healthy or unhealthy response?

**Comment by derekxia1988** [comment]
> @derekxia1988, this issue tracks a problem with deleting namespaces when an aggregated server does not implement aggregated discovery but is otherwise healthy. Even with this issue fixed, an aggregated server that is unhealthy will still block deletion, because _no_ discovery requests succeed. The symptoms would be very similar.
> 
> What API group/version is namespace deletion reporting having a problem with in your cluster? If you request it directly with `kubectl get --raw /apis/$group/$version`, do you get a healthy or unhealthy response?

I am just using Agnoes, and exactly the same appearance as above, install Agones in cluster, create namespace, delete namespace, and the deletion get stuck, and when use `kubectl describe ns foo` I got the same logs as above. 

BUT, today I can delete namespace successfully, the only difference is some settings was changed in values.yaml of Agones.
I add this in values.yaml:
    crds:
      install: true
      cleanupOnDelete: true
