### ISSUE TITLE
[kubelet-image-gc] minimum-image-ttl-duration not work,when kubelet restart.

### ISSUE THREAD

**Issue by lixd** [kubernetes/kubernetes#119642]
### What happened?

when kubelet restart,all images which notused cleaned.
but there is a flag in kubelet,`minimum-image-ttl-duration`,explain：Minimum age for an unused image before it is garbage collected.  Examples: '300ms', '10s' or '2h45m'.
i set `minimum-image-ttl-duration` to `20m0s`,it's means if a image not used,it will live 20m and then clean by kubelet（if has disk pressure）.if kubelet not restart, it work,but if restart ther is a bug, `minimum-image-ttl-duration` not work,image will be clean，even if it's no enough  time.

### What did you expect to happen?

`minimum-image-ttl-duration` work, image even if not used,it will live 20m and then clean by kubelet.

### How can we reproduce it (as minimally and precisely as possible)?

1）make node trigger disk pressure.
2）pull some image which not used by pod
3）restart kubelet
4）image cleaned by kubelet after around 10s

### Anything else we need to know?

i see the source code, and maybe there is a bug.

in [detectImages](https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/kubelet/images/image_gc_manager.go#L261-L262) func,well detect image and update firstdetect time for every image.
```go
	// New image, set it as detected now.
		if _, ok := im.imageRecords[image.ID]; !ok {
			klog.V(5).InfoS("Image ID is new", "imageID", image.ID)
			im.imageRecords[image.ID] = &imageRecord{
				firstDetected: detectTime,
			}
		}
```
and in  [freeSpace](https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/kubelet/images/image_gc_manager.go#L394C1-L397) func,well check images livetime by firstDetected.
```go
		if freeTime.Sub(image.firstDetected) < im.policy.MinAge {
			klog.V(5).InfoS("Image ID's age is less than the policy's minAge, not eligible for garbage collection", "imageID", image.id, "age", freeTime.Sub(image.firstDetected), "minAge", im.policy.MinAge)
			continue
		}
```
if kubelet running normal,it work,because there is a [Start](https://github.com/kubernetes/kubernetes/blob/97c7dbcd227ec253bb277a91575706fe30f519dc/pkg/kubelet/images/image_gc_manager.go#L190-L204) func.
```go
func (im *realImageGCManager) Start() {
	ctx := context.Background()
	go wait.Until(func() {
		// Initial detection make detected time "unknown" in the past.
		var ts time.Time
		if im.initialized {
			ts = time.Now()
		}
                // in first time,ts is zero. 
               // in first time,ts is zero.
		_, err := im.detectImages(ctx, ts)
		if err != nil {
			klog.InfoS("Failed to monitor images", "err", err)
		} else {
			im.initialized = true
		}
	}, 5*time.Minute, wait.NeverStop)
//...

```
in this line,`_, err := im.detectImages(ctx, ts)`,in first time,ts is zero. so image's firstDetected time is zero,and in freeSpace
`reeTime.Sub(image.firstDetected) < im.policy.MinAge` this check is always false,so image will be cleaned.

maybe we can change to `im.detectImages(time.now())`,can fix this bug.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux kc-worker2 5.4.156-1.el7.elrepo.x86_64 #1 SMP Tue Oct 26 11:19:09 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ffromani** [comment]
/triage accepted
/priority backlog

initial assessment of priority, subject to change
