### ISSUE TITLE
Typos in checks.go,width.go,types_swagger_doc_generated.go,swagger.json

### ISSUE THREAD

**Issue by deveshgoyal1000** [kubernetes/kubernetes#119667]
### What happened?

Typos in checks.go,width.go,types_swagger_doc_generated.go,swagger.json

**Comment by pacoxu** [comment]
/remove-kind bug
/kind cleanup
This is not typically a bug and may not need to open an issue to track IMO.

**Comment by kumarankit999** [comment]
Is anyone working on this, otherwise I can work on this issue because @deveshgoyal1000 has raised a PR for this!!!

**Comment by nilekhc** [comment]
[Trivial](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#trivial-edits) changes like this should be avoided as we have very limited resources to handle reviews and approvals.  Focus efforts on fixes that have meaningful impact on end users (bugs, docs, etc).

/close
