### ISSUE TITLE
reflector relist when api server upgrade

### ISSUE THREAD

**Issue by AuroraTwinkle** [kubernetes/kubernetes#119646]
### What happened?

My project use istio as a registry, when k8s api server upgrade or restart, the client-go reflector will do relist and watch, and 
this can result in a large number of duplicate update events(10w+ events) and pilot handl lager duplicate update events(workloadentry), eventually, the update of Routing table is delayed more then some minutes.

### What did you expect to happen?

My expectation is that during api server upgrades or when there are occasional timeout disconnects, the client-go reflector should not perform a relist operation, but instead continue to retry the watch to avoid handling a large number of duplicate update events and cause routing table delayed.

**And one of my doubts is why the watch operation is only retried when the connention refused,  why not when the connection is closed or connection reset by peer or request timeout?** I think it is safe to retry with last resourceVersion when connection close or timeout, but I'm not sure what details I haven't considered. Refer to this  [code](https://github.com/kubernetes/kubernetes/blob/v0.20.1/pkg/client/cache/reflector.go#L171)
<img width="819" alt="image" src="https://github.com/kubernetes/kubernetes/assets/25919180/35060b21-9898-460a-85fc-bf94c61f2222">

### How can we reproduce it (as minimally and precisely as possible)?

just restart api server, then you can trigger relist operation

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.4-tke.11", GitCommit:"2093e9ec8db4fd321acac1e8b78ba28792ff6395", GitTreeState:"clean", BuildDate:"2021-06-04T14:12:37Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.18) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
the code you are linking is very old and your server version indicats 1.18, that is EOL

Check the most recent code to see if that was already feature, there is also a new feature that may help you to improve your situation https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list#design-details

**Comment by AuroraTwinkle** [comment]
> the code you are linking is very old and your server version indicats 1.18, that is EOL
> 
> Check the most recent code to see if that was already feature, there is also a new feature that may help you to improve your situation https://github.com/kubernetes/enhancements/tree/master/keps/sig-api-machinery/3157-watch-list#design-details

@aojea Thank you for your reply! I have checked the latest master code, there also just retry when connection refused or TooManyRequests. 
https://github.com/kubernetes/kubernetes/blob/e68629e7b37acb1264f8518192b2d25b723d3be1/staging/src/k8s.io/client-go/tools/cache/reflector.go#L420
https://github.com/kubernetes/kubernetes/blob/e68629e7b37acb1264f8518192b2d25b723d3be1/staging/src/k8s.io/client-go/tools/cache/reflector.go#L892-L902
And the new feature that you refer to me may help, I will study it carefully. Thanks again!

**Comment by jiahuif** [comment]
/assign @aojea 
Thank you.
/triage accepted

**Comment by aojea** [comment]
> And the new feature that you refer to me may help, I will study it carefully. Thanks again!

/close

please feel free to reopen or open a new issue with more details if that information does not solve the problem
