### ISSUE TITLE
Estimate Kubernetes pods resource specification in an automated way

### ISSUE THREAD

**Issue by vivuu1989** [kubernetes/kubernetes#119676]
### What would you like to be added?

Our Developers are developing springboot java application and which are deploying to AKS cluster. We have Helm and Azure pipelines to deploy these apps to the AKS cluster dynamically and the values for the Pod resource speicification are defined in Variablegroups of the ADO pipelines and.

 But we are facing some difficlties to estimate the required resource specification for their each apps,because each apps has different JVM settings and startup behaviour. Since we dont have a proper mechanisam inplace to define the Resource Request and Limit (Cpu and Mem respectively), our clutsers are over committed by the mis usage of these values in ADO pipelines.

So we are trying to introduce some automated mechanism, where a developer can estimate their required memory& cpu request and limit values by passing their JVM arguments or some specific things to be considered for springboot application, then these estimated values can be used in the corresponding Variables groups. below are the some components which are used in jvmSetings. 

So is this possible to achieve in an automated way ? 

Below are the some of the jvmSettings parameters used by the developers

```
-Xmx650m 
-XX:MaxGCPauseMillis=100
-XX:MetaspaceSize=150m
-XX:MaxMetaspaceSize=150m 
-XX:MaxMetaspaceFreeRatio=100
-XX:CompressedClassSpaceSize=25m
-XX:InitialCodeCacheSize=100m
-XX:ReservedCodeCacheSize=100m
-XX:MaxDirectMemorySize=100m
-XX:+DisableExplicitGC
```

### Why is this needed?

This is needed to define the actual resource specifications than over committing any unused resource

**Comment by kannon92** [comment]
Have you looked into https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler?

**Comment by vivuu1989** [comment]
So. Can we use VPA along with hpa?. Because if we get more loads to the pods, there will be a limit the vla can autoscale and that may cause the application unhealthy state. So I guess we need both hoa and vpa in these scenarios. Or vpa is recommended to use only for finding the recommendation of the resource and not for dynamic update?

**Comment by vivuu1989** [comment]
So. Can we use VPA along with hpa?. Because if we get more loads to the pods, there will be a limit the vla can autoscale and that may cause the application unhealthy state. So I guess we need both hoa and vpa in these scenarios. Or vpa is recommended to use only for finding the recommendation of the resource and not for dynamic update?

**Comment by vivuu1989** [comment]
> Have you looked into https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler?

So. Can we use VPA along with hpa?. Because if we get more loads to the pods, there will be a limit the vla can autoscale and that may cause the application unhealthy state. So I guess we need both hoa and vpa in these scenarios. Or vpa is recommended to use only for finding the recommendation of the resource and not for dynamic update?

**Comment by kannon92** [comment]
> So. Can we use VPA along with hpa?. Because if we get more loads to the pods, there will be a limit the vla can autoscale and that may cause the application unhealthy state. So I guess we need both hoa and vpa in these scenarios. Or vpa is recommended to use only for finding the recommendation of the resource and not for dynamic update?

/sig autoscaling

To be honest you may know more about this than I do.  Maybe you can ask this question on sig-autoscaling in slack?

**Comment by aryan2701** [comment]
I will be going to try this approach for the automated estimation:

1. Extract relevant information from JVM settings:
From the given JVM settings, you can extract the parameters related to memory usage, such as -Xmx (maximum heap size) and -XX:MetaspaceSize, and CPU usage, such as GC-related parameters like -XX:MaxGCPauseMillis.
Analyze the values of these parameters to get an idea of the memory and CPU requirements for the application.
Map JVM settings to Kubernetes resource requests and limits:

2. Based on the extracted values, you can define rules or mappings that convert the JVM settings into appropriate Kubernetes resource requests and limits.
For example, you can set the memory request to the value of -Xmx and the memory limit to the sum of -Xmx and -XX:MetaspaceSize. Similarly, you can set the CPU request based on the -XX:MaxGCPauseMillis value.
Implement the automated mechanism:

3. Develop a tool or script that takes the JVM settings as input and calculates the corresponding Kubernetes resource requests and limits based on the defined rules.
Integrate this tool into the Azure DevOps (ADO) pipeline to automatically update the Variablegroups with the estimated resource values for each application.
Testing and refinement:

4. Test the automated mechanism with different Spring Boot applications, including those with varying JVM settings, to ensure accurate estimations.
Continuously refine the estimation rules based on feedback and real-world usage patterns.

**Comment by vivuu1989** [comment]
> I will be going to try this approach for the automated estimation:
> 
> 1. Extract relevant information from JVM settings:
> From the given JVM settings, you can extract the parameters related to memory usage, such as -Xmx (maximum heap size) and -XX:MetaspaceSize, and CPU usage, such as GC-related parameters like -XX:MaxGCPauseMillis.
> Analyze the values of these parameters to get an idea of the memory and CPU requirements for the application.
> Map JVM settings to Kubernetes resource requests and limits:
> 
> 2. Based on the extracted values, you can define rules or mappings that convert the JVM settings into appropriate Kubernetes resource requests and limits.
> For example, you can set the memory request to the value of -Xmx and the memory limit to the sum of -Xmx and -XX:MetaspaceSize. Similarly, you can set the CPU request based on the -XX:MaxGCPauseMillis value.
> Implement the automated mechanism:
> 
> 3. Develop a tool or script that takes the JVM settings as input and calculates the corresponding Kubernetes resource requests and limits based on the defined rules.
> Integrate this tool into the Azure DevOps (ADO) pipeline to automatically update the Variablegroups with the estimated resource values for each application.
> Testing and refinement:
> 
> 4. Test the automated mechanism with different Spring Boot applications, including those with varying JVM settings, to ensure accurate estimations.
> Continuously refine the estimation rules based on feedback and real-world usage patterns.
> 

Is this possible to achieve using vertical pod autoscaler recommender? Can hoa and vpa work together to ensure both the ways scaling happening for cou and memory usage
