### ISSUE TITLE
Trace exemplars for kube-apiserver metrics

### ISSUE THREAD

**Issue by dashpole** [kubernetes/kubernetes#119697]
### What would you like to be added?

Add exemplars to APIServer metrics.  To accomplish this, we need to add FooWithExemplar functions, like histograms ObserveWithExemplar to component-base/metrics: 
https://github.com/prometheus/client_golang/blob/7f2db5f1ed43d8a4312bfd85280a17dfef13358b/prometheus/histogram.go#L722 At minimum, we should allow exemplars on counters and histograms.

Then, we need to change Observe() calls to ObserveWithExemplar calls, similar to https://github.com/prometheus/client_golang/blob/main/examples/exemplars/main.go.

We should use the `trace_id` key for the trace ID, and the `span_id` key for the span ID.

cc @Richabanker @kubernetes/sig-instrumentation-leads 

### Why is this needed?

With https://github.com/kubernetes/enhancements/issues/647, we can now collect traces for requests to the kubernetes api.  We have a number of metrics, such as `apiserver_request_duration_seconds`, which would benefit from having exemplars attached.

**Comment by rexagod** [comment]
[/assign](https://github.com/kubernetes/kubernetes/compare/master...rexagod:kubernetes:support-exemplars-for-counters?expand=1)

**Comment by dashpole** [comment]
Chatted with @logicalhan offline.  We should not add ObserveWithExemplar, and similar functions to the metrics stability framework.  Our functions accept context, which means we can (and should) inspect the context for a SpanContext, and use ObserveWithExemplar if we have trace and span ids available.

**Comment by rexagod** [comment]
Sure thing, @dashpole. I had a chat with him along the same lines, I'll adjust the current implementation to accommodate checking for [TraceIDs](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.10.0#SpanContext.TraceID) and [SpanIDs](https://pkg.go.dev/go.opentelemetry.io/otel/trace@v1.10.0#SpanContext.SpanID).

**Comment by jiahuif** [comment]
Thank you @rexagod 
/triage accepted

**Comment by dgrisonnet** [comment]
From a discussion with the Prometheus team on slack, it seems that we will need to support OpenMetrics if we want to have exemplars. 

I looked a bit into the client as I was also concerned about the `_total` suffix requirement but it seems that the client is permissive: https://github.com/prometheus/common/blob/main/expfmt/openmetrics_create.go#L133-L138. The counters that don't have a correct prefix, will just be treated as `Unknown` metric in Prometheus. Looking into the openmetrics parser on the server side, it doesn't seem to impact the parsing of exemplar, so it shouldn't pose any problem at first besides not having the normal counter guarantees from Prometheus.

**Comment by dgrisonnet** [comment]
I drafted https://github.com/kubernetes/kubernetes/pull/120027 to check the impact of enabling OpenMetrics on all our components
