### ISSUE TITLE
Destination Port Unreachable is displayed when a k8s host ping the svc address

### ISSUE THREAD

**Issue by jiamengguo** [kubernetes/kubernetes#119613]
### What would you like to be added?

I newly installed k8s 27.3 version, but I found that my cluster host can not ping the svc address, but can ping the pod address, and I created svc access is no problem, please tell me what is the reason. 
![svc地址不通](https://github.com/kubernetes/kubernetes/assets/130622684/bb11e3e8-588e-462c-961d-910a492912ee)
![pod](https://github.com/kubernetes/kubernetes/assets/130622684/5cf4f663-574c-466a-b2e7-9def18102dac)

### Why is this needed?

I newly installed k8s 27.3 version, but I found that my cluster host can not ping the svc address, but can ping the pod address, and I created svc access is no problem, please tell me what is the reason. ****

**Comment by aojea** [comment]
Service is an abstraction, is a frontend that uses Pods as backends for the configured ClusterIP:Port:Protocol, it is not real IP so it does not have to respond to ping (there are some Services implementations that respond to ICMP on the ClusterIP, but that is an implementation detail of that specific implementation)

/close
