### ISSUE TITLE
Kubernetes endpoint should not use link-local address of interface

### ISSUE THREAD

**Issue by bprashanth** [kubernetes/kubernetes#11961]
On certain cloud providers like digital ocean the public interface has multiple addresses, one of which is a link-local address that points to a metadata server. The node is supposed to come up and contact the metadata server to bootstrap the public interface with a real address. At this point, the interface has 2 addresses, eg (from irc debugging): https://dpaste.de/T8s0/raw. 

Looks like we create the kubernets endpoint using the first, link-local address and it always gets rejected. The kubernetes master service creation can keep failing (and re-checking for a valid public ip) when this happens because it knows link-local is not allowed: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/master/controller.go#L97

**Comment by thockin** [comment]
Is this just a case of ChooseHostInterface() not filtering link-local?

This seems like a pretty easy change, good starter change for someone who wants to get involved.

**Comment by paralin** [comment]
Is there a fix for this?

**Comment by thockin** [comment]
Not yet - it seems like a 30 minute sort of fix.  Got 30 minutes?

**Comment by paralin** [comment]
Sure. Is there something in the output of /proc/net/route that could be used to identify the wrong IP to use? 

In the meantime is there some way to force kube-apiserver to a specific IP?

**Comment by thockin** [comment]
You may be able to set `--advertise-address` on the apiserver, but that's sort of clumsy.  I think the best fix will be to fix ChooseHostInterface() to exclude IPs which are `ip.IsLinkLocalMulticast()` or `ip.IsLinkLocalUnicast()`.  The code is easy (I think) and then a test should be straight-forward.

**Comment by paralin** [comment]
Okay, you're right, it took me 30 seconds. I'll write up a test too and pr>

**Comment by paralin** [comment]
Okay @thockin, how's this?

**Comment by paralin** [comment]
This issue might be more complex... I filtered out the link-local addresses in finalIP util function, and while all the unit tests pass, the e2e fails. Really weird.

**Comment by paralin** [comment]
After the recent updates I've rebased and the tests work.
