### ISSUE TITLE
`imagePullSecrets` (in Service Account) not used for public images (still using DockerHub)

### ISSUE THREAD

**Issue by TBG-FR** [kubernetes/kubernetes#119650]
### What happened?

When following the guide *Add ImagePullSecrets to a service account* from the documentation ([here](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account)), after creating a new secret and configuring the service account with it, public images (ex `nginx`) are still pulled from the DockerHub, without using the custom registry (confirmed by K8S logs and also registry logs)

```console
[tbg@host:~] kubectl describe pod nginx | grep Image
    Image:          nginx
    Image ID:       docker.io/library/nginx@sha256:e67bce60872000987d2a86ea0c4338b7e941accfd2ffd1d62ceaf9a100396c97
```

### What did you expect to happen?

I would expect ALL images (unless a registry is specified) to be pulled from the mirror/cache registry, without having to explicitly specify that registry in the `image: ` field...

Here's the result if I start a pod with `--image=registry.fqdn.com/library/nginx` instead of `--image=nginx`, **as stated in the docs**

```console
[tbg@Debian:~] kubectl describe pod nginx | grep Image
    Image:          registry.fqdn.com/library/nginx
    Image ID:       registry.fqdn.com/library/nginx@sha256:e67bce60872000987d2a86ea0c4338b7e941accfd2ffd1d62ceaf9a100396c97
```

### How can we reproduce it (as minimally and precisely as possible)?

```bash
REG_SECRET_KEY=your-key

kubectl create secret docker-registry ${REG_SECRET_KEY} --docker-server='registry.fqdn.com' --docker-username='USERNAME' --docker-password='PASSWORD' --docker-email='k8s@registry.fqdn.com' --namespace='default'

# Check that secret is created => OK ✅
kubectl get secrets ${REG_SECRET_KEY}

kubectl patch serviceaccount default -p "{\"imagePullSecrets\": [{\"name\": \"${REG_SECRET_KEY}\"}]}"

# Check that imagePullSecret is configured => OK ✅
kubectl edit serviceaccount/default

# Explicit registry url before image name => OK ✅
kubectl run nginx --image=registry.fqdn.com/library/nginx --restart=Never
kubectl get pod nginx -o=jsonpath='{.spec.imagePullSecrets[0].name}{"\n"}'
kubectl describe pod nginx | grep Image
kubectl delete pod nginx

# No registry url before image name => KO 🛑 (image comes from docker.io)
kubectl run nginx --image=nginx --restart=Never
kubectl get pod nginx -o=jsonpath='{.spec.imagePullSecrets[0].name}{"\n"}'
kubectl describe pod nginx | grep Image
kubectl delete pod nginx
``` 

### Anything else we need to know?

That doesn't look like a configuration issue, because K8S is able to correctly authenticate to my registry mirror when needed

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.26.4
```

```console
$ kubectl version --output=yaml
clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-04-12T12:05:35Z"
  compiler: gc
  gitCommit: f89670c3aa4059d6999cb42e23ccb4f0b9a03979
  gitTreeState: clean
  gitVersion: v1.26.4
  goVersion: go1.19.8
  major: "1"
  minor: "26"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
OVH Managed Cloud
</details>

### OS version

<details>

<br/>

**Client OS**
```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/
$ uname -a
Linux NUM00427 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
Sorry, I may misunderstand the problem.

There is no global registry prefix configuration for K8S. So everything works as expected in your descriptions.
- `nginx` without any prefix equals to `docker.io/library/nginx`.

**Comment by pacoxu** [comment]
If the document shows an example like 
```
kubectl run nginx --image=DUMMY_SERVER/nginx --restart=Never
```
then there may be nothing vague.

**Comment by TBG-FR** [comment]
I was led to believe I could force K8S to pull every image through my registry mirror simply by adding an `imagePullSecrets` to the `serviceaccount`, looks like I'm wrong.

I wanted to avoid the need to edit every image tag to explicitly target the registry instead of docker.io, but I ended up doing it, no choice 🤷‍♂️ For those interested, you could use something more specific like a MutatingAdmissionWebhook or a kind of proxy.

You're right, that's better with that doc example modification, it may prevent people from thinking like me 😬

**Comment by TBG-FR** [comment]
> As I know this can be done with a webhook like kyverno.
> 
> https://kyverno.io/docs/installation/customization/#configmap-keys has defaultRegistry.
> 
> > defaultRegistry: sets the default image registry to use if one is not specified. Defaults to docker.io.

Good to know, thanks !
