### ISSUE TITLE
Need assistance with implementing KEDA autoscaling

### ISSUE THREAD

**Issue by gourik22** [kubernetes/kubernetes#119683]
I am trying to implement Keda scaling in listener containers. Noticed that container is accepting new requests at termination period. Is there any way to close the RabbitMQ connection in termination period without breaking the current process?

**Comment by sftim** [comment]
GitHub is the wrong place to ask for assistance around using Kubernetes and related projects.

https://github.com/kubernetes/kubernetes/issues/119683#issuecomment-1657270143

/close not-planned
