### ISSUE TITLE
`initialDelaySeconds` logic changed on documentation but not in code or in changelog

### ISSUE THREAD

**Issue by pablo-suazo** [kubernetes/kubernetes#119617]
### What happened?

I have noticed in the official documentation that the logic of the initialDelaySeconds field defined in the probes has changed.

In the 1.26 documentation: https://v1-26.docs.kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes is described this way

![image](https://github.com/kubernetes/kubernetes/assets/102029997/5770d9c9-460e-4e4f-8b43-dc505c365818)

But in the latest documentation: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes , the description has changed
![image](https://github.com/kubernetes/kubernetes/assets/102029997/6a385275-75d8-42cf-ba71-461d6ed3ff9c)

As you can see, the logic has changed, but I cannot find any mention on the v1.27 or v1.28 changelogs. Even in the code related to the probes, I cannot find any changes from previous versions.

https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/kubelet/prober/worker.go
https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/kubelet/prober/prober.go
https://github.com/kubernetes/kubernetes/blob/release-1.27/pkg/kubelet/prober/prober_manager.go

The improved functionality of the initialDelaySeconds for the liveness and readiness probes when a startup is defined is very interesting and we are looking forward to implement it in our workloads, but we have to make sure in which version this functionality is deployed.

Thank you in advance

### What did you expect to happen?

The changelog and the code reflect the funcionality changes refered in the documentation

### How can we reproduce it (as minimally and precisely as possible)?

The liveness and readiness probes initialDelaySeconds counter should not start until the startup probe has succeded instead of start when the pod has started

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Maybe the documentation is wrong? Normally, we try to document how Kubernetes actually behaves.

/retitle `initialDelaySeconds` logic changed on documentation but not in code or in changelog

**Comment by pablo-suazo** [comment]
There are more changes in the documentation for the 1.29 release but I cannnot see anything in the chagelog nor in the code

![image](https://github.com/kubernetes/kubernetes/assets/102029997/2140a4af-928a-4d52-8bec-7e0acb4d520f)

**Comment by sftim** [comment]
> As you can see, the logic has changed, but I cannot find any mention on the v1.27 or v1.28 changelogs. 

It's possible that the logic has not changed and the documentation was clarified. That's what I assume has happpened.
