### ISSUE TITLE
Api server does not start

### ISSUE THREAD

**Issue by quetdn** [kubernetes/kubernetes#119633]
### What happened?

After a blackout, when I restarted the cluster (2 Controllers + 3 Workers), none of the Control-Plane nodes started the api-server, neither kube-controller-manager, kube-scheduler and etcd pods. The port 6443 is not opened. 
No changes were made in the previous week. 

### What did you expect to happen?

The cluster starts fine, as usual.

### How can we reproduce it (as minimally and precisely as possible)?

Testing with the same versions of software.

### Anything else we need to know?

Kubelet files config:
[kubelet.service.txt](https://github.com/kubernetes/kubernetes/files/12188742/kubelet.service.txt)
[config.yaml.txt](https://github.com/kubernetes/kubernetes/files/12188730/config.yaml.txt)
[kubeadm-flags.env.txt](https://github.com/kubernetes/kubernetes/files/12188734/kubeadm-flags.env.txt)

kubelet yaml pods:
[etcd.yaml.txt](https://github.com/kubernetes/kubernetes/files/12188753/etcd.yaml.txt)
[kube-apiserver.yaml.txt](https://github.com/kubernetes/kubernetes/files/12188754/kube-apiserver.yaml.txt)
[kube-controller-manager.yaml.txt](https://github.com/kubernetes/kubernetes/files/12188755/kube-controller-manager.yaml.txt)
[kube-scheduler.yaml.txt](https://github.com/kubernetes/kubernetes/files/12188756/kube-scheduler.yaml.txt)

journalctl:
[journalctl.txt](https://github.com/kubernetes/kubernetes/files/12188806/journalctl.txt)

crictl - Pods and Containers:
[pods.txt](https://github.com/kubernetes/kubernetes/files/12188825/pods.txt)
[containers.txt](https://github.com/kubernetes/kubernetes/files/12188826/containers.txt)

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1

"Kubelet version" kubeletVersion="v1.27.1"

kubeadm version: &version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:20:04Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>
Baremetal
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
# Linux k8s2700 5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd containerd.io 1.6.21 3dce8eb055cbb6872793272b4f20ed16117344f8
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: Calico v3.25.1
CSI: rook-ceph v1.11 - ceph- v17.2.6
</details>

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

/close
