### ISSUE TITLE
Apiserver can not initialize watchcache when resources size too large.

### ISSUE THREAD

**Issue by Sakuralbj** [kubernetes/kubernetes#119615]
### What happened?

As default [storageWatchListPageSize](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L60) was set to 10000, when  each resource size is large，the initial list of watchcache will exceed the maxSendBytes (2GB）and return the error
```
Cacher (configmaps): unexpected ListAndWatch error: failed to list *core.ConfigMap: rpc error: code = ResourceExhausted desc = grpc: message too large (5895956722 bytes); reinitializing...
```

### What did you expect to happen?

Apiserver watchcache can initialize normally. （If storageWatchListPageSize can be flexibly configured ）

### How can we reproduce it (as minimally and precisely as possible)?

Create many large configmaps (size * num > 2GB，size<1MB，num<10000)，and restart kube-apiserver

### Anything else we need to know?

https://github.com/etcd-io/etcd/pull/8437/files

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

**Comment by wackxu** [comment]
I think the default storageWatchListPageSize should be user configurable for kube-apiserver

**Comment by Sakuralbj** [comment]
> I think the default storageWatchListPageSize should be user configurable for kube-apiserver

Yes, If we can configure it with adding a new command line argument or using environment variable cc @marseel
