### ISSUE TITLE
OOMKiller tests are flaking - sometimes condition returned as Failed instead of OOMKilled

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#119600]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.7

### Which tests are failing?

- E2eNode Suite.[It] [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api
- E2eNode Suite.[It] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] single process container The containers terminated by OOM killer should have the reason set to OOMKilled

### Since when has it been failing?

7/22

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.7

### Relevant SIG(s)

/sig node

**Comment by lengrongfu** [comment]
The problem with OOM kill looks the same as this pr https://github.com/kubernetes/kubernetes/pull/116082

**Comment by pacoxu** [comment]
#119670 will fix this and is already approved(wait for 1.28 release and merge then).
/assign @lengrongfu

**Comment by pohly** [comment]
> #119670 will fix this and is already approved(wait for 1.28 release and merge then).

That PR has been merged, but the problem continues to occur, for example today in https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119728/pull-kubernetes-node-e2e-containerd/1692065178335580160/

**Comment by tzneal** [comment]
Still seeing this occur fairly regularly.  I tested locally just increasing the length of the sleep call, but depending on the node load it still flaked. I'm hopeful but not certain that marking the test as serial in #120059 will eliminate the flake.

**Comment by tzneal** [comment]
I created https://github.com/kubernetes/kubernetes/pull/120077 to revert the change to serial. It doesn't completely resolve the issue, will be digging into this deeper when I get some time.

**Comment by tzneal** [comment]
This looks like a containerd issue and @lengrongfu already created a ticket there. I looked at containerd logs from a good and bad test run. In the good run, we get a `Reason = OOMKilled` in the container stopped event.  In the bad run, we get a `Reason = Error` on the container stopped event.

**Comment by SergeyKanzhelev** [comment]
Linking containerd tickets for completeness:

- https://github.com/containerd/containerd/issues/8180
- https://github.com/containerd/containerd/issues/8893

**Comment by SergeyKanzhelev** [comment]
do you think it is a quick start in our case? Or something else

**Comment by tzneal** [comment]
I don't think so since the sleep didn't appear to help. containerd reads the memory.events file in the cgroup directory to discover OOM kills.  I *think* what's happening is some race where the cgroup directory gets cleaned up before it has a chance to read the memory.events file.  I did some testing and when it fails, containerd tries to read memory.events but it has already been removed.

**Comment by SergeyKanzhelev** [comment]
/retitle OOMKiller tests are flaking - sometimes condition returned as Failed instead of OOMKilled

**Comment by pacoxu** [comment]
https://storage.googleapis.com/k8s-metrics/flakes-latest.json
```
{
  "pr:pull-kubernetes-node-e2e-containerd": {
    "consistency": 0.902,
    "flakes": 55,
    "test_flakes": {
      "Node Tests": 51,
      "E2eNode Suite [It] [sig-node] OOMKiller [LinuxOnly] [NodeConformance] init container The containers terminated by OOM killer should have the reason set to OOMKilled": 24,
   
```
/priority important-soon
I suppose that we should fix it or at least make it less flaking.

**Comment by pacoxu** [comment]
According to https://github.com/kubernetes/kubernetes/pull/120460#issuecomment-1708794146, we may skip it due to https://github.com/opencontainers/runc/pull/3932 and https://github.com/cri-o/cri-o/issues/7035.

**Comment by pacoxu** [comment]
Not flake in recent three weeks. 
/close
