### ISSUE TITLE
Use bandwidth shaping on the master

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/kubernetes#11965]
Limit outbound and inbound bandwidth, using the `tc` tool, see:

https://www.iplocation.net/traffic-control

**Comment by brendandburns** [comment]
fwiw, a magic incantation that works is:

```console
export DOWNLOAD_RATE=1mbit
export UPLOAD_RATE=1mbit
export INTERFACE=eth0

tc qdisc add dev ${INTERFACE} root handle 1: htb default 30
tc class add dev ${INTERFACE} parent 1: classid 1:1 htb rate ${DOWNLOAD_RATE}
tc class add dev ${INTERFACE} parent 1: classid 1:2 htb rate ${UPLOAD_RATE}
tc filter add dev ${INTERFACE} protocol ip parent 1:0 prio 1 u32 match ip dst `hostname -i`/32 flowid 1:1
tc filter add dev ${INTERFACE} protocol ip parent 1:0 prio 1 u32 match ip src `hostname -i`/32 flowid 1:2
```

**Comment by brendandburns** [comment]
ref: https://github.com/GoogleCloudPlatform/kubernetes/pull/11968

**Comment by bgrant0607** [comment]
Earlier request: #2856

You're planning to use this for apiserver?

**Comment by thockin** [comment]
Does this produce a per-flow limit or global?  Global seems like DoS waiting to happen

**Comment by smarterclayton** [comment]
Closing due to age.  We did something here, can be solved other ways, reopen if disagree.
