### ISSUE TITLE
scheduler: register default EventsToRegister in only some extension points

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#119783]
## What

register default EventsToRegister only for PreFilter, Filter, Reserve, and Permit plugins.

Currently, we register default EventsToRegister for all plugins that don't have EnqueueExtension.
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/scheduler/framework/runtime/framework.go#L551-L554

## Why

EventsToRegister affects which events the scheduler watches, and when registered events come, the scheduling queue requeue Pods according to them. The queue checks the event can make Pod schedulable or not via QueueingHint from pInfo.UnschedulablePlugins.
Given this fact, plugins that never be registered in pInfo.UnschedulablePlugins don't need to have EventsToRegister. 
And, currently, only PreFilter, Filter, Reserve, and Permit affect pInfo.UnschedulablePlugins. Meaning all other plugins' EventsToRegister actually don't affect anything, and to register default EventsToRegister to other plugins could result in watching events in vain, which all of PreFilter, Filter, Reserve, and Permit plugins aren't interested in.

/kind feature
/sig scheduling

**Comment by alculquicondor** [comment]
Something is unclear to me.
Does having `defaultEnqueueExtension` for something like `PrioritySort` cause use to store useless events in memory?

**Comment by sanposhiho** [comment]
> Does having defaultEnqueueExtension for something like PrioritySort cause us to store useless events in memory?

If in-flight Pods enhancement is enabled, yes.

**Comment by sanposhiho** [comment]
Also, when it comes to a very very large cluster, a reduction in the number of cluster events that the scheduler handles _might_ be crucial in terms of the throughput the number of cluster events the scheduler handles. (such throughput is something we haven't much cared for now though)
