### ISSUE TITLE
ci-kubernetes-e2e-node-canary keeps failing

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#119757]
### Which jobs are failing?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/1687329849187766272

### Which tests are failing?

Not started correctly

```
Trying to find master named 'bootstrap-e2e-master'
Looking for address 'bootstrap-e2e-master-ip'
ERROR: (gcloud.compute.addresses.describe) Could not fetch resource:
 - The resource 'projects/k8s-jkns-e2e-gce/regions/us-west1/addresses/bootstrap-e2e-master-ip' was not found
Could not detect Kubernetes master node.  Make sure you've launched a cluster with 'kube-up.sh'
Master not detected. Is the cluster up?
Dumping logs from nodes locally to '/logs/artifacts'
Detecting nodes in the cluster
No nodes found!
WARNING: The following filter keys were not present in any resource : name, zone
WARNING: The following filter keys were not present in any resource : name, zone
INSTANCE_GROUPS=
NODE_NAMES=
```

### Since when has it been failing?

https://github.com/kubernetes/test-infra/pull/30265 fixed https://github.com/kubernetes/kubernetes/issues/119681.
- Now the failure is different, so open a new one instead reopening the #119681

/cc @bart0sh @aojea 

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary

### Relevant SIG(s)

/sig node

**Comment by bart0sh** [comment]
/triage accepted
/priority important-soon
/assign
I'm working on it: https://github.com/kubernetes/test-infra/pull/30288

**Comment by bart0sh** [comment]
@pacoxu [the job is running for some time](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-node-canary/1687420950766686208). It will most probably some test cases will fail (at least they did when I run it locally), but that would be totally different story. I'll take care of it.

**Comment by bart0sh** [comment]
ha! It succeeded!

**Comment by pacoxu** [comment]
Good job. Thanks. 👍

**Comment by bart0sh** [comment]
It still requires some work as it's flaky: https://testgrid.k8s.io/sig-testing-canaries#node
I'll take care of it.
