### ISSUE TITLE
Need assistance with diagnosing 'kube-apiserver.service not found' error

### ISSUE THREAD

**Issue by Todoroki02** [kubernetes/kubernetes#119718]
This is an error I am facing with kube-apiserver:
`Failed to start kube-apiserver.service: Unit kube-apiserver.service not found.`
And because of that this is what I am getting:
`sudo kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
The connection to the server 10.2.8.18:6443 was refused - did you specify the right host or port? `
Can anybody help me out here!!

**Comment by AmarNathChary** [comment]
**Verify Kubernetes Installation** and **Check kube-apiserver** Binary. If it seems like the **kube-apiserver** binary is missing or you suspect a corrupted installation, consider reinstalling **Kubernetes components** on your system. Ensure that the **kube-apiserver** service unit file exists in the appropriate directory. if its Linux it might be Located at `/etc/systemd/system/` 
If everything is ok then **Restart kube-apiserver** with following command
`sudo systemctl restart kube-apiserver
`
