### ISSUE TITLE
"kubectl delete rc" not work as expected

### ISSUE THREAD

**Issue by huikang** [kubernetes/kubernetes#11978]
Hi
I would like to disable the replication controller of a pod, while leaving the pod running. So from this link https://cloud.google.com/container-engine/docs/replicationcontrollers/operations#deleting_replication_controllers

I run "$ kubectl delete rc NAME --cascade=false"

To test if the rc is disabled, I tried deleting a container and see if kubernete will create a new one.
I run "docker rm -f" to remove one container in the pod. However, the replication controller will automatically create a new one. Is this contradict to what "kubectl delete rc" does? Thanks.

**Comment by huikang** [comment]
By the way, the recovered container has a difference ID than the removed one. So I guess it is created by replication controller, which I have disabled by kubectl delete.

**Comment by bprashanth** [comment]
you're confusing the responsibilities of the kubelet and the controller. You can delete an rc and it won't create any more pods for you, but for as long as a pod exists (shows up in kubect get pods --all-namespaces), the kubelet (running on the host the pod is assigned to) will make sure the containers in the pod are running. 

You should not kill docker containers directly. If you want to get rid of the container, delete the pod using kubectl.

**Comment by huikang** [comment]
@bprashanth 
Any idea about how to configure the prod file so that prod will not create a new container if I temporarily stop the existing one. Thanks.

**Comment by bgrant0607** [comment]
You need to set restartPolicy to Never if you don't want the container to be restarted. Or just delete the pod after deleting the replication controller.

**Comment by mvle** [comment]
Setting the restartPolicy in the pod configuration to Never doesn't seem to work. Killing the container will still trigger automatic restart of the container. I'm using k8 ver 1.0.1. 

I tried with the following pod configuration (modified from examples/storm/storm-worker-controller.json):

{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "storm-worker",
    "labels": {
      "name": "storm-worker"
    }
  },
  "spec": {
        "containers": [
          {
            "name": "storm-worker",
            "image": "mattf/storm-worker",
            "ports": [
              {
                "hostPort": 6700,
                "containerPort": 6700
              },
              {
                "hostPort": 6701,
                "containerPort": 6701
              },
              {
                "hostPort": 6702,
                "containerPort": 6702
              },
              {
                "hostPort": 6703,
                "containerPort": 6703
              }
            ],
            "resources": {
              "limits": {
                "cpu": "200m"
              }
            },
        "labels": {
          "name": "storm-worker",
          "uses": "nimbus"
        },
        "restartPolicy": "Never"
          }
        ]
      }
}

I ran:  kubectl create -f <above pod file name>

Then docker ps to find the container name:

CONTAINER ID        IMAGE                                  COMMAND             CREATED              STATUS              PORTS                              NAMES
d597fd802772        mattf/storm-worker                     "/start.sh"         About a minute ago   Up About a minute                                      k8s_storm-worker.634eb7c7_storm-worker_default_187877c8-3aeb-11e5-a8e1-068e0dac6c38_4530d19b
f5f455450160        gcr.io/google_containers/pause:0.8.0   "/pause"            About an hour ago    Up About an hour    0.0.0.0:6700-6703->6700-6703/tcp   k8s_POD.d90d5217_storm-worker_default_187877c8-3aeb-11e5-a8e1-068e0dac6c38_789936f5

Then did docker stop d597fd802772

Then docker ps shows:

CONTAINER ID        IMAGE                                  COMMAND             CREATED             STATUS              PORTS                              NAMES
e875c8583bdf        mattf/storm-worker                     "/start.sh"         59 seconds ago      Up 58 seconds                                          k8s_storm-worker.634eb7c7_storm-worker_default_187877c8-3aeb-11e5-a8e1-068e0dac6c38_40007191
f5f455450160        gcr.io/google_containers/pause:0.8.0   "/pause"            About an hour ago   Up About an hour    0.0.0.0:6700-6703->6700-6703/tcp   k8s_POD.d90d5217_storm-worker_default_187877c8-3aeb-11e5-a8e1-068e0dac6c38_789936f5

As you can see a new storm-worker container got spawned.
I don't know what the second container (gcr.io/google_containers/pause:0.8.0) is for or is doing. But stopping either one or both containers still cause autorestart of container despite the Never restartPolicy.

I have no other pods or services running (other than kubernetes).

**Comment by bgrant0607** [comment]
What's the output of `kubectl get pod -o json storm-worker`?

Try `kubetctl create --validate ...`, and see http://kubernetes.io/v1.0/docs/api-reference/definitions.html#_v1_podspec . restartPolicy should be specified outside the container list.

Another problem is that labels don't belong in the spec. The labels field in metadata is the correct one.

**Comment by mvle** [comment]
@bgrant0607 , thanks! placing restartPolicy outside of the container list did the trick.
Appreciate the help!

{
  "kind": "Pod",
  "apiVersion": "v1",
  "metadata": {
    "name": "storm-worker",
    "labels": {
      "name": "storm-worker"
    }
  },
  "spec": {
        "restartPolicy": "Never",
        "containers": [
          {
            "name": "storm-worker",
            "image": "mattf/storm-worker",
            "ports": [
              {
                "hostPort": 6700,
                "containerPort": 6700
              },
              {
                "hostPort": 6701,
                "containerPort": 6701
              },
              {
                "hostPort": 6702,
                "containerPort": 6702
              },
              {
                "hostPort": 6703,
                "containerPort": 6703
              }
            ],
            "resources": {
              "limits": {
                "cpu": "200m"
              }
            }
        }
        ]
      }
}

**Comment by mbforbes** [comment]
@huikang it looks like your question has been answered (and your follow-up one, @mvle) so I'm closing this issue. Please feel free to re-open if I'm mistaken!
