### ISSUE TITLE
empty-dir directories was not cleaned after pod deleted

### ISSUE THREAD

**Issue by borgerli** [kubernetes/kubernetes#119792]
### What happened?

When a pod with empty-dir volumes is deleted just after it was created, it's possible that the init containers still write contents to empty-dirs. And this might cause empty-dirs orphaned and kubelet could no delete it by rmdir. 

<img width="1555" alt="企业微信截图_3ff2fb4f-e1fc-40c5-b46d-57244f4dadd0" src="https://github.com/kubernetes/kubernetes/assets/63291172/eb87ccec-9891-444e-a8eb-1589c693c540">

### What did you expect to happen?

empty-dirs should be deleted forcely.

### How can we reproduce it (as minimally and precisely as possible)?

It's not easy to reproduce this issue. A possible way is that:

1. Create pod with empty-dir volumes and an init container which mounts and writes many contents to this volume
2. Delete the pod after init container just started.

### Kubernetes version

1.20

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by mmiranda96** [comment]
Could you try reproducing in a newer Kubernetes version? Perhaps 1.27. Also, which container runtime and version are you using (containerd/Dockershim/other)?

/triage needs-information

**Comment by aslafy-z** [comment]
/reopen
/remove-lifecycle rotten

Still applies to 1.26.15 on GKE

**Comment by aslafy-z** [comment]
@borgerli can you please /reopen this issue? Thanks

**Comment by haircommander** [comment]
/sig storage

can someone from SIG-storage take a look at this please?

**Comment by AnishShah** [comment]
@borgerli Can you try this on a newer k8s version?
