### ISSUE TITLE
 How can we upgrade k8s from 1.18.8 to 1.23.6 ?

### ISSUE THREAD

**Issue by liuyanzhen34** [kubernetes/kubernetes#119743]
Hello experts and teachers, may I ask a question: Our company has a k8s production environment built through binary mode, version 1.18. Now we need to upgrade the k8s version from the existing 1.18.8 to 1.23.6. Can we smoothly upgrade in place? Is it possible to upgrade one major version of K8S each time, or can it be directly upgraded from 1.18.8 to 1.23.6? What are the risks involved in the upgrade process? Or can we export existing yaml files for various resources, directly eliminate the existing lower version of the k8s cluster, and rebuild a new 1.23.6 cluster, which is safer and more efficient? Looking forward to the patient answers from all the experts and teachers, thank you very much.

**Comment by WVenus** [comment]
Kubernetes versions are expressed as x.y.z, where x is the major version, y is the minor version, and z is the patch version, following Semantic Versioning terminology. For more information, see Kubernetes Release Versioning.
This page explains how to upgrade a Kubernetes cluster created with kubeadm from version 1.26.x to version 1.27.x, and from version 1.27.x to 1.27.y (where y > x). Skipping MINOR versions when upgrading is unsupported. 
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

**Comment by liuyanzhen34** [comment]
@WVenus  Thank you very much for your patient response
