### ISSUE TITLE
☂️ Flaking/Failing tests on EC2 (sig-node related tests)

### ISSUE THREAD

**Issue by tzneal** [kubernetes/kubernetes#119763]
### Which jobs are failing?

- [x] ci-cgroupv2-containerd-node-al2023-e2e-serial-ec2-eks
- [x] ci-cgroupv2-containerd-node-arm64-al2023-e2e-serial-ec2-eks
- [ ] ci-cgroupv1-containerd-node-e2e-serial-ec2-eks
- [ ] ci-cgroupv1-containerd-node-arm64-e2e-serial-ec2-eks

### Which tests are failing?

- MirrorPod when recreating a static pod it should launch successfully even if it temporarily failed termination due to volume failing to unmount (a5884872f034e8ba5fb1)
  - Should be fixed by https://github.com/kubernetes/kubernetes/pull/119765
- when querying /stats/summary should report resource usage through the stats api (c92c54ee6f0bccaa0edd)

- container PID namespace sharing containers in pods using isolated PID namespaces should all receive PID 1
  - Should be fixed by https://github.com/kubernetes/kubernetes/pull/119636
- The containers terminated by OOM killer should have the reason set to OOMKilled (f48daf5412edac432c28)
  - Should be fixed by https://github.com/kubernetes/kubernetes/pull/119670 
-  create a batch of pods latency/resource should be within limit when create 10 pods with 0s interval (fe61709b648f843eb7b0)

### Since when has it been failing?

Since the new jobs were created

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?sig=node&job=ec2

### Relevant SIG(s)

/sig node

**Comment by dims** [comment]
We have a new testgrid dashboard as well: https://testgrid.k8s.io/amazon-ec2-node

**Comment by pacoxu** [comment]
Only `E2eNode Suite [It] [sig-node] POD Resources [Serial] [Feature:PodResources] [NodeFeature:PodResources] without SRIOV devices in the system with CPU manager None policy should return the expected responses [sig-node, Serial, Feature:PodResources, NodeFeature:PodResources]` is flaky in https://storage.googleapis.com/k8s-triage/index.html?job=ec2.

Other two failures are not in high failure rate
- `E2eNode Suite [It] [sig-node] Density [Serial] [Slow] create a sequence of pods latency/resource should be within limit when create 10 pods with 50 background pods [sig-node, Serial, Slow]`
- `E2eNode Suite [It] [sig-node] Summary API [NodeConformance] when querying /stats/summary should report resource usage through the stats api [sig-node]`

**Comment by pacoxu** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/121850 to track the `without SRIOV devices` test flake. And other flake are not with high failing rate. 

/close

Reopen if you think this still needs an umbrella ☂️
