### ISSUE TITLE
[It] [sig-network] "Services should create endpoints for unready pods" should not depend on kube-proxy for validation

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#119773]
### What happened?

**[Kubernetes e2e suite: [It] [sig-network] Services should create endpoints for unready pods](https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/test/e2e/network/service.go#L1752-L1835)**

This test validates the existence of endpoints of unready pods of a service (with  PublishNotReadyAddresses: true) by probing service with curl requests, in other words depend on kube-proxy to check if the endpoints exists for the service with unready pods. 

### What did you expect to happen?

If I'm not wrong, the purpose of setting `PublishNotReadyAddresses: true` is to make sure the endpoint/endpointslices exists even if the pods are not ready to make sure coredns is able to create A/AAAA records. 

The test should simply check if the endpoints/endpointslices exists for the given service rather than expecting a response from the curl request, i.e. should not depend on kube-proxy.

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/test/e2e/network/service.go#L4195-L4196

There are some discussions https://github.com/kubernetes/kubernetes/pull/119394#discussion_r1282269250 going on to ignore **Ready**  condition and only use **Serving** and **Terminating** for programming data path. This test becomes a blocker for that task. 

### How can we reproduce it (as minimally and precisely as possible)?

The test currently passes as kube-proxy currently uses `EndpointConditions.Ready` for programming endpoints. 
Switching from `EndpointConditions.Ready` -> `EndpointConditions.Serving && !EndpointConditions.Terminating` fails the test. 

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/endpointslice/utils.go#L36-L42

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
KIND
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
> The test should simply check if the endpoints/endpointslices exists for the given service rather than expecting a response from the curl request, i.e. should not depend on kube-proxy.

an e2e test must depend on the proxy implementation, otherwise we'll just do an integration test

> The test should simply check if the endpoints/endpointslices exists for the given service rather than expecting a response from the curl request, i.e. should not depend on kube-proxy.

it should expect a response, the purpose of this option on services is just that

> Ready condition and only use Serving 

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/staging/src/k8s.io/api/discovery/v1/types.go#L129-L144

> There are some discussions https://github.com/kubernetes/kubernetes/pull/119394#discussion_r1282269250 going on to ignore Ready condition and only use Serving and Terminating for programming data path. This test becomes a blocker for that task.

I didn't check that PR but we can not change an existing behavior

**Comment by aroradaman** [comment]
I misunderstood the purpose of `PublishNotReadyAddresses`. I thought it was only meant for DNS record creation, for unready pods, which core dns creates by watching endpoint slices and the test could simply be covered by validating endpoints/endpoint slices or validating DNS records.
 
/close
