### ISSUE TITLE
Flaky test: Kubernetes e2e suite: [It] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should reject everything except leases 

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes/kubernetes#119787]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119754/pull-kubernetes-e2e-kind-ipv6/1688119121729818624

### Which tests are flaking?

Kubernetes e2e suite: [It] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] should reject everything except leases 

### Since when has it been flaking?

The job was run on Aug 5th. I had a PR #119754 fixing typos in comments of kubelet source code. It is not related to api-machinery ipv6 but the test failed. The re-test passed.  

### Anything else we need to know?

It seems the test is recently added.

### Relevant SIG(s)

/sig api-machinery
/sig testing

**Comment by aojea** [comment]
It is failing considerably https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel&width=20, it seems it fails to connect to the webhook

> { failed [FAILED] waiting for webhook configuration to be ready: Internal error occurred: failed calling webhook "validation-webhook-with-match-conditions.k8s.io": failed to call webhook: Post "https://e2e-test-webhook.webhook-1694.svc:8443/always-deny?timeout=10s": dial tcp 10.96.224.197:8443: connect: connection refused
> In [It] at: test/e2e/apimachinery/webhook.go:886 @ 08/06/23 00:48:12.906
> }
> 

it seems started to fail constantly on 26/7  https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=connection%20refused&test=AdmissionWebhook

that matches the time the test was added https://github.com/kubernetes/kubernetes/pull/118319

I don't fully understand the test but it seems that is interacting with the cluster, I don't have clear if the deny policy affects everything and this is causing the race with the pod that implements the webhook

/priority critical-urgent
/release blocker
/cc @jpbetz @liggitt @kubernetes/release-managers

**Comment by jpbetz** [comment]
cc @a-hilaly

**Comment by aojea** [comment]
Debugged with Joe offline, paste for reference


> This test https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1688439322652446720
click open stderr on the failure to get the timeline

> These are the timestamps interesting for usSTEP: Verifying the service has paired with the endpoint - test/e2e/apimachinery/webhook.go:1203 @ 08/07/23 06:57:15.818

```
Aug  7 06:57:16.819: INFO: Waiting for amount of service:e2e-test-webhook endpoints to be 1
< Exit [BeforeEach] [sig-api-machinery] AdmissionWebhook [Privileged:ClusterAdmin] - test/e2e/apimachinery/webhook.go:93 @ 08/07/23 06:57:16.835 (4.346s)
> Enter [It] should reject everything except leases - test/e2e/apimachinery/webhook.go:868 @ 08/07/23 06:57:16.835
STEP: creating a validating webhook with match conditions - test/e2e/apimachinery/webhook.go:876 @ 08/07/23 06:57:16.835
Aug  7 06:57:16.870: INFO: Unexpected error: waiting for webhook configuration to be ready: 
if you get the kube-controller manager logs https://gcsweb.k8s.io/gcs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1688439322652446720/artifacts/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_f98117797530dede9ccfefc535d027f1/kube-controller-manager/
the ones on [0.log.20230807-065809](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1688439322652446720/artifacts/kind-control-plane/pods/kube-system_kube-controller-manager-kind-control-plane_f98117797530dede9ccfefc535d027f1/kube-controller-manager/0.log.20230807-065809)
2023-08-07T06:57:15.822075768Z stderr F I0807 06:57:15.821931       1 endpoints_controller.go:523] "Update endpoints" service="webhook-2127/e2e-test-webhook" readyEndpoints=1 notreadyEndpoints=0
2023-08-07T06:57:15.841085052Z stderr F I0807 06:57:15.840588       1 endpointslicemirroring_controller.go:285] "syncEndpoints" key="webhook-2127/e2e-test-webhook"
2023-08-07T06:57:15.841105944Z stderr F I0807 06:57:15.840628       1 endpointslicemirroring_controller.go:320] "Service now has selector, cleaning up any mirrored EndpointSlices" service="webhook-2127/e2e-test-webhook"
2023-08-07T06:57:15.841121502Z stderr F I0807 06:57:15.840663       1 endpointslicemirroring_controller.go:282] "Finished syncing EndpointSlices for Endpoints" key="webhook-2127/e2e-test-webhook" elapsedTime="85.643µs"
2023-08-07T06:57:15.841127683Z stderr F I0807 06:57:15.840699       1 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="webhook-2127/e2e-test-webhook" elapsedTime="19.383719ms"
2023-08-07T06:57:15.841132984Z stderr F I0807 06:57:15.840767       1 endpoints_controller.go:363] "Finished syncing service endpoints" service="webhook-2127/e2e-test-webhook" startTime="19.131003ms"
```

> that is Aug  7 06:57:16.819: INFO: Waiting for amount of service:e2e-test-webhook endpoints to be 1
> however, endpointslices finish syncing at 2023-08-07T06:57:16.898393955Z stderr F I0807 06:57:16.898270       1 endpointslice_controller.go:323] "Finished syncing service endpoint slices" key="webhook-2127/e2e-test-webhook" elapsedTime="21.315µs"
> and the error is at 06:57:16.870: INFO: Unexpected error: waiting for webhook configuration to be ready:

> Joe Betz, 38 min
> Oh, so the endpoints are reported are synced but the endpoint slices are unverified, and the test starts it's 30s wait and then times out because the endpoint slices don't always happen to get synced that quick (since it's now a race)?

> Antonio Ojea, 37 min
> the kube-proxy or other network component
> only watches slcies since 1.21
> so, when you want to connect to a service
> you need kube.-proxy to program the dataplane

**Comment by liggitt** [comment]
still failing after merge of https://github.com/kubernetes/kubernetes/pull/119798: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119835/pull-kubernetes-e2e-kind/1688980783198375936

**Comment by jpbetz** [comment]
It's suspicious that of all the admission webhook tests that start up a webhook pod, this is the one that flakes. I'll look more closely.

**Comment by jpbetz** [comment]
Looks like the webhook in this test may be configured to deny requests except leases globally in the cluster once enabled., which might be that this creates a race between webhook pod creation and webhook configuration registration.

I'll scope the webhook matching to the test namespace per @liggitt's offline suggestion.

**Comment by pbxqdown** [comment]
Please let me know if I can be of help debugging this.😊Have free cycle and would like to contribute.

**Comment by jiahuif** [comment]
I can still see references to the expression that gives error
https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apimachinery/webhook.go#L719
Example run: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120008/pull-kubernetes-e2e-gce/1696859184227684352/
Could you help confirm that the tests are completely removed? Thank you.

cc @BenTheElder

**Comment by a-hilaly** [comment]
I think this is another test that is impacting the rest of the tests. Probably because the tests are running in parrallel. We might want to scope things down. Currently working on a fix.

**Comment by aojea** [comment]
> I think this is another test that is impacting the rest of the tests. Probably because the tests are running in parrallel. We might want to scope things down. Currently working on a fix.

@jiahuif this is a new bug, @jpbetz please review all the `AdmissionWebhook` test that were added and verify they are scoped to the custom created namespaces by the test framework, and if not, please tag them as `[Serial]`

cc: @liggitt

**Comment by cici37** [comment]
I assume this could be closed with https://github.com/kubernetes/kubernetes/pull/119869 merged?
/cc @jiahuif @pbxqdown @aojea

**Comment by jiahuif** [comment]
http://go.k8s.io/triage
Looks like the exact flak as reported in this issue has been resolved.
/close
