### ISSUE TITLE
replace testutils.RunDeployment in the autoscaler tests w/ "e2edeployment" so we can deduplocate the testutils RunDeployment func from the e2edeployment factory

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/kubernetes#119774]
### What happened?

# Problem
We have some redundant e2e test libraries it looks like that might be confusing new contributors.
- e2edeployment.NewDeployment (correct) way of making deployments for e2e tests
- testutils.RunDeployment (other/old) way of making deployments for e2e tests

# Details
Looks like in https://github.com/kubernetes/kubernetes/pull/119623/files#diff-2191f4f175779dcfa927c21f8fc225d9d031000f516d17babb42d645f3100a9c, we found out that the **autoscaler** tests use an obsolete testutils.RunDeployment function.

This has been since replaced w/ e2edeployment.

Lets remove the old RunDeployment function since, the advice is now, to use the e2edeployment package: 

# solution 

Looks like the steps to use this are something like this: (i.e. .//test/e2e/apimachinery/garbage_collector.go) 
```
        // make a client
        deployClient := clientSet.AppsV1().Deployments(f.Namespace.Name)

       deployment := e2edeployment.NewDeployment(deploymentName, 2, labels, "nginx", imageutils.GetE2EImage(imageutils.Nginx), appsv1.RollingUpdateDeploymentStrategyType)
        
        createdDeployment, err := deployClient.Create(context.TODO(), deployment, metav1.CreateOptions{})
```

### What did you expect to happen?

We would have only one way to make deployments in e2e test

### How can we reproduce it (as minimally and precisely as possible)?

see the linked PR

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/cc @pohly 

Patrick has been doing some refactor and reorganization on the e2e folder, he is the best person to review these changes

**Comment by pohly** [comment]
Short version: yes, please avoid adding more usage of `test/utils`. If possible, remove code from it and (where necessary) move it to `test/e2e`. 

Long version: I definitely see potential for unification between integration testing and E2E testing. Both connect to an API server, do something, wait for the result, etc.

With all the [recent changes](https://www.kubernetes.dev/blog/2023/04/12/e2e-testing-best-practices-reloaded/), `test/e2e/framework` is in a much better state than it was before.  However, it currently cannot be used for integration testing:
- Instantiating a `framework.Framework` doesn't work (needs a config file).
- The default checks in `framework.Framework` (for example, ready nodes) won't work.
- Some code like `framework.ExpectNoError` relies in a global failure handler in Gomega and won't work with a per-testcase `testing.T` in an integration test.

But having said all that, all functions under `test/e2e` which accept a client and return an error are definitely usable already also for integration testing. Therefore I don't see a need for `RunDeployment` and would like to see it removed.

**Comment by pohly** [comment]
@pramitagautam: are you still interested in working on this?

/remove-lifecycle stale

**Comment by pramitagautam** [comment]
I created https://github.com/kubernetes/kubernetes/pull/119623 pull request but it was on hold as I was suggested to submit the same for 1.29 version later.

After that I didn't look into it. 
But I will work on it. Hope that's fine @pohly.
