### ISSUE TITLE
e2e-capz-windows PRESUBMIT release-1.27 jobs seems to be consistently failing

### ISSUE THREAD

**Issue by ffromani** [kubernetes/kubernetes#119734]
### Which jobs are failing?

The **presubmit** pull-kubernetes-e2e-capz-windows-1-27 job seems to fail to setup (even before running the actual test) on 1.27

### Which tests are failing?

[FAIL] [sig-node] Container Runtime blackbox test when running a container with a new image [It] should be able to pull from private registry with secret [NodeConformance]

But the actual failure seems to be in the setup stage?
```
     Aug  2 09:04:20.727: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8: { } Scheduled: Successfully assigned container-runtime-4242/image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8 to capz-conf-w8k46
    Aug  2 09:04:20.727: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for image-pull-test47ceab42-a63d-4e76-9d06-ec1121138042: { } Scheduled: Successfully assigned container-runtime-4242/image-pull-test47ceab42-a63d-4e76-9d06-ec1121138042 to capz-conf-w8k46
    Aug  2 09:04:20.727: INFO: At 0001-01-01 00:00:00 +0000 UTC - event for image-pull-testcd9a2a7b-b4fa-4224-9a3f-2aa3cedcf68a: { } Scheduled: Successfully assigned container-runtime-4242/image-pull-testcd9a2a7b-b4fa-4224-9a3f-2aa3cedcf68a to capz-conf-w8k46
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:49:19 +0000 UTC - event for image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8: {kubelet capz-conf-w8k46} Pulling: Pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:49:22 +0000 UTC - event for image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8: {kubelet capz-conf-w8k46} Failed: Error: ErrImagePull
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:49:22 +0000 UTC - event for image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8: {kubelet capz-conf-w8k46} Failed: Failed to pull image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1": rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1": no match for platform in manifest: not found
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:49:23 +0000 UTC - event for image-pull-test1ca0bfd9-3328-4b68-890c-1d15cf3800f8: {kubelet capz-conf-w8k46} BackOff: Back-off pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:54:20 +0000 UTC - event for image-pull-testcd9a2a7b-b4fa-4224-9a3f-2aa3cedcf68a: {kubelet capz-conf-w8k46} Pulling: Pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:54:22 +0000 UTC - event for image-pull-testcd9a2a7b-b4fa-4224-9a3f-2aa3cedcf68a: {kubelet capz-conf-w8k46} Failed: Error: ErrImagePull
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:54:22 +0000 UTC - event for image-pull-testcd9a2a7b-b4fa-4224-9a3f-2aa3cedcf68a: {kubelet capz-conf-w8k46} BackOff: Back-off pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:59:21 +0000 UTC - event for image-pull-test47ceab42-a63d-4e76-9d06-ec1121138042: {kubelet capz-conf-w8k46} Pulling: Pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:59:23 +0000 UTC - event for image-pull-test47ceab42-a63d-4e76-9d06-ec1121138042: {kubelet capz-conf-w8k46} Failed: Error: ErrImagePull
    Aug  2 09:04:20.727: INFO: At 2023-08-02 08:59:24 +0000 UTC - event for image-pull-test47ceab42-a63d-4e76-9d06-ec1121138042: {kubelet capz-conf-w8k46} BackOff: Back-off pulling image "gcr.io/authenticated-image-pulling/windows-nanoserver:v1"
```

### Since when has it been failing?

Can't say. I'm using the presubmit jobs as due diligence to validate a backport (https://github.com/kubernetes/kubernetes/pull/119432) and noticed the failures. Filed a testing PR to crosscheck if the backport is causing the issue or not and it seems even that testing PR is hitting the very same issues: https://github.com/kubernetes/kubernetes/pull/119590 which suggests the job is at fault.

Also see: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/119432/pull-kubernetes-e2e-capz-windows-1-27/1683770620329857024

### Testgrid link

https://testgrid.k8s.io/sig-windows-presubmit#pull-kubernetes-e2e-capz-windows-1.27

### Reason for failure (if possible)

It seems the job fails to setup the cluster. Unfortunately I'm not expert enough to dive deeper

### Relevant SIG(s)

/sig node
/sig windows

**Comment by ffromani** [comment]
looks similar to https://github.com/kubernetes/kubernetes/issues/113925

**Comment by ffromani** [comment]
update: it seems only the 1.27 branch is failing. Possibly related:
https://github.com/kubernetes/kubernetes/issues/117185
https://github.com/kubernetes/test-infra/pull/28144

**Comment by jsturtevant** [comment]
We believe this is related to WS2022 and the repolist is missing the entries for the private image.

/triage accepted
/priority important-soon

**Comment by ffromani** [comment]
/reopen

I agree that https://github.com/kubernetes/test-infra/pull/30348 , while useful, is likely not enough to close this issue

**Comment by ffromani** [comment]
/close

I should have checked https://github.com/kubernetes/test-infra/pull/30352 before: it seems the lane is all fixed now. Thanks a lot!
