### ISSUE TITLE
minimum-image-ttl-duration is not working after restart kubelet

### ISSUE THREAD

**Issue by ytinirt** [kubernetes/kubernetes#119711]
### What happened?

When a node is under disk pressure, restarting kubelet will lead to image gc immediately, even if we set a long `minimum-image-ttl-duration`.

### What did you expect to happen?

image gc honor `minimum-image-ttl-duration` when we restart kubelet of a node under disk pressure.

### How can we reproduce it (as minimally and precisely as possible)?

1. configuring a long `minimum-image-ttl-duration`, e.g. 10m.  (`minimum-image-ttl-duration`'s default value is 2 minutes, which is short enough to make many people overlook this issue.)
2. make sure node is under disk pressure, e.g. nodefs utilization 85%+ (without imagefs)
3. pull new image on disk pressure node, make sure there are unused images on this node
4. restart kubelet
5. after a short time, all unused images will be gc, and `minimum-image-ttl-duration` is not yet reached

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
1.25.8
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
CentOS
$ uname -a
# paste output here
5.15.67

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
crio version 1.24.3
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ytinirt** [comment]
After code digging, I found that when image gc manager startting, it uses **zero time** to initialize images' firstDetected time:
```golang
func (im *realImageGCManager) Start() {
	ctx := context.Background()
	go wait.Until(func() {
		// Initial detection make detected time "unknown" in the past.
		var ts time.Time
		if im.initialized {
			ts = time.Now()
		}
		_, err := im.detectImages(ctx, ts)
...
```
More details in [source code link](https://github.com/kubernetes/kubernetes/blob/99190634ab252604a4496882912ac328542d649d/pkg/kubelet/images/image_gc_manager.go#L194-L198)

firstDetected at **zero time**, which means image detected at "the begining of the time", it's too old and already exceeded the `minimum-image-ttl-duration`:
```golang
		// Avoid garbage collect the image if the image is not old enough.
		// In such a case, the image may have just been pulled down, and will be used by a container right away.

		if freeTime.Sub(image.firstDetected) < im.policy.MinAge {
			klog.V(5).InfoS("Image ID's age is less than the policy's minAge, not eligible for garbage collection", "imageID", image.id, "age", freeTime.Sub(image.firstDetected), "minAge", im.policy.MinAge)
			continue
		}
```
More details on [source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/image_gc_manager.go#L394)

After that, all unused images will be gc, and make `minimum-image-ttl-duration` not working.

**Comment by ffromani** [comment]
this seems a dupe of https://github.com/kubernetes/kubernetes/issues/119642?

**Comment by tzneal** [comment]
Agree, seems like a duplicate.
/close dupe
