### ISSUE TITLE
AWS + CoreOS + k8s 1.0.1 Documentation

### ISSUE THREAD

**Issue by mcadam** [kubernetes/kubernetes#11975]
Hello, 

Is there more documentation on how to run a Kubernetes cluster using CoreOS on AWS ??

I tried the script for AWS specifying KUBE_OS_DISTRIBUTION=coreos, it started a master on ubuntu, and then tried to launch my minions but they all crashed. 

I first had to modify the cluster/aws/coreos/util.sh script and delete those lines to make the script go this far:

```shell
  i=$1
  # TODO(bakins): Is this actually used?
  MINION_PRIVATE_IP=$INTERNAL_IP_BASE.1${i}
  
  MINION_IP=$(yaml-quote ${MINION_PRIVATE_IP})
```

That crashed because you dont use a loop anymore to create the minions.

Do you have a solution to use the script to start a cluster automatically, like create credentials and give me access to the cluster directly. I dont want to use the other guide in the multi-node coreos page, because it is basically useless as is. What do i do once the masters and minions are running ?  SSH to get the credentials ? 

I would love to be able to use the autoscaling group approach from the other script :)

I am on kubernetes version 1.0.1.

**Comment by mikedanese** [comment]
@kelseyhightower

**Comment by joshm1** [comment]
I had the same issue. Not exactly knowing if it would help, I just updated `i=$1` to `i=${i:-0}` and it at least launched the minions in.  This doesn't make much sense since it sets MINION_IP in user-data to the same IP for all minions created, but this didn't actually affect the internal IPs of my instances.  I had another issue after my cluster was up and running where dns-service resolution was only working in containers in 1 of the 2 minions I launched.  Not sure if that is related, but this has been a big blocker for me in getting kubernetes up and running on AWS with coreos.

**Comment by mcadam** [comment]
I ha ve at the same stage as you @joshm1, when trying to access the UI I get this error:

Error: 'dial tcp 172.17.0.2:8080: no route to host'
Trying to reach: 'http://172.17.0.2:8080/'

It seems the network stack is missing something ?

**Comment by mikedanese** [comment]
You should be accessing it through the apiserver proxy. Run:
```
kubectl proxy
```
Then go to http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/kube-ui

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/connecting-to-applications-proxy.md

**Comment by mcadam** [comment]
I tried to access it using address like https://xx.xx.xx.xx/api/v1/proxy/namespaces/kube-system/services/kube-ui on the IP of the master, which used to work when not using coreos as kube distribution.

Also I cant ping from one container to another.

**Comment by pires** [comment]
Have you guys tried https://github.com/kubernetes/kubernetes/blob/master/docs/getting-started-guides/coreos/coreos_multinode_cluster.md?

**Comment by mcadam** [comment]
yes I tried I am using that currently but it is not a hand key version, like authentication you need a ssh tunnel, you dont have all the addons, the UI doesnt work.

**Comment by ngbinh** [comment]
I had the same problem with @mcadam on 1.0.3.

**Comment by pires** [comment]
@mcadam there is no UI nor secure API access, indeed. But it's better than not having a cluster, am I right? Joke aside, it would be great if the alternative CoreOS documentation would include this.  I will be adding it to #9178

**Comment by mikedanese** [comment]
I suggest checking out https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/debugging-services.md

**Comment by bcwaldon** [comment]
CoreOS is now maintaining official "Kubernetes on CoreOS" documentation. See the AWS guide here: https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html

**Comment by aronchick** [comment]
I would suspect this is hideously out of date. Please reopen if it's still an issue.
