### ISSUE TITLE
Unit Tests in apiserver/pkg/storage/storagebackend/factory/factory_test.go are flaking

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [kubernetes/kubernetes#119704]
### Which jobs are flaking?

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-unit
https://prow.ppc64le-cloud.cis.ibm.net/job-history/gs/ppc64le-kubernetes/logs/periodic-kubernetes-unit-test-ppc64le

### Which tests are flaking?

apiserver/pkg/storage/storagebackend/factory
TestRateLimitHealthcheck
TestCreateHealthcheck
TestCreateReadycheck
TestTimeTravelHealthcheck

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit
https://testgrid.k8s.io/ibm-unit-tests-ppc64le#Periodic%20unit%20test%20suite%20on%20ppc64le

### Reason for failure (if possible)
**"etcd client connection not yet established"** _is the error seen while test fails._

```
--- FAIL: TestCreateHealthcheck (11.84s)
    --- FAIL: TestCreateHealthcheck/timeouts_if_response_time_higher_than_default_timeout (1.00s)
        factory_test.go:141: healthcheck() missmatch want context deadline exceeded got etcd client connection not yet established
FAIL

```

### Anything else we need to know?

Flaking in `x86` and `ppc64le` architectures.

```
[root@toad1 kubernetes]# go test ./vendor/k8s.io/apiserver/pkg/storage/storagebackend/factory/ -c -count=1 -race
[root@toad1 kubernetes]# /root/go/bin/stress ./factory.test -test.run TestCreateHealthcheck
5s: 0 runs so far, 0 failures
10s: 0 runs so far, 0 failures
15s: 4 runs so far, 0 failures
20s: 4 runs so far, 0 failures
25s: 4 runs so far, 0 failures
30s: 8 runs so far, 0 failures
35s: 8 runs so far, 0 failures
40s: 8 runs so far, 0 failures
45s: 12 runs so far, 0 failures
50s: 12 runs so far, 0 failures
55s: 14 runs so far, 0 failures
1m0s: 16 runs so far, 0 failures
1m5s: 16 runs so far, 0 failures
1m10s: 20 runs so far, 0 failures
1m15s: 20 runs so far, 0 failures
1m20s: 20 runs so far, 0 failures
1m25s: 24 runs so far, 0 failures
1m30s: 24 runs so far, 0 failures
1m35s: 25 runs so far, 0 failures
1m40s: 28 runs so far, 0 failures
1m45s: 28 runs so far, 0 failures

/tmp/go-stress-20230731T233310-2168723831
--- FAIL: TestCreateHealthcheck (11.84s)
    --- FAIL: TestCreateHealthcheck/timeouts_if_response_time_higher_than_default_timeout (1.00s)
        factory_test.go:141: healthcheck() missmatch want context deadline exceeded got etcd client connection not yet established
FAIL


ERROR: exit status 1

1m50s: 31 runs so far, 1 failures (3.23%)
^C
[root@toad1 kubernetes]#
```

[go-stress-20230731T233310-2168723831.txt](https://github.com/kubernetes/kubernetes/files/12232935/go-stress-20230731T233310-2168723831.txt)

### Relevant SIG(s)

/sig

**Comment by jiahuif** [comment]
/assign @aojea @Argh4k 
as the original authors
/triage accepted
