### ISSUE TITLE
Bind mounting Kubelet root-dir causes staging volumes to never be cleaned up for ReadWriteMany PVCs

### ISSUE THREAD

**Issue by ADustyOldMuffin** [kubernetes/kubernetes#119752]
### What happened?

For various reasons I have an installation of Kubelet on all nodes in a cluster bind mounted to another location on disk. When a volume is staged on a node this causes the staging volume to appear twice when running the `mount` command. Here's an example of such an instance with a pod on the node,

```
~$ mount | grep pvc-my-volume
<scrub>:/volumes/csi/csi-vol-uuid on /some/path/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount type <scrub>
<scrub>:/volumes/csi/csi-vol-uuid on /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount type <scrub>
<scrub>:/volumes/csi/csi-vol-uuid on /some/path/kubelet/pods/pod-id/volumes/kubernetes.io~csi/pvc-my-volume/mount type <scrub>
<scrub>:/volumes/csi/csi-vol-uuid/pod-id on /var/lib/kubelet/pods/pod-id/volumes/kubernetes.io~csi/pvc-my-volume/mount type <scrub>
```

How ever when the pod is deleted you would expect all of these mounts to be removed since no pods are on the node anymore requiring the volume, and `NodeUnstageVolume` should be called on the CSI.

If you take a look in the logs you'll see an error (only the error is here to scrub info from the log)
`kubelet[6307]: 6307 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/<scrub> podName: nodeName:}" failed. Error: "GetDeviceMountRefs check failed for volume \"pvc-my-volume\" (UniqueName: \"kubernetes.io/csi/<scrub>\") on node \"my-node\" : the device mount path \"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount\" is still mounted by other references [/some/path/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount]"`

This is caused by this check
https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/volume/util/operationexecutor/operation_generator.go#L947-L955

Which fails on a false flag that the mount is itself the reference. This seems to only happen on `ReadWriteMany` volumes, and we particularly noticed because we're using ceph-csi with CephFS and RBD. We sometimes have clients holding onto locks for folders and files in these staging mounts, and normally you'd delete the pod and the lock would be free, but due to this they stick around and the only fix is to manually umount the path. This doesn't happen for RBD as Kubelet correctly calls `NodeUnstageVolume` for the CSI plugin, but not CephFS.

### What did you expect to happen?

When all pods are removed from a node then Kubelet should call `NodeUnstageVolume` for the given CSI plugin and not error out.

### How can we reproduce it (as minimally and precisely as possible)?

1. Install Rook and setup a Ceph cluster with CephFS
2. Create a PVC with a storage class for CephFS and access mode `ReadWriteMany`
3. On a node bind mount `/var/lib/kubelet` to another directory on disk (IE `bind --mount /var/lib/kubelet /tmp/kubelet`
4. On this same node, schedule a pod and mount the PVC
5. Observe 4 mounts for this pod, 2 staging and 2 regular
6. Delete the pod
7. Observe 2 staging mounts for this PVC and errors in kubelet logs

### Anything else we need to know?

I have already tested a fix for this and located where to fix it.

The issue stems from here 
https://github.com/kubernetes/mount-utils/blob/41e8de37ef8a3782f9cd6c915699b98b2b24b2c4/mount_linux.go#L687-L728

This specific function is just looping through all mounts and checking the root path, and major:minor of the mounts. While this works generally, once you bind mount the `/var/lib/kubelet` directory this will always return 1 reference to all staging mounts.

If you inspect the mountinfo on the node (where this is getting the info), you'll notice that the parent IDs for the `/var/lib/kubelet` mounts are all the same but the bind mounted ones are not.

We can then make this change to fix it
```
+       parentID := 0
        rootPath := ""
        major := -1
        minor := -1
@@ -566,6 +568,7 @@ func SearchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
                if hostSource == mis[i].MountPoint || PathWithinBase(hostSource, mis[i].MountPoint) {
                        // If it's a mount point or path under a mount point.
                        mountID = mis[i].ID
+                       parentID = mis[i].ParentID
                        rootPath = filepath.Join(mis[i].Root, strings.TrimPrefix(hostSource, mis[i].MountPoint))
                        major = mis[i].Major
                        minor = mis[i].Minor
@@ -579,8 +582,8 @@ func SearchMountPoints(hostSource, mountInfoPath string) ([]string, error) {
 
        var refs []string
        for i := range mis {
-               if mis[i].ID == mountID {
-                       // Ignore mount entry for mount source itself.
+               if mis[i].ID == mountID || mis[i].ParentID != parentID {
+                       // Ignore mount entry for mount source itself, and other refs that don't have the same parentID.
                        continue
                }
                if mis[i].Root == rootPath && mis[i].Major == major && mis[i].Minor == minor {
```

I made these changes locally, built Kubelet, and setup my test node with the patched Kubelet and the staging directory was removed and `NodeUnstageVolume` was called in my CSI plugin with no issues.

I do not believe this should affect any other use case as realistically any mount based on the staging mount should have the same Parent ID. I'm happy to make a PR for this if this is found to be an acceptable solution.

### Kubernetes version

<details>
N/A as this happens in multiple version, and the needed change hasn't had the code changed in 3+ years.
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
N/A but can post if needed.
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CSI
</details>

**Comment by xing-yang** [comment]
cc @jsafrane

**Comment by jsafrane** [comment]
If I understand it correctly, you want kubelet to detect that `/some/path/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount` will be automatically removed from `/proc/1/mountinfo` when kubelet unmounts `/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-my-volume/globalmount`.

I am not sure how ParentID helps with that. IMO it can produce false positives. A mount with different ParentID may exist due to a bind mount, but it can have a different ParentID from different reasons.

Consider this:

```
# Mount done by kubelet
mkdir /var/lib/kubelet/test
mount /dev/sda /var/lib/kubelet/test

# Mount done by user (or something, just not bind-mount)
mkdir /mnt/tmp1
mount -t tmpfs xxx /mnt/tmp1
mdkir /mnt/tmp1/test
mount /dev/sda /mnt/tmp1/test
```

These two mounts will have a different parent ID (one is on /var, second on tmpfs), yet one won't disappear if you unmount the other one.

Kubelet's detection if it's safe to detach a volume (i.e. it's not mounted elsewhere) is not great*. But IMO https://github.com/kubernetes/kubernetes/pull/119845 does not help here much. Maybe we could reconsider what kubelet treats as "safe to detach" - right now, the global mount must be the last one to unmount, even when user or some script mounted the volume elsewhere. We could change it to detach volumes when all mounts *done by kubelet* were unmounted and if the volume is still mounted by user, it's not kubelet's problem. But that would be probably a bigger change.


*) why do we compare `Root` and not `Source`? `Root` is almost always `/`.

**Comment by ADustyOldMuffin** [comment]
I'm not quite sure I understand the concern, so in your case someone has mounted something to a staging mount outside of Kubernetes/Kubelet which I wouldn't think Kubelet would/should care about. 

We're specifically checking for the case that something Kubelet has done has generated 2 mounts, and as such it should ignore the 2nd because its something Kubelet itself has caused. Without ignoring this Kubelet will never actually cleanup the mount and its stuck on the host forever until manual intervention happens.

**Comment by ADustyOldMuffin** [comment]
@jsafrane Would you mind expanding on the points above?

**Comment by huww98** [comment]
@ADustyOldMuffin I think this issue has already been fixed by https://github.com/kubernetes/kubernetes/pull/112607

**Comment by ADustyOldMuffin** [comment]
I believe I'd agree! I'll close this.
