### ISSUE TITLE
sched: CycleState.SkipFilterPlugins not always injected into cycleState

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#119767]
### What happened?

In k8s 1.27, scheduler introduced a new "short circuit" semantics in PreFilter to bypass a Pod quickly. A change introduced here is it relies on that plugin to be stored in `CycleState.SkipFilterPlugins`, which makes sense as what it was explained [here](https://github.com/kubernetes/kubernetes/pull/114125/files#r1062646736).

However, the `SkipFilterPlugins` info, although is populated upon each plugin's PreFilter invocation, is not injected into `CycleState` when some PreFilter returns unschedulable:

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/scheduler/framework/runtime/framework.go#L655-L661

So think about this workflow:

- pluginA returns Skip in its PreFilter
- pluginB return Unschedulable in its PreFilter
- note: pluginA is not included in `CycleState.SkipFilterPlugins` due to aforementioned bug
- a Pod is claimed as unschedulable (failed by pluginB)
- during PostFilter, it's **supposed** to bypass pluginA's PreEnqueueExtension's AddPod/RemovePod, but it doesn't
- calling a "skipped" Plugin's AddPod/RemovePod during preemption, sometimes will abort the whole preemption as the logic tries to read info from cycleState, and some plugin's "skip" version doesn't fill cycleState properly, e.g., InterPodAffinity (skip immediately w/o write preFilterStateKey).

https://github.com/kubernetes/kubernetes/blob/2c6c4566eff972d6c1320b5f8ad795f88c822d09/pkg/scheduler/framework/plugins/interpodaffinity/filtering.go#L257-L262

### What did you expect to happen?

Short circuiting using Skip is fine, but `CycleState.SkipFilterPlugins` should injected properly at all cases.

### How can we reproduce it (as minimally and precisely as possible)?

Described in the workflow above.

It's firstly captured in an out-of-tree PostFilter plugin: https://github.com/kubernetes-sigs/scheduler-plugins/pull/608#issuecomment-1665855370, but can also happen in in-tree plugins.

### Kubernetes version

v1.27

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Huang-Wei** [comment]
cc @sanposhiho @alculquicondor

**Comment by Huang-Wei** [comment]
Among in-tree plugins, 3 plugins employ non-nil `PreFilterExtensions` and may return Skip in their PreFilter() implementation w/o writing `preFilterStateKey` to cycleState, while return error immediately if `preFilterStateKey` is missing in their Add/RemovePod() functions.

1. VolumeRestrictions
1. PodTopologySpread
1. InterPodAffinity

So technically, as long as a scheduling flow hit the following criteria, it would hit the bug (preemption doesn't function):

- plugin 1/2/3 return Skip in PreFilter
- arbitrary PreFilter plugin after the "skipped" plugin returns Unschedulable in its PreFilter

**Comment by zwpaper** [comment]
cc

**Comment by Huang-Wei** [comment]
Cherry-pick PRs:

- 1.28: https://github.com/kubernetes/kubernetes/pull/119942
- 1.27: https://github.com/kubernetes/kubernetes/pull/119943
