### ISSUE TITLE
e2e-gce-device-plugin-gpu PRESUBMIT release-1.2x jobs seems to be consistently failing

### ISSUE THREAD

**Issue by ffromani** [kubernetes/kubernetes#119730]
### Which jobs are failing?

The **presubmit** e2e-gce-device-plugin-gpu jobs seems to fail to setup (even before running the actual test) on 1.27

### Which tests are failing?

[sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests

### Since when has it been failing?

Can't say. I'm using the presubmit jobs as due diligence to validate a backport (https://github.com/kubernetes/kubernetes/pull/119432) and noticed the failures. Filed a testing PR to crosscheck if the backport is causing the issue or not and it seems even that testing PR is hitting the very same issues: https://github.com/kubernetes/kubernetes/pull/119590 which suggests the job is at fault.

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-nonblocking#pull-kubernetes-e2e-gce-device-plugin-gpu

### Reason for failure (if possible)

it seems the setup fails to complete at driver compilation stage?

### Relevant SIG(s)

/sig node

**Comment by lengrongfu** [comment]
The first investigation:
The gpu information is not registered on the node, and the nvidia-driver-installer container fails to start. There are two doubts:
- There is no gpu card on the machine,
- The driver version does not match the Linux kernel version
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/119590/pull-kubernetes-e2e-gce-device-plugin-gpu/1687064741190569984/artifacts/nodes.yaml

**Comment by ffromani** [comment]
fixed by https://github.com/kubernetes/test-infra/pull/30450
