### ISSUE TITLE
`--apiserver-count=1` is set, but flag is missing from docs. Is `apiserver-count` deprecated/unused?

### ISSUE THREAD

**Issue by erikschul** [kubernetes/kubernetes#119856]
### What happened?

I'm setting up a cluster from scratch, with 3 etcd servers, and 3 master nodes. This leaves the question whether `--apiserver-count` should be set to `3`. But it's missing from the [kube-apiserver docs](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/). So I'm assuming that it's deprecated.

But with `--v=4`, the kube-apiserver logs shows:
```
Aug 09 10:04:53 cp0 kube-apiserver[4645]: I0809 10:04:53.887199    4645 flags.go:64] FLAG: --apiserver-count="1"
```

Can someone clarify what this flag does, and what the consequence is of having 3 api servers configured with `--apiserver-count="1"`? Can any corruption occur?

When set, kube-apiserver also complains:
```
Flag --apiserver-count has been deprecated, apiserver-count is deprecated and will be removed in a future version.
```

### What did you expect to happen?

Flag was unexpected.

### How can we reproduce it (as minimally and precisely as possible)?

Ask if necessary.

### Kubernetes version

<details>

```console
v1.27.4
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
that option is no longer needed as the flag says, it is needed for the endpoints-reconciler type `master-count` , that has been deprecated too

```
--endpoint-reconciler-type string     Default: "lease"
Use an endpoint reconciler (master-count, lease, none) master-count is deprecated, and will be removed in a future version.
```

/close
