### ISSUE TITLE
node: provide or recommend a podresources API client

### ISSUE THREAD

**Issue by ffromani** [kubernetes/kubernetes#119817]
### What would you like to be added?

The [podresources API](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/606-compute-device-assignment) is a node-local API exposed by the kubelet graduating to GA in 1.28.
The project already exports the [API definitition proper](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubelet/pkg/apis/podresources) but not a client package.
Since this is a GA API, we should either provide easy to consume client code, or at least recommend a third party client.

For starters a golang client package is fine, and we ~should~ can [extend and polish the existing client code](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/podresources/client.go).

### Why is this needed?

Clients code wanting to consume the code maybe considering to reuse the existing client code, but this is [actively discouraged](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/podresources/client.go#L32).
One of the reasons seems to be that doing this will also require to import (and possibly vendor) `k8s.io/kubernetes`.

The only real option is to copy and paste the related code. For more details, the discussion started in the [feature graduation blog post](https://github.com/kubernetes/website/pull/42041#discussion_r1284673488), which have more details and example code (the discussion should however continue here).

[edit] clarified why importing the existing client code is a bad idea, which if nothing else makes this issue more relevant. [/edit]

**Comment by sftim** [comment]
How do we publish the `.proto` files for this? Are they a release artefact?

---

How about making the sample API client code in another language (eg Python)? Using another language emphasizes that you can use this from a client implemented in any language.

We don't mind what language a third party writes their own implementation in, right?

**Comment by ffromani** [comment]
> How do we publish the `.proto` files for this? Are they a release artefact?

Published in staging: https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kubelet/pkg/apis/podresources/v1
 
> How about making the sample API client code in another language (eg Python)? Using another language emphasizes that you can use this from a client implemented in any language.

That would be fine. I'm suggesting to promote the golang client because it's a reasonnable starting point and I know for sure there are golang projects consuming the API. But adding more clients is fine and helpful.

> We don't mind what language a third party writes their own implementation in, right?

AFAIK we don't mind at all
