### ISSUE TITLE
Namespace in terminating state

### ISSUE THREAD

**Issue by vuravenkatachaitanya** [kubernetes/kubernetes#119881]
### What happened?

Name space in terminating state since a day:
```
kgns|grep -i terminating
agent-ns       Terminating   12d
```
Checked other resources to see if those are having loopback or dependency (deployment, secret, daemon set etc)

### What did you expect to happen?

It should delete the namespace or show resources which are having issues and get the prompt. 

### How can we reproduce it (as minimally and precisely as possible)?

- Create NS and add some resources (deployment, secrets, roles, cluster role binds etc)
- Try deleting the namespace

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.15-eks-a5565ad", GitCommit:"af0b16a331376384fe84445fe2f8d4cb468b4148", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:37Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
➜  ~ 

```

</details>

### Cloud provider

<details>
EKS 1.24
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
EKS linux AMI
# paste output here
$ uname -a
# paste output here
no access to nodes

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
/remove-kind bug

I don't think we have enough evidence to confirm that this is a bug.
/priority awaiting-more-evidence

**Comment by ZeeFiix** [comment]
@vuravenkatachaitanya 
Please allow me one silly question...
Have you checked if there is no ressource / object existing in the namespace which has some finalizers configured which should be processed by pods which had been running in this namspace itself ?
When deleting the namespace the pods which should process the finalizers are probably already gone .. and so the namespace deletion simply waits for a finalizer which never will get processed

**Comment by vuravenkatachaitanya** [comment]
Fixed issue by following this blog :[[Kubectl: Force Delete Namespace Stuck In Terminating - ShellHacks](https://www.shellhacks.com/kubectl-force-delete-namespace-stuck-in-terminating/)](https://www.shellhacks.com/kubectl-force-delete-namespace-stuck-in-terminating/)

**Comment by vuravenkatachaitanya** [comment]
Even force delete did not work and command got hung for days. Only fixed when did the above fix.

**Comment by pacoxu** [comment]
> Fixed issue by following this blog :[[Kubectl: Force Delete Namespace Stuck In Terminating - ShellHacks](https://www.shellhacks.com/kubectl-force-delete-namespace-stuck-in-terminating/)](https://www.shellhacks.com/kubectl-force-delete-namespace-stuck-in-terminating/)

Namespace delete will hang for `finalizers`. This is as expected.

/close
