### ISSUE TITLE
Query about page Manage HugePages

### ISSUE THREAD

**Issue by seavershi** [kubernetes/kubernetes#119822]
How can I remove huge pages management of Kubernetes? 
Our application is a high-performance software which needs NUMA aware huge pages. But:
"the Memory Manager ensures that the memory which a pod requests is allocated from a minimum number of NUMA nodes."
Then if we cannot remove huge pages management of Kubernetes, how can we request the huge pages distributed cross NUMA nodes evenly?

**Comment by sftim** [comment]
If this turns out to be a request for more documentation that we didn't understand, please clarify and have it transferred back.

**Comment by seavershi** [comment]
OK. Then I submit an issue to the code:
https://github.com/kubernetes/kubernetes/issues/119851
