### ISSUE TITLE
dynamic-resource-allocation: PrepareResource won't be called on node reboot

### ISSUE THREAD

**Issue by moshe010** [kubernetes/kubernetes#119850]
### What happened?

We have k8s cluster with  Scalable function DRA driver deployed. 
We created Pod with resource claim to allocate Scalable function to Pod. 
When reboot the worker node the Pod with with Scalable function  failed to start with error [1].
The reason for the error is that PrepareResource is not called after reboot so we didn't create Scalable function  resource and prepare CDI file for it. 

[1] - Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873380    1851 remote_runtime.go:302] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3" podSandboxID="5ce2a000bf64e9b7d9570a95e53718f9369376b866b22fbbeed22f8faca2c88b"
Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873586    1851 kuberuntime_manager.go:1212] container &Container{Name:ctr,Image:docker.io/busybox,Command:[sleep 10000],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{ResourceClaim{Name:sf,},},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-5cs79,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},} start failed in pod test-pod_default(64de5407-6ae7-47b7-9229-1ab750117a38): CreateContainerError: failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3
Aug 09 09:58:45 cloud-dev-44 kubelet[1851]: E0809 09:58:45.873711    1851 pod_workers.go:1294] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"ctr\" with CreateContainerError: \"failed to create containerd container: CDI device injection failed: unresolvable CDI devices nvidia.com/net-sf=mlx5_core.sf.3\"" pod="default/test-pod" podUID=64de5407-6ae7-47b7-9229-1ab750117a38
Aug 09 09:58:59 cloud-dev-44 kubelet[1851]: I0809 09:58:59.891666    1851 scope.go:115] "RemoveContainer" containerID="11c40dace1080ff80bdc6695312d911536e1c3ca6c1844b38f6ba358ad8823da"

### What did you expect to happen?

The Pod should be in Running state

### How can we reproduce it (as minimally and precisely as possible)?

k8s v1.27.2
Scalable function DRA driver deployed
Create Pod with DRA Scalable function resource
reboot the worker node where the Pod runs

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:28Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
root@cloud-dev-44:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="[https://www.ubuntu.com/"](https://www.ubuntu.com/%22)
SUPPORT_URL="[https://help.ubuntu.com/"](https://help.ubuntu.com/%22)
BUG_REPORT_URL="[https://bugs.launchpad.net/ubuntu/"](https://bugs.launchpad.net/ubuntu/%22)
PRIVACY_POLICY_URL="[https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"](https://www.ubuntu.com/legal/terms-and-policies/privacy-policy%22)

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
 uname -a
Linux cloud-dev-44 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.7
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sidadarsalan** [comment]
What are you talking about?
