### ISSUE TITLE
kube-proxy: -v command line flag reset by --config file

### ISSUE THREAD

**Issue by pohly** [kubernetes/kubernetes#119864]
### What happened?

https://github.com/kubernetes/kubernetes/pull/117800 introduced configuration of additional logging aspects (e.g. format) through command line flags and config file. This was merged for Kubernetes 1.28.

Now the following invocation doesn't work as expected when the config file doesn't configure logging:
```
kube-proxy -- --config kube-proxy.conf -v=4
```

### What did you expect to happen?

It should run with verbosity 4. Instead it runs with verbosity 0, from the config.

### How can we reproduce it (as minimally and precisely as possible)?

Run with this config file:
```
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
```

### Kubernetes version

1.28 rc

### Cloud provider

n/a

**Comment by pohly** [comment]
The problem is caused by this line:

https://github.com/kubernetes/kubernetes/blob/f0dcf0614036d8c3cd1c9f3b3cf8df4bb1d8e44e/cmd/kube-proxy/app/server.go#L250

At that point, `o.config.Logging.Verbosity` is 4 (from the command line flag), and then it gets overwritten with `c.Verbosity` == 0.

The normal approach would be:
- set up config with defaults
- modify config through flags
- modify config further by parsing a config file into it.

Can kube-proxy do this? It has the downside that a config file can only overwrite fields if they are in the file. A config field doesn't get reset to defaults just by parsing the file.

/cc @cyclinder @liggitt @aojea

**Comment by liggitt** [comment]
it looks like kube-proxy special-cases the `processHostnameOverrideFlag` to let a flag override config... can/should it do the same thing for verbosity? are there any other flags like this?

**Comment by pohly** [comment]
> I don't think that's the normal approach...

Perhaps I should have said "this is how component-base/logs was meant to be used". Somehow it worked for kubelet.

Here's my preliminary solution: https://github.com/kubernetes/kubernetes/pull/119867

It needs more testing, but I wanted to share it early because I am running out of time today.

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/119523
