### ISSUE TITLE
Race condition on pod eviction due to taint manager

### ISSUE THREAD

**Issue by vDMG** [kubernetes/kubernetes#119862]
### What happened?

When running Kubernetes on AWS (EKS) version 1.24, we have a strange random race condition with the kube-controller-manager service, specifically the taint_manager component.

We use AWS autoscaler and cilium as CNI. At startup, all of our nodes have a taint with the key node.cilium.io/agent-not-ready, the value true, and the effect NoExecute. This taint is deleted by cilium when the node is ready. Once the taint is deleted, the scheduler can bind a pod to the node. However, the kube-controller-manager cannot see that the taint has been deleted and evicts the pod even though the taint no longer exists.

I have traced all of the logs and calls to the Kubernetes API or other components and have attached the history.

```
# kube-scheduler
I0809 00:12:58.755233      11 schedule_one.go:265] "Successfully bound pod to node" pod="default/test" node="ip-10-1-1-1.ec2.internal" evaluatedNodes=22 feasibleNodes=1

# kube-controller-manager
I0809 00:12:58.756918      10 taint_manager.go:353] "Not all taints are tolerated after update for pod on node" pod="default/test" node="ip-10-1-1-1.ec2.internal"
I0809 00:12:58.757005      10 taint_manager.go:106] "NoExecuteTaintManager is deleting pod" pod="default/test"
I0809 00:12:58.757713      10 event.go:294] "Event occurred" object="default/test" fieldPath="" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Marking for deletion Pod default/test"
I0809 00:12:58.763628      10 event.go:294] "Event occurred" object="default/test" fieldPath="" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Cancelling deletion of Pod default/test"

# kube-api-server 
2023-08-09T00:12:02.033236Z CREATE NODE ip-10-1-1-1.ec2.internal BY -- creating node with taint {"key":"node.cilium.io/agent-not-ready","value":"true","effect":"NoExecute"},{"key":"node.kubernetes.io/not-ready","effect":"NoSchedule"}
2023-08-09T00:12:29.099571Z PATCH NODE ip-10-1-1-1.ec2.internal BY system:serviceaccount:kube-system:node-controller (kube-controller-manager) -- removing taint node.kubernetes.io/not-ready
2023-08-09T00:12:58.748851Z PATCH NODE ip-10-1-1-1.ec2.internal BY system:serviceaccount:kube-system:cilium-operator (cilium-operator-aws) -- removing taint node.cilium.io/agent-not-ready
2023-08-09T00:12:58.763226Z DELETE PODS test BY system:serviceaccount:kube-system:node-controller (kube-controller-manager)
```

We can see that the kube-controller-manager attempts to cancel the deletion of the pod a few milliseconds after it is deleted.

### What did you expect to happen?

kube-controller-manager should let the pod bind to this node and do not start deleting the pod who is respecting existing taints and tolerations.

### How can we reproduce it (as minimally and precisely as possible)?

Using Kubernetes 1.24 : 
- Create a new node with taint `{"key":"node.cilium.io/agent-not-ready","value":"true","effect":"NoExecute"}`.
- Create a pod test with no specific tolerations
- Remove the taint 

Scheduler should bind the pod to this node, randomly the kube-controller-manager will try to evict this pod.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.15-eks-a5565ad", GitCommit:"af0b16a331376384fe84445fe2f8d4cb468b4148", GitTreeState:"clean", BuildDate:"2023-06-16T17:35:37Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS EKS 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux airflow-worker-0 5.10.176-157.645.amzn2.x86_64 #1 SMP Tue Mar 28 17:49:06 UTC 2023 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI : cilium 1.12.9
</details>

**Comment by mmiranda96** [comment]
Could you try reproducing on a supported Kubernetes version (eg. 1.27)?

/triage needs-information

**Comment by haircommander** [comment]
this looks related to pod lifecycle refactor happening in https://github.com/kubernetes/kubernetes/issues/116970
