### ISSUE TITLE
The management of HugePages memory in Kubernetes cannot be changed or deleted

### ISSUE THREAD

**Issue by seavershi** [kubernetes/kubernetes#119851]
### What happened?

The management of HugePages memory in kubernetes cannot provide a method to allocate the huge pages distributed cross NUMA nodes evenly, because it has below mechanism:
"the Memory Manager ensures that the memory which a pod requests is allocated from a minimum number of NUMA nodes."

This is unacceptable because there are many applications need the CPU and huge pages distributed cross NUMA nodes evenly, and   in fact, the kubenetes feature: cpu manager has provided a method to allocate CPU distributed cross NUMA nodes evenly.

### What did you expect to happen?

Provide a method to remove huge pages management of Kubernetes
Or:
Provide a method to allocate the huge pages distributed cross NUMA nodes evenly since CPU manager provides this method.

### How can we reproduce it (as minimally and precisely as possible)?

Step1: to configure kubelet in the worker node with below feature:
cpuManagerPolicy: static
cpuManagerPolicyOptions:
  distribute-cpus-across-numa: "true"
Step2: deploy a pod in this worker node with request and limit:
(1): CPU number bigger than the CPU number in one NUMA node.
(2): some huge pages.

Then you will see the CPU distributed cross NUMA nodes evenly, but all the huge pages are allocated in NUMA0.

### Anything else we need to know?

No.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}

</details>


### Cloud provider

<details>
Private Cloud, kubeadm
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
CentOS Stream release 9


</details>


### Install tools

<details>
kubeadm
</details>


### Container runtime (CRI) and version (if applicable)

<details>
CRI-o
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CALICO
</details>

**Comment by sftim** [comment]
/retitle  The management of HugePages memory in Kubernetes cannot be changed or deleted

**Comment by AdaephonBen** [comment]
Can I pick this up? @ndixita

**Comment by ndixita** [comment]
> Can I pick this up? @ndixita

please go for it

**Comment by seavershi** [comment]
No. The default policy of memory manager is "none".  Then when your application in the container tries to allocate huge pages memory, it will cause the application crash.  In current Kubernetes case, it requires the application must give request/limit hugepages number in yaml file.

**Comment by Tal-or** [comment]
@seavershi Have you tried to configure Kubelet topology manager policy (not memory manager policy) as `none`? (it should be the default, but maybe you've changed it) 
when topology manager is `none` it doesn't perform any NUMA topology alignment.
