### ISSUE TITLE
Dynamic Resource Allocation for Container Startup

### ISSUE THREAD

**Issue by saireddyb** [kubernetes/kubernetes#119894]
### What would you like to be added?

Background:
In certain scenarios, containers require a higher amount of CPU resources during their startup phase to accelerate application initialization. This is particularly useful for reducing startup times and ensuring fast application readiness. However, maintaining high resource allocation throughout the container's lifecycle might not be efficient, especially for business logic that can operate well with lower resource limits. This proposal aims to introduce a dynamic resource allocation mechanism specifically tailored for container startup.

Proposal:
Introduce a new feature in Kubernetes that allows users to define dynamic resource allocations for containers during their startup phase. This feature will enhance the existing resource specification by adding a separate configuration for startup resources. This will enable containers to utilize a higher amount of resources only during the initial startup, ensuring faster application initialization.

Specification:
The proposed configuration will be included in the container's resource specification as follows:
```
resources:
  startup:
    cpu: 4000m
    memory: 750Mi
  limits:
    cpu: 500m
    memory: 750Mi
  requests:
    cpu: 250m
    memory: 750Mi
```
In this configuration, the startup section defines the resource allocation that the container can use during its startup phase. Once the container becomes ready, it will switch to the resource limits specified in the limits section for ongoing operations.

Benefits:
Faster Application Startup: Containers can take advantage of higher resource allocations during startup, significantly reducing application initialization times.
Efficient Resource Utilization: After startup, containers will operate under specified limits, ensuring efficient utilization of resources during normal operations.
Simplified Configuration: The proposed approach keeps the configuration clear and distinct, allowing developers to fine-tune resource requirements based on startup needs and runtime demands.

Considerations:
Impact on Node Resources: The dynamic allocation approach should consider the potential impact on node resources, ensuring that other pods and applications are not adversely affected.
Implementation Complexity: The implementation will need to manage the transition from startup to regular operation, and ensure that the system gracefully handles changes in resource allocation.

Conclusion:
Introducing dynamic resource allocation for container startup in Kubernetes will address the specific requirement of providing higher resource limits during initialization while maintaining efficient resource utilization during normal operations. This enhancement will benefit applications that require fast startup times without compromising on runtime efficiency.

### Why is this needed?

Faster Application Startup: Containers can take advantage of higher resource allocations during startup, significantly reducing application initialization times.
Efficient Resource Utilization: After startup, containers will operate under specified limits, ensuring efficient utilization of resources during normal operations.
Simplified Configuration: The proposed approach keeps the configuration clear and distinct, allowing developers to fine-tune resource requirements based on startup needs and runtime demands.

**Comment by kannon92** [comment]
So this sounds a lot like https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/1287-in-place-update-pod-resources#summary

I believe this feature is alpha in 1.28.  You should play around with that feature and see if it solves your purpose.

**Comment by saireddyb** [comment]
Yes in place update will solve the problem by just only changing the limits after deployment but have a problem with it.
1: After every deployment need to update the resource limits (important).
2: After restart not possible to do. (important)
3: Managing different limits for a same microservice will be challenge with helm chart.

**Comment by michelefa1988** [comment]
Same here, some java require 2000 cpu requests during startup but then can use as little as 100 during normal operation. As you can see quite a massive discrepancy

**Comment by sm-xh** [comment]
got the same issue, any updates on this topic?

this would be nice feature, maybe it could be linked with initialDelaySeconds, which in my situation indicates time for application startup. im using java spring boot, so when app is starting it takes 400m of cpu, but after startup it is using like 1% of startup value

**Comment by kannon92** [comment]
I can see the usefulness in this but it is a hard ask... In place took a few years to design and has been worked on for multiple years. 

We are actively working on swap for this usecase especially for JVM based workloads. Some users have been experimenting with provisioning their nodes with swap and allowing for memory to be swapped to avoid pods being evicted during high memory usage espeically as we know that it will subside after startup.

I'd suggest looking at in-place or swap and see if those will fit your usecase for now.

**Comment by paulopacitti** [comment]
This is necessary also for loading ML models in Python, it takes a high CPU usage to load them, after that inference uses way less resources. Any updates here?

**Comment by saireddyb** [comment]
Guys looks like this is already available in GKE.
https://github.com/google/kube-startup-cpu-boost
