### ISSUE TITLE
Panic: client-go v0.26.0 - v0.26.3 in discovery against v1.27+ API Server

### ISSUE THREAD

**Issue by seans3** [kubernetes/kubernetes#119840]
### What happened?

* Clients using client-go v0.26.0 - v0.26.3 can panic under the following conditions
  * API Server v1.27+ *or* v1.26 and feature gate enabled `--feature-gates=AggregatedDiscoveryEndpoint=true`
  * Cluster contains aggregated api server for custom metrics (e.g. Prometheus) or any aggregated api server returning malformed discovery.

Fix: Update client-go to v0.26.4+
Installed Code Fix: https://github.com/kubernetes/kubernetes/pull/116603

Related Issue: https://github.com/kubernetes/kubernetes/issues/118361

Details:
* Aggregated Discovery was implemented as alpha in v1.26 [KEP]( https://github.com/kubernetes/enhancements/issues/3352).
* Some aggregated api servers return malformed discovery (e.g. custom metrics servers).
* In the affected client/server versions, the malformed discovery is propagated to the client causing a nil pointer exception.
* Stack trace looks like
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f97f90]

goroutine 1 [running]:
k8s.io/client-go/discovery.convertAPIResource(...)
        k8s.io/client-go@v0.26.0/discovery/aggregated_discovery.go:88
k8s.io/client-go/discovery.convertAPIGroup({{{0x0, 0x0}, {0x0, 0x0}}, {{0xc001668c48, 0x15}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.0/discovery/aggregated_discovery.go:69 +0x5f0
k8s.io/client-go/discovery.SplitGroupsAndResources({{{0xc0016680c0, 0x15}, {0xc0016b6540, 0x1b}}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...})
        k8s.io/client-go@v0.26.0/discovery/aggregated_discovery.go:35 +0x2f8
k8s.io/client-go/discovery.(*DiscoveryClient).downloadAPIs(0x4000105?)
        k8s.io/client-go@v0.26.0/discovery/discovery_client.go:310 +0x478
k8s.io/client-go/discovery.(*DiscoveryClient).GroupsAndMaybeResources(0x0?)
...
```

### What did you expect to happen?

* Expect not to panic

### How can we reproduce it (as minimally and precisely as possible)?

* `kubectl` version 1.26.0 - 1.26.3
* API Server version 1.27+
* Prometheus metrics installed

`$ kubectl api-versions`

### Kubernetes version

* Any client with client-go v0.26.0 - v0.26.3
* Paired with api server v1.27+
* Paired with aggregated api server with malformed discovery (e.g. custom metrics)

### Cloud provider

<details>
any
</details>

**Comment by liggitt** [comment]
> * any aggregated api server returning malformed discovery.

for subresources which don't accept/return Kubernetes API objects, it's actually correct to not return a kind, so I'm not sure I'd call that malformed

**Comment by seans3** [comment]
Istio client fixed: https://github.com/istio/istio/issues/46396

**Comment by lengrongfu** [comment]
Can you provide a pr for client-go fix？

**Comment by liggitt** [comment]
It was already fixed in 0.26.4+ in https://github.com/kubernetes/kubernetes/pull/116603

**Comment by liggitt** [comment]
@seans3, given the server-side mitigation getting backported to 1.26 and 1.27, we may want to hold off on encouraging client updates until we know the patch releases that will include https://github.com/kubernetes/kubernetes/pull/119835, and encourage folks to update to those instead, so they get the empty GVK filtering as well

**Comment by liggitt** [comment]
switching this from bug to cleanup since the bug is already fixed in k8s and this is tracking propagation effort

**Comment by jfgosselin** [comment]
Can you provide a new version of the Helm Operator with this fix ?

**Comment by liggitt** [comment]
no, the server-side mitigation in https://github.com/kubernetes/kubernetes/pull/119835 effectively resolved this, I think

/close
