### ISSUE TITLE
Bump github.com/emicklei/go-restful/v3 from version v3.9.0 to v3.10.0

### ISSUE THREAD

**Issue by Bjyothi2023** [kubernetes/kubernetes#119854]
### What happened?

An Security vulnerability "PRISMA-2022-0227" is reported during  an vulnerability scan which points to "github.com/emicklei/go-restful/v3" with version v3.9.0

Fix is available in v3.10.0

Need this packages to be upgrade to v3.10.0

### What did you expect to happen?

Resolving major security vulnerabilities

### How can we reproduce it (as minimally and precisely as possible)?

By running security scanners 

### Kubernetes version

<details>

```console
$ kubectl version
KUBERNETES_VERSION=v1.27.4
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexzielenski** [comment]
https://github.com/kubernetes/kubernetes/pull/119865 is still open to bump this dep
