### ISSUE TITLE
Propageted SIGTERM signals results in kill after 30 seconds although terminationGracePeriodSeconds is 120

### ISSUE THREAD

**Issue by gberth** [kubernetes/kubernetes#119884]
### What happened?

I have a pod with processes orchestrated from shell script (ubuntu). When SIGTERM is sent to the pod, SIGTERM is propageted to these processes. I find that these processes are killed after 30 seconds, although terminationGracePeriodSeconds is 120. The POD itself is killed after 120 seconds

### What did you expect to happen?

I was expecting nothing to be done until the 120 seconds were up, or the processes receiving SIGTERM were finished gracefully 

### How can we reproduce it (as minimally and precisely as possible)?

[dockertest.zip](https://github.com/kubernetes/kubernetes/files/12312426/dockertest.zip)

entrypoint in dockerfile:

ENTRYPOINT ["./src/sh/startup-dockertest.sh"]

### Kubernetes version

<details>

```console
$ kubectl version
1.26.5-gke.1400```

</details>


### Cloud provider

<details>
Google
</details>


### OS version

<details>
Container-Optimized OS from Google
</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
Container-Optimized OS from Google
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
are your processes handling the SIGTERM? your application should be handling the signal 

/sig node

**Comment by ndixita** [comment]
/triage needs-information

We would need podspec here to triage further to understand what's blocking the pod termination. SIGTERM is expected here.

**Comment by gberth** [comment]
There is nothing blocking pod termination. The problem is that kubernetes kills the internal processes doing controlled shutdown after having received SIGTERM (from the main shell) after 30 seconds, although the "terminationGracePeriodSeconds" is 120 seconds. The pod terminates after 120 seconds as expected but the internal processes are killed before.

**Comment by gberth** [comment]
Anything more I need to do?

**Comment by mmiranda96** [comment]
@gberth could you share a pod spec to understand a bit more your case? It would also help if you could share the kubelet logs when running this scenario.
