### ISSUE TITLE
Pods in ImagePullBackOff get stuck there, if image fails to pull for long enough

### ISSUE THREAD

**Issue by roy-work** [kubernetes/kubernetes#119891]
### What happened?

We have a pod that was stuck in ``/`ImagePullBackOff`: initially, this was caused by the pull secret not existing. Mea culpa.

We corrected that issue; however, by the time it was corrected, much time has passed (several hours) and even though the secret now exists, the image is still stuck; it spends most of its time in `ImagePullBackOff`, but occaisonally alternates to `ErrImagePull`.

The event logs only show:
```
Events:
  Type    Reason   Age                     From     Message
  ----    ------   ----                    ----     -------
  Normal  BackOff  4m55s (x5959 over 22h)  kubelet  Back-off pulling image "<the image>"
```

… but no attempts appear to be being made to actually pull the image, nor are there now any errors about *why* we're in backing off. We're backing off… but not actually doing anything?

The kubelet's logs seem to confirm this, containing only this error AFAICT:
```
1:23:18.001 PM | E0810 17:23:18.000705    1766 pod_workers.go:965] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"graphql-fhir-translator\" with ImagePullBackOff: \"Back-off pulling image \\\"<the image>\\\"\"" pod="<the NS>/<the pod>" podUID=1193f710-eeae-4761-84b6-176acbd97ea6
```
Again, AFAICT, no attempt to actually pull the image.

It took me cordoning all nodes, then re-creating the pod, to finally get this event:
```
  Warning  Failed     13s   kubelet            Failed to pull image "<the image>": json: cannot unmarshal string into Go struct field DockerConfigJSON.auths of type credentialprovider.dockerConfigEntryWithAuth
```
Which, okay, that's better! But this should have been present in the logs from the get-go.

### What did you expect to happen?

I expect the kubelet to keep attempting to pull the image, at whatever the maximum backoff delay interval is, since it has been several hours. (Or some randomized value between [0, that interval].) I expect retries. If something remains incorrect, it should get logged.

### How can we reproduce it (as minimally and precisely as possible)?

See "What happened?" — I think following those events (have a container in `ImagePullBackOff` for several hours, then fix the underlying issue) is sufficient.

### Kubernetes version

 1.24.13-gke.2500

### Cloud provider

<details>
GCP's GKE.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> 1.24.13-gke.2500

normally you should first ask for support at the managed solution (GKE), then if they think it's appropriate, they can log the upstream kubernetes ticket - i.e. in case there is a bug.

**Comment by ndixita** [comment]
/triage need-information
This needs more information. Please add steps to reproduce and check if this is reproducible in >= 1.25 versions.

**Comment by alculquicondor** [comment]
/wg batch

This is a very important problem when using queueing mechanisms. A user that submits a Job wouldn't know that the image is invalid until the job actually starts running. But it might be hours since the job submission when the job starts running. At that point, the job could block a good chunk of the cluster with no way of automatically freeing those resources.

**Comment by alculquicondor** [comment]
cc @kannon92 you thought about this problem before. Maybe it's time to pursue it.

**Comment by alculquicondor** [comment]
uhm..... I guess this bug report is asking specifically about:
- keep pulling
- give better error messages as to why it's failing

Let's split the Failing into a separate issue.

/remove-wg batch

**Comment by kannon92** [comment]
> cc @kannon92 you thought about this problem before. Maybe it's time to pursue it.

Yes, this was the crux of https://github.com/kubernetes/enhancements/pull/3816. If anyone wants to pick that up, please feel free. I don't think I will have the bandwidth to lead that anytime soon.

I decided to focus on `PodReadyToStartContainers` as this was already an existing feature. This feature was for issues in pod sandbox creation. This was promoted to beta in 1.29 so this will at least display a condition for sandbox issues.

My 2c on this is that there are two lifecycle issues that are not well covered by pod conditions/errors: image issues and pod lifecycle (ie pod hooks or config setup).

If you have any issues in image pull (validation, secrets, etc), then we hit an issue and it goes into `ImagePullBackOff`. That PR I linked was mostly about adding conditions for these cases.

So what I have thought is that maybe there is a need for two conditions (image lifecycle and pod lifecycle). I don't know if I should consider separating that KEP into two different ones per conditions.

**Comment by alculquicondor** [comment]
Let's move that conversation to #122300
