### ISSUE TITLE
Advice on Accessing the Kubernetes API from a Pod

### ISSUE THREAD

**Issue by rgupta6** [kubernetes/kubernetes#119940]
Hello,

I am trying to access to Kubernetes API from a Pod using Java Client library. I have followed in cluster config example from below URL:
https://github.com/kubernetes-client/java/blob/master/examples/examples-release-18/src/main/java/io/kubernetes/client/examples/InClusterClientExample.java

I am able to run it successfully locally but when I deploy it in GCP Kubernetes, and trying to invoke the service from within a pod, it is not working and giving below error:
org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver [http-nio-8080-exec-1] Resolved [java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt

I tried to find locate the certificate in '/var/run/secrets/kubernetes.io/serviceaccount' path within pod, but it's not available and that is why I am getting this error.

Could you please help to understand what is wrong with that.

**Comment by sftim** [comment]
@rgupta6: GitHub is (still) not the right place for support requests.

For further help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes).

You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
