### ISSUE TITLE
kubeadm init fail

### ISSUE THREAD

**Issue by zhaoxueye** [kubernetes/kubernetes#119935]
### Which jobs are failing?

kubeadm init 

### Which tests are failing?

kubeadm init 

### Since when has it been failing?

Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s

### Reason for failure (if possible)

kube-apiserver is not running, 6443 is not listening.

### Anything else we need to know?

commands:
sudo kubeadm reset -f && sudo kubeadm init --v=100 --image-repository=registry.aliyuncs.com/google_containers --kubernetes-version="1.28.0-rc.0"

logs:
[kubelet-start] Starting the kubelet
I0814 16:32:39.184462 3488038 waitcontrolplane.go:83] [wait-control-plane] Waiting for the API server to be healthy
I0814 16:32:39.186022 3488038 loader.go:395] Config loaded from file:  /etc/kubernetes/admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
I0814 16:32:39.188712 3488038 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.28.0 (linux/amd64) kubernetes/4571067" 'https://192.168.0.106:6443/healthz?timeout=10s'
I0814 16:32:39.189283 3488038 round_trippers.go:508] HTTP Trace: Dial to tcp:192.168.0.106:6443 failed: dial tcp 192.168.0.106:6443: connect: connection refused
I0814 16:32:39.189490 3488038 round_trippers.go:553] GET https://192.168.0.106:6443/healthz?timeout=10s  in 0 milliseconds
I0814 16:32:39.189581 3488038 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 0 ms Duration 0 ms
I0814 16:32:39.189644 3488038 round_trippers.go:577] Response Headers:
I0814 16:32:39.690839 3488038 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.28.0 (linux/amd64) kubernetes/4571067" 'https://192.168.0.106:6443/healthz?timeout=10s'
I0814 16:32:39.691365 3488038 round_trippers.go:508] HTTP Trace: Dial to tcp:192.168.0.106:6443 failed: dial tcp 192.168.0.106:6443: connect: connection refused
I0814 16:32:39.691459 3488038 round_trippers.go:553] GET https://192.168.0.106:6443/healthz?timeout=10s  in 0 milliseconds
I0814 16:32:39.691506 3488038 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 0 ms Duration 0 ms
I0814 16:32:39.691529 3488038 round_trippers.go:577] Response Headers:
I0814 16:32:40.191154 3488038 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.28.0 (linux/amd64) kubernetes/4571067" 'https://192.168.0.106:6443/healthz?timeout=10s'
I0814 16:32:40.191843 3488038 round_trippers.go:508] HTTP Trace: Dial to tcp:192.168.0.106:6443 failed: dial tcp 192.168.0.106:6443: connect: connection refused
I0814 16:32:40.191953 3488038 round_trippers.go:553] GET https://192.168.0.106:6443/healthz?timeout=10s  in 0 milliseconds
I0814 16:32:40.191986 3488038 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 0 ms Duration 0 ms
I0814 16:32:40.192018 3488038 round_trippers.go:577] Response Headers:
I0814 16:32:40.690705 3488038 round_trippers.go:466] curl -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubeadm/v1.28.0 (linux/amd64) kubernetes/4571067" 'https://192.168.0.106:6443/healthz?timeout=10s'
I0814 16:32:40.691135 3488038 round_trippers.go:508] HTTP Trace: Dial to tcp:192.168.0.106:6443 failed: dial tcp 192.168.0.106:6443: connect: connection refused
I0814 16:32:40.691275 3488038 round_trippers.go:553] GET https://192.168.0.106:6443/healthz?timeout=10s  in 0 milliseconds
I0814 16:32:40.691552 3488038 round_trippers.go:570] HTTP Statistics: DNSLookup 0 ms Dial 0 ms TLSHandshake 0 ms Duration 0 ms
I0814 16:32:40.691570 3488038 round_trippers.go:577] Response Headers:

**Comment by liangyuanpeng** [comment]
All version is failed or just v1.28.0-rc.0?

**Comment by zhaoxueye** [comment]
> All version is failed or just v1.28.0-rc.0?
I only tested v1.28.0-rc.0

**Comment by liangyuanpeng** [comment]
I have build the image of kind with kubernetes 1.28.0-rc.0 and it's working for me.

```shell
kind create cluster --image ghcr.io/liangyuanpeng/kindest/node:v0.20.0-v1.28.0-rc.0
```

It's run wirh kubeadm. I'm curious about your other information,like:

- kubelet log
- what's version of kubeadm
- what's cri

**Comment by zhaoxueye** [comment]
> 

### kubelet log
Aug 14 18:33:43 zxy-virtual-machine systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Aug 14 18:33:43 zxy-virtual-machine systemd[1]: kubelet.service: Deactivated successfully.
Aug 14 18:33:43 zxy-virtual-machine systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 14 18:33:43 zxy-virtual-machine systemd[1]: kubelet.service: Consumed 3.297s CPU time.
Aug 14 18:33:49 zxy-virtual-machine systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.533953 3493230 server.go:467] "Kubelet version" kubeletVersion="v1.28.0-rc.0"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.534230 3493230 server.go:469] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.534745 3493230 server.go:630] "Standalone mode, no API client"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.553094 3493230 server.go:518] "No api server defined - no events will be sent to API server"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.553786 3493230 server.go:725] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.555677 3493230 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.557518 3493230 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"cgroupfs","KubeletRootDir":"/var/lib/kubelet","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","TopologyManagerPolicyOptions":null}
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.557626 3493230 topology_manager.go:138] "Creating topology manager with none policy"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.557646 3493230 container_manager_linux.go:301] "Creating device plugin manager"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.557782 3493230 state_mem.go:36] "Initialized new in-memory state store"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.557889 3493230 kubelet.go:399] "Kubelet is running in standalone mode, will skip API server sync"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.559721 3493230 kuberuntime_manager.go:257] "Container runtime initialized" containerRuntime="containerd" version="1.6.12-0ubuntu1~22.04.3" apiVersion="v1"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.560652 3493230 volume_host.go:74] "KubeClient is nil. Skip initialization of CSIDriverLister"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: W0814 18:33:50.560988 3493230 csi_plugin.go:189] kubernetes.io/csi: kubeclient not set, assuming standalone kubelet
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: W0814 18:33:50.561422 3493230 csi_plugin.go:266] Skipping CSINode initialization, kubelet running in standalone mode
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.562454 3493230 server.go:1232] "Started kubelet"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.563159 3493230 kubelet.go:1579] "No API server defined - no node status update will be sent"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.566486 3493230 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.567004 3493230 server.go:162] "Starting to listen" address="0.0.0.0" port=10250
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.569109 3493230 volume_manager.go:291] "Starting Kubelet Volume Manager"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.569277 3493230 server.go:462] "Adding debug handlers to kubelet server"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.567155 3493230 ratelimit.go:65] "Setting rate limiting for podresources endpoint" qps=100 burstTokens=10
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.574944 3493230 server.go:233] "Starting to serve the podresources API" endpoint="unix:/var/lib/kubelet/pod-resources/kubelet.sock"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: E0814 18:33:50.569573 3493230 cri_stats_provider.go:448] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: E0814 18:33:50.576624 3493230 kubelet.go:1431] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.567035 3493230 server.go:194] "Starting to listen read-only" address="0.0.0.0" port=10255
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.569914 3493230 desired_state_of_world_populator.go:151] "Desired state populator starts to run"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.570702 3493230 reconciler_new.go:29] "Reconciler: start to sync state"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.613596 3493230 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv4"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.620924 3493230 kubelet_network_linux.go:50] "Initialized iptables rules." protocol="IPv6"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.621705 3493230 status_manager.go:213] "Kubernetes client is nil, not starting status manager"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.622375 3493230 kubelet.go:2303] "Starting kubelet main sync loop"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: E0814 18:33:50.623737 3493230 kubelet.go:2327] "Skipping pod synchronization" err="[container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.664478 3493230 cpu_manager.go:214] "Starting CPU manager" policy="none"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.664589 3493230 cpu_manager.go:215] "Reconciling" reconcilePeriod="10s"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.664621 3493230 state_mem.go:36] "Initialized new in-memory state store"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.666444 3493230 policy_none.go:49] "None policy: Start"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.669409 3493230 memory_manager.go:169] "Starting memorymanager" policy="None"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.670132 3493230 state_mem.go:35] "Initializing new in-memory state store"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.674393 3493230 manager.go:471] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.676002 3493230 plugin_manager.go:118] "Starting Kubelet Plugin Manager"
Aug 14 18:33:50 zxy-virtual-machine kubelet[3493230]: I0814 18:33:50.681451 3493230 desired_state_of_world_populator.go:159] "Finished populating initial desired state of world"
### kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.0-rc.0", GitCommit:"45710678b3052440fa2d18f2c22f687565632d88", GitTreeState:"archive", BuildDate:"2023-08-07T07:00:06Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
### OS
Linux zxy-virtual-machine 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zhaoxueye** [comment]
[-]poststarthook/rbac/bootstrap-roles failed: reason withheld
