### ISSUE TITLE
helm-operation failure - Waiting for Kubernetes API to be available with mass deployment (130+ apps)

### ISSUE THREAD

**Issue by vynguyenchantal** [kubernetes/kubernetes#119980]
### What happened?

See https://github.com/rancher/rancher/issues/42440

### What did you expect to happen?

See https://github.com/rancher/rancher/issues/42440

### How can we reproduce it (as minimally and precisely as possible)?

See https://github.com/rancher/rancher/issues/42440

### Kubernetes version

See https://github.com/rancher/rancher/issues/42440

### Cloud provider

See https://github.com/rancher/rancher/issues/42440

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> Kubernetes version: v1.23.10

< 1.24 is out of support, so core k8s cannot backport fixes for this version.

please contact rancher / helm
if the maintainers of those project confirm this is a core k8s bug, repen the issue.
this doesn't sound like a core k8s bug.

/close
/sig apps
