### ISSUE TITLE
kubectl: no way to list events about a specific object

### ISSUE THREAD

**Issue by jbeda** [kubernetes/kubernetes#11994]
There is no way, with kubectl, to find all the events about an object.  If the object still exists, you can use the "describe" command on it and that will list the relevant events.  But if the object doesn't still exist, the only way to get this data is via `kubectl get ev` and wade through lots of noise.

**Comment by xiejunan** [comment]
@hurf  SQL like query .

**Comment by erictune** [comment]
Will jsonpath templates help?

**Comment by kargakis** [comment]
cc: @kubernetes/kubectl 

This would be a nice-to-have

**Comment by AdoHe** [comment]
sounds reasonable to me.

**Comment by jwforres** [comment]
in the openshift console we let you filter the events table on name, kind, reason, and message but these are partial match as-you-type filters.  I think for the CLI the ones that make sense are filter for a particular kind, object, or Reason.

**Comment by janetkuo** [comment]
+1

**Comment by josephjacks** [comment]
is https://github.com/kubernetes/kubernetes/issues/36304 related to this?

**Comment by Ian-Rossi-aimtheory** [comment]
I could really use this to get pod event data in JSON format.

**Comment by timoreimann** [comment]
I still find this very desirable to have.

/remove-lifecycle stale

**Comment by liggitt** [comment]
--field-selector can be used to filter events to a particular object as of 1.9

**Comment by tammersaleh** [comment]
For those coming across this issue, and struggling to find the right field selector (I kept trying `metadata.name`), the incantation is:

``` console
$ kubectl get event --field-selector=involvedObject.name=foo
```
