### ISSUE TITLE
k8s三主两从 master1访问svc不通   ping  pod的ip也不通

### ISSUE THREAD

**Issue by shuangshuangaini** [kubernetes/kubernetes#119922]
### What happened?

 master1访问svc不通   ping  pod的ip也不通，通过master2和master3访问svc通   ping  pod 也是通的

### What did you expect to happen?

请大佬解决

### How can we reproduce it (as minimally and precisely as possible)?

请大佬解决

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sftim** [comment]
Please use English to report the bug. We use English to collaborate.

**Comment by thockin** [comment]
Given that almost all of the requested details are missing, there's nothing we can do here.  Please re-open with enough information to explain the problem.
