### ISSUE TITLE
Default topologySpreadConstraints are not working for StatefulSet pods

### ISSUE THREAD

**Issue by amnk** [kubernetes/kubernetes#119900]
### What happened?

I am running Kubernetes 1.21. I understand that it is fairly old, but topologySpreadConstraints are supposed to cover this.

I am running kube-scheduler with this configuration:
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
clientConnection:
  kubeconfig: /etc/kubernetes/ssl/kubecfg-kube-scheduler.yaml
profiles:
  - schedulerName: default-scheduler
    plugins:
      score:
        disabled:
          - name: SelectorSpread
    pluginConfig:
      - name: PodTopologySpread
        args:
          defaultConstraints:
            - maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: ScheduleAnyway
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
          defaultingType: List
```

And I have two zones `az1` and `az2` for label `topology.kubernetes.io/zone`. 

Above configuration works fine for any pods from Deployment controller - they are scheduler as I expect. But pods from StatefulSet object seem to be completely ignored. When I run kube-scheduler with v=10, I see that resulting score from PodTopologySpread plugin is the same:
```
xxxe-3" plugin="PodTopologySpread" node="node-101" score=200
I0810 10:06:24.276232       1 generic_scheduler.go:441] "Plugin scored node for pod" pod="xxx-3" plugin="PodTopologySpread" node="node-001" score=200
I0810 10:06:24.276285       1 generic_scheduler.go:441] "Plugin scored node for pod" pod="xxx-3" plugin="PodTopologySpread" node="node-102" score=200
I0810 10:06:24.276397       1 generic_scheduler.go:441] "Plugin scored node for pod" pod="xxx-3" plugin="PodTopologySpread" node="node-103" score=200
I0810 10:06:24.276465       1 generic_scheduler.go:441] "Plugin scored node for pod" pod="xxx-3" plugin="PodTopologySpread" node="node-002" score=200
I0810 10:06:24.276524       1 generic_scheduler.go:441] "Plugin scored node for pod" pod="xxx-3" plugin="PodTopologySpread" node="node-003" score=200
```

If I put spreads in the podspec directly everything works as expected.

### What did you expect to happen?

I expect default PodTopologySpreads to work equally for Deployment and StatefulSet objects

### How can we reproduce it (as minimally and precisely as possible)?

Not sure to be honest. I tried putting as mush details as possible, hoping that someone can point me to upstream bug (if any). I googled everything I can related to this topic

### Kubernetes version

1.21

```console
$ kubectl version
❯ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:40:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

on-premise installation

**Comment by kerthcet** [comment]
kubernetes 1.21 is out of support from the community, can you try with the 1.26 at least? We patched a lot since 1.21 ...

One thing to mention here is when rolling update, the topology spread is not respected because terminating pods are also taken into consideration in 1.21.
