### ISSUE TITLE
applying a manifest with a null label TWICE results in different behaviour each time

### ISSUE THREAD

**Issue by rsalmond** [kubernetes/kubernetes#119954]
### What happened?

@rdoherty-fastly and I were testing with this manifest:

``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: colorful
  labels:
    foo: bar
    baz:
spec:
  containers:
  - image: superorbital/color
    name: colorful
```

Result of **first** apply:

``` console
$ k apply -f pod.yaml
pod/colorful created

$ k get po colorful -ojson | jq '.metadata.labels'
{
  "baz": "",
  "foo": "bar"
}
```

Result of second apply (note `configured`):

``` console
$ k apply -f pod.yaml
pod/colorful configured

$ k get po colorful -ojson | jq '.metadata.labels'
{
  "foo": "bar"
}
```

### What did you expect to happen?

Applying the same manifest twice results in the same document being persisted twice.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:20:07Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4-gke.900", GitCommit:"a4ffa424df82619610058e9f9a93737eb64400be", GitTreeState:"clean", BuildDate:"2023-08-01T09:27:12Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
GKE
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Linux 0 5.15.0-1037-gcp #45~20.04.1-Ubuntu SMP Thu Jun 22 08:31:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
Based on the comments in the [mergeMap](https://github.com/kubernetes/kubernetes/blob/63351cce1c1099c64c6c55d540b1e65e947632ad/staging/src/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go#L1360-L1365), this seems to be the expected result

@apelisse I'm not sure if this is a bug or not, but it does cause our results to be inconsistent between the twice apply, was that a conscious decision?

**Comment by apelisse** [comment]
I would think it was not. Most things in strategic-merge-patch were not conscious decision. I'll take a quick look.

**Comment by rsalmond** [comment]
> What happens if you SMP with null again?

Just tried it 3x, you're correct, the result stays the same.

``` console
$ k get po colorful -ojson | jq '.metadata.labels'
{
  "foo": "bar"
}
```

**Comment by rsalmond** [comment]
Interestingly, it says "configured" _every_ time.

``` console
$ k apply -f pod.yaml
pod/colorful configured

$ k apply -f pod.yaml
pod/colorful configured

$ k apply -f pod.yaml
pod/colorful configured
```

**Comment by apelisse** [comment]
> Interestingly, it says "configured" every time.

Yeah, unsurprising to me. To kubectl, it looks like something needs to happen (it needs to send `baz: null`) and the "configured" logic is basically that simple (and inaccurate).

I'm sorry but I don't think there's a bug worth fixing here :-(
/close
