### ISSUE TITLE
status.reason and status.message can be copied between different pod phases by kubelet

### ISSUE THREAD

**Issue by mlowery** [kubernetes/kubernetes#119956]
### What happened?

In Kubernetes v1.18, we added a custom kubelet soft admit handler. It returns failure until some condition is met. Once the condition is met, it returns success. When upgrading to Kubernetes v1.23.6, the failure reason and message returned from this soft admit handler seem to jump between pod phases (i.e. the transition from `Pending` to `Running`), despite the soft admit handler subsequently returning success.

I suspect this behavior was introduced in https://github.com/kubernetes/kubernetes/pull/103785. I added some logging as follows to `pkg/kubelet/kubelet_pods.go` (`generateAPIPodStatus`):

```golang
	if s.Phase == oldPodStatus.Phase {
		klog.V(3).InfoS("mlowery: pod phases match", "pod", klog.KObj(pod), "s.Phase", s.Phase, "oldPodStatus.Phase", oldPodStatus.Phase)
		// preserve the reason and message which is associated with the phase
		s.Reason = oldPodStatus.Reason
		s.Message = oldPodStatus.Message
		if len(s.Reason) == 0 {
			klog.V(3).InfoS("mlowery: oldPodStatus.Reason is empty; using pod.Status.Reason", "pod", klog.KObj(pod), "pod.Status.Reason", pod.Status.Reason, "pod.Status.Phase", pod.Status.Phase)
			s.Reason = pod.Status.Reason
		}
		if len(s.Message) == 0 {
			klog.V(3).InfoS("mlowery: oldPodStatus.Message is empty; using pod.Status.Message", "pod", klog.KObj(pod), "pod.Status.Message", pod.Status.Message, "pod.Status.Phase", pod.Status.Phase)
			s.Message = pod.Status.Message
		}
	} else {
		klog.V(3).InfoS("mlowery: pod phases do not match", "pod", klog.KObj(pod), "s.Phase", s.Phase, "oldPodStatus.Phase", oldPodStatus.Phase)
	}
	klog.V(3).InfoS("mlowery: using reason and message", "pod", klog.KObj(pod), "s.Reason", s.Reason, "s.Message", s.Message)
```

With these log lines, I can produce the following sequence:

```
Aug 15 17:38:28 node-z6wrm kubelet[10380]: I0815 17:38:28.548196  10380 kubelet_pods.go:1489] "mlowery: pod phases match" pod="kube-system/test-13" s.Phase=Running oldPodStatus.Phase=Running
Aug 15 17:38:28 node-z6wrm kubelet[10380]: I0815 17:38:28.548213  10380 kubelet_pods.go:1494] "mlowery: oldPodStatus.Reason is empty; using pod.Status.Reason" pod="kube-system/test-13" pod.Status.Reason="Reason1" pod.Status.Phase=Pending
Aug 15 17:38:28 node-z6wrm kubelet[10380]: I0815 17:38:28.548231  10380 kubelet_pods.go:1498] "mlowery: oldPodStatus.Message is empty; using pod.Status.Message" pod="kube-system/test-13" pod.Status.Message="message1" pod.Status.Phase=Pending
Aug 15 17:38:28 node-z6wrm kubelet[10380]: I0815 17:38:28.548244  10380 kubelet_pods.go:1504] "mlowery: using reason and message" pod="kube-system/test-13" s.Reason="Reason1" s.Message="message1"
```

Notice the calculated phase (`s.Phase`) is `Running`, as is the previous status manager phase (`oldPodStatus.Phase`). `oldPodStatus.Reason` is empty (since the soft admit handler returned success) so it uses `pod.Status.Reason`. But the `pod.Status.Phase` is `Pending` and not `Running`.

The user-facing behavior looks like kubectl watch below. It starts as `STATUS=Blocked` since the soft admit handler returns failure. Then the soft admit handler returns success and so it moves to `STATUS=Running`, but only briefly. Then it moves to `STATUS=Reason1`.

```
$ kubectl -n kube-system get po test-13 -w
NAME      READY   STATUS    RESTARTS   AGE
test-13   0/1     Blocked   0          15s
test-13   1/1     Running   0          115s
test-13   1/1     Reason1   0          117s
```

### What did you expect to happen?

I believe the point of https://github.com/kubernetes/kubernetes/pull/103785 is to preserve reason and message, provided the phase is unchanged. But here, the phase changes from `Pending` to `Running` and the reason and message are mistakenly copied over.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create and register a soft admit handler.
2. Return failure with non-empty reason and message at least once then return success.

### Anything else we need to know?

I assume the fix is to only fall back to the `pod.Status.Reason` (and `pod.Status.Message`) if the `pod.Status.Phase` matches the newly calculated `s.Phase`.

### Kubernetes version

1.23.6

### Cloud provider

N/A

**Comment by ndixita** [comment]
/triage needs-information

Is this reproducible in >= 1.25 versions?

**Comment by mlowery** [comment]
> Is this reproducible in >= 1.25 versions?

I do not know. But checking the latest [code](https://github.com/kubernetes/kubernetes/blob/18290bfdc8fbe12921c7558c2fab1bb1447d07b5/pkg/kubelet/kubelet_pods.go#L1683-L1693) (the code I added logging to) shows it to be unchanged.

> And what does soft admit handler do? Could you please link to the doc?

I don't believe there is user-facing doc. It's a mechanism to stall or indefinitely delay the running of pods already scheduled and admitted to the node. Function `canRunPod`, which runs on every `syncPod` call, consults the soft admit handlers.

**Comment by pacoxu** [comment]
> I suspect this behavior was introduced in #103785. I added some logging as follows to `pkg/kubelet/kubelet_pods.go` (`generateAPIPodStatus`):

/cc @smarterclayton
