### ISSUE TITLE
Mount point may become local without calling `NodePublishVolume` after node rebooting 

### ISSUE THREAD

**Issue by cvvz** [kubernetes/kubernetes#119921]
### What happened?

This issue is very similar to https://github.com/kubernetes/kubernetes/issues/117513, they have the same symptom: remote volumes of the pods are becoming local mount point after rebooting the Node. And this issue is triggered by https://github.com/kubernetes/kubernetes/issues/117513.

The difference is that in https://github.com/kubernetes/kubernetes/issues/117513, kubelet didn't call `NodeStageVolume`, so the global mount point is local, but it will still call `NodePublishVolume` for the pod to bind mount the pod volume to the global mount point. Whereas in this issue, kubelet neither call `NodeStageVolume` globally nor call `NodePublishVolume` for the pod. 

This is more harmful: After writing some data to the pod volume, pod can't be deleted because kubelet encounter `directory not empty` error while unmounting the pod volume:
 
![image](https://github.com/kubernetes/kubernetes/assets/44308864/b1cc4e04-15ac-4730-a862-54eddf2a4960)

Reproduce steps:
1. Create a cluster with one Node
2. Create a deployment with **two replicas**(say `pod-1` and `pod-2`) using Non-attachable volume (for example Azurefile)
3. Shutdown the Node
4. Delete `pod-1` with option `--force` (Use force deletion to simulate the situation that mount point was left over before rebooting the Node.)
5. Bring back the Node
6. `pod-2` is always in Running state, however, after rebooting, it won't call `NodePublishVolume` and the volume it uses is local volume.

### What did you expect to happen?

`pod-2` should call `NodePublishVolume`.

### How can we reproduce it (as minimally and precisely as possible)?

As mentioned above.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-19T16:10:31Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cvvz** [comment]
Clusters with `NewVolumeManagerReconstruction` enabled is not impated.

**Comment by neolit123** [comment]
/sig node storage
(for triage)

**Comment by ndixita** [comment]
/remove-sig node

sig-storage please triage this first. Thanks
