### ISSUE TITLE
Kubelet.service failing to start in ubuntu 22.04

### ISSUE THREAD

**Issue by brf153** [kubernetes/kubernetes#119901]
### What happened?

Hello everyone,
I have installed the Kubernetes components in my system using the command `sudo apt install -y kubelet kubeadm kubectl` and then when I check the status of kubelet using the command `sudo systemctl status kubelet.service` , I get 
```
 kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor prese>
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-08-11>
       Docs: https://kubernetes.io/docs/home/
    Process: 804917 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELE>
   Main PID: 804917 (code=exited, status=1/FAILURE)
        CPU: 75ms
```
then I tried checking the error logs by using the command `journalctl -u kubelet.service --since "1 hour ago" -xn --no-pager` , it shows me `error: open /var/lib/kubelet/config.yaml: no such file or directory`  . I actually have a config.yaml file in my /var/lib/kubelet directory. I don't know why kubelet service is not being able to read the config file. I had conversation in the kubernetes slack group as well. You can check it [here](https://kubernetes.slack.com/archives/C09NXKJKA/p1691681430371399). Please help.

### What did you expect to happen?

I expected kubelet.service to start.

### How can we reproduce it (as minimally and precisely as possible)?

Just install the latest version of kubelet (Kubernetes v1.27.4).

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
/remove-kind bug
/kind support
/sig cluster-lifecycle 

I would check first that you are correctly following the instructions to create the cluster
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/

**Comment by brf153** [comment]
@aojea I am running the command `sudo kubeadm init` . Initially it shows that the port 10250 is already in use. Now, when I do `sudo lsof -i :10250` it shows me:-
```
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
kubelet 717241 root   15u  IPv6 2492426      0t0  TCP *:10250 (LISTEN)
```

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
