### ISSUE TITLE
Kubernetes Docker Config Json Globbing Not As Documented

### ISSUE THREAD

**Issue by njgibbon** [kubernetes/kubernetes#119941]
### What happened?
K8s Docker config json globbing is not as documented for subdomain wildcarding.
* https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/keyring.go

### Impact
The user impact is that people create `imagePullSecrets` and corresponding configuration to use private registries and the credentials do not get used leading to `4xx` with the registry, image pull errors and some confusion. 

### What did you expect to happen?

Docs indicate that host glob `*my-registry.io` would work to be used as auth for e.g
```
foo.my-registry.io
foo.bar.my-registry.io
```
* https://kubernetes.io/docs/concepts/containers/images/#config-json
* https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/containers/images.md

### How can we reproduce it (as minimally and precisely as possible)?

Run package unit tests with the following cases added to `TestURLsMatch`:
```
		{
			globURL:       "*kubernetes.io",
			targetURL:     "foo.kubernetes.io",
			matchExpected: true,
		},
		{
			globURL:       "*kubernetes.io",
			targetURL:     "foo.bar.kubernetes.io",
			matchExpected: true,
		},
```
* https://github.com/kubernetes/kubernetes/blob/master/pkg/credentialprovider/keyring_test.go
### Anything else we need to know?

Either docs or logic should be adjusted.

### Kubernetes version

<details>

```console
All supported.
```

</details>

### Cloud provider

<details>
All.
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by saschagrunert** [comment]
I think it should be updated in the docs, that:

- Only one subdomain depth is supported
- The glob requires the dot separator

Anything else?

**Comment by njgibbon** [comment]
@saschagrunert  - I think you can have multiple subdomains as long as you have a corresponding number of dots in your glob pattern. I think the core diff between the docs interpretation and the actual implementation is the dots.

**Comment by saschagrunert** [comment]
Yeah those are the tests for that: 

https://github.com/kubernetes/kubernetes/blob/6e0cb243d57592c917fe449dde20b0e246bc66be/pkg/credentialprovider/keyring_test.go#L75-L90
