### ISSUE TITLE
sched framework: expose NodeInfo in all functions of PluginsRunner interface

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes/kubernetes#119987]
### What would you like to be added?

Scheduler framework exposes a series of functions in PluginsRunner interface for out-of-tree plugins to implement custom functionalities:

https://github.com/kubernetes/kubernetes/blob/6f8d38406a7f16fc9cc9b72789a9b826105b1b54/pkg/scheduler/framework/interface.go#L601-L605

https://github.com/kubernetes/kubernetes/blob/6f8d38406a7f16fc9cc9b72789a9b826105b1b54/pkg/scheduler/framework/interface.go#L725-L750

However, `RunPreScorePlugins` and `RunScorePlugins` exposes `Node` instead of `NodeInfo` like other functions. It causes inconvenient UX for plugin users like [koordinator](https://github.com/koordinator-sh/koordinator). For example, one of the requirements is to find an optimal preemption candidate node in PostFilter plugins. `NodeInfo` carries important extra info during the preemption dryrun, and w/o consuming `NodeInfo`, running `Run{Pre}ScorePlugins` would be non-sense. To work around it, users have to plumb very specific and sometime ugly semantics themselves which should have been avoided.

### Why is this needed?

- consistent function signature - all use NodeInfo
- unleash more potential to use scheduler framework natively w/o hacks

**Comment by wackxu** [comment]
I want to help fix this.
/assign

**Comment by Huang-Wei** [comment]
A reminder is pkg/scheduler/framework/autoscaler_contract, which we should involve cluster-autoscaler folks for interface changes that may impact their workflow. For this flow, it doesn't seem to be breaking as it involves PreFilter/Filter only.

But still @kubernetes/sig-autoscaling-misc

**Comment by wackxu** [comment]
> /assign

@lowang-bh I'm already working on this problem，You can take a look at other issues to reduce unnecessary duplication of work

**Comment by Huang-Wei** [comment]
@lowang-bh please note that @wackxu already self-assigned this. Could you negociate with @wackxu ?

**Comment by wackxu** [comment]
@Huang-Wei I have some questions about this.

```
// PluginsRunner abstracts operations to run some plugins.
// This is used by preemption PostFilter plugins when evaluating the feasibility of
// scheduling the pod on nodes when certain running pods get evicted.
type PluginsRunner interface {
	// RunPreScorePlugins runs the set of configured PreScore plugins. If any
	// of these plugins returns any status other than "Success", the given pod is rejected.
	RunPreScorePlugins(context.Context, *CycleState, *v1.Pod, []*v1.Node) *Status
	// RunScorePlugins runs the set of configured scoring plugins.
	// It returns a list that stores scores from each plugin and total score for each Node.
	// It also returns *Status, which is set to non-success if any of the plugins returns
	// a non-success status.
	RunScorePlugins(context.Context, *CycleState, *v1.Pod, []*v1.Node) ([]NodePluginScores, *Status)
	// RunFilterPlugins runs the set of configured Filter plugins for pod on
	// the given node. Note that for the node being evaluated, the passed nodeInfo
	// reference could be different from the one in NodeInfoSnapshot map (e.g., pods
	// considered to be running on the node could be different). For example, during
	// preemption, we may pass a copy of the original nodeInfo object that has some pods
	// removed from it to evaluate the possibility of preempting them to
	// schedule the target pod.
	RunFilterPlugins(context.Context, *CycleState, *v1.Pod, *NodeInfo) *Status
	// RunPreFilterExtensionAddPod calls the AddPod interface for the set of configured
	// PreFilter plugins. It returns directly if any of the plugins return any
	// status other than Success.
	RunPreFilterExtensionAddPod(ctx context.Context, state *CycleState, podToSchedule *v1.Pod, podInfoToAdd *PodInfo, nodeInfo *NodeInfo) *Status
	// RunPreFilterExtensionRemovePod calls the RemovePod interface for the set of configured
	// PreFilter plugins. It returns directly if any of the plugins return any
	// status other than Success.
	RunPreFilterExtensionRemovePod(ctx context.Context, state *CycleState, podToSchedule *v1.Pod, podInfoToRemove *PodInfo, nodeInfo *NodeInfo) *Status
}
```
According to PluginsRunner comments and my understanding，It is usually called by in-tree or out-of-tree plugins to implement some functionalities, such as preemption or customer-defined functions.  

The specific usage process is usually that users develop their own custom `PreScorePlugin` and `ScorePlugin`, and then call `RunPreScorePlugins` and `RunScorePlugins` . 

```
// PreScorePlugin is an interface for "PreScore" plugin. PreScore is an
// informational extension point. Plugins will be called with a list of nodes
// that passed the filtering phase. A plugin may use this data to update internal
// state or to generate logs/metrics.
type PreScorePlugin interface {
	Plugin
	// PreScore is called by the scheduling framework after a list of nodes
	// passed the filtering phase. All prescore plugins must return success or
	// the pod will be rejected
	// When it returns Skip status, other fields in status are just ignored,
	// and coupled Score plugin will be skipped in this scheduling cycle.
	PreScore(ctx context.Context, state *CycleState, pod *v1.Pod, nodes []*v1.Node) *Status
}

// ScorePlugin is an interface that must be implemented by "Score" plugins to rank
// nodes that passed the filtering phase.
type ScorePlugin interface {
	Plugin
	// Score is called on each filtered node. It must return success and an integer
	// indicating the rank of the node. All scoring plugins must return success or
	// the pod will be rejected.
	Score(ctx context.Context, state *CycleState, p *v1.Pod, nodeName string) (int64, *Status)

	// ScoreExtensions returns a ScoreExtensions interface if it implements one, or nil if does not.
	ScoreExtensions() ScoreExtensions
}
```

So If we update `RunPreScorePlugins` and `RunScorePlugins` to  exposes NodeInfo, We should also update the plugin interface definition, such as `PreScorePlugin` . 

Another question is that in the plugin implementation, we can get nodeInfo through `handle.SnapshotSharedLister().NodeInfos()`, So I'm thinking whether update `RunPreScorePlugins` and `RunScorePlugins` is necessary

**Comment by Huang-Wei** [comment]
> So If we update RunPreScorePlugins and RunScorePlugins to exposes NodeInfo, We should also update the plugin interface definition, such as PreScorePlugin

Yes, please update those interfaces' signature.

> So I'm thinking whether update RunPreScorePlugins and RunScorePlugins is necessary

Please change them to accept NodeInfo as well.

**Comment by Huang-Wei** [comment]
cc @kubernetes/sig-scheduling-misc for awareness.

**Comment by alculquicondor** [comment]
I don't have any concerns.

FYI @x13n for the upcoming interface changes.

**Comment by kerthcet** [comment]
Also sounds good to me. 

For discussion: another concern(out of the scope of this issue) about the `PluginsRunner`, since most of the plugins don't care about the `PluginsRunner`, maybe we should extract it from the Handle, which should contain most about the `data and some tools that plugins can use` as commented.  And construct more smaller interfaces for combination, but this needs more works.

**Comment by x13n** [comment]
Thanks @alculquicondor for heads up!

Looks good from the autoscaler perspective: since it only runs PreFilter/Filter, not PreScore/Score, this change should not affect it at all.

**Comment by AxeZhan** [comment]
/assign
Talked with @wackxu , I'll take this over since he doesn't have much bandwidth currently.
