### ISSUE TITLE
Dynamic provisioning stopped working after upgrade

### ISSUE THREAD

**Issue by arthurala** [kubernetes/kubernetes#119913]
### What happened?

Deployments that require PVC stopped working. I thought it the chart but then tested using simple PVC yaml and it also failed to spin up a PV. 

Did a describe on the PVC and it shows status of PENDING
Checked the events and it showed:
MESSAGE:
_waiting for a volume to be created, either by external provisioner "cluster.local/nfs-client-provisioner" or manually created by system administrator_

OUTPUT from / kubectl get sc -o yaml

apiVersion: v1
items:
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2020-06-04T19:24:24Z"
    labels:
      app: nfs-client-provisioner
      chart: nfs-client-provisioner-1.2.8
      heritage: Tiller
      io.cattle.field/appId: nfs-client-provisioner
      release: nfs-client-provisioner
    name: nfs-client
    resourceVersion: "442718644"
    uid: b607cb9e-f49c-4407-827c-4014dddba287
  mountOptions:
  - nfsvers=4.1
  parameters:
    archiveOnDelete: "true"
  provisioner: cluster.local/nfs-client-provisioner
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

We do NOT know when this issue started because most of the deployments don't require PVC.  So we aren't sure if this happened after the Rancher and K8S upgrade

### What did you expect to happen?

Default behavior of Dynamic Provisioning to spin up a PV for a PVC if one doesn't already exist.

### How can we reproduce it (as minimally and precisely as possible)?

unknown

### Anything else we need to know?

Rancher: 2.6.12
Docker: 19.3.11

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.8"

Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14"

### Cloud provider

<details>

</details>
NA

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here

$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
NAME="CentOS Linux"
VERSION="7 (Core)"
Linux 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by arthurala** [comment]
Provision log = 
I0811 18:51:19.203915       1 leaderelection.go:185] attempting to acquire leader lease  nfs-client-provisioner/cluster.local-nfs-client-provisioner...
E0811 18:51:36.614372       1 event.go:259] Could not construct reference to: '&v1.Endpoints{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"cluster.local-nfs-client-provisioner", GenerateName:"", Namespace:"nfs-client-provisioner", SelfLink:"", UID:"420983e9-525f-4f19-8178-4333c400aaf2", ResourceVersion:"442658895", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63726895467, loc:(*time.Location)(0x1956800)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string{"control-plane.alpha.kubernetes.io/leader":"{\"holderIdentity\":\"nfs-client-provisioner-57f49ccf5b-jf8vd_0ee2b427-3878-11ee-8695-bab7f20f017d\",\"leaseDurationSeconds\":15,\"acquireTime\":\"2023-08-11T18:51:36Z\",\"renewTime\":\"2023-08-11T18:51:36Z\",\"leaderTransitions\":84}"}, OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Subsets:[]v1.EndpointSubset(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' 'nfs-client-provisioner-57f49ccf5b-jf8vd_0ee2b427-3878-11ee-8695-bab7f20f017d became leader'
I0811 18:51:36.614457       1 leaderelection.go:194] successfully acquired lease nfs-client-provisioner/cluster.local-nfs-client-provisioner
I0811 18:51:36.614507       1 controller.go:631] Starting provisioner controller cluster.local/nfs-client-provisioner_nfs-client-provisioner-57f49ccf5b-jf8vd_0ee2b427-3878-11ee-8695-bab7f20f017d!
I0811 18:51:36.714726       1 controller.go:680] Started provisioner controller cluster.local/nfs-client-provisioner_nfs-client-provisioner-57f49ccf5b-jf8vd_0ee2b427-3878-11ee-8695-bab7f20f017d!
I0811 18:51:36.715466       1 controller.go:987] provision "report/data-0" class "nfs-client": started
E0811 18:51:36.719407       1 controller.go:1004] provision "report/data-0" class "nfs-client": unexpected error getting claim reference: selfLink was empty, can't make reference
I0811 18:54:03.103016       1 controller.go:987] provision "default/test001-pvc" class "nfs-client": started
E0811 18:54:03.111321       1 controller.go:1004] provision "default/test001-pvc" class "nfs-client": unexpected error getting claim reference: selfLink was empty, can't make reference
I0811 19:06:36.619605       1 controller.go:987] provision "default/test001-pvc" class "nfs-client": started

**Comment by pranav-pandey0804** [comment]
Also, it could be useful to check if there are any issues with the external provisioner `cluster.local/nfs-client-provisioner` and its leader election. The log snippet shows an unexpected error during provision, possibly linked to `selfLink` being empty.

**Comment by BenTheElder** [comment]
/remove-sig k8s-infra


https://github.com/kubernetes/community/tree/master/sig-k8s-infra/README.md


/sig storage

This is in the NFS provisioner
