### ISSUE TITLE
Explain why API server cache doesn't support multi index trigger functions

### ISSUE THREAD

**Issue by Sakuralbj** [kubernetes/kubernetes#119950]
As described [here](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/cacher/cacher.go#L350), what is the reason why apiserver cache does not support multiple trigger functions? Sometimes we need to use another pod-index to reduce amount of watchers that needs to process an incoming event.

**Comment by utkarsh-singh1** [comment]
area/apiserver

**Comment by sftim** [comment]
/retitle Explain why API server cache doesn't support multi index trigger functions

**Comment by jiahuif** [comment]
/assign @wojtek-t 
for the original author, from git praise
/triage accepted

**Comment by Sakuralbj** [comment]
I know the reason，thanks.

**Comment by ahutsunshine** [comment]
@Sakuralbj Can you share why it doesn't support multi index trigger functions?
