### ISSUE TITLE
In e2e tests, there seems to be no provision of updating the agnhost library path when running on windows for network testcases

### ISSUE THREAD

**Issue by pramitagautam** [kubernetes/kubernetes#120071]
### What happened?

I was trying to fix https://github.com/kubernetes/kubernetes/issues/119538 for windows, And I added the below code in NewExecPodSpec function, so that the pod can run as host process container

```
// NewExecPodSpec returns the pod spec of hostexec pod
func NewExecPodSpec(ns, name string, hostNetwork bool) *v1.Pod {
	pod := NewAgnhostPod(ns, name, nil, nil, nil)
	pod.Spec.HostNetwork = hostNetwork

    // new code to run as host process container
    if framework.NodeOSDistroIs("windows") {
        WithWindowsHostProcess(pod, "")
    }
    return pod
}
```

But I am hitting with one more issue:- https://github.com/kubernetes/kubernetes/issues/112651 as I have updated the security specs in pod.

So I have to change the agnhost path to agnhost or $env:CONTAINER_SANDBOX_MOUNT_POINT/agnhost. But I don't think that can be done a) I think that the image is built with the agnhost binary and path is fixed as /agnhost  b) In below function I can add only the "pause" sub-command, not the binary path.

```
// NewAgnhostContainer returns the container Spec of an agnhost container.
func NewAgnhostContainer(containerName string, mounts []v1.VolumeMount, ports []v1.ContainerPort, args ...string) v1.Container {
	if len(args) == 0 {
		args = []string{"pause"}
	}
	return v1.Container{
		Name:            containerName,
		Image:           imageutils.GetE2EImage(imageutils.Agnhost),
		Args:            args,
		VolumeMounts:    mounts,
		Ports:           ports,
		SecurityContext: &v1.SecurityContext{},
		ImagePullPolicy: v1.PullIfNotPresent,
	}
}
```

### What did you expect to happen?

Ideally I should have a provision of updating the library path for the agnhost command as its different for linux and windows

### How can we reproduce it (as minimally and precisely as possible)?

- Try running up and down network tests on windows node and there add a) {"kubernetes.io/os":"windows"} as node selector and b) update the pod spec to run as host process container

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jsturtevant** [comment]
@pramitagautam you should be able to use `Command` on the `v1.Container` spec to override the binary to be executed.  `Args` appends to the "entrypoint" of the contianer image, which in this case is `agnhost`.  

Note I am not sure if this was resolved but we did have issues with the PATHEXT on agnhost and worked around it here https://github.com/kubernetes/kubernetes/blob/70a28449a76aaebe0f3707aa642499f47124dbae/test/e2e/windows/host_process.go#L693-L699

**Comment by jayunit100** [comment]
ohhh so we have to make a change the code that boots up `agnhost` in the e2e/test library
```
func GetCommand(NodeOsDistro string) {
   if NodeOsDistro == "windows" {
      return "%CONTAINER_SANDBOX_MOUNT_POINT%/anghost"
   }
   else {
        return "/anghost"
   }
}
```
and then modify that code to use this `Command:`... 
```

	return v1.Container{
                Command: getCommand(nodeOsDistro)
		Name:            containerName,
		Image:           imageutils.GetE2EImage(imageutils.Agnhost),
		Args:            args,
		VolumeMounts:    mounts,
		Ports:           ports,
		SecurityContext: &v1.SecurityContext{},
		ImagePullPolicy: v1.PullIfNotPresent,
	}
```

**Comment by jsturtevant** [comment]
Yes that is an approach that could work.

`c:\hpc` is the root on the host where the container image will be unpacked for HostProcess contianers.  It is created by containerd.  This behavior changed in 1.6 -> 1.7 and is now hardcoded to `c:\hpc`.  The content of this folder will only be visible inside the container due to bind-filter driver used in 1.7. 

 More details in https://github.com/kubernetes/enhancements/tree/07272ad507da82d66c00302a12d2a0d3d1f9933d/keps/sig-windows/1981-windows-privileged-container-support#container-mounts

**Comment by pramitagautam** [comment]
Thank you for your inputs. I will work on it to see if this fixes the issue. Thanks
