### ISSUE TITLE
eviction_manager has no test paths with dedicatedImageFS set to true.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#120061]
Eviction manager has logic in case of a user having a separate disk for images from node.

Reading the test cases we always set up a MockStatsProvider with `dedicatedImageFs` set to false.  

We should enable test cases with `dedicatedImageFS` set to true.  

```golang
				diskInfoProvider := &mockDiskInfoProvider{dedicatedImageFs: false}
```

All the cases that set this to false mean that we are testing the case where NodeFs and ImageFS are on the same disk.

/kind feature
/help
/sig node

**Comment by charles-chenzz** [comment]
I would like to help with this.
/assign

**Comment by kannon92** [comment]
> I would like to help with this.
> /assign

Thanks for picking it up!

**Comment by charles-chenzz** [comment]
> > I would like to help with this.
> > /assign
> 
> Thanks for picking it up!

learn by doing, I'm reading the code as well!

**Comment by kannon92** [comment]
/close

I ended up taking this over.
