### ISSUE TITLE
Kube-proxy setting (with proxy-mode being ipvs) ipvs.udpTimeout doesn't work

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/kubernetes#120076]
### What happened?

#84041 <a href="https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#kubeproxy-config-k8s-io-v1alpha1-KubeProxyIPVSConfiguration">Introduced a way</a> to control timeouts for UDP traffic when kube-proxy works in IPVS mode.
The setting simply doesn't work, making the actual timeout value get inherited from the underlying system configuration `net.netfilter.nf_conntrack_udp_timeout` (being 30sec by default).

### What did you expect to happen?

The setting for kube-proxy should 'beat' the system value.

### How can we reproduce it (as minimally and precisely as possible)?

Via kube-proxy configmap set `mode: ipvs` and `ipvs.udpTimeout: 300s`.
Restart kube-proxy DaemonSet for settings to supposedly take effect.
Test by sending UDP traffic via kubernetes Service and observe the actual timeouts in conntrack table.

### Anything else we need to know?

The mechanism seems to be majorly broken: `ipvs.syncPeriod` option seems to wipe all entries about related UDP connections **regardless** of their current timeout timer value in the conntrack table!
I.e. a connection with, say, 20s of time left before timeout occurs - will get wiped upon kube-proxy's sync!

### Kubernetes version

<details>
reproduced on 2 clusters of different versions:

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.5", GitCommit:"804d6167111f6858541cef440ccc53887fbbc96a", GitTreeState:"clean", BuildDate:"2022-12-08T10:08:09Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```
```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
self-hosted, 
</details>

### OS version

<details>

```console
$ cat /etc/os-release
CentOS Linux release 7.9.2009 (Core)
$ uname -a
Linux 5.10.6-1.el7.elrepo.x86_64
```
</details>

### Install tools

<details>
kubespray
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd-shim-runc-v2
  Version: v1.6.15
  Revision: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
  Go version: go1.18.9
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI: Calico v3.24.5
</details>

**Comment by aroradaman** [comment]
@Drugoy IPVS maintains an internal connection table and the parameters **ipvs**.[**tcpFinTimeout**|**tcpTimeout**|**udpTimeout**] [update IPVS connection timeouts](https://linux.die.net/man/8/ipvsadm#:~:text=or%20all%20services.-,%2D%2Dset%20tcp%20tcpfin%20udp,-Change%20the%20timeout) not netfilter conntrack timeouts.

After restarting kube-proxy, you can watch `ipvsadm --list --connection` to see the new timeout values being used by IPVS.

/cc. @uablrek

**Comment by aroradaman** [comment]
> The mechanism seems to be majorly broken: ipvs.syncPeriod option seems to wipe all entries about related UDP connections regardless of their current timeout timer value in the conntrack table!
I.e. a connection with, say, 20s of time left before timeout occurs - will get wiped upon kube-proxy's sync!


@Drugoy I can't reproduce this in master/release-1.28.0, conntrack cleaning seems to be working fine. Only restarting kube-proxy clears conntrack table.

**Comment by Drugoy** [comment]
@aroradaman I don't see UDP 'connections' at all in the output of `ipvsadm --list --connection`, that's why I was looking for them in the netfilter's conntrack.
I test it like that: I've deployed
  - a pod 'client' (with busybox+netcat)
  - a deployment 'server' with a single pod (with busybox+netcat)
  - a service for the deployment

The service has
```
...
   ports:
     - name: test
       port: 8080
       protocol: UDP
       targetPort: 8080
```
Then in the 'server' pod I run `nc -kul 8080 &` (use netcat to set up a UDP listener on port 8080) + then from 'client' pod I connect via UDP to the service (`nc -u myservice:8080` and then I just enter a few lines of text).
Client and server pods are on 2 different worker nodes and I don't see any UDP entries in `ipvsadm --list --connection` on either of these 2 nodes (I even checked on master nodes).

But I do see entries about UDP connections in netfilter's conntrack.

I might be misunderstand how things should work, so I have a follow up question: when an administrator raises `ipvs.udpTimeout` to 60 sec in the `kube-proxy` secret (and restarts kube-proxy to apply the changes) - what for UDP connections should one then observe in netfilter's conntrack table?

**Comment by aroradaman** [comment]
@Drugoy I followed the exact same steps and was able to see entries in both `netfilter.conntrack` and `ipvs.connections`.

> I might be misunderstand how things should work, so I have a few follow up questions:

1. `ipvs.udpTimeout` flag only updates IPVS timeouts. Conntrack will keep on using the default `nf_conntrack_udp_timeout` value which is 30 seconds. 

2. Yes, you would have to update the value of `nf_conntrack_udp_timeout` manually for now. You can also change `nf_conntrack_udp_timeout_stream` if packets flow in both directions in your application. 


I can see `config.Conntrack.TCPCloseWaitTimeout` and `config.Conntrack.TCPEstablishedTimeout` in proxy configuration, maybe we can add `config.Conntrack.UDPTimeout`, wdyt @danwinship @aojea @uablrek ?

**Comment by Drugoy** [comment]
@aroradaman 
1. If anyone who wants to raise timeouts (to values higher than defaults) has to not only update IPVS options in kube-proxy's config but also has to manually update `net.netfilter.nf_conntrack_*_timeout*` options on the underlying OS, since a 'connection' has to be in both IPVS' virtual server table AND netfilter's conntrack table - what was even the sense of introducing 'comfortable' configuration of IPVS via ConfigMap?
This doesn't seem to bring much comfort if manual actions are still required.
And yes, it was weird that <a href="https://kubernetes.io/docs/reference/config-api/kube-proxy-config.v1alpha1/#kubeproxy-config-k8s-io-v1alpha1-KubeProxyConntrackConfiguration">KubeProxyConntrackConfiguration</a> only introduced the options for TCP, but not for UDP.

2. Since it seems to kinda work for you and for some reason fails for me (but I will try some more to reproduce it) - could you, please, set both IPVS (`ipvs.udp_timeout`) and nftable (`net.netfilter.nf_conntrack_udp_timeout` + `net.netfilter.nf_conntrack_udp_timeout_stream`) options to something high as 60 or even 120 sec, make sure that `ipvs.syncPeriod` is set to default `30s`), send some UDP traffic and then *just observe* both netfilter's conntrack table and ipvs' virtual server: will the timer there ever actually reach values like 17s?
In my experience - the entries get wiped completely (from conntrack) every `ipvs.syncPeriod` seconds! And that surely looks like a *huge* bug.

**Comment by aroradaman** [comment]
@Drugoy possible to share logs for kube-proxy (verbosity level 4)?

**Comment by aroradaman** [comment]
@Drugoy 

> 1. If anyone who wants to raise timeouts (to values higher than defaults) has to not only update IPVS options in kube-proxy

Assuming there is an option for configuring `Conntrack.UDPTimeout` in the future, I believe both `Conntrack.UDPTimeout` and `IPVS.UDPTimeout` should be handled separately as both are independent sub-systems where one deals with all the packets destined for the machine and other only deals with packets destined for IPVS virtual servers. Increasing  `IPVS.UDPTimeout` will allow the IPVS connection to be re-used after a longer inactivity period and this only affects IPVS traffic one can set it to a much higher value than `Conntrack.UDPTimeout`. 

> 2. Since it seems to kinda work for you and for some reason fails for me (but I will try some more to reproduce it) - could you

Tested on kind `kindest/node:v1.26.3` with `ipvs.udp_timeout` and `net.netfilter.nf_conntrack_udp_timeout*` set to 300 seconds. 

Entries at the beginning:
```
IPVS connection entries
pro expire state       source             virtual            destination
UDP 04:55  UDP         10.244.3.2:42908   10.96.17.45:8080   10.244.2.2:8080

conntrack v1.4.6 (conntrack-tools): 3 flow entries have been shown.
udp      17 294 src=10.244.3.2 dst=10.96.17.45 sport=42908 dport=8080 [UNREPLIED] src=10.244.2.2 dst=10.244.3.2 sport=8080 dport=42908 mark=0 use=1
```

Entries roughly after 280 seconds:
```
IPVS connection entries
pro expire state       source             virtual            destination
UDP 00:18  UDP         10.244.3.2:42908   10.96.17.45:8080   10.244.2.2:8080

conntrack v1.4.6 (conntrack-tools): 1 flow entries have been shown.
udp      17 16 src=10.244.3.2 dst=10.96.17.45 sport=42908 dport=8080 [UNREPLIED] src=10.244.2.2 dst=10.244.3.2 sport=8080 dport=42908 mark=0 use=1
```

**Comment by Drugoy** [comment]
@aroradaman I got a bit closer to the issue:
So on a kubernetes cluster v1.25.5 everything seems to work perfectly:
I now see entries about my UDP traffic on the correct node.
The timeout there matches the value set via kube-proxy ConfigMap.
The entry about my UDP connection doesn't get wiped before it's timeout timer reaches 0 (so, the behavior here is correct) neither from IPVS nor from conntrack tables.

Re-testing now on v1.26.3 cluster where I see the problem and trying to diff options between these 2 clusters.

**Comment by Drugoy** [comment]
Well, that's weird, but on the cluster where I initially caught the problem (v1.26.3) I clearly see kube-proxy being configured with `mode: ipvs` (I even restarted kube-proxy DaemonSet just to make sure what I see in the ConfigMap is what is actually applied), but when I send UDP traffic - I only see an entry about it in conntrack table, but nothing about any UDP at all in IPVS table.
I test it the very same way I tested on v1.25.5.
I am puzzled now.

**Comment by uablrek** [comment]
As @aroradaman I can't see that any conntrack entries are removed on a kube-proxy. I _can_ confirm that an UDP "connection" fails when the conntrack entry times out (default 30s or 120s if ASSURED).

Since ipvs preserves it's entry, the conntrack should be re-created even when it has expired when a new packet arrives. That has worked in the past, but is broken by `--random-fully`. Now, when the conntrack entry expires the next packet will get a new random port that the server knows nothing about.

I tested to re-build kube-proxy without `--random-fully` and then everything works fine. The conntrack entry is re-created with the same addr/port as for the original packet.

**Comment by uablrek** [comment]
`--random-fully` can probably not be removed, but can perhaps be made configurable in some way. Some servers may actually expect the original client source port to be preserved (for UDP and SCTP that is, but not likely for TCP)

**Comment by uablrek** [comment]
@Drugoy  If you can live with `externalTrafficPolicy: Local` for your service (assuming your traffic is from an external client) that is a work-around. Then the source port and source address are preserved (no `--random-fully`).

**Comment by uablrek** [comment]
> I can see config.Conntrack.TCPCloseWaitTimeout and config.Conntrack.TCPEstablishedTimeout in proxy configuration, maybe we can add config.Conntrack.UDPTimeout

Seems like a good idea. Since that is the only way for proxy-mode=iptables, I wonder why it's missing

**Comment by Drugoy** [comment]
@aroradaman @uablrek thank you!
To sum it up:
1. it looks like I have 1 weird cluster where kube-proxy is configured to work in IPVS mode, but UDP connections for some reason don't get into IPVS table. This behavior doesn't reproduce at least on 1 another cluster (though their versions are different) on my end and on @aroradaman's cluster. This behavior looks like a bug, but is different from what I've initially described in this ticket.
2. @uablrek provided a workaround (either use `externalTrafficPolicy: Local` in the Service or re-build kube-proxy without `--random-fully`) for my case that should re-create iptables entry based on IPVS entry if only IPVS timeouts were configured and netfilter's timeouts remain with default values.
3. It looks like there's a case for Feature Request to add a proxy configuration for `config.Conntrack.UDPTimeout` option. Should Would you like me to file this as a separate ticket?

Now even though a workaround might suit my case, I'd still like to understand why one of my cluster behaves so that sending UDP traffic doesn't result into an entry in IPVS table, while kube-proxy's is clearly configured to work in IPVS mode.
I think this is the reason why kube-proxy's `ipvs.syncPeriod` timer wipes the entries from conntrack table.
I will try to investigate that on my own, but I'd appreciate any help/hints/explanations. My only suspicion is that it has something to do with CNI (Calico) configuration. I just learned that kube-proxy is basically optional and we even have 1 cluster working without it at all.

**Comment by aroradaman** [comment]
@Drugoy feel free to open an issue for adding conntrack.UDPTimeout configuration.

**Comment by khenidak** [comment]
> it looks like I have 1 weird cluster where kube-proxy is configured to work in IPVS mode, but UDP connections for some reason don't get into IPVS table. This behavior doesn't reproduce at least on 1 another cluster (though their versions are different) on my end and on @aroradaman's cluster. This behavior looks like a bug, but is different from what I've initially described in this ticket.

Kubernetes does not set ipvs timeouts directly. It rely on this: https://github.com/moby/ipvs/blob/master/netlink_linux.go#L602 (netlink wrapper). The failure can be specific to your setup. Can you check kernel logs via `dmesg`?

otherwise, we should surface UDP conntrack settings to config.

**Comment by Drugoy** [comment]
I have to close this issue as I didn't find anything worthy in dmesg and I've switched employer, so this issue will remain a mystery.
