### ISSUE TITLE
hack/update-vendor.sh fails with Go 1.21 (import is a program not a package)

### ISSUE THREAD

**Issue by skitt** [kubernetes/kubernetes#120022]
### What happened?

I was looking into upgrading Go to 1.21 (for the `slices` package among other things), and ran into a failure with `hack/update-vendor.sh`. On master everything works as usual; but

```
$ echo 1.21.0 > .go-version
$ hack/update-vendor.sh
+++ [0817 16:21:39] logfile at /tmp/update-vendor.2j1y/update-vendor.log
+++ [0817 16:21:39] go.mod: update staging references
+++ [0817 16:21:47] go.mod: propagate to staging modules
+++ [0817 16:21:47] go.mod: sorting staging modules
An error has occurred. Please see more details in /tmp/update-vendor.2j1y/update-vendor.log
```

The error is

```
=== computing tools imports for k8s.io/apiextensions-apiserver
+ go list -tags=tools all
go: found k8s.io/code-generator in k8s.io/code-generator v0.0.0-00010101000000-000000000000
../code-generator/tools.go:25:2: import "k8s.io/code-generator/cmd/applyconfiguration-gen" is a program, not an importable package
```

### What did you expect to happen?

I didn’t see anything relevant in [the Go 1.21 release notes](https://tip.golang.org/doc/go1.21) so I expected this to work. It’s not clear to me whether this is a k/k bug or a Go bug.

### How can we reproduce it (as minimally and precisely as possible)?

See above:

```
$ echo 1.21.0 > .go-version
$ hack/update-vendor.sh
```

### Kubernetes version

<details>
N/A
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
RHEL 8.8 running kernel 4.18.0-477.15.1.el8_8.x86_64
</details>

### Install tools

<details>
N/A
</details>

### Container runtime (CRI) and version (if applicable)

<details>
N/A
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by liggitt** [comment]
this is fixed in https://github.com/kubernetes/kubernetes/pull/119027
