### ISSUE TITLE
load balancing services in pods with limited resources

### ISSUE THREAD

**Issue by Rbsn-joses** [kubernetes/kubernetes#120084]
does setting the resource limit on the pod influence the service balance?
I have a problem that when I set the limit , the service does not balance the request correctly between the pods.the most resourceful and ignored pod

kubernetes: 1.24

**Comment by aojea** [comment]
/kind support

this description is very vague and hard to answer, anyway, it is better that you use other channels like discord or slack for support, we try to keep github issues only for reporting bugs or code related questions.

If you feel there is a bug on the code, please reopen and add a more detailed description of the problem

Thanks

/close
