### ISSUE TITLE
`[sig-node] Security Context should support volume SELinux relabeling` fails on `ci-crio-cgroupv1-node-e2e-flaky`

### ISSUE THREAD

**Issue by saschagrunert** [kubernetes/kubernetes#120004]
### Which jobs are failing?

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky

### Which tests are failing?

- [It] [sig-node] Security Context should support volume SELinux relabeling [Flaky] [LinuxOnly]
- [It] [sig-node] Security Context should support volume SELinux relabeling when using hostIPC [Flaky] [LinuxOnly]
- [It] [sig-node] Security Context should support volume SELinux relabeling when using hostPID [Flaky] [LinuxOnly]

### Since when has it been failing?

Since the merge of https://github.com/kubernetes/kubernetes/pull/119974

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-flaky

### Reason for failure (if possible)

I assume it's somehow related to the busybox bump, the pods got stuck in pending rather than being created.

### Anything else we need to know?

cc @haircommander @harche 

### Relevant SIG(s)

/sig node

**Comment by saschagrunert** [comment]
Using the old image before https://github.com/kubernetes/kubernetes/pull/119974 in https://github.com/kubernetes/kubernetes/pull/120005 will also make the tests fail with the pod stuck on pending. :thinking:

**Comment by tzneal** [comment]
Just checked and still all green

/close
