### ISSUE TITLE
Unify utils to fake pod in scheduler

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/kubernetes#120002]
### What would you like to be added?

We have a pod fake function `makeBasePod` in https://github.com/kubernetes/kubernetes/blob/4f874a224a31a5dc5745a0c140d3769bb178f811/pkg/scheduler/framework/types_test.go#L217-L249, but this is not a base util anymore, we have a lot of arguments, we can replace this with `PodWrapper` here https://github.com/kubernetes/kubernetes/blob/4f874a224a31a5dc5745a0c140d3769bb178f811/pkg/scheduler/testing/wrappers.go#L215

/sig scheduling
/kind cleanup
/help

This is an easy one to get start.

### Why is this needed?

Cleaner code for maintenance.

**Comment by charles-chenzz** [comment]
I want to try this one, the problem we solve here is to replace the *v1.Pod with type PodWrapper {}?
/assign

**Comment by kerthcet** [comment]
> I want to try this one, the problem we solve here is to replace the *v1.Pod with type PodWrapper {}?

Replace `makeBasePod` with `MakePod` in wrappers.go.

**Comment by charles-chenzz** [comment]
> Replace makeBasePod with MakePod in wrappers.go.

you mean replace ``makeBasePod`` with ``MakePod``  in types_test.go? I check the code and didn't found out that we have makeBasePod in wrappers.go

**Comment by lowang-bh** [comment]
I have tried it. But there will be cycle import where `testing` package imported `framework` package, where `types_test `locate.

**Comment by charles-chenzz** [comment]
yes, I've tried it as well. guess I need to wait for kerthcet's response
<img width="805" alt="image" src="https://github.com/kubernetes/kubernetes/assets/73322208/08da0c3f-2416-424f-b32f-f9dd15104f03">

**Comment by kerthcet** [comment]
Sorry, forgot to reply on this, I introduced another PR https://github.com/kubernetes/kubernetes/pull/120252 to help solve this **import cycle**, but waits for other maintainers' response. So generally, if that pr accepted, we can work on this one then. Thanks for the volunteer.

**Comment by kerthcet** [comment]
@charles-chenzz the import cycle is resolved, you can start your work now, thanks!

**Comment by charles-chenzz** [comment]
> @charles-chenzz the import cycle is resolved, you can start your work now, thanks!

thanks for the ping!
