### ISSUE TITLE
kube-apiserver doesn't clean up OpenAPI properly after deleting an APIService/CRD

### ISSUE THREAD

**Issue by tnqn** [kubernetes/kubernetes#120107]
### What happened?

I noticed some odd behaviors/logs after deleting APIServices and CRDs.

First, only CRDs were removed from the response of `/openapi/v3` and APIServices were not removed. Not only the root path, the APIService's specific paths were also available, e.g. `/openapi/v3/apis/foo.bar.com/v1alpha1`, as if they were not deleted.

Second, there were some confusing logs in kube-apiserver, indicating it failed to do some cleanup, and every failure was duplicated once:
```
E0822 15:24:36.314675       1 controller.go:159] removing "v1alpha1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.314705       1 controller.go:159] removing "v1alpha1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.316316       1 controller.go:159] removing "v1beta1.crd.antrea.io" from AggregationController failed with: resource not found
E0822 15:24:36.317664       1 controller.go:159] removing "v1beta1.crd.antrea.io" from AggregationController failed with: resource not found
```

After checking the code, I found the above observations were caused by the same code in kube-apiserver which didn't handle the removal of APIService correctly:
https://github.com/kubernetes/kubernetes/blob/aa8cb97f65fe1d24e96eda129337d86109615570/staging/src/k8s.io/kube-aggregator/pkg/apiserver/apiserver.go#L563-L568

Basically apiserver was calling wrong AggregationController when removing APIService, which caused OpenAPI v3 not cleaned up and the duplicate errors. There was another issue in v2 AggregationController which caused the error. 

Besides, just correcting L567 didn't fix the problem totally, there were some other issues in the implementation.

### What did you expect to happen?

kube-apiserver should clean up OpenAPI correctly, shoud not generate confusing errors.

### How can we reproduce it (as minimally and precisely as possible)?

Install some APIServices and CRDs and remove all of them, then check the response of "/openapi/v3" and kube-apiserver logs.

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.0", GitCommit:"855e7c48de7388eb330da0f8d9d2394ee818fb8d", GitTreeState:"clean", BuildDate:"2023-08-15T21:24:51Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexzielenski** [comment]
/unassign @jefftree
/cc @Jefftree 
looks like there is a PR already open
