### ISSUE TITLE
kubernetes 1.28.0: vendor directory is possibly incomplete

### ISSUE THREAD

**Issue by williamh** [kubernetes/kubernetes#120114]
Hi all,

I am the kubernetes package maintainer for Gentoo Linux.

When I attempt to compile any of the k8s binaries using our package manager on amd64, I get output similar to the following from attempting to compile kubeadm:
make -j9 -j1 GOFLAGS=-v GOLDFLAGS= LDFLAGS= WHAT=cmd/kubeadm
go: downloading go.uber.org/automaxprocs v1.5.2
ncpu/main.go:23:2: go.uber.org/automaxprocs@v1.5.2: Get "https://proxy.golang.org/go.uber.org/automaxprocs/@v/v1.5.2.zip": dial tcp: lookup proxy.golang.org on [2002:467c:a8b0:0:3e37:86ff:fec9:b892]:53: dial udp [2002:467c:a8b0:0:3e37:86ff:fec9:b892]:53: connect: network is unreachable
!!! [0822 16:12:22] Call tree:
!!! [0822 16:12:22]  1: /var/tmp/portage/sys-cluster/kubeadm-1.28.0/work/kubernetes-1.28.0/hack/lib/golang.sh:843 kube::golang::setup_env(...)
!!! [0822 16:12:22]  2: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0822 16:12:22] Call tree:
!!! [0822 16:12:22]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries
(...)
make: *** [Makefile:92: all] Error 1
 * ERROR: sys-cluster/kubeadm-1.28.0::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=sys-cluster/kubeadm-1.28.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sys-cluster/kubeadm-1.28.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/sys-cluster/kubeadm-1.28.0/temp/build.log'.

My understanding is contacting proxy.golang.org should not be attempted to the vendor directory, so this makes me think the vendor directory is incomplete.

What am I missing?

Thanks,

William

**Comment by tzneal** [comment]
It's used for running tests to prevent a bunch of test flakes when running against varied machine sizes.  https://github.com/kubernetes/kubernetes/pull/119977/ should have made it so that only is used in tests and it was backported to 1.28 last week. Does that resolve it for you?

**Comment by williamh** [comment]
Yes, the back port of #119977 resolves the issue.

Thanks much.

**Comment by tzneal** [comment]
Sounds good

/close
