### ISSUE TITLE
configmap voulme not mapping  to a MountPath to an airflow POD

### ISSUE THREAD

**Issue by erosons** [kubernetes/kubernetes#120190]
Hello Folks ,

I am using Server Version: v1.24.16-eks-2d98532,  created a configMap with two data point which are ssl crt and key as shown below 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ssl-keys
data:
  server.crt: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
  server.key: |
    -----BEGIN RSA PRIVATE KEY-----
    
        -----END RSA PRIVATE KEY-----
```
I having trying to mount the configMap to a MountPath in the pod => /opt/airflow  for an airflow application helm chart deployment.
but I am getting this error 
`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/kubelet/pods/fc9acf89-8a68-4891-a5cf-3978edfa32c3/volume-subpaths/config/wait-for-airflow-migrations/0" to rootfs at "/opt/airflow/airflow.cfg": mount /var/lib/kubelet/pods/fc9acf89-8a68-4891-a5cf-3978edfa32c3/volume-subpaths/config/wait-for-airflow-migrations/0:/opt/airflow/airflow.cfg (via /proc/self/fd/6), flags: 0x5001: not a directory: unknown`

<img width="361" alt="image" src="https://github.com/kubernetes/kubernetes/assets/73761240/56f990a9-77b5-4a2e-b467-1ec11805a2df">

This what the intake schema.json of airflow application looks like 

<img width="396" alt="image" src="https://github.com/kubernetes/kubernetes/assets/73761240/5639f96c-a5c3-4542-9681-aaf06731dc8a">

**Comment by kannon92** [comment]
Hey @erosons,

I’d recommend asking for help on this in the airflow community.  Airflow has some good slacks especially around kubernetes.  

Reading the logs it looks like you aren’t mounting a volume for /opt/airflow.

**Comment by neolit123** [comment]
/sig storage
/close

please ask #sig-storage on k8s slack if more help is needed
