### ISSUE TITLE
how to get all pods in a replicationcontroller？

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12013]
if   i  create a rc "redisrc" which has 4 replicases.and the label in its podtemplate is :name=redispod, how could i get these 4 pods within a webAPI, or command?

in the etcd  registry.   the data of this rc  doesn't have the message of its pods.

it's confusing.....

i create a replicationcontroller with  4 pods.  but  i don't  know   these pods'  names.   If i create another pod named "redisrcpp",  how can i distinguish between new pod and the 4 pods?

**Comment by stevesloka** [comment]
If you want to find all pods using a label, then pass `-l` in your kubectl command. 

e.g. `kubectl get pods -l name=redispod`

The pods will get named with the name you give it appended with a random string.

**Comment by yujuhong** [comment]
To expand on the previous comment, replication controller manages pod matching its [label selector](https://github.com/GoogleCloudPlatform/kubernetes/blob/2bd53119b1f7408aab93441096b00d62c8d12184/docs/user-guide/labels.md#label-selectors). You can see the selector by `kubectl get rc`, and filter pods with the selector.
E.g., `kubectl get pods -l key1=value1,key2=value2`

**Comment by fzu-huang** [comment]
@stevesloka  @yujuhong thank you all.  I know these ways but i think they're too complicated(BTW, use : kubectl describe pods redispod    will  be  better).
 what's more, I didn't  find  a  WebAPI  to do it.

**Comment by nikhiljindal** [comment]
You can get all the pods with name=frontend label using:
http://{master-ip}/api/v1/pods?labelSelector=name=frontend

http://kubernetes.io/v1.0/docs/api-reference/operations.html lists all possible URL operations.

**Comment by fzu-huang** [comment]
@nikhiljindal   NICE~   thanks~

**Comment by mbforbes** [comment]
@fzu-huang it looks like this has been resolved, so I'm closing the issue. Please ping if it's not. Thank you!
