### ISSUE TITLE
kubelet get configmap from kube-apiserver and etcd everytime

### ISSUE THREAD

**Issue by likakuli** [kubernetes/kubernetes#120126]
### What happened?

qps of configmap get request is too high in kube-apiserver.

when there are many configmaps in cluster mounted by running pod, the qps of configmap get request will be high and the request will also need to get configmap resource from etcd instead of returned from kube-apiserver cache.

### What did you expect to happen?

DO NOT get configmap from etcd. Get it from cache of kube-apiserver.

### How can we reproduce it (as minimally and precisely as possible)?

1. set kubelet configMapAndSecretChangeDetectionStrategy to Cache;
2. set kube-apiserver --v=3
3. create lots of configmaps mount to pods
4. check kube-apiserver metrics `sum(rate(apiserver_request_total{resource="configmaps",verb="GET"}[5m])) by (verb,resource,subresource)` 
5. check kube-apiserver log

### Anything else we need to know?

I have tested it in v1.22.13 and v1.28.0. The logic to set resourceversion=0 seems never be triggered

### Kubernetes version

<details>

```console
1.22.13, 1.28.0 
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by matthyx** [comment]
Thanks @likakuli can you also fill-in at least the kubernetes version, but the more info the better in your initial comment?

**Comment by likakuli** [comment]
added k8s version.

**Comment by likakuli** [comment]
I think this issue is related to kubelet not kube-apiserver and i have found the root cause i think. @mmiranda96

**Comment by jiahuif** [comment]
Could you add concrete data for some metrics?
- the request rate you describe
- timing for the requests. Is there a slowdown?

**Comment by likakuli** [comment]
request rate depends on the total number of configmaps mounted to pods. what i care is not reduce the qps but to use kube-apiserver cache instead of direct request to etcd.

for now, the request will redirect to etcd.  there is no resourceVersion in the request query.

**Comment by likakuli** [comment]
steps:
> * set kubelet configMapAndSecretChangeDetectionStrategy to Cache;
> * set kube-apiserver --v=3
> * create lots of configmaps mount to pods
> * check kube-apiserver metrics `sum(rate(apiserver_request_total{resource="configmaps",verb="GET"}[5m])) by (verb,resource,subresource)`
> * check kube-apiserver log

code:
https://github.com/likakuli/kubernetes/blame/ead7d66ee12656cfb7c633dd42a87f8d9cfaa469/pkg/kubelet/util/manager/cache_based_manager.go#L180-L203

```golang
if data.err != nil || !s.isObjectFresh(data) {
	opts := metav1.GetOptions{}
	if data.object != nil && data.err == nil {
		// This is just a periodic refresh of an object we successfully fetched previously.
		// In this case, server data from apiserver cache to reduce the load on both
		// etcd and apiserver (the cache is eventually consistent).
		util.FromApiserverCache(&opts)
	}

	object, err := s.getObject(namespace, name, opts)
	if err != nil && !apierrors.IsNotFound(err) && data.object == nil && data.err == nil {
		// Couldn't fetch the latest object, but there is no cached data to return.
		// Return the fetch result instead.
		return object, err
	}
	if (err == nil && !isObjectOlder(object, data.object)) || apierrors.IsNotFound(err) {
		// If the fetch succeeded with a newer version of the object, or if the
		// object could not be found in the apiserver, update the cached data to
		// reflect the current status.
		data.object = object
		data.err = err
		data.lastUpdateTime = s.clock.Now()
	}
}
```
The invocation chain is quite lengthy and the reason like blow:
1.  kubelet has a ticker with 1s interval and will try to get pods from queue to sync if there is data in syncCh;
2. the `--sync-frequency` is default set to 1m. pod will be enqueued with a random time between 1m ~ 1.5m by default;
3. there is background reconcicler in `pkg/kubelet/volumemanager/reconciler/reconciler.go` file. it will run every 100ms to try to mountAttachVolumes which could trigger configmap get operation when the volume is not mounted or require remount;
4. data.object will be set to nil each time pod to sync via `AddReference`. pay attention to the comment.
```golang
    // This will trigger fetch on the next Get() operation.
    item.data = nil
``` 
5. when to mount or remount volume, a configmap get request will be triggered and because the data.object is nil, the resourceversion query will not be added which result to the request goes to etcd finally.
6. after volume mounted, the `remountRequired` flag will be set to false in `actualStateOfWorld`;
7. thus when next mountAttachVolumes called but volume has been mounted and not require remount, no need to get configmap from kubelet's cache. therefore there will no http request to apiserver to get configmap;
8. there may be some configmap get operation can be satisfied by cachebasedmanager by directly return configmap from local cache or get it from apiserver's cache when cache expired because same configmap can be used by many pods and each pod has a goroutine to execute syncPod but only one goroutine to operate configmap.


I think we can always set resourceversion=0 to the query and ignore whether it's the first time to fetch the configmap or just the local cache expired.

**Comment by liggitt** [comment]
> data.object will be set to nil each time pod to sync via AddReference. pay attention to the comment.

That was intentional, so that a newly scheduled pod would be sure to get latest content from the API.

However, RegisterPod is called on every resync, and the cacheBasedManager#RegisterPod implementation is calling AddReference on all references every time, not just changed references. I agree we don't want to do that.

> I think we can always set resourceversion=0 to the query and ignore whether it's the first time to fetch the configmap or just the local cache expired

No, we want to actually fetch a live object the first time we get data for a new pod.

I think the fix needs to happen in cacheBasedManager#RegisterPod to only call AddReference for items which are not in c.getReferencedObjects(prev)

**Comment by likakuli** [comment]
make sense to me. let me try to fix it.
/assign
