### ISSUE TITLE
v1.1 Conformance test

### ISSUE THREAD

**Issue by erictune** [kubernetes/kubernetes#12014]
In conjunction with the v1.1 release:
- make a new branch `conformance-test-v1.1`
- add a blank column to the table in `docs/getting-started-guides/README.md` for v1.1 conformance.
- define the set of tests to run to test v1.1 conformance.  This would presumably be all the tests that were run for v1.0 conformance, minus any that were deleted, plus any new ones that are expected to pass on all platforms.   The set of tests is defined via a ginkgo flag in `hack/conformance-test.sh
- run for GKE, GCE, Vagrant, and Docker, and put checkmarks in v1.1 column of aforementioned table.

In particular, the v1.1 conformance test should require clusters to:
- have cluster DNS

(edit this comment to add items to above list).

**Comment by bgrant0607** [comment]
Is this done? If not, if this is for 1.1, it needs to be P0 at this point. Should it be?

**Comment by erictune** [comment]
Can be done somewhat after 1.1.  Removing milestone.

**Comment by davidopp** [comment]
The milestone was not actually removed. I'll remove it.

**Comment by ixdy** [comment]
Given that we're changing how we do conformance testing (i.e. using release branches, not a conformance test branch), should we just close this issue?

@kubernetes/sig-testing @kubernetes/goog-testing

**Comment by spiffxp** [comment]
agreed
