### ISSUE TITLE
how does kubernetes limit a container's  resources?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12015]
as i know, resourcequota and limit  are used to constraint  pod/container 's start .
when  i  set a limit rule, and set a limit in pod.json.     the pod might not successful start because its limit over the max or low than min limit.

then how to do this? i start a pod ,it use 64MB memory ,after a long time , i used much more memory than 64mb. maybe 100MB.  How to set a rule , to stop it automatically  when it use memory  more than 80Mb?

**Comment by yujuhong** [comment]
Here is an overview of resources kubernetes: https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/design/resources.md

If I understand your question correctly, you should be able to simply set the Resources.Limits (max resources requested) for each container. For example, if you set the memory limit to 80MB, scheduler would first check if there is any node with more than 80MB memory and assign the pod to the node. When starting the container on the node, the resource limits would be passed down to the container runtime (i.e., Docker or rkt), which may use cgroups to set the limit. The container would likely get terminated when it requests >80MB of memory.

**Comment by fzu-huang** [comment]
@yujuhong   thank you very much~  .  I am not good at English,  but  your example  is exactly what i want to do.

**Comment by fzu-huang** [comment]
@yujuhong  yes,your example is what i want to do.   but  i don't  have an idea...   can you tell me how to realize that?

**Comment by dalanlan** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide/resourcequota
This doc may help.
