### ISSUE TITLE
Pending pod are not recreated after updating statefulset resources

### ISSUE THREAD

**Issue by lwabish** [kubernetes/kubernetes#120123]
### What happened?

At first, I created a statefulset with a huge resource request, which leads to its pod stuck at pending status.
Then, I edited the statefulset with a reasonable resource request. But its pod remains pending , no recreating triggered.

After some digging code of statefulset controller:https://github.com/kubernetes/kubernetes/blob/2fef630dd216ddefd051ef5a2dda3fe1fdf7439a/pkg/controller/statefulset/stateful_set_control.go#L271 , I found it seems to be the reasonable behavior by design.
Meanwhile, I found that changing `.spec.podManagementPolicy` to `Parallel` could solve this problem. But this change leads to pods of statefulsets lose order squences.

Not sure if this is a bug.

### What did you expect to happen?

Is it possible to let pending pods of statefulsets try recreating without setting `.spec.podManagementPolicy` to `Parallel`?
Maybe implement some more logic in statefulset controller?

### How can we reproduce it (as minimally and precisely as possible)?

1. create a statefulset with a huge resource request like: `resources.request.memory=100000Gi`, keep `.spec.podManagementPolicy` the default value (`OrderedReady`)
2. pod-0 should be pending now
3. edit the statefulset with `kubectl edit`, change `resources.request.momory=1Mi`
4. nothing happens, but statefulset resource is updated successfully and the pending pod will never be recreated until manually deleted.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.13", GitCommit:"80ec6572b15ee0ed2e6efa97a4dcd30f57e68224", GitTreeState:"clean", BuildDate:"2022-05-24T12:40:44Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
```
also reproduced in kubernetes 1.24.10

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pwschuurman** [comment]
It sounds like this is the same root cause as #67250. There is a KEP (https://github.com/kubernetes/enhancements/pull/3562) to add an option to allow non-running pods to be deleted and re-created.

@lwabish What's your underlying goal that this issue is blocking? Is it related to misconfigured pods being stuck in a Pending state, or do you wish to gate a StatefulSet pod being scheduled?

**Comment by lwabish** [comment]
@pwschuurman misconfigured pods being stuck in a Pending state, even after users updating the statefulset resource to be right

**Comment by farazkhawaja** [comment]
bump. any updates ?

**Comment by Chupaka** [comment]
@lwabish could you `/reopen` this issue? :)

**Comment by lwabish** [comment]
> [@lwabish](https://github.com/lwabish) could you `/reopen` this issue? :)

Sorry It seems that I do not have permission to reopen this issue

**Comment by Chupaka** [comment]
> Sorry It seems that I do not have permission to reopen this issue

I mean, simply comment `/reopen`, like here: https://github.com/kubernetes/kubernetes/issues/120123#issuecomment-2485912786
