### ISSUE TITLE
how to change the InPlacePodVerticalScaling flag while the k8s is installed by kubeadm

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/kubernetes#120170]
### What happened?

i want to use this  new feature : Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha) (https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/)

i do not have this directory(~/go/src/k8s.io/kubernetes)
<img width="696" alt="image" src="https://github.com/kubernetes/kubernetes/assets/20768380/b9f419f4-d091-495e-ac44-2180279b5866">

my k8s is installed by kubeadm

do you have some suggestions about how to use this feature while the k8s is installed by kubeadm

i am a newer of k8s

looking for your reply

best
Lisa Shi

### What did you expect to happen?

use this new featute ( Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha) )

### How can we reproduce it (as minimally and precisely as possible)?

use this new featute ( Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha) )

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>
1.27.4

### Cloud provider

<details>

</details>
none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

also try #sig-node on k8s slack

/kind support
/close

**Comment by wang-mask** [comment]
+1

**Comment by wang-mask** [comment]
How to open this fuature on a installed cluster?
