### ISSUE TITLE
Facing error while connecting nodes; kubelet is not starting

### ISSUE THREAD

**Issue by siramkarthik890** [kubernetes/kubernetes#120121]
**This is a Bug Report**

**Problem:**
[kubelet-check] The HTTP call equal to 'curl -SSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz"
target machine actively refused it..

Iam facing the above error while connecting ubuntu master to windows worker node
Master CRI is containerd
Worker CRI id docker

Can anyone help me in this

**Comment by sftim** [comment]
/close

GitHub is not the right place to ask for support.
