### ISSUE TITLE
Pods in kube-system trying and failing to retrieve an image pull secret from another namespace

### ISSUE THREAD

**Issue by electricstrm-redgate** [kubernetes/kubernetes#120188]
### What happened?

The following errors happen every few mins in the syslog.  I'm not sure what's going on. 

```
kubelet_pods.go:897] "Unable to retrieve pull secret, the image pull may not succeed." pod="kube-system/local-volume-provisioner-g4shf" secret="" err="secret \"my-app-registry\" not found"
kubelet_pods.go:897] "Unable to retrieve pull secret, the image pull may not succeed." pod="kube-system/csi-smb-node-r5qq5" secret="" err="secret \"my-app-registry\" not found"
kubelet_pods.go:897] "Unable to retrieve pull secret, the image pull may not succeed." pod="kube-system/snapshot-controller-84f7b9d567-z6d7j" secret="" err="secret  \"my-app-registry\" not found"
```

The secret is for an registry image we pull for pod. The secret and the pod that uses the secret at not in the kube-system namespace.  When we use the image in the deployment it was meant to be in, it works.  It seems to be related to volumes, since the pods from kube-system are volume related.

When i create the secret in kube-system, the messages stop.  What's going on ? 

### What did you expect to happen?

No errors messages.

### How can we reproduce it (as minimally and precisely as possible)?

Using kubernetes 1.25.4
Image is registry:2.8.2
Secret is of type kubernetes.io/dockerconfigjson
Create a volume

### Anything else we need to know?

These are the volumes we use. 
1. Registry-certs is just a secret mounted as a volume.
2. registry-data is where all the registry images are saved.  The PV is using the default storage class.
4. just an empty dir
5. Volume mounted for kube api access.  The pod is on the default service account.

  volumes:
  - name: registry-certs
    secret:
      defaultMode: 420
      secretName: platform-tls
  - name: registry-data
    persistentVolumeClaim:
      claimName: registry-pvc
  - emptyDir: {}
    name: auth-dir
  - name: kube-api-access-9gfmj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Azure VM 
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION_ID="22.04"
$ uname -a
Linux ubuntu 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
kurl.sh
</details>

### Container runtime (CRI) and version (if applicable)

<details>
  containerd version: "1.6.9"
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
  flannel version: "0.21.5"
</details>

**Comment by electricstrm-redgate** [comment]
I think this ticket should probobly be in the csi snapshot controller github repo.  I wasn't aware of a separate repo when i initially wrote it.
https://github.com/kubernetes-csi/external-snapshotter

**Comment by zhucan** [comment]
what's pod config the "my-app-registry"?

**Comment by jsafrane** [comment]
From the error message it seems that your CSI driver pods have configured a pull secret that does not exist. I don't see anything storage releated here. How did you install the CSI driver? Do its pods have `spec.imagePullSecrets` and if so, then why?
/triage needs-information
