### ISSUE TITLE
Pods are stuck in NotReady after node becomes notReady for few seconds

### ISSUE THREAD

**Issue by AndyEWang** [kubernetes/kubernetes#120256]
### What happened?

Some Pods are stuck in NotReady status after related node becomes not ready for few seconds and then is healthy again.
From kube-controller-manager logs, pods won't be evicted and are still running.
Give one Pod for example.
```
I0828 07:00:00.435121       1 controller_utils.go:140] Updating ready status of pod eeeeee1-79dd69d57c-g6spv to false
I0828 07:00:00.535153       1 event.go:291] "Event occurred" object="edgetest-edge/eeeeee1-79dd69d57c-g6spv" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"

I0828 07:00:31.843751       1 node_lifecycle_controller.go:893] Node vm-node-229-106 is healthy again, removing all taints
I0828 07:00:31.845457       1 event.go:291] "Event occurred" object="edgetest-edge/eeeeee1-79dd69d57c-g6spv" kind="Pod" apiVersion="" type="Normal" reason="TaintManagerEviction" message="Cancelling deletion of Pod edgetest-edge/eeeeee1-79dd69d57c-g6spv"
```
```
# kubectl get pod eeeeee1-79dd69d57c-g6spv -n edgetest-edge -o yaml
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T10:59:59Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-28T07:00:00Z"
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T11:00:19Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T10:59:58Z"
    status: "True"
    type: PodScheduled
```
Also there are some Ready Pods in this node.

no any other useful info from kubelet except the pod creation logs. Guess that kubelet never gets a chance to run status_manager.syncPod.

### What did you expect to happen?

Pods should recover and become Ready as soon as node is healthy again.

### How can we reproduce it (as minimally and precisely as possible)?

Not sure if this can reproduce. In my env, the node suddenly cannot access apiserver and become not ready for few seconds. All its Pods become notReady. Then it's healthy again and all Pods keep running. But some Pods cannot recover Ready status.

### Anything else we need to know?

To stop container can help force kubelet to sync status again.

Something is weird for those Ready Pods. Give Pod eeeeee1-79dd69d57c-8tb96 as example. KCM set it NotReady on 08/28.
```
I0828 06:59:57.481073       1 controller_utils.go:140] Updating ready status of pod eeeeee1-79dd69d57c-8tb96 to false
I0828 06:59:57.556615       1 event.go:291] "Event occurred" object="edgetest-edge/eeeeee1-79dd69d57c-8tb96" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
```

But its Ready lastTransitionTime (08/25) never changes.
```
# kubectl get pod  -n edgetest-edge -o yaml eeeeee1-79dd69d57c-8tb96
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T11:20:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T11:20:21Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T11:20:21Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-08-25T11:20:01Z"
    status: "True"
    type: PodScheduled

```

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"archive", BuildDate:"2022-02-24T10:16:40Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9", GitCommit:"6df4433e288edc9c40c2e344eb336f63fad45cd2", GitTreeState:"archive", BuildDate:"2022-05-17T10:19:42Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

no

**Comment by aojea** [comment]
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.9",

that version is EOL, please use a new and supported version and report back https://kubernetes.io/releases/

**Comment by AndyEWang** [comment]
I'm afraid no upgrade is planned in the near future. But could you please help point out what information can be collected if it happens again. Is it enough to change kubelet logging level to 3?
Thanks.

FYI. I tried to manually make node notready and ready again. But it didn't reproduce.

**Comment by mmiranda96** [comment]
@AndyEWang even if you don't plan on upgrading, could you try to reproduce on a newer version? Kubelet log level 3 should provide us enough info.

**Comment by AndyEWang** [comment]
@mmiranda96 Thanks for your reply. I have changed kubelet logging level. But unfortunately, I didn't see this problem again in the past few weeks.
I think this issue can be closed now. And when it happens again, I will reopen this issue.
