### ISSUE TITLE
storage fuse process managed by pod/container cgroup

### ISSUE THREAD

**Issue by smileusd** [kubernetes/kubernetes#120299]
### What would you like to be added?

fuse process's cpu/memory also should be added into the pod and container cgroup limit.

### Why is this needed?

Glusterfs volume, for example, the fuse process's parent process is 1. So it not add into the pod or container cgroup. But when large IO into the volume, the fuse process also using many memory and cpu:
//top  
13143 root      20   0 9302628   3.7g   6960 S  30.2   1.0  32960:40 glusterfs                                                                                                                                                                   
//cat /proc/13143/status  |grep -i rss
VmRSS:   3877220 kB
RssAnon:         3870260 kB
RssFile:            6960 kB
RssShmem:              0 kB

Due to these resource not added into cgroup limit. That might impact pod schedule and eviction.

**Comment by msau42** [comment]
We addressed this in the GCSFuse CSI project by running the fuse process as a sidecar container in the Pod. It does have some tradeoffs, such as not being able to share mounts across Pods in the same node, and needing annotations to facilitate sidecar injection, and depending on the new sidecar containers feature, but it solves the major issues of how to account the resource usage of the fuse process to the Pod and manage the lifecycle of the fuse process.

More details:
https://www.youtube.com/watch?v=HntbxWLVMso
https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver
