### ISSUE TITLE
should workload-high has more shares than workload-low?

### ISSUE THREAD

**Issue by silenceshell** [kubernetes/kubernetes#120238]
### What happened?

In my k8s cluster(1.22), the `workload-high` prioritylevelconfiguration has 40 shares and the `workload-low` has 100 shares. Is this correct? I think the `workload-high` should has more shares.

```
# kubectl get prioritylevelconfiguration
NAME              TYPE      ASSUREDCONCURRENCYSHARES   QUEUES   HANDSIZE   QUEUELENGTHLIMIT   AGE
catch-all         Limited   5                          <none>   <none>     <none>             161d
exempt            Exempt    <none>                     <none>   <none>     <none>             161d
global-default    Limited   20                         128      6          50                 161d
leader-election   Limited   10                         16       4          50                 161d
node-high         Limited   40                         64       6          50                 161d
system            Limited   30                         64       6          50                 161d
workload-high     Limited   40                         128      6          50                 161d
workload-low      Limited   100                        128      6          50                 161d
```

### What did you expect to happen?

`workload-high` has more shares than `workload-low`

### How can we reproduce it (as minimally and precisely as possible)?

run `kubectl get prioritylevelconfiguration` on cluster whose version is above 1.22

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-alpha.0.3567+7fca6d40c55063-dirty", GitCommit:"7fca6d40c55063fd9d52a13024ffc6fd6e8ba499", GitTreeState:"dirty", BuildDate:"2023-03-16T10:10:00Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-alpha.0.3573+d2716e40089a45-dirty", GitCommit:"d2716e40089a4511afc200403e19b40db235f2bf", GitTreeState:"dirty", BuildDate:"2023-03-28T11:17:32Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
NA
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Tencent Linux"
VERSION="2.4"
ID="tlinux"
ID_LIKE="rhel fedora centos"
VERSION_ID="2.4"
PRETTY_NAME="Tencent Linux 2.4"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tlinux:linux:2"
HOME_URL="https://tlinux.qq.com/"
$ uname -a
Linux tcs-10-28-15-63 5.4.119-19-0008 #1 SMP Mon Sep 13 14:54:39 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by alexzielenski** [comment]
Does this affect any other k8s versions? 1.22 used beta3 of priority and fairness IIRC and is out of support sine 28 Feb 2023

**Comment by silenceshell** [comment]
yes, this affect all k8s versions.
we could find the value defined here:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/apis/flowcontrol/bootstrap/default.go#L229

**Comment by wojtek-t** [comment]
Yes - this is expected.
Workload-high is supposed to be used for high-priority requests, and there aren't that many of those. Workload-low is catching many more requests, and thus by design should have more shares.

**Comment by silenceshell** [comment]
thanks @wojtek-t
