### ISSUE TITLE
kube-proxy conntrack configuration should support UDP timeouts

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#120214]
### What would you like to be added?

**KubeProxyConntrackConfiguration** should support UDP conntrack settings. 
**KubeProxyConntrackConfiguration** supports TCP conntrack settings and setting conntrack timeout for UDP connections is currently a manual and tiresome process.

### Why is this needed?

Currently configuring `nf_conntrack_udp_timeout` and `nf_conntrack_udp_timeout_stream` is a manual step, and since we already support **KubeProxyConntrackConfiguration**, we can add **UDPTimeout** and **UDPStreamTimeout** fields. 

https://github.com/kubernetes/kubernetes/blob/029d5189701fab73e450158234a0aa81f659f3c7/pkg/proxy/apis/config/types.go#L78-L92 

https://github.com/kubernetes/kubernetes/issues/120076#issuecomment-1693822046

**Comment by cyclinder** [comment]
Is it just for ipvs or iptables , or both?

**Comment by aroradaman** [comment]
for both, both of them uses netfilter conntrack

**Comment by khenidak** [comment]
I think this one is a valid if not for anything other than to maintain parity between TCP and UDP settings surfaced in config.

**Comment by aroradaman** [comment]
just thinking out loud here, should we also add an option for configuring `nf_conntrack_tcp_be_liberal` ?
Historically users have enabled this sysctl to solve some of their network issues.

**Comment by aroradaman** [comment]
@khenidak I'm already working on this, just figuring out code-generation part.

**Comment by danwinship** [comment]
> just need to figure out code-generation part

`make update` (possibly preceded by `./hack/install-etcd.sh` and modifying your `PATH` as it suggests)

**Comment by thockin** [comment]
Objections to accepting this as a FR ?

**Comment by danwinship** [comment]
/triage accepted
there's already a PR open for it, #120354
