### ISSUE TITLE
Transient Driver Registration on the CSINode can Result in Missed NodeUnstageVolume RPCs During Pod Migration

### ISSUE THREAD

**Issue by rohitssingh** [kubernetes/kubernetes#120268]
### What happened?

In `unmountDetachDevices` (see [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler_common.go#L279-L316)) we have the following code that will ultimately dispatch `NodeUnstageVolume` RPCs to the underlying CSI plugin.

Here is a pseudo-code representation of the current logic:

```
function unmountDetachDevices
	for all unmounted volumes in ASoW
		if volume not in DSoW &&
		   not operation pending on volume
			if device is mounted globally or
			   device is mounted uncertain
				Case A:
				unmount device
				(this will kick off the NodeUnstageVolume RPC; we want to be here)
			else
				Case B:
				just remove volume from ASoW
				(general badness since we don't issue a NodeUnstageVolume RPC)
```

In our testbeds, we have observed a number of occurrences where we fall into `Case B` when the CSI Node plugin for a particular driver is being bounced, which leads to the volumemanager failing to dispatch the `NodeUnstageVolume` RPC. If the pod migrates to another node, this will leave behind a Zombie LUN in our testbeds (we're using iSCSI).

A Zombie LUN can and often does result in corruption when other pods later migrate to the node in question.

Based on testing that we conducted, we discovered that this case occurs because the device is marked as unmounted.

Initially, we see the device marked as uncertain during reconstruction.

However, if the CSI Node driver pod is bounced in the exact window when a `NodeStageVolume` RPC is issued, then we end up [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/util/operationexecutor/operation_generator.go#L777C1-L798C2).

There we check to see if the error encountered is a “transient error” or a “final error”; if a “final error” is encountered, then the device state transitions from uncertain to unmounted. That is what is happening in our case.

The error is generated when the CSIClient cannot find the requested driver [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_client.go#L158C1-L161C3).

The driver registration code is socket based; based on our testing, if the Node plugin goes down for any reason the driver registration is removed from the CSINode.

Now for the `NodePublishVolume` path, this is mitigated by wrapping the error in a transient error [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_mounter.go#L109C3-L109C3) (I assume to avoid such state transitions?):

```
	csi, err := c.csiClientGetter.Get()
	if err != nil {
		return volumetypes.NewTransientOperationFailure(log("mounter.SetUpAt failed to get CSI client: %v", err))
	}
```

Based on our testing to date, adding parity [here](https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/csi/csi_attacher.go#L293C20-L293C20) to the `NodeStageVolume` path would help us avoid Zombie LUNs in our test setups due to missing `NodeUnstageVolume` calls:

```
	// lets check if node/unstage is supported
	if c.csiClient == nil {
		c.csiClient, err = newCsiDriverClient(csiDriverName(csiSource.Driver))
		if err != nil {
			return errors.New(log("attacher.MountDevice failed to create newCsiDriverClient: %v", err))
		}
	}
	csi := c.csiClient
```

This can be fixed by also wrapping this error in a transient error.

### What did you expect to happen?

We expected to see a `NodeUnstageVolume` call coming to the underlying NodePlugin (once it was finally back up).

### How can we reproduce it (as minimally and precisely as possible)?

* Force reconstruction on a node.
* Take down the CSI node plugin on the node while pods are mounting.
* Try to migrate the pod to another node; the underlying machinery will correctly wait for the plugin to come back up before proceeding.
* Later, bring up the CSI node plugin.
* While the pod migration might be successful, a `NodeUnstageVolume` should be missing if the correct timing windows were hit.

### Kubernetes version

<details>

```console
root@bootstrapper:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4-gke.500", GitCommit:"a955253697d6572565777f63dfe6df9fd74591a2", GitTreeState:"clean", BuildDate:"2023-07-26T09:27:11Z", GoVersion:"go1.20.6 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.27) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>
Google
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by rohitssingh** [comment]
/sig Storage

Tagging @bswartz, @msau42, @saad-ali.

**Comment by saad-ali** [comment]
CC @jingxu97 can you PTAL?

**Comment by saad-ali** [comment]
Per @msau42 

> I think it's a relatively simple bug
> NodeStageVolume is treating csi driver missing as a final error instead of a transient error
> NodePublishVolume is properly handling the error

Per @rohitssingh 

> exception for NodeStageVolume was added in #82492

CC @gnufied
