### ISSUE TITLE
Add the skip return status support for PreEnqueue, and won't run PreFilter if PreEnqueue returned a Skip status

### ISSUE THREAD

**Issue by zhuqi-lucas** [kubernetes/kubernetes#120237]
### What would you like to be added?

Add the skip return status support for PreEnqueue, and won't run PreFilter if PreEnqueue returned a Skip status

### Why is this needed?

We have skip status for PreFilter to return, and when we skip prefilter, the following filter will not run, but we don't have skip choice for PreEnqueue, we'd better add this. 

After we support this:
When we skip for the preEnqueue, we can skip add the pod to activeQueue, it's more reasonable and saving time for plugin customer scheduler to optimize.

**Comment by AxeZhan** [comment]
See #114297 and #110175 . We have `skip` in QueueingHint, I think we can replace `PreEnqueue` after all plugins implement the `QueueingHint`

**Comment by kerthcet** [comment]
So generally **Skip** works for a pair of extension points, like we get `Skip` in `PreFilter`, then we'll skip `Filter` stage. On your case, I think you don't need `skip` at all because if you `PreEnqueue` plugin returns status other than `Success`, you pod will be blocked into the activeQ already.

**Comment by zhuqi-lucas** [comment]
Thank you @AxeZhan @kerthcet for reply, i am wandering to add skip for this when using scheduling framework to extend the preEnqueue, in some case, we don't need to back into the preFilter and following steps, we want to skip all steps when we skip the preEnqueue.

submit a PR above

**Comment by kerthcet** [comment]
If you pod is blocked by preEnqueue, the pod will not enter into the activeQ, then blocking in the scheduling cycle. Isn't this as you expected?

**Comment by zhuqi-lucas** [comment]
@kerthcet No i want to skip it, don't add it to activeQ, when we skip from preEnqueue.

**Comment by kerthcet** [comment]
I mean right now if your pod is rejected by the PreEnqueue, it will not enter into activeQ, but pending in unschedulablePods.

**Comment by zhuqi-lucas** [comment]
@kerthcet  If we also can skip unschedulablePods for this case, i am not sure if i make sense right, unschedulablePods will come back to active queue to schedule, we want to skip it totally.

**Comment by kerthcet** [comment]
If the pod failed the PreEnqueue, it will never enter into activeQ, see https://kubernetes.io/blog/2022/12/26/pod-scheduling-readiness-alpha/ for more details please.

**Comment by kerthcet** [comment]
Seems we can close this from the previous discussion, any other concerns @zhuqi-lucas

**Comment by zhuqi-lucas** [comment]
We can close it @kerthcet , thank you!
