### ISSUE TITLE
Remove the dependency of HNS in Winkernel KubeProxy Tests by replacing with mock calls.

### ISSUE THREAD

**Issue by princepereira** [kubernetes/kubernetes#120200]
### What happened?

The current tests in WinKernel Kube proxy are dependent on Windows HNS environment. The tests expect HNS to be present and are executed by making real system calls to test environment. This makes testing difficult for the developer to write make test cases as it mandates to have a real Windows Node environment.

### What did you expect to happen?

The proposal is to have a framework which can mock all HCN calls.

### How can we reproduce it (as minimally and precisely as possible)?

Running the testcases in in proxier_test.go in development environment can help to repro the issue.

### Kubernetes version

<details>

```console
$ kubectl version
# 1.29, 1.28
```

</details>

### Cloud provider

<details>
AKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by danwinship** [comment]
In #107471, I added a bunch of unit tests to the iptables proxy which parse the outputs from the Proxier so we can then have tests like:

```
	runPacketFlowTests(t, getLine(), ipt, testNodeIP, []packetFlowTest{
		{
			name:     "cluster IP accepted",
			sourceIP: "10.180.0.2",
			destIP:   "172.30.0.41",
			destPort: 80,
			output:   "10.180.0.1:80",
			masq:     false,
		},
		{
			name:     "hairpin to cluster IP",
			sourceIP: "10.180.0.1",
			destIP:   "172.30.0.41",
			destPort: 80,
			output:   "10.180.0.1:80",
			masq:     true,
		},
	})
```

ie, that tests that according to the current state of the iptables rules in `ipt`, that
- a packet from 10.180.0.2 to 172.30.0.41:80 should be NATted to 10.180.0.1:80 without masquerading
- a packet from 10.180.0.1 to 172.30.0.41:80 should be NATted to 10.180.0.1:80 _with_ masquerading"

I'd like to abstract these a bit and try to share them between the different backends. (In particular, for my work on the nftables backend, I'd like to make sure I'm testing all of the same cases as the iptables tests are.)

I'm envisioning something where like you'd have a unit test that creates a Proxier and a "flow test runner" of the right type for your backend, and then you call something like `proxytesting.TestClusterIP(t, proxier, flowTestRunner)`, and that centralized function calls `OnServiceAdded`, `OnEndpointSliceAdded`, etc, on the proxier to set up the state, then uses the flow test runner object to test out various scenarios like the ones above to make sure they give the right results. And by having these tests in a central shared directory, we'd have more closely-aligned test cases in the different proxies...

Anyway, this is still probably a ways off, but if you implement something like #107471 in winkernel then I (or someone else) can try to pull it into a larger abstraction later...
