### ISSUE TITLE
pod (deployment) keeps its running state on a node that doesn't exists.

### ISSUE THREAD

**Issue by ShaiShalevSQream** [kubernetes/kubernetes#120264]
### What happened?

In a GKE cluster version 1.26.7-gke.500
I have a few deployments. on a node pool
when i delete that node pool, or even all the node pools.
one pod, that is controlled by deployment keeps its running state on a node that does not exist

how can i avoid that?

### What did you expect to happen?

I expect to pod of that deployment to go into pending state as all my other deployments

### How can we reproduce it (as minimally and precisely as possible)?

Im not sure how to reproduce it, since its not something that need to happen

### Kubernetes version

<details>

```console
$ kubectl version
 1.26.7-gke.500```

</details>


### Cloud provider

<details>
GCP
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
Linux pop-os 6.4.6-76060406-generic #202307241739~1690928105~22.04~d567a38 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> GKE cluster version 1.26.7-gke.500

it is best to report to the GKE support first.
if they confirm a k8s bug they can talk to k8s maintainers.

/sig scheduling apps
(unclear)

**Comment by wzshiming** [comment]
In my experience these pods should be deleted by the controller-manager after 5min.
IMO you should have evicted all the pods before deleting the Node.

**Comment by mochizuki875** [comment]
FYI:

> Kubernetes automatically adds a toleration for node.kubernetes.io/not-ready and node.kubernetes.io/unreachable with tolerationSeconds=300, unless you, or a controller, set those tolerations explicitly.
> 
> These automatically-added tolerations mean that Pods remain bound to Nodes for 5 minutes after one of these problems is detected.

Taint based Evictions
https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions
