### ISSUE TITLE
[KMSv2] Drop the apimachinery and client-go dependencies from k8s.io/kms

### ISSUE THREAD

**Issue by nilekhc** [kubernetes/kubernetes#120216]
Drop the `apimachinery` and `client-go` dependencies from https://github.com/kubernetes/kms/blob/master/go.mod to keep the import lighter.

/sig auth
/triage accepted

**Comment by pegasas** [comment]
I would like to work on this issue.
/assign @pegasas

**Comment by enj** [comment]
This will likely require a new go module in https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/kms/internal to move the client-go dep.

https://github.com/kubernetes/kubernetes/blob/e5eaf8189fb510353a8af2f726c54c109d2b294c/staging/src/k8s.io/kms/pkg/service/grpc_service_test.go#L66-L67 is the only API machinery dep so we can probably come up with some way to re-implement the wait logic locally?

**Comment by liggitt** [comment]
Whoa, yeah, I'd take a for loop and a time.Sleep in a test to drop those deps

**Comment by liggitt** [comment]
What is kms using client-go for? Tests only?

**Comment by enj** [comment]
These were all needed by the KMS repo back when we had a much more complicated reference implementation which required a key hierarchy.  Now they are just used in some tests and mock implementations, so we should be able to simplify things.

**Comment by pegasas** [comment]
> What is kms using client-go for? Tests only?

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kms/internal/mock_ratelimit_remote_service.go#L24C1-L24C37 
I found a place for rate limit. #liggitt
