### ISSUE TITLE
[feature request] Service send copies of requests to production and test.

### ISSUE THREAD

**Issue by esecules** [kubernetes/kubernetes#12026]
Sometimes you might want to test out your code on real live production data so it would be nice to be able to have multiple selectors which all receive the same requests.

**Comment by thockin** [comment]
This is an interesting idea.  The first question I get is whether it should
be a facet of Service or a layer above, or some other composition.

**Comment by esecules** [comment]
As a layer above I imagine it would look a lot like a Service except that it replicates over Services instead of load balances over Pods. If it were a facet of services it seems like it would be a small addition of a loop around the function which load balances over the pods in a selector. 

In either case it would spam pods pods in the intersection of tag selection sets with repeat requests.

**Comment by thockin** [comment]
I'm mostly concerned about containing the explosion of feature requests.
Off the top of my head:

* percentage of traffic to send to each Selector
* max requests per time per selector
* policy (round-robin between selectors?)
* copy-traffic vs split traffic

And so on.  If we could find a way to compose (and maybe we can't) then we
can leave room for people who want to implement crazy stuff without US
having be in the way.

**Comment by esecules** [comment]
perhaps all these feature requests could be bundled into an item that can bundle together and limit Services. 

or to facilitate outside development, a framework that takes in requests the same way a Service would and can multiplex, broadcast, queue, deny, etc those requests to other things (according to programmer specified rules) that have the same input interface as Services.

**Comment by thockin** [comment]
This is a job for Istio
