### ISSUE TITLE
unwanted_modules: github.com/gorilla/... appear active again

### ISSUE THREAD

**Issue by vbatts** [kubernetes/kubernetes#120307]
recently [the `github.com/gorilla/...` project post an update](https://gorilla.github.io/blog/2023-07-17-project-status-update/), and un-archived all the projects.

These projects have all been listed on the [`unwanted_modules.json`]([a5fff9a](https://github.com/kubernetes/kubernetes/commit/a5fff9a5d09422cb8632777d797b809595374b87)) (commit is HEAD at the time of this issue).

It appears most references are now gone, with only a few remaining to `github.com/gorilla/websocket`.

Depending on how the Gorilla project stabilizes itself, perhaps these entries can be removed from the unwanted_modules file.

/kind cleanup

**Comment by pacoxu** [comment]
The related PR: https://github.com/kubernetes/kubernetes/pull/114408. /cc @liggitt @dims

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/pull/119186 is actually planning to start using it and will drop it from unwanted-dependencies

/assign @seans3

**Comment by pacoxu** [comment]
> #119186 is actually planning to start using it and will drop it from unwanted-dependencies
> 
> /assign @seans3

#119186 finally doesn't use the gorilla package.

@seans3 @liggitt does this issue still needed?

**Comment by liggitt** [comment]
It is used in client-go now, and was dropped from unwanted-dependencies in https://github.com/kubernetes/kubernetes/commit/a0d6a815fcc02cbfea1bb22d13a8e896ecbe116c
