### ISSUE TITLE
all the pods status are pending in my environment 

### ISSUE THREAD

**Issue by shixinlishixinli** [kubernetes/kubernetes#120378]
### What happened?

i follow this document to set k8s environment (https://github.com/kubernetes/community/blob/master/contributors/devel/development.md), 

i want to use this new feature : Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha) (https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/)

this is the environment , all the pod is pending . and i can not find the reason 

lisa@lisa:~/go/src/k8s.io/kubernetes$ ./cluster/kubectl.sh  get pod -n kube-system
NAME                     READY   STATUS    RESTARTS   AGE
coredns-886dd9fc-6gd2f   1/1     Running   0          81m

lisa@lisa:~/go/src/k8s.io/kubernetes$ ./cluster/kubectl.sh  get pod
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-679d7c68d6-c94x7   0/1     Pending   0          52m
nginx-deployment-679d7c68d6-s6vsl   0/1     Pending   0          52m
testpod                             0/1     Pending   0          45m

do you have any suggestions to solve this problem?
Best
Lisa Shi

### What did you expect to happen?

i can successfully set the pod in my k8s environment 

### How can we reproduce it (as minimally and precisely as possible)?

i follow this document to set k8s environment (https://github.com/kubernetes/community/blob/master/contributors/devel/development.md), 

i want to use this new feature : Kubernetes 1.27: In-place Resource Resize for Kubernetes Pods (alpha) (https://kubernetes.io/blog/2023/05/12/in-place-pod-resize-alpha/)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
v1.29.0-alpha
</details>

### Cloud provider

<details>

</details>
none

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

also in this case #sig-node on k8s slack.

/kind support
/close

**Comment by neolit123** [comment]
if the maintainers confirm a bug, please reopen this issue.
