### ISSUE TITLE
error message need improve: failed to create daemonSet due to invalid resources definition

### ISSUE THREAD

**Issue by cyclinder** [kubernetes/kubernetes#120342]
### What happened?

```
root@controller:~/cyclinder# cat << EOF | kubectl apply -f -
> apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: ""
            memeory: ""
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
> EOF
Error from server (BadRequest): error when creating "STDIN": DaemonSet in version "v1" cannot be handled as a DaemonSet: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

### What did you expect to happen?

I hope kubectl can return an appropriate error message

### How can we reproduce it (as minimally and precisely as possible)?

```
root@controller:~/cyclinder# cat << EOF | kubectl apply -f -
> apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: ""
            memeory: ""
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
> EOF
Error from server (BadRequest): error when creating "STDIN": DaemonSet in version "v1" cannot be handled as a DaemonSet: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by Devesh-N** [comment]
@cyclinder 
The error message quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$' indicates that the Kubernetes DaemonSet object is expecting resource quantities for CPU and memory to match a specific pattern, but they are empty in your definition. Also, there is a typo in the word memory.

Here's how you can fix it:

Provide values for the CPU and memory in the resource requests section.
Correct the typo memeory to memory.
Here is your YAML file with the suggested corrections:

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: "100m"  # 100 millicores
            memory: "64Mi"  # 64 MiB
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
You can adjust the CPU and memory values ("100m" and "64Mi") as per your requirements. Note that these are just example values.

**Comment by Ritikaa96** [comment]
@cyclinder I think the error message is appropriate. 
What detail would you like to see added in this log message, Any suggestions for improvement of the log message are welcome as long as they are valid.
Also,I hope the above explanation solved your error.

**Comment by brianpursley** [comment]
/close

We can re-open if there is more information about what specific change is requested
