### ISSUE TITLE
External GCE cloud provider has trouble with kubelet(s) in worker nodes joining the control plane node

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#120387]
Logs look like:
```
Sep 02 00:46:52.046603 bootstrap-e2e-minion-group-15cv kubelet[10550]: E0902 00:46:52.046567   10550 run.go:74] "command failed" err="failed to run Kubelet: cannot create certificate signing request: certificatesigningrequests.certificates.k8s.io is forbidden: User \"kubelet\" cannot create resource \"certificatesigningrequests\" in API group \"certificates.k8s.io\" at the cluster scope"
```

originally mentioned in https://github.com/kubernetes/kubernetes/pull/117503#issuecomment-1703667872

started a WIP PR to recreate, please see: https://github.com/kubernetes/kubernetes/pull/120386

/sig cloud-provider
/sig testing

cc @aojea @elmiko @andrewsykim

**Comment by aojea** [comment]
added more comments on the original issue, it may be possible that error is a symton and the root cause is on the installation process

https://github.com/kubernetes/kubernetes/pull/117503#issuecomment-1704251209

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/pull/120389
