### ISSUE TITLE
Improve logging on kube-proxy exit

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#120355]
There are some cases when kube-proxy has to exit and restart, in order to do that we panic, but this has the problem that the log output shows a literal "panic" message and engineers, support, customers and automation gets confused, thinking that is a problem when is the expected behavior.

As suggested by @pohly in https://github.com/kubernetes/kubernetes/commit/a38b9363ec3f0c10bb6e6ebc47d731d6c88ae03f#r126178773
 , we can replace `panic` by `klog.FlushAndExit` 

/sig network
/help
/kind cleanup

**Comment by pegasas** [comment]
/assign @pegasas 
I would like to raise a PR to fix this.
