### ISSUE TITLE
 job constantly failing on ReplicaSet and ReplicationController tests

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#120391]
### Which jobs are failing?

> **pull-kubernetes-e2e-gci-gce-ipvs** 

pull-kubernetes-e2e-gce-correctness

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120389/pull-kubernetes-e2e-gce-correctness/1698401238044905472

### Which tests are failing?

> [sig-apps] ReplicaSet should serve a basic image on each replica with a private image
> [sig-apps] ReplicationController should serve a basic image on each replica with a private image

### Since when has it been failing?

Sept 1st

### Testgrid link

https://testgrid.k8s.io/sig-network-gce#presubmit-network-ipvs,%20google-gce

### Relevant SIG(s)

/sig network

**Comment by aojea** [comment]
checking the time of failure, probably a consequence of https://groups.google.com/a/kubernetes.io/g/dev/c/VG7kUzRYaY4/m/rpvzlWTIAgAJ , however, I can't understand why only those two tests

**Comment by aojea** [comment]
hmm

```
Sep  3 08:04:10.976: INFO: At 2023-09-03 07:59:12 +0000 UTC - event for my-hostname-private-2c7dd604-0b48-49c6-a234-e5be1e6d650d-4bwcl: {kubelet bootstrap-e2e-minion-group-sdwj} Failed: Failed to pull image "gcr.io/k8s-authenticated-test/agnhost:2.6": failed to pull and unpack image "gcr.io/k8s-authenticated-test/agnhost:2.6": failed to resolve reference "gcr.io/k8s-authenticated-test/agnhost:2.6": unexpected status from HEAD request to https://gcr.io/v2/k8s-authenticated-test/agnhost/manifests/2.6: 401 Unauthorized
Sep  3 08:04:10.976: INFO: At 2023-09-03 07:59:12 +0000 UTC - event for my-hostnam
```

@andrewsykim @BenTheElder  does this ring a bell,  `Failed to pull imag` on this test?

**Comment by aojea** [comment]
it fails on others too pull-kubernetes-e2e-gce-correctness, definitively something related to the change on external cloudproviders, cc @dims

**Comment by dims** [comment]
@aojea fix is in https://github.com/kubernetes/kubernetes/pull/120392

**Comment by shaneutt** [comment]
It looks like this is fixed, so we're going to consider it as such for now.

/close

Please let us know if there is any work remaining that needs to be done and we can re-open this if required.
