### ISSUE TITLE
 customize the storage directory of /var/lib/kubelet 

### ISSUE THREAD

**Issue by long1318737396** [kubernetes/kubernetes#120394]
### What happened?

Can you customize the storage directory of /var/lib/kubelet during installation? Sometimes /var/lib/kubelet is stored in the / directory by default, but the actual environment system disk and data disk are separated, such as when kubelet starts When you want to store data in /data/kubelet

### What did you expect to happen?

no

### How can we reproduce it (as minimally and precisely as possible)?

no

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
you can use --root-dir
https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

but note kubeadm does not support a custom dir and there are no plans for it. you can try with a symlink.

/kind support
/close
