### ISSUE TITLE
When max-pods count is set on a node , how to get the list of pods (or) pod status that are considered in that limit?

### ISSUE THREAD

**Issue by Koulini** [kubernetes/kubernetes#120333]
### What happened?

I have a system with max-pods count set to 100 on a node.There are pods with different status like Running/NodeAffinity/Completed/Terminating etc on the system.

Observed that pods with NodeAffinity and Completed status are not considered in the pods count.

1.Is there a way to get the list of pods that are considered by k3s for limiting the pods?
2.Does k3s limit the creation of new pods by counting the pods with certain status like Running/Unknown? If yes, what statuses will be considered?

$ k3s --version
k3s version v1.21.1+k3s-2d1556d1-dirty (2d1556d1)
go version go1.15.2

Response from k3s team - https://github.com/k3s-io/k3s/discussions/8286#discussioncomment-6878859

### What did you expect to happen?

Irrespective of the status of pod, each pod should be accounted to max-pods count. 

Since its not the behaviour.would like to know below details.
1.Is there a way to get the list of pods that are considered by k3s for limiting the pods?
2.Does k3s limit the creation of new pods by counting the pods with certain status like Running/Unknown? If yes, what statuses will be considered?

### How can we reproduce it (as minimally and precisely as possible)?

Add max-pods limit to nodes.Create pods with different statuses.Like crashloopbackoff/Unknown/NodeAffinity etc statuses.Check what pods are considered in the pod limit.

### Kubernetes version

<details>

```console
$ # kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s-2d1556d1-dirty", GitCommit:"2d1556d1a405f353e7a2ec05413ad0bee6ae19bd", GitTreeState:"dirty", BuildDate:"2023-07-11T07:39:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s-2d1556d1-dirty", GitCommit:"2d1556d1a405f353e7a2ec05413ad0bee6ae19bd", GitTreeState:"dirty", BuildDate:"2023-07-11T07:39:07Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Local hardware
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux myhost 3.10.0-1160.71.1.F5.1.el7_8.x86_64 #1 SMP Tue Feb 14 12:21:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
Code level: It counts the user namespaces that are created for pod.

https://github.com/kubernetes/kubernetes/blob/34aaf2b972c95c7a3591d8d49c798dba348ee5c9/pkg/kubelet/userns/userns_manager.go#L240-L242

Logically, it counts running pods only. The running pod means a Pod with a successfully created sandbox with a new user namespace. If I understand it correctly,
- For a pod in terminating status, the sandbox may not be deleted yet, but it should be in the deleting process.
- For `Completed` pod, it should not be counted.

/sig node

To set a proper max pod, I would suggest setting a higher value that the node can hold. (Some background: since v1.27, we bump the API QPS and burst for kubelet in https://github.com/kubernetes/kubernetes/pull/116121, and the node can hold more pods than before. Before that, users may encounter volume mount timeout for API QPS limit on the kubelet side.)

**Comment by pacoxu** [comment]
A simple way to get that may be 
```
 crictl pods
```
or 
```
crictl ps | grep Running
```

**Comment by Devesh-N** [comment]
Hello @Koulini 

Thank you for raising this issue. Let's try to answer your questions:

Question 1: Is there a way to get the list of pods that are considered by k3s for limiting the pods?
You can list all the pods running on a specific node using the following command:

bash
Copy code
kubectl get pods --all-namespaces -o wide | grep <NODE_NAME>
However, to determine which of these are counted towards the max-pods limit, you might need to look into K3s logs or consult the Kubernetes API directly.

Question 2: Does k3s limit the creation of new pods by counting the pods with certain status like Running/Unknown? If yes, what statuses will be considered?
In standard Kubernetes, the max-pods limit counts all pods except those in a Succeeded or Failed phase. However, K3s is a lightweight distribution and could vary in its implementation. I recommend checking K3s server logs for more information:

bash
Copy code
journalctl -u k3s
Additional Steps:
Describe Node: For more insights into node conditions and statuses, run:

bash
Copy code
kubectl describe node <NODE_NAME>
Check Documentation and Issue Tracker: It may be helpful to consult the official K3s documentation and issue tracker for any specifics related to max-pods.

Version Information: You're using a version of K3s with a -dirty suffix, which implies a development or custom build. Consider upgrading to an official release for more predictable behavior
