### ISSUE TITLE
pull-kubernetes-integration: k8s.io/kubernetes/test/integration/scheduler: TestRequeueByBindFailure

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#120363]
### Which jobs are flaking?

pull-kubernetes-integration: k8s.io/kubernetes/test/integration: scheduler

### Which tests are flaking?

TestRequeueByBindFailure
```
    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
```

Running with stress reproduces the flake

```
go test -c ./test/integration/scheduler
stress ./scheduler.test -test.run TestRequeueByBindFailure
...
grep _test /var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-*
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-2919326582:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-3259000657:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
/var/folders/37/ns7gt60104scfm9fvg02p1jh00kjgb/T/go-stress-20230901T124754-4130805400:    queue_test.go:494: Expect pod-1 to be rejected by the bind plugin
```

### Since when has it been flaking?

Not sure, seeing a lot of retests on pull-kubernetes-integration

Bind logic in scheduler integration tests just changed 3 days ago in https://github.com/kubernetes/kubernetes/pull/114717, not sure if that's related 

### Anything else we need to know?

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/batch/pull-kubernetes-integration/1697624577007423488

### Relevant SIG(s)

/sig scheduling
/priority important-soon

cc @alculquicondor @kerthcet

**Comment by alculquicondor** [comment]
I doesn't look related to the latest change

https://storage.googleapis.com/k8s-triage/index.html?pr=1&text=TestRequeueByBindFailure&job=pull-kubernetes-integration

@sanposhiho you were also looking at Bind. Any ideas?

**Comment by sanposhiho** [comment]
This test is very straightforward:
1. When the first try to bind "pod-1", the Pod is rejected by the binding plugin. ([ref](https://github.com/kubernetes/kubernetes/blob/master/test/integration/scheduler/queue_test.go#L527))
2. The scheduling queue puts back this "pod-1" to activeQ/backoffQ directly, and "pod-1" will soon come back to the scheduling cycle.
3. When the second try to bind "pod-1", it's successful.

And, `queue_test.go:494: Expect pod-1 to be rejected by the bind plugin` means that (1) doesn't reject "pod-1" correctly. And I don't have any idea why it can happen. 
The only scenario I can think of is that there is somehow another Pod created before pod-1.

When `InitTestAPIServer` is executed [here](https://github.com/kubernetes/kubernetes/blob/6586296afc1484067b4633fa7350119c29e8f90a/test/integration/scheduler/queue_test.go#L469), is it possible that any other Pods (like system ones) are created automatically?

**Comment by pacoxu** [comment]
/triage accepted
current top flake of integration

**Comment by sanposhiho** [comment]
/assign

I've got one possible scenario, will have a quick fix.
