### ISSUE TITLE
Many Completed pods appear

### ISSUE THREAD

**Issue by Zruto** [kubernetes/kubernetes#120343]
This happens on my k8s cluster. When too many tasks are submitted (these tasks usually take up a lot of CPU and memory), many pods in the Completed state cannot be recycled. What is the reason?Is it due to resource limitations?  Is there any way to fix it?
![img_v2_7484e0b4-324b-4620-acbb-f2b3257864cg](https://github.com/kubernetes/kubernetes/assets/46238825/d28bb8f4-287a-45ea-be57-ad91220358d2)

**Comment by pacoxu** [comment]
/kind support 
/sig apps

If you are using cronjob, the `.spec.successfulJobsHistoryLimit` and `.spec.failedJobsHistoryLimit` fields help to limit the job number, and the cronjob controller will recycle jobs accordingly.
In your description, I think the job creator has the responsibility to do garbage collection after creating those jobs. However, I cannot figure out what controller/creator you are using.

**Comment by Anianonymous** [comment]
> This happens on my k8s cluster. When too many tasks are submitted (these tasks usually take up a lot of CPU and memory), many pods in the Completed state cannot be recycled. What is the reason?Is it due to resource limitations? Is there any way to fix it?

Reasons are :
misconfigurations in jobs.
resource limitations.

Solutions are :
deleting the deployments.
scaling down and up replica count.

**Comment by pranav-pandey0804** [comment]
hi @Zruto hope this discussion helped you,
If not then You might want to seek help on [Server Fault](https://serverfault.com/questions/tagged/kubernetes), or post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes forum](https://discuss.kubernetes.io/). These are better places for support requests than GitHub.

**Comment by pranav-pandey0804** [comment]
@Zruto please close the issue, thanks!
