### ISSUE TITLE
addon-manager image is in trouble

### ISSUE THREAD

**Issue by farcop** [kubernetes/kubernetes#120364]
### What happened?

https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager

This image must be multiarchitecture:
```
% docker manifest inspect --verbose registry.k8s.io/addon-manager/kube-addon-manager:v9.1.7 | grep architecture
			"architecture": "amd64",
```
Nope. Its linux/amd64

This image must be linux/arm64:
```
% docker manifest inspect --verbose registry.k8s.io/addon-manager/kube-addon-manager-arm64:v9.1.7 | grep architecture  
			"architecture": "amd64",
% docker run --entrypoint /bin/bash --platform linux/amd64 -it registry.k8s.io/addon-manager/kube-addon-manager-arm64:v9.1.7
root@5e79b084b8ec:/# uname -a
Linux 5e79b084b8ec 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64 GNU/Linux
```
Nope. Manifest shows its linux/amd64 But inside its arm64.

Please, give us multiarchitecture image! and fix monoarchitecture images too!

### What did you expect to happen?

We got multiarchitecture image of addon-manager

### How can we reproduce it (as minimally and precisely as possible)?

See above

### Kubernetes version

N/A

### Cloud provider

N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
anything under the /cluster directory is for internal k8s usage / tests and externally users must not use it.
you are going to have to build the addon manager for arm64. support and PRs for it will generally will not be accepted.

https://github.com/kubernetes/kubernetes/tree/master/cluster#cluster-configuration

> This directory has entered maintenance mode

/close
