### ISSUE TITLE
Failed test Namespaces [Serial] should apply changes to a namespace status [Conformance]

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#120478]
### Which jobs are failing?

https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master

### Which tests are failing?

 [It] [sig-api-machinery] Namespaces [Serial] should apply changes to a namespace status [Conformance] 

### Since when has it been failing?

Since https://github.com/kubernetes/kubernetes/pull/119459

### Testgrid link

https://testgrid.k8s.io/conformance-all#Conformance%20-%20GCE%20-%20master

### Reason for failure (if possible)

Change on the assertions semantics?

### Relevant SIG(s)

/sig api-machinery
/sig testing

**Comment by aojea** [comment]
/assign @carlory @pohly 

https://github.com/kubernetes/kubernetes/pull/119459
This test is critical as it is in the conformance suite

**Comment by Vyom-Yadav** [comment]
FYI:
The following tests are also failing:
- master informing
  - [Conformance - EC2 - master](https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20master)
  - [Conformance - EC2 - arm64 - master](https://testgrid.k8s.io/sig-release-master-informing#Conformance%20-%20EC2%20-%20arm64%20-%20master)
- master-blocking
   - [conformance-ga-only](https://testgrid.k8s.io/sig-release-master-blocking#conformance-ga-only)

**Comment by carlory** [comment]
@Vyom-Yadav It should be resolved by #120479
