### ISSUE TITLE
alpha feature gate: LegacyServiceAccountTokenCleanUp token referenced by pod still be cleaned

### ISSUE THREAD

**Issue by rxwang662001** [kubernetes/kubernetes#120447]
### What happened?

Generated serviceaccount, secret with long-lived token, and pod with this serviceaccount
enable this feature gate and found after legacy-service-account-token-clean-up-period this secret still be cleaned.
In controller manager log, could see
```
I0906 01:59:13.727397       1 legacy_serviceaccount_token_cleaner.go:186] "Delete auto-generated service account token" secret="wrxtest/sa-with-pod-token" creationTime="2023-09-04 07:46:11 +0000 UTC" lastUsed="2023-09-04"
```

This isn't consistent with 1.28 release note:
```
kube-controller-manager: The LegacyServiceAccountTokenCleanUp feature gate is now available 
as alpha (off by default). When enabled, the legacy-service-account-token-cleaner 
controller loop removes service account token secrets that have not been used in the time 
specified by --legacy-service-account-token-clean-up-period (defaulting to one year), and 
are referenced from the .secrets list of a ServiceAccount object, and are not referenced 
from pods.
```

### What did you expect to happen?

expect result consistent with release note stated

### How can we reproduce it (as minimally and precisely as possible)?

as said in issue description

### Kubernetes version

<details>

```console
$ kubectl version
# kubectl version
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1

```

</details>

### Cloud provider

<details>
self installed
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
Can you provide your `kube-controller-manager` invocation? The feature gate is off by default, and the controller loop that log line comes from only starts if the feature gate is enabled.

**Comment by liggitt** [comment]
sorry, I misunderstood the report... you intentionally enabled the feature gate, and it is not doing what you expected

**Comment by liggitt** [comment]
@yt2985, can you take a look?

**Comment by yt2985** [comment]
Hi @rxwang662001, may I know how did you generate the service account , secret and the pod? Does the secret has the servicaccount annotation? And has the secret is mounted with the pod? Did you change any default flag value when you enable the cleaner? I am trying to elucidate what happened. It's strange that if the secret is not the autogenerated token, it should not be cleaned. If you can provide more information for me to debug, that would be helpful! Thank you very much!

**Comment by yt2985** [comment]
The autogenerated serviceaccount token needs to mount to the pod before it can be used by the pod, like shown in the link line: https://github.com/yt2985/kubernetes/blob/595a57940a45f25bad4621548ee990c81779c12e/pkg/controller/serviceaccount/legacy_serviceaccount_token_cleaner_test.go#L106 I guess you just add the service account annotation to the pod, but not mount the secret itself. Besides this, I am also curious the legacy-service-account-token-clean-up-period value you used to enable the cleaner. It looks the secret was deleted at the same day as it was created.

**Comment by rxwang662001** [comment]
@yt2985 
May you check the first bug I reported in https://github.com/kubernetes/kubernetes/issues/120298 which wasn't answered, this one is a follow-up to report new issue.

1) I generated a long-live token for the service account referring to https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount
, then it has same  "type: kubernetes.io/service-account-token" as default created secret, that's why it could be cleaned I think.

2) with same method I created two serviceaccount, one is referred to in pod, one isn't, but both of them were cleaned, that's why I reported this bug.

3) no, the clean happened just 1 day after, that's why I asked in https://github.com/kubernetes/kubernetes/issues/120298 
"since DefaultCleanerSyncInterval = 24 * time.Hour, the cleaner works every 24 hours?"

**Comment by yt2985** [comment]
Hi @rxwang662001，I replied in https://github.com/kubernetes/kubernetes/issues/120298, there may be something wrong with the cleaner policy, I will check that. For the third point, the cleaner works every 24 hours and we don't have a way to changes. And I saw you set `--legacy-service-account-token-clean-up-period=1h` when you enabled the cleaner, so once the cleaner works, the token will be deleted. This is the expected behavior. If you don't change the `--legacy-service-account-token-clean-up-period`, the default value is one year. In beta, we will not delete the token directly, instead, we will make it invalid first. You may refer the KEP doc here: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/2799-reduction-of-secret-based-service-account-token#legacyserviceaccounttokencleanup

**Comment by yt2985** [comment]
> I generated a long-live token for the service account referring to https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-a-long-lived-api-token-for-a-serviceaccount
, then it has same "type: kubernetes.io/service-account-token" as autogenerated secret, that's why it could be cleaned I think.

The manually created token is different from the autogenerated token, though both of them are the "type: kubernetes.io/service-account-token". The autogenerated secret name will be added to the service account, but the manually created will not. Have you added the secret name to the service account? If not, the secret should not be deleted.

> with same method I created two serviceaccount, one is referred to in pod, one isn't, but both of them were cleaned, that's why I reported this bug.

How did you create the serviceaccounts? The serviceaccounts should not be cleaned by the cleaner.

**Comment by rxwang662001** [comment]
After mounting the secret with long-live token into the pod manually it works as expected that secret won't be cleaned, so close this ticket now.
and please continue https://github.com/kubernetes/kubernetes/issues/120298
thanks.

**Comment by yt2985** [comment]
Hi @rxwang662001 , as I asked above, for the secret that was cleaned, have you added the secret name to the service account? (There is a Secrets field in the service account, if added, the secret name will be in the Secrets list of the service account) This is important, as for the manually created secrets, there names will not be in the service account field, only the automatcially created secrets will be. Through this way, we differentiate the auto-generated secrets and manually created secrets. We only want to clean the auto-generated secrets, but not the manually created ones. Thank you very much!
