### ISSUE TITLE
Data loss due to node stage call missing during pod start up

### ISSUE THREAD

**Issue by reenakabra** [kubernetes/kubernetes#120455]
### What happened?

Steps done:
1. Create a pvc
2. Create a deployment consuming this pvc
3. Deployment pods we up and running, fio workload was running in this pod
4. Power off all the worker nodes for 20 min
5. Power on all the worker nodes

Old deployment pod was in terminating state. New deployment pod was created. This new pod was in running state and pvc was not mounted in the pod. Instead the root device was mounted on that location.

This can result in data loss.

Analyzing the dumps on the node were this pod was scheduled found below error message

[root@r7515-048-vm14 ~]# kubectl get po -n default
NAME                             READY   STATUS    RESTARTS   AGE
deployment-1-9b6cd7f9d-6wf2t     1/1     Running   0          3h33m
deployment-1-9b6cd7f9d-ljf8h     1/1     Running   0          3h33m

[root@r7515-048-vm14 ~]# kubectl exec -it deployment-1-9b6cd7f9d-6wf2t -n default – bash
[root@deployment-1-9b6cd7f9d-6wf2t /]# mount | grep podvol
/dev/mapper/rhel-root on /podvol type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)

/podvol was meant to mount the pvc instead the root device is mounted.

In the /var/log/messages of worker node were the pod was running found below messages

Aug 31 09:50:37 r7515-048-vm15 kubelet[1328]: E0831 09:50:37.105494    1328 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50 podName: nodeName:}" failed. No retries permitted until 2023-08-31 09:50:37.605464638 +0530 IST m=+15.403186676 (durationBeforeRetry 500ms). Error: MountVolume.SetUp failed for volume "pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff" (UniqueName: "kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50") pod "deployment-1-9b6cd7f9d-6wf2t" (UID: "d4c33241-44d2-4f34-acdb-fced39e7b7f5") : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name org.veritas.infoscale not found in the list of registered CSI drivers

After going through the Kubernetes csi code, the flow is as follows

GenerateMountVolumeFunc() checks for the device mount state and if the device is not mounted on the globalmount it calls attacher to mount the device. Attacher MountDevice takes care of nodeStage.

csi_mounter SetUp is called later which in turn calls nodePublish.

GenerateMountVolumeFunc()
...
                if volumeDeviceMounter != nil && actualStateOfWorld.GetDeviceMountState(volumeToMount.VolumeName) != Devi     ceGloballyMounted

{ ...                          // Mount device to global mount path                          err = volumeDeviceMounter.MountDevice(..) ..                       }
                 mountErr := volumeMounter.SetUp()

Corresponding code links

SetUp():  — Node publish https://github.com/kubernetes/kubernetes/blob/83f2d89dc987e152f27b31bf630c58ce855d954d/pkg/volume/csi/csi_mounter.go#L99

MountDevice(): — Node stage

https://github.com/kubernetes/kubernetes/blob/83f2d89dc987e152f27b31bf630c58ce855d954d/pkg/volume/csi/csi_attacher.go#L270

GenerateMountVolumeFunc() 

https://github.com/kubernetes/kubernetes/blob/83f2d89dc987e152f27b31bf630c58ce855d954d/pkg/volume/util/operationexecutor/operation_generator.go#L533

 On the same node there was a umount request for the same pvc. 

Aug 31 09:50:26 r7515-048-vm15 kubelet[1328]: E0831 09:50:26.293518    1328 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50 podName:d4ab7809-56d7-4568-bb5d-898827d8f7c0 nodeName:}" failed. No retries permitted until 2023-08-31 09:50:26.793478948 +0530 IST m=+4.591200976 (durationBeforeRetry 500ms). Error: UnmountVolume.TearDown failed for volume "pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff" (UniqueName: "kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50") pod "d4ab7809-56d7-4568-bb5d-898827d8f7c0" (UID: "d4ab7809-56d7-4568-bb5d-898827d8f7c0") : kubernetes.io/csi: Unmounter.TearDownAt failed to get CSI client: driver name org.veritas.infoscale not found in the list of registered CSI drivers

After node power on there was both unmount and mount request for same volume. 

In the csi node previous logs found that this pod id matches with the previous app pod.

ts=2023-08-31T04:03:56.907Z level=info logger=driver host=r7515-048-vm15.vxindia.veritas.com:infoscale-csi-node-f55mp msg="NodePublishVolume request for volume" volume=vol_nzr0o08a4hy4t439ot50 source=/var/lib/kubelet/plugins/kubernetes.io/csi/org.veritas.infoscale/74d85482fcfb3089adf2e874147ed0b7172594ca3baa13469b943b080efa19a6/globalmount target=/var/lib/kubelet/pods/d4ab7809-56d7-4568-bb5d-898827d8f7c0/volumes/kubernetes.io~csi/pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff/mount

When the csi pods were available, umount call completed successfully.

Aug 31 09:50:45 r7515-048-vm15 kubelet[1328]: I0831 09:50:45.199404    1328 reconciler.go:211] "operationExecutor.UnmountVolume started for volume \"pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff\" (UniqueName: \"kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50\") pod \"d4ab7809-56d7-4568-bb5d-898827d8f7c0\" (UID: \"d4ab7809-56d7-4568-bb5d-898827d8f7c0\") "

Aug 31 09:50:45 r7515-048-vm15 kubelet[1328]: I0831 09:50:45.210494    1328 operation_generator.go:890] UnmountVolume.TearDown succeeded for volume "kubernetes.io/csi/org.veritas.infoscale^clust_1200/vrts_kube_dg-1200/vol_nzr0o08a4hy4t439ot50" (OuterVolumeSpecName: "pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff") pod "d4ab7809-56d7-4568-bb5d-898827d8f7c0" (UID: "d4ab7809-56d7-4568-bb5d-898827d8f7c0"). InnerVolumeSpecName "pvc-6627dab2-22cf-4347-ae96-90d13c5ecbff". PluginName "kubernetes.io/csi", VolumeGidValue ""

There can be a race condition, when mount request checked for the volume state it was mounted. It did not attempt staging and directly tried publish. Umount request unmounted the device. 

### What did you expect to happen?

Deployment pod consuming the pvc should be staged and published before marking the pod as ready.

### How can we reproduce it (as minimally and precisely as possible)?

We are working on reproducing the issue.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

[root@r7515-048-vm14 ~]# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:29:58Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Cloud provider

<details>

Issue seen on Vanilla K8s

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.6 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.6
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.6"

$ uname -a
Linux r7515-048-vm14.vxindia.veritas.com 4.18.0-372.9.1.el8.x86_64 #1 SMP Fri Apr 15 22:12:19 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by reenakabra** [comment]
Other way through which we are able to consistently reproduce the issue is:

1. Deploy the storage cluster
2. Create pvc and application pods consuming pvc
3. Reboot all the nodes of the storage cluster

After reboot application pods come online even if the storage cluster is not up. Instead of pvc root fs is mounted in application pod. K8s CSI only checks for the mount path if it is present. But, in case of reboot even if mount path exists, volume is not mounted. Application pod startup skip the NodeStage call based on the path and directly calls NodePublish (In the previous comment I have added the code snippet from where NodeStage call is skipped). 

This can cause data loss. Even if we prevent the bind mount in NodePublish, container pods remain in ContainerCreating state until the node is marked with NoSchedule taint and all pods consuming the pvc are cleaned up.

@saad-ali @xing-yang @jsafrane @msau42 Please share your thoughts.

**Comment by jsafrane** [comment]
This looks like a dup of https://github.com/kubernetes/kubernetes/issues/117513.
Try to use `NewVolumeManagerReconstruction` beta feature, if possible, and you can help with https://github.com/kubernetes/kubernetes/pull/119827.

**Comment by reenakabra** [comment]
@jsafrane OCP versions that we support currently are on K8s version 1.25. Will using SELinuxMountReadWriteOncePod alpha feature on K8s 1.25 and 1.26 help resolve this issue?

**Comment by xing-yang** [comment]
cc @jsafrane
