### ISSUE TITLE
[Flaky Test] (capg-conformance-main-ci-artifacts) No Control Plane machines came into existence

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#120481]
### Which jobs are failing?

master-informing:
- [capg-conformance-main-ci-artifacts](https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts)

### Which tests are failing?

`capg-e2e.[It] Conformance Tests Should run conformance tests`

![Screenshot_20230907_125350](https://github.com/kubernetes/kubernetes/assets/73882557/f610511c-cc6e-4fe1-8efb-88a733b52932)

### Since when has it been failing?

Last 2 runs failed consecutively, first failure : https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts/1698303295132536832

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#capg-conformance-main-ci-artifacts

### Reason for failure (if possible)

```
[controller-runtime] log.SetLogger(...) was never called, logs will not be displayed
```

```{Timed out after 1800.000s.
No Control Plane machines came into existence. 
Expected
    <bool>: false
to be true failed [FAILED] Timed out after 1800.000s.
No Control Plane machines came into existence. 
Expected
    <bool>: false
to be true
In [It] at: /home/prow/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.0/framework/controlplane_helpers.go:153 @ 09/03/23 12:42:02.614
}
```

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by neolit123** [comment]
/close
please open this in https://github.com/openshift/cluster-api-provider-gcp

**Comment by Vyom-Yadav** [comment]
/reopen

A duplicate issue would be created in https://github.com/openshift/cluster-api-provider-gcp. This issue would help us track the test on the project board.

**Comment by Vyom-Yadav** [comment]
Created https://github.com/openshift/cluster-api-provider-gcp/issues/199

**Comment by richardcase** [comment]
@Vyom-Yadav - i think thats probably the wrong repo as the provider is in this repo: https://github.com/kubernetes-sigs/cluster-api-provider-gcp

I will create an issue for it.

**Comment by Vyom-Yadav** [comment]
> @Vyom-Yadav - i think thats probably the wrong repo as the provider is in this repo: https://github.com/kubernetes-sigs/cluster-api-provider-gcp
> 
> I will create an issue for it.

Thanks for pointing that out, I'll fix this for other issues as well.

**Comment by MaryamTavakkoli** [comment]
Hello!
I am checking in on behalf of the Bug Triage release team.

I would like to notify you that the code freeze is starting ([01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/3b849751))(about 2 weeks from now). Please ensure your issue goes in by then if you are targeting 1.29 release. (Also, please add the priority label)

Please let us know if we can be of any assistance and help :)

**Comment by pacoxu** [comment]
> There is work ongoing on the fix with PR https://github.com/kubernetes-sigs/cluster-api-provider-gcp/pull/1018, but it's taking some time to get merged.

https://github.com/kubernetes/test-infra/pull/30988 removed this from the test grid temporarily until the fix is in and the job is running successfully again for a few iterations.

**Comment by MaryamTavakkoli** [comment]
Hello!
Bug triage for the 1.29 release cycle is here! I want to check the status and remind you that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), as we want to ensure that each PR has a chance to be merged.
Are we still targeting the 1.29 release?

**Comment by cpanato** [comment]
We fixed, but now have another issue, that we are tracking, i am on it, soon we can close this :)

**Comment by dims** [comment]
this no longer blocks 1.29 and can be worked on for next release

/milestone clear

**Comment by pacoxu** [comment]
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main-ci-artifacts
recent runs are passed.

**Comment by cpanato** [comment]
yes, i will close this for now and will continue to observe the job

**Comment by Vyom-Yadav** [comment]
/reopen

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main-ci-artifacts 
I see the last two runs failed:
1. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts/1724797418731474944
2. https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-gcp-make-conformance-main-ci-artifacts/1724828581508419584

**Comment by cpanato** [comment]
i know why that is happening, but it might need some clarification on the cloud-provider-gcp

will follow up on that
/assign

**Comment by aojea** [comment]
> i know why that is happening, but it might need some clarification on the cloud-provider-gcp

@cpanato what is the question?

**Comment by cpanato** [comment]
@aojea I will check why that is failing and opening issues on the weekend. Unfortunately, I don't have time during the week for that :(

**Comment by pacoxu** [comment]
From the Job history,
- keep failing: from Sep 06th to Oct 24th
- flaking from  Oct 24th to  Oct 27th
- keep failing from Oct 28th to Nov 07th
- flaky from Nov 07th to now.

So this is now a flaking one.

**Comment by Vyom-Yadav** [comment]
/retitle [Flaky Test] (capg-conformance-main-ci-artifacts) No Control Plane machines came into existence
/remove-kind failing-test
/kind flake

**Comment by cpanato** [comment]
Opened an issue in CCM GCP: https://github.com/kubernetes/cloud-provider-gcp/issues/637

**Comment by cpanato** [comment]
I am still on it 😞
