### ISSUE TITLE
Deployment number of replicas doesn't match last applied configuration

### ISSUE THREAD

**Issue by marcush1022** [kubernetes/kubernetes#120487]
### What happened?

A Deployment's number of replicas does not match what the `kubectl.kubernetes.io/last-applied-configuration` is showing.

This is the deployment status, Notice the number of replicas is 1 in `kubectl.kubernetes.io/last-applied-configuration`, but the actual number of replicas deployed is 3 (`replicas: 3`). Shouldn't these two always be the same?

`kubectl apply` or `kubectl replace` does not work here, after I run `kubectl apply` or `kubectl replace` I see the number of pods immediately decreases to 1 and then changes back to 3 automatically.

```bash
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"my-app","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"my-app","app.kubernetes.io/version":"pre_v1.0.3-6","helm.sh/chart":"my-app-1.0.3-6"},"name":"my-app","namespace":"my-name-space"},"spec":{"minReadySeconds":10,"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"my-app","app.kubernetes.io/name":"my-app"}},"strategy":{"rollingUpdate":{"maxSurge":3,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cni.networking.kun/ipv4Enabled":"true"},"labels":{"app.kubernetes.io/instance":"my-app","app.kubernetes.io/name":"my-app"}},"spec":{"containers":[{"image":"hub.my-image-hub.com/my-app:pre_v1.0.3-6","imagePullPolicy":"IfNotPresent","name":"my-app","ports":[{"containerPort":4210,"name":"http","protocol":"TCP"}],"resources":{"limits":{"cpu":"4000m","memory":"2Gi"},"requests":{"cpu":"100m","memory":"100Mi"}},"securityContext":{},"volumeMounts":[{"mountPath":"/root/workspace/conf/config.json","name":"config","subPath":"config.json"}]}],"imagePullSecrets":[{"name":"hub-foobar"}],"securityContext":{},"volumes":[{"configMap":{"name":"my-app-config-pre-v1.0.3-6"},"name":"config"}]}}}}
  creationTimestamp: "2023-09-06T09:24:13Z"
  generation: 20
  labels:
    app.kubernetes.io/instance: my-app
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: my-app
    app.kubernetes.io/version: pre_v1.0.3-6
    helm.sh/chart: my-app-1.0.3-6
  name: my-app
  namespace: my-name-space
  resourceVersion: "614920013"
  selfLink: /apis/apps/v1/namespaces/my-name-space/deployments/my-app
  uid: my-uid
spec:
  minReadySeconds: 10
  progressDeadlineSeconds: 600
  replicas: 3
```

### What did you expect to happen?

I expect they are the same. There should be 1 replica in actual deployment.

### How can we reproduce it (as minimally and precisely as possible)?

It happens every time I deploy my app with a config file whose spec replicas value is 1.
When running `kubectl get deploy my-app -o yaml` I see that `kubectl.kubernetes.io/last-applied-configuration` doesn't match the actual spec replicas.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:21:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
n/a
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

</details>


### Install tools

<details>

</details>


### Container runtime (CRI) and version (if applicable)

<details>
n/a
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by HirazawaUi** [comment]
> ```
> $ kubectl version
> # paste output here
> Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:21:12Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:35:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
> ```
This version is no longer supported, please test with a supported version and report back https://kubernetes.io/releases/

/remove-sig release
/sig cli
/triage needs-information

**Comment by liggitt** [comment]
> This is the deployment status, Notice the number of replicas is 1 in `kubectl.kubernetes.io/last-applied-configuration`, but the actual number of replicas deployed is 3 (`replicas: 3`). Shouldn't these two always be the same?

This means something other than `kubectl apply` is changing replicas.

`kubectl get deployment/my-app -o yaml --show-managed-fields` might show what operation modified spec.replicas
