### ISSUE TITLE
cmd/kube-apiserver imports cmd/kubeadm

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#120419]
found this by running tests on this PR:
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120417/pull-kubernetes-typecheck/1698995947637313536
https://github.com/kubernetes/kubernetes/pull/120417

it's problematic for a couple of reasons:
- prevents kubeadm from moving out (eventually)
- there are no API guarantees in the given code/structs/functions in pkiutils

the logic in cmd/kube-apiserver/app/testing/testserver.go must be reworked to generate cert/key pair without using kubeadm.
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/testing/testserver.go#L54
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/testing/testserver.go#L216-L231

originally added in https://github.com/kubernetes/kubernetes/pull/112069

pending fix PR
- https://github.com/kubernetes/kubernetes/pull/120422

**Comment by aojea** [comment]
cc @enj

**Comment by enj** [comment]
Please make sure to add an import restriction to prevent a regression in the future.
