### ISSUE TITLE
GKE needs to support privileged containers

### ISSUE THREAD

**Issue by starsimpson** [kubernetes/kubernetes#12048]
I'm working to put together a docker-based build system that lives in GKE and so far appear to need privileged access to make the base docker image (dind, docker-in-docker) run. Please let me know if support for privileged containers might change in future.

**Comment by mikedanese** [comment]
This is low hanging fruit and a few people have already asked for it. @roberthbailey @zmerlynn

**Comment by roberthbailey** [comment]
This isn't quite as easy as you might think. First we need to actually make it work and be supported on GCE (for example, see https://github.com/GoogleCloudPlatform/kubernetes/issues/10489). Right now, it's possible to do on GCE if you perform some hacks, but isn't really supported and certainly isn't tested. 

@bgrant0607 also mentioned that we should do this with an admission controller rather than via flags (see https://github.com/GoogleCloudPlatform/kubernetes/issues/9626#issuecomment-116775209). I'd much prefer us to do this right rather than take shortcuts that sometimes work and that we need to continue to support. 

We should be striving for less cluster initialization configuration rather than adding more and more nobs that can only be changed by destroying and recreating your cluster.

**Comment by thockin** [comment]
We almost enabled it by default but backed away - it's a sort of scary
amount of power to have by default.

**Comment by mikedanese** [comment]
@roberthbailey thanks for the explanation. It does seem like we should move this into admission control.

**Comment by bgrant0607** [comment]
See #7893.

We could also create a trivial admission control policy that would reject privileged containers. One would enable or disable this functionality by installing that plugin or not.

**Comment by roberthbailey** [comment]
@bgrant0607 Is it possible to change the admission controllers that are applied at runtime? Your suggestion to install / not install a plugin seems to just move the logic around a bit but still require a cluster creation decision about privileged containers that can't later be changed.

**Comment by thockin** [comment]
Yeah, I think we really need a runtime decision being made as to whether a
given pod can or can not use privileged, which is a slippery slope of
features.

**Comment by thockin** [comment]
Another issue was just filed on this - NFS needs privileged containers.  I think this problem needs some very pointed attention for v1.1

@liggitt @deads2k @erictune @dchen1107 @smarterclayton @bgrant0607 @ArtfulCoder

**Comment by roberthbailey** [comment]
Is there an existing issue tracking enabling privileged containers via admission controller?

**Comment by smarterclayton** [comment]
The closest is the SCC work from @pweil- which applies a policy admission
controller which rejects pods that aren't under a service account that is
authorized to run privileged.  He's currently renaming it PodSecurityPolicy
in his pulls to better align it with the PodSecurityContext proposal.

If we made PSP a core Kube resource in expapi we'd have a much more
powerful story for restricting who can run as what.  @bgrant0607 I don't
know what your latest thoughts were on that but it's fairly decoupled from
other objects and would close the major security holes for nodes without
requiring anything more than our current authn/z story (@liggitt as well).

On Aug 26, 2015, at 11:45 PM, Robert Bailey <notifications@github.com>
wrote:

Is there an existing issue tracking enabling privileged containers via
admission controller?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12048#issuecomment-135262806>
.

**Comment by bgrant0607** [comment]
"That" being #12823 or #7893?

**Comment by smarterclayton** [comment]
Both, and https://github.com/openshift/origin/pull/4252was an attempt for
us to stop carrying the patch.  I'd like to take that last and have it
replace 7893 if we think the core idea is reasonable and we can agree on
12823.  That gives admins full control over who can escalate on nodes (and
guards against users exec'ing into privileged pods to escalate their
authority).

On Aug 27, 2015, at 1:28 PM, Brian Grant <notifications@github.com> wrote:

"That" being #12823 <https://github.com/kubernetes/kubernetes/pull/12823>
or #7893 <https://github.com/kubernetes/kubernetes/pull/7893>?

—
Reply to this email directly or view it on GitHub
<https://github.com/kubernetes/kubernetes/issues/12048#issuecomment-135484926>
.

**Comment by bgrant0607** [comment]
cc @thockin for the immediate plan

**Comment by thockin** [comment]
Immediate plan is to switch this to "enabled" by default.  It's
 unfortunate that so many things need it, but they do.

@artfulcoder to close this with his PR

**Comment by ArtfulCoder** [comment]
https://github.com/kubernetes/kubernetes/pull/13930
This PR will be in 1.1 and enabled privileged pods.
GKE will have to roll out 1.1 for master, and customers will have to rollout 1.1 on the minions.
Things should then just work.

Closing this issue.
