### ISSUE TITLE
FailedComputeMetricsReplicas: failed to get memory and CPU utilization

### ISSUE THREAD

**Issue by yashdudhatra** [kubernetes/kubernetes#120477]
### What happened?

The HPA is encountering the "FailedComputeMetricsReplicas" error, preventing it from computing metrics and making scaling decisions and I have received the following error message:

I0902 11:57:32.576643       1 event.go:294] "Event occurred" object="***/storage" fieldPath="" kind="HorizontalPodAutoscaler" apiVersion="autoscaling/v2" type="Warning" reason="FailedComputeMetricsReplicas" message="invalid metrics (2 invalid out of 2), first error is: failed to get memory utilization: unable to get metrics for resource memory: unable to fetch metrics from resource metrics API: the server is currently unable to handle the request (get pods.metrics.k8s.io)

This error was discovered in the audit logs while monitoring the system's behaviour. Despite having lower resource consumption than the thresholds set in the HPA, my system is unable to scale down due to this error. The problem is intermittent, as I have encountered this error a few times in the last week.

### What did you expect to happen?

The HPA should be able to compute metrics for replicas and scale the pods accordingly, as per the defined resource utilization thresholds.

### How can we reproduce it (as minimally and precisely as possible)?

Unfortunately, I cannot provide specific steps to reproduce this issue as it occurs intermittently.

### Kubernetes version

<details>
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.24.10
</details>

### Cloud provider

<details>
Azure Kubernetes Service (AKS)
</details>

### OS version

<details>

NAME="Common Base Linux Mariner"
VERSION="2.0.20230823"
ID=mariner
VERSION_ID="2.0"
PRETTY_NAME="CBL-Mariner/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://aka.ms/cbl-mariner"
BUG_REPORT_URL="https://aka.ms/cbl-mariner"
SUPPORT_URL="https://aka.ms/cbl-mariner"

Linux cc-6644dda2-6598f574c7-g6cxd 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lowang-bh** [comment]
https://github.com/kubernetes/kubernetes/blob/21f7bf66fa949dda2b3bec6e3581e248e270e001/staging/src/k8s.io/apimachinery/pkg/api/errors/errors.go#L477C26-L479

It seems the hpa server is not available at this time when the error occurs.

<img width="742" alt="image" src="https://github.com/kubernetes/kubernetes/assets/21003791/d609f4c6-05a6-4754-a500-673d52a2b8f6">

**Comment by yashdudhatra** [comment]
Hii @lowang-bh 
Thank you for getting back to me.
I again encountered the same error message on 09/09/2023 at 9:57 UTC 18 times—3 times for each running service.
could you please provide guidance on how to resolve this intermittent error. It is affecting the stability of our system, and we are keen to rectify the situation as soon as possible.

**Comment by RiyajKazieomccain** [comment]
HI all, Even we are seeing this issue and this is affecting our PROD. When this happens its basically brings down the entire pods and all the pipeline which are running will also fails

**Comment by RiyajKazieomccain** [comment]
@lowang-bh 
I am seeing below issue in event

network is not ready: container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized


Below are the logs from the node.
h-4.2$ sudo bash /opt/cni/bin/aws-cni-support.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    56  100    56    0     0  60021      0 --:--:-- --:--:-- --:--:-- 56000

        This is version 0.7.6. New versions can be found at https://github.com/awslabs/amazon-eks-ami/blob/master/log-collector-script/

Trying to collect common operating system logs...
Trying to collect kernel logs...
Trying to collect modinfo... Trying to collect mount points and volume information...
Trying to collect SELinux status...
Trying to collect iptables information...
Trying to collect installed packages...
Trying to collect active system services...
Trying to Collect Containerd daemon information... cp: cannot stat '/tmp/containerd.*.stacks.log': No such file or directory

Trying to Collect Containerd running information...
Trying to Collect Docker daemon information...

        Warning: The Docker daemon is not running.

Trying to collect kubelet information...
Trying to collect L-IPAMD introspection information... Trying to collect L-IPAMD prometheus metrics... Trying to collect L-IPAMD checkpoint...
Trying to collect Multus logs if they exist...
Trying to collect sysctls information...
Trying to collect networking infomation... conntrack v1.4.4 (conntrack-tools): 1965 flow entries have been shown.

Trying to collect CNI configuration information...
Trying to collect Docker daemon logs...
Trying to Collect sandbox-image daemon information...
Trying to Collect CPU Throttled Process Information...
Trying to Collect IO Throttled Process Information...
Trying to archive gathered information...

        Done... your bundled logs are located in /var/log/eks_i-05fb417a5af669596_2023-10-26_2117-UTC_0.7.6.tar.gz
