### ISSUE TITLE
ValidatingAdmissionPolicy: spec.variables should be marked omitempty

### ISSUE THREAD

**Issue by MariamFahmy98** [kubernetes/kubernetes#120491]
### What would you like to be added?

spec.variables should be marked omitempty.

### Why is this needed?

I'm trying to create a validating admission policy that uses `spec.variables` in v1.27 as follows:
```
// set validating admission policy spec
vap.Spec = v1alpha1.ValidatingAdmissionPolicySpec {
        ParamKind:        rule.Validation.CEL.ParamKind,
        MatchConstraints: &matchResources,
	Validations:      rule.Validation.CEL.Expressions,
	AuditAnnotations: rule.Validation.CEL.AuditAnnotations,
	MatchConditions:  rule.CELPreconditions,
}
```
I'm setting `FieldValidation`: to "Strict" in CreateOptions so that the server will reject requests with unknown fields but it complains that the `spec.variables` don't exist in v1.27 and it does make sense because this field was introduced in v1.28:
```
strict decoding error: unknown field "spec.variables"'
```
I'm using a 1.28 client.

**Comment by cici37** [comment]
Thanks for raising this!
/cc
