### ISSUE TITLE
Collect tips for external cloud provider migration

### ISSUE THREAD

**Issue by dims** [kubernetes/kubernetes#120411]
- [kube-apiserver] ensure `DisableCloudProviders` is `true` (by default or explicitly)
- [kubelet] ensure `DisableKubeletCloudCredentialProviders` is `true` (by default or explicitly)
- [kubelet] Need to switch on `--image-credential-provider-config` and `--image-credential-provider-bin-dir` ( see https://github.com/kubernetes/kubernetes/pull/120392 ).
- [kube-controller-manager] Need to switch off `node-ipam-controller` in the value of `--controllers` parameter
- Run the extra binaries/containers needed for the `cloud` version of the `controller-manager`
  - kube-up.sh example [start-cloud-controller-manager](https://cs.k8s.io/?q=start-cloud-controller-manager&i=nope&files=&excludeFiles=&repos=)
  - cloud-provider-aws [getting started](https://github.com/kubernetes/cloud-provider-aws/blob/master/docs/getting_started.md)
  - cloud-provider-azure [docs](https://cloud-provider-azure.sigs.k8s.io/install/azure-ccm/)

**Comment by dims** [comment]
cc @elmiko @kmala @bridgetkromhout @aojea @andrewsykim

**Comment by aojea** [comment]
> * [kube-controller-manager] Need to switch off `node-ipam-controller` in the value of `--controllers` parameter

only if uses the `CloudAllocator`

> cmd/kube-controller-manager/app/core.go:                return nil, false, errors.New("--cidr-allocator-type is set to 'CloudAllocator' but cloud provider is not configured")

**Comment by cpanato** [comment]
I would like to know if there is any docs regarding the GCE migration, existing clusters and new ones, thanks

we will need this for capg

**Comment by elmiko** [comment]
@cpanato i'm not finding an GCE specific docs for migration, but we do have these 2 general docs about migrating (depending on whether you are using HA or not):
* https://kubernetes.io/docs/tasks/administer-cluster/running-cloud-controller/#cloud-controller-manager
* https://kubernetes.io/docs/tasks/administer-cluster/controller-manager-leader-migration/

we will capture the general tips for migration and troubleshooting  in the KEP but for GCE specific guidance this is something that should be requested in the [cloud-provider-gcp](https://github.com/kubernetes/cloud-provider-gcp) repository. i have a feeling there will be more requests like this for specific cloud provider documentation and i think we will need to focus our efforts on having the individual providers create documentation as it will not scale well to centralize this knowledge for all providers.

**Comment by elmiko** [comment]
@dims 

> [kubelet] Need to switch on --image-credential-provider-config and --image-credential-provider-bin-dir

is this only for gcp?

**Comment by dims** [comment]
@elmiko for all providers
