### ISSUE TITLE
[Failing Test] kubeadm-kinder-upgrade-addons-before-controlplane-1-28-latest and kubeadm-kinder-upgrade-1-28-latest

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#120538]
### Which jobs are failing?

master-informing:
- [kubeadm-kinder-upgrade-1-28-latest](https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-1-28-latest)
- [kubeadm-kinder-upgrade-addons-before-controlplane-1-28-latest](https://testgrid.k8s.io/sig-release-master-informing#kubeadm-kinder-upgrade-addons-before-controlplane-1-28-latest)

### Which tests are failing?

`task-06-upgrade`

### Since when has it been failing?

2023-09-07 09:58:57 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing

### Reason for failure (if possible)

`
[upgrade/etcd] Failed to upgrade etcd: couldn't upgrade control plane. kubeadm has tried to recover everything into the earlier state. Errors faced: static Pod hash for component etcd on Node kinder-upgrade-addons-before-controlplane-control-plane-1 did not change after 5m0s: timed out waiting for the condition
`

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by neolit123** [comment]
there are two failing kinder jobs tracked here:
https://github.com/kubernetes/kubeadm/issues/2927

please add that issue to your board.
it's on the kubernetes/kubeadm repo, so it's possible.

we are investigating the cause.

/close
