### ISSUE TITLE
[Flaky]  HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol

### ISSUE THREAD

**Issue by alculquicondor** [kubernetes/kubernetes#120570]
### Which jobs are flaking?

pull-kubernetes-conformance-kind-ga-only-parallel

### Which tests are flaking?

Kubernetes e2e suite: [It] [sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] 

### Since when has it been flaking?

Not sure, it looks like it has been happening for a while

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?pr=1&job=pull-kubernetes-conformance-kind-ga-only-parallel&test=HostPort%20validates%20that%20there%20is%20no%20conflict%20between%20pods%20with%20same%20hostPort%20but%20different%20hostIP%20and%20protocol%20

### Reason for failure (if possible)

```
[FAILED] wait for pod pod1 timeout, err:Told to stop trying after 2.014s.
  The phase of Pod pod1 is Failed which is unexpected.
  In [It] at: test/e2e/network/hostport.go:219 @ 09/11/23 14:13:04.254
```

### Relevant SIG(s)

/sig network

**Comment by aojea** [comment]
/reopen

This is confusing

> STEP: Trying to create another pod(pod2) with hostport 54323 but hostIP fc00:f853:ccd:e793::2 on the node which pod1 resides and expect scheduled - k8s.io/kubernetes/test/e2e/network/hostport.go:91 @ 02/02/24 16:36:10.174
[FAILED] wait for pod pod2 timeout, err:Told to stop trying after 2.021s.
The phase of Pod pod2 is Failed which is unexpected.

https://storage.googleapis.com/k8s-triage/index.html?test=HostPort%20validates%20that%20there%20is%20no%20conflict%20between%20pods%20with%20same%20hostPort%20but%20different%20hostIP%20and%20protocol%20&xjob=kops%7Ccapz

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1753453048434266112

**Comment by aojea** [comment]
@pohly check this

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-conformance-parallel-ipv6/1753453048434266112

> { failed [FAILED] wait for pod pod2 timeout, err:Told to stop trying after 2.021s.
> The phase of Pod pod2 is Failed which is unexpected.
> In [It] at: k8s.io/kubernetes/test/e2e/network/hostport.go:219 @ 02/02/24 16:36:12.204

The errors is misleading , it failed because it could not schedule the pod

> I0202 16:36:12.217141 68172 dump.go:53] At 2024-02-02 16:36:10 +0000 UTC - event for pod2: {kubelet kind-worker2} OutOfpods: Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
> I0202 16:36:12.223943 68172 resource.go:168] POD   NODE          PHASE    GRACE  CONDITIONS
> I0202 16:36:12.224031 68172 resource.go:175] pod1  kind-worker2  Running         [{PodReadyToStartContainers True 0001-01-01 00:00:00 +0000 UTC 2024-02-02 16:36:08 +0000 UTC  } {Initialized True 0001-01-01 00:00:00 +0000 UTC 2024-02-02 16:35:58 +0000 UTC  } {Ready True 0001-01-01 00:00:00 +0000 UTC 2024-02-02 16:36:08 +0000 UTC  } {ContainersReady True 0001-01-01 00:00:00 +0000 UTC 2024-02-02 16:36:08 +0000 UTC  } {PodScheduled True 0001-01-01 00:00:00 +0000 UTC 2024-02-02 16:35:58 +0000 UTC  }]
> I0202 16:36:12.224049 68172 resource.go:175] pod2  kind-worker2  Failed          []
> I0202 16:36:12.224058 68172 resource.go:178] 
> I0202 16:36:12.266159 68172 resource.go:231] Unable to fetch hostport-5749/pod2/agnhost logs: the server rejected our request for an unknown reason (get pods pod2)

**Comment by pohly** [comment]
> The errors is misleading , it failed because it could not schedule the pod

The code is just giving you the pod phase. That seems to be "Failed" when a pod cannot be scheduled. If that is misleading, then we need a different pod phase for this particular case? Probably not possible without an API break.

What could be enhanced is the failure message. Including a dump of the full pod might have been useful:
https://github.com/kubernetes/kubernetes/blob/f99638d315a290801ccc3c7257c556ff1bf42051/test/e2e/network/hostport.go#L218-L220

I need to check how that is currently implemented. Adding the pod struct should be doable.

Even better is including pod events. That is more work because the information might not be accessible at the time when a timeout is detected (apiserver down!), so it would have to be collected beforehand. I have an idea, but haven't had the time to implement it.

**Comment by aojea** [comment]
@pohly no big deal, I just wanted to bring your attention, since you put a lot of thoughts on this, not changing phases or apis, just how to improve the log message , but once you click the information is there, so it is ok

/close

**Comment by aojea** [comment]
it failed with

```
STEP: Found 1 events. - k8s.io/kubernetes/test/e2e/framework/debug/dump.go:46 @ 04/18/24 08:23:42.251
I0418 08:23:42.251282 68958 dump.go:53] At 2024-04-18 08:23:40 +0000 UTC - event for pod1: {kubelet kind-worker2} OutOfpods: Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110
I0418 08:23:42.259586 68958 resource.go:168] POD   NODE          PHASE   GRACE  CONDITIONS
I0418 08:23:42.259641 68958 resource.go:175] pod1  kind-worker2  Failed         []
```

IIRC there was one test that created a lot of pods
```
simpletest-rc-to-be-deleted-8r928
```

That is the test we need to fail the bug, as it is impacting the other tests, in this case this was a victim

**Comment by aojea** [comment]
This one https://github.com/kubernetes/kubernetes/blob/c016b0b9a8ca63dbec1fade0910c2a06017cc4ab/test/e2e/apimachinery/garbage_collector.go#L714-L719

**Comment by alculquicondor** [comment]
/reopen
?
or was there another open issue?

**Comment by aojea** [comment]
> /reopen ? or was there another open issue?

/close

@alculquicondor this test is a victim , the root cause is that this other test https://github.com/kubernetes/kubernetes/issues/124369 exhaust the number of pods and the test can not schedule a new pod
