### ISSUE TITLE
[Failing Test] Error starting e2e cluster (kubetest.Up)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#120500]
### Which jobs are failing?

master-informing:
- [gce-master-scale-correctness](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-correctness) 
- [gce-master-scale-performance](https://testgrid.k8s.io/sig-release-master-informing#gce-master-scale-performance)

### Which tests are failing?

`kubetest.Up`

### Since when has it been failing?

2023-09-04 17:01:55 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing

### Reason for failure (if possible)

Not sure about the reason for failure, probable reasons:
```
scp: /var/log/cluster-autoscaler.log*: No such file or directory
scp: /var/log/fluentd.log*: No such file or directory
scp: /var/log/kubelet.cov*: No such file or directory
scp: /var/log/cl2-**: No such file or directory
scp: /var/log/startupscript.log*: No such file or directory
ERROR: (gcloud.compute.scp) [/usr/bin/scp] exited with return code [1]. 
```
The logs might just not simply exist.

Repeated
```
ERROR: (gcloud.compute.start-iap-tunnel) Error while connecting [4033: 'not authorized'].
```

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/sig cloud provider
/area provider/gcp

gce-* jobs are usually using kube-up. you can look at the logs for things like `gce/util.sh`.
that tooling is not maintained by sig cluster lifecycle and instead it's the GCP provider.
