### ISSUE TITLE
Pods are stuck ContainerCreating after volume detach error and KCM restart

### ISSUE THREAD

**Issue by jsafrane** [kubernetes/kubernetes#120571]
### What happened?

After KCM restart, any Pod that reuses a volume that failed to detach gets stuck ContainerCreating with message:

`
User "system:node:ip-10-0-243-205.us-east-2.compute.internal" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'ip-10-0-243-205.us-east-2.compute.internal' and this object
`

See steps to reproduce below, it's quite a complex condition. It happens when a pod is restarted, a CSI driver "busy" (i.e. times out) + KCM restarted at a wrong time.

### What did you expect to happen?

Pods start just fine.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a Pod that uses an attachable CSI volume.
2. Delete the Pod. Make sure it unmounts successfully, but any `ControllerUnpublish` fails with a transient error, such as timeout. The external attacher continues to detach the volume at this point.
3. Stop kube-controller-manager (KCM) and start a new one. Wait for any leader election etc - it's important for the new KCM to populate A/D controller with no pod using the detaching volume. Let the A/D controller to observe detach error.
4. Create a new Pod on the same node that uses the same volume.
5. Let the CSI driver to detach the volume (i.e. stop injecting any transient errors).

At this point:

- The external attacher succeeds detaching the volume, VolumeAttachment is deleted.
- The volume is marked as attached in node status (!!!) despite no VolumeAttachment exists. A/D controller does not even try to create a new VolumeAttachment, the volume is marked as attached in its Actual State of World (ASW).
- Kubelet tries to mount the volume, but WaitForAttach fails with: `cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node '127.0.0.1' and this object`, basically forever.

I created [a script with a reproducer](https://people.redhat.com/jsafrane/detach-error/).

* The script expects that the cluster is created by `hack/local-up-cluster.sh`, because it restarts KCM in the middle.
* It uses my hacked hostpath CSI driver to inject detach errors. Sources are at https://github.com/jsafrane/csi-driver-host-path/tree/hack-detach-error / the last commit(s) there.

### Anything else we need to know?

There are two issues that together lead to this situation:

1. After `Detach()` fails, [A/D controller marks the volume as fully attached](https://github.com/kubernetes/kubernetes/blob/887ac275a2cfb6030df80bbe3066609336fa220a/pkg/volume/util/operationexecutor/operation_generator.go#L508-L511), i.e. puts it back to `node.status.volumesAttached`.
    * With the volume in `node.status.volumesAttached`, kubelet may try to mount it, while the external attacher tries to detach it. It is not as bad as it sounds, because kubelet can't read VolumeAttachment with the deletion timestamp and it will not call `NodeStage` / `NodePublish` of un-attached volume.
2. After KCM starts, all VolumeAttachments that don't have a Pod [are marked as Uncertain](https://github.com/kubernetes/kubernetes/blob/887ac275a2cfb6030df80bbe3066609336fa220a/pkg/controller/volume/attachdetach/attach_detach_controller.go#L763-L763) (that's good), but also [as mounted on node](https://github.com/kubernetes/kubernetes/blob/887ac275a2cfb6030df80bbe3066609336fa220a/pkg/controller/volume/attachdetach/cache/actual_state_of_world.go#L370-L370) (that's probably bad).
    * When the newly started KCM re-tries to detach the volume and gets an error again, it marks the volume as fully attached (same as the previous point) and adds it to `node.status.volumesAttached`.
    * Now the volume is both mounted + attached in ASW and A/D controller actually stops here and waits forever for kubelet to unmount the volume.

### Kubernetes version

<details>
Today's k/k master, 
```console
$ kubectl version
v1.29.0-alpha.0.456+887ac275a2cfb6-dirty
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>
N/A, it's KCM issue.
</details>

### Install tools

<details>
`hack/local-up-cluster.sh`, but seen in a downstream Kubernetes distro too.
</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kvaps** [comment]
I have the same problem:

```
Events:
  Type     Reason                  Age                       From                     Message
  ----     ------                  ----                      ----                     -------
  Warning  FailedMount             41m (x584 over 4d15h)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[kube-rbac-proxy-ca data kube-api-access-p7l8w tmp]: timed out waiting for the condition
  Warning  FailedMount             21m (x1250 over 4d15h)    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-p7l8w tmp kube-rbac-proxy-ca]: timed out waiting for the condition
  Warning  FailedMount             12m (x544 over 4d15h)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[tmp kube-rbac-proxy-ca data kube-api-access-p7l8w]: timed out waiting for the condition
  Warning  FailedMount             6m41s (x3290 over 4d15h)  kubelet                  MountVolume.WaitForAttach failed for volume "pvc-480f719e-99b2-4b7a-8298-ba67d79d7079" : volume attachment is being deleted
  Warning  FailedMount             2m37s (x2 over 4m39s)     kubelet                  MountVolume.WaitForAttach failed for volume "pvc-480f719e-99b2-4b7a-8298-ba67d79d7079" : volume pvc-480f719e-99b2-4b7a-8298-ba67d79d7079 has GET error for volume attachment csi-09bb06235ebc0cbec1a784e158ef6232022627c643f4a2fe92f62296dfcbf87f: volumeattachments.storage.k8s.io "csi-09bb06235ebc0cbec1a784e158ef6232022627c643f4a2fe92f62296dfcbf87f" is forbidden: User "system:node:kube-system-1" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node 'kube-system-1' and this object
  Normal   SuccessfulAttachVolume  1s (x7 over 6m1s)         attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-480f719e-99b2-4b7a-8298-ba67d79d7079"
[citysites] root@kube-master-1 ~ # k get volumeattachments.storage.k8s.io csi-09bb06235ebc0cbec1a784e158ef6232022627c643f4a2fe92f62296dfcbf87f
Error from server (NotFound): volumeattachments.storage.k8s.io "csi-09bb06235ebc0cbec1a784e158ef6232022627c643f4a2fe92f62296dfcbf87f" not found
```

Kubernetes v1.25.13

**Comment by derekbit** [comment]
@jsafrane  Sorry. The issue is closed by the robot. Is any solution to it? Thank you.
