### ISSUE TITLE
'Connection Timed Out' error when executing inside running pod

### ISSUE THREAD

**Issue by dolgae03** [kubernetes/kubernetes#120545]
### What happened?

For my Cluster, There are 3 nodes in cluster.

2 nodes are work well, But One nodes doesn't work well.

I used calico as CNI.

I tired to access running pod using exec command like this : kubectl exec -n calico-system -it [pod_name] /bin/bash

For the 2 nodes, exec command works well.

![image](https://github.com/kubernetes/kubernetes/assets/109707681/1908d628-944f-43e8-b589-d0bc669832f6)

However, for one nodes that has problem, it shows like below.
![image](https://github.com/kubernetes/kubernetes/assets/109707681/d8c87844-8d60-45d4-a11f-57a31339ed79)

This situation also happen to kube-proxy, if i use exec command, it just pending and give 127.0.0.1:xxxx connection time out.

The describe of this pod:
Events:
Type Reason Age From Message

Normal Scheduled 5m31s default-scheduler Successfully assigned calico-system/calico-node-qmhps to ubuntu
Normal Pulled 5m30s kubelet Container image "docker.io/calico/pod2daemon-flexvol:v3.26.1" already present on machine
Normal Created 5m30s kubelet Created container flexvol-driver
Normal Started 5m30s kubelet Started container flexvol-driver
Normal Pulled 5m29s kubelet Container image "docker.io/calico/cni:v3.26.1" already present on machine
Normal Created 5m29s kubelet Created container install-cni
Normal Started 5m29s kubelet Started container install-cni
Warning Unhealthy 5m27s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0908 13:07:14.483764 61 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Warning Unhealthy 5m26s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0908 13:07:15.487428 371 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Warning Unhealthy 4m55s (x3 over 5m15s) kubelet Readiness probe failed: command "/bin/calico-node -bird-ready -felix-ready" timed out
Normal Created 4m50s (x2 over 5m28s) kubelet Created container calico-node
Normal Started 4m50s (x2 over 5m28s) kubelet Started container calico-node
Normal Pulled 4m50s (x2 over 5m28s) kubelet Container image "docker.io/calico/node:v3.26.1" already present on machine
Warning Unhealthy 4m50s (x3 over 5m10s) kubelet Liveness probe failed: Get "http://localhost:9099/liveness": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Normal Killing 4m50s kubelet Container calico-node failed liveness probe, will be restarted
Warning Unhealthy 4m50s kubelet Readiness probe failed: 2023-09-08 13:07:51.192 [INFO][523] confd/health.go 180: Number of node(s) with BGP peering established = 2
W0908 13:07:51.187693 523 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Warning Unhealthy 4m50s kubelet Readiness probe errored: rpc error: code = NotFound desc = failed to exec in container: failed to create exec "10f418b975084fd2b587cab91d3df175b0e08003ab1d756cfc9a3645ddd3d804": task 5c55e7e8fa6a9d841758e8866f23382c50d290d1b651efd3a72618434e9d62a3 not found: not found
Warning Unhealthy 4m50s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0908 13:07:51.554603 23 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Warning Unhealthy 4m49s kubelet Readiness probe failed: calico/node is not ready: BIRD is not ready: Error querying BIRD: unable to connect to BIRDv4 socket: dial unix /var/run/calico/bird.ctl: connect: connection refused
W0908 13:07:52.589282 85 feature_gate.go:241] Setting GA feature gate ServiceInternalTrafficPolicy=true. It will be removed in a future release.
Warning BackOff 30s (x7 over 90s) kubelet Back-off restarting failed container calico-node in pod calico-node-qmhps_calico-system(eaa1e1ba-190f-4fe7-83e6-343dc8cd2dae)`

The log of this pod doesn't give any Warning or Fatal for me. This is last some line of error

bird: Mesh_: Connected to table master
bird: Mesh_: State changed to wait
bird: Mesh_: Connected to table master
bird: Mesh_: State changed to wait
bird: Graceful restart done
bird: Mesh_: State changed to feed
bird: Mesh_: State changed to feed
bird: Mesh_: Invalid NEXT_HOP attribute in route 192.168.163.0/26
bird: Mesh_: State changed to up
bird: Mesh_: Invalid NEXT_HOP attribute in route 192.168.157.0/26
bird: Mesh_: State changed to up

And, One more strange things is that the calico-typha created once more.
![image](https://github.com/kubernetes/kubernetes/assets/109707681/6aece6ea-455b-4de8-8886-f051f03cdca6)

![image](https://github.com/kubernetes/kubernetes/assets/109707681/5d0d8a08-19da-4368-8d28-6adbea56b331)

### What did you expect to happen?

Running of Calico Node

### How can we reproduce it (as minimally and precisely as possible)?

I just follow the K8s kubeadm install guide and i tried to reproduce this situtation on aws but, i can't reproduce this error.

I also tried to reinstall the whole contents after delete k8s config file and cni. But, it doesn't works.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
Local Server
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd 1.6.22 for working node
containerd 1.6.21 for not working node

I used the apt install to install containerd

apt install containerd.io
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
used Calico CNI and use operator to install CNI
v3.26.1

kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml

kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
</details>

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

if you suspect a calico bug please log an issue in the calico issue tracker.

/kind support
/close
