### ISSUE TITLE
PodResources API of kubelet does not report the resources allocated to restartable init containers

### ISSUE THREAD

**Issue by gjkim42** [kubernetes/kubernetes#120501]
previous discussion: https://github.com/kubernetes/kubernetes/pull/120461#discussion_r1317515863

https://github.com/kubernetes/kubernetes/blob/56cc5e77a10ba156694309d9b6159d4cd42598e1/pkg/kubelet/apis/podresources/server_v1.go#L51-L86

kubelet's PodResources API does not report the resources allocated to restartable init containers.
This should be fixed before we move to the beta stage.

/sig-node
/kind bug

/cc @ffromani @tzneal @SergeyKanzhelev

**Comment by ffromani** [comment]
/triage accepted
/priority important-longterm

I'm convinced we should still NOT report resources for regular init container. Only sidecar containers should be reported, because they match or exceed the lifetime of app container.

**Comment by tzneal** [comment]
> I'm convinced we should still NOT report resources for regular init container. Only sidecar containers should be reported, because they match or exceed the lifetime of app container.
