### ISSUE TITLE
kube-scheduler cache has not updated sometimes

### ISSUE THREAD

**Issue by lance5890** [kubernetes/kubernetes#120512]
### What happened?

1. sometimes,  when we add or delete anti-affinity pods with pvc, the pod is pending with reason by "node(s) didn't match pod anti-affinity rules",  I forgot to check the scheduler cache that time.
2. but when we restart kube-sheduler, the pod can be scheduled   successfully again

the logs can be seen within https://github.com/kubernetes/kubernetes/issues/119967

### What did you expect to happen?

The pod can be scheduled without restarting kube-scheduler

### How can we reproduce it (as minimally and precisely as possible)?

has not found the way to reproduce it

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

```
</details>
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.8-21+a0b942b9f8e3e0-dirty", GitCommit:"a0b942b9f8e3e0119c7a191537fc78491c852b1a", GitTreeState:"dirty", BuildDate:"2023-09-05T13:42:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

Linux master0 5.15.1300-0.el9.x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>
Linux master0 5.15.1300-0.el9.x86_64

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kerthcet** [comment]
/close 
As duplicated with https://github.com/kubernetes/kubernetes/issues/121866
