### ISSUE TITLE
refactor: `TestPriorityQueue_MoveAllToActiveOrBackoffQueue`

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes/kubernetes#120540]
`TestPriorityQueue_MoveAllToActiveOrBackoffQueue` is long and hard to read now.
https://github.com/kubernetes/kubernetes/blob/21f7bf66fa949dda2b3bec6e3581e248e270e001/pkg/scheduler/internal/queue/scheduling_queue_test.go#L1328

We want to make it more readable -- probably make it in a table-driven test style.

Also, we already have `TestPriorityQueue_MoveAllToActiveOrBackoffQueueWithQueueingHint`, we may be able to just merge these two tests.
https://github.com/kubernetes/kubernetes/blob/21f7bf66fa949dda2b3bec6e3581e248e270e001/pkg/scheduler/internal/queue/scheduling_queue_test.go#L1250C6-L1250C69

/kind cleanup
/sig scheduling

**Comment by mukeshmahato18** [comment]
I would like to help with this
/assign
