### ISSUE TITLE
[Failing Test] LoadBalancers should reconcile LB health check interval (gce-cos-master-serial)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#120537]
### Which jobs are failing?

master-informing:
- [gce-cos-master-serial](https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial)

### Which tests are failing?

`Kubernetes e2e suite.[It] [sig-network] LoadBalancers should reconcile LB health check interval [Slow][Serial][Disruptive]`

![Image](https://github.com/kubernetes/kubernetes/assets/73882557/f2efd6fd-1b0f-42bf-bacd-9223d073de18)

### Since when has it been failing?

2023-09-07 03:13:59 +0000 UTC

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#gce-cos-master-serial

### Reason for failure (if possible)

```
{ failed [FAILED] Health check "k8s-1f0b520ca457e326-node" does not reconcile its check interval to 8.
In [It] at: test/e2e/network/loadbalancer.go:813 @ 09/07/23 03:35:03.353
}
```

### Relevant SIG(s)

/sig network

**Comment by aojea** [comment]
Checking this failure https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1700707881789165568

This is running ingress-gce version, logs in https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-serial/1700707881789165568/artifacts/bootstrap-e2e-master/glbc.log

> I0910 03:15:34.075425       1 main.go:78] Starting GLBC image: "v1.23.1", cluster name ""

failure is

```
{ failed [FAILED] Health check "k8s-13c9e9b43c674c71-node" does not reconcile its check interval to 8.
In [It] at: test/e2e/network/loadbalancer.go:813 @ 09/10/23 06:30:02.132
}```


It seems the healthceck interval is not updated correctly, by reading the test

https://github.com/kubernetes/kubernetes/blob/49768134e527c1cdc93152f1c575062fb836c08e/test/e2e/network/loadbalancer.go#L787-L815

tagging the people with more expertise in this area 

/cc @swetharepakula @bowei @kl52752 @DamianSawicki

**Comment by aojea** [comment]
@bowei it seems the test restarts the kube-controller-manager but we landed recently the switch from intree to outtree cloud providers, so this logic now runs in the cloud-controller-manager, can this be the problem, that we have to restart the cloud-controller-manager now instead of the kcm?

**Comment by pacoxu** [comment]
/triage accepted


> it seems the test restarts the kube-controller-manager but we landed recently the switch from intree to outtree cloud providers

This flake started after https://github.com/kubernetes/kubernetes/pull/117503 and kept failing after 09-07.

**Comment by aojea** [comment]
> /triage accepted
> 
> > it seems the test restarts the kube-controller-manager but we landed recently the switch from intree to outtree cloud providers
> 
> This flake started after #117503 and kept failing after 09-07.

yeah, the logic that handles the loadbalancer shifted to that cloud controller manager with that PR
