### ISSUE TITLE
kubelet keeps error logging "Unable to write all bytes from execInContainer"

### ISSUE THREAD

**Issue by geotransformer** [kubernetes/kubernetes#120589]
### What happened?

ubuntu@my-aio:~$ sudo journalctl -u kubelet -f
-- Logs begin at Mon 2023-09-11 18:24:09 UTC. --
Sep 12 03:06:36 my-aio kubelet[51298]: E0912 03:06:36.073938   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:06:46 my-aio kubelet[51298]: E0912 03:06:46.031257   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:06:56 my-aio kubelet[51298]: E0912 03:06:56.031507   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:06 my-aio kubelet[51298]: E0912 03:07:06.020658   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:16 my-aio kubelet[51298]: E0912 03:07:16.077621   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:26 my-aio kubelet[51298]: E0912 03:07:26.104941   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:36 my-aio kubelet[51298]: E0912 03:07:36.039636   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:46 my-aio kubelet[51298]: E0912 03:07:46.070575   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:07:56 my-aio kubelet[51298]: E0912 03:07:56.073975   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:08:06 my-aio kubelet[51298]: E0912 03:08:06.035351   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:08:16 my-aio kubelet[51298]: E0912 03:08:16.093556   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240
Sep 12 03:08:26 my-aio kubelet[51298]: E0912 03:08:26.103162   51298 prober.go:241] "Unable to write all bytes from execInContainer" err="short write" expectedBytes=21147 actualBytes=10240

### What did you expect to happen?

If it is a critical issue, it shoud have more informative logs or crash

### How can we reproduce it (as minimally and precisely as possible)?

v1.26.7 kubeadm

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.7", GitCommit:"84e1fc493a47446df2e155e70fca768d2653a398", GitTreeState:"clean", BuildDate:"2023-07-19T12:16:45Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
$ uname -a
Linux 5.4.0-162-generic

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
$ kubectl get nodes -owide
NAME                 STATUS   ROLES           AGE     VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
my-aio  Ready    control-plane   3d11h   v1.26.7   172.20.187.109   <none>        Ubuntu 20.04.6 LTS   5.4.0-162-generic   containerd://1.7.2
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by geotransformer** [comment]
https://github.com/kubernetes/kubernetes/pull/105995/files
The error log was added in 1.25

**Comment by tzneal** [comment]
It was introduced in https://github.com/kubernetes/kubernetes/commit/5706a13bd6f5444f7dbadf5478e4912a1c8b9937.  My initial thought is that this is a feature and the fix would be on the container side to not produce as much data for a probe.

Limiting the write in the proposed fix may be more confusing as you'll just get a truncated output with no log indicating why.

**Comment by geotransformer** [comment]
> 

@tzneal  thanks, i will update our liveness probe.
