### ISSUE TITLE
Why does the speed of kubelet running pause container have slowed down?

### ISSUE THREAD

**Issue by qq690388648** [kubernetes/kubernetes#12068]
Today I raise a 2 minions cluster and create a 50 replica redis-controller-master rc, the rc take about 10 minutes to launch, that's much longer than one week ago ( about 50 seconds).
I see the kubelet's log and found it take 10 seconds to pulled a pause images and another 10 seconds to start it:
![default](https://cloud.githubusercontent.com/assets/13072423/9002760/76950efa-379a-11e5-8c0a-3672758b02dd.PNG)

And after all the pause containers has started, it only takes several seconds to started all the redis containers:
![default](https://cloud.githubusercontent.com/assets/13072423/9002791/bae11d74-379a-11e5-8857-4d25bc1810de.PNG)
I thought the behavior of starting redis containers is reasonable and that about pause container is unreasonable, why it?

**Comment by qq690388648** [comment]
After that, I try to use the --pod-infra-container-image=my_pause (my_pause is the image I change the tag the google's pause) to startup the kubelet, then everything is ok.
![default](https://cloud.githubusercontent.com/assets/13072423/9003751/49384446-37a3-11e5-9181-868849c46d5b.PNG)
I'm wonder what's wrong is it.

**Comment by dalanlan** [comment]
I assume it's a networking issue. You may have the local cache for redis but not for pause.

**Comment by qq690388648** [comment]
I do not think so, because:
1 I can see the "gcr.io/google_containers/pause:0.8.0" image is already on the slaves by typing "docker images"
2 I have done the test for many times and all of them show the same result.
@dalanlan

**Comment by dalanlan** [comment]
To be honest the pic format is not so friendly. Would you mind turning to a textual one? Will TAL later.

**Comment by qq690388648** [comment]
Sorry, the textual log is below.
When use the "gcr.io/google_containers/pause:0.8.0" image, we can see that  it take 10 seconds to pulled a pause images and another 10 seconds to start it:
"
I0803 10:57:59.596895  106231 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-c0isu", UID:"6be3ac42-398b-11e5-92b     9-28e0d488c694", APIVersion:"v1", ResourceVersion:"49", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_c     ontainers/pause:0.8.0" already present on machine
I0803 10:58:09.599311  106231 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-gvm6v", UID:"6be3b932-398b-11e5-92b     9-28e0d488c694", APIVersion:"v1", ResourceVersion:"53", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_c     ontainers/pause:0.8.0" already present on machine
I0803 10:58:19.599945  106231 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-ks0o6", UID:"6be3ef07-398b-11e5-92b     9-28e0d488c694", APIVersion:"v1", ResourceVersion:"61", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_c     ontainers/pause:0.8.0" already present on machine
I0803 10:58:29.601360  106231 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-9qi8e", UID:"6be417c2-398b-11e5-92b     9-28e0d488c694", APIVersion:"v1", ResourceVersion:"72", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_c     ontainers/pause:0.8.0" already present on machine
I0803 10:58:39.603383  106231 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-wt09t", UID:"6be44f11-398b-11e5-92b     9-28e0d488c694", APIVersion:"v1", ResourceVersion:"82", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "gcr.io/google_c     ontainers/pause:0.8.0" already present on machine
"
When use the image I have renamed, we can see that the time spending on pulling and starting is decreased, the log is below:
"
I0803 11:14:00.847648  114738 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-omb7h", UID:"af222d9c-398d-11e5-bb2b    -28e0d488c694", APIVersion:"v1", ResourceVersion:"51", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "my_pause" already     present on machine
I0803 11:14:00.943898  114738 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-b8olv", UID:"af225faf-398d-11e5-bb2b    -28e0d488c694", APIVersion:"v1", ResourceVersion:"68", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "my_pause" already     present on machine
I0803 11:14:01.512471  114738 server.go:594] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"redis-master-8tnoh", UID:"af2269d4-398d-11e5-bb2b    -28e0d488c694", APIVersion:"v1", ResourceVersion:"74", FieldPath:"implicitly required container POD"}): reason: 'pulled' Pod container image "my_pause" already     present on machine
"

**Comment by dalanlan** [comment]
Ic. Sorry about my previous misunderstanding.
Yet i was wondering what troubled you that much since we cannot tell the exact difference between "10 seconds" and "several seconds". 
No err logs seems all right to me, i'm afraid.

**Comment by qq690388648** [comment]
Oh, I found some interesting thing that may help.
When I typed "docker inspect gcr.io/google_containers/pause:0.8.0", it took about 10 seconds to return message. 
But when I typed "docker inspect my_pause", it returned the message immediately.
Now I know this issue may does not matter with kubernetes, but I really want to know what make this happen.
@dalanlan

**Comment by qq690388648** [comment]
Now I opened a new issue under the Docker, because I thought it was more likely the issue of Docker.
https://github.com/docker/docker/issues/15245

**Comment by dalanlan** [comment]
Uhh, i'll bet if you try `docker inspect <container_id>` instead of `docker inspect <container_name>`, you would get the result faster. (some stuff related to param parse, maybe)
You may read through the src code of docker, from where `docker/api/client/inspect.go` locates, if it might interest you.

**Comment by qq690388648** [comment]
Thank you, when I type <code>docker inspect</code>

**Comment by qq690388648** [comment]
I'm wrong.The kubernetes can not only set the "pod-infra-container-image" by name, but also set it by id, and that's my jury solution to this issue.
