### ISSUE TITLE
how to update pods by new image  without replicases changed.

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12065]
for example, i create a rc with 5  pods. their image is : redis:1.0
then  i want to update their image to redis:1.1

i edit rc.json ,and only  change spec.container[].image   from redis1.0 to redis1.1 
i exec:
kubectl replace -f rc.json

but nothing change....   all the pods are still  running  redis1.0 

i edit rc.json again, i add replicas  from 5  to 6.
then  the new one  pod  is running redis1.1 ,the others are still redis1.0

is it a bug?  
what should i do if i want to update one/all of my resources' image-version in a rc?

**Comment by bprashanth** [comment]
https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/user-guide/kubectl/kubectl_rolling-update.md#examples
