### ISSUE TITLE
SidecarContainers: update the description of InitContainerStatuses type

### ISSUE THREAD

**Issue by SergeyKanzhelev** [kubernetes/kubernetes#120676]
We need to update the field description for InitContainerStatuses to indicate the presence of Sidecar Containers there now.

https://github.com/kubernetes/kubernetes/blob/fc786dcd1d2efcc241e0e2392086934f2806555d/pkg/apis/core/types.go#L3736C41-L3736C41

KEP: https://github.com/kubernetes/enhancements/issues/753

/kind cleanup
/sig node

**Comment by bouaouda-achraf** [comment]
Is anyone working on this ? ( @pegasas ) 
I can ✋ ( before /.assign )

**Comment by SergeyKanzhelev** [comment]
> added a comment that statuses lists are not being validated #124918

This is mostly covered in https://github.com/kubernetes/kubernetes/pull/124918
