### ISSUE TITLE
node-e2e-features and node-e2e-unlabeled jobs are failing

### ISSUE THREAD

**Issue by mmiranda96** [kubernetes/kubernetes#120635]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-containerd#node-e2e-features
- https://testgrid.k8s.io/sig-node-containerd#node-e2e-unlabeled

### Which tests are failing?

Job fails to start.

### Since when has it been failing?

Forever (or at least as long as I can see)

### Reason for failure (if possible)

It seems that the jobs are misconfigured. An extract from the job logs:
```
W0911 12:43:35.271] 2023/09/11 12:43:35 main.go:746: --gcp-project is missing, trying to fetch a project from boskos.
W0911 12:43:35.271] (for local runs please set --gcp-project to your dev project)
W0911 12:43:35.271] 2023/09/11 12:43:35 main.go:758: provider gce, will acquire project type gce-project from boskos
W0911 12:43:35.271] 2023/09/11 12:43:35 process.go:153: Running: gcloud config set project k8s-infra-e2e-boskos-044
W0911 12:43:36.089] WARNING: You do not appear to have access to project [k8s-infra-e2e-boskos-044] or it does not exist.
```

### Relevant SIG(s)

/sig node

**Comment by SergeyKanzhelev** [comment]
both are passing now

/close
