### ISSUE TITLE
Automate vanity imports update and verify

### ISSUE THREAD

**Issue by jcchavezs** [kubernetes/kubernetes#120641]
### What would you like to be added?

Vanity imports to all packages, for example

```
package validatingwebhookconfiguration
```
into
```
package validatingwebhookconfiguration // import "k8s.io/kubernetes/pkg/registry/admissionregistration/validatingwebhookconfiguration"
```

**IMPORTANT:** Kubernetes repository already uses vanity imports, we just need to provide a check so new code includes it and provide a tool for users to regenerate vanity imports.

### Why is this needed?

Following https://github.com/kubernetes/kubernetes/issues/68231, vanity imports improves code navegability for a codebase with many packages as otherwise you need to figure out what the package is, the vanity URL and probably handtype the import path.

**Comment by neolit123** [comment]
cc @dims 
https://github.com/kubernetes/kubernetes/issues/68231 spoke about adding this to go.doc files.
but https://github.com/kubernetes/kubernetes/pull/120642 adds it everywhere. this is too noisy, not needed?

**Comment by jcchavezs** [comment]
I would when debugging APIs and going to the code files you end up in a `*.go` file and in the need to find out the package name, navigating to the corresponding `doc.go` is an extra step.

**Comment by liggitt** [comment]
I don't see a clear current problem this is solving, and the solution means a lot of contributors PRs will fail verify checks and require them to run more fixup scripts. That doesn't seem like a good trade.

**Comment by jcchavezs** [comment]
In one hand I see this might look like a huge impact but as I said, code already has vanity imports, it is just that it is inconsistent all across the code as some do use and some don't. This tool address the inconsistency, also fixes automatically code re-organization and it all happens under `make update` which does not seem to be too painful. I am also happy to only apply this to `doc.go` cc @dims
