### ISSUE TITLE
cloud-node-lifecycle controller: shutdownInCloudProvider fails for node with no provider ID

### ISSUE THREAD

**Issue by mkowalski** [kubernetes/kubernetes#120617]
### What happened?

When function `shutdownInCloudProvider` is called with a Node object that has a correct name but empty provider ID in its spec and error occurs due to an attempt to call `InstanceShutdownByProviderID` with empty ID. An example of behaviour is shown below

```
I0912 00:38:54.328410       1 instances.go:160] instances.InstanceExistsByProviderID() EXISTS with 421b1d8a-b521-c466-0b89-c7737fd557d0
I0912 00:38:54.328423       1 instances.go:204] instances.InstanceShutdownByProviderID() NOT CACHED
I0912 00:38:54.328431       1 search.go:49] WhichVCandDCByNodeID called but nodeID is empty
E0912 00:38:54.328446       1 nodemanager.go:197] shakeOutNodeIDLookup failed. Err=nodeID is empty
E0912 00:38:54.328457       1 node_lifecycle_controller.go:185] error checking if node ci-op-k0wgj55m-42849-6fnh9-master-2 is shutdown: nodeID is empty
```

### What did you expect to happen?

If `shutdownInCloudProvider` is called with Node object that has a correct name and empty provider ID, we should obtain a provider ID based on the name of the instance. This way `InstanceShutdownByProviderID` can be called with a valid UUID and return a correct result.

### How can we reproduce it (as minimally and precisely as possible)?

Call `shutdownInCloudProvider` function with the node object that has a name referencing a real VM in the underlying provider but empty provider ID in its spec.

### Kubernetes version

1.27

### Cloud provider

vSphere

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle
/sig cloud-provider

SIG CP info:
https://github.com/kubernetes/community/tree/master/sig-cloud-provider#contact
