### ISSUE TITLE
Updating pods during scheduling may produce dirty data

### ISSUE THREAD

**Issue by chaohan1** [kubernetes/kubernetes#120662]
### What happened?

If we update a pod（such as update annotation） during the scheduling process, the scheduler's podInformer will generate an update event. If the pod has not been assumed at this time, this event will be added to the scheduling queue. When the pod is scheduled succeed, since the pod is still in the scheduling queue, the pod may be scheduled again. 

If there are many pods in the scheduling queue, the pod cannot be scheduled until 30 seconds later. At this time, the pod information in assumedPods has been cleared, and the pod will be scheduled again. Since the pod has been scheduled succeed, this scheduling will fail, and the scheduler will continue to retry, repeating the cycle. This pod will always become dirty data in the scheduler unless the scheduler is restarted.

### What did you expect to happen?

If the pod has been scheduled succeed, the scheduler should not schedule dirty data in the queue.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod；
2. When the pod starts scheduling, update the pod before assume（This step can be achieved by adding breakpoints through local debugging）；
3. After the update event generated by the pod enters the scheduling queue, we should guaranteed the pod  to be scheduled again after 30 seconds（Implemented through local breakpoint debugging）；
4. The pod has been scheduled, but the scheduler is still scheduling the pod in a loop.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
k8s 1.19.4
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by raghu-007** [comment]
Ensure that initial requests and restrictions for your crop are properly entered so that rescheduling is not required due to resource limitations.

**Comment by AxeZhan** [comment]
v1.19.4 is too old to support now.  Can you try this behavior with the newest release?

**Comment by chaohan1** [comment]
Thank you, I have tried the latest scheduler and the problem no longer exists, I will close this issue now.

**Comment by juliusmh** [comment]
the Issue exists on 1.23. Instead, adding # annotations can be achieved by using Annotations on the Binding resource in the Bind phase.
