### ISSUE TITLE
[Flaky] [sig-apps] [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#120650]
### Failure cluster [3b8233b83202fc3fc7a1](https://go.k8s.io/triage#3b8233b83202fc3fc7a1)

- [sig-apps] StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]

##### Error text:
```
[FAILED] Pod statefulset-8771/ss2-0 has image registry.k8s.io/e2e-test-images/httpd:2.4.39-4 not equal to previous image registry.k8s.io/e2e-test-images/httpd:2.4.38-4
Expected
    <string>: registry.k8s.io/e2e-test-images/httpd:2.4.39-4
to equal
    <string>: registry.k8s.io/e2e-test-images/httpd:2.4.38-4
In [It] at: test/e2e/apps/statefulset.go:1935 @ 09/13/23 08:12:10.161

```
#### Recent failures:
[2023/9/14 08:34:51 ci-kubernetes-kind-e2e-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1702118188218585088)
[2023/9/14 05:34:49 ci-kubernetes-kind-e2e-parallel](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-kind-e2e-parallel/1702072889462755328)

/kind flake
/sig apps
/cc @kubernetes/ci-signal 

https://testgrid.k8s.io/sig-release-master-blocking#kind-master-parallel

**Comment by pacoxu** [comment]
The test also flake in https://testgrid.k8s.io/sig-release-master-informing#capz-windows-master which is tracked in https://github.com/kubernetes/kubernetes/issues/108711

**Comment by pacoxu** [comment]
/triage accepted
 5 failure in recent 15 runs.(33%)

**Comment by aojea** [comment]
@pacoxu I didn't realize this was open, do you mind if we close this and we move to https://github.com/kubernetes/kubernetes/issues/120700 since I Already did the investigation and found the (most probably)  reason ?

**Comment by pacoxu** [comment]
Close in favor of #120700
