### ISSUE TITLE
Scale max-pods resource per machine resources.

### ISSUE THREAD

**Issue by gmarek** [kubernetes/kubernetes#12069]
Split-off from #4910

**Comment by gmarek** [comment]
Do we still want to do this? @thockin @davidopp @smarterclayton

**Comment by davidopp** [comment]
I think so, but we should probably think about this along with setting resource limits on the various node agents and addon pods that scales appropriately with machine size. Let's leave it open at P2.

**Comment by thockin** [comment]
agree

On Sat, Aug 22, 2015 at 1:38 AM, David Oppenheimer <notifications@github.com

**Comment by bgrant0607** [comment]
Max pods should be for protecting Kubelet due to scaling limitations.

**Comment by gmarek** [comment]
We're moving to max-pods-per-core performance definition. We'll need to implement this. cc @wojtek-t
