### ISSUE TITLE
Garbage collector for container images is unpredictable and inconsistent

### ISSUE THREAD

**Issue by mfranzil** [kubernetes/kubernetes#120659]
### What happened?

The garbage collector for container image lifecycle does not seem to adhere to the documentation and the provided parameters.

From [the docs](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#container-image-lifecycle), _the configured HighThresholdPercent value triggers garbage collection, which deletes images in order based on the last time they were used, starting with the oldest first. The kubelet deletes images until disk usage reaches the LowThresholdPercent value._

From some tests, this does not appear to be the case. Often, the GC will delete way more images than requires, often dropping below `LowThresholdPercent` and deleting 3 to 4 at a time.

### What did you expect to happen?

The GC should delete images until `LowThresholdPercent` is reached.

### How can we reproduce it (as minimally and precisely as possible)?

1. Either create some dummy images (we created a set of images with increasing sizes, but any will do the job), or identify some appropriate image already available on Docker Hub.
2. For each image, deploy a pod and then delete it. The image will remain in the cache.
3. After a while, the disk space will reach the `LowThresholdPercent` first and `HighThresholdPercent` later. The GC will be triggered.
4. The GC should in theory delete the earliest unused image. This does not always happen: priority is sometimes given to other images, or more than one is deleted, in a seemingly random order.

### Anything else we need to know?

The bug is hard to reproduce and needs some trial and error. Sometimes, images are correctly deleted in order and one at a time, other times the behaviour is apparently random.

If this behaviour is expected, then the docs should be appropriately corrected to mention the choices the GC makes. This is important as I/O spikes in the GC may cause SLA issues in other services deployed in the node.

### Kubernetes version

<details>

```console
$ kubectl version -o yaml
clientVersion:
  buildDate: "2023-04-14T13:21:19Z"
  compiler: gc
  gitCommit: 4c9411232e10168d7b050c49a1b59f6df9d7ea4b
  gitTreeState: clean
  gitVersion: v1.27.1
  goVersion: go1.20.3
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-08-24T00:42:11Z"
  compiler: gc
  gitCommit: 93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c
  gitTreeState: clean
  gitVersion: v1.27.5
  goVersion: go1.20.7
  major: "1"
  minor: "27"
  platform: linux/amd64
```

</details>

### Cloud provider

<details>
Private cloud
</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
$ uname -a
Linux worker2 5.4.0-146-generic #163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Install tools

<details>
  None. Installed via the official script with curl.
</details>

### Container runtime (CRI) and version (if applicable)

<details>

```
$ sudo ctr version
Client:
  Version:  1.6.22
  Revision: 8165feabfdfe38c65b599c4993d227328c231fca
  Go version: go1.19.11

Server:
  Version:  1.6.22
  Revision: 8165feabfdfe38c65b599c4993d227328c231fca
  UUID: f631674b-a911-4d6b-96bb-2b79ffd6b878
```

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
  None.
</details>

**Comment by uablrek** [comment]
The implementation in `kubelet`:

https://github.com/kubernetes/kubernetes/blob/09200e9c92784f6fb9210e6287e306649a731673/pkg/kubelet/images/image_gc_manager.go#L309

The `RemoveImage()` call will eventually be passed to the "CRI-plugin" via the [Container Runtime Interface](https://kubernetes.io/docs/concepts/architecture/cri/), so the behaviour is dependent on your CRI-plugin, usually `cri-o` or `containerd`.

The logic seem pretty straight forward and is probably OK, but it assumes that when you delete an image of `X` MB, then `X` MB is freed on disk, but that is likely not the case.

Images share `layers`, so if a layer is used by another image, it will not be deleted (and no disk space freed). The figure shows 3 images with 1G "blob" layers:

<img src="https://github.com/kubernetes/kubernetes/assets/37046727/485b50cf-25ee-426c-ba04-2b94f91a89db" width="70%" />

1. The image GC discovers that it has to free 1G
2. It deletes Image1, but since the "blob1" layer is used no space is freed
3. The image GC discovers that is *still* has to free 1G
4. It deletes Image2, but the layes are used so no space is freed
5. The image GC discovers that is *still* has to free 1G
6. It deletes Image3, and now 3G is freed

IMO this is consistent with the observed behaviour in this issue.

**Comment by uablrek** [comment]
## Reproduce

This can be "simulated" without creating any PODs using the `crictl` tool. It works with any compliant CRI-plugin, like `cri-o` or `containerd`.

First create the 3 images, and **please use a [private registry](https://docs.docker.com/registry/)!**

Dockerfile1
```
FROM alpine:latest
RUN truncate -s 1G /blob1
CMD ["/bin/tail", "-f", "/dev/null"]
```
Create image1
```
docker build -f Dockerfile1 -t example.com/blobs/blob1:local .
```

Dockerfile2
```
FROM example.com/blobs/blob1:local
RUN truncate -s 1G /blob2
CMD ["/bin/tail", "-f", "/dev/null"]
```
Create image2
```
docker build -f Dockerfile2 -t example.com/blobs/blob2:local .
```

Dockerfile3
```
FROM example.com/blobs/blob2:local
RUN truncate -s 1G /blob3
CMD ["/bin/tail", "-f", "/dev/null"]
```
Create image3
```
docker build -f Dockerfile3 -t example.com/blobs/blob3:local .
```

Now the images can be pulled from any K8s node. I have ensured that `example.com` resolves to my private registry. I run on minimalist VMs with 8G rootfs, so the sizes are quite visible:

Pull images
```
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G    839.9M      6.6G  11% /
vm-001 ~ # crictl pull example.com/blobs/blob1:local
Image is up to date for example.com/blobs/blob1@sha256:f9e8eca1284330930fbc2023f595a3692d3b4c4baf1103fd32f8f02a815a5540
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G      1.8G      5.6G  25% /
vm-001 ~ # crictl pull example.com/blobs/blob2:local
Image is up to date for example.com/blobs/blob2@sha256:ac1095a35a140029d1b0bec9ee171c873ee630b4bfb17cc966d10ea20e41c5df
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G      2.8G      4.6G  38% /
vm-001 ~ # crictl pull example.com/blobs/blob3:local
Image is up to date for example.com/blobs/blob3@sha256:26ce42c04d1cdf21a28bed9fa16a87363190e5c2649c363d90d1a22420779e32
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G      3.8G      3.6G  52% /
```

Delete images:
```
vm-001 ~ # crictl rmi example.com/blobs/blob1:local
Deleted: example.com/blobs/blob1:local
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G      3.8G      3.6G  52% /
vm-001 ~ # crictl rmi example.com/blobs/blob2:local
Deleted: example.com/blobs/blob2:local
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G      3.8G      3.6G  52% /
vm-001 ~ # crictl rmi example.com/blobs/blob3:local
Deleted: example.com/blobs/blob3:local
vm-001 ~ # df -h /
Filesystem                Size      Used Available Use% Mounted on
/dev/vda                  7.8G    840.3M      6.6G  11% /
```

**Comment by uablrek** [comment]
Oh, and you may think that layers are rarely shared? But "Ubuntu" (or other distros) layers for instance, are very likely to be shared

**Comment by uablrek** [comment]
IMHO this is not a bug in K8s. I can't see how K8s can do this in a better way without making the CRI very complicated, or dump the responsibility on the CRI-plugin, e.g. adding a "FreeSpace()" function in the CRI.

**Comment by ndixita** [comment]
@mfranzil Could you please confirm the suggestions provided by @uablrek are what you are actually seeing here?

**Comment by mfranzil** [comment]
Ok. Our previous findings were not sharing any layer (apart from the Ubuntu one. Which, by the way, is indeed likely to be shared, but it is also usually so small that it is unlikely to affect the GC's behaviour, I would say). Thus, to clarify, we have done a different scenario:

- we created 4 images with random content, each of size approx. 3 GB compressed and 6 GB uncompressed;
- we artificially inflated the storage by creating some large file, s.t. the space used before the experiment was 75%;
- we ensure that each image shared no layer.

This size is deliberate so that, with our setup (~124 GB disk size), the GC will need to delete between one and two images to drop below the 80% threshold.

We then repeated the experiment as done before,

**Comment by mfranzil** [comment]
Sorry for the accidental close and reply, I will properly reply in a moment

**Comment by mfranzil** [comment]
Ok. Our previous findings were not sharing any layer, apart from the Ubuntu one. Which, by the way, is indeed likely to be shared, but it is also usually so small that it is unlikely to affect the GC's behaviour I'd say.

To clarify, we are testing with a slightly different scenario:

- we created 4 images with random content, each of size approx. 3 GB compressed and 6 GB uncompressed;
- we artificially inflated the torage by creating some large file, s.t. the space used before the experiment was 68%;
- we ensure that each image shared no layer (again, Ubuntu excluded).

This size is deliberate so that, with our setup (~124 GB disk size), the GC will need to delete between one and two images to drop below the 80% threshold.

We are trying to run a few tests on this setup, but we need some more time to finish that. What we observed, though, is that if images manage to reach the 90% eviction threshold, the node just goes into mayhem mode and deletes more images than necessary. So probably also that is another hint.

As soon as we have enough time to generate it with a replicable example, we will reopen the discussion.

**Comment by SergeyKanzhelev** [comment]
So GC should delete every image that is unused and more than the minimal age. This is working as expected. Do you want more images to stay around? There is a setting of minimal age of an image that may prevent image from being deleted, but if you downloaded them together - it will not help, GC will clear up everything that is qualified.

Perhaps the change in GC to be lazy instead of agressive can be a good feature request.

/remove-kind bug
/kind feature

Eviction will work differently. Once it detects the issue it will start removing pods with their images. And it will delete as little as possible.
