### ISSUE TITLE
PRISMA-2022-0227: Go-restful v3.9.0 is vulnerable to Authentication Bypass

### ISSUE THREAD

**Issue by rmorelnetapps** [kubernetes/kubernetes#120604]
### What would you like to be added?

Hello! Not sure if I am right but we found out that this CVE PRISMA-2022-0227, says that go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness, also it says that the inconsistency could lead to several security check bypass

### Why is this needed?

I see that there's a pr open to [bump go-restful to 3.10.2](https://github.com/kubernetes/kubernetes/pull/119865), is there a timeline to merge this change?

**Comment by dims** [comment]
https://github.com/kubernetes/kubernetes/pull/119865 is merged!
