### ISSUE TITLE
TestWebSocketClient_HeartbeatSucceeds ut flakes（also shown as remotecommand）

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#120684]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1702464725629014016

FAIL: TestWebSocketClient_HeartbeatSucceeds 

k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand.remotecommand

### Which tests are flaking?

> Failed;  === RUN   TestWebSocketClient_HeartbeatSucceeds
> E0915 00:06:07.556630   64709 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:49548->127.0.0.1:38391: use of closed network connection
>     websocket_test.go:1093: unexpected heartbeat timeout
> E0915 00:06:07.606331   64709 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:49548->127.0.0.1:38391: use of closed network connection
> --- FAIL: TestWebSocketClient_HeartbeatSucceeds (0.06s)
> 

### Since when has it been flaking?

Added last week in https://github.com/kubernetes/kubernetes/commit/a0d6a815fcc02cbfea1bb22d13a8e896ecbe116c#diff-33da81ac4e24e52fae888fc3a4f2d15ff48fba5b52065fab62bf9f2224cc8204R1044

https://github.com/kubernetes/kubernetes/pull/119157

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit

also flake in https://storage.googleapis.com/k8s-triage/index.html?text=HeartbeatSucceeds  ci-kubernetes-unit

### Reason for failure (if possible)

use of closed network connection

### Anything else we need to know?

/cc @seans3 @aojea

### Relevant SIG(s)

/sig api-machinery network cli

**Comment by aojea** [comment]
seems it got better since https://github.com/kubernetes/kubernetes/pull/120694

**Comment by pacoxu** [comment]
> seems it got better since #120694

The new flake in this test is like 
```
Failed;
    testing.go:1465: race detected during execution of test
FAIL
FAIL	k8s.io/kubernetes/vendor/k8s.io/client-go/tools/remotecommand	9.641s
;
```
#### Recent failures:
[2023/9/21 09:21:58 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1704666704941944832)
[2023/9/20 13:13:33 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1704362629985734656)
[2023/9/19 18:04:07 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1704073348683665408)
[2023/9/19 03:59:06 ci-kubernetes-unit](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-unit/1703860695449210880)


https://storage.googleapis.com/k8s-triage/index.html?text=remotecommand

I also see the failure in some PR: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/120793/pull-kubernetes-unit/1704784613487939584 for instance.

**Comment by aojea** [comment]
yeah, it is racing somewhere , at least we have a different symptom now 👀

**Comment by aojea** [comment]
/help

someone want a great challenge and make a very useful contribution?

https://gist.github.com/liggitt/6a3a2217fa5f846b52519acfc0ffece0

**Comment by aojea** [comment]
something odd is with the test, the panic is because it logs on the goroutine, but I'm not completely sure the test is working as expected

**Comment by aojea** [comment]
@zxh326 my apologies, I found the problem and I'm submitting a patch
/assign @aojea 
/unassign @zxh326 

you can help me with the review if you want
