### ISSUE TITLE
build failed with empty KUBE_GIT_VERSION variable

### ISSUE THREAD

**Issue by pbxqdown** [kubernetes/kubernetes#120685]
**What happened**:
When I tried to build kubernetes locally using `kubetest --build` command, I got error:
```
+++ [0815 00:26:53] Syncing out of container
+++ [0815 00:27:01] Building tarball: src
+++ [0815 00:27:01] Building tarball: manifests
+++ [0815 00:27:01] Starting tarball: client linux-amd64
+++ [0815 00:27:01] Waiting on tarballs
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
tar: Removing leading `/' from member names
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
tar: Removing leading `/' from member names
+++ [0815 00:27:08] Building tarball: node linux-amd64
+++ [0815 00:27:09] Building images: linux-amd64
!!! [0815 00:27:09] git version information missing; cannot create Docker tag
!!! [0815 00:27:09] Call tree:
!!! [0815 00:27:09]  1: /home/qian/go/src/k8s.io/kubernetes/build/lib/release.sh:198 kube::release::create_docker_images_for_server(...)
!!! [0815 00:27:09]  2: /home/qian/go/src/k8s.io/kubernetes/build/lib/release.sh:204 kube::release::build_server_images(...)
!!! [0815 00:27:09]  3: /home/qian/go/src/k8s.io/kubernetes/build/lib/release.sh:54 kube::release::package_server_tarballs(...)
!!! [0815 00:27:09]  4: build/release.sh:45 kube::release::package_tarballs(...)
!!! [0815 00:27:23] previous tarball phase failed
make: *** [Makefile:427: quick-release] Error 1
make: Leaving directory '/home/qian/go/src/k8s.io/kubernetes'
2023/08/15 00:27:23 process.go:155: Step 'make -C /home/qian/go/src/k8s.io/kubernetes quick-release' finished in 2m3.328538827s
2023/08/15 00:27:23 main.go:328: Something went wrong: failed to acquire k8s binaries: error during make -C /home/qian/go/src/k8s.io/kubernetes quick-release: exit status 2
```

**What you expected to happen**:
`kubetest --build` should work without `KUBE_GIT_VERSION` specified. Or doc should mention this if the variable is required.

**How to reproduce it (as minimally and precisely as possible)**:
Run `kubetest --build` in freshly installed ubuntu22.04.
**Please provide links to example occurrences, if any**:
N/A
**Anything else we need to know?**:
None

```[tasklist]
### Tasks
```

**Comment by pbxqdown** [comment]
@BenTheElder thanks for triaging this! I think this issue is a gotcha for newbie developer, usually hard to find without other's hint. Is there a gotchas page in Kubernetes doc where we can add this issue and the fix?

**Comment by BenTheElder** [comment]
/remove-sig docs
/sig contributor-experience

There's a guide for setting up your development environment that should cover git cloning correctly

https://github.com/kubernetes/kubernetes#to-start-developing-k8s
=>
https://github.com/kubernetes/community/tree/master/contributors/devel#readme
=>
https://github.com/kubernetes/community/tree/master/contributors/devel#setting-up-your-dev-environment-coding-and-debugging
=>
https://github.com/kubernetes/community/blob/master/contributors/devel/development.md

I think we should add a note to that last link.

**Comment by pbxqdown** [comment]
I'm following this part: https://github.com/kubernetes/kubernetes#you-have-a-working-docker-environment
```
git clone https://github.com/kubernetes/kubernetes
cd kubernetes
make quick-release
```
It seems assume that we clone from main k8s repo directly. However in GitHub environment developers usually fork k8s repo. git tag info may be lost during that process. I think we should add a note in that section or an additional Gotchas section can be added to the doc.

**Comment by BenTheElder** [comment]
> It seems assume that we clone from main k8s repo directly. However in GitHub environment developers usually fork k8s repo. git tag info may be lost during that process. I think we should add a note in that section or an additional Gotchas section can be added to the doc.

There used to be explicit guidance somewhere to setup an `upstream` and `origin` git remote for the clone, for kubernetes/kubernetes and your fork respectively (and fetch both). Various tools and scripts make this assumption and we should make sure that's covered.

**Comment by pbxqdown** [comment]
@BenTheElder make sense. Is the guidance lost or too deep to find? I think we should highlight that section in main k8s doc.

**Comment by BenTheElder** [comment]
I'm not sure, it was in a totally different place when I started, I think it's still a good idea and I'm certain at least the cherry pick helper script still references `upstream` vs `origin` but I don't know what happened to those docs.

I agree we should cover this early in setting up the development environment, I've seen broken builds due to no git tags come up in issues before but this is the first time it's clear how and why that happened 😅

**Comment by pbxqdown** [comment]
Yes. another option may be embedding `git fetch` command inside helper script so user doesn't have to explicitly run the command. Doing it automatically is better than following docs. I indeed saw some util functions to check upstream branch inside helper script: https://github.com/kubernetes/kubernetes/blob/7dcb4126753fac7fa1a08a7af584a3ceeccab31c/hack/lib/util.sh#L383

Shall we engage community manager of sig-contributor-experience for this issue?
