### ISSUE TITLE
[Documentation Support] Compatibility matrix between docker and k8s (<1.24.x)

### ISSUE THREAD

**Issue by freemankevin** [kubernetes/kubernetes#120686]
### What would you like to be added?

Dear friends, although k8s 1.24.x will no longer support docker, before k8s v1.24.x, is there an entry point for querying the direct compatibility matrix with docker-ce? 

### Why is this needed?

Due to restrictions, team maintenance costs and business needs, we are still using versions below v1.24.x, but we encountered problems such as `pthread_create failed: Operation not permitted` during use, and we need to upgrade the docker version, but I am not sure what the version compatibility relationship between docker and k8s is. I would like to confirm it with the official side. Thank you very much.

**Comment by neolit123** [comment]
> ### What would you like to be added?
> Dear friends, although k8s 1.24.x will no longer support docker, before k8s v1.24.x, is there an entry point for querying the direct compatibility matrix with docker-ce?
> 
> ### Why is this needed?
> Due to restrictions, team maintenance costs and business needs, we are still using versions below v1.24.x, but we encountered problems such as `pthread_create failed: Operation not permitted` during use, and we need to upgrade the docker version, but I am not sure what the version compatibility relationship between docker and k8s is. I would like to confirm it with the official side. Thank you very much.

hi, is anything preventing you from moving to cri-dockerd?
https://github.com/Mirantis/cri-dockerd
https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/migrate-dockershim-dockerd/

it will allow you to use docker with latest k8s.

your matrix feature request to continue supporting docker will likely be rejected.

/sig node architecture

**Comment by freemankevin** [comment]
There are no plans to migrate or upgrade at the moment. The main reason is that our developers are more familiar with Dockerfile and how to play Docker. If we really want to follow the mainstream technology trend, we should also use contained. However, there is no such rigid need at present. The first priority at present is If you can still use Docker, use Docker.

**Comment by neolit123** [comment]
> /sig node architecture

i will let the assigned SIG representatives to comment.

**Comment by afbjorklund** [comment]
cri-dockerd does not support kubernetes versions before 1.24, since those were supposed to use dockershim

**Comment by freemankevin** [comment]
Dear Maintainer,

Thank you for your detailed response. We will seriously consider the changes and upgrade scheme you've mentioned. Currently, we've directly upgraded to v24.x. Although this entails some risk, everything is running smoothly so far. 

As such, I have no other concerns and will proceed to close this issue.

---

**P.S.** I have a suggestion to make:

As long-term community users, we may not always be able to promptly follow the mainstream or secondary versions due to various reasons. Therefore, we would highly appreciate if some space could be dedicated in the official documentation or relevant GitHub.md files for crucial information that might seem trivial. This would facilitate a more convenient and intuitive understanding of the mainstream version evolution:

- **Compatibility Information:** Including supported operating systems and their versions, supported architectures and versions, supported CRIs and versions, etc.

- **Architectural Evolution:** A roadmap indicating the changes in the architecture over time. Visual aids would be appreciated for better clarity.

- **Feature Changes:** A list of feature changes under the timeline of version evolution, such as additions or removals.

---

That's all I wanted to bring up at this time. Again, I deeply appreciate your assistance and patience throughout this discussion. Wishing you a pleasant day ahead!
