### ISSUE TITLE
kube-proxy discards command line args

### ISSUE THREAD

**Issue by aroradaman** [kubernetes/kubernetes#120603]
### What happened?

https://github.com/kubernetes/kubernetes/pull/55261 introduced a change to reload config from file and this happens after parsing all the command line flags and hence discards all the command line flags. 

https://github.com/kubernetes/kubernetes/blob/35199e42a41f83520e640fbfa9f409516faa7501/cmd/kube-proxy/app/server.go#L245-L259

### What did you expect to happen?

kube-proxy should respect all the command line arguments and if for some reason we need to load config from file we must do it in a way that preserves all command line flags. 

I'm trying to add three additional configuration params to kube-proxy in  https://github.com/kubernetes/kubernetes/pull/120354
1. **conntrack-tcp-be-liberal**
2. **conntrack-udp-timeout**
3. **conntrack-udp-timeout-stream**

I'm not able to use 2 and 3 via command line args. 1 works as I'm syncing it manually.

### How can we reproduce it (as minimally and precisely as possible)?

If I comment out the following line and rebuild kube-proxy for the local kind cluster, kube-proxy fails with the following logs:

```
I0912 12:58:03.614728       1 server_others.go:367] "GetConntrackMax: using scaled conntrack-max-per-core"
I0912 12:58:03.614756       1 conntrack.go:118] "Set sysctl" entry="net/netfilter/nf_conntrack_max" value=655360
E0912 12:58:03.614765       1 server.go:557] "Error running ProxyServer" err="open /proc/sys/net/netfilter/nf_conntrack_max: permission denied"
E0912 12:58:03.614775       1 run.go:74] "command failed" err="open /proc/sys/net/netfilter/nf_conntrack_max: permission denied"
```
I guess after commenting out the following line kube-proxy actually tries to run conntrack sysctls and since kind /proc/sys is read-only for kind it fails.

https://github.com/kubernetes/kubernetes/blob/35199e42a41f83520e640fbfa9f409516faa7501/cmd/kube-proxy/app/server.go#L259

### Anything else we need to know?

Current Flow:

```go
// 1. initialize options
// this internally calls newKubeProxyConfiguration() which generates kube-proxy config with default values
opts := NewOptions()

// 2. add command-line flags
opts.AddFlags(fs)

// 3. complete all the required flags, read config from the file losing defaults and
// values provided by command line flags
opts.Complete()

// 4. validate all the required options
opts.Validate()

// 5. run the kube-proxy
opts.Run()
```

In step 3 we lose all the default and pflag values. 
 

### Kubernetes version

<details>
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0-alpha.0.725+f862a44dea7b92
</details>

### Cloud provider

<details>
kind
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jayunit100** [comment]
We had a KEP to fix this but it died https://github.com/kubernetes/enhancements/issues/2157 off.... 

IIRC Liggit and others ultimately mentinoed that, command line args simply arent sustainable. 

https://github.com/kubernetes/enhancements/pull/2158#discussion_r616788544

**Comment by aojea** [comment]
that is intended, as Jay says there is much pain here, but current situation is "in general" config override flags (except the hostnameOverride and log verbosity flag)

**Comment by aroradaman** [comment]
closing as this is know/expected 
/close
