### ISSUE TITLE
 watch chan error: etcdserver: no leader

### ISSUE THREAD

**Issue by liuyanzhen34** [kubernetes/kubernetes#120648]
Hello teachers, may I ask a question: I upgraded the binary deployed K8 cluster from 1.19.12 to 1.20.0. The upgrade method was to replace the binary file of 1.19.12 with the binary file of 1.20.0, and made adjustments to the configuration file. The ETCD version is 3.3.9, and the ETCD did not change during the upgrade process. It is still the ETCD cluster used before 1.19.12. But when I upgraded the k8s from version 1.19.12 to 1.20.0, I executed 【 kubectl get node】 and finally reported a timeout. Check that the ETCD cluster is good; Check the logs of kube apiserver and there are errors reported. The specific information is as follows:

etcd  version 3.3.9 cluster info:
[root@k8s-master1 ~]#  ETCDCTL_API=3 etcdctl --write-out="table" --endpoints=192.168.80.201:2379,192.168.80.202:2379,192.168.80.203:2379 endpoint status
+---------------------+------------------+---------+---------+-----------+-----------+------------+
|      ENDPOINT       |        ID        | VERSION | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX |
+---------------------+------------------+---------+---------+-----------+-----------+------------+
| 192.168.80.201:2379 | f1103f744b8d0802 |   3.3.9 |   11 MB |      true |      1290 |     150275 |
| 192.168.80.202:2379 | 8850862b4b770466 |   3.3.9 |   11 MB |     false |      1290 |     150275 |
| 192.168.80.203:2379 | 52afc12a6ac9b029 |   3.3.9 |   11 MB |     false |      1290 |     150275 |
+---------------------+------------------+---------+---------+-----------+-----------+------------+

kube-apiserver logs:

[root@k8s-master1 ~]# systemctl status kube-apiserver
● kube-apiserver.service - Kubernetes API Server
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since 四 2023-09-14 09:23:40 CST; 6min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 3255 (kube-apiserver)
    Tasks: 7
   Memory: 369.2M
   CGroup: /system.slice/kube-apiserver.service
           └─3255 /usr/bin/kube-apiserver --insecure-bind-address=0.0.0.0 --insecure-port=0 --authorization-mode=RBAC --anonymous-auth=false --log-dir=/apps/log/kubernetes --etcd-servers=h...

9月 14 09:23:27 k8s-master1 systemd[1]: kube-apiserver.service holdoff time over, scheduling restart.
9月 14 09:23:27 k8s-master1 systemd[1]: Stopped Kubernetes API Server.
9月 14 09:23:27 k8s-master1 systemd[1]: Starting Kubernetes API Server...
9月 14 09:23:27 k8s-master1 kube-apiserver[3255]: Flag --insecure-bind-address has been deprecated, This flag has no effect now and will be removed in v1.24.
9月 14 09:23:27 k8s-master1 kube-apiserver[3255]: Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
9月 14 09:23:40 k8s-master1 systemd[1]: Started Kubernetes API Server.
9月 14 09:28:47 k8s-master1 kube-apiserver[3255]: E0914 09:28:47.983761    3255 watcher.go:218] watch chan error: etcdserver: no leader
9月 14 09:28:47 k8s-master1 kube-apiserver[3255]: E0914 09:28:47.986650    3255 watcher.go:218] watch chan error: etcdserver: no leader
9月 14 09:28:47 k8s-master1 kube-apiserver[3255]: E0914 09:28:47.986766    3255 watcher.go:218] watch chan error: etcdserver: no leader
9月 14 09:29:04 k8s-master1 kube-apiserver[3255]: E0914 09:29:04.089948    3255 watcher.go:218] watch chan error: etcdserver: no leader

**Comment by liuyanzhen34** [comment]
[root@k8s-master1 ~]# kubectl get node
Unable to connect to the server: context deadline exceeded
[root@k8s-master1 ~]#

**Comment by liuyanzhen34** [comment]
Is it due to the incompatibility between the version of ETCD 3.3.9 and the version of K8S 1.20.0? Looking at the official website of ETCD and the official website of K8S, we also found information on compatibility and matching between the two versions. However, on Github Kubernetes, we can see that compared to K8S 1.20.0 and 1.19.0, there is the following description in the changed section: Github. com/cores/ETCD: [v3.3.10+compatible → v3.3.13+compatible]（



What does incompatibility mean here? Is there any compatibility between the K8S version and the ETCD version? Looking forward to the patient answers and replies from all experts and teachers. Thank you very much

**Comment by neolit123** [comment]
this sounds like a setup issue and not a bug.

a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
