### ISSUE TITLE
what does "v3.5.0+incompatible → v3.5.1+incompatible" mean ?

### ISSUE THREAD

**Issue by liuyanzhen34** [kubernetes/kubernetes#120632]
Hello,I have a question that confused me for a long time. 

I see the following sentence from k8s documentation 
 (https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md) on k8s 1.20.0  changed log:

github.com/blang/semver: [[v3.5.0+incompatible → v3.5.1+incompatible](https://github.com/blang/semver/compare/v3.5.0...v3.5.1)](

**Comment by neolit123** [comment]
answer
https://stackoverflow.com/questions/57355929/what-does-incompatible-in-go-mod-mean-will-it-cause-harm

/kind support
/close

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md
