### ISSUE TITLE
shutting down minion, Node state reads Ready

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12066]
I have two minions running in my set up and a master. I turned off one of the minion machine but when I run the command kubectl get nodes, I get the node state as Ready.

Why is it not going to NotReady state?

**Comment by roberthbailey** [comment]
How long does it stay in the Ready state? By default, the nodecontroller [checks each node every 5 seconds](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go#L134) and should [set node ready to condition unknown](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/cloudprovider/nodecontroller/nodecontroller.go#L342) if the node hasn't pinged the master for a while.

**Comment by adyanthaya17** [comment]
It's been 15minutes since I shutdown the minion node but it still shows as Ready state.

**Comment by bprashanth** [comment]
Please share /var/log/kube-controller-manager.log and the output of kubectl describe node <rebooted node>, kubectl get node <rebooted node> -o json 
@gmarek

**Comment by Naresht-vedams** [comment]
Once turn ON the node which is you turned off. Please check `service etcd status` . If the status is stop, restart the etcd service now check get nodes, here you will see NotReady state for a while.
@adyanthaya17

**Comment by gmarek** [comment]
@adyanthaya17 how are you running your cluster? One on of cloud providers, or on some bare-metal environment?

**Comment by adyanthaya17** [comment]
@gmarek I'm running them on a cloud provider (openstack).

@bprashanth There's no /var/log/kube-controller-manager.log 

This is one of the container that's running on the minion that's turned off:
root@kubernetes-master:/home/ubuntu# kubectl describe POD update-demo-nautilus-23opn
Name:                           update-demo-nautilus-23opn
Namespace:                      default
Image(s):                       gcr.io/google_containers/update-demo:nautilus
Node:                           20.20.0.196/20.20.0.196
Labels:                         name=update-demo,version=nautilus
Status:                         Running
Reason:
Message:
IP:                             172.17.0.3
Replication Controllers:        update-demo-nautilus (5/5 replicas created)
Containers:
  update-demo:
    Image:              gcr.io/google_containers/update-demo:nautilus
    State:              Running
      Started:          Fri, 31 Jul 2015 03:05:16 +0000
    Ready:              True
    Restart Count:      0
Conditions:
  Type          Status
  Ready         True
No events.

@Naresht-vedams I turned on the minion node and restarted the services on it but the status didn't go as NotReady.

**Comment by gmarek** [comment]
@adyanthaya17 /var/log/kube-controller-manager.log should be on your master machine.

Can you also paste a result for `kubectl get pod update-demo-nautilus-23opn -o json`, and both `describe` and `get node xyz -o json` for turned off node?

**Comment by adyanthaya17** [comment]
@gmarek
root@kubernetes-master:/home/ubuntu# kubectl get pod update-demo-nautilus-23opn -o json
{
    "kind": "Pod",
    "apiVersion": "v1",
    "metadata": {
        "name": "update-demo-nautilus-23opn",
        "generateName": "update-demo-nautilus-",
        "namespace": "default",
        "selfLink": "/api/v1/namespaces/default/pods/update-demo-nautilus-23opn",
        "uid": "f6f59738-3730-11e5-97ae-fa163eff7c43",
        "resourceVersion": "13163",
        "creationTimestamp": "2015-07-31T03:05:14Z",
        "labels": {
            "name": "update-demo",
            "version": "nautilus"
        },
        "annotations": {
            "kubernetes.io/created-by": "{\"kind\":\"SerializedReference\",\"apiVersion\":\"v1\",\"reference\":{\"kind\":\"ReplicationController\",\"namespace\":\"default\",\"name\":\"update-demo-nautilus\",\"uid\":\"7d2b0b9c-3730-11e5-97ae-fa163eff7c43\",\"apiVersion\":\"v1\",\"resourceVersion\":\"11762\"}}"
        }
    },
    "spec": {
        "volumes": [
            {
                "name": "default-token-qnmy1",
                "secret": {
                    "secretName": "default-token-qnmy1"
                }
            }
        ],
        "containers": [
            {
                "name": "update-demo",
                "image": "gcr.io/google_containers/update-demo:nautilus",
                "ports": [
                    {
                        "containerPort": 80,
                        "protocol": "TCP"
                    }
                ],
                "resources": {},
                "volumeMounts": [
                    {
                        "name": "default-token-qnmy1",
                        "readOnly": true,
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
                    }
                ],
                "terminationMessagePath": "/dev/termination-log",
                "imagePullPolicy": "IfNotPresent"
            }
        ],
        "restartPolicy": "Always",
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "default",
        "serviceAccount": "default",
        "nodeName": "20.20.0.196"
    },
    "status": {
        "phase": "Running",
        "conditions": [
            {
                "type": "Ready",
                "status": "True"
            }
        ],
        "hostIP": "20.20.0.196",
        "podIP": "172.17.0.2",
        "startTime": "2015-07-31T08:53:12Z",
        "containerStatuses": [
            {
                "name": "update-demo",
                "state": {
                    "running": {
                        "startedAt": "2015-07-31T08:53:13Z"
                    }
                },
                "lastState": {
                    "terminated": {
                        "exitCode": 2,
                        "startedAt": "2015-07-31T03:05:16Z",
                        "finishedAt": "2015-07-31T04:30:17Z",
                        "containerID": "docker://8f8bacd5c2b9832eaeedad8db1c33b3ed3690ab9dc52a00b847de63ac37f59af"
                    }
                },
                "ready": true,
                "restartCount": 1,
                "image": "gcr.io/google_containers/update-demo:nautilus",
                "imageID": "docker://52d7df74b3f36e98871acf476f1933434ea1e71911965de8933ea0293e029328",
                "containerID": "docker://ed3e9327384dbc72b66d1981b87182050ca1417c8ac5d2a90c5a0e672140254a"
            }
        ]
    }
}


$ kubectl describe POD update-demo-nautilus-23opn
Name:                           update-demo-nautilus-23opn
Namespace:                      default
Image(s):                       gcr.io/google_containers/update-demo:nautilus
Node:                           20.20.0.196/20.20.0.196
Labels:                         name=update-demo,version=nautilus
Status:                         Running
Reason:
Message:
IP:                             172.17.0.2
Replication Controllers:        update-demo-nautilus (5/5 replicas created)
Containers:
  update-demo:
    Image:              gcr.io/google_containers/update-demo:nautilus
    State:              Running
      Started:          Fri, 31 Jul 2015 08:53:13 +0000
    Ready:              True
    Restart Count:      1
Conditions:
  Type          Status
  Ready         True
Events:
  FirstSeen                             LastSeen                        Count   From                    SubobjectPath                           Reason  Message
  Fri, 31 Jul 2015 08:53:12 +0000       Fri, 31 Jul 2015 08:53:12 +0000 1       {kubelet 20.20.0.196}   implicitly required container POD       pulled  Pod container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  Fri, 31 Jul 2015 08:53:12 +0000       Fri, 31 Jul 2015 08:53:12 +0000 1       {kubelet 20.20.0.196}   implicitly required container POD       created Created with docker id 070ef5b57ff8
  Fri, 31 Jul 2015 08:53:13 +0000       Fri, 31 Jul 2015 08:53:13 +0000 1       {kubelet 20.20.0.196}   implicitly required container POD       started Started with docker id 070ef5b57ff8
  Fri, 31 Jul 2015 08:53:13 +0000       Fri, 31 Jul 2015 08:53:13 +0000 1       {kubelet 20.20.0.196}   spec.containers{update-demo}            created Created with docker id ed3e9327384d
  Fri, 31 Jul 2015 08:53:13 +0000       Fri, 31 Jul 2015 08:53:13 +0000 1       {kubelet 20.20.0.196}   spec.containers{update-demo}            started Started with docker id ed3e9327384d


root@kubernetes-master:/home/ubuntu# kubectl get node 20.20.0.196 -o json
{
    "kind": "Node",
    "apiVersion": "v1",
    "metadata": {
        "name": "20.20.0.196",
        "selfLink": "/api/v1/nodes/20.20.0.196",
        "uid": "8b47f44a-36aa-11e5-a00e-fa163eff7c43",
        "resourceVersion": "13795",
        "creationTimestamp": "2015-07-30T11:03:01Z",
        "labels": {
            "kubernetes.io/hostname": "20.20.0.196"
        }
    },
    "spec": {
        "externalID": "20.20.0.196"
    },
    "status": {
        "capacity": {
            "cpu": "1",
            "memory": "2050052Ki",
            "pods": "40"
        },
        "conditions": [
            {
                "type": "Ready",
                "status": "True",
                "lastHeartbeatTime": "2015-07-31T09:43:03Z",
                "lastTransitionTime": "2015-07-31T08:53:18Z",
                "reason": "kubelet is posting ready status"
            }
        ],
        "addresses": [
            {
                "type": "LegacyHostIP",
                "address": "20.20.0.196"
            }
        ],
        "nodeInfo": {
            "machineID": "881a22130c510fca420223095591ae10",
            "systemUUID": "E75EFDA5-4112-4A1D-8505-EF89D903626F",
            "bootID": "786cb17d-c473-48cd-b480-566576ef48bf",
            "kernelVersion": "3.13.0-58-generic",
            "osImage": "Ubuntu 14.04.2 LTS",
            "containerRuntimeVersion": "docker://1.7.1",
            "kubeletVersion": "v1.0.1",
            "kubeProxyVersion": "v1.0.1"
        }
    }
}

**Comment by gmarek** [comment]
I don't know in which timezone you're running, but I believe we store time in UTC, thus if 'lastHeartbeatTime' ~2 hours ago was 9:43 it's quite likely that your Node wasn't as dead as you think it was (or there was some caching of Nodes healtz HTTP response somewhere).

Can you curl/wget your 'dead' node on port 10248?

**Comment by qq690388648** [comment]
I have the same case:https://github.com/GoogleCloudPlatform/kubernetes/issues/12062

**Comment by gmarek** [comment]
@adyanthaya17 - do you still have this problem? If not, I'll close the issue.

**Comment by adyanthaya17** [comment]
@gmarek Ye, I'm still facing this issue.

**Comment by dchen1107** [comment]
I think the issue is closed accidentally by @adyanthaya17 based the comment above.

**Comment by gmarek** [comment]
@adyanthaya17 - Can you paste the new output of `kubectl describe node` of the removed node? I want to be sure that the node is actually dead (i.e. that 'LastProbeTime' was long time ago). Note that timestamp is in UTC.

**Comment by gmarek** [comment]
@adyanthaya17 - can you provide some more data? Without it I'm unable to do anything, so I'll close this issue.
