### ISSUE TITLE
kubelet: lookup node address logic for external provider assign wrong PodIPs to hostNetwork pods

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#120720]
The kubelet  logic used to get the Node addresses when using an external provider, temporary assigns an address discovered from the node , this address can be overriden later by the external cloud provider

https://github.com/kubernetes/kubernetes/blob/0241da314e0e69817d66313b45a69c19d1ce7327/pkg/kubelet/nodestatus/setters.go#L123-L131

This was implemented in https://github.com/kubernetes/kubernetes/pull/75229 to improve the  bootstrapping problems with some external cloud providers

The side effect of this behavior is that if the external cloud provider sets a different address/es, then the pods with `HostNetwork: true` will be showing the "first" addresses as their `PodIPs`, since we don't mutate those IPs once set to avoid problems

https://github.com/kubernetes/kubernetes/blob/0241da314e0e69817d66313b45a69c19d1ce7327/pkg/kubelet/kubelet_pods.go#L1770-L1786

I think that we should revert the existing logic for external cloud providers, since is causing a temporary and inconsistent state and it seem to address mainly a problem with kubeadm https://github.com/kubernetes/kubernetes/pull/75229#issuecomment-516592142 but kubeadm folks seems to not need this functionality https://github.com/kubernetes/kubernetes/pull/75229#issuecomment-516580449

/kind bug
/sig network
/sig node

**Comment by cyclinder** [comment]
>  since is causing a temporary and inconsistent state

So we don't want the external provider to update the IP of the node, right? But I think even if it updates the address, for pods with hostnetwork, it still gets the first address from nodeStatus as podIPs, why is it inconsistent?

**Comment by aojea** [comment]
> So we don't want the external provider to update the IP

the contrary, we don't want to shortcut the address assignment, if cloud provider is external the node should wait for the cloud provider to assign the address.

Let me put an example,  a node with IPs 10.0.0.1 and 2001:db2::3 and cloud-provider external that sets the IPv6 address first.

Right, now, the Node will use prefer IPv4 when it starts and assign the IP 10.0.0.1 to the node, hostNetwork pods will get that IP. and later the cloud provider will override the IPs and sets 2001:db2::3 as the address, so new hostNetwork pods will use the IPv6 address but old hostNetwork pods will have 10.0.0.1

**Comment by cyclinder** [comment]
I see, Now I think it makes sense, but we need to confirm that kubeadm really doesn't need it anymore.

**Comment by aojea** [comment]
> I see, Now I think it makes sense, but we need to confirm that kubeadm really doesn't need it anymore.

@neolit123 ^^^

**Comment by danwinship** [comment]
> I think that we should revert the existing logic for external cloud providers, since is causing a temporary and inconsistent state and it seem to address mainly a problem with kubeadm

I don't know the history of why it works the way it currently does, but I agree that it's weird and seems likely to lead to problems, so if it turns out it's not necessary, then let's change it.

**Comment by andrewsykim** [comment]
> The side effect of this behavior is that if the external cloud provider sets a different address/es, then the pods with HostNetwork: true will be showing the "first" addresses as their PodIPs, since we don't mutate those IPs once set to avoid problems

This is why we taint nodes initially and only remove the taint once cloud provider has initialized the node. So this is reallly an issue for pods tolerating this taint

**Comment by neolit123** [comment]
> > I see, Now I think it makes sense, but we need to confirm that kubeadm really doesn't need it anymore.
> 
> @neolit123 ^^^

i don't understand what is being adked exactly, but if the Q is again whether kubeadm supports self-hosted control plane components in a DS, then no.

kubeadm does support the --cloud-privider=external on paper, but we don't have tests. i don't think we want to maintain them either.

@pacoxu do you have context?

**Comment by pacoxu** [comment]
For current behavior, the workaround would be `to delete hostNetwork:true pods and wait for recreation` if I understand correctly.

I don't know if there are any cloud provider installers that depend on this behavior. I prefer to fix the weird behavior to avoid potential problems. Or a problem detector has to cover this to check if a hostNet pod is not using the correct node IP.

**Comment by aojea** [comment]
> This is why we taint nodes initially and only remove the taint once cloud provider has initialized the node. So this is reallly an issue for pods tolerating this taint

yeah, but I think that is fair to give those pods the responsibility to deal with the known behavior (node will not have addresses until cloud provider external initializes) , than make the kubelet have two different addresses during its lifetime (that we discussed extensively https://github.com/kubernetes/kubernetes/issues/108281 and  https://github.com/kubernetes/kubernetes/pull/93898) We discarded this behavior because most components,  apps and features like downward API depend on the existing behavior of not changing the original IP

**Comment by andrewsykim** [comment]
> For the temporal status without addresses we can just set the node as notReady https://github.com/kubernetes/kubernetes/issues/120727

NetworkUnavailable might be more appropriate, but overall makes sense I think

**Comment by andrewsykim** [comment]
Ah, is it just https://github.com/kubernetes/kubernetes/issues/120727 or are there others?

**Comment by andrewsykim** [comment]
Oh -- https://github.com/kubernetes/kubernetes/issues/120727 is not even related, because they are not setting --cloud-provider=external

**Comment by aojea** [comment]
> @aojea is there a reported issue or bug that is reproducible based on what you describe in the isuse description? Logically what you said makes sense but I'm wondering how common the problem actually is

yeah, @andrewsykim I opened this issue because when I tried to bring up an IPv6 only cluster with kops in GCE it failed and one of the problems was that the hostNetwork pods were using IPv4 as pod ips

**Comment by andrewsykim** [comment]
> because when I tried to bring up an IPv6 only cluster with kops in GCE it failed and one of the problems was that the hostNetwork pods were using IPv4 as pod ips

Isn't this a configuration issue on the kubelet and not with external cloud providers then? You should configure kubelet to bootstrap initially with an IPv6 address and not IPv4.

**Comment by aojea** [comment]
> Isn't this a configuration issue on the kubelet and not with external cloud providers then? You should configure kubelet to bootstrap initially with an IPv6 address and not IPv4.

Still does not work for dual-stack, or if there are multiple addresses on the node, or multiple interfaces ....

I don't see the reason why kubelet should configure the node addresses in the first place just to wait for the cloud-provider to override that ... the pods bootstrap problem is another thing, kubelet should not be ready if there are no addresses in the node https://github.com/kubernetes/kubernetes/pull/120753, but current behavior is compensating the problem of having an external  source for the address allocation, that is clearly not generalizable

**Comment by lubronzhan** [comment]
>yeah, @andrewsykim I opened this issue because when I tried to bring up an IPv6 only cluster with kops in GCE it failed and one of the problems was that the hostNetwork pods were using IPv4 as pod ips ... is not likely anybody hits this with IPv4 or dual stack, since cloud-provider and kubelet will agree most of the times, but as soon that you use IPv6 only or IPv6 primary you ends with this problem

For cloud-provider-vsphere, what we did to workaround is to identify the preferred ip address to get, which interface, which rank, then in bootstrap time we get it and pass it to kubelet flag `--node-ip`. Now `--node-ip` support dual stack address with external cloud-provider. 

Without the kubelet starting node with some IP, if there is issue in CPI code or in the config, then it would be hard for us to debug CPI since getting the log will getting error that node doesn't have prefered ip. Might need to get the container log from containerd directly by ssh into the node.

> kubelet should not be ready if there are no addresses in the node 
You mentioned this is for GCE, I remember @jayunit100 brought it up in here https://github.com/kubernetes/kubernetes/issues/120486 that now the `NodeNetworkUnavailable` is also [managed by CCM](https://github.com/kubernetes/cloud-provider/blob/73ce03d745d168cd8169b5f9ebfde4120b9ca82f/controllers/route/route_controller.go#L398) if CCM has route controller enable, which doesn't have clear ownership between CMM and CNI which should reconcile it. And according to the CCM logic [here](https://github.com/kubernetes/cloud-provider/blob/master/controllers/node/node_controller.go#L458-L470), in GCE case it will managed the `NodeNetworkUnavailable` in CCM, and probably will mark it as false once the route is ready, then node could possibly becomes ready.
So maybe that's why in your case the node becomes ready even though the node doesn't have the address you preferred.

**Comment by aojea** [comment]
> You mentioned this is for GCE

I found it trying with GCE, but  that is not important, I can hit this with Openshift or Rancher or Kind ... my goal is to define a general behavior of the kubelet that is consistent and easier to think about, without breaking anyone of course, but current implementation is a footgun and seems tailor made... do we enforce all cloud providers to pass the --node-ip flag to kubelet to match their IPs?  🤷  I will put this for the next sig-network agenda so we can go deeper and talk more about it

**Comment by aojea** [comment]
Another example of this problem in Azure and CAPG @lubronzhan @andrewsykim https://github.com/kubernetes/kubernetes/pull/116879

**Comment by lubronzhan** [comment]
Ohk we ran into similar issue today, We didn't pass --node-ips to kubelet, and we are setting ipv6 as primary ipfamily, but kubelet chose ipv4 address at the beginning, so all hostNetwork pod has ipv4 address. Now even after CPI has fixed the node ip to put ipv6 address as primary address, all following pods still has ipv4 addresses regardless. Example:
```
kubo@l4pG6sGMZI8mF:~$ kubectl get po -o wide -A | grep cluster-a-control-plane-flvz4
default                multi-nic-pod-macvlan-l2qpj                              1/1     Running     0               8m55s   100.96.0.28                         cluster-a-control-plane-flvz4         <none>           <none>
kube-system            antrea-agent-kbtld                                       2/2     Running     0               2d11h   10.168.220.178                      cluster-a-control-plane-flvz4         <none>           <none>
kube-system            antrea-controller-74b5f7848c-74rvn                       1/1     Running     0               2d11h   10.168.220.178                      cluster-a-control-plane-flvz4         <none>           <none>
kube-system            coredns-7b7646b589-b7zvr                                 1/1     Running     0               2d11h   100.96.0.4                          cluster-a-control-plane-flvz4
```

Node addresses:
```
status:
  addresses:
  - address: cluster-a-control-plane-flvz4
    type: Hostname
  - address: fd01:0:106:209:250:56ff:fe9a:17ae
    type: InternalIP
  - address: 10.168.220.178
    type: InternalIP
  - address: fd01:0:106:209:250:56ff:fe9a:17ae
    type: ExternalIP
  - address: 10.168.220.178
    type: ExternalIP
```

**Comment by aojea** [comment]
so @lubronzhan , does it mean you agree we need to fix this as in https://github.com/kubernetes/kubernetes/pull/120751?

**Comment by andrewsykim** [comment]
I'm in favor of removing the behavior to bootstrap initial addresses as long as we are confident it is not breaking some exitsing behavior that some provider is depending on. 

I still find the scenario in [comment#](https://github.com/kubernetes/kubernetes/issues/120720#issuecomment-1731901005) a little odd, those pods should not be running on the node if the CCM has no initialized them yet. I wonder if the actual problem here is that node addresses are only updated after the first initialization: 

https://github.com/kubernetes/kubernetes/blob/c5cf0ac1889f55ab51749798bec684aed876709d/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L498-L500

Which means pods can be admitted between the time time the cloud provider taint is removed and when addresses are updated.

**Comment by lubronzhan** [comment]
>so @lubronzhan , does it mean you agree we need to fix this as in https://github.com/kubernetes/kubernetes/pull/120751?

At least from cloud-provider-vsphere it shouldn't depend on this behavior to bootstrap. It's just that it would be harder for people to debug the CPI issue in the future if something goes wrong before CPI could initialize the node.

>I still find the scenario in https://github.com/kubernetes/kubernetes/issues/120720#issuecomment-1731901005 a little odd, those pods should not be running on the node if the CCM has no initialized them yet.

Yeah this is weird. For pod like apiserver pod has ipv4 address, which make sense since it comes before CPI.
```
kube-system            kube-apiserver-cluster-a-control-plane-flvz4             1/1     Running     0                3d21h   10.168.220.178                      cluster-a-control-plane-flvz4         <none>           <none>
```
now CPI already removes the taints and updated the node with correct IP address, also the node has correct podCIDRs, with ipv6 address at the front.
```
spec:
  podCIDR: fd00:100:96::/64
  podCIDRs:
  - fd00:100:96::/64
  - 100.96.0.0/24
```
Still if I create a new pod on that node, it will be assigned with a ipv4 address. 
For example that `multi-nic-pod-macvlan-l2qpj` test pod was created long after the CPI initialized the node.
```
default                multi-nic-pod-macvlan-l2qpj                              1/1     Running     0               8m55s   100.96.0.28                         cluster-a-control-plane-flvz4         <none>           <none>
```

And we only  experience issue with pod that get created on this node, all other pod on other node will have ipv6 address as primary address.

**Comment by aojea** [comment]
@lubronzhan that should not be a problem if having node addresses is a requirement of node readiness https://github.com/kubernetes/kubernetes/pull/120753

**Comment by tzneal** [comment]
The EKS AMIs that we provide specify `--node-ip` which avoids this issue. If that flag is not passed, then the same problem exists along with a slightly worse one that we intend to fix, https://github.com/kubernetes/cloud-provider-aws/issues/656.

**Comment by aojea** [comment]
> Which means pods can be admitted between the time time the cloud provider taint is removed and when addresses are updated.

@andrewsykim good catch is event more complex, since the ccm will not add addresses meanwhile the node is tainted 😮‍💨 

https://github.com/kubernetes/kubernetes/blob/c5cf0ac1889f55ab51749798bec684aed876709d/staging/src/k8s.io/cloud-provider/controllers/node/node_controller.go#L360-L366
