### ISSUE TITLE
Kubelet didn't respect --resolv-conf when resolv.conf is empty or full of comments

### ISSUE THREAD

**Issue by fungaren** [kubernetes/kubernetes#120748]
### What happened?

When I passing `--resolv-conf` to kubelet, it did not respect the option, and still copy the `/etc/resolv.conf` to the pod.

What makes it special is that the `resolv.conf` provided by myself is empty.

> https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

After skimming the code, I found the logic here is problematic:

https://github.com/kubernetes/kubernetes/blob/v1.28.2/pkg/kubelet/network/dns/dns.go#L225-L274

Because `resolv.conf` is empty, an empty array and no error is returned. Then, if the dnsPolicy is `default` (that is the default config for CoreDNS deployment), the `podDNSType` turns to be `podDNSHost`:

https://github.com/kubernetes/kubernetes/blob/v1.28.2/pkg/kubelet/network/dns/dns.go#L316-L317

Then, containerd will get an empty `dns_config`, so it will copy `/etc/resolv.conf` from the host to the container:

https://github.com/containerd/containerd/blob/v1.7.6/pkg/cri/server/sandbox_run_linux.go#L282-L287

Finally, CoreDNS reports forwarding loop error.

### What did you expect to happen?

Kubelet should refuse to use the wrong empty `resolv.conf` to create a pod, and complains with errors.

### How can we reproduce it (as minimally and precisely as possible)?

1. Pass `--resolv-conf` to kubelet, and make sure the specified `resolv.conf` file is empty.
2. Check the output of CoreDNS, and its `/etc/resolv.conf`.

### Kubernetes version

<details>

k8s v1.28.2
containerd v1.7.6

</details>

### Cloud provider

<details>

None

</details>

### OS version

<details>

Any major Linux distribution.

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by aojea** [comment]
why if someone wants to pass an empty resolv.conf to the pods? is that a possibility?

I do not know if kubelet should compensate what it seems an operator problem, or am I reading it wrong?

**Comment by fungaren** [comment]
> why if someone wants to pass an empty resolv.conf to the pods? is that a possibility?
> 
> I do not know if kubelet should compensate what it seems an operator problem, or am I reading it wrong?

This situation MAY occur when systemd-resolved is used, and the operator pass the `--resolv-conf /run/systemd/resolve/resolv.conf` to kubelet. 

Although systemd-resolved create this file in manner of "create temp, write temp, rename" ...

> https://github.com/systemd/systemd/blob/main/src/resolve/resolved-resolv-conf.c#L348-L387

... the UPLINK config (`/run/systemd/resolve/resolv.conf`) file may still be full of comments if there is no available name server at the time.

> https://github.com/systemd/systemd/blob/main/src/resolve/resolved-resolv-conf.c#L257-L293

**Comment by fungaren** [comment]
And after a while, systemd-resolved got an available dns server by any way, then the UPLINK config should be recreated, however the kubelet have taken the stale and full-of-comments `/run/systemd/resolve/resolv.conf`.

**Comment by aojea** [comment]
I see there is a race there, thanks for the explanation ... the only question I have is if someone is relying on this behavior of passing an empty resolv.conf to the pods, a change like this will break it

**Comment by ndixita** [comment]
/remove-sig node. 

This is on network team to decide how to migrate a new behavior for empty file..

**Comment by yuzhiquan** [comment]
> the only question I have is if someone is relying on this behavior of passing an empty resolv.conf to the pods, a change like this will break it

If set `--resolve-conf=/x/y/empty.file`, it means will use the default value `/etc/resolv.conf`, so this change may be not a break, but should be a warning.

**Comment by aojea** [comment]
It is suggesting to change the behavior to stop the pod creation

> Kubelet should refuse to use the wrong empty resolv.conf to create a pod, and complains with errors.

**Comment by yuzhiquan** [comment]
/assign
But if @fungaren already have design on this, please go ahead.

**Comment by aojea** [comment]
I still don't have clear what is the proposal and how to maintain compatibility

**Comment by yuzhiquan** [comment]
> compatibility

Cool, may be it's like new warning events `CheckEmptyForResolvConf` just like `CheckLimitsForResolvConf`, or something else.

**Comment by thockin** [comment]
https://github.com/containerd/containerd/pull/9730

**Comment by cndoit18** [comment]
> This is a fun bug, but not that hard to comprehend, I think.
> 
> Forget whether it's a "good idea" or not.
> 
> Is it valid to pass an empty file to `--resolv-conf` ? If yes, should it mean the same as not passing that flag or should it mean "no config".
> 
> I think it IS valid and it SHOULD mean "no config". What really happens is that kubelet gets empty slices (but no error, so not ambiguous). When it creates the DNSConfig message, it appears empty, because it is comprised entirely of `repeated` fields with no instances. That is ambiguous - it could mean "no data" or "not specified". It's unclear to me if we can tell the difference between those? @samuelkarp @SergeyKanzhelev @ndixita - do you know? `PodSandboxConfig.GetDnsConfig()` _can_ return nil.
> 
> Containerd further conflates those two by parsing into a string, and assuming `""` means "not specified". Even if it WAS specified!
> 
> Then, containerd "helpfully" decides that, if you don't specify any contents, it should copy the host's resolv.conf.
> 
> I am not 100% confident in CRI semantics - is it valid for CRI to NOT populate the `PodSandboxConfig.DNSConfig` message? Or is that effectively required? If a CRI caller does not specify `PodSandboxConfig.DNSConfig`, is the CORRECT behavior to go look at the host? That seems like over-stepping, to me. If I wanted a DNS config, I would have sent it. Agree or disagree?
> 
> So IMO, the fix here is either (in my pref order):
> 
> 1. containerd should not fall back on host's resolv.conf AT ALL
> 2. containerd should differentiate "not provided" from "provided and empty" (`PodSandboxConfig.GetDnsConfig()` returned nil)
> 3. we should add a "this struct intentionally left blank" marker to `DNSConfig`, so containerd can do the above
> 
> So I think this very much _is_ a SIG Node issue.
> 
> /sig node
> 
> As to the question of how this problem was discovered....why are you setting the kubelet to an empty resolv.conf rather than just configuring the specific Pods in question?

The problem was found to be caused by our use of the `systemd-resolved` to generate `resolv.conf`. So we set `--resolv-conf` to `/run/systemd/resolve/resolv.conf`. 

When the machine reboots, there is a problem with the startup sequence between `systemd-resolved` and `kubelet`. 
1. if `systemd-resolved` starts before `kubelet`, then `resolv.conf` should be populated before `kubelet` starts. 
2. If `kubelet` starts before `systemd-resolved`, then an empty `resolv.conf` is served.

**Comment by fungaren** [comment]
> As to the question of how this problem was discovered....why are you setting the kubelet to an empty resolv.conf rather than just configuring the specific Pods in question?

@thockin This is because CoreDNS reports a forwarding loop issue due to systemd-resolved is used in the node, and I pass `--resolv-conf /run/systemd/resolve/resolv.conf` to kubelet. But it has a race condition here when the node restarted, the file may be full of comments if there is no available name server at the time.

And after a while, systemd-resolved got an available dns server by any way, then the UPLINK config should be recreated, however the kubelet have taken the stale and full-of-comments `/run/systemd/resolve/resolv.conf`.

Of course passing an empty `--resolv-conf` is incorrect, but it is not deliberately.

**Comment by thockin** [comment]
Fixed in containerd

**Comment by aojea** [comment]
> [containerd/containerd#9730](https://github.com/containerd/containerd/pull/9730)

@saschagrunert @haircommander @mrunalp you should check if you need to fix this too in cri-o ^^^

**Comment by roman-kiselenko** [comment]
It looks like [`cri-o/cri-o`](https://github.com/cri-o/cri-o/blob/main/internal/factory/sandbox/infra.go#L89-L93) does nothing if `DNSConfig` is nil. Only in case of an empty struct of `DSNConfig` `/etc/resolv.conf` [be copied](https://github.com/cri-o/cri-o/blob/main/internal/factory/sandbox/infra.go#L128-L130).


I'm going to create a PR in `cri-o.`

**Comment by saschagrunert** [comment]
Thank you @roman-kiselenko and thanks @aojea for the hint! :heart:
