### ISSUE TITLE
[Flake]  StatefulSet Basic StatefulSet functionality 

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#120700]
### Which jobs are flaking?

![image](https://github.com/kubernetes/kubernetes/assets/6450081/2c067a3d-d99e-41fe-8e88-9af891538d5e)

### Which tests are flaking?

 StatefulSet Basic StatefulSet functionality [StatefulSetBasic] should perform rolling updates and roll backs of template modifications [Conformance]

### Since when has it been flaking?

9/13 9.00 PM UTC+2

### Testgrid link

https://storage.googleapis.com/k8s-triage/index.html?test=StatefulSet%20Basic%20StatefulSet

### Reason for failure (if possible)

```


2m3s
--
{ failed [FAILED] Pod statefulset-179/ss2-0 has image registry.k8s.io/e2e-test-images/httpd:2.4.39-4 not equal to previous image registry.k8s.io/e2e-test-images/httpd:2.4.38-4 Expected     <string>: registry.k8s.io/e2e-test-images/httpd:2.4.39-4 to equal     <string>: registry.k8s.io/e2e-test-images/httpd:2.4.38-4 In [It] at: test/e2e/apps/statefulset.go:1935 @ 09/15/23 10:32:06.037

```

### Anything else we need to know?

This seems most likely the problem https://github.com/kubernetes/kubernetes/pull/120398, it merged about the time the test started to fail and is completely related

### Relevant SIG(s)

/sig apps

**Comment by liggitt** [comment]
do we know if this is this a test issue or a regression introduced by https://github.com/kubernetes/kubernetes/pull/120398?

**Comment by mimowo** [comment]
> do we know if this is this a test issue or a regression introduced by #120398?

I don't know for now, but I'm going to investigate.

**Comment by aleksandra-malinowska** [comment]
>Pod statefulset-179/ss2-0 has image registry.k8s.io/e2e-test-images/httpd:2.4.39-4 not equal to previous image registry.k8s.io/e2e-test-images/httpd:2.4.38-4

I suspect #120398 exposed this problem in tests. I'll need to take a closer look at it, but it sounds a lot like #119685 and #119684.

**Comment by mimowo** [comment]
I have reproduced the failure locally, by running the test in a loop (after 8 repeats). Next, I'm going to see if the test fails on branch with https://github.com/kubernetes/kubernetes/pull/120731

**Comment by mimowo** [comment]
Ok, I have 40 passes, which suggests the fix indeed fixes also this issue.

**Comment by liggitt** [comment]
we should revert the change that broke tests first to recover, rather than stacking more fixes on top of it

**Comment by aleksandra-malinowska** [comment]
>we should revert the change that broke tests first to recover, rather than stacking more fixes on top of it

I added more context in #120731#issuecomment-1723621470. TL;DR:
- #115331 introduced a bug which was probably causing this test to ignore this failure. It was already backported some months ago.
- #117071 introduced the bug detected in the test, and it was also already backported some months ago. It's also a rather large change, while the fix is rather small.
- #120398 fixed the bug which was causing the test to ignore this failure. We can easily roll it back as it was just merged, but it will just make tests green while keeping both bugs affecting users.
- #120731 not only fixes the bug originating from #120398, but also (I believe) makes the code around it more resilient.

**Comment by aleksandra-malinowska** [comment]
>we should revert the change that broke tests first to recover, rather than stacking more fixes on top of it

If I understand correctly, the purpose would be to reduce the urgency, which could result in hasty review of the fix? 

If so, I'd say the PR to rollback would be #120398. Then the fix #120731 can be reviewed and merged at normal pace while the tests are green.

**Comment by liggitt** [comment]
There's an immediate regression on master we want to fix (likely rolling back https://github.com/kubernetes/kubernetes/pull/120398), but we also want to prioritize recovering from 1.27 / 1.28 regressions over fixing long-standing bugs.

**Comment by mimowo** [comment]
Yeah, while we could rollback https://github.com/kubernetes/kubernetes/pull/120398 to recover the tests from flaking, but my understanding is that it just exposed a bug introduced in https://github.com/kubernetes/kubernetes/pull/117865, while fixing https://github.com/kubernetes/kubernetes/pull/115331.

**Comment by pacoxu** [comment]
The release plan of 1.29.0-alpha.1 is today. Is this an alpha release blocker? Should the rollback happen before the cut off?

**Comment by soltysh** [comment]
> The release plan of 1.29.0-alpha.1 is today. Is this an alpha release blocker? Should the rollback happen before the cut off?

The revert in #120755 is already tagged, so hopefully it should unblock alpha release, if it wasn't cut yet

**Comment by liggitt** [comment]
> The release plan of 1.29.0-alpha.1 is today. Is this an alpha release blocker? Should the rollback happen before the cut off?

Yes, I think it should block alpha.1. The revert is hung up on two presubmits that just started failing on all PRs - https://github.com/kubernetes/test-infra/issues/30759

**Comment by liggitt** [comment]
The revert merged in https://github.com/kubernetes/kubernetes/pull/120755

**Comment by aojea** [comment]
Thanks
