### ISSUE TITLE
Make UDP timeouts set via kube-proxy config (for ipvs mode) also change timeouts in Conntrack

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/kubernetes#120708]
### What would you like to be added?

Make UDP timeouts set via kube-proxy config (for ipvs mode) also change timeouts in Conntrack, just like it already works for TCP.
https://github.com/kubernetes/kubernetes/issues/120076#issuecomment-1693548013

### Why is this needed?

For settings consistency: current behavior for setting TCP timeouts is superior compared to setting UDP timeouts for no good reason. As a consequence, one has to manually modify `net.netfilter.nf_conntrack_udp_timeout`/`nf_conntrack_udp_timeout_stream` on the underlying nodes OSes.

**Comment by aroradaman** [comment]
@Drugoy I already opened an issue for this 🙂 


closing this one, dup of https://github.com/kubernetes/kubernetes/issues/120214
/close
