### ISSUE TITLE
cannot find module providing package k8s.io/component-base/logs/kube-log-runner: import lookup disabled by -mod=vendor

### ISSUE THREAD

**Issue by JasonCeng** [kubernetes/kubernetes#120804]
### Which jobs are failing?

root@ubuntu23-master:/home/zengzc/goPath/src/github.com/kubernetes/kubernetes# make all GOGCFLAGS="-N -l" GOLDFLAGS="-v"
+++ [0921 12:00:28] Building go targets for linux/amd64
    k8s.io/kubernetes/cmd/kube-proxy (static)
    k8s.io/kubernetes/cmd/kube-apiserver (static)
    k8s.io/kubernetes/cmd/kube-controller-manager (static)
    k8s.io/kubernetes/cmd/kubelet (non-static)
    k8s.io/kubernetes/cmd/kubeadm (static)
    k8s.io/kubernetes/cmd/kube-scheduler (static)
    k8s.io/component-base/logs/kube-log-runner (static)
    k8s.io/kube-aggregator (static)
    k8s.io/apiextensions-apiserver (static)
    k8s.io/kubernetes/cluster/gce/gci/mounter (non-static)
    k8s.io/kubernetes/cmd/kubectl (static)
    k8s.io/kubernetes/cmd/kubectl-convert (static)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/test/e2e/e2e.test (test)
    k8s.io/kubernetes/test/conformance/image/go-runner (non-static)
    k8s.io/kubernetes/cmd/kubemark (static)
    github.com/onsi/ginkgo/v2/ginkgo (non-static)
    k8s.io/kubernetes/test/e2e_node/e2e_node.test (test)
cannot find module providing package k8s.io/component-base/logs/kube-log-runner: import lookup disabled by -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
cannot find module providing package k8s.io/kube-aggregator: import lookup disabled by -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
cannot find module providing package k8s.io/apiextensions-apiserver: import lookup disabled by -mod=vendor
	(Go version in go.mod is at least 1.14 and vendor directory exists.)
!!! [0921 12:00:32] Call tree:
!!! [0921 12:00:32]  1: /home/zengzc/goPath/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh:777 kube::golang::build_some_binaries(...)
!!! [0921 12:00:32]  2: /home/zengzc/goPath/src/github.com/kubernetes/kubernetes/hack/lib/golang.sh:947 kube::golang::build_binaries_for_platform(...)
!!! [0921 12:00:32]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0921 12:00:32] Call tree:
!!! [0921 12:00:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0921 12:00:32] Call tree:
!!! [0921 12:00:32]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make: *** [Makefile:92: all] Error 1

### Which tests are failing?

make all GOGCFLAGS="-N -l" GOLDFLAGS="-v"

### Since when has it been failing?

none

### Anything else we need to know?

root@ubuntu23-master:/home/zengzc/goPath/src/github.com/kubernetes/kubernetes# go version
go version go1.21.1 linux/amd64
root@ubuntu23-master:/home/zengzc/goPath/src/github.com/kubernetes/kubernetes# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 23.04
Release:	23.04
Codename:	lunar
root@ubuntu23-master:/home/zengzc/goPath/src/github.com/kubernetes/kubernetes# ls
api    CHANGELOG     cluster  code-of-conduct.md  docs    go.sum  LICENSE   logo      Makefile.bak              _output  OWNERS_ALIASES  plugin     SECURITY_CONTACTS  SUPPORT.md  third_party
build  CHANGELOG.md  cmd      CONTRIBUTING.md     go.mod  hack    LICENSES  Makefile  Makefile.generated_files  OWNERS   pkg             README.md  staging            test        vendor
root@ubuntu23-master:/home/zengzc/goPath/src/github.com/kubernetes/kubernetes# git branch
  master
* release-1.28

### Relevant SIG(s)

/sig

**Comment by wojiushixiaobai** [comment]
You can solve the problem through the following command
```sh
./hack/update-vendor.sh
make all GOFLAGS=-v GOGCFLAGS="-N -l"
```
