### ISSUE TITLE
Curl request gets pretty printed by default

### ISSUE THREAD

**Issue by wiardvanrij** [kubernetes/kubernetes#120882]
### What happened?

```
curl http://localhost:8080/api/v1/namespaces/my-namespace/pods/my-pod
```

= 64K bytes

```
curl http://localhost:8080/api/v1/namespaces/my-namespace/pods/my-pod?pretty=false
```

= 32k bytes

### What did you expect to happen?

API call defaults to pretty=false

The docs say: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/
```
pretty	If 'true', then the output is pretty printed.
```

It does not mention that there is a default. So to me, that implies that pretty is not set/true

### How can we reproduce it (as minimally and precisely as possible)?

Curl an object with and without the arg `pretty=true` and diff the response size

### Anything else we need to know?

IF pretty=true is the default, I would then prefer the docs are updated to reflect that. But also reconsider making the x2 response size the default. 

### Kubernetes version

<details>
1.25 EKS
</details>

### Cloud provider

<details>
AWS
</details>

**Comment by Jefftree** [comment]
pretty is off by default but is on for specific "human" user agents. This includes curl, wget, etc. Refer to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/negotiation/negotiate.go#L109-L113

/triage accepted

**Comment by wiardvanrij** [comment]
> pretty is off by default but is on for specific "human" user agents. This includes curl, wget, etc. Refer to https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/negotiation/negotiate.go#L109-L113
> 
> /triage accepted

Oh wow, thanks so much for that context. That explains A LOT :)

**Comment by ldemailly** [comment]
curl is a bit of an issue for libcurl, no? also consider not doing it if `Accept: application/json` is set? in general, magic is probably not great, for APIs (humans can always `| jq` if needed and browsers can do pretty printing)

**Comment by Jefftree** [comment]
I'm not too familiar with the historical context, feel free to raise this with [sig-apimachinery](https://kubernetes.slack.com/messages/sig-api-machinery) in the slack channel or meeting if you feel the default should be changed.

**Comment by satyampsoni** [comment]
I would like to work on it. Can anyone guide me how to proceed further?
