### ISSUE TITLE
[KMSv2] Example reference implementation using PKCS11

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#120879]
In regards to PKCS11 we will probably need to use SoftHSM. Some resources that might help:

- https://github.com/psmiraglia/docker-softhsm
- https://github.com/theparanoids/crypki
- https://banzaicloud.com/docs/bank-vaults/hsm/softhsm

xref: https://github.com/kubernetes/kubernetes/issues/114188#issuecomment-1452231245

**Comment by sftim** [comment]
IMO, also
/sig security

**Comment by sftim** [comment]
SoftHSM is https://www.opendnssec.org/softhsm/
