### ISSUE TITLE
Critical: Node reboot could lead to data loss due to broken volume lifecycle management

### ISSUE THREAD

**Issue by semekh** [kubernetes/kubernetes#120853]
### What happened?

In certain situations, rebooting a Kubernetes node could lead to:
- Best case: A volume not getting mounted, despite it being a healthy volume
- Worse case: A volume getting mounted in an (ephemeral) empty host directory
- Worst cast: The wrong volume getting mounted inside the pod

### What did you expect to happen?

The right volume must be mounted in the right pod.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a PVC, and make sure all ongoing pod creations happen on the same node
- Create a deployment with long termination grace period, say 600 seconds, that uses that PVC, wait for it to become Ready
- Delete the deployment, which should result in the pod getting stuck in `Terminating` state
- Create another deployment that uses the same PVC
- Reboot the underlying node

After the reboot, one of the two happens:
- CSI node driver receives `NodePublishVolume` before receiving any `NodeStageVolume` requests, meaning the CSI will try to `Publish` using an invalid stage directory, which could lead to the CSI not being able to publish it (Best case) or it mounting the wrong volume (Worst case)
- CSI node driver does not receive any requests, and kubelet goes ahead and mounts the empty directory inside the pod, leading to the "Worse case" scenario described above.

These steps almost always results in one of the undesired outcomes to happen.

### Anything else we need to know?

After realizing that the issue was a regression, we bisected it, and it looks like this was first introduced in 1.23.15. We've verified that the issue disappears after downgrading node's kubelet to 1.23.14, but 1.23 and 1.24 have reached their EOL already.
Based on the history of changes on kubelet's volume manager code, the issue might've had been introduced in [this commit range](https://github.com/kubernetes/kubernetes/compare/75b8b1ebfd55e1c5042cdc33d3f30d8080bd707e%5E...390fc21359561b9094eff93e60176e244f3af54b).

### Kubernetes version

All currently supported kubelet versions (> 1.25) are affected.

### Cloud provider

N/A

### OS version

N/A

**Comment by thoro** [comment]
I have not pinpointed this issue, but we are also experiencing issues with pods using an empty dir - especially in combination with the zalando/postgres-operator it sometimes happens that it just gets reinitialized into the empty dir and no one notices.

The pods in question use a custom csi operator, that does not use StageVolume/UnstageVolume - so I was always assuming it was a hidden bug in our software and haven't looked further into kubernetes.

**Comment by tedyu** [comment]
```
klog.ErrorS(err, "Could not add pod to volume information to actual state of world", "pod", klog.KObj(volume.pod))
```
Did you see log in the above form after reboot ?

**Comment by jsafrane** [comment]
I think it would be better to track separate issues for each of the observed behavior. And under sig-storage
/sig storage

> Best case: A volume not getting mounted, despite it being a healthy volume

This can have many root causes, please open a new issue + share pod events + relevant kubelet and CSI driver logs.

>  Worse case: A volume getting mounted in an (ephemeral) empty host directory

That smells like https://github.com/kubernetes/kubernetes/issues/117513. It should be much better in 1.28 with `NewVolumeManagerReconstruction` feature on.

> Worst cast: The wrong volume getting mounted inside the pod

That can have serious security implications ("a database of credit cards is shown instead of a pregenerated web page"). Please open a new issue, and as above, provide logs + events + everything you know.

**Comment by mmiranda96** [comment]
/remove-sig node

+1 on @jsafrane comment, please open different issues for each case.

**Comment by xing-yang** [comment]
If this is still an issue, please open different issues for each case as suggested previously.  I'm going to close this one.  Thanks.
