### ISSUE TITLE
encryption-at-rest: Tracing is added to the API server to assess transformation timings

### ISSUE THREAD

**Issue by aramase** [kubernetes/kubernetes#120881]
This is GA graduation criteria for KMSv2: https://github.com/kubernetes/enhancements/tree/master/keps/sig-auth/3299-kms-v2-improvements#ga

xref: https://kubernetes.io/docs/concepts/cluster-administration/system-traces/

- Validate we have the tracing instrumentation to report transformation timings (including gRPC calls)
- Add instrumentation to the PKCS11 reference implementation

**Comment by MaryamTavakkoli** [comment]
Hello! 
I am checking in on behalf of the Bug Triage release team.

I would like to notify you that the code freeze is starting (01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023) (about 2 weeks from now). Please ensure your issue goes in by then if you are targeting 1.29 release. (Also, please add the kind and priority labels)

Please let us know if we can be of any assistance and help :)
