### ISSUE TITLE
When deleting pods on the same node in batches, the exited container may remain, causing pod records to remain.

### ISSUE THREAD

**Issue by ZhangZhicheng1900** [kubernetes/kubernetes#120859]
### What happened?

During performance testing, I found that when deleting pods on a node in batches, such as 100, the problem of pod deletion failure may occur. The exited container may remain, causing pod records to remain. I think this problem is related to the implementation of pod_container_deletor.go that containerDeletorBufferLimit is only 50. and in the func (p *podContainerDeletor) deleteContainersInPod, when the worker channel is full, it discards the event. I think using work queue instead of channel is a better solution. And the processing logic of runtime.DeleteContainer needs to be optimized. The processing can be skipped for containers that have been externally deleted or cannot be found. 

And i found it still almost the same solution in podContainerDeletor. The master branch may also have the same problem.

I will submit a PR later for this issue.

### What did you expect to happen?

pods and containers can be deleted successfully

### How can we reproduce it (as minimally and precisely as possible)?

batch delete over than 100 pods that on same node

### Kubernetes version

<details>

```console
$ kubectl version
v1.17.5

![1a4518d29eabb089184493696821025](https://github.com/kubernetes/kubernetes/assets/22294755/89076b32-8a34-49e6-81c3-4235179447a4)


```

</details>

### Cloud provider

<details>
icbc private cloud
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME-"SLES
VERSION-"12-SP5VERSION ID-"12.5"PRETTY NAME="SUSE Linux EnterpriseServer 12 SP5"
ID-"sles"ANSI COLOR-"0;32CPE NAME-"cpe:/o:suse:sles:12:sp5"

$ uname -a
Linux dkfhc6749web000 4.12.14-120-efault #1 SMP Thu Nov 7 16:39:09 UTC 2019 (fd9dc36) x86 64 x86 64 X86 64 GNU/Linux


![eaa5f347b3394cc8c534916578bda5e](https://github.com/kubernetes/kubernetes/assets/22294755/230d6d46-3879-4790-a5e6-010cb51ab44b)



```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
docker 18.09.7
![703c32c2bfc2477dd77476429ac4d60](https://github.com/kubernetes/kubernetes/assets/22294755/df2228b1-ad22-463e-8238-90ac932f2733)

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
no CNI, no CSI, just use docker local network and pod simple volumes
</details>

**Comment by aojea** [comment]
The last supported version is 1.25 https://kubernetes.io/releases/ and docker is no longer supported since 1.24 https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/

/close

please reopen if you can reproduce it in one of the supported versions and components
