### ISSUE TITLE
Horizontal pod autoscaler basing on scale subresource

### ISSUE THREAD

**Issue by jszczepkowski** [kubernetes/kubernetes#12087]
We are going to introduce Scale subresource and implement horizontal autoscaling of pods on a base of it. Scale subresource will be supported for RCs and Deployments. HorizontalPodAutoscaler object will be bound with exactly one Scale subresource and will be autoscaling associated RC/deployment through it.

### Scale subresource
Scale subresource will be present for RC or deployment under the following paths:
`api/vX/replicationcontrollers/myrc/scale`
`api/vX/deployments/mydeployment/scale`

It will will contain the following fields: 
`Spec(Count)`, `Status(Count, PodSelector)`

Writing `Spec(Count)` will resize RC/deployment associated with the given Scale subresource.

`Status(Count)` will report how many pods are currently running in RC/deployment, and `Status(PodSelector)` will return selector for the pods.

### HorizontalPodAutoscaler object
We will introduce HorizontalPodAutoscaler object, it will contain the following fields:
`Scale`, `MinCount`, `MaxCount`, `TargetCPUConsumption`.

The autoscaler will be implemented as a control loop. It will query pods described by PodSelector from Status of Scale subresource, and check their average CPU usage from the last 1 minute on heapster (there will be API on master for this purpose). Then, it will compare the current CPU consumption with the TargetCPUConsumption, and adjust the count of the Scale if needed to match the target (preserving condition MinCount <= Count <= MaxCount).

**Comment by jszczepkowski** [comment]
CC @smarterclayton @pweil- @bgrant0607 @davidopp @erictune @fgrzadkowski @mwielgus @piosz

**Comment by smarterclayton** [comment]
@ramr

**Comment by smarterclayton** [comment]
Shouldn't this use #11951 for metrics?

**Comment by smarterclayton** [comment]
(Eventually)

**Comment by smarterclayton** [comment]
Can you describe how this differs (for reference) from the earlier proposals (threshold based)?  Is it simpler in order to get a working minimal viable setup?

**Comment by piosz** [comment]
@smarterclayton that's what @jszczepkowski wrote here:
> (there will be API on master for this purpose)

**Comment by davidopp** [comment]
ref/ #1629 
ref/ #5492 
ref/ #9612

**Comment by jszczepkowski** [comment]
> Shouldn't this use #11951 for metrics?

Yes, we are going to use it.

> Can you describe how this differs (for reference) from the earlier proposals (threshold based)? Is it simpler in order to get a working minimal viable setup?

The first version of autoscaler will be threshold based: user will specify the target CPU consumption and autoscaler will choose such size the target will be meet. Later, we can work on extending API, so that other resources that CPU may be specified. We may also consider introducing API for rule based approach (e.g.: "if CPU drop belllow 50% remove one pod").

**Comment by smarterclayton** [comment]
Thanks

On Mon, Aug 3, 2015 at 3:30 AM, Jerzy Szczepkowski <notifications@github.com
> wrote:

> Shouldn't this use #11951
> <https://github.com/GoogleCloudPlatform/kubernetes/pull/11951> for
> metrics?
>
> Yes, we are going to use it.
>
> Can you describe how this differs (for reference) from the earlier
> proposals (threshold based)? Is it simpler in order to get a working
> minimal viable setup?
>
> The first version of autoscaler will be threshold based: user will specify
> the target CPU consumption and autoscaler will choose such size the target
> will be meet. Later, we can work on extending API, so that other resources
> that CPU may be specified. We may also consider introducing API for rule
> based approach (e.g.: "if CPU drop belllow 50% remove one pod").
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12087#issuecomment-127147727>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by smarterclayton** [comment]
This LGTM as a first pass proposal

On Mon, Aug 3, 2015 at 4:43 PM, Clayton Coleman <ccoleman@redhat.com> wrote:

> Thanks
>
> On Mon, Aug 3, 2015 at 3:30 AM, Jerzy Szczepkowski <
> notifications@github.com> wrote:
>
>> Shouldn't this use #11951
>> <https://github.com/GoogleCloudPlatform/kubernetes/pull/11951> for
>> metrics?
>>
>> Yes, we are going to use it.
>>
>> Can you describe how this differs (for reference) from the earlier
>> proposals (threshold based)? Is it simpler in order to get a working
>> minimal viable setup?
>>
>> The first version of autoscaler will be threshold based: user will
>> specify the target CPU consumption and autoscaler will choose such size the
>> target will be meet. Later, we can work on extending API, so that other
>> resources that CPU may be specified. We may also consider introducing API
>> for rule based approach (e.g.: "if CPU drop belllow 50% remove one pod").
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12087#issuecomment-127147727>
>> .
>>
>
>
>
> --
> Clayton Coleman | Lead Engineer, OpenShift
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by xiejunan** [comment]
@jiangyaoguo

**Comment by smarterclayton** [comment]
For reference here is the idling proposal that describes the 0->1 scale - where an RC has been scaled to 0 based on a platform policy, and a service needs to hold incoming connections until at least one endpoint is available (subject to rate limiting and constraints): https://github.com/GoogleCloudPlatform/kubernetes/pull/3247

**Comment by xiejunan** [comment]
@jiangyaoguo

**Comment by smarterclayton** [comment]
Can you link the PRs for this feature to this issue so we can coordinate those with folks?

**Comment by jszczepkowski** [comment]
> Can you link the PRs for this feature to this issue so we can coordinate those with folks?

Done

**Comment by bgrant0607** [comment]
Closing in favor or more specific issues.
