### ISSUE TITLE
move GetKernelVersion out of `pkg/proxy/ipvs`

### ISSUE THREAD

**Issue by danwinship** [kubernetes/kubernetes#120895]
The ipvs proxy has code to check the kernel version (including a mockable interface), and this has ended up getting used outside of that code; currently in kubelet (`pkg/kubelet/sysctl`) for figuring out what sysctls are available (for pods to request to be set), and in the future in https://github.com/kubernetes/kubernetes/pull/120354, for figuring out if a certain conntrack hack is needed.

We should move that code somewhere more generic.

/sig network
/cc @aroradaman @cyclinder

**Comment by HirazawaUi** [comment]
That sounds great, but the code still needs to be accessible by the kubelet, because we need the kubelet to decide if the pods with safe sysctl are working properly or not

**Comment by aroradaman** [comment]
maybe here https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/component-helpers/node/util ?

**Comment by cyclinder** [comment]
I think we should move this to https://github.com/kubernetes/utils, After the move is complete, We update all code in k/k (such as kubelet and kube-proxy) that uses `GetKernelVersion` so that they no longer import ipvs packages.

/assign

**Comment by aroradaman** [comment]
I thought of k/utils and k/k/pkg/util but couldn't find any relevant package and we already import **sysctl** from k/component-helpers/node/util in kube-proxy

**Comment by cyclinder** [comment]
Most of the time, If we use `GetKernelVersion`, we should import https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/version/version.go, which has some version comparison functions.

**Comment by danwinship** [comment]
If it's only shared between kubelet and kube-proxy it doesn't need to be in `staging`; it can just be in `pkg/util` somewhere. (I'm not saying component-helpers or whatever is definitely wrong, but usually we don't put things there until it's needed by something outside of core...)

> Most of the time, If we use `GetKernelVersion`, we should import https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/version/version.go, which has some version comparison functions.

Yes, adding some additional helper functions based on the existing users could be useful.

**Comment by aroradaman** [comment]
@danwinship do we still need the mockable interface ?
Right now there is no mocked implementation of `KernelHandler`, https://github.com/kubernetes/kubernetes/pull/111806 removed the `fakeKernelHandler` and this consumed as a utility function only. Will a simple utility function be sufficient  ?
