### ISSUE TITLE
CentOS virt7-testing repo has not been updated for 1.0 release

### ISSUE THREAD

**Issue by jsravn** [kubernetes/kubernetes#12080]
I'm using https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/getting-started-guides/fedora/fedora_ansible_config.md on CentOS machines.

The ansible scripts add http://cbs.centos.org/repos/virt7-testing/x86_64/os/ as a yum repo to pull in kubernetes, but it looks like that repo hasn't been updated to the 1.0 binaries. 0.18 is the latest kubernetes there.

As a result, controller manager fails to start with `unknown flag: --root_ca_file`.

**Comment by luanchuanmalu** [comment]
you can try this one, i use it replace the yum repo virt7-testing, 

[virt7-docker-common-candidate]
name=virt7-docker-common-candidate
baseurl=http://cbs.centos.org/repos/virt7-docker-common-candidate/x86_64/os/
gpgcheck=0

**Comment by roberthbailey** [comment]
Marking as obsolete since this hasn't been updated in over a year.
