### ISSUE TITLE
How to setup a warmup period for the scaled-out replicas in Kubernetes?

### ISSUE THREAD

**Issue by vivuu1989** [kubernetes/kubernetes#120841]
### What happened?

We are using Istio version 1.18.2 on all our AKS (V1.27.3) based envts (Dev,Stg, Prod, Dr, etc.) setup. We have enabled the Istio sidecars injection with namespace injection for Springboot java-based applications.

During our scalability tests, we noticed that when a service scales out, (i.e. from 3 to 4 instances), the new instance after reporting being healthy immediately gets i.e. 25% of the load. Since the service instance did not have a chance to warm up yet, requests sent to it temporarily time out or show increased response time compared to other existing instances. This state can remain from 3-4 minutes to even 15 minutes, depending on the load, from what we saw in our tastings.

### What did you expect to happen?

We were looking for a scaling related solution so that a new service instances right after scaling out to receive load that they are able to handle.
so that scaling out does not cause temporary response time to increase for the production services. 

We searched for a solution from istio side and tried as per the solution provided here for Destination Rule. 
https://stackoverflow.com/questions/74517652/gradually-warm-java-application-in-k8s-with-istio#:~:text=trafficPolicy%3A%0A%20%20%20%20loadBalancer%3A%0A%20%20%20%20%20%20simple%3A%20ROUND_ROBIN%0A%20%20%20%20%20%20warmupDurationSecs%3A%20180s 

    apiVersion: networking.istio.io/v1alpha3
    kind: DestinationRule
    metadata:
      name: myapp
      namespace: myns
    spec:
      host: "myapp.myns.svc.cluster.local"
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN
          warmupDurationSecs: "180s"
      subsets:
        - name: v1
          labels:
            app: myapp
            version: 1.0

In our destination rule, we haven't configured different versions for subsets, and it will be always v1.0 (we don't require the different versions as of now). But this solution of traffic policy also didn't worked as expected, as we tested the scaling behavior and not anew release.

is there any way to achieve this using istio while scaleout happening. ?

### How can we reproduce it (as minimally and precisely as possible)?

when a service scales out, (i.e. from 3 to 4 instances), the new instance after reporting being healthy immediately gets i.e. 25% of the load. Since the service instance did not have a chance to warm up yet, requests sent to it temporarily time out or show increased response time compared to other existing instances. This state can remain from 3-4 minutes to even 15 minutes, depending on the load, from what we saw in our tastings.

### Kubernetes version

V1.18.2

### Cloud provider

Azure AKS

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pacoxu** [comment]
This seems to be a support case for https://github.com/istio/istio/issues.

**Comment by vivuu1989** [comment]
> This seems to be a support case for https://github.com/istio/istio/issues.



> This seems to be a support case for https://github.com/istio/istio/issues.

No. I am looking for some solution from Kubernetes side itself.. if its have any solution without relay on istio
