### ISSUE TITLE
Check for bridge-nf-call-iptables=1 incorrect

### ISSUE THREAD

**Issue by uablrek** [kubernetes/kubernetes#120849]
### What happened?

The check in:
https://github.com/kubernetes/kubernetes/blob/c5cf0ac1889f55ab51749798bec684aed876709d/pkg/proxy/ipvs/proxier.go#L333-L338

is incorrect. It misses the case when the sysctl doesn't exist (err != nil).

/sig network
/area ipvs
/area kube-proxy

### What did you expect to happen?

The check sould be:
```go
 err != nil || val != 1
```

### How can we reproduce it (as minimally and precisely as possible)?

To reproduce you must use a kernel without the function, or the module unloaded. This is likely not easy if a regular Linux distro is used. But IMO no e2e testing should be needed (none exist now).

### Anything else we need to know?

It's just a warning that may be missed, so nothing urgent.

### Kubernetes version

master (all)

### Cloud provider

N/A

### OS version

N/A

### Install tools

N/A

### Container runtime (CRI) and version (if applicable)

N/A

### Related plugins (CNI, CSI, ...) and versions (if applicable)

N/A

**Comment by aojea** [comment]
@danwinship removed one of those https://github.com/kubernetes/kubernetes/pull/120818 , it looks that we should remove this to be consistent

**Comment by dhruvmehtaaa** [comment]
@aojea I can work on removing the code to maintain consistency. Can you please assign this issue to me

**Comment by HirazawaUi** [comment]
/assign @dhruvmehtaaa

You can also use `/assign` to assign the issue to yourself.

**Comment by danwinship** [comment]
oops, I should have thought to check ipvs backend too
