### ISSUE TITLE
TestWebSocketClient_ProtocolVersions flake

### ISSUE THREAD

**Issue by liggitt** [kubernetes/kubernetes#120967]
/sig api-machinery
/kind flake bug
/assign @seans3
/cc @aojea 
/priority important-soon

```
{Failed;  === RUN   TestWebSocketClient_ProtocolVersions
E1002 13:45:45.706699   64713 v2.go:150] next reader: websocket: close 1006 (abnormal closure): unexpected EOF
E1002 13:45:45.707990   64713 v2.go:150] next reader: websocket: close 1006 (abnormal closure): unexpected EOF
E1002 13:45:50.706933   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
E1002 13:45:50.709236   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36098->127.0.0.1:42119: use of closed network connection
E1002 13:45:55.709664   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
E1002 13:45:55.709705   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36098->127.0.0.1:42119: use of closed network connection
E1002 13:45:55.709822   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36104->127.0.0.1:42119: write: broken pipe
E1002 13:46:00.706908   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
E1002 13:46:00.709127   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36098->127.0.0.1:42119: use of closed network connection
E1002 13:46:00.710298   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36104->127.0.0.1:42119: write: broken pipe
E1002 13:46:05.706953   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
E1002 13:46:05.709183   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36098->127.0.0.1:42119: use of closed network connection
E1002 13:46:05.709273   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36104->127.0.0.1:42119: write: broken pipe
E1002 13:46:10.707054   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
E1002 13:46:10.708238   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36098->127.0.0.1:42119: use of closed network connection
E1002 13:46:10.709404   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36104->127.0.0.1:42119: write: broken pipe
E1002 13:46:15.707379   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connection
    websocket_test.go:752: expect stream to be closed after connection is closed.
```

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/issues/117668#issuecomment-1743068321_

**Comment by ardaguclu** [comment]
I think, sometimes `SetCloseHandler` are not triggered and code does not execute https://github.com/kubernetes/kubernetes/blob/a0d6a815fcc02cbfea1bb22d13a8e896ecbe116c/staging/src/k8s.io/client-go/tools/remotecommand/websocket.go#L448 and causing heartbeat handler goroutine hangs.
This does not stem from the unit tests, instead we need to find a way to kill that goroutine even if `SetCloseHandler` is not triggered.

**Comment by ardaguclu** [comment]
This may be fixed https://github.com/gorilla/websocket/issues/849 in latest version

**Comment by aojea** [comment]
@ardaguclu are you taking on this? should we assign it to you?

**Comment by ardaguclu** [comment]
I can bump to gorilla/websockets but it collides with @seans3's PR. If bump won't solve the problem, I'll investigate and yes, you can assign it to me :)

**Comment by ardaguclu** [comment]
ah, I made a mistake, there is no fix at all in https://github.com/gorilla/websocket/issues/849.

/assign

**Comment by aojea** [comment]
we are using latest release and I don't see any commit related to this problem or the bug you mention, why do you think this is fixed in gorilla already? it seems more a problem in our implementation of the heartbeat

**Comment by ardaguclu** [comment]
CloseAbnormalClosure is not valid https://github.com/gorilla/websocket/blob/666c197fc9157896b57515c3a3326c3f8c8319fe/conn.go#L219

And when it is not valid, closeHandler simply is not executed https://github.com/gorilla/websocket/blob/666c197fc9157896b57515c3a3326c3f8c8319fe/conn.go#L983

I'm surprised to see this. Now, if we figure out when `CloseAbnormalClosure` is happened, this will be resolved. 

But that proves that there is a chance of heartbeat goroutine can be leaked if invalid statuses arise and maybe we return whenever ping fails instead of retrying.

**Comment by aojea** [comment]
@ardaguclu I think that fix is easier

> E1002 13:46:10.709404   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36104->127.0.0.1:42119: write: broken pipe
> E1002 13:46:15.707379   64713 websocket.go:478] Websocket Ping failed: write tcp 127.0.0.1:36094->127.0.0.1:42119: use of closed network connectio

https://github.com/kubernetes/kubernetes/blob/a0d6a815fcc02cbfea1bb22d13a8e896ecbe116c/staging/src/k8s.io/client-go/tools/remotecommand/websocket.go#L475-L482

The comment there is wrong, but we need to handle the errors and only retry on transient errors and exit on fatal ones

**Comment by ardaguclu** [comment]
I'm fine with that approach(although it will add at least one error log that might mislead people). How can we discriminate the fatal ones and transient errors?

**Comment by aojea** [comment]
> How can we discriminate the fatal ones and transient errors?

check `WriteControl()`

**Comment by ardaguclu** [comment]
I think, the other problem(or a known and acceptable consequence) is that v2 subprotocol might cause abnormal closure

**Comment by aojea** [comment]
> I'm fine with that approach(although it will add at least one error log that might mislead people). How can we discriminate the fatal ones and transient errors?

that is the complexity, gorilla already does that for the exact same `conn.WriteControl`method, I don't see why we can't apply the same logic here

**Comment by ardaguclu** [comment]
Since the PR has been merged, I think we can close this;
/close
