### ISSUE TITLE
kube-proxy fails to start for IPv6 when underlying infra is dual stack in 1.28

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/kubernetes#120999]
### What happened?

A new  kube-proxyvalidation introduced in k8s 1.28 seems to break Azure + ipv6. IPv6 clusters on Azure run on dual-stack hosts. The IPv6 node IP seems like it's only getting assigned to the Node until after kube-proxy starts (someone might need to help me understand what component is responsible). However, kube-proxy now fails to start with:

kube-proxy is in CrashloopBackoff, logs show:

``` 
I0825 16:18:19.872382       1 server_others.go:69] "Using iptables proxy"
I0825 16:18:19.892673       1 node.go:141] Successfully retrieved node IP: 10.1.0.6
I0825 16:18:19.894163       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=131072
I0825 16:18:19.912200       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
E0825 16:18:19.912228       1 server.go:537] "Error running ProxyServer" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"
E0825 16:18:19.912240       1 run.go:74] "command failed" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"
```

Full logs: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-azure/4086/pull-cluster-api-provider-azure-conformance-ipv6-with-ci-artifacts/1709361655076360192/artifacts/clusters/capz-conf-klo2dh/

### What did you expect to happen?

Kube-proxy should start. This does not repro with prior versions of k8s (1.27 and below). 

### How can we reproduce it (as minimally and precisely as possible)?

- Build a Kubernetes cluster with v1.28 on Azure (underlying subnet has both IPv6 and Ipv4 addresses) with Kubeadm (e.g. CAPZ), configure the cluster CIDRs to single stack IPv6 (detailed instructions in https://capz.sigs.k8s.io/topics/ipv6)
- Observe the kube-proxy pod is crashing

This repros consistently

### Anything else we need to know?

This new validation was introduced in https://github.com/kubernetes/kubernetes/pull/119003

### Kubernetes version

v1.28.0 and above

### Cloud provider

Azure

### OS version

Linux version 6.2.0-1011-azure

### Install tools

CAPZ

### Container runtime (CRI) and version (if applicable)

revision=b69f1ad231b6d87eeb30504398075a92d615e83e version=v1.6.23

### Related plugins (CNI, CSI, ...) and versions (if applicable)

Calico CNI (Calico fails to start due to crashing kube-proxy)

**Comment by CecileRobertMichon** [comment]
cc @danwinship @aojea @thockin @khenidak @aramase

**Comment by danwinship** [comment]
>     I0825 16:18:19.872382       1 server_others.go:69] "Using iptables proxy"
>     I0825 16:18:19.892673       1 node.go:141] Successfully retrieved node IP: 10.1.0.6
>     I0825 16:18:19.894163       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=131072
>     I0825 16:18:19.912200       1 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv4"
>     E0825 16:18:19.912228       1 server.go:537] "Error running ProxyServer" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"
>     E0825 16:18:19.912240       1 run.go:74] "command failed" err="kube-proxy configuration is incorrect: cluster is IPv4-primary but clusterCIDRs contains only IPv6 addresses"

do you have examples of the equivalent (working) startup logs from 1.27?

**Comment by danwinship** [comment]
> The IPv6 node IP seems like it's only getting assigned to the Node until after kube-proxy starts (someone might need to help me understand what component is responsible).

There are two possibilities here:
- On first startup, kubelet detects the node IPs itself, so if the host hasn't completed IPv6 configuration yet, then kubelet will start up thinking that the node is single-stack IPv4 and set the Node object accordingly. #120751 will make kubelet not do this (cc @aojea), and instead rely on the cloud-provider to set the addresses, but also this is kind of a bad setup anyway; if possible, you should try to make sure that kubelet doesn't start until after IPv6 configuration has completed. (I'm not sure what sort of distro you're using, but if it's using NetworkManager, you just need to configure the default connection to have the "require IPv6 addressing" setting.)
- After first startup, the node IP should have been set by the cloud provider, so if the cloud provider doesn't know about the IPv6 IPs, then it still might be missing... that... probably shouldn't happen? But maybe the cloud-provider refuses to return the IPv6 IP until it has been configured on the node's NIC, in which case this is the same as the other case, and you should try to configure it to wait for IPv6 addressing to complete.

But anyway, yes, it looks like there was a regression: in 1.27, kube-proxy would limp through this problem but in 1.28 it won't.

**Comment by CecileRobertMichon** [comment]
@danwinship thank you for the quick response

Here are the equivalent logs (same config) with latest k8s 1.27:

```
I1004 23:51:59.385979       1 node.go:141] Successfully retrieved node IP: 10.0.0.4
I1004 23:51:59.386048       1 server_others.go:110] "Detected node IP" address="10.0.0.4"
I1004 23:51:59.386083       1 server_others.go:554] "Using iptables proxy"
I1004 23:51:59.408422       1 server_others.go:192] "Using iptables Proxier"
I1004 23:51:59.408457       1 server_others.go:199] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I1004 23:51:59.408469       1 server_others.go:200] "Creating dualStackProxier for iptables"
I1004 23:51:59.408580       1 server_others.go:475] "Detect-local-mode set to ClusterCIDR, but no IPv4 cluster CIDR defined, defaulting to no-op detect-local for IPv4"
I1004 23:51:59.408693       1 proxier.go:253] "Setting route_localnet=1 to allow node-ports on localhost; to change this either disable iptables.localhostNodePorts (--iptables-localhost-nodeports) or set nodePortAddresses (--nodeport-addresses) to filter loopback addresses"
I1004 23:51:59.409878       1 server.go:658] "Version info" version="v1.27.6-35+fa4de05719a75b"
I1004 23:51:59.409898       1 server.go:660] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I1004 23:51:59.412982       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_max" value=131072
I1004 23:51:59.413296       1 conntrack.go:52] "Setting nf_conntrack_max" nfConntrackMax=131072
I1004 23:51:59.413658       1 conntrack.go:100] "Set sysctl" entry="net/netfilter/nf_conntrack_tcp_timeout_close_wait" value=3600
I1004 23:51:59.413939       1 config.go:188] "Starting service config controller"
I1004 23:51:59.414027       1 shared_informer.go:311] Waiting for caches to sync for service config
I1004 23:51:59.414135       1 config.go:97] "Starting endpoint slice config controller"
I1004 23:51:59.414202       1 shared_informer.go:311] Waiting for caches to sync for endpoint slice config
I1004 23:51:59.414747       1 config.go:315] "Starting node config controller"
I1004 23:51:59.414887       1 shared_informer.go:311] Waiting for caches to sync for node config
I1004 23:51:59.515182       1 shared_informer.go:318] Caches are synced for node config
I1004 23:51:59.515214       1 shared_informer.go:318] Caches are synced for endpoint slice config
I1004 23:51:59.515194       1 shared_informer.go:318] Caches are synced for service config
```

**Comment by neoaggelos** [comment]
Hi, we are seeing a very similar behavior in 1.28 due to the ClusterCIDRs:

```
Oct 04 16:24:35 np0035415031 microk8s.daemon-kubelite[5037]: I1004 16:24:35.881461    5037 server.go:632] "kube-proxy running in dual-stack mode" primary ipFamily="IPv6"
Oct 04 16:24:35 np0035415031 microk8s.daemon-kubelite[5037]: E1004 16:24:35.881557    5037 server.go:537] "Error running ProxyServer" err="kube-proxy configuration is incorrect: cluster is IPv6-primary but clusterCIDRs contains only IPv4 addresses"
Oct 04 16:24:35 np0035415031 microk8s.daemon-kubelite[5037]: Error: kube-proxy configuration is incorrect: cluster is IPv6-primary but clusterCIDRs contains only IPv4 addresses
```

Similarly, this was not an issue in 1.27 or previous versions.

I believe this should be handled by this change in the linked PR https://github.com/kubernetes/kubernetes/pull/121008/files#diff-962b78049692dfaf72923ea0eabea310b600f2e29011c837bdb49056e797ab34R681
