### ISSUE TITLE
[Sig Node Presubmits] - pr-node-kubelet-containerd-alpha-features failures

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#120927]
https://testgrid.k8s.io/sig-node-presubmits#pr-node-kubelet-containerd-alpha-features

Many of the sidecar jobs seems to be failing.

```
{ failed [FAILED] Error creating Pod: Pod "startup-sidecar-7da54e1c-8654-4841-a2fe-925414eadcff" is invalid: [spec.initContainers[0].readinessProbe: Forbidden: may not be set for init containers without restartPolicy=Always, spec.initContainers[0].startupProbe: Forbidden: may not be set for init containers without restartPolicy=Always]
In [It] at: test/e2e/framework/pod/pod_client.go:99 @ 09/27/23 12:50:27.723
}
```

/sig node
/sig testing

**Comment by kannon92** [comment]
@tzneal any ideas on this one?

**Comment by tzneal** [comment]
Is this a new presubmit? The error looks like the sidecar feature gate is not enabled.

**Comment by kannon92** [comment]
It seems so.

**Comment by kannon92** [comment]
https://github.com/kubernetes/test-infra/pull/30630

/cc @gjkim42

**Comment by tzneal** [comment]
That one looks like it sets the feature gates, wonder if something changed there.

**Comment by kannon92** [comment]
Do you recall if there is something wrong with this?

```
          --feature-gates=AllAlpha=true --service-feature-gates=SidecarContainers=true
```

Seems that the AllAlpha doesn't work in this test job.  The side car job (Sorry for tagging you @gjkim42) seems to work fine because it sets both --feature-gates=SidecarContainers=true and service.  But it doesn't set the other gates.

**Comment by gjkim42** [comment]
The `--feature-gates` flag is about the feature-gate settings of the node(kubelet) and the `--service-feature-gates` is about the settings of other components.

ref: https://github.com/kubernetes/kubernetes/pull/116591


> ```
>           --feature-gates=AllAlpha=true --service-feature-gates=SidecarContainers=true
> ```

I think this should be applied.

Note that setting `--service-feature-gates=AllAlpha=true` may not work, I am not sure about the exact reason, but it seems like the limitation of the node-e2e test.

**Comment by gjkim42** [comment]
I think we can close this as SidecarContainers feature has been graduated to beta.

/close
