### ISSUE TITLE
interfaceFromUnstructured and mapFromUnstructured don't record keys

### ISSUE THREAD

**Issue by eddycharly** [kubernetes/kubernetes#120983]
### What happened?

Functions `interfaceFromUnstructured` and `mapFromUnstructured` in https://github.com/kubernetes/kubernetes/blob/ae02d1c8325f6bde582e3f9d934e935f488c144a/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go don't record keys.

This is an issue when `map` or `interface` fields are embedded in structs because we can't use `FromUnstructuredWithValidation`.

See:

https://github.com/kubernetes/kubernetes/blob/ae02d1c8325f6bde582e3f9d934e935f488c144a/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L566-L570

https://github.com/kubernetes/kubernetes/blob/ae02d1c8325f6bde582e3f9d934e935f488c144a/staging/src/k8s.io/apimachinery/pkg/runtime/converter.go#L416-L447

### What did you expect to happen?

All keys should be recorded as there is no unknown fields in this case.

### How can we reproduce it (as minimally and precisely as possible)?

```golang
import (
	"testing"

	"github.com/stretchr/testify/require"
	"k8s.io/apimachinery/pkg/runtime"
)

type Value = interface{}

type Any struct {
	Value `json:",inline"`
}

type Match struct {
	Any []Any `json:"any,omitempty"`
	All []Any `json:"all,omitempty"`
}

type Object struct {
	Match Match `json:"match"`
}

func Test(t *testing.T) {
	myObj := &Object{}
	err := runtime.DefaultUnstructuredConverter.FromUnstructuredWithValidation(map[string]interface{}{
		"match": map[string]interface{}{
			"any": []interface{}{
				map[string]interface{}{
					"resource": map[string]interface{}{
						"type": "cool type",
					},
				},
			},
		},
	}, myObj, true)
	require.NoError(t, err)
}
```

### Kubernetes version

<details>

NA

</details>

### Cloud provider

<details>

NA

</details>

### OS version

<details>

NA

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by eddycharly** [comment]
One change that seems to work for `interfaceFromUnstructured` is:
```golang

func interfaceFromUnstructured(sv, dv reflect.Value, ctx *fromUnstructuredContext) error {
	// TODO: Is this conversion safe?
	dv.Set(sv)
	if ctx.isInlined {
		for _, key := range sv.MapKeys() {
			ctx.recordMatchedKey(key.String())
		}
	}
	return nil
}
```

**Comment by alexzielenski** [comment]
Closing since for this use case `UnmarshalJSON` solved the problem for you: https://kubernetes.slack.com/archives/C0EG7JC6T/p1696370895433039?thread_ts=1696331287.543159&cid=C0EG7JC6T

/close

**Comment by eddycharly** [comment]
@alexzielenski what does that mean ? is this going to be reopened ?

**Comment by alexzielenski** [comment]
no, just cleaning up API machinery issues
