### ISSUE TITLE
[Sig Node Presubmits] - kubelet-gce-cluster-e2e-inplace-pod-resize-containerd-main-v2

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#120926]
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-cluster-e2e-inplace-pod-resize-containerd-main-v2

With the migration to podutils and adding some presubmits (from periodic jobs) we are seeing some failures in presubmits. 

The error seems to have issues finding the right node to create.

```
ERROR: (gcloud.compute.instances.create) Unable to read file [/go/src/github.com/containerd/containerd/test/e2e/master.yaml]: [Errno 2] No such file or directory: '/go/src/github.com/containerd/containerd/test/e2e/master.yaml'
Failed to create master instance due to non-retryable error
...
ERROR: (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/k8s-jkns-gce-serial-1-4/zones/us-west1-b/instances/e2e-a8ef221c6e-5209e-master' was not found
```

**Comment by kannon92** [comment]
@dims any leads on solving this one?

**Comment by dims** [comment]
@kannon92 see notes on slack - https://kubernetes.slack.com/archives/C09QZ4DQB/p1695911504801069

**Comment by kannon92** [comment]
https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-cluster-e2e-inplace-pod-resize-containerd-main-v2 this looks good now!
