### ISSUE TITLE
Split etcd /health endpoint to /livez and /readyz

### ISSUE THREAD

**Issue by siyuanfoundation** [kubernetes/kubernetes#120970]
### What would you like to be added?

k/k tracking issue for https://github.com/etcd-io/etcd/issues/16007

etcd currently has a single health endpoint for etcd /health which is used in Kubernetes distros as both liveness and readiness checking. In order to be fully api-compliant, etcd should have both a liveness check (i.e. /livez) which checks that this individual etcd member is "alive" and does not need to be restarted and a readiness check (i.e. /readyz) which signals that the etcd member is ready to accept traffic.

We are seeking feedbacks for the plan and we also need to change the default etcd health check configs in kubeadm after that is done. 

### Why is this needed?

We are trying to make etcd fully api-compliant.

**Comment by neolit123** [comment]
there is a SIG etcd in the list, but the k/k label is not yet added:
https://github.com/kubernetes/community/blob/master/sig-list.md

cc @wenjiaswe @jmhbnz 

/sig api-machinery

**Comment by chaochn47** [comment]
@siyuanfoundation Will apiserver etcd health check also be updated as well? If so, please include in the ticket description. 

https://github.com/kubernetes/kubernetes/blob/5f8fc30b2c01735d8aaa22ef5618b0b424c228e9/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L256-L268

/cc @dims

**Comment by chaochn47** [comment]
Sync'd up with @siyuanfoundation offline:

Because the readiness check is only http based and any new grpc RPC won't be added in v3.5 to maintain backward compatibility, so this kube-apiserver in-process etcd health prober will stay and not be changed.

**Comment by neolit123** [comment]
@siyuanfoundation why did you close the ticket?

**Comment by siyuanfoundation** [comment]
Synced with @logicalhan offline, it is probably better we open it after the feature has landed in etcd.
