### ISSUE TITLE
configmap formatting issue when extra blank space or new line added in configmap

### ISSUE THREAD

**Issue by infa-ddeore** [kubernetes/kubernetes#120918]
### What happened?

`data.redis-config` appears on same line with "\n" when extra space or newline used in configmap yaml

```
$ k get cm example-redis-config -o yaml | k neat
apiVersion: v1
data:
  redis-config: "maxmemory 2mb \nmaxmemory-policy allkeys-lru\nabc def\npqr 123\n"
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: default
```

sample yaml with extra trailing spaces at "maxmemory" line
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-redis-config
data:
  redis-config: |
    maxmemory 2mb  
    maxmemory-policy allkeys-lru
    abc def
    pqr 123
```

### What did you expect to happen?

configmap format should be clear as below, config isnt on same line

```
$ k get cm example-redis-config -o yaml | k neat
apiVersion: v1
data:
  redis-config: |
    maxmemory 2mb
    maxmemory-policy allkeys-lru
    abc def
    pqr 123
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: default
```

### How can we reproduce it (as minimally and precisely as possible)?

cretae configmap with below yaml which has extra blankspace at the end of "maxmemory"

```
apiVersion: v1
data:
  redis-config: |
    maxmemory 2mb  
    maxmemory-policy allkeys-lru
    abc def
    pqr 123
kind: ConfigMap
metadata:
  name: example-redis-config
  namespace: default
```

removing blankspace changes the format back to readable

### Anything else we need to know?

this doesn't break the application but reading configmap becomed difficult 

### Kubernetes version

this happens in every k8 version

<details>

```console
$ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.1", GitCommit:"e4d4e1ab7cf1bf15273ef97303551b279f0920a9", GitTreeState:"clean", BuildDate:"2022-09-14T19:42:30Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/kind support
/sig api-machinery
for triage

**Comment by tamilselvan1102** [comment]
please share the path/webpage where [example-redis-config.yaml] is mentioned

**Comment by infa-ddeore** [comment]
> please share the path/webpage where [example-redis-config.yaml] is mentioned

it can be any config defined after `|` (pipe) not only specific to redis

here is the link of my sample yaml https://kubernetes.io/docs/tutorials/configuration/configure-redis-using-configmap/

**Comment by tamilselvan1102** [comment]
@neolit123
since it is webpage issue, please help to transfer

**Comment by infa-ddeore** [comment]
> @neolit123 since it is webpage issue, please help to transfer

do you mean that the webpage has extra spaces in the yaml thats why issue came?

think this as if extra space or newline is added in such configmap then the formatting is messed up, i gave a sample config but the problem will come with any config

so this issue needs to be categorised under k8s

**Comment by tamilselvan1102** [comment]
@infa-ddeore 
understood.

**Comment by neolit123** [comment]
@infa-ddeore 
a similar problem
https://github.com/brancz/gojsontoyaml/issues/1

yaml parsers are strict. the extra space may break its understanding of how a line is expressed in multiline strings.
another parser might work as expected, but k8s uses this one
https://github.com/kubernetes-sigs/yaml
also try `|-`

you could log an issue in that repo, but note the k8s yaml library is intentionally using an oldee yaml parser, so this might not be so easy to fix.

/close

**Comment by infa-ddeore** [comment]
> @infa-ddeore a similar problem [brancz/gojsontoyaml#1](https://github.com/brancz/gojsontoyaml/issues/1)
> 
> yaml parsers are strict. the extra space may break its understanding of how a line is expressed in multiline strings. another parser might work as expected, but k8s uses this one https://github.com/kubernetes-sigs/yaml also try `|-`
> 
> you could log an issue in that repo, but note the k8s yaml library is intentionally using an oldee yaml parser, so this might not be so easy to fix.
> 
> /close

thanks @neolit123 for the reply, adding `|-` also doesn't help, will raise issue in the source repo
