### ISSUE TITLE
CSI sidecar jobs failed: Filesystem resize failed when restoring from snapshot to PVC with larger size

### ISSUE THREAD

**Issue by xing-yang** [kubernetes/kubernetes#120997]
### What happened?

We got CI failures across all CSI sidecars:

https://testgrid.k8s.io/sig-storage-csi-external-snapshotter#1-27-on-kubernetes-1-27
https://testgrid.k8s.io/sig-storage-csi-external-provisioner#1-27-on-kubernetes-1-27
https://testgrid.k8s.io/sig-storage-csi-external-resizer#1-27-on-kubernetes-1-27
......

I see the following in all the failed jobs:

Kubernetes e2e suite: [It] External Storage [Driver: hostpath.csi.k8s.io] [Testpattern: Dynamic PV (default fs)] provisioning should provision correct filesystem size when restoring snapshot to larger size pvc [Feature:VolumeSnapshotDataSource] expand_less	46s
{ failed [FAILED] Filesystem resize failed when restoring from snapshot to PVC with larger size. Restored fs size: 299853492224 bytes is not larger than origin fs size: 299853492224 bytes.
HINT: Your driver needs to check the volume in NodeStageVolume and resize fs if needed.
HINT: For an example patch see: https://github.com/kubernetes/cloud-provider-openstack/pull/1563/files
Expected
    <int>: 299853492224
to be >
    <int>: 299853492224
In [It] at: test/e2e/storage/testsuites/provisioning.go:491 @ 10/04/23 11:50:44.626
}

### What did you expect to happen?

The tests should pass.

### How can we reproduce it (as minimally and precisely as possible)?

The failure shows up in the test-grid.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xing-yang** [comment]
CSI hostpath driver does not support expanding volume when creating PVC from VolumeSnapshot, so I expected the test should be skipped before getting to the point where it failed on L530.

https://github.com/kubernetes/kubernetes/blob/v1.29.0-alpha.1/test/e2e/storage/drivers/csi.go#L153
`storageframework.CapFSResizeFromSourceNotSupported: true`

https://github.com/kubernetes/kubernetes/blob/v1.29.0-alpha.1/test/e2e/storage/testsuites/provisioning.go#L530

**Comment by gnufied** [comment]
These tests are creating a snapshot of a PVC and then creating another PVC from the snapshot with 1Gi more than original size and expect the restored size to be larger than original size. Sounds like something specific to hostpath.

**Comment by niranjandarshann** [comment]
After the creation of a snapshot from an existing PVC. A new PVC is resultant from this snapshot with a size that exceeds the original PVC by 1Gi. The expected result is that the restored PVC size should be larger than the original PVC. it is noted that this issue may be related to the hostpath storage type, suggesting that there might be a specific problem or unexpected behavior associated with hostpath storage may be possible.

**Comment by mowangdk** [comment]
I have looked at the csi-driver-host-path code [loadFromSnapshot](https://github.com/kubernetes-csi/csi-driver-host-path/blob/3348ad077ce6d3c6ddac29d0a1007696beb395dc/pkg/hostpath/controllerserver.go#L152C23-L152C23) and found that when creating a new pvc using a snapshot, the new file size will be [directly replaced by the snapshot file](https://github.com/kubernetes-csi/csi-driver-host-path/blob/3348ad077ce6d3c6ddac29d0a1007696beb395dc/pkg/hostpath/hostpath.go#L301C53-L301C61), resulting in the e2e test executing the stat to read the file in pods with the same size as the original.

**Comment by mowangdk** [comment]
> I have looked at the csi-driver-host-path code [loadFromSnapshot](https://github.com/kubernetes-csi/csi-driver-host-path/blob/3348ad077ce6d3c6ddac29d0a1007696beb395dc/pkg/hostpath/controllerserver.go#L152C23-L152C23) and found that when creating a new pvc using a snapshot, the new file size will be [directly replaced by the snapshot file](https://github.com/kubernetes-csi/csi-driver-host-path/blob/3348ad077ce6d3c6ddac29d0a1007696beb395dc/pkg/hostpath/hostpath.go#L301C53-L301C61), resulting in the e2e test executing the stat to read the file in pods with the same size as the original.

It looks like this problem should have existed in 1.26 and previous versions, so why was it exposed in 1.27? Is it a configuration error?

**Comment by xing-yang** [comment]
@mowangdk I know how to fix it now. Can you update the deployment folder to match the new versions we are supporting now (1.26, 1.27, 1.28)?
https://github.com/kubernetes-csi/csi-driver-host-path/tree/HEAD/deploy

You also need to set FSResizeFromSourceNotSupported to true for every version. See this PR:
https://github.com/kubernetes-csi/csi-driver-host-path/pull/401/files

**Comment by mowangdk** [comment]
> @mowangdk Can you update the deployment folder to match the new versions we are supporting now (1.26, 1.27, 1.28)? https://github.com/kubernetes-csi/csi-driver-host-path/tree/HEAD/deploy
> 
> Make sure FSResizeFromSourceNotSupported is set to true for every version. See this PR: https://github.com/kubernetes-csi/csi-driver-host-path/pull/401/files

okay~

**Comment by xing-yang** [comment]
This is not fixed yet.

/reopen

**Comment by xing-yang** [comment]
Tests are still failing on sidecar repos.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-csi_node-driver-registrar/340/pull-kubernetes-csi-node-driver-registrar-1-27-on-kubernetes-1-27/1711308248071540736

From the build logs:
```
Initialized empty Git repository in /home/prow/go/pkg/csiprow.owG5Z5HWYc/csi-driver/.git/
Tue Oct 10 15:43:47 UTC 2023 go1.21.2 /home/prow/go/pkg/csiprow.owG5Z5HWYc/csi-driver$ git fetch --depth=1 https://github.com/kubernetes-csi/csi-driver-host-path v1.11.0
From https://github.com/kubernetes-csi/csi-driver-host-path
```
I don't see the new parameter in test-driver.yaml in v1.11.0:
https://github.com/kubernetes-csi/csi-driver-host-path/blob/release-1.11/deploy/kubernetes-1.24-test/test-driver.yaml#L23
https://github.com/kubernetes-csi/csi-driver-host-path/blob/release-1.11/deploy/kubernetes-1.24/test-driver.yaml#L23

It's in the latest code:
https://github.com/kubernetes-csi/csi-driver-host-path/blob/master/deploy/kubernetes-1.26/test-driver.yaml#L23
```
FSResizeFromSourceNotSupported: true
```
We need to cut a new csi-driver-host-path release and update image in prow.sh in csi-release-tools.

**Comment by mowangdk** [comment]
> We need to cut a new csi-driver-host-path release and update image in prow.sh in csi-release-tools.

@xing-yang I can help with updating the csi-release-tools after the new version is released~

**Comment by xing-yang** [comment]
@mowangdk csi-driver-host-path 1.12 is released: https://github.com/kubernetes-csi/csi-driver-host-path/releases/tag/v1.12.0.  Can you help update the csi-release-tools?  Thanks.

**Comment by mowangdk** [comment]
> @mowangdk csi-driver-host-path 1.12 is released: https://github.com/kubernetes-csi/csi-driver-host-path/releases/tag/v1.12.0. Can you help update the csi-release-tools? Thanks.

ptal~

**Comment by xing-yang** [comment]
Still fails: https://github.com/kubernetes-csi/external-provisioner/pull/1050

Need to update images in test-infra:
https://github.com/kubernetes/test-infra/pull/31036

**Comment by xing-yang** [comment]
Fixed now.
