### ISSUE TITLE
About the future of existing PV generated from the in-tree format yaml once the CSI migration is complete

### ISSUE THREAD

**Issue by ziyi-xie** [kubernetes/kubernetes#120907]
### What would you like to be added?

As the title mentions, our customers are concerned about the future of existing PV generated from the in-tree format yaml once the CSI migration is complete.
I am stuck on this and would really like to know what the SIG storage policy is on this matter.

### Why is this needed?

CSI Migration allows PVs with Specs in in-tree format to be manipulated via CSI, but PVs with Specs in CSI format are treated differently from in-trees,
our customers is concerned about whether In-tree Spec and PVs generated from In-tree format yaml files will work forever in the future, or whether we need to convert from PVs generated from In-tree format yaml files to CSI PVs once the CSI migration is complete, and do we have to recreate the deployment via CSI spec if the in-tree format yaml file is no longer available.

I believe some translate functions that translate In-tree PV Spec into the CSI PV format have been added in https://github.com/kubernetes/kubernetes/pull/83098 ,
could I ask that when will these functions be maintained ?
Will it be maintained forever and not deleted in the future? And is it okay if I assume that existing In-tree PVs will continue to be used in the future?  (Specs will remain as In-tree PVs and will not need to be modified, but will be converted by translate functions and will always be processed by CSI plugins forever in the future).

I would like to know what is the policy of SIG storage. Thank you very much.

/sig storage

**Comment by ziyi-xie** [comment]
@xing-yang Hi! Please forgive me for this sudden mention, and so sorry if I mention the wrong person. Could you tell me who should I ask to get some information about this issue?

**Comment by xing-yang** [comment]
> @xing-yang Hi! Please forgive me for this sudden mention, and so sorry if I mention the wrong person. Could you tell me who should I ask to get some information about this issue?

Yes, in-tree PVs do not need to be modified. They will be converted by translate functions and will always be processed by CSI plugins. Migrated in-tree PVs should keep working as before, but they won't get new CSI features such as VolumeSnapshots.

By the way, you should also look up the documentation for the CSI driver you are using. I assume each driver that goes through CSI migration should have documentation about it.

**Comment by ziyi-xie** [comment]
@xing-yang Thank you so much for your help! 
Just wanted to make sure I didn't misunderstand,
the in-tree format yaml file will **still be used in the future** even after the migration is over, 
and **will not be** left unprocessed or **deleted** in the future,
Is my understanding correct?

**Comment by xing-yang** [comment]
> @xing-yang Thank you so much for your help!
Just wanted to make sure I didn't misunderstand,
the in-tree format yaml file will still be used in the future even after the migration is over,
and will not be left unprocessed or deleted in the future,
Is my understanding correct?

@ziyi-xie Yes, you should be able to create/delete PVC the same way as before. Please see details in the following blog:
https://kubernetes.io/blog/2022/09/26/storage-in-tree-to-csi-migration-status-update-1.25/#quick-recap-what-is-csi-migration-and-why-migrate

**Comment by xing-yang** [comment]
Can this issue be closed now?

**Comment by ziyi-xie** [comment]
@xing-yang Thank you so much for your help! I want to make sure now that my clients and I don't have any further questions so could this issue be opened for a while longer? I'll close it as soon as I'm sure it's okay.

**Comment by xing-yang** [comment]
> @xing-yang Thank you so much for your help! I want to make sure now that my clients and I don't have any further questions so could this issue be opened for a while longer? I'll close it as soon as I'm sure it's okay and hope this doesn't cause you too much trouble.

No problem.

**Comment by ziyi-xie** [comment]
We have no further questions at this time, so I'm going to close this issue. Thank you so much for your help!
