### ISSUE TITLE
Pod restore failed after using checkpoint providede by kubelet.

### ISSUE THREAD

**Issue by github-jyq** [kubernetes/kubernetes#120906]
### What happened?

At first, I use checkpoint to get a checkpoint file:
`curl -sk -X POST  "https://localhost:10250/checkpoint/<namespace>/<pod_name>/<conatiner_name>" \
  --key /etc/kubernetes/pki/apiserver-kubelet-client.key \
  --cacert /etc/kubernetes/pki/ca.crt \
  --cert /etc/kubernetes/pki/apiserver-kubelet-client.crt`
And then I build image based on the `checkpoint.tar` file and push it to the image registry.
At last, I deploy the image as a new pod.
But the pod restore failed, `kubectl describe` could get such messages:
![image](https://github.com/kubernetes/kubernetes/assets/81799971/4a35c46b-3501-4661-9051-b5967d72657f)
It seems that the criu try to restore the pod according to the container_name `m` ,but ofcourse the container's path is using its `ID` instead `name` in the path mentioned above.
I think there may be some settings not being set correctly, because I have a node can restore pod, but I don't know what's the different between it and other machines.

### What did you expect to happen?

I want to live migrate a pod , but when I try to restore a pod, I meet problem above .

### How can we reproduce it (as minimally and precisely as possible)?

Thanks. Tell me what I should do to solver problem above!

### Kubernetes version

<details>

```console
$ kubectl version
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1
```

</details>

### Cloud provider

<details>
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
Linux master 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>
kubeadm
</details>

### Container runtime (CRI) and version (if applicable)

<details>
CRI-O 1.27.1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
I use CRIU 3.17.1 as the criu  of cri-o using to checkpoint and restore.
</details>

**Comment by tamilselvan1102** [comment]
you can confirm your setting by referring this blog 
https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/

**Comment by github-jyq** [comment]
> you can confirm your settings by referring this blog https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/

Thank you for your answer!
I have read this blog many times , and confirm my environment is right . The settings in this blog just said the basic need, and I think I have make them!
It is necessary to add that I have one node `Node1` can checkpoint and restore a container , but other nodes can only checkpoint a container but can't restore one . Meanwhile , a image built by the <checkpoint>.tar file from the nodes which can't restore container can be restored at  `Node1`. This tells me the checkpoint is correct at other nodes but restore is wrong.
I don't know why `Node1` can restore and why the other nodes can't do it.

**Comment by SergeyKanzhelev** [comment]
The restore functionality is not supported yet by kubernetes. If you are restoring using CRI-O you might need to file this issue in CRI-O repository

/cc @adrianreber 

Closing, please reopen if you believe it is a kubernetes issue

/close

**Comment by adrianreber** [comment]
@github-jyq Please report this at CRI-O as suggested. Also, CentOS 7 is probably too old. Try at least CentOS 8 or better 9.

**Comment by vd2892001** [comment]
Container Checkpointing with CRIU in Kubernetes:
Kubernetes version: 1.28
Cloud being used: (put bare-metal if not on a public cloud)
Installation method: Container Checkpointing with CRIU in Kubernetes
Host OS: ubuntu 22.04
CRI and version: CRI-O
criu : 4.0

enable_criu_support field in the CRI-O configuration file to true.

curl -sk -X POST “[https://localhost:10250/checkpoint/default/nginx/nginx”](https://localhost:10250/checkpoint/default/nginx/nginx%E2%80%9D)
–key /etc/kubernetes/pki/apiserver-kubelet-client.key
–cacert /etc/kubernetes/pki/ca.crt
–cert /etc/kubernetes/pki/apiserver-kubelet-client.crt

error
ls -l /var/lib/kubelet/checkpoints/
ls: cannot access ‘/var/lib/kubelet/checkpoints/’: No such file or directory

Why doesn’t the checkpoint file appear in the directory? What configuration is needed to make it appear in the directory? Please help
