### ISSUE TITLE
Name resolution failed for service with same namespace and service name with Type ExternalName.

### ISSUE THREAD

**Issue by pm-parthasarathi** [kubernetes/kubernetes#120922]
### What happened?

I have a namespace **datalake**.
In this namespace i have three service as follows.
Service Name: Service Type
1) trino type-clusterip
2) minio type clusterip
3) datalake type ExternalName pointing to minio service

when i do nslookup.

nslookup trino.datalake.svc.cluster.local (**Working**)
nslookup trino.datalake.svc                     (**Working**)
nslookup trino.datalake                           (**Not Working, resolved to minio service. Note namespace name is datalake and i have another service with same name datalake of type ExternalName **)

### What did you expect to happen?

nslookup trino.datalake
this should resolved to trino service in datalake namespace

### How can we reproduce it (as minimally and precisely as possible)?

Create one namespace(datalake) and service type ExternalName(datalake) in same name.
try nslookup anyname with namespace.
nslookup abc.datalake not working.

### Anything else we need to know?

I tried this in kubernetes version 1.21 working
but not working in 1.25.6

![image](https://github.com/kubernetes/kubernetes/assets/121949698/49d53300-7189-47b2-89e6-3236c5c7f992)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.12", GitCommit:"ba490f01df1945d0567348b271c79a2aece7f623", GitTreeState:"clean", BuildDate:"2023-07-19T12:23:43Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:26Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}


```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)
Linux dev-digixt-w06 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by pm-parthasarathi** [comment]
Please refer the screenshot for better clarification.

**Comment by HirazawaUi** [comment]
This issue is related to coredns version updates, perhaps you should create issue in the [coredns project](https://github.com/coredns/coredns/issues) to look for help

**Comment by thockin** [comment]
I think you have fallen into a poorly defined part of the DNS schema.

First, let's repro:

```
$ k -n datalake create service clusterip trino --tcp=80
service/trino created

$ k -n datalake create service clusterip minio --tcp=80
service/minio created

$ k -n datalake create service externalname datalake --external-name=minio.datalake.svc.cluster.local
service/datalake created

$ k -n datalake get svc
NAME       TYPE           CLUSTER-IP    EXTERNAL-IP                        PORT(S)   AGE
datalake   ExternalName   <none>        minio.datalake.svc.cluster.local   <none>    5m54s
minio      ClusterIP      10.0.142.29   <none>                             80/TCP    6m46s
trino      ClusterIP      10.0.153.81   <none>                             80/TCP    6m52s

$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=busybox cat /etc/resolv.conf
If you don't see a command prompt, try pressing enter.
warning: couldn't attach to pod/test-17283, falling back to streaming logs: unable to upgrade connection: container test-17283 not found in pod test-17283_datalake
search datalake.svc.cluster.local svc.cluster.local cluster.local us-central1-b.c.thockin-dev.internal c.thockin-dev.internal google.internal
nameserver 10.0.0.10
options ndots:5

$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +short trino.datalake.svc.cluster.local
10.0.153.81

$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +short trino.datalake.svc
10.0.153.81

$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +short trino.datalake
minio.datalake.svc.cluster.local.
10.0.142.29
```

So you can see this is reproducible.  For completeness, the shortes name works:

```
$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +short trino
10.0.153.81
```

And the "problem" name works from another namespace:

```
$ k -n default run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +short trino.datalake
10.0.153.81
```

So the issue is that WITHIN THAT NAMESPACE, your query is ambiguous (sorry!)

By default, all names are subject to search-path expansion.  Unless you configure otherwise, that means:
1) `<query>.<this-namespace>.svc.<zone>`
2) `<query>.svc.<zone>`
3) `<query>.<zone>`
4) `<query>`

You seem to want `trino.datalake` to skip (1) and hit (2), but I think it will actually hit (1), because "<host>.<svc>.<ns>.svc.<suffix>" is a valid query, and seems to be matching

```
$ k -n datalake run "test-$RANDOM" -ti --restart=Never --image=thockin/dnsutils -- dig +search +showsearch +nocomments trino.datalake

; <<>> DiG 9.18.19-1~deb12u1-Debian <<>> +search +showsearch +nocomments trino.datalake
;; global options: +cmd
;trino.datalake.datalake.svc.cluster.local. IN A
trino.datalake.datalake.svc.cluster.local. 30 IN CNAME minio.datalake.svc.cluster.local.
minio.datalake.svc.cluster.local. 30 IN	A	10.0.142.29
;; Query time: 1 msec
;; SERVER: 10.0.0.10#53(10.0.0.10) (UDP)
;; WHEN: Thu Feb 01 19:47:22 UTC 2024
;; MSG SIZE  rcvd: 217
```

Note the DNS question is "trino.datalake.datalake.svc.cluster.local." which is being satisfied by the CNAME (external-name) for datalake.datalake.svc.cluster.local.

But why?  Let's look at the spec: https://github.com/kubernetes/dns/blob/master/docs/specification.md#25---records-for-external-name-services

It actually only specifies a CNAME record for  `<service>.<ns>.svc.<zone>.`  To my eyes, that SHOULD NOT match, but CNAMEs have sometimes surprising semantics.

@chrisohaver - can you shed some light, maybe?

**Comment by chrisohaver** [comment]
This errant behavior was fixed in https://github.com/coredns/coredns/pull/6162 and should be in the latest coredns release 1.11.1

**Comment by thockin** [comment]
YAY!
