### ISSUE TITLE
Undocumented enableServiceLinks behaviour

### ISSUE THREAD

**Issue by davidshen84** [kubernetes/kubernetes#120953]
### What happened?

In a pod spec, if `enableServiceLinks == false`, no services' information should be injected into the pods. That's according to the [document][1]. However, according to [the code][2], information on the services in the *master service* namespace, `kube-system` by default, is always injected.

> We always want to add environment variabled for master services

The code has this comment without explaining why we should always do this.

[1]: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#pod-v1-core
[2]: https://github.com/kubernetes/kubernetes/blob/9050c510e640f325d008792a517fe85808b34150/pkg/kubelet/kubelet_pods.go#L523

### What did you expect to happen?

When `enableServiceLinks == false` on a pod, no services' information should be injected into the pod.

### How can we reproduce it (as minimally and precisely as possible)?

Create a few pods with `enableServiceLinks == false` and associated service, then observe if the services' information is injected into the pods.

### Kubernetes version

<details>
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1
</details>

### Cloud provider

<details>
N/A
</details>

### OS version

<details>
Linux desktop-0xivd7b-wsl 5.15.123.1-microsoft-standard-WSL2 #6 SMP Fri Sep 8 22:07:13 AEST 2023 x86_64 x86_64 x86_64 GNU/Linux
</details>

### Install tools

<details>
k3s
</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
N/A
</details>

**Comment by tamilselvan1102** [comment]
As per the [code](https://github.com/kubernetes/kubernetes/blob/9050c510e640f325d008792a517fe85808b34150/pkg/kubelet/kubelet_pods.go#L531C8-L531C8), in case of pod namespace &&  pod spec enableServiceLinks ==true then NS services is injected into pod's environment variables. 
The same is documented [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.28/#pod-v1-core).
i didn't find any mismatch

**Comment by davidshen84** [comment]
@tamilselvan1102 

Excuse me. I am talking about `enableServiceLinks == false` cases. I think your reply is not relevant to my report.

**Comment by tamilselvan1102** [comment]
All the maser services are injected as default and pod's specific services are injected based on enableServiceLinks flag.

**Comment by davidshen84** [comment]
> EnableServiceLinks indicates whether information about services should be injected into pod's environment variables, matching the syntax of Docker links. Optional: Defaults to true.

This is the only line I can find that describes the function of the `enableServiceLinks` flag.

I looked back and forth but could not find any text describing anything about services in the master namespace.

If people need to read between the lines to get that information, I think we can make the document clearer.
