### ISSUE TITLE
Flaky e2e node conformance tests with enabled Evented PLEG featuregate

### ISSUE THREAD

**Issue by sairameshv** [kubernetes/kubernetes#120941]
### Which jobs are flaking?

Presubmit job - https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml#L1030 
Job History: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-crio-cgrpv1-evented-pleg-e2e 

The periodic job in the test grid is found to be flaky as well.
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-evented-pleg 

### Which tests are flaking?

Following are some of the tests that are found to be flaky
```
E2eNode Suite.[It] [sig-node] ContainerLogPath [NodeConformance] Pod with a container printed log to stdout should print log to correct cri log path
E2eNode Suite.[It] [sig-node] Container Lifecycle Hook when create a pod with lifecycle hook should execute poststart https hook properly [MinimumKubeletVersion:1.23] [NodeConformance]
E2eNode Suite.[It] [sig-node] MirrorPod when create a mirror pod without changes should successfully recreate when file is removed and recreated [NodeConformance]
E2eNode Suite.[It] [sig-node] Probing container should *not* be restarted with a /healthz http liveness probe [NodeConformance] [Conformance]
```

### Since when has it been flaking?

The flakiness is observed almost since the job's inception
https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-evented-pleg 

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-evented-pleg

### Reason for failure (if possible)

Pod status/cache seems to be not getting updated correctly between the two immediate `SyncLoop ADD/UPDATE/RECONCILE` calls of a pod and hence resulting in the creation of duplicate containers within the same pod.

Also, the `GetNewerThan()` [call](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/pod_workers.go#L1255) seems to be non-blocking when the Evented PLEG is enabled and hence resulting in the creation of duplicate containers when there are immediate multiple `SyncLoop ADD/UPDATE/RECONCILE` calls before the pod status/cache is updated.

### Relevant SIG(s)

/sig node

**Comment by alam0rt** [comment]
We are experiencing this issue https://github.com/kubernetes/kubernetes/issues/121003

Similarly, we are using cgroup v1 also.
