### ISSUE TITLE
Ability to validate kubectl exec/attach requests in the Admission Controller based on requestor source IP address

### ISSUE THREAD

**Issue by Kushwanth7** [kubernetes/kubernetes#121014]
### What would you like to be added?

Request : Expose the source IP address in the AdmissionReview Object.

Context :

We would like to have Admission Controller make decisions on a particular exec/attach request depending upon where the request originated from i.e the client source IP address.

The source IP address is not available in the AdmissionReview object so it is currently not possible to do validation on IP address at Admission Control.

The requestor's IP address is available in the K8S API server (the api server audit logs contain the IP address information) however this information is not passed along to Admission Controller.

### Why is this needed?

Due to a security policy, we want users to interact (exec, attach) with their K8S workloads only from certain machines and dis-allow all interactions from all other machines.

**Comment by stlaz** [comment]
triage: this is planned to be discussed on the next sig-auth meeting ([sig-auth bi-weekly agenda](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit))

**Comment by liggitt** [comment]
Discussed [January 3rd, 2024 in sig-auth](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit?tab=t.0#bookmark=id.adb1a24qvp5k)

Notes from that meeting:
* This sounds a lot like https://github.com/kubernetes/enhancements/pull/2843, last discussed almost exactly [one year ago](https://docs.google.com/document/d/1woLGRoONE3EBVx-wTb4pvp4CI7tmLZ6lS26VTbosLKM/edit#heading=h.120ek8ullaul) (Jan 4, 2023)
* Considerations that make this non-trivial to add raised when discussed in 2023
   * reliability of source IP across all deployments (not a singular IP if passing through proxies, no standard way to propagate trusted network path information in headers, just lots of conventions which may or may not be honored/protected by proxies)
   * impact on additional highly-variable metadata on authn / authz caches
   * opening the door to a parade of requests for "just one more request attribute" (arbitrary headers, tls level, authentication method, protocol version, proxy IP, etc, etc)
