### ISSUE TITLE
Should the completed pods be evicted?

### ISSUE THREAD

**Issue by AxeZhan** [kubernetes/kubernetes#121052]
### What would you like to be added?

During using the kubernetes, I found a case:
1. Create a pod that will finally complete.(may be controlled by a job). 
2. Suppose this pod is scheduled on to node1 and completed. Taint node1 with `NoExecute`.
3. The competed pod is **evicted** by the taint manager.

 The completed pods do not occupy node resources, so is it necessary to evict it?

### Why is this needed?

Users may need some informations of this completed pod, and if it's evicted, they will have to create a same pod again.

**Comment by charles-chenzz** [comment]
> The completed pods do not occupy node resources, so is it necessary to evict it?

the pod or (jobs) is evited due to it doesn't tolerate the taints if I understand correctly. so if a pod doesn't tolerate the taints it should be evited(or we can call it leave the room)

**Comment by pacoxu** [comment]
This seems not to be explained/described clearly in the official doc.
- https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-based-evictions At least, we should update the doc if we will keep the behavior.

> It is recommended to set ttlSecondsAfterFinished field because unmanaged jobs (Jobs that you created directly, and not indirectly through other workload APIs such as CronJob) have a default deletion policy of orphanDependents causing Pods created by an unmanaged Job to be left around after that Job is fully deleted.

BTW, IMO completed pod should have a GC ttl like ttlSecondsAfterFinished for the pod. The quota is from https://kubernetes.io/docs/concepts/workloads/controllers/job/. 

And completed pod will still use some resources, at least disk. When a node is in disk pressure, it still may be evicted as well.
