### ISSUE TITLE
how to get netnspath of container after k8s 1.24?

### ISSUE THREAD

**Issue by lelvisl** [kubernetes/kubernetes#121035]
how to get netnspath of container after k8s 1.24?
(inside of this codebase)

in 1.23 was 
```go
func (ds *dockerService) GetNetNS(podSandboxID string) (string, error) {
```

as i understood, i must get netns from CRI, but in SandboxStatus i see only netns mode, there is no netns path.

**Comment by stepanovmm1992** [comment]
I have the same problem.
I see only netns mode and cant get netns path.

**Comment by uablrek** [comment]
Here is a way to get the netns from a `k8s.io/api/core/v1.Pod` object. Please note that this just _a_ way I have used, not best practice or something! It get's the pid and returns "/proc/pid/ns/net"

[netns.go.txt](https://github.com/kubernetes/kubernetes/files/13043465/netns.go.txt)

**Comment by lelvisl** [comment]
@MikeZappa87 thanks for your answer!

I have problem with kubelet healthchecks - pod ip not available from host network ns on my cni (kube-ovn). 
Also i think, that tcp/http check with switchins netns to pod netns will be more correct. 

And now i try to make my local patch for switching netns on tcp/http prober.

**Comment by aojea** [comment]
> Here is a way to get the netns from a `k8s.io/api/core/v1.Pod` object. Please note that this just _a_ way I have used, not best practice or something! It get's the pid and returns "/proc/pid/ns/net"
> 
> [netns.go.txt](https://github.com/kubernetes/kubernetes/files/13043465/netns.go.txt)

Really cool Lars

> Also i think, that tcp/http check with switchins netns to pod netns will be more correct.

See https://github.com/kubernetes/kubernetes/issues/102613 , the problem is that breaks compatibility 

> I have problem with kubelet healthchecks - pod ip not available from host network ns on my cni (kube-ovn

If kubelet fails to get to that ip so others apps in the host, looks like a bug

I'm going to close as it seems there is nothing else to do here

/Close

**Comment by uablrek** [comment]
> I am working with containerd to expose the network namespace path in a more programmatic way.

@MikeZappa87 I made a comment on this in https://kubernetes.slack.com/archives/CAZH62UR1/p1708408002227669

A "best practice" way must work for `crio` and `containerd`, and other CRI-plugins (in a perfect world).
