### ISSUE TITLE
Make cAdvisor monitor more cgroups

### ISSUE THREAD

**Issue by machine424** [kubernetes/kubernetes#121081]
### What would you like to be added?

Since https://github.com/kubernetes/kubernetes/pull/72787, cAdvisor only monitors some predefined cgroups, while this is considered an optimization, users lost access to metrics of some special cgroups that are created for certain setups.

To spare users the necessity to roll out their own metrics collectors for that, it'd great to be able to add more cgroups for cAdvisor to monitor.
 
(via a kubelet config e.g. to be able to customize cAdvisor's `--raw_cgroup_prefix_whitelist`)

### Why is this needed?

See above.

**Comment by pranav-pandey0804** [comment]
Hi @machine424 
This idea to let us tweak cAdvisor and choose which cgroups it keeps an eye on is pretty cool. 
It means we can adapt it to our specific setups without diving into DIY metrics solutions. It's a great way to get more detailed insights into our resources. 

Just a heads up though, we'll need to be careful with how we set things up to keep it smooth and secure. Looking forward to seeing this in action!
