### ISSUE TITLE
kube-proxy SNAT policy for nodeport should only be performed on traffic originating from the pod on the current host

### ISSUE THREAD

**Issue by lidajia** [kubernetes/kubernetes#121066]
### What happened?

Pod A runs on host node-1, where there are multiple network cards (eth0:10.10.11.1, eth1:192.168.10.11). Pod A is associated with service A, which is a nodeport type and provides a nodeport 30001; Pod B runs on host node-2, and accesses Pod A through 192.168.10.11:30001. At this time, the source IP obtained inside Pod A is the IP of eth0 on node-1, and the expected IP is eth1.

### What did you expect to happen?

The source IP should be displayed as the IP of the network card through which the traffic actually passes. Some gateway applications require the setting of an x-forwarded for request header, which may be used in security policies. When multiple network cards exist, it is necessary to set the x-forwarded for to the correct business network card IP address.

### How can we reproduce it (as minimally and precisely as possible)?

create nginx pod and config x-forward-for header，access nginx using pod host ip and service nodeport。

### Anything else we need to know?

kube-proxy add this rule for nodeport traffic:
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -j MASQUERADE

MASQUERADE rule will change the source ip to the network card with the highest priority on the host.

### Kubernetes version

Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:38:19Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

k8s

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
CNI Plugin is calico
</details>

**Comment by cyclinder** [comment]
Can you use the following command to get the debug information?

on host node-2:

- *ip a show*
- *ip r get <podA_IP>*

**Comment by cyclinder** [comment]
From kernel code: https://github.com/torvalds/linux/blob/94f6f0550c625fab1f373bb86a6669b45e9748b3/net/ipv4/devinet.c#L1345

netfilter doesn't like an address that is secondary, and like an address whose scope is global. Can you use `ip a` show the interface's address on your node?

**Comment by lidajia** [comment]
![Uploading aaa.png…]()
@uablrek

**Comment by utkarsh-singh1** [comment]
@lidajia, This does not seems to be uploaded correctly, it redirects to this issue.

**Comment by uablrek** [comment]
I have tried some different CNI-plugins, and the only one that fits the description in this issue is `Calico`. Others like: flannel, cilium, antrea and kindnet don't set a node-ip as src. The others sets an address from the ClusterCIDR range (or the POD-address range configured to the CNI-plugin).

@lidajia Please specify the CNI-plugin in future issues. For network problem it is usually important.

IMO this is not a bug in K8s, and it is CNI-dependent.

**Comment by lidajia** [comment]
yes， the CNI-plugins is calico

**Comment by lidajia** [comment]
> @lidajia, This does not seems to be uploaded correctly, it redirects to this issue.

thanks, corrected it
