### ISSUE TITLE
kube-proxy constantly restarts with fatal: bad g in signal handler post 1.25 upgrade

### ISSUE THREAD

**Issue by saiharshitachava** [kubernetes/kubernetes#121033]
### What happened?

We have recently upgraded our cluster to 1.25.9 and the kube-proxy constantly restarts with fatal: bad g in signal handler 

We tried enabling the debug and we couldnt find any common ground on where its happening..Its happening on all nodes in cluster of 150 nodes except for GPU nodes 

We checked where the bad signal has been coming from but could find a common place..it randomly apperas while syncing ip tables or initializing kube proxy 

There are huge number of restarts on bigger clusters compared to the small ones

Note that we have used upstream kubernetes kube-proxy image in cluster and were able to replicate the issue

lter -m conntrack --ctstate NEW -m comment --comment kubernetes service portals -j KUBE-SERVICES]
I1006 18:05:16.490757       1 iptables.go:467] running iptables: iptables [-w 5 -W 100000 -N KUBE-FORWARD -t filter]
fatal: bad g in signal handler
I1006 18:05:16.502675       1 iptables.go:467] running iptables: iptables [-w 5 -W 100000 -C FORWARD -t filter -m comment --comment kubernetes forwarding rules -j KUBE-FORWARD]
I1006 18:05:16.516169       1 iptables.go:467] running iptables: iptables [-w 5 -W 100000 -N KUBE-PROXY-FIREWALL -t filter]

### What did you expect to happen?

kube-proxy to be healthy without restarts

### How can we reproduce it (as minimally and precisely as possible)?

We created a bare minimum EKS clusters and started creating services like  ingress controller, istio in the cluster and the restarts happen

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
EKS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by saiharshitachava** [comment]
Do we think this sync proxy rules part broke this ?
https://github.com/kubernetes/kubernetes/pull/110266

The next part of this PR was a milestone in 1.26 code to sync only needed chains 
https://github.com/kubernetes/kubernetes/pull/110268

I know its not recommended to have 1.26 kube-proxy in 1.25 clusters but we are not able to replicate the issue on the cluster with 1.26 kube-proxy image

**Comment by saiharshitachava** [comment]
tagging @danwinship to see if this is a real issue since he is the contributor of both the PR's
Thanks in advance

**Comment by wettowelreactor** [comment]
@saiharshitachava is this still an open issue? I believe you may have traced this back to a third-party vendor.

**Comment by jdn5126** [comment]
@wettowelreactor I worked on this case, and the error was traced to an issue in Dynatrace, so feel free to close this

**Comment by elansurian** [comment]
@jdn5126 Any idea what could be the issue with dynatrace that causing kube proxy restarts.. we are facing same issues
