### ISSUE TITLE
kube-proxy ipvs: "Failed to add IPVS service" err="no such file or directory"

### ISSUE THREAD

**Issue by chymy** [kubernetes/kubernetes#121042]
### What happened?

Network is disconnected and then restored, kube-proxy log errs:
```
E1007 13:57:26.145807       1 proxier.go:1242] "Failed to sync service" err="no such file or directory" service="123.123.252.197:8989/TCP"
E1007 13:57:26.145840       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="zy/aiolcm-service-use"
E1007 13:57:26.145875       1 proxier.go:1593] "Failed to sync service" err="no such file or directory" service="194.246.5.29:31134/TCP"
E1007 13:57:26.145904       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="kube-system/metrics-server"
E1007 13:57:26.145924       1 proxier.go:1242] "Failed to sync service" err="no such file or directory" service="123.123.47.233:443/TCP"
E1007 13:57:26.145952       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="cnf/sc-gw-0-0-1:dualhttpsgw"
E1007 13:57:26.162009       1 proxier.go:1672] "Failed to get ipvs service" err="could not get IPVS services: no such file or directory"
```
As a result, the K8S service IP cannot be added to kube-ipvs0

I don't know which file or directory `no such file or directory` refers to,

https://github.com/kubernetes/kubernetes/blob/c92036820499fedefec0f847e2054d824aea6cd1/pkg/util/ipvs/ipvs_linux.go#L67
returned the "no such file or directory" error message

### What did you expect to happen?

no errs

### How can we reproduce it (as minimally and precisely as possible)?

Cloud disk network is disconnected and then restore

### Kubernetes version

<details>

```console
$ kubectl version
1.22.3
# paste output here
```

</details>

### Cloud provider

<details>
no
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by cyclinder** [comment]
It seems your disk is broken, Can you manually add a virtual service using the `ipvsadm` command?

**Comment by chymy** [comment]
But this situation also occurs when I restart the virtual machine. Cloud disks are only used by business pods.
kube-proxy.yaml:
```yaml

apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-proxy
  name: kube-proxy
  namespace: kube-system
spec:
  containers:
  - command:
    - /usr/local/bin/kube-proxy
    - --log-file=/var/log/k8s/kube-proxy.klog
    - --v=0
    - --kubeconfig=/etc/kubernetes/proxy.kubeconfig
    - --hostname-override=192.168.1.15
    - --proxy-mode=ipvs
    - --healthz-bind-address=127.0.0.1
    - --bind-address=193.170.0.243
    - --feature-gates=IPv6DualStack=true
    - --cluster-cidr=192.169.0.0/16,12ab::/48
    - --nodeport-addresses=192.168.0.0/22
    - --logtostderr=false
    - --alsologtostderr=false
    image: kube-proxy:v1.22.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10256
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-proxy
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 0
        memory: 100Mi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/localtime
      name: local-time
      readOnly: true
    - mountPath: /etc/kubernetes/certs
      name: certs
      readOnly: true
    - mountPath: /var/log/k8s
      name: log-dir
    - mountPath: /etc/kubernetes/proxy.kubeconfig
      name: kubeconfig
      readOnly: true
    - mountPath: /run/xtables.lock
      name: iptableslock
      readOnly: false
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/localtime
      type: File
    name: local-time
  - hostPath:
      path: /etc/kubernetes/certs
      type: Directory
    name: certs
  - hostPath:
      path: /var/log/k8s
      type: Directory
    name: log-dir
  - hostPath:
      path: /etc/kubernetes/proxy.kubeconfig
      type: File
    name: kubeconfig
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: iptableslock
  - hostPath:
      path: /lib/modules
      type: ""
    name: lib-modules


```

**Comment by chymy** [comment]
When restarting the proxy, it will work normally

**Comment by uablrek** [comment]
What is "Cloud disk network"?

Is it a network for network file-systems?

**Comment by chymy** [comment]
sorry.
for network file-systems

**Comment by chymy** [comment]
debug log:
```
syscall.Errno(-error) err: no such file or directory
```

https://github.com/moby/ipvs/blob/fe22ac585b3e22a969cbde61addd99ecd93ab22c/netlink_linux.go#L239-L245

**Comment by uablrek** [comment]
IMO this is a legit bug. Kube-proxy enters a state where is can't recover and stays there. The reaction should be to terminate, i.e. crash-and-restart. As mentioned in https://github.com/kubernetes/kubernetes/issues/121042#issuecomment-1754143025:

> When restarting the proxy, it will work normally

However, to crash `kube-proxy` is a drastic measure and this must be investigated.

/triage accepted

**Comment by chymy** [comment]
When I restart the virtual machine, this issue occasionally recurs, continuously print the following logs:
```
E1007 13:57:26.145807       1 proxier.go:1242] "Failed to sync service" err="no such file or directory" service="123.123.252.197:8989/TCP"
E1007 13:57:26.145840       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="zy/aiolcm-service-use"
E1007 13:57:26.145875       1 proxier.go:1593] "Failed to sync service" err="no such file or directory" service="194.246.5.29:31134/TCP"
E1007 13:57:26.145904       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="kube-system/metrics-server"
E1007 13:57:26.145924       1 proxier.go:1242] "Failed to sync service" err="no such file or directory" service="123.123.47.233:443/TCP"
E1007 13:57:26.145952       1 proxier.go:2016] "Failed to add IPVS service" err="no such file or directory" svcName="cnf/sc-gw-0-0-1:dualhttpsgw"
E1007 13:57:26.162009       1 proxier.go:1672] "Failed to get ipvs service" err="could not get IPVS services: no such file or directory"
```
But the `kube-proxy` doesn't seem to crash.

**Comment by uablrek** [comment]
> But the kube-proxy doesn't seem to crash

No, and that's the bug. But _if_ we crash, it may have other implications, hence the investigation.

And [moby/ipvs seem un-maintained](https://github.com/moby/ipvs/issues/27#issuecomment-1411505338).

**Comment by chymy** [comment]
> No, and that's the bug. But _if_ we crash, it may have other implications, hence the investigation.
> 
> And [moby/ipvs seem un-maintained](https://github.com/moby/ipvs/issues/27#issuecomment-1411505338).

Thanks. I will not reproduce this issue using alpine: 3.14.7 as the base image, but I can reproduce it using alpine: 3.17.5

**Comment by lojies** [comment]
> > But the kube-proxy doesn't seem to crash
> 
> No, and that's the bug. But _if_ we crash, it may have other implications, hence the investigation.
> 
> And [moby/ipvs seem un-maintained](https://github.com/moby/ipvs/issues/27#issuecomment-1411505338).

if https://github.com/moby/ipvs/issues/27#issuecomment-1411505338 un-maintained and there is a bug,how should we do?

**Comment by lojies** [comment]
@aojea @bowei @thockin @freehan, can someone take a look at this issue,thanks.

**Comment by uablrek** [comment]
The bug is likely not in moby in this case, but in the way the error is handled in kube-proxy. The bug in [my issue](https://github.com/moby/ipvs/issues/27) has a work-around (open-write-read-checkResult). IMO we can live with the un-maintained moby until the nft proxier comes around.

/cc @aroradaman

**Comment by shaneutt** [comment]
Sounds good, thank you for that update. :bow: 

I think given your thoughts, and a generally similar sentiment on our last call, we should close this out for now as unplanned:

/close

That said: anyone who's reading this and is interested in seeing this move forward please note that closed doesn't mean "never to be fixed", more like "we need someone who's willing to step forward and drive the issue forward" so if you are interested in doing that, feel free to let us know here in the comments and/or join us and talk to us about it at an upcoming SIG Network meeting and we will support you.
