### ISSUE TITLE
DRA: create an event to ResourceClaim or ResourceClass when their parameters fail validation in resource driver

### ISSUE THREAD

**Issue by byako** [kubernetes/kubernetes#121063]
### What happened?

When ResourceClaimParameters or ResourceClassParameters fail validation in resource driver during PodSchedulingContext sync loop, the error is visible only in the events of the PodSchedulingContext.

### What did you expect to happen?

The error should be visible on the object that fails validation as well, ResourceClaim or ResourceClass respectively.

### How can we reproduce it (as minimally and precisely as possible)?

Creating ResourceClaim with unsupported parameters' `Spec` values or unsupported `parametersRef`

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ndixita** [comment]
KEP: https://github.com/kubernetes/enhancements/issues/3063
