### ISSUE TITLE
pull-kubernetes-node-e2e-containerd continuously failed

### ISSUE THREAD

**Issue by charles-chenzz** [kubernetes/kubernetes#121047]
### Which jobs are failing?

pull-kubernetes-node-e2e-containerd

### Which tests are failing?

see 
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-node-e2e-containerd
https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e

### Since when has it been failing?

Oct 07 20:25:00Oct 07 2023, 20:25:00 UTC+0800

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#pull-node-e2e

### Relevant SIG(s)

/sig node

**Comment by charles-chenzz** [comment]
still fails after another retry, so I think we can call it continuously failed
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121044/pull-kubernetes-node-e2e-containerd/1710823989007355904

**Comment by mmiranda96** [comment]
Looks like this is fixed now.
/close
