### ISSUE TITLE
Deployment of version v1 cannot be handled by deployment.

### ISSUE THREAD

**Issue by albertsuki265** [kubernetes/kubernetes#121004]
I am new in Kubernetes  and trying to create deplyment using the below YAML FIle.
When i run command kubectl apply -f deployment_myapp.yaml, It is throwing me error and it doesnot create deployment.

apiVersion: apps/v1
kind: deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLebels:
       app: myapp
  template:
    metadata:
      lebels:
        app: myapp
    spec:
     containers:
     - name: myapp
       image: mongo
       ports:
       - containerPort: 27017
       env:
       - name: MONGO_INITDB_ROOT_USERNAE
         valueFrom:
           secretKeyref:
             name: myapp-secret
             key: myapp-root-username
       - name: MONGO_INITDB_ROOT_PASS
         valueFrom:
          secretKeyref:
            name: myapp-secret
            key: myapp-root-password

why i am geting such error. You help is welcome

**Comment by niranjandarshann** [comment]
@albertsuki265 There are Error in writing the Yaml file. It has been seen here that you had used the kind `deployment` which is in lower Where as it should be capitalize like 
`kind: Deployment`
thats why i think you are facing the issue and the deployment is not  creating as expected.
Try to do this correction and let disscuss id you again face the issue.

**Comment by albertsuki265** [comment]
> @albertsuki265 : GitHub is not the right place for support requests.
> 
> If you're primarily looking for help, you could ask on [Server Fault](https://serverfault.com/questions/tagged/kubernetes) or using [Microsoft Community](https://answers.microsoft.com/).
> 
> You can also post your question on the [Kubernetes Slack](http://slack.k8s.io/) or the [Discuss Kubernetes](https://discuss.kubernetes.io/) forum.
> 
> If you'd like to help us improve the documentation, please try to file an actionable report about where the shortcoming is (if you want to suggest more than one improvement, please file a new issue for each one).

Yes @niranjandarshann  i understand it but i hadnt received any response there from a long while thats why i wrote here. But hoping for help.

**Comment by albertsuki265** [comment]
> @albertsuki265 There are Error in writing the Yaml file. It has been seen here that you had used the kind `deployment` which is in lower Where as it should be capitalize like `kind: Deployment` thats why i think you are facing the issue and the deployment is not creating as expected. Try to do this correction and let disscuss if you again face the issue.

again triggering error. @niranjandarshann

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
