### ISSUE TITLE
Why Are Pods in the UnexpectedAdmissionError State Not Recycled?

### ISSUE THREAD

**Issue by kangzhiqin** [kubernetes/kubernetes#121061]
### What would you like to be added?

My pod is in the **UnexpectedAdmissionError** state after the system is started abnormally. After the system is restored, the pod is started normally. However, pods in the **UnexpectedAdmissionError** state are residual.

![image](https://github.com/kubernetes/kubernetes/assets/143382668/a5c2153f-502c-49e6-afc9-a8b01355a368)

### Why is this needed?

Would you like to ask if pods in the **UnexpectedAdmissionError** state will not be reclaimed by K8S?

**Comment by neolit123** [comment]
/sig auth node
?

**Comment by kangzhiqin** [comment]
> /sig auth node ?

Why the UnexpectedAdmissionError State Is Not Deleted?

**Comment by swatisehgal** [comment]
> Would you like to ask if pods in the UnexpectedAdmissionError state will not be reclaimed by K8S?

I have seen this behavior as well. A workaround that I found was to manually delete such pods from the cluster with a command like below:
`kubectl delete pods --field-selector status.phase=Failed -n <Namespace>`

It would certainly be a nice improvement for such pods to be are reclaimed by Kubernetes automatically. At some stage I was under that the impression that the resolution of https://github.com/kubernetes/kubernetes/issues/118472 would allow us to fix this problem but I never managed to verify if that is the case or not.

**Comment by ffromani** [comment]
I recalled somehow that pod in terminal phase must be reclaimed explicitly (either by humans or programs) and I finally found the k8s docs references: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection

**Comment by kangzhiqin** [comment]
> > Would you like to ask if pods in the UnexpectedAdmissionError state will not be reclaimed by K8S?
> 
> I have seen this behavior as well. A workaround that I found was to manually delete such pods from the cluster with a command like below: `kubectl delete pods --field-selector status.phase=Failed -n <Namespace>`
> 
> It would certainly be a nice improvement for such pods to be are reclaimed by Kubernetes automatically. At some stage I was under that the impression that the resolution of #118472 would allow us to fix this problem but I never managed to verify if that is the case or not.

**Comment by kangzhiqin** [comment]
> I recalled somehow that pod in terminal phase must be reclaimed explicitly (either by humans or programs) and I finally found the k8s docs references: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection

This document is very useful, thank you, and I have a new question: What are the general reasons for pods in the UnexpectedAdmissionError state?

**Comment by kangzhiqin** [comment]
> > Would you like to ask if pods in the UnexpectedAdmissionError state will not be reclaimed by K8S?
> 
> I have seen this behavior as well. A workaround that I found was to manually delete such pods from the cluster with a command like below: `kubectl delete pods --field-selector status.phase=Failed -n <Namespace>`
> 
> It would certainly be a nice improvement for such pods to be are reclaimed by Kubernetes automatically. At some stage I was under that the impression that the resolution of #118472 would allow us to fix this problem but I never managed to verify if that is the case or not.

That is, this state can be automatically reclaimed only when the pod in the **terminated** state reaches the threshold.

**Comment by ffromani** [comment]
> > I recalled somehow that pod in terminal phase must be reclaimed explicitly (either by humans or programs) and I finally found the k8s docs references: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection
> 
> This document is very useful, thank you, and I have a new question: What are the general reasons for pods in the UnexpectedAdmissionError state?

There's not a well defined set of conditions because this is a generic kubelet error which can arise for a number of reason. One of the most common source of this error if when the kubelet cannot actually perform a resource allocation.
Sometimes the scheduler, and the rest of the cluster in general, have a view of node allocation state which is not completely accurate, so a node is selected to run the workload based on that view. But the kubelet is the final arbiter which actually performs the allocation, so if the node state doesn't match the expected cluster state, allocation may fail, leading to this state

**Comment by guoliangmiao** [comment]
May I ask if this issue has been fixed? Or is there any solution to avoid this problem?

**Comment by ffromani** [comment]
hi, no code change implemented. The suggested workaround is https://github.com/kubernetes/kubernetes/issues/121061#issuecomment-1752671983
