### ISSUE TITLE
Schedule a CronJob on a final day of the month

### ISSUE THREAD

**Issue by narqo** [kubernetes/kubernetes#121088]
### What would you like to be added?

As of today, Kubernetes doesn't allow scheduling a CronJob on the last day of the month. After searching around the Internet, this seems to be popular problem, fixed in some implementations of cron syntax [via `L` special character][1] in the day-of-month position (e.g. [AWS's EventBridge](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) is among parties, who support it natively).

One popular way to overcome this involves a wrapper script, that runs on the last four days of each month (days 28-31), and checks the exact day, before executing the command. While works, this makes the original intent obscure, and is prone to human errors.

Note that Kubernetes relies on `github.com/robfig/cron/v3` in parsing the CronJob's schedule. The feature to support the "L" in the library was proposed in https://github.com/robfig/cron/pull/325 (in 2020) but it seems that the library was abandoned by the maintainer. As part of this feature request, I also suggest exploring if having the parts of k8s's API (part of the CronJob spec), to be one-to-one dependent on the capabilities of a (potentially unmaintained) library, is something that needs an attention.

[1]: https://en.wikipedia.org/wiki/Cron#Cron_expression

### Why is this needed?

Running periodic tasks on the last day of the month is common a problem in different sorts of enterprise applications.

**Comment by sftim** [comment]
If we accept this, we should watch out for backwards compatibility.

We might want to support scheduling (in the cron sense) using the new format for at least one Kubernetes version before we stabilize the ability to have the new format pass admission time checks. Otherwise, someone might be part way through an upgrade, or downgrade k-c-m, and end up with a schedule that can't run.

I think the new feature would need a [KEP](https://github.com/kubernetes/enhancements/).

**Comment by miketonks-form3** [comment]
I'm also interested in this issue.

I'd add that Kubernetes also doesn't currently allow scheduling using other Non-standard but widely recognized conventions, see [wikipedia](https://en.wikipedia.org/wiki/Cron#Non-standard_characters) 

I'm particularly interested in Hash (#) syntax

> Hash (#)
>    '#' is allowed for the day-of-week field, and must be followed by a number between one and five. It allows specifying constructs such as "the second Friday" of a given month.[[20]](https://en.wikipedia.org/wiki/Cron#cite_note-21) For example, entering "5#3" in the day-of-week field corresponds to the third Friday of every month.

**Comment by ybstaked** [comment]
Any update on this?
