### ISSUE TITLE
[Failing Test] containerd-e2e-ubuntu has started failing outright since October 10th.

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#121115]
### Which jobs are failing?

The entire test case fails to start up.

### Which tests are failing?

https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu

### Since when has it been failing?

October 10th

### Testgrid link

https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu

### Relevant SIG(s)

/sig node

**Comment by aojea** [comment]
> Oct 10 11:31:21.302899 bootstrap-e2e-master containerd[1433]: /home/containerd/usr/local/bin/containerd: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/containerd/usr/local/bin/containerd)

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-e2e-ubuntu-gce/1711703035543031808/artifacts/bootstrap-e2e-master/containerd.log

There was a thread recently about the glibc compatibility but I can't remember, maybe @saschagrunert

**Comment by saschagrunert** [comment]
debian bullseye is incompatible when using binaries build on bookworm, but I guess a cos bump like proposed in https://github.com/kubernetes/test-infra/pull/31003 could do the trick.

**Comment by mmiranda96** [comment]
Looks like this is fixed now.
/close

**Comment by dims** [comment]
https://prow.k8s.io/?job=ci-containerd-e2e-ubuntu-gce is 🟢 

/woof

**Comment by kannon92** [comment]
Thank you @dims and @aojea !
