### ISSUE TITLE
[Failing Test] Nvidia GPUs not available on Node (gce-device-plugin-gpu-master)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#121169]
### Which jobs are failing?

master-blocking:
- gce-device-plugin-gpu-master

### Which tests are failing?

`Kubernetes e2e suite.[It] [sig-scheduling] [Feature:GPUDevicePlugin] run Nvidia GPU Device Plugin tests`

![Image](https://github.com/kubernetes/kubernetes/assets/73882557/2aff10ed-05f9-4949-8982-417a867d6c15)

### Since when has it been failing?

`2023-10-11 13:30:42 +0000 UTC`

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master

### Reason for failure (if possible)

```
Nvidia GPUs not available on Node: "bootstrap-e2e-minion-group-3xpv"
```
https://github.com/kubernetes/kubernetes/blob/f9d987c7c8dfa36f096c38454c1ae672bb0eb56c/test/e2e/scheduling/nvidia-gpus.go#L173-L177

### Anything else we need to know?

https://github.com/kubernetes/test-infra/pull/31003 might be the relevant PR

### Relevant SIG(s)

/sig cloud-provider
/sig testing
cc @kubernetes/ci-signal

**Comment by dims** [comment]
/close

recovered! https://testgrid.k8s.io/sig-release-master-blocking#gce-device-plugin-gpu-master&width=20

<img width="1004" alt="image" src="https://github.com/kubernetes/kubernetes/assets/23304/60d92438-237b-411f-80ec-4f145a4d64de">
