### ISSUE TITLE
DIVISION_BY_ZERO in kubernetes/vendor/k8s.io/kube-openapi/pkg/validation/validate /values.go

### ISSUE THREAD

**Issue by ellena13** [kubernetes/kubernetes#121157]
Expression `factor`

https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/k8s.io/kube-openapi/pkg/validation/validate/values.go#L208

used as **divisor** at 

https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/k8s.io/kube-openapi/pkg/validation/validate/values.go#L203-L213

may have **a zero value** when variable `factor` has value `0`. 

Check at 

https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/k8s.io/kube-openapi/pkg/validation/validate/values.go#L205-L207

_does not prevent this error_.

Here we get a **DIVISION_BY_ZERO**.

P.S. This problem is relevant for the _branch 1.26_ 

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by neolit123** [comment]
there are other functions too:
https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/k8s.io/kube-openapi/pkg/validation/validate/values.go#L216

https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/k8s.io/kube-openapi/pkg/validation/validate/values.go#L203

golang catches division by zero on compile time for constants, for non-constants it panics on runtime:
https://news.ycombinator.com/item?id=6233968#:~:text=If%20you%20divide%20by%20a%20literal%200%2C%20this,18%2C%202013%7C%20root%7C%20parent%7C%20prev%7C%20next%5B%E2%80%93%5D%20Interesting%20thanks.

returning a new error errors.MultipleOfMustBeNonZero for factor == 0 makes sense to me, but leaving to api-machinery to make the call.

/sig api-machinery

**Comment by jiahuif** [comment]
/assign @apelisse 
For kube-openapi
Thank you
/triage accepted

**Comment by carlory** [comment]
Hi @jiahuif 

It has been fixed by https://github.com/kubernetes/kubernetes/pull/108996 in v1.24. I don't know what should we do else.

**Comment by liggitt** [comment]
1.27 is now the oldest supported version. Marking this as fixed.
