### ISSUE TITLE
Allow volumeClaimTemplates annotations to be updated

### ISSUE THREAD

**Issue by andreclaro** [kubernetes/kubernetes#121178]
### What would you like to be added?

Allow annotations in volumeClaimTemplates (StatefulSet) to be updated and consequently be propagated to the PVC. This will allow us to use https://github.com/mtougeron/k8s-pvc-tagger and keep EBS Volumes tags up-to-date.

Related with https://github.com/kubernetes/kubernetes/issues/68737

### Why is this needed?

Keep EBS volumes tags up-to-date, when using volumeClaimTemplates to create PVC/volume.

**Comment by MasayaAoyama** [comment]
I'm agree to change PVC several fields with StatefulSet via volumeClaimTemplates. Do upstream has any plans for these?

**Comment by liggitt** [comment]
https://github.com/kubernetes/kubernetes/issues/123551 also requested labels be able to be updated

**Comment by Firehed** [comment]
/reopen

I've run into this (via the linked #123551) when trying to manage a StatefulSet with a volumeClaimTemplate via Kustomize. Any modification to labels via `commonLabels` (including the recommended `app.kubernetes.io/version`) will cause the apply operation to fail. To add insult to injury, it successfully applies the changes to the service's selector but not to the sts, which functionally empties out the service (leading to potential downtime) until manually deleting and recreating the statefulset.

**Comment by towolf** [comment]
@liggitt could you reopen this?

**Comment by jmtx1020** [comment]
it's kind of strange, that this doesn't *just* work? I think it should be re-opened as well. Labels aren't destructive or dangerous to change as far as I can tell.

**Comment by guillaumebernard84** [comment]
Hello, I need this feature too, is it possible to re-open? 
I need to add labels to a sts created by a helm chart but the helm chart doesn't allow labels.
I wanted to add the labels afterwards using kustomize, but I encountered this issue.

**Comment by dannysauer** [comment]
Add another usecase on the fire - I need editable PVC annotations in order to [enable automatic resizing](https://github.com/topolvm/pvc-autoresizer) when the helm chart doesn't allow for annotations.

(CC: @andreclaro to maybe reopen?)
