### ISSUE TITLE
HANDLE_LEAK in kubernetes/vendor/github.com/google/cadvisor/fs /fs.go

### ISSUE THREAD

**Issue by ellena13** [kubernetes/kubernetes#121155]
### What happened?

The handle `fileReader` **is created** by calling function `os.Open` at 

https://github.com/kubernetes/kubernetes/blob/11902a838028edef305dfe2f96be929bc4d114d8/vendor/github.com/google/cadvisor/fs/fs.go#L98

and **lost** when escape from `NewFsInfo` function. 

The **Close()** operator should be used before the function ends, otherwise there will be a **HANDLE_LEAK**.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by kannon92** [comment]
I would file this under  https://github.com/google/cadvisor as this is a vendored package.

**Comment by dims** [comment]
FYI https://github.com/golang/go/issues/41505#issuecomment-695763898

handles from os.Open seem to be garbage collected

https://github.com/search?type=code&q=path%3A%2Fsrc%5C%2Fos%5C%2Ffile_unix.go%2F+setFinalizer+org%3Agolang
