### ISSUE TITLE
pull-kubernetes-e2e-gce-storage-snapshot is timing out occasionally

### ISSUE THREAD

**Issue by msau42** [kubernetes/kubernetes#121188]
### Which jobs are flaking?

pull-kubernetes-e2e-gce-storage-snapshot

### Which tests are flaking?

The job sometimes times out during teardown

### Since when has it been flaking?

We started getting job timeouts after Oct 10: https://prow.k8s.io/job-history/gs/kubernetes-jenkins/pr-logs/directory/pull-kubernetes-e2e-gce-storage-snapshot?buildId=

### Reason for failure (if possible)

It looks like the job consistently took around 1hr40-50m, but now it is occasionally hitting the 2hr job timeout.

### Relevant SIG(s)

/sig storage

**Comment by xing-yang** [comment]
@msau42 Can this be closed now?

**Comment by msau42** [comment]
It seems like it's resolved now although I don't think we ever got to the root cause.

/close
