### ISSUE TITLE
Can we add Image digest check while kubelet pull image by "Parallel" mode.

### ISSUE THREAD

**Issue by mr-002** [kubernetes/kubernetes#121137]
### What would you like to be added?

Image digest check might needed while kubelet pull image by "Parallel" mode. 
Same Image digest pull request no need to queue up and wait meaninglessly.

Code in kubelet:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/images/puller.go#L56

### Why is this needed?

If there is multiple pods with same image are in the same node, when we update pods image, these update requests with same digest will queue up and block other pod update. 
"queue up and block " with same digest pull req is meaninglessly.

**Comment by vaibhav2107** [comment]
/remove-lifecycle rotten
As PR is open
