### ISSUE TITLE
Error adding pod to CNI network "crio": plugin type="bridge" failed (add): failed to set bridge addr: could not add IP address to "cni0": permission denied

### ISSUE THREAD

**Issue by tsukiazuma** [kubernetes/kubernetes#121102]
### What happened?

When I create new pod, I revice warning:
`Warning  FailedCreatePodSandBox  3s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to create pod network sandbox k8s_nginx_kube-system_eb625b1e-135f-4e0c-a74d-2e11d62df07c_0(c362db60e67a4e3dab204aee5ca8128f6fb6ddcbfbb5f7d3584e6fb6f3fc9595): error adding pod kube-system_nginx to CNI network "crio": plugin type="bridge" failed (add): failed to set bridge addr: could not add IP address to "cni0": permission denied`

### What did you expect to happen?

Please help me fix it

### How can we reproduce it (as minimally and precisely as possible)?

1. Deloy Kubernetes with step by step: https://www.linuxtechi.com/how-to-install-kubernetes-cluster-rhel/
2. Create new pod and revice error

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:25:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
None
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Red Hat Enterprise Linux 8.4 (Ootpa)
$ uname -a
x86_64 GNU/Linux

</details>


### Install tools

<details>
None
</details>


### Container runtime (CRI) and version (if applicable)

<details>

```console
$ crio version
Starting CRI-O, version: 1.26.4, git: unknown(clean)



### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml

**Comment by utkarsh-singh1** [comment]
@tsukiazuma, It is a support request please post your query here at - https://kubernetes.io/docs/tasks/debug/#stack-exchange and https://kubernetes.io/docs/tasks/debug/#stack-exchange.

/remove sig-network
/kind support

**Comment by tsukiazuma** [comment]
Oh sorry, I'll take note next time.
And please help me.

**Comment by utkarsh-singh1** [comment]
@tsukiazuma, this error seems to be comman Issue on Setup kubernetes cluster on Stackoverflow, if you resolve this issue you can close this issue.

**Comment by utkarsh-singh1** [comment]
You can also refer to - 

- https://github.com/cri-o/cri-o/issues/3555
- https://github.com/kubernetes/minikube/issues/7380

for more info.

**Comment by tsukiazuma** [comment]
Oh, I set up kubernetes success.
Thank you

**Comment by MikeZappa87** [comment]
@tsukiazuma what did you need to change to fix this issue?

**Comment by MikeZappa87** [comment]
Awesome thanks. Are you able to close this issue?

**Comment by tsukiazuma** [comment]
Yeah, I will close now.
Thank you
