### ISSUE TITLE
valueFrom slow work

### ISSUE THREAD

**Issue by my1990** [kubernetes/kubernetes#121263]
### What happened?

Yaml is as follows：

env:
- name: POD_NAME
  valueFrom:
     fieldRef:
       fieldPath: metadata.name

Script content for process 1: mkdir - p/home/$POD_ NAME

Expect to create/home/$POD_NAME directory, but occasionally it was found that it could not be created. Debugging found that the $POD_NAME variable value was empty at the moment of executing process 1.

So I want to know when the environment was injected into the container? Isn't the environment variable injected before process 1 started

### What did you expect to happen?

Before the start of process 1, all environment variables have been injected into the container

### How can we reproduce it (as minimally and precisely as possible)?

It is difficult to reproduce. In the environment, there are hundreds of identical pods that are frequently restarted. Occasionally, one pod may show that process 1 has started, but the environment variable has not yet been injected,

### Anything else we need to know?

Most of the time, environment variables can be injected into the container before process 1 starts, but occasionally they cannot. So I want to know when the environment variable was injected into the container

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

kubelet 1.21.5
</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
Can you reproduce on a supported version of Kubernetes?

Also please add a reproducible YAML for the pod.

/triage needs-information
