### ISSUE TITLE
[flaky] [sig-network] Services should not be able to connect to terminating and unready endpoints if PublishNotReadyAddresses is false

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121209]
### Failure cluster [2ba4254643e8ce642cec](https://go.k8s.io/triage#2ba4254643e8ce642cec)
https://storage.googleapis.com/k8s-triage/index.html?test=PublishNotReadyAddresses

also see it flaky in https://testgrid.k8s.io/sig-release-master-blocking#gce-ubuntu-master-containerd
##### Error text:
```
[FAILED] expected error when trying to connect to NodePort address
Expected an error to have occurred.  Got:
    <nil>: nil
In [It] at: test/e2e/network/service.go:2146 @ 10/01/23 10:34:07.036

```
#### Recent failures:
[2023/10/13 04:03:08 ci-kubernetes-e2e-ubuntu-gce-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1712559542350385152)
[2023/10/12 02:50:42 ci-kubernetes-e2e-prow-canary](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-prow-canary/1712178928166113280)
[2023/10/11 05:20:41 ci-kubernetes-e2e-gci-gce-proto](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-proto/1711854284548608000)
[2023/10/11 03:48:41 ci-cos-containerd-e2e-ubuntu-gce](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-cos-containerd-e2e-ubuntu-gce/1711831131495600128)
[2023/10/10 23:52:41 ci-kubernetes-e2e-ubuntu-gce-containerd](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1711771739047858176)

/kind flake
/sig network

**Comment by aojea** [comment]
hmm, it does not look well indeed , I don't have time immediately but appreciate if someone can do an analysis of one of the failures 
/cc

**Comment by aojea** [comment]
failing jobs are not storing the kube-proxy logs, this is critical to solve ASAP or we are blind on failures

https://kubernetes.slack.com/archives/C09QZ4DQB/p1697365979681519

**Comment by pacoxu** [comment]
> failing jobs are not storing the kube-proxy logs, this is critical to solve ASAP or we are blind on failures
> 
> https://kubernetes.slack.com/archives/C09QZ4DQB/p1697365979681519

https://github.com/kubernetes/test-infra/pull/31037 is merged to fix that.

Let's wait for the next flake to happen. 😄

**Comment by pacoxu** [comment]
Got 1 in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1713711396362915840
- the kube-proxy log is available

**Comment by aojea** [comment]
ok, this goes this way

https://github.com/kubernetes/kubernetes/blob/afc302c2d24fea7be7d6af33c79fdb81e1a33131/test/e2e/network/service.go#L2121-L2153

The ` Wait the change has been propagated and the service start to fail` only verifies that the change has been propagated to the specific node where that is tested , however, later we test nodePorts on different nodes, and kube-proxies in different nodes have different propagation times

See  https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1713711396362915840

> Oct 16 00:38:33.730: INFO: successfully validated that service svc-not-tolerate-unready in namespace services-7817 exposes endpoints map[webserver-pod:[80]]



> Oct 16 00:39:06.109: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.82.120.23 --kubeconfig=/workspace/.kube/config --namespace=services-7817 exec pause-pod-1 -- /bin/sh -x -c curl -q -s --connect-timeout 5 10.0.91.213:80/hostname'
> Oct 16 00:39:06.618: INFO: rc: 7
> Oct 16 00:39:06.619: INFO: Running '/workspace/kubernetes/platforms/linux/amd64/kubectl --server=https://34.82.120.23 --kubeconfig=/workspace/.kube/config --namespace=services-7817 exec pause-pod-1 -- /bin/sh -x -c curl -q -s --connect-timeout 5 10.138.0.3:30184/hostname'
> Oct 16 00:39:07.164: INFO: stderr: "+ curl -q -s --connect-timeout 5 10.138.0.3:30184/hostname\n"
> Oct 16 00:39:07.164: INFO: stdout: "webserver-pod"
> 

10.0.91.213 host rejects , however, 10.138.0.3  accepts and fails the test

> Oct 16 00:39:07.331: INFO: At 2023-10-16 00:38:33 +0000 UTC - event for pause-pod-1: {default-scheduler } Scheduled: Successfully assigned services-7817/pause-pod-1 to bootstrap-e2e-minion-group-sdr1

The test pod runs in  bootstrap-e2e-minion-group-sdr1, that is 10.138.0.6

10.138.0.3 is bootstrap-e2e-minion-group-v9j8, if we check [kube-proxy logs of that node](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-ubuntu-gce-containerd/1713711396362915840/artifacts/bootstrap-e2e-minion-group-v9j8/kube-proxy.log) , we can observe that the service is not processed until 3 seconds later than the check 00:39:09 vs 00:39:06

> I1016 00:39:09.558117       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="proxy-1070/e2e-proxy-test-service" endpoints=["10.64.3.211:80"]
> I1016 00:39:09.558169       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="services-7817/svc-not-tolerate-unready:http" endpoints=["10.64.3.204:80"]
> I1016 00:39:09.558187       1 endpointslicecache.go:373] "Setting endpoints for service port name" portName="services-7817/svc-not-tolerate-unready:http" endpoints=["10.64.3.204:80"]
> I1016 00:39:09.558218       1 proxier.go:790] "Syncing iptables rules"
> I1016 00:39:09.558657       1 iptables.go:358] "Running" command="iptables-save" arguments=["-t","nat"]
> I1016 00:39:09.567897       1 proxier.go:1501] "Reloading service iptables data" numServices=21 numEndpoints=56 numFilterChains=6 numFilterRules=8 numNATChains=7 numNATRules=39
> I1016 00:39:09.567920       1 iptables.go:423] "Running" command="iptables-restore" arguments=["-w","5","-W","100000","--noflush","--counters"]
> I1016 00:39:09.588213       1 proxier.go:1530] "Network programming" endpoint="services-7817/svc-not-tolerate-unready" elapsed=8.588175842
> I1016 00:39:09.588300       1 cleanup.go:63] "Deleting conntrack stale entries for services" IPs=[]
> I1016 00:39:09.588318       1 cleanup.go:69] "Deleting conntrack stale entries for services" nodePorts=[]
> I1016 00:39:09.588329       1 proxier.go:779] "SyncProxyRules complete" elapsed="30.353984ms"

The solution is to validate on both nodes we are doing the check that kube-proxy has programmed the rules, or just validate one node

**Comment by vlasebian** [comment]
Hi! I would like to help with this.

For now, I am trying to understand how the test works, but I don’t get something. So two pod configurations are created, one with a webserver and one with an agn image. The first one is assigned to node0 and the second one to node1. From the agn pod, which is on node1, curls are done to node0 to the webserver:

- First with clusterIPaddres:

```
cmd = fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, nodePortAddress1)
			_, err = e2eoutput.RunHostCmd(pausePod1.Namespace, pausePod1.Name, cmd)
			gomega.Expect(err).To(gomega.HaveOccurred(), "expected error when trying to connect to NodePort address")
```

- Second with the nodePortAddress0

```
cmd = fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, nodePortAddress0)
			_, err = e2eoutput.RunHostCmd(pausePod1.Namespace, pausePod1.Name, cmd)
			gomega.Expect(err).To(gomega.HaveOccurred(), "expected error when trying to connect to NodePort address")
```

But why is the third one needed?

```
cmd = fmt.Sprintf(`curl -q -s --connect-timeout 5 %s/hostname`, nodePortAddress1)
			_, err = e2eoutput.RunHostCmd(pausePod1.Namespace, pausePod1.Name, cmd)
			gomega.Expect(err).To(gomega.HaveOccurred(), "expected error when trying to connect to NodePort address")
```

Isn’t this a curl from the pod from node0 to itself? Is this relevant to the test? Or am I missing something?

**Comment by aojea** [comment]
to exercise that it works from same node to cluster ip, same node to nodeport, node to nodeport on other node

Those are different paths

**Comment by vlasebian** [comment]
I made a PR. When you have a moment to check it, let me know if it's okay or if anything needs to be modified. Thank you!
