### ISSUE TITLE
Kubernetes scale and performance support lacks details

### ISSUE THREAD

**Issue by amitkgupta** [kubernetes/kubernetes#12120]
The [documentation on Large Clusters](https://github.com/GoogleCloudPlatform/kubernetes/blame/6129d3d4eb80714286650818081a64ce2699afed/docs/admin/cluster-large.md#L38) says:

> At v1.0, Kubernetes supports clusters up to 100 nodes with 30 pods per node and 1-2 containers per pod.

I'd love to know more details as to how these numbers were determined, and what they mean in general:

* What are the supported levels of resource consumption per container, and what are the compute resource specs recommended for a node?
* What sort of the work can the containers be doing? Were the numbers above determined using the [pause container](https://groups.google.com/forum/#!topic/google-containers/jVjv0QK4b_o)?
* What does "support" mean, i.e. what's the SLA I can expect running a 100 node, 3000-6000 container environment?  Can I just bring the containers up, or can I leave them up?  Can they serve traffic?  Will there be any impact on performance of applications running in containers or Kubernetes system components (e.g. API), etc?
* What was the exact protocol used to determine these numbers, and how can I reproduce these results?
* Is there any public CI build that gives visibility into how Kubernetes is tested at scale?

I realize this is a lot to ask, but anything that sheds more light on how Kubernetes scales would be very helpful.

**Comment by bprashanth** [comment]
> What are the supported levels of resource consumption per container, and what are the compute resource specs recommended for a node?

You can reproduce it with a 100 node n1-standard1 cluster and an n1-standard-4 master 

> What sort of the work can the containers be doing? Were the numbers above determined using the pause container?

Yes, we used pause but only to avoid variance. The scalability limit is the master, so the type of pod shouldn't matter. If you want to experiment with a higher number of pods per node (and a larger master) you will have to tweak https://github.com/GoogleCloudPlatform/kubernetes/blob/12b9da8f3d1e1f27ac93d62922eb2bba110cdbe1/cmd/kubelet/app/server.go#L248.

> What does "support" mean, i.e. what's the SLA I can expect running a 100 node, 3000-6000 container environment? Can I just bring the containers up, or can I leave them up? Can they serve traffic? Will there be any impact on performance of applications running in containers or Kubernetes system components (e.g. API), etc?

Recommend profiling your application for a better understanding of how qps/throughput/latency scales (https://github.com/GoogleCloudPlatform/kubernetes/blob/release-1.0/docs/user-guide/monitoring.md). We intentionally avoid second guessing latencies on the various cloud providers. The containers will keep running and serving traffic, as long as there are resources available on the node. 

> What was the exact protocol used to determine these numbers, and how can I reproduce these results?
Is there any public CI build that gives visibility into how Kubernetes is tested at scale?

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/test/e2e/density.go. We run that ~hourly with builds from ToT, but we're still in the process of exposing the builder to the public.

**Comment by amitkgupta** [comment]
Thanks @bprashanth 

I've gone to https://console.developers.google.com, created a project, and under Compute > Container Engine > Container clusters I've created a 22 node (for now, will need to request quota increase) cluster based off machine type n1-standard-1 (1 vCPU, 3.75 GB memory).  I have the kubectl binary installed on my laptop, and an image on docker hub for a little Golang web server that listens on port 8080.  With respect to reproducing the scale test, I need to figure out how to get my kubectl client to talk to the cluster I created in GCE (GKE?), the documentation isn't clear.  Any help?

**Comment by amitkgupta** [comment]
I'm following [these docs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md) instead now, and making progress.  I can `kubectl get pods`.  I've manually edited the config file to increase the number of minion nodes and use the n1-standard-4 instance type for the master.

I don't quite get what you mean about tweaking https://github.com/GoogleCloudPlatform/kubernetes/blob/12b9da8f3d1e1f27ac93d62922eb2bba110cdbe1/cmd/kubelet/app/server.go#L248.  Do you mean that if I edit the code on my laptop and re-run `./cluster/kube-up.sh` it'll reflect the changes on the master server?  Or do I have to SSH onto the server, kill some service, and start a new service with a different flag value set?

**Comment by amitkgupta** [comment]
UPDATE: creating a 22 node cluster from the https://console.developers.google.com/ originally worked but I couldn't get it to work with `kubectl`.  I tried a few other things, but the only working documentation was [this one](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md).  Manually modifying the config file as you recommended, I tried a 22 node cluster, but it got stuck at 20.  I then tried a 10 node cluster (10 minion node of type n1-standard-1, and a separate n1-standard-4 master) and was able to push my docker application:

```sh
$ kubectl run grace --image=onsi/grace-busybox --replicas=2 --port=8080
$ kubectl expose rc grace --port=8080 --type=LoadBalancer
```

The docs say to use `kubectl get services` to get the routable IP.  The info there didn't help, but via the dev console web UI I was able to find an External IP.  Finally I've been able to route to my app, but there were a couple of questions/shortcomings:

1. My app has a `/env` endpoint that dumps the ENV, and I noticed the host was not changing much as I refreshed the page.  Seems like the load balancer is sending my requests to the same host most of the time.  I'll try to research the load balancing algorithms and open a separate issue if I still have questions.
2. I tried to `kubectl scale --replicas=N rc myapp` for various values of `N`.  Ultimately I wanted to shoot for 400 (= 10 nodes x 40 max containers per node), but when I set `N` to 100, I observed `watch "kubectl get pods | grep Run | wc -l"` top out at 82.  I waited at least a minute.

**Comment by bprashanth** [comment]
You should be following getting started guide to setup your cluster, as you've already discovered. I would recommend going through the quick-start on the main site, so you get familiar with some of the concepts (http://kubernetes.io/v1.0/docs/user-guide/quick-start.html). 

> I observed watch "kubectl get pods | grep Run | wc -l" top out at 82. I waited at least a minute.

See http://kubernetes.io/v1.0/docs/user-guide/introspection-and-debugging.html and http://kubernetes.io/v1.0/docs/user-guide/application-troubleshooting.html. You're probably out of capacity, each n1standard1 can run about 10pods unless you specify their limits otherwise, and there are some default cluster addons. 

Suggest going through the user guide to get familiar with these concepts

**Comment by amitkgupta** [comment]
I'm trying to repro the scalability numbers.  Here's exactly what I want to be able to do:

1. Run a Kubernetes cluster on GCE with 1 master and as many minions I can get, with the ideal goal of hitting 100 minions.
2. Run a single stateless web app server with very low resource requirements (practically a static asset server) as a single-container pod replicated at 40 replicas per minion. This container is based off the docker:///onsi/grace-busybox image.
3. Expose the rc as a single service, i.e. a single publicly-routable IP:PORT load-balancing in front of all 40 x numMinions containers, and confirm that I can route to the service in my browser. Ideally I'd like to be able to observe the load balancing behaviour somehow.  The app has an endpoint that exposes environment information like hostname; if I hit that endpoint and refresh, I'd like to see that value change.  I'm not sure if the load balancing algorithm does some sort of caching to route requests from the same client to the same container, so validating the load-balancing is just a nice-to-have for now.
4. No addons.

There are many sites and docs on how to do 1, the only one that I've found to work correctly is [this one](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/gce.md).  I've been able to get a 10-20 node cluster up and running, not quite 100, but fine for now.  Specifically it's a n1-standard-4 master and n1-standard-1 minions.

Trying 2, I can only get up to about 8 containers per node.  You mentioned there being something I can tweak somewhere to have the nodes and scheduler support more, but it's still not clear exactly what I have to do to do this.  My workflow for changing the instance types or number of nodes is to modify the `cluster/gce/config-default.sh` file and running `./cluster/kube-down.sh` and `./cluster/kube-up.sh`.  I don't see anything in `cluster/gce/config-default.sh` or in any documentation on how to be able to run 40 containers per node; you pointed me to some line in some source code, but I don't expect modifying source code will change the container capacity on the nodes deployed by `./cluster/kube-up.sh`.

I'm able to do 3 to a satisfactory level.

As for 4, you mentioned I might not be able to run all the containers I ask for due to addons running on the nodes.  Can I do this by modifying `cluster/gce/config-default.sh` as follows:

```
# ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-googleinfluxdb}"
ENABLE_CLUSTER_MONITORING="${KUBE_ENABLE_CLUSTER_MONITORING:-none}"

# ENABLE_NODE_LOGGING="${KUBE_ENABLE_NODE_LOGGING:-true}"
ENABLE_NODE_LOGGING="${KUBE_ENABLE_NODE_LOGGING:-false}"

# ENABLE_CLUSTER_LOGGING="${KUBE_ENABLE_CLUSTER_LOGGING:-true}"
ENABLE_CLUSTER_LOGGING="${KUBE_ENABLE_CLUSTER_LOGGING:-false}"

# ENABLE_CLUSTER_DNS=true
ENABLE_CLUSTER_DNS=false
```

Are there other addons?  How do I disable them?

Thanks again for all your help so far.

**Comment by fgrzadkowski** [comment]
@wojtek-t @gmarek

**Comment by gmarek** [comment]
@amitkgupta:
You can run ~8 pods per Node probably because each of them is using 100mCPU and if you add to it fluentd and maybe something else it will add to one, whole CPU, which is exactly as much as n1-standard-1 has. To change this you'd need to specify some lower (well - really low) CPU/memory request for your Pods.

As for loadbalancing - we do have IP-based session affinity, so make sure it's not enabled. I'm not sure if it's currently default or not (@thockin ?). Having session affinity turned on would mean that hitting service from the same machine will not let you observe load-balancing behavior.

As for cloud addons - I believe you can just kill some Pods from kube-system namespace. I'm not quite sure which ones are critical - my guess is that you shouldn't kill `fluentd`, but the rest should be disposable.

**Comment by amitkgupta** [comment]
Too hard to get cluster up and configured correctly to assess scaling numbers, giving up for now.  I look forward to:

> we're still in the process of exposing the builder to the public.

Thanks for all the help.

**Comment by thockin** [comment]
Sorry for the delay:

Client affinity is NOT enabled by default.  Note that the Client IP here is
the pod IP, not the node IP.

**Comment by amitkgupta** [comment]
@thockin Err, wouldn't the client IP be my personal machine's IP, i.e. where the browser originating the request lives?

**Comment by thockin** [comment]
if you're coming from out-of-cluster, then yes :)
