### ISSUE TITLE
Can’t get UserNamespacesSupport to work on kubernetes 1.28.1

### ISSUE THREAD

**Issue by ikwork** [kubernetes/kubernetes#121265]
### What happened?

I want to enable UserNameSpaceSupport on my k8s cluster but I can’t get it to work.
I’ve followed [User Namespaces: Now Supports Running Stateful Pods in Alpha](https://kubernetes.io/blog/2023/09/13/userns-alpha/) exactly, but still cant get the expected results.

From the above link, I understood the following requirement

```
On Linux you need Linux 6.3 or greater. This is because the feature relies on a kernel feature named idmap mounts, and support to use idmap mounts with tmpfs was merged in Linux 6.3.

If you are using CRI-O with crun, this is supported in CRI-O 1.28.1 and crun 1.9 or greater. If you are using CRI-O with runc, this is still not supported.

None of these containerd limitations apply to CRI-O 1.28.
```

I’ve configured my cluster exactly the same

```
root@ishan-mantic-minotaur:~/ishan# /usr/local/bin/crun --version
crun version 1.9.2

root@ishan-mantic-minotaur:~/ishan# /usr/local/bin/crio --version
crio version 1.28.1
Version:        1.28.1

root@ishan-mantic-minotaur:~/ishan# uname -r
6.5.0-9-generic

root@ishan-mantic-minotaur:~/ishan# kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2

root@ishan-mantic-minotaur:~/ishan# grep UserN /etc/kubernetes/manifests/kube-apiserver.yaml
    - --feature-gates=UserNamespacesSupport=true
```

### What did you expect to happen?

I’m expecting the container to be in a different user namespace, and the process inside it to not run as root on the host. But that doesnt seem to happen.

```
# INSIDE POD

root@ishan-mantic-minotaur:~/ishan# k get po test4-6f5bc89f5b-82znp -o yaml | grep hostUser
  hostUsers: false

root@ishan-mantic-minotaur:~/ishan# k exec -it test4-6f5bc89f5b-82znp bash
root@test4-6f5bc89f5b-82znp:/# id
uid=0(root) gid=0(root) groups=0(root)
root@test4-6f5bc89f5b-82znp:/# readlink /proc/self/ns/user
user:[4026531837]
root@test4-6f5bc89f5b-82znp:/# cat /proc/self/uid_map
         0          0 4294967295
root@test4-6f5bc89f5b-82znp:/# sleep 12345 &
[1] 8


# ON HOST

root@ishan-mantic-minotaur:~/ishan# readlink /proc/self/ns/user
user:[4026531837]
root@ishan-mantic-minotaur:~/ishan# cat /proc/self/uid_map
         0          0 4294967295
root@ishan-mantic-minotaur:~/ishan# ps aux | grep 12345
root        8257  0.0  0.0   2484  1280 ?        S    14:31   0:00 sleep 12345
```

### How can we reproduce it (as minimally and precisely as possible)?

Launch a pod with `hostUsers: false` and verify that a new user namespace is created for the pod.

```
apiVersion: v1
kind: Pod
metadata:
  name: userns
spec:
  hostUsers: false
  containers:
  - name: shell
    command: ["sleep", "infinity"]
    image: debian
```

```
# Verify on POD
readlink /proc/self/ns/user
user:[4026531837]
cat /proc/self/uid_map
0          0 4294967295

# The the above on host, it should not be the same
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

</details>

### Cloud provider

<details>
Bare Metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
root@ishan-mantic-minotaur:~/ishan# cat /etc/os-release
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
$ uname -a
Linux ishan-mantic-minotaur 6.5.0-9-generic #9-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct  7 01:35:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
 crio --version
crio version 1.28.1
Version:        1.28.1
GitCommit:      eda470f7f503d9f40a9aa2a02e45f0878ed6fc61
GitCommitDate:  2023-09-12T14:30:18Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.20.6
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  true

crun --version
crun version 1.9.2
commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
rundir: /run/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> root@ishan-mantic-minotaur:~/ishan# grep UserN /etc/kubernetes/manifests/kube-apiserver.yaml
    - --feature-gates=UserNamespacesSupport=true

isn't this FG supposed to be set on the kubelet?
https://github.com/search?q=repo%3Akubernetes%2Fkubernetes%20UserNamespacesSupport&type=code

**Comment by ikwork** [comment]
Thanks @neolit123 for the pointer. That seems to work. There's not a single place in documentation where I could find that this feature gate needs to be enabled on kubelet.

**Comment by neolit123** [comment]
/kind documentation
/area kubelet

> That seems to work. There's not a single place in documentation where I could find that this feature gate needs to be enabled on kubelet.

kubelet maintainers can comment.

**Comment by kannon92** [comment]
/triage accepted
/close

sounds like toggling feature on in Kubelet worked! The blog didn’t mention where to turn it on.
