### ISSUE TITLE
Request timeout not respected while listing from storage

### ISSUE THREAD

**Issue by natherz97** [kubernetes/kubernetes#121267]
### What happened?

It is possible to issue a list request which exceeds the duration set by the request-timeout apiserver flag. The request-timeout flag does not appear to be enforced when the apiserver is decoding the response from etcd. 

Specifically, listing a large number of CRDs from etcd can result in high request latency from using json encoding compared to protobuf encoding. While overall etcd latency is low, the overall listing from storage latency may be over the 1 minute timeout, particularly if the apiserver needs to fetch multiple pages from etcd.

### What did you expect to happen?

We expected the list requests to be subject to the duration specified by the request-timeout flag when this latency is coming from the listing from storage phase of the request.

### How can we reproduce it (as minimally and precisely as possible)?

Create 4000 CRs and list all the objects from etcd in 2 pages of 2000 objects. If the time to list 1 page + decode takes around 50s, listing 2 pages will result in the listing from storage phase of the request taking  around 1 minute and 40s before the request fails and the client is returned a 500 response code.

Logs for apiserver Trace message:
```
I0918 10:52:29.592390      11 trace.go:205] Trace[474507988]: "List(recursive=true) etcd3" key:/<key>,resourceVersion:,resourceVersionMatch:,limit:0,continue: (18-Sep-2023 10:50:47.716) (total time: 101875ms):
Trace[474507988]: ---"fetched all pages from etcd" page-count:2 101875ms (10:52:29.592)
Trace[474507988]: [1m41.875605715s] [1m41.875605715s] END

I0918 10:52:29.596639      11 trace.go:205] Trace[1368262150]: "List" url:/apis/<CRD-path>,user-agent:<user>,audit-id:c3badffb-7382-468e-9669-caadf5c85fc1,client:<IP>,accept:application/json,protocol:HTTP/2.0 (18-Sep-2023 10:50:47.716) (total time: 101880ms):
Trace[1368262150]: [1m41.880102098s] [1m41.880102098s] END
```
Audit log entry:
```
{
  "kind": "Event",
  "apiVersion": "audit.k8s.io/v1",
  "level": "Metadata",
  "auditID": "c3badffb-7382-468e-9669-caadf5c85fc1",
  "stage": "ResponseComplete",
  "requestURI": "/apis/<CRD-path>",
  "verb": "list",
...
  "sourceIPs": [
    "<IP>"
  ],
  "userAgent": "<user>",
  "responseStatus": {
    "metadata": {},
    "status": "Failure",
    "message": "context deadline exceeded",
    "code": 500
  },
  "requestReceivedTimestamp": "2023-09-18T10:50:47.713168Z",
  "stageTimestamp": "2023-09-18T10:52:29.597086Z",
  "annotations": {
    "apiserver.latency.k8s.io/etcd": "1.084247626s",
    "apiserver.latency.k8s.io/response-write": "3.04µs",
    "apiserver.latency.k8s.io/serialize-response-object": "3.918181ms",
    "apiserver.latency.k8s.io/total": "1m41.883918313s",
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \...""
  }
}
```

### Anything else we need to know?

Related issue for supporting protobuf for CRDs: https://github.com/kubernetes/kubernetes/issues/63677

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:55:33Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.12-eks-2d98532", GitCommit:"0aa16cf4fac4da27b9e9e9ba570b990867f6a3d8", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:04Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by natherz97** [comment]
/sig api-machinery

CC: @wojtek-t @tkashem @shyamjvs

**Comment by wojtek-t** [comment]
Interesting.. - do you know where exactly we stuck?

In the call to storage:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L708

we pass the context that has timeout set, so that shouldn't hang.

OTOH, for the processing part:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L732-L751

(a) I don't know if transformer honors the context - it probably depends on the implementation
(b) but the decoding (appendListitem) certainly isn't honoring the context

So (b) might definitely be a problem, even independently from from the transformer


So I guess what I'm saying is that if listing from etcd finishes fast but the decoding is what takes most of time, then what you described can certainly be a problem.
But is that the thing you're observing?

**Comment by natherz97** [comment]
Yes, that is our understanding. Specifically, that the decoding which occurs in appendListItem doesn't respect the context, https://github.com/kubernetes/kubernetes/blob/98d37747d8f874b846d86e34e4237cbeaa4c3dc9/staging/src/k8s.io/apiserver/pkg/storage/etcd3/store.go#L991-L1004.

As a separate follow-up, it would be useful to include decoding time, or at least the overall listing from storage time, as a separate latency annotation, given the audit log entry is only capturing this latency as part of apiserver.latency.k8s.io/total.

**Comment by chaochn47** [comment]
> As a separate follow-up, it would be useful to include decoding time, or at least the overall listing from storage time, as a separate latency annotation, given the audit log entry is only capturing this latency as part of apiserver.latency.k8s.io/total.

+1. We need more granular latency tracker especially on the latency spent on decoding. Right now, it only captures etcd round trip and transformer latency.

**Comment by wojtek-t** [comment]
I would be supportive for both and would be happy to review it if someone opens up a PR for it.
