### ISSUE TITLE
[sig-node] NodeProblemDetector should run without error 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121208]
### Which jobs are failing?

ci-npd-e2e-kubernetes-gce-gci 

### Which tests are failing?

```
{ failed [FAILED] Timed out after 60.001s.
Expected success, but got an error:
    <*errors.errorString | 0xc000bf6fb0>: 
    node condition "KernelDeadlock" not found
    {
        s: "node condition \"KernelDeadlock\" not found",
    }
In [It] at: test/e2e/node/node_problem_detector.go:168 @ 10/13/23 00:28:15.457
}
```

### Since when has it been failing?

2023-10-10

### Testgrid link

https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-npd-e2e-kubernetes-gce-gci

### Reason for failure (if possible)

NPD  failure

> Oct 10 00:12:47.985987 e2e-d19706add5-7abb6-minion-group-024t node-problem-detector[3428]: /home/kubernetes/bin/node-problem-detector: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/kubernetes/bin/node-problem-detector)
> Oct 10 00:12:47.984871 e2e-d19706add5-7abb6-minion-group-024t systemd[1]: node-problem-detector.service: Main process exited, code=exited, status=1/FAILURE
> Oct 10 00:12:47.985062 e2e-d19706add5-7abb6-minion-group-024t systemd[1]: node-problem-detector.service: Failed with result 'exit-code'.
> Oct 10 00:12:58.225459 e2e-d19706add5-7abb6-minion-group-024t systemd[1]: node-problem-detector.service: Scheduled restart job, restart counter is at 54.
> Oct 10 00:12:58.225797 e2e-d19706add5-7abb6-minion-group-024t systemd[1]: Stopped Kubernetes node problem detector.
> Oct 10 00:12:58.232581 e2e-d19706add5-7abb6-minion-group-024t systemd[1]: Started Kubernetes node problem detector.

### Anything else we need to know?

- we meet a npd related issue in https://github.com/kubernetes/kubernetes/pull/120441(revert bump npd to v0.8.14).
- GLIBC_2.34 failure in https://github.com/kubernetes/kubernetes/issues/121115#issuecomment-1756420908
- 

### Relevant SIG(s)

/sig testing node

**Comment by saschagrunert** [comment]
cc @kannon92 is this something we can fix by an image update?

**Comment by aojea** [comment]
@SergeyKanzhelev what is going on with the npd tests lately? should not the be running in its own. project https://github.com/kubernetes/node-problem-detector instead on k/k

**Comment by kannon92** [comment]
xref https://github.com/kubernetes/node-problem-detector/issues/831

**Comment by kannon92** [comment]
Yea, I think this should be fixed by an image update but its not obvious to me where.  

The obvious fix is https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/node-problem-detector/node-problem-detector-presubmits.yaml#L216

**Comment by kannon92** [comment]
> @SergeyKanzhelev what is going on with the npd tests lately? should not the be running in its own. project https://github.com/kubernetes/node-problem-detector instead on k/k

I think a lot of projects (k8s.sigs and k8s) use test-infra to set up their CI infrastructure.  I know that I have used test-infra to set up kueue and jobset.  And since sig-node owns Node-Problem-Detector, it shows up in the sig-node section.

**Comment by kannon92** [comment]
@mmiranda96 can you look into this one also?  Seems related to the other cos issue.

**Comment by hakman** [comment]
NPD tests are now passing after merging https://github.com/kubernetes/test-infra/pull/31167. Thanks everyone!

**Comment by kannon92** [comment]
/close

Nice work @hakman!
