### ISSUE TITLE
 K8s topology spread constrains existing defects

### ISSUE THREAD

**Issue by dongzhiwei-git** [kubernetes/kubernetes#121284]
### What happened?

Restrictions: 2 availability zones and 3 pods, maxSkew = 2, must be met, rolling release.
Possible occurrence: 3 Pods are scheduled to an available area
Reason: There are two availability zones a1 and a2, and three pods, p1, p2, and p3. The scheduling conditions must be met for rolling release. Now a1 has p1 and p2, and a2 has p3. When restarting, k8s scheduling will start p31, p32, and p33 in area a2.
Satisfies 4 - 2 <= maxSkew(2)

### What did you expect to happen?

Appears in different availability zones

### How can we reproduce it (as minimally and precisely as possible)?
![image](https://github.com/kubernetes/kubernetes/assets/60594407/1da87f41-001b-4bcd-8be0-72c34b9e24ae)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:41Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.17", GitCommit:"68b4e26caf6ede7af577db4af62fb405b4dd47e6", GitTreeState:"clean", BuildDate:"2021-03-18T00:54:02Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

</details>

### Cloud provider

<details>
aliyun
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by dims** [comment]
@dongzhiwei-git  @pacoxu could you help translate things? other than the manifest ... it's hard.

**Comment by kerthcet** [comment]
When rolling update, with default topology constraint, we'll meet the unbalanced scheduling result, to solve this,  we introduced `matchLabelKeys` in v1.26, we graduate to beta in v1.27, so it's enabled by default. You can refer to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition for details. I think 1.18 is too old now. 

Can this help you ?

**Comment by dongzhiwei-git** [comment]
> @dongzhiwei-git @pacoxu could you help translate things? other than the manifest ... it's hard.

done，
Looking forward to your reply

**Comment by dongzhiwei-git** [comment]
> When rolling update, with default topology constraint, we'll meet the unbalanced scheduling result, to solve this, we introduced `matchLabelKeys` in v1.26, we graduate to beta in v1.27, so it's enabled by default. You can refer to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition for details. I think 1.18 is too old now.
> 
> Can this help you ?


Thank you so much

**Comment by kerthcet** [comment]
If this solves your problem, feel free to close this one, thanks a lot.

**Comment by dongzhiwei-git** [comment]
> When rolling update, with default topology constraint, we'll meet the unbalanced scheduling result, to solve this, we introduced `matchLabelKeys` in v1.26, we graduate to beta in v1.27, so it's enabled by default. You can refer to https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#spread-constraint-definition for details. I think 1.18 is too old now.
> 
> Can this help you ?

好想并不能解决我的问题

**Comment by dongzhiwei-git** [comment]
Thanks for your help guys

**Comment by kerthcet** [comment]
> 好想并不能解决我的问题

so the problem is you're using a low version kubernetes without this feature? Or this feature can't help you?

**Comment by dongzhiwei-git** [comment]
> > 好想并不能解决我的问题
> 
> so the problem is you're using a low version kubernetes without this feature? Or this feature can't help you?

Resolved, thank you very much
