### ISSUE TITLE
Does k8s of v1.28 not require the deployment of network components (such as calico, flannel, etc.)? 

### ISSUE THREAD

**Issue by WhaleSpring** [kubernetes/kubernetes#121244]
Does k8s of v1.28 not require the deployment of network components (such as calico, flannel, etc.)? After I deployed the cluster, the two coredns pods directly changed to the Running 1/1 state and were able to deploy Pod applications to the nodes normally.
![image](https://github.com/kubernetes/kubernetes/assets/81799971/7aa2c242-7994-4e78-8401-8be1585bd44b)

**Comment by aojea** [comment]
k8s require some component that provide the network to the pods, commonly named a CNI plugin, but does not necessarily need to be a daemonset, it depends on your installation

Thanks

/kind supoort
/close
