### ISSUE TITLE
kubeadm: check for DRA/Runtime compatibility

### ISSUE THREAD

**Issue by bart0sh** [kubernetes/kubernetes#121232]
Kubeadm should check if CRI runtime supports CDI and issue a warning/error if not when user tries to setup a cluster with enabled DynamicResourceAllocation.
This would inform users of possible setup issues when enabling [Dynamic Resource Allocation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-allocation).

**Comment by neolit123** [comment]
> Kubeadm should check if CRI runtime supports CDI and issue a warning/error if not when user tries to setup a cluster with enabled DynamicResourceAllocation. This would inform users of possible setup issues when enabling [Dynamic Resource Allocation](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/3063-dynamic-resource-allocation).

historicaly kubeadm only tracked the progress of the dualstack / ipv6 core feature gate and implemented logic around it. k8s core feature gates are ephemeral and now kubeadm supports a n-3 kubelet. this makes tracking kubelet feature gates increadibly complicated.

if one day DRA graduates to GA and if crictl can check for CDI, then it seems kubeadm can produce warnings. until then, this feels like a no-op on the kubeadm side.

cc @pacoxu

**Comment by pacoxu** [comment]
DRA will be beta in v1.29. If it causes a big problem for the kubelet, a warning/error should be added. If not, we may add that when it will be GA.

@bart0sh What is the behavior of kubelet if the CDI device is not supported by the container runtime when DRA is enabled?
- Will Kubelet crash? Or does kubelet fall back for CDI device-related logic?

**Comment by pacoxu** [comment]
BTW this is also related to https://github.com/kubernetes/enhancements/issues/4009. The CDI device status will be added to the CRI API when the feature gate is enabled. This KEP is also planned to be beta in v1.29.

**Comment by bart0sh** [comment]
@neolit123 
> k8s core feature gates are ephemeral and now kubeadm supports a n-3 kubelet. this makes tracking kubelet feature gates increadibly complicated.

Can Kubeadm check DRA/Runtime compatibility only if user tries to enable DynamicResourceAllocation feature using `--feature-gates` command line option?

**Comment by bart0sh** [comment]
@pacoxu 
> Will Kubelet crash? Or does kubelet fall back for CDI device-related logic?

Kubelet will not crash. If runtime doesn't support CDI injections, CDI devices will not be enabled for the container.

**Comment by neolit123** [comment]
> @neolit123
> 
> > k8s core feature gates are ephemeral and now kubeadm supports a n-3 kubelet. this makes tracking kubelet feature gates increadibly complicated.
> 
> Can Kubeadm check DRA/Runtime compatibility only if user tries to enable DynamicResourceAllocation feature using `--feature-gates` command line option?

it is complicated because kubeadm would have to check what version of the kubelet the user picks and if a feature gate exists there. the skew is n-3, like i explained. ideally, kubeadm should not manage / wrap any of the k8s feature gates.

amending my earlier comment, even if DRA goes GA, we still have to track this graduation with version checks in kubeadm.

overall, i am not in favor for adding the warnings.

**Comment by pacoxu** [comment]
> > Will Kubelet crash? Or does kubelet fall back for CDI device-related logic?
> 
> Kubelet will not crash. If runtime doesn't support CDI injections, CDI devices will not be enabled for the container.

My intuition is that it is enough for kubelet to provide warning logs or events.


> Can Kubeadm check DRA/Runtime compatibility only if user tries to enable DynamicResourceAllocation feature using `--feature-gates` command line option?

This can be done like what kubeadm did for the dual stack. 

> if one day DRA graduates to GA and if crictl can check for CDI, then it seems kubeadm can produce warnings. until then, this feels like a no-op on the kubeadm side.

+1 
In kubeadm https://github.com/kubernetes/kubernetes/blob/add482a2d31db938f3dca87920313db9d1780cf5/cmd/kubeadm/app/util/runtime/runtime.go, we use `crictl` for checking container runtime status.

**Comment by bart0sh** [comment]
Thanks for the explanations! I agree, we need to check if CDI is enabled on the Kubelet side. The way to do it should be discussed in a separate issue. I'll investigate this further.
