### ISSUE TITLE
Cleanup: Validate pod terminationGracePeriodSeconds and fix tests

### ISSUE THREAD

**Issue by thockin** [kubernetes/kubernetes#121234]
xref: https://github.com/kubernetes/kubernetes/pull/119026/files#r1265687485

Apparently we do not validate that the `terminationGracePeriodSeconds` field is non-nil.  It has a default value, so it should never actually be nil, but because we never validated it in the past, we have tests that do not set it.

We should remove code which check for nil, like the above comment:

```
	var gracePeriod int64
	if spec.TerminationGracePeriodSeconds != nil {
		// this could happen in tests
		gracePeriod = *spec.TerminationGracePeriodSeconds
	}
```

This will cause a bunch of tests to fail.  Those tests SHOULD be setting this field properly.  See "k8s.io/kubernetes/pkg/api/service/testing" which has helper functions for the same problem in Service.

**Comment by thockin** [comment]
You don't need permission :)

**Comment by fraenkel** [comment]
I got pretty far on the cleanup but then hit this test:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/apps/validation/validation_test.go#L2091

Not sure how exactly to fix this.  I can set the TerminationGracePeriodSeconds value into the PodSpec which seems dubious given the alternative which is to apply the defaults which we don't really do anywhere either.

**Comment by thockin** [comment]
What error are you getting?  That test looks like it runs an invalid (zero-value) template, which should fail?

**Comment by fraenkel** [comment]
Well since we removed the fill in for the TerminationGraccePeriod, that panics since its nil. Each of the app resources have this issue.

ValidatePodSpec still needs to grab the gracePeriod so ti can do further validation.
