### ISSUE TITLE
Sidecar container will not be restarted when image was changed

### ISSUE THREAD

**Issue by tzneal** [kubernetes/kubernetes#121333]
### What would you like to be added?

We need E2E tests for sidecars when modifying the image of a sidecar container for a running pod.

### Why is this needed?

We don't have tests that cover this scenario and haven't documented what should occur.

**Comment by SergeyKanzhelev** [comment]
Ideally need to test what happens in the following test cases:

- Standard case: sidecar image updated while Pod is running noramally, pod `restartPolicy=Always`
- Image was updated for sidecar while Pod is still initializing
- Image was updated for sidecar when Pod's restartPolicy is `never` or `onFailure`. 
- Image was updated during termination

QQ:
- Would we call `preStop` and `postStart` when container's image is being changed?

I was surprised that the image update will not restart the whole Pod. So documenting and testing this behavior on a regular containers will also be useful.

**Comment by ruquanzhao** [comment]
And there seems to be a conflict in https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

> Altering an init container image field is equivalent to restarting the Pod.

and

> The Pod will not be restarted when the init container image is changed,

**Comment by ruquanzhao** [comment]
/unassign
Anyone interested please take over.

**Comment by dshebib** [comment]
/remove-lifecycle-stale
/assign

It is not explicitly mentioned in the [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/753-sidecar-containers/README.md), but the behavior for updating the image field of a sidecar container is unchanged from updating the image field of a regular initcontainer. That is, only updating the image in an initcontainer spec does not trigger a pod restart. If used within a deployment however, the change in template is recognized and does trigger a redeployment with an updated image as usual. This should be explicitly documented, as changing the image of a regular container in a pod triggers a restart. Useful context #122926

**Comment by SergeyKanzhelev** [comment]
/retitle Sidecar container will not be restarted when image was changed
