### ISSUE TITLE
How to access the wordpress application?

### ISSUE THREAD

**Issue by adyanthaya17** [kubernetes/kubernetes#12135]
Hi,

I have built my kubernetes cluster and wanted to know if it's possible to bring up the containers of mysql wordpress wwithout making use of the GCE.

**Comment by roberthbailey** [comment]
The [mysql-wordpress-pd example](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/examples/mysql-wordpress-pd/README.md) relies on the persistent disk features of GCE. 

You might have better luck going through the [Hello Wordpress](https://cloud.google.com/container-engine/docs/tutorials/hello-wordpress) example in the GKE documentation skipping the GCE specific steps. I think it basically boils down to running `kubectl run wordpress --image=tutum/wordpress --port=80`.

**Comment by adyanthaya17** [comment]
I ran the command:
$  kubectl run wordpress --image=tutum/wordpress --port=80 

the container is in running state when I list the PODS.

Is there a way I can access the continer on the web? or through the CLI?

**Comment by roberthbailey** [comment]
What about the container do you want to access? You can get to the wordpress installation in the container by navigating to http://<container-ip>:80 in your web browser. For the CLI are you trying to get an interactive shell inside the container?

**Comment by adyanthaya17** [comment]
I created a new container POD that has wordpress and mysql running. The wordpress and mysql services are also seen.

I have tried accessing the wordpress on the web by http://10.x.x.x:80 but it's giving me a page error.

$ kubectl get services
NAME         LABELS                                    SELECTOR         IP(S)           PORT(S)
kubernetes   component=apiserver,provider=kubernetes   <none>           192.168.3.1     443/TCP
mysql        name=mysql                                name=mysql       192.168.3.237   3306/TCP
wpfrontend   name=wpfrontend                           name=wordpress   192.168.3.212   80/TCP

$ kubectl get endpoints
NAME         ENDPOINTS
kubernetes   20.20.0.80:6443
mysql        172.17.0.1:3306
wpfrontend   172.17.0.1:80


How do I access

**Comment by adyanthaya17** [comment]
This isn't working either:
$ http://10.x.x.x:80/wp-admin/install.php

**Comment by adyanthaya17** [comment]
These are the logs...

$ kubectl logs mysql
Running mysql_install_db
.
.
.

MySQL init process done. Ready for start up.

2015-08-19 04:17:09 0 [Note] mysqld (mysqld 5.6.26) starting as process 1 ...
2015-08-19 04:17:09 1 [Note] Plugin 'FEDERATED' is disabled.
2015-08-19 04:17:09 1 [Note] InnoDB: Using atomics to ref count buffer pool pages
2015-08-19 04:17:09 1 [Note] InnoDB: The InnoDB memory heap is disabled
2015-08-19 04:17:09 1 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2015-08-19 04:17:09 1 [Note] InnoDB: Memory barrier is not used
2015-08-19 04:17:09 1 [Note] InnoDB: Compressed tables use zlib 1.2.7
2015-08-19 04:17:09 1 [Note] InnoDB: Using Linux native AIO
2015-08-19 04:17:09 1 [Note] InnoDB: Using CPU crc32 instructions
2015-08-19 04:17:09 1 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2015-08-19 04:17:09 1 [Note] InnoDB: Completed initialization of buffer pool
2015-08-19 04:17:09 1 [Note] InnoDB: Highest supported file format is Barracuda.
2015-08-19 04:17:09 1 [Note] InnoDB: 128 rollback segment(s) are active.
2015-08-19 04:17:09 1 [Note] InnoDB: Waiting for purge to start
2015-08-19 04:17:09 1 [Note] InnoDB: 5.6.26 started; log sequence number 1625997
2015-08-19 04:17:09 1 [Note] Server hostname (bind-address): '*'; port: 3306
2015-08-19 04:17:09 1 [Note] IPv6 is available.
2015-08-19 04:17:09 1 [Note]   - '::' resolves to '::';
2015-08-19 04:17:09 1 [Note] Server socket created on IP: '::'.
2015-08-19 04:17:09 1 [Warning] 'proxies_priv' entry '@ root@mysql' ignored in --skip-name-resolve mode.
2015-08-19 04:17:09 1 [Note] Event Scheduler: Loaded 0 events
2015-08-19 04:17:09 1 [Note] mysqld: ready for connections.
Version: '5.6.26'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)


$ kubectl logs wordpress
WordPress not found in /var/www/html - copying now...
Complete! WordPress has been successfully copied to /var/www/html

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

Warning: mysqli::mysqli(): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

Warning: mysqli::mysqli(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in - on line 10

MySQL Connection Error: (2002) php_network_getaddresses: getaddrinfo failed: Name or service not known

**Comment by adyanthaya17** [comment]
Is there a way as to how to access the pod containers that were hosted in the cluster environment.

**Comment by adyanthaya17** [comment]
The containers (mysql and wordpress) keep geting killed and re creating when I check for the 'docker ps -a', is there a way to stop it?

**Comment by goltermann** [comment]
We’re going through old support issues and asking everyone to direct your questions to [stackoverflow](http://stackoverflow.com/questions/tagged/kubernetes). 

We are trying to consolidate the channels to which questions for help/support are posted so that we can improve our efficiency in responding to your requests, and to make it easier for you to find answers to frequently asked questions and how to address common use cases. 

We regularly see messages posted in multiple forums, with the full response thread only in one place or, worse, spread across multiple forums. Also, the large volume of support issues on github is making it difficult for us to use issues to identify real bugs.

The Kubernetes team scans stackoverflow on a regular basis, and will try to ensure your questions don't go unanswered.
