### ISSUE TITLE
Enable Kubelet HTTP/2 idle time configurable

### ISSUE THREAD

**Issue by lht6** [kubernetes/kubernetes#121308]
### What would you like to be added?

Currently, the kubelet idle time to api server is fixed to 90 seconds. Would it be possible to make the idle time configurable, so that kubelet can recognize there is something wrong with the current connection, and reconnect sooner?   

### Why is this needed?

If there is something wrong with the connection between kubelet and api server for more than some period (40 seconds), k8s will treat nodes as not ready.

**Comment by aojea** [comment]
Where do you see is 90?

The defaults is 15 for ping timeout and 30 for readidle timeout, and you can override them by setting the corresponding environment variables
https://github.com/kubernetes/apimachinery/blob/a1b8da8152f9991a6691ae94bd6b6e3c34a590bd/pkg/util/net/http.go#L144-L172

**Comment by aojea** [comment]
/close

no answer, feel free to reopen if needed
