### ISSUE TITLE
[Failing Test] Cos containerd tests are failing due libgc mismatch

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#121309]
### Which jobs are failing?

- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-e2e
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-inplace-pod-resize-containerd-e2e-serial
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-e2e
- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-cluster-e2e-inplace-pod-resize-containerd-main-v2
- https://testgrid.k8s.io/sig-node-containerd#e2e-cos-device-plugin-gpu
- ~~https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e~~

### Which tests are failing?

These tests are completely failing due to a compilation issue so no tests are running.

### Since when has it been failing?

NA

### Testgrid link

- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-containerd-e2e
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-inplace-pod-resize-containerd-e2e-serial
- https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-e2e
- https://testgrid.k8s.io/sig-node-presubmits#pr-kubelet-gce-cluster-e2e-inplace-pod-resize-containerd-main-v2
- https://testgrid.k8s.io/sig-node-containerd#e2e-cos-device-plugin-gpu
- ~~https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv2-containerd-node-e2e~~

### Reason for failure (if possible)

```
Oct 17 18:13:43.987386 bootstrap-e2e-master containerd[1205]: /home/containerd/usr/local/bin/containerd: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/containerd/usr/local/bin/containerd)
Oct 17 18:13:43.784506 bootstrap-e2e-master systemd[1]: containerd.service: Main process exited, code=exited, status=1/FAILURE
Oct 17 18:13:43.784516 bootstrap-e2e-master systemd[1]: containerd.service: Failed with result 'exit-code'.
Oct 17 18:13:48.976159 bootstrap-e2e-master systemd[1]: containerd.service: Scheduled restart job, restart counter is at 1.
Oct 17 18:13:48.976351 bootstrap-e2e-master systemd[1]: Stopped containerd container runtime.
Oct 17 18:13:48.979390 bootstrap-e2e-master systemd[1]: Starting containerd container runtime...
Oct 17 18:13:48.981424 bootstrap-e2e-master systemd[1]: Started containerd container runtime.
Oct 17 18:13:48.986207 bootstrap-e2e-master containerd[1322]: /home/containerd/usr/local/bin/containerd: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/containerd/usr/local/bin/containerd)
```

You can go to the containerd logs in artifacts and see that GLIBC_2.34 is not found.

### Anything else we need to know?

Typically these fixes can be resolved by an image update.  

These tests don't seem to point to any default image.

### Relevant SIG(s)

/sig node

**Comment by kannon92** [comment]
One of these is not like the other!  

Looks like ci-cos-cgroupv2-containerd-node-e2e is failing due to a missing clone of containerd.  Will have a fix shortly.

**Comment by mmiranda96** [comment]
/assign

I noticed that the jobs were passing with image  `cos-stable-109-17800-0-47`, started failing with image `cos-stable-109-17800-0-51`. I've filed an internal support case, will post more updates later.

**Comment by mmiranda96** [comment]
COS team came back to us, it seems that the change is in how containerd is compiled (lGLIBC versions are the same across both images). I'll take a look at this issue next week, as I'm oncall this one.

**Comment by kannon92** [comment]
> One of these is not like the other!
> 
> Looks like ci-cos-cgroupv2-containerd-node-e2e is failing due to a missing clone of containerd. [kubernetes/test-infra#31054](https://github.com/kubernetes/test-infra/pull/31054) fixes ci-cos-cgroupv2-containerd-node-e2e.

This PR fixed this issue.  I striked it out on this issue.

**Comment by kannon92** [comment]
Added https://testgrid.k8s.io/sig-node-containerd#e2e-cos-device-plugin-gpu to the list as this is also failing for a similar reason.

**Comment by bart0sh** [comment]
We don't even need to statically rebuild containerd to fix this as statically built binaries are published by the containerd project as part of their releases, e.g. https://github.com/containerd/containerd/releases/tag/v1.7.7

**Comment by akhilerm** [comment]
The binaries that we use in testing are from the main branch of containerd. So getting a static binary from the release is not an option.

**Comment by akhilerm** [comment]
> COS team came back to us, it seems that the change is in how containerd is compiled (lGLIBC versions are the same across both images).

What is the cos version used in `cos-stable-109-17800-0-47`?  

The reason of failure may be because the [`gcr.io/k8s-staging-test-infra/kubekins-e2e`](https://github.com/kubernetes/test-infra/blob/master/config/jobs/containerd/containerd/containerd-postsubmit-jobs.yaml#L13)  image that is used for building containerd switched from bullseye to bookworm which has `glibc 2.36`

**Comment by bart0sh** [comment]
> The binaries that we use in testing are from the main branch of containerd. So getting a static binary from the release is not an option.

Correct. However, we can still statically build containerd binaries or ask containerd maintainers to publish prebuilt static binaries from their main branch. With dynamically built executables we're going to have this kind of issues in future.

**Comment by kannon92** [comment]
/reopen

Looks like https://github.com/kubernetes/test-infra/pull/31447 did not fix this so reopening the issue.

**Comment by bart0sh** [comment]
second attempt to fix it: https://github.com/kubernetes/test-infra/pull/31463

**Comment by kannon92** [comment]
Nice work @bart0sh!

**Comment by bart0sh** [comment]
Thank you. 

[ci-cos-cgroupv1-inplace-pod-resize-containerd-main-e2e-gce-serial](https://testgrid.k8s.io/sig-node-containerd#cos-cgroupv1-inplace-pod-resize-containerd-e2e-serial) is not triggered yet. Next run will be tomorrow. I hope it's fixed.
