### ISSUE TITLE
Move SidecarContainers featureGate checking from Filter to PreFilter in scheduler

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes/kubernetes#121375]
/kind feature

/sig scheduling

Filter will return `framework.UnschedulableAndUnresolvable` for all nodes when `f.enableSidecarContainers` is `false` and `hasRestartableInitContainer(pod)` is `true`. 
https://github.com/kubernetes/kubernetes/blob/2c10d9cacb0626219753a3df28a76b6bfae2b34a/pkg/scheduler/framework/plugins/noderesources/fit.go#L255-L263

This can be done is PreFilter. Executing this code in the filter will cause it to be repeated tens of times, with the worst-case scenario being repeated thousands of times. Maybe we should move this to PreFilter like:
```
// PreFilter invoked at the prefilter extension point.
func (f *Fit) PreFilter(ctx context.Context, cycleState *framework.CycleState, pod *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
	if !f.enableSidecarContainers && hasRestartableInitContainer(pod) {
		// Scheduler will calculate resources usage for a Pod containing
		// restartable init containers that will be equal or more than kubelet will
		// require to run the Pod. So there will be no overbooking. However, to
		// avoid the inconsistency in resource calculation between the scheduler
		// and the older (before v1.28) kubelet, make the Pod unschedulable.
		return nil, framework.NewStatus(framework.UnschedulableAndUnresolvable, "Pod has a restartable init container and the SidecarContainers feature is disabled")
	}
	cycleState.Write(preFilterStateKey, computePodResourceRequest(pod))
	return nil, nil
}
```

**Comment by AxeZhan** [comment]
Sounds reasonable to me :) I think you can go ahead and file a pr for this.

**Comment by KunWuLuan** [comment]
> Sounds reasonable to me :) I think you can go ahead and file a pr for this.

Sure.

**Comment by KunWuLuan** [comment]
@lowang-bh Hi, If you don't mind, I can try to do this.
