### ISSUE TITLE
Metric etcd_server_health_success reporting zero after kubernetes upgrade

### ISSUE THREAD

**Issue by cmotta2016** [kubernetes/kubernetes#121328]
### What happened?

After upgrading Kubernetes from `1.25.11` to `1.25.12` the metric `etcd_server_health_success` stops to increment. Now, it's reporting only zero value.
![Screenshot 2023-10-18 at 15 25 02](https://github.com/kubernetes/kubernetes/assets/26969641/c5a31ec0-94f7-46e3-a424-631614d34604)
![Screenshot 2023-10-18 at 15 25 33](https://github.com/kubernetes/kubernetes/assets/26969641/5bea0ebc-2abe-4274-8a8c-8edfb052ed70)

### What did you expect to happen?

Metric reporting non-zero value as at `1.25.11` Kubernetes version.

### How can we reproduce it (as minimally and precisely as possible)?

Running Kubernetes at the `1.25.11` version, check the metric value using Prometheus. So, upgrade the Kubernetes version to `1.25.12` and recheck the metric.

### Anything else we need to know?

We're using kOps at the `1.25.4` version and the etcd at the `3.5.7` version.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.25.12
Server Version: v1.25.12
```

</details>

### Cloud provider

<details>
AWS
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by jmhbnz** [comment]
Discussed during etcd triage meeting.  Relates to:
- https://github.com/kubernetes/kubernetes/pull/119039
- https://github.com/kubernetes/kubernetes/pull/118460

/assign @serathius
