### ISSUE TITLE
[Flaking Test] integration TestEncryptionConfigHotReload

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121313]
### Which jobs are flaking?

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1714423851380641792

k8s.io/kubernetes/test/integration/controlplane: transformation expand_less | 14m1s
- Failed;  === RUN   TestEncryptionConfigHotReload

### Which tests are flaking?

TestEncryptionConfigHotReload

### Since when has it been flaking?

When I see this flake, 10-09 is the first one.(But the job history in the testgrid only started from 10-03)

### Testgrid link

https://testgrid.k8s.io/sig-release-master-blocking#integration-master

### Reason for failure (if possible)

> I1018 00:01:01.197994  101086 controller.go:624] quota admission added evaluator for: namespaces
>     kms_transformation_test.go:578: unexpected metrics diff (-want +got):   []string{
>         + 	`apiserver_encryption_config_controller_automatic_reload_failures_total{apiserver_id_hash="sha256:3c607df3b2bf22c9d9f01d5314b4bbf411c48ef43ff44ff29b1d55b41367c795"} 1`,
>         + 	`apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds{apiserver_id_hash="sha256:3c607df3b2bf22c9d9f01d5314b4bbf411c48ef43ff44ff29b1d55b41367c795",status="failure"} FP`,
>           	"apiserver_encryption_config_controller_automatic_reload_last_tim"...,
>           	"apiserver_encryption_config_controller_automatic_reload_success_"...,
>           }

### Anything else we need to know?

some PR that may be related: https://github.com/kubernetes/kubernetes/pull/120544

### Relevant SIG(s)

/sig auth
/cc @ritazh

**Comment by pacoxu** [comment]
/cc @kubernetes/ci-signal 
failed two times in recent 3 runs: https://testgrid.k8s.io/sig-release-master-blocking#integration-master

**Comment by enj** [comment]
/reopen

@nilekhc as of 015297a5776aa036c334c89740f89f74cb83190c this is still [flaking](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-integration-master/1716787771676299264).
