### ISSUE TITLE
Kubelet not create Symlink for configmap volume after restarted

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#121472]
### What happened?

When kubelet is creating configmap volume  for a pod, it finished writing `timestamp` dir and made symlink to `..data`. At the same time, the kubelet is restarted, unfortunately the configmap item symlink is not created.

The restarted kubelet will try to `SetUpAt` configmap,  `no update required for target directory`.

### What did you expect to happen?

Kubelet should create absent symlink for configmap volume.

### How can we reproduce it (as minimally and precisely as possible)?

1. We can hack kubelet to help reproduce it: sleep some time before `createUserVisibleFiles` https://github.com/kubernetes/kubernetes/compare/master...chenk008:kubernetes:test_kubelet_configmap_writer`
2. stop kubelet and start official kubelet
3. kubelet will skip to create symlink for UserVisibleFiles

### Kubernetes version

<details>

```console
$ kubectl version
# Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3", GitCommit:"", GitTreeState:"clean", BuildDate:"2023-10-19T07:10:40Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by ndixita** [comment]
/sig storage

This seems like an issue for sig storage. Can someone take a look and confirm?

**Comment by ndixita** [comment]
@chenk008 Can you please add the version details as well?
