### ISSUE TITLE
Service account token projected volume validation should call `validateLocalNonReservedPath` on the token path

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#121415]
> also call `validateLocalNonReservedPath` on `source.ClusterTrustBundle.Path` to catch paths the kubelet will reject (like absolute paths, paths containing backsteps, etc):

https://github.com/kubernetes/kubernetes/blob/f7cb8a5e8a860df643e143cde54d34080372b771/pkg/volume/util/atomic_writer.go#L252-L264

> configmap, secret, and downwardAPI already call this. projected token does not (@enj, can you open an issue to ratchet validate that as well)

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/113374#discussion_r1365908487_

**Comment by fcbrule** [comment]
Hello, I'm new here. Can I try solving this? it seems like a good first issue

**Comment by fcbrule** [comment]
"Service account token projected volume" - which file am I supposed to be looking for if I am trying to understand this?

**Comment by liggitt** [comment]
> Hello, I'm new here. Can I try solving this? it seems like a good first issue

sure, context is https://github.com/kubernetes/kubernetes/pull/113374#discussion_r1365908487

the change is needed here:
https://github.com/kubernetes/kubernetes/blob/2c53de96e4e68d81080034a4b2e39490cad30a28/pkg/apis/core/validation/validation.go#L1146-L1157

We have to tolerate existing pods / pod specs that fail this validation, so we should only do this additional validation on create or if the existing object passes this validation. To do this:
1. Add an `AllowNonLocalProjectedTokenPath bool` field to `PodValidationOptions`
```diff
diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
index 3a56f256b83..96ded74fc97 100644
--- a/pkg/apis/core/validation/validation.go
+++ b/pkg/apis/core/validation/validation.go
@@ -3812,6 +3814,8 @@ type PodValidationOptions struct {
 	AllowInvalidTopologySpreadConstraintLabelSelector bool
 	// Allow node selector additions for gated pods.
 	AllowMutableNodeSelectorAndNodeAffinity bool
+	// Allow projected token volumes with non-local paths
+	AllowNonLocalProjectedTokenPath bool
 	// The top-level resource being validated is a Pod, not just a PodSpec
 	// embedded in some other resource.
 	ResourceIsPod bool
```

2. In `GetValidationOptionsFromPodSpecAndMeta`, initialize that field to false, and then *conditionally* override it to `true` if `oldPodSpec` is non-nil and has a projected token volume path that fails `ValidateLocalNonReservedPath(path, nil)` (will have to export the `validateLocalNonReservedPath` function to check this)

https://github.com/kubernetes/kubernetes/blob/2c53de96e4e68d81080034a4b2e39490cad30a28/pkg/api/pod/util.go#L356-L371

3. In `validateProjectionSources`, if `AllowNonLocalProjectedTokenPath` is false, call the validation on the path:
```diff
diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
index 3a56f256b83..96ded74fc97 100644
--- a/pkg/apis/core/validation/validation.go
+++ b/pkg/apis/core/validation/validation.go
@@ -1152,6 +1152,8 @@ func validateProjectionSources(projection *core.ProjectedVolumeSource, projectio
 			}
 			if source.ServiceAccountToken.Path == "" {
 				allErrs = append(allErrs, field.Required(fldPath.Child("path"), ""))
+			} else if !opts.AllowNonLocalProjectedTokenPath {
+				allErrs = append(allErrs, validateLocalNonReservedPath(source.ServiceAccountToken.Path, fldPath.Child("path"))...)
 			}
 		}
 		if numSources > 1 {
```

**Comment by Taction** [comment]
Hi, I'd like to work on this if there is no one is proceeding on.

/assign
