### ISSUE TITLE
[Failing-Test][sig-network] DualStack Host IP [Feature:PodHostIPs] when creating a Pod, it has no PodHostIPs feature should create pod with hostNetwork, add host ips is empty

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121424]
### Which jobs are failing?

4 other Test Failures in ci-crio-cgroupv1-node-e2e-features.

### Which tests are failing?

Test [E2eNode Suite.[It] [sig-network] DualStack Host IP [NodeFeature:PodHostIPs] [Feature:PodHostIPs] when creating a Pod, it has no PodHostIPs feature should create pod with hostNetwork, add host ips is empty [sig-network]](https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features) has failed 61 times (no passing result found). Earliest failure found at commit/239537e74 (Thu Oct 19 21:41 PDT).

### Since when has it been failing?

https://github.com/kubernetes/kubernetes/pull/120257
/cc @wzshiming

### Testgrid link

https://testgrid.k8s.io/sig-node-cri-o#ci-crio-cgroupv1-node-e2e-features

### Reason for failure (if possible)

{ failed [FAILED] Error creating Pod: pods "pod-dualstack-host-ips9ddb9810-134c-4d35-a0c6-84950abdef25" is forbidden: violates PodSecurity "restricted:latest": host namespaces (hostNetwork=true)
In [It] at: test/e2e/framework/pod/pod_client.go:99 @ 10/23/23 01:38:06.024
}

### Relevant SIG(s)

/sig network node

**Comment by akhilerm** [comment]
https://testgrid.k8s.io/sig-node-containerd#pull-containerd-node-e2e is also failing on these tests

**Comment by aojea** [comment]
the test has a bug, it checks the contrary

**Comment by aojea** [comment]
https://github.com/kubernetes/kubernetes/pull/121445, let's start over, 1 commit for the e2e test, other for the promotion, and let's validate everything is alright before merging
