### ISSUE TITLE
Docs Suggestion - Downloading cluster/saltbase for releases

### ISSUE THREAD

**Issue by mbabker** [kubernetes/kubernetes#12148]
In some examples (such as the [NFS example](http://kubernetes.io/v1.0/examples/nfs/README.html)), the docs note that the ability to create privileged containers is required and to edit `cluster/saltbase/pillar/privilege.sls` to achieve this.  However, this file is [stripped from packaged releases](https://github.com/GoogleCloudPlatform/kubernetes/blob/v1.0.1/build/common.sh#L760) so the example is a little complicated to work with if you aren't running from git.

Might I suggest a note on downloading the saltbase cluster data if you are using a packaged release be added to the documentation?  Once I did this, I was able to get the NFS server pod to launch without issue.

**Comment by mbforbes** [comment]
Privileged containers is a rough spot that could use clarification and work throughout, I think

**Comment by four43** [comment]
Looking at the master branch, it seems this is the default now? Docs could use some updating it sounds like.

Doc in question: https://github.com/kubernetes/kubernetes/blob/d680d11959357a29ee729e3cbfc3592bd8c06eb5/examples/nfs/README.md

Privileged already enabled? https://github.com/kubernetes/kubernetes/blob/master/cluster/saltbase/pillar/privilege.sls

**Comment by kargakis** [comment]
@kubernetes/sig-docs-maintainers 
/sig docs

**Comment by ahmetb** [comment]
This issue has been inactive for quite a while. I don't think we have the NFS example anymore.

We should close and open similar issues on kubernetes/kubernetes.github.io.

**Comment by chenopis** [comment]
IMHO, since all the docs now live in the k8s.io repo, any docs issue pre-2017 should be closed.
