### ISSUE TITLE
e2e tests occasionally fail due to OutOfpods

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#121475]
### Which jobs are flaking?

pull-kubernetes-e2e-kind
example: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121368/pull-kubernetes-e2e-kind/1716714341606100992

### Which tests are flaking?

Example, but does not seem to be specific to the test: "Using a pod failure policy to not count some failures towards the backoffLimit".

### Since when has it been flaking?

First time noticed, but potentially for long if this is very rare. 

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-e2e-kind

### Reason for failure (if possible)

The 3rd pod `pod-disruption-failure-ignore-3-mpvmm` for the job could not get assigned resources by kubelet to start.

See kubelet logs from kind-worker2: https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/121368/pull-kubernetes-e2e-kind/1716714341606100992/artifacts/kind-worker2/kubelet.log

Relevant lines:
```
Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.115368     248 kubelet.go:2392] "SyncLoop ADD" source="api" pods=["job-712/pod-disruption-failure-ignore-3-mpvmm"]
Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.115597     248 topology_manager.go:215] "Topology Admit Handler" podUID="a6c891f0-3b56-4c19-b5c8-c29ad74a5d36" podNamespace="job-712" podName="pod-disruption-failure-ignore-3-mpvmm"
Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.116862     248 predicate.go:168] "Predicate failed on Pod" pod="job-712/pod-disruption-failure-ignore-3-mpvmm" err="Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110"
Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.117361     248 status_manager.go:227] "Syncing updated statuses"
Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.117655     248 event.go:376] "Event occurred" object="job-712/pod-disruption-failure-ignore-3-mpvmm" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="OutOfpods" message="Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110"
```

Due to hitting the limit the pod is marked as `Failed` by kubelet which is unexpected by the test.

### Relevant SIG(s)

/sig apps

**Comment by mimowo** [comment]
I suppose the reason is that we preassigning the `NodeName` instead of asking scheduler to do so. This might be related to https://github.com/kubernetes/kubernetes/issues/113907

**Comment by mimowo** [comment]
FYI @alculquicondor @soltysh

**Comment by aojea** [comment]
we should not preassign, is that required by this test?

**Comment by mimowo** [comment]
> we should not preassign, is that required by this test?

What is required is that all pods run on the same node, because we use HostPath to communicate some information between recreations of a pod, and between replicas for indexed job.

> Do you have a link to those tests?

All tests in this file: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/apps/job.go, which use the `NewTestJobOnNode` function are affected I think. 

Here is the problematic place: https://github.com/kubernetes/kubernetes/blob/9ae55e98868d78a7103358e1feb7d15b8403d0fa/test/e2e/framework/job/fixtures.go#L83.
I suppose using a `NodeSelector` instead of setting `NodeName` directly might already help, because it the decision will go via scheduler which will delay the scheduling until node has enough capacity.

**Comment by mimowo** [comment]
FYI @alculquicondor for input on the proposed solution to use `NodeSelector` or another alternative

**Comment by aojea** [comment]
hmm ,I don't like why this is this way https://github.com/kubernetes/kubernetes/commit/c84a371f3d475f20fc85819edc03475d6b5b3c9c , if the test need to be serialized it must be tagged as Serial, but making this assumptions on e2e tests is not great

**Comment by mimowo** [comment]
> hmm ,I don't like why this is this way [c84a371](https://github.com/kubernetes/kubernetes/commit/c84a371f3d475f20fc85819edc03475d6b5b3c9c) , if the test need to be serialized it must be tagged as Serial, but making this assumptions on e2e tests is not great

Yeah, I would very much want to avoid making the test serial. I can see two options we have:
1. short term - replace the `NodeName` with `NodeSelector`. IIUC, this will already keep the pods unscheduled until there is capacity. With the timeout of 15min as we have for job it is very unlikely the pod would wait that long. Currently, it gets assigned but fails.
2. refactor the tests so that the state is kept on a mounted volume obtained by PVC. This should eliminate the need for the pods to run on the same node. 

Since 2. is slightly more involving, it might be good to have 1. merged.

**Comment by aojea** [comment]
> 2\. refactor the tests so that the state is kept on a mounted volume obtained by PVC. This should eliminate the need for the pods to run on the same node.

you can not assume the e2e test will have dynamic PV working, if you want to assume that you have to tag the test so jobs can filter based on the tag

**Comment by alculquicondor** [comment]
Let's start with the NodeSelector

**Comment by alculquicondor** [comment]
Actually, that wouldn't help, because currently the Job controller just recreates the Pod. With a node selector, it would just be scheduler that is now "busy-waiting" and we would still hit a timeout.

Can the implementation be changed to save the information in a ConfigMap? It probably requires a specialized container image. Unless a ConfigMap can be mounted as readwrite?

**Comment by mimowo** [comment]
> Actually, that wouldn't help, because currently the Job controller just recreates the Pod. With a node selector, it would just be scheduler that is now "busy-waiting" and we would still hit a timeout.

Interesting, so I greped the logs for `job-712.*OutOfpods` and only found this pod in this line:

Oct 24 07:42:50 kind-worker2 kubelet[248]: I1024 07:42:50.117655     248 event.go:376] "Event occurred" object="job-712/pod-disruption-failure-ignore-3-mpvmm" fieldPath="" kind="Pod" apiVersion="v1" type="Warning" reason="OutOfpods" message="Node didn't have enough resource: pods, requested: 1, used: 110, capacity: 110"

Which should not be that bad, because we have backoffLimit=6, yet the job failed with `BackoffLimitExceeded`. So, maybe some other failures were incrementing the counter wrongly. I don't know at the moment.

**Comment by mimowo** [comment]
> Which should not be that bad, because we have backoffLimit=6, yet the job failed with BackoffLimitExceeded. So, maybe some other failures were incrementing the counter wrongly. I don't know at the moment. 

My mistake here. The job has actually `backoffLimit=0`: https://github.com/kubernetes/kubernetes/blob/f652e61ca0e338a942fa2498ce383001943840ac/test/e2e/apps/job.go#L196. 

This explains why the job failed with BackoffLimitExceeded after seeing `pod-disruption-failure-ignore-3-mpvmm` failing with admission error by kubelet. Meaning 137 exit code, but without DisruptionTarget condition. So it was counted as failed and killed the job.

So, I think in this case adding the `NodeSelector` would actually help. It would not help, if `OutOfPods` was for a prolonged amount of time to cause test timeout. However, the test timeout is 15min. Also, there is no indication that kubelet was in the `OutOfPods` time for long. A single event was enough to cause the pod fail with 137, and this single failure caused the job failure.

As for long term solution using config maps - yes, it could work, but I think it's better to do a quick fix to minimize the flakes before release.

**Comment by alculquicondor** [comment]
I agree. Thanks for investigating!
