### ISSUE TITLE
Service account token projected volume validation should require the token path to be unique

### ISSUE THREAD

**Issue by enj** [kubernetes/kubernetes#121414]
> preexisting, but @enj, mind opening an issue to track not validating the token path is unique (in the `allPaths` accumulator)
> 
> depending on what happens today, we would either warn (if current pods "succeed" with last-one-wins behavior) or fail validation in a ratcheting way (if current pods fail to set up volumes successfully)

_Originally posted by @liggitt in https://github.com/kubernetes/kubernetes/pull/113374#discussion_r1365887046_

**Comment by Peac36** [comment]
Hey @liggitt, is this still an issue? If so, what are we supposed to do if the path is not unique - a warning or validation error? 

Any additional information would appreciated as I'm still learning my way around.

**Comment by liggitt** [comment]
Yes, it's still an issue.

Whether we warn or error depends on what the current behavior is with duplicated paths. The first step is to investigate the behavior with a volume with a duplicated path for a service account token and some other item and report back here. If pods start successfully and the last item wins, we should just warn. If pods fail to start, we can error in a *ratcheting* way:

1. error if a new object attempts to be created with a duplicated path
2. error if an existing item without a duplicated path tries to update to have a duplicated path

**Comment by Peac36** [comment]
Hey @liggitt, I've just tested it, and looks like in this case the pod started successfully and the duplicated path was overwritten with the last item so it should be a warning.

**Comment by thockin** [comment]
I am worried that a warning which doesn't always warn will give a false
sense of security. I think a condition indicating an actual collision would
be better, no? I am not AGAINST a warning, but it's a partial answer
