### ISSUE TITLE
daemonset pod cannot be created quickly, when some nodes are added to the cluster and controller-manager OOM will be triggered

### ISSUE THREAD

**Issue by xigang** [kubernetes/kubernetes#121474]
### What happened?

ref: https://github.com/kubernetes/kubernetes/issues/112319

【Question】
question 1:
Now our k8s cluster has 5k nodes. When we expand some nodes in the k8s cluster, the daemonset pod cannot be created quickly. It takes about 2 hours to create the daemonset pod.

Add a new node daemonset pod startup time:

![image](https://github.com/kubernetes/kubernetes/assets/3377677/ef2d7885-1ce4-4e90-9340-205b00093f5f)

![image](https://github.com/kubernetes/kubernetes/assets/3377677/5b0e4cb4-1fa2-470e-8eea-bb6e92c1002d)

question 2:
Look at the monitoring of `kube-controller-manager` Memory usage reaches 900GB and triggers OOM.

`kube-controller-manager` memory usage monitoring:

![image](https://github.com/kubernetes/kubernetes/assets/3377677/6b628b11-1676-4862-9616-07f99554ce36)

【Solution】

In a cluster with 5K nodes, we found that when the daemonset controller watches update `Node` events, due to the large number of `Node` events, the `NodeInformer` [pendingNotifications](https://github.com/kubernetes/kubernetes/blob/3e438c54a77ccf7b9e0aff924eb977031099cc2f/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L876) ring buffer has more `Node` events to be processed, resulting in the Node EventHandler's `Add/Update` callback function being processed slowly. Affects the creation of daemonset pod and `kube-controller-manager` `OOM` issues.

<img width="1208" alt="image" src="https://github.com/kubernetes/kubernetes/assets/3377677/7735d581-0a5a-4ff2-92cb-a61acf2ec84a">

We optimized the [shouldIgnoreNodeUpdate](https://github.com/kubernetes/kubernetes/blob/1d9e1e6d56cbd5c9d04ba25cccf184a973056a79/pkg/controller/daemon/daemon_controller.go#L693) logic in the [UpdateNode](https://github.com/kubernetes/kubernetes/blob/1d9e1e6d56cbd5c9d04ba25cccf184a973056a79/pkg/controller/daemon/daemon_controller.go#L693) method of the daemonset controller `NodeInformer` to reduce unnecessary Node event processing:

original code:
```
func shouldIgnoreNodeUpdate(oldNode, curNode v1.Node) bool {
	if !nodeInSameCondition(oldNode.Status.Conditions, curNode.Status.Conditions) {
		return false
	}
	oldNode.ResourceVersion = curNode.ResourceVersion
	oldNode.Status.Conditions = curNode.Status.Conditions
	return apiequality.Semantic.DeepEqual(oldNode, curNode)
}
```

optimized code:
```
func shouldIgnoreNodeUpdate(oldNode, curNode v1.Node) bool {
	if !nodeInSameCondition(oldNode.Status.Conditions, curNode.Status.Conditions) {
		return false
	}
	oldNode.ResourceVersion = curNode.ResourceVersion
	oldNode.Status.Conditions = curNode.Status.Conditions
+	oldNode.Status.Images = curNode.Status.Images
+	oldNode.Status.NodeInfo = curNode.Status.NodeInfo
+	oldNode.Status.Capacity = curNode.Status.Capacity
+	oldNode.Status.Allocatable = curNode.Status.Allocatable
	return apiequality.Semantic.DeepEqual(oldNode, curNode)
}

func (dsc *DaemonSetsController) updateNode(old, cur interface{}) {
	oldNode := old.(*v1.Node)
	curNode := cur.(*v1.Node)
+	oldNodeCopy := oldNode.DeepCopy()
+	curNodeCopy := curNode.DeepCopy()
	if shouldIgnoreNodeUpdate(*oldNodeCopy, *curNodeCopy) {
		return
	}

	dsList, err := dsc.dsLister.List(labels.Everything())
	if err != nil {
		klog.V(4).Infof("Error listing daemon sets: %v", err)
		return
	}
	// TODO: it'd be nice to pass a hint with these enqueues, so that each ds would only examine the added node (unless it has other work to do, too).
	for _, ds := range dsList {
		_, oldShouldSchedule, oldShouldContinueRunning, err := dsc.nodeShouldRunDaemonPod(oldNode, ds)
		if err != nil {
			klog.Errorf("Error old node %s should run daemon %s/%s pod: %v", oldNode.Name, ds.Namespace, ds.Name, err)
			continue
		}
		_, currentShouldSchedule, currentShouldContinueRunning, err := dsc.nodeShouldRunDaemonPod(curNode, ds)
		if err != nil {
			klog.Errorf("Error current node %s should run daemon %s/%s pod: %v", oldNode.Name, ds.Namespace, ds.Name, err)
			continue
		}
		if (oldShouldSchedule != currentShouldSchedule) || (oldShouldContinueRunning != currentShouldContinueRunning) {
			klog.V(4).Infof("enqueueing daemon set %s/%s for node %v.", ds.Namespace, ds.Name, curNode.Name)
			dsc.enqueueDaemonSet(ds)
		}
	}
}
```

【Effect】
After adding some nodes to the cluster, the daemonset pod can be quickly created, and the `kube-controller-manager` memory is controlled at about 20GB.

 
![image](https://github.com/kubernetes/kubernetes/assets/3377677/5c9e3a0a-13ac-45c6-b722-d8a1c802b14b)

<img width="1603" alt="image" src="https://github.com/kubernetes/kubernetes/assets/3377677/942d072f-d78f-4cde-a966-c00193c10e19">

### What did you expect to happen?

1. When adding some nodes to the k8s cluster, daemonset pod can be created quickly because the node requires CNI daemonset pod.
2.  kube-controller-manager needs to use less memory to prevent frequent `OOM`triggers.
3. We have optimized the `shouldIgnoreNodeUpdate` logic in the `updateNode` method of the daemonset controller `NodeInformer` to reduce unnecessary `Node `event processing. Is this optimization logic possible?

### How can we reproduce it (as minimally and precisely as possible)?

When the k8s cluster size reaches 5k, add new nodes to the cluster.

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17+", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ uname -a
4.18.0-2.4.3.x86_64 #1 SMP Wed Apr 6 06:31:51 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by xigang** [comment]
cc @leilajal @sttts @cici37 @wojtek-t @sxllwx

**Comment by nayihz** [comment]
You should provide some information about kubernetes version.

**Comment by xigang** [comment]
> You should provide some information about kubernetes version.

kubernetes version: 1.17  commit id: 8885823091bd6419bb2b0b83617a0a6fe0aed8cd

**Comment by neolit123** [comment]
> > You should provide some information about kubernetes version.
> 
> kubernetes version: [1.17 commit id: 8885823091bd6419bb2b0b83617a0a6fe0aed8cd](https://github.com/kubernetes/kubernetes/tree/v1.17.0)

1,17 is out of support:
https://kubernetes.io/releases/

**Comment by neolit123** [comment]
> In a cluster with 5K node

/sig scalability
for triage.

**Comment by xigang** [comment]
> > > You should provide some information about kubernetes version.
> > 
> > 
> > kubernetes version: [1.17 commit id: 8885823091bd6419bb2b0b83617a0a6fe0aed8cd](https://github.com/kubernetes/kubernetes/tree/v1.17.0)
> 
> 1,17 is out of support: https://kubernetes.io/releases/

@neolit123  1.18 also has the same problem.
https://github.com/kubernetes/kubernetes/blob/v1.28.0/pkg/controller/daemon/daemon_controller.go#L686

**Comment by nayihz** [comment]
Does `node.Status.Images/node.Status.NodeInfo/node.Status.Capacity/node.Status.Allocatable` will affect the daeomonset pod's creation and eviction? If not, maybe it's better to ignore these kind of node update events to decrease the pressure of daemonset controller.
/sig apps

**Comment by xigang** [comment]
> Does `node.Status.Images/node.Status.NodeInfo/node.Status.Capacity/node.Status.Allocatable` will affect the daeomonset pod's creation and eviction? If not, maybe it's better to ignore these kind of node update events to decrease the pressure of daemonset controller. /sig apps

The daemonset controller logic does not use these node status. so these states are ignored.(node.Status.Images/node.Status.NodeInfo/node.Status.Capacity/node.Status.Allocatable)

**Comment by sxllwx** [comment]
nit: 
```
func (dsc *DaemonSetsController) updateNode(old, cur interface{}) {
	oldNode := old.(*v1.Node)
	curNode := cur.(*v1.Node)
+	oldNodeCopy := oldNode.DeepCopy() // There is no need to perform DeepCopy here. ShadowCopy has already been performed in the following code.
+	curNodeCopy := curNode.DeepCopy() // ...
	if shouldIgnoreNodeUpdate(*oldNode, *curNode) {
		return
	}
        ....
```

**Comment by xigang** [comment]
> Can you provide a profile of the heap when memory usage is high?



> Can you provide a profile of the heap when memory usage is high?

I will be profiling in production environment tomorrow.

**Comment by xigang** [comment]
> Can you provide a profile of the heap when memory usage is high?



> Can you provide a profile of the heap when memory usage is high?

controllermanager profile:

**Comment by aojea** [comment]
So, this is one of the reasons people should not do heavy processing on the informers EventHandlers, it blocks the DeltaFIFo queue and increase the memory and drops the performance.

I think that optimizing the `shouldIgnoreNodeUpdate` to make a more targeted diff on the Node instead of compare the whole node object except Conditions and ResourceVersions will be a quick win.

If my reading of the code is correct, just adding or removing an annotation will make the handler to process that node.

/cc @wojtek-t 

for scalability

**Comment by sxllwx** [comment]
> > Can you provide a profile of the heap when memory usage is high?
> 
> @sxllwx controllermanager profile:
> 
> [kube-controller-manager-heap.txt](https://github.com/kubernetes/kubernetes/files/13167055/kube-controller-manager-heap.txt)
> 
> ![image](https://user-images.githubusercontent.com/3377677/278041674-c79fe734-f5c3-436a-8753-1e4dc174b294.png)

Is this your CPU Profile? Can it be provided together?

**Comment by sxllwx** [comment]
I opened the Heap-Profile you provided and didn't get your screenshot.

<img width="738" alt="image" src="https://github.com/kubernetes/kubernetes/assets/11829907/ef399b7c-5b28-4ec1-9a5b-37f7f06e5297">

Based on the information I saw, I can only confirm that a large amount of Events are pouring in, but I cannot be sure that the **RingBuffer** holds a large amount of memory.

**Comment by xigang** [comment]
> I opened the Heap-Profile you provided and didn't get your screenshot.
> 
> <img alt="image" width="738" src="https://user-images.githubusercontent.com/11829907/278208396-ef399b7c-5b28-4ec1-9a5b-37f7f06e5297.png">
> Based on the information I saw, I can only confirm that a large amount of Events are pouring in, but I cannot be sure that the **buffer.RingGrowing** holds a large amount of memory.

Now the controllermanager in the production environment does not enable profliing, but we can analyze that the controllermanger OOM is caused by too many buffer.RingGrowing Node events.

**Comment by sxllwx** [comment]
@aojea @wojtek-t 
Should we consider changing the action of distribute Objects here to be concurrent?

https://github.com/kubernetes/kubernetes/blob/a1809ffae377f3abbae12b137073ca4c473743cd/staging/src/k8s.io/client-go/tools/cache/shared_informer.go#L773-L789

**Comment by liggitt** [comment]
A few things:

1. The current state of `shouldIgnoreNodeUpdate` is mutating the old node (with `oldNode.ResourceVersion = curNode.ResourceVersion` and `oldNode.Status.Conditions = curNode.Status.Conditions`). That is modifying the old node object in the shared informer cache, and is **absolutely** not permitted. That should be tripping the cache mutation detector in e2e runs... I don't know why it isn't. That needs a separate issue to fix.
2. Excluding more things from the node comparison is one way to scope down `shouldIgnoreNodeUpdate`, but will definitely require copying the old node object, which is expensive to do. I *think* the only things the daemonset controller pays attention to in the node are the 1) name, 2) labels, 3) taints. The name is immutable, so checking if the labels or taints changed seems like a cheaper way to implement `shouldIgnoreNodeUpdate`

**Comment by liggitt** [comment]
> @liggitt @aojea @wojtek-t
> Should we consider changing the action of distribute Objects here to be concurrent?

Definitely not, that would break most users of this library. If listeners want concurrency, they can make their add/update/delete handler add the item to a queue and process it asynchronously.

**Comment by nayihz** [comment]
> 1. That is modifying the old node object in the shared informer cache, and is **absolutely** not permitted

`oldNode, curNode` is passed by value but not pointer in `func shouldIgnoreNodeUpdate(oldNode, curNode v1.Node) bool ` . So I don't think it will modify the old node object.



> 2\. I _think_ the only things the daemonset controller pays attention to in the node are the 1) name, 2) labels, 3) taints.

Agree. IIUC, only labels and taints will affect the daeomonset pod's creation and eviction.

**Comment by sxllwx** [comment]
> The current state of shouldIgnoreNodeUpdate is mutating the old node (with oldNode.ResourceVersion = curNode.ResourceVersion and oldNode.Status.Conditions = curNode.Status.Conditions). That is modifying the old node object in the shared informer cache, and is absolutely not permitted. That should be tripping the cache mutation detector in e2e runs... I don't know why it isn't. That needs a separate issue to fix.

The cache status is not changed because this code performs shadowCopy.

https://github.com/kubernetes/kubernetes/blob/94ec99d4c25e16b6f3c9239d9e124be9d45c161b/pkg/controller/daemon/daemon_controller.go#L698C38-L700

@liggitt

**Comment by liggitt** [comment]
ah, ok, and the two fields it happened to change were not inside pointers internally

**Comment by xigang** [comment]
> A few things:
> 
> 1. The current state of `shouldIgnoreNodeUpdate` is mutating the old node (with `oldNode.ResourceVersion = curNode.ResourceVersion` and `oldNode.Status.Conditions = curNode.Status.Conditions`). That is modifying the old node object in the shared informer cache, and is **absolutely** not permitted. That should be tripping the cache mutation detector in e2e runs... I don't know why it isn't. That needs a separate issue to fix.
> 2. Excluding more things from the node comparison is one way to scope down `shouldIgnoreNodeUpdate`, but will definitely require copying the old node object, which is expensive to do. I _think_ the only things the daemonset controller pays attention to in the node are the 1) name, 2) labels, 3) taints. The name is immutable, so checking if the labels or taints changed seems like a cheaper way to implement `shouldIgnoreNodeUpdate`

@liggitt  Should we optimize `shouldIgnoreNodeUpdate` function and compare node labels and taints to solve this problem?

**Comment by liggitt** [comment]
that would be my recommendation

**Comment by wojtek-t** [comment]
Sorry - catching up on it.

I guess I have two thoughs - we should consider short-term mitigation and a medium-term fix:

1. For short-term mitigation, I agree with @liggitt - changing shouldIgnoreNodeUpdate to just compare labels & taints seems like a reasonable mitigation.

2. For medium-term mitigation, we should rewrite the controller to the pattern where event-handler is as cheap as possible by simply putting stuff into queue. The queue then gives us deduplication for free and all the logic is then happening in the workers.

@xigang - can you please open a PR for (1) and a separate issue for (2)? Would you be able to work on (2) too?

**Comment by nayihz** [comment]
> 1. For short-term mitigation, I agree with @liggitt - changing shouldIgnoreNodeUpdate to just compare labels & taints seems like a reasonable mitigation.

I've send a small pr for this. Please take a look if you have time. @wojtek-t

**Comment by xigang** [comment]
> Sorry - catching up on it.
> 
> I guess I have two thoughs - we should consider short-term mitigation and a medium-term fix:
> 
> 1. For short-term mitigation, I agree with @liggitt - changing shouldIgnoreNodeUpdate to just compare labels & taints seems like a reasonable mitigation.
> 2. For medium-term mitigation, we should rewrite the controller to the pattern where event-handler is as cheap as possible by simply putting stuff into queue. The queue then gives us deduplication for free and all the logic is then happening in the workers.
> 
> @xigang - can you please open a PR for (1) and a separate issue for (2)? Would you be able to work on (2) too?

@wojtek-t Thank you for your reply. I can submit a PR to solve  issue (1)  and solve the medium-term issue(2) later.
