### ISSUE TITLE
file" err="failed to load Kubelet config file /etc/kubernetes/kubelet.conf, error failed to decode: no kind \"Config\" is registered for version \"v1\" in scheme \"k8s.io/kubernetes/pkg/kubelet/apis/config/scheme/scheme.go:32\"

### ISSUE THREAD

**Issue by wangqiangJN** [kubernetes/kubernetes#121467]
### What happened?

I use command line to contol kubeadm init ,but have something wrong 。

**Firstly:**
I try:
sudo kubeadm init  --pod-network-cidr=10.244.0.0/16   --kubernetes-version v1.22.2    --ignore-preflight-errors=all
and return:
The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.\
**Then** ,I found kublet is not running
then I check my kubelet log, found that:
file" err="failed to load Kubelet config file **/etc/kubernetes/kubelet.conf**, error failed to decode: **no kind \"Config\" is registered for version \"v1\" in scheme \"k8s.io/kubernetes/pkg/kubelet/apis/config/scheme/scheme.go:32\"**

How can I solve this problem? 

### What did you expect to happen?

I think the problem maybe because the apiversion and config is not match the kubelet version.

### How can we reproduce it (as minimally and precisely as possible)?

1

### Kubernetes version

<details>

```console
kubelet version 1.22.2
kubectl version 1.22.2
kubeadm version 1.22.2
unbuntu 16

```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> kubelet version 1.22.2

this is out of support.
https://kubernetes.io/releases/

a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
