### ISSUE TITLE
Move kubectl client logic into server

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/kubernetes#12143]
Doing things like `kubectl replace` requires a lot of logic in `kubectl`, such as waiting for RC to scale pods down by polling before deleting the RC itself.

Putting this in `kubectl` makes it hard to replicate in clients written in other languages to get consistent behaviour. Moving this to the api server would mean consistency across languages. 

For background, we created the Java Kubernetes client in fabric8 (https://github.com/fabric8io/kubernetes-client) & I've also contributed to the Ruby client at https://github.com/abonas/kubeclient). Having consistent behaviour means replicating undocumented functionality across clients which seems a bit dirty.

**Comment by nikhiljindal** [comment]
cc @bgrant0607

**Comment by jimmidyson** [comment]
Another prime example is `rolling-update`. The logic is all embedded in the client which means providing similar functionality in another language is hard, especially if you want to ensure that `rolling-update`s work in the same way to be interoperable.

**Comment by timothysc** [comment]
@jimmidyson If you were to put them into the apiserver, then it is no-longer stateless.  

Perhaps a better / cleaner breakdown of the api-calls makes a bit more sense here?  Ideally I would expect the to the rent to make api calls be idempotent where possible.

**Comment by jimmidyson** [comment]
@timothysc Good point. Yeah perhaps the best way is to ensure it is well documented, the problem being that things like RC names used during rolling update are implementation details that you probably don't want to expose. Or maybe it's a bad idea to try to have consistent behaviour across polyglot clients? Seems to make sense to me though.

**Comment by bgrant0607** [comment]
I agree with the principle that non-trivial functionality should be moved server-side. There are already issues filed for these:

* Rolling update: in Deployment #1743
* Resize: Scale subresource #1629
* Wait API: #1899 
* Configuration generation: #5280

We're starting on Deployment and /scale. Configuration generation will likely be added as a service layered on top of the system. We currently have no specific plans for the wait API, but it might be done as needed for the configuration layer. I imagine all external orchestrators will need something similar. cc @jackgr

If there are other specific features you'd like to move server-side, please file new issues or send PRs.

cc @lavalamp

**Comment by smarterclayton** [comment]
Keep in mind though that long running server operations in the apiserver are an antipattern, and need to be decoupled from rest style operations (wait technically gets a pass because it's a watch).

**Comment by jimmidyson** [comment]
@smarterclayton So are you saying this shouldn't be in the api server? Where should it live? Deployment config if merged? Being in the client is pretty horrible right now.

**Comment by smarterclayton** [comment]
Not that I don't agree that more of this should be simple API operations - just that the design when we move it to the API server has to be carefully considered as well.

We lack the API endpoint that represents kill this rc and stop its pods together today.  I don't disagree things like that should exist - but when we do them, we should be careful to keep our current behavior of having dumb actions that controllers make eventually consistent.

**Comment by bgrant0607** [comment]
I agree with @smarterclayton. It's not about whether we should do this, but how.

**Comment by bgrant0607** [comment]
@jimmidyson Do you have specific features in mind?

**Comment by jimmidyson** [comment]
@bgrant0607 Rolling update is the big one really, but also replace.

**Comment by bgrant0607** [comment]
Replace or scale? Your PR description mentioned replace, but you described scale ("waiting for RC to scale pods down").

**Comment by bgrant0607** [comment]
And do you care about waiting? Because scaling doesn't actually require waiting.

**Comment by jimmidyson** [comment]
Replace with cascade scales down first iirc before delete.

I'm not too bothered about waiting but I would like to be able to possibly get the progress of the request.

**Comment by smarterclayton** [comment]
Scaling an RC down to zero gracefully sounds like graceful termination of
an RC to me.  I don't think however graceful termination is flexible enough
to do that today because we just don't have the experience in using it.

On Fri, Aug 7, 2015 at 3:00 AM, Jimmi Dyson <notifications@github.com>
wrote:

> Replace with cascade scales down first iirc before delete.
>
> I'm not too bothered about waiting but I would like to be able to possibly
> get the progress of the request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/kubernetes/issues/12143#issuecomment-128617296>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by bgrant0607** [comment]
I'd really like to move to the exist-dependency model and rely on the garbage collector to clean up the pods.

Whether or not there's a way to wait for them to be cleaned up, which certainly needs graceful termination, is a separate issue.

**Comment by lavalamp** [comment]
The most obvious (to me) way of implementing these potentially long running operations, is to have an (e.g.) RollingUpdateOperation API type; you'd POST one of these to apiserver, the spec would have relevant parameters (old RC, new RC, etc), and the controller that does the work would update the status so you could watch that to see progress.

That's a lot of work to implement an operation, though.

**Comment by smarterclayton** [comment]
For lightweight operations as long as the status can be used as an atomic
checkpoint by the controller AND your spec can describe the desired state
(as per RCs and replicas), it's enough to use a controller.  For rolling
updates we've said that belongs in a deployment object.

For deletion of RCs we have graceful deletion, where we can potentially
describe the mapping between a graceful request to delete an RC.  We could
potentially add "cascade" as a delete option, which each API object could
transform to mean different things.  So if you delete with cascade, the
object is not terminated until all objects it owns are also terminated.
For RC you could manage that as "set deletion timestamp and grace period,
and also set replicas = 0".  An RC in graceful deletion with replicas 0
probably means "cascade".  An RC in graceful deletion with replicas != 0
probably means abandon.  I could imagine that not providing a grace period
for an RC means "abandon", while providing one means "shutdown gracefully
and always scale to zero".


On Tue, Aug 25, 2015 at 3:01 PM, Daniel Smith <notifications@github.com>
wrote:

> The most obvious (to me) way of implementing these potentially long
> running operations, is to have an (e.g.) RollingUpdateOperation API type;
> you'd POST one of these to apiserver, the spec would have relevant
> parameters (old RC, new RC, etc), and the controller that does the work
> would update the status so you could watch that to see progress.
>
> That's a lot of work to implement an operation, though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/kubernetes/issues/12143#issuecomment-134686632>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by jackgr** [comment]
Up to this point, the discussion has assumed that moving things server side == putting them in the api server. To @smarterclayton's point, however, that's an anti-pattern for a host of reasons. 

An alternative that we should consider is putting things into jobs kicked off by ordinary services. For example, why not create a RollingUpdate service that watches RollingUpdate objects, processes each new one when it appears by kicking off a job server side, and updates the object with job status and results, so that the caller who created it can track progress and determine the outcome of the request?

With support for third party resource types (not sure where the work on that from @brendandburns stands at this point), anyone should be able to define a new resource type that represents a point of interaction with their service. 

This pattern would work for many of the use cases being discussed here, as well as others. The api server, like all components, should be kept as small and focused as possible. From my perspective, its primary job is to manage resource lifecycles. Presumably, anything beyond that can/should be pushed out into "user space".

**Comment by nikhiljindal** [comment]
Yes thats what we do.
We have a controller manager which runs a bunch on controllers that watch apiserver resources and process them.
For ex: we have a DeploymentController, which watches Deployment objects via apiserver and carries out the rolling update process.

**Comment by jackgr** [comment]
Can you provide a pointer to the controller manager and to an example of a
controller that it managers?

Jack Greenfield | Google

**Comment by nikhiljindal** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-controller-manager/app/controllermanager.go is the controller manager.
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/deployment/deployment_controller.go is the deployment controller

**Comment by jackgr** [comment]
Thanks.

Jack Greenfield | Google

**Comment by bgrant0607** [comment]
We should move printPodBase reason summarization to kubelet.

**Comment by bgrant0607** [comment]
@jackgr moving things server side != putting the business logic in apiserver.

**Comment by jackgr** [comment]
@bgrant0607 agreed. In fact, the more we can move out of api server the better, so that it's just a REST resource manager, IMO.

**Comment by bgrant0607** [comment]
This is an impediment to 3rd-party clients. We've reached the point that we need to do this, so that ecosystem developers don't have to reverse-engineer kubectl. 

Cascading deletion (#1535), especially for Deployment, is one of the big ticket items in this area.

cc @lavalamp

**Comment by bgrant0607** [comment]
Quick list (should update as we think of more things):
* RESTMapper (apiVersion+kind to path translation)
* Resource shortnames?
* printPodBase reason summarization
* Cascading deletion #1535
* Schema validation #5889
* Conversion / dry run / eliminate round-tripping and defaulting #11488, #3955, #22431
* Node drain
* Daemonset rolling update

**Comment by bgrant0607** [comment]
FYI: https://github.com/rancher/kubectld

**Comment by bryk** [comment]
> Quick list (should update as we think of more things):
RESTMapper (apiVersion+kind to path translation)
Resource shortnames?
printPodBase reason summarization
Cascading deletion #1535
Schema validation #5889
Conversion / dry run / eliminate round-tripping and defaulting #11488, #3955, #22431
Node drain
Daemonset rolling update

Add `kubectl create/apply` here. From what I've seen this is what most most projects embed kubectl for (including the UI).

**Comment by bgrant0607** [comment]
@bryk Apply, I get.  What part(s) of create?

**Comment by lavalamp** [comment]
Deleting replication controllers. Actually reapers in general.

I want to make a list here and tackle the most important ones for 1.3. We may need a few different designs because there's a few different categories of things.

**Comment by lavalamp** [comment]
And by "list" I mean, I want to know everything that kubectl does that a client generated from e.g. swagger wouldn't.

**Comment by lavalamp** [comment]
Describe is another one.

**Comment by lavalamp** [comment]
All the generators.

**Comment by lavalamp** [comment]
@caesarxuchao do you think you can help us make a list?

**Comment by caesarxuchao** [comment]
Sure.

**Comment by bgrant0607** [comment]
@lavalamp reapers -- that's "cascading deletion"

**Comment by bryk** [comment]
> @bryk Apply, I get. What part(s) of create?

You have a YAML file, perhaps with multiple resources. You want to create all of them or none, in transaction. I think it can be also called "batch API".

**Comment by lavalamp** [comment]
@bryk That's not what create does today. (Maybe it should do that, but I'd
like to keep this issue about current functionality.)

**Comment by caesarxuchao** [comment]
I put up a list of complex behavior in the kubectl code. Some of them can be moved to server. And probably I missed something. Please feel free to comment.
	
***Fan-out operations, only Get operations***	
- [ ] LogsForObject:	If the object is RC or RS, this function retrieves the associated pods first.
- [ ] DeploymentHistoryViewer: It gets new RS and old RS associated with the deployment. It also processes the retrieved data.
- [ ] Describers: Describers may send Get requests to other resource.
	
***Fan-out operations, other than Get***
- [ ] Reapers: Cascading deletion sends Delete requests to other resources
- [ ] Drain: It updates the nodes to be unschedulable, sends Get requests to Daemonsets, RS, RC, Job, and deletes Pods.

***Processing spec/status***
- [ ] HumanReadablePrinter: Each top-level object has such a printer. It is convenient if server can sends back only the important fields of an object.
- [ ] PortsForObject: it returns the ports associated with the provided object. It's not that complex, 3rd-party client may write their own version. `kubectl expose` uses it.
- [ ] MapBasedSelectorForObject: "kubectl expose" uses this function to derive selector from the exposed object.
- [ ] Knowledge of Pod: `kubectl attach`, `exec`, `portForward` all require knowledge of the Pod scheme.

***General***
- [ ] Roundtrip conversion in the create path: `kubectl create` round-trips the versioned configuration of an object. A 3rd-party client doesn't have to follow this path, so this is more like a bug we should fix.
- [ ] Output conversion: `kubectl get` and `edit` call `resource.AsVersionedObject` to versionize the internal objects before printing them. Again, this is more like a bug in kubectl we should fix.
- [ ] RESTMapper: we should build it using the discovery client, and make it easy for a 3rd-party client to build it.
- [ ] CreateOrUpdateAnnotation: This function creates/updates the "last-applied-configuration" annotation. It would be nice if clients don't have to implement this logic.
- [ ] Generators: This affects `kubectl autoscale`, `expose`, `run`, and subcommands of `create`. Another way to approach this is let server do more defaulting (e.g., #2643).
- [ ] StrategicMergePatch	: `kubectl annotation`, `label`, and `edit` relies on it to generate patch.
- [ ] Using Swagger spec: kubectl validates config files with the swagger spec; "kubectl explain" navigate swagger to find description of fields of API objects. I think it makes more sense to keep these two features at the client-side.

**Comment by smarterclayton** [comment]
> CreateOrUpdateAnnotation: This function creates/updates the
"last-applied-configuration" annotation. It would be nice if clients don't
have to implement this logic.

I'm pretty leery of the server doing this for us.

> Using Swagger spec: kubectl validates config files with the swagger spec;
"kubectl explain" navigate swagger to find description of fields of API
objects. I think it makes more sense to keep these two features at the
client-side.

We're in a weird middle ground where swagger is *almost* an official API
for us.  It either needs to be official (and versioned, maintained,
exposed, supported) or not official (in which case we shouldn't fail when
we talk to it and can't get it).

**Comment by smarterclayton** [comment]
> Knowledge of Pod: kubectl attach, exec, portForward all require knowledge
of the Pod scheme

There is a general concept among a bunch of commands (especially the
kubectl set *) for "does this object expose a pod template" or "can this
object return one or more pods" or "can this object be turned into a pod
template".  That could be done with swagger for some of those.

**Comment by liggitt** [comment]
>> CreateOrUpdateAnnotation: This function creates/updates the "last-applied-configuration" annotation. It would be nice if clients don't have to implement this logic.
>
> I'm pretty leery of the server doing this for us.

Agree

**Comment by bgrant0607** [comment]
See also #7311

**Comment by bgrant0607** [comment]
And #17333, #5889, #3676

**Comment by bgrant0607** [comment]
With respect to printing, selection/formatting is ok, though I'd like it to be fairly automated. See #11617. Could all printers be expressed using the custom-column printer?

printPodBase is computation that should go into Kubelet

**Comment by bgrant0607** [comment]
MapBasedSelectorForObject: We need to add matchExpressions to Service, as discussed in #341.

We should also serialize selectors as strings in status of objects with selectors, as we do in Scale.

**Comment by bgrant0607** [comment]
Proxy, port forward, etc. See https://github.com/kubernetes/kubernetes/pull/4440#issuecomment-75181244 and #3481. We need a polymorphic API that returns an address+ports.

**Comment by bgrant0607** [comment]
Roundtripping is #3955

**Comment by bgrant0607** [comment]
Describers: We should link/refer to related resources in status: #3676.

**Comment by bgrant0607** [comment]
Conversion: dry run in the server

**Comment by bgrant0607** [comment]
Strategic Merge: We should find a way to express the patch keys in Swagger.

**Comment by bgrant0607** [comment]
Expose could perhaps be a subresource

**Comment by bgrant0607** [comment]
As could controller-from-podtemplate, which is really a variant of #170

**Comment by bgrant0607** [comment]
And for something like run --expose, see #14956

**Comment by bgrant0607** [comment]
cc @mml

**Comment by bgrant0607** [comment]
List of resources in help should be populated from discovery API. (see also #18622, #20293).

**Comment by davidopp** [comment]
@roberthbailey had suggested it might be useful to have a "dry run" mode where you just ask which is the best node to drain, or best N of some set, but don't drain it. not sure how you express that using a REST API though. also can't remember what the use case was (it might have been for autoscaling scale-down, so you know which node is best to remove?)

**Comment by lavalamp** [comment]
Ref #29472

**Comment by kargakis** [comment]
kubectl drain issue: https://github.com/kubernetes/kubernetes/issues/25625

**Comment by adohe** [comment]
@pwittrock @fabianofranz @bgrant0607 as what we talked on last SIG-CLI meeting, I would hope we can move a little bit forward on this in 1.7. wdyt?
