### ISSUE TITLE
Release mentioned in stable.txt does not exist on GCS

### ISSUE THREAD

**Issue by thecodeassassin** [kubernetes/kubernetes#121400]
**What happened**:

curl -LO https://storage.googleapis.com/kubernetes-release/release/$\(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt\)/bin/linux/amd64/kubectl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl</Details></Error>%

**What you expected to happen**:

Download the latest stable release

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Comment by sftim** [comment]
> ```
> curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
> ```

This is not the documented way to download kubectl - please see https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-on-linux

**Comment by sftim** [comment]
Also see https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/

**Comment by ThePooN** [comment]
The documented way still fails though at least on my end:

![image](https://github.com/kubernetes/kubernetes/assets/4985725/6763b540-98f5-41c2-884d-e5962c554d66)
