### ISSUE TITLE
[Eviction Manager] Missing unit test on PIDPressure

### ISSUE THREAD

**Issue by kannon92** [kubernetes/kubernetes#121449]
We should add a unit test to Eviction manager that accounts for PID Pressure.  

The test should cover similar cases as DiskPressure or MemoryPressure.  

https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/eviction/eviction_manager_test.go

1) PIDPressure doesn't exist on node.
2) Force PidPressure on node

We should include test cases for reclaming resources in terms of pressure and verifying differences between soft and hard eviction.

**Comment by meetguleria** [comment]
Hello! 👋 I noticed the need for a unit test to address PID Pressure in the Eviction manager, similar to the existing tests for DiskPressure and MemoryPressure. I'm new to contributing to open source and was also interested in working on this.

**Comment by kannon92** [comment]
@meetguleria it looks like @swastik959 has requested to work on this.

**Comment by meetguleria** [comment]
> @meetguleria it looks like @swastik959 has requested to work on this.

ohh, my bad. I will try contributing for some other issues. If you need help or collaboration, don't hesitate to tag me.

**Comment by hrishikeshdkakkad** [comment]
Hi @kannon92 

- What do you mean by, "verifying differences between soft and hard eviction."?

**Comment by kannon92** [comment]
> Hi @kannon92
> 
> * What do you mean by, "verifying differences between soft and hard eviction."?

It’s the same idea as what we do for disk, memory or inode pressure. Hard eviction means we trigger eviction with no grace period while soft eviction means that we obey a grace period. Test should check for that.

**Comment by hrishikeshdkakkad** [comment]
@kannon92  I have opened a PR based on what I could understand using a debugger and the other tests.
This is my first time contributing to the codebase. Happy to take brutal feedback.

**Comment by codeserra** [comment]
Hi, i would like to support this issue. Let me know if any help is required.
