### ISSUE TITLE
kube-proxy udp flow hang on "fast" rates

### ISSUE THREAD

**Issue by bnprss** [kubernetes/kubernetes#12144]
By conducting some performances test I tried to measure the performance of kube-dns I got a complete hang over udp cnx after a short amount of time : 
1,050s with kube-dns rc=2 
857ms with kube-dns rc=1

It happens around the 870's query on little to nothing loaded cluster
What used to check :
for i in $(seq 1 5000); do dig my_obfuscated_pod.my_obfuscated_namespace.svc.cluster.local @10.0.0.10 | grep ";; Query time:" | cut -d " " -f 4; done

Queries are made in sequence, we are far from a huge saturated cluster communications.

I managed to get back udp flow by restarting kube-proxy

TCP seems not to be impacted

**Comment by bnprss** [comment]
Ok there is the log :

E0803 09:53:43.326873   17247 util.go:69] Recovered from panic: "Dial failed: dial udp 10.244.2.31:53: too many open files" (Dial failed: dial udp 10.244.2.31:53: too many open files)
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/src/go/src/runtime/asm_amd64.s:401
/usr/src/go/src/runtime/panic.go:387
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:97
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:248
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:216
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:251
/usr/src/go/src/runtime/asm_amd64.s:2232
E0803 09:53:43.830860   17247 util.go:69] Recovered from panic: "Accept failed: accept tcp [::]:52417: too many open files" (Accept failed: accept tcp [::]:52417: too many open files)
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/src/go/src/runtime/asm_amd64.s:401
/usr/src/go/src/runtime/panic.go:387
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:117
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:251
/usr/src/go/src/runtime/asm_amd64.s:2232
E0803 09:53:44.099516   17247 util.go:69] Recovered from panic: "Accept failed: accept tcp [::]:51279: too many open files" (Accept failed: accept tcp [::]:51279: too many open files)
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/src/go/src/runtime/asm_amd64.s:401
/usr/src/go/src/runtime/panic.go:387
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:117
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:251
/usr/src/go/src/runtime/asm_amd64.s:2232
E0803 09:53:44.543869   17247 util.go:69] Recovered from panic: "Accept failed: accept tcp [::]:44098: too many open files" (Accept failed: accept tcp [::]:44098: too many open files)
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/src/go/src/runtime/asm_amd64.s:401
/usr/src/go/src/runtime/panic.go:387
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxysocket.go:117
/go/src/github.com/GoogleCloudPlatform/kubernetes/_output/dockerized/go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/proxy/proxier.go:251
/usr/src/go/src/runtime/asm_amd64.s:2232
E0803 09:53:44.584451   17247 proxier.go:161] Failed to ensure iptables: error creating chain "KUBE-PORTALS-CONTAINER": open /dev/null: too many open files: 
W0803 09:53:44.584494   17247 iptables.go:203] Error checking iptables version, assuming version at least 1.4.11: %vopen /dev/null: too many open files

**Comment by bnprss** [comment]
it is related to my coreos configuration : 
on stock 
Limit                     Soft Limit           Hard Limit           Units                                                                                                                                                                                                      
Max cpu time              unlimited            unlimited            seconds                                                                                                                                                                                                    
Max file size             unlimited            unlimited            bytes                                                                                                                                                                                                      
Max data size             unlimited            unlimited            bytes                                                                                                                                                                                                      
Max stack size            8388608              unlimited            bytes                                                                                                                                                                                                      
Max core file size        0                    unlimited            bytes                                                                                                                                                                                                      
Max resident set          unlimited            unlimited            bytes                                                                                                                                                                                                      
Max processes             29981                29981                processes                                                                                                                                                                                                  
Max open files            65536                65536                files                                                                                                                                                                                                      
Max locked memory         65536                65536                bytes                                                                                                                                                                                                      
Max address space         unlimited            unlimited            bytes                                                                                                                                                                                                      
Max file locks            unlimited            unlimited            locks                                                                                                                                                                                                      
Max pending signals       29981                29981                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us 

on my coreos box : 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             52016                52016                processes 
Max open files            1024                 4096                 files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       52016                52016                signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

I'll close it and you can tag it as irrelevant...

**Comment by bnprss** [comment]
I reopen this issue since it could lead to potential problem on heavy loaded cluster.

When using udp connection, the connection is made to endpoint, data flowed, and the connection is released in the state ESTABLISHED.

The problem is that the connexion will stay there until udpIdleTimeout = 10 * time.Second, using one file descriptor per connection.
The number of connection in is not caped and could lead to ressource starvation and kube-proxy does not recover the udp stack after the error occur.

With the debian configuration the descriptor allowed to kube-proxy is 65536 which mitigate and hide the problem. 

One correct way to handle that will be at least to cap the maximum allowed udp session in cache.

**Comment by thockin** [comment]
@artfulcoder same file descriptors problem

**Comment by bnprss** [comment]
@ArtfulCoder thank you for patch it is a huge helper to resource starvation and it's really welcome.

But UDP network stack won't recover from beeing hit by  "Recovered from panic: "Dial failed: dial up". DDOS would have some HUGE impact locking up udp stack. You can imagine what your cluster will look like with no more DNS transaction. Nowadays 65000 TPS can be achieved easily...

**Comment by timothysc** [comment]
This sounds like we should create an e2e stress test on this one.  

@jayunit100 @zmerlynn

**Comment by ArtfulCoder** [comment]
On a GCE minion (debian), I reduced the fd limit to 8K, increased udp timeout to 100 sec, and tried to recreate the problem.
I hit the fd  limit within seconds and dig command started to fail. But post that kube-proxy seemd to have recovered on its own without a restart. dig commands started succeeding again.

**Comment by thockin** [comment]
@bnprss - could you test the PRs I sent tonight against this issue?  I can
not reproduce it (I an sending 3k QPS at DNS with no problem)

**Comment by thockin** [comment]
I'm going to close this for now.  If the iptables proxy has not alleviated the problem in kube v1.1, please let me know.
