### ISSUE TITLE
Docs UI: The navigation menu in the Documentation pages does not support mobile browsers

### ISSUE THREAD

**Issue by RichieEscarez** [kubernetes/kubernetes#12157]
We need to add in javascript to convert the navigation menu into a slide out menu when the page is viewed by a mobile device (or the window is reduced to a small size). 

Here is an example of the behavior we want: https://mango.github.io/slideout/

Today the banner supports reduced sizes/mobile browsing so we can leverage that code and convert the navigation menu to a slide out at the same time the banner changes.

Update: I found that the banner uses bootstrap and will also use it for the menu.

**Comment by mbforbes** [comment]
Probably a naive question: Why didn't we just use Bootstrap (http://getbootstrap.com/)? Features like these have been solved for years.

**Comment by RichieEscarez** [comment]
@mbforbes, sorry i got side tracked and meant to update this but yes, thats my plan, i looked into how to change and implement the bootstrap mobile support in our site (thats actually whats used in our banner now). Im working on editing the API now but will get back to this after.

**Comment by mbforbes** [comment]
@RichieEscarez SGTM!

**Comment by brendandburns** [comment]
@RichieEscarez what is the status on this?

**Comment by RichieEscarez** [comment]
I have an item I need to wrap up and then ill continue this later today.
