### ISSUE TITLE
Statefulset scales out wrong pods with partition

### ISSUE THREAD

**Issue by xcming** [kubernetes/kubernetes#121534]
### What happened?

I have a statefulset with `replicas=4` and `partition=2`. After updating podTemplate to change the image fields, two old version pods and two new version pods are presented. 
Then scale down the statefulset to 0, and scale it up to 2, the 2 newly created pods are of the new version, which is not the expected behavior.

Possible solution: check whether the replicas is zero before changing `currentRevision`: https://github.com/kubernetes/kubernetes/blob/d0084356b3cabdafcfc140d19ad8d544b2fc9b5d/pkg/controller/statefulset/stateful_set_utils.go#L583 They should be processed correctly then.

### What did you expect to happen?

After updating the statefulset, scale it down to 0, then scale up to 2, two old version pods should be created, because the partition is 2.

### How can we reproduce it (as minimally and precisely as possible)?

- create a statefulset with replicas=4 and partition=2
- update the image field of the statefulset
- 2 old version pods and 2 new verison pods are presented
- scale down the replicas to 0
- scale up the replicas to 2
- 2 pods of new version are created, which are unexpected 

### Kubernetes version

1.24.14 and later

### Cloud provider

<details>
N/A
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by olderTaoist** [comment]
refer to the introduction of [partition](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions), 
this issue is correct behavior

**Comment by xcming** [comment]
> refer to the introduction of [partition](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions), this issue is correct behavior

correct behavior? sorry, I don't quite understand. 
means that the statefulset with `partition=2` should scale out 2 new version pods, instead of 2 old version pods, from 0 -> 2?

**Comment by olderTaoist** [comment]
> > refer to the introduction of [partition](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions), this issue is correct behavior
> 
> correct behavior? sorry, I don't quite understand. means that the statefulset with `partition=2` should scale out 2 new version pods, instead of 2 old version pods, from 0 -> 2?

you specify partition with 2, meaning that all pods with an ordinal that is less than the partition will not be updated with newest version no matter how you change replicas

**Comment by xcming** [comment]
> > > refer to the introduction of [partition](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#partitions), this issue is correct behavior
> > 
> > 
> > correct behavior? sorry, I don't quite understand. means that the statefulset with `partition=2` should scale out 2 new version pods, instead of 2 old version pods, from 0 -> 2?
> 
> you specify partition with 2, meaning that all pods with an ordinal that is less than the partition will not be updated with newest version no matter how you change replicas

yep, so this is a bug in statefulset

**Comment by olderTaoist** [comment]
this not bug, you can set partition with 1, the one pod will be recreate with newest version

**Comment by xcming** [comment]
> this is not bug, you can set partition with 1, the one pod will be recreate with newest version

no, now my partition is 2 and replicas are also 2, but the 2 pods are created with newest version

**Comment by atiratree** [comment]
docs

> Partition indicates the ordinal at which the StatefulSet should be partitioned
for updates. During a rolling update, all pods from ordinal Replicas-1 to
Partition are updated. All pods from ordinal Partition-1 to 0 remain untouched.
This is helpful in being able to do a canary based deployment. The default value is 0.

It states that the pods should be partitioned for updates. Not for an initial rollout.

This is not possible to fix today. Suppose you have 5 revisions. It is unclear which pod should have which revision during the initial rollout. It would need a new enhancement/feature to implement this.

**Comment by xcming** [comment]
clear, thanks
