### ISSUE TITLE
Existing scheduler-extender framework transfer too much content, which resulting in the poor performance in production K8s clusters when new pod needs to be scheduled

### ISSUE THREAD

**Issue by minghuiyuan** [kubernetes/kubernetes#121527]
### What would you like to be added?

When I write a scheduler extender in my k8s cluster, try to extend one extend policy to let k8s scheduler take my extender into consideration, while found that:

#### the content of [extenderv1.ExtenderArgs](https://github.com/kubernetes/kubernetes/blob/release-1.28/pkg/scheduler/extender.go#L256C1-L256C38) that need to be sent is too large, which make the  performance so poor for each pod's scheduling.

Why we did not just send the nodeName list by default, and then let each scheduler extender to watch-list the node contents and pods, and then return the result, just like [what Prioritize does: just return a nodeName list and score](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/extender.go#L319)?

I see the issue https://github.com/kubernetes/kubernetes/issues/72634 was already discussing about it, but seems there is no actions in upstream.

kind/feature

## What did you expect to happen? ## 

For scheduler extender framework, just send the content as small as possible, let each scheduler-extender watch-list get the contents from api-server or something else.

Kubernetes version
v1.23 and master

k8s Cluster node number
5000

Container runtime (CRI) and version (if applicable)
N/A

Related plugins (CNI, CSI, ...) and versions (if applicable)
CNI

### Why is this needed?

Existing scheduler-extender framework is a very brilliant design for incoming-scheduler extender! It did not affect any other components to achieve the extendable features.

While in reality, after adding such extender, the time cost is several times that of the original. it depends on the scale of k8s clusters, when there are more than 5000 nodes in one clusters, the result is the disaster.

One of the main reasons is that "there are too much content to transfer between scheduler-extender framework and users scheduler-extender".

are there some concern that we did not send the [full-nodelist contents](https://github.com/kubernetes/kubernetes/blob/release-1.28/pkg/scheduler/extender.go#L256C1-L256C38) for scheduler-extender framework? why not just send the nodelist ??

**Comment by Huang-Wei** [comment]
I'm afraid it's a known limitation for scheduler extender. And due to its essence (communicating via webhook), the overhead is unavoidable. sig-scheduling has designed and matured scheduler framework for years, officially we'd recommend implement  custom scheduling requirements using scheduler plugins. For scheduler extender, it's in maintenance mode, and someday we may deprecate/remove it.

**Comment by minghuiyuan** [comment]
Hi @Huang-Wei  thanks for responsing.
Communicating via webhook in shceuder is a brilliant idea and the advantage of scheduler extender is :
- if there are some issues in extender, it will not affact any other main components.
- it is extendable in anytime without "re-rollout new codes, just update the configs".

Why can't we just simplify the payload? For example, just change the payload from "*extenderv1.ExtenderArgs" into "nodelist(string)"???

**Comment by ahg-g** [comment]
you can also use the new scheduling gates feature. It is a different design pattern, but close extenders in that you can have a second level scheduler without changing kube-scheduler: https://kubernetes.io/blog/2022/12/26/pod-scheduling-readiness-alpha/
