### ISSUE TITLE
[Failing test]  [sig-node] ImageID [NodeFeature: ImageID] should be set to the manifest digest (from RepoDigests) when available 

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121599]
### Failure cluster [2635916009e310df2e05](https://go.k8s.io/triage#2635916009e310df2e05)
https://storage.googleapis.com/k8s-triage/index.html?test=NodeFeature%3A%20ImageID#0334f50ce7dd7114a467

Error since 10-24
##### Error text:
```
[FAILED] Expected
    <string>: 3e0d9138669908f438c06993e9a6815bbd8c05411b8e9acfc297b3c8b017c28c
to contain substring
    <string>: registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9
In [It] at: test/e2e_node/image_id_test.go:69 @ 10/26/23 12:41:59.111

```
#### Recent failures:
[2023/10/30 06:00:04 ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1718748974304727040)
[2023/10/30 05:23:18 ci-kubernetes-node-swap-fedora](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-node-swap-fedora/1718739662903709696)
[2023/10/30 05:00:50 ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1718733874227318784)
[2023/10/30 04:00:08 ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1718718774640644096)
[2023/10/30 03:00:12 ci-crio-cgroupv1-node-e2e-features](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1718703675100106752)

/kind failing-test
/sig node

**Comment by pacoxu** [comment]
> Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.956400022Z" level=debug msg="Request: &ImageStatusRequest{Image:&ImageSpec{Image:registry.k8s.io/e2e-test-images/busybox:1.36.1-1,Annotations:map[string]string{},UserSpecifiedImage:,},Verbose:false,}" file="otel-collector/interceptors.go:62" id=409ded34-fa83-42f9-b67b-c6635e3a929f name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.956857422Z" level=info msg="Checking image status: registry.k8s.io/e2e-test-images/busybox:1.36.1-1" file="server/image_status.go:27" id=409ded34-fa83-42f9-b67b-c6635e3a929f name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.956459552Z" level=debug msg="Request: &ImageStatusRequest{Image:&ImageSpec{Image:registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9,Annotations:map[string]string{},UserSpecifiedImage:,},Verbose:false,}" file="otel-collector/interceptors.go:62" id=07f1d927-4c08-4e22-80d1-8fb3e545ba9b name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.956939691Z" level=info msg="Checking image status: registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9" file="server/image_status.go:27" id=07f1d927-4c08-4e22-80d1-8fb3e545ba9b name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.957060122Z" level=debug msg="reference \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]docker.io/nfvpe/sriov-device-plugin:v3.1\" does not resolve to an image ID" file="storage/storage_reference.go:146"
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.957540771Z" level=debug msg="Can't find registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9" file="server/image_status.go:97" id=07f1d927-4c08-4e22-80d1-8fb3e545ba9b name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.957580431Z" level=info msg="Image registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9 not found" file="server/image_status.go:111" id=07f1d927-4c08-4e22-80d1-8fb3e545ba9b name=/runtime.v1.ImageService/ImageStatus
Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.957615871Z" level=info msg="Image registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9 not found" file="server/image_status.go:33" id=07f1d927-4c08-4e22-80d1-8fb3e545ba9b name=/runtime.v1.ImageService/ImageStatus

Oct 26 12:40:30 tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64 crio[2295]: time="2023-10-26 12:40:30.957149212Z" level=debug msg="reference \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]registry.k8s.io/e2e-test-images/busybox@sha256:a9155b13325b2abef48e71de77bb8ac015412a566829f621d06bfae5c699b1b9\" does not resolve to an image ID" file="storage/storage_reference.go:146"

https://storage.googleapis.com/kubernetes-jenkins/logs/ci-crio-cgroupv1-node-e2e-features/1717516582516690944/artifacts/tmp-node-e2e-9516abbc-fedora-coreos-38-20231002-3-1-gcp-x86-64-system.log

**Comment by saschagrunert** [comment]
Fix available in https://github.com/kubernetes/kubernetes/pull/121531

**Comment by kannon92** [comment]
I think we can close. Thank you @saschagrunert for fixing this.

/close
