### ISSUE TITLE
Kube-Proxy IPVS mode support port hash and fallback in sh schedule 

### ISSUE THREAD

**Issue by bamboo12366** [kubernetes/kubernetes#121590]
### What would you like to be added?

Current `sh` load balancing policy only performs hashing of sourcing IP, the server load maybe really high when only a single client is sending bunch of data to the server; So like this MR, we definitely need source port hash flag in `sh` policy as well

Another things is the `sh` don't have the fallback flag enabled, which the client will have no endpoints to send when the hashed one is unready and the weight set to zero. Can refer to this [patch](https://lore.kernel.org/lkml/20130619095425.GA20145@eldamar.org.uk/)

### Why is this needed?

kubeproxy IPVS mod should include src-port hash and fallback flag in  `sh` policy.

**Comment by aojea** [comment]
I couldn't find the other issues, but I  vaguely remember to see this request in the past, @uablrek do you remember?

**Comment by bamboo12366** [comment]
kindly ping @uablrek master; if you guys think it's acceptable I can open a PR for that

**Comment by uablrek** [comment]
The PR https://github.com/kubernetes/kubernetes/pull/115527 adds this for the `mh` scheduler. But it was rejected for `sh` because it's a non backward compatible change https://github.com/kubernetes/kubernetes/pull/115527#issuecomment-1426638214

**Comment by uablrek** [comment]
> Current sh load balancing policy only performs hashing of sourcing IP, the server load maybe really high when only a single client is sending bunch of data to the server; So like this MR, we definitely need source port hash flag in sh policy as well

You must provide a better use-case. Sh is not intended to be a "deterministic round-robin" in K8s. Quote from the kernel patch:

>  This basically allows for deterministic round-robin load balancing (i.e., where any director in a cluster of directors with identical config will send the same packet the same way).

If that is what you want, please take a look at the `mh` scheduler.

**Comment by uablrek** [comment]
From what I can see, `mh` takes care of the fallback case too
