### ISSUE TITLE
Define new well-known annotation: `kubernetes.io/display-name`

### ISSUE THREAD

**Issue by akutz** [kubernetes/kubernetes#121514]
### What would you like to be added?

~~We~~ VMware would like to define a new, well-known annotation, `kubernetes.io/display-name`, per [_Well-known labels, annotations, and taints_](https://kubernetes.io/docs/reference/labels-annotations-taints). A quick tl;dr about the history of this issue is as follows:

* There is a PR open at https://github.com/kubernetes/website/pull/43658.
* This topic has been discussed in [this thread](https://kubernetes.slack.com/archives/C5P3FE08M/p1697837862269049) in the `#sig-architecture` channel from k8s Slack.
* @sftim has been a giant help in shepherding this issue.
* @dims requested this issue be filed and assigned to `#sig-cli`.

/sig cli

### Why is this needed?

To my knowledge, such an annotation does not exist, and while [`kubernetes.io/description`](https://kubernetes.io/docs/reference/labels-annotations-taints/#description) is close, it is not exactly the same thing. ~~We~~ VMware was likely to introduce a similar annotation internally due to the lack of a standard, well-known annotation for this use case in upstream K8s. However, after speaking with some folks, we opted to [engage](https://kubernetes.slack.com/archives/C1J0BPD2M/p1697816976615399) `#sig-docs`, who suggested we [reach out](https://kubernetes.slack.com/archives/C5P3FE08M/p1697837862269049) to `#sig-architecture` about adding this annotation to upstream K8.

#### Goals

1. **Standard approach for mutable, human-readable name on K8s objects**
  Users & non-interactive processes should be able to read/write a K8s object's human-readable name.

1. **Well-defined syntax and character set for human-readable names**
  Users & non-interactive processes should be able to read/write human-readable names using UTF-16.

1. **Support for human-readable name in standard human-readable column**
  Applications that surface or present K8s objects should be able to refer to a common location for surfacing an object's human-readable name.

#### Non-goals

1. **Object relationships based on human-readable names**
  Support for defining relationships between objects based on their human-readable names is not in scope of this change. Object relationships must still be defined using an object's name.

1. **Performant query/search for objects based on human-readable names**
  Support for performant queries based on human-readable names is not in scope of this change. Server-side indexing/filtering of objects is not supported by annotations, only labels. While both labels and annotations offer mutability, the former's values are constrained to a restrictive character set. The ability to input free-form data for a human-readable name was prioritized over searching for objects based on human-readable names.

1. **Support for human-readable names built into `kubectl`**
  Support for this annotation in `kubectl` is not in scope of this change. APIs may use this annotation's value as an additional printer column to surface this annotation's value when printing objects with `kubectl`. However, any feature such as the introduction of a `--display-name` flag to print the human-readable names for objects is not part of this change.

**Comment by sftim** [comment]
/sig architecture
too

**Comment by sftim** [comment]
(nit)
/retitle Define new well-known annotation: `kubernetes.io/display-name`

Issue titles (but not PRs) can safely have Markdown in them

**Comment by akutz** [comment]
> "we"

VMware

**Comment by akutz** [comment]
I met with the SIG CLI group this morning and presented this topic. First of all, my gratitude to SIG CLI for being so welcoming and open to this discussion. After the use cases were outlined, the general consensus was the bar for adding a new well-known label / annotation should be an accompanying use of said label / annotation by some core part of Kubernetes, such as the API server or kubectl. Given that, I will be closing this issue at this time and may revist it in the future once I can provide an associated patch that uses this annotation. Thanks all!

**Comment by sftim** [comment]
> the bar for adding a new well-known label / annotation should be an accompanying use of said label / annotation by some core part of Kubernetes

BTW that's already not true. Non-core parts of Kubernetes define well-known labels and annotations fairly often.
