### ISSUE TITLE
kubernetes deletes info from all NFS shares when one of the mounts becames stalled (google container engine)

### ISSUE THREAD

**Issue by jyrip** [kubernetes/kubernetes#12155]
When mounting several shares over NFS to container and when one of the directories is deleted from NFS server, something in the node is deleting content from other shares. I suspect that something goes wrong with "cleanupOrphanedVolumes"? not sure tough.

Use case: php-app is running in container, uses php-sessions for remembering login. php sessions are stored in file and shared through nfs-share between containers. also app code is shared and several other directories to store different data (data dirs are mapped under code, code is in separate share so generated document files don't get to git tree), all is managed by separate integration server (in container), that uses same shares to prepare the code.

This happened first time in GCE with Cluster API version 0.17.something, now it acts same on 1.0.1 and 0.18.2. Problem is repeatable:
First of all you need to install package "nfs-common" to **all cluster nodes**, otherwise you can't map NFS shares at all:

    apt-get update && apt-get install nfs-common

now you need nfs server. I created small instance for that with /etc/export stating:

    /export 	10.240.0.0/16(rw,sync,crossmnt,no_subtree_check)

also I made directories under /export/test/:
 
    #ls -la ubuntutest ubuntutest2 ubuntutest3
    ubuntutest:
    total 12
    drwxrwxrwx  2 root root 4096 Aug  3 15:07 .
    drwxr-xr-x 12 root root 4096 Aug  3 15:06 ..
    -rw-r--r--  1 root root 1580 Aug  3 15:06 testifail
    ubuntutest2:
    total 12
    drwxrwxrwx  2 root root 4096 Aug  3 15:06 .
    drwxr-xr-x 12 root root 4096 Aug  3 15:06 ..
    -rw-r--r--  1 root root 1580 Aug  3 15:06 testifail2
    ubuntutest3:
    total 12
    drwxr-xr-x  2 root root 4096 Aug  3 15:07 .
    drwxr-xr-x 12 root root 4096 Aug  3 15:06 ..
    -rw-r--r--  1 root root 1580 Aug  3 15:07 testifail3

next you need ubuntutest.yaml to start it up (replace nfs server ip with your own):

    apiVersion: v1
    kind: ReplicationController
    metadata:
      labels:
        name: zubuntu
      name: zubuntu
    spec:
      replicas: 1
      selector:
        name: zubuntu-rc
      template:
        metadata:
          labels:
            name: zubuntu-rc
        spec:
          restartPolicy: Always
          containers:
            - image: tutum/apache-php
              name: ubuntu-cont
              ports:
                - containerPort: 80
                  name: web-port
              volumeMounts:
                - name: test-nfs-1
                  mountPath: /app
                - name: test-nfs-2
                  mountPath: /app2
                - name: test-nfs-3
                  mountPath: /app3
          volumes:
            - name: test-nfs-1
              nfs:
                server: 10.240.175.237
                path: /export/test/ubuntutest
            - name: test-nfs-2
              nfs:
                server: 10.240.175.237
                path: /export/test/ubuntutest2
            - name: test-nfs-3
              nfs:
                server: 10.240.175.237
                path: /export/test/ubuntutest3
    
now start up the pod:

    kubectl create -f ubuntutest.yaml 
    kubectl get pods

verify, that the directories are mapped:

    kubectl exec -ti zubuntu-8y55c bash
	# ls -la /app*
	/app:
	total 12
	drwxrwxrwx  2 root root 4096 Aug  3 18:07 .
	drwxr-xr-x 69 root root 4096 Aug  3 18:09 ..
	-rw-r--r--  1 root root 1580 Aug  3 18:06 testifail

	/app2:
	total 12
	drwxrwxrwx  2 root root 4096 Aug  3 18:06 .
	drwxr-xr-x 69 root root 4096 Aug  3 18:09 ..
	-rw-r--r--  1 root root 1580 Aug  3 18:06 testifail2

	/app3:
	total 12
	drwxr-xr-x  2 root root 4096 Aug  3 18:07 .
	drwxr-xr-x 69 root root 4096 Aug  3 18:09 ..
	-rw-r--r--  1 root root 1580 Aug  3 18:07 testifail3

now the funny part:
remove directory from nfs server

     # rm -rf ubuntutest

the zubuntu pod shows:

	# ls -la /app*
	/app:
	ls: reading directory /app: Stale file handle
	total 0

	/app2:
	total 12
	drwxrwxrwx  2 root root 4096 Aug  3 18:06 .
	drwxr-xr-x 69 root root 4096 Aug  3 18:09 ..
	-rw-r--r--  1 root root 1580 Aug  3 18:06 testifail2

	/app3:
	total 12
	drwxr-xr-x  2 root root 4096 Aug  3 18:07 .
	drwxr-xr-x 69 root root 4096 Aug  3 18:09 ..
	-rw-r--r--  1 root root 1580 Aug  3 18:07 testifail3

nothing happens on nfs server yet, but just launch the stop command:

    kubectl stop -f ubuntutest.yaml 

and now nfs server shows:

	# ls -la ubuntutest ubuntutest2 ubuntutest3
	ls: cannot access ubuntutest: No such file or directory
	ubuntutest2:
	total 8
	drwxrwxrwx  2 root root 4096 Aug  3 15:18 .
	drwxr-xr-x 11 root root 4096 Aug  3 15:17 ..
	ubuntutest3:
	total 12
	drwxr-xr-x  2 root root 4096 Aug  3 15:07 .
	drwxr-xr-x 11 root root 4096 Aug  3 15:17 ..
	-rw-r--r--  1 root root 1580 Aug  3 15:07 testifail3

you see, that one file was left, but not for long. this is because root in client does not have root access in nfs-file system, but just after giving rights, the file is gone:

	# chmod 777 ubuntutest3

	# ls -la ubuntutest ubuntutest2 ubuntutest3
	ls: cannot access ubuntutest: No such file or directory
	ubuntutest2:
	total 8
	drwxrwxrwx  2 root root 4096 Aug  3 15:18 .
	drwxr-xr-x 11 root root 4096 Aug  3 15:17 ..
	ubuntutest3:
	total 8
	drwxrwxrwx  2 root root 4096 Aug  3 15:20 .
	drwxr-xr-x 11 root root 4096 Aug  3 15:17 ..

now you can test "black hole" by creating new files. they dissaperar from the server in few moments. the dissapearing continues until cluster node is restarted.

**Comment by smarterclayton** [comment]
@rootfs @markturansky

**Comment by rootfs** [comment]
so the problem looks to me is that containers delete files though they are not told to do. I am not quite convinced `cleanupOrphanedVolumes` is the culprit here, since the directories are still alive. 

@jyrip what the first version you believe this problem started to show up? Would it be possible for you to take a tcpdump on the nfs server so we can look at the nfs traffic? Thanks!

**Comment by jyrip** [comment]
I started to play with the Google Container Engine about in middle of June and the version of the cluster was 0.17. something. I don’t have that cluster anymore. So I don’t know what happened or did it worked before.

About tcpdump. What ports and what traffic do you think you need for that? Also in what timeframe? Maybe you can even give me command-line for that?

Jüri.

**Comment by rootfs** [comment]
@jyrip I am setting up an environment to simulate your tests, stay tuned

**Comment by thockin** [comment]
Something is fishy.  Volume cleanup should be happening against the volume dirs, which is totally separate from pod dirs.  Pod teardown should un-bind-mount the NFS from th epod dir, so pod cleanup can happen, even if the volume can't umount...

@yujuhong @saad-ali

**Comment by yujuhong** [comment]
> Something is fishy. Volume cleanup should be happening against the volume dirs, which is totally separate from pod dirs. Pod teardown should un-bind-mount the NFS from th epod dir, so pod cleanup can happen, even if the volume can't umount...

@thockin, I didn't touch much of the volume code, but think the directory structure is `/var/lib/pods/<pod_UID>/volumes/`. Removing pod directories would remove the volumes as well. We can delay the pod directory cleanup until all volumes in it are properly unmounted.

Another user reported a similar case in #12210

**Comment by rootfs** [comment]
@yujuhong in this particular case, the mountpoint cannot be properly unmounted (because it was deleted), and  I believe the current NFS mount is [hard mount](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/5/html/Deployment_Guide/s1-nfs-client-config-options.html), so it won't be easy to unmount even after delay.

**Comment by thockin** [comment]
Ahh yes, it was only GCE PD that was doing something tricker here

**Comment by yujuhong** [comment]
> @yujuhong in this particular case, the mountpoint cannot be properly unmounted (because it was deleted), and I believe the current NFS mount is hard mount, so it won't be easy to unmount even after delay.

I see. Thanks for the explanation. I didn't read the original post carefully.

> unmount error might be a good heuristic. In this case, NFS stale handle error is probably good sign nothing is good for wait for.

If we let `cleanupOrphanedVolumes` propagate the error upstream, kubelet may always skip pod directory cleanup because of one failed teardown. That seems undesirable. I agree that the NFS stale handle error alone should be enough for us to skip waiting. In short,
- `vol.TearDown()` should distinguish the NFS error and report a successful teardown in this case.
- `cleanupOrphanedPodDirs` should check if there are any uncleaned volume directories, and avoid removing the specific pod.

**Comment by rootfs** [comment]
cool, thanks.  When a patch is available, I'll give it a test on other volumes too.

**Comment by saad-ali** [comment]
> `cleanupOrphanedPodDirs` should check if there are any uncleaned volume directories, and avoid removing the specific pod.

This was completed by @yujuhong in PR #13293

> `vol.TearDown()` should distinguish the NFS error and report a successful teardown in this case.

@rootfs can you take a crack at this?

**Comment by rootfs** [comment]
ok, glad to do it.

**Comment by saad-ali** [comment]
> ok, glad to do it.

Thanks!
