### ISSUE TITLE
[Flaky test][sig-node] can make a CDI device accessible in a container 

### ISSUE THREAD

**Issue by chendave** [kubernetes/kubernetes#121562]
### What happened?

Full test name is: 
E2eNode Suite.[It] [sig-node] Device Plugin [Feature:DevicePluginProbe][NodeFeature:DevicePluginProbe][Serial] DevicePlugin [Serial] [Disruptive] can make a CDI device accessible in a container [sig-node]

The failure can be detected on both GCE arm64 or EC2 arm64,  I am not sure is the testcase running on any X86_64 arch or not.

ec2:
https://testgrid.k8s.io/sig-node-ec2#ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2&width=90
gce:
https://testgrid.k8s.io/sig-node-kubelet#kubelet-gce-e2e-arm64-ubuntu-serial

the log said it's timeout.

### What did you expect to happen?

The testcase can pass consistently.

### How can we reproduce it (as minimally and precisely as possible)?

refer to the log from the link I paste above.

### Kubernetes version

<details>

```console
$ kubectl version

on master branch
```

</details>

### Cloud provider

<details>
gce/ec2
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chendave** [comment]
/assign @bart0sh 

I believe this is the change from https://github.com/kubernetes/kubernetes/pull/121440

/cc @SergeyKanzhelev @dims @pacoxu

**Comment by bart0sh** [comment]
@chendave thanks for pointing out. Here is the fix: https://github.com/kubernetes/kubernetes/pull/121557
Please, review.

**Comment by bart0sh** [comment]
/triage accepted
The fix has been merged. Let's see if it fixes the jobs.

**Comment by kannon92** [comment]
Fix was merged so we can monitor for a few days. We will close once tests run a few times.

**Comment by bart0sh** [comment]
last ec2 job run skipped the test: https://testgrid.k8s.io/sig-node-ec2#ci-cgroupv2-containerd-node-arm64-e2e-serial-ec2&width=90

**Comment by bart0sh** [comment]
kubelet-gce-e2e-arm64-ubuntu-serial should also skip it because [it skips tests marked a [NodeSpecialFeature]](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-node/node-kubelet.yaml#L195). Let's see.

**Comment by kannon92** [comment]
/close

Tests are being skipped correctly and I haven't seen these in a few days.
