### ISSUE TITLE
Can’t connect from Pods on one server to Pods on different server using VXLAN

### ISSUE THREAD

**Issue by hawk2111** [kubernetes/kubernetes#121530]
### What happened?

I build Kubernetes cluster v1.26.9 on Virtual Machines with RHEL 8.6. I am using flannel as Container Networking Interface with backend VXLAN. Communication between Pods on the same server works fine but I can’t connect from Pods on one server to Pods on different server.

For testing purposes I tried to use flannel with UDP backend. It helped. Connection between Pods on different servers is possible when UDP backend is used. Since UDP backend is recommended only for debugging, it can't be my final solution. That is why I want to configure connection using VXLAN.

I also tried to configure connection using host-gw backend but it also didn't work.

There is no firewall between servers. Connection between servers is possible.
Firewalld service is disabled on servers.
SELinux is set to permissive.
In sysctl below options are set:
    net.ipv4.ip_forward = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-arptables = 1
In /etc/modules-load.d/k8s.conf there are set options:
    overlay
    br_netfilter
Execution of command "iptables -P FORWARD ACCEPT" didn't help.
Reboot of VMs didn't help.

### What did you expect to happen?

It is possible to connect from Pods on one server to Pods on different server for flannel with VXLAN backend.

### Settings for flannel in kube-flannel.yml for backend vxlan - connection between pods on different nodes doesn't work
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
...

  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        **"Type": "vxlan"**
      }
    }

### Settings for flannel in kube-flannel.yml for backend udp - connection between pods on different nodes works fine
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
...
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        **"Type": "udp",
        "Port": 8285**
      }
    }

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
...
        securityContext:
          **privileged: true**
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:32:41Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.9", GitCommit:"d1483fdf7a0578c83523bc1e2212a606a44fd71d", GitTreeState:"clean", BuildDate:"2023-09-13T11:25:26Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
none
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"

$ uname -a
Linux 4.18.0-372.32.1.el8_6.x86_64

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
cri-dockerd 0.3.4
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>
flannel:v0.22.3
</details>

**Comment by uablrek** [comment]
This is not a K8s bug, CNI-plugins are not a part of K8s.

It _could_ be a bug in Flannel, but I think the problem should be searched for in your network setup. For example that some firewall filters vxlan traffic. I run Flannel with vxlan overlay without problems. Please check something like:
```
# ip route get 11.0.0.4
11.0.0.4 via 11.0.0.0 dev flannel.1 src 11.0.1.0 uid 0 
    cache 
# ip -d link show flannel.1
7: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 0a:85:fd:4f:0e:ec brd ff:ff:ff:ff:ff:ff promiscuity 0  allmulti 0 minmtu 68 maxmtu 65535 
    vxlan id 1 local 192.168.1.2 dev eth1 srcport 0 0 dstport 8472 nolearning ttl auto ageing 300 udpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 tso_max_size 65536 tso_max_segs 65535 gro_max_size 65536 gso_ipv4_max_size 65536 gro_ipv4_max_size 65536 
# ping -c1 11.0.1.0
PING 11.0.1.0 (11.0.1.0) 56(84) bytes of data.
64 bytes from 11.0.1.0: icmp_seq=1 ttl=64 time=0.068 ms

--- 11.0.1.0 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.068/0.068/0.068/0.000 ms
```
Here I use `ip route get ...` on a node to a POD on another node. The route uses interface `flannel.1`, which is a vxlan interface. Ping works fine.

**Comment by MikeZappa87** [comment]
Are you able to provide additional details? Having the route table (ip route) will help. If you ping from one pod to a pod on another node do you have a tshark capture? I am curious where the issue is happening. However this is more of a CNI issue. RHEL or flannel would be a better forum.

**Comment by sftim** [comment]
/kind support
/remove-kind bug

based on https://github.com/kubernetes/kubernetes/issues/121530#issuecomment-1781240955

**Comment by hawk2111** [comment]
I was able to solve the issue. It seems that on default port for vxlan there is already some other process running. As a result communication between pods on different nodes wasn't working. As a solution I changed the port. Thank you for support.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-ds
...

  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan",
        **"Port": 8285**
      }
    }
