### ISSUE TITLE
Why is the expiration time of the certificate set to 365 days?

### ISSUE THREAD

**Issue by kunkunhaohao** [kubernetes/kubernetes#121580]
https://github.com/kubernetes/kubernetes/blob/1aef58b72a7d9a37cc7590c881b63808d02695f1/staging/src/k8s.io/client-go/util/cert/cert.go#L124
```[tasklist]
### Tasks
```

**Comment by kunkunhaohao** [comment]
After my kube-apiserver has been running for one year, I find that when I create a new resource deploy, kube-controller keeps reporting the certificate expiration error during pod creation. Therefore, kube-apiserver has a built-in loopbackClientConfig parameter. The validity period of the certificate is 365 days. As a result, pods cannot be created.

**Comment by kunkunhaohao** [comment]
Events:
  Type     Reason        Age                  From                   Message
  ----     ------        ----                 ----                   -------
  Warning  FailedCreate  8m4s (x8 over 8m4s)  replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:23+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  8m3s                 replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:24+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  8m2s                 replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:25+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  7m59s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:28+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  7m54s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:33+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  7m44s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:43:43+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  7m23s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:44:04+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  6m42s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:44:45+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  5m20s                replicaset-controller  Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:46:07+08:00 is after 2032-03-08T15:05:21Z
  Warning  FailedCreate  2m36s                replicaset-controller  (combined from similar events): Error creating: pods "test-5c644fc9cc-" is forbidden: Get "https://33.18.1.55:4443/api/v1/namespaces/fst-manage/limitranges": x509: certificate has expired or is not yet valid: current time 2033-03-10T14:48:51+08:00 is after 2032-03-08T15:05:21Z

**Comment by kunkunhaohao** [comment]
my k8s version is v1.19

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close

**Comment by kunkunhaohao** [comment]
> a better place to ask would be on the support channels. please see: https://git.k8s.io/kubernetes/SUPPORT.md
> 
> /kind support /close

I think it's a bug, and I'm not allowed to create resources after my kube-apiserver has been running for a year, which is unreasonable and I think it should be extended.
