### ISSUE TITLE
Kubernetes CronJob pods is not getting clean-up when Job is completed

### ISSUE THREAD

**Issue by nicknamenotknown** [kubernetes/kubernetes#121502]
### What happened?

I create cron job from this sample https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/cronjob.yaml 
completed pod not clean.

### What did you expect to happen?

The pods spawned from the cronjob should get cleanup after the job has completed

### How can we reproduce it (as minimally and precisely as possible)?

apply sample https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/application/job/cronjob.yaml  to kubernetes cluster, and wait.

### Anything else we need to know?

```
#kubectl  get cronjobs hello -o yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"CronJob","metadata":{"annotations":{},"name":"hello","namespace":"test"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["/bin/sh","-c","date; echo Hello from the Kubernetes cluster"],"image":"busybox:1.28","imagePullPolicy":"IfNotPresent","name":"hello"}],"restartPolicy":"OnFailure"}}}},"schedule":"* * * * *"}}
  creationTimestamp: "2023-10-25T07:24:11Z"
  generation: 1
  name: hello
  namespace: test
  resourceVersion: "267016543"
  uid: df0ace03-1937-43b2-8b5e-ba185203ff8e
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            name: hello
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2023-10-25T08:08:00Z"
  lastSuccessfulTime: "2023-10-25T08:08:04Z"
```

```
#kubectl get cronjob
NAME    SCHEDULE    SUSPEND   ACTIVE   LAST SCHEDULE   AGE
hello   * * * * *   False     0        21s             45m
```

```
#kubectl get job
NAME             COMPLETIONS   DURATION   AGE
hello-28303687   1/1           3s         2m52s
hello-28303688   1/1           4s         112s
hello-28303689   1/1           4s         52s
```

```
#kubectl get pods
NAME                   READY   STATUS      RESTARTS   AGE
hello-28303645-db9h4   0/1     Completed   0          45m
hello-28303646-jc8sg   0/1     Completed   0          44m
hello-28303647-dsrnc   0/1     Completed   0          43m
hello-28303648-554d9   0/1     Completed   0          42m
hello-28303649-f2q7x   0/1     Completed   0          41m
hello-28303650-hslvt   0/1     Completed   0          40m
hello-28303651-z5qxj   0/1     Completed   0          39m
hello-28303652-xbdvx   0/1     Completed   0          38m
hello-28303653-nbz64   0/1     Completed   0          37m
hello-28303654-2czqx   0/1     Completed   0          36m
hello-28303655-88wxz   0/1     Completed   0          35m
hello-28303656-zh9k9   0/1     Completed   0          34m
hello-28303657-5ds8l   0/1     Completed   0          33m
hello-28303658-2mcqd   0/1     Completed   0          32m
hello-28303659-mb2jx   0/1     Completed   0          31m
hello-28303660-9psxw   0/1     Completed   0          30m
hello-28303661-2gm4d   0/1     Completed   0          29m
hello-28303662-kq5kq   0/1     Completed   0          28m
hello-28303663-lqs6k   0/1     Completed   0          27m
hello-28303664-nhgkm   0/1     Completed   0          26m
hello-28303665-rzdd7   0/1     Completed   0          25m
hello-28303666-bz9gc   0/1     Completed   0          24m
hello-28303667-j47pz   0/1     Completed   0          23m
hello-28303668-lgdp6   0/1     Completed   0          22m
hello-28303669-bpbk4   0/1     Completed   0          21m
hello-28303670-srnlv   0/1     Completed   0          20m
hello-28303671-gxrkb   0/1     Completed   0          19m
hello-28303672-d8hwj   0/1     Completed   0          18m
hello-28303673-fttzk   0/1     Completed   0          17m
hello-28303674-mrdj7   0/1     Completed   0          16m
hello-28303675-jdjq6   0/1     Completed   0          15m
hello-28303676-z5src   0/1     Completed   0          14m
hello-28303677-r7mfg   0/1     Completed   0          13m
hello-28303678-mwn9t   0/1     Completed   0          12m
hello-28303679-tpp5z   0/1     Completed   0          11m
hello-28303680-rn98s   0/1     Completed   0          10m
hello-28303681-p5qp5   0/1     Completed   0          9m19s
hello-28303682-tnmjf   0/1     Completed   0          8m19s
hello-28303683-sr5dl   0/1     Completed   0          7m19s
hello-28303684-bbmkh   0/1     Completed   0          6m19s
hello-28303685-p4k46   0/1     Completed   0          5m19s
hello-28303686-8fdld   0/1     Completed   0          4m19s
hello-28303687-lljls   0/1     Completed   0          3m19s
hello-28303688-4j6dv   0/1     Completed   0          2m19s
hello-28303689-sc2hr   0/1     Completed   0          79s
hello-28303690-sgqmb   0/1     Completed   0          19s
```

### Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.25.8
</details>


### Cloud provider

<details>
VMware Server
</details>


### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux srv 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
</details>


### Install tools

<details>
kubeadm
</details>


### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.16
</details>


### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
You could use the Ttlafterfinished feature for jobs.  That would delete the jobs after they finish.

**Comment by nicknamenotknown** [comment]
@kannon92 after set `spec.jobTemplate.spec.ttlSecondsAfterFinished: 5` new pod not clean after ttl.

**Comment by nicknamenotknown** [comment]
This is not good idea, i think, but the competed pod full my pod list very fast. Default setting 3 for sucsess  jobs and 1 for erro job.
Can clean pods then clened job, in older version kubernetes it work fine.

**Comment by nicknamenotknown** [comment]
@kannon92  in old version kubernetes pod cleaned, when job cleaned. In this exaple i have 60 new pod in hour it is very big count pods to view after one day.

**Comment by nicknamenotknown** [comment]
> Looking into this, https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection
> 
> it sounds like we keep them around until they hit a maximum limit and then PodGC cleans them up

Pod not have status Succsess or Error:
`apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 471ddef808266df0c5498a8231dc99a0b63e2a9905e5a2358ec6c728b79ec138
    cni.projectcalico.org/podIP: ""
    cni.projectcalico.org/podIPs: ""
  creationTimestamp: "2023-10-26T15:31:00Z"
  generateName: hello-28305571-
  labels:
    controller-uid: 65ca4d44-32e4-4f68-82f8-7bc9e73b9bc9
    job-name: hello-28305571
  name: hello-28305571-j4wx6
  namespace: test
  ownerReferences:
  - apiVersion: batch/v1
    blockOwnerDeletion: true
    controller: true
    kind: Job
    name: hello-28305571
    uid: 65ca4d44-32e4-4f68-82f8-7bc9e73b9bc9
  resourceVersion: "267591447"
  uid: f73a5588-529f-4832-a8d0-fce065f01090
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - date; echo Hello from the Kubernetes cluster
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: hello
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-8r7qm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8s-worker01
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-8r7qm
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T15:31:00Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T15:31:00Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T15:31:00Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-10-26T15:31:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://bba38dd02b2819348f418adfe3518eebb5d19b2915fe911b84f1b7f333bbcdb3
    image: docker.io/library/busybox:1.28
    imageID: docker.io/library/busybox@sha256:141c253bc4c3fd0a201d32dc1f493bcf3fff003b6df416dea4f41046e0f37d47
    lastState: {}
    name: hello
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://bba38dd02b2819348f418adfe3518eebb5d19b2915fe911b84f1b7f333bbcdb3
        exitCode: 0
        finishedAt: "2023-10-26T15:31:01Z"
        reason: Completed
        startedAt: "2023-10-26T15:31:01Z"
  hostIP: 10.5.3.53
  phase: Succeeded
  podIP: 10.112.172.158
  podIPs:
  - ip: 10.112.172.158
  qosClass: BestEffort
  startTime: "2023-10-26T15:31:00Z"`

**Comment by kannon92** [comment]
So can you confirm that if you use a Job controller TTL (without CronJob) are the pods getting cleaned up after the job is deleted?

And if you use CronJob, this is no longer the case?

Trying to narrow down exactly what the problem is.

Can you reproduce this issue on later versions of K8s (1.28)?  

What versions of Kubernetes did this work on?

**Comment by nicknamenotknown** [comment]
> So can you confirm that if you use a Job controller TTL (without CronJob) are the pods getting cleaned up after the job is deleted?
Pod not cleaned after delete job 
> And if you use CronJob, this is no longer the case?
Pod not cleaned after delete job(without CronJob)  and if delete CronJob the jobs and pods not deleted
> Trying to narrow down exactly what the problem is.
> 
> Can you reproduce this issue on later versions of K8s (1.28)?
I can not test on 1.28
> What versions of Kubernetes did this work on?
in 1.21.5, without ttl dafault save 3 jobs adn 3 pods, with ttl delete jobs and pods after end ttl time.

**Comment by nicknamenotknown** [comment]
@kannon92 You need any more to resolve problem?

**Comment by kannon92** [comment]
> > So can you confirm that if you use a Job controller TTL (without CronJob) are the pods getting cleaned up after the job is deleted?
> > And if you use CronJob, this is no longer the case?
> > Trying to narrow down exactly what the problem is.
> > Can you reproduce this issue on later versions of K8s (1.28)?
> > What versions of Kubernetes did this work on?
> 
> Pod not cleaned after delete job created (without CronJob). And if delete CronJob the jobs and pods not deleted. I can not test on 1.28 now. In 1.21.5, without ttl default save 3 jobs adn 3 pods, with ttl delete jobs and pods after end ttl time.

You could test this on kind with 1.28 or minikube.

**Comment by nicknamenotknown** [comment]
@kannon92 Now i can not use 1.28 in my project, but i searh this issues https://github.com/kubernetes/kubernetes/issues/107730  
And this problem is exist in my case too.

**Comment by kannon92** [comment]
1.21 is out of support so there isn't really much we can do with 1.21.

**Comment by nicknamenotknown** [comment]
> 1.21 is out of support so there isn't really much we can do with 1.21.

my case in 1.21 work fine, i have problem in 1.25.8

**Comment by kannon92** [comment]
I was unable to reproduce the CronJob issue.  

I used 

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

I'll see if someone more familar with CronJobs can weigh in.  

I was able to see deletions happen in 1.25.11.  Pods were deleted and we kept only the amount of jobs that we requested.

**Comment by nicknamenotknown** [comment]
> I was unable to reproduce the CronJob issue.
> 
> I used
> 
> ```yaml
> apiVersion: batch/v1
> kind: CronJob
> metadata:
>   name: hello
> spec:
>   schedule: "* * * * *"
>   failedJobsHistoryLimit: 1
>   successfulJobsHistoryLimit: 3
>   jobTemplate:
>     spec:
>       template:
>         spec:
>           containers:
>           - name: hello
>             image: busybox:1.28
>             imagePullPolicy: IfNotPresent
>             command:
>             - /bin/sh
>             - -c
>             - date; echo Hello from the Kubernetes cluster
>           restartPolicy: OnFailure
> ```
> 
> I'll see if someone more familar with CronJobs can weigh in.
> 
> I was able to see deletions happen in 1.25.11. Pods were deleted and we kept only the amount of jobs that we requested.

Thanks for the tests and clarifications. The error was caused by the package "tigera-operator" version "v3.26.0". After upgrading to version "v3.26.3" everything began to work correctly.
