### ISSUE TITLE
Allowed configure IPVS scheduler per service

### ISSUE THREAD

**Issue by bamboo12366** [kubernetes/kubernetes#121591]
### What would you like to be added?

The ipvs scheduler is configured by clusters, can we allow it to be configured by service?

For our situation is we configure the `rr` for the cluster, all the node will pick the first the same apiserver since server list is well sorted, so when we create a daemonset with all newly started apiserver, the daemonset will direct to the first apiserver which will cause a lot load to it and cause it OOM cuz the list request is quite expensive. If we change cluster configuration to `sh` or `mh`, it will influence the other request like there is a client on single node and rely on service loadbalancing.

### Why is this needed?

Allowed configure IPVS scheduler per service

**Comment by arrowfeng** [comment]
Looks like a very good suggestion

**Comment by cyclinder** [comment]
I think it's a good idea, but not all modes support multiple scheduler, so we don't want to change the API, Maybe there can be a special annotation for the service?

How do you think? 

/cc @uablrek

**Comment by uablrek** [comment]
It has been proposed, and rejected, many times before, e.g. https://github.com/kubernetes/kubernetes/issues/75502.

Now it's a bit different since the ipvs-proxier doesn't check modules any more, please see https://github.com/kubernetes/kubernetes/pull/114669.

But there is a KEP for a [nft based proxy](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/3866-nftables-proxy) to replace both ipvs and iptables proxiers. So, I am unsure if ipvs-only features are welcome.

/cc @danwinship @aroradaman

**Comment by uablrek** [comment]
Here is a summary https://github.com/kubernetes/kubernetes/issues/118784#issuecomment-1603854344, and the comments after this.

**Comment by danwinship** [comment]
As you commented in the linked bug, this looks like a job for Gateway...

I don't think we currently have any backend-specific Service features.

> For our situation is we configure the `rr` for the cluster, all the node will pick the first the same apiserver since server list is well sorted

I'm not an expert on how people expect the ipvs backend to work, but it seems plausible that it doesn't _have to_ work in exactly that way. E.g., each node could rotate the list of endpoints for each service by `(last_digit_of_node_IP % len(endpoints))` positions.

**Comment by uablrek** [comment]
> each node could rotate the list of endpoints for each service by (last_digit_of_node_IP % len(endpoints)) positions.

Seemed like a good idea, so I tried it. But is seems like the sorting is done by the kernel (I haven't checked the kernel source). I added a log printout at:

https://github.com/kubernetes/kubernetes/blob/c3eebb233d000ac2dbbd559725124a79bf40d0f0/pkg/proxy/ipvs/proxier.go#L1912

And it is not called in order:
```
11.0.11.2:5001"
11.0.11.2:5001"
11.0.14.2:5001"
11.0.7.2:5001"
11.0.14.2:5001"
11.0.7.2:5001"
11.0.10.2:5001"
11.0.12.2:5001"
11.0.18.2:5001"
11.0.2.2:5001"
...
```
The order is slightly different between nodes.

But `ipvsadm` shows an ordered list:
```
# ipvsadm -Ln
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port Scheduler Flags
  -> RemoteAddress:Port           Forward Weight ActiveConn InActConn
TCP  10.0.0.1:5001 rr
  -> 11.0.1.2:5001                Masq    1      0          0         
  -> 11.0.2.2:5001                Masq    1      0          0         
  -> 11.0.3.2:5001                Masq    1      0          0         
  -> 11.0.4.2:5001                Masq    1      0          0         
  -> 11.0.5.2:5001                Masq    1      0          0         
  -> 11.0.6.2:5001                Masq    1      0          0         
  -> 11.0.7.2:5001                Masq    1      0          0         
...
```
It _could_ be the user-space `ipvsadm` that sorts the list, but I don't think so.

**Comment by uablrek** [comment]
Actually, on a closer look it seems like `ipvsadm` does the sorting. The _first_ "real-server" (endpoint) ipvs selects is the _last_ one added. But there is another problem: the real-servers does not come as _one_ list, they are announced asynchronously, so it's hard to make it differently on different nodes.

**Comment by aroradaman** [comment]
@uablrek 
ipvsadm sorts the output (by default).
https://github.com/e7e5/ipvsadm/blob/3a0060a842074202286068c5ca5931b65648b6a1/ipvsadm.c#L707-L708



```
err = proxier.ipvs.AddRealServer(appliedVirtualServer, newDest) 
```
For this, order should be same on every node as we sort and then iterate 
https://github.com/kubernetes/kubernetes/blob/c3eebb233d000ac2dbbd559725124a79bf40d0f0/pkg/proxy/ipvs/proxier.go#L1868

**Comment by uablrek** [comment]
Changed to this:
```go
	// Create new endpoints
	eps := newEndpoints.UnsortedList()
	rand.Shuffle(len(eps), func(i, j int) { eps[i], eps[j] = eps[j], eps[i]})
	for _, ep := range eps {
```
And it really makes a difference if the service is created _after the endpoints are ready_. All nodes starts with a random list. Happy days!

But if the service and the server is created in the same manifest, which is normal I think, the improvement is small.

**Comment by uablrek** [comment]
IMO the dependency on the start sequence makes this update dubious, however, it's small and un-intrusive.

**Comment by uablrek** [comment]
The sort in:
https://github.com/kubernetes/kubernetes/blob/c3eebb233d000ac2dbbd559725124a79bf40d0f0/pkg/proxy/ipvs/proxier.go#L1868

is completely unnecessary and takes $\mathcal{O}(n\log{}n)$ (with a really good sort algorithm), while the shuffle is just $\mathcal{O}(n)$, so it can be seen as a performance improvement :smiley:

**Comment by uablrek** [comment]
I made some additional testing like:

1. Start a 20 node K8s cluster
2. Create the PODs (DaemonSet) and the service in the desired order
3. Setup ECMP to the loadBalancerIP on an external traffic generator
4. Do 20 connects from the traffic generator and check the distribution

And it turns out that _even without the "shuffle"_ the distribution becomes far better if the service is created *after* the PODs are "ready":

The service created before the DaemonSet
```
mconnect -address 10.0.0.1:5001 -nconn 20
tserver-daemonset-srbnz 2
tserver-daemonset-jzfck 3
tserver-daemonset-m7lsk 15
```
The DaemonSet is ready before the service is created
```
tserver-daemonset-z5nrt 1
tserver-daemonset-glqmd 3
tserver-daemonset-w2mzk 1
tserver-daemonset-zxz9r 1
tserver-daemonset-2gdd5 3
tserver-daemonset-k9lnb 1
tserver-daemonset-x2l7m 1
tserver-daemonset-zbrqn 2
tserver-daemonset-l77kf 2
tserver-daemonset-ttwv4 1
tserver-daemonset-28bn6 2
tserver-daemonset-8gkzw 2
```

**Comment by uablrek** [comment]
I created a cleanup PR to remove the unnecessary sort https://github.com/kubernetes/kubernetes/pull/121744.

Since this feature has been discussed several times before and not much has changed, I close this issue.

/close

**Comment by zengyuxing007** [comment]
The load balancing algorithm at the service level is meaningful, as different services within a cluster may have distinct characteristics. Some services are of the long-lived connection type, for which the default round-robin (RR) algorithm may not be suitable.
