### ISSUE TITLE
Endpoints and EndpointSlices can have duplicate addresses with different Ready conditions

### ISSUE THREAD

**Issue by aojea** [kubernetes/kubernetes#121556]
both Endpoints and EndpointSlices can contain the same IP duplicate with different Condition. In case of Endpoints this means the same IP is at the same time Ready and NotReady, leaving to implementations how to best deal with it.

This was not a problem in the past for Endpoints, before https://github.com/kubernetes/kubernetes/pull/94112, because the kube-apiserver canonicalized the Endpoints using the RepackSubsets function https://github.com/kubernetes/kubernetes/blob/ea5e4bc2326c71250774f6a4f5545492c5621760/pkg/api/v1/endpoints/util_test.go#L206-L221 , removing the duplication.

This patch just adds two unit tests to document this and verify that we maintain the existing behavior, since does not sound likely we strict validation now not allowing IPs to be duplicated.

I just found out about this while debugging https://github.com/kubernetes/kubernetes/issues/121231#issuecomment-1763245731

```
kubectl get endpoints kubernetes -o yaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Endpoints","metadata":{"annotations":{},"labels":{"endpointslice.kubernetes.io/skip-mirror":"true"},"name":"kubernetes","namespace":"default"},"subsets":[{"addresses":[{"ip":"192.168.8.4"}],"ports":[{"name":"https","port":6443,"protocol":"TCP"}]},{"notReadyAddresses":[{"ip":"192.168.8.4"}],"ports":[{"name":"https","port":6443,"protocol":"TCP"}]}]}
  creationTimestamp: "2023-10-12T16:22:09Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
  resourceVersion: "854537"
  uid: c6a8f3b3-afbe-48e6-89c3-2b27d4284c5d
subsets:
- addresses:
  - ip: 192.168.8.4
  ports:
  - name: https
    port: 6443
    protocol: TCP
- notReadyAddresses:
  - ip: 192.168.8.4
  ports:
  - name: https
    port: 6443
    protocol: TCP
```

### Notes from original discussion

              While it's possible to have 2 EPS and thereby have duplicate endpoints, I think we should still consider validating no dups within a slice.  Lots of use-cases have just one slice (by design!)

_Originally posted by @thockin in https://github.com/kubernetes/kubernetes/issues/121330#issuecomment-1773290647_

**Comment by aojea** [comment]
/sig network
/cc @thockin 

to not forget about it

**Comment by thockin** [comment]
Also https://github.com/kubernetes/kubernetes/issues/121231#issuecomment-1781556685

**Comment by sftim** [comment]
> both Endpoints and EndpointSlices can contain the same IP duplicate with different Condition. In case of Endpoints this means the same IP is at the same time Ready and NotReady, leaving to implementations how to best deal with it.

I think two EndpointSlices could do that too, even without involving an Endpoints
