### ISSUE TITLE
RunPodSandbox from runtime service failed

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes/kubernetes#121548]
I'm experiencing this errors:

    root@k8s-eu-1-master:~# systemctl status kubelet
    ● kubelet.service - kubelet: The Kubernetes Node Agent
         Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: enabled)
        Drop-In: /etc/systemd/system/kubelet.service.d
                 └─10-kubeadm.conf
         Active: active (running) since Thu 2023-10-26 12:03:09 CEST; 2h 5min ago
           Docs: https://kubernetes.io/docs/home/
       Main PID: 1067481 (kubelet)
          Tasks: 18 (limit: 72235)
         Memory: 43.0M
            CPU: 2min 43.501s
         CGroup: /system.slice/kubelet.service
                 └─1067481 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --pod-infra-container-image=registry.k8s.io/pause:3.9
    
    Oct 26 14:08:18 k8s-eu-1-master kubelet[1067481]: E1026 14:08:18.459322 1067481 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"5db402ddcda98eb797e884575883860a0211c9bf5b6b9d08562793290fd5de78\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
    Oct 26 14:08:18 k8s-eu-1-master kubelet[1067481]: E1026 14:08:18.459398 1067481 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"5db402ddcda98eb797e884575883860a0211c9bf5b6b9d08562793290fd5de78\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-gt7xt"
    Oct 26 14:08:18 k8s-eu-1-master kubelet[1067481]: E1026 14:08:18.459421 1067481 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"5db402ddcda98eb797e884575883860a0211c9bf5b6b9d08562793290fd5de78\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-gt7xt"
    Oct 26 14:08:18 k8s-eu-1-master kubelet[1067481]: E1026 14:08:18.459507 1067481 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-gt7xt_kube-system(8f974cff-995d-4449-8b3d-095c3e9efa96)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-gt7xt_kube-system(8f974cff-995d-4449-8b3d-095c3e9efa96)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"5db402ddcda98eb797e884575883860a0211c9bf5b6b9d08562793290fd5de78\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-gt7xt" podUID="8f974cff-995d-4449-8b3d-095c3e9efa96"
    Oct 26 14:08:19 k8s-eu-1-master kubelet[1067481]: I1026 14:08:19.421859 1067481 scope.go:117] "RemoveContainer" containerID="1cfe3a1d67806d0f309784c10f66f1444acb1459a75084ebcd131652e4a44453"
    Oct 26 14:08:19 k8s-eu-1-master kubelet[1067481]: E1026 14:08:19.422163 1067481 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=kube-flannel pod=kube-flannel-ds-7sf87_kube-flannel(76bd2939-fd7a-4828-820c-af5a9c82e2fb)\"" pod="kube-flannel/kube-flannel-ds-7sf87" podUID="76bd2939-fd7a-4828-820c-af5a9c82e2fb"
    Oct 26 14:08:22 k8s-eu-1-master kubelet[1067481]: E1026 14:08:22.464703 1067481 remote_runtime.go:193] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"8902a65b15fa748436e36451288dea3ab85a031c5baa891722a2bc5356146c5c\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory"
    Oct 26 14:08:22 k8s-eu-1-master kubelet[1067481]: E1026 14:08:22.465203 1067481 kuberuntime_sandbox.go:72] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"8902a65b15fa748436e36451288dea3ab85a031c5baa891722a2bc5356146c5c\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-g2bkc"
    Oct 26 14:08:22 k8s-eu-1-master kubelet[1067481]: E1026 14:08:22.465321 1067481 kuberuntime_manager.go:1166] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"8902a65b15fa748436e36451288dea3ab85a031c5baa891722a2bc5356146c5c\": plugin type=\"flannel\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory" pod="kube-system/coredns-5dd5756b68-g2bkc"
    Oct 26 14:08:22 k8s-eu-1-master kubelet[1067481]: E1026 14:08:22.465511 1067481 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"coredns-5dd5756b68-g2bkc_kube-system(7d1be4ef-d086-4e76-b34c-4d48adaace3d)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"coredns-5dd5756b68-g2bkc_kube-system(7d1be4ef-d086-4e76-b34c-4d48adaace3d)\\\": rpc error: code = Unknown desc = failed to setup network for sandbox \\\"8902a65b15fa748436e36451288dea3ab85a031c5baa891722a2bc5356146c5c\\\": plugin type=\\\"flannel\\\" failed (add): loadFlannelSubnetEnv failed: open /run/flannel/subnet.env: no such file or directory\"" pod="kube-system/coredns-5dd5756b68-g2bkc" podUID="7d1be4ef-d086-4e76-b34c-4d48adaace3d"

    root@k8s-eu-1-master:~# kubelet
    I1026 15:45:46.904653 1176781 server.go:467] "Kubelet version" kubeletVersion="v1.28.2"
    I1026 15:45:46.904817 1176781 server.go:469] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
    I1026 15:45:46.905357 1176781 server.go:630] "Standalone mode, no API client"
    I1026 15:45:46.924554 1176781 server.go:518] "No api server defined - no events will be sent to API server"
    I1026 15:45:46.924603 1176781 server.go:725] "--cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /"
    I1026 15:45:46.924913 1176781 container_manager_linux.go:265] "Container manager verified user specified cgroup-root exists" cgroupRoot=[]
    I1026 15:45:46.925236 1176781 container_manager_linux.go:270] "Creating Container Manager object based on Node Config" nodeConfig={"RuntimeCgroupsName":"","SystemCgroupsName":"","KubeletCgroupsName":"","KubeletOOMScoreAdj":-999,"ContainerRuntime":"","CgroupsPerQOS":true,"CgroupRoot":"/","CgroupDriver":"cgroupfs","KubeletRootDir":"/var/lib/kubelet","ProtectKernelDefaults":false,"KubeReservedCgroupName":"","SystemReservedCgroupName":"","ReservedSystemCPUs":{},"EnforceNodeAllocatable":{"pods":{}},"KubeReserved":null,"SystemReserved":null,"HardEvictionThresholds":[],"QOSReserved":{},"CPUManagerPolicy":"none","CPUManagerPolicyOptions":null,"TopologyManagerScope":"container","CPUManagerReconcilePeriod":10000000000,"ExperimentalMemoryManagerPolicy":"None","ExperimentalMemoryManagerReservedMemory":null,"PodPidsLimit":-1,"EnforceCPULimits":true,"CPUCFSQuotaPeriod":100000000,"TopologyManagerPolicy":"none","TopologyManagerPolicyOptions":null}
    I1026 15:45:46.925440 1176781 topology_manager.go:138] "Creating topology manager with none policy"
    I1026 15:45:46.925472 1176781 container_manager_linux.go:301] "Creating device plugin manager"
    I1026 15:45:46.925559 1176781 state_mem.go:36] "Initialized new in-memory state store"
    I1026 15:45:46.925650 1176781 kubelet.go:399] "Kubelet is running in standalone mode, will skip API server sync"
    I1026 15:45:46.926546 1176781 kuberuntime_manager.go:257] "Container runtime initialized" containerRuntime="containerd" version="1.6.24" apiVersion="v1"
    I1026 15:45:46.926948 1176781 volume_host.go:74] "KubeClient is nil. Skip initialization of CSIDriverLister"
    W1026 15:45:46.928483 1176781 csi_plugin.go:189] kubernetes.io/csi: kubeclient not set, assuming standalone kubelet
    W1026 15:45:46.928704 1176781 csi_plugin.go:266] Skipping CSINode initialization, kubelet running in standalone mode
    I1026 15:45:46.929233 1176781 server.go:1232] "Started kubelet"
    I1026 15:45:46.929456 1176781 kubelet.go:1579] "No API server defined - no node status update will be sent"
    I1026 15:45:46.929655 1176781 server.go:194] "Starting to listen read-only" address="0.0.0.0" port=10255
    I1026 15:45:46.929795 1176781 ratelimit.go:65] "Setting rate limiting for podresources endpoint" qps=100 burstTokens=10
    E1026 15:45:46.930598 1176781 cri_stats_provider.go:448] "Failed to get the info of the filesystem with mountpoint" err="unable to find data in memory cache" mountpoint="/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs"
    I1026 15:45:46.930646 1176781 server.go:162] "Starting to listen" address="0.0.0.0" port=10250
    E1026 15:45:46.930656 1176781 kubelet.go:1431] "Image garbage collection failed once. Stats initialization may not have completed yet" err="invalid capacity 0 on image filesystem"
    I1026 15:45:46.930753 1176781 server.go:233] "Starting to serve the podresources API" endpoint="unix:/var/lib/kubelet/pod-resources/kubelet.sock"
    E1026 15:45:46.930827 1176781 server.go:852] "Failed to start healthz server" err="listen tcp 127.0.0.1:10248: bind: address already in use"
    I1026 15:45:46.931218 1176781 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
    I1026 15:45:46.931911 1176781 server.go:462] "Adding debug handlers to kubelet server"
    I1026 15:45:46.932015 1176781 desired_state_of_world_populator.go:151] "Desired state populator starts to run"
    I1026 15:45:46.931987 1176781 volume_manager.go:291] "Starting Kubelet Volume Manager"
    E1026 15:45:46.933909 1176781 server.go:179] "Failed to listen and serve" err="listen tcp 0.0.0.0:10250: bind: address already in use"

    
    root@k8s-eu-1-master:~# kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.2

O.S. : Ubuntu 22.04

### Cluster information:

Kubernetes version:

  root@k8s-eu-1-master:~# kubectl version
  Client Version: v1.28.2
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.2

Cloud being used: (put bare-metal if not on a public cloud)  : bare-metal (Contabo Cloud)
Installation method: I installed kubernetes following these indications: https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
Host OS: Ubuntu 22.04
CNI and version:

    root@k8s-eu-1-master:~# ls /etc/cni/net.d/
    10-flannel.conflist
    root@k8s-eu-1-master:~# 
    root@k8s-eu-1-master:~# ip a s flannel.1
    23: flannel.1: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default 
        link/ether 9a:0d:1b:93:61:ef brd ff:ff:ff:ff:ff:ff
    root@k8s-eu-1-master:~# 

    root@k8s-eu-1-master:~# crictl pods ls
    WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
    ERRO[0000] validate service connection: validate CRI v1 runtime API for endpoint "unix:///var/run/dockershim.sock": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /var/run/dockershim.sock: connect: no such file or directory" 
    POD ID              CREATED             STATE               NAME                                      NAMESPACE           ATTEMPT             RUNTIME
    02f6c786b8be3       3 hours ago         Ready               kube-flannel-ds-7sf87                     kube-flannel        0                   (default)
    4928efe000ed8       47 hours ago        Ready               kube-proxy-qhvrn                          kube-system         5                   (default)
    ff796c03022b5       47 hours ago        Ready               kube-scheduler-k8s-eu-1-master            kube-system         5                   (default)
    ee5cf0acafee0       47 hours ago        Ready               kube-controller-manager-k8s-eu-1-master   kube-system         5                   (default)
    964707729241d       47 hours ago        Ready               kube-apiserver-k8s-eu-1-master            kube-system         5                   (default)
    425309d119aa6       47 hours ago        Ready               etcd-k8s-eu-1-master                      kube-system         5                   (default)
    0d5af9ab38ff2       2 days ago          NotReady            kube-proxy-qhvrn                          kube-system         4                   (default)
    dcd2220d19eb9       2 days ago          NotReady            kube-apiserver-k8s-eu-1-master            kube-system         4                   (default)
    400848343f530       2 days ago          NotReady            etcd-k8s-eu-1-master                      kube-system         4                   (default)
    601101dcb8471       2 days ago          NotReady            kube-controller-manager-k8s-eu-1-master   kube-system         4                   (default)
    ed75d5bbdb6a2       2 days ago          NotReady            kube-scheduler-k8s-eu-1-master            kube-system         4                   (default)
    d0c99b759eeec       8 days ago          NotReady            coredns-5dd5756b68-gt7xt                  kube-system         0                   (default)
    1c740a8a348fa       8 days ago          NotReady            coredns-5dd5756b68-g2bkc                  kube-system         0                   (default)
    root@k8s-eu-1-master:~# 

CRI and version: 

    root@k8s-eu-1-master:~# kubectl describe node k8s-eu-1-master
    Name:               k8s-eu-1-master
    Roles:              control-plane
    Labels:             beta.kubernetes.io/arch=amd64
                        beta.kubernetes.io/os=linux
                        kubernetes.io/arch=amd64
                        kubernetes.io/hostname=k8s-eu-1-master
                        kubernetes.io/os=linux
                        node-role.kubernetes.io/control-plane=
                        node.kubernetes.io/exclude-from-external-load-balancers=
    Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                        node.alpha.kubernetes.io/ttl: 0
                        volumes.kubernetes.io/controller-managed-attach-detach: true
    CreationTimestamp:  Tue, 17 Oct 2023 13:35:04 +0200
    Taints:             node-role.kubernetes.io/control-plane:NoSchedule
    Unschedulable:      false
    Lease:
      HolderIdentity:  k8s-eu-1-master
      AcquireTime:     <unset>
      RenewTime:       Thu, 26 Oct 2023 16:32:35 +0200
    Conditions:
      Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
      ----             ------  -----------------                 ------------------                ------                       -------
      MemoryPressure   False   Thu, 26 Oct 2023 16:28:36 +0200   Tue, 17 Oct 2023 13:35:03 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
      DiskPressure     False   Thu, 26 Oct 2023 16:28:36 +0200   Tue, 17 Oct 2023 13:35:03 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
      PIDPressure      False   Thu, 26 Oct 2023 16:28:36 +0200   Tue, 17 Oct 2023 13:35:03 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
      Ready            True    Thu, 26 Oct 2023 16:28:36 +0200   Thu, 26 Oct 2023 12:03:20 +0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled
    Addresses:
      InternalIP:  yy.yyy.yyy.yy
      Hostname:    k8s-eu-1-master
    Capacity:
      cpu:                10
      ephemeral-storage:  2061040144Ki
      hugepages-1Gi:      0
      hugepages-2Mi:      0
      memory:             61714440Ki
      pods:               110
    Allocatable:
      cpu:                10
      ephemeral-storage:  1899454593566
      hugepages-1Gi:      0
      hugepages-2Mi:      0
      memory:             61612040Ki
      pods:               110
    System Info:
      Machine ID:                 20539bd7c301cf97deb69a1d652e2613
      System UUID:                d2ca271d-2f5b-4b7f-8282-5031297d3a19
      Boot ID:                    02f5756a-2b89-46b2-a4e3-8109ab741c01
      Kernel Version:             5.15.0-86-generic
      OS Image:                   Ubuntu 22.04.3 LTS
      Operating System:           linux
      Architecture:               amd64
      Container Runtime Version:  containerd://1.6.24
      Kubelet Version:            v1.28.2
      Kube-Proxy Version:         v1.28.2
    Non-terminated Pods:          (8 in total)
      Namespace                   Name                                       CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
      ---------                   ----                                       ------------  ----------  ---------------  -------------  ---
      kube-flannel                kube-flannel-ds-7sf87                      100m (1%)     0 (0%)      50Mi (0%)        0 (0%)         3h7m
      kube-system                 coredns-5dd5756b68-g2bkc                   100m (1%)     0 (0%)      70Mi (0%)        170Mi (0%)     9d
      kube-system                 coredns-5dd5756b68-gt7xt                   100m (1%)     0 (0%)      70Mi (0%)        170Mi (0%)     9d
      kube-system                 etcd-k8s-eu-1-master                       100m (1%)     0 (0%)      100Mi (0%)       0 (0%)         9d
      kube-system                 kube-apiserver-k8s-eu-1-master             250m (2%)     0 (0%)      0 (0%)           0 (0%)         9d
      kube-system                 kube-controller-manager-k8s-eu-1-master    200m (2%)     0 (0%)      0 (0%)           0 (0%)         9d
      kube-system                 kube-proxy-qhvrn                           0 (0%)        0 (0%)      0 (0%)           0 (0%)         9d
      kube-system                 kube-scheduler-k8s-eu-1-master             100m (1%)     0 (0%)      0 (0%)           0 (0%)         9d
    Allocated resources:
      (Total limits may be over 100 percent, i.e., overcommitted.)
      Resource           Requests    Limits
      --------           --------    ------
      cpu                950m (9%)   0 (0%)
      memory             290Mi (0%)  340Mi (0%)
      ephemeral-storage  0 (0%)      0 (0%)
      hugepages-1Gi      0 (0%)      0 (0%)
      hugepages-2Mi      0 (0%)      0 (0%)
    Events:              <none>

How to make it wok?

**Comment by neolit123** [comment]
/kind support
/sig node

unclear if a bug or a support ticket.

**Comment by neolit123** [comment]
> E1026 15:45:46.933909 1176781 server.go:179] "Failed to listen and serve" err="listen tcp 0.0.0.0:10250: bind: address already in use"

seems like more than one kubelet is running for some reason.
try to understand why.

**Comment by raphael10-collab** [comment]
Hi @neolit123 Lubomir !

What do I have to do in order to make it work?

**Comment by raphael10-collab** [comment]
A question @neolit123 

Since I'm thinking to wipe-out the kubernetes cluster and re-install and configure it from scratch again,

I would like to know if this kind of  `Invalid argument` error is a big issue, or can be considered harmless : 

    root@k8s-eu-1-master:~# sudo tee /etc/modules-load.d/containerd.conf <<EOF
    > overlay
    > br_netfilter
    > EOF
    overlay
    br_netfilter
    
    root@k8s-eu-1-master:~# sudo modprobe overlay
    root@k8s-eu-1-master:~# sudo modprobe br_netfilter
    
    root@k8s-eu-1-master:~# sudo tee /etc/sysctl.d/kubernetes.conf <<EOF
    > net.bridge.bridge-nf-call-ip6tables = 1
    > net.bridge.bridge-nf-call-iptables = 1
    > net.ipv4.ip_forward = 1
    > EOF
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    
    root@k8s-eu-1-master:~# sudo sysctl --system
    * Applying /etc/sysctl.d/10-console-messages.conf ...
    kernel.printk = 4 4 1 7
    * Applying /etc/sysctl.d/10-ipv6-privacy.conf ...
    net.ipv6.conf.all.use_tempaddr = 2
    net.ipv6.conf.default.use_tempaddr = 2
    * Applying /etc/sysctl.d/10-kernel-hardening.conf ...
    kernel.kptr_restrict = 1
    * Applying /etc/sysctl.d/10-magic-sysrq.conf ...
    kernel.sysrq = 176
    * Applying /etc/sysctl.d/10-network-security.conf ...
    net.ipv4.conf.default.rp_filter = 2
    net.ipv4.conf.all.rp_filter = 2
    * Applying /etc/sysctl.d/10-ptrace.conf ...
    kernel.yama.ptrace_scope = 1
    * Applying /etc/sysctl.d/10-zeropage.conf ...
    vm.mmap_min_addr = 65536
    * Applying /usr/lib/sysctl.d/50-default.conf ...
    kernel.core_uses_pid = 1
    net.ipv4.conf.default.rp_filter = 2
    net.ipv4.conf.default.accept_source_route = 0
    sysctl: setting key "net.ipv4.conf.all.accept_source_route": Invalid argument
    net.ipv4.conf.default.promote_secondaries = 1
    sysctl: setting key "net.ipv4.conf.all.promote_secondaries": Invalid argument
    net.ipv4.ping_group_range = 0 2147483647
    net.core.default_qdisc = fq_codel
    fs.protected_hardlinks = 1
    fs.protected_symlinks = 1
    fs.protected_regular = 1
    fs.protected_fifos = 1
    * Applying /usr/lib/sysctl.d/50-pid-max.conf ...
    kernel.pid_max = 4194304
    * Applying /usr/lib/sysctl.d/99-protect-links.conf ...
    fs.protected_fifos = 1
    fs.protected_hardlinks = 1
    fs.protected_regular = 2
    fs.protected_symlinks = 1
    * Applying /etc/sysctl.d/99-sysctl.conf ...
    net.ipv6.conf.all.disable_ipv6 = 1
    kernel.panic = 10
    * Applying /etc/sysctl.d/kubernetes.conf ...
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    * Applying /etc/sysctl.conf ...
    net.ipv6.conf.all.disable_ipv6 = 1
    kernel.panic = 10
    root@k8s-eu-1-master:~#


Previously I followed these indications : https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/
are they fine according to you?
