### ISSUE TITLE
using port-forward error:  socat not found

### ISSUE THREAD

**Issue by mysodalife** [kubernetes/kubernetes#121560]
I'm using the port-forward command on a Kubernetes cluster to establish port mapping between local and cloud ports, binding the local port 8080 to the cloud port 8081. My Kubernetes cluster version is 1.21.7. When I try to access the local service via curl localhost:8080, it shows "socat not found". Later on, I installed socat version 1.7.4.4 on all nodes in the cluster. However, after installation, I still get the "socat not found" message. What should I do? Here's the error information I received:
1. First, I executed the command using the kubectl tool: `kubectl port-forward svc/ess-test 8080:8081`
2. Then, I ran `curl localhost:8080` locally. Upon executing that command, the following message appeared:
   E1027 13964 port-forward.go:400] an error occurred forwarding 8080 -> 8081: error forwarding port 8081 to pod 234ffwe423fs54535345g, uid: unable to do port forwarding: scout not found.
3. After installing socat version 1.7.4.4 on all nodes in the cluster and executing `curl localhost:8080`, I still get the same error message. What should I do?"

d a draft title or issue reference here
```

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/sig network
/kind support
/close
