### ISSUE TITLE
Unable to use the value of `image` as an env variable

### ISSUE THREAD

**Issue by kolluria** [kubernetes/kubernetes#121558]
### What happened?

I have a Deployment that has an init container and a few containers.

I have a requirement to set the env variable of the `initContainer` with the value of the `image` field of one of the containers.

Based on what I found in the documentation, there's no way to do this either by using `env.valueFrom.resourceFieldRef` or `env.valueFrom.fieldRef`.

IMO this is a gap in the solution that needs to be fixed.

### What did you expect to happen?

I expected the Deployment spec to get updated without failing after making the aforementioned change.

### How can we reproduce it (as minimally and precisely as possible)?

Create a Deployment spec with one container.

Try to set an env to the value of the image of the container using resource field ref or field ref.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.4+vmware.wcp.0", GitCommit:"c3baec6e66bbd8235269e021ea047488f4930fca", GitTreeState:"clean", BuildDate:"2023-07-30T15:42:34Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
</details>

### Cloud provider

<details>
VMware
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```
NAME="VMware Photon OS"
VERSION="3.0"
ID=photon
VERSION_ID=3.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>
containerd://1.6.18-1-gdbc99e5b1
</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by toVersus** [comment]
Related to https://github.com/kubernetes/kubernetes/issues/19475. This is not a bug but a feature request. We need a KEP to add new Downward API values. See https://github.com/kubernetes/kubernetes/issues/19475#issuecomment-1781724590.
I'm not sure about the use case for referencing a value in the `image` field via an environment variable in initContainers. What is the purpose of this?

**Comment by iamryanchia** [comment]
YAML has a syntax called [Anchor](https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/). Does this satisfy your requirement?

**Comment by kolluria** [comment]
@iamryanchia lemme take a look and let you know. Thanks :)

**Comment by thockin** [comment]
We have a pretty easy path for adding ways to publish info about *this* container into this container.  We don't have a precedent for exposing information about *a different* container into this container.
