### ISSUE TITLE
[Failing Test] unable to create the kubeadm:cluster-admins ClusterRoleBinding (periodic-kubernetes-e2e-kind-kms)

### ISSUE THREAD

**Issue by Vyom-Yadav** [kubernetes/kubernetes#121587]
### Which jobs are failing?

master-informing:
- periodic-kubernetes-e2e-kind-kms

### Which tests are failing?

`kubetest2.Up`

![Image](https://github.com/kubernetes/kubernetes/assets/73882557/668efbe4-a899-4f43-9939-febd0dad9cc6)

### Since when has it been failing?

https://github.com/kubernetes/kubernetes/pull/121305

### Testgrid link

https://testgrid.k8s.io/sig-release-master-informing#periodic-kubernetes-e2e-kind-kms

### Reason for failure (if possible)

```
I1029 07:10:01.667112     297 kubeconfig.go:682] creating the ClusterRoleBinding for the kubeadm:cluster-admins Group by using super-admin.conf
I1029 07:10:01.705456     297 round_trippers.go:553] POST https://kms-control-plane:6443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=10s 500 Internal Server Error in 38 milliseconds
Internal error occurred: got unexpected nil transformer
unable to create the kubeadm:cluster-admins ClusterRoleBinding
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.EnsureAdminClusterRoleBindingImpl
	cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:691
k8s.io/kubernetes/cmd/kubeadm/app/phases/kubeconfig.EnsureAdminClusterRoleBinding
	cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go:595
```

### Relevant SIG(s)

/sig cluster-lifecycle

**Comment by neolit123** [comment]
/assign

but this test job is maintained by sig auth:
/sig auth

looks like the API server has decided to consistently fail on an unpolled CRB create API call in the kubeadm client.
this did not happen on the kind presubmit jobs here:
https://github.com/kubernetes/kubernetes/pull/121305

or kubeamd periodicjobs using the kinder:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm

or my local tests.

> Internal error occurred: got unexpected nil transformer

so what is different here and why are we getting informer errors?
is this highlighting a bug in core k8s? cc @enj @liggitt 

best we can do in kubeadm is make that API call polled.
FTR, the API call exactly prior to this failing API call was already polled.

**Comment by zelenushechka** [comment]
Hello. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and we want to ensure that each PR has a chance to be merged and issues can be addressed.
Is this PR still targeting the 1.29 release?

**Comment by chendave** [comment]
> best we can do in kubeadm is make that API call polled.
FTR, the API call exactly prior to this failing API call is already polled.

+1 to have the API call polled just as the API call with `adminClient`.

**Comment by neolit123** [comment]
> > best we can do in kubeadm is make that API call polled.
> > FTR, the API call exactly prior to this failing API call is already polled.
> 
> +1 to have the API call polled just as the API call with `adminClient`.

here is the kubeadm PR.
https://github.com/kubernetes/kubernetes/pull/121609

**Comment by neolit123** [comment]
> Hello. I want to echo that the code freeze is starting [01:00 UTC Wednesday 1st November 2023 / 18:00 PDT Tuesday 31st October 2023](https://everytimezone.com/s/24b27b03) (next week), and we want to ensure that each PR has a chance to be merged and issues can be addressed. Is this PR still targeting the 1.29 release?

we are tracking a failing test in this ticket and we can proceed with fixing this after code freeze is in effect.
i just submitted an associated fix PR here:
https://github.com/kubernetes/kubernetes/pull/121609

**Comment by Vyom-Yadav** [comment]
As the Alpha 3 release cut is approaching (2nd Nov)
/priority critical-urgent

**Comment by neolit123** [comment]
we have a couple of kubeadm passes here:
https://github.com/kubernetes/kubernetes/pull/121609

of the presubmit variant of this job:
pull-kubernetes-e2e-kind-kms 

this seems like a flake and not a failure, given the offending PR merged on the 27th and looking at the history of the periodic.

**Comment by cpanato** [comment]
@neolit123 we are having the similar issue with https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main-ci-artifacts

i saw in the logs


```
[2023-11-05 12:37:59] [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[2023-11-05 12:37:59] [kubelet-start] Starting the kubelet
[2023-11-05 12:38:39] error execution phase wait-control-plane: cannot obtain client: could not bootstrap the admin user in file admin.conf: unable to create ClusterRoleBinding: Post "https://34.36.83.170:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=10s": context deadline exceeded
[2023-11-05 12:38:39] To see the stack trace of this error execute with --v=5 or higher
[2023-11-05 12:38:39] 2023-11-05 12:38:39,989 - cc_scripts_user.py[WARNING]: Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts)
[2023-11-05 12:38:39] 2023-11-05 12:38:39,989 - util.py[WARNING]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
[2023-11-05 12:38:40] Cloud-init v. 23.3.1-0ubuntu1~22.04.1 finished at Sun, 05 Nov 2023 12:38:40 +0000. Datasource DataSourceGCE.  Up 101.69 seconds

```

I am not sure what I should do, could you help me? thanks

**Comment by chendave** [comment]
@cpanato Can you pls tell where is the the log you pasted above? I searched in this file: blob:https://prow.k8s.io/a2607897-aac4-4101-9317-b92a9b5c8aa1, and some other logs related with kubeadm but cannot find it.

The original issue is expected to be fixed by: https://github.com/kubernetes/kubernetes/pull/121609. It's now continuous green now: https://testgrid.k8s.io/sig-release-master-informing#periodic-kubernetes-e2e-kind-kms

But the log you pasted do point to the change we landed last week: https://github.com/kubernetes/kubernetes/pull/121305/files#diff-a2dacc345dc9d047bb6142103ed5e939748d644cc39af4d5d401713337665dd6R505

**Comment by neolit123** [comment]
> @neolit123 we are having the similar issue with https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-gcp#capg-conformance-main-ci-artifacts
> 
> i saw in the logs
> 
> ```
> [2023-11-05 12:37:59] [kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
> [2023-11-05 12:37:59] [kubelet-start] Starting the kubelet
> [2023-11-05 12:38:39] error execution phase wait-control-plane: cannot obtain client: could not bootstrap the admin user in file admin.conf: unable to create ClusterRoleBinding: Post "https://34.36.83.170:443/apis/rbac.authorization.k8s.io/v1/clusterrolebindings?timeout=10s": context deadline exceeded
> [2023-11-05 12:38:39] To see the stack trace of this error execute with --v=5 or higher
> [2023-11-05 12:38:39] 2023-11-05 12:38:39,989 - cc_scripts_user.py[WARNING]: Failed to run module scripts_user (scripts in /var/lib/cloud/instance/scripts)
> [2023-11-05 12:38:39] 2023-11-05 12:38:39,989 - util.py[WARNING]: Running module scripts_user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
> [2023-11-05 12:38:40] Cloud-init v. 23.3.1-0ubuntu1~22.04.1 finished at Sun, 05 Nov 2023 12:38:40 +0000. Datasource DataSourceGCE.  Up 101.69 seconds
> ```
> 
> I am not sure what I should do, could you help me? thanks

@cpanato 
kubeadm introduced a new step in the "init" process. it creates an admin.conf file but it needs RBAC for it.
this RBAC is created in a rather complicated manner (with a fallback), but in your case it's failing at the first step where the API server is not reachable in 40 seconds.

https://github.com/kubernetes/kubernetes/blob/24e6b037800953d2cf9c621c6ffe2cf0de20d879/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L659

do you expect the API server to no be ready in 40 seconds?
are you sure there are no other problems with the setup and it just ends up failing at this first API server step where RBAC is created?

@chendave 
i wonder if we can just stop returning this error and fallback to the super-admin.conf "create" attempt later:
https://github.com/kubernetes/kubernetes/blob/24e6b037800953d2cf9c621c6ffe2cf0de20d879/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L665-L667

this will allow for more time for certain setups to start.
...but i added it exactly to catch problems like the one @cpanato is reporting - no connectivity to the API server.

**Comment by neolit123** [comment]
@cpanato 
also note that the kubeadm CP provider in CAPI does not yet support this feature and the upgrade CAPI jobs are also failing:
https://github.com/kubernetes-sigs/cluster-api/issues/9578

https://github.com/kubernetes-sigs/cluster-api/issues/9578

> Issues specific to the Kubernetes minor release:
> https://github.com/kubernetes/enhancements/pull/4302. (assuming change is merged for 1.29.

**Comment by neolit123** [comment]
> @chendave i wonder if we can just stop returning this error and fallback to the super-admin.conf "create" attempt later:
> 
> https://github.com/kubernetes/kubernetes/blob/24e6b037800953d2cf9c621c6ffe2cf0de20d879/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L665-L667
> 
> this will allow for more time for certain setups to start - 40 + 40 seconds. ... added it exactly to catch problems like the one @cpanato is reporting - no early connectivity to the API server. but if this is now the "first thing" in kubeadm, it might have introduced a bit of a timeout regression for slower setups.

actually, the feature seems change the order of "init":

```
[kubelet-start] Starting the kubelet
I1106 07:33:02.737117    5559 waitcontrolplane.go:83] [wait-control-plane] Waiting for the API server to be healthy
I1106 07:33:02.740886    5559 kubeconfig.go:606] ensuring that the ClusterRoleBinding for the kubeadm:cluster-admins Group exists
I1106 07:33:10.329549    5559 kubeconfig.go:682] creating the ClusterRoleBinding for the kubeadm:cluster-admins Group by using super-admin.conf
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 2.504095 seconds
```

it waits for the apiserver + kubelet ([separate go routines](https://github.com/kubernetes/kubernetes/blob/24e6b037800953d2cf9c621c6ffe2cf0de20d879/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go#L82), 40seconds for kubelet) and the RBAC create ([main thread](https://github.com/kubernetes/kubernetes/blob/24e6b037800953d2cf9c621c6ffe2cf0de20d879/cmd/kubeadm/app/cmd/phases/init/waitcontrolplane.go#L83-L98) when the first client() creation happens) at the same time.

i think what has to be changed here is:
1. remove the parallel aspect of the apiserver + kubelet wait. it has been difficult to manage and confusing.
2. somehow delay the RBAC create to be after the apiserver + kubelet waiting is done.

maybe something i can do for .29 is 2. but 1 is a bigger refactor.

**Comment by neolit123** [comment]
PR with an attempt to improve the kubeadm wait logic:
https://github.com/kubernetes/kubernetes/pull/121743

@cpanato i do think CAPG has unrelated problems.

**Comment by sbueringer** [comment]
Had some discussion with Carlos. I didn't follow this issue here in full detail, but probably the CAPG issue is resolved by the PR that we merged in core CAPI and will be part of the CAPI rc next week
