### ISSUE TITLE
IPv6 and dual stack Azure tests failing to pull image with k8s HEAD 

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/kubernetes#121550]
### Which jobs are failing?

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-conformance-dual-stack-k8s-ci-main
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-pr-conformance-ipv6-k8s-ci-main
https://testgrid.k8s.io/provider-azure-master-signal#capz-conformance-ipv6
https://testgrid.k8s.io/provider-azure-master-signal#capz-conformance-dual-stack

### Which tests are failing?

Cluster nodes are not becoming ready because pods are failing to pull images

### Since when has it been failing?

10/24

### Testgrid link

See above

### Reason for failure (if possible)

Calico tigera install pod is failing to start with

```
  Warning  Failed     16m (x4 over 18m)    kubelet            Error: ErrImagePull
  Warning  Failed     16m                  kubelet            Failed to pull image "mcr.microsoft.com/oss/tigera/operator:v1.30.4": failed to pull and unpack image "mcr.microsoft.com/oss/tigera/operator:v1.30.4": failed to resolve reference "mcr.microsoft.com/oss/tigera/operator:v1.30.4": failed to do request: Head "https://mcr.microsoft.com/v2/oss/tigera/operator/manifests/v1.30.4": dial tcp: lookup mcr.microsoft.com on 127.0.0.53:53: read udp 127.0.0.1:49168->127.0.0.53:53: read: connection refused``
```

https://[storage.googleapis.com/kubernetes-jenkins/logs/capz-conformance-dual-stack-master/1717271719137251328/artifacts/clusters/capz-conf-qx382v/tigera-operator/tigera-operator-776f4dcbf5-jv28v/pod-describe.txt](https://storage.googleapis.com/kubernetes-jenkins/logs/capz-conformance-dual-stack-master/1717271719137251328/artifacts/clusters/capz-conf-qx382v/tigera-operator/tigera-operator-776f4dcbf5-jv28v/pod-describe.txt)

Note: this is not a specific issue with that image, other pods have pre-pulled images on the VM image, it just happens that this is the first image getting pulled (other pods are stuck pending since the node CNI is not ready).

### Anything else we need to know?

the exact same release-1.28 branch (+ all other branches) jobs are passing so this is likely only an issue with k8s main branch
[provider-azure-1.28-signal Test Grid (k8s.io)](https://testgrid.k8s.io/provider-azure-1.28-signal#capz-conformance-dual-stack)

equivalent logs in the tigera operator pod:

```
  Normal  Scheduled  16m   default-scheduler  Successfully assigned tigera-operator/tigera-operator-776f4dcbf5-gxpfz to capz-conf-mlf5pt-control-plane-w5r4h
  Normal  Pulling    16m   kubelet            Pulling image "mcr.microsoft.com/oss/tigera/operator:v1.30.4"
  Normal  Pulled     16m   kubelet            Successfully pulled image "mcr.microsoft.com/oss/tigera/operator:v1.30.4" in 2.555s (2.556s including waiting)
  Normal  Created    16m   kubelet            Created container tigera-operator
  Normal  Started    16m   kubelet            Started container tigera-operator
```

The equivalent job for IPv4 is also passing: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-azure#capz-periodic-conformance-k8s-ci-main

### Relevant SIG(s)

/sig network

**Comment by CecileRobertMichon** [comment]
Looking at the last test pass and the first failure, it looks like the breakage happened sometime between https://github.com/kubernetes/kubernetes/commit/c6b3a2f477c9ed051ace8ae1c479424e4a5c066d and https://github.com/kubernetes/kubernetes/commit/88c0a8be1bde10e2ce9887af5de0ea2b6706ddd5

**Comment by uablrek** [comment]
> read udp 127.0.0.1:49168->127.0.0.53:53: read: connection refused

Points in the DNS direction

**Comment by uablrek** [comment]
Since this is an image pull, the lookup should be done from main netns. So, please check /etc/resolv.conf on the node and with netstat for port 53.

If this is kind of a "strict" ipv6, please verify that the local DNS server (at 127.0.0.53) really opens for ipv4 and ipv6, and not only ipv6.

**Comment by CecileRobertMichon** [comment]
@uablrek thank you for the pointers. I did check your suggestions above but I'm not seeing anything standout:

```
nslookup google.com 168.63.129.16
Server:         168.63.129.16
Address:        168.63.129.16#53

Non-authoritative answer:
Name:   google.com
Address: 142.251.167.139
Name:   google.com
Address: 142.251.167.100
Name:   google.com
Address: 142.251.167.138
Name:   google.com
Address: 142.251.167.102
Name:   google.com
Address: 142.251.167.113
Name:   google.com
Address: 142.251.167.101
Name:   google.com
Address: 2607:f8b0:4004:c1b::65
Name:   google.com
Address: 2607:f8b0:4004:c1b::71
Name:   google.com
Address: 2607:f8b0:4004:c1b::8a
Name:   google.com
Address: 2607:f8b0:4004:c1b::66
```

```
cat /etc/resolv.conf
# This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients directly to
# all known uplink DNS servers. This file lists all configured search domains.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

nameserver 168.63.129.16
search 2xa33mey1nfufhx0flupj2ugjf.bx.internal.cloudapp.net
```

However, I did find that the underlying VM image changed between the time the last successful test and the first failing test. That seems to be the likely cause, rather than a k8s commit. One of the changes in the image that stands out to me is a [bump of containerd from 1.6.23 to 1.7.6](https://github.com/kubernetes-sigs/image-builder/commit/9988c4af8141ab2e8f6ec0b91d53db0db0c38a10).

**Comment by CecileRobertMichon** [comment]
Confirmed it's the containerd version:

On a live repro built with containerd 1.7.6, I ssh'd on the node and installed containerd 1.6.23 and restarted containerd. The image immediately got pulled successfully after failing to pull for 2 days:

```
  Normal  BackOff  44m (x17928 over 2d20h)  kubelet  Back-off pulling image "mcr.microsoft.com/oss/tigera/operator:v1.30.4"
  Normal  Pulled   39m                      kubelet  Successfully pulled image "mcr.microsoft.com/oss/tigera/operator:v1.30.4" in 2.73s (2.73s including waiting)
```

**Comment by CecileRobertMichon** [comment]
/close

This is due to a new containerd version being used causing a race condition due to a new go version and a workaround that was previously in place: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4209
