### ISSUE TITLE
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged k8ssandra-0-control-plane kubeadm init --skip-phases=preflight --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 1

### ISSUE THREAD

**Issue by raphael10-collab** [kubernetes/kubernetes#121644]
### What happened?

I've been told my `k8ssandra` people that the following errors are related to `kubernetes` 

What do I have to do to detect, and solve, the issue?

`kind` seems working fine:

    root@k8s-eu-1-master:~# kind create cluster
    Creating cluster "kind" ...
     ✓ Ensuring node image (kindest/node:v1.27.3) 🖼 
     ✓ Preparing nodes 📦  
     ✓ Writing configuration 📜 
     ✓ Starting control-plane 🕹️ 
     ✓ Installing CNI 🔌 
     ✓ Installing StorageClass 💾 
    Set kubectl context to "kind-kind"
    You can now use your cluster with:
    kubectl cluster-info --context kind-kind

    root@k8s-eu-1-master:~# kubectl cluster-info --context kind-kind
    Kubernetes control plane is running at https://127.0.0.1:41237
    CoreDNS is running at https://127.0.0.1:41237/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
 
    root@k8s-eu-1-master:~# kind get clusters
    kind

But I'm getting these errors : 

    root@k8s-eu-1-master:~/go/bin/k8ssandra-operator# scripts/setup-kind-multicluster.sh --clusters 1 --kind-worker-nodes 5
    Creating 1 clusters...
    Creating cluster 1 out of 1
    Creating cluster "k8ssandra-0" ...
     ✓ Ensuring node image (kindest/node:v1.25.3) 🖼
     ✓ Preparing nodes 📦 📦 📦 📦 📦 📦  
     ✓ Writing configuration 📜 
     ✓ Starting control-plane 🕹️ 
     ✓ Installing CNI 🔌 
     ✓ Installing StorageClass 💾 
     ✗ Joining worker nodes 🚜 
    Deleted nodes: ["k8ssandra-0-worker" "k8ssandra-0-worker3" "k8ssandra-0-worker5" "k8ssandra-0-control-plane" "k8ssandra-0-worker2" "k8ssandra-0-worker4"]
    ERROR: failed to create cluster: failed to join node with kubeadm: command "docker exec --privileged k8ssandra-0-worker5 kubeadm join --config /kind/kubeadm.conf --skip-phases=preflight --v=6" failed with error: exit status 1

This is the complete log: 
https://drive.google.com/file/d/1t0LAX5TtunnNYLbCVXeQ1x1pBIIL9dxv/view?usp=sharing

This is the ouput of cluster-info dump :  
https://drive.google.com/file/d/1RPenPw6ki6cCORMrpfOJqm89wFo_G-xN/view?usp=drive_link

### What did you expect to happen?

kind cluster configured correctly

### How can we reproduce it (as minimally and precisely as possible)?

This is the complete log: 
https://drive.google.com/file/d/1t0LAX5TtunnNYLbCVXeQ1x1pBIIL9dxv/view?usp=sharing

This is the ouput of cluster-info dump :  
https://drive.google.com/file/d/1RPenPw6ki6cCORMrpfOJqm89wFo_G-xN/view?usp=drive_link

### Cluster information:

Kubernetes version:

    root@k8s-eu-1-master:~# kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.27.3

### Cloud provider

Cloud being used: (put bare-metal if not on a public cloud)  : bare-metal : Contabo Cloud : 3 XL VPS + 3 S VPS

### OS version

    root@k8s-eu-1-master:~# cat /etc/os-release
    PRETTY_NAME="Ubuntu 22.04.3 LTS"
    NAME="Ubuntu"
    VERSION_ID="22.04"
    VERSION="22.04.3 LTS (Jammy Jellyfish)"
    VERSION_CODENAME=jammy
    ID=ubuntu
    ID_LIKE=debian
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    UBUNTU_CODENAME=jammy

### Install tools

I followed the steps described here:  https://www.linuxtechi.com/install-kubernetes-on-ubuntu-22-04/

### Container runtime (CRI) and version (if applicable)

    CRI and version: 
    
        root@k8s-eu-1-master:~# containerd version
        INFO[2023-10-31T11:26:54.962841985+01:00] starting containerd                               
        revision=61f9fd88f79f081d64d6fa3bb1a0dc71ec870523 version=1.6.24

### Related plugins (CNI, CSI, ...) and versions (if applicable)

    CNI and version:
    
        root@k8s-eu-1-master:~# ls /etc/cni/net.d
        10-calico.conflist  calico-kubeconfig

**Comment by neolit123** [comment]
/remove-sig cluster-lifecycle network

kind issues must be posted in the kubernetes-sigs/kind repository.
/close

you can also try #kind on k8s slack for support.
