### ISSUE TITLE
Rename GCE target pools and forwarding rules to match $CLUSTERNAME prefix convention

### ISSUE THREAD

**Issue by alex-mohr** [kubernetes/kubernetes#12165]
Most GCE resources that k8s creates have a prefix of $CLUSTERNAME, which allows people to get a basic understanding of why a resource exists and what it's used for.  Target pools and forwarding rules do not, which is an ongoing tax with running jenkins tests along with a poor UX.

We should rename them to match convention.

And we should be backwards-compatible so that existing clusters can be upgraded.

**Comment by kargakis** [comment]
@kubernetes/sig-cluster-lifecycle-misc

**Comment by roberthbailey** [comment]
@kubernetes/sig-network-misc as well

**Comment by roberthbailey** [comment]
target pools and forwarding rules are network, and not cluster lifecycle. I'll let @bowei et. al decide if this should remain open.
