### ISSUE TITLE
Mesos-Docker cluster should cache certificates/keys/tokens

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kubernetes#12164]
Once #10049 is merged, the mesos-docker cluster scripts will be generating several certificates & keys, for development use. 

Optimally, these should be cached in a location outside of the repo.

Possible cache location: `~/.kube/cluster/mesos/docker/`

Reasons:
- (slightly) speed up deployment 
- allow the user to supply their own certs/keys
- reuse keys across deployments

xref https://github.com/mesosphere/kubernetes-mesos/issues/443

**Comment by jdef** [comment]
tracking this in kubernetes-mesos, closing here for now
