### ISSUE TITLE
Dualstack Service endpoints are only from one IP family 

### ISSUE THREAD

**Issue by lzhecheng** [kubernetes/kubernetes#121631]
### What happened?

For a dualstack Service, its endpoints are only from one IP family.
```
	if len(svc.Spec.IPFamilies) > 0 {
		// controller is connected to an api-server that correctly sets IPFamilies
		ipFamily = svc.Spec.IPFamilies[0] // this works for headful and headless
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/endpoint/endpoints_controller.go#L207-L213

But from the enhancement doc, it should have endpoints of 2 IP families.
```
2 single-family endpoints per backend pod: Make no change to the [Kubernetes Endpoints API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#endpoints-v1-core). Treat each IPv4/IPv6 address as separate, distinct endpoints, and include each address in the comma-separated list of addresses in an 'Endpoints' API object.
```
```
Given a phased approach, the 2 single-family endpoint approach represents the least disruptive change. Services will select only the endpoints that match the spec.ipFamily defined in the Service.
```
https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/563-dual-stack#endpoints

There's a gap between code and doc.

### What did you expect to happen?

Endpoints of 2 IP families should be in a Service's endpoints.

### How can we reproduce it (as minimally and precisely as possible)?

Create a dualstack cluster and create a dualstack Service.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"31eb725f9812713ec7fd6cf293466ce4fdc7efa8", GitTreeState:"clean", BuildDate:"2023-10-09T14:42:41Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>
cloud-provider-azure 1.27.3
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by lzhecheng** [comment]
@khenidak could you take a look?

**Comment by aojea** [comment]
/close

This is working as intended, EndpointSlices have dual stack addresses, Endpoints are always single-stack
