### ISSUE TITLE
Cleanup for apps e2e tests: do not use deprecated pointer package

### ISSUE THREAD

**Issue by mimowo** [kubernetes/kubernetes#121690]
/kind cleanup 
/good-first-issue
/sig-apps

Replace usages of "k8s.io/utils/pointer" with "k8s.io/utils/ptr".
The old one is currently used for:
- job: https://github.com/kubernetes/kubernetes/blob/227d1b2357d93a6884addccb50122df16674ca95/test/e2e/apps/job.go#L52
- stateful set: https://github.com/kubernetes/kubernetes/blob/227d1b2357d93a6884addccb50122df16674ca95/test/e2e/apps/statefulset.go#L60
- controller_revision: https://github.com/kubernetes/kubernetes/blob/227d1b2357d93a6884addccb50122df16674ca95/test/e2e/apps/controller_revision.go#L44

**Comment by mimowo** [comment]
FYI @alculquicondor @kannon92 
/good-first-issue

**Comment by guidovisk1** [comment]
Hello guys, I´m tryng to get my frist issue in Open Source using go. Is this a good one to start?

**Comment by mimowo** [comment]
Hi, I think so, thus the `good-first-issue` label. However, it is already taken (see `/assign` above).

Hint: try to search for issues with the `label:"good first issue"` param. Then, either grab some without assignee or ask if the assignee about progress, if the issue seems stale. Feel free to also reach out on slack.

**Comment by guidovisk1** [comment]
Ok, that was a great tip. I will do it!

**Comment by pohly** [comment]
Before we start merging PRs for this, can we clarify how large each PR for this should be? This issue can be addressed more or less automatically with a global search/replace + gofmt,  but each PR is manual review work and costs resources for testing.

I'd say let's do one PR for everything and then split that up...

**Comment by pohly** [comment]
@mimowo was this already discussed somewhere?

**Comment by mimowo** [comment]
> @mimowo was this already discussed somewhere?

Not discussed. I opened this issue dedicated to sig-apps which already narrows the scope, and the PR is small: https://github.com/kubernetes/kubernetes/pull/121694. However, I'm also happy extending the scope and doing something more automatic. WDYT?

**Comment by pohly** [comment]
To be honest, I'd prefer to not change anything. It's not worth the churn.

**Comment by mimowo** [comment]
> To be honest, I'd prefer to not change anything. It's not worth the churn.

I see, I noticed that approach taken here https://github.com/kubernetes/kubernetes/pull/120951, and thought as a good idea to follow here, so it does not cross the functions in UI (vs-code). Anyway, I'm also ok with closing / another more hollistic approach.

**Comment by kannon92** [comment]
We have been changing these in this release.  I was told/have told people to keep the PRs small and limited to a single sig.  That way we only need a single approver.  There were large ones that were opened but it was difficult to get approvers across multie sigs.  

I ended up openeing that PR because if one tries to use pointer, the linter says it is deprecated.  So we end up using the new ptr package but the rest of the code is using the deprecated one.  I figured opening up a PR that switches these over at least allows people to know which package to use in the future.

**Comment by kannon92** [comment]
https://github.com/kubernetes/kubernetes/pull/120631#issuecomment-1717628223 for example.  PR is still waiting for final approval so I thought keeping them more targeted has helped.

**Comment by mimowo** [comment]
I think if we close the specific issue for sig-apps I prefer it is replaced with something more holistic so that we don't accumulate the deprecated functions. 

Working with deprecated functions in UI is one reason. Working with them during code review is another. Keeping the diffs small means, in some cases, using two types of packages in the same function, which seems awkward to me.

**Comment by mimowo** [comment]
> [#120631 (comment)](https://github.com/kubernetes/kubernetes/pull/120631#issuecomment-1717628223) for example. PR is still waiting for final approval so I thought keeping them more targeted has helped.

I'm also leaning towards small PRs per sig, so that we don't need to bother top-level approvers (as in the referenced case), which increases the churn for them,

**Comment by mimowo** [comment]
> Can you ask on #k8s-code-organization about this issue specifically?

Sure, started the thread: https://kubernetes.slack.com/archives/CHGFYJVAN/p1699022254366619

**Comment by mimowo** [comment]
/close
As per slack thread. The old packages are meant to stay, so there is no need to switch. If it makes coding easier, the switch can be justified as a preparatory PR.

**Comment by raminderis** [comment]
> Hi, I think so, thus the `good-first-issue` label. However, it is already taken (see `/assign` above).
> 
> Hint: try to search for issues with the `label:"good first issue"` param. Then, either grab some without assignee or ask if the assignee about progress, if the issue seems stale. Feel free to also reach out on slack.

@mimowo which slack channel should we use for such an ask. k/k has so many its hard for new people like me to figure out which channel is which. is there a document that explains these channels so what. thanks for your reply in advance.
