### ISSUE TITLE
Retry the Docker image pull

### ISSUE THREAD

**Issue by gyuvaraj10** [kubernetes/kubernetes#121693]
### What would you like to be added?

Due to transient issues with the infrastructure sometimes the docker image pull fails and in the current version of Kubernetes there is no ability to retry the Docker image pull when it fails due to transient issues such as Network issues. At present this is handled manually where the production support person will do a retry of it.

### Why is this needed?

1. Reduce the Turn around time 
2.  Replace manual effort in retrying

**Comment by neolit123** [comment]
what is this feature request for -
kubelet, kubeadm or something else?

what version of k8s?

docker is no longer supported, are you using cri-dockerd?

**Comment by gyuvaraj10** [comment]
Hi @neolit123  Please find the following details.

Feature request for kubelet 
K8s : 1.27.x
Container Runtime used: using containerd instead of the docker.

**Comment by dims** [comment]
https://www.google.com/search?q=ImagePullBackOff
https://github.com/kubernetes/kubernetes/blob/ca5c522080bc62e2e6387516a605c24bb513256b/SUPPORT.md

/close

**Comment by gyuvaraj10** [comment]
@dims , Can you please let me know why this issue is closed? why can't we have this feature available?

**Comment by dims** [comment]
@gyuvaraj10 this is a problem with your environment with your setup (registry / kubelet / containerd knobs), we already have image back off to retry. 

If you can prove that is this a bug with a reproduction, that's one thing. If you can figure out that all the existing stuff is not enough and you really need a feature/enhancement then the process is https://github.com/kubernetes/enhancements

(this repository is NOT for support for your cluster, if you do use a managed service provider, please contact them as well)
