### ISSUE TITLE
performance test for 5000 nodes shows LoadInitEventsCount change a lot

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121668]
https://perf-dash.k8s.io/#/?jobname=aws-5000Nodes&metriccategoryname=APIServer&metricname=LoadInitEventsCount&resource=pods

A potential performance change from 09-19  to 09-21.

https://github.com/kubernetes/kubernetes/pulls?q=merged%3A2023-09-19..2023-09-21+-label%3Acherry-pick-approved+

Regression of watch bookmarks?

/cc @wojtek-t 

@kubernetes/sig-scalability-bugs

did we change the infra ?

**Comment by pacoxu** [comment]
https://github.com/kubernetes/test-infra/pull/30787
https://github.com/kubernetes/test-infra/pull/30754
/cc @dims 
It may be related to some bump changes in test infra.
If so, feel free to close it.

**Comment by wojtek-t** [comment]
the AWS tests weren't official at that point (are they already at this point?) @shyamjvs
