### ISSUE TITLE
Proxy (ssh-tunnel) errors are not helpful when we have 0 tunnels.

### ISSUE THREAD

**Issue by cjcullen** [kubernetes/kubernetes#12167]
If the master can't open any ssh tunnels, requests that go through the proxy (kubectl logs, kube UI, ...) return an unhelpful "Empty tunnel list" error.

There are several reasons why the master may end up with an empty tunnel list. It would be nice if we surfaced these reasons to give some hope at debuggability.

**Comment by timothysc** [comment]
cc @jwforres

**Comment by pnovotnak** [comment]
bump

**Comment by tmandry** [comment]
Currently running into this with `kubectl exec`. I have no idea what the problem is.

**Comment by smreed** [comment]
Not sure if anybody seeing this is on GCE, but we were, and it was because our project was at its limit for metadata. We had a ton of old ssh keys that were just taking up space, removed them, tunnels appeared and the cluster recovered.

**Comment by SergeyCherepanov** [comment]
Hi, I have this error on GCE.

How I can know cause of issue and resolve it?

**Comment by csaintc** [comment]
Same, I get it when I attempt to retrieve logs.

**Comment by vincentheet** [comment]
I had the same issue and followed the advice of @smreed 
Since our build servers makes connections to GKE for some builds a ssh key is stored every build in the metadata of GCE. When the metadata is full (32KB) it will give you the 'empty tunnel list' error. What I did was going to the Google Developer Console and cleaning the list of SSH Keys which you can find here: Google Developer Console > Compute > Compute Engine > Metadata > SSH Keys
After deleting the old ssh keys everything worked again.

**Comment by bradfordcp** [comment]
I am seeing this issue with only a single SSH key inside of Compute Engine Metadata.

**Comment by nckturner** [comment]
Saw this in GKE with a lot of keys in metadata.  Deleted the majority of the keys and everything worked again.

**Comment by kevinliuzhong** [comment]
`kubectl logs` works fine, but can not `kubectl exec`, I am installing k8s cluster on azure.
BTW, how can I print detail response of internal error?
```
kubectl exec --v=6 nfs ls
I1127 10:15:08.338980    4120 debugging.go:120] GET https://example.com:6443/api 200 OK in 6333 milliseconds
I1127 10:15:08.350207    4120 debugging.go:120] GET https://example.com:6443/api/v1/namespaces/default/pods/nfs 200 OK in 8 milliseconds
I1127 10:15:08.351973    4120 exec.go:179] defaulting container name to nfs
I1127 10:15:10.931260    4120 debugging.go:120] POST https://example.com:6443/api/v1/namespaces/default/pods/nfs/exec?command=ls&container=nfs&container=nfs&stderr=true&stdout=true 500 Internal Server Error in 2227 milliseconds
F1127 10:15:10.931503    4120 helpers.go:96] error: unexpected response status code 500 (Internal Server Error)
```

**Comment by nckturner** [comment]
Seeing this again, deleted all metadata keys to no avail.

**Comment by bradfordcp** [comment]
@nckturner do you have any keys on the instance level or just the project level? When I had a single key on the instance level.

**Comment by nckturner** [comment]
@bradfordcp Just the project level, but not anymore.

**Comment by cjcullen** [comment]
I've seen three failure modes for this issue:

1. **Project level metadata is full, GKE cannot add its SSH key.** GCE has a [32 KB limit](https://cloud.google.com/compute/docs/metadata?hl=en#custom) on metadata values.

    **Solution**: Remove unused SSH keys.

2. **Node(s) with instance-level SSH keys set.** GCE allows instance-level SSH keys to override project-level keys. In this case `gcloud compute ssh` will also fail.

    **Solution**: Remove instance-level SSH Keys, or manually add GKE's SSH key to the instance-level metadata.

3. **SSH is firewalled.** By default, GKE creates a firewall rule to give the master SSH access to the nodes, but it is possible to delete that rule.

    **Solution**: Re-add a firewall rule that allows tcp:22 from the GKE master's IP.

I think Google Cloud [User Accounts](https://cloud.google.com/compute/docs/access/user-accounts/) will provide a better way to make this harder to break. That feature is still in beta, so we can't yet rely on it for a general solution.

**Comment by nckturner** [comment]
@cjcullen None of these seem to apply.  We just deleted all the ssh keys from the project metadata, we have never added any keys at the instance level, and I have confirmed the ssh firewall rule is still there.  FWIW, gcloud ssh works fine.

**Comment by cjcullen** [comment]
:/
The 4th failure mode I've also seen is "Other/Unknown". If it isn't any of those first three, you could look in `/var/log/auth.log` on your nodes for anything suspicious. Sometimes rebooting nodes (or deleting and waiting for the instance group to re-add) is enough to get things working.

Let me know what you find out.

**Comment by mbmccoy** [comment]
Bump. 

I just had this problem, and I would put it under "Other/Unknown" given the sparsity of our metadata/keys.

It happened after GKE created some extra oddly-named pods during a rolling-upgrade. (They had names like `usual-name-6d494c8ca4d9becd7e3e3d9d2ae000ba-uax4d`. The long hash in the middle is unusual, the short trailing nonce is standard.) I nuked these extra pods and then couldn't view my logs.

I wasn't too invested in the cluster so I just nuked it and started over. :/

**Comment by GavinYYY** [comment]
I solved the problem，just executing   iptables -F.

**Comment by cjcullen** [comment]
The flakiness of tunnels has been reduced, and the error message has been updated. Closing.

**Comment by fredbwang** [comment]
> I solved the problem, just executing iptables -F.

Where did you execute this command? Can I have more details on how you solve this?
