### ISSUE TITLE
RBAC return 403 Forbidden after restarting APIServer when there is a large amount of

### ISSUE THREAD

**Issue by miaojianwei** [kubernetes/kubernetes#121635]
### What happened?

Pod access APIServer normal at beginning, but after restarting APIServer, the access returns 403 in a few minutes at the begining of APIServer became ready.

`"HTTP" verb="GET" URI="/api/v1/namespaces/nsxxx/configmaps?resourceVersion=970285583&allowWatchBookmarks=true&watch=true" latency="1.097754946s" userAgent="xxx" srcIP="xxx" resp=403 contentType="application/json" requestID="xxx"`

### What did you expect to happen?

The access returns 200 after APIServer become ready.

### How can we reproduce it (as minimally and precisely as possible)?

First create over fifty thousand rolebindings in the same namespace, then use one role in that namespace access apiserver with RBAC authorization will return 200.
At this point, restart the APIServer and access it immediately after it is running, then apiserver will return 403.

### Anything else we need to know?

I debug the code of rbac and found during authorization, APIServer would list all rolebindings in the informer to find the role binding to user. However, at the beginning of startup, due to the large number of rolebindings, the informer was not yet fully synced, so cannot find the role binding to the request user, then return 403.
I think the APISever should wait for rbac versionedInformers cache sync before serving.

### Kubernetes version

<details>

```console
$ kubectl version
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by liggitt** [comment]
API server already waits for informer sync before returning healthy. A load balancer waiting for the server to be healthy before routing to it would not encounter this. I don't really think a single server should wait for informers to sync before serving any endpoints.
