### ISSUE TITLE
Fix golangci-lint-pr-hints test

### ISSUE THREAD

**Issue by kiashok** [kubernetes/kubernetes#121660]
### What happened?

Looks like the golangci-lint-pr-hints linter was updated recently to put the feature gate comment ahead of the owner field in pkg/features/kube_features.go

All the feature gates in pkg/features/kube_features.go are ordered by the following comments:

	// owner: 
	// kep: 
	// alpha: 
	// beta: 
	//
       // Describe the feature gate
      <declare the feature gate> 
 
The new linter changes now requires that the comment describing the feature gate should even precede the owner comment line which goes against the structure followed by the entire file and this needs to be fixed

### What did you expect to happen?

Feature gates should be ordered as follows to maintain parity with the rest of pkg/features/kube_features.go

	// owner: 
	// kep: 
	// alpha: 
	// beta: 
	//
       // Describe the feature gate
      <declare the feature gate> 

### How can we reproduce it (as minimally and precisely as possible)?

Update/add new feature gate to pkg/features/kube_features.go

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

master branch of k8s/k8s

### Cloud provider

<details>

</details>
N/A

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kiashok** [comment]
https://github.com/kubernetes/kubernetes/pull/121456 

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121456/pull-kubernetes-linter-hints/1719487886656540672

![image](https://github.com/kubernetes/kubernetes/assets/99994218/5f262f84-7583-4f40-9851-2238db3fce8e)

**Comment by kiashok** [comment]
cc @kannon92 @jsturtevant @dims

**Comment by dims** [comment]
cc @pohly

**Comment by neolit123** [comment]
> Looks like the golangci-lint-pr-hints linter was updated recently to put the feature gate comment ahead of the owner field in pkg/features/kube_features.go

it was supposed to only apply to cmd/kubeadm.

**Comment by kannon92** [comment]
Thank you @pohly for fixing that.

**Comment by pohly** [comment]
If I break it, I fix it... :hot_face:
