### ISSUE TITLE
Implement RequiredDuringSchedulingRequiredDuringExecution for node affinity.

### ISSUE THREAD

**Issue by AxeZhan** [kubernetes/kubernetes#121758]
### What would you like to be added?

I'd like to try to implement `RequiredDuringSchedulingRequiredDuringExecution` for node affinity in next release :)

### Why is this needed?

We mentioned `requiredDuringSchedulingRequiredDuringExecution` before(https://github.com/kubernetes/kubernetes/issues/96149), and it may help in some scenarios.

I drafted a simple kep to discuss feasibility. https://github.com/kubernetes/enhancements/issues/4328

**Comment by neolit123** [comment]
why not reopen https://github.com/kubernetes/kubernetes/issues/96149  and close this ticket ?
it has the history of the feature plan since 2020?

**Comment by AxeZhan** [comment]
> /remove-sig node

I think this is mainly a sig-node KEP, as we aim to add a new controller related to node labels?

**Comment by chendave** [comment]
/sig node

this is primarily a sig-node change, @AxeZhan maybe this one could be closed in favor of https://github.com/kubernetes/kubernetes/issues/96149?

**Comment by AxeZhan** [comment]
> this is primarily a sig-node change, @AxeZhan maybe this one could be closed in favor of #96149?

Yea.. Sounds reasonable since I already reopened #96149
