### ISSUE TITLE
Kubernetes Proxy Service restarted but IP tables is not loaded

### ISSUE THREAD

**Issue by devendra614** [kubernetes/kubernetes#121726]
Hi Great Team,

I have faces IP table is not loaded after worker node reboot. Kube-proxy services is restarted automatically but IP tables is not loaded.
Please suggest IP tables loading automatically after reboot of worker node.

1>
 ========
#systemctl status kube-proxy

● kube-proxy.service - Kubernetes Kube Proxy
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-11-02 23:38:04 IST; 1min 54s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 6315 (kube-proxy)
    Tasks: 14
   Memory: 21.5M
   CGroup: /system.slice/kube-proxy.service
           └─6315 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/kube-proxy-config.yaml

Nov 02 23:38:04 hostname kube-proxy[6315]: E1102 23:38:04.959564    6315 proxier.go:1507] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.4.21: Co...or directory
Nov 02 23:38:04 hostname kube-proxy[6315]: Error occurred at line: 141
Nov 02 23:38:04 hostname kube-proxy[6315]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Nov 02 23:38:04 hostname kube-proxy[6315]: )
Nov 02 23:38:04 hostname kube-proxy[6315]: I1102 23:38:04.959679    6315 proxier.go:779] Sync failed; retrying in 30s
Nov 02 23:38:04 hostname kube-proxy[6315]: E1102 23:38:04.993053    6315 proxier.go:1507] Failed to execute iptables-restore: exit status 2 (iptables-restore v1.4.21: Co...or directory
Nov 02 23:38:04 hostname kube-proxy[6315]: Error occurred at line: 100
Nov 02 23:38:04 hostname kube-proxy[6315]: Try `iptables-restore -h' or 'iptables-restore --help' for more information.
Nov 02 23:38:04 hostname kube-proxy[6315]: )
Nov 02 23:38:04 hostname kube-proxy[6315]: I1102 23:38:04.993148    6315 proxier.go:779] Sync failed; retrying in 30s
Hint: Some lines were ellipsized, use -l to show in full.
===============

2>

I have manually restarted kube-proxy servers then it was restarted. Here is below command and status logs

● kube-proxy.service - Kubernetes Kube Proxy
   Loaded: loaded (/etc/systemd/system/kube-proxy.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-11-02 23:40:21 IST; 4s ago
     Docs: https://github.com/kubernetes/kubernetes
 Main PID: 18866 (kube-proxy)
    Tasks: 16
   Memory: 11.1M
   CGroup: /system.slice/kube-proxy.service
           └─18866 /usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/kube-proxy-config.yaml

Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.943855   18866 node.go:135] Successfully retrieved node IP: 10.94.240.62
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.943949   18866 server_others.go:145] Using iptables Proxier.
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.944287   18866 server.go:571] Version: v1.17.0
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.944639   18866 conntrack.go:52] Setting nf_conntrack_max to 262144
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.945189   18866 config.go:131] Starting endpoints config controller
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.945235   18866 shared_informer.go:197] Waiting for caches to sync for endpoints config
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.945282   18866 config.go:313] Starting service config controller
Nov 02 23:40:21 hostname kube-proxy[18866]: I1102 23:40:21.945290   18866 shared_informer.go:197] Waiting for caches to sync for service config
Nov 02 23:40:22 hostname kube-proxy[18866]: I1102 23:40:22.045392   18866 shared_informer.go:204] Caches are synced for endpoints config
Nov 02 23:40:22 hostname kube-proxy[18866]: I1102 23:40:22.045394   18866 shared_informer.go:204] Caches are synced for service config

**Comment by sftim** [comment]
/kind support

/close

I'm inferring that @devendra614 you were able to work out how to fix your cluster / affected node.
