### ISSUE TITLE
Issue with using feature HonorPVReclaimPolicy in csi-provisioner

### ISSUE THREAD

**Issue by reenakabra** [kubernetes/kubernetes#121799]
### What happened?

In my CSI controller I have enabled the feature gate HonorPVReclaimPolicy for csi-provisioner. 

Based on the documentation 
Finalizers can be added on a PersistentVolume to ensure that PersistentVolumes having Delete reclaim policy are deleted only after the backing storage are deleted.

The newly introduced finalizers kubernetes.io/pv-controller and external-provisioner.volume.kubernetes.io/finalizer are only added to dynamically provisioned volumes.

I can see the finalizer set on the PV while creating static Persistent Volume. PV deletion is stuck due to this finalizer

apiVersion: v1
kind: PersistentVolume
metadata:
  creationTimestamp: "2023-11-08T11:39:24Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-11-08T11:54:31Z"
  finalizers:
  - external-provisioner.volume.kubernetes.io/finalizer
  name: csi-infoscale-pv

### What did you expect to happen?

PV should be deleted when PVC is deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Persistent Volume yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-infoscale-pv
spec:
  storageClassName: csi-infoscale-sc-prod
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: org.veritas.infoscale
    # Please provide pre-provisioned Infoscale volume name.
    volumeHandle: clust_21432/vrts_kube_dg-21432/vol1
    fsType: vxfs

Persistent Volume Claim 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-infoscale-pvc-static
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-infoscale-sc-prod
  volumeName: csi-infoscale-pv

### Anything else we need to know?

Same thing works fine on OCP.

### Kubernetes version

# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:48:26Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.5", GitCommit:"93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c", GitTreeState:"clean", BuildDate:"2023-08-24T00:42:11Z", GoVersion:"go1.20.7", Compiler:"gc", Platform:"linux/amd64"}

### Cloud provider

Vanilla K8s setup

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
/sig storage
maybe similar issues should go in https://github.com/kubernetes-csi/external-provisioner

**Comment by reenakabra** [comment]
Opened similar issue in external-provisioner repo also
https://github.com/kubernetes-csi/external-provisioner/issues/1097

There is no reply on that as well. Can you please help understand the behavior of the feature HonorPVReclaimPolicy.

**Comment by niranjandarshann** [comment]
If you want  Persistent Volume (PV) to be deleted when the associated Persistent Volume Claim (PVC) is deleted, you donot need to use finalizers explicitly. Kubernetes handles this behavior by default.
It is ok that if you use to get the desire output using Finalizer we can do it.

**Comment by niranjandarshann** [comment]
As per my understanding Please follow the steps :
1.  Add finalizer in metadata of PV.yaml as you did above 
```
finalizers:
external-provisioner.volume.kubernetes.io/finalizer
name: csi-infoscale-pv
```
2. We need to make change in the controller which is handling PV deletion in .go file.
3.  See whether the controller administrator is working or not. 
  
 I think it will work.

**Comment by reenakabra** [comment]
Finalizer is added because the feature gate HonorPVReclaimPolicy for csi-provisioner is enabled. We are not adding the finalizer explicitly. 

From the documentation, 
"The newly introduced finalizers kubernetes.io/pv-controller and external-provisioner.volume.kubernetes.io/finalizer are only added to dynamically provisioned volumes."

Not sure why is the finalizer getting set. Also, for deleting PV it requires the annotation "pv.kubernetes.io/provisioned-by" but this annotation is set in case of dynamic PVs. Should it be set explicitly for static PV?

**Comment by xing-yang** [comment]
This feature is alpha so the feature gate is not enabled by default. Did you enable the feature gate `HonorPVReclaimPolicy` on kube-controller-manager?

**Comment by reenakabra** [comment]
Yes, i have enabled this feature.

**Comment by carlory** [comment]
> The newly introduced finalizers kubernetes.io/pv-controller and external-provisioner.volume.kubernetes.io/finalizer are only added to dynamically provisioned volumes.

external-provisioner.volume.kubernetes.io/finalizer is also applied to statically provisioned volumes.

FYI
- https://github.com/kubernetes-csi/external-provisioner/blob/2c62ba53a65d2f7ff113784a6628d58c808778fc/vendor/sigs.k8s.io/sig-storage-lib-external-provisioner/v9/controller/controller.go#L1132
- https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2644-honor-pv-reclaim-policy

**Comment by carlory** [comment]
Hi @niranjandarshann 

-  Which version of the external provisioner is the driver using? 
-  Does the driver meet the requirements of the CSI spec on the DeleteVolume PRC?
  ```
  a volume corresponding to the specified volume_id does not exist or the artifacts associated with the volume do not exist anymore, the Plugin MUST reply 0 OK.
  ```
  FYI: https://github.com/container-storage-interface/spec/blob/master/spec.md#deletevolume
- Is this problem occasional or permanently reproducible?
- Can you provide the provisioner logs at that time?

**Comment by xing-yang** [comment]
cc @deepakkinni

**Comment by reenakabra** [comment]
External provisioner used is : "csi-provisioner:v3.5.0"

This problem is always reproducible

Provisioner logs:

I1123 12:22:38.834284       1 controller.go:1151] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{csi-infoscale-pv    4ff8cd8d-420a-4e9e-be82-53874e9a4463 43348296 0 2023-11-23 12:21:18 +0000 UTC <nil> <nil> map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"csi-infoscale-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"},"csi":{"driver":"org.veritas.infoscale","fsType":"vxfs","volumeHandle":"clust_40559/vrts_kube_dg-40559/vol1"},"persistentVolumeReclaimPolicy":"Delete","storageClassName":"csi-infoscale-sc-prod"}}
 pv.kubernetes.io/bound-by-controller:yes] [] [kubernetes.io/pv-protection external-provisioner.volume.kubernetes.io/finalizer] [{kubectl-client-side-apply Update v1 2023-11-23 12:21:18 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:accessModes":{},"f:capacity":{".":{},"f:storage":{}},"f:csi":{".":{},"f:driver":{},"f:fsType":{},"f:volumeHandle":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} } {csi-provisioner Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:finalizers":{"v:\"external-provisioner.volume.kubernetes.io/finalizer\"":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{"f:pv.kubernetes.io/bound-by-controller":{}}},"f:spec":{"f:claimRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:22:38 +0000 UTC FieldsV1 {"f:status":{"f:phase":{}}} status}]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{2147483648 0} {<nil>} 2Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:org.veritas.infoscale,VolumeHandle:clust_40559/vrts_kube_dg-40559/vol1,ReadOnly:false,FSType:vxfs,VolumeAttributes:map[string]string{},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:&ObjectReference{Kind:PersistentVolumeClaim,Namespace:default,Name:csi-infoscale-pvc-static,UID:fd4ec891-59a5-4f02-83ac-1c5e7d489a88,APIVersion:v1,ResourceVersion:43348116,FieldPath:,},PersistentVolumeReclaimPolicy:Delete,StorageClassName:csi-infoscale-sc-prod,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:nil,},Status:PersistentVolumeStatus{Phase:Released,Message:,Reason:,},}
I1123 12:22:38.834430       1 controller.go:1502] delete "csi-infoscale-pv": started
I1123 12:22:38.834455       1 connection.go:193] GRPC call: /csi.v1.Controller/DeleteVolume
I1123 12:22:38.834460       1 connection.go:194] GRPC request: {"volume_id":"clust_40559/vrts_kube_dg-40559/vol1"}
I1123 12:22:39.346757       1 connection.go:200] GRPC response: {}
I1123 12:22:39.346772       1 connection.go:201] GRPC error: <nil>
I1123 12:22:39.346784       1 controller.go:1517] delete "csi-infoscale-pv": volume deleted
I1123 12:22:39.357177       1 controller.go:1554] delete "csi-infoscale-pv": failed to remove finalizer for persistentvolume: Operation cannot be fulfilled on persistentvolumes "csi-infoscale-pv": the object has been modified; please apply your changes to the latest version and try again
W1123 12:22:39.357202       1 controller.go:989] Retrying syncing volume "csi-infoscale-pv", failure 0
E1123 12:22:39.357217       1 controller.go:1007] error syncing volume "csi-infoscale-pv": Operation cannot be fulfilled on persistentvolumes "csi-infoscale-pv": the object has been modified; please apply your changes to the latest version and try again
I1123 12:22:39.357225       1 controller.go:1151] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{csi-infoscale-pv    4ff8cd8d-420a-4e9e-be82-53874e9a4463 43348301 0 2023-11-23 12:21:18 +0000 UTC 2023-11-23 12:22:38 +0000 UTC 0xc0007f63d0 map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"csi-infoscale-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"},"csi":{"driver":"org.veritas.infoscale","fsType":"vxfs","volumeHandle":"clust_40559/vrts_kube_dg-40559/vol1"},"persistentVolumeReclaimPolicy":"Delete","storageClassName":"csi-infoscale-sc-prod"}}
 pv.kubernetes.io/bound-by-controller:yes] [] [external-provisioner.volume.kubernetes.io/finalizer] [{kubectl-client-side-apply Update v1 2023-11-23 12:21:18 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:accessModes":{},"f:capacity":{".":{},"f:storage":{}},"f:csi":{".":{},"f:driver":{},"f:fsType":{},"f:volumeHandle":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} } {csi-provisioner Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:finalizers":{"v:\"external-provisioner.volume.kubernetes.io/finalizer\"":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{"f:pv.kubernetes.io/bound-by-controller":{}}},"f:spec":{"f:claimRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:22:38 +0000 UTC FieldsV1 {"f:status":{"f:message":{},"f:phase":{}}} status}]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{2147483648 0} {<nil>} 2Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:org.veritas.infoscale,VolumeHandle:clust_40559/vrts_kube_dg-40559/vol1,ReadOnly:false,FSType:vxfs,VolumeAttributes:map[string]string{},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:&ObjectReference{Kind:PersistentVolumeClaim,Namespace:default,Name:csi-infoscale-pvc-static,UID:fd4ec891-59a5-4f02-83ac-1c5e7d489a88,APIVersion:v1,ResourceVersion:43348116,FieldPath:,},PersistentVolumeReclaimPolicy:Delete,StorageClassName:csi-infoscale-sc-prod,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:nil,},Status:PersistentVolumeStatus{Phase:Failed,Message:error getting deleter volume plugin for volume "csi-infoscale-pv": no deletable volume plugin matched,Reason:,},}
I1123 12:22:40.358329       1 controller.go:1151] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{csi-infoscale-pv    4ff8cd8d-420a-4e9e-be82-53874e9a4463 43348301 0 2023-11-23 12:21:18 +0000 UTC 2023-11-23 12:22:38 +0000 UTC 0xc0007f63d0 map[] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"PersistentVolume","metadata":{"annotations":{},"name":"csi-infoscale-pv"},"spec":{"accessModes":["ReadWriteOnce"],"capacity":{"storage":"2Gi"},"csi":{"driver":"org.veritas.infoscale","fsType":"vxfs","volumeHandle":"clust_40559/vrts_kube_dg-40559/vol1"},"persistentVolumeReclaimPolicy":"Delete","storageClassName":"csi-infoscale-sc-prod"}}
 pv.kubernetes.io/bound-by-controller:yes] [] [external-provisioner.volume.kubernetes.io/finalizer] [{kubectl-client-side-apply Update v1 2023-11-23 12:21:18 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:accessModes":{},"f:capacity":{".":{},"f:storage":{}},"f:csi":{".":{},"f:driver":{},"f:fsType":{},"f:volumeHandle":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} } {csi-provisioner Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:finalizers":{"v:\"external-provisioner.volume.kubernetes.io/finalizer\"":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:21:22 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{"f:pv.kubernetes.io/bound-by-controller":{}}},"f:spec":{"f:claimRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}}}} } {kube-controller-manager Update v1 2023-11-23 12:22:38 +0000 UTC FieldsV1 {"f:status":{"f:message":{},"f:phase":{}}} status}]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{2147483648 0} {<nil>} 2Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:org.veritas.infoscale,VolumeHandle:clust_40559/vrts_kube_dg-40559/vol1,ReadOnly:false,FSType:vxfs,VolumeAttributes:map[string]string{},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:&ObjectReference{Kind:PersistentVolumeClaim,Namespace:default,Name:csi-infoscale-pvc-static,UID:fd4ec891-59a5-4f02-83ac-1c5e7d489a88,APIVersion:v1,ResourceVersion:43348116,FieldPath:,},PersistentVolumeReclaimPolicy:Delete,StorageClassName:csi-infoscale-sc-prod,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:nil,},Status:PersistentVolumeStatus{Phase:Failed,Message:error getting deleter volume plugin for volume "csi-infoscale-pv": no deletable volume plugin matched,Reason:,},}

**Comment by carlory** [comment]
Thank you @reenakabra  

I will try to fix it. 
/remove-triage needs-information
/assign
