### ISSUE TITLE
POD drop resolv.conf conf when restart Pause container 

### ISSUE THREAD

**Issue by gaopeiliang** [kubernetes/kubernetes#121712]
### What happened?

Pod  with clusterFirst DNS mode,  resolv.conf will config with coredns VIP;   But when restart Pause Container with cri runtime,  pause container will drop resolv.conf coredns config, and become HostNetwork mode config.... 

### What did you expect to happen?

restart pause container will keep same resolv.conf dns server

### How can we reproduce it (as minimally and precisely as possible)?

1.   create Pod  with clusterFirst dns mode

2.   docker restart this Pod Pause container

you will find Pod resolv.conf become hostNetwork  always ...

### Anything else we need to know?

kubelet pleg cycle not see this pause container  from running -> existed -> running life,  so nothing to do recreate ... 

restart status  change  so quickly , mis pleg check ,,,,,

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.7-6+25bc7282306ce2", GitCommit:"25bc7282306ce2bb968b04c17a4e6342d2dc4a21", GitTreeState:"clean", BuildDate:"2021-06-28T10:26:47Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by kannon92** [comment]
1.20 k8 version is out of support.  Can you try a later version of k8s and see if this problem still persists?

Please add container runtime version also.

**Comment by SergeyKanzhelev** [comment]
/triage needs-information

(see comment above for information needed)
