### ISSUE TITLE
flaky test k8s.io/kubernetes/pkg/proxy: ipvs (different tests)

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#121750]
### Which jobs are flaking?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Which tests are flaking?

TestNodePortIPv4, TestEndpointSliceE2E, est_EndpointSliceOnlyReadyAndTerminatingCluster, + others?

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121744/pull-kubernetes-unit/1721463684926017536

```
FAIL: pkg/proxy/ipvs TestNodePortIPv4/node_port_service_with_protocol_sctp_and_externalTrafficPolicy_local (0.06s)
    proxier_test.go:970: actual ipvs state: &{Scheduler: Services:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:10.20.30.41:80/SCTP {IP:100.101.102.103 Port:3001 Protocol:SCTP}:100.101.102.103:3001/SCTP] Destinations:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:[10.180.1.1:80 10.180.0.1:80] {IP:100.101.102.103 Port:3001 Protocol:SCTP}:[10.180.0.1:80]]}
    proxier_test.go:971: expected ipvs state: &{Scheduler: Services:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:10.20.30.41:80/SCTP {IP:100.101.102.103 Port:3001 Protocol:SCTP}:100.101.102.103:3001/SCTP] Destinations:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:[10.180.0.1:80 10.180.1.1:80] {IP:100.101.102.103 Port:3001 Protocol:SCTP}:[10.180.0.1:80]]}
    proxier_test.go:972: unexpected IPVS state
=== FAIL: pkg/proxy/ipvs TestNodePortIPv4 (0.16s)
```

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121744/pull-kubernetes-unit/1721427865792155648

```

=== FAIL: pkg/proxy/ipvs TestEndpointSliceE2E (0.02s)
...

=== FAIL: pkg/proxy/ipvs Test_EndpointSliceOnlyReadyAndTerminatingCluster (0.08s)
...
```

### Relevant SIG(s)

/sig network

**Comment by aojea** [comment]
ok, it seems that it has a problem with the assertion as it expects certain order

```
 &{Scheduler: Services:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:10.20.30.41:80/SCTP {IP:100.101.102.103 Port:3001 Protocol:SCTP}:100.101.102.103:3001/SCTP] Destinations:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:[10.180.1.1:80 10.180.0.1:80] {IP:100.101.102.103 Port:3001 Protocol:SCTP}:[10.180.0.1:80]]}
 &{Scheduler: Services:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:10.20.30.41:80/SCTP {IP:100.101.102.103 Port:3001 Protocol:SCTP}:100.101.102.103:3001/SCTP] Destinations:map[{IP:10.20.30.41 Port:80 Protocol:SCTP}:[10.180.0.1:80 10.180.1.1:80] {IP:100.101.102.103 Port:3001 Protocol:SCTP}:[10.180.0.1:80]]}

```

`[10.180.1.1:80 10.180.0.1:80]` vs `[10.180.0.1:80 10.180.1.1:80] `

if the unordered output is expected then we can't do reflectDeepqual and  need to sort and compare the arrays

https://github.com/kubernetes/kubernetes/blob/246d363ea4bab2ac99a938d0cee73d72fc44de45/pkg/proxy/ipvs/proxier_test.go#L968-L970

/cc @uablrek

**Comment by uablrek** [comment]
I encountered this in https://github.com/kubernetes/kubernetes/pull/121744, and I thought this was my mess-up, but that PR hasn't been merged!

But perhaps the fix in that PR solves the problem: https://github.com/kubernetes/kubernetes/pull/121744/commits/d78a794be22abfa16ac6c53ec72f9f1fe47442d6.

**Comment by uablrek** [comment]
Tested:
```
cd pkg/proxy/ipvs
go test -count 1000
```
But on my PC it passes both on "master" and with https://github.com/kubernetes/kubernetes/commit/d78a794be22abfa16ac6c53ec72f9f1fe47442d6.

> Program testing can be used to show the presence of bugs, but never to show their absence!

[Edsger Dijkstra](https://www.cs.scranton.edu/~mccloske/dijkstra_quotes.html)

**Comment by aroradaman** [comment]
There are only two failures for pkg `k8s.io/kubernetes/pkg/proxy/ipvs` and both of them occurred during implementation/pre-submit  of https://github.com/kubernetes/kubernetes/pull/121744. 

We can ignore them, these are not flakes ... they failed during pre-submits (due to ordering only which Lars fixed in his PR later)

**Comment by aroradaman** [comment]
/close
(as not flake)

**Comment by uablrek** [comment]
In the process I added `t.Parallel()` in the unit tests:
```
pkg/proxy/ipvs
sed -i '/func Test/a t.Parallel()' proxier_test.go
gofmt -s -w proxier_test.go
go test -count 1000
```
and got the time down from ~60s to ~12s. IMO it would be a good idea to add this, but there may be some reason not to, so I made a query on slack: https://kubernetes.slack.com/archives/C09QZ4DQB/p1699337965516959
