### ISSUE TITLE
Release OCI container images instead of docker

### ISSUE THREAD

**Issue by rchincha** [kubernetes/kubernetes#121742]
### What would you like to be added?

Currently kubernetes container images are built and released as docker images. 

```
$ crane manifest k8s.gcr.io/kube-apiserver:v1.15.2 | jq .mediaType

"application/vnd.docker.distribution.manifest.list.v2+json"
```

Do you plan to build these as OCI images instead?

For example, `distroless` images are being built and pushed as OCI images

```
$ crane manifest gcr.io/distroless/python3-debian12 | jq .mediaType

"application/vnd.oci.image.index.v1+json"
```

### Why is this needed?

OCI specs (runtime, image and distribution) are intended to be vendor neutral.

**Comment by neolit123** [comment]
if this change is planned, someone needs to estimate if it will break tests in the k8s testing space (which is huge..).

i know at least one test that relies on the docker spec for images:
https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go

> "application/vnd.oci.image.index.v1+json"

Q: is the docker to OCI spec compatible in terms of JSON structs or not?

the test mentioned above relies on parsing a docker image as per the docker image structures:
https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go#L70-L73
https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go#L115-L148

**Comment by neolit123** [comment]
it feels like such a change would need a KEP.
https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps

**Comment by sftim** [comment]
We could do this in multiple stages. First stage, publish OCI images but with a special tag. I don't think that part needs a KEP.

**Second** stage, switch things so that `registry.k8s.io/kube-apiserver:v1.28.3` (or whatever) is OCI format.

**Comment by rchincha** [comment]
Not very familiar with the build/release system used here. That said, if it helps 

https://github.com/ko-build/ko

"ko uses environment variable KO_DOCKER_REPO to set the repository where the OCI images will be published."

**Comment by rchincha** [comment]
> if this change is planned, someone needs to estimate if it will break tests or tools in the wider k8s space (which is huge..).
> 
> i know at least one test that relies on the docker spec for images: https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go it actually tests the validity of the registry.k8s.io common images.
> 
> > "application/vnd.oci.image.index.v1+json"
> 
> Q: is the docker to OCI spec compatible in terms of JSON structs or not?
> 
> the test mentioned above relies on parsing a docker image as per the docker image structures: https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go#L70-L73 https://github.com/kubernetes/kubeadm/blob/main/tests/e2e/manifests/verify_manifest_lists.go#L115-L148

Would point to the OCI image spec's `go` artifacts.

https://github.com/opencontainers/image-spec/blob/main/specs-go/v1/mediatype.go
https://github.com/opencontainers/image-spec/tree/main/specs-go

**Comment by saschagrunert** [comment]
Hm, we use docker buildx to build our container images. They have an [OCI image format exporter](https://docs.docker.com/build/exporters/), but we need to tag and save them during the process:

https://github.com/kubernetes/kubernetes/blob/46f4248d56dae757a949bbe4a406bcebc41b9ad2/build/lib/release.sh#L339-L363

I'm not sure if docker can even push the OCI image formats to a registry.

**Comment by sudo-bmitch** [comment]
Buildx lets you change the media type, which is separate from the output type: https://docs.docker.com/build/exporters/#oci-media-types

The OCI output is an OCI Image Layout, a filesystem format for storing images locally. Tools like crane, oras, regclient, and skopeo support copying from that to a registry, which I'm a fan of, but shouldn't be needed for this.
