### ISSUE TITLE
ctr i import throws Segmentation fault

### ISSUE THREAD

**Issue by AndyInAi** [kubernetes/kubernetes#121769]
### What happened?

root@k8s6:~#
root@k8s6:~# **ctr i import /mnt/gluster-gv0/k8s/image/ubuntu-chrome-beta.tar**
**Segmentation fault**
root@k8s6:~#

### What did you expect to happen?

unpacking docker.io/library/ubuntu:chrome-beta (sha256:...)...done

### How can we reproduce it (as minimally and precisely as possible)?

ctr i import foo.tar

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ uname -a
Linux k8s6 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
not a k8s bug. must be reported to
https://github.com/containerd/containerd

/kind support
/close
