### ISSUE TITLE
[sig-autoscaling] [HPA] [Feature:CustomMetricsAutoscaling] with multiple metrics of different types should not scale down when one metric is missing

### ISSUE THREAD

**Issue by pacoxu** [kubernetes/kubernetes#121738]
### Failure cluster [342eb6fbb29170f44f82](https://go.k8s.io/triage#342eb6fbb29170f44f82)
https://storage.googleapis.com/k8s-triage/index.html?test=CustomMetricsAutoscaling

**First Failure  in  Nov 02 16:01:48Nov 02 2023, 16:01:48 UTC+0800**

- first failure: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1719988161754435584/artifacts/metadata.json -> commit 227d1b2357d93a  Added in #119762
- last success: https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1719967273617199104/artifacts/metadata.json -> commit 6b8b1881491e26 

- the k/k commit is https://github.com/kubernetes/kubernetes/pull/119762 (not sure if it is related)

/cc @smarterclayton @liggitt  @aojea @AxeZhan 

##### Error text:
```
[FAILED] Failed to get replication controller &Deployment{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:DeploymentSpec{Replicas:nil,Selector:nil,Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {[] [] [] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil <nil> [] []}},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,ProgressDeadlineSeconds:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[]DeploymentCondition{},ReadyReplicas:0,CollisionCount:nil,},}: client rate limiter Wait returned an error: context deadline exceeded
In [It] at: test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:617 @ 11/03/23 20:49:46.812

```
#### Recent failures:
[2023/11/6 04:32:26 ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1721264227454291968)
[2023/11/6 04:32:26 ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa/1721264227517206528)
[2023/11/6 03:08:26 ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa/1721243087700758528)
[2023/11/6 03:03:26 ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm/1721241829648633856)
[2023/11/6 01:43:26 ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa](https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa/1721221696221876224)

/kind failing-test

/sig autoscaling

**Comment by mengjiao-liu** [comment]
/triage accepted
The tests are still failing multiple times.

**Comment by AxeZhan** [comment]
Hmmm, looking into the log. There is  a intended timeout `// Expected number of replicas found. Continue polling until timeout.`
And when timeout occurred during getting deployments, we'll use `framework.Failf` to fail the test.
And since this will throw a panic, the e2e test will fail correspondingly.

This can be easily reproduced by the following code:
```
func TestXxx(t *testing.T) {
	ctx := context.Background()
	err := PollUntilContextTimeout(ctx, time.Second, time.Second*10, true, func(ctx context.Context) (bool, error) {
		Failf("hit")
		return false, nil
	})
	fmt.Println(err)
}
```
Which will result in a panic but not err.
This explains why it's failing now, but I **have no idea** how it succeed before🤦.

**Comment by pacoxu** [comment]
https://github.com/kubernetes/kubernetes/blob/6eeb48cd7f9b21ac16ac5f9dc707e9a3d61f4376/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go#L598-L603

https://github.com/kubernetes/kubernetes/blob/6eeb48cd7f9b21ac16ac5f9dc707e9a3d61f4376/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go#L614-L619

IMO, `framework.Failf` is not valid inside `wait.PollUntilContextTimeout`.

We should return the err instead of calling `framework.Failf` there. 

/cc @pohly

**Comment by AxeZhan** [comment]
The strange thing is that we check if context is canceled just before execute the function in `poll`, there will only be a few nanoseconds of delay, so it shouldn't timeout during executing the function everytime.

> We should return the err instead of calling framework.Failf there.

I'm definitely +1 for this.

**Comment by pacoxu** [comment]
> ##### Error text:
> ```
> [FAILED] Failed to get replication controller &Deployment{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []},Spec:DeploymentSpec{Replicas:nil,Selector:nil,Template:{{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] [] []} {[] [] [] []  <nil> <nil>  map[]   <nil>  false false false <nil> nil []   nil  [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil <nil> [] []}},Strategy:DeploymentStrategy{Type:,RollingUpdate:nil,},MinReadySeconds:0,RevisionHistoryLimit:nil,Paused:false,ProgressDeadlineSeconds:nil,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[]DeploymentCondition{},ReadyReplicas:0,CollisionCount:nil,},}: client rate limiter Wait returned an error: context deadline exceeded
> In [It] at: test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:617 @ 11/03/23 20:49:46.812
> ```

This flake is not there for two weeks.

> { failed [FAILED] Failed to create metric descriptor: googleapi: Error 500: Internal error encountered. Please retry after a few seconds. If internal errors persist, contact support at https://cloud.google.com/support/docs., backendError
> In [It] at: k8s.io/kubernetes/test/e2e/autoscaling/custom_metrics_stackdriver_autoscaling.go:426 @ 05/02/24 02:58:36.318
> }

And the test flakes for another reason as well.

**Comment by pacoxu** [comment]
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-migs-hpa
https://prow.k8s.io/job-history/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-autoscaling-hpa-cm
are green

https://storage.googleapis.com/k8s-triage/index.html?test=CustomMetricsAutoscaling

has no errors.

/close
