### ISSUE TITLE
falky test pkg/registry/core/persistentvolume/storage TestUpdateStatus

### ISSUE THREAD

**Issue by neolit123** [kubernetes/kubernetes#121752]
### Which jobs are flaking?

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Which tests are flaking?

pkg/registry/core/persistentvolume/storage TestUpdateStatus

### Since when has it been flaking?

unknown

### Testgrid link

https://testgrid.k8s.io/presubmits-kubernetes-blocking#pull-kubernetes-unit

### Reason for failure (if possible)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/121743/pull-kubernetes-unit/1721422670844661760

```
=== FAIL: pkg/registry/core/persistentvolume/storage TestUpdateStatus (0.23s)
    storage_test.go:215: unexpected object:   core.PersistentVolumeStatus{
          	Phase:                   "Bound",
          	Message:                 "",
          	Reason:                  "",
        - 	LastPhaseTransitionTime: s"2023-11-06 07:22:50 +0000 UTC",
        + 	LastPhaseTransitionTime: s"2023-11-06 07:22:51 +0000 UTC",
          }
```

### Relevant SIG(s)

/sig storage

**Comment by pacoxu** [comment]
/priority important-soon
as it failed in master blocking https://testgrid.k8s.io/sig-release-master-blocking#ci-kubernetes-unit
