### ISSUE TITLE
unable to sync kubernetes service:

### ISSUE THREAD

**Issue by YuYue999** [kubernetes/kubernetes#121772]
### What happened?

when Binary installation k8s, start kube-apiserver, Report the following error:

unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "169.254.135.8": may not be in the link-local range (169.254.0.0/16, fe80::/10)

### What did you expect to happen?

I want to know how to solve this bug，pelsease,Thank you!

### How can we reproduce it (as minimally and precisely as possible)?

when you Binary installation k8s for version 1.22.1 ,may be reproduce  this BUG

### Kubernetes version

k8s version : 1.22.1

### Cloud provider

..

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by neolit123** [comment]
> k8s version : 1.22.1

it's out of support. your version must be >= 1.26:
https://kubernetes.io/releases/

we also don't provide support on github.
please try the support channels
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
