### ISSUE TITLE
HTTP2_PING_TIMEOUT_SECONDS+HTTP2_READ_IDLE_TIMEOUT_SECONDS > 40s will cause all node NotReady

### ISSUE THREAD

**Issue by chenk008** [kubernetes/kubernetes#121793]
### What happened?

The controller-manager node-lifecycle-controller watches node lease and update `nodeHealthMap` probeTimestamp , and it check node probeTimestamp is before `now - node-monitor-grace-period`. The node-monitor-grace-period default value is 40s.

When the client connection lost, the lease watcher cannot receive new event. With the http2 health check,   HTTP2_PING_TIMEOUT_SECONDS default is 30s, HTTP2_READ_IDLE_TIMEOUT_SECONDS default is  15s, it will delay 45s to kill http2  connection.  

During this period, node-lifecycle-controller will mark all nodes NotReady.

Here are some logs

```
I1103 23:00:28.464015       1 node_lifecycle_controller.go:1097] node 10.0.10.240 hasn't been updated for 40.010894415s. Last Ready is: &NodeCondition{Type:Ready,Status:True,LastHeartbeatTime:2023-11-03 22:57:18 +0800 CST,LastTransitionTime:2023-04-21 14:39:17 +0800 CST,Reason:KubeletReady,Message:kubelet is posting ready status,}

W1103 23:00:41.408493       1 reflector.go:441] k8s.io/client-go/informers/factory.go:134: watch of *v1.Lease ended with: an error on the server ("unable to decode an event from the watch stream: http2: client connection lost") has prevented the request from succeeding
```

### What did you expect to happen?

When the http2 connection lost, the watch should stop as soon as possible. The reflector should relist resource, and node-lifecycle-controller should not mark all node NotReady.

HTTP2_PING_TIMEOUT_SECONDS+HTTP2_READ_IDLE_TIMEOUT_SECONDS should be less than 40s.

### How can we reproduce it (as minimally and precisely as possible)?

1. Find the controller-manager node-lifecycle-controller watch client srcIP:srcPort. Drop all tcp package send into srcIP:srcPort.
2. Wait for more than 40 seconds, all node will be marked NotReady
3. All node will be Ready after some seconds.

### Kubernetes version

<details>

```console
$ kubectl version
# Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.3", GitCommit:"", GitTreeState:"clean", BuildDate:"2023-10-19T07:10:40Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Cloud provider

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by chenk008** [comment]
How about double-check node lease before marking node NotReady? The node-lifecycle-controller can get reference lease from apiserver with `resourceversion=''`

**Comment by aojea** [comment]
/cc @aojea @liggitt 

We have discussed this timeouts values before @andrewsykim @linxiulei and myself, I also think @linxiulei got some metrics with lower timeouts for the HTTP2 connections.

In this situation is clear that the defaults of the node watcher and the timeouts are related and having good defaults will be ideal, but the question is which values do we change ?

**Comment by chenk008** [comment]
@aojea I think in internal network, the ping response almost return in 1 seconds, the HTTP2_PING_TIMEOUT_SECONDS default value should be 5 seconds. And the total timeout will 35 seconds. WDYT?

**Comment by SergeyKanzhelev** [comment]
/triage accepted


> We have discussed this timeouts values before @andrewsykim @linxiulei and myself, I also think @linxiulei got some metrics with lower timeouts for the HTTP2 connections.
> 
> In this situation is clear that the defaults of the node watcher and the timeouts are related and having good defaults will be ideal, but the question is which values do we change ?

@aojea any pointers in other places where those timeouts were changed for http2? Any notes from those discussions?

**Comment by SergeyKanzhelev** [comment]
/priority important-longterm

since it is not a regression I will keep it longterm priority and not higher. But we can reevaluate if we hear more reports about it.

**Comment by jmcmeek** [comment]
I'm investigating problems similar to this, but I'm looking for a way to confirm this is what is happening - and if there are tips for how to recreate such a scenario, that would be very helpful.

We get infrequent reports of "worker goes NotReady for a short time" incidents that appear to be triggered by events like failing over a LB sitting front of the kube-apiservers.

We've done some tests with a simple client-go app and have recreated a scenario in which the app logs `http2: client connection lost` messages after 45 secs of "context exceeded" errors.

The failures reported to us from customers don't have http2 errors in the kubelet logs, and our attempts to recreate with kubelet have never shown more more than a single error which works on subsequent retry.

**Comment by rtheis** [comment]
Hi folks, we have a simulated recreate of the problem. This recreate involves injecting a 40 second delay in "connectivity" between the Kubernetes API server and etcd (we added a 40 second delay to etcd defrag and defragged all etcd members at the same time). The connectivity between these two components is obviously critical to nodes successfully updating their leases in order to stay ready. We use 40 seconds because it matches [Kubernetes etcd keepalive configuration](https://github.com/kubernetes/kubernetes/blob/01eb9f47541156a38e4b28759977c06f07f08012/staging/src/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go#L60-L64). Given this, one or more of the cluster nodes will flap their readiness state. Setting `--node-monitor-grace-period=50s` on the Kubernetes controller manager prevents the flap. Given this, I think that one or more of the Kubernetes default configurations needs to change in order to tolerate such "connectivity" problems in order to maintain healthy node state.

**Comment by aojea** [comment]
What's the proposal then? Do we update --node-monitor-grace-period to 50s?

It seems the less risky change as the client-go defaults are more sensitive and impact the whole ecosystem, beyond kubernetes itself 

@dchen1107 are you open to increase this default? It seems worth it to improve the reliability of cluster

**Comment by rtheis** [comment]
@aojea I think we should update `node-monitor-grace-period`.

**Comment by aojea** [comment]
> @aojea I think we should update `node-monitor-grace-period`.

can someone send a PR to see how it will look like?

**Comment by devppratik** [comment]
I have been following this discussion as we had encountered the bug as well.
@aojea @rtheis  I have created a PR - https://github.com/kubernetes/kubernetes/pull/126287
Please let me know if it works

**Comment by rtheis** [comment]
I'll add another data point from our testing. Namely, the simulated recreate noted [here](https://github.com/kubernetes/kubernetes/issues/121793#issuecomment-2239228879) depends on the Kubernetes controller manager (KCM) leader election configuration. Using the following leader election configuration for the KCM yields a KCM that has no leader after the delayed etcd defrag. As a result, nodes won't be marked not ready unless the KCM leadership is restored before the nodes renew their lease.

```
        - --leader-elect-resource-lock=leases
        - --leader-elect=true
        - --leader-elect-renew-deadline=12s
        - --leader-elect-retry-period=3s
```

Extending the KCM leader election configuration to the following, makes the problem easier to recreate.

```
        - --leader-elect-resource-lock=leases
        - --leader-elect=true
        - --leader-elect-lease-duration=137s
        - --leader-elect-renew-deadline=107s
        - --leader-elect-retry-period=26s
```

**Comment by linxiulei** [comment]
Has anyone confirm this issue has been fixed?

I am not convinced that changing it to 50s completely resolved this issue

For example:

00:00 the last successful node HB is served
00:09 the connection becomes stale
00:10 kubelet sends HB
00:20 previous HB is failed with 10s timeout and retry
00:30 failed again and retry
00:40 failed again and retry
00:50 node becomes Unknown
00:54 connection is dropped due to ping timeout (09 + 30 + 15)

**Comment by aojea** [comment]
this can have an e2e test that shows the problem, it seems it could be also possible to reproduce with an integration test, but we can not keep bumping default values each release https://github.com/kubernetes/kubernetes/issues/127352
