### ISSUE TITLE
Helm upgrade fails to update the deployment in another EKS cluster

### ISSUE THREAD

**Issue by irfanjs** [kubernetes/kubernetes#121848]
**What is the issue**

We have custom JAVA based application which basically updates the ingress entries in another EKS cluster using API layer . Let me explain

1: JAVA application is deployed in POD in one EKS cluster, named , A. This app has logic of setting the context of another EKS cluster, named , B and run few commands to append the ingress entries in deployment using helm package manager.

2: If we run the java app without container / POD , it works fine

3: If we run the java app within POD (using deployment/service) , deployed in cluster A, throws following error. This JAVA app basically executes the helm.sh explained below

`Error: Kubernetes cluster unreachable: the server has asked for the client to provide credentials `

The Dockerfile as below :

```
FROM openjdk:17-slim

WORKDIR /app
EXPOSE 8080

RUN apt-get -y update; apt-get -y install curl; apt-get -y install unzip; apt-get -y install jq
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip && ./aws/install

ENV AWS_ACCESS_KEY_ID=<key>
ENV AWS_SECRET_ACCESS_KEY=<acc-key>
ENV AWS_DEFAULT_REGION=us-east-1

ADD helm.sh /app 
RUN chmod 755 /app/helm.sh
ADD target/app1.jar /app/app1.jar
CMD ["java", "-jar", "/app/app1.jar" ]
```
The content of shell script (helm.sh) is as follows :

`helm upgrade --install <chartname> <chart-dir> --namespace plat --kubeconfig ~/.kube/config -f <chart-dir>/values.yaml`
**what we have tried**

1: open all the traffic on the nodes of EKS cluster (incoming/outgoing)

2: configured the service as "NodePort" instead of ClusterIP. It is the same service where we need to append the ingress entries.

3: pass the kubeconfig at command line of that cluster where we need to append the ingress entries

Still no luck

As the error suggests , it is the issue of POD communication across clusters but not getting where we are missing .

Please help / suggest

**Comment by neolit123** [comment]
please see:
https://github.com/kubernetes/kubernetes/blob/master/SUPPORT.md

you can also try contacting Helm or EKS for support.

/kind support
/close
