### ISSUE TITLE
how to use a heapster?

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/kubernetes#12186]
i have tried to create a heapster rc on kubernetes.but it failed.
i checked the log and it showed:
 open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

there are only a 'default' serviceaccount running in my kubernetes master. and it has no secret. 
what should i do in kubernetes?create a secret in the default serviceaccount? if so, how to do?

**Comment by dalanlan** [comment]
Each namespace has a SA named `default` with at least one token(secret).
You may try 
```
$ kubectl get secrets --all-namespaces
```

**Comment by fzu-huang** [comment]
nop.i have tried it many times.

[root@vm-56-65 bin]#  kubectl  get serviceaccounts  --all-namespaces
NAMESPACE   NAME       SECRETS
default     default    0
default     heapster   0

my kubernetes version is 1.0.0 and i added a flag --admission_control=ServiceAccount,LimitRanger  when i start apiserver.

**Comment by dalanlan** [comment]
Hmm, that's odd. The `--admission-control` seems all right though.
You may try [this](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/user-guide/secrets).
Yet i was wondering if it's a problem related to heapster only, or with all pods ( that they cannot consume a proper secret). Did you check the log of kubelet?

**Comment by fzu-huang** [comment]
at  first  i start apiserver   without --admission-control   and  all is ok (but still no secret in default servcieaccount) .  then  i  want to start a heapster replication-controller. it failed with log(in container):
 1 heapster.go:59] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

it must because heapster  need to get token from kubernetes Master.right??

so i restart kubernetes apiserver with flag --admission-control=serviceAccount . but this time i cant' even create a  normal pod : 

Error from server: error when creating "imgpod.json": Pod "imgpod" is forbidden: no API token found for service account default/default, retry after the token is automatically created and added to the service account


but  i  have not  idea  how  to solve it...
have you successfully start a heapster by kubernetes? or start kuber-apiserver  with    --admission-control=serviceAccount  and create pod?

**Comment by dalanlan** [comment]
As i put out before, i believe it's a common case for all pods instead of heapster only.
Each pod should consume a secret which goes to /var/run/secrets/kubernetes.io/serviceaccount/token as a volume, that lack of token is exactly why you cannot create a pod properly.
`--admission-control=serviceAccount` is well enough and should not be the trouble maker.
Did you at least check the log of kubelet, if i may ask again?

**Comment by fzu-huang** [comment]
i am sorry but there are  no  log of kubelet when i create a heapster. the pod can be created .
the problem,  heapster start and it panic with :
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

then the pod  automaticaly restart it, so it run into a loop

**Comment by dalanlan** [comment]
It's not a panic but a fatal error, i'm afraid.  
If a pod is not even running, how could you call it as "the pod can be created"?
Without any other details, i'm afraid i cannot help.

**Comment by iremA** [comment]
Same here. 
Either I start apiserver without  --admission-control line, then I can create  the pods as expected but see the error in the heapster pod log:
open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

kubectl get pods
NAME                                 READY     STATUS    RESTARTS   AGE
monitoring-heapster-v5-3qers         0/1       Pending   0          2s
monitoring-influx-grafana-v1-20lt2   0/2       Pending   0          2s
redis-master-ohklu                   1/1       Running   1          2h


OR I uncomment KUBE_ADMISSION_CONTROL="--admission_control=LimitRanger,ServiceAccount"
then I see errors in apiserver logs:
 
20138 reflector.go:136] Failed to list *api.Secret: Get http://0.0.0.0:8080/api/v1/secrets?fieldSelector=type%3Dkubernetes.io%2Fservice-account-token: di
 20138 reflector.go:136] Failed to list *api.ServiceAccount: Get http://0.0.0.0:8080/api/v1/serviceaccounts: dial tcp 0.0.0.0:8080: connection refused
20138 reflector.go:136] Failed to list *api.LimitRange: Get http://0.0.0.0:8080/api/v1/limitranges: dial tcp 0.0.0.0:8080: connection refused

and cannot create any pod.

I guess, I should create some cert for pods to access apiserver but I don't know how exactly.

**Comment by dalanlan** [comment]
Without a proper `--admission-control`, SA/secrets would be automatically created.
A default one as `--admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota`.
Also you need a key to verify your SA. Use `--service-account-key-file` or `--tls-private-key-file`, which is optional.

**Comment by fzu-huang** [comment]
@iremA 
use these commands to make crt and key:
openssl genrsa -out ca.key 2048

openssl req -x509 -new -nodes -key ca.key -subj "/CN=abc.com" -days 5000 -out ca.crt

openssl genrsa -out server.key 2048

openssl req -new -key server.key -subj "/CN=vm-56-65" -out server.csr
**there "/CN=vm-56-65" shuold be  "/CN=[yourhostname]"
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 5000

put these keys into /var/run/kubernetes/

and start api-server as:
./kube-apiserver --logtostderr=true --log-dir=/var/log/ --v=0 --admission_control=ServiceAccount --etcd_servers=http://127.0.0.1:4001 --insecure_bind_address=0.0.0.0 --insecure_port=8080 --kubelet_port=10250 --service-cluster-ip-range=10.0.0.1/24 --allow_privileged=false   --service-node-port-range='30000-35535'       --client_ca_file=/var/run/kubernetes/ca.crt  --tls-private-key-file=/var/run/kubernetes/server.key --tls-cert-file=/var/run/kubernetes/server.crt 

start controller-manager with these two flags:
--root-ca-file="/var/run/kubernetes/ca.crt"
--service-account-private-key-file="/var/run/kubernetes/server.key"

now  try to create a pod

**Comment by lvlv** [comment]
Great guide! How about put this into docs/admin/service-accounts-admin.md
or docs/admin/heapster.md? It could save me hours if I saw this earlier
this week!

**Comment by fzu-huang** [comment]
@lvlv  I‘m afraid it is not a good idea ~  :)   my way is a clumsy way .  I believe there must be a easier way to run a heapster instance.   When api-server is starting, it will create apiserver.crt and apiserver.key by it self, I have tried to use them  when i create heapster  but i failed,heapster log showed that the crt is invalid. You can try it , maybe you  will find something interesting~

**Comment by vishh** [comment]
cc @mikedanese

**Comment by mikedanese** [comment]
Would it be easy for you to upgrade to `1.0.3`? It contained some critical bug fixes around service account timing?

**Comment by dalanlan** [comment]
>When api-server is starting, it will create apiserver.crt and apiserver.key by it self

I doubted it, i'm afraid. What makes you catch this, if i may ask?

**Comment by fzu-huang** [comment]
@dalanlan 
 I started api-server with --admission_control=ServiceAccount  and didn't set flag --tls-private-key-file  and  --tls-cert-file , after apiserver is created, i saw these two files:apiserver.crt and apiserver.key


in kubernetes\cmd\kube-apiserver\app\server.go, i saw this:

if s.TLSCertFile == "" && s.TLSPrivateKeyFile == "" {
                    s.TLSCertFile = path.Join(s.CertDirectory, "apiserver.crt")
                    s.TLSPrivateKeyFile = path.Join(s.CertDirectory, "apiserver.key")
                    // TODO (cjcullen): Is PublicAddress the right address to sign a cert with?
                    alternateIPs := []net.IP{config.ServiceReadWriteIP}
                    alternateDNS := []string{"kubernetes.default.svc", "kubernetes.default", "kubernetes"}
                    // It would be nice to set a fqdn subject alt name, but only the kubelets know, the apiserver is clueless
                    // alternateDNS = append(alternateDNS, "kubernetes.default.svc.CLUSTER.DNS.NAME")
                    if err := util.GenerateSelfSignedCert(config.PublicAddress.String(), s.TLSCertFile, s.TLSPrivateKeyFile, alternateIPs, alternateDNS); err != nil {
                        glog.Errorf("Unable to generate self signed cert: %v", err)
                    } else {
                        glog.Infof("Using self-signed cert (%s, %s)", s.TLSCertFile, s.TLSPrivateKeyFile)
                    }
                }

which means that if we start api-server without flags: --tls-private-key-file  and  --tls-cert-file   it will  generate self-signed certification:
    util.GenerateSelfSignedCert(config.PublicAddress.String(), s.TLSCertFile, s.TLSPrivateKeyFile, alternateIPs, alternateDNS)

We can also add those two flags to specific server.key and server.crt.

**Comment by fzu-huang** [comment]
@mikedanese 

I will try it next week...

**Comment by dalanlan** [comment]
Thx. And I'm totally a moron when it comes to security stuff. 
Do you have any idea how a client identifies itself in this case? I assume there is no client cert or key here (Correct me if i'm wrong)

**Comment by mikedanese** [comment]
@dalanlan Is correct. If you want to use in cluster config, you need to a bit more with the CA cert generation. You can also use heapster over http:// if you are on a trusted network. I've opened kubernetes/heapster#479 to improve the documentation. For now please see:

https://github.com/mikedanese/heapster/blob/service-account-doc/docs/source-configuration.md#kubernetes

**Comment by mikedanese** [comment]
The CA cert generated by the apiserver is not sufficient to use with the default serviceaccount to auth with the apiserver as it does not contain a SAN for the ClusterIP of the kubernetes service.

**Comment by fzu-huang** [comment]
@dalanlan 
I saw some docs said that  in this case , client must use the same crt and key as server.


@mikedanese  
YES~~~，  I saw the code add IP and DNS when it use func: `util.GenerateSelfSignedCert()`
so I think it must be usable when we run a heapster.

I tried to push server.crt and server.key into heapster(By volumn a secret). I tried it but failed, there must be something wrong, but I can't find it out. So I have to use specific crt and key .
It will be great if there is a doc tell us how to use security mode. It took me so much time ...(≧口≦)

**Comment by mikedanese** [comment]
Yes it is quite complicated (and we are working on making it easier and having better documentation). The reason the `util.GenerateSelfSignedCert` doesn't work, even when you distribute it with the controller-manager is that it only signs the cert for the hostname of the apiserver but heapster communicates with the apiserver using the kubernetes service clusterIP by default. The default cert generated by apiserver is invalid for that IP address. cc @erictune, is there good doc on how to setup secure kubernetes? Perhaps it should be included in the "from scratch" getting started guide? I couldn't find any.

**Comment by fzu-huang** [comment]
@mikedanese   thank you very  much ~ ^_^
