### ISSUE TITLE
Deployment with replicas and resources not deploying specific resources in Azure

### ISSUE THREAD

**Issue by souvik-dw** [kubernetes/kubernetes#121844]
I tried to add Deployment with replicas in Azure. I added resources but it's always taking 4 CPU and 15Gi Memory.
Below is the deployed yml.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test-cf-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-cf
  template:
    metadata:
      labels:
        app: test-cf
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - image: adobecoldfusion/coldfusion2021:latest
        name: test-cf
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2
            memory: 8Gi
          requests:
            cpu: 2
            memory: 8Gi

**Comment by souvik-dw** [comment]
@k8s-ci-robot How to add those? Unable to find options to add labels.

**Comment by neolit123** [comment]
a better place to ask would be on the k8s support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

azure community support is here:
https://azure.microsoft.com/en-us/support/community/

/kind support
/close
