### ISSUE TITLE
what lead to my apiserver overloaded?

### ISSUE THREAD

**Issue by wiluen** [kubernetes/kubernetes#121845]
### What would you like to be added?

i deploy a VM based cluster, each VM is 8 core,16GB memory,I have 1 master and 7 nodes,I just use it for some simply experiments, recently ,apiserver is always overload, but I dont know why, in this picture,I dont run any program, dont send requests to apiserver , but it comsume many cpu, and if I used VSCODE to connect to the  master, apiserver is very very very overloaded, it's very wonder what affect my apiserver?
![1699712827979](https://github.com/kubernetes/kubernetes/assets/49629610/ecea4fbe-8c18-4de6-8db0-db0ff86240c7)

### Why is this needed?

I cant do anything

**Comment by neolit123** [comment]
a better place to ask would be on the support channels. please see:
https://git.k8s.io/kubernetes/SUPPORT.md

/kind support
/close
